Vangers: src/3d/3d_math.h File Reference
3d_math.h File Reference
Classes
struct Vector
struct Matrix
struct DBV
struct DBM
struct Quaternion
Macros
#define M_PI 3.14159265358979323846
#define DBL_EPS 1e-15
#define INT_INF 0x7FFFFFFF
#define SWAP(a, b) { *(int*)&a ^= int(b); *(int*)&b ^= int(a); *(int*)&a ^= int(b); }
#define SIGN(x) (x ? (x > 0 ? 1 : -1) : 0)
#define GOOD_SHR(x, n) ((x) < 0 ? -((-(x) + (1 << ((n) - 1))) >> (n)) : (((x) + (1 << ((n) - 1))) >> (n)))
#define DIV16(a, b) (a = ((a) << 16)/(b))
#define DIV16T(x, y) ((int)div_table_short[((x) & 0xFF) | (((y) << 8) & 0xFF00)] << 8)
#define MUL_CHAR(x, y) (mul_table[((x) & 0xFF) | (((y) << 8) & 0xFF00)])
#define random(num) ((int)(((long)_rand()*(num)) >> 15))
#define N_POWER_MAX 16
#define GTOR(x) (double(x)*(M_PI/double(Pi)))
#define RTOG(x) (round(x*(double(Pi)/M_PI)))
#define MUL(x, y) ((int)mul_table[(x & 0xFF) | ((y << 8) & 0xFF00)])
#define DIV_by_table(y, x) ((int)div_table[(x & 0xFF) | ((y << 8) & 0xFF00)])
#define POW(x, n) ((int)power_table[((n) - 2 << 8) + (x)])
#define DIAGONAL 1
#define EULER 2
#define EULER_INV 3
#define AROUND_EULER 4
#define AROUND_VECTOR 5
#define _psi_ x
#define _tetta_ y
#define _radius_ z
#define DECOMPOSITION(v_tangent, v_normal, v, axis) { v_tangent = (axis*(axis*v))/axis.abs2(); v_normal = v - v_tangent; }
Functions
int _rand (void)
void _srand (unsigned int seed)
double max (double x, double y)
double min (double x, double y)
int max (int x, int y)
int min (int x, int y)
int max (int x, int y, int z)
int min (int x, int y, int z)
int maxa (int x, int y)
int maxa (int x, int y, int z)
int mina (int x, int y)
int mina (int x, int y, int z)
double fmax (double x, double y)
double fmax (double x, double y, double z)
double fmaxa (double x, double y)
double fmaxa (double x, double y, double z)
double fmin (double x, double y)
double fmin (double x, double y, double z)
double fmina (double x, double y)
double fmina (double x, double y, double z)
int round_sin (int x)
int roundi (int x)
int DistPi (int s0, int s1)
double DistPIreal (double s0, double s1)
void make_tables ()
void write_tables ()
float Sin (int angle)
float Cos (int angle)
int ArcCos (int Dx, int Abs)
int Atan2 (int Dy, int Dx)
int Sqrt (int x)
Quaternion Slerp (const Quaternion &A, const Quaternion &B, double t)
Vector operator* (int w, const Vector &v)
Vector operator* (double w, const Vector &v)
Vector operator* (const DBM &m, const Vector &v)
DBV operator* (double w, const DBV &v)
DBV operator* (const DBM &m, const DBV &v)
DBM transpose (const DBM &m)
Variables
const int M_1_ = 32768
const int Pi_len = 11
const int Pi = 1 << Pi_len
const int ANGLE_MASK = 2*Pi - 1
const int ArcCosLen = 12
const int ArcCosMAX = 1 << ArcCosLen
const int ArcTanLen = 12
const int ArcTanMAX = 1 << ArcTanLen
const int SqrtLen = 12
const int SqrtMax = 1 << SqrtLen
float * cos_table
char * mul_table
short * div_table_short
char * power_table
const int X_AXIS = 0
const int Y_AXIS = 1
const int Z_AXIS = 2
Macro Definition Documentation
_psi_
#define _psi_ x
_radius_
#define _radius_ z
_tetta_
#define _tetta_ y
AROUND_EULER
#define AROUND_EULER 4
AROUND_VECTOR
#define AROUND_VECTOR 5
DBL_EPS
#define DBL_EPS 1e-15
DECOMPOSITION
#define DECOMPOSITION (v_tangent, v_normal, v, axis) { v_tangent = (axis*(axis*v))/axis.abs2(); v_normal = v - v_tangent; }
DIAGONAL
#define DIAGONAL 1
DIV16
#define DIV16 (a, b) (a = ((a) << 16)/(b))
DIV16T
#define DIV16T (x, y) ((int)div_table_short[((x) & 0xFF) | (((y) << 8) & 0xFF00)] << 8)
DIV_by_table
#define DIV_by_table (y, x) ((int)div_table[(x & 0xFF) | ((y << 8) & 0xFF00)])
EULER
#define EULER 2
EULER_INV
#define EULER_INV 3
GOOD_SHR
#define GOOD_SHR (x, n) ((x) < 0 ? -((-(x) + (1 << ((n) - 1))) >> (n)) : (((x) + (1 << ((n) - 1))) >> (n)))
GTOR
#define GTOR (x) (double(x)*(M_PI/double(Pi)))
INT_INF
#define INT_INF 0x7FFFFFFF
M_PI
#define M_PI 3.14159265358979323846
MUL
#define MUL (x, y) ((int)mul_table[(x & 0xFF) | ((y << 8) & 0xFF00)])
MUL_CHAR
#define MUL_CHAR (x, y) (mul_table[((x) & 0xFF) | (((y) << 8) & 0xFF00)])
N_POWER_MAX
#define N_POWER_MAX 16
POW
#define POW (x, n) ((int)power_table[((n) - 2 << 8) + (x)])
random
#define random (num) ((int)(((long)_rand()*(num)) >> 15))
RTOG
#define RTOG (x) (round(x*(double(Pi)/M_PI)))
SIGN
#define SIGN (x) (x ? (x > 0 ? 1 : -1) : 0)
SWAP
#define SWAP (a, b) { *(int*)&a ^= int(b); *(int*)&b ^= int(a); *(int*)&a ^= int(b); }
Function Documentation
_rand()
int _rand (void)
 {
     next = next * 1103515245 + 12345;
     return ((unsigned int) (next >> 16) & 0x7FFF);
 }
_srand()
void _srand (unsigned int seed)
 {
     next = seed;
 }
ArcCos()
int ArcCos (int Dx, int Abs)
 {
     if(!Abs)
         return 0;
     if(Dx >= 0){
         if(Dx >= Abs)
             return 0;
         return ArcCosTable[(((unsigned int )Dx) << ArcCosLen)/Abs];
         }
     else{
         if(-Dx >= Abs)
             return Pi;
         return Pi - ArcCosTable[(((unsigned int )-Dx) << ArcCosLen)/Abs];
         }
 }
References ArcCosLen, ArcCosTable, and Pi.
Referenced by Vector::descart2spherical(), Vector::spherical(), and Vector::tetta().
Atan2()
int Atan2 (int Dy, int Dx)
 {
     if(!Dx && !Dy)
         return 0;
     int Q = 0,S = 0;
     if(Dy >= 0){
         if(Dx < 0){
             Dx = -Dx;
             Q = Pi;
             S = 1;
             }
         }
     else
         if(Dx < 0){
             Dy = -Dy;
             Dx = -Dx;
             Q = Pi;
             }
         else{
             Dy = -Dy;
             Q = 2*Pi;
             S = 1;
             }
     unsigned int Ind;
     int Val;
     if(Dx >= Dy){
         Ind = Dy;
         Val = ArcTanTable[(Ind << ArcTanLen)/Dx];
         }
     else{
         Ind = Dx;
         Val = Pi/2 - ArcTanTable[(Ind << ArcTanLen)/Dy];
         }
     return Q + (S ? -Val : Val);
 }
References ArcTanLen, ArcTanTable, and Pi.
Referenced by Vector::descart2spherical(), Vector::psi(), and Vector::spherical().
Cos()
float Cos (int angle) inline
 { return cos_table[angle & ANGLE_MASK]; }
References ANGLE_MASK, and cos_table.
Referenced by Object::basic_mechous_analysis(), calc_view_factors(), CastArbitraryShadow(), ParticleObject::CreateDirectParticle(), WaterParticleObject::CreateParticle(), ParticleObject::CreateParticle(), DBM::DBM(), Vector::descart(), TrackUnit::DrawMechosParticle(), Object::get_max_jump_distance(), Object::impulse(), Object::jump(), Object::mechous_analysis(), HordeObject::Quant(), smart_putspr(), smart_putspr_f(), GameObjectDispatcher::Sort(), Vector::spherical(), and Vector::spherical2descart().
DistPi()
int DistPi (int s0, int s1)
 {
     s0 &= ANGLE_MASK;
     s1 &= ANGLE_MASK;
     int d0 = s0 - s1;
     int ad0 = abs(d0);
     int d1 = 2*Pi - ad0;
     if(ad0 < d1) return d0;
     return s0 > s1 ? -(2*Pi - s0 + s1) : 2*Pi - s1 + s0;
 }
References ANGLE_MASK, and Pi.
Referenced by camera_direct(), and camera_quant().
DistPIreal()
double DistPIreal (double s0, double s1)
fmax() [1/2]
double fmax (double x, double y) inline
 { return x > y ? x : y; }
Referenced by fmax().
fmax() [2/2]
double fmax (double x, double y, double z) inline
 { return fmax(fmax(x,y),z); }
References fmax().
fmaxa() [1/2]
double fmaxa (double x, double y) inline
 { return fabs(x) > fabs(y) ? x : y; }
Referenced by fmaxa().
fmaxa() [2/2]
double fmaxa (double x, double y, double z) inline
 { return fmaxa(fmaxa(x,y),z); }
References fmaxa().
fmin() [1/2]
double fmin (double x, double y) inline
 { return x < y ? x : y; }
Referenced by fmin().
fmin() [2/2]
double fmin (double x, double y, double z) inline
 { return fmin(fmin(x,y),z); }
References fmin().
fmina() [1/2]
double fmina (double x, double y) inline
 { return fabs(x) < fabs(y) ? x : y; }
Referenced by fmina().
fmina() [2/2]
double fmina (double x, double y, double z) inline
 { return fmina(fmina(x,y),z); }
References fmina().
make_tables()
void make_tables ()
 {
     int i;
     if(tables_are_made)
         return;
     tables_are_made = 1;
 #ifndef _STATIC_TABLES_
     int size = 2*Pi*sizeof(float) + ((ArcCosMAX + 1) + (ArcTanMAX + 1) + SqrtMax)*sizeof(short int);
     cos_table = ALLOC(size,float);
     ArcCosTable = (short unsigned int*)(cos_table + 2*Pi);
     ArcTanTable = ArcCosTable + ArcCosMAX + 1;
     SqrtTable = ArcTanTable + ArcTanMAX + 1;
     mul_table = new char[256*256];
     memset(mul_table, 0, 256*256);
     div_table_short = ALLOC(256*256,short);  // TODO uninitialised value(s)
     power_table = ALLOC(256*(N_POWER_MAX - 1),char);
 #endif
     for(i = 0;i < 2*Pi;i++)
         cos_table[i] = (float)cos(GTOR(i));
     for(i = 0;i <= ArcCosMAX;i++)
         ArcCosTable[i] = (int)(double(Pi)*acos(((double)i)/ArcCosMAX)/M_PI);
     for(i = 0;i <= ArcTanMAX;i++)
         ArcTanTable[i] = (int)(double(Pi)*atan(((double)i)/ArcTanMAX)/M_PI);
     for(i = 0;i < SqrtMax;i++)
         SqrtTable[i] = (int)(sqrt((double)i) + .5);
     int x,y;
     for(x = -127;x <= 127;x++){
         for(y = -127;y <= 127;y++)
             mul_table[(x & 0xFF) | ((y << 8) & 0xFF00)] = GOOD_SHR(x*y,7);
         for(y = 0;y <= 255;y++){
             div_table_short[(x & 0xFF) | ((y << 8) & 0xFF00)] = y ? (x << 8)/y : 0;
             }
         }
     int n;
     for(n = 2;n <= N_POWER_MAX;n++){
         for(x = -127;x <= 127;x++){
             y = x;
             for(i = 1;i < n;i++)
                 y = GOOD_SHR(y*x,7);
             power_table[((n - 2) << 8) + (x & 0xFF)] = y;
             }
         }
 }
References ALLOC, ArcCosMAX, ArcCosTable, ArcTanMAX, ArcTanTable, cos_table, div_table_short, GOOD_SHR, GTOR, M_PI, mul_table, N_POWER_MAX, Pi, power_table, SqrtMax, SqrtTable, and tables_are_made.
Referenced by graph3d_init().
max() [1/3]
double max (double x, double y) inline
 { return x > y ? x : y; }
Referenced by Vector::BitSR(), and max().
max() [2/3]
int max (int x, int y) inline
 { return x > y ? x : y; }
max() [3/3]
int max (int x, int y, int z) inline
 { return max(max(x,y),z); }
References max().
maxa() [1/2]
int maxa (int x, int y) inline
 { return abs(x) > abs(y) ? x : y; }
Referenced by maxa().
maxa() [2/2]
int maxa (int x, int y, int z) inline
 { return maxa(maxa(x,y),z); }
References maxa().
min() [1/3]
double min (double x, double y) inline
 { return x < y ? x : y; }
Referenced by min().
min() [2/3]
int min (int x, int y) inline
 { return x < y ? x : y; }
min() [3/3]
int min (int x, int y, int z) inline
 { return min(min(x,y),z); }
References min().
mina() [1/2]
int mina (int x, int y) inline
 { return abs(x) < abs(y) ? x : y; }
Referenced by mina().
mina() [2/2]
int mina (int x, int y, int z) inline
 { return mina(mina(x,y),z); }
References mina().
operator*() [1/5]
DBV operator* (const DBM & m, const DBV & v) inline
 {
     return DBV (m.a[0]*v.x + m.a[1]*v.y + m.a[2]*v.z,
              m.a[3]*v.x + m.a[4]*v.y + m.a[5]*v.z,
              m.a[6]*v.x + m.a[7]*v.y + m.a[8]*v.z);
 }
References DBM::a, DBV::x, DBV::y, and DBV::z.
operator*() [2/5]
Vector operator* (const DBM & m, const Vector & v) inline
 {
     return Vector(
         round(m.a[0]*v.x + m.a[1]*v.y + m.a[2]*v.z),
         round(m.a[3]*v.x + m.a[4]*v.y + m.a[5]*v.z),
         round(m.a[6]*v.x + m.a[7]*v.y + m.a[8]*v.z));
 }
References DBM::a, round(), Vector::x, Vector::y, and Vector::z.
operator*() [3/5]
DBV operator* (double w, const DBV & v) inline
 {
     return DBV(v.x*w, v.y*w, v.z*w);
 }
References DBV::x, DBV::y, and DBV::z.
operator*() [4/5]
Vector operator* (double w, const Vector & v) inline
 {
     return Vector(round(v.x*w), round(v.y*w), round(v.z*w));
 }
References round(), Vector::x, Vector::y, and Vector::z.
operator*() [5/5]
Vector operator* (int w, const Vector & v) inline
 {
     return Vector(v.x*w, v.y*w, v.z*w);
 }
References Vector::x, Vector::y, and Vector::z.
round_sin()
int round_sin (int x) inline
 { return x >= 0 ? (x + (1 << 14)) >> 15 : -((-x + (1 << 14)) >> 15); }
roundi()
int roundi (int x) inline
 { return x >= 0 ? (x + (1 << 14)) >> 15 : -((-x + (1 << 14)) >> 15); }
Sin()
float Sin (int angle) inline
 { return cos_table[(angle - Pi/2) & ANGLE_MASK]; }
References ANGLE_MASK, cos_table, and Pi.
Referenced by Object::basic_mechous_analysis(), calc_view_factors(), CastArbitraryShadow(), ParticleObject::CreateDirectParticle(), WaterParticleObject::CreateParticle(), DBM::DBM(), Vector::descart(), TrackUnit::DrawMechosParticle(), StuffObject::DrawQuant(), HordeSource::DrawQuant(), Object::get_max_jump_distance(), Object::impulse(), Object::jump(), LinkDist(), Object::mechous_analysis(), PointDist(), HordeObject::Quant(), GameObjectDispatcher::Sort(), Vector::spherical(), and Vector::spherical2descart().
Slerp()
Quaternion Slerp (const Quaternion & A, const Quaternion & B, double t)
 {
     double pre_theta = A*B;
     if (fabs(pre_theta) > 1.0) {
         return A;
     }
     double theta = acos(pre_theta);
     double sin_theta = sin(theta);
     if(fabs(sin_theta) < DBL_EPS) {
         return A;
     }
     sin_theta = 1/sin_theta;
     return A*(sin(theta*(1 - t))*sin_theta) + B*(sin(theta* t)*sin_theta);
 }
References DBL_EPS.
Sqrt()
int Sqrt (int x)
 {
     if(x < 0)
         x = 0;
     int len = BitSR(x);
     if(len >= SqrtLen){
         int shift = len - SqrtLen + 1;
         if(shift & 1)
             shift++;
         return SqrtTable[x >> shift] << (shift >> 1);
         }
     return SqrtTable[x];
 }
References BitSR(), SqrtLen, and SqrtTable.
transpose()
DBM transpose (const DBM & m) inline
 {
     return DBM(m[0],m[3],m[6],
                 m[1],m[4],m[7],
                 m[2],m[5],m[8]);
 }
Referenced by Object::basic_debris_analysis(), Object::basic_mechous_analysis(), Object::draw(), Object::fish_analysis(), Object::ground_pressing(), Object::insect_analysis(), Object::NetEvent(), and Object::skyfarmer_analysis().
write_tables()
void write_tables ()
Variable Documentation
ANGLE_MASK
const int ANGLE_MASK = 2*Pi - 1
Referenced by Cos(), DistPi(), and Sin().
ArcCosLen
const int ArcCosLen = 12
Referenced by ArcCos().
ArcCosMAX
const int ArcCosMAX = 1 << ArcCosLen
Referenced by make_tables().
ArcTanLen
const int ArcTanLen = 12
Referenced by Atan2().
ArcTanMAX
const int ArcTanMAX = 1 << ArcTanLen
Referenced by make_tables().
cos_table
float* cos_table extern
Referenced by Cos(), make_tables(), and Sin().
div_table_short
short* div_table_short extern
Referenced by make_tables().
M_1_
const int M_1_ = 32768
mul_table
char* mul_table extern
Referenced by make_tables().
Pi
const int Pi = 1 << Pi_len
Referenced by uvsShop::addItem(), ArcCos(), Atan2(), SkyFarmerObject::CreateSkyFarmer(), DistPi(), Object::get_max_jump_distance(), Object::jump(), make_tables(), and Sin().
Pi_len
const int Pi_len = 11
power_table
char* power_table extern
Referenced by Normal::fast_calc_intensity(), and make_tables().
SqrtLen
const int SqrtLen = 12
Referenced by Sqrt().
SqrtMax
const int SqrtMax = 1 << SqrtLen
Referenced by make_tables().
X_AXIS
const int X_AXIS = 0
Referenced by DBM::DBM().
Y_AXIS
const int Y_AXIS = 1
Referenced by DBM::DBM().
Z_AXIS
const int Z_AXIS = 2
Referenced by DBM::DBM().