Vangers: src/3d/3d_math.cpp File Reference
3d_math.cpp File Reference
#include "../global.h"
#include "general.h"
Functions
void make_tables ()
int ArcCos (int Dx, int Abs)
int Atan2 (int Dy, int Dx)
int Sqrt (int x)
int DistPi (int s0, int s1)
double DistPI (double s0, double s1)
int _rand (void)
void _srand (unsigned int seed)
XStream & operator<= (XStream &s, const Vector &v)
XStream & operator>= (XStream &s, Vector &v)
XStream & operator< (XStream &s, Vector &v)
XStream & operator> (XStream &s, Vector &v)
XBuffer & operator<= (XBuffer &b, const Vector &v)
XBuffer & operator>= (XBuffer &b, Vector &v)
XBuffer & operator< (XBuffer &b, const Vector &v)
XBuffer & operator> (XBuffer &b, Vector &v)
XStream & operator<= (XStream &s, const DBV &v)
XStream & operator>= (XStream &s, DBV &v)
XStream & operator< (XStream &s, DBV &v)
XStream & operator> (XStream &s, DBV &v)
XBuffer & operator<= (XBuffer &b, const DBV &v)
XBuffer & operator>= (XBuffer &b, DBV &v)
XBuffer & operator< (XBuffer &b, const DBV &v)
XBuffer & operator> (XBuffer &b, DBV &v)
XStream & operator<= (XStream &s, const DBM &m)
XStream & operator>= (XStream &s, DBM &m)
XStream & operator< (XStream &s, DBM &m)
XStream & operator> (XStream &s, DBM &m)
XBuffer & operator<= (XBuffer &b, const DBM &m)
XBuffer & operator>= (XBuffer &b, DBM &m)
XBuffer & operator< (XBuffer &b, const DBM &m)
XBuffer & operator> (XBuffer &b, DBM &m)
Quaternion operator* (double s, const Quaternion &q)
Quaternion Slerp (const Quaternion &A, const Quaternion &B, double t)
XStream & operator<= (XStream &s, const Quaternion &q)
XStream & operator>= (XStream &s, Quaternion &q)
XStream & operator< (XStream &s, Quaternion &q)
XStream & operator> (XStream &s, Quaternion &q)
XBuffer & operator<= (XBuffer &b, const Quaternion &q)
XBuffer & operator>= (XBuffer &b, Quaternion &q)
XBuffer & operator< (XBuffer &b, const Quaternion &q)
XBuffer & operator> (XBuffer &b, Quaternion &q)
Variables
short unsigned int * ArcCosTable
short unsigned int * ArcTanTable
short unsigned int * SqrtTable
float * cos_table
char * mul_table
short * div_table_short
char * power_table
int tables_are_made = 0
Function Documentation
_rand()
int _rand (void)
 {
     next = next * 1103515245 + 12345;
     return ((unsigned int) (next >> 16) & 0x7FFF);
 }
_srand()
void _srand (unsigned int seed)
 {
     next = seed;
 }
ArcCos()
int ArcCos (int Dx, int Abs)
 {
     if(!Abs)
         return 0;
     if(Dx >= 0){
         if(Dx >= Abs)
             return 0;
         return ArcCosTable[(((unsigned int )Dx) << ArcCosLen)/Abs];
         }
     else{
         if(-Dx >= Abs)
             return Pi;
         return Pi - ArcCosTable[(((unsigned int )-Dx) << ArcCosLen)/Abs];
         }
 }
References ArcCosLen, ArcCosTable, and Pi.
Referenced by Vector::descart2spherical(), Vector::spherical(), and Vector::tetta().
Atan2()
int Atan2 (int Dy, int Dx)
 {
     if(!Dx && !Dy)
         return 0;
     int Q = 0,S = 0;
     if(Dy >= 0){
         if(Dx < 0){
             Dx = -Dx;
             Q = Pi;
             S = 1;
             }
         }
     else
         if(Dx < 0){
             Dy = -Dy;
             Dx = -Dx;
             Q = Pi;
             }
         else{
             Dy = -Dy;
             Q = 2*Pi;
             S = 1;
             }
     unsigned int Ind;
     int Val;
     if(Dx >= Dy){
         Ind = Dy;
         Val = ArcTanTable[(Ind << ArcTanLen)/Dx];
         }
     else{
         Ind = Dx;
         Val = Pi/2 - ArcTanTable[(Ind << ArcTanLen)/Dy];
         }
     return Q + (S ? -Val : Val);
 }
References ArcTanLen, ArcTanTable, and Pi.
Referenced by Vector::descart2spherical(), Vector::psi(), and Vector::spherical().
DistPI()
double DistPI (double s0, double s1)
 {
     s0 = asin(sin(s0));
     s1 = asin(sin(s1));
     double d0 = s0 - s1;
     double ad0 = fabs(d0);
     double d1 = 2*M_PI - ad0;
     if(ad0 < d1) return d0;
     return s0 > s1 ? -(2*M_PI - s0 + s1) : 2*M_PI - s1 + s0;
 }
References M_PI.
DistPi()
int DistPi (int s0, int s1)
 {
     s0 &= ANGLE_MASK;
     s1 &= ANGLE_MASK;
     int d0 = s0 - s1;
     int ad0 = abs(d0);
     int d1 = 2*Pi - ad0;
     if(ad0 < d1) return d0;
     return s0 > s1 ? -(2*Pi - s0 + s1) : 2*Pi - s1 + s0;
 }
References ANGLE_MASK, and Pi.
Referenced by camera_direct(), and camera_quant().
make_tables()
void make_tables ()
 {
     int i;
     if(tables_are_made)
         return;
     tables_are_made = 1;
 #ifndef _STATIC_TABLES_
     int size = 2*Pi*sizeof(float) + ((ArcCosMAX + 1) + (ArcTanMAX + 1) + SqrtMax)*sizeof(short int);
     cos_table = ALLOC(size,float);
     ArcCosTable = (short unsigned int*)(cos_table + 2*Pi);
     ArcTanTable = ArcCosTable + ArcCosMAX + 1;
     SqrtTable = ArcTanTable + ArcTanMAX + 1;
     mul_table = new char[256*256];
     memset(mul_table, 0, 256*256);
     div_table_short = ALLOC(256*256,short);  // TODO uninitialised value(s)
     power_table = ALLOC(256*(N_POWER_MAX - 1),char);
 #endif
     for(i = 0;i < 2*Pi;i++)
         cos_table[i] = (float)cos(GTOR(i));
     for(i = 0;i <= ArcCosMAX;i++)
         ArcCosTable[i] = (int)(double(Pi)*acos(((double)i)/ArcCosMAX)/M_PI);
     for(i = 0;i <= ArcTanMAX;i++)
         ArcTanTable[i] = (int)(double(Pi)*atan(((double)i)/ArcTanMAX)/M_PI);
     for(i = 0;i < SqrtMax;i++)
         SqrtTable[i] = (int)(sqrt((double)i) + .5);
     int x,y;
     for(x = -127;x <= 127;x++){
         for(y = -127;y <= 127;y++)
             mul_table[(x & 0xFF) | ((y << 8) & 0xFF00)] = GOOD_SHR(x*y,7);
         for(y = 0;y <= 255;y++){
             div_table_short[(x & 0xFF) | ((y << 8) & 0xFF00)] = y ? (x << 8)/y : 0;
             }
         }
     int n;
     for(n = 2;n <= N_POWER_MAX;n++){
         for(x = -127;x <= 127;x++){
             y = x;
             for(i = 1;i < n;i++)
                 y = GOOD_SHR(y*x,7);
             power_table[((n - 2) << 8) + (x & 0xFF)] = y;
             }
         }
 }
References ALLOC, ArcCosMAX, ArcCosTable, ArcTanMAX, ArcTanTable, cos_table, div_table_short, GOOD_SHR, GTOR, M_PI, mul_table, N_POWER_MAX, Pi, power_table, SqrtMax, SqrtTable, and tables_are_made.
Referenced by graph3d_init().
operator*()
Quaternion operator* (double s, const Quaternion & q)
 {
     return Quaternion(q.w*s,q.x*s,q.y*s,q.z*s);
 }
References Quaternion::w, Quaternion::x, Quaternion::y, and Quaternion::z.
operator<() [1/8]
XBuffer& operator< (XBuffer & b, const DBM & m)
 {
     b < m.a[0] < m.a[1] < m.a[2];
     b < m.a[3] < m.a[4] < m.a[5];
     b < m.a[6] < m.a[7] < m.a[8];
     return b;
 }
References DBM::a.
operator<() [2/8]
XBuffer& operator< (XBuffer & b, const DBV & v)
 {
     b < v.x < v.y < v.z;
     return b;
 }
References DBV::x, DBV::y, and DBV::z.
operator<() [3/8]
XBuffer& operator< (XBuffer & b, const Quaternion & q)
 {
     b < q.w < q.x < q.y < q.z;
     return b;
 }
References Quaternion::w, Quaternion::x, Quaternion::y, and Quaternion::z.
operator<() [4/8]
XBuffer& operator< (XBuffer & b, const Vector & v)
 {
     b < v.x < v.y < v.z;
     return b;
 }
References Vector::x, Vector::y, and Vector::z.
operator<() [5/8]
XStream& operator< (XStream & s, DBM & m)
 {
     s.write(&m,sizeof(DBM));
     return s;
 }
References XStream::write().
operator<() [6/8]
XStream& operator< (XStream & s, DBV & v)
 {
     s.write(&v,sizeof(DBV));
     return s;
 }
References XStream::write().
operator<() [7/8]
XStream& operator< (XStream & s, Quaternion & q)
 {
     s.write(&q,sizeof(Quaternion));
     return s;
 }
References XStream::write().
operator<() [8/8]
XStream& operator< (XStream & s, Vector & v)
 {
     s.write(&v,sizeof(Vector));
     return s;
 }
References XStream::write().
operator<=() [1/8]
XBuffer& operator<= (XBuffer & b, const DBM & m)
 {
     b <= m.a[0] < " \t" <= m.a[1] < " \t" <= m.a[2] < "\n";
     b <= m.a[3] < " \t" <= m.a[4] < " \t" <= m.a[5] < "\n";
     b <= m.a[6] < " \t" <= m.a[7] < " \t" <= m.a[8] < "\n";
     return b;
 }
References DBM::a.
operator<=() [2/8]
XBuffer& operator<= (XBuffer & b, const DBV & v)
 {
     b <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return b;
 }
References DBV::x, DBV::y, and DBV::z.
operator<=() [3/8]
XBuffer& operator<= (XBuffer & b, const Quaternion & q)
 {
     b <= q.w < " \t\t"  <= q.x < " \t" <= q.y < " \t" <= q.z < "\n";
     return b;
 }
References Quaternion::w, Quaternion::x, Quaternion::y, and Quaternion::z.
operator<=() [4/8]
XBuffer& operator<= (XBuffer & b, const Vector & v)
 {
     b <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return b;
 }
References Vector::x, Vector::y, and Vector::z.
operator<=() [5/8]
XStream& operator<= (XStream & s, const DBM & m)
 {
     s <= m.a[0] < " \t" <= m.a[1] < " \t" <= m.a[2] < "\n";
     s <= m.a[3] < " \t" <= m.a[4] < " \t" <= m.a[5] < "\n";
     s <= m.a[6] < " \t" <= m.a[7] < " \t" <= m.a[8] < "\n";
     return s;
 }
References DBM::a.
operator<=() [6/8]
XStream& operator<= (XStream & s, const DBV & v)
 {
     s <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return s;
 }
References DBV::x, DBV::y, and DBV::z.
operator<=() [7/8]
XStream& operator<= (XStream & s, const Quaternion & q)
 {
     s <= q.w < " \t\t"  <= q.x < " \t" <= q.y < " \t" <= q.z < "\n";
     return s;
 }
References Quaternion::w, Quaternion::x, Quaternion::y, and Quaternion::z.
operator<=() [8/8]
XStream& operator<= (XStream & s, const Vector & v)
 {
     s <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return s;
 }
References Vector::x, Vector::y, and Vector::z.
operator>() [1/8]
XBuffer& operator> (XBuffer & b, DBM & m)
 {
     b > m.a[0] > m.a[1] > m.a[2];
     b > m.a[3] > m.a[4] > m.a[5];
     b > m.a[6] > m.a[7] > m.a[8];
     return b;
 }
References DBM::a.
operator>() [2/8]
XBuffer& operator> (XBuffer & b, DBV & v)
 {
     b > v.x > v.y > v.z;
     return b;
 }
References DBV::x, DBV::y, and DBV::z.
operator>() [3/8]
XBuffer& operator> (XBuffer & b, Quaternion & q)
 {
     b > q.w > q.x > q.y > q.z;
     return b;
 }
References Quaternion::w, Quaternion::x, Quaternion::y, and Quaternion::z.
operator>() [4/8]
XBuffer& operator> (XBuffer & b, Vector & v)
 {
     b > v.x > v.y > v.z;
     return b;
 }
References Vector::x, Vector::y, and Vector::z.
operator>() [5/8]
XStream& operator> (XStream & s, DBM & m)
 {
     s.read(&m,sizeof(DBM));
     return s;
 }
References XStream::read().
operator>() [6/8]
XStream& operator> (XStream & s, DBV & v)
 {
     s.read(&v,sizeof(DBV));
     return s;
 }
References XStream::read().
operator>() [7/8]
XStream& operator> (XStream & s, Quaternion & q)
 {
     s.read(&q,sizeof(Quaternion));
     return s;
 }
References XStream::read().
operator>() [8/8]
XStream& operator> (XStream & s, Vector & v)
 {
     s.read(&v,sizeof(Vector));
     return s;
 }
References XStream::read().
operator>=() [1/8]
XBuffer& operator>= (XBuffer & b, DBM & m)
 {
     b >= m.a[0] >= m.a[1] >= m.a[2];
     b >= m.a[3] >= m.a[4] >= m.a[5];
     b >= m.a[6] >= m.a[7] >= m.a[8];
     return b;
 }
References DBM::a.
operator>=() [2/8]
XBuffer& operator>= (XBuffer & b, DBV & v)
 {
     b >= v.x >= v.y >= v.z;
     return b;
 }
References DBV::x, DBV::y, and DBV::z.
operator>=() [3/8]
XBuffer& operator>= (XBuffer & b, Quaternion & q)
 {
     b >= q.w >= q.x >= q.y >= q.z;
     return b;
 }
References Quaternion::w, Quaternion::x, Quaternion::y, and Quaternion::z.
operator>=() [4/8]
XBuffer& operator>= (XBuffer & b, Vector & v)
 {
     b >= v.x >= v.y >= v.z;
     return b;
 }
References Vector::x, Vector::y, and Vector::z.
operator>=() [5/8]
XStream& operator>= (XStream & s, DBM & m)
 {
     s >= m.a[0] >= m.a[1] >= m.a[2];
     s >= m.a[3] >= m.a[4] >= m.a[5];
     s >= m.a[6] >= m.a[7] >= m.a[8];
     return s;
 }
References DBM::a.
operator>=() [6/8]
XStream& operator>= (XStream & s, DBV & v)
 {
     s >= v.x >= v.y >= v.z;
     return s;
 }
References DBV::x, DBV::y, and DBV::z.
operator>=() [7/8]
XStream& operator>= (XStream & s, Quaternion & q)
 {
     s >= q.w >= q.x >= q.y >= q.z;
     return s;
 }
References Quaternion::w, Quaternion::x, Quaternion::y, and Quaternion::z.
operator>=() [8/8]
XStream& operator>= (XStream & s, Vector & v)
 {
     s >= v.x >= v.y >= v.z;
     return s;
 }
References Vector::x, Vector::y, and Vector::z.
Slerp()
Quaternion Slerp (const Quaternion & A, const Quaternion & B, double t)
 {
     double pre_theta = A*B;
     if (fabs(pre_theta) > 1.0) {
         return A;
     }
     double theta = acos(pre_theta);
     double sin_theta = sin(theta);
     if(fabs(sin_theta) < DBL_EPS) {
         return A;
     }
     sin_theta = 1/sin_theta;
     return A*(sin(theta*(1 - t))*sin_theta) + B*(sin(theta* t)*sin_theta);
 }
References DBL_EPS.
Sqrt()
int Sqrt (int x)
 {
     if(x < 0)
         x = 0;
     int len = BitSR(x);
     if(len >= SqrtLen){
         int shift = len - SqrtLen + 1;
         if(shift & 1)
             shift++;
         return SqrtTable[x >> shift] << (shift >> 1);
         }
     return SqrtTable[x];
 }
References BitSR(), SqrtLen, and SqrtTable.
Variable Documentation
ArcCosTable
short unsigned int* ArcCosTable
Referenced by ArcCos(), and make_tables().
ArcTanTable
short unsigned int* ArcTanTable
Referenced by Atan2(), and make_tables().
cos_table
float* cos_table
Referenced by Cos(), make_tables(), and Sin().
div_table_short
short* div_table_short
Referenced by make_tables().
mul_table
char* mul_table
Referenced by make_tables().
power_table
char* power_table
Referenced by Normal::fast_calc_intensity(), and make_tables().
SqrtTable
short unsigned int* SqrtTable
Referenced by make_tables(), and Sqrt().
tables_are_made
int tables_are_made = 0
Referenced by make_tables().