Vangers: lib/xsound/_xsound.h File Reference
_xsound.h File Reference
#include <clunk/clunk.h>
Macros
#define DS_LOOPING 0x00000001
#define DS_QUEUE 0x00000100
#define DS_STREAM 0x00000200
#define AVI_LOOPING DS_LOOPING
#define AVI_DRAW 0x00100000
#define AVI_END 0x00200000
#define AVI_NOTIMER 0x00400000
#define AVI_NODRAW 0x00800000
#define AVI_INTERPOLATE 0x01000000
#define AVI_NOPALETTE 0x02000000
#define DIG_F_MONO_8 0
#define DIG_F_MONO_16 1
#define DIG_F_STEREO_8 2
#define DIG_F_STEREO_16 3
#define PLAYBACK_TIMER_PERIOD 200
#define PLAYBACK_OVERSAMPLE 4
#define PLAYBACK_TIMER_ACCURACY 10
#define NUM_BUFFER_SEGMENTS 4
#define SoundStreamPlay(lpDSB, channel, priority, cropos, flags) SoundPlay(lpDSB, channel, priority, cropos, flags | DS_STREAM)
#define XCD_NOT_READY 0x00
#define XCD_PAUSED 0x01
#define XCD_PLAYING 0x02
#define XCD_STOPPED 0x03
#define XCD_OTHER 0x04
Functions
int SoundInit (int maxHZ, int channels)
void SoundPlay (void *lpDSB, int channel, int priority, int cropos, int flags)
void SoundRelease (void *lpDSB)
void SoundStop (int channel)
void * GetSound (int channel)
void SoundLoad (char *filename, void **lpDSB)
void SoundFinit (void)
void SoundVolume (int channel, int volume)
void SetVolume (void *lpDSB, int volume)
int GetVolume (void *lpDSB)
int GetSoundVolume (int channel)
void GlobalVolume (int volume)
void SoundPan (int channel, int panning)
int GetSoundFrequency (void *lpDSB)
void SetSoundFrequency (void *lpDSB, int frq)
void SoundStreamOpen (char *filename, void **strptr)
void SoundStreamClose (void *stream)
void SoundStreamRelease (void *stream)
int AVIopen (char *filename, int flags, int channel, void **avi)
void AVIplay (void *avi, int x, int y)
void AVIstop (void *avi)
void AVIclose (void *avi)
int AVIwidth (void *avi)
int AVIheight (void *avi)
int AVIredraw (void *avi)
void AVIredraw (void *avi, int state)
void AVIdraw (void *avi)
void AVIGetData (void *avi, void *data)
void * AVIGetPalette (void *avi)
void xsInitCD (void)
void xsPlayCD (int track, int min=0, int sec=0)
void xsPlayOneTrackCD (int track, int min=0, int sec=0)
void xsStopCD (void)
void xsPauseCD (void)
void xsResumeCD (void)
int xsGetStatusCD (void)
int xsGetCurTrackCD (void)
int xsGetNumTracksCD (void)
int xsGetTrackLenCD (int track)
void xsMixerOpen (void)
int xsGetVolumeCD (void)
void xsSetVolumeCD (int val)
int xsGetVolumeWAVE (void)
void xsSetVolumeWAVE (int val)
Macro Definition Documentation
AVI_DRAW
#define AVI_DRAW 0x00100000
AVI_END
#define AVI_END 0x00200000
AVI_INTERPOLATE
#define AVI_INTERPOLATE 0x01000000
AVI_LOOPING
#define AVI_LOOPING DS_LOOPING
AVI_NODRAW
#define AVI_NODRAW 0x00800000
AVI_NOPALETTE
#define AVI_NOPALETTE 0x02000000
AVI_NOTIMER
#define AVI_NOTIMER 0x00400000
DIG_F_MONO_16
#define DIG_F_MONO_16 1
DIG_F_MONO_8
#define DIG_F_MONO_8 0
DIG_F_STEREO_16
#define DIG_F_STEREO_16 3
DIG_F_STEREO_8
#define DIG_F_STEREO_8 2
DS_LOOPING
#define DS_LOOPING 0x00000001
DS_QUEUE
#define DS_QUEUE 0x00000100
DS_STREAM
#define DS_STREAM 0x00000200
NUM_BUFFER_SEGMENTS
#define NUM_BUFFER_SEGMENTS 4
PLAYBACK_OVERSAMPLE
#define PLAYBACK_OVERSAMPLE 4
PLAYBACK_TIMER_ACCURACY
#define PLAYBACK_TIMER_ACCURACY 10
PLAYBACK_TIMER_PERIOD
#define PLAYBACK_TIMER_PERIOD 200
SoundStreamPlay
#define SoundStreamPlay (lpDSB, channel, priority, cropos, flags) SoundPlay(lpDSB, channel, priority, cropos, flags | DS_STREAM)
XCD_NOT_READY
#define XCD_NOT_READY 0x00
XCD_OTHER
#define XCD_OTHER 0x04
XCD_PAUSED
#define XCD_PAUSED 0x01
XCD_PLAYING
#define XCD_PLAYING 0x02
XCD_STOPPED
#define XCD_STOPPED 0x03
Function Documentation
AVIclose()
void AVIclose (void * avi)
 {
     AVIFile* p = (AVIFile*)avi;
     aviXList.RemoveElement((XListElement*)p);
     delete p;
 }
Referenced by iAVIElement::free(), and iScreenObject::init().
AVIdraw()
void AVIdraw (void * avi)
 {
     ((AVIFile *)avi) -> draw();
 }
References AVIFile::draw().
Referenced by iScreenElement::redraw().
AVIGetData()
void AVIGetData (void * avi, void * data)
 {
     XCriticalSection critical(((AVIFile *)avi) -> avCriticalSection);
     int xs = AVIwidth(avi);
     int ys = AVIheight(avi);
     int i, i2;
     if (((AVIFile *)avi)->pFrame)
         for(i=0; i<ys; ++i){
             for (i2=0;i2<xs;++i2){
                 ((unsigned char *)data)[i*xs+i2]=
                 ((unsigned char *)((AVIFile *)avi)->pFrame->data[0])[i*((AVIFile *)avi)->pFrame->linesize[0]+i2];
             }
         }
 }
References AVIFile::avCriticalSection, AVIheight(), AVIwidth(), and AVIFile::pFrame.
Referenced by iScreenElement::redraw().
AVIGetPalette()
void* AVIGetPalette (void * avi)
 {
     XCriticalSection critical(((AVIFile *)avi) -> avCriticalSection);
     return ((AVIFile *)avi) -> palette;
 }
References AVIFile::avCriticalSection, and AVIFile::palette.
Referenced by iAVIElement::load().
AVIheight()
int AVIheight (void * avi)
 {
     return ((AVIFile *)avi) -> height;
 }
References AVIFile::height.
Referenced by AVIGetData(), iScreenObject::init(), and iAVIElement::init_size().
AVIopen()
int AVIopen (char * filename, int flags, int channel, void ** avi)
 {
     AVIFile *newavi = new AVIFile;
     if(!newavi -> open(filename,flags,channel))
         return 0;
     *avi = newavi;
     aviXList.AddElement((XListElement*)newavi);
     xtRegisterSysFinitFnc(FinitAVI,XAVI_SYSOBJ_ID);
     return 1;
 }
References AVIFile::AVIFile(), AVIFile::filename, AVIFile::flags, and AVIFile::open().
Referenced by iScreenObject::init(), and iAVIElement::load().
AVIplay()
void AVIplay (void * avi, int x, int y)
 {
     ((AVIFile *)avi) -> pause = 0;
     ((AVIFile *)avi) -> x = xx;
     ((AVIFile *)avi) -> y = yy;
 }
References AVIFile::pause, AVIFile::x, and AVIFile::y.
Referenced by iAVIElement::load().
AVIredraw() [1/2]
int AVIredraw (void * avi)
 {
     return ((AVIFile *)avi) -> redraw;
 }
References AVIFile::redraw.
AVIredraw() [2/2]
void AVIredraw (void * avi, int state)
 {
     ((AVIFile *)avi) -> redraw = state;
 }
References AVIFile::redraw.
AVIstop()
void AVIstop (void * avi)
 {
     ((AVIFile *)avi) -> pause = 1;
 }
References AVIFile::pause.
Referenced by iAVIElement::free().
AVIwidth()
int AVIwidth (void * avi)
 {
     return ((AVIFile *)avi) -> width;
 }
References AVIFile::width.
Referenced by AVIGetData(), iScreenObject::init(), and iAVIElement::init_size().
GetSound()
void* GetSound (int channel)
 {
     //std::cout<<"GetSound:"<<((clunk::Sample *)channels[channel].sound)->name<<" channel:"<<channel<<std::endl;
     if(XSoundInitFlag)
         return channels[channel].sound;
     return NULL;
 }
References XSoundInitFlag.
GetSoundFrequency()
int GetSoundFrequency (void * lpDSB)
 {
     //std::cout<<"Get SoundFrequency"<<((clunk::Sample *)lpDSB)->name<<std::endl;
     unsigned long ret = 0;
     if(XSoundInitFlag){
         /*int numtimesopened, frequency, channels;
         Uint16 format;
         SDL_Mixer Version
         numtimesopened=Mix_QuerySpec(&frequency, &format, &channels);
         ret = frequency;*/
         //ret = g_freq;
         ret = ((clunk::Sample *)lpDSB)->pitch*22050;
     }
     return ret;
 }
References XSoundInitFlag.
GetSoundVolume()
int GetSoundVolume (int channel)
 {
     int volume = 0;
     if(XSoundInitFlag){
         std::cout<<"GetSoundVolume:"<<channel<<std::endl;
         if(channels[channel].sound)
             volume = channels[channel].volume;
     }
     return volume;
 }
GetVolume()
int GetVolume (void * lpDSB)
 {
     int ret = 0;
     if(XSoundInitFlag){
         /* SDL_Mixer Version
         ret = Mix_VolumeChunk((Mix_Chunk *)lpDSB, 0);
         Mix_VolumeChunk((Mix_Chunk *)lpDSB, ret);*/
         ret = ((clunk::Sample *)lpDSB)->gain*256;
     }
     return ret;
 }
References XSoundInitFlag.
GlobalVolume()
void GlobalVolume (int volume)
 {
     int i;
     std::cout<<"GlobalVolume:"<<volume<<std::endl;
     for(i = 0; i < MAX_CHANNELS; i ++)
         SoundVolume(i, volume);
 }
SetSoundFrequency()
void SetSoundFrequency (void * lpDSB, int frq)
 {
     //std::cout<<"SetSoundFrequency:"<<((clunk::Sample *)lpDSB)->name<<" frq:"<<frq<<std::endl;
     if(XSoundInitFlag){
         float out_pitch = frq;
         out_pitch/=22050;
         //std::cout<<"pitch:"<<out_pitch<<" freq:"<<((clunk::Sample *)lpDSB)->spec.freq<<std::endl;
         ((clunk::Sample *)lpDSB)->pitch = out_pitch;
     }
 }
References XSoundInitFlag.
SetVolume()
void SetVolume (void * lpDSB, int volume)
 {
     /* SDL_Mixer Version
     volume+=10000;
     volume*=0.0128;*/
     /* OLD system
     float f_volume = volume + 10000;
     f_volume *= 0.0001;*/
     //std::cout<<"SetVolume lpDSB f_volume:"<<volume/256.0<<" volume:"<<volume<<std::endl;
     ((clunk::Sample *)lpDSB)->gain=volume/256.0;
     /* SDL_Mixer Version */
     /*if(XSoundInitFlag){
         Mix_VolumeChunk((Mix_Chunk *)lpDSB, volume);
     }*/
 }
SoundFinit()
void SoundFinit (void)
 {
     int i;
     if(XSoundInitFlag){
         for(i = 0; i < MAX_CHANNELS; ++i)
             SoundStop(i);
         /* SDL_Mixer version
         Mix_CloseAudio();*/
         delete clunk_object;
         context.deinit();
         XSoundInitFlag = 0;
     }
 }
References clunk_object, context, MAX_CHANNELS, SoundStop(), and XSoundInitFlag.
SoundInit()
int SoundInit (int maxHZ, int channels)
 {
     //Only one freq, now sound more powerfull.
     /* SDL_Mixer version
     if (SDL_Init (SDL_INIT_AUDIO) == -1)
     {
         std::cout<<"SDL_init: "<<Mix_GetError()<<std::endl;
         ErrH.Abort("SDL_init:trabl!");
         return false;
     }
     if (Mix_OpenAudio (maxHZ, MIX_DEFAULT_FORMAT, 2, 1024) == -1)
     {
         std::cout<<"Mix_OpenAudio: "<<Mix_GetError()<<std::endl;
         ErrH.Abort(Mix_GetError());
         return false;
     }
     Mix_AllocateChannels(MAX_CHANNELS); */
     //std::cout<<"SoundInit maxHZ:"<<maxHZ<<std::endl;
     context.init(maxHZ, 2, 512);
     g_freq = maxHZ;
     context.set_max_sources(MAX_CHANNELS);
     clunk_object = context.create_object();
     int i;
     for(i = 0; i < MAX_CHANNELS; ++i)
     {
         /* SDL_Mixer version
         Mix_Volume(i, MIX_MAX_VOLUME); */
         channels[i].sound = NULL;
         channels[i].priority = channels[i].flags = channels[i].cropos = channels[i].pan = 0;
     }
     /* SDL_Mixer version
     Mix_ChannelFinished(&ChannelFinished);*/
     XSoundInitFlag = 1;
     //ErrH.Abort("SoundInit OK!!!");
     return true;
 }
References clunk_object, context, g_freq, and MAX_CHANNELS.
SoundLoad()
void SoundLoad (char * filename, void ** lpDSB)
 {
     /* SDL_Mixer version
     Mix_Chunk *chunk=Mix_LoadWAV(filename);
     if(chunk==NULL)
         {
         std::string tmp;
         tmp="Error load sound: ";
         tmp+=filename;
         ErrH.Log(tmp.c_str());
         }
     */
     //std::cout<<"SoundLoad:"<<filename<<std::endl;
     clunk::Sample *chunk;
     try {
         chunk = context.create_sample();
         chunk->load(filename);
     } catch(const std::exception & e)
         {
         std::string tmp;
         tmp="Error load sound: ";
         tmp+=filename;
         ErrH.Log(tmp.c_str());
         delete chunk;
         chunk = NULL;
         }
     (*lpDSB) = (void *)chunk;
 }
References context, ErrH, XErrorHandler::Log(), and NULL.
SoundPan()
void SoundPan (int channel, int panning)
 {
     if(XSoundInitFlag){
         //std::cout<<"SoundPan "<<channel<<" "<<panning*0.001<<std::endl;
         channels[channel].pan = panning;
         //if(channels[channel].sound) {
         //  channels[channel].sound->panning = panning*0.01;
         //}
         //if(channels[channel].sound) channels[channel].sound -> SetPan((LONG )panning);
     }
 }
References XSoundInitFlag.
SoundPlay()
void SoundPlay (void * lpDSB, int channel, int priority, int cropos, int flags)
 {
     if(XSoundInitFlag){
         clunk::Sample *source = (clunk::Sample *)lpDSB;
         //if (channel==2)
         //  std::cout<<"SoundPlay:"<<source->name<<" channel:"<<channel<<" cropos:"<<cropos<<" pr1:"<<channels[channel].priority<<" pr2:"<<priority<<" playing:"<<clunk_object->playing(source->name)<<std::endl;
         if (cropos == 255) {
             if (!clunk_object->playing(source->name)||channels[channel].priority>priority) {
                 SoundStop(channel);
                 clunk_object->play(source->name, new clunk::Source(source, false, clunk::v3<float>(), 1, 1, channels[channel].pan*0.0001));
                 if(flags & DS_LOOPING){
                     clunk_object->set_loop(source->name, true);
                 }
             } else {
                 return;
             }
         } else {
             if (channels[channel].sound) {
                 if (clunk_object->playing(channels[channel].sound->name)&&channels[channel].priority<priority) {
                     return;
                 }
                 SoundStop(channel);
             }
             clunk_object->play(source->name, new clunk::Source(source, false, clunk::v3<float>(), 1, 1, channels[channel].pan*0.0001));
             if(flags & DS_LOOPING){
                 clunk_object->set_loop(source->name, true);
             }
         }
         if(flags & DS_QUEUE){
             std::cout<<"DS_QUEUE!!!"<<std::endl;
         }
         if(flags & DS_STREAM){
             std::cout<<"DS_STREAM!!!"<<std::endl;
         }
         channels[channel].priority = priority;
         channels[channel].flags = flags;
         channels[channel].cropos = cropos;
         channels[channel].sound = source;
         /*
         //Other sound logic for FUTURE
         //channels[channel].priority = priority;
         //channels[channel].sound = (Mix_Chunk *)lpDSB;
         //channels[channel].flags = flags;
         //Mix_PlayChannel(-1, channels[channel].sound, 0);
         if(channels[channel].sound)
             {
             if(channels[channel].priority < priority)
                 {
                 //ErrH.Log("D1");
                 SoundStop(channel);
                 channels[channel].priority = priority;
                 channels[channel].flags = flags;
                 //SDL_Mixer version
                 //channels[channel].sound = (Mix_Chunk *)lpDSB;
                 //Mix_PlayChannel(channel, channels[channel].sound, 0);
                 channels[channel].sound = (clunk::Sample *)lpDSB;
                 clunk_object->play(channels[channel].sound->name, new clunk::Source(channels[channel].sound, false));
                 if(flags & DS_LOOPING){
                     clunk_object->set_loop(channels[channel].sound->name, true);
                 }
                 }
             else
                 {
                 if(channel<20)
                     SoundPlay(lpDSB, channel+10, priority, cropos, flags);
                 }
             }
         else
             {
             //ErrH.Log("D2");
             channels[channel].priority = priority;
             channels[channel].flags = flags;
             //SDL_Mixer version
             //channels[channel].sound = (Mix_Chunk *)lpDSB;
             //Mix_PlayChannel(channel, channels[channel].sound, 0);
             channels[channel].sound = (clunk::Sample *)lpDSB;
             clunk_object->play(channels[channel].sound->name, new clunk::Source(channels[channel].sound, false));
             if(flags & DS_LOOPING){
                 clunk_object->set_loop(channels[channel].sound->name, true);
             }
             }*/
     }
 }
SoundRelease()
void SoundRelease (void * lpDSB)
 {
     if(XSoundInitFlag){
         //std::cout<<"SoundRelease:"<<((clunk::Sample *)lpDSB)->name<<std::endl;
         /* SDL_Mixer version
         Mix_FreeChunk((Mix_Chunk *)lpDSB);*/
         //clunk_object->cancel(((clunk::Sample *)lpDSB)->name, 0);
         delete (clunk::Sample *)lpDSB;
     }
 }
References XSoundInitFlag.
SoundStop()
void SoundStop (int channel)
 {
     if(XSoundInitFlag){
         //std::cout<<"SoundStop:"<<channel<<std::endl;
         if(channels[channel].sound){
             /* SDL_Mixer version
             Mix_HaltChannel(channel); */
             //context.stop_all();
             clunk_object->cancel(channels[channel].sound->name, 0);
             channels[channel].sound = NULL;
             channels[channel].priority = channels[channel].flags = channels[channel].cropos = channels[channel].pan = 0;
         }
     }
 }
References XSoundInitFlag.
Referenced by EffectsOff(), EffectsOnOff(), SoundFinit(), and StopEFFECT().
SoundStreamClose()
void SoundStreamClose (void * stream)
SoundStreamOpen()
void SoundStreamOpen (char * filename, void ** strptr)
SoundStreamRelease()
void SoundStreamRelease (void * stream)
SoundVolume()
void SoundVolume (int channel, int volume)
 {
     /* SDL_Mixer Version
     volume+=10000;
     volume*=0.0128;*/
     float f_volume = volume + 10000;
     f_volume *= 0.0001;
     //Debug
     //std::cout<<"SoundVolume:"<<channel<<" "<<volume<<std::endl;
     if(XSoundInitFlag){
         if(channels[channel].sound) //channels[channel].sound -> SetVolume((LONG )volume);
             {
             channels[channel].volume = volume;
             /* SDL_Mixer Version
             Mix_Volume(channel, volume);*/
             context.set_volume(channel, f_volume);
             }
     }
 }
xsGetCurTrackCD()
int xsGetCurTrackCD (void)
xsGetNumTracksCD()
int xsGetNumTracksCD (void)
xsGetStatusCD()
int xsGetStatusCD (void)
xsGetTrackLenCD()
int xsGetTrackLenCD (int track)
xsGetVolumeCD()
int xsGetVolumeCD (void)
xsGetVolumeWAVE()
int xsGetVolumeWAVE (void)
xsInitCD()
void xsInitCD (void)
xsMixerOpen()
void xsMixerOpen (void)
xsPauseCD()
void xsPauseCD (void)
xsPlayCD()
void xsPlayCD (int track, int min = 0, int sec = 0)
xsPlayOneTrackCD()
void xsPlayOneTrackCD (int track, int min = 0, int sec = 0)
xsResumeCD()
void xsResumeCD (void)
xsSetVolumeCD()
void xsSetVolumeCD (int val)
xsSetVolumeWAVE()
void xsSetVolumeWAVE (int val)
xsStopCD()
void xsStopCD (void)