Vangers: src/actint/actint.cpp File Reference
actint.cpp File Reference
#include "../global.h"
#include "../runtime.h"
#include "../iscreen/hfont.h"
#include "../iscreen/iscreen.h"
#include "item_api.h"
#include "actint.h"
#include "aci_scr.h"
#include "aci_str.h"
#include "aci_evnt.h"
#include "a_consts.h"
#include "credits.h"
#include "../iscreen/ikeys.h"
#include "../iscreen/controls.h"
#include "mlconsts.h"
#include "mlstruct.h"
#include "../units/uvsapi.h"
#include "../uvs/univang.h"
#include "../uvs/diagen.h"
#include "../sound/hsound.h"
Macros
#define ACI_IND_SPIRAL_COL 195
#define ACI_IND_SPIRAL_SIZE 3
#define ACI_IND_JUMP_COL 160
#define ACI_IND_JUMP_SIZE 1
#define ACI_IND_DVC_COL 160
#define ACI_IND_DVC_SIZE 1
#define ACI_IND_NRG0_COL 224
#define ACI_IND_NRG0_SIZE 1
#define ACI_IND_NRG1_COL 128
#define ACI_IND_NRG1_SIZE 1
#define ACI_IND_LOAD_COL 224
#define ACI_IND_LOAD_SIZE 1
#define ACI_IND_FON_START 74
#define ACI_IND_FON_SIZE 3
#define ACI_IND_ARROW_START 72
#define ACI_IND_ARROW_SIZE 1
#define AS_NUMRES 2
#define FULLSCR_MODE 1
#define INVSCR_MODE 2
#define FM_OFFSET 3
#define ACI_ARROW_OFFS_UP 1
#define ACI_ARROW_OFFS_DOWN 5
#define IND_DATA_OFFS 5
#define SHADOW_COL 103
#define WORLD_COORD_MAX 1000
Functions
void aciWorldExploredInfo (void)
void LoadingMessage (int flush=0)
void acsHandleExtEvent (int code, int data0=0, int data1=0, int data2=0)
void aciShowLocationPicture (void)
void aciPrepareScreenText (char *ptr, int sz, int max_len)
void aOutText32 (int x, int y, int color, void *text, int font, int hspace, int vspace)
void aOutText32clip (int x, int y, int color, void *text, int font, int hspace, int vspace)
int aTextWidth32 (void *text, int font, int hspace)
int aTextHeight32 (void *text, int font, int vspace)
void aciInitItmTextQueue (void)
void aciReadItmText (void)
char * dgGetThreallPhrase (void)
void aciShowRacingPlace (void)
void aciML_Pause (void)
void aciML_Resume (void)
int aciGetCurCycle (void)
void ipal_init (unsigned char *p)
void aciPutBufSpr (int x, int y, int sx, int sy, int bsx, void *src, void *dest, int col, int col_sz)
iListElement * iGetObject (const char *scr, const char *obj)
int aciGetCurMatrixPrice (void)
void aciChangeWorld (int id)
void iChatInit (void)
void iChatQuant (int flush=0)
void iChatFinit (void)
void iChatKeyQuant (SDL_Event *k)
void iChatMouseQuant (int x, int y, int bt)
void LoadResourceSOUND (const char *path_name, int surface)
void SoundEscaveOff (void)
void aci_setMatrixBorder (void)
void aci_setScMatrixBorder (void)
void aci_LocationQuant (void)
void aciAutoMoveItems (void)
void aciSetMechName (void)
void aciSell_Item (invItem *p)
void aciSell_Matrix (invMatrix *p)
void aciSellMoveItem (void)
void aciInitInfoPanels (void)
int aciCheckSellItem (void)
void aciSetTimePanel (void)
void aciInitEvLineID (void)
void aciChangeList (void)
void aciInitShopItems (void)
void aciSetShopItem (int id)
void aciShowFrags (void)
void aciInitAviObject (void)
void aciPutTreasureItem (void)
void aciCHandler (int k)
void aciHandleCameraEvent (int code, int data)
void aciPrepareWorldsMenu (void)
void aciSet_aMouse (void)
void aciSet_iMouse (void)
void aciNextShopItem (void)
void aciPrevShopItem (void)
void aciInitShopAvi (void)
void aciChangeAviIndex (void)
void aciBuyItem (void)
void aciInitShopButtons (void)
void aciGetEleech (void)
void aciGetRubox (void)
void aciInitMechosInfo (invMatrix *p, InfoPanel *ip)
void aciInitShopList (void)
void aciChooseShopItem (void)
void aciNextPhrase (void)
void aciStartSpeech (void)
void aciInitCurMatrixPtr (void)
void aciHandleSubmenuEvent (int id, fncMenuItem *p)
char * aciGetPrice (iListElement *p, int mode, int sell_mode)
char * aciGetItemLoad (invItem *p, int mode)
void aciSwapMatrices (void)
void aciCancelMatrix (void)
void aciShowScMatrix (void)
void aciBuildQuestList (void)
void aciAskQuestion (void)
void aciShowBlockPhrase (void)
void aciPay4Item (invItem *p)
int aciCheckItemCredits (void)
void iScrQuant (void)
void i_evince_pal (unsigned char *p, int delta)
int aciGetScreenMechos (int x, int y)
void redraw_fnc (int x, int y, int sx, int sy, int fnc)
char * GetCompasTarget (void)
void swap_buf_col (int src, int dest, int sx, int sy, unsigned char *buf)
void restore_mouse_cursor (void)
void set_mouse_cursor (char *p, int sx, int sy)
void set_screen (int Dx, int Dy, int mode, int xcenter, int ycenter)
void put_fon (int x, int y, int sx, int sy, unsigned char *buf)
void put_attr_fon (int x, int y, int sx, int sy, unsigned char *buf)
void iregRender (int LowX, int LowY, int HiX, int HiY)
void show_map (int x, int y, int sx, int sy)
void a_buf_line (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char *buf)
void a_buf_line2 (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char *buf)
void a_buf_setpixel (int x, int y, int sx, int sy, int col, unsigned char *buf)
void ibsout (int x, int y, void *ptr)
void change_screen (int scr)
void mem_putspr (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char *src, unsigned char *dest)
void mem_putspr_h (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char *src, unsigned char *dest)
void mem_rectangle (int x, int y, int sx, int sy, int bsx, int col_in, int col_out, int mode, void *buf)
void build_cell_frame (void)
void free_cell_frame (void)
void aMS_init (void)
void put_buf2col (int x, int y, int sx, int sy, unsigned char *buf, int null_lev, int n_mode)
void put_map (int x, int y, int sx, int sy)
int acsQuant (void)
Variables
int uvsTabuTaskFlag
bmlObject * aIndArrowBML
bmlObject * aIndDataBML
bmlObject * aIndBackBML
int iChatExit
int NetworkON
int iMouseX
int iMouseY
int iMouseLPressFlag
int iMouseRPressFlag
int iMousePrevX
int iMousePrevY
aciFont ** aScrFonts32
aciFont ** aScrFonts
int aciKeyboardLocked
int aciML_ToolzerRadius
unsigned char * iscrPal
iScreenDispatcher * iScrDisp
int CurrentWorld
int GameQuantReturnValue
int * aSinTable
int * aCosTable
int uvsCurrentWorldUnable
int iScreenLog
int * AVI_index
actIntDispatcher * aScrDisp
int PalIterLock
int aciShopMenuLog
int ExclusiveLog
int aciWorldIndex
int Pause
char * aciSTR_OFF
char * aciSTR_DAY
char * aciSTR_UNDEFINED_PRICE
char * aciSTR_PRICE
char * aciSTR_EMPTY_SLOT
char * aciSTR_UNNAMED_SAVE
char * aciSTR_AUTOSAVE
char * aciSTR_KILLS
char * aciSTR_DEATHS
char * aciSTR_LUCK
char * aciSTR_DOMINANCE
char * aciSTR_BROKEN
char * aciSTR_ENERGY_SHIELD
char * aciSTR_RESTORING_SPEED
char * aciSTR_MECHANIC_ARMOR
char * aciSTR_VELOCITY
char * aciSTR_SPIRAL_CAPACITY
char * aciSTR_AIR_RESERVE
char * aciSTR_DAMAGE
char * aciSTR_LOAD
char * aciSTR_SHOTS
char * aciSTR_BURST
char * aciSTR_WORKING_TIME
char * aciSTR_SECONDS
char * aciSTR_IN_PACK
char * aciSTR_NO_CASH
char * aciSTR_PICKUP_ITEMS_OFF
char * aciSTR_PICKUP_WEAPONS_OFF
char * aciSTR_PutThis
int aciItmTextQueueSize
const int aciTEXT_COLOR = 165 + (2 << 16)
const int MAX_ITEM_ID = 9
const int MAX_MATRIX_ID = 3
int aCellSize = 20
int iCellSize = 20
int aci_CellSize = 20
int aciCurCredits01 = 0
int curItemID = 1
int curMatrixID = 0
unsigned char * aCellFrame
int aciTextColBright = 0
int aciTextColBrightDelta = 1
int aci_tmp = 0
int aci_tmp_max = 64
int aciCurLuck = 0
int aciPrevLuck = -1
int aciCurDominance = 0
int aciPrevDominance = -1
int aciCurEnergy = 63
int aciMaxEnergy = 64
int aciCurArmor = 63
int aciMaxArmor = 64
int aciCurLoad = 0
int aciMaxLoad = 1
int aciCurFrame = 0
int aciTextEndFlag = 0
int aciCurWpnResource = 0
int aciMaxWpnResource = 1
int aciCurDvcResource = 0
int aciMaxDvcResource = 1
int aciCurJumpCount = 3
int aciMaxJumpCount = 5
int aciPrevJumpCount = -1
int aciCurTime = 0
int aciCurJumpImpulse = 0
int aciMaxJumpImpulse = 1
int aciNumColSchemes = 0
int aciColSchemeLen = 0
unsigned char ** aciColorSchemes = NULL
unsigned char * aciCurColorScheme
unsigned char * actIntPal
const char * aci_curLocationName = ""
int aci_curLocationID = 0
int aci_SecondMatrixID = 0
char * aci_ivMapName = NULL
char * aci_iScreenID = NULL
unsigned char aci_iscrPal [768]
invMatrix * backupMatrix
int prevWorld
int aciPickupItems = 1
int aciPickupDevices = 1
int aciBufRedrawFlag = 0
int aciProtractorEvent = 0
int aciMechMessiahEvent = 0
int aciTeleportEvent = 0
const int aciSaveVersion = 1
Macro Definition Documentation
ACI_ARROW_OFFS_DOWN
#define ACI_ARROW_OFFS_DOWN 5
ACI_ARROW_OFFS_UP
#define ACI_ARROW_OFFS_UP 1
ACI_IND_ARROW_SIZE
#define ACI_IND_ARROW_SIZE 1
ACI_IND_ARROW_START
#define ACI_IND_ARROW_START 72
ACI_IND_DVC_COL
#define ACI_IND_DVC_COL 160
ACI_IND_DVC_SIZE
#define ACI_IND_DVC_SIZE 1
ACI_IND_FON_SIZE
#define ACI_IND_FON_SIZE 3
ACI_IND_FON_START
#define ACI_IND_FON_START 74
ACI_IND_JUMP_COL
#define ACI_IND_JUMP_COL 160
ACI_IND_JUMP_SIZE
#define ACI_IND_JUMP_SIZE 1
ACI_IND_LOAD_COL
#define ACI_IND_LOAD_COL 224
ACI_IND_LOAD_SIZE
#define ACI_IND_LOAD_SIZE 1
ACI_IND_NRG0_COL
#define ACI_IND_NRG0_COL 224
ACI_IND_NRG0_SIZE
#define ACI_IND_NRG0_SIZE 1
ACI_IND_NRG1_COL
#define ACI_IND_NRG1_COL 128
ACI_IND_NRG1_SIZE
#define ACI_IND_NRG1_SIZE 1
ACI_IND_SPIRAL_COL
#define ACI_IND_SPIRAL_COL 195
ACI_IND_SPIRAL_SIZE
#define ACI_IND_SPIRAL_SIZE 3
AS_NUMRES
#define AS_NUMRES 2
FM_OFFSET
#define FM_OFFSET 3
FULLSCR_MODE
#define FULLSCR_MODE 1
IND_DATA_OFFS
#define IND_DATA_OFFS 5
INVSCR_MODE
#define INVSCR_MODE 2
SHADOW_COL
#define SHADOW_COL 103
WORLD_COORD_MAX
#define WORLD_COORD_MAX 1000
Function Documentation
a_buf_line()
void a_buf_line (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char * buf)
 {
     int dx,dy,xinc,yinc,err,cnt,index,i_xinc,i_yinc;
     dx = x2 - x1;
     dy = y2 - y1;
     xinc = (dx > 0) ? 1 : (dx < 0) ? (-1) : 0;
     yinc = (dy > 0) ? 1 : (dy < 0) ? (-1) : 0;
     i_xinc = xinc;
     i_yinc = (dy > 0) ? sx : (dy < 0) ? (-sx) : 0;
     dx = abs(dx);
     dy = abs(dy);
     index = x1 + y1 * sx;
     if(dx > dy){
         err = dx/2;
         cnt = dx + 1;
         while(cnt--){
             buf[index] = col;
             x1 += xinc;
             index += i_xinc;
             err += dy;
             if(err >= dx){
                 if(cnt)
                     buf[index] = col;
                 err -= dx;
                 y1 += yinc;
                 index += i_yinc;
             }
         }
     }
     else {
         err = dy / 2;
         cnt = dy + 1;
         while(cnt--){
             buf[index] = col;
             y1 += yinc;
             index += i_yinc;
             err += dx;
             if(err >= dy){
                 if(cnt)
                     buf[index] = col;
                 err -= dy;
                 x1 += xinc;
                 index += i_xinc;
             }
         }
     }
 }
Referenced by build_cell_frame().
a_buf_line2()
void a_buf_line2 (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char * buf)
 {
     int dx,dy,xinc,yinc,err,cnt,index,i_xinc,i_yinc;
     dx = x2 - x1;
     dy = y2 - y1;
     xinc = (dx > 0) ? 1 : (dx < 0) ? (-1) : 0;
     yinc = (dy > 0) ? 1 : (dy < 0) ? (-1) : 0;
     i_xinc = xinc;
     i_yinc = (dy > 0) ? sx : (dy < 0) ? (-sx) : 0;
     dx = abs(dx);
     dy = abs(dy);
     index = x1 + y1 * sx;
     if(dx > dy){
         err = dx/2;
         cnt = dx + 1;
         while(cnt--){
             buf[index] = col;
             x1 += xinc;
             index += i_xinc;
             err += dy;
             if(err >= dx){
                 err -= dx;
                 y1 += yinc;
                 index += i_yinc;
             }
         }
     }
     else {
         err = dy / 2;
         cnt = dy + 1;
         while(cnt--){
             buf[index] = col;
             y1 += yinc;
             index += i_yinc;
             err += dx;
             if(err >= dy){
                 err -= dy;
                 x1 += xinc;
                 index += i_xinc;
             }
         }
     }
 }
Referenced by aciWorldMap::show_link().
a_buf_setpixel()
void a_buf_setpixel (int x, int y, int sx, int sy, int col, unsigned char * buf)
 {
     buf[x + y * sx] = col;
 }
aci_LocationQuant()
void aci_LocationQuant (void)
aci_setMatrixBorder()
void aci_setMatrixBorder (void)
 {
     int id,i,t,sz;
     XBuffer XBuf;
     iBitmapElement* p = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_MATRIX_BORDER_ID];
     if(!p) return;
     short sx,sy;
     if(aScrDisp -> curMatrix){
         id = aScrDisp -> curMatrix -> internalID;
         XBuf < "resource/actint/iscreen/matrix/mt";
         if(id < 10) XBuf < "0";
         XBuf <= id < ".bmp";
         XStream fh(XBuf.GetBuf(),XS_IN);
         fh > sx > sy;
         fh.read(p -> fdata,sx * sy);
         fh.close();
         sz = sx * sy;
         for(i = 0; i < sz; i ++){
             t = ((unsigned char*)p -> fdata)[i];
             if(t)
                 t += p -> bmp_null_level;
             else
                 t = HFONT_NULL_LEVEL;
             p -> fdata[i] = t;
         }
     }
     else {
         memset(p -> fdata,HFONT_NULL_LEVEL,p -> SizeX * p -> SizeY);
     }
 }
Referenced by actIntDispatcher::EventQuant().
aci_setScMatrixBorder()
void aci_setScMatrixBorder (void)
 {
     XBuffer XBuf;
 //  if(!aScrDisp -> secondMatrix) return;
     iBitmapElement* p = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(!p) return;
     if(!aScrDisp -> secondMatrix){
         memset(p -> fdata,HFONT_NULL_LEVEL,p -> bSizeX * p -> bSizeY);
         return;
     }
     short sx,sy;
     int id = aScrDisp -> secondMatrix -> internalID;
     XBuf < "resource/actint/iscreen/matrix/mt";
     if(id < 10) XBuf < "0";
     XBuf <= id < ".bmp";
     XStream fh(XBuf.GetBuf(),XS_IN);
     fh > sx > sy;
     fh.read(p -> fdata,sx * sy);
     fh.close();
     int i,t,sz = sx * sy;
     for(i = 0; i < sz; i ++){
         t = ((unsigned char*)p -> fdata)[i];
         if(t)
             t += p -> bmp_null_level;
         else
             t = HFONT_NULL_LEVEL;
         p -> fdata[i] = t;
     }
 }
Referenced by actIntDispatcher::EventQuant().
aciAskQuestion()
void aciAskQuestion (void)
 {
     char* str,*subj;
     fncMenuSet* m = aScrDisp -> qMenu;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p || !m) return;
     if(aciEscaveDead || aciEscaveEmpty) return;
     if(!(m -> flags & FMC_DATA_INIT)){
         str = dgD -> getQempty();
     }
     else {
         subj = m -> get();
         str = dgD -> getAnswer(subj);
     }
     if(str){
         p -> free_list();
         aciInitPanel(p,(unsigned char*)str);
         p -> set_redraw();
     }
     aciStartSpeech();
 }
References ACI_ANSWER_PANEL, aciEscaveDead, aciEscaveEmpty, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciAutoMoveItems()
void aciAutoMoveItems (void)
 {
     int i,x,y,sz;
     invItem* p,*p1;
     if(!aScrDisp -> curMatrix || !aScrDisp -> secondMatrix)
         return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     sz = aScrDisp -> curMatrix -> items -> Size;
     for(i = 0; i < sz; i ++){
         p1 = (invItem*)p -> prev;
         x = p -> MatrixX;
         y = p -> MatrixY;
         aScrDisp -> curMatrix -> remove_item(p);
         if(!aScrDisp -> secondMatrix -> auto_put_item(p)){
             aScrDisp -> curMatrix -> put_item(x,y,p);
         }
         else {
             ((uvsActInt*)p -> uvsDataPtr) -> pos_x = p -> MatrixX;
             ((uvsActInt*)p -> uvsDataPtr) -> pos_y = p -> MatrixY;
         }
         p = p1;
     }
     SOUND_DROP();
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
 }
References aScrDisp, curMatrix, prev, and SOUND_DROP.
Referenced by actIntDispatcher::EventQuant().
aciBuildQuestList()
void aciBuildQuestList (void)
 {
     int cd = 0;
     char* p;
     if(!aScrDisp -> qMenu) return;
     if(aciEscaveDead || aciEscaveEmpty) return;
     fncMenuItem* itm;
     fncMenu* m;
     p = dgD -> findQfirst();
     if(!p) return;
     aScrDisp -> qMenu -> finit();
     aScrDisp -> qMenu -> init();
     p = dgD -> getQprefix();
     if(p){
         m = new fncMenu;
         m -> flags |= FM_RANGE_FONT;
         itm = aScrDisp -> alloc_menu_item();
         itm -> init_name(p);
         itm -> fnc_code = 0;
         itm -> font = ACI_PHRASE_FONT;
         itm -> space = 1;
         itm -> init();
         m -> add_item(itm);
         aScrDisp -> qMenu -> add(m);
     }
     p = dgD -> findQfirst();
     if(p){
         m = new fncMenu;
         m -> flags |= FM_RANGE_FONT;
         while(p){
             itm = aScrDisp -> alloc_menu_item();
             itm -> init_name(p);
             itm -> fnc_code = cd;
             itm -> font = ACI_PHRASE_FONT;
             itm -> space = 1;
             itm -> init();
             m -> add_item(itm);
             cd ++;
             p = dgD -> findQnext();
         }
         aScrDisp -> qMenu -> add(m,1);
     }
     p = dgD -> getQpostfix();
     if(p){
         m = new fncMenu;
         m -> flags |= FM_RANGE_FONT;
         itm = aScrDisp -> alloc_menu_item();
         itm -> init_name(p);
         itm -> fnc_code = 0;
         itm -> font = ACI_PHRASE_FONT;
         itm -> space = 1;
         itm -> init();
         m -> add_item(itm);
         aScrDisp -> qMenu -> add(m);
     }
     aScrDisp -> qMenu -> init_redraw();
     aScrDisp -> qMenu -> build();
     aScrDisp -> qMenu -> set_redraw();
 }
References aciEscaveDead, aciEscaveEmpty, aScrDisp, and dgD.
Referenced by actIntDispatcher::EventQuant().
aciBuyItem()
void aciBuyItem (void)
 {
     int cr;
     invItem* p,*p1;
     invMatrix* m,*m1;
     uvsActInt* u,*u1;
     listElem* el;
     if(!(aScrDisp -> flags & AS_INV_MOVE_ITEM)){
         if(iShopItem){
             if(iEvLineID == MECHOS_MODE || iEvLineID == MECHOS_LIST_MODE){
                 m = (invMatrix*)iShopItem;
                 u = (uvsActInt*)m -> uvsDataPtr;
                 if(!u) ErrH.Abort("Bad shop item...");
                 u -> delink(GMechos);
                 if(aScrDisp -> curMatrix){
                     if(GGamerMechos){
                         el = GMechos;
                         //std::cout<<"GGamerMechos -> link(el)"<<std::endl;
                         GGamerMechos -> link(el);
                         GMechos = (uvsActInt*)el;
                     }
                     m1 = aScrDisp -> get_imatrix(aScrDisp -> curMatrix -> type);
                     if(!m1 -> uvsDataPtr) m1 -> uvsDataPtr = GGamerMechos;
                     iShopItem = (iListElement*)m1;
                 }
                 else {
                     aciNextShopItem();
                 }
                 //std::cout<<"aciBuyItem GGamerMechos = u"<<std::endl;
                 GGamerMechos = u;
                 cr = aciGetCurCredits();
                 cr -= u -> price;
                 aciUpdateCurCredits(cr);
                 u1 = aciGetMechos(m -> type);
                 if(u1)
                     m -> uvsDataPtr = u1;
                 else
                     m -> uvsDataPtr = NULL;
             }
             else {
                 if(aScrDisp -> flags & AS_INV_MOVE_ITEM) return;
                 p = (invItem*)iShopItem;
                 p1 = aScrDisp -> alloc_item();
                 p -> clone(p1);
                 aScrDisp -> curItem = p1;
                 set_mouse_cursor(p1 -> frame,p1 -> ScreenSizeX,p1 -> ScreenSizeY);
                 aScrDisp -> flags |= AS_INV_MOVE_ITEM;
                 el = (listElem*)GGamer;
                 u = (uvsActInt*)p -> uvsDataPtr;
                 if(!u) ErrH.Abort("Null uvsDataPtr...");
                 u -> delink(GItem);
                 u -> link(el);
                 GGamer = (uvsActInt*)el;
                 p1 -> uvsDataPtr = u;
                 p1 -> flags |= INV_ITEM_NO_PAY;
                 p1 -> flags |= INV_ITEM_NEW;
                 u -> pos_x = u -> pos_y = -1;
                 p1 -> MatrixX = p1 -> MatrixY = -1;
                 if(aScrDisp -> iscr_iP){
                     aciInitPricePanel(aScrDisp -> iscr_iP,(iListElement*)p1,ITEMS_MODE,1);
                     aScrDisp -> iscr_iP -> set_redraw();
                 }
                 u1 = aciGetShopItem(u -> type);
                 if(u1 && !aScrDisp -> curLocData -> ExcludeItems[u1 -> type]){
                     p -> uvsDataPtr = u1;
                 }
                 else {
                     p -> uvsDataPtr = NULL;
                     aciNextShopItem();
                 }
             }
         }
         aciInitAviID();
         if(iEvLineID == MECHOS_LIST_MODE || iEvLineID == ITEMS_LIST_MODE || iEvLineID == WEAPONS_LIST_MODE)
             aciBuildShopList();
     }
     else {
         aciSellMoveItem();
     }
 }
References aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciCancelMatrix()
void aciCancelMatrix (void)
 {
     _iSTORE_OFFS_;
     int i,num2,timer = 0;
     iScreenObject* m_owner = NULL,*m2_owner = NULL;
     iBitmapElement* b,*b1;
     b = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_MATRIX_BORDER_ID];
     b1 = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(b) m_owner = (iScreenObject*)b -> owner;
     if(b1) m2_owner = (iScreenObject*)b1 -> owner;
     unsigned char* fon_buf;
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
 #ifndef _ACI_NO_SHOP_ANIMATION_
     num2 = aScrDisp -> curLocData -> numMatrixShutters2;
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters2[i] -> loadData();
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     SOUND_GATE();
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
 #endif
     aScrDisp -> cancel_matrix();
     aci_setMatrixBorder();
     aci_setScMatrixBorder();
     if(m_owner){
         m_owner -> putfon();
         m_owner -> redraw();
     }
     if(m2_owner){
         m2_owner -> curHeightScale = 0;
         m2_owner -> putfon();
         m2_owner -> redraw();
     }
     put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
     if(aScrDisp -> curMatrix)
         aScrDisp -> curMatrix -> redraw();
     iScrDisp -> curScr -> show_avi();
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 #else
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     SOUND_GATE();
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> freeData();
     }
     delete[] fon_buf;
 #endif
     if(v_flag)
         XGR_MouseShow();
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_MATRIX_BORDER_ID, aci_setMatrixBorder(), aci_setScMatrixBorder(), ACI_SHUTTER_CLOSE, ACI_SHUTTER_OPEN, ACI_SMATRIX_BORDER_ID, aScrDisp, curMatrix, i_get_scrfon(), i_put_scrfon(), I_RES_X, I_RES_Y, iScrDisp, iScreenOffs, NULL, put_map(), Redraw, SOUND_GATE, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
Referenced by actIntDispatcher::EventQuant().
aciCHandler()
void aciCHandler (int k)
 {
     return;
     int code = 0,cr;
     if(NetworkON || key > 256 || key <= 0) return;
     if(aciTreeData) {
         code = aciTreeData -> quant(key);
     }
     switch(code << NetworkON){
         case ACI_ADD_BEEBOS:
             cr = aciGetCurCredits();
             cr += 50000;
             aciUpdateCurCredits(cr);
             if(!(aScrDisp -> flags & AS_ISCREEN))
                 SetWorldBeebos(cr);
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_ADD_LUCK:
             uvsChangeLuck();
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_ADD_DOMINANCE:
             uvsChangeDominance();
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_ADD_KEYS:
             aciOpenWorldLink(1,0);
             aciOpenWorldLink(1,3);
             aciOpenWorldLink(1,2);
             aciOpenWorldLink(1,4);
             aciOpenWorldLink(0,6);
             aciOpenWorldLink(3,8);
             aciOpenWorldLink(2,9);
             aciOpenWorldLink(2,5);
             aciOpenWorldLink(7,7);
             aciPrepareWorldsMenu();
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_COMPLETE_TABUTASK:
             aciCompleteTabutask();
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK01:
             aciAddTabutask(1);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK02:
             aciAddTabutask(2);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK03:
             aciAddTabutask(3);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK04:
             aciAddTabutask(4);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK05:
             aciAddTabutask(5);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK06:
             aciAddTabutask(6);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK07:
             aciAddTabutask(7);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK08:
             aciAddTabutask(8);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK09:
             aciAddTabutask(9);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK10:
             aciAddTabutask(10);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK11:
             aciAddTabutask(11);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK12:
             aciAddTabutask(12);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK13:
             aciAddTabutask(13);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK14:
             aciAddTabutask(14);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK15:
             aciAddTabutask(15);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK16:
             aciAddTabutask(16);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK17:
             aciAddTabutask(17);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK18:
             aciAddTabutask(18);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK19:
             aciAddTabutask(19);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK20:
             aciAddTabutask(20);
             aciTreeData -> reset();
             break;
         case ACI_TELEPORT_G:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,0);
             }
             break;
         case ACI_TELEPORT_F:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,1);
             }
             break;
         case ACI_TELEPORT_N:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,2);
             }
             break;
         case ACI_TELEPORT_X:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,3);
             }
             break;
         case ACI_TELEPORT_B:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,4);
             }
             break;
         case ACI_TELEPORT_K:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,6);
             }
             break;
         case ACI_TELEPORT_T:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,7);
             }
             break;
         case ACI_TELEPORT_H:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,8);
             }
             break;
         case ACI_TELEPORT_W:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,11);
             }
             break;
         case ACI_TELEPORT_A:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,12);
             }
             break;
         case ACI_END_GAME0:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_INFERNAL_LOCKED);
             }
             break;
         case ACI_END_GAME1:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_SPOBS_LOCKED);
             }
             break;
         case ACI_END_GAME2:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_ALL_LOCKED);
             }
             break;
         case ACI_END_GAME3:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_LUCKY);
             }
             break;
         case ACI_CHANGE_CYCLE:
             if(!actIntLog){
                 SOUND_DROP();
                 uvsChangeCycle();
             }
             break;
         case ACI_REPAIR:
             if(!actIntLog){
                 SOUND_DROP();
                 FakeOfMight();
             }
             break;
     }
 }
References ACI_ADD_BEEBOS, aciGetCurCredits(), aciTreeData, aciUpdateCurCredits(), aScrDisp, key(), and NetworkON.
Referenced by actIntDispatcher::iKeyTrap(), and actIntDispatcher::KeyQuant().
aciChangeAviIndex()
void aciChangeAviIndex (void)
 {
     switch(aciCurAviIndex){
         case ACI_PICTURE_AVI_ENG:
             aciCurAviIndex = (lang() == RUSSIAN) ? ACI_TEXT_AVI_RUS : ACI_TEXT_AVI_ENG;
             break;
         case ACI_TEXT_AVI_RUS:
         case ACI_TEXT_AVI_ENG:
             aciCurAviIndex = ACI_PICTURE_AVI_ENG;
             break;
     }
     aciInitAviID();
 }
References ACI_PICTURE_AVI_ENG, ACI_TEXT_AVI_ENG, ACI_TEXT_AVI_RUS, aciCurAviIndex, aciInitAviID(), lang(), and RUSSIAN.
Referenced by actIntDispatcher::EventQuant().
aciChangeList()
void aciChangeList (void)
 {
     invItem* p,*fp;
     invMatrix* m,*fm;
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
             fm = m = (invMatrix*)aScrDisp -> i_matrixList -> first;
             while(!m -> uvsDataPtr){
                 m = (invMatrix*)m -> next;
                 if(m == fm) break;
             }
             if(!m -> uvsDataPtr){
                 iShopItem = NULL;
             }
             else {
                 iShopItem = (iListElement*)m;
                 aciCurMechosID = m -> type;
             }
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
             fp = p = (invItem*)aScrDisp -> i_itemList -> first;
             while(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS){
                 p = (invItem*)p -> next;
                 if(p == fp) break;
             }
             if(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS)
                 iShopItem = NULL;
             else
                 iShopItem = (iListElement*)p;
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
             fp = p = (invItem*)aScrDisp -> i_itemList -> first;
             while(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS){
                 p = (invItem*)p -> next;
                 if(p == fp) break;
             }
             if(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS)
                 iShopItem = NULL;
             else
                 iShopItem = (iListElement*)p;
             break;
     }
     aciInitAviID();
     if(iEvLineID == MECHOS_LIST_MODE || iEvLineID == ITEMS_LIST_MODE || iEvLineID == WEAPONS_LIST_MODE)
         aciBuildShopList();
 }
References aScrDisp, iEvLineID, MECHOS_LIST_MODE, and MECHOS_MODE.
Referenced by aciNextShopItem(), aciPrevShopItem(), aciSetShopItem(), and actIntDispatcher::EventQuant().
aciChangeWorld()
void aciChangeWorld (int id)
 {
     int i,cur_id,fl = 0;
     aciWorldInfo* p,*p1;
     if(w_id == -1) return;
     cur_id = aScrDisp -> wMap -> world_ids[w_id];
     if(cur_id == -1) return;
     p = aScrDisp -> wMap -> world_ptr[cur_id];
     if(!p) return;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p1 = aScrDisp -> wMap -> world_ptr[i];
         if(p1){
             if(p1 -> flags & AS_ACCESSIBLE_WORLD){
                 p1 -> flags &= ~AS_ACCESSIBLE_WORLD;
                 fl = 1;
             }
             if(p1 -> flags & AS_CURRENT_WORLD){
                 p1 -> flags &= ~AS_CURRENT_WORLD;
                 p1 -> flags |= AS_VISIBLE_WORLD;
             }
         }
     }
     if(fl){
         for(i = 0; i < AS_MAX_WORLD; i ++){
             p1 = aScrDisp -> wMap -> world_ptr[i];
             if(i != cur_id && p1){
                 if(p1 -> links[cur_id] || p -> links[i]){
                     p1 -> flags |= AS_ACCESSIBLE_WORLD;
                 }
             }
         }
     }
     p -> flags |= AS_CURRENT_WORLD;
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
 }
References AS_MAX_WORLD, aScrDisp, and wMap.
Referenced by actIntDispatcher::i_finit(), and load_map_bmp().
aciCheckItemCredits()
int aciCheckItemCredits (void)
 {
     int cr = aciGetCurCredits();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(((uvsActInt*)aScrDisp -> curItem -> uvsDataPtr) -> price > cr) return 0;
         return 1;
     }
     return 0;
 }
References aciGetCurCredits(), and aScrDisp.
Referenced by actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_quant_l(), and actIntDispatcher::inv_mouse_quant_r().
aciCheckSellItem()
int aciCheckSellItem (void)
 {
     int x = iMouseX;
     iScreenObject* p;
     iAVIElement* el = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(!el) return 0;
     p = (iScreenObject*)el -> owner;
     if(p -> owner) x += ((iScreen*)p -> owner) -> ScreenOffs;
     if(p -> CheckXY(x,iMouseY)) return 1;
     return 0;
 }
References ACI_MECHOS_AVI_ID, aScrDisp, iMouseX, and iMouseY.
aciChooseShopItem()
void aciChooseShopItem (void)
 {
     int x,y,id;
     invItem* p;
     invMatrix* m;
     fncMenu* mn;
     fncMenuItem* itm;
     mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(!mn) return;
     itm = mn -> curItem;
     x = iMouseX;
     y = iMouseY;
     if(!mn -> check_xy(x,y)) return;
     if(mn -> change(x,y)){
         switch(iEvLineID){
             case MECHOS_LIST_MODE:
                 m = aScrDisp -> get_imatrix(mn -> curFunction);
                 iShopItem = (iListElement*)m;
                 aciInitAviID();
                 aciInitShopAvi();
                 mn -> flags &= ~FM_ACTIVE;
                 break;
             case ITEMS_LIST_MODE:
                 p = aScrDisp -> get_iitem(mn -> curFunction);
                 iShopItem = (iListElement*)p;
                 aciInitAviID();
                 aciInitShopAvi();
                 mn -> flags &= ~FM_ACTIVE;
                 break;
             case WEAPONS_LIST_MODE:
                 p = aScrDisp -> get_iitem(mn -> curFunction);
                 iShopItem = (iListElement*)p;
                 aciInitAviID();
                 aciInitShopAvi();
                 mn -> flags &= ~FM_ACTIVE;
                 break;
         }
     }
     else {
         if(iEvLineID == MECHOS_LIST_MODE || iEvLineID == MECHOS_MODE){
             id = ((invMatrix*)iShopItem) -> type;
             if(id != mn -> curFunction){
                 aciSetShopItem(mn -> curFunction);
                 iScrDisp -> end_event();
             }
         }
         else {
             id = ((invItem*)iShopItem) -> ID;
             if(id != mn -> curFunction){
                 aciSetShopItem(mn -> curFunction);
                 iScrDisp -> end_event();
             }
         }
         aciInitAviID();
         aciInitShopAvi();
         if(itm == mn -> curItem)
             mn -> flags &= ~FM_ACTIVE;
     }
 }
References aciInitAviID(), aciInitShopAvi(), aScrDisp, iEvLineID, iMouseX, iMouseY, iShopItem, MECHOS_LIST_MODE, and SHOP_ITEMS_MENU_ID.
Referenced by actIntDispatcher::EventQuant().
aciGetCurCycle()
int aciGetCurCycle (void)
 {
 #ifdef _ACI_ESCAVE_DEBUG_
     return 1;
 #else
     return uvsCurrentCycle;
 #endif
 }
aciGetCurMatrixPrice()
int aciGetCurMatrixPrice (void)
 {
     int price = 0;
 //    invItem* p;
     uvsActInt* u;
     if(!aScrDisp -> curMatrix) return 0;
     u = (uvsActInt*)aScrDisp -> curMatrix -> uvsDataPtr;
     if(!u) ErrH.Abort("Bad CurMatrix...");
     price += u -> sell_price;
 /*
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         u = (uvsActInt*)p -> uvsDataPtr;
         if(!u) ErrH.Abort("Bad CurMatrix item...");
         price += u -> price;
         p = (invItem*)p -> prev;
     }
 */
     return price;
 }
References XErrorHandler::Abort(), aScrDisp, curMatrix, and ErrH.
Referenced by actIntDispatcher::inv_mouse_imove_quant().
aciGetEleech()
void aciGetEleech (void)
 {
     listElem* el;
     uvsActInt* u;
     invItem* p,*p1;
     if(!GCharItem) return;
     u = GCharItem;
     p = aScrDisp -> get_iitem(u -> type);
     p1 = aScrDisp -> alloc_item();
     p -> clone(p1);
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         aciSell_Item(aScrDisp -> curItem);
         aScrDisp -> curItem = NULL;
     }
     aScrDisp -> flags |= AS_INV_MOVE_ITEM;
     aScrDisp -> curItem = p1;
     set_mouse_cursor(p1 -> frame,p1 -> ScreenSizeX,p1 -> ScreenSizeY);
     el = (listElem*)GGamer;
     u -> link(el);
     GGamer = (uvsActInt*)el;
     p1 -> uvsDataPtr = u;
     GCharItem = NULL;
 }
References aScrDisp, and GCharItem.
Referenced by actIntDispatcher::EventQuant().
aciGetItemLoad()
char * aciGetItemLoad (invItem * p, int mode)
 {
     char* ptr;
     aciXConv -> init();
     if(p -> pTemplate){
         switch(mode){
             case 0:
                 if(p -> flags & INV_ITEM_SHOW_ESCAVE){
                     if(p -> item_ptr)
                         sprintf(aciXConv -> address(),p -> pTemplate,aciGetItemEscave(p -> item_ptr -> data1));
                 }
                 else {
                     if(p -> item_ptr)
                         sprintf(aciXConv -> address(),p -> pTemplate,p -> item_ptr -> data1);
                 }
                 break;
             case 1:
                 if(p -> flags & INV_ITEM_SHOW_ESCAVE){
                     if(p -> uvsDataPtr)
                         sprintf(aciXConv -> address(),p -> pTemplate,aciGetItemEscave(((uvsActInt*)p -> uvsDataPtr) -> param2));
                 }
                 else {
                     if(p -> uvsDataPtr)
                         sprintf(aciXConv -> address(),p -> pTemplate,((uvsActInt*)p -> uvsDataPtr) -> param2);
                 }
                 break;
         }
     }
     ptr = aciXConv -> address();
     return ptr;
 }
References aciXConv.
Referenced by actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::put_in_slot(), and actIntDispatcher::set_move_item().
aciGetPrice()
char * aciGetPrice (iListElement * p, int mode, int sell_mode)
 {
     char* ptr;
     invItem* it;
     invMatrix* m;
     uvsActInt* u;
     if(mode == MECHOS_MODE){
         m = (invMatrix*)p;
         u = (uvsActInt*)m -> uvsDataPtr;
     }
     else {
         it = (invItem*)p;
         u = (uvsActInt*)it -> uvsDataPtr;
     }
     aciXConv -> init();
     if(!u){
         *aciXConv < aciSTR_UNDEFINED_PRICE;
         return aciXConv -> address();
     }
     *aciXConv < aciSTR_PRICE;
     if(sell_mode)
         *aciXConv <= u -> sell_price < " $";
     else
         *aciXConv <= u -> price < " $";
     ptr = aciXConv -> address();
     return ptr;
 }
References aciSTR_PRICE, aciSTR_UNDEFINED_PRICE, aciXConv, and MECHOS_MODE.
Referenced by aciInitMechosInfo(), actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_imove_quant(), and actIntDispatcher::set_move_item().
aciGetRubox()
void aciGetRubox (void)
 {
     uvsActInt* p;
     invItem* itm;
     listElem* el = (listElem*)GGamer;
     if(!aciPutItem(ACI_RUBOX,-1,-1)) ErrH.Abort("aciPutItem() failed...");
     itm = (invItem*)aScrDisp -> curMatrix -> items -> last;
     aScrDisp -> curMatrix -> remove_item(itm);
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         aciSell_Item(aScrDisp -> curItem);
         aScrDisp -> curItem = NULL;
     }
     aScrDisp -> flags |= AS_INV_MOVE_ITEM;
     aScrDisp -> curItem = itm;
     set_mouse_cursor(itm -> frame,itm -> ScreenSizeX,itm -> ScreenSizeY);
     p = new uvsActInt;
     p -> type = ACI_RUBOX;
     itm -> uvsDataPtr = p;
     p -> link(el);
     GGamer = (uvsActInt*)el;
 }
References XErrorHandler::Abort(), ACI_RUBOX, aciPutItem(), aScrDisp, curMatrix, ErrH, and GGamer.
Referenced by actIntDispatcher::EventQuant().
aciGetScreenMechos()
int aciGetScreenMechos (int x, int y)
 {
 //  BaseObject* p;
 //  BaseObject* mp;
     int tx,ty,dx,dy,l;
 //  Vector vCheck;
 //  mp = NULL;
     S2G(x,y,tx,ty);
 //  vCheck = Vector(getDistX(tx,ViewX),getDistY(ty,ViewY),0);
 /*  p = (BaseObject*)(ActD.Tail);
     while(p){
         if(p->Visibility == VISIBLE){
             dx = getDistX(tx,p->R_curr.x);
             dy = getDistY(ty,p->R_curr.y);
             l = p->radius + ACI_CHECK_RADIUS;
             if((dx*dx + dy*dy) < l*l){
                 mp = p;
                 return 1;
             };
         };
         p = (BaseObject*)(p->NextTypeList);
     };*/
     if(ActD.Active){
         dx = getDistX(tx,ActD.Active->R_curr.x);
         dy = getDistY(ty,ActD.Active->R_curr.y);
         l = ActD.Active->radius + ACI_CHECK_RADIUS;
         if((dx*dx + dy*dy) < l*l) return 1;
     };
     return 0;
 };
References ACI_CHECK_RADIUS, ActD, ActionDispatcher::Active, getDistX(), getDistY(), Object::radius, S2G(), Object::x, and Object::y.
Referenced by actIntDispatcher::inv_mouse_move_quant().
aciHandleCameraEvent()
void aciHandleCameraEvent (int code, int data)
 {
     aciBitmapMenu* m;
     aciBitmapMenuItem* p;
     switch(code){
         case BMENU_ITEM_ROT:
             camera_rotate_enable = data;
             iScrOpt[iCAMERA_TURN]->SetValueINT(data);
             if(RAM16 && data){
                 camera_moving_xy_enable = camera_moving_z_enable = 0;
                 camera_slope_enable = 0;
             }
             break;
         case BMENU_ITEM_ZOOM:
             camera_moving_xy_enable = camera_moving_z_enable = data;
             iScrOpt[iCAMERA_SCALE]->SetValueINT(data);
             if(RAM16 && data){
                 camera_rotate_enable = 0;
                 camera_slope_enable = 0;
             }
             break;
         case BMENU_ITEM_PERSP:
             camera_slope_enable = data;
             iScrOpt[iCAMERA_SLOPE]->SetValueINT(data);
             if(RAM16 && data){
                 camera_moving_xy_enable = camera_moving_z_enable = 0;
                 camera_rotate_enable = 0;
             }
             break;
     }
     if(RAM16 && data){
         m = aScrDisp -> get_bmenu(BMENU_CAMERAS_MENU);
         if(m){
             p = (aciBitmapMenuItem*)m -> items -> last;
             while(p){
                 if(p -> ID != code) p -> curState = 0;
                 p = (aciBitmapMenuItem*)p -> prev;
             }
         }
     }
     iSaveData();
 }
References aScrDisp, BMENU_CAMERAS_MENU, BMENU_ITEM_PERSP, BMENU_ITEM_ROT, BMENU_ITEM_ZOOM, camera_moving_xy_enable, camera_moving_z_enable, camera_rotate_enable, camera_slope_enable, iCAMERA_SCALE, iCAMERA_SLOPE, iCAMERA_TURN, iSaveData(), iScrOpt, prev, RAM16, and iScreenOption::SetValueINT().
Referenced by aciBitmapMenu::change().
aciHandleSubmenuEvent()
void aciHandleSubmenuEvent (int id, fncMenuItem * p)
 {
     if(p -> eventPtr){
         aci_SendEvent(p -> eventPtr -> code,p -> eventPtr -> data);
         return;
     }
     switch(id){
         case FMENU_TARGETS_MENU:
             if(strcmp(p -> name,aciSTR_OFF)){
                 SelectCompasTarget(p -> name);
             }
             else {
                 SelectCompasTarget(NULL);
             }
             break;
         case FMENU_TELEPORT_MENU:
             aciTeleportEvent = p -> fnc_code;
             break;
     }
 }
References aci_SendEvent(), aciSTR_OFF, aciTeleportEvent, FMENU_TARGETS_MENU, FMENU_TELEPORT_MENU, NULL, and SelectCompasTarget().
Referenced by fncMenu::change().
aciInitAviObject()
void aciInitAviObject (void)
 {
     fncMenu* mn;
     iScreenObject* obj;
     iAVIElement* avi;
     avi = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(avi){
         obj = (iScreenObject*)avi -> owner;
         if(obj -> flags & OBJ_TRIGGER){
             ((iTriggerObject*)obj) -> state = 0;
             ((iTriggerObject*)obj) -> trigger_init();
         }
     }
     mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(mn) mn -> flags &= ~FM_ACTIVE;
     switch(iEvLineID){
         case MECHOS_LIST_MODE:
             iEvLineID = MECHOS_MODE;
             break;
         case ITEMS_LIST_MODE:
             iEvLineID = ITEMS_MODE;
             break;
         case WEAPONS_LIST_MODE:
             iEvLineID = WEAPONS_MODE;
             break;
     }
     aciCurAviIndex = ACI_PICTURE_AVI_ENG;
 }
References ACI_MECHOS_AVI_ID, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciInitCurMatrixPtr()
void aciInitCurMatrixPtr (void)
 {
     aScrDisp -> curMatrix -> uvsDataPtr = GGamerMechos;
 }
References aScrDisp, curMatrix, and GGamerMechos.
Referenced by actIntDispatcher::swap_matrices().
aciInitEvLineID()
void aciInitEvLineID (void)
 {
     fncMenu* mn;
     iTriggerObject* p = (iTriggerObject*)aScrDisp -> curLocData -> objList[ACI_TRIGGER_ID];
     if(!p) return;
     if(GMechos){
         p -> state = 2;
         p -> init_state();
     }
     else {
         p -> state = 0;
         p -> init_state();
     }
     iEvLineID = p -> state + 1;
     p = (iTriggerObject*)aScrDisp -> curLocData -> objList[ACI_AVI_OBJ_ID];
     if(p){
         mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
         if(mn) mn -> flags &= ~FM_ACTIVE;
         p -> state = 0;
         p -> init_state();
     }
     switch(uvsBunchNumber){
         case 2:
             aciCurAviIndexDelta = 0;
             break;
         case 0:
             aciCurAviIndexDelta = ACI_PICTURE_AVI_ENG2;
             break;
         case 1:
             aciCurAviIndexDelta = ACI_PICTURE_AVI_ENG3;
             break;
     }
 }
References ACI_AVI_OBJ_ID, ACI_TRIGGER_ID, aScrDisp, GMechos, iEvLineID, and SHOP_ITEMS_MENU_ID.
Referenced by aciNextShopItem(), aciPrevShopItem(), aciSetShopItem(), and actIntDispatcher::i_init().
aciInitInfoPanels()
void aciInitInfoPanels (void)
 {
     InfoPanel* pl;
     CounterPanel* cp;
     iBitmapElement* el;
     fncMenu* mn;
     iScreenObject* obj;
     iScreen* scr;
     iAVIElement* avi;
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_QUEST_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_QUEST_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_ANSWER_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_TIME_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_SHOP_TIME_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_PRICE_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_PRICE_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_INFO_PANEL_ID];
     pl = aScrDisp -> iscr_iP;
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_CREDITS_PANEL_ID];
     cp = aScrDisp -> get_icounter(ACI_CREDITS_PANEL);
     if(el && cp){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         cp -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         cp -> PosY = obj -> PosY + el -> lY;
         cp -> iScreenOwner = el;
         cp -> SizeX = el -> bSizeX;
         cp -> SizeY = el -> bSizeY;
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_QUEST_PANEL_ID];
     mn = aScrDisp -> get_imenu(ACI_QUEST_MENU);
     if(aScrDisp -> qMenu && el){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         aScrDisp -> qMenu -> data = el;
         aScrDisp -> qMenu -> ScreenX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         aScrDisp -> qMenu -> ScreenY = obj -> PosY + el -> lY;
         aScrDisp -> qMenu -> ScreenSizeX = obj -> SizeX;
         aScrDisp -> qMenu -> ScreenSizeY = obj -> SizeY;
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_ITEMS_MENU_ID];
     mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(mn && el){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         mn -> iScreenOwner = el;
         mn -> SizeX = el -> bSizeX;
         mn -> SizeY = el -> bSizeY;
         mn -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         mn -> PosY = obj -> PosY + el -> lY;
         aScrDisp -> clear_menu(mn);
     }
     avi = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(avi){
         obj = (iScreenObject*)avi -> owner;
         if(obj -> flags & OBJ_TRIGGER){
             ((iTriggerObject*)obj) -> state = 0;
             ((iTriggerObject*)obj) -> trigger_init();
         }
     }
 }
References ACI_ANSWER_PANEL, ACI_ANSWER_PANEL_ID, ACI_CREDITS_PANEL, ACI_CREDITS_PANEL_ID, ACI_INFO_PANEL_ID, ACI_ITEMS_MENU_ID, ACI_MECHOS_AVI_ID, ACI_PRICE_PANEL, ACI_PRICE_PANEL_ID, ACI_QUEST_MENU, ACI_QUEST_PANEL, ACI_QUEST_PANEL_ID, ACI_SHOP_TIME_PANEL, ACI_TIME_PANEL_ID, aScrDisp, and SHOP_ITEMS_MENU_ID.
Referenced by actIntDispatcher::i_init().
aciInitItmTextQueue()
void aciInitItmTextQueue (void)
 {
     int i;
     invItem* p;
     for(i = 0; i < ACI_ITEM_QUEUE_MAX; i ++){
         aciItmTextQueue[i] = NULL;
     }
     aciItmTextQueueSize = aciItmTextQueueCur = 0;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         if(aciItmTextQueueSize < ACI_ITEM_QUEUE_MAX && p -> ID == ACI_TABUTASK && (p -> flags & INV_ITEM_NEW)){
             aciItmTextQueue[aciItmTextQueueSize] = p;
             aciItmTextQueueSize ++;
         }
         p = (invItem*)p -> prev;
     }
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         if(aciItmTextQueueSize < ACI_ITEM_QUEUE_MAX && (p -> ID == ACI_ELEEPOD || p -> ID == ACI_BEEBOORAT || p -> ID == ACI_ZEEX) && (p -> flags & INV_ITEM_NEW)){
             aciItmTextQueue[aciItmTextQueueSize] = p;
             aciItmTextQueueSize ++;
         }
         p = (invItem*)p -> prev;
     }
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         p -> flags &= ~INV_ITEM_NEW;
         p = (invItem*)p -> prev;
     }
 }
References ACI_ITEM_QUEUE_MAX, ACI_TABUTASK, aciItmTextQueue, aciItmTextQueueCur, aciItmTextQueueSize, aScrDisp, curMatrix, and NULL.
Referenced by actIntDispatcher::i_finit().
aciInitMechosInfo()
void aciInitMechosInfo (invMatrix * p, InfoPanel * ip)
 {
     ip -> free_list();
     if(p){
         ip -> add_item(p -> mech_name,-1,aciCurColorScheme[FM_SELECT_COL]);
         if(!uvsCurrentWorldUnable){
             if(GMechos)
                 ip -> add_item(aciGetPrice((iListElement*)p,MECHOS_MODE,1));
         }
         ip -> set_redraw();
     }
 }
References aciCurColorScheme, aciGetPrice(), FM_SELECT_COL, GMechos, MECHOS_MODE, and uvsCurrentWorldUnable.
Referenced by actIntDispatcher::inv_mouse_imove_quant().
aciInitShopAvi()
void aciInitShopAvi (void)
 {
     iAVIElement* avi;
     avi = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(!avi) return;
     avi -> change_avi(avi -> avi_name);
     avi -> init_size();
     avi -> init_align();
 }
References ACI_MECHOS_AVI_ID, and aScrDisp.
Referenced by aciChooseShopItem(), and actIntDispatcher::EventQuant().
aciInitShopButtons()
void aciInitShopButtons (void)
 {
     iScreenObject* obj;
     iScreenElement* p,*p1,*p2,*p3,*p4;
     fncMenu* mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     p = NULL;
     p1 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_WEAPONS_BUTTON_ID];
     p2 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_BUTTON_ID];
     p3 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_ITEMS_BUTTON_ID];
     p4 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_MENU_BUTTON_ID];
     if(p1){
         obj = (iScreenObject*)p1 -> owner;
         p1 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
         obj -> flags |= OBJ_MUST_REDRAW;
     }
     if(p2){
         obj = (iScreenObject*)p2 -> owner;
         p2 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
         obj -> flags |= OBJ_MUST_REDRAW;
     }
     if(p3){
         obj = (iScreenObject*)p3 -> owner;
         p3 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
         obj -> flags |= OBJ_MUST_REDRAW;
     }
     if(p4){
         obj = (iScreenObject*)p4 -> owner;
         obj -> flags |= OBJ_MUST_REDRAW;
         if(mn && mn -> flags & FM_ACTIVE)
             p4 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_ON_TYPE]);
         else
             p4 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
     }
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
         case CHANGE_2_MECHOS_MODE:
             p = p2;
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             p = p1;
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
             p = p3;
             break;
     }
     if(p){
         p -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_ON_TYPE]);
     }
 }
References ACI_BUTTON_OFF_TYPE, ACI_ITEMS_BUTTON_ID, ACI_MECHOS_BUTTON_ID, ACI_MENU_BUTTON_ID, ACI_WEAPONS_BUTTON_ID, aScrDisp, NULL, and SHOP_ITEMS_MENU_ID.
Referenced by actIntDispatcher::EventQuant().
aciInitShopItems()
void aciInitShopItems (void)
 {
     invItem* p;
     invMatrix* m;
     uvsActInt* u;
 #ifdef _ACI_LOGFILE_
     aScrDisp -> logFile.open(aciLogFileName,XS_OUT | XS_APPEND | XS_NOREPLACE);
     aScrDisp -> logFile < "\r\nLocation: " < aci_curLocationName;
 #endif
     p = (invItem*)aScrDisp -> i_itemList -> last;
     while(p){
         p -> uvsDataPtr = NULL;
         p = (invItem*)p -> prev;
     }
     m = (invMatrix*)aScrDisp -> i_matrixList -> last;
     while(m){
         m -> uvsDataPtr = NULL;
         m = (invMatrix*)m -> prev;
     }
     if(aScrDisp -> curMatrix){
         p = (invItem*)aScrDisp -> curMatrix -> items -> last;
         while(p){
             p -> uvsDataPtr = NULL;
             p = (invItem*)p -> prev;
         }
     }
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\n\r\nShopItems :\r\n";
 #endif
     u = GMechos;
     while(u){
         m = aScrDisp -> get_imatrix(u -> type);
         if(m && !m -> uvsDataPtr)
             m -> uvsDataPtr = u;
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\nMechos \"" < m -> mech_name < "\"";
 #endif
         u = (uvsActInt*)u -> next;
     }
     u = GItem;
     while(u){
         p = aScrDisp -> get_iitem(u -> type);
         if(p && !p -> uvsDataPtr)
             p -> uvsDataPtr = u;
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\nItem \"" < p -> ID_ptr < "\"";
 #endif
         u = (uvsActInt*)u -> next;
     }
     if(aScrDisp -> curMatrix){
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\n\r\nGamerItems :\r\n";
 #endif
         p = (invItem*)aScrDisp -> curMatrix -> items -> last;
         while(p){
             p -> uvsDataPtr = NULL;
 #ifdef _ACI_LOGFILE_
             aScrDisp -> logFile < "\r\n" < p -> ID_ptr;
 #endif
             p = (invItem*)p -> prev;
         }
         u = GGamer;
         while(u){
             p = (invItem*)aScrDisp -> curMatrix -> items -> last;
             while(p){
                 if(!p -> uvsDataPtr && p -> ID == u -> type && p -> MatrixX == u -> pos_x && p -> MatrixY == u -> pos_y){
                     p -> uvsDataPtr = u;
                     break;
                 }
                 p = (invItem*)p -> prev;
             }
             u = (uvsActInt*)u -> next;
         }
         p = (invItem*)aScrDisp -> curMatrix -> items -> last;
         while(p){
             if(!p -> uvsDataPtr)
                 ErrH.Abort("aciInitShopItems failed...");
             p = (invItem*)p -> prev;
         }
         aScrDisp -> curMatrix -> uvsDataPtr = GGamerMechos;
     }
     aciChangeList();
 #ifdef _ACI_LOGFILE_
     aScrDisp -> logFile.close();
 #endif
 }
References aci_curLocationName, aScrDisp, curMatrix, GMechos, NULL, prev, XS_APPEND, XS_NOREPLACE, and XS_OUT.
Referenced by actIntDispatcher::i_init().
aciInitShopList()
void aciInitShopList (void)
 {
     switch(iEvLineID){
         case MECHOS_LIST_MODE:
             iEvLineID = MECHOS_MODE;
             aciCloseShopMenu();
             break;
         case ITEMS_LIST_MODE:
             iEvLineID = ITEMS_MODE;
             aciCloseShopMenu();
             break;
         case WEAPONS_LIST_MODE:
             iEvLineID = WEAPONS_MODE;
             aciCloseShopMenu();
             break;
         case MECHOS_MODE:
         case ITEMS_MODE:
         case WEAPONS_MODE:
             aciBuildShopList();
             break;
     }
 }
References aciBuildShopList(), aciCloseShopMenu(), iEvLineID, ITEMS_LIST_MODE, ITEMS_MODE, MECHOS_LIST_MODE, MECHOS_MODE, WEAPONS_LIST_MODE, and WEAPONS_MODE.
Referenced by actIntDispatcher::EventQuant().
aciML_Pause()
void aciML_Pause (void)
 {
     PauseIMLall();
     aciML_D -> flags |= AML_PAUSE;
 }
References aciML_D, and PauseIMLall().
Referenced by actIntDispatcher::EventQuant().
aciML_Resume()
void aciML_Resume (void)
 {
     ResumeIMLall();
     aciML_D -> flags &= ~AML_PAUSE;
 }
References aciML_D, and ResumeIMLall().
Referenced by actIntDispatcher::EventQuant().
aciNextPhrase()
void aciNextPhrase (void)
 {
     unsigned char* str;
     iScreenObject* obj;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p || !p -> iScreenOwner) return;
     if(aciEscaveDead){
         aciClearQuestMenu();
         obj = (iScreenObject*)p -> iScreenOwner -> owner;
         p -> free_list();
         str = (unsigned char*)dgD -> getQdead();
         if(str) aciInitPanel(p,str);
         p -> set_redraw();
         return;
     }
     if(!aciSpeechStarted && dgD -> isEnd())
         aciSpeechEndLocked = aciSpeechBegLocked = aciEndSpeech = 1;
     aciClearQuestMenu();
     obj = (iScreenObject*)p -> iScreenOwner -> owner;
     p -> free_list();
     str = (unsigned char*)dgD -> getNextPhrase();
     if(aciEndSpeech){
         if(!dgD -> isEnd()){
             aciEndSpeech = 0;
         }
         else {
             p -> set_redraw();
             return;
         }
     }
     if(str)
         aciInitPanel(p,str);
     aciSpeechEndLocked = dgD -> isEnd();
     if(str && !aciEscaveEmpty)
         aciStartSpeech();
     p -> set_redraw();
 }
Referenced by actIntDispatcher::EventQuant().
aciNextShopItem()
void aciNextShopItem (void)
 {
     invItem* p,*fp;
     invMatrix* m,*fm;
     if(!iShopItem){
         aciInitEvLineID();
         aciChangeList();
         return;
     }
     aciShopMenuDown();
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
             fm = (invMatrix*)iShopItem;
             m = (invMatrix*)fm -> next;
             if(m != fm){
                 while(!m -> uvsDataPtr){
                     m = (invMatrix*)m -> next;
                     if(m == fm) break;
                 }
                 if(!m -> uvsDataPtr){
                     iShopItem = NULL;
                 }
                 else {
                     iShopItem = (iListElement*)m;
                     aciCurMechosID = m -> type;
                 }
             }
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> next;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS){
                     p = (invItem*)p -> next;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> next;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS){
                     p = (invItem*)p -> next;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
     }
     aciInitAviID();
 }
References aciChangeList(), aciInitEvLineID(), aciShopMenuDown(), iEvLineID, iShopItem, MECHOS_LIST_MODE, and MECHOS_MODE.
Referenced by actIntDispatcher::EventQuant().
aciPay4Item()
void aciPay4Item (invItem * p)
 {
     int cr = aciGetCurCredits();
     uvsActInt* u = (uvsActInt*)p -> uvsDataPtr;
     cr -= u -> price;
     aciUpdateCurCredits(cr);
     p -> flags &= ~INV_ITEM_NO_PAY;
 }
References aciGetCurCredits(), and aciUpdateCurCredits().
Referenced by actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_quant_l(), and actIntDispatcher::inv_mouse_quant_r().
aciPrepareScreenText()
void aciPrepareScreenText (char * ptr, int sz, int max_len)
 {
     int i,offs_start,offs_end,offs;
 //    XStream fh("text0.dat",XS_OUT);
 //    fh.write(ptr,sz);
 //    fh.close();
     offs_start = offs_end = 0;
     while(offs_start < sz - 1){
         while(ptr[offs_end] != '\n'){
             offs_end ++;
             if(offs_end >= sz){
                 offs_end = sz - 1;
                 break;
             }
         }
         if(offs_end - offs_start > max_len){
             offs = offs_start + max_len;
             for(i = 0; i < max_len; i ++){
                 if(ptr[offs] == ' ' || ptr[offs] == '\t'){
                     break;
                 }
                 offs --;
                 if(offs <= offs_start){
                     break;
                 }
             }
             ptr[offs] = '\n';
             if(offs > offs_start){
                 offs_start = offs;
                 offs_end = offs + 1;
             }
             else {
                 offs_start = offs_end;
                 offs_end ++;
             }
         }
         else {
             offs_start = offs_end;
             offs_end ++;
         }
     }
 //    fh.open("text1.dat",XS_OUT);
 //    fh.write(ptr,sz);
 //    fh.close();
 }
Referenced by aciScreenText::alloc().
aciPrepareWorldsMenu()
void aciPrepareWorldsMenu (void)
 {
     int i;
     aciWorldInfo* p1;
     if(CurrentWorld == -1) return;
     fncMenu* p = aScrDisp -> get_menu(FMENU_WORLDS_MENU);
     if(p){
         p -> prepare_items();
         for(i = 0; i < AS_MAX_WORLD; i ++){
             if(!aScrDisp -> wMap -> world_key(i)){
                 p -> deactivate_item(1000 + i);
             }
         }
         if(aScrDisp -> flags & AS_WORLDS_INIT){
             p1 = (aciWorldInfo*)aScrDisp -> wMap -> world_list -> last;
             while(p1){
                 if(p1 -> uvsID == CurrentWorld) p -> deactivate_item(1000 + p1 -> ID);
                 p1 = (aciWorldInfo*)p1 -> prev;
             }
         }
     }
 }
Referenced by actIntDispatcher::i_finit().
aciPrevShopItem()
void aciPrevShopItem (void)
 {
     invItem* p,*fp;
     invMatrix* m,*fm;
     if(!iShopItem){
         aciInitEvLineID();
         aciChangeList();
         return;
     }
     aciShopMenuUp();
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
             fm = (invMatrix*)iShopItem;
             m = (invMatrix*)fm -> prev;
             if(!m) m = (invMatrix*)aScrDisp -> i_matrixList -> last;
             while(!m -> uvsDataPtr){
                 m = (invMatrix*)m -> prev;
                 if(!m) m = (invMatrix*)aScrDisp -> i_matrixList -> last;
                 if(m == fm) break;
             }
             if(!m -> uvsDataPtr){
                 iShopItem = NULL;
             }
             else {
                 iShopItem = (iListElement*)m;
                 aciCurMechosID = m -> type;
             }
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> prev;
             if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS){
                     p = (invItem*)p -> prev;
                     if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> prev;
             if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS){
                     p = (invItem*)p -> prev;
                     if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
     }
     aciInitAviID();
 }
References aciChangeList(), aciCurMechosID, aciInitAviID(), aciInitEvLineID(), aciShopMenuUp(), AS_ITEM_CLASS, AS_WEAPON_CLASS, aScrDisp, CHANGE_2_ITEMS_MODE, CHANGE_2_WEAPONS_MODE, iEvLineID, iShopItem, ITEMS_LIST_MODE, ITEMS_MODE, MECHOS_LIST_MODE, MECHOS_MODE, NULL, prev, WEAPONS_LIST_MODE, and WEAPONS_MODE.
Referenced by actIntDispatcher::EventQuant().
aciPutBufSpr()
void aciPutBufSpr (int x, int y, int sx, int sy, int bsx, void * src, void * dest, int col, int col_sz)
 {
     int i,j,dest_index,src_index;
     unsigned src_col;
     unsigned char* src_buf,*dest_buf;
     dest_index = x + y * bsx;
     src_index = 0;
     src_buf = (unsigned char*)src;
     dest_buf = (unsigned char*)dest;
     if(!col_sz){
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 src_col = src_buf[src_index + j];
                 if(src_col)
                     dest_buf[dest_index + j] = col + src_col;
             }
             dest_index += bsx;
             src_index += sx;
         }
     }
     else {
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 src_col = src_buf[src_index + j];
                 if(src_col)
                     dest_buf[dest_index + j] = col + (src_col >> col_sz);
             }
             dest_index += bsx;
             src_index += sx;
         }
     }
 }
Referenced by aPutStr32(), and aIndData::build_pict().
aciPutTreasureItem()
void aciPutTreasureItem (void)
 {
     uvsActInt* p;
     if(!GTreasureItem) return;
     p = GTreasureItem;
     while(p){
         aciML_D -> curDataSet -> put_item(p -> type);
         p = (uvsActInt*)p -> next;
     }
 }
References aciML_D, and GTreasureItem.
Referenced by actIntDispatcher::i_init().
aciReadItmText()
void aciReadItmText (void)
 {
     invItem* p;
     p = aciItmTextQueue[aciItmTextQueueCur];
     aciItmTextQueueCur ++;
     if(aciItmTextQueueCur >= aciItmTextQueueSize)
         aciItmTextQueueCur = aciItmTextQueueSize = 0;
     if(p && p -> EvCode)
         aScrDisp -> send_event(p -> EvCode,0,p -> item_ptr);
 }
References aciItmTextQueue, aciItmTextQueueCur, aciItmTextQueueSize, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciSell_Item()
void aciSell_Item (invItem * p)
 {
     int cr;
     invItem* it = aScrDisp -> get_iitem(p -> ID);
     uvsActInt* ptr = (uvsActInt*)p -> uvsDataPtr;
     listElem* el = (listElem*)GItem;
     if(!ptr) ErrH.Abort("Bad sell item...");
     ptr -> delink(GGamer);
     ptr -> link(el);
     GItem = (uvsActInt*)el;
     if(!(p -> flags & INV_ITEM_NO_PAY))
         uvsActIntSell(ptr);
     if(!it -> uvsDataPtr && (!aScrDisp -> curLocData -> ExcludeItems[p -> ID] || (p -> flags & INV_ITEM_NO_PAY))){
         it -> uvsDataPtr = ptr;
     }
     if(!(p -> flags & INV_ITEM_NO_PAY)){
         cr = aciGetCurCredits();
         cr += ptr -> sell_price;
         aciUpdateCurCredits(cr);
     }
     aScrDisp -> free_item(p);
 }
References XErrorHandler::Abort(), aScrDisp, ErrH, GGamer, and GItem.
Referenced by aciSell_Matrix(), and actIntDispatcher::i_finit().
aciSell_Matrix()
void aciSell_Matrix (invMatrix * p)
 {
     int cr;
     invItem* itm = (invItem*)p -> items -> last,*itm1;
     uvsActInt* ptr = (uvsActInt*)p -> uvsDataPtr;
     if(!ptr) ErrH.Abort("Bad sell mechos...");
     while(itm){
         itm1 = (invItem*)itm -> prev;
         p -> items -> dconnect((iListElement*)itm);
         aciSell_Item(itm);
         itm = itm1;
     }
     cr = aciGetCurCredits();
     cr += ptr -> sell_price;
     aciUpdateCurCredits(cr);
 }
References XErrorHandler::Abort(), aciGetCurCredits(), aciSell_Item(), aciUpdateCurCredits(), ErrH, and prev.
Referenced by actIntDispatcher::swap_matrices().
aciSellMoveItem()
void aciSellMoveItem (void)
 {
     int i,id,fl = 0,index,exclude = 1;
     invItem* p,*p1;
     invMatrix* m,*m1;
     uvsActInt* u,*pu;
     iListElement* prev_item = iShopItem;
     int change_mode = 0,prev_mode = iEvLineID;
     if(!(aScrDisp -> flags & AS_INV_MOVE_ITEM)) return;
     p = aScrDisp -> curItem;
     p1 = aScrDisp -> get_iitem(p -> ID);
     pu = (uvsActInt*)p -> uvsDataPtr;
     if(!uvsCurrentWorldUnable && p -> partData){
         index = -1;
         m = (invMatrix*)aScrDisp -> i_matrixList -> last;
         while(m){
             for(i = 0; i < 2; i ++){
                 if(m -> uvsDataPtr && m -> type == p -> partData -> baseID[i])
                     index = i;
             }
             m = (invMatrix*)m -> prev;
         }
         if(index != -1)
             fl = 1;
     }
     if(!fl){
         id = p -> ID;
         if(p -> flags & INV_ITEM_NO_PAY) exclude = 0;
         if(p -> classID == AS_ITEM_CLASS && prev_mode != ITEMS_MODE && prev_mode != ITEMS_LIST_MODE){
             change_mode = CHANGE_2_ITEMS_MODE;
             if(iEvLineID != ITEMS_MODE && iEvLineID != ITEMS_LIST_MODE)
                 iEvLineID = change_mode;
         }
         if(p -> classID == AS_WEAPON_CLASS && prev_mode != WEAPONS_MODE && prev_mode != WEAPONS_LIST_MODE){
             change_mode = CHANGE_2_WEAPONS_MODE;
             if(iEvLineID != WEAPONS_MODE && iEvLineID != WEAPONS_LIST_MODE)
                 iEvLineID = change_mode;
         }
         aciSell_Item(p);
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         if(!exclude || !aScrDisp -> curLocData -> ExcludeItems[id]){
             iShopItem = p1;
         }
         else {
             aciRemoveUvsItem(pu);
             iShopItem = prev_item;
             switch(prev_mode){
                 case ITEMS_MODE:
                 case ITEMS_LIST_MODE:
                     change_mode = CHANGE_2_ITEMS_MODE;
                     break;
                 case WEAPONS_MODE:
                 case WEAPONS_LIST_MODE:
                     change_mode = CHANGE_2_WEAPONS_MODE;
                     break;
                 case MECHOS_MODE:
                 case MECHOS_LIST_MODE:
                     change_mode = CHANGE_2_MECHOS_MODE;
                     break;
             }
             iEvLineID = change_mode;
         }
     }
     else {
         m = aScrDisp -> get_imatrix(p -> partData -> baseID[index]);
         m1 = aScrDisp -> get_imatrix(p -> partData -> targetID[index]);
         if(!m || !m1)
             ErrH.Abort("Bad constructor mechos ID...");
         if(m1 -> uvsDataPtr)
             ErrH.Abort("Duplicate constructor mechos...");
         u = (uvsActInt*)m -> uvsDataPtr;
         u -> type = m1 -> type;
         m1 -> uvsDataPtr = u;
         m -> uvsDataPtr = NULL;
         iShopItem = (iListElement*)m1;
         u = (uvsActInt*)p -> uvsDataPtr;
         u -> delink(GGamer);
         delete u;
         p -> uvsDataPtr = NULL;
         if(m1 -> flags & IM_NOT_COMPLETE){
             SOUND_UNICUM_1();
         }
         else {
             SOUND_UNICUM_2();
         }
         iEvLineID = CHANGE_2_MECHOS_MODE;
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
     }
     aciInitAviID();
     restore_mouse_cursor();
     if(aScrDisp -> iscr_iP){
         aScrDisp -> iscr_iP -> free_list();
         aScrDisp -> iscr_iP -> set_redraw();
     }
     if(fl) iEvLineID = CHANGE_2_MECHOS_MODE;
     aciInitShopAvi();
 }
References aScrDisp, iEvLineID, and iShopItem.
Referenced by actIntDispatcher::EventQuant().
aciSet_aMouse()
void aciSet_aMouse (void)
 {
     MouseSizeX = aMouseSizeX;
     MouseSizeY = aMouseSizeY;
     MouseSize = aMouseSize;
     MouseFrames = aMouseFrames;
 }
Referenced by actIntDispatcher::i_finit(), and actIntDispatcher::init().
aciSet_iMouse()
void aciSet_iMouse (void)
 {
     MouseSizeX = iMouseSizeX;
     MouseSizeY = iMouseSizeY;
     MouseSize = iMouseSize;
     MouseFrames = iMouseFrames;
 }
Referenced by actIntDispatcher::i_init().
aciSetMechName()
void aciSetMechName (void)
 {
     iScreenObject* obj;
     iStringElement* str;
     if(!aScrDisp -> secondMatrix) return;
     obj = (iScreenObject*)aScrDisp -> curLocData -> objList[ACI_MECHOS_ID_OBJ];
     str = (iStringElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_ID_STR];
     if(!obj || !str) return;
     if(aScrDisp -> secondMatrix -> mech_name)
         strcpy(str -> string,aScrDisp -> secondMatrix -> mech_name);
     else
         strcpy(str -> string," ");
     str -> SizeX = str -> SizeY = 0;
     str -> lX = str -> lY = 0;
     obj -> init();
 }
References ACI_MECHOS_ID_OBJ, ACI_MECHOS_ID_STR, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciSetShopItem()
void aciSetShopItem (int id)
 {
     invItem* p;
     invMatrix* m;
     if(!iShopItem){
         aciInitEvLineID();
         aciChangeList();
         return;
     }
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
         case CHANGE_2_MECHOS_MODE:
             m = (invMatrix*)aScrDisp -> i_matrixList -> last;
             while(m){
                 if(m -> type == id){
                     iShopItem = (iListElement*)m;
                     aciCurMechosID = m -> type;
                     break;
                 }
                 m = (invMatrix*)m -> prev;
             }
             if(!m) iShopItem = NULL;
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             p = (invItem*)aScrDisp -> i_itemList -> last;
             while(p){
                 if(p -> ID == id){
                     iShopItem = (iListElement*)p;
                     break;
                 }
                 p = (invItem*)p -> prev;
             }
             if(!p) iShopItem = NULL;
             break;
     }
     aciInitAviID();
 }
References aciChangeList(), aciCurMechosID, aciInitAviID(), aciInitEvLineID(), aScrDisp, CHANGE_2_ITEMS_MODE, CHANGE_2_MECHOS_MODE, CHANGE_2_WEAPONS_MODE, iEvLineID, iShopItem, ITEMS_LIST_MODE, ITEMS_MODE, MECHOS_LIST_MODE, MECHOS_MODE, NULL, prev, WEAPONS_LIST_MODE, and WEAPONS_MODE.
Referenced by actIntDispatcher::iKeyQuant().
aciSetTimePanel()
void aciSetTimePanel (void)
 {
     char* p;
     int d,h,m,s;
     InfoPanel* iPl;
     if(aScrDisp -> flags & AS_ISCREEN)
         iPl = aScrDisp -> get_info_panel(ACI_SHOP_TIME_PANEL);
     else
         iPl = aScrDisp -> get_aci_info_panel(ACI_TIME_PANEL);
     if(!iPl) return;
     ConTimer.sTime.init();
     if(NetworkON){
         GetNetworkGameTime(d,h,m,s);
     }
     else {
         d = ConTimer.day;
         h = ConTimer.hour;
         m = ConTimer.min;
         s = ConTimer.sec;
     }
     if(d < 100) ConTimer.sTime < " ";
     if(d < 10) ConTimer.sTime < " ";
     ConTimer.sTime <= d < " ";
     if(h < 10) ConTimer.sTime < "0";
     ConTimer.sTime <= h < ":";
     if(m < 10) ConTimer.sTime < "0";
     ConTimer.sTime <= m < ":";
     if(s < 10) ConTimer.sTime < "0";
     ConTimer.sTime <= s;
     p = ConTimer.sTime.GetBuf();
     iPl -> free_list();
     iPl -> add_item(aciSTR_DAY);
     iPl -> add_item(p,-1,(aciCurColorScheme[FM_SELECT_BORDER_COL] << 8) | aciCurColorScheme[FM_SELECT_COL]);
     if(aScrDisp -> flags & AS_ISCREEN)
         iPl -> set_redraw();
 }
References aScrDisp, and iPl.
Referenced by actIntDispatcher::EventQuant().
aciShowBlockPhrase()
void aciShowBlockPhrase (void)
 {
     char* str;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p) return;
     str = dgD -> getQblock();
     if(str){
         p -> free_list();
         aciInitPanel(p,(unsigned char*)str);
         p -> set_redraw();
     }
 }
References ACI_ANSWER_PANEL, aciInitPanel(), aScrDisp, and dgD.
Referenced by actIntDispatcher::EventQuant().
aciShowFrags()
void aciShowFrags (void)
 {
     int i,num;
     XBuffer XBuf;
     PlayerData* p;
     char* world_name;
     static int fragColors[10] = { ACI_FRAG_COL0, ACI_FRAG_COL1, ACI_FRAG_COL2, ACI_FRAG_COL3, ACI_FRAG_COL4, ACI_FRAG_COL5, ACI_FRAG_COL6, ACI_FRAG_COL7, ACI_FRAG_COL8, ACI_FRAG_COL9 };
     if(!NetworkON || !players_list.size()) return;
     if(aScrDisp -> curPrompt -> NumStr){
         aScrDisp -> curPrompt -> free_mem();
         return;
     }
     iSortPlayers(1);
     num = iNumPlayers;
     aScrDisp -> curPrompt -> alloc_mem(num);
     aScrDisp -> curPrompt -> CurTimer = 0;
     aScrDisp -> curPrompt -> fontID = ACI_FRAG_FONT;
     switch(iCurMultiGame){
         case 0: // VAN-WAR...
             for(i = 0; i < num; i ++){
                 p = iPlayers[i];
                 XBuf.init();
                 world_name = aScrDisp -> wMap -> world_ptr[aScrDisp -> wMap -> world_ids[p -> body.world]] -> name;
                 XBuf < p -> name < " (" < world_name < ") : " <= p -> body.kills < " " < aciSTR_KILLS < " " <= p -> body.deaths < " " < aciSTR_DEATHS;
                 aScrDisp -> curPrompt -> add_str(i,(unsigned char*)XBuf.address());
                 aScrDisp -> curPrompt -> TimeBuf[i] = ACI_FRAG_TIMER;
                 aScrDisp -> curPrompt -> ColBuf[i] = fragColors[p -> body.color];
             }
             break;
         case 1: // MECHOSOMA...
             for(i = 0; i < num; i ++){
                 p = iPlayers[i];
                 XBuf.init();
                 world_name = aScrDisp -> wMap -> world_ptr[aScrDisp -> wMap -> world_ids[p -> body.world]] -> name;
                 XBuf < p -> name < " (" < world_name < ") : " < aciSTR_Ware1 < " " <= p -> body.MechosomaStat.ItemCount1 < "/" <= my_server_data.Mechosoma.ProductQuantity1;
                 XBuf < " " < aciSTR_Ware2 < " " <= p -> body.MechosomaStat.ItemCount2 < "/" <= my_server_data.Mechosoma.ProductQuantity2;
                 aScrDisp -> curPrompt -> add_str(i,(unsigned char*)XBuf.address());
                 aScrDisp -> curPrompt -> TimeBuf[i] = ACI_FRAG_TIMER;
                 aScrDisp -> curPrompt -> ColBuf[i] = fragColors[p -> body.color];
             }
             break;
         case 2: // PASSEMBLOSS...
             for(i = 0; i < num; i ++){
                 p = iPlayers[i];
                 XBuf.init();
                 world_name = aScrDisp -> wMap -> world_ptr[aScrDisp -> wMap -> world_ids[p -> body.world]] -> name;
                 XBuf < p -> name < " (" < world_name < ") : " < aciSTR_Checkpoints < " " <= p -> body.PassemblossStat.CheckpointLighting < "/" <= my_server_data.Passembloss.CheckpointsNumber;
                 aScrDisp -> curPrompt -> add_str(i,(unsigned char*)XBuf.address());
                 aScrDisp -> curPrompt -> TimeBuf[i] = ACI_FRAG_TIMER;
                 aScrDisp -> curPrompt -> ColBuf[i] = fragColors[p -> body.color];
             }
             break;
     }
 }
References ACI_FRAG_COL0, ACI_FRAG_COL1, ACI_FRAG_COL2, ACI_FRAG_COL3, ACI_FRAG_COL4, ACI_FRAG_COL5, ACI_FRAG_COL6, ACI_FRAG_COL7, ACI_FRAG_COL8, ACI_FRAG_COL9, ACI_FRAG_FONT, ACI_FRAG_TIMER, aciSTR_Checkpoints, aciSTR_DEATHS, aciSTR_KILLS, aciSTR_Ware1, aciSTR_Ware2, XBuffer::address(), aScrDisp, PASSEMBLOSS_PRM::CheckpointsNumber, iCurMultiGame, XBuffer::init(), iNumPlayers, iPlayers, iSortPlayers(), ServerData::Mechosoma, my_server_data, NetworkON, ServerData::Passembloss, players_list, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, XTList< Type >::size(), wMap, and PlayerData::world.
Referenced by actIntDispatcher::KeyQuant().
aciShowLocationPicture()
void aciShowLocationPicture (void)
 {
     int i,max_timer = 0;
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer)
         return;
     if(XGR_MouseVisible())
         XGR_MouseHide();
     XGR_Fill(0);
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_OPEN);
         aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
     }
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     i_evince_pal(iscrPal,8);
 }
References ACI_SHUTTER_OPEN, aScrDisp, i_evince_pal(), iscrPal, Redraw, XGR_Fill, XGR_MouseHide, and XGR_MouseVisible.
Referenced by actIntDispatcher::i_init().
aciShowRacingPlace()
void aciShowRacingPlace (void)
 {
     int x,y,dx;
     aciXConv -> init();
     *aciXConv < aciCurRaceType < " ";
     if(!(aScrDisp -> flags & AS_FULLSCR)){
         if(actintLowResFlag){
             x = aScrDisp -> curIbs -> PosX + ACI_RACING_X;
             y = aScrDisp -> curIbs -> PosY + ACI_RACING_Y;
         }
         else {
             x = aScrDisp -> curIbs -> PosX + ACI_RACING_X_H;
             y = aScrDisp -> curIbs -> PosY + ACI_RACING_Y_H;
         }
         y = XGR_MAXY - y;
     }
     else {
         if(actintLowResFlag){
             x = ACI_RACING2_X;
             y = ACI_RACING2_Y;
         }
         else {
             x = ACI_RACING2_X_H;
             y = ACI_RACING2_Y_H;
         }
         y = XGR_MAXY - y;
     }
     aOutStr(x,y,ACI_RACING_FONT,ACI_RACING_COL,(unsigned char*)aciXConv -> address(),1);
     dx = aStrLen((unsigned char*)aciXConv -> address(),ACI_RACING_FONT,1);
     aciXConv -> init();
     *aciXConv < aciCurRaceInfo;
     aOutStr(x + dx,y,ACI_RACING_FONT,ACI_RACING_COL2,(unsigned char*)aciXConv -> address(),1);
 }
References aciCurRaceType, aciXConv, and aScrDisp.
Referenced by actIntDispatcher::flush().
aciShowScMatrix()
void aciShowScMatrix (void)
 {
     _iSTORE_OFFS_;
     int i,num2,timer = 0;
     SOUND_GATE();
     iScreenObject* m_owner = NULL;
     iBitmapElement* b;
     b = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(b) m_owner = (iScreenObject*)b -> owner;
     unsigned char* fon_buf;
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
 #ifndef _ACI_NO_SHOP_ANIMATION_
     num2 = aScrDisp -> curLocData -> numMatrixShutters2;
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters2[i] -> loadData();
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
 #endif
     aci_setScMatrixBorder();
     if(m_owner){
         m_owner -> curHeightScale = 256;
         m_owner -> putfon();
         m_owner -> redraw();
     }
     put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
     if(aScrDisp -> curMatrix)
         aScrDisp -> curMatrix -> redraw();
     aScrDisp -> secondMatrix -> redraw();
     iScrDisp -> curScr -> show_avi();
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 #else
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     SOUND_GATE();
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> freeData();
     }
     delete[] fon_buf;
 #endif
     if(v_flag)
         XGR_MouseShow();
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, aci_setScMatrixBorder(), ACI_SHUTTER_CLOSE, ACI_SHUTTER_OPEN, ACI_SMATRIX_BORDER_ID, aScrDisp, curMatrix, i_get_scrfon(), i_put_scrfon(), I_RES_X, I_RES_Y, iScrDisp, iScreenOffs, NULL, put_map(), Redraw, SOUND_GATE, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
Referenced by actIntDispatcher::EventQuant().
aciStartSpeech()
void aciStartSpeech (void)
 {
     aciML_EventSeq* seq;
     int i,unlock_id,prepare2_id,prepare_id,speech_id,end_id,end2_id,lock_id,speech_sz,dropLev = 0;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p) return;
     aciSpeechMode = dgMood;
 #ifdef _ACI_ESCAVE_DEBUG_
     if(aci_dgMoodNext != -1){
         aciSpeechMode = aci_dgMoodNext;
         aci_dgMoodNext = -1;
     }
 #endif
     unlock_id = AML_UNLOCK0_SEQ + aciSpeechMode;
     prepare2_id = AML_PREPARE0_SEQ2 + aciSpeechMode;
     prepare_id = AML_PREPARE0_SEQ + aciSpeechMode;
     speech_id = AML_SPEECH0_SEQ + aciSpeechMode;
     end_id = AML_END0_SEQ + aciSpeechMode;
     end2_id = AML_END0_SEQ2 + aciSpeechMode;
     lock_id = AML_LOCK0_SEQ + aciSpeechMode;
     speech_sz = p -> items -> Size;
     aciSpeechSeq -> size = 0;
     for(i = 0; i < AML_MAX_DROP_EVENT; i ++)
         aciSpeechSeq -> dropLevel[i] = -1;
     if(aciSpeechBegLocked || !aciSpeechStarted){
         seq = aciML_D -> getEventSeq(unlock_id);
         if(seq){
             aciSpeechSeq -> mergeSeq(seq);
             aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
             dropLev ++;
         }
         aciSpeechStarted = 1;
     }
     seq = aciML_D -> getEventSeq(prepare2_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     seq = aciML_D -> getEventSeq(prepare_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     seq = aciML_D -> getEventSeq(speech_id);
     if(seq){
         for(i = 0; i < speech_sz; i ++)
             aciSpeechSeq -> mergeSeq(seq);
     }
     seq = aciML_D -> getEventSeq(end_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     seq = aciML_D -> getEventSeq(end2_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     if(aciSpeechEndLocked){
         seq = aciML_D -> getEventSeq(lock_id);
         if(seq){
             aciSpeechSeq -> mergeSeq(seq);
             aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
             dropLev ++;
         }
     }
     aciSpeechSeq -> ChannelID = aciML_D -> curDataSet -> SpeechChannel;
     aciML_D -> SeqList[0] -> putSeq(aciSpeechSeq);
     aciSpeechBegLocked = aciSpeechEndLocked;
 }
References ACI_ANSWER_PANEL, aciML_D, aciSpeechBegLocked, aciSpeechEndLocked, aciSpeechMode, aciSpeechSeq, aciSpeechStarted, AML_END0_SEQ, AML_END0_SEQ2, AML_LOCK0_SEQ, AML_MAX_DROP_EVENT, AML_PREPARE0_SEQ, AML_PREPARE0_SEQ2, AML_SPEECH0_SEQ, AML_UNLOCK0_SEQ, aScrDisp, and dgMood.
Referenced by aciEscaveKickOut(), and aciNextPhrase().
aciSwapMatrices()
void aciSwapMatrices (void)
 {
     _iSTORE_OFFS_;
     int i,max_timer,num1,num2,timer = 0;
     iScreenObject* m_owner = NULL,*m2_owner = NULL;
     iBitmapElement* b,*b1;
     b = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_MATRIX_BORDER_ID];
     b1 = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(b) m_owner = (iScreenObject*)b -> owner;
     if(b1) m2_owner = (iScreenObject*)b1 -> owner;
     unsigned char* fon_buf;
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
 #ifndef _ACI_NO_SHOP_ANIMATION_
     num1 = aScrDisp -> curLocData -> numMatrixShutters1;
     num2 = aScrDisp -> curLocData -> numMatrixShutters2;
     max_timer = aScrDisp -> curLocData -> numMatrixShutters1 + aScrDisp -> curLocData -> numMatrixShutters2;
     for(i = 0; i < num1; i ++){
         aScrDisp -> curLocData -> MatrixShutters1[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters1[i] -> loadData();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters2[i] -> loadData();
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     SOUND_GATE();
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < num1; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters1[i] -> Quant();
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num1; i ++)
             aScrDisp -> curLocData -> MatrixShutters1[i] -> Redraw();
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
 #endif
     aScrDisp -> swap_matrices();
     aci_setMatrixBorder();
     aci_setScMatrixBorder();
     if(m_owner){
         m_owner -> putfon();
         m_owner -> redraw();
     }
     if(m2_owner){
         m2_owner -> curHeightScale = 0;
         m2_owner -> putfon();
         m2_owner -> redraw();
     }
     put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
     aScrDisp -> curMatrix -> redraw();
     iScrDisp -> curScr -> show_avi();
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 #else
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < num1; i ++){
         aScrDisp -> curLocData -> MatrixShutters1[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     SOUND_GATE();
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < num1; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters1[i] -> Quant();
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num1; i ++)
             aScrDisp -> curLocData -> MatrixShutters1[i] -> Redraw();
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < num1; i ++){
         aScrDisp -> curLocData -> MatrixShutters1[i] -> freeData();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> freeData();
     }
     delete[] fon_buf;
 #endif
     if(v_flag)
         XGR_MouseShow();
 }
References _iSTORE_OFFS_, ACI_MATRIX_BORDER_ID, aci_setMatrixBorder(), aci_setScMatrixBorder(), ACI_SHUTTER_CLOSE, ACI_SHUTTER_OPEN, ACI_SMATRIX_BORDER_ID, aScrDisp, curMatrix, i_get_scrfon(), i_put_scrfon(), I_RES_X, I_RES_Y, iScrDisp, iScreenOffs, NULL, put_map(), Redraw, SOUND_GATE, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
Referenced by actIntDispatcher::EventQuant().
aciWorldExploredInfo()
void aciWorldExploredInfo (void)
 {
     int i;
     aciWorldInfo* p1;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p1 = aScrDisp -> wMap -> world_ptr[i];
         if(p1 && uvsReturnWorldGamerVisit(p1 -> uvsID)){
             p1 -> flags |= AS_EXPLORED_WORLD;
         }
     }
 }
References AS_MAX_WORLD, aScrDisp, uvsReturnWorldGamerVisit(), and wMap.
Referenced by aciWorldMap::build_map().
acsHandleExtEvent()
void acsHandleExtEvent (int code, int data0 = 0, int data1 = 0, int data2 = 0)
 {
     int val,max_val,i_val,i_max_val;
     switch(code){
         case ACS_GLOBAL_EXIT:
             if(!(aScrDisp -> flags & AS_ISCREEN))
                 GameQuantReturnValue = RTO_LOADING3_ID;
             else {
                 iScrDisp -> flags |= SD_EXIT;
                 iScrExitCode = 1;
                 iAbortGameFlag = 1;
             }
             if(NetworkON) iMultiFlag = 1;
             acsScrD -> QuantCode = 1; // resume game pause
             if(!GameOverID)
                 GameOverID = GAME_OVER_ABORT;
             break;
         case ACS_INIT_TUTORIAL_MODE:
             acsSetStrState(ACS_TUTORIAL_MODE,!iGetOptionValue(iTUTORIAL_ON));
             break;
         case ACS_SET_TUTORIAL_MODE:
             iSetOptionValue(iTUTORIAL_ON,!acsGetStrState(ACS_TUTORIAL_MODE));
             iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
             break;
         case ACS_SET_AUTORUN_MODE:
             aciAutoRun = acsGetStrState(ACS_AUTORUN_MODE);
             iScrOpt[iAUTO_ACCELERATION]->SetValueINT(acsGetStrState(ACS_AUTORUN_MODE));
             break;
         case ACS_SET_SOUND_MODE:
             iSetOptionValue(iSOUND_ON,!acsGetStrState(ACS_SOUND_MODE));
             iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
             break;
         case ACS_SET_MUSIC_MODE:
             iSetOptionValue(iMUSIC_ON,!acsGetStrState(ACS_MUSIC_MODE));
             iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
             break;
         case ACS_INIT_AUTORUN_MODE:
 //          acsSetStrState(ACS_AUTORUN_MODE,aciAutoRun);
             aciAutoRun = iGetOptionValue(iAUTO_ACCELERATION);
             acsSetStrState(ACS_AUTORUN_MODE,iGetOptionValue(iAUTO_ACCELERATION));
             break;
         case ACS_INIT_SOUND_MODE:
             acsSetStrState(ACS_SOUND_MODE,!iGetOptionValue(iSOUND_ON));
             break;
         case ACS_INIT_SOUND_VOLUME:
             acsScrD -> SetScroller(ACS_SOUND_VOLUME,iGetOptionValue(iSOUND_VOLUME_CUR),iGetOptionValue(iSOUND_VOLUME_MAX));
             break;
         case ACS_SET_SOUND_VOLUME:
             val = acsScrD -> GetObjectValue(ACS_SOUND_VOLUME);
             max_val = acsScrD -> GetObjectValue(ACS_SOUND_VOLUME,1);
             i_max_val = iGetOptionValue(iSOUND_VOLUME_MAX);
             i_val = (val * i_max_val) / max_val;
             iSetOptionValue(iSOUND_VOLUME_CUR,i_val);
             iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
             break;
         case ACS_INIT_MUSIC_MODE:
             acsSetStrState(ACS_MUSIC_MODE,!iGetOptionValue(iMUSIC_ON));
             break;
         case ACS_INIT_MUSIC_VOLUME:
             acsScrD -> SetScroller(ACS_MUSIC_VOLUME,iGetOptionValue(iMUSIC_VOLUME_CUR),iGetOptionValue(iMUSIC_VOLUME_MAX));
             break;
         case ACS_SET_MUSIC_VOLUME:
             val = acsScrD -> GetObjectValue(ACS_MUSIC_VOLUME);
             max_val = acsScrD -> GetObjectValue(ACS_MUSIC_VOLUME,1);
             i_max_val = iGetOptionValue(iMUSIC_VOLUME_MAX);
             i_val = (val * i_max_val) / max_val;
             iSetOptionValue(iMUSIC_VOLUME_CUR,i_val);
             iHandleExtEvent(iEXT_UPDATE_MUSIC_VOLUME);
             break;
         case ACS_CHANGE_MUSIC_MODE:
             acsChangeStrState(ACS_MUSIC_MODE);
             iSetOptionValue(iMUSIC_ON,!acsGetStrState(ACS_MUSIC_MODE));
             iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
             break;
         case ACS_CHANGE_AUTORUN_MODE:
             acsChangeStrState(ACS_AUTORUN_MODE);
             aciAutoRun = acsGetStrState(ACS_AUTORUN_MODE);
             iScrOpt[iAUTO_ACCELERATION]->SetValueINT(acsGetStrState(ACS_AUTORUN_MODE));
             break;
         case ACS_CHANGE_SOUND_MODE:
             acsChangeStrState(ACS_SOUND_MODE);
             iSetOptionValue(iSOUND_ON,!acsGetStrState(ACS_SOUND_MODE));
             iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
             break;
         case ACS_CHANGE_TUTORIAL_MODE:
             acsChangeStrState(ACS_TUTORIAL_MODE);
             iSetOptionValue(iTUTORIAL_ON,!acsGetStrState(ACS_TUTORIAL_MODE));
             iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
             break;
         case ACS_INIT_SLOT_NAME:
             acsPrepareSlotName(data0,data1);
             break;
         case ACS_INIT_SLOT_NAME_INPUT:
             acsPrepareSlotNameInput(data0,data1);
             break;
         case ACS_SAVE_GAME:
             acsSaveData();
             break;
     }
 }
Referenced by actIntDispatcher::flush().
acsQuant()
int acsQuant (void)
 {
     int ret,k,firstQuant = 0;
     if(!acsAllocFlag){
         acsAllocFlag = 1;
         if(NetworkON) aciKeyboardLocked = 1;
         acsScrD -> curScrID = acsScreenID;
         acsScrD -> QuantCode = 0;
         XGR_MouseObj.DisablePrompt();
         XGR_MouseShow();
         acsScrD -> alloc_mem();
         if(XGR_MAXX == 800 && !(aScrDisp -> flags & AS_ISCREEN))
             acsScrD -> curScr -> ChangeCoords((800 - 640)/2,(600 - 480)/2);
         EffectsOff();
         firstQuant = 1;
         if(acsScrD -> curScrID >= 3){
             aciCloseGate();
             acsScrD -> Quant(0);
             aciOpenGate();
         }
         KeyBuf -> clear();
     }
     while(KeyBuf->size){
         SDL_Event *e = KeyBuf->get();
         if (e->type == SDL_KEYDOWN) {
             k = sdlEventToCode(e);
         }
         if (e->type == SDL_KEYDOWN || e->type == SDL_TEXTINPUT) {
             acsScrD->KeyTrap(0, e);
             if (e->key.keysym.scancode == SDL_SCANCODE_ESCAPE && !acsScrD -> QuantCode) {
                 acsScrD -> QuantCode = 1;
             }
         }
     }
     if(aScrDisp -> flags & aMS_MOVED){
         acsScrD -> KeyTrap(iMOUSE_MOVE_CODE, nullptr);
         aScrDisp -> flags ^= aMS_MOVED;
         if(aciMouseFlagL){
             acsScrD -> KeyTrap(iMOUSE_LEFT_MOVE, nullptr);
         }
         if(aciMouseFlagR){
             acsScrD -> KeyTrap(iMOUSE_RIGHT_MOVE, nullptr);
         }
     }
     if(aScrDisp -> flags & aMS_LEFT_PRESS){
         acsScrD -> KeyTrap(iMOUSE_LEFT_PRESS_CODE, nullptr);
         aScrDisp -> flags ^= aMS_LEFT_PRESS;
     }
     if(aScrDisp -> flags & aMS_RIGHT_PRESS){
         acsScrD -> KeyTrap(iMOUSE_RIGHT_PRESS_CODE, nullptr);
         aScrDisp -> flags ^= aMS_RIGHT_PRESS;
     }
     if(NetworkON){
         acsScrD -> flags |= ACS_FORCED_REDRAW;
         ret = acsScrD -> Quant(actIntLog);
     }
     else
         ret = acsScrD -> Quant();
     if(firstQuant){
         acsPrepareSlotNameInput(acsCurrentSlotID,acsCurrentSlotNum);
         acsScrD -> PrepareInput(acsCurrentSlotID);
     }
     if(ret){
         acsAllocFlag = 0;
         if(XGR_MAXX == 800 && !(aScrDisp -> flags & AS_ISCREEN))
             acsScrD -> curScr -> ChangeCoords(-(800 - 640)/2,-(600 - 480)/2);
         acsScrD -> free_mem();
         if(aScrDisp -> flags & AS_FULLSCR && !(aScrDisp -> flags & AS_ISCREEN)){
             XGR_MouseHide();
         }
         else
             aScrDisp -> flags &= ~AS_FULL_REDRAW;
         iScrDisp -> flags &= ~MS_LEFT_PRESS;
         iScrDisp -> flags &= ~MS_RIGHT_PRESS;
         iScrDisp -> flags &= ~MS_MOVED;
         iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
         iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
         iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
         if(NetworkON) aciKeyboardLocked = 0;
         acsScreenID = 1;
         iSaveData();
         KeyBuf -> clear();
         return 1;
     }
     return 0;
 }
Referenced by actIntDispatcher::flush(), and GameQuantRTO::Quant().
aMS_init()
void aMS_init (void)
 {
     XGR_MouseSetPressHandler(XGM_LEFT_BUTTON,aMS_LeftPress);
     XGR_MouseSetUnPressHandler(XGM_LEFT_BUTTON,aMS_LeftUnpress);
     XGR_MouseSetPressHandler(XGM_RIGHT_BUTTON,aMS_RightPress);
     XGR_MouseSetUnPressHandler(XGM_RIGHT_BUTTON,aMS_RightUnpress);
     XGR_MouseSetMoveHandler(aMS_Movement);
     aciMouseFlagL = aciMouseFlagR = 0;
 }
References aciMouseFlagL, aciMouseFlagR, aMS_LeftPress(), aMS_LeftUnpress(), aMS_Movement(), aMS_RightPress(), aMS_RightUnpress(), XGM_LEFT_BUTTON, XGM_RIGHT_BUTTON, XGR_MouseSetMoveHandler, XGR_MouseSetPressHandler, and XGR_MouseSetUnPressHandler.
Referenced by actIntDispatcher::i_finit().
aOutText32()
void aOutText32 (int x, int y, int color, void * text, int font, int hspace, int vspace)
 {
     int s,xs,ys,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     int color_size,chr;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     color_size = (color >> 16) & 0xFF;
     color &= 0xFFFF;
     unsigned char* p = aScrFonts32[font] -> data;
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     X = x;
     Y = y;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 X -= aScrFonts32[font] -> LeftOffs[chr];
                 offs = xs * ys * chr;
                 aciPutSpr32(X,Y,xs,ys,p + offs,color,color_size);
                 X += xs + hspace - aScrFonts32[font] -> RightOffs[chr];
             }
         }
         else {
             X = x;
             Y += ys + vspace;
         }
     }
 }
aOutText32clip()
void aOutText32clip (int x, int y, int color, void * text, int font, int hspace, int vspace)
 {
     int s,xs,ys,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     int color_size,chr;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     color_size = (color >> 16) & 0xFF;
     color &= 0xFFFF;
     unsigned char* p = aScrFonts32[font] -> data;
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     X = x;
     Y = y;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 X -= aScrFonts32[font] -> LeftOffs[chr];
                 offs = xs * ys * chr;
                 aciPutSpr32clip(X,Y,xs,ys,p + offs,color,color_size);
                 X += xs + hspace - aScrFonts32[font] -> RightOffs[chr];
             }
         }
         else {
             X = x;
             Y += ys + vspace;
         }
     }
 }
aTextHeight32()
int aTextHeight32 (void * text, int font, int vspace)
 {
     int s,xs,ys,sz = strlen((char*)text),chr;
     int len = 0;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     len = ys + vspace;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr == '\n'){
             len += ys + vspace;
         }
     }
     return len;
 }
aTextWidth32()
int aTextWidth32 (void * text, int font, int hspace)
 {
     int s,xs,ys,sz = strlen((char*)text),chr;
     int len = 0,max_len = 0;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 len += xs + hspace - aScrFonts32[font] -> RightOffs[chr] - aScrFonts32[font] -> LeftOffs[chr];
             }
         }
         else {
             if(len > max_len) max_len = len;
             len = 0;
         }
     }
     if(len > max_len) max_len = len;
     return max_len;
 }
build_cell_frame()
void build_cell_frame (void)
 {
     int dx = aCellSize;
     int dxx = dx * dx;
     int dx2 = dx >> 1;
     int dx4 = dx >> 2;
     unsigned char* cell = new unsigned char[(dx + 1) * (dx + 1)];
     memset(cell,0,(dx + 1) * (dx + 1));
 /*
     a_buf_line(dx2,0,dx,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx4,dx,dx2 + dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx2 + dx4,dx2,dx,1,dx + 1,dx + 1,cell);
     a_buf_line(dx2,dx,0,dx2 + dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx2 + dx4,0,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx4,dx2,0,1,dx + 1,dx + 1,cell);
 */
     a_buf_line(dx2,0,dx,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx - dx4,dx2,dx,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx4,dx,dx - dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx - dx4,0,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx - dx4,dx2,dx,1,dx + 1,dx + 1,cell);
     a_buf_line(dx2,0,0,dx4,1,dx + 1,dx + 1,cell);
     fill_buf(dx2,dx2,0,2,dx + 1,dx + 1,cell);
     aCellFrame = cell;
 }
References a_buf_line(), aCellFrame, aCellSize, and fill_buf().
Referenced by actIntDispatcher::i_init(), and actIntDispatcher::init().
change_screen()
void change_screen (int scr)
 {
     aScrDisp -> change_ibs(mode);
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
     set_screen(aScrDisp -> curIbs -> SideX,aScrDisp -> curIbs -> SideY,0,aScrDisp -> curIbs -> CenterX,aScrDisp -> curIbs -> CenterY);
 }
References aScrDisp.
Referenced by actIntDispatcher::change_mode(), and actIntDispatcher::EventQuant().
dgGetThreallPhrase()
char* dgGetThreallPhrase (void)
 {
     return dgD -> getNextPhrase();
 }
free_cell_frame()
void free_cell_frame (void)
 {
     delete[] aCellFrame;
 }
References aCellFrame.
Referenced by aciFreeAll(), actIntDispatcher::finit(), and actIntDispatcher::i_finit().
GetCompasTarget()
char* GetCompasTarget (void)
 {
     if(CompasObj.CurrentTarget){
         return CompasObj.CurrentTarget->aciName;
     };
     return NULL;
 };
Referenced by actIntDispatcher::init_submenu().
i_evince_pal()
void i_evince_pal (unsigned char * p, int delta)
 {
     int i,col,scale = 0;
     unsigned char* buf = new unsigned char[768];
     while(scale < 256){
         for(i = 0; i < 768; i ++){
             col = p[i];
             buf[i] = (col * scale) >> 8;
         }
         XGR_SetPal(buf,0,255);
         SDL_Delay(10);
         scale += delta;
     }
     XGR_SetPal(p,0,255);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     delete[] buf;
 }
Referenced by actIntDispatcher::flush(), and actIntDispatcher::pal_flush().
ibsout()
void ibsout (int x, int y, void * ptr)
 {
     int _x,_y,cnt;
     int* offs_table = XGR_Obj.yOffsTable;
     unsigned char* vbuf = XGR_VIDEOBUF;
     unsigned char* pbuf = (unsigned char*)ptr;
     cnt = *((int*)pbuf);
     pbuf += 4;
     while(cnt){
         _x = *((int*)pbuf);
         pbuf += 4;
         _y = *((int*)pbuf);
         pbuf += 4;
         memcpy(vbuf + offs_table[_y + y] + _x + x,pbuf,cnt);
         pbuf += cnt;
         cnt = *((int*)pbuf);
         pbuf += 4;
     }
 }
References XGR_Obj, XGR_VIDEOBUF, and XGR_Screen::yOffsTable.
Referenced by ibsObject::show().
iChatFinit()
void iChatFinit (void)
 {
     iChatButton* p,*p1;
     if(iChatButtons){
         p = (iChatButton*)iChatButtons -> fPtr;
         while(p){
             p1 = (iChatButton*)p -> next;
             delete p;
             p = p1;
         }
         delete iChatButtons;
     }
     if(iChatHistory)
         delete iChatHistory;
     if(iChatInput)
         delete iChatInput;
     iChatON = iScreenChat = 0;
     aciKeyboardLocked = 0;
     iChatHistory = NULL;
     iChatInput = NULL;
     iChatButtons = NULL;
     SDL_StopTextInput();
 }
Referenced by actIntDispatcher::EventQuant().
iChatInit()
void iChatInit (void)
 {
     int x,y,sx,sy,bsx,col0,col1,bcol;
     iChatButton* p;
     sx = ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X;
     sy = ICS_HISTORY_SIZE_Y + ICS_DELTA * 2 + ICS_BUTTON_SIZE_Y * 2;
 //    bsx = (sx - ICS_DELTA * 2) / 3;
     bsx = (ICS_HISTORY_SIZE_X - ICS_DELTA * 2) / 3;
     x = (XGR_MAXX - sx) / 2;
     y = (XGR_MAXY - sy) / 2;
     if(!iScreenChat)
         bcol = ICS_BORDER_COLOR;
     else {
         y -= 30;
         bcol = ICS_iBORDER_COLOR;
     }
     iChatButtons = new XList;
     iChatHistory = new iChatHistoryScreen;
     iChatHistory -> init(x,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_HISTORY_SIZE_X,ICS_HISTORY_SIZE_Y,bcol,bcol);
     iChatInput = new iChatInputField;
     iChatInput -> init(x,y + ICS_HISTORY_SIZE_Y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_HISTORY_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     strcpy(iChatInput -> string,">_");
     p = new iChatButton(2);
     p -> init(x,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_MUTE_BUTTON;
     p -> set_string(iSTR_MUTE_ALL);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p -> CurState = iChatMUTE;
     p = new iChatButton(1);
     p -> init(x + bsx + ICS_DELTA,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_CLEAR_BUTTON;
     p -> set_string(iSTR_CLEAR_LOG);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     iChatButtons -> AddElement((XListElement*)p);
     iChatBackLog = 1;
     if(!iScreenChat){
         p = new iChatButton(2);
         p -> init(x + (bsx + ICS_DELTA) * 3,y,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
         p -> ID = ICS_BACK_BUTTON;
         p -> set_string(iSTR_BACKGROUND);
         if(!iScreenChat){
             col0 = ICS_STRING_COL0;
             col1 = ICS_STRING_COL1;
         }
         else {
             col0 = ICS_iSTRING_COL0;
             col1 = ICS_iSTRING_COL1;
         }
         p -> set_color(0,col0);
         p -> set_color(1,col1);
         p -> CurState = 1;
         iChatButtons -> AddElement((XListElement*)p);
     }
 //    else {
 //        iChatBackLog = 0;
 //    }
     if(!iScreenChat){
         p = new iChatButton(1);
         p -> init(x + bsx * 2 + ICS_DELTA * 2,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
         p -> ID = ICS_EXIT_BUTTON;
         p -> set_string(iSTR_LEAVE_CHAT);
         col0 = ICS_STRING_COL0;
         p -> set_color(0,col0);
         iChatButtons -> AddElement((XListElement*)p);
     }
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_ALL_BUTTON;
     p -> set_string(iSTR_All);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 2,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_YELLOW_BUTTON;
     p -> set_string(iSTR_Yellow);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 3,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_ORANGE_BUTTON;
     p -> set_string(iSTR_Orange);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 4,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_BLUE_BUTTON;
     p -> set_string(iSTR_Blue);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 5,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_GREEN_BUTTON;
     p -> set_string(iSTR_Green);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 6,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_RED_BUTTON;
     p -> set_string(iSTR_Red);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 2,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_WHITE_BUTTON;
     p -> set_string(iSTR_White);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 3,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_GRAY_BUTTON;
     p -> set_string(iSTR_Gray);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 4,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_BLACK_BUTTON;
     p -> set_string(iSTR_Black);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 5,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_CAMOUFLAGE_BUTTON;
     p -> set_string(iSTR_Camouflage);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 6,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PATROL_BUTTON;
     p -> set_string(iSTR_Patrol);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/4,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 6,ICS_BUTTON_SIZE_X/2,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_UP_BUTTON;
     p -> set_string("\x1E");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 7,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER1_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 8,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER2_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 9,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER3_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 10,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER4_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 11,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER5_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/4,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 12,ICS_BUTTON_SIZE_X/2,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_DN_BUTTON;
     p -> set_string("\x1F");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     iChatExit = 0;
     iChatON = 1;
     aciKeyboardLocked = 1;
     XGR_MouseShow();
     iInitChatScreen();
     SDL_StartTextInput();
 }
Referenced by actIntDispatcher::EventQuant().
iChatKeyQuant()
void iChatKeyQuant (SDL_Event * k)
{
     if (k->type == SDL_TEXTINPUT) {
         return iChatInputChar(k);
     }
     if (k->type != SDL_KEYDOWN) {
         iChatExit = 1;
         return;
     }
     if(iCheckKeyID(iKEY_CHAT, k->key.keysym.scancode))
         iChatExit = 1;
     switch(k->key.keysym.scancode) {
         case SDL_SCANCODE_ESCAPE:
             iChatExit = 1;
             break;
         case SDL_SCANCODE_RETURN:
             iChatInputFlush();
             break;
         case SDL_SCANCODE_BACKSPACE:
         case SDL_SCANCODE_LEFT:
             iChatInputBack();
             break;
         default:
             if(k) {
                 iChatInputChar(k);
             }
             break;
     }
 }
Referenced by actIntDispatcher::KeyQuant().
iChatMouseQuant()
void iChatMouseQuant (int x, int y, int bt)
 {
     iChatButton* p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         if(p -> check_xy(x,y)) iChatMouseHandler(p,bt);
         p = (iChatButton*)p -> next;
     }
 }
Referenced by actIntDispatcher::KeyQuant().
iChatQuant()
void iChatQuant (int flush = 0)
 {
     int sz;
     iChatButton* p;
     if(!iChatON) return;
 //    if(iScreenChat) put_map(iScreenOffs,0,XGR_MAXX,XGR_MAXY);
     iInitChatScreen();
     p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         if(!(p -> flags & ICS_HIDDEN_OBJECT)) p -> redraw();
         p = (iChatButton*)p -> next;
     }
     iChatCursorTimer ++;
     if(iChatCursorTimer >= ICS_INPUT_TIMER){
         iChatCursorTimer = 0;
         iChatCursorFlag = 1;
     }
     if(iChatCursorFlag){
         sz = strlen(iChatInput -> string);
         if(iChatInput -> string[sz - 1] == '_')
             iChatInput -> string[sz - 1] = ' ';
         else
             iChatInput -> string[sz - 1] = '_';
         iChatCursorFlag = 0;
     }
     iChatInput -> redraw();
     iChatHistory -> redraw();
     if(flush){
         p = (iChatButton*)iChatButtons -> fPtr;
         while(p){
             if(!(p -> flags & ICS_HIDDEN_OBJECT)) p -> flush();
             p = (iChatButton*)p -> next;
         }
         iChatInput -> flush();
         iChatHistory -> flush();
     }
 }
Referenced by actIntDispatcher::flush().
iGetObject()
iListElement * iGetObject (const char * scr, const char * obj)
 {
     iScreen* p;
     iListElement* el = NULL;
     if(scr) {
         p = (iScreen*)iScrDisp -> get_object(scr);
         el = p -> get_object(obj);
     } else {
         el = iScrDisp -> get_object(obj);
     }
     return el;
 }
Referenced by actIntDispatcher::inv_mouse_imove_quant().
ipal_init()
void ipal_init (unsigned char * p)
 {
     if(!ipalbuf){
         ipalbuf = new uchar[768];
         ipalbufOrg = new uchar[768];
         }
     memcpy(ipalbuf,p,768);
     memcpy(ipalbufOrg,p,768);
 }
Referenced by actIntDispatcher::i_init().
iregRender()
void iregRender (int LowX, int LowY, int HiX, int HiY)
 {
     LowX = iXCYCL(LowX);
     HiX = iXCYCL(HiX);
     LowY = iYCYCL(LowY);
     HiY = iYCYCL(HiY);
     LowX &= ~1;
     HiX |= 1;
     int SizeY = (LowY == HiY) ? iV_SIZE : iYCYCL(HiY - LowY);
     int SizeX = (0 == iXCYCL(HiX - LowX)) ? H_SIZE : iXCYCL(HiX - LowX);
     int BackScanLen = 0;
     int j;
     for(j = 0;j < SizeY;j++){
         const int y = iYCYCL(j + LowY);
         BYTE* pa0 = ivMap -> lineT[y];
         BYTE* pc0 = ivMap -> lineTcolor[y];
         if(!pa0) continue;
         MEMSET(ishadowParent,0,(((SizeX*SHADOWDEEP) >> POSPOWER) + 4*MAX_ALT));
         int hC = MAX_ALT;
         int LastStep = (H_SIZE - 1 - HiX) * SHADOWDEEP;
         LastStep -= ((LastStep >> POSPOWER) - MAX_ALT) << POSPOWER;
         //
         iPreStage(LastStep,HiX,pa0,hC,ishadowParent + MAX_ALT);
         //
         int x = HiX;
         BYTE* grid = ishadowParent + MAX_ALT + MAX_ALT;
         int MaxAlt = 0;
         iMainStage(pa0,hC,pc0,SizeX,x,grid,MaxAlt);
         //
         {
         x |= 1;
         BYTE* pa = pa0 + x;
         BYTE* pf = pa + H_SIZE;
         BYTE* pc = pc0 + x;
         BYTE* palCLRlast;
         BYTE* lightCLRlast;
         BYTE typeC = 0xFF;
         int MaxPossibleAlt = MAX_ALT;
         unsigned bNeedScan = 1;
         while(bNeedScan && MaxPossibleAlt >= 0){
             bNeedScan = 0;
             if(*pf & DOUBLE_LEVEL){
                 const BYTE lxVal = *pa;
                 const BYTE rxVal = *(pa0 + iXCYCL(x + 2));
                 const BYTE h = *pa;
                 const BYTE dh = *(pa - 1);
                 const BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 const BYTE level = h;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 grid += 3;
                 hC -= 3;
                 MaxAlt -= 3;
                 MaxPossibleAlt -= 3;
                 if(dh < MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *(pf - 1) |= SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *(pf - 1) &= ~SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 pa--; pf--; pc--;
                 if(*pf & SHADOW_MASK) bNeedScan = 1;
                 if(dh > hC){
                     MEMSET(grid + hC,1,dh - hC);
                     hC = dh;
                     }
                 MEMSET(grid + h - SS_WIDTH,1,SS_WIDTH + 1);
                 }
             else {
                 BYTE lxVal = *(pa - 1);
                 BYTE rxVal = *(pa0 + iXCYCL(x + 1));
                 BYTE h = *pa;
                 BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 BYTE level = h;
                 grid += 1;
                 hC -= 1;
                 MaxAlt -= 1;
                 MaxPossibleAlt -= 1;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 pa--; pf--; pc--;
                 rxVal = h;
                 h = lxVal;
                 lxVal = *(pa0 + iXCYCL(x - 2));
                 grid += 2;
                 hC -= 2;
                 MaxAlt -= 2;
                 MaxPossibleAlt -= 2;
                 type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 level = h;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 }
             if(x == 1){
                 x = H_SIZE - 1;
                 pa = pa0 + x;
                 pf = pa + H_SIZE;
                 pc = pc0 + x;
                 }
             else {
                 x = iXCYCL(x - 2);
                 pa--; pf--; pc--;
                 }
             }
         const int CurrScanLenght = iXCYCL(LowX - x);
         if(CurrScanLenght > BackScanLen) BackScanLen = CurrScanLenght;
         }
         }
 }
Referenced by aciML_ItemData::put_frame(), and iMobileLocation::setPhase().
iScrQuant()
void iScrQuant (void)
LoadingMessage()
void LoadingMessage (int flush = 0)
 {
     if(flush){
         char col255[3] = { 60,40,0 }; XGR_SetPal(col255,255,1);
         char col0[3] = { 0,0,0 }; XGR_SetPal(col0,0,1);
         XGR_Fill(0);
     }
     char* str = getRC();
     sysfont.draw(8,XGR_MAXY - 35,(unsigned char*)str,255,-1);
     XBuffer buf;
     if (lang() == RUSSIAN) {
         buf < Convert(zSTR_LOADING_800_RU);
     } else if (lang() == GERMAN) {
         if(XGR_MAXX == 800)
             buf < "(C)1997-2014. Alle Rechte vorbehalten. Release Version 1.3. Gleich geht's weiter...";
         else
             buf < "Spiel wird geladen. Gleich geht's weiter...";
     } else {
         buf < "(C)1997-2014 All Rights Reserved. Release Version 1.3 Loading. Please wait...";
     }
     int len = MAX(strlen(str),strlen(buf.GetBuf()));
     sysfont.draw(8,XGR_MAXY - 20,(unsigned char*)(buf.GetBuf()),255,-1);
     XGR_LineTo(8,XGR_MAXY - 45,len*8 + 5 + 16,2,255);
     XGR_LineTo(8 + len*8 + 11,XGR_MAXY - 45 - 7,2*7,3,255);
     //if(flush){
     //  XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     //}
 }
Referenced by actIntDispatcher::i_init().
LoadResourceSOUND()
void LoadResourceSOUND (const char * path_name, int surface)
 {
     int i;
     //if(MuteLog) return;
     EffectsOff();
     XBuffer buf;
     XStream ff(0);
     for(i = 0;i < EFF_MAX;i++) {
         if ((SndData[i].status & LOCAL_SOUND) && SndData[i].lpDSB && surface) {
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
         buf.init();
         if((i == EFF_DRIVING) || (i == EFF_START) || (i == EFF_STOP)) {
             if(EngineNoise) {
                 buf < "resource/sound/effects" < "/" < SndData[i].fname < ".wav";
             } else {
                 continue;
             }
         } else {
             buf < path_name < "/" < SndData[i].fname < ".wav";
         }
         if(ff.open(buf.GetBuf(),XS_IN)){
             ff.close();
             if (SndData[i].lpDSB){
                 SoundRelease(SndData[i].lpDSB);
                 SndData[i].lpDSB = NULL;
                 }
             SoundLoad(buf.GetBuf(),&SndData[i].lpDSB);
         }
         //std::cout<<"file:"<<buf.GetBuf()<<" addr:"<<SndData[i].lpDSB<<std::endl;
     }
     EffectsOn(surface);
     sndBackgroundMax = sndStepMax = sndScratchMax = 0;
     for(i = EFF_BACKGROUND_0;i <= EFF_BACKGROUND_5;i++)
         if(SndData[i].lpDSB) sndBackgroundMax++;
     for(i = EFF_STEP0;i <= EFF_STEP2;i++)
         if(SndData[i].lpDSB) sndStepMax++;
     for(i = EFF_SCRATCH0;i <= EFF_SCRATCH1;i++)
         if(SndData[i].lpDSB) sndScratchMax++;
 }
Referenced by ChangeWorld(), actIntDispatcher::i_init(), LoadingRTO2::Init(), and xtInitApplication().
mem_putspr()
void mem_putspr (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char * src, unsigned char * dest)
 {
     int i,j,index = 0,b_index = 0;
     index = x + y * bsx;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             if(src[b_index])
                 dest[index + j] = src[b_index];
             b_index ++;
         }
         index += bsx;
     }
 }
Referenced by aciBitmapMenuItem::redraw(), aciWorldInfo::redraw(), and CounterPanel::redraw().
mem_putspr_h()
void mem_putspr_h (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char * src, unsigned char * dest)
 {
     int i,j,index = x + y * bsx,b_index = 0;
     int h,h1;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             if(src[b_index]){
                 h1 = dest[index + j];
                 h = src[b_index];
                 if(h > h1)
                     dest[index + j] = h;
             }
             b_index ++;
         }
         index += bsx;
     }
 }
Referenced by invMatrix::redraw_matrix().
mem_rectangle()
void mem_rectangle (int x, int y, int sx, int sy, int bsx, int col_in, int col_out, int mode, void * buf)
 {
     int i,index,_sx,_sy;
     unsigned char* p = (unsigned char*)buf;
     index = x + y * bsx;
     memset(p + index,col_out,sx);
     for(i = 0; i < sy; i ++){
         p[index] = p[index + sx - 1] = col_out;
         index += bsx;
     }
     memset(p + index - bsx,col_out,sx);
     if(mode){
         _sx = sx - 2;
         _sy = sy - 2;
         if(_sx <= 0 || _sy <= 0) return;
         index = (x + 1) + (y + 1) * bsx;
         for(i = 0; i < _sy; i ++){
             memset(p + index,col_in,_sx);
             index += bsx;
         }
     }
 }
Referenced by aciWorldMap::show_jump_count().
put_attr_fon()
void put_attr_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     for(j = 0; j < sy; j ++){
         memcpy(lta[y + j] + x + H_SIZE,buf + index,sx);
         index += sx;
     }
 }
References H_SIZE, and ivMap.
Referenced by aciLocationInfo::init_map_data().
put_buf2col()
void put_buf2col (int x, int y, int sx, int sy, unsigned char * buf, int null_lev, int n_mode)
 {
     int i,j,index = 0;
     unsigned t,l,n = null_lev;
     unsigned char** lta = ivMap -> lineT;
     unsigned char** ltc = ivMap -> lineTcolor;
     int yy,xx;
     if(!n_mode){
         if(n > 255){
             for(j = 0; j < sy; j ++){
                 yy = y + j;
                 for(i = 0; i < sx; i ++){
                     t = buf[index];
                     if(t) ltc[yy][x + i] = t;
                     index ++;
                 }
             }
         }
         else {
             for(j = 0; j < sy; j ++){
                 yy = y + j;
                 for(i = 0; i < sx; i ++){
                     xx = x + i;
                     t = buf[index];
                     l = lta[yy][xx];
                     if(t && n > l)
                         ltc[yy][xx] = t;
                     index ++;
                 }
             }
         }
     }
     else {
         if(n_mode == 1){
             for(j = 0; j < sy; j ++){
                 yy = y + j;
                 for(i = 0; i < sx; i ++){
                     xx = x + i;
                     l = lta[yy][xx];
                     if(n > l)
                         ltc[yy][xx] = buf[index];
                     index ++;
                 }
             }
         }
         else {
             for(j = 0; j < sy; j ++){
                 yy = y + j;
                 for(i = 0; i < sx; i ++){
                     xx = x + i;
                     ltc[yy][xx] = buf[index];
                     index ++;
                 }
             }
         }
     }
 }
Referenced by invItem::redraw(), invMatrix::redraw_matrix(), and invMatrix::redraw_shadow_cells().
put_fon()
void put_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     for(j = 0; j < sy; j ++){
         memcpy(lta[y + j] + x,buf + index,sx);
         index += sx;
     }
 }
Referenced by aciLocationInfo::init_map_data().
put_map()
void put_map (int x, int y, int sx, int sy)
 {
     int j;
     unsigned char** ltc = ivMap -> lineTcolor;
     int yy,x0,x1,bsx,index;
     int scr_offs = iScreenOffs;
     x0 = x;
     x1 = x + sx;
     if(x0 < scr_offs) x0 = scr_offs;
     if(x1 >= scr_offs + I_RES_X) x1 = scr_offs + I_RES_X;
     bsx = x1 - x0;
     if(bsx > 0){
         index = (x0 - scr_offs) + y * XGR_MAXX;
         for(j = 0; j < sy; j ++){
             yy = iYCYCL(y + j);
             memcpy(XGR_VIDEOBUF + index,ltc[yy] + x0,bsx);
             index += XGR_MAXX;
         }
     }
 }
Referenced by invItem::redraw(), invMatrix::redraw(), and invMatrix::redraw_shadow_cells().
redraw_fnc()
void redraw_fnc (int x, int y, int sx, int sy, int fnc)
 {
     switch(fnc){
         case FMENU_MAP:
             show_map(x,y,sx,sy);
             break;
         case FMENU_WMAP:
             if(aScrDisp -> wMap){
                 aScrDisp -> wMap -> redraw(x + ((sx - aScrDisp -> wMap -> SizeX) >> 1),y + ((sy - aScrDisp -> wMap -> SizeY) >> 1));
             }
             else {
                 XGR_Rectangle(x,y,sx,sy,0,0,XGR_FILLED);
             }
             break;
         case FMENU_TARGETS:
             break;
         case FMENU_CAMERAS:
             aciShowCamerasMenu(x,y,sx,sy);
             break;
         case FMENU_PARAMETERS:
             aciRedrawParamsPanel(x,y,sx,sy);
             break;
         default:
             XGR_Rectangle(x,y,sx,sy,0,0,XGR_FILLED);
             break;
     }
 }
References aciRedrawParamsPanel(), aciShowCamerasMenu(), aScrDisp, FMENU_CAMERAS, FMENU_MAP, FMENU_PARAMETERS, FMENU_TARGETS, FMENU_WMAP, show_map(), wMap, XGR_FILLED, and XGR_Rectangle.
Referenced by fncMenu::redraw().
restore_mouse_cursor()
void restore_mouse_cursor (void)
 {
     XGR_MouseSetCursor(MouseSizeX,MouseSizeY,MouseSize,MouseFrames);
     XGR_MouseSetSpot(MouseSizeX/2,0);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     XGR_MouseRedraw();
 }
Referenced by actIntDispatcher::cancel_matrix(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), actIntDispatcher::put_in_slot(), and actIntDispatcher::put_item_xy().
set_mouse_cursor()
void set_mouse_cursor (char * p, int sx, int sy)
 {
     XGR_MouseSetCursor(sx,sy,1,p);
     XGR_MouseSetSpot(sx/2,sy/2);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     XGR_MouseRedraw();
 }
Referenced by actIntDispatcher::change_items(), actIntDispatcher::put_in_slot(), and actIntDispatcher::set_move_item().
set_screen()
void set_screen (int Dx, int Dy, int mode, int xcenter, int ycenter)
 {
     curGMap -> change(Dx,Dy,mode,xcenter,ycenter);
     Redraw = 1;
 }
Referenced by actIntDispatcher::EventQuant().
show_map()
void show_map (int x, int y, int sx, int sy)
 {
     int i,index,m_index,cx,cy,y0,x_index = 0,_x = 0,_y = 0,vy,sx2,sy2;
     int scr_x,scr_y,dx,scr_x0;
     unsigned char* ptr;
     bmlObject* p = aScrDisp -> mapObj;
     cx = (ViewX * p -> SizeX) >> MAP_POWER_X;
     cy = (ViewY * p -> SizeY) >> MAP_POWER_Y;
     sx2 = sx / 2;
     sy2 = sy / 2;
     vy = sy * ((1 << MAP_POWER_Y) / p -> SizeY) / 2;
     y0 = cy - sy2;
     if(y0 < 0) y0 += p -> SizeY;
     if(y0 >= p -> SizeY) y0 -= p -> SizeY;
     ptr = new unsigned char[sx * sy];
     memset(ptr,0,sx * sy);
     if(cx < sx2){
         dx = sx2 - cx;
         _y = y0;
         index = 0;
         m_index = y0 * p -> SizeX + p -> SizeX - dx;
         for(i = 0; i < sy; i ++){
             memcpy(ptr + index,p -> frames + m_index,dx);
             index += sx;
             m_index += p -> SizeX;
             _y ++;
             if(_y >= p -> SizeY){
                 m_index = p -> SizeX - dx;
                 _y = 0;
             }
         }
         _y = y0;
         index = dx;
         m_index = y0 * p -> SizeX;
         for(i = 0; i < sy; i ++){
             memcpy(ptr + index,p -> frames + m_index,sx - dx);
             index += sx;
             m_index += p -> SizeX;
             _y ++;
             if(_y >= p -> SizeY){
                 m_index = 0;
                 _y = 0;
             }
         }
     }
     else {
         if(p -> SizeX - cx < sx2){
             dx = sx2 - (p -> SizeX - cx);
             _y = y0;
             index = 0;
             m_index = y0 * p -> SizeX + p -> SizeX - (sx - dx);
             for(i = 0; i < sy; i ++){
                 memcpy(ptr + index,p -> frames + m_index,sx - dx);
                 index += sx;
                 m_index += p -> SizeX;
                 _y ++;
                 if(_y >= p -> SizeY){
                     m_index = p -> SizeX - (sx - dx);
                     _y = 0;
                 }
             }
             _y = y0;
             index = sx - dx;
             m_index = y0 * p -> SizeX;
             for(i = 0; i < sy; i ++){
                 memcpy(ptr + index,p -> frames + m_index,dx);
                 index += sx;
                 m_index += p -> SizeX;
                 _y ++;
                 if(_y >= p -> SizeY){
                     m_index = 0;
                     _y = 0;
                 }
             }
         }
         else {
             _y = y0;
             index = 0;
             m_index = y0 * p -> SizeX + cx - sx2;
             int max_frames_size = p->SizeX * p->SizeY * p->Size;
             for(i = 0; i < sy; i ++){
                 if (m_index + sx >= max_frames_size) {
                     memcpy(ptr + index, p -> frames + m_index, max_frames_size - m_index);
                 } else {
                     memcpy(ptr + index, p -> frames + m_index, sx);
                 }
                 index += sx;
                 m_index += p -> SizeX;
                 _y ++;
                 if(_y >= p -> SizeY){
                     m_index = cx - sx2;
                     _y = 0;
                 }
             }
         }
     }
     XGR_PutSpr(x,y,sx,sy,ptr,XGR_BLACK_FON);
     delete[] ptr;
     _y = 0;
     scr_x = sx2;
     scr_y = sy2;
 /*
     if(scr_x > MAP_PTR_X && scr_x < sx - MAP_PTR_X && scr_y > MAP_PTR_X && scr_y < sy - MAP_PTR_X)
         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[aciGamerColor],aciMapVngColors[aciGamerColor],XGR_FILLED);
 */
 #ifdef _ACI_MAP_TESTING_
     index = 2;
     for(_y = 0; _y < (1 << MAP_POWER_Y); _y += 256){
         for(_x = 0; _x < (1 << MAP_POWER_X); _x += 256){
             scr_x = -1;
             scr_x0 = ((_x * p -> SizeX) >> MAP_POWER_X);
             if(cx < sx2){
                 if(p -> SizeX - scr_x0 < dx)
                     scr_x = scr_x0 - (p -> SizeX - dx);
                 else {
                     if(scr_x0 < sx - dx)
                         scr_x = scr_x0 + dx;
                     else
                         scr_x = -1;
                 }
             }
             else {
                 if(p -> SizeX - cx < sx2){
                     if(p -> SizeX - scr_x0 < sx - dx)
                         scr_x = scr_x0 - (p -> SizeX - (sx - dx));
                     else {
                         if(scr_x0 < dx)
                             scr_x = scr_x0 + (sx - dx);
                         else
                             scr_x = -1;
                     }
                 }
                 else {
                     scr_x = scr_x0 - (cx - sx2);
                 }
             }
             scr_y = ((_y * p -> SizeY) >> MAP_POWER_Y) - y0;
             if(scr_y < 0)
                 scr_y += p -> SizeY;
             if(scr_x > MAP_PTR_X && scr_x < sx - MAP_PTR_X && scr_y > MAP_PTR_X && scr_y < sy - MAP_PTR_X){
                 switch(index){
                     case 1:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR1,MAP_COLOR1,XGR_FILLED);
                         break;
                     case 2:
                         XGR_SetPixel(x + scr_x,y + scr_y,(_y >> 8) & 255);
                         break;
                     case 3:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR3,MAP_COLOR3,XGR_FILLED);
                         break;
                 }
             }
         }
     }
 #else
     index = getObjectPosition(_x,_y);
     while(index != -1){
         if(index){
             scr_x = -1;
             scr_x0 = ((_x * p -> SizeX) >> MAP_POWER_X);
             if(cx < sx2){
                 if(p -> SizeX - scr_x0 < dx)
                     scr_x = scr_x0 - (p -> SizeX - dx);
                 else {
                     if(scr_x0 < sx - dx)
                         scr_x = scr_x0 + dx;
                     else
                         scr_x = -1;
                 }
             }
             else {
                 if(p -> SizeX - cx < sx2){
                     if(p -> SizeX - scr_x0 < sx - dx)
                         scr_x = scr_x0 - (p -> SizeX - (sx - dx));
                     else {
                         if(scr_x0 < dx)
                             scr_x = scr_x0 + (sx - dx);
                         else
                             scr_x = -1;
                     }
                 }
                 else {
                     scr_x = scr_x0 - (cx - sx2);
                 }
             }
             scr_y = ((_y * p -> SizeY) >> MAP_POWER_Y) - y0;
             if(scr_y < 0)
                 scr_y += p -> SizeY;
             if(scr_x > MAP_PTR_X && scr_x < sx - MAP_PTR_X && scr_y > MAP_PTR_X && scr_y < sy - MAP_PTR_X){
                 switch(index){
                     case 1:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR1,MAP_COLOR1,XGR_FILLED);
                         break;
 #ifdef _ACI_SHOW_BUGS_ON_MAP_
                     case 2:
                         XGR_SetPixel(x + scr_x,y + scr_y,MAP_COLOR2);
                         break;
 #endif
                     case 3:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR3,MAP_COLOR3,XGR_FILLED);
                         break;
                     case 4:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[0],aciMapVngColors[0],XGR_FILLED);
                         break;
                     case 5:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[1],aciMapVngColors[1],XGR_FILLED);
                         break;
                     case 6:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[2],aciMapVngColors[2],XGR_FILLED);
                         break;
                     case 7:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[3],aciMapVngColors[3],XGR_FILLED);
                         break;
                     case 8:
                         if(scr_x > MAP_PTR_XL && scr_x < sx - MAP_PTR_XL && scr_y > MAP_PTR_XL && scr_y < sy - MAP_PTR_XL)
                             XGR_Rectangle(x + scr_x - MAP_PTR_XL2,y + scr_y - MAP_PTR_XL2,MAP_PTR_XL,MAP_PTR_XL,aciMapVngColors[3],aciMapVngColors[0],XGR_FILLED);
                         break;
                     case 9:
                         if(scr_x > MAP_PTR_XL && scr_x < sx - MAP_PTR_XL && scr_y > MAP_PTR_XL && scr_y < sy - MAP_PTR_XL)
                             XGR_Rectangle(x + scr_x - MAP_PTR_XL2,y + scr_y - MAP_PTR_XL2,MAP_PTR_XL,MAP_PTR_XL,aciMapVngColors[3],aciMapVngColors[1],XGR_FILLED);
                         break;
                     case 10:
                         if(scr_x > MAP_PTR_XL && scr_x < sx - MAP_PTR_XL && scr_y > MAP_PTR_XL && scr_y < sy - MAP_PTR_XL)
                             XGR_Rectangle(x + scr_x - MAP_PTR_XL2,y + scr_y - MAP_PTR_XL2,MAP_PTR_XL,MAP_PTR_XL,aciMapVngColors[3],aciMapVngColors[2],XGR_FILLED);
                         break;
                     case 11:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[5],aciMapVngColors[5],XGR_FILLED);
                         break;
                     case 12:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[6],aciMapVngColors[6],XGR_FILLED);
                         break;
                     case 13:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[7],aciMapVngColors[7],XGR_FILLED);
                         break;
                     case 14:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[8],aciMapVngColors[8],XGR_FILLED);
                         break;
                     case 15:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[9],aciMapVngColors[9],XGR_FILLED);
                         break;
                     case 16:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[10],aciMapVngColors[10],XGR_FILLED);
                         break;
                 }
             }
         }
         index = getObjectPosition(_x,_y);
     }
 #endif
 }
References aScrDisp, getObjectPosition(), MAP_COLOR1, MAP_COLOR2, MAP_COLOR3, MAP_POWER_X, MAP_POWER_Y, MAP_PTR_X, MAP_PTR_X2, bmlObject::Size, bmlObject::SizeX, bmlObject::SizeY, ViewX, ViewY, XGR_BLACK_FON, XGR_FILLED, XGR_PutSpr, XGR_Rectangle, and XGR_SetPixel.
Referenced by redraw_fnc().
SoundEscaveOff()
void SoundEscaveOff (void)
{
     EffectsOff();
     for(int i = 0;i < EFF_MAX;i++){
         if ((SndData[i].status & ESCAVE_SOUND) && SndData[i].lpDSB){
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
     }
     EffectsOn(0);
 }
Referenced by actIntDispatcher::i_finit().
swap_buf_col()
void swap_buf_col (int src, int dest, int sx, int sy, unsigned char * buf)
 {
     int i,j,index = 0;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             if(buf[index] == src) buf[index] = dest;
             index ++;
         }
     }
 }
Referenced by aciWorldInfo::redraw(), CounterPanel::redraw(), invMatrix::redraw_matrix(), and invMatrix::redraw_shadow_cells().
Variable Documentation
aCellFrame
unsigned char* aCellFrame
Referenced by build_cell_frame(), free_cell_frame(), CounterPanel::redraw(), invMatrix::redraw_matrix(), and invMatrix::redraw_shadow_cells().
aCellSize
int aCellSize = 20
Referenced by build_cell_frame(), invItem::calc_shape_center(), invItem::get_coords(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), invMatrix::init(), CounterPanel::init(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), invItem::redraw(), CounterPanel::redraw(), invMatrix::redraw_matrix(), and invMatrix::redraw_shadow_cells().
aci_CellSize
int aci_CellSize = 20
Referenced by actIntDispatcher::i_finit(), and actIntDispatcher::i_init().
aci_curLocationID
int aci_curLocationID = 0
Referenced by actIntDispatcher::i_init().
aci_curLocationName
const char* aci_curLocationName = ""
Referenced by aciAddTeleportMenuItem(), aciInitShopItems(), uvsBunch::begin_race(), uvsBunch::game_exit(), uvsVanger::get_shop(), actIntDispatcher::i_init(), uvsVanger::makeJump(), uvsVanger::prepare_shop(), uvsVanger::Quant(), uniVangPrepare(), uvsActIntSell(), uvsCloseQuant(), and uvsPassagerFromStatistic().
aci_iScreenID
char* aci_iScreenID = NULL
Referenced by actIntDispatcher::i_init(), iPreInitFirst(), and iQuantFirst().
aci_iscrPal
unsigned char aci_iscrPal[768]
Referenced by actIntDispatcher::i_init().
aci_ivMapName
char* aci_ivMapName = NULL
Referenced by actIntDispatcher::i_init(), and ivMapPrepare().
aci_SecondMatrixID
int aci_SecondMatrixID = 0
Referenced by aciInitAviID(), and actIntDispatcher::EventQuant().
aci_tmp
int aci_tmp = 0
Referenced by aIndData::init(), and actIntDispatcher::redraw().
aci_tmp_max
int aci_tmp_max = 64
Referenced by aIndData::init().
aciBufRedrawFlag
int aciBufRedrawFlag = 0
Referenced by invMatrix::flush(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), invItem::redraw(), invMatrix::redraw(), invMatrix::redraw_matrix(), and invMatrix::redraw_shadow_cells().
aciColorSchemes
unsigned char** aciColorSchemes = NULL
Referenced by actIntDispatcher::i_init(), actIntDispatcher::init(), and actIntDispatcher::~actIntDispatcher().
aciColSchemeLen
int aciColSchemeLen = 0
aciCurArmor
int aciCurArmor = 63
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciCurColorScheme
unsigned char* aciCurColorScheme
Referenced by aciInitMechosInfo(), aciInitPanel(), aciInitPricePanel(), aciRedrawParamsPanel(), aciWorldMap::build_map(), aciBitmapMenu::build_pict(), actIntDispatcher::change_items(), invMatrix::flush(), actIntDispatcher::i_init(), aIndData::init(), fncMenu::init(), actIntDispatcher::init(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), iScreen::prepare(), actIntDispatcher::put_in_slot(), aciWorldInfo::redraw(), fncMenuItem::redraw(), invItem::redraw(), fncMenu::redraw(), CounterPanel::redraw(), InfoPanel::redraw(), invMatrix::redraw_matrix(), invMatrix::redraw_shadow_cells(), fncMenuItem::redraw_str(), actIntDispatcher::set_move_item(), aciWorldMap::show_jump_count(), and aciWorldMap::show_link().
aciCurCredits01
int aciCurCredits01 = 0
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurDominance
int aciCurDominance = 0
Referenced by aciRedrawParamsPanel().
aciCurDvcResource
int aciCurDvcResource = 0
Referenced by ActionDispatcher::DrawResource(), and aIndData::init().
aciCurEnergy
int aciCurEnergy = 63
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciCurFrame
int aciCurFrame = 0
Referenced by actIntDispatcher::EventQuant().
aciCurJumpCount
int aciCurJumpCount = 3
Referenced by aiMessageTouch(), VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), aIndData::init(), aciWorldMap::quant(), VangerUnit::SensorQuant(), and aciWorldMap::show_jump_count().
aciCurJumpImpulse
int aciCurJumpImpulse = 0
Referenced by Object::direct_keyboard_control(), and aIndData::init().
aciCurLoad
int aciCurLoad = 0
Referenced by actIntDispatcher::calc_load(), and aIndData::init().
aciCurLuck
int aciCurLuck = 0
Referenced by aciRedrawParamsPanel().
aciCurTime
int aciCurTime = 0
Referenced by CounterPanel::init().
aciCurWpnResource
int aciCurWpnResource = 0
Referenced by aIndData::init().
aciItmTextQueueSize
int aciItmTextQueueSize extern
Referenced by aciInitItmTextQueue(), aciReadItmText(), and actIntDispatcher::EventQuant().
aciKeyboardLocked
int aciKeyboardLocked extern
Referenced by actIntDispatcher::KeyQuant().
aciMaxArmor
int aciMaxArmor = 64
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciMaxDvcResource
int aciMaxDvcResource = 1
Referenced by ActionDispatcher::DrawResource(), and aIndData::init().
aciMaxEnergy
int aciMaxEnergy = 64
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciMaxJumpCount
int aciMaxJumpCount = 5
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), aIndData::init(), and aciWorldMap::show_jump_count().
aciMaxJumpImpulse
int aciMaxJumpImpulse = 1
Referenced by aIndData::init().
aciMaxLoad
int aciMaxLoad = 1
Referenced by actIntDispatcher::calc_load(), and aIndData::init().
aciMaxWpnResource
int aciMaxWpnResource = 1
Referenced by aIndData::init().
aciMechMessiahEvent
int aciMechMessiahEvent = 0
Referenced by actIntDispatcher::EventQuant(), and ActionDispatcher::FunctionQuant().
aciML_ToolzerRadius
int aciML_ToolzerRadius extern
Referenced by actIntDispatcher::aml_check_redraw().
aciNumColSchemes
int aciNumColSchemes = 0
Referenced by actIntDispatcher::~actIntDispatcher().
aciPickupDevices
int aciPickupDevices = 1
Referenced by aciCheckItemPickUp(), and actIntDispatcher::EventQuant().
aciPickupItems
int aciPickupItems = 1
Referenced by aciCheckItemPickUp(), and actIntDispatcher::EventQuant().
aciPrevDominance
int aciPrevDominance = -1
Referenced by aciRedrawParamsPanel().
aciPrevJumpCount
int aciPrevJumpCount = -1
Referenced by actIntDispatcher::EventQuant(), actIntDispatcher::i_finit(), actIntDispatcher::init(), and aciWorldMap::quant().
aciPrevLuck
int aciPrevLuck = -1
Referenced by aciRedrawParamsPanel().
aciProtractorEvent
int aciProtractorEvent = 0
Referenced by actIntDispatcher::EventQuant(), and ActionDispatcher::FunctionQuant().
aciSaveVersion
const int aciSaveVersion = 1
Referenced by actIntDispatcher::load_data(), and actIntDispatcher::save_data().
aciShopMenuLog
int aciShopMenuLog extern
aciSTR_AIR_RESERVE
char* aciSTR_AIR_RESERVE extern
Referenced by aciInitStrings().
aciSTR_AUTOSAVE
char* aciSTR_AUTOSAVE extern
Referenced by aciInitStrings(), and acsSaveData().
aciSTR_BROKEN
char* aciSTR_BROKEN extern
Referenced by aciInitStrings().
aciSTR_BURST
char* aciSTR_BURST extern
Referenced by aciInitStrings().
aciSTR_DAMAGE
char* aciSTR_DAMAGE extern
Referenced by aciInitStrings().
aciSTR_DAY
char* aciSTR_DAY extern
Referenced by aciInitStrings().
aciSTR_DEATHS
char* aciSTR_DEATHS extern
Referenced by aciInitStrings(), and aciShowFrags().
aciSTR_DOMINANCE
char* aciSTR_DOMINANCE extern
Referenced by aciInitStrings(), and aciRedrawParamsPanel().
aciSTR_EMPTY_SLOT
char* aciSTR_EMPTY_SLOT extern
Referenced by aciInitStrings(), acsPrepareSlotName(), and acsPrepareSlotNameInput().
aciSTR_ENERGY_SHIELD
char* aciSTR_ENERGY_SHIELD extern
Referenced by aciInitStrings().
aciSTR_IN_PACK
char* aciSTR_IN_PACK extern
Referenced by aciInitStrings().
aciSTR_KILLS
char* aciSTR_KILLS extern
Referenced by aciInitStrings(), and aciShowFrags().
aciSTR_LOAD
char* aciSTR_LOAD extern
Referenced by aciInitStrings().
aciSTR_LUCK
char* aciSTR_LUCK extern
Referenced by aciInitStrings(), and aciRedrawParamsPanel().
aciSTR_MECHANIC_ARMOR
char* aciSTR_MECHANIC_ARMOR extern
Referenced by aciInitStrings().
aciSTR_NO_CASH
char* aciSTR_NO_CASH extern
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_imove_quant().
aciSTR_OFF
char* aciSTR_OFF extern
Referenced by aciAdd2Targets(), aciDeleteFromTargets(), aciHandleSubmenuEvent(), aciInitStrings(), aciRefreshTargetsMenu(), and actIntDispatcher::init_submenu().
aciSTR_PICKUP_ITEMS_OFF
char* aciSTR_PICKUP_ITEMS_OFF extern
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_move_quant().
aciSTR_PICKUP_WEAPONS_OFF
char* aciSTR_PICKUP_WEAPONS_OFF extern
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_move_quant().
aciSTR_PRICE
char* aciSTR_PRICE extern
Referenced by aciGetPrice(), and aciInitStrings().
aciSTR_PutThis
char* aciSTR_PutThis extern
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_imove_quant().
aciSTR_RESTORING_SPEED
char* aciSTR_RESTORING_SPEED extern
Referenced by aciInitStrings().
aciSTR_SECONDS
char* aciSTR_SECONDS extern
Referenced by aciInitStrings().
aciSTR_SHOTS
char* aciSTR_SHOTS extern
Referenced by aciInitStrings().
aciSTR_SPIRAL_CAPACITY
char* aciSTR_SPIRAL_CAPACITY extern
Referenced by aciInitStrings().
aciSTR_UNDEFINED_PRICE
char* aciSTR_UNDEFINED_PRICE extern
Referenced by aciGetPrice(), and aciInitStrings().
aciSTR_UNNAMED_SAVE
char* aciSTR_UNNAMED_SAVE extern
Referenced by aciInitStrings(), acsPrepareSlotNameInput(), and acsSaveData().
aciSTR_VELOCITY
char* aciSTR_VELOCITY extern
Referenced by aciInitStrings().
aciSTR_WORKING_TIME
char* aciSTR_WORKING_TIME extern
Referenced by aciInitStrings().
aciTeleportEvent
int aciTeleportEvent = 0
Referenced by aciHandleSubmenuEvent(), and VangerUnit::Quant().
aciTEXT_COLOR
const int aciTEXT_COLOR = 165 + (2 << 16)
Referenced by actIntDispatcher::EventQuant().
aciTextColBright
int aciTextColBright = 0
Referenced by actIntDispatcher::EventQuant().
aciTextColBrightDelta
int aciTextColBrightDelta = 1
Referenced by actIntDispatcher::EventQuant().
aciTextEndFlag
int aciTextEndFlag = 0
Referenced by actIntDispatcher::KeyQuant().
aciWorldIndex
int aciWorldIndex extern
Referenced by actIntDispatcher::EventQuant().
aCosTable
int* aCosTable extern
Referenced by a_calc_tables().
actIntPal
unsigned char* actIntPal
Referenced by actIntDispatcher::flush(), actIntDispatcher::i_init(), actIntDispatcher::pal_flush(), and uvsCloseQuant().
aIndArrowBML
bmlObject* aIndArrowBML extern
Referenced by aciFreeAll(), aInit(), aIndData::build_pict(), and aIndData::init().
aIndBackBML
bmlObject* aIndBackBML extern
Referenced by aciFreeAll(), and aIndData::build_pict().
aIndDataBML
bmlObject* aIndDataBML extern
Referenced by aciFreeAll(), and aIndData::build_pict().
aScrDisp
actIntDispatcher* aScrDisp extern
Referenced by invMatrix::backup(), iGameMap::draw(), LoadingRTO1::Init(), and LoadingRTO2::Init().
aScrFonts
aciFont** aScrFonts extern
Referenced by aFreeFonts(), aLoadFonts(), aOutStr(), aPutChar(), aPutStr(), aStrHeight(), aStrLen(), fncMenuItem::init(), aciWorldInfo::redraw(), invItem::redraw(), CounterPanel::redraw(), InfoPanel::redraw(), and fncMenu::set_prefix().
aScrFonts32
aciFont** aScrFonts32 extern
Referenced by CounterPanel::redraw(), and InfoPanel::redraw().
aSinTable
int* aSinTable extern
Referenced by a_calc_tables().
AVI_index
int* AVI_index extern
backupMatrix
invMatrix* backupMatrix
Referenced by actIntDispatcher::cancel_matrix(), actIntDispatcher::EventQuant(), and actIntDispatcher::swap_matrices().
curItemID
int curItemID = 1
curMatrixID
int curMatrixID = 0
Referenced by actIntDispatcher::init().
CurrentWorld
int CurrentWorld extern
Referenced by aciPrepareWorldsMenu(), aciWorldLinksON(), addVanger(), aiMessageTouch(), BunchEvent(), VangerUnit::CalcAiFactor(), ChangeVanger(), ChangeWorld(), CheckPlayerList(), ClearBarell(), ItemsDispatcher::Close(), CloseBunchPal(), CloseCyclicPal(), BulletObject::CreateBullet(), DangerDataType::CreateDanger(), ItemsDispatcher::CreateEnableCrypt(), CreatePhantomTarget(), ItemsDispatcher::CryptQuant(), VangerUnit::Destroy(), TntCreature::Destroy(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), DestroySmoothCheck(), DestroySpot(), TrackUnit::DrawMechosParticle(), ParticleObject::DrawQuant(), HordeObject::DrawQuant(), VangerUnit::DrawQuant(), BulletObject::Event(), DangerDataType::FireWork(), SkyFarmerList::Free(), GeneralSystemFree(), GeneralSystemInit(), GeneralSystemOpen(), GeneralTableOpen(), GetEscaveDist(), getObjectPosition(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), actIntDispatcher::init(), ClefList::Init(), SkyFarmerList::Init(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), InsectList::Init(), VangerUnit::InitAI(), VangerUnit::InitEnvironment(), MLload(), VangerUnit::NetCreateVanger(), TntCreature::NetDestroy(), TntCreature::NetQuant(), NetworkWorldOpen(), ActionDispatcher::NewFunction(), ObjectDestroy(), ItemsDispatcher::Open(), ActionDispatcher::Open(), TiristorEngine::Open(), ItemGenerator::Open(), GameObjectDispatcher::Open(), OpenCyclicPal(), ActionDispatcher::PromptChangeCycle(), ActionDispatcher::PromptQuant(), GameObjectDispatcher::Quant(), StuffObject::Quant(), GloryPlace::Quant(), VangerUnit::Quant(), ActionDispatcher::Quant(), DoorEngine::Quant(), ItemGenerator::Quant(), TntCreature::Quant(), DangerDataType::Quant(), RadialRender(), VangerUnit::SensorQuant(), PalPoint::Set(), StaticOpen(), VangerUnit::TerrainQuant(), VangerUnit::UsingCrotrig(), and VLload().
ExclusiveLog
int ExclusiveLog extern
Referenced by actIntDispatcher::flush(), and actIntDispatcher::i_init().
GameQuantReturnValue
int GameQuantReturnValue extern
Referenced by actIntDispatcher::flush().
iCellSize
int iCellSize = 20
Referenced by actIntDispatcher::i_init().
iChatExit
int iChatExit extern
Referenced by actIntDispatcher::EventQuant(), iChatInit(), iChatKeyQuant(), and iChatMouseHandler().
iMouseLPressFlag
int iMouseLPressFlag extern
Referenced by actIntDispatcher::iKeyQuant(), iMS_LeftUnpress(), and set_mouse().
iMousePrevX
int iMousePrevX extern
Referenced by actIntDispatcher::iKeyQuant().
iMousePrevY
int iMousePrevY extern
Referenced by actIntDispatcher::iKeyQuant().
iMouseRPressFlag
int iMouseRPressFlag extern
Referenced by iMS_RightUnpress(), and set_mouse().
iMouseX
int iMouseX extern
Referenced by actIntDispatcher::iKeyQuant(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), and actIntDispatcher::KeyQuant().
iMouseY
int iMouseY extern
Referenced by actIntDispatcher::iKeyQuant(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), and actIntDispatcher::KeyQuant().
iScrDisp
iScreenDispatcher* iScrDisp extern
Referenced by aciExitShop(), actIntDispatcher::EventQuant(), aciLocationInfo::get_shop_scr(), actIntDispatcher::inv_mouse_imove_quant(), and aciLocationInfo::prepare().
iScreenLog
int iScreenLog extern
Referenced by iScrQuantFinit(), and iScrQuantPrepare().
iscrPal
unsigned char* iscrPal extern
Referenced by actIntDispatcher::i_init().
MAX_ITEM_ID
const int MAX_ITEM_ID = 9
MAX_MATRIX_ID
const int MAX_MATRIX_ID = 3
NetworkON
int NetworkON extern
Referenced by actIntDispatcher::flush(), actIntDispatcher::iKeyTrap(), and actIntDispatcher::KeyQuant().
PalIterLock
int PalIterLock extern
Referenced by VangerUnit::AddFree(), actIntDispatcher::flush(), actIntDispatcher::i_init(), actIntDispatcher::pal_flush(), and VangerUnit::Quant().
Pause
int Pause extern
Referenced by actIntDispatcher::flush(), KeyCenter(), and GameQuantRTO::Quant().
prevWorld
int prevWorld
Referenced by actIntDispatcher::i_finit(), and actIntDispatcher::i_init().
uvsCurrentWorldUnable
int uvsCurrentWorldUnable extern
Referenced by actIntDispatcher::change_items(), CloseBunchPal(), GeneralTableOpen(), InsectList::Init(), actIntDispatcher::inv_mouse_imove_quant(), and actIntDispatcher::set_move_item().
uvsTabuTaskFlag
int uvsTabuTaskFlag extern