Vangers: src/actint/actintml.cpp File Reference
actintml.cpp File Reference
#include "../global.h"
#include "../iscreen/hfont.h"
#include "../iscreen/iscreen.h"
#include "../iscreen/iworld.h"
#include "../iscreen/iml.h"
#include "item_api.h"
#include "actint.h"
#include "a_consts.h"
#include "../iscreen/ikeys.h"
#include "../uvs/diagen.h"
#include "mlconsts.h"
#include "mlstruct.h"
Macros
#define AML_MIN_SHUTDOWN_TIMER 10
#define AML_SHUTDOWN_DELTA 3
Functions
void aciNextPhrase (void)
void aciClearQuestMenu (void)
void aciExitShop (void)
void iShopForcedExit (void)
void iLockShop (void)
void iUnlockShop (void)
void iLockExit (void)
void iUnlockExit (void)
void aciAcceptRubox (void)
void aciAddRubox (void)
void aciExpropriation (void)
void aciChange2Raffa (void)
void aciWaitNextPeriod (void)
void aciOfferWeezyk (void)
void aciEscaveKickOut (void)
void aciStealItem (int type)
void aciML_Close (int id, int phase)
void aciML_Invert (int id, int phase)
aciML_Event * aciML_GetEvent (int key, int mode)
void aciML_KeyTrap (int key, int mode)
void aciML_StartEvent (aciML_Event *ev)
void aci_SendEvent (int cd, int dt=0)
void aciOfferEleech (void)
int isEventActive (int key, int mode)
int isChannelActive (int ch)
void StartupIML (void)
void InitIML (void)
void put_map (int x, int y, int sx, int sy)
void get_fon (int x, int y, int sx, int sy, unsigned char *buf)
void put_fon (int x, int y, int sx, int sy, unsigned char *buf)
void get_terr_fon (int x, int y, int sx, int sy, unsigned char *buf)
void put_terr_fon (int x, int y, int sx, int sy, unsigned char *buf)
void iSoundQuant (int value=0)
void aciML_Pause (void)
void aciML_Resume (void)
void dg_SendEvent (int code)
int aciML_DropEvents (int channel, int pr)
void aciML_SendEvent (int cd, int d0, int d1)
void SetFlushIML (int x, int y, int sx, int sy)
Variables
int iMouseX
int iMouseY
int iTheEND
int aciEndSpeech
int aciBreathFlag
int ActiveTerrain []
actIntDispatcher * aScrDisp
aciML_Dispatcher * aciML_D
int aciML_ToolzerON = 0
int aciML_ToolzerRadius = 0
int aciML_ShutdownCount = 0
Macro Definition Documentation
AML_MIN_SHUTDOWN_TIMER
#define AML_MIN_SHUTDOWN_TIMER 10
AML_SHUTDOWN_DELTA
#define AML_SHUTDOWN_DELTA 3
Function Documentation
aci_SendEvent()
void aci_SendEvent (int cd, int dt = 0)
 {
     aScrDisp -> send_event(cd,dt);
 }
Referenced by dg_SendEvent(), aciML_Dispatcher::event_quant(), and aciML_Dispatcher::startup().
aciAcceptRubox()
void aciAcceptRubox (void)
 {
     aciML_D -> key_trap(AML_RUBOX_CODE,AML_KEY);
 }
References aciML_D, AML_KEY, and AML_RUBOX_CODE.
Referenced by dg_SendEvent().
aciAddRubox()
void aciAddRubox (void)
 {
     uvsActInt* p;
     invItem* itm;
     listElem* el = (listElem*)GGamer;
     if(!aciPutItem(ACI_RUBOX,-1,-1)) ErrH.Abort("aciPutItem() failed...");
     itm = (invItem*)aScrDisp -> curMatrix -> items -> last;
     p = new uvsActInt;
     p -> type = ACI_RUBOX;
     itm -> uvsDataPtr = p;
     p -> pos_x = itm -> MatrixX;
     p -> pos_y = itm -> MatrixY;
     p -> link(el);
     GGamer = (uvsActInt*)el;
 }
References XErrorHandler::Abort(), ACI_RUBOX, aciPutItem(), aScrDisp, curMatrix, ErrH, and GGamer.
Referenced by dg_SendEvent().
aciChange2Raffa()
void aciChange2Raffa (void)
 {
     invMatrix* m,*rf = NULL;
     uvsActInt* u,*u1;
     listElem* el;
     if(aScrDisp -> curMatrix) aciExpropriation();
     aScrDisp -> curMatrix = NULL;
     if(GGamerMechos){
         //std::cout<<"aciChange2Raffa if(GGamerMechos) "<<GGamerMechos<<std::endl;
         m = aScrDisp -> get_imatrix(GGamerMechos -> type);
         if(!m -> uvsDataPtr) {
             m -> uvsDataPtr = GGamerMechos;
         }
         //std::cout<<"aciChange2Raffa el = GMechos "<<GMechos<<std::endl;
         el = GMechos;
         GGamerMechos -> link(el);
         GMechos = (uvsActInt*)el;
         //std::cout<<"aciChange2Raffa GMechos = (uvsActInt*)el "<<GMechos<<std::endl;
     }
     GGamerMechos = NULL;
     m = (invMatrix*)aScrDisp -> i_matrixList -> last;
     while(m){
         //std::cout<<"aciChange2Raffa invMatrix type: "<<m->type<<std::endl;
         if(m -> flags & IM_RAFFA){
             if(m -> uvsDataPtr){
                 u = (uvsActInt*)m -> uvsDataPtr;
                 //std::cout<<"aciChange2Raffa GMechos "<<GMechos<<std::endl;
                 u -> delink(GMechos);
                 u->next = NULL;
                 u->prev = NULL;
                 if(((iListElement*)m) == iShopItem)
                     aciNextShopItem();
                 //std::cout<<"aciChange2Raffa GGamerMechos = u "<<u<<std::endl;
                 GGamerMechos = u;
                 u1 = aciGetMechos(m -> type);
                 if(u1)
                     m -> uvsDataPtr = u1;
                 else
                     m -> uvsDataPtr = NULL;
                 aScrDisp -> curMatrix = aScrDisp -> alloc_matrix(m -> type,1);
                 aScrDisp -> curMatrix -> uvsDataPtr = u;
                 return;
             } else {
                 rf = m;
             }
         }
         m = (invMatrix*)m -> prev;
     }
     if(!rf)
         ErrH.Abort("Free mechos not found...");
     m = rf;
     u = new uvsActInt;
     u -> type = m -> type;
     u -> price = u -> sell_price = 1;
     if(((iListElement*)m) == iShopItem)
         aciNextShopItem();
     //std::cout<<"aciChange2Raffa2 GGamerMechos = u"<<std::endl;
     GGamerMechos = u;
     u1 = aciGetMechos(m -> type);
     if(u1)
         m -> uvsDataPtr = u1;
     else
         m -> uvsDataPtr = NULL;
     aScrDisp -> curMatrix = aScrDisp -> alloc_matrix(m -> type,1);
     aScrDisp -> curMatrix -> uvsDataPtr = u;
 }
References aciExpropriation(), aScrDisp, curMatrix, GGamerMechos, GMechos, and NULL.
Referenced by dg_SendEvent().
aciClearQuestMenu()
void aciClearQuestMenu (void)
 {
     fncMenuSet* m;
     m = aScrDisp -> qMenu;
     if(m && m -> flags & FMC_DATA_INIT){
         m -> finit();
         m -> redraw();
         m -> redraw_owner();
     }
 }
References aScrDisp.
Referenced by aciNextPhrase(), and dg_SendEvent().
aciEscaveKickOut()
void aciEscaveKickOut (void)
 {
     char* str;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p) return;
     str = dgD -> getQout();
     if(str){
         p -> free_list();
         aciInitPanel(p,(unsigned char*)str);
         p -> set_redraw();
     }
     aciStartSpeech();
 }
References ACI_ANSWER_PANEL, aciInitPanel(), aciStartSpeech(), aScrDisp, and dgD.
Referenced by dg_SendEvent().
aciExitShop()
void aciExitShop (void)
 {
     iScrDisp -> ret_val = 1;
     iScrDisp -> flags |= SD_EXIT;
 }
References iScrDisp.
Referenced by aciML_Dispatcher::event_quant().
aciExpropriation()
void aciExpropriation (void)
 {
     if(!aScrDisp -> curMatrix) return;
     invItem* itm = (invItem*)aScrDisp -> curMatrix -> items -> last,*itm1;
     uvsActInt* ptr = (uvsActInt*)aScrDisp -> curMatrix -> uvsDataPtr;
     if(!ptr) ErrH.Abort("Bad sell mechos...");
     while(itm){
         itm1 = (invItem*)itm -> prev;
         aScrDisp -> curMatrix -> remove_item(itm);
         itm -> flags |= INV_ITEM_NO_PAY;
         aciSell_Item(itm);
         itm = itm1;
     }
 }
References XErrorHandler::Abort(), aScrDisp, curMatrix, ErrH, and prev.
Referenced by aciChange2Raffa(), and dg_SendEvent().
aciML_Close()
void aciML_Close (int id, int phase)
 {
     int cur_phase = GetPhaseIML(id);
     if(cur_phase != phase)
         HandlerIML(AML_GO_PHASE,id,phase);
 }
References AML_GO_PHASE, GetPhaseIML(), and HandlerIML().
Referenced by aciML_Dispatcher::event_quant().
aciML_DropEvents()
int aciML_DropEvents (int channel, int pr)
 {
     return aciML_D -> drop_channel_events(channel,pr);
 }
References aciML_D.
Referenced by aciML_Data::key_trap().
aciML_GetEvent()
aciML_Event * aciML_GetEvent (int key, int mode)
 {
     return aciML_D -> getEvent(key,mode);
 }
References aciML_D, and key().
Referenced by aciML_EventSeqLine::putSeq().
aciML_Invert()
void aciML_Invert (int id, int phase)
 {
     int cur_phase = GetPhaseIML(id);
     if(cur_phase != phase){
         HandlerIML(AML_GO_PHASE,id,phase);
     }
     else {
         HandlerIML(AML_GO_PHASE,id,0);
     }
 }
References AML_GO_PHASE, GetPhaseIML(), and HandlerIML().
Referenced by aciML_Dispatcher::event_quant().
aciML_KeyTrap()
void aciML_KeyTrap (int key, int mode)
 {
     aciML_D -> key_trap(key,mode);
 }
References aciML_D, and key().
Referenced by aciML_EventSeqLine::firstQuant(), and aciML_Data::rnd_event_quant().
aciML_Pause()
void aciML_Pause (void)
 {
     PauseIMLall();
     aciML_D -> flags |= AML_PAUSE;
 }
References aciML_D, and PauseIMLall().
Referenced by actIntDispatcher::EventQuant().
aciML_Resume()
void aciML_Resume (void)
 {
     ResumeIMLall();
     aciML_D -> flags &= ~AML_PAUSE;
 }
References aciML_D, and ResumeIMLall().
Referenced by actIntDispatcher::EventQuant().
aciML_SendEvent()
void aciML_SendEvent (int cd, int d0, int d1)
 {
     aciML_D -> send_event(cd,d0,d1);
 }
References aciML_D.
Referenced by aciOfferEleech(), aciOfferWeezyk(), and aciML_Event::quant().
aciML_StartEvent()
void aciML_StartEvent (aciML_Event * ev)
aciNextPhrase()
void aciNextPhrase (void)
 {
     unsigned char* str;
     iScreenObject* obj;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p || !p -> iScreenOwner) return;
     if(aciEscaveDead){
         aciClearQuestMenu();
         obj = (iScreenObject*)p -> iScreenOwner -> owner;
         p -> free_list();
         str = (unsigned char*)dgD -> getQdead();
         if(str) aciInitPanel(p,str);
         p -> set_redraw();
         return;
     }
     if(!aciSpeechStarted && dgD -> isEnd())
         aciSpeechEndLocked = aciSpeechBegLocked = aciEndSpeech = 1;
     aciClearQuestMenu();
     obj = (iScreenObject*)p -> iScreenOwner -> owner;
     p -> free_list();
     str = (unsigned char*)dgD -> getNextPhrase();
     if(aciEndSpeech){
         if(!dgD -> isEnd()){
             aciEndSpeech = 0;
         }
         else {
             p -> set_redraw();
             return;
         }
     }
     if(str)
         aciInitPanel(p,str);
     aciSpeechEndLocked = dgD -> isEnd();
     if(str && !aciEscaveEmpty)
         aciStartSpeech();
     p -> set_redraw();
 }
References ACI_ANSWER_PANEL, aciClearQuestMenu(), aciEndSpeech, aciEscaveDead, aciEscaveEmpty, aciInitPanel(), aciSpeechBegLocked, aciSpeechEndLocked, aciSpeechStarted, aciStartSpeech(), aScrDisp, and dgD.
Referenced by aciML_Dispatcher::event_quant().
aciOfferEleech()
void aciOfferEleech (void)
 {
     int w_id = aScrDisp -> wMap -> world_ptr[aScrDisp -> curLocData -> WorldID] -> uvsID;
     aciML_SendEvent(AML_KEY_TRAP,AML_KEY,AML_ELEECH_CODE);
     WaitGameInTown(w_id);
 }
References aciML_SendEvent(), AML_ELEECH_CODE, AML_KEY, AML_KEY_TRAP, aScrDisp, WaitGameInTown(), and wMap.
Referenced by dg_SendEvent().
aciOfferWeezyk()
void aciOfferWeezyk (void)
 {
     aciML_SendEvent(AML_KEY_TRAP,AML_KEY,AML_ELEECH_CODE);
 }
References aciML_SendEvent(), AML_ELEECH_CODE, AML_KEY, and AML_KEY_TRAP.
Referenced by dg_SendEvent().
aciStealItem()
void aciStealItem (int type)
 {
     listElem* el;
     uvsActInt* u;
     invItem* p,*p1;
     if(!GTreasureItem) return;
     u = GTreasureItem;
     while(u){
         if(u -> type == type) break;
         u = (uvsActInt*)u -> next;
     }
     if(!u) return;
     if(u -> type == ACI_BOORAWCHIK) aciEscaveEmpty = 1;
     p = aScrDisp -> get_iitem(u -> type);
     p1 = aScrDisp -> alloc_item();
     p -> clone(p1);
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         aciSell_Item(aScrDisp -> curItem);
         aScrDisp -> curItem = NULL;
     }
     aScrDisp -> flags |= AS_INV_MOVE_ITEM;
     aScrDisp -> curItem = p1;
     set_mouse_cursor(p1 -> frame,p1 -> ScreenSizeX,p1 -> ScreenSizeY);
     u -> delink(GTreasureItem);
     el = (listElem*)GGamer;
     u -> link(el);
     GGamer = (uvsActInt*)el;
     p1 -> uvsDataPtr = u;
 }
References GTreasureItem.
aciWaitNextPeriod()
void aciWaitNextPeriod (void)
 {
     int w_id = aScrDisp -> wMap -> world_ptr[aScrDisp -> curLocData -> WorldID] -> uvsID;
     WaitGameInTown(w_id);
 }
References aScrDisp, WaitGameInTown(), and wMap.
Referenced by dg_SendEvent().
dg_SendEvent()
void dg_SendEvent (int code)
 {
     switch(code){
         case AML_GET_QUESTION:
             aci_SendEvent(EV_SHOW_QUESTS);
             break;
         case AML_TAKE_ELEECH:
             aciOfferEleech();
             break;
         case AML_TAKE_WEEZYK:
             aciOfferWeezyk();
             break;
         case AML_WAIT_NEXT_PERIOD:
             aciWaitNextPeriod();
             break;
         case AML_CLEAR_QUESTION:
             aciClearQuestMenu();
             break;
         case AML_ABORT_ESCAVE_SESSION:
             iShopForcedExit();
             break;
         case AML_BLOCK_SHOP:
             iLockShop();
             break;
         case AML_UNBLOCK_SHOP:
             iUnlockShop();
             break;
         case AML_BLOCK_EXIT:
             iLockExit();
             break;
         case AML_UNBLOCK_EXIT:
             iUnlockExit();
             break;
         case AML_LAMPASSO_THEEND:
             iShopForcedExit();
             GameOverID = GAME_OVER_LAMPASSO;
             iTheEND = 1;
             break;
         case AML_KICK_OUT_FROM_ESCAVE:
             aciEscaveKickOut();
             break;
         case AML_ACCEPT_RUBBOX:
             aciAcceptRubox();
             break;
         case AML_ADD_RUBBOX:
             aciAddRubox();
             break;
         case AML_EXPROPRIATION:
             aciExpropriation();
             break;
         case AML_CHANGE_TO_RAFFA:
             aciChange2Raffa();
             break;
     }
 }
References aci_SendEvent(), aciAcceptRubox(), aciAddRubox(), aciChange2Raffa(), aciClearQuestMenu(), aciEscaveKickOut(), aciExpropriation(), aciOfferEleech(), aciOfferWeezyk(), aciWaitNextPeriod(), AML_ABORT_ESCAVE_SESSION, AML_ACCEPT_RUBBOX, AML_ADD_RUBBOX, AML_BLOCK_EXIT, AML_BLOCK_SHOP, AML_CHANGE_TO_RAFFA, AML_CLEAR_QUESTION, AML_EXPROPRIATION, AML_GET_QUESTION, AML_KICK_OUT_FROM_ESCAVE, AML_LAMPASSO_THEEND, AML_TAKE_ELEECH, AML_TAKE_WEEZYK, AML_UNBLOCK_EXIT, AML_UNBLOCK_SHOP, AML_WAIT_NEXT_PERIOD, EV_SHOW_QUESTS, GAME_OVER_LAMPASSO, GameOverID, iLockExit(), iLockShop(), iShopForcedExit(), iTheEND, iUnlockExit(), and iUnlockShop().
get_fon()
void get_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int i,j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     int yy,xx;
     for(j = 0; j < sy; j ++){
         yy = iYCYCL(y + j);
         for(i = 0; i < sx; i ++){
             xx = iXCYCL(x + i);
             buf[index + i] = lta[yy][xx];
         }
         index += sx;
     }
 }
Referenced by aciML_ItemData::put2low_level().
get_terr_fon()
void get_terr_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int i,j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     int yy,xx;
     for(j = 0; j < sy; j ++){
         yy = iYCYCL(y + j);
         for(i = 0; i < sx; i ++){
             xx = iXCYCL(x + i);
             buf[index + i] = lta[yy][xx + H_SIZE];
         }
         index += sx;
     }
 }
Referenced by aciML_ItemData::check_double_level(), and aciML_ItemData::put2low_level().
iLockExit()
void iLockExit (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button01");
     if(p) p -> flags |= OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
iLockShop()
void iLockShop (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button04");
     if(p) p -> flags |= OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
InitIML()
void InitIML (void)
 {
     ML_FRAME_DELTA = new uchar[ML_FRAME_SIZE];
     ML_FRAME_TERRAIN = new uchar[ML_FRAME_SIZE];
 }
Referenced by aciML_Dispatcher::init().
isChannelActive()
int isChannelActive (int ch)
 {
     return aciML_D -> check_channel_events(ch);
 }
References aciML_D.
Referenced by aciML_Event::check_seq().
isEventActive()
int isEventActive (int key, int mode)
 {
     return aciML_D -> isEventActive(key,mode);
 }
References aciML_D, and key().
Referenced by aciML_Event::quant().
iShopForcedExit()
void iShopForcedExit (void)
 {
 /*
     if(iScrDisp -> ActiveEv){
         iScrDisp -> ActiveEv -> flags &= ~EV_ACTIVE;
         iScrDisp -> ActiveEv = NULL;
     }
     iScrDisp -> key_trap(AML_FORCED_EXIT_CODE);
 */
     iForcedExitFlag = 1;
 }
References iForcedExitFlag.
Referenced by dg_SendEvent().
iSoundQuant()
void iSoundQuant (int value = 0)
 {
     switch(value){
         case ACI_NOISE_SOUND:
             SOUND_NOISE();
             break;
         case ACI_SPEECH0_SOUND:
             SOUND_TALK0();
             break;
         case ACI_SPEECH1_SOUND:
             SOUND_TALK1();
             break;
         case ACI_SPEECH2_SOUND:
             SOUND_TALK2();
             break;
         case ACI_SPEECH3_SOUND:
             SOUND_TALK2();
             break;
         case ACI_WND_SOUND:
             SOUND_WINDOW();
             break;
         case ACI_GATE_SOUND:
             SOUND_GATE();
             break;
         case ACI_L0_OUTIN_SOUND:
         case ACI_L2_OUTIN_SOUND:
             SOUND_OUTIN();
             break;
         case ACI_L0_SWARM_SOUND:
         case ACI_L1_SWARM_SOUND:
             SOUND_SWARM();
             break;
         case ACI_L0_ANGRY_SOUND:
         case ACI_L1_ANGRY_SOUND:
         case ACI_L5_ANGRY_SOUND:
             SOUND_ANGRY();
             break;
         case ACI_L1_STEP0_SOUND:
         case ACI_L2_STEP_SOUND:
         case ACI_L3_STEP_SOUND:
         case ACI_L4_STEP_SOUND:
             SOUND_STEP();
             break;
         case ACI_L2_GETOUT_SOUND:
         case ACI_L3_GETOUT_SOUND:
         case ACI_L5_GETOUT_SOUND:
         case ACI_L6_GETOUT_SOUND:
             SOUND_GETOUT();
             break;
         case ACI_L4_HAND_SOUND:
             SOUND_HAND();
             break;
         case ACI_L5_SCRATCH_SOUND:
         case ACI_L6_SCRATCH_SOUND:
             SOUND_SCRATCH();
             break;
         case ACI_L5_CLAP_SOUND:
         case ACI_L6_CLAP_SOUND:
             SOUND_CLAP();
             break;
     }
 }
Referenced by aciML_Dispatcher::event_quant().
iUnlockExit()
void iUnlockExit (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button01");
     if(p) p -> flags &= ~OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
iUnlockShop()
void iUnlockShop (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button04");
     if(p) p -> flags &= ~OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
put_fon()
void put_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     for(j = 0; j < sy; j ++){
         memcpy(lta[y + j] + x,buf + index,sx);
         index += sx;
     }
 }
Referenced by aciML_ItemData::put2low_level(), and aciML_ItemData::put_frame().
put_map()
void put_map (int x, int y, int sx, int sy)
 {
     int j;
     unsigned char** ltc = ivMap -> lineTcolor;
     int yy,x0,x1,bsx,index;
     int scr_offs = iScreenOffs;
     x0 = x;
     x1 = x + sx;
     if(x0 < scr_offs) x0 = scr_offs;
     if(x1 >= scr_offs + I_RES_X) x1 = scr_offs + I_RES_X;
     bsx = x1 - x0;
     if(bsx > 0){
         index = (x0 - scr_offs) + y * XGR_MAXX;
         for(j = 0; j < sy; j ++){
             yy = iYCYCL(y + j);
             memcpy(XGR_VIDEOBUF + index,ltc[yy] + x0,bsx);
             index += XGR_MAXX;
         }
     }
 }
Referenced by aciML_Dispatcher::flush(), and aciML_ItemData::put_frame().
put_terr_fon()
void put_terr_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int i,j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     int yy,xx;
     for(j = 0; j < sy; j ++){
         yy = iYCYCL(y + j);
         for(i = 0; i < sx; i ++){
             xx = iXCYCL(x + i);
             lta[yy][xx + H_SIZE] = buf[index + i];
         }
         index += sx;
     }
 }
Referenced by aciML_ItemData::put2low_level(), and aciML_ItemData::put_frame().
SetFlushIML()
void SetFlushIML (int x, int y, int sx, int sy)
 {
     aciML_D -> add_flush(x,y,sx,sy);
 }
References aciML_D.
Referenced by aciML_ItemData::put_frame(), and iMobileLocation::setPhase().
StartupIML()
void StartupIML (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++){
         imlChannel[i] = 0;
         imlMode[i] = 0;
         imlQueue[i] = -1;
         imlPauseMode[i] = 0;
         imlLocked[i] = 0;
         }
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::init().
Variable Documentation
aciBreathFlag
int aciBreathFlag extern
Referenced by aciML_Dispatcher::event_quant().
aciEndSpeech
int aciEndSpeech extern
Referenced by aci_LocationQuantPrepare(), aciNextPhrase(), and aciML_Dispatcher::event_quant().
aciML_D
aciML_Dispatcher* aciML_D
Referenced by aci_iScreenQuant(), aciAcceptRubox(), aciHideLocation(), aciML_DropEvents(), aciML_GetEvent(), aciML_KeyTrap(), aciML_Pause(), aciML_Resume(), aciML_SendEvent(), aciPutTreasureItem(), aciShowLocation(), aciStartSpeech(), aParseScript(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), iKeyTrap(), iOutEscaveFinit(), iQuantPrepare(), isChannelActive(), isEventActive(), and SetFlushIML().
aciML_ShutdownCount
int aciML_ShutdownCount = 0
Referenced by aciML_Dispatcher::quant(), and aciML_Dispatcher::shutdown().
aciML_ToolzerON
int aciML_ToolzerON = 0
Referenced by iMS_LeftUnpress(), aciML_Dispatcher::quant(), and aciML_Dispatcher::startup().
aciML_ToolzerRadius
int aciML_ToolzerRadius = 0
Referenced by actIntDispatcher::aml_check_redraw().
ActiveTerrain
int ActiveTerrain[] extern
Referenced by aciML_ItemData::build_empty_frame(), pixDownSet(), pixSet(), and ToolzerQuant().
aScrDisp
actIntDispatcher* aScrDisp extern
Referenced by aciML_Dispatcher::quant().
iMouseX
int iMouseX extern
Referenced by aciML_Data::key_trap(), aciML_Dispatcher::key_trap(), and aciML_Dispatcher::quant().
iMouseY
int iMouseY extern
Referenced by aciML_Data::key_trap(), aciML_Dispatcher::key_trap(), and aciML_Dispatcher::quant().
iTheEND
int iTheEND extern
Referenced by dg_SendEvent().