Vangers: src/actint/ascr_fnc.cpp File Reference
ascr_fnc.cpp File Reference
#include "../global.h"
#include "../lang.h"
#include <zlib.h>
#include "../runtime.h"
#include "../network.h"
#include "../terra/world.h"
#include "../iscreen/hfont.h"
#include "../iscreen/iscreen.h"
#include "../iscreen/iscript.h"
#include "../iscreen/iml.h"
#include "item_api.h"
#include "../units/uvsapi.h"
#include "../uvs/univang.h"
#include "../uvs/diagen.h"
#include "a_consts.h"
#include "actint.h"
#include "credits.h"
#include "aci_str.h"
#include "mlconsts.h"
#include "mlstruct.h"
#include "../iscreen/ikeys.h"
#include "../iscreen/zip.h"
#include "../iscreen/ext_evnt.h"
#include "../sound/hsound.h"
#include "aci_evnt.h"
#include "acsconst.h"
#include "aci_scr.h"
#include "chtree.h"
Macros
#define iEXT_INIT_SOCKETS 47
#define ACI_ITEM_QUEUE_MAX 5
#define _GENERATE_EXIT_
#define ACI_COLOR_MASK 0xFF
#define MAP_COLOR 200
#define MAP_COLOR1 166
#define MAP_COLOR2 143
#define MAP_COLOR3 111
#define MAP_PTR_X 3
#define MAP_PTR_X2 1
#define MAP_PTR_XL 6
#define MAP_PTR_XL2 3
#define MAP_CUR_VANGER 0
#define MAP_VANGER 1
#define MAP_INSECT 2
#define ACI_PROMPT_OFFSET 50
#define ACI_PROMPT_FONT 7
#define ACI_PROMPT_COLOR 175
#define ACI_PROMPT_DELTA_X 1
#define ACI_PROMPT_DELTA_Y 1
#define ACI_FRAG_TIMER 300
#define ACI_FRAG_FONT 0
#define ACI_RACING_X 70
#define ACI_RACING_Y 70
#define ACI_RACING2_X 70
#define ACI_RACING2_Y 70
#define ACI_RACING_X_H 80
#define ACI_RACING_Y_H 80
#define ACI_RACING2_X_H 80
#define ACI_RACING2_Y_H 80
#define ACI_RACING_FONT 7
#define ACI_RACING_COL 103
#define ACI_RACING_COL2 111
Functions
void uvsChangeCycle (void)
void iSortPlayers (int mode=0)
void aciInitEndGame (int id)
int aciTextQuant (void)
void aciAddTabutask (int num)
void aciCompleteTabutask (void)
void aciDisableParametersMenu (void)
void uvsTabuComplete (int i)
void uvsTabuCreate (uvsActInt *pa, int num)
void aciReadItmText (void)
char * uvsGetNameByID (int type, int &ID)
char * aciGetItemEscave (int p2)
void acsChangeStrState (int id)
void acsSetStrState (int id, int state)
int acsGetStrState (int id)
int uvsReturnWorldGamerVisit (int where)
void uvsChangeLuck (void)
void uvsChangeDominance (void)
void iSoundQuant (int value=0)
void i_slake_pal (unsigned char *p, int delta)
void i_evince_pal (unsigned char *p, int delta)
void aWriteHelpString (int count, int *x, int *y, int font, unsigned char **pstr, int timer, int color, int space, unsigned int *pcolor)
void EffectsOff (void)
void iSaveData (void)
void iLoadData (void)
void acsSaveData (void)
void acsLoadData (void)
void acsCompressData (char *p)
void acsDecompressData (char *p)
void aciShowFrags (void)
void aciRedrawParamsPanel (int x, int y, int sx, int sy)
void aciSaveUVSList (XStream &fh, uvsActInt *p)
void aciLoadUVSList (XStream &fh, uvsActInt **p, int list_type=0)
void aciFreeUVSList (uvsActInt *p)
void aciFreeUVS (void)
void aciPutTreasureItem (void)
void aciStealItem (int type)
void acsPrepareSlotName (int id, int slot_num)
void acsPrepareSlotNameInput (int id, int slot_num)
int acsQuant (void)
void acsHandleExtEvent (int code, int data0=0, int data1=0, int data2=0)
void GeneralSystemLoad (XStream &in)
void GeneralSystemSave (XStream &out)
void load_map_bmp (int num)
void set_screen (int Dx, int Dy, int mode, int xcenter, int ycenter)
void set_mouse_cursor (char *p, int sx, int sy)
void restore_mouse_cursor (void)
void aciInitAviObject (void)
void aciFreeAll (void)
void loadMouseFrames (void)
void build_cell_frame (void)
void free_cell_frame (void)
void swap_buf_col (int src, int dest, int sx, int sy, unsigned char *buf)
void mem_putspr (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char *src, unsigned char *dest)
void mem_rectangle (int x, int y, int sx, int sy, int bsx, int col_in, int col_out, int mode, void *buf)
void aParseScript (const char *fname, char *bname=NULL)
void acsParseScript (const char *fname, char *bname=NULL)
void aciChangeWorld (int w_id)
void aciInitWorldIDs (void)
void aciPrepareWorldsMenu (void)
void aciInitPanel (InfoPanel *p, unsigned char *str)
void aciClearQuestMenu (void)
void aciInitShopButtons (void)
void aciSet_aMouse (void)
void aciSet_iMouse (void)
void aInit (void)
void aRedraw (void)
void aLoadFonts (void)
void aFreeFonts (void)
void aKeyInit (void)
void aKeyTrap (SDL_Event *k)
void aKeyQuant (void)
void actIntQuant (void)
void aci_iScreenQuant (void)
void aciSetCameraMenu (void)
void aciHandleCameraEvent (int code, int data)
void aci_setMatrixBorder (void)
void aci_setScMatrixBorder (void)
void aciAutoMoveItems (void)
void aciSetMechName (void)
void aciSellMoveItem (void)
void aciRemoveUvsItem (uvsActInt *ptr)
void aciSell_Item (invItem *p)
void aciSell_Matrix (invMatrix *p)
void aciInitInfoPanels (void)
int aciCheckSellItem (void)
void aciSetTimePanel (void)
void aciInitEvLineID (void)
void aciChangeList (void)
void aciChangeLineID (void)
void aciInitShopItems (void)
void aciCloseShopMenu (void)
void aciShopMenuUp (void)
void aciShopMenuDown (void)
void aciBuildShopList (void)
void aciInitShopList (void)
void aciChooseShopItem (void)
void aciSetShopItem (int id)
void aciNextPhrase (void)
void aciStartSpeech (void)
void aciEscaveKickOut (void)
void aciInitMechosInfo (invMatrix *p, InfoPanel *ip)
void aciOfferEleech (void)
void aciWaitNextPeriod (void)
void aciOfferWeezyk (void)
void aciGetEleech (void)
void aciNextShopItem (void)
void aciPrevShopItem (void)
void aciInitShopAvi (void)
void aciBuyItem (void)
void aciOpenGate (void)
void aciCloseGate (void)
void SelectCompasTarget (const char *n)
char * GetCompasTarget (void)
int aciCheckCredits (void)
void aciShowCamerasMenu (int x, int y, int sx, int sy)
void aciHandleSubmenuEvent (int id, fncMenuItem *p)
int aciGetCurCycle (void)
void aciInitAviID (void)
void aciChangeAviIndex (void)
void aciBuildQuestList (void)
char * aciGetItemLoad (invItem *p, int mode)
char * aciGetPrice (iListElement *p, int mode, int sell_mode)
void aciInitPricePanel (InfoPanel *ip, iListElement *p, int mode, int sell_mode)
int aciGetCurMatrixPrice (void)
void aciCHandler (int key)
int aciCheckSlot (void)
void iScrQuantPrepare (void)
void iScrQuantFinit (void)
void show_map (int x, int y, int sx, int sy)
void set_mouse (void)
void a_calc_tables (void)
void a_buf_line (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char *buf)
void aMS_init (void)
void aci_SendEvent (int cd, int dt=0)
void aciPackFile (char *fname)
void aciUnPackFile (char *fname)
void aMS_LeftPress (int, int, int)
void aMS_LeftUnpress (int, int, int)
void aMS_RightPress (int, int, int)
void aMS_RightUnpress (int, int, int)
void aMS_Movement (int, int, int)
void aciShowRacingPlace (void)
void aciPutBufSpr (int x, int y, int sx, int sy, int bsx, void *src, void *dest, int col, int col_sz)
void aciPutSpr32 (int x, int y, int sx, int sy, void *buf, int col, int col_sz)
void aciPutSpr32clip (int x, int y, int sx, int sy, void *buf, int col, int col_sz)
void aOutText32 (int x, int y, int color, void *text, int font, int hspace, int vspace)
void aOutText32clip (int x, int y, int color, void *text, int font, int hspace, int vspace)
int aTextWidth32 (void *text, int font, int hspace)
int aTextHeight32 (void *text, int font, int vspace)
void aciInitStrings (void)
void aciInitItmTextQueue (void)
void aLoadFonts32 (void)
void aPutNum (int x, int y, int font, int color, int str, int bsx, unsigned char *buf, int space)
int aStrLen (unsigned char *str, int font, int space)
int aStrLen32 (void *str, int font, int space)
int aStrHeight (int font)
int aStrHeight32 (int font)
void aPutStr32 (int x, int y, int font, int color, int color_size, void *str, int bsx, void *buf, int space)
void aPutStr (int x, int y, int font, int color, unsigned char *str, int bsx, unsigned char *buf, int space)
void aOutStr (int x, int y, int font, int color, unsigned char *str, int space)
void aPutChar (int x, int y, int font, int color, int str, int bsx, int bsy, unsigned char *buf)
void change_screen (int mode)
void aciSendEvent2actint (int code, actintItemData *p, int data)
actintItemData * aciGetLast (void)
void a_buf_setpixel (int x, int y, int sx, int sy, int col, unsigned char *buf)
void a_buf_line2 (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char *buf)
void fill_buf (int fx, int fy, int src_col, int dest_col, int sx, int sy, unsigned char *buf)
void mem_putspr_h (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char *src, unsigned char *dest)
void aci_LocationQuantPrepare (void)
void aci_LocationQuantFinit (void)
int aciReInitItem (actintItemData *p)
int aciReInitItemXY (actintItemData *p, int x, int y)
void aciKillLinks (void)
uvsActInt * aciGetMechos (int id)
uvsActInt * aciGetGamerItem (int id)
uvsActInt * aciGetShopItem (int id)
void redraw_fnc (int x, int y, int sx, int sy, int fnc)
void aciWorldLinksON (void)
void aciWorldExploredInfo (void)
void aciWorldLinksOFF (void)
void aciOpenWorldLink (int w1, int w2)
int aciWorldLinkExist (int w1, int w2, int sp_flag)
int uvs_aciKillItem (int id, int id1)
int uvs_aciKillOneItem (int id, int x, int y)
void uvs_aciChangeItem (int id_from, int id_to)
void uvs_aciChangeOneItem (int id_from, int id_to, int x, int y)
void uvs_aciChangeOneItem (int id_from, int id_to, uvsActInt *ptr)
void aciChangeItem (actintItemData *p)
int aciCheckItemCredits (void)
void aciInitCurMatrixPtr (void)
void aciShowBlockPhrase (void)
void aciAskQuestion (void)
int aciCheckItemPickUp (actintItemData *p)
void aciAddTeleportMenuItem (int id, int fnc_id)
void aciDeleteTeleportMenuItem (int fnc_id)
void aciAdd2Targets (char *p)
void aciRefreshTargetsMenu (void)
void aciDeleteFromTargets (char *p)
void aciPay4Item (invItem *p)
void aciSaveData (void)
void aciLoadData (void)
void ibsout (int x, int y, void *ptr)
void aciPrepareMenus (void)
void aciGetItemCoords (actintItemData *p, int &x, int &y)
void aciGetItemCoords (int id, int &x, int &y)
int aciPutItem (int id, int x, int y)
void aciRemoveItem (actintItemData *d)
void aciNewMechos (int newID)
void aciSendPrompt (aciPromptData *p)
void aciActivateItemFunction (int itemID, int fncID)
void aciDeactivateItemFunction (int itemID, int fncID)
void aciAcceptRubox (void)
void aciGetRubox (void)
void aciAddRubox (void)
void aciExpropriation (void)
void aciChange2Raffa (void)
char * aciGetPlayerName (void)
char * aciGetPlayerPassword (void)
int aciGetPlayerColor (void)
void aciClearTeleportMenu (void)
void aciExitShop (void)
void aciPrepareText (char *ptr)
void aciAutoSave (void)
void aciDropMoveItem (void)
void aPutChar32 (int x, int y, int font, int color, int color_size, int str, int bsx, void *buf)
void aciSetRedraw (void)
void aciVMapPrepare (void)
void aciPrepareScreenText (char *ptr, int sz, int max_len)
void aciPrepareEndImage (void)
char * aciLoadPackedFile (XStream &fh, int &out_sz)
int sdlEventToCode (SDL_Event *event)
Variables
int aciPrevJumpCount
PlayerData ** iPlayers
int dgMood
int iMultiFlag
int aciCurLuck
int aciPrevLuck
const char * iVideoPath
int aciCurDominance
int aciPrevDominance
char * acsBackupStr
unsigned char * palbuf
int RAM16
int aciPickupItems
int aciPickupDevices
int iNumPlayers
int prevWorld
uvsActInt * GGamer
uvsActInt * GCharItem
unsigned char * iscrPal
int iScreenActive
int iSlotNumber
int ShowImageKeyFlag
int ShowImageMouseFlag
uvsContimer ConTimer
int GameQuantReturnValue
int aci_SecondMatrixID
int curMatrixID
actIntDispatcher * aScrDisp
char * aImageBmp
unsigned char * aCellFrame
unsigned char * actIntPal
int beebos
int uvsCurrentWorldUnable
int aCellSize
int iCellSize
int aci_CellSize
int iMouseX
int iMouseY
int iEvLineID
int curMatrix
int ViewX
int ViewY
short iMouseSizeX
short iMouseSizeY
short iMouseSize
unsigned char * iMouseFrames
short aMouseSizeX
short aMouseSizeY
short aMouseSize
unsigned char * aMouseFrames
short MouseSizeX
short MouseSizeY
short MouseSize
unsigned char * MouseFrames
unsigned char * aciCurColorScheme
int aciTeleportEvent
uvsVanger * Gamer
int MouseSize2
int camera_moving_xy_enable
int camera_moving_z_enable
int camera_slope_enable
int camera_rotate_enable
int iCurMultiGame
aciFont ** aScrFonts32 = NULL
aciFont ** aScrFonts = NULL
int aciCurCredits02 = 0
int aciRacingFlag = 0
char * aciCurRaceType = NULL
char * aciCurRaceInfo = NULL
int aciMouseFlagL = 0
int aciMouseFlagR = 0
int aInitFlag = 0
int actintLowResFlag = 0
int actintActiveFlag = 0
int actIntLog = 0
int aciGamerColor = 0
int aciCurMechosID = 0
int * aSinTable = NULL
int * aCosTable = NULL
bmlObject * aIndArrowBML = NULL
bmlObject * aIndDataBML = NULL
bmlObject * aIndBackBML = NULL
iListElement * iShopItem
XBuffer * aciXConv
unsigned char * aciDgPrefix = NULL
unsigned char * aciDgPostfix = NULL
aciScreenText * aciImgText = NULL
int aciCurAviIndex = 0
int aciCurAviIndexDelta = 0
int aciLoadLog = 0
int aciShopMenuLog = 0
int aciWorldIndex = -1
int acsScreenID = 1
int acsCurrentSlotID = ACS_SAVE_SLOT0
int acsCurrentSlotNum = 0
int acsAllocFlag = 0
int aciSpeechStarted = 0
int aciSpeechBegLocked = 0
int aciSpeechEndLocked = 0
int aciEndSpeech = 0
int aciSpeechMode = 2
int aciBreathFlag = 0
int aciEscaveDead = 0
int aciEscaveEmpty = 0
aciML_EventSeq * aciSpeechSeq = NULL
aciCHTree * aciTreeData = NULL
int aciKeyboardLocked = 0
int aciAutoRun = 0
int aciAutoSaveFlag = 0
const char * aciSTR_ON = aciSTR_ON1
const char * aciSTR_OFF = aciSTR_OFF1
const char * aciSTR_DAY = aciSTR_DAY1
const char * aciSTR_UNDEFINED_PRICE = aciSTR_UNDEFINED_PRICE1
const char * aciSTR_PRICE = aciSTR_PRICE1
const char * aciSTR_EMPTY_SLOT = aciSTR_EMPTY_SLOT1
const char * aciSTR_UNNAMED_SAVE = aciSTR_UNNAMED_SAVE1
const char * aciSTR_AUTOSAVE = aciSTR_AUTOSAVE1
const char * aciSTR_KILLS = aciSTR_KILLS1
const char * aciSTR_DEATHS = aciSTR_DEATHS1
const char * aciSTR_LUCK = aciSTR_LUCK1
const char * aciSTR_DOMINANCE = aciSTR_DOMINANCE1
const char * aciSTR_BROKEN = aciSTR_BROKEN1
const char * aciSTR_ENERGY_SHIELD = aciSTR_ENERGY_SHIELD1
const char * aciSTR_RESTORING_SPEED = aciSTR_RESTORING_SPEED1
const char * aciSTR_MECHANIC_ARMOR = aciSTR_MECHANIC_ARMOR1
const char * aciSTR_VELOCITY = aciSTR_VELOCITY1
const char * aciSTR_SPIRAL_CAPACITY = aciSTR_SPIRAL_CAPACITY1
const char * aciSTR_AIR_RESERVE = aciSTR_AIR_RESERVE1
const char * aciSTR_DAMAGE = aciSTR_DAMAGE1
const char * aciSTR_LOAD = aciSTR_LOAD1
const char * aciSTR_SHOTS = aciSTR_SHOTS1
const char * aciSTR_BURST = aciSTR_BURST1
const char * aciSTR_WORKING_TIME = aciSTR_WORKING_TIME1
const char * aciSTR_SECONDS = aciSTR_SECONDS1
const char * aciSTR_IN_PACK = aciSTR_IN_PACK1
const char * aciSTR_NO_CASH = aciSTR_NO_CASH1
const char * aciSTR_PICKUP_ITEMS_OFF = aciSTR_PICKUP_ITEMS_OFF1
const char * aciSTR_PICKUP_WEAPONS_OFF = aciSTR_PICKUP_WEAPONS_OFF1
const char * aciSTR_PutThis = aciSTR_PutThis1
const char * aciSTR_Ware1 = aciSTR_Ware11
const char * aciSTR_Ware2 = aciSTR_Ware21
const char * aciSTR_Checkpoints = aciSTR_Checkpoints1
int aciItmTextQueueSize = 0
int aciItmTextQueueCur = 0
invItem ** aciItmTextQueue = NULL
iScreenOption ** iScrOpt
const double _PI128 = 3.14/128.0
int aciBadPhraseFlag = 0
const unsigned ACI_FRAG_COL0 = (252 | (246 << 8))
const unsigned ACI_FRAG_COL1 = (143 | (135 << 8))
const unsigned ACI_FRAG_COL2 = (156 | (151 << 8))
const unsigned ACI_FRAG_COL3 = (173 | (166 << 8))
const unsigned ACI_FRAG_COL4 = (200 | (195 << 8))
const unsigned ACI_FRAG_COL5 = (238 | (233 << 8))
const unsigned ACI_FRAG_COL6 = (238 | (233 << 8))
const unsigned ACI_FRAG_COL7 = (238 | (233 << 8))
const unsigned ACI_FRAG_COL8 = (252 | (246 << 8))
const unsigned ACI_FRAG_COL9 = (156 | (151 << 8))
Macro Definition Documentation
_GENERATE_EXIT_
#define _GENERATE_EXIT_
ACI_COLOR_MASK
#define ACI_COLOR_MASK 0xFF
ACI_FRAG_FONT
#define ACI_FRAG_FONT 0
ACI_FRAG_TIMER
#define ACI_FRAG_TIMER 300
ACI_ITEM_QUEUE_MAX
#define ACI_ITEM_QUEUE_MAX 5
ACI_PROMPT_COLOR
#define ACI_PROMPT_COLOR 175
ACI_PROMPT_DELTA_X
#define ACI_PROMPT_DELTA_X 1
ACI_PROMPT_DELTA_Y
#define ACI_PROMPT_DELTA_Y 1
ACI_PROMPT_FONT
#define ACI_PROMPT_FONT 7
ACI_PROMPT_OFFSET
#define ACI_PROMPT_OFFSET 50
ACI_RACING2_X
#define ACI_RACING2_X 70
ACI_RACING2_X_H
#define ACI_RACING2_X_H 80
ACI_RACING2_Y
#define ACI_RACING2_Y 70
ACI_RACING2_Y_H
#define ACI_RACING2_Y_H 80
ACI_RACING_COL
#define ACI_RACING_COL 103
ACI_RACING_COL2
#define ACI_RACING_COL2 111
ACI_RACING_FONT
#define ACI_RACING_FONT 7
ACI_RACING_X
#define ACI_RACING_X 70
ACI_RACING_X_H
#define ACI_RACING_X_H 80
ACI_RACING_Y
#define ACI_RACING_Y 70
ACI_RACING_Y_H
#define ACI_RACING_Y_H 80
iEXT_INIT_SOCKETS
#define iEXT_INIT_SOCKETS 47
MAP_COLOR
#define MAP_COLOR 200
MAP_COLOR1
#define MAP_COLOR1 166
MAP_COLOR2
#define MAP_COLOR2 143
MAP_COLOR3
#define MAP_COLOR3 111
MAP_CUR_VANGER
#define MAP_CUR_VANGER 0
MAP_INSECT
#define MAP_INSECT 2
MAP_PTR_X
#define MAP_PTR_X 3
MAP_PTR_X2
#define MAP_PTR_X2 1
MAP_PTR_XL
#define MAP_PTR_XL 6
MAP_PTR_XL2
#define MAP_PTR_XL2 3
MAP_VANGER
#define MAP_VANGER 1
Function Documentation
a_buf_line()
void a_buf_line (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char * buf)
 {
     int dx,dy,xinc,yinc,err,cnt,index,i_xinc,i_yinc;
     dx = x2 - x1;
     dy = y2 - y1;
     xinc = (dx > 0) ? 1 : (dx < 0) ? (-1) : 0;
     yinc = (dy > 0) ? 1 : (dy < 0) ? (-1) : 0;
     i_xinc = xinc;
     i_yinc = (dy > 0) ? sx : (dy < 0) ? (-sx) : 0;
     dx = abs(dx);
     dy = abs(dy);
     index = x1 + y1 * sx;
     if(dx > dy){
         err = dx/2;
         cnt = dx + 1;
         while(cnt--){
             buf[index] = col;
             x1 += xinc;
             index += i_xinc;
             err += dy;
             if(err >= dx){
                 if(cnt)
                     buf[index] = col;
                 err -= dx;
                 y1 += yinc;
                 index += i_yinc;
             }
         }
     }
     else {
         err = dy / 2;
         cnt = dy + 1;
         while(cnt--){
             buf[index] = col;
             y1 += yinc;
             index += i_yinc;
             err += dx;
             if(err >= dy){
                 if(cnt)
                     buf[index] = col;
                 err -= dy;
                 x1 += xinc;
                 index += i_xinc;
             }
         }
     }
 }
Referenced by build_cell_frame().
a_buf_line2()
void a_buf_line2 (int x1, int y1, int x2, int y2, int col, int sx, int sy, unsigned char * buf)
 {
     int dx,dy,xinc,yinc,err,cnt,index,i_xinc,i_yinc;
     dx = x2 - x1;
     dy = y2 - y1;
     xinc = (dx > 0) ? 1 : (dx < 0) ? (-1) : 0;
     yinc = (dy > 0) ? 1 : (dy < 0) ? (-1) : 0;
     i_xinc = xinc;
     i_yinc = (dy > 0) ? sx : (dy < 0) ? (-sx) : 0;
     dx = abs(dx);
     dy = abs(dy);
     index = x1 + y1 * sx;
     if(dx > dy){
         err = dx/2;
         cnt = dx + 1;
         while(cnt--){
             buf[index] = col;
             x1 += xinc;
             index += i_xinc;
             err += dy;
             if(err >= dx){
                 err -= dx;
                 y1 += yinc;
                 index += i_yinc;
             }
         }
     }
     else {
         err = dy / 2;
         cnt = dy + 1;
         while(cnt--){
             buf[index] = col;
             y1 += yinc;
             index += i_yinc;
             err += dx;
             if(err >= dy){
                 err -= dy;
                 x1 += xinc;
                 index += i_xinc;
             }
         }
     }
 }
Referenced by aciWorldMap::show_link().
a_buf_setpixel()
void a_buf_setpixel (int x, int y, int sx, int sy, int col, unsigned char * buf)
 {
     buf[x + y * sx] = col;
 }
a_calc_tables()
void a_calc_tables (void)
 {
     int i;
     double phi;
     if(!aSinTable && !aCosTable){
         aSinTable = new int[256];
         aCosTable = new int[256];
         for(i = 0; i < 256; i ++){
             phi = ((double)i) * _PI128;
             aSinTable[i] = (int)(sin(phi) * 256.0);
             aCosTable[i] = (int)(cos(phi) * 256.0);
         }
     }
 }
References _PI128, aCosTable, and aSinTable.
aci_iScreenQuant()
void aci_iScreenQuant (void)
 {
     aScrDisp -> iKeyQuant();
     aScrDisp -> EventQuant();
     aciML_D -> quant();
     aScrDisp -> i_redraw();
     aScrDisp -> i_flush();
 }
References aciML_D, and aScrDisp.
aci_LocationQuantFinit()
void aci_LocationQuantFinit (void)
 {
     iScrQuantFinit();
     aScrDisp -> i_finit();
     aciKillLinks();
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
     aciAutoRun = iGetOptionValue(iAUTO_ACCELERATION);
 }
References aciKillLinks(), aScrDisp, and iScrQuantFinit().
Referenced by EscaveOutRTO::Finit(), and FirstEscaveOutRTO::Finit().
aci_LocationQuantPrepare()
void aci_LocationQuantPrepare (void)
 {
     aciSpeechBegLocked = aciSpeechEndLocked = 0;
     aciSpeechStarted = aciEndSpeech = 0;
     aciEscaveDead = aciEscaveEmpty = 0;
     aciBreathFlag = 0;
     aScrDisp -> i_init();
     iScrQuantPrepare();
 }
References aciBreathFlag, aciEndSpeech, aciEscaveDead, aciEscaveEmpty, aciSpeechBegLocked, aciSpeechEndLocked, aciSpeechStarted, aScrDisp, and iScrQuantPrepare().
Referenced by FirstEscaveRTO::Init(), and EscaveRTO::Init().
aci_SendEvent()
void aci_SendEvent (int cd, int dt = 0)
 {
     aScrDisp -> send_event(cd,dt);
 }
References aScrDisp.
Referenced by aciHandleSubmenuEvent(), dg_SendEvent(), aciML_Dispatcher::event_quant(), and aciML_Dispatcher::startup().
aci_setMatrixBorder()
void aci_setMatrixBorder (void)
 {
     int id,i,t,sz;
     XBuffer XBuf;
     iBitmapElement* p = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_MATRIX_BORDER_ID];
     if(!p) return;
     short sx,sy;
     if(aScrDisp -> curMatrix){
         id = aScrDisp -> curMatrix -> internalID;
         XBuf < "resource/actint/iscreen/matrix/mt";
         if(id < 10) XBuf < "0";
         XBuf <= id < ".bmp";
         XStream fh(XBuf.GetBuf(),XS_IN);
         fh > sx > sy;
         fh.read(p -> fdata,sx * sy);
         fh.close();
         sz = sx * sy;
         for(i = 0; i < sz; i ++){
             t = ((unsigned char*)p -> fdata)[i];
             if(t)
                 t += p -> bmp_null_level;
             else
                 t = HFONT_NULL_LEVEL;
             p -> fdata[i] = t;
         }
     }
     else {
         memset(p -> fdata,HFONT_NULL_LEVEL,p -> SizeX * p -> SizeY);
     }
 }
aci_setScMatrixBorder()
void aci_setScMatrixBorder (void)
 {
     XBuffer XBuf;
 //  if(!aScrDisp -> secondMatrix) return;
     iBitmapElement* p = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(!p) return;
     if(!aScrDisp -> secondMatrix){
         memset(p -> fdata,HFONT_NULL_LEVEL,p -> bSizeX * p -> bSizeY);
         return;
     }
     short sx,sy;
     int id = aScrDisp -> secondMatrix -> internalID;
     XBuf < "resource/actint/iscreen/matrix/mt";
     if(id < 10) XBuf < "0";
     XBuf <= id < ".bmp";
     XStream fh(XBuf.GetBuf(),XS_IN);
     fh > sx > sy;
     fh.read(p -> fdata,sx * sy);
     fh.close();
     int i,t,sz = sx * sy;
     for(i = 0; i < sz; i ++){
         t = ((unsigned char*)p -> fdata)[i];
         if(t)
             t += p -> bmp_null_level;
         else
             t = HFONT_NULL_LEVEL;
         p -> fdata[i] = t;
     }
 }
aciAcceptRubox()
void aciAcceptRubox (void)
 {
     aciML_D -> key_trap(AML_RUBOX_CODE,AML_KEY);
 }
References aciML_D, AML_KEY, and AML_RUBOX_CODE.
Referenced by dg_SendEvent().
aciActivateItemFunction()
void aciActivateItemFunction (int itemID, int fncID)
 {
     fncMenu* m = NULL;
     invItem* p = aScrDisp -> get_item(itemID);
     if(p && p -> menu){
         m = (fncMenu*)p -> menu;
         m -> activate_item(fncID + 2000);
     }
     if(m && m -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         m -> set_redraw();
 }
References aScrDisp, and NULL.
Referenced by addInfernalsKill2Protractor(), addSpectorsKill2Messiah(), and ActionDispatcher::Open().
aciAdd2Targets()
void aciAdd2Targets (char * p)
 {
     char* ptr;
     fncMenu* mn;
     fncMenuItem* itm;
     mn = aScrDisp -> get_menu(FMENU_TARGETS_MENU);
     if(!mn) return;
     itm = aScrDisp -> alloc_menu_item();
     itm -> init_name(p);
     itm -> font = FMENU_TARGETS_FONT;
     itm -> space = FMENU_TARGETS_SPACE;
     itm -> fnc_code = FMENU_OFF;
     itm -> init();
     mn -> add_item(itm);
     // rebuild...
     ptr = GetCompasTarget();
     if(ptr)
         mn -> curItem = mn -> get_obj(ptr);
     else
         mn -> curItem = mn -> get_obj(aciSTR_OFF);
     mn -> firstItem = mn -> curItem;
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aciSTR_OFF, aScrDisp, FMENU_OFF, FMENU_TARGETS_FONT, FMENU_TARGETS_MENU, FMENU_TARGETS_SPACE, GetCompasTarget(), and init_objects().
Referenced by CompasObject::AddTarget().
aciAddRubox()
void aciAddRubox (void)
 {
     uvsActInt* p;
     invItem* itm;
     listElem* el = (listElem*)GGamer;
     if(!aciPutItem(ACI_RUBOX,-1,-1)) ErrH.Abort("aciPutItem() failed...");
     itm = (invItem*)aScrDisp -> curMatrix -> items -> last;
     p = new uvsActInt;
     p -> type = ACI_RUBOX;
     itm -> uvsDataPtr = p;
     p -> pos_x = itm -> MatrixX;
     p -> pos_y = itm -> MatrixY;
     p -> link(el);
     GGamer = (uvsActInt*)el;
 }
References XErrorHandler::Abort(), ACI_RUBOX, aciPutItem(), aScrDisp, curMatrix, ErrH, and GGamer.
Referenced by dg_SendEvent().
aciAddTabutask()
void aciAddTabutask (int num)
 {
     invItem* p;
     uvsActInt* u;
     listElem* el = (listElem*)GItem;
     if(!(aScrDisp -> flags & AS_ISCREEN)) return;
     p = aScrDisp -> get_iitem(ACI_TABUTASK);
     if(p -> uvsDataPtr){
         u = (uvsActInt*)p -> uvsDataPtr;
     }
     else {
         u = new uvsActInt;
         u -> type = ACI_TABUTASK;
         p -> uvsDataPtr = u;
         u -> link(el);
         GItem = (uvsActInt*)el;
     }
     uvsTabuCreate(u,num);
     SOUND_DROP();
 }
References aScrDisp, and GItem.
aciAddTeleportMenuItem()
void aciAddTeleportMenuItem (int id, int fnc_id)
 {
     const char* ptr;
     fncMenu* mn;
     fncMenuItem* itm;
     invMatrix* m;
     mn = aScrDisp -> get_menu(FMENU_TELEPORT_MENU);
     if(!mn) return;
     if(id == -1){
         ptr = aci_curLocationName;
     }
     else {
         m = aScrDisp -> get_matrix(id);
         ptr = m -> mech_name;
     }
     itm = aScrDisp -> alloc_menu_item();
     itm -> init_name(ptr);
     itm -> font = FMENU_TARGETS_FONT;
     itm -> space = FMENU_TARGETS_SPACE;
     itm -> fnc_code = fnc_id;
     itm -> flags |= FM_RANGE_FONT;
     itm -> init();
     mn -> add_item(itm);
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aci_curLocationName, aScrDisp, FMENU_TARGETS_FONT, FMENU_TARGETS_SPACE, and FMENU_TELEPORT_MENU.
Referenced by ObjectDestroy(), and GameObjectDispatcher::Quant().
aciAskQuestion()
void aciAskQuestion (void)
 {
     char* str,*subj;
     fncMenuSet* m = aScrDisp -> qMenu;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p || !m) return;
     if(aciEscaveDead || aciEscaveEmpty) return;
     if(!(m -> flags & FMC_DATA_INIT)){
         str = dgD -> getQempty();
     }
     else {
         subj = m -> get();
         str = dgD -> getAnswer(subj);
     }
     if(str){
         p -> free_list();
         aciInitPanel(p,(unsigned char*)str);
         p -> set_redraw();
     }
     aciStartSpeech();
 }
References ACI_ANSWER_PANEL, aciEscaveDead, aciEscaveEmpty, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciAutoMoveItems()
void aciAutoMoveItems (void)
 {
     int i,x,y,sz;
     invItem* p,*p1;
     if(!aScrDisp -> curMatrix || !aScrDisp -> secondMatrix)
         return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     sz = aScrDisp -> curMatrix -> items -> Size;
     for(i = 0; i < sz; i ++){
         p1 = (invItem*)p -> prev;
         x = p -> MatrixX;
         y = p -> MatrixY;
         aScrDisp -> curMatrix -> remove_item(p);
         if(!aScrDisp -> secondMatrix -> auto_put_item(p)){
             aScrDisp -> curMatrix -> put_item(x,y,p);
         }
         else {
             ((uvsActInt*)p -> uvsDataPtr) -> pos_x = p -> MatrixX;
             ((uvsActInt*)p -> uvsDataPtr) -> pos_y = p -> MatrixY;
         }
         p = p1;
     }
     SOUND_DROP();
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
 }
References aScrDisp, curMatrix, prev, and SOUND_DROP.
Referenced by actIntDispatcher::EventQuant().
aciAutoSave()
void aciAutoSave (void)
 {
     if(NetworkON || aScrDisp -> curLocData -> WorldID == XPLO_ID) return;
     aciAutoSaveFlag = 1;
     acsSaveData();
 }
References aciAutoSaveFlag, acsSaveData(), aScrDisp, NetworkON, and XPLO_ID.
Referenced by aciShowLocation().
aciBuildQuestList()
void aciBuildQuestList (void)
 {
     int cd = 0;
     char* p;
     if(!aScrDisp -> qMenu) return;
     if(aciEscaveDead || aciEscaveEmpty) return;
     fncMenuItem* itm;
     fncMenu* m;
     p = dgD -> findQfirst();
     if(!p) return;
     aScrDisp -> qMenu -> finit();
     aScrDisp -> qMenu -> init();
     p = dgD -> getQprefix();
     if(p){
         m = new fncMenu;
         m -> flags |= FM_RANGE_FONT;
         itm = aScrDisp -> alloc_menu_item();
         itm -> init_name(p);
         itm -> fnc_code = 0;
         itm -> font = ACI_PHRASE_FONT;
         itm -> space = 1;
         itm -> init();
         m -> add_item(itm);
         aScrDisp -> qMenu -> add(m);
     }
     p = dgD -> findQfirst();
     if(p){
         m = new fncMenu;
         m -> flags |= FM_RANGE_FONT;
         while(p){
             itm = aScrDisp -> alloc_menu_item();
             itm -> init_name(p);
             itm -> fnc_code = cd;
             itm -> font = ACI_PHRASE_FONT;
             itm -> space = 1;
             itm -> init();
             m -> add_item(itm);
             cd ++;
             p = dgD -> findQnext();
         }
         aScrDisp -> qMenu -> add(m,1);
     }
     p = dgD -> getQpostfix();
     if(p){
         m = new fncMenu;
         m -> flags |= FM_RANGE_FONT;
         itm = aScrDisp -> alloc_menu_item();
         itm -> init_name(p);
         itm -> fnc_code = 0;
         itm -> font = ACI_PHRASE_FONT;
         itm -> space = 1;
         itm -> init();
         m -> add_item(itm);
         aScrDisp -> qMenu -> add(m);
     }
     aScrDisp -> qMenu -> init_redraw();
     aScrDisp -> qMenu -> build();
     aScrDisp -> qMenu -> set_redraw();
 }
References aciEscaveDead, aciEscaveEmpty, aScrDisp, and dgD.
Referenced by actIntDispatcher::EventQuant().
aciBuildShopList()
void aciBuildShopList (void)
 {
     int i;
     invItem* p;
     fncMenu* mn;
     invMatrix* m;
     fncMenuItem* itm;
     if(!iShopItem) return;
     mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(!mn) return;
     aScrDisp -> clear_menu(mn);
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
             m = (invMatrix*)aScrDisp -> i_matrixList -> first;
             for(i = 0; i < aScrDisp -> i_matrixList -> Size; i ++){
                 if(m -> uvsDataPtr){
                     if(m -> mech_name){
                         itm = aScrDisp -> alloc_menu_item();
                         itm -> init_name(m -> mech_name);
                         itm -> fnc_code = m -> type;
                         itm -> init();
                         mn -> add_item(itm);
                     }
                 }
                 m = (invMatrix*)m -> next;
             }
             mn -> curFunction = ((invMatrix*)iShopItem) -> type;
             iEvLineID = MECHOS_LIST_MODE;
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
             p = (invItem*)aScrDisp -> i_itemList -> first;
             for(i = 0; i < aScrDisp -> i_itemList -> Size; i ++){
                 if(p -> uvsDataPtr && p -> classID == AS_ITEM_CLASS){
                     if(p->ID_ptr.size()){
                         itm = aScrDisp -> alloc_menu_item();
                         itm -> init_name(p->ID_ptr.c_str());
                         itm -> fnc_code = p -> ID;
                         itm -> init();
                         mn -> add_item(itm);
                     }
                 }
                 p = (invItem*)p -> next;
             }
             mn -> curFunction = ((invItem*)iShopItem) -> ID;
             iEvLineID = ITEMS_LIST_MODE;
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
             p = (invItem*)aScrDisp -> i_itemList -> first;
             for(i = 0; i < aScrDisp -> i_itemList -> Size; i ++){
                 if(p -> uvsDataPtr && p -> classID == AS_WEAPON_CLASS){
                     if(p->ID_ptr.size()){
                         itm = aScrDisp -> alloc_menu_item();
                         itm -> init_name(p->ID_ptr.c_str());
                         itm -> fnc_code = p -> ID;
                         itm -> init();
                         mn -> add_item(itm);
                     }
                 }
                 p = (invItem*)p -> next;
             }
             mn -> curFunction = ((invItem*)iShopItem) -> ID;
             iEvLineID = WEAPONS_LIST_MODE;
             break;
     }
     mn -> set_redraw();
     mn -> flags |= FM_ACTIVE;
     mn -> init_objects();
     mn -> curItem = mn -> get_fnc_item(mn -> curFunction);
     if(!mn -> curItem)
         ErrH.Abort("Bad shop menu list...");
     if(mn -> VItems < mn -> items -> Size)
         mn -> firstItem = mn -> curItem;
     else
         mn -> firstItem = (fncMenuItem*)mn -> items -> first;
 }
References aScrDisp, iEvLineID, iShopItem, MECHOS_LIST_MODE, MECHOS_MODE, and SHOP_ITEMS_MENU_ID.
Referenced by aciInitShopList().
aciBuyItem()
void aciBuyItem (void)
 {
     int cr;
     invItem* p,*p1;
     invMatrix* m,*m1;
     uvsActInt* u,*u1;
     listElem* el;
     if(!(aScrDisp -> flags & AS_INV_MOVE_ITEM)){
         if(iShopItem){
             if(iEvLineID == MECHOS_MODE || iEvLineID == MECHOS_LIST_MODE){
                 m = (invMatrix*)iShopItem;
                 u = (uvsActInt*)m -> uvsDataPtr;
                 if(!u) ErrH.Abort("Bad shop item...");
                 u -> delink(GMechos);
                 if(aScrDisp -> curMatrix){
                     if(GGamerMechos){
                         el = GMechos;
                         //std::cout<<"GGamerMechos -> link(el)"<<std::endl;
                         GGamerMechos -> link(el);
                         GMechos = (uvsActInt*)el;
                     }
                     m1 = aScrDisp -> get_imatrix(aScrDisp -> curMatrix -> type);
                     if(!m1 -> uvsDataPtr) m1 -> uvsDataPtr = GGamerMechos;
                     iShopItem = (iListElement*)m1;
                 }
                 else {
                     aciNextShopItem();
                 }
                 //std::cout<<"aciBuyItem GGamerMechos = u"<<std::endl;
                 GGamerMechos = u;
                 cr = aciGetCurCredits();
                 cr -= u -> price;
                 aciUpdateCurCredits(cr);
                 u1 = aciGetMechos(m -> type);
                 if(u1)
                     m -> uvsDataPtr = u1;
                 else
                     m -> uvsDataPtr = NULL;
             }
             else {
                 if(aScrDisp -> flags & AS_INV_MOVE_ITEM) return;
                 p = (invItem*)iShopItem;
                 p1 = aScrDisp -> alloc_item();
                 p -> clone(p1);
                 aScrDisp -> curItem = p1;
                 set_mouse_cursor(p1 -> frame,p1 -> ScreenSizeX,p1 -> ScreenSizeY);
                 aScrDisp -> flags |= AS_INV_MOVE_ITEM;
                 el = (listElem*)GGamer;
                 u = (uvsActInt*)p -> uvsDataPtr;
                 if(!u) ErrH.Abort("Null uvsDataPtr...");
                 u -> delink(GItem);
                 u -> link(el);
                 GGamer = (uvsActInt*)el;
                 p1 -> uvsDataPtr = u;
                 p1 -> flags |= INV_ITEM_NO_PAY;
                 p1 -> flags |= INV_ITEM_NEW;
                 u -> pos_x = u -> pos_y = -1;
                 p1 -> MatrixX = p1 -> MatrixY = -1;
                 if(aScrDisp -> iscr_iP){
                     aciInitPricePanel(aScrDisp -> iscr_iP,(iListElement*)p1,ITEMS_MODE,1);
                     aScrDisp -> iscr_iP -> set_redraw();
                 }
                 u1 = aciGetShopItem(u -> type);
                 if(u1 && !aScrDisp -> curLocData -> ExcludeItems[u1 -> type]){
                     p -> uvsDataPtr = u1;
                 }
                 else {
                     p -> uvsDataPtr = NULL;
                     aciNextShopItem();
                 }
             }
         }
         aciInitAviID();
         if(iEvLineID == MECHOS_LIST_MODE || iEvLineID == ITEMS_LIST_MODE || iEvLineID == WEAPONS_LIST_MODE)
             aciBuildShopList();
     }
     else {
         aciSellMoveItem();
     }
 }
References aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciCHandler()
void aciCHandler (int key)
 {
     return;
     int code = 0,cr;
     if(NetworkON || key > 256 || key <= 0) return;
     if(aciTreeData) {
         code = aciTreeData -> quant(key);
     }
     switch(code << NetworkON){
         case ACI_ADD_BEEBOS:
             cr = aciGetCurCredits();
             cr += 50000;
             aciUpdateCurCredits(cr);
             if(!(aScrDisp -> flags & AS_ISCREEN))
                 SetWorldBeebos(cr);
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_ADD_LUCK:
             uvsChangeLuck();
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_ADD_DOMINANCE:
             uvsChangeDominance();
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_ADD_KEYS:
             aciOpenWorldLink(1,0);
             aciOpenWorldLink(1,3);
             aciOpenWorldLink(1,2);
             aciOpenWorldLink(1,4);
             aciOpenWorldLink(0,6);
             aciOpenWorldLink(3,8);
             aciOpenWorldLink(2,9);
             aciOpenWorldLink(2,5);
             aciOpenWorldLink(7,7);
             aciPrepareWorldsMenu();
             aciTreeData -> reset();
             SOUND_DROP();
             break;
         case ACI_COMPLETE_TABUTASK:
             aciCompleteTabutask();
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK01:
             aciAddTabutask(1);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK02:
             aciAddTabutask(2);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK03:
             aciAddTabutask(3);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK04:
             aciAddTabutask(4);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK05:
             aciAddTabutask(5);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK06:
             aciAddTabutask(6);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK07:
             aciAddTabutask(7);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK08:
             aciAddTabutask(8);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK09:
             aciAddTabutask(9);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK10:
             aciAddTabutask(10);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK11:
             aciAddTabutask(11);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK12:
             aciAddTabutask(12);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK13:
             aciAddTabutask(13);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK14:
             aciAddTabutask(14);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK15:
             aciAddTabutask(15);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK16:
             aciAddTabutask(16);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK17:
             aciAddTabutask(17);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK18:
             aciAddTabutask(18);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK19:
             aciAddTabutask(19);
             aciTreeData -> reset();
             break;
         case ACI_ADD_TABUTASK20:
             aciAddTabutask(20);
             aciTreeData -> reset();
             break;
         case ACI_TELEPORT_G:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,0);
             }
             break;
         case ACI_TELEPORT_F:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,1);
             }
             break;
         case ACI_TELEPORT_N:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,2);
             }
             break;
         case ACI_TELEPORT_X:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,3);
             }
             break;
         case ACI_TELEPORT_B:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,4);
             }
             break;
         case ACI_TELEPORT_K:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,6);
             }
             break;
         case ACI_TELEPORT_T:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,7);
             }
             break;
         case ACI_TELEPORT_H:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,8);
             }
             break;
         case ACI_TELEPORT_W:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,11);
             }
             break;
         case ACI_TELEPORT_A:
             if(!actIntLog){
                 SOUND_DROP();
                 aci_SendEvent(EV_TELEPORT,12);
             }
             break;
         case ACI_END_GAME0:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_INFERNAL_LOCKED);
             }
             break;
         case ACI_END_GAME1:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_SPOBS_LOCKED);
             }
             break;
         case ACI_END_GAME2:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_ALL_LOCKED);
             }
             break;
         case ACI_END_GAME3:
             if(!actIntLog){
                 SOUND_DROP();
                 XpeditionOFF(GAME_OVER_LUCKY);
             }
             break;
         case ACI_CHANGE_CYCLE:
             if(!actIntLog){
                 SOUND_DROP();
                 uvsChangeCycle();
             }
             break;
         case ACI_REPAIR:
             if(!actIntLog){
                 SOUND_DROP();
                 FakeOfMight();
             }
             break;
     }
 }
References ACI_ADD_BEEBOS, aciGetCurCredits(), aciTreeData, aciUpdateCurCredits(), aScrDisp, key(), and NetworkON.
Referenced by actIntDispatcher::iKeyTrap(), and actIntDispatcher::KeyQuant().
aciChange2Raffa()
void aciChange2Raffa (void)
 {
     invMatrix* m,*rf = NULL;
     uvsActInt* u,*u1;
     listElem* el;
     if(aScrDisp -> curMatrix) aciExpropriation();
     aScrDisp -> curMatrix = NULL;
     if(GGamerMechos){
         //std::cout<<"aciChange2Raffa if(GGamerMechos) "<<GGamerMechos<<std::endl;
         m = aScrDisp -> get_imatrix(GGamerMechos -> type);
         if(!m -> uvsDataPtr) {
             m -> uvsDataPtr = GGamerMechos;
         }
         //std::cout<<"aciChange2Raffa el = GMechos "<<GMechos<<std::endl;
         el = GMechos;
         GGamerMechos -> link(el);
         GMechos = (uvsActInt*)el;
         //std::cout<<"aciChange2Raffa GMechos = (uvsActInt*)el "<<GMechos<<std::endl;
     }
     GGamerMechos = NULL;
     m = (invMatrix*)aScrDisp -> i_matrixList -> last;
     while(m){
         //std::cout<<"aciChange2Raffa invMatrix type: "<<m->type<<std::endl;
         if(m -> flags & IM_RAFFA){
             if(m -> uvsDataPtr){
                 u = (uvsActInt*)m -> uvsDataPtr;
                 //std::cout<<"aciChange2Raffa GMechos "<<GMechos<<std::endl;
                 u -> delink(GMechos);
                 u->next = NULL;
                 u->prev = NULL;
                 if(((iListElement*)m) == iShopItem)
                     aciNextShopItem();
                 //std::cout<<"aciChange2Raffa GGamerMechos = u "<<u<<std::endl;
                 GGamerMechos = u;
                 u1 = aciGetMechos(m -> type);
                 if(u1)
                     m -> uvsDataPtr = u1;
                 else
                     m -> uvsDataPtr = NULL;
                 aScrDisp -> curMatrix = aScrDisp -> alloc_matrix(m -> type,1);
                 aScrDisp -> curMatrix -> uvsDataPtr = u;
                 return;
             } else {
                 rf = m;
             }
         }
         m = (invMatrix*)m -> prev;
     }
     if(!rf)
         ErrH.Abort("Free mechos not found...");
     m = rf;
     u = new uvsActInt;
     u -> type = m -> type;
     u -> price = u -> sell_price = 1;
     if(((iListElement*)m) == iShopItem)
         aciNextShopItem();
     //std::cout<<"aciChange2Raffa2 GGamerMechos = u"<<std::endl;
     GGamerMechos = u;
     u1 = aciGetMechos(m -> type);
     if(u1)
         m -> uvsDataPtr = u1;
     else
         m -> uvsDataPtr = NULL;
     aScrDisp -> curMatrix = aScrDisp -> alloc_matrix(m -> type,1);
     aScrDisp -> curMatrix -> uvsDataPtr = u;
 }
References aciExpropriation(), aScrDisp, curMatrix, GGamerMechos, GMechos, and NULL.
Referenced by dg_SendEvent().
aciChangeAviIndex()
void aciChangeAviIndex (void)
 {
     switch(aciCurAviIndex){
         case ACI_PICTURE_AVI_ENG:
             aciCurAviIndex = (lang() == RUSSIAN) ? ACI_TEXT_AVI_RUS : ACI_TEXT_AVI_ENG;
             break;
         case ACI_TEXT_AVI_RUS:
         case ACI_TEXT_AVI_ENG:
             aciCurAviIndex = ACI_PICTURE_AVI_ENG;
             break;
     }
     aciInitAviID();
 }
References ACI_PICTURE_AVI_ENG, ACI_TEXT_AVI_ENG, ACI_TEXT_AVI_RUS, aciCurAviIndex, aciInitAviID(), lang(), and RUSSIAN.
Referenced by actIntDispatcher::EventQuant().
aciChangeItem()
void aciChangeItem (actintItemData * p)
 {
     invItem* p1,*it;
     if(!aScrDisp -> curMatrix) return;
     if(!(aScrDisp -> flags & AS_ISCREEN))
         it = aScrDisp -> get_item(p -> type);
     else
         it = aScrDisp -> get_iitem(p -> type);
     p1 = (invItem*)p -> actintOwner;
     it -> clone(p1);
     if(!(aScrDisp -> flags & AS_ISCREEN) && aScrDisp -> curMode == AS_INV_MODE)
         aScrDisp -> curMatrix -> set_redraw();
 }
References aScrDisp, and curMatrix.
Referenced by aciSendEvent2itmdsp(), ChangeItemData(), ChangeTabutaskItem(), ChargeDevice(), VangerUnit::CheckOutDevice(), GunDevice::DeviceQuant(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), and uvsapiDestroyItem().
aciChangeLineID()
void aciChangeLineID (void)
 {
     switch(iEvLineID){
         case CHANGE_2_MECHOS_MODE:
             iEvLineID = MECHOS_MODE;
             break;
         case CHANGE_2_WEAPONS_MODE:
             iEvLineID = WEAPONS_MODE;
             break;
         case CHANGE_2_ITEMS_MODE:
             iEvLineID = ITEMS_MODE;
             break;
         case MECHOS_LIST_MODE:
             iEvLineID = MECHOS_MODE;
             break;
         case ITEMS_LIST_MODE:
             iEvLineID = ITEMS_MODE;
             break;
         case WEAPONS_LIST_MODE:
             iEvLineID = WEAPONS_MODE;
             break;
     }
 }
References CHANGE_2_ITEMS_MODE, CHANGE_2_MECHOS_MODE, CHANGE_2_WEAPONS_MODE, iEvLineID, ITEMS_LIST_MODE, ITEMS_MODE, MECHOS_LIST_MODE, MECHOS_MODE, WEAPONS_LIST_MODE, and WEAPONS_MODE.
aciChangeList()
void aciChangeList (void)
 {
     invItem* p,*fp;
     invMatrix* m,*fm;
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
             fm = m = (invMatrix*)aScrDisp -> i_matrixList -> first;
             while(!m -> uvsDataPtr){
                 m = (invMatrix*)m -> next;
                 if(m == fm) break;
             }
             if(!m -> uvsDataPtr){
                 iShopItem = NULL;
             }
             else {
                 iShopItem = (iListElement*)m;
                 aciCurMechosID = m -> type;
             }
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
             fp = p = (invItem*)aScrDisp -> i_itemList -> first;
             while(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS){
                 p = (invItem*)p -> next;
                 if(p == fp) break;
             }
             if(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS)
                 iShopItem = NULL;
             else
                 iShopItem = (iListElement*)p;
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
             fp = p = (invItem*)aScrDisp -> i_itemList -> first;
             while(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS){
                 p = (invItem*)p -> next;
                 if(p == fp) break;
             }
             if(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS)
                 iShopItem = NULL;
             else
                 iShopItem = (iListElement*)p;
             break;
     }
     aciInitAviID();
     if(iEvLineID == MECHOS_LIST_MODE || iEvLineID == ITEMS_LIST_MODE || iEvLineID == WEAPONS_LIST_MODE)
         aciBuildShopList();
 }
References aScrDisp, iEvLineID, MECHOS_LIST_MODE, and MECHOS_MODE.
Referenced by aciNextShopItem(), aciPrevShopItem(), aciSetShopItem(), and actIntDispatcher::EventQuant().
aciChangeWorld()
void aciChangeWorld (int w_id)
 {
     int i,cur_id,fl = 0;
     aciWorldInfo* p,*p1;
     if(w_id == -1) return;
     cur_id = aScrDisp -> wMap -> world_ids[w_id];
     if(cur_id == -1) return;
     p = aScrDisp -> wMap -> world_ptr[cur_id];
     if(!p) return;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p1 = aScrDisp -> wMap -> world_ptr[i];
         if(p1){
             if(p1 -> flags & AS_ACCESSIBLE_WORLD){
                 p1 -> flags &= ~AS_ACCESSIBLE_WORLD;
                 fl = 1;
             }
             if(p1 -> flags & AS_CURRENT_WORLD){
                 p1 -> flags &= ~AS_CURRENT_WORLD;
                 p1 -> flags |= AS_VISIBLE_WORLD;
             }
         }
     }
     if(fl){
         for(i = 0; i < AS_MAX_WORLD; i ++){
             p1 = aScrDisp -> wMap -> world_ptr[i];
             if(i != cur_id && p1){
                 if(p1 -> links[cur_id] || p -> links[i]){
                     p1 -> flags |= AS_ACCESSIBLE_WORLD;
                 }
             }
         }
     }
     p -> flags |= AS_CURRENT_WORLD;
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
 }
References AS_MAX_WORLD, aScrDisp, and wMap.
Referenced by actIntDispatcher::i_finit(), and load_map_bmp().
aciCheckCredits()
int aciCheckCredits (void)
 {
     invItem* p;
     invMatrix* m;
     uvsActInt* u;
     int cr = aciGetCurCredits();
     if(iEvLineID == MECHOS_MODE || iEvLineID == MECHOS_LIST_MODE){
         m = (invMatrix*)iShopItem;
         u = (uvsActInt*)m -> uvsDataPtr;
         if(m -> flags & IM_NOT_COMPLETE) return 0;
     }
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> partData) return 1;
         if(!((uvsActInt*)aScrDisp -> curItem -> uvsDataPtr) -> sell_price) return 0;
         return 1;
     }
     if(iEvLineID == EMPTY_MODE)
         return 0;
     if(iEvLineID == MECHOS_MODE || iEvLineID == MECHOS_LIST_MODE){
         if(u -> price > cr + aciGetCurMatrixPrice()) return 0;
     }
     else {
         p = (invItem*)iShopItem;
         u = (uvsActInt*)p -> uvsDataPtr;
         if(u -> price > cr) return 0;
     }
     return 1;
 }
References aciGetCurCredits(), iEvLineID, iShopItem, MECHOS_LIST_MODE, and MECHOS_MODE.
aciCheckItemCredits()
int aciCheckItemCredits (void)
 {
     int cr = aciGetCurCredits();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(((uvsActInt*)aScrDisp -> curItem -> uvsDataPtr) -> price > cr) return 0;
         return 1;
     }
     return 0;
 }
References aciGetCurCredits(), and aScrDisp.
Referenced by actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_quant_l(), and actIntDispatcher::inv_mouse_quant_r().
aciCheckItemPickUp()
int aciCheckItemPickUp (actintItemData * p)
 {
     invItem* itm = aScrDisp -> get_item(p -> type);
     if((itm -> classID == AS_ITEM_CLASS && aciPickupItems) || (itm -> classID == AS_WEAPON_CLASS && aciPickupDevices))
         return 1;
     return 0;
 }
References aciPickupDevices, aciPickupItems, AS_ITEM_CLASS, AS_WEAPON_CLASS, and aScrDisp.
Referenced by VangerUnit::CheckInDevice().
aciCheckSellItem()
int aciCheckSellItem (void)
 {
     int x = iMouseX;
     iScreenObject* p;
     iAVIElement* el = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(!el) return 0;
     p = (iScreenObject*)el -> owner;
     if(p -> owner) x += ((iScreen*)p -> owner) -> ScreenOffs;
     if(p -> CheckXY(x,iMouseY)) return 1;
     return 0;
 }
References ACI_MECHOS_AVI_ID, aScrDisp, iMouseX, and iMouseY.
aciCheckSlot()
int aciCheckSlot (void)
 {
     if(!aScrDisp -> curMatrix) return 0;
     return aScrDisp -> curMatrix -> check_slot(AS_DEVICE_SLOT);
 }
References AS_DEVICE_SLOT, aScrDisp, and curMatrix.
aciChooseShopItem()
void aciChooseShopItem (void)
 {
     int x,y,id;
     invItem* p;
     invMatrix* m;
     fncMenu* mn;
     fncMenuItem* itm;
     mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(!mn) return;
     itm = mn -> curItem;
     x = iMouseX;
     y = iMouseY;
     if(!mn -> check_xy(x,y)) return;
     if(mn -> change(x,y)){
         switch(iEvLineID){
             case MECHOS_LIST_MODE:
                 m = aScrDisp -> get_imatrix(mn -> curFunction);
                 iShopItem = (iListElement*)m;
                 aciInitAviID();
                 aciInitShopAvi();
                 mn -> flags &= ~FM_ACTIVE;
                 break;
             case ITEMS_LIST_MODE:
                 p = aScrDisp -> get_iitem(mn -> curFunction);
                 iShopItem = (iListElement*)p;
                 aciInitAviID();
                 aciInitShopAvi();
                 mn -> flags &= ~FM_ACTIVE;
                 break;
             case WEAPONS_LIST_MODE:
                 p = aScrDisp -> get_iitem(mn -> curFunction);
                 iShopItem = (iListElement*)p;
                 aciInitAviID();
                 aciInitShopAvi();
                 mn -> flags &= ~FM_ACTIVE;
                 break;
         }
     }
     else {
         if(iEvLineID == MECHOS_LIST_MODE || iEvLineID == MECHOS_MODE){
             id = ((invMatrix*)iShopItem) -> type;
             if(id != mn -> curFunction){
                 aciSetShopItem(mn -> curFunction);
                 iScrDisp -> end_event();
             }
         }
         else {
             id = ((invItem*)iShopItem) -> ID;
             if(id != mn -> curFunction){
                 aciSetShopItem(mn -> curFunction);
                 iScrDisp -> end_event();
             }
         }
         aciInitAviID();
         aciInitShopAvi();
         if(itm == mn -> curItem)
             mn -> flags &= ~FM_ACTIVE;
     }
 }
References aciInitAviID(), aciInitShopAvi(), aScrDisp, iEvLineID, iMouseX, iMouseY, iShopItem, MECHOS_LIST_MODE, and SHOP_ITEMS_MENU_ID.
Referenced by actIntDispatcher::EventQuant().
aciClearQuestMenu()
void aciClearQuestMenu (void)
 {
     fncMenuSet* m;
     m = aScrDisp -> qMenu;
     if(m && m -> flags & FMC_DATA_INIT){
         m -> finit();
         m -> redraw();
         m -> redraw_owner();
     }
 }
References aScrDisp.
Referenced by aciNextPhrase(), and dg_SendEvent().
aciClearTeleportMenu()
void aciClearTeleportMenu (void)
 {
     fncMenu* mn;
     fncMenuItem* p,*p1;
     mn = aScrDisp -> get_menu(FMENU_TELEPORT_MENU);
     if(!mn) return;
     p = (fncMenuItem*)mn -> items -> last;
     while(p){
         p1 = (fncMenuItem*)p -> prev;
         if(p -> fnc_code != FMENU_OFF){
             mn -> items -> dconnect((iListElement*)p);
             aScrDisp -> free_menu_item(p);
         }
         p = p1;
     }
     p = (fncMenuItem*)mn -> inactive_items -> last;
     while(p){
         p1 = (fncMenuItem*)p -> prev;
         if(p -> fnc_code != FMENU_OFF){
             mn -> inactive_items -> dconnect((iListElement*)p);
             aScrDisp -> free_menu_item(p);
         }
         p = p1;
     }
     mn -> prefix = NULL;
     mn -> postfix = NULL;
 }
References aScrDisp, FMENU_OFF, FMENU_TELEPORT_MENU, NULL, and prev.
Referenced by GeneralSystemClose(), and ObjectDestroy().
aciCloseGate()
void aciCloseGate (void)
 {
     int i,timer,max_timer = 0;
     _iSTORE_OFFS_;
     unsigned char* fon_buf;
 #ifdef _ACI_NO_SHOP_ANIMATION_
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     return;
 #endif
     SOUND_GATE();
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer){
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         return;
     }
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_CLOSE);
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < max_timer; i ++)
             timer += aScrDisp -> curLocData -> GateShutters[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < max_timer; i ++)
             aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> freeData();
     }
     delete[] fon_buf;
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_SHUTTER_CLOSE, aScrDisp, i_get_scrfon(), i_put_scrfon(), Redraw, SOUND_GATE, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseVisible, and xtClearMessageQueue().
aciCloseShopMenu()
void aciCloseShopMenu (void)
 {
     fncMenu* mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(mn)
         mn -> flags &= ~FM_ACTIVE;
 }
References aScrDisp, and SHOP_ITEMS_MENU_ID.
Referenced by aciInitShopList().
aciCompleteTabutask()
void aciCompleteTabutask (void)
 {
     invItem* p;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         if(p -> ID == ACI_TABUTASK){
             if(aScrDisp -> flags & AS_ISCREEN){
                 if(p -> uvsDataPtr)
                     uvsTabuComplete(((uvsActInt*)p -> uvsDataPtr) -> param2);
             }
             else {
                 if(p -> item_ptr)
                 uvsTabuComplete(p -> item_ptr -> data1);
             }
             SOUND_DROP();
             return;
         }
         p = (invItem*)p -> prev;
     }
 }
References ACI_TABUTASK, aScrDisp, and curMatrix.
aciDeactivateItemFunction()
void aciDeactivateItemFunction (int itemID, int fncID)
 {
     fncMenu* m = NULL;
     invItem* p = aScrDisp -> get_item(itemID);
     if(p && p -> menu){
         m = (fncMenu*)p -> menu;
         m -> deactivate_item(fncID + 2000);
     }
     if(m && m -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         m -> set_redraw();
 }
References aScrDisp, and NULL.
Referenced by ActionDispatcher::Open().
aciDeleteFromTargets()
void aciDeleteFromTargets (char * p)
 {
     char* ptr;
     fncMenu* mn;
     fncMenuItem* itm;
     mn = aScrDisp -> get_menu(FMENU_TARGETS_MENU);
     if(!mn) return;
     itm = mn -> get_obj(p);
     if(itm == mn -> curItem)
         SelectCompasTarget(NULL);
     if(itm){
         mn -> delete_obj(itm);
         aScrDisp -> free_menu_item(itm);
     }
     // rebuild...
     ptr = GetCompasTarget();
     if(ptr)
         mn -> curItem = mn -> get_obj(ptr);
     else
         mn -> curItem = mn -> get_obj(aciSTR_OFF);
     mn -> firstItem = mn -> curItem;
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aciSTR_OFF, aScrDisp, FMENU_TARGETS_MENU, GetCompasTarget(), init_objects(), NULL, and SelectCompasTarget().
Referenced by CompasObject::DeleteTarget().
aciDeleteTeleportMenuItem()
void aciDeleteTeleportMenuItem (int fnc_id)
 {
     fncMenu* m = aScrDisp -> get_menu(FMENU_TELEPORT_MENU);
     if(!m) return;
     m -> deactivate_item(fnc_id);
     if(m -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         m -> set_redraw();
 }
References aScrDisp, and FMENU_TELEPORT_MENU.
aciDisableParametersMenu()
void aciDisableParametersMenu (void)
 {
     fncMenu* m = (fncMenu*)aScrDisp -> menuList -> last;
     while(m){
         if(m -> flags & FM_MAIN_MENU)
             m -> delete_item(FMENU_PARAMETERS);
         m = (fncMenu*)m -> prev;
     }
 }
References aScrDisp.
aciDropMoveItem()
void aciDropMoveItem (void)
 {
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aciSendEvent2itmdsp(ACI_DROP_ITEM,aScrDisp -> curItem -> item_ptr);
         aScrDisp -> flags &= ~AS_INV_MOVE_ITEM;
         aScrDisp -> free_item(aScrDisp -> curItem);
     }
 }
References aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::Go2Universe(), and VangerUnit::OutCarNator().
aciEscaveKickOut()
void aciEscaveKickOut (void)
 {
     char* str;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p) return;
     str = dgD -> getQout();
     if(str){
         p -> free_list();
         aciInitPanel(p,(unsigned char*)str);
         p -> set_redraw();
     }
     aciStartSpeech();
 }
References ACI_ANSWER_PANEL, aciInitPanel(), aciStartSpeech(), aScrDisp, and dgD.
Referenced by dg_SendEvent().
aciExitShop()
void aciExitShop (void)
 {
     iScrDisp -> ret_val = 1;
     iScrDisp -> flags |= SD_EXIT;
 }
References iScrDisp.
Referenced by aciML_Dispatcher::event_quant().
aciExpropriation()
void aciExpropriation (void)
 {
     if(!aScrDisp -> curMatrix) return;
     invItem* itm = (invItem*)aScrDisp -> curMatrix -> items -> last,*itm1;
     uvsActInt* ptr = (uvsActInt*)aScrDisp -> curMatrix -> uvsDataPtr;
     if(!ptr) ErrH.Abort("Bad sell mechos...");
     while(itm){
         itm1 = (invItem*)itm -> prev;
         aScrDisp -> curMatrix -> remove_item(itm);
         itm -> flags |= INV_ITEM_NO_PAY;
         aciSell_Item(itm);
         itm = itm1;
     }
 }
References XErrorHandler::Abort(), aScrDisp, curMatrix, ErrH, and prev.
Referenced by aciChange2Raffa(), and dg_SendEvent().
aciFreeAll()
void aciFreeAll (void)
 {
     delete aScrDisp;
     aScrDisp = NULL;
     delete acsScrD;
     acsScrD = NULL;
     free_cell_frame();
     if(aIndArrowBML)
         delete aIndArrowBML;
     if(aIndDataBML)
         delete aIndDataBML;
     if(aIndBackBML)
         delete aIndBackBML;
     aIndArrowBML = NULL;
     aIndDataBML = NULL;
     aIndBackBML = NULL;
     aciLoadLog = 0;
 }
References aciLoadLog, acsScrD, aIndArrowBML, aIndBackBML, aIndDataBML, aScrDisp, free_cell_frame(), and NULL.
Referenced by LoadingRTO3::Init().
aciFreeUVS()
void aciFreeUVS (void)
 {
     //std::cout<<"aciFreeUVSList(GItem)"<<std::endl;
     if(GItem) aciFreeUVSList(GItem);
     //std::cout<<"aciFreeUVSList(GMechos)"<<std::endl;
     if(GMechos) aciFreeUVSList(GMechos);
     //std::cout<<"aciFreeUVSList(GGamer)"<<std::endl;
     if(GGamer) aciFreeUVSList(GGamer);
     //std::cout<<"aciFreeUVSList(GGamerMechos)"<<std::endl;
     if(GGamerMechos) aciFreeUVSList(GGamerMechos);
     //std::cout<<"aciFreeUVSList(GCharItem)"<<std::endl;
     if(GCharItem) aciFreeUVSList(GCharItem);
     //std::cout<<"aciFreeUVSList(GTreasureItem)"<<std::endl;
     if(GTreasureItem) aciFreeUVSList(GTreasureItem);
     GItem = NULL;
     GMechos = NULL;
     GGamer = NULL;
     GGamerMechos = NULL;
     GCharItem = NULL;
     GTreasureItem = NULL;
 }
References aciFreeUVSList(), GCharItem, GGamer, GGamerMechos, GItem, GMechos, GTreasureItem, and NULL.
Referenced by LoadingRTO3::Init().
aciFreeUVSList()
void aciFreeUVSList (uvsActInt * p)
 {
     uvsActInt* ptr,*ptr1;
     ptr = p;
     while(ptr){
         ptr1 = (uvsActInt*)ptr -> next;
         //std::cout<<"aciFreeUVSList "<<ptr<<" type:"<<ptr->type<<std::endl;
         delete ptr;
         ptr = ptr1;
     }
 }
Referenced by aciFreeUVS().
aciGetCurCycle()
int aciGetCurCycle (void)
 {
 #ifdef _ACI_ESCAVE_DEBUG_
     return 1;
 #else
     return uvsCurrentCycle;
 #endif
 }
References uvsCurrentCycle.
Referenced by ToolzerQuant().
aciGetCurMatrixPrice()
int aciGetCurMatrixPrice (void)
 {
     int price = 0;
 //    invItem* p;
     uvsActInt* u;
     if(!aScrDisp -> curMatrix) return 0;
     u = (uvsActInt*)aScrDisp -> curMatrix -> uvsDataPtr;
     if(!u) ErrH.Abort("Bad CurMatrix...");
     price += u -> sell_price;
 /*
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         u = (uvsActInt*)p -> uvsDataPtr;
         if(!u) ErrH.Abort("Bad CurMatrix item...");
         price += u -> price;
         p = (invItem*)p -> prev;
     }
 */
     return price;
 }
References XErrorHandler::Abort(), aScrDisp, curMatrix, and ErrH.
Referenced by actIntDispatcher::inv_mouse_imove_quant().
aciGetEleech()
void aciGetEleech (void)
 {
     listElem* el;
     uvsActInt* u;
     invItem* p,*p1;
     if(!GCharItem) return;
     u = GCharItem;
     p = aScrDisp -> get_iitem(u -> type);
     p1 = aScrDisp -> alloc_item();
     p -> clone(p1);
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         aciSell_Item(aScrDisp -> curItem);
         aScrDisp -> curItem = NULL;
     }
     aScrDisp -> flags |= AS_INV_MOVE_ITEM;
     aScrDisp -> curItem = p1;
     set_mouse_cursor(p1 -> frame,p1 -> ScreenSizeX,p1 -> ScreenSizeY);
     el = (listElem*)GGamer;
     u -> link(el);
     GGamer = (uvsActInt*)el;
     p1 -> uvsDataPtr = u;
     GCharItem = NULL;
 }
References aScrDisp, and GCharItem.
Referenced by actIntDispatcher::EventQuant().
aciGetGamerItem()
uvsActInt* aciGetGamerItem (int id)
 {
     uvsActInt* p = GGamer;
     while(p){
         if(p -> type == id)
             return p;
         p = (uvsActInt*)p -> next;
     }
     return NULL;
 }
References GGamer.
aciGetItemCoords() [1/2]
void aciGetItemCoords (actintItemData * p, int & x, int & y)
 {
     invItem* itm = (invItem*)p -> actintOwner;
     x = itm -> MatrixX;
     y = itm -> MatrixY;
 }
Referenced by VangerUnit::Go2Universe(), and VangerUnit::OutCarNator().
aciGetItemCoords() [2/2]
void aciGetItemCoords (int id, int & x, int & y)
 {
     invItem* itm;
     if(!aScrDisp -> curMatrix) return;
     itm = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(itm){
         if(itm -> ID == id){
             x = itm -> MatrixX;
             y = itm -> MatrixY;
             return;
         }
         itm = (invItem*)itm -> prev;
     }
 }
References aScrDisp, curMatrix, and prev.
aciGetItemEscave()
char * aciGetItemEscave (int p2)
 {
     int id;
     aciLocationInfo* locData;
     char* ptr = uvsGetNameByID(p2 & 0x0000FFFF,id);
     id = aScrDisp -> get_locdata_id(ptr);
     locData = aScrDisp -> get_locdata(id);
     if(locData)
         return locData -> nameID2;
     else
         return NULL;//NEED SEE!!! ""
 }
References aScrDisp, locData, NULL, and uvsGetNameByID().
aciGetItemLoad()
char* aciGetItemLoad (invItem * p, int mode)
 {
     char* ptr;
     aciXConv -> init();
     if(p -> pTemplate){
         switch(mode){
             case 0:
                 if(p -> flags & INV_ITEM_SHOW_ESCAVE){
                     if(p -> item_ptr)
                         sprintf(aciXConv -> address(),p -> pTemplate,aciGetItemEscave(p -> item_ptr -> data1));
                 }
                 else {
                     if(p -> item_ptr)
                         sprintf(aciXConv -> address(),p -> pTemplate,p -> item_ptr -> data1);
                 }
                 break;
             case 1:
                 if(p -> flags & INV_ITEM_SHOW_ESCAVE){
                     if(p -> uvsDataPtr)
                         sprintf(aciXConv -> address(),p -> pTemplate,aciGetItemEscave(((uvsActInt*)p -> uvsDataPtr) -> param2));
                 }
                 else {
                     if(p -> uvsDataPtr)
                         sprintf(aciXConv -> address(),p -> pTemplate,((uvsActInt*)p -> uvsDataPtr) -> param2);
                 }
                 break;
         }
     }
     ptr = aciXConv -> address();
     return ptr;
 }
References aciXConv.
Referenced by actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::put_in_slot(), and actIntDispatcher::set_move_item().
aciGetLast()
actintItemData* aciGetLast (void)
 {
     invItem* itm;
     invItem* p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     itm = p;
     while(p){
         if(p -> dropCount > itm -> dropCount)
             itm = p;
         p = (invItem*)p -> prev;
     }
     if(itm)
         return itm -> item_ptr;
     return NULL;
 }
References aScrDisp, curMatrix, NULL, and prev.
Referenced by VangerUnit::ItemQuant().
aciGetMechos()
uvsActInt* aciGetMechos (int id)
 {
     uvsActInt* p = GMechos;
     while(p){
         if(p -> type == id)
             return p;
         p = (uvsActInt*)p -> next;
     }
     return NULL;
 }
References GMechos.
aciGetPlayerColor()
int aciGetPlayerColor (void)
 {
     return iGetOptionValue(iPLAYER_COLOR);
 }
References iGetOptionValue(), and iPLAYER_COLOR.
Referenced by VangerUnit::CreateVangerUnit(), and NetInit().
aciGetPlayerName()
char* aciGetPlayerName (void)
 {
     return iGetOptionValueCHR(iPLAYER_NAME2);
 }
References iGetOptionValueCHR(), and iPLAYER_NAME2.
Referenced by NetInit().
aciGetPlayerPassword()
char* aciGetPlayerPassword (void)
 {
     return iGetOptionValueCHR(iPLAYER_PASSWORD);
 }
References iGetOptionValueCHR(), and iPLAYER_PASSWORD.
Referenced by NetInit().
aciGetPrice()
char* aciGetPrice (iListElement * p, int mode, int sell_mode)
 {
     char* ptr;
     invItem* it;
     invMatrix* m;
     uvsActInt* u;
     if(mode == MECHOS_MODE){
         m = (invMatrix*)p;
         u = (uvsActInt*)m -> uvsDataPtr;
     }
     else {
         it = (invItem*)p;
         u = (uvsActInt*)it -> uvsDataPtr;
     }
     aciXConv -> init();
     if(!u){
         *aciXConv < aciSTR_UNDEFINED_PRICE;
         return aciXConv -> address();
     }
     *aciXConv < aciSTR_PRICE;
     if(sell_mode)
         *aciXConv <= u -> sell_price < " $";
     else
         *aciXConv <= u -> price < " $";
     ptr = aciXConv -> address();
     return ptr;
 }
References aciSTR_PRICE, aciSTR_UNDEFINED_PRICE, aciXConv, and MECHOS_MODE.
Referenced by aciInitMechosInfo(), actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_imove_quant(), and actIntDispatcher::set_move_item().
aciGetRubox()
void aciGetRubox (void)
 {
     uvsActInt* p;
     invItem* itm;
     listElem* el = (listElem*)GGamer;
     if(!aciPutItem(ACI_RUBOX,-1,-1)) ErrH.Abort("aciPutItem() failed...");
     itm = (invItem*)aScrDisp -> curMatrix -> items -> last;
     aScrDisp -> curMatrix -> remove_item(itm);
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         aciSell_Item(aScrDisp -> curItem);
         aScrDisp -> curItem = NULL;
     }
     aScrDisp -> flags |= AS_INV_MOVE_ITEM;
     aScrDisp -> curItem = itm;
     set_mouse_cursor(itm -> frame,itm -> ScreenSizeX,itm -> ScreenSizeY);
     p = new uvsActInt;
     p -> type = ACI_RUBOX;
     itm -> uvsDataPtr = p;
     p -> link(el);
     GGamer = (uvsActInt*)el;
 }
References XErrorHandler::Abort(), ACI_RUBOX, aciPutItem(), aScrDisp, curMatrix, ErrH, and GGamer.
Referenced by actIntDispatcher::EventQuant().
aciGetShopItem()
uvsActInt* aciGetShopItem (int id)
 {
     uvsActInt* p = GItem;
     while(p){
         if(p -> type == id)
             return p;
         p = (uvsActInt*)p -> next;
     }
     return NULL;
 }
References GItem.
aciHandleCameraEvent()
void aciHandleCameraEvent (int code, int data)
 {
     aciBitmapMenu* m;
     aciBitmapMenuItem* p;
     switch(code){
         case BMENU_ITEM_ROT:
             camera_rotate_enable = data;
             iScrOpt[iCAMERA_TURN]->SetValueINT(data);
             if(RAM16 && data){
                 camera_moving_xy_enable = camera_moving_z_enable = 0;
                 camera_slope_enable = 0;
             }
             break;
         case BMENU_ITEM_ZOOM:
             camera_moving_xy_enable = camera_moving_z_enable = data;
             iScrOpt[iCAMERA_SCALE]->SetValueINT(data);
             if(RAM16 && data){
                 camera_rotate_enable = 0;
                 camera_slope_enable = 0;
             }
             break;
         case BMENU_ITEM_PERSP:
             camera_slope_enable = data;
             iScrOpt[iCAMERA_SLOPE]->SetValueINT(data);
             if(RAM16 && data){
                 camera_moving_xy_enable = camera_moving_z_enable = 0;
                 camera_rotate_enable = 0;
             }
             break;
     }
     if(RAM16 && data){
         m = aScrDisp -> get_bmenu(BMENU_CAMERAS_MENU);
         if(m){
             p = (aciBitmapMenuItem*)m -> items -> last;
             while(p){
                 if(p -> ID != code) p -> curState = 0;
                 p = (aciBitmapMenuItem*)p -> prev;
             }
         }
     }
     iSaveData();
 }
References aScrDisp, BMENU_CAMERAS_MENU, BMENU_ITEM_PERSP, BMENU_ITEM_ROT, BMENU_ITEM_ZOOM, camera_moving_xy_enable, camera_moving_z_enable, camera_rotate_enable, camera_slope_enable, iCAMERA_SCALE, iCAMERA_SLOPE, iCAMERA_TURN, iSaveData(), iScrOpt, prev, RAM16, and iScreenOption::SetValueINT().
Referenced by aciBitmapMenu::change().
aciHandleSubmenuEvent()
void aciHandleSubmenuEvent (int id, fncMenuItem * p)
 {
     if(p -> eventPtr){
         aci_SendEvent(p -> eventPtr -> code,p -> eventPtr -> data);
         return;
     }
     switch(id){
         case FMENU_TARGETS_MENU:
             if(strcmp(p -> name,aciSTR_OFF)){
                 SelectCompasTarget(p -> name);
             }
             else {
                 SelectCompasTarget(NULL);
             }
             break;
         case FMENU_TELEPORT_MENU:
             aciTeleportEvent = p -> fnc_code;
             break;
     }
 }
References aci_SendEvent(), aciSTR_OFF, aciTeleportEvent, FMENU_TARGETS_MENU, FMENU_TELEPORT_MENU, NULL, and SelectCompasTarget().
Referenced by fncMenu::change().
aciInitAviID()
void aciInitAviID (void)
 {
     invItem* p;
     invMatrix* m;
     iAVIElement* avi;
     InfoPanel* ip = aScrDisp -> get_info_panel(ACI_PRICE_PANEL);
     avi = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(!avi) return;
     if(ip){
         ip -> free_list();
         ip -> set_redraw();
     }
     if(!iShopItem){
         aciXConv -> init();
         *aciXConv < iVideoPath < "empty.avi";
         strcpy(avi -> avi_name,aciXConv -> address());
         iEvLineID = EMPTY_MODE;
         return;
     }
     if(iEvLineID == MECHOS_MODE || iEvLineID == MECHOS_LIST_MODE || iEvLineID == CHANGE_2_MECHOS_MODE){
         m = (invMatrix*)iShopItem;
         aci_SecondMatrixID = m -> type;
         if(!aciCurAviIndex){
             if(m -> avi_ids && m -> avi_ids[aciCurAviIndex + aciCurAviIndexDelta]){
                 strcpy(avi -> avi_name,m -> avi_ids[aciCurAviIndex + aciCurAviIndexDelta]);
             }
         }
         else {
             if(m -> avi_ids && m -> avi_ids[aciCurAviIndex]){
                 strcpy(avi -> avi_name,m -> avi_ids[aciCurAviIndex]);
             }
         }
         if(ip && m -> mech_name){
             aciInitPricePanel(ip,(iListElement*)m,MECHOS_MODE,0);
 //            ip -> add_item(m -> mech_name,-1,aciCurColorScheme[FM_SELECT_COL]);
 //            ip -> add_item(aciGetPrice((iListElement*)m,MECHOS_MODE,0),-1,aciCurColorScheme[FM_SELECT_COL]);
         }
     }
     else {
         p = (invItem*)iShopItem;
         if(p -> avi_ids && p -> avi_ids[aciCurAviIndex]){
             strcpy(avi -> avi_name,p -> avi_ids[aciCurAviIndex]);
         }
         if(ip){
             aciInitPricePanel(ip,(iListElement*)p,ITEMS_MODE,0);
         }
     }
 }
References ACI_MECHOS_AVI_ID, ACI_PRICE_PANEL, aci_SecondMatrixID, aciCurAviIndex, aciCurAviIndexDelta, aciInitPricePanel(), aciXConv, aScrDisp, CHANGE_2_MECHOS_MODE, EMPTY_MODE, iEvLineID, iShopItem, ITEMS_MODE, iVideoPath, MECHOS_LIST_MODE, and MECHOS_MODE.
Referenced by aciChangeAviIndex(), aciChooseShopItem(), aciPrevShopItem(), and aciSetShopItem().
aciInitAviObject()
void aciInitAviObject (void)
 {
     fncMenu* mn;
     iScreenObject* obj;
     iAVIElement* avi;
     avi = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(avi){
         obj = (iScreenObject*)avi -> owner;
         if(obj -> flags & OBJ_TRIGGER){
             ((iTriggerObject*)obj) -> state = 0;
             ((iTriggerObject*)obj) -> trigger_init();
         }
     }
     mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(mn) mn -> flags &= ~FM_ACTIVE;
     switch(iEvLineID){
         case MECHOS_LIST_MODE:
             iEvLineID = MECHOS_MODE;
             break;
         case ITEMS_LIST_MODE:
             iEvLineID = ITEMS_MODE;
             break;
         case WEAPONS_LIST_MODE:
             iEvLineID = WEAPONS_MODE;
             break;
     }
     aciCurAviIndex = ACI_PICTURE_AVI_ENG;
 }
References ACI_MECHOS_AVI_ID, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciInitCurMatrixPtr()
void aciInitCurMatrixPtr (void)
 {
     aScrDisp -> curMatrix -> uvsDataPtr = GGamerMechos;
 }
References aScrDisp, curMatrix, and GGamerMechos.
Referenced by actIntDispatcher::swap_matrices().
aciInitEndGame()
void aciInitEndGame (int id)
 {
     char* ptr;
     ShowImageRTO* p = (ShowImageRTO*)xtGetRuntimeObject(RTO_SHOW_IMAGE_ID);
     LoadingRTO3* lp = (LoadingRTO3*)xtGetRuntimeObject(RTO_LOADING3_ID);
 //  int sz;
 //  XStream fh;
     if(!aciImgText){
         aciImgText = new aciScreenText;
         aciImgText -> MaxStrLen = 55;
         aciImgText -> MaxPageStr = 19;
         aciImgText -> color = 239 | (1 << 16);
         aciImgText -> DeltaY = -2;
         aciImgText -> font = 3;
     }
     switch(GameOverID){
         case GAME_OVER_EXPLOSION:
             if(lang() == RUSSIAN)
                 p -> SetName("img/img7.bmp");
             else
                 p -> SetName("img/img0.bmp");
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_INFERNAL_LOCKED:
             p -> SetName("img/img1.bmp");
             ptr = dgD -> getInvText(DG_FINAL,3);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_SPOBS_LOCKED:
             p -> SetName("img/img2.bmp");
             ptr = dgD -> getInvText(DG_FINAL,4);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_ALL_LOCKED:
             p -> SetName("img/img3.bmp");
             ptr = dgD -> getInvText(DG_FINAL,5);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_LUCKY:
             p -> SetName("img/img4.bmp");
             ptr = dgD -> getInvText(DG_FINAL,2);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_LAMPASSO:
             p -> SetName("img/img5.bmp");
             ptr = dgD -> getInvText(DG_FINAL,1);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_ABORT:
             lp -> SetNext(RTO_MAIN_MENU_ID);
             break;
         case GAME_OVER_NETWORK:
             iMultiFlag = 1;
             lp -> SetNext(RTO_MAIN_MENU_ID);
             break;
         default:
             lp -> SetNext(RTO_MAIN_MENU_ID);
             break;
     }
     p -> SetFlag(0,IMG_RTO_CD_IMAGE);
     GameOverID = 0;
 }
References aciImgText, DG_FINAL, dgD, GAME_OVER_ABORT, GAME_OVER_ALL_LOCKED, GAME_OVER_EXPLOSION, GAME_OVER_INFERNAL_LOCKED, GAME_OVER_LAMPASSO, GAME_OVER_LUCKY, GAME_OVER_NETWORK, GAME_OVER_SPOBS_LOCKED, GameOverID, IMG_RTO_CD_IMAGE, IMG_RTO_CDTRACK_TIME, IMG_RTO_KEEP_IMAGE, IMG_RTO_SHOW_TEXT, iMultiFlag, lang(), RTO_LOADING3_ID, RTO_MAIN_MENU_ID, RTO_SHOW_IMAGE_ID, RUSSIAN, and xtGetRuntimeObject().
Referenced by LoadingRTO3::Init().
aciInitEvLineID()
void aciInitEvLineID (void)
 {
     fncMenu* mn;
     iTriggerObject* p = (iTriggerObject*)aScrDisp -> curLocData -> objList[ACI_TRIGGER_ID];
     if(!p) return;
     if(GMechos){
         p -> state = 2;
         p -> init_state();
     }
     else {
         p -> state = 0;
         p -> init_state();
     }
     iEvLineID = p -> state + 1;
     p = (iTriggerObject*)aScrDisp -> curLocData -> objList[ACI_AVI_OBJ_ID];
     if(p){
         mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
         if(mn) mn -> flags &= ~FM_ACTIVE;
         p -> state = 0;
         p -> init_state();
     }
     switch(uvsBunchNumber){
         case 2:
             aciCurAviIndexDelta = 0;
             break;
         case 0:
             aciCurAviIndexDelta = ACI_PICTURE_AVI_ENG2;
             break;
         case 1:
             aciCurAviIndexDelta = ACI_PICTURE_AVI_ENG3;
             break;
     }
 }
References ACI_AVI_OBJ_ID, ACI_TRIGGER_ID, aScrDisp, GMechos, iEvLineID, and SHOP_ITEMS_MENU_ID.
Referenced by aciNextShopItem(), aciPrevShopItem(), aciSetShopItem(), and actIntDispatcher::i_init().
aciInitInfoPanels()
void aciInitInfoPanels (void)
 {
     InfoPanel* pl;
     CounterPanel* cp;
     iBitmapElement* el;
     fncMenu* mn;
     iScreenObject* obj;
     iScreen* scr;
     iAVIElement* avi;
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_QUEST_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_QUEST_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_ANSWER_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_TIME_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_SHOP_TIME_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_PRICE_PANEL_ID];
     pl = aScrDisp -> get_info_panel(ACI_PRICE_PANEL);
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_INFO_PANEL_ID];
     pl = aScrDisp -> iscr_iP;
     if(el && pl){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         pl -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         pl -> PosY = obj -> PosY + el -> lY;
         pl -> iScreenOwner = el;
         pl -> SizeX = el -> bSizeX;
         pl -> SizeY = el -> bSizeY;
         pl -> free_list();
         pl -> set_redraw();
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_CREDITS_PANEL_ID];
     cp = aScrDisp -> get_icounter(ACI_CREDITS_PANEL);
     if(el && cp){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         cp -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         cp -> PosY = obj -> PosY + el -> lY;
         cp -> iScreenOwner = el;
         cp -> SizeX = el -> bSizeX;
         cp -> SizeY = el -> bSizeY;
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> s_objList[ACI_QUEST_PANEL_ID];
     mn = aScrDisp -> get_imenu(ACI_QUEST_MENU);
     if(aScrDisp -> qMenu && el){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         aScrDisp -> qMenu -> data = el;
         aScrDisp -> qMenu -> ScreenX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         aScrDisp -> qMenu -> ScreenY = obj -> PosY + el -> lY;
         aScrDisp -> qMenu -> ScreenSizeX = obj -> SizeX;
         aScrDisp -> qMenu -> ScreenSizeY = obj -> SizeY;
     }
     el = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_ITEMS_MENU_ID];
     mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(mn && el){
         obj = (iScreenObject*)el -> owner;
         scr = (iScreen*)obj -> owner;
         mn -> iScreenOwner = el;
         mn -> SizeX = el -> bSizeX;
         mn -> SizeY = el -> bSizeY;
         mn -> PosX = obj -> PosX + el -> lX - scr -> ScreenOffs;
         mn -> PosY = obj -> PosY + el -> lY;
         aScrDisp -> clear_menu(mn);
     }
     avi = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(avi){
         obj = (iScreenObject*)avi -> owner;
         if(obj -> flags & OBJ_TRIGGER){
             ((iTriggerObject*)obj) -> state = 0;
             ((iTriggerObject*)obj) -> trigger_init();
         }
     }
 }
References ACI_ANSWER_PANEL, ACI_ANSWER_PANEL_ID, ACI_CREDITS_PANEL, ACI_CREDITS_PANEL_ID, ACI_INFO_PANEL_ID, ACI_ITEMS_MENU_ID, ACI_MECHOS_AVI_ID, ACI_PRICE_PANEL, ACI_PRICE_PANEL_ID, ACI_QUEST_MENU, ACI_QUEST_PANEL, ACI_QUEST_PANEL_ID, ACI_SHOP_TIME_PANEL, ACI_TIME_PANEL_ID, aScrDisp, and SHOP_ITEMS_MENU_ID.
Referenced by actIntDispatcher::i_init().
aciInitItmTextQueue()
void aciInitItmTextQueue (void)
 {
     int i;
     invItem* p;
     for(i = 0; i < ACI_ITEM_QUEUE_MAX; i ++){
         aciItmTextQueue[i] = NULL;
     }
     aciItmTextQueueSize = aciItmTextQueueCur = 0;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         if(aciItmTextQueueSize < ACI_ITEM_QUEUE_MAX && p -> ID == ACI_TABUTASK && (p -> flags & INV_ITEM_NEW)){
             aciItmTextQueue[aciItmTextQueueSize] = p;
             aciItmTextQueueSize ++;
         }
         p = (invItem*)p -> prev;
     }
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         if(aciItmTextQueueSize < ACI_ITEM_QUEUE_MAX && (p -> ID == ACI_ELEEPOD || p -> ID == ACI_BEEBOORAT || p -> ID == ACI_ZEEX) && (p -> flags & INV_ITEM_NEW)){
             aciItmTextQueue[aciItmTextQueueSize] = p;
             aciItmTextQueueSize ++;
         }
         p = (invItem*)p -> prev;
     }
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         p -> flags &= ~INV_ITEM_NEW;
         p = (invItem*)p -> prev;
     }
 }
References ACI_ITEM_QUEUE_MAX, ACI_TABUTASK, aciItmTextQueue, aciItmTextQueueCur, aciItmTextQueueSize, aScrDisp, curMatrix, and NULL.
Referenced by actIntDispatcher::i_finit().
aciInitMechosInfo()
void aciInitMechosInfo (invMatrix * p, InfoPanel * ip)
 {
     ip -> free_list();
     if(p){
         ip -> add_item(p -> mech_name,-1,aciCurColorScheme[FM_SELECT_COL]);
         if(!uvsCurrentWorldUnable){
             if(GMechos)
                 ip -> add_item(aciGetPrice((iListElement*)p,MECHOS_MODE,1));
         }
         ip -> set_redraw();
     }
 }
References aciCurColorScheme, aciGetPrice(), FM_SELECT_COL, GMechos, MECHOS_MODE, and uvsCurrentWorldUnable.
Referenced by actIntDispatcher::inv_mouse_imove_quant().
aciInitPanel()
void aciInitPanel (InfoPanel * p, unsigned char * str)
 {
     int i = 0,quit_log = 0,sz = strlen((char*)str),str_len,len,col;
     unsigned char* dest_str,*ptr,*tmp_ptr;
     dest_str = new unsigned char[sz + 1];
     ptr = new unsigned char[sz + 1];
     tmp_ptr = ptr;
     str_len = sz;
     strcpy((char*)ptr,(char*)str);
     col = (aciCurColorScheme[FM_SELECT_BORDER_COL] << 8) | aciCurColorScheme[FM_SELECT_BORDER_COL];
     while(!quit_log){
         strcpy((char*)dest_str,(char*)tmp_ptr);
         if(p -> flags & IP_RANGE_FONT)
             len = aStrLen32(dest_str,ACI_PHRASE_FONT,p->hSpace);
         else
             len = aStrLen(dest_str,ACI_PHRASE_FONT,p->hSpace);
         if(len < p->SizeX){
             if(p -> items -> Size >= p -> MaxStr){
                 std::cout<<"Dialog phrase too long..."<<std::endl;
                 quit_log = 1;
             } else {
                 p->add_item((char*)dest_str,-1,col);
                 sz -= strlen((char*)dest_str);
                 strcpy((char*)ptr, (char*)str);
                 if(sz <= 0) {
                     quit_log = 1;
                 } else {
                     tmp_ptr = ptr + (str_len - sz);
                 }
             }
         } else {
             i = sz;
             while(dest_str[i] != ' '){
                 i --;
                 if(i <= 0){
                     quit_log = 1;
                     break;
                 }
             }
             if(!quit_log)
                 tmp_ptr[i] = 0;
         }
     }
     delete[] dest_str;
     delete[] ptr;
 }
References aciCurColorScheme, and FM_SELECT_BORDER_COL.
Referenced by aciEscaveKickOut(), aciNextPhrase(), and aciShowBlockPhrase().
aciInitPricePanel()
void aciInitPricePanel (InfoPanel * ip, iListElement * p, int mode, int sell_mode)
 {
     invItem* it;
     invMatrix* m;
     uvsActInt* u;
     int col = -1;
     ip -> free_list();
     if(mode == MECHOS_MODE){
         m = (invMatrix*)p;
         u = (uvsActInt*)m -> uvsDataPtr;
         if(m -> mech_name) ip -> add_item(m -> mech_name,-1,aciCurColorScheme[FM_SELECT_COL]);
         if(m -> flags & IM_NOT_COMPLETE)
             ip -> add_item(aciSTR_BROKEN);
     }
     else {
         it = (invItem*)p;
         u = (uvsActInt*)it -> uvsDataPtr;
         if(it->ID_ptr.size()) {
             ip -> add_item(it->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
         }
     }
     if(!u)
         return;
     aciXConv -> init();
     if(!uvsCurrentWorldUnable){
         if(mode != MECHOS_MODE || !(m -> flags & IM_NOT_COMPLETE)){
             if(sell_mode)
                 *aciXConv < aciSTR_PRICE <= u -> sell_price < " $";
             else
                 *aciXConv < aciSTR_PRICE <= u -> price < " $";
             ip -> add_item(aciXConv -> address(),-1,col);
         }
     }
     if(mode == MECHOS_MODE){
         m = (invMatrix*)p;
         if(!sell_mode && m -> pData){
             aciXConv -> init();
             *aciXConv < aciSTR_ENERGY_SHIELD < " " < (m -> pData + ACI_MECHOS_ENERGY_SHIELD * ACI_MAX_PRM_LEN);
             ip -> add_item(aciXConv -> address(),-1,col);
             aciXConv -> init();
             *aciXConv < aciSTR_RESTORING_SPEED < " " < (m -> pData + ACI_MECHOS_RESTORING_SPEED * ACI_MAX_PRM_LEN);
             ip -> add_item(aciXConv -> address(),-1,col);
             aciXConv -> init();
             *aciXConv < aciSTR_MECHANIC_ARMOR < " " < (m -> pData + ACI_MECHOS_MECHANIC_ARMOR * ACI_MAX_PRM_LEN) < " " < aciSTR_VELOCITY < " " < (m -> pData + ACI_MECHOS_VELOCITY * ACI_MAX_PRM_LEN);
             ip -> add_item(aciXConv -> address(),-1,col);
             aciXConv -> init();
             *aciXConv < aciSTR_SPIRAL_CAPACITY < " " < (m -> pData + ACI_MECHOS_SPIRAL_CAPACITY * ACI_MAX_PRM_LEN);
             ip -> add_item(aciXConv -> address(),-1,col);
             aciXConv -> init();
             *aciXConv < aciSTR_AIR_RESERVE < " " < (m -> pData + ACI_MECHOS_AIR_RESERVE * ACI_MAX_PRM_LEN);
             ip -> add_item(aciXConv -> address(),-1,col);
         }
     }
     else {
         it = (invItem*)p;
         if(it -> pData && !sell_mode){
             if(it -> slotType == AS_WEAPON_SLOT || it -> slotType == AS_TWEAPON_SLOT){
                 aciXConv -> init();
                 *aciXConv < aciSTR_DAMAGE < " " < (it -> pData + ACI_WEAPON_DAMAGE * ACI_MAX_PRM_LEN);
                 ip -> add_item(aciXConv -> address(),-1,col);
                 if(!uvsCurrentWorldUnable){
                     aciXConv -> init();
                     *aciXConv < aciSTR_LOAD < " " < (it -> pData + ACI_WEAPON_LOAD * ACI_MAX_PRM_LEN);
                     ip -> add_item(aciXConv -> address(),-1,col);
                 }
                 aciXConv -> init();
                 *aciXConv < aciSTR_SHOTS < " " < (it -> pData + ACI_WEAPON_SHOTS_SEC * ACI_MAX_PRM_LEN);
                 ip -> add_item(aciXConv -> address(),-1,col);
                 aciXConv -> init();
                 *aciXConv < aciSTR_BURST < " " < (it -> pData + ACI_WEAPON_RANGE * ACI_MAX_PRM_LEN);
                 ip -> add_item(aciXConv -> address(),-1,col);
             }
             else {
                 if(it -> slotType == AS_DEVICE_SLOT){
                     if(!uvsCurrentWorldUnable){
                         aciXConv -> init();
                         *aciXConv < aciSTR_WORKING_TIME < " " < (it -> pData + ACI_DEVICE_WORKING_TIME * ACI_MAX_PRM_LEN) < aciSTR_SECONDS;
                         ip -> add_item(aciXConv -> address(),-1,col);
                     }
                 }
                 else {
                     aciXConv -> init();
                     *aciXConv < aciSTR_DAMAGE < " " < (it -> pData + ACI_AMMO_DAMAGE * ACI_MAX_PRM_LEN);
                     ip -> add_item(aciXConv -> address(),-1,col);
                     aciXConv -> init();
                     *aciXConv < aciSTR_IN_PACK < " " < (it -> pData + ACI_AMMO_IN_PACK * ACI_MAX_PRM_LEN);
                     ip -> add_item(aciXConv -> address(),-1,col);
                 }
             }
         }
     }
 }
References aciCurColorScheme, FM_SELECT_COL, and MECHOS_MODE.
Referenced by aciInitAviID().
aciInitShopAvi()
void aciInitShopAvi (void)
 {
     iAVIElement* avi;
     avi = (iAVIElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_AVI_ID];
     if(!avi) return;
     avi -> change_avi(avi -> avi_name);
     avi -> init_size();
     avi -> init_align();
 }
References ACI_MECHOS_AVI_ID, and aScrDisp.
Referenced by aciChooseShopItem(), and actIntDispatcher::EventQuant().
aciInitShopButtons()
void aciInitShopButtons (void)
 {
     iScreenObject* obj;
     iScreenElement* p,*p1,*p2,*p3,*p4;
     fncMenu* mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     p = NULL;
     p1 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_WEAPONS_BUTTON_ID];
     p2 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_BUTTON_ID];
     p3 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_ITEMS_BUTTON_ID];
     p4 = (iScreenElement*)aScrDisp -> curLocData -> objList[ACI_MENU_BUTTON_ID];
     if(p1){
         obj = (iScreenObject*)p1 -> owner;
         p1 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
         obj -> flags |= OBJ_MUST_REDRAW;
     }
     if(p2){
         obj = (iScreenObject*)p2 -> owner;
         p2 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
         obj -> flags |= OBJ_MUST_REDRAW;
     }
     if(p3){
         obj = (iScreenObject*)p3 -> owner;
         p3 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
         obj -> flags |= OBJ_MUST_REDRAW;
     }
     if(p4){
         obj = (iScreenObject*)p4 -> owner;
         obj -> flags |= OBJ_MUST_REDRAW;
         if(mn && mn -> flags & FM_ACTIVE)
             p4 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_ON_TYPE]);
         else
             p4 -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_OFF_TYPE]);
     }
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
         case CHANGE_2_MECHOS_MODE:
             p = p2;
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             p = p1;
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
             p = p3;
             break;
     }
     if(p){
         p -> change_terrainNum(aScrDisp -> curLocData -> numIndex[ACI_BUTTON_ON_TYPE]);
     }
 }
References ACI_BUTTON_OFF_TYPE, ACI_ITEMS_BUTTON_ID, ACI_MECHOS_BUTTON_ID, ACI_MENU_BUTTON_ID, ACI_WEAPONS_BUTTON_ID, aScrDisp, NULL, and SHOP_ITEMS_MENU_ID.
Referenced by actIntDispatcher::EventQuant().
aciInitShopItems()
void aciInitShopItems (void)
 {
     invItem* p;
     invMatrix* m;
     uvsActInt* u;
 #ifdef _ACI_LOGFILE_
     aScrDisp -> logFile.open(aciLogFileName,XS_OUT | XS_APPEND | XS_NOREPLACE);
     aScrDisp -> logFile < "\r\nLocation: " < aci_curLocationName;
 #endif
     p = (invItem*)aScrDisp -> i_itemList -> last;
     while(p){
         p -> uvsDataPtr = NULL;
         p = (invItem*)p -> prev;
     }
     m = (invMatrix*)aScrDisp -> i_matrixList -> last;
     while(m){
         m -> uvsDataPtr = NULL;
         m = (invMatrix*)m -> prev;
     }
     if(aScrDisp -> curMatrix){
         p = (invItem*)aScrDisp -> curMatrix -> items -> last;
         while(p){
             p -> uvsDataPtr = NULL;
             p = (invItem*)p -> prev;
         }
     }
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\n\r\nShopItems :\r\n";
 #endif
     u = GMechos;
     while(u){
         m = aScrDisp -> get_imatrix(u -> type);
         if(m && !m -> uvsDataPtr)
             m -> uvsDataPtr = u;
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\nMechos \"" < m -> mech_name < "\"";
 #endif
         u = (uvsActInt*)u -> next;
     }
     u = GItem;
     while(u){
         p = aScrDisp -> get_iitem(u -> type);
         if(p && !p -> uvsDataPtr)
             p -> uvsDataPtr = u;
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\nItem \"" < p -> ID_ptr < "\"";
 #endif
         u = (uvsActInt*)u -> next;
     }
     if(aScrDisp -> curMatrix){
 #ifdef _ACI_LOGFILE_
         aScrDisp -> logFile < "\r\n\r\nGamerItems :\r\n";
 #endif
         p = (invItem*)aScrDisp -> curMatrix -> items -> last;
         while(p){
             p -> uvsDataPtr = NULL;
 #ifdef _ACI_LOGFILE_
             aScrDisp -> logFile < "\r\n" < p -> ID_ptr;
 #endif
             p = (invItem*)p -> prev;
         }
         u = GGamer;
         while(u){
             p = (invItem*)aScrDisp -> curMatrix -> items -> last;
             while(p){
                 if(!p -> uvsDataPtr && p -> ID == u -> type && p -> MatrixX == u -> pos_x && p -> MatrixY == u -> pos_y){
                     p -> uvsDataPtr = u;
                     break;
                 }
                 p = (invItem*)p -> prev;
             }
             u = (uvsActInt*)u -> next;
         }
         p = (invItem*)aScrDisp -> curMatrix -> items -> last;
         while(p){
             if(!p -> uvsDataPtr)
                 ErrH.Abort("aciInitShopItems failed...");
             p = (invItem*)p -> prev;
         }
         aScrDisp -> curMatrix -> uvsDataPtr = GGamerMechos;
     }
     aciChangeList();
 #ifdef _ACI_LOGFILE_
     aScrDisp -> logFile.close();
 #endif
 }
References aci_curLocationName, aScrDisp, curMatrix, GMechos, NULL, prev, XS_APPEND, XS_NOREPLACE, and XS_OUT.
Referenced by actIntDispatcher::i_init().
aciInitShopList()
void aciInitShopList (void)
 {
     switch(iEvLineID){
         case MECHOS_LIST_MODE:
             iEvLineID = MECHOS_MODE;
             aciCloseShopMenu();
             break;
         case ITEMS_LIST_MODE:
             iEvLineID = ITEMS_MODE;
             aciCloseShopMenu();
             break;
         case WEAPONS_LIST_MODE:
             iEvLineID = WEAPONS_MODE;
             aciCloseShopMenu();
             break;
         case MECHOS_MODE:
         case ITEMS_MODE:
         case WEAPONS_MODE:
             aciBuildShopList();
             break;
     }
 }
References aciBuildShopList(), aciCloseShopMenu(), iEvLineID, ITEMS_LIST_MODE, ITEMS_MODE, MECHOS_LIST_MODE, MECHOS_MODE, WEAPONS_LIST_MODE, and WEAPONS_MODE.
Referenced by actIntDispatcher::EventQuant().
aciInitStrings()
void aciInitStrings (void)
 {
     if(lang() != RUSSIAN){
         aciSTR_ON = aciSTR_ON1;
         aciSTR_OFF = aciSTR_OFF1;
         aciSTR_DAY = aciSTR_DAY1;
         aciSTR_UNDEFINED_PRICE = aciSTR_UNDEFINED_PRICE1;
         aciSTR_PRICE = aciSTR_PRICE1;
         aciSTR_EMPTY_SLOT = aciSTR_EMPTY_SLOT1;
         aciSTR_UNNAMED_SAVE = aciSTR_UNNAMED_SAVE1;
         aciSTR_AUTOSAVE = aciSTR_AUTOSAVE1;
         aciSTR_KILLS = aciSTR_KILLS1;
         aciSTR_DEATHS = aciSTR_DEATHS1;
         aciSTR_LUCK = aciSTR_LUCK1;
         aciSTR_DOMINANCE = aciSTR_DOMINANCE1;
         aciSTR_BROKEN = aciSTR_BROKEN1;
         aciSTR_ENERGY_SHIELD = aciSTR_ENERGY_SHIELD1;
         aciSTR_RESTORING_SPEED = aciSTR_RESTORING_SPEED1;
         aciSTR_MECHANIC_ARMOR = aciSTR_MECHANIC_ARMOR1;
         aciSTR_VELOCITY = aciSTR_VELOCITY1;
         aciSTR_SPIRAL_CAPACITY = aciSTR_SPIRAL_CAPACITY1;
         aciSTR_AIR_RESERVE = aciSTR_AIR_RESERVE1;
         aciSTR_DAMAGE = aciSTR_DAMAGE1;
         aciSTR_LOAD = aciSTR_LOAD1;
         aciSTR_SHOTS = aciSTR_SHOTS1;
         aciSTR_BURST = aciSTR_BURST1;
         aciSTR_WORKING_TIME = aciSTR_WORKING_TIME1;
         aciSTR_SECONDS = aciSTR_SECONDS1;
         aciSTR_IN_PACK = aciSTR_IN_PACK1;
         aciSTR_NO_CASH = aciSTR_NO_CASH1;
         aciSTR_PICKUP_ITEMS_OFF = aciSTR_PICKUP_ITEMS_OFF1;
         aciSTR_PICKUP_WEAPONS_OFF = aciSTR_PICKUP_WEAPONS_OFF1;
         aciSTR_PutThis = aciSTR_PutThis1;
         aciSTR_Ware1 = aciSTR_Ware11;
         aciSTR_Ware2 = aciSTR_Ware21;
         aciSTR_Checkpoints = aciSTR_Checkpoints1;
     }
     else {
         aciSTR_ON = aciSTR_ON2;
         aciSTR_OFF = aciSTR_OFF2;
         aciSTR_DAY = aciSTR_DAY2;
         aciSTR_UNDEFINED_PRICE = aciSTR_UNDEFINED_PRICE2;
         aciSTR_PRICE = aciSTR_PRICE2;
         aciSTR_EMPTY_SLOT = aciSTR_EMPTY_SLOT2;
         aciSTR_UNNAMED_SAVE = aciSTR_UNNAMED_SAVE2;
         aciSTR_AUTOSAVE = aciSTR_AUTOSAVE2;
         aciSTR_KILLS = aciSTR_KILLS2;
         aciSTR_DEATHS = aciSTR_DEATHS2;
         aciSTR_LUCK = aciSTR_LUCK2;
         aciSTR_DOMINANCE = aciSTR_DOMINANCE2;
         aciSTR_BROKEN = aciSTR_BROKEN2;
         aciSTR_ENERGY_SHIELD = aciSTR_ENERGY_SHIELD2;
         aciSTR_RESTORING_SPEED = aciSTR_RESTORING_SPEED2;
         aciSTR_MECHANIC_ARMOR = aciSTR_MECHANIC_ARMOR2;
         aciSTR_VELOCITY = aciSTR_VELOCITY2;
         aciSTR_SPIRAL_CAPACITY = aciSTR_SPIRAL_CAPACITY2;
         aciSTR_AIR_RESERVE = aciSTR_AIR_RESERVE2;
         aciSTR_DAMAGE = aciSTR_DAMAGE2;
         aciSTR_LOAD = aciSTR_LOAD2;
         aciSTR_SHOTS = aciSTR_SHOTS2;
         aciSTR_BURST = aciSTR_BURST2;
         aciSTR_WORKING_TIME = aciSTR_WORKING_TIME2;
         aciSTR_SECONDS = aciSTR_SECONDS2;
         aciSTR_IN_PACK = aciSTR_IN_PACK2;
         aciSTR_NO_CASH = aciSTR_NO_CASH2;
         aciSTR_PICKUP_ITEMS_OFF = aciSTR_PICKUP_ITEMS_OFF2;
         aciSTR_PICKUP_WEAPONS_OFF = aciSTR_PICKUP_WEAPONS_OFF2;
         aciSTR_PutThis = aciSTR_PutThis2;
         aciSTR_Ware1 = aciSTR_Ware12;
         aciSTR_Ware2 = aciSTR_Ware22;
         aciSTR_Checkpoints = aciSTR_Checkpoints2;
     }
 }
References aciSTR_AIR_RESERVE, aciSTR_AIR_RESERVE1, aciSTR_AIR_RESERVE2, aciSTR_AUTOSAVE, aciSTR_AUTOSAVE1, aciSTR_AUTOSAVE2, aciSTR_BROKEN, aciSTR_BROKEN1, aciSTR_BROKEN2, aciSTR_BURST, aciSTR_BURST1, aciSTR_BURST2, aciSTR_Checkpoints, aciSTR_Checkpoints1, aciSTR_Checkpoints2, aciSTR_DAMAGE, aciSTR_DAMAGE1, aciSTR_DAMAGE2, aciSTR_DAY, aciSTR_DAY1, aciSTR_DAY2, aciSTR_DEATHS, aciSTR_DEATHS1, aciSTR_DEATHS2, aciSTR_DOMINANCE, aciSTR_DOMINANCE1, aciSTR_DOMINANCE2, aciSTR_EMPTY_SLOT, aciSTR_EMPTY_SLOT1, aciSTR_EMPTY_SLOT2, aciSTR_ENERGY_SHIELD, aciSTR_ENERGY_SHIELD1, aciSTR_ENERGY_SHIELD2, aciSTR_IN_PACK, aciSTR_IN_PACK1, aciSTR_IN_PACK2, aciSTR_KILLS, aciSTR_KILLS1, aciSTR_KILLS2, aciSTR_LOAD, aciSTR_LOAD1, aciSTR_LOAD2, aciSTR_LUCK, aciSTR_LUCK1, aciSTR_LUCK2, aciSTR_MECHANIC_ARMOR, aciSTR_MECHANIC_ARMOR1, aciSTR_MECHANIC_ARMOR2, aciSTR_NO_CASH, aciSTR_NO_CASH1, aciSTR_NO_CASH2, aciSTR_OFF, aciSTR_OFF1, aciSTR_OFF2, aciSTR_ON, aciSTR_ON1, aciSTR_ON2, aciSTR_PICKUP_ITEMS_OFF, aciSTR_PICKUP_ITEMS_OFF1, aciSTR_PICKUP_ITEMS_OFF2, aciSTR_PICKUP_WEAPONS_OFF, aciSTR_PICKUP_WEAPONS_OFF1, aciSTR_PICKUP_WEAPONS_OFF2, aciSTR_PRICE, aciSTR_PRICE1, aciSTR_PRICE2, aciSTR_PutThis, aciSTR_PutThis1, aciSTR_PutThis2, aciSTR_RESTORING_SPEED, aciSTR_RESTORING_SPEED1, aciSTR_RESTORING_SPEED2, aciSTR_SECONDS, aciSTR_SECONDS1, aciSTR_SECONDS2, aciSTR_SHOTS, aciSTR_SHOTS1, aciSTR_SHOTS2, aciSTR_SPIRAL_CAPACITY, aciSTR_SPIRAL_CAPACITY1, aciSTR_SPIRAL_CAPACITY2, aciSTR_UNDEFINED_PRICE, aciSTR_UNDEFINED_PRICE1, aciSTR_UNDEFINED_PRICE2, aciSTR_UNNAMED_SAVE, aciSTR_UNNAMED_SAVE1, aciSTR_UNNAMED_SAVE2, aciSTR_VELOCITY, aciSTR_VELOCITY1, aciSTR_VELOCITY2, aciSTR_Ware1, aciSTR_Ware11, aciSTR_Ware12, aciSTR_Ware2, aciSTR_Ware21, aciSTR_Ware22, aciSTR_WORKING_TIME, aciSTR_WORKING_TIME1, aciSTR_WORKING_TIME2, lang(), and RUSSIAN.
Referenced by aInit().
aciInitWorldIDs()
void aciInitWorldIDs (void)
 {
     int i;
     signed char* ids;
     uvsWorld* wrld;
     aciWorldInfo* a_wrld;
     if(!aScrDisp -> wMap) return;
     ids = aScrDisp -> wMap -> world_ids;
     memset(ids,-1,AS_MAX_WORLD);
     for(i = 0; i < WORLD_MAX; i ++){
         wrld = WorldTable[i];
         a_wrld = aScrDisp -> wMap -> get_world_p(wrld -> name);
         if(a_wrld){
             ids[i] = a_wrld -> ID;
             a_wrld -> uvsID = i;
         }
     }
     aScrDisp -> flags |= AS_WORLDS_INIT;
 //    aciPrepareWorldsMenu();
 }
References AS_MAX_WORLD, aScrDisp, wMap, WORLD_MAX, and WorldTable.
aciKillLinks()
void aciKillLinks (void)
 {
     if(!aScrDisp -> curMatrix) return;
     invItem* p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         p -> item_ptr = NULL;
         p = (invItem*)p -> prev;
     }
 }
References aScrDisp, curMatrix, NULL, and prev.
Referenced by aci_LocationQuantFinit(), and VangerUnit::Go2Universe().
aciLoadData()
void aciLoadData (void)
 {
     acsLoadData();
 }
References acsLoadData().
Referenced by FirstEscaveRTO::Init().
aciLoadPackedFile()
char* aciLoadPackedFile (XStream & fh, int & out_sz)
 {
     int sz;
     char *p,*ptr;
     sz = fh.size();
     p = new char[sz];
     fh.read(p,sz);
     out_sz = *(unsigned int*)(p + 2);
     long long_out_sz = out_sz;
     ptr = new char[out_sz];
     //ZIP_expand(ptr,out_sz,p,sz);
     /* ZLIB realisation (stalkerg)*/
     if(*(short*)(p)) { //if label = 0 not compress
         //std::cout<<"aciLoadPackedFile DeCompress "<<fh.file_name<<" file."<<std::endl;
         int stat = uncompress((Bytef*)ptr,(uLongf*)&long_out_sz,(Bytef*)(p+2+4),sz-2-4);
         switch(stat){
             //case Z_OK: std::cout<<"DeCompress ok."<<std::endl; break;
             case Z_MEM_ERROR: std::cout<<"DeCompress not enough memory."<<std::endl; break;
             case Z_BUF_ERROR: std::cout<<"DeCompress not enough room in the output buffer."<<std::endl; break;
             case Z_DATA_ERROR: std::cout<<"DeCompress error data."<<std::endl; break;
         };
     } else {
         memcpy(ptr, p + 2 + 4,(unsigned)(sz - 2 - 4));
     }
     delete[] p;
     return ptr;
 }
References XStream::read(), and XStream::size().
Referenced by iTextData::load(), load_s_text(), and load_text().
aciLoadUVSList()
void aciLoadUVSList (XStream & fh, uvsActInt ** p, int list_type = 0)
 {
     int i,list_size = 0;
     uvsActInt* ptr;
     listElem* el = (listElem*)(*p);
     fh > list_size;
     for(i = 0; i < list_size; i ++){
         ptr = new uvsActInt;
         ptr -> load(fh,list_type);
         //std::cout<<"aciLoadUVSList new "<<ptr<<" type:"<<ptr->type<<" price:"<<ptr->price<<" param1:"<<ptr->param1<<" param2:"<<ptr->param2<<std::endl;
         ptr -> link(el);
     }
     *p = (uvsActInt*)el;
 }
Referenced by acsLoadData().
aciNewMechos()
void aciNewMechos (int newID)
 {
     if(aScrDisp -> curMatrix)
         aScrDisp -> free_matrix(aScrDisp -> curMatrix);
     if(newID != -1)
         aScrDisp -> curMatrix = aScrDisp -> alloc_matrix(newID);
     else
         aScrDisp -> curMatrix = NULL;
 }
References aScrDisp, curMatrix, and NULL.
Referenced by VangerUnit::ChangeVangerProcess(), and VangerUnit::Go2Universe().
aciNextPhrase()
void aciNextPhrase (void)
 {
     unsigned char* str;
     iScreenObject* obj;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p || !p -> iScreenOwner) return;
     if(aciEscaveDead){
         aciClearQuestMenu();
         obj = (iScreenObject*)p -> iScreenOwner -> owner;
         p -> free_list();
         str = (unsigned char*)dgD -> getQdead();
         if(str) aciInitPanel(p,str);
         p -> set_redraw();
         return;
     }
     if(!aciSpeechStarted && dgD -> isEnd())
         aciSpeechEndLocked = aciSpeechBegLocked = aciEndSpeech = 1;
     aciClearQuestMenu();
     obj = (iScreenObject*)p -> iScreenOwner -> owner;
     p -> free_list();
     str = (unsigned char*)dgD -> getNextPhrase();
     if(aciEndSpeech){
         if(!dgD -> isEnd()){
             aciEndSpeech = 0;
         }
         else {
             p -> set_redraw();
             return;
         }
     }
     if(str)
         aciInitPanel(p,str);
     aciSpeechEndLocked = dgD -> isEnd();
     if(str && !aciEscaveEmpty)
         aciStartSpeech();
     p -> set_redraw();
 }
References ACI_ANSWER_PANEL, aciClearQuestMenu(), aciEndSpeech, aciEscaveDead, aciEscaveEmpty, aciInitPanel(), aciSpeechBegLocked, aciSpeechEndLocked, aciSpeechStarted, aciStartSpeech(), aScrDisp, and dgD.
Referenced by aciML_Dispatcher::event_quant(), and actIntDispatcher::EventQuant().
aciNextShopItem()
void aciNextShopItem (void)
 {
     invItem* p,*fp;
     invMatrix* m,*fm;
     if(!iShopItem){
         aciInitEvLineID();
         aciChangeList();
         return;
     }
     aciShopMenuDown();
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
             fm = (invMatrix*)iShopItem;
             m = (invMatrix*)fm -> next;
             if(m != fm){
                 while(!m -> uvsDataPtr){
                     m = (invMatrix*)m -> next;
                     if(m == fm) break;
                 }
                 if(!m -> uvsDataPtr){
                     iShopItem = NULL;
                 }
                 else {
                     iShopItem = (iListElement*)m;
                     aciCurMechosID = m -> type;
                 }
             }
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> next;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS){
                     p = (invItem*)p -> next;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> next;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS){
                     p = (invItem*)p -> next;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
     }
     aciInitAviID();
 }
References aciChangeList(), aciInitEvLineID(), aciShopMenuDown(), iEvLineID, iShopItem, MECHOS_LIST_MODE, and MECHOS_MODE.
Referenced by actIntDispatcher::EventQuant().
aciOfferEleech()
void aciOfferEleech (void)
 {
     int w_id = aScrDisp -> wMap -> world_ptr[aScrDisp -> curLocData -> WorldID] -> uvsID;
     aciML_SendEvent(AML_KEY_TRAP,AML_KEY,AML_ELEECH_CODE);
     WaitGameInTown(w_id);
 }
References aciML_SendEvent(), AML_ELEECH_CODE, AML_KEY, AML_KEY_TRAP, aScrDisp, WaitGameInTown(), and wMap.
Referenced by dg_SendEvent().
aciOfferWeezyk()
void aciOfferWeezyk (void)
 {
     aciML_SendEvent(AML_KEY_TRAP,AML_KEY,AML_ELEECH_CODE);
 }
References aciML_SendEvent(), AML_ELEECH_CODE, AML_KEY, and AML_KEY_TRAP.
Referenced by dg_SendEvent().
aciOpenGate()
void aciOpenGate (void)
 {
     int i,timer,max_timer = 0;
     _iSTORE_OFFS_;
     unsigned char* fon_buf;
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_MouseShow();
     return;
 #endif
     SOUND_GATE();
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer){
         XGR_MouseShow();
         return;
     }
     if(XGR_MouseVisible())
         XGR_MouseHide();
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < max_timer; i ++)
         aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < max_timer; i ++)
             timer += aScrDisp -> curLocData -> GateShutters[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < max_timer; i ++)
             aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> freeData();
     }
     delete[] fon_buf;
     XGR_MouseShow();
     iKeyClear();
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_SHUTTER_OPEN, aScrDisp, i_get_scrfon(), i_put_scrfon(), iKeyClear(), Redraw, SOUND_GATE, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
aciOpenWorldLink()
void aciOpenWorldLink (int w1, int w2)
 {
     int id1,id2;
     aciWorldInfo* p1,*p2;
     id1 = aScrDisp -> wMap -> world_ids[w1];
     id2 = aScrDisp -> wMap -> world_ids[w2];
     if(id1 == -1 || id2 == -1) ErrH.Abort("Bad world ID...");
     p1 = aScrDisp -> wMap -> world_ptr[id1];
     p2 = aScrDisp -> wMap -> world_ptr[id2];
     if(!p1 || !p2) ErrH.Abort("Bad world ptr...");
     p1 -> links[id2] = 1;
     if(id1 != id2 && p2 -> links[id1]) p2 -> links[id1] = 0;
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
     aciPrevJumpCount = -1;
 }
References XErrorHandler::Abort(), aScrDisp, ErrH, and wMap.
Referenced by NetworkWorldOpen(), and StuffObject::Quant().
aciPackFile()
void aciPackFile (char * fname)
 {
     int sz, sz1;
     char* p, *p1;
     XStream fh(fname,XS_IN);
     sz1 = sz = fh.size();
     sz1+=12;
     p = new char[sz];
     p1 = new char[sz1];
     fh.read(p,sz);
     fh.close();
     //sz1 = ZIP_compress(p1,sz,p,sz);
     /* ZLIB realization (stalkerg)*/
     p1[0] = (char)(8 & 0xFF); //8 it is DEFLATE method
     p1[1] = (char)((8 >> 8) & 0xFF);
     *(unsigned int*)(p1 + 2) = (unsigned int)sz;
     sz1-=2+4;
     int stat = compress((Bytef*)(p1+2+4),(uLongf*)&(sz1),(Bytef*)p,sz);
     sz1+=2+4;
     switch(stat){
         //case Z_OK: std::cout<<"Compress ok."<<std::endl; break;
         case Z_MEM_ERROR: std::cout<<"not enough memory."<<std::endl; break;
         case Z_BUF_ERROR: std::cout<<"not enough room in the output buffer."<<std::endl; break;
     };
     fh.open(fname,XS_OUT);
     fh.write(p1,sz1);
     fh.close();
     delete[] p;
     delete[] p1;
 }
References XStream::close(), XStream::open(), XStream::read(), XStream::size(), XStream::write(), XS_IN, and XS_OUT.
aciPay4Item()
void aciPay4Item (invItem * p)
 {
     int cr = aciGetCurCredits();
     uvsActInt* u = (uvsActInt*)p -> uvsDataPtr;
     cr -= u -> price;
     aciUpdateCurCredits(cr);
     p -> flags &= ~INV_ITEM_NO_PAY;
 }
References aciGetCurCredits(), and aciUpdateCurCredits().
Referenced by actIntDispatcher::change_items(), actIntDispatcher::inv_mouse_quant_l(), and actIntDispatcher::inv_mouse_quant_r().
aciPrepareEndImage()
void aciPrepareEndImage (void)
 {
     StopCDTRACK();
     ShowImageRTO* p;
     p = (ShowImageRTO*)xtGetRuntimeObject(RTO_SHOW_IMAGE_ID);
     p -> SetNumFiles(1);
     if(lang() == RUSSIAN)
         p -> SetName("img/img8.bmp",0);
     else
         p -> SetName("img/img6.bmp",0);
     p -> SetFlag(0,IMG_RTO_CD_IMAGE);
     p -> SetNext(XT_TERMINATE_ID);
 }
References IMG_RTO_CD_IMAGE, lang(), RTO_SHOW_IMAGE_ID, RUSSIAN, StopCDTRACK(), XT_TERMINATE_ID, and xtGetRuntimeObject().
Referenced by actIntDispatcher::flush(), and MainMenuRTO::Quant().
aciPrepareMenus()
void aciPrepareMenus (void)
 {
     aScrDisp -> clean_menus();
     aScrDisp -> prepare_menus();
     aciPrepareWorldsMenu();
 }
References aciPrepareWorldsMenu(), and aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), GeneralSystemOpen(), and FirstEscaveRTO::Init().
aciPrepareScreenText()
void aciPrepareScreenText (char * ptr, int sz, int max_len)
 {
     int i,offs_start,offs_end,offs;
 //    XStream fh("text0.dat",XS_OUT);
 //    fh.write(ptr,sz);
 //    fh.close();
     offs_start = offs_end = 0;
     while(offs_start < sz - 1){
         while(ptr[offs_end] != '\n'){
             offs_end ++;
             if(offs_end >= sz){
                 offs_end = sz - 1;
                 break;
             }
         }
         if(offs_end - offs_start > max_len){
             offs = offs_start + max_len;
             for(i = 0; i < max_len; i ++){
                 if(ptr[offs] == ' ' || ptr[offs] == '\t'){
                     break;
                 }
                 offs --;
                 if(offs <= offs_start){
                     break;
                 }
             }
             ptr[offs] = '\n';
             if(offs > offs_start){
                 offs_start = offs;
                 offs_end = offs + 1;
             }
             else {
                 offs_start = offs_end;
                 offs_end ++;
             }
         }
         else {
             offs_start = offs_end;
             offs_end ++;
         }
     }
 //    fh.open("text1.dat",XS_OUT);
 //    fh.write(ptr,sz);
 //    fh.close();
 }
Referenced by aciScreenText::alloc().
aciPrepareText()
void aciPrepareText (char * ptr)
 {
     int sz = strlen(ptr);
     aScrDisp -> ScrTextData -> alloc(ptr,sz);
     aScrDisp -> send_event(ACI_SHOW_TEXT);
 }
References ACI_SHOW_TEXT, and aScrDisp.
Referenced by aciSendEvent2itmdsp(), and DoorEngine::Quant().
aciPrepareWorldsMenu()
void aciPrepareWorldsMenu (void)
 {
     int i;
     aciWorldInfo* p1;
     if(CurrentWorld == -1) return;
     fncMenu* p = aScrDisp -> get_menu(FMENU_WORLDS_MENU);
     if(p){
         p -> prepare_items();
         for(i = 0; i < AS_MAX_WORLD; i ++){
             if(!aScrDisp -> wMap -> world_key(i)){
                 p -> deactivate_item(1000 + i);
             }
         }
         if(aScrDisp -> flags & AS_WORLDS_INIT){
             p1 = (aciWorldInfo*)aScrDisp -> wMap -> world_list -> last;
             while(p1){
                 if(p1 -> uvsID == CurrentWorld) p -> deactivate_item(1000 + p1 -> ID);
                 p1 = (aciWorldInfo*)p1 -> prev;
             }
         }
     }
 }
References AS_MAX_WORLD, aScrDisp, CurrentWorld, FMENU_WORLDS_MENU, and wMap.
Referenced by aciPrepareMenus(), actIntDispatcher::i_finit(), load_map_bmp(), NetworkWorldOpen(), and StuffObject::Quant().
aciPrevShopItem()
void aciPrevShopItem (void)
 {
     invItem* p,*fp;
     invMatrix* m,*fm;
     if(!iShopItem){
         aciInitEvLineID();
         aciChangeList();
         return;
     }
     aciShopMenuUp();
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
             fm = (invMatrix*)iShopItem;
             m = (invMatrix*)fm -> prev;
             if(!m) m = (invMatrix*)aScrDisp -> i_matrixList -> last;
             while(!m -> uvsDataPtr){
                 m = (invMatrix*)m -> prev;
                 if(!m) m = (invMatrix*)aScrDisp -> i_matrixList -> last;
                 if(m == fm) break;
             }
             if(!m -> uvsDataPtr){
                 iShopItem = NULL;
             }
             else {
                 iShopItem = (iListElement*)m;
                 aciCurMechosID = m -> type;
             }
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> prev;
             if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS){
                     p = (invItem*)p -> prev;
                     if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_ITEM_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             fp = (invItem*)iShopItem;
             p = (invItem*)fp -> prev;
             if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
             if(p != fp){
                 while(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS){
                     p = (invItem*)p -> prev;
                     if(!p) p = (invItem*)aScrDisp -> i_itemList -> last;
                     if(p == fp) break;
                 }
                 if(!p -> uvsDataPtr || p -> classID != AS_WEAPON_CLASS)
                     iShopItem = NULL;
                 else
                     iShopItem = (iListElement*)p;
             }
             break;
     }
     aciInitAviID();
 }
References aciChangeList(), aciCurMechosID, aciInitAviID(), aciInitEvLineID(), aciShopMenuUp(), AS_ITEM_CLASS, AS_WEAPON_CLASS, aScrDisp, CHANGE_2_ITEMS_MODE, CHANGE_2_WEAPONS_MODE, iEvLineID, iShopItem, ITEMS_LIST_MODE, ITEMS_MODE, MECHOS_LIST_MODE, MECHOS_MODE, NULL, prev, WEAPONS_LIST_MODE, and WEAPONS_MODE.
Referenced by actIntDispatcher::EventQuant().
aciPutBufSpr()
void aciPutBufSpr (int x, int y, int sx, int sy, int bsx, void * src, void * dest, int col, int col_sz)
 {
     int i,j,dest_index,src_index;
     unsigned src_col;
     unsigned char* src_buf,*dest_buf;
     dest_index = x + y * bsx;
     src_index = 0;
     src_buf = (unsigned char*)src;
     dest_buf = (unsigned char*)dest;
     if(!col_sz){
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 src_col = src_buf[src_index + j];
                 if(src_col)
                     dest_buf[dest_index + j] = col + src_col;
             }
             dest_index += bsx;
             src_index += sx;
         }
     }
     else {
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 src_col = src_buf[src_index + j];
                 if(src_col)
                     dest_buf[dest_index + j] = col + (src_col >> col_sz);
             }
             dest_index += bsx;
             src_index += sx;
         }
     }
 }
Referenced by aPutStr32(), and aIndData::build_pict().
aciPutItem()
int aciPutItem (int id, int x, int y)
 {
     invItem* p,*p1;
     if(aScrDisp -> flags & AS_ISCREEN)
         p1 = aScrDisp -> get_iitem(id);
     else
         p1 = aScrDisp -> get_item(id);
     if(!p1) ErrH.Abort("Bad aciPutItem() argument...");
     p = aScrDisp -> alloc_item();
     p1 -> clone(p);
     p -> item_ptr = NULL;
     if(aScrDisp -> curMatrix){
         if(x != -1){
             if(!aScrDisp -> put_item_xy(p,x,y,0)){
                 aScrDisp -> free_item(p);
                 return 0;
             }
         }
         else {
             if(!aScrDisp -> put_item_auto(p)){
                 aScrDisp -> free_item(p);
                 return 0;
             }
         }
         return 1;
     }
     aScrDisp->free_item(p);
     return 0;
 }
References aScrDisp.
Referenced by aciAddRubox(), aciGetRubox(), VangerUnit::Go2Universe(), and VangerUnit::Go2World().
aciPutSpr32()
void aciPutSpr32 (int x, int y, int sx, int sy, void * buf, int col, int col_sz)
 {
     int i,j,index = 0;
     unsigned cl;
     unsigned char* p = (unsigned char*)buf;
     if(col_sz){
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 cl = p[index];
                 cl >>= col_sz;
                 if(cl)
                     XGR_SetPixelFast(x + j,y + i,col + cl);
                 index ++;
             }
         }
     }
     else {
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 cl = p[index];
                 if(cl)
                     XGR_SetPixelFast(x + j,y + i,col + cl);
                 index ++;
             }
         }
     }
 }
References XGR_SetPixelFast().
Referenced by acsOutStr(), and aOutText32().
aciPutSpr32clip()
void aciPutSpr32clip (int x, int y, int sx, int sy, void * buf, int col, int col_sz)
 {
     int i,j,index = 0;
     unsigned cl;
     unsigned char* p = (unsigned char*)buf;
     if(col_sz){
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 cl = p[index];
                 cl >>= col_sz;
                 if(cl)
                     XGR_SetPixel(x + j,y + i,col + cl);
                 index ++;
             }
         }
     }
     else {
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 cl = p[index];
                 if(cl)
                     XGR_SetPixel(x + j,y + i,col + cl);
                 index ++;
             }
         }
     }
 }
References XGR_SetPixel.
Referenced by aOutText32clip().
aciPutTreasureItem()
void aciPutTreasureItem (void)
 {
     uvsActInt* p;
     if(!GTreasureItem) return;
     p = GTreasureItem;
     while(p){
         aciML_D -> curDataSet -> put_item(p -> type);
         p = (uvsActInt*)p -> next;
     }
 }
References aciML_D, and GTreasureItem.
Referenced by actIntDispatcher::i_init().
aciReadItmText()
void aciReadItmText (void)
 {
     invItem* p;
     p = aciItmTextQueue[aciItmTextQueueCur];
     aciItmTextQueueCur ++;
     if(aciItmTextQueueCur >= aciItmTextQueueSize)
         aciItmTextQueueCur = aciItmTextQueueSize = 0;
     if(p && p -> EvCode)
         aScrDisp -> send_event(p -> EvCode,0,p -> item_ptr);
 }
References aciItmTextQueue, aciItmTextQueueCur, aciItmTextQueueSize, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciRedrawParamsPanel()
void aciRedrawParamsPanel (int x, int y, int sx, int sy)
 {
     int col0,col1;
     InfoPanel* pl = aScrDisp -> get_aci_info_panel(ACI_PARAMS_PANEL);
     if(!pl){
         XGR_Rectangle(x,y,sx,sy,0,0,XGR_FILLED);
         return;
     }
     col0 = (aciCurColorScheme[FM_SELECT_START2] << 8) | aciCurColorScheme[FM_UNSELECT_START];
     col1 = (aciCurColorScheme[FM_SELECT_SIZE2] << 8) | aciCurColorScheme[FM_UNSELECT_SIZE];
     if(aciCurLuck != aciPrevLuck || aciCurDominance != aciPrevDominance){
         pl -> free_list();
         pl -> add_item(aciSTR_LUCK);
         aciXConv -> init();
         *aciXConv <= aciCurLuck;
         if(aciCurLuck < 100)
             pl -> add_item(aciXConv -> address());
         else
             pl -> add_item(aciXConv -> address(),-1,col0 | (col1 << 16));
         pl -> add_item(" ");
         pl -> add_item(aciSTR_DOMINANCE);
         aciXConv -> init();
         *aciXConv <= aciCurDominance;
         if(aciCurDominance < 100)
             pl -> add_item(aciXConv -> address());
         else
             pl -> add_item(aciXConv -> address(),-1,col0 | (col1 << 16));
     }
     pl -> PosX = x;
     pl -> PosY = y;
     pl -> SizeX = sx;
     pl -> SizeY = sy;
     pl -> flags |= IP_NO_REDRAW;
     pl -> redraw();
 }
References ACI_PARAMS_PANEL, aciCurColorScheme, aciCurDominance, aciCurLuck, aciPrevDominance, aciPrevLuck, aciSTR_DOMINANCE, aciSTR_LUCK, aciXConv, aScrDisp, FM_SELECT_SIZE2, FM_SELECT_START2, FM_UNSELECT_SIZE, FM_UNSELECT_START, XGR_FILLED, and XGR_Rectangle.
Referenced by redraw_fnc().
aciRefreshTargetsMenu()
void aciRefreshTargetsMenu (void)
 {
     char* ptr;
     fncMenu* mn;
     mn = aScrDisp -> get_menu(FMENU_TARGETS_MENU);
     if(!mn) return;
     ptr = GetCompasTarget();
     if(ptr)
         mn -> curItem = mn -> get_obj(ptr);
     else
         mn -> curItem = mn -> get_obj(aciSTR_OFF);
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aciSTR_OFF, aScrDisp, FMENU_TARGETS_MENU, GetCompasTarget(), and init_objects().
Referenced by ClearPhantomTarget(), ClearTabutaskTarget(), CreatePhantomTarget(), CreateTabutaskTarget(), DeleteArtefactTarget(), VangerUnit::GamerOrderInit(), and ActionDispatcher::PromptQuant().
aciReInitItem()
int aciReInitItem (actintItemData * p)
 {
     int id;
     invItem* it = aScrDisp -> get_item_ptr(p -> type);
     if(!it) {
         std::cout<<"aciReInitItem !it p:"<<p<<std::endl;
         return 0;
     }
     it -> item_ptr = p;
     p -> actintOwner = it;
     if(it -> slotType != -1){
         id = aScrDisp -> curMatrix -> get_item_slot(it);
         if(id != -1)
             aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,p,id);
     }
     return 1;
 }
References ACI_ACTIVATE_ITEM, aciSendEvent2itmdsp(), aScrDisp, and curMatrix.
Referenced by VangerUnit::Go2World().
aciReInitItemXY()
int aciReInitItemXY (actintItemData * p, int x, int y)
 {
     int id;
     invItem* it = aScrDisp->get_item_ptr_xy(p->type, x, y);
     if(!it) {
         std::cout<<"aciReInitItemXY !it p:"<<p<<std::endl;
         return 0;
     }
     it -> item_ptr = p;
     p -> actintOwner = it;
     if(it -> slotType != -1){
         id = aScrDisp -> curMatrix -> get_item_slot(it);
         if(id != -1)
             aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,p,id);
     }
     return 1;
 }
References ACI_ACTIVATE_ITEM, aciSendEvent2itmdsp(), aScrDisp, curMatrix, actIntDispatcher::get_item_ptr_xy(), and actintItemData::type.
Referenced by VangerUnit::Go2World().
aciRemoveItem()
void aciRemoveItem (actintItemData * d)
 {
     aScrDisp -> remove_item(d);
 }
References aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::DestroyItem(), VangerUnit::DischargeItem(), VangerUnit::Go2Universe(), StuffObject::NetEvent(), StuffObject::NetOwnerQuant(), VangerUnit::OutCarNator(), GunSlot::Quant(), VangerFunctionType::Quant(), and uvsapiDestroyItem().
aciRemoveUvsItem()
void aciRemoveUvsItem (uvsActInt * ptr)
 {
     switch(ptr -> type){
         case ACI_PROTRACTOR:
         case ACI_MECHANIC_MESSIAH:
         case ACI_FUNCTION83:
         case ACI_SPUMMY:
         case ACI_BOOT_SECTOR:
         case ACI_PEELOT:
         case ACI_LEEPURINGA:
         case ACI_SANDOLL_PART1:
         case ACI_SANDOLL_PART2:
         case ACI_LAST_MOGGY_PART1:
         case ACI_LAST_MOGGY_PART2:
         case ACI_QUEEN_FROG_PART1:
         case ACI_QUEEN_FROG_PART2:
         case ACI_LAWN_MOWER_PART1:
         case ACI_LAWN_MOWER_PART2:
         case ACI_WORMASTER_PART1:
         case ACI_WORMASTER_PART2:
         case ACI_PALOCHKA:
         case ACI_PIPKA:
         case ACI_NOBOOL:
         case ACI_BOORAWCHIK:
         case ACI_PEREPONKA:
         case ACI_ZEEFICK:
             return;
         default:
             ptr -> delink(GItem);
             delete ptr;
             break;
     }
 }
References ACI_BOORAWCHIK, ACI_BOOT_SECTOR, ACI_FUNCTION83, ACI_LAST_MOGGY_PART1, ACI_LAST_MOGGY_PART2, ACI_LAWN_MOWER_PART1, ACI_LAWN_MOWER_PART2, ACI_LEEPURINGA, ACI_MECHANIC_MESSIAH, ACI_NOBOOL, ACI_PALOCHKA, ACI_PEELOT, ACI_PEREPONKA, ACI_PIPKA, ACI_PROTRACTOR, ACI_QUEEN_FROG_PART1, ACI_QUEEN_FROG_PART2, ACI_SANDOLL_PART1, ACI_SANDOLL_PART2, ACI_SPUMMY, ACI_WORMASTER_PART1, ACI_WORMASTER_PART2, ACI_ZEEFICK, and GItem.
aciSaveData()
void aciSaveData (void)
 {
     acsSaveData();
 }
References acsSaveData().
aciSaveUVSList()
void aciSaveUVSList (XStream & fh, uvsActInt * p)
 {
     uvsActInt* ptr;
     int i,list_size = 0;
     ptr = p;
     while(ptr){
         list_size ++;
         ptr = (uvsActInt*)ptr -> next;
     }
     ptr = p;
     fh < list_size;
     for(i = 0; i < list_size; i ++){
         ptr -> save(fh);
         ptr = (uvsActInt*)ptr -> next;
     }
 }
aciSell_Item()
void aciSell_Item (invItem * p)
 {
     int cr;
     invItem* it = aScrDisp -> get_iitem(p -> ID);
     uvsActInt* ptr = (uvsActInt*)p -> uvsDataPtr;
     listElem* el = (listElem*)GItem;
     if(!ptr) ErrH.Abort("Bad sell item...");
     ptr -> delink(GGamer);
     ptr -> link(el);
     GItem = (uvsActInt*)el;
     if(!(p -> flags & INV_ITEM_NO_PAY))
         uvsActIntSell(ptr);
     if(!it -> uvsDataPtr && (!aScrDisp -> curLocData -> ExcludeItems[p -> ID] || (p -> flags & INV_ITEM_NO_PAY))){
         it -> uvsDataPtr = ptr;
     }
     if(!(p -> flags & INV_ITEM_NO_PAY)){
         cr = aciGetCurCredits();
         cr += ptr -> sell_price;
         aciUpdateCurCredits(cr);
     }
     aScrDisp -> free_item(p);
 }
References XErrorHandler::Abort(), aScrDisp, ErrH, GGamer, and GItem.
Referenced by aciSell_Matrix(), and actIntDispatcher::i_finit().
aciSell_Matrix()
void aciSell_Matrix (invMatrix * p)
 {
     int cr;
     invItem* itm = (invItem*)p -> items -> last,*itm1;
     uvsActInt* ptr = (uvsActInt*)p -> uvsDataPtr;
     if(!ptr) ErrH.Abort("Bad sell mechos...");
     while(itm){
         itm1 = (invItem*)itm -> prev;
         p -> items -> dconnect((iListElement*)itm);
         aciSell_Item(itm);
         itm = itm1;
     }
     cr = aciGetCurCredits();
     cr += ptr -> sell_price;
     aciUpdateCurCredits(cr);
 }
References XErrorHandler::Abort(), aciGetCurCredits(), aciSell_Item(), aciUpdateCurCredits(), ErrH, and prev.
Referenced by actIntDispatcher::swap_matrices().
aciSellMoveItem()
void aciSellMoveItem (void)
 {
     int i,id,fl = 0,index,exclude = 1;
     invItem* p,*p1;
     invMatrix* m,*m1;
     uvsActInt* u,*pu;
     iListElement* prev_item = iShopItem;
     int change_mode = 0,prev_mode = iEvLineID;
     if(!(aScrDisp -> flags & AS_INV_MOVE_ITEM)) return;
     p = aScrDisp -> curItem;
     p1 = aScrDisp -> get_iitem(p -> ID);
     pu = (uvsActInt*)p -> uvsDataPtr;
     if(!uvsCurrentWorldUnable && p -> partData){
         index = -1;
         m = (invMatrix*)aScrDisp -> i_matrixList -> last;
         while(m){
             for(i = 0; i < 2; i ++){
                 if(m -> uvsDataPtr && m -> type == p -> partData -> baseID[i])
                     index = i;
             }
             m = (invMatrix*)m -> prev;
         }
         if(index != -1)
             fl = 1;
     }
     if(!fl){
         id = p -> ID;
         if(p -> flags & INV_ITEM_NO_PAY) exclude = 0;
         if(p -> classID == AS_ITEM_CLASS && prev_mode != ITEMS_MODE && prev_mode != ITEMS_LIST_MODE){
             change_mode = CHANGE_2_ITEMS_MODE;
             if(iEvLineID != ITEMS_MODE && iEvLineID != ITEMS_LIST_MODE)
                 iEvLineID = change_mode;
         }
         if(p -> classID == AS_WEAPON_CLASS && prev_mode != WEAPONS_MODE && prev_mode != WEAPONS_LIST_MODE){
             change_mode = CHANGE_2_WEAPONS_MODE;
             if(iEvLineID != WEAPONS_MODE && iEvLineID != WEAPONS_LIST_MODE)
                 iEvLineID = change_mode;
         }
         aciSell_Item(p);
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         if(!exclude || !aScrDisp -> curLocData -> ExcludeItems[id]){
             iShopItem = p1;
         }
         else {
             aciRemoveUvsItem(pu);
             iShopItem = prev_item;
             switch(prev_mode){
                 case ITEMS_MODE:
                 case ITEMS_LIST_MODE:
                     change_mode = CHANGE_2_ITEMS_MODE;
                     break;
                 case WEAPONS_MODE:
                 case WEAPONS_LIST_MODE:
                     change_mode = CHANGE_2_WEAPONS_MODE;
                     break;
                 case MECHOS_MODE:
                 case MECHOS_LIST_MODE:
                     change_mode = CHANGE_2_MECHOS_MODE;
                     break;
             }
             iEvLineID = change_mode;
         }
     }
     else {
         m = aScrDisp -> get_imatrix(p -> partData -> baseID[index]);
         m1 = aScrDisp -> get_imatrix(p -> partData -> targetID[index]);
         if(!m || !m1)
             ErrH.Abort("Bad constructor mechos ID...");
         if(m1 -> uvsDataPtr)
             ErrH.Abort("Duplicate constructor mechos...");
         u = (uvsActInt*)m -> uvsDataPtr;
         u -> type = m1 -> type;
         m1 -> uvsDataPtr = u;
         m -> uvsDataPtr = NULL;
         iShopItem = (iListElement*)m1;
         u = (uvsActInt*)p -> uvsDataPtr;
         u -> delink(GGamer);
         delete u;
         p -> uvsDataPtr = NULL;
         if(m1 -> flags & IM_NOT_COMPLETE){
             SOUND_UNICUM_1();
         }
         else {
             SOUND_UNICUM_2();
         }
         iEvLineID = CHANGE_2_MECHOS_MODE;
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
     }
     aciInitAviID();
     restore_mouse_cursor();
     if(aScrDisp -> iscr_iP){
         aScrDisp -> iscr_iP -> free_list();
         aScrDisp -> iscr_iP -> set_redraw();
     }
     if(fl) iEvLineID = CHANGE_2_MECHOS_MODE;
     aciInitShopAvi();
 }
References aScrDisp, iEvLineID, and iShopItem.
Referenced by actIntDispatcher::EventQuant().
aciSendEvent2actint()
void aciSendEvent2actint (int code, actintItemData * p, int data)
 {
     aScrDisp -> send_event(code,data,p);
 }
References aScrDisp.
Referenced by aciSendEvent2itmdsp(), GunSlot::Fire(), VangerUnit::InCarNator(), iScrQuantFinit(), VangerUnit::ItemQuant(), StuffObject::NetOwnerQuant(), VangerUnit::NewKeyHandler(), ItemsDispatcher::Quant(), DoorEngine::Quant(), VangerUnit::SensorQuant(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), and XpeditionOFF().
aciSendPrompt()
void aciSendPrompt (aciPromptData * p)
 {
     aScrDisp -> curPrompt -> copy_data(p);
     aScrDisp -> curPrompt -> CurTimer = 0;
 }
References aScrDisp.
Referenced by aiPromptDominanceMessage(), aiPromptLuckMessage(), aiPromptTaskMessage(), NetCheckRemovePlayer(), and aiMessageType::Send().
aciSet_aMouse()
void aciSet_aMouse (void)
 {
     MouseSizeX = aMouseSizeX;
     MouseSizeY = aMouseSizeY;
     MouseSize = aMouseSize;
     MouseFrames = aMouseFrames;
 }
References aMouseFrames, aMouseSize, aMouseSizeX, aMouseSizeY, MouseFrames, MouseSize, MouseSizeX, and MouseSizeY.
Referenced by actIntDispatcher::i_finit(), and actIntDispatcher::init().
aciSet_iMouse()
void aciSet_iMouse (void)
 {
     MouseSizeX = iMouseSizeX;
     MouseSizeY = iMouseSizeY;
     MouseSize = iMouseSize;
     MouseFrames = iMouseFrames;
 }
References iMouseFrames, iMouseSize, iMouseSizeX, iMouseSizeY, MouseFrames, MouseSize, MouseSizeX, and MouseSizeY.
Referenced by actIntDispatcher::i_init(), and iQuantFirst().
aciSetCameraMenu()
void aciSetCameraMenu (void)
 {
     aciBitmapMenu* m;
     aciBitmapMenuItem* p;
     m = aScrDisp -> get_bmenu(BMENU_CAMERAS_MENU);
     if(m){
         p = (aciBitmapMenuItem*)m -> items -> last;
         while(p){
             switch(p -> ID){
                 case BMENU_ITEM_ROT:
                     p -> curState = camera_rotate_enable;
                     iScrOpt[iCAMERA_TURN]->SetValueINT(camera_rotate_enable);
                     break;
                 case BMENU_ITEM_ZOOM:
                     p -> curState = camera_moving_xy_enable;
                     iScrOpt[iCAMERA_SCALE]->SetValueINT(camera_moving_xy_enable);
                     break;
                 case BMENU_ITEM_PERSP:
                     p -> curState = camera_slope_enable;
                     iScrOpt[iCAMERA_SLOPE]->SetValueINT(camera_slope_enable);
                     break;
             }
             p = (aciBitmapMenuItem*)p -> prev;
         }
     }
     m -> flags |= BM_REBUILD;
     iSaveData();
 }
References aScrDisp, BMENU_CAMERAS_MENU, BMENU_ITEM_PERSP, BMENU_ITEM_ROT, BMENU_ITEM_ZOOM, camera_moving_xy_enable, camera_rotate_enable, camera_slope_enable, iCAMERA_SCALE, iCAMERA_SLOPE, iCAMERA_TURN, iScrOpt, prev, and iScreenOption::SetValueINT().
Referenced by KeyCenter().
aciSetMechName()
void aciSetMechName (void)
 {
     iScreenObject* obj;
     iStringElement* str;
     if(!aScrDisp -> secondMatrix) return;
     obj = (iScreenObject*)aScrDisp -> curLocData -> objList[ACI_MECHOS_ID_OBJ];
     str = (iStringElement*)aScrDisp -> curLocData -> objList[ACI_MECHOS_ID_STR];
     if(!obj || !str) return;
     if(aScrDisp -> secondMatrix -> mech_name)
         strcpy(str -> string,aScrDisp -> secondMatrix -> mech_name);
     else
         strcpy(str -> string," ");
     str -> SizeX = str -> SizeY = 0;
     str -> lX = str -> lY = 0;
     obj -> init();
 }
References ACI_MECHOS_ID_OBJ, ACI_MECHOS_ID_STR, and aScrDisp.
Referenced by actIntDispatcher::EventQuant().
aciSetRedraw()
void aciSetRedraw (void)
 {
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
     aciPrevJumpCount = -1;
 }
References aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), and PassageImageType::Hide().
aciSetShopItem()
void aciSetShopItem (int id)
 {
     invItem* p;
     invMatrix* m;
     if(!iShopItem){
         aciInitEvLineID();
         aciChangeList();
         return;
     }
     switch(iEvLineID){
         case MECHOS_MODE:
         case MECHOS_LIST_MODE:
         case CHANGE_2_MECHOS_MODE:
             m = (invMatrix*)aScrDisp -> i_matrixList -> last;
             while(m){
                 if(m -> type == id){
                     iShopItem = (iListElement*)m;
                     aciCurMechosID = m -> type;
                     break;
                 }
                 m = (invMatrix*)m -> prev;
             }
             if(!m) iShopItem = NULL;
             break;
         case ITEMS_MODE:
         case ITEMS_LIST_MODE:
         case CHANGE_2_ITEMS_MODE:
         case WEAPONS_MODE:
         case WEAPONS_LIST_MODE:
         case CHANGE_2_WEAPONS_MODE:
             p = (invItem*)aScrDisp -> i_itemList -> last;
             while(p){
                 if(p -> ID == id){
                     iShopItem = (iListElement*)p;
                     break;
                 }
                 p = (invItem*)p -> prev;
             }
             if(!p) iShopItem = NULL;
             break;
     }
     aciInitAviID();
 }
References aciChangeList(), aciCurMechosID, aciInitAviID(), aciInitEvLineID(), aScrDisp, CHANGE_2_ITEMS_MODE, CHANGE_2_MECHOS_MODE, CHANGE_2_WEAPONS_MODE, iEvLineID, iShopItem, ITEMS_LIST_MODE, ITEMS_MODE, MECHOS_LIST_MODE, MECHOS_MODE, NULL, prev, WEAPONS_LIST_MODE, and WEAPONS_MODE.
Referenced by actIntDispatcher::iKeyQuant().
aciSetTimePanel()
void aciSetTimePanel (void)
 {
     char* p;
     int d,h,m,s;
     InfoPanel* iPl;
     if(aScrDisp -> flags & AS_ISCREEN)
         iPl = aScrDisp -> get_info_panel(ACI_SHOP_TIME_PANEL);
     else
         iPl = aScrDisp -> get_aci_info_panel(ACI_TIME_PANEL);
     if(!iPl) return;
     ConTimer.sTime.init();
     if(NetworkON){
         GetNetworkGameTime(d,h,m,s);
     }
     else {
         d = ConTimer.day;
         h = ConTimer.hour;
         m = ConTimer.min;
         s = ConTimer.sec;
     }
     if(d < 100) ConTimer.sTime < " ";
     if(d < 10) ConTimer.sTime < " ";
     ConTimer.sTime <= d < " ";
     if(h < 10) ConTimer.sTime < "0";
     ConTimer.sTime <= h < ":";
     if(m < 10) ConTimer.sTime < "0";
     ConTimer.sTime <= m < ":";
     if(s < 10) ConTimer.sTime < "0";
     ConTimer.sTime <= s;
     p = ConTimer.sTime.GetBuf();
     iPl -> free_list();
     iPl -> add_item(aciSTR_DAY);
     iPl -> add_item(p,-1,(aciCurColorScheme[FM_SELECT_BORDER_COL] << 8) | aciCurColorScheme[FM_SELECT_COL]);
     if(aScrDisp -> flags & AS_ISCREEN)
         iPl -> set_redraw();
 }
References aScrDisp, and iPl.
Referenced by actIntDispatcher::EventQuant().
aciShopMenuDown()
void aciShopMenuDown (void)
 {
     fncMenu* mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(mn && mn -> flags & FM_ACTIVE)
         mn -> step_down();
 }
References aScrDisp, and SHOP_ITEMS_MENU_ID.
Referenced by aciNextShopItem().
aciShopMenuUp()
void aciShopMenuUp (void)
 {
     fncMenu* mn = aScrDisp -> get_imenu(SHOP_ITEMS_MENU_ID);
     if(mn && mn -> flags & FM_ACTIVE)
         mn -> step_up();
 }
References aScrDisp, and SHOP_ITEMS_MENU_ID.
Referenced by aciPrevShopItem().
aciShowBlockPhrase()
void aciShowBlockPhrase (void)
 {
     char* str;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p) return;
     str = dgD -> getQblock();
     if(str){
         p -> free_list();
         aciInitPanel(p,(unsigned char*)str);
         p -> set_redraw();
     }
 }
References ACI_ANSWER_PANEL, aciInitPanel(), aScrDisp, and dgD.
Referenced by actIntDispatcher::EventQuant().
aciShowCamerasMenu()
void aciShowCamerasMenu (int x, int y, int sx, int sy)
 {
     aciBitmapMenu* p = aScrDisp -> get_bmenu(BMENU_CAMERAS_MENU);
     if(!p) return;
     if(p -> activeCount){
         p -> curCount --;
         if(p -> curCount <= 0){
             p -> go2upmenu();
             return;
         }
     }
     p -> redraw(x,y,sx,sy);
 }
References aScrDisp, and BMENU_CAMERAS_MENU.
Referenced by redraw_fnc().
aciShowFrags()
void aciShowFrags (void)
 {
     int i,num;
     XBuffer XBuf;
     PlayerData* p;
     char* world_name;
     static int fragColors[10] = { ACI_FRAG_COL0, ACI_FRAG_COL1, ACI_FRAG_COL2, ACI_FRAG_COL3, ACI_FRAG_COL4, ACI_FRAG_COL5, ACI_FRAG_COL6, ACI_FRAG_COL7, ACI_FRAG_COL8, ACI_FRAG_COL9 };
     if(!NetworkON || !players_list.size()) return;
     if(aScrDisp -> curPrompt -> NumStr){
         aScrDisp -> curPrompt -> free_mem();
         return;
     }
     iSortPlayers(1);
     num = iNumPlayers;
     aScrDisp -> curPrompt -> alloc_mem(num);
     aScrDisp -> curPrompt -> CurTimer = 0;
     aScrDisp -> curPrompt -> fontID = ACI_FRAG_FONT;
     switch(iCurMultiGame){
         case 0: // VAN-WAR...
             for(i = 0; i < num; i ++){
                 p = iPlayers[i];
                 XBuf.init();
                 world_name = aScrDisp -> wMap -> world_ptr[aScrDisp -> wMap -> world_ids[p -> body.world]] -> name;
                 XBuf < p -> name < " (" < world_name < ") : " <= p -> body.kills < " " < aciSTR_KILLS < " " <= p -> body.deaths < " " < aciSTR_DEATHS;
                 aScrDisp -> curPrompt -> add_str(i,(unsigned char*)XBuf.address());
                 aScrDisp -> curPrompt -> TimeBuf[i] = ACI_FRAG_TIMER;
                 aScrDisp -> curPrompt -> ColBuf[i] = fragColors[p -> body.color];
             }
             break;
         case 1: // MECHOSOMA...
             for(i = 0; i < num; i ++){
                 p = iPlayers[i];
                 XBuf.init();
                 world_name = aScrDisp -> wMap -> world_ptr[aScrDisp -> wMap -> world_ids[p -> body.world]] -> name;
                 XBuf < p -> name < " (" < world_name < ") : " < aciSTR_Ware1 < " " <= p -> body.MechosomaStat.ItemCount1 < "/" <= my_server_data.Mechosoma.ProductQuantity1;
                 XBuf < " " < aciSTR_Ware2 < " " <= p -> body.MechosomaStat.ItemCount2 < "/" <= my_server_data.Mechosoma.ProductQuantity2;
                 aScrDisp -> curPrompt -> add_str(i,(unsigned char*)XBuf.address());
                 aScrDisp -> curPrompt -> TimeBuf[i] = ACI_FRAG_TIMER;
                 aScrDisp -> curPrompt -> ColBuf[i] = fragColors[p -> body.color];
             }
             break;
         case 2: // PASSEMBLOSS...
             for(i = 0; i < num; i ++){
                 p = iPlayers[i];
                 XBuf.init();
                 world_name = aScrDisp -> wMap -> world_ptr[aScrDisp -> wMap -> world_ids[p -> body.world]] -> name;
                 XBuf < p -> name < " (" < world_name < ") : " < aciSTR_Checkpoints < " " <= p -> body.PassemblossStat.CheckpointLighting < "/" <= my_server_data.Passembloss.CheckpointsNumber;
                 aScrDisp -> curPrompt -> add_str(i,(unsigned char*)XBuf.address());
                 aScrDisp -> curPrompt -> TimeBuf[i] = ACI_FRAG_TIMER;
                 aScrDisp -> curPrompt -> ColBuf[i] = fragColors[p -> body.color];
             }
             break;
     }
 }
References ACI_FRAG_COL0, ACI_FRAG_COL1, ACI_FRAG_COL2, ACI_FRAG_COL3, ACI_FRAG_COL4, ACI_FRAG_COL5, ACI_FRAG_COL6, ACI_FRAG_COL7, ACI_FRAG_COL8, ACI_FRAG_COL9, ACI_FRAG_FONT, ACI_FRAG_TIMER, aciSTR_Checkpoints, aciSTR_DEATHS, aciSTR_KILLS, aciSTR_Ware1, aciSTR_Ware2, XBuffer::address(), aScrDisp, PASSEMBLOSS_PRM::CheckpointsNumber, iCurMultiGame, XBuffer::init(), iNumPlayers, iPlayers, iSortPlayers(), ServerData::Mechosoma, my_server_data, NetworkON, ServerData::Passembloss, players_list, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, XTList< Type >::size(), wMap, and PlayerData::world.
Referenced by actIntDispatcher::KeyQuant().
aciShowRacingPlace()
void aciShowRacingPlace (void)
 {
     int x,y,dx;
     aciXConv -> init();
     *aciXConv < aciCurRaceType < " ";
     if(!(aScrDisp -> flags & AS_FULLSCR)){
         if(actintLowResFlag){
             x = aScrDisp -> curIbs -> PosX + ACI_RACING_X;
             y = aScrDisp -> curIbs -> PosY + ACI_RACING_Y;
         }
         else {
             x = aScrDisp -> curIbs -> PosX + ACI_RACING_X_H;
             y = aScrDisp -> curIbs -> PosY + ACI_RACING_Y_H;
         }
         y = XGR_MAXY - y;
     }
     else {
         if(actintLowResFlag){
             x = ACI_RACING2_X;
             y = ACI_RACING2_Y;
         }
         else {
             x = ACI_RACING2_X_H;
             y = ACI_RACING2_Y_H;
         }
         y = XGR_MAXY - y;
     }
     aOutStr(x,y,ACI_RACING_FONT,ACI_RACING_COL,(unsigned char*)aciXConv -> address(),1);
     dx = aStrLen((unsigned char*)aciXConv -> address(),ACI_RACING_FONT,1);
     aciXConv -> init();
     *aciXConv < aciCurRaceInfo;
     aOutStr(x + dx,y,ACI_RACING_FONT,ACI_RACING_COL2,(unsigned char*)aciXConv -> address(),1);
 }
References aciCurRaceType, aciXConv, and aScrDisp.
Referenced by actIntDispatcher::flush().
aciStartSpeech()
void aciStartSpeech (void)
 {
     aciML_EventSeq* seq;
     int i,unlock_id,prepare2_id,prepare_id,speech_id,end_id,end2_id,lock_id,speech_sz,dropLev = 0;
     InfoPanel* p = aScrDisp -> get_info_panel(ACI_ANSWER_PANEL);
     if(!p) return;
     aciSpeechMode = dgMood;
 #ifdef _ACI_ESCAVE_DEBUG_
     if(aci_dgMoodNext != -1){
         aciSpeechMode = aci_dgMoodNext;
         aci_dgMoodNext = -1;
     }
 #endif
     unlock_id = AML_UNLOCK0_SEQ + aciSpeechMode;
     prepare2_id = AML_PREPARE0_SEQ2 + aciSpeechMode;
     prepare_id = AML_PREPARE0_SEQ + aciSpeechMode;
     speech_id = AML_SPEECH0_SEQ + aciSpeechMode;
     end_id = AML_END0_SEQ + aciSpeechMode;
     end2_id = AML_END0_SEQ2 + aciSpeechMode;
     lock_id = AML_LOCK0_SEQ + aciSpeechMode;
     speech_sz = p -> items -> Size;
     aciSpeechSeq -> size = 0;
     for(i = 0; i < AML_MAX_DROP_EVENT; i ++)
         aciSpeechSeq -> dropLevel[i] = -1;
     if(aciSpeechBegLocked || !aciSpeechStarted){
         seq = aciML_D -> getEventSeq(unlock_id);
         if(seq){
             aciSpeechSeq -> mergeSeq(seq);
             aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
             dropLev ++;
         }
         aciSpeechStarted = 1;
     }
     seq = aciML_D -> getEventSeq(prepare2_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     seq = aciML_D -> getEventSeq(prepare_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     seq = aciML_D -> getEventSeq(speech_id);
     if(seq){
         for(i = 0; i < speech_sz; i ++)
             aciSpeechSeq -> mergeSeq(seq);
     }
     seq = aciML_D -> getEventSeq(end_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     seq = aciML_D -> getEventSeq(end2_id);
     if(seq){
         aciSpeechSeq -> mergeSeq(seq);
         aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
         dropLev ++;
     }
     if(aciSpeechEndLocked){
         seq = aciML_D -> getEventSeq(lock_id);
         if(seq){
             aciSpeechSeq -> mergeSeq(seq);
             aciSpeechSeq -> dropLevel[dropLev] = seq -> dropLevel[0];
             dropLev ++;
         }
     }
     aciSpeechSeq -> ChannelID = aciML_D -> curDataSet -> SpeechChannel;
     aciML_D -> SeqList[0] -> putSeq(aciSpeechSeq);
     aciSpeechBegLocked = aciSpeechEndLocked;
 }
References ACI_ANSWER_PANEL, aciML_D, aciSpeechBegLocked, aciSpeechEndLocked, aciSpeechMode, aciSpeechSeq, aciSpeechStarted, AML_END0_SEQ, AML_END0_SEQ2, AML_LOCK0_SEQ, AML_MAX_DROP_EVENT, AML_PREPARE0_SEQ, AML_PREPARE0_SEQ2, AML_SPEECH0_SEQ, AML_UNLOCK0_SEQ, aScrDisp, and dgMood.
Referenced by aciEscaveKickOut(), and aciNextPhrase().
aciStealItem()
void aciStealItem (int type)
 {
     listElem* el;
     uvsActInt* u;
     invItem* p,*p1;
     if(!GTreasureItem) return;
     u = GTreasureItem;
     while(u){
         if(u -> type == type) break;
         u = (uvsActInt*)u -> next;
     }
     if(!u) return;
     if(u -> type == ACI_BOORAWCHIK) aciEscaveEmpty = 1;
     p = aScrDisp -> get_iitem(u -> type);
     p1 = aScrDisp -> alloc_item();
     p -> clone(p1);
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
         aciSell_Item(aScrDisp -> curItem);
         aScrDisp -> curItem = NULL;
     }
     aScrDisp -> flags |= AS_INV_MOVE_ITEM;
     aScrDisp -> curItem = p1;
     set_mouse_cursor(p1 -> frame,p1 -> ScreenSizeX,p1 -> ScreenSizeY);
     u -> delink(GTreasureItem);
     el = (listElem*)GGamer;
     u -> link(el);
     GGamer = (uvsActInt*)el;
     p1 -> uvsDataPtr = u;
 }
References GTreasureItem.
aciTextQuant()
int aciTextQuant (void)
 {
     int ret = 0;
     ShowImageRTO* p = (ShowImageRTO*)xtGetRuntimeObject(RTO_SHOW_IMAGE_ID);
     if(aciImgText -> flags & ACI_TEXT_INIT){
         ret = 0;
         if(ShowImageMouseFlag || ShowImageKeyFlag){
             if(aciImgText -> flags & ACI_TEXT_END)
                 ret = 1;
             else {
                 aciImgText -> NextPage();
                 if(aciImgText -> flags & ACI_TEXT_END){
                     if(p -> imageData){
                         XGR_PutSpr(0,0,p -> imageSX,p -> imageSY,p -> imageData,XGR_BLACK_FON);
                     }
                     else {
                         XGR_Fill(0);
                     }
                     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
                 }
             }
             ShowImageMouseFlag = ShowImageKeyFlag = 0;
         }
         aciImgText -> Quant();
         if(!(aciImgText -> flags & ACI_TEXT_REDRAW)){
             if(p -> imageData){
                 XGR_PutSpr(0,0,p -> imageSX,p -> imageSY,p -> imageData,XGR_BLACK_FON);
             }
             else {
                 XGR_Fill(0);
             }
             aciImgText -> redraw();
             XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         }
     }
     else {
         if(ShowImageMouseFlag || ShowImageKeyFlag)
                 ret = 1;
     }
     return ret;
 }
References aciImgText, RTO_SHOW_IMAGE_ID, and xtGetRuntimeObject().
Referenced by ShowImageRTO::Quant().
aciUnPackFile()
void aciUnPackFile (char * fname)
 {
     int sz,sz1;
     char* p,*p1;
     XStream fh(fname,XS_IN);
     sz = fh.size();
     p = new char[sz];
     fh.read(p,sz);
     fh.close();
     sz1 = *(unsigned int*)(p + 2) + 12;//ZIP_GetExpandedSize(p);
     p1 = new char[sz1];
     //ZIP_expand(p1,sz1,p,sz);
     /* ZLIB realization (stalkerg)*/
     if(*(short*)(p)) { //if label = 0 not compress
         std::cout<<"aciUnPackFile DeCompress "<<fname<<" file."<<std::endl;
         int stat = uncompress((Bytef*)p1,(uLongf*)&sz1,(Bytef*)(p+2+4),sz-2-4);
         switch(stat){
             //case Z_OK: std::cout<<"DeCompress ok."<<std::endl; break;
             case Z_MEM_ERROR: std::cout<<"DeCompress not enough memory."<<std::endl; break;
             case Z_BUF_ERROR: std::cout<<"DeCompress not enough room in the output buffer."<<std::endl; break;
             case Z_DATA_ERROR: std::cout<<"DeCompress error data."<<std::endl; break;
         };
     } else {
         memcpy(p1, p + 2 + 4,(unsigned)(sz - 2 - 4));
     }
     fh.open(fname,XS_OUT);
     fh.write(p1,sz1);
     fh.close();
     delete[] p;
     delete[] p1;
 }
References XStream::close(), XStream::open(), XStream::read(), XStream::size(), XStream::write(), XS_IN, and XS_OUT.
aciVMapPrepare()
void aciVMapPrepare (void)
 {
     aScrDisp -> curLocData -> init_map_data();
 }
References aScrDisp.
Referenced by iSecondInit().
aciWaitNextPeriod()
void aciWaitNextPeriod (void)
 {
     int w_id = aScrDisp -> wMap -> world_ptr[aScrDisp -> curLocData -> WorldID] -> uvsID;
     WaitGameInTown(w_id);
 }
References aScrDisp, WaitGameInTown(), and wMap.
Referenced by dg_SendEvent().
aciWorldExploredInfo()
void aciWorldExploredInfo (void)
 {
     int i;
     aciWorldInfo* p1;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p1 = aScrDisp -> wMap -> world_ptr[i];
         if(p1 && uvsReturnWorldGamerVisit(p1 -> uvsID)){
             p1 -> flags |= AS_EXPLORED_WORLD;
         }
     }
 }
References AS_MAX_WORLD, aScrDisp, uvsReturnWorldGamerVisit(), and wMap.
Referenced by aciWorldMap::build_map().
aciWorldLinkExist()
int aciWorldLinkExist (int w1, int w2, int sp_flag)
 {
     int id1,id2;
     aciWorldInfo* p1,*p2;
     id1 = aScrDisp -> wMap -> world_ids[w1];
     id2 = aScrDisp -> wMap -> world_ids[w2];
     if(id1 == -1 || id2 == -1) ErrH.Abort("Bad world ID...");
     p1 = aScrDisp -> wMap -> world_ptr[id1];
     p2 = aScrDisp -> wMap -> world_ptr[id2];
     if(!p1 || !p2) ErrH.Abort("Bad world ptr...");
     if(p1 -> links[id2] || p2 -> links[id1]){
         if(!sp_flag || (p1 -> flags & AS_ACCESSIBLE_WORLD || p2 -> flags & AS_ACCESSIBLE_WORLD)){
             return 1;
         }
     }
     return 0;
 }
References XErrorHandler::Abort(), aScrDisp, ErrH, and wMap.
Referenced by aiMessageTouch(), ItemsDispatcher::Close(), uvsTabuTaskType::is_able(), ActionDispatcher::PromptQuant(), VangerUnit::SensorQuant(), and uvsSecretON().
aciWorldLinksOFF()
void aciWorldLinksOFF (void)
 {
     int i;
     aciWorldInfo* p;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p = aScrDisp -> wMap -> world_ptr[i];
         if(p){
             p -> flags &= ~AS_ACCESSIBLE_WORLD;
         }
     }
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
 }
References AS_MAX_WORLD, aScrDisp, and wMap.
Referenced by aciWorldMap::quant().
aciWorldLinksON()
void aciWorldLinksON (void)
 {
     int i,cur_id;
     aciWorldInfo* p,*p1;
     if(CurrentWorld == -1) return;
     cur_id = aScrDisp -> wMap -> world_ids[CurrentWorld];
     if(cur_id == -1) return;
     p = aScrDisp -> wMap -> world_ptr[cur_id];
     if(!p) return;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p1 = aScrDisp -> wMap -> world_ptr[i];
         if(i != cur_id && p1){
             if(p1 -> links[cur_id] || p -> links[i]){
                 p1 -> flags |= AS_ACCESSIBLE_WORLD;
             }
         }
         if(p1 && uvsReturnWorldGamerVisit(p1 -> uvsID)){
             p1 -> flags |= AS_EXPLORED_WORLD;
         }
     }
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
 }
References AS_MAX_WORLD, aScrDisp, CurrentWorld, and wMap.
Referenced by aciWorldMap::quant(), and VangerUnit::TouchSensor().
acsChangeStrState()
void acsChangeStrState (int id)
 {
     aciScreenInputField* p = (aciScreenInputField*)acsScrD -> GetObject(id);
     if(p) p -> change_state();
 }
References acsScrD.
Referenced by aciScreenDispatcher::FlushEvents().
acsCompressData()
void acsCompressData (char * p)
 {
     int len,time_len,flags,sz,data;
     unsigned long dest_sz, src_sz;
     XStream fh;
     char* header,*src_buf,*dest_buf;
     fh.open(p,XS_IN);
     sz = fh.size();
     fh > len;
     time_len = (len >> 16) & 0xFF;
     flags = (len >> 24) & 0xFF;
     len &= 0xFF;
     if(flags & ACI_SAVE_COMPRESSED){
         fh.close();
         return;
     }
     dest_sz = src_sz = sz - time_len - len - sizeof(int);
     dest_sz*=2;
     header = new char[len + time_len];
     src_buf = new char[src_sz];
     dest_buf = new char[dest_sz];
     fh.read(header,len + time_len);
     fh.read(src_buf,src_sz);
     fh.close();
     //std::cout<<"compress src_sz:"<<src_sz<<std::endl;
     //dest_sz = ZIP_compress(dest_buf,src_sz,src_buf,src_sz);
     /* ZLIB realization (stalkerg)*/
     dest_buf[0] = (char)(8 & 0xFF); //8 it is DEFLATE method
     dest_buf[1] = (char)((8 >> 8) & 0xFF);
     *(unsigned int*)(dest_buf + 2) = (unsigned int)src_sz;
     dest_sz-=2+4;
     int stat = compress((Bytef*)(dest_buf+2+4),(uLongf*)&(dest_sz),(Bytef*)src_buf,src_sz);
     dest_sz+=2+4;
     switch(stat){
         //case Z_OK: std::cout<<"Compress ok."<<std::endl; break;
         case Z_MEM_ERROR: std::cout<<"not enough memory."<<std::endl; break;
         case Z_BUF_ERROR: std::cout<<"not enough room in the output buffer."<<std::endl; break;
     };
     //std::cout<<"compress dest_sz:"<<dest_sz<<std::endl;
     flags |= ACI_SAVE_COMPRESSED;
     data = len | ((time_len | (flags << 8)) << 16);
     fh.open(p,XS_OUT);
     fh < data;
     fh.write(header,len + time_len);
     fh.write(dest_buf,dest_sz);
     fh.close();
     delete[] header;
     delete[] src_buf;
     delete[] dest_buf;
 }
acsDecompressData()
void acsDecompressData (char * p)
 {
     int len,time_len,flags,sz,data;
     XStream fh;
     unsigned long dest_sz, src_sz;
     char* header,*src_buf,*dest_buf;
     fh.open(p,XS_IN);
     sz = fh.size();
     fh > len;
     time_len = (len >> 16) & 0xFF;
     flags = (len >> 24) & 0xFF;
     len &= 0xFF;
     if(!(flags & ACI_SAVE_COMPRESSED)){
         fh.close();
         return;
     }
     src_sz = sz - time_len - len - sizeof(int);
     header = new char[len + time_len];
     src_buf = new char[src_sz];
     fh.read(header,len + time_len);
     fh.read(src_buf,src_sz);
     fh.close();
     //dest_sz = ZIP_GetExpandedSize(src_buf);
     dest_sz = *(unsigned int*)(src_buf + 2) + 12; //+12 for size need for zlib
     dest_buf = new char[dest_sz];
     //ZIP_expand(dest_buf,dest_sz,src_buf,src_sz);
     /* ZLIB realisation (stalkerg)*/
     if(*(short*)(src_buf)) { //if label = 0 not compress
         //std::cout<<"acsDecompressData DeCompress "<<p<<" file."<<std::endl;
         int stat = uncompress((Bytef*)dest_buf,(uLongf*)&dest_sz,(Bytef*)(src_buf+2+4),src_sz-2-4);
         switch(stat){
             //case Z_OK: std::cout<<"DeCompress ok."<<std::endl; break;
             case Z_MEM_ERROR: std::cout<<"not enough memory."<<std::endl; break;
             case Z_BUF_ERROR: std::cout<<"not enough room in the output buffer."<<std::endl; break;
             case Z_DATA_ERROR: std::cout<<"error data."<<std::endl; break;
         };
     } else {
         memcpy(dest_buf,src_buf + 2 + 4,(unsigned)(src_sz - 2 - 4));
     }
     flags &= ~ACI_SAVE_COMPRESSED;
     data = len | ((time_len | (flags << 8)) << 16);
     fh.open(p,XS_OUT);
     fh < data;
     fh.write(header,len + time_len);
     fh.write(dest_buf,dest_sz);
     fh.close();
     delete[] header;
     delete[] src_buf;
     delete[] dest_buf;
 }
Referenced by acsLoadData().
acsGetStrState()
int acsGetStrState (int id)
 {
     aciScreenInputField* p = (aciScreenInputField*)acsScrD -> GetObject(id);
     if(p) return p -> get_state();
     return 0;
 }
References acsScrD.
acsHandleExtEvent()
void acsHandleExtEvent (int code, int data0 = 0, int data1 = 0, int data2 = 0)
 {
     int val,max_val,i_val,i_max_val;
     switch(code){
         case ACS_GLOBAL_EXIT:
             if(!(aScrDisp -> flags & AS_ISCREEN))
                 GameQuantReturnValue = RTO_LOADING3_ID;
             else {
                 iScrDisp -> flags |= SD_EXIT;
                 iScrExitCode = 1;
                 iAbortGameFlag = 1;
             }
             if(NetworkON) iMultiFlag = 1;
             acsScrD -> QuantCode = 1; // resume game pause
             if(!GameOverID)
                 GameOverID = GAME_OVER_ABORT;
             break;
         case ACS_INIT_TUTORIAL_MODE:
             acsSetStrState(ACS_TUTORIAL_MODE,!iGetOptionValue(iTUTORIAL_ON));
             break;
         case ACS_SET_TUTORIAL_MODE:
             iSetOptionValue(iTUTORIAL_ON,!acsGetStrState(ACS_TUTORIAL_MODE));
             iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
             break;
         case ACS_SET_AUTORUN_MODE:
             aciAutoRun = acsGetStrState(ACS_AUTORUN_MODE);
             iScrOpt[iAUTO_ACCELERATION]->SetValueINT(acsGetStrState(ACS_AUTORUN_MODE));
             break;
         case ACS_SET_SOUND_MODE:
             iSetOptionValue(iSOUND_ON,!acsGetStrState(ACS_SOUND_MODE));
             iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
             break;
         case ACS_SET_MUSIC_MODE:
             iSetOptionValue(iMUSIC_ON,!acsGetStrState(ACS_MUSIC_MODE));
             iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
             break;
         case ACS_INIT_AUTORUN_MODE:
 //          acsSetStrState(ACS_AUTORUN_MODE,aciAutoRun);
             aciAutoRun = iGetOptionValue(iAUTO_ACCELERATION);
             acsSetStrState(ACS_AUTORUN_MODE,iGetOptionValue(iAUTO_ACCELERATION));
             break;
         case ACS_INIT_SOUND_MODE:
             acsSetStrState(ACS_SOUND_MODE,!iGetOptionValue(iSOUND_ON));
             break;
         case ACS_INIT_SOUND_VOLUME:
             acsScrD -> SetScroller(ACS_SOUND_VOLUME,iGetOptionValue(iSOUND_VOLUME_CUR),iGetOptionValue(iSOUND_VOLUME_MAX));
             break;
         case ACS_SET_SOUND_VOLUME:
             val = acsScrD -> GetObjectValue(ACS_SOUND_VOLUME);
             max_val = acsScrD -> GetObjectValue(ACS_SOUND_VOLUME,1);
             i_max_val = iGetOptionValue(iSOUND_VOLUME_MAX);
             i_val = (val * i_max_val) / max_val;
             iSetOptionValue(iSOUND_VOLUME_CUR,i_val);
             iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
             break;
         case ACS_INIT_MUSIC_MODE:
             acsSetStrState(ACS_MUSIC_MODE,!iGetOptionValue(iMUSIC_ON));
             break;
         case ACS_INIT_MUSIC_VOLUME:
             acsScrD -> SetScroller(ACS_MUSIC_VOLUME,iGetOptionValue(iMUSIC_VOLUME_CUR),iGetOptionValue(iMUSIC_VOLUME_MAX));
             break;
         case ACS_SET_MUSIC_VOLUME:
             val = acsScrD -> GetObjectValue(ACS_MUSIC_VOLUME);
             max_val = acsScrD -> GetObjectValue(ACS_MUSIC_VOLUME,1);
             i_max_val = iGetOptionValue(iMUSIC_VOLUME_MAX);
             i_val = (val * i_max_val) / max_val;
             iSetOptionValue(iMUSIC_VOLUME_CUR,i_val);
             iHandleExtEvent(iEXT_UPDATE_MUSIC_VOLUME);
             break;
         case ACS_CHANGE_MUSIC_MODE:
             acsChangeStrState(ACS_MUSIC_MODE);
             iSetOptionValue(iMUSIC_ON,!acsGetStrState(ACS_MUSIC_MODE));
             iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
             break;
         case ACS_CHANGE_AUTORUN_MODE:
             acsChangeStrState(ACS_AUTORUN_MODE);
             aciAutoRun = acsGetStrState(ACS_AUTORUN_MODE);
             iScrOpt[iAUTO_ACCELERATION]->SetValueINT(acsGetStrState(ACS_AUTORUN_MODE));
             break;
         case ACS_CHANGE_SOUND_MODE:
             acsChangeStrState(ACS_SOUND_MODE);
             iSetOptionValue(iSOUND_ON,!acsGetStrState(ACS_SOUND_MODE));
             iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
             break;
         case ACS_CHANGE_TUTORIAL_MODE:
             acsChangeStrState(ACS_TUTORIAL_MODE);
             iSetOptionValue(iTUTORIAL_ON,!acsGetStrState(ACS_TUTORIAL_MODE));
             iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
             break;
         case ACS_INIT_SLOT_NAME:
             acsPrepareSlotName(data0,data1);
             break;
         case ACS_INIT_SLOT_NAME_INPUT:
             acsPrepareSlotNameInput(data0,data1);
             break;
         case ACS_SAVE_GAME:
             acsSaveData();
             break;
     }
 }
References ACS_GLOBAL_EXIT, and aScrDisp.
Referenced by actIntDispatcher::flush(), and aciScreenDispatcher::FlushEvents().
acsLoadData()
void acsLoadData (void)
 {
     int slot = iSlotNumber,len,time_len;
     XBuffer XBuf;
     XStream fh;
     if(slot != -1){
         XBuf < "savegame/save";
         if(slot < 10) XBuf < "0";
         XBuf <= slot < ".dat";
 #ifdef _ACI_PACK_SAVES_
         acsDecompressData(XBuf.address());
 #endif
         std::cout<<"acsLoadData"<<std::endl;
         fh.open(XBuf.address(),XS_IN);
         fh > len;
         time_len = (len >> 16) & 0xFF;
         len &= 0xFF;
         fh.seek(len + sizeof(int) + time_len,XS_BEG);
         uniVangLoad(fh);
         aciLoadUVSList(fh,&GItem,1);
         aciLoadUVSList(fh,&GMechos);
         aciLoadUVSList(fh,&GGamer,1);
         aciLoadUVSList(fh,&GGamerMechos);
         aciLoadUVSList(fh,&GCharItem,1);
         aciLoadUVSList(fh,&GTreasureItem,1);
         aScrDisp->load_data(&fh);
         //stalkerg
         //     ,
         if(aScrDisp->curMatrix) { //
             listElem *el = NULL;
             listElem *el2 = NULL;
             uvsActInt *new_item = NULL;
             uvsActInt *iter_gamer = (uvsActInt*)GGamer;
             invItem* p,*p1;
             while (iter_gamer) {
                 bool item_detect = false;
                 int i, j, index = 0;
                 for(i = 0; i < aScrDisp->curMatrix->SizeY; i++){
                     for(j = 0; j < aScrDisp->curMatrix->SizeX; j++){
                         invMatrixCell *cell = aScrDisp->curMatrix->matrix[index];
                         /*std::cout<<"GGamer type:"<<iter_gamer->type
                             <<" x:"<<iter_gamer->pos_x
                             <<" y:"<<iter_gamer->pos_y
                             <<" i:"<<i
                             <<" j:"<<j
                             <<" mcell flags:"<<cell->flags
                             <<" mcell type:"<<cell->type
                             <<" index:"<<index<<std::endl;*/
                         if(cell->flags & AS_BUSY_CELL && cell->item) {
                             /*std::cout<<"item_type:"<<cell->item->ID
                                 <<" MX:"<<cell->item->MatrixX
                                 <<" MY:"<<cell->item->MatrixY<<std::endl;*/
                             if (cell->item->ID == iter_gamer->type &&
                                 cell->item->MatrixX == iter_gamer->pos_x &&
                                 cell->item->MatrixY == iter_gamer->pos_y
                             ) {
                                 item_detect = true;
                                 goto end_find;
                             }
                         }
                         index++;
                     }
                 }
                 std::cout<<"Can't find item GGamer type:"<<iter_gamer->type
                         <<" pos_x:"<<iter_gamer->pos_x
                         <<" pos_y:"<<iter_gamer->pos_y
                         <<" and we make it"<<std::endl;
                 if(aScrDisp->flags & AS_ISCREEN)
                     p = aScrDisp->get_iitem(iter_gamer->type);
                 else
                     p = aScrDisp->get_item(iter_gamer->type);
                 p1 = aScrDisp->alloc_item();
                 p->clone(p1);
                 aScrDisp->curMatrix->put_item(iter_gamer->pos_x, iter_gamer->pos_y, p1, 1);
                 end_find:
                 //Is it duplicate?
                 if (el != NULL) {
                     el2 = el;
                     while (el2) {
                         uvsActInt *item = dynamic_cast<uvsActInt*> (el2);
                         if (item->pos_x == iter_gamer->pos_x && item->pos_y == iter_gamer->pos_y && item->type == iter_gamer->type) {
                             std::cout<<"We find duplicate item GGamer type:"<<iter_gamer->type
                                 <<" pos_x:"<<iter_gamer->pos_x
                                 <<" pos_y:"<<iter_gamer->pos_y
                                 <<std::endl;
                             goto next;
                         }
                         el2 = el2->next;
                     }
                 }
                 new_item = new uvsActInt;
                 new_item->pos_x = iter_gamer->pos_x;
                 new_item->pos_y = iter_gamer->pos_y;
                 new_item->type = iter_gamer->type;
                 new_item->price = iter_gamer->price;
                 new_item->sell_price = iter_gamer->sell_price;
                 new_item->param1 = iter_gamer->param1;
                 new_item->param2 = iter_gamer->param2;
                 new_item->link(el);
                 next:
                 iter_gamer = (uvsActInt*)iter_gamer->next;
             }
             aciFreeUVSList(GGamer);
             GGamer = (uvsActInt*)el;
         }
         GeneralSystemLoad(fh);
         dgD -> load(fh);
         fh.close();
 #ifdef _ACI_PACK_SAVES_
         acsCompressData(XBuf.address());
 #endif
     }
 }
References aciLoadUVSList(), acsDecompressData(), XBuffer::address(), actIntDispatcher::alloc_item(), AS_BUSY_CELL, AS_ISCREEN, aScrDisp, invItem::clone(), actIntDispatcher::curMatrix, invMatrixCell::flags, actIntDispatcher::flags, GCharItem, actIntDispatcher::get_iitem(), actIntDispatcher::get_item(), GGamer, GGamerMechos, GItem, GMechos, GTreasureItem, invItem::ID, iSlotNumber, invMatrixCell::item, actIntDispatcher::load_data(), invMatrix::matrix, invItem::MatrixX, invItem::MatrixY, NULL, XStream::open(), uvsActInt::pos_x, uvsActInt::pos_y, invMatrix::put_item(), XStream::seek(), invMatrix::SizeX, invMatrix::SizeY, uvsActInt::type, uniVangLoad(), XS_BEG, and XS_IN.
Referenced by aciLoadData().
acsParseScript()
void acsParseScript (const char * fname, char * bname = NULL)
 {
     int id,num = 0;
     acsScrD = new aciScreenDispatcher;
 #ifndef _BINARY_SCRIPT_
     _sALLOC_HEAP_(ACS_SCRIPT_SIZE,char);
 #endif
     script = new ScriptFile;
 #ifndef _BINARY_SCRIPT_
     script -> set_bscript_name(bname);
 #endif
     script -> load(fname);
     script -> prepare();
     while(!script -> EOF_Flag){
 #ifndef _BINARY_SCRIPT_
         if(script -> curBlock && *script -> curBlock -> data){
 #endif
             id = script -> read_option(-1);
 #ifndef _BINARY_SCRIPT_
             if(id == -1)
                 handle_error("Unknown keyword",script -> prevStrBuf);
 #else
             if(id == iSCRIPT_EOF) script -> EOF_Flag = 1;
             if(id == -1)
                 handle_error("Unknown keyword",NULL);
 #endif
             switch(id){
                 case ACS_END_BLOCK:
                     acsEndScriptBlock();
                     break;
                 case ACS_END_STRING:
                     break;
                 case ACS_NEW_RESOURCE:
                     if(acsScriptMode != ACS_NONE && acsScriptMode != ACS_INIT_SCREEN)
                         handle_error("Misplaced option",acsOptIDs[id]);
                     acsEndBlockMode = acsScriptMode;
                     acsScriptMode = ACS_INIT_RESOURCE;
                     num = script -> read_idata();
                     acsRes = acsAllocResource(num);
                     if(!acsRes) ErrH.Abort("Bad resource type...");
                     break;
                 case ACS_NEW_COMMAND:
                     if(acsScriptMode != ACS_INIT_EVENT)
                         handle_error("Misplaced option",acsOptIDs[id]);
                     acsScriptMode = ACS_INIT_COMMAND;
                     acsEvComm = new aciScreenEventCommand;
                     break;
                 case ACS_NEW_EVENT:
                     if(acsScriptMode != ACS_INIT_OBJECT && acsScriptMode != ACS_INIT_SCREEN)
                         handle_error("Misplaced option",acsOptIDs[id]);
                     acsEndBlockMode = acsScriptMode;
                     acsScriptMode = ACS_INIT_EVENT;
                     acsEv = new aciScreenEvent;
                     break;
                 case ACS_NEW_FRAME_SEQ:
                     if(acsScriptMode != ACS_INIT_OBJECT)
                         handle_error("Misplaced option",acsOptIDs[id]);
                     acsScriptMode = ACS_INIT_FRAME_SEQ;
                     acsFrameSeq = new aciScreenFrameSequence;
                     break;
                 case ACS_NEW_OBJECT:
                     if(acsScriptMode != ACS_INIT_SCREEN)
                         handle_error("Misplaced option",acsOptIDs[id]);
                     acsScriptMode = ACS_INIT_OBJECT;
                     acsObj = acsAllocObject(script -> read_idata());
                     break;
                 case ACS_NEW_SCREEN:
                     if(acsScriptMode != ACS_NONE)
                         handle_error("Misplaced option",acsOptIDs[id]);
                     acsScriptMode = ACS_INIT_SCREEN;
                     acsScr = new aciScreen;
                     break;
                 case ACS_SET_ID:
                     if(acsScriptMode == ACS_INIT_RESOURCE){
                         acsRes -> ID = script -> read_idata();
                     }
                     else {
                         if(acsScriptMode == ACS_INIT_FRAME_SEQ){
                             acsFrameSeq -> ID = script -> read_idata();
                         }
                         else {
                             if(acsScriptMode == ACS_INIT_OBJECT){
                                 acsObj -> ID = script -> read_idata();
                             }
                             else {
                                 if(acsScriptMode == ACS_INIT_SCREEN){
                                     acsScr -> ID = script -> read_idata();
                                 }
                                 else {
                                     handle_error("Misplaced option",acsOptIDs[id]);
                                 }
                             }
                         }
                     }
                     break;
                 case ACS_SET_FNAME:
                     if(acsScriptMode == ACS_INIT_RESOURCE){
                         script -> prepare_pdata();
                         acsRes -> set_name(script -> get_conv_ptr());
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_BUILD:
                     if(acsScriptMode == ACS_INIT_RESOURCE){
                         acsRes -> flags |= ACS_BUILD_RESOURCE;
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_OFFS_X:
                     if(acsScriptMode == ACS_INIT_RESOURCE && acsRes -> type == ACS_BMO){
                         ((aciScreenResourceBMO*)acsRes) -> OffsX = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_OFFS_Y:
                     if(acsScriptMode == ACS_INIT_RESOURCE && acsRes -> type == ACS_BMO){
                         ((aciScreenResourceBMO*)acsRes) -> OffsY = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_SZ_X:
                     if(acsScriptMode == ACS_INIT_RESOURCE && acsRes -> type == ACS_BMO){
                         ((aciScreenResourceBMO*)acsRes) -> SizeX = script -> read_idata();
                     }
                     else {
                         if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                             ((aciScreenScroller*)acsObj) -> SizeX = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_SZ_Y:
                     if(acsScriptMode == ACS_INIT_RESOURCE && acsRes -> type == ACS_BMO){
                         ((aciScreenResourceBMO*)acsRes) -> SizeY = script -> read_idata();
                     }
                     else {
                         if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                             ((aciScreenScroller*)acsObj) -> SizeY = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_EVENT:
                     if(acsScriptMode == ACS_INIT_COMMAND){
                         acsEvComm -> code = script -> read_idata();
                         for(num = 0; num < 4; num ++)
                             acsEvComm -> data[num] = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_START_TIMER:
                     if(acsScriptMode == ACS_INIT_COMMAND){
                         acsEvComm -> StartTimer = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_MAX_TIMER:
                     if(acsScriptMode == ACS_INIT_EVENT){
                         acsEv -> MaxTimer = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_ADD_KEY:
                     if(acsScriptMode == ACS_INIT_EVENT){
                         acsEv -> AddKey(script -> read_key());
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_RESOURCE_ID:
                     if(acsScriptMode == ACS_INIT_FRAME_SEQ){
                         acsFrameSeq -> ResourceID = script -> read_idata();
                     }
                     else {
                         if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                             ((aciScreenScroller*)acsObj) -> ScrResID = script -> read_idata();
                         }
                         else {
                             handle_error("Misplaced option",acsOptIDs[id]);
                         }
                     }
                     break;
                 case ACS_SET_SEQ:
                     if(acsScriptMode == ACS_INIT_FRAME_SEQ){
                         acsFrameSeq -> StartFrame = script -> read_idata();
                         acsFrameSeq -> EndFrame = script -> read_idata();
                         acsFrameSeq -> FrameDelta = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_POS_X:
                     if(acsScriptMode == ACS_INIT_OBJECT){
                         acsObj -> PosX = script -> read_idata();
                     }
                     else {
                         if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                             ((aciScreenScroller*)acsObj) -> PosX = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_POS_Y:
                     if(acsScriptMode == ACS_INIT_OBJECT){
                         acsObj -> PosY = script -> read_idata();
                     }
                     else {
                         if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                             ((aciScreenScroller*)acsObj) -> PosY = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_MAX_VALUE:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                         ((aciScreenScroller*)acsObj) -> MaxValue = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_ACTIVE_SX:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                         ((aciScreenScroller*)acsObj) -> ActiveSX = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_ACTIVE_SY:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                         ((aciScreenScroller*)acsObj) -> ActiveSY = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_SECOND_RES:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                         ((aciScreenScroller*)acsObj) -> sResID = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_COLORS:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                         ((aciScreenScroller*)acsObj) -> Color = script -> read_idata();
                         ((aciScreenScroller*)acsObj) -> BackColor = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_STRING_LEN:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_INPUT_FIELD_OBJ){
                         ((aciScreenInputField*)acsObj) -> MaxStrLen = script -> read_idata();
                         ((aciScreenInputField*)acsObj) -> alloc_str();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_FONT:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_INPUT_FIELD_OBJ){
                         ((aciScreenInputField*)acsObj) -> font = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_CENTER:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_INPUT_FIELD_OBJ){
                         acsObj -> flags |= ACS_ALIGN_CENTER;
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_COLOR:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_INPUT_FIELD_OBJ){
                         num = script -> read_idata();
                         if(num == 0) ((aciScreenInputField*)acsObj) -> Color0 = script -> read_idata();
                         if(num == 1) ((aciScreenInputField*)acsObj) -> Color1 = script -> read_idata();
                         if(num == 2) ((aciScreenInputField*)acsObj) -> Color2 = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_STRING:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_INPUT_FIELD_OBJ){
                         script -> prepare_pdata();
                         ((aciScreenInputField*)acsObj) -> set_string(script -> get_conv_ptr());
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_IFONT:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_INPUT_FIELD_OBJ){
                         ((aciScreenInputField*)acsObj) -> font = script -> read_idata();
                         ((aciScreenInputField*)acsObj) -> flags |= ACS_ISCREEN_FONT;
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_SPACE:
                     if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_INPUT_FIELD_OBJ){
                         ((aciScreenInputField*)acsObj) -> Space = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
                 case ACS_SET_BACK_ID:
                     if(acsScriptMode == ACS_INIT_SCREEN){
                         acsScr -> backResID = script -> read_idata();
                     }
                     else {
                         if(acsScriptMode == ACS_INIT_OBJECT && acsObj -> type == ACS_SCROLLER_OBJ){
                             ((aciScreenScroller*)acsObj) -> flags |= ACS_BACK_RES;
                         }
                         else
                             handle_error("Misplaced option",acsOptIDs[id]);
                     }
                     break;
             }
 #ifndef _BINARY_SCRIPT_
         }
         else
             script -> next_ptr();
 #endif
     }
 #ifdef _SAVE_BINARY_SCRIPT_
     script -> close_bscript();
 #endif
     delete script;
 #ifndef _BINARY_SCRIPT_
     _sFREE_HEAP_(ACS_SCRIPT_SIZE,char);
 #endif
 }
References _sALLOC_HEAP_, ACS_END_BLOCK, ACS_END_STRING, ACS_INIT_SCREEN, ACS_NEW_RESOURCE, ACS_NONE, ACS_SCRIPT_SIZE, acsEndScriptBlock(), acsScrD, acsScriptMode, handle_error(), iSCRIPT_EOF, NULL, and script.
acsPrepareSlotName()
void acsPrepareSlotName (int id, int slot_num)
 {
     int len,time_len;
     XBuffer XBuf;
     XStream fh(0);
     aciScreenInputField* p = (aciScreenInputField*)acsScrD -> GetObject(id);
     if(!p) return;
     XBuf.init();
     XBuf < "savegame/save";
     if(slot_num < 10) XBuf < "0";
     XBuf <= slot_num < ".dat";
     if(fh.open(XBuf.address(),XS_IN)){
         fh > len;
         time_len = (len >> 16) & 0xFF;
         len &= 0xFF;
         memset(p -> string,0,p -> MaxStrLen + 2);
         fh.read(p -> string,len);
         fh.close();
     }
     else
         strcpy(p -> string,aciSTR_EMPTY_SLOT);
 }
References aciSTR_EMPTY_SLOT, acsScrD, XBuffer::address(), XStream::close(), XBuffer::init(), XStream::open(), XStream::read(), and XS_IN.
acsPrepareSlotNameInput()
void acsPrepareSlotNameInput (int id, int slot_num)
 {
     int sz;
     aciScreenInputField* p = (aciScreenInputField*)acsScrD -> GetObject(id);
     if(!p) return;
     if(acsScrD -> activeInput){
         acsScrD -> activeInput -> StopEvents();
         acsScrD -> CancelInput();
     }
     if(!strcmp(p -> string,aciSTR_EMPTY_SLOT) || !strcmp(p -> string,aciSTR_UNNAMED_SAVE)){
         sz = strlen(p -> string) + 1;
         acsBackupStr = new char[sz];
         strcpy(acsBackupStr,p -> string);
         memset(p -> string,0,p -> MaxStrLen + 2);
     }
     acsCurrentSlotID = id;
     acsCurrentSlotNum = slot_num;
 }
References aciSTR_EMPTY_SLOT, aciSTR_UNNAMED_SAVE, acsBackupStr, acsCurrentSlotID, acsCurrentSlotNum, and acsScrD.
acsQuant()
int acsQuant (void)
 {
     int ret,k,firstQuant = 0;
     if(!acsAllocFlag){
         acsAllocFlag = 1;
         if(NetworkON) aciKeyboardLocked = 1;
         acsScrD -> curScrID = acsScreenID;
         acsScrD -> QuantCode = 0;
         XGR_MouseObj.DisablePrompt();
         XGR_MouseShow();
         acsScrD -> alloc_mem();
         if(XGR_MAXX == 800 && !(aScrDisp -> flags & AS_ISCREEN))
             acsScrD -> curScr -> ChangeCoords((800 - 640)/2,(600 - 480)/2);
         EffectsOff();
         firstQuant = 1;
         if(acsScrD -> curScrID >= 3){
             aciCloseGate();
             acsScrD -> Quant(0);
             aciOpenGate();
         }
         KeyBuf -> clear();
     }
     while(KeyBuf->size){
         SDL_Event *e = KeyBuf->get();
         if (e->type == SDL_KEYDOWN) {
             k = sdlEventToCode(e);
         }
         if (e->type == SDL_KEYDOWN || e->type == SDL_TEXTINPUT) {
             acsScrD->KeyTrap(0, e);
             if (e->key.keysym.scancode == SDL_SCANCODE_ESCAPE && !acsScrD -> QuantCode) {
                 acsScrD -> QuantCode = 1;
             }
         }
     }
     if(aScrDisp -> flags & aMS_MOVED){
         acsScrD -> KeyTrap(iMOUSE_MOVE_CODE, nullptr);
         aScrDisp -> flags ^= aMS_MOVED;
         if(aciMouseFlagL){
             acsScrD -> KeyTrap(iMOUSE_LEFT_MOVE, nullptr);
         }
         if(aciMouseFlagR){
             acsScrD -> KeyTrap(iMOUSE_RIGHT_MOVE, nullptr);
         }
     }
     if(aScrDisp -> flags & aMS_LEFT_PRESS){
         acsScrD -> KeyTrap(iMOUSE_LEFT_PRESS_CODE, nullptr);
         aScrDisp -> flags ^= aMS_LEFT_PRESS;
     }
     if(aScrDisp -> flags & aMS_RIGHT_PRESS){
         acsScrD -> KeyTrap(iMOUSE_RIGHT_PRESS_CODE, nullptr);
         aScrDisp -> flags ^= aMS_RIGHT_PRESS;
     }
     if(NetworkON){
         acsScrD -> flags |= ACS_FORCED_REDRAW;
         ret = acsScrD -> Quant(actIntLog);
     }
     else
         ret = acsScrD -> Quant();
     if(firstQuant){
         acsPrepareSlotNameInput(acsCurrentSlotID,acsCurrentSlotNum);
         acsScrD -> PrepareInput(acsCurrentSlotID);
     }
     if(ret){
         acsAllocFlag = 0;
         if(XGR_MAXX == 800 && !(aScrDisp -> flags & AS_ISCREEN))
             acsScrD -> curScr -> ChangeCoords(-(800 - 640)/2,-(600 - 480)/2);
         acsScrD -> free_mem();
         if(aScrDisp -> flags & AS_FULLSCR && !(aScrDisp -> flags & AS_ISCREEN)){
             XGR_MouseHide();
         }
         else
             aScrDisp -> flags &= ~AS_FULL_REDRAW;
         iScrDisp -> flags &= ~MS_LEFT_PRESS;
         iScrDisp -> flags &= ~MS_RIGHT_PRESS;
         iScrDisp -> flags &= ~MS_MOVED;
         iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
         iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
         iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
         if(NetworkON) aciKeyboardLocked = 0;
         acsScreenID = 1;
         iSaveData();
         KeyBuf -> clear();
         return 1;
     }
     return 0;
 }
References aciKeyboardLocked, acsAllocFlag, acsScrD, acsScreenID, aScrDisp, XGR_Mouse::DisablePrompt(), NetworkON, XGR_MAXX, XGR_MouseObj, and XGR_MouseShow.
Referenced by actIntDispatcher::flush(), and GameQuantRTO::Quant().
acsSaveData()
void acsSaveData (void)
 {
     int i,null_flag = 1;
     int slot = acsCurrentSlotNum,len,time_len;
     XBuffer XBuf;
     XStream fh;
     XStream fh2;
     fh2.open("tmp_f1.txt",XS_OUT);
     fh2<14<40;
     fh2.close();
     const char* ptr = NULL;
     aciScreenInputField* p;
     if(aciAutoSaveFlag){
         ptr = aciSTR_AUTOSAVE;
         slot = ACS_NUM_SLOTS;
     }
     else {
         if(acsScrD -> activeInput) acsScrD -> DoneInput();
         p = (aciScreenInputField*)acsScrD -> GetObject(acsCurrentSlotID);
         ptr = p -> string;
     }
     if(slot != -1 && ptr){
         XBuf < "savegame/save";
         if(slot < 10) XBuf < "0";
         XBuf <= slot < ".dat";
         len = strlen(ptr);
         for(i = 0; i < len; i ++){
             if(ptr[i] && ptr[i] != ' ')
                 null_flag = 0;
         }
         if(null_flag){
             ptr = aciSTR_UNNAMED_SAVE;
             len = strlen(ptr);
         }
         if(aScrDisp -> flags & AS_INV_MOVE_ITEM && aScrDisp -> curItem -> uvsDataPtr){
             ((uvsActInt*)aScrDisp -> curItem -> uvsDataPtr) -> pos_x = aScrDisp -> curItem -> MatrixX = -1;
             ((uvsActInt*)aScrDisp -> curItem -> uvsDataPtr) -> pos_y = aScrDisp -> curItem -> MatrixY = -1;
         }
         fh.open(XBuf.address(),XS_OUT);
         aciXConv -> init();
         *aciXConv < aScrDisp -> curLocData -> nameID2 < ", ";
         *aciXConv <= ConTimer.day < ":";
         if(ConTimer.hour < 10) *aciXConv < "0";
         *aciXConv <= ConTimer.hour < ":";
         if(ConTimer.min < 10) *aciXConv < "0";
         *aciXConv <= ConTimer.min < ":";
         if(ConTimer.sec < 10) *aciXConv < "0";
         *aciXConv <= ConTimer.sec;
         time_len = aciXConv -> tell();
         fh < (len | (time_len << 16));
         fh.write(ptr,len);
         fh.write(aciXConv -> address(),time_len);
         CurrentWorld = prevWorld;
         uniVangSave(fh);
         aciSaveUVSList(fh,GItem);
         aciSaveUVSList(fh,GMechos);
         aciSaveUVSList(fh,GGamer);
         aciSaveUVSList(fh,GGamerMechos);
         aciSaveUVSList(fh,GCharItem);
         aciSaveUVSList(fh,GTreasureItem);
         aScrDisp -> save_data(&fh);
         GeneralSystemSave(fh);
         dgD -> save(fh);
         CurrentWorld = -1;
         fh.close();
 #ifdef _ACI_PACK_SAVES_
         acsCompressData(XBuf.address());
 #endif
     }
     aciAutoSaveFlag = 0;
 }
References aciAutoSaveFlag, aciSTR_AUTOSAVE, aciSTR_UNNAMED_SAVE, ACS_NUM_SLOTS, acsCurrentSlotID, acsCurrentSlotNum, acsScrD, aScrDisp, XStream::close(), NULL, XStream::open(), and XS_OUT.
Referenced by aciAutoSave(), and aciSaveData().
acsSetStrState()
void acsSetStrState (int id, int state)
 {
     aciScreenInputField* p = (aciScreenInputField*)acsScrD -> GetObject(id);
     if(p) p -> set_state(state);
 }
References acsScrD.
actIntQuant()
void actIntQuant (void)
 {
     actintActiveFlag = 1;
     aScrDisp -> KeyQuant();
     aScrDisp -> EventQuant();
     /*             .*/
     aScrDisp -> redraw();
 }
References actintActiveFlag, and aScrDisp.
Referenced by iGameMap::draw().
aFreeFonts()
void aFreeFonts (void)
 {
     int i;
     for(i = 0; i < AS_NUM_FONTS; i ++){
         delete aScrFonts[i];
     }
     delete aScrFonts;
     aScrFonts = NULL;
 /*
     for(i = 0; i < AS_NUM_FONTS_32; i ++){
         delete aScrFonts32[i];
     }
     delete aScrFonts32;
     aScrFonts32 = NULL;
 */
 }
References AS_NUM_FONTS, aScrFonts, and NULL.
aInit()
void aInit (void)
 {
     GameOverID = 0;
     aciInitStrings();
     if(!aIndArrowBML){
         aIndArrowBML = new bmlObject;
         aIndArrowBML -> flags |= BML_NO_OFFSETS;
         if(actintLowResFlag)
             aIndArrowBML -> load("resource/actint/640x480/ind_data/arrow.bml");
         else
             aIndArrowBML -> load("resource/actint/800x600/ind_data/arrow.bml");
     }
     if(!aIndDataBML){
         aIndDataBML = new bmlObject;
         aIndDataBML -> flags |= BML_NO_OFFSETS;
         if(actintLowResFlag)
             aIndDataBML -> load("resource/actint/640x480/ind_data/data.bml");
         else
             aIndDataBML -> load("resource/actint/800x600/ind_data/data.bml");
     }
     if(!aIndBackBML){
         aIndBackBML = new bmlObject;
         aIndBackBML -> flags |= BMP_FLAG;
         if(actintLowResFlag)
             aIndBackBML -> load("resource/actint/640x480/ind_data/back.bmp");
         else
             aIndBackBML -> load("resource/actint/800x600/ind_data/back.bmp");
     }
     if(!aciSpeechSeq){
         aciSpeechSeq = new aciML_EventSeq;
         aciSpeechSeq -> alloc_mem(256);
     }
     if(!aciCurRaceType)
             aciCurRaceType = new char[10];
     if(!aciCurRaceInfo)
             aciCurRaceInfo = new char[10];
     if(!aciTreeData){
         aciTreeData = new aciCHTree;
         aciTreeData -> load("resource/iscreen/ldata/l7/border.xbm");
     }
 #ifdef _BINARY_SCRIPT_
     if(actintLowResFlag){
         if(lang() == RUSSIAN){
             aParseScript("resource/actint/aci_low2.scb");
             acsParseScript("resource/actint/acs_low2.scb");
         }
         else {
             aParseScript("resource/actint/aci_low.scb");
             acsParseScript("resource/actint/acs_low.scb");
         }
     }
     else {
         if(lang() == RUSSIAN){
             aParseScript("resource/actint/aci_hi2.scb");
             acsParseScript("resource/actint/acs_low2.scb");
         }
         else {
             aParseScript("resource/actint/aci_hi.scb");
             acsParseScript("resource/actint/acs_low.scb");
         }
     }
 #else
     if(actintLowResFlag){
         if(lang() == RUSSIAN){
             aParseScript("actint/aci_low2.scr","resource/actint/aci_low2.scb");
             acsParseScript("actint/acs_low2.scr","resource/actint/acs_low2.scb");
         }
         else {
             aParseScript("actint/aci_low.scr","resource/actint/aci_low.scb");
             acsParseScript("actint/acs_low.scr","resource/actint/acs_low.scb");
         }
     }
     else {
         if(lang() == RUSSIAN){
             aParseScript("actint/aci_hi2.scr","resource/actint/aci_hi2.scb");
             acsParseScript("actint/acs_low2.scr","resource/actint/acs_low2.scb");
         }
         else {
             aParseScript("actint/aci_hi.scr","resource/actint/aci_hi.scb");
             acsParseScript("actint/acs_low.scr","resource/actint/acs_low.scb");
         }
     }
 #endif
     a_calc_tables();
     if(!NetworkON){
         aciUpdateCurCredits(ACI_STARTUP_CREDITS + beebos);
     }
     else {
         aciDisableParametersMenu();
     }
 #ifdef _ACI_LOGFILE_
     aScrDisp -> logFile.open(aciLogFileName,XS_OUT);
     aScrDisp -> logFile < "actIntDispatcher Log File...\r\n";
     aScrDisp -> logFile.close();
 #endif
     curMatrixID = 0;
     aciXConv = new XBuffer;
     aciInitWorldIDs();
     aLoadFonts();
     aScrDisp -> init_prompt();
     aScrDisp -> init();
     aInitFlag = 1;
     aMS_init();
 #ifdef _GENERATE_MATRIX_SHAPES_
     invMatrix* p = (invMatrix*)aScrDisp -> matrixList -> last;
     while(p){
         p -> generate_shape();
         p -> generate_floor();
         p = (invMatrix*)p -> prev;
     }
 #ifdef _GENERATE_EXIT_
     ErrH.Abort("Done...");
 #endif
 #endif
 #ifdef _GENERATE_iMATRIX_SHAPES_
     aci_CellSize = aCellSize;
     aCellSize = iCellSize;
     build_cell_frame();
     invMatrix* p = (invMatrix*)aScrDisp -> i_matrixList -> last;
     while(p){
         p -> generate_shape();
         p -> generate_floor();
         p = (invMatrix*)p -> prev;
     }
     aCellSize = aci_CellSize;
     build_cell_frame();
 #ifdef _GENERATE_EXIT_
     ErrH.Abort("Done...");
 #endif
 #endif
     actIntPal = new unsigned char[768];
     if(!aciItmTextQueue) aciItmTextQueue = new invItem*[ACI_ITEM_QUEUE_MAX];
 #ifdef _FULLSCREEN_MODE_
     aScrDisp -> send_event(EV_FULLSCR_CHANGE);
 #endif
 /*
 #ifdef _GENERATE_ITEM_DATA_
     aScrDisp -> save_items();
 #ifdef _GENERATE_EXIT_
     ErrH.Abort("Done...");
 #endif
 #endif
 */
 #ifdef _ACTINT_MEMSTAT_
     aciDetectLeaks();
     aMemStatFile.close();
 #endif
 }
References aciInitStrings(), aIndArrowBML, and GameOverID.
Referenced by LoadingRTO1::Init().
aKeyInit()
void aKeyInit (void)
 {
     loadMouseFrames();
     KeyBuf = new KeyBuffer;
     set_mouse();
 }
References KeyBuf, loadMouseFrames(), and set_mouse().
Referenced by LoadingRTO1::Init().
aKeyQuant()
void aKeyQuant (void)
 {
     aScrDisp -> KeyQuant();
 }
References aScrDisp.
aKeyTrap()
void aKeyTrap (SDL_Event * k)
 {
     if(aInitFlag){
         KeyBuf -> put(k,CUR_KEY_PRESSED);
     }
 }
References aInitFlag, CUR_KEY_PRESSED, and KeyBuf.
Referenced by KeyCenter().
aLoadFonts()
void aLoadFonts (void)
 {
     int i;
     XBuffer XBuf;
     XStream fh;
 #ifdef _ACI_BML_FONTS_
     if(!aScrFonts)
         aScrFonts = new aciFont*[AS_NUM_FONTS];
 #else
     int sz;
     char* buf;
     if(!aScrFonts)
         aScrFonts = new iScreenFont*[AS_NUM_FONTS];
 #endif
     for(i = 0; i < AS_NUM_FONTS; i ++){
         XBuf.init();
         XBuf < "resource/actint/fonts/sfont";
         if(i < 10)
             XBuf < "0";
 #ifdef _ACI_BML_FONTS_
         XBuf <= i < ".bml";
         aScrFonts[i] = new aciFont;
         aScrFonts[i] -> load(XBuf.GetBuf());
         aScrFonts[i] -> calc_offs();
 #else
         XBuf <= i < ".fnt";
         fh.open(XBuf,XS_IN);
         sz = fh.size();
         buf = new char[sz];
         fh.read(buf,sz);
         fh.close();
         aScrFonts[i] = new iScreenFont(buf,sz);
 #endif
     }
 }
References AS_NUM_FONTS, aScrFonts, XStream::close(), XBuffer::GetBuf(), XBuffer::init(), XStream::open(), XStream::read(), XStream::size(), and XS_IN.
aLoadFonts32()
void aLoadFonts32 (void)
 {
     int i;
     XBuffer XBuf;
     XStream fh;
     if(!aScrFonts32)
         aScrFonts32 = new aciFont*[AS_NUM_FONTS_32];
     for(i = 0; i < AS_NUM_FONTS_32; i ++){
         XBuf.init();
         XBuf < "resource/actint/fonts/cfont";
         if(i < 10)
             XBuf < "0";
         XBuf <= i < ".bml";
         aScrFonts32[i] = new aciFont;
         aScrFonts32[i] -> flags |= ACI_RANGE_FONT;
         aScrFonts32[i] -> load(XBuf.GetBuf());
         aScrFonts32[i] -> calc_offs();
     }
     XGR_SetTextOutFnc(aOutText32);
     XGR_SetTextXFnc(aTextWidth32);
     XGR_SetTextYFnc(aTextHeight32);
 }
References AS_NUM_FONTS_32, aScrFonts32, and XBuffer::init().
Referenced by iInit(), and MainMenuRTO::Init().
aMS_init()
void aMS_init (void)
 {
     XGR_MouseSetPressHandler(XGM_LEFT_BUTTON,aMS_LeftPress);
     XGR_MouseSetUnPressHandler(XGM_LEFT_BUTTON,aMS_LeftUnpress);
     XGR_MouseSetPressHandler(XGM_RIGHT_BUTTON,aMS_RightPress);
     XGR_MouseSetUnPressHandler(XGM_RIGHT_BUTTON,aMS_RightUnpress);
     XGR_MouseSetMoveHandler(aMS_Movement);
     aciMouseFlagL = aciMouseFlagR = 0;
 }
References aciMouseFlagL, aciMouseFlagR, aMS_LeftPress(), aMS_LeftUnpress(), aMS_Movement(), aMS_RightPress(), aMS_RightUnpress(), XGM_LEFT_BUTTON, XGM_RIGHT_BUTTON, XGR_MouseSetMoveHandler, XGR_MouseSetPressHandler, and XGR_MouseSetUnPressHandler.
Referenced by actIntDispatcher::i_finit().
aMS_LeftPress()
void aMS_LeftPress (int fl, int x, int y)
 {
     if (aScrDisp==NULL) {
         return;
     }
     aScrDisp -> flags |= aMS_LEFT_PRESS;
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagL = 1;
     XGR_MouseSetSeq(0,1,XGM_PLAY_ONCE,1);
 }
References aScrDisp, and NULL.
Referenced by aMS_init().
aMS_LeftUnpress()
void aMS_LeftUnpress (int fl, int x, int y)
 {
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagL = 0;
     XGR_MouseSetSeq(XGR_MouseCurFrame,XGR_MouseNumFrames - 1,XGM_PLAY_ONCE,1);
 }
References aciMouseFlagL, iMouseX, iMouseY, XGM_PLAY_ONCE, XGR_MouseCurFrame, XGR_MouseNumFrames, and XGR_MouseSetSeq.
Referenced by aMS_init(), and iMS_LeftUnpress().
aMS_Movement()
void aMS_Movement (int fl, int x, int y)
 {
     if (aScrDisp==NULL) {
         return;
     }
     aScrDisp -> flags |= aMS_MOVED;
     iMouseX = x;
     iMouseY = y;
 }
References aScrDisp, and NULL.
Referenced by aMS_init().
aMS_RightPress()
void aMS_RightPress (int fl, int x, int y)
 {
     if (aScrDisp==NULL) {
         return;
     }
     aScrDisp -> flags |= aMS_RIGHT_PRESS;
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagR = 1;
     XGR_MouseSetSeq(0,1,XGM_PLAY_ONCE,1);
 }
References aScrDisp, and NULL.
Referenced by aMS_init().
aMS_RightUnpress()
void aMS_RightUnpress (int fl, int x, int y)
 {
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagR = 0;
     XGR_MouseSetSeq(XGR_MouseCurFrame,XGR_MouseNumFrames - 1,XGM_PLAY_ONCE,1);
 }
References aciMouseFlagR, iMouseX, iMouseY, XGM_PLAY_ONCE, XGR_MouseCurFrame, XGR_MouseNumFrames, and XGR_MouseSetSeq.
Referenced by aMS_init(), and iMS_RightUnpress().
aOutStr()
void aOutStr (int x, int y, int font, int color, unsigned char * str, int space)
 {
     int i,j,s,xs,ys,offs = 0,sz = strlen((char*)str),X = 0,Y = 0,col1,col2;
     unsigned char* palBuf = palbuf;
     col1 = color & ACI_COLOR_MASK;
     col2 = (color >> 8) & ACI_COLOR_MASK;
     if(aScrFonts[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     unsigned char* p = aScrFonts[font] -> data;
     xs = aScrFonts[font] -> SizeX;
     ys = aScrFonts[font] -> SizeY;
     X = x;
     if(col2){
         for(s = 0; s < sz; s ++){
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             for(i = 0; i < ys; i ++){
                 Y = y + i;
                 for(j = 0; j < xs; j ++){
                     switch(p[offs + j]){
                         case 1:
                             XGR_SetPixel(X + j,Y,col1);
                             break;
                         case 2:
                             XGR_SetPixel(X + j,Y,col2);
                             break;
                     }
                 }
                 offs += xs;
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
     else {
         for(s = 0; s < sz; s ++){
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             for(i = 0; i < ys; i ++){
                 Y = y + i;
                 for(j = 0; j < xs; j ++){
                     switch(p[offs + j]){
                         case 1:
                             XGR_SetPixel(X + j,Y,col1);
                             break;
                     }
                 }
                 offs += xs;
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
 }
References XErrorHandler::Abort(), ACI_COLOR_MASK, aScrFonts, ErrH, NULL, palbuf, and XGR_SetPixel.
Referenced by aWriteHelpString(), and aciScreenInputField::redraw().
aOutText32()
void aOutText32 (int x, int y, int color, void * text, int font, int hspace, int vspace)
 {
     int s,xs,ys,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     int color_size,chr;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     color_size = (color >> 16) & 0xFF;
     color &= 0xFFFF;
     unsigned char* p = aScrFonts32[font] -> data;
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     X = x;
     Y = y;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 X -= aScrFonts32[font] -> LeftOffs[chr];
                 offs = xs * ys * chr;
                 aciPutSpr32(X,Y,xs,ys,p + offs,color,color_size);
                 X += xs + hspace - aScrFonts32[font] -> RightOffs[chr];
             }
         }
         else {
             X = x;
             Y += ys + vspace;
         }
     }
 }
References XErrorHandler::Abort(), aciPutSpr32(), aScrFonts32, ErrH, and NULL.
Referenced by iChatInputField::redraw(), iChatHistoryScreen::redraw(), and iChatButton::redraw().
aOutText32clip()
void aOutText32clip (int x, int y, int color, void * text, int font, int hspace, int vspace)
 {
     int s,xs,ys,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     int color_size,chr;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     color_size = (color >> 16) & 0xFF;
     color &= 0xFFFF;
     unsigned char* p = aScrFonts32[font] -> data;
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     X = x;
     Y = y;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 X -= aScrFonts32[font] -> LeftOffs[chr];
                 offs = xs * ys * chr;
                 aciPutSpr32clip(X,Y,xs,ys,p + offs,color,color_size);
                 X += xs + hspace - aScrFonts32[font] -> RightOffs[chr];
             }
         }
         else {
             X = x;
             Y += ys + vspace;
         }
     }
 }
References XErrorHandler::Abort(), aciPutSpr32clip(), aScrFonts32, ErrH, and NULL.
Referenced by VangerUnit::DrawQuant().
aParseScript()
void aParseScript (const char * fname, char * bname = NULL)
 {
     int i,id,t_id = 0,sz = 0,num;
     char* ptr;
     iListElement* elemPtr;
     invMatrix* mtx;
     invItem* itm;
     aScrDisp = new actIntDispatcher;
     aciML_D = new aciML_Dispatcher;
 #ifndef _BINARY_SCRIPT_
     _sALLOC_HEAP_(3000000,char);
 #endif
     script = new ScriptFile;
 #ifndef _BINARY_SCRIPT_
     script -> set_bscript_name(bname);
 #endif
     script -> load(fname);
     script -> prepare();
     while(!script -> EOF_Flag){
 #ifndef _BINARY_SCRIPT_
         if(script -> curBlock && *script -> curBlock -> data){
 #endif
             id = script -> read_option(0);
 #ifndef _BINARY_SCRIPT_
             if(id == -1)
                 handle_error("Unknown keyword",script -> prevStrBuf);
 #else
             if(id == iSCRIPT_EOF) script -> EOF_Flag = 1;
             if(id == -1)
                 handle_error("Unknown keyword",NULL);
 #endif
             switch(id){
                 case INIT_MECHOS_PRM:
                     t_id = script -> read_idata();
                     t_id = script -> read_idata();
                     mtx = aScrDisp -> get_imatrix(t_id);
                     if(mtx){
                         t_id = script -> read_idata();
                         if(!mtx -> pData) mtx -> alloc_prm();
                         ptr = mtx -> pData + t_id * ACI_MAX_PRM_LEN;
                         script -> read_pdata(&ptr);
                     }
                     else
                         handle_error("Bad matrix ID");
                     break;
                 case INIT_ITEM_PRM:
                     t_id = script -> read_idata();
                     itm = aScrDisp -> get_iitem(t_id);
                     if(itm){
                         t_id = script -> read_idata();
                         if(!itm -> pData) itm -> alloc_prm();
                         ptr = itm -> pData + t_id * ACI_MAX_PRM_LEN;
                         script -> read_pdata(&ptr);
                     }
                     else
                         handle_error("Bad item ID");
                     break;
                 case SET_PROMPT_TEXT:
                     if(curMode == AS_INIT_BUTTON){
                         script -> read_pdata(&aBt -> promptData,1);
                     }
                     else {
                         if(curMode == AS_INIT_IND){
                             script -> read_pdata(&aInd -> promptData,1);
                         }
                         else {
                             if(curMode == AS_INIT_ITEM){
                                 script -> read_pdata(&invItm -> promptData,1);
                             }
                             else
                                 handle_error("Misplaced option",aOptIDs[id]);
                         }
                     }
                     break;
                 case INIT_NUM_GATE_SHUTTERS:
                     if(curMode == AS_INIT_LOC_DATA){
                         t_id = script -> read_idata();
                         locData -> alloc_gate_shutters(t_id);
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case ADD_MAP_INFO_FILE:
                     if(curMode == AS_INIT_LOC_DATA){
                         script -> prepare_pdata();
                         elemPtr = new iListElement;
                         elemPtr -> init_id(script -> get_conv_ptr());
                         locData -> mapData -> connect(elemPtr);
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_SOUND_PATH:
                     if(curMode == AS_INIT_LOC_DATA){
                         script -> read_pdata(&locData -> soundResPath,1);
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_NUM_MATRIX_SHUTTERS:
                     if(curMode == AS_INIT_LOC_DATA){
                         t_id = script -> read_idata();
                         sz = script -> read_idata();
                         locData -> alloc_matrix_shutters(t_id,sz);
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_SHUTTER_POS:
                     if(curMode == AS_INIT_SHUTTER){
                         t_id = script -> read_idata();
                         locSh -> Pos[t_id].X = script -> read_idata();
                         locSh -> Pos[t_id].Y = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_SHUTTER_DELTA:
                     if(curMode == AS_INIT_SHUTTER){
                         locSh -> Delta.X = script -> read_idata();
                         locSh -> Delta.Y = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case NEW_GATE_SHUTTER:
                     if(curMode == AS_INIT_LOC_DATA){
                         curMode = AS_INIT_SHUTTER;
                         locSh = new aciLocationShutterInfo;
                         t_id = script -> read_idata();
                         if(t_id < 0 || t_id >= locData -> numGateShutters) ErrH.Abort("Bad shutter index...");
                         locData -> GateShutters[t_id] = locSh;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case NEW_MATRIX_SHUTTER:
                     if(curMode == AS_INIT_LOC_DATA){
                         curMode = AS_INIT_SHUTTER;
                         t_id = script -> read_idata();
                         sz = script -> read_idata();
                         locSh = new aciLocationShutterInfo;
                         if(t_id == 1) num = locData -> numMatrixShutters1;
                         else num = locData -> numMatrixShutters2;
                         if(sz < 0 || sz >= num)
                             ErrH.Abort("Bad shutter index...");
                         if(t_id == 1)
                             locData -> MatrixShutters1[sz] = locSh;
                         else
                             locData -> MatrixShutters2[sz] = locSh;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_STARTUP_TIME:
                     aciML_D -> startup_timer = script -> read_idata();
                     break;
                 case SET_UPMENU_FLAG:
                     upMenuFlag = 1;
                     break;
                 case INIT_SHUTDOWN_TIME:
                     aciML_D -> shutdown_timer = script -> read_idata();
                     break;
                 case NEW_ML_EVENT_COMMAND:
                     if(curMode != AML_INIT_EVENT)
                         handle_error("Misplaced option",aOptIDs[id]);
                     mlEvComm = new aciML_EventCommand;
                     curMode = AML_INIT_EVENT_COMMAND;
                     break;
                 case NEW_ML_EVENT:
                     if(curMode != AML_INIT_DATA)
                         handle_error("Misplaced option",aOptIDs[id]);
                     mlEv = new aciML_Event;
                     curMode = AML_INIT_EVENT;
                     break;
                 case NEW_ML_DATA:
                     if(curMode != AML_INIT_DATA_SET)
                         handle_error("Misplaced option",aOptIDs[id]);
                     mlData = new aciML_Data;
                     curMode = AML_INIT_DATA;
                     break;
                 case NEW_ML_EVENT_SEQ:
                     if(curMode != AML_INIT_DATA_SET)
                         handle_error("Misplaced option",aOptIDs[id]);
                     mlEvSeq = new aciML_EventSeq;
                     mlEvSeq -> ID = script -> read_idata();
                     mlEvSeq -> size = script -> read_idata();
                     mlEvSeq -> alloc_mem(mlEvSeq -> size);
                     curMode = AML_INIT_EVENT_SEQ;
                     break;
                 case NEW_BITMAP_MENU:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     aciBM = new aciBitmapMenu;
                     curMode = BM_INIT_MENU;
                     break;
                 case NEW_BITMAP_MENU_ITEM:
                     if(curMode != BM_INIT_MENU)
                         handle_error("Misplaced option",aOptIDs[id]);
                     aciBM_it = new aciBitmapMenuItem;
                     curMode = BM_INIT_MENU_ITEM;
                     break;
                 case NEW_ML_DATA_SET:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     mlDataSet = new aciML_DataSet;
                     curMode = AML_INIT_DATA_SET;
                     break;
                 case NEW_ML_ITEM_DATA:
                     if(curMode != AML_INIT_DATA_SET)
                         handle_error("Misplaced option",aOptIDs[id]);
                     mlItm = new aciML_ItemData;
                     mlItm -> ItemID = script -> read_idata();
                     mlItm -> NullLevel = script -> read_idata();
                     script -> read_pdata(&mlItm -> frameName,1);
                     mlDataSet -> add_item(mlItm);
                     break;
                 case INIT_ML_EVENT_KEY_CODE:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> keys -> add_key(script -> read_idata());
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_RND_VALUE:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> rndValue = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_SPEECH_CHANNEL:
                     if(curMode == AML_INIT_DATA_SET){
                         mlDataSet -> SpeechChannel = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_FRAME_CHECK_FLAG:
                     if(curMode == AML_INIT_DATA){
                         mlData -> flags |= AML_FRAME_CHECK;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_SPEECH_LEVEL:
                     if(curMode == AML_INIT_DATA_SET){
                         t_id = script -> read_idata();
                         mlDataSet -> SpeechPriority[t_id] = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_ML_EVENT_SEQUENCE:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> flags |= AML_SEQUENCE_EVENT;
                     }
                     else {
                         if(curMode == AML_INIT_EVENT_SEQ){
                             for(t_id = 0; t_id < mlEvSeq -> size; t_id ++){
                                 mlEvSeq -> SeqIDs[t_id] = script -> read_idata();
                                 mlEvSeq -> SeqModes[t_id] = script -> read_idata();
                             }
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_ML_EVENT_CODE:
                     if(curMode == AML_INIT_EVENT_COMMAND){
                         mlEvComm -> code = script -> read_idata();
                         mlEvComm -> data0 = script -> read_idata();
                         mlEvComm -> data1 = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_ML_EVENT_STARTUP:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> startupType = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_PRIORITY:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> priority = script -> read_idata();
                     }
                     else {
                         if(curMode == AML_INIT_EVENT_SEQ){
                             mlEvSeq -> dropLevel[0] = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_NOT_LOCKED_FLAG:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> flags |= AML_IF_NOT_LOCKED;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_LOCKED_FLAG:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> flags |= AML_IF_LOCKED;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_START_TIMER:
                     if(curMode == AML_INIT_EVENT_COMMAND){
                         mlEvComm -> start_timer = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_CHANNEL_ID:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> ChannelID = script -> read_idata();
                     }
                     else {
                         if(curMode == AML_INIT_DATA){
                             mlData -> ChannelID = script -> read_idata();
                         }
                         else {
                             if(curMode == AML_INIT_EVENT_SEQ){
                                 mlEvSeq -> ChannelID = script -> read_idata();
                             }
                             else
                                 handle_error("Misplaced option",aOptIDs[id]);
                         }
                     }
                     break;
                 case INIT_ML_EVENT_SDATA:
                     if(curMode == AML_INIT_EVENT){
                         mlEv -> data = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_OFFS_X:
                     if(curMode == AS_INIT_WORLD_MAP){
                         t_id = script -> read_idata();
                         wMap -> ShapeOffsX[t_id] = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_IBS){
                             t_id = script -> read_idata();
                             ibsObj -> indPosX[t_id] = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_WORLD_NAME:
                     if(curMode == AS_INIT_WORLD_DATA){
                         script -> read_pdata(&wData -> name,1);
                     }
                     else {
                         if(curMode == AML_INIT_DATA){
                             script -> read_pdata(&mlData -> name,1);
                         }
                         else {
                             if(curMode == AS_INIT_LOC_DATA){
                                 script -> read_pdata(&locData -> nameID,1);
                                 script -> read_pdata(&locData -> nameID2,1);
                             }
                             else {
                                 if(curMode == AS_INIT_SHUTTER){
                                     script -> read_pdata(&locSh -> name,1);
                                 }
                                 else
                                     handle_error("Misplaced option",aOptIDs[id]);
                             }
                         }
                     }
                     break;
                 case ADD_FLAG:
                     if(curMode == AS_INIT_WORLD_DATA){
                         t_id = script -> read_idata();
                         wData -> flags |= t_id;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case ADD_LINK:
                     if(curMode == AS_INIT_WORLD_DATA){
                         t_id = script -> read_idata();
                         wData -> links[t_id] = 1;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_MAX_STR:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> MaxStr = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_INFO_OFFS_X:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> OffsX = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_BACK_COL:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> bCol = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_MENU){
                             fnMnu -> bCol = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_RANGE_FLAG:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> flags |= IP_RANGE_FONT;
                     }
                     else {
                         if(curMode == AS_INIT_MENU){
                             fnMnu -> flags |= FM_RANGE_FONT;
                         }
                         else {
                             if(curMode == AS_INIT_COUNTER){
                                 cP -> flags |= CP_RANGE_FONT;
                             }
                             else
                                 handle_error("Misplaced option",aOptIDs[id]);
                         }
                     }
                     break;
                 case SET_SUBMENU_FLAG:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> flags |= FM_SUBMENU;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_MAINMENU_FLAG:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> flags |= FM_MAIN_MENU;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_INFO_OFFS_Y:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> OffsY = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_NO_ALIGN:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> flags |= IP_NO_ALIGN;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_OFFS_Y:
                     if(curMode == AS_INIT_WORLD_MAP){
                         t_id = script -> read_idata();
                         wMap -> ShapeOffsY[t_id] = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_IBS){
                             t_id = script -> read_idata();
                             ibsObj -> indPosY[t_id] = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case NEW_WORLD_MAP:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     wMap = new aciWorldMap;
                     curMode = AS_INIT_WORLD_MAP;
                     break;
                 case NEW_WORLD_DATA:
                     if(curMode != AS_INIT_WORLD_MAP)
                         handle_error("Misplaced option",aOptIDs[id]);
                     wData = new aciWorldInfo;
                     wData -> ID = script -> read_idata();
                     wData -> letter = script -> read_idata();
                     wData -> shape_id = script -> read_idata();
                     curMode = AS_INIT_WORLD_DATA;
                     break;
                 case TOGGLE_ISCREEN_MODE:
                     iScreenFlag = 1;
                     break;
                 case I_END_BLOCK:
                     end_block();
                     break;
                 case INIT_CELL_SIZE:
                     if(iScreenFlag)
                         iCellSize = script -> read_idata();
                     else
                         aCellSize = script -> read_idata();
                     break;
                 case NEW_INV_MATRIX:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     invMat = new invMatrix;
                     curMode = AS_INIT_MATRIX;
                     invMat -> internalID = script -> read_idata();
                     invMat -> type = script -> read_idata();
                     break;
                 case NEW_INFO_PANEL:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     iPl = new InfoPanel;
                     curMode = AS_INIT_INFO_PANEL;
                     break;
                 case NEW_IBS:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     ibsObj = new ibsObject;
                     curMode = AS_INIT_IBS;
                     ibsObj -> ID = script -> read_idata();
                     break;
                 case NEW_IND:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     aInd = new aIndData;
                     curMode = AS_INIT_IND;
                     aInd -> ID = script -> read_idata();
                     break;
                 case NEW_BML:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     bmlObj = new bmlObject;
                     bmlObj -> flags |= BMP_FLAG;
                     curMode = AS_INIT_BML;
                     bmlObj -> ID = script -> read_idata();
                     break;
                 case NEW_INV_ITEM:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     invItm = new invItem;
                     curMode = AS_INIT_ITEM;
                     script -> prepare_pdata();
                     invItm -> init_name(script -> get_conv_ptr());
                     break;
                 case NEW_COUNTER:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     cP = new CounterPanel;
                     cP -> type = script -> read_option(0) - NEW_COUNTER - 1;
                     curMode = AS_INIT_COUNTER;
                     break;
                 case NEW_BUTTON:
                     if(curMode != AS_NONE)
                         handle_error("Misplaced option",aOptIDs[id]);
                     aBt = new aButton;
                     aBt -> type = script -> read_option(0) - NEW_BUTTON - 1;
                     curMode = AS_INIT_BUTTON;
                     break;
                 case NEW_MENU:
                     if(curMode != AS_NONE && curMode != AS_INIT_ITEM)
                         handle_error("Misplaced option",aOptIDs[id]);
                     fnMnu = new fncMenu;
                     if(curMode == AS_INIT_ITEM)
                         fnMnu -> flags |= FM_ITEM_MENU;
                     curMode = AS_INIT_MENU;
                     break;
                 case NEW_MENU_ITEM:
                     if(curMode != AS_INIT_MENU)
                         handle_error("Misplaced option",aOptIDs[id]);
                     fnMnuItm = new fncMenuItem;
                     curMode = AS_INIT_MENU_ITEM;
                     break;
                 case INIT_NUMVALS:
                     if(curMode == AS_INIT_IND){
                         aInd -> NumVals = script -> read_idata();
                         aInd -> alloc_mem();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_X:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> ScreenX = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_MENU){
                             fnMnu -> PosX = script -> read_idata();
                         }
                         else {
                             if(curMode == AS_INIT_BUTTON){
                                 aBt -> PosX = script -> read_idata();
                             }
                             else {
                                 if(curMode == AS_INIT_IND){
                                     aInd -> PosX = script -> read_idata();
                                     aInd -> dX = aInd -> PosX;
                                 }
                                 else {
                                     if(curMode == AS_INIT_INFO_PANEL){
                                         iPl -> PosX = script -> read_idata();
                                     }
                                     else {
                                         if(curMode == AS_INIT_COUNTER){
                                             cP -> PosX = script -> read_idata();
                                         }
                                         else {
                                             if(curMode == AS_INIT_WORLD_DATA){
                                                 wData -> PosX = script -> read_idata();
                                             }
                                             else {
                                                 if(curMode == BM_INIT_MENU_ITEM){
                                                     aciBM_it -> PosX = script -> read_idata();
                                                 }
                                                 else
                                                     handle_error("Misplaced option",aOptIDs[id]);
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                     break;
                 case INIT_Y:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> ScreenY = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_MENU){
                             fnMnu -> PosY = script -> read_idata();
                         }
                         else {
                             if(curMode == AS_INIT_BUTTON){
                                 aBt -> PosY = script -> read_idata();
                             }
                             else {
                                 if(curMode == AS_INIT_IND){
                                     aInd -> PosY = script -> read_idata();
                                     aInd -> dY = aInd -> PosY;
                                 }
                                 else {
                                     if(curMode == AS_INIT_INFO_PANEL){
                                         iPl -> PosY = script -> read_idata();
                                     }
                                     else {
                                         if(curMode == AS_INIT_COUNTER){
                                             cP -> PosY = script -> read_idata();
                                         }
                                         else {
                                             if(curMode == AS_INIT_WORLD_DATA){
                                                 wData -> PosY = script -> read_idata();
                                             }
                                             else {
                                                 if(curMode == BM_INIT_MENU_ITEM){
                                                     aciBM_it -> PosY = script -> read_idata();
                                                 }
                                                 else
                                                     handle_error("Misplaced option",aOptIDs[id]);
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                     break;
                 case INIT_MSX:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> SizeX = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_RAFFA_FLAG:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> flags |= IM_RAFFA;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_NUM_AVI_ID:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> numAviIDs = script -> read_idata();
                         if(!invMat -> numAviIDs) handle_error("Bad invMatrix::numAviIDs");
                         invMat -> avi_ids = new char*[invMat -> numAviIDs];
                         for(i = 0; i < invMat -> numAviIDs; i ++)
                             invMat -> avi_ids[i] = NULL;
                     }
                     else {
                         if(curMode == AS_INIT_ITEM){
                             invItm -> numAviIDs = script -> read_idata();
                             if(!invItm -> numAviIDs) handle_error("Bad invItem::numAviIDs");
                             invItm -> avi_ids = new char*[invItm -> numAviIDs];
                             for(i = 0; i < invItm -> numAviIDs; i ++)
                                 invItm -> avi_ids[i] = NULL;
                         }
                         else {
                             handle_error("Misplaced option",aOptIDs[id]);
                         }
                     }
                     break;
                 case SET_ESCAVE_FLAG:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> flags |= INV_ITEM_SHOW_ESCAVE;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_SHOW_LOAD:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> flags |= INV_ITEM_SHOW_LOAD;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_TEMPLATE:
                     if(curMode == AS_INIT_ITEM){
                         script -> prepare_pdata();
                         if(strcasecmp(script -> get_conv_ptr(),"NONE"))
                             invItm -> set_template(script -> get_conv_ptr());
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_ACTIVATE_FLAG:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> flags |= INV_ITEM_NO_ACTIVATE;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_PART_DATA:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> partData = new aciMechosPartInfo;
                         invItm -> partData -> baseID[0] = script -> read_idata();
                         invItm -> partData -> targetID[0] = script -> read_idata();
                         invItm -> partData -> baseID[1] = script -> read_idata();
                         invItm -> partData -> targetID[1] = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_NO_SHOW_LOAD:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> flags &= ~INV_ITEM_SHOW_LOAD;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_NOT_COMPLETED_FLAG:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> flags |= IM_NOT_COMPLETE;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_MSY:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> SizeY = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_RADIUS:
                     if(curMode == AS_INIT_IND){
                         script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_CORNER:
                     if(curMode == AS_INIT_IND){
                         aInd -> CornerNum = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_IND_TYPE:
                     if(curMode == AS_INIT_IND){
                         aInd -> type = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_SX:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> ScreenSizeX = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_ITEM){
                             t_id = script -> read_idata();
                         }
                         else {
                             if(curMode == AS_INIT_MENU){
                                 fnMnu -> SizeX = script -> read_idata();
                             }
                             else {
                                 if(curMode == AS_INIT_BML){
                                     bmlObj -> SizeX = script -> read_idata();
                                 }
                                 else {
                                     if(curMode == AS_INIT_INFO_PANEL){
                                         iPl -> SizeX = script -> read_idata();
                                     }
                                     else {
                                         if(curMode == AS_INIT_WORLD_MAP){
                                             wMap -> SizeX = script -> read_idata();
                                         }
                                         else {
                                             if(curMode == AS_INIT_COUNTER){
                                                 cP -> SizeX = script -> read_idata();
                                             }
                                             else {
                                                 if(curMode == BM_INIT_MENU){
                                                     aciBM -> SizeX = script -> read_idata();
                                                 }
                                                 else
                                                     handle_error("Misplaced option",aOptIDs[id]);
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                     break;
                 case INIT_SY:
                     if(curMode == AS_INIT_MATRIX){
                         invMat -> ScreenSizeY = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_ITEM){
                             t_id = script -> read_idata();
                         }
                         else {
                             if(curMode == AS_INIT_MENU){
                                 fnMnu -> SizeY = script -> read_idata();
                             }
                             else {
                                 if(curMode == AS_INIT_BML){
                                     bmlObj -> SizeY = script -> read_idata();
                                 }
                                 else {
                                     if(curMode == AS_INIT_INFO_PANEL){
                                         iPl -> SizeY = script -> read_idata();
                                     }
                                     else {
                                         if(curMode == AS_INIT_WORLD_MAP){
                                             wMap -> SizeY = script -> read_idata();
                                         }
                                         else {
                                             if(curMode == AS_INIT_COUNTER){
                                                 cP -> SizeY = script -> read_idata();
                                             }
                                             else {
                                                 if(curMode == BM_INIT_MENU){
                                                     aciBM -> SizeY = script -> read_idata();
                                                 }
                                                 else
                                                     handle_error("Misplaced option",aOptIDs[id]);
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                     break;
                 case INIT_SLOT_TYPE:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> slotType = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_AVI_ID:
                     if(curMode == AS_INIT_ITEM){
                         if(!invItm -> numAviIDs) handle_error("Null item numAviIDs...");
                         t_id = script -> read_idata();
                         if(t_id >= invItm -> numAviIDs || invItm -> avi_ids[t_id])
                             handle_error("Bad AVI_ID number");
                         script -> prepare_pdata();
                         invItm -> init_avi_id(script -> get_pdata_ptr(),t_id);
                     }
                     else {
                         if(curMode == AS_INIT_MATRIX){
                             if(!invMat -> numAviIDs) handle_error("Null matrix numAviIDs...");
                             t_id = script -> read_idata();
                             if(t_id >= invMat -> numAviIDs || invMat -> avi_ids[t_id])
                                 handle_error("Bad AVI_ID number");
                             script -> prepare_pdata();
                             invMat -> init_avi_id(script -> get_pdata_ptr(),t_id);
                         }
                         else {
                             handle_error("Misplaced option",aOptIDs[id]);
                         }
                     }
                     break;
                 case INIT_COMMENTS:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> numComments = script -> read_idata();
                         if(invItm -> numComments){
                             invItm -> comments = new char*[invItm -> numComments];
                             for(i = 0; i < invItm -> numComments; i ++){
                                 script -> read_pdata(&invItm -> comments[i],1);
                             }
                         }
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_NUM_INDEX:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> NumIndex = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_LOC_DATA){
                             t_id = script -> read_idata();
                             if(t_id < 0 || t_id >= ACI_LOCATION_INDEX_SIZE)
                                 ErrH.Abort("Bad aciLocationInfo::numIndex ID...");
                             locData -> numIndex[t_id] = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                         }
                     break;
                 case INIT_SHAPE_LEN:
                     if(curMode == AS_INIT_ITEM){
                         invItm -> ShapeLen = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_SHAPE:
                     if(curMode == AS_INIT_ITEM){
                         curMode = AS_INIT_SHAPE_OFFS;
                         load_item_shape();
                     }
                     else {
                         if(curMode == AS_INIT_WORLD_MAP){
                             t_id = script -> read_idata();
                             script -> read_pdata(&wMap -> shape_files[t_id],1);
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_MATRIX_EL:
                     if(curMode == AS_INIT_MATRIX){
                         curMode = AS_INIT_MATRIX_EL;
                         load_matrix();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_SLOT_NUMS:
                     if(curMode == AS_INIT_MATRIX){
                         curMode = AS_INIT_MATRIX_EL;
                         load_slot_nums();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_SLOT_TYPES:
                     if(curMode == AS_INIT_MATRIX){
                         curMode = AS_INIT_MATRIX_EL;
                         load_slot_types();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_CLASS:
                     if(curMode == AS_INIT_ITEM){
                         t_id = script -> read_option(0) - INIT_CLASS - 1;
                         invItm -> classID = t_id;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_FNAME:
                     if(curMode == AS_INIT_ITEM){
                         script -> prepare_pdata();
                         invItm -> init_fname(script -> get_conv_ptr());
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_FILE:
                     script -> prepare_pdata();
                     if(curMode == AS_INIT_IBS){
                         ibsObj -> set_name(script -> get_conv_ptr());
                     }
                     else {
                         if(curMode == AS_INIT_BML){
                             bmlObj -> init_name(script -> get_conv_ptr());
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_BGROUND:
                     if(curMode == AS_INIT_IBS){
                         ibsObj -> backObjID = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_SEQ_NAME:
                     script -> prepare_pdata();
                     if(curMode == AS_INIT_BUTTON){
                         aBt -> set_fname(script -> get_conv_ptr());
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_CONTROL_ID:
                     if(curMode == AS_INIT_BUTTON){
                         aBt -> ControlID = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_EVENT_CODE:
                     if(curMode == AS_INIT_BUTTON){
                         t_id = script -> read_idata();
                         init_event_code(t_id);
                     }
                     else {
                         if(curMode == AS_INIT_ITEM){
                             invItm -> EvCode = script -> read_idata() + ACI_MAX_EVENT;
                         }
                         else {
                             if(curMode == AS_INIT_MENU_ITEM){
                                 fnMnuItm -> eventPtr = new actEvent;
                                 fnMnuItm -> eventPtr -> code = script -> read_idata() + ACI_MAX_EVENT;
                                 fnMnuItm -> eventPtr -> data = script -> read_idata();
                             }
                             else
                                 handle_error("Misplaced option",aOptIDs[id]);
                         }
                     }
                     break;
                 case SET_UNPRESS:
                     if(curMode == AS_INIT_BUTTON){
                         aBt -> flags |= B_UNPRESS;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_ACTIVE_TIME:
                     if(curMode == AS_INIT_BUTTON){
                         aBt -> activeCount = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_MENU){
                             fnMnu -> activeCount = script -> read_idata();
                         }
                         else {
                             if(curMode == AML_INIT_EVENT){
                                 mlEv -> active_time = script -> read_idata();
                             }
                             else {
                                 if(curMode == BM_INIT_MENU){
                                     aciBM -> activeCount = script -> read_idata();
                                 }
                                 else
                                     handle_error("Misplaced option",aOptIDs[id]);
                             }
                         }
                     }
                     break;
                 case INIT_FNC_CODE:
                     if(curMode == AS_INIT_MENU_ITEM){
                         fnMnuItm -> fnc_code = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_NO_DELETE_FLAG:
                     if(curMode == AS_INIT_MENU_ITEM){
                         fnMnuItm -> flags |= FM_NO_DELETE;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_SUBMENU_ID:
                     if(curMode == AS_INIT_MENU_ITEM){
                         fnMnuItm -> submenuID = script -> read_idata();
                         fnMnuItm -> flags |= FM_SUBMENU_ITEM;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_BSUBMENU_ID:
                     if(curMode == AS_INIT_MENU_ITEM){
                         fnMnuItm -> submenuID = script -> read_idata();
                         fnMnuItm -> flags |= FM_BSUBMENU_ITEM;
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_NUM_V_ITEMS:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> VItems = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_SPACE:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> vSpace = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_MENU_ITEM){
                             fnMnuItm -> space = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_NO_DEACTIVATE_FLAG:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> flags |= FM_NO_DEACTIVATE;
                     }
                     else {
                         if(curMode == AML_INIT_EVENT){
                             mlEv -> flags |= AML_NO_DEACTIVATE;
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_LOCATION_MENU_FLAG:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> flags |= FM_LOCATION_MENU;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_BML_NAME:
                     if(curMode == AS_INIT_MENU){
                         script -> read_pdata(&fnMnu -> bml_name,1);
                     }
                     else {
                         if(curMode == AS_INIT_IND){
                             script -> prepare_pdata();
                             if(aInd -> bml)
                                 handle_error("aIndData::bml already inited");
                             aInd -> bml = new bmlObject;
                             aInd -> bml -> init_name(script -> get_conv_ptr());
                         }
                         else {
                             if(curMode == AS_INIT_INFO_PANEL){
                                 script -> read_pdata(&iPl -> bml_name,1);
                             }
                             else {
                                 if(curMode == BM_INIT_MENU_ITEM){
                                     script -> read_pdata(&aciBM_it -> fname,1);
                                 }
                                 else
                                     handle_error("Misplaced option",aOptIDs[id]);
                             }
                         }
                     }
                     break;
                 case INIT_BACK_BML:
                     if(curMode == AS_INIT_MATRIX){
                         script -> prepare_pdata();
                         if(invMat -> back)
                             handle_error("invMatrix::back already inited");
                         invMat -> back = new bmlObject;
                         invMat -> back -> init_name(script -> get_conv_ptr());
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case SET_IBS_NAME:
                     if(curMode == AS_INIT_MENU){
                         script -> read_pdata(&fnMnu -> ibs_name,1);
                     }
                     else {
                         if(curMode == AS_INIT_INFO_PANEL){
                             script -> read_pdata(&iPl -> ibs_name,1);
                         }
                         else {
                             if(curMode == AS_INIT_COUNTER){
                                 script -> read_pdata(&cP -> ibs_name,1);
                             }
                             else
                                 handle_error("Misplaced option",aOptIDs[id]);
                         }
                     }
                     break;
                 case SET_MAP_NAME:
                     if(curMode == AS_INIT_LOC_DATA){
                         script -> read_pdata(&locData -> mapName,1);
                     }
                     else {
                         t_id = script -> read_idata();
                         script -> read_pdata(&aScrDisp -> map_names[t_id],1);
                     }
                     break;
                 case SET_SAVE_SCREEN_ID:
                     if(curMode == AS_INIT_LOC_DATA){
                         locData -> SaveScreenID = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_WORLD_ID:
                     if(curMode == AS_INIT_LOC_DATA){
                         locData -> WorldID = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case SET_EXCLUDE:
                     if(curMode == AS_INIT_LOC_DATA){
                         t_id = script -> read_idata();
                         locData -> ExcludeItems[t_id] = 1;
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_SCREEN_ID:
                     if(curMode == AS_INIT_LOC_DATA){
                         script -> read_pdata(&locData -> screenID,1);
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_PAL_NAME:
                     if(curMode == AS_INIT_LOC_DATA){
                         script -> read_pdata(&locData -> palName,1);
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_CUR_FNC:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> curFunction = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_FONT:
                     if(curMode == AS_INIT_MENU_ITEM){
                         fnMnuItm -> font = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_INFO_PANEL){
                             iPl -> font = script -> read_idata();
                         }
                         else {
                             if(curMode == AS_INIT_WORLD_DATA){
                                 wData -> font = script -> read_idata();
                             }
                             else {
                                 if(curMode == AS_INIT_COUNTER){
                                     cP -> font = script -> read_idata();
                                 }
                                 else {
                                     if(curMode == AS_INIT_IBS){
                                         ibsObj -> fontID = script -> read_idata();
                                     }
                                     else
                                         handle_error("Misplaced option",aOptIDs[id]);
                                 }
                             }
                         }
                     }
                     break;
                 case INIT_VSPACE:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> vSpace = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_HSPACE:
                     if(curMode == AS_INIT_INFO_PANEL){
                         iPl -> hSpace = script -> read_idata();
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_STRING:
                     if(curMode == AS_INIT_MENU_ITEM){
                         script -> prepare_pdata();
                         fnMnuItm -> init_name(script -> get_conv_ptr());
                     }
                     else
                         handle_error("Misplaced option",aOptIDs[id]);
                     break;
                 case INIT_SCANCODE:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> add_key(script -> read_key());
                     }
                     else {
                         if(curMode == AS_INIT_MENU_ITEM){
                             fnMnuItm -> add_key(script -> read_key());
                         }
                         else {
                             if(curMode == AS_INIT_BUTTON){
                                 aBt -> add_key(script -> read_key());
                             }
                             else {
                                 if(curMode == AML_INIT_EVENT){
                                     mlEv -> add_key(script -> read_key());
                                 }
                                 else
                                     handle_error("Misplaced option",aOptIDs[id]);
                             }
                         }
                     }
                     break;
                 case INIT_MENU_TYPE:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> type = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_UP_KEY:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> up_key -> add_key(script -> read_key());
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_DOWN_KEY:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> down_key -> add_key(script -> read_key());
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_TRIGGER:
                     if(curMode == AS_INIT_MENU){
                         fnMnu -> trigger_code = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_ID:
                     if(curMode == AS_INIT_BUTTON){
                         aBt -> ID = script -> read_idata();
                     }
                     else {
                         if(curMode == AS_INIT_ITEM){
                             invItm -> ID = script -> read_idata();
                         }
                         else {
                             if(curMode == AS_INIT_LOC_DATA){
                                 t_id = script -> read_idata();
                                 script -> read_pdata(&locData -> objIDs[t_id],1);
                             }
                             else {
                                 if(curMode == AS_INIT_MATRIX){
                                     script -> read_pdata(&invMat -> mech_name,1);
                                 }
                                 else {
                                     if(curMode == AS_INIT_INFO_PANEL){
                                         iPl -> type = script -> read_idata();
                                     }
                                     else {
                                         if(curMode == AS_INIT_COUNTER){
                                             cP -> ID = script -> read_idata();
                                         }
                                         else {
                                             if(curMode == AML_INIT_DATA_SET){
                                                 mlDataSet -> ID = script -> read_idata();
                                             }
                                             else {
                                                 if(curMode == AML_INIT_DATA){
                                                     mlData -> ID = script -> read_idata();
                                                 }
                                                 else {
                                                     if(curMode == BM_INIT_MENU_ITEM){
                                                         aciBM_it -> ID = script -> read_idata();
                                                     }
                                                     else {
                                                         if(curMode == BM_INIT_MENU){
                                                             aciBM -> ID = script -> read_idata();
                                                         }
                                                         else {
                                                             if(curMode == AML_INIT_EVENT_SEQ){
                                                                 mlEvSeq -> add_id(script -> read_idata());
                                                             }
                                                             else
                                                                 handle_error("Misplaced option",aOptIDs[id]);
                                                         }
                                                     }
                                                 }
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                     break;
                 case INIT_S_ID:
                     if(curMode == AS_INIT_LOC_DATA){
                         t_id = script -> read_idata();
                         script -> read_pdata(&locData -> s_objIDs[t_id],1);
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
                 case INIT_MODE_KEY:
                     aScrDisp -> ModeObj -> add_key(script -> read_key());
                     break;
                 case INIT_INV_KEY:
                     aScrDisp -> InvObj -> add_key(script -> read_key());
                     break;
                 case INIT_INFO_KEY:
                     aScrDisp -> InfoObj -> add_key(script -> read_key());
                     break;
                 case SET_CURMATRIX:
                     curMatrix = script -> read_idata();
                     break;
                 case INIT_CUR_IBS:
                     aScrDisp -> curIbsID = script -> read_idata();
                     break;
                 case NEW_LOC_DATA:
                     if(curMode != AS_NONE){
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     locData = new aciLocationInfo;
                     locData -> ID = script -> read_idata();
                     curMode = AS_INIT_LOC_DATA;
                     break;
                 case NEW_COL_SCHEME:
                     if(curMode != AS_NONE){
                         if(curMode == AS_INIT_LOC_DATA){
                             locData -> numColorScheme = script -> read_idata();
                         }
                         else
                             handle_error("Misplaced option",aOptIDs[id]);
                     }
                     curMode = AS_INIT_COLOR_SCHEME;
                     t_id = script -> read_idata();
                     curScheme = t_id;
                     aciColorSchemes[t_id] = new unsigned char[aciColSchemeLen];
                     memset(aciColorSchemes[t_id],0,aciColSchemeLen);
                     break;
                 case INIT_NUM_SCHEMES:
                     aciNumColSchemes = script -> read_idata();
                     aciColorSchemes = new unsigned char*[aciNumColSchemes];
                     for(i = 0; i < aciNumColSchemes; i ++)
                         aciColorSchemes[i] = NULL;
                     break;
                 case INIT_SCHEME_LEN:
                     aciColSchemeLen = script -> read_idata();
                     break;
                 case INIT_COLOR:
                     if(curMode == AS_INIT_COLOR_SCHEME){
                         t_id = script -> read_idata();
                         aciColorSchemes[curScheme][t_id] = script -> read_idata();
                     }
                     else {
                         handle_error("Misplaced option",aOptIDs[id]);
                     }
                     break;
             }
 #ifndef _BINARY_SCRIPT_
         }
         else
             script -> next_ptr();
 #endif
     }
 #ifdef _SAVE_BINARY_SCRIPT_
     script -> close_bscript();
 #endif
     delete script;
 #ifndef _BINARY_SCRIPT_
     _sFREE_HEAP_(1500000,char);
 #endif
 }
References _sALLOC_HEAP_, aBt, ACI_MAX_PRM_LEN, aciML_D, aInd, AS_INIT_BUTTON, AS_INIT_IND, AS_INIT_ITEM, aScrDisp, curMode, handle_error(), INIT_ITEM_PRM, INIT_MECHOS_PRM, invItm, iSCRIPT_EOF, NULL, script, and SET_PROMPT_TEXT.
aPutChar()
void aPutChar (int x, int y, int font, int color, int str, int bsx, int bsy, unsigned char * buf)
 {
     int i,j,xs,ys,offs = 0,X = 0,col1,col2;
     int buf_index = 0,buf_offs = 0;
     col1 = color & ACI_COLOR_MASK;
     col2 = (color >> 8) & ACI_COLOR_MASK;
     if(aScrFonts[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     unsigned char* p = aScrFonts[font] -> data;
     xs = aScrFonts[font] -> SizeX;
     ys = aScrFonts[font] -> SizeY;
     buf_index = x + y * bsx;
     buf_offs = 0;
     offs = xs * ys * str;
     if(col2){
         for(i = 0; i < ys; i ++){
             for(j = 0; j < xs; j ++){
                 switch(p[offs + j]){
                     case 1:
                         buf[X + j + buf_index + buf_offs] = col1;
                         break;
                     case 2:
                         buf[X + j + buf_index + buf_offs] = col2;
                         break;
                 }
             }
             offs += xs;
             buf_offs += bsx;
         }
     }
     else {
         for(i = 0; i < ys; i ++){
             for(j = 0; j < xs; j ++){
                 switch(p[offs + j]){
                     case 1:
                         buf[X + j + buf_index + buf_offs] = col1;
                         break;
                 }
             }
             offs += xs;
             buf_offs += bsx;
         }
     }
 }
References XErrorHandler::Abort(), ACI_COLOR_MASK, aScrFonts, ErrH, and NULL.
Referenced by aciWorldInfo::redraw(), and CounterPanel::redraw().
aPutChar32()
void aPutChar32 (int x, int y, int font, int color, int color_size, int str, int bsx, void * buf)
 {
     aciXConv -> init();
     *aciXConv < (char)str < "\0";
     aPutStr32(x,y,font,color,color_size,aciXConv -> address(),bsx,buf,0);
 }
References aciXConv, and aPutStr32().
Referenced by CounterPanel::redraw().
aPutNum()
void aPutNum (int x, int y, int font, int color, int str, int bsx, unsigned char * buf, int space)
 {
     char* p;
     static XBuffer XBuf;
     XBuf.init();
     XBuf <= str;
     p = XBuf.GetBuf();
     aPutStr(x,y,font,color,(unsigned char*)p,bsx,buf,space);
 }
References aPutStr(), XBuffer::GetBuf(), and XBuffer::init().
Referenced by invItem::redraw().
aPutStr()
void aPutStr (int x, int y, int font, int color, unsigned char * str, int bsx, unsigned char * buf, int space)
 {
     int i,j,s,xs,ys,offs = 0,sz = strlen((char*)str),X = 0,col1,col2,col3,col4;
     int buf_index = 0,buf_offs = 0;
     col1 = color & ACI_COLOR_MASK;
     col2 = (color >> 8) & ACI_COLOR_MASK;
     col3 = (color >> 16) & ACI_COLOR_MASK;
     col4 = (color >> 24) & ACI_COLOR_MASK;
     if(aScrFonts[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     unsigned char* p = aScrFonts[font] -> data;
     xs = aScrFonts[font] -> SizeX;
     ys = aScrFonts[font] -> SizeY;
     buf_index = x + y * bsx;
     if(col2){
         for(s = 0; s < sz; s ++){
             buf_offs = 0;
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             if((col3 || col4) && ((str[s] >= 48 && str[s] <= 57) || str[s] == 36)){
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col3;
                                 break;
                             case 2:
                                 buf[X + j + buf_index + buf_offs] = col4;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             else {
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col1;
                                 break;
                             case 2:
                                 buf[X + j + buf_index + buf_offs] = col2;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
     else {
         for(s = 0; s < sz; s ++){
             buf_offs = 0;
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             if(col3 && ((str[s] >= 48 && str[s] <= 57) || str[s] == 36)){
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col3;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             else {
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col1;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
 }
References XErrorHandler::Abort(), ACI_COLOR_MASK, aScrFonts, ErrH, and NULL.
Referenced by aPutNum(), fncMenuItem::redraw(), InfoPanel::redraw(), and fncMenuItem::redraw_str().
aPutStr32()
void aPutStr32 (int x, int y, int font, int color, int color_size, void * str, int bsx, void * buf, int space)
 {
     int s,xs,ys,offs = 0,sz = strlen((char*)str),X = 0,col,col_sz,col1,col2,col_sz1,col_sz2;
     int buf_offs = 0;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     col1 = color & 0xFF;
     col2 = (color >> 16) & 0xFF;
     col_sz1 = color_size & 0xFF;
     col_sz2 = (color_size >> 16) & 0xFF;
     unsigned char* p = aScrFonts32[font] -> data;
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)str;
     X = x;
     for(s = 0; s < sz; s ++){
         buf_offs = 0;
         X -= aScrFonts32[font] -> LeftOffs[str_buf[s]];
         offs = xs * ys * str_buf[s];
         if(col2){
             if((str_buf[s] >= 48 && str_buf[s] <= 57) || str_buf[s] == 36){
                 col = col2;
                 col_sz = col_sz2;
             }
             else {
                 col = col1;
                 col_sz = col_sz1;
             }
         }
         else {
             col = col1;
             col_sz = col_sz1;
         }
         aciPutBufSpr(X,y,xs,ys,bsx,p + offs,buf,col,col_sz);
         X += xs + space - aScrFonts32[font] -> RightOffs[str_buf[s]];
     }
 }
References XErrorHandler::Abort(), aciPutBufSpr(), aScrFonts32, ErrH, and NULL.
Referenced by aPutChar32(), fncMenuItem::redraw(), iScreenElement::redraw(), and InfoPanel::redraw().
aRedraw()
void aRedraw (void)
 {
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
     aScrDisp -> redraw();
 }
References aScrDisp.
aStrHeight()
int aStrHeight (int font)
 {
     return aScrFonts[font] -> SizeY;
 }
References aScrFonts.
aStrHeight32()
int aStrHeight32 (int font)
 {
     return aScrFonts32[font] -> SizeY;
 }
References aScrFonts32.
Referenced by iScreenObject::init(), and iS_StringElement::init_size().
aStrLen()
int aStrLen (unsigned char * str, int font, int space)
 {
     int s,sz = strlen((char*)str),len = 0;
     for(s = 0; s < sz; s ++)
         len += aScrFonts[font] -> SizeX - (aScrFonts[font] -> LeftOffs[str[s]] + aScrFonts[font] -> RightOffs[str[s]]) + space;
     return len;
 }
References aScrFonts.
Referenced by aWriteHelpString(), fncMenuItem::init(), aciScreenInputField::redraw(), InfoPanel::redraw(), and fncMenu::set_prefix().
aStrLen32()
int aStrLen32 (void * str, int font, int space)
 {
     int s,sz,len = 0;
     unsigned char* str_buf = (unsigned char*)str;
     sz = strlen((char*)str_buf);
     for(s = 0; s < sz; s ++)
         len += aScrFonts32[font] -> SizeX - (aScrFonts32[font] -> LeftOffs[str_buf[s]] + aScrFonts32[font] -> RightOffs[str_buf[s]]) + space;
     //printf("aStrLen32: %s %d %d %d -> %d\n", str_buf, sz, font, space, len);
     return len;
 }
References aScrFonts32.
Referenced by fncMenuItem::init(), iScreenObject::init(), iS_StringElement::init_size(), and InfoPanel::redraw().
aTextHeight32()
int aTextHeight32 (void * text, int font, int vspace)
 {
     int s,xs,ys,sz = strlen((char*)text),chr;
     int len = 0;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     len = ys + vspace;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr == '\n'){
             len += ys + vspace;
         }
     }
     return len;
 }
References XErrorHandler::Abort(), aScrFonts32, ErrH, and NULL.
Referenced by iChatInputField::redraw(), iChatHistoryScreen::redraw(), and iChatButton::redraw().
aTextWidth32()
int aTextWidth32 (void * text, int font, int hspace)
 {
     int s,xs,ys,sz = strlen((char*)text),chr;
     int len = 0,max_len = 0;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 len += xs + hspace - aScrFonts32[font] -> RightOffs[chr] - aScrFonts32[font] -> LeftOffs[chr];
             }
         }
         else {
             if(len > max_len) max_len = len;
             len = 0;
         }
     }
     if(len > max_len) max_len = len;
     return max_len;
 }
References XErrorHandler::Abort(), aScrFonts32, ErrH, and NULL.
Referenced by iChatInputChar(), and iChatButton::redraw().
aWriteHelpString()
void aWriteHelpString (int count, int * x, int * y, int font, unsigned char ** pstr, int timer, int color, int space, unsigned int * pcolor)
{
     int i, total_len = 0;
     int draw_len = CHAR_SPEED*timer;
     unsigned char tmp[256];
     int _x;
     int _color = color;
     for( i = 0; i < count; i++){
         if (pstr[i]){
             if (pcolor[i]) _color = pcolor[i];
             total_len += strlen((char*)pstr[i]);
             if (total_len <= draw_len){
                 aOutStr(x[i], y[i], font, _color, pstr[i], space );
             } else {
                 int d = total_len - draw_len;
                 memcpy( tmp, pstr[i],strlen((char*)pstr[i]) - d);
                 tmp[strlen((char*)pstr[i]) - d] = 0;
                 aOutStr(x[i], y[i], font, _color, tmp, space );
                 _x = x[i] + aStrLen(tmp, font, space );
                 EffD.FireBallData[2].Show2(_x, y[i], FrameCount);
                 EffD.FireBallData[2].CheckOut(FrameCount);
                 return;
             }//  end if
         }//  end if pstr[i]
     }//  end for
 }
build_cell_frame()
void build_cell_frame (void)
 {
     int dx = aCellSize;
     int dxx = dx * dx;
     int dx2 = dx >> 1;
     int dx4 = dx >> 2;
     unsigned char* cell = new unsigned char[(dx + 1) * (dx + 1)];
     memset(cell,0,(dx + 1) * (dx + 1));
 /*
     a_buf_line(dx2,0,dx,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx4,dx,dx2 + dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx2 + dx4,dx2,dx,1,dx + 1,dx + 1,cell);
     a_buf_line(dx2,dx,0,dx2 + dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx2 + dx4,0,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx4,dx2,0,1,dx + 1,dx + 1,cell);
 */
     a_buf_line(dx2,0,dx,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx - dx4,dx2,dx,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx4,dx,dx - dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(0,dx - dx4,0,dx4,1,dx + 1,dx + 1,cell);
     a_buf_line(dx,dx - dx4,dx2,dx,1,dx + 1,dx + 1,cell);
     a_buf_line(dx2,0,0,dx4,1,dx + 1,dx + 1,cell);
     fill_buf(dx2,dx2,0,2,dx + 1,dx + 1,cell);
     aCellFrame = cell;
 }
References a_buf_line(), aCellFrame, aCellSize, and fill_buf().
Referenced by actIntDispatcher::i_init(), and actIntDispatcher::init().
change_screen()
void change_screen (int mode)
 {
     aScrDisp -> change_ibs(mode);
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
     set_screen(aScrDisp -> curIbs -> SideX,aScrDisp -> curIbs -> SideY,0,aScrDisp -> curIbs -> CenterX,aScrDisp -> curIbs -> CenterY);
 }
References aScrDisp.
Referenced by actIntDispatcher::change_mode(), and actIntDispatcher::EventQuant().
EffectsOff()
void EffectsOff (void)
 {
     if(EffectInUsePriory && EffectInUse){
         for(int i = 0;i < 16;i++) SoundStop(i);
         EffectInUse = 0;
         lastSoundFlag = 0;
         //SoundVolumeCD = -1;
     }
 }
Referenced by LoadingRTO3::Finit(), uvsVanger::makeJump(), uvsVanger::prepare_shop(), GameQuantRTO::Quant(), uvsVanger::Quant(), and theEND().
fill_buf()
void fill_buf (int fx, int fy, int src_col, int dest_col, int sx, int sy, unsigned char * buf)
 {
     int x,y,flag = 1,index;
     buf[fx + fy * sx] = dest_col;
     while(flag){
         index = 0;
         flag = 0;
         for(y = 0; y < sy; y ++){
             for(x = 0; x < sx; x ++){
                 if(buf[index] == src_col){
                     if(x && buf[index - 1] == dest_col){
                         flag = 1;
                         buf[index] = dest_col;
                     }
                     if(x < sx - 1 && buf[index + 1] == dest_col){
                         flag = 1;
                         buf[index] = dest_col;
                     }
                     if(y && buf[index - sx] == dest_col){
                         flag = 1;
                         buf[index] = dest_col;
                     }
                     if(y < sy - 1 && buf[index + sx] == dest_col){
                         flag = 1;
                         buf[index] = dest_col;
                     }
                 }
                 index ++;
             }
         }
     }
 }
Referenced by build_cell_frame().
free_cell_frame()
void free_cell_frame (void)
 {
     delete[] aCellFrame;
 }
References aCellFrame.
Referenced by aciFreeAll(), actIntDispatcher::finit(), and actIntDispatcher::i_finit().
GeneralSystemLoad()
void GeneralSystemLoad (XStream & in)
 {
     int i,ver;
     in > ver;
     in > ViewX;
     in > ViewY;
     in > GlobalFuryLevel;
     preViewY = ViewY;
     GeneralMapReload = 1;
     GeneralLoadReleaseFlag = 1;
     LoadProtoCrypt(in,ver);
     in > ChangeEnergy;
     in > ChangeArmor;
     switch(ver){
         case 0:
             for(i = 0;i < 83;i++)
                 in >  ver;
             break;
         case 1:
         case 2:
             for(i = 0;i < 83 - WORLD_MAX;i++)
                 in > ver;
             break;
         case 3:
             in > ActD.SpobsDestroy;
             in > ActD.ThreallDestroy;
             in > ActD.SpummyRunner;
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_INDEX[i];
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_DATA[i];
             for(i = 0;i < 83 - WORLD_MAX - 3*sizeof(int) - 2*NUM_CHECK_BSIGN;i++)
                 in > ver;
             break;
         case 4:
             in > ActD.SpobsDestroy;
             in > ActD.ThreallDestroy;
             in > ActD.SpummyRunner;
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_INDEX[i];
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_DATA[i];
             in > ActD.SpobsDestroyActive;
             in >ActD.ThreallDestroyActive;
             for(i = 0;i < MAX_TIME_SECRET;i++){
                 in > TimeSecretEnable[WORLD_FOSTRAL][i];
                 in > TimeSecretEnable[WORLD_GLORX][i];
             };
             in > i;
             if(i != 3791)
                 ErrH.Abort("Bad Save Signature");
             in > i;
             if(i != 11083)
                 ErrH.Abort("Bad Save Signature");
             break;
         case 5:
             in > ActD.SpobsDestroy;
             in > ActD.ThreallDestroy;
             in > ActD.SpummyRunner;
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_INDEX[i];
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_DATA[i];
             in > ActD.SpobsDestroyActive;
             in > ActD.ThreallDestroyActive;
             for(i = 0;i < MAX_TIME_SECRET;i++){
                 in > TimeSecretEnable[WORLD_FOSTRAL][i];
                 in > TimeSecretEnable[WORLD_GLORX][i];
             };
             in > ActD.PromptPodishFreeVisit;
             in > ActD.PromptIncubatorFreeVisit;
             in > ActD.PromptChangeCycleCount;
             in > i;
             if(i != 3791)
                 ErrH.Abort("Bad Save Signature");
             in > i;
             if(i != 11083)
                 ErrH.Abort("Bad Save Signature");
             break;
         case 6:
             in > ActD.SpobsDestroy;
             in > ActD.ThreallDestroy;
             in > ActD.SpummyRunner;
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_INDEX[i];
             for(i = 0;i < NUM_CHECK_BSIGN;i++)
                 in > CHECK_BSIGN_DATA[i];
             in > ActD.SpobsDestroyActive;
             in > ActD.ThreallDestroyActive;
             for(i = 0;i < MAX_TIME_SECRET;i++){
                 in > TimeSecretEnable[WORLD_FOSTRAL][i];
                 in > TimeSecretEnable[WORLD_GLORX][i];
                 in > TimeSecretType[WORLD_FOSTRAL][i];
                 in > TimeSecretType[WORLD_GLORX][i];
                 in > TimeSecretData0[WORLD_FOSTRAL][i];
                 in > TimeSecretData0[WORLD_GLORX][i];
                 in > TimeSecretData1[WORLD_FOSTRAL][i];
                 in > TimeSecretData1[WORLD_GLORX][i];
             };
             in > ActD.PromptPodishFreeVisit;
             in > ActD.PromptIncubatorFreeVisit;
             in > ActD.PromptChangeCycleCount;
             in > i;
             if(i != 3791)
                 ErrH.Abort("Bad Save Signature");
             in > i;
             if(i != 11083)
                 ErrH.Abort("Bad Save Signature");
             break;
     };
 //  if(strlen(CHECK_BSIGN_DATA) < NUM_CONTROL_BSIGN)
 //      ErrH.Abort("Bad Load Word in Boozeena");
 };
GeneralSystemSave()
void GeneralSystemSave (XStream & out)
 {
     int i;
 //  if(strlen(CHECK_BSIGN_DATA) < NUM_CONTROL_BSIGN)
 //      ErrH.Abort("Bad Save Word in Boozeena");
     out < (int)(6);
     out < ViewX;
     out < ViewY;
     out < GlobalFuryLevel;
     SaveProtoCrypt(out);
     out < ChangeEnergy;
     out < ChangeArmor;
 //Version3--------------------------------
     out < ActD.SpobsDestroy;
     out < ActD.ThreallDestroy;
     out < ActD.SpummyRunner;
     for(i = 0;i < NUM_CHECK_BSIGN;i++)
         out < CHECK_BSIGN_INDEX[i];
     for(i = 0;i < NUM_CHECK_BSIGN;i++)
         out < CHECK_BSIGN_DATA[i];
 //Version4--------------------------------
     out < ActD.SpobsDestroyActive;
     out < ActD.ThreallDestroyActive;
     for(i = 0;i < MAX_TIME_SECRET;i++){
         out < TimeSecretEnable[WORLD_FOSTRAL][i];
         out < TimeSecretEnable[WORLD_GLORX][i];
 //Version6-------------------------------
         out < TimeSecretType[WORLD_FOSTRAL][i];
         out < TimeSecretType[WORLD_GLORX][i];
         out < TimeSecretData0[WORLD_FOSTRAL][i];
         out < TimeSecretData0[WORLD_GLORX][i];
         out < TimeSecretData1[WORLD_FOSTRAL][i];
         out < TimeSecretData1[WORLD_GLORX][i];
 //-------------------------------------------
     };
 //Version5-------------------------------
     out < ActD.PromptPodishFreeVisit;
     out < ActD.PromptIncubatorFreeVisit;
     out < ActD.PromptChangeCycleCount;
 //-------------------------------------------
     out < (int)(3791);
     out < (int)(11083);
 };
GetCompasTarget()
char* GetCompasTarget (void)
 {
     if(CompasObj.CurrentTarget){
         return CompasObj.CurrentTarget->aciName;
     };
     return NULL;
 };
Referenced by aciAdd2Targets(), aciDeleteFromTargets(), and aciRefreshTargetsMenu().
i_evince_pal()
void i_evince_pal (unsigned char * p, int delta)
 {
     int i,col,scale = 0;
     unsigned char* buf = new unsigned char[768];
     while(scale < 256){
         for(i = 0; i < 768; i ++){
             col = p[i];
             buf[i] = (col * scale) >> 8;
         }
         XGR_SetPal(buf,0,255);
         SDL_Delay(10);
         scale += delta;
     }
     XGR_SetPal(p,0,255);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     delete[] buf;
 }
References XGR_SetPal.
Referenced by aciShowLocation(), and aciShowLocationPicture().
i_slake_pal()
void i_slake_pal (unsigned char * p, int delta)
 {
     int i,col,scale = 256;
     unsigned char* buf = new unsigned char[768];
     i_getpal(p);
     while(scale > 0){
         for(i = 0; i < 768; i ++){
             col = p[i];
             buf[i] = (col * scale) >> 8;
         }
         XGR_SetPal(buf,0,255);
         SDL_Delay(10);
         scale -= delta;
     }
     memset(buf,0,768);
     XGR_SetPal(buf,0,255);
     XGR_Fill(0);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     delete[] buf;
 }
Referenced by ShowImageRTO::Finit(), actIntDispatcher::flush(), actIntDispatcher::i_init(), and MainMenuRTO::Quant().
ibsout()
void ibsout (int x, int y, void * ptr)
 {
     int _x,_y,cnt;
     int* offs_table = XGR_Obj.yOffsTable;
     unsigned char* vbuf = XGR_VIDEOBUF;
     unsigned char* pbuf = (unsigned char*)ptr;
     cnt = *((int*)pbuf);
     pbuf += 4;
     while(cnt){
         _x = *((int*)pbuf);
         pbuf += 4;
         _y = *((int*)pbuf);
         pbuf += 4;
         memcpy(vbuf + offs_table[_y + y] + _x + x,pbuf,cnt);
         pbuf += cnt;
         cnt = *((int*)pbuf);
         pbuf += 4;
     }
 }
References XGR_Obj, XGR_VIDEOBUF, and XGR_Screen::yOffsTable.
Referenced by aciScreenResourceXBM::redraw(), and ibsObject::show().
iLoadData()
void iLoadData (void)
 {
     XStream fh(0);
     if(!RecorderMode){
         if(fh.open("options.dat",XS_IN)){
             iScrDisp -> load_data(&fh);
             fh > aciAutoRun;
             fh.close();
         }
     }
     aciAutoRun = iGetOptionValue(iAUTO_ACCELERATION);
     iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
     iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
     iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
     iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
     iHandleExtEvent(iEXT_UPDATE_MUSIC_VOLUME);
     iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
     iHandleExtEvent(iEXT_INIT_KEEP_OPTIONS);
     iHandleExtEvent(iEXT_INIT_JOYSTICK);
     iHandleExtEvent(iEXT_INIT_PROXY);
     iHandleExtEvent(iEXT_INIT_PORT);
 }
References aciAutoRun, XStream::close(), iAUTO_ACCELERATION, iEXT_INIT_JOYSTICK, iEXT_INIT_KEEP_OPTIONS, iEXT_INIT_PORT, iEXT_INIT_PROXY, iEXT_UPDATE_MUSIC_MODE, iEXT_UPDATE_MUSIC_VOLUME, iEXT_UPDATE_SOUND_MODE, iEXT_UPDATE_SOUND_VOLUME, iEXT_UPDATE_TUTORIAL_MODE, iGetOptionValue(), iHandleExtEvent(), iScrDisp, XStream::open(), RecorderMode, and XS_IN.
Referenced by iQuantFirst(), and iQuantPrepare().
iSaveData()
void iSaveData (void)
 {
 #ifndef _ACI_SKIP_MAINMENU_
     if(!RecorderMode){
         XStream fh("options.dat",XS_OUT);
         iScrDisp -> save_data(&fh);
 //      fh < aciAutoRun;
         fh < iGetOptionValue(iAUTO_ACCELERATION);
         fh.close();
     }
 #endif
 }
References XStream::close(), iAUTO_ACCELERATION, iGetOptionValue(), iScrDisp, RecorderMode, and XS_OUT.
Referenced by aciHandleCameraEvent(), and iFinitQuant().
iScrQuantFinit()
void iScrQuantFinit (void)
 {
     static unsigned char pal_buf[768];
     if(iScreenLog){
         iFinitQuant();
         set_key_nadlers(&KeyCenter, NULL);
         i_slake_pal(iscrPal,16);
         if(actintActiveFlag){
             i_getpal(pal_buf);
             i_change_res();
         }
         aciSendEvent2actint(EV_EVINCE_PALETTE,NULL);
     }
     actIntLog = 0;
 }
References aciSendEvent2actint(), actintActiveFlag, actIntLog, EV_EVINCE_PALETTE, i_change_res(), i_getpal(), i_slake_pal(), iFinitQuant(), iScreenLog, iscrPal, KeyCenter(), NULL, and set_key_nadlers().
Referenced by aci_LocationQuantFinit().
iScrQuantPrepare()
void iScrQuantPrepare (void)
 {
     actIntLog = 1;
     if(iScreenLog){
         iSecondInit();
         iQuantFirst();
         iQuantPrepare();
     }
 }
References actIntLog, iQuantFirst(), iQuantPrepare(), iScreenLog, and iSecondInit().
Referenced by aci_LocationQuantPrepare().
iSortPlayers()
void iSortPlayers (int mode = 0)
 {
     int i,flag = 1,num;
     double tmp;
     PlayerData* p = players_list.first();
     num = players_list.size();
     if(iPlayers) delete iPlayers;
     if(iPlayerRatings) delete iPlayerRatings;
     iPlayers = new PlayerData*[num];
     iPlayerRatings = new double[num];
     iNumPlayers = 0;
     for(i = 0; i < num; i ++){
         //   ,  -
         if(p -> name && (p -> status == GAMING_STATUS || (p -> status == FINISHED_STATUS && !mode))){
             iPlayers[iNumPlayers] = p;
             iPlayerRatings[iNumPlayers] = p -> body.rating;
             iNumPlayers ++;
         }
         p = (PlayerData*)p -> next;
     }
     if(mode){
         while(flag){
             flag = 0;
             for(i = 0; i < iNumPlayers - 1; i ++){
                 if(iCurMultiGame == iMP_VAN_WAR || iCurMultiGame == iMP_HUNTAGE){
                     if(iPlayers[i] -> body.kills - iPlayers[i] -> body.deaths < iPlayers[i + 1] -> body.kills - iPlayers[i + 1] -> body.deaths){
                         p = iPlayers[i];
                         iPlayers[i] = iPlayers[i + 1];
                         iPlayers[i + 1] = p;
                         flag = 1;
                     }
                 }
                 if(iCurMultiGame == iMP_MECHOSOMA){
                     if(iPlayers[i] -> body.MechosomaStat.ItemCount1 + iPlayers[i] -> body.MechosomaStat.ItemCount2 < iPlayers[i + 1] -> body.MechosomaStat.ItemCount1 + iPlayers[i + 1] -> body.MechosomaStat.ItemCount2){
                         p = iPlayers[i];
                         iPlayers[i] = iPlayers[i + 1];
                         iPlayers[i + 1] = p;
                         flag = 1;
                     }
                 }
                 if(iCurMultiGame == iMP_PASSEMBLOSS){
                     if(iPlayers[i] -> body.PassemblossStat.CheckpointLighting < iPlayers[i + 1] -> body.PassemblossStat.CheckpointLighting){
                         p = iPlayers[i];
                         iPlayers[i] = iPlayers[i + 1];
                         iPlayers[i + 1] = p;
                         flag = 1;
                     }
                 }
                 if(iCurMultiGame == iMP_MUSTODONT){
                     if(!iPlayers[i] -> body.MustodontStat.MakeTime && iPlayers[i + 1] -> body.MustodontStat.MakeTime){
                         p = iPlayers[i];
                         iPlayers[i] = iPlayers[i + 1];
                         iPlayers[i + 1] = p;
                         flag = 1;
                     }
                     if(iPlayers[i] -> body.MustodontStat.MakeTime && iPlayers[i + 1] -> body.MustodontStat.MakeTime && iPlayers[i] -> body.MustodontStat.MakeTime > iPlayers[i + 1] -> body.MustodontStat.MakeTime){
                         p = iPlayers[i];
                         iPlayers[i] = iPlayers[i + 1];
                         iPlayers[i + 1] = p;
                         flag = 1;
                     }
                 }
             }
         }
     }
     else {
         while(flag){
             flag = 0;
             for(i = 0; i < iNumPlayers - 1; i ++){
                 if(iPlayerRatings[i] < iPlayerRatings[i + 1]){
                     p = iPlayers[i];
                     tmp = iPlayerRatings[i];
                     iPlayers[i] = iPlayers[i + 1];
                     iPlayerRatings[i] = iPlayerRatings[i + 1];
                     iPlayers[i + 1] = p;
                     iPlayerRatings[i + 1] = tmp;
                     flag = 1;
                 }
             }
         }
     }
 }
References FINISHED_STATUS, XTList< Type >::first(), GAMING_STATUS, iNumPlayers, iPlayerRatings, iPlayers, players_list, and XTList< Type >::size().
Referenced by aciShowFrags(), and iPrepareResults().
iSoundQuant()
void iSoundQuant (int value = 0)
 {
     switch(value){
         case ACI_NOISE_SOUND:
             SOUND_NOISE();
             break;
         case ACI_SPEECH0_SOUND:
             SOUND_TALK0();
             break;
         case ACI_SPEECH1_SOUND:
             SOUND_TALK1();
             break;
         case ACI_SPEECH2_SOUND:
             SOUND_TALK2();
             break;
         case ACI_SPEECH3_SOUND:
             SOUND_TALK2();
             break;
         case ACI_WND_SOUND:
             SOUND_WINDOW();
             break;
         case ACI_GATE_SOUND:
             SOUND_GATE();
             break;
         case ACI_L0_OUTIN_SOUND:
         case ACI_L2_OUTIN_SOUND:
             SOUND_OUTIN();
             break;
         case ACI_L0_SWARM_SOUND:
         case ACI_L1_SWARM_SOUND:
             SOUND_SWARM();
             break;
         case ACI_L0_ANGRY_SOUND:
         case ACI_L1_ANGRY_SOUND:
         case ACI_L5_ANGRY_SOUND:
             SOUND_ANGRY();
             break;
         case ACI_L1_STEP0_SOUND:
         case ACI_L2_STEP_SOUND:
         case ACI_L3_STEP_SOUND:
         case ACI_L4_STEP_SOUND:
             SOUND_STEP();
             break;
         case ACI_L2_GETOUT_SOUND:
         case ACI_L3_GETOUT_SOUND:
         case ACI_L5_GETOUT_SOUND:
         case ACI_L6_GETOUT_SOUND:
             SOUND_GETOUT();
             break;
         case ACI_L4_HAND_SOUND:
             SOUND_HAND();
             break;
         case ACI_L5_SCRATCH_SOUND:
         case ACI_L6_SCRATCH_SOUND:
             SOUND_SCRATCH();
             break;
         case ACI_L5_CLAP_SOUND:
         case ACI_L6_CLAP_SOUND:
             SOUND_CLAP();
             break;
     }
 }
References ACI_GATE_SOUND, ACI_L0_ANGRY_SOUND, ACI_L0_OUTIN_SOUND, ACI_L0_SWARM_SOUND, ACI_L1_ANGRY_SOUND, ACI_L1_STEP0_SOUND, ACI_L1_SWARM_SOUND, ACI_L2_GETOUT_SOUND, ACI_L2_OUTIN_SOUND, ACI_L2_STEP_SOUND, ACI_L3_GETOUT_SOUND, ACI_L3_STEP_SOUND, ACI_L4_HAND_SOUND, ACI_L4_STEP_SOUND, ACI_L5_ANGRY_SOUND, ACI_L5_CLAP_SOUND, ACI_L5_GETOUT_SOUND, ACI_L5_SCRATCH_SOUND, ACI_L6_CLAP_SOUND, ACI_L6_GETOUT_SOUND, ACI_L6_SCRATCH_SOUND, ACI_NOISE_SOUND, ACI_SPEECH0_SOUND, ACI_SPEECH1_SOUND, ACI_SPEECH2_SOUND, ACI_SPEECH3_SOUND, ACI_WND_SOUND, SOUND_ANGRY, SOUND_CLAP, SOUND_GATE, SOUND_GETOUT, SOUND_HAND, SOUND_NOISE, SOUND_OUTIN, SOUND_SCRATCH, SOUND_STEP, SOUND_SWARM, SOUND_TALK0, SOUND_TALK1, SOUND_TALK2, and SOUND_WINDOW.
load_map_bmp()
void load_map_bmp (int num)
 {
     aScrDisp -> mapObj -> free();
     if(aScrDisp -> wMap -> world_ids[num] == -1 || !(aScrDisp -> map_names[aScrDisp -> wMap -> world_ids[num]])) ErrH.Abort("Map BMP not present...");
     aScrDisp -> mapObj -> load(aScrDisp -> map_names[aScrDisp -> wMap -> world_ids[num]],1);
     aScrDisp -> unlock();
     aciPrepareWorldsMenu();
     aciChangeWorld(num);
 }
References XErrorHandler::Abort(), aciChangeWorld(), aciPrepareWorldsMenu(), aScrDisp, ErrH, and wMap.
Referenced by ChangeWorld().
loadMouseFrames()
void loadMouseFrames (void)
 {
     XStream fh;
     if(actintLowResFlag)
         fh.open("resource/actint/640x480/mouse.bml",XS_IN);
     else
         fh.open("resource/actint/800x600/mouse.bml",XS_IN);
     fh > aMouseSizeX > aMouseSizeY > aMouseSize;
     aMouseFrames = new unsigned char[aMouseSizeX * aMouseSizeY * aMouseSize];
     fh.read(aMouseFrames,aMouseSizeX * aMouseSizeY * aMouseSize);
     fh.close();
     fh.open("resource/iscreen/mouse.bml");
     fh > iMouseSizeX > iMouseSizeY > iMouseSize;
     iMouseFrames = new unsigned char[iMouseSizeX * iMouseSizeY * iMouseSize];
     fh.read(iMouseFrames,iMouseSizeX * iMouseSizeY * iMouseSize);
     fh.close();
     MouseSize2 = iMouseSize/2;
 }
References actintLowResFlag, aMouseFrames, aMouseSize, aMouseSizeX, aMouseSizeY, XStream::close(), iMouseFrames, iMouseSize, iMouseSizeX, iMouseSizeY, MouseSize2, XStream::open(), XStream::read(), and XS_IN.
Referenced by aKeyInit(), and iInit().
mem_putspr()
void mem_putspr (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char * src, unsigned char * dest)
 {
     int i,j,index = 0,b_index = 0;
     index = x + y * bsx;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             if(src[b_index])
                 dest[index + j] = src[b_index];
             b_index ++;
         }
         index += bsx;
     }
 }
Referenced by aciBitmapMenuItem::redraw(), aciWorldInfo::redraw(), and CounterPanel::redraw().
mem_putspr_h()
void mem_putspr_h (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char * src, unsigned char * dest)
 {
     int i,j,index = x + y * bsx,b_index = 0;
     int h,h1;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             if(src[b_index]){
                 h1 = dest[index + j];
                 h = src[b_index];
                 if(h > h1)
                     dest[index + j] = h;
             }
             b_index ++;
         }
         index += bsx;
     }
 }
Referenced by invMatrix::redraw_matrix().
mem_rectangle()
void mem_rectangle (int x, int y, int sx, int sy, int bsx, int col_in, int col_out, int mode, void * buf)
 {
     int i,index,_sx,_sy;
     unsigned char* p = (unsigned char*)buf;
     index = x + y * bsx;
     memset(p + index,col_out,sx);
     for(i = 0; i < sy; i ++){
         p[index] = p[index + sx - 1] = col_out;
         index += bsx;
     }
     memset(p + index - bsx,col_out,sx);
     if(mode){
         _sx = sx - 2;
         _sy = sy - 2;
         if(_sx <= 0 || _sy <= 0) return;
         index = (x + 1) + (y + 1) * bsx;
         for(i = 0; i < _sy; i ++){
             memset(p + index,col_in,_sx);
             index += bsx;
         }
     }
 }
Referenced by aciWorldMap::show_jump_count().
redraw_fnc()
void redraw_fnc (int x, int y, int sx, int sy, int fnc)
 {
     switch(fnc){
         case FMENU_MAP:
             show_map(x,y,sx,sy);
             break;
         case FMENU_WMAP:
             if(aScrDisp -> wMap){
                 aScrDisp -> wMap -> redraw(x + ((sx - aScrDisp -> wMap -> SizeX) >> 1),y + ((sy - aScrDisp -> wMap -> SizeY) >> 1));
             }
             else {
                 XGR_Rectangle(x,y,sx,sy,0,0,XGR_FILLED);
             }
             break;
         case FMENU_TARGETS:
             break;
         case FMENU_CAMERAS:
             aciShowCamerasMenu(x,y,sx,sy);
             break;
         case FMENU_PARAMETERS:
             aciRedrawParamsPanel(x,y,sx,sy);
             break;
         default:
             XGR_Rectangle(x,y,sx,sy,0,0,XGR_FILLED);
             break;
     }
 }
References aciRedrawParamsPanel(), aciShowCamerasMenu(), aScrDisp, FMENU_CAMERAS, FMENU_MAP, FMENU_PARAMETERS, FMENU_TARGETS, FMENU_WMAP, show_map(), wMap, XGR_FILLED, and XGR_Rectangle.
Referenced by fncMenu::redraw().
restore_mouse_cursor()
void restore_mouse_cursor (void)
 {
     XGR_MouseSetCursor(MouseSizeX,MouseSizeY,MouseSize,MouseFrames);
     XGR_MouseSetSpot(MouseSizeX/2,0);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     XGR_MouseRedraw();
 }
References MouseFrames, MouseSize, MouseSizeX, MouseSizeY, XGM_NONE, XGR_MouseRedraw, XGR_MouseSetCursor, XGR_MouseSetSeq, and XGR_MouseSetSpot.
sdlEventToCode()
int sdlEventToCode (SDL_Event * event)
{
     switch (event->type) {
         case SDL_KEYDOWN:
         case SDL_KEYUP:
             return event->key.keysym.scancode;
         case SDL_MOUSEBUTTONDOWN:
         case SDL_MOUSEBUTTONUP:
             switch (event->button.button) {
                 case SDL_BUTTON_LEFT:
                     return iMOUSE_LEFT_PRESS_CODE;
                 case SDL_BUTTON_RIGHT:
                     return iMOUSE_RIGHT_PRESS_CODE;
             }
         case SDL_MOUSEMOTION:
             if (event->motion.state & SDL_BUTTON_LMASK)
                 return iMOUSE_LEFT_MOVE;
             else if (event->motion.state & SDL_BUTTON_RMASK)
                 return iMOUSE_RIGHT_MOVE;
             else
                 return iMOUSE_MOVE_CODE;
     }
     return -1;
 }
References iMOUSE_LEFT_MOVE, iMOUSE_LEFT_PRESS_CODE, iMOUSE_MOVE_CODE, iMOUSE_RIGHT_MOVE, and iMOUSE_RIGHT_PRESS_CODE.
Referenced by iScreenDispatcher::input_string_quant(), KeyCenter(), and actIntDispatcher::KeyQuant().
SelectCompasTarget()
void SelectCompasTarget (const char * n)
 {
     CompasTargetType* p;
     if(ActD.Active) ActD.Active->aiResolveFind.ClearResolve();
     if(!n){
         CompasObj.CurrentTarget = NULL;
         return;
     };
     p = CompasObj.TargetData;
     while(p){
         if(!strcmp(n,p->aciName)){
             CompasObj.CurrentTarget = p;
             return;
         };
         p = p->Next;
     };
     CompasObj.CurrentTarget = NULL;
 };
Referenced by aciDeleteFromTargets(), aciHandleSubmenuEvent(), and GeneralSystemOpen().
set_mouse()
void set_mouse (void)
 {
     XGR_MouseInit(XGR_MAXX/2,XGR_MAXY/2,MouseSizeX,MouseSizeY,MouseSize,MouseFrames);
     XGR_MouseSetSpot(MouseSizeX/2,0);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     iMouseLPressFlag = 0;
     iMouseRPressFlag = 0;
 }
References iMouseLPressFlag, iMouseRPressFlag, MouseFrames, MouseSize, MouseSizeX, MouseSizeY, XGM_NONE, XGR_MAXX, XGR_MAXY, XGR_MouseInit, XGR_MouseSetSeq, and XGR_MouseSetSpot.
Referenced by aKeyInit(), i_change_res(), and MS_init().
set_mouse_cursor()
void set_mouse_cursor (char * p, int sx, int sy)
 {
     XGR_MouseSetCursor(sx,sy,1,p);
     XGR_MouseSetSpot(sx/2,sy/2);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     XGR_MouseRedraw();
 }
References XGM_NONE, XGR_MouseRedraw, XGR_MouseSetCursor, XGR_MouseSetSeq, and XGR_MouseSetSpot.
set_screen()
void set_screen (int Dx, int Dy, int mode, int xcenter, int ycenter)
 {
     curGMap -> change(Dx,Dy,mode,xcenter,ycenter);
     Redraw = 1;
 }
References curGMap, and Redraw.
show_map()
void show_map (int x, int y, int sx, int sy)
 {
     int i,index,m_index,cx,cy,y0,x_index = 0,_x = 0,_y = 0,vy,sx2,sy2;
     int scr_x,scr_y,dx,scr_x0;
     unsigned char* ptr;
     bmlObject* p = aScrDisp -> mapObj;
     cx = (ViewX * p -> SizeX) >> MAP_POWER_X;
     cy = (ViewY * p -> SizeY) >> MAP_POWER_Y;
     sx2 = sx / 2;
     sy2 = sy / 2;
     vy = sy * ((1 << MAP_POWER_Y) / p -> SizeY) / 2;
     y0 = cy - sy2;
     if(y0 < 0) y0 += p -> SizeY;
     if(y0 >= p -> SizeY) y0 -= p -> SizeY;
     ptr = new unsigned char[sx * sy];
     memset(ptr,0,sx * sy);
     if(cx < sx2){
         dx = sx2 - cx;
         _y = y0;
         index = 0;
         m_index = y0 * p -> SizeX + p -> SizeX - dx;
         for(i = 0; i < sy; i ++){
             memcpy(ptr + index,p -> frames + m_index,dx);
             index += sx;
             m_index += p -> SizeX;
             _y ++;
             if(_y >= p -> SizeY){
                 m_index = p -> SizeX - dx;
                 _y = 0;
             }
         }
         _y = y0;
         index = dx;
         m_index = y0 * p -> SizeX;
         for(i = 0; i < sy; i ++){
             memcpy(ptr + index,p -> frames + m_index,sx - dx);
             index += sx;
             m_index += p -> SizeX;
             _y ++;
             if(_y >= p -> SizeY){
                 m_index = 0;
                 _y = 0;
             }
         }
     }
     else {
         if(p -> SizeX - cx < sx2){
             dx = sx2 - (p -> SizeX - cx);
             _y = y0;
             index = 0;
             m_index = y0 * p -> SizeX + p -> SizeX - (sx - dx);
             for(i = 0; i < sy; i ++){
                 memcpy(ptr + index,p -> frames + m_index,sx - dx);
                 index += sx;
                 m_index += p -> SizeX;
                 _y ++;
                 if(_y >= p -> SizeY){
                     m_index = p -> SizeX - (sx - dx);
                     _y = 0;
                 }
             }
             _y = y0;
             index = sx - dx;
             m_index = y0 * p -> SizeX;
             for(i = 0; i < sy; i ++){
                 memcpy(ptr + index,p -> frames + m_index,dx);
                 index += sx;
                 m_index += p -> SizeX;
                 _y ++;
                 if(_y >= p -> SizeY){
                     m_index = 0;
                     _y = 0;
                 }
             }
         }
         else {
             _y = y0;
             index = 0;
             m_index = y0 * p -> SizeX + cx - sx2;
             int max_frames_size = p->SizeX * p->SizeY * p->Size;
             for(i = 0; i < sy; i ++){
                 if (m_index + sx >= max_frames_size) {
                     memcpy(ptr + index, p -> frames + m_index, max_frames_size - m_index);
                 } else {
                     memcpy(ptr + index, p -> frames + m_index, sx);
                 }
                 index += sx;
                 m_index += p -> SizeX;
                 _y ++;
                 if(_y >= p -> SizeY){
                     m_index = cx - sx2;
                     _y = 0;
                 }
             }
         }
     }
     XGR_PutSpr(x,y,sx,sy,ptr,XGR_BLACK_FON);
     delete[] ptr;
     _y = 0;
     scr_x = sx2;
     scr_y = sy2;
 /*
     if(scr_x > MAP_PTR_X && scr_x < sx - MAP_PTR_X && scr_y > MAP_PTR_X && scr_y < sy - MAP_PTR_X)
         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[aciGamerColor],aciMapVngColors[aciGamerColor],XGR_FILLED);
 */
 #ifdef _ACI_MAP_TESTING_
     index = 2;
     for(_y = 0; _y < (1 << MAP_POWER_Y); _y += 256){
         for(_x = 0; _x < (1 << MAP_POWER_X); _x += 256){
             scr_x = -1;
             scr_x0 = ((_x * p -> SizeX) >> MAP_POWER_X);
             if(cx < sx2){
                 if(p -> SizeX - scr_x0 < dx)
                     scr_x = scr_x0 - (p -> SizeX - dx);
                 else {
                     if(scr_x0 < sx - dx)
                         scr_x = scr_x0 + dx;
                     else
                         scr_x = -1;
                 }
             }
             else {
                 if(p -> SizeX - cx < sx2){
                     if(p -> SizeX - scr_x0 < sx - dx)
                         scr_x = scr_x0 - (p -> SizeX - (sx - dx));
                     else {
                         if(scr_x0 < dx)
                             scr_x = scr_x0 + (sx - dx);
                         else
                             scr_x = -1;
                     }
                 }
                 else {
                     scr_x = scr_x0 - (cx - sx2);
                 }
             }
             scr_y = ((_y * p -> SizeY) >> MAP_POWER_Y) - y0;
             if(scr_y < 0)
                 scr_y += p -> SizeY;
             if(scr_x > MAP_PTR_X && scr_x < sx - MAP_PTR_X && scr_y > MAP_PTR_X && scr_y < sy - MAP_PTR_X){
                 switch(index){
                     case 1:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR1,MAP_COLOR1,XGR_FILLED);
                         break;
                     case 2:
                         XGR_SetPixel(x + scr_x,y + scr_y,(_y >> 8) & 255);
                         break;
                     case 3:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR3,MAP_COLOR3,XGR_FILLED);
                         break;
                 }
             }
         }
     }
 #else
     index = getObjectPosition(_x,_y);
     while(index != -1){
         if(index){
             scr_x = -1;
             scr_x0 = ((_x * p -> SizeX) >> MAP_POWER_X);
             if(cx < sx2){
                 if(p -> SizeX - scr_x0 < dx)
                     scr_x = scr_x0 - (p -> SizeX - dx);
                 else {
                     if(scr_x0 < sx - dx)
                         scr_x = scr_x0 + dx;
                     else
                         scr_x = -1;
                 }
             }
             else {
                 if(p -> SizeX - cx < sx2){
                     if(p -> SizeX - scr_x0 < sx - dx)
                         scr_x = scr_x0 - (p -> SizeX - (sx - dx));
                     else {
                         if(scr_x0 < dx)
                             scr_x = scr_x0 + (sx - dx);
                         else
                             scr_x = -1;
                     }
                 }
                 else {
                     scr_x = scr_x0 - (cx - sx2);
                 }
             }
             scr_y = ((_y * p -> SizeY) >> MAP_POWER_Y) - y0;
             if(scr_y < 0)
                 scr_y += p -> SizeY;
             if(scr_x > MAP_PTR_X && scr_x < sx - MAP_PTR_X && scr_y > MAP_PTR_X && scr_y < sy - MAP_PTR_X){
                 switch(index){
                     case 1:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR1,MAP_COLOR1,XGR_FILLED);
                         break;
 #ifdef _ACI_SHOW_BUGS_ON_MAP_
                     case 2:
                         XGR_SetPixel(x + scr_x,y + scr_y,MAP_COLOR2);
                         break;
 #endif
                     case 3:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,MAP_COLOR3,MAP_COLOR3,XGR_FILLED);
                         break;
                     case 4:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[0],aciMapVngColors[0],XGR_FILLED);
                         break;
                     case 5:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[1],aciMapVngColors[1],XGR_FILLED);
                         break;
                     case 6:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[2],aciMapVngColors[2],XGR_FILLED);
                         break;
                     case 7:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[3],aciMapVngColors[3],XGR_FILLED);
                         break;
                     case 8:
                         if(scr_x > MAP_PTR_XL && scr_x < sx - MAP_PTR_XL && scr_y > MAP_PTR_XL && scr_y < sy - MAP_PTR_XL)
                             XGR_Rectangle(x + scr_x - MAP_PTR_XL2,y + scr_y - MAP_PTR_XL2,MAP_PTR_XL,MAP_PTR_XL,aciMapVngColors[3],aciMapVngColors[0],XGR_FILLED);
                         break;
                     case 9:
                         if(scr_x > MAP_PTR_XL && scr_x < sx - MAP_PTR_XL && scr_y > MAP_PTR_XL && scr_y < sy - MAP_PTR_XL)
                             XGR_Rectangle(x + scr_x - MAP_PTR_XL2,y + scr_y - MAP_PTR_XL2,MAP_PTR_XL,MAP_PTR_XL,aciMapVngColors[3],aciMapVngColors[1],XGR_FILLED);
                         break;
                     case 10:
                         if(scr_x > MAP_PTR_XL && scr_x < sx - MAP_PTR_XL && scr_y > MAP_PTR_XL && scr_y < sy - MAP_PTR_XL)
                             XGR_Rectangle(x + scr_x - MAP_PTR_XL2,y + scr_y - MAP_PTR_XL2,MAP_PTR_XL,MAP_PTR_XL,aciMapVngColors[3],aciMapVngColors[2],XGR_FILLED);
                         break;
                     case 11:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[5],aciMapVngColors[5],XGR_FILLED);
                         break;
                     case 12:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[6],aciMapVngColors[6],XGR_FILLED);
                         break;
                     case 13:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[7],aciMapVngColors[7],XGR_FILLED);
                         break;
                     case 14:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[8],aciMapVngColors[8],XGR_FILLED);
                         break;
                     case 15:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[9],aciMapVngColors[9],XGR_FILLED);
                         break;
                     case 16:
                         XGR_Rectangle(x + scr_x - MAP_PTR_X2,y + scr_y - MAP_PTR_X2,MAP_PTR_X,MAP_PTR_X,aciMapVngColors[10],aciMapVngColors[10],XGR_FILLED);
                         break;
                 }
             }
         }
         index = getObjectPosition(_x,_y);
     }
 #endif
 }
References aScrDisp, getObjectPosition(), MAP_COLOR1, MAP_COLOR2, MAP_COLOR3, MAP_POWER_X, MAP_POWER_Y, MAP_PTR_X, MAP_PTR_X2, bmlObject::Size, bmlObject::SizeX, bmlObject::SizeY, ViewX, ViewY, XGR_BLACK_FON, XGR_FILLED, XGR_PutSpr, XGR_Rectangle, and XGR_SetPixel.
Referenced by redraw_fnc().
swap_buf_col()
void swap_buf_col (int src, int dest, int sx, int sy, unsigned char * buf)
 {
     int i,j,index = 0;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             if(buf[index] == src) buf[index] = dest;
             index ++;
         }
     }
 }
Referenced by aciWorldInfo::redraw(), CounterPanel::redraw(), invMatrix::redraw_matrix(), and invMatrix::redraw_shadow_cells().
uvs_aciChangeItem()
void uvs_aciChangeItem (int id_from, int id_to)
 {
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     if(!(aScrDisp -> flags & AS_ISCREEN))
         it = aScrDisp -> get_item(id_to);
     else
         it = aScrDisp -> get_iitem(id_to);
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id_from){
             it -> clone(p);
         }
         p = p1;
     }
     aScrDisp -> curMatrix -> set_redraw();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id_from){
                 it -> clone(aScrDisp -> curItem);
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
         }
     }
     if(aScrDisp -> flags & AS_ISCREEN){
         if(!aScrDisp -> secondMatrix) return;
         p = (invItem*)aScrDisp -> secondMatrix -> items -> last;
         while(p){
             p1 = (invItem*)p -> prev;
             if(p -> ID == id_from){
                 it -> clone(p);
             }
             p = p1;
         }
         aScrDisp -> secondMatrix -> set_redraw();
     }
 }
References aScrDisp, and curMatrix.
uvs_aciChangeOneItem() [1/2]
void uvs_aciChangeOneItem (int id_from, int id_to, int x, int y)
 {
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     if(!(aScrDisp -> flags & AS_ISCREEN))
         it = aScrDisp -> get_item(id_to);
     else
         it = aScrDisp -> get_iitem(id_to);
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id_from && p -> MatrixX == x && p -> MatrixY == y){
             it -> clone(p);
 //            if(p -> uvsDataPtr) ((uvsActInt*)p -> uvsDataPtr) -> type = id_to;
             return;
         }
         p = p1;
     }
     aScrDisp -> curMatrix -> set_redraw();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id_from && aScrDisp -> curItem -> MatrixX == x && aScrDisp -> curItem -> MatrixY == y){
                 it -> clone(aScrDisp -> curItem);
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
                 return;
         }
     }
     if(aScrDisp -> flags & AS_ISCREEN){
         if(!aScrDisp -> secondMatrix) return;
         p = (invItem*)aScrDisp -> secondMatrix -> items -> last;
         while(p){
             p1 = (invItem*)p -> prev;
             if(p -> ID == id_from && p -> MatrixX == x && p -> MatrixY == y){
                 it -> clone(p);
             }
             p = p1;
         }
         aScrDisp -> secondMatrix -> set_redraw();
     }
 }
References aScrDisp, and curMatrix.
Referenced by uvsChangeGoodsInList(), and uvsChangeTabuTask().
uvs_aciChangeOneItem() [2/2]
void uvs_aciChangeOneItem (int id_from, int id_to, uvsActInt * ptr)
 {
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     it = aScrDisp -> get_iitem(id_to);
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id_from && p -> uvsDataPtr == ptr){
             it -> clone(p);
             return;
         }
         p = p1;
     }
     aScrDisp -> curMatrix -> set_redraw();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id_from && aScrDisp -> curItem -> uvsDataPtr == ptr){
                 it -> clone(aScrDisp -> curItem);
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
                 return;
         }
     }
     if(aScrDisp -> flags & AS_ISCREEN){
         if(!aScrDisp -> secondMatrix) return;
         p = (invItem*)aScrDisp -> secondMatrix -> items -> last;
         while(p){
             p1 = (invItem*)p -> prev;
             if(p -> ID == id_from && p -> uvsDataPtr == ptr){
                 it -> clone(p);
             }
             p = p1;
         }
         aScrDisp -> secondMatrix -> set_redraw();
     }
 }
References aScrDisp, curMatrix, and prev.
uvs_aciKillItem()
int uvs_aciKillItem (int id, int id1)
 {
     int ret = 0;
     uvsActInt* u;
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return ret;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     if(id1 != -1){
         it = aScrDisp -> get_iitem(id1);
     }
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id){
             if(id1 == -1){
                 aScrDisp -> curMatrix -> remove_item(p);
                 aScrDisp -> free_item(p);
             }
             else {
                 it -> clone(p);
                 u = (uvsActInt*)p -> uvsDataPtr;
                 u -> type = it -> ID;
             }
             ret = 1;
         }
         p = p1;
     }
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id){
             if(id1 == -1){
                 aScrDisp -> free_item(aScrDisp -> curItem);
                 aScrDisp -> curItem = NULL;
                 aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
                 restore_mouse_cursor();
             }
             else {
                 it -> clone(aScrDisp -> curItem);
                 u = (uvsActInt*)aScrDisp -> curItem -> uvsDataPtr;
                 u -> type = it -> ID;
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
             }
             ret = 1;
         }
     }
     aScrDisp -> curMatrix -> set_redraw();
     if((aScrDisp -> flags & AS_ISCREEN) && GCharItem && GCharItem -> type == id){
         aciML_D -> key_trap(AML_KEY,AML_KILL_ELEECH_CODE);
     }
     return ret;
 }
References aScrDisp, curMatrix, and prev.
Referenced by uvsBunch::end_harvest(), uvsBunch::end_race(), and uvsVanger::race_result().
uvs_aciKillOneItem()
int uvs_aciKillOneItem (int id, int x, int y)
 {
     int ret = 0;
     invItem* p,*p1;
     if(!aScrDisp -> curMatrix) return ret;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id && p -> MatrixX == x && p -> MatrixY == y){
             aScrDisp -> curMatrix -> remove_item(p);
             aScrDisp -> free_item(p);
             return 1;
         }
         p = p1;
     }
     return 0;
 }
References aScrDisp, curMatrix, and prev.
Referenced by uvsVanger::checkDolly(), uvsVanger::prepare_list_for_ActInt(), and uvsDeleteItem().
uvsChangeCycle()
void uvsChangeCycle (void)
{
     uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
     int i = pb -> currentStage;
     pb -> cycleTable[i].cirtQ += pb -> cycleTable[i].cirtMAX;
 }
uvsChangeDominance()
void uvsChangeDominance (void)
{
     GamerResult.dominance += 20;
     ShowDominanceMessage(20);
     if (GamerResult.dominance > 100) GamerResult.dominance = 100;
 }
References uvsGamerResult::dominance, GamerResult, and ShowDominanceMessage().
uvsChangeLuck()
void uvsChangeLuck (void)
{
     GamerResult.luck += 20;
     ShowLuckMessage(20);
     if (GamerResult.luck > 100) GamerResult.luck = 100;
 }
References GamerResult, uvsGamerResult::luck, and ShowLuckMessage().
uvsGetNameByID()
char* uvsGetNameByID (int type, int & ID)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(pe){
         ID = pe -> SeekID( type );
         if (ID != -1)
             return pe -> name;
         pe = (uvsEscave*)pe -> next;
     }
     while(ps){
         ID = ps -> SeekID( type );
         if (ID != -1)
             return ps -> name;
         ps = (uvsSpot*)ps -> next;
     }
     return NULL;
 }
Referenced by aciGetItemEscave().
uvsReturnWorldGamerVisit()
int uvsReturnWorldGamerVisit (int where)
{
     if(where < 0 || where > 9) ErrH.Abort("uvsReturnWorldGamerVisit : Bad world");
     return WorldTable[where] -> GamerVisit;
 }
References XErrorHandler::Abort(), ErrH, uvsEscave::GamerVisit, and WorldTable.
Referenced by aciWorldExploredInfo().
uvsTabuComplete()
void uvsTabuComplete (int i)
{
     uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
     uvsChangeTownTabuTask(i);
 }
References UVS_TABUTASK_STATUS::GOOD, uvsChangeTabuTask(), and uvsChangeTownTabuTask().
uvsTabuCreate()
void uvsTabuCreate (uvsActInt * pa, int num)
{
     int TabuTaskID;
     if (Gamer -> Pescave)
         TabuTaskID = Gamer -> Pescave -> TabuTaskID + num - 1;
     else
         TabuTaskID = Gamer -> Pspot -> TabuTaskID + num -1;
     pa -> param1 = Gamer -> Pworld -> gIndex<<16;
     pa -> param2 = TabuTaskID;
     pa -> price = 1;
     pa -> sell_price = 1;
 }
References Gamer, uvsEscave::Pworld, and uvsEscave::TabuTaskID.
Variable Documentation
_PI128
const double _PI128 = 3.14/128.0
Referenced by a_calc_tables().
aCellFrame
unsigned char* aCellFrame extern
Referenced by build_cell_frame(), free_cell_frame(), CounterPanel::redraw(), invMatrix::redraw_matrix(), and invMatrix::redraw_shadow_cells().
aCellSize
int aCellSize extern
Referenced by build_cell_frame().
aci_CellSize
int aci_CellSize extern
Referenced by actIntDispatcher::i_finit(), and actIntDispatcher::i_init().
ACI_FRAG_COL0
const unsigned ACI_FRAG_COL0 = (252 | (246 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL1
const unsigned ACI_FRAG_COL1 = (143 | (135 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL2
const unsigned ACI_FRAG_COL2 = (156 | (151 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL3
const unsigned ACI_FRAG_COL3 = (173 | (166 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL4
const unsigned ACI_FRAG_COL4 = (200 | (195 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL5
const unsigned ACI_FRAG_COL5 = (238 | (233 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL6
const unsigned ACI_FRAG_COL6 = (238 | (233 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL7
const unsigned ACI_FRAG_COL7 = (238 | (233 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL8
const unsigned ACI_FRAG_COL8 = (252 | (246 << 8))
Referenced by aciShowFrags().
ACI_FRAG_COL9
const unsigned ACI_FRAG_COL9 = (156 | (151 << 8))
Referenced by aciShowFrags().
aci_SecondMatrixID
int aci_SecondMatrixID extern
Referenced by aciInitAviID().
aciAutoRun
int aciAutoRun = 0
Referenced by Object::direct_keyboard_control(), and iLoadData().
aciAutoSaveFlag
int aciAutoSaveFlag = 0
Referenced by aciAutoSave(), and acsSaveData().
aciBadPhraseFlag
int aciBadPhraseFlag = 0
aciBreathFlag
int aciBreathFlag = 0
Referenced by aci_LocationQuantPrepare(), and aciML_Dispatcher::event_quant().
aciCurAviIndex
int aciCurAviIndex = 0
Referenced by aciChangeAviIndex(), and aciInitAviID().
aciCurAviIndexDelta
int aciCurAviIndexDelta = 0
Referenced by aciInitAviID().
aciCurColorScheme
unsigned char* aciCurColorScheme extern
Referenced by aciInitMechosInfo(), aciInitPanel(), aciInitPricePanel(), and aciRedrawParamsPanel().
aciCurCredits02
int aciCurCredits02 = 0
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurDominance
int aciCurDominance extern
Referenced by aciRedrawParamsPanel().
aciCurLuck
int aciCurLuck extern
Referenced by aciRedrawParamsPanel().
aciCurMechosID
int aciCurMechosID = 0
Referenced by aciPrevShopItem(), aciSetShopItem(), and RegisterValues().
aciCurRaceInfo
char* aciCurRaceInfo = NULL
aciCurRaceType
char* aciCurRaceType = NULL
Referenced by aciShowRacingPlace(), and ActionDispatcher::Quant().
aciDgPostfix
unsigned char* aciDgPostfix = NULL
aciDgPrefix
unsigned char* aciDgPrefix = NULL
aciEndSpeech
int aciEndSpeech = 0
Referenced by aci_LocationQuantPrepare(), aciNextPhrase(), and aciML_Dispatcher::event_quant().
aciEscaveDead
int aciEscaveDead = 0
Referenced by aci_LocationQuantPrepare(), aciAskQuestion(), aciBuildQuestList(), and aciNextPhrase().
aciEscaveEmpty
int aciEscaveEmpty = 0
Referenced by aci_LocationQuantPrepare(), aciAskQuestion(), aciBuildQuestList(), and aciNextPhrase().
aciGamerColor
int aciGamerColor = 0
aciImgText
aciScreenText* aciImgText = NULL
Referenced by aciInitEndGame(), and aciTextQuant().
aciItmTextQueue
invItem** aciItmTextQueue = NULL
Referenced by aciInitItmTextQueue(), and aciReadItmText().
aciItmTextQueueCur
int aciItmTextQueueCur = 0
Referenced by aciInitItmTextQueue(), and aciReadItmText().
aciItmTextQueueSize
int aciItmTextQueueSize = 0
Referenced by aciInitItmTextQueue(), aciReadItmText(), and actIntDispatcher::EventQuant().
aciKeyboardLocked
int aciKeyboardLocked = 0
Referenced by acsQuant(), Object::analysis(), iChatInit(), KeyCenter(), and actIntDispatcher::KeyQuant().
aciLoadLog
int aciLoadLog = 0
Referenced by aciFreeAll(), LoadingRTO2::Init(), and FirstEscaveRTO::Init().
aciMouseFlagL
int aciMouseFlagL = 0
Referenced by aMS_init(), and aMS_LeftUnpress().
aciMouseFlagR
int aciMouseFlagR = 0
Referenced by aMS_init(), and aMS_RightUnpress().
aciPickupDevices
int aciPickupDevices extern
Referenced by aciCheckItemPickUp().
aciPickupItems
int aciPickupItems extern
Referenced by aciCheckItemPickUp().
aciPrevDominance
int aciPrevDominance extern
Referenced by aciRedrawParamsPanel().
aciPrevJumpCount
int aciPrevJumpCount extern
Referenced by actIntDispatcher::EventQuant(), actIntDispatcher::i_finit(), actIntDispatcher::init(), and aciWorldMap::quant().
aciPrevLuck
int aciPrevLuck extern
Referenced by aciRedrawParamsPanel().
aciRacingFlag
int aciRacingFlag = 0
Referenced by actIntDispatcher::flush(), and ActionDispatcher::Quant().
aciShopMenuLog
int aciShopMenuLog = 0
aciSpeechBegLocked
int aciSpeechBegLocked = 0
Referenced by aci_LocationQuantPrepare(), aciNextPhrase(), and aciStartSpeech().
aciSpeechEndLocked
int aciSpeechEndLocked = 0
Referenced by aci_LocationQuantPrepare(), aciNextPhrase(), and aciStartSpeech().
aciSpeechMode
int aciSpeechMode = 2
Referenced by aciStartSpeech().
aciSpeechSeq
aciML_EventSeq* aciSpeechSeq = NULL
Referenced by aciStartSpeech().
aciSpeechStarted
int aciSpeechStarted = 0
Referenced by aci_LocationQuantPrepare(), aciNextPhrase(), and aciStartSpeech().
aciSTR_AIR_RESERVE
const char* aciSTR_AIR_RESERVE = aciSTR_AIR_RESERVE1
Referenced by aciInitStrings().
aciSTR_AUTOSAVE
const char* aciSTR_AUTOSAVE = aciSTR_AUTOSAVE1
Referenced by aciInitStrings(), and acsSaveData().
aciSTR_BROKEN
const char* aciSTR_BROKEN = aciSTR_BROKEN1
Referenced by aciInitStrings().
aciSTR_BURST
const char* aciSTR_BURST = aciSTR_BURST1
Referenced by aciInitStrings().
aciSTR_Checkpoints
const char* aciSTR_Checkpoints = aciSTR_Checkpoints1
Referenced by aciInitStrings(), and aciShowFrags().
aciSTR_DAMAGE
const char* aciSTR_DAMAGE = aciSTR_DAMAGE1
Referenced by aciInitStrings().
aciSTR_DAY
const char* aciSTR_DAY = aciSTR_DAY1
Referenced by aciInitStrings().
aciSTR_DEATHS
const char* aciSTR_DEATHS = aciSTR_DEATHS1
Referenced by aciInitStrings(), and aciShowFrags().
aciSTR_DOMINANCE
const char* aciSTR_DOMINANCE = aciSTR_DOMINANCE1
Referenced by aciInitStrings(), and aciRedrawParamsPanel().
aciSTR_EMPTY_SLOT
const char* aciSTR_EMPTY_SLOT = aciSTR_EMPTY_SLOT1
Referenced by aciInitStrings(), acsPrepareSlotName(), and acsPrepareSlotNameInput().
aciSTR_ENERGY_SHIELD
const char* aciSTR_ENERGY_SHIELD = aciSTR_ENERGY_SHIELD1
Referenced by aciInitStrings().
aciSTR_IN_PACK
const char* aciSTR_IN_PACK = aciSTR_IN_PACK1
Referenced by aciInitStrings().
aciSTR_KILLS
const char* aciSTR_KILLS = aciSTR_KILLS1
Referenced by aciInitStrings(), and aciShowFrags().
aciSTR_LOAD
const char* aciSTR_LOAD = aciSTR_LOAD1
Referenced by aciInitStrings().
aciSTR_LUCK
const char* aciSTR_LUCK = aciSTR_LUCK1
Referenced by aciInitStrings(), and aciRedrawParamsPanel().
aciSTR_MECHANIC_ARMOR
const char* aciSTR_MECHANIC_ARMOR = aciSTR_MECHANIC_ARMOR1
Referenced by aciInitStrings().
aciSTR_NO_CASH
const char* aciSTR_NO_CASH = aciSTR_NO_CASH1
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_imove_quant().
aciSTR_OFF
const char* aciSTR_OFF = aciSTR_OFF1
Referenced by aciAdd2Targets(), aciDeleteFromTargets(), aciHandleSubmenuEvent(), aciInitStrings(), aciRefreshTargetsMenu(), aciScreenInputField::change_state(), aciScreenInputField::get_state(), actIntDispatcher::init_submenu(), and aciScreenInputField::set_state().
aciSTR_ON
const char* aciSTR_ON = aciSTR_ON1
Referenced by aciInitStrings(), aciScreenInputField::change_state(), and aciScreenInputField::set_state().
aciSTR_PICKUP_ITEMS_OFF
const char* aciSTR_PICKUP_ITEMS_OFF = aciSTR_PICKUP_ITEMS_OFF1
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_move_quant().
aciSTR_PICKUP_WEAPONS_OFF
const char* aciSTR_PICKUP_WEAPONS_OFF = aciSTR_PICKUP_WEAPONS_OFF1
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_move_quant().
aciSTR_PRICE
const char* aciSTR_PRICE = aciSTR_PRICE1
Referenced by aciGetPrice(), and aciInitStrings().
aciSTR_PutThis
const char* aciSTR_PutThis = aciSTR_PutThis1
Referenced by aciInitStrings(), and actIntDispatcher::inv_mouse_imove_quant().
aciSTR_RESTORING_SPEED
const char* aciSTR_RESTORING_SPEED = aciSTR_RESTORING_SPEED1
Referenced by aciInitStrings().
aciSTR_SECONDS
const char* aciSTR_SECONDS = aciSTR_SECONDS1
Referenced by aciInitStrings().
aciSTR_SHOTS
const char* aciSTR_SHOTS = aciSTR_SHOTS1
Referenced by aciInitStrings().
aciSTR_SPIRAL_CAPACITY
const char* aciSTR_SPIRAL_CAPACITY = aciSTR_SPIRAL_CAPACITY1
Referenced by aciInitStrings().
aciSTR_UNDEFINED_PRICE
const char* aciSTR_UNDEFINED_PRICE = aciSTR_UNDEFINED_PRICE1
Referenced by aciGetPrice(), and aciInitStrings().
aciSTR_UNNAMED_SAVE
const char* aciSTR_UNNAMED_SAVE = aciSTR_UNNAMED_SAVE1
Referenced by aciInitStrings(), acsPrepareSlotNameInput(), and acsSaveData().
aciSTR_VELOCITY
const char* aciSTR_VELOCITY = aciSTR_VELOCITY1
Referenced by aciInitStrings().
aciSTR_Ware1
const char* aciSTR_Ware1 = aciSTR_Ware11
Referenced by aciInitStrings(), and aciShowFrags().
aciSTR_Ware2
const char* aciSTR_Ware2 = aciSTR_Ware21
Referenced by aciInitStrings(), and aciShowFrags().
aciSTR_WORKING_TIME
const char* aciSTR_WORKING_TIME = aciSTR_WORKING_TIME1
Referenced by aciInitStrings().
aciTeleportEvent
int aciTeleportEvent extern
Referenced by aciHandleSubmenuEvent().
aciTreeData
aciCHTree* aciTreeData = NULL
Referenced by aciCHandler().
aciWorldIndex
int aciWorldIndex = -1
Referenced by VangerUnit::CreateVangerUnit(), actIntDispatcher::EventQuant(), and VangerUnit::Quant().
aciXConv
XBuffer* aciXConv
Referenced by aciGetItemLoad(), aciGetPrice(), aciInitAviID(), aciRedrawParamsPanel(), aciShowRacingPlace(), and aPutChar32().
aCosTable
int* aCosTable = NULL
Referenced by a_calc_tables().
acsAllocFlag
int acsAllocFlag = 0
Referenced by acsQuant().
acsBackupStr
char* acsBackupStr extern
Referenced by acsPrepareSlotNameInput(), aciScreenDispatcher::CancelInput(), aciScreenDispatcher::DoneInput(), and aciScreenDispatcher::PrepareInput().
acsCurrentSlotID
int acsCurrentSlotID = ACS_SAVE_SLOT0
Referenced by acsPrepareSlotNameInput(), and acsSaveData().
acsCurrentSlotNum
int acsCurrentSlotNum = 0
Referenced by acsPrepareSlotNameInput(), and acsSaveData().
acsScreenID
int acsScreenID = 1
Referenced by acsQuant().
actintActiveFlag
int actintActiveFlag = 0
Referenced by actIntQuant(), and iScrQuantFinit().
actIntLog
int actIntLog = 0
Referenced by iScreenDispatcher::aci_move_screen(), iScreenDispatcher::alloc_mem(), iScreenDispatcher::free_mem(), iFinitQuant(), iHandleExtEvent(), iKeyTrap(), iMS_LeftUnpress(), iMS_RightUnpress(), LoadingRTO3::Init(), iOutEscaveFinit(), iOutEscaveInit(), iOutEscaveQuant(), iPreInitFirst(), iQuantFirst(), iQuantPrepare(), iQuantSecond(), iScrQuantFinit(), iScrQuantPrepare(), iSecondInit(), ivMapPrepare(), iScreenDispatcher::key_trap(), iScreenDispatcher::move2screen(), iScreen::prepare(), and iScreenDispatcher::redraw().
actintLowResFlag
int actintLowResFlag = 0
Referenced by MainMenuRTO::Finit(), loadMouseFrames(), and xtInitApplication().
actIntPal
unsigned char* actIntPal extern
aImageBmp
char* aImageBmp extern
aIndArrowBML
bmlObject* aIndArrowBML = NULL
Referenced by aciFreeAll(), aInit(), aIndData::build_pict(), and aIndData::init().
aIndBackBML
bmlObject* aIndBackBML = NULL
Referenced by aciFreeAll(), and aIndData::build_pict().
aIndDataBML
bmlObject* aIndDataBML = NULL
Referenced by aciFreeAll(), and aIndData::build_pict().
aInitFlag
int aInitFlag = 0
Referenced by aKeyTrap().
aMouseFrames
unsigned char* aMouseFrames extern
Referenced by aciSet_aMouse(), and loadMouseFrames().
aMouseSize
short aMouseSize extern
Referenced by aciSet_aMouse(), and loadMouseFrames().
aMouseSizeX
short aMouseSizeX extern
Referenced by aciSet_aMouse(), and loadMouseFrames().
aMouseSizeY
short aMouseSizeY extern
Referenced by aciSet_aMouse(), and loadMouseFrames().
aScrDisp
actIntDispatcher* aScrDisp extern
Referenced by aci_iScreenQuant(), aci_LocationQuantFinit(), aci_LocationQuantPrepare(), aci_SendEvent(), aciActivateItemFunction(), aciAdd2Targets(), aciAddRubox(), aciAddTabutask(), aciAddTeleportMenuItem(), aciAskQuestion(), aciAutoMoveItems(), aciAutoSave(), aciBuildQuestList(), aciBuildShopList(), aciBuyItem(), aciCHandler(), aciChange2Raffa(), aciChangeItem(), aciChangeList(), aciChangeWorld(), aciCheckItemCredits(), aciCheckItemPickUp(), aciCheckSellItem(), aciCheckSlot(), aciChooseShopItem(), aciClearQuestMenu(), aciClearTeleportMenu(), aciCloseShopMenu(), aciCompleteTabutask(), aciDeactivateItemFunction(), aciDeleteFromTargets(), aciDeleteTeleportMenuItem(), aciDisableParametersMenu(), aciDropMoveItem(), aciEscaveKickOut(), aciExpropriation(), aciFreeAll(), aciGetCurMatrixPrice(), aciGetEleech(), aciGetItemCoords(), aciGetItemEscave(), aciGetLast(), aciGetRubox(), aciHandleCameraEvent(), aciInitAviID(), aciInitAviObject(), aciInitCurMatrixPtr(), aciInitEvLineID(), aciInitInfoPanels(), aciInitItmTextQueue(), aciInitShopAvi(), aciInitShopButtons(), aciInitShopItems(), aciInitWorldIDs(), aciKillLinks(), aciNewMechos(), aciNextPhrase(), aciOfferEleech(), aciOpenWorldLink(), aciPrepareMenus(), aciPrepareText(), aciPrepareWorldsMenu(), aciPrevShopItem(), aciPutItem(), aciReadItmText(), aciRedrawParamsPanel(), aciRefreshTargetsMenu(), aciReInitItem(), aciReInitItemXY(), aciRemoveItem(), aciSell_Item(), aciSellMoveItem(), aciSendEvent2actint(), aciSendPrompt(), aciSetCameraMenu(), aciSetMechName(), aciSetRedraw(), aciSetShopItem(), aciSetTimePanel(), aciShopMenuDown(), aciShopMenuUp(), aciShowBlockPhrase(), aciShowCamerasMenu(), aciShowFrags(), aciShowRacingPlace(), aciStartSpeech(), aciVMapPrepare(), aciWaitNextPeriod(), aciWorldExploredInfo(), aciWorldLinkExist(), aciWorldLinksOFF(), aciWorldLinksON(), acsHandleExtEvent(), acsLoadData(), acsQuant(), acsSaveData(), actIntQuant(), aKeyQuant(), aMS_LeftPress(), aMS_Movement(), aMS_RightPress(), aRedraw(), change_screen(), load_map_bmp(), aciPromptData::redraw(), redraw_fnc(), show_map(), uvs_aciChangeItem(), uvs_aciChangeOneItem(), uvs_aciKillItem(), and uvs_aciKillOneItem().
aScrFonts
aciFont** aScrFonts = NULL
Referenced by aFreeFonts(), aLoadFonts(), aOutStr(), aPutChar(), aPutStr(), aStrHeight(), aStrLen(), fncMenuItem::init(), aciWorldInfo::redraw(), invItem::redraw(), CounterPanel::redraw(), InfoPanel::redraw(), and fncMenu::set_prefix().
aScrFonts32
aciFont** aScrFonts32 = NULL
Referenced by aLoadFonts32(), aOutText32(), aOutText32clip(), aPutStr32(), aStrHeight32(), aStrLen32(), aTextHeight32(), aTextWidth32(), iChatInputChar(), CounterPanel::redraw(), and InfoPanel::redraw().
aSinTable
int* aSinTable = NULL
Referenced by a_calc_tables().
beebos
int beebos extern
Referenced by ComlineAnalyze().
camera_moving_xy_enable
int camera_moving_xy_enable extern
Referenced by aciHandleCameraEvent(), and aciSetCameraMenu().
camera_moving_z_enable
int camera_moving_z_enable extern
Referenced by aciHandleCameraEvent().
camera_rotate_enable
int camera_rotate_enable extern
Referenced by aciHandleCameraEvent(), and aciSetCameraMenu().
camera_slope_enable
int camera_slope_enable extern
Referenced by aciHandleCameraEvent(), and aciSetCameraMenu().
ConTimer
uvsContimer ConTimer extern
Referenced by ItemsDispatcher::Close(), StuffObject::CreateStuff(), StuffObject::DeviceOut(), iGameMap::draw(), StuffObject::ImpulseAction(), ActionDispatcher::PromptQuant(), StuffObject::Quant(), and ScreenQuant().
curMatrix
int curMatrix extern
Referenced by aci_setMatrixBorder(), aciAddRubox(), aciAutoMoveItems(), aciCancelMatrix(), aciChange2Raffa(), aciChangeItem(), aciCheckSlot(), aciCompleteTabutask(), aciExpropriation(), aciGetCurMatrixPrice(), aciGetItemCoords(), aciGetLast(), aciGetRubox(), aciInitCurMatrixPtr(), aciInitItmTextQueue(), aciInitShopItems(), aciKillLinks(), aciNewMechos(), aciReInitItem(), aciReInitItemXY(), aciShowScMatrix(), aciSwapMatrices(), uvs_aciChangeItem(), uvs_aciChangeOneItem(), uvs_aciKillItem(), and uvs_aciKillOneItem().
curMatrixID
int curMatrixID extern
Referenced by actIntDispatcher::init().
dgMood
int dgMood extern
Referenced by aciStartSpeech(), and DiagenDispatcher::getQout().
GameQuantReturnValue
int GameQuantReturnValue extern
Gamer
uvsVanger* Gamer extern
GCharItem
uvsActInt* GCharItem extern
Referenced by aciFreeUVS(), aciGetEleech(), acsLoadData(), uvsBunch::begin_race(), and uvsBunch::end_race().
GGamer
uvsActInt* GGamer extern
Referenced by aciAddRubox(), aciFreeUVS(), aciGetGamerItem(), aciGetRubox(), aciSell_Item(), and acsLoadData().
iCellSize
int iCellSize extern
iCurMultiGame
int iCurMultiGame extern
Referenced by aciShowFrags().
iEvLineID
int iEvLineID extern
Referenced by aciBuildShopList(), aciChangeLineID(), aciChangeList(), aciCheckCredits(), aciChooseShopItem(), aciInitAviID(), aciInitEvLineID(), aciInitShopList(), aciNextShopItem(), aciPrevShopItem(), aciSellMoveItem(), and aciSetShopItem().
iMouseFrames
unsigned char* iMouseFrames extern
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseSize
short iMouseSize extern
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseSizeX
short iMouseSizeX extern
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseSizeY
short iMouseSizeY extern
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseX
int iMouseX extern
Referenced by aciCheckSellItem(), aciChooseShopItem(), aMS_LeftUnpress(), and aMS_RightUnpress().
iMouseY
int iMouseY extern
Referenced by aciCheckSellItem(), aciChooseShopItem(), aMS_LeftUnpress(), and aMS_RightUnpress().
iMultiFlag
int iMultiFlag extern
Referenced by aciInitEndGame(), iPreInitFirst(), and iQuantFirst().
iNumPlayers
int iNumPlayers extern
Referenced by aciShowFrags(), iPrepareResults(), and iSortPlayers().
iPlayers
PlayerData** iPlayers extern
Referenced by aciShowFrags(), iPreparePlayerResults(), iPrepareResults(), and iSortPlayers().
iScreenActive
int iScreenActive extern
Referenced by iFinitQuant(), iHandleExtEvent(), and iQuantFirst().
iScrOpt
iScreenOption** iScrOpt extern
Referenced by aciHandleCameraEvent(), and aciSetCameraMenu().
iscrPal
unsigned char* iscrPal extern
iShopItem
iListElement* iShopItem
Referenced by aciBuildShopList(), aciCheckCredits(), aciChooseShopItem(), aciInitAviID(), aciNextShopItem(), aciPrevShopItem(), aciSellMoveItem(), and aciSetShopItem().
iSlotNumber
int iSlotNumber extern
Referenced by acsLoadData(), and iHandleExtEvent().
iVideoPath
const char* iVideoPath extern
Referenced by aciInitAviID(), ShowImageRTO::Init(), and SetupPath().
MouseFrames
unsigned char* MouseFrames extern
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
MouseSize
short MouseSize extern
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
MouseSize2
int MouseSize2 extern
Referenced by loadMouseFrames().
MouseSizeX
short MouseSizeX extern
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
MouseSizeY
short MouseSizeY extern
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
palbuf
unsigned char* palbuf extern
Referenced by aOutStr(), ChangeWorld(), GeneralTableOpen(), PassageImageType::Hide(), PalPoint::Quant(), VangerUnit::Quant(), PalPoint::Set(), and PassageImageType::Show().
prevWorld
int prevWorld extern
Referenced by actIntDispatcher::i_finit(), and actIntDispatcher::i_init().
RAM16
int RAM16 extern
Referenced by aciHandleCameraEvent().
ShowImageKeyFlag
int ShowImageKeyFlag extern
Referenced by ShowImageRTO::Init(), ShowImageRTO::Quant(), and ShowImageKeyPress().
ShowImageMouseFlag
int ShowImageMouseFlag extern
Referenced by ShowImageRTO::Init(), ShowImageRTO::Quant(), and ShowImageMousePress().
uvsCurrentWorldUnable
int uvsCurrentWorldUnable extern
Referenced by aciInitMechosInfo().
ViewX
int ViewX extern
Referenced by show_map().
ViewY
int ViewY extern
Referenced by show_map().