Vangers: lib/xsound/avi.cpp File Reference
avi.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include "_xsound.h"
#include "xglobal.h"
#include "xcritical.h"
#include "xgraph.h"
#include "avi.h"
Macros
#define AV_FRAME_ALLOC avcodec_alloc_frame
#define AV_PACKET_UNREF av_free_packet
#define AV_CODEC_PAR (LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(57, 33, 100))
Functions
void FinitAVI (void)
void xtRegisterSysFinitFnc (void(*fPtr)(void), int id)
void xtUnRegisterSysFinitFnc (int id)
int AVIopen (char *filename, int flags, int channel, void **avi)
void AVIplay (void *avi, int xx, int yy)
void AVIstop (void *avi)
void AVIclose (void *avi)
int AVIwidth (void *avi)
int AVIheight (void *avi)
int AVIredraw (void *avi)
void AVIredraw (void *avi, int state)
void AVIdraw (void *avi)
void AVIGetData (void *avi, void *data)
void * AVIGetPalette (void *avi)
Macro Definition Documentation
AV_CODEC_PAR
#define AV_CODEC_PAR (LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(57, 33, 100))
AV_FRAME_ALLOC
#define AV_FRAME_ALLOC avcodec_alloc_frame
AV_PACKET_UNREF
#define AV_PACKET_UNREF av_free_packet
Function Documentation
AVIclose()
void AVIclose (void * avi)
 {
     AVIFile* p = (AVIFile*)avi;
     aviXList.RemoveElement((XListElement*)p);
     delete p;
 }
Referenced by iAVIElement::free(), and iScreenObject::init().
AVIdraw()
void AVIdraw (void * avi)
 {
     ((AVIFile *)avi) -> draw();
 }
References AVIFile::draw().
Referenced by iScreenElement::redraw().
AVIGetData()
void AVIGetData (void * avi, void * data)
 {
     XCriticalSection critical(((AVIFile *)avi) -> avCriticalSection);
     int xs = AVIwidth(avi);
     int ys = AVIheight(avi);
     int i, i2;
     if (((AVIFile *)avi)->pFrame)
         for(i=0; i<ys; ++i){
             for (i2=0;i2<xs;++i2){
                 ((unsigned char *)data)[i*xs+i2]=
                 ((unsigned char *)((AVIFile *)avi)->pFrame->data[0])[i*((AVIFile *)avi)->pFrame->linesize[0]+i2];
             }
         }
 }
References AVIFile::avCriticalSection, AVIheight(), AVIwidth(), and AVIFile::pFrame.
Referenced by iScreenElement::redraw().
AVIGetPalette()
void* AVIGetPalette (void * avi)
 {
     XCriticalSection critical(((AVIFile *)avi) -> avCriticalSection);
     return ((AVIFile *)avi) -> palette;
 }
References AVIFile::avCriticalSection, and AVIFile::palette.
Referenced by iAVIElement::load().
AVIheight()
int AVIheight (void * avi)
 {
     return ((AVIFile *)avi) -> height;
 }
References AVIFile::height.
Referenced by AVIGetData(), iScreenObject::init(), and iAVIElement::init_size().
AVIopen()
int AVIopen (char * filename, int flags, int channel, void ** avi)
 {
     AVIFile *newavi = new AVIFile;
     if(!newavi -> open(filename,flags,channel))
         return 0;
     *avi = newavi;
     aviXList.AddElement((XListElement*)newavi);
     xtRegisterSysFinitFnc(FinitAVI,XAVI_SYSOBJ_ID);
     return 1;
 }
References AVIFile::AVIFile(), AVIFile::filename, AVIFile::flags, and AVIFile::open().
Referenced by iScreenObject::init(), and iAVIElement::load().
AVIplay()
void AVIplay (void * avi, int xx, int yy)
 {
     ((AVIFile *)avi) -> pause = 0;
     ((AVIFile *)avi) -> x = xx;
     ((AVIFile *)avi) -> y = yy;
 }
References AVIFile::pause, AVIFile::x, and AVIFile::y.
Referenced by iAVIElement::load().
AVIredraw() [1/2]
int AVIredraw (void * avi)
 {
     return ((AVIFile *)avi) -> redraw;
 }
References AVIFile::redraw.
AVIredraw() [2/2]
void AVIredraw (void * avi, int state)
 {
     ((AVIFile *)avi) -> redraw = state;
 }
References AVIFile::redraw.
AVIstop()
void AVIstop (void * avi)
 {
     ((AVIFile *)avi) -> pause = 1;
 }
References AVIFile::pause.
Referenced by iAVIElement::free().
AVIwidth()
int AVIwidth (void * avi)
 {
     return ((AVIFile *)avi) -> width;
 }
References AVIFile::width.
Referenced by AVIGetData(), iScreenObject::init(), and iAVIElement::init_size().
FinitAVI()
void FinitAVI (void)
 {
     AVIFile* p,*p1;
     p = (AVIFile*)aviXList.fPtr;
     while(p){
         p1 = (AVIFile*)p -> next;
         AVIclose(p);
         p = p1;
     }
 }
xtRegisterSysFinitFnc()
void xtRegisterSysFinitFnc (void(*)(void) fPtr, int id)
 {
     xtAddSysObj(&XSysFinitLst,fPtr,id);
 }
xtUnRegisterSysFinitFnc()
void xtUnRegisterSysFinitFnc (int id)
 {
     xtDeleteSysObj(&XSysFinitLst,id);
 }