Vangers: Se3f Class Reference
Se3f Class Reference
#include <xmath.h>
Public Member Functions
Se3f ()
Se3f (const QuatF &q_, const Vect3f &d_)
Se3f (const MatXf &X)
xm_inline operator Se3d () const
Se3f & set (const QuatF &q_, const Vect3f &d_)
Se3f & set (const MatXf &X)
const QuatF & rot () const
const Vect3f & trans () const
QuatF & rot ()
Vect3f & trans ()
xm_inline Se3f & mult (const Se3f &T, const Se3f &U)
xm_inline Se3f & premult (const Se3f &T)
xm_inline Se3f & postmult (const Se3f &T)
xm_inline Se3f & operator*= (const Se3f &T)
xm_inline Se3f operator* (const Se3f &U) const
xm_inline Se3f & invert (const Se3f &T)
xm_inline Se3f & invert ()
xm_inline Vect3f & xformVect (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & xformVect (Vect3f &v) const
xm_inline Vect3f & xformPoint (const Vect3f &p, Vect3f &xp) const
xm_inline Vect3f & xformPoint (Vect3f &p) const
xm_inline Vect3f & invXformVect (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & invXformVect (Vect3f &v) const
xm_inline Vect3f & invXformPoint (const Vect3f &p, Vect3f &xp) const
xm_inline Vect3f & invXformPoint (Vect3f &p) const
Static Public Attributes
static const Se3f ID
Friends
ostream & operator<< (ostream &os, const Se3f &se3)
istream & operator>> (istream &is, Se3f &se3)
Detailed Description
Constructor & Destructor Documentation
Se3f() [1/3]
Se3f::Se3f () inline
 {}
Se3f() [2/3]
Se3f::Se3f (const QuatF & q_, const Vect3f & d_) inline
 { set(q_, d_); }
References set().
Se3f() [3/3]
Se3f::Se3f (const MatXf & X) inline
 { set(X); }
References set().
Member Function Documentation
invert() [1/2]
Se3f & Se3f::invert ()
 {
   q.s_ = -q.s_;
   q.xform(d);
   d.negate();
   return *this;
 }
References Vect3f::negate(), and QuatF::xform().
invert() [2/2]
Se3f & Se3f::invert (const Se3f & T)
 {
   q.s_ = -T.q.s_;
   q.x_ =  T.q.x_;
   q.y_ =  T.q.y_;
   q.z_ =  T.q.z_;
   q.xform(T.d, d);
   d.negate(d);
   return *this;
 }
References Vect3f::negate(), and QuatF::xform().
invXformPoint() [1/2]
Vect3f & Se3f::invXformPoint (const Vect3f & p, Vect3f & xp) const
 {
   xp.sub(p, d);
   q.invXform(xp);
   return xp;
 }
References QuatF::invXform(), and Vect3f::sub().
invXformPoint() [2/2]
Vect3f & Se3f::invXformPoint (Vect3f & p) const
 {
   p.sub(d);
   q.invXform(p);
   return p;
 }
References QuatF::invXform(), and Vect3f::sub().
invXformVect() [1/2]
Vect3f & Se3f::invXformVect (const Vect3f & v, Vect3f & xv) const
 {
   q.invXform(v, xv);
   return xv;
 }
References QuatF::invXform().
invXformVect() [2/2]
Vect3f & Se3f::invXformVect (Vect3f & v) const
 {
   q.invXform(v);
   return v;
 }
References QuatF::invXform().
mult()
Se3f & Se3f::mult (const Se3f & T, const Se3f & U)
 {
   q.mult(T.q, U.q);
   T.q.xform(U.d, d);
   d.add(d, T.d);
   return *this;
 }
References Vect3f::add(), QuatF::mult(), and QuatF::xform().
Referenced by operator*().
operator Se3d()
Se3f::operator Se3d () const
 {
     return Se3d(q, d);
 }
operator*()
xm_inline Se3f Se3f::operator* (const Se3f & U) const inline
 { Se3f T; return T.mult(*this, U); }
References mult().
operator*=()
xm_inline Se3f& Se3f::operator*= (const Se3f & T) inline
 { return postmult(T); }
References postmult().
postmult()
Se3f & Se3f::postmult (const Se3f & T)
 {
   Vect3f v;
   q.xform(T.d, v);
   d.add(v);
   q.postmult(T.q);
   return *this;
 }
References Vect3f::add(), QuatF::postmult(), and QuatF::xform().
Referenced by operator*=().
premult()
Se3f & Se3f::premult (const Se3f & T)
 {
   q.premult(T.q);
   T.q.xform(d);
   d.add(T.d);
   return *this;
 }
References Vect3f::add(), QuatF::premult(), and QuatF::xform().
rot() [1/2]
QuatF& Se3f::rot () inline
 {return q;}
rot() [2/2]
const QuatF& Se3f::rot () const inline
 {return q;}
Referenced by MatXf::set().
set() [1/2]
Se3f& Se3f::set (const MatXf & X) inline
 { q.set(X.rot()); d = X.trans(); return *this; }
References MatXf::rot(), QuatF::set(), and MatXf::trans().
set() [2/2]
Se3f& Se3f::set (const QuatF & q_, const Vect3f & d_) inline
 { q = q_; d = d_; return *this; }
Referenced by Se3f().
trans() [1/2]
Vect3f& Se3f::trans () inline
 {return d;}
trans() [2/2]
const Vect3f& Se3f::trans () const inline
 {return d;}
Referenced by MatXf::set().
xformPoint() [1/2]
Vect3f & Se3f::xformPoint (const Vect3f & p, Vect3f & xp) const
 {
   q.xform(p, xp);
   xp.add(d);
   return xp;
 }
References Vect3f::add(), and QuatF::xform().
xformPoint() [2/2]
Vect3f & Se3f::xformPoint (Vect3f & p) const
 {
   q.xform(p);
   p.add(d);
   return p;
 }
References Vect3f::add(), and QuatF::xform().
xformVect() [1/2]
Vect3f & Se3f::xformVect (const Vect3f & v, Vect3f & xv) const
 {
   q.xform(v, xv);
   return xv;
 }
References QuatF::xform().
xformVect() [2/2]
Vect3f & Se3f::xformVect (Vect3f & v) const
 {
   q.xform(v);
   return v;
 }
References QuatF::xform().
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & os, const Se3f & se3) friend
 {
   return os << se3.q << se3.d;
 }
operator>>
istream& operator>> (istream & is, Se3f & se3) friend
 {
     return is >> se3.q >> se3.d;
 }
Member Data Documentation
ID
const Se3f Se3f::ID static
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp