Vangers: MatX2f Class Reference
MatX2f Class Reference
#include <xmath.h>
Public Member Functions
MatX2f (const Mat2f &r, const Vect2f &t)
void set (const Mat2f &r, const Vect2f &t)
void invert ()
Vect2f invXform (const Vect2f &v) const
Public Attributes
Mat2f rot
Vect2f trans
Friends
Vect2f & operator*= (Vect2f &v, const MatX2f &m)
Detailed Description
Constructor & Destructor Documentation
MatX2f()
MatX2f::MatX2f (const Mat2f & r, const Vect2f & t) inline
 : rot(r), trans(t) {}
Member Function Documentation
invert()
void MatX2f::invert () inline
 { rot.invert(); trans = -rot.invXform(trans); }
References Mat2f::invert(), Mat2f::invXform(), rot, and trans.
invXform()
Vect2f MatX2f::invXform (const Vect2f & v) const inline
 { return rot.invXform(v - trans); }
References Mat2f::invXform(), rot, and trans.
set()
void MatX2f::set (const Mat2f & r, const Vect2f & t) inline
 { rot = r; trans = t; }
References rot, and trans.
Friends And Related Function Documentation
operator*=
Vect2f& operator*= (Vect2f & v, const MatX2f & m) friend
 { v *= m.rot; v += m.trans; return v; }
Member Data Documentation
rot
Mat2f MatX2f::rot
Referenced by invert(), invXform(), and set().
trans
Vect2f MatX2f::trans
Referenced by invert(), invXform(), and set().
The documentation for this class was generated from the following file:
lib/xtool/xmath/xmath.h