Vangers: XZIP_FileHeader Class Reference
XZIP_FileHeader Class Reference
#include <zip_resource.h>
Public Member Functions
void SetName (char *p)
unsigned size (void) const
unsigned offset (void) const
char * data (void) const
char * name (void) const
void save (XStream &fh)
XZIP_FileHeader (void)
XZIP_FileHeader (char *fname, unsigned offs, unsigned size, void *ext_ptr, int ext_sz)
XZIP_FileHeader (XStream &fh)
~XZIP_FileHeader (void)
Public Attributes
void * list
XZIP_FileHeader * prev
XZIP_FileHeader * next
Detailed Description
Constructor & Destructor Documentation
XZIP_FileHeader() [1/3]
XZIP_FileHeader::XZIP_FileHeader (void)
 {
     fileName = NULL;
     dataOffset = 0;
     dataSize = 0;
     extDataSize = 0;
     extData = NULL;
     list = NULL;
 }
References list, and NULL.
XZIP_FileHeader() [2/3]
XZIP_FileHeader::XZIP_FileHeader (char * fname, unsigned offs, unsigned size, void * ext_ptr, int ext_sz)
 {
     SetName(fname);
     dataOffset = offs;
     dataSize = size;
     list = NULL;
     if(ext_sz){
         extData = new char[extDataSize = ext_sz];
         memcpy(extData,(char*)ext_ptr,extDataSize);
     }
 }
References list, NULL, SetName(), and size().
XZIP_FileHeader() [3/3]
XZIP_FileHeader::XZIP_FileHeader (XStream & fh)
 {
     int sz;
     char fname[256];
     fh > sz;
     fh.read(fname,sz);
     fname[sz] = 0;
     SetName(fname);
     fh > dataOffset > dataSize > extDataSize;
     if(extDataSize){
         extData = new char[extDataSize];
         fh.read(extData,extDataSize);
     }
 }
References XStream::read(), and SetName().
~XZIP_FileHeader()
XZIP_FileHeader::~XZIP_FileHeader (void)
 {
     if(fileName) free(fileName);
     if(extData)
         delete extData;
 }
Member Function Documentation
data()
char* XZIP_FileHeader::data (void) const inline
 { return extData; }
name()
char* XZIP_FileHeader::name (void) const inline
 { return fileName; }
offset()
unsigned XZIP_FileHeader::offset (void) const inline
 { return dataOffset; }
save()
void XZIP_FileHeader::save (XStream & fh)
 {
     int sz = strlen(fileName);
     fh < sz;
     fh.write(fileName,sz);
     fh < dataOffset < dataSize < extDataSize;
     if(extDataSize)
         fh.write(extData,extDataSize);
 }
References XStream::write().
SetName()
void XZIP_FileHeader::SetName (char * p)
 {
     int i,sz = strlen(p);
     fileName = strdup(p);
     for(i = 0; i < sz; i ++)
         if(fileName[i] == '/') fileName[i] = '\\';
 }
Referenced by XZIP_FileHeader().
size()
unsigned XZIP_FileHeader::size (void) const inline
 { return dataSize; }
Referenced by XZIP_FileHeader().
Member Data Documentation
list
void* XZIP_FileHeader::list
Referenced by XZIP_FileHeader().
next
XZIP_FileHeader* XZIP_FileHeader::next
prev
XZIP_FileHeader* XZIP_FileHeader::prev
The documentation for this class was generated from the following files:
lib/xtool/zip_resource.h
lib/xtool/xresource/zip_resource.cpp