Vangers: XQueue< Type > Class Template Reference
XQueue< Type > Class Template Reference
#include <xcontainers.h>
Public Member Functions
XQueue (int size)
int tell ()
int empty ()
void clear ()
int simple_put (Type p)
Type simple_get ()
int put (Type p)
Type get ()
Detailed Description
template<class Type>
class XQueue< Type >
Constructor & Destructor Documentation
XQueue()
template<class Type > XQueue< Type >::XQueue (int size) inline
 {
     if(!IsPowerOf2(sz))
         ErrH.Abort("XQueue's size must be a power of 2",sz);
     buffer = new Type[size = sz];
     clear();
 }
References XErrorHandler::Abort(), ErrH, and IsPowerOf2().
Member Function Documentation
clear()
template<class Type > void XQueue< Type >::clear (void) inline
 {
     head = tail = 0;
 }
References head.
empty()
template<class Type > int XQueue< Type >::empty inline
 {
     return head == tail;
 }
References head.
Referenced by Player::send().
get()
template<class Type > Type XQueue< Type >::get (void) inline
 {
     int ind;
     while(head != tail) {
         ind = tail;
         tail = (tail + 1) & (size - 1);
         Type&& t = (Type)(-1);
         if(buffer[ind] != t) {
             return buffer[ind];
         }
     }
     return (Type)0;
 }
References head.
Referenced by Player::clear_object_queue(), and Player::send().
put()
template<class Type > int XQueue< Type >::put (Type p) inline
 {
     int i = tail;
     while(i != head){
         if(buffer[i] == p){
             buffer[i] = (Type)(-1);
             break;
             }
         i = (i + 1) & (size - 1);
         }
     int new_head = (head + 1) & (size - 1);
     if(new_head != tail){
         buffer[head] = p;
         head = new_head;
         return 1;
         }
     ErrH.Abort("XQueue overflow");
     return 0;
 }
References XErrorHandler::Abort(), ErrH, and head.
Referenced by World::attach_player(), Player::clear_object_queue(), World::process_set_position(), Game::put_event_for_all(), Player::put_object(), and Player::receive().
simple_get()
template<class Type > Type XQueue< Type >::simple_get inline
 {
     int ind;
     if(head != tail){
         ind = tail;
         tail = (tail + 1) & (size - 1);
         return buffer[ind];
         }
     return (Type)0;
 }
References head.
simple_put()
template<class Type > int XQueue< Type >::simple_put (Type p) inline
 {
     buffer[head] = p;
     head = (head + 1) & (size - 1);
     if(head == tail)
         tail = (tail + 1) & (size - 1);
     return 1;
 }
References head.
tell()
template<class Type > int XQueue< Type >::tell (void) inline
 {
     return size + head - tail & size - 1;
 }
References head.
Referenced by Player::clear_object_queue().
The documentation for this class was generated from the following file:
src/xcontainers.h