Vangers: OutputEventBuffer Class Reference
OutputEventBuffer Class Reference
#include <server.h>
Public Member Functions
OutputEventBuffer (unsigned int size)
int send (XSocket &sock)
void begin_event (int event_ID)
void end_event ()
OutputEventBuffer (unsigned int size)
void clear ()
void create_permanent_object (int ID, int x, int y, int radius, int flags=0)
void update_object (int ID, int x, int y, int flags=0)
void delete_object (int ID)
void begin_create_z_object (int Type, int ID)
void begin_server_data ()
void begin_direct_send (unsigned int mask)
void begin_event (int event_ID)
void end_body ()
void register_name (char *name, char *password)
void set_world (int world, int y_size_of_world)
void set_position (int x, int y, int y_half_size_of_screen)
void set_player_body (PlayerBody &body)
int number_of_events ()
int send (int system_send=0, XSocket &sock=main_socket)
int send_simple_query (int event, XSocket &sock=main_socket)
int send_simple_query (int event, unsigned char data, XSocket &sock=main_socket)
int send_simple_query (int event, unsigned char data1, unsigned char data2, XSocket &sock=main_socket)
Public Member Functions inherited from XBuffer
XBuffer (unsigned int sz=XB_DEFSIZE)
XBuffer (void *p, int sz)
~XBuffer (void)
void SetRadix (int r)
void SetDigits (int d)
void alloc (unsigned int sz)
void free (void)
void fill (char fc='\0')
void set (int off, int mode=XB_BEG)
void init (void)
int search (char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int search (const char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int end () const
unsigned int tell (void) const
unsigned int length (void) const
char * address ()
unsigned int read (void *s, unsigned int len)
unsigned int write (const void *s, unsigned int len, int bin_flag=1)
void handleOutOfSize ()
XBuffer & operator< (const char *v)
XBuffer & operator< (char v)
XBuffer & operator< (unsigned char v)
XBuffer & operator< (short v)
XBuffer & operator< (unsigned short v)
XBuffer & operator< (int v)
XBuffer & operator< (unsigned int v)
XBuffer & operator< (long v)
XBuffer & operator< (unsigned long v)
XBuffer & operator< (float v)
XBuffer & operator< (double v)
XBuffer & operator< (long double v)
XBuffer & operator> (char *v)
XBuffer & operator> (char &v)
XBuffer & operator> (unsigned char &v)
XBuffer & operator> (short &v)
XBuffer & operator> (unsigned short &v)
XBuffer & operator> (int &v)
XBuffer & operator> (unsigned int &v)
XBuffer & operator> (long &v)
XBuffer & operator> (unsigned long &v)
XBuffer & operator> (float &v)
XBuffer & operator> (double &v)
XBuffer & operator> (long double &v)
XBuffer & operator<= (char)
XBuffer & operator<= (unsigned char)
XBuffer & operator<= (short)
XBuffer & operator<= (unsigned short)
XBuffer & operator<= (int)
XBuffer & operator<= (unsigned int)
XBuffer & operator<= (long)
XBuffer & operator<= (unsigned long)
XBuffer & operator<= (long long int)
XBuffer & operator<= (float)
XBuffer & operator<= (double)
XBuffer & operator<= (long double)
XBuffer & operator>= (char &)
XBuffer & operator>= (unsigned char &)
XBuffer & operator>= (short &)
XBuffer & operator>= (unsigned short &)
XBuffer & operator>= (int &)
XBuffer & operator>= (unsigned int &)
XBuffer & operator>= (long &)
XBuffer & operator>= (unsigned long &)
XBuffer & operator>= (float &)
XBuffer & operator>= (double &)
XBuffer & operator>= (long double &)
char * GetBuf ()
char * operator() (int offs)
char * operator() (unsigned int offs)
XBuffer & operator++ ()
XBuffer & operator-- ()
XBuffer & operator+= (int v)
XBuffer & operator-= (int v)
XBuffer & operator+= (unsigned int v)
XBuffer & operator-= (unsigned int v)
char operator[] (int ind) const
char operator() () const
char & operator[] (int ind)
char & operator() ()
template<class T >
XBuffer & write (const T &v)
template<class T >
XBuffer & read (T &v)
Additional Inherited Members
Public Attributes inherited from XBuffer
char * buf
unsigned int size
unsigned int offset
int radix
int digits
int MakeFree
int automatic_realloc
Detailed Description
Constructor & Destructor Documentation
OutputEventBuffer() [1/2]
OutputEventBuffer::OutputEventBuffer (unsigned int size)
                                                      : XBuffer(size) {
     pointer_to_size_of_event = -1;
 }
OutputEventBuffer() [2/2]
OutputEventBuffer::OutputEventBuffer (unsigned int size)
Member Function Documentation
begin_create_z_object()
void OutputEventBuffer::begin_create_z_object (int Type, int ID)
 {
     n_event++;
     pointer_to_size_of_event = tell();
     *this < short(0) < (unsigned char)zCREATE_OBJECT_BY_CLIENT < (unsigned int)GLOBAL_CLOCK() < (unsigned char)Type < (unsigned char)ID;
     OUT_EVENTS_LOG(zCREATE_OBJECT_BY_CLIENT);
 }
References GLOBAL_CLOCK, OUT_EVENTS_LOG, XBuffer::tell(), and zCREATE_OBJECT_BY_CLIENT.
begin_direct_send()
void OutputEventBuffer::begin_direct_send (unsigned int mask)
 {
     n_event++;
     pointer_to_size_of_event = tell();
     *this < short(0) < (unsigned char)DIRECT_SENDING < mask;
     OUT_EVENTS_LOG(DIRECT_SENDING);
 }
References DIRECT_SENDING, OUT_EVENTS_LOG, and XBuffer::tell().
Referenced by MessageDispatcher::send().
begin_event() [1/2]
void OutputEventBuffer::begin_event (int event_ID)
{
     if (pointer_to_size_of_event != -1)
         SERVER_ERROR("There wasn't the end of the event", 0);
     pointer_to_size_of_event = offset;
     *this < short(0) < (unsigned char)event_ID;
 }
References XBuffer::offset, and SERVER_ERROR.
Referenced by connect_to_server(), Server::get_games_list(), Server::get_top_list(), Game::get_total_list_of_players_data(), Player::receive(), restore_connection(), and Player::send().
begin_event() [2/2]
void OutputEventBuffer::begin_event (int event_ID)
begin_server_data()
void OutputEventBuffer::begin_server_data ()
 {
     n_event++;
     pointer_to_size_of_event = tell();
     *this < short(0) < (unsigned char)SET_GAME_DATA;
     OUT_EVENTS_LOG(SET_GAME_DATA);
 }
References OUT_EVENTS_LOG, SET_GAME_DATA, and XBuffer::tell().
Referenced by send_server_data().
clear()
void OutputEventBuffer::clear (void)
 {
     n_event = 0;
     offset = 0;
     pointer_to_the_first_event = 0;
     pointer_to_the_last_event = 0;
     pointer_to_size_of_event = -1;
 }
References XBuffer::offset.
Referenced by connect_to_server(), disconnect_from_server(), and restore_connection().
create_permanent_object()
void OutputEventBuffer::create_permanent_object (int ID, int x, int y, int radius, int flags = 0)
 {
     n_event++;
     pointer_to_size_of_event = tell();
     *this < short(0) < (unsigned char)(CREATE_PERMANENT_OBJECT | flags);
     *this < ID < (unsigned int)GLOBAL_CLOCK() < (unsigned short)x < (unsigned short)y < (unsigned short)radius;
     OUT_EVENTS_LOG1(CREATE_PERMANENT_OBJECT,ID);
 }
delete_object()
void OutputEventBuffer::delete_object (int ID)
 {
     n_event++;
     pointer_to_size_of_event = tell();
     *this < short(0) < (unsigned char)DELETE_OBJECT < ID < (unsigned int)GLOBAL_CLOCK();
     OUT_EVENTS_LOG1(DELETE_OBJECT,ID);
 }
References DELETE_OBJECT, GLOBAL_CLOCK, OUT_EVENTS_LOG1, and XBuffer::tell().
end_body()
void OutputEventBuffer::end_body ()
 {
     int i;
     if(pointer_to_size_of_event < 0)
         ErrH.Abort("There wasn't a beginning of event");
     //std::cout<<"OutputEventBuffer::end_body size:"<<tell() - pointer_to_size_of_event - sizeof(short int)<<std::endl;
     *(short*)(address() + pointer_to_size_of_event) = tell() - pointer_to_size_of_event - sizeof(short int);
     int ev_ID,event_ID = *(unsigned char*)(address() + pointer_to_size_of_event + 2);
     if((event_ID & (~ECHO_EVENT)) == UPDATE_OBJECT) {
         int object_ID = *(int*)(address() + pointer_to_size_of_event + 3);
         for(i = pointer_to_the_first_event; i < pointer_to_the_last_event; i += full_event_size(i)) {
             ev_ID = *((unsigned char*)(address() + i + 2));
             if((ev_ID & (~ECHO_EVENT)) == UPDATE_OBJECT) {
                 if(*((int*)(address() + i + 3)) == object_ID) {
                     int event_size = full_event_size(i);
                     memmove(address() + i, address() + i + event_size, tell() - (i + event_size));
                     *(unsigned char*)(address() + pointer_to_size_of_event + 2) |= ev_ID & ECHO_EVENT;
                     offset -= event_size;
                     pointer_to_the_last_event -= event_size;
                     n_event--;
                     OUT_EVENTS_LOG1(Pack_update,object_ID);
                     break;
                 }
             }
         }
     }
     pointer_to_size_of_event = -1;
 }
References XErrorHandler::Abort(), XBuffer::address(), ECHO_EVENT, ErrH, XBuffer::offset, OUT_EVENTS_LOG1, XBuffer::tell(), and UPDATE_OBJECT.
Referenced by connect_to_server(), restore_connection(), MessageDispatcher::send(), and send_server_data().
end_event()
void OutputEventBuffer::end_event ()
{
     if (pointer_to_size_of_event == -1)
         SERVER_ERROR("There wasn't the begining of the event", 0);
     int off = tell();
     set(pointer_to_size_of_event);
     *this < short(off - pointer_to_size_of_event - 2);
     set(off);
     pointer_to_size_of_event = -1;
 }
References SERVER_ERROR, XBuffer::set(), and XBuffer::tell().
Referenced by Server::get_games_list(), Server::get_top_list(), Game::get_total_list_of_players_data(), Player::receive(), and Player::send().
number_of_events()
int OutputEventBuffer::number_of_events () inline
 { return n_event; }
register_name()
void OutputEventBuffer::register_name (char * name, char * password)
 {
     n_event++;
     *this < short(1 + strlen(name) + 1 + strlen(password) + 1) < (unsigned char)(REGISTER_NAME) < name < char(0) < password < char(0);
     OUT_EVENTS_LOG(REGISTER_NAME);
 }
References OUT_EVENTS_LOG, and REGISTER_NAME.
send() [1/2]
int OutputEventBuffer::send (int system_send = 0, XSocket & sock = main_socket)
 {
     if(pointer_to_size_of_event > 0)
         ErrH.Abort("There wasn't an end of event");
     int sent_size = 0;
     //if(sock() && (system_send | enable_send))
     if(sock()){
         sent_size = sock.send(address(),tell());
         //if(!system_send)
         //  enable_send = 0;
         }
     int unsent_size = tell() - sent_size;
     n_sended_bytes += sent_size;
 #ifdef _FOUT_
     if(sent_size)
         fout < "Send: " <= SDL_GetTicks() < "\t" <= sent_size < "\t" <= unsent_size < "\t" <= n_event < "\n";
 #endif
     if(!unsent_size){
         n_sended_events += n_event;
         pointer_to_the_first_event = 0;
         pointer_to_the_last_event = 0;
         n_event = 0;
         offset = 0;
         }
     else{
         OUT_EVENTS_LOG1(Send_would_block,unsent_size);
         now_unsent_size = unsent_size;
         while(pointer_to_the_first_event < sent_size){
             pointer_to_the_first_event += full_event_size(pointer_to_the_first_event);
             n_sended_events++;
             n_event--;
             }
         if(sent_size){
             memmove(buf,buf + sent_size,unsent_size);
             offset -= sent_size;
             pointer_to_the_first_event -= sent_size;
             }
         pointer_to_the_last_event = offset;
         }
     return sent_size;
 }
References XErrorHandler::Abort(), XBuffer::address(), XBuffer::buf, ErrH, fout, n_sended_bytes, n_sended_events, now_unsent_size, XBuffer::offset, OUT_EVENTS_LOG1, XSocket::send(), and XBuffer::tell().
send() [2/2]
int OutputEventBuffer::send (XSocket & sock)
{
     if (pointer_to_size_of_event != -1)
         SERVER_ERROR("There wasn't the end of the event", 0);
     unsigned int sent = sock.send(buf, tell());
     if (sent == tell())
         init();
     else {
         memmove(buf, buf + sent, tell() - sent);
         offset -= sent;
     }
     return sent;
 }
References XBuffer::buf, XBuffer::init(), XBuffer::offset, XSocket::send(), SERVER_ERROR, and XBuffer::tell().
Referenced by connect_to_server(), restore_connection(), Player::send(), MessageDispatcher::send(), send_player_body(), send_simple_query(), and set_world().
send_simple_query() [1/3]
int OutputEventBuffer::send_simple_query (int event, unsigned char data, XSocket & sock = main_socket)
 {
     n_event++;
     *this < short(2) < (unsigned char)event < data;
     OUT_EVENTS_LOG1(send_simple_query,event);
     return send(1,sock);
 }
References OUT_EVENTS_LOG1, send(), and send_simple_query().
send_simple_query() [2/3]
int OutputEventBuffer::send_simple_query (int event, unsigned char data1, unsigned char data2, XSocket & sock = main_socket)
 {
     n_event++;
     *this < short(3) < (unsigned char)event < data1 < data2;
     OUT_EVENTS_LOG1(send_simple_query,event);
     return send(1,sock);
 }
References OUT_EVENTS_LOG1, send(), and send_simple_query().
send_simple_query() [3/3]
int OutputEventBuffer::send_simple_query (int event, XSocket & sock = main_socket)
 {
     if(pointer_to_size_of_event > 0)
         ErrH.Abort("There wasn't an end of event");
     n_event++;
     *this < short(1) < (unsigned char)event;
     OUT_EVENTS_LOG1(send_simple_query,event);
     return send(1,sock);
 }
References XErrorHandler::Abort(), ErrH, OUT_EVENTS_LOG1, and send().
Referenced by disconnect_from_server(), is_current_server_configured(), leave_world(), send_server_data(), send_simple_query(), set_time_by_server(), TopList::TopList(), and total_players_data_list_query().
set_player_body()
void OutputEventBuffer::set_player_body (PlayerBody & body)
 {
     n_event++;
     *this < short(1 + sizeof(PlayerBody)) < (unsigned char)SET_PLAYER_DATA;
     write(&body,sizeof(PlayerBody));
     OUT_EVENTS_LOG(SET_PLAYER_DATA);
 }
References OUT_EVENTS_LOG, SET_PLAYER_DATA, and XBuffer::write().
Referenced by send_player_body().
set_position()
void OutputEventBuffer::set_position (int x, int y, int y_half_size_of_screen)
 {
     n_event++;
     *this < short(7) < (unsigned char)SET_POSITION < (unsigned short)x < (unsigned short)y < (unsigned short)y_half_size_of_screen;
     OUT_EVENTS_LOG1(SET_POSITION,y);
     for(int i = pointer_to_the_first_event;i < pointer_to_the_last_event;i += full_event_size(i)){
         if(*((unsigned char*)(address() + i + 2)) == SET_POSITION){
             int event_size = full_event_size(i);
             memmove(address() + i, address() + i + event_size, tell() - (i + event_size));
             offset -= event_size;
             pointer_to_the_last_event -= event_size;
             n_event--;
             OUT_EVENTS_LOG(Pack_SetPosition);
             break;
             }
         }
 }
References XBuffer::address(), XBuffer::offset, OUT_EVENTS_LOG, OUT_EVENTS_LOG1, SET_POSITION, and XBuffer::tell().
set_world()
void OutputEventBuffer::set_world (int world, int y_size_of_world)
 {
     n_event++;
     *this < short(4) < (unsigned char)SET_WORLD < (unsigned char)world < (unsigned short)y_size_of_world;
     OUT_EVENTS_LOG1(SET_WORLD,world);
 }
References OUT_EVENTS_LOG1, and SET_WORLD.
Referenced by set_world().
update_object()
void OutputEventBuffer::update_object (int ID, int x, int y, int flags = 0)
 {
     n_event++;
     pointer_to_size_of_event = tell();
     *this < short(0) < (unsigned char)(UPDATE_OBJECT | flags);
     *this < ID < (unsigned int)GLOBAL_CLOCK() < (unsigned short)x < (unsigned short)y;
     OUT_EVENTS_LOG1(UPDATE_OBJECT,ID);
 }
The documentation for this class was generated from the following files:
server/server.h
src/network.h
server/server.cpp
src/network.cpp