Vangers: XTListAlt< Type > Class Template Reference
XTListAlt< Type > Class Template Reference
#include <xcontainers.h>
Public Member Functions
XTListAlt ()
~XTListAlt ()
int size ()
Type * first ()
Type * last ()
void clear ()
void delete_all ()
void insert (Type *p)
void insert (Type *pointer, Type *p)
void append (Type *p)
void remove (Type *p)
Type * search (int ID)
Detailed Description
template<class Type>
class XTListAlt< Type >
Constructor & Destructor Documentation
XTListAlt()
template<class Type > XTListAlt< Type >::XTListAlt inline
 {
     num_elements = 0; first_element = 0;
 }
~XTListAlt()
template<class Type > XTListAlt< Type >::~XTListAlt inline
 {
     clear();
 }
Member Function Documentation
append()
template<class Type > void XTListAlt< Type >::append (Type * p) inline
 {
     if(p -> list_alt)
         ErrH.Abort("Element is already in list");
     num_elements++;
     if(first_element){
         p -> next_alt = 0;
         p -> prev_alt = first_element -> prev_alt;
         first_element -> prev_alt -> next_alt = p;
         first_element -> prev_alt = p;
         }
     else{
         p -> next_alt = 0;
         p -> prev_alt = first_element = p;
         }
     p -> list_alt = this;
 }
References XErrorHandler::Abort(), and ErrH.
Referenced by World::add_object(), World::attach_player(), and World::process_create_inventory().
clear()
template<class Type > void XTListAlt< Type >::clear (void) inline
 {
     while(first())
         remove(first());
 }
Referenced by World::~World().
delete_all()
template<class Type > void XTListAlt< Type >::delete_all inline
 {
     Type* p;
     while((p = first()) != 0){
         remove(p);
         delete p;
         }
 }
first()
template<class Type > Type * XTListAlt< Type >::first inline
 {
     return first_element;
 }
Referenced by World::detach_player(), Game::get_object_ID_offsets(), World::process_create(), World::process_create_inventory(), World::process_delete(), World::process_set_position(), World::process_update(), World::process_update_inventory(), and World::~World().
insert() [1/2]
template<class Type > void XTListAlt< Type >::insert (Type * p) inline
 {
     if(p -> list_alt)
         ErrH.Abort("Element is already in list");
     num_elements++;
     if(first_element){
         p -> next_alt = first_element;
         p -> prev_alt = first_element -> prev_alt;
         first_element -> prev_alt = p;
         }
     else{
         p -> prev_alt = p;
         p -> next_alt = 0;
         }
     first_element = p;
     p -> list_alt = this;
 }
References XErrorHandler::Abort(), and ErrH.
insert() [2/2]
template<class Type > void XTListAlt< Type >::insert (Type * pointer, Type * p) inline
 {
     if(!first_element || first_element == pointer){
         insert(p);
         return;
         }
     if(!pointer){
         append(p);
         return;
         }
     if(p -> list)
         ErrH.Abort("Element is already in list");
     num_elements++;
     p -> next_alt = pointer;
     p -> prev_alt = pointer -> prev_alt;
     pointer -> prev_alt -> next_alt = p;
     pointer -> prev_alt = p;
     p -> list_alt = this;
 }
References XErrorHandler::Abort(), and ErrH.
last()
template<class Type > Type * XTListAlt< Type >::last inline
 {
     return first_element -> prev_alt;
 }
remove()
template<class Type > void XTListAlt< Type >::remove (Type * p) inline
 {
     if(p -> list_alt != this)
         ErrH.Abort("Removed element isn't in list");
     num_elements--;
     if(p -> next_alt)
         p -> next_alt -> prev_alt = p -> prev_alt;
     else
         first_element -> prev_alt = p -> prev_alt;
     if(p != first_element)
         p -> prev_alt -> next_alt = p -> next_alt;
     else{
         first_element = p -> next_alt;
         if(first_element)
             first_element -> prev_alt = p -> prev_alt;
         }
     p -> next_alt = p -> prev_alt = 0;
     p -> list_alt = 0;
 }
References XErrorHandler::Abort(), and ErrH.
Referenced by World::delete_object(), and World::detach_player().
search()
template<class Type > Type * XTListAlt< Type >::search (int ID) inline
 {
     Type* p = first();
     while(p){
         if(p -> ID == ID)
             return p;
         p = p -> next_alt;
         }
     return 0;
 }
Referenced by World::search_object().
size()
template<class Type > int XTListAlt< Type >::size (void) inline
 {
     return num_elements;
 }
The documentation for this class was generated from the following file:
src/xcontainers.h