Vangers: QuatD Class Reference
QuatD Class Reference
#include <xmath.h>
Public Member Functions
QuatD ()
QuatD (double s, double x, double y, double z)
QuatD (double angle, const Vect3d &axis, int normalizeAxis=1)
QuatD (const Mat3d &R)
xm_inline operator QuatF () const
QuatD & set (double s, double x, double y, double z)
QuatD & set (double angle, const Vect3d &axis, int normalizeAxis=1)
QuatD & set (const Mat3d &R)
xm_inline operator const double * () const
xm_inline operator double * ()
xm_inline const double & operator[] (int i) const
xm_inline double & operator[] (int i)
double s () const
double x () const
double y () const
double z () const
double & s ()
double & x ()
double & y ()
double & z ()
xm_inline Vect3d axis () const
xm_inline double angle () const
xm_inline int operator== (const QuatD &other) const
xm_inline int operator!= (const QuatD &other) const
xm_inline QuatD operator- () const
xm_inline QuatD & negate (const QuatD &q)
xm_inline QuatD & negate ()
xm_inline QuatD & normalize (const QuatD &q)
xm_inline QuatD & normalize ()
xm_inline double norm () const
xm_inline QuatD & invert (const QuatD &q)
xm_inline QuatD & invert ()
xm_inline QuatD & operator+= (const QuatD &q)
xm_inline QuatD & operator-= (const QuatD &q)
xm_inline QuatD operator+ (const QuatD &q) const
xm_inline QuatD operator- (const QuatD &q) const
QuatD & mult (const QuatD &p, const QuatD &q)
QuatD & premult (const QuatD &q)
QuatD & postmult (const QuatD &q)
xm_inline QuatD & operator%= (const QuatD &q)
xm_inline QuatD operator% (const QuatD &q) const
xm_inline double dot (const QuatD &other) const
xm_inline QuatD & operator*= (double s)
xm_inline QuatD & operator/= (double s)
xm_inline QuatD operator* (double s) const
xm_inline QuatD operator/ (double s) const
Vect3d & xform (const Vect3d &u, Vect3d &v) const
Vect3d & xform (Vect3d &v) const
Vect3d & invXform (const Vect3d &v, Vect3d &xv) const
Vect3d & invXform (Vect3d &v) const
xm_inline void slerp (const QuatD &a, const QuatD &b, double t)
Static Public Attributes
static const QuatD ID
Friends
class Mat3d
class Se3d
xm_inline friend QuatD normalize (const QuatD &q)
double dot (const QuatD &u, const QuatD &v)
xm_inline friend QuatD operator* (double s, const QuatD &q)
ostream & operator<< (ostream &os, const QuatD &q)
istream & operator>> (istream &is, QuatD &q)
XStream & operator<= (XStream &s, const QuatD &q)
XStream & operator>= (XStream &s, QuatD &q)
XStream & operator< (XStream &s, const QuatD &q)
XStream & operator> (XStream &s, QuatD &q)
XBuffer & operator<= (XBuffer &b, const QuatD &q)
XBuffer & operator>= (XBuffer &b, QuatD &q)
XBuffer & operator< (XBuffer &b, const QuatD &q)
XBuffer & operator> (XBuffer &b, QuatD &q)
Detailed Description
Constructor & Destructor Documentation
QuatD() [1/4]
QuatD::QuatD () inline
 {}
Referenced by operator*(), operator+(), operator-(), and operator/().
QuatD() [2/4]
QuatD::QuatD (double s, double x, double y, double z) inline
 {set(s, x, y, z);}
References s(), set(), x(), y(), and z().
QuatD() [3/4]
QuatD::QuatD (double angle, const Vect3d & axis, int normalizeAxis = 1) inline
     {set(angle, axis, normalizeAxis);}
References angle(), axis(), and set().
QuatD() [4/4]
QuatD::QuatD (const Mat3d & R) inline
 {set(R);}
References set().
Member Function Documentation
angle()
double QuatD::angle () const
 {
   return 2 * acos(s_);
 }
Referenced by QuatD(), and set().
axis()
Vect3d QuatD::axis () const
 {
   Vect3d v(x_, y_, z_);
   if (v.norm() == 0.0) v = Vect3d::I;  // axis is arbitrary here
   else v.normalize();
   return v;
 }
References Vect3d::I, Vect3d::norm(), and Vect3d::normalize().
Referenced by QuatD(), and set().
dot()
double QuatD::dot (const QuatD & other) const
 {
     return s_*q.s_ + x_*q.x_ + y_*q.y_ + z_*q.z_;
 }
Referenced by slerp().
invert() [1/2]
QuatD & QuatD::invert ()
 {
   s_ = -s_;
   return *this;
 }
invert() [2/2]
QuatD & QuatD::invert (const QuatD & q)
 {
   s_ = -q.s_;
   x_ =  q.x_;
   y_ =  q.y_;
   z_ =  q.z_;
   return *this;
 }
invXform() [1/2]
Vect3d & QuatD::invXform (const Vect3d & v, Vect3d & xv) const
 {
   Vect3d *u, uv, uuv;
   u = (Vect3d *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.0 * -s_);
   uuv.scale(2.0);
   xv.add(v, uv);
   xv.add(uuv);
   return xv;
 }
References Vect3d::add(), Vect3d::cross(), and Vect3d::scale().
Referenced by Se3d::invXformPoint(), and Se3d::invXformVect().
invXform() [2/2]
Vect3d & QuatD::invXform (Vect3d & v) const
 {
   Vect3d *u, uv, uuv;
   u = (Vect3d *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.0 * -s_);
   uuv.scale(2.0);
   v.add(uv);
   v.add(uuv);
   return v;
 }
References Vect3d::add(), Vect3d::cross(), and Vect3d::scale().
mult()
QuatD & QuatD::mult (const QuatD & p, const QuatD & q)
 {
   s_ = p.s_ * q.s_ - (p.x_ * q.x_ + p.y_ * q.y_ + p.z_ * q.z_);
   x_ = p.s_ * q.x_ +  q.s_ * p.x_ + p.y_ * q.z_ - p.z_ * q.y_;
   y_ = p.s_ * q.y_ +  q.s_ * p.y_ + p.z_ * q.x_ - p.x_ * q.z_;
   z_ = p.s_ * q.z_ +  q.s_ * p.z_ + p.x_ * q.y_ - p.y_ * q.x_;
   return *this;
 }
Referenced by Se3d::mult(), and operator%().
negate() [1/2]
xm_inline QuatD& QuatD::negate () inline
 { s_ = -s_; x_ = -x_; y_ = -y_; z_ = -z_; return *this; }
Referenced by slerp().
negate() [2/2]
xm_inline QuatD& QuatD::negate (const QuatD & q) inline
 { s_ = -q.s_; x_ = -q.x_; y_ = -q.y_; z_ = -q.z_; return *this; }
norm()
xm_inline double QuatD::norm () const inline
 { return sqrt(x_*x_ + y_*y_ + z_*z_ + s_*s_); }
normalize() [1/2]
QuatD & QuatD::normalize ()
 {
   double scale;
   scale = 1.0 / sqrt(s_*s_ + x_*x_ + y_*y_ + z_*z_);
   s_ *= scale;
   x_ *= scale;
   y_ *= scale;
   z_ *= scale;
   return *this;
 }
normalize() [2/2]
QuatD & QuatD::normalize (const QuatD & q)
 {
   double scale;
   scale = 1.0 / sqrt(q.s_*q.s_ + q.x_*q.x_ + q.y_*q.y_ + q.z_*q.z_);
   s_ = scale * q.s_;
   x_ = scale * q.x_;
   y_ = scale * q.y_;
   z_ = scale * q.z_;
   return *this;
 }
operator const double *()
xm_inline QuatD::operator const double * () const inline
 { return &s_; }
operator double *()
xm_inline QuatD::operator double * () inline
 { return &s_; }
operator QuatF()
QuatD::operator QuatF () const
 {
     return QuatF((float)s_,(float)x_,(float)y_,(float)z_);
 }
operator!=()
int QuatD::operator!= (const QuatD & other) const
 {
   return fabs(s_ - other.s_) > DBL_COMPARE_TOLERANCE ||
         fabs(x_ - other.x_) > DBL_COMPARE_TOLERANCE ||
         fabs(y_ - other.y_) > DBL_COMPARE_TOLERANCE ||
         fabs(z_ - other.z_) > DBL_COMPARE_TOLERANCE;
 }
References DBL_COMPARE_TOLERANCE.
operator%()
xm_inline QuatD QuatD::operator% (const QuatD & q) const inline
 { QuatD u; return u.mult(*this, q); }
References mult().
operator%=()
xm_inline QuatD& QuatD::operator%= (const QuatD & q) inline
 { return postmult(q); }
References postmult().
operator*()
QuatD QuatD::operator* (double s) const
 {
     return QuatD(s_*w,x_*w,y_*w,z_*w);
 }
References QuatD().
operator*=()
QuatD & QuatD::operator*= (double s)
 {
     s_ *= w;
     x_ *= w;
     y_ *= w;
     z_ *= w;
     return *this;
 }
operator+()
QuatD QuatD::operator+ (const QuatD & q) const
 {
     return QuatD(s_ + q.s_,x_ + q.x_,y_ + q.y_,z_ + q.z_);
 }
References QuatD().
operator+=()
QuatD & QuatD::operator+= (const QuatD & q)
 {
     s_ += q.s_;
     x_ += q.x_;
     y_ += q.y_;
     z_ += q.z_;
     return *this;
 }
operator-() [1/2]
xm_inline QuatD QuatD::operator- () const inline
 { return QuatD(-s_, -x_, -y_, -z_); }
References QuatD().
operator-() [2/2]
QuatD QuatD::operator- (const QuatD & q) const
 {
     return QuatD(s_ - q.s_,x_ - q.x_,y_ - q.y_,z_ - q.z_);
 }
References QuatD().
operator-=()
QuatD & QuatD::operator-= (const QuatD & q)
 {
     s_ -= q.s_;
     x_ -= q.x_;
     y_ -= q.y_;
     z_ -= q.z_;
     return *this;
 }
operator/()
QuatD QuatD::operator/ (double s) const
 {
     w = 1/w;
     return QuatD(s_*w,x_*w,y_*w,z_*w);
 }
References QuatD().
operator/=()
QuatD & QuatD::operator/= (double s)
 {
     w = 1/w;
     s_ *= w;
     x_ *= w;
     y_ *= w;
     z_ *= w;
     return *this;
 }
operator==()
int QuatD::operator== (const QuatD & other) const
 {
   return fabs(s_ - other.s_) < DBL_COMPARE_TOLERANCE &&
         fabs(x_ - other.x_) < DBL_COMPARE_TOLERANCE &&
         fabs(y_ - other.y_) < DBL_COMPARE_TOLERANCE &&
         fabs(z_ - other.z_) < DBL_COMPARE_TOLERANCE;
 }
References DBL_COMPARE_TOLERANCE.
operator[]() [1/2]
xm_inline double& QuatD::operator[] (int i) inline
 {return *(&s_ + i);}
operator[]() [2/2]
xm_inline const double& QuatD::operator[] (int i) const inline
 {return *(&s_ + i);}
postmult()
QuatD & QuatD::postmult (const QuatD & q)
 {
   double ox, oy, oz;
   ox = x_; oy = y_; oz = z_;
   x_ = s_ * q.x_ +  ox * q.s_ + oy * q.z_ - oz * q.y_;
   y_ = s_ * q.y_ +  oy * q.s_ + oz * q.x_ - ox * q.z_;
   z_ = s_ * q.z_ +  oz * q.s_ + ox * q.y_ - oy * q.x_;
   s_ = s_ * q.s_ - (ox * q.x_ + oy * q.y_ + oz * q.z_);
   return *this;
 }
Referenced by operator%=(), and Se3d::postmult().
premult()
QuatD & QuatD::premult (const QuatD & q)
 {
   double ox, oy, oz;
   ox = x_; oy = y_; oz = z_;
   x_ = q.s_ * ox +  s_ * q.x_ + q.y_ * oz - q.z_ * oy;
   y_ = q.s_ * oy +  s_ * q.y_ + q.z_ * ox - q.x_ * oz;
   z_ = q.s_ * oz +  s_ * q.z_ + q.x_ * oy - q.y_ * ox;
   s_ = q.s_ * s_ - (q.x_ * ox + q.y_ * oy + q.z_ * oz);
   return *this;
 }
Referenced by Se3d::premult().
s() [1/2]
double& QuatD::s () inline
 {return s_;}
s() [2/2]
double QuatD::s () const inline
 {return s_;}
Referenced by QuatD(), and set().
set() [1/3]
QuatD & QuatD::set (const Mat3d & R)
 {
   double qs2, qx2, qy2, qz2;  // squared magniudes of quaternion components
   double tmp;
   int i;
   // first compute squared magnitudes of quaternion components - at least one
   // will be greater than 0 since quaternion is unit magnitude
   qs2 = 0.25 * (R.xx + R.yy + R.zz + 1);
   qx2 = qs2 - 0.5 * (R.yy + R.zz);
   qy2 = qs2 - 0.5 * (R.zz + R.xx);
   qz2 = qs2 - 0.5 * (R.xx + R.yy);
   // find maximum magnitude component
   i = (qs2 > qx2 ) ?
     ((qs2 > qy2) ? ((qs2 > qz2) ? 0 : 3) : ((qy2 > qz2) ? 2 : 3)) :
     ((qx2 > qy2) ? ((qx2 > qz2) ? 1 : 3) : ((qy2 > qz2) ? 2 : 3));
   // compute signed quaternion components using numerically stable method
   switch(i) {
   case 0:
     s_ = sqrt(qs2);
     tmp = 0.25 / s_;
     x_ = (R.zy - R.yz) * tmp;
     y_ = (R.xz - R.zx) * tmp;
     z_ = (R.yx - R.xy) * tmp;
     break;
   case 1:
     x_ = sqrt(qx2);
     tmp = 0.25 / x_;
     s_ = (R.zy - R.yz) * tmp;
     y_ = (R.xy + R.yx) * tmp;
     z_ = (R.xz + R.zx) * tmp;
     break;
   case 2:
     y_ = sqrt(qy2);
     tmp = 0.25 / y_;
     s_ = (R.xz - R.zx) * tmp;
     z_ = (R.yz + R.zy) * tmp;
     x_ = (R.yx + R.xy) * tmp;
     break;
   case 3:
     z_ = sqrt(qz2);
     tmp = 0.25 / z_;
     s_ = (R.yx - R.xy) * tmp;
     x_ = (R.zx + R.xz) * tmp;
     y_ = (R.zy + R.yz) * tmp;
     break;
   }
   // for consistency, force positive scalar component [ (s; v) = (-s; -v) ]
   if (s_ < 0) {
     s_ = -s_;
     x_ = -x_;
     y_ = -y_;
     z_ = -z_;
   }
   // normalize, just to be safe
   tmp = 1.0 / sqrt(s_*s_ + x_*x_ + y_*y_ + z_*z_);
   s_ *= tmp;
   x_ *= tmp;
   y_ *= tmp;
   z_ *= tmp;
   return *this;
 }
set() [2/3]
QuatD & QuatD::set (double angle, const Vect3d & axis, int normalizeAxis = 1)
 {
     double theta = 0.5 * angle;
     double sine = sin(theta);
     s_ = cos(theta);
     if(normalizeAxis){
         double n2;
         if((n2 = axis.norm2()) < DBL_EPS){
             *this = QuatD::ID;
             return *this;
             }
         sine /= sqrt(n2);
         }
     x_ = axis.x * sine;
     y_ = axis.y * sine;
     z_ = axis.z * sine;
     return *this;
 }
References angle(), axis(), DBL_EPS, ID, Vect3d::norm2(), Vect3d::x, Vect3d::y, and Vect3d::z.
set() [3/3]
QuatD& QuatD::set (double s, double x, double y, double z) inline
 { s_=s; x_=x; y_=y; z_=z; return *this; }
References s(), x(), y(), and z().
Referenced by QuatD(), Se3d::set(), and Mat3d::set().
slerp()
xm_inline void QuatD::slerp (const QuatD & a, const QuatD & b, double t)
 {
     // Slerp(q1,q2,t) = (sin((1-t)*A)/sin(A))*q1+(sin(t*A)/sin(A))*q2
         double scale0, scale1;
         // calc cosine
         double cosom = a.dot(b);
         // adjust signs (if necessary)
         if(cosom < 0.0){
         cosom = -cosom;
         negate(b);
         }
     else
         *this = b;
         // calculate coefficients
        if ((1.0 - cosom) > 1e-5f ) {
                 // standard case (slerp)
                 double omega = acos(cosom);
                 double sinom = sin(omega);
                 scale0 = sin((1.0 - t) * omega) / sinom;
                 scale1 = sin(t * omega) / sinom;
         }
         else {  // "from" and "to" quaternions are very close, so we can do a linear interpolation
                 scale0 = 1.0 - t;
                 scale1 = t;
         }
         // calculate final values
     *this *= scale1;
     *this += a*scale0;
 }
References dot(), and negate().
x() [1/2]
double& QuatD::x () inline
 {return x_;}
x() [2/2]
double QuatD::x () const inline
 {return x_;}
Referenced by QuatD(), and set().
xform() [1/2]
Vect3d & QuatD::xform (const Vect3d & u, Vect3d & v) const
 {
   Vect3d *u, uv, uuv;
   u = (Vect3d *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.0 * s_);
   uuv.scale(2.0);
   xv.add(v, uv);
   xv.add(uuv);
   return xv;
 }
References Vect3d::add(), Vect3d::cross(), and Vect3d::scale().
Referenced by Se3d::invert(), Se3d::mult(), Se3d::postmult(), Se3d::premult(), Se3d::xformPoint(), and Se3d::xformVect().
xform() [2/2]
Vect3d & QuatD::xform (Vect3d & v) const
 {
   Vect3d *u, uv, uuv;
   u = (Vect3d *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.0 * s_);
   uuv.scale(2.0);
   v.add(uv);
   v.add(uuv);
   return v;
 }
References Vect3d::add(), Vect3d::cross(), and Vect3d::scale().
y() [1/2]
double& QuatD::y () inline
 {return y_;}
y() [2/2]
double QuatD::y () const inline
 {return y_;}
Referenced by QuatD(), and set().
z() [1/2]
double& QuatD::z () inline
 {return z_;}
z() [2/2]
double QuatD::z () const inline
 {return z_;}
Referenced by QuatD(), and set().
Friends And Related Function Documentation
dot
double dot (const QuatD & u, const QuatD & v) friend
 { return u.dot(v); }
Mat3d
friend class Mat3d friend
normalize
xm_inline friend QuatD normalize (const QuatD & q) friend
 {
   double scale;
   scale = 1.0 / sqrt(q.s_*q.s_ + q.x_*q.x_ + q.y_*q.y_ + q.z_*q.z_);
   return QuatD(scale * q.s_, scale * q.x_, scale * q.y_, scale * q.z_);
 }
operator*
xm_inline friend QuatD operator* (double s, const QuatD & q) friend
 {
     return QuatD(q.s_*w,q.x_*w,q.y_*w,q.z_*w);
 }
operator< [1/2]
XBuffer& operator< (XBuffer & b, const QuatD & q) friend
 {
     b < q.s_ < q.x_ < q.y_ < q.z_;
     return b;
 }
operator< [2/2]
XStream& operator< (XStream & s, const QuatD & q) friend
 {
     s.write(&q,sizeof(QuatD));
     return s;
 }
operator<<
ostream& operator<< (ostream & os, const QuatD & q) friend
 {
   os << q.s_ << " \t" << q.x_ << " \t" << q.y_ << " \t" << q.z_;
   return os;
 }
operator<= [1/2]
XBuffer& operator<= (XBuffer & b, const QuatD & q) friend
 {
     b <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return b;
 }
operator<= [2/2]
XStream& operator<= (XStream & s, const QuatD & q) friend
 {
     s <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return s;
 }
operator> [1/2]
XBuffer& operator> (XBuffer & b, QuatD & q) friend
 {
     b > q.s_ > q.x_ > q.y_ > q.z_;
     return b;
 }
operator> [2/2]
XStream& operator> (XStream & s, QuatD & q) friend
 {
     s.read(&q,sizeof(QuatD));
     return s;
 }
operator>= [1/2]
XBuffer& operator>= (XBuffer & b, QuatD & q) friend
 {
     b >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return b;
 }
operator>= [2/2]
XStream& operator>= (XStream & s, QuatD & q) friend
 {
     s >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return s;
 }
operator>>
istream& operator>> (istream & is, QuatD & q) friend
 {
   is >> q.s_ >> q.x_ >> q.y_ >> q.z_;
   return is;
 }
Se3d
friend class Se3d friend
Member Data Documentation
ID
const QuatD QuatD::ID static
Referenced by set(), and QuatF::set().
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp