Vangers: RandomGenerator Class Reference
RandomGenerator Class Reference
#include <xmath.h>
Public Member Functions
RandomGenerator (int val=1)
void set (int val)
int get () const
int operator() ()
xm_inline int operator() (int m)
xm_inline float frnd (float x=1.f)
xm_inline float fabsRnd (float x=1.f)
xm_inline float frand ()
Detailed Description
Constructor & Destructor Documentation
RandomGenerator()
RandomGenerator::RandomGenerator (int val = 1) inline
 { set(val); }
References set().
Member Function Documentation
fabsRnd()
xm_inline float RandomGenerator::fabsRnd (float x = 1.f) inline
 { return (float)((*this)())*x/(float)max_value; }
Referenced by fabsRnd().
frand()
xm_inline float RandomGenerator::frand () inline
 { return (*this)()/(float)max_value; }
frnd()
xm_inline float RandomGenerator::frnd (float x = 1.f) inline
 { return (float)((*this)()*2 - max_value)*x/(float)max_value; }
Referenced by frnd().
get()
int RandomGenerator::get () const inline
 { return value; }
operator()() [1/2]
int RandomGenerator::operator() ()
 { return ((value = value*214013L + 2531011L) >> 16) & 0x7fff; }
operator()() [2/2]
xm_inline int RandomGenerator::operator() (int m) inline
 { return m ? (*this)() % m : 0; } // May by used in random_shuffle
set()
void RandomGenerator::set (int val) inline
 { value = val; }
Referenced by RandomGenerator().
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp