Vangers: MatXf Class Reference
MatXf Class Reference
#include <xmath.h>
Public Types
typedef float float16[16]
Public Member Functions
xm_inline MatXf ()
xm_inline MatXf (const Mat3f &R_, const Vect3f &d_)
xm_inline MatXf (const Se3f &T)
xm_inline MatXf (const float16 &T)
xm_inline operator MatXd () const
xm_inline MatXf & set (const Mat3f &R_, const Vect3f &d_)
xm_inline MatXf & set (const Se3f &T)
xm_inline const Mat3f & rot () const
xm_inline const Vect3f & trans () const
xm_inline Mat3f & rot ()
xm_inline Vect3f & trans ()
MatXf & mult (const MatXf &M, const MatXf &N)
MatXf & premult (const MatXf &M)
MatXf & postmult (const MatXf &M)
xm_inline MatXf & operator*= (const MatXf &M)
xm_inline MatXf operator* (const MatXf &N) const
MatXf & invert (const MatXf &M)
MatXf & invert ()
MatXf & Invert (const MatXf &M)
MatXf & Invert ()
xm_inline Vect3d & xformVect (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & xformVect (Vect3d &v) const
xm_inline Vect3d & xformPoint (const Vect3d &p, Vect3d &xp) const
xm_inline Vect3d & xformPoint (Vect3d &p) const
xm_inline Vect3d & invXformVect (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & invXformVect (Vect3d &v) const
xm_inline Vect3d & invXformPoint (const Vect3d &p, Vect3d &xp) const
xm_inline Vect3d & invXformPoint (Vect3d &p) const
xm_inline Vect3f & xformVect (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & xformVect (Vect3f &v) const
xm_inline Vect3f & xformPoint (const Vect3f &p, Vect3f &xp) const
xm_inline Vect3f & xformPoint (Vect3f &p) const
xm_inline Vect3f & invXformVect (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & invXformVect (Vect3f &v) const
xm_inline Vect3f & invXformPoint (const Vect3f &p, Vect3f &xp) const
xm_inline Vect3f & invXformPoint (Vect3f &p) const
Static Public Attributes
static const MatXf ID
Friends
ostream & operator<< (ostream &os, const MatXf &M)
istream & operator>> (istream &is, MatXf &M)
Detailed Description
Member Typedef Documentation
float16
typedef float MatXf::float16[16]
Constructor & Destructor Documentation
MatXf() [1/4]
xm_inline MatXf::MatXf () inline
 {}
MatXf() [2/4]
xm_inline MatXf::MatXf (const Mat3f & R_, const Vect3f & d_) inline
 {set(R_, d_);}
References set().
MatXf() [3/4]
xm_inline MatXf::MatXf (const Se3f & T) inline
 {set(T);}
References set().
MatXf() [4/4]
MatXf::MatXf (const float16 & T)
 {
     R[0][0] = T[0]; R[1][0] = T[1]; R[2][0] = T[2];
     R[0][1] = T[4]; R[1][1] = T[5]; R[2][1] = T[6];
     R[0][2] = T[8]; R[1][2] = T[9]; R[2][2] = T[10];
     d[0] = T[12]; d[1] = T[13]; d[2] = T[14];
 }
Member Function Documentation
invert() [1/2]
MatXf & MatXf::invert ()
 {
   float tmp, odx, ody;
   // invert the rotation part by transposing it
   tmp  = R.xy;
   R.xy = R.yx;
   R.yx = tmp;
   tmp  = R.yz;
   R.yz = R.zy;
   R.zy = tmp;
   tmp  = R.zx;
   R.zx = R.xz;
   R.xz = tmp;
   // new displacement vector given by:  d' = -(R^T) * d
   odx = d.x; ody = d.y;
   d.x = - (R.xx * odx + R.xy * ody + R.xz * d.z);
   d.y = - (R.yx * odx + R.yy * ody + R.yz * d.z);
   d.z = - (R.zx * odx + R.zy * ody + R.zz * d.z);
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Invert() [1/2]
MatXf & MatXf::Invert ()
 {
     // invert the rotation part
     R.invert();
     // new displacement vector given by:    d' = -(R^-1) * d
     R.xform(d);
     d.negate();
     return *this;
 }
References Mat3f::invert(), Vect3f::negate(), and Mat3f::xform().
invert() [2/2]
MatXf & MatXf::invert (const MatXf & M)
 {
   // invert the rotation part by transposing it
   R.xx = M.R.xx;
   R.xy = M.R.yx;
   R.xz = M.R.zx;
   R.yx = M.R.xy;
   R.yy = M.R.yy;
   R.yz = M.R.zy;
   R.zx = M.R.xz;
   R.zy = M.R.yz;
   R.zz = M.R.zz;
   // new displacement vector given by:  d' = -(R^-1) * d
   d.x = - (R.xx * M.d.x + R.xy * M.d.y + R.xz * M.d.z);
   d.y = - (R.yx * M.d.x + R.yy * M.d.y + R.yz * M.d.z);
   d.z = - (R.zx * M.d.x + R.zy * M.d.y + R.zz * M.d.z);
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Invert() [2/2]
MatXf & MatXf::Invert (const MatXf & M)
 {
     // invert the rotation part
     R.invert(M.R);
     // new displacement vector given by:    d' = -(R^-1) * d
     R.xform(M.d, d);
     d.negate();
     return *this;
 }
References Mat3f::invert(), Vect3f::negate(), and Mat3f::xform().
invXformPoint() [1/4]
Vect3d & MatXf::invXformPoint (const Vect3d & p, Vect3d & xp) const
 {
   xp.sub(p, d);
   R.invXform(xp);
   return xp;
 }
References Mat3f::invXform(), and Vect3d::sub().
invXformPoint() [2/4]
Vect3f & MatXf::invXformPoint (const Vect3f & p, Vect3f & xp) const
 {
   xp.sub(p, d);
   R.invXform(xp);
   return xp;
 }
References Mat3f::invXform(), and Vect3f::sub().
invXformPoint() [3/4]
Vect3d & MatXf::invXformPoint (Vect3d & p) const
 {
   p.sub(d);
   R.invXform(p);
   return p;
 }
References Mat3f::invXform(), and Vect3d::sub().
invXformPoint() [4/4]
Vect3f & MatXf::invXformPoint (Vect3f & p) const
 {
   p.sub(d);
   R.invXform(p);
   return p;
 }
References Mat3f::invXform(), and Vect3f::sub().
invXformVect() [1/4]
Vect3d & MatXf::invXformVect (const Vect3d & v, Vect3d & xv) const
 {
   return R.invXform(v, xv);
 }
References Mat3f::invXform().
invXformVect() [2/4]
Vect3f & MatXf::invXformVect (const Vect3f & v, Vect3f & xv) const
 {
   return R.invXform(v, xv);
 }
References Mat3f::invXform().
invXformVect() [3/4]
Vect3d & MatXf::invXformVect (Vect3d & v) const
 {
   return R.invXform(v);
 }
References Mat3f::invXform().
invXformVect() [4/4]
Vect3f & MatXf::invXformVect (Vect3f & v) const
 {
   return R.invXform(v);
 }
References Mat3f::invXform().
mult()
MatXf & MatXf::mult (const MatXf & M, const MatXf & N)
 {
   // multiply rotation matrices
   R.xx = M.R.xx * N.R.xx + M.R.xy * N.R.yx + M.R.xz * N.R.zx;
   R.xy = M.R.xx * N.R.xy + M.R.xy * N.R.yy + M.R.xz * N.R.zy;
   R.xz = M.R.xx * N.R.xz + M.R.xy * N.R.yz + M.R.xz * N.R.zz;
   R.yx = M.R.yx * N.R.xx + M.R.yy * N.R.yx + M.R.yz * N.R.zx;
   R.yy = M.R.yx * N.R.xy + M.R.yy * N.R.yy + M.R.yz * N.R.zy;
   R.yz = M.R.yx * N.R.xz + M.R.yy * N.R.yz + M.R.yz * N.R.zz;
   R.zx = M.R.zx * N.R.xx + M.R.zy * N.R.yx + M.R.zz * N.R.zx;
   R.zy = M.R.zx * N.R.xy + M.R.zy * N.R.yy + M.R.zz * N.R.zy;
   R.zz = M.R.zx * N.R.xz + M.R.zy * N.R.yz + M.R.zz * N.R.zz;
   // d = M.R * N.d + M.d
   d.x = M.R.xx * N.d.x + M.R.xy * N.d.y + M.R.xz * N.d.z + M.d.x;
   d.y = M.R.yx * N.d.x + M.R.yy * N.d.y + M.R.yz * N.d.z + M.d.y;
   d.z = M.R.zx * N.d.x + M.R.zy * N.d.y + M.R.zz * N.d.z + M.d.z;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Referenced by operator*().
operator MatXd()
MatXf::operator MatXd () const
 {
     return MatXd(R, d);
 }
operator*()
xm_inline MatXf MatXf::operator* (const MatXf & N) const inline
 { MatXf M; return M.mult(*this, N); }
References mult().
operator*=()
xm_inline MatXf& MatXf::operator*= (const MatXf & M) inline
 { return postmult(M); }
References postmult().
postmult()
MatXf & MatXf::postmult (const MatXf & M)
 {
   float oxy, oyz, ozx, oyx, ozy, oxz;
   Vect3d v;
   // d = R * M.d + d
   d.x += R.xx * M.d.x + R.xy * M.d.y + R.xz * M.d.z;
   d.y += R.yx * M.d.x + R.yy * M.d.y + R.yz * M.d.z;
   d.z += R.zx * M.d.x + R.zy * M.d.y + R.zz * M.d.z;
   // multiply rotation matrices
   oxy = R.xy; oyx = R.yx; oyz = R.yz; ozy = R.zy; ozx = R.zx; oxz = R.xz;
   R.xy = R.xx * M.R.xy + oxy  * M.R.yy + oxz  * M.R.zy;
   R.xz = R.xx * M.R.xz + oxy  * M.R.yz + oxz  * M.R.zz;
   R.yx = oyx  * M.R.xx + R.yy * M.R.yx + oyz  * M.R.zx;
   R.yz = oyx  * M.R.xz + R.yy * M.R.yz + oyz  * M.R.zz;
   R.zx = ozx  * M.R.xx + ozy  * M.R.yx + R.zz * M.R.zx;
   R.zy = ozx  * M.R.xy + ozy  * M.R.yy + R.zz * M.R.zy;
   R.xx = R.xx * M.R.xx + oxy  * M.R.yx + oxz  * M.R.zx;
   R.yy = oyx  * M.R.xy + R.yy * M.R.yy + oyz  * M.R.zy;
   R.zz = ozx  * M.R.xz + ozy  * M.R.yz + R.zz * M.R.zz;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Referenced by operator*=().
premult()
MatXf & MatXf::premult (const MatXf & M)
 {
   float oxy, oyz, ozx, oyx, ozy, oxz, odx, ody;
   // multiply rotation matrices
   oxy = R.xy; oyx = R.yx; oyz = R.yz; ozy = R.zy; ozx = R.zx; oxz = R.xz;
   R.xy = M.R.xx * oxy  + M.R.xy * R.yy + M.R.xz * ozy;
   R.xz = M.R.xx * oxz  + M.R.xy * oyz  + M.R.xz * R.zz;
   R.yx = M.R.yx * R.xx + M.R.yy * oyx  + M.R.yz * ozx;
   R.yz = M.R.yx * oxz  + M.R.yy * oyz  + M.R.yz * R.zz;
   R.zx = M.R.zx * R.xx + M.R.zy * oyx  + M.R.zz * ozx;
   R.zy = M.R.zx * oxy  + M.R.zy * R.yy + M.R.zz * ozy;
   R.xx = M.R.xx * R.xx + M.R.xy * oyx  + M.R.xz * ozx;
   R.yy = M.R.yx * oxy  + M.R.yy * R.yy + M.R.yz * ozy;
   R.zz = M.R.zx * oxz  + M.R.zy * oyz  + M.R.zz * R.zz;
   // d = M.R * d + M.d
   odx = d.x; ody = d.y;
   d.x = M.R.xx * odx + M.R.xy * ody + M.R.xz * d.z + M.d.x;
   d.y = M.R.yx * odx + M.R.yy * ody + M.R.yz * d.z + M.d.y;
   d.z = M.R.zx * odx + M.R.zy * ody + M.R.zz * d.z + M.d.z;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
rot() [1/2]
xm_inline Mat3f& MatXf::rot () inline
 {return R;}
rot() [2/2]
xm_inline const Mat3f& MatXf::rot () const inline
 {return R;}
Referenced by Se3f::set(), and Mat4f::set().
set() [1/2]
xm_inline MatXf& MatXf::set (const Mat3f & R_, const Vect3f & d_) inline
 {R = R_; d = d_; return *this; }
Referenced by MatXf(), and operator>>().
set() [2/2]
MatXf & MatXf::set (const Se3f & T)
 {
   R.set(T.rot());
   d = T.trans();
   return *this;
 }
References Se3f::rot(), Mat3f::set(), and Se3f::trans().
trans() [1/2]
xm_inline Vect3f& MatXf::trans () inline
 {return d;}
trans() [2/2]
xm_inline const Vect3f& MatXf::trans () const inline
 {return d;}
Referenced by Se3f::set(), and Mat4f::set().
xformPoint() [1/4]
Vect3d & MatXf::xformPoint (const Vect3d & p, Vect3d & xp) const
 {
   R.xform(p, xp);
   xp.add(d);
   return xp;
 }
References Vect3d::add(), and Mat3f::xform().
xformPoint() [2/4]
Vect3f & MatXf::xformPoint (const Vect3f & p, Vect3f & xp) const
 {
   R.xform(p, xp);
   xp.add(d);
   return xp;
 }
References Vect3f::add(), and Mat3f::xform().
xformPoint() [3/4]
Vect3d & MatXf::xformPoint (Vect3d & p) const
 {
   R.xform(p);
   p.add(d);
   return p;
 }
References Vect3d::add(), and Mat3f::xform().
xformPoint() [4/4]
Vect3f & MatXf::xformPoint (Vect3f & p) const
 {
   R.xform(p);
   p.add(d);
   return p;
 }
References Vect3f::add(), and Mat3f::xform().
xformVect() [1/4]
Vect3d & MatXf::xformVect (const Vect3d & v, Vect3d & xv) const
 {
   return R.xform(v, xv);
 }
References Mat3f::xform().
xformVect() [2/4]
Vect3f & MatXf::xformVect (const Vect3f & v, Vect3f & xv) const
 {
   return R.xform(v, xv);
 }
References Mat3f::xform().
xformVect() [3/4]
Vect3d & MatXf::xformVect (Vect3d & v) const
 {
   return R.xform(v);
 }
References Mat3f::xform().
xformVect() [4/4]
Vect3f & MatXf::xformVect (Vect3f & v) const
 {
   return R.xform(v);
 }
References Mat3f::xform().
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & os, const MatXf & M) friend
 {
   return os << m.R << m.d;
 }
operator>>
istream& operator>> (istream & is, MatXf & M) friend
 {
   Se3d T;
   is >> T;
   m.set(T);
   return is;
 }
Member Data Documentation
ID
const MatXf MatXf::ID static
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp