Vangers: QuatF Class Reference
QuatF Class Reference
#include <xmath.h>
Public Member Functions
xm_inline QuatF ()
xm_inline QuatF (float s, float x, float y, float z)
xm_inline QuatF (float angle, const Vect3f &axis, int normalizeAxis=1)
xm_inline QuatF (const Mat3f &R)
xm_inline operator QuatD () const
xm_inline QuatF & set (float s, float x, float y, float z)
QuatF & set (float angle, const Vect3f &axis, int normalizeAxis=1)
QuatF & set (const Mat3f &R)
xm_inline operator const float * () const
xm_inline operator float * ()
xm_inline const float & operator[] (int i) const
xm_inline float & operator[] (int i)
float s () const
float x () const
float y () const
float z () const
float & s ()
float & x ()
float & y ()
float & z ()
xm_inline Vect3f axis () const
xm_inline float angle () const
xm_inline int operator== (const QuatF &other) const
xm_inline int operator!= (const QuatF &other) const
xm_inline QuatF operator- () const
xm_inline QuatF & negate (const QuatF &q)
xm_inline QuatF & negate ()
xm_inline QuatF & normalize (const QuatF &q)
xm_inline QuatF & normalize ()
xm_inline float norm () const
xm_inline QuatF & invert (const QuatF &q)
xm_inline QuatF & invert ()
xm_inline QuatF & operator+= (const QuatF &q)
xm_inline QuatF & operator-= (const QuatF &q)
xm_inline QuatF operator+ (const QuatF &q) const
xm_inline QuatF operator- (const QuatF &q) const
QuatF & mult (const QuatF &p, const QuatF &q)
QuatF & premult (const QuatF &q)
QuatF & postmult (const QuatF &q)
xm_inline QuatF & operator%= (const QuatF &q)
xm_inline QuatF operator% (const QuatF &q) const
xm_inline float dot (const QuatF &other) const
xm_inline QuatF & operator*= (float s)
xm_inline QuatF & operator/= (float s)
xm_inline QuatF operator* (float s) const
xm_inline QuatF operator/ (float s) const
Vect3f & xform (const Vect3f &u, Vect3f &v) const
Vect3f & xform (Vect3f &v) const
Vect3f & invXform (const Vect3f &v, Vect3f &xv) const
Vect3f & invXform (Vect3f &v) const
xm_inline void slerp (const QuatF &a, const QuatF &b, float t)
Static Public Attributes
static const QuatF ID
Friends
class Mat3f
class Se3f
xm_inline friend QuatF normalize (const QuatF &q)
xm_inline friend float dot (const QuatF &u, const QuatF &v)
xm_inline friend QuatF operator* (float s, const QuatF &q)
ostream & operator<< (ostream &os, const QuatF &q)
istream & operator>> (istream &is, QuatF &q)
XStream & operator<= (XStream &s, const QuatF &q)
XStream & operator>= (XStream &s, QuatF &q)
XStream & operator< (XStream &s, const QuatF &q)
XStream & operator> (XStream &s, QuatF &q)
XBuffer & operator<= (XBuffer &b, const QuatF &q)
XBuffer & operator>= (XBuffer &b, QuatF &q)
XBuffer & operator< (XBuffer &b, const QuatF &q)
XBuffer & operator> (XBuffer &b, QuatF &q)
Detailed Description
Constructor & Destructor Documentation
QuatF() [1/4]
xm_inline QuatF::QuatF () inline
 {}
Referenced by operator*(), operator+(), operator-(), and operator/().
QuatF() [2/4]
xm_inline QuatF::QuatF (float s, float x, float y, float z) inline
 {set(s, x, y, z);}
References s(), set(), x(), y(), and z().
QuatF() [3/4]
xm_inline QuatF::QuatF (float angle, const Vect3f & axis, int normalizeAxis = 1) inline
 {set(angle, axis, normalizeAxis);}
References angle(), axis(), and set().
QuatF() [4/4]
xm_inline QuatF::QuatF (const Mat3f & R) inline
 {set(R);}
References set().
Member Function Documentation
angle()
float QuatF::angle () const
 {
   return 2 * acosf(s_);
 }
Referenced by Mat3f::Mat3f(), QuatF(), and set().
axis()
Vect3f QuatF::axis () const
 {
   Vect3f v(x_, y_, z_);
   if (v.norm() == 0.0) v = Vect3f::I;  // axis is arbitrary here
   else v.normalize();
   return v;
 }
References Vect3f::I, Vect3f::norm(), and Vect3f::normalize().
Referenced by Mat3f::col(), Mat3f::Mat3f(), QuatF(), set(), and Mat3f::setCol().
dot()
float QuatF::dot (const QuatF & other) const
 {
     return s_*q.s_ + x_*q.x_ + y_*q.y_ + z_*q.z_;
 }
Referenced by slerp().
invert() [1/2]
QuatF & QuatF::invert ()
 {
   s_ = -s_;
   return *this;
 }
invert() [2/2]
QuatF & QuatF::invert (const QuatF & q)
 {
   s_ = -q.s_;
   x_ =  q.x_;
   y_ =  q.y_;
   z_ =  q.z_;
   return *this;
 }
invXform() [1/2]
Vect3f & QuatF::invXform (const Vect3f & v, Vect3f & xv) const
 {
   Vect3f *u, uv, uuv;
   u = (Vect3f *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.f * -s_);
   uuv.scale(2.f);
   xv.add(v, uv);
   xv.add(uuv);
   return xv;
 }
References Vect3f::add(), Vect3f::cross(), and Vect3f::scale().
Referenced by Se3f::invXformPoint(), and Se3f::invXformVect().
invXform() [2/2]
Vect3f & QuatF::invXform (Vect3f & v) const
 {
   Vect3f *u, uv, uuv;
   u = (Vect3f *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.f * -s_);
   uuv.scale(2.f);
   v.add(uv);
   v.add(uuv);
   return v;
 }
References Vect3f::add(), Vect3f::cross(), and Vect3f::scale().
mult()
QuatF & QuatF::mult (const QuatF & p, const QuatF & q)
 {
   s_ = p.s_ * q.s_ - (p.x_ * q.x_ + p.y_ * q.y_ + p.z_ * q.z_);
   x_ = p.s_ * q.x_ +  q.s_ * p.x_ + p.y_ * q.z_ - p.z_ * q.y_;
   y_ = p.s_ * q.y_ +  q.s_ * p.y_ + p.z_ * q.x_ - p.x_ * q.z_;
   z_ = p.s_ * q.z_ +  q.s_ * p.z_ + p.x_ * q.y_ - p.y_ * q.x_;
   return *this;
 }
Referenced by Se3f::mult(), and operator%().
negate() [1/2]
xm_inline QuatF& QuatF::negate () inline
 { s_ = -s_; x_ = -x_; y_ = -y_; z_ = -z_; return *this; }
Referenced by slerp().
negate() [2/2]
xm_inline QuatF& QuatF::negate (const QuatF & q) inline
 { s_ = -q.s_; x_ = -q.x_; y_ = -q.y_; z_ = -q.z_; return *this; }
norm()
xm_inline float QuatF::norm () const inline
 { return sqrtf(x_*x_ + y_*y_ + z_*z_ + s_*s_); }
normalize() [1/2]
QuatF & QuatF::normalize ()
 {
   float scale;
   scale = 1.f / sqrtf(s_*s_ + x_*x_ + y_*y_ + z_*z_);
   s_ *= scale;
   x_ *= scale;
   y_ *= scale;
   z_ *= scale;
   return *this;
 }
normalize() [2/2]
QuatF & QuatF::normalize (const QuatF & q)
 {
   float scale;
   scale = 1.f / sqrtf(q.s_*q.s_ + q.x_*q.x_ + q.y_*q.y_ + q.z_*q.z_);
   s_ = scale * q.s_;
   x_ = scale * q.x_;
   y_ = scale * q.y_;
   z_ = scale * q.z_;
   return *this;
 }
operator const float *()
xm_inline QuatF::operator const float * () const inline
 { return &s_; }
operator float *()
xm_inline QuatF::operator float * () inline
 { return &s_; }
operator QuatD()
QuatF::operator QuatD () const
 {
     return QuatD((float)s_,(float)x_,(float)y_,(float)z_);
 }
operator!=()
int QuatF::operator!= (const QuatF & other) const
 {
   return fabs(s_ - other.s_) > FLT_COMPARE_TOLERANCE ||
         fabs(x_ - other.x_) > FLT_COMPARE_TOLERANCE ||
         fabs(y_ - other.y_) > FLT_COMPARE_TOLERANCE ||
         fabs(z_ - other.z_) > FLT_COMPARE_TOLERANCE;
 }
References FLT_COMPARE_TOLERANCE.
operator%()
xm_inline QuatF QuatF::operator% (const QuatF & q) const inline
 { QuatF u; return u.mult(*this, q); }
References mult().
operator%=()
xm_inline QuatF& QuatF::operator%= (const QuatF & q) inline
 { return postmult(q); }
References postmult().
operator*()
QuatF QuatF::operator* (float s) const
 {
     return QuatF(s_*w,x_*w,y_*w,z_*w);
 }
References QuatF().
operator*=()
QuatF & QuatF::operator*= (float s)
 {
     s_ *= w;
     x_ *= w;
     y_ *= w;
     z_ *= w;
     return *this;
 }
operator+()
QuatF QuatF::operator+ (const QuatF & q) const
 {
     return QuatF(s_ + q.s_,x_ + q.x_,y_ + q.y_,z_ + q.z_);
 }
References QuatF().
operator+=()
QuatF & QuatF::operator+= (const QuatF & q)
 {
     s_ += q.s_;
     x_ += q.x_;
     y_ += q.y_;
     z_ += q.z_;
     return *this;
 }
operator-() [1/2]
xm_inline QuatF QuatF::operator- () const inline
 { return QuatF(-s_, -x_, -y_, -z_); }
References QuatF().
operator-() [2/2]
QuatF QuatF::operator- (const QuatF & q) const
 {
     return QuatF(s_ - q.s_,x_ - q.x_,y_ - q.y_,z_ - q.z_);
 }
References QuatF().
operator-=()
QuatF & QuatF::operator-= (const QuatF & q)
 {
     s_ -= q.s_;
     x_ -= q.x_;
     y_ -= q.y_;
     z_ -= q.z_;
     return *this;
 }
operator/()
QuatF QuatF::operator/ (float s) const
 {
     w = 1/w;
     return QuatF(s_*w,x_*w,y_*w,z_*w);
 }
References QuatF().
operator/=()
QuatF & QuatF::operator/= (float s)
 {
     w = 1/w;
     s_ *= w;
     x_ *= w;
     y_ *= w;
     z_ *= w;
     return *this;
 }
operator==()
int QuatF::operator== (const QuatF & other) const
 {
   return fabs(s_ - other.s_) < FLT_COMPARE_TOLERANCE &&
         fabs(x_ - other.x_) < FLT_COMPARE_TOLERANCE &&
         fabs(y_ - other.y_) < FLT_COMPARE_TOLERANCE &&
         fabs(z_ - other.z_) < FLT_COMPARE_TOLERANCE;
 }
References FLT_COMPARE_TOLERANCE.
operator[]() [1/2]
xm_inline float& QuatF::operator[] (int i) inline
 {return *(&s_ + i);}
operator[]() [2/2]
xm_inline const float& QuatF::operator[] (int i) const inline
 {return *(&s_ + i);}
postmult()
QuatF & QuatF::postmult (const QuatF & q)
 {
   float ox, oy, oz;
   ox = x_; oy = y_; oz = z_;
   x_ = s_ * q.x_ +  ox * q.s_ + oy * q.z_ - oz * q.y_;
   y_ = s_ * q.y_ +  oy * q.s_ + oz * q.x_ - ox * q.z_;
   z_ = s_ * q.z_ +  oz * q.s_ + ox * q.y_ - oy * q.x_;
   s_ = s_ * q.s_ - (ox * q.x_ + oy * q.y_ + oz * q.z_);
   return *this;
 }
Referenced by operator%=(), and Se3f::postmult().
premult()
QuatF & QuatF::premult (const QuatF & q)
 {
   float ox, oy, oz;
   ox = x_; oy = y_; oz = z_;
   x_ = q.s_ * ox +  s_ * q.x_ + q.y_ * oz - q.z_ * oy;
   y_ = q.s_ * oy +  s_ * q.y_ + q.z_ * ox - q.x_ * oz;
   z_ = q.s_ * oz +  s_ * q.z_ + q.x_ * oy - q.y_ * ox;
   s_ = q.s_ * s_ - (q.x_ * ox + q.y_ * oy + q.z_ * oz);
   return *this;
 }
Referenced by Se3f::premult().
s() [1/2]
float& QuatF::s () inline
 {return s_;}
s() [2/2]
float QuatF::s () const inline
 {return s_;}
Referenced by Mat3f::operator*(), Mat3f::operator*=(), Mat3f::operator/(), Mat3f::operator/=(), QuatF(), and set().
set() [1/3]
QuatF & QuatF::set (const Mat3f & R)
 {
   float qs2, qx2, qy2, qz2;  // squared magniudes of quaternion components
   float tmp;
   int i;
   // first compute squared magnitudes of quaternion components - at least one
   // will be greater than 0 since quaternion is unit magnitude
   qs2 = 0.25f * (R.xx + R.yy + R.zz + 1);
   qx2 = qs2 - 0.5f * (R.yy + R.zz);
   qy2 = qs2 - 0.5f * (R.zz + R.xx);
   qz2 = qs2 - 0.5f * (R.xx + R.yy);
   // find maximum magnitude component
   i = (qs2 > qx2 ) ?
     ((qs2 > qy2) ? ((qs2 > qz2) ? 0 : 3) : ((qy2 > qz2) ? 2 : 3)) :
     ((qx2 > qy2) ? ((qx2 > qz2) ? 1 : 3) : ((qy2 > qz2) ? 2 : 3));
   // compute signed quaternion components using numerically stable method
   switch(i) {
   case 0:
     s_ = sqrtf(qs2);
     tmp = 0.25f / s_;
     x_ = (R.zy - R.yz) * tmp;
     y_ = (R.xz - R.zx) * tmp;
     z_ = (R.yx - R.xy) * tmp;
     break;
   case 1:
     x_ = sqrtf(qx2);
     tmp = 0.25f / x_;
     s_ = (R.zy - R.yz) * tmp;
     y_ = (R.xy + R.yx) * tmp;
     z_ = (R.xz + R.zx) * tmp;
     break;
   case 2:
     y_ = sqrtf(qy2);
     tmp = 0.25f / y_;
     s_ = (R.xz - R.zx) * tmp;
     z_ = (R.yz + R.zy) * tmp;
     x_ = (R.yx + R.xy) * tmp;
     break;
   case 3:
     z_ = sqrtf(qz2);
     tmp = 0.25f / z_;
     s_ = (R.yx - R.xy) * tmp;
     x_ = (R.zx + R.xz) * tmp;
     y_ = (R.zy + R.yz) * tmp;
     break;
   }
   // for consistency, force positive scalar component [ (s; v) = (-s; -v) ]
   if (s_ < 0) {
     s_ = -s_;
     x_ = -x_;
     y_ = -y_;
     z_ = -z_;
   }
   // normalize, just to be safe
   tmp = 1.f / sqrtf(s_*s_ + x_*x_ + y_*y_ + z_*z_);
   s_ *= tmp;
   x_ *= tmp;
   y_ *= tmp;
   z_ *= tmp;
   return *this;
 }
set() [2/3]
QuatF & QuatF::set (float angle, const Vect3f & axis, int normalizeAxis = 1)
 {
     float theta = 0.5f * angle;
     float sine = sinf(theta);
     s_ = cosf(theta);
     if(normalizeAxis){
         float n2;
         if((n2 = axis.norm2()) < FLT_EPS){
             *this = QuatD::ID;
             return *this;
             }
         sine /= sqrtf(n2);
         }
     x_ = axis.x * sine;
     y_ = axis.y * sine;
     z_ = axis.z * sine;
     return *this;
 }
References angle(), axis(), FLT_EPS, QuatD::ID, Vect3f::norm2(), Vect3f::x, Vect3f::y, and Vect3f::z.
set() [3/3]
xm_inline QuatF& QuatF::set (float s, float x, float y, float z) inline
 { s_=s; x_=x; y_=y; z_=z; return *this; }
References s(), x(), y(), and z().
Referenced by QuatF(), Se3f::set(), and Mat3f::set().
slerp()
xm_inline void QuatF::slerp (const QuatF & a, const QuatF & b, float t)
 {
     // Slerp(q1,q2,t) = (sin((1-t)*A)/sin(A))*q1+(sin(t*A)/sin(A))*q2
         float scale0, scale1;
         // calc cosine
         float cosom = a.dot(b);
         // adjust signs (if necessary)
         if(cosom < 0.0){
         cosom = -cosom;
         negate(b);
         }
     else
         *this = b;
         // calculate coefficients
        if ((1.0 - cosom) > 1e-5f ) {
                 // standard case (slerp)
                 float omega = acosf(cosom);
                 float sinom = sinf(omega);
                 scale0 = sinf((1.0f - t) * omega) / sinom;
                 scale1 = sinf(t * omega) / sinom;
         }
         else {  // "from" and "to" quaternions are very close, so we can do a linear interpolation
                 scale0 = 1.0f - t;
                 scale1 = t;
         }
         // calculate final values
     *this *= scale1;
     *this += a*scale0;
 }
References dot(), and negate().
x() [1/2]
float& QuatF::x () inline
 {return x_;}
x() [2/2]
float QuatF::x () const inline
 {return x_;}
Referenced by QuatF(), and set().
xform() [1/2]
Vect3f & QuatF::xform (const Vect3f & u, Vect3f & v) const
 {
   Vect3f *u, uv, uuv;
   u = (Vect3f *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.f * s_);
   uuv.scale(2.f);
   xv.add(v, uv);
   xv.add(uuv);
   return xv;
 }
References Vect3f::add(), Vect3f::cross(), and Vect3f::scale().
Referenced by Se3f::invert(), Se3f::mult(), Se3f::postmult(), Se3f::premult(), Se3f::xformPoint(), and Se3f::xformVect().
xform() [2/2]
Vect3f & QuatF::xform (Vect3f & v) const
 {
   Vect3f *u, uv, uuv;
   u = (Vect3f *) &x_;
   uv.cross(*u, v);
   uuv.cross(*u, uv);
   uv.scale(2.f * s_);
   uuv.scale(2.f);
   v.add(uv);
   v.add(uuv);
   return v;
 }
References Vect3f::add(), Vect3f::cross(), and Vect3f::scale().
y() [1/2]
float& QuatF::y () inline
 {return y_;}
y() [2/2]
float QuatF::y () const inline
 {return y_;}
Referenced by QuatF(), and set().
z() [1/2]
float& QuatF::z () inline
 {return z_;}
z() [2/2]
float QuatF::z () const inline
 {return z_;}
Referenced by QuatF(), and set().
Friends And Related Function Documentation
dot
xm_inline friend float dot (const QuatF & u, const QuatF & v) friend
 { return u.dot(v); }
Mat3f
friend class Mat3f friend
normalize
xm_inline friend QuatF normalize (const QuatF & q) friend
 {
   float scale;
   scale = 1.f / sqrtf(q.s_*q.s_ + q.x_*q.x_ + q.y_*q.y_ + q.z_*q.z_);
   return QuatF(scale * q.s_, scale * q.x_, scale * q.y_, scale * q.z_);
 }
operator*
xm_inline friend QuatF operator* (float s, const QuatF & q) friend
 {
     return QuatF(q.s_*w,q.x_*w,q.y_*w,q.z_*w);
 }
operator< [1/2]
XBuffer& operator< (XBuffer & b, const QuatF & q) friend
 {
     b < q.s_ < q.x_ < q.y_ < q.z_;
     return b;
 }
operator< [2/2]
XStream& operator< (XStream & s, const QuatF & q) friend
 {
     s.write(&q,sizeof(QuatF));
     return s;
 }
operator<<
ostream& operator<< (ostream & os, const QuatF & q) friend
 {
   os << q.s_ << " \t" << q.x_ << " \t" << q.y_ << " \t" << q.z_;
   return os;
 }
operator<= [1/2]
XBuffer& operator<= (XBuffer & b, const QuatF & q) friend
 {
     b <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return b;
 }
operator<= [2/2]
XStream& operator<= (XStream & s, const QuatF & q) friend
 {
     s <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return s;
 }
operator> [1/2]
XBuffer& operator> (XBuffer & b, QuatF & q) friend
 {
     b > q.s_ > q.x_ > q.y_ > q.z_;
     return b;
 }
operator> [2/2]
XStream& operator> (XStream & s, QuatF & q) friend
 {
     s.read(&q,sizeof(QuatF));
     return s;
 }
operator>= [1/2]
XBuffer& operator>= (XBuffer & b, QuatF & q) friend
 {
     b >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return b;
 }
operator>= [2/2]
XStream& operator>= (XStream & s, QuatF & q) friend
 {
     s >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return s;
 }
operator>>
istream& operator>> (istream & is, QuatF & q) friend
 {
   is >> q.s_ >> q.x_ >> q.y_ >> q.z_;
   return is;
 }
Se3f
friend class Se3f friend
Member Data Documentation
ID
const QuatF QuatF::ID static
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp