Vangers: XTList< Type > Class Template Reference
XTList< Type > Class Template Reference
#include <xcontainers.h>
Public Member Functions
XTList ()
~XTList ()
int size ()
Type * first ()
Type * last ()
void clear ()
void delete_all ()
void insert (Type *p)
void append (Type *p)
void insert (Type *pointer, Type *p)
void append (Type *pointer, Type *p)
void remove (Type *p)
Type * search (int ID)
Detailed Description
template<class Type>
class XTList< Type >
Constructor & Destructor Documentation
XTList()
template<class Type > XTList< Type >::XTList inline
 {
     num_elements = 0; first_element = 0;
 }
~XTList()
template<class Type > XTList< Type >::~XTList inline
 {
     clear();
 }
Member Function Documentation
append() [1/2]
template<class Type > void XTList< Type >::append (Type * p) inline
 {
     if(p -> list)
         ErrH.Abort("Element is already in list");
     num_elements++;
     if(first_element){
         p -> next = 0;
         p -> prev = first_element -> prev;
         first_element -> prev -> next = p;
         first_element -> prev = p;
         }
     else{
         p -> next = 0;
         p -> prev = first_element = p;
         }
     p -> list = this;
 }
References XErrorHandler::Abort(), and ErrH.
Referenced by World::add_object(), Game::attach_player(), Server::check_new_clients(), Server::create_game(), Server::load_rating_list(), Game::load_result(), World::move_object(), Game::process_create_globals(), World::process_create_inventory(), Game::quant(), and Player::receive().
append() [2/2]
template<class Type > void XTList< Type >::append (Type * pointer, Type * p)
clear()
template<class Type > void XTList< Type >::clear (void) inline
 {
     while(first())
         remove(first());
 }
delete_all()
template<class Type > void XTList< Type >::delete_all inline
 {
     Type* p;
     while((p = first()) != 0){
         remove(p);
         delete p;
         }
 }
Referenced by Game::load_result(), and Game::~Game().
first()
template<class Type > Type * XTList< Type >::first inline
 {
     return first_element;
 }
Referenced by Server::add_rating_data(), Game::check_global_objects(), CheckPlayerList(), Server::clear(), Server::clients_quant(), World::detach_player(), VangerUnit::DrawQuant(), Server::games_quant(), Server::get_games_list(), Game::get_object_ID_offsets(), Server::get_top_list(), Game::get_total_list_of_players_data(), iCreateServer(), iHandleExtEvent(), iInitChatButtons(), iPrepareHallOfFame(), iSortPlayers(), iUpdateServersList(), NetSlotEvent(), network_analysis(), Game::process_create_globals(), Game::process_delete_globals(), Game::process_direct_sending(), Game::process_MECHOSOMA_ratings(), Game::process_PASSEMBLOSS_ratings(), World::process_set_position(), Game::process_update_globals(), Game::process_VAN_WAR_ratings(), Game::put_event_for_all(), Game::quant(), Server::quant(), CompasObject::Quant(), ActionDispatcher::Quant(), Player::receive(), Server::report(), Server::save_rating_list(), Server::search_rating_data(), test_block(), xtInitApplication(), Game::~Game(), and Server::~Server().
insert() [1/2]
template<class Type > void XTList< Type >::insert (Type * p) inline
 {
     if(p -> list)
         ErrH.Abort("Element is already in list");
     num_elements++;
     if(first_element){
         p -> next = first_element;
         p -> prev = first_element -> prev;
         first_element -> prev = p;
         }
     else{
         p -> prev = p;
         p -> next = 0;
         }
     first_element = p;
     p -> list = this;
 }
References XErrorHandler::Abort(), and ErrH.
Referenced by Server::add_rating_data().
insert() [2/2]
template<class Type > void XTList< Type >::insert (Type * pointer, Type * p) inline
 {
     if(!first_element || first_element == pointer){
         insert(p);
         return;
         }
     if(!pointer){
         append(p);
         return;
         }
     if(p -> list)
         ErrH.Abort("Element is already in list");
     num_elements++;
     p -> next = pointer;
     p -> prev = pointer -> prev;
     pointer -> prev -> next = p;
     pointer -> prev = p;
     p -> list = this;
 }
References XErrorHandler::Abort(), and ErrH.
last()
template<class Type > Type * XTList< Type >::last inline
 {
     return first_element -> prev;
 }
References prev.
remove()
template<class Type > void XTList< Type >::remove (Type * p) inline
 {
     if(p -> list != this)
         ErrH.Abort("Removed element isn't in list");
     num_elements--;
     if(p -> next)
         p -> next -> prev = p -> prev;
     else
         first_element -> prev = p -> prev;
     if(p != first_element)
         p -> prev -> next = p -> next;
     else{
         first_element = p -> next;
         if(first_element)
             first_element -> prev = p -> prev;
         }
     p -> next = p -> prev = 0;
     p -> list = 0;
 }
References XErrorHandler::Abort(), and ErrH.
Referenced by Server::add_rating_data(), Game::attach_player(), Server::clear(), Player::clear_object_queue(), Server::clients_quant(), World::delete_object(), Game::detach_player(), Server::games_quant(), World::move_object(), Player::receive(), Player::send(), Game::~Game(), and Server::~Server().
search()
template<class Type > Type * XTList< Type >::search (int ID) inline
 {
     Type* p = first();
     while(p){
         if(p -> ID == ID)
             return p;
         p = p -> next;
         }
     return 0;
 }
Referenced by Player::receive().
size()
template<class Type > int XTList< Type >::size (void) inline
 {
     return num_elements;
 }
Referenced by aciShowFrags(), Server::consoleReport(), KDWIN::create_server(), Game::get_total_list_of_players_data(), iChatMouseHandler(), iInitChatButtons(), iPrepareHallOfFame(), iSortPlayers(), Server::quant(), Player::receive(), Server::report(), Server::save_rating_list(), Game::save_result(), and Game::~Game().
The documentation for this class was generated from the following file:
src/xcontainers.h