Vangers: Mat2f Class Reference
Mat2f Class Reference
#include <xmath.h>
Public Member Functions
Mat2f ()
Mat2f (float angle)
Mat2f (float xx_, float xy_, float yx_, float yy_)
void set (float angle)
xm_inline const Vect2f & operator[] (int i) const
xm_inline Vect2f & operator[] (int i)
xm_inline Vect2f xcol () const
xm_inline Vect2f ycol () const
xm_inline Vect2f col (int axis) const
void invert ()
xm_inline Mat2f & operator*= (const Mat2f &m)
xm_inline Vect2f invXform (const Vect2f &v) const
Friends
xm_inline friend Vect2f & operator*= (Vect2f &v, const Mat2f &m)
Detailed Description
Constructor & Destructor Documentation
Mat2f() [1/3]
Mat2f::Mat2f () inline
 {}
Referenced by operator*=().
Mat2f() [2/3]
Mat2f::Mat2f (float angle) inline explicit
 { set(angle); }
References set().
Mat2f() [3/3]
Mat2f::Mat2f (float xx_, float xy_, float yx_, float yy_) inline
 { xx = xx_; xy = xy_; yx = yx_; yy = yy_; }
Member Function Documentation
col()
xm_inline Vect2f Mat2f::col (int axis) const inline
 { return axis == X_AXIS ? Vect2f(xx, yx) : Vect2f(xy, yy); }
References X_AXIS.
invert()
void Mat2f::invert () inline
 { float t = xy; xy = yx; yx = t; }
Referenced by MatX2f::invert().
invXform()
xm_inline Vect2f Mat2f::invXform (const Vect2f & v) const inline
 { return Vect2f(v.x*xx + v.y*yx, v.x*xy + v.y*yy); }
References Vect2f::x, and Vect2f::y.
Referenced by MatX2f::invert(), and MatX2f::invXform().
operator*=()
xm_inline Mat2f& Mat2f::operator*= (const Mat2f & m) inline
 { return (*this) = Mat2f(xx*m.xx+xy*m.yx, xx*m.xy+xy*m.yy, yx*m.xx+yy*m.yx, yx*m.xy+yy*m.yy); }
References Mat2f().
operator[]() [1/2]
xm_inline Vect2f& Mat2f::operator[] (int i) inline
 { return ((Vect2f*)&xx)[i]; }
operator[]() [2/2]
xm_inline const Vect2f& Mat2f::operator[] (int i) const inline
 { return ((Vect2f*)&xx)[i]; }
set()
void Mat2f::set (float angle) inline
 { xx = yy = cosf(angle); yx = sinf(angle); xy = -yx; }
Referenced by Mat2f().
xcol()
xm_inline Vect2f Mat2f::xcol () const inline
 { return Vect2f(xx, yx); }
ycol()
xm_inline Vect2f Mat2f::ycol () const inline
 { return Vect2f(xy, yy); }
Friends And Related Function Documentation
operator*=
xm_inline friend Vect2f& operator*= (Vect2f & v, const Mat2f & m) friend
 { float x = v.x*m.xx + v.y*m.xy; v.y = v.x*m.yx + v.y*m.yy; v.x = x; return v; }
The documentation for this class was generated from the following file:
lib/xtool/xmath/xmath.h