Vangers: Mat4f Class Reference
Mat4f Class Reference
#include <xmath.h>
Public Member Functions
xm_inline Mat4f ()
xm_inline Mat4f (float xx, float xy, float xz, float xw, float yx, float yy, float yz, float yw, float zx, float zy, float zz, float zw, float wx, float wy, float wz, float ww)
xm_inline Mat4f (const Mat3f &rot)
xm_inline Mat4f (const Mat3f &rot, const Vect3f &trans)
xm_inline Mat4f (const MatXf &X)
xm_inline Mat4f & set (const Mat3f &rot)
xm_inline Mat4f & set (const Mat3f &rot, const Vect3f &trans)
xm_inline Mat4f & set (const MatXf &X)
xm_inline const Vect4f & operator[] (int i) const
xm_inline Vect4f & operator[] (int i)
xm_inline const Vect4f & xrow () const
xm_inline const Vect4f & yrow () const
xm_inline const Vect4f & zrow () const
xm_inline const Vect4f & wrow () const
xm_inline Vect4f & xrow ()
xm_inline Vect4f & yrow ()
xm_inline Vect4f & zrow ()
xm_inline Vect4f & wrow ()
xm_inline Vect4f xcol () const
xm_inline Vect4f ycol () const
xm_inline Vect4f zcol () const
xm_inline Vect4f wcol () const
xm_inline Mat4f & setXcol (const Vect4f &v)
xm_inline Mat4f & setYcol (const Vect4f &v)
xm_inline Mat4f & setZcol (const Vect4f &v)
xm_inline Mat4f & setWcol (const Vect4f &v)
xm_inline Vect4f diag () const
xm_inline const float & operator() (int i, int j) const
xm_inline float & operator() (int i, int j)
xm_inline float det () const
Mat4f & mult (const Mat4f &M, const Mat4f &N)
Mat4f & premult (const Mat4f &M)
Mat4f & postmult (const Mat4f &M)
Mat4f & operator*= (const Mat4f &M)
Mat4f operator* (const Mat4f &M) const
xm_inline Mat4f & xpose ()
xm_inline Mat4f & xpose (const Mat4f &M)
int invert ()
int invert (const Mat4f &M)
xm_inline Vect4f & xform (const Vect4f &v, Vect4f &xv) const
xm_inline Vect4f & xform (Vect4f &v) const
xm_inline Vect4f & xform (const Vect3f &v, Vect4f &xv) const
Static Public Attributes
static const Mat4f ZERO
static const Mat4f ID
Friends
xm_inline friend Mat4f xpose (const Mat4f &M)
xm_inline friend Mat4f invert (const Mat4f &M)
xm_inline friend Vect4f & operator*= (Vect4f &v, const Mat4f &M)
xm_inline friend Vect4f operator* (const Vect4f &v, const Mat4f &M)
xm_inline friend Vect4f operator* (const Mat4f &M, const Vect4f &v)
xm_inline friend Vect4f operator* (const Vect3f &v, const Mat4f &M)
xm_inline friend Vect4f operator* (const Mat4f &M, const Vect3f &v)
ostream & operator<< (ostream &os, const Mat4f &M)
istream & operator>> (istream &is, Mat4f &M)
XStream & operator<= (XStream &s, const Mat4f &M)
XStream & operator>= (XStream &s, Mat4f &M)
XStream & operator< (XStream &s, const Mat4f &M)
XStream & operator> (XStream &s, Mat4f &M)
XBuffer & operator<= (XBuffer &b, const Mat4f &M)
XBuffer & operator>= (XBuffer &b, Mat4f &M)
XBuffer & operator< (XBuffer &b, const Mat4f &M)
XBuffer & operator> (XBuffer &b, Mat4f &M)
Detailed Description
Constructor & Destructor Documentation
Mat4f() [1/5]
xm_inline Mat4f::Mat4f () inline
 {}
Mat4f() [2/5]
Mat4f::Mat4f (float xx, float xy, float xz, float xw, float yx, float yy, float yz, float yw, float zx, float zy, float zz, float zw, float wx, float wy, float wz, float ww)
 {
     xx = xx_; xy = xy_; xz = xz_; xw = xw_;
     yx = yx_; yy = yy_; yz = yz_; yw = yw_;
     zx = zx_; zy = zy_; zz = zz_; zw = zw_;
     wx = wx_; wy = wy_; wz = wz_; ww = ww_;
 }
Mat4f() [3/5]
xm_inline Mat4f::Mat4f (const Mat3f & rot) inline
 { set(rot); }
References set().
Mat4f() [4/5]
xm_inline Mat4f::Mat4f (const Mat3f & rot, const Vect3f & trans) inline
 { set(rot, trans); }
References set().
Mat4f() [5/5]
xm_inline Mat4f::Mat4f (const MatXf & X) inline
 { set(X); }
References set().
Member Function Documentation
det()
xm_inline float Mat4f::det () const
diag()
xm_inline Vect4f Mat4f::diag () const inline
 {return Vect4f(xx, yy, zz, ww); }
invert() [1/2]
int Mat4f::invert ()
invert() [2/2]
int Mat4f::invert (const Mat4f & M)
mult()
Mat4f & Mat4f::mult (const Mat4f & M, const Mat4f & N)
 {
     for(int i = 0; i < 4; i++)
         for(int j = 0; j < 4; j++)
             (*this)[i][j] = M[i][0]*N[0][j] + M[i][1]*N[1][j] + M[i][2]*N[2][j] + M[i][3]*N[3][j];
     return *this;
 }
Referenced by operator*(), postmult(), and premult().
operator()() [1/2]
xm_inline float& Mat4f::operator() (int i, int j) inline
 { return (&xx)[(i - 1)*4 + j - 1]; }
operator()() [2/2]
xm_inline const float& Mat4f::operator() (int i, int j) const inline
 { return (&xx)[(i - 1)*4 + j - 1]; }
operator*()
Mat4f Mat4f::operator* (const Mat4f & M) const inline
 { Mat4f N; return N.mult(*this, M); }
References mult().
operator*=()
Mat4f& Mat4f::operator*= (const Mat4f & M) inline
 { return postmult(M); }
References postmult().
operator[]() [1/2]
xm_inline Vect4f& Mat4f::operator[] (int i) inline
 {return *(((Vect4f *) &xx) + i);}
operator[]() [2/2]
xm_inline const Vect4f& Mat4f::operator[] (int i) const inline
 {return *(((Vect4f *) &xx) + i);}
postmult()
Mat4f & Mat4f::postmult (const Mat4f & M)
 {
     Mat4f N = *this;
      return mult(N, M);
 }
References mult().
Referenced by operator*=().
premult()
Mat4f & Mat4f::premult (const Mat4f & M)
 {
     Mat4f N = *this;
      return mult(M, N);
 }
References mult().
set() [1/3]
Mat4f & Mat4f::set (const Mat3f & rot)
 {
     xx = rot.xx; xy = rot.xy; xz = rot.xz; xw = 0;
     yx = rot.yx; yy = rot.yy; yz = rot.yz; yw = 0;
     zx = rot.zx; zy = rot.zy; zz = rot.zz; zw = 0;
     wx = 0; wy = 0; wz = 0; ww = 1.0f;
     return *this;
 }
Referenced by Mat4f().
set() [2/3]
Mat4f & Mat4f::set (const Mat3f & rot, const Vect3f & trans)
 {
     xx = rot.xx; xy = rot.xy; xz = rot.xz; xw = trans.x;
     yx = rot.yx; yy = rot.yy; yz = rot.yz; yw = trans.y;
     zx = rot.zx; zy = rot.zy; zz = rot.zz; zw = trans.z;
     wx = 0; wy = 0; wz = 0; ww = 1.0f;
     return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
set() [3/3]
Mat4f & Mat4f::set (const MatXf & X)
 {
     const Mat3f& rot = X.rot();
     const Vect3f& trans = X.trans();
     xx = rot.xx; xy = rot.xy; xz = rot.xz; xw = trans.x;
     yx = rot.yx; yy = rot.yy; yz = rot.yz; yw = trans.y;
     zx = rot.zx; zy = rot.zy; zz = rot.zz; zw = trans.z;
     wx = 0; wy = 0; wz = 0; ww = 1.0f;
     return *this;
 }
References MatXf::rot(), MatXf::trans(), Vect3f::x, Vect3f::y, and Vect3f::z.
setWcol()
Mat4f & Mat4f::setWcol (const Vect4f & v)
 {
   xw = v.x;
   yw = v.y;
   zw = v.z;
   ww = v.w;
   return *this;
 }
References Vect4f::w, Vect4f::x, Vect4f::y, and Vect4f::z.
setXcol()
Mat4f & Mat4f::setXcol (const Vect4f & v)
 {
   xx = v.x;
   yx = v.y;
   zx = v.z;
   wx = v.w;
   return *this;
 }
References Vect4f::w, Vect4f::x, Vect4f::y, and Vect4f::z.
setYcol()
Mat4f & Mat4f::setYcol (const Vect4f & v)
 {
   xy = v.x;
   yy = v.y;
   zy = v.z;
   wy = v.w;
   return *this;
 }
References Vect4f::w, Vect4f::x, Vect4f::y, and Vect4f::z.
setZcol()
Mat4f & Mat4f::setZcol (const Vect4f & v)
 {
   xz = v.x;
   yz = v.y;
   zz = v.z;
   wz = v.w;
   return *this;
 }
References Vect4f::w, Vect4f::x, Vect4f::y, and Vect4f::z.
wcol()
xm_inline Vect4f Mat4f::wcol () const inline
 {return Vect4f(xw, yw, zw, ww);}
wrow() [1/2]
xm_inline Vect4f& Mat4f::wrow () inline
 {return *((Vect4f *) &wx);}
wrow() [2/2]
xm_inline const Vect4f& Mat4f::wrow () const inline
 {return *((Vect4f *) &wx);}
xcol()
xm_inline Vect4f Mat4f::xcol () const inline
 {return Vect4f(xx, yx, zx, wx);}
xform() [1/3]
Vect4f & Mat4f::xform (const Vect3f & v, Vect4f & xv) const
 {
   xv.x = xx * v.x + xy * v.y + xz * v.z + xw;
   xv.y = yx * v.x + yy * v.y + yz * v.z + yw;
   xv.z = zx * v.x + zy * v.y + zz * v.z + zw;
   xv.w = wx * v.x + wy * v.y + wz * v.z + ww;
   return xv;
 }
References Vect4f::w, Vect3f::x, Vect4f::x, Vect3f::y, Vect4f::y, Vect3f::z, and Vect4f::z.
xform() [2/3]
Vect4f & Mat4f::xform (const Vect4f & v, Vect4f & xv) const
 {
   xv.x = xx * v.x + xy * v.y + xz * v.z + xw * v.w;
   xv.y = yx * v.x + yy * v.y + yz * v.z + yw * v.w;
   xv.z = zx * v.x + zy * v.y + zz * v.z + zw * v.w;
   xv.w = wx * v.x + wy * v.y + wz * v.z + ww * v.w;
   return xv;
 }
References Vect4f::w, Vect4f::x, Vect4f::y, and Vect4f::z.
Referenced by xform().
xform() [3/3]
Vect4f & Mat4f::xform (Vect4f & v) const
 {
   Vect4f v0 = v;
   return xform(v0, v);
 }
References xform().
xpose() [1/2]
Mat4f & Mat4f::xpose ()
 {
   #define __swap__(x,y) { float t = y; y = x; x = t; }
   __swap__(xy, yx);
   __swap__(yz, zy);
   __swap__(zx, xz);
   __swap__(xw, wx);
   __swap__(yw, wy);
   __swap__(zw, wz);
   #undef __swap__
   return *this;
 }
References __swap__.
xpose() [2/2]
Mat4f & Mat4f::xpose (const Mat4f & M)
 {
   xx = M.xx;
   xy = M.yx;
   xz = M.zx;
   xw = M.wx;
   yx = M.xy;
   yy = M.yy;
   yz = M.zy;
   yw = M.wy;
   zx = M.xz;
   zy = M.yz;
   zz = M.zz;
   zw = M.wz;
   wx = M.xw;
   wy = M.yw;
   wz = M.zw;
   ww = M.ww;
   return *this;
 }
xrow() [1/2]
xm_inline Vect4f& Mat4f::xrow () inline
 {return *((Vect4f *) &xx);}
xrow() [2/2]
xm_inline const Vect4f& Mat4f::xrow () const inline
 {return *((Vect4f *) &xx);}
ycol()
xm_inline Vect4f Mat4f::ycol () const inline
 {return Vect4f(xy, yy, zy, wy);}
yrow() [1/2]
xm_inline Vect4f& Mat4f::yrow () inline
 {return *((Vect4f *) &yx);}
yrow() [2/2]
xm_inline const Vect4f& Mat4f::yrow () const inline
 {return *((Vect4f *) &yx);}
zcol()
xm_inline Vect4f Mat4f::zcol () const inline
 {return Vect4f(xz, yz, zz, wz);}
zrow() [1/2]
xm_inline Vect4f& Mat4f::zrow () inline
 {return *((Vect4f *) &zx);}
zrow() [2/2]
xm_inline const Vect4f& Mat4f::zrow () const inline
 {return *((Vect4f *) &zx);}
Friends And Related Function Documentation
invert
xm_inline friend Mat4f invert (const Mat4f & M) friend
 { Mat4f N; N.invert(M); return N; }
operator* [1/4]
xm_inline friend Vect4f operator* (const Mat4f & M, const Vect3f & v) friend
 { Vect4f xv; return M.xform(v, xv); }
operator* [2/4]
xm_inline friend Vect4f operator* (const Mat4f & M, const Vect4f & v) friend
 { Vect4f xv; return M.xform(v, xv); }
operator* [3/4]
xm_inline friend Vect4f operator* (const Vect3f & v, const Mat4f & M) friend
 { Vect4f xv; return M.xform(v, xv); }
operator* [4/4]
xm_inline friend Vect4f operator* (const Vect4f & v, const Mat4f & M) friend
 { Vect4f xv; return M.xform(v, xv); }
operator*=
xm_inline friend Vect4f& operator*= (Vect4f & v, const Mat4f & M) friend
 { return M.xform(v); }
operator< [1/2]
XBuffer& operator< (XBuffer & b, const Mat4f & M) friend
operator< [2/2]
XStream& operator< (XStream & s, const Mat4f & M) friend
operator<<
ostream& operator<< (ostream & os, const Mat4f & M) friend
operator<= [1/2]
XBuffer& operator<= (XBuffer & b, const Mat4f & M) friend
operator<= [2/2]
XStream& operator<= (XStream & s, const Mat4f & M) friend
operator> [1/2]
XBuffer& operator> (XBuffer & b, Mat4f & M) friend
operator> [2/2]
XStream& operator> (XStream & s, Mat4f & M) friend
operator>= [1/2]
XBuffer& operator>= (XBuffer & b, Mat4f & M) friend
operator>= [2/2]
XStream& operator>= (XStream & s, Mat4f & M) friend
operator>>
istream& operator>> (istream & is, Mat4f & M) friend
xpose
xm_inline friend Mat4f xpose (const Mat4f & M) friend
 { Mat4f N; return N.xpose(M); }
Member Data Documentation
ID
const Mat4f Mat4f::ID static
ZERO
const Mat4f Mat4f::ZERO static
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp