Vangers: XIQueue< Type > Class Template Reference
XIQueue< Type > Class Template Reference
#include <xcontainers.h>
Public Member Functions
XIQueue (int size)
int empty ()
void clear ()
Type put (Type p, int ID)
Type get ()
Detailed Description
template<class Type>
class XIQueue< Type >
Constructor & Destructor Documentation
XIQueue()
template<class Type > XIQueue< Type >::XIQueue (int size) inline
 {
     if((1 << BitSR(sz)) != sz)
         ErrH.Abort("XIQueue's size must be a power of 2",sz);
     buffer = new Node[size = sz];
     clear();
 }
References XErrorHandler::Abort(), BitSR(), and ErrH.
Member Function Documentation
clear()
template<class Type > void XIQueue< Type >::clear (void) inline
 {
     head = tail = 0;
 }
References head.
empty()
template<class Type > int XIQueue< Type >::empty inline
 {
     return head == tail;
 }
References head.
get()
template<class Type > Type XIQueue< Type >::get (void) inline
 {
     int ind;
     while(head != tail){
         ind = tail;
         tail = (tail + 1) & (size - 1);
         if(buffer[ind].ID != -1)
             return buffer[ind].data;
         }
     return (Type)0;
 }
References head.
put()
template<class Type > Type XIQueue< Type >::put (Type p, int ID) inline
 {
     int i = tail;
     Type prev_data = (Type)0;
     while(i != head){
         if(buffer[i].ID == ID){
             buffer[i].ID = -1;
             prev_data = buffer[i].p;
             break;
             }
         i = (i + 1) & (size - 1);
         }
     int new_head = (head + 1) & (size - 1);
     if(new_head != tail){
         buffer[head].ID = ID;
         buffer[head].data = p;
         head = new_head;
         return prev_data;
         }
     ErrH.Abort("XIQueue overflow");
     return (Type)0;
 }
References XErrorHandler::Abort(), ErrH, and head.
The documentation for this class was generated from the following file:
src/xcontainers.h