Vangers: XZIP_Resource Class Reference
XZIP_Resource Class Reference
#include <zip_resource.h>
Public Member Functions
int open (char *fname, XStream &fh)
void LoadHeaders (void)
void LoadIndex (void)
void SaveIndex (void)
void dump (char *fname)
XZIP_Resource (char *fname, int fl)
~XZIP_Resource (void)
Detailed Description
Constructor & Destructor Documentation
XZIP_Resource()
XZIP_Resource::XZIP_Resource (char * fname, int fl)
 {
     int sz;
     flags = fl;
     fileName = strdup(fname);
     idxName = strdup(fname);
     sz = strlen(fname);
     idxName[sz - 1] = 'x';
     idxName[sz - 2] = 'd';
     idxName[sz - 3] = 'i';
     file.open(fname,XS_IN);
     if(flags & XZIP_ENABLE_ZIP_HEADERS)
         LoadHeaders();
     else
         LoadIndex();
 }
References LoadHeaders(), LoadIndex(), XStream::open(), XS_IN, and XZIP_ENABLE_ZIP_HEADERS.
~XZIP_Resource()
XZIP_Resource::~XZIP_Resource (void)
 {
     XZIP_FileHeader* p;
     free(fileName);
     free(idxName);
     p = fileList.first();
     while(p){
         fileList.remove(p);
         delete p;
         p = fileList.first();
     }
 }
References xtList< Type >::first(), and xtList< Type >::remove().
Member Function Documentation
dump()
void XZIP_Resource::dump (char * fname)
 {
     XZIP_FileHeader* p = fileList.first();
     XStream fh(fname,XS_OUT);
     while(p){
         fh < p -> name() < " " <= p -> size() < "/" <= p -> offset() < "\r\n";
         p = p -> next;
     }
     fh.close();
 }
References xtList< Type >::first(), and XS_OUT.
LoadHeaders()
void XZIP_Resource::LoadHeaders (void)
 {
     int fl = 0;
     longint sig;
     char fname[512];
     XZIP_FileHeader* p;
     local_file_header lhdr;
     central_directory_file_header chdr;
     end_central_dir_record ecr;
     while(!fl){
         file > sig;
         switch(sig){
             case local_file_header_signature:
                 file > lhdr.version_needed_to_extract;
                 file > lhdr.general_purpose_bit_flag;
                 file > lhdr.compression_method;
                 file > lhdr.last_mod_file_time;
                 file > lhdr.last_mod_file_date;
                 file > lhdr.crc32;
                 file > lhdr.compressed_size;
                 file > lhdr.uncompressed_size;
                 file > lhdr.filename_length;
                 file > lhdr.extra_field_length;
                 file.read(fname,lhdr.filename_length);
                 fname[lhdr.filename_length] = 0;
                 file.seek(lhdr.extra_field_length,XS_CUR);
                 p = new XZIP_FileHeader(fname,file.tell(),lhdr.uncompressed_size,&lhdr,sizeof(local_file_header));
                 fileList.append(p);
                 file.seek(lhdr.compressed_size,XS_CUR);
                 break;
             case central_file_header_signature:
                 file > chdr.version_made_by;
                 file > chdr.version_needed_to_extract;
                 file > chdr.general_purpose_bit_flag;
                 file > chdr.compression_method;
                 file > chdr.last_mod_file_time;
                 file > chdr.last_mod_file_date;
                 file > chdr.crc32;
                 file > chdr.compressed_size;
                 file > chdr.uncompressed_size;
                 file > chdr.filename_length;
                 file > chdr.extra_field_length;
                 file > chdr.file_comment_length;
                 file > chdr.disk_number_start;
                 file > chdr.internal_file_attributes;
                 file > chdr.external_file_attributes;
                 file > chdr.relative_offset_local_header;
                 file.seek(chdr.filename_length,XS_CUR);
                 file.seek(chdr.extra_field_length,XS_CUR);
                 file.seek(chdr.file_comment_length,XS_CUR);
                 break;
             case end_central_dir_signature:
                 file > ecr.number_this_disk;
                 file > ecr.number_disk_with_start_central_directory;
                 file > ecr.total_entries_central_dir_on_this_disk;
                 file > ecr.total_entries_central_dir;
                 file > ecr.size_central_directory;
                 file > ecr.offset_start_central_directory;
                 file > ecr.zipfile_comment_length;
                 file.seek(ecr.zipfile_comment_length,XS_CUR);
                 fl = 1;
                 break;
         }
     }
     file.seek(0,XS_BEG);
 }
References xtList< Type >::append(), central_file_header_signature, local_file_header::compressed_size, central_directory_file_header::compressed_size, local_file_header::compression_method, central_directory_file_header::compression_method, local_file_header::crc32, central_directory_file_header::crc32, central_directory_file_header::disk_number_start, end_central_dir_signature, central_directory_file_header::external_file_attributes, local_file_header::extra_field_length, central_directory_file_header::extra_field_length, central_directory_file_header::file_comment_length, local_file_header::filename_length, central_directory_file_header::filename_length, local_file_header::general_purpose_bit_flag, central_directory_file_header::general_purpose_bit_flag, central_directory_file_header::internal_file_attributes, local_file_header::last_mod_file_date, central_directory_file_header::last_mod_file_date, local_file_header::last_mod_file_time, central_directory_file_header::last_mod_file_time, local_file_header_signature, end_central_dir_record::number_disk_with_start_central_directory, end_central_dir_record::number_this_disk, end_central_dir_record::offset_start_central_directory, XStream::read(), central_directory_file_header::relative_offset_local_header, XStream::seek(), end_central_dir_record::size_central_directory, XStream::tell(), end_central_dir_record::total_entries_central_dir, end_central_dir_record::total_entries_central_dir_on_this_disk, local_file_header::uncompressed_size, central_directory_file_header::uncompressed_size, central_directory_file_header::version_made_by, local_file_header::version_needed_to_extract, central_directory_file_header::version_needed_to_extract, XS_BEG, XS_CUR, and end_central_dir_record::zipfile_comment_length.
Referenced by XZIP_Resource().
LoadIndex()
void XZIP_Resource::LoadIndex (void)
 {
     int i,sz;
     XZIP_FileHeader* p;
     XStream fh(idxName,XS_IN);
     fh > sz;
     for(i = 0; i < sz; i ++){
         p = new XZIP_FileHeader(fh);
         fileList.append(p);
     }
     fh.close();
 }
References xtList< Type >::append(), XStream::close(), and XS_IN.
Referenced by XZIP_Resource().
open()
int XZIP_Resource::open (char * fname, XStream & fh)
 {
     XZIP_FileHeader* p = find(fname);
     if(p){
          fh.open(&file,p -> offset(),p -> size());
 //       fh.open(new XStream(fileName,XS_IN),p -> offset(),p -> size());
          return 1;
     }
     return 0;
 }
References XStream::open().
SaveIndex()
void XZIP_Resource::SaveIndex (void)
 {
     XZIP_FileHeader* p;
     XStream fh(idxName,XS_OUT);
     fh < fileList.size();
     p = fileList.first();
     while(p){
         p -> save(fh);
         p = p -> next;
     }
     fh.close();
 }
References xtList< Type >::first(), xtList< Type >::size(), and XS_OUT.
The documentation for this class was generated from the following files:
lib/xtool/zip_resource.h
lib/xtool/xresource/zip_resource.cpp