Vangers: Mat3d Class Reference
Mat3d Class Reference
#include <xmath.h>
Public Member Functions
Mat3d ()
xm_inline Mat3d (double xx, double xy, double xz, double yx, double yy, double yz, double zx, double zy, double zz)
Mat3d (double angle, eAxis axis)
Mat3d (const Vect3d &diag, const Vect3d &sym)
Mat3d (const Vect3d &axis, double angle, int normalizeAxis=1)
Mat3d (const QuatD &q)
Mat3d (const Vect3d &x_from, const Vect3d &y_from, const Vect3d &z_from, const Vect3d &x_to=Vect3d::I, const Vect3d &y_to=Vect3d::J, const Vect3d &z_to=Vect3d::K)
xm_inline operator Mat3f () const
xm_inline Mat3d & set (double angle, eAxis axis)
xm_inline Mat3d & set (const Vect3d &diag, const Vect3d &sym)
Mat3d & set (const Vect3d &axis, double angle, int normalizeAxis=1)
Mat3d & set (const QuatD &q)
Mat3d & set (const Vect3d &x_from, const Vect3d &y_from, const Vect3d &z_from, const Vect3d &x_to=Vect3d::I, const Vect3d &y_to=Vect3d::J, const Vect3d &z_to=Vect3d::K)
const Vect3d & operator[] (int i) const
Vect3d & operator[] (int i)
xm_inline Mat3d & setSkew (const Vect3d &v)
const Vect3d & xrow () const
const Vect3d & yrow () const
const Vect3d & zrow () const
Vect3d & xrow ()
Vect3d & yrow ()
Vect3d & zrow ()
Vect3d xcol () const
Vect3d ycol () const
Vect3d zcol () const
Vect3d col (int axis) const
xm_inline Mat3d & setXcol (const Vect3d &v)
xm_inline Mat3d & setYcol (const Vect3d &v)
xm_inline Mat3d & setZcol (const Vect3d &v)
Mat3d & setCol (int axis, const Vect3d &v)
Vect3d diag () const
Vect3d sym () const
const double & operator() (int i, int j) const
double & operator() (int i, int j)
xm_inline double det () const
xm_inline Mat3d operator- () const
xm_inline Mat3d & negate ()
xm_inline Mat3d & negate (const Mat3d &M)
xm_inline Mat3d & add (const Mat3d &M, const Mat3d &N)
xm_inline Mat3d & add (const Mat3d &M)
xm_inline Mat3d & sub (const Mat3d &M, const Mat3d &N)
xm_inline Mat3d & sub (const Mat3d &M)
Mat3d & operator+= (const Mat3d &M)
Mat3d & operator-= (const Mat3d &M)
Mat3d operator+ (const Mat3d &M) const
Mat3d operator- (const Mat3d &M) const
Mat3d & mult (const Mat3d &M, const Mat3d &N)
Mat3d & premult (const Mat3d &M)
Mat3d & postmult (const Mat3d &M)
Mat3d & operator*= (const Mat3d &M)
Mat3d operator* (const Mat3d &M) const
xm_inline Mat3d & scale (const Mat3d &M, double s)
xm_inline Mat3d & scale (double s)
Mat3d & operator*= (double s)
Mat3d & operator/= (double s)
Mat3d operator* (double s) const
Mat3d operator/ (double s) const
xm_inline Mat3d & preScale (const Mat3d &M, const Vect3d &v)
xm_inline Mat3d & preScale (const Vect3d &v)
xm_inline Mat3d & postScale (const Mat3d &M, const Vect3d &v)
xm_inline Mat3d & postScale (const Vect3d &v)
xm_inline Mat3d & xpose ()
xm_inline Mat3d & xpose (const Mat3d &M)
int invert ()
int invert (const Mat3d &M)
xm_inline Mat3d & symmetrize (const Mat3d &M)
xm_inline Mat3d & symmetrize ()
xm_inline Vect3d & xform (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & xform (Vect3d &v) const
xm_inline Vect3d & invXform (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & invXform (Vect3d &v) const
xm_inline Vect3f & xform (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & xform (Vect3f &v) const
xm_inline Vect3f & invXform (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & invXform (Vect3f &v) const
Static Public Attributes
static const Mat3d ZERO
static const Mat3d ID
Friends
class QuatD
class MatXd
Mat3d operator* (double s, const Mat3d &M)
Mat3d xpose (const Mat3d &M)
Mat3d invert (const Mat3d &M)
Vect3d & operator*= (Vect3d &v, const Mat3d &M)
Vect3d operator* (const Vect3d &v, const Mat3d &M)
Vect3d operator* (const Mat3d &M, const Vect3d &v)
Vect3f & operator*= (Vect3f &v, const Mat3d &M)
Vect3f operator* (const Vect3f &v, const Mat3d &M)
Vect3f operator* (const Mat3d &M, const Vect3f &v)
ostream & operator<< (ostream &os, const Mat3d &M)
istream & operator>> (istream &is, Mat3d &M)
XStream & operator<= (XStream &s, const Mat3d &M)
XStream & operator>= (XStream &s, Mat3d &M)
XStream & operator< (XStream &s, const Mat3d &M)
XStream & operator> (XStream &s, Mat3d &M)
XBuffer & operator<= (XBuffer &b, const Mat3d &M)
XBuffer & operator>= (XBuffer &b, Mat3d &M)
XBuffer & operator< (XBuffer &b, const Mat3d &M)
XBuffer & operator> (XBuffer &b, Mat3d &M)
Detailed Description
Constructor & Destructor Documentation
Mat3d() [1/7]
Mat3d::Mat3d () inline
 {}
Mat3d() [2/7]
Mat3d::Mat3d (double xx, double xy, double xz, double yx, double yy, double yz, double zx, double zy, double zz)
 {
     xx = xx_; xy = xy_; xz = xz_;
     yx = yx_; yy = yy_; yz = yz_;
     zx = zx_; zy = zy_; zz = zz_;
 }
Mat3d() [3/7]
Mat3d::Mat3d (double angle, eAxis axis) inline
 { set(angle, axis); }
References set().
Mat3d() [4/7]
Mat3d::Mat3d (const Vect3d & diag, const Vect3d & sym) inline
 {set(diag, sym);}
References diag(), set(), and sym().
Mat3d() [5/7]
Mat3d::Mat3d (const Vect3d & axis, double angle, int normalizeAxis = 1) inline
     {set(axis, angle, normalizeAxis);}
References set().
Mat3d() [6/7]
Mat3d::Mat3d (const QuatD & q) inline
 {set(q);}
References set().
Mat3d() [7/7]
Mat3d::Mat3d (const Vect3d & x_from, const Vect3d & y_from, const Vect3d & z_from, const Vect3d & x_to = Vect3d::I, const Vect3d & y_to = Vect3d::J, const Vect3d & z_to = Vect3d::K) inline
       { set(x_from, y_from, z_from, x_to, y_to, z_to); }
References set().
Member Function Documentation
add() [1/2]
Mat3d & Mat3d::add (const Mat3d & M)
 {
   xx += M.xx;
   xy += M.xy;
   xz += M.xz;
   yx += M.yx;
   yy += M.yy;
   yz += M.yz;
   zx += M.zx;
   zy += M.zy;
   zz += M.zz;
   return *this;
 }
add() [2/2]
Mat3d & Mat3d::add (const Mat3d & M, const Mat3d & N)
 {
   xx = M.xx + N.xx;
   xy = M.xy + N.xy;
   xz = M.xz + N.xz;
   yx = M.yx + N.yx;
   yy = M.yy + N.yy;
   yz = M.yz + N.yz;
   zx = M.zx + N.zx;
   zy = M.zy + N.zy;
   zz = M.zz + N.zz;
   return *this;
 }
Referenced by operator+(), and operator+=().
col()
Vect3d Mat3d::col (int axis) const inline
 { return axis == X_AXIS ? Vect3d(xx, yx, zx) : (axis == Y_AXIS ? Vect3d(xy, yy, zy) : Vect3d(xz, yz, zz) ); }
References X_AXIS, and Y_AXIS.
det()
double Mat3d::det () const
 {
   return  xx * (yy * zz - yz * zy)
     + xy * (yz * zx - yx * zz)
     + xz * (yx * zy - yy * zx);
 }
Referenced by invert().
diag()
Vect3d Mat3d::diag () const inline
 {return Vect3d(xx, yy, zz);}
Referenced by Mat3d(), and set().
invert() [1/2]
int Mat3d::invert ()
 {
   double D, oneOverDet;
   double oxy, oyz, ozx, oyx, ozy, oxz, oxx, oyy;
   if (fabs(D = det()) < 1.0e-12) return 1; // not invertible
   oneOverDet = 1 / D;
   oxx = xx; oyy = yy;
   oxy = xy; oyx = yx;
   oyz = yz; ozy = zy;
   ozx = zx; oxz = xz;
   xy = (oxz * ozy - zz * oxy) * oneOverDet;
   yz = (oxz * oyx - xx * oyz) * oneOverDet;
   zx = (oyx * ozy - yy * ozx) * oneOverDet;
   yx = (oyz * ozx - oyx * zz) * oneOverDet;
   zy = (oxy * ozx - ozy * xx) * oneOverDet;
   xz = (oxy * oyz - oxz * yy) * oneOverDet;
   xx = (oyy * zz - oyz * ozy) * oneOverDet;
   yy = (oxx * zz - oxz * ozx) * oneOverDet;
   zz = (oxx * oyy - oxy * oyx) * oneOverDet;
   return 0;
 }
References det().
Referenced by MatXd::Invert().
invert() [2/2]
int Mat3d::invert (const Mat3d & M)
 {
   double D, oneOverDet;
   if (fabs(D = M.det()) < 1.0e-12) return 1; // not invertible
   oneOverDet = 1 / D;
   xx = (M.yy * M.zz - M.yz * M.zy) * oneOverDet;
   xy = (M.xz * M.zy - M.xy * M.zz) * oneOverDet;
   xz = (M.xy * M.yz - M.xz * M.yy) * oneOverDet;
   yx = (M.yz * M.zx - M.yx * M.zz) * oneOverDet;
   yy = (M.xx * M.zz - M.xz * M.zx) * oneOverDet;
   yz = (M.xz * M.yx - M.xx * M.yz) * oneOverDet;
   zx = (M.yx * M.zy - M.yy * M.zx) * oneOverDet;
   zy = (M.xy * M.zx - M.xx * M.zy) * oneOverDet;
   zz = (M.xx * M.yy - M.xy * M.yx) * oneOverDet;
   return 0;
 }
References det().
invXform() [1/4]
Vect3d & Mat3d::invXform (const Vect3d & v, Vect3d & xv) const
 {
   xv.x = xx * v.x + yx * v.y + zx * v.z;
   xv.y = xy * v.x + yy * v.y + zy * v.z;
   xv.z = xz * v.x + yz * v.y + zz * v.z;
   return xv;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
Referenced by MatXd::invXformPoint(), and MatXd::invXformVect().
invXform() [2/4]
Vect3f & Mat3d::invXform (const Vect3f & v, Vect3f & xv) const
 {
   xv.x = (float)(xx * v.x + yx * v.y + zx * v.z);
   xv.y = (float)(xy * v.x + yy * v.y + zy * v.z);
   xv.z = (float)(xz * v.x + yz * v.y + zz * v.z);
   return xv;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
invXform() [3/4]
Vect3d & Mat3d::invXform (Vect3d & v) const
 {
   double ox, oy;
   ox = v.x; oy= v.y;
   v.x = xx * ox + yx * oy + zx * v.z;
   v.y = xy * ox + yy * oy + zy * v.z;
   v.z = xz * ox + yz * oy + zz * v.z;
   return v;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
invXform() [4/4]
Vect3f & Mat3d::invXform (Vect3f & v) const
 {
   float ox, oy;
   ox = v.x; oy= v.y;
   v.x = (float)(xx * ox + yx * oy + zx * v.z);
   v.y = (float)(xy * ox + yy * oy + zy * v.z);
   v.z = (float)(xz * ox + yz * oy + zz * v.z);
   return v;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
mult()
Mat3d & Mat3d::mult (const Mat3d & M, const Mat3d & N)
 {
   xx = M.xx * N.xx + M.xy * N.yx + M.xz * N.zx;
   xy = M.xx * N.xy + M.xy * N.yy + M.xz * N.zy;
   xz = M.xx * N.xz + M.xy * N.yz + M.xz * N.zz;
   yx = M.yx * N.xx + M.yy * N.yx + M.yz * N.zx;
   yy = M.yx * N.xy + M.yy * N.yy + M.yz * N.zy;
   yz = M.yx * N.xz + M.yy * N.yz + M.yz * N.zz;
   zx = M.zx * N.xx + M.zy * N.yx + M.zz * N.zx;
   zy = M.zx * N.xy + M.zy * N.yy + M.zz * N.zy;
   zz = M.zx * N.xz + M.zy * N.yz + M.zz * N.zz;
   return *this;
 }
Referenced by operator*().
negate() [1/2]
Mat3d & Mat3d::negate ()
 {
   xx = - xx;
   xy = - xy;
   xz = - xz;
   yx = - yx;
   yy = - yy;
   yz = - yz;
   zx = - zx;
   zy = - zy;
   zz = - zz;
   return *this;
 }
negate() [2/2]
Mat3d & Mat3d::negate (const Mat3d & M)
 {
   xx = - M.xx;
   xy = - M.xy;
   xz = - M.xz;
   yx = - M.yx;
   yy = - M.yy;
   yz = - M.yz;
   zx = - M.zx;
   zy = - M.zy;
   zz = - M.zz;
   return *this;
 }
operator Mat3f()
Mat3d::operator Mat3f () const
 {
     return Mat3f( (float)xx, (float)xy, (float)xz,
                 (float)yx, (float)yy, (float)yz,
                 (float)zx, (float)zy, (float)zz );
 }
operator()() [1/2]
double& Mat3d::operator() (int i, int j) inline
 { return (&xx)[(i - 1)*3 + j - 1]; }
operator()() [2/2]
const double& Mat3d::operator() (int i, int j) const inline
 { return (&xx)[(i - 1)*3 + j - 1]; }
operator*() [1/2]
Mat3d Mat3d::operator* (const Mat3d & M) const inline
 { Mat3d N; return N.mult(*this, M); }
References mult().
operator*() [2/2]
Mat3d Mat3d::operator* (double s) const inline
 { Mat3d N; return N.scale(*this, s); }
References scale().
operator*=() [1/2]
Mat3d& Mat3d::operator*= (const Mat3d & M) inline
 { return postmult(M); }
References postmult().
operator*=() [2/2]
Mat3d& Mat3d::operator*= (double s) inline
 { return scale(s); }
References scale().
operator+()
Mat3d Mat3d::operator+ (const Mat3d & M) const inline
 { Mat3d N; return N.add(*this,M); }
References add().
operator+=()
Mat3d& Mat3d::operator+= (const Mat3d & M) inline
 { return add(M); }
References add().
operator-() [1/2]
Mat3d Mat3d::operator- () const
 {
    Mat3d M;
    M.xx = - xx;
    M.xy = - xy;
    M.xz = - xz;
    M.yx = - yx;
    M.yy = - yy;
    M.yz = - yz;
    M.zx = - zx;
    M.zy = - zy;
    M.zz = - zz;
    return M;
 }
operator-() [2/2]
Mat3d Mat3d::operator- (const Mat3d & M) const inline
 { Mat3d N; return N.sub(*this,M); }
References sub().
operator-=()
Mat3d& Mat3d::operator-= (const Mat3d & M) inline
 { return sub(M); }
References sub().
operator/()
Mat3d Mat3d::operator/ (double s) const inline
 { Mat3d N; return N.scale(*this, 1/s); }
References scale().
operator/=()
Mat3d& Mat3d::operator/= (double s) inline
 { return scale(1/s); }
References scale().
operator[]() [1/2]
Vect3d& Mat3d::operator[] (int i) inline
 {return *(((Vect3d *) &xx) + i);}
operator[]() [2/2]
const Vect3d& Mat3d::operator[] (int i) const inline
 {return *(((Vect3d *) &xx) + i);}
postmult()
Mat3d & Mat3d::postmult (const Mat3d & M)
 {
   double oxy, oyz, ozx, oyx, ozy, oxz;
   oxy = xy; oyx = yx; oyz = yz; ozy = zy; ozx = zx; oxz = xz;
   xy = xx *  M.xy + oxy * M.yy + oxz * M.zy;
   xz = xx *  M.xz + oxy * M.yz + oxz * M.zz;
   yx = oyx * M.xx + yy  * M.yx + oyz * M.zx;
   yz = oyx * M.xz + yy  * M.yz + oyz * M.zz;
   zx = ozx * M.xx + ozy * M.yx + zz  * M.zx;
   zy = ozx * M.xy + ozy * M.yy + zz  * M.zy;
   xx = xx  * M.xx + oxy * M.yx + oxz * M.zx;
   yy = oyx * M.xy + yy  * M.yy + oyz * M.zy;
   zz = ozx * M.xz + ozy * M.yz + zz  * M.zz;
   return *this;
 }
Referenced by operator*=().
postScale() [1/2]
Mat3d & Mat3d::postScale (const Mat3d & M, const Vect3d & v)
 {   // M * Mat3d(v)
     xx = M.xx*v.x;
     xy = M.xy*v.y;
     xz = M.xz*v.z;
     yx = M.yx*v.x;
     yy = M.yy*v.y;
     yz = M.yz*v.z;
     zx = M.zx*v.x;
     zy = M.zy*v.y;
     zz = M.zz*v.z;
     return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
postScale() [2/2]
Mat3d & Mat3d::postScale (const Vect3d & v)
 {   // this * Mat3d(v)
     xx *= v.x;
     xy *= v.y;
     xz *= v.z;
     yx *= v.x;
     yy *= v.y;
     yz *= v.z;
     zx *= v.x;
     zy *= v.y;
     zz *= v.z;
     return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
premult()
Mat3d & Mat3d::premult (const Mat3d & M)
 {
   double oxy, oyz, ozx, oyx, ozy, oxz;
   oxy = xy; oyx = yx; oyz = yz; ozy = zy; ozx = zx; oxz = xz;
   xy = M.xx * oxy + M.xy * yy  + M.xz * ozy;
   xz = M.xx * oxz + M.xy * oyz + M.xz * zz;
   yx = M.yx * xx  + M.yy * oyx + M.yz * ozx;
   yz = M.yx * oxz + M.yy * oyz + M.yz * zz;
   zx = M.zx * xx  + M.zy * oyx + M.zz * ozx;
   zy = M.zx * oxy + M.zy * yy  + M.zz * ozy;
   xx = M.xx * xx  + M.xy * oyx + M.xz * ozx;
   yy = M.yx * oxy + M.yy * yy  + M.yz * ozy;
   zz = M.zx * oxz + M.zy * oyz + M.zz * zz;
   return *this;
 }
preScale() [1/2]
Mat3d & Mat3d::preScale (const Mat3d & M, const Vect3d & v)
 {   // Mat3d(v) * M
     xx = M.xx*v.x;
     xy = M.xy*v.x;
     xz = M.xz*v.x;
     yx = M.yx*v.y;
     yy = M.yy*v.y;
     yz = M.yz*v.y;
     zx = M.zx*v.z;
     zy = M.zy*v.z;
     zz = M.zz*v.z;
     return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
preScale() [2/2]
Mat3d & Mat3d::preScale (const Vect3d & v)
 {   // Mat3d(s) * this
     xx *= v.x;
     xy *= v.x;
     xz *= v.x;
     yx *= v.y;
     yy *= v.y;
     yz *= v.y;
     zx *= v.z;
     zy *= v.z;
     zz *= v.z;
     return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
scale() [1/2]
Mat3d & Mat3d::scale (const Mat3d & M, double s)
 {
   xx = s * M.xx;
   xy = s * M.xy;
   xz = s * M.xz;
   yx = s * M.yx;
   yy = s * M.yy;
   yz = s * M.yz;
   zx = s * M.zx;
   zy = s * M.zy;
   zz = s * M.zz;
   return *this;
 }
Referenced by operator*(), operator*=(), operator/(), and operator/=().
scale() [2/2]
Mat3d & Mat3d::scale (double s)
 {
   xx *= s;
   xy *= s;
   xz *= s;
   yx *= s;
   yy *= s;
   yz *= s;
   zx *= s;
   zy *= s;
   zz *= s;
   return *this;
 }
set() [1/5]
Mat3d & Mat3d::set (const QuatD & q)
 {
   xx = 2.0 * (q.s_ * q.s_ + q.x_ * q.x_ - 0.5);
   yy = 2.0 * (q.s_ * q.s_ + q.y_ * q.y_ - 0.5);
   zz = 2.0 * (q.s_ * q.s_ + q.z_ * q.z_ - 0.5);
   xy = 2.0 * (q.y_ * q.x_ - q.z_ * q.s_);
   yx = 2.0 * (q.x_ * q.y_ + q.z_ * q.s_);
   yz = 2.0 * (q.z_ * q.y_ - q.x_ * q.s_);
   zy = 2.0 * (q.y_ * q.z_ + q.x_ * q.s_);
   zx = 2.0 * (q.x_ * q.z_ - q.y_ * q.s_);
   xz = 2.0 * (q.z_ * q.x_ + q.y_ * q.s_);
   return *this;
 }
set() [2/5]
Mat3d & Mat3d::set (const Vect3d & axis, double angle, int normalizeAxis = 1)
 {
   QuatD q;
   q.set(angle, axis, normalizeAxis);
   set(q);
   return *this;
 }
References set(), and QuatD::set().
set() [3/5]
Mat3d & Mat3d::set (const Vect3d & diag, const Vect3d & sym)
 {
   xx = diag.x;
   yy = diag.y;
   zz = diag.z;
   yz = zy = sym.x;
   zx = xz = sym.y;
   xy = yx = sym.z;
   return *this;
 }
References diag(), sym(), Vect3d::x, Vect3d::y, and Vect3d::z.
set() [4/5]
Mat3d & Mat3d::set (const Vect3d & x_from, const Vect3d & y_from, const Vect3d & z_from, const Vect3d & x_to = Vect3d::I, const Vect3d & y_to = Vect3d::J, const Vect3d & z_to = Vect3d::K)
 {
     xx = dot(x_from, x_to);
     xy = dot(y_from, x_to);
     xz = dot(z_from, x_to);
     yx = dot(x_from, y_to);
     yy = dot(y_from, y_to);
     yz = dot(z_from, y_to);
     zx = dot(x_from, z_to);
     zy = dot(y_from, z_to);
     zz = dot(z_from, z_to);
     return *this;
 }
References dot().
set() [5/5]
Mat3d & Mat3d::set (double angle, eAxis axis)
 {
 //  ------ Calculate Matrix for ROTATE point an angle ------
     double calpha = cos(angle);
     double salpha = sin(angle);
     switch(axis){
         case Z_AXIS:
             xx   =  calpha; xy   = -salpha; xz   = 0;
             yx   =  salpha; yy   = calpha;  yz   = 0;
             zx   = 0;     zy     = 0;       zz   = 1;
             break;
         case X_AXIS:
             xx   =  1;    xy     =  0;      xz   = 0;
             yx   =  0;    yy     =  calpha; yz   = -salpha;
             zx   =  0;    zy     =  salpha; zz   = calpha;
             break;
         case Y_AXIS:
             xx   = calpha;  xy   =  0;      xz   = salpha;
             yx   = 0;     yy     =  1;      yz   = 0;
             zx   = -salpha; zy   =  0;      zz   = calpha;
             break;
         case W_AXIS:
             break;
         }
     return *this;
 }
References W_AXIS, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by Mat3d(), MatXd::set(), and set().
setCol()
Mat3d& Mat3d::setCol (int axis, const Vect3d & v) inline
 { if(axis == X_AXIS) setXcol(v); else if(axis == Y_AXIS) setYcol(v); else setZcol(v); return *this; }
References setXcol(), setYcol(), setZcol(), X_AXIS, and Y_AXIS.
setSkew()
Mat3d & Mat3d::setSkew (const Vect3d & v)
 {
   xx = yy = zz = 0.0;
   zy =  v.x;
   yz = -v.x;
   xz =  v.y;
   zx = -v.y;
   yx =  v.z;
   xy = -v.z;
   return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
setXcol()
Mat3d & Mat3d::setXcol (const Vect3d & v)
 {
   xx = v.x;
   yx = v.y;
   zx = v.z;
   return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
Referenced by setCol().
setYcol()
Mat3d & Mat3d::setYcol (const Vect3d & v)
 {
   xy = v.x;
   yy = v.y;
   zy = v.z;
   return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
Referenced by setCol().
setZcol()
Mat3d & Mat3d::setZcol (const Vect3d & v)
 {
   xz = v.x;
   yz = v.y;
   zz = v.z;
   return *this;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
Referenced by setCol().
sub() [1/2]
Mat3d & Mat3d::sub (const Mat3d & M)
 {
   xx -= M.xx;
   xy -= M.xy;
   xz -= M.xz;
   yx -= M.yx;
   yy -= M.yy;
   yz -= M.yz;
   zx -= M.zx;
   zy -= M.zy;
   zz -= M.zz;
   return *this;
 }
sub() [2/2]
Mat3d & Mat3d::sub (const Mat3d & M, const Mat3d & N)
 {
   xx = M.xx - N.xx;
   xy = M.xy - N.xy;
   xz = M.xz - N.xz;
   yx = M.yx - N.yx;
   yy = M.yy - N.yy;
   yz = M.yz - N.yz;
   zx = M.zx - N.zx;
   zy = M.zy - N.zy;
   zz = M.zz - N.zz;
   return *this;
 }
Referenced by operator-(), and operator-=().
sym()
Vect3d Mat3d::sym () const inline
 {return Vect3d(yz, zx, xy);}
Referenced by Mat3d(), and set().
symmetrize() [1/2]
Mat3d & Mat3d::symmetrize ()
 {
   xx = 2 * xx;
   yy = 2 * yy;
   zz = 2 * zz;
   xy = yx = xy + yx;
   yz = zy = yz + zy;
   zx = xz = zx + xz;
   return *this;
 }
symmetrize() [2/2]
Mat3d & Mat3d::symmetrize (const Mat3d & M)
 {
   xx = 2 * M.xx;
   yy = 2 * M.yy;
   zz = 2 * M.zz;
   xy = yx = M.xy + M.yx;
   yz = zy = M.yz + M.zy;
   zx = xz = M.zx + M.xz;
   return *this;
 }
xcol()
Vect3d Mat3d::xcol () const inline
 {return Vect3d(xx, yx, zx);}
xform() [1/4]
Vect3d & Mat3d::xform (const Vect3d & v, Vect3d & xv) const
 {
   xv.x = xx * v.x + xy * v.y + xz * v.z;
   xv.y = yx * v.x + yy * v.y + yz * v.z;
   xv.z = zx * v.x + zy * v.y + zz * v.z;
   return xv;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
Referenced by MatXd::Invert(), MatXd::xformPoint(), and MatXd::xformVect().
xform() [2/4]
Vect3f & Mat3d::xform (const Vect3f & v, Vect3f & xv) const
 {
   xv.x = (float)(xx * v.x + xy * v.y + xz * v.z);
   xv.y = (float)(yx * v.x + yy * v.y + yz * v.z);
   xv.z = (float)(zx * v.x + zy * v.y + zz * v.z);
   return xv;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
xform() [3/4]
Vect3d & Mat3d::xform (Vect3d & v) const
 {
   double ox, oy;
   ox = v.x; oy= v.y;
   v.x = xx * ox + xy * oy + xz * v.z;
   v.y = yx * ox + yy * oy + yz * v.z;
   v.z = zx * ox + zy * oy + zz * v.z;
   return v;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
xform() [4/4]
Vect3f & Mat3d::xform (Vect3f & v) const
 {
   float ox, oy;
   ox = v.x; oy= v.y;
   v.x = (float)(xx * ox + xy * oy + xz * v.z);
   v.y = (float)(yx * ox + yy * oy + yz * v.z);
   v.z = (float)(zx * ox + zy * oy + zz * v.z);
   return v;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
xpose() [1/2]
Mat3d & Mat3d::xpose ()
 {
   double tmp;
   tmp = xy;
   xy = yx;
   yx = tmp;
   tmp = yz;
   yz = zy;
   zy = tmp;
   tmp = zx;
   zx = xz;
   xz = tmp;
   return *this;
 }
xpose() [2/2]
Mat3d & Mat3d::xpose (const Mat3d & M)
 {
   xx = M.xx;
   xy = M.yx;
   xz = M.zx;
   yx = M.xy;
   yy = M.yy;
   yz = M.zy;
   zx = M.xz;
   zy = M.yz;
   zz = M.zz;
   return *this;
 }
xrow() [1/2]
Vect3d& Mat3d::xrow () inline
 {return *((Vect3d *) &xx);}
xrow() [2/2]
const Vect3d& Mat3d::xrow () const inline
 {return *((Vect3d *) &xx);}
ycol()
Vect3d Mat3d::ycol () const inline
 {return Vect3d(xy, yy, zy);}
yrow() [1/2]
Vect3d& Mat3d::yrow () inline
 {return *((Vect3d *) &yx);}
yrow() [2/2]
const Vect3d& Mat3d::yrow () const inline
 {return *((Vect3d *) &yx);}
zcol()
Vect3d Mat3d::zcol () const inline
 {return Vect3d(xz, yz, zz);}
zrow() [1/2]
Vect3d& Mat3d::zrow () inline
 {return *((Vect3d *) &zx);}
zrow() [2/2]
const Vect3d& Mat3d::zrow () const inline
 {return *((Vect3d *) &zx);}
Friends And Related Function Documentation
invert
Mat3d invert (const Mat3d & M) friend
 { Mat3d N; N.invert(M); return N; }
MatXd
friend class MatXd friend
operator* [1/5]
Vect3d operator* (const Mat3d & M, const Vect3d & v) friend
 { Vect3d xv; return M.xform(v, xv); }
operator* [2/5]
Vect3f operator* (const Mat3d & M, const Vect3f & v) friend
 { Vect3f xv; return M.xform(v, xv); }
operator* [3/5]
Vect3d operator* (const Vect3d & v, const Mat3d & M) friend
 { Vect3d xv; return M.xform(v, xv); }
operator* [4/5]
Vect3f operator* (const Vect3f & v, const Mat3d & M) friend
 { Vect3f xv; return M.xform(v, xv); }
operator* [5/5]
Mat3d operator* (double s, const Mat3d & M) friend
 { Mat3d N; return N.scale(M, s); }
operator*= [1/2]
Vect3d& operator*= (Vect3d & v, const Mat3d & M) friend
 { return M.xform(v); }
operator*= [2/2]
Vect3f& operator*= (Vect3f & v, const Mat3d & M) friend
 { return M.xform(v); }
operator< [1/2]
XBuffer& operator< (XBuffer & b, const Mat3d & M) friend
 {
     b < m.xx < m.xy < m.xz;
     b < m.yx < m.yy < m.yz;
     b < m.zx < m.zy < m.zz;
     return b;
 }
operator< [2/2]
XStream& operator< (XStream & s, const Mat3d & M) friend
 {
     s.write(&m,sizeof(Mat3d));
     return s;
 }
operator<<
ostream& operator<< (ostream & os, const Mat3d & M) friend
 {
   os << m.xx << " \t" << m.xy << " \t" << m.xz << endl;
   os << m.yx << " \t" << m.yy << " \t" << m.yz << endl;
   os << m.zx << " \t" << m.zy << " \t" << m.zz;
   return os;
 }
operator<= [1/2]
XBuffer& operator<= (XBuffer & b, const Mat3d & M) friend
 {
     b <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     b <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     b <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return b;
 }
operator<= [2/2]
XStream& operator<= (XStream & s, const Mat3d & M) friend
 {
     s <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     s <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     s <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return s;
 }
operator> [1/2]
XBuffer& operator> (XBuffer & b, Mat3d & M) friend
 {
     b > m.xx > m.xy > m.xz;
     b > m.yx > m.yy > m.yz;
     b > m.zx > m.zy > m.zz;
     return b;
 }
operator> [2/2]
XStream& operator> (XStream & s, Mat3d & M) friend
 {
     s.read(&m,sizeof(Mat3d));
     return s;
 }
operator>= [1/2]
XBuffer& operator>= (XBuffer & b, Mat3d & M) friend
 {
     b >= m.xx >= m.xy >= m.xz;
     b >= m.yx >= m.yy >= m.yz;
     b >= m.zx >= m.zy >= m.zz;
     return b;
 }
operator>= [2/2]
XStream& operator>= (XStream & s, Mat3d & M) friend
 {
     s >= m.xx >= m.xy >= m.xz;
     s >= m.yx >= m.yy >= m.yz;
     s >= m.zx >= m.zy >= m.zz;
     return s;
 }
operator>>
istream& operator>> (istream & is, Mat3d & M) friend
 {
   is >> m.xx >> m.xy >> m.xz;
   is >> m.yx >> m.yy >> m.yz;
   is >> m.zx >> m.zy >> m.zz;
   return is;
 }
QuatD
friend class QuatD friend
xpose
Mat3d xpose (const Mat3d & M) friend
 { Mat3d N; return N.xpose(M); }
Member Data Documentation
ID
const Mat3d Mat3d::ID static
ZERO
const Mat3d Mat3d::ZERO static
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp