Vangers: Se3d Class Reference
Se3d Class Reference
#include <xmath.h>
Public Member Functions
Se3d ()
Se3d (const QuatD &q_, const Vect3d &d_)
Se3d (const MatXd &X)
xm_inline operator Se3f () const
Se3d & set (const QuatD &q_, const Vect3d &d_)
Se3d & set (const MatXd &X)
const QuatD & rot () const
const Vect3d & trans () const
QuatD & rot ()
Vect3d & trans ()
xm_inline Se3d & mult (const Se3d &T, const Se3d &U)
xm_inline Se3d & premult (const Se3d &T)
xm_inline Se3d & postmult (const Se3d &T)
Se3d & operator*= (const Se3d &T)
Se3d operator* (const Se3d &U) const
xm_inline Se3d & invert (const Se3d &T)
xm_inline Se3d & invert ()
xm_inline Vect3d & xformVect (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & xformVect (Vect3d &v) const
xm_inline Vect3d & xformPoint (const Vect3d &p, Vect3d &xp) const
xm_inline Vect3d & xformPoint (Vect3d &p) const
xm_inline Vect3d & invXformVect (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & invXformVect (Vect3d &v) const
xm_inline Vect3d & invXformPoint (const Vect3d &p, Vect3d &xp) const
xm_inline Vect3d & invXformPoint (Vect3d &p) const
Static Public Attributes
static const Se3d ID
Friends
ostream & operator<< (ostream &os, const Se3d &se3)
istream & operator>> (istream &is, Se3d &se3)
Detailed Description
Constructor & Destructor Documentation
Se3d() [1/3]
Se3d::Se3d () inline
 {}
Se3d() [2/3]
Se3d::Se3d (const QuatD & q_, const Vect3d & d_) inline
 { set(q_, d_); }
References set().
Se3d() [3/3]
Se3d::Se3d (const MatXd & X) inline
 { set(X); }
References set().
Member Function Documentation
invert() [1/2]
Se3d & Se3d::invert ()
 {
   q.s_ = -q.s_;
   q.xform(d);
   d.negate();
   return *this;
 }
References Vect3d::negate(), and QuatD::xform().
invert() [2/2]
Se3d & Se3d::invert (const Se3d & T)
 {
   q.s_ = -T.q.s_;
   q.x_ =  T.q.x_;
   q.y_ =  T.q.y_;
   q.z_ =  T.q.z_;
   q.xform(T.d, d);
   d.negate(d);
   return *this;
 }
References Vect3d::negate(), and QuatD::xform().
invXformPoint() [1/2]
Vect3d & Se3d::invXformPoint (const Vect3d & p, Vect3d & xp) const
 {
   xp.sub(p, d);
   q.invXform(xp);
   return xp;
 }
References QuatD::invXform(), and Vect3d::sub().
invXformPoint() [2/2]
Vect3d & Se3d::invXformPoint (Vect3d & p) const
 {
   p.sub(d);
   q.invXform(p);
   return p;
 }
References QuatD::invXform(), and Vect3d::sub().
invXformVect() [1/2]
Vect3d & Se3d::invXformVect (const Vect3d & v, Vect3d & xv) const
 {
   q.invXform(v, xv);
   return xv;
 }
References QuatD::invXform().
invXformVect() [2/2]
Vect3d & Se3d::invXformVect (Vect3d & v) const
 {
   q.invXform(v);
   return v;
 }
References QuatD::invXform().
mult()
Se3d & Se3d::mult (const Se3d & T, const Se3d & U)
 {
   q.mult(T.q, U.q);
   T.q.xform(U.d, d);
   d.add(d, T.d);
   return *this;
 }
References Vect3d::add(), QuatD::mult(), and QuatD::xform().
Referenced by operator*().
operator Se3f()
Se3d::operator Se3f () const
 {
     return Se3f(q, d);
 }
operator*()
Se3d Se3d::operator* (const Se3d & U) const inline
 { Se3d T; return T.mult(*this, U); }
References mult().
operator*=()
Se3d& Se3d::operator*= (const Se3d & T) inline
 { return postmult(T); }
References postmult().
postmult()
Se3d & Se3d::postmult (const Se3d & T)
 {
   Vect3d v;
   q.xform(T.d, v);
   d.add(v);
   q.postmult(T.q);
   return *this;
 }
References Vect3d::add(), QuatD::postmult(), and QuatD::xform().
Referenced by operator*=().
premult()
Se3d & Se3d::premult (const Se3d & T)
 {
   q.premult(T.q);
   T.q.xform(d);
   d.add(T.d);
   return *this;
 }
References Vect3d::add(), QuatD::premult(), and QuatD::xform().
rot() [1/2]
QuatD& Se3d::rot () inline
 {return q;}
rot() [2/2]
const QuatD& Se3d::rot () const inline
 {return q;}
Referenced by MatXd::set().
set() [1/2]
Se3d& Se3d::set (const MatXd & X) inline
 { q.set(X.rot()); d = X.trans(); return *this; }
References MatXd::rot(), QuatD::set(), and MatXd::trans().
set() [2/2]
Se3d& Se3d::set (const QuatD & q_, const Vect3d & d_) inline
 { q = q_; d = d_; return *this; }
Referenced by Se3d().
trans() [1/2]
Vect3d& Se3d::trans () inline
 {return d;}
trans() [2/2]
const Vect3d& Se3d::trans () const inline
 {return d;}
Referenced by MatXd::set().
xformPoint() [1/2]
Vect3d & Se3d::xformPoint (const Vect3d & p, Vect3d & xp) const
 {
   q.xform(p, xp);
   xp.add(d);
   return xp;
 }
References Vect3d::add(), and QuatD::xform().
xformPoint() [2/2]
Vect3d & Se3d::xformPoint (Vect3d & p) const
 {
   q.xform(p);
   p.add(d);
   return p;
 }
References Vect3d::add(), and QuatD::xform().
xformVect() [1/2]
Vect3d & Se3d::xformVect (const Vect3d & v, Vect3d & xv) const
 {
   q.xform(v, xv);
   return xv;
 }
References QuatD::xform().
xformVect() [2/2]
Vect3d & Se3d::xformVect (Vect3d & v) const
 {
   q.xform(v);
   return v;
 }
References QuatD::xform().
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & os, const Se3d & se3) friend
 {
   return os << se3.q << se3.d;
 }
operator>>
istream& operator>> (istream & is, Se3d & se3) friend
 {
     return is >> se3.q >> se3.d;
 }
Member Data Documentation
ID
const Se3d Se3d::ID static
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp