Vangers: XSocket Class Reference
XSocket Class Reference
#include <xsocket.h>
Public Member Functions
XSocket ()
~XSocket ()
XSocket (XSocket &donor)
XSocket & operator= (XSocket &donor)
int open (int IP, int port)
int open (char *name, int port)
void close ()
int listen (int port)
XSocket accept ()
int send (const char *buffer, int size)
int receive (char *buffer, int size_of_buffer, int ms_time=0)
int operator! ()
int operator() ()
Public Attributes
IPaddress addr
Detailed Description
Constructor & Destructor Documentation
XSocket() [1/2]
XSocket::XSocket ()
                  {
     tcpSock = NULL;
     ErrHUsed = 1;
     addr.host = 0;
     addr.port = 0;
     socketSet = NULL;
 }
References addr, and NULL.
~XSocket()
XSocket::~XSocket ()
                   {
     if (tcpSock != NULL)
         close();
 }
References close(), and NULL.
XSocket() [2/2]
XSocket::XSocket (XSocket & donor)
{
     tcpSock = donor.tcpSock;
     ErrHUsed = donor.ErrHUsed;
     addr = donor.addr;
     donor.tcpSock = NULL;
     socketSet = NULL;
 }
References addr, and NULL.
Member Function Documentation
accept()
XSocket XSocket::accept (void)
{
     XSocket xsock;
     TCPsocket newSock;
     newSock = SDLNet_TCP_Accept(tcpSock);
     if (!newSock) // TODO: Should emit error here
         return xsock;
     xsock.tcpSock = newSock;
     xsock.ErrHUsed = ErrHUsed;
     xsock.addr.port = addr.port;
     xsock.socketSet = SDLNet_AllocSocketSet(16);
     SDLNet_TCP_AddSocket(xsock.socketSet, newSock);
     return xsock;
 }
References addr.
Referenced by Server::check_new_clients().
close()
void XSocket::close (void)
                     {
     if (tcpSock) {
         SDLNet_TCP_Close(tcpSock);
         tcpSock = NULL;
     }
     if (socketSet) {
         SDLNet_FreeSocketSet(socketSet);
         socketSet = NULL;
     }
     addr.host = 0;
     addr.port = 0;
 }
References addr, and NULL.
Referenced by disconnect_from_server(), identification(), Player::receive(), receive(), and ~XSocket().
listen()
int XSocket::listen (int port)
{
     addr.host = INADDR_ANY;
     addr.port = htons(port);
     tcpSock = SDLNet_TCP_Open(&addr);
     if (tcpSock == NULL) {
         XSOCKET_ERROR("TCP listen failed", SDLNet_GetError());
         return 0;
     }
     return 1;
 }
References addr, NULL, and XSOCKET_ERROR.
Referenced by Server::Server().
open() [1/2]
int XSocket::open (char * name, int port)
{
     if (!name)
         ErrH.Abort("NULL inet_addr() argument...");
     if (SDLNet_ResolveHost(&addr, name, port) == -1) {
         XSOCKET_ERROR("TCP socket hostname resolution failed", SDLNet_GetError());
         return 0;
     }
     return tcp_open();
 }
References XErrorHandler::Abort(), addr, ErrH, and XSOCKET_ERROR.
open() [2/2]
int XSocket::open (int IP, int port)
{
     addr.host = htonl(IP);
     addr.port = htons(port);
     return tcp_open();
 }
References addr.
Referenced by ServerFindChain::connect(), and ServersList::talk_to_server().
operator!()
int XSocket::operator! () inline
 { return tcpSock == NULL; }
References NULL.
operator()()
int XSocket::operator() () inline
 { return tcpSock != NULL; }
References NULL.
operator=()
XSocket & XSocket::operator= (XSocket & donor)
{
     tcpSock = donor.tcpSock;
     ErrHUsed = donor.ErrHUsed;
     addr = donor.addr;
     socketSet = donor.socketSet;
     donor.tcpSock = NULL;
     donor.socketSet = NULL;
     return *this;
 }
References addr, and NULL.
receive()
int XSocket::receive (char * buffer, int size_of_buffer, int ms_time = 0)
{
     if (ms_time == 0) {
         int n;
         n = SDLNet_CheckSockets(socketSet, 0);
         if (n == -1) {
             printf("SDLNet_CheckSockets: %s\n", SDLNet_GetError());
             // most of the time this is a system error, where perror might help you.
             perror("SDLNet_CheckSockets");
         } else if (n == 0) {
             return 0;
         }
         if (!SDLNet_SocketReady(tcpSock)) {
             return 0;
         }
     }
     if (!tcpSock)
         return 0;
     int status = SDLNet_TCP_Recv(tcpSock, buffer, size_of_buffer);
     if (status <= 0) {
         close();
         return 0;
     }
     return status;
 }
References close().
Referenced by Player::identification(), identification(), InputEventBuffer::receive(), and ServersList::talk_to_server().
send()
int XSocket::send (const char * buffer, int size)
{
     if (!tcpSock)
         return 0;
     int status = SDLNet_TCP_Send(tcpSock, buffer, size);
     if (status < size) {
         XSOCKET_ERROR("TCP send failed", SDLNet_GetError()); // TODO: close socket?
         return 0;
     }
     return status;
 }
References XSOCKET_ERROR.
Referenced by Player::identification(), identification(), Player::is_alive(), OutputEventBuffer::send(), and ServersList::talk_to_server().
Member Data Documentation
addr
IPaddress XSocket::addr
Referenced by accept(), close(), listen(), open(), operator=(), and XSocket().
The documentation for this class was generated from the following files:
src/xsocket.h
src/xsocket.cpp