Vangers: Mat3f Class Reference
Mat3f Class Reference
#include <xmath.h>
Public Member Functions
Mat3f ()
xm_inline Mat3f (float xx, float xy, float xz, float yx, float yy, float yz, float zx, float zy, float zz)
Mat3f (float angle, eAxis axis)
Mat3f (const Vect3f &diag, const Vect3f &sym)
Mat3f (const Vect3f &axis, float angle, int normalizeAxis=1)
Mat3f (const QuatF &q)
Mat3f (const Vect3f &x_from, const Vect3f &y_from, const Vect3f &z_from, const Vect3f &x_to=Vect3f::I, const Vect3f &y_to=Vect3f::J, const Vect3f &z_to=Vect3f::K)
xm_inline operator Mat3d () const
xm_inline Mat3f & set (float angle, eAxis axis)
xm_inline Mat3f & set (const Vect3f &diag, const Vect3f &sym)
Mat3f & set (const Vect3f &axis, float angle, int normalizeAxis=1)
Mat3f & set (const QuatF &q)
Mat3f & set (const Vect3f &x_from, const Vect3f &y_from, const Vect3f &z_from, const Vect3f &x_to=Vect3f::I, const Vect3f &y_to=Vect3f::J, const Vect3f &z_to=Vect3f::K)
xm_inline const Vect3f & operator[] (int i) const
xm_inline Vect3f & operator[] (int i)
xm_inline Mat3f & setSkew (const Vect3f &v)
xm_inline const Vect3f & xrow () const
xm_inline const Vect3f & yrow () const
xm_inline const Vect3f & zrow () const
xm_inline Vect3f & xrow ()
xm_inline Vect3f & yrow ()
xm_inline Vect3f & zrow ()
xm_inline Vect3f xcol () const
xm_inline Vect3f ycol () const
xm_inline Vect3f zcol () const
xm_inline Vect3f col (int axis) const
xm_inline Mat3f & setXcol (const Vect3f &v)
xm_inline Mat3f & setYcol (const Vect3f &v)
xm_inline Mat3f & setZcol (const Vect3f &v)
xm_inline Mat3f & setCol (int axis, const Vect3f &v)
xm_inline Vect3f diag () const
xm_inline Vect3f sym () const
xm_inline const float & operator() (int i, int j) const
xm_inline float & operator() (int i, int j)
xm_inline float det () const
xm_inline Mat3f operator- () const
xm_inline Mat3f & negate ()
xm_inline Mat3f & negate (const Mat3f &M)
xm_inline Mat3f & add (const Mat3f &M, const Mat3f &N)
xm_inline Mat3f & add (const Mat3f &M)
xm_inline Mat3f & sub (const Mat3f &M, const Mat3f &N)
xm_inline Mat3f & sub (const Mat3f &M)
xm_inline Mat3f & operator+= (const Mat3f &M)
xm_inline Mat3f & operator-= (const Mat3f &M)
xm_inline Mat3f operator+ (const Mat3f &M) const
xm_inline Mat3f operator- (const Mat3f &M) const
Mat3f & mult (const Mat3f &M, const Mat3f &N)
Mat3f & premult (const Mat3f &M)
Mat3f & postmult (const Mat3f &M)
xm_inline Mat3f & operator*= (const Mat3f &M)
xm_inline Mat3f operator* (const Mat3f &M) const
xm_inline Mat3f & scale (const Mat3f &M, float s)
xm_inline Mat3f & scale (const Vect3f &s)
xm_inline Mat3f & scale (float s)
xm_inline Mat3f & operator*= (float s)
xm_inline Mat3f & operator/= (float s)
xm_inline Mat3f operator* (float s) const
xm_inline Mat3f operator/ (float s) const
xm_inline Mat3f & preScale (const Mat3f &M, const Vect3f &v)
xm_inline Mat3f & preScale (const Vect3f &v)
xm_inline Mat3f & postScale (const Mat3f &M, const Vect3f &v)
xm_inline Mat3f & postScale (const Vect3f &v)
xm_inline Mat3f & xpose ()
xm_inline Mat3f & xpose (const Mat3f &M)
int invert ()
int invert (const Mat3f &M)
xm_inline Mat3f & symmetrize (const Mat3f &M)
xm_inline Mat3f & symmetrize ()
xm_inline Vect3d & xform (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & xform (Vect3d &v) const
xm_inline Vect3d & invXform (const Vect3d &v, Vect3d &xv) const
xm_inline Vect3d & invXform (Vect3d &v) const
xm_inline Vect3f & xform (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & xform (Vect3f &v) const
xm_inline Vect3f & invXform (const Vect3f &v, Vect3f &xv) const
xm_inline Vect3f & invXform (Vect3f &v) const
Static Public Attributes
static const Mat3f ZERO
static const Mat3f ID
Friends
class MatXf
class Mat4f
class QuatF
xm_inline friend Mat3f operator* (float s, const Mat3f &M)
xm_inline friend Mat3f xpose (const Mat3f &M)
xm_inline friend Mat3f invert (const Mat3f &M)
xm_inline friend Vect3d & operator*= (Vect3d &v, const Mat3f &M)
xm_inline friend Vect3d operator* (const Vect3d &v, const Mat3f &M)
xm_inline friend Vect3d operator* (const Mat3f &M, const Vect3d &v)
xm_inline friend Vect3f & operator*= (Vect3f &v, const Mat3f &M)
xm_inline friend Vect3f operator* (const Vect3f &v, const Mat3f &M)
xm_inline friend Vect3f operator* (const Mat3f &M, const Vect3f &v)
ostream & operator<< (ostream &os, const Mat3f &M)
istream & operator>> (istream &is, Mat3f &M)
XStream & operator<= (XStream &s, const Mat3f &M)
XStream & operator>= (XStream &s, Mat3f &M)
XStream & operator< (XStream &s, const Mat3f &M)
XStream & operator> (XStream &s, Mat3f &M)
XBuffer & operator<= (XBuffer &b, const Mat3f &M)
XBuffer & operator>= (XBuffer &b, Mat3f &M)
XBuffer & operator< (XBuffer &b, const Mat3f &M)
XBuffer & operator> (XBuffer &b, Mat3f &M)
Detailed Description
Constructor & Destructor Documentation
Mat3f() [1/7]
Mat3f::Mat3f () inline
 {}
Mat3f() [2/7]
Mat3f::Mat3f (float xx, float xy, float xz, float yx, float yy, float yz, float zx, float zy, float zz)
 {
     xx = xx_; xy = xy_; xz = xz_;
     yx = yx_; yy = yy_; yz = yz_;
     zx = zx_; zy = zy_; zz = zz_;
 }
Mat3f() [3/7]
Mat3f::Mat3f (float angle, eAxis axis) inline
 { set(angle, axis); }
References QuatF::angle(), QuatF::axis(), and set().
Mat3f() [4/7]
Mat3f::Mat3f (const Vect3f & diag, const Vect3f & sym) inline
 {set(diag, sym);}
References diag(), set(), and sym().
Mat3f() [5/7]
Mat3f::Mat3f (const Vect3f & axis, float angle, int normalizeAxis = 1) inline
     {set(axis, angle, normalizeAxis);}
References QuatF::angle(), QuatF::axis(), and set().
Mat3f() [6/7]
Mat3f::Mat3f (const QuatF & q) inline
 {set(q);}
References set().
Mat3f() [7/7]
Mat3f::Mat3f (const Vect3f & x_from, const Vect3f & y_from, const Vect3f & z_from, const Vect3f & x_to = Vect3f::I, const Vect3f & y_to = Vect3f::J, const Vect3f & z_to = Vect3f::K) inline
       { set(x_from, y_from, z_from, x_to, y_to, z_to); }
References set().
Member Function Documentation
add() [1/2]
Mat3f & Mat3f::add (const Mat3f & M)
 {
   xx += M.xx;
   xy += M.xy;
   xz += M.xz;
   yx += M.yx;
   yy += M.yy;
   yz += M.yz;
   zx += M.zx;
   zy += M.zy;
   zz += M.zz;
   return *this;
 }
add() [2/2]
Mat3f & Mat3f::add (const Mat3f & M, const Mat3f & N)
 {
   xx = M.xx + N.xx;
   xy = M.xy + N.xy;
   xz = M.xz + N.xz;
   yx = M.yx + N.yx;
   yy = M.yy + N.yy;
   yz = M.yz + N.yz;
   zx = M.zx + N.zx;
   zy = M.zy + N.zy;
   zz = M.zz + N.zz;
   return *this;
 }
Referenced by operator+(), and operator+=().
col()
xm_inline Vect3f Mat3f::col (int axis) const inline
 { return axis == X_AXIS ? Vect3f(xx, yx, zx) : (axis == Y_AXIS ? Vect3f(xy, yy, zy) : Vect3f(xz, yz, zz) ); }
References QuatF::axis(), X_AXIS, and Y_AXIS.
det()
float Mat3f::det () const
 {
   return  xx * (yy * zz - yz * zy)
     + xy * (yz * zx - yx * zz)
     + xz * (yx * zy - yy * zx);
 }
Referenced by invert().
diag()
xm_inline Vect3f Mat3f::diag () const inline
 {return Vect3f(xx, yy, zz);}
Referenced by Mat3f(), and set().
invert() [1/2]
int Mat3f::invert ()
 {
   float D, oneOverDet;
   float oxy, oyz, ozx, oyx, ozy, oxz, oxx, oyy;
   if (fabs(D = det()) < 1.0e-12) return 1; // not invertible
   oneOverDet = 1 / D;
   oxx = xx; oyy = yy;
   oxy = xy; oyx = yx;
   oyz = yz; ozy = zy;
   ozx = zx; oxz = xz;
   xy = (oxz * ozy - zz * oxy) * oneOverDet;
   yz = (oxz * oyx - xx * oyz) * oneOverDet;
   zx = (oyx * ozy - yy * ozx) * oneOverDet;
   yx = (oyz * ozx - oyx * zz) * oneOverDet;
   zy = (oxy * ozx - ozy * xx) * oneOverDet;
   xz = (oxy * oyz - oxz * yy) * oneOverDet;
   xx = (oyy * zz - oyz * ozy) * oneOverDet;
   yy = (oxx * zz - oxz * ozx) * oneOverDet;
   zz = (oxx * oyy - oxy * oyx) * oneOverDet;
   return 0;
 }
References det().
Referenced by MatXf::Invert().
invert() [2/2]
int Mat3f::invert (const Mat3f & M)
 {
   float D, oneOverDet;
   if (fabs(D = M.det()) < 1.0e-12) return 1; // not invertible
   oneOverDet = 1 / D;
   xx = (M.yy * M.zz - M.yz * M.zy) * oneOverDet;
   xy = (M.xz * M.zy - M.xy * M.zz) * oneOverDet;
   xz = (M.xy * M.yz - M.xz * M.yy) * oneOverDet;
   yx = (M.yz * M.zx - M.yx * M.zz) * oneOverDet;
   yy = (M.xx * M.zz - M.xz * M.zx) * oneOverDet;
   yz = (M.xz * M.yx - M.xx * M.yz) * oneOverDet;
   zx = (M.yx * M.zy - M.yy * M.zx) * oneOverDet;
   zy = (M.xy * M.zx - M.xx * M.zy) * oneOverDet;
   zz = (M.xx * M.yy - M.xy * M.yx) * oneOverDet;
   return 0;
 }
References det().
invXform() [1/4]
Vect3d & Mat3f::invXform (const Vect3d & v, Vect3d & xv) const
 {
   xv.x = xx * v.x + yx * v.y + zx * v.z;
   xv.y = xy * v.x + yy * v.y + zy * v.z;
   xv.z = xz * v.x + yz * v.y + zz * v.z;
   return xv;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
Referenced by MatXf::invXformPoint(), and MatXf::invXformVect().
invXform() [2/4]
Vect3f & Mat3f::invXform (const Vect3f & v, Vect3f & xv) const
 {
   xv.x = (float)(xx * v.x + yx * v.y + zx * v.z);
   xv.y = (float)(xy * v.x + yy * v.y + zy * v.z);
   xv.z = (float)(xz * v.x + yz * v.y + zz * v.z);
   return xv;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
invXform() [3/4]
Vect3d & Mat3f::invXform (Vect3d & v) const
 {
   double ox, oy;
   ox = v.x; oy= v.y;
   v.x = xx * ox + yx * oy + zx * v.z;
   v.y = xy * ox + yy * oy + zy * v.z;
   v.z = xz * ox + yz * oy + zz * v.z;
   return v;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
invXform() [4/4]
Vect3f & Mat3f::invXform (Vect3f & v) const
 {
   float ox, oy;
   ox = v.x; oy= v.y;
   v.x = (float)(xx * ox + yx * oy + zx * v.z);
   v.y = (float)(xy * ox + yy * oy + zy * v.z);
   v.z = (float)(xz * ox + yz * oy + zz * v.z);
   return v;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
mult()
Mat3f & Mat3f::mult (const Mat3f & M, const Mat3f & N)
 {
   xx = M.xx * N.xx + M.xy * N.yx + M.xz * N.zx;
   xy = M.xx * N.xy + M.xy * N.yy + M.xz * N.zy;
   xz = M.xx * N.xz + M.xy * N.yz + M.xz * N.zz;
   yx = M.yx * N.xx + M.yy * N.yx + M.yz * N.zx;
   yy = M.yx * N.xy + M.yy * N.yy + M.yz * N.zy;
   yz = M.yx * N.xz + M.yy * N.yz + M.yz * N.zz;
   zx = M.zx * N.xx + M.zy * N.yx + M.zz * N.zx;
   zy = M.zx * N.xy + M.zy * N.yy + M.zz * N.zy;
   zz = M.zx * N.xz + M.zy * N.yz + M.zz * N.zz;
   return *this;
 }
Referenced by operator*().
negate() [1/2]
Mat3f & Mat3f::negate ()
 {
   xx = - xx;
   xy = - xy;
   xz = - xz;
   yx = - yx;
   yy = - yy;
   yz = - yz;
   zx = - zx;
   zy = - zy;
   zz = - zz;
   return *this;
 }
negate() [2/2]
Mat3f & Mat3f::negate (const Mat3f & M)
 {
   xx = - M.xx;
   xy = - M.xy;
   xz = - M.xz;
   yx = - M.yx;
   yy = - M.yy;
   yz = - M.yz;
   zx = - M.zx;
   zy = - M.zy;
   zz = - M.zz;
   return *this;
 }
operator Mat3d()
Mat3f::operator Mat3d () const
 {
     return Mat3d( xx, xy, xz,   yx, yy, yz,  zx, zy, zz );
 }
operator()() [1/2]
xm_inline float& Mat3f::operator() (int i, int j) inline
 { return (&xx)[(i - 1)*3 + j - 1]; }
operator()() [2/2]
xm_inline const float& Mat3f::operator() (int i, int j) const inline
 { return (&xx)[(i - 1)*3 + j - 1]; }
operator*() [1/2]
xm_inline Mat3f Mat3f::operator* (const Mat3f & M) const inline
 { Mat3f N; return N.mult(*this, M); }
References mult().
operator*() [2/2]
xm_inline Mat3f Mat3f::operator* (float s) const inline
 { Mat3f N; return N.scale(*this, s); }
References QuatF::s(), and scale().
operator*=() [1/2]
xm_inline Mat3f& Mat3f::operator*= (const Mat3f & M) inline
 { return postmult(M); }
References postmult().
operator*=() [2/2]
xm_inline Mat3f& Mat3f::operator*= (float s) inline
 { return scale(s); }
References QuatF::s(), and scale().
operator+()
xm_inline Mat3f Mat3f::operator+ (const Mat3f & M) const inline
 { Mat3f N; return N.add(*this,M); }
References add().
operator+=()
xm_inline Mat3f& Mat3f::operator+= (const Mat3f & M) inline
 { return add(M); }
References add().
operator-() [1/2]
Mat3f Mat3f::operator- () const
 {
    Mat3f M;
    M.xx = - xx;
    M.xy = - xy;
    M.xz = - xz;
    M.yx = - yx;
    M.yy = - yy;
    M.yz = - yz;
    M.zx = - zx;
    M.zy = - zy;
    M.zz = - zz;
    return M;
 }
operator-() [2/2]
xm_inline Mat3f Mat3f::operator- (const Mat3f & M) const inline
 { Mat3f N; return N.sub(*this,M); }
References sub().
operator-=()
xm_inline Mat3f& Mat3f::operator-= (const Mat3f & M) inline
 { return sub(M); }
References sub().
operator/()
xm_inline Mat3f Mat3f::operator/ (float s) const inline
 { Mat3f N; return N.scale(*this, 1/s); }
References QuatF::s(), and scale().
operator/=()
xm_inline Mat3f& Mat3f::operator/= (float s) inline
 { return scale(1/s); }
References QuatF::s(), and scale().
operator[]() [1/2]
xm_inline Vect3f& Mat3f::operator[] (int i) inline
 {return *(((Vect3f *) &xx) + i);}
operator[]() [2/2]
xm_inline const Vect3f& Mat3f::operator[] (int i) const inline
 {return *(((Vect3f *) &xx) + i);}
postmult()
Mat3f & Mat3f::postmult (const Mat3f & M)
 {
   float oxy, oyz, ozx, oyx, ozy, oxz;
   oxy = xy; oyx = yx; oyz = yz; ozy = zy; ozx = zx; oxz = xz;
   xy = xx *  M.xy + oxy * M.yy + oxz * M.zy;
   xz = xx *  M.xz + oxy * M.yz + oxz * M.zz;
   yx = oyx * M.xx + yy  * M.yx + oyz * M.zx;
   yz = oyx * M.xz + yy  * M.yz + oyz * M.zz;
   zx = ozx * M.xx + ozy * M.yx + zz  * M.zx;
   zy = ozx * M.xy + ozy * M.yy + zz  * M.zy;
   xx = xx  * M.xx + oxy * M.yx + oxz * M.zx;
   yy = oyx * M.xy + yy  * M.yy + oyz * M.zy;
   zz = ozx * M.xz + ozy * M.yz + zz  * M.zz;
   return *this;
 }
Referenced by operator*=().
postScale() [1/2]
Mat3f & Mat3f::postScale (const Mat3f & M, const Vect3f & v)
 {   // M * Mat3f(v)
     xx = M.xx*v.x;
     xy = M.xy*v.y;
     xz = M.xz*v.z;
     yx = M.yx*v.x;
     yy = M.yy*v.y;
     yz = M.yz*v.z;
     zx = M.zx*v.x;
     zy = M.zy*v.y;
     zz = M.zz*v.z;
     return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
postScale() [2/2]
Mat3f & Mat3f::postScale (const Vect3f & v)
 {   // this * Mat3f(v)
     xx *= v.x;
     xy *= v.y;
     xz *= v.z;
     yx *= v.x;
     yy *= v.y;
     yz *= v.z;
     zx *= v.x;
     zy *= v.y;
     zz *= v.z;
     return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
premult()
Mat3f & Mat3f::premult (const Mat3f & M)
 {
   float oxy, oyz, ozx, oyx, ozy, oxz;
   oxy = xy; oyx = yx; oyz = yz; ozy = zy; ozx = zx; oxz = xz;
   xy = M.xx * oxy + M.xy * yy  + M.xz * ozy;
   xz = M.xx * oxz + M.xy * oyz + M.xz * zz;
   yx = M.yx * xx  + M.yy * oyx + M.yz * ozx;
   yz = M.yx * oxz + M.yy * oyz + M.yz * zz;
   zx = M.zx * xx  + M.zy * oyx + M.zz * ozx;
   zy = M.zx * oxy + M.zy * yy  + M.zz * ozy;
   xx = M.xx * xx  + M.xy * oyx + M.xz * ozx;
   yy = M.yx * oxy + M.yy * yy  + M.yz * ozy;
   zz = M.zx * oxz + M.zy * oyz + M.zz * zz;
   return *this;
 }
preScale() [1/2]
Mat3f & Mat3f::preScale (const Mat3f & M, const Vect3f & v)
 {   // Mat3f(v) * M
     xx = M.xx*v.x;
     xy = M.xy*v.x;
     xz = M.xz*v.x;
     yx = M.yx*v.y;
     yy = M.yy*v.y;
     yz = M.yz*v.y;
     zx = M.zx*v.z;
     zy = M.zy*v.z;
     zz = M.zz*v.z;
     return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
preScale() [2/2]
Mat3f & Mat3f::preScale (const Vect3f & v)
 {   // Mat3f(s) * this
     xx *= v.x;
     xy *= v.x;
     xz *= v.x;
     yx *= v.y;
     yy *= v.y;
     yz *= v.y;
     zx *= v.z;
     zy *= v.z;
     zz *= v.z;
     return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
scale() [1/3]
Mat3f & Mat3f::scale (const Mat3f & M, float s)
 {
   xx = s * M.xx;
   xy = s * M.xy;
   xz = s * M.xz;
   yx = s * M.yx;
   yy = s * M.yy;
   yz = s * M.yz;
   zx = s * M.zx;
   zy = s * M.zy;
   zz = s * M.zz;
   return *this;
 }
Referenced by operator*(), operator*=(), operator/(), and operator/=().
scale() [2/3]
Mat3f & Mat3f::scale (const Vect3f & s)
 {
   xx *= s.x;
   xy *= s.y;
   xz *= s.z;
   yx *= s.x;
   yy *= s.y;
   yz *= s.z;
   zx *= s.x;
   zy *= s.y;
   zz *= s.z;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
scale() [3/3]
Mat3f & Mat3f::scale (float s)
 {
   xx *= s;
   xy *= s;
   xz *= s;
   yx *= s;
   yy *= s;
   yz *= s;
   zx *= s;
   zy *= s;
   zz *= s;
   return *this;
 }
set() [1/5]
Mat3f & Mat3f::set (const QuatF & q)
 {
   xx = 2.f * (q.s_ * q.s_ + q.x_ * q.x_ - 0.5f);
   yy = 2.f * (q.s_ * q.s_ + q.y_ * q.y_ - 0.5f);
   zz = 2.f * (q.s_ * q.s_ + q.z_ * q.z_ - 0.5f);
   xy = 2.f * (q.y_ * q.x_ - q.z_ * q.s_);
   yx = 2.f * (q.x_ * q.y_ + q.z_ * q.s_);
   yz = 2.f * (q.z_ * q.y_ - q.x_ * q.s_);
   zy = 2.f * (q.y_ * q.z_ + q.x_ * q.s_);
   zx = 2.f * (q.x_ * q.z_ - q.y_ * q.s_);
   xz = 2.f * (q.z_ * q.x_ + q.y_ * q.s_);
   return *this;
 }
set() [2/5]
Mat3f & Mat3f::set (const Vect3f & axis, float angle, int normalizeAxis = 1)
 {
   QuatF q;
   q.set(angle, axis, normalizeAxis);
   set(q);
   return *this;
 }
References set(), and QuatF::set().
set() [3/5]
Mat3f & Mat3f::set (const Vect3f & diag, const Vect3f & sym)
 {
   xx = diag.x;
   yy = diag.y;
   zz = diag.z;
   yz = zy = sym.x;
   zx = xz = sym.y;
   xy = yx = sym.z;
   return *this;
 }
References diag(), sym(), Vect3f::x, Vect3f::y, and Vect3f::z.
set() [4/5]
Mat3f & Mat3f::set (const Vect3f & x_from, const Vect3f & y_from, const Vect3f & z_from, const Vect3f & x_to = Vect3f::I, const Vect3f & y_to = Vect3f::J, const Vect3f & z_to = Vect3f::K)
 {
     xx = dot(x_from, x_to);
     xy = dot(y_from, x_to);
     xz = dot(z_from, x_to);
     yx = dot(x_from, y_to);
     yy = dot(y_from, y_to);
     yz = dot(z_from, y_to);
     zx = dot(x_from, z_to);
     zy = dot(y_from, z_to);
     zz = dot(z_from, z_to);
     return *this;
 }
References dot().
set() [5/5]
Mat3f & Mat3f::set (float angle, eAxis axis)
 {
 //  ------ Calculate Matrix for ROTATE point an angle ------
     float calpha = (float)cos(angle);
     float salpha = (float)sin(angle);
     switch(axis){
         case Z_AXIS:
             xx   =  calpha; xy   = -salpha; xz   = 0;
             yx   =  salpha; yy   = calpha;  yz   = 0;
             zx   = 0;     zy     = 0;       zz   = 1;
             break;
         case X_AXIS:
             xx   =  1;    xy     =  0;      xz   = 0;
             yx   =  0;    yy     =  calpha; yz   = -salpha;
             zx   =  0;    zy     =  salpha; zz   = calpha;
             break;
         case Y_AXIS:
             xx   = calpha;  xy   =  0;      xz   = salpha;
             yx   = 0;     yy     =  1;      yz   = 0;
             zx   = -salpha; zy   =  0;      zz   = calpha;
             break;
         case W_AXIS:
             break;
         }
     return *this;
 }
References W_AXIS, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by Mat3f(), MatXf::set(), and set().
setCol()
xm_inline Mat3f& Mat3f::setCol (int axis, const Vect3f & v) inline
 { if(axis == X_AXIS) setXcol(v); else if(axis == Y_AXIS) setYcol(v); else setZcol(v); return *this; }
References QuatF::axis(), setXcol(), setYcol(), setZcol(), X_AXIS, and Y_AXIS.
setSkew()
Mat3f & Mat3f::setSkew (const Vect3f & v)
 {
   xx = yy = zz = 0.0;
   zy =  v.x;
   yz = -v.x;
   xz =  v.y;
   zx = -v.y;
   yx =  v.z;
   xy = -v.z;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
setXcol()
Mat3f & Mat3f::setXcol (const Vect3f & v)
 {
   xx = v.x;
   yx = v.y;
   zx = v.z;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Referenced by setCol().
setYcol()
Mat3f & Mat3f::setYcol (const Vect3f & v)
 {
   xy = v.x;
   yy = v.y;
   zy = v.z;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Referenced by setCol().
setZcol()
Mat3f & Mat3f::setZcol (const Vect3f & v)
 {
   xz = v.x;
   yz = v.y;
   zz = v.z;
   return *this;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Referenced by setCol().
sub() [1/2]
Mat3f & Mat3f::sub (const Mat3f & M)
 {
   xx -= M.xx;
   xy -= M.xy;
   xz -= M.xz;
   yx -= M.yx;
   yy -= M.yy;
   yz -= M.yz;
   zx -= M.zx;
   zy -= M.zy;
   zz -= M.zz;
   return *this;
 }
sub() [2/2]
Mat3f & Mat3f::sub (const Mat3f & M, const Mat3f & N)
 {
   xx = M.xx - N.xx;
   xy = M.xy - N.xy;
   xz = M.xz - N.xz;
   yx = M.yx - N.yx;
   yy = M.yy - N.yy;
   yz = M.yz - N.yz;
   zx = M.zx - N.zx;
   zy = M.zy - N.zy;
   zz = M.zz - N.zz;
   return *this;
 }
Referenced by operator-(), and operator-=().
sym()
xm_inline Vect3f Mat3f::sym () const inline
 {return Vect3f(yz, zx, xy);}
Referenced by Mat3f(), and set().
symmetrize() [1/2]
Mat3f & Mat3f::symmetrize ()
 {
   xx = 2 * xx;
   yy = 2 * yy;
   zz = 2 * zz;
   xy = yx = xy + yx;
   yz = zy = yz + zy;
   zx = xz = zx + xz;
   return *this;
 }
symmetrize() [2/2]
Mat3f & Mat3f::symmetrize (const Mat3f & M)
 {
   xx = 2 * M.xx;
   yy = 2 * M.yy;
   zz = 2 * M.zz;
   xy = yx = M.xy + M.yx;
   yz = zy = M.yz + M.zy;
   zx = xz = M.zx + M.xz;
   return *this;
 }
xcol()
xm_inline Vect3f Mat3f::xcol () const inline
 {return Vect3f(xx, yx, zx);}
xform() [1/4]
Vect3d & Mat3f::xform (const Vect3d & v, Vect3d & xv) const
 {
   xv.x = xx * v.x + xy * v.y + xz * v.z;
   xv.y = yx * v.x + yy * v.y + yz * v.z;
   xv.z = zx * v.x + zy * v.y + zz * v.z;
   return xv;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
Referenced by MatXf::Invert(), MatXf::xformPoint(), and MatXf::xformVect().
xform() [2/4]
Vect3f & Mat3f::xform (const Vect3f & v, Vect3f & xv) const
 {
   xv.x = (float)(xx * v.x + xy * v.y + xz * v.z);
   xv.y = (float)(yx * v.x + yy * v.y + yz * v.z);
   xv.z = (float)(zx * v.x + zy * v.y + zz * v.z);
   return xv;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
xform() [3/4]
Vect3d & Mat3f::xform (Vect3d & v) const
 {
   double ox, oy;
   ox = v.x; oy= v.y;
   v.x = xx * ox + xy * oy + xz * v.z;
   v.y = yx * ox + yy * oy + yz * v.z;
   v.z = zx * ox + zy * oy + zz * v.z;
   return v;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
xform() [4/4]
Vect3f & Mat3f::xform (Vect3f & v) const
 {
   float ox, oy;
   ox = v.x; oy= v.y;
   v.x = (float)(xx * ox + xy * oy + xz * v.z);
   v.y = (float)(yx * ox + yy * oy + yz * v.z);
   v.z = (float)(zx * ox + zy * oy + zz * v.z);
   return v;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
xpose() [1/2]
Mat3f & Mat3f::xpose ()
 {
   float tmp;
   tmp = xy;
   xy = yx;
   yx = tmp;
   tmp = yz;
   yz = zy;
   zy = tmp;
   tmp = zx;
   zx = xz;
   xz = tmp;
   return *this;
 }
xpose() [2/2]
Mat3f & Mat3f::xpose (const Mat3f & M)
 {
   xx = M.xx;
   xy = M.yx;
   xz = M.zx;
   yx = M.xy;
   yy = M.yy;
   yz = M.zy;
   zx = M.xz;
   zy = M.yz;
   zz = M.zz;
   return *this;
 }
xrow() [1/2]
xm_inline Vect3f& Mat3f::xrow () inline
 {return *((Vect3f *) &xx);}
xrow() [2/2]
xm_inline const Vect3f& Mat3f::xrow () const inline
 {return *((Vect3f *) &xx);}
ycol()
xm_inline Vect3f Mat3f::ycol () const inline
 {return Vect3f(xy, yy, zy);}
yrow() [1/2]
xm_inline Vect3f& Mat3f::yrow () inline
 {return *((Vect3f *) &yx);}
yrow() [2/2]
xm_inline const Vect3f& Mat3f::yrow () const inline
 {return *((Vect3f *) &yx);}
zcol()
xm_inline Vect3f Mat3f::zcol () const inline
 {return Vect3f(xz, yz, zz);}
zrow() [1/2]
xm_inline Vect3f& Mat3f::zrow () inline
 {return *((Vect3f *) &zx);}
zrow() [2/2]
xm_inline const Vect3f& Mat3f::zrow () const inline
 {return *((Vect3f *) &zx);}
Friends And Related Function Documentation
invert
xm_inline friend Mat3f invert (const Mat3f & M) friend
 { Mat3f N; N.invert(M); return N; }
Mat4f
friend class Mat4f friend
MatXf
friend class MatXf friend
operator* [1/5]
xm_inline friend Vect3d operator* (const Mat3f & M, const Vect3d & v) friend
 { Vect3d xv; return M.xform(v, xv); }
operator* [2/5]
xm_inline friend Vect3f operator* (const Mat3f & M, const Vect3f & v) friend
 { Vect3f xv; return M.xform(v, xv); }
operator* [3/5]
xm_inline friend Vect3d operator* (const Vect3d & v, const Mat3f & M) friend
 { Vect3d xv; return M.xform(v, xv); }
operator* [4/5]
xm_inline friend Vect3f operator* (const Vect3f & v, const Mat3f & M) friend
 { Vect3f xv; return M.xform(v, xv); }
operator* [5/5]
xm_inline friend Mat3f operator* (float s, const Mat3f & M) friend
 { Mat3f N; return N.scale(M, s); }
operator*= [1/2]
xm_inline friend Vect3d& operator*= (Vect3d & v, const Mat3f & M) friend
 { return M.xform(v); }
operator*= [2/2]
xm_inline friend Vect3f& operator*= (Vect3f & v, const Mat3f & M) friend
 { return M.xform(v); }
operator< [1/2]
XBuffer& operator< (XBuffer & b, const Mat3f & M) friend
 {
     b < m.xx < m.xy < m.xz;
     b < m.yx < m.yy < m.yz;
     b < m.zx < m.zy < m.zz;
     return b;
 }
operator< [2/2]
XStream& operator< (XStream & s, const Mat3f & M) friend
 {
     s.write(&m,sizeof(Mat3f));
     return s;
 }
operator<<
ostream& operator<< (ostream & os, const Mat3f & M) friend
 {
   os << m.xx << " \t" << m.xy << " \t" << m.xz << endl;
   os << m.yx << " \t" << m.yy << " \t" << m.yz << endl;
   os << m.zx << " \t" << m.zy << " \t" << m.zz;
   return os;
 }
operator<= [1/2]
XBuffer& operator<= (XBuffer & b, const Mat3f & M) friend
 {
     b <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     b <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     b <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return b;
 }
operator<= [2/2]
XStream& operator<= (XStream & s, const Mat3f & M) friend
 {
     s <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     s <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     s <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return s;
 }
operator> [1/2]
XBuffer& operator> (XBuffer & b, Mat3f & M) friend
 {
     b > m.xx > m.xy > m.xz;
     b > m.yx > m.yy > m.yz;
     b > m.zx > m.zy > m.zz;
     return b;
 }
operator> [2/2]
XStream& operator> (XStream & s, Mat3f & M) friend
 {
     s.read(&m,sizeof(Mat3f));
     return s;
 }
operator>= [1/2]
XBuffer& operator>= (XBuffer & b, Mat3f & M) friend
 {
     b >= m.xx >= m.xy >= m.xz;
     b >= m.yx >= m.yy >= m.yz;
     b >= m.zx >= m.zy >= m.zz;
     return b;
 }
operator>= [2/2]
XStream& operator>= (XStream & s, Mat3f & M) friend
 {
     s >= m.xx >= m.xy >= m.xz;
     s >= m.yx >= m.yy >= m.yz;
     s >= m.zx >= m.zy >= m.zz;
     return s;
 }
operator>>
istream& operator>> (istream & is, Mat3f & M) friend
 {
   is >> m.xx >> m.xy >> m.xz;
   is >> m.yx >> m.yy >> m.yz;
   is >> m.zx >> m.zy >> m.zz;
   return is;
 }
QuatF
friend class QuatF friend
xpose
xm_inline friend Mat3f xpose (const Mat3f & M) friend
 { Mat3f N; return N.xpose(M); }
Member Data Documentation
ID
const Mat3f Mat3f::ID static
ZERO
const Mat3f Mat3f::ZERO static
The documentation for this class was generated from the following files:
lib/xtool/xmath/xmath.h
lib/xtool/xmath/xmath.cpp