Vangers: InputEventBuffer Class Reference
InputEventBuffer Class Reference
#include <server.h>
Public Member Functions
InputEventBuffer (unsigned int size)
void reset ()
int receive (XSocket &sock)
int current_event ()
int event_size ()
int next_event ()
void ignore_event ()
int get_byte ()
int get_short ()
int get_word ()
int get_int ()
unsigned int get_dword ()
double get_float ()
InputEventBuffer (unsigned int size)
void reset ()
int receive (XSocket &sock=main_socket, int dont_free=0)
int receive_waiting_for_event (int event, XSocket &sock=main_socket, int skip_if_aint=0)
int current_event ()
int current_ID ()
int current_creator ()
int current_time ()
int current_x ()
int current_y ()
int current_radius ()
int current_body_size ()
void ignore_event ()
int next_event ()
int get_byte ()
int get_short ()
double get_float ()
int get_word ()
int get_int ()
unsigned int get_dword ()
int parsing_names_query ()
int parsing_coords_query ()
int parsing_players_data_query ()
Public Member Functions inherited from XBuffer
XBuffer (unsigned int sz=XB_DEFSIZE)
XBuffer (void *p, int sz)
~XBuffer (void)
void SetRadix (int r)
void SetDigits (int d)
void alloc (unsigned int sz)
void free (void)
void fill (char fc='\0')
void set (int off, int mode=XB_BEG)
void init (void)
int search (char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int search (const char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int end () const
unsigned int tell (void) const
unsigned int length (void) const
char * address ()
unsigned int read (void *s, unsigned int len)
unsigned int write (const void *s, unsigned int len, int bin_flag=1)
void handleOutOfSize ()
XBuffer & operator< (const char *v)
XBuffer & operator< (char v)
XBuffer & operator< (unsigned char v)
XBuffer & operator< (short v)
XBuffer & operator< (unsigned short v)
XBuffer & operator< (int v)
XBuffer & operator< (unsigned int v)
XBuffer & operator< (long v)
XBuffer & operator< (unsigned long v)
XBuffer & operator< (float v)
XBuffer & operator< (double v)
XBuffer & operator< (long double v)
XBuffer & operator> (char *v)
XBuffer & operator> (char &v)
XBuffer & operator> (unsigned char &v)
XBuffer & operator> (short &v)
XBuffer & operator> (unsigned short &v)
XBuffer & operator> (int &v)
XBuffer & operator> (unsigned int &v)
XBuffer & operator> (long &v)
XBuffer & operator> (unsigned long &v)
XBuffer & operator> (float &v)
XBuffer & operator> (double &v)
XBuffer & operator> (long double &v)
XBuffer & operator<= (char)
XBuffer & operator<= (unsigned char)
XBuffer & operator<= (short)
XBuffer & operator<= (unsigned short)
XBuffer & operator<= (int)
XBuffer & operator<= (unsigned int)
XBuffer & operator<= (long)
XBuffer & operator<= (unsigned long)
XBuffer & operator<= (long long int)
XBuffer & operator<= (float)
XBuffer & operator<= (double)
XBuffer & operator<= (long double)
XBuffer & operator>= (char &)
XBuffer & operator>= (unsigned char &)
XBuffer & operator>= (short &)
XBuffer & operator>= (unsigned short &)
XBuffer & operator>= (int &)
XBuffer & operator>= (unsigned int &)
XBuffer & operator>= (long &)
XBuffer & operator>= (unsigned long &)
XBuffer & operator>= (float &)
XBuffer & operator>= (double &)
XBuffer & operator>= (long double &)
char * GetBuf ()
char * operator() (int offs)
char * operator() (unsigned int offs)
XBuffer & operator++ ()
XBuffer & operator-- ()
XBuffer & operator+= (int v)
XBuffer & operator-= (int v)
XBuffer & operator+= (unsigned int v)
XBuffer & operator-= (unsigned int v)
char operator[] (int ind) const
char operator() () const
char & operator[] (int ind)
char & operator() ()
template<class T >
XBuffer & write (const T &v)
template<class T >
XBuffer & read (T &v)
Additional Inherited Members
Public Attributes inherited from XBuffer
char * buf
unsigned int size
unsigned int offset
int radix
int digits
int MakeFree
int automatic_realloc
Detailed Description
Constructor & Destructor Documentation
InputEventBuffer() [1/2]
InputEventBuffer::InputEventBuffer (unsigned int size)
                                                    : XBuffer(size) {
     reset();
 }
References reset().
InputEventBuffer() [2/2]
InputEventBuffer::InputEventBuffer (unsigned int size)
Member Function Documentation
current_body_size()
int InputEventBuffer::current_body_size () inline
 { return body_size; }
Referenced by is_current_server_configured(), and send_server_data().
current_creator()
int InputEventBuffer::current_creator () inline
 { return client_ID; }
Referenced by MessageDispatcher::receive().
current_event() [1/2]
int InputEventBuffer::current_event () inline
{
         return event_ID;
     }
Referenced by Player::receive(), receive_waiting_for_event(), and void_network_quant().
current_event() [2/2]
int InputEventBuffer::current_event () inline
 { return event_ID; } // 0 if there isn't any enents,  EventID othewise
current_ID()
int InputEventBuffer::current_ID () inline
 { return object_ID; }
current_radius()
int InputEventBuffer::current_radius () inline
 { return radius; }
current_time()
int InputEventBuffer::current_time () inline
 { return time; }
Referenced by set_time_by_server().
current_x()
int InputEventBuffer::current_x () inline
 { return x; }
current_y()
int InputEventBuffer::current_y () inline
 { return y; }
event_size()
int InputEventBuffer::event_size () inline
                      {
         return size_of_event;
     }
get_byte() [1/2]
int InputEventBuffer::get_byte () inline
                    {
         unsigned char t;
         *this > t;
         return (int)t;
     }
Referenced by connect_to_server(), is_current_server_configured(), Object::NetEvent(), next_event(), PlayersList::parsing_total_body_query(), Player::receive(), restore_connection(), send_server_data(), set_world(), PlayersList::single_parsing(), and TopList::TopList().
get_byte() [2/2]
int InputEventBuffer::get_byte () inline
 { unsigned char t; *this > t; return (int)t; }
get_dword() [1/2]
unsigned int InputEventBuffer::get_dword () inline
{
         unsigned int t;
         *this > t;
         return (unsigned int)t;
     }
Referenced by connect_to_server(), and Player::receive().
get_dword() [2/2]
unsigned int InputEventBuffer::get_dword () inline
 { unsigned int t; *this > t; return (unsigned int )t; }
get_float() [1/2]
double InputEventBuffer::get_float () inline
{
         float t;
         *this > t;
         return (double)t;
     }
Referenced by PlayersList::single_parsing().
get_float() [2/2]
double InputEventBuffer::get_float () inline
 { float t; *this > t; return (double)t; }
get_int() [1/2]
int InputEventBuffer::get_int () inline
                   {
         int t;
         *this > t;
         return (int)t;
     }
Referenced by connect_to_server(), and Player::receive().
get_int() [2/2]
int InputEventBuffer::get_int () inline
 { int t; *this > t; return (int)t; }
get_short() [1/2]
int InputEventBuffer::get_short () inline
                     {
         short t;
         *this > t;
         return (int)t;
     }
Referenced by Object::NetEvent(), next_event(), Player::receive(), and PlayersList::single_parsing().
get_short() [2/2]
int InputEventBuffer::get_short () inline
 { short t; *this > t; return (int)t; }
get_word() [1/2]
int InputEventBuffer::get_word () inline
                    {
         unsigned short t;
         *this > t;
         return (int)t;
     }
Referenced by connect_to_server(), and Object::NetEvent().
get_word() [2/2]
int InputEventBuffer::get_word () inline
 { unsigned short t; *this > t; return (int)t; }
ignore_event() [1/2]
void InputEventBuffer::ignore_event ()
{
     event_ID = 0;
     set(next_event_pointer);
 }
References XBuffer::set().
Referenced by connect_to_server(), is_current_server_configured(), Player::receive(), receive_waiting_for_event(), restore_connection(), send_server_data(), set_time_by_server(), set_world(), TopList::TopList(), total_players_data_list_query(), and void_network_quant().
ignore_event() [2/2]
void InputEventBuffer::ignore_event ()
next_event() [1/2]
int InputEventBuffer::next_event ()
{
     event_ID = 0;
     if (next_event_pointer + 2 > filled_size)
         return 0;
     if (next_event_pointer != tell())
         ErrH.Abort("Incorrect events reading");
     size_of_event = get_short();
     unsigned int new_pointer = next_event_pointer + size_of_event + 2;
     if (new_pointer > filled_size) {
         set(next_event_pointer);
         return 0;
     }
     next_event_pointer = new_pointer;
     return (event_ID = get_byte());
 }
References XErrorHandler::Abort(), ErrH, get_byte(), get_short(), XBuffer::set(), and XBuffer::tell().
Referenced by Player::receive(), receive(), receive_waiting_for_event(), and void_network_quant().
next_event() [2/2]
int InputEventBuffer::next_event ()
parsing_coords_query()
int InputEventBuffer::parsing_coords_query ()
parsing_names_query()
int InputEventBuffer::parsing_names_query ()
parsing_players_data_query()
int InputEventBuffer::parsing_players_data_query ()
receive() [1/2]
int InputEventBuffer::receive (XSocket & sock)
{
     if (next_event_pointer != tell())
         ErrH.Abort("Incorrect events reading");
     if (next_event_pointer) {
         if (filled_size != next_event_pointer)
             memmove(address(), address() + next_event_pointer, filled_size - next_event_pointer);
         filled_size -= next_event_pointer;
         offset = next_event_pointer = 0;
     }
     int add_size = sock.receive((char *)address() + filled_size, length() - filled_size);
     filled_size += add_size;
     next_event();
     return add_size;
 }
References XErrorHandler::Abort(), XBuffer::address(), ErrH, XBuffer::length(), next_event(), XBuffer::offset, XSocket::receive(), and XBuffer::tell().
Referenced by Player::receive(), receive_waiting_for_event(), and void_network_quant().
receive() [2/2]
int InputEventBuffer::receive (XSocket & sock = main_socket, int dont_free = 0)
{
     restore_connection();
     if(next_event_pointer != tell()) {
         XBuffer str;
         str < "Connection's problems: " <= event_ID < "  "  <= object_ID < "  "  <= next_event_pointer - tell();
         ErrH.Abort(str.GetBuf(), XERR_USER);
     }
     if(next_event_pointer && !dont_free) {
         if(filled_size != next_event_pointer) {
             memmove(address(), address() + next_event_pointer, filled_size - next_event_pointer);
         }
         filled_size -= next_event_pointer;
         offset = next_event_pointer = 0;
     }
     int add_size = sock.receive(address() + filled_size, length() - filled_size);
     filled_size += add_size;
     n_received_bytes += add_size;
     if(add_size)
         enable_send = 1;
 #ifdef _FOUT_
     if(add_size)
         fout < "Receive: " <= SDL_GetTicks() < "\t" <= add_size < "\n";
 #endif
     //std::cout<<"InputEventBuffer::receive "<<add_size<<" "<<std::endl;
     return next_event();
 }
References XErrorHandler::Abort(), XBuffer::address(), enable_send, ErrH, fout, XBuffer::GetBuf(), XBuffer::length(), n_received_bytes, next_event(), XBuffer::offset, XSocket::receive(), restore_connection(), XBuffer::tell(), and XERR_USER.
receive_waiting_for_event()
int InputEventBuffer::receive_waiting_for_event (int event, XSocket & sock = main_socket, int skip_if_aint = 0)
 {
     //std::cout<<"InputEventBuffer::receive_waiting_for_event "<<event<<std::endl;
     receive(sock);
     START_TIMER(10*1000);
     while(current_event() || CHECK_TIMER()) {
         do {
             //std::cout<<"current_event:"<<(int)current_event()<<" clock:"<<SDL_GetTicks()<<" _end_time_:"<<_end_time_<<std::endl;
             if(current_event() == event) {
                 //std::cout<<"ok"<<std::endl;
                 int size = event_size + 2;
                 int prefix = next_event_pointer - size;
                 if(prefix > 0) {
                     memmove(buf + size,buf,filled_size);
                     memmove(buf,buf + size + prefix,size);
                     memmove(buf + size + prefix,buf + 2*size + prefix,filled_size - size - prefix);
                     //offset = next_event_pointer = size - body_size;
                     offset = next_event_pointer = 0;
                     return next_event();
                 }
                 return event;
             }
             ignore_event();
         } while(next_event());
         receive(sock,1);
     }
     if(!skip_if_aint)
         if (lang() == RUSSIAN) {
             ErrH.Abort("  ", XERR_USER, event);
         } else {
             ErrH.Abort("Time out of Server's response receiving", XERR_USER, event);
         }
     event_ID = 0;
     offset = next_event_pointer = 0;
     return 0;
 }
References XErrorHandler::Abort(), XBuffer::buf, CHECK_TIMER, current_event(), ErrH, ignore_event(), lang(), next_event(), XBuffer::offset, receive(), RUSSIAN, XBuffer::size, START_TIMER, and XERR_USER.
Referenced by connect_to_server(), is_current_server_configured(), restore_connection(), send_server_data(), set_time_by_server(), set_world(), TopList::TopList(), and total_players_data_list_query().
reset() [1/2]
void InputEventBuffer::reset ()
{
     next_event_pointer = 0;
     filled_size = 0;
     offset = 0;
 }
References XBuffer::offset.
Referenced by connect_to_server(), disconnect_from_server(), InputEventBuffer(), and restore_connection().
reset() [2/2]
void InputEventBuffer::reset ()
The documentation for this class was generated from the following files:
server/server.h
src/network.h
server/server.cpp
src/network.cpp