Vangers: src/common.h File Reference
common.h File Reference
Macros
#define MIN(a, b) (((a) < (b))?(a):(b))
#define MAX(a, b) (((a) > (b))?(a):(b))
#define XCYCL(x) ((x) & clip_mask_x)
#define YCYCL(y) ((y) & clip_mask_y)
#define iXCYCL(x) ((x) & clip_mask_x)
#define iYCYCL(y) ((y) & iclip_mask_y)
#define rPI(a) (((a)) & (PIx2 - 1))
#define random(num) (int)RND(num)
#define RNDSIGN ((!RND(2)) ? -1 : 1)
#define PCSIDE 64
#define PC_MAX 2*PCSIDE + 1
#define mSQRT(a, b) sqrt((a)*(double)(a) + (b)*(double)(b))
#define mATAN2(a, b) rPI((int)(atan2((double)-b,(double)a)*PIx2/(2.*_PI)))
#define EXTERNAL_USE
#define UP_LAYER 0
#define DOWN_LAYER 1
#define COL1 255
#define COL2 252
#define COL3 250
#define COL4 249
#define COL5 251
#define _MEM_STATISTIC_(a) ;
Typedefs
typedef unsigned char uchar
typedef unsigned short ushort
typedef unsigned int uint
Functions
int COS (int x)
int SIN (int x)
unsigned RND (unsigned m)
unsigned realRND (unsigned m)
void cycleTor (int &x, int &y)
char * GetTargetName (const char *name)
Variables
const uint MAP_POWER_X = 11
const uint map_size_x = 1 << MAP_POWER_X
const uint clip_mask_x = map_size_x - 1
const uint TOR_POWER = 1
const uint TOR_XSIZE = TOR_POWER*map_size_x
uint MAP_POWER_Y
uint map_size_y
uint clip_mask_y
uint iclip_mask_y
uint clip_mask
uint TOR_YSIZE
const int MAX_RADIUS = 48
const int UNIT = 0x10000
const int SHIFT = 16
const int PIx2 = 1 << 12
const int PI = PIx2/2
const int locPI = PIx2/2
int * SI
int * CO
const char * mapFName
int ColorShow
unsigned char * palbuf
unsigned char * palbufA
unsigned char * palbufC
unsigned RNDVAL
void * _video
Macro Definition Documentation
_MEM_STATISTIC_
#define _MEM_STATISTIC_ (a) ;
COL1
#define COL1 255
COL2
#define COL2 252
COL3
#define COL3 250
COL4
#define COL4 249
COL5
#define COL5 251
DOWN_LAYER
#define DOWN_LAYER 1
EXTERNAL_USE
#define EXTERNAL_USE
iXCYCL
#define iXCYCL (x) ((x) & clip_mask_x)
iYCYCL
#define iYCYCL (y) ((y) & iclip_mask_y)
mATAN2
#define mATAN2 (a, b) rPI((int)(atan2((double)-b,(double)a)*PIx2/(2.*_PI)))
MAX
#define MAX (a, b) (((a) > (b))?(a):(b))
MIN
#define MIN (a, b) (((a) < (b))?(a):(b))
mSQRT
#define mSQRT (a, b) sqrt((a)*(double)(a) + (b)*(double)(b))
PC_MAX
#define PC_MAX 2*PCSIDE + 1
PCSIDE
#define PCSIDE 64
random
#define random (num) (int)RND(num)
RNDSIGN
#define RNDSIGN ((!RND(2)) ? -1 : 1)
rPI
#define rPI (a) (((a)) & (PIx2 - 1))
UP_LAYER
#define UP_LAYER 0
XCYCL
#define XCYCL (x) ((x) & clip_mask_x)
YCYCL
#define YCYCL (y) ((y) & clip_mask_y)
Typedef Documentation
uchar
typedef unsigned char uchar
uint
typedef unsigned int uint
ushort
typedef unsigned short ushort
Function Documentation
COS()
int COS (int x) inline
 { return CO[rPI(x)]; }
References CO, and rPI.
Referenced by CastArbitraryShadow(), and ParticleObject::CreateParticle().
cycleTor()
void cycleTor (int & x, int & y) inline
 {
     x &= TOR_XSIZE - 1;
     y &= TOR_YSIZE - 1;
 }
References TOR_XSIZE, and TOR_YSIZE.
Referenced by aciSendEvent2itmdsp(), VangerUnit::AddFree(), TargetParticleObject::AddVertex(), TargetParticleObject::AddVertex2(), AxisLen(), calc_view_factors(), VangerUnit::ChangeVangerProcess(), GunSlot::CheckTarget(), ActionUnit::CreateActionUnit(), JumpBallObject::CreateBullet(), ClefObject::CreateClef(), DangerDataType::CreateDanger(), DebrisObject::CreateDebris(), ParticleObject::CreateDirectParticle(), ExplosionObject::CreateExplosion(), FireBallObject::CreateFireBall(), FishWarrior::CreateFish(), ParticleGenerator::CreateGenerator(), HordeObject::CreateHorde(), TargetParticleObject::CreateParticle(), WaterParticleObject::CreateParticle(), ParticleObject::CreateParticle(), ParticleObject::CreateRingOfLord(), SensorDataType::CreateSensor(), SkyFarmerObject::CreateSkyFarmer(), HordeSource::CreateSource(), StuffObject::CreateStuff(), StuffObject::DeviceOut(), TrackUnit::DrawMechosParticle(), DrawMechosWheelDown(), DrawMechosWheelUp(), BulletObject::DrawQuant(), ActionUnit::HideAction(), InsectUnit::HideAction(), StuffObject::ImpulseAction(), VangerUnit::keyhandler(), TntCreature::Load(), StuffObject::NetEvent(), ParticleGenerator::Quant(), DebrisObject::Quant(), StuffObject::Quant(), HordeObject::Quant(), JumpBallObject::Quant(), ClefObject::Quant(), SkyFarmerObject::Quant(), ActionUnit::Quant(), TrackUnit::Quant(), GunSlot::Quant(), VangerFunctionType::Quant(), VangerUnit::SensorQuant(), BulletObject::TimeOutQuant(), and InsectUnit::Touch().
GetTargetName()
char* GetTargetName (const char * name)
 {
     static int first = 1;
     static char namebuf[256];
     //std::cout<<"name:"<<name<<" mapFName:"<<mapFName<<std::endl;
     if(!name) {
         first = 1;
         return NULL;
     }
     if(first) {
         first = 0;
         path_to_world = name;
         int st = path_to_world.find_last_of('/');
         path_to_world = path_to_world.substr(0, st+1);
         return strdup(name);
         }
     std::string path;
     path = path_to_world + name;
     strcpy(namebuf, path.c_str());
     return namebuf;
 }
Referenced by ChangeWorld(), GeneralSystemOpen(), TrackType::Open(), TrackType::Save(), and StaticOpen().
realRND()
unsigned realRND (unsigned m) inline
{
     if (!m) {
         return 0;
     }
     return rand()%m;
 }
Referenced by camera_quant(), VangerUnit::CreateParticleRotor(), VangerUnit::Destroy(), getRC(), pal_iter0(), pal_iter1(), DangerDataType::Quant(), and VangerUnit::SensorQuant().
RND()
unsigned RND (unsigned m) inline
 {
     RNDVAL ^= RNDVAL >> 3;
     RNDVAL ^= RNDVAL << 28;
     RNDVAL &= 0x7FFFFFFF;
     if(!m) return 0;
     //std::cout<<"m:"<<m<<" r:"<<RNDVAL%m<<std::endl;
     return RNDVAL%m;
 }
References RNDVAL.
Referenced by VangerUnit::Action(), uvsDolly::ActiveQuant(), VangerUnit::AddFree(), uvsVanger::addInventory(), addVanger(), uvsBunch::begin_harvest(), uvsBunch::begin_race(), VangerUnit::CalcAiFactor(), camera_impulse(), ChangeWorld(), ItemsDispatcher::Close(), CreateBoozeeniadaString(), BulletObject::CreateBullet(), JumpBallObject::CreateBullet(), ClefObject::CreateClef(), DangerDataType::CreateDanger(), ParticleObject::CreateDirectParticle(), ParticleGenerator::CreateGenerator(), InsectUnit::CreateInsect(), WaterParticleObject::CreateParticle(), ParticleObject::CreateParticle(), VangerUnit::CreateParticleMechos(), SkyFarmerObject::CreateSkyFarmer(), StuffObject::CreateStuff(), ItemsDispatcher::CryptQuant(), dastPutSandOnMapAlt(), uvsVanger::destroy(), VangerUnit::Destroy(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroyBarellSpot(), VangerUnit::DestroyItem(), DestroySmooth(), DestroySmoothCheck(), DestroySmoothPut(), DestroySpot(), StuffObject::DeviceOut(), VangerUnit::DischargeItem(), TrackUnit::DrawMechosParticle(), VangerUnit::DrawMechosParticle(), uvsVanger::emuQuant(), uvsVanger::emuStep(), BulletObject::Event(), Particle::express(), FindFreeVanger(), DangerDataType::FireWork(), uvsWorld::generate_item(), EnterCenter::GetNearCenter(), uvsWorld::getRandSpot(), getRW(), uvsVanger::go_from_escave(), uvsVanger::go_from_spot(), uvsVanger::goCirt(), uvsVanger::goNewEscave(), uvsFlyFarmer::GrowCorn(), ActionUnit::HideAction(), VangerUnit::HideAction(), uvsVanger::homeArrival(), ActionDispatcher::Init(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), InsectList::Init(), VangerUnit::InitAI(), InitProtoCrypt(), LandSlideLine(), TntCreature::Load(), VangerUnit::MainOrderInit(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), dastPoly3D::make_mole(), uvsVanger::makeJump(), MLload(), StuffObject::NetEvent(), TntCreature::NetQuant(), ItemsDispatcher::Open(), uvsShop::prepare_list_for_ActInt(), ParticleMapProcess::process(), Particle::purge(), ParticleGenerator::Quant(), StuffObject::Quant(), HordeObject::Quant(), SkyFarmerObject::Quant(), FishWarrior::Quant(), GloryPlace::Quant(), VangerUnit::Quant(), VangerFunctionType::Quant(), TntCreature::Quant(), DangerDataType::Quant(), uvsFlyFarmer::Quant(), uvsDolly::Quant(), uvsVanger::Quant(), SimpleParticleType::QuantP(), uvsBunch::randVRes(), VangerUnit::ResolveGenerator(), VangerUnit::ResolveHandlerFind(), EnterCenter::Resort(), uvsShop::sellMechos(), VangerUnit::SensorQuant(), uvsFlyFarmer::setSpeed(), uvsDolly::setSpeed(), uvsVanger::spotArrival(), BulletObject::TimeOutQuant(), CheckPointEngine::Touch(), JumpBallObject::Touch(), InsectUnit::Touch(), VangerUnit::TouchSensor(), uvsWorld::updateResource(), uvsShop::updateResource(), uvsActIntSell(), uvsFlyFarmer::uvsFlyFarmer(), uvsGenerateItemForCrypt(), uvsKronDeleteItem(), uvsMakeNewGamerInEscave(), uvsShop::uvsShop(), xDestroySpot(), and xRestoreDestroySpot().
SIN()
int SIN (int x) inline
 { return SI[rPI(x)]; }
References rPI, and SI.
Referenced by CastArbitraryShadow(), and ParticleObject::CreateParticle().
Variable Documentation
_video
void* _video extern
Referenced by PerpSlopTurn(), and SlopTurnSkip().
clip_mask
uint clip_mask extern
clip_mask_x
const uint clip_mask_x = map_size_x - 1
Referenced by Object::basic_debris_analysis(), Object::basic_mechous_analysis(), cast_arbitrary_shadow_line(), cast_shadow_line(), check_double_level(), VariablePolygon::check_mole_submerging(), VariablePolygon::check_terrain_type(), color_line(), dastPutSandOnMapAlt(), dastPutSpriteOnMapAlt(), Object::destroy_double_level(), ExplosionObject::DrawQuant(), LightPoint::FourLightLine(), get_height(), get_three_heights(), get_upper_height(), Object::ground_pressing(), height_analysis_fish(), image_line(), InsectList::Init(), Object::insect_analysis(), LandSlideLine(), VariablePolygon::lower_average(), VariablePolygon::lower_average_z(), VangerUnit::MainOrderInit(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), dastPoly3D::make_mole(), MapLineTrace(), PerpSlopTurn(), Object::precise_impulse(), LightPoint::quant(), S2G(), vrtMap::scaling_3D(), section_prepare(), set_3D_adjust(), ParticleProcess::set_hot_spot(), shadow_line(), SlopTurnSkip(), square_analysis(), Object::test_whether_there_is_not_something_above(), InsectUnit::Touch(), TouchSphere(), TouchSphereZ(), transparency_line(), transparency_line_f(), vrtMap::turning(), and VariablePolygon::upper_average().
clip_mask_y
uint clip_mask_y extern
Referenced by Object::basic_debris_analysis(), Object::basic_mechous_analysis(), CastArbitraryShadow(), CastShadow(), check_double_level(), VariablePolygon::check_mole_submerging(), VariablePolygon::check_terrain_type(), color_line(), dastPutSandOnMapAlt(), dastPutSpriteOnMapAlt(), Object::destroy_double_level(), ExplosionObject::DrawQuant(), LightPoint::FourLightLine(), get_down_ground(), get_height(), get_real_ground(), get_three_heights(), get_up_ground(), get_upper_height(), Object::ground_pressing(), height_analysis_fish(), image_line(), InsectList::Init(), Object::insect_analysis(), VariablePolygon::lower_average(), VariablePolygon::lower_average_z(), VangerUnit::MainOrderInit(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), dastPoly3D::make_mole(), MapLineTrace(), PerpSlopTurn(), Object::precise_impulse(), LightPoint::quant(), S2G(), vrtMap::scaling_3D(), section_prepare(), set_3D_adjust(), ParticleProcess::set_hot_spot(), shadow_line(), SlopTurnSkip(), square_analysis(), Object::test_whether_there_is_not_something_above(), InsectUnit::Touch(), TouchSphere(), TouchSphereZ(), transparency_line(), transparency_line_f(), vrtMap::turning(), VariablePolygon::upper_average(), and YSetup().
CO
int* CO extern
Referenced by COS(), ItemsDispatcher::CryptQuant(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), ItemsDispatcher::Open(), PerpSlopTurn(), DangerDataType::Quant(), and SlopTurnSkip().
ColorShow
int ColorShow extern
iclip_mask_y
uint iclip_mask_y extern
locPI
const int locPI = PIx2/2
MAP_POWER_X
const uint MAP_POWER_X = 11
Referenced by ivrtMap::analyzeINI(), and show_map().
MAP_POWER_Y
uint MAP_POWER_Y extern
Referenced by vrtMap::delink(), vrtMap::increase(), vrtMap::link(), vrtMap::linkC(), vrtMap::request(), show_map(), and YSetup().
map_size_x
const uint map_size_x = 1 << MAP_POWER_X
Referenced by creat_poster(), vrtMap::dump_terrain(), iLINE_render(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), LINE_render(), vrtMap::load(), FishWarrior::Quant(), vrtMap::reload(), RenderPrepare(), Object::update_coord(), and YSetup().
map_size_y
uint map_size_y extern
Referenced by Object::basic_debris_analysis(), creat_poster(), GeneralSystemOpen(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), vrtMap::load(), Object::mechous_analysis(), NetworkWorldOpen(), FishWarrior::Quant(), vrtMap::reload(), Object::update_coord(), and YSetup().
mapFName
const char* mapFName extern
MAX_RADIUS
const int MAX_RADIUS = 48
Referenced by ilandPrepare(), PerpSlopTurn(), vrtMap::scaling(), vrtMap::scaling_3D(), SlopTurnSkip(), and vrtMap::turning().
palbuf
unsigned char* palbuf extern
palbufA
unsigned char * palbufA
palbufC
unsigned char * palbufC
PI
const int PI = PIx2/2
Referenced by aciSendEvent2itmdsp(), ActionUnit::Action(), VangerUnit::Action(), VangerUnit::AddFree(), addVanger(), calc_view_factors(), VangerUnit::CalcAiFactor(), ActionUnit::CalcTrackVector(), GunSlot::CheckTarget(), JumpBallObject::CreateBullet(), ParticleObject::CreateDirectParticle(), WaterParticleObject::CreateParticle(), ParticleObject::CreateParticle(), VangerUnit::CreateParticleMechos(), ParticleObject::CreateRingOfLord(), ItemsDispatcher::CryptQuant(), TntCreature::Destroy(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), ParticleObject::DrawQuant(), StuffObject::DrawQuant(), BulletObject::Event(), ActionUnit::HideAction(), InsectUnit::HideAction(), ActionDispatcher::Init(), FishWarriorList::Init(), ActionUnit::MixVector(), TntCreature::NetDestroy(), TntCreature::NetQuant(), ItemsDispatcher::Open(), HordeSource::Quant(), HordeObject::Quant(), FishWarrior::Quant(), ActionUnit::Quant(), VangerUnit::Quant(), VangerFunctionType::Quant(), TntCreature::Quant(), DangerDataType::Quant(), VangerUnit::ResolveGenerator(), VangerUnit::SensorQuant(), BulletObject::TimeOutQuant(), vrtMap::turning(), xDestroySpot(), and xRestoreDestroySpot().
PIx2
const int PIx2 = 1 << 12
Referenced by costab(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), and PerpSlopTurn().
RNDVAL
unsigned RNDVAL extern
Referenced by RND(), and xtInitApplication().
SHIFT
const int SHIFT = 16
SI
int* SI extern
Referenced by ItemsDispatcher::CryptQuant(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), ParticleObject::DrawQuant(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), ItemsDispatcher::Open(), PerpSlopTurn(), DangerDataType::Quant(), SIN(), SlopTurnSkip(), xDestroySpot(), and xRestoreDestroySpot().
TOR_POWER
const uint TOR_POWER = 1
Referenced by YSetup().
TOR_XSIZE
const uint TOR_XSIZE = TOR_POWER*map_size_x
Referenced by cycleTor(), LandSlideLine(), and EffectDispatcher::Quant().
TOR_YSIZE
uint TOR_YSIZE extern
Referenced by cycleTor(), EffectDispatcher::Quant(), StaticQuant(), and YSetup().
UNIT
const int UNIT = 0x10000
Referenced by calc_view_factors(), and costab().