Vangers: src/units/compas.h File Reference
compas.h File Reference
Functions
void AddTarget2Compas (int type, void *point, const char *head)
void SelectCompasTarget (const char *n)
char * GetCompasTarget (void)
void aciAdd2Targets (char *p)
void aciDeleteFromTargets (char *p)
void IncFuryFactor (void)
void DecFuryFactor (void)
Variables
const int CMP_TARGET_ESCAVE = 0
const int CMP_TARGET_SPOT = 1
const int CMP_TARGET_PASSAGE = 2
const int CMP_TARGET_ITEM = 3
const int CMP_TARGET_VANGER = 4
const int CMP_TARGET_SENSOR = 5
const int CMP_OBJECT_ESCAVE = 0
const int CMP_OBJECT_SPOT = 1
const int CMP_OBJECT_PASSAGE = 2
const int CMP_OBJECT_ITEM = 3
const int CMP_OBJECT_VANGER = 4
const int CMP_OBJECT_SENSOR = 5
const int CMP_OBJECT_PHANTOM = 6
const int CMP_OBJECT_VECTOR = 7
int GlobalFuryLevel
Function Documentation
aciAdd2Targets()
void aciAdd2Targets (char * p)
 {
     char* ptr;
     fncMenu* mn;
     fncMenuItem* itm;
     mn = aScrDisp -> get_menu(FMENU_TARGETS_MENU);
     if(!mn) return;
     itm = aScrDisp -> alloc_menu_item();
     itm -> init_name(p);
     itm -> font = FMENU_TARGETS_FONT;
     itm -> space = FMENU_TARGETS_SPACE;
     itm -> fnc_code = FMENU_OFF;
     itm -> init();
     mn -> add_item(itm);
     // rebuild...
     ptr = GetCompasTarget();
     if(ptr)
         mn -> curItem = mn -> get_obj(ptr);
     else
         mn -> curItem = mn -> get_obj(aciSTR_OFF);
     mn -> firstItem = mn -> curItem;
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aciSTR_OFF, aScrDisp, FMENU_OFF, FMENU_TARGETS_FONT, FMENU_TARGETS_MENU, FMENU_TARGETS_SPACE, GetCompasTarget(), and init_objects().
Referenced by CompasObject::AddTarget().
aciDeleteFromTargets()
void aciDeleteFromTargets (char * p)
 {
     char* ptr;
     fncMenu* mn;
     fncMenuItem* itm;
     mn = aScrDisp -> get_menu(FMENU_TARGETS_MENU);
     if(!mn) return;
     itm = mn -> get_obj(p);
     if(itm == mn -> curItem)
         SelectCompasTarget(NULL);
     if(itm){
         mn -> delete_obj(itm);
         aScrDisp -> free_menu_item(itm);
     }
     // rebuild...
     ptr = GetCompasTarget();
     if(ptr)
         mn -> curItem = mn -> get_obj(ptr);
     else
         mn -> curItem = mn -> get_obj(aciSTR_OFF);
     mn -> firstItem = mn -> curItem;
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aciSTR_OFF, aScrDisp, FMENU_TARGETS_MENU, GetCompasTarget(), init_objects(), NULL, and SelectCompasTarget().
Referenced by CompasObject::DeleteTarget().
AddTarget2Compas()
void AddTarget2Compas (int type, void * point, const char * head)
 {
     switch(type){
         case CMP_TARGET_ESCAVE:
             CompasObj.AddTarget(type,(uvsEscave*)(NULL),(char*)(point),head);
             break;
         case CMP_TARGET_SPOT:
             CompasObj.AddTarget(type,(uvsSpot*)(NULL),(char*)(point),head);
             break;
         case CMP_TARGET_PASSAGE:
             CompasObj.AddTarget(type,(uvsPassage*)(NULL),(char*)(point),head);
             break;
         case CMP_TARGET_SENSOR:
             CompasObj.AddTarget(type,(ActionUnit*)(NULL),(char*)(point),head);
             break;
     };
 };
References CompasObject::AddTarget(), CMP_TARGET_ESCAVE, CMP_TARGET_PASSAGE, CMP_TARGET_SENSOR, CMP_TARGET_SPOT, CompasObj, head, and NULL.
Referenced by GeneralSystemOpen().
DecFuryFactor()
void DecFuryFactor (void) inline
 {
     if(GlobalFuryLevel > 0) GlobalFuryLevel--;
 };
References GlobalFuryLevel.
GetCompasTarget()
char* GetCompasTarget (void)
 {
     if(CompasObj.CurrentTarget){
         return CompasObj.CurrentTarget->aciName;
     };
     return NULL;
 };
References CompasTargetType::aciName, CompasObj, CompasObject::CurrentTarget, and NULL.
Referenced by ActionDispatcher::PromptQuant().
IncFuryFactor()
void IncFuryFactor (void) inline
 {
     GlobalFuryLevel ++;
 };
References GlobalFuryLevel.
SelectCompasTarget()
void SelectCompasTarget (const char * n)
 {
     CompasTargetType* p;
     if(ActD.Active) ActD.Active->aiResolveFind.ClearResolve();
     if(!n){
         CompasObj.CurrentTarget = NULL;
         return;
     };
     p = CompasObj.TargetData;
     while(p){
         if(!strcmp(n,p->aciName)){
             CompasObj.CurrentTarget = p;
             return;
         };
         p = p->Next;
     };
     CompasObj.CurrentTarget = NULL;
 };
References CompasTargetType::aciName, ActD, ActionDispatcher::Active, VangerUnit::aiResolveFind, aiResolveList::ClearResolve(), CompasObj, CompasObject::CurrentTarget, CompasTargetType::Next, NULL, and CompasObject::TargetData.
Referenced by ClearPhantomTarget(), ClearTabutaskTarget(), CreatePhantomTarget(), CreateTabutaskTarget(), DeleteArtefactTarget(), and ActionDispatcher::PromptQuant().
Variable Documentation
CMP_OBJECT_ESCAVE
const int CMP_OBJECT_ESCAVE = 0
Referenced by VangerUnit::GamerOrderInit(), CompasObject::Open(), and CompasObject::Quant().
CMP_OBJECT_ITEM
const int CMP_OBJECT_ITEM = 3
Referenced by CreateArtefactTarget(), and DeleteArtefactTarget().
CMP_OBJECT_PASSAGE
const int CMP_OBJECT_PASSAGE = 2
Referenced by VangerUnit::GamerOrderInit(), and CompasObject::Quant().
CMP_OBJECT_PHANTOM
const int CMP_OBJECT_PHANTOM = 6
Referenced by AddPhantomTarget(), ClearPhantomTarget(), and CompasObject::Quant().
CMP_OBJECT_SENSOR
const int CMP_OBJECT_SENSOR = 5
Referenced by VangerUnit::GamerOrderInit(), and CompasObject::Quant().
CMP_OBJECT_SPOT
const int CMP_OBJECT_SPOT = 1
Referenced by VangerUnit::GamerOrderInit(), and CompasObject::Quant().
CMP_OBJECT_VANGER
const int CMP_OBJECT_VANGER = 4
Referenced by ClearTabutaskTarget(), and CreateTabutaskTarget().
CMP_OBJECT_VECTOR
const int CMP_OBJECT_VECTOR = 7
Referenced by CreatePhantomTarget().
CMP_TARGET_ESCAVE
const int CMP_TARGET_ESCAVE = 0
Referenced by AddTarget2Compas(), GeneralSystemOpen(), and CompasObject::Open().
CMP_TARGET_ITEM
const int CMP_TARGET_ITEM = 3
CMP_TARGET_PASSAGE
const int CMP_TARGET_PASSAGE = 2
Referenced by AddTarget2Compas(), and GeneralSystemOpen().
CMP_TARGET_SENSOR
const int CMP_TARGET_SENSOR = 5
Referenced by AddTarget2Compas(), and GeneralSystemOpen().
CMP_TARGET_SPOT
const int CMP_TARGET_SPOT = 1
Referenced by AddTarget2Compas(), and GeneralSystemOpen().
CMP_TARGET_VANGER
const int CMP_TARGET_VANGER = 4
GlobalFuryLevel
int GlobalFuryLevel extern
Referenced by VangerUnit::CalcAiFactor(), DecFuryFactor(), GeneralSystemLoad(), GeneralSystemSave(), IncFuryFactor(), and ActionDispatcher::Init().