Vangers: src/iscreen/controls.h File Reference
controls.h File Reference
Macros
#define iKEY_OBJECT_SIZE 2
Enumerations
enum iControlID {
iKEY_TURN_WHEELS_LEFT = 1, iKEY_TURN_WHEELS_RIGHT, iKEY_MOVE_FORWARD, iKEY_MOVE_BACKWARD,
iKEY_TURN_OVER_LEFT, iKEY_TURN_OVER_RIGHT, iKEY_DEVICE_ON, iKEY_DEVICE_OFF,
iKEY_ACTIVATE_KID, iKEY_ACCELERATION, iKEY_VERTICAL_THRUST, iKEY_INVENTORY,
iKEY_OPEN, iKEY_FIRE_WEAPON1, iKEY_FIRE_WEAPON2, iKEY_FIRE_WEAPON3,
iKEY_FIRE_WEAPON4, iKEY_FIRE_ALL_WEAPONS, iKEY_CHANGE_TARGET, iKEY_FULLSCREEN,
iKEY_REDUCE_VIEW, iKEY_ENLARGE_VIEW, iKEY_ROTATION, iKEY_AUTO_ZOOM,
iKEY_AUTO_TILT, iKEY_ZOOM_IN, iKEY_ZOOM_OUT, iKEY_ZOOM_STANDART,
iKEY_HANDBRAKE, iKEY_USE_GLUEK, iKEY_JOYSTICK_SWITCH, iKEY_SKIP_TEXT,
iKEY_USE_VECTOR, iKEY_FRAG_INFO, iKEY_CHAT, iKEY_EXIT,
iKEY_SCREENSHOT, iKEY_MAX_ID
}
Functions
int iGetKeyID (int key)
int iKeyPressed (int id)
int iCheckKeyID (int id, int key)
void iInitControls (void)
void iResetControls (void)
void iInitControlObjects (void)
void iSetControlCode (int id, int key, int num=0)
void iResetControlCode (int id, int num=0)
int iGetControlCode (int id, int num=0)
char * iGetJoystickButtonName (int vkey)
char * iGetMouseButtonName (int vkey)
Macro Definition Documentation
iKEY_OBJECT_SIZE
#define iKEY_OBJECT_SIZE 2
Enumeration Type Documentation
iControlID
enum iControlID
Enumerator
iKEY_TURN_WHEELS_LEFT
iKEY_TURN_WHEELS_RIGHT
iKEY_MOVE_FORWARD
iKEY_MOVE_BACKWARD
iKEY_TURN_OVER_LEFT
iKEY_TURN_OVER_RIGHT
iKEY_DEVICE_ON
iKEY_DEVICE_OFF
iKEY_ACTIVATE_KID
iKEY_ACCELERATION
iKEY_VERTICAL_THRUST
iKEY_INVENTORY
iKEY_OPEN
iKEY_FIRE_WEAPON1
iKEY_FIRE_WEAPON2
iKEY_FIRE_WEAPON3
iKEY_FIRE_WEAPON4
iKEY_FIRE_ALL_WEAPONS
iKEY_CHANGE_TARGET
iKEY_FULLSCREEN
iKEY_REDUCE_VIEW
iKEY_ENLARGE_VIEW
iKEY_ROTATION
iKEY_AUTO_ZOOM
iKEY_AUTO_TILT
iKEY_ZOOM_IN
iKEY_ZOOM_OUT
iKEY_ZOOM_STANDART
iKEY_HANDBRAKE
iKEY_USE_GLUEK
iKEY_JOYSTICK_SWITCH
iKEY_SKIP_TEXT
iKEY_USE_VECTOR
iKEY_FRAG_INFO
iKEY_CHAT
iKEY_EXIT
iKEY_SCREENSHOT
iKEY_MAX_ID
                 {
     iKEY_TURN_WHEELS_LEFT   = 1,
     iKEY_TURN_WHEELS_RIGHT,     // 2
     iKEY_MOVE_FORWARD,      // 3
     iKEY_MOVE_BACKWARD,     // 4
     iKEY_TURN_OVER_LEFT,        // 5
     iKEY_TURN_OVER_RIGHT,       // 6
     iKEY_DEVICE_ON,         // 7
     iKEY_DEVICE_OFF,        // 8
     iKEY_ACTIVATE_KID,      // 9
     iKEY_ACCELERATION,      // 10
     iKEY_VERTICAL_THRUST,       // 11
     iKEY_INVENTORY,         // 12
     iKEY_OPEN,          // 13
     iKEY_FIRE_WEAPON1,      // 14
     iKEY_FIRE_WEAPON2,      // 15
     iKEY_FIRE_WEAPON3,      // 16
     iKEY_FIRE_WEAPON4,      // 17
     iKEY_FIRE_ALL_WEAPONS,      // 18
     iKEY_CHANGE_TARGET,     // 19
     iKEY_FULLSCREEN,        // 20
     iKEY_REDUCE_VIEW,       // 21
     iKEY_ENLARGE_VIEW,      // 22
     iKEY_ROTATION,          // 23
     iKEY_AUTO_ZOOM,         // 24
     iKEY_AUTO_TILT,         // 25
     iKEY_ZOOM_IN,           // 26
     iKEY_ZOOM_OUT,          // 27
     iKEY_ZOOM_STANDART,     // 28
     iKEY_HANDBRAKE,         // 29
     iKEY_USE_GLUEK,         // 30
     iKEY_JOYSTICK_SWITCH,       // 31
     iKEY_SKIP_TEXT,         // 32
     iKEY_USE_VECTOR,        // 33
     iKEY_FRAG_INFO,         // 34
     iKEY_CHAT,          // 35
     iKEY_EXIT,          // 36
     iKEY_SCREENSHOT,            // 37
     iKEY_MAX_ID
 };
Function Documentation
iCheckKeyID()
int iCheckKeyID (int id, int key)
 {
     if(iControlsObj)
         return iControlsObj -> CheckID(id,key);
     return 0;
 }
References iControlsObj, and key().
Referenced by iChatKeyQuant(), and actIntDispatcher::KeyQuant().
iGetControlCode()
int iGetControlCode (int id, int num = 0)
 {
     if(iControlsObj)
         return iControlsObj -> getCode(id,num);
     return 0;
 }
References iControlsObj.
Referenced by iDeleteControl(), iHandleExtEvent(), iInitControlObjects(), and aButton::init().
iGetJoystickButtonName()
char* iGetJoystickButtonName (int vkey)
 {
     return NULL;
 }
References NULL.
iGetKeyID()
int iGetKeyID (int key)
 {
     if(iControlsObj)
         return iControlsObj -> GetID(key);
     return -1;
 }
References iControlsObj, and key().
iGetMouseButtonName()
char* iGetMouseButtonName (int vkey)
iInitControlObjects()
void iInitControlObjects (void)
 {
     //std::cout<<"iInitControlObjects"<<std::endl;
     int i,j,key,index;
     const char* str;
     iScreenObject* obj;
     for(i = 0; i < iKEY_MAX_ID; i ++){
         for(j = 0; j < iKEY_OBJECT_SIZE; j ++){
             index = i * iKEY_OBJECT_SIZE + j;
             if(iControlsStr[index]) {
                 key = iGetControlCode(i, j);
                 //NEED Full Rewrite
                 /*if(!(key & iJOYSTICK_MASK)){
                     str = iGetKeyNameText(key,lang());
                 }
                 else {
                     str = iGetJoyBtnNameText(key,lang());
                 }*/
                 str = iGetKeyNameText(key, lang(), true);
                 if (str) {
                     if(strcasecmp(iControlsStr[index]->string,str)) {
                         strcpy(iControlsStr[index]->string,str);
                         obj = (iScreenObject*)iControlsStr[index] -> owner;
                         obj -> flags |= OBJ_REINIT;
                         obj -> flags |= OBJ_MUST_REDRAW;
                     }
                 } else {
                     if(strcasecmp(iControlsStr[index] -> string,iSTR_NONE)) {
                         strcpy(iControlsStr[index] -> string,iSTR_NONE);
                         obj = (iScreenObject*)iControlsStr[index] -> owner;
                         obj -> flags |= OBJ_REINIT;
                         obj -> flags |= OBJ_MUST_REDRAW;
                     }
                 }
             }
         }
     }
 }
References iControlsStr, iGetControlCode(), iGetKeyNameText(), iKEY_MAX_ID, iKEY_OBJECT_SIZE, key(), and lang().
iInitControls()
void iInitControls (void)
 {
     if(!iControlsObj){
         iControlsObj = new iKeyControls;
         iControlsObj -> init();
     }
 }
References iControlsObj.
Referenced by iPreInitFirst(), and iQuantFirst().
iKeyPressed()
int iKeyPressed (int id)
 {
     int i,code, state = 0;
     SDL_Joystick *joy = get_joystick();
     SDL_GameController *ctrl = get_gamecontroller();
     if(!iControlsObj) return 0;
     for(i = 0; i < iKEY_OBJECT_SIZE; i ++){
         code = iControlsObj->getCode(id, i);
         //std::cout<<"iKeyPressed code:"<<(int)code<<" id:"<<id<<" i:"<<i<<std::endl;
         if(code) {
             if (code & SDLK_JOYSTICK_BUTTON_MASK && joy) {
                 state = SDL_JoystickGetButton(joy, code ^ SDLK_JOYSTICK_BUTTON_MASK);
             } else if (code & SDLK_GAMECONTROLLER_BUTTON_MASK && ctrl) {
                 state = SDL_GameControllerGetButton(ctrl, (SDL_GameControllerButton)(code ^ SDLK_GAMECONTROLLER_BUTTON_MASK));
             } else if (code & SDLK_JOYSTICK_HAT_MASK && joy) {
                 state = SDL_JoystickGetHat(joy, (code ^ SDLK_JOYSTICK_HAT_MASK) / 10 ) == (code ^ SDLK_JOYSTICK_HAT_MASK) % 10;
             } else if (code & SDLK_SCANCODE_MASK) {
                 state = SDL_GetKeyboardState(NULL)[SDL_GetScancodeFromKey(code)];
             } else {
                 state = SDL_GetKeyboardState(NULL)[code];
             }
             if (state) {
                 return state;
             }
         }
     }
     return 0;
 }
References ctrl, get_gamecontroller(), get_joystick(), iKeyControls::getCode(), iControlsObj, iKEY_OBJECT_SIZE, joy, NULL, SDLK_GAMECONTROLLER_BUTTON_MASK, SDLK_JOYSTICK_BUTTON_MASK, and SDLK_JOYSTICK_HAT_MASK.
Referenced by Object::direct_keyboard_control(), actIntDispatcher::flush(), KeyCenter(), and VangerUnit::NewKeyHandler().
iResetControlCode()
void iResetControlCode (int id, int num = 0)
 {
     if(iControlsObj)
         iControlsObj -> removeCode(id,num);
 }
References iControlsObj.
Referenced by iDeleteControlKey().
iResetControls()
void iResetControls (void)
 {
     if(iControlsObj)
         iControlsObj -> reset();
 }
References iControlsObj.
iSetControlCode()
void iSetControlCode (int id, int key, int num = 0)
 {
     if(iControlsObj)
         iControlsObj -> addCode(id,key,num);
 }
References iControlsObj, and key().
Referenced by iDeleteControl(), and iInitControlKey().