Vangers: src/iscreen/controls.cpp File Reference
controls.cpp File Reference
#include "../global.h"
#include "../xjoystick.h"
#include "hfont.h"
#include "iscreen.h"
#include "ikeys.h"
#include "controls.h"
Classes
struct iKeyControls
Macros
#define iKEY_NO_RESET 0x01
Functions
void iInitControlObjects (void)
void iInitControls (void)
int iGetKeyID (int key)
int iCheckKeyID (int id, int key)
void iSetControlCode (int id, int key, int num)
void iResetControlCode (int id, int num)
int iGetControlCode (int id, int num)
void iResetControls (void)
void iSaveControls (void)
void iLoadControls (void)
int iKeyPressed (int id)
char * iGetJoystickButtonName (int vkey)
Variables
int RecorderMode
int iKeyFirstInit = 0
iKeyControls * iControlsObj = NULL
Macro Definition Documentation
iKEY_NO_RESET
#define iKEY_NO_RESET 0x01
Function Documentation
iCheckKeyID()
int iCheckKeyID (int id, int key)
 {
     if(iControlsObj)
         return iControlsObj -> CheckID(id,key);
     return 0;
 }
References iControlsObj, and key().
Referenced by iChatKeyQuant(), and actIntDispatcher::KeyQuant().
iGetControlCode()
int iGetControlCode (int id, int num)
 {
     if(iControlsObj)
         return iControlsObj -> getCode(id,num);
     return 0;
 }
References iControlsObj.
Referenced by iDeleteControl(), iHandleExtEvent(), iInitControlObjects(), and aButton::init().
iGetJoystickButtonName()
char* iGetJoystickButtonName (int vkey)
 {
     return NULL;
 }
References NULL.
iGetKeyID()
int iGetKeyID (int key)
 {
     if(iControlsObj)
         return iControlsObj -> GetID(key);
     return -1;
 }
References iControlsObj, and key().
iInitControlObjects()
void iInitControlObjects (void)
 {
     //std::cout<<"iInitControlObjects"<<std::endl;
     int i,j,key,index;
     const char* str;
     iScreenObject* obj;
     for(i = 0; i < iKEY_MAX_ID; i ++){
         for(j = 0; j < iKEY_OBJECT_SIZE; j ++){
             index = i * iKEY_OBJECT_SIZE + j;
             if(iControlsStr[index]) {
                 key = iGetControlCode(i, j);
                 //NEED Full Rewrite
                 /*if(!(key & iJOYSTICK_MASK)){
                     str = iGetKeyNameText(key,lang());
                 }
                 else {
                     str = iGetJoyBtnNameText(key,lang());
                 }*/
                 str = iGetKeyNameText(key, lang(), true);
                 if (str) {
                     if(strcasecmp(iControlsStr[index]->string,str)) {
                         strcpy(iControlsStr[index]->string,str);
                         obj = (iScreenObject*)iControlsStr[index] -> owner;
                         obj -> flags |= OBJ_REINIT;
                         obj -> flags |= OBJ_MUST_REDRAW;
                     }
                 } else {
                     if(strcasecmp(iControlsStr[index] -> string,iSTR_NONE)) {
                         strcpy(iControlsStr[index] -> string,iSTR_NONE);
                         obj = (iScreenObject*)iControlsStr[index] -> owner;
                         obj -> flags |= OBJ_REINIT;
                         obj -> flags |= OBJ_MUST_REDRAW;
                     }
                 }
             }
         }
     }
 }
Referenced by iLoadControls(), and iQuantFirst().
iInitControls()
void iInitControls (void)
 {
     if(!iControlsObj){
         iControlsObj = new iKeyControls;
         iControlsObj -> init();
     }
 }
References iControlsObj.
Referenced by iPreInitFirst(), and iQuantFirst().
iKeyPressed()
int iKeyPressed (int id)
 {
     int i,code, state = 0;
     SDL_Joystick *joy = get_joystick();
     SDL_GameController *ctrl = get_gamecontroller();
     if(!iControlsObj) return 0;
     for(i = 0; i < iKEY_OBJECT_SIZE; i ++){
         code = iControlsObj->getCode(id, i);
         //std::cout<<"iKeyPressed code:"<<(int)code<<" id:"<<id<<" i:"<<i<<std::endl;
         if(code) {
             if (code & SDLK_JOYSTICK_BUTTON_MASK && joy) {
                 state = SDL_JoystickGetButton(joy, code ^ SDLK_JOYSTICK_BUTTON_MASK);
             } else if (code & SDLK_GAMECONTROLLER_BUTTON_MASK && ctrl) {
                 state = SDL_GameControllerGetButton(ctrl, (SDL_GameControllerButton)(code ^ SDLK_GAMECONTROLLER_BUTTON_MASK));
             } else if (code & SDLK_JOYSTICK_HAT_MASK && joy) {
                 state = SDL_JoystickGetHat(joy, (code ^ SDLK_JOYSTICK_HAT_MASK) / 10 ) == (code ^ SDLK_JOYSTICK_HAT_MASK) % 10;
             } else if (code & SDLK_SCANCODE_MASK) {
                 state = SDL_GetKeyboardState(NULL)[SDL_GetScancodeFromKey(code)];
             } else {
                 state = SDL_GetKeyboardState(NULL)[code];
             }
             if (state) {
                 return state;
             }
         }
     }
     return 0;
 }
References ctrl, get_gamecontroller(), get_joystick(), iKeyControls::getCode(), iControlsObj, iKEY_OBJECT_SIZE, joy, NULL, SDLK_GAMECONTROLLER_BUTTON_MASK, SDLK_JOYSTICK_BUTTON_MASK, and SDLK_JOYSTICK_HAT_MASK.
Referenced by Object::direct_keyboard_control(), actIntDispatcher::flush(), KeyCenter(), and VangerUnit::NewKeyHandler().
iLoadControls()
void iLoadControls (void)
 {
     int sz0,sz1;
     if(!iControlsObj || RecorderMode) return;
     XStream fh(0);
     if(!fh.open("controls.dat",XS_IN)) return;
     fh > sz0 > sz1;
     if(sz0 != iKEY_MAX_ID || sz1 != iKEY_OBJECT_SIZE){
         fh.close();
         return;
     }
     fh.read(iControlsObj -> keyCodes,iKEY_OBJECT_SIZE * iKEY_MAX_ID * sizeof(int));
     fh.close();
     iInitControlObjects();
 }
References XStream::close(), iControlsObj, iInitControlObjects(), iKEY_MAX_ID, iKEY_OBJECT_SIZE, XStream::open(), XStream::read(), RecorderMode, and XS_IN.
Referenced by iQuantFirst().
iResetControlCode()
void iResetControlCode (int id, int num)
 {
     if(iControlsObj)
         iControlsObj -> removeCode(id,num);
 }
References iControlsObj.
Referenced by iDeleteControlKey().
iResetControls()
void iResetControls (void)
 {
     if(iControlsObj)
         iControlsObj -> reset();
 }
References iControlsObj.
iSaveControls()
void iSaveControls (void)
 {
     if(!iControlsObj || RecorderMode) return;
     XStream fh("controls.dat",XS_OUT);
     fh < (int)iKEY_MAX_ID < (int)iKEY_OBJECT_SIZE;
     fh.write(iControlsObj -> keyCodes,iKEY_OBJECT_SIZE * iKEY_MAX_ID * sizeof(int));
     fh.close();
 }
References XStream::close(), iControlsObj, iKEY_MAX_ID, iKEY_OBJECT_SIZE, RecorderMode, XStream::write(), and XS_OUT.
iSetControlCode()
void iSetControlCode (int id, int key, int num)
 {
     if(iControlsObj)
         iControlsObj -> addCode(id,key,num);
 }
References iControlsObj, and key().
Referenced by iDeleteControl(), and iInitControlKey().
Variable Documentation
iControlsObj
iKeyControls* iControlsObj = NULL
Referenced by iCheckKeyID(), iGetControlCode(), iGetKeyID(), iInitControls(), iKeyPressed(), iLoadControls(), iResetControlCode(), iResetControls(), iSaveControls(), and iSetControlCode().
iKeyFirstInit
int iKeyFirstInit = 0
Referenced by iKeyControls::reset().
RecorderMode
int RecorderMode extern
Referenced by iLoadControls(), and iSaveControls().