Vangers: src/actint/credits.h File Reference
credits.h File Reference
Functions
int aciGetCurCredits (void)
void aciUpdateCurCredits (int val)
Variables
int aciCurCredits00
int aciCurCredits01
int aciCurCredits02
int aciCurCredits03
int aciCurCredits04
int aciCurCredits05
int aciCurCredits06
int aciCurCredits07
Function Documentation
aciGetCurCredits()
int aciGetCurCredits (void) inline
 {
     return   aciCurCredits00    |
         (aciCurCredits01 << 4)  |
         (aciCurCredits02 << 8)  |
         (aciCurCredits03 << 12) |
         (aciCurCredits04 << 16) |
         (aciCurCredits05 << 20) |
         (aciCurCredits06 << 24) |
         (aciCurCredits07 << 28);
 };
References aciCurCredits00, aciCurCredits01, aciCurCredits02, aciCurCredits03, aciCurCredits04, aciCurCredits05, aciCurCredits06, and aciCurCredits07.
Referenced by aciCHandler(), aciCheckCredits(), aciCheckItemCredits(), aciPay4Item(), aciSell_Matrix(), uvsVanger::checkDolly(), ActionDispatcher::CreateActive(), actIntDispatcher::inv_mouse_imove_quant(), uvsVanger::prepare_list_for_ActInt(), uvsVanger::race_result(), CounterPanel::redraw(), actIntDispatcher::save_data(), actIntDispatcher::swap_matrices(), uvsgetDGdata(), and uvsMakeNewGamerInEscave().
aciUpdateCurCredits()
void aciUpdateCurCredits (int val) inline
 {
     aciCurCredits00 = val & 0x0F;
     aciCurCredits01 = (val >> 4) & 0x0F;
     aciCurCredits02 = (val >> 8) & 0x0F;
     aciCurCredits03 = (val >> 12) & 0x0F;
     aciCurCredits04 = (val >> 16) & 0x0F;
     aciCurCredits05 = (val >> 20) & 0x0F;
     aciCurCredits06 = (val >> 24) & 0x0F;
     aciCurCredits07 = (val >> 28) & 0x0F;
 };
References aciCurCredits00, aciCurCredits01, aciCurCredits02, aciCurCredits03, aciCurCredits04, aciCurCredits05, aciCurCredits06, and aciCurCredits07.
Referenced by aciCHandler(), aciPay4Item(), aciSell_Matrix(), VangerUnit::ChangeVangerProcess(), uvsVanger::checkDolly(), VangerUnit::CreateVangerUnit(), actIntDispatcher::load_data(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsVanger::race_result(), actIntDispatcher::swap_matrices(), and uvsMakeNewGamerInEscave().
Variable Documentation
aciCurCredits00
int aciCurCredits00 extern
Referenced by aciGetCurCredits(), aciUpdateCurCredits(), and CounterPanel::init().
aciCurCredits01
int aciCurCredits01 extern
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurCredits02
int aciCurCredits02 extern
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurCredits03
int aciCurCredits03 extern
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurCredits04
int aciCurCredits04 extern
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurCredits05
int aciCurCredits05 extern
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurCredits06
int aciCurCredits06 extern
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciCurCredits07
int aciCurCredits07 extern
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().