Vangers: src/uvs/diagen.cpp File Reference
diagen.cpp File Reference
#include "../global.h"
#include "../lang.h"
#include "../common.h"
#include "diagen.h"
#include "../actint/mlconsts.h"
#include "../actint/credits.h"
#include "../3d/parser.h"
#include "../units/uvsapi.h"
#include "../units/compas.h"
#include "univang.h"
Classes
struct FileBox
union dual_char
struct Q
struct Q2
struct Q3
struct CMD
struct Q4
Macros
#define STARTUP_TESTING
#define SAVE_SINGE_LANGUAGE
#define SINGLE_LANGUAGE
#define DGF_NONE 0
#define DGF_DUAL 1
#define SUBJ_SYMBOL '['
#define SUBJ_SYMBOL_RIGHT ']'
#define LINK_SYMBOL '{'
#define LINK_SYMBOL_RIGHT '}'
#define COMMAND_SYMBOL '@'
Functions
void dg_SendEvent (int code)
void aciOpenWorldLink (int, int)
void uvsSetTownName (const char *_name_)
char * uvsGetLarvaWorld (int n)
int uvsgetDGdata (int code)
int getPreviousCycle (int cycle)
int isCycleExist (int cycle, char ew=0)
int getWorldVisitStats (char wc)
int getPassangerStats (char efrom, char wto)
int getPassangerFrom (char efrom)
char * StringOfBoozeeniada (void)
int getSpobsState (void)
int getThreallState (void)
void addInfernalsKill2Protractor (void)
void addSpectorsKill2Messiah (void)
int isSpummyDeath (void)
void OpenCrypt (int world, int id)
void uvsBoorawchickZero (void)
int aciWorldLinkExist (int w1, int w2, int flag=0)
void uvsLuckChange (int val)
void dgLog (char *string)
void dataList (int val=-1)
void loadList (void)
void saveList (void)
void showmap (void)
const char * DiagenTextName ()
char * ConvertUTF8 (const char *s, int back=0)
char * Convert (const char *s, int back=0)
std::string cp866_to_cp1251 (std::string in)
std::string cp1251_to_utf8 (std::string in_string)
char * getDGname (const char *name, const char *ext)
char * getSubj (char *p, int &m)
char * getSubj (char *p)
void cutLink (char *&p)
int Comparision (char *opr, int a, int b)
void diagenPrepare (void)
int getSpectorsTaskStatus (void)
int getInfernalsTaskStatus (void)
bool ISEALPHA (char c)
char * detect_text (char *ret)
void dgInThreall (void)
void dgOutThreall (void)
char * dgGetThreallPhrase (void)
Variables
int RACE_WAIT
int aciEscaveDead
int aciEscaveEmpty
int NetworkON
int uvsCurrentWorldUnableBefore
uvsGamerResult GamerResult
const int saveVersion = 3
int MP_GAME = 0
DiagenDispatcher * dgD
int dgMood
int dgAbortStatus
struct Q2 Query []
struct Q3 ArgData []
struct Q4 CmdData []
Macro Definition Documentation
COMMAND_SYMBOL
#define COMMAND_SYMBOL '@'
DGF_DUAL
#define DGF_DUAL 1
DGF_NONE
#define DGF_NONE 0
LINK_SYMBOL
#define LINK_SYMBOL '{'
LINK_SYMBOL_RIGHT
#define LINK_SYMBOL_RIGHT '}'
SAVE_SINGE_LANGUAGE
#define SAVE_SINGE_LANGUAGE
SINGLE_LANGUAGE
#define SINGLE_LANGUAGE
STARTUP_TESTING
#define STARTUP_TESTING
SUBJ_SYMBOL
#define SUBJ_SYMBOL '['
SUBJ_SYMBOL_RIGHT
#define SUBJ_SYMBOL_RIGHT ']'
Function Documentation
aciOpenWorldLink()
void aciOpenWorldLink (int , int)
 {
     int id1,id2;
     aciWorldInfo* p1,*p2;
     id1 = aScrDisp -> wMap -> world_ids[w1];
     id2 = aScrDisp -> wMap -> world_ids[w2];
     if(id1 == -1 || id2 == -1) ErrH.Abort("Bad world ID...");
     p1 = aScrDisp -> wMap -> world_ptr[id1];
     p2 = aScrDisp -> wMap -> world_ptr[id2];
     if(!p1 || !p2) ErrH.Abort("Bad world ptr...");
     p1 -> links[id2] = 1;
     if(id1 != id2 && p2 -> links[id1]) p2 -> links[id1] = 0;
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
     aciPrevJumpCount = -1;
 }
References XErrorHandler::Abort(), aScrDisp, ErrH, and wMap.
Referenced by NetworkWorldOpen(), and StuffObject::Quant().
aciWorldLinkExist()
int aciWorldLinkExist (int w1, int w2, int flag = 0)
 {
     int id1,id2;
     aciWorldInfo* p1,*p2;
     id1 = aScrDisp -> wMap -> world_ids[w1];
     id2 = aScrDisp -> wMap -> world_ids[w2];
     if(id1 == -1 || id2 == -1) ErrH.Abort("Bad world ID...");
     p1 = aScrDisp -> wMap -> world_ptr[id1];
     p2 = aScrDisp -> wMap -> world_ptr[id2];
     if(!p1 || !p2) ErrH.Abort("Bad world ptr...");
     if(p1 -> links[id2] || p2 -> links[id1]){
         if(!sp_flag || (p1 -> flags & AS_ACCESSIBLE_WORLD || p2 -> flags & AS_ACCESSIBLE_WORLD)){
             return 1;
         }
     }
     return 0;
 }
References XErrorHandler::Abort(), aScrDisp, ErrH, and wMap.
Referenced by aiMessageTouch(), ItemsDispatcher::Close(), uvsTabuTaskType::is_able(), ActionDispatcher::PromptQuant(), VangerUnit::SensorQuant(), and uvsSecretON().
addInfernalsKill2Protractor()
void addInfernalsKill2Protractor (void)
 {
     ActD.ThreallDestroyActive = 1;
     aciActivateItemFunction(ACI_PROTRACTOR,ACI_PROTRACTOR_EVENT8);
 };
References ACI_PROTRACTOR, ACI_PROTRACTOR_EVENT8, aciActivateItemFunction(), ActD, and ActionDispatcher::ThreallDestroyActive.
addSpectorsKill2Messiah()
void addSpectorsKill2Messiah (void)
 {
     ActD.SpobsDestroyActive = 1;
     aciActivateItemFunction(ACI_MECHANIC_MESSIAH,ACI_MECH_MESSIAH_EVENT6);
 };
References ACI_MECH_MESSIAH_EVENT6, ACI_MECHANIC_MESSIAH, aciActivateItemFunction(), ActD, and ActionDispatcher::SpobsDestroyActive.
Comparision()
int Comparision (char * opr, int a, int b)
 {
     char mss[] = "Wrong operation";
     switch(*opr){
         case '=':
             switch(*(opr + 1)){
                 case '=': return a == b;
                 default: ErrH.Abort(mss);
                 }
         case '>':
             switch(*(opr + 1)){
                 case '=': return a >= b;
                 case '\0': return a > b;
                 default: ErrH.Abort(mss);
                 }
         case '<':
             switch(*(opr + 1)){
                 case '=': return a <= b;
                 case '\0': return a < b;
                 default: ErrH.Abort(mss);
                 }
         default:
             ErrH.Abort(mss);
         }
     return 0;
 }
References XErrorHandler::Abort(), and ErrH.
Referenced by dgCell::analyzeACCESS().
Convert()
char* Convert (const char * s, int back = 0)
{
     if(!(lang() == RUSSIAN)) {
         char* buffer = NULL;
         int len = strlen(s)+1;
         buffer = new char[len + 2];
         memset(buffer, 0, len+2);
         strcpy(buffer, s);
         return buffer;
     }
     static int len = 0;
     static char* buffer = NULL;
     len = strlen(s)+1;
     buffer = new char[len + 2];
     memset(buffer, 0, len+2);
     int i;
     if (!back) {
         for (i=0;i<len;i++) {
             if ((unsigned char)s[i]>=192&&(unsigned char)s[i]<=239)
                 buffer[i]=(char)((unsigned char)s[i]-64);
             else if ((unsigned char)s[i]>=240&&(unsigned char)s[i]<=255)
                 buffer[i]=(char)((unsigned char)s[i]-16);
             else if ((unsigned char)s[i]==184)
                 buffer[i]=(char)((unsigned char)241); //
             else if ((unsigned char)s[i]==168)
                 buffer[i]=(char)((unsigned char)240); //
             else if ((unsigned char)s[i]==185)
                 buffer[i]=(char)((unsigned char)252); //
             else if ((unsigned char)s[i]<128)
                 buffer[i]=s[i];
             else
                 buffer[i]=' ';
         }
     } else {
         for (i=0;i<len;i++) {
             if ((unsigned char)s[i]>=128&&(unsigned char)s[i]<=175)
                 buffer[i]=(char)((unsigned char)s[i]+64);
             else if ((unsigned char)s[i]>=224&&(unsigned char)s[i]<=239)
                 buffer[i]=(char)((unsigned char)s[i]+16);
             else if ((unsigned char)s[i]==241)
                 buffer[i]=(char)((unsigned char)184); //
             else if ((unsigned char)s[i]==240)
                 buffer[i]=(char)((unsigned char)168); //
             else if ((unsigned char)s[i]==252)
                 buffer[i]=(char)((unsigned char)185); //
             else if ((unsigned char)s[i]<128)
                 buffer[i]=s[i];
             else
                 buffer[i]=' ';
         }
     }
     return buffer;
 }
References lang(), NULL, and RUSSIAN.
Referenced by DiagenDispatcher::findQfirst(), DiagenDispatcher::findQnext(), DiagenDispatcher::getAnswer(), DiagenDispatcher::getInvText(), DiagenDispatcher::getQblock(), DiagenDispatcher::getQdead(), DiagenDispatcher::getQempty(), DiagenDispatcher::getQout(), DiagenDispatcher::getQpostfix(), and DiagenDispatcher::getQprefix().
ConvertUTF8()
char* ConvertUTF8 (const char * s, int back = 0)
{
     static char* buffer = NULL;
     int len = strlen(s);
     buffer = new char[len+2];
     memset( buffer, 0, len+2);
     dual_char dc;
     bool get_dual=false;
     int i_dual_char=0, i;
     if (!back)
         for (i=0;i<len;i++)
             {
             //NOT IMPLEMENT NOW
             /*if((unsigned char)s[i]<128 && !get_dual)
                 std::cout<<" "<<(int)s[i];
             if((unsigned char)s[i]>127 || get_dual)
                 {
                 dc.c[i_dual_char]=s[i];
                 if(get_dual)
                     {
                     get_dual=false;
                     i_dual_char=0;
                     std::cout<<" "<<std::dec<<dc.sh;
                     std::cout<<"-"<<std::hex<<(int)dc.c[0]<<(int)dc.c[1];
                     }
                 else
                     {
                     get_dual=true;
                     i_dual_char++;
                     }
                 }*/
             buffer[i]=s[i];
             }
     else
         std::cout<<"ERROR:CP866 to UTF8 not implement!!!"<<std::endl;
     //std::cout<<std::endl;
     //std::cout<<"A:"<<(unsigned char*)buffer<<std::endl;
     return buffer;
 }
References NULL.
Referenced by getRC().
cp1251_to_utf8()
std::string cp1251_to_utf8 (std::string in_string)
{
     if(lang() != RUSSIAN) {
         return in_string;
     }
 #ifdef WIN32
     return in_string;
 #endif
     char *out_mem = new char[in_string.length()*3+3];
     char *out = out_mem;
     const char *in = in_string.c_str();
     static const int table[128] = {
         0x82D0,0x83D0,0x9A80E2,0x93D1,0x9E80E2,0xA680E2,0xA080E2,0xA180E2,
         0xAC82E2,0xB080E2,0x89D0,0xB980E2,0x8AD0,0x8CD0,0x8BD0,0x8FD0,
         0x92D1,0x9880E2,0x9980E2,0x9C80E2,0x9D80E2,0xA280E2,0x9380E2,0x9480E2,
         0,0xA284E2,0x99D1,0xBA80E2,0x9AD1,0x9CD1,0x9BD1,0x9FD1,
         0xA0C2,0x8ED0,0x9ED1,0x88D0,0xA4C2,0x90D2,0xA6C2,0xA7C2,
         0x81D0,0xA9C2,0x84D0,0xABC2,0xACC2,0xADC2,0xAEC2,0x87D0,
         0xB0C2,0xB1C2,0x86D0,0x96D1,0x91D2,0xB5C2,0xB6C2,0xB7C2,
         0x91D1,0x9684E2,0x94D1,0xBBC2,0x98D1,0x85D0,0x95D1,0x97D1,
         0x90D0,0x91D0,0x92D0,0x93D0,0x94D0,0x95D0,0x96D0,0x97D0,
         0x98D0,0x99D0,0x9AD0,0x9BD0,0x9CD0,0x9DD0,0x9ED0,0x9FD0,
         0xA0D0,0xA1D0,0xA2D0,0xA3D0,0xA4D0,0xA5D0,0xA6D0,0xA7D0,
         0xA8D0,0xA9D0,0xAAD0,0xABD0,0xACD0,0xADD0,0xAED0,0xAFD0,
         0xB0D0,0xB1D0,0xB2D0,0xB3D0,0xB4D0,0xB5D0,0xB6D0,0xB7D0,
         0xB8D0,0xB9D0,0xBAD0,0xBBD0,0xBCD0,0xBDD0,0xBED0,0xBFD0,
         0x80D1,0x81D1,0x82D1,0x83D1,0x84D1,0x85D1,0x86D1,0x87D1,
         0x88D1,0x89D1,0x8AD1,0x8BD1,0x8CD1,0x8DD1,0x8ED1,0x8FD1
     };
     while (*in)
         if (*in & 0x80) {
             int v = table[(int)(0x7f & *in++)];
             if (!v)
                 continue;
             *out++ = (char)v;
             *out++ = (char)(v >> 8);
             if (v >>= 16)
                 *out++ = (char)v;
         }
         else
             *out++ = *in++;
     *out = 0;
     std::string string_out(out_mem);
     delete[] out_mem;
     return string_out;
 }
References lang(), and RUSSIAN.
Referenced by DiagenDispatcher::startSession().
cp866_to_cp1251()
std::string cp866_to_cp1251 (std::string in)
{
     if(lang() != RUSSIAN) {
         return in;
     }
 #ifdef WIN32
     return in;
 #endif
     unsigned int i;
     for (i = 0; i < in.length(); i++) {
         if ((unsigned char)in[i]>=128&&(unsigned char)in[i]<=175)
             in[i]=(char)((unsigned char)in[i]+64);
         else if ((unsigned char)in[i]>=224&&(unsigned char)in[i]<=239)
             in[i]=(char)((unsigned char)in[i]+16);
         else if ((unsigned char)in[i]==241)
             in[i]=(char)((unsigned char)184); //
         else if ((unsigned char)in[i]==240)
             in[i]=(char)((unsigned char)168); //
         else if ((unsigned char)in[i]==252)
             in[i]=(char)((unsigned char)185); //
         else if ((unsigned char)in[i]<128)
             in[i]=in[i];
         else
             in[i]=' ';
     }
     return in;
 }
References lang(), and RUSSIAN.
cutLink()
void cutLink (char *& p) inline
 {
     if(p){
         *p++ = '\0';
         *(p + strlen(p) - 1) = '\0';
         }
 }
Referenced by dgAtom::read().
dataList()
void dataList (int val = -1)
detect_text()
char* detect_text (char * ret)
{
     char* ret2 = ret;
     if (*ret2) {
         if (*ret2 == '$' && *(ret2+1) == '(') {
             std::cout<<"Detect variable in start string."<<std::endl;
             while(*ret2 && *ret2 != ')') { //  .   .     . :)
                 ret2++;
             }
             ret2++;
             while(*ret2 && *ret2 == ' ') { //
                 ret2++;
             }
         }
     }
     if(*ret2 == SUBJ_SYMBOL || *ret2 == COMMAND_SYMBOL) {
         return ret;
     }
     return  (*ret2 == LINK_SYMBOL || *ret2 == '<') ? ret2 + 1 : ret2;
 }
References COMMAND_SYMBOL, LINK_SYMBOL, and SUBJ_SYMBOL.
dg_SendEvent()
void dg_SendEvent (int code)
 {
     switch(code){
         case AML_GET_QUESTION:
             aci_SendEvent(EV_SHOW_QUESTS);
             break;
         case AML_TAKE_ELEECH:
             aciOfferEleech();
             break;
         case AML_TAKE_WEEZYK:
             aciOfferWeezyk();
             break;
         case AML_WAIT_NEXT_PERIOD:
             aciWaitNextPeriod();
             break;
         case AML_CLEAR_QUESTION:
             aciClearQuestMenu();
             break;
         case AML_ABORT_ESCAVE_SESSION:
             iShopForcedExit();
             break;
         case AML_BLOCK_SHOP:
             iLockShop();
             break;
         case AML_UNBLOCK_SHOP:
             iUnlockShop();
             break;
         case AML_BLOCK_EXIT:
             iLockExit();
             break;
         case AML_UNBLOCK_EXIT:
             iUnlockExit();
             break;
         case AML_LAMPASSO_THEEND:
             iShopForcedExit();
             GameOverID = GAME_OVER_LAMPASSO;
             iTheEND = 1;
             break;
         case AML_KICK_OUT_FROM_ESCAVE:
             aciEscaveKickOut();
             break;
         case AML_ACCEPT_RUBBOX:
             aciAcceptRubox();
             break;
         case AML_ADD_RUBBOX:
             aciAddRubox();
             break;
         case AML_EXPROPRIATION:
             aciExpropriation();
             break;
         case AML_CHANGE_TO_RAFFA:
             aciChange2Raffa();
             break;
     }
 }
References aci_SendEvent(), aciAcceptRubox(), aciAddRubox(), aciChange2Raffa(), aciClearQuestMenu(), aciEscaveKickOut(), aciExpropriation(), aciOfferEleech(), aciOfferWeezyk(), aciWaitNextPeriod(), AML_ABORT_ESCAVE_SESSION, AML_ACCEPT_RUBBOX, AML_ADD_RUBBOX, AML_BLOCK_EXIT, AML_BLOCK_SHOP, AML_CHANGE_TO_RAFFA, AML_CLEAR_QUESTION, AML_EXPROPRIATION, AML_GET_QUESTION, AML_KICK_OUT_FROM_ESCAVE, AML_LAMPASSO_THEEND, AML_TAKE_ELEECH, AML_TAKE_WEEZYK, AML_UNBLOCK_EXIT, AML_UNBLOCK_SHOP, AML_WAIT_NEXT_PERIOD, EV_SHOW_QUESTS, GAME_OVER_LAMPASSO, GameOverID, iLockExit(), iLockShop(), iShopForcedExit(), iTheEND, iUnlockExit(), and iUnlockShop().
dgGetThreallPhrase()
char* dgGetThreallPhrase (void)
 {
     return dgD -> getNextPhrase();
 }
References dgD.
Referenced by DoorEngine::Quant().
dgInThreall()
void dgInThreall (void)
 {
     dgD -> startSession("Threall");
 }
References dgD.
Referenced by DoorEngine::Quant().
dgLog()
void dgLog (char * string)
 {
 /*
     static XStream ff(getDGname("current.log"),XS_OUT);
     ff < "\"" < string < "\"\r\n";
 */
     if(!string) return;
 #ifdef DIAGEN_TEST
     if(checkStatus) return;
     std::cout << cp1251_to_utf8(cp866_to_cp1251(string)) << "\n";
     std::cout << strLine << strLine << "\n\n";
 #endif
 }
dgOutThreall()
void dgOutThreall (void)
 {
     dgD -> endSession();
 }
References dgD.
Referenced by DoorEngine::Quant().
diagenPrepare()
void diagenPrepare (void)
 {
     dgD = new DiagenDispatcher;
     dgD -> init();
 #ifdef DIAGEN_TEST
     loadList();
 #endif
 }
References dgD, and loadList().
Referenced by LoadingRTO1::Init().
DiagenTextName()
const char* DiagenTextName ()
{
     if (lang() == RUSSIAN) {
         return "diagen.text";
     }
     return "diagen_eng.text";
 }
References lang(), and RUSSIAN.
Referenced by FileBox::load().
getDGname()
char* getDGname (const char * name, const char * ext)
 {
     static char buf[256];
     strcpy(buf,"data/");
     strcat(buf,name);
     strcat(buf,ext);
     return buf;
 }
Referenced by dgRoom::acceptDIL(), dgRoom::acceptQUERY(), dgRoom::acceptTEXT(), and DiagenDispatcher::init().
getInfernalsTaskStatus()
int getInfernalsTaskStatus (void)
 {
 //#ifndef DIAGEN_TEST
     int res = 0,i;
     for(i = 0;i < 3;i++) res += isCycleExist(i,'F');
     for(i = 0;i < 3;i++) res += isCycleExist(i,'G');
     for(i = 0;i < 3;i++) res += isCycleExist(i,'N');
     return !res;
 /*#else
     return 1;
 #endif*/
 }
References isCycleExist().
getPassangerFrom()
int getPassangerFrom (char efrom)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     while(pe){
         if ( pe -> name[0] == efrom)
             return pe -> PassagerFrom;
         pe = (uvsEscave*)pe -> next;
     }
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(ps){
         if ( ps -> name[0] == efrom)
             return ps -> PassagerFrom;
         ps = (uvsSpot*)ps -> next;
     }
     return 0;
 }
References EscaveTail, uvsEscave::name, listElem::next, uvsEscave::PassagerFrom, and SpotTail.
getPassangerStats()
int getPassangerStats (char efrom, char wto)
{
     uvsWorld *pw = (uvsWorld*)WorldTail;
     while(pw && pw -> name[0] != wto ){
         pw = (uvsWorld*)pw -> next;
     }
     if (!pw) ErrH.Abort("getPassangerStats :: Incorrect world name");
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     while(pe){
         if ( pe -> name[0] == efrom)
             return pe -> PassagerStatistic[pw -> gIndex];
         pe = (uvsEscave*)pe -> next;
     }
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(ps){
         if ( ps -> name[0] == efrom)
             return ps -> PassagerStatistic[pw -> gIndex];
         ps = (uvsSpot*)ps -> next;
     }
     return 0;
 }
Referenced by getSpectorsTaskStatus().
getPreviousCycle()
int getPreviousCycle (int cycle)
{
     uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
     int i = cycle - 1;
     int _i = 0;
     if( i < 0 ) i = pb -> cycleN - 1;
     while( pb -> cycleTable[i].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE  ){
         if( --i < 0 ) i = pb -> cycleN - 1;
         _i++;
         if (_i > pb -> cycleN) {
             return -1;
         }
     }//  end while
     return i;
 }
References Gamer, uvsEscave::Pbunch, uvsEscave::Pworld, and UVS_DOLLY_STATUS::UNABLE.
Referenced by dgCell::analyzeACCESS().
getSpectorsTaskStatus()
int getSpectorsTaskStatus (void)
 {
 //#ifndef DIAGEN_TEST
     char es[] = "PIVLOZB";
     char ws[] = "WKBA";
     char esS[] = "???????";
     char wsS[] = "????";
     memcpy(esS,es,7);
     memcpy(wsS,ws,4);
     int i,j,res;
     for(i = 0;i < 4;i++)
         for(j = 0;j < 7;j++)
             if(res = getPassangerStats(es[j],ws[i])){
                 esS[j] = '\0';
                 wsS[i] = '\0';
                 }
     res = 0;
     for(i = 0;i < 4;i++) res += wsS[i];
     for(i = 0;i < 7;i++) res += esS[i];
     return !res;
 /*#else
     return 0;
 #endif*/
 }
References getPassangerStats().
getSpobsState()
int getSpobsState (void)
 {
     if(ActD.SpobsDestroy == 0) return 1;
     return 0;
 };
References ActD, and ActionDispatcher::SpobsDestroy.
getSubj() [1/2]
char* getSubj (char * p) inline
 {
 #ifdef GERMAN_VERSION
     if(*p != '$')
 #else
     if(*p != '#')
 #endif
         ErrH.Abort(dgSyntaxError);
     return p + 1;
 }
References XErrorHandler::Abort(), and ErrH.
getSubj() [2/2]
char* getSubj (char * p, int & m) inline
 {
     int len = strlen(p);
     if(*p != SUBJ_SYMBOL || *(p + len - 1) != SUBJ_SYMBOL_RIGHT) {
         std::cout<<"dgSyntaxError p:"<<p<<"|"<<m<<std::endl;
         ErrH.Abort(dgSyntaxError);
     }
     *(p + len - 1) = '\0';
     char* add = ++p;
     while(*add && *add != ':') {
         add++;
     }
     if(*add) {
         *add++ = '\0';
     }
     switch(*add){
         case 'G': m = 1; break;
         case 'B': m = 2; break;
         default: m = 0;
     }
     return p;
 }
References XErrorHandler::Abort(), ErrH, SUBJ_SYMBOL, and SUBJ_SYMBOL_RIGHT.
Referenced by dgRoom::acceptQUERY(), dgRoom::acceptTEXT(), and dgRoom::read().
getThreallState()
int getThreallState (void)
 {
      if(ActD.ThreallDestroy == 0) return 1;
      return 0;
 };
References ActD, and ActionDispatcher::ThreallDestroy.
getWorldVisitStats()
int getWorldVisitStats (char wc)
{
     uvsWorld *pw = (uvsWorld*)WorldTail;
     while(pw && pw -> name[0] != wc ){
         pw = (uvsWorld*)pw -> next;
     }
     if (!pw) ErrH.Abort("getWorldVisitStats :: Incorrect world name");
     return pw -> GamerVisit;
 }
Referenced by dgCell::analyzeACCESS().
isCycleExist()
int isCycleExist (int cycle, char ew = 0)
{
     if(!ew)
         return Gamer -> checkCycle(cycle);
     else {
         uvsWorld *pw = (uvsWorld*)WorldTail;
         while(pw && pw -> name[0] != ew ){
             pw = (uvsWorld*)pw -> next;
         }
         if (!pw) ErrH.Abort("isCycleExist :: Incorrect world name");
         if (!pw -> escTmax) return 0;
         uvsBunch *pb = pw -> escT[0] -> Pbunch;
         if (pb -> cycleTable[cycle].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE)
             return 0;
         else
             return 1;
     }
 }
References Gamer.
Referenced by getInfernalsTaskStatus().
ISEALPHA()
bool ISEALPHA (char c)
                       {
     if (lang() == RUSSIAN) {
         return ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'));
     } else if (lang() == GERMAN) {
         return  (c != '#' && !(c >= '0' && c <= '9'));
     }
     return ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'));
 }
References GERMAN, lang(), and RUSSIAN.
isSpummyDeath()
int isSpummyDeath (void)
 {
     return ActD.SpummyRunner;
 };
References ActD, and ActionDispatcher::SpummyRunner.
Referenced by DiagenDispatcher::getQdead().
loadList()
void loadList (void)
Referenced by diagenPrepare().
OpenCrypt()
void OpenCrypt (int world, int id)
 {
     TimeSecretEnable[world][id] = 1;
 };
References TimeSecretEnable.
saveList()
void saveList (void)
showmap()
void showmap (void)
StringOfBoozeeniada()
char* StringOfBoozeeniada (void)
 {
     return CHECK_BSIGN_DATA;
 };
References CHECK_BSIGN_DATA.
Referenced by dgMolecule::getVarPhrase().
uvsBoorawchickZero()
void uvsBoorawchickZero (void)
{
     GamerResult.BoorawchickGoHimself = 0;
 }
References uvsGamerResult::BoorawchickGoHimself, and GamerResult.
uvsgetDGdata()
int uvsgetDGdata (int code)
{
     switch( code ){
     case DG_EXTERNS::INV_UNIQUE_POPONKA:
             return GamerResult.unik_poponka;
             break;
         case DG_EXTERNS::ELR_RESULT:
 //          if (GamerResult.get_eleech)
                 return GamerResult.game_result;
 //          else
 //              return 0;
             break;
         case DG_EXTERNS::ELR_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::ELR_RATING:
             return (GamerResult.game_elr_result);
             break;
         case DG_EXTERNS::KER_RESULT:
             return GamerResult.game_result;
             break;
         case DG_EXTERNS::KER_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::KER_RATING:
             return (GamerResult.game_ker_result);
             break;
         case DG_EXTERNS::PIP_RESULT:
             return GamerResult.game_result;
             break;
         case DG_EXTERNS::PIP_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::PIP_RATING:
             return (GamerResult.game_pip_result);
             break;
         case DG_EXTERNS::ZYK_RESULT:
             return GamerResult.game_result;
             break;
         case DG_EXTERNS::ZYK_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::ZYK_RATING:
             return (GamerResult.game_zyk_result);
             break;
         case DG_EXTERNS::INV_BAD_CIRT:
             return (GamerResult.cirt_bad);
             break;
         case DG_EXTERNS::INV_GOOD_CIRT:
             return (GamerResult.cirt_good);
             break;
         case DG_EXTERNS::INV_NYMBOS:
             return (GamerResult.nymbos);
             break;
         case DG_EXTERNS::INV_PHLEGMA:
             return (GamerResult.phlegma);
             break;
         case DG_EXTERNS::INV_HEROIN:
             return (GamerResult.heroin);
             break;
         case DG_EXTERNS::INV_SHRUB:
             return (GamerResult.shrub);
             break;
         case DG_EXTERNS::INV_POPONKA:
             return (GamerResult.poponka);
             break;
         case DG_EXTERNS::INV_TOXICK:
             return (GamerResult.toxick);
             break;
         case DG_EXTERNS::INV_PIPETKA:
             return (GamerResult.pipetka);
             break;
         case DG_EXTERNS::INV_KERNOBOO:
             return (GamerResult.kernoboo);
             break;
         case DG_EXTERNS::INV_WEEZYK:
             return (GamerResult.weezyk);
             break;
         case DG_EXTERNS::INV_ELEECH:
             return (GamerResult.eleech);
             break;
         case DG_EXTERNS::INV_DEAD_ELEECH:
             return (GamerResult.dead_eleech_now);
             break;
         case DG_EXTERNS::INV_RUBBOX:
             return (GamerResult.rubbox);
             break;
         case DG_EXTERNS::KILLED_VANGERS:
             return (GamerResult.vanger_kill);
             break;
         case DG_EXTERNS::MECHOS_CHANGED:
             return (GamerResult.mechos_variant);
             break;
         case DG_EXTERNS::MECHOS_TYPE:
             return (GamerResult.mechos_type);
             break;
         case DG_EXTERNS::NYMBOS_DELIVERY:
             return (GamerResult.nymbos_total);
             break;
         case DG_EXTERNS::PHLEGMA_DELIVERY:
             return (GamerResult.phlegma_total);
             break;
         case DG_EXTERNS::HEROIN_DELIVERY:
             return (GamerResult.heroin_total);
             break;
         case DG_EXTERNS::SHRUB_DELIVERY:
             return (GamerResult.shrub_total);
             break;
         case DG_EXTERNS::POPONKA_DELIVERY:
             return (GamerResult.poponka_total);
             break;
         case DG_EXTERNS::TOXICK_DELIVERY:
             return (GamerResult.toxick_total);
             break;
         case DG_EXTERNS::NYMBOS_BONUS:
             return (GamerResult.nymbos_total >= GamerResult.nymbos_bonus*20);
             break;
         case DG_EXTERNS::PHLEGMA_BONUS:
             return (GamerResult.phlegma_total  >= GamerResult.phlegma_bonus*20);
             break;
         case DG_EXTERNS::HEROIN_BONUS:
             return (GamerResult.heroin_total  >= GamerResult.heroin_bonus*20);
             break;
         case DG_EXTERNS::SHRUB_BONUS:
             return (GamerResult.shrub_total >=  GamerResult.shrub_bonus*20);
             break;
         case DG_EXTERNS::POPONKA_BONUS:
             return (GamerResult.poponka_total >= GamerResult.poponka_bonus*20);
             break;
         case DG_EXTERNS::TOXICK_BONUS:
             return (GamerResult.toxick_total  >= GamerResult.toxick_bonus*20);
             break;
         case DG_EXTERNS::CYCLE:
             return (uvsCurrentCycle);
             break;
         case DG_EXTERNS::BEEBS:
             return (aciGetCurCredits());
             break;
         case DG_EXTERNS::WEEZYK_ASSIGNMENT:
             return (GamerResult.get_weezyk);
             break;
         case DG_EXTERNS::INV_BAD_LARVA:
             return (GamerResult.dolly == UVS_DOLLY_TYPE::ALIEN);
             break;
         case DG_EXTERNS::LARVA_CYCLE:
             return (GamerResult.dolly_cycle);
             break;
         case DG_EXTERNS::INV_GOOD_LARVA:
             return (GamerResult.dolly == UVS_DOLLY_TYPE::OWN);
             break;
         case DG_EXTERNS::LUCK:
             if (GamerResult.luck + GamerResult.add_luck > 100)
                 return 100;
             if (GamerResult.luck + GamerResult.add_luck < 0)
                 return 0;
             return (GamerResult.luck + GamerResult.add_luck);
             break;
         case DG_EXTERNS::INV_MESSIAH:
             if (uvsKronActive)
                 return CheckThreallMessiah();
             else
                 return (GamerResult.mechanic_messiah);
             break;
         case DG_EXTERNS::INV_ELEEPOD:
             return (GamerResult.eleepod);
             break;
         case DG_EXTERNS::INV_BEEBOORAT:
             return (GamerResult.beeboorat);
             break;
         case DG_EXTERNS::INV_ZEEX:
             return (GamerResult.zeex);
             break;
         case DG_EXTERNS::INV_LEEPURINGA:
             return (GamerResult.leepuringa);
             break;
         case DG_EXTERNS::INV_PALOCHKA:
             return (GamerResult.palochka);
             break;
         case DG_EXTERNS::INV_BOORAWCHICK:
             return (GamerResult.boorawchick);
             break;
         case DG_EXTERNS::INV_NOBOOL:
             return (GamerResult.nobool);
             break;
         case DG_EXTERNS::INV_PIPKA:
             return (GamerResult.pipka);
             break;
         case DG_EXTERNS::INV_PEREPONKA:
             return (GamerResult.pereponka);
             break;
         case DG_EXTERNS::INV_ZEEFICK:
             return (GamerResult.zeefick);
             break;
         case DG_EXTERNS::INV_PROTRACTOR:
             return (GamerResult.protractor);
             break;
         case DG_EXTERNS::INV_FUNCTION83:
             return (GamerResult.fun83);
             break;
         case DG_EXTERNS::INV_BOOTSECTOR:
             return (GamerResult.boot_sector);
             break;
         case DG_EXTERNS:: INV_PEELOT:
             return (GamerResult.peelot);
             break;
         case DG_EXTERNS::INV_SPUMMY:
             return (GamerResult.spummy);
             break;
         case DG_EXTERNS::DOMINANCE:
             if (GamerResult.dominance+GamerResult.add_dominance > 100 )
                 return 100;
             if (GamerResult.dominance+GamerResult.add_dominance < -100)
                 return -100;
             return (GamerResult.dominance+GamerResult.add_dominance);
             break;
         case DG_EXTERNS::TABUTASKS:
             return (Gamer -> GoodTabuTask());
             break;
         case DG_EXTERNS::FRESH_TABUTASKS:
             return (Gamer -> newGoodTabuTask());
             break;
         case DG_EXTERNS::WTABUTASKS:
             return (Gamer -> GoodWorldTabuTask());
             break;
         case DG_EXTERNS::CIRT_DELIVERY:
             return (Gamer -> CirtDelivery());
             break;
         case DG_EXTERNS::THIEF_LEEPURINGA:
             return (GamerResult.thief_leepuringa);
             break;
         case DG_EXTERNS::THIEF_PALOCHKA:
             return (GamerResult.thief_palochka);
             break;
         case DG_EXTERNS::THIEF_BOORAWCHICK:
             return (GamerResult.thief_boorawchick);
             break;
         case DG_EXTERNS::THIEF_NOBOOL:
             return (GamerResult.thief_nobool);
             break;
         case DG_EXTERNS::THIEF_PIPKA:
             return (GamerResult.thief_pipka);
             break;
         case DG_EXTERNS::THIEF_PEREPONKA:
             return (GamerResult.thief_pereponka);
             break;
         case DG_EXTERNS::THIEF_ZEEFICK:
             return (GamerResult.thief_zeefick);
             break;
         case DG_EXTERNS::TRUE_PASSENGER:
             return GamerResult.passagerOk;
             break;
         case DG_EXTERNS::HERE_LEEPURINGA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::LEEPURINGA, uvsTreasureInShop) ||
                     uvsReturnTreasureStatus(UVS_ITEM_TYPE::LEEPURINGA, 0));
             break;
         case DG_EXTERNS::HERE_PALOCHKA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::PALOCHKA, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::PALOCHKA, 0));
             break;
         case DG_EXTERNS::HERE_BOORAWCHICK:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::BOORAWCHICK, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::BOORAWCHICK, 0));
             break;
         case DG_EXTERNS::HERE_NOBOOL:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::NOBOOL, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::NOBOOL, 0));
             break;
         case DG_EXTERNS::HERE_PIPKA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::PIPKA, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::PIPKA, 0));
             break;
         case DG_EXTERNS::HERE_PEREPONKA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::PEREPONKA, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::PEREPONKA, 0));
             break;
         case DG_EXTERNS::HERE_ZEEFICK:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::ZEEFICK, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::ZEEFICK, 0));
             break;
         case DG_EXTERNS::BOORAWCHICK_RETURN:
             return GamerResult.BoorawchickGoHimself;
             break;
         case DG_EXTERNS::ZIGGER_ZAGGER:
             return (uvsMechosTable[19] -> constractor == 1 || uvsMechosTable[19] -> constractor == 3);
             break;
         case DG_EXTERNS::CART:
             return (uvsMechosTable[19] -> constractor == 2 || uvsMechosTable[19] -> constractor == 3);
             break;
         case DG_EXTERNS::PUT_PUT:
             return (uvsMechosTable[20] -> constractor == 1 || uvsMechosTable[20] -> constractor == 3);
             break;
         case DG_EXTERNS::BOX:
             return (uvsMechosTable[20] -> constractor == 2 || uvsMechosTable[20] -> constractor == 3);
             break;
         case DG_EXTERNS::RATTLE:
             return (uvsMechosTable[21] -> constractor == 1 || uvsMechosTable[21] -> constractor == 3);
             break;
         case DG_EXTERNS::HEAVY_IRON:
             return (uvsMechosTable[21] -> constractor == 2 || uvsMechosTable[21] -> constractor == 3);
             break;
         case DG_EXTERNS::STAR:
             return (uvsMechosTable[22] -> constractor == 1 || uvsMechosTable[22] -> constractor == 3);
             break;
         case DG_EXTERNS::WHIZZER:
             return (uvsMechosTable[22] -> constractor == 2 || uvsMechosTable[22] -> constractor == 3);
             break;
         case DG_EXTERNS::HUSKER:
             return (uvsMechosTable[23] -> constractor == 1 || uvsMechosTable[23] -> constractor == 3);
             break;
         case DG_EXTERNS::COGGED_WIDGET:
             return (uvsMechosTable[23] -> constractor == 2 || uvsMechosTable[23] -> constractor == 3);
             break;
         }// end switrh
     return 0;
 }
Referenced by dgCell::analyzeACCESS(), and dgMolecule::getVarPhrase().
uvsGetLarvaWorld()
char* uvsGetLarvaWorld (int n)
{
     uvsWorld *Pworld = Gamer->Pworld;
     if (Pworld -> escTmax){
         uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
         return pb -> cycleTable[n].Pdolly -> Pworld -> name;
     } else
         return NULL;
 }
Referenced by dgMolecule::getVarPhrase().
uvsLuckChange()
void uvsLuckChange (int val)
{
     GamerResult.luck += delta;
     ShowLuckMessage(delta);
     if (GamerResult.luck < 0) GamerResult.luck = 0;
     if (GamerResult.luck > 100) GamerResult.luck = 100;
 }
References GamerResult, uvsGamerResult::luck, and ShowLuckMessage().
uvsSetTownName()
void uvsSetTownName (const char * _name_)
{
     uvsTownName = _name_;
 }
References uvsTownName.
Variable Documentation
aciEscaveDead
int aciEscaveDead extern
Referenced by aci_LocationQuantPrepare(), aciAskQuestion(), aciBuildQuestList(), and aciNextPhrase().
aciEscaveEmpty
int aciEscaveEmpty extern
Referenced by aci_LocationQuantPrepare(), aciAskQuestion(), aciBuildQuestList(), and aciNextPhrase().
ArgData
struct Q3 ArgData[]
Referenced by dgCell::analyzeACCESS().
CmdData
struct Q4 CmdData[]
Referenced by dgCell::doCMD().
dgAbortStatus
int dgAbortStatus
Referenced by uvsVanger::prepare_list_for_ActInt(), and DiagenDispatcher::startSession().
dgD
DiagenDispatcher* dgD
Referenced by aciBuildQuestList(), aciEscaveKickOut(), aciInitEndGame(), aciNextPhrase(), aciSendEvent2itmdsp(), aciShowBlockPhrase(), dgGetThreallPhrase(), dgInThreall(), dgOutThreall(), diagenPrepare(), dgMolecule::getVarPhrase(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), uvsTabuTaskType::is_able(), uvsShop::prepare_list_for_ActInt(), and ActionDispatcher::PromptQuant().
dgMood
int dgMood
Referenced by aciStartSpeech(), and DiagenDispatcher::getQout().
GamerResult
uvsGamerResult GamerResult extern
Referenced by VangerUnit::BulletCollision(), ActionDispatcher::CreateActive(), VangerUnit::Destroy(), VangerUnit::DestroyCollision(), GeneralSystemOpen(), ActionDispatcher::PromptQuant(), and VangerUnit::SensorQuant().
MP_GAME
int MP_GAME = 0
Referenced by is_current_server_configured(), and send_server_data().
NetworkON
int NetworkON extern
Query
struct Q2 Query[]
Initial value:
= {
    { Q::TRU, "true" },
    { Q::DATA, "data" },
    { Q::VISITE, "visitE" },
    { Q::VISITW, "visitW" },
    { Q::COMING, "coming" },
    { Q::SINGLERAND, "singlerand" },
    { Q::BSTATUS, "bstatus" },
    { Q::ZSTATUS, "zstatus" },
    { Q::SSTATUS, "sstatus" },
    { Q::ENTER_SSTATUS, "enter_sstatus" },
    { Q::QCODE, "qcode" },
    { Q::MP_GAME, "mp_game" },
    { Q::CYCLE_EXIST, "cycle_exist" },
    { Q::PASSENGER_OUT, "passenger_out" },
    { Q::PASSENGER_ARRIVAL, "passenger_arrival" },
    { Q::SPECTORS_TASK, "spectors_task" },
    { Q::INFERNALS_TASK, "infernals_task" },
    { Q::SPOBS_ALIVE, "spobs_alive" },
    { Q::THREALL_ALIVE, "threall_alive" },
    { Q::SUCCESS, "success" },
    { Q::FIASCO, "fiasco" },
    { Q::SPUMMY_DEATH, "spummy_death" },
    { Q::KEY2GLORX_EXIST,"key2glorx_exist" },
    { Q::KEY2ARKAZNOY_EXIST,"key2arkaznoy_exist" },
    { Q::KEY2BOOZEENA_EXIST,"key2boozeena_exist" },
    { Q::WAS_RUBEECATED, "wasRubeecated" },
    { -1, NULL }
    }
Referenced by dgCell::analyzeACCESS().
RACE_WAIT
int RACE_WAIT extern
Referenced by uvsBunch::begin_race().
saveVersion
const int saveVersion = 3
Referenced by DiagenDispatcher::save().
uvsCurrentWorldUnableBefore
int uvsCurrentWorldUnableBefore extern
Referenced by uvsVanger::prepare_shop().