Vangers: lib/xtool/iniparser/dictionary.c File Reference
dictionary.c File Reference
Implements a dictionary for string variables.
#include "dictionary.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Macros
#define MAXVALSZ 1024
#define DICTMINSZ 128
#define DICT_INVALID_KEY ((char*)-1)
Functions
unsigned dictionary_hash (char *key)
Compute the hash key for a string.
dictionary * dictionary_new (int size)
Create a new dictionary object.
void dictionary_del (dictionary *d)
Delete a dictionary object.
char * dictionary_get (dictionary *d, char *key, char *def)
Get a value from a dictionary.
int dictionary_set (dictionary *d, char *key, char *val)
Set a value in a dictionary.
void dictionary_unset (dictionary *d, char *key)
Delete a key in a dictionary.
void dictionary_dump (dictionary *d, FILE *out)
Dump a dictionary to an opened file pointer.
Detailed Description
Implements a dictionary for string variables.
Author
N. Devillard
Date
Sep 2007
Version
Revision
1.27
This module implements a simple dictionary object, i.e. a list of string/string associations. This object is useful to store e.g. informations retrieved from a configuration file (ini files).
Definition in file dictionary.c.
Macro Definition Documentation
DICT_INVALID_KEY
#define DICT_INVALID_KEY ((char*)-1)
Invalid key token
DICTMINSZ
#define DICTMINSZ 128
Minimal allocated number of entries in a dictionary
MAXVALSZ
#define MAXVALSZ 1024
Maximum value size for integers and doubles.
Function Documentation
dictionary_del()
void dictionary_del (dictionary * d)
Delete a dictionary object.
Parameters
d dictionary object to deallocate.
Returns
void
Deallocate a dictionary object and all memory associated to it.
 {
     int     i ;
     if (d==NULL) return ;
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]!=NULL)
             free(d->key[i]);
         if (d->val[i]!=NULL)
             free(d->val[i]);
     }
     free(d->val);
     free(d->key);
     free(d->hash);
     free(d);
     return ;
 }
References _dictionary_::hash, _dictionary_::key, NULL, _dictionary_::size, and _dictionary_::val.
Referenced by iniparser_freedict(), and iniparser_load().
dictionary_dump()
void dictionary_dump (dictionary * d, FILE * out)
Dump a dictionary to an opened file pointer.
Parameters
d Dictionary to dump
f Opened file pointer.
Returns
void
Dumps a dictionary onto an opened file pointer. Key pairs are printed out as [Key]=[Value], one per line. It is Ok to provide stdout or stderr as output file pointers.
 {
     int     i ;
     if (d==NULL || out==NULL) return ;
     if (d->n<1) {
         fprintf(out, "empty dictionary\n");
         return ;
     }
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]) {
             fprintf(out, "%20s\t[%s]\n",
                     d->key[i],
                     d->val[i] ? d->val[i] : "UNDEF");
         }
     }
     return ;
 }
References _dictionary_::key, _dictionary_::n, NULL, _dictionary_::size, and _dictionary_::val.
dictionary_get()
char* dictionary_get (dictionary * d, char * key, char * def)
Get a value from a dictionary.
Parameters
d dictionary object to search.
key Key to look for in the dictionary.
def Default value to return if key not found.
Returns
1 pointer to internally allocated character string.
This function locates a key in a dictionary and returns a pointer to its value, or the passed 'def' pointer if no such key can be found in dictionary. The returned character pointer points to data internal to the dictionary object, you should not try to free it or modify it.
 {
     unsigned    hash ;
     int         i ;
     hash = dictionary_hash(key);
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]==NULL)
             continue ;
         /* Compare hash */
         if (hash==d->hash[i]) {
             /* Compare string, to avoid hash collisions */
             if (!strcmp(key, d->key[i])) {
                 return d->val[i] ;
             }
         }
     }
     return def ;
 }
References dictionary_hash(), _dictionary_::hash, _dictionary_::key, key(), NULL, _dictionary_::size, and _dictionary_::val.
dictionary_hash()
unsigned dictionary_hash (char * key)
Compute the hash key for a string.
Parameters
key Character string to use for key.
Returns
1 unsigned int on at least 32 bits.
This hash function has been taken from an Article in Dr Dobbs Journal. This is normally a collision-free function, distributing keys evenly. The key is stored anyway in the struct so that collision can be avoided by comparing the key itself in last resort.
 {
     int         len ;
     unsigned    hash ;
     int         i ;
     len = strlen(key);
     for (hash=0, i=0 ; i<len ; i++) {
         hash += (unsigned)key[i] ;
         hash += (hash<<10);
         hash ^= (hash>>6) ;
     }
     hash += (hash <<3);
     hash ^= (hash >>11);
     hash += (hash <<15);
     return hash ;
 }
References key().
Referenced by dictionary_get(), dictionary_set(), and dictionary_unset().
dictionary_new()
dictionary* dictionary_new (int size)
Create a new dictionary object.
Parameters
size Optional initial size of the dictionary.
Returns
1 newly allocated dictionary objet.
This function allocates a new dictionary object of given size and returns it. If you do not know in advance (roughly) the number of entries in the dictionary, give size=0.
 {
     dictionary  *   d ;
     /* If no size was specified, allocate space for DICTMINSZ */
     if (size<DICTMINSZ) size=DICTMINSZ ;
     if (!(d = (dictionary *)calloc(1, sizeof(dictionary)))) {
         return NULL;
     }
     d->size = size ;
     d->val  = (char **)calloc(size, sizeof(char*));
     d->key  = (char **)calloc(size, sizeof(char*));
     d->hash = (unsigned int *)calloc(size, sizeof(unsigned));
     return d ;
 }
References DICTMINSZ, _dictionary_::hash, _dictionary_::key, NULL, _dictionary_::size, and _dictionary_::val.
Referenced by iniparser_load().
dictionary_set()
int dictionary_set (dictionary * d, char * key, char * val)
Set a value in a dictionary.
Parameters
d dictionary object to modify.
key Key to modify or add.
val Value to add.
Returns
int 0 if Ok, anything else otherwise
If the given key is found in the dictionary, the associated value is replaced by the provided one. If the key cannot be found in the dictionary, it is added to it.
It is Ok to provide a NULL value for val, but NULL values for the dictionary or the key are considered as errors: the function will return immediately in such a case.
Notice that if you dictionary_set a variable to NULL, a call to dictionary_get will return a NULL value: the variable will be found, and its value (NULL) is returned. In other words, setting the variable content to NULL is equivalent to deleting the variable from the dictionary. It is not possible (in this implementation) to have a key in the dictionary without value.
This function returns non-zero in case of failure.
 {
     int         i ;
     unsigned    hash ;
     if (d==NULL || key==NULL) return -1 ;
     /* Compute hash for this key */
     hash = dictionary_hash(key) ;
     /* Find if value is already in dictionary */
     if (d->n>0) {
         for (i=0 ; i<d->size ; i++) {
             if (d->key[i]==NULL)
                 continue ;
             if (hash==d->hash[i]) { /* Same hash value */
                 if (!strcmp(key, d->key[i])) {   /* Same key */
                     /* Found a value: modify and return */
                     if (d->val[i]!=NULL)
                         free(d->val[i]);
                     d->val[i] = val ? xstrdup(val) : NULL ;
                     /* Value has been modified: return */
                     return 0 ;
                 }
             }
         }
     }
     /* Add a new value */
     /* See if dictionary needs to grow */
     if (d->n==d->size) {
         /* Reached maximum size: reallocate dictionary */
         d->val  = (char **)mem_double(d->val,  d->size * sizeof(char*)) ;
         d->key  = (char **)mem_double(d->key,  d->size * sizeof(char*)) ;
         d->hash = (unsigned int *)mem_double(d->hash, d->size * sizeof(unsigned)) ;
         if ((d->val==NULL) || (d->key==NULL) || (d->hash==NULL)) {
             /* Cannot grow dictionary */
             return -1 ;
         }
         /* Double size */
         d->size *= 2 ;
     }
     /* Insert key in the first empty slot */
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]==NULL) {
             /* Add key here */
             break ;
         }
     }
     /* Copy key */
     d->key[i]  = xstrdup(key);
     d->val[i]  = val ? xstrdup(val) : NULL ;
     d->hash[i] = hash;
     d->n ++ ;
     return 0 ;
 }
References dictionary_hash(), _dictionary_::hash, _dictionary_::key, key(), _dictionary_::n, NULL, _dictionary_::size, and _dictionary_::val.
Referenced by iniparser_set().
dictionary_unset()
void dictionary_unset (dictionary * d, char * key)
Delete a key in a dictionary.
Parameters
d dictionary object to modify.
key Key to remove.
Returns
void
This function deletes a key in a dictionary. Nothing is done if the key cannot be found.
 {
     unsigned    hash ;
     int         i ;
     if (key == NULL) {
         return;
     }
     hash = dictionary_hash(key);
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]==NULL)
             continue ;
         /* Compare hash */
         if (hash==d->hash[i]) {
             /* Compare string, to avoid hash collisions */
             if (!strcmp(key, d->key[i])) {
                 /* Found key */
                 break ;
             }
         }
     }
     if (i>=d->size)
         /* Key not found */
         return ;
     free(d->key[i]);
     d->key[i] = NULL ;
     if (d->val[i]!=NULL) {
         free(d->val[i]);
         d->val[i] = NULL ;
     }
     d->hash[i] = 0 ;
     d->n -- ;
     return ;
 }
References dictionary_hash(), _dictionary_::hash, _dictionary_::key, key(), _dictionary_::n, NULL, _dictionary_::size, and _dictionary_::val.
Referenced by iniparser_unset().