var hierarchy =
[
    [ "_dictionary_", "struct__dictionary__.html", null ],
    [ "aciCHTree", "structaci_c_h_tree.html", null ],
    [ "aciFont", "structaci_font.html", null ],
    [ "aciLocationShutterInfo", "structaci_location_shutter_info.html", null ],
    [ "aciMechosPartInfo", "structaci_mechos_part_info.html", null ],
    [ "aciML_Dispatcher", "structaci_m_l___dispatcher.html", null ],
    [ "aciML_EventLine", "structaci_m_l___event_line.html", null ],
    [ "aciML_EventSeqLine", "structaci_m_l___event_seq_line.html", null ],
    [ "aciML_FlushLine", "structaci_m_l___flush_line.html", null ],
    [ "aciPos", "structaci_pos.html", null ],
    [ "aciPromptData", "structaci_prompt_data.html", null ],
    [ "aciScreenDispatcher", "structaci_screen_dispatcher.html", null ],
    [ "aciScreenEventLine", "structaci_screen_event_line.html", null ],
    [ "aciScreenKeyObject", "structaci_screen_key_object.html", null ],
    [ "aciScreenText", "structaci_screen_text.html", null ],
    [ "actEvent", "structact_event.html", null ],
    [ "actEventHeap", "structact_event_heap.html", null ],
    [ "actIntDispatcher", "structact_int_dispatcher.html", null ],
    [ "actintItemData", "structactint_item_data.html", null ],
    [ "aiFactorType", "structai_factor_type.html", [
      [ "VangerUnit", "struct_vanger_unit.html", null ]
    ] ],
    [ "aiListElement", "structai_list_element.html", [
      [ "aiUnitEvent", "structai_unit_event.html", null ],
      [ "aiUnitResolve", "structai_unit_resolve.html", null ]
    ] ],
    [ "aiListType", "structai_list_type.html", [
      [ "aiResolveList", "structai_resolve_list.html", null ]
    ] ],
    [ "aiMessageList", "structai_message_list.html", null ],
    [ "aiMessageListElem", "structai_message_list_elem.html", null ],
    [ "aiMessageType", "structai_message_type.html", null ],
    [ "aiRndType", "structai_rnd_type.html", null ],
    [ "aKeyObj", "structa_key_obj.html", null ],
    [ "BackgroundDispatcher", "struct_background_dispatcher.html", null ],
    [ "BackgroundElement", "struct_background_element.html", [
      [ "LightPoint", "struct_light_point.html", null ],
      [ "ParticleProcess", "struct_particle_process.html", null ]
    ] ],
    [ "bfd_ctx", "structbfd__ctx.html", null ],
    [ "bfd_set", "structbfd__set.html", null ],
    [ "BranchType", "struct_branch_type.html", null ],
    [ "BULLET_CONTROL_MODE", "struct_b_u_l_l_e_t___c_o_n_t_r_o_l___m_o_d_e.html", null ],
    [ "BULLET_EVENT_ID", "struct_b_u_l_l_e_t___e_v_e_n_t___i_d.html", null ],
    [ "BULLET_SHOW_TYPE_ID", "struct_b_u_l_l_e_t___s_h_o_w___t_y_p_e___i_d.html", null ],
    [ "BULLET_TARGET_MODE", "struct_b_u_l_l_e_t___t_a_r_g_e_t___m_o_d_e.html", null ],
    [ "BULLET_TYPE_ID", "struct_b_u_l_l_e_t___t_y_p_e___i_d.html", null ],
    [ "BulletControlType", "struct_bullet_control_type.html", [
      [ "BulletObject", "struct_bullet_object.html", null ],
      [ "WorldBulletTemplate", "struct_world_bullet_template.html", null ]
    ] ],
    [ "central_directory_file_header", "structcentral__directory__file__header.html", null ],
    [ "CharacterDataType", "struct_character_data_type.html", null ],
    [ "CMD", "struct_c_m_d.html", null ],
    [ "COLORS_IDS", "struct_c_o_l_o_r_s___i_d_s.html", null ],
    [ "CompasObject", "struct_compas_object.html", null ],
    [ "CompasTargetType", "struct_compas_target_type.html", null ],
    [ "config", "structconfig.html", null ],
    [ "CONTROLS", "struct_c_o_n_t_r_o_l_s.html", null ],
    [ "ct_data", "structct__data.html", null ],
    [ "DangerTypeList", "struct_danger_type_list.html", null ],
    [ "DAST_SIGN_TYPE", "struct_d_a_s_t___s_i_g_n___t_y_p_e.html", null ],
    [ "dastPoly3D", "structdast_poly3_d.html", null ],
    [ "dastResourcePoly3D", "structdast_resource_poly3_d.html", null ],
    [ "dastResourceSign", "structdast_resource_sign.html", null ],
    [ "DBM", "struct_d_b_m.html", null ],
    [ "DBV", "struct_d_b_v.html", null ],
    [ "DeformProcess", "struct_deform_process.html", null ],
    [ "DG_CELLSTATUS", "struct_d_g___c_e_l_l_s_t_a_t_u_s.html", null ],
    [ "DG_EXTERNS", "struct_d_g___e_x_t_e_r_n_s.html", null ],
    [ "dgAtom", "structdg_atom.html", null ],
    [ "dgCell", "structdg_cell.html", null ],
    [ "dgFile", "structdg_file.html", null ],
    [ "dgMolecule", "structdg_molecule.html", null ],
    [ "dgQuery", "structdg_query.html", null ],
    [ "dgRoom", "structdg_room.html", null ],
    [ "DHuff", "struct_d_huff.html", null ],
    [ "DiagenDispatcher", "struct_diagen_dispatcher.html", null ],
    [ "dual_char", "uniondual__char.html", null ],
    [ "end_central_dir_record", "structend__central__dir__record.html", null ],
    [ "EngineModeList", "struct_engine_mode_list.html", null ],
    [ "EngineTypeList", "struct_engine_type_list.html", null ],
    [ "EnterCenter", "struct_enter_center.html", null ],
    [ "Event", "struct_event.html", null ],
    [ "FileBox", "struct_file_box.html", null ],
    [ "find_info", "structfind__info.html", null ],
    [ "FireBallProcess", "struct_fire_ball_process.html", null ],
    [ "fncMenuSet", "structfnc_menu_set.html", null ],
    [ "Game", "struct_game.html", null ],
    [ "GameObjectDispatcher", "struct_game_object_dispatcher.html", null ],
    [ "GeneralObject", "struct_general_object.html", [
      [ "BaseObject", "struct_base_object.html", [
        [ "BulletObject", "struct_bullet_object.html", null ],
        [ "DeformObject", "struct_deform_object.html", null ],
        [ "ExplosionObject", "struct_explosion_object.html", null ],
        [ "FireBallObject", "struct_fire_ball_object.html", null ],
        [ "HordeObject", "struct_horde_object.html", null ],
        [ "ParticleGenerator", "struct_particle_generator.html", null ],
        [ "ParticleObject", "struct_particle_object.html", null ],
        [ "TargetParticleObject", "struct_target_particle_object.html", null ],
        [ "WaterParticleObject", "struct_water_particle_object.html", null ]
      ] ],
      [ "GloryPlace", "struct_glory_place.html", null ],
      [ "LightPoint", "struct_light_point.html", null ],
      [ "StaticObject", "struct_static_object.html", [
        [ "DangerDataType", "struct_danger_data_type.html", null ],
        [ "SensorDataType", "struct_sensor_data_type.html", null ],
        [ "TntCreature", "struct_tnt_creature.html", null ]
      ] ]
    ] ],
    [ "GunSlot", "struct_gun_slot.html", null ],
    [ "HChar", "struct_h_char.html", null ],
    [ "HFont", "struct_h_font.html", null ],
    [ "huft", "structhuft.html", null ],
    [ "HUNTAGE_PRM", "struct_h_u_n_t_a_g_e___p_r_m.html", null ],
    [ "iGameMap", "structi_game_map.html", null ],
    [ "iKeyControls", "structi_key_controls.html", null ],
    [ "iList", "structi_list.html", [
      [ "iScreenDispatcher", "structi_screen_dispatcher.html", null ]
    ] ],
    [ "iListElement", "structi_list_element.html", [
      [ "aButton", "structa_button.html", null ],
      [ "aciBitmapMenu", "structaci_bitmap_menu.html", null ],
      [ "aciBitmapMenuItem", "structaci_bitmap_menu_item.html", null ],
      [ "aciLocationInfo", "structaci_location_info.html", null ],
      [ "aciML_Data", "structaci_m_l___data.html", null ],
      [ "aciML_DataSet", "structaci_m_l___data_set.html", null ],
      [ "aciML_Event", "structaci_m_l___event.html", null ],
      [ "aciML_EventCommand", "structaci_m_l___event_command.html", null ],
      [ "aciML_EventSeq", "structaci_m_l___event_seq.html", null ],
      [ "aciML_FlushData", "structaci_m_l___flush_data.html", null ],
      [ "aciML_ItemData", "structaci_m_l___item_data.html", null ],
      [ "aciScreenTextPage", "structaci_screen_text_page.html", null ],
      [ "aciScreenTextString", "structaci_screen_text_string.html", null ],
      [ "aciWorldInfo", "structaci_world_info.html", null ],
      [ "aciWorldMap", "structaci_world_map.html", null ],
      [ "aIndData", "structa_ind_data.html", null ],
      [ "bmlObject", "structbml_object.html", null ],
      [ "CounterPanel", "struct_counter_panel.html", null ],
      [ "fncMenu", "structfnc_menu.html", null ],
      [ "fncMenuItem", "structfnc_menu_item.html", null ],
      [ "ibsObject", "structibs_object.html", null ],
      [ "iListElementPtr", "structi_list_element_ptr.html", null ],
      [ "InfoPanel", "struct_info_panel.html", null ],
      [ "InfoPanelItem", "struct_info_panel_item.html", null ],
      [ "invItem", "structinv_item.html", null ],
      [ "invMatrix", "structinv_matrix.html", null ],
      [ "invMatrixCell", "structinv_matrix_cell.html", null ],
      [ "iObjID", "structi_obj_i_d.html", null ],
      [ "iScanCode", "structi_scan_code.html", null ],
      [ "iScreen", "structi_screen.html", null ],
      [ "iScreenElement", "structi_screen_element.html", [
        [ "iAVIBorderElement", "structi_a_v_i_border_element.html", null ],
        [ "iAVIElement", "structi_a_v_i_element.html", null ],
        [ "iBitmapElement", "structi_bitmap_element.html", [
          [ "iScrollerElement", "structi_scroller_element.html", null ]
        ] ],
        [ "iS_StringElement", "structi_s___string_element.html", null ],
        [ "iStringElement", "structi_string_element.html", null ],
        [ "iTerrainElement", "structi_terrain_element.html", null ]
      ] ],
      [ "iScreenEvent", "structi_screen_event.html", null ],
      [ "iScreenEventCommand", "structi_screen_event_command.html", null ],
      [ "iScreenObject", "structi_screen_object.html", [
        [ "iTriggerObject", "structi_trigger_object.html", null ]
      ] ],
      [ "iTextData", "structi_text_data.html", null ]
    ] ],
    [ "iMLFrame", "structi_m_l_frame.html", null ],
    [ "iMobileLocation", "structi_mobile_location.html", null ],
    [ "iMultiGameData", "structi_multi_game_data.html", null ],
    [ "iMultiGameParameter", "structi_multi_game_parameter.html", null ],
    [ "iMultiResultString", "structi_multi_result_string.html", null ],
    [ "iScreenFont", "structi_screen_font.html", null ],
    [ "iScreenOption", "structi_screen_option.html", null ],
    [ "iStack", "structi_stack.html", null ],
    [ "iStackElement", "structi_stack_element.html", null ],
    [ "ivrtMap", "structivrt_map.html", null ],
    [ "ivrtNode", "structivrt_node.html", null ],
    [ "KeyBuffer", "struct_key_buffer.html", null ],
    [ "LandQuake", "struct_land_quake.html", null ],
    [ "LIGHT_TYPE", "struct_l_i_g_h_t___t_y_p_e.html", null ],
    [ "LinkType", "struct_link_type.html", null ],
    [ "listElem", "structlist_elem.html", [
      [ "Place", "struct_place.html", null ],
      [ "uvsActInt", "structuvs_act_int.html", null ],
      [ "uvsBunch", "structuvs_bunch.html", null ],
      [ "uvsCrypt", "structuvs_crypt.html", null ],
      [ "uvsDolly", "structuvs_dolly.html", null ],
      [ "uvsEscave", "structuvs_escave.html", null ],
      [ "uvsItem", "structuvs_item.html", null ],
      [ "uvsMechos", "structuvs_mechos.html", null ],
      [ "uvsPassage", "structuvs_passage.html", null ],
      [ "uvsShop", "structuvs_shop.html", null ],
      [ "uvsSpot", "structuvs_spot.html", null ],
      [ "uvsTabuTaskType", "structuvs_tabu_task_type.html", null ],
      [ "uvsTradeItem", "structuvs_trade_item.html", null ],
      [ "uvsWorld", "structuvs_world.html", null ]
    ] ],
    [ "local_file_header", "structlocal__file__header.html", null ],
    [ "LocationEngine", "struct_location_engine.html", [
      [ "CheckPointEngine", "struct_check_point_engine.html", null ],
      [ "CyclicEngine", "struct_cyclic_engine.html", null ],
      [ "DoorEngine", "struct_door_engine.html", null ],
      [ "EnterEngine", "struct_enter_engine.html", [
        [ "ElevatorEngine", "struct_elevator_engine.html", [
          [ "EscaveEngine", "struct_escave_engine.html", [
            [ "ImpulseEscave", "struct_impulse_escave.html", [
              [ "ImpulseSpot", "struct_impulse_spot.html", null ]
            ] ]
          ] ]
        ] ]
      ] ],
      [ "ItemGenerator", "struct_item_generator.html", null ],
      [ "LandSlideEngine", "struct_land_slide_engine.html", null ],
      [ "PassageEngine", "struct_passage_engine.html", null ],
      [ "SignPlayEngine", "struct_sign_play_engine.html", null ],
      [ "TiristorEngine", "struct_tiristor_engine.html", null ],
      [ "TrainEngine", "struct_train_engine.html", null ]
    ] ],
    [ "Mask", "struct_mask.html", null ],
    [ "Mat2f", "class_mat2f.html", null ],
    [ "Mat3d", "class_mat3d.html", null ],
    [ "Mat3f", "class_mat3f.html", null ],
    [ "Mat4f", "class_mat4f.html", null ],
    [ "Matrix", "struct_matrix.html", null ],
    [ "MatX2f", "class_mat_x2f.html", null ],
    [ "MatXd", "class_mat_xd.html", null ],
    [ "MatXf", "class_mat_xf.html", null ],
    [ "MECHOSOMA_PRM", "struct_m_e_c_h_o_s_o_m_a___p_r_m.html", null ],
    [ "MechosomaStatistic", "struct_mechosoma_statistic.html", null ],
    [ "MemoryHeap", "struct_memory_heap.html", null ],
    [ "MemoryStorageType", "struct_memory_storage_type.html", null ],
    [ "MemTestBlock", "struct_mem_test_block.html", null ],
    [ "MLFrame", "struct_m_l_frame.html", null ],
    [ "MobileLocation", "struct_mobile_location.html", null ],
    [ "Model", "struct_model.html", null ],
    [ "ModelDispatcher", "struct_model_dispatcher.html", null ],
    [ "MUSTODONT_PRM", "struct_m_u_s_t_o_d_o_n_t___p_r_m.html", null ],
    [ "MustodontStatistic", "struct_mustodont_statistic.html", null ],
    [ "NetRndType", "struct_net_rnd_type.html", null ],
    [ "NodeType", "struct_node_type.html", null ],
    [ "Normal", "struct_normal.html", null ],
    [ "Object", "struct_object.html", [
      [ "ActionUnit", "struct_action_unit.html", [
        [ "InsectUnit", "struct_insect_unit.html", null ],
        [ "TrackUnit", "struct_track_unit.html", [
          [ "VangerUnit", "struct_vanger_unit.html", null ]
        ] ]
      ] ],
      [ "ClefObject", "struct_clef_object.html", null ],
      [ "DebrisObject", "struct_debris_object.html", null ],
      [ "FishWarrior", "struct_fish_warrior.html", null ],
      [ "HordeSource", "struct_horde_source.html", null ],
      [ "JumpBallObject", "struct_jump_ball_object.html", null ],
      [ "SkyFarmerObject", "struct_sky_farmer_object.html", null ],
      [ "StuffObject", "struct_stuff_object.html", [
        [ "ChangerDevice", "struct_changer_device.html", null ],
        [ "GunDevice", "struct_gun_device.html", null ]
      ] ]
    ] ],
    [ "output_buffer", "structoutput__buffer.html", null ],
    [ "PalConstructor", "struct_pal_constructor.html", null ],
    [ "PaletteTransform", "struct_palette_transform.html", null ],
    [ "PalPoint", "struct_pal_point.html", null ],
    [ "Particle", "struct_particle.html", null ],
    [ "ParticleInitDataType", "struct_particle_init_data_type.html", null ],
    [ "ParticleMapProcess", "struct_particle_map_process.html", null ],
    [ "ParticleMapProcessType", "struct_particle_map_process_type.html", null ],
    [ "PassageImageType", "struct_passage_image_type.html", null ],
    [ "PASSEMBLOSS_PRM", "struct_p_a_s_s_e_m_b_l_o_s_s___p_r_m.html", null ],
    [ "PassemblossStatistic", "struct_passembloss_statistic.html", null ],
    [ "Player", "struct_player.html", null ],
    [ "PlayerBody", "struct_player_body.html", null ],
    [ "PlayerData", "struct_player_data.html", null ],
    [ "PrmFile", "struct_prm_file.html", null ],
    [ "Q", "struct_q.html", null ],
    [ "Q2", "struct_q2.html", null ],
    [ "Q3", "struct_q3.html", null ],
    [ "Q4", "struct_q4.html", null ],
    [ "QuatD", "class_quat_d.html", null ],
    [ "Quaternion", "struct_quaternion.html", null ],
    [ "QuatF", "class_quat_f.html", null ],
    [ "RandomGenerator", "class_random_generator.html", null ],
    [ "RatingData", "struct_rating_data.html", null ],
    [ "scMathExpression", "structsc_math_expression.html", null ],
    [ "scMathNode", "structsc_math_node.html", null ],
    [ "ScriptBlock", "struct_script_block.html", null ],
    [ "ScriptDefine", "struct_script_define.html", null ],
    [ "ScriptFile", "struct_script_file.html", null ],
    [ "ScriptFileBuffer", "struct_script_file_buffer.html", null ],
    [ "ScriptLine", "struct_script_line.html", null ],
    [ "Se3d", "class_se3d.html", null ],
    [ "Se3f", "class_se3f.html", null ],
    [ "SensorTypeList", "struct_sensor_type_list.html", null ],
    [ "Server", "struct_server.html", null ],
    [ "ServerData", "struct_server_data.html", null ],
    [ "ServerFindChain", "struct_server_find_chain.html", null ],
    [ "SimpleParticleType", "struct_simple_particle_type.html", null ],
    [ "SndParameters", "struct_snd_parameters.html", null ],
    [ "StaticObjectType", "struct_static_object_type.html", null ],
    [ "StorageClusterType", "struct_storage_cluster_type.html", null ],
    [ "StorageType", "struct_storage_type.html", null ],
    [ "Stream", null, [
      [ "OggStream", "class_ogg_stream.html", null ]
    ] ],
    [ "sWinVideo", "structs_win_video.html", null ],
    [ "TargetParticleType", "struct_target_particle_type.html", null ],
    [ "TrackLinkType", "struct_track_link_type.html", [
      [ "TrackUnit", "struct_track_unit.html", null ]
    ] ],
    [ "TrackType", "struct_track_type.html", null ],
    [ "tree_desc", "structtree__desc.html", null ],
    [ "UnitItemMatrix", "struct_unit_item_matrix.html", null ],
    [ "UnitList", "struct_unit_list.html", [
      [ "ActionDispatcher", "struct_action_dispatcher.html", null ],
      [ "EffectDispatcher", "struct_effect_dispatcher.html", null ],
      [ "ItemsDispatcher", "struct_items_dispatcher.html", null ]
    ] ],
    [ "UnitListType", "struct_unit_list_type.html", [
      [ "UnitBaseListType", "struct_unit_base_list_type.html", [
        [ "BulletList", "struct_bullet_list.html", null ],
        [ "ClefList", "struct_clef_list.html", null ],
        [ "DebrisList", "struct_debris_list.html", null ],
        [ "FishWarriorList", "struct_fish_warrior_list.html", null ],
        [ "HordeList", "struct_horde_list.html", null ],
        [ "HordeSourceList", "struct_horde_source_list.html", null ],
        [ "InsectList", "struct_insect_list.html", null ],
        [ "JumpBallList", "struct_jump_ball_list.html", null ],
        [ "SkyFarmerList", "struct_sky_farmer_list.html", null ]
      ] ]
    ] ],
    [ "UnitOrderType", "union_unit_order_type.html", null ],
    [ "UVS_BUNCH_STATUS", "struct_u_v_s___b_u_n_c_h___s_t_a_t_u_s.html", null ],
    [ "UVS_CAR_TYPE", "struct_u_v_s___c_a_r___t_y_p_e.html", null ],
    [ "UVS_CRYPT", "struct_u_v_s___c_r_y_p_t.html", null ],
    [ "UVS_DOLLY_STATUS", "struct_u_v_s___d_o_l_l_y___s_t_a_t_u_s.html", null ],
    [ "UVS_DOLLY_TYPE", "struct_u_v_s___d_o_l_l_y___t_y_p_e.html", null ],
    [ "UVS_EVENT", "struct_u_v_s___e_v_e_n_t.html", null ],
    [ "UVS_GAME_ID", "struct_u_v_s___g_a_m_e___i_d.html", null ],
    [ "UVS_GAME_TYPE", "struct_u_v_s___g_a_m_e___t_y_p_e.html", null ],
    [ "UVS_ITEM_STATUS", "struct_u_v_s___i_t_e_m___s_t_a_t_u_s.html", null ],
    [ "UVS_ITEM_TYPE", "struct_u_v_s___i_t_e_m___t_y_p_e.html", null ],
    [ "UVS_KRON_EVENT", "struct_u_v_s___k_r_o_n___e_v_e_n_t.html", null ],
    [ "UVS_KRON_FLAG", "struct_u_v_s___k_r_o_n___f_l_a_g.html", null ],
    [ "UVS_MECHOS_USED", "struct_u_v_s___m_e_c_h_o_s___u_s_e_d.html", null ],
    [ "UVS_OBJECT", "struct_u_v_s___o_b_j_e_c_t.html", null ],
    [ "UVS_ORDER", "struct_u_v_s___o_r_d_e_r.html", null ],
    [ "UVS_TABUTASK_STATUS", "struct_u_v_s___t_a_b_u_t_a_s_k___s_t_a_t_u_s.html", null ],
    [ "UVS_TABUTASK_WORK", "struct_u_v_s___t_a_b_u_t_a_s_k___w_o_r_k.html", null ],
    [ "UVS_TARGET", "struct_u_v_s___t_a_r_g_e_t.html", null ],
    [ "UVS_TOWN", "struct_u_v_s___t_o_w_n.html", null ],
    [ "UVS_VANGER_SHAPE", "struct_u_v_s___v_a_n_g_e_r___s_h_a_p_e.html", null ],
    [ "UVS_VANGER_STATUS", "struct_u_v_s___v_a_n_g_e_r___s_t_a_t_u_s.html", null ],
    [ "uvsContimer", "structuvs_contimer.html", null ],
    [ "uvsCultGame", "structuvs_cult_game.html", null ],
    [ "uvsCultStage", "structuvs_cult_stage.html", null ],
    [ "uvsElement", "structuvs_element.html", [
      [ "uvsDolly", "structuvs_dolly.html", null ],
      [ "uvsFlyFarmer", "structuvs_fly_farmer.html", null ],
      [ "uvsRaffa", "structuvs_raffa.html", null ],
      [ "uvsVanger", "structuvs_vanger.html", null ]
    ] ],
    [ "uvsGamerResult", "structuvs_gamer_result.html", null ],
    [ "uvsItemType", "structuvs_item_type.html", null ],
    [ "uvsKernel", "structuvs_kernel.html", [
      [ "uvsUnitType", "structuvs_unit_type.html", [
        [ "VangerUnit", "struct_vanger_unit.html", null ]
      ] ]
    ] ],
    [ "uvsMechosType", "structuvs_mechos_type.html", null ],
    [ "uvsOrder", "structuvs_order.html", null ],
    [ "uvsTarget", "structuvs_target.html", [
      [ "uvsCrypt", "structuvs_crypt.html", null ],
      [ "uvsDolly", "structuvs_dolly.html", null ],
      [ "uvsEscave", "structuvs_escave.html", null ],
      [ "uvsFlyFarmer", "structuvs_fly_farmer.html", null ],
      [ "uvsItem", "structuvs_item.html", null ],
      [ "uvsPassage", "structuvs_passage.html", null ],
      [ "uvsRaffa", "structuvs_raffa.html", null ],
      [ "uvsSpot", "structuvs_spot.html", null ],
      [ "uvsVanger", "structuvs_vanger.html", null ]
    ] ],
    [ "VAN_WAR_PRM", "struct_v_a_n___w_a_r___p_r_m.html", null ],
    [ "VangerFunctionType", "struct_vanger_function_type.html", null ],
    [ "VanVarStatistic", "struct_van_var_statistic.html", null ],
    [ "VariablePolygon", "struct_variable_polygon.html", null ],
    [ "Vect2f", "class_vect2f.html", null ],
    [ "Vect2i", "class_vect2i.html", null ],
    [ "Vect2s", "class_vect2s.html", null ],
    [ "Vect3d", "class_vect3d.html", null ],
    [ "Vect3f", "class_vect3f.html", null ],
    [ "Vect4f", "class_vect4f.html", null ],
    [ "Vector", "struct_vector.html", null ],
    [ "Vertex", "struct_vertex.html", null ],
    [ "vrtMap", "structvrt_map.html", null ],
    [ "vrtNode", "structvrt_node.html", null ],
    [ "vrtWorld", "structvrt_world.html", null ],
    [ "WaveProcess", "struct_wave_process.html", null ],
    [ "Wheel", "struct_wheel.html", null ],
    [ "World", "struct_world.html", null ],
    [ "WorldScreen", "struct_world_screen.html", null ],
    [ "XBuffer", "struct_x_buffer.html", [
      [ "InputEventBuffer", "class_input_event_buffer.html", null ],
      [ "OutputEventBuffer", "class_output_event_buffer.html", null ],
      [ "Parser", "struct_parser.html", null ]
    ] ],
    [ "XCriticalSection", "struct_x_critical_section.html", null ],
    [ "XErrorHandler", "struct_x_error_handler.html", null ],
    [ "XGR_ColorData", "struct_x_g_r___color_data.html", null ],
    [ "XGR_Font", "struct_x_g_r___font.html", null ],
    [ "XGR_Mouse", "struct_x_g_r___mouse.html", null ],
    [ "XGR_MouseButton", "struct_x_g_r___mouse_button.html", null ],
    [ "XGR_Pal64K", "struct_x_g_r___pal64_k.html", null ],
    [ "XGR_Screen", "struct_x_g_r___screen.html", null ],
    [ "XIQueue< Type >", "class_x_i_queue.html", null ],
    [ "XJOYSTATE", "struct_x_j_o_y_s_t_a_t_e.html", null ],
    [ "XList", "struct_x_list.html", [
      [ "MessageDispatcher", "struct_message_dispatcher.html", null ],
      [ "XGR_MousePromptScreen", "struct_x_g_r___mouse_prompt_screen.html", null ]
    ] ],
    [ "XListElement", "struct_x_list_element.html", [
      [ "aciCHTreeElement", "structaci_c_h_tree_element.html", null ],
      [ "aciScreen", "structaci_screen.html", null ],
      [ "aciScreenEvent", "structaci_screen_event.html", null ],
      [ "aciScreenEventCommand", "structaci_screen_event_command.html", null ],
      [ "aciScreenFrameSequence", "structaci_screen_frame_sequence.html", null ],
      [ "aciScreenKey", "structaci_screen_key.html", null ],
      [ "aciScreenObject", "structaci_screen_object.html", [
        [ "aciScreenInputField", "structaci_screen_input_field.html", null ],
        [ "aciScreenScroller", "structaci_screen_scroller.html", null ]
      ] ],
      [ "aciScreenResource", "structaci_screen_resource.html", [
        [ "aciScreenResourceBML", "structaci_screen_resource_b_m_l.html", null ],
        [ "aciScreenResourceBMO", "structaci_screen_resource_b_m_o.html", null ],
        [ "aciScreenResourceBMP", "structaci_screen_resource_b_m_p.html", null ],
        [ "aciScreenResourceXBM", "structaci_screen_resource_x_b_m.html", null ]
      ] ],
      [ "AVIFile", "struct_a_v_i_file.html", null ],
      [ "iChatScreenObject", "structi_chat_screen_object.html", [
        [ "iChatButton", "structi_chat_button.html", null ],
        [ "iChatHistoryScreen", "structi_chat_history_screen.html", null ],
        [ "iChatInputField", "structi_chat_input_field.html", null ]
      ] ],
      [ "iScreenOptionPtr", "structi_screen_option_ptr.html", null ],
      [ "MessageElement", "struct_message_element.html", null ],
      [ "XGR_MousePromptData", "struct_x_g_r___mouse_prompt_data.html", null ],
      [ "XSysObject", "struct_x_sys_object.html", null ]
    ] ],
    [ "XMessageBuffer", "struct_x_message_buffer.html", null ],
    [ "XQueue< Type >", "class_x_queue.html", null ],
    [ "XQueue< Event >", "class_x_queue.html", null ],
    [ "XQueue< Object * >", "class_x_queue.html", null ],
    [ "XRecorder", "struct_x_recorder.html", null ],
    [ "XRecorderMessage", "struct_x_recorder_message.html", null ],
    [ "XRuntimeObject", "struct_x_runtime_object.html", [
      [ "BaseRTO", "struct_base_r_t_o.html", [
        [ "EscaveOutRTO", "struct_escave_out_r_t_o.html", null ],
        [ "EscaveRTO", "struct_escave_r_t_o.html", null ],
        [ "FirstEscaveOutRTO", "struct_first_escave_out_r_t_o.html", null ],
        [ "FirstEscaveRTO", "struct_first_escave_r_t_o.html", null ],
        [ "GameQuantRTO", "struct_game_quant_r_t_o.html", null ],
        [ "LoadingRTO1", "struct_loading_r_t_o1.html", null ],
        [ "LoadingRTO2", "struct_loading_r_t_o2.html", null ],
        [ "LoadingRTO3", "struct_loading_r_t_o3.html", null ],
        [ "MainMenuRTO", "struct_main_menu_r_t_o.html", null ],
        [ "PaletteTransformRTO", "struct_palette_transform_r_t_o.html", null ],
        [ "ShowImageRTO", "struct_show_image_r_t_o.html", [
          [ "ShowAviRTO", "struct_show_avi_r_t_o.html", null ]
        ] ]
      ] ],
      [ "KDsPlus", "struct_k_ds_plus.html", null ]
    ] ],
    [ "XSocket", "class_x_socket.html", null ],
    [ "XSoundChannelQueue", "struct_x_sound_channel_queue.html", [
      [ "XSoundChannel", "struct_x_sound_channel.html", null ]
    ] ],
    [ "XStream", "struct_x_stream.html", null ],
    [ "xtList< Type >", "classxt_list.html", null ],
    [ "XTList< Type >", "class_x_t_list.html", null ],
    [ "XTList< Game >", "class_x_t_list.html", null ],
    [ "XTList< MemTestBlock >", "class_x_t_list.html", null ],
    [ "XTList< Object >", "class_x_t_list.html", null ],
    [ "XTList< Player >", "class_x_t_list.html", null ],
    [ "XTList< PlayerData >", "class_x_t_list.html", [
      [ "PlayersList", "struct_players_list.html", null ]
    ] ],
    [ "XTList< RatingData >", "class_x_t_list.html", [
      [ "TopList", "struct_top_list.html", null ]
    ] ],
    [ "XTList< ServerFindChain >", "class_x_t_list.html", [
      [ "ServersList", "struct_servers_list.html", null ]
    ] ],
    [ "XTList< World >", "class_x_t_list.html", null ],
    [ "xtList< XZIP_FileHeader >", "classxt_list.html", null ],
    [ "XTListAlt< Type >", "class_x_t_list_alt.html", null ],
    [ "XTListAlt< Object >", "class_x_t_list_alt.html", null ],
    [ "XTListAlt< Player >", "class_x_t_list_alt.html", null ],
    [ "xtMsgHandlerObject", "structxt_msg_handler_object.html", null ],
    [ "XZIP_FileHeader", "class_x_z_i_p___file_header.html", null ],
    [ "XZIP_Resource", "class_x_z_i_p___resource.html", null ],
    [ "zCreateObjectQueue", "structz_create_object_queue.html", null ],
    [ "zServerData", "structz_server_data.html", null ]
];