Vangers: src/sound/hsound.h File Reference
hsound.h File Reference
#include "../../lib/xsound/_xsound.h"
Macros
#define ST_INTRO 2
#define ST_FOSTRAL 3
#define ST_GLORX 4
#define ST_NECROSS 5
#define ST_XPLO 6
#define ST_SECRETS 7
#define ST_GAMEOVER 8
#define ST_THEEND 9
#define ST_THEEND_DOUBLE 10
#define ST_DOUBLE 11
#define SOUND_START_MOTOR() if(EngineNoise) StartEFFECT(EFF_DRIVING,1);
#define SOUND_STOP_MOTOR() if(EngineNoise) StopEFFECT(EFF_DRIVING);
#define SOUND_MOTOR_PARAMETER(speed) if(EngineNoise) SetMotorSound(speed);
#define SOUND_OBJECT_TO_OBJECT_COLLISION() StartEFFECT(EFF_MECHOS_COLLISION);
#define SOUND_UNDERWATER_START() StartEFFECT(EFF_UNDERWATER,1);
#define SOUND_UNDERWATER_STOP() StopEFFECT(EFF_UNDERWATER);
#define SOUND_COPTERIG_START() StartEFFECT(EFF_COPTERIG,1);
#define SOUND_COPTERIG_STOP() StopEFFECT(EFF_COPTERIG);
#define SOUND_CUTTERIG_START() StartEFFECT(EFF_CUTTERIG,1);
#define SOUND_CUTTERIG_STOP() StopEFFECT(EFF_CUTTERIG);
#define SOUND_CROTRIG_START() StartEFFECT(EFF_CROTRIG,1);
#define SOUND_CROTRIG_STOP() StopEFFECT(EFF_CROTRIG);
#define SOUND_ENTRANCE(p) StartEFFECT(EFF_DOOR, 0, p);
#define SOUND_PASSAGE(p) StartEFFECT(EFF_PASSAGE, 0, p);
#define SOUND_PASSAGE_START(p) StartEFFECT(EFF_PASSAGE, 1, p);
#define SOUND_PASSAGE_STOP(p) StopEFFECT(EFF_PASSAGE);
#define SOUND_BEEB_DEATH(p) StartEFFECT(EFF_CRACK, 0, p);
#define SOUND_MACHOTINE_SHOT(p) StartEFFECT(EFF_SHOT_0, 0, p);
#define SOUND_SPEETLE_SHOT(p) StartEFFECT(EFF_SHOT_2, 0, p);
#define SOUND_GHORB_SHOT(p) StartEFFECT(EFF_SHOT_3, 0, p);
#define SOUND_GHORB_BIG_SHOT(p) StartEFFECT(EFF_SHOT_4, 0, p);
#define SOUND_BEEBBANOZA_SHOT(p) StartEFFECT(EFF_SHOT_6, 0, p);
#define SOUND_CRUSTEST_SHOT(p) StartEFFECT(EFF_SHOT_5, 0, p);
#define SOUND_TERMINATOR_SHOT(p) StartEFFECT(EFF_SHOT_1, 0, p);
#define SOUND_AMPUTATOR_SHOT(p) StartEFFECT(EFF_SHOT_1, 0, p);
#define SOUND_DEGRADATOR_SHOT(p) StartEFFECT(EFF_SHOT_1, 0, p);
#define SOUND_INCARNATOR_SHOT(p) StartEFFECT(EFF_SHOT_1, 0, p);
#define SOUND_RAFFA_SHOT(p) StartEFFECT(EFF_SHOT_RAFFA, 0, p);
#define SOUND_GLOBAL() StartEFFECT((EFFECT_VALUE)((int)EFF_BACKGROUND_0 + realRND(sndBackgroundMax)));
#define SOUND_BARREL_DESTROY(p) StartEFFECT(EFF_BARREL, 0, p);
#define SOUND_TAKE_ITEM(p) StartEFFECT(EFF_TAKE_ITEM, 0, p);
#define SOUND_HIT(p) StartEFFECT(EFF_HIT, 0, p);
#define SOUND_EXPLOSION(p) { StartEFFECT(EFF_MECHOS_EXPLOSION, 0, p); StartEFFECT(EFF_BACK_EXPLOSION, 0, p);}
#define SOUND_EXPLOSION_CRUSTER(p) {StartEFFECT(EFF_CRUSTER_EXPLOSION, 0, p);StartEFFECT(EFF_BACK_EXPLOSION, 0, p);}
#define SOUND_KIDPULL() StartEFFECT(EFF_KIDPULL);
#define SOUND_KIDPUSH() StartEFFECT(EFF_KIDPUSH);
#define SOUND_SELECT() StartEFFECT((EFFECT_VALUE)((int)EFF_SELECT_0 + realRND(3)));
#define SOUND_PICK() StartEFFECT(EFF_PICK);
#define SOUND_DROP() StartEFFECT(EFF_DROP);
#define SOUND_CHARGE() StartEFFECT(EFF_CHARGE_GHORB);
#define SOUND_CHARGE_GHORB() StartEFFECT(EFF_CHARGE_GHORB);
#define SOUND_CHARGE_MACHOTIN() StartEFFECT(EFF_CHARGE_MACHOTIN);
#define SOUND_CHARGE_REPARE() StartEFFECT(EFF_CHARGE_REPARE);
#define SOUND_CHARGE_ENERGE() StartEFFECT(EFF_CHARGE_ENERGE);
#define SOUND_CHARGE_SPIRAL() StartEFFECT(EFF_CHARGE_SPIRAL);
#define SOUND_CHARGE_RIGS() StartEFFECT(EFF_CHARGE_RIGS);
#define SOUND_CRASH() StartEFFECT(EFF_CRASH);
#define SOUND_HORDE(p) StartEFFECT(EFF_HORDE, 0, p);
#define SOUND_CYCLE() StartEFFECT(EFF_CYCLE);
#define SOUND_FAILEDPASS() StartEFFECT(EFF_FAILEDPASS);
#define SOUND_SHOCK() StartEFFECT((EFFECT_VALUE)((int)EFF_SHOCK0 + realRND(6)));
#define SOUND_SUCCESS() StartEFFECT(EFF_SUCCESS);
#define SOUND_FAILED() StartEFFECT(EFF_FAILED);
#define SOUND_THUNDER(p) StartEFFECT(EFF_THUNDER, 0, p);
#define SOUND_TOGGLE() StartEFFECT(EFF_TOGGLE);
#define SOUND_BOLT() StartEFFECT(EFF_BOLT);
#define SOUND_ACID() StartEFFECT(EFF_ACID);
#define SOUND_CHECKPOINT() StartEFFECT(EFF_CHECKPOINT);
#define SOUND_SWAMP(p) { StartEFFECT(EFF_SWAMP, 0, p); }
#define SOUND_TEAR(p) { StartEFFECT(EFF_TEAR, 0, p); }
#define SOUND_HIDEOUT(p) StartEFFECT(EFF_HIDEOUT, 0, p);
#define SOUND_GROW(p) StartEFFECT(EFF_GROW, 0, p);
#define SOUND_NOISE() StartEFFECT(EFF_NOISE);
#define SOUND_TALK0() StartEFFECT((EFFECT_VALUE)((int)EFF_TALK0 + realRND(3)));
#define SOUND_TALK1() StartEFFECT((EFFECT_VALUE)((int)EFF_TALK1 + realRND(3)));
#define SOUND_TALK2() StartEFFECT((EFFECT_VALUE)((int)EFF_TALK2 + realRND(3)));
#define SOUND_WINDOW() StartEFFECT(EFF_WINDOW);
#define SOUND_OUTIN() StartEFFECT(EFF_OUTIN);
#define SOUND_SWARM() StartEFFECT(EFF_SWARM);
#define SOUND_ANGRY() StartEFFECT(EFF_ANGRY);
#define SOUND_GETOUT() StartEFFECT(EFF_GETOUT);
#define SOUND_GATE() StartEFFECT(EFF_GATE);
#define SOUND_STEP() StartEFFECT((EFFECT_VALUE)((int)EFF_STEP0 + realRND(sndStepMax)));
#define SOUND_HAND() StartEFFECT(EFF_HAND);
#define SOUND_PUT() StartEFFECT(EFF_PUT);
#define SOUND_SCRATCH() StartEFFECT((EFFECT_VALUE)((int)EFF_SCRATCH0 + realRND(sndScratchMax)));
#define SOUND_CLAP() StartEFFECT(EFF_CLAP);
#define SOUND_BUTTON0() StartEFFECT(EFF_BUTTON0);
#define SOUND_BUTTON1() StartEFFECT(EFF_BUTTON1);
#define SOUND_BUTTON2() StartEFFECT(EFF_BUTTON2);
#define SOUND_BUTTON3() StartEFFECT(EFF_BUTTON3);
#define SOUND_BUTTON4() StartEFFECT(EFF_BUTTON4);
#define SOUND_MUSIC() StartEFFECT(EFF_MUSIC);
#define SOUND_MESSIAH() StartEFFECT(EFF_MECH_MESSIAN);
#define SOUND_MESSIAH_START() StartEFFECT(EFF_MECH_MESSIAN,1);
#define SOUND_MESSIAH_STOP() StopEFFECT(EFF_MECH_MESSIAN);
#define SOUND_PROCTRACTOR() StartEFFECT(EFF_PROCTRACTOR);
#define SOUND_PROCTRACTOR_START() StartEFFECT(EFF_PROCTRACTOR,1);
#define SOUND_PROCTRACTOR_STOP() StopEFFECT(EFF_PROCTRACTOR);
#define SOUND_BOOT() StartEFFECT(EFF_BOOTSECTOR);
#define SOUND_BOOT_START() StartEFFECT(EFF_BOOTSECTOR,1);
#define SOUND_BOOT_STOP() StopEFFECT(EFF_BOOTSECTOR);
#define SOUND_LARVA() StartEFFECT(EFF_END_LARVA);
#define SOUND_END_LARVA() StartEFFECT(EFF_END_CYCLE_LARVA);
#define SOUND_UNICUM_1() StartEFFECT(EFF_UNICUM_MECHOS_1);
#define SOUND_UNICUM_2() StartEFFECT(EFF_UNICUM_MECHOS_2);
#define SOUND_DESTROY_TERRAIN() StartEFFECT(EFF_DESTROY_TERRAIN);
#define SOUND_PR_FUNCTION_START() StartEFFECT(EFF_PROTRACTOR_FUNCTION,1);
#define SOUND_PR_FUNCTION_STOP() StopEFFECT(EFF_PROTRACTOR_FUNCTION);
#define SOUND_PR_RESIZE() StartEFFECT(EFF_PROTRACTOR_RESIZE);
#define SOUND_PR_BARRIER() StartEFFECT(EFF_PROTRACTOR_BARRIER);
#define SOUND_MES_LUCK() StartEFFECT(EFF_MESSIAN_LUCK);
#define SOUND_MES_BEEBSOSPY() StartEFFECT(EFF_MESSIAN_BEEBSOSPY);
#define SOUND_MES_FIRE() StartEFFECT(EFF_MESSIAN_FIRE);
#define SOUND_MES_CLOAK() StartEFFECT(EFF_MESSIAN_CLOAK);
#define SOUND_DISCHARGE() StartEFFECT(EFF_DISCHARGE);
#define SOUND_SPOPS_ALIES() StartEFFECT(EFF_SPOPS_ALIES);
#define SOUND_BEEP() StartEFFECT(EFF_BEEP);
#define SOUND_DAMAGE() StartEFFECT(EFF_DAMAGE);
Enumerations
enum EFFECT_VALUE {
EFF_START, EFF_DRIVING, EFF_STOP, EFF_UNDERWATER,
EFF_COPTERIG, EFF_CUTTERIG, EFF_CROTRIG, EFF_MECHOS_EXPLOSION,
EFF_BACK_EXPLOSION, EFF_CRUSTER_EXPLOSION, EFF_MECHOS_COLLISION, EFF_SHOT_0,
EFF_SHOT_1, EFF_SHOT_2, EFF_SHOT_3, EFF_SHOT_4,
EFF_SHOT_5, EFF_SHOT_6, EFF_SELECT_0, EFF_SELECT_1,
EFF_SELECT_2, EFF_BACKGROUND_0, EFF_BACKGROUND_1, EFF_BACKGROUND_2,
EFF_BACKGROUND_3, EFF_BACKGROUND_4, EFF_BACKGROUND_5, EFF_DOOR,
EFF_PASSAGE, EFF_PICK, EFF_DROP, EFF_CRACK,
EFF_GLOBAL, EFF_BARREL, EFF_TAKE_ITEM, EFF_HIT,
EFF_KIDPULL, EFF_KIDPUSH, EFF_CHARGE_GHORB, EFF_CHARGE_MACHOTIN,
EFF_CHARGE_REPARE, EFF_CHARGE_ENERGE, EFF_CHARGE_SPIRAL, EFF_CHARGE_RIGS,
EFF_CRASH, EFF_HORDE, EFF_CYCLE, EFF_FAILEDPASS,
EFF_SHOCK0, EFF_SHOCK1, EFF_SHOCK2, EFF_SHOCK3,
EFF_SHOCK4, EFF_SHOCK5, EFF_SUCCESS, EFF_FAILED,
EFF_THUNDER, EFF_TOGGLE, EFF_BOLT, EFF_ACID,
EFF_CHECKPOINT, EFF_SWAMP, EFF_TEAR, EFF_HIDEOUT,
EFF_GROW, EFF_NOISE, EFF_TALK0, EFF_TALK01,
EFF_TALK02, EFF_TALK1, EFF_TALK11, EFF_TALK12,
EFF_TALK2, EFF_TALK21, EFF_TALK22, EFF_WINDOW,
EFF_OUTIN, EFF_SWARM, EFF_ANGRY, EFF_GETOUT,
EFF_GATE, EFF_STEP0, EFF_STEP1, EFF_STEP2,
EFF_HAND, EFF_SCRATCH0, EFF_SCRATCH1, EFF_CLAP,
EFF_MECH_MESSIAN, EFF_PROCTRACTOR, EFF_BOOTSECTOR, EFF_END_LARVA,
EFF_END_CYCLE_LARVA, EFF_UNICUM_MECHOS_1, EFF_UNICUM_MECHOS_2, EFF_DESTROY_TERRAIN,
EFF_DISCHARGE, EFF_PROTRACTOR_FUNCTION, EFF_PROTRACTOR_RESIZE, EFF_PROTRACTOR_BARRIER,
EFF_MESSIAN_CLOAK, EFF_MESSIAN_BEEBSOSPY, EFF_MESSIAN_FIRE, EFF_SPOPS_ALIES,
EFF_BEEP, EFF_DAMAGE, EFF_SHOT_RAFFA, EFF_MAX
}
enum SPEECH_VALUE { SPEECH_MUFLER, SPEECH_MAX }
Functions
void InstallSOUND (void)
void RestoreSOUND (void)
void LoadResourceSOUND (const char *, int surface=1)
void EffectsOnOff (void)
void EffectsOn (int surface=1)
void EffectsOff (void)
void SetSoundVolume (int value)
void SoundQuant (void)
void SoundEscaveOff (void)
void SetMotorSound (int speed)
void SetMotorFile (int type)
void StartSPEECH (SPEECH_VALUE SpeechValue)
void StartEFFECT (EFFECT_VALUE EffectValue, int loop=0, int pan=0)
void StopEFFECT (EFFECT_VALUE EffectValue)
void StartCDTRACK (void)
void PauseCDTRACK (void)
void ResumeCDTRACK (void)
void StopCDTRACK (void)
void StartWTRACK (void)
void SlowCDTRACK (void)
void MainMenuSoundQuant (int TRACK=ST_INTRO)
void LocalEffectFree (void)
void LastSoundQuant (void)
void LastStartWTRACK (int TRACK)
Variables
int sndBackgroundMax
int sndStepMax
int sndScratchMax
int SoundFlag
int EngineNoise
int Backgroundound
const int SoundCopterig = 0x00000001
const int SoundCrotrig = 0x00000002
const int SoundCutterig = 0x00000004
const int SoundUnderWater = 0x00000008
const int SoundMotor = 0x00000010
Macro Definition Documentation
SOUND_ACID
#define SOUND_ACID () StartEFFECT(EFF_ACID);
SOUND_AMPUTATOR_SHOT
#define SOUND_AMPUTATOR_SHOT (p) StartEFFECT(EFF_SHOT_1, 0, p);
SOUND_ANGRY
#define SOUND_ANGRY () StartEFFECT(EFF_ANGRY);
SOUND_BARREL_DESTROY
#define SOUND_BARREL_DESTROY (p) StartEFFECT(EFF_BARREL, 0, p);
SOUND_BEEB_DEATH
#define SOUND_BEEB_DEATH (p) StartEFFECT(EFF_CRACK, 0, p);
SOUND_BEEBBANOZA_SHOT
#define SOUND_BEEBBANOZA_SHOT (p) StartEFFECT(EFF_SHOT_6, 0, p);
SOUND_BEEP
#define SOUND_BEEP () StartEFFECT(EFF_BEEP);
SOUND_BOLT
#define SOUND_BOLT () StartEFFECT(EFF_BOLT);
SOUND_BOOT
#define SOUND_BOOT () StartEFFECT(EFF_BOOTSECTOR);
SOUND_BOOT_START
#define SOUND_BOOT_START () StartEFFECT(EFF_BOOTSECTOR,1);
SOUND_BOOT_STOP
#define SOUND_BOOT_STOP () StopEFFECT(EFF_BOOTSECTOR);
SOUND_BUTTON0
#define SOUND_BUTTON0 () StartEFFECT(EFF_BUTTON0);
SOUND_BUTTON1
#define SOUND_BUTTON1 () StartEFFECT(EFF_BUTTON1);
SOUND_BUTTON2
#define SOUND_BUTTON2 () StartEFFECT(EFF_BUTTON2);
SOUND_BUTTON3
#define SOUND_BUTTON3 () StartEFFECT(EFF_BUTTON3);
SOUND_BUTTON4
#define SOUND_BUTTON4 () StartEFFECT(EFF_BUTTON4);
SOUND_CHARGE
#define SOUND_CHARGE () StartEFFECT(EFF_CHARGE_GHORB);
SOUND_CHARGE_ENERGE
#define SOUND_CHARGE_ENERGE () StartEFFECT(EFF_CHARGE_ENERGE);
SOUND_CHARGE_GHORB
#define SOUND_CHARGE_GHORB () StartEFFECT(EFF_CHARGE_GHORB);
SOUND_CHARGE_MACHOTIN
#define SOUND_CHARGE_MACHOTIN () StartEFFECT(EFF_CHARGE_MACHOTIN);
SOUND_CHARGE_REPARE
#define SOUND_CHARGE_REPARE () StartEFFECT(EFF_CHARGE_REPARE);
SOUND_CHARGE_RIGS
#define SOUND_CHARGE_RIGS () StartEFFECT(EFF_CHARGE_RIGS);
SOUND_CHARGE_SPIRAL
#define SOUND_CHARGE_SPIRAL () StartEFFECT(EFF_CHARGE_SPIRAL);
SOUND_CHECKPOINT
#define SOUND_CHECKPOINT () StartEFFECT(EFF_CHECKPOINT);
SOUND_CLAP
#define SOUND_CLAP () StartEFFECT(EFF_CLAP);
SOUND_COPTERIG_START
#define SOUND_COPTERIG_START () StartEFFECT(EFF_COPTERIG,1);
SOUND_COPTERIG_STOP
#define SOUND_COPTERIG_STOP () StopEFFECT(EFF_COPTERIG);
SOUND_CRASH
#define SOUND_CRASH () StartEFFECT(EFF_CRASH);
SOUND_CROTRIG_START
#define SOUND_CROTRIG_START () StartEFFECT(EFF_CROTRIG,1);
SOUND_CROTRIG_STOP
#define SOUND_CROTRIG_STOP () StopEFFECT(EFF_CROTRIG);
SOUND_CRUSTEST_SHOT
#define SOUND_CRUSTEST_SHOT (p) StartEFFECT(EFF_SHOT_5, 0, p);
SOUND_CUTTERIG_START
#define SOUND_CUTTERIG_START () StartEFFECT(EFF_CUTTERIG,1);
SOUND_CUTTERIG_STOP
#define SOUND_CUTTERIG_STOP () StopEFFECT(EFF_CUTTERIG);
SOUND_CYCLE
#define SOUND_CYCLE () StartEFFECT(EFF_CYCLE);
SOUND_DAMAGE
#define SOUND_DAMAGE () StartEFFECT(EFF_DAMAGE);
SOUND_DEGRADATOR_SHOT
#define SOUND_DEGRADATOR_SHOT (p) StartEFFECT(EFF_SHOT_1, 0, p);
SOUND_DESTROY_TERRAIN
#define SOUND_DESTROY_TERRAIN () StartEFFECT(EFF_DESTROY_TERRAIN);
SOUND_DISCHARGE
#define SOUND_DISCHARGE () StartEFFECT(EFF_DISCHARGE);
SOUND_DROP
#define SOUND_DROP () StartEFFECT(EFF_DROP);
SOUND_END_LARVA
#define SOUND_END_LARVA () StartEFFECT(EFF_END_CYCLE_LARVA);
SOUND_ENTRANCE
#define SOUND_ENTRANCE (p) StartEFFECT(EFF_DOOR, 0, p);
SOUND_EXPLOSION
#define SOUND_EXPLOSION (p) { StartEFFECT(EFF_MECHOS_EXPLOSION, 0, p); StartEFFECT(EFF_BACK_EXPLOSION, 0, p);}
SOUND_EXPLOSION_CRUSTER
#define SOUND_EXPLOSION_CRUSTER (p) {StartEFFECT(EFF_CRUSTER_EXPLOSION, 0, p);StartEFFECT(EFF_BACK_EXPLOSION, 0, p);}
SOUND_FAILED
#define SOUND_FAILED () StartEFFECT(EFF_FAILED);
SOUND_FAILEDPASS
#define SOUND_FAILEDPASS () StartEFFECT(EFF_FAILEDPASS);
SOUND_GATE
#define SOUND_GATE () StartEFFECT(EFF_GATE);
SOUND_GETOUT
#define SOUND_GETOUT () StartEFFECT(EFF_GETOUT);
SOUND_GHORB_BIG_SHOT
#define SOUND_GHORB_BIG_SHOT (p) StartEFFECT(EFF_SHOT_4, 0, p);
SOUND_GHORB_SHOT
#define SOUND_GHORB_SHOT (p) StartEFFECT(EFF_SHOT_3, 0, p);
SOUND_GLOBAL
#define SOUND_GLOBAL () StartEFFECT((EFFECT_VALUE)((int)EFF_BACKGROUND_0 + realRND(sndBackgroundMax)));
SOUND_GROW
#define SOUND_GROW (p) StartEFFECT(EFF_GROW, 0, p);
SOUND_HAND
#define SOUND_HAND () StartEFFECT(EFF_HAND);
SOUND_HIDEOUT
#define SOUND_HIDEOUT (p) StartEFFECT(EFF_HIDEOUT, 0, p);
SOUND_HIT
#define SOUND_HIT (p) StartEFFECT(EFF_HIT, 0, p);
SOUND_HORDE
#define SOUND_HORDE (p) StartEFFECT(EFF_HORDE, 0, p);
SOUND_INCARNATOR_SHOT
#define SOUND_INCARNATOR_SHOT (p) StartEFFECT(EFF_SHOT_1, 0, p);
SOUND_KIDPULL
#define SOUND_KIDPULL () StartEFFECT(EFF_KIDPULL);
SOUND_KIDPUSH
#define SOUND_KIDPUSH () StartEFFECT(EFF_KIDPUSH);
SOUND_LARVA
#define SOUND_LARVA () StartEFFECT(EFF_END_LARVA);
SOUND_MACHOTINE_SHOT
#define SOUND_MACHOTINE_SHOT (p) StartEFFECT(EFF_SHOT_0, 0, p);
SOUND_MES_BEEBSOSPY
#define SOUND_MES_BEEBSOSPY () StartEFFECT(EFF_MESSIAN_BEEBSOSPY);
SOUND_MES_CLOAK
#define SOUND_MES_CLOAK () StartEFFECT(EFF_MESSIAN_CLOAK);
SOUND_MES_FIRE
#define SOUND_MES_FIRE () StartEFFECT(EFF_MESSIAN_FIRE);
SOUND_MES_LUCK
#define SOUND_MES_LUCK () StartEFFECT(EFF_MESSIAN_LUCK);
SOUND_MESSIAH
#define SOUND_MESSIAH () StartEFFECT(EFF_MECH_MESSIAN);
SOUND_MESSIAH_START
#define SOUND_MESSIAH_START () StartEFFECT(EFF_MECH_MESSIAN,1);
SOUND_MESSIAH_STOP
#define SOUND_MESSIAH_STOP () StopEFFECT(EFF_MECH_MESSIAN);
SOUND_MOTOR_PARAMETER
#define SOUND_MOTOR_PARAMETER (speed) if(EngineNoise) SetMotorSound(speed);
SOUND_MUSIC
#define SOUND_MUSIC () StartEFFECT(EFF_MUSIC);
SOUND_NOISE
#define SOUND_NOISE () StartEFFECT(EFF_NOISE);
SOUND_OBJECT_TO_OBJECT_COLLISION
#define SOUND_OBJECT_TO_OBJECT_COLLISION () StartEFFECT(EFF_MECHOS_COLLISION);
SOUND_OUTIN
#define SOUND_OUTIN () StartEFFECT(EFF_OUTIN);
SOUND_PASSAGE
#define SOUND_PASSAGE (p) StartEFFECT(EFF_PASSAGE, 0, p);
SOUND_PASSAGE_START
#define SOUND_PASSAGE_START (p) StartEFFECT(EFF_PASSAGE, 1, p);
SOUND_PASSAGE_STOP
#define SOUND_PASSAGE_STOP (p) StopEFFECT(EFF_PASSAGE);
SOUND_PICK
#define SOUND_PICK () StartEFFECT(EFF_PICK);
SOUND_PR_BARRIER
#define SOUND_PR_BARRIER () StartEFFECT(EFF_PROTRACTOR_BARRIER);
SOUND_PR_FUNCTION_START
#define SOUND_PR_FUNCTION_START () StartEFFECT(EFF_PROTRACTOR_FUNCTION,1);
SOUND_PR_FUNCTION_STOP
#define SOUND_PR_FUNCTION_STOP () StopEFFECT(EFF_PROTRACTOR_FUNCTION);
SOUND_PR_RESIZE
#define SOUND_PR_RESIZE () StartEFFECT(EFF_PROTRACTOR_RESIZE);
SOUND_PROCTRACTOR
#define SOUND_PROCTRACTOR () StartEFFECT(EFF_PROCTRACTOR);
SOUND_PROCTRACTOR_START
#define SOUND_PROCTRACTOR_START () StartEFFECT(EFF_PROCTRACTOR,1);
SOUND_PROCTRACTOR_STOP
#define SOUND_PROCTRACTOR_STOP () StopEFFECT(EFF_PROCTRACTOR);
SOUND_PUT
#define SOUND_PUT () StartEFFECT(EFF_PUT);
SOUND_RAFFA_SHOT
#define SOUND_RAFFA_SHOT (p) StartEFFECT(EFF_SHOT_RAFFA, 0, p);
SOUND_SCRATCH
#define SOUND_SCRATCH () StartEFFECT((EFFECT_VALUE)((int)EFF_SCRATCH0 + realRND(sndScratchMax)));
SOUND_SELECT
#define SOUND_SELECT () StartEFFECT((EFFECT_VALUE)((int)EFF_SELECT_0 + realRND(3)));
SOUND_SHOCK
#define SOUND_SHOCK () StartEFFECT((EFFECT_VALUE)((int)EFF_SHOCK0 + realRND(6)));
SOUND_SPEETLE_SHOT
#define SOUND_SPEETLE_SHOT (p) StartEFFECT(EFF_SHOT_2, 0, p);
SOUND_SPOPS_ALIES
#define SOUND_SPOPS_ALIES () StartEFFECT(EFF_SPOPS_ALIES);
SOUND_START_MOTOR
#define SOUND_START_MOTOR () if(EngineNoise) StartEFFECT(EFF_DRIVING,1);
SOUND_STEP
#define SOUND_STEP () StartEFFECT((EFFECT_VALUE)((int)EFF_STEP0 + realRND(sndStepMax)));
SOUND_STOP_MOTOR
#define SOUND_STOP_MOTOR () if(EngineNoise) StopEFFECT(EFF_DRIVING);
SOUND_SUCCESS
#define SOUND_SUCCESS () StartEFFECT(EFF_SUCCESS);
SOUND_SWAMP
#define SOUND_SWAMP (p) { StartEFFECT(EFF_SWAMP, 0, p); }
SOUND_SWARM
#define SOUND_SWARM () StartEFFECT(EFF_SWARM);
SOUND_TAKE_ITEM
#define SOUND_TAKE_ITEM (p) StartEFFECT(EFF_TAKE_ITEM, 0, p);
SOUND_TALK0
#define SOUND_TALK0 () StartEFFECT((EFFECT_VALUE)((int)EFF_TALK0 + realRND(3)));
SOUND_TALK1
#define SOUND_TALK1 () StartEFFECT((EFFECT_VALUE)((int)EFF_TALK1 + realRND(3)));
SOUND_TALK2
#define SOUND_TALK2 () StartEFFECT((EFFECT_VALUE)((int)EFF_TALK2 + realRND(3)));
SOUND_TEAR
#define SOUND_TEAR (p) { StartEFFECT(EFF_TEAR, 0, p); }
SOUND_TERMINATOR_SHOT
#define SOUND_TERMINATOR_SHOT (p) StartEFFECT(EFF_SHOT_1, 0, p);
SOUND_THUNDER
#define SOUND_THUNDER (p) StartEFFECT(EFF_THUNDER, 0, p);
SOUND_TOGGLE
#define SOUND_TOGGLE () StartEFFECT(EFF_TOGGLE);
SOUND_UNDERWATER_START
#define SOUND_UNDERWATER_START () StartEFFECT(EFF_UNDERWATER,1);
SOUND_UNDERWATER_STOP
#define SOUND_UNDERWATER_STOP () StopEFFECT(EFF_UNDERWATER);
SOUND_UNICUM_1
#define SOUND_UNICUM_1 () StartEFFECT(EFF_UNICUM_MECHOS_1);
SOUND_UNICUM_2
#define SOUND_UNICUM_2 () StartEFFECT(EFF_UNICUM_MECHOS_2);
SOUND_WINDOW
#define SOUND_WINDOW () StartEFFECT(EFF_WINDOW);
ST_DOUBLE
#define ST_DOUBLE 11
ST_FOSTRAL
#define ST_FOSTRAL 3
ST_GAMEOVER
#define ST_GAMEOVER 8
ST_GLORX
#define ST_GLORX 4
ST_INTRO
#define ST_INTRO 2
ST_NECROSS
#define ST_NECROSS 5
ST_SECRETS
#define ST_SECRETS 7
ST_THEEND
#define ST_THEEND 9
ST_THEEND_DOUBLE
#define ST_THEEND_DOUBLE 10
ST_XPLO
#define ST_XPLO 6
Enumeration Type Documentation
EFFECT_VALUE
enum EFFECT_VALUE
Enumerator
EFF_START
EFF_DRIVING
EFF_STOP
EFF_UNDERWATER
EFF_COPTERIG
EFF_CUTTERIG
EFF_CROTRIG
EFF_MECHOS_EXPLOSION
EFF_BACK_EXPLOSION
EFF_CRUSTER_EXPLOSION
EFF_MECHOS_COLLISION
EFF_SHOT_0
EFF_SHOT_1
EFF_SHOT_2
EFF_SHOT_3
EFF_SHOT_4
EFF_SHOT_5
EFF_SHOT_6
EFF_SELECT_0
EFF_SELECT_1
EFF_SELECT_2
EFF_BACKGROUND_0
EFF_BACKGROUND_1
EFF_BACKGROUND_2
EFF_BACKGROUND_3
EFF_BACKGROUND_4
EFF_BACKGROUND_5
EFF_DOOR
EFF_PASSAGE
EFF_PICK
EFF_DROP
EFF_CRACK
EFF_GLOBAL
EFF_BARREL
EFF_TAKE_ITEM
EFF_HIT
EFF_KIDPULL
EFF_KIDPUSH
EFF_CHARGE_GHORB
EFF_CHARGE_MACHOTIN
EFF_CHARGE_REPARE
EFF_CHARGE_ENERGE
EFF_CHARGE_SPIRAL
EFF_CHARGE_RIGS
EFF_CRASH
EFF_HORDE
EFF_CYCLE
EFF_FAILEDPASS
EFF_SHOCK0
EFF_SHOCK1
EFF_SHOCK2
EFF_SHOCK3
EFF_SHOCK4
EFF_SHOCK5
EFF_SUCCESS
EFF_FAILED
EFF_THUNDER
EFF_TOGGLE
EFF_BOLT
EFF_ACID
EFF_CHECKPOINT
EFF_SWAMP
EFF_TEAR
EFF_HIDEOUT
EFF_GROW
EFF_NOISE
EFF_TALK0
EFF_TALK01
EFF_TALK02
EFF_TALK1
EFF_TALK11
EFF_TALK12
EFF_TALK2
EFF_TALK21
EFF_TALK22
EFF_WINDOW
EFF_OUTIN
EFF_SWARM
EFF_ANGRY
EFF_GETOUT
EFF_GATE
EFF_STEP0
EFF_STEP1
EFF_STEP2
EFF_HAND
EFF_SCRATCH0
EFF_SCRATCH1
EFF_CLAP
EFF_MECH_MESSIAN
EFF_PROCTRACTOR
EFF_BOOTSECTOR
EFF_END_LARVA
EFF_END_CYCLE_LARVA
EFF_UNICUM_MECHOS_1
EFF_UNICUM_MECHOS_2
EFF_DESTROY_TERRAIN
EFF_DISCHARGE
EFF_PROTRACTOR_FUNCTION
EFF_PROTRACTOR_RESIZE
EFF_PROTRACTOR_BARRIER
EFF_MESSIAN_CLOAK
EFF_MESSIAN_BEEBSOSPY
EFF_MESSIAN_FIRE
EFF_SPOPS_ALIES
EFF_BEEP
EFF_DAMAGE
EFF_SHOT_RAFFA
EFF_MAX
                   {
     EFF_START,
     EFF_DRIVING,
     EFF_STOP,
     EFF_UNDERWATER,
     EFF_COPTERIG,
     EFF_CUTTERIG,
     EFF_CROTRIG,
     EFF_MECHOS_EXPLOSION,
     EFF_BACK_EXPLOSION,
     EFF_CRUSTER_EXPLOSION,
     EFF_MECHOS_COLLISION,
     EFF_SHOT_0,
     EFF_SHOT_1,
     EFF_SHOT_2,
     EFF_SHOT_3,
     EFF_SHOT_4,
     EFF_SHOT_5,
     EFF_SHOT_6,
     EFF_SELECT_0,
     EFF_SELECT_1,
     EFF_SELECT_2,
     EFF_BACKGROUND_0,
     EFF_BACKGROUND_1,
     EFF_BACKGROUND_2,
     EFF_BACKGROUND_3,
     EFF_BACKGROUND_4,
     EFF_BACKGROUND_5,
     EFF_DOOR,
     EFF_PASSAGE,
     EFF_PICK,
     EFF_DROP,
     EFF_CRACK,
     EFF_GLOBAL,
     EFF_BARREL,
     EFF_TAKE_ITEM,
     EFF_HIT,
     EFF_KIDPULL,
     EFF_KIDPUSH,
     EFF_CHARGE_GHORB,
     EFF_CHARGE_MACHOTIN,
     EFF_CHARGE_REPARE,
     EFF_CHARGE_ENERGE,
     EFF_CHARGE_SPIRAL,
     EFF_CHARGE_RIGS,
     EFF_CRASH,
     EFF_HORDE,
     EFF_CYCLE,
     EFF_FAILEDPASS,
     EFF_SHOCK0,
     EFF_SHOCK1,
     EFF_SHOCK2,
     EFF_SHOCK3,
     EFF_SHOCK4,
     EFF_SHOCK5,
     EFF_SUCCESS,
     EFF_FAILED,
     EFF_THUNDER,
     EFF_TOGGLE,
     EFF_BOLT,
     EFF_ACID,
     EFF_CHECKPOINT,
     EFF_SWAMP,
     EFF_TEAR,
     EFF_HIDEOUT,
     EFF_GROW,
     EFF_NOISE,
     EFF_TALK0,
     EFF_TALK01,
     EFF_TALK02,
     EFF_TALK1,
     EFF_TALK11,
     EFF_TALK12,
     EFF_TALK2,
     EFF_TALK21,
     EFF_TALK22,
     EFF_WINDOW,
     EFF_OUTIN,
     EFF_SWARM,
     EFF_ANGRY,
     EFF_GETOUT,
     EFF_GATE,
     EFF_STEP0,
     EFF_STEP1,
     EFF_STEP2,
     EFF_HAND,
     EFF_SCRATCH0,
     EFF_SCRATCH1,
     EFF_CLAP,
     EFF_MECH_MESSIAN,
     EFF_PROCTRACTOR,
     EFF_BOOTSECTOR,
     EFF_END_LARVA,
     EFF_END_CYCLE_LARVA,
     EFF_UNICUM_MECHOS_1,
     EFF_UNICUM_MECHOS_2,
     EFF_DESTROY_TERRAIN,
     EFF_DISCHARGE,
     EFF_PROTRACTOR_FUNCTION,
     EFF_PROTRACTOR_RESIZE,
     EFF_PROTRACTOR_BARRIER,
     EFF_MESSIAN_CLOAK,
 //  EFF_MESSIAN_LUCK,
     EFF_MESSIAN_BEEBSOSPY,
     EFF_MESSIAN_FIRE,
     EFF_SPOPS_ALIES,
     EFF_BEEP,
     EFF_DAMAGE,
     EFF_SHOT_RAFFA,
     EFF_MAX
     };
SPEECH_VALUE
enum SPEECH_VALUE
Enumerator
SPEECH_MUFLER
SPEECH_MAX
                   {
     SPEECH_MUFLER,
     SPEECH_MAX
     };
Function Documentation
EffectsOff()
void EffectsOff (void)
 {
     if(EffectInUsePriory && EffectInUse){
         for(int i = 0;i < 16;i++) SoundStop(i);
         EffectInUse = 0;
         lastSoundFlag = 0;
         //SoundVolumeCD = -1;
     }
 }
References EffectInUse, EffectInUsePriory, lastSoundFlag, and SoundStop().
Referenced by LoadResourceSOUND(), LocalEffectFree(), and SoundEscaveOff().
EffectsOn()
void EffectsOn (int surface = 1)
 {
     if(EffectInUsePriory && !EffectInUse) EffectInUse = 1;
 }
References EffectInUse, and EffectInUsePriory.
Referenced by iHandleExtEvent(), and GameQuantRTO::Quant().
EffectsOnOff()
void EffectsOnOff (void)
 {
     if(EffectInUsePriory){
         EffectInUse = 1 - EffectInUse;
         if(!EffectInUse) {
             for(int i = 0;i < 16;i++) SoundStop(i);
             lastSoundFlag = 0;
         }
     }
 }
References EffectInUse, EffectInUsePriory, lastSoundFlag, and SoundStop().
InstallSOUND()
void InstallSOUND (void)
 {
     if (lang() == RUSSIAN) {
         TrackCDTime = new int[11] { 0, 1, 174, 108, 128, 238, 130, 181, 120, 151, 200 };
     } else {
         TrackCDTime = new int[11] { 0, 1, 174, 108, 128, 238, 130, 181, 120, 151, 60 };
     }
     if(!SoundInit(EFFECT_KHZ, 16)){
         std::cout<<"\nInitialization of sound failed, mute mode accepted...\n";
         MuteLog = 1;
         return;
         }
     EffectInUsePriory = EffectInUse = 1;
 //  xsInitCD();
     xsInitMusic();
 }
References lang(), and RUSSIAN.
Referenced by xtInitApplication().
LastSoundQuant()
void LastSoundQuant (void)
{
     if(!MusicON) return;
     time_t l_time;
     time(&l_time);
     if (l_time - lastTimeCD > TimeCD){
 //      int status = xsGetStatusCD();
         int status = xsGetStatusMusic();
         if (status & XCD_PAUSED){
             if (LastTrack == ST_DOUBLE){
 //              xsPlayCD(ST_THEEND);
                 xsPlayMusic(ST_THEEND);
                 TimeCD = TrackCDTime[ST_THEEND] + TrackCDTime[ST_THEEND_DOUBLE];
             }else{
                 if (LastTrack == ST_THEEND_DOUBLE)
 //                  xsPlayCD(LastTrack);
                     xsPlayMusic(LastTrack);
                 else
 //                  xsPlayOneTrackCD(LastTrack);
                     xsPlayOneTrackMusic(LastTrack);
                 TimeCD = TrackCDTime[LastTrack];
             }
             time(&lastTimeCD);
         }
     }
 }
References MusicON.
Referenced by ShowImageRTO::Quant().
LastStartWTRACK()
void LastStartWTRACK (int TRACK)
 {
     if(!MusicON) return;
     LastTrack = TRACK;
     if (TRACK == ST_DOUBLE){
 //      xsPlayCD(ST_THEEND);
         xsPlayMusic(ST_THEEND);
         TimeCD = TrackCDTime[ST_THEEND] + TrackCDTime[ST_THEEND_DOUBLE];
     }else{
         if (TRACK == ST_THEEND_DOUBLE)
 //          xsPlayCD(TRACK);
             xsPlayMusic(TRACK);
         else
 //          xsPlayOneTrackCD(TRACK);
             xsPlayOneTrackMusic(TRACK);
         TimeCD = TrackCDTime[TRACK];
     }
     time(&lastTimeCD);
     activeWTRACK = 1;
 }
References MusicON.
Referenced by ShowImageRTO::Init().
LoadResourceSOUND()
void LoadResourceSOUND (const char * , int surface = 1)
 {
     int i;
     //if(MuteLog) return;
     EffectsOff();
     XBuffer buf;
     XStream ff(0);
     for(i = 0;i < EFF_MAX;i++) {
         if ((SndData[i].status & LOCAL_SOUND) && SndData[i].lpDSB && surface) {
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
         buf.init();
         if((i == EFF_DRIVING) || (i == EFF_START) || (i == EFF_STOP)) {
             if(EngineNoise) {
                 buf < "resource/sound/effects" < "/" < SndData[i].fname < ".wav";
             } else {
                 continue;
             }
         } else {
             buf < path_name < "/" < SndData[i].fname < ".wav";
         }
         if(ff.open(buf.GetBuf(),XS_IN)){
             ff.close();
             if (SndData[i].lpDSB){
                 SoundRelease(SndData[i].lpDSB);
                 SndData[i].lpDSB = NULL;
                 }
             SoundLoad(buf.GetBuf(),&SndData[i].lpDSB);
         }
         //std::cout<<"file:"<<buf.GetBuf()<<" addr:"<<SndData[i].lpDSB<<std::endl;
     }
     EffectsOn(surface);
     sndBackgroundMax = sndStepMax = sndScratchMax = 0;
     for(i = EFF_BACKGROUND_0;i <= EFF_BACKGROUND_5;i++)
         if(SndData[i].lpDSB) sndBackgroundMax++;
     for(i = EFF_STEP0;i <= EFF_STEP2;i++)
         if(SndData[i].lpDSB) sndStepMax++;
     for(i = EFF_SCRATCH0;i <= EFF_SCRATCH1;i++)
         if(SndData[i].lpDSB) sndScratchMax++;
 }
References EFF_MAX, and EffectsOff().
LocalEffectFree()
void LocalEffectFree (void)
{
     EffectsOff();
     for(int i = 0;i < EFF_MAX;i++){
         if ((SndData[i].status & LOCAL_SOUND) && SndData[i].lpDSB){
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
     }
     EffectsOn(1);
 }
References EFF_MAX, and EffectsOff().
Referenced by LoadingRTO3::Init().
MainMenuSoundQuant()
void MainMenuSoundQuant (int TRACK = ST_INTRO)
{
 #ifndef _DEMO_
     if(!MusicON) return;
 //  int track = xsGetCurTrackCD();
 //  int status = xsGetStatusCD();
     int status = xsGetStatusMusic();
     if (SoundVolumeCD == -1)
 //          SoundVolumeCD = xsGetVolumeCD();
             SoundVolumeCD = xsGetVolumeMusic();
 //  if ( TRACK != track || !activeWTRACK )
     time_t l_time;
     time(&l_time);
     if (l_time - lastTimeCD > TimeCD){
 //      int status = xsGetStatusCD();
         int status = xsGetStatusMusic();
         if (status & XCD_PAUSED){
 //          xsPlayOneTrackCD(TRACK);
             xsPlayOneTrackMusic(TRACK);
             TimeCD = TrackCDTime[TRACK];
             time(&lastTimeCD);
         }
     } else  if ( !activeWTRACK ){
 //      xsPlayOneTrackCD(TRACK);
         xsPlayOneTrackMusic(TRACK);
         TimeCD = TrackCDTime[TRACK];
         time(&lastTimeCD);
     }
     activeWTRACK = 1;
 #endif
 }
References MusicON, SoundVolumeCD, xsGetStatusMusic(), and xsGetVolumeMusic().
Referenced by MainMenuRTO::Quant().
PauseCDTRACK()
void PauseCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsPauseCD();
     xsPauseMusic();
 #endif
 }
References MusicON, and xsPauseMusic().
RestoreSOUND()
void RestoreSOUND (void)
 {
     delete[] TrackCDTime;
 #ifndef _NO_CDAUDIO_
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsStopCD();
     xsStopMusic();
     xsDeInitMusic();
 #endif
 #endif
 }
Referenced by restore().
ResumeCDTRACK()
void ResumeCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsResumeCD();
     xsResumeMusic();
 #endif
 }
References MusicON, and xsResumeMusic().
SetMotorFile()
void SetMotorFile (int type)
{
     SndData[EFF_DRIVING].fname = SndMotorFileName[type*2];
 //  SndData[EFF_START].fname = SndMotorFileName[type*3+1];
     SndData[EFF_STOP].fname = SndMotorFileName[type*2+1];
     LoadMotorSound();
 }
SetMotorSound()
void SetMotorSound (int speed)
{
     if ((speed > 0) && (speed < 11)){
         if(SndData[EffectInFrequence].lpDSB)
             SetSoundFrequency(SndData[EffectInFrequence].lpDSB, EFFECT_KHZ + DELTA_KHZ*speed);
         if(SndData[EffectInFrequence + 1].lpDSB)
             SetSoundFrequency(SndData[EffectInFrequence + 1].lpDSB, EFFECT_KHZ + DELTA_KHZ*speed);
         }
 }
SetSoundVolume()
void SetSoundVolume (int value)
 {
     //std::cout<<"SetSoundVolume:"<<value<<std::endl;
     if(EffectInUsePriory){
 //      xsSetVolumeWAVE(value);
         soundVolumecurrent = soundVolume = value;
         //soundVolumecurrent = soundVolume = DB_MIN + round(log10(9.0*log(double(value))/(log(2.0)*8) + 1.0)*DB_SIZE);
     }
 }
References EffectInUsePriory.
SlowCDTRACK()
void SlowCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
     if (SlowOn){
 //      LocalVolume = xsGetVolumeCD();
         LocalVolume = xsGetVolumeMusic();
         DeltaVolume = (LocalVolume/40) + 1;
     }
     SlowOn = 0;
 //  LocalVolume = xsGetVolumeCD() - DeltaVolume;
     LocalVolume = xsGetVolumeMusic() - DeltaVolume;
     if (LocalVolume > 0 )
 //      xsSetVolumeCD(LocalVolume);
         xsSetVolumeMusic(LocalVolume);
     else{
 //      xsStopCD();
         xsStopMusic();
         activeWTRACK = 0;
         SlowOn = 1;
     }
 #endif
 }
References MusicON.
Referenced by aciShowLocation().
SoundEscaveOff()
void SoundEscaveOff (void)
{
     EffectsOff();
     for(int i = 0;i < EFF_MAX;i++){
         if ((SndData[i].status & ESCAVE_SOUND) && SndData[i].lpDSB){
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
     }
     EffectsOn(0);
 }
References EFF_MAX, and EffectsOff().
SoundQuant()
void SoundQuant (void)
 {
     if(!EffectInUse) return;
     if(MusicON){
         int _world_ = CurrentWorld;
         int Distance = DISTANCE_TO_TOWN;
         if (_world_ > 3) {
             _world_ = 4;
             Distance = DISTANCE_TO_SICRET;
         }
 //      int len = GetEscaveDist();
         if (SoundVolumeCD == -1)
 //          SoundVolumeCD = xsGetVolumeCD();
             SoundVolumeCD = xsGetVolumeMusic();
 /*      if ( len == -1 )
             xsSetVolumeCD(0);
         else*/ {
             time_t l_time;
             time(&l_time);
             if (l_time - lastTimeCD > TimeCD){
 //              int status = xsGetStatusCD();
                 int status = xsGetStatusMusic();
                 if (status & XCD_PAUSED)
                     StartWTRACK();
             }
 //          if(len > Distance) len = 0; else len = Distance - abs(len);
         }
 //      xsSetVolumeCD(len*SoundVolumeCD/Distance);
     }
     int DiffSound = SoundFlag ^ lastSoundFlag;
     if (DiffSound){
         if (DiffSound & SoundCopterig) {
             if (SoundFlag & SoundCopterig) {
                 SOUND_COPTERIG_START()
             } else {
                 SOUND_COPTERIG_STOP()
             }
         }
         if (DiffSound & SoundCrotrig) {
             if (SoundFlag & SoundCrotrig) {
                 SOUND_CROTRIG_START()
             } else {
                 SOUND_CROTRIG_STOP()
             }
         }
         if (DiffSound & SoundCutterig) {
             if (SoundFlag & SoundCutterig) {
                 SOUND_CUTTERIG_START()
             } else {
                 SOUND_CUTTERIG_STOP()
             }
         }
         if (DiffSound & SoundUnderWater) {
             if (SoundFlag & SoundUnderWater) {
                 SOUND_UNDERWATER_START()
             } else {
                 SOUND_UNDERWATER_STOP()
             }
         }
         if (DiffSound & SoundMotor) {
             if (SoundFlag & SoundMotor) {
                 SOUND_START_MOTOR()
             } else {
                 SOUND_STOP_MOTOR()
             }
         }
     }
     lastSoundFlag = SoundFlag;
     /*      ?    .
     int d = ViewZ - preViewZ;
     if(!d) {
         return;
     }
     std::cout<<"AAAAAAAAAAAAA"<<std::cout;
     if(ViewZ >= 512) {
         d = soundVolume - DB_SIZE/32 - (ViewZ - 512)*DB_SIZE/4/(1024 - 512);
     } else {
         d = soundVolume - DB_SIZE/32 + (512 - ViewZ)*DB_SIZE/4/(512 - 384);
     }
     preViewZ = ViewZ;
     soundVolumecurrent = d;
     if(soundVolumecurrent < DB_MIN) {
         soundVolumecurrent = DB_MIN;
     } else {
         if(soundVolumecurrent > DB_MAX) {
             soundVolumecurrent = DB_MAX;
         }
     }*/
     for(int i = 0;i < 16;i++) {
         if(i != LOCAL_CHANNEL) {
             SoundVolume(i,soundVolumecurrent);
         }
     }
 }
References CurrentWorld, DISTANCE_TO_SICRET, DISTANCE_TO_TOWN, EffectInUse, MusicON, SoundVolumeCD, and xsGetVolumeMusic().
Referenced by iGameMap::draw().
StartCDTRACK()
void StartCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsPlayOneTrackCD(LastTrack);
     xsPlayOneTrackMusic(LastTrack);
 #endif
 }
References MusicON, and xsPlayOneTrackMusic().
Referenced by iHandleExtEvent().
StartEFFECT()
void StartEFFECT (EFFECT_VALUE EffectValue, int loop = 0, int pan = 0)
 {
     if(!EffectInUse || !SndData[EffectValue].lpDSB) return;
     int flag = SndData[EffectValue].flags;
     if(loop) flag |= DS_LOOPING;
     if(SndData[EffectValue].channel != LOCAL_CHANNEL)
         SetVolume(SndData[EffectValue].lpDSB,soundVolumecurrent);
     else
         SetVolume(SndData[EffectValue].lpDSB,soundVolume);
     if(EngineNoise && EffectValue == EFF_DRIVING) SoundStop(SndData[EffectValue].channel);
     if (SoundVolumePanning)
         SoundPan(SndData[EffectValue].channel, -pan*8);
     //if (SndData[EffectValue].status & ESCAVE_SOUND&&EffectValue!=EFF_NOISE)
     //  std::cout<<"StartEFFECT:"<<SndData[EffectValue].fname<<" int:"<<(int)EffectValue<<std::endl;
     SoundPlay(SndData[EffectValue].lpDSB,SndData[EffectValue].channel,SndData[EffectValue].priority,SndData[EffectValue].cropos,flag);
 }
References EffectInUse.
Referenced by pal_iter0().
StartSPEECH()
void StartSPEECH (SPEECH_VALUE SpeechValue)
 {
 }
StartWTRACK()
void StartWTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
     int w_id = CurrentWorld;
     if (CurrentWorld == -1)
         w_id = getWID();
     if(w_id >= 0 && w_id <= 3){
 //      xsPlayOneTrackCD(ST_FOSTRAL + w_id);
         xsPlayOneTrackMusic(ST_FOSTRAL + w_id);
         TimeCD = TrackCDTime[ST_FOSTRAL + w_id];
     } else {
         if(w_id > 3){
 //          xsPlayOneTrackCD(ST_SECRETS);
             xsPlayOneTrackMusic(ST_SECRETS);
             TimeCD = TrackCDTime[ST_SECRETS];
         }
     }
     time(&lastTimeCD);
     activeWTRACK = 1;
 #endif
 }
References CurrentWorld, getWID(), MusicON, ST_FOSTRAL, and xsPlayOneTrackMusic().
Referenced by uvsRestoreVanger(), and uvsWorldReload().
StopCDTRACK()
void StopCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  LastTrack = xsGetCurTrackCD();
 //  xsStopCD();
     xsStopMusic();
     activeWTRACK = 0;
     SlowOn = 1;
 #endif
 }
References activeWTRACK, MusicON, and xsStopMusic().
Referenced by aciPrepareEndImage(), aciShowLocation(), iHandleExtEvent(), LoadingRTO3::Init(), VangerUnit::Quant(), VangerUnit::SensorQuant(), and XpeditionOFF().
StopEFFECT()
void StopEFFECT (EFFECT_VALUE EffectValue)
 {
     if(!EffectInUse) return;
     SoundStop(SndData[EffectValue].channel);
     if(EngineNoise && EffectValue == EFF_DRIVING && SndData[EFF_STOP].lpDSB) StartEFFECT(EFF_STOP);
 }
References EffectInUse, and SoundStop().
Variable Documentation
Backgroundound
int Backgroundound
EngineNoise
int EngineNoise extern
Referenced by LoadMotorSound().
sndBackgroundMax
int sndBackgroundMax extern
sndScratchMax
int sndScratchMax
sndStepMax
int sndStepMax
SoundCopterig
const int SoundCopterig = 0x00000001
Referenced by Object::mechous_analysis(), and VangerFunctionType::Quant().
SoundCrotrig
const int SoundCrotrig = 0x00000002
Referenced by Object::mechous_analysis(), and VangerFunctionType::Quant().
SoundCutterig
const int SoundCutterig = 0x00000004
Referenced by Object::mechous_analysis().
SoundFlag
int SoundFlag extern
Referenced by Object::analysis(), Object::mechous_analysis(), VangerFunctionType::Quant(), and Object::switch_analysis().
SoundMotor
const int SoundMotor = 0x00000010
Referenced by Object::mechous_analysis().
SoundUnderWater
const int SoundUnderWater = 0x00000008
Referenced by Object::mechous_analysis().