Vangers: src/iscreen/i_chat.cpp File Reference
i_chat.cpp File Reference
#include "../global.h"
#include "../network.h"
#include "controls.h"
#include "i_chat.h"
#include "i_str.h"
#include "hfont.h"
#include "iscreen.h"
#include "../actint/item_api.h"
#include "../actint/actint.h"
#include <arpa/inet.h>
Macros
#define ICS_INPUT_TIMER 5
#define ICS_UP_BUTTON 0x01
#define ICS_DN_BUTTON 0x02
#define ICS_ALL_BUTTON 0x03
#define ICS_GREEN_BUTTON 0x04
#define ICS_ORANGE_BUTTON 0x05
#define ICS_BLUE_BUTTON 0x06
#define ICS_YELLOW_BUTTON 0x07
#define ICS_MUTE_BUTTON 0x08
#define ICS_CLEAR_BUTTON 0x09
#define ICS_PLAYER1_BUTTON 0x0A
#define ICS_PLAYER2_BUTTON 0x0B
#define ICS_PLAYER3_BUTTON 0x0C
#define ICS_PLAYER4_BUTTON 0x0D
#define ICS_PLAYER5_BUTTON 0x0E
#define ICS_EXIT_BUTTON 0x0F
#define ICS_BACK_BUTTON 0x10
#define ICS_RED_BUTTON 0x11
#define ICS_WHITE_BUTTON 0x12
#define ICS_GRAY_BUTTON 0x13
#define ICS_BLACK_BUTTON 0x14
#define ICS_CAMOUFLAGE_BUTTON 0x15
#define ICS_PATROL_BUTTON 0x16
#define ICS_DELTA 10
#define ICS_HISTORY_SIZE_X 450
#define ICS_HISTORY_SIZE_Y 320
#define ICS_BUTTON_SIZE_X 170
#define ICS_BUTTON_SIZE_Y 20
Functions
int iGetKeyName (int vkey, int shift, int lng_flag)
void aOutText32 (int x, int y, int color, void *text, int font, int hspace, int vspace)
int aTextWidth32 (void *text, int font, int hspace)
int aTextHeight32 (void *text, int font, int vspace)
void iChatInit (void)
void iChatQuant (int flush=0)
void iChatFinit (void)
void iChatKeyQuant (SDL_Event *k)
void iChatMouseQuant (int x, int y, int bt)
void iInitChatButtons (void)
void iInitChatScreen (void)
void iChatInputChar (SDL_Event *code)
void iChatInputFlush (void)
void iChatInputBack (void)
void iChatMouseHandler (iChatButton *bt, int bt_id)
void iChatClearButtons (void)
void iChatClearLog (void)
iChatButton * iGetChatButton (int id)
iChatButton * iGetChatPlayerButton (int id)
void put_map (int x, int y, int sx, int sy)
unsigned char UTF8toCP866 (unsigned short utf)
Variables
XBuffer * iResBuf
int aciKeyboardLocked
int iScreenOffs
char * iSTR_WORLD_NONE_CHAR
char * iSTR_WORLD_FOSTRAL_CHAR
char * iSTR_WORLD_GLORX_CHAR
char * iSTR_WORLD_NECROSS_CHAR
char * iSTR_WORLD_XPLO_CHAR
char * iSTR_WORLD_KHOX_CHAR
char * iSTR_WORLD_BOOZEENA_CHAR
char * iSTR_WORLD_WEEXOW_CHAR
char * iSTR_WORLD_HMOK_CHAR
char * iSTR_WORLD_THREALL_CHAR
char * iSTR_WORLD_ARK_A_ZNOY_CHAR
char * iSTR_COLOR_GREEN_CHAR
char * iSTR_COLOR_ORANGE_CHAR
char * iSTR_COLOR_BLUE_CHAR
char * iSTR_COLOR_YELLOW_CHAR
char * iSTR_COLOR_RED_CHAR
char * iSTR_COLOR_WHITE_CHAR
char * iSTR_COLOR_GRAY_CHAR
char * iSTR_COLOR_BLACK_CHAR
char * iSTR_COLOR_CAMOUFLAGE_CHAR
char * iSTR_COLOR_PATROL_CHAR
char * iSTR_MUTE_ALL
char * iSTR_CLEAR_LOG
char * iSTR_BACKGROUND
char * iSTR_LEAVE_CHAT
char * iSTR_All
char * iSTR_Yellow
char * iSTR_Orange
char * iSTR_Blue
char * iSTR_Green
char * iSTR_Red
char * iSTR_White
char * iSTR_Gray
char * iSTR_Black
char * iSTR_Camouflage
char * iSTR_Patrol
aciFont ** aScrFonts32
const int ICS_FON_COLOR = 184
const int ICS_BORDER_COLOR = 184
const int ICS_STRING_COL0 = 227 + (3 << 16)
const int ICS_STRING_COL1 = 88 + (1 << 16)
const int ICS_iFON_COLOR = 80
const int ICS_iBORDER_COLOR = 80
const int ICS_iSTRING_COL0 = 2 + (3 << 16)
const int ICS_iSTRING_COL1 = 144 + (1 << 16)
XList * iChatButtons = NULL
iChatHistoryScreen * iChatHistory = NULL
iChatInputField * iChatInput = NULL
int iChatON = 0
int iChatExit = 0
int iScreenChat = 0
int iChatSkip = 0
int iChatFilter = MESSAGE_FOR_ALL
int iChatFilterID = 0
int iChatMUTE = 0
int iChatBackLog = 1
int iChatCursorFlag = 0
int iChatCursorTimer = 0
Macro Definition Documentation
ICS_ALL_BUTTON
#define ICS_ALL_BUTTON 0x03
ICS_BACK_BUTTON
#define ICS_BACK_BUTTON 0x10
ICS_BLACK_BUTTON
#define ICS_BLACK_BUTTON 0x14
ICS_BLUE_BUTTON
#define ICS_BLUE_BUTTON 0x06
ICS_BUTTON_SIZE_X
#define ICS_BUTTON_SIZE_X 170
ICS_BUTTON_SIZE_Y
#define ICS_BUTTON_SIZE_Y 20
ICS_CAMOUFLAGE_BUTTON
#define ICS_CAMOUFLAGE_BUTTON 0x15
ICS_CLEAR_BUTTON
#define ICS_CLEAR_BUTTON 0x09
ICS_DELTA
#define ICS_DELTA 10
ICS_DN_BUTTON
#define ICS_DN_BUTTON 0x02
ICS_EXIT_BUTTON
#define ICS_EXIT_BUTTON 0x0F
ICS_GRAY_BUTTON
#define ICS_GRAY_BUTTON 0x13
ICS_GREEN_BUTTON
#define ICS_GREEN_BUTTON 0x04
ICS_HISTORY_SIZE_X
#define ICS_HISTORY_SIZE_X 450
ICS_HISTORY_SIZE_Y
#define ICS_HISTORY_SIZE_Y 320
ICS_INPUT_TIMER
#define ICS_INPUT_TIMER 5
ICS_MUTE_BUTTON
#define ICS_MUTE_BUTTON 0x08
ICS_ORANGE_BUTTON
#define ICS_ORANGE_BUTTON 0x05
ICS_PATROL_BUTTON
#define ICS_PATROL_BUTTON 0x16
ICS_PLAYER1_BUTTON
#define ICS_PLAYER1_BUTTON 0x0A
ICS_PLAYER2_BUTTON
#define ICS_PLAYER2_BUTTON 0x0B
ICS_PLAYER3_BUTTON
#define ICS_PLAYER3_BUTTON 0x0C
ICS_PLAYER4_BUTTON
#define ICS_PLAYER4_BUTTON 0x0D
ICS_PLAYER5_BUTTON
#define ICS_PLAYER5_BUTTON 0x0E
ICS_RED_BUTTON
#define ICS_RED_BUTTON 0x11
ICS_UP_BUTTON
#define ICS_UP_BUTTON 0x01
ICS_WHITE_BUTTON
#define ICS_WHITE_BUTTON 0x12
ICS_YELLOW_BUTTON
#define ICS_YELLOW_BUTTON 0x07
Function Documentation
aOutText32()
void aOutText32 (int x, int y, int color, void * text, int font, int hspace, int vspace)
 {
     int s,xs,ys,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     int color_size,chr;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     color_size = (color >> 16) & 0xFF;
     color &= 0xFFFF;
     unsigned char* p = aScrFonts32[font] -> data;
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     X = x;
     Y = y;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 X -= aScrFonts32[font] -> LeftOffs[chr];
                 offs = xs * ys * chr;
                 aciPutSpr32(X,Y,xs,ys,p + offs,color,color_size);
                 X += xs + hspace - aScrFonts32[font] -> RightOffs[chr];
             }
         }
         else {
             X = x;
             Y += ys + vspace;
         }
     }
 }
References XErrorHandler::Abort(), aciPutSpr32(), aScrFonts32, ErrH, and NULL.
Referenced by iChatInputField::redraw(), iChatHistoryScreen::redraw(), and iChatButton::redraw().
aTextHeight32()
int aTextHeight32 (void * text, int font, int vspace)
 {
     int s,xs,ys,sz = strlen((char*)text),chr;
     int len = 0;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     len = ys + vspace;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr == '\n'){
             len += ys + vspace;
         }
     }
     return len;
 }
References XErrorHandler::Abort(), aScrFonts32, ErrH, and NULL.
Referenced by iChatInputField::redraw(), iChatHistoryScreen::redraw(), and iChatButton::redraw().
aTextWidth32()
int aTextWidth32 (void * text, int font, int hspace)
 {
     int s,xs,ys,sz = strlen((char*)text),chr;
     int len = 0,max_len = 0;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 len += xs + hspace - aScrFonts32[font] -> RightOffs[chr] - aScrFonts32[font] -> LeftOffs[chr];
             }
         }
         else {
             if(len > max_len) max_len = len;
             len = 0;
         }
     }
     if(len > max_len) max_len = len;
     return max_len;
 }
References XErrorHandler::Abort(), aScrFonts32, ErrH, and NULL.
Referenced by iChatInputChar(), and iChatButton::redraw().
iChatClearButtons()
void iChatClearButtons (void)
 {
     iChatButton* p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         switch(p -> ID){
             case ICS_ALL_BUTTON:
             case ICS_YELLOW_BUTTON:
             case ICS_ORANGE_BUTTON:
             case ICS_BLUE_BUTTON:
             case ICS_GREEN_BUTTON:
             case ICS_RED_BUTTON:
             case ICS_WHITE_BUTTON:
             case ICS_GRAY_BUTTON:
             case ICS_BLACK_BUTTON:
             case ICS_CAMOUFLAGE_BUTTON:
             case ICS_PATROL_BUTTON:
             case ICS_PLAYER1_BUTTON:
             case ICS_PLAYER2_BUTTON:
             case ICS_PLAYER3_BUTTON:
             case ICS_PLAYER4_BUTTON:
             case ICS_PLAYER5_BUTTON:
                 p -> CurState = 0;
                 break;
         }
         p = (iChatButton*)p -> next;
     }
 }
References iChatButtons, ICS_ALL_BUTTON, ICS_BLACK_BUTTON, ICS_BLUE_BUTTON, ICS_CAMOUFLAGE_BUTTON, ICS_GRAY_BUTTON, ICS_GREEN_BUTTON, ICS_ORANGE_BUTTON, ICS_PATROL_BUTTON, ICS_PLAYER1_BUTTON, ICS_PLAYER2_BUTTON, ICS_PLAYER3_BUTTON, ICS_PLAYER4_BUTTON, ICS_PLAYER5_BUTTON, ICS_RED_BUTTON, ICS_WHITE_BUTTON, and ICS_YELLOW_BUTTON.
Referenced by iChatMouseHandler(), and iInitChatScreen().
iChatClearLog()
void iChatClearLog (void)
 {
     MessageElement* p,*p1;
     p = message_dispatcher.first();
     while(p){
         p1 = (MessageElement*)p -> next;
         delete p;
         p = p1;
     }
     message_dispatcher.ClearList();
 }
References MessageDispatcher::first(), and message_dispatcher.
Referenced by iChatMouseHandler().
iChatFinit()
void iChatFinit (void)
 {
     iChatButton* p,*p1;
     if(iChatButtons){
         p = (iChatButton*)iChatButtons -> fPtr;
         while(p){
             p1 = (iChatButton*)p -> next;
             delete p;
             p = p1;
         }
         delete iChatButtons;
     }
     if(iChatHistory)
         delete iChatHistory;
     if(iChatInput)
         delete iChatInput;
     iChatON = iScreenChat = 0;
     aciKeyboardLocked = 0;
     iChatHistory = NULL;
     iChatInput = NULL;
     iChatButtons = NULL;
     SDL_StopTextInput();
 }
References iChatButtons.
Referenced by actIntDispatcher::EventQuant(), and VangerUnit::Go2Universe().
iChatInit()
void iChatInit (void)
 {
     int x,y,sx,sy,bsx,col0,col1,bcol;
     iChatButton* p;
     sx = ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X;
     sy = ICS_HISTORY_SIZE_Y + ICS_DELTA * 2 + ICS_BUTTON_SIZE_Y * 2;
 //    bsx = (sx - ICS_DELTA * 2) / 3;
     bsx = (ICS_HISTORY_SIZE_X - ICS_DELTA * 2) / 3;
     x = (XGR_MAXX - sx) / 2;
     y = (XGR_MAXY - sy) / 2;
     if(!iScreenChat)
         bcol = ICS_BORDER_COLOR;
     else {
         y -= 30;
         bcol = ICS_iBORDER_COLOR;
     }
     iChatButtons = new XList;
     iChatHistory = new iChatHistoryScreen;
     iChatHistory -> init(x,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_HISTORY_SIZE_X,ICS_HISTORY_SIZE_Y,bcol,bcol);
     iChatInput = new iChatInputField;
     iChatInput -> init(x,y + ICS_HISTORY_SIZE_Y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_HISTORY_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     strcpy(iChatInput -> string,">_");
     p = new iChatButton(2);
     p -> init(x,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_MUTE_BUTTON;
     p -> set_string(iSTR_MUTE_ALL);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p -> CurState = iChatMUTE;
     p = new iChatButton(1);
     p -> init(x + bsx + ICS_DELTA,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_CLEAR_BUTTON;
     p -> set_string(iSTR_CLEAR_LOG);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     iChatButtons -> AddElement((XListElement*)p);
     iChatBackLog = 1;
     if(!iScreenChat){
         p = new iChatButton(2);
         p -> init(x + (bsx + ICS_DELTA) * 3,y,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
         p -> ID = ICS_BACK_BUTTON;
         p -> set_string(iSTR_BACKGROUND);
         if(!iScreenChat){
             col0 = ICS_STRING_COL0;
             col1 = ICS_STRING_COL1;
         }
         else {
             col0 = ICS_iSTRING_COL0;
             col1 = ICS_iSTRING_COL1;
         }
         p -> set_color(0,col0);
         p -> set_color(1,col1);
         p -> CurState = 1;
         iChatButtons -> AddElement((XListElement*)p);
     }
 //    else {
 //        iChatBackLog = 0;
 //    }
     if(!iScreenChat){
         p = new iChatButton(1);
         p -> init(x + bsx * 2 + ICS_DELTA * 2,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
         p -> ID = ICS_EXIT_BUTTON;
         p -> set_string(iSTR_LEAVE_CHAT);
         col0 = ICS_STRING_COL0;
         p -> set_color(0,col0);
         iChatButtons -> AddElement((XListElement*)p);
     }
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_ALL_BUTTON;
     p -> set_string(iSTR_All);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 2,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_YELLOW_BUTTON;
     p -> set_string(iSTR_Yellow);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 3,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_ORANGE_BUTTON;
     p -> set_string(iSTR_Orange);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 4,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_BLUE_BUTTON;
     p -> set_string(iSTR_Blue);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 5,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_GREEN_BUTTON;
     p -> set_string(iSTR_Green);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 6,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_RED_BUTTON;
     p -> set_string(iSTR_Red);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 2,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_WHITE_BUTTON;
     p -> set_string(iSTR_White);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 3,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_GRAY_BUTTON;
     p -> set_string(iSTR_Gray);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 4,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_BLACK_BUTTON;
     p -> set_string(iSTR_Black);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 5,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_CAMOUFLAGE_BUTTON;
     p -> set_string(iSTR_Camouflage);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 6,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PATROL_BUTTON;
     p -> set_string(iSTR_Patrol);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/4,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 6,ICS_BUTTON_SIZE_X/2,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_UP_BUTTON;
     p -> set_string("\x1E");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 7,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER1_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 8,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER2_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 9,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER3_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 10,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER4_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 11,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER5_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/4,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 12,ICS_BUTTON_SIZE_X/2,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_DN_BUTTON;
     p -> set_string("\x1F");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     iChatExit = 0;
     iChatON = 1;
     aciKeyboardLocked = 1;
     XGR_MouseShow();
     iInitChatScreen();
     SDL_StartTextInput();
 }
References aciKeyboardLocked, iChatBackLog, iChatButtons, iChatExit, iChatHistory, iChatInput, iChatMUTE, iChatON, ICS_ALL_BUTTON, ICS_BACK_BUTTON, ICS_BLACK_BUTTON, ICS_BLUE_BUTTON, ICS_BORDER_COLOR, ICS_BUTTON_SIZE_X, ICS_BUTTON_SIZE_Y, ICS_CAMOUFLAGE_BUTTON, ICS_CLEAR_BUTTON, ICS_DELTA, ICS_DN_BUTTON, ICS_EXIT_BUTTON, ICS_GRAY_BUTTON, ICS_GREEN_BUTTON, ICS_HISTORY_SIZE_X, ICS_HISTORY_SIZE_Y, ICS_iBORDER_COLOR, ICS_iSTRING_COL0, ICS_iSTRING_COL1, ICS_MUTE_BUTTON, ICS_ORANGE_BUTTON, ICS_PATROL_BUTTON, ICS_PLAYER1_BUTTON, ICS_PLAYER2_BUTTON, ICS_PLAYER3_BUTTON, ICS_PLAYER4_BUTTON, ICS_PLAYER5_BUTTON, ICS_RED_BUTTON, ICS_STRING_COL0, ICS_STRING_COL1, ICS_UP_BUTTON, ICS_WHITE_BUTTON, ICS_YELLOW_BUTTON, iInitChatScreen(), iScreenChat, iSTR_All, iSTR_BACKGROUND, iSTR_Black, iSTR_Blue, iSTR_Camouflage, iSTR_CLEAR_LOG, iSTR_Gray, iSTR_Green, iSTR_LEAVE_CHAT, iSTR_MUTE_ALL, iSTR_Orange, iSTR_Patrol, iSTR_Red, iSTR_White, iSTR_Yellow, XGR_MAXX, XGR_MAXY, and XGR_MouseShow.
Referenced by actIntDispatcher::EventQuant().
iChatInputBack()
void iChatInputBack (void)
 {
     char* ptr = iChatInput -> string;
     int sz = strlen(ptr);
     if(sz > 2){
         ptr[sz - 1] = 0;
         ptr[sz - 2] = '_';
     }
 }
References iChatInput.
Referenced by iChatKeyQuant().
iChatInputChar()
void iChatInputChar (SDL_Event * code)
 {
     char* ptr,*ptr0 = iChatInput->string;
     int x, sz;
     unsigned char chr;
     iChatInput->XConv->init();
     *iChatInput->XConv < CurPlayerName < iChatInput->string;
     ptr = iChatInput->XConv->address();
     x = aTextWidth32(ptr, iChatInput->font, 1);
     sz = strlen(ptr0);
 //  if(sz >= ISC_MAX_STRING_LEN && x >= iChatInput->SizeX - 10) {
     if((sz >= ISC_MAX_STRING_LEN) || (x >= iChatInput->SizeX - 10))
         return;
     aciFont* hfnt = aScrFonts32[iChatInput->font];
     if (event->type == SDL_TEXTINPUT) {
         if ((unsigned char)event->text.text[0] < 128) {
             chr = event->text.text[0];
         } else {
             unsigned short utf = ((unsigned short *)event->text.text)[0];
             utf = ntohs(utf);
             // All cyrilic chars should be coding in two octets. 8, 11 bit-index for 1,2 octets
             if ((utf & (1<<(7))) && !(utf & (1<<(10)))) {
                 chr = UTF8toCP866(utf);
             } else {
                 chr = ' ';
             }
         }
         if(hfnt && chr < hfnt->Size) {
             ptr0[sz - 1] = chr;
             ptr0[sz] = '_';
             ptr0[sz + 1] = 0;
         }
     }
 }
References XBuffer::address(), aScrFonts32, aTextWidth32(), CurPlayerName, iChatScreenObject::font, iChatInput, XBuffer::init(), ISC_MAX_STRING_LEN, iChatScreenObject::SizeX, iChatInputField::string, UTF8toCP866(), and iChatInputField::XConv.
Referenced by iChatKeyQuant().
iChatInputFlush()
void iChatInputFlush (void)
 {
     int sz;
     char* ptr = iChatInput -> string;
     sz = strlen(ptr);
     ptr[sz - 1] = 0;
     if(sz > 2){
         message_dispatcher.send(ptr + 1,iChatFilter,iChatFilterID);
     }
     strcpy(ptr,">_");
 }
References iChatFilter, iChatFilterID, iChatInput, message_dispatcher, and MessageDispatcher::send().
Referenced by iChatKeyQuant().
iChatKeyQuant()
void iChatKeyQuant (SDL_Event * k)
{
     if (k->type == SDL_TEXTINPUT) {
         return iChatInputChar(k);
     }
     if (k->type != SDL_KEYDOWN) {
         iChatExit = 1;
         return;
     }
     if(iCheckKeyID(iKEY_CHAT, k->key.keysym.scancode))
         iChatExit = 1;
     switch(k->key.keysym.scancode) {
         case SDL_SCANCODE_ESCAPE:
             iChatExit = 1;
             break;
         case SDL_SCANCODE_RETURN:
             iChatInputFlush();
             break;
         case SDL_SCANCODE_BACKSPACE:
         case SDL_SCANCODE_LEFT:
             iChatInputBack();
             break;
         default:
             if(k) {
                 iChatInputChar(k);
             }
             break;
     }
 }
References iChatExit, iChatInputBack(), iChatInputChar(), iChatInputFlush(), iCheckKeyID(), and iKEY_CHAT.
Referenced by actIntDispatcher::KeyQuant().
iChatMouseHandler()
void iChatMouseHandler (iChatButton * bt, int bt_id)
 {
     switch(bt -> ID){
         case ICS_EXIT_BUTTON:
             iChatExit = 1;
             break;
         case ICS_UP_BUTTON:
             if(iChatSkip)
                 iChatSkip --;
             break;
         case ICS_DN_BUTTON:
             if(iChatSkip < players_list.size() - 5)
                 iChatSkip ++;
             break;
         case ICS_ALL_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_ALL;
             iChatFilterID = 0;
             break;
         case ICS_YELLOW_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_YELLOW;
             break;
         case ICS_ORANGE_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_ORANGE;
             break;
         case ICS_BLUE_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_BLUE;
             break;
         case ICS_GREEN_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_GREEN;
             break;
         case ICS_RED_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_RED;
             break;
         case ICS_WHITE_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_WHITE;
             break;
         case ICS_GRAY_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_GRAY;
             break;
         case ICS_BLACK_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_BLACK;
             break;
         case ICS_CAMOUFLAGE_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_CAMOUFLAGE;
             break;
         case ICS_PATROL_BUTTON:
             iChatClearButtons();
             bt -> CurState = 1;
             iChatFilter = MESSAGE_FOR_TEAM;
             iChatFilterID = TEAM_PATROL;
             break;
         case ICS_MUTE_BUTTON:
             bt -> CurState ^= 1;
             iChatMUTE = bt -> CurState;
             break;
         case ICS_BACK_BUTTON:
             bt -> CurState ^= 1;
             iChatBackLog = bt -> CurState;
             break;
         case ICS_CLEAR_BUTTON:
             iChatClearLog();
             break;
         case ICS_PLAYER1_BUTTON:
         case ICS_PLAYER2_BUTTON:
         case ICS_PLAYER3_BUTTON:
         case ICS_PLAYER4_BUTTON:
         case ICS_PLAYER5_BUTTON:
             if(!(bt -> flags & ICS_HIDDEN_OBJECT)){
                 iChatClearButtons();
                 bt -> CurState = 1;
                 iChatFilter = MESSAGE_FOR_PLAYER;
                 iChatFilterID = bt -> extData;
             }
             break;
     }
 }
References iChatBackLog, iChatClearButtons(), iChatClearLog(), iChatExit, iChatFilter, iChatFilterID, iChatMUTE, iChatSkip, ICS_ALL_BUTTON, ICS_BACK_BUTTON, ICS_BLACK_BUTTON, ICS_BLUE_BUTTON, ICS_CAMOUFLAGE_BUTTON, ICS_CLEAR_BUTTON, ICS_DN_BUTTON, ICS_EXIT_BUTTON, ICS_GRAY_BUTTON, ICS_GREEN_BUTTON, ICS_MUTE_BUTTON, ICS_ORANGE_BUTTON, ICS_PATROL_BUTTON, ICS_PLAYER1_BUTTON, ICS_PLAYER2_BUTTON, ICS_PLAYER3_BUTTON, ICS_PLAYER4_BUTTON, ICS_PLAYER5_BUTTON, ICS_RED_BUTTON, ICS_UP_BUTTON, ICS_WHITE_BUTTON, ICS_YELLOW_BUTTON, MESSAGE_FOR_ALL, MESSAGE_FOR_TEAM, players_list, XTList< Type >::size(), TEAM_BLACK, TEAM_BLUE, TEAM_CAMOUFLAGE, TEAM_GRAY, TEAM_GREEN, TEAM_ORANGE, TEAM_PATROL, TEAM_RED, TEAM_WHITE, and TEAM_YELLOW.
Referenced by iChatMouseQuant().
iChatMouseQuant()
void iChatMouseQuant (int x, int y, int bt)
 {
     iChatButton* p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         if(p -> check_xy(x,y)) iChatMouseHandler(p,bt);
         p = (iChatButton*)p -> next;
     }
 }
References iChatButtons, and iChatMouseHandler().
Referenced by actIntDispatcher::KeyQuant().
iChatQuant()
void iChatQuant (int flush = 0)
 {
     int sz;
     iChatButton* p;
     if(!iChatON) return;
 //    if(iScreenChat) put_map(iScreenOffs,0,XGR_MAXX,XGR_MAXY);
     iInitChatScreen();
     p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         if(!(p -> flags & ICS_HIDDEN_OBJECT)) p -> redraw();
         p = (iChatButton*)p -> next;
     }
     iChatCursorTimer ++;
     if(iChatCursorTimer >= ICS_INPUT_TIMER){
         iChatCursorTimer = 0;
         iChatCursorFlag = 1;
     }
     if(iChatCursorFlag){
         sz = strlen(iChatInput -> string);
         if(iChatInput -> string[sz - 1] == '_')
             iChatInput -> string[sz - 1] = ' ';
         else
             iChatInput -> string[sz - 1] = '_';
         iChatCursorFlag = 0;
     }
     iChatInput -> redraw();
     iChatHistory -> redraw();
     if(flush){
         p = (iChatButton*)iChatButtons -> fPtr;
         while(p){
             if(!(p -> flags & ICS_HIDDEN_OBJECT)) p -> flush();
             p = (iChatButton*)p -> next;
         }
         iChatInput -> flush();
         iChatHistory -> flush();
     }
 }
References iChatButtons, iChatON, and iInitChatScreen().
Referenced by actIntDispatcher::flush().
iGetChatButton()
iChatButton * iGetChatButton (int id)
 {
     iChatButton* p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         if(p -> ID == id) return p;
         p = (iChatButton*)p -> next;
     }
     return NULL;
 }
References iChatButtons.
Referenced by iInitChatButtons(), and iInitChatScreen().
iGetChatPlayerButton()
iChatButton * iGetChatPlayerButton (int id)
 {
     iChatButton* p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         switch(p -> ID){
             case ICS_ALL_BUTTON:
             case ICS_YELLOW_BUTTON:
             case ICS_ORANGE_BUTTON:
             case ICS_BLUE_BUTTON:
             case ICS_GREEN_BUTTON:
             case ICS_RED_BUTTON:
             case ICS_WHITE_BUTTON:
             case ICS_GRAY_BUTTON:
             case ICS_BLACK_BUTTON:
             case ICS_CAMOUFLAGE_BUTTON:
             case ICS_PATROL_BUTTON:
             case ICS_PLAYER1_BUTTON:
             case ICS_PLAYER2_BUTTON:
             case ICS_PLAYER3_BUTTON:
             case ICS_PLAYER4_BUTTON:
             case ICS_PLAYER5_BUTTON:
                 if(p -> extData == id) return p;
                 break;
         }
         p = (iChatButton*)p -> next;
     }
     return 0;
 }
References iChatButtons, ICS_ALL_BUTTON, ICS_BLACK_BUTTON, ICS_BLUE_BUTTON, ICS_CAMOUFLAGE_BUTTON, ICS_GRAY_BUTTON, ICS_GREEN_BUTTON, ICS_ORANGE_BUTTON, ICS_PATROL_BUTTON, ICS_PLAYER1_BUTTON, ICS_PLAYER2_BUTTON, ICS_PLAYER3_BUTTON, ICS_PLAYER4_BUTTON, ICS_PLAYER5_BUTTON, ICS_RED_BUTTON, ICS_WHITE_BUTTON, and ICS_YELLOW_BUTTON.
Referenced by iInitChatScreen().
iGetKeyName()
int iGetKeyName (int vkey, int shift, int lng_flag)
iInitChatButtons()
void iInitChatButtons (void)
 {
     int i;
     PlayerData* p = players_list.first();
     iChatButton* bt;
     if(!p) return;
     if(players_list.size() < 5){
         iChatSkip = 0;
         bt = iGetChatButton(ICS_UP_BUTTON);
         bt -> flags |= ICS_HIDDEN_OBJECT;
         bt = iGetChatButton(ICS_DN_BUTTON);
         bt -> flags |= ICS_HIDDEN_OBJECT;
     }
     else {
         bt = iGetChatButton(ICS_UP_BUTTON);
         bt -> flags &= ~ICS_HIDDEN_OBJECT;
         bt = iGetChatButton(ICS_DN_BUTTON);
         bt -> flags &= ~ICS_HIDDEN_OBJECT;
     }
     for(i = 0; i < 5; i ++){
         bt = iGetChatButton(ICS_PLAYER1_BUTTON + i);
         bt -> flags |= ICS_HIDDEN_OBJECT;
     }
     for(i = 0; i < iChatSkip; i ++){
         if(p){
             p = (PlayerData*)p -> next;
         }
         else {
             iChatSkip = 0;
             p = players_list.first();
         }
     }
     for(i = 0; i < 5; i ++){
         if(p -> client_ID == GlobalStationID)
         p = (PlayerData*)p -> next;
         if(!p) break;
         bt = iGetChatButton(ICS_PLAYER1_BUTTON + i);
         iResBuf -> init();
         *iResBuf < p -> name < " " < iChatWorlds[p -> body.world + 1] < "/" < iChatColors[p -> body.color];
         bt -> set_string(iResBuf -> address());
         bt -> flags &= ~ICS_HIDDEN_OBJECT;
         bt -> extData = p -> client_ID;
         p = (PlayerData*)p -> next;
         if(!p) break;
     }
 }
References XTList< Type >::first(), iChatSkip, ICS_UP_BUTTON, iGetChatButton(), players_list, and XTList< Type >::size().
Referenced by iInitChatScreen().
iInitChatScreen()
void iInitChatScreen (void)
 {
     int i;
     int teamFilterID = ICS_GREEN_BUTTON + iChatFilterID;
     iChatButton* p;
     MessageElement* el;
     iInitChatButtons();
     iChatClearButtons();
     if (iChatFilterID > 3) {
         teamFilterID = teamFilterID + 9;
     }
     switch(iChatFilter){
         case MESSAGE_FOR_ALL:
             p = iGetChatButton(ICS_ALL_BUTTON);
             p -> CurState = 1;
             break;
         case MESSAGE_FOR_TEAM:
             p = iGetChatButton(teamFilterID);
             p -> CurState = 1;
             break;
         case MESSAGE_FOR_PLAYER:
             if(!players_list.find(iChatFilterID)){
                 p = iGetChatButton(ICS_ALL_BUTTON);
                 p -> CurState = 1;
                 iChatFilter = MESSAGE_FOR_ALL;
                 iChatFilterID = 0;
             }
             p = iGetChatPlayerButton(iChatFilterID);
             if(!p){
                 iChatSkip = 0;
                 while(!p){
                     iInitChatButtons();
                     p = iGetChatPlayerButton(iChatFilterID);
                     if(!p) iChatSkip ++;
                 }
             }
             p -> CurState = 1;
             break;
     }
     i = 0;
     el = message_dispatcher.first();
     iChatHistory -> clear();
     if(!iChatMUTE){
         while(el){
             iChatHistory -> add_str(el -> message,i,el -> color);
 //            iChatHistory -> add_str(el -> message,i);
             i ++;
             el = (MessageElement*)el -> next;
         }
     }
 }
References PlayersList::find(), MessageDispatcher::first(), iChatClearButtons(), iChatFilter, iChatFilterID, iChatHistory, iChatMUTE, iChatSkip, ICS_ALL_BUTTON, ICS_GREEN_BUTTON, iGetChatButton(), iGetChatPlayerButton(), iInitChatButtons(), message_dispatcher, MESSAGE_FOR_ALL, MESSAGE_FOR_PLAYER, MESSAGE_FOR_TEAM, and players_list.
Referenced by iChatInit(), and iChatQuant().
put_map()
void put_map (int x, int y, int sx, int sy)
 {
     int j;
     unsigned char** ltc = ivMap -> lineTcolor;
     int yy,x0,x1,bsx,index;
     int scr_offs = iScreenOffs;
     x0 = x;
     x1 = x + sx;
     if(x0 < scr_offs) x0 = scr_offs;
     if(x1 >= scr_offs + I_RES_X) x1 = scr_offs + I_RES_X;
     bsx = x1 - x0;
     if(bsx > 0){
         index = (x0 - scr_offs) + y * XGR_MAXX;
         for(j = 0; j < sy; j ++){
             yy = iYCYCL(y + j);
             memcpy(XGR_VIDEOBUF + index,ltc[yy] + x0,bsx);
             index += XGR_MAXX;
         }
     }
 }
UTF8toCP866()
unsigned char UTF8toCP866 (unsigned short utf)
{
     if (utf >= 0xd090 && utf <= 0xd0bf) {
         return utf - 0xd010;
     }
     if (utf >= 0xd180 && utf <= 0xd18f) {
         return utf - 0xd0a0;
     }
     switch(utf) {
         case 0xd081: //
             return 0xf0;
         case 0xd191: //
             return 0xf1;
     }
     return 0xdb;
 }
Referenced by iChatInputChar(), and aciScreenDispatcher::InputQuant().
Variable Documentation
aciKeyboardLocked
int aciKeyboardLocked extern
Referenced by iChatInit().
aScrFonts32
aciFont** aScrFonts32 extern
Referenced by aLoadFonts32(), aOutText32(), aOutText32clip(), aPutStr32(), aStrHeight32(), aStrLen32(), aTextHeight32(), aTextWidth32(), and iChatInputChar().
iChatBackLog
int iChatBackLog = 1
Referenced by iChatInit(), iChatMouseHandler(), and iChatScreenObject::redraw().
iChatButtons
XList* iChatButtons = NULL
Referenced by iChatClearButtons(), iChatFinit(), iChatInit(), iChatMouseQuant(), iChatQuant(), iGetChatButton(), and iGetChatPlayerButton().
iChatCursorFlag
int iChatCursorFlag = 0
iChatCursorTimer
int iChatCursorTimer = 0
iChatExit
int iChatExit = 0
Referenced by actIntDispatcher::EventQuant(), iChatInit(), iChatKeyQuant(), and iChatMouseHandler().
iChatFilter
int iChatFilter = MESSAGE_FOR_ALL
Referenced by iChatInputFlush(), iChatMouseHandler(), and iInitChatScreen().
iChatFilterID
int iChatFilterID = 0
Referenced by iChatInputFlush(), iChatMouseHandler(), and iInitChatScreen().
iChatHistory
iChatHistoryScreen* iChatHistory = NULL
Referenced by iChatInit(), and iInitChatScreen().
iChatInput
iChatInputField* iChatInput = NULL
Referenced by iChatInit(), iChatInputBack(), iChatInputChar(), and iChatInputFlush().
iChatMUTE
int iChatMUTE = 0
Referenced by iChatInit(), iChatMouseHandler(), and iInitChatScreen().
iChatON
int iChatON = 0
Referenced by iChatInit(), iChatQuant(), and IncomingChatMessage().
iChatSkip
int iChatSkip = 0
Referenced by iChatMouseHandler(), iInitChatButtons(), and iInitChatScreen().
ICS_BORDER_COLOR
const int ICS_BORDER_COLOR = 184
Referenced by iChatInit().
ICS_FON_COLOR
const int ICS_FON_COLOR = 184
ICS_iBORDER_COLOR
const int ICS_iBORDER_COLOR = 80
Referenced by iChatInit().
ICS_iFON_COLOR
const int ICS_iFON_COLOR = 80
ICS_iSTRING_COL0
const int ICS_iSTRING_COL0 = 2 + (3 << 16)
Referenced by iChatHistoryScreen::iChatHistoryScreen(), and iChatInit().
ICS_iSTRING_COL1
const int ICS_iSTRING_COL1 = 144 + (1 << 16)
Referenced by iChatInit(), and iChatInputField::iChatInputField().
ICS_STRING_COL0
const int ICS_STRING_COL0 = 227 + (3 << 16)
Referenced by iChatHistoryScreen::iChatHistoryScreen(), and iChatInit().
ICS_STRING_COL1
const int ICS_STRING_COL1 = 88 + (1 << 16)
Referenced by iChatInit(), and iChatInputField::iChatInputField().
iResBuf
XBuffer* iResBuf extern
iScreenChat
int iScreenChat = 0
Referenced by iChatHistoryScreen::add_str(), iChatHistoryScreen::iChatHistoryScreen(), iChatInit(), and iChatInputField::iChatInputField().
iScreenOffs
int iScreenOffs extern
Referenced by aciCancelMatrix(), aciShowScMatrix(), aciSwapMatrices(), invMatrix::flush(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), iPreInitFirst(), iQuantFirst(), aciML_Data::key_trap(), aciML_Dispatcher::key_trap(), put_frame(), put_frame2scr(), put_map(), put_sframe(), and aciML_Dispatcher::quant().
iSTR_All
char* iSTR_All extern
Referenced by iChatInit(), and iInitStrings().
iSTR_BACKGROUND
char* iSTR_BACKGROUND extern
Referenced by iChatInit(), and iInitStrings().
iSTR_Black
char* iSTR_Black extern
Referenced by iChatInit(), and iInitStrings().
iSTR_Blue
char* iSTR_Blue extern
Referenced by iChatInit(), and iInitStrings().
iSTR_Camouflage
char* iSTR_Camouflage extern
Referenced by iChatInit(), and iInitStrings().
iSTR_CLEAR_LOG
char* iSTR_CLEAR_LOG extern
Referenced by iChatInit(), and iInitStrings().
iSTR_COLOR_BLACK_CHAR
char* iSTR_COLOR_BLACK_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_BLUE_CHAR
char* iSTR_COLOR_BLUE_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_CAMOUFLAGE_CHAR
char* iSTR_COLOR_CAMOUFLAGE_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_GRAY_CHAR
char* iSTR_COLOR_GRAY_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_GREEN_CHAR
char* iSTR_COLOR_GREEN_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_ORANGE_CHAR
char* iSTR_COLOR_ORANGE_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_PATROL_CHAR
char* iSTR_COLOR_PATROL_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_RED_CHAR
char* iSTR_COLOR_RED_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_WHITE_CHAR
char* iSTR_COLOR_WHITE_CHAR extern
Referenced by iInitStrings().
iSTR_COLOR_YELLOW_CHAR
char* iSTR_COLOR_YELLOW_CHAR extern
Referenced by iInitStrings().
iSTR_Gray
char* iSTR_Gray extern
Referenced by iChatInit(), and iInitStrings().
iSTR_Green
char* iSTR_Green extern
Referenced by iChatInit(), and iInitStrings().
iSTR_LEAVE_CHAT
char* iSTR_LEAVE_CHAT extern
Referenced by iChatInit(), and iInitStrings().
iSTR_MUTE_ALL
char* iSTR_MUTE_ALL extern
Referenced by iChatInit(), and iInitStrings().
iSTR_Orange
char* iSTR_Orange extern
Referenced by iChatInit(), and iInitStrings().
iSTR_Patrol
char* iSTR_Patrol extern
Referenced by iChatInit(), and iInitStrings().
iSTR_Red
char* iSTR_Red extern
Referenced by iChatInit(), and iInitStrings().
iSTR_White
char* iSTR_White extern
Referenced by iChatInit(), and iInitStrings().
iSTR_WORLD_ARK_A_ZNOY_CHAR
char* iSTR_WORLD_ARK_A_ZNOY_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_BOOZEENA_CHAR
char* iSTR_WORLD_BOOZEENA_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_FOSTRAL_CHAR
char* iSTR_WORLD_FOSTRAL_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_GLORX_CHAR
char* iSTR_WORLD_GLORX_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_HMOK_CHAR
char* iSTR_WORLD_HMOK_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_KHOX_CHAR
char* iSTR_WORLD_KHOX_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_NECROSS_CHAR
char* iSTR_WORLD_NECROSS_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_NONE_CHAR
char* iSTR_WORLD_NONE_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_THREALL_CHAR
char* iSTR_WORLD_THREALL_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_WEEXOW_CHAR
char* iSTR_WORLD_WEEXOW_CHAR extern
Referenced by iInitStrings().
iSTR_WORLD_XPLO_CHAR
char* iSTR_WORLD_XPLO_CHAR extern
Referenced by iInitStrings().
iSTR_Yellow
char* iSTR_Yellow extern
Referenced by iChatInit(), and iInitStrings().