Vangers: src/iscreen/ikeys.h File Reference
ikeys.h File Reference
#include <SDL.h>
Classes
struct KeyBuffer
Macros
#define CUR_KEY_PRESSED 0x01
#define CUR_KEY_UNPRESSED 0x02
Functions
void key (SDL_Event *)
void unpress_key (SDL_Event *)
void KBD_init (void)
Variables
const int MAX_SIZE = 500
const int CTRL_PRESSED = 0x01
const int SHIFT_PRESSED = 0x02
const int KBD_ENABLE = 0x04
KeyBuffer * KeyBuf
int KeyType
Macro Definition Documentation
CUR_KEY_PRESSED
#define CUR_KEY_PRESSED 0x01
CUR_KEY_UNPRESSED
#define CUR_KEY_UNPRESSED 0x02
Function Documentation
KBD_init()
void KBD_init (void)
                     {
     if(!KeyBuf)
         KeyBuf = new KeyBuffer;
     set_key_nadlers(&key, &unpress_key);
 }
References key(), KeyBuf, set_key_nadlers(), and unpress_key().
Referenced by iQuantFirst().
key()
void key (SDL_Event *)
{
     if(KeyBuf -> flag & KBD_ENABLE &&
        (key->type == SDL_KEYDOWN || key->type == SDL_TEXTINPUT)
     ) {
         KeyBuf -> put(key, CUR_KEY_PRESSED);
     }
 }
References CUR_KEY_PRESSED, KBD_ENABLE, key(), and KeyBuf.
Referenced by aciCHandler(), aciML_GetEvent(), aciML_KeyTrap(), aButton::add_key(), fncMenuItem::add_key(), fncMenu::add_key(), iKeyControls::addCode(), iKeyControls::addDefaultCode(), aciML_Event::check_key(), iKeyControls::CheckID(), dictionary_get(), dictionary_hash(), dictionary_set(), dictionary_unset(), KeyBuffer::get(), get_joystick_hat_name(), aciML_Dispatcher::getEvent(), iKeyControls::GetID(), iCheckKeyID(), iDeleteControl(), iGetKeyID(), iInitControlObjects(), iniparser_getboolean(), iniparser_getdouble(), iniparser_getint(), iniparser_getstring(), iniparser_load(), aButton::init(), uvsGamerResult::Init(), iSetControlCode(), isEventActive(), aciML_Data::isEventActive(), aciML_Dispatcher::isEventActive(), KBD_init(), key(), aciML_Data::key_trap(), KeyCenter(), ActionUnit::keyhandler(), VangerUnit::keyhandler(), ActionDispatcher::keyhandler(), uvsGamerResult::Load(), Name2Int(), KeyBuffer::put(), uvsGamerResult::Save(), unpress_key(), and xtGetKeyNameText().
unpress_key()
void unpress_key (SDL_Event *)
{
     if (key->type == SDL_KEYUP) {
         KeyBuf -> put(key, CUR_KEY_UNPRESSED);
     }
 }
References CUR_KEY_UNPRESSED, key(), and KeyBuf.
Referenced by KBD_init().
Variable Documentation
CTRL_PRESSED
const int CTRL_PRESSED = 0x01
KBD_ENABLE
const int KBD_ENABLE = 0x04
Referenced by key(), and KeyBuffer::KeyBuffer().
KeyBuf
KeyBuffer* KeyBuf extern
Referenced by aKeyInit(), aKeyTrap(), iKeyClear(), iScreenDispatcher::input_string_quant(), KBD_init(), key(), actIntDispatcher::KeyQuant(), and unpress_key().
KeyType
int KeyType extern
MAX_SIZE
const int MAX_SIZE = 500
Referenced by KeyBuffer::get(), KeyBuffer::KeyBuffer(), and KeyBuffer::put().
SHIFT_PRESSED
const int SHIFT_PRESSED = 0x02
Referenced by iScreenDispatcher::input_string_quant().