Vangers: src/iscreen/ikeys.cpp File Reference
ikeys.cpp File Reference
#include "../global.h"
#include "ikeys.h"
Functions
void ShowMTargets (void)
void KBD_init (void)
void key (SDL_Event *key)
void unpress_key (SDL_Event *key)
Variables
int MultiLog
int KeyType = 0
KeyBuffer * KeyBuf = NULL
Function Documentation
KBD_init()
void KBD_init (void)
                     {
     if(!KeyBuf)
         KeyBuf = new KeyBuffer;
     set_key_nadlers(&key, &unpress_key);
 }
References key(), KeyBuf, set_key_nadlers(), and unpress_key().
Referenced by iQuantFirst().
key()
void key (SDL_Event * key)
{
     if(KeyBuf -> flag & KBD_ENABLE &&
        (key->type == SDL_KEYDOWN || key->type == SDL_TEXTINPUT)
     ) {
         KeyBuf -> put(key, CUR_KEY_PRESSED);
     }
 }
References CUR_KEY_PRESSED, KBD_ENABLE, key(), and KeyBuf.
Referenced by aciCHandler(), aciML_GetEvent(), aciML_KeyTrap(), aButton::add_key(), fncMenuItem::add_key(), fncMenu::add_key(), iKeyControls::addCode(), iKeyControls::addDefaultCode(), aciML_Event::check_key(), iKeyControls::CheckID(), dictionary_get(), dictionary_hash(), dictionary_set(), dictionary_unset(), KeyBuffer::get(), get_joystick_hat_name(), aciML_Dispatcher::getEvent(), iKeyControls::GetID(), iCheckKeyID(), iDeleteControl(), iGetKeyID(), iInitControlObjects(), iniparser_getboolean(), iniparser_getdouble(), iniparser_getint(), iniparser_getstring(), iniparser_load(), aButton::init(), uvsGamerResult::Init(), iSetControlCode(), isEventActive(), aciML_Data::isEventActive(), aciML_Dispatcher::isEventActive(), KBD_init(), key(), aciML_Data::key_trap(), KeyCenter(), ActionUnit::keyhandler(), VangerUnit::keyhandler(), ActionDispatcher::keyhandler(), uvsGamerResult::Load(), Name2Int(), KeyBuffer::put(), uvsGamerResult::Save(), unpress_key(), and xtGetKeyNameText().
ShowMTargets()
void ShowMTargets (void)
unpress_key()
void unpress_key (SDL_Event * key)
{
     if (key->type == SDL_KEYUP) {
         KeyBuf -> put(key, CUR_KEY_UNPRESSED);
     }
 }
References CUR_KEY_UNPRESSED, key(), and KeyBuf.
Referenced by KBD_init().
Variable Documentation
KeyBuf
KeyBuffer* KeyBuf = NULL
Referenced by aKeyInit(), aKeyTrap(), iKeyClear(), iScreenDispatcher::input_string_quant(), KBD_init(), key(), actIntDispatcher::KeyQuant(), and unpress_key().
KeyType
int KeyType = 0
MultiLog
int MultiLog extern