Vangers: src/iscreen/iml.cpp File Reference
iml.cpp File Reference
#include "../global.h"
#include "iworld.h"
#include "ivmap.h"
#include "iml.h"
#include "../rle.h"
#include "../actint/mlconsts.h"
Macros
#define FLUSH_DELTA 48
Functions
void MLverify (XStream &ff)
int aciGetCurCycle (void)
int getWID (void)
void RegisterIML (char *fname, int id, int channel)
void ReleaseIML (void)
void HandlerIML (int code, int id, int val)
int QuantIML (void)
int isInQueueIML (int ch_id, int ml_id)
void CleanQueueIML (int ch_id)
int CheckIML (int id, int x, int y, int frame)
void PauseIMLall (void)
void ResumeIMLall (void)
int GetPhaseIML (int id)
int isActiveIML (int id)
void LockIML (int id)
void UnlockIML (int id)
int isLockedIML (int id)
void ilandPrepare (void)
void ToolzerQuant (int x, int y)
void StartupIML (void)
void InitIML (void)
Variables
int idOS
int aciML_ToolzerRadius
int uvsCurrentWorldUnable
const int IML_MAXTABLE = 32
const int ACTIVATED = 1
int ActiveTerrain [TERRAIN_MAX] = { 1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0 }
Macro Definition Documentation
FLUSH_DELTA
#define FLUSH_DELTA 48
Function Documentation
aciGetCurCycle()
int aciGetCurCycle (void)
 {
 #ifdef _ACI_ESCAVE_DEBUG_
     return 1;
 #else
     return uvsCurrentCycle;
 #endif
 }
References uvsCurrentCycle.
Referenced by ToolzerQuant().
CheckIML()
int CheckIML (int id, int x, int y, int frame)
 {
     iMobileLocation* m = imlTable[id];
     if(!frame){
         if(x > m -> x0 && x < m -> x1 && y > m -> y0 && y < m -> y1) return 1;
         }
     else {
         iMLFrame* f = m -> table + m -> cFrame;
         if(x > f -> x0 && x < f -> x0 + f -> sx && y > f -> y0 && y < f -> y0 + f -> sy) return 1;
         }
     return 0;
 }
Referenced by aciML_Data::check_xy().
CleanQueueIML()
void CleanQueueIML (int ch_id)
 {
     for(int i = 0;i < IML_MAXTABLE;i++)
         if(imlChannel[i] == ch_id) imlQueue[i] = -1;
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::event_quant().
GetPhaseIML()
int GetPhaseIML (int id)
 { return imlTable[id] -> getCurPhase(); }
Referenced by aciML_Close(), and aciML_Invert().
getWID()
int getWID (void)
 {
     return aScrDisp -> wMap -> world_ptr[aScrDisp -> curLocData -> WorldID] -> uvsID;
 }
Referenced by ToolzerQuant().
HandlerIML()
void HandlerIML (int code, int id, int val)
 {
     int i;
     if(!imlLocked[id]){
         switch(code){
             case AML_GO_INFINITE:
                 imlMode[id] = ACTIVATED;
                 imlTable[id] -> goPhase(-1);
                 break;
             case AML_GO_PHASE:
                 imlMode[id] = ACTIVATED;
                 imlTable[id] -> goPhase(val);
                 break;
             case AML_PUT_IN_QUEUE:
                 imlQueue[id] = val;
                 imlTable[id] -> goPhase(0);
                 break;
             case AML_STOP:
                 imlMode[id] = 0;
                 break;
             case AML_SET_PHASE:
                 imlTable[id] -> setPhase(val);
                 break;
             case AML_REWIND:
                 imlTable[id] -> setNull();
                 break;
             }
         }
     switch(code){
         case AML_PUT_IN_CH_QUEUE:
             for(i = 0;i < IML_MAXTABLE;i++)
                 if(imlChannel[i] == id)
                     if(imlTable[i] && imlMode[i] == ACTIVATED && !imlLocked[i]){
                         imlQueue[i] = val;
                         imlTable[i] -> goPhase(0);
                         return;
                         }
             if(imlTable[val] && !imlLocked[val]){
                 imlMode[val] = ACTIVATED;
                 imlTable[val] -> goPhase(0);
                 }
             break;
         case AML_STOP_CHANNEL:
             for(i = 0;i < IML_MAXTABLE;i++)
                 if(imlTable[i] && imlMode[i] == ACTIVATED && imlChannel[i] == id && !imlLocked[i])
                     imlMode[i] = 0;
             break;
         }
 }
Referenced by aciML_Close(), aciML_Invert(), and aciML_Dispatcher::event_quant().
ilandPrepare()
void ilandPrepare (void)
 {
     const int SIDE = 2*MAX_RADIUS + 1;
     short* rad = new short[SIDE*SIDE];
     int max = 0;
     int calc = 1;
     int i,j,r,ind;
     short* p = rad;
     if(calc){
         for(j = -MAX_RADIUS;j <= MAX_RADIUS;j++)
             for(i = -MAX_RADIUS;i <= MAX_RADIUS;i++,p++){
                 r = (int)sqrt(i*(double)i + j*(double)j);
                 if(r > MAX_RADIUS) *p = -1;
                 else {
                     *p = r;
                     maxRad[r]++;
                     max++;
                     }
                 }
         }
     int* xheap = new int[max];
     int* yheap = new int[max];
     for(ind = 0;ind <= MAX_RADIUS;ind++){
         xRad[ind] = xheap;
         yRad[ind] = yheap;
         for(p = rad,r = 0,j = -MAX_RADIUS;j <= MAX_RADIUS;j++)
             for(i = -MAX_RADIUS;i <= MAX_RADIUS;i++,p++)
                 if(*p == ind){
                     xheap[r] = i;
                     yheap[r] = j;
                     r++;
                     }
         xheap += maxRad[ind];
         yheap += maxRad[ind];
         }
     delete[] rad;
 }
References max(), and MAX_RADIUS.
Referenced by xtInitApplication().
InitIML()
void InitIML (void)
 {
     ML_FRAME_DELTA = new uchar[ML_FRAME_SIZE];
     ML_FRAME_TERRAIN = new uchar[ML_FRAME_SIZE];
 }
Referenced by aciML_Dispatcher::init().
isActiveIML()
int isActiveIML (int id)
 { return imlMode[id]; }
Referenced by aciML_Event::check_seq(), aciML_Dispatcher::event_quant(), and aciML_Event::quant().
isInQueueIML()
int isInQueueIML (int ch_id, int ml_id)
 {
     for(int i = 0;i < IML_MAXTABLE;i++)
         if(imlChannel[i] == ch_id && imlQueue[i] == ml_id) return 1;
     return 0;
 }
References IML_MAXTABLE.
Referenced by aciML_Event::check_seq(), and aciML_Dispatcher::event_quant().
isLockedIML()
int isLockedIML (int id)
 { return imlLocked[id]; }
Referenced by aciML_Event::check_seq(), aciML_Data::key_trap(), and aciML_Event::quant().
LockIML()
void LockIML (int id)
 { imlLocked[id] = 1; imlMode[id] = 0; }
Referenced by aciML_Dispatcher::event_quant().
MLverify()
void MLverify (XStream & ff)
 {
     ff.read(SignBuf,3);
     if(memcmp(SignBuf,MLsign,3)) ErrH.Abort("ML-VOT invalid format");
 };
References XStream::read().
Referenced by iMobileLocation::load(), and MobileLocation::load().
PauseIMLall()
void PauseIMLall (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++){
         imlPauseMode[i] = imlMode[i];
         imlMode[i] = 0;
         }
 }
References IML_MAXTABLE.
Referenced by aciML_Pause(), and aciML_Dispatcher::event_quant().
QuantIML()
int QuantIML (void)
 {
     int ret = 0,log;
     for(int i = 0;i < IML_MAXTABLE;i++)
         if(imlTable[i])
             if(imlMode[i] == ACTIVATED){
                 ret += (log = imlTable[i] -> quant(1));
                 if(!log){
                     imlMode[i] = 0;
                     if(imlQueue[i] != -1){
                         imlMode[imlQueue[i]] = ACTIVATED;
                         imlTable[imlQueue[i]] -> goPhase(-1);
                         imlQueue[i] = -1;
                         }
                     }
                 }
     return ret;
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::quant().
RegisterIML()
void RegisterIML (char * fname, int id, int channel)
 {
     if(id < 0 || id >= IML_MAXTABLE) ErrH.Abort("Wrong IML object ID");
     (imlTable[id] = new iMobileLocation) -> load(fname);
     imlChannel[id] = channel;
     imlMode[id] = 0;
     imlQueue[id] = -1;
     imlLocked[id] = 0;
     imlPauseMode[id] = 0;
 }
References XErrorHandler::Abort(), ErrH, and IML_MAXTABLE.
Referenced by aciML_Dispatcher::register_names().
ReleaseIML()
void ReleaseIML (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++) if(imlTable[i]){ delete imlTable[i]; imlTable[i] = NULL; }
     delete[] ML_FRAME_DELTA;
     ML_FRAME_DELTA = NULL;
     delete[] ML_FRAME_TERRAIN;
     ML_FRAME_TERRAIN = NULL;
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::finit().
ResumeIMLall()
void ResumeIMLall (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++)
         imlMode[i] = imlPauseMode[i];
 }
References IML_MAXTABLE.
Referenced by aciML_Resume(), and aciML_Dispatcher::event_quant().
StartupIML()
void StartupIML (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++){
         imlChannel[i] = 0;
         imlMode[i] = 0;
         imlQueue[i] = -1;
         imlPauseMode[i] = 0;
         imlLocked[i] = 0;
         }
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::init().
ToolzerQuant()
void ToolzerQuant (int x, int y)
 {
     y += 16;
     int period = !uvsCurrentWorldUnable ? aciGetCurCycle() : 3;
     if(getWID() == 3) period = 3;
     switch(period){
         case 0:
             ActiveTerrain[CHTYPEINDEX0] = 0;
             ActiveTerrain[CHTYPEINDEX1] = 1;
             ActiveTerrain[7] = 0;
             CurrentTerrain = CHTYPEINDEX0;
             deltaZone(x,y,32,10,1 - realRND(3),realRND(3),realRND(8) ? 0 : realRND(10));
             aciML_ToolzerRadius = 32;
             break;
         case 1:
             ActiveTerrain[CHTYPEINDEX0] = 1;
             ActiveTerrain[CHTYPEINDEX1] = 1;
             ActiveTerrain[7] = 0;
             CurrentTerrain = -1;
             deltaZone(x,y,40,10,0,0,0);
             aciML_ToolzerRadius = 40;
             break;
         case 2:
             ActiveTerrain[CHTYPEINDEX0] = 1;
             ActiveTerrain[CHTYPEINDEX1] = 0;
             ActiveTerrain[7] = 0;
             CurrentTerrain = CHTYPEINDEX1;
             deltaZone(x,y,32,10,1 - realRND(3),realRND(3),realRND(8) ? 0 : realRND(10));
             aciML_ToolzerRadius = 32;
             break;
         case 3:
             ActiveTerrain[CHTYPEINDEX0] = 1;
             ActiveTerrain[CHTYPEINDEX1] = 1;
             ActiveTerrain[7] = 1;
             CurrentTerrain = -1;
             deltaZone(x,y,45,10,1 + realRND(4),0,0);
             aciML_ToolzerRadius = 45;
             break;
         }
 }
References aciGetCurCycle(), ActiveTerrain, CHTYPEINDEX0, CHTYPEINDEX1, CurrentTerrain, getWID(), and uvsCurrentWorldUnable.
Referenced by aciML_Dispatcher::quant().
UnlockIML()
void UnlockIML (int id)
 { imlLocked[id] = 0; }
Referenced by aciML_Dispatcher::event_quant().
Variable Documentation
aciML_ToolzerRadius
int aciML_ToolzerRadius extern
ACTIVATED
const int ACTIVATED = 1
ActiveTerrain
int ActiveTerrain[TERRAIN_MAX] = { 1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0 }
Referenced by ToolzerQuant().
idOS
int idOS extern
Referenced by LoadingRTO2::Init().
IML_MAXTABLE
const int IML_MAXTABLE = 32
Referenced by CleanQueueIML(), isInQueueIML(), PauseIMLall(), QuantIML(), RegisterIML(), ReleaseIML(), ResumeIMLall(), and StartupIML().
uvsCurrentWorldUnable
int uvsCurrentWorldUnable extern
Referenced by ToolzerQuant().