Vangers: src/iscreen/iml.h File Reference
iml.h File Reference
Classes
struct iMLFrame
struct iMobileLocation
Macros
#define CHTYPEINDEX0 0
#define CHTYPEINDEX1 10
#define CHTYPE0 (CHTYPEINDEX0 << TERRAIN_OFFSET)
#define CHTYPE1 (CHTYPEINDEX1 << TERRAIN_OFFSET)
#define MLM_RELATIVE 0
#define MLM_ABSOLUTE 1
#define MLM_REL2ABS 2
Typedefs
typedef int MLAtype
Functions
void iregRender (int x0, int y0, int x1, int y1)
void RegisterIML (char *fname, int id, int channel)
void ReleaseIML (void)
void HandlerIML (int code, int id, int val)
int QuantIML (void)
int CheckIML (int id, int x, int y, int frame=0)
void PauseIMLall (void)
void ResumeIMLall (void)
int GetPhaseIML (int id)
int isActiveIML (int id)
void LockIML (int id)
void UnlockIML (int id)
int isLockedIML (int id)
int isInQueueIML (int ch_id, int ml_id)
void CleanQueueIML (int ch_id)
void SetFlushIML (int x, int y, int sx, int sy)
void dg_SendEvent (int code)
void ToolzerQuant (int x, int y)
Variables
const int MLPREC = 16
const int MLNAMELEN = 15
const int MAX_KEYPHASE = 4
Macro Definition Documentation
CHTYPE0
#define CHTYPE0 (CHTYPEINDEX0 << TERRAIN_OFFSET)
CHTYPE1
#define CHTYPE1 (CHTYPEINDEX1 << TERRAIN_OFFSET)
CHTYPEINDEX0
#define CHTYPEINDEX0 0
CHTYPEINDEX1
#define CHTYPEINDEX1 10
MLM_ABSOLUTE
#define MLM_ABSOLUTE 1
MLM_REL2ABS
#define MLM_REL2ABS 2
MLM_RELATIVE
#define MLM_RELATIVE 0
Typedef Documentation
MLAtype
typedef int MLAtype
Function Documentation
CheckIML()
int CheckIML (int id, int x, int y, int frame = 0)
 {
     iMobileLocation* m = imlTable[id];
     if(!frame){
         if(x > m -> x0 && x < m -> x1 && y > m -> y0 && y < m -> y1) return 1;
         }
     else {
         iMLFrame* f = m -> table + m -> cFrame;
         if(x > f -> x0 && x < f -> x0 + f -> sx && y > f -> y0 && y < f -> y0 + f -> sy) return 1;
         }
     return 0;
 }
Referenced by aciML_Data::check_xy().
CleanQueueIML()
void CleanQueueIML (int ch_id)
 {
     for(int i = 0;i < IML_MAXTABLE;i++)
         if(imlChannel[i] == ch_id) imlQueue[i] = -1;
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::event_quant().
dg_SendEvent()
void dg_SendEvent (int code)
 {
     switch(code){
         case AML_GET_QUESTION:
             aci_SendEvent(EV_SHOW_QUESTS);
             break;
         case AML_TAKE_ELEECH:
             aciOfferEleech();
             break;
         case AML_TAKE_WEEZYK:
             aciOfferWeezyk();
             break;
         case AML_WAIT_NEXT_PERIOD:
             aciWaitNextPeriod();
             break;
         case AML_CLEAR_QUESTION:
             aciClearQuestMenu();
             break;
         case AML_ABORT_ESCAVE_SESSION:
             iShopForcedExit();
             break;
         case AML_BLOCK_SHOP:
             iLockShop();
             break;
         case AML_UNBLOCK_SHOP:
             iUnlockShop();
             break;
         case AML_BLOCK_EXIT:
             iLockExit();
             break;
         case AML_UNBLOCK_EXIT:
             iUnlockExit();
             break;
         case AML_LAMPASSO_THEEND:
             iShopForcedExit();
             GameOverID = GAME_OVER_LAMPASSO;
             iTheEND = 1;
             break;
         case AML_KICK_OUT_FROM_ESCAVE:
             aciEscaveKickOut();
             break;
         case AML_ACCEPT_RUBBOX:
             aciAcceptRubox();
             break;
         case AML_ADD_RUBBOX:
             aciAddRubox();
             break;
         case AML_EXPROPRIATION:
             aciExpropriation();
             break;
         case AML_CHANGE_TO_RAFFA:
             aciChange2Raffa();
             break;
     }
 }
GetPhaseIML()
int GetPhaseIML (int id)
 { return imlTable[id] -> getCurPhase(); }
Referenced by aciML_Close(), and aciML_Invert().
HandlerIML()
void HandlerIML (int code, int id, int val)
 {
     int i;
     if(!imlLocked[id]){
         switch(code){
             case AML_GO_INFINITE:
                 imlMode[id] = ACTIVATED;
                 imlTable[id] -> goPhase(-1);
                 break;
             case AML_GO_PHASE:
                 imlMode[id] = ACTIVATED;
                 imlTable[id] -> goPhase(val);
                 break;
             case AML_PUT_IN_QUEUE:
                 imlQueue[id] = val;
                 imlTable[id] -> goPhase(0);
                 break;
             case AML_STOP:
                 imlMode[id] = 0;
                 break;
             case AML_SET_PHASE:
                 imlTable[id] -> setPhase(val);
                 break;
             case AML_REWIND:
                 imlTable[id] -> setNull();
                 break;
             }
         }
     switch(code){
         case AML_PUT_IN_CH_QUEUE:
             for(i = 0;i < IML_MAXTABLE;i++)
                 if(imlChannel[i] == id)
                     if(imlTable[i] && imlMode[i] == ACTIVATED && !imlLocked[i]){
                         imlQueue[i] = val;
                         imlTable[i] -> goPhase(0);
                         return;
                         }
             if(imlTable[val] && !imlLocked[val]){
                 imlMode[val] = ACTIVATED;
                 imlTable[val] -> goPhase(0);
                 }
             break;
         case AML_STOP_CHANNEL:
             for(i = 0;i < IML_MAXTABLE;i++)
                 if(imlTable[i] && imlMode[i] == ACTIVATED && imlChannel[i] == id && !imlLocked[i])
                     imlMode[i] = 0;
             break;
         }
 }
Referenced by aciML_Close(), aciML_Invert(), and aciML_Dispatcher::event_quant().
iregRender()
void iregRender (int x0, int y0, int x1, int y1)
 {
     LowX = iXCYCL(LowX);
     HiX = iXCYCL(HiX);
     LowY = iYCYCL(LowY);
     HiY = iYCYCL(HiY);
     LowX &= ~1;
     HiX |= 1;
     int SizeY = (LowY == HiY) ? iV_SIZE : iYCYCL(HiY - LowY);
     int SizeX = (0 == iXCYCL(HiX - LowX)) ? H_SIZE : iXCYCL(HiX - LowX);
     int BackScanLen = 0;
     int j;
     for(j = 0;j < SizeY;j++){
         const int y = iYCYCL(j + LowY);
         BYTE* pa0 = ivMap -> lineT[y];
         BYTE* pc0 = ivMap -> lineTcolor[y];
         if(!pa0) continue;
         MEMSET(ishadowParent,0,(((SizeX*SHADOWDEEP) >> POSPOWER) + 4*MAX_ALT));
         int hC = MAX_ALT;
         int LastStep = (H_SIZE - 1 - HiX) * SHADOWDEEP;
         LastStep -= ((LastStep >> POSPOWER) - MAX_ALT) << POSPOWER;
         //
         iPreStage(LastStep,HiX,pa0,hC,ishadowParent + MAX_ALT);
         //
         int x = HiX;
         BYTE* grid = ishadowParent + MAX_ALT + MAX_ALT;
         int MaxAlt = 0;
         iMainStage(pa0,hC,pc0,SizeX,x,grid,MaxAlt);
         //
         {
         x |= 1;
         BYTE* pa = pa0 + x;
         BYTE* pf = pa + H_SIZE;
         BYTE* pc = pc0 + x;
         BYTE* palCLRlast;
         BYTE* lightCLRlast;
         BYTE typeC = 0xFF;
         int MaxPossibleAlt = MAX_ALT;
         unsigned bNeedScan = 1;
         while(bNeedScan && MaxPossibleAlt >= 0){
             bNeedScan = 0;
             if(*pf & DOUBLE_LEVEL){
                 const BYTE lxVal = *pa;
                 const BYTE rxVal = *(pa0 + iXCYCL(x + 2));
                 const BYTE h = *pa;
                 const BYTE dh = *(pa - 1);
                 const BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 const BYTE level = h;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 grid += 3;
                 hC -= 3;
                 MaxAlt -= 3;
                 MaxPossibleAlt -= 3;
                 if(dh < MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *(pf - 1) |= SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *(pf - 1) &= ~SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 pa--; pf--; pc--;
                 if(*pf & SHADOW_MASK) bNeedScan = 1;
                 if(dh > hC){
                     MEMSET(grid + hC,1,dh - hC);
                     hC = dh;
                     }
                 MEMSET(grid + h - SS_WIDTH,1,SS_WIDTH + 1);
                 }
             else {
                 BYTE lxVal = *(pa - 1);
                 BYTE rxVal = *(pa0 + iXCYCL(x + 1));
                 BYTE h = *pa;
                 BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 BYTE level = h;
                 grid += 1;
                 hC -= 1;
                 MaxAlt -= 1;
                 MaxPossibleAlt -= 1;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 pa--; pf--; pc--;
                 rxVal = h;
                 h = lxVal;
                 lxVal = *(pa0 + iXCYCL(x - 2));
                 grid += 2;
                 hC -= 2;
                 MaxAlt -= 2;
                 MaxPossibleAlt -= 2;
                 type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 level = h;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 }
             if(x == 1){
                 x = H_SIZE - 1;
                 pa = pa0 + x;
                 pf = pa + H_SIZE;
                 pc = pc0 + x;
                 }
             else {
                 x = iXCYCL(x - 2);
                 pa--; pf--; pc--;
                 }
             }
         const int CurrScanLenght = iXCYCL(LowX - x);
         if(CurrScanLenght > BackScanLen) BackScanLen = CurrScanLenght;
         }
         }
 }
Referenced by iMLFrame::Render().
isActiveIML()
int isActiveIML (int id)
 { return imlMode[id]; }
Referenced by aciML_Event::check_seq(), aciML_Dispatcher::event_quant(), and aciML_Event::quant().
isInQueueIML()
int isInQueueIML (int ch_id, int ml_id)
 {
     for(int i = 0;i < IML_MAXTABLE;i++)
         if(imlChannel[i] == ch_id && imlQueue[i] == ml_id) return 1;
     return 0;
 }
References IML_MAXTABLE.
Referenced by aciML_Event::check_seq(), and aciML_Dispatcher::event_quant().
isLockedIML()
int isLockedIML (int id)
 { return imlLocked[id]; }
Referenced by aciML_Event::check_seq(), aciML_Data::key_trap(), and aciML_Event::quant().
LockIML()
void LockIML (int id)
 { imlLocked[id] = 1; imlMode[id] = 0; }
Referenced by aciML_Dispatcher::event_quant().
PauseIMLall()
void PauseIMLall (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++){
         imlPauseMode[i] = imlMode[i];
         imlMode[i] = 0;
         }
 }
References IML_MAXTABLE.
Referenced by aciML_Pause(), and aciML_Dispatcher::event_quant().
QuantIML()
int QuantIML (void)
 {
     int ret = 0,log;
     for(int i = 0;i < IML_MAXTABLE;i++)
         if(imlTable[i])
             if(imlMode[i] == ACTIVATED){
                 ret += (log = imlTable[i] -> quant(1));
                 if(!log){
                     imlMode[i] = 0;
                     if(imlQueue[i] != -1){
                         imlMode[imlQueue[i]] = ACTIVATED;
                         imlTable[imlQueue[i]] -> goPhase(-1);
                         imlQueue[i] = -1;
                         }
                     }
                 }
     return ret;
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::quant().
RegisterIML()
void RegisterIML (char * fname, int id, int channel)
 {
     if(id < 0 || id >= IML_MAXTABLE) ErrH.Abort("Wrong IML object ID");
     (imlTable[id] = new iMobileLocation) -> load(fname);
     imlChannel[id] = channel;
     imlMode[id] = 0;
     imlQueue[id] = -1;
     imlLocked[id] = 0;
     imlPauseMode[id] = 0;
 }
References XErrorHandler::Abort(), ErrH, and IML_MAXTABLE.
Referenced by aciML_Dispatcher::register_names().
ReleaseIML()
void ReleaseIML (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++) if(imlTable[i]){ delete imlTable[i]; imlTable[i] = NULL; }
     delete[] ML_FRAME_DELTA;
     ML_FRAME_DELTA = NULL;
     delete[] ML_FRAME_TERRAIN;
     ML_FRAME_TERRAIN = NULL;
 }
References IML_MAXTABLE.
Referenced by aciML_Dispatcher::finit().
ResumeIMLall()
void ResumeIMLall (void)
 {
     for(int i = 0;i < IML_MAXTABLE;i++)
         imlMode[i] = imlPauseMode[i];
 }
References IML_MAXTABLE.
Referenced by aciML_Resume(), and aciML_Dispatcher::event_quant().
SetFlushIML()
void SetFlushIML (int x, int y, int sx, int sy)
 {
     aciML_D -> add_flush(x,y,sx,sy);
 }
References aciML_D.
Referenced by aciML_ItemData::put_frame(), and iMobileLocation::setPhase().
ToolzerQuant()
void ToolzerQuant (int x, int y)
 {
     y += 16;
     int period = !uvsCurrentWorldUnable ? aciGetCurCycle() : 3;
     if(getWID() == 3) period = 3;
     switch(period){
         case 0:
             ActiveTerrain[CHTYPEINDEX0] = 0;
             ActiveTerrain[CHTYPEINDEX1] = 1;
             ActiveTerrain[7] = 0;
             CurrentTerrain = CHTYPEINDEX0;
             deltaZone(x,y,32,10,1 - realRND(3),realRND(3),realRND(8) ? 0 : realRND(10));
             aciML_ToolzerRadius = 32;
             break;
         case 1:
             ActiveTerrain[CHTYPEINDEX0] = 1;
             ActiveTerrain[CHTYPEINDEX1] = 1;
             ActiveTerrain[7] = 0;
             CurrentTerrain = -1;
             deltaZone(x,y,40,10,0,0,0);
             aciML_ToolzerRadius = 40;
             break;
         case 2:
             ActiveTerrain[CHTYPEINDEX0] = 1;
             ActiveTerrain[CHTYPEINDEX1] = 0;
             ActiveTerrain[7] = 0;
             CurrentTerrain = CHTYPEINDEX1;
             deltaZone(x,y,32,10,1 - realRND(3),realRND(3),realRND(8) ? 0 : realRND(10));
             aciML_ToolzerRadius = 32;
             break;
         case 3:
             ActiveTerrain[CHTYPEINDEX0] = 1;
             ActiveTerrain[CHTYPEINDEX1] = 1;
             ActiveTerrain[7] = 1;
             CurrentTerrain = -1;
             deltaZone(x,y,45,10,1 + realRND(4),0,0);
             aciML_ToolzerRadius = 45;
             break;
         }
 }
References aciGetCurCycle(), ActiveTerrain, CHTYPEINDEX0, CHTYPEINDEX1, CurrentTerrain, getWID(), and uvsCurrentWorldUnable.
Referenced by aciML_Dispatcher::quant().
UnlockIML()
void UnlockIML (int id)
 { imlLocked[id] = 0; }
Referenced by aciML_Dispatcher::event_quant().
Variable Documentation
MAX_KEYPHASE
const int MAX_KEYPHASE = 4
MLNAMELEN
const int MLNAMELEN = 15
Referenced by MobileLocation::clear(), MobileLocation::cloning(), iMobileLocation::iMobileLocation(), iMobileLocation::load(), and MobileLocation::load().
MLPREC
const int MLPREC = 16
Referenced by MLFrame::start(), and iMLFrame::start().