Vangers: lib/xtool/iniparser/iniparser.c File Reference
iniparser.c File Reference
Parser for ini files.
#include <ctype.h>
#include "iniparser.h"
Macros
#define ASCIILINESZ (1024)
#define INI_INVALID_KEY ((char*)-1)
Typedefs
typedef enum _line_status_ line_status
Enumerations
enum _line_status_ {
LINE_UNPROCESSED, LINE_ERROR, LINE_EMPTY, LINE_COMMENT,
LINE_SECTION, LINE_VALUE
}
Functions
int iniparser_getnsec (dictionary *d)
Get number of sections in a dictionary.
char * iniparser_getsecname (dictionary *d, int n)
Get name for section n in a dictionary.
void iniparser_dump (dictionary *d, FILE *f)
Dump a dictionary to an opened file pointer.
void iniparser_dump_ini (dictionary *d, FILE *f)
Save a dictionary to a loadable ini file.
char * iniparser_getstring (dictionary *d, const char *key, char *def)
Get the string associated to a key.
int iniparser_getint (dictionary *d, const char *key, int notfound)
Get the string associated to a key, convert to an int.
double iniparser_getdouble (dictionary *d, char *key, double notfound)
Get the string associated to a key, convert to a double.
int iniparser_getboolean (dictionary *d, const char *key, int notfound)
Get the string associated to a key, convert to a boolean.
int iniparser_find_entry (dictionary *ini, char *entry)
Finds out if a given entry exists in a dictionary.
int iniparser_set (dictionary *ini, char *entry, char *val)
Set an entry in a dictionary.
void iniparser_unset (dictionary *ini, char *entry)
Delete an entry in a dictionary.
dictionary * iniparser_load (const char *ininame)
Parse an ini file and return an allocated dictionary object.
void iniparser_freedict (dictionary *d)
Free all memory associated to an ini dictionary.
Detailed Description
Parser for ini files.
Author
N. Devillard
Date
Sep 2007
Version
3.0
Definition in file iniparser.c.
Macro Definition Documentation
ASCIILINESZ
#define ASCIILINESZ (1024)
INI_INVALID_KEY
#define INI_INVALID_KEY ((char*)-1)
Typedef Documentation
line_status
typedef enum _line_status_ line_status
This enum stores the status for each parsed line (internal use only).
Enumeration Type Documentation
_line_status_
enum _line_status_
This enum stores the status for each parsed line (internal use only).
Enumerator
LINE_UNPROCESSED
LINE_ERROR
LINE_EMPTY
LINE_COMMENT
LINE_SECTION
LINE_VALUE
{
     LINE_UNPROCESSED,
     LINE_ERROR,
     LINE_EMPTY,
     LINE_COMMENT,
     LINE_SECTION,
     LINE_VALUE
 } line_status ;
Function Documentation
iniparser_dump()
void iniparser_dump (dictionary * d, FILE * f)
Dump a dictionary to an opened file pointer.
Parameters
d Dictionary to dump.
f Opened file pointer to dump to.
Returns
void
This function prints out the contents of a dictionary, one element by line, onto the provided file pointer. It is OK to specify stderr or stdout as output files. This function is meant for debugging purposes mostly.
 {
     int     i ;
     if (d==NULL || f==NULL) return ;
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]==NULL)
             continue ;
         if (d->val[i]!=NULL) {
             fprintf(f, "[%s]=[%s]\n", d->key[i], d->val[i]);
         } else {
             fprintf(f, "[%s]=UNDEF\n", d->key[i]);
         }
     }
     return ;
 }
References _dictionary_::key, NULL, _dictionary_::size, and _dictionary_::val.
iniparser_dump_ini()
void iniparser_dump_ini (dictionary * d, FILE * f)
Save a dictionary to a loadable ini file.
Parameters
d Dictionary to dump
f Opened file pointer to dump to
Returns
void
This function dumps a given dictionary into a loadable ini file. It is Ok to specify stderr or stdout as output files.
 {
     int     i, j ;
     char    keym[ASCIILINESZ+1];
     int     nsec ;
     char *  secname ;
     int     seclen ;
     if (d==NULL || f==NULL) return ;
     nsec = iniparser_getnsec(d);
     if (nsec<1) {
         /* No section in file: dump all keys as they are */
         for (i=0 ; i<d->size ; i++) {
             if (d->key[i]==NULL)
                 continue ;
             fprintf(f, "%s = %s\n", d->key[i], d->val[i]);
         }
         return ;
     }
     for (i=0 ; i<nsec ; i++) {
         secname = iniparser_getsecname(d, i) ;
         seclen  = (int)strlen(secname);
         fprintf(f, "\n[%s]\n", secname);
         sprintf(keym, "%s:", secname);
         for (j=0 ; j<d->size ; j++) {
             if (d->key[j]==NULL)
                 continue ;
             if (!strncmp(d->key[j], keym, seclen+1)) {
                 fprintf(f,
                         "%-30s = %s\n",
                         d->key[j]+seclen+1,
                         d->val[j] ? d->val[j] : "");
             }
         }
     }
     fprintf(f, "\n");
     return ;
 }
References ASCIILINESZ, iniparser_getnsec(), iniparser_getsecname(), _dictionary_::key, NULL, _dictionary_::size, and _dictionary_::val.
iniparser_find_entry()
int iniparser_find_entry (dictionary * ini, char * entry)
Finds out if a given entry exists in a dictionary.
Parameters
ini Dictionary to search
entry Name of the entry to look for
Returns
integer 1 if entry exists, 0 otherwise
Finds out if a given entry exists in the dictionary. Since sections are stored as keys with NULL associated values, this is the only way of querying for the presence of sections in a dictionary.
 {
     int found=0 ;
     if (iniparser_getstring(ini, entry, INI_INVALID_KEY)!=INI_INVALID_KEY) {
         found = 1 ;
     }
     return found ;
 }
References INI_INVALID_KEY, and iniparser_getstring().
iniparser_freedict()
void iniparser_freedict (dictionary * d)
Free all memory associated to an ini dictionary.
Parameters
d Dictionary to free
Returns
void
Free all memory associated to an ini dictionary. It is mandatory to call this function before the dictionary object gets out of the current context.
 {
     dictionary_del(d);
 }
References dictionary_del().
Referenced by GetKeepSpace().
iniparser_getboolean()
int iniparser_getboolean (dictionary * d, const char * key, int notfound)
Get the string associated to a key, convert to a boolean.
Parameters
d Dictionary to search
key Key string to look for
notfound Value to return in case of error
Returns
integer
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the notfound value is returned.
A true boolean is found if one of the following is matched:
A string starting with 'y'
A string starting with 'Y'
A string starting with 't'
A string starting with 'T'
A string starting with '1'
A false boolean is found if one of the following is matched:
A string starting with 'n'
A string starting with 'N'
A string starting with 'f'
A string starting with 'F'
A string starting with '0'
The notfound value returned if no boolean is identified, does not necessarily have to be 0 or 1.
 {
     char    *   c ;
     int         ret ;
     c = iniparser_getstring(d, key, INI_INVALID_KEY);
     if (c==INI_INVALID_KEY) return notfound ;
     if (c[0]=='y' || c[0]=='Y' || c[0]=='1' || c[0]=='t' || c[0]=='T') {
         ret = 1 ;
     } else if (c[0]=='n' || c[0]=='N' || c[0]=='0' || c[0]=='f' || c[0]=='F') {
         ret = 0 ;
     } else {
         ret = notfound ;
     }
     return ret;
 }
References INI_INVALID_KEY, iniparser_getstring(), and key().
iniparser_getdouble()
double iniparser_getdouble (dictionary * d, char * key, double notfound)
Get the string associated to a key, convert to a double.
Parameters
d Dictionary to search
key Key string to look for
notfound Value to return in case of error
Returns
double
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the notfound value is returned.
 {
     char    *   str ;
     str = iniparser_getstring(d, key, INI_INVALID_KEY);
     if (str==INI_INVALID_KEY) return notfound ;
     return atof(str);
 }
References INI_INVALID_KEY, iniparser_getstring(), and key().
iniparser_getint()
int iniparser_getint (dictionary * d, const char * key, int notfound)
Get the string associated to a key, convert to an int.
Parameters
d Dictionary to search
key Key string to look for
notfound Value to return in case of error
Returns
integer
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the notfound value is returned.
Supported values for integers include the usual C notation so decimal, octal (starting with 0) and hexadecimal (starting with 0x) are supported. Examples:
"42" -> 42 "042" -> 34 (octal -> decimal) "0x42" -> 66 (hexa -> decimal)
Warning: the conversion may overflow in various ways. Conversion is totally outsourced to strtol(), see the associated man page for overflow handling.
Credits: Thanks to A. Becker for suggesting strtol()
 {
     char    *   str ;
     str = iniparser_getstring(d, key, INI_INVALID_KEY);
     if (str==INI_INVALID_KEY) return notfound ;
     return (int)strtol(str, NULL, 0);
 }
References INI_INVALID_KEY, iniparser_getstring(), key(), and NULL.
iniparser_getnsec()
int iniparser_getnsec (dictionary * d)
Get number of sections in a dictionary.
Parameters
d Dictionary to examine
Returns
int Number of sections found in dictionary
This function returns the number of sections found in a dictionary. The test to recognize sections is done on the string stored in the dictionary: a section name is given as "section" whereas a key is stored as "section:key", thus the test looks for entries that do not contain a colon.
This clearly fails in the case a section name contains a colon, but this should simply be avoided.
This function returns -1 in case of error.
 {
     int i ;
     int nsec ;
     if (d==NULL) return -1 ;
     nsec=0 ;
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]==NULL)
             continue ;
         if (strchr(d->key[i], ':')==NULL) {
             nsec ++ ;
         }
     }
     return nsec ;
 }
References _dictionary_::key, NULL, and _dictionary_::size.
Referenced by iniparser_dump_ini().
iniparser_getsecname()
char* iniparser_getsecname (dictionary * d, int n)
Get name for section n in a dictionary.
Parameters
d Dictionary to examine
n Section number (from 0 to nsec-1).
Returns
Pointer to char string
This function locates the n-th section in a dictionary and returns its name as a pointer to a string statically allocated inside the dictionary. Do not free or modify the returned string!
This function returns NULL in case of error.
 {
     int i ;
     int foundsec ;
     if (d==NULL || n<0) return NULL ;
     foundsec=0 ;
     for (i=0 ; i<d->size ; i++) {
         if (d->key[i]==NULL)
             continue ;
         if (strchr(d->key[i], ':')==NULL) {
             foundsec++ ;
             if (foundsec>n)
                 break ;
         }
     }
     if (foundsec<=n) {
         return NULL ;
     }
     return d->key[i] ;
 }
References _dictionary_::key, NULL, and _dictionary_::size.
Referenced by iniparser_dump_ini().
iniparser_getstring()
char* iniparser_getstring (dictionary * d, const char * key, char * def)
Get the string associated to a key.
Parameters
d Dictionary to search
key Key string to look for
def Default value to return if key not found.
Returns
pointer to statically allocated character string
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the pointer passed as 'def' is returned. The returned char pointer is pointing to a string allocated in the dictionary, do not free or modify it.
 {
     char * lc_key ;
     char * sval ;
     if (d==NULL || key==NULL)
         return def ;
     lc_key = strlwc(key);
     sval = dictionary_get(d, lc_key, def);
     return sval ;
 }
References key(), and NULL.
Referenced by ivrtMap::analyzeINI(), GetKeepSpace(), iniparser_find_entry(), iniparser_getboolean(), iniparser_getdouble(), iniparser_getint(), and KeepCleanUp().
iniparser_load()
dictionary* iniparser_load (const char * ininame)
Parse an ini file and return an allocated dictionary object.
Parameters
ininame Name of the ini file to read.
Returns
Pointer to newly allocated dictionary
This is the parser for ini files. This function is called, providing the name of the file to be read. It returns a dictionary object that should not be accessed directly, but through accessor functions instead.
The returned dictionary must be freed using iniparser_freedict().
 {
     FILE * in ;
     char line    [ASCIILINESZ+1] ;
     char section [ASCIILINESZ+1] ;
     char key     [ASCIILINESZ+1] ;
     char tmp     [ASCIILINESZ+1] ;
     char val     [ASCIILINESZ+1] ;
     int  last=0 ;
     int  len ;
     int  lineno=0 ;
     int  errs=0;
     dictionary * dict ;
     if ((in=fopen(ininame, "r"))==NULL) {
         fprintf(stderr, "iniparser: cannot open %s\n", ininame);
         return NULL ;
     }
     dict = dictionary_new(0) ;
     if (!dict) {
         fclose(in);
         return NULL ;
     }
     memset(line,    0, ASCIILINESZ+1);
     memset(section, 0, ASCIILINESZ+1);
     memset(key,     0, ASCIILINESZ+1);
     memset(val,     0, ASCIILINESZ+1);
     last=0 ;
     while (fgets(line+last, ASCIILINESZ-last, in)!=NULL) {
         lineno++ ;
         len = (int)strlen(line)-1;
         /* Safety check against buffer overflows */
         if (line[len]!='\n') {
             fprintf(stderr,
                     "iniparser: input line too long in %s (%d)\n",
                     ininame,
                     lineno);
             dictionary_del(dict);
             fclose(in);
             return NULL ;
         }
         /* Get rid of \n and spaces at end of line */
         while ((len>=0) &&
                 ((line[len]=='\n') || (isspace(line[len])))) {
             line[len]=0 ;
             len-- ;
         }
         if (len<0) {
             len = 0;
         }
         /* Detect multi-line */
         if (line[len]=='\\') {
             /* Multi-line value */
             last=len ;
             continue ;
         } else {
             last=0 ;
         }
         switch (iniparser_line(line, section, key, val)) {
             case LINE_EMPTY:
             case LINE_COMMENT:
             break ;
             case LINE_SECTION:
             errs = dictionary_set(dict, section, NULL);
             break ;
             case LINE_VALUE:
             memset(tmp, 0, ASCIILINESZ+1);
             strncpy(tmp, section, strlen(section));
             tmp[strlen(section)] = ':';
             strncpy(tmp+strlen(tmp), key, strlen(key));
             //snprintf(tmp, ASCIILINESZ, "%s:%s", section, key);
             //printf("tmp:%s\n", tmp);
             errs = dictionary_set(dict, tmp, val) ;
             break ;
             case LINE_ERROR:
             fprintf(stderr, "iniparser: syntax error in %s (%d):\n",
                     ininame,
                     lineno);
             fprintf(stderr, "-> %s\n", line);
             errs++ ;
             break;
             default:
             break ;
         }
         memset(line, 0, ASCIILINESZ+1);
         last=0;
         if (errs<0) {
             fprintf(stderr, "iniparser: memory allocation failure\n");
             break ;
         }
     }
     if (errs) {
         dictionary_del(dict);
         dict = NULL ;
     }
     fclose(in);
     return dict ;
 }
References ASCIILINESZ, dictionary_del(), dictionary_new(), key(), and NULL.
Referenced by ivrtMap::analyzeINI(), GetKeepSpace(), and KeepCleanUp().
iniparser_set()
int iniparser_set (dictionary * ini, char * entry, char * val)
Set an entry in a dictionary.
Parameters
ini Dictionary to modify.
entry Entry to modify (entry name)
val New value to associate to the entry.
Returns
int 0 if Ok, -1 otherwise.
If the given entry can be found in the dictionary, it is modified to contain the provided value. If it cannot be found, -1 is returned. It is Ok to set val to NULL.
 {
     return dictionary_set(ini, strlwc(entry), val) ;
 }
References dictionary_set().
iniparser_unset()
void iniparser_unset (dictionary * ini, char * entry)
Delete an entry in a dictionary.
Parameters
ini Dictionary to modify
entry Entry to delete (entry name)
Returns
void
If the given entry can be found, it is deleted from the dictionary.
 {
     dictionary_unset(ini, strlwc(entry));
 }
References dictionary_unset().