Vangers: src/iscreen/iscr_fnc.cpp File Reference
iscr_fnc.cpp File Reference
#include "../global.h"
#include "../sound/hsound.h"
#include "../network.h"
#include "../xjoystick.h"
#include "ivmap.h"
#include "iworld.h"
#include "i_str.h"
#include "hfont.h"
#include "iscreen.h"
#include "iscript.h"
#include "i_mem.h"
#include "ikeys.h"
#include "controls.h"
#include "ext_evnt.h"
#include "../actint/item_api.h"
#include "../actint/a_consts.h"
#include "../actint/actint.h"
#include "../actint/mlconsts.h"
#include "../actint/mlstruct.h"
#include "../actint/acsconst.h"
#include "../actint/aci_evnt.h"
#include "../actint/aci_scr.h"
#include <arpa/inet.h>
#include "../sound/hmusic.h"
Macros
#define EXTQUIT_VERIFY
#define _SAVE_SCREEN_
#define I_TIME_DELTA 1
#define FADE_SPEED 60
#define ACI_DOOR_DELAY 10
Functions
int iGetEscaveTime (void)
void aciVMapPrepare (void)
void iPrepareHallOfFame (void)
void iBlockJoystickOption (int mode)
void iInitProxyOptions (void)
iListElement * iGetObject (const char *scr, const char *obj)
void aciAutoSave (void)
void shotFlush (void)
void iGetIP (void)
void iInitStrings (void)
void iInitKeepOptions (void)
void iKeepCleanUp (void)
int GetKeepSpace (void)
void KeepCleanUp (void)
void aLoadFonts32 (void)
void iPrepareResults (void)
void iPreparePlayerResults (int id)
void iCreateServer (void)
void iChatInit (void)
void iChatQuant (int flush=0)
void iChatFinit (void)
void iChatKeyQuant (SDL_Event *k)
void iChatMouseQuant (int x, int y, int bt)
void iSoundQuant (int value=0)
void iPrepareSaveNames (void)
void iInitServersList ()
void iUpdateServersList ()
void iServersListUp ()
void iServersListDown ()
void iConnect2Server (void)
void iInitControlKey (int id, int num)
void iDeleteControl (int vkey, int id)
void iDeleteControlKey (int id, int num)
void iUpdateMultiGameName (void)
void iSetMultiGameParameters (void)
void iGetMultiGameParameters (void)
void iLockMultiGameParameters (void)
void iUnlockMultiGameParameters (void)
ServerFindChain * iGetCurServer (void)
void SetSoundVolume (int)
void EffectsOff (void)
int acsQuant (void)
void acsHandleExtEvent (int code, int data0=0, int data1=0, int data2=0)
void ipal_init (unsigned char *p)
void ipal_iter (int r)
void iKeyTrap (int k)
void iInitMultiGames (void)
void aci_setMatrixBorder (void)
void aci_setScMatrixBorder (void)
void aciSet_aMouse (void)
void aciSet_iMouse (void)
void aciShowLocationPicture (void)
void aciShowLocation (void)
void aciHideLocation (void)
void aciCloseGate (void)
void aciOpenGate (void)
void aciSwapMatrices (void)
void aciCancelMatrix (void)
void aciShowScMatrix (void)
void iShopForcedExit (void)
void iLockShop (void)
void iUnlockShop (void)
void put_fon (int x, int y, int sx, int sy, unsigned char *buf)
void get_fon (int x, int y, int sx, int sy, unsigned char *buf)
void loadMouseFrames (void)
void scale_buf (int sx, int sy, int sc, unsigned char *p, unsigned char *p1)
void put_buf (int x, int y, int sx, int sy, unsigned char *buf, unsigned char *mask, int lev, int hide_mode)
void put_level (int x, int y, int sx, int sy, int lev)
void get_buf (int x, int y, int sx, int sy, uchar *buf)
void get_col_buf (int x, int y, int sx, int sy, uchar *buf)
void iPutStr (int x, int y, int fnt, unsigned char *str, int mode, int scale, int space, int level, int hide_mode)
int iStrLen (char *p, int f, int space)
void ivMapPrepare (void)
void InitScreenFonts (void)
void LoadingMessage (int flush=0)
void put_map (int x, int y, int sx, int sy)
void i_get_scrfon (int x, int y, int sx, int sy, unsigned char *buf)
void i_put_scrfon (int x, int y, int sx, int sy, unsigned char *buf)
void i_mem_putspr (int x, int y, int sx, int sy, unsigned char *buf)
void mem_putspr (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char *src, unsigned char *dest)
void iInit (void)
void map_init (void)
void init_hfonts (void)
void free_hfonts (void)
void i_preExtQuant (void)
void i_postExtQuant (void)
void RegisterValues (void)
void iPrepareOptions (void)
void iregRender (int x0, int y0, int x1, int y1)
void MS_init (void)
void recorder_synchro (unsigned int frame)
void KeyCenter (SDL_Event *key)
void i_getpal (unsigned char *p)
void aci_iScreenQuant (void)
void i_slake_pal (unsigned char *p, int delta)
void i_evince_pal (unsigned char *p, int delta)
void iSaveData (void)
void iLoadData (void)
void iSaveControls (void)
void iLoadControls (void)
void aciSaveData (void)
void aciLoadData (void)
void uvsQuant (void)
void iMS_LeftPress (int, int, int)
void iMS_LeftUnpress (int, int, int)
void iMS_RightPress (int, int, int)
void iMS_RightUnpress (int, int, int)
void iMS_Movement (int, int, int)
void aMS_LeftPress (int, int, int)
void aMS_LeftUnpress (int, int, int)
void aMS_RightPress (int, int, int)
void aMS_RightUnpress (int, int, int)
void aMS_Movement (int, int, int)
void iSecondInit (void)
void set_mouse (void)
void iPreInitFirst ()
void iQuantFirst (void)
void iQuantPrepare (void)
int iQuantSecond (void)
void iFinitQuant (void)
void iOutEscaveInit (void)
int iOutEscaveQuant (void)
void iOutEscaveFinit (void)
void restore_mouse_cursor (void)
void set_mouse_cursor (char *p, int sx, int sy)
iScreen * iCreateScreen (const char *id, iScreen *tpl)
iScreenObject * iCreateScreenObject (const char *id, iScreenObject *tpl)
iTriggerObject * iCreateTriggerObject (const char *id, iScreenObject *tpl)
iScreenElement * iCreateScreenElement (int tp, const char *id, iScreenElement *tpl)
iScreenEvent * iCreateScreenEvent (iScreenEvent *tpl)
iScreenEventCommand * iCreateEventCommand (iScreenEventCommand *tpl)
void iInitText (iScreenObject *obj, char *text, int text_len, int font, int space, int null_level)
void iInitS_Text (iScreenObject *obj, char *text, int text_len, int font, int space, int null_level)
void i_change_res (void)
void iScrQuantPrepare (void)
void iScrQuantFinit (void)
void iLockExit (void)
void iUnlockExit (void)
void iKeyClear (void)
void iHandleExtEvent (int code, int data)
int getWID (void)
Variables
iStringElement ** iControlsStr
int MusicON
int SoundVolumePanning
int KeepON
int RecorderMode
int iCurMultiGame
int SoundVolumeCD
int MuteLog
int EffectInUsePriory
int EffectInUse
iScreenDispatcher * iScrDisp
int aciAutoRun
int aciML_ToolzerON
int aciLoadLog
int aciBreathFlag
int Dead
int ExclusiveLog
int DIBLog
int actintLowResFlag
int actintActiveFlag
int iEvLineID
int acsScreenID
int actIntLog
char * aci_iScreenID
unsigned char * actIntPal
actIntDispatcher * aScrDisp
int iScreenLastInput
int iScreenChat
int iChatON
const int iFRAME_CYCLE = 10
HFont ** HFntTable = NULL
iScreenFont ** iScrFontTable
int iNumFonts = 1
uchar * iscrPal
const char * CurServerName = "Server"
const char * CurPlayerName = "Vanger"
int iMouseX = 0
int iMouseY = 0
int iMousePrevX = 0
int iMousePrevY = 0
int iForcedExitFlag = 0
int iTheEND = 0
int iFrameCount = 0
int iFrameFlag = 0
int aciCurCredits07 = 0
int iScreenLog = 0
int iFirstInit = 0
int iScreenActive = 0
int iMultiFlag = 0
short MouseSizeX = 0
short MouseSizeY = 0
short MouseSize = 0
unsigned char * MouseFrames
int MouseSize2 = 0
short aMouseSizeX = 0
short aMouseSizeY = 0
short aMouseSize = 0
unsigned char * aMouseFrames
short iMouseSizeX = 0
short iMouseSizeY = 0
short iMouseSize = 0
unsigned char * iMouseFrames
int iStartupLog = 0
int iPause = 0
int iEndGameFlag = 0
int iCurHall = 0
int iEscaveTimer = 0
int iAbortGameFlag = 0
int iAbortGameMode = 1
int iMouseLPressFlag = 0
int iMouseRPressFlag = 0
int iSlotNumber = 0
int iCDTrackLog = 0
int iFirstServerSearch = 0
int iCurServer = 0
ServerFindChain * iFirstServerPtr
XBuffer * iResBuf
const char * iVideoPath = "resource/video/"
const char * iVideoPathDefault = "resource/video/"
const char * iSTR_WORLD_NONE_CHAR = iSTR_WORLD_NONE_CHAR1
const char * iSTR_WORLD_FOSTRAL_CHAR = iSTR_WORLD_FOSTRAL_CHAR1
const char * iSTR_WORLD_GLORX_CHAR = iSTR_WORLD_GLORX_CHAR1
const char * iSTR_WORLD_NECROSS_CHAR = iSTR_WORLD_NECROSS_CHAR1
const char * iSTR_WORLD_XPLO_CHAR = iSTR_WORLD_XPLO_CHAR1
const char * iSTR_WORLD_KHOX_CHAR = iSTR_WORLD_KHOX_CHAR1
const char * iSTR_WORLD_BOOZEENA_CHAR = iSTR_WORLD_BOOZEENA_CHAR1
const char * iSTR_WORLD_WEEXOW_CHAR = iSTR_WORLD_WEEXOW_CHAR1
const char * iSTR_WORLD_HMOK_CHAR = iSTR_WORLD_HMOK_CHAR1
const char * iSTR_WORLD_THREALL_CHAR = iSTR_WORLD_THREALL_CHAR1
const char * iSTR_WORLD_ARK_A_ZNOY_CHAR = iSTR_WORLD_ARK_A_ZNOY_CHAR1
const char * iSTR_COLOR_GREEN_CHAR = iSTR_COLOR_GREEN_CHAR1
const char * iSTR_COLOR_ORANGE_CHAR = iSTR_COLOR_ORANGE_CHAR1
const char * iSTR_COLOR_BLUE_CHAR = iSTR_COLOR_BLUE_CHAR1
const char * iSTR_COLOR_YELLOW_CHAR = iSTR_COLOR_YELLOW_CHAR1
const char * iSTR_COLOR_RED_CHAR = iSTR_COLOR_RED_CHAR1
const char * iSTR_COLOR_WHITE_CHAR = iSTR_COLOR_WHITE_CHAR1
const char * iSTR_COLOR_GRAY_CHAR = iSTR_COLOR_GRAY_CHAR1
const char * iSTR_COLOR_BLACK_CHAR = iSTR_COLOR_BLACK_CHAR1
const char * iSTR_COLOR_CAMOUFLAGE_CHAR = iSTR_COLOR_CAMOUFLAGE_CHAR1
const char * iSTR_COLOR_PATROL_CHAR = iSTR_COLOR_PATROL_CHAR1
const char * iSTR_MUTE_ALL = iSTR_MUTE_ALL1
const char * iSTR_CLEAR_LOG = iSTR_CLEAR_LOG1
const char * iSTR_BACKGROUND = iSTR_BACKGROUND1
const char * iSTR_LEAVE_CHAT = iSTR_LEAVE_CHAT1
const char * iSTR_All = iSTR_All1
const char * iSTR_Yellow = iSTR_Yellow1
const char * iSTR_Orange = iSTR_Orange1
const char * iSTR_Blue = iSTR_Blue1
const char * iSTR_Green = iSTR_Green1
const char * iSTR_Red = iSTR_Red1
const char * iSTR_White = iSTR_White1
const char * iSTR_Gray = iSTR_Gray1
const char * iSTR_Black = iSTR_Black1
const char * iSTR_Camouflage = iSTR_Camouflage1
const char * iSTR_Patrol = iSTR_Patrol1
const char * iSTR_CleanUp = iSTR_CleanUp1
const char * iSTR_SpaceInUse = iSTR_SpaceInUse1
const char * iSTR_MBytes = iSTR_MBytes1
const char * iSTR_MP_Kills = iSTR_MP_Kills1
const char * iSTR_MP_Deaths = iSTR_MP_Deaths1
const char * iSTR_MP_DeathTimeMin = iSTR_MP_DeathTimeMin1
const char * iSTR_MP_DeathTimeMax = iSTR_MP_DeathTimeMax1
const char * iSTR_MP_Kills_rate = iSTR_MP_Kills_rate1
const char * iSTR_MP_Deaths_rate = iSTR_MP_Deaths_rate1
const char * iSTR_MP_Ware01_Delivery = iSTR_MP_Ware01_Delivery1
const char * iSTR_MP_Ware02_Delivery = iSTR_MP_Ware02_Delivery1
const char * iSTR_MP_Min_delivery_time = iSTR_MP_Min_delivery_time1
const char * iSTR_MP_Max_delivery_time = iSTR_MP_Max_delivery_time1
const char * iSTR_MP_StolenWares = iSTR_MP_StolenWares1
const char * iSTR_MP_Wares_lost = iSTR_MP_Wares_lost1
const char * iSTR_MP_Total_time = iSTR_MP_Total_time1
const char * iSTR_MP_Min_checkpoint_time = iSTR_MP_Min_checkpoint_time1
const char * iSTR_MP_Max_checkpoint_time = iSTR_MP_Max_checkpoint_time1
const char * iSTR_MP_1st_part_delivery = iSTR_MP_1st_part_delivery1
const char * iSTR_MP_2nd_part_delivery = iSTR_MP_2nd_part_delivery1
const char * iSTR_MP_Mechos_frame = iSTR_MP_Mechos_frame1
const char * iSTR_MP_Mechos_assembled_in = iSTR_MP_Mechos_assembled_in1
const char * iSTR_NONE = iSTR_NONE1
const char * iSTR_EMPTY_SLOT = iSTR_EMPTY_SLOT1
const char * iSTR_Checkpoints_Number = iSTR_Checkpoints_Number1
const char * iSTR_DefaultPassword = iSTR_DefaultPassword1
int iProxyTerrFlag = 0
int iProxyServerStrTerr = -1
int iProxyServerTerr = -1
int iProxyPortStrTerr = -1
int iProxyPortTerr = -1
int iProxyUsage = 0
char * iProxyServer = NULL
int iProxyPort = 1080
int iServerPort = 2197
Macro Definition Documentation
_SAVE_SCREEN_
#define _SAVE_SCREEN_
ACI_DOOR_DELAY
#define ACI_DOOR_DELAY 10
EXTQUIT_VERIFY
#define EXTQUIT_VERIFY
FADE_SPEED
#define FADE_SPEED 60
I_TIME_DELTA
#define I_TIME_DELTA 1
Function Documentation
aci_iScreenQuant()
void aci_iScreenQuant (void)
 {
     aScrDisp -> iKeyQuant();
     aScrDisp -> EventQuant();
     aciML_D -> quant();
     aScrDisp -> i_redraw();
     aScrDisp -> i_flush();
 }
References aciML_D, and aScrDisp.
aci_setMatrixBorder()
void aci_setMatrixBorder (void)
 {
     int id,i,t,sz;
     XBuffer XBuf;
     iBitmapElement* p = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_MATRIX_BORDER_ID];
     if(!p) return;
     short sx,sy;
     if(aScrDisp -> curMatrix){
         id = aScrDisp -> curMatrix -> internalID;
         XBuf < "resource/actint/iscreen/matrix/mt";
         if(id < 10) XBuf < "0";
         XBuf <= id < ".bmp";
         XStream fh(XBuf.GetBuf(),XS_IN);
         fh > sx > sy;
         fh.read(p -> fdata,sx * sy);
         fh.close();
         sz = sx * sy;
         for(i = 0; i < sz; i ++){
             t = ((unsigned char*)p -> fdata)[i];
             if(t)
                 t += p -> bmp_null_level;
             else
                 t = HFONT_NULL_LEVEL;
             p -> fdata[i] = t;
         }
     }
     else {
         memset(p -> fdata,HFONT_NULL_LEVEL,p -> SizeX * p -> SizeY);
     }
 }
References ACI_MATRIX_BORDER_ID, aScrDisp, XStream::close(), curMatrix, XBuffer::GetBuf(), HFONT_NULL_LEVEL, XStream::read(), and XS_IN.
Referenced by aciCancelMatrix(), aciSwapMatrices(), actIntDispatcher::EventQuant(), and iScreenDispatcher::move2screen().
aci_setScMatrixBorder()
void aci_setScMatrixBorder (void)
 {
     XBuffer XBuf;
 //  if(!aScrDisp -> secondMatrix) return;
     iBitmapElement* p = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(!p) return;
     if(!aScrDisp -> secondMatrix){
         memset(p -> fdata,HFONT_NULL_LEVEL,p -> bSizeX * p -> bSizeY);
         return;
     }
     short sx,sy;
     int id = aScrDisp -> secondMatrix -> internalID;
     XBuf < "resource/actint/iscreen/matrix/mt";
     if(id < 10) XBuf < "0";
     XBuf <= id < ".bmp";
     XStream fh(XBuf.GetBuf(),XS_IN);
     fh > sx > sy;
     fh.read(p -> fdata,sx * sy);
     fh.close();
     int i,t,sz = sx * sy;
     for(i = 0; i < sz; i ++){
         t = ((unsigned char*)p -> fdata)[i];
         if(t)
             t += p -> bmp_null_level;
         else
             t = HFONT_NULL_LEVEL;
         p -> fdata[i] = t;
     }
 }
References ACI_SMATRIX_BORDER_ID, aScrDisp, XStream::close(), XBuffer::GetBuf(), HFONT_NULL_LEVEL, XStream::read(), and XS_IN.
Referenced by aciCancelMatrix(), aciShowScMatrix(), aciSwapMatrices(), actIntDispatcher::EventQuant(), and iScreenDispatcher::move2screen().
aciAutoSave()
void aciAutoSave (void)
 {
     if(NetworkON || aScrDisp -> curLocData -> WorldID == XPLO_ID) return;
     aciAutoSaveFlag = 1;
     acsSaveData();
 }
References aciAutoSaveFlag, acsSaveData(), aScrDisp, NetworkON, and XPLO_ID.
Referenced by aciShowLocation().
aciCancelMatrix()
void aciCancelMatrix (void)
 {
     _iSTORE_OFFS_;
     int i,num2,timer = 0;
     iScreenObject* m_owner = NULL,*m2_owner = NULL;
     iBitmapElement* b,*b1;
     b = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_MATRIX_BORDER_ID];
     b1 = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(b) m_owner = (iScreenObject*)b -> owner;
     if(b1) m2_owner = (iScreenObject*)b1 -> owner;
     unsigned char* fon_buf;
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
 #ifndef _ACI_NO_SHOP_ANIMATION_
     num2 = aScrDisp -> curLocData -> numMatrixShutters2;
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters2[i] -> loadData();
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     SOUND_GATE();
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
 #endif
     aScrDisp -> cancel_matrix();
     aci_setMatrixBorder();
     aci_setScMatrixBorder();
     if(m_owner){
         m_owner -> putfon();
         m_owner -> redraw();
     }
     if(m2_owner){
         m2_owner -> curHeightScale = 0;
         m2_owner -> putfon();
         m2_owner -> redraw();
     }
     put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
     if(aScrDisp -> curMatrix)
         aScrDisp -> curMatrix -> redraw();
     iScrDisp -> curScr -> show_avi();
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 #else
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     SOUND_GATE();
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> freeData();
     }
     delete[] fon_buf;
 #endif
     if(v_flag)
         XGR_MouseShow();
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_MATRIX_BORDER_ID, aci_setMatrixBorder(), aci_setScMatrixBorder(), ACI_SHUTTER_CLOSE, ACI_SHUTTER_OPEN, ACI_SMATRIX_BORDER_ID, aScrDisp, curMatrix, i_get_scrfon(), i_put_scrfon(), I_RES_X, I_RES_Y, iScrDisp, iScreenOffs, NULL, put_map(), Redraw, SOUND_GATE, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
Referenced by actIntDispatcher::EventQuant().
aciCloseGate()
void aciCloseGate (void)
 {
     int i,timer,max_timer = 0;
     _iSTORE_OFFS_;
     unsigned char* fon_buf;
 #ifdef _ACI_NO_SHOP_ANIMATION_
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     return;
 #endif
     SOUND_GATE();
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer){
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         return;
     }
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_CLOSE);
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < max_timer; i ++)
             timer += aScrDisp -> curLocData -> GateShutters[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < max_timer; i ++)
             aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> freeData();
     }
     delete[] fon_buf;
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_SHUTTER_CLOSE, aScrDisp, i_get_scrfon(), i_put_scrfon(), Redraw, SOUND_GATE, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseVisible, and xtClearMessageQueue().
aciHideLocation()
void aciHideLocation (void)
 {
     int i,timer,max_timer = 0;
     _iSTORE_OFFS_;
     unsigned char* fon_buf;
 #ifdef _ACI_NO_SHOP_ANIMATION_
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     return;
 #endif
     SOUND_GATE();
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer){
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         return;
     }
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_CLOSE);
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     aciML_D -> quant();
     aciML_D -> flush();
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < max_timer; i ++)
             timer += aScrDisp -> curLocData -> GateShutters[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < max_timer; i ++)
             aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> freeData();
     }
     delete[] fon_buf;
     if(v_flag)
         XGR_MouseShow();
     _iRESTORE_OFFS_;
 //  StartWTRACK();
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_SHUTTER_CLOSE, aciML_D, aScrDisp, flush(), i_get_scrfon(), i_put_scrfon(), Redraw, SOUND_GATE, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
Referenced by iFinitQuant().
aciLoadData()
void aciLoadData (void)
 {
     acsLoadData();
 }
References acsLoadData().
Referenced by FirstEscaveRTO::Init().
aciOpenGate()
void aciOpenGate (void)
 {
     int i,timer,max_timer = 0;
     _iSTORE_OFFS_;
     unsigned char* fon_buf;
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_MouseShow();
     return;
 #endif
     SOUND_GATE();
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer){
         XGR_MouseShow();
         return;
     }
     if(XGR_MouseVisible())
         XGR_MouseHide();
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < max_timer; i ++)
         aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < max_timer; i ++)
             timer += aScrDisp -> curLocData -> GateShutters[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < max_timer; i ++)
             aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> freeData();
     }
     delete[] fon_buf;
     XGR_MouseShow();
     iKeyClear();
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_SHUTTER_OPEN, aScrDisp, i_get_scrfon(), i_put_scrfon(), iKeyClear(), Redraw, SOUND_GATE, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
aciSaveData()
void aciSaveData (void)
 {
     acsSaveData();
 }
aciSet_aMouse()
void aciSet_aMouse (void)
 {
     MouseSizeX = aMouseSizeX;
     MouseSizeY = aMouseSizeY;
     MouseSize = aMouseSize;
     MouseFrames = aMouseFrames;
 }
References aMouseFrames, aMouseSize, aMouseSizeX, aMouseSizeY, MouseFrames, MouseSize, MouseSizeX, and MouseSizeY.
aciSet_iMouse()
void aciSet_iMouse (void)
 {
     MouseSizeX = iMouseSizeX;
     MouseSizeY = iMouseSizeY;
     MouseSize = iMouseSize;
     MouseFrames = iMouseFrames;
 }
References iMouseFrames, iMouseSize, iMouseSizeX, iMouseSizeY, MouseFrames, MouseSize, MouseSizeX, and MouseSizeY.
Referenced by iQuantFirst().
aciShowLocation()
void aciShowLocation (void)
 {
     int i,timer,max_timer = 0;
 //    StopCDTRACK();
     SlowCDTRACK();
     _iSTORE_OFFS_;
     unsigned char* fon_buf;
     aciAutoSave();
 #ifdef _ACI_NO_SHOP_ANIMATION_
     aciML_D -> quant();
     aciML_D -> flush();
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     XGR_SetPal(iscrPal,0,255);
     XGR_MouseShow();
     return;
 #endif
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer){
         aciML_D -> quant();
         aciML_D -> flush();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         i_evince_pal(iscrPal,8);
         XGR_MouseShow();
         return;
     }
     if(XGR_MouseVisible())
         XGR_MouseHide();
 /*
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_OPEN);
     }
 */
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     aciML_D -> quant();
     aciML_D -> flush(0);
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     //TODO: stalkerg   !
     for(i = 0; i < max_timer; i ++)
         aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
     XGR_Flip();
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     //i_evince_pal(iscrPal,8);
     timer = CLOCK();
     for(i = 0; i < ACI_DOOR_DELAY; i ++){
         while(CLOCK() < timer + I_TIME_DELTA){
             xtClearMessageQueue();
         }
         SlowCDTRACK();
         timer = CLOCK();
     }
     SOUND_GATE();
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < max_timer; i ++){
             timer += aScrDisp -> curLocData -> GateShutters[i] -> Quant();
             SlowCDTRACK();
         }
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < max_timer; i ++)
             aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
         //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         XGR_Flip();
         xtClearMessageQueue();
     }
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> freeData();
     }
     delete []fon_buf;
     StopCDTRACK();
     XGR_MouseShow();
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, ACI_DOOR_DELAY, aciAutoSave(), aciML_D, aScrDisp, CLOCK, flush(), i_evince_pal(), i_get_scrfon(), i_put_scrfon(), I_TIME_DELTA, iscrPal, Redraw, SlowCDTRACK(), SOUND_GATE, StopCDTRACK(), XGR_Flip, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, XGR_SetPal, and xtClearMessageQueue().
Referenced by FirstEscaveRTO::Init(), and EscaveRTO::Init().
aciShowLocationPicture()
void aciShowLocationPicture (void)
 {
     int i,max_timer = 0;
     max_timer = aScrDisp -> curLocData -> numGateShutters;
     if(!max_timer)
         return;
     if(XGR_MouseVisible())
         XGR_MouseHide();
     XGR_Fill(0);
     for(i = 0; i < max_timer; i ++){
         aScrDisp -> curLocData -> GateShutters[i] -> loadData();
         aScrDisp -> curLocData -> GateShutters[i] -> prepare(ACI_SHUTTER_OPEN);
         aScrDisp -> curLocData -> GateShutters[i] -> Redraw();
     }
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     i_evince_pal(iscrPal,8);
 }
References ACI_SHUTTER_OPEN, aScrDisp, i_evince_pal(), iscrPal, Redraw, XGR_Fill, XGR_MouseHide, and XGR_MouseVisible.
Referenced by actIntDispatcher::i_init().
aciShowScMatrix()
void aciShowScMatrix (void)
 {
     _iSTORE_OFFS_;
     int i,num2,timer = 0;
     SOUND_GATE();
     iScreenObject* m_owner = NULL;
     iBitmapElement* b;
     b = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(b) m_owner = (iScreenObject*)b -> owner;
     unsigned char* fon_buf;
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
 #ifndef _ACI_NO_SHOP_ANIMATION_
     num2 = aScrDisp -> curLocData -> numMatrixShutters2;
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters2[i] -> loadData();
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
 #endif
     aci_setScMatrixBorder();
     if(m_owner){
         m_owner -> curHeightScale = 256;
         m_owner -> putfon();
         m_owner -> redraw();
     }
     put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
     if(aScrDisp -> curMatrix)
         aScrDisp -> curMatrix -> redraw();
     aScrDisp -> secondMatrix -> redraw();
     iScrDisp -> curScr -> show_avi();
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 #else
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     SOUND_GATE();
     timer = 0;
     while(timer < num2){
         timer = 0;
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> freeData();
     }
     delete[] fon_buf;
 #endif
     if(v_flag)
         XGR_MouseShow();
     _iRESTORE_OFFS_;
 }
References _iRESTORE_OFFS_, _iSTORE_OFFS_, aci_setScMatrixBorder(), ACI_SHUTTER_CLOSE, ACI_SHUTTER_OPEN, ACI_SMATRIX_BORDER_ID, aScrDisp, curMatrix, i_get_scrfon(), i_put_scrfon(), I_RES_X, I_RES_Y, iScrDisp, iScreenOffs, NULL, put_map(), Redraw, SOUND_GATE, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
Referenced by actIntDispatcher::EventQuant().
aciSwapMatrices()
void aciSwapMatrices (void)
 {
     _iSTORE_OFFS_;
     int i,max_timer,num1,num2,timer = 0;
     iScreenObject* m_owner = NULL,*m2_owner = NULL;
     iBitmapElement* b,*b1;
     b = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_MATRIX_BORDER_ID];
     b1 = (iBitmapElement*)aScrDisp -> curLocData -> objList[ACI_SMATRIX_BORDER_ID];
     if(b) m_owner = (iScreenObject*)b -> owner;
     if(b1) m2_owner = (iScreenObject*)b1 -> owner;
     unsigned char* fon_buf;
     int v_flag = XGR_MouseVisible();
     if(v_flag)
         XGR_MouseHide();
 #ifndef _ACI_NO_SHOP_ANIMATION_
     num1 = aScrDisp -> curLocData -> numMatrixShutters1;
     num2 = aScrDisp -> curLocData -> numMatrixShutters2;
     max_timer = aScrDisp -> curLocData -> numMatrixShutters1 + aScrDisp -> curLocData -> numMatrixShutters2;
     for(i = 0; i < num1; i ++){
         aScrDisp -> curLocData -> MatrixShutters1[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters1[i] -> loadData();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_CLOSE);
         aScrDisp -> curLocData -> MatrixShutters2[i] -> loadData();
     }
     fon_buf = new unsigned char[XGR_MAXX * XGR_MAXY];
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     SOUND_GATE();
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < num1; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters1[i] -> Quant();
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num1; i ++)
             aScrDisp -> curLocData -> MatrixShutters1[i] -> Redraw();
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
 #endif
     aScrDisp -> swap_matrices();
     aci_setMatrixBorder();
     aci_setScMatrixBorder();
     if(m_owner){
         m_owner -> putfon();
         m_owner -> redraw();
     }
     if(m2_owner){
         m2_owner -> curHeightScale = 0;
         m2_owner -> putfon();
         m2_owner -> redraw();
     }
     put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
     aScrDisp -> curMatrix -> redraw();
     iScrDisp -> curScr -> show_avi();
 #ifdef _ACI_NO_SHOP_ANIMATION_
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 #else
     i_get_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
     for(i = 0; i < num1; i ++){
         aScrDisp -> curLocData -> MatrixShutters1[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> prepare(ACI_SHUTTER_OPEN);
     }
     SOUND_GATE();
     timer = 0;
     while(timer < max_timer){
         timer = 0;
         for(i = 0; i < num1; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters1[i] -> Quant();
         for(i = 0; i < num2; i ++)
             timer += aScrDisp -> curLocData -> MatrixShutters2[i] -> Quant();
         i_put_scrfon(0,0,XGR_MAXX,XGR_MAXY,fon_buf);
         for(i = 0; i < num1; i ++)
             aScrDisp -> curLocData -> MatrixShutters1[i] -> Redraw();
         for(i = 0; i < num2; i ++)
             aScrDisp -> curLocData -> MatrixShutters2[i] -> Redraw();
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
     }
     for(i = 0; i < num1; i ++){
         aScrDisp -> curLocData -> MatrixShutters1[i] -> freeData();
     }
     for(i = 0; i < num2; i ++){
         aScrDisp -> curLocData -> MatrixShutters2[i] -> freeData();
     }
     delete[] fon_buf;
 #endif
     if(v_flag)
         XGR_MouseShow();
 }
References _iSTORE_OFFS_, ACI_MATRIX_BORDER_ID, aci_setMatrixBorder(), aci_setScMatrixBorder(), ACI_SHUTTER_CLOSE, ACI_SHUTTER_OPEN, ACI_SMATRIX_BORDER_ID, aScrDisp, curMatrix, i_get_scrfon(), i_put_scrfon(), I_RES_X, I_RES_Y, iScrDisp, iScreenOffs, NULL, put_map(), Redraw, SOUND_GATE, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseShow, XGR_MouseVisible, and xtClearMessageQueue().
Referenced by actIntDispatcher::EventQuant().
aciVMapPrepare()
void aciVMapPrepare (void)
 {
     aScrDisp -> curLocData -> init_map_data();
 }
References aScrDisp.
Referenced by iSecondInit().
acsHandleExtEvent()
void acsHandleExtEvent (int code, int data0 = 0, int data1 = 0, int data2 = 0)
 {
     int val,max_val,i_val,i_max_val;
     switch(code){
         case ACS_GLOBAL_EXIT:
             if(!(aScrDisp -> flags & AS_ISCREEN))
                 GameQuantReturnValue = RTO_LOADING3_ID;
             else {
                 iScrDisp -> flags |= SD_EXIT;
                 iScrExitCode = 1;
                 iAbortGameFlag = 1;
             }
             if(NetworkON) iMultiFlag = 1;
             acsScrD -> QuantCode = 1; // resume game pause
             if(!GameOverID)
                 GameOverID = GAME_OVER_ABORT;
             break;
         case ACS_INIT_TUTORIAL_MODE:
             acsSetStrState(ACS_TUTORIAL_MODE,!iGetOptionValue(iTUTORIAL_ON));
             break;
         case ACS_SET_TUTORIAL_MODE:
             iSetOptionValue(iTUTORIAL_ON,!acsGetStrState(ACS_TUTORIAL_MODE));
             iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
             break;
         case ACS_SET_AUTORUN_MODE:
             aciAutoRun = acsGetStrState(ACS_AUTORUN_MODE);
             iScrOpt[iAUTO_ACCELERATION]->SetValueINT(acsGetStrState(ACS_AUTORUN_MODE));
             break;
         case ACS_SET_SOUND_MODE:
             iSetOptionValue(iSOUND_ON,!acsGetStrState(ACS_SOUND_MODE));
             iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
             break;
         case ACS_SET_MUSIC_MODE:
             iSetOptionValue(iMUSIC_ON,!acsGetStrState(ACS_MUSIC_MODE));
             iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
             break;
         case ACS_INIT_AUTORUN_MODE:
 //          acsSetStrState(ACS_AUTORUN_MODE,aciAutoRun);
             aciAutoRun = iGetOptionValue(iAUTO_ACCELERATION);
             acsSetStrState(ACS_AUTORUN_MODE,iGetOptionValue(iAUTO_ACCELERATION));
             break;
         case ACS_INIT_SOUND_MODE:
             acsSetStrState(ACS_SOUND_MODE,!iGetOptionValue(iSOUND_ON));
             break;
         case ACS_INIT_SOUND_VOLUME:
             acsScrD -> SetScroller(ACS_SOUND_VOLUME,iGetOptionValue(iSOUND_VOLUME_CUR),iGetOptionValue(iSOUND_VOLUME_MAX));
             break;
         case ACS_SET_SOUND_VOLUME:
             val = acsScrD -> GetObjectValue(ACS_SOUND_VOLUME);
             max_val = acsScrD -> GetObjectValue(ACS_SOUND_VOLUME,1);
             i_max_val = iGetOptionValue(iSOUND_VOLUME_MAX);
             i_val = (val * i_max_val) / max_val;
             iSetOptionValue(iSOUND_VOLUME_CUR,i_val);
             iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
             break;
         case ACS_INIT_MUSIC_MODE:
             acsSetStrState(ACS_MUSIC_MODE,!iGetOptionValue(iMUSIC_ON));
             break;
         case ACS_INIT_MUSIC_VOLUME:
             acsScrD -> SetScroller(ACS_MUSIC_VOLUME,iGetOptionValue(iMUSIC_VOLUME_CUR),iGetOptionValue(iMUSIC_VOLUME_MAX));
             break;
         case ACS_SET_MUSIC_VOLUME:
             val = acsScrD -> GetObjectValue(ACS_MUSIC_VOLUME);
             max_val = acsScrD -> GetObjectValue(ACS_MUSIC_VOLUME,1);
             i_max_val = iGetOptionValue(iMUSIC_VOLUME_MAX);
             i_val = (val * i_max_val) / max_val;
             iSetOptionValue(iMUSIC_VOLUME_CUR,i_val);
             iHandleExtEvent(iEXT_UPDATE_MUSIC_VOLUME);
             break;
         case ACS_CHANGE_MUSIC_MODE:
             acsChangeStrState(ACS_MUSIC_MODE);
             iSetOptionValue(iMUSIC_ON,!acsGetStrState(ACS_MUSIC_MODE));
             iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
             break;
         case ACS_CHANGE_AUTORUN_MODE:
             acsChangeStrState(ACS_AUTORUN_MODE);
             aciAutoRun = acsGetStrState(ACS_AUTORUN_MODE);
             iScrOpt[iAUTO_ACCELERATION]->SetValueINT(acsGetStrState(ACS_AUTORUN_MODE));
             break;
         case ACS_CHANGE_SOUND_MODE:
             acsChangeStrState(ACS_SOUND_MODE);
             iSetOptionValue(iSOUND_ON,!acsGetStrState(ACS_SOUND_MODE));
             iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
             break;
         case ACS_CHANGE_TUTORIAL_MODE:
             acsChangeStrState(ACS_TUTORIAL_MODE);
             iSetOptionValue(iTUTORIAL_ON,!acsGetStrState(ACS_TUTORIAL_MODE));
             iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
             break;
         case ACS_INIT_SLOT_NAME:
             acsPrepareSlotName(data0,data1);
             break;
         case ACS_INIT_SLOT_NAME_INPUT:
             acsPrepareSlotNameInput(data0,data1);
             break;
         case ACS_SAVE_GAME:
             acsSaveData();
             break;
     }
 }
References ACS_GLOBAL_EXIT, and aScrDisp.
acsQuant()
int acsQuant (void)
 {
     int ret,k,firstQuant = 0;
     if(!acsAllocFlag){
         acsAllocFlag = 1;
         if(NetworkON) aciKeyboardLocked = 1;
         acsScrD -> curScrID = acsScreenID;
         acsScrD -> QuantCode = 0;
         XGR_MouseObj.DisablePrompt();
         XGR_MouseShow();
         acsScrD -> alloc_mem();
         if(XGR_MAXX == 800 && !(aScrDisp -> flags & AS_ISCREEN))
             acsScrD -> curScr -> ChangeCoords((800 - 640)/2,(600 - 480)/2);
         EffectsOff();
         firstQuant = 1;
         if(acsScrD -> curScrID >= 3){
             aciCloseGate();
             acsScrD -> Quant(0);
             aciOpenGate();
         }
         KeyBuf -> clear();
     }
     while(KeyBuf->size){
         SDL_Event *e = KeyBuf->get();
         if (e->type == SDL_KEYDOWN) {
             k = sdlEventToCode(e);
         }
         if (e->type == SDL_KEYDOWN || e->type == SDL_TEXTINPUT) {
             acsScrD->KeyTrap(0, e);
             if (e->key.keysym.scancode == SDL_SCANCODE_ESCAPE && !acsScrD -> QuantCode) {
                 acsScrD -> QuantCode = 1;
             }
         }
     }
     if(aScrDisp -> flags & aMS_MOVED){
         acsScrD -> KeyTrap(iMOUSE_MOVE_CODE, nullptr);
         aScrDisp -> flags ^= aMS_MOVED;
         if(aciMouseFlagL){
             acsScrD -> KeyTrap(iMOUSE_LEFT_MOVE, nullptr);
         }
         if(aciMouseFlagR){
             acsScrD -> KeyTrap(iMOUSE_RIGHT_MOVE, nullptr);
         }
     }
     if(aScrDisp -> flags & aMS_LEFT_PRESS){
         acsScrD -> KeyTrap(iMOUSE_LEFT_PRESS_CODE, nullptr);
         aScrDisp -> flags ^= aMS_LEFT_PRESS;
     }
     if(aScrDisp -> flags & aMS_RIGHT_PRESS){
         acsScrD -> KeyTrap(iMOUSE_RIGHT_PRESS_CODE, nullptr);
         aScrDisp -> flags ^= aMS_RIGHT_PRESS;
     }
     if(NetworkON){
         acsScrD -> flags |= ACS_FORCED_REDRAW;
         ret = acsScrD -> Quant(actIntLog);
     }
     else
         ret = acsScrD -> Quant();
     if(firstQuant){
         acsPrepareSlotNameInput(acsCurrentSlotID,acsCurrentSlotNum);
         acsScrD -> PrepareInput(acsCurrentSlotID);
     }
     if(ret){
         acsAllocFlag = 0;
         if(XGR_MAXX == 800 && !(aScrDisp -> flags & AS_ISCREEN))
             acsScrD -> curScr -> ChangeCoords(-(800 - 640)/2,-(600 - 480)/2);
         acsScrD -> free_mem();
         if(aScrDisp -> flags & AS_FULLSCR && !(aScrDisp -> flags & AS_ISCREEN)){
             XGR_MouseHide();
         }
         else
             aScrDisp -> flags &= ~AS_FULL_REDRAW;
         iScrDisp -> flags &= ~MS_LEFT_PRESS;
         iScrDisp -> flags &= ~MS_RIGHT_PRESS;
         iScrDisp -> flags &= ~MS_MOVED;
         iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
         iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
         iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
         if(NetworkON) aciKeyboardLocked = 0;
         acsScreenID = 1;
         iSaveData();
         KeyBuf -> clear();
         return 1;
     }
     return 0;
 }
References aciKeyboardLocked, acsAllocFlag, acsScrD, acsScreenID, aScrDisp, XGR_Mouse::DisablePrompt(), NetworkON, XGR_MAXX, XGR_MouseObj, and XGR_MouseShow.
aLoadFonts32()
void aLoadFonts32 (void)
 {
     int i;
     XBuffer XBuf;
     XStream fh;
     if(!aScrFonts32)
         aScrFonts32 = new aciFont*[AS_NUM_FONTS_32];
     for(i = 0; i < AS_NUM_FONTS_32; i ++){
         XBuf.init();
         XBuf < "resource/actint/fonts/cfont";
         if(i < 10)
             XBuf < "0";
         XBuf <= i < ".bml";
         aScrFonts32[i] = new aciFont;
         aScrFonts32[i] -> flags |= ACI_RANGE_FONT;
         aScrFonts32[i] -> load(XBuf.GetBuf());
         aScrFonts32[i] -> calc_offs();
     }
     XGR_SetTextOutFnc(aOutText32);
     XGR_SetTextXFnc(aTextWidth32);
     XGR_SetTextYFnc(aTextHeight32);
 }
References AS_NUM_FONTS_32, aScrFonts32, and XBuffer::init().
Referenced by iInit(), and MainMenuRTO::Init().
aMS_LeftPress()
void aMS_LeftPress (int , int , int)
 {
     if (aScrDisp==NULL) {
         return;
     }
     aScrDisp -> flags |= aMS_LEFT_PRESS;
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagL = 1;
     XGR_MouseSetSeq(0,1,XGM_PLAY_ONCE,1);
 }
References aScrDisp, and NULL.
Referenced by aMS_init().
aMS_LeftUnpress()
void aMS_LeftUnpress (int , int , int)
 {
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagL = 0;
     XGR_MouseSetSeq(XGR_MouseCurFrame,XGR_MouseNumFrames - 1,XGM_PLAY_ONCE,1);
 }
References aciMouseFlagL, iMouseX, iMouseY, XGM_PLAY_ONCE, XGR_MouseCurFrame, XGR_MouseNumFrames, and XGR_MouseSetSeq.
Referenced by aMS_init(), and iMS_LeftUnpress().
aMS_Movement()
void aMS_Movement (int , int , int)
 {
     if (aScrDisp==NULL) {
         return;
     }
     aScrDisp -> flags |= aMS_MOVED;
     iMouseX = x;
     iMouseY = y;
 }
References aScrDisp, and NULL.
Referenced by aMS_init().
aMS_RightPress()
void aMS_RightPress (int , int , int)
 {
     if (aScrDisp==NULL) {
         return;
     }
     aScrDisp -> flags |= aMS_RIGHT_PRESS;
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagR = 1;
     XGR_MouseSetSeq(0,1,XGM_PLAY_ONCE,1);
 }
References aScrDisp, and NULL.
Referenced by aMS_init().
aMS_RightUnpress()
void aMS_RightUnpress (int , int , int)
 {
     iMouseX = x;
     iMouseY = y;
     aciMouseFlagR = 0;
     XGR_MouseSetSeq(XGR_MouseCurFrame,XGR_MouseNumFrames - 1,XGM_PLAY_ONCE,1);
 }
References aciMouseFlagR, iMouseX, iMouseY, XGM_PLAY_ONCE, XGR_MouseCurFrame, XGR_MouseNumFrames, and XGR_MouseSetSeq.
Referenced by aMS_init(), and iMS_RightUnpress().
EffectsOff()
void EffectsOff (void)
 {
     if(EffectInUsePriory && EffectInUse){
         for(int i = 0;i < 16;i++) SoundStop(i);
         EffectInUse = 0;
         lastSoundFlag = 0;
         //SoundVolumeCD = -1;
     }
 }
Referenced by iHandleExtEvent().
free_hfonts()
void free_hfonts (void)
 {
     int i;
     for(i = 0; i < iNumFonts; i ++)
         delete HFntTable[i];
     delete[] HFntTable;
     HFntTable = NULL;
 }
References HFntTable, iNumFonts, and NULL.
Referenced by iFinitQuant().
get_buf()
void get_buf (int x, int y, int sx, int sy, uchar * buf)
 {
     int i,j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     int vy,xx;
     for(j = 0; j < sy; j ++){
         vy = iYCYCL(y + j);
         for(i = 0; i < sx; i ++){
             xx = iXCYCL(x + i);
             buf[index] = *(lta[vy] + xx);
             index ++;
         }
     }
 }
get_col_buf()
void get_col_buf (int x, int y, int sx, int sy, uchar * buf)
 {
     int i,j,index = 0;
     unsigned char** ltc = ivMap -> lineTcolor;
     int vy,xx;
     for(j = 0; j < sy; j ++){
         vy = iYCYCL(y + j);
         for(i = 0; i < sx; i ++){
             xx = iXCYCL(x + i);
             buf[index] = *(ltc[vy] + xx);
             index ++;
         }
     }
 }
References ivMap, iXCYCL, and iYCYCL.
get_fon()
void get_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int i,j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     int yy,xx;
     for(j = 0; j < sy; j ++){
         yy = iYCYCL(y + j);
         for(i = 0; i < sx; i ++){
             xx = iXCYCL(x + i);
             buf[index + i] = lta[yy][xx];
         }
         index += sx;
     }
 }
GetKeepSpace()
int GetKeepSpace (void)
 {
     PrmFile pFile;
     pFile.init(mapFName);
     int maxWorld = atoi(pFile.getAtom());
     if(maxWorld < 1) ErrH.Abort("Empty world list");
     int i;
     char* atom;
     char* buf = new char[256];
     XStream ff(0);
     int size = 0;
     for(i = 0;i < maxWorld;i++){
         atom = pFile.getAtom();
         atom = pFile.getAtom();
         if(!atom) ErrH.Abort("Null world path");
         GetTargetName(NULL);
         strcpy(buf,GetTargetName(atom));
         dictionary *dict_name = iniparser_load(buf);
         strcpy(buf,iniparser_getstring(dict_name,"Storage:File Name", NULL));
         iniparser_freedict(dict_name);
         strcat(buf,".vmt");
         if(ff.open(GetTargetName(buf))){
             size += ff.size();
             ff.close();
             }
         }
     delete[] buf;
     pFile.finit();
     GetTargetName(NULL);
     return size/1024/1024;
 }
References XErrorHandler::Abort(), XStream::close(), ErrH, PrmFile::finit(), PrmFile::getAtom(), GetTargetName(), iniparser_freedict(), iniparser_getstring(), iniparser_load(), PrmFile::init(), mapFName, NULL, XStream::open(), and XStream::size().
Referenced by iInitKeepOptions().
getWID()
int getWID (void)
 {
     return aScrDisp -> wMap -> world_ptr[aScrDisp -> curLocData -> WorldID] -> uvsID;
 }
References aScrDisp, and wMap.
Referenced by StartWTRACK(), and ToolzerQuant().
i_change_res()
void i_change_res (void)
 {
     int emode = ExclusiveLog ? XGR_EXCLUSIVE : 0;
     /*if(actintLowResFlag){
         if(XGR_ReInit(640,480,emode)) ErrH.Abort("Error video initialization");
     }*/
     XGR_Flip();
     set_mouse();
 }
References emode, ExclusiveLog, set_mouse(), XGR_EXCLUSIVE, and XGR_Flip.
Referenced by LoadingRTO2::Init(), and iScrQuantFinit().
i_evince_pal()
void i_evince_pal (unsigned char * p, int delta)
 {
     int i,col,scale = 0;
     unsigned char* buf = new unsigned char[768];
     while(scale < 256){
         for(i = 0; i < 768; i ++){
             col = p[i];
             buf[i] = (col * scale) >> 8;
         }
         XGR_SetPal(buf,0,255);
         SDL_Delay(10);
         scale += delta;
     }
     XGR_SetPal(p,0,255);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     delete[] buf;
 }
References XGR_SetPal.
Referenced by aciShowLocation(), aciShowLocationPicture(), actIntDispatcher::flush(), and actIntDispatcher::pal_flush().
i_get_scrfon()
void i_get_scrfon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int i,index,s_index;
     unsigned char* p = (unsigned char*)XGR_VIDEOBUF;
     index = 0;
     s_index = x + y * XGR_MAXX;
     for(i = 0; i < sy; i ++){
         memcpy(buf + index,p + s_index,sx);
         index += sx;
         s_index += XGR_MAXX;
     }
 }
References XGR_MAXX, and XGR_VIDEOBUF.
Referenced by aciCancelMatrix(), aciCloseGate(), aciHideLocation(), aciOpenGate(), aciShowLocation(), aciShowScMatrix(), and aciSwapMatrices().
i_getpal()
void i_getpal (unsigned char * p)
 {
     XGR_GetPal(p);
 }
References XGR_GetPal.
Referenced by i_slake_pal(), and iScrQuantFinit().
i_mem_putspr()
void i_mem_putspr (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int i,j,_x,_y,_x1,_y1,_sx,_sy,dx = 0,dy = 0;
     unsigned char* scrBuf,*memBuf;
     _x = (x > 0) ? x : 0;
     _y = (y > 0) ? y : 0;
     dx = _x - x;
     dy = _y - y;
     _x1 = (x + sx < XGR_MAXX) ? (x + sx) : XGR_MAXX;
     _y1 = (y + sy < XGR_MAXY) ? (y + sy) : XGR_MAXY;
     _sx = _x1 - _x;
     _sy = _y1 - _y;
     if(_sx <= 0 || _sy <= 0) return;
     scrBuf = (unsigned char*)XGR_VIDEOBUF + _y * XGR_MAXX + _x;
     memBuf = ptr + dy * sx + dx;
     for(i = 0; i < _sy; i ++){
         for(j = 0; j < _sx; j ++){
             if(memBuf[j]){
                 scrBuf[j] = memBuf[j];
             }
         }
         scrBuf += XGR_MAXX;
         memBuf += sx;
     }
 }
References XGR_MAXX, XGR_MAXY, and XGR_VIDEOBUF.
i_postExtQuant()
void i_postExtQuant (void)
 {
 }
i_preExtQuant()
void i_preExtQuant (void)
 {
     iScreen* scr;
     iScreen* scrTmp;
     switch(CurEvComm -> EvType){
         case EV_EXT_SCREEN_JUMP:
             if(!strcmp(CurEvComm -> pvalue,"ExtScreen00")){
                 scr = iScrDisp -> get_ext_screen("ExtScreen00");
                 if(!scr){
                     scrTmp = (iScreen*)iScrDisp -> get_object("Test template");
                     scr = iCreateScreen("ExtScreen00",scrTmp);
                     scr -> init();
                     iScrDisp -> add_ext_screen(scr);
                 }
             }
             if(!strcmp(CurEvComm -> pvalue,"ExtScreen01")){
                 scr = iScrDisp -> get_ext_screen("ExtScreen01");
                 if(!scr){
                     scr = create_screen();
                     scr -> init();
                     iScrDisp -> add_ext_screen(scr);
                 }
             }
             break;
     }
 }
i_put_scrfon()
void i_put_scrfon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int i,index,s_index;
     unsigned char* p = (unsigned char*)XGR_VIDEOBUF;
     index = 0;
     s_index = x + y * XGR_MAXX;
     for(i = 0; i < sy; i ++){
         memcpy(p + s_index,buf + index,sx);
         index += sx;
         s_index += XGR_MAXX;
     }
 }
References XGR_MAXX, and XGR_VIDEOBUF.
Referenced by aciCancelMatrix(), aciCloseGate(), aciHideLocation(), aciOpenGate(), aciShowLocation(), aciShowScMatrix(), and aciSwapMatrices().
i_slake_pal()
void i_slake_pal (unsigned char * p, int delta)
 {
     int i,col,scale = 256;
     unsigned char* buf = new unsigned char[768];
     i_getpal(p);
     while(scale > 0){
         for(i = 0; i < 768; i ++){
             col = p[i];
             buf[i] = (col * scale) >> 8;
         }
         XGR_SetPal(buf,0,255);
         SDL_Delay(10);
         scale -= delta;
     }
     memset(buf,0,768);
     XGR_SetPal(buf,0,255);
     XGR_Fill(0);
     //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     delete[] buf;
 }
References i_getpal(), XGR_Fill, and XGR_SetPal.
Referenced by ShowImageRTO::Finit(), actIntDispatcher::flush(), actIntDispatcher::i_init(), iScrQuantFinit(), and MainMenuRTO::Quant().
iBlockJoystickOption()
void iBlockJoystickOption (int mode)
 {
     iScreenObject* obj = (iScreenObject*)iGetObject("Controls screen2","Joystick Option");
     if(obj){
         if(mode)
             obj -> flags &= ~OBJ_LOCKED;
         else
             obj -> flags |= OBJ_LOCKED;
     }
 }
References iGetObject().
Referenced by iHandleExtEvent().
iChatFinit()
void iChatFinit (void)
 {
     iChatButton* p,*p1;
     if(iChatButtons){
         p = (iChatButton*)iChatButtons -> fPtr;
         while(p){
             p1 = (iChatButton*)p -> next;
             delete p;
             p = p1;
         }
         delete iChatButtons;
     }
     if(iChatHistory)
         delete iChatHistory;
     if(iChatInput)
         delete iChatInput;
     iChatON = iScreenChat = 0;
     aciKeyboardLocked = 0;
     iChatHistory = NULL;
     iChatInput = NULL;
     iChatButtons = NULL;
     SDL_StopTextInput();
 }
iChatInit()
void iChatInit (void)
 {
     int x,y,sx,sy,bsx,col0,col1,bcol;
     iChatButton* p;
     sx = ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X;
     sy = ICS_HISTORY_SIZE_Y + ICS_DELTA * 2 + ICS_BUTTON_SIZE_Y * 2;
 //    bsx = (sx - ICS_DELTA * 2) / 3;
     bsx = (ICS_HISTORY_SIZE_X - ICS_DELTA * 2) / 3;
     x = (XGR_MAXX - sx) / 2;
     y = (XGR_MAXY - sy) / 2;
     if(!iScreenChat)
         bcol = ICS_BORDER_COLOR;
     else {
         y -= 30;
         bcol = ICS_iBORDER_COLOR;
     }
     iChatButtons = new XList;
     iChatHistory = new iChatHistoryScreen;
     iChatHistory -> init(x,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_HISTORY_SIZE_X,ICS_HISTORY_SIZE_Y,bcol,bcol);
     iChatInput = new iChatInputField;
     iChatInput -> init(x,y + ICS_HISTORY_SIZE_Y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_HISTORY_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     strcpy(iChatInput -> string,">_");
     p = new iChatButton(2);
     p -> init(x,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_MUTE_BUTTON;
     p -> set_string(iSTR_MUTE_ALL);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p -> CurState = iChatMUTE;
     p = new iChatButton(1);
     p -> init(x + bsx + ICS_DELTA,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_CLEAR_BUTTON;
     p -> set_string(iSTR_CLEAR_LOG);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     iChatButtons -> AddElement((XListElement*)p);
     iChatBackLog = 1;
     if(!iScreenChat){
         p = new iChatButton(2);
         p -> init(x + (bsx + ICS_DELTA) * 3,y,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
         p -> ID = ICS_BACK_BUTTON;
         p -> set_string(iSTR_BACKGROUND);
         if(!iScreenChat){
             col0 = ICS_STRING_COL0;
             col1 = ICS_STRING_COL1;
         }
         else {
             col0 = ICS_iSTRING_COL0;
             col1 = ICS_iSTRING_COL1;
         }
         p -> set_color(0,col0);
         p -> set_color(1,col1);
         p -> CurState = 1;
         iChatButtons -> AddElement((XListElement*)p);
     }
 //    else {
 //        iChatBackLog = 0;
 //    }
     if(!iScreenChat){
         p = new iChatButton(1);
         p -> init(x + bsx * 2 + ICS_DELTA * 2,y,bsx,ICS_BUTTON_SIZE_Y,bcol,bcol);
         p -> ID = ICS_EXIT_BUTTON;
         p -> set_string(iSTR_LEAVE_CHAT);
         col0 = ICS_STRING_COL0;
         p -> set_color(0,col0);
         iChatButtons -> AddElement((XListElement*)p);
     }
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 1,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_ALL_BUTTON;
     p -> set_string(iSTR_All);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 2,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_YELLOW_BUTTON;
     p -> set_string(iSTR_Yellow);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 3,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_ORANGE_BUTTON;
     p -> set_string(iSTR_Orange);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 4,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_BLUE_BUTTON;
     p -> set_string(iSTR_Blue);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 5,ICS_BUTTON_SIZE_X/2 -1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_GREEN_BUTTON;
     p -> set_string(iSTR_Green);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 6,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_RED_BUTTON;
     p -> set_string(iSTR_Red);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 2,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_WHITE_BUTTON;
     p -> set_string(iSTR_White);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 3,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_GRAY_BUTTON;
     p -> set_string(iSTR_Gray);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 4,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_BLACK_BUTTON;
     p -> set_string(iSTR_Black);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 5,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_CAMOUFLAGE_BUTTON;
     p -> set_string(iSTR_Camouflage);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/2 + 1,y + ICS_DELTA + (ICS_BUTTON_SIZE_Y + ICS_DELTA/5) * 6,ICS_BUTTON_SIZE_X/2 - 1,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PATROL_BUTTON;
     p -> set_string(iSTR_Patrol);
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/4,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 6,ICS_BUTTON_SIZE_X/2,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_UP_BUTTON;
     p -> set_string("\x1E");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 7,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER1_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 8,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER2_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 9,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER3_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 10,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER4_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 11,ICS_BUTTON_SIZE_X,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_PLAYER5_BUTTON;
     p -> set_string("123456789012345 (F/B)");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     p = new iChatButton(2);
     p -> init(x + ICS_HISTORY_SIZE_X + ICS_DELTA + ICS_BUTTON_SIZE_X/4,y + (ICS_BUTTON_SIZE_Y + ICS_DELTA) * 12,ICS_BUTTON_SIZE_X/2,ICS_BUTTON_SIZE_Y,bcol,bcol);
     p -> ID = ICS_DN_BUTTON;
     p -> set_string("\x1F");
     if(!iScreenChat){
         col0 = ICS_STRING_COL0;
         col1 = ICS_STRING_COL1;
     }
     else {
         col0 = ICS_iSTRING_COL0;
         col1 = ICS_iSTRING_COL1;
     }
     p -> set_color(0,col0);
     p -> set_color(1,col1);
     iChatButtons -> AddElement((XListElement*)p);
     iChatExit = 0;
     iChatON = 1;
     aciKeyboardLocked = 1;
     XGR_MouseShow();
     iInitChatScreen();
     SDL_StartTextInput();
 }
References aciKeyboardLocked, iChatBackLog, iChatButtons, iChatExit, iChatHistory, iChatInput, iChatMUTE, iChatON, ICS_ALL_BUTTON, ICS_BACK_BUTTON, ICS_BLACK_BUTTON, ICS_BLUE_BUTTON, ICS_BORDER_COLOR, ICS_BUTTON_SIZE_X, ICS_BUTTON_SIZE_Y, ICS_CAMOUFLAGE_BUTTON, ICS_CLEAR_BUTTON, ICS_DELTA, ICS_DN_BUTTON, ICS_EXIT_BUTTON, ICS_GRAY_BUTTON, ICS_GREEN_BUTTON, ICS_HISTORY_SIZE_X, ICS_HISTORY_SIZE_Y, ICS_iBORDER_COLOR, ICS_iSTRING_COL0, ICS_iSTRING_COL1, ICS_MUTE_BUTTON, ICS_ORANGE_BUTTON, ICS_PATROL_BUTTON, ICS_PLAYER1_BUTTON, ICS_PLAYER2_BUTTON, ICS_PLAYER3_BUTTON, ICS_PLAYER4_BUTTON, ICS_PLAYER5_BUTTON, ICS_RED_BUTTON, ICS_STRING_COL0, ICS_STRING_COL1, ICS_UP_BUTTON, ICS_WHITE_BUTTON, ICS_YELLOW_BUTTON, iInitChatScreen(), iScreenChat, iSTR_All, iSTR_BACKGROUND, iSTR_Black, iSTR_Blue, iSTR_Camouflage, iSTR_CLEAR_LOG, iSTR_Gray, iSTR_Green, iSTR_LEAVE_CHAT, iSTR_MUTE_ALL, iSTR_Orange, iSTR_Patrol, iSTR_Red, iSTR_White, iSTR_Yellow, XGR_MAXX, XGR_MAXY, and XGR_MouseShow.
iChatKeyQuant()
void iChatKeyQuant (SDL_Event * k)
{
     if (k->type == SDL_TEXTINPUT) {
         return iChatInputChar(k);
     }
     if (k->type != SDL_KEYDOWN) {
         iChatExit = 1;
         return;
     }
     if(iCheckKeyID(iKEY_CHAT, k->key.keysym.scancode))
         iChatExit = 1;
     switch(k->key.keysym.scancode) {
         case SDL_SCANCODE_ESCAPE:
             iChatExit = 1;
             break;
         case SDL_SCANCODE_RETURN:
             iChatInputFlush();
             break;
         case SDL_SCANCODE_BACKSPACE:
         case SDL_SCANCODE_LEFT:
             iChatInputBack();
             break;
         default:
             if(k) {
                 iChatInputChar(k);
             }
             break;
     }
 }
References iChatExit, iChatInputBack(), iChatInputChar(), iChatInputFlush(), iCheckKeyID(), and iKEY_CHAT.
iChatMouseQuant()
void iChatMouseQuant (int x, int y, int bt)
 {
     iChatButton* p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         if(p -> check_xy(x,y)) iChatMouseHandler(p,bt);
         p = (iChatButton*)p -> next;
     }
 }
References iChatButtons, and iChatMouseHandler().
iChatQuant()
void iChatQuant (int flush = 0)
 {
     int sz;
     iChatButton* p;
     if(!iChatON) return;
 //    if(iScreenChat) put_map(iScreenOffs,0,XGR_MAXX,XGR_MAXY);
     iInitChatScreen();
     p = (iChatButton*)iChatButtons -> fPtr;
     while(p){
         if(!(p -> flags & ICS_HIDDEN_OBJECT)) p -> redraw();
         p = (iChatButton*)p -> next;
     }
     iChatCursorTimer ++;
     if(iChatCursorTimer >= ICS_INPUT_TIMER){
         iChatCursorTimer = 0;
         iChatCursorFlag = 1;
     }
     if(iChatCursorFlag){
         sz = strlen(iChatInput -> string);
         if(iChatInput -> string[sz - 1] == '_')
             iChatInput -> string[sz - 1] = ' ';
         else
             iChatInput -> string[sz - 1] = '_';
         iChatCursorFlag = 0;
     }
     iChatInput -> redraw();
     iChatHistory -> redraw();
     if(flush){
         p = (iChatButton*)iChatButtons -> fPtr;
         while(p){
             if(!(p -> flags & ICS_HIDDEN_OBJECT)) p -> flush();
             p = (iChatButton*)p -> next;
         }
         iChatInput -> flush();
         iChatHistory -> flush();
     }
 }
References iChatButtons, iChatON, and iInitChatScreen().
iConnect2Server()
void iConnect2Server (void)
 {
     int i;
     ServerFindChain* p = iFirstServerPtr;
     for(i = 0; i < iCurServer; i ++){
         p = p -> next;
     }
     if(!p)
         iEvLineID = 1;
     else {
         if(NetInit(p))
             iEvLineID = 2;
         else
             iEvLineID = 1;
     }
 }
References iCurServer, and iFirstServerPtr.
iCreateEventCommand()
iScreenEventCommand* iCreateEventCommand (iScreenEventCommand * tpl)
 {
     iScreenEventCommand* p = new iScreenEventCommand;
     if(tpl)
         tpl -> copy(p);
     return p;
 }
Referenced by create_screen().
iCreateScreen()
iScreen* iCreateScreen (const char * id, iScreen * tpl)
 {
     iScreen* p = new iScreen;
     p -> init_id(id);
     if(tpl)
         tpl -> copy(p);
     return p;
 }
Referenced by create_screen(), and i_preExtQuant().
iCreateScreenElement()
iScreenElement* iCreateScreenElement (int tp, const char * id, iScreenElement * tpl)
 {
     iScreenElement* p = NULL;
     iStringElement* str;
     iBitmapElement* bmp;
     iScrollerElement* scr;
     iTerrainElement* tr;
     iS_StringElement* sstr;
     iAVIElement* avi;
     iAVIBorderElement* avi_b;
     switch(tp){
         case I_STRING_ELEM:
             str = new iStringElement;
             p = (iScreenElement*)str;
             break;
         case I_BITMAP_ELEM:
             bmp = new iBitmapElement;
             p = (iScreenElement*)bmp;
             break;
         case I_SCROLLER_ELEM:
             scr = new iScrollerElement;
             p = (iScreenElement*)scr;
             break;
         case I_TERRAIN_ELEM:
             tr = new iTerrainElement;
             p = (iScreenElement*)tr;
             break;
         case I_S_STRING_ELEM:
             sstr = new iS_StringElement;
             p = (iScreenElement*)sstr;
             break;
         case I_AVI_ELEM:
             avi = new iAVIElement;
             p = (iScreenElement*)avi;
             break;
         case I_AVI_BORDER_ELEM:
             avi_b = new iAVIBorderElement;
             p = (iScreenElement*)avi_b;
             break;
     }
     if(!p)
         ErrH.Abort("Error creating element...");
     if(id)
         p -> init_id(id);
     if(tpl)
         tpl -> copy(p);
     return p;
 }
References XErrorHandler::Abort(), ErrH, I_AVI_BORDER_ELEM, I_AVI_ELEM, I_BITMAP_ELEM, I_S_STRING_ELEM, I_SCROLLER_ELEM, I_STRING_ELEM, I_TERRAIN_ELEM, and NULL.
Referenced by iScreenObject::copy(), and create_screen().
iCreateScreenEvent()
iScreenEvent* iCreateScreenEvent (iScreenEvent * tpl)
 {
     iScreenEvent* p = new iScreenEvent;
     if(tpl)
         tpl -> copy(p);
     return p;
 }
Referenced by create_screen().
iCreateScreenObject()
iScreenObject* iCreateScreenObject (const char * id, iScreenObject * tpl)
 {
     iTriggerObject* trg;
     iScreenObject* p;
     if(tpl && tpl -> flags & OBJ_TRIGGER){
         trg = new iTriggerObject;
         p = (iScreenObject*)trg;
     }
     else
         p = new iScreenObject;
     p -> init_id(id);
     if(tpl)
         tpl -> copy(p);
     return p;
 }
Referenced by create_screen().
iCreateServer()
void iCreateServer (void)
 {
     if(KDWIN::create_server(iServerPort)){
         iEvLineID = 2;
         iFirstServerPtr = avaible_servers.first();
         iCurServer = 0;
     }
     else {
         iEvLineID = 1;
     }
 }
References avaible_servers, KDWIN::create_server(), XTList< Type >::first(), iCurServer, iEvLineID, iFirstServerPtr, and iServerPort.
iCreateTriggerObject()
iTriggerObject* iCreateTriggerObject (const char * id, iScreenObject * tpl)
 {
     iTriggerObject* trg;
     iScreenObject* p;
     trg = new iTriggerObject;
     p = (iScreenObject*)trg;
     p -> init_id(id);
     if(tpl)
         tpl -> copy(p);
     trg -> flags |= OBJ_TRIGGER;
     return trg;
 }
Referenced by create_screen().
iDeleteControl()
void iDeleteControl (int vkey, int id)
 {
     //std::cout<<"iDeleteControl vkey:"<<vkey<<" id:"<<id<<std::endl;
     int i,j,key,index;
     iScreenObject* obj;
     for(i = 0; i < iKEY_MAX_ID; i ++){
         for(j = 0; j < iKEY_OBJECT_SIZE; j ++){
             index = i * iKEY_OBJECT_SIZE + j;
             if(index != id && iControlsStr[index]){
                 key = iGetControlCode(i,j);
                 if(key == vkey){
                     iSetControlCode(i,0,j);
                     strcpy(iControlsStr[index] -> string,iSTR_NONE);
                     obj = (iScreenObject*)iControlsStr[index] -> owner;
                     obj -> flags |= OBJ_REINIT;
                     obj -> flags |= OBJ_MUST_REDRAW;
                 }
             }
         }
     }
 }
References iControlsStr, iGetControlCode(), iKEY_MAX_ID, iKEY_OBJECT_SIZE, iSetControlCode(), iSTR_NONE, and key().
Referenced by iInitControlKey().
iDeleteControlKey()
void iDeleteControlKey (int id, int num)
 {
     //std::cout<<"iDeleteControlKey"<<std::endl;
     int index;
     iScreenObject* obj;
     iResetControlCode(id,num);
     index = id * iKEY_OBJECT_SIZE + num;
     if(iControlsStr && iControlsStr[index]){
         strcpy(iControlsStr[index] -> string,iSTR_NONE);
         obj = (iScreenObject*)iControlsStr[index] -> owner;
         obj -> flags |= OBJ_REINIT;
         obj -> flags |= OBJ_MUST_REDRAW;
     }
 }
References iControlsStr, iKEY_OBJECT_SIZE, iResetControlCode(), and iSTR_NONE.
iFinitQuant()
void iFinitQuant (void)
 {
     if(actIntLog){
         aciHideLocation();
     }
     else {
         iSaveData();
     }
 #ifdef _ACI_SKIP_MAINMENU_
     if(actIntLog){
 #endif
     free_hfonts();
     iScrDisp -> free_mem();
 #ifdef _ACI_SKIP_MAINMENU_
     }
 #endif
     ivMap -> finit();
     if(!actIntLog) iScrDisp -> finit_texts();
     XGR_MouseSetPromptData(NULL);
     XGR_MouseObj.PromptDeltaX = 0;
     XGR_MouseHide();
     iScreenActive = 0;
 //  iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
     iHandleExtEvent(iEXT_UPDATE_MUSIC_VOLUME);
 }
References aciHideLocation(), actIntLog, free_hfonts(), iEXT_UPDATE_MUSIC_VOLUME, iHandleExtEvent(), iSaveData(), iScrDisp, iScreenActive, ivMap, NULL, XGR_Mouse::PromptDeltaX, XGR_MouseHide, XGR_MouseObj, and XGR_MouseSetPromptData.
Referenced by MainMenuRTO::Finit(), and iScrQuantFinit().
iGetCurServer()
ServerFindChain * iGetCurServer (void)
 {
     int i;
     ServerFindChain* p = iFirstServerPtr;
     for(i = 0; i < iCurServer; i ++){
         p = p -> next;
     }
     return p;
 }
References iCurServer, and iFirstServerPtr.
iGetEscaveTime()
int iGetEscaveTime (void)
 {
     int value = iGetMultiGameParameter(iCurMultiGame,iMP_IN_ESCAVE_TIME);
     return (value + 1) * 1200;
 }
References iCurMultiGame, iGetMultiGameParameter(), and iMP_IN_ESCAVE_TIME.
iGetIP()
void iGetIP (void)
 {
     //Should be BigEndian in anycase
     int IP = XSocketLocalHostExternADDR.host;
     XBuffer XBuf;
     XBuf <= (IP & 0xff) < "." <= ((IP >> 8) & 0xff) < "." <= ((IP >> 16) & 0xff) < "." <= ((IP >> 24) & 0xff);
     iSetOptionValueCHR(iIP_ADDRESS,XBuf.address());
 }
References XBuffer::address(), iIP_ADDRESS, iSetOptionValueCHR(), and XSocketLocalHostExternADDR.
Referenced by iHandleExtEvent(), and iQuantFirst().
iGetMultiGameParameters()
void iGetMultiGameParameters (void)
 {
     int value;
     time_t tm;
     my_server_data.GameType = iCurMultiGame;
     switch(iCurMultiGame){
         case iMP_VAN_WAR:
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_INITIAL_CASH);
             my_server_data.Van_War.InitialCash = value;
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_ARTEFACTS_USING);
             my_server_data.Van_War.ArtefactsUsing = value;
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_IN_ESCAVE_TIME);
             my_server_data.Van_War.InEscaveTime = value;
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_TEAM_MODE);
             my_server_data.Van_War.TeamMode = value;
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_NASCENCY);
             my_server_data.Van_War.Nascency = value - 1;
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_ACCESS);
             my_server_data.Van_War.WorldAccess = value;
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_MAX_KILLS);
             my_server_data.Van_War.MaxKills = value;
             value = iGetMultiGameParameter(iMP_VAN_WAR,iMP_MAX_TIME);
             my_server_data.Van_War.MaxTime = value;
             break;
         case iMP_MECHOSOMA:
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_INITIAL_CASH);
             my_server_data.Mechosoma.InitialCash = value;
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_ARTEFACTS_USING);
             my_server_data.Mechosoma.ArtefactsUsing = value;
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_IN_ESCAVE_TIME);
             my_server_data.Mechosoma.InEscaveTime = value;
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_TEAM_MODE);
             my_server_data.Mechosoma.TeamMode = value;
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_WORLD);
             my_server_data.Mechosoma.World = value;
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_QUANTITY1);
             my_server_data.Mechosoma.ProductQuantity1 = value;
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_QUANTITY2);
             my_server_data.Mechosoma.ProductQuantity2 = value;
             value = iGetMultiGameParameter(iMP_MECHOSOMA,iMP_ONE_AT_A_TIME);
             my_server_data.Mechosoma.One_at_a_time = value;
             break;
         case iMP_PASSEMBLOSS:
             value = iGetMultiGameParameter(iMP_PASSEMBLOSS,iMP_INITIAL_CASH);
             my_server_data.Passembloss.InitialCash = value;
             value = iGetMultiGameParameter(iMP_PASSEMBLOSS,iMP_ARTEFACTS_USING);
             my_server_data.Passembloss.ArtefactsUsing = value;
             value = iGetMultiGameParameter(iMP_PASSEMBLOSS,iMP_IN_ESCAVE_TIME);
             my_server_data.Passembloss.InEscaveTime = value;
             time(&tm);
             value = iGetMultiGameParameter(iMP_PASSEMBLOSS,iMP_CHECKPOINTS_NUM);
             my_server_data.Passembloss.CheckpointsNumber = value;
             value = iGetMultiGameParameter(iMP_PASSEMBLOSS,iMP_ESCAVE);
             my_server_data.Passembloss.RandomEscave = value - 1;
 //          my_server_data.Passembloss.RandomEscave = tm % 3;
             break;
         case iMP_HUNTAGE:
             value = iGetMultiGameParameter(iMP_HUNTAGE,iMP_INITIAL_CASH);
             my_server_data.Huntage.InitialCash = value;
             value = iGetMultiGameParameter(iMP_HUNTAGE,iMP_ARTEFACTS_USING);
             my_server_data.Huntage.ArtefactsUsing = value;
             value = iGetMultiGameParameter(iMP_HUNTAGE,iMP_IN_ESCAVE_TIME);
             my_server_data.Huntage.InEscaveTime = value;
             break;
         case iMP_MUSTODONT:
             value = iGetMultiGameParameter(iMP_MUSTODONT,iMP_INITIAL_CASH);
             my_server_data.Mustodont.InitialCash = value;
             value = iGetMultiGameParameter(iMP_MUSTODONT,iMP_ARTEFACTS_USING);
             my_server_data.Mustodont.ArtefactsUsing = value;
             value = iGetMultiGameParameter(iMP_MUSTODONT,iMP_IN_ESCAVE_TIME);
             my_server_data.Mustodont.InEscaveTime = value;
             value = iGetMultiGameParameter(iMP_MUSTODONT,iMP_TEAM_MODE);
             my_server_data.Mustodont.TeamMode = value;
             break;
     }
 }
References VAN_WAR_PRM::ArtefactsUsing, MECHOSOMA_PRM::ArtefactsUsing, PASSEMBLOSS_PRM::ArtefactsUsing, HUNTAGE_PRM::ArtefactsUsing, MUSTODONT_PRM::ArtefactsUsing, PASSEMBLOSS_PRM::CheckpointsNumber, ServerData::GameType, ServerData::Huntage, iCurMultiGame, iGetMultiGameParameter(), iMP_ACCESS, iMP_ARTEFACTS_USING, iMP_CHECKPOINTS_NUM, iMP_ESCAVE, iMP_HUNTAGE, iMP_IN_ESCAVE_TIME, iMP_INITIAL_CASH, iMP_MAX_KILLS, iMP_MAX_TIME, iMP_MECHOSOMA, iMP_MUSTODONT, iMP_NASCENCY, iMP_ONE_AT_A_TIME, iMP_PASSEMBLOSS, iMP_QUANTITY1, iMP_QUANTITY2, iMP_TEAM_MODE, iMP_VAN_WAR, iMP_WORLD, VAN_WAR_PRM::InEscaveTime, MECHOSOMA_PRM::InEscaveTime, PASSEMBLOSS_PRM::InEscaveTime, HUNTAGE_PRM::InEscaveTime, MUSTODONT_PRM::InEscaveTime, VAN_WAR_PRM::InitialCash, MECHOSOMA_PRM::InitialCash, PASSEMBLOSS_PRM::InitialCash, HUNTAGE_PRM::InitialCash, MUSTODONT_PRM::InitialCash, VAN_WAR_PRM::MaxKills, VAN_WAR_PRM::MaxTime, ServerData::Mechosoma, ServerData::Mustodont, my_server_data, VAN_WAR_PRM::Nascency, MECHOSOMA_PRM::One_at_a_time, ServerData::Passembloss, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, PASSEMBLOSS_PRM::RandomEscave, VAN_WAR_PRM::TeamMode, MECHOSOMA_PRM::TeamMode, MUSTODONT_PRM::TeamMode, ServerData::Van_War, MECHOSOMA_PRM::World, and VAN_WAR_PRM::WorldAccess.
iGetObject()
iListElement* iGetObject (const char * scr, const char * obj)
 {
     iScreen* p;
     iListElement* el = NULL;
     if(scr) {
         p = (iScreen*)iScrDisp -> get_object(scr);
         el = p -> get_object(obj);
     } else {
         el = iScrDisp -> get_object(obj);
     }
     return el;
 }
References iScrDisp, and NULL.
Referenced by iBlockJoystickOption(), iInitKeepOptions(), iMultiResultString::init(), and iScreenOption::iScreenOption().
iHandleExtEvent()
void iHandleExtEvent (int code, int data)
 {
     int mode;
     switch(code){
         case iEXT_INIT_SOCKETS:
             XSocketInit();
             iGetIP();
             break;
         case iEXT_INIT_PORT:
             iServerPort = atoi(iGetOptionValueCHR(iSERVER_PORT));
             break;
         case iEXT_RESTORE_PORT:
             iSetOptionValueCHR(iSERVER_PORT,"2197");
             iServerPort = 2197;
             break;
         case iEXT_SELECT_HALL:
             iCurHall = data;
             iPrepareHallOfFame();
             break;
         case iEXT_INIT_PROXY:
             iInitProxyOptions();
             break;
         case iEXT_INIT_JOYSTICK_OBJ:
             iBlockJoystickOption(JoystickAvailable);
             break;
         case iEXT_INIT_JOYSTICK:
             JoystickMode = iGetOptionValue(iJOYSTICK_TYPE);
             JoystickStickSwitchButton = iGetControlCode(iKEY_JOYSTICK_SWITCH);
             break;
         case iEXT_UPDATE_SOUND_MODE:
             if(!iGetOptionValue(iSOUND_ON)) {
                 EffectInUsePriory = 1;
                 EffectsOn(!iScreenActive);
                 MuteLog = 0;
             } else {
                 EffectsOff();
             }
             break;
         case iEXT_UPDATE_TUTORIAL_MODE:
             if(iGetOptionValue(iTUTORIAL_ON))
                 XGR_MouseObj.DisablePrompt();
             else
                 XGR_MouseObj.EnablePrompt();
             break;
         case iEXT_UPDATE_MUSIC_MODE:
 #ifndef _NO_CDAUDIO_
 //          mode = xsGetStatusCD();
             mode = xsGetStatusMusic();
             if(!iGetOptionValue(iMUSIC_ON)){
                 MusicON = 1;
                 if(mode != XCD_PLAYING){
                     StartCDTRACK();
                 }
             }
             else {
                 if(mode == XCD_PLAYING){
                     StopCDTRACK();
                 }
                 MusicON = 0;
             }
 //          SoundVolumeCD = xsGetVolumeCD();
             SoundVolumeCD = xsGetVolumeMusic();
 #endif
             break;
         case iEXT_UPDATE_MUSIC_VOLUME:
 #ifndef _NO_CDAUDIO_
 //          xsSetVolumeCD(iGetOptionValue(iMUSIC_VOLUME_CUR)*256/iGetOptionValue(iMUSIC_VOLUME_MAX));
             xsSetVolumeMusic(iGetOptionValue(iMUSIC_VOLUME_CUR)*256/iGetOptionValue(iMUSIC_VOLUME_MAX));
 //          SoundVolumeCD = xsGetVolumeCD();
             SoundVolumeCD = xsGetVolumeMusic();
 #endif
             break;
         case iEXT_UPDATE_SOUND_VOLUME:
             if(!MuteLog && EffectInUsePriory){
                 if(!iGetOptionValue(iSOUND_ON)){
                     SetSoundVolume(iGetOptionValue(iSOUND_VOLUME_CUR)*256/iGetOptionValue(iSOUND_VOLUME_MAX));
                 }
             }
             break;
         case iEXT_PREPARE_SLOTS:
             iPrepareSaveNames();
             break;
         case iEXT_SET_SLOT:
             iSlotNumber = data;
             break;
 //      case iEXT_INIT_SERVERS_LIST:
 //          iFirstServerPtr = avaible_servers.first();
 //          iInitServersList();
 //          break;
         case iEXT_INIT_iSERVERS_LIST:
             iFirstServerPtr = avaible_servers.first();
             iInitServersList();
             break;
 //      case iEXT_UPDATE_SERVERS_LIST:
 //          iUpdateServersList();
 //          break;
         case iEXT_UPDATE_iSERVERS_LIST:
             iUpdateServersList();
             break;
 //      case iEXT_UP_SERVERS_LIST:
 //          iServersListUp();
 //          break;
         case iEXT_UP_iSERVERS_LIST:
             iServersListUp();
             break;
 //      case iEXT_DN_SERVERS_LIST:
 //          iServersListDown();
 //          break;
         case iEXT_DN_iSERVERS_LIST:
             iServersListDown();
             break;
         case iEXT_SAVE_GAME:
             if(actIntLog && !iPause && !NetworkON){
                 if(!(aScrDisp -> flags & AS_INV_MOVE_ITEM)){
                     iPause = 1;
                     acsScreenID = aScrDisp -> curLocData -> SaveScreenID;
                 }
             }
             break;
         case iEXT_CHOOSE_SERVER:
             iCurServer = data;
             break;
         case iEXT_CHECK_SERVER_CONFIG:
 //zmod fixed
             if(is_current_server_configured(iGetOptionValueCHR(iSERVER_NAME),&my_server_data, &z_my_server_data)){
                 iUpdateOptionValue(iSERVER_NAME);
                 iSetMultiGameParameters();
                 iUpdateMultiGameName();
                 iEvLineID = 3;
             }
             else {
                 iUpdateMultiGameName();
                 iEvLineID = 4;
             }
 //#ifdef ZMOD_BETA
             NetRnd.Init(my_server_data.InitialRND);
 //#endif
             break;
         case iEXT_CHECK_END_FLAG:
             if(iEndGameFlag)
                 iEvLineID = 1;
             else
                 iEvLineID = 3;
             break;
         case iEXT_CONNECT:
             iConnect2Server();
             break;
         case iEXT_FIRST_SEARCH:
             if(!iFirstServerSearch){
 //                iFirstServerSearch = 1;
                 iEvLineID = 1;
             }
             else
                 iEvLineID = 2;
             break;
         case iEXT_INIT_CONTROL:
             iInitControlKey(data & 0xFF,(data >> 8) & 0xFF);
             break;
         case iEXT_DELETE_CONTROL:
             iDeleteControlKey(data & 0xFF,(data >> 8) & 0xFF);
             break;
         case iEXT_RESET_CONTROLS:
             iResetControls();
             iInitControlObjects();
             break;
         case iEXT_UPDATE_OPTION:
             iUpdateOptionValue(data);
             break;
         case iEXT_SELECT_GAME:
             iCurMultiGame = data;
             iUpdateMultiGameName();
             break;
         case iEXT_SEND_CONFIG_DATA:
             iGetMultiGameParameters();
 //zmod fixed
             if(!send_server_data(iGetOptionValueCHR(iSERVER_NAME),&my_server_data,&z_my_server_data)){
                 iUpdateOptionValue(iSERVER_NAME);
                 iUpdateMultiGameName();
                 iSetMultiGameParameters();
                 iEvLineID = 3;
             }
             else {
                 iUpdateOptionValue(iSERVER_NAME);
                 iUpdateMultiGameName();
                 iEvLineID = 4;
             }
 //#ifdef ZMOD_BETA
             NetRnd.Init(my_server_data.InitialRND);
 //#endif
             break;
         case iEXT_CHOOSE_PARAMS_SCREEN:
             iEvLineID = iCurMultiGame + 1;
             break;
         case iEXT_ACTIVATE_CHAT:
             if(!iChatON){
                 iScreenChat = 1;
                 iChatInit();
             }
             break;
         case iEXT_DEACTIVATE_CHAT:
             if(iChatON){
                 iChatFinit();
                 put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
                 //XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
             }
             break;
         case iEXT_LOCK_PARAMS:
             iLockMultiGameParameters();
             break;
         case iEXT_UNLOCK_PARAMS:
             iUnlockMultiGameParameters();
             break;
         case iEXT_DISCONNECT:
             disconnect_from_server();
             NetworkON = 0;
             break;
         case iEXT_INIT_KEEP_OPTIONS:
             iInitKeepOptions();
             break;
         case iEXT_KEEP_CLEAN_UP:
             iKeepCleanUp();
             break;
         case iEXT_INIT_RESULT:
             iPreparePlayerResults(data);
             break;
         case iEXT_CREATE_SERVER:
             iCreateServer();
             break;
         case iEXT_PREPARE_MP_RESULTS:
             iPrepareResults();
             break;
         //case iFULLSCREEN:
         //  std::cout<<"iFULLSCREEN"<<std::endl;
         //  break;
     }
 }
References actIntLog, aScrDisp, avaible_servers, XGR_Mouse::DisablePrompt(), EffectInUsePriory, EffectsOff(), EffectsOn(), XGR_Mouse::EnablePrompt(), XTList< Type >::first(), iBlockJoystickOption(), iCurHall, iEXT_DN_iSERVERS_LIST, iEXT_INIT_iSERVERS_LIST, iEXT_INIT_JOYSTICK, iEXT_INIT_JOYSTICK_OBJ, iEXT_INIT_PORT, iEXT_INIT_PROXY, iEXT_INIT_SOCKETS, iEXT_PREPARE_SLOTS, iEXT_RESTORE_PORT, iEXT_SAVE_GAME, iEXT_SELECT_HALL, iEXT_SET_SLOT, iEXT_UP_iSERVERS_LIST, iEXT_UPDATE_iSERVERS_LIST, iEXT_UPDATE_MUSIC_MODE, iEXT_UPDATE_MUSIC_VOLUME, iEXT_UPDATE_SOUND_MODE, iEXT_UPDATE_SOUND_VOLUME, iEXT_UPDATE_TUTORIAL_MODE, iFirstServerPtr, iGetControlCode(), iGetIP(), iGetOptionValue(), iGetOptionValueCHR(), iInitProxyOptions(), iInitServersList(), iJOYSTICK_TYPE, iKEY_JOYSTICK_SWITCH, iMUSIC_ON, iMUSIC_VOLUME_CUR, iMUSIC_VOLUME_MAX, iPause, iPrepareHallOfFame(), iPrepareSaveNames(), iScreenActive, iSERVER_PORT, iServerPort, iServersListDown(), iServersListUp(), iSetOptionValueCHR(), iSlotNumber, iSOUND_ON, iSOUND_VOLUME_CUR, iSOUND_VOLUME_MAX, iTUTORIAL_ON, iUpdateServersList(), JoystickAvailable, JoystickMode, JoystickStickSwitchButton, MusicON, MuteLog, NetworkON, SetSoundVolume(), SoundVolumeCD, StartCDTRACK(), StopCDTRACK(), XCD_PLAYING, XGR_MouseObj, xsGetStatusMusic(), xsGetVolumeMusic(), XSocketInit(), and xsSetVolumeMusic().
Referenced by iFinitQuant(), iLoadData(), and iScreenDispatcher::ProcessEvent().
iInit()
void iInit (void)
 {
     if(!iFirstInit){
         loadMouseFrames();
         InitScreenFonts();
         iResBuf = new XBuffer(2048);
         aLoadFonts32();
         iInitStrings();
     }
 #ifdef _BINARY_SCRIPT_
     if(!iFirstInit){
         if(lang() == RUSSIAN)
             ParseScript("resource/iscreen/oftr2.scb");
         else
             ParseScript("resource/iscreen/oftr.scb");
     }
 #else
     if(!iFirstInit){
         if(lang() == RUSSIAN)
             ParseScript("iscreen/oftr2.scr","resource/iscreen/oftr2.scb");
         else
             ParseScript("iscreen/oftr.scr","resource/iscreen/oftr.scb");
     }
 #endif
     if(iFirstInit){
         iScrDisp -> flags &= ~SD_EXIT;
         iScrDisp -> ret_val = 0;
     }
     ivMapPrepare();
 #ifndef _ACI_SKIP_MAINMENU_
     map_init();
 #endif
     XStream ff("resource/iscreen/mainmenu.pal",XS_IN);
     iscrPal = new uchar[768];
     ff.read(iscrPal,768);
     ipal_init(iscrPal);
     iScreenLog = 1;
 }
References aLoadFonts32(), iFirstInit, iInitStrings(), InitScreenFonts(), iResBuf, iScrDisp, lang(), loadMouseFrames(), ParseScript(), and RUSSIAN.
Referenced by MainMenuRTO::Init().
iInitControlKey()
void iInitControlKey (int id, int num)
 {
     //Stalkerg
     if (iScreenLastInput == SDL_SCANCODE_ESCAPE) {
         return;
     }
     //std::cout<<"iInitControlKey id:"<<id<<" num:"<<num<<std::endl;
     iSetControlCode(id,iScreenLastInput,num);
     iDeleteControl(iScreenLastInput,id * iKEY_OBJECT_SIZE + num);
 }
References iDeleteControl(), iKEY_OBJECT_SIZE, iScreenLastInput, and iSetControlCode().
iInitKeepOptions()
void iInitKeepOptions (void)
 {
     int sz;
     iScreenObject* p;
     if(iGetOptionValue(iKEEP_MODE)){
         sz = GetKeepSpace();
         iResBuf -> init();
         *iResBuf < iSTR_SpaceInUse < " " <= sz < " " < iSTR_MBytes;
         iSetOptionValueCHR(iKEEP_IN_USE,iResBuf -> address());
         iSetOptionValueCHR(iKEEP_CLEAN_UP,iSTR_CleanUp);
         p = (iScreenObject*)iGetObject("Graphics screen","CleanUpObj");
         if(p) p -> flags &= ~OBJ_LOCKED;
         KeepON = 1;
     }
     else {
         iSetOptionValueCHR(iKEEP_IN_USE,"");
         iSetOptionValueCHR(iKEEP_CLEAN_UP,"");
         p = (iScreenObject*)iGetObject("Graphics screen","CleanUpObj");
         if(p) p -> flags |= OBJ_LOCKED;
         KeepON = 0;
     }
 }
References GetKeepSpace(), iGetObject(), iGetOptionValue(), iKEEP_CLEAN_UP, iKEEP_IN_USE, iKEEP_MODE, iResBuf, iSetOptionValueCHR(), iSTR_CleanUp, iSTR_MBytes, and iSTR_SpaceInUse.
Referenced by iKeepCleanUp().
iInitMultiGames()
void iInitMultiGames (void)
 {
     int i;
     iScreen* scr;
     iListElement* el;
     XBuffer XNum;
     XBuffer XStr;
     XBuffer XPlace;
     iMP_Games = new iMultiGameData*[iMP_MAX_ID];
     for(i = 0; i < iMP_MAX_ID; i ++){
         iMP_Games[i] = new iMultiGameData;
     }
     scr = (iScreen*)iScrDisp -> get_object("Game Params 0");
     if(!scr) ErrH.Abort("iMP_Screen not found...");
     iMP_Games[iMP_VAN_WAR] -> alloc_mem(8);
     el = scr -> get_object("BeebosNumberID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_INITIAL_CASH] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_INITIAL_CASH] -> add_obj(el);
     el = scr -> get_object("ArtefactsTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_ARTEFACTS_USING] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_ARTEFACTS_USING] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_ARTEFACTS_USING] -> add_obj(el);
     el = scr -> get_object("TimeTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_IN_ESCAVE_TIME] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_IN_ESCAVE_TIME] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_IN_ESCAVE_TIME] -> add_obj(el);
     el = scr -> get_object("BirthTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_NASCENCY] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_NASCENCY] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_NASCENCY] -> add_obj(el);
     el = scr -> get_object("TeamTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_TEAM_MODE] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_TEAM_MODE] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_TEAM_MODE] -> add_obj(el);
     el = scr -> get_object("AccessTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_ACCESS] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_ACCESS] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_ACCESS] -> add_obj(el);
     el = scr -> get_object("MaxKillsID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_MAX_KILLS] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_MAX_KILLS] -> add_obj(el);
     el = scr -> get_object("MaxTimeID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_MAX_TIME] -> alloc_mem(1);
     iMP_Games[iMP_VAN_WAR] -> pData[iMP_MAX_TIME] -> add_obj(el);
     scr = (iScreen*)iScrDisp -> get_object("Game Params 1");
     if(!scr) ErrH.Abort("iMP_Screen not found...");
     iMP_Games[iMP_MECHOSOMA] -> alloc_mem(8);
     el = scr -> get_object("BeebosNumberID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_INITIAL_CASH] -> alloc_mem(1);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_INITIAL_CASH] -> add_obj(el);
     el = scr -> get_object("ArtefactsTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_ARTEFACTS_USING] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_ARTEFACTS_USING] -> alloc_mem(1);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_ARTEFACTS_USING] -> add_obj(el);
     el = scr -> get_object("TimeTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_IN_ESCAVE_TIME] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_IN_ESCAVE_TIME] -> alloc_mem(1);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_IN_ESCAVE_TIME] -> add_obj(el);
     el = scr -> get_object("TeamTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_TEAM_MODE] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_TEAM_MODE] -> alloc_mem(1);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_TEAM_MODE] -> add_obj(el);
     el = scr -> get_object("OneTimeNumID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_ONE_AT_A_TIME] -> alloc_mem(1);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_ONE_AT_A_TIME] -> add_obj(el);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_WORLD] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_WORLD] -> alloc_mem(3);
     el = scr -> get_object("WorldTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_WORLD] -> add_obj(el);
     el = scr -> get_object("ItemStrTrig1");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_WORLD] -> add_obj(el,1);
     el = scr -> get_object("ItemStrTrig2");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_WORLD] -> add_obj(el,2);
     el = scr -> get_object("ItemsNumberID1");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_QUANTITY1] -> alloc_mem(1);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_QUANTITY1] -> add_obj(el);
     el = scr -> get_object("ItemsNumberID2");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_QUANTITY2] -> alloc_mem(1);
     iMP_Games[iMP_MECHOSOMA] -> pData[iMP_QUANTITY2] -> add_obj(el);
     scr = (iScreen*)iScrDisp -> get_object("Game Params 2");
     if(!scr) ErrH.Abort("iMP_Screen not found...");
     iMP_Games[iMP_PASSEMBLOSS] -> alloc_mem(5);
     el = scr -> get_object("BeebosNumberID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_INITIAL_CASH] -> alloc_mem(1);
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_INITIAL_CASH] -> add_obj(el);
     el = scr -> get_object("ArtefactsTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_ARTEFACTS_USING] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_ARTEFACTS_USING] -> alloc_mem(1);
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_ARTEFACTS_USING] -> add_obj(el);
     el = scr -> get_object("TimeTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_IN_ESCAVE_TIME] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_IN_ESCAVE_TIME] -> alloc_mem(1);
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_IN_ESCAVE_TIME] -> add_obj(el);
     el = scr -> get_object("ChecksInputStrID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_CHECKPOINTS_NUM] -> alloc_mem(1);
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_CHECKPOINTS_NUM] -> add_obj(el);
     el = scr -> get_object("EscaveTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_ESCAVE] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_ESCAVE] -> alloc_mem(1);
     iMP_Games[iMP_PASSEMBLOSS] -> pData[iMP_ESCAVE] -> add_obj(el);
     scr = (iScreen*)iScrDisp -> get_object("Game Params 3");
     if(!scr) ErrH.Abort("iMP_Screen not found...");
     iMP_Games[iMP_HUNTAGE] -> alloc_mem(3);
     el = scr -> get_object("BeebosNumberID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_INITIAL_CASH] -> alloc_mem(1);
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_INITIAL_CASH] -> add_obj(el);
     el = scr -> get_object("ArtefactsTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_ARTEFACTS_USING] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_ARTEFACTS_USING] -> alloc_mem(1);
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_ARTEFACTS_USING] -> add_obj(el);
     el = scr -> get_object("TimeTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_IN_ESCAVE_TIME] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_IN_ESCAVE_TIME] -> alloc_mem(1);
     iMP_Games[iMP_HUNTAGE] -> pData[iMP_IN_ESCAVE_TIME] -> add_obj(el);
     scr = (iScreen*)iScrDisp -> get_object("Game Params 4");
     if(!scr) ErrH.Abort("iMP_Screen not found...");
     iMP_Games[iMP_MUSTODONT] -> alloc_mem(5);
     el = scr -> get_object("BeebosNumberID");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_INITIAL_CASH] -> alloc_mem(1);
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_INITIAL_CASH] -> add_obj(el);
     el = scr -> get_object("ArtefactsTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_ARTEFACTS_USING] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_ARTEFACTS_USING] -> alloc_mem(1);
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_ARTEFACTS_USING] -> add_obj(el);
     el = scr -> get_object("TimeTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_IN_ESCAVE_TIME] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_IN_ESCAVE_TIME] -> alloc_mem(1);
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_IN_ESCAVE_TIME] -> add_obj(el);
     el = scr -> get_object("TeamTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_TEAM_MODE] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_TEAM_MODE] -> alloc_mem(1);
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_TEAM_MODE] -> add_obj(el);
     el = scr -> get_object("MechosTrig");
     if(!el) ErrH.Abort("iObject not found...");
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_MECHOS_NAME] -> type = iMP_TRIGGER_STATE;
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_MECHOS_NAME] -> alloc_mem(1);
     iMP_Games[iMP_MUSTODONT] -> pData[iMP_MECHOS_NAME] -> add_obj(el);
     iPlaces = new iMultiResultString*[iMP_MAX_PLACE];
     iResults = new iMultiResultString*[iMP_MAX_RESULT];
     iHallPlaces = new iMultiResultString*[iMP_MAX_HALL_RESULT];
     for(i = 0; i < iMP_MAX_PLACE; i ++){
         iPlaces[i] = new iMultiResultString;
         XStr.init();
         XStr < "PrmStr" <= i;
         XNum.init();
         XNum < "NumStr" <= i;
         XPlace.init();
         XPlace < "PlaceStr" <= i;
         iPlaces[i] -> init("MultiGame Results screen",XPlace.address(),XStr.address(),XNum.address());
     }
     for(i = 0; i < iMP_MAX_RESULT; i ++){
         iResults[i] = new iMultiResultString;
         XStr.init();
         XStr < "PrmStr" <= i;
         XNum.init();
         XNum < "NumStr" <= i;
         XPlace.init();
         XPlace < "PlaceStr" <= i;
         iResults[i] -> init("MultiGame Results screen 2",XPlace.address(),XStr.address(),XNum.address());
     }
     for(i = 0; i < iMP_MAX_HALL_RESULT; i ++){
         iHallPlaces[i] = new iMultiResultString;
         XStr.init();
         XStr < "PrmStr" <= i;
         XNum.init();
         XNum < "NumStr" <= i;
         XPlace.init();
         XPlace < "PlaceStr" <= i;
         iHallPlaces[i] -> init("HallOfFame screen",XPlace.address(),XStr.address(),XNum.address());
     }
 }
References XErrorHandler::Abort(), XBuffer::address(), ErrH, iHallPlaces, iMP_ACCESS, iMP_ARTEFACTS_USING, iMP_CHECKPOINTS_NUM, iMP_ESCAVE, iMP_Games, iMP_HUNTAGE, iMP_IN_ESCAVE_TIME, iMP_INITIAL_CASH, iMP_MAX_HALL_RESULT, iMP_MAX_ID, iMP_MAX_KILLS, iMP_MAX_PLACE, iMP_MAX_RESULT, iMP_MAX_TIME, iMP_MECHOS_NAME, iMP_MECHOSOMA, iMP_MUSTODONT, iMP_NASCENCY, iMP_ONE_AT_A_TIME, iMP_PASSEMBLOSS, iMP_QUANTITY1, iMP_QUANTITY2, iMP_TEAM_MODE, iMP_TRIGGER_STATE, iMP_VAN_WAR, iMP_WORLD, XBuffer::init(), iPlaces, iResults, and iScrDisp.
Referenced by iQuantFirst().
iInitProxyOptions()
void iInitProxyOptions (void)
 {
     int mode;
     iScreenObject* obj;
     iStringElement* p1,*p2,*p3,*p4;
     p1 = (iStringElement*)iGetOptionObj(iPROXY_SERVER_STR);
     p2 = (iStringElement*)iGetOptionObj(iPROXY_SERVER);
     p3 = (iStringElement*)iGetOptionObj(iPROXY_PORT_STR);
     p4 = (iStringElement*)iGetOptionObj(iPROXY_PORT);
     if(!iProxyTerrFlag){
         iProxyTerrFlag = 1;
         iProxyServerStrTerr = p1 -> terrainNum;
         iProxyServerTerr = p2 -> terrainNum;
         iProxyPortStrTerr = p3 -> terrainNum;
         iProxyPortTerr = p4 -> terrainNum;
     }
     mode = iGetOptionValue(iPROXY_USAGE);
     if(mode){
         p1 -> terrainNum = iProxyServerStrTerr;
         p2 -> terrainNum = iProxyServerTerr;
         p3 -> terrainNum = iProxyPortStrTerr;
         p4 -> terrainNum = iProxyPortTerr;
     }
     else {
         p1 -> terrainNum = -1;
         p2 -> terrainNum = -1;
         p3 -> terrainNum = -1;
         p4 -> terrainNum = -1;
     }
     obj = (iScreenObject*)p1 -> owner;
     obj -> flags |= OBJ_REINIT;
     obj -> flags |= OBJ_MUST_REDRAW;
     if(!mode) obj -> flags |= OBJ_LOCKED;
     else obj -> flags &= ~OBJ_LOCKED;
     obj = (iScreenObject*)p2 -> owner;
     obj -> flags |= OBJ_REINIT;
     obj -> flags |= OBJ_MUST_REDRAW;
     if(!mode) obj -> flags |= OBJ_LOCKED;
     else obj -> flags &= ~OBJ_LOCKED;
     obj = (iScreenObject*)p3 -> owner;
     obj -> flags |= OBJ_REINIT;
     obj -> flags |= OBJ_MUST_REDRAW;
     if(!mode) obj -> flags |= OBJ_LOCKED;
     else obj -> flags &= ~OBJ_LOCKED;
     obj = (iScreenObject*)p4 -> owner;
     obj -> flags |= OBJ_REINIT;
     obj -> flags |= OBJ_MUST_REDRAW;
     if(!mode) obj -> flags |= OBJ_LOCKED;
     else obj -> flags &= ~OBJ_LOCKED;
     iProxyUsage = iGetOptionValue(iPROXY_USAGE);
     iProxyServer = iGetOptionValueCHR(iPROXY_SERVER);
     iProxyPort = atoi(iGetOptionValueCHR(iPROXY_PORT));
 }
References iGetOptionObj(), iGetOptionValue(), iPROXY_PORT, iPROXY_PORT_STR, iPROXY_SERVER, iPROXY_SERVER_STR, iPROXY_USAGE, iProxyPortStrTerr, iProxyPortTerr, iProxyServerStrTerr, iProxyServerTerr, and iProxyTerrFlag.
Referenced by iHandleExtEvent().
iInitS_Text()
void iInitS_Text (iScreenObject * obj, char * text, int text_len, int font, int space, int null_level)
 {
     int i,y = 0,t_sz;
     char* buf;
     iS_StringElement* p;
     buf = new char[text_len];
     memcpy(buf,text,text_len);
     for(i = 0; i < text_len; i ++){
         if(buf[i] == '\r' || buf[i] == '\n') buf[i] = 0;
     }
     i = 0;
     while(i < text_len){
         while(!buf[i]) i ++;
         if(i < text_len){
             p = new iS_StringElement;
             t_sz = strlen(buf + i) + 1;
             if(t_sz){
                 p -> string = new char[t_sz];
                 strcpy(p -> string,buf + i);
                 p -> flags |= EL_TEXT_STRING;
                 p -> font = font;
                 p -> null_level = null_level;
                 p -> space = space;
                 p -> lY = y;
                 y += iScrFontTable[p -> font] -> SizeY + p -> space;
                 obj -> add_element((iListElement*)p);
             }
             while(buf[i]) i ++;
         }
     }
 }
iInitServersList()
void iInitServersList ()
 {
     int i,sz;
     iScreen* scr;
     iStringElement* el;
     iScreenObject* obj;
     XBuffer XBuf;
     ServerFindChain* p;
     scr = (iScreen*)iScrDisp -> get_object("iSearch server screen");
     if(!scr) return;
     p = iFirstServerPtr;
     for(i = 0; i < ACI_NUM_SERVERS; i ++){
         XBuf.init();
         XBuf < "ServerStr" <= i;
         el = (iStringElement*)scr -> get_object(XBuf.address());
         if(el){
             obj = (iScreenObject*)el -> owner;
             memset(el -> string,0,ACI_SERVER_NAME_LEN + 1);
             if(p){
                 sz = strlen(p -> name);
                 if(sz > ACI_SERVER_NAME_LEN)
                     memcpy(el -> string,p -> name,ACI_SERVER_NAME_LEN);
                 else
                     strcpy(el -> string,p -> name);
                 p = p -> next;
                 obj -> flags &= ~OBJ_LOCKED;
             }
             else
                 obj -> flags |= (OBJ_LOCKED | OBJ_NOT_UNLOCK);
             el -> init_size();
             el -> init_align();
             obj -> flags |= OBJ_MUST_REDRAW;
         }
     }
 }
References ACI_NUM_SERVERS, ACI_SERVER_NAME_LEN, XBuffer::address(), iFirstServerPtr, XBuffer::init(), and iScrDisp.
Referenced by iHandleExtEvent(), iServersListUp(), and iUpdateServersList().
iInitStrings()
void iInitStrings (void)
 {
     if(lang() == RUSSIAN){
         iSTR_WORLD_NONE_CHAR = iSTR_WORLD_NONE_CHAR2;
         iSTR_WORLD_FOSTRAL_CHAR = iSTR_WORLD_FOSTRAL_CHAR2;
         iSTR_WORLD_GLORX_CHAR = iSTR_WORLD_GLORX_CHAR2;
         iSTR_WORLD_NECROSS_CHAR = iSTR_WORLD_NECROSS_CHAR2;
         iSTR_WORLD_XPLO_CHAR = iSTR_WORLD_XPLO_CHAR2;
         iSTR_WORLD_KHOX_CHAR = iSTR_WORLD_KHOX_CHAR2;
         iSTR_WORLD_BOOZEENA_CHAR = iSTR_WORLD_BOOZEENA_CHAR2;
         iSTR_WORLD_WEEXOW_CHAR = iSTR_WORLD_WEEXOW_CHAR2;
         iSTR_WORLD_HMOK_CHAR = iSTR_WORLD_HMOK_CHAR2;
         iSTR_WORLD_THREALL_CHAR = iSTR_WORLD_THREALL_CHAR2;
         iSTR_WORLD_ARK_A_ZNOY_CHAR = iSTR_WORLD_ARK_A_ZNOY_CHAR2;
         iSTR_COLOR_GREEN_CHAR = iSTR_COLOR_GREEN_CHAR2;
         iSTR_COLOR_ORANGE_CHAR = iSTR_COLOR_ORANGE_CHAR2;
         iSTR_COLOR_BLUE_CHAR = iSTR_COLOR_BLUE_CHAR2;
         iSTR_COLOR_YELLOW_CHAR = iSTR_COLOR_YELLOW_CHAR2;
         iSTR_COLOR_RED_CHAR = iSTR_COLOR_RED_CHAR2;
         iSTR_COLOR_WHITE_CHAR = iSTR_COLOR_WHITE_CHAR2;
         iSTR_COLOR_GRAY_CHAR = iSTR_COLOR_GRAY_CHAR2;
         iSTR_COLOR_BLACK_CHAR = iSTR_COLOR_BLACK_CHAR2;
         iSTR_COLOR_CAMOUFLAGE_CHAR = iSTR_COLOR_CAMOUFLAGE_CHAR2;
         iSTR_COLOR_PATROL_CHAR = iSTR_COLOR_PATROL_CHAR2;
         iSTR_MUTE_ALL = iSTR_MUTE_ALL2;
         iSTR_CLEAR_LOG = iSTR_CLEAR_LOG2;
         iSTR_BACKGROUND = iSTR_BACKGROUND2;
         iSTR_LEAVE_CHAT = iSTR_LEAVE_CHAT2;
         iSTR_All = iSTR_All2;
         iSTR_Yellow = iSTR_Yellow2;
         iSTR_Orange = iSTR_Orange2;
         iSTR_Blue = iSTR_Blue2;
         iSTR_Green = iSTR_Green2;
         iSTR_Red = iSTR_Red2;
         iSTR_White = iSTR_White2;
         iSTR_Gray = iSTR_Gray2;
         iSTR_Black = iSTR_Black2;
         iSTR_Camouflage = iSTR_Camouflage2;
         iSTR_Patrol = iSTR_Patrol2;
         iSTR_CleanUp = iSTR_CleanUp2;
         iSTR_SpaceInUse = iSTR_SpaceInUse2;
         iSTR_MBytes = iSTR_MBytes2;
         iSTR_MP_Kills = iSTR_MP_Kills2;
         iSTR_MP_Deaths = iSTR_MP_Deaths2;
         iSTR_MP_DeathTimeMin = iSTR_MP_DeathTimeMin2;
         iSTR_MP_DeathTimeMax = iSTR_MP_DeathTimeMax2;
         iSTR_MP_Kills_rate = iSTR_MP_Kills_rate2;
         iSTR_MP_Deaths_rate = iSTR_MP_Deaths_rate2;
         iSTR_MP_Ware01_Delivery = iSTR_MP_Ware01_Delivery2;
         iSTR_MP_Ware02_Delivery = iSTR_MP_Ware02_Delivery2;
         iSTR_MP_Min_delivery_time = iSTR_MP_Min_delivery_time2;
         iSTR_MP_Max_delivery_time = iSTR_MP_Max_delivery_time2;
         iSTR_MP_StolenWares = iSTR_MP_StolenWares2;
         iSTR_MP_Wares_lost = iSTR_MP_Wares_lost2;
         iSTR_MP_Total_time = iSTR_MP_Total_time2;
         iSTR_MP_Min_checkpoint_time = iSTR_MP_Min_checkpoint_time2;
         iSTR_MP_Max_checkpoint_time = iSTR_MP_Max_checkpoint_time2;
         iSTR_MP_1st_part_delivery = iSTR_MP_1st_part_delivery2;
         iSTR_MP_2nd_part_delivery = iSTR_MP_2nd_part_delivery2;
         iSTR_MP_Mechos_frame = iSTR_MP_Mechos_frame2;
         iSTR_MP_Mechos_assembled_in = iSTR_MP_Mechos_assembled_in2;
         iSTR_NONE = iSTR_NONE2;
         iSTR_EMPTY_SLOT = iSTR_EMPTY_SLOT2;
         iSTR_Checkpoints_Number = iSTR_Checkpoints_Number2;
         iSTR_DefaultPassword = iSTR_DefaultPassword2;
     }
     else {
         iSTR_WORLD_NONE_CHAR = iSTR_WORLD_NONE_CHAR1;
         iSTR_WORLD_FOSTRAL_CHAR = iSTR_WORLD_FOSTRAL_CHAR1;
         iSTR_WORLD_GLORX_CHAR = iSTR_WORLD_GLORX_CHAR1;
         iSTR_WORLD_NECROSS_CHAR = iSTR_WORLD_NECROSS_CHAR1;
         iSTR_WORLD_XPLO_CHAR = iSTR_WORLD_XPLO_CHAR1;
         iSTR_WORLD_KHOX_CHAR = iSTR_WORLD_KHOX_CHAR1;
         iSTR_WORLD_BOOZEENA_CHAR = iSTR_WORLD_BOOZEENA_CHAR1;
         iSTR_WORLD_WEEXOW_CHAR = iSTR_WORLD_WEEXOW_CHAR1;
         iSTR_WORLD_HMOK_CHAR = iSTR_WORLD_HMOK_CHAR1;
         iSTR_WORLD_THREALL_CHAR = iSTR_WORLD_THREALL_CHAR1;
         iSTR_WORLD_ARK_A_ZNOY_CHAR = iSTR_WORLD_ARK_A_ZNOY_CHAR1;
         iSTR_COLOR_GREEN_CHAR = iSTR_COLOR_GREEN_CHAR1;
         iSTR_COLOR_ORANGE_CHAR = iSTR_COLOR_ORANGE_CHAR1;
         iSTR_COLOR_BLUE_CHAR = iSTR_COLOR_BLUE_CHAR1;
         iSTR_COLOR_YELLOW_CHAR = iSTR_COLOR_YELLOW_CHAR1;
         iSTR_COLOR_RED_CHAR = iSTR_COLOR_RED_CHAR1;
         iSTR_COLOR_WHITE_CHAR = iSTR_COLOR_WHITE_CHAR1;
         iSTR_COLOR_GRAY_CHAR = iSTR_COLOR_GRAY_CHAR1;
         iSTR_COLOR_BLACK_CHAR = iSTR_COLOR_BLACK_CHAR1;
         iSTR_COLOR_CAMOUFLAGE_CHAR = iSTR_COLOR_CAMOUFLAGE_CHAR1;
         iSTR_COLOR_PATROL_CHAR = iSTR_COLOR_PATROL_CHAR1;
         iSTR_MUTE_ALL = iSTR_MUTE_ALL1;
         iSTR_CLEAR_LOG = iSTR_CLEAR_LOG1;
         iSTR_BACKGROUND = iSTR_BACKGROUND1;
         iSTR_LEAVE_CHAT = iSTR_LEAVE_CHAT1;
         iSTR_All = iSTR_All1;
         iSTR_Yellow = iSTR_Yellow1;
         iSTR_Orange = iSTR_Orange1;
         iSTR_Blue = iSTR_Blue1;
         iSTR_Green = iSTR_Green1;
         iSTR_Red = iSTR_Red1;
         iSTR_White = iSTR_White1;
         iSTR_Gray = iSTR_Gray1;
         iSTR_Black = iSTR_Black1;
         iSTR_Camouflage = iSTR_Camouflage1;
         iSTR_Patrol = iSTR_Patrol1;
         iSTR_CleanUp = iSTR_CleanUp1;
         iSTR_SpaceInUse = iSTR_SpaceInUse1;
         iSTR_MBytes = iSTR_MBytes1;
         iSTR_MP_Kills = iSTR_MP_Kills1;
         iSTR_MP_Deaths = iSTR_MP_Deaths1;
         iSTR_MP_DeathTimeMin = iSTR_MP_DeathTimeMin1;
         iSTR_MP_DeathTimeMax = iSTR_MP_DeathTimeMax1;
         iSTR_MP_Kills_rate = iSTR_MP_Kills_rate1;
         iSTR_MP_Deaths_rate = iSTR_MP_Deaths_rate1;
         iSTR_MP_Ware01_Delivery = iSTR_MP_Ware01_Delivery1;
         iSTR_MP_Ware02_Delivery = iSTR_MP_Ware02_Delivery1;
         iSTR_MP_Min_delivery_time = iSTR_MP_Min_delivery_time1;
         iSTR_MP_Max_delivery_time = iSTR_MP_Max_delivery_time1;
         iSTR_MP_StolenWares = iSTR_MP_StolenWares1;
         iSTR_MP_Wares_lost = iSTR_MP_Wares_lost1;
         iSTR_MP_Total_time = iSTR_MP_Total_time1;
         iSTR_MP_Min_checkpoint_time = iSTR_MP_Min_checkpoint_time1;
         iSTR_MP_Max_checkpoint_time = iSTR_MP_Max_checkpoint_time1;
         iSTR_MP_1st_part_delivery = iSTR_MP_1st_part_delivery1;
         iSTR_MP_2nd_part_delivery = iSTR_MP_2nd_part_delivery1;
         iSTR_MP_Mechos_frame = iSTR_MP_Mechos_frame1;
         iSTR_MP_Mechos_assembled_in = iSTR_MP_Mechos_assembled_in1;
         iSTR_NONE = iSTR_NONE1;
         iSTR_EMPTY_SLOT = iSTR_EMPTY_SLOT1;
         iSTR_Checkpoints_Number = iSTR_Checkpoints_Number1;
         iSTR_DefaultPassword = iSTR_DefaultPassword1;
     }
 }
References iSTR_All, iSTR_All1, iSTR_All2, iSTR_BACKGROUND, iSTR_BACKGROUND1, iSTR_BACKGROUND2, iSTR_Black, iSTR_Black1, iSTR_Black2, iSTR_Blue, iSTR_Blue1, iSTR_Blue2, iSTR_Camouflage, iSTR_Camouflage1, iSTR_Camouflage2, iSTR_Checkpoints_Number, iSTR_Checkpoints_Number1, iSTR_Checkpoints_Number2, iSTR_CleanUp, iSTR_CleanUp1, iSTR_CleanUp2, iSTR_CLEAR_LOG, iSTR_CLEAR_LOG1, iSTR_CLEAR_LOG2, iSTR_COLOR_BLACK_CHAR, iSTR_COLOR_BLACK_CHAR1, iSTR_COLOR_BLACK_CHAR2, iSTR_COLOR_BLUE_CHAR, iSTR_COLOR_BLUE_CHAR1, iSTR_COLOR_BLUE_CHAR2, iSTR_COLOR_CAMOUFLAGE_CHAR, iSTR_COLOR_CAMOUFLAGE_CHAR1, iSTR_COLOR_CAMOUFLAGE_CHAR2, iSTR_COLOR_GRAY_CHAR, iSTR_COLOR_GRAY_CHAR1, iSTR_COLOR_GRAY_CHAR2, iSTR_COLOR_GREEN_CHAR, iSTR_COLOR_GREEN_CHAR1, iSTR_COLOR_GREEN_CHAR2, iSTR_COLOR_ORANGE_CHAR, iSTR_COLOR_ORANGE_CHAR1, iSTR_COLOR_ORANGE_CHAR2, iSTR_COLOR_PATROL_CHAR, iSTR_COLOR_PATROL_CHAR1, iSTR_COLOR_PATROL_CHAR2, iSTR_COLOR_RED_CHAR, iSTR_COLOR_RED_CHAR1, iSTR_COLOR_RED_CHAR2, iSTR_COLOR_WHITE_CHAR, iSTR_COLOR_WHITE_CHAR1, iSTR_COLOR_WHITE_CHAR2, iSTR_COLOR_YELLOW_CHAR, iSTR_COLOR_YELLOW_CHAR1, iSTR_COLOR_YELLOW_CHAR2, iSTR_DefaultPassword, iSTR_DefaultPassword1, iSTR_DefaultPassword2, iSTR_EMPTY_SLOT, iSTR_EMPTY_SLOT1, iSTR_EMPTY_SLOT2, iSTR_Gray, iSTR_Gray1, iSTR_Gray2, iSTR_Green, iSTR_Green1, iSTR_Green2, iSTR_LEAVE_CHAT, iSTR_LEAVE_CHAT1, iSTR_LEAVE_CHAT2, iSTR_MBytes, iSTR_MBytes1, iSTR_MBytes2, iSTR_MP_1st_part_delivery, iSTR_MP_1st_part_delivery1, iSTR_MP_1st_part_delivery2, iSTR_MP_2nd_part_delivery, iSTR_MP_2nd_part_delivery1, iSTR_MP_2nd_part_delivery2, iSTR_MP_Deaths, iSTR_MP_Deaths1, iSTR_MP_Deaths2, iSTR_MP_Deaths_rate, iSTR_MP_Deaths_rate1, iSTR_MP_Deaths_rate2, iSTR_MP_DeathTimeMax, iSTR_MP_DeathTimeMax1, iSTR_MP_DeathTimeMax2, iSTR_MP_DeathTimeMin, iSTR_MP_DeathTimeMin1, iSTR_MP_DeathTimeMin2, iSTR_MP_Kills, iSTR_MP_Kills1, iSTR_MP_Kills2, iSTR_MP_Kills_rate, iSTR_MP_Kills_rate1, iSTR_MP_Kills_rate2, iSTR_MP_Max_checkpoint_time, iSTR_MP_Max_checkpoint_time1, iSTR_MP_Max_checkpoint_time2, iSTR_MP_Max_delivery_time, iSTR_MP_Max_delivery_time1, iSTR_MP_Max_delivery_time2, iSTR_MP_Mechos_assembled_in, iSTR_MP_Mechos_assembled_in1, iSTR_MP_Mechos_assembled_in2, iSTR_MP_Mechos_frame, iSTR_MP_Mechos_frame1, iSTR_MP_Mechos_frame2, iSTR_MP_Min_checkpoint_time, iSTR_MP_Min_checkpoint_time1, iSTR_MP_Min_checkpoint_time2, iSTR_MP_Min_delivery_time, iSTR_MP_Min_delivery_time1, iSTR_MP_Min_delivery_time2, iSTR_MP_StolenWares, iSTR_MP_StolenWares1, iSTR_MP_StolenWares2, iSTR_MP_Total_time, iSTR_MP_Total_time1, iSTR_MP_Total_time2, iSTR_MP_Ware01_Delivery, iSTR_MP_Ware01_Delivery1, iSTR_MP_Ware01_Delivery2, iSTR_MP_Ware02_Delivery, iSTR_MP_Ware02_Delivery1, iSTR_MP_Ware02_Delivery2, iSTR_MP_Wares_lost, iSTR_MP_Wares_lost1, iSTR_MP_Wares_lost2, iSTR_MUTE_ALL, iSTR_MUTE_ALL1, iSTR_MUTE_ALL2, iSTR_NONE, iSTR_NONE1, iSTR_NONE2, iSTR_Orange, iSTR_Orange1, iSTR_Orange2, iSTR_Patrol, iSTR_Patrol1, iSTR_Patrol2, iSTR_Red, iSTR_Red1, iSTR_Red2, iSTR_SpaceInUse, iSTR_SpaceInUse1, iSTR_SpaceInUse2, iSTR_White, iSTR_White1, iSTR_White2, iSTR_WORLD_ARK_A_ZNOY_CHAR, iSTR_WORLD_ARK_A_ZNOY_CHAR1, iSTR_WORLD_ARK_A_ZNOY_CHAR2, iSTR_WORLD_BOOZEENA_CHAR, iSTR_WORLD_BOOZEENA_CHAR1, iSTR_WORLD_BOOZEENA_CHAR2, iSTR_WORLD_FOSTRAL_CHAR, iSTR_WORLD_FOSTRAL_CHAR1, iSTR_WORLD_FOSTRAL_CHAR2, iSTR_WORLD_GLORX_CHAR, iSTR_WORLD_GLORX_CHAR1, iSTR_WORLD_GLORX_CHAR2, iSTR_WORLD_HMOK_CHAR, iSTR_WORLD_HMOK_CHAR1, iSTR_WORLD_HMOK_CHAR2, iSTR_WORLD_KHOX_CHAR, iSTR_WORLD_KHOX_CHAR1, iSTR_WORLD_KHOX_CHAR2, iSTR_WORLD_NECROSS_CHAR, iSTR_WORLD_NECROSS_CHAR1, iSTR_WORLD_NECROSS_CHAR2, iSTR_WORLD_NONE_CHAR, iSTR_WORLD_NONE_CHAR1, iSTR_WORLD_NONE_CHAR2, iSTR_WORLD_THREALL_CHAR, iSTR_WORLD_THREALL_CHAR1, iSTR_WORLD_THREALL_CHAR2, iSTR_WORLD_WEEXOW_CHAR, iSTR_WORLD_WEEXOW_CHAR1, iSTR_WORLD_WEEXOW_CHAR2, iSTR_WORLD_XPLO_CHAR, iSTR_WORLD_XPLO_CHAR1, iSTR_WORLD_XPLO_CHAR2, iSTR_Yellow, iSTR_Yellow1, iSTR_Yellow2, lang(), and RUSSIAN.
Referenced by iInit().
iInitText()
void iInitText (iScreenObject * obj, char * text, int text_len, int font, int space, int null_level)
 {
     int i, y = 0, t_sz;
     char* buf;
     iStringElement* p;
     buf = new char[text_len];
     memcpy(buf, text, text_len);
     for(i = 0; i < text_len; i ++) {
         if(buf[i] == '\r' || buf[i] == '\n') {
             buf[i] = 0;
         }
     }
     i = 0;
     while(i < text_len) {
         while(!buf[i]) {
             i++;
         }
         if(i < text_len) {
             p = new iStringElement;
             t_sz = strlen(buf + i) + 1;
             if(t_sz) {
                 p->string = new char[t_sz];
                 strcpy(p->string, buf + i);
                 p->flags |= EL_TEXT_STRING;
                 p->font = font;
                 p->null_level = null_level;
                 p->space = space;
                 p->lY = y;
                 y += HFntTable[p->font]->SizeY + p->space;
                 obj->add_element((iListElement*)p);
             }
             while(buf[i]) {
                 i++;
             }
         }
     }
     delete[] buf;
 }
References iScreenObject::add_element(), EL_TEXT_STRING, iScreenElement::flags, iStringElement::font, HFntTable, iScreenElement::lY, iScreenElement::null_level, HFont::SizeY, iStringElement::space, and iStringElement::string.
iKeepCleanUp()
void iKeepCleanUp (void)
 {
     KeepCleanUp();
     iInitKeepOptions();
 }
References iInitKeepOptions(), and KeepCleanUp().
iKeyClear()
void iKeyClear (void)
 {
     KeyBuf -> clear();
 }
References KeyBuf.
Referenced by aciOpenGate(), actIntDispatcher::i_finit(), and MainMenuRTO::Init().
iKeyTrap()
void iKeyTrap (int k)
 {
     if(!iPause){
         if(!iScrDisp -> ActiveEv){
             if(!actIntLog){
                 iScrDisp -> CheckScanCode(k);
             }
             else {
                 aciML_D -> key_trap(k,AML_KEY);
                 aScrDisp -> iKeyTrap(k);
             }
             if(!(iScrDisp -> flags & SD_LOCK_EVENTS))
                 iScrDisp -> curScr -> CheckScanCode(k);
         }
     }
 }
References aciML_D, actIntLog, AML_KEY, aScrDisp, iPause, and iScrDisp.
iLoadControls()
void iLoadControls (void)
 {
     int sz0,sz1;
     if(!iControlsObj || RecorderMode) return;
     XStream fh(0);
     if(!fh.open("controls.dat",XS_IN)) return;
     fh > sz0 > sz1;
     if(sz0 != iKEY_MAX_ID || sz1 != iKEY_OBJECT_SIZE){
         fh.close();
         return;
     }
     fh.read(iControlsObj -> keyCodes,iKEY_OBJECT_SIZE * iKEY_MAX_ID * sizeof(int));
     fh.close();
     iInitControlObjects();
 }
References XStream::close(), iControlsObj, iInitControlObjects(), iKEY_MAX_ID, iKEY_OBJECT_SIZE, XStream::open(), XStream::read(), RecorderMode, and XS_IN.
Referenced by iQuantFirst().
iLoadData()
void iLoadData (void)
 {
     XStream fh(0);
     if(!RecorderMode){
         if(fh.open("options.dat",XS_IN)){
             iScrDisp -> load_data(&fh);
             fh > aciAutoRun;
             fh.close();
         }
     }
     aciAutoRun = iGetOptionValue(iAUTO_ACCELERATION);
     iHandleExtEvent(iEXT_UPDATE_SOUND_MODE);
     iHandleExtEvent(iEXT_UPDATE_MUSIC_MODE);
     iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
     iHandleExtEvent(iEXT_UPDATE_SOUND_VOLUME);
     iHandleExtEvent(iEXT_UPDATE_MUSIC_VOLUME);
     iHandleExtEvent(iEXT_UPDATE_TUTORIAL_MODE);
     iHandleExtEvent(iEXT_INIT_KEEP_OPTIONS);
     iHandleExtEvent(iEXT_INIT_JOYSTICK);
     iHandleExtEvent(iEXT_INIT_PROXY);
     iHandleExtEvent(iEXT_INIT_PORT);
 }
References aciAutoRun, XStream::close(), iAUTO_ACCELERATION, iEXT_INIT_JOYSTICK, iEXT_INIT_KEEP_OPTIONS, iEXT_INIT_PORT, iEXT_INIT_PROXY, iEXT_UPDATE_MUSIC_MODE, iEXT_UPDATE_MUSIC_VOLUME, iEXT_UPDATE_SOUND_MODE, iEXT_UPDATE_SOUND_VOLUME, iEXT_UPDATE_TUTORIAL_MODE, iGetOptionValue(), iHandleExtEvent(), iScrDisp, XStream::open(), RecorderMode, and XS_IN.
Referenced by iQuantFirst(), and iQuantPrepare().
iLockExit()
void iLockExit (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button01");
     if(p) p -> flags |= OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
iLockMultiGameParameters()
void iLockMultiGameParameters (void)
 {
     int i;
     for(i = 0; i < iMP_MAX_ID; i ++){
         iMP_Games[i] -> block();
     }
 }
References iMP_Games, and iMP_MAX_ID.
iLockShop()
void iLockShop (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button04");
     if(p) p -> flags |= OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
iMS_LeftPress()
void iMS_LeftPress (int fl, int x, int y)
 {
     iScrDisp -> flags |= MS_LEFT_PRESS;
     iMouseX = x;
     iMouseY = y;
     iMouseLPressFlag = 1;
     aciML_ToolzerON = 1;
     if(actIntLog)
         aMS_LeftPress(0,x,y);
     XGR_MouseSetSeq(0,1,XGM_PLAY_ONCE,1);
 }
References iScrDisp.
Referenced by MS_init().
iMS_LeftUnpress()
void iMS_LeftUnpress (int fl, int x, int y)
 {
     iMouseX = x;
     iMouseY = y;
     aciML_ToolzerON = 0;
     iMouseLPressFlag = 0;
     if(actIntLog)
         aMS_LeftUnpress(0,x,y);
     XGR_MouseSetSeq(XGR_MouseCurFrame,XGR_MouseNumFrames - 1,XGM_PLAY_ONCE,1);
 }
References aciML_ToolzerON, actIntLog, aMS_LeftUnpress(), iMouseLPressFlag, iMouseX, iMouseY, XGM_PLAY_ONCE, XGR_MouseCurFrame, XGR_MouseNumFrames, and XGR_MouseSetSeq.
Referenced by MS_init().
iMS_Movement()
void iMS_Movement (int v, int x, int y)
 {
     iScrDisp -> flags |= MS_MOVED;
     iMousePrevX = iMouseX;
     iMousePrevY = iMouseY;
     iMouseX = x;
     iMouseY = y;
     if(actIntLog)
         aMS_Movement(v,x,y);
 }
References iScrDisp.
Referenced by MS_init().
iMS_RightPress()
void iMS_RightPress (int fl, int x, int y)
 {
     iScrDisp -> flags |= MS_RIGHT_PRESS;
     iMouseX = x;
     iMouseY = y;
     iMouseRPressFlag = 1;
     if(actIntLog)
         aMS_RightPress(0,x,y);
     XGR_MouseSetSeq(0,1,XGM_PLAY_ONCE,1);
 }
References iScrDisp.
Referenced by MS_init().
iMS_RightUnpress()
void iMS_RightUnpress (int fl, int x, int y)
 {
     iMouseX = x;
     iMouseY = y;
     iMouseRPressFlag = 0;
     if(actIntLog)
         aMS_RightUnpress(0,x,y);
     XGR_MouseSetSeq(XGR_MouseCurFrame,XGR_MouseNumFrames - 1,XGM_PLAY_ONCE,1);
 }
References actIntLog, aMS_RightUnpress(), iMouseRPressFlag, iMouseX, iMouseY, XGM_PLAY_ONCE, XGR_MouseCurFrame, XGR_MouseNumFrames, and XGR_MouseSetSeq.
Referenced by MS_init().
init_hfonts()
void init_hfonts (void)
 {
     int i;
     XBuffer XBuf;
     if(!HFntTable){
         HFntTable = new HFont*[iNumFonts];
         for(i = 0; i < iNumFonts; i ++){
             XBuf.init();
             XBuf < "resource/iscreen/fonts/hfont";
             if(i < 10)  XBuf < "0";
             XBuf <= i < ".fnh";
             HFntTable[i] = new HFont;
             HFntTable[i] -> load(XBuf.GetBuf());
         }
     }
 }
References XBuffer::GetBuf(), HFntTable, XBuffer::init(), and iNumFonts.
Referenced by iPreInitFirst(), iQuantFirst(), and ParseScript().
InitScreenFonts()
void InitScreenFonts (void)
 {
     int i,sz;
     XBuffer XBuf;
     XStream fh;
     char* buf;
     iScrFontTable = new iScreenFont*[I_FONT_SIZE];
     for(i = 0; i < I_FONT_SIZE; i ++){
         XBuf.init();
         XBuf < "resource/iscreen/fonts/sfont";
         if(i < 10)
             XBuf < "0";
         XBuf <= i < ".fnt";
         fh.open(XBuf.GetBuf(),XS_IN);
         sz = fh.size();
         buf = new char[sz];
         fh.read(buf,sz);
         fh.close();
         iScrFontTable[i] = new iScreenFont(buf,sz);
     }
 }
References XStream::close(), XBuffer::GetBuf(), I_FONT_SIZE, XBuffer::init(), iScrFontTable, XStream::open(), XStream::read(), XStream::size(), and XS_IN.
Referenced by iInit().
iOutEscaveFinit()
void iOutEscaveFinit (void)
 {
     if(actIntLog){
         aciML_D -> flags &= ~AML_END_SHUTDOWN;
     }
 }
References aciML_D, and actIntLog.
Referenced by EscaveOutRTO::Finit(), and FirstEscaveOutRTO::Finit().
iOutEscaveInit()
void iOutEscaveInit (void)
 {
     if(actIntLog && !(aScrDisp -> flags & AS_ISCREEN_INV_MODE)){
         aciML_SendEvent(AML_SHUTDOWN_EV);
     }
 }
References actIntLog, and aScrDisp.
Referenced by EscaveOutRTO::Init(), and FirstEscaveOutRTO::Init().
iOutEscaveQuant()
int iOutEscaveQuant (void)
 {
 #ifndef _ACI_NO_SHOP_ANIMATION_
     if(actIntLog && !(aScrDisp -> flags & AS_ISCREEN_INV_MODE)){
         if(!(aciML_D -> flags & AML_END_SHUTDOWN) && !(aciML_D -> flags & AML_PAUSE)){
             aciML_D -> quant();
             aciML_D -> flush();
             return 0;
         }
     }
 #endif
     return 1;
 }
References actIntLog, and aScrDisp.
Referenced by EscaveOutRTO::Quant(), and FirstEscaveOutRTO::Quant().
ipal_init()
void ipal_init (unsigned char * p)
 {
     if(!ipalbuf){
         ipalbuf = new uchar[768];
         ipalbufOrg = new uchar[768];
         }
     memcpy(ipalbuf,p,768);
     memcpy(ipalbufOrg,p,768);
 }
ipal_iter()
void ipal_iter (int r)
 {
     ipal_iter0();
     ipal_iter1();
     ipal_iter2();
     XGR_SetPal(ipalbuf,0,reduced ? 128 : 256);
 }
References ipal_iter0(), ipal_iter1(), ipal_iter2(), and XGR_SetPal.
iPreInitFirst()
void iPreInitFirst ()
                      {
     if (!iFirstInit) {
         aScrDisp->i_init();
     }
     iSecondInit();
     iScreen* p;
     if(actIntLog){
         p = (iScreen*)iScrDisp -> get_object(aci_iScreenID);
         if(!p) ErrH.Abort("Bad aci_iScreenID...");
         iScrDisp -> curScr = p;
         if(NetworkON){
             iEscaveTimer = -1;
             iEndGameFlag = 0;
         }
     }
     else {
 #ifndef _ACI_SKIP_MAINMENU_
         iEvLineID = 0;
         iScrDisp -> init_texts();
         if(iMultiFlag){
             iScrDisp -> curScr = (iScreen*)iScrDisp -> get_object("MultiGame Results screen");
             iPrepareResults();
             iMultiFlag = 0;
             iEndGameFlag = 1;
         }
         else
             iScrDisp -> curScr = (iScreen*)iScrDisp -> get_object(iScrDisp -> t_scrID);
 #endif
     }
     iInitControls();
     iScreenOffs = iScrDisp -> curScr -> ScreenOffs;
 #ifdef _ACI_SKIP_MAINMENU_
     if(actIntLog){
 #endif
     init_hfonts();
     if(!actIntLog)
         iScrDisp -> prepare();
     iScrDisp -> curScr -> prepare();
     iScrDisp -> alloc_mem();
 #ifdef _ACI_SKIP_MAINMENU_
     }
 #endif
     if(!iFirstInit){
         RegisterValues();
         iPrepareOptions();
     }
 }
References XErrorHandler::Abort(), aci_iScreenID, actIntLog, aScrDisp, ErrH, actIntDispatcher::i_init(), iEndGameFlag, iEscaveTimer, iEvLineID, iFirstInit, iInitControls(), iMultiFlag, init_hfonts(), iPrepareOptions(), iPrepareResults(), iScrDisp, iScreenOffs, iSecondInit(), NetworkON, and RegisterValues().
iPrepareHallOfFame()
void iPrepareHallOfFame (void)
 {
     int i,num;
     RatingData* p;
     XBuffer XPlace,XNum;
     TopList top_list(iCurHall);
     XNum.digits = 3;
     num = top_list.size();
     if(num > iMP_MAX_HALL_RESULT) num = iMP_MAX_HALL_RESULT;
     p = top_list.first();
     for(i = 0; i < num; i ++){
         XPlace.init();
         XPlace <= i + 1 < ".";
         XNum.init();
         XNum <= (int)round(p -> rating);
         iHallPlaces[i] -> set_data(XPlace.address(),p -> name,XNum.address());
         iHallPlaces[i] -> redraw();
         p = p -> next;
     }
     for(i = num; i < iMP_MAX_HALL_RESULT; i ++){
         iHallPlaces[i] -> set_data("","","");
         iHallPlaces[i] -> redraw();
     }
 }
References XBuffer::address(), XBuffer::digits, XTList< Type >::first(), iCurHall, iHallPlaces, iMP_MAX_HALL_RESULT, XBuffer::init(), round(), and XTList< Type >::size().
Referenced by iHandleExtEvent().
iPrepareOptions()
void iPrepareOptions (void)
 {
     int i;
     iScrOpt = new iScreenOption*[iMAX_OPTION_ID];
     for(i = 0; i < iMAX_OPTION_ID; i ++)
         iScrOpt[i] = NULL;
     iScrOpt[iJOYSTICK_TYPE] = new iScreenOption(iTRIGGER,0,"Joystick screen","JoyTypeID");
     iScrOpt[iSOUND_ON] = new iScreenOption(iTRIGGER,0,"Sound screen","SoundTrig");
     iScrOpt[iSOUND_VOLUME_CUR] = new iScreenOption(iSCROLLER,0,"Sound screen","SndVolumeScroller");
     iScrOpt[iSOUND_VOLUME_MAX] = new iScreenOption(iSCROLLER,1,"Sound screen","SndVolumeScroller");
     iScrOpt[iMECH_SOUND] = new iScreenOption(iTRIGGER,0,"Sound screen","MechSndTrig");
     iScrOpt[iBACK_SOUND] = new iScreenOption(iTRIGGER,0,"Sound screen","BackSndTrig");
     iScrOpt[iMUSIC_ON] = new iScreenOption(iTRIGGER,0,"Sound screen","MusicTrig");
     iScrOpt[iPANNING_ON] = new iScreenOption(iTRIGGER,0,"Sound screen","PanningTrig");
     iScrOpt[iMUSIC_VOLUME_CUR] = new iScreenOption(iSCROLLER,0,"Sound screen","MusVolumeScroller");
     iScrOpt[iMUSIC_VOLUME_MAX] = new iScreenOption(iSCROLLER,1,"Sound screen","MusVolumeScroller");
     iScrOpt[iTUTORIAL_ON] = new iScreenOption(iTRIGGER,0,"Graphics screen","TutorialTrig");
     iScrOpt[iDETAIL_SETTING] = new iScreenOption(iTRIGGER,0,"Graphics screen","DetailTrig");
     iScrOpt[iSCREEN_RESOLUTION] = new iScreenOption(iTRIGGER,0,"Graphics screen","ResTrig");
     iScrOpt[iPLAYER_COLOR3] = new iScreenOption(iTRIGGER,0,"Identification screen2","ColorTrig");
     iScrOpt[iPLAYER_COLOR] = new iScreenOption(iTRIGGER,0,"Identification screen","ColorTrig");
     iScrOpt[iPLAYER_NAME2] = new iScreenOption(iSTRING,0,"Identification screen","PlayerName");
     iScrOpt[iPLAYER_NAME_CR] = new iScreenOption(iSTRING,0,"Identification screen2","PlayerName");
     iScrOpt[iPLAYER_NAME3] = new iScreenOption(iSTRING,0,"Configuration screen 2","PlayerName");
     iScrOpt[iPLAYER_COLOR2] = new iScreenOption(iTRIGGER,0,"Configuration screen 2","ColorTrig");
     iScrOpt[iPLAYER_PASSWORD] = new iScreenOption(iSTRING,0,"Identification screen","PasswordString");
     iScrOpt[iPLAYER_PASSWORD_CR] = new iScreenOption(iSTRING,0,"Identification screen2","PasswordString");
     iScrOpt[iPLAYER_PASSWORD] -> add_link(iScrOpt[iPLAYER_PASSWORD_CR]);
     iScrOpt[iPLAYER_PASSWORD_CR] -> add_link(iScrOpt[iPLAYER_PASSWORD]);
     iScrOpt[iPLAYER_NAME3] -> add_link(iScrOpt[iPLAYER_NAME2]);
     iScrOpt[iPLAYER_NAME2] -> add_link(iScrOpt[iPLAYER_NAME3]);
     iScrOpt[iPLAYER_NAME_CR] -> add_link(iScrOpt[iPLAYER_NAME2]);
     iScrOpt[iPLAYER_NAME_CR] -> add_link(iScrOpt[iPLAYER_NAME3]);
     iScrOpt[iPLAYER_NAME2] -> add_link(iScrOpt[iPLAYER_NAME_CR]);
     iScrOpt[iPLAYER_NAME3] -> add_link(iScrOpt[iPLAYER_NAME_CR]);
     iScrOpt[iPLAYER_COLOR] -> add_link(iScrOpt[iPLAYER_COLOR2]);
     iScrOpt[iPLAYER_COLOR] -> add_link(iScrOpt[iPLAYER_COLOR3]);
     iScrOpt[iPLAYER_COLOR2] -> add_link(iScrOpt[iPLAYER_COLOR]);
     iScrOpt[iPLAYER_COLOR2] -> add_link(iScrOpt[iPLAYER_COLOR3]);
     iScrOpt[iPLAYER_COLOR3] -> add_link(iScrOpt[iPLAYER_COLOR]);
     iScrOpt[iPLAYER_COLOR3] -> add_link(iScrOpt[iPLAYER_COLOR2]);
     iScrOpt[iSERVER_NAME] = new iScreenOption(iSTRING,0,"Server Config screen","ServerName");
     iScrOpt[iSERVER_NAME2] = new iScreenOption(iSTRING,0,"Server Info screen","ServerName");
     iScrOpt[iSERVER_NAME2] -> add_link(iScrOpt[iSERVER_NAME]);
     iScrOpt[iSERVER_NAME] -> add_link(iScrOpt[iSERVER_NAME2]);
     iScrOpt[iMPGAME0_ID] = new iScreenOption(iSTRING,0,"Select Game","GameStr0");
     iScrOpt[iMPGAME1_ID] = new iScreenOption(iSTRING,0,"Select Game","GameStr1");
     iScrOpt[iMPGAME2_ID] = new iScreenOption(iSTRING,0,"Select Game","GameStr2");
     iScrOpt[iMPGAME3_ID] = new iScreenOption(iSTRING,0,"Select Game","GameStr3");
     iScrOpt[iMPGAME4_ID] = new iScreenOption(iSTRING,0,"Select Game","GameStr4");
     iScrOpt[iMPGAME0_ID] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iMPGAME1_ID] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iMPGAME2_ID] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iMPGAME3_ID] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iMPGAME4_ID] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iCUR_MPGAME_ID] = new iScreenOption(iSTRING,0,"Server Config screen","GameNameStr");
     iScrOpt[iCUR_MPGAME_ID] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iCUR_MPGAME_ID2] = new iScreenOption(iSTRING,0,"Server Info screen","GameNameStr");
     iScrOpt[iCUR_MPGAME_ID2] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iCUR_MPGAME_ID] -> add_link(iScrOpt[iCUR_MPGAME_ID2]);
     iScrOpt[iCUR_MPGAME_ID2] -> add_link(iScrOpt[iCUR_MPGAME_ID]);
     iScrOpt[iHOST_NAME] = new iScreenOption(iSTRING,0,"INet Host screen","HostName");
     iScrOpt[iIP_ADDRESS] = new iScreenOption(iSTRING,0,"INet Host screen","IP_AddrID");
     iScrOpt[iIP_ADDRESS] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iKEEP_IN_USE] = new iScreenOption(iSTRING,0,"Graphics screen","InUseStr");
     iScrOpt[iKEEP_IN_USE] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iKEEP_CLEAN_UP] = new iScreenOption(iSTRING,0,"Graphics screen","CleanUpStr");
     iScrOpt[iKEEP_CLEAN_UP] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iKEEP_MODE] = new iScreenOption(iTRIGGER,0,"Graphics screen","KeepTrig");
     iScrOpt[iDESTR_MODE] = new iScreenOption(iTRIGGER,0,"Graphics screen","DestrTrig");
     iScrOpt[iPROXY_USAGE] = new iScreenOption(iTRIGGER,0,"INet Host screen","ProxyTrg");
     iScrOpt[iPROXY_SERVER] = new iScreenOption(iSTRING,0,"INet Host screen","ProxyServerName");
     iScrOpt[iPROXY_PORT] = new iScreenOption(iSTRING,0,"INet Host screen","ProxyPortNum");
     iScrOpt[iSERVER_PORT] = new iScreenOption(iSTRING,0,"Port screen","PortStrID");
     iScrOpt[iPROXY_SERVER_STR] = new iScreenOption(iSTRING,0,"INet Host screen","ProxyServerStrID");
     iScrOpt[iPROXY_SERVER_STR] -> flags |= iOPTION_NO_SAVE;
     iScrOpt[iPROXY_PORT_STR] = new iScreenOption(iSTRING,0,"INet Host screen","ProxyPortStrID");
     iScrOpt[iPROXY_PORT_STR] -> flags |= iOPTION_NO_SAVE;
     //Stalkerg hack for save fake menu options.
     iScrOpt[iCAMERA_TURN] = new iScreenOption(iTRIGGER,0,NULL,"CameraTurn");
     iScrOpt[iCAMERA_TURN]->objPtr = new iTriggerObject();
     iScrOpt[iCAMERA_SLOPE] = new iScreenOption(iTRIGGER,0,NULL,"CameraSlope");
     iScrOpt[iCAMERA_SLOPE]->objPtr = new iTriggerObject();
     iScrOpt[iCAMERA_SCALE] = new iScreenOption(iTRIGGER,0,NULL,"CameraScale");
     iScrOpt[iCAMERA_SCALE]->objPtr = new iTriggerObject();
     iScrOpt[iFULLSCREEN] = new iScreenOption(iTRIGGER,0,"Graphics screen","FullScreenTrig");
     ((iTriggerObject *)iScrOpt[iFULLSCREEN]->objPtr)->callback = &iSetFullscreen;
     iScrOpt[iAUTO_ACCELERATION] = new iScreenOption(iTRIGGER,0,"Controls screen","AutoAccelerationTrig");
     iPrepareControls();
 }
References iBACK_SOUND, iDETAIL_SETTING, iJOYSTICK_TYPE, iMAX_OPTION_ID, iMECH_SOUND, iMPGAME0_ID, iMPGAME1_ID, iMPGAME2_ID, iMPGAME3_ID, iMPGAME4_ID, iMUSIC_ON, iMUSIC_VOLUME_CUR, iMUSIC_VOLUME_MAX, iPANNING_ON, iPLAYER_COLOR, iPLAYER_COLOR2, iPLAYER_COLOR3, iPLAYER_NAME2, iPLAYER_NAME3, iPLAYER_NAME_CR, iPLAYER_PASSWORD, iPLAYER_PASSWORD_CR, iSCREEN_RESOLUTION, iSCROLLER, iScrOpt, iSERVER_NAME, iSERVER_NAME2, iSOUND_ON, iSOUND_VOLUME_CUR, iSOUND_VOLUME_MAX, iSTRING, iTRIGGER, iTUTORIAL_ON, and NULL.
Referenced by iPreInitFirst(), and iQuantFirst().
iPreparePlayerResults()
void iPreparePlayerResults (int id)
 {
     int i,num,num0,num1,num2;
     XBuffer XBuf;
     PlayerData* p = iPlayers[id];
     if(iCurMultiGame == iMP_VAN_WAR){
         XBuf.init();
         XBuf <= p -> body.kills;
         iResults[0] -> set_data("",iSTR_MP_Kills,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.deaths;
         iResults[1] -> set_data("",iSTR_MP_Deaths,XBuf.address());
 /*
         XBuf.init();
         if(p -> body.VanVarStat.MinLiveTime)
             XBuf <= p -> body.VanVarStat.MinLiveTime;
         else
             XBuf < "-";
         iResults[2] -> set_data("",iSTR_MP_DeathTimeMin,XBuf.address());
         XBuf.init();
         if(p -> body.VanVarStat.MaxLiveTime)
             XBuf <= p -> body.VanVarStat.MaxLiveTime;
         else
             XBuf < "-";
         iResults[3] -> set_data("",iSTR_MP_DeathTimeMax,XBuf.address());
 */
         num = p -> body.VanVarStat.KillFreq;
         num0 = num / 3600;
         num1 = (num - num0 * 3600) / 60;
         num2 = num % 60;
         XBuf.init();
         if(num)
             XBuf <= num0 < ":" <= num1 < ":" <= num2;
         else
             XBuf < "-";
         iResults[2] -> set_data("",iSTR_MP_Kills_rate,XBuf.address());
         num = p -> body.VanVarStat.DeathFreq;
         num0 = num / 3600;
         num1 = (num - num0 * 3600) / 60;
         num2 = num % 60;
         XBuf.init();
         if(p -> body.VanVarStat.DeathFreq)
             XBuf <= num0 < ":" <= num1 < ":" <= num2;
         else
             XBuf < "-";
         iResults[3] -> set_data("",iSTR_MP_Deaths_rate,XBuf.address());
         for(i = 0; i < 4; i ++)
             iResults[i] -> redraw();
         for(i = 4; i < iMP_MAX_RESULT; i ++){
             iResults[i] -> set_data("","","");
             iResults[i] -> redraw();
         }
     }
     if(iCurMultiGame == iMP_MECHOSOMA){
         XBuf.init();
         XBuf <= p -> body.kills;
         iResults[0] -> set_data("",iSTR_MP_Kills,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.deaths;
         iResults[1] -> set_data("",iSTR_MP_Deaths,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.MechosomaStat.ItemCount1;
         iResults[2] -> set_data("",iSTR_MP_Ware01_Delivery,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.MechosomaStat.ItemCount2;
         iResults[3] -> set_data("",iSTR_MP_Ware02_Delivery,XBuf.address());
 /*
         XBuf.init();
         if(p -> body.MechosomaStat.MinTransitTime)
             XBuf <= p -> body.MechosomaStat.MinTransitTime;
         else
             XBuf < "-";
         iResults[4] -> set_data("",iSTR_MP_Min_delivery_time,XBuf.address());
 */
         num = p -> body.MechosomaStat.MaxTransitTime;
         num0 = num / 3600;
         num1 = (num - num0 * 3600) / 60;
         num2 = num % 60;
         XBuf.init();
         if(p -> body.MechosomaStat.MaxTransitTime)
             XBuf <= num0 < ":" <= num1 < ":" <= num2;
         else
             XBuf < "-";
         iResults[4] -> set_data("",iSTR_MP_Max_delivery_time,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.MechosomaStat.SneakCount;
         iResults[5] -> set_data("",iSTR_MP_StolenWares,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.MechosomaStat.LostCount;
         iResults[6] -> set_data("",iSTR_MP_Wares_lost,XBuf.address());
         for(i = 0; i < 7; i ++)
             iResults[i] -> redraw();
         for(i = 7; i < iMP_MAX_RESULT; i ++){
             iResults[i] -> set_data("","","");
             iResults[i] -> redraw();
         }
     }
     if(iCurMultiGame == iMP_PASSEMBLOSS){
         XBuf.init();
         XBuf <= p -> body.kills;
         iResults[0] -> set_data("",iSTR_MP_Kills,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.deaths;
         iResults[1] -> set_data("",iSTR_MP_Deaths,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.PassemblossStat.CheckpointLighting;
         iResults[2] -> set_data("",iSTR_Checkpoints_Number,XBuf.address());
         num = p -> body.PassemblossStat.TotalTime;
         num0 = num / 3600;
         num1 = (num - num0 * 3600) / 60;
         num2 = num % 60;
         XBuf.init();
         if(p -> body.PassemblossStat.TotalTime)
             XBuf <= num0 < ":" <= num1 < ":" <= num2;
         else
             XBuf < "-";
         iResults[3] -> set_data("",iSTR_MP_Total_time,XBuf.address());
 /*
         XBuf.init();
         if(p -> body.PassemblossStat.MinTime)
             XBuf <= p -> body.PassemblossStat.MinTime;
         else
             XBuf < "-";
         iResults[3] -> set_data("",iSTR_MP_Min_checkpoint_time,XBuf.address());
         XBuf.init();
         if(p -> body.PassemblossStat.MaxTime)
             XBuf <= p -> body.PassemblossStat.MaxTime;
         else
             XBuf < "-";
         iResults[4] -> set_data("",iSTR_MP_Max_checkpoint_time,XBuf.address());
 */
         for(i = 0; i < 4; i ++)
             iResults[i] -> redraw();
         for(i = 4; i < iMP_MAX_RESULT; i ++){
             iResults[i] -> set_data("","","");
             iResults[i] -> redraw();
         }
     }
     if(iCurMultiGame == iMP_HUNTAGE){
         XBuf.init();
         XBuf <= p -> body.kills;
         iResults[0] -> set_data("",iSTR_MP_Kills,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.deaths;
         iResults[1] -> set_data("",iSTR_MP_Deaths,XBuf.address());
         for(i = 0; i < 2; i ++)
             iResults[i] -> redraw();
         for(i = 2; i < iMP_MAX_RESULT; i ++){
             iResults[i] -> set_data("","","");
             iResults[i] -> redraw();
         }
     }
     if(iCurMultiGame == iMP_MUSTODONT){
         XBuf.init();
         XBuf <= p -> body.kills;
         iResults[0] -> set_data("",iSTR_MP_Kills,XBuf.address());
         XBuf.init();
         XBuf <= p -> body.deaths;
         iResults[1] -> set_data("",iSTR_MP_Deaths,XBuf.address());
         XBuf.init();
         if(p -> body.MustodontStat.PartTime1)
             XBuf <= p -> body.MustodontStat.PartTime1;
         else
             XBuf < "-";
         iResults[2] -> set_data("",iSTR_MP_1st_part_delivery,XBuf.address());
         XBuf.init();
         if(p -> body.MustodontStat.PartTime2)
             XBuf <= p -> body.MustodontStat.PartTime2;
         else
             XBuf < "-";
         iResults[3] -> set_data("",iSTR_MP_2nd_part_delivery,XBuf.address());
         XBuf.init();
         if(p -> body.MustodontStat.BodyTime)
             XBuf <= p -> body.MustodontStat.BodyTime;
         else
             XBuf < "-";
         iResults[4] -> set_data("",iSTR_MP_Mechos_frame,XBuf.address());
         XBuf.init();
         if(p -> body.MustodontStat.MakeTime)
             XBuf <= p -> body.MustodontStat.MakeTime;
         else
             XBuf < "-";
         iResults[5] -> set_data("",iSTR_MP_Mechos_assembled_in,XBuf.address());
         for(i = 0; i < 6; i ++)
             iResults[i] -> redraw();
         for(i = 6; i < iMP_MAX_RESULT; i ++){
             iResults[i] -> set_data("","","");
             iResults[i] -> redraw();
         }
     }
 }
References XBuffer::address(), iCurMultiGame, iMP_HUNTAGE, iMP_MAX_RESULT, iMP_MECHOSOMA, iMP_MUSTODONT, iMP_PASSEMBLOSS, iMP_VAN_WAR, XBuffer::init(), iPlayers, iResults, iSTR_Checkpoints_Number, iSTR_MP_1st_part_delivery, iSTR_MP_2nd_part_delivery, iSTR_MP_Deaths, iSTR_MP_Deaths_rate, iSTR_MP_Kills, iSTR_MP_Kills_rate, iSTR_MP_Max_delivery_time, iSTR_MP_Mechos_assembled_in, iSTR_MP_Mechos_frame, iSTR_MP_StolenWares, iSTR_MP_Total_time, iSTR_MP_Ware01_Delivery, iSTR_MP_Ware02_Delivery, and iSTR_MP_Wares_lost.
iPrepareResults()
void iPrepareResults (void)
 {
     int i,num;
     XBuffer XPlace,XNum;
     XNum.digits = 3;
     iSortPlayers();
     num = (iNumPlayers < iMP_MAX_PLACE) ? iNumPlayers : iMP_MAX_PLACE;
     for(i = 0; i < num; i ++){
         XPlace.init();
         XPlace <= i + 1 < ".";
         XNum.init();
         XNum <= (int)round(iPlayerRatings[i]);
         iPlaces[i] -> set_data(XPlace.address(),iPlayers[i] -> name,XNum.address());
         iPlaces[i] -> redraw();
     }
     for(i = num; i < iMP_MAX_PLACE; i ++){
         iPlaces[i] -> set_data("","","");
         iPlaces[i] -> redraw();
     }
 }
References XBuffer::address(), XBuffer::digits, iMP_MAX_PLACE, XBuffer::init(), iNumPlayers, iPlaces, iPlayerRatings, iPlayers, iSortPlayers(), and round().
Referenced by iPreInitFirst(), and iQuantFirst().
iPrepareSaveNames()
void iPrepareSaveNames (void)
 {
     int i,len,time_len;
     XBuffer XBuf;
     XBuffer XBufStr;
     XStream fh(0);
     iScreen* scr = (iScreen*)iScrDisp -> get_object("Loading screen");
     iScreenObject* obj,*obj1;
     if(!scr) return;
     iStringElement* el,*el1;
     for(i = 0; i <= ACS_NUM_SLOTS; i ++){
         XBuf.init();
         XBufStr.init();
         XBuf < "savegame/save";
         if(i < 10) XBuf < "0";
         XBuf <= i < ".dat";
         XBufStr < "SlotStr" <= i;
         el = (iStringElement*)scr -> get_object(XBufStr.address());
         XBufStr.init();
         XBufStr < "SlotStrTime" <= i;
         el1 = (iStringElement*)scr -> get_object(XBufStr.address());
         if(el){
             obj = (iScreenObject*)el -> owner;
             if(el1){
                 obj1 = (iScreenObject*)el1 -> owner;
             }
             if(fh.open(XBuf.address(),XS_IN)){
                 fh > len;
                 time_len = (len >> 16) & 0xFF;
                 len &= 0xFF;
                 fh.read(el -> string,len);
                 el -> string[len] = 0;
                 if(el1){
                     if(time_len){
                         fh.read(el1 -> string,time_len);
                         el1 -> string[time_len] = 0;
                         obj1 -> flags &= ~OBJ_LOCKED;
                     }
                     else {
                         el1 -> string[0] = 0;
                         obj1 -> flags |= OBJ_LOCKED;
                     }
                 }
                 fh.close();
                 obj -> flags &= ~OBJ_LOCKED;
             }
             else {
                 strcpy(el -> string,iSTR_EMPTY_SLOT);
                 obj -> flags |= OBJ_LOCKED;
                 if(el1){
                     el1 -> string[0] = 0;
                     obj1 -> flags |= OBJ_LOCKED;
                 }
             }
             el -> init_size();
             el -> init_align();
             obj -> flags |= OBJ_REINIT;
             if(el1){
                 el1 -> init_size();
                 el1 -> init_align();
                 obj1 -> flags |= OBJ_REINIT;
             }
         }
     }
 }
References ACS_NUM_SLOTS, XBuffer::address(), XBuffer::init(), iScrDisp, XStream::open(), XStream::read(), and XS_IN.
Referenced by iHandleExtEvent().
iPutStr()
void iPutStr (int x, int y, int fnt, unsigned char * str, int mode, int scale, int space, int level, int hide_mode)
 {
     int _x,_y,i,sx,sy,ss,sz = strlen((char*)str);
     HFont* p = HFntTable[fnt];
     HChar* ch;
     unsigned char* ptr,*ptr1;
     _x = x;
     _y = y;
     for(i = 0; i < sz; i ++){
         ch = p -> data[str[i]];
         ptr = ch -> HeightMap;
         sx = ch -> SizeX;
         sy = ch -> SizeY;
         ss = sx * sy;
         if(str[i] == '\n'){
             _x = x;
             _y += sy + space;
         }
         else {
             _iALLOC_A_(unsigned char,ptr1,ss);
             scale_buf(sx,sy,scale,ptr,ptr1);
             put_buf(_x - ch -> LeftOffs,_y,sx,sy,ptr1,ptr,level,hide_mode);
             _iFREE_A_(unsigned char,ptr1,ss);
             _x += sx - ch -> RightOffs - ch -> LeftOffs + space;
         }
     }
 }
iQuantFirst()
void iQuantFirst (void)
 {
     iScreen* p;
     if(actIntLog){
         p = (iScreen*)iScrDisp -> get_object(aci_iScreenID);
         if(!p) ErrH.Abort("Bad aci_iScreenID...");
         iScrDisp -> curScr = p;
         if(NetworkON){
             iEscaveTimer = -1;
             iEndGameFlag = 0;
         }
     }
     else {
 #ifndef _ACI_SKIP_MAINMENU_
         iEvLineID = 0;
         iScrDisp -> init_texts();
         if(iMultiFlag){
             iScrDisp -> curScr = (iScreen*)iScrDisp -> get_object("MultiGame Results screen");
             iPrepareResults();
             iMultiFlag = 0;
             iEndGameFlag = 1;
         }
         else
             iScrDisp -> curScr = (iScreen*)iScrDisp -> get_object(iScrDisp -> t_scrID);
 #endif
     }
     iInitControls();
     iScreenOffs = iScrDisp -> curScr -> ScreenOffs;
 #ifdef _ACI_SKIP_MAINMENU_
     if(actIntLog){
 #endif
     init_hfonts();
     if(!actIntLog)
         iScrDisp -> prepare();
     iScrDisp -> curScr -> prepare();
     iScrDisp -> alloc_mem();
 #ifdef _ACI_SKIP_MAINMENU_
     }
 #endif
     if(!iFirstInit){
         RegisterValues();
         iPrepareOptions();
 #ifndef _ACI_SKIP_MAINMENU_
         if(lang() == RUSSIAN)
             iSetOptionValueCHR(iPLAYER_NAME2," ");
         else
             iSetOptionValueCHR(iPLAYER_NAME2,"Vanger");
         iSetOptionValueCHR(iPLAYER_PASSWORD,iSTR_DefaultPassword);
         if(lang() == RUSSIAN) {
             iSetOptionValueCHR(iHOST_NAME, "vangers.net");
         } else if (lang() == GERMAN) {
 //          iSetOptionValueCHR(iHOST_NAME,"www.imagicgames.de");
             iSetOptionValueCHR(iHOST_NAME,"vangers.net");
         }
         else
             iSetOptionValueCHR(iHOST_NAME,"vangers.net");
 //            iSetOptionValueCHR(iHOST_NAME,"www.imagicgames.com");
         iSetOptionValueCHR(iSERVER_NAME,iSTR_NONE);
         iSetOptionValueCHR(iPROXY_SERVER,"192.1.1.1");
         iSetOptionValueCHR(iPROXY_PORT,"1080");
         iSetOptionValueCHR(iSERVER_PORT,"2197");
         iGetIP();
 #endif
         iInitMultiGames();
         CurServerName = iGetOptionValueCHR(iSERVER_NAME);
         CurPlayerName = iGetOptionValueCHR(iPLAYER_NAME2);
     }
     aciSet_iMouse();
     KBD_init();
     MS_init();
     XGR_MouseHide();
 #ifdef _ACI_SKIP_MAINMENU_
     if(actIntLog){
 #endif
     if(!actIntLog){
         iLoadData();
     }
     iStartupLog = 1;
     iScrDisp -> redraw();
     put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
     iStartupLog = 0;
 #ifdef _ACI_SKIP_MAINMENU_
     }
 #endif
     if(!iFirstInit){
         iLoadControls();
         iInitControlObjects();
     }
     iFirstInit = 1;
     iScreenActive = 1;
 }
References XErrorHandler::Abort(), aci_iScreenID, aciSet_iMouse(), actIntLog, CurPlayerName, CurServerName, ErrH, GERMAN, I_RES_X, I_RES_Y, iEndGameFlag, iEscaveTimer, iEvLineID, iFirstInit, iGetIP(), iGetOptionValueCHR(), iHOST_NAME, iInitControlObjects(), iInitControls(), iInitMultiGames(), iLoadControls(), iLoadData(), iMultiFlag, init_hfonts(), iPLAYER_NAME2, iPLAYER_PASSWORD, iPrepareOptions(), iPrepareResults(), iPROXY_PORT, iPROXY_SERVER, iScrDisp, iScreenActive, iScreenOffs, iSERVER_NAME, iSERVER_PORT, iSetOptionValueCHR(), iStartupLog, iSTR_DefaultPassword, iSTR_NONE, KBD_init(), lang(), MS_init(), NetworkON, put_map(), RegisterValues(), RUSSIAN, and XGR_MouseHide.
Referenced by MainMenuRTO::Init(), and iScrQuantPrepare().
iQuantPrepare()
void iQuantPrepare (void)
 {
     if(actIntLog){
         aciML_D -> redraw_items();
         iForcedExitFlag = 0;
     }
     else {
 #ifndef _ACI_SKIP_MAINMENU_
         iLoadData();
 #endif
     }
     if(iScrDisp -> ActiveEv){
         iScrDisp -> ActiveEv -> flags &= ~EV_ACTIVE;
         iScrDisp -> ActiveEv = NULL;
     }
 }
References aciML_D, actIntLog, iForcedExitFlag, iLoadData(), and iScrDisp.
Referenced by MainMenuRTO::Init(), and iScrQuantPrepare().
iQuantSecond()
int iQuantSecond (void)
 {
     SDL_Event *k;
 #ifdef _DEBUG
     int cr;
     int count = 0;
     XBuffer* XBufBMP,*XBufPAL;
 #endif
 #ifdef _ACI_SKIP_MAINMENU_
     if(!actIntLog){
         iScrDisp -> flags |= SD_EXIT;
         iScrDisp -> ret_val = 1;
 #ifdef _ACI_STARTUP_LOAD_GAME_
         iScrDisp -> ret_val = ACI_LOAD_CODE;
 #endif
     }
 #endif
     if(!iPause) {
         if(actIntLog && NetworkON){
             if(iEscaveTimer == -1)
                 iEscaveTimer = iGetEscaveTime();
             iEscaveTimer--;
             if(iEscaveTimer < 0){
                 iScrDisp -> flags |= SD_EXIT;
                 iScrExitCode = 1;
                 aScrDisp -> events -> clear();
             }
         }
         if(iForcedExitFlag && iScrDisp -> ActiveEv && iScrDisp -> ActiveEv -> cur_time <= 1){
             iScrDisp -> flags |= SD_EXIT;
             iForcedExitFlag = 0;
             if(iTheEND){
                 Dead = 1;
                 acsHandleExtEvent(ACS_GLOBAL_EXIT);
             }
         }
         if(!(iScrDisp -> flags & SD_EXIT)){
             if(iKeyPressed(iKEY_EXIT)){
                 i_slake_pal(iscrPal,32);
                 if(!actIntLog){
                     iSaveControls();
                     iSaveData();
                 }
                 if(actIntLog)
                     acsHandleExtEvent(ACS_GLOBAL_EXIT);
                 aciPrepareEndImage();
                 iScrExitCode = 0;
                 XGR_MouseHide();
                 return 1;
             }
             if(!(iScrDisp -> flags & SD_INPUT_STRING)) {
                 while(KeyBuf -> size) {
                     k = KeyBuf -> get();
                     if(iChatON)
                         iChatKeyQuant(k);
                     if((k->type == SDL_KEYDOWN && k->key.keysym.scancode == SDL_SCANCODE_ESCAPE) && actIntLog){
                         iPause ^= 1;
                         acsScreenID = 2;
                     }
 //                  if(k->type == SDL_KEYDOWN && k->key.keysym.scancode == SDL_SCANCODE_F11) {
                     if(iKeyPressed(iKEY_SCREENSHOT)) {
                         shotFlush();
                     }
                     if (k->type == SDL_KEYDOWN || k->type == SDL_KEYUP) {
                         iKeyTrap(k->key.keysym.scancode);
                     } else if (k->type == SDL_JOYBUTTONDOWN || k->type == SDL_JOYBUTTONUP) {
                         iKeyTrap(k->jbutton.button | SDLK_JOYSTICK_BUTTON_MASK);
                     } else if (k->type == SDL_CONTROLLERBUTTONDOWN || k->type == SDL_CONTROLLERBUTTONUP) {
                         iKeyTrap(k->cbutton.button | SDLK_GAMECONTROLLER_BUTTON_MASK);
                     } else if (k->type == SDL_JOYHATMOTION) {
                         iKeyTrap((k->jhat.value + 10*k->jhat.hat) | SDLK_JOYSTICK_HAT_MASK);
                     }
                 }
             } /*else {
                 k = JoystickWhatsPressedNow();
                 if(k)
                     KeyBuf -> put(k,CUR_KEY_PRESSED);
             }*/
             if(iScrDisp -> flags & MS_LEFT_PRESS){
                 iScrDisp -> flags &= ~MS_LEFT_PRESS;
                 iKeyTrap(iMOUSE_LEFT_PRESS_CODE);
                 if(iChatON) iChatMouseQuant(iMouseX,iMouseY,1);
             }
             if(iScrDisp -> flags & MS_RIGHT_PRESS){
                 iScrDisp -> flags &= ~MS_RIGHT_PRESS;
                 iKeyTrap(iMOUSE_RIGHT_PRESS_CODE);
                 if(iChatON) iChatMouseQuant(iMouseX,iMouseY,1);
             }
             if(iScrDisp -> flags & MS_MOVED){
                 iScrDisp -> flags &= ~MS_MOVED;
                 iKeyTrap(iMOUSE_MOVE_CODE);
                 if(iMouseLPressFlag)
                     iKeyTrap(iMOUSE_LEFT_MOVE);
                 if(iMouseRPressFlag)
                     iKeyTrap(iMOUSE_RIGHT_MOVE);
             }
 #ifdef iMOVE_MOUSE_OBJECTS
             iMovedObj = iGetScreenObj(iMouseX + iScreenOffs,iMouseY);
             iShowObjCoords(iMovedObj);
 #endif
             if(!iPause && actIntLog)
                 uvsQuant();
             if(NetworkON) void_network_quant();
             if(!iPause){
                 iFrameCount ++;
                 if(iFrameCount >= iFRAME_CYCLE){
                     iFrameFlag = 1;
                     iFrameCount = 0;
                 }
                 if(actIntLog) aci_iScreenQuant();
                 iScrDisp -> EventQuant();
                 if(actIntLog && !iScreenOffs) aciML_D -> flush();
                 if(actIntLog)
                     ipal_iter(iScreenOffs);
                 if(actIntLog && !iScreenOffs && aciBreathFlag){
                     iSoundQuant();
                 }
                 if(EventFlag){
                     i_postExtQuant();
                     EventFlag = 0;
                 }
                 if(iChatON) iChatQuant(1);
             }
             return 0;
         }
         if(iScrDisp -> ret_val == ACI_LOAD_CODE) aciLoadLog = 1;
         if(!actIntLog){
             iSaveControls();
             iSaveData();
         }
         return 1;
     }
     else {
         if(actIntLog && !iScreenOffs && acsScrD -> curScrID >= 3)
             ipal_iter(0);
         if(acsQuant()){
             iPause = 0;
             if(acsScrD -> curScrID >= 3){
                 aciCloseGate();
             }
             put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
             if(acsScrD -> curScrID >= 3){
                 aciOpenGate();
             }
             else
                 XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         }
         return 0;
     }
 }
References actIntLog, and iScrDisp.
Referenced by MainMenuRTO::Quant(), FirstEscaveRTO::Quant(), and EscaveRTO::Quant().
iregRender()
void iregRender (int x0, int y0, int x1, int y1)
 {
     LowX = iXCYCL(LowX);
     HiX = iXCYCL(HiX);
     LowY = iYCYCL(LowY);
     HiY = iYCYCL(HiY);
     LowX &= ~1;
     HiX |= 1;
     int SizeY = (LowY == HiY) ? iV_SIZE : iYCYCL(HiY - LowY);
     int SizeX = (0 == iXCYCL(HiX - LowX)) ? H_SIZE : iXCYCL(HiX - LowX);
     int BackScanLen = 0;
     int j;
     for(j = 0;j < SizeY;j++){
         const int y = iYCYCL(j + LowY);
         BYTE* pa0 = ivMap -> lineT[y];
         BYTE* pc0 = ivMap -> lineTcolor[y];
         if(!pa0) continue;
         MEMSET(ishadowParent,0,(((SizeX*SHADOWDEEP) >> POSPOWER) + 4*MAX_ALT));
         int hC = MAX_ALT;
         int LastStep = (H_SIZE - 1 - HiX) * SHADOWDEEP;
         LastStep -= ((LastStep >> POSPOWER) - MAX_ALT) << POSPOWER;
         //
         iPreStage(LastStep,HiX,pa0,hC,ishadowParent + MAX_ALT);
         //
         int x = HiX;
         BYTE* grid = ishadowParent + MAX_ALT + MAX_ALT;
         int MaxAlt = 0;
         iMainStage(pa0,hC,pc0,SizeX,x,grid,MaxAlt);
         //
         {
         x |= 1;
         BYTE* pa = pa0 + x;
         BYTE* pf = pa + H_SIZE;
         BYTE* pc = pc0 + x;
         BYTE* palCLRlast;
         BYTE* lightCLRlast;
         BYTE typeC = 0xFF;
         int MaxPossibleAlt = MAX_ALT;
         unsigned bNeedScan = 1;
         while(bNeedScan && MaxPossibleAlt >= 0){
             bNeedScan = 0;
             if(*pf & DOUBLE_LEVEL){
                 const BYTE lxVal = *pa;
                 const BYTE rxVal = *(pa0 + iXCYCL(x + 2));
                 const BYTE h = *pa;
                 const BYTE dh = *(pa - 1);
                 const BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 const BYTE level = h;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 grid += 3;
                 hC -= 3;
                 MaxAlt -= 3;
                 MaxPossibleAlt -= 3;
                 if(dh < MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *(pf - 1) |= SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *(pf - 1) &= ~SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 pa--; pf--; pc--;
                 if(*pf & SHADOW_MASK) bNeedScan = 1;
                 if(dh > hC){
                     MEMSET(grid + hC,1,dh - hC);
                     hC = dh;
                     }
                 MEMSET(grid + h - SS_WIDTH,1,SS_WIDTH + 1);
                 }
             else {
                 BYTE lxVal = *(pa - 1);
                 BYTE rxVal = *(pa0 + iXCYCL(x + 1));
                 BYTE h = *pa;
                 BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 BYTE level = h;
                 grid += 1;
                 hC -= 1;
                 MaxAlt -= 1;
                 MaxPossibleAlt -= 1;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 pa--; pf--; pc--;
                 rxVal = h;
                 h = lxVal;
                 lxVal = *(pa0 + iXCYCL(x - 2));
                 grid += 2;
                 hC -= 2;
                 MaxAlt -= 2;
                 MaxPossibleAlt -= 2;
                 type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
                 level = h;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = ipalCLR[type];
                     lightCLRlast = ilightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> SHADOW_CORRECTION)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 }
             if(x == 1){
                 x = H_SIZE - 1;
                 pa = pa0 + x;
                 pf = pa + H_SIZE;
                 pc = pc0 + x;
                 }
             else {
                 x = iXCYCL(x - 2);
                 pa--; pf--; pc--;
                 }
             }
         const int CurrScanLenght = iXCYCL(LowX - x);
         if(CurrScanLenght > BackScanLen) BackScanLen = CurrScanLenght;
         }
         }
 }
iSaveControls()
void iSaveControls (void)
 {
     if(!iControlsObj || RecorderMode) return;
     XStream fh("controls.dat",XS_OUT);
     fh < (int)iKEY_MAX_ID < (int)iKEY_OBJECT_SIZE;
     fh.write(iControlsObj -> keyCodes,iKEY_OBJECT_SIZE * iKEY_MAX_ID * sizeof(int));
     fh.close();
 }
References XStream::close(), iControlsObj, iKEY_MAX_ID, iKEY_OBJECT_SIZE, RecorderMode, XStream::write(), and XS_OUT.
iSaveData()
void iSaveData (void)
 {
 #ifndef _ACI_SKIP_MAINMENU_
     if(!RecorderMode){
         XStream fh("options.dat",XS_OUT);
         iScrDisp -> save_data(&fh);
 //      fh < aciAutoRun;
         fh < iGetOptionValue(iAUTO_ACCELERATION);
         fh.close();
     }
 #endif
 }
References XStream::close(), iAUTO_ACCELERATION, iGetOptionValue(), iScrDisp, RecorderMode, and XS_OUT.
Referenced by aciHandleCameraEvent(), and iFinitQuant().
iScrQuantFinit()
void iScrQuantFinit (void)
 {
     static unsigned char pal_buf[768];
     if(iScreenLog){
         iFinitQuant();
         set_key_nadlers(&KeyCenter, NULL);
         i_slake_pal(iscrPal,16);
         if(actintActiveFlag){
             i_getpal(pal_buf);
             i_change_res();
         }
         aciSendEvent2actint(EV_EVINCE_PALETTE,NULL);
     }
     actIntLog = 0;
 }
References aciSendEvent2actint(), actintActiveFlag, actIntLog, EV_EVINCE_PALETTE, i_change_res(), i_getpal(), i_slake_pal(), iFinitQuant(), iScreenLog, iscrPal, KeyCenter(), NULL, and set_key_nadlers().
Referenced by aci_LocationQuantFinit().
iScrQuantPrepare()
void iScrQuantPrepare (void)
 {
     actIntLog = 1;
     if(iScreenLog){
         iSecondInit();
         iQuantFirst();
         iQuantPrepare();
     }
 }
References actIntLog, iQuantFirst(), iQuantPrepare(), iScreenLog, and iSecondInit().
Referenced by aci_LocationQuantPrepare().
iSecondInit()
void iSecondInit (void)
 {
     ivMapPrepare();
     map_init();
     if(actIntLog)
         aciVMapPrepare();
     iScrDisp -> flags &= ~SD_EXIT;
 }
References aciVMapPrepare(), actIntLog, iScrDisp, ivMapPrepare(), and map_init().
Referenced by iPreInitFirst(), and iScrQuantPrepare().
iServersListDown()
void iServersListDown ()
 {
     int i;
     ServerFindChain* p = iFirstServerPtr;
     for(i = 0; i < ACI_NUM_SERVERS; i ++){
         if(p) p = p -> next;
     }
     if(p){
         iFirstServerPtr = p;
         iInitServersList();
     }
 }
References ACI_NUM_SERVERS, and iFirstServerPtr.
Referenced by iHandleExtEvent().
iServersListUp()
void iServersListUp ()
 {
     int i;
     ServerFindChain* p = iFirstServerPtr;
     for(i = 0; i < ACI_NUM_SERVERS; i ++){
         if(p) p = p -> prev;
     }
     if(p){
         iFirstServerPtr = p;
         iInitServersList();
     }
 }
References ACI_NUM_SERVERS, iFirstServerPtr, iInitServersList(), and prev.
Referenced by iHandleExtEvent().
iSetMultiGameParameters()
void iSetMultiGameParameters (void)
 {
     int value = 0;
     iCurMultiGame = my_server_data.GameType;
     switch(iCurMultiGame){
         case iMP_VAN_WAR:
             value = my_server_data.Van_War.InitialCash;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_INITIAL_CASH,value);
             value = my_server_data.Van_War.ArtefactsUsing;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_ARTEFACTS_USING,value);
             value = my_server_data.Van_War.InEscaveTime;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_IN_ESCAVE_TIME,value);
             value = my_server_data.Van_War.TeamMode;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_TEAM_MODE,value);
             value = my_server_data.Van_War.Nascency + 1;
             if(value > 3) value = 0;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_NASCENCY,value);
             value = my_server_data.Van_War.WorldAccess;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_ACCESS,value);
             value = my_server_data.Van_War.MaxKills;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_MAX_KILLS,value);
             value = my_server_data.Van_War.MaxTime;
             iSetMultiGameParameter(iMP_VAN_WAR,iMP_MAX_TIME,value);
             break;
         case iMP_MECHOSOMA:
             value = my_server_data.Mechosoma.InitialCash;
             iSetMultiGameParameter(iMP_MECHOSOMA,iMP_INITIAL_CASH,value);
             value = my_server_data.Mechosoma.ArtefactsUsing;
             iSetMultiGameParameter(iMP_MECHOSOMA,iMP_ARTEFACTS_USING,value);
             value = my_server_data.Mechosoma.InEscaveTime;
             iSetMultiGameParameter(iMP_MECHOSOMA,iMP_IN_ESCAVE_TIME,value);
             value = my_server_data.Mechosoma.TeamMode;
             iSetMultiGameParameter(iMP_MECHOSOMA,iMP_TEAM_MODE,value);
             value = my_server_data.Mechosoma.World;
             iSetMultiGameParameter(iMP_MECHOSOMA,iMP_WORLD,value);
             value = my_server_data.Mechosoma.ProductQuantity1;
             iSetMultiGameParameter(iMP_MECHOSOMA,iMP_QUANTITY1,value);
             value = my_server_data.Mechosoma.ProductQuantity2;
             iSetMultiGameParameter(iMP_MECHOSOMA,iMP_QUANTITY2,value);
             break;
         case iMP_PASSEMBLOSS:
             value = my_server_data.Passembloss.InitialCash;
             iSetMultiGameParameter(iMP_PASSEMBLOSS,iMP_INITIAL_CASH,value);
             value = my_server_data.Passembloss.ArtefactsUsing;
             iSetMultiGameParameter(iMP_PASSEMBLOSS,iMP_ARTEFACTS_USING,value);
             value = my_server_data.Passembloss.InEscaveTime;
             iSetMultiGameParameter(iMP_PASSEMBLOSS,iMP_IN_ESCAVE_TIME,value);
             value = my_server_data.Passembloss.CheckpointsNumber;
             iSetMultiGameParameter(iMP_PASSEMBLOSS,iMP_CHECKPOINTS_NUM,value);
             value = my_server_data.Passembloss.RandomEscave + 1;
             if(value > 3) value = 0;
             iSetMultiGameParameter(iMP_PASSEMBLOSS,iMP_ESCAVE,value);
             break;
         case iMP_HUNTAGE:
             value = my_server_data.Huntage.InitialCash;
             iSetMultiGameParameter(iMP_HUNTAGE,iMP_INITIAL_CASH,value);
             value = my_server_data.Huntage.ArtefactsUsing;
             iSetMultiGameParameter(iMP_HUNTAGE,iMP_ARTEFACTS_USING,value);
             value = my_server_data.Huntage.InEscaveTime;
             iSetMultiGameParameter(iMP_HUNTAGE,iMP_IN_ESCAVE_TIME,value);
             break;
         case iMP_MUSTODONT:
             value = my_server_data.Mustodont.InitialCash;
             iSetMultiGameParameter(iMP_MUSTODONT,iMP_INITIAL_CASH,value);
             value = my_server_data.Mustodont.ArtefactsUsing;
             iSetMultiGameParameter(iMP_MUSTODONT,iMP_ARTEFACTS_USING,value);
             value = my_server_data.Mustodont.InEscaveTime;
             iSetMultiGameParameter(iMP_MUSTODONT,iMP_IN_ESCAVE_TIME,value);
             value = my_server_data.Mustodont.TeamMode;
             iSetMultiGameParameter(iMP_MUSTODONT,iMP_TEAM_MODE,value);
             break;
     }
 }
References VAN_WAR_PRM::ArtefactsUsing, MECHOSOMA_PRM::ArtefactsUsing, PASSEMBLOSS_PRM::ArtefactsUsing, HUNTAGE_PRM::ArtefactsUsing, MUSTODONT_PRM::ArtefactsUsing, PASSEMBLOSS_PRM::CheckpointsNumber, ServerData::GameType, ServerData::Huntage, iCurMultiGame, iMP_ACCESS, iMP_ARTEFACTS_USING, iMP_CHECKPOINTS_NUM, iMP_ESCAVE, iMP_HUNTAGE, iMP_IN_ESCAVE_TIME, iMP_INITIAL_CASH, iMP_MAX_KILLS, iMP_MAX_TIME, iMP_MECHOSOMA, iMP_MUSTODONT, iMP_NASCENCY, iMP_PASSEMBLOSS, iMP_QUANTITY1, iMP_QUANTITY2, iMP_TEAM_MODE, iMP_VAN_WAR, iMP_WORLD, VAN_WAR_PRM::InEscaveTime, MECHOSOMA_PRM::InEscaveTime, PASSEMBLOSS_PRM::InEscaveTime, HUNTAGE_PRM::InEscaveTime, MUSTODONT_PRM::InEscaveTime, VAN_WAR_PRM::InitialCash, MECHOSOMA_PRM::InitialCash, PASSEMBLOSS_PRM::InitialCash, HUNTAGE_PRM::InitialCash, MUSTODONT_PRM::InitialCash, iSetMultiGameParameter(), VAN_WAR_PRM::MaxKills, VAN_WAR_PRM::MaxTime, ServerData::Mechosoma, ServerData::Mustodont, my_server_data, VAN_WAR_PRM::Nascency, ServerData::Passembloss, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, PASSEMBLOSS_PRM::RandomEscave, VAN_WAR_PRM::TeamMode, MECHOSOMA_PRM::TeamMode, MUSTODONT_PRM::TeamMode, ServerData::Van_War, MECHOSOMA_PRM::World, and VAN_WAR_PRM::WorldAccess.
iShopForcedExit()
void iShopForcedExit (void)
 {
 /*
     if(iScrDisp -> ActiveEv){
         iScrDisp -> ActiveEv -> flags &= ~EV_ACTIVE;
         iScrDisp -> ActiveEv = NULL;
     }
     iScrDisp -> key_trap(AML_FORCED_EXIT_CODE);
 */
     iForcedExitFlag = 1;
 }
References iForcedExitFlag.
Referenced by dg_SendEvent().
iSoundQuant()
void iSoundQuant (int value = 0)
 {
     switch(value){
         case ACI_NOISE_SOUND:
             SOUND_NOISE();
             break;
         case ACI_SPEECH0_SOUND:
             SOUND_TALK0();
             break;
         case ACI_SPEECH1_SOUND:
             SOUND_TALK1();
             break;
         case ACI_SPEECH2_SOUND:
             SOUND_TALK2();
             break;
         case ACI_SPEECH3_SOUND:
             SOUND_TALK2();
             break;
         case ACI_WND_SOUND:
             SOUND_WINDOW();
             break;
         case ACI_GATE_SOUND:
             SOUND_GATE();
             break;
         case ACI_L0_OUTIN_SOUND:
         case ACI_L2_OUTIN_SOUND:
             SOUND_OUTIN();
             break;
         case ACI_L0_SWARM_SOUND:
         case ACI_L1_SWARM_SOUND:
             SOUND_SWARM();
             break;
         case ACI_L0_ANGRY_SOUND:
         case ACI_L1_ANGRY_SOUND:
         case ACI_L5_ANGRY_SOUND:
             SOUND_ANGRY();
             break;
         case ACI_L1_STEP0_SOUND:
         case ACI_L2_STEP_SOUND:
         case ACI_L3_STEP_SOUND:
         case ACI_L4_STEP_SOUND:
             SOUND_STEP();
             break;
         case ACI_L2_GETOUT_SOUND:
         case ACI_L3_GETOUT_SOUND:
         case ACI_L5_GETOUT_SOUND:
         case ACI_L6_GETOUT_SOUND:
             SOUND_GETOUT();
             break;
         case ACI_L4_HAND_SOUND:
             SOUND_HAND();
             break;
         case ACI_L5_SCRATCH_SOUND:
         case ACI_L6_SCRATCH_SOUND:
             SOUND_SCRATCH();
             break;
         case ACI_L5_CLAP_SOUND:
         case ACI_L6_CLAP_SOUND:
             SOUND_CLAP();
             break;
     }
 }
References ACI_GATE_SOUND, ACI_L0_ANGRY_SOUND, ACI_L0_OUTIN_SOUND, ACI_L0_SWARM_SOUND, ACI_L1_ANGRY_SOUND, ACI_L1_STEP0_SOUND, ACI_L1_SWARM_SOUND, ACI_L2_GETOUT_SOUND, ACI_L2_OUTIN_SOUND, ACI_L2_STEP_SOUND, ACI_L3_GETOUT_SOUND, ACI_L3_STEP_SOUND, ACI_L4_HAND_SOUND, ACI_L4_STEP_SOUND, ACI_L5_ANGRY_SOUND, ACI_L5_CLAP_SOUND, ACI_L5_GETOUT_SOUND, ACI_L5_SCRATCH_SOUND, ACI_L6_CLAP_SOUND, ACI_L6_GETOUT_SOUND, ACI_L6_SCRATCH_SOUND, ACI_NOISE_SOUND, ACI_SPEECH0_SOUND, ACI_SPEECH1_SOUND, ACI_SPEECH2_SOUND, ACI_SPEECH3_SOUND, ACI_WND_SOUND, SOUND_ANGRY, SOUND_CLAP, SOUND_GATE, SOUND_GETOUT, SOUND_HAND, SOUND_NOISE, SOUND_OUTIN, SOUND_SCRATCH, SOUND_STEP, SOUND_SWARM, SOUND_TALK0, SOUND_TALK1, SOUND_TALK2, and SOUND_WINDOW.
Referenced by aciML_Dispatcher::event_quant().
iStrLen()
int iStrLen (char * p, int f, int space)
iUnlockExit()
void iUnlockExit (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button01");
     if(p) p -> flags &= ~OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
iUnlockMultiGameParameters()
void iUnlockMultiGameParameters (void)
 {
     int i;
     for(i = 0; i < iMP_MAX_ID; i ++){
         iMP_Games[i] -> unblock();
     }
 }
References iMP_Games, and iMP_MAX_ID.
iUnlockShop()
void iUnlockShop (void)
 {
     iScreenObject* p = (iScreenObject*)iScrDisp -> curScr -> get_object("Button04");
     if(p) p -> flags &= ~OBJ_LOCKED;
 }
References iScrDisp.
Referenced by dg_SendEvent().
iUpdateMultiGameName()
void iUpdateMultiGameName (void)
 {
     char* name = NULL;
     switch(iCurMultiGame){
         case 0:
             name = iGetOptionValueCHR(iMPGAME0_ID);
             break;
         case 1:
             name = iGetOptionValueCHR(iMPGAME1_ID);
             break;
         case 2:
             name = iGetOptionValueCHR(iMPGAME2_ID);
             break;
         case 3:
             name = iGetOptionValueCHR(iMPGAME3_ID);
             break;
         case 4:
             name = iGetOptionValueCHR(iMPGAME4_ID);
             break;
     }
     if(!name) return;
     iSetOptionValueCHR(iCUR_MPGAME_ID,name);
 }
References iCUR_MPGAME_ID, iCurMultiGame, iGetOptionValueCHR(), iMPGAME0_ID, iMPGAME1_ID, iMPGAME2_ID, iMPGAME3_ID, iMPGAME4_ID, iSetOptionValueCHR(), and NULL.
iUpdateServersList()
void iUpdateServersList ()
 {
     avaible_servers.find_servers_in_the_internet(iGetOptionValueCHR(iHOST_NAME), iServerPort);
     iFirstServerPtr = avaible_servers.first();
     iInitServersList();
 }
References avaible_servers, ServersList::find_servers_in_the_internet(), XTList< Type >::first(), iFirstServerPtr, iGetOptionValueCHR(), iHOST_NAME, iInitServersList(), and iServerPort.
Referenced by iHandleExtEvent().
ivMapPrepare()
void ivMapPrepare (void)
 {
     if(!ivMap) ivMap = new ivrtMap;
     if(!actIntLog){
         if(lang() != RUSSIAN)
             ivMap -> load("resource/iscreen/mainmenu.ini");
         else
             ivMap -> load("resource/iscreen/mainmenu2.ini");
         }
     else {
         ivMap -> load(aci_ivMapName);
         }
     ivMap -> init();
 }
References aci_ivMapName, actIntLog, ivMap, lang(), and RUSSIAN.
Referenced by iSecondInit().
KeepCleanUp()
void KeepCleanUp (void)
 {
     PrmFile pFile;
     pFile.init(mapFName);
     int maxWorld = atoi(pFile.getAtom());
     int i;
     char* atom;
     char* buf = new char[256];
     XStream ff(0);
     int size = 0;
     for(i = 0;i < maxWorld;i++){
         atom = pFile.getAtom();
         atom = pFile.getAtom();
         GetTargetName(NULL);
         strcpy(buf,GetTargetName(atom));
         dictionary *dict_name = iniparser_load(buf);
         strcpy(buf, iniparser_getstring(dict_name,"Storage:File Name", NULL));
         strcat(buf,".vmt");
         if(ff.open(GetTargetName(buf))){
             ff.close();
             remove(GetTargetName(buf));
             }
         }
     delete[] buf;
     pFile.finit();
     GetTargetName(NULL);
 }
References XStream::close(), PrmFile::finit(), PrmFile::getAtom(), GetTargetName(), iniparser_getstring(), iniparser_load(), PrmFile::init(), mapFName, NULL, and XStream::open().
Referenced by iKeepCleanUp().
KeyCenter()
void KeyCenter (SDL_Event * key)
 {
     extern int entry_scan_code;
     SDL_Keymod mod;
     if(aciKeyboardLocked) {
 #ifdef ACTINT
         aKeyTrap(key);
 #endif
         return;
     }
     entry_scan_code = sdlEventToCode(key);
     switch(entry_scan_code) {
         case SDL_SCANCODE_ESCAPE:
 #ifdef ESCAPE_EXIT
             disconnect_from_server();
             ErrH.Exit();
 #endif
             std::cout<<"road.KeyCenter:"<<key<<std::endl;
             if(!Pause) {
                 Pause = 1;
             }
 //                GameQuantReturnValue = RTO_LOADING3_ID;
             break;
 #ifndef ACTINT
         case SDL_SCANCODE_F1:
             curGMap -> change(-3,-2);
             break;
         case SDL_SCANCODE_F2:
             curGMap -> change(3,2);
             break;
 #endif
 #ifdef _DEBUG
         case SDL_SCANCODE_F12:
             DBGCHECK
             break;
 #endif
 #ifdef SCREENSHOT
 //          case SDL_SCANCODE_F4:
 //              creat_poster();
 //              break;
 //      case SDL_SCANCODE_F11:
 //          shotFlush();
 //          break;
 #endif
         case SDL_SCANCODE_T:
             mod = SDL_GetModState();
             if ((mod&KMOD_SHIFT)||(mod&KMOD_CTRL)) {
                 GameTimerON_OFF();
             }
             break;
         case SDL_SCANCODE_F:
             mod = SDL_GetModState();
             if (mod&KMOD_CTRL) {
                 curGMap -> prmFlag ^= PRM_FPS;
             }
 #ifdef _DEBUG
             else
                 message_mode++;
 #endif
             break;
         case SDL_SCANCODE_F5:
             if(!Pause){
                 camera_rotate_enable = 1 - camera_rotate_enable;
                 aciSetCameraMenu();
             }
             break;
         case SDL_SCANCODE_F6:
             if(!Pause){
                 camera_moving_xy_enable = 1 - camera_moving_xy_enable;
                 camera_moving_z_enable = 1 - camera_moving_z_enable;
                 aciSetCameraMenu();
             }
             break;
         case SDL_SCANCODE_F7:
             if(!Pause){
                 camera_slope_enable = 1 - camera_slope_enable;
                 aciSetCameraMenu();
             }
             break;
         }
     if (iKeyPressed(iKEY_ZOOM_IN)) {
         if(!Pause){
             if((camera_zmin -= 8) < curGMap -> xsize*MIN_ZOOM >> 8)
                 camera_zmin = curGMap -> xsize*MIN_ZOOM >> 8;
         }
     }
     if (iKeyPressed(iKEY_ZOOM_OUT)) {
         if(!Pause){
             if((camera_zmin += 8) > curGMap -> xsize*MAX_ZOOM >> 8)
                 camera_zmin = curGMap -> xsize*MAX_ZOOM >> 8;
         }
     }
     if (iKeyPressed(iKEY_ZOOM_STANDART)) {
         if(!Pause)
             camera_zmin = curGMap -> xsize;
     }
     if (iKeyPressed(iKEY_SCREENSHOT)) {
         shotFlush();
     }
 #ifdef ACTINT
     aKeyTrap(key);
 #endif
 }
References aciKeyboardLocked, aciSetCameraMenu(), aKeyTrap(), camera_moving_xy_enable, camera_moving_z_enable, camera_rotate_enable, camera_slope_enable, camera_zmin, curGMap, DBGCHECK, disconnect_from_server(), entry_scan_code, ErrH, XErrorHandler::Exit(), GameTimerON_OFF(), iKEY_SCREENSHOT, iKEY_ZOOM_IN, iKEY_ZOOM_OUT, iKEY_ZOOM_STANDART, iKeyPressed(), key(), MAX_ZOOM, message_mode, MIN_ZOOM, Pause, PRM_FPS, sdlEventToCode(), and shotFlush().
Referenced by LoadingRTO1::Init(), and iScrQuantFinit().
LoadingMessage()
void LoadingMessage (int flush = 0)
 {
     if(flush){
         char col255[3] = { 60,40,0 }; XGR_SetPal(col255,255,1);
         char col0[3] = { 0,0,0 }; XGR_SetPal(col0,0,1);
         XGR_Fill(0);
     }
     char* str = getRC();
     sysfont.draw(8,XGR_MAXY - 35,(unsigned char*)str,255,-1);
     XBuffer buf;
     if (lang() == RUSSIAN) {
         buf < Convert(zSTR_LOADING_800_RU);
     } else if (lang() == GERMAN) {
         if(XGR_MAXX == 800)
             buf < "(C)1997-2014. Alle Rechte vorbehalten. Release Version 1.3. Gleich geht's weiter...";
         else
             buf < "Spiel wird geladen. Gleich geht's weiter...";
     } else {
         buf < "(C)1997-2014 All Rights Reserved. Release Version 1.3 Loading. Please wait...";
     }
     int len = MAX(strlen(str),strlen(buf.GetBuf()));
     sysfont.draw(8,XGR_MAXY - 20,(unsigned char*)(buf.GetBuf()),255,-1);
     XGR_LineTo(8,XGR_MAXY - 45,len*8 + 5 + 16,2,255);
     XGR_LineTo(8 + len*8 + 11,XGR_MAXY - 45 - 7,2*7,3,255);
     //if(flush){
     //  XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     //}
 }
loadMouseFrames()
void loadMouseFrames (void)
 {
     XStream fh;
     if(actintLowResFlag)
         fh.open("resource/actint/640x480/mouse.bml",XS_IN);
     else
         fh.open("resource/actint/800x600/mouse.bml",XS_IN);
     fh > aMouseSizeX > aMouseSizeY > aMouseSize;
     aMouseFrames = new unsigned char[aMouseSizeX * aMouseSizeY * aMouseSize];
     fh.read(aMouseFrames,aMouseSizeX * aMouseSizeY * aMouseSize);
     fh.close();
     fh.open("resource/iscreen/mouse.bml");
     fh > iMouseSizeX > iMouseSizeY > iMouseSize;
     iMouseFrames = new unsigned char[iMouseSizeX * iMouseSizeY * iMouseSize];
     fh.read(iMouseFrames,iMouseSizeX * iMouseSizeY * iMouseSize);
     fh.close();
     MouseSize2 = iMouseSize/2;
 }
References actintLowResFlag, aMouseFrames, aMouseSize, aMouseSizeX, aMouseSizeY, XStream::close(), iMouseFrames, iMouseSize, iMouseSizeX, iMouseSizeY, MouseSize2, XStream::open(), XStream::read(), and XS_IN.
Referenced by aKeyInit(), and iInit().
map_init()
void map_init (void)
 {
     ivMap -> accept(0,I_RES_Y - 1);
 //  ivMap -> render(0,I_RES_Y - 1);
 }
References I_RES_Y, and ivMap.
Referenced by iSecondInit().
mem_putspr()
void mem_putspr (int x, int y, int sx, int sy, int bsx, int bsy, unsigned char * src, unsigned char * dest)
 {
     int i,j,index = 0,b_index = 0;
     index = x + y * bsx;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             if(src[b_index])
                 dest[index + j] = src[b_index];
             b_index ++;
         }
         index += bsx;
     }
 }
MS_init()
void MS_init (void)
 {
     set_mouse();
     XGR_MouseSetPressHandler(XGM_LEFT_BUTTON,iMS_LeftPress);
     XGR_MouseSetUnPressHandler(XGM_LEFT_BUTTON,iMS_LeftUnpress);
     XGR_MouseSetPressHandler(XGM_RIGHT_BUTTON,iMS_RightPress);
     XGR_MouseSetUnPressHandler(XGM_RIGHT_BUTTON,iMS_RightUnpress);
     XGR_MouseSetMoveHandler(iMS_Movement);
 }
References iMS_LeftPress(), iMS_LeftUnpress(), iMS_Movement(), iMS_RightPress(), iMS_RightUnpress(), set_mouse(), XGM_LEFT_BUTTON, XGM_RIGHT_BUTTON, XGR_MouseSetMoveHandler, XGR_MouseSetPressHandler, and XGR_MouseSetUnPressHandler.
Referenced by iQuantFirst().
put_buf()
void put_buf (int x, int y, int sx, int sy, unsigned char * buf, unsigned char * mask, int lev, int hide_mode)
 {
 //std::cout<<"put_buf "<<hide_mode<<std::endl;
     int i,j,index = 0;
     int t,m;
     unsigned char** lta = ivMap -> lineT;
     int yy,xx;
     switch(hide_mode){
         case 0:
             for(j = 0; j < sy; j ++){
                 yy = iYCYCL(y + j);
                 for(i = 0; i < sx; i ++){
                     xx = iXCYCL(x + i);
                     t = buf[index] - HFONT_NULL_LEVEL;
                     m = mask[index] - HFONT_NULL_LEVEL;
                     if(t || m){
                         t += lev;
                         if(t < 0) t = 0;
                         else if(t > 255) t = 255;
                         lta[yy][xx] = t;
                     }
                     index ++;
                 }
             }
             break;
         case 1:
             for(j = 0; j < sy; j ++){
                 yy = iYCYCL(y + j);
                 for(i = 0; i < sx; i ++){
                     xx = iXCYCL(x + i);
                     t = buf[index] - HFONT_NULL_LEVEL;
                     if(t){
                         t += lev;
                         if(t < 0) t = 0;
                         else if(t > 255) t = 255;
                         lta[yy][xx] = t;
                     }
                     index ++;
                 }
             }
             break;
         case 2:
             for(j = 0; j < sy; j ++){
                 yy = iYCYCL(y + j);
                 for(i = 0; i < sx; i ++){
                     xx = iXCYCL(x + i);
                     t = buf[index] - HFONT_NULL_LEVEL;
                     t += lev;
                     if(t < 0) t = 0;
                     else if(t > 255) t = 255;
                     lta[yy][xx] = t;
                     index ++;
                 }
             }
             break;
     }
 }
put_fon()
void put_fon (int x, int y, int sx, int sy, unsigned char * buf)
 {
     int j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     for(j = 0; j < sy; j ++){
         memcpy(lta[y + j] + x,buf + index,sx);
         index += sx;
     }
 }
put_level()
void put_level (int x, int y, int sx, int sy, int lev)
 {
     int i,j,index = 0;
     unsigned char** lta = ivMap -> lineT;
     int yy,xx;
     for(j = 0; j < sy; j ++){
         yy = iYCYCL(y + j);
         for(i = 0; i < sx; i ++){
             xx = iXCYCL(x + i);
             lta[yy][xx] = lev;
             index ++;
         }
     }
 }
put_map()
void put_map (int x, int y, int sx, int sy)
 {
     int j;
     unsigned char** ltc = ivMap -> lineTcolor;
     int yy,x0,x1,bsx,index;
     int scr_offs = iScreenOffs;
     x0 = x;
     x1 = x + sx;
     if(x0 < scr_offs) x0 = scr_offs;
     if(x1 >= scr_offs + I_RES_X) x1 = scr_offs + I_RES_X;
     bsx = x1 - x0;
     if(bsx > 0){
         index = (x0 - scr_offs) + y * XGR_MAXX;
         for(j = 0; j < sy; j ++){
             yy = iYCYCL(y + j);
             memcpy(XGR_VIDEOBUF + index,ltc[yy] + x0,bsx);
             index += XGR_MAXX;
         }
     }
 }
Referenced by aciCancelMatrix(), aciShowScMatrix(), aciSwapMatrices(), and iQuantFirst().
recorder_synchro()
void recorder_synchro (unsigned int frame)
RegisterValues()
void RegisterValues (void)
 {
     iScrollerElement* sl;
     iTriggerObject* trg;
     iScreen* scr;
     AVI_index = &aciCurMechosID;
     scr = (iScreen*)iScrDisp -> get_object("Options screen");
     if(!scr) return;
     trg = (iTriggerObject*)scr -> get_object("MemTrig");
     if(trg){
         iMemoryIndex = &trg -> state;
     }
     else
         iMemoryIndex = NULL;
     trg = (iTriggerObject*)scr -> get_object("LangTrig");
     if(trg){
         iLanguageIndex = &trg -> state;
     }
     else
         iLanguageIndex = NULL;
     trg = (iTriggerObject*)scr -> get_object("SndTrig");
     if(trg){
         iSoundIndex = &trg -> state;
     }
     else
         iSoundIndex = NULL;
     sl = (iScrollerElement*)scr -> get_object("VolumeScroller");
     if(sl){
         iSoundVolume = &sl -> Value;
         iSoundVolumeMax = &sl -> maxValue;
     }
     else {
         iSoundVolume = iSoundVolumeMax = NULL;
     }
 }
References aciCurMechosID, AVI_index, iLanguageIndex, iMemoryIndex, iScrDisp, iSoundIndex, iSoundVolume, iSoundVolumeMax, and NULL.
Referenced by iPreInitFirst(), and iQuantFirst().
restore_mouse_cursor()
void restore_mouse_cursor (void)
 {
     XGR_MouseSetCursor(MouseSizeX,MouseSizeY,MouseSize,MouseFrames);
     XGR_MouseSetSpot(MouseSizeX/2,0);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     XGR_MouseRedraw();
 }
References MouseFrames, MouseSize, MouseSizeX, MouseSizeY, XGM_NONE, XGR_MouseRedraw, XGR_MouseSetCursor, XGR_MouseSetSeq, and XGR_MouseSetSpot.
Referenced by actIntDispatcher::cancel_matrix(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), actIntDispatcher::put_in_slot(), and actIntDispatcher::put_item_xy().
scale_buf()
void scale_buf (int sx, int sy, int sc, unsigned char * p, unsigned char * p1)
 {
     int i,j,index = 0,t,t1;
     if(sc == 256){
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 p1[index] = p[index];
                 index ++;
             }
         }
     }
     else {
         for(i = 0; i < sy; i ++){
             for(j = 0; j < sx; j ++){
                 t = p[index] - HFONT_NULL_LEVEL;
                 t1 = (t * sc) >> 8;
                 p1[index] = t1 + HFONT_NULL_LEVEL;
                 index ++;
             }
         }
     }
 }
set_mouse()
void set_mouse (void)
 {
     XGR_MouseInit(XGR_MAXX/2,XGR_MAXY/2,MouseSizeX,MouseSizeY,MouseSize,MouseFrames);
     XGR_MouseSetSpot(MouseSizeX/2,0);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     iMouseLPressFlag = 0;
     iMouseRPressFlag = 0;
 }
References iMouseLPressFlag, iMouseRPressFlag, MouseFrames, MouseSize, MouseSizeX, MouseSizeY, XGM_NONE, XGR_MAXX, XGR_MAXY, XGR_MouseInit, XGR_MouseSetSeq, and XGR_MouseSetSpot.
Referenced by aKeyInit(), i_change_res(), and MS_init().
set_mouse_cursor()
void set_mouse_cursor (char * p, int sx, int sy)
 {
     XGR_MouseSetCursor(sx,sy,1,p);
     XGR_MouseSetSpot(sx/2,sy/2);
     XGR_MouseSetSeq(0,0,XGM_NONE,0);
     XGR_MouseRedraw();
 }
References XGM_NONE, XGR_MouseRedraw, XGR_MouseSetCursor, XGR_MouseSetSeq, and XGR_MouseSetSpot.
Referenced by actIntDispatcher::change_items(), actIntDispatcher::put_in_slot(), and actIntDispatcher::set_move_item().
SetSoundVolume()
void SetSoundVolume (int)
 {
     //std::cout<<"SetSoundVolume:"<<value<<std::endl;
     if(EffectInUsePriory){
 //      xsSetVolumeWAVE(value);
         soundVolumecurrent = soundVolume = value;
         //soundVolumecurrent = soundVolume = DB_MIN + round(log10(9.0*log(double(value))/(log(2.0)*8) + 1.0)*DB_SIZE);
     }
 }
Referenced by iHandleExtEvent().
shotFlush()
void shotFlush (void)
 {
     static int curShotNumber;
     XBuffer buf, out_buf;
     buf < "Vangers";
     if(curShotNumber < 1000)
         buf < "0";
     if(curShotNumber < 100)
         buf < "0";
     if(curShotNumber < 10)
         buf < "0";
     buf <= curShotNumber;
     while(true) {
         XBuffer buf2;
         buf2 = buf2 < buf.GetBuf() < ".bmp";
         std::fstream filestr(buf2.GetBuf(), std::ios::in);
         if (!filestr.is_open()) {
             out_buf = out_buf < buf2.GetBuf();
             break;
         }
         filestr.close();
         buf = buf < "v";
     }
     std::cout<<"ScreenShot name:"<<out_buf.GetBuf()<<std::endl;
     SDL_SaveBMP(XGR_Obj.XGR_ScreenSurface, out_buf.GetBuf());
     curShotNumber++;
 }
References XBuffer::GetBuf(), out_buf, XGR_Obj, and XGR_Screen::XGR_ScreenSurface.
Referenced by KeyCenter().
uvsQuant()
void uvsQuant (void)
                    {
 //  DBGCHECK;
 //_MEM_STATISTIC_("BEFOR uvsQuant -> ");
 //  uvsBunchCheck("Before Quant");
 //  uvsCheckAllItem();
     NetworkQuant();
     if (NetworkON && ConTimer.day == 1 && ConTimer.hour == 0 && ConTimer.min == 0 && ConTimer.sec == 0){
         uvsBunch* pb = (uvsBunch*)BunchTail;
         while(pb){
             sBunchCreate(pb -> id, pb -> Pescave -> Pworld -> gIndex,0,pb -> currentStage);
             pb = (uvsBunch*)pb -> next;
         }
 //      sBunchCreate(int& id,int world,int data);
         ConTimer.sec = 1;
     }
     if (!RND(1024) && NetworkON && uvsNetworkChangeWorld){
         if (Gamer -> Pworld -> gIndex < 3){
             uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
             pb -> cycleTable[pb -> currentStage].cirtQ++;
             sBunchSend(pb -> id, pb -> cycleTable[pb -> currentStage].cirtQ, pb -> currentStage);
         }//  end fi
     }//  end if
     if (!RND(1024) && !NetworkON && (Gamer -> status == UVS_VANGER_STATUS::IN_SHOP)){
         if (Gamer -> Pworld -> gIndex < 3){
             uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
             pb -> cycleTable[pb -> currentStage].cirtQ++;
         }//  end fi
     }//  end if
     uvsQuantFlag ^= 1;
     if (uvsQuantFlag &&  Gamer -> status == UVS_VANGER_STATUS::IN_SHOP) return;
     ConTimer.Quant();
     uvsElement* p;
     if(NetworkON) {
         Gamer -> Quant();
         listElem* l = BunchTail;
         while(l){
             ((uvsBunch*)l) -> Quant();
             l = l -> next;
         }
         //znfo HERE CALLED DOLLY QUANT in network game
         p = ETail;
         while(p){
             switch (p->type) {
             case UVS_OBJECT::DOLLY:
             //case UVS_OBJECT::VANGER:
             //case UVS_OBJECT::FLY_FARMER:
                 p->Quant();
             }
             p = p->enext;
         }
         return;
     }
     c_All_Number = c_S_Number = c_R_Number = c_A_Number = 0;
     for(int i = 0;i < EMU_MAX;i++){
         p = ETail;
         while(p){
             p -> emuQuant();
             p = p -> enext;
             }
         }
     p = ETail;
     while(p){
         p -> Quant();
         p = p -> enext;
         }
     listElem* l = BunchTail;
     while(l){
         ((uvsBunch*)l) -> Quant();
         l = l -> next;
         }
     l = WorldTail;
     while(l){
         ((uvsWorld*)l) -> Quant();
         l = l -> next;
         }
     uvsElement*& ip = deleteETail;
     while(ip){
         p = ip;
         ip = ip -> eprev;
         delete ((uvsVanger*)p);
         }
 //  uvsBunchCheck("After Quant");
 //  DBGCHECK;
 //_MEM_STATISTIC_("AFTER uvsQuant -> ");
 }
Referenced by iGameMap::draw().
Variable Documentation
aci_iScreenID
char* aci_iScreenID extern
Referenced by actIntDispatcher::i_init(), iPreInitFirst(), and iQuantFirst().
aciAutoRun
int aciAutoRun extern
Referenced by iLoadData().
aciBreathFlag
int aciBreathFlag extern
Referenced by aci_LocationQuantPrepare().
aciCurCredits07
int aciCurCredits07 = 0
Referenced by aciGetCurCredits(), and aciUpdateCurCredits().
aciLoadLog
int aciLoadLog extern
Referenced by aciFreeAll(), LoadingRTO2::Init(), and FirstEscaveRTO::Init().
aciML_ToolzerON
int aciML_ToolzerON extern
Referenced by iMS_LeftUnpress(), aciML_Dispatcher::quant(), and aciML_Dispatcher::startup().
acsScreenID
int acsScreenID extern
Referenced by acsQuant().
actintActiveFlag
int actintActiveFlag extern
Referenced by actIntQuant(), and iScrQuantFinit().
actIntLog
int actIntLog extern
Referenced by iFinitQuant(), iHandleExtEvent(), iKeyTrap(), iMS_LeftUnpress(), iMS_RightUnpress(), iOutEscaveFinit(), iOutEscaveInit(), iOutEscaveQuant(), iPreInitFirst(), iQuantFirst(), iQuantPrepare(), iQuantSecond(), iScrQuantFinit(), iScrQuantPrepare(), and iSecondInit().
actintLowResFlag
int actintLowResFlag extern
Referenced by loadMouseFrames().
actIntPal
unsigned char* actIntPal extern
aMouseFrames
unsigned char* aMouseFrames
Referenced by aciSet_aMouse(), and loadMouseFrames().
aMouseSize
short aMouseSize = 0
Referenced by aciSet_aMouse(), and loadMouseFrames().
aMouseSizeX
short aMouseSizeX = 0
Referenced by aciSet_aMouse(), and loadMouseFrames().
aMouseSizeY
short aMouseSizeY = 0
Referenced by aciSet_aMouse(), and loadMouseFrames().
aScrDisp
actIntDispatcher* aScrDisp extern
Referenced by aci_setMatrixBorder(), aci_setScMatrixBorder(), aciCancelMatrix(), aciCloseGate(), aciHideLocation(), aciOpenGate(), aciShowLocation(), aciShowLocationPicture(), aciShowScMatrix(), aciSwapMatrices(), getWID(), iHandleExtEvent(), iKeyTrap(), iOutEscaveInit(), iOutEscaveQuant(), and iPreInitFirst().
CurPlayerName
const char* CurPlayerName = "Vanger"
Referenced by iChatInputChar(), iQuantFirst(), iChatInputField::redraw(), and MessageDispatcher::send().
CurServerName
const char* CurServerName = "Server"
Referenced by iQuantFirst().
Dead
int Dead extern
DIBLog
int DIBLog
EffectInUse
int EffectInUse
EffectInUsePriory
int EffectInUsePriory extern
Referenced by iHandleExtEvent().
ExclusiveLog
int ExclusiveLog extern
Referenced by ComlineAnalyze(), i_change_res(), vrtMap::release(), and xtInitApplication().
HFntTable
HFont** HFntTable = NULL
Referenced by free_hfonts(), i_terrPutStr(), iInitText(), iScreenObject::init(), init_hfonts(), iStringElement::init_size(), iScreenDispatcher::input_string_quant(), iPutStr(), iPutStr2buf(), and iStrLen().
iAbortGameFlag
int iAbortGameFlag = 0
Referenced by EscaveOutRTO::Finit(), LoadingRTO3::Init(), EscaveOutRTO::Quant(), and FirstEscaveOutRTO::Quant().
iAbortGameMode
int iAbortGameMode = 1
Referenced by LoadingRTO3::Init(), EscaveOutRTO::Quant(), and FirstEscaveOutRTO::Quant().
iCDTrackLog
int iCDTrackLog = 0
iChatON
int iChatON extern
iControlsStr
iStringElement** iControlsStr extern
Referenced by iDeleteControl(), iDeleteControlKey(), iInitControlObjects(), iPrepareControls(), and iProcessControlsScreen().
iCurHall
int iCurHall = 0
Referenced by iHandleExtEvent(), and iPrepareHallOfFame().
iCurMultiGame
int iCurMultiGame extern
Referenced by iGetEscaveTime(), iGetMultiGameParameters(), iPreparePlayerResults(), iSetMultiGameParameters(), and iUpdateMultiGameName().
iCurServer
int iCurServer = 0
Referenced by iConnect2Server(), iCreateServer(), and iGetCurServer().
iEndGameFlag
int iEndGameFlag = 0
Referenced by iPreInitFirst(), and iQuantFirst().
iEscaveTimer
int iEscaveTimer = 0
Referenced by iPreInitFirst(), and iQuantFirst().
iEvLineID
int iEvLineID extern
Referenced by iCreateServer(), iPreInitFirst(), iQuantFirst(), and iScreenDispatcher::ProcessEvent().
iFirstInit
int iFirstInit = 0
Referenced by iInit(), iPreInitFirst(), and iQuantFirst().
iFirstServerPtr
ServerFindChain* iFirstServerPtr
Referenced by iConnect2Server(), iCreateServer(), iGetCurServer(), iHandleExtEvent(), iInitServersList(), iServersListDown(), iServersListUp(), and iUpdateServersList().
iFirstServerSearch
int iFirstServerSearch = 0
iForcedExitFlag
int iForcedExitFlag = 0
Referenced by iQuantPrepare(), and iShopForcedExit().
iFRAME_CYCLE
const int iFRAME_CYCLE = 10
iFrameCount
int iFrameCount = 0
iFrameFlag
int iFrameFlag = 0
Referenced by iScreenDispatcher::input_string_quant().
iMouseFrames
unsigned char* iMouseFrames
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseLPressFlag
int iMouseLPressFlag = 0
Referenced by actIntDispatcher::iKeyQuant(), iMS_LeftUnpress(), and set_mouse().
iMousePrevX
int iMousePrevX = 0
Referenced by actIntDispatcher::iKeyQuant().
iMousePrevY
int iMousePrevY = 0
Referenced by actIntDispatcher::iKeyQuant().
iMouseRPressFlag
int iMouseRPressFlag = 0
Referenced by iMS_RightUnpress(), and set_mouse().
iMouseSize
short iMouseSize = 0
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseSizeX
short iMouseSizeX = 0
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseSizeY
short iMouseSizeY = 0
Referenced by aciSet_iMouse(), and loadMouseFrames().
iMouseX
int iMouseX = 0
Referenced by aciCheckSellItem(), aciChooseShopItem(), aMS_LeftUnpress(), aMS_RightUnpress(), iScreen::CheckScanCode(), iScreenDispatcher::CheckScanCode(), actIntDispatcher::iKeyQuant(), iMS_LeftUnpress(), iMS_RightUnpress(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), aciML_Data::key_trap(), aciML_Dispatcher::key_trap(), actIntDispatcher::KeyQuant(), aciScreen::KeyTrap(), iScreenDispatcher::ProcessEvent(), and aciML_Dispatcher::quant().
iMouseY
int iMouseY = 0
Referenced by aciCheckSellItem(), aciChooseShopItem(), aMS_LeftUnpress(), aMS_RightUnpress(), iScreen::CheckScanCode(), iScreenDispatcher::CheckScanCode(), actIntDispatcher::iKeyQuant(), iMS_LeftUnpress(), iMS_RightUnpress(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), aciML_Data::key_trap(), aciML_Dispatcher::key_trap(), actIntDispatcher::KeyQuant(), aciScreen::KeyTrap(), iScreenDispatcher::ProcessEvent(), and aciML_Dispatcher::quant().
iMultiFlag
int iMultiFlag = 0
Referenced by aciInitEndGame(), iPreInitFirst(), and iQuantFirst().
iNumFonts
int iNumFonts = 1
Referenced by free_hfonts(), and init_hfonts().
iPause
int iPause = 0
Referenced by iHandleExtEvent(), and iKeyTrap().
iProxyPort
int iProxyPort = 1080
iProxyPortStrTerr
int iProxyPortStrTerr = -1
Referenced by iInitProxyOptions().
iProxyPortTerr
int iProxyPortTerr = -1
Referenced by iInitProxyOptions().
iProxyServer
char* iProxyServer = NULL
Referenced by ComlineAnalyze().
iProxyServerStrTerr
int iProxyServerStrTerr = -1
Referenced by iInitProxyOptions().
iProxyServerTerr
int iProxyServerTerr = -1
Referenced by iInitProxyOptions().
iProxyTerrFlag
int iProxyTerrFlag = 0
Referenced by iInitProxyOptions().
iProxyUsage
int iProxyUsage = 0
iResBuf
XBuffer* iResBuf
Referenced by iInit(), iInitKeepOptions(), iScreenObject::init(), iAVIElement::load(), iMultiResultString::redraw(), and iMultiGameParameter::set_value().
iScrDisp
iScreenDispatcher* iScrDisp extern
Referenced by aciCancelMatrix(), aciShowScMatrix(), aciSwapMatrices(), iFinitQuant(), iInit(), iInitServersList(), iKeyTrap(), iLoadData(), iLockExit(), iLockShop(), iMS_LeftPress(), iMS_Movement(), iMS_RightPress(), iPreInitFirst(), iPrepareSaveNames(), iQuantFirst(), iQuantPrepare(), iQuantSecond(), iSaveData(), iSecondInit(), iUnlockExit(), and iUnlockShop().
iScreenActive
int iScreenActive = 0
Referenced by iFinitQuant(), iHandleExtEvent(), and iQuantFirst().
iScreenChat
int iScreenChat extern
Referenced by iChatHistoryScreen::add_str(), iChatHistoryScreen::iChatHistoryScreen(), iChatInit(), and iChatInputField::iChatInputField().
iScreenLastInput
int iScreenLastInput extern
Referenced by iInitControlKey(), and iScreenDispatcher::input_string_quant().
iScreenLog
int iScreenLog = 0
Referenced by iScrQuantFinit(), and iScrQuantPrepare().
iScrFontTable
iScreenFont** iScrFontTable
Referenced by InitScreenFonts(), iPutS_Str(), and iS_StrLen().
iscrPal
uchar* iscrPal
Referenced by aciShowLocation(), aciShowLocationPicture(), actIntDispatcher::i_init(), LoadingRTO1::Init(), MainMenuRTO::Init(), and iScrQuantFinit().
iServerPort
int iServerPort = 2197
Referenced by iCreateServer(), iHandleExtEvent(), and iUpdateServersList().
iSlotNumber
int iSlotNumber = 0
Referenced by acsLoadData(), and iHandleExtEvent().
iStartupLog
int iStartupLog = 0
Referenced by iQuantFirst().
iSTR_All
const char* iSTR_All = iSTR_All1
Referenced by iChatInit(), and iInitStrings().
iSTR_BACKGROUND
const char* iSTR_BACKGROUND = iSTR_BACKGROUND1
Referenced by iChatInit(), and iInitStrings().
iSTR_Black
const char* iSTR_Black = iSTR_Black1
Referenced by iChatInit(), and iInitStrings().
iSTR_Blue
const char* iSTR_Blue = iSTR_Blue1
Referenced by iChatInit(), and iInitStrings().
iSTR_Camouflage
const char* iSTR_Camouflage = iSTR_Camouflage1
Referenced by iChatInit(), and iInitStrings().
iSTR_Checkpoints_Number
const char* iSTR_Checkpoints_Number = iSTR_Checkpoints_Number1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_CleanUp
const char* iSTR_CleanUp = iSTR_CleanUp1
Referenced by iInitKeepOptions(), and iInitStrings().
iSTR_CLEAR_LOG
const char* iSTR_CLEAR_LOG = iSTR_CLEAR_LOG1
Referenced by iChatInit(), and iInitStrings().
iSTR_COLOR_BLACK_CHAR
const char* iSTR_COLOR_BLACK_CHAR = iSTR_COLOR_BLACK_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_BLUE_CHAR
const char* iSTR_COLOR_BLUE_CHAR = iSTR_COLOR_BLUE_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_CAMOUFLAGE_CHAR
const char* iSTR_COLOR_CAMOUFLAGE_CHAR = iSTR_COLOR_CAMOUFLAGE_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_GRAY_CHAR
const char* iSTR_COLOR_GRAY_CHAR = iSTR_COLOR_GRAY_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_GREEN_CHAR
const char* iSTR_COLOR_GREEN_CHAR = iSTR_COLOR_GREEN_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_ORANGE_CHAR
const char* iSTR_COLOR_ORANGE_CHAR = iSTR_COLOR_ORANGE_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_PATROL_CHAR
const char* iSTR_COLOR_PATROL_CHAR = iSTR_COLOR_PATROL_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_RED_CHAR
const char* iSTR_COLOR_RED_CHAR = iSTR_COLOR_RED_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_WHITE_CHAR
const char* iSTR_COLOR_WHITE_CHAR = iSTR_COLOR_WHITE_CHAR1
Referenced by iInitStrings().
iSTR_COLOR_YELLOW_CHAR
const char* iSTR_COLOR_YELLOW_CHAR = iSTR_COLOR_YELLOW_CHAR1
Referenced by iInitStrings().
iSTR_DefaultPassword
const char* iSTR_DefaultPassword = iSTR_DefaultPassword1
Referenced by iInitStrings(), and iQuantFirst().
iSTR_EMPTY_SLOT
const char* iSTR_EMPTY_SLOT = iSTR_EMPTY_SLOT1
Referenced by iInitStrings().
iSTR_Gray
const char* iSTR_Gray = iSTR_Gray1
Referenced by iChatInit(), and iInitStrings().
iSTR_Green
const char* iSTR_Green = iSTR_Green1
Referenced by iChatInit(), and iInitStrings().
iSTR_LEAVE_CHAT
const char* iSTR_LEAVE_CHAT = iSTR_LEAVE_CHAT1
Referenced by iChatInit(), and iInitStrings().
iSTR_MBytes
const char* iSTR_MBytes = iSTR_MBytes1
Referenced by iInitKeepOptions(), and iInitStrings().
iSTR_MP_1st_part_delivery
const char* iSTR_MP_1st_part_delivery = iSTR_MP_1st_part_delivery1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_2nd_part_delivery
const char* iSTR_MP_2nd_part_delivery = iSTR_MP_2nd_part_delivery1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Deaths
const char* iSTR_MP_Deaths = iSTR_MP_Deaths1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Deaths_rate
const char* iSTR_MP_Deaths_rate = iSTR_MP_Deaths_rate1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_DeathTimeMax
const char* iSTR_MP_DeathTimeMax = iSTR_MP_DeathTimeMax1
Referenced by iInitStrings().
iSTR_MP_DeathTimeMin
const char* iSTR_MP_DeathTimeMin = iSTR_MP_DeathTimeMin1
Referenced by iInitStrings().
iSTR_MP_Kills
const char* iSTR_MP_Kills = iSTR_MP_Kills1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Kills_rate
const char* iSTR_MP_Kills_rate = iSTR_MP_Kills_rate1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Max_checkpoint_time
const char* iSTR_MP_Max_checkpoint_time = iSTR_MP_Max_checkpoint_time1
Referenced by iInitStrings().
iSTR_MP_Max_delivery_time
const char* iSTR_MP_Max_delivery_time = iSTR_MP_Max_delivery_time1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Mechos_assembled_in
const char* iSTR_MP_Mechos_assembled_in = iSTR_MP_Mechos_assembled_in1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Mechos_frame
const char* iSTR_MP_Mechos_frame = iSTR_MP_Mechos_frame1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Min_checkpoint_time
const char* iSTR_MP_Min_checkpoint_time = iSTR_MP_Min_checkpoint_time1
Referenced by iInitStrings().
iSTR_MP_Min_delivery_time
const char* iSTR_MP_Min_delivery_time = iSTR_MP_Min_delivery_time1
Referenced by iInitStrings().
iSTR_MP_StolenWares
const char* iSTR_MP_StolenWares = iSTR_MP_StolenWares1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Total_time
const char* iSTR_MP_Total_time = iSTR_MP_Total_time1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Ware01_Delivery
const char* iSTR_MP_Ware01_Delivery = iSTR_MP_Ware01_Delivery1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Ware02_Delivery
const char* iSTR_MP_Ware02_Delivery = iSTR_MP_Ware02_Delivery1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MP_Wares_lost
const char* iSTR_MP_Wares_lost = iSTR_MP_Wares_lost1
Referenced by iInitStrings(), and iPreparePlayerResults().
iSTR_MUTE_ALL
const char* iSTR_MUTE_ALL = iSTR_MUTE_ALL1
Referenced by iChatInit(), and iInitStrings().
iSTR_NONE
const char* iSTR_NONE = iSTR_NONE1
Referenced by iDeleteControl(), iDeleteControlKey(), iInitStrings(), and iQuantFirst().
iSTR_Orange
const char* iSTR_Orange = iSTR_Orange1
Referenced by iChatInit(), and iInitStrings().
iSTR_Patrol
const char* iSTR_Patrol = iSTR_Patrol1
Referenced by iChatInit(), and iInitStrings().
iSTR_Red
const char* iSTR_Red = iSTR_Red1
Referenced by iChatInit(), and iInitStrings().
iSTR_SpaceInUse
const char* iSTR_SpaceInUse = iSTR_SpaceInUse1
Referenced by iInitKeepOptions(), and iInitStrings().
iSTR_White
const char* iSTR_White = iSTR_White1
Referenced by iChatInit(), and iInitStrings().
iSTR_WORLD_ARK_A_ZNOY_CHAR
const char* iSTR_WORLD_ARK_A_ZNOY_CHAR = iSTR_WORLD_ARK_A_ZNOY_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_BOOZEENA_CHAR
const char* iSTR_WORLD_BOOZEENA_CHAR = iSTR_WORLD_BOOZEENA_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_FOSTRAL_CHAR
const char* iSTR_WORLD_FOSTRAL_CHAR = iSTR_WORLD_FOSTRAL_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_GLORX_CHAR
const char* iSTR_WORLD_GLORX_CHAR = iSTR_WORLD_GLORX_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_HMOK_CHAR
const char* iSTR_WORLD_HMOK_CHAR = iSTR_WORLD_HMOK_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_KHOX_CHAR
const char* iSTR_WORLD_KHOX_CHAR = iSTR_WORLD_KHOX_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_NECROSS_CHAR
const char* iSTR_WORLD_NECROSS_CHAR = iSTR_WORLD_NECROSS_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_NONE_CHAR
const char* iSTR_WORLD_NONE_CHAR = iSTR_WORLD_NONE_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_THREALL_CHAR
const char* iSTR_WORLD_THREALL_CHAR = iSTR_WORLD_THREALL_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_WEEXOW_CHAR
const char* iSTR_WORLD_WEEXOW_CHAR = iSTR_WORLD_WEEXOW_CHAR1
Referenced by iInitStrings().
iSTR_WORLD_XPLO_CHAR
const char* iSTR_WORLD_XPLO_CHAR = iSTR_WORLD_XPLO_CHAR1
Referenced by iInitStrings().
iSTR_Yellow
const char* iSTR_Yellow = iSTR_Yellow1
Referenced by iChatInit(), and iInitStrings().
iTheEND
int iTheEND = 0
Referenced by dg_SendEvent().
iVideoPath
const char* iVideoPath = "resource/video/"
Referenced by aciInitAviID(), ShowImageRTO::Init(), iScreenObject::init(), iAVIElement::load(), PassageImageType::Open(), and SetupPath().
iVideoPathDefault
const char* iVideoPathDefault = "resource/video/"
Referenced by ShowImageRTO::Init(), iScreenObject::init(), iAVIElement::load(), and PassageImageType::Open().
KeepON
int KeepON extern
Referenced by vrtMap::accept(), vrtMap::delink(), vrtMap::dump_terrain(), vrtMap::fileLoad(), vrtMap::link(), vrtMap::linkC(), vrtMap::load(), vrtMap::reload(), vMapPrepare(), and vrtMap::~vrtMap().
MouseFrames
unsigned char* MouseFrames
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
MouseSize
short MouseSize = 0
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
MouseSize2
int MouseSize2 = 0
Referenced by loadMouseFrames().
MouseSizeX
short MouseSizeX = 0
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
MouseSizeY
short MouseSizeY = 0
Referenced by aciSet_aMouse(), aciSet_iMouse(), restore_mouse_cursor(), and set_mouse().
MusicON
int MusicON extern
Referenced by iHandleExtEvent(), LastSoundQuant(), LastStartWTRACK(), MainMenuSoundQuant(), PauseCDTRACK(), ResumeCDTRACK(), SlowCDTRACK(), SoundQuant(), StartCDTRACK(), StartWTRACK(), and StopCDTRACK().
MuteLog
int MuteLog extern
Referenced by iHandleExtEvent().
RecorderMode
int RecorderMode extern
Referenced by ComlineAnalyze(), iLoadData(), iSaveData(), and xtInitApplication().
SoundVolumeCD
int SoundVolumeCD extern
Referenced by iHandleExtEvent(), MainMenuSoundQuant(), and SoundQuant().
SoundVolumePanning
int SoundVolumePanning extern