Vangers: src/iscreen/iscreen_options.h File Reference
iscreen_options.h File Reference
Enumerations
enum iScreenOptionID {
iSOUND_ON, iSOUND_VOLUME_CUR, iSOUND_VOLUME_MAX, iMUSIC_ON,
iMUSIC_VOLUME_CUR, iMUSIC_VOLUME_MAX, iTUTORIAL_ON, iDETAIL_SETTING,
iPLAYER_COLOR3, iPLAYER_COLOR, iSERVER_NAME, iSERVER_NAME2,
iPLAYER_PASSWORD, iMPGAME0_ID, iMPGAME1_ID, iMPGAME2_ID,
iMPGAME3_ID, iMPGAME4_ID, iCUR_MPGAME_ID, iCUR_MPGAME_ID2,
iPLAYER_NAME2, iSCREEN_RESOLUTION, iHOST_NAME, iKEEP_IN_USE,
iKEEP_CLEAN_UP, iKEEP_MODE, iPANNING_ON, iDESTR_MODE,
iPLAYER_COLOR2, iPLAYER_NAME3, iMECH_SOUND, iBACK_SOUND,
iJOYSTICK_TYPE, iPROXY_USAGE, iPROXY_SERVER, iPROXY_PORT,
iPROXY_SERVER_STR, iPROXY_PORT_STR, iSERVER_PORT, iPLAYER_NAME_CR,
iPLAYER_PASSWORD_CR, iIP_ADDRESS, iCAMERA_TURN, iCAMERA_SLOPE,
iCAMERA_SCALE, iFULLSCREEN, iAUTO_ACCELERATION, iMAX_OPTION_ID
}
enum iScreenOptionObjType {
iSCROLLER, iTRIGGER, iSTRING, iS_STRING,
iMAX_OPTION_OBJ_TYPE
}
Functions
int iGetOptionValue (int id)
void iSetOptionValue (int id, int val)
char * iGetOptionValueCHR (int id)
void iSetOptionValueCHR (int id, const char *p)
void iUpdateOptionValue (int id)
Enumeration Type Documentation
iScreenOptionID
enum iScreenOptionID
Enumerator
iSOUND_ON
iSOUND_VOLUME_CUR
iSOUND_VOLUME_MAX
iMUSIC_ON
iMUSIC_VOLUME_CUR
iMUSIC_VOLUME_MAX
iTUTORIAL_ON
iDETAIL_SETTING
iPLAYER_COLOR3
iPLAYER_COLOR
iSERVER_NAME
iSERVER_NAME2
iPLAYER_PASSWORD
iMPGAME0_ID
iMPGAME1_ID
iMPGAME2_ID
iMPGAME3_ID
iMPGAME4_ID
iCUR_MPGAME_ID
iCUR_MPGAME_ID2
iPLAYER_NAME2
iSCREEN_RESOLUTION
iHOST_NAME
iKEEP_IN_USE
iKEEP_CLEAN_UP
iKEEP_MODE
iPANNING_ON
iDESTR_MODE
iPLAYER_COLOR2
iPLAYER_NAME3
iMECH_SOUND
iBACK_SOUND
iJOYSTICK_TYPE
iPROXY_USAGE
iPROXY_SERVER
iPROXY_PORT
iPROXY_SERVER_STR
iPROXY_PORT_STR
iSERVER_PORT
iPLAYER_NAME_CR
iPLAYER_PASSWORD_CR
iIP_ADDRESS
iCAMERA_TURN
iCAMERA_SLOPE
iCAMERA_SCALE
iFULLSCREEN
iAUTO_ACCELERATION
iMAX_OPTION_ID
 {
     iSOUND_ON,          // 0
     iSOUND_VOLUME_CUR,      // 1
     iSOUND_VOLUME_MAX,      // 2
     iMUSIC_ON,          // 3
     iMUSIC_VOLUME_CUR,      // 4
     iMUSIC_VOLUME_MAX,      // 5
     iTUTORIAL_ON,           // 6
     iDETAIL_SETTING,        // 7
     iPLAYER_COLOR3,         // 8
     iPLAYER_COLOR,          // 9
     iSERVER_NAME,           // 10
     iSERVER_NAME2,          // 11
     iPLAYER_PASSWORD,       // 12
     iMPGAME0_ID,            // 13
     iMPGAME1_ID,            // 14
     iMPGAME2_ID,            // 15
     iMPGAME3_ID,            // 16
     iMPGAME4_ID,            // 17
     iCUR_MPGAME_ID,         // 18
     iCUR_MPGAME_ID2,        // 19
     iPLAYER_NAME2,          // 20
     iSCREEN_RESOLUTION,     // 21
     iHOST_NAME,         // 22
     iKEEP_IN_USE,           // 23
     iKEEP_CLEAN_UP,         // 24
     iKEEP_MODE,         // 25
     iPANNING_ON,            // 26
     iDESTR_MODE,            // 27
     iPLAYER_COLOR2,         // 28
     iPLAYER_NAME3,          // 29
     iMECH_SOUND,            // 30
     iBACK_SOUND,            // 31
     iJOYSTICK_TYPE,         // 32
     iPROXY_USAGE,           // 33
     iPROXY_SERVER,          // 34
     iPROXY_PORT,            // 35
     iPROXY_SERVER_STR,      // 36
     iPROXY_PORT_STR,        // 37
     iSERVER_PORT,           // 38
     iPLAYER_NAME_CR,        // 39
     iPLAYER_PASSWORD_CR,        // 40
     iIP_ADDRESS,            // 41
     iCAMERA_TURN,           // 42
     iCAMERA_SLOPE,          // 43
     iCAMERA_SCALE,          // 44
     iFULLSCREEN,            // 45
     iAUTO_ACCELERATION,         // 46
     iMAX_OPTION_ID
 };
iScreenOptionObjType
enum iScreenOptionObjType
Enumerator
iSCROLLER
iTRIGGER
iSTRING
iS_STRING
iMAX_OPTION_OBJ_TYPE
 {
     iSCROLLER,
     iTRIGGER,
     iSTRING,
     iS_STRING,
     iMAX_OPTION_OBJ_TYPE
 };
Function Documentation
iGetOptionValue()
int iGetOptionValue (int id)
 {
     if(iScrOpt && iScrOpt[id])
         return iScrOpt[id] -> GetValueINT();
     else
         return 1;
 }
iGetOptionValueCHR()
char* iGetOptionValueCHR (int id)
 {
     if(iScrOpt && iScrOpt[id])
         return iScrOpt[id] -> GetValueCHR();
     else
         return NULL;
 }
References iScrOpt, and NULL.
Referenced by aciGetPlayerName(), aciGetPlayerPassword(), iHandleExtEvent(), iQuantFirst(), iUpdateMultiGameName(), and iUpdateServersList().
iSetOptionValue()
void iSetOptionValue (int id, int val)
 {
     if(iScrOpt && iScrOpt[id])
         iScrOpt[id] -> SetValueINT(val);
 }
References iScrOpt.
iSetOptionValueCHR()
void iSetOptionValueCHR (int id, const char * p)
 {
     if(iScrOpt && iScrOpt[id])
         iScrOpt[id] -> SetValueCHR(p);
 }
References iScrOpt.
Referenced by iGetIP(), iHandleExtEvent(), iInitKeepOptions(), iQuantFirst(), and iUpdateMultiGameName().
iUpdateOptionValue()
void iUpdateOptionValue (int id)
 {
     if(iScrOpt && iScrOpt[id])
         iScrOpt[id] -> update();
 }
References iScrOpt.