Vangers: src/actint/item_api.h File Reference
item_api.h File Reference
Classes
struct actintItemData
struct aciPromptData
Macros
#define ACI_PROMPT_UP 0
#define ACI_PROMPT_CENTER 1
Enumerations
enum actintItemTypes {
ACI_MACHOTINE_GUN_LIGHT = 1, ACI_MACHOTINE_GUN_HEAVY, ACI_SPEETLE_SYSTEM_LIGHT, ACI_SPEETLE_SYSTEM_HEAVY,
ACI_GHORB_GEAR_LIGHT, ACI_GHORB_GEAR_HEAVY, ACI_BEEBBANOZA_BLOCKADE, ACI_CRUSTEST_CANNON,
ACI_TERMINATOR, ACI_TERMINATOR2, ACI_SPEETLE_SYSTEM_AMMO0, ACI_SPEETLE_SYSTEM_AMMO1,
ACI_CRUSTEST_CANNON_AMMO, ACI_COPTE_RIG, ACI_EMPTY_COPTE_RIG, ACI_CUTTE_RIG,
ACI_EMPTY_CUTTE_RIG, ACI_CROT_RIG, ACI_EMPTY_CROT_RIG, ACI_LHARK_DEVICE,
ACI_EMPTY_LHARK_DEVICE, ACI_RADAR_DEVICE, ACI_CIRTAINER, ACI_EMPTY_CIRTAINER,
ACI_CONLARVER, ACI_EMPTY_CONLARVER, ACI_NYMBOS, ACI_PHLEGMA,
ACI_HEROIN, ACI_SHRUB, ACI_POPONKA, ACI_TOXICK,
ACI_ELEECH, ACI_KERNOBOO, ACI_PIPETKA, ACI_WEEZYK,
ACI_PROTRACTOR, ACI_MECHANIC_MESSIAH, ACI_FUNCTION83, ACI_SPUMMY,
ACI_BOOT_SECTOR, ACI_PEELOT, ACI_LEEPURINGA, ACI_DEAD_ELEECH,
ACI_RUBOX, ACI_SANDOLL_PART1, ACI_SANDOLL_PART2, ACI_LAST_MOGGY_PART1,
ACI_LAST_MOGGY_PART2, ACI_QUEEN_FROG_PART1, ACI_QUEEN_FROG_PART2, ACI_LAWN_MOWER_PART1,
ACI_LAWN_MOWER_PART2, ACI_WORMASTER_PART1, ACI_WORMASTER_PART2, ACI_TANKACID,
ACI_AMPUTATOR, ACI_DEGRADATOR, ACI_MECHOSCOPE, ACI_GLUEK,
ACI_TABUTASK, ACI_ELEEPOD, ACI_BEEBOORAT, ACI_ZEEX,
ACI_PALOCHKA, ACI_PIPKA, ACI_NOBOOL, ACI_BOORAWCHIK,
ACI_PEREPONKA, ACI_ZEEFICK, ACI_TABUTASK_FAILED, ACI_TABUTASK_SUCCESSFUL,
ACI_EMPTY_AMPUTATOR, ACI_EMPTY_DEGRADATOR, ACI_EMPTY_MECHOSCOPE, ACI_ROTTEN_KERNOBOO,
ACI_ROTTEN_PIPETKA, ACI_ROTTEN_WEEZYK, ACI_MAX_TYPE
}
enum actintItemEvents {
ACI_PUT_ITEM = 1, ACI_DROP_ITEM, ACI_CHANGE_ITEM_DATA, ACI_ACTIVATE_ITEM,
ACI_DEACTIVATE_ITEM, ACI_GET_ITEM_DATA, ACI_CHECK_MOUSE, ACI_SET_DROP_LEVEL,
ACI_PUT_IN_SLOT, ACI_LOCK_INTERFACE, ACI_UNLOCK_INTERFACE, ACI_SHOW_TEXT,
ACI_HIDE_TEXT, ACI_SHOW_ITEM_TEXT, ACI_DROP_CONFIRM, ACI_MAX_EVENT
}
enum aciProtractorEvents {
ACI_PROTRACTOR_EVENT1 = 1, ACI_PROTRACTOR_EVENT2, ACI_PROTRACTOR_EVENT3, ACI_PROTRACTOR_EVENT4,
ACI_PROTRACTOR_EVENT5, ACI_PROTRACTOR_EVENT6, ACI_PROTRACTOR_EVENT7, ACI_PROTRACTOR_EVENT8,
ACI_MAX_PROTRACTOR_EVENT
}
enum aciMechMessiahEvents {
ACI_MECH_MESSIAH_EVENT1 = 1, ACI_MECH_MESSIAH_EVENT2, ACI_MECH_MESSIAH_EVENT3, ACI_MECH_MESSIAH_EVENT4,
ACI_MECH_MESSIAH_EVENT5, ACI_MECH_MESSIAH_EVENT6, ACI_MAX_MECH_MESSIAH_EVENT
}
enum GameOverStatus {
GAME_OVER_EXPLOSION = 1, GAME_OVER_INFERNAL_LOCKED, GAME_OVER_SPOBS_LOCKED, GAME_OVER_ALL_LOCKED,
GAME_OVER_LUCKY, GAME_OVER_LAMPASSO, GAME_OVER_ABORT, GAME_OVER_NETWORK
}
Functions
void aciSendEvent2actint (int code, actintItemData *p, int data=0)
void aciSendEvent2itmdsp (int code, actintItemData *p, int data=0)
char getObjectPosition (int &x, int &y)
actintItemData * aciGetLast (void)
int aciGetScreenItem (int x, int y)
int aciReInitItem (actintItemData *p)
int aciReInitItemXY (actintItemData *p, int x, int y)
void aciKillLinks (void)
void aciWorldLinksON (void)
void aciWorldLinksOFF (void)
void aciOpenWorldLink (int w1, int w2)
int aciWorldLinkExist (int w1, int w2, int sp_flag=1)
int uvs_aciKillItem (int id, int id1=-1)
int uvs_aciKillOneItem (int id, int x, int y)
void uvs_aciChangeItem (int id_from, int id_to)
void uvs_aciChangeOneItem (int id_from, int id_to, int x, int y)
void aciChangeItem (actintItemData *p)
void aciActivateItemFunction (int itemID, int fncID)
void aciDeactivateItemFunction (int itemID, int fncID)
int aciCheckItemPickUp (actintItemData *p)
void aciActionEvent (void)
int aciCheckSlot (void)
void aciGetItemCoords (actintItemData *p, int &x, int &y)
void aciGetItemCoords (int id, int &x, int &y)
int aciPutItem (int id, int x=-1, int y=-1)
void aciRemoveItem (actintItemData *d)
void aciNewMechos (int newID)
void aciSendPrompt (aciPromptData *p)
void aciAddTeleportMenuItem (int id, int fnc_id)
void aciDeleteTeleportMenuItem (int fnc_id)
void aciClearTeleportMenu (void)
char * aciGetPlayerName (void)
char * aciGetPlayerPassword (void)
int aciGetPlayerColor (void)
void aciRefreshTargetsMenu (void)
void aciPrepareText (char *ptr)
void aciDropMoveItem (void)
void SetWorldBeebos (int n)
void aciSetRedraw (void)
void aciPrepareEndImage (void)
void aciInitEndGame (int id)
int aciTextQuant (void)
char * aciLoadPackedFile (XStream &fh, int &sz)
void XpeditionOFF (int type)
void FakeOfMight (void)
void GetNetworkGameTime (int &day, int &hour, int &min, int &sec)
Variables
const int ACI_WEAPON = 0x01
const int ACI_ACTIVE = 0x02
int aciCurEnergy
int aciMaxEnergy
int aciMaxArmor
int aciCurArmor
int aciPickupItems
int aciPickupDevices
int aciRacingFlag
char * aciCurRaceType
char * aciCurRaceInfo
int aciGamerColor
const char * aci_curLocationName
int GameOverID
char * GameOverText
Macro Definition Documentation
ACI_PROMPT_CENTER
#define ACI_PROMPT_CENTER 1
ACI_PROMPT_UP
#define ACI_PROMPT_UP 0
Enumeration Type Documentation
aciMechMessiahEvents
enum aciMechMessiahEvents
Enumerator
ACI_MECH_MESSIAH_EVENT1
ACI_MECH_MESSIAH_EVENT2
ACI_MECH_MESSIAH_EVENT3
ACI_MECH_MESSIAH_EVENT4
ACI_MECH_MESSIAH_EVENT5
ACI_MECH_MESSIAH_EVENT6
ACI_MAX_MECH_MESSIAH_EVENT
 {
     ACI_MECH_MESSIAH_EVENT1 = 1,
     ACI_MECH_MESSIAH_EVENT2,
     ACI_MECH_MESSIAH_EVENT3,
     ACI_MECH_MESSIAH_EVENT4,
     ACI_MECH_MESSIAH_EVENT5,
     ACI_MECH_MESSIAH_EVENT6,
     ACI_MAX_MECH_MESSIAH_EVENT
 };
aciProtractorEvents
enum aciProtractorEvents
Enumerator
ACI_PROTRACTOR_EVENT1
ACI_PROTRACTOR_EVENT2
ACI_PROTRACTOR_EVENT3
ACI_PROTRACTOR_EVENT4
ACI_PROTRACTOR_EVENT5
ACI_PROTRACTOR_EVENT6
ACI_PROTRACTOR_EVENT7
ACI_PROTRACTOR_EVENT8
ACI_MAX_PROTRACTOR_EVENT
 {
     ACI_PROTRACTOR_EVENT1 = 1,
     ACI_PROTRACTOR_EVENT2,
     ACI_PROTRACTOR_EVENT3,
     ACI_PROTRACTOR_EVENT4,
     ACI_PROTRACTOR_EVENT5,
     ACI_PROTRACTOR_EVENT6,
     ACI_PROTRACTOR_EVENT7,
     ACI_PROTRACTOR_EVENT8,
     ACI_MAX_PROTRACTOR_EVENT
 };
actintItemEvents
enum actintItemEvents
Enumerator
ACI_PUT_ITEM
ACI_DROP_ITEM
ACI_CHANGE_ITEM_DATA
ACI_ACTIVATE_ITEM
ACI_DEACTIVATE_ITEM
ACI_GET_ITEM_DATA
ACI_CHECK_MOUSE
ACI_SET_DROP_LEVEL
ACI_PUT_IN_SLOT
ACI_LOCK_INTERFACE
ACI_UNLOCK_INTERFACE
ACI_SHOW_TEXT
ACI_HIDE_TEXT
ACI_SHOW_ITEM_TEXT
ACI_DROP_CONFIRM
ACI_MAX_EVENT
 {
     ACI_PUT_ITEM    = 1,
     ACI_DROP_ITEM,
     ACI_CHANGE_ITEM_DATA,
     ACI_ACTIVATE_ITEM,
     ACI_DEACTIVATE_ITEM,
     ACI_GET_ITEM_DATA,
     ACI_CHECK_MOUSE,
     ACI_SET_DROP_LEVEL,
     ACI_PUT_IN_SLOT,
     ACI_LOCK_INTERFACE,
     ACI_UNLOCK_INTERFACE,
     ACI_SHOW_TEXT,
     ACI_HIDE_TEXT,
     ACI_SHOW_ITEM_TEXT,
     ACI_DROP_CONFIRM,
     ACI_MAX_EVENT
 };
actintItemTypes
enum actintItemTypes
Enumerator
ACI_MACHOTINE_GUN_LIGHT
ACI_MACHOTINE_GUN_HEAVY
ACI_SPEETLE_SYSTEM_LIGHT
ACI_SPEETLE_SYSTEM_HEAVY
ACI_GHORB_GEAR_LIGHT
ACI_GHORB_GEAR_HEAVY
ACI_BEEBBANOZA_BLOCKADE
ACI_CRUSTEST_CANNON
ACI_TERMINATOR
ACI_TERMINATOR2
ACI_SPEETLE_SYSTEM_AMMO0
ACI_SPEETLE_SYSTEM_AMMO1
ACI_CRUSTEST_CANNON_AMMO
ACI_COPTE_RIG
ACI_EMPTY_COPTE_RIG
ACI_CUTTE_RIG
ACI_EMPTY_CUTTE_RIG
ACI_CROT_RIG
ACI_EMPTY_CROT_RIG
ACI_LHARK_DEVICE
ACI_EMPTY_LHARK_DEVICE
ACI_RADAR_DEVICE
ACI_CIRTAINER
ACI_EMPTY_CIRTAINER
ACI_CONLARVER
ACI_EMPTY_CONLARVER
ACI_NYMBOS
ACI_PHLEGMA
ACI_HEROIN
ACI_SHRUB
ACI_POPONKA
ACI_TOXICK
ACI_ELEECH
ACI_KERNOBOO
ACI_PIPETKA
ACI_WEEZYK
ACI_PROTRACTOR
ACI_MECHANIC_MESSIAH
ACI_FUNCTION83
ACI_SPUMMY
ACI_BOOT_SECTOR
ACI_PEELOT
ACI_LEEPURINGA
ACI_DEAD_ELEECH
ACI_RUBOX
ACI_SANDOLL_PART1
ACI_SANDOLL_PART2
ACI_LAST_MOGGY_PART1
ACI_LAST_MOGGY_PART2
ACI_QUEEN_FROG_PART1
ACI_QUEEN_FROG_PART2
ACI_LAWN_MOWER_PART1
ACI_LAWN_MOWER_PART2
ACI_WORMASTER_PART1
ACI_WORMASTER_PART2
ACI_TANKACID
ACI_AMPUTATOR
ACI_DEGRADATOR
ACI_MECHOSCOPE
ACI_GLUEK
ACI_TABUTASK
ACI_ELEEPOD
ACI_BEEBOORAT
ACI_ZEEX
ACI_PALOCHKA
ACI_PIPKA
ACI_NOBOOL
ACI_BOORAWCHIK
ACI_PEREPONKA
ACI_ZEEFICK
ACI_TABUTASK_FAILED
ACI_TABUTASK_SUCCESSFUL
ACI_EMPTY_AMPUTATOR
ACI_EMPTY_DEGRADATOR
ACI_EMPTY_MECHOSCOPE
ACI_ROTTEN_KERNOBOO
ACI_ROTTEN_PIPETKA
ACI_ROTTEN_WEEZYK
ACI_MAX_TYPE
 {
     // Weapons...
     ACI_MACHOTINE_GUN_LIGHT    = 1,
     ACI_MACHOTINE_GUN_HEAVY,
     ACI_SPEETLE_SYSTEM_LIGHT,
     ACI_SPEETLE_SYSTEM_HEAVY,
     ACI_GHORB_GEAR_LIGHT,
     ACI_GHORB_GEAR_HEAVY,
     ACI_BEEBBANOZA_BLOCKADE,
     ACI_CRUSTEST_CANNON,
     ACI_TERMINATOR,
     ACI_TERMINATOR2,
     // Ammo...
     ACI_SPEETLE_SYSTEM_AMMO0,
     ACI_SPEETLE_SYSTEM_AMMO1,
     ACI_CRUSTEST_CANNON_AMMO,
     // Devices...
     ACI_COPTE_RIG,          // Jumper...
     ACI_EMPTY_COPTE_RIG,        // Empty jumper...
     ACI_CUTTE_RIG,          // Sail device...
     ACI_EMPTY_CUTTE_RIG,        // Empty sail device...
     ACI_CROT_RIG,           // Wormer device...
     ACI_EMPTY_CROT_RIG,     // Empty wormer device...
     ACI_LHARK_DEVICE,       // Some device...
     ACI_EMPTY_LHARK_DEVICE,     // Some empty device...
     ACI_RADAR_DEVICE,
     // Items...
     ACI_CIRTAINER,          // Container for cirt...
     ACI_EMPTY_CIRTAINER,        // Empty container...
     ACI_CONLARVER,
     ACI_EMPTY_CONLARVER,
     // Wares...
     ACI_NYMBOS,         // Eleepod's eggs...
     ACI_PHLEGMA,            // Incubator slime...
     ACI_HEROIN,
     ACI_SHRUB,
     ACI_POPONKA,
     ACI_TOXICK,
     // Cultic units...
     ACI_ELEECH,         // Small eleepod...
     ACI_KERNOBOO,
     ACI_PIPETKA,
     ACI_WEEZYK,
     // Artefacts...
     ACI_PROTRACTOR,
     ACI_MECHANIC_MESSIAH,
     ACI_FUNCTION83,
     ACI_SPUMMY,
     ACI_BOOT_SECTOR,
     ACI_PEELOT,
     ACI_LEEPURINGA,         // Statue...
     ACI_DEAD_ELEECH,
     // Tokens...
     ACI_RUBOX,
     // Mehos parts...
     ACI_SANDOLL_PART1,
     ACI_SANDOLL_PART2,
     ACI_LAST_MOGGY_PART1,
     ACI_LAST_MOGGY_PART2,
     ACI_QUEEN_FROG_PART1,
     ACI_QUEEN_FROG_PART2,
     ACI_LAWN_MOWER_PART1,
     ACI_LAWN_MOWER_PART2,
     ACI_WORMASTER_PART1,
     ACI_WORMASTER_PART2,
     ACI_TANKACID,
     // Additional items...
     // Weapons...
     ACI_AMPUTATOR,
     ACI_DEGRADATOR,
     ACI_MECHOSCOPE,
     // Ammo...
     ACI_GLUEK,
     // Warez...
     ACI_TABUTASK,
     ACI_ELEEPOD,
     ACI_BEEBOORAT,
     ACI_ZEEX,
     // Personal Articles...
     ACI_PALOCHKA,
     ACI_PIPKA,
     ACI_NOBOOL,
     ACI_BOORAWCHIK,
     ACI_PEREPONKA,
     ACI_ZEEFICK,
     // Some more items...
     ACI_TABUTASK_FAILED,
     ACI_TABUTASK_SUCCESSFUL,
     ACI_EMPTY_AMPUTATOR,
     ACI_EMPTY_DEGRADATOR,
     ACI_EMPTY_MECHOSCOPE,
     ACI_ROTTEN_KERNOBOO,
     ACI_ROTTEN_PIPETKA,
     ACI_ROTTEN_WEEZYK,
     ACI_MAX_TYPE
 };
GameOverStatus
enum GameOverStatus
Enumerator
GAME_OVER_EXPLOSION
GAME_OVER_INFERNAL_LOCKED
GAME_OVER_SPOBS_LOCKED
GAME_OVER_ALL_LOCKED
GAME_OVER_LUCKY
GAME_OVER_LAMPASSO
GAME_OVER_ABORT
GAME_OVER_NETWORK
 {
     GAME_OVER_EXPLOSION = 1,
     GAME_OVER_INFERNAL_LOCKED,
     GAME_OVER_SPOBS_LOCKED,
     GAME_OVER_ALL_LOCKED,
     GAME_OVER_LUCKY,
     GAME_OVER_LAMPASSO,
     GAME_OVER_ABORT,
     GAME_OVER_NETWORK
 };
Function Documentation
aciActionEvent()
void aciActionEvent (void)
 {
     if(ActD.Active)
         ActD.Active->DoorFlag = 1;
 };
References ActD, ActionDispatcher::Active, and VangerUnit::DoorFlag.
Referenced by actIntDispatcher::EventQuant().
aciActivateItemFunction()
void aciActivateItemFunction (int itemID, int fncID)
 {
     fncMenu* m = NULL;
     invItem* p = aScrDisp -> get_item(itemID);
     if(p && p -> menu){
         m = (fncMenu*)p -> menu;
         m -> activate_item(fncID + 2000);
     }
     if(m && m -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         m -> set_redraw();
 }
References aScrDisp, and NULL.
Referenced by addInfernalsKill2Protractor(), addSpectorsKill2Messiah(), and ActionDispatcher::Open().
aciAddTeleportMenuItem()
void aciAddTeleportMenuItem (int id, int fnc_id)
 {
     const char* ptr;
     fncMenu* mn;
     fncMenuItem* itm;
     invMatrix* m;
     mn = aScrDisp -> get_menu(FMENU_TELEPORT_MENU);
     if(!mn) return;
     if(id == -1){
         ptr = aci_curLocationName;
     }
     else {
         m = aScrDisp -> get_matrix(id);
         ptr = m -> mech_name;
     }
     itm = aScrDisp -> alloc_menu_item();
     itm -> init_name(ptr);
     itm -> font = FMENU_TARGETS_FONT;
     itm -> space = FMENU_TARGETS_SPACE;
     itm -> fnc_code = fnc_id;
     itm -> flags |= FM_RANGE_FONT;
     itm -> init();
     mn -> add_item(itm);
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aci_curLocationName, aScrDisp, FMENU_TARGETS_FONT, FMENU_TARGETS_SPACE, and FMENU_TELEPORT_MENU.
Referenced by ObjectDestroy(), and GameObjectDispatcher::Quant().
aciChangeItem()
void aciChangeItem (actintItemData * p)
 {
     invItem* p1,*it;
     if(!aScrDisp -> curMatrix) return;
     if(!(aScrDisp -> flags & AS_ISCREEN))
         it = aScrDisp -> get_item(p -> type);
     else
         it = aScrDisp -> get_iitem(p -> type);
     p1 = (invItem*)p -> actintOwner;
     it -> clone(p1);
     if(!(aScrDisp -> flags & AS_ISCREEN) && aScrDisp -> curMode == AS_INV_MODE)
         aScrDisp -> curMatrix -> set_redraw();
 }
References aScrDisp, and curMatrix.
Referenced by aciSendEvent2itmdsp(), ChangeItemData(), ChangeTabutaskItem(), ChargeDevice(), VangerUnit::CheckOutDevice(), GunDevice::DeviceQuant(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), and uvsapiDestroyItem().
aciCheckItemPickUp()
int aciCheckItemPickUp (actintItemData * p)
 {
     invItem* itm = aScrDisp -> get_item(p -> type);
     if((itm -> classID == AS_ITEM_CLASS && aciPickupItems) || (itm -> classID == AS_WEAPON_CLASS && aciPickupDevices))
         return 1;
     return 0;
 }
References aciPickupDevices, aciPickupItems, AS_ITEM_CLASS, AS_WEAPON_CLASS, and aScrDisp.
Referenced by VangerUnit::CheckInDevice().
aciCheckSlot()
int aciCheckSlot (void)
 {
     if(!aScrDisp -> curMatrix) return 0;
     return aScrDisp -> curMatrix -> check_slot(AS_DEVICE_SLOT);
 }
References AS_DEVICE_SLOT, aScrDisp, and curMatrix.
aciClearTeleportMenu()
void aciClearTeleportMenu (void)
 {
     fncMenu* mn;
     fncMenuItem* p,*p1;
     mn = aScrDisp -> get_menu(FMENU_TELEPORT_MENU);
     if(!mn) return;
     p = (fncMenuItem*)mn -> items -> last;
     while(p){
         p1 = (fncMenuItem*)p -> prev;
         if(p -> fnc_code != FMENU_OFF){
             mn -> items -> dconnect((iListElement*)p);
             aScrDisp -> free_menu_item(p);
         }
         p = p1;
     }
     p = (fncMenuItem*)mn -> inactive_items -> last;
     while(p){
         p1 = (fncMenuItem*)p -> prev;
         if(p -> fnc_code != FMENU_OFF){
             mn -> inactive_items -> dconnect((iListElement*)p);
             aScrDisp -> free_menu_item(p);
         }
         p = p1;
     }
     mn -> prefix = NULL;
     mn -> postfix = NULL;
 }
References aScrDisp, FMENU_OFF, FMENU_TELEPORT_MENU, NULL, and prev.
Referenced by GeneralSystemClose(), and ObjectDestroy().
aciDeactivateItemFunction()
void aciDeactivateItemFunction (int itemID, int fncID)
 {
     fncMenu* m = NULL;
     invItem* p = aScrDisp -> get_item(itemID);
     if(p && p -> menu){
         m = (fncMenu*)p -> menu;
         m -> deactivate_item(fncID + 2000);
     }
     if(m && m -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         m -> set_redraw();
 }
References aScrDisp, and NULL.
Referenced by ActionDispatcher::Open().
aciDeleteTeleportMenuItem()
void aciDeleteTeleportMenuItem (int fnc_id)
 {
     fncMenu* m = aScrDisp -> get_menu(FMENU_TELEPORT_MENU);
     if(!m) return;
     m -> deactivate_item(fnc_id);
     if(m -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         m -> set_redraw();
 }
References aScrDisp, and FMENU_TELEPORT_MENU.
aciDropMoveItem()
void aciDropMoveItem (void)
 {
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         aciSendEvent2itmdsp(ACI_DROP_ITEM,aScrDisp -> curItem -> item_ptr);
         aScrDisp -> flags &= ~AS_INV_MOVE_ITEM;
         aScrDisp -> free_item(aScrDisp -> curItem);
     }
 }
References aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::Go2Universe(), and VangerUnit::OutCarNator().
aciGetItemCoords() [1/2]
void aciGetItemCoords (actintItemData * p, int & x, int & y)
 {
     invItem* itm = (invItem*)p -> actintOwner;
     x = itm -> MatrixX;
     y = itm -> MatrixY;
 }
Referenced by VangerUnit::Go2Universe(), and VangerUnit::OutCarNator().
aciGetItemCoords() [2/2]
void aciGetItemCoords (int id, int & x, int & y)
 {
     invItem* itm;
     if(!aScrDisp -> curMatrix) return;
     itm = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(itm){
         if(itm -> ID == id){
             x = itm -> MatrixX;
             y = itm -> MatrixY;
             return;
         }
         itm = (invItem*)itm -> prev;
     }
 }
References aScrDisp, curMatrix, and prev.
aciGetLast()
actintItemData* aciGetLast (void)
 {
     invItem* itm;
     invItem* p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     itm = p;
     while(p){
         if(p -> dropCount > itm -> dropCount)
             itm = p;
         p = (invItem*)p -> prev;
     }
     if(itm)
         return itm -> item_ptr;
     return NULL;
 }
References aScrDisp, curMatrix, NULL, and prev.
Referenced by VangerUnit::ItemQuant().
aciGetPlayerColor()
int aciGetPlayerColor (void)
 {
     return iGetOptionValue(iPLAYER_COLOR);
 }
References iGetOptionValue(), and iPLAYER_COLOR.
Referenced by VangerUnit::CreateVangerUnit(), and NetInit().
aciGetPlayerName()
char* aciGetPlayerName (void)
 {
     return iGetOptionValueCHR(iPLAYER_NAME2);
 }
References iGetOptionValueCHR(), and iPLAYER_NAME2.
Referenced by NetInit().
aciGetPlayerPassword()
char* aciGetPlayerPassword (void)
 {
     return iGetOptionValueCHR(iPLAYER_PASSWORD);
 }
References iGetOptionValueCHR(), and iPLAYER_PASSWORD.
Referenced by NetInit().
aciGetScreenItem()
int aciGetScreenItem (int x, int y)
 {
     BaseObject* p;
     BaseObject* mp;
     int tx,ty,dx,dy,l;
     int rz;
     mp = NULL;
     rz = -1;
     S2G(x,y,tx,ty);
     GeneralMousePoint = Vector(getDistX(tx,ViewX),getDistY(ty,ViewY),0);
     p = (BaseObject*)(ItemD.Tail);
     while(p){
 //      if(p->ID != ID_STUFF)
 //          ErrH.Abort("Bad STUFF List");
         if(p->Visibility == VISIBLE && p->R_curr.z > rz){
             dx = getDistX(tx,p->R_curr.x);
             dy = getDistY(ty,p->R_curr.y);
             l = p->radius + ACI_CHECK_RADIUS;
             if((dx*dx + dy*dy) < l*l){
                 mp = p;
                 rz = p->R_curr.z;
             };
         };
         p = (BaseObject*)(p->NextTypeList);
     };
     if(mp) return ((StuffObject*)(mp))->ActIntBuffer.type;
     return -1;
 };
References ACI_CHECK_RADIUS, GeneralMousePoint, getDistX(), getDistY(), ItemD, GeneralObject::NextTypeList, NULL, GeneralObject::R_curr, BaseObject::radius, S2G(), UnitList::Tail, ViewX, ViewY, BaseObject::Visibility, VISIBLE, Vector::x, Vector::y, and Vector::z.
Referenced by actIntDispatcher::inv_mouse_move_quant().
aciInitEndGame()
void aciInitEndGame (int id)
 {
     char* ptr;
     ShowImageRTO* p = (ShowImageRTO*)xtGetRuntimeObject(RTO_SHOW_IMAGE_ID);
     LoadingRTO3* lp = (LoadingRTO3*)xtGetRuntimeObject(RTO_LOADING3_ID);
 //  int sz;
 //  XStream fh;
     if(!aciImgText){
         aciImgText = new aciScreenText;
         aciImgText -> MaxStrLen = 55;
         aciImgText -> MaxPageStr = 19;
         aciImgText -> color = 239 | (1 << 16);
         aciImgText -> DeltaY = -2;
         aciImgText -> font = 3;
     }
     switch(GameOverID){
         case GAME_OVER_EXPLOSION:
             if(lang() == RUSSIAN)
                 p -> SetName("img/img7.bmp");
             else
                 p -> SetName("img/img0.bmp");
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_INFERNAL_LOCKED:
             p -> SetName("img/img1.bmp");
             ptr = dgD -> getInvText(DG_FINAL,3);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_SPOBS_LOCKED:
             p -> SetName("img/img2.bmp");
             ptr = dgD -> getInvText(DG_FINAL,4);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_ALL_LOCKED:
             p -> SetName("img/img3.bmp");
             ptr = dgD -> getInvText(DG_FINAL,5);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_LUCKY:
             p -> SetName("img/img4.bmp");
             ptr = dgD -> getInvText(DG_FINAL,2);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_LAMPASSO:
             p -> SetName("img/img5.bmp");
             ptr = dgD -> getInvText(DG_FINAL,1);
             if(ptr){
                 aciImgText -> alloc(ptr,strlen(ptr));
                 p -> SetFlag(0,IMG_RTO_SHOW_TEXT | IMG_RTO_KEEP_IMAGE);
             }
             p -> SetFlag(0,IMG_RTO_CDTRACK_TIME);
             break;
         case GAME_OVER_ABORT:
             lp -> SetNext(RTO_MAIN_MENU_ID);
             break;
         case GAME_OVER_NETWORK:
             iMultiFlag = 1;
             lp -> SetNext(RTO_MAIN_MENU_ID);
             break;
         default:
             lp -> SetNext(RTO_MAIN_MENU_ID);
             break;
     }
     p -> SetFlag(0,IMG_RTO_CD_IMAGE);
     GameOverID = 0;
 }
References aciImgText, DG_FINAL, dgD, GAME_OVER_ABORT, GAME_OVER_ALL_LOCKED, GAME_OVER_EXPLOSION, GAME_OVER_INFERNAL_LOCKED, GAME_OVER_LAMPASSO, GAME_OVER_LUCKY, GAME_OVER_NETWORK, GAME_OVER_SPOBS_LOCKED, GameOverID, IMG_RTO_CD_IMAGE, IMG_RTO_CDTRACK_TIME, IMG_RTO_KEEP_IMAGE, IMG_RTO_SHOW_TEXT, iMultiFlag, lang(), RTO_LOADING3_ID, RTO_MAIN_MENU_ID, RTO_SHOW_IMAGE_ID, RUSSIAN, and xtGetRuntimeObject().
Referenced by LoadingRTO3::Init().
aciKillLinks()
void aciKillLinks (void)
 {
     if(!aScrDisp -> curMatrix) return;
     invItem* p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         p -> item_ptr = NULL;
         p = (invItem*)p -> prev;
     }
 }
References aScrDisp, curMatrix, NULL, and prev.
Referenced by aci_LocationQuantFinit(), and VangerUnit::Go2Universe().
aciLoadPackedFile()
char* aciLoadPackedFile (XStream & fh, int & sz)
 {
     int sz;
     char *p,*ptr;
     sz = fh.size();
     p = new char[sz];
     fh.read(p,sz);
     out_sz = *(unsigned int*)(p + 2);
     long long_out_sz = out_sz;
     ptr = new char[out_sz];
     //ZIP_expand(ptr,out_sz,p,sz);
     /* ZLIB realisation (stalkerg)*/
     if(*(short*)(p)) { //if label = 0 not compress
         //std::cout<<"aciLoadPackedFile DeCompress "<<fh.file_name<<" file."<<std::endl;
         int stat = uncompress((Bytef*)ptr,(uLongf*)&long_out_sz,(Bytef*)(p+2+4),sz-2-4);
         switch(stat){
             //case Z_OK: std::cout<<"DeCompress ok."<<std::endl; break;
             case Z_MEM_ERROR: std::cout<<"DeCompress not enough memory."<<std::endl; break;
             case Z_BUF_ERROR: std::cout<<"DeCompress not enough room in the output buffer."<<std::endl; break;
             case Z_DATA_ERROR: std::cout<<"DeCompress error data."<<std::endl; break;
         };
     } else {
         memcpy(ptr, p + 2 + 4,(unsigned)(sz - 2 - 4));
     }
     delete[] p;
     return ptr;
 }
aciNewMechos()
void aciNewMechos (int newID)
 {
     if(aScrDisp -> curMatrix)
         aScrDisp -> free_matrix(aScrDisp -> curMatrix);
     if(newID != -1)
         aScrDisp -> curMatrix = aScrDisp -> alloc_matrix(newID);
     else
         aScrDisp -> curMatrix = NULL;
 }
References aScrDisp, curMatrix, and NULL.
Referenced by VangerUnit::ChangeVangerProcess(), and VangerUnit::Go2Universe().
aciOpenWorldLink()
void aciOpenWorldLink (int w1, int w2)
 {
     int id1,id2;
     aciWorldInfo* p1,*p2;
     id1 = aScrDisp -> wMap -> world_ids[w1];
     id2 = aScrDisp -> wMap -> world_ids[w2];
     if(id1 == -1 || id2 == -1) ErrH.Abort("Bad world ID...");
     p1 = aScrDisp -> wMap -> world_ptr[id1];
     p2 = aScrDisp -> wMap -> world_ptr[id2];
     if(!p1 || !p2) ErrH.Abort("Bad world ptr...");
     p1 -> links[id2] = 1;
     if(id1 != id2 && p2 -> links[id1]) p2 -> links[id1] = 0;
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
     aciPrevJumpCount = -1;
 }
aciPrepareEndImage()
void aciPrepareEndImage (void)
 {
     StopCDTRACK();
     ShowImageRTO* p;
     p = (ShowImageRTO*)xtGetRuntimeObject(RTO_SHOW_IMAGE_ID);
     p -> SetNumFiles(1);
     if(lang() == RUSSIAN)
         p -> SetName("img/img8.bmp",0);
     else
         p -> SetName("img/img6.bmp",0);
     p -> SetFlag(0,IMG_RTO_CD_IMAGE);
     p -> SetNext(XT_TERMINATE_ID);
 }
References IMG_RTO_CD_IMAGE, lang(), RTO_SHOW_IMAGE_ID, RUSSIAN, StopCDTRACK(), XT_TERMINATE_ID, and xtGetRuntimeObject().
Referenced by actIntDispatcher::flush(), and MainMenuRTO::Quant().
aciPrepareText()
void aciPrepareText (char * ptr)
 {
     int sz = strlen(ptr);
     aScrDisp -> ScrTextData -> alloc(ptr,sz);
     aScrDisp -> send_event(ACI_SHOW_TEXT);
 }
References ACI_SHOW_TEXT, and aScrDisp.
Referenced by aciSendEvent2itmdsp(), and DoorEngine::Quant().
aciPutItem()
int aciPutItem (int id, int x = -1, int y = -1)
 {
     invItem* p,*p1;
     if(aScrDisp -> flags & AS_ISCREEN)
         p1 = aScrDisp -> get_iitem(id);
     else
         p1 = aScrDisp -> get_item(id);
     if(!p1) ErrH.Abort("Bad aciPutItem() argument...");
     p = aScrDisp -> alloc_item();
     p1 -> clone(p);
     p -> item_ptr = NULL;
     if(aScrDisp -> curMatrix){
         if(x != -1){
             if(!aScrDisp -> put_item_xy(p,x,y,0)){
                 aScrDisp -> free_item(p);
                 return 0;
             }
         }
         else {
             if(!aScrDisp -> put_item_auto(p)){
                 aScrDisp -> free_item(p);
                 return 0;
             }
         }
         return 1;
     }
     aScrDisp->free_item(p);
     return 0;
 }
References aScrDisp.
Referenced by aciAddRubox(), aciGetRubox(), VangerUnit::Go2Universe(), and VangerUnit::Go2World().
aciRefreshTargetsMenu()
void aciRefreshTargetsMenu (void)
 {
     char* ptr;
     fncMenu* mn;
     mn = aScrDisp -> get_menu(FMENU_TARGETS_MENU);
     if(!mn) return;
     ptr = GetCompasTarget();
     if(ptr)
         mn -> curItem = mn -> get_obj(ptr);
     else
         mn -> curItem = mn -> get_obj(aciSTR_OFF);
     mn -> init_objects();
     if(mn -> flags & FM_ACTIVE && aScrDisp -> curMode == AS_INFO_MODE)
         mn -> set_redraw();
 }
References aciSTR_OFF, aScrDisp, FMENU_TARGETS_MENU, GetCompasTarget(), and init_objects().
Referenced by ClearPhantomTarget(), ClearTabutaskTarget(), CreatePhantomTarget(), CreateTabutaskTarget(), DeleteArtefactTarget(), VangerUnit::GamerOrderInit(), and ActionDispatcher::PromptQuant().
aciReInitItem()
int aciReInitItem (actintItemData * p)
 {
     int id;
     invItem* it = aScrDisp -> get_item_ptr(p -> type);
     if(!it) {
         std::cout<<"aciReInitItem !it p:"<<p<<std::endl;
         return 0;
     }
     it -> item_ptr = p;
     p -> actintOwner = it;
     if(it -> slotType != -1){
         id = aScrDisp -> curMatrix -> get_item_slot(it);
         if(id != -1)
             aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,p,id);
     }
     return 1;
 }
References ACI_ACTIVATE_ITEM, aciSendEvent2itmdsp(), aScrDisp, and curMatrix.
Referenced by VangerUnit::Go2World().
aciReInitItemXY()
int aciReInitItemXY (actintItemData * p, int x, int y)
 {
     int id;
     invItem* it = aScrDisp->get_item_ptr_xy(p->type, x, y);
     if(!it) {
         std::cout<<"aciReInitItemXY !it p:"<<p<<std::endl;
         return 0;
     }
     it -> item_ptr = p;
     p -> actintOwner = it;
     if(it -> slotType != -1){
         id = aScrDisp -> curMatrix -> get_item_slot(it);
         if(id != -1)
             aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,p,id);
     }
     return 1;
 }
References ACI_ACTIVATE_ITEM, aciSendEvent2itmdsp(), aScrDisp, curMatrix, actIntDispatcher::get_item_ptr_xy(), and actintItemData::type.
Referenced by VangerUnit::Go2World().
aciRemoveItem()
void aciRemoveItem (actintItemData * d)
 {
     aScrDisp -> remove_item(d);
 }
References aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::DestroyItem(), VangerUnit::DischargeItem(), VangerUnit::Go2Universe(), StuffObject::NetEvent(), StuffObject::NetOwnerQuant(), VangerUnit::OutCarNator(), GunSlot::Quant(), VangerFunctionType::Quant(), and uvsapiDestroyItem().
aciSendEvent2actint()
void aciSendEvent2actint (int code, actintItemData * p, int data = 0)
 {
     aScrDisp -> send_event(code,data,p);
 }
References aScrDisp.
Referenced by aciSendEvent2itmdsp(), GunSlot::Fire(), VangerUnit::InCarNator(), iScrQuantFinit(), VangerUnit::ItemQuant(), StuffObject::NetOwnerQuant(), VangerUnit::NewKeyHandler(), ItemsDispatcher::Quant(), DoorEngine::Quant(), VangerUnit::SensorQuant(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), and XpeditionOFF().
aciSendEvent2itmdsp()
void aciSendEvent2itmdsp (int code, actintItemData * p, int data = 0)
 {
     Vector vCheck;
     int i;
     int what,id;
     char* name_from;
     char* name_to;
     if(ActD.Active){
         switch(code){
             case ACI_DROP_ITEM:
                 ((VangerUnit*)(ActD.Active))->CheckOutDevice((StuffObject*)(p->stuffOwner));
                 ActD.CheckDevice((StuffObject*)(p->stuffOwner));
                 ((StuffObject*)(p->stuffOwner))->DeviceOut(ActD.Active->R_curr + Vector(0,0,ActD.Active->radius*3));
                 break;
             case ACI_ACTIVATE_ITEM:
                 switch(p->type){
                     case ACI_EMPTY_CIRTAINER:
                         if(ActD.Active->dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH)){
                             ActD.Active->uvsPoint->gatherCirt(ActD.Active->R_curr.x,ActD.Active->R_curr.y,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1);
                             p->type = uvsSetItemType(((StuffObject*)(p->stuffOwner))->uvsDeviceType,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1);
                             aciChangeItem(p);
                         };
                         break;
                     case ACI_CIRTAINER:
                         ((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0 = 0;
                         ((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1 = 0;
                         p->type = uvsSetItemType(((StuffObject*)(p->stuffOwner))->uvsDeviceType,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1);
                         aciChangeItem(p);
                         break;
                     case ACI_PEELOT:
                         if(ActD.Active->Status & SOBJ_AUTOMAT)
                             aiMessageQueue.Send(AI_MESSAGE_AUTOMATIC_OFF,0,0xff,0);
                         else
                             aiMessageQueue.Send(AI_MESSAGE_AUTOMATIC_ON,0,0xff,0);
                         ActD.Active->Status ^= SOBJ_AUTOMAT;
                         break;
                     case ACI_GLUEK:
                         (ActD.Active)->Armor += 10 << 16;
                         ObjectDestroy((StuffObject*)(p->stuffOwner));
                         (ActD.Active)->CheckOutDevice((StuffObject*)(p->stuffOwner));
                         ActD.CheckDevice((StuffObject*)(p->stuffOwner));
                         ((StuffObject*)(p->stuffOwner))->Storage->Deactive((StuffObject*)(p->stuffOwner));
                         (ActD.Active)->DelDevice((StuffObject*)(p->stuffOwner));
                         aciSendEvent2actint(ACI_DROP_ITEM,p);
                         break;
                     case ACI_TANKACID:
                         ObjectDestroy((StuffObject*)(p->stuffOwner));
                         for(i = 0;i < 3;i++){
                             vCheck = Vector(40,0,0)*DBM(i*PI / 3,Z_AXIS);
                             vCheck += ActD.Active->R_curr;
                             cycleTor(vCheck.x,vCheck.y);
                             MapD.CreateAcidSpot(vCheck,40,60,0,-16,40);
                         };
                         MapD.CreateAcidSpot(ActD.Active->R_curr,40,60,0,-16,40);
                         (ActD.Active)->CheckOutDevice((StuffObject*)(p->stuffOwner));
                         ActD.CheckDevice((StuffObject*)(p->stuffOwner));
                         ((StuffObject*)(p->stuffOwner))->Storage->Deactive((StuffObject*)(p->stuffOwner));
                         (ActD.Active)->DelDevice((StuffObject*)(p->stuffOwner));
                         aciSendEvent2actint(ACI_DROP_ITEM,p);
                         SOUND_ACID()
                         break;
                     default:
                         p->flags |= ACI_ACTIVE;
                         ActD.SlotIn(data,(StuffObject*)(p->stuffOwner));
                         break;
                 };
                 break;
             case ACI_DEACTIVATE_ITEM:
                 p->flags &= ~ACI_ACTIVE;
                 ActD.SlotOut((StuffObject*)(p->stuffOwner));
                 break;
             case ACI_SHOW_ITEM_TEXT:
                 if(p->type == ACI_TABUTASK_SUCCESSFUL){
                     RaceTxtBuff.init();
                     if(lang() == RUSSIAN){
 //GERMAN
                         RaceTxtBuff < uvsGetNameByID(p->data1 & 0xffff,i);
                         RaceTxtBuff < rFirstTabuTaskMessage;
                         RaceTxtBuff < rSecondTabuTaskMessage;
                         RaceTxtBuff <= TabuTable[p->data1 & 0xffff]->cash < "$";
 //ENGLISH
 /*
                         RaceTxtBuff < rFirstTabuTaskMessage;
                         RaceTxtBuff < uvsGetNameByID(p->data1 & 0xffff,i);
                         RaceTxtBuff < rSecondTabuTaskMessage;
                         RaceTxtBuff <= TabuTable[p->data1 & 0xffff]->cash < "$";*/
                     }else{
                         RaceTxtBuff < uvsGetNameByID(p->data1 & 0xffff,i);
                         RaceTxtBuff < FirstTabuTaskMessage;
                         RaceTxtBuff < SecondTabuTaskMessage;
                         RaceTxtBuff <= TabuTable[p->data1 & 0xffff]->cash < "$";
                     };
                     aciPrepareText(RaceTxtBuff.address());
                 }else{
                     if(uvsPrepareItemToDiagen(((StuffObject*)(p->stuffOwner))->uvsDeviceType,p->data0,p->data1,what,id,name_from,name_to))
                         aciPrepareText(dgD->getInvText(what,id,name_from,name_to));
                 };
                 break;
         };
     };
 };
References ACI_ACTIVATE_ITEM, ACI_ACTIVE, ACI_CIRTAINER, ACI_DEACTIVATE_ITEM, ACI_DROP_ITEM, ACI_EMPTY_CIRTAINER, ACI_GLUEK, ACI_PEELOT, ACI_SHOW_ITEM_TEXT, ACI_TABUTASK_SUCCESSFUL, ACI_TANKACID, aciChangeItem(), aciPrepareText(), aciSendEvent2actint(), ActD, ActionDispatcher::Active, XBuffer::address(), AI_MESSAGE_AUTOMATIC_OFF, AI_MESSAGE_AUTOMATIC_ON, aiMessageQueue, uvsTabuTaskType::cash, ActionDispatcher::CheckDevice(), cycleTor(), actintItemData::data0, actintItemData::data1, dgD, FirstTabuTaskMessage, actintItemData::flags, uvsVanger::gatherCirt(), DiagenDispatcher::getInvText(), GROUND_COLLISION, XBuffer::init(), lang(), MapD, ObjectDestroy(), PI, RaceTxtBuff, Object::radius, rFirstTabuTaskMessage, rSecondTabuTaskMessage, RUSSIAN, SecondTabuTaskMessage, aiMessageList::Send(), ActionDispatcher::SlotIn(), ActionDispatcher::SlotOut(), SOBJ_AUTOMAT, SOUND_ACID, actintItemData::stuffOwner, TabuTable, actintItemData::type, uvsGetNameByID(), uvsKernel::uvsPoint, uvsPrepareItemToDiagen(), uvsSetItemType(), WHEELS_TOUCH, Object::x, Vector::x, Object::y, Vector::y, and Z_AXIS.
Referenced by aciReInitItem(), aciReInitItemXY(), actIntDispatcher::change_items(), actIntDispatcher::deactivate_items(), actIntDispatcher::EventQuant(), actIntDispatcher::i_init(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), actIntDispatcher::put_in_slot(), actIntDispatcher::put_item(), actIntDispatcher::put_item_xy(), actIntDispatcher::reinit_items(), and actIntDispatcher::set_move_item().
aciSendPrompt()
void aciSendPrompt (aciPromptData * p)
 {
     aScrDisp -> curPrompt -> copy_data(p);
     aScrDisp -> curPrompt -> CurTimer = 0;
 }
References aScrDisp.
Referenced by aiPromptDominanceMessage(), aiPromptLuckMessage(), aiPromptTaskMessage(), NetCheckRemovePlayer(), and aiMessageType::Send().
aciSetRedraw()
void aciSetRedraw (void)
 {
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
     aciPrevJumpCount = -1;
 }
References aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), and PassageImageType::Hide().
aciTextQuant()
int aciTextQuant (void)
 {
     int ret = 0;
     ShowImageRTO* p = (ShowImageRTO*)xtGetRuntimeObject(RTO_SHOW_IMAGE_ID);
     if(aciImgText -> flags & ACI_TEXT_INIT){
         ret = 0;
         if(ShowImageMouseFlag || ShowImageKeyFlag){
             if(aciImgText -> flags & ACI_TEXT_END)
                 ret = 1;
             else {
                 aciImgText -> NextPage();
                 if(aciImgText -> flags & ACI_TEXT_END){
                     if(p -> imageData){
                         XGR_PutSpr(0,0,p -> imageSX,p -> imageSY,p -> imageData,XGR_BLACK_FON);
                     }
                     else {
                         XGR_Fill(0);
                     }
                     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
                 }
             }
             ShowImageMouseFlag = ShowImageKeyFlag = 0;
         }
         aciImgText -> Quant();
         if(!(aciImgText -> flags & ACI_TEXT_REDRAW)){
             if(p -> imageData){
                 XGR_PutSpr(0,0,p -> imageSX,p -> imageSY,p -> imageData,XGR_BLACK_FON);
             }
             else {
                 XGR_Fill(0);
             }
             aciImgText -> redraw();
             XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         }
     }
     else {
         if(ShowImageMouseFlag || ShowImageKeyFlag)
                 ret = 1;
     }
     return ret;
 }
References aciImgText, RTO_SHOW_IMAGE_ID, and xtGetRuntimeObject().
Referenced by ShowImageRTO::Quant().
aciWorldLinkExist()
int aciWorldLinkExist (int w1, int w2, int sp_flag = 1)
 {
     int id1,id2;
     aciWorldInfo* p1,*p2;
     id1 = aScrDisp -> wMap -> world_ids[w1];
     id2 = aScrDisp -> wMap -> world_ids[w2];
     if(id1 == -1 || id2 == -1) ErrH.Abort("Bad world ID...");
     p1 = aScrDisp -> wMap -> world_ptr[id1];
     p2 = aScrDisp -> wMap -> world_ptr[id2];
     if(!p1 || !p2) ErrH.Abort("Bad world ptr...");
     if(p1 -> links[id2] || p2 -> links[id1]){
         if(!sp_flag || (p1 -> flags & AS_ACCESSIBLE_WORLD || p2 -> flags & AS_ACCESSIBLE_WORLD)){
             return 1;
         }
     }
     return 0;
 }
aciWorldLinksOFF()
void aciWorldLinksOFF (void)
 {
     int i;
     aciWorldInfo* p;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p = aScrDisp -> wMap -> world_ptr[i];
         if(p){
             p -> flags &= ~AS_ACCESSIBLE_WORLD;
         }
     }
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
 }
References AS_MAX_WORLD, aScrDisp, and wMap.
Referenced by aciWorldMap::quant().
aciWorldLinksON()
void aciWorldLinksON (void)
 {
     int i,cur_id;
     aciWorldInfo* p,*p1;
     if(CurrentWorld == -1) return;
     cur_id = aScrDisp -> wMap -> world_ids[CurrentWorld];
     if(cur_id == -1) return;
     p = aScrDisp -> wMap -> world_ptr[cur_id];
     if(!p) return;
     for(i = 0; i < AS_MAX_WORLD; i ++){
         p1 = aScrDisp -> wMap -> world_ptr[i];
         if(i != cur_id && p1){
             if(p1 -> links[cur_id] || p -> links[i]){
                 p1 -> flags |= AS_ACCESSIBLE_WORLD;
             }
         }
         if(p1 && uvsReturnWorldGamerVisit(p1 -> uvsID)){
             p1 -> flags |= AS_EXPLORED_WORLD;
         }
     }
     aScrDisp -> wMap -> flags |= WMAP_REBUILD_PIC;
 }
References AS_MAX_WORLD, aScrDisp, CurrentWorld, and wMap.
Referenced by aciWorldMap::quant(), and VangerUnit::TouchSensor().
FakeOfMight()
void FakeOfMight (void)
 {
     if(uvsKronActive && ActD.Active){
         ActD.Active->Armor = ActD.Active->MaxArmor;
         ActD.Active->Energy = ActD.Active->MaxEnergy;
     };
 };
References ActD, ActionDispatcher::Active, uvsUnitType::Armor, uvsUnitType::Energy, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, and uvsKronActive.
GetNetworkGameTime()
void GetNetworkGameTime (int & day, int & hour, int & min, int & sec)
 {
     int t;
     t = age_of_current_game();
     sec = t  %  60;
     min = (t / 60) % 60;
     hour = (t / (60*60)) % 12;
     day = (t / (60*60*12)) % 30;
 };
References age_of_current_game, and min().
getObjectPosition()
char getObjectPosition (int & x, int & y)
 {
     char c;
         if(!actCurrentViewObject){
 #ifdef _DEBUG
             if(aiCutDominance >= 0){
 #else
 //#ifdef ZMOD_BETA
 //          if (1) {
 //#else
             if (!NetworkON && aiCutDominance >= 50) {
                 //znfo - dolly visibility
 //#endif //ZMOD_BETA
 #endif
                 if(!actCurrentViewDolly){
 #ifdef _DEBUG
                     if(!actCurrentViewStuff){
                         actCurrentViewStuff = (StuffObject*)(ItemD.Tail);
                         actCurrentViewObject = (VangerUnit*)(ActD.Tail);
                         if(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION)){
                             do{
                                 actCurrentViewObject = (VangerUnit*)(actCurrentViewObject)->NextTypeList;
                             }while(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION));
                         };
                         actCurrentViewDolly = (uvsDolly*)(DollyTail);
                         if(actCurrentViewDolly && (actCurrentViewDolly->Pworld->gIndex != CurrentWorld || actCurrentViewDolly->status)){
                             do{
                                 actCurrentViewDolly = (uvsDolly*)(actCurrentViewDolly->next);
                             }while(actCurrentViewDolly && (actCurrentViewDolly->Pworld->gIndex != CurrentWorld || actCurrentViewDolly->status));
                         };
                         return -1;
                     };
                     x = actCurrentViewStuff->R_curr.x;
                     y = actCurrentViewStuff->R_curr.y;
                     actCurrentViewStuff = (StuffObject*)(actCurrentViewStuff->NextTypeList);
                     return 3;
 #endif
                     actCurrentViewObject = (VangerUnit*)(ActD.Tail);
                     if(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION)){
                         do{
                             actCurrentViewObject = (VangerUnit*)(actCurrentViewObject)->NextTypeList;
                         }while(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION));
                     };
                     actCurrentViewDolly = (uvsDolly*)(DollyTail);
                     if(actCurrentViewDolly && (actCurrentViewDolly->Pworld->gIndex != CurrentWorld || actCurrentViewDolly->status)){
                         do{
                             actCurrentViewDolly = (uvsDolly*)(actCurrentViewDolly->next);
                         }while(actCurrentViewDolly && (actCurrentViewDolly->Pworld->gIndex != CurrentWorld || actCurrentViewDolly->status));
                     };
                     return -1;
                 };
                 x = actCurrentViewDolly->pos_x;
                 y = actCurrentViewDolly->pos_y;
                 switch(actCurrentViewDolly->biosNindex){
                     case 0:
                         c = 8;
                         break;
                     case 1:
                         c = 9;
                         break;
                     case 2:
                         c = 10;
                         break;
                 };
                 do{
                     actCurrentViewDolly = (uvsDolly*)(actCurrentViewDolly->next);
                 }while(actCurrentViewDolly && (actCurrentViewDolly->Pworld->gIndex != CurrentWorld || actCurrentViewDolly->status));
                 return c;
             }else{
                 actCurrentViewObject = (VangerUnit*)(ActD.Tail);
                 if(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION)){
                     do{
                         actCurrentViewObject = (VangerUnit*)(actCurrentViewObject)->NextTypeList;
                     }while(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION));
                 };
                 return -1;
             };
         };
         x = actCurrentViewObject->R_curr.x;
         y = actCurrentViewObject->R_curr.y;
         switch(actCurrentViewObject->ID){
             case ID_VANGER:
                 if(actCurrentViewObject->VangerRaceStatus != VANGER_RACE_NONE/* && aciRacingFlag*/){
 //                  actCurrentViewObject = (VangerUnit*)(actCurrentViewObject->NextTypeList);
                     do{
                         actCurrentViewObject = (VangerUnit*)(actCurrentViewObject)->NextTypeList;
                     }while(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION));
                     return 3;
                 };
                 switch(actCurrentViewObject->uvsPoint->Pmechos->color){
                     case 0:
                         c = 4;
                         break;
                     case 1:
                         c = 5;
                         break;
                     case 2:
                         c = 6;
                         break;
                     case 3:
                         c = 7;
                         break;
                     case 4:
                         c = 11;
                         break;
                     case 5:
                         c = 12;
                         break;
                     case 6:
                         c = 13;
                         break;
                     case 7:
                         c = 14;
                         break;
                     case 8:
                         c = 15;
                         break;
                     case 9:
                         c = 16;
                         break;
                     default:
                         c = 7;
                         break;
                 };
                 do{
                     actCurrentViewObject = (VangerUnit*)(actCurrentViewObject)->NextTypeList;
                 }while(actCurrentViewObject && (actCurrentViewObject->Status & SOBJ_WAIT_CONFIRMATION));
 //              actCurrentViewObject = (VangerUnit*)(actCurrentViewObject)->NextTypeList;
                 return c;
         };
 /*  else{
         if(!actCurrentViewObject){
             actCurrentViewObject = PhantomD.Tail;
             return -1;
         };
         x = actCurrentViewObject->R_curr.x;
         y = actCurrentViewObject->R_curr.y;
         actCurrentViewObject = actCurrentViewObject->NextTypeList;
         return 1;
     };*/
     return -1;
 };
References actCurrentViewDolly, actCurrentViewObject, actCurrentViewStuff, ActD, aiCutDominance, uvsDolly::biosNindex, uvsMechos::color, CurrentWorld, DollyTail, uvsWorld::gIndex, Object::ID, ID_VANGER, ItemD, NetworkON, listElem::next, uvsVanger::Pmechos, uvsTarget::pos_x, uvsTarget::pos_y, uvsDolly::Pworld, SOBJ_WAIT_CONFIRMATION, uvsDolly::status, UnitList::Tail, uvsKernel::uvsPoint, VANGER_RACE_NONE, VangerUnit::VangerRaceStatus, Object::x, and Object::y.
Referenced by show_map().
SetWorldBeebos()
void SetWorldBeebos (int n)
 {
     aiPutHotBug(n);
 };
References aiPutHotBug().
uvs_aciChangeItem()
void uvs_aciChangeItem (int id_from, int id_to)
 {
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     if(!(aScrDisp -> flags & AS_ISCREEN))
         it = aScrDisp -> get_item(id_to);
     else
         it = aScrDisp -> get_iitem(id_to);
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id_from){
             it -> clone(p);
         }
         p = p1;
     }
     aScrDisp -> curMatrix -> set_redraw();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id_from){
                 it -> clone(aScrDisp -> curItem);
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
         }
     }
     if(aScrDisp -> flags & AS_ISCREEN){
         if(!aScrDisp -> secondMatrix) return;
         p = (invItem*)aScrDisp -> secondMatrix -> items -> last;
         while(p){
             p1 = (invItem*)p -> prev;
             if(p -> ID == id_from){
                 it -> clone(p);
             }
             p = p1;
         }
         aScrDisp -> secondMatrix -> set_redraw();
     }
 }
References aScrDisp, and curMatrix.
uvs_aciChangeOneItem()
void uvs_aciChangeOneItem (int id_from, int id_to, int x, int y)
 {
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     if(!(aScrDisp -> flags & AS_ISCREEN))
         it = aScrDisp -> get_item(id_to);
     else
         it = aScrDisp -> get_iitem(id_to);
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id_from && p -> MatrixX == x && p -> MatrixY == y){
             it -> clone(p);
 //            if(p -> uvsDataPtr) ((uvsActInt*)p -> uvsDataPtr) -> type = id_to;
             return;
         }
         p = p1;
     }
     aScrDisp -> curMatrix -> set_redraw();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id_from && aScrDisp -> curItem -> MatrixX == x && aScrDisp -> curItem -> MatrixY == y){
                 it -> clone(aScrDisp -> curItem);
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
                 return;
         }
     }
     if(aScrDisp -> flags & AS_ISCREEN){
         if(!aScrDisp -> secondMatrix) return;
         p = (invItem*)aScrDisp -> secondMatrix -> items -> last;
         while(p){
             p1 = (invItem*)p -> prev;
             if(p -> ID == id_from && p -> MatrixX == x && p -> MatrixY == y){
                 it -> clone(p);
             }
             p = p1;
         }
         aScrDisp -> secondMatrix -> set_redraw();
     }
 }
uvs_aciKillItem()
int uvs_aciKillItem (int id, int id1 = -1)
 {
     int ret = 0;
     uvsActInt* u;
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return ret;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     if(id1 != -1){
         it = aScrDisp -> get_iitem(id1);
     }
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id){
             if(id1 == -1){
                 aScrDisp -> curMatrix -> remove_item(p);
                 aScrDisp -> free_item(p);
             }
             else {
                 it -> clone(p);
                 u = (uvsActInt*)p -> uvsDataPtr;
                 u -> type = it -> ID;
             }
             ret = 1;
         }
         p = p1;
     }
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id){
             if(id1 == -1){
                 aScrDisp -> free_item(aScrDisp -> curItem);
                 aScrDisp -> curItem = NULL;
                 aScrDisp -> flags ^= AS_INV_MOVE_ITEM;
                 restore_mouse_cursor();
             }
             else {
                 it -> clone(aScrDisp -> curItem);
                 u = (uvsActInt*)aScrDisp -> curItem -> uvsDataPtr;
                 u -> type = it -> ID;
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
             }
             ret = 1;
         }
     }
     aScrDisp -> curMatrix -> set_redraw();
     if((aScrDisp -> flags & AS_ISCREEN) && GCharItem && GCharItem -> type == id){
         aciML_D -> key_trap(AML_KEY,AML_KILL_ELEECH_CODE);
     }
     return ret;
 }
References aScrDisp, curMatrix, and prev.
Referenced by uvsBunch::end_harvest(), uvsBunch::end_race(), and uvsVanger::race_result().
uvs_aciKillOneItem()
int uvs_aciKillOneItem (int id, int x, int y)
 {
     int ret = 0;
     invItem* p,*p1;
     if(!aScrDisp -> curMatrix) return ret;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id && p -> MatrixX == x && p -> MatrixY == y){
             aScrDisp -> curMatrix -> remove_item(p);
             aScrDisp -> free_item(p);
             return 1;
         }
         p = p1;
     }
     return 0;
 }
XpeditionOFF()
void XpeditionOFF (int type)
 {
     if(uvsKronActive && ActD.Active){
         ActD.Active->ExternalMode = EXTERNAL_MODE_EARTH_IN;
         aciSendEvent2actint(ACI_LOCK_INTERFACE,NULL);
         ActD.Active->ExternalTime = ROTOR_PROCESS_LIFE_TIME;
         ActD.Active->CreateParticleRotor(ActD.Active->R_curr,ActD.Active->radius);
         camera_direct(ActD.Active->R_curr.x,ActD.Active->R_curr.y,1 << 7,0,0,ROTOR_PROCESS_LIFE_TIME + 1);
         PalCD.Set(CPAL_HIDE_PASSAGE,ROTOR_PROCESS_LIFE_TIME);
         ActD.Active->ExternalLock = 1;
         ActD.Active->ExternalDraw = 0;
         ActD.Active->ExternalObject = NULL;
         ActD.Active->switch_analysis(1);
         StopCDTRACK();
         switch(type){
             case GAME_OVER_INFERNAL_LOCKED:
                 ActD.ThreallDestroy = 1;
                 ActD.SpobsDestroy = 0;
                 break;
             case GAME_OVER_SPOBS_LOCKED:
                 ActD.ThreallDestroy = 0;
                 ActD.SpobsDestroy = 1;
                 break;
             case GAME_OVER_ALL_LOCKED:
                 ActD.ThreallDestroy = 1;
                 ActD.SpobsDestroy = 1;
                 break;
             case GAME_OVER_LUCKY:
                 ActD.LuckyFunction = 1;
                 ActD.ThreallDestroy = 0;
                 ActD.SpobsDestroy = 0;
                 break;
         };
     };
 };
References ACI_LOCK_INTERFACE, aciSendEvent2actint(), ActD, ActionDispatcher::Active, camera_direct(), CPAL_HIDE_PASSAGE, VangerUnit::CreateParticleRotor(), EXTERNAL_MODE_EARTH_IN, VangerUnit::ExternalDraw, VangerUnit::ExternalLock, VangerUnit::ExternalMode, VangerUnit::ExternalObject, VangerUnit::ExternalTime, GAME_OVER_ALL_LOCKED, GAME_OVER_INFERNAL_LOCKED, GAME_OVER_LUCKY, GAME_OVER_SPOBS_LOCKED, ActionDispatcher::LuckyFunction, NULL, PalCD, Object::radius, ROTOR_PROCESS_LIFE_TIME, PalConstructor::Set(), ActionDispatcher::SpobsDestroy, StopCDTRACK(), Object::switch_analysis(), ActionDispatcher::ThreallDestroy, uvsKronActive, Object::x, and Object::y.
Referenced by ActionDispatcher::FunctionQuant().
Variable Documentation
ACI_ACTIVE
const int ACI_ACTIVE = 0x02
Referenced by aciSendEvent2itmdsp().
aci_curLocationName
const char* aci_curLocationName extern
Referenced by aciAddTeleportMenuItem(), aciInitShopItems(), uvsBunch::begin_race(), uvsBunch::game_exit(), uvsVanger::get_shop(), actIntDispatcher::i_init(), uvsVanger::makeJump(), uvsVanger::prepare_shop(), uvsVanger::Quant(), uniVangPrepare(), uvsActIntSell(), uvsCloseQuant(), and uvsPassagerFromStatistic().
ACI_WEAPON
const int ACI_WEAPON = 0x01
aciCurArmor
int aciCurArmor extern
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciCurEnergy
int aciCurEnergy extern
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciCurRaceInfo
char* aciCurRaceInfo extern
aciCurRaceType
char* aciCurRaceType extern
Referenced by aciShowRacingPlace(), and ActionDispatcher::Quant().
aciGamerColor
int aciGamerColor extern
aciMaxArmor
int aciMaxArmor extern
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciMaxEnergy
int aciMaxEnergy extern
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), and aIndData::init().
aciPickupDevices
int aciPickupDevices extern
Referenced by actIntDispatcher::EventQuant().
aciPickupItems
int aciPickupItems extern
Referenced by actIntDispatcher::EventQuant().
aciRacingFlag
int aciRacingFlag extern
Referenced by actIntDispatcher::flush(), and ActionDispatcher::Quant().
GameOverID
int GameOverID extern
Referenced by aciInitEndGame(), aInit(), VangerUnit::Destroy(), dg_SendEvent(), uvsVanger::get_shop(), LoadingRTO3::Init(), and VangerUnit::SensorQuant().
GameOverText
char* GameOverText extern