Vangers: src/units/items.cpp File Reference
items.cpp File Reference
#include "../global.h"
#include "../lang.h"
#include "../3d/3d_math.h"
#include "../3d/3dgraph.h"
#include "../3d/3dobject.h"
#include "../3d/parser.h"
#include "../common.h"
#include "../sqexp.h"
#include "../backg.h"
#include "../actint/item_api.h"
#include "uvsapi.h"
#include "../network.h"
#include "../terra/vmap.h"
#include "../terra/world.h"
#include "../terra/render.h"
#include "../uvs/univang.h"
#include "../particle/particle.h"
#include "../particle/df.h"
#include "../particle/partmap.h"
#include "../particle/light.h"
#include "../dast/poly3d.h"
#include "track.h"
#include "hobj.h"
#include "moveland.h"
#include "items.h"
#include "sensor.h"
#include "effect.h"
#include "mechos.h"
#include "../sound/hsound.h"
#include "magnum.h"
Functions
void Item2ShopAction (int type)
void aciPrepareWorldsMenu (void)
void camera_impulse (int amplitude_8)
StuffObject * addDevice (int x, int y, int z, int device_type, int param1, int param2, VangerUnit *Owner, int cMode)
void CreateDestroyEffect (Vector &v, int crat_id, int def_id, int def_flag, int expl_id, int fire_id)
int Name2Int (char *name, const char *key[], int max)
int aciGetScreenItem (int x, int y)
void addFarmer (int x_pos, int y_pos, int x_speed, int y_speed, int corn_type, int corn, int time)
int uvsapiDestroyItem (int ind, int ind2)
void aiPromptTaskMessage (int l)
void aiPromptDominanceMessage (int d)
void aiPromptLuckMessage (int d)
void ShowTaskMessage (int l)
void ShowDominanceMessage (int d)
void ShowLuckMessage (int l)
void ChangeItemData (int d)
void ChangeTabutaskItem (int type, int status)
int aciGetScreenMechos (int x, int y)
Variables
int RAM16
iGameMap * curGMap
uchar * FireColorTable
const char DEBRIS_LIFE_TIME = 100
int AdvancedView
const int MAX_STUFF_SCATTER = 150
const int MAX_BULLET_ID = 8
const int MAX_STORAGE_NAME = 2
const char * BULLET_ID_NAME [MAX_BULLET_ID]
const int MAX_BULLET_TARGET_MODE_NAME = 6
const char * BULLET_TARGET_MODE_NAME [MAX_BULLET_TARGET_MODE_NAME]
const int MAX_BULLET_CONTROL_MODE_NAME = 9
const char * BULLET_CONTROL_MODE_NAME [MAX_BULLET_CONTROL_MODE_NAME]
const int BULLET_CONTROL_MODE_VALUE [MAX_BULLET_CONTROL_MODE_NAME] = {0,1,2,4,8,16,32,64,128}
const int MAX_BULLET_SHOW_ID_NAME = 7
const char * BULLET_SHOW_ID_NAME [MAX_BULLET_SHOW_ID_NAME]
Vector GeneralMousePoint
int SkyFarmerWayTableSize
SensorDataType * SkyFarmerWayTable
int WeaponWaitTime
int ProtoCryptTableSize [WORLD_MAX]
SensorDataType * ProtoCryptTable [WORLD_MAX]
const int ITEM_LUCK_RADIUS = 20
dastPoly3D DollyPoint
const int DEVICE_OUT_NORMAL = 70
const int BULLET_IMPULSE_POWER = 9 << 14
const int BULLET_IMPULSE_ARM = 5 << 16
int DevicetStorageID [MAX_DEVICE_TYPE] = {ITEM_GUN_DEVICE,ITEM_CHANGER,ITEM_OTHER}
const int ACI_CHECK_RADIUS = 1
const int MAX_DROP_SEED = 1
const int MAX_DROP_POINT = MAX_DROP_SEED*10
const int HORDE_PARTICLE_NUM = 200
const int HORDE_RADIUS_DELTA = 30
int GloryPlaceNum
GloryPlace * GloryPlaceData
int UsedCheckNum
aiRndType GloryRnd
aciPromptData aiMessageBuffer
uvsTabuTaskType ** TabuTable
Function Documentation
aciGetScreenItem()
int aciGetScreenItem (int x, int y)
 {
     BaseObject* p;
     BaseObject* mp;
     int tx,ty,dx,dy,l;
     int rz;
     mp = NULL;
     rz = -1;
     S2G(x,y,tx,ty);
     GeneralMousePoint = Vector(getDistX(tx,ViewX),getDistY(ty,ViewY),0);
     p = (BaseObject*)(ItemD.Tail);
     while(p){
 //      if(p->ID != ID_STUFF)
 //          ErrH.Abort("Bad STUFF List");
         if(p->Visibility == VISIBLE && p->R_curr.z > rz){
             dx = getDistX(tx,p->R_curr.x);
             dy = getDistY(ty,p->R_curr.y);
             l = p->radius + ACI_CHECK_RADIUS;
             if((dx*dx + dy*dy) < l*l){
                 mp = p;
                 rz = p->R_curr.z;
             };
         };
         p = (BaseObject*)(p->NextTypeList);
     };
     if(mp) return ((StuffObject*)(mp))->ActIntBuffer.type;
     return -1;
 };
References ACI_CHECK_RADIUS, GeneralMousePoint, getDistX(), getDistY(), ItemD, GeneralObject::NextTypeList, NULL, GeneralObject::R_curr, BaseObject::radius, S2G(), UnitList::Tail, ViewX, ViewY, BaseObject::Visibility, VISIBLE, Vector::x, Vector::y, and Vector::z.
Referenced by actIntDispatcher::inv_mouse_move_quant().
aciGetScreenMechos()
int aciGetScreenMechos (int x, int y)
 {
 //  BaseObject* p;
 //  BaseObject* mp;
     int tx,ty,dx,dy,l;
 //  Vector vCheck;
 //  mp = NULL;
     S2G(x,y,tx,ty);
 //  vCheck = Vector(getDistX(tx,ViewX),getDistY(ty,ViewY),0);
 /*  p = (BaseObject*)(ActD.Tail);
     while(p){
         if(p->Visibility == VISIBLE){
             dx = getDistX(tx,p->R_curr.x);
             dy = getDistY(ty,p->R_curr.y);
             l = p->radius + ACI_CHECK_RADIUS;
             if((dx*dx + dy*dy) < l*l){
                 mp = p;
                 return 1;
             };
         };
         p = (BaseObject*)(p->NextTypeList);
     };*/
     if(ActD.Active){
         dx = getDistX(tx,ActD.Active->R_curr.x);
         dy = getDistY(ty,ActD.Active->R_curr.y);
         l = ActD.Active->radius + ACI_CHECK_RADIUS;
         if((dx*dx + dy*dy) < l*l) return 1;
     };
     return 0;
 };
References ACI_CHECK_RADIUS, ActD, ActionDispatcher::Active, getDistX(), getDistY(), Object::radius, S2G(), Object::x, and Object::y.
Referenced by actIntDispatcher::inv_mouse_move_quant().
aciPrepareWorldsMenu()
void aciPrepareWorldsMenu (void)
 {
     int i;
     aciWorldInfo* p1;
     if(CurrentWorld == -1) return;
     fncMenu* p = aScrDisp -> get_menu(FMENU_WORLDS_MENU);
     if(p){
         p -> prepare_items();
         for(i = 0; i < AS_MAX_WORLD; i ++){
             if(!aScrDisp -> wMap -> world_key(i)){
                 p -> deactivate_item(1000 + i);
             }
         }
         if(aScrDisp -> flags & AS_WORLDS_INIT){
             p1 = (aciWorldInfo*)aScrDisp -> wMap -> world_list -> last;
             while(p1){
                 if(p1 -> uvsID == CurrentWorld) p -> deactivate_item(1000 + p1 -> ID);
                 p1 = (aciWorldInfo*)p1 -> prev;
             }
         }
     }
 }
References AS_MAX_WORLD, aScrDisp, CurrentWorld, FMENU_WORLDS_MENU, and wMap.
Referenced by aciPrepareMenus(), load_map_bmp(), and StuffObject::Quant().
addDevice()
StuffObject* addDevice (int x, int y, int z, int device_type, int param1, int param2, VangerUnit * Owner, int cMode)
 {
     StuffObject* n = NULL;
     StuffObject* p = NULL;
     GeneralObject* g;
     GeneralObject* gg;
     int t;
     n = ItemD.StuffItemLink[device_type];
     p = (StuffObject*)(ItemD.GetObject(DevicetStorageID[n->StuffType]));
     if(!p && Owner){
         g = ItemD.Tail;
         t = n->StuffType;
         while(g){
             gg = g->NextTypeList;
             if(((StuffObject*)(g))->StuffType == t && ((StuffObject*)(g))->CheckItemOver()){
                 ItemD.DeleteItem((StuffObject*)(g));
                 break;
             };
             g = gg;
         };
         p = (StuffObject*)(ItemD.GetObject(DevicetStorageID[t]));
     };
     if(p){
         p->ActIntBuffer.data0 = param1;
         p->ActIntBuffer.data1 = param2;
         if(Owner) p->CreateDevice(Vector(x,y,z),Owner,n);
         else{
             if(cMode == STUFF_CREATE_NONE){
                 if(z == ITEM_DEFAULT_Z) p->CreateStuff(Vector(x,y,z),n,STUFF_CREATE_NONE);
                 else
                     p->CreateStuff(Vector(x,y,z),n,STUFF_CREATE_RELAX);
             }else p->CreateStuff(Vector(x,y,z),n,cMode);
         };
         if(p->StuffType == DEVICE_ID_GUN)
             ((GunDevice*)(p))->CreateGun();
     };
     return p;
 };
References StuffObject::ActIntBuffer, StuffObject::CreateDevice(), StuffObject::CreateStuff(), actintItemData::data0, actintItemData::data1, ItemsDispatcher::DeleteItem(), DEVICE_ID_GUN, DevicetStorageID, g, UnitList::GetObject(), ITEM_DEFAULT_Z, ItemD, NULL, STUFF_CREATE_NONE, STUFF_CREATE_RELAX, ItemsDispatcher::StuffItemLink, StuffObject::StuffType, and UnitList::Tail.
Referenced by ItemsDispatcher::CryptQuant(), VangerUnit::Go2World(), VangerUnit::InCarNator(), NetworkWorldOpen(), ItemsDispatcher::Open(), SkyFarmerObject::Quant(), and ItemGenerator::Quant().
addFarmer()
void addFarmer (int x_pos, int y_pos, int x_speed, int y_speed, int corn_type, int corn, int time)
 {
     (FarmerD.CreateSkyFarmer())->CreateSkyFarmer(x_pos,y_pos,x_speed,y_speed,corn_type,corn,time);
 };
References SkyFarmerList::CreateSkyFarmer(), and FarmerD.
Referenced by uvsBunch::begin_harvest(), and SkyFarmerList::Init().
aiPromptDominanceMessage()
void aiPromptDominanceMessage (int d)
 {
 //  if(!uvsKronActive) return;
     RaceTxtBuff.init();
     if(lang() == RUSSIAN) RaceTxtBuff < rDominanceMessageData;
     else RaceTxtBuff < DominanceMessageData;
     if(d > 0) RaceTxtBuff < " +";
     else RaceTxtBuff < " -";
     RaceTxtBuff <= abs(d);
     aiMessageBuffer.align_type = 0;
     aiMessageBuffer.TimeBuf[0] = 200;
     aiMessageBuffer.ColBuf[0] = 143;
     aiMessageBuffer.NumStr = 1;
     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
     aciSendPrompt(&aiMessageBuffer);
 };
References aciSendPrompt(), aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, aciPromptData::ColBuf, DominanceMessageData, XBuffer::GetBuf(), XBuffer::init(), lang(), aciPromptData::NumStr, RaceTxtBuff, rDominanceMessageData, RUSSIAN, and aciPromptData::TimeBuf.
Referenced by aiMessageList::Quant().
aiPromptLuckMessage()
void aiPromptLuckMessage (int d)
 {
 //  if(!uvsKronActive) return;
     RaceTxtBuff.init();
     if(lang() == RUSSIAN) RaceTxtBuff < rTaskMessageLuck;
     else RaceTxtBuff < TaskMessageLuck;
     if(d > 0) RaceTxtBuff < " +";
     else RaceTxtBuff < " -";
     RaceTxtBuff <= abs(d);
     aiMessageBuffer.align_type = 0;
     aiMessageBuffer.TimeBuf[0] = 200;
     aiMessageBuffer.ColBuf[0] = 143;
     aiMessageBuffer.NumStr = 1;
     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
     aciSendPrompt(&aiMessageBuffer);
 };
References aciSendPrompt(), aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, aciPromptData::ColBuf, XBuffer::GetBuf(), XBuffer::init(), lang(), aciPromptData::NumStr, RaceTxtBuff, rTaskMessageLuck, RUSSIAN, TaskMessageLuck, and aciPromptData::TimeBuf.
Referenced by aiMessageList::Quant().
aiPromptTaskMessage()
void aiPromptTaskMessage (int l)
 {
 //  if(!uvsKronActive) return;
     aiMessageBuffer.align_type = 0;
     if(l >= 0){
         if(lang() == RUSSIAN) aiMessageBuffer.add_str(0,(unsigned char*)rSuccessTaskMessageData);
         else aiMessageBuffer.add_str(0,(unsigned char*)SuccessTaskMessageData);
     }else{
         if(lang() == RUSSIAN) aiMessageBuffer.add_str(0,(unsigned char*)rFailedTaskMessageData);
         else aiMessageBuffer.add_str(0,(unsigned char*)FailedTaskMessageData);
     };
 //  aiMessageBuffer.add_str(0,(uchar*)(s));
     aiMessageBuffer.TimeBuf[0] = 200;
     aiMessageBuffer.ColBuf[0] = 143;
     RaceTxtBuff.init();
     if(lang() == RUSSIAN) RaceTxtBuff < rTaskMessageLuck;
     else RaceTxtBuff < TaskMessageLuck;
     if(l > 0) RaceTxtBuff < " +";
     else RaceTxtBuff < " -";
     RaceTxtBuff <= abs(l);
     aiMessageBuffer.add_str(1,(uchar*)(RaceTxtBuff.GetBuf()));
     aiMessageBuffer.TimeBuf[1] = 200;
     aiMessageBuffer.ColBuf[1] = 143;
     aiMessageBuffer.NumStr = 2;
     aciSendPrompt(&aiMessageBuffer);
     ClearTabutaskTarget();
 };
References aciSendPrompt(), aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, ClearTabutaskTarget(), aciPromptData::ColBuf, FailedTaskMessageData, XBuffer::GetBuf(), XBuffer::init(), lang(), aciPromptData::NumStr, RaceTxtBuff, rFailedTaskMessageData, rSuccessTaskMessageData, rTaskMessageLuck, RUSSIAN, SuccessTaskMessageData, TaskMessageLuck, and aciPromptData::TimeBuf.
Referenced by aiMessageList::Quant().
camera_impulse()
void camera_impulse (int amplitude_8)
 {
     camera_vt += (camera_turn_impulse - (int)RND(2*camera_turn_impulse))*amplitude_8 >> 8;
 }
References camera_turn_impulse, camera_vt, and RND().
Referenced by VangerUnit::Destroy(), VangerUnit::keyhandler(), and BulletObject::Touch().
ChangeItemData()
void ChangeItemData (int d)
 {
     StuffObject* p;
     VangerUnit* n;
     p = (StuffObject*)(ItemD.Tail);
     while(p){
 //      uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d);
         if(uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d)){
             p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
             switch(p->ActIntBuffer.type){
                 case ACI_TABUTASK_FAILED:
                     SOUND_FAILED();
 //                  ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
                 case ACI_TABUTASK_SUCCESSFUL:
                     SOUND_SUCCESS();
 //                  ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
             };
         };
         p = (StuffObject*)(p->NextTypeList);
     };
     n = (VangerUnit*)(ActD.Tail);
     while(n){
         p = n->DeviceData;
         while(p){
 //          uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d);
             if(uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d)){
                 p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 if(p->Owner->Status & SOBJ_ACTIVE) aciChangeItem(&(p->ActIntBuffer));
                 switch(p->ActIntBuffer.type){
                     case ACI_TABUTASK_FAILED:
                         SOUND_FAILED();
 //                      ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         break;
                     case ACI_TABUTASK_SUCCESSFUL:
                         SOUND_SUCCESS();
 //                      ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         break;
                 };
             };
             p = p->NextDeviceList;
         };
         n = (VangerUnit*)(n->NextTypeList);
     };
 };
References ACI_TABUTASK_FAILED, ACI_TABUTASK_SUCCESSFUL, aciChangeItem(), ActD, StuffObject::ActIntBuffer, actintItemData::data0, actintItemData::data1, uvsUnitType::DeviceData, ItemD, StuffObject::NextDeviceList, StuffObject::Owner, StuffObject::SetStuffColor(), SOBJ_ACTIVE, SOUND_FAILED, SOUND_SUCCESS, UnitList::Tail, actintItemData::type, uvsChangeGoodsParam(), StuffObject::uvsDeviceType, and uvsSetItemType().
Referenced by uvsChangeGoodsInList().
ChangeTabutaskItem()
void ChangeTabutaskItem (int type, int status)
 {
     StuffObject* p;
     VangerUnit* n;
     p = (StuffObject*)(ItemD.Tail);
     while(p){
         if(p->uvsDeviceType == UVS_ITEM_TYPE::TABUTASK && uvsChangeTabuTask(p->ActIntBuffer.data0,p->ActIntBuffer.data1,type,status)){
             p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
             switch(p->ActIntBuffer.type){
                 case ACI_TABUTASK_FAILED:
                     SOUND_FAILED();
 //                  ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
                 case ACI_TABUTASK_SUCCESSFUL:
                     SOUND_SUCCESS();
 //                  ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
             };
         };
         p = (StuffObject*)(p->NextTypeList);
     };
     n = (VangerUnit*)(ActD.Tail);
     while(n){
         p = n->DeviceData;
         while(p){
             if(p->uvsDeviceType == UVS_ITEM_TYPE::TABUTASK && uvsChangeTabuTask(p->ActIntBuffer.data0,p->ActIntBuffer.data1,type,status)){
                 p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 switch(p->ActIntBuffer.type){
                     case ACI_TABUTASK_FAILED:
                         SOUND_FAILED();
 //                      ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         if(p->Owner->Status & SOBJ_ACTIVE) aciChangeItem(&(p->ActIntBuffer));
                         break;
                     case ACI_TABUTASK_SUCCESSFUL:
                         SOUND_SUCCESS();
 //                      ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         if(p->Owner->Status & SOBJ_ACTIVE) aciChangeItem(&(p->ActIntBuffer));
                         break;
                 };
             };
             p = p->NextDeviceList;
         };
         n = (VangerUnit*)(n->NextTypeList);
     };
 };
References ACI_TABUTASK_FAILED, ACI_TABUTASK_SUCCESSFUL, aciChangeItem(), ActD, StuffObject::ActIntBuffer, actintItemData::data0, actintItemData::data1, uvsUnitType::DeviceData, ItemD, StuffObject::NextDeviceList, StuffObject::Owner, StuffObject::SetStuffColor(), SOBJ_ACTIVE, SOUND_FAILED, SOUND_SUCCESS, UVS_ITEM_TYPE::TABUTASK, UnitList::Tail, actintItemData::type, uvsChangeTabuTask(), StuffObject::uvsDeviceType, and uvsSetItemType().
Referenced by uvsChangeTabuTask().
CreateDestroyEffect()
void CreateDestroyEffect (Vector & v, int crat_id, int def_id, int def_flag, int expl_id, int fire_id)
 {
     WaterParticleObject* wp;
     uchar* tp = vMap->lineT[v.y];
     if(tp)  tp += v.x + H_SIZE;
     else return;
     if(GET_TERRAIN_TYPE(*tp) == WATER_TERRAIN && FloodLvl[v.y >> WPART_POWER] >= v.z){
         if(def_id >= 0) EffD.CreateDeform(v,def_flag,def_id);
         wp = (WaterParticleObject*)(EffD.GetObject(EFF_PARTICLE04));
         if(wp){
             wp->CreateParticle(30,5,1 << 8,5,5,28,5,v);
             EffD.ConnectObject(wp);
         };
     }else{
         if(expl_id >= 0) EffD.CreateExplosion(v,expl_id);
         else if(fire_id >= 0) EffD.CreateFireBall(v,fire_id);
     };
     if(crat_id >= 0) MapD.CreateCrater(v,crat_id);
 };
References UnitList::ConnectObject(), EffectDispatcher::CreateDeform(), EffectDispatcher::CreateExplosion(), EffectDispatcher::CreateFireBall(), EFF_PARTICLE04, EffD, FloodLvl, GET_TERRAIN_TYPE, UnitList::GetObject(), H_SIZE, vrtMap::lineT, MapD, vMap, WATER_TERRAIN, wp, WPART_POWER, Vector::x, Vector::y, and Vector::z.
Referenced by BulletObject::Event(), JumpBallObject::Quant(), FishWarrior::Quant(), and FishWarrior::Touch().
Item2ShopAction()
void Item2ShopAction (int type)
 {
     int i,j;
     for(i = 0;i < WORLD_MAX;i++){
         for(j = 0;j < ProtoCryptTableSize[i];j++){
             if(ProtoCryptTable[i][j].SensorType == type && ProtoCryptTable[i][j].Enable){
                 uvsKronDeleteItem(ProtoCryptTable[i][j].z0,0,0);
                 ProtoCryptTable[i][j].Enable = 0;
                 return;
             };
         };
     };
 };
References StaticObject::Enable, ProtoCryptTable, ProtoCryptTableSize, uvsKronDeleteItem(), and WORLD_MAX.
Referenced by ItemsDispatcher::Close().
Name2Int()
int Name2Int (char * name, const char * key[], int max)
 {
     int i,n;
     n = -1;
     for(i = 0;i < max;i++)
         if(!strcmp(name,key[i])){
             n = i;
             break;
         };
     if(n == -1)
         ErrH.Abort("Bad Name 2 Int");
     return n;
 };
References XErrorHandler::Abort(), ErrH, key(), and max().
Referenced by WorldBulletTemplate::Init().
ShowDominanceMessage()
void ShowDominanceMessage (int d)
 {
 //#ifndef ZMOD_BETA
     if(NetworkON) return;
 //#endif
     aiMessageQueue.SendDominance(d);
 };
References aiMessageQueue, NetworkON, and aiMessageList::SendDominance().
Referenced by uvsVanger::get_shop(), uvsVanger::homeArrival(), uvsVanger::KillStatic(), uvsVanger::makeJump(), uvsVanger::Quant(), uvsVanger::spotArrival(), uvsChangeDominance(), and uvsDomChangeFromItem().
ShowLuckMessage()
void ShowLuckMessage (int l)
 {
 //#ifndef ZMOD_BETA
     if(NetworkON) return;
 //#endif
     aiMessageQueue.SendLuck(l);
 };
References aiMessageQueue, NetworkON, and aiMessageList::SendLuck().
Referenced by uvsVanger::checkDolly(), uvsBunch::end_harvest(), uvsBunch::end_race(), uvsVanger::get_shop(), uvsChangeLuck(), uvsDomChangeFromItem(), uvsFreeDolly(), uvsLuckChange(), and uvsOnKillItem().
ShowTaskMessage()
void ShowTaskMessage (int l)
 {
     if(NetworkON) return;
     aiMessageQueue.SendTabuTask(l);
 };
References aiMessageQueue, NetworkON, and aiMessageList::SendTabuTask().
Referenced by uvsTabuTaskType::checkCycleEvent(), uvsTabuTaskType::Erase(), and uvsChangeTabuTask().
uvsapiDestroyItem()
int uvsapiDestroyItem (int ind, int ind2)
 {
     VangerUnit* n;
     GeneralObject* p;
     StuffObject* g;
     int GamerOwnerLog,keep_log;
     GeneralObject* tp;
     StuffObject* tg;
     GamerOwnerLog = 0;
     p = ItemD.Tail;
     while(p){
 //      if(p->ID != ID_STUFF)
 //          ErrH.Abort("Bad Stuff List");
         tp = p->NextTypeList;
         if(((StuffObject*)(p))->uvsDeviceType == ind)
             ItemD.DeleteItem((StuffObject*)(p));
         p = tp;
     };
     n = (VangerUnit*)(ActD.Tail);
     if(ind2 == -1){
         while(n){
 //          if(n->ID != ID_VANGER)
 //              ErrH.Abort("Bad Vanger List");
             g = n->DeviceData;
             if(n->Status & SOBJ_ACTIVE){
                 while(g){
                     tg = g->NextDeviceList;
                     if(g->uvsDeviceType == ind){
                         n->CheckOutDevice(g);
                         ActD.CheckDevice(g);
                         aciRemoveItem(&(g->ActIntBuffer));
                         GamerOwnerLog = 1;
                         n->DelDevice(g);
                         g->Storage->Deactive(g);
                     };
                     g = tg;
                 };
             }else{
                 while(g){
                     tg = g->NextDeviceList;
                     if(g->uvsDeviceType == ind){
                         n->CheckOutDevice(g);
                         n->DelDevice(g);
                         g->Storage->Deactive(g);
                     };
                     g = tg;
                 };
             };
             n = (VangerUnit*)(n->NextTypeList);
         };
     }else{
         while(n){
             keep_log = 0;
             if(ind == UVS_ITEM_TYPE::ELEECH){
                 g = n->DeviceData;
                 while(g){
                     if(g->ActIntBuffer.type == ACI_TOXICK){
                         keep_log++;
                         if(keep_log == SAFE_STUFF_MAX)
                             break;
                     };
                     g = g->NextDeviceList;
                 };
 //              if(GetStuffObject(n,ACI_TOXICK)) keep_log = 1;
             }else{
                 if(ind == UVS_ITEM_TYPE::WEEZYK){
 //                  if(GetStuffObject(n,ACI_PHLEGMA)) keep_log = 1;
                     g = n->DeviceData;
                     while(g){
                         if(g->ActIntBuffer.type == ACI_PHLEGMA){
                             keep_log++;
                             if(keep_log == SAFE_STUFF_MAX)
                                 break;
                         };
                         g = g->NextDeviceList;
                     };
                 };
             };
             if(keep_log < SAFE_STUFF_MAX){
                 g = n->DeviceData;
                 while(g){
                     tg = g->NextDeviceList;
                     if(g->uvsDeviceType == ind){
                         g->uvsDeviceType = ind2;
                         g->ActIntBuffer.type = uvsSetItemType(g->uvsDeviceType,g->ActIntBuffer.data0,g->ActIntBuffer.data1);
                         if(n->Status & SOBJ_ACTIVE){
                             switch(ind){
                                 case UVS_ITEM_TYPE::ELEECH:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_ELLECH,0,0xff,0);
                                     break;
                                 case UVS_ITEM_TYPE::WEEZYK:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_WEEZYK,0,0xff,0);
                                     break;
                                 case UVS_ITEM_TYPE::KERNOBOO:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_KERN,0,0xff,0);
                                     break;
                                 case UVS_ITEM_TYPE::PIPETKA:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_PIP,0,0xff,0);
                                     break;
                             };
                             aciChangeItem(&(g->ActIntBuffer));
                             GamerOwnerLog = 1;
                         };
                     };
                     g = tg;
                 };
             };
             n = (VangerUnit*)(n->NextTypeList);
         };
     };
     return GamerOwnerLog;
 };
References ACI_PHLEGMA, ACI_TOXICK, aciChangeItem(), aciRemoveItem(), ActD, AI_MESSAGE_DOWN_ELLECH, AI_MESSAGE_DOWN_KERN, AI_MESSAGE_DOWN_PIP, AI_MESSAGE_DOWN_WEEZYK, aiMessageQueue, ActionDispatcher::CheckDevice(), VangerUnit::CheckOutDevice(), uvsUnitType::DelDevice(), ItemsDispatcher::DeleteItem(), uvsUnitType::DeviceData, UVS_ITEM_TYPE::ELEECH, g, ItemD, UVS_ITEM_TYPE::KERNOBOO, GeneralObject::NextTypeList, UVS_ITEM_TYPE::PIPETKA, SAFE_STUFF_MAX, aiMessageList::Send(), SOBJ_ACTIVE, UnitList::Tail, uvsSetItemType(), and UVS_ITEM_TYPE::WEEZYK.
Referenced by uvsBunch::end_harvest(), and uvsBunch::end_race().
Variable Documentation
ACI_CHECK_RADIUS
const int ACI_CHECK_RADIUS = 1
Referenced by aciGetScreenItem(), and aciGetScreenMechos().
AdvancedView
int AdvancedView extern
Referenced by BulletObject::DrawQuant(), and HordeObject::DrawQuant().
aiMessageBuffer
aciPromptData aiMessageBuffer extern
Referenced by aiPromptDominanceMessage(), aiPromptLuckMessage(), and aiPromptTaskMessage().
BULLET_CONTROL_MODE_NAME
const char* BULLET_CONTROL_MODE_NAME[MAX_BULLET_CONTROL_MODE_NAME]
Initial value:
= {
    "None",
    "Fly",
    "Target",
    "Aim",
    "Speed",
    "Impulse",
    "MapDestruction",
    "Untouch",
    "Physic"
}
Referenced by WorldBulletTemplate::Init().
BULLET_CONTROL_MODE_VALUE
const int BULLET_CONTROL_MODE_VALUE[MAX_BULLET_CONTROL_MODE_NAME] = {0,1,2,4,8,16,32,64,128}
Referenced by WorldBulletTemplate::Init().
BULLET_ID_NAME
const char* BULLET_ID_NAME[MAX_BULLET_ID]
Initial value:
= {
    "ChainGun",
    "Rocket",
    "FireBall",
    "Terminator",
    "JumpBall",
    "Laser",
    "Horde",
    "Hypnotise"
}
Referenced by WorldBulletTemplate::Init().
BULLET_IMPULSE_ARM
const int BULLET_IMPULSE_ARM = 5 << 16
Referenced by BulletObject::Touch().
BULLET_IMPULSE_POWER
const int BULLET_IMPULSE_POWER = 9 << 14
Referenced by BulletObject::Touch().
BULLET_SHOW_ID_NAME
const char* BULLET_SHOW_ID_NAME[MAX_BULLET_SHOW_ID_NAME]
Initial value:
= {
        "Particle",
        "FireBall",
        "Deform",
        "Dust",
        "Crater",
        "JumpBall",
        "Laser"
}
Referenced by WorldBulletTemplate::Init().
BULLET_TARGET_MODE_NAME
const char* BULLET_TARGET_MODE_NAME[MAX_BULLET_TARGET_MODE_NAME]
Initial value:
= {
        "None",
        "Control",
        "LeftRound",
        "RightRound",
        "Random",
        "Wall"
}
Referenced by WorldBulletTemplate::Init().
curGMap
iGameMap* curGMap extern
DEBRIS_LIFE_TIME
const char DEBRIS_LIFE_TIME = 100
Referenced by DebrisObject::Quant().
DEVICE_OUT_NORMAL
const int DEVICE_OUT_NORMAL = 70
DevicetStorageID
int DevicetStorageID[MAX_DEVICE_TYPE] = {ITEM_GUN_DEVICE,ITEM_CHANGER,ITEM_OTHER}
Referenced by addDevice(), ItemsDispatcher::NetDevice(), and ItemsDispatcher::NetEvent().
DollyPoint
dastPoly3D DollyPoint extern
Referenced by StuffObject::DeviceOut(), StuffObject::ImpulseAction(), and StuffObject::Quant().
FireColorTable
uchar* FireColorTable extern
Referenced by BulletObject::DrawQuant().
GeneralMousePoint
Vector GeneralMousePoint
Referenced by aciGetScreenItem(), StuffObject::DeviceOut(), and ItemsDispatcher::Open().
GloryPlaceData
GloryPlace* GloryPlaceData
Referenced by CreatePhantomTarget(), VangerUnit::Destroy(), GeneralSystemClose(), GeneralSystemFree(), NetInit(), NetworkWorldOpen(), and GameObjectDispatcher::Quant().
GloryPlaceNum
int GloryPlaceNum
Referenced by CreatePhantomTarget(), GeneralSystemClose(), NetInit(), NetworkWorldOpen(), GameObjectDispatcher::Quant(), GloryPlace::Quant(), VangerUnit::Quant(), and VangerUnit::SensorQuant().
GloryRnd
aiRndType GloryRnd
Referenced by GloryPlace::Init(), and NetworkWorldOpen().
HORDE_PARTICLE_NUM
const int HORDE_PARTICLE_NUM = 200
Referenced by HordeObject::CreateHorde(), and HordeObject::Init().
HORDE_RADIUS_DELTA
const int HORDE_RADIUS_DELTA = 30
ITEM_LUCK_RADIUS
const int ITEM_LUCK_RADIUS = 20
Referenced by ItemsDispatcher::CryptQuant(), and ItemsDispatcher::Open().
MAX_BULLET_CONTROL_MODE_NAME
const int MAX_BULLET_CONTROL_MODE_NAME = 9
Referenced by WorldBulletTemplate::Init().
MAX_BULLET_ID
const int MAX_BULLET_ID = 8
Referenced by WorldBulletTemplate::Init().
MAX_BULLET_SHOW_ID_NAME
const int MAX_BULLET_SHOW_ID_NAME = 7
Referenced by WorldBulletTemplate::Init().
MAX_BULLET_TARGET_MODE_NAME
const int MAX_BULLET_TARGET_MODE_NAME = 6
Referenced by WorldBulletTemplate::Init().
MAX_DROP_POINT
const int MAX_DROP_POINT = MAX_DROP_SEED*10
Referenced by SkyFarmerObject::CreateSkyFarmer(), and SkyFarmerObject::Quant().
MAX_DROP_SEED
const int MAX_DROP_SEED = 1
Referenced by SkyFarmerObject::Quant().
MAX_STORAGE_NAME
const int MAX_STORAGE_NAME = 2
MAX_STUFF_SCATTER
const int MAX_STUFF_SCATTER = 150
Referenced by StuffObject::CreateStuff(), StuffObject::DeviceOut(), and StuffObject::NetEvent().
ProtoCryptTable
SensorDataType* ProtoCryptTable[WORLD_MAX] extern
Referenced by ItemsDispatcher::Close(), ItemsDispatcher::CreateEnableCrypt(), ItemsDispatcher::CryptQuant(), FreeProtoCrypt(), InitProtoCrypt(), Item2ShopAction(), LoadProtoCrypt(), NetworkWorldOpen(), ItemsDispatcher::Open(), and SaveProtoCrypt().
ProtoCryptTableSize
int ProtoCryptTableSize[WORLD_MAX] extern
Referenced by ItemsDispatcher::Close(), ItemsDispatcher::CreateEnableCrypt(), ItemsDispatcher::CryptQuant(), FreeProtoCrypt(), InitProtoCrypt(), Item2ShopAction(), LoadProtoCrypt(), NetworkWorldOpen(), ItemsDispatcher::Open(), and SaveProtoCrypt().
RAM16
int RAM16 extern
Referenced by ItemsDispatcher::Init().
SkyFarmerWayTable
SensorDataType* SkyFarmerWayTable
Referenced by SkyFarmerObject::FindFarmer(), SkyFarmerList::Free(), and SkyFarmerList::Init().
SkyFarmerWayTableSize
int SkyFarmerWayTableSize
Referenced by SkyFarmerObject::CreateSkyFarmer(), SkyFarmerObject::FindFarmer(), SkyFarmerList::Free(), SkyFarmerList::Init(), and SkyFarmerObject::Quant().
TabuTable
uvsTabuTaskType** TabuTable extern
UsedCheckNum
int UsedCheckNum
Referenced by CreatePhantomTarget(), VangerUnit::Destroy(), NetInit(), NetStatisticUpdate(), NetworkWorldOpen(), GameObjectDispatcher::Quant(), GloryPlace::Quant(), VangerUnit::Quant(), and VangerUnit::SensorQuant().
WeaponWaitTime
int WeaponWaitTime
Referenced by GeneralSystemInit(), WorldBulletTemplate::Init(), VangerUnit::InitEnvironment(), VangerUnit::keyhandler(), VangerUnit::NewKeyHandler(), and VangerUnit::ShellNetEvent().