Vangers: src/lang.h File Reference
lang.h File Reference
Enumerations
enum Language { ENGLISH = 0, RUSSIAN = 1, GERMAN = 2 }
Functions
Language lang ()
void setLang (Language lang)
Enumeration Type Documentation
Language
enum Language
Enumerator
ENGLISH
RUSSIAN
GERMAN
               {
     ENGLISH = 0,
     RUSSIAN = 1,
     GERMAN = 2,
 };
Function Documentation
lang()
Language lang ()
                 {
     return _lang;
 }
Referenced by dgRoom::acceptQUERY(), aciChangeAviIndex(), aciInitEndGame(), aciInitStrings(), aciPrepareEndImage(), aciSendEvent2itmdsp(), aiPromptDominanceMessage(), aiPromptLuckMessage(), aiPromptTaskMessage(), Convert(), iScreenDispatcher::copy_text_next(), iScreenDispatcher::copy_text_prev(), cp1251_to_utf8(), cp866_to_cp1251(), CreateArtefactTarget(), CreatePhantomTarget(), CreateTabutaskTarget(), DiagenTextName(), GeneralSystemOpen(), getRC(), dgMolecule::getVarPhrase(), DiagenDispatcher::getWorldName(), iGetJoyBtnNameText(), iGetKeyNameText(), iInit(), iInitControlObjects(), iInitStrings(), iScreenDispatcher::input_string_quant(), InstallSOUND(), iQuantFirst(), ISEALPHA(), ivMapPrepare(), aiMessageType::Load(), LoadingMessage(), NetCheckRemovePlayer(), iScreenDispatcher::next_text(), iScreenDispatcher::prev_text(), ActionDispatcher::PromptQuant(), InputEventBuffer::receive_waiting_for_event(), restore_connection(), ServerFindChain::ServerFindChain(), setLang(), and xtInitApplication().
setLang()
void setLang (Language lang)
{
     _lang = lang;
 }
References lang().
Referenced by ComlineAnalyze(), and main().