Vangers: src/particle/light.h File Reference
light.h File Reference
Classes
struct LIGHT_TYPE
struct LandQuake
struct LightPoint
Macros
#define LIGHT_HEIGHT 100
#define LIGHT_LIFE_TIME 16
#define LIGHT_FIRST_TIME 2
#define LIGHT_MAX_RADIUSE 256
#define LIGHT_MAX_BRIGHTNESS 32
#define CHAR_SPEED 2
Functions
void PrepareLight (void)
void aWriteHelpString (int count, int *x, int *y, int font, unsigned char **pstr, int timer, int color, int space, unsigned int *pcolor)
Variables
int * light_table
uchar * invisible_table
LightPoint LPoint
Macro Definition Documentation
CHAR_SPEED
#define CHAR_SPEED 2
LIGHT_FIRST_TIME
#define LIGHT_FIRST_TIME 2
LIGHT_HEIGHT
#define LIGHT_HEIGHT 100
LIGHT_LIFE_TIME
#define LIGHT_LIFE_TIME 16
LIGHT_MAX_BRIGHTNESS
#define LIGHT_MAX_BRIGHTNESS 32
LIGHT_MAX_RADIUSE
#define LIGHT_MAX_RADIUSE 256
Function Documentation
aWriteHelpString()
void aWriteHelpString (int count, int * x, int * y, int font, unsigned char ** pstr, int timer, int color, int space, unsigned int * pcolor)
{
     int i, total_len = 0;
     int draw_len = CHAR_SPEED*timer;
     unsigned char tmp[256];
     int _x;
     int _color = color;
     for( i = 0; i < count; i++){
         if (pstr[i]){
             if (pcolor[i]) _color = pcolor[i];
             total_len += strlen((char*)pstr[i]);
             if (total_len <= draw_len){
                 aOutStr(x[i], y[i], font, _color, pstr[i], space );
             } else {
                 int d = total_len - draw_len;
                 memcpy( tmp, pstr[i],strlen((char*)pstr[i]) - d);
                 tmp[strlen((char*)pstr[i]) - d] = 0;
                 aOutStr(x[i], y[i], font, _color, tmp, space );
                 _x = x[i] + aStrLen(tmp, font, space );
                 EffD.FireBallData[2].Show2(_x, y[i], FrameCount);
                 EffD.FireBallData[2].CheckOut(FrameCount);
                 return;
             }//  end if
         }//  end if pstr[i]
     }//  end for
 }
References aOutStr(), aStrLen(), CHAR_SPEED, FireBallProcess::CheckOut(), EffD, EffectDispatcher::FireBallData, FrameCount, and FireBallProcess::Show2().
PrepareLight()
void PrepareLight (void)
{
     std::cout<<"PrepareLight"<<std::endl;
     int i, j, k;
     //int h2 = LIGHT_HEIGHT*LIGHT_HEIGHT;
     light_table_pal = new uchar[ light_table_pal_size ];
     invisible_table = new uchar[ 256*16 ];
     memset(light_table_pal, 0, light_table_pal_size);
     for( i = 0; i < TERRAIN_MAX; i++){
         for( j = 0; j < LIGHT_MAX_BRIGHTNESS; j++){
             for( k = BEGCOLOR[i]; k <= ENDCOLOR[i]; k++){
                 light_table_pal[k + (j << 8)] = k + round( float(j*BRIGHTNESS[i])/(255.0f));
                 if( light_table_pal[k + (j << 8)] > ENDCOLOR[i] ) light_table_pal[k + (j << 8)] = ENDCOLOR[i];
             }//  end for k
         }//  end for j
     }//  end fro i
     for( i = 0; i < TERRAIN_MAX; i++){
         for( j = 0; j < 16; j++){
             for( k = BEGCOLOR[i]; k <= ENDCOLOR[i]; k++){
                 invisible_table[k + (j << 8)] = k - j/2;
                 if( invisible_table[k + (j << 8)] > ENDCOLOR[i] ) invisible_table[k + (j << 8)] = ENDCOLOR[i];
                 if( invisible_table[k + (j << 8)] < BEGCOLOR[i] ) invisible_table[k + (j << 8)] = BEGCOLOR[i];
             }//  end for k
         }//  end for j
     }//  end fro i
 }
References BEGCOLOR, BRIGHTNESS, ENDCOLOR, invisible_table, LIGHT_MAX_BRIGHTNESS, light_table_pal, light_table_pal_size, round(), and TERRAIN_MAX.
Referenced by LoadingRTO2::Init().
Variable Documentation
invisible_table
uchar* invisible_table extern
Referenced by PrepareLight().
light_table
int* light_table extern
LPoint
LightPoint LPoint extern