Vangers: src/particle/light.cpp File Reference
light.cpp File Reference
#include "../global.h"
#include "../3d/3d_math.h"
#include "../3d/3dgraph.h"
#include "../3d/3dobject.h"
#include "../3d/parser.h"
#include "../sqexp.h"
#include "../backg.h"
#include "../terra/vmap.h"
#include "../terra/world.h"
#include "../terra/render.h"
#include "../dast/poly3d.h"
#include "../particle/particle.h"
#include "../particle/partmap.h"
#include "../particle/df.h"
#include "../particle/light.h"
#include "../units/hobj.h"
#include "../units/effect.h"
Functions
void LineQuake (int x1, int y1, int x0, int y0, int dx, int shiftparam)
int aStrLen (unsigned char *str, int font, int space)
void aOutStr (int x, int y, int font, int color, unsigned char *str, int space)
void PrepareLight (void)
void aWriteHelpString (int count, int *x, int *y, int font, unsigned char **pstr, int timer, int color, int space, unsigned int *pcolor)
Variables
uchar * light_table_pal = NULL
uchar * invisible_table
int FrameCount = 0
uchar BRIGHTNESS [TERRAIN_MAX] = { 255, 255, 255, 255, 255, 255, 255, 255}
int light_table_pal_size = 256*LIGHT_MAX_BRIGHTNESS
Function Documentation
aOutStr()
void aOutStr (int x, int y, int font, int color, unsigned char * str, int space)
 {
     int i,j,s,xs,ys,offs = 0,sz = strlen((char*)str),X = 0,Y = 0,col1,col2;
     unsigned char* palBuf = palbuf;
     col1 = color & ACI_COLOR_MASK;
     col2 = (color >> 8) & ACI_COLOR_MASK;
     if(aScrFonts[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     unsigned char* p = aScrFonts[font] -> data;
     xs = aScrFonts[font] -> SizeX;
     ys = aScrFonts[font] -> SizeY;
     X = x;
     if(col2){
         for(s = 0; s < sz; s ++){
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             for(i = 0; i < ys; i ++){
                 Y = y + i;
                 for(j = 0; j < xs; j ++){
                     switch(p[offs + j]){
                         case 1:
                             XGR_SetPixel(X + j,Y,col1);
                             break;
                         case 2:
                             XGR_SetPixel(X + j,Y,col2);
                             break;
                     }
                 }
                 offs += xs;
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
     else {
         for(s = 0; s < sz; s ++){
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             for(i = 0; i < ys; i ++){
                 Y = y + i;
                 for(j = 0; j < xs; j ++){
                     switch(p[offs + j]){
                         case 1:
                             XGR_SetPixel(X + j,Y,col1);
                             break;
                     }
                 }
                 offs += xs;
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
 }
Referenced by aWriteHelpString().
aStrLen()
int aStrLen (unsigned char * str, int font, int space)
 {
     int s,sz = strlen((char*)str),len = 0;
     for(s = 0; s < sz; s ++)
         len += aScrFonts[font] -> SizeX - (aScrFonts[font] -> LeftOffs[str[s]] + aScrFonts[font] -> RightOffs[str[s]]) + space;
     return len;
 }
References aScrFonts.
Referenced by aWriteHelpString().
aWriteHelpString()
void aWriteHelpString (int count, int * x, int * y, int font, unsigned char ** pstr, int timer, int color, int space, unsigned int * pcolor)
{
     int i, total_len = 0;
     int draw_len = CHAR_SPEED*timer;
     unsigned char tmp[256];
     int _x;
     int _color = color;
     for( i = 0; i < count; i++){
         if (pstr[i]){
             if (pcolor[i]) _color = pcolor[i];
             total_len += strlen((char*)pstr[i]);
             if (total_len <= draw_len){
                 aOutStr(x[i], y[i], font, _color, pstr[i], space );
             } else {
                 int d = total_len - draw_len;
                 memcpy( tmp, pstr[i],strlen((char*)pstr[i]) - d);
                 tmp[strlen((char*)pstr[i]) - d] = 0;
                 aOutStr(x[i], y[i], font, _color, tmp, space );
                 _x = x[i] + aStrLen(tmp, font, space );
                 EffD.FireBallData[2].Show2(_x, y[i], FrameCount);
                 EffD.FireBallData[2].CheckOut(FrameCount);
                 return;
             }//  end if
         }//  end if pstr[i]
     }//  end for
 }
References aOutStr(), aStrLen(), CHAR_SPEED, FireBallProcess::CheckOut(), EffD, EffectDispatcher::FireBallData, FrameCount, and FireBallProcess::Show2().
LineQuake()
void LineQuake (int x1, int y1, int x0, int y0, int dx, int shiftparam)
{
     if(y1 > VcutDown) return;
     if(x1 > UcutRight) return;
     if(y1 < VcutUp) return;
     if(x1 < UcutLeft) return;
     int coef = (1<<shiftparam)-1;
     int color = XGR_GetPixel(x1, y1);
     XGR_Line(x1,y1,(coef*x1 + x0)>>shiftparam,(coef*y1 + y0)>>shiftparam,color);
 }
References UcutLeft, UcutRight, VcutDown, VcutUp, XGR_GetPixel, and XGR_Line.
Referenced by LandQuake::quant().
PrepareLight()
void PrepareLight (void)
{
     std::cout<<"PrepareLight"<<std::endl;
     int i, j, k;
     //int h2 = LIGHT_HEIGHT*LIGHT_HEIGHT;
     light_table_pal = new uchar[ light_table_pal_size ];
     invisible_table = new uchar[ 256*16 ];
     memset(light_table_pal, 0, light_table_pal_size);
     for( i = 0; i < TERRAIN_MAX; i++){
         for( j = 0; j < LIGHT_MAX_BRIGHTNESS; j++){
             for( k = BEGCOLOR[i]; k <= ENDCOLOR[i]; k++){
                 light_table_pal[k + (j << 8)] = k + round( float(j*BRIGHTNESS[i])/(255.0f));
                 if( light_table_pal[k + (j << 8)] > ENDCOLOR[i] ) light_table_pal[k + (j << 8)] = ENDCOLOR[i];
             }//  end for k
         }//  end for j
     }//  end fro i
     for( i = 0; i < TERRAIN_MAX; i++){
         for( j = 0; j < 16; j++){
             for( k = BEGCOLOR[i]; k <= ENDCOLOR[i]; k++){
                 invisible_table[k + (j << 8)] = k - j/2;
                 if( invisible_table[k + (j << 8)] > ENDCOLOR[i] ) invisible_table[k + (j << 8)] = ENDCOLOR[i];
                 if( invisible_table[k + (j << 8)] < BEGCOLOR[i] ) invisible_table[k + (j << 8)] = BEGCOLOR[i];
             }//  end for k
         }//  end for j
     }//  end fro i
 }
References BEGCOLOR, BRIGHTNESS, ENDCOLOR, invisible_table, LIGHT_MAX_BRIGHTNESS, light_table_pal, light_table_pal_size, round(), and TERRAIN_MAX.
Referenced by LoadingRTO2::Init().
Variable Documentation
BRIGHTNESS
uchar BRIGHTNESS[TERRAIN_MAX] = { 255, 255, 255, 255, 255, 255, 255, 255}
Referenced by PrepareLight().
FrameCount
int FrameCount = 0
Referenced by aWriteHelpString().
invisible_table
uchar* invisible_table
Referenced by PrepareLight().
light_table_pal
uchar* light_table_pal = NULL
Referenced by LightPoint::FourLightLine(), PrepareLight(), and LightPoint::quant().
light_table_pal_size
int light_table_pal_size = 256*LIGHT_MAX_BRIGHTNESS
Referenced by PrepareLight(), and LightPoint::quant().