Vangers: src/units/mechos.cpp File Reference
mechos.cpp File Reference
#include "../global.h"
#include "../lang.h"
#include "../zmod_client.h"
#include "../runtime.h"
#include "../3d/3d_math.h"
#include "../3d/3dgraph.h"
#include "../3d/3dobject.h"
#include "../3d/parser.h"
#include "../common.h"
#include "../sqexp.h"
#include "../backg.h"
#include "../terra/vmap.h"
#include "../terra/world.h"
#include "../terra/render.h"
#include "../iscreen/controls.h"
#include "../iscreen/iscreen_options.h"
#include "../actint/item_api.h"
#include "uvsapi.h"
#include "../network.h"
#include "../uvs/univang.h"
#include "../dast/poly3d.h"
#include "../particle/particle.h"
#include "../particle/partmap.h"
#include "../particle/df.h"
#include "../particle/light.h"
#include "track.h"
#include "hobj.h"
#include "moveland.h"
#include "items.h"
#include "sensor.h"
#include "effect.h"
#include "mechos.h"
#include "compas.h"
#include "../sound/hsound.h"
#include "../uvs/diagen.h"
#include "magnum.h"
#include "../actint/credits.h"
Macros
#define INSECTOIDS
#define DUST
#define AUTOMAT
#define SLOPE_MAX Pi/6
#define MAX_ZOOM 384
#define MAX_ZOOM_16 320
#define MIN_ZOOM 128
#define UPPER_THRESHOULD 32
#define LOWER_THRESHOULD 64
Functions
int test_block (unsigned char *ptr, int size)
void camera_impulse (int amplitude_8)
void DrawCircle (int x, int y, int R, int color)
void aPutStr (int x, int y, int font, int color, unsigned char *str, int bsx, unsigned char *buf, int space)
void calc_view_factors ()
void uvsChangeCycle (void)
void aOutText32clip (int x, int y, int color, void *text, int font, int hspace, int vspace)
void FIRE_ALL_WEAPONS ()
char CheckAddLink (LinkType *l, BranchType *b, int s)
char CheckDecLink (LinkType *l, BranchType *b, int s)
int GetAngle (int x0, int y0, int x1, int y1, int x2, int y2)
char CheckInNode (Vector &v, NodeType *n)
char CheckInLink (Vector &v, LinkType *pl, LinkType *nl)
char CheckInBranch (Vector &v, LinkType *pl, LinkType *nl, BranchType *b)
int LinkDist (int x, int y, int x1, int y1, int x2, int y2)
void LinkDist (int x, int y, int x1, int y1, int x2, int y2, int radius, Vector &v)
void AxisLen (Vector vA0, Vector vA1, Vector vC, Vector &vR)
void PointDist (int dx, int dy, int dz, int r, int radius, char dir, Vector &vd, Vector &v)
void LenDist (int x, int y, int z, int x1, int y1, int z1, int dist, int radius, Vector &v)
char GetNodeDist (TrackLinkType *p1, TrackLinkType *p2)
char * dgGetThreallPhrase (void)
int uvsWorldToCross (int fromWID, int toWID)
void start_vibration ()
void camera_reset ()
void camera_quant (int X, int Y, int Turn, double V_abs)
void camera_quant ()
void camera_direct (int X, int Y, int zoom, int Turn, int Slope, int num_frames)
void aci_LocationQuant (void)
VangerUnit * addVanger (uvsVanger *p, int x, int y, int Human)
VangerUnit * addVanger (uvsVanger *p, uvsPassage *origin, int Human)
int iGetOptionValue (int id)
VangerUnit * addVanger (uvsVanger *p, uvsEscave *origin, int Human)
VangerUnit * addVanger (uvsVanger *p, uvsSpot *origin, int Human)
int uvsMechosType_to_AciInt (int)
void iChatFinit (void)
int uvsCheckItemOnLive (int type)
void uvsOnKillItem (void)
void BunchEvent (int type)
void section_prepare (int xg0, int yg0, int xg1, int yg1, int xg2, int yg2, int xg3, int yg3, int z_mechous, double &A, double &B, double &Z_AVR, DBV &normal)
void aciActionEvent (void)
char * uvsGetNameByID (int type, int &ID)
void aciSendEvent2itmdsp (int code, actintItemData *p, int data)
StuffObject * GetStuffObject (uvsUnitType *g, int n)
void aOutStr (int x, int y, int font, int color, unsigned char *str, int space)
int CheckStartJump (Object *p)
void ClearTabutaskTarget (void)
void ClearPhantomTarget (int id)
void AddPhantomTarget (PlayerData *n)
void CreateArtefactTarget (StuffObject *n)
void DeleteArtefactTarget (StuffObject *n)
void CreateTabutaskTarget (void)
void CreatePhantomTarget (void)
void AddTarget2Compas (int type, void *point, const char *head)
void SelectCompasTarget (const char *n)
char * GetCompasTarget (void)
int ChargeWeapon (VangerUnit *p, int ind, int sign)
int ChargeDevice (VangerUnit *p, int ind, int sign)
void NetSlotEvent (int type, int id)
int GetEscaveDist (void)
void NetStatisticInit (void)
void NetStatisticGameStart (void)
void NetStatisticUpdate (int id)
void CheckPlayerList (void)
void NetEvent4Uvs (PlayerData *p)
void SetWorldBeebos (int n)
void ObjectDestroy (GeneralObject *n, int mode)
int FuckOFFinWater (void)
void CreateBoozeeniadaString (void)
char * StringOfBoozeeniada (void)
void addInfernalsKill2Protractor (void)
void addSpectorsKill2Messiah (void)
int getSpobsState (void)
int getThreallState (void)
int isSpummyDeath (void)
void FakeOfMight (void)
void XpeditionOFF (int type)
void NetworkGetStart (char *name, int &x, int &y)
void aciPrepareMenus (void)
void NetCheckRemovePlayer (PlayerData *p)
void GetNetworkGameTime (int &day, int &hour, int &min, int &sec)
Variables
int DbgCheckEnable
int AUTOMATIC_WORLD_INDEX = WORLD_NECROSS
iGameMap * curGMap
int frame
uchar * palbufOrg
uchar * FireColorTable
int multi_analysis
int multi_draw
int RAM16
int GameQuantReturnValue
int aciWorldIndex
int light_modulation
int vSetVangerFlag = -1
int * SpeedLenTable
int * SpeedAngleTable
int * RudderLenTable
int * RudderAngleTable
TrackType HideTrack
int NumHumanModel = 1
int AdvancedView = 0
int ChangeEnergy
int ChangeArmor
CompasObject CompasObj
int aciCurJumpCount
int aciMaxJumpCount
const int FLY_DEVICE_DEFAULT = 22
const int MOLE_DEVICE_DEFAULT = 23
const int SWIM_DEVICE_DEFAULT = 21
Vector vInsectTarget
int aciProtractorEvent
int aciMechMessiahEvent
int uvsKronActive
int MAX_TABUTASK
int UnitGlobalTime
LandQuake SkyQuake
int SkyQuakeEnable
LandQuake SkyQuake2
int SkyQuakeEnable2
LandQuake SkyQuake3
int SkyQuakeEnable3
int aciTeleportEvent
const int SKY_QUAKE_RADIUS = 300
const int SKY_QUAKE_DELTA = 15
const int SKY_QUAKE_TIME = 10
const int SKY_QUAKE_DELAY = 25
const int SIGNATOR_DELAY = 70
int Dead
int Quit
int aiReadEvent
int aiWriteEvent
int aiNumGlobalEvent [2][AI_EVENT_MAX]
aiUnitEvent aiGlobalEventData [2][AI_EVENT_MAX][AI_GLOBAL_EVENT_MAX]
int TotalVangerSpeed
int max_jump_power
int aciCurLuck
int aciCurDominance
int aiStatusLastEscave
int aiStatusEscaveEmpty
int aiStatusPodishCount
int aiStatusIncubatorCount
int aiStatusPodishEmptyCount
int aiStatusIncubatorEmptyCount
int aiStatusEmptyCount
int aiStatusEmptyTime
int aiStatusPrevY
aiFactorType aiFactorData [AI_FACTOR_NUM]
uvsTabuTaskType ** TabuTable
int aiHotBugData00
int aiHotBugData01
int aiHotBugData02
int aiHotBugData03
int aiHotBugAdd00
int aiHotBugAdd01
int aiHotBugAdd02
int aiHotBugAdd03
const char MECHOS_WATER_WAVE = 0
int view_lock
int aciTextEndFlag
XBuffer RaceTxtBuff (1024)
double camera_mi
double camera_miz
double camera_mit
double camera_mii
double camera_mis
double camera_drag
double camera_dragz
double camera_dragt
double camera_dragi
double camera_drags
double camera_vz_min
double camera_vt_min
double camera_vs_min
int camera_turn_impulse = Pi
int camera_zmin = 400
int camera_slope_min = 0
int camera_zmax = 800
double camera_vmax = 20
double camera_x =0
double camera_vx =0
double camera_y =0
double camera_vy =0
double camera_z =0
double camera_vz =0
double camera_t =0
double camera_vt =0
double camera_vi =0
double camera_s =0
double camera_vs =0
int stop_camera = 0
int camera_moving_log = 0
int camera_X_prev
int camera_Y_prev
int camera_moving_xy_enable = 0
int camera_moving_z_enable = 0
int camera_slope_enable = 0
int camera_rotate_enable = 0
int time_vibration = 0
int max_time_vibration
double A_vibration
double alpha_vibration
double oscillar_vibration
int NewWorldX
int NewWorldY
const int INSECT_RADIUS = 2500
const int INSECT_RADIUS2 = INSECT_RADIUS * 2
int uvsGamerWaitGame
int preViewY
VangerUnit * actCurrentViewObject
int aciCurDvcResource
int aciMaxDvcResource
const int COMPAS_RIGHT = 80
const int COMPAS_LEFT = 60
const int COMPAS_UP = 60
const int COMPAS_DOWN = 80
const int MAX_COMPAS_DELTA = 7
const int MAX_COMPAS_SPEED = 10
listElem * EscaveTail
listElem * SpotTail
listElem * PassageTail
dastPoly3D terra_moving_tool
const int HYPNOTISE_WEAPON_RADIUS = 100
UnitItemMatrix * UnitMatrixData
uvsVanger * Gamer
time_t StartGameTime
time_t PrevLifeTime
time_t PrevKillTime
time_t MinLifeTime
time_t MaxLifeTime
time_t MinKillTime
time_t MaxKillTime
int CHECK_BSIGN_INDEX [NUM_CHECK_BSIGN]
char * CHECK_BSIGN_DATA
int uvsPoponkaID
listElem * DollyTail
const int NETWORK_NUM_ESCAVE = 7
const char * NetworkEscaveName [NETWORK_NUM_ESCAVE] ={"Podish","Incubator","VigBoo","Lampasso","Ogorod","ZeePa","B-Zone"}
aciPromptData aiMessageBuffer
Macro Definition Documentation
AUTOMAT
#define AUTOMAT
DUST
#define DUST
INSECTOIDS
#define INSECTOIDS
LOWER_THRESHOULD
#define LOWER_THRESHOULD 64
MAX_ZOOM
#define MAX_ZOOM 384
MAX_ZOOM_16
#define MAX_ZOOM_16 320
MIN_ZOOM
#define MIN_ZOOM 128
SLOPE_MAX
#define SLOPE_MAX Pi/6
UPPER_THRESHOULD
#define UPPER_THRESHOULD 32
Function Documentation
aci_LocationQuant()
void aci_LocationQuant (void)
aciActionEvent()
void aciActionEvent (void)
 {
     if(ActD.Active)
         ActD.Active->DoorFlag = 1;
 };
References ActD, ActionDispatcher::Active, and VangerUnit::DoorFlag.
Referenced by actIntDispatcher::EventQuant().
aciPrepareMenus()
void aciPrepareMenus (void)
 {
     aScrDisp -> clean_menus();
     aScrDisp -> prepare_menus();
     aciPrepareWorldsMenu();
 }
References aciPrepareWorldsMenu(), and aScrDisp.
Referenced by VangerUnit::ChangeVangerProcess(), and FirstEscaveRTO::Init().
aciSendEvent2itmdsp()
void aciSendEvent2itmdsp (int code, actintItemData * p, int data)
 {
     Vector vCheck;
     int i;
     int what,id;
     char* name_from;
     char* name_to;
     if(ActD.Active){
         switch(code){
             case ACI_DROP_ITEM:
                 ((VangerUnit*)(ActD.Active))->CheckOutDevice((StuffObject*)(p->stuffOwner));
                 ActD.CheckDevice((StuffObject*)(p->stuffOwner));
                 ((StuffObject*)(p->stuffOwner))->DeviceOut(ActD.Active->R_curr + Vector(0,0,ActD.Active->radius*3));
                 break;
             case ACI_ACTIVATE_ITEM:
                 switch(p->type){
                     case ACI_EMPTY_CIRTAINER:
                         if(ActD.Active->dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH)){
                             ActD.Active->uvsPoint->gatherCirt(ActD.Active->R_curr.x,ActD.Active->R_curr.y,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1);
                             p->type = uvsSetItemType(((StuffObject*)(p->stuffOwner))->uvsDeviceType,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1);
                             aciChangeItem(p);
                         };
                         break;
                     case ACI_CIRTAINER:
                         ((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0 = 0;
                         ((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1 = 0;
                         p->type = uvsSetItemType(((StuffObject*)(p->stuffOwner))->uvsDeviceType,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data0,((StuffObject*)(p->stuffOwner))->ActIntBuffer.data1);
                         aciChangeItem(p);
                         break;
                     case ACI_PEELOT:
                         if(ActD.Active->Status & SOBJ_AUTOMAT)
                             aiMessageQueue.Send(AI_MESSAGE_AUTOMATIC_OFF,0,0xff,0);
                         else
                             aiMessageQueue.Send(AI_MESSAGE_AUTOMATIC_ON,0,0xff,0);
                         ActD.Active->Status ^= SOBJ_AUTOMAT;
                         break;
                     case ACI_GLUEK:
                         (ActD.Active)->Armor += 10 << 16;
                         ObjectDestroy((StuffObject*)(p->stuffOwner));
                         (ActD.Active)->CheckOutDevice((StuffObject*)(p->stuffOwner));
                         ActD.CheckDevice((StuffObject*)(p->stuffOwner));
                         ((StuffObject*)(p->stuffOwner))->Storage->Deactive((StuffObject*)(p->stuffOwner));
                         (ActD.Active)->DelDevice((StuffObject*)(p->stuffOwner));
                         aciSendEvent2actint(ACI_DROP_ITEM,p);
                         break;
                     case ACI_TANKACID:
                         ObjectDestroy((StuffObject*)(p->stuffOwner));
                         for(i = 0;i < 3;i++){
                             vCheck = Vector(40,0,0)*DBM(i*PI / 3,Z_AXIS);
                             vCheck += ActD.Active->R_curr;
                             cycleTor(vCheck.x,vCheck.y);
                             MapD.CreateAcidSpot(vCheck,40,60,0,-16,40);
                         };
                         MapD.CreateAcidSpot(ActD.Active->R_curr,40,60,0,-16,40);
                         (ActD.Active)->CheckOutDevice((StuffObject*)(p->stuffOwner));
                         ActD.CheckDevice((StuffObject*)(p->stuffOwner));
                         ((StuffObject*)(p->stuffOwner))->Storage->Deactive((StuffObject*)(p->stuffOwner));
                         (ActD.Active)->DelDevice((StuffObject*)(p->stuffOwner));
                         aciSendEvent2actint(ACI_DROP_ITEM,p);
                         SOUND_ACID()
                         break;
                     default:
                         p->flags |= ACI_ACTIVE;
                         ActD.SlotIn(data,(StuffObject*)(p->stuffOwner));
                         break;
                 };
                 break;
             case ACI_DEACTIVATE_ITEM:
                 p->flags &= ~ACI_ACTIVE;
                 ActD.SlotOut((StuffObject*)(p->stuffOwner));
                 break;
             case ACI_SHOW_ITEM_TEXT:
                 if(p->type == ACI_TABUTASK_SUCCESSFUL){
                     RaceTxtBuff.init();
                     if(lang() == RUSSIAN){
 //GERMAN
                         RaceTxtBuff < uvsGetNameByID(p->data1 & 0xffff,i);
                         RaceTxtBuff < rFirstTabuTaskMessage;
                         RaceTxtBuff < rSecondTabuTaskMessage;
                         RaceTxtBuff <= TabuTable[p->data1 & 0xffff]->cash < "$";
 //ENGLISH
 /*
                         RaceTxtBuff < rFirstTabuTaskMessage;
                         RaceTxtBuff < uvsGetNameByID(p->data1 & 0xffff,i);
                         RaceTxtBuff < rSecondTabuTaskMessage;
                         RaceTxtBuff <= TabuTable[p->data1 & 0xffff]->cash < "$";*/
                     }else{
                         RaceTxtBuff < uvsGetNameByID(p->data1 & 0xffff,i);
                         RaceTxtBuff < FirstTabuTaskMessage;
                         RaceTxtBuff < SecondTabuTaskMessage;
                         RaceTxtBuff <= TabuTable[p->data1 & 0xffff]->cash < "$";
                     };
                     aciPrepareText(RaceTxtBuff.address());
                 }else{
                     if(uvsPrepareItemToDiagen(((StuffObject*)(p->stuffOwner))->uvsDeviceType,p->data0,p->data1,what,id,name_from,name_to))
                         aciPrepareText(dgD->getInvText(what,id,name_from,name_to));
                 };
                 break;
         };
     };
 };
References ACI_ACTIVATE_ITEM, ACI_ACTIVE, ACI_CIRTAINER, ACI_DEACTIVATE_ITEM, ACI_DROP_ITEM, ACI_EMPTY_CIRTAINER, ACI_GLUEK, ACI_PEELOT, ACI_SHOW_ITEM_TEXT, ACI_TABUTASK_SUCCESSFUL, ACI_TANKACID, aciChangeItem(), aciPrepareText(), aciSendEvent2actint(), ActD, ActionDispatcher::Active, XBuffer::address(), AI_MESSAGE_AUTOMATIC_OFF, AI_MESSAGE_AUTOMATIC_ON, aiMessageQueue, uvsTabuTaskType::cash, ActionDispatcher::CheckDevice(), cycleTor(), actintItemData::data0, actintItemData::data1, dgD, FirstTabuTaskMessage, actintItemData::flags, uvsVanger::gatherCirt(), DiagenDispatcher::getInvText(), GROUND_COLLISION, XBuffer::init(), lang(), MapD, ObjectDestroy(), PI, RaceTxtBuff, Object::radius, rFirstTabuTaskMessage, rSecondTabuTaskMessage, RUSSIAN, SecondTabuTaskMessage, aiMessageList::Send(), ActionDispatcher::SlotIn(), ActionDispatcher::SlotOut(), SOBJ_AUTOMAT, SOUND_ACID, actintItemData::stuffOwner, TabuTable, actintItemData::type, uvsGetNameByID(), uvsKernel::uvsPoint, uvsPrepareItemToDiagen(), uvsSetItemType(), WHEELS_TOUCH, Object::x, Vector::x, Object::y, Vector::y, and Z_AXIS.
Referenced by aciReInitItem(), aciReInitItemXY(), actIntDispatcher::change_items(), actIntDispatcher::deactivate_items(), actIntDispatcher::EventQuant(), actIntDispatcher::i_init(), actIntDispatcher::inv_mouse_quant_l(), actIntDispatcher::inv_mouse_quant_r(), actIntDispatcher::put_in_slot(), actIntDispatcher::put_item(), actIntDispatcher::put_item_xy(), actIntDispatcher::reinit_items(), and actIntDispatcher::set_move_item().
addInfernalsKill2Protractor()
void addInfernalsKill2Protractor (void)
 {
     ActD.ThreallDestroyActive = 1;
     aciActivateItemFunction(ACI_PROTRACTOR,ACI_PROTRACTOR_EVENT8);
 };
References ACI_PROTRACTOR, ACI_PROTRACTOR_EVENT8, aciActivateItemFunction(), ActD, and ActionDispatcher::ThreallDestroyActive.
AddPhantomTarget()
void AddPhantomTarget (PlayerData * n)
 {
     CompasTargetType* p;
     p = CompasObj.TargetData;
     while(p){
         if(p->ID == CMP_OBJECT_PHANTOM && (p->Data).ID == n->client_ID)
             break;
         p = p->Next;
     };
     if(!p)
         CompasObj.AddTarget(CMP_OBJECT_PHANTOM,UnitOrderType(n->client_ID),NULL,n->name);
 };
References CompasObject::AddTarget(), PlayerData::client_ID, CMP_OBJECT_PHANTOM, CompasObj, CompasTargetType::Data, CompasTargetType::ID, PlayerData::name, CompasTargetType::Next, NULL, and CompasObject::TargetData.
Referenced by VangerUnit::InitPlayerPoint().
addSpectorsKill2Messiah()
void addSpectorsKill2Messiah (void)
 {
     ActD.SpobsDestroyActive = 1;
     aciActivateItemFunction(ACI_MECHANIC_MESSIAH,ACI_MECH_MESSIAH_EVENT6);
 };
References ACI_MECH_MESSIAH_EVENT6, ACI_MECHANIC_MESSIAH, aciActivateItemFunction(), ActD, and ActionDispatcher::SpobsDestroyActive.
AddTarget2Compas()
void AddTarget2Compas (int type, void * point, const char * head)
 {
     switch(type){
         case CMP_TARGET_ESCAVE:
             CompasObj.AddTarget(type,(uvsEscave*)(NULL),(char*)(point),head);
             break;
         case CMP_TARGET_SPOT:
             CompasObj.AddTarget(type,(uvsSpot*)(NULL),(char*)(point),head);
             break;
         case CMP_TARGET_PASSAGE:
             CompasObj.AddTarget(type,(uvsPassage*)(NULL),(char*)(point),head);
             break;
         case CMP_TARGET_SENSOR:
             CompasObj.AddTarget(type,(ActionUnit*)(NULL),(char*)(point),head);
             break;
     };
 };
References CompasObject::AddTarget(), CMP_TARGET_ESCAVE, CMP_TARGET_PASSAGE, CMP_TARGET_SENSOR, CMP_TARGET_SPOT, CompasObj, head, and NULL.
Referenced by GeneralSystemOpen().
addVanger() [1/4]
VangerUnit* addVanger (uvsVanger * p, int x, int y, int Human)
 {
     VangerUnit* n;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         n->CreateUnitType(p);
         if(Human){
             if(GeneralMapReload){
                 if(GeneralLoadReleaseFlag) vMap->release();
                 ViewX = x;
                 preViewY = ViewY = y;
                 vMap->reload(CurrentWorld);
                 GeneralMapReload = 0;
 #ifndef NEW_TNT
                 RestoreFlagBarell();
                 RestoreBarell();
 #endif
             };
             MLCheckQuant();
             ActD.CreateActive(n);
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,Vector(x,y,128),0,SET_3D_DIRECT_PLACE);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,Vector(x,y,128),0,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
         if(NetworkON){
             if(Human){
                 n->NetCreateVanger(NULL,NULL,NULL);
                 n->AddFree();
             }else n->NetCreateSlave();
         }else n->AddFree();
         ActD.ConnectObject(n);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddFree(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), CurrentWorld, ModelDispatcher::FindModel(), GeneralLoadReleaseFlag, GeneralMapReload, UnitList::GetObject(), MLCheckQuant(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, uvsVanger::Pmechos, preViewY, vrtMap::release(), vrtMap::reload(), SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, uvsMechos::type, uvsMechosTable, ViewX, ViewY, and vMap.
Referenced by CheckPlayerList(), uvsVanger::makeJump(), uvsVanger::Quant(), uvsRestoreVanger(), and uvsWorldReload().
addVanger() [2/4]
VangerUnit* addVanger (uvsVanger * p, uvsEscave * origin, int Human)
 {
     int ang;
     VangerUnit* n;
     SensorDataType* s;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(origin->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddInEscave");
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(origin->locked)
 //      ErrH.Abort("Bad Locked Escave");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         s = origin->unitPtr.EnterT->GetCenter();
         if(Human){
             if(GeneralMapReload){
                 if(GeneralLoadReleaseFlag) vMap->release();
                 ViewX = s->R_curr.x;
                 preViewY = ViewY = s->R_curr.y;
                 vMap->reload(CurrentWorld);
                 GeneralMapReload = 0;
 #ifndef NEW_TNT
                 RestoreFlagBarell();
                 RestoreBarell();
 #endif
             };
             MLCheckQuant();
         };
         ((origin->unitPtr).EnterT)->ActiveCenter();
         n->CreateUnitType(p);
         if(s->Owner->Type == EngineTypeList::ESCAVE) ang = ((EscaveEngine*)(s->Owner))->StartAngle;
         else ang = RND(PI*2);
         if(Human){
             ActD.CreateActive(n);
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,s->R_curr,ang,SET_3D_DIRECT_PLACE);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,s->R_curr,ang,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
         n->AddEscave(s);
         ActD.ConnectObject(n);
         if(NetworkON){
             if(Human) n->NetCreateVanger(NULL,origin,NULL);
             else n->NetCreateSlave();
         };
         if(Human)
             ActD.PromptInit(1);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddEscave(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), CurrentWorld, EngineTypeList::ESCAVE, ModelDispatcher::FindModel(), GeneralLoadReleaseFlag, GeneralMapReload, UnitList::GetObject(), MLCheckQuant(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, SensorDataType::Owner, PI, uvsVanger::Pmechos, preViewY, ActionDispatcher::PromptInit(), GeneralObject::R_curr, vrtMap::release(), vrtMap::reload(), RND(), SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, LocationEngine::Type, uvsMechos::type, uvsMechosTable, ViewX, ViewY, vMap, Vector::x, and Vector::y.
addVanger() [3/4]
VangerUnit* addVanger (uvsVanger * p, uvsPassage * origin, int Human)
 {
     VangerUnit* n;
     SensorDataType* s;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(origin->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddInPassage");
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(origin->locked)
 //      ErrH.Abort("Bad locked Passage");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         n->CreateUnitType(p);
         s = ((origin->unitPtr).PassageT)->ActionLink;
         if(Human){
             ActD.CreateActive(n);
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,s->R_curr,0,SET_3D_DIRECT_PLACE);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,s->R_curr,0,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
 //      n->AddPassage(s);
         if(NetworkON){
             if(Human){
                 n->NetCreateVanger(origin,NULL,NULL);
                 n->AddPassage(s);
             }else n->NetCreateSlave();
         }else n->AddPassage(s);
 //      if(NetworkON){
 //          if(Human) n->NetCreateVanger(origin,NULL,NULL);
 //          else n->NetCreateSlave();
 //      };
         ActD.ConnectObject(n);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddPassage(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), ModelDispatcher::FindModel(), UnitList::GetObject(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, uvsVanger::Pmechos, GeneralObject::R_curr, SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, uvsMechos::type, and uvsMechosTable.
addVanger() [4/4]
VangerUnit* addVanger (uvsVanger * p, uvsSpot * origin, int Human)
 {
     VangerUnit* n;
     SensorDataType* s;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(origin->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddInSpot");
 //  if(origin->locked)
 //      ErrH.Abort("Bad locked Spot");
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         s = ((origin->unitPtr).EnterT)->GetCenter();
         if(Human){
             if(GeneralMapReload){
                 if(GeneralLoadReleaseFlag) vMap->release();
                 ViewX = s->R_curr.x;
                 preViewY = ViewY = s->R_curr.y;
                 vMap->reload(CurrentWorld);
                 GeneralMapReload = 0;
 #ifndef NEW_TNT
                 RestoreFlagBarell();
                 RestoreBarell();
 #endif
             };
             MLCheckQuant();
         };
         ((origin->unitPtr).EnterT)->ActiveCenter();
         n->CreateUnitType(p);
         if(Human){
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,s->R_curr,0,SET_3D_DIRECT_PLACE);
             ActD.CreateActive(n);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,s->R_curr,0,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
         n->AddSpot(s);
         ActD.ConnectObject(n);
         if(NetworkON){
             if(Human) n->NetCreateVanger(NULL,NULL,origin);
             else n->NetCreateSlave();
         };
         if(Human)
             ActD.PromptInit(0);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddSpot(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), CurrentWorld, ModelDispatcher::FindModel(), GeneralLoadReleaseFlag, GeneralMapReload, UnitList::GetObject(), MLCheckQuant(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, uvsVanger::Pmechos, preViewY, ActionDispatcher::PromptInit(), GeneralObject::R_curr, vrtMap::release(), vrtMap::reload(), SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, uvsMechos::type, uvsMechosTable, ViewX, ViewY, vMap, Vector::x, and Vector::y.
aOutStr()
void aOutStr (int x, int y, int font, int color, unsigned char * str, int space)
 {
     int i,j,s,xs,ys,offs = 0,sz = strlen((char*)str),X = 0,Y = 0,col1,col2;
     unsigned char* palBuf = palbuf;
     col1 = color & ACI_COLOR_MASK;
     col2 = (color >> 8) & ACI_COLOR_MASK;
     if(aScrFonts[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     unsigned char* p = aScrFonts[font] -> data;
     xs = aScrFonts[font] -> SizeX;
     ys = aScrFonts[font] -> SizeY;
     X = x;
     if(col2){
         for(s = 0; s < sz; s ++){
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             for(i = 0; i < ys; i ++){
                 Y = y + i;
                 for(j = 0; j < xs; j ++){
                     switch(p[offs + j]){
                         case 1:
                             XGR_SetPixel(X + j,Y,col1);
                             break;
                         case 2:
                             XGR_SetPixel(X + j,Y,col2);
                             break;
                     }
                 }
                 offs += xs;
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
     else {
         for(s = 0; s < sz; s ++){
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             for(i = 0; i < ys; i ++){
                 Y = y + i;
                 for(j = 0; j < xs; j ++){
                     switch(p[offs + j]){
                         case 1:
                             XGR_SetPixel(X + j,Y,col1);
                             break;
                     }
                 }
                 offs += xs;
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
 }
References XErrorHandler::Abort(), ACI_COLOR_MASK, aScrFonts, ErrH, NULL, palbuf, and XGR_SetPixel.
aOutText32clip()
void aOutText32clip (int x, int y, int color, void * text, int font, int hspace, int vspace)
 {
     int s,xs,ys,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     int color_size,chr;
     unsigned char* str_buf;
     if(aScrFonts32[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     color_size = (color >> 16) & 0xFF;
     color &= 0xFFFF;
     unsigned char* p = aScrFonts32[font] -> data;
     xs = aScrFonts32[font] -> SizeX;
     ys = aScrFonts32[font] -> SizeY;
     str_buf = (unsigned char*)text;
     X = x;
     Y = y;
     for(s = 0; s < sz; s ++){
         chr = str_buf[s];
         if(chr != '\n'){
             if(chr != '\r'){
                 X -= aScrFonts32[font] -> LeftOffs[chr];
                 offs = xs * ys * chr;
                 aciPutSpr32clip(X,Y,xs,ys,p + offs,color,color_size);
                 X += xs + hspace - aScrFonts32[font] -> RightOffs[chr];
             }
         }
         else {
             X = x;
             Y += ys + vspace;
         }
     }
 }
References XErrorHandler::Abort(), aciPutSpr32clip(), aScrFonts32, ErrH, and NULL.
Referenced by VangerUnit::DrawQuant().
aPutStr()
void aPutStr (int x, int y, int font, int color, unsigned char * str, int bsx, unsigned char * buf, int space)
 {
     int i,j,s,xs,ys,offs = 0,sz = strlen((char*)str),X = 0,col1,col2,col3,col4;
     int buf_index = 0,buf_offs = 0;
     col1 = color & ACI_COLOR_MASK;
     col2 = (color >> 8) & ACI_COLOR_MASK;
     col3 = (color >> 16) & ACI_COLOR_MASK;
     col4 = (color >> 24) & ACI_COLOR_MASK;
     if(aScrFonts[font] == NULL)
         ErrH.Abort("MISSING FONT...");
     unsigned char* p = aScrFonts[font] -> data;
     xs = aScrFonts[font] -> SizeX;
     ys = aScrFonts[font] -> SizeY;
     buf_index = x + y * bsx;
     if(col2){
         for(s = 0; s < sz; s ++){
             buf_offs = 0;
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             if((col3 || col4) && ((str[s] >= 48 && str[s] <= 57) || str[s] == 36)){
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col3;
                                 break;
                             case 2:
                                 buf[X + j + buf_index + buf_offs] = col4;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             else {
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col1;
                                 break;
                             case 2:
                                 buf[X + j + buf_index + buf_offs] = col2;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
     else {
         for(s = 0; s < sz; s ++){
             buf_offs = 0;
             offs = ys * str[s];
             X -= aScrFonts[font] -> LeftOffs[str[s]];
             offs = xs * ys * str[s];
             if(col3 && ((str[s] >= 48 && str[s] <= 57) || str[s] == 36)){
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col3;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             else {
                 for(i = 0; i < ys; i ++){
                     for(j = 0; j < xs; j ++){
                         switch(p[offs + j]){
                             case 1:
                                 buf[X + j + buf_index + buf_offs] = col1;
                                 break;
                         }
                     }
                     offs += xs;
                     buf_offs += bsx;
                 }
             }
             X += xs + space - aScrFonts[font] -> RightOffs[str[s]];
         }
     }
 }
References XErrorHandler::Abort(), ACI_COLOR_MASK, aScrFonts, ErrH, and NULL.
Referenced by aPutNum().
AxisLen()
void AxisLen (Vector vA0, Vector vA1, Vector vC, Vector & vR)
 {
     Vector vTrack,vCheck;
     int dAp,dC,dA;
     vTrack = Vector(getDistX(vA1.x,vA0.x),getDistY(vA1.y,vA0.y),vA1.z - vA0.z);
     vCheck = Vector(getDistX(vC.x,vA0.x),getDistY(vC.y,vA0.y),vC.z - vA0.z);
     dAp = vTrack.vabs();
     dC = vCheck.vabs();
     vCheck.x = vCheck.x * vTrack.x;
     vCheck.y = vCheck.y * vTrack.y;
     vCheck.z = vCheck.z * vTrack.z;
     dA = (vCheck.x + vCheck.y + vCheck.z)/dAp;
     vR = vA0 + (dA * vTrack / dAp);
     cycleTor(vR.x,vR.y);
     /*line_trace(Vector(vA0.x,vA0.y,159),Vector(vA1.x,vA1.y,159));
     line_trace(Vector(vA0.x,vA0.y,159),Vector(vC.x,vC.y,159));
     line_trace(Vector(vR.x,vR.y,159),Vector(vC.x,vC.y,159));*/
 };
References cycleTor(), getDistX(), getDistY(), Vector::vabs(), Vector::x, Vector::y, and Vector::z.
BunchEvent()
void BunchEvent (int type)
 {
     GeneralObject* p;
     switch(type){
         case BUNCH_CHANGE_CYCLE:
             if(CurrentWorld >= MAIN_WORLD_MAX - 1) return;
             WorldPalCurrent = uvsCurrentCycle;
             if(WorldPalCurrent >= WorldPalNum) WorldPalCurrent = 0;
 //          StartSetColor(100,WorldPalData[WorldPalCurrent]);
             PalCD.Set(CPAL_CHANGE_CYCLE,100,WorldPalData[WorldPalCurrent]);
             p = FarmerD.Tail;
             while(p){
 //              if(p->ID != ID_SKYFARMER)
 //                  ErrH.Abort("Bad SkyFarmer List");
                 ((SkyFarmerObject*)(p))->skyfarmer_end();
                 p = p->NextTypeList;
             };
             ActD.PromptChangeCycle();
             break;
     };
 };
References ActD, BUNCH_CHANGE_CYCLE, CPAL_CHANGE_CYCLE, CurrentWorld, FarmerD, MAIN_WORLD_MAX, GeneralObject::NextTypeList, PalCD, ActionDispatcher::PromptChangeCycle(), PalConstructor::Set(), UnitListType::Tail, uvsCurrentCycle, WorldPalCurrent, WorldPalData, and WorldPalNum.
Referenced by uvsBunch::Quant().
calc_view_factors()
void calc_view_factors ()
 {
     //if(!(XRec.flags & (XRC_RECORD_MODE | XRC_PLAY_MODE)) && prev_frame_time)
     //Stalkerg
     if((speed_correction_enabled | NetworkON) && prev_frame_time){
         int dt = SDL_GetTicks() - prev_frame_time;
         if(dt > 15 && dt < 200) {
             speed_correction_factor = (double)dt*((double)STANDART_FRAME_RATE/1000.)*speed_correction_tau + speed_correction_factor*(1 - speed_correction_tau);
         }
     } else {
         speed_correction_factor = 1;
     }
     //speed_correction_factor = 1;
     //std::cout<<"DT::"<<SDL_GetTicks() - prev_frame_time<<std::endl;
     prev_frame_time = SDL_GetTicks();
     cycleTor(ViewX,ViewY);
     TurnSecY = curGMap -> ysize*TurnSecX/curGMap -> xsize;
     TurnSideX = TurnSecX >> 1;
     TurnSideY = TurnSecY >> 1;
     ViewZ = focus*TurnSecX/curGMap -> xsize;
     ScaleMapFlt = (double)TurnSecX/curGMap -> xsize;
     ScaleMapInvFlt = (double)curGMap -> xsize/TurnSecX;
     ScaleMap = round(ScaleMapFlt*256);
     ScaleMapInv = round(ScaleMapInvFlt*256);
     DepthShow = SlopeAngle < -PI/512;
     ModulatedNORMAL = (double)NORMAL*light_modulation/256.;
     Light = Vector(DBV(ModulatedNORMAL,0,ModulatedNORMAL*SHADOWDEEP/256.).norm(ModulatedNORMAL));
     CurrShadowDirection =  DBV(-Cos(TurnAngle),-Sin(TurnAngle),(double)SHADOWDEEP/256.);
     if(DepthShow){
         A_g2s = DBM(SlopeAngle,X_AXIS)*DBM(TurnAngle,Z_AXIS);
         A_s2g = DBM(-TurnAngle,Z_AXIS)*DBM(-SlopeAngle,X_AXIS);
     } else {
         A_g2s = DBM(TurnAngle,Z_AXIS);
         A_s2g = DBM(-TurnAngle,Z_AXIS);
     }
     A_g2sZ = A_g2s*DBM(1,1,-1,DIAGONAL);
     sinTurnInvFlt = sinTurnFlt = Sin(TurnAngle);
     cosTurnInvFlt =cosTurnFlt = Cos(TurnAngle);
     sinTurnFlt *= ScaleMapInvFlt;
     cosTurnFlt *= ScaleMapInvFlt;
     sinTurnInvFlt *= ScaleMapFlt;
     cosTurnInvFlt *= ScaleMapFlt;
     sinTurn = round(UNIT*sinTurnFlt);
     cosTurn = round(UNIT*cosTurnFlt);
     sinTurnInv = round(UNIT*sinTurnInvFlt);
     cosTurnInv = round(UNIT*cosTurnInvFlt);
     // Inverse factors calculation
     double M_x = A_g2s[0]*focus_flt;
     double N_x = A_g2s[1]*focus_flt;
     double M_y = A_g2s[3]*focus_flt;
     double N_y = A_g2s[4]*focus_flt;
     double M_z = A_g2s[6];
     double N_z = A_g2s[7];
     double H = ViewZ << 16;
     Ha = N_y*H;
     Va = -N_x*H;
     Hb = -M_y*H;
     Vb = M_x*H;
     Oc = M_x*N_y - M_y*N_x;
     Hc = M_y*N_z - M_z*N_y;
     Vc = M_z*N_x - M_x*N_z;
 }
References A_g2s, A_g2sZ, A_s2g, Cos(), cosTurn, cosTurnFlt, cosTurnInv, cosTurnInvFlt, curGMap, CurrShadowDirection, cycleTor(), DepthShow, DIAGONAL, focus, focus_flt, Ha, Hb, Hc, Light, light_modulation, ModulatedNORMAL, NetworkON, NORMAL, Oc, PI, prev_frame_time, round(), ScaleMap, ScaleMapFlt, ScaleMapInv, ScaleMapInvFlt, SHADOWDEEP, Sin(), sinTurn, sinTurnFlt, sinTurnInv, sinTurnInvFlt, SlopeAngle, speed_correction_enabled, speed_correction_factor, speed_correction_tau, STANDART_FRAME_RATE, TurnAngle, TurnSecX, TurnSecY, TurnSideX, TurnSideY, UNIT, Va, Vb, Vc, ViewX, ViewY, ViewZ, X_AXIS, and Z_AXIS.
Referenced by camera_quant(), and iGameMap::change().
camera_direct()
void camera_direct (int X, int Y, int zoom, int Turn, int Slope, int num_frames)
 {
     // Where zoom is between  MIN_ZOOM and MAX_ZOOM
     double time = (double)num_frames * XTCORE_FRAME_NORMAL;
     camera_moving_log = num_frames;
     camera_vx = (double)getDistX(X, ViewX) / time;
     camera_vy = (double)getDistY(Y, ViewY) / time;
     camera_vz = (double)((curGMap -> xsize*zoom >> 8) - TurnSecX)/time;
     camera_vs = (double)(-Slope - SlopeAngle) / time;
     camera_vt += (double)DistPi(Turn,TurnAngle) / time;
 }
References camera_moving_log, camera_vs, camera_vt, camera_vx, camera_vy, camera_vz, curGMap, DistPi(), getDistX(), getDistY(), SlopeAngle, TurnAngle, TurnSecX, ViewX, ViewY, and XTCORE_FRAME_NORMAL.
Referenced by VangerUnit::AddPassage(), VangerUnit::InitEnvironment(), VangerUnit::SensorQuant(), and XpeditionOFF().
camera_impulse()
void camera_impulse (int amplitude_8)
 {
     camera_vt += (camera_turn_impulse - (int)RND(2*camera_turn_impulse))*amplitude_8 >> 8;
 }
References camera_turn_impulse, camera_vt, and RND().
Referenced by VangerUnit::Destroy(), VangerUnit::keyhandler(), and BulletObject::Touch().
camera_quant() [1/2]
void camera_quant ()
 {
     int t, t2;
     camera_x += camera_vx;
     ViewX += (t = round(camera_x)) * XTCORE_FRAME_NORMAL;
     camera_x -= t;
     camera_y += camera_vy;
     ViewY += (t = round(camera_y)) * XTCORE_FRAME_NORMAL;
     camera_y -= t;
     camera_z += camera_vz;
     TurnSecX += (t = round(camera_z)) * XTCORE_FRAME_NORMAL;
     if (TurnSecX < MIN_ZOOM) {
         TurnSecX = MIN_ZOOM;
     }
     camera_z -= t;
     camera_s += camera_vs;
     SlopeAngle += (t = round(camera_s)) * XTCORE_FRAME_NORMAL;
     if(SlopeAngle < -SLOPE_MAX)
         SlopeAngle = -SLOPE_MAX;
     camera_s -= t;
     camera_t += camera_vt;
     TurnAngle += (t = round(camera_t)) * XTCORE_FRAME_NORMAL;
     camera_t -= t;
     calc_view_factors();
 }
References calc_view_factors(), camera_s, camera_t, camera_vs, camera_vt, camera_vx, camera_vy, camera_vz, camera_x, camera_y, camera_z, MIN_ZOOM, round(), SLOPE_MAX, SlopeAngle, TurnAngle, TurnSecX, ViewX, ViewY, and XTCORE_FRAME_NORMAL.
camera_quant() [2/2]
void camera_quant (int X, int Y, int Turn, double V_abs)
{
     if(stop_camera)
         return;
     int t,dx,dy;
     if(!camera_moving_xy_enable) {
         dx = getDistX(X,camera_X_prev);
         dy = getDistY(Y,camera_Y_prev);
         if(dx < 400 && dy < 400) {
             ViewX += dx;
             ViewY += dy;
         } else {
             ViewX = X;
             ViewY = Y;
         }
     }
     dx = getDistX(X,ViewX);
     dy = getDistY(Y,ViewY);
     if(dx > 400 || dy > 400){
         ViewX = X;
         ViewY = Y;
     } else {
         camera_vx += (double)dx*camera_mi * XTCORE_FRAME_NORMAL;
         camera_vx *= camera_drag;
         camera_x += camera_vx * XTCORE_FRAME_NORMAL;
         ViewX += (t = round(camera_x));
         camera_x -= t;
         camera_vy += (double)dy*camera_mi * XTCORE_FRAME_NORMAL;
         camera_vy *= camera_drag;
         camera_y += camera_vy * XTCORE_FRAME_NORMAL;
         ViewY += (t = round(camera_y));
         camera_y -= t;
     }
     if(time_vibration) {
         static int phase_vibration;
         double k = A_vibration*exp(-alpha_vibration*time_vibration);
         double t = oscillar_vibration*(time_vibration + phase_vibration);
         ViewX += round(k*sin(1.276*t)+.8*sin(2.878*t)+0.3*sin(23.876*t)) * XTCORE_FRAME_NORMAL;
         ViewY += round(k*sin(0.981*t)+.8*sin(2.98*t)+0.3*sin(20.82*t)) * XTCORE_FRAME_NORMAL;
         if(time_vibration++ > max_time_vibration) {
             time_vibration = 0;
             phase_vibration = realRND(1367339);
         }
     }
     camera_X_prev = X;
     camera_Y_prev = Y;
     int TurnSecX_old = TurnSecX;
     int z = camera_moving_z_enable ? (V_abs < camera_vmax ? camera_zmin + ((curGMap -> xsize*MAX_ZOOM >> 8) - camera_zmin)*V_abs/camera_vmax : camera_zmax)
                     : camera_zmin;
     camera_vz += (double)(z - TurnSecX)*camera_miz * XTCORE_FRAME_NORMAL;
     //camera_vz -= camera_vz*camera_dragz;
     camera_vz *= camera_dragz*pow(0.97,camera_vz_min/(fabs(camera_vz) + 1e-10));
     camera_z += camera_vz * XTCORE_FRAME_NORMAL;
     TurnSecX += (t = round(camera_z));
     camera_z -= t;
     if(TurnSecX > (t = curGMap -> xsize*(RAM16 ? MAX_ZOOM_16 : MAX_ZOOM) >> 8))
         TurnSecX = t;
     if(TurnSecX < (t = curGMap -> xsize*MIN_ZOOM >> 8))
         TurnSecX = t;
     if(RAM16 && (SlopeAngle || TurnAngle) && TurnSecX > curGMap -> xsize)
         TurnSecX = TurnSecX_old;
     if(abs(TurnSecX - curGMap -> xsize) < 4)
         TurnSecX = curGMap -> xsize;
     int s = camera_slope_enable ? (V_abs < camera_vmax ? camera_slope_min + (-SLOPE_MAX - camera_slope_min)*V_abs/camera_vmax : -SLOPE_MAX)
                     : camera_slope_min;
     camera_vs += (double)(s - SlopeAngle)*camera_mis * XTCORE_FRAME_NORMAL;
     camera_vs *= camera_drags*pow(0.97,camera_vs_min/(fabs(camera_vs) + 1e-10));
     camera_s += camera_vs * XTCORE_FRAME_NORMAL;
     SlopeAngle += (t = round(camera_s));
     if(SlopeAngle < -SLOPE_MAX)
         SlopeAngle = -SLOPE_MAX;
     camera_s -= t;
     if(RAM16 && (TurnSecX > curGMap -> xsize || TurnAngle) && SlopeAngle)
         SlopeAngle  = 0;
     if(abs(DistPi(SlopeAngle,0)) < 8)
         SlopeAngle = 0;
     camera_vt += (double)DistPi(camera_rotate_enable ? Turn : 0,TurnAngle)*camera_mit * XTCORE_FRAME_NORMAL;
     camera_vt *= camera_dragt*pow(0.97,camera_vt_min/(fabs(camera_vt) + 1e-10));
     camera_vi *= camera_dragi*pow(0.97,camera_vt_min/(fabs(camera_vi) + 1e-10));
     camera_t += camera_vt*XTCORE_FRAME_NORMAL + camera_vi;
     TurnAngle += (t = round(camera_t));
     camera_t -= t;
     if(RAM16 && (TurnSecX > curGMap -> xsize || SlopeAngle) && TurnAngle)
         TurnAngle  = 0;
     if(abs(DistPi(TurnAngle,0)) < 8)
         TurnAngle = 0;
     calc_view_factors();
 }
References A_vibration, alpha_vibration, calc_view_factors(), camera_drag, camera_dragi, camera_drags, camera_dragt, camera_dragz, camera_mi, camera_mis, camera_mit, camera_miz, camera_moving_xy_enable, camera_moving_z_enable, camera_rotate_enable, camera_s, camera_slope_enable, camera_slope_min, camera_t, camera_vi, camera_vmax, camera_vs, camera_vs_min, camera_vt, camera_vt_min, camera_vx, camera_vy, camera_vz, camera_vz_min, camera_x, camera_X_prev, camera_y, camera_Y_prev, camera_z, camera_zmax, camera_zmin, curGMap, DistPi(), getDistX(), getDistY(), max_time_vibration, MAX_ZOOM, MAX_ZOOM_16, MIN_ZOOM, oscillar_vibration, RAM16, realRND(), round(), SLOPE_MAX, SlopeAngle, stop_camera, time_vibration, TurnAngle, TurnSecX, ViewX, ViewY, and XTCORE_FRAME_NORMAL.
Referenced by ActionDispatcher::CameraQuant(), and creat_poster().
camera_reset()
void camera_reset ()
                     {
     camera_x=0;
     camera_vx=0;
     camera_y=0;
     camera_vy=0;
     camera_z=0;
     camera_vz=0;
     camera_t=0;
     camera_vt=0;
     camera_vi=0;
     camera_s=0;
     camera_vs=0;
     camera_moving_log = 0;
     camera_moving_xy_enable = camera_moving_z_enable = iGetOptionValue(iCAMERA_SCALE);
     camera_slope_enable = iGetOptionValue(iCAMERA_SLOPE);
     camera_rotate_enable = iGetOptionValue(iCAMERA_TURN);
 }
References camera_moving_log, camera_moving_xy_enable, camera_moving_z_enable, camera_rotate_enable, camera_s, camera_slope_enable, camera_t, camera_vi, camera_vs, camera_vt, camera_vx, camera_vy, camera_vz, camera_x, camera_y, camera_z, iCAMERA_SCALE, iCAMERA_SLOPE, iCAMERA_TURN, and iGetOptionValue().
Referenced by ActionDispatcher::CameraQuant(), and iGameMap::reset().
ChargeDevice()
int ChargeDevice (VangerUnit * p, int ind, int sign)
 {
     StuffObject* n;
     int c_log = 0;
     if(p->Status & SOBJ_ACTIVE){
         n = p->DeviceData;
         while(n){
             if(n->ActIntBuffer.type == ind){
                 if(sign > 0){
                     if(n->ActIntBuffer.data1 < uvsItemTable[n->uvsDeviceType]->param2){
                         c_log = 1;
                         n->ActIntBuffer.data1 = uvsItemTable[n->uvsDeviceType]->param2;
                         n->ActIntBuffer.type = uvsSetItemType(n->uvsDeviceType,n->ActIntBuffer.data0,n->ActIntBuffer.data1);
                         aciChangeItem(&(n->ActIntBuffer));
                     };
                 }else{
                     if(n->ActIntBuffer.data1 > 0){
                         c_log = 1;
                         n->ActIntBuffer.data1 = 0;
                         n->ActIntBuffer.type = uvsSetItemType(n->uvsDeviceType,n->ActIntBuffer.data0,n->ActIntBuffer.data1);
                         aciChangeItem(&(n->ActIntBuffer));
                     };
                 };
             };
             n = n->NextDeviceList;
         };
         if(sign){
             if(c_log){
                 aiMessageQueue.Send(AI_MESSAGE_COPTER,p->Speed,2,0);//aiMessageData[AI_MESSAGE_COPTER].Send(p->Speed,2,0);
                 SOUND_CHARGE_RIGS();
             };
         }else{
             if(c_log){
                 aiMessageQueue.Send(AI_MESSAGE_DCOPTER,p->Speed,1,0);//aiMessageData[AI_MESSAGE_DCOPTER].Send(p->Speed,1,0);
                 SOUND_DISCHARGE();
             };
         };
     }else{
         n = p->DeviceData;
         while(n){
             if(n->ActIntBuffer.type == ind){
                 if(sign > 0){
                     if(n->ActIntBuffer.data1 < uvsItemTable[n->uvsDeviceType]->param2){
                         c_log = 1;
                         n->ActIntBuffer.data1 = uvsItemTable[n->uvsDeviceType]->param2;
                         n->ActIntBuffer.type = uvsSetItemType(n->uvsDeviceType,n->ActIntBuffer.data0,n->ActIntBuffer.data1);
                     };
                 }else{
                     if(n->ActIntBuffer.data1 > 0){
                         c_log = 1;
                         n->ActIntBuffer.data1 = 0;
                         n->ActIntBuffer.type = uvsSetItemType(n->uvsDeviceType,n->ActIntBuffer.data0,n->ActIntBuffer.data1);
                     };
                 };
             };
             n = n->NextDeviceList;
         };
     };
     return c_log;
 };
References aciChangeItem(), StuffObject::ActIntBuffer, AI_MESSAGE_COPTER, AI_MESSAGE_DCOPTER, aiMessageQueue, actintItemData::data0, actintItemData::data1, uvsUnitType::DeviceData, StuffObject::NextDeviceList, uvsItemType::param2, aiMessageList::Send(), SOBJ_ACTIVE, SOUND_CHARGE_RIGS, SOUND_DISCHARGE, ActionUnit::Speed, actintItemData::type, StuffObject::uvsDeviceType, uvsItemTable, and uvsSetItemType().
Referenced by VangerUnit::TouchSensor().
ChargeWeapon()
int ChargeWeapon (VangerUnit * p, int ind, int sign)
 {
     StuffObject* n;
     int c_log = 0;
     n = p->DeviceData;
     while(n){
         if(n->ActIntBuffer.type == ind){
             if(sign > 0){
                 if(n->ActIntBuffer.data1 < uvsItemTable[n->uvsDeviceType]->param2){
                     c_log = 1;
                     n->ActIntBuffer.data1 = uvsItemTable[n->uvsDeviceType]->param2;
                 };
             }else{
                 if(n->ActIntBuffer.data1 > 0){
                     c_log = 1;
                     n->ActIntBuffer.data1 = 0;
                 };
             };
         };
         n = n->NextDeviceList;
     };
     if(p->Status & SOBJ_ACTIVE){
         if(sign){
             if(c_log){
                 switch(ind){
                     case ACI_MACHOTINE_GUN_LIGHT:
                     case ACI_MACHOTINE_GUN_HEAVY:
                         aiMessageQueue.Send(AI_MESSAGE_MACHOTINE,p->Speed,1,0);//aiMessageData[AI_MESSAGE_MACHOTINE].Send(p->Speed,1,0);
                         SOUND_CHARGE_MACHOTIN();
                         break;
                     case ACI_GHORB_GEAR_LIGHT:
                     case ACI_GHORB_GEAR_HEAVY:
                         aiMessageQueue.Send(AI_MESSAGE_GHORB,p->Speed,2,0);//aiMessageData[AI_MESSAGE_GHORB].Send(p->Speed,2,0);
                         SOUND_CHARGE_GHORB();
                         break;
                 };
             };
         }else{
             if(c_log){
                 switch(ind){
                     case ACI_GHORB_GEAR_LIGHT:
                     case ACI_GHORB_GEAR_HEAVY:
                         aiMessageQueue.Send(AI_MESSAGE_DGHORB,p->Speed,1,0);//aiMessageData[AI_MESSAGE_DGHORB].Send(p->Speed,1,0);
                         SOUND_DISCHARGE();
                         break;
                 };
             };
         };
     };
     return c_log;
 };
References ACI_GHORB_GEAR_HEAVY, ACI_GHORB_GEAR_LIGHT, ACI_MACHOTINE_GUN_HEAVY, ACI_MACHOTINE_GUN_LIGHT, StuffObject::ActIntBuffer, AI_MESSAGE_DGHORB, AI_MESSAGE_GHORB, AI_MESSAGE_MACHOTINE, aiMessageQueue, actintItemData::data1, uvsUnitType::DeviceData, StuffObject::NextDeviceList, uvsItemType::param2, aiMessageList::Send(), SOBJ_ACTIVE, SOUND_CHARGE_GHORB, SOUND_CHARGE_MACHOTIN, SOUND_DISCHARGE, ActionUnit::Speed, actintItemData::type, StuffObject::uvsDeviceType, and uvsItemTable.
Referenced by VangerUnit::AutomaticTouchSensor(), VangerUnit::DrawQuant(), and VangerUnit::TouchSensor().
CheckAddLink()
char CheckAddLink (LinkType * l, BranchType * b, int s)
 {
 // l - Next Link
 /*  l += s;
     if((int)(l) >= (int)(b->Link + b->NumLink)) return 0;
     return 1;*/
     if(((uintptr_t)(l) + s*sizeof(LinkType)) >= (uintptr_t)(b->Link + b->NumLink)) return 0;
     return 1;
 };
References BranchType::Link, and BranchType::NumLink.
Referenced by TrackUnit::DirectQuant().
CheckDecLink()
char CheckDecLink (LinkType * l, BranchType * b, int s)
 {
 // l - Prev Link
 /*  l -= s;
     if(int(l) < (int)(b->Link)) return 0;
     return 1;*/
     if(((uintptr_t)(l) - s*sizeof(LinkType)) < (uintptr_t)(b->Link)) return 0;
     return 1;
 };
References BranchType::Link.
Referenced by TrackUnit::DirectQuant().
CheckInBranch()
char CheckInBranch (Vector & v, LinkType * pl, LinkType * nl, BranchType * b)
 {
     char i;
     for(i = 0;i < CHECK_BRANCH_DELTA;i++){
         if(GetAngle(v.x,v.y,nl->xl,nl->yl,nl->xr,nl->yr) < 0){
             nl++;
             if(nl >= b->Link + b->NumLink) return 0;
             else pl++;
         }else{
             if(GetAngle(v.x,v.y,pl->xr,pl->yr,pl->xl,pl->yl) < 0){
                 nl--;
                 if(nl <= b->Link) return 0;
                 else pl--;
             }else{
                 if(GetAngle(v.x,v.y,pl->xl,pl->yl,nl->xl,nl->yl) < 0) return 0;
                 else{
                     if(GetAngle(v.x,v.y,nl->xr,nl->yr,pl->xr,pl->yr) < 0) return 0;
                     else return 1;
                 };
             };
         };
     };
     return 0;
 };
References CHECK_BRANCH_DELTA, GetAngle(), BranchType::Link, BranchType::NumLink, Vector::x, LinkType::xl, LinkType::xr, Vector::y, LinkType::yl, and LinkType::yr.
Referenced by TrackUnit::ActiveGetBranch(), TrackUnit::GetBranch(), TrackType::GetPosition(), and TrackUnit::TestAnalysis().
CheckInLink()
char CheckInLink (Vector & v, LinkType * pl, LinkType * nl)
 {
     if(GetAngle(v.x,v.y,nl->xl,nl->yl,nl->xr,nl->yr) < 0) return 0; // NEXT
     if(GetAngle(v.x,v.y,pl->xr,pl->yr,pl->xl,pl->yl) < 0) return 0; // PREV
     if(GetAngle(v.x,v.y,pl->xl,pl->yl,nl->xl,nl->yl) < 0) return 0; // LEFT
     if(GetAngle(v.x,v.y,nl->xr,nl->yr,pl->xr,pl->yr) < 0) return 0; // RIGHT
     return 1;
 };
References GetAngle(), Vector::x, LinkType::xl, LinkType::xr, Vector::y, LinkType::yl, and LinkType::yr.
Referenced by TrackUnit::GetInside(), and TrackType::GetInsidePosition().
CheckInNode()
char CheckInNode (Vector & v, NodeType * n)
 {
     char i;
     char nn;
     int bx,by,pbx,pby;
     int* dx;
     int* dy;
     nn = n->NumBranch;
     dx = n->BorderX;
     dy = n->BorderY;
     pbx = *dx;
     pby = *dy;
     if(GetAngle(v.x,v.y,dx[nn - 1],dy[nn - 1],pbx,pby) < 0) return 0;
     for(i = 1;i < nn;i++){
         dx++;
         dy++;
         bx = *dx;
         by = *dy;
         if(GetAngle(v.x,v.y,pbx,pby,bx,by) < 0) return 0;
         pbx = bx;
         pby = by;
     };
     return 1;
 };
References NodeType::BorderX, NodeType::BorderY, GetAngle(), NodeType::NumBranch, Vector::x, and Vector::y.
Referenced by TrackUnit::ActiveGetBranch(), TrackUnit::GetBranch(), TrackUnit::GetInside(), TrackType::GetInsidePosition(), TrackType::GetPosition(), and TrackUnit::TestAnalysis().
CheckPlayerList()
void CheckPlayerList (void)
 {
     PlayerData* p;
     VangerUnit* v;
     p = players_list.first();
     while(p){
         if(p->client_ID != GlobalStationID && p->name && p->status == GAMING_STATUS){
             if(p->CreatePlayerFlag == 3 && p->body.NetID == 0)
                 p->CreatePlayerFlag = 0;
             if(p->body.world == CurrentWorld && p->body.NetID != 0 && p->body.CarIndex != 255 && p->CreatePlayerFlag == 0)
                 NetEvent4Uvs(p);
             if(p->CreatePlayerFlag == 1){
                 if(!((uvsVanger*)(p->uvsPoint))->Pescave && !((uvsVanger*)(p->uvsPoint))->Pspot && !((uvsVanger*)(p->uvsPoint))->Ppassage)
                     v = addVanger((uvsVanger*)(p->uvsPoint),p->body.Data0,p->body.Data1);
                 else
                     v = addVanger((uvsVanger*)(p->uvsPoint),((uvsVanger*)(p->uvsPoint))->Ppassage);
                 if(v) v->InitPlayerPoint(p);
             };
         }else{
             if(ActD.Active) ActD.Active->pNetPlayer = p;
         };
         p = (PlayerData*)p -> next;
     };
 };
References ActD, ActionDispatcher::Active, addVanger(), PlayerData::body, PlayerBody::CarIndex, PlayerData::client_ID, PlayerData::CreatePlayerFlag, CurrentWorld, PlayerBody::Data0, PlayerBody::Data1, XTList< Type >::first(), GAMING_STATUS, GlobalStationID, VangerUnit::InitPlayerPoint(), PlayerData::name, NetEvent4Uvs(), PlayerBody::NetID, players_list, VangerUnit::pNetPlayer, PlayerData::status, PlayerData::uvsPoint, and PlayerBody::world.
Referenced by GameObjectDispatcher::Quant().
CheckStartJump()
int CheckStartJump (Object * p)
 {
     return ((VangerUnit*)(p))->CheckStartJump();
 };
Referenced by Object::mechous_analysis().
ClearPhantomTarget()
void ClearPhantomTarget (int id)
 {
     CompasTargetType* p;
     CompasTargetType* pp;
     p = CompasObj.TargetData;
     while(p){
         pp = p->Next;
         if(p->ID == CMP_OBJECT_PHANTOM && (p->Data).ID == id){
             if(CompasObj.CurrentTarget == p) SelectCompasTarget(NULL);
             CompasObj.DeleteTarget(p);
             aciRefreshTargetsMenu();
             return;
         };
         p = pp;
     };
 };
References aciRefreshTargetsMenu(), CMP_OBJECT_PHANTOM, CompasObj, CompasObject::CurrentTarget, CompasTargetType::Data, CompasObject::DeleteTarget(), CompasTargetType::ID, CompasTargetType::Next, NULL, SelectCompasTarget(), and CompasObject::TargetData.
Referenced by NetCheckRemovePlayer(), and ObjectDestroy().
ClearTabutaskTarget()
void ClearTabutaskTarget (void)
 {
     int r_log = 0;
     CompasTargetType* p;
     CompasTargetType* pp;
     p = CompasObj.TargetData;
     while(p){
         pp = p->Next;
         if(p->ID == CMP_OBJECT_VANGER){
             if(p == CompasObj.TargetData)
                 SelectCompasTarget(NULL);
             CompasObj.DeleteTarget(p);
             r_log = 1;
         };
         p = pp;
     };
     if(r_log) aciRefreshTargetsMenu();
 };
References aciRefreshTargetsMenu(), CMP_OBJECT_VANGER, CompasObj, CompasObject::DeleteTarget(), CompasTargetType::ID, CompasTargetType::Next, NULL, SelectCompasTarget(), and CompasObject::TargetData.
Referenced by aiPromptTaskMessage().
CreateArtefactTarget()
void CreateArtefactTarget (StuffObject * n)
 {
     CompasTargetType* p;
     p = CompasObj.TargetData;
     while(p){
         if(p->ID == CMP_OBJECT_ITEM && (p->Data).StuffT == n)
             break;
         p = p->Next;
     };
     if(!p){
         if(lang() == RUSSIAN){
             switch(n->ActIntBuffer.type){
                 case ACI_PROTRACTOR:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,rProtractorCompasTarget);
                     break;
                 case ACI_MECHANIC_MESSIAH:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,rMessiahCompasTarget);
                     break;
                 case ACI_FUNCTION83:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,rFunction83CompasTarget);
                     break;
                 case ACI_SPUMMY:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,rSpummyCompasTarget);
                     break;
             };
         }else{
             switch(n->ActIntBuffer.type){
                 case ACI_PROTRACTOR:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,ProtractorCompasTarget);
                     break;
                 case ACI_MECHANIC_MESSIAH:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,MessiahCompasTarget);
                     break;
                 case ACI_FUNCTION83:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,Function83CompasTarget);
                     break;
                 case ACI_SPUMMY:
                     CompasObj.AddTarget(CMP_OBJECT_ITEM,UnitOrderType(n),NULL,SpummyCompasTarget);
                     break;
             };
         };
     };
 };
References ACI_FUNCTION83, ACI_MECHANIC_MESSIAH, ACI_PROTRACTOR, ACI_SPUMMY, StuffObject::ActIntBuffer, CompasObject::AddTarget(), CMP_OBJECT_ITEM, CompasObj, CompasTargetType::Data, Function83CompasTarget, CompasTargetType::ID, lang(), MessiahCompasTarget, CompasTargetType::Next, NULL, ProtractorCompasTarget, rFunction83CompasTarget, rMessiahCompasTarget, rProtractorCompasTarget, rSpummyCompasTarget, RUSSIAN, SpummyCompasTarget, CompasObject::TargetData, and actintItemData::type.
Referenced by StuffObject::CreateStuff(), and StuffObject::DeviceOut().
CreateBoozeeniadaString()
void CreateBoozeeniadaString (void)
 {
     int i,t,i1,i2,s1,s2;
     char ch;
     CHECK_BSIGN_DATA = new char[NUM_CHECK_BSIGN + 1]; memset(CHECK_BSIGN_DATA, '\0', NUM_CHECK_BSIGN + 1);
     strcpy(CHECK_BSIGN_DATA, "ABCDEFKLMNOPR");
     for(i = 0;i < NUM_CHECK_BSIGN;i++)
         CHECK_BSIGN_INDEX[i] = i;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         i1 = RND(NUM_CHECK_BSIGN);
         i2 = RND(NUM_CHECK_BSIGN);
         if(i1 != i2){
             t = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = CHECK_BSIGN_INDEX[i2];
             CHECK_BSIGN_INDEX[i2] = t;
             ch = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = CHECK_BSIGN_DATA[i2];
             CHECK_BSIGN_DATA[i2] = ch;
         };
     };
     i1 = 1;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         if(CHECK_BSIGN_DATA[i] == 'A'){
             t = CHECK_BSIGN_INDEX[i];
             CHECK_BSIGN_INDEX[i] = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = t;
             ch = CHECK_BSIGN_DATA[i];
             CHECK_BSIGN_DATA[i] = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = ch;
             break;
         };
     };
     i1 = 3;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         if(CHECK_BSIGN_DATA[i] == 'E'){
             t = CHECK_BSIGN_INDEX[i];
             CHECK_BSIGN_INDEX[i] = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = t;
             ch = CHECK_BSIGN_DATA[i];
             CHECK_BSIGN_DATA[i] = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = ch;
             break;
         };
     };
     i1 = 5;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         if(CHECK_BSIGN_DATA[i] == 'O'){
             t = CHECK_BSIGN_INDEX[i];
             CHECK_BSIGN_INDEX[i] = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = t;
             ch = CHECK_BSIGN_DATA[i];
             CHECK_BSIGN_DATA[i] = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = ch;
             break;
         };
     };
     CHECK_BSIGN_DATA[NUM_CONTROL_BSIGN] = '\0';
     for(i = 0;i < 8;i++){
         i1 = RND(2);
         i2 = RND(MAX_TIME_SECRET);
         s1 = RND(2);
         s2 = RND(MAX_TIME_SECRET);
         t = TimeSecretType[i1][i2];
         TimeSecretType[i1][i2] = TimeSecretType[s1][s2];
         TimeSecretType[s1][s2] = t;
     };
     for(i = 0;i < MAX_TIME_SECRET;i++){
         TimeSecretData0[0][i] = 0;
         if(UVS_ITEM_TYPE::POPONKA)
             TimeSecretData1[0][i] = uvsPoponkaID;
         else
             TimeSecretData1[0][i] = 0;
         TimeSecretData0[1][i] = 0;
         if(UVS_ITEM_TYPE::POPONKA)
             TimeSecretData1[1][i] = uvsPoponkaID;
         else
             TimeSecretData1[1][i] = 0;
     };
 };
References CHECK_BSIGN_DATA, CHECK_BSIGN_INDEX, MAX_TIME_SECRET, NUM_CHECK_BSIGN, NUM_CONTROL_BSIGN, UVS_ITEM_TYPE::POPONKA, RND(), TimeSecretData0, TimeSecretData1, TimeSecretType, and uvsPoponkaID.
Referenced by GeneralSystemInit().
CreatePhantomTarget()
void CreatePhantomTarget (void)
 {
     CompasTargetType* n;
     uvsPassage* pass;
     if(my_server_data.GameType == PASSEMBLOSS && UsedCheckNum < GloryPlaceNum){
         n = CompasObj.TargetData;
         while(n){
             if(n -> ID == CMP_OBJECT_VECTOR){
                 if(GloryPlaceData[UsedCheckNum].World == CurrentWorld){
                     (n->Data).vT.x = GloryPlaceData[UsedCheckNum].R_curr.x;
                     (n->Data).vT.y = GloryPlaceData[UsedCheckNum].R_curr.y;
                     (n->Data).vT.z = GloryPlaceData[UsedCheckNum].R_curr.z;
                 }else{
                     pass = GetPassage(CurrentWorld,GloryPlaceData[UsedCheckNum].World);
                     if(pass){
                         (n->Data).vT.x = pass->unitPtr.PassageT->ActionLink->R_curr.x;
                         (n->Data).vT.y = pass->unitPtr.PassageT->ActionLink->R_curr.y;
                         (n->Data).vT.z = pass->unitPtr.PassageT->ActionLink->R_curr.z;
                     };
                 };
                 break;
             };
             n = n->Next;
         };
         if(!n){
             if(lang() == RUSSIAN){
                 CompasObj.AddTarget(CMP_OBJECT_VECTOR,UnitOrderType(GloryPlaceData[UsedCheckNum].R_curr.x,GloryPlaceData[UsedCheckNum].R_curr.y,GloryPlaceData[UsedCheckNum].R_curr.z),NULL,rCheckPointCompasTarget);
                 SelectCompasTarget(rCheckPointCompasTarget);
             }else{
                 CompasObj.AddTarget(CMP_OBJECT_VECTOR,UnitOrderType(GloryPlaceData[UsedCheckNum].R_curr.x,GloryPlaceData[UsedCheckNum].R_curr.y,GloryPlaceData[UsedCheckNum].R_curr.z),NULL,CheckPointCompasTarget);
                 SelectCompasTarget(CheckPointCompasTarget);
             };
             aciRefreshTargetsMenu();
         };
     };
 };
References aciRefreshTargetsMenu(), CompasObject::AddTarget(), CheckPointCompasTarget, CMP_OBJECT_VECTOR, CompasObj, CurrentWorld, CompasTargetType::Data, ServerData::GameType, GetPassage(), GloryPlaceData, GloryPlaceNum, lang(), my_server_data, CompasTargetType::Next, NULL, PASSEMBLOSS, GeneralObject::R_curr, rCheckPointCompasTarget, RUSSIAN, SelectCompasTarget(), CompasObject::TargetData, UsedCheckNum, Vector::x, Vector::y, and Vector::z.
Referenced by GameObjectDispatcher::DrawQuant().
CreateTabutaskTarget()
void CreateTabutaskTarget (void)
 {
     int i;
     CompasTargetType* n;
     UnitOrderType c;
     for(i = 0;i < MAX_TABUTASK;i++){
         if(TabuTable[i]->status == UVS_TABUTASK_STATUS::ACTIVE){
             switch(TabuTable[i]->target){
                 case UVS_TARGET::VANGER:
                     c.TargetT = TabuTable[i]->Ptarget;
                     n = CompasObj.TargetData;
                     while(n){
                         if(n->ID == CMP_OBJECT_VANGER){
                             if(n->Data.TargetT == c.TargetT)
                                 break;
                         };
                         n = n->Next;
                     };
                     if(!n){
                         RaceTxtBuff.init();
                         if(lang() == RUSSIAN) RaceTxtBuff < rTaskCompasTarget <= i;
                         else RaceTxtBuff < TaskCompasTarget <= i;
                         CompasObj.AddTarget(CMP_OBJECT_VANGER,UnitOrderType(c),NULL,RaceTxtBuff.GetBuf());
                         SelectCompasTarget(RaceTxtBuff.GetBuf());
                         aciRefreshTargetsMenu();
                     };
                     break;
             };
         };
     };
 };
References aciRefreshTargetsMenu(), UVS_TABUTASK_STATUS::ACTIVE, CompasObject::AddTarget(), CMP_OBJECT_VANGER, CompasObj, CompasTargetType::Data, XBuffer::GetBuf(), CompasTargetType::ID, XBuffer::init(), lang(), MAX_TABUTASK, CompasTargetType::Next, NULL, uvsTabuTaskType::Ptarget, RaceTxtBuff, rTaskCompasTarget, RUSSIAN, SelectCompasTarget(), TabuTable, CompasObject::TargetData, UnitOrderType::TargetT, TaskCompasTarget, and UVS_TARGET::VANGER.
Referenced by GameObjectDispatcher::DrawQuant().
DeleteArtefactTarget()
void DeleteArtefactTarget (StuffObject * n)
 {
     CompasTargetType* p;
     p = CompasObj.TargetData;
     while(p){
         if(p->ID == CMP_OBJECT_ITEM && (p->Data).StuffT == n){
             if(CompasObj.CurrentTarget == p) SelectCompasTarget(NULL);
             CompasObj.DeleteTarget(p);
             aciRefreshTargetsMenu();
             return;
         };
         p = p->Next;
     };
 };
References aciRefreshTargetsMenu(), CMP_OBJECT_ITEM, CompasObj, CompasObject::CurrentTarget, CompasTargetType::Data, CompasObject::DeleteTarget(), CompasTargetType::ID, CompasTargetType::Next, NULL, SelectCompasTarget(), and CompasObject::TargetData.
Referenced by StuffObject::DeviceIn().
dgGetThreallPhrase()
char* dgGetThreallPhrase (void)
 {
     return dgD -> getNextPhrase();
 }
DrawCircle()
void DrawCircle (int x, int y, int R, int color)
FakeOfMight()
void FakeOfMight (void)
 {
     if(uvsKronActive && ActD.Active){
         ActD.Active->Armor = ActD.Active->MaxArmor;
         ActD.Active->Energy = ActD.Active->MaxEnergy;
     };
 };
References ActD, ActionDispatcher::Active, uvsUnitType::Armor, uvsUnitType::Energy, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, and uvsKronActive.
FIRE_ALL_WEAPONS()
void FIRE_ALL_WEAPONS ()
 {
     // TODO(amdmi3): this should handle both ctrl's actually
     ActD.keyhandler(SDL_SCANCODE_RCTRL);
 }
References ActD, and ActionDispatcher::keyhandler().
FuckOFFinWater()
int FuckOFFinWater (void)
 {
     if(ActD.Active && (ActD.Active->dynamic_state & TOUCH_OF_WATER)) return 1;
     return 0;
 };
References ActD, ActionDispatcher::Active, and TOUCH_OF_WATER.
Referenced by uvsTabuTaskType::checkCycleEvent().
GetAngle()
int GetAngle (int x0, int y0, int x1, int y1, int x2, int y2)
 {
     int nx,ny,dx,dy;
     nx = getDistY(y2,y1);
     ny = -getDistX(x2,x1);
     dx = getDistX(x0,x1);
     dy = getDistY(y0,y1);
     return dx*nx + dy*ny;
 };
References getDistX(), and getDistY().
Referenced by TrackLinkType::ChangeLink(), CheckInBranch(), CheckInLink(), CheckInNode(), TrackLinkType::HideChangeLink(), and OutCheckNode().
GetCompasTarget()
char* GetCompasTarget (void)
 {
     if(CompasObj.CurrentTarget){
         return CompasObj.CurrentTarget->aciName;
     };
     return NULL;
 };
References CompasTargetType::aciName, CompasObj, CompasObject::CurrentTarget, and NULL.
Referenced by aciAdd2Targets(), aciDeleteFromTargets(), aciRefreshTargetsMenu(), actIntDispatcher::init_submenu(), and ActionDispatcher::PromptQuant().
GetEscaveDist()
int GetEscaveDist (void)
 {
     uvsEscave* p1;
     uvsSpot* p2;
     uvsPassage *p3;
     int md,d;
     Vector vCheck;
     md = -1;
     p1 = (uvsEscave*)EscaveTail;
     while(p1){
         if (((uvsEscave*)p1) -> Pworld -> gIndex == CurrentWorld ){
             vCheck = Vector(getDistX(p1->pos_x,Gamer->pos_x),getDistY(p1->pos_y,Gamer->pos_y),0);
             d = vCheck.vabs();
             if(d < md || md == -1) md = d;
         }
         p1 = (uvsEscave*)(p1 -> next);
     };
     p2 = (uvsSpot*)SpotTail;
     while(p2){
         if (((uvsSpot*)p2) -> Pworld -> gIndex == CurrentWorld ){
             vCheck = Vector(getDistX(p2->pos_x,Gamer->pos_x),getDistY(p2->pos_y,Gamer->pos_y),0);
             d = vCheck.vabs();
             if(d < md || md == -1) md = d;
         }
         p2 = (uvsSpot*)(p2 -> next);
     };
     if ( md == -1 ){
         p3 = (uvsPassage*)PassageTail;
         while(p3){
             if (((uvsPassage*)p3) -> Pworld -> gIndex == CurrentWorld ){
                 vCheck = Vector(getDistX(p3->pos_x,Gamer->pos_x),getDistY(p3->pos_y,Gamer->pos_y),0);
                 d = vCheck.vabs();
                 if(d < md || md == -1) md = d;
             }
             p3 = (uvsPassage*)(p3 -> next);
         };
     }
     return md;
 };
References CurrentWorld, EscaveTail, Gamer, getDistX(), getDistY(), uvsTarget::pos_x, uvsTarget::pos_y, and Vector::vabs().
GetNetworkGameTime()
void GetNetworkGameTime (int & day, int & hour, int & min, int & sec)
 {
     int t;
     t = age_of_current_game();
     sec = t  %  60;
     min = (t / 60) % 60;
     hour = (t / (60*60)) % 12;
     day = (t / (60*60*12)) % 30;
 };
References age_of_current_game, and min().
GetNodeDist()
char GetNodeDist (TrackLinkType * p1, TrackLinkType * p2)
 {
     NodeType* n;
     char i;
     if(p1->PointStatus & TRK_BRANCH_MASK){
         if(p2->PointStatus & TRK_BRANCH_MASK){
             if(p1->pBranch == p2->pBranch) return 0;
             else if(p1->pBranch->pBeg == p2->pBranch->pBeg || p1->pBranch->pBeg == p2->pBranch->pEnd ||
                    p1->pBranch->pEnd == p2->pBranch->pBeg || p1->pBranch->pEnd == p2->pBranch->pEnd) return 2;
         }else if(p1->pBranch->pBeg == p2->pNode || p1->pBranch->pEnd == p2->pNode) return 1;
     }else{
         if(p2->PointStatus & TRK_BRANCH_MASK){
             if(p2->pBranch->pBeg == p1->pNode || p2->pBranch->pEnd == p1->pNode) return 1;
         }else{
             n = p1->pNode;
             if(n == p2->pNode) return 0;
             for(i = 0;i < n->NumBranch;i++){
                 if(n->Status[i]){
                     if(n->pBranches[i]->pEnd == p2->pNode) return 2;
                 }else{
                     if(n->pBranches[i]->pBeg == p2->pNode) return 2;
                 };
             };
         };
     };
     return 3;
 };
References NodeType::NumBranch, BranchType::pBeg, TrackLinkType::pBranch, NodeType::pBranches, BranchType::pEnd, TrackLinkType::pNode, TrackLinkType::PointStatus, NodeType::Status, and TRK_BRANCH_MASK.
Referenced by CharacterDataType::GetInternalStuffOrder(), and CharacterDataType::GetVangerOrder().
getSpobsState()
int getSpobsState (void)
 {
     if(ActD.SpobsDestroy == 0) return 1;
     return 0;
 };
References ActD, and ActionDispatcher::SpobsDestroy.
GetStuffObject()
StuffObject* GetStuffObject (uvsUnitType * g, int n)
 {
     StuffObject* p;
     p = g->DeviceData;
     while(p){
         if(p->ActIntBuffer.type == n) return p;
         p = p->NextDeviceList;
     };
     return NULL;
 };
References StuffObject::ActIntBuffer, g, StuffObject::NextDeviceList, NULL, and actintItemData::type.
Referenced by GunSlot::CheckTarget(), CheckThreallMessiah(), VangerUnit::Destroy(), GunSlot::Fire(), VangerUnit::NewKeyHandler(), ActionDispatcher::PromptQuant(), VangerUnit::ResolveHandlerFind(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), and VangerUnit::UsingCutterig().
getThreallState()
int getThreallState (void)
 {
      if(ActD.ThreallDestroy == 0) return 1;
      return 0;
 };
References ActD, and ActionDispatcher::ThreallDestroy.
iChatFinit()
void iChatFinit (void)
 {
     iChatButton* p,*p1;
     if(iChatButtons){
         p = (iChatButton*)iChatButtons -> fPtr;
         while(p){
             p1 = (iChatButton*)p -> next;
             delete p;
             p = p1;
         }
         delete iChatButtons;
     }
     if(iChatHistory)
         delete iChatHistory;
     if(iChatInput)
         delete iChatInput;
     iChatON = iScreenChat = 0;
     aciKeyboardLocked = 0;
     iChatHistory = NULL;
     iChatInput = NULL;
     iChatButtons = NULL;
     SDL_StopTextInput();
 }
References iChatButtons.
Referenced by VangerUnit::Go2Universe().
iGetOptionValue()
int iGetOptionValue (int id)
 {
     if(iScrOpt && iScrOpt[id])
         return iScrOpt[id] -> GetValueINT();
     else
         return 1;
 }
References iScrOpt.
Referenced by aciGetPlayerColor(), camera_reset(), MainMenuRTO::Finit(), iHandleExtEvent(), iInitKeepOptions(), iInitProxyOptions(), iLoadData(), LoadingRTO1::Init(), MainMenuRTO::Init(), iSaveData(), aciBitmapMenuItem::load(), ActionDispatcher::PromptChangeCycle(), and ActionDispatcher::PromptQuant().
isSpummyDeath()
int isSpummyDeath (void)
 {
     return ActD.SpummyRunner;
 };
References ActD, and ActionDispatcher::SpummyRunner.
Referenced by DiagenDispatcher::getQdead().
LenDist()
void LenDist (int x, int y, int z, int x1, int y1, int z1, int dist, int radius, Vector & v)
 {
     int l;
     Vector vLink;
     if(abs(z - z1) < radius){
         vLink = Vector(getDistX(x,x1),getDistY(y,y1),0);
         if(dist < radius && dist > 0){
             l = MAX_TOUCH_VECTOR - (dist * MAX_TOUCH_VECTOR/radius);
             v += vLink * l / dist;
         };
     };
 };
References getDistX(), getDistY(), and MAX_TOUCH_VECTOR.
LinkDist() [1/2]
int LinkDist (int x, int y, int x1, int y1, int x2, int y2)
 {
     int d,a;
     Vector vBorder;
     Vector vLink;
     vLink = Vector(getDistX(x1,x),getDistY(y1,y),0);
     vBorder = Vector(getDistX(x2,x1),getDistY(y2,y1),0);
     d = vLink.vabs();
     a = rPI(vBorder.psi() - vLink.psi());
     return round(d * fabs(Sin(a)));
 };
References getDistX(), getDistY(), Vector::psi(), round(), rPI, Sin(), and Vector::vabs().
Referenced by TrackUnit::GetTrackVector().
LinkDist() [2/2]
void LinkDist (int x, int y, int x1, int y1, int x2, int y2, int radius, Vector & v)
 {
     int d,l,r;
     Vector vBorder;
     Vector vLink;
     vLink = Vector(getDistX(x1,x),getDistY(y1,y),0);
     vBorder = Vector(getDistX(x2,x1),getDistY(y2,y1),0);
     d = round((vLink.vabs() * fabs(Sin(vBorder.psi() - vLink.psi())))) - radius;
     if(d < MAX_TOUCH_BORDER){
         vLink = Vector(vBorder.y,-vBorder.x,0);
         r = vLink.vabs();
         if(r > 5){
             l = (MAX_TOUCH_VECTOR - (d * MAX_DELTA_VECTOR >> 15)) / 2;
             v += vLink * l / r;
         };
     };
 };
References getDistX(), getDistY(), MAX_DELTA_VECTOR, MAX_TOUCH_BORDER, MAX_TOUCH_VECTOR, Vector::psi(), round(), Sin(), Vector::vabs(), Vector::x, and Vector::y.
NetCheckRemovePlayer()
void NetCheckRemovePlayer (PlayerData * p)
 {
     VangerUnit* v;
     if(p->uvsPoint){
         v = (VangerUnit*)(ActD.Tail);
         while(v){
             if(v->pNetPlayer == p){
                 ClearPhantomTarget(p->client_ID);
                 v->pNetPlayer = NULL;
             };
             v = (VangerUnit*)(v->NextTypeList);
         };
     };
     if(uvsKronActive && ActD.Active && p->name){
         RaceTxtBuff.init();
         switch(my_server_data.GameType){
             case MECHOSOMA:
                 if((p->body.MechosomaStat.ItemCount1 + p->body.MechosomaStat.ItemCount2) >= (my_server_data.Mechosoma.ProductQuantity1 + my_server_data.Mechosoma.ProductQuantity2)){
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerWinnerSecondMessage;
                     else RaceTxtBuff < PlayerWinnerSecondMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.TimeBuf[2] = 200;
                     aiMessageBuffer.ColBuf[2] = 143;
                     aiMessageBuffer.NumStr = 3;
                     if(lang() == RUSSIAN){
                         aiMessageBuffer.add_str(0,(uchar*)(rPlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(rPlayerWinnerOtherMessage));
                     }else{
                         aiMessageBuffer.add_str(0,(uchar*)(PlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(PlayerWinnerOtherMessage));
                     };
                     aiMessageBuffer.add_str(1,(uchar*)(RaceTxtBuff.GetBuf()));
                     aciSendPrompt(&aiMessageBuffer);
                 }else{
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerFirstDropedMessage;
                     else RaceTxtBuff < PlayerFirstDropedMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.NumStr = 2;
                     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
                     if(lang() == RUSSIAN) aiMessageBuffer.add_str(1,(uchar*)(rPlayerSecondDropedMessage));
                     else aiMessageBuffer.add_str(1,(uchar*)(PlayerSecondDropedMessage));
                     aciSendPrompt(&aiMessageBuffer);
                 };
                 break;
             case PASSEMBLOSS:
                 if(p->body.PassemblossStat.CheckpointLighting >= my_server_data.Passembloss.CheckpointsNumber){
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerWinnerSecondMessage;
                     else RaceTxtBuff < PlayerWinnerSecondMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.TimeBuf[2] = 200;
                     aiMessageBuffer.ColBuf[2] = 143;
                     aiMessageBuffer.NumStr = 3;
                     if(lang() == RUSSIAN){
                         aiMessageBuffer.add_str(0,(uchar*)(rPlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(rPlayerWinnerOtherMessage));
                     }else{
                         aiMessageBuffer.add_str(0,(uchar*)(PlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(PlayerWinnerOtherMessage));
                     };
                     aiMessageBuffer.add_str(1,(uchar*)(RaceTxtBuff.GetBuf()));
                     aciSendPrompt(&aiMessageBuffer);
                 }else{
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerFirstDropedMessage;
                     else RaceTxtBuff < PlayerFirstDropedMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.NumStr = 2;
                     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
                     if(lang() == RUSSIAN) aiMessageBuffer.add_str(1,(uchar*)(rPlayerSecondDropedMessage));
                     else aiMessageBuffer.add_str(1,(uchar*)(PlayerSecondDropedMessage));
                     aciSendPrompt(&aiMessageBuffer);
                 };
                 break;
             case VAN_WAR:
                 RaceTxtBuff < p->name;
                 if(lang() == RUSSIAN) RaceTxtBuff < rPlayerFirstDropedMessage;
                 else RaceTxtBuff < PlayerFirstDropedMessage;
                 aiMessageBuffer.align_type = 0;
                 aiMessageBuffer.TimeBuf[0] = 200;
                 aiMessageBuffer.ColBuf[0] = 143;
                 aiMessageBuffer.TimeBuf[1] = 200;
                 aiMessageBuffer.ColBuf[1] = 143;
                 aiMessageBuffer.NumStr = 2;
                 aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
                 if(lang() == RUSSIAN) aiMessageBuffer.add_str(1,(uchar*)(rPlayerSecondDropedMessage));
                 else aiMessageBuffer.add_str(1,(uchar*)(PlayerSecondDropedMessage));
                 aciSendPrompt(&aiMessageBuffer);
                 break;
         };
     };
 };
References aciSendPrompt(), ActD, ActionDispatcher::Active, aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, PlayerData::body, PassemblossStatistic::CheckpointLighting, PASSEMBLOSS_PRM::CheckpointsNumber, ClearPhantomTarget(), PlayerData::client_ID, aciPromptData::ColBuf, ServerData::GameType, XBuffer::GetBuf(), XBuffer::init(), MechosomaStatistic::ItemCount1, MechosomaStatistic::ItemCount2, lang(), MECHOSOMA, ServerData::Mechosoma, PlayerBody::MechosomaStat, my_server_data, PlayerData::name, NULL, aciPromptData::NumStr, PASSEMBLOSS, ServerData::Passembloss, PlayerBody::PassemblossStat, PlayerFirstDropedMessage, PlayerSecondDropedMessage, PlayerWinnerFirstMessage, PlayerWinnerOtherMessage, PlayerWinnerSecondMessage, VangerUnit::pNetPlayer, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, RaceTxtBuff, rPlayerFirstDropedMessage, rPlayerSecondDropedMessage, rPlayerWinnerFirstMessage, rPlayerWinnerOtherMessage, rPlayerWinnerSecondMessage, RUSSIAN, UnitList::Tail, aciPromptData::TimeBuf, uvsKronActive, PlayerData::uvsPoint, and VAN_WAR.
NetEvent4Uvs()
void NetEvent4Uvs (PlayerData * p)
 {
     p->uvsPoint = (void*)(uvsCreateNetVanger(p->body.CarIndex,p->body.color,p->body.Data0,p->body.Data1));
     p->CreatePlayerFlag = 1;
 };
References PlayerData::body, PlayerBody::CarIndex, PlayerBody::color, PlayerData::CreatePlayerFlag, PlayerBody::Data0, PlayerBody::Data1, uvsCreateNetVanger(), and PlayerData::uvsPoint.
Referenced by CheckPlayerList().
NetSlotEvent()
void NetSlotEvent (int type, int id)
 {
     uchar ch;
     int t;
     VangerUnit* p;
     PlayerData* n;
     if(type == UPDATE_OBJECT){
         NETWORK_IN_STREAM > t;
         NETWORK_IN_STREAM > ch;
         p = (VangerUnit*)(ActD.GetNetObject(t));
         if(p){
             p->GunSlotData[ch].NetID = id;
             p->GunSlotData[ch].NetEvent(NETWORK_IN_STREAM.current_time());
         }else{
             n = players_list.first();
             while(n){
                 if(n->client_ID == NETWORK_IN_STREAM.current_creator()){
                     n->SlotNetID[ch] = id;
                     NETWORK_IN_STREAM > t;
                     n->SlotStuffNetID[ch] = t;
                     NETWORK_IN_STREAM > t;
                     n->SlotFireCount[ch] = t;
                     NETWORK_IN_STREAM > t;
                     break;
                 };
                 n = (PlayerData*)n -> next;
             };
             if(!n) NETWORK_IN_STREAM.ignore_event();
         };
     }else NETWORK_IN_STREAM.ignore_event();
 };
References ActD, PlayerData::client_ID, XTList< Type >::first(), UnitList::GetNetObject(), VangerUnit::GunSlotData, GunSlot::NetEvent(), GunSlot::NetID, NETWORK_IN_STREAM, players_list, PlayerData::SlotFireCount, PlayerData::SlotNetID, PlayerData::SlotStuffNetID, and UPDATE_OBJECT.
Referenced by GameObjectDispatcher::NetEvent().
NetStatisticGameStart()
void NetStatisticGameStart (void)
 {
     time(&StartGameTime);
     PrevKillTime = PrevLifeTime = StartGameTime;
 };
References PrevKillTime, PrevLifeTime, and StartGameTime.
NetStatisticInit()
void NetStatisticInit (void)
 {
     my_player_body.kills = 0;
     my_player_body.deaths = 0;
     switch(my_server_data.GameType){
         case VAN_WAR:
             my_player_body.VanVarStat.MaxLiveTime = 0;
             my_player_body.VanVarStat.MinLiveTime = 0;
             my_player_body.VanVarStat.KillFreq = 0;
             my_player_body.VanVarStat.DeathFreq = 0;
             MinLifeTime = 0;
             MaxLifeTime = 0;
             MinKillTime = 0;
             MaxKillTime = 0;
             break;
         case PASSEMBLOSS:
             my_player_body.PassemblossStat.TotalTime = 0;
             my_player_body.PassemblossStat.MinTime = 0;
             my_player_body.PassemblossStat.MaxTime = 0;
             my_player_body.PassemblossStat.CheckpointLighting = 0;
             break;
         case MECHOSOMA:
             my_player_body.MechosomaStat.ItemCount1 = 0;
             my_player_body.MechosomaStat.ItemCount2 = 0;
             my_player_body.MechosomaStat.MaxTransitTime = 0;
             my_player_body.MechosomaStat.MinTransitTime = 0;
             my_player_body.MechosomaStat.SneakCount = 0;
             my_player_body.MechosomaStat.LostCount = 0;
             break;
     };
 };
References PassemblossStatistic::CheckpointLighting, VanVarStatistic::DeathFreq, PlayerBody::deaths, ServerData::GameType, MechosomaStatistic::ItemCount1, MechosomaStatistic::ItemCount2, VanVarStatistic::KillFreq, PlayerBody::kills, MechosomaStatistic::LostCount, MaxKillTime, MaxLifeTime, VanVarStatistic::MaxLiveTime, PassemblossStatistic::MaxTime, MechosomaStatistic::MaxTransitTime, MECHOSOMA, PlayerBody::MechosomaStat, MinKillTime, MinLifeTime, VanVarStatistic::MinLiveTime, PassemblossStatistic::MinTime, MechosomaStatistic::MinTransitTime, my_player_body, my_server_data, PASSEMBLOSS, PlayerBody::PassemblossStat, MechosomaStatistic::SneakCount, PassemblossStatistic::TotalTime, VAN_WAR, and PlayerBody::VanVarStat.
NetStatisticUpdate()
void NetStatisticUpdate (int id)
 {
     time_t t,d;
     time(&t);
     switch(my_server_data.GameType){
         case VAN_WAR:
             switch(id){
                 case NET_STATISTICS_KILL:
                     my_player_body.kills++;
                     d = labs((long)(t - PrevKillTime));
                     if(MinKillTime == 0 || MinKillTime > d) MinKillTime = d;
                     if(MaxKillTime == 0 || MaxKillTime < d) MaxKillTime = d;
                     PrevKillTime = t;
                     if(MinKillTime == MaxKillTime)my_player_body.VanVarStat.KillFreq = MaxKillTime;
                     else my_player_body.VanVarStat.KillFreq = (MaxKillTime - MinKillTime) / 2;
                     break;
                 case NET_STATISTICS_DEATH:
                     my_player_body.deaths++;
                     d = labs((long)(t - PrevLifeTime));
                     if(MinLifeTime == 0 || MinLifeTime > d) MinLifeTime = d;
                     if(MaxLifeTime == 0 || MaxLifeTime < d) MaxLifeTime = d;
                     PrevLifeTime = t;
                     if(MinLifeTime == MaxLifeTime) my_player_body.VanVarStat.DeathFreq = MaxLifeTime;
                     else my_player_body.VanVarStat.DeathFreq = (MaxLifeTime - MinLifeTime) / 2;
                     break;
             };
             break;
         case PASSEMBLOSS:
             switch(id){
                 case NET_STATISTICS_KILL:
                     my_player_body.kills++;
                     break;
                 case NET_STATISTICS_DEATH:
                     my_player_body.deaths++;
                     break;
                 case NET_STATISTICS_CHECKPOINT:
                     my_player_body.PassemblossStat.CheckpointLighting = UsedCheckNum;
                     my_player_body.PassemblossStat.MaxTime = labs((long)(t - StartGameTime));
                     break;
                 case NET_STATISTICS_END_RACE:
                     my_player_body.PassemblossStat.CheckpointLighting = UsedCheckNum;
                     my_player_body.PassemblossStat.TotalTime =
                         my_player_body.PassemblossStat.MaxTime = labs((long)(t - StartGameTime));
                     break;
             };
             break;
         case MECHOSOMA:
             switch(id){
                 case NET_STATISTICS_KILL:
                     my_player_body.kills++;
                     break;
                 case NET_STATISTICS_DEATH:
                     my_player_body.deaths++;
                     break;
                 case NET_STATISTICS_CHECKPOINT:
                 case NET_STATISTICS_END_RACE:
                     my_player_body.MechosomaStat.MinTransitTime = labs((long)(t - StartGameTime));
                     break;
             };
             break;
     };
 };
References PassemblossStatistic::CheckpointLighting, VanVarStatistic::DeathFreq, PlayerBody::deaths, ServerData::GameType, VanVarStatistic::KillFreq, PlayerBody::kills, MaxKillTime, MaxLifeTime, PassemblossStatistic::MaxTime, MECHOSOMA, PlayerBody::MechosomaStat, MinKillTime, MinLifeTime, MechosomaStatistic::MinTransitTime, my_player_body, my_server_data, NET_STATISTICS_CHECKPOINT, NET_STATISTICS_DEATH, NET_STATISTICS_END_RACE, NET_STATISTICS_KILL, PASSEMBLOSS, PlayerBody::PassemblossStat, PrevKillTime, PrevLifeTime, StartGameTime, PassemblossStatistic::TotalTime, UsedCheckNum, VAN_WAR, and PlayerBody::VanVarStat.
Referenced by VangerUnit::Destroy(), uvsVanger::prepare_diagen_statistic(), GloryPlace::Quant(), and VangerUnit::ShellNetEvent().
NetworkGetStart()
void NetworkGetStart (char * name, int & x, int & y)
 {
     int i,j,t;
     SensorSortedData = new SensorDataType*[SnsTableSize];
     StaticSort(SnsTableSize,(StaticObject**)SensorObjectData,(StaticObject**)SensorSortedData);
     for(i = 0;i < NETWORK_NUM_ESCAVE;i++){
         if(!strcmp(name,NetworkEscaveName[i])){
             t = -1;
             for(j = ActD.NetEnterOffset + 1;j < SnsTableSize;j++){
                 if(SensorObjectData[j]->SensorType == SensorTypeList::PLAYER_BIRTH && SensorObjectData[j]->data5 == i){
                     t = j;
                     break;
                 };
             };
             if(t == -1){
                 for(j =0;j < SnsTableSize;j++){
                     if(SensorObjectData[j]->SensorType == SensorTypeList::PLAYER_BIRTH && SensorObjectData[j]->data5 == i){
                         ActD.NetEnterOffset = j;
                         x = SensorObjectData[j]->R_curr.x;
                         y = SensorObjectData[j]->R_curr.y;
                         return;
                     };
                 };
             }else{
                 ActD.NetEnterOffset = t;
                 x = SensorObjectData[t]->R_curr.x;
                 y = SensorObjectData[t]->R_curr.y;
                 return;
             };
         };
     };
 //  ErrH.Abort("Escave Name Not FOUND!");
 };
References ActD, ActionDispatcher::NetEnterOffset, NETWORK_NUM_ESCAVE, NetworkEscaveName, SensorTypeList::PLAYER_BIRTH, GeneralObject::R_curr, SensorObjectData, SensorSortedData, SnsTableSize, StaticSort(), Vector::x, and Vector::y.
Referenced by uvsRestoreVanger().
ObjectDestroy()
void ObjectDestroy (GeneralObject * n, int mode)
 {
     VangerUnit* p;
     int i,k;
     if(n->ID == ID_VANGER){
         if(mode){
             if(NetworkON && !(n->Status & SOBJ_ACTIVE) && ((VangerUnit*)(n))->pNetPlayer) ClearPhantomTarget(((VangerUnit*)(n))->pNetPlayer->client_ID);
             if(n == ActD.Active) ActD.Active = NULL;
             if(n == ActD.pfActive) ActD.pfActive = NULL;
             if(n == ActD.mfActive) ActD.mfActive = NULL;
             if(actCurrentViewObject == n){
                 actCurrentViewObject = (VangerUnit*)(actCurrentViewObject->NextTypeList);
                 if(!actCurrentViewObject) actCurrentViewObject = (VangerUnit*)(ActD.Tail);
             };
             if(((VangerUnit*)(n))->aiActionID == AI_ACTION_BRAKE && ActD.Active && !(ActD.Active->Status & SOBJ_DISCONNECT)){
                 aciClearTeleportMenu();
                 i = TELEPORT_ESCAVE_ID + 1;
                 p = (VangerUnit*)(ActD.Tail);
                 while(p){
                     if(p->uvsPoint->shape == UVS_VANGER_SHAPE::GAMER_SLAVE){
                         aciAddTeleportMenuItem(uvsMechosType_to_AciInt(p->uvsPoint->Pmechos->type),i);
                         p->VangerCloneID = i;
                         i++;
                     };
                     p = (VangerUnit*)(p->NextTypeList);
                 };
                 if(CurrentWorld  < MAIN_WORLD_MAX - 1 && (i - TELEPORT_ESCAVE_ID - 1) <= 5) aciAddTeleportMenuItem(-1,TELEPORT_ESCAVE_ID);
             };
         };
         if(((VangerUnit*)(n))->VangerChanger){
             if(((VangerUnit*)(n))->VangerChanger->VangerChanger == n){
                 ((VangerUnit*)(n))->VangerChanger->VangerChanger = NULL;
                 ((VangerUnit*)(n))->VangerChanger->VangerChangerCount = 0;
                 if(NetworkON && (((VangerUnit*)(n))->VangerChanger->Status & SOBJ_ACTIVE)){
                     ((VangerUnit*)(n))->VangerChanger->NetChanger = 0;
                     ((VangerUnit*)(n))->VangerChanger->ShellUpdateFlag = 1;
                 };
             };
             ((VangerUnit*)(n))->VangerChanger = NULL;
             ((VangerUnit*)(n))->VangerChangerCount = 0;
         };
         for(k = 0;k < AI_EVENT_MAX;k++){
             for(i = 0;i < aiNumGlobalEvent[0][k];i++){
                 if(aiGlobalEventData[0][k][i].Obj == n || aiGlobalEventData[0][k][i].Subj == (VangerUnit*)(n))
                     aiGlobalEventData[0][k][i].Refresh = 0;
             };
             for(i = 0;i < aiNumGlobalEvent[1][k];i++){
                 if(aiGlobalEventData[1][k][i].Obj == n || aiGlobalEventData[1][k][i].Subj == (VangerUnit*)(n))
                     aiGlobalEventData[1][k][i].Refresh = 0;
             };
         };
         p = (VangerUnit*)(ActD.Tail);
         while(p){
             p->VangerDestroyHandler(n);
             p = (VangerUnit*)(p->NextTypeList);
         };
     }else{
         if(NetworkON){
             if(((StuffObject*)(n))->Owner){
                 if(((StuffObject*)(n))->Owner->Status & SOBJ_ACTIVE){
                     NETWORK_OUT_STREAM.delete_object(((StuffObject*)(n))->NetDeviceID);
                     NETWORK_OUT_STREAM < (uchar)(0);
                     NETWORK_OUT_STREAM.end_body();
                 };
             }else{
                 NETWORK_OUT_STREAM.delete_object(n->NetID);
                 NETWORK_OUT_STREAM < (uchar)(0);
                 NETWORK_OUT_STREAM.end_body();
             };
         };
         for(k = 0;k < AI_EVENT_MAX;k++){
             for(i = 0;i < aiNumGlobalEvent[0][k];i++){
                 if(aiGlobalEventData[0][k][i].Obj == n)
                     aiGlobalEventData[0][k][i].Refresh = 0;
             };
             for(i = 0;i < aiNumGlobalEvent[1][k];i++){
                 if(aiGlobalEventData[1][k][i].Obj == n)
                     aiGlobalEventData[1][k][i].Refresh = 0;
             };
         };
         p = (VangerUnit*)(ActD.Tail);
         while(p){
             p->StuffDestroyHandler(n);
             p = (VangerUnit*)(p->NextTypeList);
         };
     };
 };
References aciAddTeleportMenuItem(), aciClearTeleportMenu(), actCurrentViewObject, ActD, ActionDispatcher::Active, AI_ACTION_BRAKE, AI_EVENT_MAX, aiGlobalEventData, aiNumGlobalEvent, ClearPhantomTarget(), CurrentWorld, UVS_VANGER_SHAPE::GAMER_SLAVE, GeneralObject::ID, ID_VANGER, MAIN_WORLD_MAX, ActionDispatcher::mfActive, GeneralObject::NetID, NETWORK_OUT_STREAM, NetworkON, NULL, ActionDispatcher::pfActive, uvsVanger::Pmechos, aiUnitEvent::Refresh, uvsVanger::shape, SOBJ_ACTIVE, SOBJ_DISCONNECT, GeneralObject::Status, VangerUnit::StuffDestroyHandler(), UnitList::Tail, TELEPORT_ESCAVE_ID, uvsMechos::type, uvsMechosType_to_AciInt(), uvsKernel::uvsPoint, VangerUnit::VangerCloneID, and VangerUnit::VangerDestroyHandler().
Referenced by aciSendEvent2itmdsp(), VangerUnit::ChangeVangerProcess(), ActionDispatcher::Close(), VangerUnit::DestroyItem(), VangerUnit::DischargeItem(), GunSlot::Fire(), uvsUnitType::Go2Universe(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), VangerUnit::ItemQuant(), VangerUnit::NewKeyHandler(), VangerUnit::OutCarNator(), ItemsDispatcher::Quant(), and VangerFunctionType::Quant().
PointDist()
void PointDist (int dx, int dy, int dz, int r, int radius, char dir, Vector & vd, Vector & v)
 {
     int l,d,m;
 //  int r;
     Vector vLink;
     if(abs(dz) < radius){
         vLink = Vector(dx,dy,0);
 //      r = vLink.vabs();
         d = round(r * fabs(Sin(vd.psi() - vLink.psi())));
         if(r < radius){
             l = MAX_TOUCH_VECTOR - (r * MAX_TOUCH_VECTOR/radius);
             v += vLink * l / r;
             m = MAX_TOUCH_VECTOR - l;
         }else m = MAX_TOUCH_VECTOR;
         if(r < MAX_TOUCH_TARGET){
             if(dir) vLink = Vector(vd.y,-vd.x,0);
             else vLink = Vector(-vd.y,vd.x,0);
             l = m - d * m / MAX_TOUCH_TARGET;
             d = m - r * m / MAX_TOUCH_TARGET;
             v += vLink * l * d / (vLink.vabs() * m);
         };
     };
 };
References MAX_TOUCH_TARGET, MAX_TOUCH_VECTOR, Vector::psi(), round(), Sin(), Vector::vabs(), Vector::x, and Vector::y.
section_prepare()
void section_prepare (int xg0, int yg0, int xg1, int yg1, int xg2, int yg2, int xg3, int yg3, int z_mechous, double & A, double & B, double & Z_AVR, DBV & normal)
 {
     int xl,xr,al,ar,bl,br,d,where,Y;
     int x1,x2;
     Vector *lfv,*rfv,*ltv,*rtv;
     Vector *curr,*beg,*up,*end;
     unsigned char *p0,*p;
     Vector vertices[4];
     vertices[0].x = xg0;
     vertices[0].y = yg0;
     vertices[1].x = xg1;
     vertices[1].y = yg1;
     vertices[2].x = xg2;
     vertices[2].y = yg2;
     vertices[3].x = xg3;
     vertices[3].y = yg3;
     beg = up = curr = vertices;
     end = vertices + 3;
     curr++;
     for(;curr <= end;curr++)
         if(up -> y > curr -> y)
             up = curr;
     rfv = lfv = up;
     if(up == beg)
         ltv = end;
     else
         ltv = up - 1;
     if(up == end)
         rtv = beg;
     else
         rtv = up + 1;
     Y = lfv -> y; xl = lfv -> x;
     al = ltv -> x - xl; bl = ltv -> y - Y;
     ar = rtv -> x - xl; br = rtv -> y - Y;
     xr = xl = (xl << 16) + (1 << 15);
     if(bl)
         DIV16(al,bl);
     if(br)
         DIV16(ar,br);
     int z,lh,uh;
     int N=0;
     double Sx=0,Sx2=0;
     double Sy=0,Sy2=0;
     double Sz=0;
     double Sxy = 0,Sxz=0,Syz=0;
     while(1){
         if(bl > br){
             d = br;
             where = 0;
             }
         else{
             d = bl;
             where = 1;
             }
         while(d-- > 0){
             p0 = vMap -> lineT[Y & clip_mask_y];
             if(!p0)
                 goto cont;
             x1 = xl >> 16;
             x2 = xr >> 16;
             if(x1 > x2)
                 SWAP(x1,x2);
             x1 &= ~1;
             x2 |= 1;
             while(x1 < x2){
                 p = p0 + (x1 & clip_mask_x);
                 if(!(*(p + 2*H_SIZE) & DOUBLE_LEVEL)){
                     z = *p;
                     if((uh = *(p + 1)) > z)
                         z = uh;
                     }
                 else{
                     lh = *p;
                     uh = *(p + 1);
                     z = z_mechous >= uh ? uh : lh;
                     }
                 if(z_mechous - z < LOWER_THRESHOULD && z - z_mechous < UPPER_THRESHOULD){
                     N++;
                     Sy += Y;
                     Sy2 += Y*Y;
                     Sx += x1;
                     Sx2 += x1*x1;
                     Sz += z;
                     Sxz += x1*z;
                     Syz += Y*z;
                     }
                 x1 += 2;
                 }
         cont:
             Y++;
             xl += al;
             xr += ar;
             }
         if(where){
             if(ltv == rtv)
                 goto ret;
             lfv = ltv;
             if(ltv == beg)
                 ltv = end;
             else
                 ltv--;
             br -= bl;
             xl = lfv -> x;
             al = ltv -> x - xl;
             bl = ltv -> y - Y;
             xl = (xl << 16) + (1 << 15);
             if(bl)
                 DIV16(al,bl);
             }
         else{
             if(rtv == ltv)
                 goto ret;
             rfv = rtv;
             if(rtv == end)
                 rtv = beg;
             else
                 rtv++;
             bl -= br;
             xr = rfv -> x;
             ar = rtv -> x - xr;
             br = rtv -> y - Y;
             xr = (xr << 16) + (1 << 15);
             if(br)
                 DIV16(ar,br);
             }
         }
 ret:
     if(!N){
         A = B = Z_AVR = 0;
         normal = DBV();
         return;
         }
     Z_AVR = Sz/N;
     double Det_x = (double)N*Sx2 - (double)Sx*Sx;
     if(fabs(Det_x) < DBL_EPS)
         return;
     double Det_y = (double)N*Sy2 - (double)Sy*Sy;
     if(fabs(Det_y) < DBL_EPS)
         return;
     A = ((double)N*Sxz - (double)Sx*Sz)/Det_x;
     B = ((double)N*Syz - (double)Sy*Sz)/Det_y;
     normal = DBV(-A,-B,1);
     normal.norm(1);
 }
References clip_mask_x, clip_mask_y, DBL_EPS, DIV16, DOUBLE_LEVEL, H_SIZE, LOWER_THRESHOULD, DBV::norm(), SWAP, UPPER_THRESHOULD, vMap, Vector::x, and Vector::y.
Referenced by VangerUnit::SensorQuant().
SelectCompasTarget()
void SelectCompasTarget (const char * n)
 {
     CompasTargetType* p;
     if(ActD.Active) ActD.Active->aiResolveFind.ClearResolve();
     if(!n){
         CompasObj.CurrentTarget = NULL;
         return;
     };
     p = CompasObj.TargetData;
     while(p){
         if(!strcmp(n,p->aciName)){
             CompasObj.CurrentTarget = p;
             return;
         };
         p = p->Next;
     };
     CompasObj.CurrentTarget = NULL;
 };
References CompasTargetType::aciName, ActD, ActionDispatcher::Active, VangerUnit::aiResolveFind, aiResolveList::ClearResolve(), CompasObj, CompasObject::CurrentTarget, CompasTargetType::Next, NULL, and CompasObject::TargetData.
Referenced by aciDeleteFromTargets(), aciHandleSubmenuEvent(), ClearPhantomTarget(), ClearTabutaskTarget(), CreatePhantomTarget(), CreateTabutaskTarget(), DeleteArtefactTarget(), GeneralSystemOpen(), and ActionDispatcher::PromptQuant().
SetWorldBeebos()
void SetWorldBeebos (int n)
 {
     aiPutHotBug(n);
 };
References aiPutHotBug().
start_vibration()
void start_vibration ()
 {
     time_vibration = 1;
 }
References time_vibration.
Referenced by VangerUnit::keyhandler(), and StuffObject::Quant().
StringOfBoozeeniada()
char* StringOfBoozeeniada (void)
 {
     return CHECK_BSIGN_DATA;
 };
References CHECK_BSIGN_DATA.
Referenced by dgMolecule::getVarPhrase().
test_block()
int test_block (unsigned char * ptr, int size)
 {
     int CRC = calc_CRC(ptr,size);
     MemTestBlock* p = mem_test_list.first();
     while(p){
         if(ptr == p -> ptr && size == p -> size)
             return CRC != p -> CRC;
         p = p -> next;
         }
     mem_test_list.append(new MemTestBlock(ptr,size,CRC));
     return 0;
 }
References calc_CRC(), XTList< Type >::first(), and mem_test_list.
uvsChangeCycle()
void uvsChangeCycle (void)
{
     uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
     int i = pb -> currentStage;
     pb -> cycleTable[i].cirtQ += pb -> cycleTable[i].cirtMAX;
 }
References Gamer, uvsEscave::Pbunch, and uvsEscave::Pworld.
uvsCheckItemOnLive()
int uvsCheckItemOnLive (int type)
{
     uvsBunch* pb = (uvsBunch*)BunchTail;
     uvsCultGame* pg;
     while(pb){
         pg = pb -> cycleTable[ pb -> currentStage ].Pgame;
         if (pg){
             if (pg -> GoodsTypeBeg == type) return 1;
         }
         pb = (uvsBunch*)pb -> next;
     }//  end while
     return 0;
 }
Referenced by VangerUnit::CheckOutDevice().
uvsGetNameByID()
char* uvsGetNameByID (int type, int & ID)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(pe){
         ID = pe -> SeekID( type );
         if (ID != -1)
             return pe -> name;
         pe = (uvsEscave*)pe -> next;
     }
     while(ps){
         ID = ps -> SeekID( type );
         if (ID != -1)
             return ps -> name;
         ps = (uvsSpot*)ps -> next;
     }
     return NULL;
 }
References EscaveTail, uvsEscave::name, listElem::next, NULL, uvsEscave::SeekID(), and SpotTail.
Referenced by aciSendEvent2itmdsp(), uvsActIntSell(), uvsPassagerFromStatistic(), and uvsPrepareItemToDiagen().
uvsMechosType_to_AciInt()
int uvsMechosType_to_AciInt (int)
{
     int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
     int _type;
     int _type_;
     if ( type >= first_constr){
          _type = type - first_constr;
          _type_ =  first_constr + (_type<<2) + uvsMechosTable[type] -> constractor;
     } else
         _type_ = type;
     return _type_;
 }
References MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, and uvsMechosTable.
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::Go2Universe(), and ObjectDestroy().
uvsOnKillItem()
void uvsOnKillItem (void)
{
     GamerResult.luck -= 10;
     ShowLuckMessage(-10);
     if (GamerResult.luck < 0) GamerResult.luck = 0;
 }
References GamerResult, uvsGamerResult::luck, and ShowLuckMessage().
Referenced by VangerUnit::CheckOutDevice().
uvsWorldToCross()
int uvsWorldToCross (int fromWID, int toWID)
{
     uvsWorld* fromW = WorldTable[fromWID];
     uvsWorld* toW = WorldTable[toWID];
     uvsWorld* nextW,*tmpW = NULL;
     uvsWorld *lastfromW = NULL, *lasttoW = NULL;
     uvsPassage* pp;
     int i = 0;
     int _i_ = 0;
     if ( fromWID == 7 || toWID == 7)
         return -1;
     if (fromW -> gIndex >= MAIN_WORLD_MAX ) {
         lastfromW = fromW;
         fromW = fromW -> pssT[0] -> Poutput;
         _i_ += 1;
     }
     if (toW -> gIndex >= MAIN_WORLD_MAX ) {
         lasttoW = toW;
         toW = toW -> pssT[0] -> Poutput;
         _i_ += 1;
     }
     unsigned int linkage = ChainMap[toW -> gIndex + fromW -> gIndex*MAIN_WORLD_MAX],mI;
     if ( fromW == toW ) return _i_;
     for(i = 0; i < 8; i++, _i_++){
         mI = (linkage & (0x0000000F << 4*i)) >> 4*i;
         nextW = getWorld(mI);
         if(!nextW)  nextW = toW;
         pp = fromW -> getPassage(nextW);
         if ( !pp ) ErrH.Abort( "buildWay:: not passage");
         fromW = nextW;
         if ( fromW == toW ) break;
     }
     _i_++;
     return (_i_);
 }
References MAIN_WORLD_MAX, NULL, and WorldTable.
XpeditionOFF()
void XpeditionOFF (int type)
 {
     if(uvsKronActive && ActD.Active){
         ActD.Active->ExternalMode = EXTERNAL_MODE_EARTH_IN;
         aciSendEvent2actint(ACI_LOCK_INTERFACE,NULL);
         ActD.Active->ExternalTime = ROTOR_PROCESS_LIFE_TIME;
         ActD.Active->CreateParticleRotor(ActD.Active->R_curr,ActD.Active->radius);
         camera_direct(ActD.Active->R_curr.x,ActD.Active->R_curr.y,1 << 7,0,0,ROTOR_PROCESS_LIFE_TIME + 1);
         PalCD.Set(CPAL_HIDE_PASSAGE,ROTOR_PROCESS_LIFE_TIME);
         ActD.Active->ExternalLock = 1;
         ActD.Active->ExternalDraw = 0;
         ActD.Active->ExternalObject = NULL;
         ActD.Active->switch_analysis(1);
         StopCDTRACK();
         switch(type){
             case GAME_OVER_INFERNAL_LOCKED:
                 ActD.ThreallDestroy = 1;
                 ActD.SpobsDestroy = 0;
                 break;
             case GAME_OVER_SPOBS_LOCKED:
                 ActD.ThreallDestroy = 0;
                 ActD.SpobsDestroy = 1;
                 break;
             case GAME_OVER_ALL_LOCKED:
                 ActD.ThreallDestroy = 1;
                 ActD.SpobsDestroy = 1;
                 break;
             case GAME_OVER_LUCKY:
                 ActD.LuckyFunction = 1;
                 ActD.ThreallDestroy = 0;
                 ActD.SpobsDestroy = 0;
                 break;
         };
     };
 };
References ACI_LOCK_INTERFACE, aciSendEvent2actint(), ActD, ActionDispatcher::Active, camera_direct(), CPAL_HIDE_PASSAGE, VangerUnit::CreateParticleRotor(), EXTERNAL_MODE_EARTH_IN, VangerUnit::ExternalDraw, VangerUnit::ExternalLock, VangerUnit::ExternalMode, VangerUnit::ExternalObject, VangerUnit::ExternalTime, GAME_OVER_ALL_LOCKED, GAME_OVER_INFERNAL_LOCKED, GAME_OVER_LUCKY, GAME_OVER_SPOBS_LOCKED, ActionDispatcher::LuckyFunction, NULL, PalCD, Object::radius, ROTOR_PROCESS_LIFE_TIME, PalConstructor::Set(), ActionDispatcher::SpobsDestroy, StopCDTRACK(), Object::switch_analysis(), ActionDispatcher::ThreallDestroy, uvsKronActive, Object::x, and Object::y.
Referenced by ActionDispatcher::FunctionQuant().
Variable Documentation
A_vibration
double A_vibration
Referenced by camera_quant(), and Object::load_parameters().
aciCurDominance
int aciCurDominance extern
aciCurDvcResource
int aciCurDvcResource extern
Referenced by ActionDispatcher::DrawResource(), and aIndData::init().
aciCurJumpCount
int aciCurJumpCount extern
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), aIndData::init(), aciWorldMap::quant(), VangerUnit::SensorQuant(), and aciWorldMap::show_jump_count().
aciCurLuck
int aciCurLuck extern
aciMaxDvcResource
int aciMaxDvcResource extern
Referenced by ActionDispatcher::DrawResource(), and aIndData::init().
aciMaxJumpCount
int aciMaxJumpCount extern
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CreateVangerUnit(), aIndData::init(), and aciWorldMap::show_jump_count().
aciMechMessiahEvent
int aciMechMessiahEvent extern
Referenced by actIntDispatcher::EventQuant(), and ActionDispatcher::FunctionQuant().
aciProtractorEvent
int aciProtractorEvent extern
Referenced by actIntDispatcher::EventQuant(), and ActionDispatcher::FunctionQuant().
aciTeleportEvent
int aciTeleportEvent extern
Referenced by VangerUnit::Quant().
aciTextEndFlag
int aciTextEndFlag extern
Referenced by actIntDispatcher::KeyQuant().
aciWorldIndex
int aciWorldIndex extern
Referenced by VangerUnit::CreateVangerUnit(), and VangerUnit::Quant().
actCurrentViewObject
VangerUnit* actCurrentViewObject extern
Referenced by GeneralSystemOpen(), getObjectPosition(), and ObjectDestroy().
AdvancedView
int AdvancedView = 0
Referenced by ExplosionObject::DrawQuant(), FireBallObject::DrawQuant(), ParticleObject::DrawQuant(), TargetParticleObject::DrawQuant(), BulletObject::DrawQuant(), HordeObject::DrawQuant(), GameObjectDispatcher::Quant(), and ScreenLineTrace().
aiFactorData
aiFactorType aiFactorData[AI_FACTOR_NUM]
Referenced by GeneralSystemInit(), and VangerUnit::InitAI().
aiGlobalEventData
aiUnitEvent aiGlobalEventData[2][AI_EVENT_MAX][AI_GLOBAL_EVENT_MAX]
Referenced by ObjectDestroy(), and VangerUnit::ResolveGenerator().
aiHotBugAdd00
int aiHotBugAdd00
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiHotBugAdd01
int aiHotBugAdd01
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiHotBugAdd02
int aiHotBugAdd02
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiHotBugAdd03
int aiHotBugAdd03
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiHotBugData00
int aiHotBugData00
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiHotBugData01
int aiHotBugData01
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiHotBugData02
int aiHotBugData02
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiHotBugData03
int aiHotBugData03
Referenced by aiGetHotBug(), aiPutHotBug(), and ActionDispatcher::Init().
aiMessageBuffer
aciPromptData aiMessageBuffer extern
Referenced by GeneralSystemFree(), GeneralSystemInit(), NetCheckRemovePlayer(), and aiMessageType::Send().
aiNumGlobalEvent
int aiNumGlobalEvent[2][AI_EVENT_MAX]
Referenced by ObjectDestroy(), ActionDispatcher::Open(), ActionDispatcher::Quant(), and VangerUnit::ResolveGenerator().
aiReadEvent
int aiReadEvent
Referenced by ActionDispatcher::Open(), ActionDispatcher::Quant(), and VangerUnit::ResolveGenerator().
aiStatusEmptyCount
int aiStatusEmptyCount
aiStatusEmptyTime
int aiStatusEmptyTime
aiStatusEscaveEmpty
int aiStatusEscaveEmpty
aiStatusIncubatorCount
int aiStatusIncubatorCount
aiStatusIncubatorEmptyCount
int aiStatusIncubatorEmptyCount
aiStatusLastEscave
int aiStatusLastEscave
aiStatusPodishCount
int aiStatusPodishCount
aiStatusPodishEmptyCount
int aiStatusPodishEmptyCount
aiStatusPrevY
int aiStatusPrevY
aiWriteEvent
int aiWriteEvent
Referenced by ActionDispatcher::Open(), and ActionDispatcher::Quant().
alpha_vibration
double alpha_vibration
Referenced by camera_quant(), and Object::load_parameters().
AUTOMATIC_WORLD_INDEX
int AUTOMATIC_WORLD_INDEX = WORLD_NECROSS
Referenced by VangerUnit::CreateVangerUnit().
camera_drag
double camera_drag
Referenced by camera_quant(), and Object::load_parameters().
camera_dragi
double camera_dragi
Referenced by camera_quant(), and Object::load_parameters().
camera_drags
double camera_drags
Referenced by camera_quant(), and Object::load_parameters().
camera_dragt
double camera_dragt
Referenced by camera_quant(), and Object::load_parameters().
camera_dragz
double camera_dragz
Referenced by camera_quant(), and Object::load_parameters().
camera_mi
double camera_mi
Referenced by camera_quant(), and Object::load_parameters().
camera_mii
double camera_mii
Referenced by Object::load_parameters().
camera_mis
double camera_mis
Referenced by camera_quant(), and Object::load_parameters().
camera_mit
double camera_mit
Referenced by camera_quant(), and Object::load_parameters().
camera_miz
double camera_miz
Referenced by camera_quant(), and Object::load_parameters().
camera_moving_log
int camera_moving_log = 0
Referenced by camera_direct(), camera_reset(), and ActionDispatcher::CameraQuant().
camera_moving_xy_enable
int camera_moving_xy_enable = 0
Referenced by aciHandleCameraEvent(), aciSetCameraMenu(), camera_quant(), camera_reset(), and KeyCenter().
camera_moving_z_enable
int camera_moving_z_enable = 0
Referenced by aciHandleCameraEvent(), camera_quant(), camera_reset(), and KeyCenter().
camera_rotate_enable
int camera_rotate_enable = 0
Referenced by aciHandleCameraEvent(), aciSetCameraMenu(), camera_quant(), camera_reset(), and KeyCenter().
camera_s
double camera_s =0
Referenced by camera_quant(), and camera_reset().
camera_slope_enable
int camera_slope_enable = 0
Referenced by aciHandleCameraEvent(), aciSetCameraMenu(), camera_quant(), camera_reset(), and KeyCenter().
camera_slope_min
int camera_slope_min = 0
Referenced by camera_quant().
camera_t
double camera_t =0
Referenced by camera_quant(), and camera_reset().
camera_turn_impulse
int camera_turn_impulse = Pi
Referenced by camera_impulse(), and Object::load_parameters().
camera_vi
double camera_vi =0
Referenced by camera_quant(), and camera_reset().
camera_vmax
double camera_vmax = 20
Referenced by camera_quant().
camera_vs
double camera_vs =0
Referenced by camera_direct(), camera_quant(), and camera_reset().
camera_vs_min
double camera_vs_min
Referenced by camera_quant(), and Object::load_parameters().
camera_vt
double camera_vt =0
Referenced by camera_direct(), camera_impulse(), camera_quant(), and camera_reset().
camera_vt_min
double camera_vt_min
Referenced by camera_quant(), and Object::load_parameters().
camera_vx
double camera_vx =0
Referenced by camera_direct(), camera_quant(), and camera_reset().
camera_vy
double camera_vy =0
Referenced by camera_direct(), camera_quant(), and camera_reset().
camera_vz
double camera_vz =0
Referenced by camera_direct(), camera_quant(), and camera_reset().
camera_vz_min
double camera_vz_min
Referenced by camera_quant(), and Object::load_parameters().
camera_x
double camera_x =0
Referenced by camera_quant(), and camera_reset().
camera_X_prev
int camera_X_prev
Referenced by camera_quant(), and ChangeWorld().
camera_y
double camera_y =0
Referenced by camera_quant(), and camera_reset().
camera_Y_prev
int camera_Y_prev
Referenced by camera_quant(), and ChangeWorld().
camera_z
double camera_z =0
Referenced by camera_quant(), and camera_reset().
camera_zmax
int camera_zmax = 800
Referenced by camera_quant().
camera_zmin
int camera_zmin = 400
Referenced by camera_quant(), iGameMap::change(), KeyCenter(), and iGameMap::reset().
ChangeArmor
int ChangeArmor
Referenced by VangerUnit::AddEscave(), VangerUnit::AddFree(), VangerUnit::AddPassage(), VangerUnit::AddSpot(), uvsVanger::get_shop(), uvsVanger::prepare_list_for_ActInt(), and VangerUnit::SensorQuant().
ChangeEnergy
int ChangeEnergy
Referenced by VangerUnit::AddEscave(), VangerUnit::AddFree(), VangerUnit::AddPassage(), VangerUnit::AddSpot(), GeneralSystemInit(), GeneralSystemLoad(), GeneralSystemSave(), and VangerUnit::SensorQuant().
CHECK_BSIGN_DATA
char* CHECK_BSIGN_DATA
Referenced by CreateBoozeeniadaString(), GeneralSystemFree(), GeneralSystemLoad(), GeneralSystemSave(), and StringOfBoozeeniada().
CHECK_BSIGN_INDEX
int CHECK_BSIGN_INDEX[NUM_CHECK_BSIGN]
Referenced by CreateBoozeeniadaString(), GeneralSystemLoad(), GeneralSystemSave(), and CheckPointEngine::Touch().
COMPAS_DOWN
const int COMPAS_DOWN = 80
COMPAS_LEFT
const int COMPAS_LEFT = 60
COMPAS_RIGHT
const int COMPAS_RIGHT = 80
COMPAS_UP
const int COMPAS_UP = 60
CompasObj
CompasObject CompasObj
Referenced by AddPhantomTarget(), AddTarget2Compas(), ClearPhantomTarget(), ClearTabutaskTarget(), CreateArtefactTarget(), CreatePhantomTarget(), CreateTabutaskTarget(), DeleteArtefactTarget(), GameObjectDispatcher::DrawQuant(), VangerUnit::GamerOrderInit(), GeneralSystemClose(), GeneralSystemFree(), GeneralSystemInit(), GeneralSystemOpen(), GetCompasTarget(), and SelectCompasTarget().
curGMap
iGameMap* curGMap extern
Referenced by camera_direct(), camera_quant(), ActionUnit::InitEnvironment(), VangerUnit::NetCreateVanger(), and VangerUnit::Quant().
DbgCheckEnable
int DbgCheckEnable
Referenced by VangerUnit::keyhandler().
Dead
int Dead extern
DollyTail
listElem* DollyTail extern
Referenced by VangerUnit::CalcAiFactor(), uvsVanger::gatherCirt(), uvsWorld::generateDolly(), uvsFreeDolly(), and uvsVanger::uvsVanger().
EscaveTail
listElem* EscaveTail extern
Referenced by GetEscaveDist(), and CompasObject::Open().
FireColorTable
uchar* FireColorTable extern
Referenced by FireBallProcess::Show(), and FireBallProcess::Show2().
FLY_DEVICE_DEFAULT
const int FLY_DEVICE_DEFAULT = 22
Referenced by VangerUnit::UsingCopterig().
frame
int frame extern
Referenced by VangerUnit::Action(), FireBallProcess::Activate(), actIntDispatcher::change_items(), iGameMap::draw(), AVIFile::draw(), bmlObject::offs_show(), actIntDispatcher::put_in_slot(), KDsPlus::Quant(), GameQuantRTO::Quant(), aciScreenResourceBML::redraw(), aciScreenResourceBMO::redraw(), actIntDispatcher::set_move_item(), bmlObject::show(), FireBallProcess::Show(), FireBallProcess::Show2(), Object::test_object_to_baseobject(), and VangerUnit::TouchSensor().
GameQuantReturnValue
int GameQuantReturnValue extern
Referenced by VangerUnit::Destroy(), and VangerUnit::SensorQuant().
Gamer
uvsVanger* Gamer extern
Referenced by GetEscaveDist().
HideTrack
TrackType HideTrack extern
Referenced by VangerUnit::AddFindResolve(), VangerUnit::CalcForce(), VangerUnit::CalcImpulse(), VangerUnit::ChangeVangerProcess(), VangerUnit::CheckNearTrack(), TrackUnit::CreateTrackUnit(), TrackUnit::GetInside(), TrackUnit::GetNode(), TrackUnit::MakeTrackDist(), TrackUnit::Open(), VangerUnit::Quant(), VangerUnit::ResolveHandlerFind(), VangerUnit::TargetAnalysis(), TrackUnit::TraceWay(), and TrackUnit::WayInit().
HYPNOTISE_WEAPON_RADIUS
const int HYPNOTISE_WEAPON_RADIUS = 100
Referenced by GunSlot::Quant().
INSECT_RADIUS
const int INSECT_RADIUS = 2500
Referenced by InsectUnit::CreateInsect().
INSECT_RADIUS2
const int INSECT_RADIUS2 = INSECT_RADIUS * 2
Referenced by InsectUnit::CreateInsect().
light_modulation
int light_modulation extern
MAX_COMPAS_DELTA
const int MAX_COMPAS_DELTA = 7
MAX_COMPAS_SPEED
const int MAX_COMPAS_SPEED = 10
max_jump_power
int max_jump_power extern
Referenced by VangerUnit::Action(), VangerUnit::CheckStartJump(), Object::direct_keyboard_control(), Object::get_max_jump_distance(), Object::load_parameters(), and Object::mechous_analysis().
MAX_TABUTASK
int MAX_TABUTASK extern
Referenced by CreateTabutaskTarget(), uvsCheckItemOnTabuTask(), uvsCheckKronIventTabuTask(), uvsCheckVangerTabuTask(), and uvsRestoreTabuTask().
max_time_vibration
int max_time_vibration
Referenced by camera_quant(), and Object::load_parameters().
MaxKillTime
time_t MaxKillTime
Referenced by NetStatisticInit(), and NetStatisticUpdate().
MaxLifeTime
time_t MaxLifeTime
Referenced by NetStatisticInit(), and NetStatisticUpdate().
MECHOS_WATER_WAVE
const char MECHOS_WATER_WAVE = 0
Referenced by ActionUnit::CreateActionUnit().
MinKillTime
time_t MinKillTime
Referenced by NetStatisticInit(), and NetStatisticUpdate().
MinLifeTime
time_t MinLifeTime
Referenced by NetStatisticInit(), and NetStatisticUpdate().
MOLE_DEVICE_DEFAULT
const int MOLE_DEVICE_DEFAULT = 23
Referenced by VangerUnit::UsingCrotrig().
multi_analysis
int multi_analysis extern
multi_draw
int multi_draw extern
NETWORK_NUM_ESCAVE
const int NETWORK_NUM_ESCAVE = 7
Referenced by NetworkGetStart().
NetworkEscaveName
const char* NetworkEscaveName[NETWORK_NUM_ESCAVE] ={"Podish","Incubator","VigBoo","Lampasso","Ogorod","ZeePa","B-Zone"}
Referenced by NetworkGetStart().
NewWorldX
int NewWorldX extern
Referenced by ChangeWorld(), and VangerUnit::SensorQuant().
NewWorldY
int NewWorldY extern
Referenced by ChangeWorld(), and VangerUnit::SensorQuant().
NumHumanModel
int NumHumanModel = 1
Referenced by addVanger(), ComlineAnalyze(), and VangerUnit::keyhandler().
oscillar_vibration
double oscillar_vibration
Referenced by camera_quant(), and Object::load_parameters().
palbufOrg
uchar* palbufOrg extern
Referenced by VangerUnit::Quant().
PassageTail
listElem* PassageTail extern
preViewY
int preViewY extern
Referenced by vrtMap::accept(), addVanger(), and vrtMap::another().
PrevKillTime
time_t PrevKillTime
Referenced by NetStatisticGameStart(), and NetStatisticUpdate().
PrevLifeTime
time_t PrevLifeTime
Referenced by NetStatisticGameStart(), and NetStatisticUpdate().
Quit
int Quit
RaceTxtBuff
XBuffer RaceTxtBuff(1024)
Referenced by aciSendEvent2itmdsp(), aiPromptDominanceMessage(), aiPromptLuckMessage(), aiPromptTaskMessage(), CreateTabutaskTarget(), NetCheckRemovePlayer(), CompasObject::Quant(), and ActionDispatcher::Quant().
RAM16
int RAM16 extern
Referenced by camera_quant(), and LoadingRTO1::Init().
RudderAngleTable
int* RudderAngleTable
Referenced by ActionDispatcher::Free(), ActionDispatcher::Init(), and ActionUnit::MixVector().
RudderLenTable
int* RudderLenTable
Referenced by ActionDispatcher::Free(), ActionDispatcher::Init(), and ActionUnit::MixVector().
SIGNATOR_DELAY
const int SIGNATOR_DELAY = 70
Referenced by ActionDispatcher::FunctionQuant(), VangerFunctionType::Init(), VangerFunctionType::Quant(), and VangerFunctionType::SoundQuant().
SKY_QUAKE_DELAY
const int SKY_QUAKE_DELAY = 25
Referenced by ActionDispatcher::FunctionQuant(), VangerFunctionType::Init(), and VangerFunctionType::Quant().
SKY_QUAKE_DELTA
const int SKY_QUAKE_DELTA = 15
Referenced by ActionDispatcher::DrawResource(), ActionDispatcher::FunctionQuant(), VangerFunctionType::Init(), ActionDispatcher::NewFunction(), and VangerFunctionType::Quant().
SKY_QUAKE_RADIUS
const int SKY_QUAKE_RADIUS = 300
Referenced by ActionDispatcher::DrawResource(), ActionDispatcher::FunctionQuant(), VangerFunctionType::Init(), ActionDispatcher::NewFunction(), and VangerFunctionType::Quant().
SKY_QUAKE_TIME
const int SKY_QUAKE_TIME = 10
Referenced by VangerFunctionType::Quant().
SkyQuake
LandQuake SkyQuake
Referenced by ActionDispatcher::DrawResource(), and VangerFunctionType::Init().
SkyQuake2
LandQuake SkyQuake2
Referenced by ActionDispatcher::DrawResource(), ActionDispatcher::FunctionQuant(), ActionDispatcher::NewFunction(), and VangerFunctionType::Quant().
SkyQuake3
LandQuake SkyQuake3
Referenced by ActionDispatcher::DrawResource().
SkyQuakeEnable
int SkyQuakeEnable
Referenced by ActionDispatcher::DrawResource(), VangerFunctionType::Init(), and ActionDispatcher::Open().
SkyQuakeEnable2
int SkyQuakeEnable2
Referenced by ActionDispatcher::DrawResource(), ActionDispatcher::FunctionQuant(), ActionDispatcher::NewFunction(), ActionDispatcher::Open(), and VangerFunctionType::Quant().
SkyQuakeEnable3
int SkyQuakeEnable3
Referenced by ActionDispatcher::DrawResource(), ActionDispatcher::Open(), and VangerFunctionType::Quant().
SpeedAngleTable
int* SpeedAngleTable
Referenced by ActionDispatcher::Free(), ActionDispatcher::Init(), and ActionUnit::MixVector().
SpeedLenTable
int* SpeedLenTable
Referenced by ActionDispatcher::Free(), ActionDispatcher::Init(), and ActionUnit::MixVector().
SpotTail
listElem* SpotTail extern
StartGameTime
time_t StartGameTime
Referenced by NetStatisticGameStart(), and NetStatisticUpdate().
stop_camera
int stop_camera = 0
Referenced by camera_quant().
SWIM_DEVICE_DEFAULT
const int SWIM_DEVICE_DEFAULT = 21
Referenced by VangerUnit::UsingCutterig().
TabuTable
uvsTabuTaskType** TabuTable extern
Referenced by aciSendEvent2itmdsp(), uvsWorld::ChangeTabuTaskInList(), CreateTabutaskTarget(), uvsVanger::prepare_list_for_ActInt(), uvsActIntSell(), uvsChangeGoodsInList(), uvsChangeGoodsParam(), uvsChangeTabuTask(), uvsCheckItemOnTabuTask(), uvsCheckKronIventTabuTask(), uvsCheckVangerTabuTask(), uvsKronDeleteItem(), and uvsRestoreTabuTask().
terra_moving_tool
dastPoly3D terra_moving_tool extern
time_vibration
int time_vibration = 0
Referenced by camera_quant(), and start_vibration().
TotalVangerSpeed
int TotalVangerSpeed
Referenced by GeneralSystemInit(), and VangerUnit::InitAI().
UnitGlobalTime
int UnitGlobalTime
Referenced by VangerUnit::ChangeVangerProcess(), HordeObject::CreateHorde(), uvsUnitType::CreateUnitType(), and GeneralSystemInit().
UnitMatrixData
UnitItemMatrix* UnitMatrixData
Referenced by VangerUnit::ChangeVangerProcess(), uvsUnitType::CreateUnitType(), GeneralSystemFree(), GeneralSystemInit(), and UnitItemMatrix::Open().
uvsGamerWaitGame
int uvsGamerWaitGame extern
Referenced by uvsBunch::begin_harvest(), uvsVanger::prepare_shop(), VangerUnit::Quant(), uniVangLoad(), uniVangSave(), and WaitGameInTown().
uvsKronActive
int uvsKronActive extern
Referenced by FakeOfMight(), GeneralSystemClose(), GeneralSystemOpen(), NetCheckRemovePlayer(), GameObjectDispatcher::Quant(), PalConstructor::Quant(), ActionDispatcher::SlotIn(), and XpeditionOFF().
uvsPoponkaID
int uvsPoponkaID extern
Referenced by CreateBoozeeniadaString(), uvsVanger::go_from_escave(), uvsVanger::go_from_spot(), and uvsPoponkaIDON().
view_lock
int view_lock extern
vInsectTarget
Vector vInsectTarget
Referenced by InsectUnit::InitEnvironment(), ActionDispatcher::Open(), InsectUnit::Quant(), and VangerFunctionType::Quant().
vSetVangerFlag
int vSetVangerFlag = -1
Referenced by VangerUnit::AddFree(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), and VangerUnit::Quant().