Vangers: src/units/moveland.h File Reference
moveland.h File Reference
Classes
struct MLFrame
struct MobileLocation
Macros
#define MLM_RELATIVE 0
#define MLM_ABSOLUTE 1
#define MLM_REL2ABS 2
#define GET_DESTROY_MECHOS(n) DestroyMechosTable[n]
#define GET_DESTROY_MOLE(n) DestroyMechosMole[n]
Typedefs
typedef int MLAtype
Functions
void MLload (void)
void MLsave (void)
void MLreload (void)
int MLquant (void)
void MLfree (void)
void VLload (void)
void DestroyBarellSmooth (int x0, int y0, int SmoothRadius, int SpotRadius, int Delta, uchar terrain, int Num, int z0, uchar rfactor)
void DestroySmooth (int x0, int y0, int SmoothRadius, int SpotRadius, int Delta, int cDelta, uchar terrain, int Num, uchar rfactor)
void DestroySpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
void DestroyBarellSpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
int DestroyBarellSmoothWithCheck (int x0, int y0, int SmoothRadius, int SpotRadius, int Delta, uchar terrain, int Num, int z0, uchar rfactor)
void DestroySmoothCheck (int x0, int y0, int Radius)
void DestroySmoothPut (int x0, int y0, int Radius)
void DestroySmoothInit (void)
void DestroySmoothFree (void)
void xDestroySpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
void xRestoreDestroySpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
void RadialRender (int x0, int y0, int radius)
int GetLandAlt (int x0, int y0, int Radius)
int LandSlideProcess (int *fx, int *fy, int pow, int z0, int delta)
int LandSlideLine (int x0, int y0, int z0, int x1, int delta)
void MakeSecondLevel (int x0, int y0, uchar z0, int Radius)
void MapCircleProcess (int x0, int y0, int z0, int r0, int mode, uchar terrain)
void ClearBarell (int x0, int y0, int radius, uchar terrain, int z0)
int GetSmoothUpAlt (uchar *type, uchar *pa0, int x)
void MLReset (void)
Variables
const char MOBILE_LOCATION_ACTIVE = 1
const int MLPREC = 16
const int MAX_KEYPHASE = 4
MobileLocation ** MLTable
int MLTableSize
int TntTableSize
int SnsTableSize
int DngTableSize
uchar DestroyMechosTable [TERRAIN_MAX]
uchar DestroyMoleTable [TERRAIN_MAX]
Macro Definition Documentation
GET_DESTROY_MECHOS
#define GET_DESTROY_MECHOS (n) DestroyMechosTable[n]
GET_DESTROY_MOLE
#define GET_DESTROY_MOLE (n) DestroyMechosMole[n]
MLM_ABSOLUTE
#define MLM_ABSOLUTE 1
MLM_REL2ABS
#define MLM_REL2ABS 2
MLM_RELATIVE
#define MLM_RELATIVE 0
Typedef Documentation
MLAtype
typedef int MLAtype
Function Documentation
ClearBarell()
void ClearBarell (int x0, int y0, int radius, uchar terrain, int z0)
 {
     uchar* pa0,*pf0;
     int i,j;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int* dx,*dy;
     for(i = y0 - radius;i <= y0 + radius;i++) if(!lt[YCYCL(i)]) return;
     if(terrain != 83){
 //      for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 0;
         memset(SmoothTerrainMask,0,TERRAIN_MAX);
         SmoothTerrainMask[terrain] = 1;
     }else{
 //      for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 1;
         memset(SmoothTerrainMask,1,TERRAIN_MAX);
     };
     if(radius >= MAX_DESTROY_RADIUS)
         ErrH.Abort("Bad Clear Radius");
     for(i = 0;i < radius;i++){
         dx = RadiusDestroyX[i];
         dy = RadiusDestroyY[i];
         for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
             rx = XCYCL((*dx) + x0);
             ry = YCYCL((*dy) + y0);
             pa0 = lt[ry] + rx;
             pf0 = pa0 + H_SIZE;
             if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                 if(*pf0 & DOUBLE_LEVEL){
                     if(rx & 1)
                         *pa0 = AltProtectedTable[z0 + (((*pa0) - z0) >> 6) + ALT_PROTECTED_OFFSET];
                 }else
                     *pa0 = AltProtectedTable[z0 + (((*pa0) - z0) >> 6) + ALT_PROTECTED_OFFSET];
             };
         };
     };
     int x1,y1;
     rx = XCYCL(x0 - radius);
     ry = YCYCL(y0 - radius);
     x1 = XCYCL(x0 + radius);
     y1 = YCYCL(y0 + radius);
 #ifdef _ROAD_
     if(CurrentWorld != WORLD_NECROSS)
 #endif
         regSet(rx,ry,x1,y1,1,0);
     regRender(rx,ry,x1,y1);
 };
References XErrorHandler::Abort(), ALT_PROTECTED_OFFSET, AltProtectedTable, CurrentWorld, DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, ErrH, GET_TERRAIN, H_SIZE, NumDestroyRadius, RadiusDestroyX, RadiusDestroyY, regRender(), regSet(), SmoothTerrainMask, TERRAIN_MAX, vMap, WORLD_NECROSS, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, MobileLocation::y1, and YCYCL.
Referenced by TntCreature::NetQuant().
DestroyBarellSmooth()
void DestroyBarellSmooth (int x0, int y0, int SmoothRadius, int SpotRadius, int Delta, uchar terrain, int Num, int z0, uchar rfactor)
 {
     int Phi = RND(PI/2);
     uchar* pa0,*pf0;
     int i,j,n;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int* dx,*dy;
     int h;
     for(i = y0 - SmoothRadius;i <= y0 + SmoothRadius;i++) if(!lt[YCYCL(i)]) return;
     if(terrain != 83){
 //      for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 0;
         memset(SmoothTerrainMask,0,TERRAIN_MAX);
         SmoothTerrainMask[terrain] = 1;
     }else{
 //      for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 1;
         memset(SmoothTerrainMask,1,TERRAIN_MAX);
     };
     h = 2*SmoothRadius / 3;
     if(h >= MAX_DESTROY_RADIUS)
         ErrH.Abort("Bad Clear Radius");
     for(i = 0;i < h;i++){
         dx = RadiusDestroyX[i];
         dy = RadiusDestroyY[i];
         for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
             rx = XCYCL((*dx) + x0);
             ry = YCYCL((*dy) + y0);
             pa0 = lt[ry] + rx;
             pf0 = pa0 + H_SIZE;
             if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                 if(*pf0 & DOUBLE_LEVEL){
                     if(rx & 1)
                         *pa0 = AltProtectedTable[z0 + (((*pa0) - z0) >> 6) + ALT_PROTECTED_OFFSET];
                 }else
                     *pa0 = AltProtectedTable[z0 + (((*pa0) - z0) >> 6) + ALT_PROTECTED_OFFSET];
             };
         };
     };
 //  for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 1;
     memset(SmoothTerrainMask,1,TERRAIN_MAX);
     SmoothTerrainMask[4] = 0;
     SmoothTerrainMask[5] = 0;
     if(Delta > 0){
         for(i = 0;i < Num;i++){
             n = RND(SmoothRadius - SpotRadius);
             rx = XCYCL(x0 + ((CO[Phi] * n) >> 16));
             ry = YCYCL(y0 + ((SI[Phi] * n) >> 16));
             DestroyBarellSpot(rx,ry,SpotRadius,terrain,RND(Delta),rfactor);
             Phi = rPI(Phi + 2*PI / Num);
         };
     }else{
         for(i = 0;i < Num;i++){
             n = RND(SmoothRadius - SpotRadius);
             rx = XCYCL(x0 + ((CO[Phi] * n) >> 16));
             ry = YCYCL(y0 + ((SI[Phi] * n) >> 16));
             DestroyBarellSpot(rx,ry,SpotRadius,terrain,-(int)(RND(-Delta)),rfactor);
             Phi = rPI(Phi + 2*PI / Num);
         };
     };
     DestroySmoothPut(x0,y0,SmoothRadius);
     int x1,y1;
     rx = XCYCL(x0 - SmoothRadius);
     ry = YCYCL(y0 - SmoothRadius);
     x1 = XCYCL(x0 + SmoothRadius);
     y1 = YCYCL(y0 + SmoothRadius);
 #ifdef _ROAD_
     if(CurrentWorld != WORLD_NECROSS)
 #endif
         regSet(rx,ry,x1,y1,1,0);
     regRender(rx,ry,x1,y1,0);
 };
References XErrorHandler::Abort(), ALT_PROTECTED_OFFSET, AltProtectedTable, CO, CurrentWorld, DestroyBarellSpot(), DestroySmoothPut(), DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, ErrH, GET_TERRAIN, H_SIZE, NumDestroyRadius, PI, RadiusDestroyX, RadiusDestroyY, regRender(), regSet(), RND(), rPI, SI, SmoothTerrainMask, TERRAIN_MAX, vMap, WORLD_NECROSS, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, MobileLocation::y1, and YCYCL.
DestroyBarellSmoothWithCheck()
int DestroyBarellSmoothWithCheck (int x0, int y0, int SmoothRadius, int SpotRadius, int Delta, uchar terrain, int Num, int z0, uchar rfactor)
 {
     int Phi = RND(PI/2);
     uchar* pa0,*pf0;
     int i,j,n;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int* dx,*dy;
     int h;
     for(i = y0 - SmoothRadius;i <= y0 + SmoothRadius;i++) if(!lt[YCYCL(i)]) return 0;
 //  for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 0;
     memset(SmoothTerrainMask,0,TERRAIN_MAX);
     if(terrain != 83) SmoothTerrainMask[terrain] = 1;
     h = 2*SmoothRadius / 3;
     if(h >= MAX_DESTROY_RADIUS)
         ErrH.Abort("Bad Clear Radius");
     for(i = 0;i < h;i++){
         dx = RadiusDestroyX[i];
         dy = RadiusDestroyY[i];
         for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
             rx = XCYCL((*dx) + x0);
             ry = YCYCL((*dy) + y0);
             pa0 = lt[ry] + rx;
             pf0 = pa0 + H_SIZE;
             if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                 if(*pf0 & DOUBLE_LEVEL){
                     if(rx & 1)
                         *pa0 = AltProtectedTable[z0 + (((*pa0) - z0) >> 6) + ALT_PROTECTED_OFFSET];
                 }else
                     *pa0 = AltProtectedTable[z0 + (((*pa0) - z0) >> 6) + ALT_PROTECTED_OFFSET];
             };
         };
     };
 //  for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 1;
     memset(SmoothTerrainMask,1,TERRAIN_MAX);
     SmoothTerrainMask[4] = 0;
     SmoothTerrainMask[5] = 0;
     if(Delta > 0){
         for(i = 0;i < Num;i++){
             n = RND(SmoothRadius - SpotRadius);
             rx = XCYCL(x0 + ((CO[Phi] * n) >> 16));
             ry = YCYCL(y0 + ((SI[Phi] * n) >> 16));
             DestroyBarellSpot(rx,ry,SpotRadius,terrain,RND(Delta),rfactor);
             Phi = rPI(Phi + 2*PI / Num);
         };
     }else{
         for(i = 0;i < Num;i++){
             n = RND(SmoothRadius - SpotRadius);
             rx = XCYCL(x0 + ((CO[Phi] * n) >> 16));
             ry = YCYCL(y0 + ((SI[Phi] * n) >> 16));
             DestroyBarellSpot(rx,ry,SpotRadius,terrain,-(int)(RND(-Delta)),rfactor);
             Phi = rPI(Phi + 2*PI / Num);
         };
     };
     DestroySmoothPut(x0,y0,SmoothRadius);
     int x1,y1;
     rx = XCYCL(x0 - SmoothRadius);
     ry = YCYCL(y0 - SmoothRadius);
     x1 = XCYCL(x0 + SmoothRadius);
     y1 = YCYCL(y0 + SmoothRadius);
 #ifdef _ROAD_
     if(CurrentWorld != WORLD_NECROSS)
 #endif
         regSet(rx,ry,x1,y1,1,0);
     regRender(rx,ry,x1,y1);
     return 1;
 };
References XErrorHandler::Abort(), ALT_PROTECTED_OFFSET, AltProtectedTable, CO, CurrentWorld, DestroyBarellSpot(), DestroySmoothPut(), DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, ErrH, GET_TERRAIN, H_SIZE, NumDestroyRadius, PI, RadiusDestroyX, RadiusDestroyY, regRender(), regSet(), RND(), rPI, SI, SmoothTerrainMask, TERRAIN_MAX, vMap, WORLD_NECROSS, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, MobileLocation::y1, and YCYCL.
DestroyBarellSpot()
void DestroyBarellSpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
 {
     uchar* pa0,*pf0;
     int i,j;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     uchar t;
     int r;
     int* dx,*dy;
     int rrad;
     switch(rfactor){
         case 0:
             rrad = 0;
             break;
         case 1:
             rrad = Radius >> 3;
             break;
         case 2:
             rrad = Radius >> 2;
             break;
         case 3:
             rrad = Radius >> 1;
             break;
         case 4:
             rrad = Radius;
             break;
         case 5:
             rrad = Radius << 1;
             break;
         case 6:
             rrad = Radius << 2;
             break;
         case 7:
             rrad = Radius << 3;
             break;
         case 8:
             rrad = Radius << 4;
             break;
     };
     if(Radius > MAX_DESTROY_RADIUS)
         ErrH.Abort("Bad Spot Radius");
     if(terrain == 83){
         for(i = 0;i < Radius;i++){
             dx = RadiusDestroyX[i];
             dy = RadiusDestroyY[i];
             r = (Radius - i) * delta >> 8;
             for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
                 if((int)RND(rrad) < Radius - i){
                     rx = XCYCL((*dx) + x0);
                     ry = YCYCL((*dy) + y0);
                     pa0 = lt[ry] + rx;
                     pf0 = pa0 + H_SIZE;
                     if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                         if(*pf0 & DOUBLE_LEVEL){
                             if(rx & 1) *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                         }else
                             *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                     };
                 };
             };
         };
     }else{
         t = terrain <<TERRAIN_OFFSET;
         for(i = 0;i < Radius;i++){
             dx = RadiusDestroyX[i];
             dy = RadiusDestroyY[i];
             r = (Radius - i) * delta >> 8;
             for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
                 if((int)RND(rrad) < Radius - i){
                     rx = XCYCL((*dx) + x0);
                     ry = YCYCL((*dy) + y0);
                     pa0 = lt[ry] + rx;
                     pf0 = pa0 + H_SIZE;
                     if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                         if(*pf0 & DOUBLE_LEVEL){
                             if(rx & 1){
                                 *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                                 SET_TERRAIN(*pf0,t);
                             };
                         }else{
                             *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                             SET_TERRAIN(*pf0,t);
                         };
                     };
                 };
             };
         };
     };
 };
References XErrorHandler::Abort(), ALT_PROTECTED_OFFSET, AltProtectedTable, DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, ErrH, GET_TERRAIN, H_SIZE, NumDestroyRadius, RadiusDestroyX, RadiusDestroyY, RND(), SET_TERRAIN, SmoothTerrainMask, TERRAIN_OFFSET, vMap, MobileLocation::x0, XCYCL, MobileLocation::y0, and YCYCL.
Referenced by DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), and DestroySmooth().
DestroySmooth()
void DestroySmooth (int x0, int y0, int SmoothRadius, int SpotRadius, int Delta, int cDelta, uchar terrain, int Num, uchar rfactor)
 {
     int Phi = RND(PI/2);
     int i,n,rx,ry;
     uchar** lt = vMap -> lineT;
     for(i = y0 - SmoothRadius;i <= y0 + SmoothRadius;i++) if(!lt[YCYCL(i)]) return;
 //  for(i = 0;i < TERRAIN_MAX;i++) SmoothTerrainMask[i] = 1;
     memset(SmoothTerrainMask,1,TERRAIN_MAX);
 //  if(CurrentWorld == WORLD_NECROSS) SmoothTerrainMask[0] = 0;
     SmoothTerrainMask[4] = 0;
     SmoothTerrainMask[5] = 0;
     if(Delta > 0){
         for(i = 0;i < Num;i++){
             n = RND(SmoothRadius - SpotRadius);
             rx = XCYCL(x0 + ((CO[Phi] * n) >> 16));
             ry = YCYCL(y0 + ((SI[Phi] * n) >> 16));
             DestroyBarellSpot(rx,ry,SpotRadius,terrain,cDelta + RND(Delta),rfactor);
             Phi = rPI(Phi + 2*PI / Num);
         };
     }else{
         for(i = 0;i < Num;i++){
             n = RND(SmoothRadius - SpotRadius);
             rx = XCYCL(x0 + ((CO[Phi] * n) >> 16));
             ry = YCYCL(y0 + ((SI[Phi] * n) >> 16));
             DestroyBarellSpot(rx,ry,SpotRadius,terrain,cDelta - RND(-Delta),rfactor);
             Phi = rPI(Phi + 2*PI / Num);
         };
     };
     DestroySmoothPut(x0,y0,SmoothRadius);
     int x1,y1;
     rx = XCYCL(x0 - SmoothRadius);
     ry = YCYCL(y0 - SmoothRadius);
     x1 = XCYCL(x0 + SmoothRadius);
     y1 = YCYCL(y0 + SmoothRadius);
 #ifdef _ROAD_
     if(CurrentWorld != WORLD_NECROSS)
 #endif
         regSet(rx,ry,x1,y1,1,0);
     regRender(rx,ry,x1,y1);
 };
References CO, CurrentWorld, DestroyBarellSpot(), DestroySmoothPut(), PI, regRender(), regSet(), RND(), rPI, SI, SmoothTerrainMask, TERRAIN_MAX, vMap, WORLD_NECROSS, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, MobileLocation::y1, and YCYCL.
DestroySmoothCheck()
void DestroySmoothCheck (int x0, int y0, int Radius)
 {
     uchar *pf0,*pf1,*pac,*pc0;
     uchar v,a;
     int i,j;
     unsigned int t;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int x1,y1;
     int xx,yy;
     unsigned int l;
     int* dx,*dy;
     for(i = y0 - Radius;i <= y0 + Radius;i++) if(!lt[YCYCL(i)]) return;
     for(i = Radius - 1;i >= 0;i--){
         dx = RadiusDestroyX[i];
         dy = RadiusDestroyY[i];
         l = Radius - i;
         for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
             if(RND(Radius) < l ){
                 int hrx = (rx = XCYCL((*dx) + x0)) + H_SIZE;
                 ry = YCYCL((*dy) + y0);
                 pf0 = (pc0 = lt[ry]) + H_SIZE;
                 a = *(pf0 + rx);
                 if(SmoothTerrainMask[GET_TERRAIN(a)]){
                     if(a & DOUBLE_LEVEL){
                         if(rx ^ 1){
                             v = *(pac = pc0 + rx);
                             pf1 = pf0 + (xx = XCYCL(rx + 2));
                             if((*pf1) & DOUBLE_LEVEL) t = *(pc0 + xx);
                             else t = v;
                             pf1 = pf0 + (xx = XCYCL(rx - 2));
                             if((*pf1) & DOUBLE_LEVEL) t += *(pc0 + xx);
                             else t += v;
                             pf1= lt[yy = YCYCL(ry - 1)] + hrx;
                             if((*pf1) & DOUBLE_LEVEL) t += *(lt[yy] + rx);
                             else t += v;
                             pf1= lt[yy = YCYCL(ry + 1)] + hrx;
                             if((*pf1) & DOUBLE_LEVEL) t += *(lt[yy] + rx);
                             else t += v;
                             *pac = t >> 2;
                         }// if rx;
                     }else{
                         v = *(pac = pc0 + rx);
                         pf1 = pf0 + (xx = XCYCL(rx + 1));
                         if((*pf1) & DOUBLE_LEVEL) t = v;
                         else t = *(pc0 + xx);
                         pf1 = pf0 + (xx = XCYCL(rx - 1));
                         if((*pf1) & DOUBLE_LEVEL) t += v;
                         else t += *(pc0 + xx);
                         pf1= lt[yy = YCYCL(ry - 1)] + hrx;
                         if((*pf1) & DOUBLE_LEVEL) t += v;
                         else t += *(lt[yy] + rx);
                         pf1= lt[yy = YCYCL(ry + 1)] + hrx;
                         if((*pf1) & DOUBLE_LEVEL) t += v;
                         else t += *(lt[yy] + rx);
                         *pac = t >> 2;
                     }//  if DOUBLE;
                 }//  if Smooth;
             }//  if RND;
         }//  for j;
     }//  for i;
     rx = XCYCL(x0 - Radius);
     ry = YCYCL(y0 - Radius);
     x1 = XCYCL(x0 + Radius);
     y1 = YCYCL(y0 + Radius);
 #ifdef _ROAD_
     if(CurrentWorld != WORLD_NECROSS)
 #endif
         regSet(rx,ry,x1,y1,1,0);
     regRender(rx,ry,x1,y1);
 };
References CurrentWorld, DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, GET_TERRAIN, H_SIZE, NumDestroyRadius, RadiusDestroyX, RadiusDestroyY, regRender(), regSet(), RND(), SmoothTerrainMask, vMap, WORLD_NECROSS, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, MobileLocation::y1, and YCYCL.
DestroySmoothFree()
void DestroySmoothFree (void)
 {
     int i;
     for(i = 0;i < MAX_DESTROY_RADIUS;i++){
         NumDestroyRadius[i] = 0;
         delete[] RadiusDestroyX[i];
         delete[] RadiusDestroyY[i];
     };
     delete[] AltProtectedTable;
     delete[] NumDestroyRadiusTable;
 };
References AltProtectedTable, NumDestroyRadius, NumDestroyRadiusTable, RadiusDestroyX, and RadiusDestroyY.
DestroySmoothInit()
void DestroySmoothInit (void)
 {
     NumDestroyRadiusTable = new short[MAX_DESTROY_SIDE*MAX_DESTROY_SIDE];
     int i,j,r,ind;
     short* p = NumDestroyRadiusTable;
     int* xheap;
     int* yheap;
     for(j = -MAX_DESTROY_RADIUS;j <= MAX_DESTROY_RADIUS;j++){
         for(i = -MAX_DESTROY_RADIUS;i <= MAX_DESTROY_RADIUS;i++){
             r = (int)sqrt(i*(double)i + j*(double)j);
             if(r >= MAX_DESTROY_RADIUS){
                 *p = r;
             }   else{
                 *p = r;
                 NumDestroyRadius[r]++;
             };
             p++;
         };
     };
     for(ind = 0;ind < MAX_DESTROY_RADIUS;ind++){
         RadiusDestroyX[ind] = new int[NumDestroyRadius[ind]];
         RadiusDestroyY[ind] = new int[NumDestroyRadius[ind]];
         xheap = RadiusDestroyX[ind];
         yheap = RadiusDestroyY[ind];
         for(p = NumDestroyRadiusTable,r = 0,j = -MAX_DESTROY_RADIUS;j <= MAX_DESTROY_RADIUS;j++){
             for(i = -MAX_DESTROY_RADIUS;i <= MAX_DESTROY_RADIUS;i++){
                 if(*p == ind){
                     xheap[r] = i;
                     yheap[r] = j;
                     r++;
                 };
                 p++;
             };
         };
     };
     AltProtectedTable = new uchar[256*ALT_PROTECTED_VALUE];
     for(i = 0;i < 256*ALT_PROTECTED_VALUE;i++){
         if(i < ALT_PROTECTED_OFFSET) AltProtectedTable[i] = 0;
         else{
             if(i > ALT_PROTECTED_OFFSET + 255) AltProtectedTable[i] = 255;
             else AltProtectedTable[i] = i - ALT_PROTECTED_OFFSET;
         };
     };
 };
References ALT_PROTECTED_OFFSET, ALT_PROTECTED_VALUE, AltProtectedTable, MAX_DESTROY_SIDE, NumDestroyRadius, NumDestroyRadiusTable, RadiusDestroyX, and RadiusDestroyY.
DestroySmoothPut()
void DestroySmoothPut (int x0, int y0, int Radius)
 {
     uchar *pf0,*pf1,*pac,*pc0;
     uchar v,a;
     int i,j;
     unsigned int t;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int xx,yy;
     unsigned int l;
     int* dx,*dy;
     if(Radius >= MAX_DESTROY_RADIUS)
         ErrH.Abort("Bad Smooth Radius");
     for(i = Radius - 1;i >= 0;i--){
         dx = RadiusDestroyX[i];
         dy = RadiusDestroyY[i];
         l = Radius - i;
         for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
             if(RND(Radius) < l){
                 int hrx = (rx = XCYCL((*dx) + x0)) + H_SIZE;
                 ry = YCYCL((*dy) + y0);
                 pf0 = (pc0 = lt[ry]) + H_SIZE;
                 a = *(pf0 + rx);
                 if(SmoothTerrainMask[GET_TERRAIN(a)]){
                     if(a & DOUBLE_LEVEL){
                         if(rx ^ 1){
                             v = *(pac = pc0 + rx);
                             pf1 = pf0 + (xx = XCYCL(rx + 2));
                             if((*pf1) & DOUBLE_LEVEL) t = *(pc0 + xx);
                             else t = v;
                             pf1 = pf0 + (xx = XCYCL(rx - 2));
                             if((*pf1) & DOUBLE_LEVEL) t += *(pc0 + xx);
                             else t += v;
                             pf1= lt[yy = YCYCL(ry - 1)] + hrx;
                             if((*pf1) & DOUBLE_LEVEL) t += *(lt[yy] + rx);
                             else t += v;
                             pf1= lt[yy = YCYCL(ry + 1)] + hrx;
                             if((*pf1) & DOUBLE_LEVEL) t += *(lt[yy] + rx);
                             else t += v;
                             *pac = t >> 2;
                         };
                     }else{
                         v = *(pac = pc0 + rx);
                         pf1 = pf0 + (xx = XCYCL(rx + 1));
                         if((*pf1) & DOUBLE_LEVEL) t = v;
                         else t = *(pc0 + xx);
                         pf1 = pf0 + (xx = XCYCL(rx - 1));
                         if((*pf1) & DOUBLE_LEVEL) t += v;
                         else t += *(pc0 + xx);
                         pf1= lt[yy = YCYCL(ry - 1)] + hrx;
                         if((*pf1) & DOUBLE_LEVEL) t += v;
                         else t += *(lt[yy] + rx);
                         pf1= lt[yy = YCYCL(ry + 1)] + hrx;
                         if((*pf1) & DOUBLE_LEVEL) t += v;
                         else t += *(lt[yy] + rx);
                         *pac = t >> 2;
                     };
                 };
             };
         };
     };
 };
References XErrorHandler::Abort(), DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, ErrH, GET_TERRAIN, H_SIZE, NumDestroyRadius, RadiusDestroyX, RadiusDestroyY, RND(), SmoothTerrainMask, vMap, MobileLocation::x0, XCYCL, MobileLocation::y0, and YCYCL.
Referenced by DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), and DestroySmooth().
DestroySpot()
void DestroySpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
 {
     uchar* pa0,*pf0;
     int i,j;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     uchar t;
     int r;
     int* dx,*dy;
     int rrad;
     for(i = y0 - Radius;i <= y0 + Radius;i++) if(!lt[YCYCL(i)]) return;
     switch(rfactor){
         case 0:
             rrad = 0;
             break;
         case 1:
             rrad = Radius >> 3;
             break;
         case 2:
             rrad = Radius >> 2;
             break;
         case 3:
             rrad = Radius >> 1;
             break;
         case 4:
             rrad = Radius;
             break;
         case 5:
             rrad = Radius << 1;
             break;
         case 6:
             rrad = Radius << 2;
             break;
         case 7:
             rrad = Radius << 3;
             break;
         case 8:
             rrad = Radius << 4;
             break;
     };
     if(terrain == 83){
         for(i = 0;i < Radius;i++){
             dx = RadiusDestroyX[i];
             dy = RadiusDestroyY[i];
             r = (Radius - i) * delta >> 8;
             for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
                 if((int)RND(rrad) < Radius - i){
                     rx = XCYCL((*dx) + x0);
                     ry = YCYCL((*dy) + y0);
                     pa0 = lt[ry] + rx;
                     pf0 = pa0 + H_SIZE;
                     if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                         if(*pf0 & DOUBLE_LEVEL){
                             if(rx & 1)
                                 *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                         }else
                             *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                     };
                 };
             };
         };
     }else{
         t = terrain <<TERRAIN_OFFSET;
         for(i = 0;i < Radius;i++){
             dx = RadiusDestroyX[i];
             dy = RadiusDestroyY[i];
             r = (Radius - i) * delta >> 8;
             for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
                 if((int)RND(rrad) < Radius - i){
                     rx = XCYCL((*dx) + x0);
                     ry = YCYCL((*dy) + y0);
                     pa0 = lt[ry] + rx;
                     pf0 = pa0 + H_SIZE;
                     if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                         if(*pf0 & DOUBLE_LEVEL){
                             if(rx & 1){
                                 *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                                 SET_TERRAIN(*pf0,t);
                             };
                         }else{
                             *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                             SET_TERRAIN(*pf0,t);
                         };
                     };
                 };
             };
         };
     };
     int x1,y1;
     rx = XCYCL(x0 - Radius);
     ry = YCYCL(y0 - Radius);
     x1 = XCYCL(x0 + Radius);
     y1 = YCYCL(y0 + Radius);
 #ifdef _ROAD_
     if(CurrentWorld != WORLD_NECROSS)
 #endif
         regSet(rx,ry,x1,y1,1,0);
     regRender(rx,ry,x1,y1);
 };
References ALT_PROTECTED_OFFSET, AltProtectedTable, CurrentWorld, DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, GET_TERRAIN, H_SIZE, NumDestroyRadius, RadiusDestroyX, RadiusDestroyY, regRender(), regSet(), RND(), SET_TERRAIN, SmoothTerrainMask, TERRAIN_OFFSET, vMap, WORLD_NECROSS, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, MobileLocation::y1, and YCYCL.
GetLandAlt()
int GetLandAlt (int x0, int y0, int Radius)
 {
 /*  uchar *pc0,*pf0;
     int t,i,j,t1;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int* dx,*dy;
     for(i = y0 - Radius;i <= y0 + Radius;i++) if(!lt[YCYCL(i)]) return -1;
     t1 = 255;
     for(i = 0;i < Radius;i++){
         if(RND(Radius) < i){
             dx = RadiusDestroyX[i];
             dy = RadiusDestroyY[i];
             for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
                 rx = XCYCL((*dx) + x0);
                 ry = YCYCL((*dy) + y0);
                 pf0 = (pc0 = lt[ry]) + H_SIZE;
                 if(((*(pf0 + rx)) & DOUBLE_LEVEL) && (rx & 1)){
                     t = *(pc0 + rx);
                     if(t < t1) t1 = t;
                 };
             };
         };
     };
     return t1;*/
     uchar *pf0,*pf;
     uchar** lt;
     lt = vMap -> lineT;
     int t,i,j,t1;
     t1 = 255;
     for(i = y0 - Radius;i <= y0 + Radius;i++) if(!lt[YCYCL(i)]) return -1;
     if(!(x0 & 1)) x0 = XCYCL(x0 + 1);
     for(i = -Radius;i < Radius;i++){
         pf0 = lt[YCYCL(y0 + i)] + H_SIZE;
         for(j = -Radius;j < Radius;j += 2){
             pf = pf0 + XCYCL(x0 + j);
             if((*pf) & DOUBLE_LEVEL){
                 t = *(pf - H_SIZE);
                 if(t < t1) t1 = t;
             };
         };
     };
     return t1;
 };
References DOUBLE_LEVEL, H_SIZE, pf, vMap, MobileLocation::x0, XCYCL, MobileLocation::y0, and YCYCL.
GetSmoothUpAlt()
int GetSmoothUpAlt (uchar * type, uchar * pa0, int x) inline
 {
     if(IS_DOUBLE(*type)){
         if(x & 1) return *(pa0 + x);
         else return *(pa0 + x + 1);
     };
     return *(pa0 + x);
 };
References IS_DOUBLE.
LandSlideLine()
int LandSlideLine (int x0, int y0, int z0, int x1, int delta)
 {
     uchar *pf,*pf0,*pc0,*pc;
     int f;
     int i,l;
     uchar* lt;
     uchar a0,a1,f0,f1;
     int r1,r2;
     int cnt;
     y0 = YCYCL(y0);
     lt = vMap -> lineT[y0];
     if(!lt) return 0;
     cnt = 0;
     if(x0 & 1) x0--;
     x0 = XCYCL(x0);
     if(!(x1 & 1)) x1++;
     x1 = XCYCL(x1);
     r1 = x1 - x0;
     r2 = TOR_XSIZE - r1;
     if(r1 > r2) l = r2;
     else l = r1;
     pc0 = lt + x0;
     pf0 = pc0 + H_SIZE;
     f = x0;
     for(i = 0;i < l;i++){
         if(f & 1){
             f1 = *pf0;
             if(f1 & DOUBLE_LEVEL){
                 a1 = *pc0;
                 if(a1 < z0){
                     *pc0 = (a0 + RND(delta));
                     *pc = (a0 + RND(delta));
                     f1 &= ~(DELTA_MASK | DOUBLE_LEVEL);
                     *pf = *pf0 = f1;
                     if(RND(5000) < 5)
                         EffD.CreateFireBall(Vector(XCYCL(x0 + i),y0,z0 + 20),DT_FIRE_BALL05,NULL,1 << 8,0);
                     cnt++;
                 };
             };
         }else{
             f0 = *pf0;
             if(f0 & DOUBLE_LEVEL){
                 a0 = *pc0;
                 pf = pf0;
                 pc = pc0;
             };
         };
         if(f >= clip_mask_x){
             f = 0;
             pc0 = lt;
             pf0 = pc0 + H_SIZE;
         }else{
             f++;
             pf0++;
             pc0++;
         };
     };
     int nx,ny;
         nx = XCYCL(x0 + 10 - RND(20));
         ny = YCYCL(y0 + 10 - RND(20));
         lt = vMap -> lineT[ny];
         if(!lt) return cnt;
         pc0 = lt + nx;
         pf0 = pc0 + H_SIZE;
         if((*pf0) & DOUBLE_LEVEL){
             if(nx & 1) nx = XCYCL(nx + 1);
             a0 = *pc0;
             if(a0 > delta && a0 < 255 - delta)
                 *pc0 = a0 + (delta >> 1) - RND(delta);
         };
         nx = XCYCL(x1 + 10 - RND(20));
         ny = YCYCL(y0 + 10 - RND(20));
         lt = vMap -> lineT[ny];
         if(!lt) return cnt;
         pc0 = lt + nx;
         pf0 = pc0 + H_SIZE;
         if((*pf0) & DOUBLE_LEVEL){
             if(nx & 1) nx = XCYCL(nx + 1);
             a0 = *pc0;
             if(a0 > delta && a0 < 255 - delta)
                 *pc0 = a0 + (delta >> 1) - RND(delta);
         };
     return cnt;
 };
References clip_mask_x, EffectDispatcher::CreateFireBall(), DELTA_MASK, DOUBLE_LEVEL, DT_FIRE_BALL05, EffD, H_SIZE, NULL, pf, RND(), TOR_XSIZE, vMap, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, and YCYCL.
Referenced by LandSlideProcess().
LandSlideProcess()
int LandSlideProcess (int * fx, int * fy, int pow, int z0, int delta)
 {
     int xl,xr;
     int kl,kr;
     int al,bl,ar,br;
     int d;
     int where;
     int Y;
     int i;
     int fv,rv,lv;
     int n,n_clip;
     int cnt;
     cnt = 0;
     n = 1 << pow;
     n_clip = n - 1;
     Y = fy[0];
     fv = 0;
     for(i = 1;i < n;i++){
         if(fy[i] < Y){
             Y = fy[i];
             fv = i;
         };
     };
     rv = (fv - 1) & n_clip;
     lv = (fv + 1) & n_clip;
     xl = fx[fv];
     al = fx[lv] - xl;
     bl = fy[lv] - Y;
     ar = fx[rv] - xl;
     br = fy[rv] - Y;
     xl = (xl << 16) + (1 << 15);
     xr = xl;
     if(bl == 0) kl = al;
     else kl = (al << 16) / bl;
     if(br == 0) kr = ar;
     else kr = (ar << 16) / br;
     if(bl < 0) bl = -bl;
     if(br < 0) br = -br;
     while(1){
         if(bl > br){
             d = br;
             where = 0;
         }else{
             d = bl;
             where = 1;
         };
         while(d--){
 //          LandSlideLine(int x0,int y0,int z0,int l,int delta);
             cnt += LandSlideLine(xl >> 16,Y,z0,xr >> 16,delta);
             xl += kl;
             xr += kr;
             Y++;
         };
         if(where){
             if(lv == rv) return cnt;
             fv = lv;
             lv = (fv + 1) & n_clip;
             br -= bl;
             xl = fx[fv];
             al = fx[lv] - xl;
             bl = fy[lv] - Y;
             xl = (xl << 16) + (1 << 15);
             if(bl == 0) kl = al;
             else kl = (al << 16) / bl;
             if(al < 0) al = -al;
         }else{
             if(rv == lv) return cnt;
             fv = rv;
             rv = (rv - 1) & n_clip;
             bl -= br;
             xr = fx[fv];
             ar = fx[rv] - xr;
             br = fy[rv] - Y;
             xr = (xr << 16) + (1 << 15);
             if(br == 0) kr = ar;
             else kr = (ar << 16) / br;
             if(ar < 0) ar = -ar;
         };
     };
 };
References LandSlideLine().
MakeSecondLevel()
void MakeSecondLevel (int x0, int y0, uchar z0, int Radius)
 {
     uchar *pf0,*pf1,*pf;
     uchar** lt;
     lt = vMap -> lineT;
     int t,i,j;
     int d = 32;
     for(i = y0 - Radius;i <= y0 + Radius;i++) if(!lt[YCYCL(i)]) return;
     for(i = -Radius;i < Radius;i++){
         pf1 = NULL;
         pf0 = lt[YCYCL(y0 + i)] + H_SIZE;
         for(j = -Radius;j < Radius;j++){
             t = XCYCL(x0 + j);
             pf = pf0 + t;
             if(t & 1){
                 if(/*GET_TERRAIN(*pf) == 1 || */pf1){
                     *(pf) |= (DOUBLE_LEVEL);
                     SET_DELTA(*pf,(d & 3));
                 };
             }else{
 //              if(GET_TERRAIN(*pf) == 1){
                     *(pf - H_SIZE) = z0;
                     *(pf) |= (DOUBLE_LEVEL);
                     SET_DELTA(*pf,(d & 12) >> 2);
                     pf1 = pf;
 //              }else pf1 = NULL;
             };
         };
     };
     RadialRender(x0,y0,Radius);
 };
References DOUBLE_LEVEL, H_SIZE, NULL, pf, RadialRender(), SET_DELTA, vMap, MobileLocation::x0, XCYCL, MobileLocation::y0, and YCYCL.
MapCircleProcess()
void MapCircleProcess (int x0, int y0, int z0, int r0, int mode, uchar terrain)
 {
     uchar *pc,*pf0,*pf,*ph;
     int j;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int* dx,*dy;
     uchar delta0,delta1;
     uchar t1;
     int z;
     x0 |= 1;
     for(j = y0 - r0;j <= y0 + r0;j++) if(!lt[YCYCL(j)]) return;
     if(r0 < 0 || r0 > MAX_DESTROY_RADIUS) return;
     delta0 = 32 & 3;
     delta1 = (32 & 12) >> 2;
     if(mode){
         dx = RadiusDestroyX[r0];
         dy = RadiusDestroyY[r0];
         for(j = 0;j < NumDestroyRadius[r0];j++,dx++,dy++){
             rx = XCYCL((*dx) + x0);
             ry = YCYCL((*dy) + y0);
             pf0 =  lt[ry] + H_SIZE;
             pf = pf0 + rx;
             if(((*pf) & DOUBLE_LEVEL) && !(rx & 1)){
                 *pf &= ~(DELTA_MASK | DOUBLE_LEVEL);
                 *(pf + 1) = *pf;
                 ph = pf - H_SIZE;
                 if((z = (int)*ph + *(ph + 1) - z0) >= 0){
                     *(ph + 1) = z;
                     SET_DELTA(*pf,1);
                     }
                 else
                     SET_DELTA(*pf,2);
             };
         };
     }else{
         t1 = terrain << TERRAIN_OFFSET;
         dx = RadiusDestroyX[r0];
         dy = RadiusDestroyY[r0];
         for(j = 0;j < NumDestroyRadius[r0];j++,dx++,dy++){
             rx = XCYCL((*dx) + x0);
             ry = YCYCL((*dy) + y0);
             pf0 = lt[ry] + H_SIZE;
             pf = pf0 + rx;
             if(!(*pf & DOUBLE_LEVEL) && !(rx & 1) && *pf & DELTA_MASK){
                 pc = pf + 1;
                 *pf |= DOUBLE_LEVEL;
                 SET_DELTA(*pf,delta1);
                 SET_DELTA(*pc,delta0);
                 SET_TERRAIN(*pc,t1);
                 *pc |= DOUBLE_LEVEL;
                 pc -= H_SIZE;
                 *pc = z0 + *pc - *(pf - H_SIZE);
             };
         };
     };
 };
References DELTA_MASK, DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, H_SIZE, MobileLocation::mode, NumDestroyRadius, pf, RadiusDestroyX, RadiusDestroyY, SET_DELTA, SET_TERRAIN, TERRAIN_OFFSET, vMap, MobileLocation::x0, XCYCL, MobileLocation::y0, and YCYCL.
MLfree()
void MLfree (void)
 {
     int i;
     if (ML_FRAME_DELTA) {
         delete[] ML_FRAME_DELTA;
         ML_FRAME_DELTA = NULL;
     }
     if (ML_FRAME_TERRAIN) {
         delete[] ML_FRAME_TERRAIN;
         ML_FRAME_TERRAIN = NULL;
     }
     for(i = 0;i < MLTableSize;i++) {
         delete MLTable[i];
     }
     delete[] MLTable;
     MLTableSize = 0;
 #ifdef _ROAD_
     for(i = 0;i < 8;i++)
         delete MLobjBug[i];
     for(i = 0;i < 4;i++)
         delete MLobjExp[i];
     for(i = 0;i < 2;i++)
         if(MLTnt[i]){
             delete MLTnt[i];
             MLTnt[i] = NULL;
             }
 #endif
 #ifdef _SURMAP_
     TntValoc::tail = NULL;
     MLCloneValoc::tail = NULL;
     SensorValoc::tail = NULL;
     DangerValoc::tail = NULL;
     delete TntTable;
     delete MLCTable;
     delete SnsTable;
     delete DngTable;
     TntTableSize = 0;
     MLCTableSize = 0;
     SnsTableSize = 0;
     DngTableSize = 0;
 #endif
 #ifdef _ROAD_
     ValocTableFree();
 #endif
 };
Referenced by FreeAll().
MLload()
void MLload (void)
 {
     int i,j,t;
     XBuffer buf;
 #ifdef _ROAD_
     int k;
     for(i = 0;i < NumSkipLocation[CurrentWorld];i++)
         NumLocationData[CurrentWorld][i] = i;
     for(i = 0;i < NumSkipLocation[CurrentWorld];i++){
         j = RND(NumSkipLocation[CurrentWorld]);
         k = RND(NumSkipLocation[CurrentWorld]);
         if(j != k){
             t = NumLocationData[CurrentWorld][j];
             NumLocationData[CurrentWorld][j] = NumLocationData[CurrentWorld][k];
             NumLocationData[CurrentWorld][k] = t;
         };
     };
     for(i = 0;i < 8;i++){
         buf.init();
         buf < "resource/mlvot/bugtrl" <= i < ".vot";
         (MLobjBug[i] = new MobileLocation) -> load(buf.GetBuf(),1);
         }
     for(i = 0;i < 4;i++){
         buf.init();
         buf < "resource/mlvot/exptrl" <= i < ".vot";
         (MLobjExp[i] = new MobileLocation) -> load(buf.GetBuf(),1);
         }
     for(i = 0;i < 2;i++){
         buf.init();
         if(strcmp(MLTntName[CurrentWorld][i],"None")){
             buf < "resource/mlvot/" < MLTntName[CurrentWorld][i] < ".vot";
             (MLTnt[i] = new MobileLocation) -> load(buf.GetBuf(),1);
         }else MLTnt[i] = 0;
     };
 #endif
 MLTableSize = 0;
 #if !(defined(__unix__) || defined(__APPLE__))
     buf.init();
     buf < "data.vot/*.vot";
     char* fn = win32_findfirst(GetTargetName(buf.GetBuf()));
     while(fn){
         MLTableSize++;
         fn = win32_findnext();
         }
 #else
     std::string tmp = path_to_world+"data.vot/";
     struct dirent **namelist;
     int n;
     n = scandir(tmp.c_str(), &namelist, 0, alphasort);
     if (n < 0)
         perror("scandir");
     else {
         while(n--) {
             std::string name = namelist[n]->d_name;
             if (name.find(".vot")!=std::string::npos)
                 MLTableSize++;
             free(namelist[n]);
         }
     free(namelist);
     }
 #endif
 #ifdef _ROAD_
 #if !(defined(__unix__) || defined(__APPLE__))
     MLTableSize -= NumSkipLocation[CurrentWorld] - RealNumLocation[CurrentWorld];
 #endif
 #endif
     MLTable = new MobileLocation*[MLTableSize];
     i = 0;
 #if !(defined(__unix__) || defined(__APPLE__))
     fn = win32_findfirst(GetTargetName(buf.GetBuf()));
     while(fn){
         t = 1;
 #ifdef _ROAD_
         for(j = 0;j < NumSkipLocation[CurrentWorld];j++){
             if(!strcmp(fn,SkipLocationName[CurrentWorld][NumLocationData[CurrentWorld][j]])){
                 if(j >= RealNumLocation[CurrentWorld])
                     t = 0;
                 break;
                 }
             }
 #endif
         if(t){
             (MLTable[i] = new MobileLocation) -> load(fn);
              i++;
             }
         fn = win32_findnext();
     };
 #else
     struct dirent **namelist2;
     n = scandir(tmp.c_str(), &namelist2, 0, alphasort);
     if (n < 0)
         perror("scandir");
     else {
         while(n--) {
             std::string name = namelist2[n]->d_name;
             if (name.find(".vot")!=std::string::npos)
                 {
                 (MLTable[i] = new MobileLocation) -> load(namelist2[n]->d_name);
                 i++;
                 }
             else
                 free(namelist2[n]);
         }
     //free(namelist2);
     }
 #endif
     VLload();
     ML_FRAME_DELTA = new uchar[ML_FRAME_SIZE];
     ML_FRAME_TERRAIN = new uchar[ML_FRAME_SIZE];
 };
References CurrentWorld, XBuffer::GetBuf(), GetTargetName(), XBuffer::init(), MLobjBug, MLobjExp, MLTable, MLTableSize, MLTnt, MLTntName, NumLocationData, NumSkipLocation, path_to_world, RealNumLocation, RND(), SkipLocationName, VLload(), win32_findfirst(), and win32_findnext().
MLquant()
int MLquant (void)
 {
 #ifdef _SURMAP_
     if(MLstatus || !MLprocess) return 0;
 #endif
     int ret = 0;
     for(int i = 0;i < MLTableSize;i++) ret += MLTable[i] -> quant();
     return ret;
 }
References MLprocess, MLstatus, MLTable, MLTableSize, and MobileLocation::quant().
MLreload()
void MLreload (void)
 {
     int i;
     delete[] ML_FRAME_DELTA;
     ML_FRAME_DELTA = NULL;
     delete[] ML_FRAME_TERRAIN;
     ML_FRAME_TERRAIN = NULL;
     for(i = 0;i < MLTableSize;i++) {
         delete MLTable[i];
     }
     delete[] MLTable;
 #ifdef _ROAD_
     for(i = 0;i < 8;i++)
         delete MLobjBug[i];
     for(i = 0;i < 4;i++)
         delete MLobjExp[i];
     for(i = 0;i < 2;i++)
         if(MLTnt[i]){
             delete MLTnt[i];
             MLTnt[i] = NULL;
             }
 #endif
     MLTableSize = 0;
 #ifdef _SURMAP_
     TntValoc::tail = NULL;
     MLCloneValoc::tail = NULL;
     SensorValoc::tail = NULL;
     DangerValoc::tail = NULL;
     delete TntTable;
     delete MLCTable;
     delete SnsTable;
     delete DngTable;
     TntTableSize = 0;
     MLCTableSize = 0;
     SnsTableSize = 0;
     DngTableSize = 0;
 #endif
 #ifdef _ROAD_
     ValocTableFree();
 #endif
     MLload();
 //  VLload();
 };
Referenced by ChangeWorld().
MLReset()
void MLReset (void)
 {
     for(int i = 0;i < MLTableSize;i++) MLTable[i]->reset();
 };
MLsave()
void MLsave (void)
 {
 #ifdef _SURMAP_
     for(int i = 0;i < MLTableSize;i++) MLTable[i] -> save();
 #endif
 }
References MLTable, and MLTableSize.
RadialRender()
void RadialRender (int x0, int y0, int radius)
 {
     int i;
     int x1,y1;
     int rx,ry;
     uchar** lt = vMap -> lineT;
     for(i = y0 - radius;i <= y0 + radius;i++) if(!lt[YCYCL(i)]) return;
     rx = XCYCL(x0 - radius);
     ry = YCYCL(y0 - radius);
     x1 = XCYCL(x0 + radius);
     y1 = YCYCL(y0 + radius);
 #ifdef _ROAD_
     if(CurrentWorld != WORLD_NECROSS)
 #endif
         regSet(rx,ry,x1,y1,1,0);
     regRender(rx,ry,x1,y1);
 };
References CurrentWorld, regRender(), regSet(), vMap, WORLD_NECROSS, MobileLocation::x0, MobileLocation::x1, XCYCL, MobileLocation::y0, MobileLocation::y1, and YCYCL.
Referenced by MakeSecondLevel(), and DangerDataType::Quant().
VLload()
void VLload (void)
 {
     const char* errm = "Wrong VLC format";
     XBuffer buf;
     XStream ff(0);
     char sign[8];
     int i;
     buf < "data.vot/" < VLfilenames[0] < ".vlc";
     if(ff.open(GetTargetName(buf.GetBuf()),XS_IN)){
         ff.read(sign,strlen(VLCsign[0]));
         if(memcmp(sign,VLCsign[0],strlen(VLCsign[0]))) ErrH.Abort(errm);
         ff > TntTableSize;
 #ifdef _SURMAP_
         TntTable = new TntValoc[TntTableSize];
         for(i = 0;i < TntTableSize;i++){
             TntTable[i].load(ff);
             TntTable[i].link();
         }
 #else
     #ifdef NEW_TNT
         TntObjectData = new TntCreature*[TntTableSize];
         for(i = 0;i < TntTableSize;i++){
             TntObjectData[i] = new TntCreature;
             TntObjectData[i]->Load(ff);
         };
     #else
         TntObjectData = new TntStaticObject*[TntTableSize];
         for(i = 0;i < TntTableSize;i++){
             TntObjectData[i] = new TntStaticObject;
             TntObjectData[i]->Load(ff);
         };
     #endif
 #endif
         ff.close();
         }
     buf.init();
     buf < "data.vot/" < VLfilenames[1] < ".vlc";
     if(ff.open(GetTargetName(buf.GetBuf()),XS_IN)){
         ff.read(sign,strlen(VLCsign[1]));
         if(memcmp(sign,VLCsign[1],strlen(VLCsign[1]))) ErrH.Abort(errm);
         ff > MLCTableSize;
 #ifdef _SURMAP_
         MLCTable = new MLCloneValoc[MLCTableSize];
         for(i = 0;i < MLCTableSize;i++){
             MLCTable[i].load(ff);
             MLCTable[i].link();
         };
 #else
 #endif
         ff.close();
         }
     buf.init();
     buf < "data.vot/" < VLfilenames[2] < ".vlc";
     if(ff.open(GetTargetName(buf.GetBuf()),XS_IN)){
         ff.read(sign,strlen(VLCsign[2]));
         if(memcmp(sign,VLCsign[2],strlen(VLCsign[2]))) ErrH.Abort(errm);
         ff > SnsTableSize;
 /*#ifndef _NT
         SnsTableSize = 0;
 #endif*/
 #ifdef _SURMAP_
         SnsTable = new SensorValoc[SnsTableSize];
         for(i = 0;i < SnsTableSize;i++){
             SnsTable[i].load(ff);
             SnsTable[i].link();
         };
 #else
 //#ifdef _NT
         SensorObjectData = new SensorDataType*[SnsTableSize];
         for(i = 0;i < SnsTableSize;i++){
             SensorObjectData[i] = new SensorDataType;
             SensorObjectData[i]->CreateSensor(ff,i);
         };
 //------------------------------------------------------------------------------
 /*      XStream fff;
         buf.init();
         buf < "DATA.VOT\\" < VLfilenames[2] < ".VLC";
         fff.open(GetTargetName(buf.GetBuf()),XS_OUT);
         fff.write(sign,strlen(VLCsign[2]));
         fff < SnsTableSize;
         for(i = 0;i < SnsTableSize;i++)
             SensorObjectData[i]->SaveSensor(fff);
         fff.close();*/
 //------------------------------------------------------------------------------
 //#endif
 #endif
         ff.close();
         }
 #ifdef _ROAD_
     NumAddDanger = MaxAddDanger[CurrentWorld];
 #endif
     buf.init();
     buf < "data.vot/" < VLfilenames[3] < ".vlc";
     if(ff.open(GetTargetName(buf.GetBuf()),XS_IN)){
         ff.read(sign,strlen(VLCsign[3]));
         if(memcmp(sign,VLCsign[3],strlen(VLCsign[3]))) ErrH.Abort(errm);
         ff > DngTableSize;
 #ifdef _SURMAP_
         DngTable = new DangerValoc[DngTableSize];
         for(i = 0;i < DngTableSize;i++){
             DngTable[i].load(ff);
             DngTable[i].link();
             }
 #else
         DangerObjectData = new DangerDataType*[DngTableSize + NumAddDanger];
         for(i = 0;i < DngTableSize;i++){
             DangerObjectData[i] = new DangerDataType;
             DangerObjectData[i]->CreateDanger(ff);
         };
         for(i=0; i<NumAddDanger; i++) {
             DangerObjectData[DngTableSize + i] = new DangerDataType;
             DangerObjectData[DngTableSize + i]->R_curr = Vector(0, 0, 0);
         }
         NumAddDanger = DngTableSize;
         DngTableSize += MaxAddDanger[CurrentWorld];
 #endif
         ff.close();
         }
 }
References XErrorHandler::Abort(), XStream::close(), DangerDataType::CreateDanger(), SensorDataType::CreateSensor(), CurrentWorld, DangerObjectData, DngTableSize, ErrH, XBuffer::GetBuf(), GetTargetName(), XBuffer::init(), TntCreature::Load(), MaxAddDanger, MLCTableSize, NumAddDanger, XStream::open(), GeneralObject::R_curr, XStream::read(), SensorObjectData, SnsTableSize, TntObjectData, TntTableSize, VLCsign, VLfilenames, and XS_IN.
Referenced by MLload().
xDestroySpot()
void xDestroySpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
 {
     uchar* pa0,*pf0;
     int i,j;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     uchar t;
     int r;
     int* dx,*dy;
     int rrad;
     int phase,sphase;
     if(!Radius) return;
     for(i = y0 - Radius;i <= y0 + Radius;i++) if(!lt[YCYCL(i)]) return;
     switch(rfactor){
         case 0:
             rrad = 0;
             break;
         case 1:
             rrad = Radius >> 3;
             break;
         case 2:
             rrad = Radius >> 2;
             break;
         case 3:
             rrad = Radius >> 1;
             break;
         case 4:
             rrad = Radius;
             break;
         case 5:
             rrad = Radius << 1;
             break;
         case 6:
             rrad = Radius << 2;
             break;
         case 7:
             rrad = Radius << 3;
             break;
         case 8:
             rrad = Radius << 4;
             break;
     };
     phase = PI / 2;
     sphase = PI / (2 * Radius);
     if(terrain == 83){
         for(i = 0;i < Radius;i++){
             dx = RadiusDestroyX[i];
             dy = RadiusDestroyY[i];
             r = SI[rPI(phase)]*delta >> 16;
             for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
                 if((int)RND(rrad) < Radius - i){
                     rx = XCYCL((*dx) + x0);
                     ry = YCYCL((*dy) + y0);
                     pa0 = lt[ry] + rx;
                     pf0 = pa0 + H_SIZE;
                     if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                         if(*pf0 & DOUBLE_LEVEL){
                             if(rx & 1)
 //                              *pa0 += r;
                                 *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                         }else
 //                          *pa0 += r;
                             *pa0 = AltProtectedTable[(*pa0) + r + ALT_PROTECTED_OFFSET];
                     };
                 };
             };
             phase -= sphase;
         };
     }else{
         t = terrain <<TERRAIN_OFFSET;
         for(i = 0;i < Radius;i++){
             dx = RadiusDestroyX[i];
             dy = RadiusDestroyY[i];
             r = SI[rPI(phase)]*delta >> 16;
             for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
                 if((int)RND(rrad) < Radius - i){
                     rx = XCYCL((*dx) + x0);
                     ry = YCYCL((*dy) + y0);
                     pa0 = lt[ry] + rx;
                     pf0 = pa0 + H_SIZE;
                     if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                         if(*pf0 & DOUBLE_LEVEL){
                             if(rx & 1){
 //                              *pa0 += r;
                                 *pa0 = AltProtectedTable[*pa0 + r + ALT_PROTECTED_OFFSET];
                                 SET_TERRAIN(*pf0,t);
                             };
                         }else{
 //                          *pa0 += r;
                             *pa0 = AltProtectedTable[*pa0 + r + ALT_PROTECTED_OFFSET];
                             SET_TERRAIN(*pf0,t);
                         };
                     };
                 };
             };
             phase -= sphase;
         };
     };
 };
References ALT_PROTECTED_OFFSET, AltProtectedTable, DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, GET_TERRAIN, H_SIZE, NumDestroyRadius, PI, RadiusDestroyX, RadiusDestroyY, RND(), rPI, SET_TERRAIN, SI, SmoothTerrainMask, TERRAIN_OFFSET, vMap, MobileLocation::x0, XCYCL, MobileLocation::y0, and YCYCL.
xRestoreDestroySpot()
void xRestoreDestroySpot (int x0, int y0, int Radius, uchar terrain, int delta, uchar rfactor)
 {
     uchar* pa0,*pf0;
     int i,j;
     uchar** lt = vMap -> lineT;
     int rx,ry;
     int r;
     int* dx,*dy;
     int rrad;
     int phase,sphase;
     if(!Radius) return;
     for(i = y0 - Radius;i <= y0 + Radius;i++) if(!lt[YCYCL(i)]) return;
     switch(rfactor){
         case 0:
             rrad = 0;
             break;
         case 1:
             rrad = Radius >> 3;
             break;
         case 2:
             rrad = Radius >> 2;
             break;
         case 3:
             rrad = Radius >> 1;
             break;
         case 4:
             rrad = Radius;
             break;
         case 5:
             rrad = Radius << 1;
             break;
         case 6:
             rrad = Radius << 2;
             break;
         case 7:
             rrad = Radius << 3;
             break;
         case 8:
             rrad = Radius << 4;
             break;
     };
     phase = PI / 2;
     sphase = PI / (2 * Radius);
     for(i = 0;i < Radius;i++){
         dx = RadiusDestroyX[i];
         dy = RadiusDestroyY[i];
         r = SI[rPI(phase)]*delta >> 16;
         for(j = 0;j < NumDestroyRadius[i];j++,dx++,dy++){
             if((int)RND(rrad) < Radius - i){
                 rx = XCYCL((*dx) + x0);
                 ry = YCYCL((*dy) + y0);
                 pa0 = lt[ry] + rx;
                 pf0 = pa0 + H_SIZE;
                 if(SmoothTerrainMask[GET_TERRAIN(*pf0)]){
                     if(*pf0 & DOUBLE_LEVEL){
                         if(rx & 1)
 //                          *pa0 -= r;
                             *pa0 = AltProtectedTable[(*pa0) - r + ALT_PROTECTED_OFFSET];
                     }else
 //                      *pa0 -= r;
                         *pa0 = AltProtectedTable[(*pa0) - r + ALT_PROTECTED_OFFSET];
                 };
             };
         };
         phase -= sphase;
     };
 };
References ALT_PROTECTED_OFFSET, AltProtectedTable, DOUBLE_LEVEL, MobileLocation::dx, MobileLocation::dy, GET_TERRAIN, H_SIZE, NumDestroyRadius, PI, RadiusDestroyX, RadiusDestroyY, RND(), rPI, SI, SmoothTerrainMask, vMap, MobileLocation::x0, XCYCL, MobileLocation::y0, and YCYCL.
Variable Documentation
DestroyMechosTable
uchar DestroyMechosTable[TERRAIN_MAX] extern
DestroyMoleTable
uchar DestroyMoleTable[TERRAIN_MAX] extern
DngTableSize
int DngTableSize extern
MAX_KEYPHASE
const int MAX_KEYPHASE = 4
MLPREC
const int MLPREC = 16
MLTable
MobileLocation** MLTable extern
Referenced by FindMobileLocation(), MLCheckQuant(), MLload(), MLquant(), MLReset(), and MLsave().
MLTableSize
int MLTableSize extern
Referenced by FindMobileLocation(), MLCheckQuant(), MLload(), MLquant(), MLReset(), and MLsave().
MOBILE_LOCATION_ACTIVE
const char MOBILE_LOCATION_ACTIVE = 1
SnsTableSize
int SnsTableSize extern
Referenced by FindSensor(), GetNearSensor(), VangerUnit::InitEnvironment(), NetworkGetStart(), StaticClose(), StaticOpen(), ValocTableFree(), and VLload().
TntTableSize
int TntTableSize extern
Referenced by BulletObject::Event(), NetworkWorldOpen(), JumpBallObject::Quant(), StaticClose(), StaticOpen(), StaticQuant(), VangerUnit::TerrainQuant(), ValocTableFree(), and VLload().