Vangers: src/sound/music.cpp File Reference
music.cpp File Reference
#include <sstream>
#include "../global.h"
#include "hsound.h"
#include "../../lib/xsound/ogg_stream.h"
Functions
const char * getTrackPathName (int track)
void xsInitMusic (void)
void xsDeInitMusic (void)
void xsPlayMusic (int track, int min=0, int sec=0)
void xsPlayOneTrackMusic (int track, int min=0, int sec=0)
void xsStopMusic (void)
void xsPauseMusic (void)
void xsResumeMusic (void)
int xsGetStatusMusic (void)
int xsGetCurTrackMusic (void)
int xsGetNumTracksMusic (void)
int xsGetTrackLenMusic (int track)
void xsMixerOpenMusic (void)
int xsGetVolumeMusic (void)
void xsSetVolumeMusic (int val)
Variables
clunk::Context context
Function Documentation
getTrackPathName()
const char* getTrackPathName (int track)
{
     switch (track) {
         case ST_INTRO:          //2
             return "resource/music/track02.ogg";
         case ST_FOSTRAL:        //3
             return "resource/music/track03.ogg";
         case ST_GLORX:          //4
             return "resource/music/track04.ogg";
         case ST_NECROSS:        //5
             return "resource/music/track05.ogg";
         case ST_XPLO:           //6
             return "resource/music/track06.ogg";
         case ST_SECRETS:        //7
             return "resource/music/track07.ogg";
         case ST_GAMEOVER:       //8
             return "resource/music/track08.ogg";
         case ST_THEEND:         //9
             return "resource/music/track09.ogg";
         case ST_THEEND_DOUBLE:  //10
             return "resource/music/track10.ogg";
         case ST_DOUBLE:         //11
             return "resource/music/track01.ogg";
         default:
             return "resource/music/track01.ogg";
     }
 }
References ST_DOUBLE, ST_FOSTRAL, ST_GAMEOVER, ST_GLORX, ST_INTRO, ST_NECROSS, ST_SECRETS, ST_THEEND, ST_THEEND_DOUBLE, and ST_XPLO.
xsDeInitMusic()
void xsDeInitMusic (void)
{
 //  music->Stop();
 //  delete music;
     //if (music)
     //  {
         //Mix_FreeMusic(music);
     //  music = NULL;
     //  }
     //MpegDeinitLibrary();
 }
xsGetCurTrackMusic()
int xsGetCurTrackMusic (void)
{
     return curTrack;
 }
xsGetNumTracksMusic()
int xsGetNumTracksMusic (void)
{
     return 0;
 }
xsGetStatusMusic()
int xsGetStatusMusic (void)
{
     /*switch (music->IsPlay()) {
         case MPEG_STOP:
             return XCD_STOPPED;
         case MPEG_PAUSE:
             return XCD_PAUSED;
         case MPEG_PLAY:
             return XCD_PLAYING;
         default:
             return XCD_OTHER;
     }*/
     if (context.playing(-1)) {
         return XCD_PLAYING;
     } else {
         return XCD_STOPPED;
     }
     return XCD_OTHER;
 }
References context, XCD_OTHER, XCD_PLAYING, and XCD_STOPPED.
Referenced by iHandleExtEvent(), and MainMenuSoundQuant().
xsGetTrackLenMusic()
int xsGetTrackLenMusic (int track)
{
     return 0;
 }
xsGetVolumeMusic()
int xsGetVolumeMusic (void)
{
     //return music->GetVolume();
     return volume;
 }
Referenced by iHandleExtEvent(), MainMenuSoundQuant(), and SoundQuant().
xsInitMusic()
void xsInitMusic (void)
{
     //MpegInitLibrary(lpDS);
 //  music = new MpegSound();
 //  music->SetVolume(255);
 }
xsMixerOpenMusic()
void xsMixerOpenMusic (void)
{
 }
xsPauseMusic()
void xsPauseMusic (void)
{
     //music->Pause();
     //Mix_PausedMusic();
     context.pause(-1);
 }
References context.
Referenced by PauseCDTRACK().
xsPlayMusic()
void xsPlayMusic (int track, int min = 0, int sec = 0)
{
     curTrack = track;
     //music->OpenToPlay(getTrackPathName(track));
     //music=Mix_LoadMUS(getTrackPathName(track));
     //Mix_PlayMusic(music, 31);
     //std::cout<<"xsPlayMusic:"<<curTrack<<std::endl;
     context.play(-1, new OggStream(getTrackPathName(track)), true);
     context.set_volume(-1, volume/256.0);
 }
xsPlayOneTrackMusic()
void xsPlayOneTrackMusic (int track, int min = 0, int sec = 0)
{
     curTrack = track;
     //if (music)
     //  {
         //Mix_HaltMusic();
         //Mix_RewindMusic();
         //Mix_FreeMusic(music);
         //music = NULL;
         //}
     //music=Mix_LoadMUS(getTrackPathName(track));
     //Mix_RewindMusic();
     //Mix_PlayMusic(music, 31);
     //music->OpenToPlay(getTrackPathName(track));
     //std::cout<<"xsPlayOneTrackMusic:"<<curTrack<<std::endl;
     if (context.playing(-1))
         context.stop(-1);
     context.play(-1, new OggStream(getTrackPathName(track)), true);
     context.set_volume(-1, volume/256.0);
 }
Referenced by StartCDTRACK(), and StartWTRACK().
xsResumeMusic()
void xsResumeMusic (void)
{
     //music->Resume();
     //Mix_ResumeMusic();
     context.pause(-1);
 }
References context.
Referenced by ResumeCDTRACK().
xsSetVolumeMusic()
void xsSetVolumeMusic (int val)
{
     //std::cout<<"xsSetVolumeMusic:"<<val<<std::endl;
     //music->SetVolume(val);
     float f_val = val;
     f_val/=256;
     //Mix_VolumeMusic(val);
     context.set_volume(-1, f_val);
     volume=val;
 }
References context.
Referenced by iHandleExtEvent().
xsStopMusic()
void xsStopMusic (void)
{
     //music->Stop();
     //Mix_HaltMusic();
     if (context.playing(-1))
         context.stop(-1);
 }
References context.
Referenced by StopCDTRACK().
Variable Documentation
context
clunk::Context context extern
Referenced by SoundFinit(), SoundInit(), SoundLoad(), xsGetStatusMusic(), xsPauseMusic(), xsResumeMusic(), xsSetVolumeMusic(), and xsStopMusic().