Vangers: KDWIN Namespace Reference
KDWIN Namespace Reference
Functions
int create_server (int port)
void destroy_server ()
Function Documentation
create_server()
int KDWIN::create_server (int port)
 {
     if(!XSocketLocalHostADDR.host)
         ErrH.Abort("You have an incompatible network configuration. Please consult Readme.txt on how to configure your network for Vangers multiplayer.");
     avaible_servers.clear_states();
     if(avaible_servers.talk_to_server(ntohl(XSocketLocalHostADDR.host),port,0,1))
         return avaible_servers.size();
     destroy_server(); // if  You've already created server on another port
     XBuffer cmd_line;
     cmd_line < "MP_SERVER\\VangersServer.exe /t900 /i /p" <= port;
 /*  ZeroMemory(&StartUpInfo,sizeof(STARTUPINFO));
     StartUpInfo.cb = sizeof(STARTUPINFO);
     StartUpInfo.dwFlags = STARTF_USESHOWWINDOW;
     StartUpInfo.wShowWindow = SW_HIDE;
      if(CreateProcess(
                     0,  // pointer to name of executable module
                     cmd_line.GetBuf(),  // pointer to command line string
                     0,  // pointer to process security attributes
                     0,  // pointer to thread security attributes
                     0,  // handle inheritance flag
 //zmod
 //                  NORMAL_PRIORITY_CLASS,  // creation flags //zMod
                     HIGH_PRIORITY_CLASS,  // creation flags //zMod
                     0,  // pointer to new environment block
                     0,  // pointer to current directory name
                     &StartUpInfo,   // pointer to STARTUPINFO
                     &ProcessInformation // pointer to PROCESS_INFORMATION
                     )){
         CloseHandle(ProcessInformation.hThread);
         if(avaible_servers.talk_to_server(XSocketLocalHostADDR,port,0,1))
             return avaible_servers.size();
         }
 */
     return 0;
 }
References XErrorHandler::Abort(), avaible_servers, ServersList::clear_states(), destroy_server(), ErrH, XTList< Type >::size(), ServersList::talk_to_server(), and XSocketLocalHostADDR.
Referenced by iCreateServer().
destroy_server()
void KDWIN::destroy_server ()
 {
 /*  HANDLE hProcess = ProcessInformation.hProcess;
     if(hProcess){
 //      TerminateProcess(ProcessInformation.hProcess,0);
         CloseHandle(ProcessInformation.hProcess);
         }
 */}
Referenced by create_server(), and restore().