Vangers: src/network.cpp File Reference
network.cpp File Reference
#include "zmod_client.h"
#include "global.h"
#include "lang.h"
#include "3d/3d_math.h"
#include "sound/hsound.h"
#include <arpa/inet.h>
#include "network.h"
Classes
struct MemTestBlock
Namespaces
KDWIN
Macros
#define CLIENT_VERSION 1
#define SERVER_VERSION 1
#define PLAYER_REMOVAL_EVENT(p) {NetCheckRemovePlayer(p);}
#define IN_EVENTS_LOG(id)
#define IN_EVENTS_LOG1(id, code)
#define OUT_EVENTS_LOG(id)
#define OUT_EVENTS_LOG1(id, code)
#define DOUT(str) { std::cout<<str<<"\n"; }
#define DOUT1(str, code) { std::cout<<str<<", code: "<<code<<"\n"; }
Functions
int KDWIN::create_server (int port)
void KDWIN::destroy_server ()
int identification (XSocket &socket)
int connect_to_server (ServerFindChain *p)
int restore_connection ()
void disconnect_from_server ()
void set_time_by_server (int n_measures)
int set_world (int world, int world_y_size)
void leave_world ()
void total_players_data_list_query ()
void send_player_body (PlayerBody &body)
void network_analysis (XBuffer &out, int integral)
void short_network_analysis (XBuffer &out)
void delay (int msec)
int is_current_server_configured (char *name, ServerData *data, zServerData *zdata)
int send_server_data (char *name, ServerData *data, zServerData *zdata)
void void_network_quant ()
void IncomingChatMessage (void)
int calc_CRC (unsigned char *p, int size)
int test_block (unsigned char *ptr, int size)
Variables
int MP_GAME
XStream fout
int frame
int GlobalExit
int zserver_version = 0
int NetworkON = 0
NetRndType NetRnd
const int IN_BUFFER_SIZE = 128000
const int OUT_BUFFER_SIZE = 256000
int iProxyUsage
char * iProxyServer
int iProxyPort
int non_blocking_mode = 1
int enable_transferring = 0
int enable_send = 1
int average_lag = 0
XQueue< unsigned int > lag_averaging_t0 (32)
int global_clock_tau = 0
unsigned int game_birth_time_offset
double response_time = 0
double time_synchronization_sigma
int n_sended_events
int n_sended_bytes
int n_received_events
int n_received_bytes
int network_clock
int network_frame
int n_sended_events_global
int n_sended_bytes_global
int n_received_events_global
int n_received_bytes_global
int network_clock_global = -1
int network_frame_global
int delay_time
int delay_time_global
int delay_time_counter
int delay_time_counter_global
int now_unsent_size
int global_unsent_size = 0
int set_world_status = 0
XBuffer network_analysis_buffer (10000)
InputEventBuffer events_in (IN_BUFFER_SIZE)
OutputEventBuffer events_out (OUT_BUFFER_SIZE)
ServerData my_server_data
ServersList avaible_servers
zServerData z_my_server_data
zCreateObjectQueue * z_create_object_queue
PlayerBody my_player_body
PlayerData * my_player_data = 0
PlayersList players_list
MessageDispatcher message_dispatcher
XSocket main_socket
ServerFindChain current_server_addr
int number_of_reconnection_attempt = 5
int object_ID_offsets [16]
void * XGR_hWnd
XTList< MemTestBlock > mem_test_list
Macro Definition Documentation
CLIENT_VERSION
#define CLIENT_VERSION 1
DOUT
#define DOUT (str) { std::cout<<str<<"\n"; }
DOUT1
#define DOUT1 (str, code) { std::cout<<str<<", code: "<<code<<"\n"; }
IN_EVENTS_LOG
#define IN_EVENTS_LOG (id)
IN_EVENTS_LOG1
#define IN_EVENTS_LOG1 (id, code)
OUT_EVENTS_LOG
#define OUT_EVENTS_LOG (id)
OUT_EVENTS_LOG1
#define OUT_EVENTS_LOG1 (id, code)
PLAYER_REMOVAL_EVENT
#define PLAYER_REMOVAL_EVENT (p) {NetCheckRemovePlayer(p);}
SERVER_VERSION
#define SERVER_VERSION 1
Function Documentation
calc_CRC()
int calc_CRC (unsigned char * p, int size)
 {
     int VAL = 276859467;
     int sum = 0;
     while(size-- > 0){
         sum += VAL ^ *(p++);
         VAL ^= VAL >> 3;
         VAL ^= VAL << 28;
         VAL &= 0x7FFFFFFF;
         }
     return sum;
 }
Referenced by test_block().
connect_to_server()
int connect_to_server (ServerFindChain * p)
 {
     p->connect(main_socket);
     if(main_socket() && identification(main_socket)){
         current_server_addr = *p;
         events_out.clear();
         events_in.reset();
         events_out.begin_event(ATTACH_TO_GAME);
         events_out < current_server_addr.game_ID;
         events_out.end_body();
         events_out.send(1);
         //std::cout<<"ATTACH_TO_GAME_RESPONSE"<<std::endl;
         events_in.receive_waiting_for_event(ATTACH_TO_GAME_RESPONSE);
         //std::cout<<"[ok]"<<std::endl;
         current_server_addr.game_ID = events_in.get_int();
         current_server_addr.configured = events_in.get_byte();
         game_birth_time_offset = events_in.get_dword();
         GlobalStationID = events_in.get_byte();
         for(int i = 0;i < 16;i++)
             object_ID_offsets[i] = events_in.get_word();
         events_in.ignore_event();
         zGameBirthTime = 0;
         if (zserver_version > 1) {
             //std::cout<<"zTIME_RESPONSE"<<std::endl;
             events_in.receive_waiting_for_event(zTIME_RESPONSE); //ZMOD second network packet
             //std::cout<<"[ok]"<<std::endl;
             zGameBirthTime = events_in.get_int();
             events_in.ignore_event();
         }
         NetworkON = 1;
         number_of_reconnection_attempt = 5;
         return GlobalStationID;
         }
     NetworkON = 0;
     return 0;
 }
References ATTACH_TO_GAME, ATTACH_TO_GAME_RESPONSE, OutputEventBuffer::begin_event(), OutputEventBuffer::clear(), ServerFindChain::configured, ServerFindChain::connect(), current_server_addr, OutputEventBuffer::end_body(), events_in, events_out, game_birth_time_offset, ServerFindChain::game_ID, InputEventBuffer::get_byte(), InputEventBuffer::get_dword(), InputEventBuffer::get_int(), InputEventBuffer::get_word(), GlobalStationID, identification(), InputEventBuffer::ignore_event(), main_socket, NetworkON, number_of_reconnection_attempt, object_ID_offsets, InputEventBuffer::receive_waiting_for_event(), InputEventBuffer::reset(), OutputEventBuffer::send(), zGameBirthTime, zserver_version, and zTIME_RESPONSE.
Referenced by NetInit().
delay()
void delay (int msec)
 {
     START_TIMER(msec);
     while(CHECK_TIMER());
 }
References CHECK_TIMER, and START_TIMER.
Referenced by Object::direct_joystick_control(), Object::direct_keyboard_control(), and disconnect_from_server().
disconnect_from_server()
void disconnect_from_server ()
 {
     events_out.send_simple_query(CLOSE_SOCKET);
     delay(256);
     main_socket.close();
     delay(256);
     events_out.clear();
     events_in.reset();
 }
References OutputEventBuffer::clear(), XSocket::close(), CLOSE_SOCKET, delay(), events_in, events_out, main_socket, InputEventBuffer::reset(), and OutputEventBuffer::send_simple_query().
Referenced by GeneralSystemFree(), and KeyCenter().
identification()
int identification (XSocket & socket)
 {
     char string[256] = "";
     memset(string,0,256);
     unsigned int len,identificated = 0;
     START_TIMER(60*1000);
     const char* request_str = "Vivat Sicher, Rock'n'Roll forever!!!";
     strcpy(string, request_str);
     string[strlen(string) + 1] = CLIENT_VERSION;
     socket.send(string,strlen(string) + 2);
     while(CHECK_TIMER())
         if((len = socket.receive(string, 255, 1000)) != 0 && !strcmp(string,"Enter, my son, please...")){
             if(!SERVER_VERSION || (len > strlen(string) + 1 && string[strlen(string) + 1] == SERVER_VERSION))
                 identificated = 1;
             break;
             }
     if(!identificated) {
         std::cout<<"Network:identificated is wrong! SV:"<<SERVER_VERSION<<" SV2:"<<(int)string[strlen(string)+1]<<std::endl;
         socket.close();
         return 0;
     }
 // zMod fixed ---------------------------------------------------------
     XBuffer zbuffer(10000);
     zbuffer < short(1) < char(SERVER_TIME_QUERY);
     if(!socket.send(zbuffer.GetBuf(),zbuffer.tell()))
         return 0;
     unsigned int z_end_time_ = SDL_GetTicks() + 2*60*1000;
     while (((int)(SDL_GetTicks() - z_end_time_) < 0))
     if (socket.receive(zbuffer.GetBuf(), zbuffer.length(), 1000))
        break;
     unsigned char zevent_ID;
     short zevent_size;
     int zresponse;
     zbuffer.set(0);
     zbuffer > zevent_size > zevent_ID > zresponse;
     if(zevent_ID == SERVER_TIME)
         zserver_version = 1;
     //std::cout<<"Client auth: "<<(int)zevent_ID<<" "<<zSERVER_VERSION_RESPONSE<<" "<<(int)zresponse<<" "<<zCLIENT_VERSION<<std::endl;
     if (zevent_ID == zSERVER_VERSION_RESPONSE) {
         if (zCLIENT_VERSION == zresponse) {
             zserver_version = zresponse;
         } else {
         //NEED SEE!
         //    ErrH.Abort(zSTR_WRONG_VERSION);
          //   return 0;
         }
     }
 // /zMod ---------------------------------------------------------
     return 1;
 }
References CHECK_TIMER, CLIENT_VERSION, XSocket::close(), XBuffer::GetBuf(), XBuffer::length(), XSocket::receive(), XSocket::send(), SERVER_TIME, SERVER_TIME_QUERY, SERVER_VERSION, XBuffer::set(), START_TIMER, XBuffer::tell(), zCLIENT_VERSION, zserver_version, and zSERVER_VERSION_RESPONSE.
Referenced by connect_to_server(), and ServersList::talk_to_server().
IncomingChatMessage()
void IncomingChatMessage (void)
 {
     if(!iChatON)
         aiMessageQueue.Send(AI_MESSAGE_INCOMING_MESSAGE,0,0xff,0);
 };
References AI_MESSAGE_INCOMING_MESSAGE, aiMessageQueue, iChatON, and aiMessageList::Send().
is_current_server_configured()
int is_current_server_configured (char * name, ServerData * data, zServerData * zdata)
 {
     if(current_server_addr.configured){
         events_out.send_simple_query(GET_GAME_DATA);
         if(events_in.receive_waiting_for_event(GAME_DATA_RESPONSE)){
             if(events_in.current_body_size()){
                 events_in > name;
                 events_in.read(data,sizeof(ServerData));
                 MP_GAME = data -> GameType;
                 events_in.ignore_event();
                 //---------------------------zMod fixed net packet zGAME_DATA_RESPONSE
                 if (zserver_version>1) {
                     if (events_in.receive_waiting_for_event(zGAME_DATA_RESPONSE)) {
                         if(events_in.current_body_size()) {
                             zdata->mod_id = events_in.get_byte();
                             events_in.ignore_event();
                             return 1;
                         }
                         events_in.ignore_event();
                         return 0;
                     }
                 }
                 //---------------------------zMod net packet zGAME_DATA_RESPONSE
                 return 1;
             }
             events_in.ignore_event();
             return 0;
             }
         }
     return 0;
 }
References ServerFindChain::configured, InputEventBuffer::current_body_size(), current_server_addr, events_in, events_out, GAME_DATA_RESPONSE, InputEventBuffer::get_byte(), GET_GAME_DATA, InputEventBuffer::ignore_event(), zServerData::mod_id, MP_GAME, XBuffer::read(), InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send_simple_query(), zGAME_DATA_RESPONSE, and zserver_version.
leave_world()
void leave_world ()
 {
     events_out.send_simple_query(LEAVE_WORLD);
     enable_transferring = 0;
 }
References enable_transferring, events_out, LEAVE_WORLD, and OutputEventBuffer::send_simple_query().
Referenced by NetworkWorldClose().
network_analysis()
void network_analysis (XBuffer & out, int integral)
 {
     out.init();
     out.SetDigits(3);
     out < "Network's Statistics\n";
     out < (!non_blocking_mode ? "Blocking send()\n" :  "Non-blocking send()\n");
 #ifdef EVENTS_LOG
     out < "Net events is being logged\n";
 #endif
     out < "Set world status: " <= set_world_status < "\n";
     out < "Players:\n";
     PlayerData* p = players_list.first();
     while(p){
         out <= p -> client_ID < "\ts:" <= p -> status < "\tw:" <= p -> world < "\tx:" <= p -> x < "\ty:" <= p -> y < "\tk:" <= p -> body.kills < "\td:" <= p -> body.deaths < "\t";
         if(p -> name)
             out < p -> name < "\t";
         out < "\n";
         p = p -> next;
         }
     out < "Chat:\n";
     MessageElement* pm = message_dispatcher.last();
     while(pm){
         out < pm -> message < "\n";
         if(pm == message_dispatcher.first())
             break;
         pm = (MessageElement*)pm -> prev;
         }
     if(!integral){
         double dt = (double)(SDL_GetTicks() - (int)network_clock)/1000;
         double df = frame - network_frame;
         out < "Rate: " <= df/dt < " FPS\n";
         out < "Time synchronization, lag: " <= response_time < " Sec,  Sigma: " <= time_synchronization_sigma < " Sec\n";
         //out < "Average lag of events (C->S->C): " <= (double)delay_time/(delay_time_counter*256) < " Sec\n";
         out < "Average lag of events (C->S->C): " <= average_lag < " mSec\n";
         out < "Send:  " <= round(n_sended_events/dt) < " EPS,  " <= round(n_sended_bytes/dt) < " BPS,  " <= round(n_sended_events/df) < " EPF,  " <= round(n_sended_bytes/df) < " BPF\n";
         out < "Receive: " <= round(n_received_events/dt) < " EPS,  " <= round(n_received_bytes/dt) < " BPS,  " <= round(n_received_events/df) < " EPF,  " <= round(n_received_bytes/df) < " BPF\n";
         out < "Total send: " <= n_sended_bytes_global < "\n";
         out < "Total receive: " <= n_received_bytes_global < "\n";
         if(now_unsent_size)
             out < "Unsent size: " <= now_unsent_size < "\n";
         network_clock = SDL_GetTicks();
         network_frame = frame;
         n_sended_events_global += n_sended_events;
         n_sended_bytes_global += n_sended_bytes;
         n_received_events_global += n_received_events;
         n_received_bytes_global += n_received_bytes;
         delay_time_global += delay_time;
         delay_time_counter_global += delay_time_counter;
         if(global_unsent_size < now_unsent_size)
             global_unsent_size = now_unsent_size;
         now_unsent_size = n_sended_events = n_sended_bytes = n_received_events = n_received_bytes = delay_time = delay_time_counter = 0;
         }
     else{
         out < "Frames: "        <= frame < "\n";
         out < "Time: " <= (double)GLOBAL_CLOCK()/256. < " sec\n";
         double dt = (double)(SDL_GetTicks() - (int)network_clock_global)/1000;
         double df = frame - network_frame_global;
         out < "Rate: " <= df/dt < " FPS\n";
         out < "Time synchronization, lag: " <= response_time < " Sec,  Sigma: " <= time_synchronization_sigma < " Sec\n";
         //out < "Average delay of events (C->S->C): " <= (double)delay_time_global/(delay_time_counter_global*256) < " Sec\n";
         out < "Average lag of events (C->S->C): " <= average_lag < " mSec\n";
         out < "Send:   " <= n_sended_events_global/dt < " EPS,  " <= n_sended_bytes_global/dt < " BPS,  " <= n_sended_events_global/df < " EPF,  " <= n_sended_bytes_global/df < " BPF\n";
         out < "Receive: " <= n_received_events_global/dt < " EPS,  " <= n_received_bytes_global/dt < " BPS,  " <= n_received_events_global/df < " EPF,  " <= n_received_bytes_global/df < " BPF\n";
         if(global_unsent_size)
             out < "Global unsent size: " <= global_unsent_size < "\n";
         }
 //zmod
     out < "\n";
     out < "zTime: " <= z_time < " / " <= z_time_avg < "\n";
 //#ifdef ZMOD_BETA
 //  out < "zCycle       : " <= zMod_cycle < "\n";
 //  out < "zFlood       : " <= zMod_flood_level_delta < "\n";
 //  out < "zBirthTime   : " <= zGameBirthTime < "\n";
 //  out < "InitialRND   : " <= (unsigned int)my_server_data.InitialRND < "\n";
 //#endif
     if(network_clock_global == -1){
         network_clock_global = SDL_GetTicks();
         network_frame_global = frame;
         n_sended_events_global = n_sended_bytes_global = n_received_events_global = n_received_bytes_global = delay_time_global = 0;
         }
 }
References XTList< Type >::first(), XBuffer::init(), non_blocking_mode, players_list, set_world_status, and XBuffer::SetDigits().
Referenced by GameQuantRTO::Quant(), and restore().
restore_connection()
int restore_connection ()
 {
     if(main_socket())
         return 1;
     //std::cout<<"restore_connection:Connection lost"<<std::endl;
     DOUT("Connection lost");
     current_server_addr.connect(main_socket);
     if(!main_socket){
         if(number_of_reconnection_attempt-- <= 0)
             if (lang() == RUSSIAN) {
                 ErrH.Abort("     ");
             } else {
                 ErrH.Abort("Unable to restore connection to Server");
             }
         return 0;
     }
     number_of_reconnection_attempt = 5;
     events_out.clear();
     events_in.reset();
     events_out.begin_event(RESTORE_CONNECTION);
     events_out < current_server_addr.game_ID < (unsigned char)GlobalStationID;
     events_out.end_body();
     events_out.send(1);
     events_in.receive_waiting_for_event(RESTORE_CONNECTION_RESPONSE);
     int resp = events_in.get_byte();
     events_in.ignore_event();
     DOUT1("Connection restore",resp);
     return resp;
 }
References XErrorHandler::Abort(), OutputEventBuffer::begin_event(), OutputEventBuffer::clear(), ServerFindChain::connect(), current_server_addr, DOUT, DOUT1, OutputEventBuffer::end_body(), ErrH, events_in, events_out, ServerFindChain::game_ID, InputEventBuffer::get_byte(), GlobalStationID, InputEventBuffer::ignore_event(), lang(), main_socket, number_of_reconnection_attempt, InputEventBuffer::receive_waiting_for_event(), InputEventBuffer::reset(), RESTORE_CONNECTION, RESTORE_CONNECTION_RESPONSE, RUSSIAN, and OutputEventBuffer::send().
Referenced by InputEventBuffer::receive().
send_player_body()
void send_player_body (PlayerBody & body)
 {
     if(my_player_data)
         my_player_data -> body = body;
     events_out.set_player_body(body);
     events_out.send(1);
 }
References events_out, my_player_data, OutputEventBuffer::send(), and OutputEventBuffer::set_player_body().
Referenced by VangerUnit::ChangeVangerProcess(), ActionDispatcher::Close(), VangerUnit::Destroy(), GunSlot::Fire(), uvsVanger::get_shop(), VangerUnit::NetCreateVanger(), NetInit(), uvsVanger::prepare_diagen_statistic(), GloryPlace::Quant(), VangerUnit::ShellNetEvent(), and InsectUnit::Touch().
send_server_data()
int send_server_data (char * name, ServerData * data, zServerData * zdata)
 {
     MP_GAME = data -> GameType;
     if(current_server_addr.configured){
         events_out.send_simple_query(GET_GAME_DATA);
         if(events_in.receive_waiting_for_event(GAME_DATA_RESPONSE)){
             if(events_in.current_body_size()){
                 events_in > name;
                 events_in.read(data,sizeof(ServerData));
                 MP_GAME = data -> GameType;
                 events_in.ignore_event();
                 //---------------------------zMod fixed net packet zGAME_DATA_RESPONSE
                 if (zserver_version>1) {
                     if (events_in.receive_waiting_for_event(zGAME_DATA_RESPONSE)) {
                         if(events_in.current_body_size()) {
                             zdata->mod_id = events_in.get_byte();
                             events_in.ignore_event();
                             return 1;
                         }
                         events_in.ignore_event();
                         return 0;
                     }
                 }
                 //---------------------------zMod net packet zGAME_DATA_RESPONSE
                 return 0;//zmod - MAYBE NOT NEEDED
                 }
             events_in.ignore_event();
             }
         return 0;
         }
     events_out.begin_server_data();
     events_out < name < char(0);
     events_out.write(data,sizeof(ServerData));
     events_out.end_body();
     events_out.send_simple_query(GET_GAME_DATA);
     if(!events_in.receive_waiting_for_event(GAME_DATA_RESPONSE) || !events_in.current_body_size())
         ErrH.Abort("Network error: unable to configure server");
     char name_tmp[256];
     ServerData data_tmp;
     events_in > name_tmp;
     events_in.read(&data_tmp,sizeof(ServerData));
     events_in.ignore_event();
     //---------------------------zMod fixed net packet zGAME_DATA_RESPONSE
     if (zserver_version>1) {
         if(!events_in.receive_waiting_for_event(zGAME_DATA_RESPONSE) || !events_in.current_body_size())
             ErrH.Abort("Network error: unable to configure server");
         zdata->mod_id = events_in.get_byte();
         events_in.ignore_event();
     }
     //---------------------------zMod net packet zGAME_DATA_RESPONSE
     current_server_addr.configured = 1;
     if(strcmp(name,name_tmp) || memcmp(data,&data_tmp,sizeof(ServerData))){
         strcpy(name,name_tmp);
         memcpy(data,&data_tmp,sizeof(ServerData));
         return 0;
         }
     return 1;
 }
References XErrorHandler::Abort(), OutputEventBuffer::begin_server_data(), ServerFindChain::configured, InputEventBuffer::current_body_size(), current_server_addr, OutputEventBuffer::end_body(), ErrH, events_in, events_out, GAME_DATA_RESPONSE, InputEventBuffer::get_byte(), GET_GAME_DATA, InputEventBuffer::ignore_event(), zServerData::mod_id, MP_GAME, XBuffer::read(), InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send_simple_query(), XBuffer::write(), zGAME_DATA_RESPONSE, and zserver_version.
set_time_by_server()
void set_time_by_server (int n_measures)
 {
     int i;
     int t0,T1,t2;
     double tau = 0;
     double dtau,dtau2 = 0;
     for(i = 0;i < n_measures;i++){
         //zmod
         z_time_init();
         events_out.send_simple_query(SERVER_TIME_QUERY);
         events_in.receive_waiting_for_event(SERVER_TIME);
         t0 = events_in.current_time();
         events_in.ignore_event();
         T1 = GLOBAL_CLOCK();
         //zmod
         z_time_init();
         events_out.send_simple_query(SERVER_TIME_QUERY);
         events_in.receive_waiting_for_event(SERVER_TIME);
         t2 = events_in.current_time();
         events_in.ignore_event();
         dtau = T1 - (t2 + t0)/2;
         tau += dtau;
         dtau2 += sqr(dtau);
         response_time += t2 - t0;
         }
     double N = n_measures;
     global_clock_tau += round(tau /= N);
     response_time /= N*256.;
     average_lag = round(response_time*1000);
     time_synchronization_sigma = sqrt((dtau2 - N*sqr(tau))/N/(N-1))/256.;
     std::cout<<"set_time_by_server time_synchronization_sigma:"<<time_synchronization_sigma
              <<" average_lag:"<<average_lag<<" t2:"<<t2<<std::endl;
 }
References average_lag, InputEventBuffer::current_time(), events_in, events_out, GLOBAL_CLOCK, global_clock_tau, InputEventBuffer::ignore_event(), InputEventBuffer::receive_waiting_for_event(), response_time, round(), OutputEventBuffer::send_simple_query(), SERVER_TIME, SERVER_TIME_QUERY, sqr(), time_synchronization_sigma, and z_time_init().
Referenced by NetInit().
set_world()
int set_world (int world, int world_y_size)
 {
     events_out.set_world(world,world_y_size);
     events_out.send(1);
     events_in.receive_waiting_for_event(SET_WORLD_RESPONSE);
     events_in.get_byte(); //resp_world
     int resp_status = events_in.get_byte();
     events_in.ignore_event();
     set_world_status = resp_status;
     enable_transferring = 1;
     lag_averaging_t0.clear();
     return resp_status;
 }
References enable_transferring, events_in, events_out, InputEventBuffer::get_byte(), InputEventBuffer::ignore_event(), lag_averaging_t0, InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send(), OutputEventBuffer::set_world(), SET_WORLD_RESPONSE, and set_world_status.
Referenced by NetworkWorldOpen().
short_network_analysis()
void short_network_analysis (XBuffer & out)
 {
     out.init();
     out.SetDigits(3);
     out < "Network's Statistics\n";
     out < "Time synchronization lag: " <= response_time < " Sec\n";
     out < "Time synchronization sigma: " <= time_synchronization_sigma < " Sec\n";
     double dt = (double)(SDL_GetTicks() - (int)network_clock)/1000;
     double df = frame - network_frame;
     out < (main_socket() ? "Connection ok\n" : "Connection lost\n");
     out < "Rate: " <= df/dt < " FPS\n";
     //if(delay_time_counter)
     //out < "Average lag of events (C->S->C): " <= (double)delay_time/(delay_time_counter*256) < " Sec\n";
     out < "Average lag of events (C->S->C): " <= average_lag < " mSec\n";
     out < "Send:  " <= round(n_sended_bytes/dt) < " BPS\n";
     out < "Receive: " <= round(n_received_bytes/dt) < " BPS\n";
     out < "Total send: " <= n_sended_bytes_global < "\n";
     out < "Total receive: " <= n_received_bytes_global < "\n";
     if(now_unsent_size)
         out < "Unsent size: " <= now_unsent_size < "\n";
 //zmod
     out < "\n";
     out < "zTime: " <= z_time < " / " <= z_time_avg < "\n";
 //#ifdef ZMOD_BETA
 //  out < "zCycle       : " <= zMod_cycle < "\n";
 //  out < "zFlood       : " <= zMod_flood_level_delta < "\n";
 //  out < "zBirthTime   : " <= zGameBirthTime < "\n";
 //  out < "InitialRND   : " <= (unsigned int)my_server_data.InitialRND < "\n";
 //#endif
     network_clock = SDL_GetTicks();
     network_frame = frame;
     n_sended_events_global += n_sended_events;
     n_sended_bytes_global += n_sended_bytes;
     n_received_events_global += n_received_events;
     n_received_bytes_global += n_received_bytes;
     delay_time_global += delay_time;
     delay_time_counter_global += delay_time_counter;
     if(global_unsent_size < now_unsent_size)
         global_unsent_size = now_unsent_size;
     now_unsent_size = n_sended_events = n_sended_bytes = n_received_events = n_received_bytes = delay_time = delay_time_counter = 0;
     if(network_clock_global == -1){
         network_clock_global = SDL_GetTicks();
         network_frame_global = frame;
         n_sended_events_global = n_sended_bytes_global = n_received_events_global = n_received_bytes_global = delay_time_global = 0;
         }
 }
References average_lag, delay_time, delay_time_counter, delay_time_counter_global, delay_time_global, frame, global_unsent_size, XBuffer::init(), main_socket, n_received_bytes, n_received_bytes_global, n_received_events, n_received_events_global, n_sended_bytes, n_sended_bytes_global, n_sended_events, n_sended_events_global, network_clock, network_clock_global, network_frame, network_frame_global, now_unsent_size, response_time, round(), XBuffer::SetDigits(), time_synchronization_sigma, z_time, and z_time_avg.
Referenced by GameQuantRTO::Quant().
test_block()
int test_block (unsigned char * ptr, int size)
 {
     int CRC = calc_CRC(ptr,size);
     MemTestBlock* p = mem_test_list.first();
     while(p){
         if(ptr == p -> ptr && size == p -> size)
             return CRC != p -> CRC;
         p = p -> next;
         }
     mem_test_list.append(new MemTestBlock(ptr,size,CRC));
     return 0;
 }
References calc_CRC(), XTList< Type >::first(), and mem_test_list.
total_players_data_list_query()
void total_players_data_list_query ()
 {
     events_out.send_simple_query(TOTAL_PLAYERS_DATA_QUERY);
     events_in.receive_waiting_for_event(TOTAL_LIST_OF_PLAYERS_DATA);
     players_list.parsing_total_body_query();
     events_in.ignore_event();
 }
References events_in, events_out, InputEventBuffer::ignore_event(), PlayersList::parsing_total_body_query(), players_list, InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send_simple_query(), TOTAL_LIST_OF_PLAYERS_DATA, and TOTAL_PLAYERS_DATA_QUERY.
Referenced by GeneralSystemFree(), and NetInit().
void_network_quant()
void void_network_quant ()
 {
     events_in.receive();
     while(events_in.current_event()) {
         events_in.ignore_event();
         events_in.next_event();
     }
 }
References InputEventBuffer::current_event(), events_in, InputEventBuffer::ignore_event(), InputEventBuffer::next_event(), and InputEventBuffer::receive().
Variable Documentation
avaible_servers
ServersList avaible_servers
Referenced by KDWIN::create_server(), iCreateServer(), iHandleExtEvent(), iUpdateServersList(), and xtInitApplication().
average_lag
int average_lag = 0
Referenced by VangerUnit::Quant(), set_time_by_server(), and short_network_analysis().
current_server_addr
ServerFindChain current_server_addr
Referenced by connect_to_server(), is_current_server_configured(), restore_connection(), and send_server_data().
delay_time
int delay_time
Referenced by short_network_analysis().
delay_time_counter
int delay_time_counter
Referenced by short_network_analysis().
delay_time_counter_global
int delay_time_counter_global
Referenced by short_network_analysis().
delay_time_global
int delay_time_global
Referenced by short_network_analysis().
enable_send
int enable_send = 1
Referenced by InputEventBuffer::receive().
enable_transferring
int enable_transferring = 0
Referenced by leave_world(), and set_world().
events_in
InputEventBuffer events_in(IN_BUFFER_SIZE)
Referenced by connect_to_server(), disconnect_from_server(), is_current_server_configured(), Object::NetEvent(), PlayersList::parsing_total_body_query(), MessageDispatcher::receive(), restore_connection(), send_server_data(), set_time_by_server(), set_world(), PlayersList::single_parsing(), TopList::TopList(), total_players_data_list_query(), and void_network_quant().
events_out
OutputEventBuffer events_out(OUT_BUFFER_SIZE)
Referenced by connect_to_server(), disconnect_from_server(), is_current_server_configured(), leave_world(), restore_connection(), MessageDispatcher::send(), Object::Send(), send_player_body(), send_server_data(), VangerUnit::SendCameraData(), set_time_by_server(), set_world(), TopList::TopList(), and total_players_data_list_query().
fout
XStream fout extern
Referenced by InputEventBuffer::receive(), and OutputEventBuffer::send().
frame
int frame extern
Referenced by short_network_analysis().
game_birth_time_offset
unsigned int game_birth_time_offset
Referenced by connect_to_server().
global_clock_tau
int global_clock_tau = 0
Referenced by set_time_by_server().
global_unsent_size
int global_unsent_size = 0
Referenced by short_network_analysis().
GlobalExit
int GlobalExit extern
Referenced by Player::identification(), Server::quant(), and KDsPlus::Quant().
IN_BUFFER_SIZE
const int IN_BUFFER_SIZE = 128000
iProxyPort
int iProxyPort extern
iProxyServer
char* iProxyServer extern
Referenced by ComlineAnalyze().
iProxyUsage
int iProxyUsage extern
lag_averaging_t0
XQueue<unsigned int> lag_averaging_t0(32)
Referenced by VangerUnit::Quant(), and set_world().
main_socket
XSocket main_socket
Referenced by connect_to_server(), disconnect_from_server(), restore_connection(), and short_network_analysis().
mem_test_list
XTList<MemTestBlock> mem_test_list
Referenced by test_block().
message_dispatcher
MessageDispatcher message_dispatcher
Referenced by iGameMap::draw(), iChatClearLog(), iChatInputFlush(), and iInitChatScreen().
MP_GAME
int MP_GAME extern
Referenced by is_current_server_configured(), and send_server_data().
my_player_body
PlayerBody my_player_body
Referenced by VangerUnit::ChangeVangerProcess(), ActionDispatcher::Close(), VangerUnit::Destroy(), GunSlot::Fire(), uvsVanger::get_shop(), VangerUnit::NetCreateVanger(), NetInit(), NetStatisticInit(), NetStatisticUpdate(), uvsVanger::prepare_diagen_statistic(), GloryPlace::Quant(), MessageDispatcher::send(), VangerUnit::ShellNetEvent(), and InsectUnit::Touch().
my_player_data
PlayerData* my_player_data = 0
Referenced by PlayersList::parsing_total_body_query(), and send_player_body().
my_server_data
ServerData my_server_data
Referenced by aciShowFrags(), VangerUnit::BulletCollision(), CreatePhantomTarget(), VangerUnit::Destroy(), VangerUnit::DestroyCollision(), GeneralSystemClose(), GeneralSystemFree(), uvsVanger::get_shop(), iGetMultiGameParameters(), iSetMultiGameParameters(), NetCheckRemovePlayer(), NetStatisticInit(), NetStatisticUpdate(), NetworkWorldOpen(), uvsVanger::prepare_diagen_statistic(), GameObjectDispatcher::Quant(), VangerUnit::Quant(), ActionDispatcher::Quant(), VangerUnit::SensorQuant(), and VangerUnit::ShellNetEvent().
n_received_bytes
int n_received_bytes
Referenced by InputEventBuffer::receive(), and short_network_analysis().
n_received_bytes_global
int n_received_bytes_global
Referenced by short_network_analysis().
n_received_events
int n_received_events
Referenced by short_network_analysis().
n_received_events_global
int n_received_events_global
Referenced by short_network_analysis().
n_sended_bytes
int n_sended_bytes
Referenced by OutputEventBuffer::send(), and short_network_analysis().
n_sended_bytes_global
int n_sended_bytes_global
Referenced by short_network_analysis().
n_sended_events
int n_sended_events
Referenced by OutputEventBuffer::send(), and short_network_analysis().
n_sended_events_global
int n_sended_events_global
Referenced by short_network_analysis().
NetRnd
NetRndType NetRnd
Referenced by HordeList::Init(), HordeSourceList::Init(), and FishWarriorList::Init().
network_analysis_buffer
XBuffer network_analysis_buffer(10000)
Referenced by iGameMap::draw(), GameQuantRTO::Quant(), and restore().
network_clock
int network_clock
Referenced by short_network_analysis().
network_clock_global
int network_clock_global = -1
Referenced by short_network_analysis().
network_frame
int network_frame
Referenced by short_network_analysis().
network_frame_global
int network_frame_global
Referenced by short_network_analysis().
NetworkON
int NetworkON = 0
Referenced by aciAutoSave(), aciCHandler(), aciShowFrags(), acsQuant(), uvsEscave::add_goods_to_shop(), uvsSpot::add_goods_to_shop(), VangerUnit::AddFree(), VangerUnit::AddPassage(), addVanger(), uvsBunch::begin_harvest(), VangerUnit::BulletCollision(), calc_view_factors(), VangerUnit::ChangeVangerProcess(), ItemsDispatcher::Close(), ActionDispatcher::Close(), GunSlot::CloseGun(), GunSlot::CloseSlot(), connect_to_server(), DangerDataType::CreateDanger(), StuffObject::CreateDevice(), StuffObject::CreateStuff(), VangerUnit::CreateVangerUnit(), VangerUnit::Destroy(), VangerUnit::DestroyCollision(), VangerUnit::DestroyItem(), StuffObject::DeviceIn(), GunDevice::DeviceIn(), StuffObject::DeviceOut(), VangerUnit::DischargeItem(), iGameMap::draw(), GameObjectDispatcher::DrawQuant(), VangerUnit::DrawQuant(), GunSlot::Fire(), DangerDataType::FireWork(), actIntDispatcher::flush(), ActionDispatcher::FunctionQuant(), GeneralSystemClose(), GeneralSystemFree(), GeneralSystemInit(), GeneralSystemOpen(), uvsVanger::get_shop(), getObjectPosition(), VangerUnit::Go2Universe(), iHandleExtEvent(), actIntDispatcher::iKeyTrap(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), VangerUnit::InitAI(), VangerUnit::InitEnvironment(), iPreInitFirst(), iQuantFirst(), VangerUnit::ItemQuant(), actIntDispatcher::KeyQuant(), vrtMap::linkC(), TntCreature::Load(), LoadVPR(), NetInit(), NetworkQuant(), VangerUnit::NewKeyHandler(), ObjectDestroy(), ItemsDispatcher::Open(), LocationEngine::Open(), DoorEngine::Open(), TiristorEngine::Open(), GunSlot::OpenGun(), GunSlot::OpenSlot(), VangerUnit::OutCarNator(), uvsVanger::prepare_diagen_statistic(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), ActionDispatcher::PromptChangeCycle(), ActionDispatcher::PromptQuant(), aciScreenDispatcher::Quant(), aciPromptData::quant(), GameQuantRTO::Quant(), GameObjectDispatcher::Quant(), StuffObject::Quant(), FishWarrior::Quant(), ItemsDispatcher::Quant(), VangerUnit::Quant(), VangerFunctionType::Quant(), ActionDispatcher::Quant(), DoorEngine::Quant(), TiristorEngine::Quant(), DangerDataType::Quant(), uvsBunch::Quant(), ResortEnter(), VangerUnit::SensorQuant(), uvsVanger::shiftOrders(), ShowDominanceMessage(), ShowLuckMessage(), ShowTaskMessage(), StaticQuant(), VangerUnit::test_objects_collision(), FishWarrior::Touch(), VangerUnit::Touch(), InsectUnit::Touch(), TntCreature::Touch(), uvsQuant(), uvsRestoreVanger(), uvsWorldReload(), and vMapPrepare().
non_blocking_mode
int non_blocking_mode = 1
Referenced by network_analysis().
now_unsent_size
int now_unsent_size
Referenced by OutputEventBuffer::send(), and short_network_analysis().
number_of_reconnection_attempt
int number_of_reconnection_attempt = 5
Referenced by connect_to_server(), and restore_connection().
object_ID_offsets
int object_ID_offsets[16]
Referenced by connect_to_server(), and NetInit().
OUT_BUFFER_SIZE
const int OUT_BUFFER_SIZE = 256000
players_list
PlayersList players_list
Referenced by aciShowFrags(), CheckPlayerList(), VangerUnit::DrawQuant(), iChatMouseHandler(), iInitChatButtons(), iInitChatScreen(), iSortPlayers(), NetSlotEvent(), network_analysis(), CompasObject::Quant(), ActionDispatcher::Quant(), MessageDispatcher::receive(), MessageDispatcher::send(), and total_players_data_list_query().
response_time
double response_time = 0
Referenced by set_time_by_server(), and short_network_analysis().
set_world_status
int set_world_status = 0
Referenced by network_analysis(), and set_world().
time_synchronization_sigma
double time_synchronization_sigma
Referenced by set_time_by_server(), and short_network_analysis().
XGR_hWnd
void* XGR_hWnd extern
Referenced by XGR_Screen::finit(), xtGet_hWnd(), and xtSet_hWnd().
z_create_object_queue
zCreateObjectQueue* z_create_object_queue
z_my_server_data
zServerData z_my_server_data
Referenced by GloryPlace::Init(), and FishWarriorList::Init().
zserver_version
int zserver_version = 0
Referenced by connect_to_server(), identification(), is_current_server_configured(), and send_server_data().