Vangers: src/network.h File Reference
network.h File Reference
#include "zmod_client.h"
#include "xsocket.h"
#include "multiplayer.h"
Classes
struct ServerFindChain
struct ServersList
struct PlayerData
struct PlayersList
struct MessageElement
struct MessageDispatcher
struct RatingData
struct TopList
class OutputEventBuffer
class InputEventBuffer
struct NetRndType
Namespaces
KDWIN
Macros
#define DEFAULT_SERVER_PORT 2197
#define CLOCK() (SDL_GetTicks()*18/1000)
#define GLOBAL_CLOCK() (round(SDL_GetTicks()*(256./1000)) - global_clock_tau)
#define LOCAL_CLOCK() (round(SDL_GetTicks()*(256./1000)))
#define age_of_current_game() (((int)GLOBAL_CLOCK() - (int)game_birth_time_offset) >> 8)
#define START_TIMER(interval) unsigned int _end_time_ = SDL_GetTicks() + interval;
#define CHECK_TIMER() ((int)(SDL_GetTicks() - _end_time_) < 0)
#define IS_FUTURE(time) ((int)((time) - SDL_GetTicks()) > 0)
#define IS_PAST(time) ((int)(SDL_GetTicks() - (time)) > 0)
#define CREATE_NET_ID(d) ((++LocalStationCounter[(d & (~(1 << 31))) >> 16] & 0xffff) | d | LocalNetEnvironment)
#define CREATE_STUFF_NET_ID(d) (((++LocalStationCounter[(d & (~(1 << 31))) >> 16] + stuff_ID_offsets) & 0xffff) | d | LocalNetEnvironment)
#define GET_NETWORK_ID(d) (d & ((63 << 16) | (1 << 31)))
#define GET_COUNTER_INDEX(d) ((d & (~(1 << 31))) >> 16)
Enumerations
enum {
UNCONFIGURED = -1, VAN_WAR, MECHOSOMA, PASSEMBLOSS,
NUMBER_MP_GAMES, HUNTAGE, MUSTODONT, DRAW_DEFAULT,
DRAW_LINE, DRAW_FLAT, DRAW_GOURAUD, SET_3D_DIRECT_PLACE = 1,
SET_3D_CONST_Z = 2, SET_3D_TO_THE_LOWER_LEVEL = 4, SET_3D_TO_THE_UPPER_LEVEL = 8, SET_3D_CHOOSE_LEVEL = 16,
UNCONFIGURED = -1, VAN_WAR, MECHOSOMA, PASSEMBLOSS,
NUMBER_MP_GAMES, HUNTAGE, MUSTODONT, MESSAGE_FOR_ALL,
MESSAGE_FOR_TEAM, MESSAGE_FOR_PLAYER, EXPLOSION_64x64 = 0, EXPLOSION_16x16,
VK_BUTTON_1 = VK_BUTTON + 1, VK_BUTTON_2, VK_BUTTON_3, VK_BUTTON_4,
VK_BUTTON_5, VK_BUTTON_6, VK_BUTTON_7, VK_BUTTON_8,
VK_BUTTON_9, VK_BUTTON_10, VK_BUTTON_11, VK_BUTTON_12,
VK_BUTTON_13, VK_BUTTON_14, VK_BUTTON_15, VK_BUTTON_16,
VK_BUTTON_17, VK_BUTTON_18, VK_BUTTON_19, VK_BUTTON_20,
VK_BUTTON_21, VK_BUTTON_22, VK_BUTTON_23, VK_BUTTON_24,
VK_BUTTON_25, VK_BUTTON_26, VK_BUTTON_27, VK_BUTTON_28,
VK_BUTTON_29, VK_BUTTON_30, VK_BUTTON_31, VK_BUTTON_32,
VK_STICK_SWITCH_1 = VK_STICK_SWITCH + 1, VK_STICK_SWITCH_2, VK_STICK_SWITCH_3, VK_STICK_SWITCH_4,
VK_STICK_SWITCH_5, VK_STICK_SWITCH_6, VK_STICK_SWITCH_7, VK_STICK_SWITCH_8,
VK_STICK_SWITCH_9
}
enum {
LastMoggy, QueenFrog, Sandoll, LawnMower,
Wormaster, LastMoggy, QueenFrog, Sandoll,
LawnMower, Wormaster, TEAM_GREEN, TEAM_ORANGE,
TEAM_BLUE, TEAM_YELLOW, TEAM_RED, TEAM_WHITE,
TEAM_GRAY, TEAM_BLACK, TEAM_CAMOUFLAGE, TEAM_PATROL,
JOYSTICK_None, JOYSTICK_GamePad, JOYSTICK_Joystick, JOYSTICK_SteeringWheel
}
Functions
int KDWIN::create_server (int port)
void KDWIN::destroy_server ()
int connect_to_server (ServerFindChain *p)
int restore_connection ()
void disconnect_from_server ()
void set_time_by_server (int n_measures=16)
int set_world (int world, int world_y_size)
void leave_world ()
void total_players_data_list_query ()
void send_player_body (PlayerBody &body)
void short_network_analysis (XBuffer &out)
void network_analysis (XBuffer &out, int integral)
void delay (int msec)
int send_server_data (char *name, ServerData *data, zServerData *zdata)
int is_current_server_configured (char *name, ServerData *data, zServerData *zdata)
void void_network_quant ()
int NetInit (ServerFindChain *p)
void NetCheckRemovePlayer (PlayerData *p)
Variables
double zMod_cycle
double zMod_flood_level_delta
const int MAX_ACTIVE_SLOT = 8
XSocket main_socket
char * host_name
int host_port
char * proxy_name
int proxy_port
int non_blocking_mode
InputEventBuffer events_in
OutputEventBuffer events_out
int global_clock_tau
int time_interval_t0
unsigned int game_birth_time_offset
XBuffer network_analysis_buffer
int average_lag
XQueue< unsigned int > lag_averaging_t0
int NetworkON
NetRndType NetRnd
int zGameBirthTime
int CurrentWorld
const char * CurPlayerName
PlayerBody my_player_body
PlayerData * my_player_data
PlayersList players_list
ServerData my_server_data
ServersList avaible_servers
MessageDispatcher message_dispatcher
zServerData z_my_server_data
zCreateObjectQueue * z_create_object_queue
int GlobalStationID
int LocalStationID
int LocalStationCounter [MAX_NID_OBJECT]
int LocalNetEnvironment
int object_ID_offsets [16]
int stuff_ID_offsets
const int NET_SBUNCH_COUNTER = 83
Macro Definition Documentation
age_of_current_game
#define age_of_current_game () (((int)GLOBAL_CLOCK() - (int)game_birth_time_offset) >> 8)
CHECK_TIMER
#define CHECK_TIMER () ((int)(SDL_GetTicks() - _end_time_) < 0)
CLOCK
#define CLOCK () (SDL_GetTicks()*18/1000)
CREATE_NET_ID
#define CREATE_NET_ID (d) ((++LocalStationCounter[(d & (~(1 << 31))) >> 16] & 0xffff) | d | LocalNetEnvironment)
CREATE_STUFF_NET_ID
#define CREATE_STUFF_NET_ID (d) (((++LocalStationCounter[(d & (~(1 << 31))) >> 16] + stuff_ID_offsets) & 0xffff) | d | LocalNetEnvironment)
DEFAULT_SERVER_PORT
#define DEFAULT_SERVER_PORT 2197
GET_COUNTER_INDEX
#define GET_COUNTER_INDEX (d) ((d & (~(1 << 31))) >> 16)
GET_NETWORK_ID
#define GET_NETWORK_ID (d) (d & ((63 << 16) | (1 << 31)))
GLOBAL_CLOCK
#define GLOBAL_CLOCK () (round(SDL_GetTicks()*(256./1000)) - global_clock_tau)
IS_FUTURE
#define IS_FUTURE (time) ((int)((time) - SDL_GetTicks()) > 0)
IS_PAST
#define IS_PAST (time) ((int)(SDL_GetTicks() - (time)) > 0)
LOCAL_CLOCK
#define LOCAL_CLOCK () (round(SDL_GetTicks()*(256./1000)))
START_TIMER
#define START_TIMER (interval) unsigned int _end_time_ = SDL_GetTicks() + interval;
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
UNCONFIGURED
VAN_WAR
MECHOSOMA
PASSEMBLOSS
NUMBER_MP_GAMES
HUNTAGE
MUSTODONT
DRAW_DEFAULT
DRAW_LINE
DRAW_FLAT
DRAW_GOURAUD
SET_3D_DIRECT_PLACE
SET_3D_CONST_Z
SET_3D_TO_THE_LOWER_LEVEL
SET_3D_TO_THE_UPPER_LEVEL
SET_3D_CHOOSE_LEVEL
UNCONFIGURED
VAN_WAR
MECHOSOMA
PASSEMBLOSS
NUMBER_MP_GAMES
HUNTAGE
MUSTODONT
MESSAGE_FOR_ALL
MESSAGE_FOR_TEAM
MESSAGE_FOR_PLAYER
EXPLOSION_64x64
EXPLOSION_16x16
VK_BUTTON_1
VK_BUTTON_2
VK_BUTTON_3
VK_BUTTON_4
VK_BUTTON_5
VK_BUTTON_6
VK_BUTTON_7
VK_BUTTON_8
VK_BUTTON_9
VK_BUTTON_10
VK_BUTTON_11
VK_BUTTON_12
VK_BUTTON_13
VK_BUTTON_14
VK_BUTTON_15
VK_BUTTON_16
VK_BUTTON_17
VK_BUTTON_18
VK_BUTTON_19
VK_BUTTON_20
VK_BUTTON_21
VK_BUTTON_22
VK_BUTTON_23
VK_BUTTON_24
VK_BUTTON_25
VK_BUTTON_26
VK_BUTTON_27
VK_BUTTON_28
VK_BUTTON_29
VK_BUTTON_30
VK_BUTTON_31
VK_BUTTON_32
VK_STICK_SWITCH_1
VK_STICK_SWITCH_2
VK_STICK_SWITCH_3
VK_STICK_SWITCH_4
VK_STICK_SWITCH_5
VK_STICK_SWITCH_6
VK_STICK_SWITCH_7
VK_STICK_SWITCH_8
VK_STICK_SWITCH_9
      {
     MESSAGE_FOR_ALL,
     MESSAGE_FOR_TEAM,
     MESSAGE_FOR_PLAYER
     };
anonymous enum
anonymous enum
Enumerator
LastMoggy
QueenFrog
Sandoll
LawnMower
Wormaster
LastMoggy
QueenFrog
Sandoll
LawnMower
Wormaster
TEAM_GREEN
TEAM_ORANGE
TEAM_BLUE
TEAM_YELLOW
TEAM_RED
TEAM_WHITE
TEAM_GRAY
TEAM_BLACK
TEAM_CAMOUFLAGE
TEAM_PATROL
JOYSTICK_None
JOYSTICK_GamePad
JOYSTICK_Joystick
JOYSTICK_SteeringWheel
      {
     TEAM_GREEN,
     TEAM_ORANGE,
     TEAM_BLUE,
     TEAM_YELLOW,
     TEAM_RED,
     TEAM_WHITE,
     TEAM_GRAY,
     TEAM_BLACK,
     TEAM_CAMOUFLAGE,
     TEAM_PATROL
     };
Function Documentation
connect_to_server()
int connect_to_server (ServerFindChain * p)
 {
     p->connect(main_socket);
     if(main_socket() && identification(main_socket)){
         current_server_addr = *p;
         events_out.clear();
         events_in.reset();
         events_out.begin_event(ATTACH_TO_GAME);
         events_out < current_server_addr.game_ID;
         events_out.end_body();
         events_out.send(1);
         //std::cout<<"ATTACH_TO_GAME_RESPONSE"<<std::endl;
         events_in.receive_waiting_for_event(ATTACH_TO_GAME_RESPONSE);
         //std::cout<<"[ok]"<<std::endl;
         current_server_addr.game_ID = events_in.get_int();
         current_server_addr.configured = events_in.get_byte();
         game_birth_time_offset = events_in.get_dword();
         GlobalStationID = events_in.get_byte();
         for(int i = 0;i < 16;i++)
             object_ID_offsets[i] = events_in.get_word();
         events_in.ignore_event();
         zGameBirthTime = 0;
         if (zserver_version > 1) {
             //std::cout<<"zTIME_RESPONSE"<<std::endl;
             events_in.receive_waiting_for_event(zTIME_RESPONSE); //ZMOD second network packet
             //std::cout<<"[ok]"<<std::endl;
             zGameBirthTime = events_in.get_int();
             events_in.ignore_event();
         }
         NetworkON = 1;
         number_of_reconnection_attempt = 5;
         return GlobalStationID;
         }
     NetworkON = 0;
     return 0;
 }
References ATTACH_TO_GAME, ATTACH_TO_GAME_RESPONSE, OutputEventBuffer::begin_event(), OutputEventBuffer::clear(), ServerFindChain::configured, ServerFindChain::connect(), current_server_addr, OutputEventBuffer::end_body(), events_in, events_out, game_birth_time_offset, ServerFindChain::game_ID, InputEventBuffer::get_byte(), InputEventBuffer::get_dword(), InputEventBuffer::get_int(), InputEventBuffer::get_word(), GlobalStationID, identification(), InputEventBuffer::ignore_event(), main_socket, NetworkON, number_of_reconnection_attempt, object_ID_offsets, InputEventBuffer::receive_waiting_for_event(), InputEventBuffer::reset(), OutputEventBuffer::send(), zGameBirthTime, zserver_version, and zTIME_RESPONSE.
Referenced by NetInit().
delay()
void delay (int msec)
 {
     START_TIMER(msec);
     while(CHECK_TIMER());
 }
References CHECK_TIMER, and START_TIMER.
Referenced by Object::direct_joystick_control(), Object::direct_keyboard_control(), and disconnect_from_server().
disconnect_from_server()
void disconnect_from_server ()
 {
     events_out.send_simple_query(CLOSE_SOCKET);
     delay(256);
     main_socket.close();
     delay(256);
     events_out.clear();
     events_in.reset();
 }
References OutputEventBuffer::clear(), XSocket::close(), CLOSE_SOCKET, delay(), events_in, events_out, main_socket, InputEventBuffer::reset(), and OutputEventBuffer::send_simple_query().
Referenced by GeneralSystemFree(), and KeyCenter().
is_current_server_configured()
int is_current_server_configured (char * name, ServerData * data, zServerData * zdata)
 {
     if(current_server_addr.configured){
         events_out.send_simple_query(GET_GAME_DATA);
         if(events_in.receive_waiting_for_event(GAME_DATA_RESPONSE)){
             if(events_in.current_body_size()){
                 events_in > name;
                 events_in.read(data,sizeof(ServerData));
                 MP_GAME = data -> GameType;
                 events_in.ignore_event();
                 //---------------------------zMod fixed net packet zGAME_DATA_RESPONSE
                 if (zserver_version>1) {
                     if (events_in.receive_waiting_for_event(zGAME_DATA_RESPONSE)) {
                         if(events_in.current_body_size()) {
                             zdata->mod_id = events_in.get_byte();
                             events_in.ignore_event();
                             return 1;
                         }
                         events_in.ignore_event();
                         return 0;
                     }
                 }
                 //---------------------------zMod net packet zGAME_DATA_RESPONSE
                 return 1;
             }
             events_in.ignore_event();
             return 0;
             }
         }
     return 0;
 }
References ServerFindChain::configured, InputEventBuffer::current_body_size(), current_server_addr, events_in, events_out, GAME_DATA_RESPONSE, InputEventBuffer::get_byte(), GET_GAME_DATA, InputEventBuffer::ignore_event(), zServerData::mod_id, MP_GAME, XBuffer::read(), InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send_simple_query(), zGAME_DATA_RESPONSE, and zserver_version.
leave_world()
void leave_world ()
 {
     events_out.send_simple_query(LEAVE_WORLD);
     enable_transferring = 0;
 }
References enable_transferring, events_out, LEAVE_WORLD, and OutputEventBuffer::send_simple_query().
Referenced by NetworkWorldClose().
NetCheckRemovePlayer()
void NetCheckRemovePlayer (PlayerData * p)
 {
     VangerUnit* v;
     if(p->uvsPoint){
         v = (VangerUnit*)(ActD.Tail);
         while(v){
             if(v->pNetPlayer == p){
                 ClearPhantomTarget(p->client_ID);
                 v->pNetPlayer = NULL;
             };
             v = (VangerUnit*)(v->NextTypeList);
         };
     };
     if(uvsKronActive && ActD.Active && p->name){
         RaceTxtBuff.init();
         switch(my_server_data.GameType){
             case MECHOSOMA:
                 if((p->body.MechosomaStat.ItemCount1 + p->body.MechosomaStat.ItemCount2) >= (my_server_data.Mechosoma.ProductQuantity1 + my_server_data.Mechosoma.ProductQuantity2)){
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerWinnerSecondMessage;
                     else RaceTxtBuff < PlayerWinnerSecondMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.TimeBuf[2] = 200;
                     aiMessageBuffer.ColBuf[2] = 143;
                     aiMessageBuffer.NumStr = 3;
                     if(lang() == RUSSIAN){
                         aiMessageBuffer.add_str(0,(uchar*)(rPlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(rPlayerWinnerOtherMessage));
                     }else{
                         aiMessageBuffer.add_str(0,(uchar*)(PlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(PlayerWinnerOtherMessage));
                     };
                     aiMessageBuffer.add_str(1,(uchar*)(RaceTxtBuff.GetBuf()));
                     aciSendPrompt(&aiMessageBuffer);
                 }else{
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerFirstDropedMessage;
                     else RaceTxtBuff < PlayerFirstDropedMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.NumStr = 2;
                     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
                     if(lang() == RUSSIAN) aiMessageBuffer.add_str(1,(uchar*)(rPlayerSecondDropedMessage));
                     else aiMessageBuffer.add_str(1,(uchar*)(PlayerSecondDropedMessage));
                     aciSendPrompt(&aiMessageBuffer);
                 };
                 break;
             case PASSEMBLOSS:
                 if(p->body.PassemblossStat.CheckpointLighting >= my_server_data.Passembloss.CheckpointsNumber){
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerWinnerSecondMessage;
                     else RaceTxtBuff < PlayerWinnerSecondMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.TimeBuf[2] = 200;
                     aiMessageBuffer.ColBuf[2] = 143;
                     aiMessageBuffer.NumStr = 3;
                     if(lang() == RUSSIAN){
                         aiMessageBuffer.add_str(0,(uchar*)(rPlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(rPlayerWinnerOtherMessage));
                     }else{
                         aiMessageBuffer.add_str(0,(uchar*)(PlayerWinnerFirstMessage));
                         aiMessageBuffer.add_str(2,(uchar*)(PlayerWinnerOtherMessage));
                     };
                     aiMessageBuffer.add_str(1,(uchar*)(RaceTxtBuff.GetBuf()));
                     aciSendPrompt(&aiMessageBuffer);
                 }else{
                     RaceTxtBuff < p->name;
                     if(lang() == RUSSIAN) RaceTxtBuff < rPlayerFirstDropedMessage;
                     else RaceTxtBuff < PlayerFirstDropedMessage;
                     aiMessageBuffer.align_type = 0;
                     aiMessageBuffer.TimeBuf[0] = 200;
                     aiMessageBuffer.ColBuf[0] = 143;
                     aiMessageBuffer.TimeBuf[1] = 200;
                     aiMessageBuffer.ColBuf[1] = 143;
                     aiMessageBuffer.NumStr = 2;
                     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
                     if(lang() == RUSSIAN) aiMessageBuffer.add_str(1,(uchar*)(rPlayerSecondDropedMessage));
                     else aiMessageBuffer.add_str(1,(uchar*)(PlayerSecondDropedMessage));
                     aciSendPrompt(&aiMessageBuffer);
                 };
                 break;
             case VAN_WAR:
                 RaceTxtBuff < p->name;
                 if(lang() == RUSSIAN) RaceTxtBuff < rPlayerFirstDropedMessage;
                 else RaceTxtBuff < PlayerFirstDropedMessage;
                 aiMessageBuffer.align_type = 0;
                 aiMessageBuffer.TimeBuf[0] = 200;
                 aiMessageBuffer.ColBuf[0] = 143;
                 aiMessageBuffer.TimeBuf[1] = 200;
                 aiMessageBuffer.ColBuf[1] = 143;
                 aiMessageBuffer.NumStr = 2;
                 aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
                 if(lang() == RUSSIAN) aiMessageBuffer.add_str(1,(uchar*)(rPlayerSecondDropedMessage));
                 else aiMessageBuffer.add_str(1,(uchar*)(PlayerSecondDropedMessage));
                 aciSendPrompt(&aiMessageBuffer);
                 break;
         };
     };
 };
References aciSendPrompt(), ActD, ActionDispatcher::Active, aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, PlayerData::body, PassemblossStatistic::CheckpointLighting, PASSEMBLOSS_PRM::CheckpointsNumber, ClearPhantomTarget(), PlayerData::client_ID, aciPromptData::ColBuf, ServerData::GameType, XBuffer::GetBuf(), XBuffer::init(), MechosomaStatistic::ItemCount1, MechosomaStatistic::ItemCount2, lang(), MECHOSOMA, ServerData::Mechosoma, PlayerBody::MechosomaStat, my_server_data, PlayerData::name, NULL, aciPromptData::NumStr, PASSEMBLOSS, ServerData::Passembloss, PlayerBody::PassemblossStat, PlayerFirstDropedMessage, PlayerSecondDropedMessage, PlayerWinnerFirstMessage, PlayerWinnerOtherMessage, PlayerWinnerSecondMessage, VangerUnit::pNetPlayer, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, RaceTxtBuff, rPlayerFirstDropedMessage, rPlayerSecondDropedMessage, rPlayerWinnerFirstMessage, rPlayerWinnerOtherMessage, rPlayerWinnerSecondMessage, RUSSIAN, UnitList::Tail, aciPromptData::TimeBuf, uvsKronActive, PlayerData::uvsPoint, and VAN_WAR.
NetInit()
int NetInit (ServerFindChain * p)
 {
     std::cout<<"NetInit - [start]"<<std::endl;
     int i;
     if(!connect_to_server(p))
         return 0;
     std::cout<<"NetInit - [1]"<<std::endl;
     NetworkON = 1;
     LocalStationID = GlobalStationID << 26;
     for(i = 0;i < MAX_NID_OBJECT;i++)
         LocalStationCounter[i] = 0;
     LocalNetEnvironment  =  0;
     set_time_by_server(10);
     std::cout<<"NetInit - [1.5]"<<std::endl;
     my_player_body.clear();
     NETWORK_OUT_STREAM.register_name((char*)(aciGetPlayerName() ? aciGetPlayerName() : "Finger"), (char*)(aciGetPlayerPassword() ? aciGetPlayerPassword() : "Password"));
     std::cout<<"NetInit - [2]"<<std::endl;
     //NETWORK_OUT_STREAM.register_name(aciGetPlayerName() ? aciGetPlayerName() : "Finger", "Password");
     my_player_body.color = aciGetPlayerColor();
     std::cout<<"NetInit - [3]"<<std::endl;
     send_player_body(my_player_body);
     std::cout<<"NetInit - [4]"<<std::endl;
     total_players_data_list_query();
     std::cout<<"NetInit - [5]"<<std::endl;
     GloryPlaceNum = 0;
     GloryPlaceData = NULL;
     UsedCheckNum = 0;
     if(object_ID_offsets[NID_DEVICE >> 16] > object_ID_offsets[NID_STUFF >> 16]) stuff_ID_offsets = object_ID_offsets[(NID_DEVICE & (~(1 << 31))) >> 16];
     else stuff_ID_offsets = object_ID_offsets[(NID_STUFF & (~(1 << 31))) >> 16];
     std::cout<<"NetInit - [ok]"<<std::endl;
     return 1;
 }
network_analysis()
void network_analysis (XBuffer & out, int integral)
 {
     out.init();
     out.SetDigits(3);
     out < "Network's Statistics\n";
     out < (!non_blocking_mode ? "Blocking send()\n" :  "Non-blocking send()\n");
 #ifdef EVENTS_LOG
     out < "Net events is being logged\n";
 #endif
     out < "Set world status: " <= set_world_status < "\n";
     out < "Players:\n";
     PlayerData* p = players_list.first();
     while(p){
         out <= p -> client_ID < "\ts:" <= p -> status < "\tw:" <= p -> world < "\tx:" <= p -> x < "\ty:" <= p -> y < "\tk:" <= p -> body.kills < "\td:" <= p -> body.deaths < "\t";
         if(p -> name)
             out < p -> name < "\t";
         out < "\n";
         p = p -> next;
         }
     out < "Chat:\n";
     MessageElement* pm = message_dispatcher.last();
     while(pm){
         out < pm -> message < "\n";
         if(pm == message_dispatcher.first())
             break;
         pm = (MessageElement*)pm -> prev;
         }
     if(!integral){
         double dt = (double)(SDL_GetTicks() - (int)network_clock)/1000;
         double df = frame - network_frame;
         out < "Rate: " <= df/dt < " FPS\n";
         out < "Time synchronization, lag: " <= response_time < " Sec,  Sigma: " <= time_synchronization_sigma < " Sec\n";
         //out < "Average lag of events (C->S->C): " <= (double)delay_time/(delay_time_counter*256) < " Sec\n";
         out < "Average lag of events (C->S->C): " <= average_lag < " mSec\n";
         out < "Send:  " <= round(n_sended_events/dt) < " EPS,  " <= round(n_sended_bytes/dt) < " BPS,  " <= round(n_sended_events/df) < " EPF,  " <= round(n_sended_bytes/df) < " BPF\n";
         out < "Receive: " <= round(n_received_events/dt) < " EPS,  " <= round(n_received_bytes/dt) < " BPS,  " <= round(n_received_events/df) < " EPF,  " <= round(n_received_bytes/df) < " BPF\n";
         out < "Total send: " <= n_sended_bytes_global < "\n";
         out < "Total receive: " <= n_received_bytes_global < "\n";
         if(now_unsent_size)
             out < "Unsent size: " <= now_unsent_size < "\n";
         network_clock = SDL_GetTicks();
         network_frame = frame;
         n_sended_events_global += n_sended_events;
         n_sended_bytes_global += n_sended_bytes;
         n_received_events_global += n_received_events;
         n_received_bytes_global += n_received_bytes;
         delay_time_global += delay_time;
         delay_time_counter_global += delay_time_counter;
         if(global_unsent_size < now_unsent_size)
             global_unsent_size = now_unsent_size;
         now_unsent_size = n_sended_events = n_sended_bytes = n_received_events = n_received_bytes = delay_time = delay_time_counter = 0;
         }
     else{
         out < "Frames: "        <= frame < "\n";
         out < "Time: " <= (double)GLOBAL_CLOCK()/256. < " sec\n";
         double dt = (double)(SDL_GetTicks() - (int)network_clock_global)/1000;
         double df = frame - network_frame_global;
         out < "Rate: " <= df/dt < " FPS\n";
         out < "Time synchronization, lag: " <= response_time < " Sec,  Sigma: " <= time_synchronization_sigma < " Sec\n";
         //out < "Average delay of events (C->S->C): " <= (double)delay_time_global/(delay_time_counter_global*256) < " Sec\n";
         out < "Average lag of events (C->S->C): " <= average_lag < " mSec\n";
         out < "Send:   " <= n_sended_events_global/dt < " EPS,  " <= n_sended_bytes_global/dt < " BPS,  " <= n_sended_events_global/df < " EPF,  " <= n_sended_bytes_global/df < " BPF\n";
         out < "Receive: " <= n_received_events_global/dt < " EPS,  " <= n_received_bytes_global/dt < " BPS,  " <= n_received_events_global/df < " EPF,  " <= n_received_bytes_global/df < " BPF\n";
         if(global_unsent_size)
             out < "Global unsent size: " <= global_unsent_size < "\n";
         }
 //zmod
     out < "\n";
     out < "zTime: " <= z_time < " / " <= z_time_avg < "\n";
 //#ifdef ZMOD_BETA
 //  out < "zCycle       : " <= zMod_cycle < "\n";
 //  out < "zFlood       : " <= zMod_flood_level_delta < "\n";
 //  out < "zBirthTime   : " <= zGameBirthTime < "\n";
 //  out < "InitialRND   : " <= (unsigned int)my_server_data.InitialRND < "\n";
 //#endif
     if(network_clock_global == -1){
         network_clock_global = SDL_GetTicks();
         network_frame_global = frame;
         n_sended_events_global = n_sended_bytes_global = n_received_events_global = n_received_bytes_global = delay_time_global = 0;
         }
 }
References XTList< Type >::first(), XBuffer::init(), non_blocking_mode, players_list, set_world_status, and XBuffer::SetDigits().
Referenced by GameQuantRTO::Quant(), and restore().
restore_connection()
int restore_connection ()
 {
     if(main_socket())
         return 1;
     //std::cout<<"restore_connection:Connection lost"<<std::endl;
     DOUT("Connection lost");
     current_server_addr.connect(main_socket);
     if(!main_socket){
         if(number_of_reconnection_attempt-- <= 0)
             if (lang() == RUSSIAN) {
                 ErrH.Abort("     ");
             } else {
                 ErrH.Abort("Unable to restore connection to Server");
             }
         return 0;
     }
     number_of_reconnection_attempt = 5;
     events_out.clear();
     events_in.reset();
     events_out.begin_event(RESTORE_CONNECTION);
     events_out < current_server_addr.game_ID < (unsigned char)GlobalStationID;
     events_out.end_body();
     events_out.send(1);
     events_in.receive_waiting_for_event(RESTORE_CONNECTION_RESPONSE);
     int resp = events_in.get_byte();
     events_in.ignore_event();
     DOUT1("Connection restore",resp);
     return resp;
 }
References XErrorHandler::Abort(), OutputEventBuffer::begin_event(), OutputEventBuffer::clear(), ServerFindChain::connect(), current_server_addr, DOUT, DOUT1, OutputEventBuffer::end_body(), ErrH, events_in, events_out, ServerFindChain::game_ID, InputEventBuffer::get_byte(), GlobalStationID, InputEventBuffer::ignore_event(), lang(), main_socket, number_of_reconnection_attempt, InputEventBuffer::receive_waiting_for_event(), InputEventBuffer::reset(), RESTORE_CONNECTION, RESTORE_CONNECTION_RESPONSE, RUSSIAN, and OutputEventBuffer::send().
Referenced by InputEventBuffer::receive().
send_player_body()
void send_player_body (PlayerBody & body)
 {
     if(my_player_data)
         my_player_data -> body = body;
     events_out.set_player_body(body);
     events_out.send(1);
 }
References events_out, my_player_data, OutputEventBuffer::send(), and OutputEventBuffer::set_player_body().
Referenced by VangerUnit::ChangeVangerProcess(), ActionDispatcher::Close(), VangerUnit::Destroy(), GunSlot::Fire(), uvsVanger::get_shop(), VangerUnit::NetCreateVanger(), NetInit(), uvsVanger::prepare_diagen_statistic(), GloryPlace::Quant(), VangerUnit::ShellNetEvent(), and InsectUnit::Touch().
send_server_data()
int send_server_data (char * name, ServerData * data, zServerData * zdata)
 {
     MP_GAME = data -> GameType;
     if(current_server_addr.configured){
         events_out.send_simple_query(GET_GAME_DATA);
         if(events_in.receive_waiting_for_event(GAME_DATA_RESPONSE)){
             if(events_in.current_body_size()){
                 events_in > name;
                 events_in.read(data,sizeof(ServerData));
                 MP_GAME = data -> GameType;
                 events_in.ignore_event();
                 //---------------------------zMod fixed net packet zGAME_DATA_RESPONSE
                 if (zserver_version>1) {
                     if (events_in.receive_waiting_for_event(zGAME_DATA_RESPONSE)) {
                         if(events_in.current_body_size()) {
                             zdata->mod_id = events_in.get_byte();
                             events_in.ignore_event();
                             return 1;
                         }
                         events_in.ignore_event();
                         return 0;
                     }
                 }
                 //---------------------------zMod net packet zGAME_DATA_RESPONSE
                 return 0;//zmod - MAYBE NOT NEEDED
                 }
             events_in.ignore_event();
             }
         return 0;
         }
     events_out.begin_server_data();
     events_out < name < char(0);
     events_out.write(data,sizeof(ServerData));
     events_out.end_body();
     events_out.send_simple_query(GET_GAME_DATA);
     if(!events_in.receive_waiting_for_event(GAME_DATA_RESPONSE) || !events_in.current_body_size())
         ErrH.Abort("Network error: unable to configure server");
     char name_tmp[256];
     ServerData data_tmp;
     events_in > name_tmp;
     events_in.read(&data_tmp,sizeof(ServerData));
     events_in.ignore_event();
     //---------------------------zMod fixed net packet zGAME_DATA_RESPONSE
     if (zserver_version>1) {
         if(!events_in.receive_waiting_for_event(zGAME_DATA_RESPONSE) || !events_in.current_body_size())
             ErrH.Abort("Network error: unable to configure server");
         zdata->mod_id = events_in.get_byte();
         events_in.ignore_event();
     }
     //---------------------------zMod net packet zGAME_DATA_RESPONSE
     current_server_addr.configured = 1;
     if(strcmp(name,name_tmp) || memcmp(data,&data_tmp,sizeof(ServerData))){
         strcpy(name,name_tmp);
         memcpy(data,&data_tmp,sizeof(ServerData));
         return 0;
         }
     return 1;
 }
References XErrorHandler::Abort(), OutputEventBuffer::begin_server_data(), ServerFindChain::configured, InputEventBuffer::current_body_size(), current_server_addr, OutputEventBuffer::end_body(), ErrH, events_in, events_out, GAME_DATA_RESPONSE, InputEventBuffer::get_byte(), GET_GAME_DATA, InputEventBuffer::ignore_event(), zServerData::mod_id, MP_GAME, XBuffer::read(), InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send_simple_query(), XBuffer::write(), zGAME_DATA_RESPONSE, and zserver_version.
set_time_by_server()
void set_time_by_server (int n_measures = 16)
 {
     int i;
     int t0,T1,t2;
     double tau = 0;
     double dtau,dtau2 = 0;
     for(i = 0;i < n_measures;i++){
         //zmod
         z_time_init();
         events_out.send_simple_query(SERVER_TIME_QUERY);
         events_in.receive_waiting_for_event(SERVER_TIME);
         t0 = events_in.current_time();
         events_in.ignore_event();
         T1 = GLOBAL_CLOCK();
         //zmod
         z_time_init();
         events_out.send_simple_query(SERVER_TIME_QUERY);
         events_in.receive_waiting_for_event(SERVER_TIME);
         t2 = events_in.current_time();
         events_in.ignore_event();
         dtau = T1 - (t2 + t0)/2;
         tau += dtau;
         dtau2 += sqr(dtau);
         response_time += t2 - t0;
         }
     double N = n_measures;
     global_clock_tau += round(tau /= N);
     response_time /= N*256.;
     average_lag = round(response_time*1000);
     time_synchronization_sigma = sqrt((dtau2 - N*sqr(tau))/N/(N-1))/256.;
     std::cout<<"set_time_by_server time_synchronization_sigma:"<<time_synchronization_sigma
              <<" average_lag:"<<average_lag<<" t2:"<<t2<<std::endl;
 }
References average_lag, InputEventBuffer::current_time(), events_in, events_out, GLOBAL_CLOCK, global_clock_tau, InputEventBuffer::ignore_event(), InputEventBuffer::receive_waiting_for_event(), response_time, round(), OutputEventBuffer::send_simple_query(), SERVER_TIME, SERVER_TIME_QUERY, sqr(), time_synchronization_sigma, and z_time_init().
Referenced by NetInit().
set_world()
int set_world (int world, int world_y_size)
 {
     events_out.set_world(world,world_y_size);
     events_out.send(1);
     events_in.receive_waiting_for_event(SET_WORLD_RESPONSE);
     events_in.get_byte(); //resp_world
     int resp_status = events_in.get_byte();
     events_in.ignore_event();
     set_world_status = resp_status;
     enable_transferring = 1;
     lag_averaging_t0.clear();
     return resp_status;
 }
References enable_transferring, events_in, events_out, InputEventBuffer::get_byte(), InputEventBuffer::ignore_event(), lag_averaging_t0, InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send(), OutputEventBuffer::set_world(), SET_WORLD_RESPONSE, and set_world_status.
Referenced by NetworkWorldOpen().
short_network_analysis()
void short_network_analysis (XBuffer & out)
 {
     out.init();
     out.SetDigits(3);
     out < "Network's Statistics\n";
     out < "Time synchronization lag: " <= response_time < " Sec\n";
     out < "Time synchronization sigma: " <= time_synchronization_sigma < " Sec\n";
     double dt = (double)(SDL_GetTicks() - (int)network_clock)/1000;
     double df = frame - network_frame;
     out < (main_socket() ? "Connection ok\n" : "Connection lost\n");
     out < "Rate: " <= df/dt < " FPS\n";
     //if(delay_time_counter)
     //out < "Average lag of events (C->S->C): " <= (double)delay_time/(delay_time_counter*256) < " Sec\n";
     out < "Average lag of events (C->S->C): " <= average_lag < " mSec\n";
     out < "Send:  " <= round(n_sended_bytes/dt) < " BPS\n";
     out < "Receive: " <= round(n_received_bytes/dt) < " BPS\n";
     out < "Total send: " <= n_sended_bytes_global < "\n";
     out < "Total receive: " <= n_received_bytes_global < "\n";
     if(now_unsent_size)
         out < "Unsent size: " <= now_unsent_size < "\n";
 //zmod
     out < "\n";
     out < "zTime: " <= z_time < " / " <= z_time_avg < "\n";
 //#ifdef ZMOD_BETA
 //  out < "zCycle       : " <= zMod_cycle < "\n";
 //  out < "zFlood       : " <= zMod_flood_level_delta < "\n";
 //  out < "zBirthTime   : " <= zGameBirthTime < "\n";
 //  out < "InitialRND   : " <= (unsigned int)my_server_data.InitialRND < "\n";
 //#endif
     network_clock = SDL_GetTicks();
     network_frame = frame;
     n_sended_events_global += n_sended_events;
     n_sended_bytes_global += n_sended_bytes;
     n_received_events_global += n_received_events;
     n_received_bytes_global += n_received_bytes;
     delay_time_global += delay_time;
     delay_time_counter_global += delay_time_counter;
     if(global_unsent_size < now_unsent_size)
         global_unsent_size = now_unsent_size;
     now_unsent_size = n_sended_events = n_sended_bytes = n_received_events = n_received_bytes = delay_time = delay_time_counter = 0;
     if(network_clock_global == -1){
         network_clock_global = SDL_GetTicks();
         network_frame_global = frame;
         n_sended_events_global = n_sended_bytes_global = n_received_events_global = n_received_bytes_global = delay_time_global = 0;
         }
 }
References average_lag, delay_time, delay_time_counter, delay_time_counter_global, delay_time_global, frame, global_unsent_size, XBuffer::init(), main_socket, n_received_bytes, n_received_bytes_global, n_received_events, n_received_events_global, n_sended_bytes, n_sended_bytes_global, n_sended_events, n_sended_events_global, network_clock, network_clock_global, network_frame, network_frame_global, now_unsent_size, response_time, round(), XBuffer::SetDigits(), time_synchronization_sigma, z_time, and z_time_avg.
Referenced by GameQuantRTO::Quant().
total_players_data_list_query()
void total_players_data_list_query ()
 {
     events_out.send_simple_query(TOTAL_PLAYERS_DATA_QUERY);
     events_in.receive_waiting_for_event(TOTAL_LIST_OF_PLAYERS_DATA);
     players_list.parsing_total_body_query();
     events_in.ignore_event();
 }
References events_in, events_out, InputEventBuffer::ignore_event(), PlayersList::parsing_total_body_query(), players_list, InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send_simple_query(), TOTAL_LIST_OF_PLAYERS_DATA, and TOTAL_PLAYERS_DATA_QUERY.
Referenced by GeneralSystemFree(), and NetInit().
void_network_quant()
void void_network_quant ()
 {
     events_in.receive();
     while(events_in.current_event()) {
         events_in.ignore_event();
         events_in.next_event();
     }
 }
References InputEventBuffer::current_event(), events_in, InputEventBuffer::ignore_event(), InputEventBuffer::next_event(), and InputEventBuffer::receive().
Variable Documentation
avaible_servers
ServersList avaible_servers extern
Referenced by KDWIN::create_server(), iCreateServer(), iHandleExtEvent(), iUpdateServersList(), and xtInitApplication().
average_lag
int average_lag extern
Referenced by VangerUnit::Quant(), set_time_by_server(), and short_network_analysis().
CurPlayerName
const char* CurPlayerName extern
Referenced by iChatInputChar(), iQuantFirst(), iChatInputField::redraw(), and MessageDispatcher::send().
CurrentWorld
int CurrentWorld extern
events_in
InputEventBuffer events_in extern
Referenced by connect_to_server(), disconnect_from_server(), is_current_server_configured(), Object::NetEvent(), PlayersList::parsing_total_body_query(), MessageDispatcher::receive(), restore_connection(), send_server_data(), set_time_by_server(), set_world(), PlayersList::single_parsing(), TopList::TopList(), total_players_data_list_query(), and void_network_quant().
events_out
OutputEventBuffer events_out extern
Referenced by connect_to_server(), disconnect_from_server(), is_current_server_configured(), leave_world(), restore_connection(), MessageDispatcher::send(), Object::Send(), send_player_body(), send_server_data(), VangerUnit::SendCameraData(), set_time_by_server(), set_world(), TopList::TopList(), and total_players_data_list_query().
game_birth_time_offset
unsigned int game_birth_time_offset extern
Referenced by connect_to_server().
global_clock_tau
int global_clock_tau extern
Referenced by set_time_by_server().
GlobalStationID
int GlobalStationID extern
Referenced by CheckPlayerList(), connect_to_server(), NetInit(), PlayersList::parsing_total_body_query(), VangerUnit::Quant(), restore_connection(), MessageDispatcher::send(), and VangerUnit::ShellNetEvent().
host_name
char* host_name extern
Referenced by ComlineAnalyze(), ServersList::find_servers_in_the_internet(), and xtInitApplication().
host_port
int host_port extern
Referenced by ComlineAnalyze(), ServersList::find_servers_in_the_internet(), and xtInitApplication().
lag_averaging_t0
XQueue<unsigned int> lag_averaging_t0 extern
Referenced by VangerUnit::Quant(), and set_world().
LocalNetEnvironment
int LocalNetEnvironment extern
Referenced by ChangeWorld(), GeneralSystemInit(), and NetInit().
LocalStationCounter
int LocalStationCounter[MAX_NID_OBJECT] extern
Referenced by ChangeWorld(), and NetInit().
LocalStationID
int LocalStationID extern
Referenced by ChangeWorld(), GeneralSystemInit(), and NetInit().
main_socket
XSocket main_socket extern
Referenced by connect_to_server(), disconnect_from_server(), restore_connection(), and short_network_analysis().
MAX_ACTIVE_SLOT
const int MAX_ACTIVE_SLOT = 8
Referenced by ActionDispatcher::ActiveAllSlots(), ActionDispatcher::ActiveAllTerminator(), VangerUnit::ChangeVangerProcess(), ActionDispatcher::CheckDevice(), VangerUnit::CheckOutDevice(), ActionDispatcher::Close(), ActionDispatcher::CreateActive(), ActionDispatcher::DeactiveAllSlots(), ActionDispatcher::DrawResource(), VangerUnit::Go2World(), VangerUnit::InitPlayerPoint(), VangerUnit::ItemQuant(), VangerUnit::NewKeyHandler(), PlayerData::PlayerData(), GameObjectDispatcher::Quant(), ActionDispatcher::Quant(), ActionDispatcher::SlotOut(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), and VangerUnit::UsingCutterig().
message_dispatcher
MessageDispatcher message_dispatcher extern
Referenced by iGameMap::draw(), iChatClearLog(), iChatInputFlush(), and iInitChatScreen().
my_player_body
PlayerBody my_player_body extern
Referenced by VangerUnit::ChangeVangerProcess(), ActionDispatcher::Close(), VangerUnit::Destroy(), GunSlot::Fire(), uvsVanger::get_shop(), VangerUnit::NetCreateVanger(), NetInit(), NetStatisticInit(), NetStatisticUpdate(), uvsVanger::prepare_diagen_statistic(), GloryPlace::Quant(), MessageDispatcher::send(), VangerUnit::ShellNetEvent(), and InsectUnit::Touch().
my_player_data
PlayerData* my_player_data extern
Referenced by PlayersList::parsing_total_body_query(), and send_player_body().
my_server_data
ServerData my_server_data extern
Referenced by aciShowFrags(), VangerUnit::BulletCollision(), CreatePhantomTarget(), VangerUnit::Destroy(), VangerUnit::DestroyCollision(), GeneralSystemClose(), GeneralSystemFree(), uvsVanger::get_shop(), iGetMultiGameParameters(), iSetMultiGameParameters(), NetCheckRemovePlayer(), NetStatisticInit(), NetStatisticUpdate(), NetworkWorldOpen(), uvsVanger::prepare_diagen_statistic(), GameObjectDispatcher::Quant(), VangerUnit::Quant(), ActionDispatcher::Quant(), VangerUnit::SensorQuant(), and VangerUnit::ShellNetEvent().
NET_SBUNCH_COUNTER
const int NET_SBUNCH_COUNTER = 83
Referenced by sBunchCreate().
NetRnd
NetRndType NetRnd extern
network_analysis_buffer
XBuffer network_analysis_buffer extern
Referenced by iGameMap::draw(), GameQuantRTO::Quant(), and restore().
NetworkON
int NetworkON extern
non_blocking_mode
int non_blocking_mode extern
Referenced by network_analysis().
object_ID_offsets
int object_ID_offsets[16] extern
Referenced by connect_to_server(), and NetInit().
players_list
PlayersList players_list extern
Referenced by aciShowFrags(), CheckPlayerList(), VangerUnit::DrawQuant(), iChatMouseHandler(), iInitChatButtons(), iInitChatScreen(), iSortPlayers(), NetSlotEvent(), network_analysis(), CompasObject::Quant(), ActionDispatcher::Quant(), MessageDispatcher::receive(), MessageDispatcher::send(), and total_players_data_list_query().
proxy_name
char* proxy_name extern
proxy_port
int proxy_port extern
stuff_ID_offsets
int stuff_ID_offsets extern
Referenced by NetInit().
time_interval_t0
int time_interval_t0 extern
z_create_object_queue
zCreateObjectQueue* z_create_object_queue extern
z_my_server_data
zServerData z_my_server_data extern
Referenced by GloryPlace::Init(), and FishWarriorList::Init().
zGameBirthTime
int zGameBirthTime extern
Referenced by connect_to_server().
zMod_cycle
double zMod_cycle extern
Referenced by LoadVPR().
zMod_flood_level_delta
double zMod_flood_level_delta extern
Referenced by HordeList::Init(), HordeSourceList::Init(), vrtMap::linkC(), and LoadVPR().