Vangers: src/palette.h File Reference
palette.h File Reference
Classes
struct PaletteTransform
Functions
void PalettePrepare (void)
void PalEvidence (char *tpal, char *pal)
void PalSlake (char *pal)
void pal_iter (void)
void pal_iter_init (void)
Variables
PaletteTransform * palTr
int PAL_MAX
int PAL_WAVE_TERRAIN
int PAL_TERRAIN [TERRAIN_MAX]
int PAL_SPEED [TERRAIN_MAX]
int PAL_AMPL [TERRAIN_MAX]
int PAL_RED [TERRAIN_MAX]
int PAL_GREEN [TERRAIN_MAX]
int PAL_BLUE [TERRAIN_MAX]
Function Documentation
pal_iter()
void pal_iter (void)
 {
     pal_iter0();
     pal_iter1();
     pal_iter2();
 #ifdef TERRAIN16
     XGR_SetPal(palbuf,0,256);
 #else
     XGR_SetPal(palbuf,0,128);
 #endif
 }
References pal_iter0(), pal_iter1(), pal_iter2(), palbuf, and XGR_SetPal.
Referenced by PalConstructor::Quant().
pal_iter_init()
void pal_iter_init (void)
 {
     PAL_MAX = 0;
     PAL_WAVE_TERRAIN = -1;
     for(int i = 0;i < TERRAIN_MAX;i++) offset[i] = 0;
 }
References PAL_MAX, PAL_WAVE_TERRAIN, and TERRAIN_MAX.
PalettePrepare()
void PalettePrepare (void)
{
     std::cout<<"PalettePrepare"<<std::endl;
 //  palbufC = new unsigned char[768];
 //  palbufA = new unsigned char[768];
 //  palbufOrg = new unsigned char[768];
     palbuf = palbufA;
     int k;
     memset(palbuf,0,768);
     int i,j;
     memset(palbufC,0,768);
     if(CurrentWorld < MAIN_WORLD_MAX - 1){
         WorldPalCurrent = WorldTable[CurrentWorld]->escT[0]->Pbunch->currentStage;
         light_modulation  = WorldLightParam[CurrentWorld][WorldPalCurrent];
         memcpy(palbufC,WorldPalData[WorldPalCurrent],768);
     }else{
         WorldPalCurrent = 0;
         light_modulation  = WorldLightParam[CurrentWorld][0];
         XStream fpal(GetTargetName(vMap -> paletteName),XS_IN);
         fpal.read(palbufC,768);
         fpal.close();
     };
     XStream ffp("resource/pal/objects.pal",XS_IN);
     ffp.seek(3*(ENDCOLOR[TERRAIN_MAX - 1] + 1),XS_BEG);
     ffp.read(palbufC + 3*(ENDCOLOR[TERRAIN_MAX - 1] + 1),768 - 3 - 3*(ENDCOLOR[TERRAIN_MAX - 1]));
     ffp.close();
     palbufC[0] = palbufC[1] = palbufC[2] = 0;
 //  palbufC[3*BEGCOLOR[1]] = palbufC[3*BEGCOLOR[1] + 1] = palbufC[3*BEGCOLOR[1] + 2] = 1;
     for(i = 0;i < TERRAIN_MAX;i++){
         palbufC[3*BEGCOLOR[i] + 0] >>= 1;
         palbufC[3*BEGCOLOR[i] + 1] >>= 1;
         palbufC[3*BEGCOLOR[i] + 2] >>= 1;
         }
     palbuf = palbufC;
     for(i = 0;i < 16;i++) palbuf[3*(224 + i) + 0] = palbuf[3*(224 + i) + 1] = palbuf[3*(224 + i) + 2] = i*4; //(uchar)(10 + (pow((double)i/16.,.70)*UNIT)*54/UNIT);
     memcpy(palbufOrg,palbuf,768);
 #if defined(ISCREEN) && defined(ACTINT)
 //  memcpy(palbuf + 0*32*3,palbufOrg + 32*3,32*3);
 //  memcpy(palbuf + 2*32*3,palbufOrg + 32*3,32*3);
 //  memcpy(palbuf + 3*32*3,palbufOrg + 32*3,32*3);
 //  memset(palbuf + 0*32*3,0,32*3);
 //  memset(palbuf + 2*32*3,0,32*3);
 //  memset(palbuf + 3*32*3,0,32*3);
     if(palbufInt) {
         delete[] palbufInt;
     }
     palbufInt = new uchar[768];
     uchar r = palbufOrg[3*(32 + 10) + 0];
     uchar g = palbufOrg[3*(32 + 10) + 1];
     uchar b = palbufOrg[3*(32 + 10) + 2];
     for(i = 0;i < 256;i++){
         palbufInt[i*3 + 0] = r;
         palbufInt[i*3 + 1] = g;
         palbufInt[i*3 + 2] = b;
         }
 #endif
     if(CurrentWorld < MAIN_WORLD_MAX - 1) {
         for(k = 0;k < WorldPalNum;k++)  memcpy(WorldPalData[k] + 128*3,palbufOrg + 128*3,128*3);
     };
     if(CurrentWorld == WORLD_XPLO && ActD.SpobsDestroy){
         for(i = BEGCOLOR[SPOBS_PAL_TERRAIN]*3;i <= ENDCOLOR[SPOBS_PAL_TERRAIN]*3;i++)
             palbuf[i] = palbufSrc[i] = palbufOrg[i] = 5 * (i - BEGCOLOR[SPOBS_PAL_TERRAIN]*3) / (3*(ENDCOLOR[SPOBS_PAL_TERRAIN] - BEGCOLOR[SPOBS_PAL_TERRAIN]));
     };
     if(CurrentWorld == WORLD_THREALL && ActD.ThreallDestroy){
         for(j = 0;j < TERRAIN_MAX;j++){
             if(j == 3 || j == 5 || j == 6 || j == 4) break;
             for(i = BEGCOLOR[j];i <= ENDCOLOR[j];i++){
                 palbufSrc[i*3] = palbufOrg[i*3] = 63 * (i - BEGCOLOR[j]) / (ENDCOLOR[j] - BEGCOLOR[j]);
                 palbufSrc[i*3 + 1] = palbufOrg[i*3 + 1] = 63 *(i - BEGCOLOR[j]) / (ENDCOLOR[j] - BEGCOLOR[j]);
                 palbufSrc[i*3 + 2] = palbufOrg[i*3 + 2] = 63 * (i - BEGCOLOR[j]) / (ENDCOLOR[j] - BEGCOLOR[j]);
             };
         };
     };
 };
PalEvidence()
void PalEvidence (char * tpal, char * pal)
 {
     const int SPEED = 4;
     int log = 1,i;
     int t;
     while(log){
         t = CLOCK();
         while(CLOCK() < t + 1);
         log = 0;
         for(i = 0;i < 256;i++){
             tpal[3*i + 0] += SPEED;
             tpal[3*i + 1] += SPEED;
             tpal[3*i + 2] += SPEED;
             if(tpal[3*i + 0] >= pal[3*i + 0]) tpal[3*i + 0] = pal[3*i + 0]; else log = 1;
             if(tpal[3*i + 1] >= pal[3*i + 1]) tpal[3*i + 1] = pal[3*i + 1]; else log = 1;
             if(tpal[3*i + 2] >= pal[3*i + 2]) tpal[3*i + 2] = pal[3*i + 2]; else log = 1;
             }
         XGR_SetPal(tpal,0,255);
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
         }
 }
References CLOCK, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_SetPal, and xtClearMessageQueue().
Referenced by ShowImageRTO::Init().
PalSlake()
void PalSlake (char * pal)
 {
     const int SPEED = 4;
     int log = 1,i;
     int t;
     while(log){
         t = CLOCK();
         while(CLOCK() < t + 1);
         log = 0;
         for(i = 0;i < 256;i++){
             if(pal[3*i + 0] <= SPEED) pal[3*i + 0] = 0; else pal[3*i + 0] -= SPEED, log = 1;
             if(pal[3*i + 1] <= SPEED) pal[3*i + 1] = 0; else pal[3*i + 1] -= SPEED, log = 1;
             if(pal[3*i + 2] <= SPEED) pal[3*i + 2] = 0; else pal[3*i + 2] -= SPEED, log = 1;
             }
         XGR_SetPal(pal,0,255);
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
         }
 }
References CLOCK, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_SetPal, and xtClearMessageQueue().
Variable Documentation
PAL_AMPL
int PAL_AMPL[TERRAIN_MAX] extern
PAL_BLUE
int PAL_BLUE[TERRAIN_MAX] extern
PAL_GREEN
int PAL_GREEN[TERRAIN_MAX] extern
PAL_MAX
int PAL_MAX extern
Referenced by pal_iter2(), and pal_iter_init().
PAL_RED
int PAL_RED[TERRAIN_MAX] extern
PAL_SPEED
int PAL_SPEED[TERRAIN_MAX] extern
PAL_TERRAIN
int PAL_TERRAIN[TERRAIN_MAX] extern
PAL_WAVE_TERRAIN
int PAL_WAVE_TERRAIN extern
Referenced by pal_iter0(), pal_iter1(), and pal_iter_init().
palTr
PaletteTransform* palTr extern
Referenced by LoadingRTO1::Init(), LoadingRTO2::Init(), LoadingRTO3::Init(), MainMenuRTO::Init(), PaletteTransformRTO::Quant(), PalConstructor::Quant(), and xtInitApplication().