Vangers: src/palette.cpp File Reference
palette.cpp File Reference
#include "global.h"
#include "terra/world.h"
#include "palette.h"
#include "sound/hsound.h"
Macros
#define CLOCK() (SDL_GetTicks()*18/1000)
Functions
void PalEvidence (char *tpal, char *pal)
void PalSlake (char *pal)
void pal_iter0 (void)
void pal_iter1 (void)
void pal_iter2 (void)
void pal_iter_init (void)
void pal_iter (void)
Variables
int DIBLog
uchar * palbuf
uchar * palbufA
uchar * palbufC
uchar * palbufOrg
uchar * palbufInt
uchar * palbufBlack
int MuteLog
int BackgroundSound
PaletteTransform * palTr
int PAL_MAX
int PAL_WAVE_TERRAIN
int PAL_TERRAIN [TERRAIN_MAX]
int PAL_SPEED [TERRAIN_MAX]
int PAL_AMPL [TERRAIN_MAX]
int PAL_RED [TERRAIN_MAX]
int PAL_GREEN [TERRAIN_MAX]
int PAL_BLUE [TERRAIN_MAX]
Macro Definition Documentation
CLOCK
#define CLOCK () (SDL_GetTicks()*18/1000)
Function Documentation
pal_iter()
void pal_iter (void)
 {
     pal_iter0();
     pal_iter1();
     pal_iter2();
 #ifdef TERRAIN16
     XGR_SetPal(palbuf,0,256);
 #else
     XGR_SetPal(palbuf,0,128);
 #endif
 }
References pal_iter0(), pal_iter1(), pal_iter2(), palbuf, and XGR_SetPal.
Referenced by PalConstructor::Quant().
pal_iter0()
void pal_iter0 (void)
 {
     if(PAL_WAVE_TERRAIN == -1 || PAL_WAVE_TERRAIN >= TERRAIN_MAX) return;
     const int DSIZE = 8;
     const int PRD = 64;
     const int DATA[DSIZE] = { 1,3,5,6,5,3,2,1 };
     const int BEG = BEGCOLOR[PAL_WAVE_TERRAIN];
     const int SZ = ENDCOLOR[PAL_WAVE_TERRAIN] - BEG;
     static int off = 0;
     static int cnt = PRD;
     static int add = 1;
     int i;
     uchar* p = palbuf + 3*(BEG + 1);
     uchar* po = palbufOrg + 3*(BEG + 1);
     memcpy(p,po,3*SZ);
     if(off > 0) p += 3*off, po += 3*off;
     uchar* p0 = p;
     for(i = 0;i < DSIZE;i++)
         if(off + i >= 0 && off + i < SZ){
             *p += DATA[i];
             if(*p > 63) *p = 63;
             p++;
             *p += DATA[i];
             if(*p > 63) *p = 63;
             p++;
             *p += DATA[i];
             if(*p > 63) *p = 63;
             p++;
             }
     if(--cnt) off = off + add;
     else {
         cnt = PRD;
         add = realRND(2) ? 1 : -1;
         if(add > 0) off = -DSIZE;
         else off = SZ - 1;
         }
 #ifdef _ROAD_
     if(MuteLog) return;
     static int timer = 10 + realRND(100);
     if(!--timer){
         SOUND_GLOBAL();
         timer = 20 + realRND(100);
         }
     if(BackgroundSound) StartEFFECT(EFF_GLOBAL,1);
 #endif
 }
References BackgroundSound, BEGCOLOR, EFF_GLOBAL, ENDCOLOR, MuteLog, PAL_WAVE_TERRAIN, palbuf, palbufOrg, realRND(), SOUND_GLOBAL, StartEFFECT(), and TERRAIN_MAX.
Referenced by pal_iter().
pal_iter1()
void pal_iter1 (void)
 {
     if(PAL_WAVE_TERRAIN == -1 || PAL_WAVE_TERRAIN >= TERRAIN_MAX) return;
     const int DSIZE = 10;
     const int PRD = 150;
     const int DATA[DSIZE] = { 1,3,5,7,10,8,6,4,2,1 };
     const int BEG = BEGCOLOR[PAL_WAVE_TERRAIN];
     const int SZ = ENDCOLOR[PAL_WAVE_TERRAIN] - BEG;
     static int off = 0;
     static int cnt = PRD;
     static int add = 1;
     int i;
     uchar* p = palbuf + 3*(BEGCOLOR[PAL_WAVE_TERRAIN] + 1);
     uchar* po = palbufOrg + 3*(BEGCOLOR[PAL_WAVE_TERRAIN] + 1);
     memcpy(p,po,3*SZ);
     if(off > 0) p += 3*off, po += 3*off;
     uchar* p0 = p;
     for(i = 0;i < DSIZE;i++)
         if(off + i >= 0 && off + i < SZ){
             *p += DATA[i];
             if(*p > 63) *p = 63;
             p++;
             *p += DATA[i];
             if(*p > 63) *p = 63;
             p++;
             *p += DATA[i];
             if(*p > 63) *p = 63;
             p++;
             }
     if(--cnt) off = off + add;
     else {
         cnt = PRD;
         add = realRND(2) ? 1 : -1;
         if(add > 0) off = -DSIZE;
         else off = SZ - 1;
         }
 }
References BEGCOLOR, ENDCOLOR, PAL_WAVE_TERRAIN, palbuf, palbufOrg, realRND(), and TERRAIN_MAX.
Referenced by pal_iter().
pal_iter2()
void pal_iter2 (void)
 {
     int add,i,j;
     uchar *p,*po;
     for(int ind = 0;ind < PAL_MAX;ind++){
         offset[ind] = rPI(offset[ind] + PAL_SPEED[ind]);
         add = PAL_AMPL[ind]*SI[offset[ind]]/UNIT;
         p = palbuf + 3*BEGCOLOR[PAL_TERRAIN[ind]];
         po = palbufOrg + 3*BEGCOLOR[PAL_TERRAIN[ind]];
         for(i = BEGCOLOR[PAL_TERRAIN[ind]];i <= ENDCOLOR[PAL_TERRAIN[ind]];i++){
             if(PAL_RED[ind]){
                 j = *po + add; if(j > 63) j = 63; else if(j < 0) j = 0;
                 *p++ = j; po++;
                 }
             else *p++ = *po++;
             if(PAL_GREEN[ind]){
                 j = *po + add; if(j > 63) j = 63; else if(j < 0) j = 0;
                 *p++ = j; po++;
                 }
             else *p++ = *po++;
             if(PAL_BLUE[ind]){
                 j = *po + add; if(j > 63) j = 63; else if(j < 0) j = 0;
                 *p++ = j; po++;
                 }
             else *p++ = *po++;
             }
         }
 }
References PAL_MAX.
Referenced by pal_iter().
pal_iter_init()
void pal_iter_init (void)
 {
     PAL_MAX = 0;
     PAL_WAVE_TERRAIN = -1;
     for(int i = 0;i < TERRAIN_MAX;i++) offset[i] = 0;
 }
References PAL_MAX, PAL_WAVE_TERRAIN, and TERRAIN_MAX.
PalEvidence()
void PalEvidence (char * tpal, char * pal)
 {
     const int SPEED = 4;
     int log = 1,i;
     int t;
     while(log){
         t = CLOCK();
         while(CLOCK() < t + 1);
         log = 0;
         for(i = 0;i < 256;i++){
             tpal[3*i + 0] += SPEED;
             tpal[3*i + 1] += SPEED;
             tpal[3*i + 2] += SPEED;
             if(tpal[3*i + 0] >= pal[3*i + 0]) tpal[3*i + 0] = pal[3*i + 0]; else log = 1;
             if(tpal[3*i + 1] >= pal[3*i + 1]) tpal[3*i + 1] = pal[3*i + 1]; else log = 1;
             if(tpal[3*i + 2] >= pal[3*i + 2]) tpal[3*i + 2] = pal[3*i + 2]; else log = 1;
             }
         XGR_SetPal(tpal,0,255);
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
         }
 }
References CLOCK, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_SetPal, and xtClearMessageQueue().
Referenced by ShowImageRTO::Init().
PalSlake()
void PalSlake (char * pal)
 {
     const int SPEED = 4;
     int log = 1,i;
     int t;
     while(log){
         t = CLOCK();
         while(CLOCK() < t + 1);
         log = 0;
         for(i = 0;i < 256;i++){
             if(pal[3*i + 0] <= SPEED) pal[3*i + 0] = 0; else pal[3*i + 0] -= SPEED, log = 1;
             if(pal[3*i + 1] <= SPEED) pal[3*i + 1] = 0; else pal[3*i + 1] -= SPEED, log = 1;
             if(pal[3*i + 2] <= SPEED) pal[3*i + 2] = 0; else pal[3*i + 2] -= SPEED, log = 1;
             }
         XGR_SetPal(pal,0,255);
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
         xtClearMessageQueue();
         }
 }
References CLOCK, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_SetPal, and xtClearMessageQueue().
Variable Documentation
BackgroundSound
int BackgroundSound extern
Referenced by pal_iter0().
DIBLog
int DIBLog extern
Referenced by ComlineAnalyze(), and PaletteTransform::quant().
MuteLog
int MuteLog extern
Referenced by pal_iter0().
PAL_AMPL
int PAL_AMPL[TERRAIN_MAX]
PAL_BLUE
int PAL_BLUE[TERRAIN_MAX]
PAL_GREEN
int PAL_GREEN[TERRAIN_MAX]
PAL_MAX
int PAL_MAX
Referenced by pal_iter2(), and pal_iter_init().
PAL_RED
int PAL_RED[TERRAIN_MAX]
PAL_SPEED
int PAL_SPEED[TERRAIN_MAX]
PAL_TERRAIN
int PAL_TERRAIN[TERRAIN_MAX]
PAL_WAVE_TERRAIN
int PAL_WAVE_TERRAIN
Referenced by pal_iter0(), pal_iter1(), and pal_iter_init().
palbuf
uchar* palbuf extern
Referenced by pal_iter(), pal_iter0(), and pal_iter1().
palbufA
uchar * palbufA
palbufBlack
uchar * palbufBlack
palbufC
uchar * palbufC
palbufInt
uchar * palbufInt
palbufOrg
uchar * palbufOrg
Referenced by pal_iter0(), and pal_iter1().
palTr
PaletteTransform* palTr
Referenced by LoadingRTO1::Init(), LoadingRTO2::Init(), LoadingRTO3::Init(), MainMenuRTO::Init(), PaletteTransformRTO::Quant(), PalConstructor::Quant(), and xtInitApplication().