Vangers: src/particle/partmap.cpp File Reference
partmap.cpp File Reference
#include "../global.h"
#include "../3d/3d_math.h"
#include "../common.h"
#include "../sqexp.h"
#include "../backg.h"
#include "../terra/vmap.h"
#include "../terra/world.h"
#include "../terra/render.h"
#include "../dast/poly3d.h"
#include "particle.h"
#include "partmap.h"
#include <string.h>
Macros
#define random(a) BogusRND(a)
#define random1(a) (rand() & 1 ? random(a) : -random(a))
#define P(a, b) int((f1p)[(a) + (b)])
Functions
void color_line_f (int len, unsigned char *dbuf, int bx, int bKx, int fx, int fy)
void transparency_line_f (int len, unsigned char *dbuf, int bx, int bKx, int fx, int fy)
void smart_putspr_f (unsigned char *data, int Xcenter, int Ycenter, int XsizeB, int YsizeB, int ScaleXsize, int height=255)
void processParticleMapLineWithNoMask (unsigned char *&f1p, unsigned char *&f2p, int Xmax)
void processParticleMapLineWithMask (unsigned char *&f1p, unsigned char *&f2p, int Xmax, TABLE_TYPE *&moff)
void bitmap2screen (char *vb, unsigned char *data, int Xcenter, int Ycenter, int XsizeB, int YsizeB, int ScaleXsize, int turn)
void FirePaletteInit (unsigned char *pal)
void FirePaletteTableInit (unsigned char *pal)
Variables
Mask * ParticleMapProcessMaskArray = 0
int ParticleMapProcessMaskTotal = 0
unsigned char * FirePaletteTable
int CurrDev = 0
int frame
Macro Definition Documentation
P
#define P (a, b) int((f1p)[(a) + (b)])
random
#define random (a) BogusRND(a)
random1
#define random1 (a) (rand() & 1 ? random(a) : -random(a))
Function Documentation
bitmap2screen()
void bitmap2screen (char * vb, unsigned char * data, int Xcenter, int Ycenter, int XsizeB, int YsizeB, int ScaleXsize, int turn)
color_line_f()
void color_line_f (int len, unsigned char * dbuf, int bx, int bKx, int fx, int fy)
FirePaletteInit()
void FirePaletteInit (unsigned char * pal)
 {
     int first_col = FIRE_COLOR_FIRST;
     int i;
     const int NULL_INTENS = 20;
     for(i = 0;i < RED_POINT;i++){
         pal[3*(i + first_col)] = NULL_INTENS + (64 - NULL_INTENS)*i/RED_POINT;
         pal[3*(i + first_col) + 1] = 0;
         pal[3*(i + first_col) + 2] = 0;
         }
     for(;i < YELLOW_POINT;i++){
         pal[3*(i + first_col)] = 63;
         pal[3*(i + first_col) + 1] = (64*(i - YELLOW_POINT)/(YELLOW_POINT - RED_POINT)) & 63;
 //      pal[3*(i + first_col) + 1] = (64*(i - YELLOW_POINT)/(YELLOW_POINT - RED_POINT));
         pal[3*(i + first_col) + 2] = 0;
         }
     for(;i < WHITE_POINT;i++){
         pal[3*(i + first_col)] = 63;
         pal[3*(i + first_col) + 1] = 63;
         pal[3*(i + first_col) + 2] = (64*(i - WHITE_POINT)/(WHITE_POINT - YELLOW_POINT)) & 63;
 //      pal[3*(i + first_col) + 2] = (64*(i - WHITE_POINT)/(WHITE_POINT - YELLOW_POINT));
         }
     i = WHITE_POINT - 1;
     pal[3*(i + first_col)] = pal[3*(i + first_col) + 1] = pal[3*(i + first_col) + 2] = 63;
 /*
     int middle = first_col + WHITE_POINT/2;
     const BLACK_RAD = 2;
     for(int j = 0;j <= BLACK_RAD;j++){
         pal[3*(middle + j)] =     pal[3*(middle + BLACK_RAD)]*j/BLACK_RAD;
         pal[3*(middle + j) + 1] = pal[3*(middle + BLACK_RAD) + 1]*j/BLACK_RAD;
         pal[3*(middle + j) + 2] = pal[3*(middle + BLACK_RAD) + 2]*j/BLACK_RAD;
         pal[3*(middle - j)] =     pal[3*(middle - BLACK_RAD)]*j/BLACK_RAD;
         pal[3*(middle - j) + 1] = pal[3*(middle - BLACK_RAD) + 1]*j/BLACK_RAD;
         pal[3*(middle - j) + 2] = pal[3*(middle - BLACK_RAD) + 2]*j/BLACK_RAD;
         }
 */
 }
References FIRE_COLOR_FIRST, RED_POINT, WHITE_POINT, and YELLOW_POINT.
Referenced by GeneralTableOpen().
FirePaletteTableInit()
void FirePaletteTableInit (unsigned char * pal)
 {
     /*for(int i = 0;i < 256;i++){
         int Y = ((19595*(int)pal[3*i] + 38470*(int)pal[3*i + 1] + 7471*(int)pal[3*i + 2])>>17);
         for(int j = 0; j < 256; j++){
             int A = ((19595*(int)pal[3*j] + 38470*(int)pal[3*j + 1] + 7471*(int)pal[3*j + 2])>>16);
             if( A >= 32 ) A = 31;
             FirePaletteTable[i + (j << 8)] = A;
             //  if ( ((Y + A ) >> 1) >= FIRE_PROCESS_COLOR_MAX )
             //      FirePaletteTable[i + (j << 8)] = FIRE_PROCESS_COLOR_MAX-1;
             //  else
             //      FirePaletteTable[i + (j << 8)] = (Y + A)>>1;
         }  //  end for j
     }//  end for i*/
 }
Referenced by GeneralTableOpen().
processParticleMapLineWithMask()
void processParticleMapLineWithMask (unsigned char *& f1p, unsigned char *& f2p, int Xmax, TABLE_TYPE *& moff)
processParticleMapLineWithNoMask()
void processParticleMapLineWithNoMask (unsigned char *& f1p, unsigned char *& f2p, int Xmax)
smart_putspr_f()
void smart_putspr_f (unsigned char * data, int Xcenter, int Ycenter, int XsizeB, int YsizeB, int ScaleXsize, int height = 255)
 {
     if(!XsizeB || !ScaleXsize)
         return;
     int XsizeS = ScaleXsize;
     int YsizeS = ScaleXsize*YsizeB/XsizeB;
     if(DepthShow)
         YsizeS = round(YsizeS*Cos(SlopeAngle));
     int bKx,bKy;
     int X = Xcenter - XsizeS/2;
     int Y = Ycenter - YsizeS/2;
     bKx = bKy = (XsizeB << 15)/ScaleXsize;
     int bx = 0;
     int by = 0;
     int xt = X + XsizeS;
     int yt = Y + YsizeS;
     if(X < UcutLeft){
         bx = ((UcutLeft - X) << 15)*XsizeB/ScaleXsize;
         XsizeS -= UcutLeft - X;
         X = UcutLeft;
         }
     if(Y < VcutUp){
         by = ((VcutUp - Y) << 15)*XsizeB/ScaleXsize;
         YsizeS -= VcutUp - Y;
         Y = VcutUp;
         }
     if(xt > UcutRight){
         XsizeS -= xt - UcutRight;
         xt = UcutRight;
         }
     if(yt > VcutDown){
         YsizeS -= yt - VcutDown;
         yt = VcutDown;
         }
     if(XsizeS <= 0)
         return;
     int vadd = XGR_MAXX - XsizeS;
     draw_vbuf = XGR_VIDEOBUF + Y*XGR_MAXX + X;
     draw_lt = vMap -> lineT;
     z_level = height;
     if(height >= 256){
         while(YsizeS-- > 0){
             transparency_line_non_test_f(XsizeS,data + (by >> 15)*XsizeB,bx,bKx);
             by += bKy;
             draw_vbuf += vadd;
             }
         return;
         }
     int x = X - ScreenCX;
     int y = Y - ScreenCY;
     if(!DepthShow){
         draw_k_xscr_x = cosTurnInv;
         draw_k_xscr_y = -sinTurnInv;
         int k_yscr_x = sinTurnInv;
         int k_yscr_y = cosTurnInv;
         int tfx = (ViewX << 16) + (x*cosTurnInv + y*sinTurnInv) + (1 << 15);
         int tfy = (ViewY << 16) + (-x*sinTurnInv + y*cosTurnInv) + (1 << 15);
         while(YsizeS-- > 0){
             transparency_line_f(XsizeS,data + (by >> 15)*XsizeB,bx,bKx,tfx,tfy);
             by += bKy;
             draw_vbuf += vadd;
             tfx += k_yscr_x;
             tfy += k_yscr_y;
             }
         }
     else{
         int fx,fy;
         int cx = ViewX << 16;
         int cy = ViewY << 16;
         double al = Ha*x + Va*y;
         double bl = Hb*x + Vb*y;
         double cl = Oc + Hc*x + Vc*y;
         double ar = Ha*(x + XsizeS) + Va*y;
         double br = Hb*(x + XsizeS) + Vb*y;
         double nxs_inv = 1/(double)XsizeS;
         double cl_inv;
         while(YsizeS-- > 0){
             if(fabs(cl) < DBL_EPS)
                 return;
             cl_inv = 1/cl;
             fx = round(al*cl_inv);
             fy = round(bl*cl_inv);
             cl_inv *= nxs_inv;
             draw_k_xscr_x = round((ar - al)*cl_inv);
             draw_k_xscr_y = round((br - bl)*cl_inv);
             transparency_line_f(XsizeS,data + (by >> 15)*XsizeB,bx,bKx,fx + cx,fy + cy);
             by += bKy;
             draw_vbuf += vadd;
             al += Va;
             bl += Vb;
             cl += Vc;
             ar += Va;
             br += Vb;
             }
         }
 }
References Cos(), cosTurnInv, DBL_EPS, DepthShow, draw_k_xscr_x, draw_k_xscr_y, draw_lt, draw_vbuf, Ha, Hb, Hc, Oc, round(), ScreenCX, ScreenCY, sinTurnInv, SlopeAngle, transparency_line_f(), transparency_line_non_test_f(), UcutLeft, UcutRight, Va, Vb, Vc, VcutDown, VcutUp, ViewX, ViewY, vMap, XGR_MAXX, XGR_VIDEOBUF, and z_level.
Referenced by ParticleMapProcess::process().
transparency_line_f()
void transparency_line_f (int len, unsigned char * dbuf, int bx, int bKx, int fx, int fy)
 {
     unsigned char c;
     unsigned char* mbuf;
     while(len-- > 0){
         if((c = dbuf[bx >> 15]) != 0){
             mbuf = draw_lt[(fy >> 16) & clip_mask_y] + (((fx >> 16) | 1) & clip_mask_x);
             if ( c > 31 ) c = 31;
             if(z_level > *mbuf)
                 *draw_vbuf = FireColorTable[*draw_vbuf + (c << 11)];
             }
         draw_vbuf++;
         bx += bKx;
         fx += draw_k_xscr_x;
         fy += draw_k_xscr_y;
         }
 }
References clip_mask_x, clip_mask_y, draw_k_xscr_x, draw_k_xscr_y, draw_lt, draw_vbuf, FireColorTable, and z_level.
Referenced by smart_putspr_f().
Variable Documentation
CurrDev
int CurrDev = 0
Referenced by ParticleMapProcess::process().
FirePaletteTable
unsigned char* FirePaletteTable
Referenced by GeneralTableFree(), and GeneralTableInit().
frame
int frame extern
Referenced by ParticleMapProcess::process().
ParticleMapProcessMaskArray
Mask* ParticleMapProcessMaskArray = 0
Referenced by ParticleMapProcess::finitMask(), and ParticleMapProcess::PickUpMask().
ParticleMapProcessMaskTotal
int ParticleMapProcessMaskTotal = 0
Referenced by ParticleMapProcess::PickUpMask().