Vangers: src/dast/poly3d.h File Reference
poly3d.h File Reference
Classes
struct DAST_SIGN_TYPE
struct dastPoly3D
struct dastResourcePoly3D
struct dastResourceSign
Functions
void precalc_sqr3_matr (void)
uchar sqr3 (int x)
uchar * get_down_ground (int x, int y)
uchar * get_up_ground (int x, int y)
uchar * get_real_ground (int where, int x, int y)
void dastCreateResource (const char *FileName)
void dastCreateResourceSign (const char *FileName)
void dastDeleteResource (void)
void dastDeleteResourceSign (void)
void dastPutSpriteOnMapAlt (int x, int y, uchar *data, int x_size, int y_size, unsigned int scale)
void dastPutSandOnMapAlt (int x, int y, uchar _z, uchar, uchar)
Variables
dastResourcePoly3D * dastResource
dastResourceSign * dastResSign
uchar * sqr3_matr
int MOVER_ON
Function Documentation
dastCreateResource()
void dastCreateResource (const char * FileName)
{
     dastResource = new dastResourcePoly3D(FileName);
 }
References dastResource.
Referenced by LoadingRTO2::Init().
dastCreateResourceSign()
void dastCreateResourceSign (const char * FileName)
{
     dastResSign = new dastResourceSign(FileName);
 }
References dastResSign.
Referenced by ActionDispatcher::Init().
dastDeleteResource()
void dastDeleteResource (void)
dastDeleteResourceSign()
void dastDeleteResourceSign (void)
{
     delete dastResSign;
 }
References dastResSign.
Referenced by ActionDispatcher::Free().
dastPutSandOnMapAlt()
void dastPutSandOnMapAlt (int x, int y, uchar _z, uchar , uchar)
{
         uchar **lt = vMap -> lineT;
         int i, j;
         uchar _d = 82;
         newter <<= TERRAIN_OFFSET;
         int x_size = wide;
         int y_size = wide;
         for( i = y - (y_size>>1); i < y + (y_size>>1); i++)
             if (!lt[(i) & clip_mask_y]) return;
         for( i = y - (y_size>>1); i <= y + (y_size>>1); i++)
             for( j = x - (x_size>>1); j <= x + (x_size>>1); j++){
                 //uchar *lc = get_down_ground( (j) & clip_mask_x, i );
                 //uchar *lc = (*pf)( (j) & clip_mask_x, i );
                 uchar *lc = get_up_ground( (j) & clip_mask_x, i );
                 if ( *lc > _z ) lc = get_down_ground( (j) & clip_mask_x, i );
                 if (*lc + _d < _z) continue;
                 uchar hh = RND(4);
                 //if ( GET_TERRAIN(*(lc + H_SIZE)) ){
                     *lc += hh + RND(2);
                     //*lc += RND(6);
                 if ( GET_TERRAIN(*(lc + H_SIZE)) ){
                     //if ( hh || !RND(4) ){
                     if ( !RND(4) ){
                         *(lc + H_SIZE) &= ~TERRAIN_MASK;
                         *(lc + H_SIZE) += newter;
                     }
                 }
         }
         regRender(x - (x_size>>1), y - (y_size>>1), x + (x_size>>1), y + (y_size>>1), 0);
 }
References clip_mask_x, clip_mask_y, get_down_ground(), GET_TERRAIN, get_up_ground(), H_SIZE, regRender(), RND(), TERRAIN_MASK, TERRAIN_OFFSET, and vMap.
Referenced by dastPoly3D::quant_make_sign().
dastPutSpriteOnMapAlt()
void dastPutSpriteOnMapAlt (int x, int y, uchar * data, int x_size, int y_size, unsigned int scale)
{
         uchar **lt = vMap -> lineT;
         int i, j;
         uchar *llt;
         for( i = y - (y_size>>1); i < y + (y_size>>1); i++)
             if (!lt[(i) & clip_mask_y]) return;
         for( i = y - (y_size>>1); i < y + (y_size>>1); i++)
             for( j = x - (x_size>>1); j < x + (x_size>>1); j++, data++){
                 llt = get_down_ground( (j) & clip_mask_x, i );
                 if (BREAKABLE_TERRAIN(*(llt + H_SIZE))){
                     int dz = (*data)*scale>>15;
                     if ( *llt + dz < 256 ) *llt += dz;
                     else *llt = 255;
                 }
             }
 }
References BREAKABLE_TERRAIN, clip_mask_x, clip_mask_y, get_down_ground(), H_SIZE, and vMap.
Referenced by dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), and dastPoly3D::make_mole().
get_down_ground()
uchar* get_down_ground (int x, int y) inline
 {
     uchar * lt = vMap -> lineT[y & clip_mask_y] + x;
 //  if ( !lt ) ErrH.Abort( "DAST : not it line" );
     if(*(lt + H_SIZE) & DOUBLE_LEVEL){
             if((x & 1)) return (--lt);
     }
     return (lt) ;
 }
References clip_mask_y, DOUBLE_LEVEL, H_SIZE, and vMap.
Referenced by dastPutSandOnMapAlt(), dastPutSpriteOnMapAlt(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), and dastPoly3D::make_mole().
get_real_ground()
uchar* get_real_ground (int where, int x, int y) inline
 {
     uchar * lt = vMap -> lineT[y & clip_mask_y] + x;
     //if ( !lt ) ErrH.Abort( "DAST : not it line" );
     if(*(lt + H_SIZE) & DOUBLE_LEVEL){
         if ( where ){
             if((x & 1)) return (--lt);
         } else {
             if(!(x & 1)) return (++lt);
         }
     }
     return (lt) ;
 }
References clip_mask_y, DOUBLE_LEVEL, H_SIZE, and vMap.
Referenced by ParticleMapProcess::process().
get_up_ground()
uchar* get_up_ground (int x, int y) inline
 {
     uchar * lt = vMap -> lineT[y & clip_mask_y] + x;
 //  if ( !lt ) ErrH.Abort( "DAST : not it line" );
     if(*(lt + H_SIZE) & DOUBLE_LEVEL){
             if(!(x & 1)) return (++lt);
     }
     return (lt) ;
 }
References clip_mask_y, DOUBLE_LEVEL, H_SIZE, and vMap.
Referenced by dastPutSandOnMapAlt().
precalc_sqr3_matr()
void precalc_sqr3_matr (void)
sqr3()
uchar sqr3 (int x)
Variable Documentation
dastResource
dastResourcePoly3D* dastResource extern
Referenced by dastCreateResource().
dastResSign
dastResourceSign* dastResSign extern
Referenced by dastCreateResourceSign(), dastDeleteResourceSign(), dastPoly3D::dastPoly3D(), and dastPoly3D::quant_make_sign().
MOVER_ON
int MOVER_ON extern
sqr3_matr
uchar * sqr3_matr extern