Vangers: src/terra/render.h File Reference
render.h File Reference
Macros
#define DX(x, d) (XCYCL((x) + (d)))
#define DY(y, d) (YCYCL((y) + (d)))
#define GET_TERRAIN_TYPE(a) ((a) & TERRAIN_MASK)
#define GET_TERRAIN(a) (((a) & TERRAIN_MASK) >> TERRAIN_OFFSET)
#define IS_DOUBLE(a) ((a) & DOUBLE_LEVEL)
#define GETUPALT(x, y) GET_UP_ALT((vMap -> lineT[y] + H_SIZE + (x)),(*(vMap -> lineT[y] + (x))),vMap -> lineT[y],x)
#define GETDOWNALT(x, y) GET_DOWN_ALT((vMap -> lineT[y] + H_SIZE + (x)),(*(vMap -> lineT[y] + (x))),vMap -> lineT[y],x)
#define GETWIDTH(x, y) GET_WIDTH(vMap -> lineT[y] + H_SIZE + (x), x)
#define GETCOL(x, y) (*(vMap -> lineTcolor[y] + (x)))
#define GETTERRAIN(x, y) GET_REAL_TERRAIN((vMap -> lineT[y] + H_SIZE + (x)),x)
#define GETDOWNTERRAIN(x, y) GET_REAL_DOWNTERRAIN((vMap -> lineT[y] + H_SIZE + (x)),x)
Functions
uchar GET_REAL_TERRAIN (uchar *type, int x)
uchar GET_REAL_TERRAIN_TYPE (uchar *type, int x)
uchar GET_REAL_DOWNTERRAIN (uchar *type, int x)
uchar GET_REAL_DOWNTERRAIN_TYPE (uchar *type, int x)
uchar GET_DOWN_ALT (uchar *type, int h, uchar *pa0, int x)
uchar GET_UP_ALT (uchar *type, int h, uchar *pa0, int x)
void SET_UP_ALT (uchar *type, uchar h, uchar *pa0, int x)
void SET_DOWN_ALT (uchar *type, uchar h, uchar *pa0, int x)
int SET_REAL_TERRAIN (uchar *type, uchar newtype, int x)
int SET_REAL_DOWNTERRAIN (uchar *type, uchar newtype, int x)
uchar GET_WIDTH (uchar *type, int x)
void regRender (int x0, int y0, int x1, int y1, int changed=1)
void regRenderSimple (int x0, int y0, int x1, int y1)
void regDownRender (int x0, int y0, int x1, int y1, int changed=1)
void pixSet (int x, int y, int delta, int surf=1)
void pixSetR (int x, int y, int delta, int surf=1)
void pixDownSet (int x, int y, int delta, int surf=1)
void regSet (int x0, int y0, int x1, int y1, int dry, int surf=1)
Variables
const int CLR_MAX_SIDE = 255
const int CLR_MAX = 2*CLR_MAX_SIDE + 1
const uchar H_CORRECTION = 1
uchar * lightCLR [TERRAIN_MAX]
uchar palCLR [TERRAIN_MAX][2 *256]
Macro Definition Documentation
DX
#define DX (x, d) (XCYCL((x) + (d)))
DY
#define DY (y, d) (YCYCL((y) + (d)))
GET_TERRAIN
#define GET_TERRAIN (a) (((a) & TERRAIN_MASK) >> TERRAIN_OFFSET)
GET_TERRAIN_TYPE
#define GET_TERRAIN_TYPE (a) ((a) & TERRAIN_MASK)
GETCOL
#define GETCOL (x, y) (*(vMap -> lineTcolor[y] + (x)))
GETDOWNALT
#define GETDOWNALT (x, y) GET_DOWN_ALT((vMap -> lineT[y] + H_SIZE + (x)),(*(vMap -> lineT[y] + (x))),vMap -> lineT[y],x)
GETDOWNTERRAIN
#define GETDOWNTERRAIN (x, y) GET_REAL_DOWNTERRAIN((vMap -> lineT[y] + H_SIZE + (x)),x)
GETTERRAIN
#define GETTERRAIN (x, y) GET_REAL_TERRAIN((vMap -> lineT[y] + H_SIZE + (x)),x)
GETUPALT
#define GETUPALT (x, y) GET_UP_ALT((vMap -> lineT[y] + H_SIZE + (x)),(*(vMap -> lineT[y] + (x))),vMap -> lineT[y],x)
GETWIDTH
#define GETWIDTH (x, y) GET_WIDTH(vMap -> lineT[y] + H_SIZE + (x), x)
IS_DOUBLE
#define IS_DOUBLE (a) ((a) & DOUBLE_LEVEL)
Function Documentation
GET_DOWN_ALT()
uchar GET_DOWN_ALT (uchar * type, int h, uchar * pa0, int x) inline
 {
     if(IS_DOUBLE(*type)) if(x & 1) h = *(pa0 + x - 1);
     return h;
 }
References IS_DOUBLE.
Referenced by pixDownSet(), pixSet(), and pixSetR().
GET_REAL_DOWNTERRAIN()
uchar GET_REAL_DOWNTERRAIN (uchar * type, int x) inline
 {
     if(*type & DOUBLE_LEVEL) {
         if(!(x & 1)) {
             return GET_TERRAIN(*type);
         } else {
             return GET_TERRAIN(*(type - 1));
         }
     }
     return GET_TERRAIN(*type);
 }
References DOUBLE_LEVEL, and GET_TERRAIN.
Referenced by TrackUnit::DrawMechosParticle(), and pixDownSet().
GET_REAL_DOWNTERRAIN_TYPE()
uchar GET_REAL_DOWNTERRAIN_TYPE (uchar * type, int x) inline
 {
     if(*type & DOUBLE_LEVEL) {
         if(!(x & 1)) {
             return GET_TERRAIN_TYPE(*type);
         } else {
             return GET_TERRAIN_TYPE(*(type - 1));
         }
     }
     return GET_TERRAIN_TYPE(*type);
 }
References DOUBLE_LEVEL, and GET_TERRAIN_TYPE.
Referenced by pixDownSet().
GET_REAL_TERRAIN()
uchar GET_REAL_TERRAIN (uchar * type, int x) inline
 {
     if(x & 1) return GET_TERRAIN(*type);
     else if(*type & DOUBLE_LEVEL) return GET_TERRAIN(*(type + 1));
     return GET_TERRAIN(*type);
 }
References DOUBLE_LEVEL, and GET_TERRAIN.
Referenced by TrackUnit::DrawMechosParticle(), and pixSet().
GET_REAL_TERRAIN_TYPE()
uchar GET_REAL_TERRAIN_TYPE (uchar * type, int x) inline
 {
     if(x & 1) return GET_TERRAIN_TYPE(*type);
     else if(*type & DOUBLE_LEVEL) return GET_TERRAIN_TYPE(*(type + 1));
     return GET_TERRAIN_TYPE(*type);
 }
References DOUBLE_LEVEL, and GET_TERRAIN_TYPE.
Referenced by pixSet(), and pixSetR().
GET_UP_ALT()
uchar GET_UP_ALT (uchar * type, int h, uchar * pa0, int x) inline
 {
     if(IS_DOUBLE(*type)){
         if(x & 1)
             h = *(pa0 + x);
         else
             h = *(pa0 + x + 1);
         }
     return h;
 }
References IS_DOUBLE.
Referenced by pixSet(), and pixSetR().
GET_WIDTH()
uchar GET_WIDTH (uchar * type, int x) inline
 {
     if(*type & DOUBLE_LEVEL){
         if(x & 1)
             return (((GET_DELTA(*(type - 1)) << 2) + GET_DELTA(*type) + 1) << DELTA_SHIFT);
         else
             return (((GET_DELTA(*type) << 2) + GET_DELTA(*(type + 1)) + 1) << DELTA_SHIFT);
         }
     return 0;
 }
References DELTA_SHIFT, DOUBLE_LEVEL, and GET_DELTA.
pixDownSet()
void pixDownSet (int x, int y, int delta, int surf = 1)
 {
 std::cout<<"pixDownSet"<<std::endl;
     uchar** lt = vMap -> lineT;
     uchar* pa = lt[y];
     if(!pa){
 #ifdef _SURMAP_
         vMap -> increase(y,y);
         pa = lt[y];
 #else
         return;
 #endif
         }
     uchar* pa0 = pa;
     pa += x;
     uchar* pf = pa + H_SIZE;
     int h = GET_DOWN_ALT(pf,*pa,pa0,x),t;
 #ifdef _SURMAP_
     if(surf) if(!ActiveTerrain[GET_REAL_DOWNTERRAIN(pf,x)]) return;
     if(h < MiniLevel || h > MaxiLevel) return;
     if(MosaicToggle && mosaicBMP.mode <= 1) delta = mosaicBMP.getDelta(x,y,delta);
 #endif
     if(*pf & DOUBLE_LEVEL)
         if(!(x & 1)){
             h += delta;
 #ifdef _SURMAP_
             if(h < MiniLevel) h = MiniLevel;
             if(h > MaxiLevel) h = MaxiLevel;
 #endif
 //          t = ((GET_DELTA(*pf) << 2) + GET_DELTA(*(pf + 1)) + 1) << DELTA_SHIFT;
             t = *(pa + 1) - TunnelProof - h;
             if(t < 0) t = 0;
             t &= ~(MIN_RDELTA - 1);
             if(t <= MIN_RDELTA){
                 *pf &= ~DOUBLE_LEVEL;
                 *(pf + 1) &= ~DOUBLE_LEVEL;
                 SET_TERRAIN(*pf,GET_TERRAIN_TYPE(*(pf + 1)));
                 h = *pa = *(pa + 1);
                 SET_DELTA(*pf,0);
                 SET_DELTA(*(pf + 1),0);
                 }
             else {
                 if(t > MAX_RDELTA) t = MAX_RDELTA;
                 t = (t >> DELTA_SHIFT) - 1;
                 SET_DELTA(*pf,(t & 12) >> 2);
                 SET_DELTA(*(pf + 1),(t & 3));
                 }
             }
         else
             return;
     else
 #ifdef _SURMAP_
         if(ExclusiveLayerMode) return; else
 #endif
         h += delta;
 #ifdef _SURMAP_
     if(LandBounded){
 #endif
         if(h < 0) h = 0;
         else if(h > 255) h = 255;
 #ifdef _SURMAP_
         }
     else {
         if(h < 0) h += 256;
         else if(h > 255) h -= 256;
         }
     if(h < MiniLevel) h = MiniLevel;
     if(h > MaxiLevel) h = MaxiLevel;
 #endif
 //  SET_DOWN_ALT(pf,h,pa0,x);
     *pa = h;
 #ifdef _SURMAP_
     if(MosaicToggle && mosaicBMP.mode == 2){
         int t = mosaicBMP.getType(x,y);
         if(t >= 0) SET_REAL_DOWNTERRAIN(pf,(t%TERRAIN_MAX) << TERRAIN_OFFSET,x);
         }
     else if(surf) if(CurrentTerrain != -1) SET_REAL_DOWNTERRAIN(pf,CurrentTerrain << TERRAIN_OFFSET,x);
 #endif
 #ifndef TERRAIN16
     if(h < FloodLvl[y >> WPART_POWER]){
         uchar* pfN = pa0 + H_SIZE;
         int xx = XCYCL(x - 1);
         if(GET_REAL_DOWNTERRAIN_TYPE(pfN + xx,xx) == WATER_TERRAIN){ SET_REAL_DOWNTERRAIN(pf,WATER_TERRAIN,x); return; }
         xx = XCYCL(x + 1);
         if(GET_REAL_DOWNTERRAIN_TYPE(pfN + xx,xx) == WATER_TERRAIN){ SET_REAL_DOWNTERRAIN(pf,WATER_TERRAIN,x); return; }
         int yy = YCYCL(y - 1);
         pfN = lt[yy];
         if(pfN){
             pfN += H_SIZE + x;
             if(GET_REAL_DOWNTERRAIN_TYPE(pfN,x) == WATER_TERRAIN){ SET_REAL_DOWNTERRAIN(pf,WATER_TERRAIN,x); return; }
             }
         yy = YCYCL(y + 1);
         pfN = lt[yy];
         if(pfN){
             pfN += H_SIZE + x;
             if(GET_REAL_DOWNTERRAIN_TYPE(pfN,x) == WATER_TERRAIN){ SET_REAL_DOWNTERRAIN(pf,WATER_TERRAIN,x); return; }
             }
         }
     else {
         if(GET_REAL_DOWNTERRAIN_TYPE(pf,x) == WATER_TERRAIN)
             SET_REAL_DOWNTERRAIN(pf,MAIN_TERRAIN,x);
         }
 #endif
 }
References ActiveTerrain, CurrentTerrain, DELTA_SHIFT, DOUBLE_LEVEL, ExclusiveLayerMode, FloodLvl, GET_DOWN_ALT(), GET_REAL_DOWNTERRAIN(), GET_REAL_DOWNTERRAIN_TYPE(), GET_TERRAIN_TYPE, H_SIZE, LandBounded, MAIN_TERRAIN, MAX_RDELTA, MaxiLevel, MIN_RDELTA, MiniLevel, pf, SET_DELTA, SET_REAL_DOWNTERRAIN(), SET_TERRAIN, TERRAIN_MAX, TERRAIN_OFFSET, TunnelProof, vMap, WATER_TERRAIN, WPART_POWER, XCYCL, and YCYCL.
Referenced by DrawMechosWheelDown(), and pixSet().
pixSet()
void pixSet (int x, int y, int delta, int surf = 1)
 {
 std::cout<<"pixSet"<<std::endl;
     if(!delta) return;
 #ifdef _SURMAP_
     if(RenderingLayer == DOWN_LAYER){
         pixDownSet(x,y,delta,surf);
         return;
         }
 #endif
     uchar** lt = vMap -> lineT;
     uchar* pa = lt[y];
     if(!pa){
 #ifdef _SURMAP_
         vMap -> increase(y,y);
         pa = lt[y];
 #else
         return;
 #endif
         }
     uchar* pa0 = pa;
     pa += x;
     uchar* pf = pa + H_SIZE;
     int h = GET_UP_ALT(pf,*pa,pa0,x),xx;
 #ifdef _SURMAP_
     if(surf) if(!ActiveTerrain[GET_REAL_TERRAIN(pf,x)]) return;
     if(h < MiniLevel || h > MaxiLevel) return;
     if(MosaicToggle && mosaicBMP.mode <= 1) delta = mosaicBMP.getDelta(x,y,delta);
 #endif
     if(IS_DOUBLE(*pf))
         if(x & 1){
             h += delta;
             if((int)*(pa - 1) + (((GET_DELTA(*(pf - 1)) << 2) + GET_DELTA(*pf) + 1) << DELTA_SHIFT) >= h){
                 *pf &= ~DOUBLE_LEVEL;
                 *(pf - 1) &= ~DOUBLE_LEVEL;
 #ifdef _SURMAP_
                 if(surf && CurrentTerrain != -1){
                     SET_TERRAIN(*pf,CurrentTerrain << TERRAIN_OFFSET);
                     SET_TERRAIN(*(pf - 1),CurrentTerrain << TERRAIN_OFFSET);
                     }
                 else
 #endif
                     SET_TERRAIN(*pf,GET_TERRAIN_TYPE(*(pf - 1)));
                 xx = XCYCL(x + 1);
                 h = *pa = (*(pa - 1) + GET_DOWN_ALT(pa0 + xx + H_SIZE,*(pa0 + xx),pa0,xx)) >> 1;
                 SET_DELTA(*pf,0);
                 SET_DELTA(*(pf - 1),0);
 //              *(vMap -> lineTcolor[y] + x - 1) = COL1;
 //              *(vMap -> lineTcolor[y] + x) = COL1;
                 }
             }
         else
             return;
     else
 #ifdef _SURMAP_
         if(ExclusiveLayerMode) return; else
 #endif
         h += delta;
 #ifdef _SURMAP_
     if(LandBounded){
 #endif
         if(h < 0) h = 0;
         else if(h > 255) h = 255;
 #ifdef _SURMAP_
         }
     else {
         if(h < 0) h += 256;
         else if(h > 255) h -= 256;
         }
     if(h < MiniLevel) h = MiniLevel;
     if(h > MaxiLevel) h = MaxiLevel;
 #endif
 //  SET_UP_ALT(pf,h,pa0,x);
     *pa = h;
 //  *(vMap -> lineTcolor[y] + x) = COL1;
 #ifdef _SURMAP_
     if(MosaicToggle && mosaicBMP.mode == 2){
         int t = mosaicBMP.getType(x,y);
         if(t >= 0) SET_REAL_TERRAIN(pf,(t%TERRAIN_MAX) << TERRAIN_OFFSET,x);
         }
     else if(surf) if(CurrentTerrain != -1) SET_REAL_TERRAIN(pf,CurrentTerrain << TERRAIN_OFFSET,x);
 #endif
 #ifndef TERRAIN16
     if(h < FloodLvl[y >> WPART_POWER]){
         uchar* pfN = pa0 + H_SIZE;
         int xx = XCYCL(x - 1);
         if(GET_REAL_TERRAIN_TYPE(pfN + xx,xx) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
         xx = XCYCL(x + 1);
         if(GET_REAL_TERRAIN_TYPE(pfN + xx,xx) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
         int yy = YCYCL(y - 1);
         pfN = lt[yy];
         if(pfN){
             pfN += H_SIZE + x;
             if(GET_REAL_TERRAIN_TYPE(pfN,x) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
             }
         yy = YCYCL(y + 1);
         pfN = lt[yy];
         if(pfN){
             pfN += H_SIZE + x;
             if(GET_REAL_TERRAIN_TYPE(pfN,x) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
             }
         }
     else {
         if(GET_REAL_TERRAIN_TYPE(pf,x) == WATER_TERRAIN)
             SET_REAL_TERRAIN(pf,MAIN_TERRAIN,x);
         }
 #endif
 }
References ActiveTerrain, CurrentTerrain, DELTA_SHIFT, DOUBLE_LEVEL, DOWN_LAYER, ExclusiveLayerMode, FloodLvl, GET_DELTA, GET_DOWN_ALT(), GET_REAL_TERRAIN(), GET_REAL_TERRAIN_TYPE(), GET_TERRAIN_TYPE, GET_UP_ALT(), H_SIZE, IS_DOUBLE, LandBounded, MAIN_TERRAIN, MaxiLevel, MiniLevel, pf, pixDownSet(), RenderingLayer, SET_DELTA, SET_REAL_TERRAIN(), SET_TERRAIN, TERRAIN_MAX, TERRAIN_OFFSET, vMap, WATER_TERRAIN, WPART_POWER, XCYCL, and YCYCL.
pixSetR()
void pixSetR (int x, int y, int delta, int surf = 1)
Render !!!
 {
 //std::cout<<"pixSetR"<<std::endl;
     if(!delta) return;
     uchar** lt = vMap -> lineT;
     uchar* pa = lt[y];
 // Render
     uchar* pc = vMap -> lineTcolor[y];
     uchar* pc0=pc;
     pc += x;
 //
     if(!pa){
         return;
         }
     uchar* pa0 = pa;
     pa += x;
     uchar* pf = pa + H_SIZE;
     int h = GET_UP_ALT(pf,*pa,pa0,x),xx;
     if(IS_DOUBLE(*pf))
         if(x & 1){
             h += delta;
             if((int)*(pa - 1) + (((GET_DELTA(*(pf - 1)) << 2) + GET_DELTA(*pf) + 1) << DELTA_SHIFT) >= h){
                 *pf &= ~DOUBLE_LEVEL;
                 *(pf - 1) &= ~DOUBLE_LEVEL;
                     SET_TERRAIN(*pf,GET_TERRAIN_TYPE(*(pf - 1)));
                 xx = XCYCL(x + 1);
                 h = *pa = (*(pa - 1) + GET_DOWN_ALT(pa0 + xx + H_SIZE,*(pa0 + xx),pa0,xx)) >> 1;
                 SET_DELTA(*pf,0);
                 SET_DELTA(*(pf - 1),0);
 //              *(vMap -> lineTcolor[y] + x - 1) = COL1;
 //              *(vMap -> lineTcolor[y] + x) = COL1;
                 }
             }
         else
             return;
     else
         h += delta;
         if(h < 0) h = 0;
         else if(h > 255) h = 255;
 //  SET_UP_ALT(pf,h,pa0,x);
     *pa = h;
 //  *(vMap -> lineTcolor[y] + x) = COL1;
 #ifndef TERRAIN16
     if(h < FloodLvl[y >> WPART_POWER]){
         uchar* pfN = pa0 + H_SIZE;
         int xx = XCYCL(x - 1);
         if(GET_REAL_TERRAIN_TYPE(pfN + xx,xx) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
         xx = XCYCL(x + 1);
         if(GET_REAL_TERRAIN_TYPE(pfN + xx,xx) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
         int yy = YCYCL(y - 1);
         pfN = lt[yy];
         if(pfN){
             pfN += H_SIZE + x;
             if(GET_REAL_TERRAIN_TYPE(pfN,x) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
             }
         yy = YCYCL(y + 1);
         pfN = lt[yy];
         if(pfN){
             pfN += H_SIZE + x;
             if(GET_REAL_TERRAIN_TYPE(pfN,x) == WATER_TERRAIN){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); return; }
             }
         }
     else {
         if(GET_REAL_TERRAIN_TYPE(pf,x) == WATER_TERRAIN)
             SET_REAL_TERRAIN(pf,MAIN_TERRAIN,x);
         }
 #endif
     uchar types=(*pf&TERRAIN_MASK)>>TERRAIN_OFFSET;
     if(IS_DOUBLE(*pf)){
         if (x&1){
         uchar lx_h =*(pa0+XCYCL(x-2));
         uchar c_h =*pa;
         uchar rx_h =*(pa0+XCYCL(x+2));
         if (rx_h-3>=h) *pf|=*(pf-1)|=SHADOW_MASK;
         if (*pf&SHADOW_MASK){
         *pc=*(pc-1)=palCLR[types][256+((lightCLR[types][255-(c_h-rx_h)]-((255-c_h)>>H_CORRECTION))>>1)];
         }
         else *pc=*(pc-1)=palCLR[types][256+(lightCLR[types][255-(c_h-rx_h)]-((255-c_h)>>H_CORRECTION))];
         //2pix
         pf=pa0+XCYCL(x-2)+H_SIZE;
         pc=pc0+XCYCL(x-2);
         if (h-3>=lx_h) *pf|=*(pf-1)|=SHADOW_MASK;
         if (*pf&SHADOW_MASK){
         *pc=*(pc-1)=palCLR[types][256+((lightCLR[types][255-(lx_h-c_h)]-((255-lx_h)>>H_CORRECTION))>>1)];
         }
         else *pc=*(pc-1)=palCLR[types][256+(lightCLR[types][255-(lx_h-c_h)]-((255-lx_h)>>H_CORRECTION))];
         }
     } else {
         uchar llx_h=*(pa0+XCYCL(x-2));
         uchar lx_h =*(pa0+XCYCL(x-1));
         uchar c_h =*pa;
         uchar rx_h =*(pa0+XCYCL(x+1));
         if (rx_h-1-(x&1)>=h) {
             *pf|=SHADOW_MASK;
         }
         if (*pf&SHADOW_MASK){
             *pc=palCLR[types][256+((lightCLR[types][255-(lx_h-rx_h)]-((255-c_h)>>H_CORRECTION))>>1)];
         } else {
             *pc=palCLR[types][256+(lightCLR[types][255-(lx_h-rx_h)]-((255-c_h)>>H_CORRECTION))];
         }
         //2pix
         pf=pa0+XCYCL(x-1)+H_SIZE;
         pc=pc0+XCYCL(x-1);
         if (h-1-((x-1)&1)>=llx_h) *pf|=SHADOW_MASK;
         if (*pf&SHADOW_MASK){
         *pc=palCLR[types][256+((lightCLR[types][255-(llx_h-c_h)]-((255-lx_h)>>H_CORRECTION))>>1)];
         }
         else *pc=palCLR[types][256+(lightCLR[types][255-(llx_h-c_h)]-((255-lx_h)>>H_CORRECTION))];
     }
 }
References DELTA_SHIFT, DOUBLE_LEVEL, FloodLvl, GET_DELTA, GET_DOWN_ALT(), GET_REAL_TERRAIN_TYPE(), GET_TERRAIN_TYPE, GET_UP_ALT(), H_CORRECTION, H_SIZE, IS_DOUBLE, lightCLR, MAIN_TERRAIN, palCLR, pf, SET_DELTA, SET_REAL_TERRAIN(), SET_TERRAIN, SHADOW_MASK, TERRAIN_MASK, TERRAIN_OFFSET, vMap, WATER_TERRAIN, WPART_POWER, XCYCL, and YCYCL.
Referenced by DrawMechosWheelUp().
regDownRender()
void regDownRender (int x0, int y0, int x1, int y1, int changed = 1)
Referenced by regRender().
regRender()
void regRender (int x0, int y0, int x1, int y1, int changed = 1)
 {
 #ifdef _SURMAP_
     if(RenderingLayer == DOWN_LAYER){
         regDownRender(LowX,LowY,HiX,HiY,changed);
         return;
         }
 #endif
     LowX = XCYCL(LowX);
     HiX = XCYCL(HiX);
     LowY = YCYCL(LowY);
     HiY = YCYCL(HiY);
     LowX &= ~1;
     HiX |= 1;
     int SizeY = (LowY == HiY) ? V_SIZE : YCYCL(HiY - LowY);
     int SizeX = (0 == XCYCL(HiX - LowX)) ? H_SIZE : XCYCL(HiX - LowX);
     int BackScanLen = 0;
     int j;
     for(j = 0;j < SizeY;j++){
         const int y = YCYCL(j + LowY);
         BYTE* pa0 = vMap -> lineT[y];
         BYTE* pc0 = vMap -> lineTcolor[y];
         if(!pa0) return;
         if(changed) vMap -> changedT[y] = 1;
         MEMSET(shadowParent,0,(((SizeX*SHADOWDEEP) >> POSPOWER) + 4*MAX_ALT));
 //      MEMSET(shadowParent,0,map_size_x);
         int hC = MAX_ALT;
         int LastStep = (H_SIZE - 1 - HiX) * SHADOWDEEP;
         LastStep -= ((LastStep >> POSPOWER) - MAX_ALT) << POSPOWER;
         //
         PreStage(LastStep,HiX,pa0,hC,shadowParent + MAX_ALT);
         //
         int x = HiX;
         BYTE* grid = shadowParent + MAX_ALT + MAX_ALT;
         int MaxAlt = 0;
         MainStage(pa0,hC,pc0,SizeX,x,grid,MaxAlt);
         //
         {
         x |= 1;
         BYTE* pa = pa0 + x;
         BYTE* pf = pa + H_SIZE;
         BYTE* pc = pc0 + x;
         BYTE* palCLRlast;
         BYTE* lightCLRlast;
         BYTE typeC = 0xFF;
         int MaxPossibleAlt = MAX_ALT;
         unsigned bNeedScan = 1;
         while(bNeedScan && MaxPossibleAlt >= 0){
             bNeedScan = 0;
             if(*pf & DOUBLE_LEVEL){
                 const BYTE lxVal = *pa;
                 const BYTE rxVal = *(pa0 + XCYCL(x + 2));
                 const BYTE h = *pa;
                 const BYTE dh = *(pa - 1);
                 const BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
 #ifndef TERRAIN16
                 const BYTE level = type ? h : FloodLEVEL;
 #else
                 const BYTE level = h;
 #endif
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = palCLR[type];
                     lightCLRlast = lightCLR[type];
                     }
                 grid += 3;
                 hC -= 3;
                 MaxAlt -= 3;
                 MaxPossibleAlt -= 3;
                 if(dh < MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *(pf - 1) |= SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> 1)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *(pf - 1) &= ~SHADOW_MASK;
                     *(pc - 1) = *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
 #ifndef TERRAIN16
                 if(*(grid + SHADOWHEIGHT + level)){
                     *pf |= OBJSHADOW;
                     *(pf - 1) |= OBJSHADOW;
                     }
                 else {
                     *pf &= ~OBJSHADOW;
                     *(pf - 1) &= ~OBJSHADOW;
                     }
 #endif
                 pa--; pf--; pc--;
                 if(*pf & SHADOW_MASK) bNeedScan = 1;
                 if(dh > hC){
                     MEMSET(grid + hC,1,dh - hC);
                     hC = dh;
                     }
                 MEMSET(grid + h - SS_WIDTH,1,SS_WIDTH + 1);
                 }
             else {
                 BYTE lxVal = *(pa - 1);
                 BYTE rxVal = *(pa0 + XCYCL(x + 1));
                 BYTE h = *pa;
                 BYTE type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
 #ifndef TERRAIN16
                 BYTE level = type ? h : FloodLEVEL;
 #else
                 BYTE level = h;
 #endif
                 grid += 1;
                 hC -= 1;
                 MaxAlt -= 1;
                 MaxPossibleAlt -= 1;
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = palCLR[type];
                     lightCLRlast = lightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> 1)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
 #ifndef TERRAIN16
                 if(*(grid + SHADOWHEIGHT + level))
                     *pf |= OBJSHADOW;
                 else
                     *pf &= ~OBJSHADOW;
 #endif
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 pa--; pf--; pc--;
                 rxVal = h;
                 h = lxVal;
                 lxVal = *(pa0 + XCYCL(x - 2));
                 grid += 2;
                 hC -= 2;
                 MaxAlt -= 2;
                 MaxPossibleAlt -= 2;
                 type = (*pf & TERRAIN_MASK) >> TERRAIN_OFFSET;
 #ifndef TERRAIN16
                 level = type ? h : FloodLEVEL;
 #else
                 level = h;
 #endif
                 if(type != typeC){
                     typeC = type;
                     palCLRlast = palCLR[type];
                     lightCLRlast = lightCLR[type];
                     }
                 if(h <= MaxAlt || (*pf & SHADOW_MASK)) bNeedScan = 1;
                 if(*(grid + level)){
                     *pf |= SHADOW_MASK;
                     *pc = palCLRlast[256 + ((lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)) >> 1)];
                     }
                 else {
                     *pf &= ~SHADOW_MASK;
                     *pc = palCLRlast[256 + lightCLRlast[255 - (lxVal - rxVal)] - ((255 - h) >> H_CORRECTION)];
                     }
 #ifndef TERRAIN16
                 if(*(grid + SHADOWHEIGHT + level))
                     *pf |= OBJSHADOW;
                 else
                     *pf &= ~OBJSHADOW;
 #endif
                 if(h > hC){
                     MEMSET(grid + hC,1,h - hC);
                     hC = h;
                     }
                 }
             if(x == 1){
                 x = H_SIZE - 1;
                 pa = pa0 + x;
                 pf = pa + H_SIZE;
                 pc = pc0 + x;
                 }
             else {
                 x = XCYCL(x - 2);
                 pa--; pf--; pc--;
                 }
             }
         const int CurrScanLenght = XCYCL(LowX - x);
         if(CurrScanLenght > BackScanLen) BackScanLen = CurrScanLenght;
         }
     }
 }
References DOUBLE_LEVEL, DOWN_LAYER, FloodLEVEL, H_CORRECTION, H_SIZE, level, lightCLR, MainStage(), MAX_ALT, MEMSET, OBJSHADOW, palCLR, pf, POSPOWER, PreStage(), regDownRender(), RenderingLayer, SHADOW_MASK, SHADOWDEEP, SHADOWHEIGHT, shadowParent, SS_WIDTH, TERRAIN_MASK, TERRAIN_OFFSET, V_SIZE, vMap, XCYCL, and YCYCL.
Referenced by ClearBarell(), dastPutSandOnMapAlt(), Object::destroy_double_level(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), DestroySmoothCheck(), DestroySpot(), Object::ground_pressing(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), dastPoly3D::make_mole(), RadialRender(), regRenderSimple(), MLFrame::Render(), and MobileLocation::setPhase().
regRenderSimple()
void regRenderSimple (int x0, int y0, int x1, int y1)
 {
     regRender(x0,y0,x1,y1);
 }
References regRender().
Referenced by DrawMechosWheelDown().
regSet()
void regSet (int x0, int y0, int x1, int y1, int dry, int surf = 1)
 {
 //std::cout<<"regSet"<<std::endl;
     int i;
     uchar** lt = vMap -> lineT;
     uchar* pa0,*pa,*pf,*pf0;
     x0 = XCYCL(x0);
     x1 = XCYCL(x1 + 1);
     y0 = YCYCL(y0);
     y1 = YCYCL(y1);
     int sx = getDeltaX(x1,x0) + 3;
     int x0l = XCYCL(x0 - 1);
     int x0r = XCYCL(x1 + 1);
     int x,y;
 #ifndef TERRAIN16
     uchar *pfd,*pfd0;
     uchar* uw = waterBuf[0],*w = waterBuf[1],*dw = waterBuf[2];
     memset(dw,0,sx);
     pa0 = lt[YCYCL(y0 - 1)];
     if(pa0){
         pf = (pf0 = pa0 + H_SIZE) + x0l;
         pfd = (pfd0 = lt[y0] + H_SIZE) + x0l;
         for(i = 0,x = x0l;i < sx;i++,x = XCYCL(x + 1),pf++,pfd++){
             if(!x){ pf = pf0; pfd = pfd0; }
             *uw++ = IS_WATER(*pf);
             *w++ = IS_WATER(*pfd);
             }
         }
     uw = waterBuf[0] + 1;
     w = waterBuf[1] + 1;
     int fld = FloodLEVEL,ind = 0;
 #endif
     for(y = y0;y != y1;y = YCYCL(y + 1)){
         pa = (pa0 = lt[y]) + x0;
         if(!pa0) return;
         pf0 = pa0 + H_SIZE;
         pf = pa + H_SIZE;
 #ifndef TERRAIN16
         pfd0 = lt[YCYCL(y + 1)];
         if(!pfd0) pfd0 = pf0;
         else pfd0 += H_SIZE;
         pfd = pfd0 + x0;
         dw[sx - 1] = IS_WATER(*(pfd0 + x0r));
         *dw++ = IS_WATER(*(pfd0 + x0l));
 #endif
         for(x = x0;x != x1;x = XCYCL(x + 1),pa++,pf++){
             if(!x){
                 pa = pa0; pf = pf0;
 #ifndef TERRAIN16
                 pfd = pfd0;
 #endif
                 }
             if((*pf & DOUBLE_LEVEL) && (x & 1)){
                 if((int)*(pa - 1) + (((GET_DELTA(*(pf - 1)) << 2) + GET_DELTA(*pf) + 1) << DELTA_SHIFT) >= *pa){
                     *pf &= ~DOUBLE_LEVEL;
                     *(pf - 1) &= ~DOUBLE_LEVEL;
                     SET_TERRAIN(*pf,GET_TERRAIN_TYPE(*(pf - 1)));
                     *pa = (*(pa - 1) + (int)*(pa0 + XCYCL(x + 1))) >> 1;
                     SET_DELTA(*pf,0);
                     SET_DELTA(*(pf - 1),0);
                     }
                 }
 #ifdef _SURMAP_
             if(surf) if(CurrentTerrain != -1) SET_REAL_TERRAIN(pf,CurrentTerrain << TERRAIN_OFFSET,x);
 #endif
 #ifndef TERRAIN16
             *dw = IS_WATER(*pfd);
             if(*pa >= fld){
                 if(*w){ SET_REAL_TERRAIN(pf,dry,x); *w = 0; }
                 }
             else {
                 if(*uw){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); *w = 1; }
                 else if(*dw){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); *w = 1; }
                 else if(*(w - 1)){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); *w = 1; }
                 else if(*(w + 1)){ SET_REAL_TERRAIN(pf,WATER_TERRAIN,x); *w = 1; }
                 }
             uw++;w++;dw++;pfd++;
 #endif
             }
 #ifndef TERRAIN16
         if(++ind == 3) ind = 0;
         uw = waterBuf[ind] + 1;
         if(++ind == 3) ind = 0;
         w = waterBuf[ind] + 1;
         if(++ind == 3) ind = 0;
         dw = waterBuf[ind];
         if(++ind == 3) ind = 0;
 #endif
         }
 }
References getDeltaX(), pf, vMap, XCYCL, and YCYCL.
Referenced by ClearBarell(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), DestroySmoothCheck(), DestroySpot(), RadialRender(), and MobileLocation::setPhase().
SET_DOWN_ALT()
void SET_DOWN_ALT (uchar * type, uchar h, uchar * pa0, int x) inline
 {
     if(*type & DOUBLE_LEVEL){ if(!(x & 1)) *(pa0 + x) = h; }
     else *(pa0 + x) = h;
 }
References DOUBLE_LEVEL.
SET_REAL_DOWNTERRAIN()
int SET_REAL_DOWNTERRAIN (uchar * type, uchar newtype, int x) inline
 {
     if(*type & DOUBLE_LEVEL){
         if(!(x & 1)){ SET_TERRAIN(*type,newtype); return 1; }
         }
     else {
         SET_TERRAIN(*type,newtype);
         return 1;
         }
     return 0;
 }
References DOUBLE_LEVEL, and SET_TERRAIN.
Referenced by pixDownSet().
SET_REAL_TERRAIN()
int SET_REAL_TERRAIN (uchar * type, uchar newtype, int x) inline
 {
     if(*type & DOUBLE_LEVEL){
         if(x & 1){ SET_TERRAIN(*type,newtype); return 1; }
         }
     else {
         SET_TERRAIN(*type,newtype);
         return 1;
         }
     return 0;
 }
References DOUBLE_LEVEL, and SET_TERRAIN.
Referenced by pixSet(), and pixSetR().
SET_UP_ALT()
void SET_UP_ALT (uchar * type, uchar h, uchar * pa0, int x) inline
 {
     if(*type & DOUBLE_LEVEL){ if(x & 1) *(pa0 + x) = h; }
     else *(pa0 + x) = h;
 }
References DOUBLE_LEVEL.
Variable Documentation
CLR_MAX
const int CLR_MAX = 2*CLR_MAX_SIDE + 1
CLR_MAX_SIDE
const int CLR_MAX_SIDE = 255
H_CORRECTION
const uchar H_CORRECTION = 1
lightCLR
uchar* lightCLR[TERRAIN_MAX] extern
Referenced by LINE_render(), MainStage(), MainStage2(), pixSetR(), regRender(), and regRender2().
palCLR
uchar palCLR[TERRAIN_MAX][2 *256] extern
Referenced by LINE_render(), MainStage(), MainStage2(), pixSetR(), regRender(), and regRender2().