Vangers: src/road.cpp File Reference
road.cpp File Reference
#include "zmod_client.h"
#include "global.h"
#include "lang.h"
#include "_xsound.h"
#include "runtime.h"
#include "sqexp.h"
#include "backg.h"
#include "xjoystick.h"
#include "network.h"
#include "3d/3d_math.h"
#include "3d/3dgraph.h"
#include "3d/3dobject.h"
#include "3d/parser.h"
#include "actint/item_api.h"
#include "units/uvsapi.h"
#include "terra/world.h"
#include "terra/vmap.h"
#include "terra/render.h"
#include "particle/particle.h"
#include "particle/light.h"
#include "particle/partmap.h"
#include "particle/df.h"
#include "uvs/univang.h"
#include "uvs/screen.h"
#include "uvs/diagen.h"
#include "dast/poly3d.h"
#include "units/track.h"
#include "units/hobj.h"
#include "units/moveland.h"
#include "units/effect.h"
#include "units/items.h"
#include "units/sensor.h"
#include "units/mechos.h"
#include "terra/cpuid.h"
#include "palette.h"
#include "sound/hsound.h"
#include "video/winvideo.h"
Macros
#define _ROAD_
#define SCREENSHOT
#define ISCREEN
#define SHOW_LOGOS
#define SHOW_IMAGES
#define DBGCHECK
#define RANDOMIZE
#define MEMSTAT(a)
#define SLOPE_MAX Pi/6
#define MAX_ZOOM 384
#define MIN_ZOOM 128
Functions
void iPreInitFirst ()
void ShowImageMousePress (int fl, int x, int y)
void ShowImageKeyPress (SDL_Event *k)
void ComlineAnalyze (int argc, char **argv)
void restore (void)
int NetInit (ServerFindChain *p)
void camera_reset ()
int sqrint (int x)
void showF (int x0, int y0, int x1, int y1)
void showCell (void)
void showRadar (void)
void costab (void)
void buildField (void)
void MechPrepare (void)
void hObjPrepare (void)
void cycleTor (int &x, int &y)
void preCALC (void)
char * GetTargetName (const char *name)
void shotFlush (void)
void LoadingMessage (int flush=0)
void vMapInit (void)
void theEND (void)
void ilandPrepare (void)
void aciSetCameraMenu (void)
void calc_view_factors ()
void gameQuant (void)
void SetupPath (void)
char * getRC (void)
void GameTimerON_OFF (void)
void uvsRestoreVanger (void)
void MLload (void)
int MLquant (void)
void aci_LocationQuantPrepare (void)
void aci_LocationQuantFinit (void)
void KeyCenter (SDL_Event *key)
int distance (int, int)
int ibsout (int, int, void *, void *)
int sdlEventToCode (SDL_Event *event)
void showModal (char *fname, float reelW, float reelH, float screenW, float screenH)
int xtInitApplication (void)
void xtDoneApplication (void)
void PalettePrepare (void)
void camera_quant (int X, int Y, int Turn, double V_abs)
void creat_poster_pixels_copy (SDL_Surface *src, SDL_Rect *srcrect, SDL_Surface *dst, SDL_Rect *dstrect)
void creat_poster ()
void PrintError (char *error, char *msg)
void set_screen (int Dx, int Dy, int mode, int xcenter, int ycenter)
void rtoSetNextID (int id, int next)
void rtoSetFlag (int id, int fl)
void rtoClearFlag (int id, int fl)
Variables
XStream fout
uchar * iscrPal
int MainRqCounter
int AuxRqCounter
int RQ_THREAD_COUNT
int SlopeQualityFactor
int camera_zmin
int camera_slope_min
int stop_camera
int camera_moving_xy_enable
int camera_moving_z_enable
int camera_slope_enable
int camera_rotate_enable
int EngineNoise
int BackgroundSound
int aciGroundPressingEnabled
int aciKeyboardLocked
int SoundVolumePanning
int NumHumanModel
int EffectInUsePriory
int EffectInUse
bool XGR_FULL_SCREEN
char * host_name = 0
int host_port = DEFAULT_SERVER_PORT
int network_log = 0
const int FPS_PERIOD = 50
int fps_frame
int fps_start
char fps_string [20]
int stop_all_except_me = 0
int ErrHExcept = 1
int RAM16
int emode
int vSoundON
int vSoundOFF
int message_mode = 0
int setTimerLog = 1
int GameOverTrigger = -1
int page
clock_t _Timer_
int frame
int Quit = 1
int Dead
XBuffer msg_buf (16000)
int view_lock = 0
int debug_view = 0
int StandLog
int loadingStatus = 1
int GameQuantReturnValue = 0
int XSIDE = 200
int YSIDE = 170
int XSIZE = 2*XSIDE + 1
int YSIZE = 2*YSIDE + 1
int MuteLog = 0
int Verbose
int DepthShow
int SkipIntro = 0
int PalIterLock = 0
unsigned char * palbuf
unsigned char * palbufA
unsigned char * palbufC
unsigned char * palbufOrg
unsigned char * palbufInt
unsigned char * palbufBlack
sqFont sysfont
sqFont zchatfont
int * SI
int * CO
int zoom_delta
int zoom_threshold
int videoMode = 1
int beebos
int idOS
int inHighPriority
const char * roadFNTname = "road.fnt"
const char * zchatFNTname = "zfont.fnt"
unsigned RNDVAL = 83
unsigned realRNDVAL = 83
int Geo = 0
int Redraw = 1
int Pause = 0
int FirstDraw = 1
int speed_correction_enabled = 1
int prev_frame_time = 0
iGameMap * curGMap
const char * mapFName = "wrlds.dat"
int ColorShow = 1
int SkipShow = 1
int WorldPrm
int shotNum
int ExclusiveLog = 1
int DIBLog = 0
int MMXsuppress
int SkipCD
int CurrentWorld = 0
int inTRall
int TimerMode = 1
int * AVI_index
int TotalDrawFlag = 1
int StartMainQuantFlag = 0
int RecorderMode = 0
char * RecorderName = NULL
int ShowImageMouseFlag = 0
int ShowImageKeyFlag = 0
const char * ErrorVideoMss = "Error video initialization"
const char * AVInotFound = "Error video initialization"
const char * AVInotFoundMSS = "Please ensure that the VANGERS CD-ROM is in the drive!"
const char * nVER = "Patch 4.20"
sWinVideo winVideo
int activeWTRACK
int light_modulation
int WorldLightParam [WORLD_MAX][3]
int CurrentWorldLightParam
Macro Definition Documentation
_ROAD_
#define _ROAD_
DBGCHECK
#define DBGCHECK
ISCREEN
#define ISCREEN
MAX_ZOOM
#define MAX_ZOOM 384
MEMSTAT
#define MEMSTAT (a)
MIN_ZOOM
#define MIN_ZOOM 128
RANDOMIZE
#define RANDOMIZE
SCREENSHOT
#define SCREENSHOT
SHOW_IMAGES
#define SHOW_IMAGES
SHOW_LOGOS
#define SHOW_LOGOS
SLOPE_MAX
#define SLOPE_MAX Pi/6
Function Documentation
aci_LocationQuantFinit()
void aci_LocationQuantFinit (void)
 {
     iScrQuantFinit();
     aScrDisp -> i_finit();
     aciKillLinks();
     aScrDisp -> flags &= ~AS_FULL_REDRAW;
     aciAutoRun = iGetOptionValue(iAUTO_ACCELERATION);
 }
References aciKillLinks(), aScrDisp, and iScrQuantFinit().
Referenced by EscaveOutRTO::Finit(), and FirstEscaveOutRTO::Finit().
aci_LocationQuantPrepare()
void aci_LocationQuantPrepare (void)
 {
     aciSpeechBegLocked = aciSpeechEndLocked = 0;
     aciSpeechStarted = aciEndSpeech = 0;
     aciEscaveDead = aciEscaveEmpty = 0;
     aciBreathFlag = 0;
     aScrDisp -> i_init();
     iScrQuantPrepare();
 }
References aciBreathFlag, aciEndSpeech, aciEscaveDead, aciEscaveEmpty, aciSpeechBegLocked, aciSpeechEndLocked, aciSpeechStarted, aScrDisp, and iScrQuantPrepare().
Referenced by FirstEscaveRTO::Init(), and EscaveRTO::Init().
aciSetCameraMenu()
void aciSetCameraMenu (void)
 {
     aciBitmapMenu* m;
     aciBitmapMenuItem* p;
     m = aScrDisp -> get_bmenu(BMENU_CAMERAS_MENU);
     if(m){
         p = (aciBitmapMenuItem*)m -> items -> last;
         while(p){
             switch(p -> ID){
                 case BMENU_ITEM_ROT:
                     p -> curState = camera_rotate_enable;
                     iScrOpt[iCAMERA_TURN]->SetValueINT(camera_rotate_enable);
                     break;
                 case BMENU_ITEM_ZOOM:
                     p -> curState = camera_moving_xy_enable;
                     iScrOpt[iCAMERA_SCALE]->SetValueINT(camera_moving_xy_enable);
                     break;
                 case BMENU_ITEM_PERSP:
                     p -> curState = camera_slope_enable;
                     iScrOpt[iCAMERA_SLOPE]->SetValueINT(camera_slope_enable);
                     break;
             }
             p = (aciBitmapMenuItem*)p -> prev;
         }
     }
     m -> flags |= BM_REBUILD;
     iSaveData();
 }
References aScrDisp, BMENU_CAMERAS_MENU, BMENU_ITEM_PERSP, BMENU_ITEM_ROT, BMENU_ITEM_ZOOM, camera_moving_xy_enable, camera_rotate_enable, camera_slope_enable, iCAMERA_SCALE, iCAMERA_SLOPE, iCAMERA_TURN, iScrOpt, prev, and iScreenOption::SetValueINT().
Referenced by KeyCenter().
buildField()
void buildField (void)
calc_view_factors()
void calc_view_factors ()
 {
     //if(!(XRec.flags & (XRC_RECORD_MODE | XRC_PLAY_MODE)) && prev_frame_time)
     //Stalkerg
     if((speed_correction_enabled | NetworkON) && prev_frame_time){
         int dt = SDL_GetTicks() - prev_frame_time;
         if(dt > 15 && dt < 200) {
             speed_correction_factor = (double)dt*((double)STANDART_FRAME_RATE/1000.)*speed_correction_tau + speed_correction_factor*(1 - speed_correction_tau);
         }
     } else {
         speed_correction_factor = 1;
     }
     //speed_correction_factor = 1;
     //std::cout<<"DT::"<<SDL_GetTicks() - prev_frame_time<<std::endl;
     prev_frame_time = SDL_GetTicks();
     cycleTor(ViewX,ViewY);
     TurnSecY = curGMap -> ysize*TurnSecX/curGMap -> xsize;
     TurnSideX = TurnSecX >> 1;
     TurnSideY = TurnSecY >> 1;
     ViewZ = focus*TurnSecX/curGMap -> xsize;
     ScaleMapFlt = (double)TurnSecX/curGMap -> xsize;
     ScaleMapInvFlt = (double)curGMap -> xsize/TurnSecX;
     ScaleMap = round(ScaleMapFlt*256);
     ScaleMapInv = round(ScaleMapInvFlt*256);
     DepthShow = SlopeAngle < -PI/512;
     ModulatedNORMAL = (double)NORMAL*light_modulation/256.;
     Light = Vector(DBV(ModulatedNORMAL,0,ModulatedNORMAL*SHADOWDEEP/256.).norm(ModulatedNORMAL));
     CurrShadowDirection =  DBV(-Cos(TurnAngle),-Sin(TurnAngle),(double)SHADOWDEEP/256.);
     if(DepthShow){
         A_g2s = DBM(SlopeAngle,X_AXIS)*DBM(TurnAngle,Z_AXIS);
         A_s2g = DBM(-TurnAngle,Z_AXIS)*DBM(-SlopeAngle,X_AXIS);
     } else {
         A_g2s = DBM(TurnAngle,Z_AXIS);
         A_s2g = DBM(-TurnAngle,Z_AXIS);
     }
     A_g2sZ = A_g2s*DBM(1,1,-1,DIAGONAL);
     sinTurnInvFlt = sinTurnFlt = Sin(TurnAngle);
     cosTurnInvFlt =cosTurnFlt = Cos(TurnAngle);
     sinTurnFlt *= ScaleMapInvFlt;
     cosTurnFlt *= ScaleMapInvFlt;
     sinTurnInvFlt *= ScaleMapFlt;
     cosTurnInvFlt *= ScaleMapFlt;
     sinTurn = round(UNIT*sinTurnFlt);
     cosTurn = round(UNIT*cosTurnFlt);
     sinTurnInv = round(UNIT*sinTurnInvFlt);
     cosTurnInv = round(UNIT*cosTurnInvFlt);
     // Inverse factors calculation
     double M_x = A_g2s[0]*focus_flt;
     double N_x = A_g2s[1]*focus_flt;
     double M_y = A_g2s[3]*focus_flt;
     double N_y = A_g2s[4]*focus_flt;
     double M_z = A_g2s[6];
     double N_z = A_g2s[7];
     double H = ViewZ << 16;
     Ha = N_y*H;
     Va = -N_x*H;
     Hb = -M_y*H;
     Vb = M_x*H;
     Oc = M_x*N_y - M_y*N_x;
     Hc = M_y*N_z - M_z*N_y;
     Vc = M_z*N_x - M_x*N_z;
 }
References A_g2s, A_g2sZ, A_s2g, Cos(), cosTurn, cosTurnFlt, cosTurnInv, cosTurnInvFlt, curGMap, CurrShadowDirection, cycleTor(), DepthShow, DIAGONAL, focus, focus_flt, Ha, Hb, Hc, Light, light_modulation, ModulatedNORMAL, NetworkON, NORMAL, Oc, PI, prev_frame_time, round(), ScaleMap, ScaleMapFlt, ScaleMapInv, ScaleMapInvFlt, SHADOWDEEP, Sin(), sinTurn, sinTurnFlt, sinTurnInv, sinTurnInvFlt, SlopeAngle, speed_correction_enabled, speed_correction_factor, speed_correction_tau, STANDART_FRAME_RATE, TurnAngle, TurnSecX, TurnSecY, TurnSideX, TurnSideY, UNIT, Va, Vb, Vc, ViewX, ViewY, ViewZ, X_AXIS, and Z_AXIS.
Referenced by camera_quant(), and iGameMap::change().
camera_quant()
void camera_quant (int X, int Y, int Turn, double V_abs)
{
     if(stop_camera)
         return;
     int t,dx,dy;
     if(!camera_moving_xy_enable) {
         dx = getDistX(X,camera_X_prev);
         dy = getDistY(Y,camera_Y_prev);
         if(dx < 400 && dy < 400) {
             ViewX += dx;
             ViewY += dy;
         } else {
             ViewX = X;
             ViewY = Y;
         }
     }
     dx = getDistX(X,ViewX);
     dy = getDistY(Y,ViewY);
     if(dx > 400 || dy > 400){
         ViewX = X;
         ViewY = Y;
     } else {
         camera_vx += (double)dx*camera_mi * XTCORE_FRAME_NORMAL;
         camera_vx *= camera_drag;
         camera_x += camera_vx * XTCORE_FRAME_NORMAL;
         ViewX += (t = round(camera_x));
         camera_x -= t;
         camera_vy += (double)dy*camera_mi * XTCORE_FRAME_NORMAL;
         camera_vy *= camera_drag;
         camera_y += camera_vy * XTCORE_FRAME_NORMAL;
         ViewY += (t = round(camera_y));
         camera_y -= t;
     }
     if(time_vibration) {
         static int phase_vibration;
         double k = A_vibration*exp(-alpha_vibration*time_vibration);
         double t = oscillar_vibration*(time_vibration + phase_vibration);
         ViewX += round(k*sin(1.276*t)+.8*sin(2.878*t)+0.3*sin(23.876*t)) * XTCORE_FRAME_NORMAL;
         ViewY += round(k*sin(0.981*t)+.8*sin(2.98*t)+0.3*sin(20.82*t)) * XTCORE_FRAME_NORMAL;
         if(time_vibration++ > max_time_vibration) {
             time_vibration = 0;
             phase_vibration = realRND(1367339);
         }
     }
     camera_X_prev = X;
     camera_Y_prev = Y;
     int TurnSecX_old = TurnSecX;
     int z = camera_moving_z_enable ? (V_abs < camera_vmax ? camera_zmin + ((curGMap -> xsize*MAX_ZOOM >> 8) - camera_zmin)*V_abs/camera_vmax : camera_zmax)
                     : camera_zmin;
     camera_vz += (double)(z - TurnSecX)*camera_miz * XTCORE_FRAME_NORMAL;
     //camera_vz -= camera_vz*camera_dragz;
     camera_vz *= camera_dragz*pow(0.97,camera_vz_min/(fabs(camera_vz) + 1e-10));
     camera_z += camera_vz * XTCORE_FRAME_NORMAL;
     TurnSecX += (t = round(camera_z));
     camera_z -= t;
     if(TurnSecX > (t = curGMap -> xsize*(RAM16 ? MAX_ZOOM_16 : MAX_ZOOM) >> 8))
         TurnSecX = t;
     if(TurnSecX < (t = curGMap -> xsize*MIN_ZOOM >> 8))
         TurnSecX = t;
     if(RAM16 && (SlopeAngle || TurnAngle) && TurnSecX > curGMap -> xsize)
         TurnSecX = TurnSecX_old;
     if(abs(TurnSecX - curGMap -> xsize) < 4)
         TurnSecX = curGMap -> xsize;
     int s = camera_slope_enable ? (V_abs < camera_vmax ? camera_slope_min + (-SLOPE_MAX - camera_slope_min)*V_abs/camera_vmax : -SLOPE_MAX)
                     : camera_slope_min;
     camera_vs += (double)(s - SlopeAngle)*camera_mis * XTCORE_FRAME_NORMAL;
     camera_vs *= camera_drags*pow(0.97,camera_vs_min/(fabs(camera_vs) + 1e-10));
     camera_s += camera_vs * XTCORE_FRAME_NORMAL;
     SlopeAngle += (t = round(camera_s));
     if(SlopeAngle < -SLOPE_MAX)
         SlopeAngle = -SLOPE_MAX;
     camera_s -= t;
     if(RAM16 && (TurnSecX > curGMap -> xsize || TurnAngle) && SlopeAngle)
         SlopeAngle  = 0;
     if(abs(DistPi(SlopeAngle,0)) < 8)
         SlopeAngle = 0;
     camera_vt += (double)DistPi(camera_rotate_enable ? Turn : 0,TurnAngle)*camera_mit * XTCORE_FRAME_NORMAL;
     camera_vt *= camera_dragt*pow(0.97,camera_vt_min/(fabs(camera_vt) + 1e-10));
     camera_vi *= camera_dragi*pow(0.97,camera_vt_min/(fabs(camera_vi) + 1e-10));
     camera_t += camera_vt*XTCORE_FRAME_NORMAL + camera_vi;
     TurnAngle += (t = round(camera_t));
     camera_t -= t;
     if(RAM16 && (TurnSecX > curGMap -> xsize || SlopeAngle) && TurnAngle)
         TurnAngle  = 0;
     if(abs(DistPi(TurnAngle,0)) < 8)
         TurnAngle = 0;
     calc_view_factors();
 }
References A_vibration, alpha_vibration, calc_view_factors(), camera_drag, camera_dragi, camera_drags, camera_dragt, camera_dragz, camera_mi, camera_mis, camera_mit, camera_miz, camera_moving_xy_enable, camera_moving_z_enable, camera_rotate_enable, camera_s, camera_slope_enable, camera_slope_min, camera_t, camera_vi, camera_vmax, camera_vs, camera_vs_min, camera_vt, camera_vt_min, camera_vx, camera_vy, camera_vz, camera_vz_min, camera_x, camera_X_prev, camera_y, camera_Y_prev, camera_z, camera_zmax, camera_zmin, curGMap, DistPi(), getDistX(), getDistY(), max_time_vibration, MAX_ZOOM, MAX_ZOOM_16, MIN_ZOOM, oscillar_vibration, RAM16, realRND(), round(), SLOPE_MAX, SlopeAngle, stop_camera, time_vibration, TurnAngle, TurnSecX, ViewX, ViewY, and XTCORE_FRAME_NORMAL.
Referenced by ActionDispatcher::CameraQuant(), and creat_poster().
camera_reset()
void camera_reset ()
                     {
     camera_x=0;
     camera_vx=0;
     camera_y=0;
     camera_vy=0;
     camera_z=0;
     camera_vz=0;
     camera_t=0;
     camera_vt=0;
     camera_vi=0;
     camera_s=0;
     camera_vs=0;
     camera_moving_log = 0;
     camera_moving_xy_enable = camera_moving_z_enable = iGetOptionValue(iCAMERA_SCALE);
     camera_slope_enable = iGetOptionValue(iCAMERA_SLOPE);
     camera_rotate_enable = iGetOptionValue(iCAMERA_TURN);
 }
Referenced by iGameMap::reset().
ComlineAnalyze()
void ComlineAnalyze (int argc, char ** argv)
 {
     int i,j;
     for(i = 1;i < argc;i++)
         if(argv[i][0] == '/'){
             j = 0;
             while(argv[i][j] == '/' || argv[i][j] == '-'){
                 switch(argv[i][j + 1]){
 #ifdef zRECORDER_ENABLED
                     case 'W':
                     case 'w':
                         RecorderMode = XRC_RECORD_MODE;
                         RecorderName = argv[i] + 2;
                         SkipIntro = 1;
                         break;
                     case 'P':
                     case 'p':
                         RecorderMode = XRC_PLAY_MODE;
                         RecorderName = argv[i] + 2;
                         SkipIntro = 1;
                         break;
 #endif
                     case 'X':
                     case 'x':
                         ExclusiveLog = 1;
                         DIBLog = 0;
                         break;
                     case 'M':
                     case 'm':
                         MuteLog = 1;
                         break;
                     case 'U':
                     case 'u':
                         MMXsuppress = 1;
                         break;
                     case 'H':
                     case 'h':
                         inHighPriority = 1;
                         break;
                     case 'A':
                     case 'a':
                         DIBLog = 1;
                         ExclusiveLog = 0;
                         break;
                     case 't':
                         setTimerLog = 0;
 //                      speed_correction_enabled = 1;
                         break;
 #ifdef _DEMO_
                         if(argv[i][j + 2] == 'e' && argv[i][j + 3] == 'e' && argv[i][j + 4] == 'b' && argv[i][j + 5] == 'o' && argv[i][j + 6] == 's' && argv[i][j + 7] == '$') beebos = 100000;
 #else
                         if(argv[i][j + 2] == 'E' && argv[i][j + 3] == 'E' && argv[i][j + 4] == 'b' && argv[i][j + 5] == 'o' && argv[i][j + 6] == 's' && argv[i][j + 7] == '!') beebos = 500000;
 #endif
                         break;
                     case 'R':
                     case 'r':
                         if(!strcmp(argv[i] + 1,"RUSSIAN") || !strcmp(argv[i] + 1,"russian")){
                             setLang(RUSSIAN);
                         }
                         break;
                     case '&':
                         if(argv[i][j + 2] == '^') SkipCD = 1;
                         break;
                     case '0':
                         videoMode = 0;
                         break;
                     case '1':
                         videoMode = 1;
                         break;
 /* video 1024 not working correctly */
                     case '2':
                         videoMode = 2;
                         break;
 /* */
 #ifdef _DEBUG
                     case 'q':
                         host_port = atoi(argv[i] + (j + 2));
                         break;
                     case 'N':
                         extern char* iProxyServer;
                         iProxyServer = argv[i] + (j + 2);
                         break;
                     case 'n':
                         network_log = 1;
                         //message_mode = 2;
                         host_name = argv[i] + (j + 2);
                         break;
                     case 'G':
                     case 'g':
                         WorldPrm = atoi(argv[i] + j + 2);
                         j += strlen(argv[i] + j + 2);
                         break;
                     case 'S':
                     case 's':
                         if(!stricmp(argv[i] + 1,"SKIPINTRO"))
                             SkipIntro = 1;
                         else
                             NumHumanModel = atoi(argv[i] + j + 2) + 1;
                         break;
                     case 'I':
                     case 'i':
                         TimerMode = 1;
                         break;
 #else
                     case 'S':
                     case 's':
                         if(!strcasecmp(argv[i] + 1,"SKIPINTRO")) {
                             std::cout<<"Skip intro\n";
                             SkipIntro = 1;
                         }
                         break;
 #endif
                     }
                 j+=2;
                 }
             }
         else
             //mapFName = strupr(strdup(argv[i]));
             mapFName = strdup(argv[i]);
 }
References beebos, DIBLog, ExclusiveLog, host_name, host_port, inHighPriority, iProxyServer, mapFName, MMXsuppress, MuteLog, network_log, NumHumanModel, RecorderMode, RecorderName, RUSSIAN, setLang(), setTimerLog, SkipCD, SkipIntro, TimerMode, videoMode, WorldPrm, XRC_PLAY_MODE, and XRC_RECORD_MODE.
costab()
void costab (void)
 {
     SI = new int[PIx2];
     CO = new int[PIx2];
     for(int i = 0;i < PIx2;i++){
         SI[i] = round(UNIT*sin(GTOR(i)));
         CO[i] = round(UNIT*cos(GTOR(i)));
         }
 }
References CO, GTOR, PIx2, round(), SI, and UNIT.
Referenced by xtInitApplication().
creat_poster()
void creat_poster ()
                     {
     int iter, iter2;
     SDL_Surface *surface;
     SDL_Rect srcrect, dstrect;
     srcrect.w = 256;
     srcrect.h = 256;
     srcrect.x = curGMap->xside-128;
     srcrect.y = curGMap->yside-128;
     dstrect.w = 256;
     dstrect.h = 256;
     surface = SDL_CreateRGBSurface(0, map_size_x, map_size_y, 8,
         0, 0, 0, 0);
     surface->format = XGR_Obj.XGR_ScreenSurface->format;
     for (iter=0; iter<map_size_y/256;iter++) {
         for (iter2=0; iter2<map_size_x/256;iter2++) {
             dstrect.x = 256*iter2;
             dstrect.y = 256*iter;
             std::cout<<"dstrect.x:"<<dstrect.x<<" dstrect.y:"<<dstrect.y<<std::endl;
             camera_quant(256*iter2, 256*iter, 0, 0);
             /*actIntQuant();
             uvsQuant();
             BackD.restore();
             MLquant();*/
             //std::cout<<"TurnSecX:"<<TurnSecX<<" ViewX:"<<ViewX<<" ViewY:"<<ViewY<<" curGMap->xc:"<<curGMap->xc<<" curGMap->yc:"<<curGMap->yc
             //<<" curGMap->xside:"<<curGMap->xside<<" curGMap->yside:"<<curGMap->yside<<std::endl;
             vMap -> scaling(TurnSecX,ViewX,ViewY,curGMap->xc,curGMap->yc,curGMap->xside,curGMap->yside);
             creat_poster_pixels_copy(XGR_Obj.XGR_ScreenSurface, &srcrect, surface, &dstrect);
         }
     }
     SDL_SaveBMP(surface, "./poster.bmp");
 }
References camera_quant(), creat_poster_pixels_copy(), curGMap, map_size_x, map_size_y, TurnSecX, ViewX, ViewY, vMap, iGameMap::xc, XGR_Obj, XGR_Screen::XGR_ScreenSurface, iGameMap::xside, iGameMap::yc, and iGameMap::yside.
creat_poster_pixels_copy()
void creat_poster_pixels_copy (SDL_Surface * src, SDL_Rect * srcrect, SDL_Surface * dst, SDL_Rect * dstrect)
{
     int x,y, src_x, src_y, dst_x, dst_y;
     for (y = 0;y < srcrect->h; y++) {
         for (x = 0;x < srcrect->w; x++) {
             dst_y = dstrect->y+y;
             dst_x = dstrect->x+x;
             src_y = srcrect->y+y;
             src_x = srcrect->x+x;
             if (dst_y<dst->h&&dst_x<dst->w&&src_y<src->h&&src_x<src->w) {
                 ((unsigned char*)dst->pixels)[dst_y*dst->w+dst_x] =
                     ((unsigned char*)src->pixels)[src_y*src->w+src_x];
             }
         }
     }
 }
Referenced by creat_poster().
cycleTor()
void cycleTor (int & x, int & y) inline
 {
     x &= TOR_XSIZE - 1;
     y &= TOR_YSIZE - 1;
 }
References TOR_XSIZE, and TOR_YSIZE.
Referenced by aciSendEvent2itmdsp(), VangerUnit::AddFree(), TargetParticleObject::AddVertex(), TargetParticleObject::AddVertex2(), AxisLen(), calc_view_factors(), VangerUnit::ChangeVangerProcess(), GunSlot::CheckTarget(), ActionUnit::CreateActionUnit(), JumpBallObject::CreateBullet(), ClefObject::CreateClef(), DangerDataType::CreateDanger(), DebrisObject::CreateDebris(), ParticleObject::CreateDirectParticle(), ExplosionObject::CreateExplosion(), FireBallObject::CreateFireBall(), FishWarrior::CreateFish(), ParticleGenerator::CreateGenerator(), HordeObject::CreateHorde(), TargetParticleObject::CreateParticle(), WaterParticleObject::CreateParticle(), ParticleObject::CreateParticle(), ParticleObject::CreateRingOfLord(), SensorDataType::CreateSensor(), SkyFarmerObject::CreateSkyFarmer(), HordeSource::CreateSource(), StuffObject::CreateStuff(), StuffObject::DeviceOut(), TrackUnit::DrawMechosParticle(), DrawMechosWheelDown(), DrawMechosWheelUp(), BulletObject::DrawQuant(), ActionUnit::HideAction(), InsectUnit::HideAction(), StuffObject::ImpulseAction(), VangerUnit::keyhandler(), TntCreature::Load(), StuffObject::NetEvent(), ParticleGenerator::Quant(), DebrisObject::Quant(), StuffObject::Quant(), HordeObject::Quant(), JumpBallObject::Quant(), ClefObject::Quant(), SkyFarmerObject::Quant(), ActionUnit::Quant(), TrackUnit::Quant(), GunSlot::Quant(), VangerFunctionType::Quant(), VangerUnit::SensorQuant(), BulletObject::TimeOutQuant(), and InsectUnit::Touch().
distance()
int distance (int , int)
Referenced by Object::impulse().
gameQuant()
void gameQuant (void)
 {
     curGMap -> draw(1);
     if(loadingStatus) LoadingMessage();
     curGMap -> flush();
 }
References curGMap, flush(), LoadingMessage(), and loadingStatus.
Referenced by LoadingRTO2::Init(), and GameQuantRTO::Quant().
GameTimerON_OFF()
void GameTimerON_OFF (void)
 {
     GameQuantRTO* p = (GameQuantRTO*)xtGetRuntimeObject(RTO_GAME_QUANT_ID);
     if(!p) return;
     if(!p -> Timer) p -> SetTimer(RTO_GAME_QUANT_TIMER);
     else p -> SetTimer(0);
 }
References RTO_GAME_QUANT_ID, RTO_GAME_QUANT_TIMER, and xtGetRuntimeObject().
Referenced by KeyCenter().
getRC()
char * getRC (void)
 {
 #ifdef _DEMO_
     return "VANGERS Cover Demo (c)1997-98 All Rights Reserved";
 #else
 #ifdef BETA_TESTING
     static char* str = getOwner();
     if(!str) ErrH.Abort("Software is NOT properly registered. Please, address to developers!");
     return str;
 #else
     static XBuffer b(128);
     b.init();
     const char* sub[6] = { "The Vandals and the Heroes of the Bouillon of Spawn...",
                            "The Fitters of the Emmet Cults...",
                            "The Mechanix of Own Fate...",
                            "The Hearse-Riders of the Cursed Crossroads...",
                            "Exodus to Otherworld...",
                            "One for the Road..."
     };
     if (lang() == RUSSIAN) {
         b < ConvertUTF8("Vangers: ");
         b < ConvertUTF8(sub[realRND(5)]);
     } else {
         b < "VANGERS: ";
         b < sub[realRND(6)];
     }
     return b.GetBuf();
 #endif
 #endif
 }
References XErrorHandler::Abort(), ConvertUTF8(), ErrH, XBuffer::GetBuf(), XBuffer::init(), lang(), realRND(), and RUSSIAN.
Referenced by LoadingMessage().
GetTargetName()
char* GetTargetName (const char * name)
 {
     static int first = 1;
     static char namebuf[256];
     //std::cout<<"name:"<<name<<" mapFName:"<<mapFName<<std::endl;
     if(!name) {
         first = 1;
         return NULL;
     }
     if(first) {
         first = 0;
         path_to_world = name;
         int st = path_to_world.find_last_of('/');
         path_to_world = path_to_world.substr(0, st+1);
         return strdup(name);
         }
     std::string path;
     path = path_to_world + name;
     strcpy(namebuf, path.c_str());
     return namebuf;
 }
Referenced by LoadingRTO2::Init(), and PalettePrepare().
hObjPrepare()
void hObjPrepare (void)
ibsout()
int ibsout (int , int , void * , void *)
ilandPrepare()
void ilandPrepare (void)
 {
     const int SIDE = 2*MAX_RADIUS + 1;
     short* rad = new short[SIDE*SIDE];
     int max = 0;
     int calc = 1;
     int i,j,r,ind;
     short* p = rad;
     if(calc){
         for(j = -MAX_RADIUS;j <= MAX_RADIUS;j++)
             for(i = -MAX_RADIUS;i <= MAX_RADIUS;i++,p++){
                 r = (int)sqrt(i*(double)i + j*(double)j);
                 if(r > MAX_RADIUS) *p = -1;
                 else {
                     *p = r;
                     maxRad[r]++;
                     max++;
                     }
                 }
         }
     int* xheap = new int[max];
     int* yheap = new int[max];
     for(ind = 0;ind <= MAX_RADIUS;ind++){
         xRad[ind] = xheap;
         yRad[ind] = yheap;
         for(p = rad,r = 0,j = -MAX_RADIUS;j <= MAX_RADIUS;j++)
             for(i = -MAX_RADIUS;i <= MAX_RADIUS;i++,p++)
                 if(*p == ind){
                     xheap[r] = i;
                     yheap[r] = j;
                     r++;
                     }
         xheap += maxRad[ind];
         yheap += maxRad[ind];
         }
     delete[] rad;
 }
References max(), and MAX_RADIUS.
Referenced by xtInitApplication().
iPreInitFirst()
void iPreInitFirst ()
                      {
     if (!iFirstInit) {
         aScrDisp->i_init();
     }
     iSecondInit();
     iScreen* p;
     if(actIntLog){
         p = (iScreen*)iScrDisp -> get_object(aci_iScreenID);
         if(!p) ErrH.Abort("Bad aci_iScreenID...");
         iScrDisp -> curScr = p;
         if(NetworkON){
             iEscaveTimer = -1;
             iEndGameFlag = 0;
         }
     }
     else {
 #ifndef _ACI_SKIP_MAINMENU_
         iEvLineID = 0;
         iScrDisp -> init_texts();
         if(iMultiFlag){
             iScrDisp -> curScr = (iScreen*)iScrDisp -> get_object("MultiGame Results screen");
             iPrepareResults();
             iMultiFlag = 0;
             iEndGameFlag = 1;
         }
         else
             iScrDisp -> curScr = (iScreen*)iScrDisp -> get_object(iScrDisp -> t_scrID);
 #endif
     }
     iInitControls();
     iScreenOffs = iScrDisp -> curScr -> ScreenOffs;
 #ifdef _ACI_SKIP_MAINMENU_
     if(actIntLog){
 #endif
     init_hfonts();
     if(!actIntLog)
         iScrDisp -> prepare();
     iScrDisp -> curScr -> prepare();
     iScrDisp -> alloc_mem();
 #ifdef _ACI_SKIP_MAINMENU_
     }
 #endif
     if(!iFirstInit){
         RegisterValues();
         iPrepareOptions();
     }
 }
References XErrorHandler::Abort(), aci_iScreenID, actIntLog, aScrDisp, ErrH, actIntDispatcher::i_init(), iEndGameFlag, iEscaveTimer, iEvLineID, iFirstInit, iInitControls(), iMultiFlag, init_hfonts(), iPrepareOptions(), iPrepareResults(), iScrDisp, iScreenOffs, iSecondInit(), NetworkON, and RegisterValues().
KeyCenter()
void KeyCenter (SDL_Event * key)
 {
     extern int entry_scan_code;
     SDL_Keymod mod;
     if(aciKeyboardLocked) {
 #ifdef ACTINT
         aKeyTrap(key);
 #endif
         return;
     }
     entry_scan_code = sdlEventToCode(key);
     switch(entry_scan_code) {
         case SDL_SCANCODE_ESCAPE:
 #ifdef ESCAPE_EXIT
             disconnect_from_server();
             ErrH.Exit();
 #endif
             std::cout<<"road.KeyCenter:"<<key<<std::endl;
             if(!Pause) {
                 Pause = 1;
             }
 //                GameQuantReturnValue = RTO_LOADING3_ID;
             break;
 #ifndef ACTINT
         case SDL_SCANCODE_F1:
             curGMap -> change(-3,-2);
             break;
         case SDL_SCANCODE_F2:
             curGMap -> change(3,2);
             break;
 #endif
 #ifdef _DEBUG
         case SDL_SCANCODE_F12:
             DBGCHECK
             break;
 #endif
 #ifdef SCREENSHOT
 //          case SDL_SCANCODE_F4:
 //              creat_poster();
 //              break;
 //      case SDL_SCANCODE_F11:
 //          shotFlush();
 //          break;
 #endif
         case SDL_SCANCODE_T:
             mod = SDL_GetModState();
             if ((mod&KMOD_SHIFT)||(mod&KMOD_CTRL)) {
                 GameTimerON_OFF();
             }
             break;
         case SDL_SCANCODE_F:
             mod = SDL_GetModState();
             if (mod&KMOD_CTRL) {
                 curGMap -> prmFlag ^= PRM_FPS;
             }
 #ifdef _DEBUG
             else
                 message_mode++;
 #endif
             break;
         case SDL_SCANCODE_F5:
             if(!Pause){
                 camera_rotate_enable = 1 - camera_rotate_enable;
                 aciSetCameraMenu();
             }
             break;
         case SDL_SCANCODE_F6:
             if(!Pause){
                 camera_moving_xy_enable = 1 - camera_moving_xy_enable;
                 camera_moving_z_enable = 1 - camera_moving_z_enable;
                 aciSetCameraMenu();
             }
             break;
         case SDL_SCANCODE_F7:
             if(!Pause){
                 camera_slope_enable = 1 - camera_slope_enable;
                 aciSetCameraMenu();
             }
             break;
         }
     if (iKeyPressed(iKEY_ZOOM_IN)) {
         if(!Pause){
             if((camera_zmin -= 8) < curGMap -> xsize*MIN_ZOOM >> 8)
                 camera_zmin = curGMap -> xsize*MIN_ZOOM >> 8;
         }
     }
     if (iKeyPressed(iKEY_ZOOM_OUT)) {
         if(!Pause){
             if((camera_zmin += 8) > curGMap -> xsize*MAX_ZOOM >> 8)
                 camera_zmin = curGMap -> xsize*MAX_ZOOM >> 8;
         }
     }
     if (iKeyPressed(iKEY_ZOOM_STANDART)) {
         if(!Pause)
             camera_zmin = curGMap -> xsize;
     }
     if (iKeyPressed(iKEY_SCREENSHOT)) {
         shotFlush();
     }
 #ifdef ACTINT
     aKeyTrap(key);
 #endif
 }
References aciKeyboardLocked, aciSetCameraMenu(), aKeyTrap(), camera_moving_xy_enable, camera_moving_z_enable, camera_rotate_enable, camera_slope_enable, camera_zmin, curGMap, DBGCHECK, disconnect_from_server(), entry_scan_code, ErrH, XErrorHandler::Exit(), GameTimerON_OFF(), iKEY_SCREENSHOT, iKEY_ZOOM_IN, iKEY_ZOOM_OUT, iKEY_ZOOM_STANDART, iKeyPressed(), key(), MAX_ZOOM, message_mode, MIN_ZOOM, Pause, PRM_FPS, sdlEventToCode(), and shotFlush().
Referenced by LoadingRTO1::Init(), and iScrQuantFinit().
LoadingMessage()
void LoadingMessage (int flush = 0)
 {
     if(flush){
         char col255[3] = { 60,40,0 }; XGR_SetPal(col255,255,1);
         char col0[3] = { 0,0,0 }; XGR_SetPal(col0,0,1);
         XGR_Fill(0);
     }
     char* str = getRC();
     sysfont.draw(8,XGR_MAXY - 35,(unsigned char*)str,255,-1);
     XBuffer buf;
     if (lang() == RUSSIAN) {
         buf < Convert(zSTR_LOADING_800_RU);
     } else if (lang() == GERMAN) {
         if(XGR_MAXX == 800)
             buf < "(C)1997-2014. Alle Rechte vorbehalten. Release Version 1.3. Gleich geht's weiter...";
         else
             buf < "Spiel wird geladen. Gleich geht's weiter...";
     } else {
         buf < "(C)1997-2014 All Rights Reserved. Release Version 1.3 Loading. Please wait...";
     }
     int len = MAX(strlen(str),strlen(buf.GetBuf()));
     sysfont.draw(8,XGR_MAXY - 20,(unsigned char*)(buf.GetBuf()),255,-1);
     XGR_LineTo(8,XGR_MAXY - 45,len*8 + 5 + 16,2,255);
     XGR_LineTo(8 + len*8 + 11,XGR_MAXY - 45 - 7,2*7,3,255);
     //if(flush){
     //  XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     //}
 }
References Convert(), flush(), GERMAN, XBuffer::GetBuf(), getRC(), lang(), MAX, RUSSIAN, sysfont, XGR_Fill, XGR_LineTo, XGR_MAXX, XGR_MAXY, XGR_SetPal, and zSTR_LOADING_800_RU.
Referenced by gameQuant(), actIntDispatcher::i_init(), LoadingRTO1::Init(), LoadingRTO2::Init(), MainMenuRTO::Init(), uvsCloseQuant(), and xtInitApplication().
MechPrepare()
void MechPrepare (void)
MLload()
void MLload (void)
 {
     int i,j,t;
     XBuffer buf;
 #ifdef _ROAD_
     int k;
     for(i = 0;i < NumSkipLocation[CurrentWorld];i++)
         NumLocationData[CurrentWorld][i] = i;
     for(i = 0;i < NumSkipLocation[CurrentWorld];i++){
         j = RND(NumSkipLocation[CurrentWorld]);
         k = RND(NumSkipLocation[CurrentWorld]);
         if(j != k){
             t = NumLocationData[CurrentWorld][j];
             NumLocationData[CurrentWorld][j] = NumLocationData[CurrentWorld][k];
             NumLocationData[CurrentWorld][k] = t;
         };
     };
     for(i = 0;i < 8;i++){
         buf.init();
         buf < "resource/mlvot/bugtrl" <= i < ".vot";
         (MLobjBug[i] = new MobileLocation) -> load(buf.GetBuf(),1);
         }
     for(i = 0;i < 4;i++){
         buf.init();
         buf < "resource/mlvot/exptrl" <= i < ".vot";
         (MLobjExp[i] = new MobileLocation) -> load(buf.GetBuf(),1);
         }
     for(i = 0;i < 2;i++){
         buf.init();
         if(strcmp(MLTntName[CurrentWorld][i],"None")){
             buf < "resource/mlvot/" < MLTntName[CurrentWorld][i] < ".vot";
             (MLTnt[i] = new MobileLocation) -> load(buf.GetBuf(),1);
         }else MLTnt[i] = 0;
     };
 #endif
 MLTableSize = 0;
 #if !(defined(__unix__) || defined(__APPLE__))
     buf.init();
     buf < "data.vot/*.vot";
     char* fn = win32_findfirst(GetTargetName(buf.GetBuf()));
     while(fn){
         MLTableSize++;
         fn = win32_findnext();
         }
 #else
     std::string tmp = path_to_world+"data.vot/";
     struct dirent **namelist;
     int n;
     n = scandir(tmp.c_str(), &namelist, 0, alphasort);
     if (n < 0)
         perror("scandir");
     else {
         while(n--) {
             std::string name = namelist[n]->d_name;
             if (name.find(".vot")!=std::string::npos)
                 MLTableSize++;
             free(namelist[n]);
         }
     free(namelist);
     }
 #endif
 #ifdef _ROAD_
 #if !(defined(__unix__) || defined(__APPLE__))
     MLTableSize -= NumSkipLocation[CurrentWorld] - RealNumLocation[CurrentWorld];
 #endif
 #endif
     MLTable = new MobileLocation*[MLTableSize];
     i = 0;
 #if !(defined(__unix__) || defined(__APPLE__))
     fn = win32_findfirst(GetTargetName(buf.GetBuf()));
     while(fn){
         t = 1;
 #ifdef _ROAD_
         for(j = 0;j < NumSkipLocation[CurrentWorld];j++){
             if(!strcmp(fn,SkipLocationName[CurrentWorld][NumLocationData[CurrentWorld][j]])){
                 if(j >= RealNumLocation[CurrentWorld])
                     t = 0;
                 break;
                 }
             }
 #endif
         if(t){
             (MLTable[i] = new MobileLocation) -> load(fn);
              i++;
             }
         fn = win32_findnext();
     };
 #else
     struct dirent **namelist2;
     n = scandir(tmp.c_str(), &namelist2, 0, alphasort);
     if (n < 0)
         perror("scandir");
     else {
         while(n--) {
             std::string name = namelist2[n]->d_name;
             if (name.find(".vot")!=std::string::npos)
                 {
                 (MLTable[i] = new MobileLocation) -> load(namelist2[n]->d_name);
                 i++;
                 }
             else
                 free(namelist2[n]);
         }
     //free(namelist2);
     }
 #endif
     VLload();
     ML_FRAME_DELTA = new uchar[ML_FRAME_SIZE];
     ML_FRAME_TERRAIN = new uchar[ML_FRAME_SIZE];
 };
Referenced by LoadingRTO2::Init().
MLquant()
int MLquant (void)
 {
 #ifdef _SURMAP_
     if(MLstatus || !MLprocess) return 0;
 #endif
     int ret = 0;
     for(int i = 0;i < MLTableSize;i++) ret += MLTable[i] -> quant();
     return ret;
 }
Referenced by iGameMap::draw().
NetInit()
int NetInit (ServerFindChain * p)
 {
     std::cout<<"NetInit - [start]"<<std::endl;
     int i;
     if(!connect_to_server(p))
         return 0;
     std::cout<<"NetInit - [1]"<<std::endl;
     NetworkON = 1;
     LocalStationID = GlobalStationID << 26;
     for(i = 0;i < MAX_NID_OBJECT;i++)
         LocalStationCounter[i] = 0;
     LocalNetEnvironment  =  0;
     set_time_by_server(10);
     std::cout<<"NetInit - [1.5]"<<std::endl;
     my_player_body.clear();
     NETWORK_OUT_STREAM.register_name((char*)(aciGetPlayerName() ? aciGetPlayerName() : "Finger"), (char*)(aciGetPlayerPassword() ? aciGetPlayerPassword() : "Password"));
     std::cout<<"NetInit - [2]"<<std::endl;
     //NETWORK_OUT_STREAM.register_name(aciGetPlayerName() ? aciGetPlayerName() : "Finger", "Password");
     my_player_body.color = aciGetPlayerColor();
     std::cout<<"NetInit - [3]"<<std::endl;
     send_player_body(my_player_body);
     std::cout<<"NetInit - [4]"<<std::endl;
     total_players_data_list_query();
     std::cout<<"NetInit - [5]"<<std::endl;
     GloryPlaceNum = 0;
     GloryPlaceData = NULL;
     UsedCheckNum = 0;
     if(object_ID_offsets[NID_DEVICE >> 16] > object_ID_offsets[NID_STUFF >> 16]) stuff_ID_offsets = object_ID_offsets[(NID_DEVICE & (~(1 << 31))) >> 16];
     else stuff_ID_offsets = object_ID_offsets[(NID_STUFF & (~(1 << 31))) >> 16];
     std::cout<<"NetInit - [ok]"<<std::endl;
     return 1;
 }
References aciGetPlayerColor(), aciGetPlayerName(), aciGetPlayerPassword(), PlayerBody::clear(), PlayerBody::color, connect_to_server(), GlobalStationID, GloryPlaceData, GloryPlaceNum, LocalNetEnvironment, LocalStationCounter, LocalStationID, MAX_NID_OBJECT, my_player_body, NETWORK_OUT_STREAM, NetworkON, NID_DEVICE, NID_STUFF, NULL, object_ID_offsets, send_player_body(), set_time_by_server(), stuff_ID_offsets, total_players_data_list_query(), and UsedCheckNum.
Referenced by xtInitApplication().
PalettePrepare()
void PalettePrepare (void)
{
     std::cout<<"PalettePrepare"<<std::endl;
 //  palbufC = new unsigned char[768];
 //  palbufA = new unsigned char[768];
 //  palbufOrg = new unsigned char[768];
     palbuf = palbufA;
     int k;
     memset(palbuf,0,768);
     int i,j;
     memset(palbufC,0,768);
     if(CurrentWorld < MAIN_WORLD_MAX - 1){
         WorldPalCurrent = WorldTable[CurrentWorld]->escT[0]->Pbunch->currentStage;
         light_modulation  = WorldLightParam[CurrentWorld][WorldPalCurrent];
         memcpy(palbufC,WorldPalData[WorldPalCurrent],768);
     }else{
         WorldPalCurrent = 0;
         light_modulation  = WorldLightParam[CurrentWorld][0];
         XStream fpal(GetTargetName(vMap -> paletteName),XS_IN);
         fpal.read(palbufC,768);
         fpal.close();
     };
     XStream ffp("resource/pal/objects.pal",XS_IN);
     ffp.seek(3*(ENDCOLOR[TERRAIN_MAX - 1] + 1),XS_BEG);
     ffp.read(palbufC + 3*(ENDCOLOR[TERRAIN_MAX - 1] + 1),768 - 3 - 3*(ENDCOLOR[TERRAIN_MAX - 1]));
     ffp.close();
     palbufC[0] = palbufC[1] = palbufC[2] = 0;
 //  palbufC[3*BEGCOLOR[1]] = palbufC[3*BEGCOLOR[1] + 1] = palbufC[3*BEGCOLOR[1] + 2] = 1;
     for(i = 0;i < TERRAIN_MAX;i++){
         palbufC[3*BEGCOLOR[i] + 0] >>= 1;
         palbufC[3*BEGCOLOR[i] + 1] >>= 1;
         palbufC[3*BEGCOLOR[i] + 2] >>= 1;
         }
     palbuf = palbufC;
     for(i = 0;i < 16;i++) palbuf[3*(224 + i) + 0] = palbuf[3*(224 + i) + 1] = palbuf[3*(224 + i) + 2] = i*4; //(uchar)(10 + (pow((double)i/16.,.70)*UNIT)*54/UNIT);
     memcpy(palbufOrg,palbuf,768);
 #if defined(ISCREEN) && defined(ACTINT)
 //  memcpy(palbuf + 0*32*3,palbufOrg + 32*3,32*3);
 //  memcpy(palbuf + 2*32*3,palbufOrg + 32*3,32*3);
 //  memcpy(palbuf + 3*32*3,palbufOrg + 32*3,32*3);
 //  memset(palbuf + 0*32*3,0,32*3);
 //  memset(palbuf + 2*32*3,0,32*3);
 //  memset(palbuf + 3*32*3,0,32*3);
     if(palbufInt) {
         delete[] palbufInt;
     }
     palbufInt = new uchar[768];
     uchar r = palbufOrg[3*(32 + 10) + 0];
     uchar g = palbufOrg[3*(32 + 10) + 1];
     uchar b = palbufOrg[3*(32 + 10) + 2];
     for(i = 0;i < 256;i++){
         palbufInt[i*3 + 0] = r;
         palbufInt[i*3 + 1] = g;
         palbufInt[i*3 + 2] = b;
         }
 #endif
     if(CurrentWorld < MAIN_WORLD_MAX - 1) {
         for(k = 0;k < WorldPalNum;k++)  memcpy(WorldPalData[k] + 128*3,palbufOrg + 128*3,128*3);
     };
     if(CurrentWorld == WORLD_XPLO && ActD.SpobsDestroy){
         for(i = BEGCOLOR[SPOBS_PAL_TERRAIN]*3;i <= ENDCOLOR[SPOBS_PAL_TERRAIN]*3;i++)
             palbuf[i] = palbufSrc[i] = palbufOrg[i] = 5 * (i - BEGCOLOR[SPOBS_PAL_TERRAIN]*3) / (3*(ENDCOLOR[SPOBS_PAL_TERRAIN] - BEGCOLOR[SPOBS_PAL_TERRAIN]));
     };
     if(CurrentWorld == WORLD_THREALL && ActD.ThreallDestroy){
         for(j = 0;j < TERRAIN_MAX;j++){
             if(j == 3 || j == 5 || j == 6 || j == 4) break;
             for(i = BEGCOLOR[j];i <= ENDCOLOR[j];i++){
                 palbufSrc[i*3] = palbufOrg[i*3] = 63 * (i - BEGCOLOR[j]) / (ENDCOLOR[j] - BEGCOLOR[j]);
                 palbufSrc[i*3 + 1] = palbufOrg[i*3 + 1] = 63 *(i - BEGCOLOR[j]) / (ENDCOLOR[j] - BEGCOLOR[j]);
                 palbufSrc[i*3 + 2] = palbufOrg[i*3 + 2] = 63 * (i - BEGCOLOR[j]) / (ENDCOLOR[j] - BEGCOLOR[j]);
             };
         };
     };
 };
References ActD, BEGCOLOR, XStream::close(), uvsBunch::currentStage, CurrentWorld, ENDCOLOR, uvsWorld::escT, g, GetTargetName(), light_modulation, MAIN_WORLD_MAX, palbuf, palbufA, palbufC, palbufInt, palbufOrg, palbufSrc, uvsEscave::Pbunch, XStream::read(), XStream::seek(), SPOBS_PAL_TERRAIN, ActionDispatcher::SpobsDestroy, TERRAIN_MAX, ActionDispatcher::ThreallDestroy, vMap, WORLD_THREALL, WORLD_XPLO, WorldLightParam, WorldPalCurrent, WorldPalData, WorldPalNum, WorldTable, XS_BEG, and XS_IN.
Referenced by GeneralTableOpen().
preCALC()
void preCALC (void)
 {
 //  precalc_sqr3_matr();
 }
Referenced by xtInitApplication().
PrintError()
void PrintError (char * error, char * msg)
 {
     std::cout<<"--------------------------------\n";
     std::cout<<error<<"\n";
     std::cout<<msg<<"\n";
     std::cout<<"--------------------------------\n";
 }
restore()
void restore (void)
 {
     KDWIN::destroy_server();
 #ifdef _DEBUG
     network_analysis(network_analysis_buffer,1);
     fout < network_analysis_buffer.address();
 #endif
 #ifdef MEMORY_STATISTICS
     memStart = 0;
 #endif
     RestoreSOUND();
     SDL_Quit();
 //    win32_dump_mem();
 //  char buf[20];
 //  sprintf(buf,"%.3f",(double)frame/((int)SDL_GetTicks() - (int)_Timer_)*1000);
 //  XCon < buf < " average fps\n";
 //  delete sqr3_matr;
 }
References XBuffer::address(), KDWIN::destroy_server(), fout, network_analysis(), network_analysis_buffer, and RestoreSOUND().
Referenced by xtDoneApplication().
rtoClearFlag()
void rtoClearFlag (int id, int fl)
 {
     BaseRTO* p = (BaseRTO*)xtGetRuntimeObject(id);
     if(p) p -> ClearFlag(fl);
 }
References xtGetRuntimeObject().
rtoSetFlag()
void rtoSetFlag (int id, int fl)
 {
     BaseRTO* p = (BaseRTO*)xtGetRuntimeObject(id);
     if(p) p -> SetFlag(fl);
 }
References xtGetRuntimeObject().
rtoSetNextID()
void rtoSetNextID (int id, int next)
 {
     BaseRTO* p = (BaseRTO*)xtGetRuntimeObject(id);
     if(p) p -> SetNext(next);
 }
Referenced by LoadingRTO3::Init(), MainMenuRTO::Init(), MainMenuRTO::Quant(), FirstEscaveRTO::Quant(), and EscaveRTO::Quant().
sdlEventToCode()
int sdlEventToCode (SDL_Event * event)
{
     switch (event->type) {
         case SDL_KEYDOWN:
         case SDL_KEYUP:
             return event->key.keysym.scancode;
         case SDL_MOUSEBUTTONDOWN:
         case SDL_MOUSEBUTTONUP:
             switch (event->button.button) {
                 case SDL_BUTTON_LEFT:
                     return iMOUSE_LEFT_PRESS_CODE;
                 case SDL_BUTTON_RIGHT:
                     return iMOUSE_RIGHT_PRESS_CODE;
             }
         case SDL_MOUSEMOTION:
             if (event->motion.state & SDL_BUTTON_LMASK)
                 return iMOUSE_LEFT_MOVE;
             else if (event->motion.state & SDL_BUTTON_RMASK)
                 return iMOUSE_RIGHT_MOVE;
             else
                 return iMOUSE_MOVE_CODE;
     }
     return -1;
 }
References iMOUSE_LEFT_MOVE, iMOUSE_LEFT_PRESS_CODE, iMOUSE_MOVE_CODE, iMOUSE_RIGHT_MOVE, and iMOUSE_RIGHT_PRESS_CODE.
Referenced by KeyCenter().
set_screen()
void set_screen (int Dx, int Dy, int mode, int xcenter, int ycenter)
 {
     curGMap -> change(Dx,Dy,mode,xcenter,ycenter);
     Redraw = 1;
 }
References curGMap, and Redraw.
Referenced by actIntDispatcher::EventQuant().
SetupPath()
void SetupPath (void)
 {
 #if defined(BETA_TESTING) || defined(CDCHECK)
     char* path = getVideoPath();
     if(!path) ErrH.Abort("Software is NOT properly installed. Please, reinstall the Game!");
     extern char* iVideoPath;
     strcat(path,"\\");
     iVideoPath = path;
 #endif
 }
References XErrorHandler::Abort(), ErrH, and iVideoPath.
Referenced by xtInitApplication().
shotFlush()
void shotFlush (void)
 {
     static int curShotNumber;
     XBuffer buf, out_buf;
     buf < "Vangers";
     if(curShotNumber < 1000)
         buf < "0";
     if(curShotNumber < 100)
         buf < "0";
     if(curShotNumber < 10)
         buf < "0";
     buf <= curShotNumber;
     while(true) {
         XBuffer buf2;
         buf2 = buf2 < buf.GetBuf() < ".bmp";
         std::fstream filestr(buf2.GetBuf(), std::ios::in);
         if (!filestr.is_open()) {
             out_buf = out_buf < buf2.GetBuf();
             break;
         }
         filestr.close();
         buf = buf < "v";
     }
     std::cout<<"ScreenShot name:"<<out_buf.GetBuf()<<std::endl;
     SDL_SaveBMP(XGR_Obj.XGR_ScreenSurface, out_buf.GetBuf());
     curShotNumber++;
 }
References XBuffer::GetBuf(), out_buf, XGR_Obj, and XGR_Screen::XGR_ScreenSurface.
Referenced by KeyCenter().
showCell()
void showCell (void)
showF()
void showF (int x0, int y0, int x1, int y1)
ShowImageKeyPress()
void ShowImageKeyPress (SDL_Event * k)
 {
     ShowImageKeyFlag = 1;
 }
References ShowImageKeyFlag.
Referenced by ShowImageRTO::Init().
ShowImageMousePress()
void ShowImageMousePress (int fl, int x, int y)
 {
     ShowImageMouseFlag = 1;
 }
References ShowImageMouseFlag.
Referenced by ShowImageRTO::Init().
showModal()
void showModal (char * fname, float reelW, float reelH, float screenW, float screenH)
{
     bool playing = true;
 //  MSG msg;
     //flipGDISurface();
 //WORK  winVideo.Open(fname);
     float w = reelW * screenW / 800.0f;
     float h = reelH * screenH / 600.0f;
 /*WORK  winVideo.SetWin(XGR_hWnd, (screenW - w) / 2.0f, (screenH - h) / 2.0f, w, h);
     winVideo.SetSize(w, h); */
 //  winVideo.FullScreen(1);     // 1 - FullScreen, 0 - Window
 /*WORK  winVideo.Play();
     winVideo.HideCursor(1); */  // 1 - hide cursor, 0 - unhide cursor
 //  winVideo.WaitEnd();
 /*  while (playing) {
         if ( PeekMessage(&msg, 0, 0, 0, PM_REMOVE) ) {
             TranslateMessage( &msg );
             DispatchMessage( &msg );
             if (msg.message == WM_KEYDOWN) {
                 playing = false;
             }
         } else {
             if (winVideo.IsComplete()) {
                 playing = false;
             }
         }
     }*/
 /*WORK  winVideo.Stop();
     winVideo.Close(); */
 }
showRadar()
void showRadar (void)
sqrint()
int sqrint (int x)
theEND()
void theEND (void)
 {
     EffectsOff();
     //if(XGR_MAXX != 800)
     //  if(XGR_ReInit(800,600,emode)) ErrH.Abort(ErrorVideoMss);
 #ifdef ISCREEN
 //  if(Dead) ShowImage("resource\\iscreen\\bitmap\\corpse.bmp");
 //  ShowImage("resource\\iscreen\\bitmap\\email.bmp");
 #endif
 }
References EffectsOff().
uvsRestoreVanger()
void uvsRestoreVanger (void)
{
 #ifdef _ROAD_
     uvsElement* p = ETail;
     uvsVanger* v;
     v = Gamer;
     if (!NetworkON) {
         if( v -> Pescave) {
             addVanger(v,v->Pescave, 1);
         } else {
             addVanger(v,v->Pspot, 1);
         }
     } else {
         if( v -> Pescave ){
             int x, y;
             NetworkGetStart(v -> Pescave -> name, x, y);
             addVanger(v,x,y, 1);
         }else{
             int x, y;
             NetworkGetStart(v -> Pspot -> name, x, y);
             addVanger(v,x, y, 1);
         }
     }
     while(p){
         if(p -> type == UVS_OBJECT::VANGER ){
             v = (uvsVanger*)p;
             if ( v -> shape != UVS_VANGER_SHAPE::GAMER ){
                 if(v -> Pworld -> gIndex == CurrentWorld && (v -> status == UVS_VANGER_STATUS::MOVEMENT
                         || v -> status == UVS_VANGER_STATUS::FREE_MOVEMENT
                         || v -> status == UVS_VANGER_STATUS::AIM_HANDLE
                         || v -> status == UVS_VANGER_STATUS::RACE_HUNTER
                         || v -> status == UVS_VANGER_STATUS::GATHERING
                         || v -> status == UVS_VANGER_STATUS::WAIT_GAMER
                         || v -> status == UVS_VANGER_STATUS::RACE)){
                     if ( v -> Pmechos -> color < 3 &&
                         WorldTable[v -> Pmechos -> color] -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE &&
                         v -> shape != UVS_VANGER_SHAPE::GAMER_SLAVE){
                             v -> Pmechos -> color = 3;
                             if(v -> shape == UVS_VANGER_SHAPE::BUNCH_SLAVE)
                                 v -> shape = UVS_VANGER_SHAPE::RANGER;
                     }
                     addVanger(v,v -> pos_x,v -> pos_y);
                 }
             }
         }
         p = p -> enext;
     }
     StartWTRACK();
 #endif
 }
References addVanger(), UVS_VANGER_STATUS::AIM_HANDLE, UVS_VANGER_SHAPE::BUNCH_SLAVE, CurrentWorld, ETail, UVS_VANGER_STATUS::FREE_MOVEMENT, Gamer, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, UVS_VANGER_STATUS::GATHERING, UVS_VANGER_STATUS::MOVEMENT, NetworkGetStart(), NetworkON, uvsVanger::Pescave, uvsVanger::Pspot, UVS_VANGER_STATUS::RACE, UVS_VANGER_STATUS::RACE_HUNTER, UVS_VANGER_SHAPE::RANGER, StartWTRACK(), UVS_BUNCH_STATUS::UNABLE, UVS_OBJECT::VANGER, UVS_VANGER_STATUS::WAIT_GAMER, and WorldTable.
Referenced by LoadingRTO2::Init(), and uvsCloseQuant().
vMapInit()
void vMapInit (void)
 {
     if(RAM16) MAX_LINE = 900;
     vMap -> init();
     Verbose = 0;
 #ifdef SESSION
     linebuf = new uchar[H2_SIZE];
 #endif
 }
References H2_SIZE, MAX_LINE, RAM16, Verbose, and vMap.
Referenced by LoadingRTO2::Init(), and vMapPrepare().
xtDoneApplication()
void xtDoneApplication (void)
 {
     restore();
 }
References restore().
xtInitApplication()
int xtInitApplication (void)
{
     XGraphWndID = "VANGERS";
     char *tmp;
 #ifdef _DEMO_
     std::cout<<"\""<<XGraphWndID<<": One For The Road\" Cover Demo by K-D Lab (SDL Version)\n";
 #else
     if (lang() == GERMAN) {
         std::cout << "\"" << XGraphWndID << "\" by K-D Lab (SDL Version)\n";
         std::cout << "Release (DE)\n";
     } else if (lang() == RUSSIAN) {
         std::cout << "\"" << XGraphWndID << "\" by K-D Lab (SDL Version)\n";
         std::cout << "Release (RUS)\n";
     } else {
         std::cout << "\"" << XGraphWndID << ": One For The Road\" by K-D Lab (SDL Version)\n";
         std::cout << "Release (ENG)\n";
     }
 #ifdef BETA_TESTING
     std::cout<<nVER<<"\n";
 #endif
 #endif
     _MEM_STATISTIC_("BEGIN WORK WITH MEMORY -> ");
 #ifdef MEMORY_STATISTICS
     memstatInit();
 #endif
 //zmod
 #ifdef _ZMOD_DEBUG_
     ZLog = ZLogOpen();
 #endif
     //stalkerg:NEED SEE!!!
     //ComlineAnalyze(__internal_argc,__internal_argv);
 //  ErrH.SetRestore(restore); #not implement
 //  ErrH.SetFlags(XERR_CTRLBRK);
     RNDVAL = 83;
     realRNDVAL = SDL_GetTicks();
     costab();
     _MEM_STATISTIC_("COS TAB -> ");
     preCALC();
     _MEM_STATISTIC_("PRE CALC -> ");
     ilandPrepare();
     _MEM_STATISTIC_("ILANDPREPARE -> ");
 //  vMapPrepare(mapFName,WorldPrm);
     XStream ffo(roadFNTname, XS_IN);
     void *fo = new char[ffo.size()];
     ffo.read(fo, ffo.size());
     ffo.close();
     sysfont.init(fo);
     //zmod
     XStream zch_ffo(zchatFNTname, XS_IN);
     void *zch_fo = new char[zch_ffo.size()];
     zch_ffo.read(zch_fo, zch_ffo.size());
     zch_ffo.close();
     zchatfont.init(zch_fo);
     palTr = new PaletteTransform;
 #ifdef CDCHECK
     int getCDdrives(void);
     int isCDok(int);
     int d = getCDdrives();
     int mask = 1;
     int res = 0;
     for(int ii = 0;ii < 26;ii++,mask <<= 1)
         if(d & mask) res += isCDok(ii);
     if(!res) ErrH.Abort(AVInotFoundMSS);
 #endif
     SetupPath();
     _MEM_STATISTIC_("FONT -> ");
     emode = ExclusiveLog ? XGR_EXCLUSIVE : 0;
     //emode |= XGR_HICOLOR;
     if (!videoMode) {
         actintLowResFlag = 1;
 #ifdef ISCREEN
         videoMode = 2;
 #endif
     }
     videoMode = 1;
     float w = 800;
     float h = 600;
     switch (videoMode) {
         case 1:
             w = 800;
             h = 600;
             break;
         case 2:
             w = 1024;
             h = 768;
             break;
         case 3:
             w = 1280;
             h = 720;
     }
     if (XGR_Init(w, h, emode)) ErrH.Abort(ErrorVideoMss);
 //WORK  sWinVideo::Init();
 //  ::ShowCursor(0);
     //zmod
     if (!SkipIntro) {
 //      showModal( "resource\\video\\intro\\logo1.avi", 512, 384, w, h );
 //      showModal( "resource\\video\\intro\\logo2.avi", 512, 384, w, h );
 //      showModal( "resource\\video\\intro\\intro.avi", 512, 380, w, h );
     }
 //WORK  sWinVideo::Done();
     emode = ExclusiveLog ? XGR_EXCLUSIVE : 0;
 /*  switch(videoMode){
         case 0:
             if(XGR_ReInit(640,480,emode)) ErrH.Abort(ErrorVideoMss);
             break;
         case 1:
             if(XGR_ReInit(800,600,emode)) ErrH.Abort(ErrorVideoMss);
             break;
         case 2:
             if(XGR_ReInit(1024,768,emode)) ErrH.Abort(ErrorVideoMss);
             break;
         }
     if(XGR_GetVideoLine(1) - XGR_GetVideoLine(0) != XGR_MAXX)
         ErrH.Abort("Bad maxx",XGR_GetVideoLine(1) - XGR_GetVideoLine(0));
 */
     XGR_Fill(0);
     LoadingMessage(1);
     _MEM_STATISTIC_("INIT VIDEO -> ");
     InstallSOUND();
     LoadResourceSOUND("resource/sound/effects/", 0);
     SetSoundVolume(256);
     if (XJoystickInit()) {
         std::cout << "Joystick found\n";
         JoystickMode = JOYSTICK_Joystick;
     } else {
         std::cout << "Joystick not found" << std::endl;
     }
     //XSocketInit();
 #ifdef _DEBUG
     if(host_name && avaible_servers.talk_to_server(0,host_port,host_name))
         NetInit(avaible_servers.first());
 #endif
     _MEM_STATISTIC_("INIT SOUND -> ");
     // Runtime objects init...
     xtCreateRuntimeObjectTable(RTO_MAX_ID);
     GameQuantRTO *gqObj = new GameQuantRTO;
     MainMenuRTO *mmObj = new MainMenuRTO;
     EscaveRTO *eObj = new EscaveRTO;
     EscaveOutRTO *eoObj = new EscaveOutRTO;
     FirstEscaveRTO *fObj = new FirstEscaveRTO;
     FirstEscaveOutRTO *foObj = new FirstEscaveOutRTO;
     PaletteTransformRTO *pObj = new PaletteTransformRTO;
     LoadingRTO1 *lObj1 = new LoadingRTO1;
     LoadingRTO2 *lObj2 = new LoadingRTO2;
     LoadingRTO3 *lObj3 = new LoadingRTO3;
     ShowImageRTO *siObj = new ShowImageRTO;
     ShowAviRTO *saObj = new ShowAviRTO;
 //    siObj -> SetNumFiles(1);
 //    siObj -> SetName("resource\\iscreen\\bitmap\\kdlogo.bmp",0);
 //    siObj -> SetNext(RTO_MAIN_MENU_ID);
     if (lang() == RUSSIAN) {
         saObj->SetNumFiles(3);
         //saObj -> SetName("resource\\video\\intro\\logo1.avi",0);
         //saObj -> SetName("resource\\video\\intro\\logo2.avi",1);
         //saObj -> SetName("resource\\video\\intro\\intro.avi",2);
         //  saObj -> SetFlag(0,AVI_RTO_HICOLOR);
 //  saObj -> SetFlag(1,AVI_RTO_HICOLOR);
 //  saObj -> SetFlag(2,AVI_RTO_HICOLOR);
     } else {
         saObj->SetNumFiles(4);
         saObj->SetName("resource/video/intro/logo0.avi", 0);
         saObj->SetName("resource/video/intro/logo1.avi", 1);
         saObj->SetName("resource/video/intro/logo2.avi", 2);
         saObj->SetName("resource/video/intro/intro.avi", 3);
     //znfo commented in zmod
     //  saObj -> SetFlag(0,AVI_RTO_HICOLOR);
     //  saObj -> SetFlag(1,AVI_RTO_HICOLOR);
     //  saObj -> SetFlag(2,AVI_RTO_HICOLOR);
     //  saObj -> SetFlag(3,AVI_RTO_HICOLOR);
     //znfo
     }
     saObj -> SetNext(RTO_MAIN_MENU_ID);
     xtRegisterRuntimeObject(gqObj);
     xtRegisterRuntimeObject(mmObj);
     xtRegisterRuntimeObject(eObj);
     xtRegisterRuntimeObject(eoObj);
     xtRegisterRuntimeObject(fObj);
     xtRegisterRuntimeObject(foObj);
     xtRegisterRuntimeObject(pObj);
     xtRegisterRuntimeObject(lObj1);
     xtRegisterRuntimeObject(lObj2);
     xtRegisterRuntimeObject(lObj3);
     xtRegisterRuntimeObject(siObj);
     //xtRegisterRuntimeObject(saObj);
     if(RecorderMode)
         XRec.Open(RecorderName,RecorderMode);
     else
         RNDVAL = SDL_GetTicks();
     _MEM_STATISTIC_("AFTER FIRST INIT -> ");
 #ifdef CDCHECK
     mask = 1;
     res = 0;
     for(ii = 0;ii < 26;ii++,mask <<= 1)
         if(d & mask) res += isCDok(ii);
     if(!res) ErrH.Abort(AVInotFoundMSS);
 #endif
     if(!setTimerLog){
         GameQuantRTO* p = (GameQuantRTO*)xtGetRuntimeObject(RTO_GAME_QUANT_ID);
         p -> SetTimer(0);
         }
     if(RecorderMode){
         GameQuantRTO* p = (GameQuantRTO*)xtGetRuntimeObject(RTO_GAME_QUANT_ID);
 //      p -> SetTimer(1000/20);
         speed_correction_enabled = 0;
         }
     //STEAM
 #ifdef _STEAM_API_
     if ( SteamAPI_RestartAppIfNecessary( k_uAppIdInvalid ) ) {
         // if Steam is not running or the game wasn't started through Steam, SteamAPI_RestartAppIfNecessary starts the
         // local Steam client and also launches this game again.
         // Once you get a public Steam AppID assigned for this game, you need to replace k_uAppIdInvalid with it and
         // removed steam_appid.txt from the game depot.
         SDL_Quit();
     }
     // Init Steam CEG
     if ( !Steamworks_InitCEGLibrary() ) {
         std::cout<<"Steamworks_InitCEGLibrary() failed"<<std::endl;
         std::cout<<"Fatal Error, Steam must be running to play this game (InitDrmLibrary() failed)."<<std::endl;
         SDL_Quit();
     }
     // Initialize SteamAPI, if this fails we bail out since we depend on Steam for lots of stuff.
     // You don't necessarily have to though if you write your code to check whether all the Steam
     // interfaces are NULL before using them and provide alternate paths when they are unavailable.
     //
     // This will also load the in-game steam overlay dll into your process.  That dll is normally
     // injected by steam when it launches games, but by calling this you cause it to always load,
     // even when not launched via steam.
     if ( !SteamAPI_Init() ) {
         std::cout<<"SteamAPI_Init() failed"<<std::endl;
         std::cout<<"Fatal Error, Steam must be running to play this game (SteamAPI_Init() failed)."<<std::endl;
         SDL_Quit();
     }
     // set our debug handler
     //SteamClient()->SetWarningMessageHook( &SteamAPIDebugTextHook );
     // Tell Steam where it's overlay should show notification dialogs, this can be top right, top left,
     // bottom right, bottom left. The default position is the bottom left if you don't call this.
     // Generally you should use the default and not call this as users will be most comfortable with
     // the default position.  The API is provided in case the bottom right creates a serious conflict
     // with important UI in your game.
     SteamUtils()->SetOverlayNotificationPosition( k_EPositionTopRight );
 #endif
 #if defined(__unix__) || defined(__linux__) || defined(__APPLE__)
     std::cout<<"Set locale. ";
     char* res = setlocale(LC_NUMERIC, "POSIX");
     std::cout<<"Result:"<<res<<std::endl;
 #endif
     if(SkipIntro)
         return RTO_MAIN_MENU_ID;
     return RTO_MAIN_MENU_ID;
 }
References _MEM_STATISTIC_, XErrorHandler::Abort(), actintLowResFlag, avaible_servers, AVInotFoundMSS, XStream::close(), costab(), emode, ErrH, ErrorVideoMss, ExclusiveLog, XTList< Type >::first(), GERMAN, host_name, host_port, ilandPrepare(), InstallSOUND(), JOYSTICK_Joystick, JoystickMode, lang(), LoadingMessage(), LoadResourceSOUND(), NetInit(), nVER, XRecorder::Open(), palTr, preCALC(), XStream::read(), realRNDVAL, RecorderMode, RecorderName, RNDVAL, roadFNTname, RTO_GAME_QUANT_ID, RTO_MAIN_MENU_ID, RTO_MAX_ID, RUSSIAN, ShowImageRTO::SetName(), ShowImageRTO::SetNumFiles(), SetSoundVolume(), setTimerLog, SetupPath(), XStream::size(), SkipIntro, speed_correction_enabled, sysfont, ServersList::talk_to_server(), videoMode, XGR_EXCLUSIVE, XGR_Fill, XGR_Init, XGraphWndID, XJoystickInit(), XRec, XS_IN, xtCreateRuntimeObjectTable(), xtGetRuntimeObject(), xtRegisterRuntimeObject(), zchatFNTname, and zchatfont.
Variable Documentation
_Timer_
clock_t _Timer_
Referenced by GameQuantRTO::Quant().
aciGroundPressingEnabled
int aciGroundPressingEnabled extern
Referenced by MainMenuRTO::Finit().
aciKeyboardLocked
int aciKeyboardLocked extern
Referenced by acsQuant(), and KeyCenter().
activeWTRACK
int activeWTRACK extern
Referenced by StopCDTRACK().
AuxRqCounter
int AuxRqCounter
AVI_index
int* AVI_index extern
Referenced by RegisterValues().
AVInotFound
const char* AVInotFound = "Error video initialization"
Referenced by iScreenObject::init(), and iAVIElement::load().
AVInotFoundMSS
const char* AVInotFoundMSS = "Please ensure that the VANGERS CD-ROM is in the drive!"
Referenced by EscaveRTO::Finit(), and xtInitApplication().
BackgroundSound
int BackgroundSound extern
Referenced by MainMenuRTO::Finit().
beebos
int beebos
Referenced by ComlineAnalyze().
camera_moving_xy_enable
int camera_moving_xy_enable extern
Referenced by camera_quant(), camera_reset(), and KeyCenter().
camera_moving_z_enable
int camera_moving_z_enable extern
Referenced by camera_quant(), camera_reset(), and KeyCenter().
camera_rotate_enable
int camera_rotate_enable extern
Referenced by camera_quant(), camera_reset(), and KeyCenter().
camera_slope_enable
int camera_slope_enable extern
Referenced by camera_quant(), camera_reset(), and KeyCenter().
camera_slope_min
int camera_slope_min extern
Referenced by camera_quant().
camera_zmin
int camera_zmin extern
Referenced by camera_quant(), iGameMap::change(), KeyCenter(), and iGameMap::reset().
CO
int* CO
Referenced by COS(), costab(), ItemsDispatcher::CryptQuant(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), ItemsDispatcher::Open(), PerpSlopTurn(), DangerDataType::Quant(), SlopTurnSkip(), and vrtMap::turning().
ColorShow
int ColorShow = 1
curGMap
iGameMap* curGMap
Referenced by calc_view_factors(), camera_direct(), camera_quant(), creat_poster(), iGameMap::draw(), gameQuant(), LoadingRTO2::Init(), ActionUnit::InitEnvironment(), KeyCenter(), VangerUnit::NetCreateVanger(), MobileLocation::quant(), GameQuantRTO::Quant(), VangerUnit::Quant(), VangerUnit::SendCameraData(), and set_screen().
CurrentWorld
int CurrentWorld = 0
Referenced by aciPrepareWorldsMenu(), aciWorldLinksON(), addVanger(), aiMessageTouch(), uvsBunch::begin_harvest(), BunchEvent(), VangerUnit::CalcAiFactor(), ChangeVanger(), ChangeWorld(), CheckPlayerList(), ClearBarell(), ItemsDispatcher::Close(), CloseBunchPal(), CloseCyclicPal(), BulletObject::CreateBullet(), DangerDataType::CreateDanger(), ItemsDispatcher::CreateEnableCrypt(), CreatePhantomTarget(), ItemsDispatcher::CryptQuant(), VangerUnit::Destroy(), TntCreature::Destroy(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), DestroySmoothCheck(), DestroySpot(), TrackUnit::DrawMechosParticle(), ParticleObject::DrawQuant(), HordeObject::DrawQuant(), VangerUnit::DrawQuant(), uvsVanger::emuQuant(), BulletObject::Event(), DangerDataType::FireWork(), SkyFarmerList::Free(), FreeFarmer(), uvsVanger::gatherCirt(), GeneralSystemFree(), GeneralSystemInit(), GeneralSystemOpen(), GeneralTableOpen(), uvsVanger::get_shop(), GetEscaveDist(), getObjectPosition(), actIntDispatcher::i_finit(), actIntDispatcher::i_init(), LoadingRTO2::Init(), FirstEscaveRTO::Init(), actIntDispatcher::init(), ClefList::Init(), SkyFarmerList::Init(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), InsectList::Init(), VangerUnit::InitAI(), VangerUnit::InitEnvironment(), LoadVPR(), MLload(), VangerUnit::NetCreateVanger(), TntCreature::NetDestroy(), TntCreature::NetQuant(), NetworkWorldOpen(), ActionDispatcher::NewFunction(), ObjectDestroy(), ItemsDispatcher::Open(), ActionDispatcher::Open(), TiristorEngine::Open(), ItemGenerator::Open(), GameObjectDispatcher::Open(), OpenCyclicPal(), PalettePrepare(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), ActionDispatcher::PromptChangeCycle(), ActionDispatcher::PromptQuant(), GameObjectDispatcher::Quant(), StuffObject::Quant(), GloryPlace::Quant(), VangerUnit::Quant(), ActionDispatcher::Quant(), DoorEngine::Quant(), ItemGenerator::Quant(), TntCreature::Quant(), DangerDataType::Quant(), uvsBunch::Quant(), uvsWorld::Quant(), uvsFlyFarmer::Quant(), uvsDolly::Quant(), RadialRender(), VangerUnit::SensorQuant(), PalPoint::Set(), SoundQuant(), StartWTRACK(), StaticOpen(), VangerUnit::TerrainQuant(), thief_on_world(), VangerUnit::UsingCrotrig(), uvsCheckVangerTabuTask(), uvsCloseQuant(), uvsCreateNetVanger(), uvsFreeDolly(), uvsKronDeleteItem(), uvsPrepareQuant(), uvsRestoreVanger(), uvsWorld::uvsWorld(), uvsWorldReload(), and VLload().
CurrentWorldLightParam
int CurrentWorldLightParam extern
Referenced by PalPoint::Quant(), and PalPoint::Set().
Dead
int Dead
Referenced by uvsVanger::destroy(), and MainMenuRTO::Init().
debug_view
int debug_view = 0
Referenced by vrtMap::scaling().
DepthShow
int DepthShow
Referenced by calc_view_factors(), Object::draw(), iGameMap::draw(), ActionUnit::InitEnvironment(), Object::pixel_draw(), ParticleObject::Quant(), WaterParticleObject::Quant(), TargetParticleObject::Quant(), GameObjectDispatcher::Quant(), iGameMap::reset(), S2G(), vrtMap::scaling(), smart_putspr(), smart_putspr_f(), GameObjectDispatcher::Sort(), and Object::update_coord().
DIBLog
int DIBLog = 0
Referenced by ComlineAnalyze(), and PaletteTransform::quant().
EffectInUse
int EffectInUse
Referenced by LoadingRTO1::Init().
EffectInUsePriory
int EffectInUsePriory extern
Referenced by EffectsOff(), EffectsOn(), EffectsOnOff(), LoadingRTO1::Init(), and SetSoundVolume().
emode
int emode
Referenced by actIntDispatcher::flush(), i_change_res(), actIntDispatcher::i_init(), and xtInitApplication().
EngineNoise
int EngineNoise extern
Referenced by MainMenuRTO::Finit().
ErrHExcept
int ErrHExcept = 1
ErrorVideoMss
const char* ErrorVideoMss = "Error video initialization"
Referenced by xtInitApplication().
ExclusiveLog
int ExclusiveLog = 1
Referenced by ComlineAnalyze(), and xtInitApplication().
FirstDraw
int FirstDraw = 1
Referenced by iGameMap::change(), and iGameMap::draw().
fout
XStream fout extern
Referenced by restore().
fps_frame
int fps_frame
Referenced by GameQuantRTO::Quant().
FPS_PERIOD
const int FPS_PERIOD = 50
Referenced by GameQuantRTO::Quant().
fps_start
int fps_start
Referenced by GameQuantRTO::Quant().
fps_string
char fps_string[20]
Referenced by iGameMap::draw(), and GameQuantRTO::Quant().
frame
int frame
Referenced by VangerUnit::Action(), iGameMap::draw(), ParticleMapProcess::process(), GameQuantRTO::Quant(), aiMessageList::Send(), short_network_analysis(), and VangerUnit::TouchSensor().
GameOverTrigger
int GameOverTrigger = -1
Referenced by LoadingRTO3::Init(), and ShowImageRTO::Init().
GameQuantReturnValue
int GameQuantReturnValue = 0
Referenced by uvsVanger::destroy(), VangerUnit::Destroy(), actIntDispatcher::flush(), uvsVanger::get_shop(), GameQuantRTO::Quant(), uvsVanger::Quant(), and VangerUnit::SensorQuant().
Geo
int Geo = 0
host_name
char* host_name = 0
Referenced by ComlineAnalyze(), ServersList::find_servers_in_the_internet(), and xtInitApplication().
host_port
int host_port = DEFAULT_SERVER_PORT
Referenced by ComlineAnalyze(), ServersList::find_servers_in_the_internet(), and xtInitApplication().
idOS
int idOS
Referenced by LoadingRTO2::Init().
inHighPriority
int inHighPriority
Referenced by ComlineAnalyze().
inTRall
int inTRall
iscrPal
uchar* iscrPal extern
Referenced by aciShowLocation(), aciShowLocationPicture(), LoadingRTO1::Init(), MainMenuRTO::Init(), and iScrQuantFinit().
light_modulation
int light_modulation extern
Referenced by calc_view_factors(), and PalettePrepare().
loadingStatus
int loadingStatus = 1
Referenced by gameQuant(), and LoadingRTO2::Init().
MainRqCounter
int MainRqCounter
mapFName
const char* mapFName = "wrlds.dat"
Referenced by ComlineAnalyze(), GetKeepSpace(), LoadingRTO2::Init(), and KeepCleanUp().
message_mode
int message_mode = 0
Referenced by iGameMap::draw(), and KeyCenter().
MMXsuppress
int MMXsuppress
Referenced by ComlineAnalyze().
msg_buf
XBuffer msg_buf(16000)
Referenced by Object::analysis(), Object::basic_mechous_analysis(), and iGameMap::draw().
MuteLog
int MuteLog = 0
Referenced by ComlineAnalyze(), iGameMap::draw(), iHandleExtEvent(), LoadingRTO1::Init(), and pal_iter0().
network_log
int network_log = 0
Referenced by ComlineAnalyze().
NumHumanModel
int NumHumanModel extern
Referenced by addVanger(), ComlineAnalyze(), and VangerUnit::keyhandler().
nVER
const char* nVER = "Patch 4.20"
Referenced by xtInitApplication().
page
int page
palbuf
unsigned char* palbuf
Referenced by aOutStr(), ChangeWorld(), GeneralTableOpen(), PassageImageType::Hide(), LoadingRTO2::Init(), LoadingRTO3::Init(), pal_iter(), pal_iter0(), pal_iter1(), PalettePrepare(), PalPoint::Quant(), VangerUnit::Quant(), PalPoint::Set(), PassageImageType::Show(), and uvsCloseQuant().
palbufA
unsigned char * palbufA
Referenced by GeneralTableFree(), GeneralTableInit(), and PalettePrepare().
palbufBlack
unsigned char * palbufBlack
Referenced by GeneralTableFree(), and GeneralTableInit().
palbufC
unsigned char * palbufC
Referenced by GeneralTableFree(), GeneralTableInit(), and PalettePrepare().
palbufInt
unsigned char * palbufInt
Referenced by PalettePrepare().
palbufOrg
unsigned char * palbufOrg
Referenced by GeneralTableFree(), GeneralTableInit(), GeneralTableOpen(), LoadingRTO2::Init(), PalettePrepare(), PalPoint::Quant(), VangerUnit::Quant(), PalPoint::Set(), and uvsCloseQuant().
PalIterLock
int PalIterLock = 0
Referenced by VangerUnit::AddFree(), actIntDispatcher::flush(), actIntDispatcher::i_init(), actIntDispatcher::pal_flush(), GameQuantRTO::Quant(), and VangerUnit::Quant().
Pause
int Pause = 0
Referenced by actIntDispatcher::flush(), KeyCenter(), and GameQuantRTO::Quant().
prev_frame_time
int prev_frame_time = 0
Referenced by calc_view_factors().
Quit
int Quit = 1
Referenced by LoadingRTO1::Init(), LoadingRTO3::Init(), and MainMenuRTO::Init().
RAM16
int RAM16
Referenced by aciHandleCameraEvent(), camera_quant(), vrtMap::delink(), vrtMap::increase(), LoadingRTO1::Init(), EffectDispatcher::Init(), ItemsDispatcher::Init(), vrtMap::link(), vrtMap::linkC(), vMapInit(), and YSetup().
realRNDVAL
unsigned realRNDVAL = 83
Referenced by xtInitApplication().
RecorderMode
int RecorderMode = 0
Referenced by ComlineAnalyze(), iLoadControls(), iLoadData(), iSaveControls(), iSaveData(), and xtInitApplication().
RecorderName
char* RecorderName = NULL
Referenced by ComlineAnalyze(), and xtInitApplication().
Redraw
int Redraw = 1
Referenced by aciCancelMatrix(), aciCloseGate(), aciHideLocation(), aciOpenGate(), aciShowLocation(), aciShowLocationPicture(), aciShowScMatrix(), aciSwapMatrices(), iGameMap::change(), ChangeWorld(), LoadingRTO2::Init(), GameQuantRTO::Quant(), and set_screen().
RNDVAL
unsigned RNDVAL = 83
Referenced by RND(), and xtInitApplication().
roadFNTname
const char* roadFNTname = "road.fnt"
Referenced by xtInitApplication().
RQ_THREAD_COUNT
int RQ_THREAD_COUNT extern
setTimerLog
int setTimerLog = 1
Referenced by ComlineAnalyze(), and xtInitApplication().
shotNum
int shotNum
ShowImageKeyFlag
int ShowImageKeyFlag = 0
Referenced by ShowImageRTO::Init(), ShowImageRTO::Quant(), and ShowImageKeyPress().
ShowImageMouseFlag
int ShowImageMouseFlag = 0
Referenced by ShowImageRTO::Init(), ShowImageRTO::Quant(), and ShowImageMousePress().
SI
int* SI
Referenced by costab(), ItemsDispatcher::CryptQuant(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroySmooth(), ParticleObject::DrawQuant(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), ItemsDispatcher::Open(), PerpSlopTurn(), DangerDataType::Quant(), SIN(), SlopTurnSkip(), vrtMap::turning(), xDestroySpot(), and xRestoreDestroySpot().
SkipCD
int SkipCD
Referenced by ComlineAnalyze().
SkipIntro
int SkipIntro = 0
Referenced by ComlineAnalyze(), and xtInitApplication().
SkipShow
int SkipShow = 1
Referenced by iGameMap::draw().
SlopeQualityFactor
int SlopeQualityFactor extern
Referenced by PerpSlopTurn().
SoundVolumePanning
int SoundVolumePanning extern
Referenced by MainMenuRTO::Finit().
speed_correction_enabled
int speed_correction_enabled = 1
Referenced by calc_view_factors(), and xtInitApplication().
StandLog
int StandLog
Referenced by iGameMap::draw().
StartMainQuantFlag
int StartMainQuantFlag = 0
Referenced by LoadingRTO2::Init().
stop_all_except_me
int stop_all_except_me = 0
stop_camera
int stop_camera extern
Referenced by camera_quant().
sysfont
sqFont sysfont
Referenced by iGameMap::draw(), LoadingMessage(), WorldScreen::Quant(), ScreenQuant(), and xtInitApplication().
TimerMode
int TimerMode = 1
Referenced by ComlineAnalyze().
TotalDrawFlag
int TotalDrawFlag = 1
Referenced by GameObjectDispatcher::DrawQuant(), and vrtMap::scaling().
Verbose
int Verbose
Referenced by vMapInit().
videoMode
int videoMode = 1
Referenced by ComlineAnalyze(), and xtInitApplication().
view_lock
int view_lock = 0
vSoundOFF
int vSoundOFF
Referenced by GameQuantRTO::Quant().
vSoundON
int vSoundON
Referenced by GameQuantRTO::Quant().
winVideo
sWinVideo winVideo
WorldLightParam
int WorldLightParam[WORLD_MAX][3] extern
Referenced by PalettePrepare().
WorldPrm
int WorldPrm
Referenced by ComlineAnalyze().
XGR_FULL_SCREEN
bool XGR_FULL_SCREEN extern
Referenced by XGR_Screen::flip(), XGR_Screen::init(), and XGR_Screen::set_fullscreen().
XSIDE
int XSIDE = 200
Referenced by LoadingRTO1::Init(), and LoadingRTO2::Init().
XSIZE
int XSIZE = 2*XSIDE + 1
Referenced by LoadingRTO1::Init().
YSIDE
int YSIDE = 170
Referenced by LoadingRTO1::Init(), and LoadingRTO2::Init().
YSIZE
int YSIZE = 2*YSIDE + 1
Referenced by LoadingRTO1::Init().
zchatFNTname
const char* zchatFNTname = "zfont.fnt"
Referenced by xtInitApplication().
zchatfont
sqFont zchatfont
Referenced by iGameMap::draw(), and xtInitApplication().
zoom_delta
int zoom_delta
zoom_threshold
int zoom_threshold