Vangers: src/uvs/screen.h File Reference
screen.h File Reference
Classes
struct Place
struct WorldScreen
Functions
void ScreenQuant (void)
void StandScreenPrepare (void)
Function Documentation
ScreenQuant()
void ScreenQuant (void)
 {
 #ifdef TINY_MODE
     sysfont.draw(3,3,ConTimer.GetTime());
 #else
     sysfont.draw(XGR_MAXX - 8*18 - 3,3,ConTimer.GetTime());
 #endif
     for(int i = 0;i < MAIN_WORLD_MAX;i++)
         scrTable[i] -> Quant();
     static XBuffer buf;
 #ifndef TINY_MODE
     buf.init();
     buf < "Total: " <= c_All_Number < " S: " <= c_S_Number < " R: " <= c_R_Number < " A: " <= c_A_Number;
     sysfont.draw(3,3,(char*)buf);
 #endif
     uvsElement* p = ETail;
     int ind;
     while(p){
         switch(p -> type){
             case UVS_OBJECT::DOLLY:
                 ind = ((uvsDolly*)p) -> Pworld -> gIndex;
                 if(ind != -1) scrTable[ind] -> DollyQuant((uvsDolly*)p);
                 break;
             case UVS_OBJECT::VANGER:
                 ind = ((uvsVanger*)p) -> Pworld -> gIndex;
                 if(ind != -1) scrTable[ind] -> VangerQuant((uvsVanger*)p);
                 break;
             }
         p = p -> enext;
         }
 }
References c_A_Number, c_All_Number, c_R_Number, c_S_Number, ConTimer, UVS_OBJECT::DOLLY, ETail, uvsContimer::GetTime(), XBuffer::init(), MAIN_WORLD_MAX, scrTable, sysfont, UVS_OBJECT::VANGER, and XGR_MAXX.
Referenced by iGameMap::draw().
StandScreenPrepare()
void StandScreenPrepare (void)
 {
 #ifdef TINY_MODE
     const int wsy = 64;
 #else
     const int wsy = 145;
 #endif
     for(int y = 80 + 16 + 2,i = 0;i < MAIN_WORLD_MAX;i++, y += wsy + 3) scrTable[i] = new WorldScreen(y,wsy,getWorld(i));
 }
References getWorld(), MAIN_WORLD_MAX, and scrTable.
Referenced by LoadingRTO2::Init().