Vangers: src/iscreen/script.cpp File Reference
script.cpp File Reference
#include <zlib.h>
#include "../global.h"
#include "s_mem.h"
#include "iscript.h"
#include "zip.h"
Macros
#define SCRIPT_CONV_BUF_SIZE 2048
#define MAX_SCAN_KEY 89
Functions
void handle_error (const char *prefix, const char *subj=NULL)
int GetKeyCode (char *p)
int GetOptionID (char *p)
int aGetOptionID (char *p)
int acsGetOptionID (char *p)
Variables
char * sMemHeap
unsigned sHeapOffs = 0
unsigned sHeapSize = 0
const int MAX_STRIP_CHAR = 6
ScriptFile * script
scMathExpression * mExpr
Macro Definition Documentation
MAX_SCAN_KEY
#define MAX_SCAN_KEY 89
SCRIPT_CONV_BUF_SIZE
#define SCRIPT_CONV_BUF_SIZE 2048
Function Documentation
acsGetOptionID()
int acsGetOptionID (char * p)
 {
     int i;
     if(!p) handle_error("Null ID pointer");
     for(i = 0; i < MAX_OPTION; i ++){
         if(!strcmp(p,acsOptIDs[i]))
             return i;
     }
     return -1;
 }
References handle_error(), and MAX_OPTION.
Referenced by ScriptFile::read_option().
aGetOptionID()
int aGetOptionID (char * p)
 {
     int i;
     if(!p) handle_error("Null ID pointer");
     for(i = 0; i < MAX_OPTION; i ++){
         if(!strcmp(p,aOptIDs[i]))
             return i;
     }
     return -1;
 }
References handle_error(), and MAX_OPTION.
Referenced by ScriptFile::read_option().
GetKeyCode()
int GetKeyCode (char * p)
 {
     char* stopstr = p;
     return strtol(p,&stopstr,16);
 }
Referenced by ScriptFile::read_key().
GetOptionID()
int GetOptionID (char * p)
 {
     int i;
     if(!p) handle_error("Null ID pointer");
     for(i = 0; i < MAX_OPTION; i ++){
         if(!strcmp(p,OptIDs[i]))
             return i;
     }
     return -1;
 }
References handle_error(), and MAX_OPTION.
Referenced by ScriptFile::read_option().
handle_error()
void handle_error (const char * prefix, const char * subj = NULL)
 {
     XBuffer XBuf;
 #ifndef _BINARY_SCRIPT_
     XBuf < prefix < "...";
     ErrH.Abort(XBuf.GetBuf(),XERR_USER,script -> get_cur_str() + 1,subj);
 #else
     XBuf < prefix < "...";
     ErrH.Abort(XBuf.GetBuf(),XERR_USER,script -> binConv -> tell(),subj);
 #endif
 }
References XErrorHandler::Abort(), ErrH, XBuffer::GetBuf(), script, and XERR_USER.
Referenced by acsGetOptionID(), acsParseScript(), addObjID(), aGetOptionID(), aParseScript(), build_links(), end_block(), GetOptionID(), init_command(), link_object(), new_object(), ParseScript(), ScriptFile::prepare(), and ScriptFile::strip_comments().
Variable Documentation
MAX_STRIP_CHAR
const int MAX_STRIP_CHAR = 6
Referenced by ScriptFile::prepare().
mExpr
scMathExpression* mExpr
script
ScriptFile* script
Referenced by acsParseScript(), aParseScript(), handle_error(), init_event_code(), load_item_shape(), load_matrix(), load_slot_nums(), load_slot_types(), new_element(), and ParseScript().
sHeapOffs
unsigned sHeapOffs = 0
sHeapSize
unsigned sHeapSize = 0
sMemHeap
char* sMemHeap