Vangers: src/terra/slopskip.cpp File Reference
slopskip.cpp File Reference
#include "../global.h"
#include "../3d/3d_math.h"
#include "vmap.h"
Macros
#define ROX(x) (x << (16 - H_POWER))
#define ROY(y) (y << (16 - V_POWER))
#define BitMap vrtMap
#define uv2y(u, v) (((Auy*(u) + Avy*(v) + Awy*F) >> 8)*H/((Auz*(u) + Avz*(v) + Awz*F) >> 8))
Functions
uchar ** SetSkipLineTable (uchar **lt, int ky, int Ymin, int Ymax)
int pre_calc_fy (int i, int XDstSize, int YDstSize, int Awy, int Awz, int Auy, int Avy, int Avz, int F, int H, int cy)
void SlopTurnSkip (int Turn, int Slop, int H, int F, int cx, int cy, int xc, int yc, int XDstSize, int YDstSize)
Variables
int ParaMapSkipFactor0 = 100
int ParaMapSkipFactor = 100
int ParaScreenSkipFactor0 = 100
int ParaScreenSkipFactor = 0
Macro Definition Documentation
BitMap
#define BitMap vrtMap
ROX
#define ROX (x) (x << (16 - H_POWER))
ROY
#define ROY (y) (y << (16 - V_POWER))
uv2y
#define uv2y (u, v) (((Auy*(u) + Avy*(v) + Awy*F) >> 8)*H/((Auz*(u) + Avz*(v) + Awz*F) >> 8))
Function Documentation
pre_calc_fy()
int pre_calc_fy (int i, int XDstSize, int YDstSize, int Awy, int Awz, int Auy, int Avy, int Avz, int F, int H, int cy) inline
{
     int u = -XDstSize/2;
     int v = -YDstSize/2 + i;
     int z = (v*Avz + F*Awz) >> 16;
     if(!z) z = 1;
     int fy = H*((u*Auy + v*Avy + F*Awy) >> 4)/z << 4;
     int k_xscr_y = H*Auy/z;
     fy += cy;
     return (fy + k_xscr_y*i) >> 16;
 }
Referenced by SlopTurnSkip().
SetSkipLineTable()
uchar** SetSkipLineTable (uchar ** lt, int ky, int Ymin, int Ymax)
 {
     Ymin = YCYCL(Ymin);
     Ymax = YCYCL(Ymax);
 #ifdef TURN_TEST
     Ymin = 0;
     Ymax = V_SIZE;
 #endif
     if (ky <= 1 << 16)
         return lt;
     unsigned int tmpy;
     tmpy = Ymin << 16;
     tmpy = tmpy - tmpy%ky;
     unsigned i, y;
     if (Ymin < Ymax) {
         for (i = Ymin; (int)i < Ymax; i = YCYCL(i + 1)) {
             y = YCYCL(tmpy >> 16);
             SkipLineTable[i] = lt[y];
             if (y < i) {
                 tmpy += ky;
             }
         }
     } else {
         for (i = Ymin; i < V_SIZE; i++) {
             y = YCYCL(tmpy >> 16);
             SkipLineTable[i] = lt[y];
             if (y - i) {
                 tmpy += ky;
             }
         }
         for (i = 0; (int)i <= Ymax; i++) {
             y = YCYCL(tmpy >> 16);
             SkipLineTable[i] = lt[y];
             if (y - i) {
                 tmpy += ky;
             }
         }
     }
     return SkipLineTable;
 }
References SkipLineTable, V_SIZE, and YCYCL.
Referenced by PerpSlopTurn(), and SlopTurnSkip().
SlopTurnSkip()
void SlopTurnSkip (int Turn, int Slop, int H, int F, int cx, int cy, int xc, int yc, int XDstSize, int YDstSize)
 {
     Slop = -Slop;
     int sinAlpha,cosAlpha;
     int sinTetta,cosTetta;
 #ifdef __ZORTECHC__
     char* vp = _video + (yc - YDstSize)*XGR_MAXX + (xc - XDstSize);
 #else
     char* vp = (char*)XGR_VIDEOBUF + (yc - YDstSize)*XGR_MAXX + (xc - XDstSize);
 #endif
     XDstSize = 2*XDstSize;
     YDstSize = 2*YDstSize;
     sinAlpha = SI[rPI(Turn)];
     cosAlpha = CO[rPI(Turn)];
     sinTetta = SI[rPI(Slop)];
     cosTetta = CO[rPI(Slop)];
     int CenterDistance = H;
     H = H*cosTetta >> 16;
     int Aux,Avx,Awx;
     int Auy,Avy,Awy;
     int Auz,Avz,Awz;
     Aux = cosAlpha;
     Avx = (sinAlpha >> 1)*(cosTetta >> 1) >> 14;
     Awx = (sinAlpha >> 1)*(sinTetta >> 1) >> 14;
     Auy = -sinAlpha;
     Avy = (cosAlpha >> 1)*(cosTetta >> 1) >> 14;
     Awy = (cosAlpha >> 1)*(sinTetta >> 1) >> 14;
     Auz = 0;
     Avz = -sinTetta;
     Awz = cosTetta;
     cx -= Awx*H/Awz;
     cy -= Awy*H/Awz;
     cx = (cx & clip_mask_x) << 16;
     cy = (cy & clip_mask_y) << 16;
     int y0,y1,y2,y3;
 #define uv2y(u,v) (((Auy*(u) + Avy*(v) + Awy*F) >> 8)*H/((Auz*(u) + Avz*(v) + Awz*F) >> 8))
     y0 = uv2y(XDstSize/2,YDstSize/2) + (cy >> 16);
     y1 = uv2y(-XDstSize/2,YDstSize/2) + (cy >> 16);
     y2 = uv2y(XDstSize/2,-YDstSize/2) + (cy >> 16);
     y3 = uv2y(-XDstSize/2,-YDstSize/2) + (cy >> 16);
 //#ifndef TURN_TEST
 // #ifndef _VTEST_
 //  vMap -> request(MIN(MIN(MIN(y0,y1),y2),y3) - MAX_RADIUS/2, MAX(MAX(MAX(y0,y1),y2),y3) + MAX_RADIUS/2, 0, 0);
 //  uchar** lt = vMap -> lineTcolor;
 // #else
 //  uchar** lt = lineTcolor;
 // #endif
 // #else
 //  uchar** lt = TextureDataTable;
 //  uchar** ht = HeightDataTable;
 // #endif
     int first_line = pre_calc_fy(0, XDstSize, YDstSize, Awy, Awz, Auy, Avy, Avz, F, H, cy);
     int last_line = pre_calc_fy(YDstSize - 1, XDstSize, YDstSize, Awy, Awz, Auy, Avy, Avz, F, H, cy);
     int Ymin = MIN(MIN(MIN(MIN(MIN(y0,y1),y2),y3), first_line), last_line);
     int Ymax = MAX(MAX(MAX(MAX(MAX(y0,y1),y2),y3), first_line), last_line);
     #ifndef TURN_TEST
         Ymin -= 30;
         Ymax += 30;
     #endif
     vMap->request(
         Ymin - MAX_RADIUS/2,
         Ymax + MAX_RADIUS/2,
         0,
         0
     );
     uchar** lt = vMap -> lineTcolor;
     int z;
     z = F*Awz >> 16;
     if(!z) z = 1;
     int ky = ((ParaMapSkipFactor0 << 16) + abs(sinAlpha)*ParaMapSkipFactor)/100*CenterDistance/F;
     uchar** slt = SetSkipLineTable(lt, ky, Ymin - MAX_RADIUS/2, Ymax + MAX_RADIUS/2);
 #ifdef TURN_TEST
     ::MapSkipFactor = ky;
 #endif
     int k_xscr_x,k_xscr_y;
     int i,fx,fy;
     i = 0;
     int i_float = 0;
     int ScreenSkipFactor;
     ScreenSkipFactor = (ParaScreenSkipFactor0 << 16)/100;
     ScreenSkipFactor += abs(sinAlpha)*ParaScreenSkipFactor/100;
 #ifdef TURN_TEST
     ::ScreenSkipFactor = ScreenSkipFactor;
 #endif
     int DrawPrev = 0;
     while (i < YDstSize) {
         char* vpp = vp + XGR_MAXX*i;
         int u = -XDstSize/2;
         int v = -YDstSize/2 + i;
         int z = (v*Avz + F*Awz) >> 16;
         if(!z) z = 1;
         fx = H*((u*Aux + v*Avx + F*Awx) >> 4)/z << 4;
         fy = H*((u*Auy + v*Avy + F*Awy) >> 4)/z << 4;
         k_xscr_x = H*Aux/z;
         k_xscr_y = H*Auy/z;
         fx += cx;
         fy += cy;
         if (DrawPrev) {
             k_xscr_x *= 2;
             k_xscr_y *= 2;
             for (int j = 0; j < XDstSize; j += 2) {
                 int tmp = *(slt[YCYCL(fy >> 16)] + XCYCL(fx >> 16));
                 *vpp++ = tmp;
                 *vpp++ = tmp;
                 fx += k_xscr_x;
                 fy += k_xscr_y;
             }
         } else {
             for (int j = 0; j < XDstSize; j++) {
                 *vpp++ = *(slt[YCYCL(fy >> 16)] + XCYCL(fx >> 16));
                 fx += k_xscr_x;
                 fy += k_xscr_y;
             }
         }
         int tmp_i = i_float >> 16;
         i_float += ScreenSkipFactor;
         DrawPrev = (i_float >> 16) > tmp_i + 1;
         i++;
     }
 }
References _video, clip_mask_x, clip_mask_y, CO, MAX, MAX_RADIUS, MIN, ParaMapSkipFactor, ParaMapSkipFactor0, ParaScreenSkipFactor, ParaScreenSkipFactor0, pre_calc_fy(), vrtMap::request(), rPI, SetSkipLineTable(), SI, uv2y, vMap, XCYCL, XGR_MAXX, XGR_VIDEOBUF, and YCYCL.
Referenced by iGameMap::draw(), and PerpSlopTurn().
Variable Documentation
ParaMapSkipFactor
int ParaMapSkipFactor = 100
Referenced by PerpSlopTurn(), and SlopTurnSkip().
ParaMapSkipFactor0
int ParaMapSkipFactor0 = 100
Referenced by SlopTurnSkip().
ParaScreenSkipFactor
int ParaScreenSkipFactor = 0
Referenced by SlopTurnSkip().
ParaScreenSkipFactor0
int ParaScreenSkipFactor0 = 100
Referenced by SlopTurnSkip().