Vangers: src/sound/sound.cpp File Reference
sound.cpp File Reference
#include "../global.h"
#include "../lang.h"
#include "hmusic.h"
#include "hsound.h"
Classes
struct SndParameters
Macros
#define EFFECT_KHZ 44100
#define SPEECH_KHZ 22050
#define DELTA_KHZ 2000
#define DISTANCE_TO_TOWN 2000
#define DISTANCE_TO_SICRET 512
#define DB_MIN -10000
#define DB_MAX 0
#define DB_SIZE 10000
Functions
int GetEscaveDist (void)
int getWID (void)
void LoadMotorSound (void)
void InstallSOUND (void)
void RestoreSOUND (void)
void SetMotorFile (int type)
void SetMotorSound (int speed)
void LoadResourceSOUND (const char *path_name, int surface)
void LocalEffectFree (void)
void SoundEscaveOff (void)
void StartEFFECT (EFFECT_VALUE EffectValue, int loop, int pan)
void StopEFFECT (EFFECT_VALUE EffectValue)
void StartSPEECH (SPEECH_VALUE SpeechValue)
void EffectsOnOff (void)
void EffectsOff (void)
void EffectsOn (int surface)
void SetSoundVolume (int value)
void SoundQuant (void)
void StartCDTRACK (void)
void PauseCDTRACK (void)
void ResumeCDTRACK (void)
void StopCDTRACK (void)
void SlowCDTRACK (void)
void StartWTRACK (void)
void MainMenuSoundQuant (int TRACK)
void LastStartWTRACK (int TRACK)
void LastSoundQuant (void)
Variables
int MuteLog
int ViewZ
int frame
int CurrentWorld
const int LOCAL_CHANNEL = 9
const int LOCAL_SOUND = 1
const int ESCAVE_SOUND = 2
int SoundFlag = 0
int lastSoundFlag = 0
int SoundVolumeCD = -1
int SoundVolumePanning = 1
int MusicON = 1
int EffectInUse
int EffectInUsePriory
int EffectInFrequence = 1
int NumBackgroundsEff
int sndBackgroundMax
int sndStepMax
int sndScratchMax
int EngineNoise = 1
int BackgroundSound = 1
int activeWTRACK = 0
Macro Definition Documentation
DB_MAX
#define DB_MAX 0
DB_MIN
#define DB_MIN -10000
DB_SIZE
#define DB_SIZE 10000
DELTA_KHZ
#define DELTA_KHZ 2000
DISTANCE_TO_SICRET
#define DISTANCE_TO_SICRET 512
DISTANCE_TO_TOWN
#define DISTANCE_TO_TOWN 2000
EFFECT_KHZ
#define EFFECT_KHZ 44100
SPEECH_KHZ
#define SPEECH_KHZ 22050
Function Documentation
EffectsOff()
void EffectsOff (void)
 {
     if(EffectInUsePriory && EffectInUse){
         for(int i = 0;i < 16;i++) SoundStop(i);
         EffectInUse = 0;
         lastSoundFlag = 0;
         //SoundVolumeCD = -1;
     }
 }
References EffectInUse, EffectInUsePriory, lastSoundFlag, and SoundStop().
Referenced by LoadingRTO3::Finit(), iHandleExtEvent(), LoadResourceSOUND(), LocalEffectFree(), uvsVanger::makeJump(), uvsVanger::prepare_shop(), GameQuantRTO::Quant(), uvsVanger::Quant(), SoundEscaveOff(), and theEND().
EffectsOn()
void EffectsOn (int surface)
 {
     if(EffectInUsePriory && !EffectInUse) EffectInUse = 1;
 }
References EffectInUse, and EffectInUsePriory.
Referenced by iHandleExtEvent(), and GameQuantRTO::Quant().
EffectsOnOff()
void EffectsOnOff (void)
 {
     if(EffectInUsePriory){
         EffectInUse = 1 - EffectInUse;
         if(!EffectInUse) {
             for(int i = 0;i < 16;i++) SoundStop(i);
             lastSoundFlag = 0;
         }
     }
 }
References EffectInUse, EffectInUsePriory, lastSoundFlag, and SoundStop().
GetEscaveDist()
int GetEscaveDist (void)
 {
     uvsEscave* p1;
     uvsSpot* p2;
     uvsPassage *p3;
     int md,d;
     Vector vCheck;
     md = -1;
     p1 = (uvsEscave*)EscaveTail;
     while(p1){
         if (((uvsEscave*)p1) -> Pworld -> gIndex == CurrentWorld ){
             vCheck = Vector(getDistX(p1->pos_x,Gamer->pos_x),getDistY(p1->pos_y,Gamer->pos_y),0);
             d = vCheck.vabs();
             if(d < md || md == -1) md = d;
         }
         p1 = (uvsEscave*)(p1 -> next);
     };
     p2 = (uvsSpot*)SpotTail;
     while(p2){
         if (((uvsSpot*)p2) -> Pworld -> gIndex == CurrentWorld ){
             vCheck = Vector(getDistX(p2->pos_x,Gamer->pos_x),getDistY(p2->pos_y,Gamer->pos_y),0);
             d = vCheck.vabs();
             if(d < md || md == -1) md = d;
         }
         p2 = (uvsSpot*)(p2 -> next);
     };
     if ( md == -1 ){
         p3 = (uvsPassage*)PassageTail;
         while(p3){
             if (((uvsPassage*)p3) -> Pworld -> gIndex == CurrentWorld ){
                 vCheck = Vector(getDistX(p3->pos_x,Gamer->pos_x),getDistY(p3->pos_y,Gamer->pos_y),0);
                 d = vCheck.vabs();
                 if(d < md || md == -1) md = d;
             }
             p3 = (uvsPassage*)(p3 -> next);
         };
     }
     return md;
 };
References CurrentWorld, EscaveTail, Gamer, getDistX(), getDistY(), uvsTarget::pos_x, uvsTarget::pos_y, and Vector::vabs().
getWID()
int getWID (void)
 {
     return aScrDisp -> wMap -> world_ptr[aScrDisp -> curLocData -> WorldID] -> uvsID;
 }
References aScrDisp, and wMap.
Referenced by StartWTRACK().
InstallSOUND()
void InstallSOUND (void)
 {
     if (lang() == RUSSIAN) {
         TrackCDTime = new int[11] { 0, 1, 174, 108, 128, 238, 130, 181, 120, 151, 200 };
     } else {
         TrackCDTime = new int[11] { 0, 1, 174, 108, 128, 238, 130, 181, 120, 151, 60 };
     }
     if(!SoundInit(EFFECT_KHZ, 16)){
         std::cout<<"\nInitialization of sound failed, mute mode accepted...\n";
         MuteLog = 1;
         return;
         }
     EffectInUsePriory = EffectInUse = 1;
 //  xsInitCD();
     xsInitMusic();
 }
References lang(), and RUSSIAN.
Referenced by xtInitApplication().
LastSoundQuant()
void LastSoundQuant (void)
{
     if(!MusicON) return;
     time_t l_time;
     time(&l_time);
     if (l_time - lastTimeCD > TimeCD){
 //      int status = xsGetStatusCD();
         int status = xsGetStatusMusic();
         if (status & XCD_PAUSED){
             if (LastTrack == ST_DOUBLE){
 //              xsPlayCD(ST_THEEND);
                 xsPlayMusic(ST_THEEND);
                 TimeCD = TrackCDTime[ST_THEEND] + TrackCDTime[ST_THEEND_DOUBLE];
             }else{
                 if (LastTrack == ST_THEEND_DOUBLE)
 //                  xsPlayCD(LastTrack);
                     xsPlayMusic(LastTrack);
                 else
 //                  xsPlayOneTrackCD(LastTrack);
                     xsPlayOneTrackMusic(LastTrack);
                 TimeCD = TrackCDTime[LastTrack];
             }
             time(&lastTimeCD);
         }
     }
 }
References MusicON.
Referenced by ShowImageRTO::Quant().
LastStartWTRACK()
void LastStartWTRACK (int TRACK)
 {
     if(!MusicON) return;
     LastTrack = TRACK;
     if (TRACK == ST_DOUBLE){
 //      xsPlayCD(ST_THEEND);
         xsPlayMusic(ST_THEEND);
         TimeCD = TrackCDTime[ST_THEEND] + TrackCDTime[ST_THEEND_DOUBLE];
     }else{
         if (TRACK == ST_THEEND_DOUBLE)
 //          xsPlayCD(TRACK);
             xsPlayMusic(TRACK);
         else
 //          xsPlayOneTrackCD(TRACK);
             xsPlayOneTrackMusic(TRACK);
         TimeCD = TrackCDTime[TRACK];
     }
     time(&lastTimeCD);
     activeWTRACK = 1;
 }
References MusicON.
Referenced by ShowImageRTO::Init().
LoadMotorSound()
void LoadMotorSound (void)
{
     XBuffer buf;
     XStream ff(0);
     for(int i = 0;i < 3;i++){
         buf.init();
         if(EngineNoise)
             buf < "resource/sound/effects/" < "/" < SndData[i].fname < ".wav";
         if(ff.open(buf.GetBuf(),XS_IN)){
             ff.close();
             if (SndData[i].lpDSB){
                 SoundStop(SndData[i].channel);
                 SoundRelease(SndData[i].lpDSB);
                 SndData[i].lpDSB = NULL;
             }
             SoundLoad(buf.GetBuf(),&SndData[i].lpDSB);
         }
     }   //  end for i
 }
References EngineNoise, and XBuffer::init().
LoadResourceSOUND()
void LoadResourceSOUND (const char * path_name, int surface)
 {
     int i;
     //if(MuteLog) return;
     EffectsOff();
     XBuffer buf;
     XStream ff(0);
     for(i = 0;i < EFF_MAX;i++) {
         if ((SndData[i].status & LOCAL_SOUND) && SndData[i].lpDSB && surface) {
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
         buf.init();
         if((i == EFF_DRIVING) || (i == EFF_START) || (i == EFF_STOP)) {
             if(EngineNoise) {
                 buf < "resource/sound/effects" < "/" < SndData[i].fname < ".wav";
             } else {
                 continue;
             }
         } else {
             buf < path_name < "/" < SndData[i].fname < ".wav";
         }
         if(ff.open(buf.GetBuf(),XS_IN)){
             ff.close();
             if (SndData[i].lpDSB){
                 SoundRelease(SndData[i].lpDSB);
                 SndData[i].lpDSB = NULL;
                 }
             SoundLoad(buf.GetBuf(),&SndData[i].lpDSB);
         }
         //std::cout<<"file:"<<buf.GetBuf()<<" addr:"<<SndData[i].lpDSB<<std::endl;
     }
     EffectsOn(surface);
     sndBackgroundMax = sndStepMax = sndScratchMax = 0;
     for(i = EFF_BACKGROUND_0;i <= EFF_BACKGROUND_5;i++)
         if(SndData[i].lpDSB) sndBackgroundMax++;
     for(i = EFF_STEP0;i <= EFF_STEP2;i++)
         if(SndData[i].lpDSB) sndStepMax++;
     for(i = EFF_SCRATCH0;i <= EFF_SCRATCH1;i++)
         if(SndData[i].lpDSB) sndScratchMax++;
 }
References EFF_MAX, and EffectsOff().
Referenced by ChangeWorld(), actIntDispatcher::i_init(), LoadingRTO2::Init(), and xtInitApplication().
LocalEffectFree()
void LocalEffectFree (void)
{
     EffectsOff();
     for(int i = 0;i < EFF_MAX;i++){
         if ((SndData[i].status & LOCAL_SOUND) && SndData[i].lpDSB){
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
     }
     EffectsOn(1);
 }
References EFF_MAX, and EffectsOff().
Referenced by LoadingRTO3::Init().
MainMenuSoundQuant()
void MainMenuSoundQuant (int TRACK)
{
 #ifndef _DEMO_
     if(!MusicON) return;
 //  int track = xsGetCurTrackCD();
 //  int status = xsGetStatusCD();
     int status = xsGetStatusMusic();
     if (SoundVolumeCD == -1)
 //          SoundVolumeCD = xsGetVolumeCD();
             SoundVolumeCD = xsGetVolumeMusic();
 //  if ( TRACK != track || !activeWTRACK )
     time_t l_time;
     time(&l_time);
     if (l_time - lastTimeCD > TimeCD){
 //      int status = xsGetStatusCD();
         int status = xsGetStatusMusic();
         if (status & XCD_PAUSED){
 //          xsPlayOneTrackCD(TRACK);
             xsPlayOneTrackMusic(TRACK);
             TimeCD = TrackCDTime[TRACK];
             time(&lastTimeCD);
         }
     } else  if ( !activeWTRACK ){
 //      xsPlayOneTrackCD(TRACK);
         xsPlayOneTrackMusic(TRACK);
         TimeCD = TrackCDTime[TRACK];
         time(&lastTimeCD);
     }
     activeWTRACK = 1;
 #endif
 }
References MusicON, SoundVolumeCD, xsGetStatusMusic(), and xsGetVolumeMusic().
Referenced by MainMenuRTO::Quant().
PauseCDTRACK()
void PauseCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsPauseCD();
     xsPauseMusic();
 #endif
 }
References MusicON, and xsPauseMusic().
RestoreSOUND()
void RestoreSOUND (void)
 {
     delete[] TrackCDTime;
 #ifndef _NO_CDAUDIO_
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsStopCD();
     xsStopMusic();
     xsDeInitMusic();
 #endif
 #endif
 }
Referenced by restore().
ResumeCDTRACK()
void ResumeCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsResumeCD();
     xsResumeMusic();
 #endif
 }
References MusicON, and xsResumeMusic().
SetMotorFile()
void SetMotorFile (int type)
{
     SndData[EFF_DRIVING].fname = SndMotorFileName[type*2];
 //  SndData[EFF_START].fname = SndMotorFileName[type*3+1];
     SndData[EFF_STOP].fname = SndMotorFileName[type*2+1];
     LoadMotorSound();
 }
SetMotorSound()
void SetMotorSound (int speed)
{
     if ((speed > 0) && (speed < 11)){
         if(SndData[EffectInFrequence].lpDSB)
             SetSoundFrequency(SndData[EffectInFrequence].lpDSB, EFFECT_KHZ + DELTA_KHZ*speed);
         if(SndData[EffectInFrequence + 1].lpDSB)
             SetSoundFrequency(SndData[EffectInFrequence + 1].lpDSB, EFFECT_KHZ + DELTA_KHZ*speed);
         }
 }
SetSoundVolume()
void SetSoundVolume (int value)
 {
     //std::cout<<"SetSoundVolume:"<<value<<std::endl;
     if(EffectInUsePriory){
 //      xsSetVolumeWAVE(value);
         soundVolumecurrent = soundVolume = value;
         //soundVolumecurrent = soundVolume = DB_MIN + round(log10(9.0*log(double(value))/(log(2.0)*8) + 1.0)*DB_SIZE);
     }
 }
References EffectInUsePriory.
Referenced by iHandleExtEvent(), LoadingRTO1::Init(), and xtInitApplication().
SlowCDTRACK()
void SlowCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
     if (SlowOn){
 //      LocalVolume = xsGetVolumeCD();
         LocalVolume = xsGetVolumeMusic();
         DeltaVolume = (LocalVolume/40) + 1;
     }
     SlowOn = 0;
 //  LocalVolume = xsGetVolumeCD() - DeltaVolume;
     LocalVolume = xsGetVolumeMusic() - DeltaVolume;
     if (LocalVolume > 0 )
 //      xsSetVolumeCD(LocalVolume);
         xsSetVolumeMusic(LocalVolume);
     else{
 //      xsStopCD();
         xsStopMusic();
         activeWTRACK = 0;
         SlowOn = 1;
     }
 #endif
 }
References MusicON.
Referenced by aciShowLocation().
SoundEscaveOff()
void SoundEscaveOff (void)
{
     EffectsOff();
     for(int i = 0;i < EFF_MAX;i++){
         if ((SndData[i].status & ESCAVE_SOUND) && SndData[i].lpDSB){
             SoundRelease(SndData[i].lpDSB);
             SndData[i].lpDSB = NULL;
         }
     }
     EffectsOn(0);
 }
References EFF_MAX, and EffectsOff().
Referenced by actIntDispatcher::i_finit().
SoundQuant()
void SoundQuant (void)
 {
     if(!EffectInUse) return;
     if(MusicON){
         int _world_ = CurrentWorld;
         int Distance = DISTANCE_TO_TOWN;
         if (_world_ > 3) {
             _world_ = 4;
             Distance = DISTANCE_TO_SICRET;
         }
 //      int len = GetEscaveDist();
         if (SoundVolumeCD == -1)
 //          SoundVolumeCD = xsGetVolumeCD();
             SoundVolumeCD = xsGetVolumeMusic();
 /*      if ( len == -1 )
             xsSetVolumeCD(0);
         else*/ {
             time_t l_time;
             time(&l_time);
             if (l_time - lastTimeCD > TimeCD){
 //              int status = xsGetStatusCD();
                 int status = xsGetStatusMusic();
                 if (status & XCD_PAUSED)
                     StartWTRACK();
             }
 //          if(len > Distance) len = 0; else len = Distance - abs(len);
         }
 //      xsSetVolumeCD(len*SoundVolumeCD/Distance);
     }
     int DiffSound = SoundFlag ^ lastSoundFlag;
     if (DiffSound){
         if (DiffSound & SoundCopterig) {
             if (SoundFlag & SoundCopterig) {
                 SOUND_COPTERIG_START()
             } else {
                 SOUND_COPTERIG_STOP()
             }
         }
         if (DiffSound & SoundCrotrig) {
             if (SoundFlag & SoundCrotrig) {
                 SOUND_CROTRIG_START()
             } else {
                 SOUND_CROTRIG_STOP()
             }
         }
         if (DiffSound & SoundCutterig) {
             if (SoundFlag & SoundCutterig) {
                 SOUND_CUTTERIG_START()
             } else {
                 SOUND_CUTTERIG_STOP()
             }
         }
         if (DiffSound & SoundUnderWater) {
             if (SoundFlag & SoundUnderWater) {
                 SOUND_UNDERWATER_START()
             } else {
                 SOUND_UNDERWATER_STOP()
             }
         }
         if (DiffSound & SoundMotor) {
             if (SoundFlag & SoundMotor) {
                 SOUND_START_MOTOR()
             } else {
                 SOUND_STOP_MOTOR()
             }
         }
     }
     lastSoundFlag = SoundFlag;
     /*      ?    .
     int d = ViewZ - preViewZ;
     if(!d) {
         return;
     }
     std::cout<<"AAAAAAAAAAAAA"<<std::cout;
     if(ViewZ >= 512) {
         d = soundVolume - DB_SIZE/32 - (ViewZ - 512)*DB_SIZE/4/(1024 - 512);
     } else {
         d = soundVolume - DB_SIZE/32 + (512 - ViewZ)*DB_SIZE/4/(512 - 384);
     }
     preViewZ = ViewZ;
     soundVolumecurrent = d;
     if(soundVolumecurrent < DB_MIN) {
         soundVolumecurrent = DB_MIN;
     } else {
         if(soundVolumecurrent > DB_MAX) {
             soundVolumecurrent = DB_MAX;
         }
     }*/
     for(int i = 0;i < 16;i++) {
         if(i != LOCAL_CHANNEL) {
             SoundVolume(i,soundVolumecurrent);
         }
     }
 }
References CurrentWorld, DISTANCE_TO_SICRET, DISTANCE_TO_TOWN, EffectInUse, MusicON, SoundVolumeCD, and xsGetVolumeMusic().
Referenced by iGameMap::draw().
StartCDTRACK()
void StartCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  xsPlayOneTrackCD(LastTrack);
     xsPlayOneTrackMusic(LastTrack);
 #endif
 }
References MusicON, and xsPlayOneTrackMusic().
Referenced by iHandleExtEvent().
StartEFFECT()
void StartEFFECT (EFFECT_VALUE EffectValue, int loop, int pan)
 {
     if(!EffectInUse || !SndData[EffectValue].lpDSB) return;
     int flag = SndData[EffectValue].flags;
     if(loop) flag |= DS_LOOPING;
     if(SndData[EffectValue].channel != LOCAL_CHANNEL)
         SetVolume(SndData[EffectValue].lpDSB,soundVolumecurrent);
     else
         SetVolume(SndData[EffectValue].lpDSB,soundVolume);
     if(EngineNoise && EffectValue == EFF_DRIVING) SoundStop(SndData[EffectValue].channel);
     if (SoundVolumePanning)
         SoundPan(SndData[EffectValue].channel, -pan*8);
     //if (SndData[EffectValue].status & ESCAVE_SOUND&&EffectValue!=EFF_NOISE)
     //  std::cout<<"StartEFFECT:"<<SndData[EffectValue].fname<<" int:"<<(int)EffectValue<<std::endl;
     SoundPlay(SndData[EffectValue].lpDSB,SndData[EffectValue].channel,SndData[EffectValue].priority,SndData[EffectValue].cropos,flag);
 }
References EffectInUse.
Referenced by pal_iter0().
StartSPEECH()
void StartSPEECH (SPEECH_VALUE SpeechValue)
 {
 }
StartWTRACK()
void StartWTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
     int w_id = CurrentWorld;
     if (CurrentWorld == -1)
         w_id = getWID();
     if(w_id >= 0 && w_id <= 3){
 //      xsPlayOneTrackCD(ST_FOSTRAL + w_id);
         xsPlayOneTrackMusic(ST_FOSTRAL + w_id);
         TimeCD = TrackCDTime[ST_FOSTRAL + w_id];
     } else {
         if(w_id > 3){
 //          xsPlayOneTrackCD(ST_SECRETS);
             xsPlayOneTrackMusic(ST_SECRETS);
             TimeCD = TrackCDTime[ST_SECRETS];
         }
     }
     time(&lastTimeCD);
     activeWTRACK = 1;
 #endif
 }
References CurrentWorld, getWID(), MusicON, ST_FOSTRAL, and xsPlayOneTrackMusic().
Referenced by uvsRestoreVanger(), and uvsWorldReload().
StopCDTRACK()
void StopCDTRACK (void)
 {
 #ifndef _DEMO_
     if(!MusicON) return;
 //  LastTrack = xsGetCurTrackCD();
 //  xsStopCD();
     xsStopMusic();
     activeWTRACK = 0;
     SlowOn = 1;
 #endif
 }
References activeWTRACK, MusicON, and xsStopMusic().
Referenced by aciPrepareEndImage(), aciShowLocation(), iHandleExtEvent(), LoadingRTO3::Init(), VangerUnit::Quant(), VangerUnit::SensorQuant(), and XpeditionOFF().
StopEFFECT()
void StopEFFECT (EFFECT_VALUE EffectValue)
 {
     if(!EffectInUse) return;
     SoundStop(SndData[EffectValue].channel);
     if(EngineNoise && EffectValue == EFF_DRIVING && SndData[EFF_STOP].lpDSB) StartEFFECT(EFF_STOP);
 }
References EffectInUse, and SoundStop().
Variable Documentation
activeWTRACK
int activeWTRACK = 0
Referenced by StopCDTRACK().
BackgroundSound
int BackgroundSound = 1
Referenced by MainMenuRTO::Finit(), and pal_iter0().
CurrentWorld
int CurrentWorld extern
Referenced by SoundQuant(), and StartWTRACK().
EffectInFrequence
int EffectInFrequence = 1
EffectInUse
int EffectInUse
Referenced by EffectsOff(), EffectsOn(), EffectsOnOff(), SoundQuant(), StartEFFECT(), and StopEFFECT().
EffectInUsePriory
int EffectInUsePriory
Referenced by EffectsOff(), EffectsOn(), EffectsOnOff(), iHandleExtEvent(), LoadingRTO1::Init(), and SetSoundVolume().
EngineNoise
int EngineNoise = 1
Referenced by MainMenuRTO::Finit(), and LoadMotorSound().
ESCAVE_SOUND
const int ESCAVE_SOUND = 2
frame
int frame extern
lastSoundFlag
int lastSoundFlag = 0
Referenced by EffectsOff(), and EffectsOnOff().
LOCAL_CHANNEL
const int LOCAL_CHANNEL = 9
LOCAL_SOUND
const int LOCAL_SOUND = 1
MusicON
int MusicON = 1
Referenced by iHandleExtEvent(), LastSoundQuant(), LastStartWTRACK(), MainMenuSoundQuant(), PauseCDTRACK(), ResumeCDTRACK(), SlowCDTRACK(), SoundQuant(), StartCDTRACK(), StartWTRACK(), and StopCDTRACK().
MuteLog
int MuteLog extern
Referenced by ComlineAnalyze(), iGameMap::draw(), and LoadingRTO1::Init().
NumBackgroundsEff
int NumBackgroundsEff
sndBackgroundMax
int sndBackgroundMax
sndScratchMax
int sndScratchMax
sndStepMax
int sndStepMax
SoundFlag
int SoundFlag = 0
Referenced by Object::analysis(), Object::mechous_analysis(), VangerFunctionType::Quant(), and Object::switch_analysis().
SoundVolumeCD
int SoundVolumeCD = -1
Referenced by iHandleExtEvent(), MainMenuSoundQuant(), and SoundQuant().
SoundVolumePanning
int SoundVolumePanning = 1
Referenced by MainMenuRTO::Finit().
ViewZ
int ViewZ extern
Referenced by calc_screen(), calc_view_factors(), iGameMap::draw(), G2LF(), G2LQ(), G2LS(), ActionUnit::InitEnvironment(), ParticleObject::Quant(), WaterParticleObject::Quant(), TargetParticleObject::Quant(), iGameMap::reset(), VangerUnit::SendCameraData(), and GameObjectDispatcher::Sort().