Vangers: aciScreenEvent Struct Reference
aciScreenEvent Struct Reference
#include <aci_scr.h>
Public Member Functions
void AddCommand (aciScreenEventCommand *p)
void AddKey (int code)
int KeyTrap (int code)
void Start (void)
void Stop (void)
void Quant (void)
aciScreenEvent (void)
~aciScreenEvent (void)
Public Member Functions inherited from XListElement
XListElement (void)
Public Attributes
int flags
int CurTimer
int MaxTimer
XList * commSeq
aciScreenKeyObject * keyObj
Public Attributes inherited from XListElement
XListElement * next
XListElement * prev
Detailed Description
Constructor & Destructor Documentation
aciScreenEvent()
aciScreenEvent::aciScreenEvent (void)
 {
     flags = 0;
     CurTimer = 0;
     MaxTimer = 1;
     commSeq = new XList;
     keyObj = new aciScreenKeyObject;
 }
References commSeq, CurTimer, flags, keyObj, and MaxTimer.
~aciScreenEvent()
aciScreenEvent::~aciScreenEvent (void)
 {
     aciScreenEventCommand* p,*p1;
     aci_FREE_LIST(commSeq,p,p1,aciScreenEventCommand);
     delete commSeq;
     delete keyObj;
 }
References aci_FREE_LIST, commSeq, and keyObj.
Member Function Documentation
AddCommand()
void aciScreenEvent::AddCommand (aciScreenEventCommand * p)
 {
     commSeq -> AddElement((XListElement*)p);
 }
References commSeq.
AddKey()
void aciScreenEvent::AddKey (int code) inline
 { keyObj -> AddKey(code); }
References AddKey(), and keyObj.
Referenced by AddKey().
KeyTrap()
int aciScreenEvent::KeyTrap (int code) inline
 { return keyObj -> KeyTrap(code); }
References keyObj, and KeyTrap().
Referenced by KeyTrap().
Quant()
void aciScreenEvent::Quant (void)
 {
     aciScreenEventCommand* p = (aciScreenEventCommand*)commSeq -> fPtr;
     int nextQuant = 1;
     while(p){
         if(p -> StartTimer == CurTimer){
             if(p -> flags & ACS_COMMAND_STARTED){
                 if(!acsEventActive(p))
                     nextQuant = 0;
             }
             else {
                 p -> flags |= ACS_COMMAND_STARTED;
                 acsSendEvent(p);
                 nextQuant = 0;
             }
         }
         p = (aciScreenEventCommand*)p -> next;
     }
     if(nextQuant){
         CurTimer ++;
         if(CurTimer > MaxTimer) Stop();
     }
 }
References ACS_COMMAND_STARTED, acsEventActive(), acsSendEvent(), commSeq, CurTimer, flags, MaxTimer, XListElement::next, and Stop().
Start()
void aciScreenEvent::Start (void)
 {
     Stop();
     CurTimer = 0;
     flags |= ACS_EVENT_ACTIVE;
 }
References ACS_EVENT_ACTIVE, CurTimer, flags, and Stop().
Stop()
void aciScreenEvent::Stop (void)
 {
     flags &= ~ACS_EVENT_ACTIVE;
     aciScreenEventCommand* p = (aciScreenEventCommand*)commSeq -> fPtr;
     while(p){
         p -> flags &= ~ACS_COMMAND_STARTED;
         p = (aciScreenEventCommand*)p -> next;
     }
 }
References ACS_COMMAND_STARTED, ACS_EVENT_ACTIVE, commSeq, flags, and XListElement::next.
Referenced by Quant(), and Start().
Member Data Documentation
commSeq
XList* aciScreenEvent::commSeq
Referenced by aciScreenEvent(), AddCommand(), Quant(), Stop(), and ~aciScreenEvent().
CurTimer
int aciScreenEvent::CurTimer
Referenced by aciScreenEvent(), Quant(), and Start().
flags
int aciScreenEvent::flags
Referenced by aciScreenEvent(), Quant(), Start(), and Stop().
keyObj
aciScreenKeyObject* aciScreenEvent::keyObj
Referenced by aciScreenEvent(), AddKey(), KeyTrap(), and ~aciScreenEvent().
MaxTimer
int aciScreenEvent::MaxTimer
Referenced by aciScreenEvent(), and Quant().
The documentation for this struct was generated from the following files:
src/actint/aci_scr.h
src/actint/aci_scr.cpp