Vangers: JumpBallList Struct Reference
JumpBallList Struct Reference
#include <items.h>
Public Member Functions
JumpBallObject * CreateBall (void)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Init (void)
virtual void Free (void)
virtual void Quant (void)
virtual void NetEvent (int type, int id)
virtual void FreeUnit (GeneralObject *p)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Additional Inherited Members
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
CreateBall()
JumpBallObject * JumpBallList::CreateBall (void)
 {
     JumpBallObject* p;
     p = new JumpBallObject;
     p->Init();
     ConnectTypeList(p);
     return p;
 };
References UnitBaseListType::ConnectTypeList(), and JumpBallObject::Init().
Referenced by GunSlot::Quant().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp