Vangers: Player Struct Reference
Player Struct Reference
#include <server.h>
Public Member Functions
Player (Server *server, XSocket &sock)
~Player ()
void identification ()
int is_alive ()
int receive ()
int send ()
void put_object (Object *object)
void clear_object_queue (int keep_globals)
Public Attributes
int ID
int identificated
int client_version
int client_mask
int status
char * name
char * password
Server * server
Game * game
World * world
int x
int y
int y_half_size_of_screen
int x_prev
int y_prev
int y_half_size_of_screen_prev
PlayerBody body
float prev_rating
XTList< Object > inventory
unsigned int birth_time
unsigned int last_sent_position
unsigned int last_IO_operation
unsigned int time_to_remove
int total_sent
int total_received
XSocket socket
InputEventBuffer in_buffer
OutputEventBuffer out_buffer
XQueue< Object * > object_queue
XQueue< Event > code_queue
Player * next
Player * prev
XTList< Player > * list
Player * next_alt
Player * prev_alt
XTListAlt< Player > * list_alt
Detailed Description
Constructor & Destructor Documentation
Player()
Player::Player (Server * server, XSocket & sock)
     : in_buffer(IN_BUFFER_SIZE), out_buffer(OUT_BUFFER_SIZE), object_queue(OUT_QUEUE_SIZE),
       code_queue(OUT_QUEUE_SIZE) {
     server = serv;
     socket = sock;
     identificated = 0;
     client_version = 0;
     status = 0;
     game = 0;
     ID = 0;
     client_mask = 0;
     password = name = 0;
     prev_rating = 0;
     world = 0;
     x = y = y_half_size_of_screen = 0;
     x_prev = y_prev = y_half_size_of_screen_prev = 0;
     last_IO_operation = SDL_GetTicks() + 20 * 1000;
     last_sent_position = SDL_GetTicks();
     birth_time = SDL_GetTicks();
     //  current_sent_object = 0;
     time_to_remove = 0;
     next = prev = 0;
     list = 0;
     next_alt = prev_alt = 0;
     list_alt = 0;
 }
References birth_time, client_mask, client_version, game, ID, identificated, last_IO_operation, last_sent_position, list, list_alt, name, next, next_alt, password, prev, prev_alt, prev_rating, server, socket, status, time_to_remove, world, x, x_prev, y, y_half_size_of_screen, y_half_size_of_screen_prev, and y_prev.
~Player()
Player::~Player ()
                 {
     if (name)
         delete name;
     if (password)
         delete password;
 }
References name, and password.
Member Function Documentation
clear_object_queue()
void Player::clear_object_queue (int keep_globals)
{
     int number = object_queue.tell();
     for (; number > 0; number--) {
         Object *obj = object_queue.get();
         if (!obj)
             continue;
         if (keep_globals && !NON_GLOBAL_OBJECT(obj->ID)) {
             object_queue.put(obj);
             continue;
         }
         obj->in_queue &= ~client_mask;
         if (obj->send_delete & client_mask && (obj->send_delete &= ~client_mask) == 0) {
             if (NON_GLOBAL_OBJECT(obj->ID))
                 world->delete_object(obj);
             else
                 // if(obj -> ID != DIRECT_SENDING_OBJECT)
                 if (obj->list)
                 obj->list->remove(obj);
             delete obj;
         }
     }
 }
References client_mask, World::delete_object(), XQueue< Type >::get(), Object::ID, Object::in_queue, Object::list, NON_GLOBAL_OBJECT, object_queue, XQueue< Type >::put(), XTList< Type >::remove(), Object::send_delete, XQueue< Type >::tell(), and world.
Referenced by World::detach_player(), and Game::detach_player().
identification()
void Player::identification ()
{
     char string[256];
     memset(string, 0, 256);
     char *request_str = "Vivat Sicher, Rock'n'Roll forever!!!";
     char *response_str = "Enter, my son, please...";
     char *kill_str = "I'm sorry, darling...";
     unsigned int len;
     if ((len = socket.receive(string, 255)) != 0) {
         if (!strcmp(string, request_str)) {
             identificated = 1;
             if (len > strlen(request_str) + 1)
                 client_version = ((unsigned char *)string)[len - 1];
             strcpy(string, response_str);
             string[strlen(string) + 1] = SERVER_VERSION;
             socket.send(string, strlen(string) + 2);
             return;
         }
         if (!strcmp(string, kill_str))
             GlobalExit = 1;
     }
 }
References client_version, GlobalExit, identificated, XSocket::receive(), XSocket::send(), SERVER_VERSION, and socket.
Referenced by Server::clients_quant().
is_alive()
int Player::is_alive ()
                      {
     if (socket()) {
         if ((int)(SDL_GetTicks() - last_IO_operation) > 3000) {
             short size = 0;
             socket.send((const char *)&size, 2);
             last_IO_operation = SDL_GetTicks();
         }
         return 1;
     }
     if (!game)
         return 0;
     if (!time_to_remove) {
         time_to_remove = SDL_GetTicks() + WAITING_TO_REMOVE;
         MOUT1("Connection have been lost", ID);
         return 1;
     }
     return (int)(SDL_GetTicks() - time_to_remove) < 0 ? 1 : 0;
 }
References game, ID, last_IO_operation, MOUT1, XSocket::send(), socket, time_to_remove, and WAITING_TO_REMOVE.
Referenced by Server::clients_quant(), and Game::quant().
put_object()
void Player::put_object (Object * object)
{
     if (!(object->in_queue & client_mask)) {
         object->in_queue |= client_mask;
         object_queue.put(object);
     }
 }
References client_mask, Object::in_queue, object_queue, and XQueue< Type >::put().
Referenced by Game::check_global_objects(), World::process_create(), Game::process_create_globals(), World::process_create_inventory(), World::process_delete(), Game::process_delete_globals(), Game::process_direct_sending(), World::process_set_position(), World::process_update(), Game::process_update_globals(), World::process_update_inventory(), and receive().
receive()
int Player::receive ()
                     {
     if (!socket)
         return 0;
     int recv_size = in_buffer.receive(socket);
     if (recv_size) {
         last_IO_operation = SDL_GetTicks();
         //      IN_EVENTS_LOG1(Receive_Block,recv_size);
     }
     int code;
     while ((code = in_buffer.current_event()) != 0) {
         if (!(code & AUXILIARY_EVENT))
             code &= ~ECHO_EVENT;
         switch (code) {
         case CREATE_PERMANENT_OBJECT: {
             int obj_ID = in_buffer.get_dword();
             Object *obj = 0;
             if (NON_GLOBAL_OBJECT(obj_ID)) {
                 if (!world) {
                     SERVER_ERROR("Create permanent object before set world", 0);
                     in_buffer.ignore_event();
                     break;
                 }
                 obj = world->search_object(obj_ID);
             } else
                 obj = game->global_objects.search(obj_ID);
             if (obj) {
                 if (obj->send_delete) {
                     if (NON_GLOBAL_OBJECT(obj->ID))
                         world->delete_object(obj);
                     else
                         obj->list->remove(obj);
                     obj->ID = 0;
                 } else {
                     obj->last_update |= client_mask;
                     put_object(obj);
                     DOUT1("Duplicated create", obj_ID);
                     in_buffer.ignore_event();
                     break;
                 }
             }
             obj = new Object();
             obj->ID = obj_ID;
             obj->client_ID = ID;
             obj->time = in_buffer.get_dword();
             obj->x = in_buffer.get_short();
             obj->y = in_buffer.get_short();
             obj->radius = in_buffer.get_short();
             if (GET_OBJECT_TYPE(obj_ID) == NID_VANGER) {
                 x = obj->x;
                 y = obj->y;
                 y_half_size_of_screen = in_buffer.get_byte() << 1;
                 obj->body_size = in_buffer.event_size() - 16;
                 obj->body = new unsigned char[obj->body_size];
                 in_buffer.read(obj->body, obj->body_size);
                 world->process_create(!(in_buffer.current_event() & ECHO_EVENT) ? this : 0, obj);
                 world->process_set_position(this);
             } else {
                 obj->body_size = in_buffer.event_size() - 15;
                 obj->body = new unsigned char[obj->body_size];
                 in_buffer.read(obj->body, obj->body_size);
                 if (!PLAYERS_OBJECT(obj_ID))
                     world->process_create(
                         !(in_buffer.current_event() & ECHO_EVENT) ? this : 0, obj);
                 else {
                     if (NON_GLOBAL_OBJECT(obj_ID))
                         world->process_create_inventory(this, obj);
                     else
                         game->process_create_globals(
                             !(in_buffer.current_event() & ECHO_EVENT) ? this : 0, obj);
                 }
             }
             IN_EVENTS_LOG1(CREATE_PERMANENT_OBJECT, obj->ID);
         } break;
         case DELETE_OBJECT: {
             int obj_ID = in_buffer.get_dword();
             Object *obj = 0;
             if (NON_GLOBAL_OBJECT(obj_ID)) {
                 if (!world) {
                     SERVER_ERROR("Delete object before set world", 0);
                     in_buffer.ignore_event();
                     break;
                 }
                 obj = world->search_object(obj_ID);
             } else
                 obj = game->global_objects.search(obj_ID);
             if (!obj || obj->send_delete) {
                 IN_EVENTS_LOG1(SKIP_DELETE_OBJECT, obj_ID);
                 in_buffer.ignore_event();
                 break;
             }
             obj->client_ID = ID;
             obj->time = in_buffer.get_dword();
             obj->death_body_size = in_buffer.event_size() - 9;
             if (obj->death_body_size > obj->body_size) {
                 if (obj->body)
                     delete obj->body;
                 obj->body = new unsigned char[obj->death_body_size];
             }
             in_buffer.read(obj->body, obj->death_body_size);
             if (NON_GLOBAL_OBJECT(obj_ID))
                 world->process_delete(obj);
             else
                 game->process_delete_globals(obj);
             IN_EVENTS_LOG1(DELETE_OBJECT, obj->ID);
         } break;
         case UPDATE_OBJECT: {
             int obj_ID = in_buffer.get_dword();
             Object *obj = 0;
             if (NON_GLOBAL_OBJECT(obj_ID)) {
                 if (!world) {
                     SERVER_ERROR("Update object before set world", 0);
                     in_buffer.ignore_event();
                     break;
                 }
                 obj = world->search_object(obj_ID);
             } else
                 obj = game->global_objects.search(obj_ID);
             if (!obj || obj->send_delete) {
                 IN_EVENTS_LOG1(SKIP_UPDATE_OBJECT, obj_ID);
                 in_buffer.ignore_event();
                 break;
             }
             obj->client_ID = ID;
             obj->time = in_buffer.get_dword();
             obj->x = in_buffer.get_short();
             obj->y = in_buffer.get_short();
             if (GET_OBJECT_TYPE(obj_ID) == NID_VANGER) {
                 x = obj->x;
                 y = obj->y;
                 y_half_size_of_screen = in_buffer.get_byte() << 1;
                 int update_size = in_buffer.event_size() - 14;
                 if (update_size > obj->body_size)
                     SERVER_ERROR("Update body size is greater than create size", obj_ID);
                 in_buffer.read(obj->body, update_size);
                 world->process_update(!(in_buffer.current_event() & ECHO_EVENT) ? this : 0, obj);
                 world->process_set_position(this);
             } else {
                 int update_size = in_buffer.event_size() - 13;
                 if (update_size > obj->body_size)
                     SERVER_ERROR("Update body size is greater than create size", obj_ID);
                 in_buffer.read(obj->body, update_size);
                 if (!PLAYERS_OBJECT(obj_ID))
                     world->process_update(
                         !(in_buffer.current_event() & ECHO_EVENT) ? this : 0, obj);
                 else {
                     if (NON_GLOBAL_OBJECT(obj_ID))
                         world->process_update_inventory(this, obj);
                     else
                         game->process_update_globals(
                             !(in_buffer.current_event() & ECHO_EVENT) ? this : 0, obj);
                 }
             }
             IN_EVENTS_LOG1(UPDATE_OBJECT, obj->ID);
         } break;
         case SET_POSITION:
             if (!world) {
                 SERVER_ERROR("Set position before set world", 0);
                 in_buffer.ignore_event();
                 break;
             }
             x = in_buffer.get_short();
             y = in_buffer.get_short();
             y_half_size_of_screen = in_buffer.get_short();
             if (world)
                 world->process_set_position(this);
             IN_EVENTS_LOG(SET_POSITION);
             break;
         case TOP_LIST_QUERY:
             server->get_top_list(out_buffer, in_buffer.get_byte());
             IN_EVENTS_LOG(TOP_LIST_QUERY);
             break;
         case GAMES_LIST_QUERY:
             code_queue.put(GAMES_LIST_RESPONSE);
             IN_EVENTS_LOG(GAMES_LIST_QUERY);
             break;
         case ATTACH_TO_GAME:
             if (game || ID)
                 SERVER_ERROR("Player have already been attached to game", game->ID);
             if ((game = server->games.search(in_buffer.get_int())) == 0 ||
                 (game->data.GameType == UNCONFIGURED && game->players.size()) ||
                 game->used_players_IDs == 0x7fffffff)
                 game = server->create_game();
             game->attach_player(this);
             game->check_global_objects(this);
             out_buffer.begin_event(ATTACH_TO_GAME_RESPONSE);
             out_buffer < game->ID < char(game->data.GameType != UNCONFIGURED ? 1 : 0) <
                 (unsigned int)round((double)game->birth_time * (256. / 1000.)) < (unsigned char)ID;
             game->get_object_ID_offsets(out_buffer, ID);
             out_buffer.end_event();
             IN_EVENTS_LOG(ATTACH_TO_GAME);
             break;
         case RESTORE_CONNECTION: {
             Player *p;
             Game *game;
             if ((game = server->games.search(in_buffer.get_int())) != 0 &&
                 (p = game->players.search(in_buffer.get_byte())) != 0) {
                 if (p->socket())
                     p->socket.close();
                 p->socket = socket;
                 p->time_to_remove = 0;
                 MOUT1("Connection have been restored", p->ID);
                 p->out_buffer.begin_event(RESTORE_CONNECTION_RESPONSE);
                 p->out_buffer < char(1);
                 p->out_buffer.end_event();
                 IN_EVENTS_LOG(RESTORE_CONNECTION);
             } else {
                 out_buffer.begin_event(RESTORE_CONNECTION_RESPONSE);
                 out_buffer < char(0);
                 out_buffer.end_event();
                 IN_EVENTS_LOG(RESTORE_CONNECTION);
             }
         } break;
         case REGISTER_NAME: {
             if (name)
                 delete name;
             int name_len = strlen(in_buffer(in_buffer.tell()));
             name = new char[name_len + 2];
             in_buffer > name;
             name[name_len + 1] = 0;
             int number = 0;
             Player *p = game->players.first();
             while (p) {
                 if (p != this && p->name && !strcmp(p->name, name)) {
                     name[name_len] = '0' + ++number;
                     p = game->players.first();
                 } else
                     p = p->next;
             }
             if (password)
                 delete password;
             password = new char[strlen(in_buffer(in_buffer.tell())) + 1];
             in_buffer > password;
             game->put_event_for_all(PLAYERS_NAME, this);
             IN_EVENTS_LOG(REGISTER_NAME);
             break;
         }
         case SET_WORLD: {
             if (world) {
                 SERVER_ERROR("Duplicated set world", ID);
                 in_buffer.ignore_event();
                 break;
             }
             int world_ID = in_buffer.get_byte();
             int world_y_size = in_buffer.get_short();
             int world_status = 0;
             if ((world = game->worlds.search(world_ID)) == 0) {
                 world = new World(world_ID, world_y_size);
                 game->worlds.append(world);
                 world_status = 1;
             } else if (world_y_size != world->V_SIZE)
                 SERVER_ERROR("Incorrect world Y size", world_y_size * 100000 + world->V_SIZE);
             out_buffer.begin_event(SET_WORLD_RESPONSE);
             out_buffer < (unsigned char)world_ID;
             out_buffer < (unsigned char)world_status;
             out_buffer.end_event();
             world->attach_player(this);
             IN_EVENTS_LOG(SET_WORLD);
             OUT_EVENTS_LOG1(SET_WORLD_RESPONSE, world_status);
         } break;
         case LEAVE_WORLD:
             if (!world) {
                 SERVER_ERROR("Leave world before set", 0);
                 in_buffer.ignore_event();
                 break;
             }
             world->detach_player(this);
             IN_EVENTS_LOG(STOP_QUERY);
             break;
         case SERVER_TIME_QUERY:
             out_buffer.begin_event(SERVER_TIME);
             out_buffer < (unsigned int)GLOBAL_CLOCK();
             out_buffer.end_event();
             IN_EVENTS_LOG(SERVER_TIME_QUERY);
             OUT_EVENTS_LOG(SERVER_TIME);
             break;
         case SET_GAME_DATA: {
             if (game->data.GameType != UNCONFIGURED) {
                 DOUT1("Attempt to reassign game data", game->ID);
             }
             in_buffer > game->name;
             int size = in_buffer.event_size() - 1 - strlen(game->name) - 1;
             if (size != sizeof(ServerData))
                 SERVER_ERROR("Incorrect Server Data", size);
             in_buffer.read((unsigned char *)&game->data, sizeof(ServerData));
             game->client_version = client_version;
             IN_EVENTS_LOG(SET_GAME_DATA);
         } break;
         case GET_GAME_DATA:
             code_queue.put(GAME_DATA_RESPONSE);
             IN_EVENTS_LOG(GET_GAME_DATA);
             break;
         case SET_PLAYER_DATA: {
             int size = in_buffer.event_size() - 1;
             if (size != sizeof(PlayerBody))
                 SERVER_ERROR("Incorrect Player Body", size);
             static PlayerBody prev_body;
             prev_body = body;
             in_buffer.read((unsigned char *)&body, sizeof(PlayerBody));
             switch (game->data.GameType) {
             case VAN_WAR:
                 if (body.kills != prev_body.kills || body.deaths != prev_body.deaths ||
                     body.rating != prev_body.rating) {
                     game->process_VAN_WAR_ratings();
                     if (fabs(body.rating - prev_body.rating) > 0.01)
                         code_queue.put(Event(PLAYERS_RATING, this));
                 }
                 break;
             case MECHOSOMA:
                 if (body.MechosomaStat.MaxTransitTime) {
                     game->process_MECHOSOMA_ratings();
                     if (fabs(body.rating - prev_body.rating) > 0.01)
                         code_queue.put(Event(PLAYERS_RATING, this));
                 }
                 break;
             case PASSEMBLOSS:
                 if (body.PassemblossStat.TotalTime) {
                     game->process_PASSEMBLOSS_ratings();
                     if (fabs(body.rating - prev_body.rating) > 0.01)
                         code_queue.put(Event(PLAYERS_RATING, this));
                 }
                 break;
             }
             game->put_event_for_all(PLAYERS_DATA, this);
             IN_EVENTS_LOG(SET_PLAYER_DATA);
         } break;
         case TOTAL_PLAYERS_DATA_QUERY:
             code_queue.put(TOTAL_LIST_OF_PLAYERS_DATA);
             IN_EVENTS_LOG(TOTAL_PLAYERS_DATA_QUERY);
             break;
         case DIRECT_SENDING: {
             unsigned int mask = in_buffer.get_dword();
             Object *obj = new Object();
             obj->ID = DIRECT_SENDING_OBJECT;
             obj->client_ID = ID;
             obj->time = GLOBAL_CLOCK();
             obj->body_size = in_buffer.event_size() - 5;
             obj->body = new unsigned char[obj->body_size];
             in_buffer.read(obj->body, obj->body_size);
             game->process_direct_sending(obj, mask);
             IN_EVENTS_LOG(DIRECT_SENDING);
         } break;
         case CLOSE_SOCKET:
             socket.close();
             time_to_remove = SDL_GetTicks();
             break;
         default:
             SERVER_ERROR("Incorrect event ID", in_buffer.current_event());
         }
         in_buffer.next_event();
     }
     return recv_size;
 }
References XTList< Type >::append(), World::attach_player(), Game::attach_player(), ATTACH_TO_GAME, ATTACH_TO_GAME_RESPONSE, AUXILIARY_EVENT, OutputEventBuffer::begin_event(), Game::birth_time, Object::body, body, Object::body_size, Game::check_global_objects(), Object::client_ID, client_mask, client_version, Game::client_version, XSocket::close(), CLOSE_SOCKET, code_queue, Server::create_game(), CREATE_PERMANENT_OBJECT, InputEventBuffer::current_event(), Game::data, Object::death_body_size, PlayerBody::deaths, DELETE_OBJECT, World::delete_object(), World::detach_player(), DIRECT_SENDING, DIRECT_SENDING_OBJECT, DOUT1, ECHO_EVENT, OutputEventBuffer::end_event(), XTList< Type >::first(), game, GAME_DATA_RESPONSE, Server::games, GAMES_LIST_QUERY, GAMES_LIST_RESPONSE, ServerData::GameType, InputEventBuffer::get_byte(), InputEventBuffer::get_dword(), GET_GAME_DATA, InputEventBuffer::get_int(), Game::get_object_ID_offsets(), GET_OBJECT_TYPE, InputEventBuffer::get_short(), Server::get_top_list(), GLOBAL_CLOCK, Game::global_objects, Object::ID, ID, Game::ID, InputEventBuffer::ignore_event(), in_buffer, IN_EVENTS_LOG, IN_EVENTS_LOG1, PlayerBody::kills, last_IO_operation, Object::last_update, LEAVE_WORLD, Object::list, MechosomaStatistic::MaxTransitTime, MECHOSOMA, PlayerBody::MechosomaStat, MOUT1, name, Game::name, next, InputEventBuffer::next_event(), NID_VANGER, NON_GLOBAL_OBJECT, out_buffer, OUT_EVENTS_LOG, OUT_EVENTS_LOG1, PASSEMBLOSS, PlayerBody::PassemblossStat, password, Game::players, PLAYERS_DATA, PLAYERS_NAME, PLAYERS_OBJECT, PLAYERS_RATING, World::process_create(), Game::process_create_globals(), World::process_create_inventory(), World::process_delete(), Game::process_delete_globals(), Game::process_direct_sending(), Game::process_MECHOSOMA_ratings(), Game::process_PASSEMBLOSS_ratings(), World::process_set_position(), World::process_update(), Game::process_update_globals(), World::process_update_inventory(), Game::process_VAN_WAR_ratings(), XQueue< Type >::put(), Game::put_event_for_all(), put_object(), Object::radius, PlayerBody::rating, XBuffer::read(), InputEventBuffer::receive(), REGISTER_NAME, XTList< Type >::remove(), RESTORE_CONNECTION, RESTORE_CONNECTION_RESPONSE, round(), XTList< Type >::search(), World::search_object(), Object::send_delete, server, SERVER_ERROR, SERVER_TIME, SERVER_TIME_QUERY, SET_GAME_DATA, SET_PLAYER_DATA, SET_POSITION, SET_WORLD, SET_WORLD_RESPONSE, XTList< Type >::size(), socket, XBuffer::tell(), Object::time, time_to_remove, TOP_LIST_QUERY, TOTAL_LIST_OF_PLAYERS_DATA, TOTAL_PLAYERS_DATA_QUERY, PassemblossStatistic::TotalTime, UNCONFIGURED, UPDATE_OBJECT, Game::used_players_IDs, World::V_SIZE, VAN_WAR, world, Game::worlds, Object::x, x, Object::y, y, and y_half_size_of_screen.
Referenced by Server::clients_quant(), and Game::quant().
send()
int Player::send ()
                  {
     if (!socket)
         return 0;
     Object *obj;
     int code, total_sent = 0;
     for (;;) {
         if (out_buffer.tell()) {
             int sent;
             total_sent += sent = out_buffer.send(socket);
             last_IO_operation = SDL_GetTicks();
             //          OUT_EVENTS_LOG1(Send_Block,sent);
             if (out_buffer.tell())
                 return total_sent;
         }
         // if(!current_sent_object)
         //  current_sent_object = object_queue.get();
         // if(current_sent_object && current_sent_object -> time + LAG < GLOBAL_CLOCK())
         //  obj = current_sent_object;
         //  current_sent_object = 0;
         // Object's Queue
         if (!object_queue.empty()) {
             obj = object_queue.get();
             obj->in_queue &= ~client_mask;
             // Check for deleted objects
             if (!obj->ID) {
                 if ((obj->send_delete &= ~client_mask) == 0)
                     delete obj;
                 continue;
             }
             if (obj->send_delete) { // !!!
                 if (obj->ID != DIRECT_SENDING_OBJECT) {
                     out_buffer.begin_event(DELETE_OBJECT);
                     out_buffer < obj->ID < (unsigned char)obj->client_ID < obj->time;
                     out_buffer.write(obj->body, obj->death_body_size);
                     out_buffer.end_event();
                     OUT_EVENTS_LOG1(DELETE_OBJECT, obj->ID);
                     if ((obj->send_delete &= ~client_mask) == 0) {
                         if (NON_GLOBAL_OBJECT(obj->ID))
                             world->delete_object(obj);
                         else
                             obj->list->remove(obj);
                         delete obj;
                     }
                 } else {
                     out_buffer.begin_event(DIRECT_RECEIVING);
                     out_buffer < (unsigned char)obj->client_ID;
                     out_buffer.write(obj->body, obj->body_size);
                     out_buffer.end_event();
                     OUT_EVENTS_LOG(DIRECT_RECEIVING);
                     if ((obj->send_delete &= ~client_mask) == 0)
                         delete obj;
                 }
                 continue;
             }
             if (!(obj->send_hide & client_mask)) {
                 out_buffer.begin_event(UPDATE_OBJECT);
                 out_buffer < obj->ID < (unsigned char)obj->client_ID < obj->time < (short)obj->x <
                     (short)obj->y;
                 out_buffer.write(obj->body, obj->body_size);
                 out_buffer.end_event();
                 OUT_EVENTS_LOG1(UPDATE_OBJECT, obj->ID);
                 continue;
             } else {
                 out_buffer.begin_event(HIDE_OBJECT);
                 out_buffer < obj->ID;
                 out_buffer.end_event();
                 OUT_EVENTS_LOG1(HIDE_OBJECT, obj->ID);
                 obj->send_hide &= ~client_mask;
                 continue;
             }
         }
         // Code Queue
         if (!code_queue.empty()) {
             Event event = code_queue.get();
             code = event.code;
             Player *player = event.pointer;
             switch (code) {
             case GAMES_LIST_RESPONSE:
                 server->get_games_list(out_buffer, client_version);
                 OUT_EVENTS_LOG(GAMES_LIST_RESPONSE);
                 break;
             case TOTAL_LIST_OF_PLAYERS_DATA:
                 game->get_total_list_of_players_data(out_buffer);
                 OUT_EVENTS_LOG(TOTAL_LIST_OF_PLAYERS_DATA);
                 break;
             case GAME_DATA_RESPONSE:
                 out_buffer.begin_event(GAME_DATA_RESPONSE);
                 out_buffer < game->name < char(0);
                 out_buffer.write(&game->data, sizeof(ServerData));
                 out_buffer.end_event();
                 OUT_EVENTS_LOG(GAME_DATA_RESPONSE);
                 break;
             case PLAYERS_NAME:
                 out_buffer.begin_event(PLAYERS_NAME);
                 out_buffer < (unsigned char)player->ID < player->name < char(0);
                 out_buffer.end_event();
                 OUT_EVENTS_LOG(PLAYERS_NAME);
                 break;
             case PLAYERS_POSITION:
                 out_buffer.begin_event(PLAYERS_POSITION);
                 out_buffer < (unsigned char)player->ID < short(player->x) < short(player->y);
                 out_buffer.end_event();
                 OUT_EVENTS_LOG(PLAYERS_POSITION);
                 break;
             case PLAYERS_WORLD:
                 out_buffer.begin_event(PLAYERS_WORLD);
                 out_buffer < (unsigned char)player->ID <
                     (unsigned char)(player->world ? player->world->ID : 0);
                 out_buffer.end_event();
                 OUT_EVENTS_LOG(PLAYERS_WORLD);
                 break;
             case PLAYERS_DATA:
                 out_buffer.begin_event(PLAYERS_DATA);
                 out_buffer < (unsigned char)player->ID;
                 out_buffer.write(&(player->body), sizeof(PlayerBody));
                 out_buffer.end_event();
                 OUT_EVENTS_LOG(PLAYERS_DATA);
                 break;
             case PLAYERS_RATING:
                 out_buffer.begin_event(PLAYERS_RATING);
                 out_buffer < (unsigned char)player->ID < (float)player->body.rating;
                 out_buffer.end_event();
                 OUT_EVENTS_LOG(PLAYERS_RATING);
                 break;
             case PLAYERS_STATUS:
                 out_buffer.begin_event(PLAYERS_STATUS);
                 out_buffer < (unsigned char)player->ID < (unsigned char)player->status;
                 out_buffer.end_event();
                 OUT_EVENTS_LOG(PLAYERS_STATUS);
                 break;
             default:
                 SERVER_ERROR("Incorrect event ID in code queue", code);
             }
             continue;
         }
         return total_sent;
     }
 }
References OutputEventBuffer::begin_event(), Object::body, body, Object::body_size, Object::client_ID, client_mask, client_version, Event::code, code_queue, Game::data, Object::death_body_size, DELETE_OBJECT, World::delete_object(), DIRECT_RECEIVING, DIRECT_SENDING_OBJECT, XQueue< Type >::empty(), OutputEventBuffer::end_event(), game, GAME_DATA_RESPONSE, GAMES_LIST_RESPONSE, XQueue< Type >::get(), Server::get_games_list(), Game::get_total_list_of_players_data(), HIDE_OBJECT, Object::ID, World::ID, ID, Object::in_queue, last_IO_operation, Object::list, name, Game::name, NON_GLOBAL_OBJECT, object_queue, out_buffer, OUT_EVENTS_LOG, OUT_EVENTS_LOG1, PLAYERS_DATA, PLAYERS_NAME, PLAYERS_POSITION, PLAYERS_RATING, PLAYERS_STATUS, PLAYERS_WORLD, PlayerBody::rating, XTList< Type >::remove(), OutputEventBuffer::send(), Object::send_delete, Object::send_hide, server, SERVER_ERROR, socket, status, XBuffer::tell(), Object::time, TOTAL_LIST_OF_PLAYERS_DATA, total_sent, UPDATE_OBJECT, world, XBuffer::write(), Object::x, x, Object::y, and y.
Referenced by Server::clients_quant(), and Game::quant().
Member Data Documentation
birth_time
unsigned int Player::birth_time
Referenced by Player().
body
PlayerBody Player::body
Referenced by Server::add_rating_data(), Game::load_result(), Game::process_MECHOSOMA_ratings(), Game::process_PASSEMBLOSS_ratings(), Game::process_VAN_WAR_ratings(), receive(), and send().
client_mask
int Player::client_mask
Referenced by Game::attach_player(), Game::check_global_objects(), clear_object_queue(), World::detach_player(), Game::detach_player(), Player(), World::process_create(), Game::process_create_globals(), World::process_create_inventory(), World::process_delete(), Game::process_delete_globals(), Game::process_direct_sending(), World::process_set_position(), World::process_update(), Game::process_update_globals(), World::process_update_inventory(), put_object(), receive(), and send().
client_version
int Player::client_version
Referenced by identification(), Player(), receive(), and send().
code_queue
XQueue<Event> Player::code_queue
Referenced by World::attach_player(), World::process_set_position(), Game::put_event_for_all(), receive(), and send().
game
Game* Player::game
Referenced by World::attach_player(), Game::attach_player(), World::detach_player(), Game::detach_player(), is_alive(), Player(), receive(), and send().
ID
int Player::ID
Referenced by Game::attach_player(), World::detach_player(), Game::detach_player(), is_alive(), Player(), Game::quant(), receive(), Server::report(), and send().
identificated
int Player::identificated
Referenced by Server::clients_quant(), identification(), and Player().
in_buffer
InputEventBuffer Player::in_buffer
Referenced by receive().
inventory
XTList<Object> Player::inventory
Referenced by World::detach_player(), Game::get_object_ID_offsets(), World::process_create_inventory(), World::process_set_position(), and Server::report().
last_IO_operation
unsigned int Player::last_IO_operation
Referenced by is_alive(), Player(), receive(), and send().
last_sent_position
unsigned int Player::last_sent_position
Referenced by Player(), and World::process_set_position().
list
XTList<Player>* Player::list
Referenced by Player().
list_alt
XTListAlt<Player>* Player::list_alt
Referenced by Player().
name
char* Player::name
Referenced by Server::add_rating_data(), Game::load_result(), Player(), receive(), Server::report(), send(), and ~Player().
next
Player* Player::next
Referenced by Server::clients_quant(), Game::get_object_ID_offsets(), Player(), Game::process_create_globals(), Game::process_delete_globals(), Game::process_direct_sending(), Game::process_MECHOSOMA_ratings(), Game::process_PASSEMBLOSS_ratings(), Game::process_update_globals(), Game::process_VAN_WAR_ratings(), Game::put_event_for_all(), Game::quant(), receive(), and Server::report().
next_alt
Player* Player::next_alt
Referenced by World::detach_player(), Player(), World::process_create(), World::process_create_inventory(), World::process_delete(), World::process_set_position(), World::process_update(), and World::process_update_inventory().
object_queue
XQueue<Object *> Player::object_queue
Referenced by clear_object_queue(), put_object(), and send().
out_buffer
OutputEventBuffer Player::out_buffer
Referenced by receive(), and send().
password
char* Player::password
Referenced by Server::add_rating_data(), Player(), receive(), and ~Player().
prev
Player* Player::prev
Referenced by Player().
prev_alt
Player* Player::prev_alt
Referenced by Player().
prev_rating
float Player::prev_rating
Referenced by Server::add_rating_data(), and Player().
server
Server* Player::server
Referenced by Game::attach_player(), Player(), Game::process_MECHOSOMA_ratings(), Game::process_PASSEMBLOSS_ratings(), Game::process_VAN_WAR_ratings(), receive(), and send().
socket
XSocket Player::socket
Referenced by identification(), is_alive(), Player(), receive(), Server::report(), and send().
status
int Player::status
Referenced by World::attach_player(), Player(), Game::process_MECHOSOMA_ratings(), Game::process_PASSEMBLOSS_ratings(), Game::process_VAN_WAR_ratings(), Game::quant(), and send().
time_to_remove
unsigned int Player::time_to_remove
Referenced by is_alive(), Player(), and receive().
total_received
int Player::total_received
total_sent
int Player::total_sent
Referenced by send().
world
World* Player::world
Referenced by World::attach_player(), clear_object_queue(), World::detach_player(), Game::detach_player(), Player(), receive(), Server::report(), and send().
x
int Player::x
Referenced by World::attach_player(), Player(), World::process_set_position(), receive(), and send().
x_prev
int Player::x_prev
Referenced by World::attach_player(), Player(), and World::process_set_position().
y
int Player::y
Referenced by World::attach_player(), World::check_visibility(), Player(), World::process_set_position(), receive(), and send().
y_half_size_of_screen
int Player::y_half_size_of_screen
Referenced by World::attach_player(), World::check_visibility(), Player(), World::process_set_position(), and receive().
y_half_size_of_screen_prev
int Player::y_half_size_of_screen_prev
Referenced by World::attach_player(), Player(), and World::process_set_position().
y_prev
int Player::y_prev
Referenced by World::attach_player(), Player(), and World::process_set_position().
The documentation for this struct was generated from the following files:
server/server.h
server/server.cpp