Vangers: PassageImageType Struct Reference
PassageImageType Struct Reference
#include <hobj.h>
Public Member Functions
void Open (char *name)
void Close (void)
void Show (void)
void Hide (void)
Public Attributes
int xSize
int ySize
char * Name
char * Data
char Pal [768]
Detailed Description
Member Function Documentation
Close()
void PassageImageType::Close (void)
 {
     if(Name) {
         delete[] Name;
     }
 };
References Name.
Hide()
void PassageImageType::Hide (void)
 {
     int i,j;
     int delta[768],start[768];
     if(!Name) return;
     for(i = 0;i < 768;i++){
         start[i] = Pal[i] << 16;
         delta[i] = -start[i] / MAX_PASSAGE_IMAGE_SHOW_TIME;
     };
     for(j = 0;j < MAX_PASSAGE_IMAGE_SHOW_TIME;j++){
         for(i = 0;i < 768;i++){
             start[i] += delta[i];
             palbuf[i] = (uchar)(start[i] >> 16);
         };
         XGR_SetPal(palbuf,0,255);
     };
     aciSetRedraw();
 };
References aciSetRedraw(), MAX_PASSAGE_IMAGE_SHOW_TIME, Name, Pal, palbuf, and XGR_SetPal.
Referenced by ChangeWorld().
Open()
void PassageImageType::Open (char * name)
 {
     short st;
     XStream in(0);
     XBuffer buf(1024);
     buf.init();
     buf < iVideoPathDefault < "svs/" < name;
     if(!in.open(buf.address(),XS_IN)){
         buf.init();
         buf < iVideoPath < "svs/" < name;
         if(!in.open(buf.address(),XS_IN)){
             Name = NULL;
             return;
         };
     };
     in.read(Pal,768);
     in > st;
     xSize = st;
     in > st;
     ySize = st;
     in.close();
     Name = new char[strlen(buf.address()) + 1];
     strcpy(Name,buf.address());
 };
References XBuffer::address(), XStream::close(), XBuffer::init(), iVideoPath, iVideoPathDefault, Name, NULL, XStream::open(), Pal, XStream::read(), XS_IN, xSize, and ySize.
Referenced by GeneralSystemInit().
Show()
void PassageImageType::Show (void)
 {
     int i,j;
     int delta[768],start[768];
     int cclx,ccly,ccrx,ccry,ccm;
     short st;
     XStream in;
     if(!Name) return;
     in.open(Name,XS_IN);
     in.read(Pal,768);
     in > st;
     in > st;
     Data = new char[xSize*ySize];
     in.read(Data,xSize*ySize);
     in.close();
     for(i = 0;i < 768;i++){
         start[i] = palbuf[i] << 16;
         delta[i] = -start[i] / MAX_PASSAGE_IMAGE_SHOW_TIME;
     };
     for(j = 0;j < MAX_PASSAGE_IMAGE_SHOW_TIME;j++){
         for(i = 0;i < 768;i++){
             start[i] += delta[i];
             palbuf[i] = (uchar)(start[i] >> 16);
         };
         XGR_SetPal(palbuf,0,255);
     };
 //  PassageImageType::Hide();
 //  XGR_PutSpr(0,0,xSize,ySize,Data,XGR_BLACK_FON);
     ccm = XGR_Obj.ClipMode;
     XGR_SetClipMode(XGR_CLIP_ALL);
     cclx = XGR_Obj.clipLeft;
     ccly = XGR_Obj.clipTop;
     ccrx = XGR_Obj.clipRight;
     ccry = XGR_Obj.clipBottom;
     XGR_SetClip(0,0,XGR_MAXX,XGR_MAXY);
     XGR_PutSpr(0,0,xSize,ySize,Data,XGR_BLACK_FON);
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     XGR_SetClip(cclx,ccly,ccrx,ccry);
     XGR_SetClipMode(ccm);
     for(i = 0;i < 768;i++){
         start[i] = 0;
         delta[i] = ((int)(Pal[i]) << 16) / MAX_PASSAGE_IMAGE_SHOW_TIME;
     };
     for(j = 0;j < MAX_PASSAGE_IMAGE_SHOW_TIME;j++){
         for(i = 0;i < 768;i++){
             start[i] += delta[i];
             palbuf[i] = (uchar)(start[i] >> 16);
         };
         XGR_SetPal(palbuf,0,255);
     };
     delete[] Data;
 };
References XGR_Screen::clipBottom, XGR_Screen::clipLeft, XGR_Screen::ClipMode, XGR_Screen::clipRight, XGR_Screen::clipTop, XStream::close(), Data, MAX_PASSAGE_IMAGE_SHOW_TIME, Name, XStream::open(), Pal, palbuf, XStream::read(), XGR_BLACK_FON, XGR_CLIP_ALL, XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_Obj, XGR_PutSpr, XGR_SetClip, XGR_SetClipMode, XGR_SetPal, XS_IN, xSize, and ySize.
Referenced by ChangeWorld().
Member Data Documentation
Data
char* PassageImageType::Data
Referenced by Show().
Name
char* PassageImageType::Name
Referenced by Close(), Hide(), Open(), and Show().
Pal
char PassageImageType::Pal[768]
Referenced by Hide(), Open(), and Show().
xSize
int PassageImageType::xSize
Referenced by Open(), and Show().
ySize
int PassageImageType::ySize
Referenced by Open(), and Show().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp