Vangers: ServersList Struct Reference
ServersList Struct Reference
#include <network.h>
Public Member Functions
void clear_states ()
int talk_to_server (int IP, int port, char *domain_name, int only_new_game=0)
int find_servers_in_the_internet (char *host_name, int host_port=DEFAULT_SERVER_PORT)
Public Member Functions inherited from XTList< ServerFindChain >
XTList ()
~XTList ()
int size ()
ServerFindChain * first ()
ServerFindChain * last ()
void clear ()
void delete_all ()
void insert (ServerFindChain *p)
void insert (ServerFindChain *pointer, ServerFindChain *p)
void append (ServerFindChain *p)
void append (ServerFindChain *pointer, ServerFindChain *p)
void remove (ServerFindChain *p)
ServerFindChain * search (int ID)
Public Attributes
char domain_name [257]
Detailed Description
Member Function Documentation
clear_states()
void ServersList::clear_states ()
 {
     ServerFindChain* p;
     while((p = first()) != 0){
         remove(p);
         delete p;
         }
 }
References XTList< ServerFindChain >::first(), and XTList< ServerFindChain >::remove().
Referenced by KDWIN::create_server(), and find_servers_in_the_internet().
find_servers_in_the_internet()
int ServersList::find_servers_in_the_internet (char * host_name, int host_port = DEFAULT_SERVER_PORT)
 {
     clear_states();
     strcpy(domain_name, host_name);
     return talk_to_server(0, host_port, domain_name);
 }
References clear_states(), domain_name, host_name, host_port, and talk_to_server().
Referenced by iUpdateServersList().
talk_to_server()
int ServersList::talk_to_server (int IP, int port, char * domain_name, int only_new_game = 0)
 {
     XSocket sock;
     if(IP) {
         sock.open(IP,port);
     } else {
         if(!domain_name)
             return 0;
 //      if(!iProxyUsage || !iProxyServer)
             sock.open(domain_name,port);
 //      else
 //          sock.open_by_socks5(domain_name,port,iProxyServer,iProxyPort);
     }
     if(!sock || !identification(sock))
         return 0;
     XBuffer servers_buffer(10000);
     servers_buffer < short(1) < char(GAMES_LIST_QUERY);
     if(!sock.send(servers_buffer.GetBuf(),servers_buffer.tell()))
         return 0;
     START_TIMER(60*1000);
     while(CHECK_TIMER())
         if(sock.receive(servers_buffer.GetBuf(), servers_buffer.length(), 1000))
             break;
     ServerFindChain* p;
     unsigned char n_games,event_ID;
     int game_ID;
     char game_name[257];
     short event_size;
     servers_buffer.set(0);
     servers_buffer > event_size > event_ID > n_games;
     if(event_ID != GAMES_LIST_RESPONSE)
         return 0;
     if(only_new_game)
         n_games = 0;
     for(int i = 0;i < n_games;i++) {
         servers_buffer > game_ID > game_name;
         std::cout<<"game_ID:"<<game_ID<<" game_name:"<<game_name<<std::endl;
         p = new ServerFindChain(IP, port, domain_name, game_ID, game_name);
         append(p);
     }
     p = new ServerFindChain(IP,port,domain_name,0,0);
     append(p);
     return n_games + 1;
 }
References XTList< ServerFindChain >::append(), CHECK_TIMER, domain_name, GAMES_LIST_QUERY, GAMES_LIST_RESPONSE, XBuffer::GetBuf(), identification(), XBuffer::length(), XSocket::open(), XSocket::receive(), XSocket::send(), XBuffer::set(), START_TIMER, and XBuffer::tell().
Referenced by KDWIN::create_server(), find_servers_in_the_internet(), and xtInitApplication().
Member Data Documentation
domain_name
char ServersList::domain_name[257]
Referenced by find_servers_in_the_internet(), and talk_to_server().
The documentation for this struct was generated from the following files:
src/network.h
src/network.cpp