Vangers: FirstEscaveRTO Struct Reference
FirstEscaveRTO Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
virtual void Finit (void)
FirstEscaveRTO (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Additional Inherited Members
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
FirstEscaveRTO()
FirstEscaveRTO::FirstEscaveRTO (void) inline
 { ID = RTO_FIRST_ESCAVE_ID; Timer = RTO_ISCREEN_TIMER; }
References XRuntimeObject::ID, RTO_FIRST_ESCAVE_ID, RTO_ISCREEN_TIMER, and XRuntimeObject::Timer.
Member Function Documentation
Finit()
void FirstEscaveRTO::Finit (void) virtual
Reimplemented from XRuntimeObject.
 {
     if(flags & RTO_FINIT_FLAG){
         ClearFlag(RTO_ALL_FLAGS);
     }
     else {
         SetFlag(RTO_FINIT_FLAG);
     }
 _MEM_STATISTIC_("AFTER FIRST ESCAVE FINIT -> ");
 }
References _MEM_STATISTIC_, BaseRTO::ClearFlag(), BaseRTO::flags, RTO_ALL_FLAGS, RTO_FINIT_FLAG, and BaseRTO::SetFlag().
Init()
void FirstEscaveRTO::Init (int id) virtual
Reimplemented from XRuntimeObject.
 {
 _MEM_STATISTIC_("\nBEFORE FIRST ESCAVE RTO INIT -> ");
 #ifdef ISCREEN
     CurrentWorld = 0;
     if(aciLoadLog){
         aciLoadData();
 _MEM_STATISTIC_("AFTER ACILOADDATA INIT -> ");
     }
     FirstShopPrepare(aciLoadLog);
 _MEM_STATISTIC_("AFTER FIRSTSHOP PREPARE INIT -> ");
 #ifndef _ACI_SKIP_SHOP_
     aci_LocationQuantPrepare();
 _MEM_STATISTIC_("AFTER LOADQUANT PREPARE INIT -> ");
     aciShowLocation();
 _MEM_STATISTIC_("AFTER SHOWLOCATION INIT -> ");
 #else
     aciPrepareMenus();
 _MEM_STATISTIC_("AFTER PREPARE MENU INIT -> ");
 #endif
 #endif
 _MEM_STATISTIC_("AFTER FIRST ESCAVE RTO INIT -> ");
 }
References _MEM_STATISTIC_, aci_LocationQuantPrepare(), aciLoadData(), aciLoadLog, aciPrepareMenus(), aciShowLocation(), CurrentWorld, and FirstShopPrepare().
Quant()
int FirstEscaveRTO::Quant (void) virtual
Reimplemented from XRuntimeObject.
 {
 //std::cout<<"FirstEscaveRTO::Quant"<<std::endl;
 #ifdef ISCREEN
     int code;
 #ifndef _ACI_SKIP_SHOP_
     code = iQuantSecond();
 #else
     code = 1;
 #endif
     if(code){
         if(!iScrExitCode)
             return RTO_SHOW_IMAGE_ID;
         rtoSetNextID(RTO_FIRST_ESCAVE_OUT_ID,RTO_LOADING2_ID);
         rtoSetNextID(RTO_LOADING2_ID,RTO_GAME_QUANT_ID);
         return RTO_FIRST_ESCAVE_OUT_ID;
     }
     //XGR_Flip();
     return 0;
 #else
     return RTO_GAME_QUANT_ID;
 #endif
 }
References iQuantSecond(), iScrExitCode, RTO_FIRST_ESCAVE_OUT_ID, RTO_GAME_QUANT_ID, RTO_LOADING2_ID, RTO_SHOW_IMAGE_ID, and rtoSetNextID().
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp