Vangers: scMathExpression Struct Reference
scMathExpression Struct Reference
#include <iscript.h>
Public Member Functions
void clear (void)
int check_math (char *p)
void add2list (ScriptBlock *p)
void free_list (void)
void prepare_list (void)
int eval (void)
void eval_quant (void)
void connect (scMathNode *p)
void dconnect (scMathNode *p)
scMathExpression (void)
~scMathExpression (void)
Public Attributes
int Size
int MaxValue
scMathNode * first
scMathNode * last
Detailed Description
Constructor & Destructor Documentation
scMathExpression()
scMathExpression::scMathExpression (void)
 {
     clear();
 }
References clear().
~scMathExpression()
scMathExpression::~scMathExpression (void)
 {
     free_list();
 }
References free_list().
Member Function Documentation
add2list()
void scMathExpression::add2list (ScriptBlock * p)
 {
     int code;
     scMathNode* n = new scMathNode;
     code = check_math(p -> data);
     if(code)
         n -> op_code = code - 1;
     else {
         n -> value = atoi(p -> data);
     }
     connect(n);
 }
References check_math(), and connect().
check_math()
int scMathExpression::check_math (char * p)
 {
     int i;
     for(i = 0; i < MT_MAX_CODE; i ++){
         if(*p == *scMathOpNames[i] && !strcmp(p,scMathOpNames[i])) return (i + 1);
     }
     return 0;
 }
References MT_MAX_CODE.
Referenced by add2list().
clear()
void scMathExpression::clear (void) inline
 { first = last = NULL; Size = 0; MaxValue = 0; }
References first, last, MaxValue, NULL, and Size.
Referenced by free_list(), and scMathExpression().
connect()
void scMathExpression::connect (scMathNode * p)
 {
     if(last){
         last -> next = p;
         p -> prev = last;
         p -> next = first;
         last  = p;
     }
     else{
         last = p;
         first = p;
         p -> next = p;
         p -> prev = 0;
     }
     Size ++;
 }
References last.
Referenced by add2list().
dconnect()
void scMathExpression::dconnect (scMathNode * p)
 {
     Size --;
     if(!Size){
         last = first = NULL;
         return;
     }
     if(p -> next -> prev)
         p -> next -> prev = p -> prev;
     else
         last = p -> prev;
     if(p -> prev)
         p -> prev -> next = p -> next;
     else {
         first = p -> next;
         last -> next = p -> next;
     }
 }
References first, last, NULL, and Size.
eval()
int scMathExpression::eval (void)
 {
     if(!Size) return 0;
 #ifdef _iSCRIPT_DEBUG_
     int file_out = 0;
     if(Size > 1){
         if(mtLogFile){
             logFile.open("ISCREEN\\math.dat",XS_OUT | XS_APPEND | XS_NOREPLACE);
         }
         else {
             mtLogFile = 1;
             logFile.open("ISCREEN\\math.dat",XS_OUT);
         }
         logFile < "\r\n---------------------- EXPRESSION START ----------------------\r\n";
         write();
         file_out = 1;
     }
 #endif
     while(Size > 1){
         eval_quant();
     }
 #ifdef _iSCRIPT_DEBUG_
     if(file_out){
         logFile < "----------------------- EXPRESSION END -----------------------\r\n";
         logFile.close();
     }
 #endif
     return first -> value;
 }
References eval_quant(), first, Size, XS_APPEND, XS_NOREPLACE, and XS_OUT.
eval_quant()
void scMathExpression::eval_quant (void)
 {
     int flag = 0;
     scMathNode* p,*pp,*pn;
     p = last;
     while(p){
         if(p -> op_code != -1 && p -> value == MaxValue){
             pp = p -> prev;
             pn = p -> next;
             if(!pp || pn == first || pp -> op_code != -1 || pn -> op_code != -1)
                 handle_error("Math expression error");
 #ifdef _iSCRIPT_DEBUG_
             logFile < "Step -> " <= pp -> value < " " < scMathOpNames[p -> op_code] < " " <= pn -> value < "\r\n";
 #endif
             switch(p -> op_code){
                 case MT_PLUS:
                     pp -> value += pn -> value;
                     break;
                 case MT_MINUS:
                     pp -> value -= pn -> value;
                     break;
                 case MT_MUL:
                     pp -> value *= pn -> value;
                     break;
                 case MT_DIV:
                     pp -> value /= pn -> value;
                     break;
             }
             dconnect(p);
             dconnect(pn);
             delete p;
             delete pn;
             break;
         }
         p = p -> prev;
     }
     p = last;
     while(p){
         if(p -> op_code != -1 && p -> value == MaxValue) flag = 1;
         p = p -> prev;
     }
     if(!flag && MaxValue) MaxValue --;
 }
References last, MaxValue, and prev.
Referenced by eval().
free_list()
void scMathExpression::free_list (void)
 {
     scMathNode* p,*p1;
     p = last;
     while(p){
         p1 = p -> prev;
         delete p;
         p = p1;
     }
     clear();
 }
References clear(), last, and prev.
Referenced by ~scMathExpression().
prepare_list()
void scMathExpression::prepare_list (void)
 {
     int i,delta = 0;
     scMathNode* p,*p1;
     p = first;
     for(i = 0; i < Size; i ++){
         if(p -> op_code != -1){
             if(p -> op_code == MT_LEFT_BR){
                 delta += 2;
             }
             else {
                 if(p -> op_code == MT_RIGHT_BR){
                     delta -= 2;
                 }
                 else {
                     p -> value = delta + scMathOpLevels[p -> op_code];
                     if(MaxValue < p -> value) MaxValue = p -> value;
                 }
             }
         }
         p = p -> next;
     }
     if(delta)
         handle_error("Math expression error");
     p = last;
     while(p){
         p1 = p -> prev;
         if(p -> op_code == MT_LEFT_BR || p -> op_code == MT_RIGHT_BR){
             dconnect(p);
             delete p;
         }
         p = p1;
     }
 }
References first, MT_LEFT_BR, MT_RIGHT_BR, and Size.
Member Data Documentation
first
scMathNode* scMathExpression::first
Referenced by clear(), dconnect(), eval(), and prepare_list().
last
scMathNode* scMathExpression::last
Referenced by clear(), connect(), dconnect(), eval_quant(), and free_list().
MaxValue
int scMathExpression::MaxValue
Referenced by clear(), and eval_quant().
Size
int scMathExpression::Size
Referenced by clear(), dconnect(), eval(), and prepare_list().
The documentation for this struct was generated from the following files:
src/iscreen/iscript.h
src/iscreen/script.cpp