Vangers: MessageDispatcher Struct Reference
MessageDispatcher Struct Reference
#include <network.h>
Public Member Functions
MessageDispatcher (int max_num_messages=15)
MessageElement * first ()
MessageElement * last ()
void send (char *message, int mode, int parameter)
void receive ()
Public Member Functions inherited from XList
void ClearList (void)
void AddElement (XListElement *p)
void RemoveElement (XListElement *p)
XList (void)
~XList (void)
Public Attributes
int max_number_of_messages
int new_messages
Public Attributes inherited from XList
int ListSize
XListElement * fPtr
XListElement * lPtr
Detailed Description
Constructor & Destructor Documentation
MessageDispatcher()
MessageDispatcher::MessageDispatcher (int max_num_messages = 15) inline
 : XList() { max_number_of_messages = max_num_messages; }
References max_number_of_messages.
Member Function Documentation
first()
MessageElement* MessageDispatcher::first () inline
 { return (MessageElement*)fPtr; }
References XList::fPtr.
Referenced by iGameMap::draw(), iChatClearLog(), iInitChatScreen(), receive(), and send().
last()
MessageElement* MessageDispatcher::last () inline
 { return (MessageElement*)lPtr; }
References XList::lPtr.
Referenced by iGameMap::draw().
receive()
void MessageDispatcher::receive ()
 {
     char msg[512];
     events_in > msg;
     PlayerData* p = players_list.find(events_in.current_creator());
     MessageElement* pm = new MessageElement(p ? p -> name : (char *)"Unknown", msg, p -> body.color);
     AddElement(pm);
     if(ListSize > max_number_of_messages){
         RemoveElement(pm = first());
         delete pm;
         }
 #ifdef _ROAD_
     SOUND_BEEP();
     //zmod
     //IncomingChatMessage();
 #endif
     //zmod
     new_messages = 1;
 }
References XList::AddElement(), InputEventBuffer::current_creator(), events_in, PlayersList::find(), first(), XList::ListSize, max_number_of_messages, new_messages, players_list, XList::RemoveElement(), and SOUND_BEEP.
send()
void MessageDispatcher::send (char * message, int mode, int parameter)
 {
     unsigned int cors;
     switch(mode){
         case MESSAGE_FOR_ALL:
             cors = 0xffffffff & ~(1 << (GlobalStationID - 1));
             break;
         case MESSAGE_FOR_TEAM:
             cors = players_list.get_team_mask(parameter) & ~(1 << (GlobalStationID - 1));
             break;
         case MESSAGE_FOR_PLAYER:
             cors = 1 << (parameter - 1);
             break;
         }
     events_out.begin_direct_send(cors);
     events_out < message < char(0);
     events_out.end_body();
     events_out.send(1);
     MessageElement* p = new MessageElement(CurPlayerName, message, my_player_body.color);
     AddElement(p);
     if(ListSize > max_number_of_messages){
         RemoveElement(p = first());
         delete p;
         }
     //zmod
     new_messages = 1;
 }
References XList::AddElement(), OutputEventBuffer::begin_direct_send(), PlayerBody::color, CurPlayerName, OutputEventBuffer::end_body(), events_out, first(), PlayersList::get_team_mask(), GlobalStationID, XList::ListSize, max_number_of_messages, MESSAGE_FOR_ALL, MESSAGE_FOR_PLAYER, MESSAGE_FOR_TEAM, my_player_body, new_messages, players_list, XList::RemoveElement(), and OutputEventBuffer::send().
Referenced by iChatInputFlush().
Member Data Documentation
max_number_of_messages
int MessageDispatcher::max_number_of_messages
Referenced by MessageDispatcher(), receive(), and send().
new_messages
int MessageDispatcher::new_messages
Referenced by iGameMap::draw(), receive(), and send().
The documentation for this struct was generated from the following files:
src/network.h
src/network.cpp