Vangers: aiListType Struct Reference
aiListType Struct Reference
#include <mechos.h>
Public Member Functions
void Init (void)
void Free (void)
void Connect (aiListElement *p)
void Disconnect (aiListElement *p)
Public Attributes
aiListElement * Tail
int Num
Detailed Description
Member Function Documentation
Connect()
void aiListType::Connect (aiListElement * p)
 {
     if(!Tail){
         p->Next = p->Prev = NULL;
         Tail = p;
     }else{
         Tail -> Prev = p;
         p -> Next = Tail;
         p -> Prev = NULL;
         Tail = p;
     };
     Num++;
 };
References aiListElement::Next, NULL, Num, aiListElement::Prev, and Tail.
Referenced by VangerUnit::AddEvent(), aiResolveList::AddResolve(), and aiResolveList::FastAddResolve().
Disconnect()
void aiListType::Disconnect (aiListElement * p)
 {
     if((!p->Prev) && (!p->Next)) Tail = NULL;
     else{
         if(p->Prev) p->Prev->Next = p->Next;
         else Tail = p->Next;
         if(p->Next) p->Next->Prev = p->Prev;
     };
     Num--;
 };
References aiListElement::Next, NULL, Num, aiListElement::Prev, and Tail.
Referenced by aiResolveList::AddResolve(), Free(), VangerUnit::InitEnvironment(), and VangerUnit::ResolveGenerator().
Free()
void aiListType::Free (void)
 {
     aiListElement* p;
     aiListElement* pp;
     p = Tail;
     while(p){
         pp = p->Next;
         Disconnect(p);
         delete p;
         p = pp;
     };
 };
References Disconnect(), aiListElement::Next, and Tail.
Referenced by VangerUnit::ChangeVangerProcess(), and VangerUnit::Go2Universe().
Init()
void aiListType::Init (void)
 {
     Num = 0;
     Tail = NULL;
 };
References NULL, Num, and Tail.
Referenced by VangerUnit::ChangeVangerProcess(), and VangerUnit::Go2World().
Member Data Documentation
Num
int aiListType::Num
Referenced by VangerUnit::CalcAiFactor(), Connect(), Disconnect(), Init(), and VangerUnit::ResolveGenerator().
Tail
aiListElement* aiListType::Tail
Referenced by VangerUnit::AddEvent(), VangerUnit::AddEventTime(), VangerUnit::ClearEvent(), VangerUnit::ClearObjEvent(), aiResolveList::ClearResolve(), aiResolveList::ClearResolveForce(), VangerUnit::ClearSubjEvent(), Connect(), Disconnect(), VangerUnit::FindEvent(), aiResolveList::FindResolve(), Free(), Init(), VangerUnit::InitEnvironment(), and VangerUnit::ResolveGenerator().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp