Vangers: dgCell Struct Reference
dgCell Struct Reference
#include <diagen.h>
Public Member Functions
dgCell (dgRoom *r)
void read (dgFile *dgf)
int isACCESS (void)
int doCMD (int startup=1)
int analyzeACCESS (char *p)
int expressACCESS (int endreq, char *&p, int &uplogic)
Public Attributes
int x
int y
char * Name
int Type
int isWaiting
int isLooping
dgFile Access
dgFile PostCMD
dgFile StartCMD
dgRoom * owner
Detailed Description
Constructor & Destructor Documentation
dgCell()
dgCell::dgCell (dgRoom * r) inline
 { Name = NULL; Type = isWaiting = isLooping = -1; owner = r; }
References isLooping, isWaiting, Name, NULL, owner, and Type.
Member Function Documentation
analyzeACCESS()
int dgCell::analyzeACCESS (char * p)
 {
     int i = 0;
     do if(!strcasecmp(p,Query[i].name)) break;
     while(Query[++i].name);
     if(!Query[i].name)
         std::cout<<"Unknown query "<<p<<std::endl;
     char* opr,*arg2;
     int lvalue = 0,rvalue;
     dgRoom* r;
     switch(Query[i].id){
         case Q::TRU:
             return 1;
         case Q::DATA:
             p = Access.getElement(DGF_NONE);
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             if(*arg2 == '$'){
                 arg2++;
                 if(!strcmp(arg2,"ELR_TOTAL")) rvalue = uvsgetDGdata(DG_EXTERNS::ELR_TOTAL);
                 else if(!strcmp(arg2,"KER_TOTAL")) rvalue = uvsgetDGdata(DG_EXTERNS::KER_TOTAL);
                 else if(!strcmp(arg2,"PIP_TOTAL")) rvalue = uvsgetDGdata(DG_EXTERNS::PIP_TOTAL);
                 else if(!strcmp(arg2,"ZYK_TOTAL")) rvalue = uvsgetDGdata(DG_EXTERNS::ZYK_TOTAL);
 #ifdef DIAGEN_TEST
                 else if(!strcmp(arg2,"PREV_CYCLE_1")) rvalue = 0;
                 else if(!strcmp(arg2,"PREV_CYCLE_2")) rvalue = 1;
 #else
                 else if(!strcmp(arg2,"PREV_CYCLE_1")) rvalue = getPreviousCycle(1);
                 else if(!strcmp(arg2,"PREV_CYCLE_2")) rvalue = getPreviousCycle(2);
 #endif
 #ifdef DIAGEN_TEST
                 else{
                     XBuffer buf;
                     buf < arg2 < "/" < owner -> roomName;
                     ErrH.Abort("Wrong ARG2",XERR_USER,-1,buf.GetBuf());
                     }
 #else
                 else ErrH.Abort("Wrong ARG2");
 #endif
             }
             else
                 rvalue = atoi(arg2);
             i = 0; do if(!strcmp(p,ArgData[i].name)) break;
             while(ArgData[++i].name);
             if(!ArgData[i].name) ErrH.Abort("Unknown data",XERR_USER,-1,p);
             lvalue = uvsgetDGdata(ArgData[i].id);
             return Comparision(opr,lvalue,rvalue);
         case Q::VISITE:
             p = Access.getElement(DGF_NONE);
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             r = owner -> owner -> seekR(p,1);
             if(!r) ErrH.Abort("Unknown Escave-ID");
             lvalue = r -> visitCounter;
             rvalue = atoi(arg2);
             return Comparision(opr,lvalue,rvalue);
         case Q::VISITW:
             p = Access.getElement(DGF_NONE);
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
 //#ifndef DIAGEN_TEST
             lvalue = getWorldVisitStats(*p);
 //#endif
             rvalue = atoi(arg2);
             return Comparision(opr,lvalue,rvalue);
         case Q::COMING:
             p = Access.getElement(DGF_NONE);
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             r = owner -> owner -> seekR(p,1);
             if(!r) ErrH.Abort("Unknown Escave-ID");
             lvalue = r -> comingCounter;
             rvalue = atoi(arg2);
             return Comparision(opr,lvalue,rvalue);
         case Q::SINGLERAND:
             p = Access.getElement(DGF_NONE);
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             if(singleRandAvailable){
                 lvalue = realRND(atoi(p));
                 rvalue = atoi(arg2);
                 if(Comparision(opr,lvalue,rvalue)){
                     singleRandAvailable = 0;
                     return 1;
                     }
                 else
                     return 0;
                 }
             else
                 return 0;
         case Q::BSTATUS:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,owner -> owner -> bStatus,rvalue);
         case Q::ZSTATUS:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,owner -> owner -> zStatus,rvalue);
         case Q::SSTATUS:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,owner -> owner -> sStatus,rvalue);
         case Q::ENTER_SSTATUS:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,enter_sStatus,rvalue);
         case Q::QCODE:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,Qcode,rvalue);
         case Q::MP_GAME:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,MP_GAME,rvalue);
         case Q::CYCLE_EXIST:
             lvalue = atoi(Access.getElement(DGF_NONE));
             opr = Access.getElement(DGF_NONE);
             rvalue = atoi(Access.getElement(DGF_NONE));
 #ifdef DIAGEN_TEST
             return 1;
 #else
             return Comparision(opr,isCycleExist(lvalue),rvalue);
 #endif
         case Q::PASSENGER_OUT:
             p = Access.getElement(DGF_NONE);
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
 //#ifndef DIAGEN_TEST
             lvalue = getPassangerStats(*p,*(p + 1));
 //#endif
             rvalue = atoi(arg2);
             return Comparision(opr,lvalue,rvalue);
         case Q::PASSENGER_ARRIVAL:
             p = Access.getElement(DGF_NONE);
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
 //#ifndef DIAGEN_TEST
             lvalue = getPassangerFrom(*p);
 //#endif
             rvalue = atoi(arg2);
             return Comparision(opr,lvalue,rvalue);
         case Q::SPECTORS_TASK:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,getSpectorsTaskStatus(),rvalue);
         case Q::INFERNALS_TASK:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,getInfernalsTaskStatus(),rvalue);
         case Q::SPOBS_ALIVE:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,getSpobsState(),rvalue);
         case Q::THREALL_ALIVE:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,getThreallState(),rvalue);
         case Q::SUCCESS:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,(int)realRND(100) < uvsgetDGdata(DG_EXTERNS::LUCK),rvalue);
         case Q::FIASCO:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,(int)realRND(60) >= uvsgetDGdata(DG_EXTERNS::LUCK),rvalue);
         case Q::SPUMMY_DEATH:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,isSpummyDeath(),rvalue);
         case Q::KEY2GLORX_EXIST:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,aciWorldLinkExist(0,1,0),rvalue);
         case Q::KEY2ARKAZNOY_EXIST:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,aciWorldLinkExist(2,9,0),rvalue);
         case Q::KEY2BOOZEENA_EXIST:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,aciWorldLinkExist(2,5,0),rvalue);
         case Q::WAS_RUBEECATED:
             opr = Access.getElement(DGF_NONE);
             arg2 = Access.getElement(DGF_NONE);
             rvalue = atoi(arg2);
             return Comparision(opr,wasRubeecated,rvalue);
         }
     return 0;
 }
References XErrorHandler::Abort(), Access, ArgData, Q::COMING, Comparision(), Q::DATA, DGF_NONE, DG_EXTERNS::ELR_TOTAL, ErrH, XBuffer::GetBuf(), dgFile::getElement(), getPreviousCycle(), getWorldVisitStats(), DG_EXTERNS::KER_TOTAL, owner, DG_EXTERNS::PIP_TOTAL, Query, Q::SINGLERAND, Q::TRU, uvsgetDGdata(), Q::VISITE, Q::VISITW, XERR_USER, and DG_EXTERNS::ZYK_TOTAL.
Referenced by expressACCESS().
doCMD()
int dgCell::doCMD (int startup = 1)
 {
     dgFile* dgf = startup ? &StartCMD : &PostCMD;
 //#ifndef DIAGEN_TEST
     int aciCurCredits;
 //#endif
     dgf -> reset();
     char* p = dgf -> getElement(DGF_NONE,1);
     int i;
     int ret = 0;
     while(p){
         i = 0; do if(!strcmp(p,CmdData[i].name)) break;
         while(CmdData[++i].name);
         if(!CmdData[i].name) ErrH.Abort("Unknown CMD",XERR_USER,-1,p);
 #ifdef DIAGEN_TEST
         if(!checkStatus) std::cout << "   [DOING]: " << CmdData[i].name << "\n";
 #endif
         if(checkStatus){
             if(CmdData[i].id == CMD::ABORT)
                 dgAbortStatus = 1;
             }
         else
             switch(CmdData[i].id){
                 case CMD::CONTINUE:
                     ret++;
                     break;
                 case CMD::CLEAR:
                     ClearStatus = 1;
                     break;
                 case CMD::EPROMOTION:
                     owner -> owner -> eStatus++;
                     owner -> updateLevel();
                     break;
                 case CMD::BPROMOTION:
                     owner -> owner -> bStatus++;
                     owner -> updateLevel();
                     break;
                 case CMD::SPROMOTION:
                     owner -> owner -> sStatus++;
                     owner -> updateLevel();
                     break;
                 case CMD::BDEGRADATION:
                     if(owner -> owner -> bStatus){
                         owner -> owner -> bStatus--;
 //#ifndef DIAGEN_TEST
                         uvsLuckChange(-15);
 //#endif
                         }
                     owner -> updateLevel();
 //#ifndef DIAGEN_TEST
                     GamerResult.game_ker_result = 0;
                     GamerResult.game_pip_result = 0;
 //#endif
                     break;
                 case CMD::MAKE_WEEZYK:
                     owner -> owner -> zStatus = 2;
                     break;
                 case CMD::REGISTER_WEEZYK:
                     owner -> owner -> zStatus = 1;
                     owner -> updateLevel();
                     break;
                 case CMD::COMINGOZERO:
                     owner -> owner -> seekR("O",1) -> comingCounter = 0;
                     break;
                 case CMD::RUBEECATION:
                     wasRubeecated = 1;
                     break;
 //#ifndef DIAGEN_TEST
                 case CMD::ABORT:
                     dg_SendEvent(AML_KICK_OUT_FROM_ESCAVE);
                     eventOUT = 1;
                     break;
                 case CMD::QUIT:
                     dg_SendEvent(AML_ABORT_ESCAVE_SESSION);
                     eventOUT = 1;
                     break;
                 case CMD::BLOCK:
                     dg_SendEvent(AML_BLOCK_SHOP);
                     break;
                 case CMD::UNBLOCK:
                     dg_SendEvent(AML_UNBLOCK_SHOP);
                     break;
                 case CMD::FURY_LEVEL_INCREASE:
                     IncFuryFactor();
                     break;
                 case CMD::FURY_LEVEL_DECREASE:
                     DecFuryFactor();
                     break;
                 case CMD::ELR_WAITING_DECREASE:
                     RACE_WAIT = 5*RACE_WAIT/6;
                     break;
                 case CMD::ELP_PRIZE_GIFT:
                     aciCurCredits = aciGetCurCredits();
                     aciCurCredits += 3000;
                     aciUpdateCurCredits(aciCurCredits);
                     break;
                 case CMD::BBR_PRIZE_GIFT:
                     aciCurCredits = aciGetCurCredits();
                     aciCurCredits += 5000;
                     aciUpdateCurCredits(aciCurCredits);
                     break;
                 case CMD::PENALTY1000:
                     aciCurCredits = aciGetCurCredits();
                     aciCurCredits -= 1000;
                     if(aciCurCredits < 0) aciCurCredits = 0;
                     aciUpdateCurCredits(aciCurCredits);
                     break;
                 case CMD::PENALTY10000:
                     aciCurCredits = aciGetCurCredits();
                     aciCurCredits -= 10000;
                     if(aciCurCredits < 0) aciCurCredits = 0;
                     aciUpdateCurCredits(aciCurCredits);
                     break;
                 case CMD::KEY2GLORX_GIFT:
                     aciOpenWorldLink(0,1);
                     break;
                 case CMD::KEY2NECROSS_GIFT:
                     aciOpenWorldLink(1,2);
                     break;
                 case CMD::KEY2XPLO_GIFT:
                     aciOpenWorldLink(1,3);
                     break;
                 case CMD::KEY2WEEXOW_GIFT:
                     aciOpenWorldLink(0,6);
                     break;
                 case CMD::KEY2BOOZEENA_GIFT:
                     aciOpenWorldLink(2,5);
                     break;
                 case CMD::KEY2KHOX_GIFT:
                     aciOpenWorldLink(1,4);
                     break;
                 case CMD::KEY2ARKAZNOY_GIFT:
                     aciOpenWorldLink(2,9);
                     break;
                 case CMD::KEY2THREALL_GIFT:
                     aciOpenWorldLink(3,8);
                     break;
                 case CMD::EXPROPRIATION:
                     dg_SendEvent(AML_EXPROPRIATION);
                     break;
                 case CMD::ZERO_CASH:
                     aciCurCredits = aciGetCurCredits();
                     if(aciCurCredits > 600) aciCurCredits = 600;
                     aciUpdateCurCredits(aciCurCredits);
                     break;
                 case CMD::LAMPASSOTHE_END:
                     dg_SendEvent(AML_LAMPASSO_THEEND);
                     break;
                 case CMD::TRANSITION2V:
                     uvsSetTownName("VigBoo");
                     break;
                 case CMD::TRANSITION2L:
                     uvsSetTownName("Lampasso");
                     break;
                 case CMD::TRANSITION2O:
                     uvsSetTownName("Ogorod");
                     break;
                 case CMD::TRANSITION2B:
                     uvsSetTownName("B-Zone");
                     break;
                 case CMD::CHANGE2RAFFA:
                     dg_SendEvent(AML_CHANGE_TO_RAFFA);
                     break;
                 case CMD::ACCEPT_RUBBOX:
                     dg_SendEvent(AML_ACCEPT_RUBBOX);
                     break;
                 case CMD::ADD_RUBBOX:
                     dg_SendEvent(AML_ADD_RUBBOX);
                     break;
                 case CMD::ZERO_KERRATING:
                     GamerResult.game_ker_result = 0;
                     break;
                 case CMD::ZERO_PIPRATING:
                     GamerResult.game_pip_result = 0;
                     break;
                 case CMD::ADD_PROTRACTORKILL:
                     addInfernalsKill2Protractor();
                     break;
                 case CMD::ADD_MESSIAHKILL:
                     addSpectorsKill2Messiah();
                     break;
                 case CMD::OPEN_H00:
                     OpenCrypt(0,0);
                     break;
                 case CMD::OPEN_H01:
                     OpenCrypt(0,1);
                     break;
                 case CMD::OPEN_H10:
                     OpenCrypt(1,0);
                     break;
                 case CMD::OPEN_H11:
                     OpenCrypt(1,1);
                     break;
                 case CMD::ZERO_BOORAWCHICK:
                     uvsBoorawchickZero();
                     break;
                 case CMD::ZERO_ARKAZNOY:
                     WorldTable[9] -> GamerVisit = 0;
                     break;
 //#endif
                 }
         p = dgf -> getElement(DGF_NONE,1);
         }
     return ret;
 }
References XErrorHandler::Abort(), CmdData, DGF_NONE, ErrH, PostCMD, StartCMD, and XERR_USER.
expressACCESS()
int dgCell::expressACCESS (int endreq, char *& p, int & uplogic)
 {
     if(endreq) p = Access.getElement(DGF_NONE);
     int logic = 1;
     int result = analyzeACCESS(p),r;
     p = Access.getElement(DGF_NONE,1);
     while(p){
         if(!strcmp(p,")")){
             if(!endreq)
                 ErrH.Abort("Unexpected ')'");
             p = Access.getElement(DGF_NONE,1);
             return result;
             }
         else if(!strcmp(p,"(")){
             if(endreq)  ErrH.Abort("Unexpected '('");
             p = Access.getElement(DGF_NONE);
             uplogic = logic;
             return result;
             }
         else if(!strcasecmp(p,"AND")){ logic = 1; p = Access.getElement(DGF_NONE); }
         else if(!strcasecmp(p,"OR")){ logic = 0; p = Access.getElement(DGF_NONE); }
         else {
             r = analyzeACCESS(p);
             result = logic ? (result && r) : (result || r);
             p = Access.getElement(DGF_NONE,1);
             }
         }
     if(endreq) ErrH.Abort("Expected ')' missing");
     return result;
 }
References XErrorHandler::Abort(), Access, analyzeACCESS(), DGF_NONE, ErrH, and dgFile::getElement().
Referenced by isACCESS().
isACCESS()
int dgCell::isACCESS (void)
 {
     Access.reset();
     char* p = Access.getElement(DGF_NONE);
     int result = -1,r;
     int logic = 1;
     while(p){
         if(!strcmp(p,"(")){
             r = expressACCESS(1,p,logic);
             if(result != -1) result = logic ? (result && r) : (result || r);
             else result = r;
             }
         else if(!strcasecmp(p,"AND")){ logic = 1; p = Access.getElement(DGF_NONE); }
         else if(!strcasecmp(p,"OR")){ logic = 0; p = Access.getElement(DGF_NONE); }
         else{
             r = expressACCESS(0,p,logic);
             if(result != -1) result = logic ? (result && r) : (result || r);
             else result = r;
             }
         }
     return result;
 }
References Access, DGF_NONE, expressACCESS(), dgFile::getElement(), and dgFile::reset().
read()
void dgCell::read (dgFile * dgf)
 {
     x = atoi(dgf -> getElement(DGF_NONE));
     y = atoi(dgf -> getElement(DGF_NONE));
     char* p = dgf -> getElement(DGF_NONE);
     if(*p != ' ') Name = p;
     Type = atoi(dgf -> getElement(DGF_NONE));
     isWaiting = atoi(dgf -> getElement(DGF_NONE));
     isLooping = atoi(dgf -> getElement(DGF_NONE));
     p = dgf -> getElement(DGF_NONE); if(*p != ' ') { Access.load(p,strlen(p)); }
     p = dgf -> getElement(DGF_NONE); if(*p != ' ') { PostCMD.load(p,strlen(p)); }
     p = dgf -> getElement(DGF_NONE); if(*p != ' ') { StartCMD.load(p,strlen(p)); }
 }
References Access, DGF_NONE, isLooping, isWaiting, dgFile::load(), Name, PostCMD, StartCMD, Type, x, and y.
Member Data Documentation
Access
dgFile dgCell::Access
Referenced by analyzeACCESS(), expressACCESS(), isACCESS(), and read().
isLooping
int dgCell::isLooping
Referenced by dgCell(), and read().
isWaiting
int dgCell::isWaiting
Referenced by dgCell(), and read().
Name
char* dgCell::Name
Referenced by dgCell(), and read().
owner
dgRoom* dgCell::owner
Referenced by analyzeACCESS(), and dgCell().
PostCMD
dgFile dgCell::PostCMD
Referenced by doCMD(), and read().
StartCMD
dgFile dgCell::StartCMD
Referenced by doCMD(), and read().
Type
int dgCell::Type
Referenced by dgCell(), and read().
x
int dgCell::x
Referenced by read().
y
int dgCell::y
Referenced by read().
The documentation for this struct was generated from the following files:
src/uvs/diagen.h
src/uvs/diagen.cpp