Vangers: TargetParticleObject Struct Reference
TargetParticleObject Struct Reference
#include <effect.h>
Public Member Functions
void InitParicle (int num)
void Init (StorageType *s)
void Free (void)
void Quant (void)
void DrawQuant (void)
void AddVertex (const Vector &_vR, int _Color, int _Speed1, int _Speed2)
void AddVertex2 (const Vector &_vR, const Vector &_vT, int _Color, int _type=PARTICLE_DIRECT)
void CreateParticle (const Vector &_vTarget, int _LifeTime, char type)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
char TargetType
int NumParticle
int CurrParticle
int LifeTime
int Time
TargetParticleType * Data
Vector vTarget
int FadeTime
int FadeNum
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
AddVertex()
void TargetParticleObject::AddVertex (const Vector & _vR, int _Color, int _Speed1, int _Speed2)
 {
     TargetParticleType* p;
     Vector vCheck;
     int d;
     if(CurrParticle < NumParticle){
         vCheck = Vector(abs(getDistX(_vR.x,R_curr.x)),abs(getDistY(_vR.y,R_curr.y)),0);
         if(vCheck.x > vCheck.y){
             if(vCheck.x > radius) radius = vCheck.x;
         }else{
             if(vCheck.y > radius) radius = vCheck.y;
         };
         p = &Data[CurrParticle];
         vCheck = _vR;
         cycleTor(vCheck.x,vCheck.y);
         p->type = PARTICLE_DIRECT;
         p->Color = _Color;
         p->vR.x = vCheck.x << 8;
         p->vR.y = vCheck.y << 8;
         p->vR.z = vCheck.z << 8;
         vCheck.x = getDistX(R_curr.x,vCheck.x);
         vCheck.y = getDistY(R_curr.y,vCheck.y);
         vCheck.z = R_curr.z - vCheck.z;
         d = vCheck.vabs();
         if(d){
             vCheck.x = _Speed1 * vCheck.x / d;
             vCheck.y = _Speed1 * vCheck.y / d;
             p->vD.x = vCheck.x + vCheck.y;
             p->vD.y = vCheck.y - vCheck.x;
         }else p->vD = Vector(0,0,0);
         p->vD.z = (vCheck.z << 8) / LifeTime;
         p->s = _Speed2;
         p->vT = vTarget;
         p->pDist = d;
         CurrParticle++;
     };
 };
References TargetParticleType::Color, CurrParticle, cycleTor(), Data, getDistX(), getDistY(), LifeTime, NumParticle, PARTICLE_DIRECT, TargetParticleType::pDist, GeneralObject::R_curr, BaseObject::radius, TargetParticleType::s, TargetParticleType::type, Vector::vabs(), TargetParticleType::vD, TargetParticleType::vR, TargetParticleType::vT, vTarget, Vector::x, Vector::y, and Vector::z.
Referenced by VangerUnit::CreateParticleRotor().
AddVertex2()
void TargetParticleObject::AddVertex2 (const Vector & _vR, const Vector & _vT, int _Color, int _type = PARTICLE_DIRECT)
 {
     TargetParticleType* p;
     Vector vCheck;
     if(CurrParticle < NumParticle){
         vCheck = Vector(abs(getDistX(_vR.x,R_curr.x)),abs(getDistY(_vR.y,R_curr.y)),0);
         if(vCheck.x > vCheck.y){
             if(vCheck.x > radius) radius = vCheck.x;
         }else{
             if(vCheck.y > radius) radius = vCheck.y;
         };
         p = &Data[CurrParticle];
         vCheck = _vR;
         cycleTor(vCheck.x,vCheck.y);
         p->Color = _Color;
         p->type = _type;
         p->LifeTime = LifeTime;
         if (_type){
             p->vT.x = vCheck.x << 8;
             p->vT.y = vCheck.y << 8;
             p->vT.z = vCheck.z << 8;
         } else {
             p->vR.x = vCheck.x << 8;
             p->vR.y = vCheck.y << 8;
             p->vR.z = vCheck.z << 8;
             p->vD.x = vCheck.x << 8;
             p->vD.y = vCheck.y << 8;
             p->vD.z = vCheck.z << 8;
         }
         vCheck = _vT;
         cycleTor(vCheck.x,vCheck.y);
         if ( _type){
             p->vR.x = vCheck.x << 8;
             p->vR.y = vCheck.y << 8;
             p->vR.z = vCheck.z << 8;
             p->vD.x = vCheck.x << 8;
             p->vD.y = vCheck.y << 8;
             p->vD.z = vCheck.z << 8;
         } else {
             p->vT.x = vCheck.x << 8;
             p->vT.y = vCheck.y << 8;
             p->vT.z = vCheck.z << 8;
         }
         p->pDist = LifeTime;
         if ( _type ) {
             p->pDist >>= 1;
             p->LifeTime >>= 1;
         }
         p->s =((_vR.z  - _vT.z) << 8) / p->pDist;
         CurrParticle++;
     };
 };
References TargetParticleType::Color, CurrParticle, cycleTor(), Data, getDistX(), getDistY(), TargetParticleType::LifeTime, LifeTime, NumParticle, TargetParticleType::pDist, GeneralObject::R_curr, BaseObject::radius, TargetParticleType::s, TargetParticleType::type, TargetParticleType::vD, TargetParticleType::vR, TargetParticleType::vT, Vector::x, Vector::y, and Vector::z.
Referenced by VangerUnit::CreateParticleMechos().
CreateParticle()
void TargetParticleObject::CreateParticle (const Vector & _vTarget, int _LifeTime, char type)
 {
     Time = 0;
     CurrParticle = 0;
     LifeTime = _LifeTime;
     R_curr = _vTarget;
     cycleTor(R_curr.x,R_curr.y);
     vTarget.x = R_curr.x << 8;
     vTarget.y = R_curr.y << 8;
     vTarget.z = R_curr.z << 8;
     radius = 0;
     Status = 0;
     MapLevel = 1;
     TargetType = type;
     FadeTime = FadeNum = 0;
 };
References CurrParticle, cycleTor(), FadeNum, FadeTime, LifeTime, BaseObject::MapLevel, GeneralObject::R_curr, BaseObject::radius, GeneralObject::Status, TargetType, Time, vTarget, Vector::x, Vector::y, and Vector::z.
Referenced by VangerUnit::CreateParticleMechos(), and VangerUnit::CreateParticleRotor().
DrawQuant()
void TargetParticleObject::DrawQuant (void)
 {
     int i;
     TargetParticleType* p;
     if(TargetType){
         if(AdvancedView) for(i = 0,p = Data;i < CurrParticle;i++,p++) p->aQuant();
         else for(i = 0,p = Data;i < CurrParticle;i++,p++) p->sQuant();
     }else{
         if(AdvancedView) for(i = 0,p = Data;i < CurrParticle;i++,p++) p->aQuant2();
         else for(i = 0,p = Data;i < CurrParticle;i++,p++) p->sQuant2();
     };
 };
References AdvancedView, TargetParticleType::aQuant(), TargetParticleType::aQuant2(), CurrParticle, Data, TargetParticleType::sQuant(), TargetParticleType::sQuant2(), and TargetType.
Free()
void TargetParticleObject::Free (void)
 {
     delete[] Data;
 };
References Data.
Init()
void TargetParticleObject::Init (StorageType * s)
 {
     BaseObject::Init(s);
     ID = ID_EXPLOSION;
 };
References GeneralObject::ID, and ID_EXPLOSION.
InitParicle()
void TargetParticleObject::InitParicle (int num)
 {
     CurrParticle = 0;
     NumParticle = num;
     Data = new TargetParticleType[num];
     FadeTime = FadeNum = 0;
 };
References CurrParticle, Data, FadeNum, FadeTime, and NumParticle.
Quant()
void TargetParticleObject::Quant (void)
 {
     if(DepthShow){
         int xt = getDistX(R_curr.x,ViewX);
         int yy = getDistY(R_curr.y,ViewY);
         int zz = round(A_g2s.a[6]*xt + A_g2s.a[7]*yy) - R_curr.z + ViewZ;
         int xx = round(A_g2s.a[0]*xt + A_g2s.a[1]*yy);
         yy = round(A_g2s.a[3]*xt + A_g2s.a[4]*yy);
         if(zz < -radius || abs(xx) > zz*TurnSideX/ViewZ + radius*2 ||  abs(yy) > zz*TurnSideY/ViewZ + radius*2) Visibility = UNVISIBLE;
         else Visibility = VISIBLE;
     }else{
         if(abs(getDistX(R_curr.x,ViewX)) - (radius << 1) < TurnSideX && abs(getDistY(R_curr.y,ViewY)) -  (radius << 1) < TurnSideY) Visibility = VISIBLE;
         else Visibility = UNVISIBLE;
     };
     if(TargetType){
         if(Time == 0){
             FadeTime = LifeTime - TARGET_PARTICLE_FADE_TIME;
             FadeNum = CurrParticle / TARGET_PARTICLE_FADE_TIME;
         }else{
             if(Time >= FadeTime)
                 CurrParticle -= FadeNum;
         };
     };
     if(++Time > LifeTime)   Status |= SOBJ_DISCONNECT;
 };
References DBM::a, A_g2s, CurrParticle, DepthShow, FadeNum, FadeTime, getDistX(), getDistY(), LifeTime, GeneralObject::R_curr, BaseObject::radius, round(), SOBJ_DISCONNECT, GeneralObject::Status, TARGET_PARTICLE_FADE_TIME, TargetType, Time, TurnSideX, TurnSideY, UNVISIBLE, ViewX, ViewY, ViewZ, BaseObject::Visibility, VISIBLE, Vector::x, Vector::y, and Vector::z.
Member Data Documentation
CurrParticle
int TargetParticleObject::CurrParticle
Referenced by AddVertex(), AddVertex2(), CreateParticle(), DrawQuant(), InitParicle(), and Quant().
Data
TargetParticleType* TargetParticleObject::Data
Referenced by AddVertex(), AddVertex2(), DrawQuant(), Free(), and InitParicle().
FadeNum
int TargetParticleObject::FadeNum
Referenced by CreateParticle(), InitParicle(), and Quant().
FadeTime
int TargetParticleObject::FadeTime
Referenced by CreateParticle(), InitParicle(), and Quant().
LifeTime
int TargetParticleObject::LifeTime
Referenced by AddVertex(), AddVertex2(), CreateParticle(), and Quant().
NumParticle
int TargetParticleObject::NumParticle
Referenced by AddVertex(), AddVertex2(), VangerUnit::CreateParticleRotor(), and InitParicle().
TargetType
char TargetParticleObject::TargetType
Referenced by CreateParticle(), DrawQuant(), and Quant().
Time
int TargetParticleObject::Time
Referenced by CreateParticle(), and Quant().
vTarget
Vector TargetParticleObject::vTarget
Referenced by AddVertex(), and CreateParticle().
The documentation for this struct was generated from the following files:
src/units/effect.h
src/units/effect.cpp