Vangers: iKeyControls Struct Reference
iKeyControls Struct Reference
Public Member Functions
void init (void)
void reset (void)
void setFlag (int id, int fl)
void dropFlag (int id, int fl)
void clearFlag (int id)
void addCode (int id, int key, int num=0)
void removeCode (int id, int num=0)
void addDefaultCode (int id, int key, int num=0)
int getCode (int id, int num)
int GetID (int key)
int CheckID (int id, int key)
iKeyControls (void)
Public Attributes
int * keyCodes
int * defaultCodes
int * flags
Detailed Description
Constructor & Destructor Documentation
iKeyControls()
iKeyControls::iKeyControls (void)
 {
     keyCodes = new int[iKEY_OBJECT_SIZE * iKEY_MAX_ID];
     defaultCodes = new int[iKEY_OBJECT_SIZE * iKEY_MAX_ID];
     flags = new int[iKEY_MAX_ID];
     memset(keyCodes,0,iKEY_OBJECT_SIZE * iKEY_MAX_ID * sizeof(int));
     memset(defaultCodes,0,iKEY_OBJECT_SIZE * iKEY_MAX_ID * sizeof(int));
     memset(flags,0,iKEY_MAX_ID * sizeof(int));
 }
References defaultCodes, flags, iKEY_MAX_ID, iKEY_OBJECT_SIZE, and keyCodes.
Member Function Documentation
addCode()
void iKeyControls::addCode (int id, int key, int num = 0)
 {
     keyCodes[id * iKEY_OBJECT_SIZE + num] = key;
 }
References iKEY_OBJECT_SIZE, key(), and keyCodes.
addDefaultCode()
void iKeyControls::addDefaultCode (int id, int key, int num = 0)
 {
     defaultCodes[id * iKEY_OBJECT_SIZE + num] = key;
 }
References defaultCodes, iKEY_OBJECT_SIZE, and key().
Referenced by init().
CheckID()
int iKeyControls::CheckID (int id, int key)
 {
     int i,index = iKEY_OBJECT_SIZE * id;
     for(i = 0; i < iKEY_OBJECT_SIZE; i ++){
         if(keyCodes[i + index] == key)
             return 1;
     }
     return 0;
 }
References iKEY_OBJECT_SIZE, key(), and keyCodes.
clearFlag()
void iKeyControls::clearFlag (int id) inline
 { flags[id] = 0; }
References flags.
dropFlag()
void iKeyControls::dropFlag (int id, int fl) inline
 { flags[id] &= ~fl; }
References flags.
getCode()
int iKeyControls::getCode (int id, int num)
 {
     return keyCodes[id * iKEY_OBJECT_SIZE + num];
 }
References iKEY_OBJECT_SIZE, and keyCodes.
Referenced by iKeyPressed().
GetID()
int iKeyControls::GetID (int key)
 {
     int i,id = -1,sz = iKEY_OBJECT_SIZE * iKEY_MAX_ID;
     for(i = 0; i < sz; i ++){
         if(keyCodes[i] == key){
             id = i / iKEY_OBJECT_SIZE;
             return id;
         }
     }
     return id;
 }
References iKEY_MAX_ID, iKEY_OBJECT_SIZE, key(), and keyCodes.
init()
void iKeyControls::init (void)
 {
     // Movement
     addDefaultCode(iKEY_TURN_WHEELS_LEFT,SDL_SCANCODE_LEFT);
     addDefaultCode(iKEY_TURN_WHEELS_RIGHT,SDL_SCANCODE_RIGHT);
     addDefaultCode(iKEY_MOVE_FORWARD,SDL_SCANCODE_UP);
     addDefaultCode(iKEY_MOVE_BACKWARD,SDL_SCANCODE_DOWN);
     //addDefaultCode(iKEY_MOVE_BACKWARD,SDL_SCANCODE_KP_0,1);
     addDefaultCode(iKEY_ACCELERATION,SDL_SCANCODE_LSHIFT);
     addDefaultCode(iKEY_ACCELERATION,SDL_SCANCODE_RSHIFT,1);
 //  addDefaultCode(iKEY_ACTIVATE_KID,'A',1);
     addDefaultCode(iKEY_ACTIVATE_KID,SDL_SCANCODE_W);
 //  addDefaultCode(iKEY_ACTIVATE_KID,SDL_SCANCODE_SLASH,1);
     addDefaultCode(iKEY_HANDBRAKE,SDL_SCANCODE_Q);
     // Utility
     addDefaultCode(iKEY_OPEN,SDL_SCANCODE_SPACE);
     //addDefaultCode(iKEY_OPEN,VK_STICK_SWITCH_2,1);
     addDefaultCode(iKEY_INVENTORY,SDL_SCANCODE_RETURN);
     //addDefaultCode(iKEY_INVENTORY,VK_STICK_SWITCH_3,1);
     addDefaultCode(iKEY_TURN_OVER_LEFT,SDL_SCANCODE_A);
 //  addDefaultCode(iKEY_TURN_OVER_LEFT,SDL_SCANCODE_COMMA,1);
     addDefaultCode(iKEY_TURN_OVER_RIGHT,SDL_SCANCODE_D);
 //  addDefaultCode(iKEY_TURN_OVER_RIGHT,SDL_SCANCODE_PERIOD,1);
     addDefaultCode(iKEY_DEVICE_ON,SDL_SCANCODE_R);
     addDefaultCode(iKEY_DEVICE_ON,SDL_SCANCODE_PAGEUP,1);
     //addDefaultCode(iKEY_DEVICE_ON,VK_STICK_SWITCH_9,1);
     addDefaultCode(iKEY_DEVICE_OFF,SDL_SCANCODE_F);
     addDefaultCode(iKEY_DEVICE_OFF,SDL_SCANCODE_PAGEDOWN,1);
     //addDefaultCode(iKEY_DEVICE_OFF,VK_STICK_SWITCH_7,1);
     // Combat
     addDefaultCode(iKEY_FIRE_ALL_WEAPONS,SDL_SCANCODE_E);
     addDefaultCode(iKEY_FIRE_ALL_WEAPONS,SDL_SCANCODE_LCTRL, 1);
     addDefaultCode(iKEY_FIRE_WEAPON4,SDL_SCANCODE_4);
     addDefaultCode(iKEY_USE_GLUEK,SDL_SCANCODE_5);
     addDefaultCode(iKEY_FIRE_WEAPON1,SDL_SCANCODE_1);
     addDefaultCode(iKEY_FIRE_WEAPON2,SDL_SCANCODE_2);
     addDefaultCode(iKEY_FIRE_WEAPON3,SDL_SCANCODE_3);
     addDefaultCode(iKEY_USE_VECTOR, SDL_SCANCODE_V);
     addDefaultCode(iKEY_CHANGE_TARGET,SDL_SCANCODE_TAB);
     //addDefaultCode(iKEY_CHANGE_TARGET,VK_STICK_SWITCH_1,1);
     // Camera
     addDefaultCode(iKEY_FULLSCREEN,SDL_SCANCODE_F1);
     addDefaultCode(iKEY_ZOOM_OUT,SDL_SCANCODE_MINUS);
     addDefaultCode(iKEY_ZOOM_IN,SDL_SCANCODE_EQUALS);
     addDefaultCode(iKEY_ZOOM_STANDART,SDL_SCANCODE_0);
     addDefaultCode(iKEY_ROTATION,SDL_SCANCODE_F5);
     addDefaultCode(iKEY_AUTO_TILT,SDL_SCANCODE_F6);
     addDefaultCode(iKEY_AUTO_ZOOM,SDL_SCANCODE_F7);
     // Multiplayer and misc.
     addDefaultCode(iKEY_CHAT,SDL_SCANCODE_F3);
     addDefaultCode(iKEY_FRAG_INFO,SDL_SCANCODE_S);
     addDefaultCode(iKEY_SCREENSHOT,SDL_SCANCODE_F9);
     addDefaultCode(iKEY_SKIP_TEXT,SDL_SCANCODE_TAB);
 //  addDefaultCode(iKEY_EXIT,SDL_SCANCODE_F10);
 //  addDefaultCode(iKEY_REDUCE_VIEW,SDL_SCANCODE_F2);
 //  addDefaultCode(iKEY_ENLARGE_VIEW,SDL_SCANCODE_F3);
     // Not found in the available controls settings
 //    addDefaultCode(iKEY_VERTICAL_THRUST,'Z');
     addDefaultCode(iKEY_JOYSTICK_SWITCH,VK_BUTTON_1);
     setFlag(iKEY_JOYSTICK_SWITCH,iKEY_NO_RESET);
     reset();
 }
References addDefaultCode(), iKEY_ACCELERATION, iKEY_ACTIVATE_KID, iKEY_AUTO_TILT, iKEY_AUTO_ZOOM, iKEY_CHANGE_TARGET, iKEY_CHAT, iKEY_DEVICE_OFF, iKEY_DEVICE_ON, iKEY_FIRE_ALL_WEAPONS, iKEY_FIRE_WEAPON1, iKEY_FIRE_WEAPON2, iKEY_FIRE_WEAPON3, iKEY_FIRE_WEAPON4, iKEY_FRAG_INFO, iKEY_FULLSCREEN, iKEY_HANDBRAKE, iKEY_INVENTORY, iKEY_JOYSTICK_SWITCH, iKEY_MOVE_BACKWARD, iKEY_MOVE_FORWARD, iKEY_NO_RESET, iKEY_OPEN, iKEY_ROTATION, iKEY_SCREENSHOT, iKEY_SKIP_TEXT, iKEY_TURN_OVER_LEFT, iKEY_TURN_OVER_RIGHT, iKEY_TURN_WHEELS_LEFT, iKEY_TURN_WHEELS_RIGHT, iKEY_USE_GLUEK, iKEY_USE_VECTOR, iKEY_ZOOM_IN, iKEY_ZOOM_OUT, iKEY_ZOOM_STANDART, reset(), setFlag(), and VK_BUTTON_1.
removeCode()
void iKeyControls::removeCode (int id, int num = 0)
 {
     keyCodes[id * iKEY_OBJECT_SIZE + num] = 0;
 }
References iKEY_OBJECT_SIZE, and keyCodes.
reset()
void iKeyControls::reset (void)
 {
     int i;
     if(iKeyFirstInit){
         for(i = 0; i < iKEY_MAX_ID; i ++){
             if(!(flags[i] & iKEY_NO_RESET)){
                 memcpy(keyCodes + i * iKEY_OBJECT_SIZE,defaultCodes + i * iKEY_OBJECT_SIZE,iKEY_OBJECT_SIZE * sizeof(int));
             }
         }
     }
     else {
         memcpy(keyCodes,defaultCodes,iKEY_OBJECT_SIZE * iKEY_MAX_ID * sizeof(int));
         iKeyFirstInit = 1;
     }
 }
References defaultCodes, flags, iKEY_MAX_ID, iKEY_NO_RESET, iKEY_OBJECT_SIZE, iKeyFirstInit, and keyCodes.
Referenced by init().
setFlag()
void iKeyControls::setFlag (int id, int fl) inline
 { flags[id] |= fl; }
References flags.
Referenced by init().
Member Data Documentation
defaultCodes
int* iKeyControls::defaultCodes
Referenced by addDefaultCode(), iKeyControls(), and reset().
flags
int* iKeyControls::flags
Referenced by clearFlag(), dropFlag(), iKeyControls(), reset(), and setFlag().
keyCodes
int* iKeyControls::keyCodes
Referenced by addCode(), CheckID(), getCode(), GetID(), iKeyControls(), removeCode(), and reset().
The documentation for this struct was generated from the following file:
src/iscreen/controls.cpp