Vangers: HordeSourceList Struct Reference
HordeSourceList Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void Quant (void)
HordeSource * CreateSource (void)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Free (void)
virtual void NetEvent (int type, int id)
virtual void FreeUnit (GeneralObject *p)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Additional Inherited Members
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
CreateSource()
HordeSource * HordeSourceList::CreateSource (void)
 {
     HordeSource* p;
     p = new HordeSource;
     p->Init();
     ConnectTypeList(p);
     return p;
 };
References UnitBaseListType::ConnectTypeList().
Referenced by Init().
Init()
void HordeSourceList::Init (void) virtual
Reimplemented from UnitListType.
 {
     int i,max;
     UnitBaseListType::Init();
 //zmod 1.21
     if(NetworkON){
         double kmax = (1.+zMod_flood_level_delta)/2;
         switch(CurrentWorld){
             case WORLD_FOSTRAL:
             case WORLD_GLORX:
             case WORLD_NECROSS:
                 max = MAX_HORDE_OBJECT;
                 break;
             default:
                 max = MAX_HORDE_SOURCE_OBJECT / 2;
         };
         max = (int)((double)max * kmax);
         for(i = 0;i < max;i++)
             (CreateSource())->CreateSource(Vector(NetRnd.Get(map_size_x),NetRnd.Get(map_size_y),270),ModelD.FindModel("Horde"),20,60);
     }else{
         switch(CurrentWorld){
             case WORLD_FOSTRAL:
             case WORLD_GLORX:
             case WORLD_NECROSS:
             case WORLD_XPLO:
                 for(i = 0;i < MAX_HORDE_SOURCE_OBJECT;i++)
                     (CreateSource())->CreateSource(Vector(RND(map_size_x),RND(map_size_y),270),ModelD.FindModel("Horde"),20,60);
                 break;
         };
     };
 };
References CreateSource(), CurrentWorld, ModelDispatcher::FindModel(), NetRndType::Get(), UnitListType::Init(), map_size_x, map_size_y, max(), MAX_HORDE_OBJECT, MAX_HORDE_SOURCE_OBJECT, ModelD, NetRnd, NetworkON, RND(), WORLD_FOSTRAL, WORLD_GLORX, WORLD_NECROSS, WORLD_XPLO, and zMod_flood_level_delta.
Referenced by GeneralSystemOpen().
Quant()
void HordeSourceList::Quant (void) virtual
Reimplemented from UnitListType.
 {
     GeneralObject* p;
     GeneralObject* pp;
     p = Tail;
     while(p){
         p->Quant();
         p = p->NextTypeList;
     };
     p = Tail;
     while(p){
         pp = p->NextTypeList;
         if(p->Status & SOBJ_DISCONNECT){
             (HordeD.CreateHorde())->CreateHorde(p->R_curr,((HordeSource*)(p))->HordeRadius,((HordeSource*)(p))->zHorde,400,NULL);
             FreeUnit(p);
         };
         p = pp;
     };
 };
References HordeList::CreateHorde(), UnitListType::FreeUnit(), HordeD, GeneralObject::NextTypeList, NULL, GeneralObject::R_curr, SOBJ_DISCONNECT, GeneralObject::Status, and UnitListType::Tail.
Referenced by GameObjectDispatcher::Quant().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp