Vangers: DoorEngine Struct Reference
DoorEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Close (void)
void Touch (GeneralObject *obj, SensorDataType *p)
void Quant (void)
void OpenDoor (void)
void CloseDoor (void)
void OpenDoor (int t)
void CloseDoor (int t)
Public Member Functions inherited from LocationEngine
virtual void Link (void)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
int NumSensor
SensorDataType ** SensorLink
int TouchFlag
int ProcessFlag
int Time
int LockFlag
int Level
int NumTouchObject
int Luck
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Close()
void DoorEngine::Close (void) virtual
Reimplemented from LocationEngine.
 {
     delete[] SensorLink;
 };
References SensorLink.
CloseDoor() [1/2]
void DoorEngine::CloseDoor (int t)
 {
     if(!Enable || !MLLink) return;
     Time = t;
     Mode = EngineModeList::WAIT;
     ProcessFlag = 1;
     if(!MLLink->frozen){
         MLLink->goKeyPhase(DeactivePhase);
         SoundEvent();
     };
 /*  if(NetworkON){
         NetMode = Mode;
         NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
         NETWORK_OUT_STREAM < (char)(NetMode);
         NETWORK_OUT_STREAM.end_body();
     };*/
 };
References LocationEngine::DeactivePhase, LocationEngine::Enable, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, ProcessFlag, LocationEngine::SoundEvent(), Time, and EngineModeList::WAIT.
CloseDoor() [2/2]
void DoorEngine::CloseDoor (void)
 {
     if(!Enable || !MLLink) return;
     Time = DeactiveTime;
     Mode = EngineModeList::WAIT;
     ProcessFlag = 1;
     if(!MLLink->frozen){
         MLLink->goKeyPhase(DeactivePhase);
         SoundEvent();
     };
 /*  if(NetworkON){
         NetMode = Mode;
         NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
         NETWORK_OUT_STREAM < (char)(NetMode);
         NETWORK_OUT_STREAM.end_body();
     };*/
 };
References LocationEngine::DeactivePhase, LocationEngine::DeactiveTime, LocationEngine::Enable, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, ProcessFlag, LocationEngine::SoundEvent(), Time, and EngineModeList::WAIT.
Referenced by VangerUnit::AutomaticTouchSensor(), Quant(), ElevatorEngine::Quant(), ImpulseEscave::Quant(), and VangerUnit::TouchSensor().
Open()
void DoorEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     char* n;
     int i;
     LocationEngine::Open(in);
     in.search_name("NumSensorLink");
     NumSensor = in.get_int();
     SensorLink = new SensorDataType*[NumSensor];
     for(i = 0;i < NumSensor;i++){
         in.search_name("SensorName");
         n = in.get_name();
         SensorLink[i] = NULL;
         SensorLink[i] = FindSensor(n);
         if(!SensorLink[i])
             ErrH.Abort("Bad Find Sensor");
         SensorLink[i]->Enable = 1;
         SensorLink[i]->Owner = this;
     };
     in.search_name("LockFlag");
     LockFlag = in.get_int();
     in.search_name("Luck");
     Luck = in.get_int();
     if(NetworkON) Luck = 0;
     TouchFlag = 0;
     Type = EngineTypeList::DOOR;
     Mode = EngineModeList::WAIT;
     Time = 0;
     ProcessFlag = 0;
 //  MLLink->setStaticPhase(DeactivePhase);
     MLLink->goKeyPhase(DeactivePhase);
     Level = 0;
     NumTouchObject = 0;
 };
References XErrorHandler::Abort(), LocationEngine::DeactivePhase, EngineTypeList::DOOR, StaticObject::Enable, ErrH, FindSensor(), Parser::get_int(), Parser::get_name(), MobileLocation::goKeyPhase(), Level, LockFlag, Luck, LocationEngine::MLLink, LocationEngine::Mode, NetworkON, NULL, NumSensor, NumTouchObject, LocationEngine::Open(), SensorDataType::Owner, ProcessFlag, Parser::search_name(), SensorLink, Time, TouchFlag, LocationEngine::Type, and EngineModeList::WAIT.
OpenDoor() [1/2]
void DoorEngine::OpenDoor (int t)
 {
     if(!Enable || !MLLink) return;
     Time = t;
     Mode = EngineModeList::OPEN;
     ProcessFlag = 1;
     if(!MLLink->frozen){
         MLLink->goKeyPhase(ActivePhase);
         SoundEvent();
     };
 /*  if(NetworkON){
         NetMode = Mode;
         NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
         NETWORK_OUT_STREAM < (char)(NetMode);
         NETWORK_OUT_STREAM.end_body();
     };*/
 };
References LocationEngine::ActivePhase, LocationEngine::Enable, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, EngineModeList::OPEN, ProcessFlag, LocationEngine::SoundEvent(), and Time.
OpenDoor() [2/2]
void DoorEngine::OpenDoor (void)
 {
     if(!Enable || !MLLink) return;
     Time = ActiveTime;
     Mode = EngineModeList::OPEN;
     ProcessFlag = 1;
     if(!MLLink->frozen){
         MLLink->goKeyPhase(ActivePhase);
         SoundEvent();
     };
 /*  if(NetworkON){
         NetMode = Mode;
         NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
         NETWORK_OUT_STREAM < (char)(NetMode);
         NETWORK_OUT_STREAM.end_body();
     };*/
 };
References LocationEngine::ActivePhase, LocationEngine::ActiveTime, LocationEngine::Enable, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, EngineModeList::OPEN, ProcessFlag, LocationEngine::SoundEvent(), and Time.
Referenced by ElevatorEngine::Active(), ImpulseEscave::Active(), ImpulseSpot::Active(), VangerUnit::AutomaticTouchSensor(), Quant(), and VangerUnit::TouchSensor().
Quant()
void DoorEngine::Quant (void) virtual
Reimplemented from LocationEngine.
 {
     char* ThreallText;
     if(!MLLink) return;
     if(!MLLink->frozen){
         HideFlag = 0;
         NumTouchObject = TouchFlag;
         if(MLLink->isGoFinish()){
             ProcessFlag = 0;
             if(NetworkON && Mode != NetMode){
                 if(UpdateFlag){
                     if(NetMode == EngineModeList::OPEN) OpenDoor(0);
                     else CloseDoor(0);
                     UpdateFlag = 0;
                     return;
                 }else{
                     NetMode = Mode;
                     NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
                     NETWORK_OUT_STREAM < (char)(NetMode);
                     NETWORK_OUT_STREAM.end_body();
                 };
             };
             if(Time){
                 Time--;
                 TouchFlag = 0;
             }else{
                 if(TouchFlag){
                     if(Mode != EngineModeList::OPEN && !(LockFlag & DOOR_OPEN_LOCK)){
                         if(CurrentWorld == WORLD_THREALL && !strcmp(MLLink->name,"MMMM")){
 //                          aciSendEvent2actint(ACI_SHOW_TEXT,NULL);
                             dgInThreall();
                             ThreallText = dgGetThreallPhrase();
                             if(ThreallText) aciPrepareText(ThreallText);
                             ThreallMessageProcess = 1;
                         };
                         Mode = EngineModeList::OPEN;
                         MLLink->goKeyPhase(ActivePhase);
                         ProcessFlag = 1;
                         SoundEvent();
                     };
                     TouchFlag = 0;
                 }else{
                     if(Mode != EngineModeList::WAIT && !(LockFlag & DOOR_CLOSE_LOCK)){
                         if(CurrentWorld == WORLD_THREALL && !strcmp(MLLink->name,"MMMM")){
                             aciSendEvent2actint(ACI_HIDE_TEXT,NULL);
                             dgOutThreall();
                             ThreallMessageProcess = 0;
                         };
                         Mode = EngineModeList::WAIT;
                         MLLink->goKeyPhase(DeactivePhase);
                         ProcessFlag = 1;
                         SoundEvent();
                     };
                 };
             };
         };
     }else{
         if(Mode != EngineModeList::WAIT)
             MLLink->goKeyPhase(DeactivePhase);
         Mode = EngineModeList::WAIT;
         Time = 0;
         ProcessFlag = 0;
         NumTouchObject = 0;
         HideFlag = 1;
     };
 };
References ACI_HIDE_TEXT, aciPrepareText(), aciSendEvent2actint(), LocationEngine::ActivePhase, CloseDoor(), CurrentWorld, LocationEngine::DeactivePhase, dgGetThreallPhrase(), dgInThreall(), dgOutThreall(), DOOR_CLOSE_LOCK, DOOR_OPEN_LOCK, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::HideFlag, MobileLocation::isGoFinish(), LockFlag, LocationEngine::MLLink, LocationEngine::Mode, MobileLocation::name, LocationEngine::NetID, LocationEngine::NetMode, NETWORK_OUT_STREAM, NetworkON, NULL, NumTouchObject, EngineModeList::OPEN, OpenDoor(), ProcessFlag, LocationEngine::R_curr, LocationEngine::SoundEvent(), ThreallMessageProcess, Time, TouchFlag, LocationEngine::UpdateFlag, EngineModeList::WAIT, WORLD_THREALL, Vector::x, and Vector::y.
Touch()
void DoorEngine::Touch (GeneralObject * obj, SensorDataType * p) virtual
Reimplemented from LocationEngine.
 {
     if(!Enable || !MLLink) return;
     if(!MLLink->frozen)
         TouchFlag++;
 };
References LocationEngine::Enable, MobileLocation::frozen, LocationEngine::MLLink, and TouchFlag.
Member Data Documentation
Level
int DoorEngine::Level
Referenced by Open().
LockFlag
int DoorEngine::LockFlag
Referenced by Open(), and Quant().
Luck
int DoorEngine::Luck
Referenced by Open(), and VangerUnit::TouchSensor().
NumSensor
int DoorEngine::NumSensor
Referenced by Open(), and VangerUnit::TouchSensor().
NumTouchObject
int DoorEngine::NumTouchObject
Referenced by Open(), Quant(), and ElevatorEngine::Quant().
ProcessFlag
int DoorEngine::ProcessFlag
Referenced by VangerUnit::AutomaticTouchSensor(), CloseDoor(), Open(), OpenDoor(), Quant(), ElevatorEngine::Quant(), EscaveEngine::Quant(), ImpulseEscave::Quant(), and ImpulseSpot::Quant().
SensorLink
SensorDataType** DoorEngine::SensorLink
Referenced by Close(), Open(), and VangerUnit::TouchSensor().
Time
int DoorEngine::Time
Referenced by CloseDoor(), Open(), OpenDoor(), and Quant().
TouchFlag
int DoorEngine::TouchFlag
Referenced by Open(), Quant(), and Touch().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp