Vangers: PalConstructor Struct Reference
PalConstructor Struct Reference
#include <hobj.h>
Public Member Functions
void Init (void)
void Free (void)
void Quant (void)
void Set (int mode, int time, uchar *p1=NULL, uchar *p2=NULL)
void Clear (PalPoint *p)
Public Attributes
PalPoint * pPrev
PalPoint * Tail
int PalEnable
Detailed Description
Member Function Documentation
Clear()
void PalConstructor::Clear (PalPoint * p)
 {
     if((!p->Prev) && (!p->Next)) Tail = NULL;
     else{
         if(p->Prev) p->Prev->Next = p->Next;
         else Tail = p->Next;
         if(p->Next) p->Next->Prev = p->Prev;
     };
 };
References PalPoint::Next, NULL, PalPoint::Prev, and Tail.
Referenced by Quant().
Free()
void PalConstructor::Free (void)
 {
     PalPoint* p;
     PalPoint* pp;
     p = Tail;
     while(p){
         pp = p->Next;
         delete p;
         p = pp;
     };
     Tail = NULL;
 };
References PalPoint::Next, NULL, and Tail.
Referenced by GeneralSystemClose().
Init()
void PalConstructor::Init (void)
 {
     Tail = NULL;
     pPrev = NULL;
     PalEnable = 1;
 };
References NULL, PalEnable, pPrev, and Tail.
Referenced by GeneralSystemOpen().
Quant()
void PalConstructor::Quant (void)
 {
     PalPoint* p;
     PalPoint* pp;
     int m;
     if(ActD.Active == NULL || uvsKronActive == 0)
         return;
     p = NULL;
     m = 0;
     pp = Tail;
     while(pp){
         if(pp->Mode > m){
             p = pp;
             m = pp->Mode;
         };
         pp = pp->Next;
     };
     if(p){
         if(pPrev != p && pPrev != NULL){
             if(p->Mode == CPAL_CHANGE_CYCLE)
                 p->Set(CPAL_RESTORE_CHANGE,p->Time);
             else
                 p->Set(p->Mode,p->Time);
         };
         pPrev = p;
         p->Quant();
         if(p->Time <= 0){
             Clear(p);
             delete p;
         };
     }else{
         pPrev = NULL;
         if(PalEnable && !palTr -> quant())
             pal_iter();
     };
 };
References ActD, ActionDispatcher::Active, Clear(), CPAL_CHANGE_CYCLE, CPAL_RESTORE_CHANGE, PalPoint::Mode, PalPoint::Next, NULL, pal_iter(), PalEnable, palTr, pPrev, PalPoint::Quant(), PalPoint::Set(), Tail, PalPoint::Time, and uvsKronActive.
Referenced by GameQuantRTO::Quant().
Set()
void PalConstructor::Set (int mode, int time, uchar * p1 = NULL, uchar * p2 = NULL)
 {
     PalPoint* p;
     p = new PalPoint;
     p->Set(mode,time,p1,p2);
     if(!Tail){
         p->Next = p->Prev = NULL;
         Tail = p;
     }else{
         Tail -> Prev = p;
         p -> Next = Tail;
         p -> Prev = NULL;
         Tail = p;
     };
 };
References PalPoint::Next, NULL, PalPoint::Prev, PalPoint::Set(), and Tail.
Referenced by VangerUnit::AddFree(), VangerUnit::AddPassage(), BunchEvent(), VangerUnit::Destroy(), StuffObject::Quant(), VangerUnit::Quant(), VangerUnit::SensorQuant(), and XpeditionOFF().
Member Data Documentation
PalEnable
int PalConstructor::PalEnable
Referenced by Init(), Quant(), VangerUnit::Quant(), and PalPoint::Set().
pPrev
PalPoint* PalConstructor::pPrev
Referenced by Init(), and Quant().
Tail
PalPoint* PalConstructor::Tail
Referenced by Clear(), Free(), Init(), Quant(), and Set().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp