Vangers: StuffObject Struct Reference
StuffObject Struct Reference
#include <items.h>
Public Member Functions
void Init (StorageType *s)
void Quant (void)
void DrawQuant (void)
void Touch (GeneralObject *p)
void CreateStuff (const Vector &_v, StuffObject *p, int cMode)
void CreateDevice (Vector v, VangerUnit *own, StuffObject *p)
virtual void DeviceIn (void)
virtual void DeviceOut (Vector v1, int flag=1, Vector v2=Vector(-1,-1,-1))
virtual void Active (void)
virtual void Deactive (void)
virtual void DeviceQuant (void)
virtual void DeviceLoad (Parser &in)
virtual void GetDevice (StuffObject *p)
void NetEvent (int type, int id, int creator, int x, int y)
void NetDeviceEvent (int type, int id, int creator, int x, int y)
void NetOwnerQuant (int impulse=0)
int GetTouchSensor (const char *name)
void ImpulseAction (Vector v1, int flag, Vector v2)
int CheckItemOver (void)
void SetStuffColor (void)
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
virtual int test_objects_collision ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Attributes
int StuffType
int ModelID
int uvsDeviceType
actintItemData ActIntBuffer
VangerUnit * Owner
int CreateMode
int DataID
int SizeID
StuffObject * NextDeviceList
StuffObject * PrevDeviceList
LightPoint * LightData
int CycleTime
VangerUnit * PrevOwner
int NetDeviceID
int xImpulse
int yImpulse
int OutFlag
int NetOwner
int Hour
int Minutes
int Time
int FindDolly
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Detailed Description
Member Function Documentation
Active()
void StuffObject::Active (void) virtual
 { };
CheckItemOver()
int StuffObject::CheckItemOver (void) inline
{
         if(ActIntBuffer.type == ACI_PROTRACTOR ||
            ActIntBuffer.type == ACI_MECHANIC_MESSIAH ||
            ActIntBuffer.type == ACI_FUNCTION83 ||
            ActIntBuffer.type == ACI_SPUMMY ||
            ActIntBuffer.type == ACI_BOOT_SECTOR ||
            ActIntBuffer.type == ACI_PEELOT ||
            ActIntBuffer.type == ACI_LEEPURINGA ||
            ActIntBuffer.type == ACI_SANDOLL_PART1 ||
            ActIntBuffer.type == ACI_SANDOLL_PART2 ||
            ActIntBuffer.type == ACI_LAST_MOGGY_PART1 ||
            ActIntBuffer.type == ACI_LAST_MOGGY_PART2 ||
            ActIntBuffer.type == ACI_QUEEN_FROG_PART1 ||
            ActIntBuffer.type == ACI_QUEEN_FROG_PART2 ||
            ActIntBuffer.type == ACI_LAWN_MOWER_PART1 ||
            ActIntBuffer.type == ACI_LAWN_MOWER_PART2 ||
            ActIntBuffer.type == ACI_WORMASTER_PART1 ||
            ActIntBuffer.type == ACI_WORMASTER_PART2 ||
            ActIntBuffer.type == ACI_TABUTASK_SUCCESSFUL ||
            ActIntBuffer.type == ACI_TABUTASK)
            return 0;
         else
             return 1;
     };
References ACI_BOOT_SECTOR, ACI_FUNCTION83, ACI_LAST_MOGGY_PART1, ACI_LAST_MOGGY_PART2, ACI_LAWN_MOWER_PART1, ACI_LAWN_MOWER_PART2, ACI_LEEPURINGA, ACI_MECHANIC_MESSIAH, ACI_PEELOT, ACI_PROTRACTOR, ACI_QUEEN_FROG_PART1, ACI_QUEEN_FROG_PART2, ACI_SANDOLL_PART1, ACI_SANDOLL_PART2, ACI_SPUMMY, ACI_TABUTASK, ACI_TABUTASK_SUCCESSFUL, ACI_WORMASTER_PART1, ACI_WORMASTER_PART2, ActIntBuffer, and actintItemData::type.
CreateDevice()
void StuffObject::CreateDevice (Vector v, VangerUnit * own, StuffObject * p)
 {
     GetDevice(p);
     ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
     own->AddDevice(this);
     Object::operator = (ModelD.ActiveModel(ModelID));
     Owner = own;
     Status = 0;
     R_curr = v;
 //  set_3D(R_curr.x,R_curr.y,0,0);
     set_active(0);
     LightData = NULL;
     OutFlag = 0;
     xImpulse = R_curr.x;
     yImpulse = R_curr.y;
     NetOwner = Owner->NetID;
     Time = 0;
     FindDolly = 0;
     if(NetworkON && (Owner->Status & SOBJ_ACTIVE)){
         NetID = CREATE_STUFF_NET_ID(NID_STUFF);
         NetDeviceID = CREATE_STUFF_NET_ID(NID_DEVICE);
         NETWORK_OUT_STREAM.create_permanent_object(NetDeviceID,xImpulse,yImpulse,radius);
         NETWORK_OUT_STREAM < (uchar)(DataID);
         NETWORK_OUT_STREAM < (int)(NetID);
         NETWORK_OUT_STREAM < (short)(R_curr.z);
         NETWORK_OUT_STREAM < (uchar)(ActIntBuffer.type);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data0);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data1);
         NETWORK_OUT_STREAM < (uchar)(CreateMode | (OutFlag));
         NETWORK_OUT_STREAM < (short)(Time);
         NETWORK_OUT_STREAM < (short)(R_curr.x);
         NETWORK_OUT_STREAM < (short)(R_curr.y);
         NETWORK_OUT_STREAM < (int)(NetOwner);
         NETWORK_OUT_STREAM.end_body();
     };
 };
References ActIntBuffer, ModelDispatcher::ActiveModel(), uvsUnitType::AddDevice(), CREATE_STUFF_NET_ID, CreateMode, actintItemData::data0, actintItemData::data1, DataID, FindDolly, GetDevice(), LightData, ModelD, ModelID, NetDeviceID, NetOwner, NETWORK_OUT_STREAM, NetworkON, NID_DEVICE, NID_STUFF, NULL, Object::operator=(), OutFlag, Owner, Object::radius, Object::set_active(), SOBJ_ACTIVE, Time, actintItemData::type, uvsDeviceType, uvsSetItemType(), xImpulse, and yImpulse.
Referenced by addDevice().
CreateStuff()
void StuffObject::CreateStuff (const Vector & _v, StuffObject * p, int cMode)
 {
     GetDevice(p);
     ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
     Object::operator = (ModelD.ActiveModel(ModelID));
     Owner = NULL;
     ItemD.ConnectTypeList(this);
     GameD.ConnectBaseList(this);
     R_curr = _v;
     Status = 0;
     cycleTor(R_curr.x,R_curr.y);
     set_active(0);
     GetVisible();
     switch_analysis(0);
     CreateMode = cMode;
     CycleTime = 0;
     LightData = NULL;
     Hour = ConTimer.hour;
     Minutes = ConTimer.min;
     Time = 0;
     FindDolly = 0;
     switch(CreateMode){
         case STUFF_CREATE_TRACK:
             if(Visibility == VISIBLE){
                 set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
                 xImpulse = XCYCL(R_curr.x + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                 yImpulse = YCYCL(R_curr.y + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                 precise_impulse(R_curr,xImpulse,yImpulse);
             }else{
                 R_curr.x = XCYCL(R_curr.x + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                 R_curr.y = YCYCL(R_curr.y + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                 xImpulse = R_curr.x;
                 yImpulse = R_curr.y;
             };
             break;
         case STUFF_CREATE_RELAX:
             switch_analysis(1);
             set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
             xImpulse = R_curr.x;
             yImpulse = R_curr.y;
             break;
         case STUFF_CREATE_NONE:
             set_3D(SET_3D_TO_THE_LOWER_LEVEL,R_curr.x,R_curr.y,0,radius/2,0,0);
             xImpulse = R_curr.x;
             yImpulse = R_curr.y;
             break;
         default:
             xImpulse = R_curr.x;
             yImpulse = R_curr.y;
             break;
     };
     SetStuffColor();
     switch(ActIntBuffer.type){
         case  ACI_KERNOBOO:
         case ACI_PIPETKA:
             archimedean = 255;
             break;
         case ACI_ELEEPOD:
         case ACI_BEEBOORAT:
         case ACI_ZEEX:
         case ACI_BOORAWCHIK:
             device_modulation = 1;
             break;
         case ACI_PROTRACTOR:
         case ACI_MECHANIC_MESSIAH:
         case ACI_FUNCTION83:
         case ACI_SPUMMY:
             CreateArtefactTarget(this);
             break;
         default:
             archimedean = 0;
             break;
     };
     OutFlag = 0;
     NetOwner = 0;
     if(NetworkON){
         NetID = CREATE_STUFF_NET_ID(NID_STUFF);
         NetDeviceID = CREATE_STUFF_NET_ID(NID_DEVICE);
         NETWORK_OUT_STREAM.create_permanent_object(NetID,xImpulse,yImpulse,radius);
         NETWORK_OUT_STREAM < (uchar)(DataID);
         NETWORK_OUT_STREAM < (int)(NetDeviceID);
         NETWORK_OUT_STREAM < (short)(R_curr.z);
         NETWORK_OUT_STREAM < (uchar)(ActIntBuffer.type);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data0);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data1);
         NETWORK_OUT_STREAM < (uchar)(CreateMode | (OutFlag));
         NETWORK_OUT_STREAM < (short)(Time);
         NETWORK_OUT_STREAM < (short)(R_curr.x);
         NETWORK_OUT_STREAM < (short)(R_curr.y);
         NETWORK_OUT_STREAM < (int)(NetOwner);
         NETWORK_OUT_STREAM.end_body();
     };
 };
References ACI_BEEBOORAT, ACI_BOORAWCHIK, ACI_ELEEPOD, ACI_FUNCTION83, ACI_KERNOBOO, ACI_MECHANIC_MESSIAH, ACI_PIPETKA, ACI_PROTRACTOR, ACI_SPUMMY, ACI_ZEEX, ActIntBuffer, ModelDispatcher::ActiveModel(), Object::archimedean, GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ConTimer, CREATE_STUFF_NET_ID, CreateArtefactTarget(), CreateMode, CycleTime, cycleTor(), actintItemData::data0, actintItemData::data1, DataID, Object::device_modulation, FindDolly, GameD, GetDevice(), Hour, uvsContimer::hour, ItemD, LightData, MAX_STUFF_SCATTER, uvsContimer::min, Minutes, ModelD, ModelID, NetDeviceID, NetOwner, NETWORK_OUT_STREAM, NetworkON, NID_DEVICE, NID_STUFF, NULL, Object::operator=(), OutFlag, Owner, Object::precise_impulse(), Object::radius, RND(), Object::set_3D(), SET_3D_DIRECT_PLACE, SET_3D_TO_THE_LOWER_LEVEL, Object::set_active(), SetStuffColor(), STUFF_CREATE_NONE, STUFF_CREATE_RELAX, STUFF_CREATE_TRACK, Object::switch_analysis(), Time, actintItemData::type, uvsDeviceType, uvsSetItemType(), VISIBLE, XCYCL, xImpulse, YCYCL, and yImpulse.
Referenced by addDevice().
Deactive()
void StuffObject::Deactive (void) virtual
 { };
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::ClearItemList(), ActionDispatcher::DeactiveAllSlots(), ItemsDispatcher::DeleteItem(), VangerUnit::DestroyItem(), VangerUnit::DischargeItem(), GunSlot::Fire(), uvsUnitType::Go2Universe(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), VangerUnit::ItemQuant(), VangerUnit::NewKeyHandler(), VangerUnit::OutCarNator(), and ActionDispatcher::SlotOut().
DeviceIn()
void StuffObject::DeviceIn (void) virtual
Reimplemented in GunDevice.
 {
     GameD.DisconnectBaseList(this);
     ItemD.DisconnectTypeList(this);
     Owner->AddDevice(this);
     Status = 0;
     if(LightData){
         LightData->Destroy();
         LightData = NULL;
     };
     FindDolly = 0;
     NetOwner = Owner->NetID;
     switch(ActIntBuffer.type){
         case ACI_PROTRACTOR:
         case ACI_MECHANIC_MESSIAH:
         case ACI_FUNCTION83:
         case ACI_SPUMMY:
             DeleteArtefactTarget(this);
             break;
 //      case ACI_MECHOSCOPE:
 //          break;
     };
     if(NetworkON && (Owner->Status & SOBJ_ACTIVE)){
         NETWORK_OUT_STREAM.delete_object(NetID);
         NETWORK_OUT_STREAM < (uchar)(1);
         NETWORK_OUT_STREAM.end_body();
         NETWORK_OUT_STREAM.create_permanent_object(NetDeviceID,xImpulse,yImpulse,radius);
         NETWORK_OUT_STREAM < (uchar)(DataID);
         NETWORK_OUT_STREAM < (int)(NetID);
         NETWORK_OUT_STREAM < (short)(R_curr.z);
         NETWORK_OUT_STREAM < (uchar)(ActIntBuffer.type);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data0);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data1);
         NETWORK_OUT_STREAM < (uchar)(CreateMode | (OutFlag));
         NETWORK_OUT_STREAM < (short)(Time);
         NETWORK_OUT_STREAM < (short)(R_curr.x);
         NETWORK_OUT_STREAM < (short)(R_curr.y);
         NETWORK_OUT_STREAM < (int)(NetOwner);
         NETWORK_OUT_STREAM.end_body();
     };
 };
References ACI_FUNCTION83, ACI_MECHANIC_MESSIAH, ACI_PROTRACTOR, ACI_SPUMMY, ActIntBuffer, uvsUnitType::AddDevice(), CreateMode, actintItemData::data0, actintItemData::data1, DataID, DeleteArtefactTarget(), LightPoint::Destroy(), GameObjectDispatcher::DisconnectBaseList(), UnitList::DisconnectTypeList(), FindDolly, GameD, ItemD, LightData, NetDeviceID, NetOwner, NETWORK_OUT_STREAM, NetworkON, NULL, OutFlag, Owner, Object::radius, SOBJ_ACTIVE, Time, actintItemData::type, xImpulse, and yImpulse.
Referenced by GunDevice::DeviceIn(), NetOwnerQuant(), and ItemsDispatcher::Quant().
DeviceLoad()
void StuffObject::DeviceLoad (Parser & in) virtual
Reimplemented in GunDevice.
 {
     in.search_name("ModelID");
     ModelID = ModelD.FindModel(in.get_name());
     in.search_name("SizeID");
     SizeID = in.get_int();
 //  in.search_name("ActiveInterfaceID");
 //  ActIntBuffer.type = in.get_int();
 };
References ModelDispatcher::FindModel(), Parser::get_int(), Parser::get_name(), ModelD, ModelID, Parser::search_name(), and SizeID.
Referenced by GunDevice::DeviceLoad(), and ItemsDispatcher::Init().
DeviceOut()
void StuffObject::DeviceOut (Vector v1, int flag = 1, Vector v2 = Vector(-1,-1,-1)) virtual
Reimplemented in ChangerDevice, and GunDevice.
 {
     int d;
     if(LightData){
         LightData->Destroy();
         LightData = NULL;
     };
     R_curr = v1;
     Status = 0;
     cycleTor(R_curr.x,R_curr.y);
     GetVisible();
     CycleTime = 0;
     Hour = ConTimer.hour;
     Minutes = ConTimer.min;
     if(CreateMode == STUFF_CREATE_RELAX) CreateMode = STUFF_CREATE_EXRELAX;
     else CreateMode = STUFF_CREATE_NONE;
     switch_analysis(0);
     SetStuffColor();
     switch(ActIntBuffer.type){
         case  ACI_KERNOBOO:
         case ACI_PIPETKA:
             archimedean = 255;
             break;
         case ACI_ELEEPOD:
         case ACI_BEEBOORAT:
         case ACI_ZEEX:
         case ACI_BOORAWCHIK:
             device_modulation = 1;
             break;
         case ACI_PROTRACTOR:
         case ACI_MECHANIC_MESSIAH:
         case ACI_FUNCTION83:
         case ACI_SPUMMY:
             CreateArtefactTarget(this);
             break;
         default:
             archimedean = 0;
             break;
     };
     if(!NetworkON || (Owner->Status & SOBJ_ACTIVE)){
         if(flag){
             if(ActIntBuffer.type == ACI_EMPTY_CONLARVER){
                 FindDolly = 1;
                 R_curr = Vector(XCYCL(R_curr.x + GeneralMousePoint.x),YCYCL(R_curr.y + GeneralMousePoint.y),0);
                 set_3D(SET_3D_TO_THE_LOWER_LEVEL,R_curr.x,R_curr.y,0,0,0,0);
                 DollyPoint.set(R_curr,15,8);
             }else{
                 set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
                 if(Owner->Armor > 0 && Owner->Energy >= Owner->DropEnergy){
                     if(Owner->Status & SOBJ_ACTIVE){
                         d = GeneralMousePoint.vabs();
                         if(d > 512) d = 512;
                         if(v2.y == -1){
                             v2.x = XCYCL(R_curr.x + GeneralMousePoint.x);
                             v2.y = YCYCL(GeneralMousePoint.y + R_curr.y);
                         };
                     }else{
                         if(v2.y == -1){
                             v2.x = XCYCL(R_curr.x + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                             v2.y = YCYCL(R_curr.y + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                         };
                     };
                 }else{
                     if(v2.y == -1){
                         v2.x = XCYCL(R_curr.x + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                         v2.y = YCYCL(R_curr.y + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER));
                     };
                 };
                 precise_impulse(R_curr,v2.x,v2.y);
             };
         }else
             set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
     }else{
         if(flag){
             if(ActIntBuffer.type == ACI_EMPTY_CONLARVER){
                 FindDolly = 1;
                 DollyPoint.set(R_curr,15,8);
             };
             set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
             precise_impulse(R_curr,v2.x,v2.y);
         }else
             set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
     };
     Owner->DelDevice(this);
     ItemD.ConnectTypeList(this);
     GameD.ConnectBaseList(this);
     PUT_GLOBAL_EVENT(AI_EVENT_DROP,ID,this,Owner);
     NetOwner = 0;
     xImpulse = v2.x;
     yImpulse = v2.y;
     if(Visibility == UNVISIBLE){
         R_curr.x = v2.x;
         R_curr.y = v2.y;
     };
     OutFlag = flag;
     if(NetworkON && (Owner->Status & SOBJ_ACTIVE)){
         NETWORK_OUT_STREAM.delete_object(NetDeviceID);
         NETWORK_OUT_STREAM < (uchar)(1);
         NETWORK_OUT_STREAM.end_body();
         NETWORK_OUT_STREAM.create_permanent_object(NetID,xImpulse,yImpulse,radius);
         NETWORK_OUT_STREAM < (uchar)(DataID);
         NETWORK_OUT_STREAM < (int)(NetDeviceID);
         NETWORK_OUT_STREAM < (short)(R_curr.z);
         NETWORK_OUT_STREAM < (uchar)(ActIntBuffer.type);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data0);
         NETWORK_OUT_STREAM < (int)(ActIntBuffer.data1);
         NETWORK_OUT_STREAM < (uchar)(CreateMode | (OutFlag << 7));
         NETWORK_OUT_STREAM < (short)(Time);
         NETWORK_OUT_STREAM < (short)(R_curr.x);
         NETWORK_OUT_STREAM < (short)(R_curr.y);
         NETWORK_OUT_STREAM < (int)(NetOwner);
         NETWORK_OUT_STREAM.end_body();
     };
     Owner = NULL;
 };
References ACI_BEEBOORAT, ACI_BOORAWCHIK, ACI_ELEEPOD, ACI_EMPTY_CONLARVER, ACI_FUNCTION83, ACI_KERNOBOO, ACI_MECHANIC_MESSIAH, ACI_PIPETKA, ACI_PROTRACTOR, ACI_SPUMMY, ACI_ZEEX, ActIntBuffer, AI_EVENT_DROP, Object::archimedean, uvsUnitType::Armor, GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ConTimer, CreateArtefactTarget(), CreateMode, CycleTime, cycleTor(), actintItemData::data0, actintItemData::data1, DataID, uvsUnitType::DelDevice(), LightPoint::Destroy(), Object::device_modulation, DollyPoint, uvsUnitType::DropEnergy, uvsUnitType::Energy, FindDolly, GameD, GeneralMousePoint, Hour, uvsContimer::hour, Object::ID, ItemD, LightData, MAX_STUFF_SCATTER, uvsContimer::min, Minutes, NetDeviceID, NetOwner, NETWORK_OUT_STREAM, NetworkON, NULL, OutFlag, Owner, Object::precise_impulse(), PUT_GLOBAL_EVENT, Object::radius, RND(), dastPoly3D::set(), Object::set_3D(), SET_3D_DIRECT_PLACE, SET_3D_TO_THE_LOWER_LEVEL, SetStuffColor(), SOBJ_ACTIVE, STUFF_CREATE_EXRELAX, STUFF_CREATE_NONE, STUFF_CREATE_RELAX, Object::switch_analysis(), Time, actintItemData::type, UNVISIBLE, Vector::vabs(), Vector::x, XCYCL, xImpulse, Vector::y, YCYCL, and yImpulse.
Referenced by VangerUnit::DestroyItem(), GunDevice::DeviceOut(), ChangerDevice::DeviceOut(), VangerUnit::DischargeItem(), NetOwnerQuant(), and VangerFunctionType::Quant().
DeviceQuant()
void StuffObject::DeviceQuant (void) virtual
Reimplemented in ChangerDevice, and GunDevice.
 { };
Referenced by VangerUnit::ItemQuant().
DrawQuant()
void StuffObject::DrawQuant (void)
 {
     if(Status & SOBJ_WAIT_CONFIRMATION) return;
     if(ActIntBuffer.type != ACI_CONLARVER && ActIntBuffer.type != ACI_EMPTY_CONLARVER){
         CycleTime = rPI(CycleTime + PI / 12);
         scale_size = original_scale_size + original_scale_size*Sin(CycleTime) / 8.;
     };
     draw();
 };
References ACI_CONLARVER, ACI_EMPTY_CONLARVER, ActIntBuffer, CycleTime, Object::draw(), Object::original_scale_size, PI, rPI, Object::scale_size, Sin(), SOBJ_WAIT_CONFIRMATION, and actintItemData::type.
GetDevice()
void StuffObject::GetDevice (StuffObject * p) virtual
Reimplemented in GunDevice.
 {
     DataID = p->DataID;
     StuffType = p->StuffType;
     ModelID = p->ModelID;
     uvsDeviceType = p->uvsDeviceType;
     ActIntBuffer.type = p->ActIntBuffer.type;
     ActIntBuffer.stuffOwner = (void*)(this);
     SizeID = p->SizeID;
 };
References ActIntBuffer, DataID, ModelID, SizeID, actintItemData::stuffOwner, StuffType, actintItemData::type, and uvsDeviceType.
Referenced by CreateDevice(), CreateStuff(), GunDevice::GetDevice(), and NetEvent().
GetTouchSensor()
int StuffObject::GetTouchSensor (const char * name)
 {
     int dx,dy,l;
     StaticObject* st;
     Vector vCheck;
     st = FindSensor(name);
     if(st){
         if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z  < ((SensorDataType*)(st))->z1 + radius){
             dx = getDistX(R_curr.x,st->R_curr.x);
             dy = getDistY(R_curr.y,st->R_curr.y);
             l = radius + st->radius;
             if((dx*dx + dy*dy) < l*l)
                 return 1;
         };
     };
     return 0;
 };
References FindSensor(), getDistX(), getDistY(), GeneralObject::R_curr, Object::radius, StaticObject::radius, Vector::x, and Vector::y.
Referenced by Quant().
ImpulseAction()
void StuffObject::ImpulseAction (Vector v1, int flag, Vector v2)
 {
     R_curr = v1;
     cycleTor(R_curr.x,R_curr.y);
     GetVisible();
     CycleTime = 0;
     Hour = ConTimer.hour;
     Minutes = ConTimer.min;
     if(CreateMode == STUFF_CREATE_RELAX) CreateMode = STUFF_CREATE_EXRELAX;
     else CreateMode = STUFF_CREATE_NONE;
     switch_analysis(0);
     SetStuffColor();
     switch(ActIntBuffer.type){
         case  ACI_KERNOBOO:
         case ACI_PIPETKA:
             archimedean = 255;
             break;
         case ACI_ELEEPOD:
         case ACI_BEEBOORAT:
         case ACI_ZEEX:
         case ACI_BOORAWCHIK:
             device_modulation = 1;
             break;
         default:
             archimedean = 0;
             break;
     };
     if(flag){
         if(ActIntBuffer.type == ACI_EMPTY_CONLARVER){
             FindDolly = 1;
             DollyPoint.set(R_curr,15,8);
         };
         set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
         precise_impulse(R_curr,v2.x,v2.y);
     }else
         set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
 };
References ACI_BEEBOORAT, ACI_BOORAWCHIK, ACI_ELEEPOD, ACI_EMPTY_CONLARVER, ACI_KERNOBOO, ACI_PIPETKA, ACI_ZEEX, ActIntBuffer, Object::archimedean, ConTimer, CreateMode, CycleTime, cycleTor(), Object::device_modulation, DollyPoint, FindDolly, Hour, uvsContimer::hour, uvsContimer::min, Minutes, Object::precise_impulse(), dastPoly3D::set(), Object::set_3D(), SET_3D_DIRECT_PLACE, SetStuffColor(), STUFF_CREATE_EXRELAX, STUFF_CREATE_NONE, STUFF_CREATE_RELAX, Object::switch_analysis(), actintItemData::type, Vector::x, and Vector::y.
Referenced by NetOwnerQuant().
Init()
void StuffObject::Init (StorageType * s)
 {
     BaseObject::Init(s);
     ID = ID_STUFF;
     Status = SOBJ_DISCONNECT;
     Owner = NULL;
     CreateMode = STUFF_CREATE_NONE;
 };
References CreateMode, Object::ID, ID_STUFF, NULL, Owner, SOBJ_DISCONNECT, and STUFF_CREATE_NONE.
NetDeviceEvent()
void StuffObject::NetDeviceEvent (int type, int id, int creator, int x, int y)
NetEvent()
void StuffObject::NetEvent (int type, int id, int creator, int x, int y)
 {
     char ch;
     short st;
     int t;
     switch(type){
         case UPDATE_OBJECT:
             NETWORK_IN_STREAM > ch;
             NETWORK_IN_STREAM > t;
             if(GET_NETWORK_ID(id) == NID_DEVICE){
                 NetDeviceID = id;
                 NetID = t;
             }else{
                 NetID = id;
                 NetDeviceID = t;
                 GetVisible();
             };
             NETWORK_IN_STREAM > st;
             R_curr.z = st;
             NETWORK_IN_STREAM > ch;
             ActIntBuffer.type = ch;
             NETWORK_IN_STREAM > ActIntBuffer.data0;
             NETWORK_IN_STREAM > ActIntBuffer.data1;
             NETWORK_IN_STREAM > ch;
             CreateMode = ch & 127;
             OutFlag = ch & 128;
             NETWORK_IN_STREAM > st;
             Time = st;
             SetStuffColor();
 /*          NETWORK_IN_STREAM > st;
             xImpulse = st;
             NETWORK_IN_STREAM > st;
             yImpulse = st;
             R_curr.x = x;
             R_curr.y = y;*/
             NETWORK_IN_STREAM > st;
             R_curr.x = st;
             NETWORK_IN_STREAM > st;
             R_curr.y = st;
             xImpulse = x;
             yImpulse = y;
             cycleTor(R_curr.x,R_curr.y);
             NETWORK_IN_STREAM > NetOwner;
             if(!Owner && !NetOwner && Visibility == UNVISIBLE){
                 R_curr.x = xImpulse;
                 R_curr.y = yImpulse;
             };
 //          if(Owner && !NetOwner) NetStuffLog < "\nBad Update Owner";
             Status |= SOBJ_WAIT_CONFIRMATION;
             NetOwnerQuant(1);
             break;
         case CREATE_OBJECT:
             NETWORK_IN_STREAM > t;
             if(GET_NETWORK_ID(id) == NID_DEVICE){
                 NetDeviceID = id;
                 NetID = t;
             }else{
                 NetID = id;
                 NetDeviceID = t;
             };
             ID = ID_STUFF;
             GetDevice(ItemD.DeviceTypeData[DataID]);
             Object::operator = (ModelD.ActiveModel(ModelID));
             Status = 0;
             set_active(0);
             CycleTime = 0;
             switch_analysis(0);
             LightData = NULL;
             NETWORK_IN_STREAM > st;
             R_curr.z = st;
             NETWORK_IN_STREAM > ch;
             ActIntBuffer.type = ch;
             NETWORK_IN_STREAM > ActIntBuffer.data0;
             NETWORK_IN_STREAM > ActIntBuffer.data1;
             NETWORK_IN_STREAM > ch;
             CreateMode = ch & 127;
             OutFlag = ch & 128;
             NETWORK_IN_STREAM > st;
             Time = st;
 /*          NETWORK_IN_STREAM > st;
             xImpulse = st;
             NETWORK_IN_STREAM > st;
             yImpulse = st;
             R_curr.x = x;
             R_curr.y = y;
             cycleTor(R_curr.x,R_curr.y);*/
             NETWORK_IN_STREAM > st;
             R_curr.x = st;
             NETWORK_IN_STREAM > st;
             R_curr.y = st;
             R_curr.x = xImpulse = x;
             R_curr.y = yImpulse = y;
             NETWORK_IN_STREAM > NetOwner;
             SetStuffColor();
             Time = 0;
             FindDolly = 1;
             switch(ActIntBuffer.type){
                 case  ACI_KERNOBOO:
                 case ACI_PIPETKA:
                     archimedean = 255;
                     break;
                 default:
                     archimedean = 0;
                     break;
             };
             Owner = NULL;
             Status |= SOBJ_WAIT_CONFIRMATION;
             if(NetOwner){
                 Owner = (VangerUnit*)(ActD.GetNetObject(NetOwner));
                 if(Owner) Owner->AddDevice(this);
                 else{
                     ItemD.ConnectTypeList(this);
                     GameD.ConnectBaseList(this);
                 };
             }else{
                 ItemD.ConnectTypeList(this);
                 GameD.ConnectBaseList(this);
                 switch(CreateMode){
                     case STUFF_CREATE_TRACK:
                         set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
                         precise_impulse(R_curr,XCYCL(R_curr.x + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER)),YCYCL(R_curr.y + MAX_STUFF_SCATTER - RND(2*MAX_STUFF_SCATTER)));
                         break;
                     case STUFF_CREATE_RELAX:
                         switch_analysis(1);
                         set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
                         break;
                     case STUFF_CREATE_NONE:
                         set_3D(SET_3D_TO_THE_LOWER_LEVEL,R_curr.x,R_curr.y,0,radius/2,0,0);
                         break;
                     default:
                         set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
                         break;
                 };
                 GetVisible();
 //              R_curr.x = xImpulse;
 //              R_curr.y = yImpulse;
             };
 //          if(Owner && !NetOwner) NetStuffLog < "\nBad Create Owner";
             break;
         case DELETE_OBJECT:
             if(NETWORK_IN_STREAM.current_body_size())
                 NETWORK_IN_STREAM > ch;
             else
                 ch = 0;
             if(!ch){
                 if(Owner){
                     Owner->CheckOutDevice(this);
                     if(Owner->Status & SOBJ_ACTIVE){
                         ActD.CheckDevice(this);
                         aciRemoveItem(&ActIntBuffer);
                     };
                     Owner->DelDevice(this);
                     Storage->Deactive(this);
                 }else
                     Status |= SOBJ_DISCONNECT;
             }else Status |= SOBJ_WAIT_CONFIRMATION;
             break;
     };
 };
References ACI_KERNOBOO, ACI_PIPETKA, aciRemoveItem(), ActD, ActIntBuffer, ModelDispatcher::ActiveModel(), uvsUnitType::AddDevice(), Object::archimedean, ActionDispatcher::CheckDevice(), VangerUnit::CheckOutDevice(), GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), CREATE_OBJECT, CreateMode, CycleTime, cycleTor(), actintItemData::data0, actintItemData::data1, DataID, uvsUnitType::DelDevice(), DELETE_OBJECT, ItemsDispatcher::DeviceTypeData, FindDolly, GameD, GET_NETWORK_ID, GetDevice(), UnitList::GetNetObject(), Object::ID, ID_STUFF, ItemD, LightData, MAX_STUFF_SCATTER, ModelD, ModelID, NetDeviceID, NetOwner, NetOwnerQuant(), NETWORK_IN_STREAM, NID_DEVICE, NULL, Object::operator=(), OutFlag, Owner, Object::precise_impulse(), Object::radius, RND(), Object::set_3D(), SET_3D_DIRECT_PLACE, SET_3D_TO_THE_LOWER_LEVEL, Object::set_active(), SetStuffColor(), SOBJ_ACTIVE, SOBJ_DISCONNECT, SOBJ_WAIT_CONFIRMATION, STUFF_CREATE_NONE, STUFF_CREATE_RELAX, STUFF_CREATE_TRACK, Object::switch_analysis(), Time, actintItemData::type, UNVISIBLE, UPDATE_OBJECT, Object::x, XCYCL, xImpulse, Object::y, YCYCL, and yImpulse.
Referenced by ItemsDispatcher::NetDevice(), and ItemsDispatcher::NetEvent().
NetOwnerQuant()
void StuffObject::NetOwnerQuant (int impulse = 0)
 {
     StuffObject* p;
     VangerUnit* n;
     if(NetOwner){
         if(Owner){
             if(Owner->NetID != NetOwner){
                 n = (VangerUnit*)(ActD.GetNetObject(NetOwner));
                 if(n){
                     Owner->CheckOutDevice(this);
                     if(Owner->Status & SOBJ_ACTIVE){
                         ActD.CheckDevice(this);
                         aciRemoveItem(&ActIntBuffer);
                     };
                     Owner->DelDevice(this);
                     Owner = n;
                     DeviceIn();
                     if(Owner->Status & SOBJ_ACTIVE){
                         ActIntBuffer.slot = -1;
                         aciSendEvent2actint(ACI_PUT_ITEM,&ActIntBuffer);
                     };
                     Status &= ~SOBJ_WAIT_CONFIRMATION;
                 };
             }else Status &= ~SOBJ_WAIT_CONFIRMATION;
         }else{
             Owner = (VangerUnit*)(ActD.GetNetObject(NetOwner));
             if(Owner){
                 DeviceIn();
                 if(Owner->Status & SOBJ_ACTIVE){
                     ActIntBuffer.slot = -1;
                     aciSendEvent2actint(ACI_PUT_ITEM,&ActIntBuffer);
                 };
                 Status &= ~SOBJ_WAIT_CONFIRMATION;
             };
         };
     }else{
         if(Owner){
             p = (StuffObject*)(ItemD.Tail);
             while(p){
                 if(p == this) break;
                 p = (StuffObject*)(p->NextTypeList);
             };
             if(!p){
                 Owner->CheckOutDevice(this);
                 if(Owner->Status & SOBJ_ACTIVE){
                     ActD.CheckDevice(this);
                     aciRemoveItem(&ActIntBuffer);
                 };
                 DeviceOut(R_curr,OutFlag,Vector(xImpulse,yImpulse,0));
             }else{
                 p = (StuffObject*)(Owner->DeviceData);
                 while(p){
                     if(p == this){
                         Owner->CheckOutDevice(this);
                         if(Owner->Status & SOBJ_ACTIVE){
                             ActD.CheckDevice(this);
                             aciRemoveItem(&ActIntBuffer);
                         };
                         Owner->DelDevice(this);
                         break;
                     };
                     p = p->NextDeviceList;
                 };
                 Owner = NULL;
             };
             Status &= ~SOBJ_WAIT_CONFIRMATION;
         }else{
             if(impulse) ImpulseAction(R_curr,OutFlag,Vector(xImpulse,yImpulse,0));
             Status &= ~SOBJ_WAIT_CONFIRMATION;
         };
     };
 };
References ACI_PUT_ITEM, aciRemoveItem(), aciSendEvent2actint(), ActD, ActIntBuffer, ActionDispatcher::CheckDevice(), VangerUnit::CheckOutDevice(), uvsUnitType::DelDevice(), uvsUnitType::DeviceData, DeviceIn(), DeviceOut(), UnitList::GetNetObject(), Object::impulse(), ImpulseAction(), ItemD, NetOwner, NextDeviceList, NULL, OutFlag, Owner, actintItemData::slot, SOBJ_ACTIVE, SOBJ_WAIT_CONFIRMATION, UnitList::Tail, xImpulse, and yImpulse.
Referenced by VangerUnit::ItemQuant(), NetEvent(), and Quant().
Quant()
void StuffObject::Quant (void)
 {
     int lv;
     int update_log = 0;
     if(NetworkON && (Status & SOBJ_WAIT_CONFIRMATION)) NetOwnerQuant();
     lv = Visibility;
     GetVisible();
     if(Status & SOBJ_WAIT_CONFIRMATION) return;
     if(ActIntBuffer.type == ACI_CONLARVER && Hour != ConTimer.hour/* && Minutes == ConTimer.min*/){
         uvsFreeDolly(R_curr.x,R_curr.y,ActIntBuffer.data0);
         ActIntBuffer.data1 = ActIntBuffer.data0 = 0;
         ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
         FindDolly = 0;
         SetStuffColor();
         if(LightData){
             LightData->Destroy();
             LightData = NULL;
         };
     };
     if(Visibility == VISIBLE){
         ItemD.NumVisibleItem++;
         switch(ActIntBuffer.type){
             case ACI_CONLARVER:
                 if(LightData) LightData->set_position(R_curr.x,R_curr.y,512);
                 else LightData = MapD.CreateLight(R_curr.x,R_curr.y,512,radius*2,63,LIGHT_TYPE::STATIC);
                 break;
             case ACI_EMPTY_CONLARVER:
                 if(LightData) LightData->set_position(R_curr.x,R_curr.y,512);
                 else LightData = MapD.CreateLight(R_curr.x,R_curr.y,512,radius,63,LIGHT_TYPE::DYNAMIC);
                 break;
             case ACI_MECHANIC_MESSIAH:
                 if(CurrentWorld == WORLD_XPLO && ActD.FunctionSpobsDestroyActive){
                     if(!ActD.SpobsDestroy && (dynamic_state & GROUND_COLLISION) && GetTouchSensor("Spot1")){
                         ActD.SpobsDestroy = 1;
                         PalCD.Set(CPAL_SPOBS_TO,50);
                         Status |= SOBJ_DISCONNECT;
                         ActD.XploKeyEnable = 0;
                         aciOpenWorldLink(WORLD_HMOK,WORLD_HMOK);
                         aciPrepareWorldsMenu();
                         start_vibration();
                         ActD.FunctionSpobsDestroyActive = 0;
                         SOUND_SPOPS_ALIES();
                     };
                 };
                 break;
             case ACI_PROTRACTOR:
                 if(CurrentWorld == WORLD_THREALL){
                     if(ActD.ThreallDestroy){
                         if(LightData) LightData->set_position(R_curr.x,R_curr.y,512);
                         else LightData = MapD.CreateLight(R_curr.x,R_curr.y,512,80,63,LIGHT_TYPE::DYNAMIC);
                         if(R_curr.z < 255) impulse(Vector(0,0,64),RND(15),RND(8));
                     }else{
                         if((dynamic_state & GROUND_COLLISION) && GetTouchSensor("SIGN") && ActD.FunctionThreallDestroyActive){
                             ActD.ThreallDestroy = 1;
                             aciOpenWorldLink(WORLD_HMOK,WORLD_HMOK);
                             aciPrepareWorldsMenu();
                             PalCD.Set(CPAL_THREALL_TO,50);
                             start_vibration();
                             SOUND_SPOPS_ALIES();
                             ActD.FunctionThreallDestroyActive = 0;
                         };
                     };
                 };
                 break;
             case ACI_ELEEPOD:
             case ACI_BEEBOORAT:
             case ACI_ZEEX:
             case ACI_BOORAWCHIK:
                 if(device_modulation > 0 && (dynamic_state & GROUND_COLLISION)){
                     DollyPoint.set(R_curr,15,20);
                     EffD.CreateDeform(R_curr,DEFORM_ALL,PASSING_WAVE_PROCESS);
                     device_modulation = 0;
                 };
                 break;
             default:
                 if((ActIntBuffer.type == ACI_ROTTEN_KERNOBOO || ActIntBuffer.type == ACI_ROTTEN_PIPETKA || ActIntBuffer.type == ACI_ROTTEN_WEEZYK || ActIntBuffer.type == ACI_DEAD_ELEECH) && (dynamic_state & GROUND_COLLISION))
                     Status |= SOBJ_DISCONNECT;
                 else{
                     if(LightData){
                         LightData->Destroy();
                         LightData = NULL;
                     };
                 };
                 break;
         };
         if(lv == UNVISIBLE){
             if(CreateMode == STUFF_CREATE_RELAX)
                 set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
             else{
                 if(uvsDeviceType == UVS_ITEM_TYPE::KERNOBOO || uvsDeviceType == UVS_ITEM_TYPE::PIPETKA)
                     set_3D(SET_3D_TO_THE_UPPER_LEVEL,R_curr.x,R_curr.y,0,0,0,0);
                 else
                     set_3D(SET_3D_CHOOSE_LEVEL,R_curr.x,R_curr.y,R_curr.z,0,0,0);
             };
         };
         analysis();
         cycleTor(R_curr.x,R_curr.y);
     }else{
         switch(ActIntBuffer.type){
             case ACI_ELEEPOD:
             case ACI_BEEBOORAT:
             case ACI_ZEEX:
             case ACI_BOORAWCHIK:
                 uvsKronDeleteItem(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
                 Status |= SOBJ_DISCONNECT;
                 break;
             case ACI_ROTTEN_KERNOBOO:
             case ACI_ROTTEN_PIPETKA:
             case ACI_ROTTEN_WEEZYK:
             case ACI_DEAD_ELEECH:
                 Status |= SOBJ_DISCONNECT;
                 break;
         };
         if(LightData){
             LightData->Destroy();
             LightData = NULL;
         };
     };
 };
References ACI_BEEBOORAT, ACI_BOORAWCHIK, ACI_CONLARVER, ACI_DEAD_ELEECH, ACI_ELEEPOD, ACI_EMPTY_CONLARVER, ACI_MECHANIC_MESSIAH, ACI_PROTRACTOR, ACI_ROTTEN_KERNOBOO, ACI_ROTTEN_PIPETKA, ACI_ROTTEN_WEEZYK, ACI_ZEEX, aciOpenWorldLink(), aciPrepareWorldsMenu(), ActD, ActIntBuffer, Object::analysis(), ConTimer, CPAL_SPOBS_TO, CPAL_THREALL_TO, EffectDispatcher::CreateDeform(), CreateMode, CurrentWorld, cycleTor(), actintItemData::data0, actintItemData::data1, DEFORM_ALL, LightPoint::Destroy(), Object::device_modulation, DollyPoint, LIGHT_TYPE::DYNAMIC, EffD, FindDolly, ActionDispatcher::FunctionSpobsDestroyActive, ActionDispatcher::FunctionThreallDestroyActive, GetTouchSensor(), GROUND_COLLISION, Hour, uvsContimer::hour, Object::impulse(), ItemD, UVS_ITEM_TYPE::KERNOBOO, LightData, MapD, NetOwnerQuant(), NetworkON, NULL, ItemsDispatcher::NumVisibleItem, PalCD, PASSING_WAVE_PROCESS, UVS_ITEM_TYPE::PIPETKA, Object::radius, RND(), PalConstructor::Set(), dastPoly3D::set(), Object::set_3D(), SET_3D_CHOOSE_LEVEL, SET_3D_DIRECT_PLACE, SET_3D_TO_THE_UPPER_LEVEL, LightPoint::set_position(), SetStuffColor(), SOBJ_DISCONNECT, SOBJ_WAIT_CONFIRMATION, SOUND_SPOPS_ALIES, ActionDispatcher::SpobsDestroy, start_vibration(), LIGHT_TYPE::STATIC, STUFF_CREATE_RELAX, ActionDispatcher::ThreallDestroy, actintItemData::type, UNVISIBLE, uvsDeviceType, uvsFreeDolly(), uvsKronDeleteItem(), uvsSetItemType(), VISIBLE, WORLD_HMOK, WORLD_THREALL, WORLD_XPLO, and ActionDispatcher::XploKeyEnable.
Referenced by GunDevice::Quant().
SetStuffColor()
void StuffObject::SetStuffColor (void)
 {
     int t;
     t = GetColorDevice(ActIntBuffer.type);
     if(t >= 0) set_body_color(t);
 };
References ActIntBuffer, GetColorDevice(), Object::set_body_color(), and actintItemData::type.
Referenced by ChangeItemData(), ChangeTabutaskItem(), CreateStuff(), DeviceOut(), ImpulseAction(), NetEvent(), and Quant().
Touch()
void StuffObject::Touch (GeneralObject * p)
 {
     if(Status & SOBJ_WAIT_CONFIRMATION) return;
     switch(p->ID){
         case ID_VANGER:
             if(!Owner){
                 Status |= SOBJ_LINK;
                 Owner = (VangerUnit*)p;
             };
 /*          if(!Owner){
                 if(((VangerUnit*)(p))->CheckInDevice(this)){
                     if(!(((VangerUnit*)(p))->Status & SOBJ_AUTOMAT)){
                         ActIntBuffer.slot = -1;
                         aciSendEvent2actint(ACI_PUT_ITEM,&ActIntBuffer);
                         SOUND_TAKE_ITEM()
                     };
                     Owner = (VangerUnit*)p;
                     Status |= SOBJ_LINK;
                 };
             }else{
                 if(!(Status & SOBJ_LINK)) ErrH.Abort("Bad Collision Stuff");
             };*/
             break;
     };
 };
References GeneralObject::ID, ID_VANGER, Owner, SOBJ_LINK, and SOBJ_WAIT_CONFIRMATION.
Member Data Documentation
ActIntBuffer
actintItemData StuffObject::ActIntBuffer
Referenced by uvsDolly::ActiveQuant(), addDevice(), uvsUnitType::AddDevice(), ChangeItemData(), ChangeTabutaskItem(), VangerUnit::ChangeVangerProcess(), ChargeDevice(), ChargeWeapon(), VangerUnit::CheckAmmo(), ActionDispatcher::CheckDevice(), VangerUnit::CheckInDevice(), CheckItemOver(), VangerUnit::CheckOutDevice(), VangerUnit::CheckSpeetle(), ItemsDispatcher::Close(), GunSlot::CloseGun(), CreateArtefactTarget(), CreateDevice(), CreateStuff(), VangerUnit::DestroyItem(), DeviceIn(), GunDevice::DeviceIn(), DeviceOut(), GunDevice::DeviceOut(), GunDevice::DeviceQuant(), VangerUnit::DischargeItem(), DrawQuant(), ActionDispatcher::DrawResource(), GunSlot::Fire(), GetDevice(), CharacterDataType::GetInternalStuffOrder(), GetStuffObject(), CharacterDataType::GetStuffOrder(), uvsUnitType::Go2Universe(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), ImpulseAction(), VangerUnit::InCarNator(), ItemsDispatcher::Init(), VangerUnit::ItemQuant(), ItemsDispatcher::LarvaHilator(), NetEvent(), NetOwnerQuant(), GunSlot::NetStuffQuant(), VangerUnit::NewKeyHandler(), GunSlot::OpenGun(), VangerUnit::OutCarNator(), Quant(), GunDevice::Quant(), ItemsDispatcher::Quant(), GunSlot::Quant(), VangerUnit::Quant(), VangerFunctionType::Quant(), GunSlot::RemoteFire(), VangerUnit::ResolveGenerator(), VangerUnit::ResolveHandlerFind(), SetStuffColor(), ActionDispatcher::SlotOut(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), and VangerUnit::WeaponGenerator().
CreateMode
int StuffObject::CreateMode
Referenced by ItemsDispatcher::Close(), CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), ImpulseAction(), Init(), NetEvent(), and Quant().
CycleTime
int StuffObject::CycleTime
Referenced by CreateStuff(), DeviceOut(), DrawQuant(), ImpulseAction(), and NetEvent().
DataID
int StuffObject::DataID
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), GetDevice(), ItemsDispatcher::Init(), ItemsDispatcher::NetDevice(), ItemsDispatcher::NetEvent(), and NetEvent().
FindDolly
int StuffObject::FindDolly
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), ImpulseAction(), NetEvent(), and Quant().
Hour
int StuffObject::Hour
Referenced by ItemsDispatcher::Close(), CreateStuff(), DeviceOut(), ImpulseAction(), and Quant().
LightData
LightPoint* StuffObject::LightData
Referenced by uvsDolly::ActiveQuant(), CreateDevice(), CreateStuff(), ItemsDispatcher::DeleteItem(), DeviceIn(), DeviceOut(), NetEvent(), and Quant().
Minutes
int StuffObject::Minutes
Referenced by CreateStuff(), DeviceOut(), and ImpulseAction().
ModelID
int StuffObject::ModelID
Referenced by CreateDevice(), CreateStuff(), DeviceLoad(), GetDevice(), NetEvent(), GunSlot::NetStuffQuant(), and GunSlot::OpenGun().
NetDeviceID
int StuffObject::NetDeviceID
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), ItemsDispatcher::NetDevice(), NetEvent(), GunSlot::NetStuffQuant(), and GunSlot::OpenGun().
NetOwner
int StuffObject::NetOwner
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), NetEvent(), and NetOwnerQuant().
NextDeviceList
StuffObject* StuffObject::NextDeviceList
Referenced by uvsUnitType::AddDevice(), ChangeItemData(), ChangeTabutaskItem(), VangerUnit::ChangeVangerProcess(), ChargeDevice(), ChargeWeapon(), VangerUnit::CheckInDevice(), VangerUnit::CheckOutDevice(), VangerUnit::ClearItemList(), uvsUnitType::DelDevice(), GunSlot::Fire(), GetStuffObject(), uvsUnitType::Go2Universe(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), VangerUnit::InCarNator(), VangerUnit::ItemQuant(), ItemsDispatcher::NetDevice(), ItemsDispatcher::NetEvent(), NetOwnerQuant(), GunSlot::NetStuffQuant(), VangerUnit::OutCarNator(), ItemsDispatcher::Quant(), VangerUnit::Quant(), VangerFunctionType::Quant(), VangerUnit::ResolveGenerator(), and VangerUnit::WeaponGenerator().
OutFlag
int StuffObject::OutFlag
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), NetEvent(), and NetOwnerQuant().
Owner
VangerUnit* StuffObject::Owner
Referenced by VangerUnit::CalcAiFactor(), ChangeItemData(), ChangeTabutaskItem(), CreateDevice(), CreateStuff(), DeviceIn(), GunDevice::DeviceIn(), DeviceOut(), GunDevice::DeviceOut(), ChangerDevice::DeviceOut(), GunDevice::DeviceQuant(), Init(), NetEvent(), NetOwnerQuant(), ItemsDispatcher::Quant(), and Touch().
PrevDeviceList
StuffObject* StuffObject::PrevDeviceList
Referenced by uvsUnitType::AddDevice(), and uvsUnitType::DelDevice().
PrevOwner
VangerUnit* StuffObject::PrevOwner
Referenced by GunDevice::CreateGun(), GunDevice::DeviceIn(), and GunDevice::DeviceOut().
SizeID
int StuffObject::SizeID
Referenced by DeviceLoad(), GetDevice(), and VangerUnit::WeaponGenerator().
StuffType
int StuffObject::StuffType
Referenced by addDevice(), GetDevice(), ItemsDispatcher::Init(), ItemsDispatcher::NetDevice(), ItemsDispatcher::NetEvent(), GameObjectDispatcher::Quant(), ActionDispatcher::SlotIn(), ActionDispatcher::SlotOut(), and VangerUnit::WeaponGenerator().
Time
int StuffObject::Time
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), GunDevice::DeviceOut(), GunDevice::DeviceQuant(), NetEvent(), GunDevice::Quant(), and GunSlot::Quant().
uvsDeviceType
int StuffObject::uvsDeviceType
Referenced by ChangeItemData(), ChangeTabutaskItem(), ChargeDevice(), ChargeWeapon(), VangerUnit::CheckInDevice(), VangerUnit::CheckOutDevice(), ItemsDispatcher::Close(), CreateDevice(), GunDevice::CreateGun(), CreateStuff(), GunDevice::DeviceIn(), GunDevice::DeviceQuant(), VangerUnit::DischargeItem(), ActionDispatcher::DrawResource(), GetDevice(), uvsUnitType::Go2Universe(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), ItemsDispatcher::Init(), ItemsDispatcher::LarvaHilator(), VangerUnit::OutCarNator(), Quant(), GunDevice::Quant(), ItemsDispatcher::Quant(), VangerUnit::ResolveHandlerFind(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), and VangerUnit::UsingCutterig().
xImpulse
int StuffObject::xImpulse
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), NetEvent(), and NetOwnerQuant().
yImpulse
int StuffObject::yImpulse
Referenced by CreateDevice(), CreateStuff(), DeviceIn(), DeviceOut(), NetEvent(), and NetOwnerQuant().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp