Vangers: XBuffer Struct Reference
XBuffer Struct Reference
#include <xbuffer.h>
Public Member Functions
XBuffer (unsigned int sz=XB_DEFSIZE)
XBuffer (void *p, int sz)
~XBuffer (void)
void SetRadix (int r)
void SetDigits (int d)
void alloc (unsigned int sz)
void free (void)
void fill (char fc='\0')
void set (int off, int mode=XB_BEG)
void init (void)
int search (char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int search (const char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int end () const
unsigned int tell (void) const
unsigned int length (void) const
char * address ()
unsigned int read (void *s, unsigned int len)
unsigned int write (const void *s, unsigned int len, int bin_flag=1)
void handleOutOfSize ()
XBuffer & operator< (const char *v)
XBuffer & operator< (char v)
XBuffer & operator< (unsigned char v)
XBuffer & operator< (short v)
XBuffer & operator< (unsigned short v)
XBuffer & operator< (int v)
XBuffer & operator< (unsigned int v)
XBuffer & operator< (long v)
XBuffer & operator< (unsigned long v)
XBuffer & operator< (float v)
XBuffer & operator< (double v)
XBuffer & operator< (long double v)
XBuffer & operator> (char *v)
XBuffer & operator> (char &v)
XBuffer & operator> (unsigned char &v)
XBuffer & operator> (short &v)
XBuffer & operator> (unsigned short &v)
XBuffer & operator> (int &v)
XBuffer & operator> (unsigned int &v)
XBuffer & operator> (long &v)
XBuffer & operator> (unsigned long &v)
XBuffer & operator> (float &v)
XBuffer & operator> (double &v)
XBuffer & operator> (long double &v)
XBuffer & operator<= (char)
XBuffer & operator<= (unsigned char)
XBuffer & operator<= (short)
XBuffer & operator<= (unsigned short)
XBuffer & operator<= (int)
XBuffer & operator<= (unsigned int)
XBuffer & operator<= (long)
XBuffer & operator<= (unsigned long)
XBuffer & operator<= (long long int)
XBuffer & operator<= (float)
XBuffer & operator<= (double)
XBuffer & operator<= (long double)
XBuffer & operator>= (char &)
XBuffer & operator>= (unsigned char &)
XBuffer & operator>= (short &)
XBuffer & operator>= (unsigned short &)
XBuffer & operator>= (int &)
XBuffer & operator>= (unsigned int &)
XBuffer & operator>= (long &)
XBuffer & operator>= (unsigned long &)
XBuffer & operator>= (float &)
XBuffer & operator>= (double &)
XBuffer & operator>= (long double &)
char * GetBuf ()
char * operator() (int offs)
char * operator() (unsigned int offs)
XBuffer & operator++ ()
XBuffer & operator-- ()
XBuffer & operator+= (int v)
XBuffer & operator-= (int v)
XBuffer & operator+= (unsigned int v)
XBuffer & operator-= (unsigned int v)
char operator[] (int ind) const
char operator() () const
char & operator[] (int ind)
char & operator() ()
template<class T >
XBuffer & write (const T &v)
template<class T >
XBuffer & read (T &v)
Public Attributes
char * buf
unsigned int size
unsigned int offset
int radix
int digits
int MakeFree
int automatic_realloc
Detailed Description
Constructor & Destructor Documentation
XBuffer() [1/2]
XBuffer::XBuffer (unsigned int sz = XB_DEFSIZE) inline
         {
         alloc(sz);
         radix=XB_DEFRADIX;
         digits=XB_DEFDIGITS;
         //Diffrent with _xtool.h in Source
         //automatic_realloc=automatic_realloc_;
         }
References alloc(), digits, radix, XB_DEFDIGITS, and XB_DEFRADIX.
XBuffer() [2/2]
XBuffer::XBuffer (void * p, int sz)
 {
     offset = 0L;
     radix = XB_DEFRADIX;
     digits = XB_DEFDIGITS;
     MakeFree = 0;
     size = sz;
     buf = (char*)p;
 }
References buf, digits, MakeFree, offset, radix, size, XB_DEFDIGITS, and XB_DEFRADIX.
~XBuffer()
XBuffer::~XBuffer (void) inline
 { free(); }
References free().
Member Function Documentation
address()
char* XBuffer::address () inline
 { return buf; }
References buf.
Referenced by aciSendEvent2itmdsp(), aciShowFrags(), acsLoadData(), acsPrepareSlotName(), iGameMap::draw(), OutputEventBuffer::end_body(), Parser::get_name(), Parser::get_string(), iChatInputChar(), iGetIP(), iInitMultiGames(), iInitServersList(), iScreenObject::init(), iPrepareHallOfFame(), iPreparePlayerResults(), iPrepareResults(), iPrepareSaveNames(), iProcessControlsScreen(), Object::load(), Server::load_rating_list(), Object::loadA3D(), Object::loadM3D(), PassageImageType::Open(), Parser::Parser(), InputEventBuffer::receive(), restore(), aciCHTree::save(), OutputEventBuffer::send(), and OutputEventBuffer::set_position().
alloc()
void XBuffer::alloc (unsigned int sz)
 {
     buf =  new char[size = sz];;
     offset = 0L;
     radix = XB_DEFRADIX;
     digits = XB_DEFDIGITS;
     MakeFree = 1;
     *buf = 0;
 }
References buf, digits, MakeFree, offset, radix, size, XB_DEFDIGITS, and XB_DEFRADIX.
Referenced by Parser::Parser(), and XBuffer().
end()
int XBuffer::end () const inline
 { return (offset > size); }
References offset, and size.
fill()
void XBuffer::fill (char fc = '\0')
{
     memset(buf,fc,size);
 }
References buf, and size.
free()
void XBuffer::free (void)
 {
     if(MakeFree && buf){
         delete[] buf;
         buf = NULL;
     }
 }
References buf, MakeFree, and NULL.
Referenced by ~XBuffer().
GetBuf()
char* XBuffer::GetBuf () inline
 { return buf; }
References buf.
Referenced by dgRoom::acceptQUERY(), dgRoom::acceptTEXT(), aci_setMatrixBorder(), aci_setScMatrixBorder(), acsLoadFonts(), aiPromptDominanceMessage(), aiPromptLuckMessage(), aiPromptTaskMessage(), aLoadFonts(), dgCell::analyzeACCESS(), aPutNum(), CreateTabutaskTarget(), iGameMap::draw(), ivrtMap::fileLoad(), vrtMap::fileLoad(), DiagenDispatcher::getInvText(), getRC(), uvsContimer::GetTime(), handle_error(), identification(), init_hfonts(), InitProtoCrypt(), InitScreenFonts(), MobileLocation::load(), ibsObject::load(), LoadingMessage(), MLload(), NetCheckRemovePlayer(), WorldScreen::Quant(), InputEventBuffer::receive(), dgRoom::seekM(), Server::Server(), ServerFindChain::ServerFindChain(), shotFlush(), ServersList::talk_to_server(), and VLload().
handleOutOfSize()
void XBuffer::handleOutOfSize ()
 {
     if(automatic_realloc)
         buf = (char*)realloc(buf, size *= 2);
     else {
         //xassert(0 && "Out of XBuffer");
         ErrH.Abort("Out of XBuffer");
     }
 }
References XErrorHandler::Abort(), automatic_realloc, buf, ErrH, and size.
Referenced by write().
init()
void XBuffer::init (void) inline
 { offset = 0; *buf = 0; }
References buf, and offset.
Referenced by aciSendEvent2itmdsp(), aciShowFrags(), acsLoadFonts(), acsPrepareSlotName(), aiPromptDominanceMessage(), aiPromptLuckMessage(), aiPromptTaskMessage(), aLoadFonts(), aLoadFonts32(), aPutNum(), CreateTabutaskTarget(), iGameMap::draw(), DiagenDispatcher::getInvText(), getRC(), uvsContimer::GetTime(), iChatInputChar(), iInitMultiGames(), iInitServersList(), init_hfonts(), InitProtoCrypt(), InitScreenFonts(), iPrepareHallOfFame(), iPreparePlayerResults(), iPrepareResults(), iPrepareSaveNames(), iProcessControlsScreen(), LoadMotorSound(), MLload(), NetCheckRemovePlayer(), network_analysis(), PassageImageType::Open(), CompasObject::Quant(), ActionDispatcher::Quant(), WorldScreen::Quant(), ScreenQuant(), OutputEventBuffer::send(), short_network_analysis(), and VLload().
length()
unsigned int XBuffer::length (void) const inline
 { return size; }
References size.
Referenced by Parser::get_name(), Parser::get_string(), identification(), Parser::Parser(), InputEventBuffer::receive(), and ServersList::talk_to_server().
operator()() [1/4]
char& XBuffer::operator() () inline
 { return buf[offset]; }
References buf, and offset.
operator()() [2/4]
char XBuffer::operator() () const inline
 { return buf[offset]; }
References buf, and offset.
operator()() [3/4]
char* XBuffer::operator() (int offs) inline
 { return buf + offs; }
References buf.
operator()() [4/4]
char* XBuffer::operator() (unsigned int offs) inline
 { return buf + offs; }
References buf.
operator++()
XBuffer& XBuffer::operator++ () inline
 { offset++; return *this; }
References offset.
operator+=() [1/2]
XBuffer& XBuffer::operator+= (int v) inline
 { offset+=v; return *this; }
References offset.
operator+=() [2/2]
XBuffer& XBuffer::operator+= (unsigned int v) inline
 { offset += v; return *this; }
References offset.
operator--()
XBuffer& XBuffer::operator-- () inline
 { offset--; return *this; }
References offset.
operator-=() [1/2]
XBuffer& XBuffer::operator-= (int v) inline
 { offset-=v; return *this; }
References offset.
operator-=() [2/2]
XBuffer& XBuffer::operator-= (unsigned int v) inline
 { offset -= v; return *this; }
References offset.
operator<() [1/12]
XBuffer& XBuffer::operator< (char v) inline
 { return write(v); }
References write().
operator<() [2/12]
XBuffer & XBuffer::operator< (const char * v)
 {
     if(v)
         write(v, strlen(v), 0);
     return *this;
 }
References write().
operator<() [3/12]
XBuffer& XBuffer::operator< (double v) inline
 { return write(v); }
References write().
operator<() [4/12]
XBuffer& XBuffer::operator< (float v) inline
 { return write(v); }
References write().
operator<() [5/12]
XBuffer& XBuffer::operator< (int v) inline
 { return write(v); }
References write().
operator<() [6/12]
XBuffer& XBuffer::operator< (long double v) inline
 { return write(v); }
References write().
operator<() [7/12]
XBuffer& XBuffer::operator< (long v) inline
 { return write(v); }
References write().
operator<() [8/12]
XBuffer& XBuffer::operator< (short v) inline
 { return write(v); }
References write().
operator<() [9/12]
XBuffer& XBuffer::operator< (unsigned char v) inline
 { return write(v); }
References write().
operator<() [10/12]
XBuffer& XBuffer::operator< (unsigned int v) inline
 { return write(v); }
References write().
operator<() [11/12]
XBuffer& XBuffer::operator< (unsigned long v) inline
 { return write(v); }
References write().
operator<() [12/12]
XBuffer& XBuffer::operator< (unsigned short v) inline
 { return write(v); }
References write().
operator<=() [1/12]
XBuffer & XBuffer::operator<= (char var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [2/12]
XBuffer & XBuffer::operator<= (double var)
 {
     int len = snprintf(_ConvertBuffer, _CONV_BUFFER_LEN, "%.*g", digits, var);
     write(_ConvertBuffer,len,0);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, digits, and write().
operator<=() [3/12]
XBuffer & XBuffer::operator<= (float var)
 {
     int len = snprintf(_ConvertBuffer, _CONV_BUFFER_LEN, "%.*g", digits, var);
     write(_ConvertBuffer,len,0);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, digits, and write().
operator<=() [4/12]
XBuffer & XBuffer::operator<= (int var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [5/12]
XBuffer & XBuffer::operator<= (long double var)
 {
     int len = snprintf(_ConvertBuffer, _CONV_BUFFER_LEN, "%.*Lg", digits, var);
     write(_ConvertBuffer,len,0);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, digits, and write().
operator<=() [6/12]
XBuffer & XBuffer::operator<= (long long int var)
 {
     char* s = port_ltoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_ltoa(), radix, and write().
operator<=() [7/12]
XBuffer & XBuffer::operator<= (long var)
 {
     char* s = port_ltoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_ltoa(), radix, and write().
operator<=() [8/12]
XBuffer & XBuffer::operator<= (short var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [9/12]
XBuffer & XBuffer::operator<= (unsigned char var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [10/12]
XBuffer& XBuffer::operator<= (unsigned int)
operator<=() [11/12]
XBuffer & XBuffer::operator<= (unsigned long var)
 {
     char* s = port_ultoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_ultoa(), radix, and write().
operator<=() [12/12]
XBuffer & XBuffer::operator<= (unsigned short var)
 {
     char* s = port_ltoa(var,_ConvertBuffer,radix);
     write(s,strlen(s),0);
     return *this;
 }
References _ConvertBuffer, port_ltoa(), radix, and write().
operator>() [1/12]
XBuffer& XBuffer::operator> (char & v) inline
 { return read(v); }
References read().
operator>() [2/12]
XBuffer & XBuffer::operator> (char * v)
 {
     if(v)
         read(v, strlen(buf + offset) + 1);
     return *this;
 }
References buf, offset, and read().
operator>() [3/12]
XBuffer& XBuffer::operator> (double & v) inline
 { return read(v); }
References read().
operator>() [4/12]
XBuffer& XBuffer::operator> (float & v) inline
 { return read(v); }
References read().
operator>() [5/12]
XBuffer& XBuffer::operator> (int & v) inline
 { return read(v); }
References read().
operator>() [6/12]
XBuffer& XBuffer::operator> (long & v) inline
 { return read(v); }
References read().
operator>() [7/12]
XBuffer& XBuffer::operator> (long double & v) inline
 { return read(v); }
References read().
operator>() [8/12]
XBuffer& XBuffer::operator> (short & v) inline
 { return read(v); }
References read().
operator>() [9/12]
XBuffer& XBuffer::operator> (unsigned char & v) inline
 { return read(v); }
References read().
operator>() [10/12]
XBuffer& XBuffer::operator> (unsigned int & v) inline
 { return read(v); }
References read().
operator>() [11/12]
XBuffer& XBuffer::operator> (unsigned long & v) inline
 { return read(v); }
References read().
operator>() [12/12]
XBuffer& XBuffer::operator> (unsigned short & v) inline
 { return read(v); }
References read().
operator>=() [1/11]
XBuffer & XBuffer::operator>= (char & var)
 {
     char* p = buf + offset;
     var = (char)strtol(p,&p,0);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [2/11]
XBuffer & XBuffer::operator>= (double & var)
 {
     char* p = buf + offset;
     var = strtod(p, &p);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [3/11]
XBuffer & XBuffer::operator>= (float & var)
 {
     char* p = buf + offset;
     var = (float)strtod(p, &p);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [4/11]
XBuffer & XBuffer::operator>= (int & var)
 {
     char* p = buf + offset;
     var = strtol(p,&p,0);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [5/11]
XBuffer & XBuffer::operator>= (long & var)
 {
     char* p = buf + offset;
     var = strtol(p, &p, 0);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [6/11]
XBuffer & XBuffer::operator>= (long double & var)
 {
     char* p = buf + offset;
     var = strtod(p, &p);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [7/11]
XBuffer & XBuffer::operator>= (short & var)
 {
     char* p = buf + offset;
     var = (short)strtol(p,&p,0);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [8/11]
XBuffer & XBuffer::operator>= (unsigned char & var)
 {
     char* p = buf + offset;
     var = (unsigned char)strtoul(p,&p,0);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [9/11]
XBuffer& XBuffer::operator>= (unsigned int &)
operator>=() [10/11]
XBuffer & XBuffer::operator>= (unsigned long & var)
 {
     char* p = buf + offset;
     var = strtoul(p, &p,0);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator>=() [11/11]
XBuffer & XBuffer::operator>= (unsigned short & var)
 {
     char* p = buf + offset;
     var = (unsigned short)strtoul(p,&p,0);
     offset += p - (buf + offset);
     return *this;
 }
References buf, and offset.
operator[]() [1/2]
char& XBuffer::operator[] (int ind) inline
 { return buf[ind]; }
References buf.
operator[]() [2/2]
char XBuffer::operator[] (int ind) const inline
 { return buf[ind]; }
References buf.
read() [1/2]
template<class T > XBuffer& XBuffer::read (T & v) inline
{
         v = (T&)buf[offset];
         offset += sizeof(T);
         return *this;
     }
References buf, and offset.
read() [2/2]
unsigned int XBuffer::read (void * s, unsigned int len)
 {
     memcpy(s, buf + offset, len);
     offset += len;
     return len;
 }
References buf, and offset.
Referenced by is_current_server_configured(), operator>(), PlayersList::parsing_total_body_query(), Player::receive(), send_server_data(), and PlayersList::single_parsing().
search() [1/2]
int XBuffer::search (char * what, int mode = XB_FORWARD, int cs = XB_CASEON)
 {
     int i,j;
     unsigned int wlen = strlen(what) - 1;
     if(mode == XB_GLOBAL) { i = 0; mode = XB_FORWARD; } else i = offset;
     if(mode == XB_FORWARD){
         if(cs == XB_CASEON){
             while(buf[i]){
                 if(buf[i] == *what){
                     j = wlen;
                     while(buf[i + j] == what[j] && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i++;
                 }
             }
         else {
             while(buf[i]){
                 if(toupper(buf[i]) == toupper(*what)){
                     j = wlen;
                     while(toupper(buf[i + j]) == toupper(what[j]) && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i++;
                 }
             }
         }
     else {
         i-=wlen + 1;
         if(cs == XB_CASEON){
             while(i >= 0){
                 if(buf[i] == *what){
                     j = wlen;
                     while(buf[i + j] == what[j] && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i--;
                 }
             }
         else {
             while(i >= 0){
                 if(toupper(buf[i]) == toupper(*what)){
                     j = wlen;
                     while(toupper(buf[i + j]) == toupper(what[j]) && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i--;
                 }
             }
         }
     return 0;
 }
References buf, offset, XB_CASEON, XB_FORWARD, and XB_GLOBAL.
Referenced by Parser::is_next_name(), and Parser::search_name().
search() [2/2]
int XBuffer::search (const char * what, int mode = XB_FORWARD, int cs = XB_CASEON)
 {
     int i,j;
     unsigned int wlen = strlen(what) - 1;
     if(mode == XB_GLOBAL) { i = 0; mode = XB_FORWARD; } else i = offset;
     if(mode == XB_FORWARD){
         if(cs == XB_CASEON){
             while(buf[i]){
                 if(buf[i] == *what){
                     j = wlen;
                     while(buf[i + j] == what[j] && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i++;
                 }
             }
         else {
             while(buf[i]){
                 if(toupper(buf[i]) == toupper(*what)){
                     j = wlen;
                     while(toupper(buf[i + j]) == toupper(what[j]) && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i++;
                 }
             }
         }
     else {
         i-=wlen + 1;
         if(cs == XB_CASEON){
             while(i >= 0){
                 if(buf[i] == *what){
                     j = wlen;
                     while(buf[i + j] == what[j] && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i--;
                 }
             }
         else {
             while(i >= 0){
                 if(toupper(buf[i]) == toupper(*what)){
                     j = wlen;
                     while(toupper(buf[i + j]) == toupper(what[j]) && j) j--;
                     if(j <= 0) { offset = i; return 1; };
                     }
                 i--;
                 }
             }
         }
     return 0;
 }
References buf, offset, XB_CASEON, XB_FORWARD, and XB_GLOBAL.
set()
void XBuffer::set (int off, int mode = XB_BEG)
 {
     switch(mode){
         case XB_BEG:
             offset = off;
             break;
         case XB_CUR:
             offset+=off;
             break;
         case XB_END:
             offset = size - off;
             break;
         }
 }
References offset, size, XB_BEG, XB_CUR, and XB_END.
Referenced by OutputEventBuffer::end_event(), Parser::get_name(), Parser::get_string(), identification(), InputEventBuffer::ignore_event(), Parser::is_next_name(), FileBox::load(), Model::loadC3D(), Model::loadC3Dvariable(), InputEventBuffer::next_event(), Parser::search_name(), and ServersList::talk_to_server().
SetDigits()
void XBuffer::SetDigits (int d) inline
 { digits = d; }
References digits.
Referenced by iGameMap::draw(), network_analysis(), and short_network_analysis().
SetRadix()
void XBuffer::SetRadix (int r) inline
 { radix = r; }
References radix.
Referenced by Object::analysis().
tell()
unsigned int XBuffer::tell (void) const inline
 { return offset; }
References offset.
Referenced by OutputEventBuffer::begin_create_z_object(), OutputEventBuffer::begin_direct_send(), OutputEventBuffer::begin_server_data(), OutputEventBuffer::delete_object(), OutputEventBuffer::end_body(), OutputEventBuffer::end_event(), Parser::get_name(), Parser::get_string(), identification(), Parser::is_next_name(), InputEventBuffer::next_event(), Player::receive(), InputEventBuffer::receive(), aciCHTree::save(), Parser::search_name(), Player::send(), OutputEventBuffer::send(), OutputEventBuffer::set_position(), and ServersList::talk_to_server().
write() [1/2]
template<class T > XBuffer& XBuffer::write (const T & v) inline
 { while(offset + sizeof(T) >= size) handleOutOfSize(); (T&)buf[offset] = v; offset += sizeof(T); return *this; }
References buf, handleOutOfSize(), offset, and size.
write() [2/2]
unsigned int XBuffer::write (const void * s, unsigned int len, int bin_flag = 1)
 {
     while(offset + len >= size)
         handleOutOfSize();
     memcpy(buf + offset, s, len);
     offset += len;
     if(!bin_flag)
         buf[offset] = '\0';
     return len;
 }
References buf, handleOutOfSize(), offset, and size.
Referenced by Game::get_total_list_of_players_data(), operator<(), operator<=(), Player::send(), send_server_data(), and OutputEventBuffer::set_player_body().
Member Data Documentation
automatic_realloc
int XBuffer::automatic_realloc
Referenced by handleOutOfSize().
buf
char* XBuffer::buf
Referenced by address(), alloc(), fill(), free(), Parser::get_name(), Parser::get_string(), GetBuf(), handleOutOfSize(), init(), Parser::is_next_name(), operator()(), operator>(), operator>=(), operator[](), Parser::Parser(), read(), InputEventBuffer::receive_waiting_for_event(), search(), OutputEventBuffer::send(), write(), and XBuffer().
digits
int XBuffer::digits
Referenced by alloc(), iPrepareHallOfFame(), iPrepareResults(), operator<=(), SetDigits(), and XBuffer().
MakeFree
int XBuffer::MakeFree
Referenced by alloc(), free(), and XBuffer().
offset
unsigned int XBuffer::offset
Referenced by alloc(), OutputEventBuffer::begin_event(), OutputEventBuffer::clear(), end(), OutputEventBuffer::end_body(), init(), operator()(), operator++(), operator+=(), operator--(), operator-=(), operator>(), operator>=(), read(), InputEventBuffer::receive(), InputEventBuffer::receive_waiting_for_event(), InputEventBuffer::reset(), search(), OutputEventBuffer::send(), set(), OutputEventBuffer::set_position(), tell(), write(), and XBuffer().
radix
int XBuffer::radix
Referenced by alloc(), operator<=(), SetRadix(), and XBuffer().
size
unsigned int XBuffer::size
Referenced by alloc(), end(), fill(), handleOutOfSize(), length(), InputEventBuffer::receive_waiting_for_event(), set(), write(), and XBuffer().
The documentation for this struct was generated from the following files:
lib/xtool/xbuffer.h
lib/xtool/xbuffer/xbcnvin.cpp
lib/xtool/xbuffer/xbcnvout.cpp
lib/xtool/xbuffer/xbcore.cpp
lib/xtool/xbuffer/xbsearch.cpp