Vangers: ivrtMap Struct Reference
ivrtMap Struct Reference
#include <ivmap.h>
Public Member Functions
ivrtMap (void)
void init (void)
void finit (void)
void load (const char *name)
void accept (int up, int down)
uchar * use (void)
uchar * use_c (void)
void analyzeINI (const char *name)
void fileLoad (void)
Public Attributes
uchar ** lineT
uchar ** lineTcolor
int upLine
int downLine
uchar * dHeap
int freeMax
int freeTail
ivrtNode * freeNodes
uchar * dHeap_c
int freeMax_c
int freeTail_c
ivrtNode * freeNodes_c
XStream fmap
int foffset
int offset
char * iniName
char * fileName
char * paletteName
char * fname
int isCompressed
int * st_table
short * sz_table
uchar * inbuf
Detailed Description
Constructor & Destructor Documentation
ivrtMap()
ivrtMap::ivrtMap (void)
 : fmap(0){}
Member Function Documentation
accept()
void ivrtMap::accept (int up, int down)
 {
     up = iYCYCL(up);
     down = iYCYCL(down);
     int max = iYCYCL(down + 1);
     int i = up;
     uchar* p;
     int off;
     if(!isCompressed)
         do {
             freeMax--;
             p = use();
             off = i*H2_SIZE;
             if(off != offset){
                 offset = off + H2_SIZE;
                 fmap.seek(foffset + off,XS_BEG);
                 }
             else
                 offset += H2_SIZE;
             fmap.read(p,H2_SIZE);
             lineT[i] = p;
             lineTcolor[i] = use_c();
             iLINE_render(i);
             i = iYCYCL(i + 1);
         } while(i != max);
     else
         do {
             freeMax--;
             p = use();
             fmap.seek(st_table[i],XS_BEG);
             fmap.read(inbuf,sz_table[i]);
             ExpandBuffer(inbuf,p);
             lineT[i] = p;
             lineTcolor[i] = use_c();
             iLINE_render(i);
             i = iYCYCL(i + 1);
         } while(i != max);
     upLine = up;
     downLine = down;
 }
References downLine, ExpandBuffer(), fmap, foffset, freeMax, H2_SIZE, iLINE_render(), inbuf, isCompressed, iYCYCL, lineT, lineTcolor, max(), offset, XStream::read(), XStream::seek(), st_table, sz_table, upLine, use(), use_c(), and XS_BEG.
analyzeINI()
void ivrtMap::analyzeINI (const char * name)
 {
     const char* version = "1.4";
     std::string secGlobal = "global parameters:";
     std::string secStorage = "Storage:";
     std::string secRender = "Rendering Parameters:";
     std::string secPalette = "Dynamic Palette:";
     XStream ff((char*)name,XS_IN);
     ff.close();
     dictionary *dict_name = iniparser_load(name);
     //iniparser_dump(dict_name, stdout);
     int val = atoi(iniparser_getstring(dict_name,"global parameters:Map Power X", NULL));
     if(val != MAP_POWER_X) ErrH.Abort("Incorrect X-Size");
     iMAP_POWER_Y = atoi(iniparser_getstring(dict_name,"global parameters:Map Power Y", NULL));
     if(strcmp(version,iniparser_getstring(dict_name,"Storage:Version", NULL))) ErrH.Abort("Incorrect Storage Version");
     isCompressed = atoi(iniparser_getstring(dict_name,"Storage:Compressed Format Using", NULL));
     fileName = strdup(iniparser_getstring(dict_name,"Storage:File Name", NULL));
     paletteName = strdup(iniparser_getstring(dict_name,"Storage:Palette File", NULL));
     int tmax = atoi(iniparser_getstring(dict_name,"Rendering Parameters:Terrain Max", NULL));
     if((!tmax && TERRAIN_MAX != 8) || (tmax && tmax != TERRAIN_MAX)) ErrH.Abort("Incorrect Terrain Max");
     int i;
     {
         char* p = iniparser_getstring(dict_name,"Rendering Parameters:Begin Colors", NULL);
         XBuffer buf(p,128);
         for(i = 0;i < TERRAIN_MAX;i++)
             buf >= iBEGCOLOR[i];
     }
     {
         char* p = iniparser_getstring(dict_name,"Rendering Parameters:End Colors", NULL);
         XBuffer buf(p,128);
         for(i = 0;i < TERRAIN_MAX;i++)
             buf >= iENDCOLOR[i];
     }
     ipal_iter_init();
     iPAL_MAX = iniparser_getint(dict_name,"Dynamic Palette:Terrain Number", 0);
     iPAL_WAVE_TERRAIN = iniparser_getint(dict_name,"Dynamic Palette:Wave Terrain", 0);
     if(iPAL_MAX > 0){
         {
             char* pp = iniparser_getstring(dict_name,"Dynamic Palette:Terrains", NULL);
             XBuffer b(pp,128);
             for(i = 0;i < iPAL_MAX;i++)
                 b >= iPAL_TERRAIN[i];
         }
         {
             char* pp = iniparser_getstring(dict_name,"Dynamic Palette:Speeds", NULL);
             XBuffer b(pp,128);
             for(i = 0;i < iPAL_MAX;i++)
                 b >= iPAL_SPEED[i];
         }
         {
             char *pp = iniparser_getstring(dict_name,"Dynamic Palette:Amplitudes", NULL);
             XBuffer b(pp,128);
             for(i = 0;i < iPAL_MAX;i++)
                 b >= iPAL_AMPL[i];
         }
         {
             char *pp = iniparser_getstring(dict_name,"Dynamic Palette:Red", NULL);
             XBuffer b(pp,128);
             for(i = 0;i < iPAL_MAX;i++)
                 b >= iPAL_RED[i];
         }
         {
             char *pp = iniparser_getstring(dict_name,"Dynamic Palette:Green", NULL);
             XBuffer b(pp,128);
             for(i = 0;i < iPAL_MAX;i++)
                 b >= iPAL_GREEN[i];
         }
         {
             char *pp = iniparser_getstring(dict_name,"Dynamic Palette:Blue", NULL);
             XBuffer b(pp,128);
             for(i = 0;i < iPAL_MAX;i++)
                 b >= iPAL_BLUE[i];
         }
     }
     iniparser_freedict(dict_name);
 }
References XErrorHandler::Abort(), XStream::close(), ErrH, iniparser_getstring(), iniparser_load(), MAP_POWER_X, NULL, and XS_IN.
Referenced by fileLoad().
fileLoad()
void ivrtMap::fileLoad (void)
 {
     analyzeINI(iniName);
     iYSetup();
     XBuffer buf;
     buf < fileName < (isCompressed ? ".vmc" : ".vmp");
     std::string sbuf=strdup(iGetMergedName(buf.GetBuf(),iniName)), sbuf2;
     int startR = sbuf.find("reso");
     sbuf2 = sbuf.substr(startR, sbuf.size()-startR);
     fname = strdup(sbuf2.c_str());
 }
References analyzeINI(), fileName, fname, XBuffer::GetBuf(), iGetMergedName(), iniName, isCompressed, and iYSetup().
Referenced by load().
finit()
void ivrtMap::finit (void)
 {
 #ifdef SAVE_ABILITY
     int max = iYCYCL(downLine + 1);
     int i = upLine;
     do {
         if(lineT[i]){
             fmap.seek(foffset + i*H2_SIZE,XS_BEG);
             fmap.write(lineT[i],H2_SIZE);
             }
         if(++i == iV_SIZE) i = 0;
     } while(i != max);
 #endif
     delete[] freeNodes;
     delete[] freeNodes_c;
     delete[] dHeap;
     delete[] dHeap_c;
     delete[] lineT;
     delete[] lineTcolor;
     if(isCompressed){
         delete[] inbuf;
         delete[] st_table;
         delete[] sz_table;
         }
     free(fileName);
     free(paletteName);
     free(iniName);
     free(fname);
     fmap.close();
 }
References downLine, fmap, foffset, H2_SIZE, iYCYCL, lineT, max(), XStream::seek(), upLine, XStream::write(), and XS_BEG.
init()
void ivrtMap::init (void)
 {
     freeNodes = new ivrtNode[MAX_LINE];
     dHeap = new uchar[MAX_LINE*H2_SIZE];
     freeNodes_c = new ivrtNode[MAX_LINE];
     dHeap_c = new uchar[MAX_LINE*H_SIZE];
     memset(lineT = new uchar*[iV_SIZE],0,iV_SIZE*sizeof(uchar*));
     memset(lineTcolor = new uchar*[iV_SIZE],0,iV_SIZE*sizeof(uchar*));
     freeMax = freeMax_c = MAX_LINE;
     freeTail = freeTail_c = 0;
     ivrtNode* p;
     int i;
     for(i = 0,p = freeNodes;i < MAX_LINE - 1;i++,p++) p -> next = p + 1;
     p -> next = freeNodes;
     for(i = 0,p = freeNodes_c;i < MAX_LINE - 1;i++,p++) p -> next = p + 1;
     p -> next = freeNodes_c;
 }
References dHeap, dHeap_c, freeNodes, freeNodes_c, H2_SIZE, H_SIZE, lineT, and MAX_LINE.
load()
void ivrtMap::load (const char * name)
 {
     iniName = strdup(name);
     fileLoad();
 #ifndef SAVE_ABILITY
     if(!fmap.open(fname,XS_IN))
         ErrH.Abort("iVMP not found");
 #else
     if(!fmap.open(fname,XS_IN | XS_OUT))
         ErrH.Abort("iVMP not found");
 #endif
     if(isCompressed){
         inbuf = new uchar[H2_SIZE];
         st_table = new int[iV_SIZE];
         sz_table = new short[iV_SIZE];
         for(uint i = 0;i < iV_SIZE;i++){
             fmap > st_table[i];
             fmap > sz_table[i];
             }
         InitSplay(fmap);
         }
     else {
         st_table = NULL;
         sz_table = NULL;
 //      if(fmap.size() != (int)map_size_x*(int)imap_size_y*2) ErrH.Abort("Incorrect ivmp-file size");
         }
     offset = 0;
     foffset = fmap.tell();
     iRenderPrepare();
 }
References XErrorHandler::Abort(), ErrH, fileLoad(), fmap, fname, H2_SIZE, inbuf, iniName, isCompressed, XStream::open(), st_table, XS_IN, and XS_OUT.
use()
uchar * ivrtMap::use (void) inline
 {
     uchar* p = dHeap + freeTail*H2_SIZE;
     freeTail = (freeNodes + freeTail) -> next - freeNodes;
     return p;
 }
References dHeap, freeNodes, freeTail, and H2_SIZE.
Referenced by accept().
use_c()
uchar * ivrtMap::use_c (void) inline
 {
     uchar* p = dHeap_c + freeTail_c*H_SIZE;
     freeTail_c = (freeNodes_c + freeTail_c) -> next - freeNodes_c;
     return p;
 }
References dHeap_c, freeNodes_c, freeTail_c, and H_SIZE.
Referenced by accept().
Member Data Documentation
dHeap
uchar* ivrtMap::dHeap
Referenced by init(), and use().
dHeap_c
uchar* ivrtMap::dHeap_c
Referenced by init(), and use_c().
downLine
int ivrtMap::downLine
Referenced by accept(), and finit().
fileName
char* ivrtMap::fileName
Referenced by fileLoad().
fmap
XStream ivrtMap::fmap
Referenced by accept(), finit(), and load().
fname
char* ivrtMap::fname
Referenced by fileLoad(), and load().
foffset
int ivrtMap::foffset
Referenced by accept(), and finit().
freeMax
int ivrtMap::freeMax
Referenced by accept().
freeMax_c
int ivrtMap::freeMax_c
freeNodes
ivrtNode* ivrtMap::freeNodes
Referenced by init(), and use().
freeNodes_c
ivrtNode* ivrtMap::freeNodes_c
Referenced by init(), and use_c().
freeTail
int ivrtMap::freeTail
Referenced by use().
freeTail_c
int ivrtMap::freeTail_c
Referenced by use_c().
inbuf
uchar* ivrtMap::inbuf
Referenced by accept(), and load().
iniName
char* ivrtMap::iniName
Referenced by fileLoad(), and load().
isCompressed
int ivrtMap::isCompressed
Referenced by accept(), fileLoad(), and load().
lineT
uchar** ivrtMap::lineT
Referenced by accept(), finit(), and init().
lineTcolor
uchar** ivrtMap::lineTcolor
Referenced by accept().
offset
int ivrtMap::offset
Referenced by accept().
paletteName
char* ivrtMap::paletteName
st_table
int* ivrtMap::st_table
Referenced by accept(), and load().
sz_table
short* ivrtMap::sz_table
Referenced by accept().
upLine
int ivrtMap::upLine
Referenced by accept(), and finit().
The documentation for this struct was generated from the following files:
src/iscreen/ivmap.h
src/iscreen/ivmap.cpp