Vangers: XRecorder Struct Reference
XRecorder Struct Reference
#include <xrec.h>
Public Member Functions
void Quant (void)
void Open (char *fname, int mode)
void Close (void)
void Flush (void)
void PutSysMessage (int id, SDL_Event *e)
void GetMessage (void)
void DispatchMessage (void)
int CheckMessage (int code)
XRecorder (void)
Public Attributes
int flags
int frameCount
int controlCount
void * hWnd
XStream * hFile
int nextMsgDataSize
XRecorderMessage * nextMsg
Detailed Description
Constructor & Destructor Documentation
XRecorder()
XRecorder::XRecorder (void)
 {
     flags = 0;
     frameCount = controlCount = 0;
     hFile = NULL;
     nextMsg = NULL;
     hWnd = NULL;
 }
References controlCount, flags, frameCount, hFile, hWnd, nextMsg, and NULL.
Member Function Documentation
CheckMessage()
int XRecorder::CheckMessage (int code)
 {
     int i;
     for(i = 0; i < XREC_MAX_CMESSAGE; i ++){
         if(XREC_CMESSAGES[i] == code){
             if(flags & XRC_PLAY_MODE)
                 Close();
             return 0;
         }
     }
     for(i = 0; i < XREC_MAX_IMESSAGE; i ++){
         if(XREC_IMESSAGES[i] == code) return 0;
     }
     return 1;
 }
References XREC_MAX_CMESSAGE.
Referenced by xtClearMessageQueue(), and xtProcessMessageBuffer().
Close()
void XRecorder::Close (void)
 {
     if(flags & (XRC_RECORD_MODE | XRC_PLAY_MODE)){
         hFile -> close();
         flags &= ~(XRC_RECORD_MODE | XRC_PLAY_MODE | XRC_MESSAGE_READ);
 #ifdef  _XRECORDER_LOG_
         XRecLog.close();
 #endif
     }
 }
References XStream::close(), flags, hFile, XRC_MESSAGE_READ, XRC_PLAY_MODE, and XRC_RECORD_MODE.
Referenced by GetMessage(), and Open().
DispatchMessage()
void XRecorder::DispatchMessage (void)
 {
     SDL_Event e;
     if((flags & XRC_MESSAGE_READ) && frameCount == nextMsg -> Frame){
         switch(nextMsg -> Type){
             case XRC_USER_MESSAGE:
                 break;
             case XRC_XMOUSE_MESSAGE:
             case XRC_SYSTEM_MESSAGE:
                 memcpy(&e, nextMsg->data, sizeof(SDL_Event));
                 xtDispatchMessage(&e);
                 break;
         }
 #ifdef  _XRECORDER_LOG_
         XRecLog < "\r\nEvent -> " <= nextMsg -> Type < "(" <= nextMsg -> data[0] < "), frame = " <= frameCount;
 #endif
     }
 }
References XRecorderMessage::data, flags, frameCount, nextMsg, XRC_MESSAGE_READ, XRC_SYSTEM_MESSAGE, XRC_USER_MESSAGE, XRC_XMOUSE_MESSAGE, and xtDispatchMessage().
Referenced by Quant().
Flush()
void XRecorder::Flush (void)
 {
 #ifdef  _XRECORDER_LOG_
         XRecLog < "\r\nEvent -> " <= nextMsg -> Type < "(" <= nextMsg -> data[0] < "), frame = " <= frameCount;
 #endif
     *hFile < nextMsg -> Type < nextMsg -> Frame < nextMsg -> DataSize;
     if(nextMsg -> DataSize){
         hFile -> write((char*)nextMsg -> data, nextMsg -> DataSize);
     }
 }
References frameCount, hFile, and nextMsg.
Referenced by PutSysMessage().
GetMessage()
void XRecorder::GetMessage (void)
 {
     if(flags & XRC_PLAY_MODE){
         if(hFile -> eof()){
             Close();
             return;
         }
         *hFile > nextMsg -> Type > nextMsg -> Frame > nextMsg -> DataSize;
         if(nextMsg -> DataSize){
             if(nextMsg -> DataSize > nextMsgDataSize){
                 delete nextMsg -> data;
                 nextMsg -> data = new SDL_Event;
                 nextMsgDataSize = nextMsg -> DataSize;
             }
             hFile -> read((char*)nextMsg -> data, nextMsg -> DataSize);
         }
         flags |= XRC_MESSAGE_READ;
     }
 }
References Close(), flags, hFile, nextMsg, nextMsgDataSize, XRC_MESSAGE_READ, and XRC_PLAY_MODE.
Referenced by Quant().
Open()
void XRecorder::Open (char * fname, int mode)
 {
     int fmode;
     if(flags & (XRC_RECORD_MODE | XRC_PLAY_MODE))
         Close();
     if(!nextMsg){
         nextMsg = new XRecorderMessage;
         nextMsg -> data = new SDL_Event;
         nextMsgDataSize = sizeof(SDL_Event);
     }
     if(!hFile)
         hFile = new XStream;
     fmode = (mode == XRC_RECORD_MODE) ? XS_OUT : XS_IN;
     hFile -> open(fname,fmode);
 #ifdef  _XRECORDER_LOG_
     if(mode == XRC_RECORD_MODE)
         XRecLog.open("xrec_wr.log",XS_OUT);
     else
         XRecLog.open("xrec_pl.log",XS_OUT);
 #endif
     frameCount = 0;
     flags |= mode;
 }
References Close(), flags, frameCount, hFile, nextMsg, nextMsgDataSize, XStream::open(), XRC_PLAY_MODE, XRC_RECORD_MODE, XS_IN, and XS_OUT.
Referenced by xtInitApplication().
PutSysMessage()
void XRecorder::PutSysMessage (int id, SDL_Event * e)
 {
     nextMsg -> Type = id;
     nextMsg -> Frame = frameCount;
     nextMsg -> DataSize = sizeof(SDL_Event);
     memcpy(nextMsg -> data, e, sizeof(SDL_Event));
     Flush();
 }
References Flush(), frameCount, and nextMsg.
Quant()
void XRecorder::Quant (void)
 {
     frameCount ++;
     if(flags & XRC_PLAY_MODE){
         if(!(flags & XRC_MESSAGE_READ))
             GetMessage();
         while(flags & XRC_MESSAGE_READ && frameCount == nextMsg -> Frame){
             DispatchMessage();
             GetMessage();
         }
     }
     xtSysQuant();
     xtClearMessageQueue();
     xtProcessMessageBuffer();
 }
References DispatchMessage(), flags, frameCount, GetMessage(), nextMsg, XRC_MESSAGE_READ, XRC_PLAY_MODE, xtClearMessageQueue(), xtProcessMessageBuffer(), and xtSysQuant().
Referenced by main().
Member Data Documentation
controlCount
int XRecorder::controlCount
Referenced by XRecorder().
flags
int XRecorder::flags
Referenced by Close(), DispatchMessage(), GetMessage(), main(), Open(), Quant(), aciML_Dispatcher::startup(), XGR_MouseFnc(), XRecorder(), and xtProcessMessageBuffer().
frameCount
int XRecorder::frameCount
Referenced by DispatchMessage(), aciML_Dispatcher::event_quant(), Flush(), main(), Open(), PutSysMessage(), Quant(), and XRecorder().
hFile
XStream* XRecorder::hFile
Referenced by Close(), Flush(), GetMessage(), Open(), and XRecorder().
hWnd
void* XRecorder::hWnd
Referenced by XRecorder().
nextMsg
XRecorderMessage* XRecorder::nextMsg
Referenced by DispatchMessage(), Flush(), GetMessage(), Open(), PutSysMessage(), Quant(), and XRecorder().
nextMsgDataSize
int XRecorder::nextMsgDataSize
Referenced by GetMessage(), and Open().
The documentation for this struct was generated from the following files:
lib/xtool/xrec.h
lib/xtool/xrecorder/xrec.cpp