Vangers: dgFile Struct Reference
dgFile Struct Reference
#include <diagen.h>
Public Member Functions
dgFile (char *fname, int _len=0)
dgFile (void)
~dgFile (void)
void load (char *fname, int _len=0)
char * getElement (int DualElements, int empty_available=0)
void free (void)
void reset (void)
Public Attributes
char * buf
int len
int index
int external
Detailed Description
Constructor & Destructor Documentation
dgFile() [1/2]
dgFile::dgFile (char * fname, int _len = 0) inline
 { load(fname,_len); }
References load().
dgFile() [2/2]
dgFile::dgFile (void) inline
 { buf = NULL; len = index = -1; external = 0; }
References buf, external, index, len, and NULL.
~dgFile()
dgFile::~dgFile (void) inline
 { if(!external && buf) delete buf; }
References buf, and external.
Member Function Documentation
free()
void dgFile::free (void) inline
 { if(!external && buf) delete buf; len = index = -1; }
References buf, external, index, and len.
getElement()
char * dgFile::getElement (int DualElements, int empty_available = 0)
 {
     char* p = buf + index;
     while(index < len && !(*p)) p++, index++;
     if(index == len){
         if(!empty_available)
             ErrH.Abort(dgSyntaxError);
         return NULL;
         }
     char* ret = p;
     while(index < len && *p) p++, index++;
 #if defined(DIAGEN_TEST) || !defined(SINGLE_LANGUAGE)
     char* ret2 = ret; //(stalkerg) Для определения символа по которому можно понять язык
     char* elem;
     if(DualElements == DGF_DUAL) {
         if (*ret2) {
             if (*ret2 == '$' && *(ret2+1) == '(') {
                 std::cout<<"Detect variable in start string."<<std::endl;
                 while(*ret2 && *ret2 != ')') { //Ищем конец переменной. Могут быть переполнения. Но мы будем писать аккуратно. :)
                     ret2++;
                 }
                 ret2++;
                 while(*ret2 && *ret2 == ' ') { //Пропускаем пробелы
                     ret2++;
                 }
             }
         }
         if (!(*ret2)) {
             ErrH.Abort("Nope closing bracket for variable",XERR_USER,-1,"");
         }
         if(*ret2 == SUBJ_SYMBOL || *ret2 == COMMAND_SYMBOL) {
             return ret;
         }
         elem = (*ret2 == LINK_SYMBOL || *ret2 == '<') ? ret2 + 1 : ret2;
         if((lang() != RUSSIAN && ISEALPHA(*elem)) || (lang() == RUSSIAN && !ISEALPHA(*elem))) {
             return ret;
         } else {
             return getElement(DualElements, empty_available);
         }
     }
 #endif
     return ret;
 }
References XErrorHandler::Abort(), buf, ErrH, index, and len.
Referenced by dgCell::analyzeACCESS(), dgCell::expressACCESS(), and dgCell::isACCESS().
load()
void dgFile::load (char * fname, int _len = 0)
 {
     static char mss[] = "Wrong dgFile format";
     int handle = 0;
     if(!_len){
 #ifdef DIAGEN_TEST
         external = 0;
         XStream ff(fname,XS_IN);
         buf = new char[(len = ff.size()) + 1];
         ff.read(buf,len);
         ff.close();
         buf[len] = '\0';
         handle = 1;
 #else
         external = 1;
         buf = FBox -> get(fname,len);
 #endif
     } else {
         external = 1;
         len = _len;
         buf = fname;
         handle = 1;
     }
     if(!handle) {
         index = 0;
         return;
     }
     int i = 0,mode = 1,j;
     char c;
     //(stalkerg)Разрезаем буфер там где есть комментарии
     while(i < len){
         c = buf[i];
         if(mode) {
             if(c == '/' && buf[i + 1] == '*') {
                 buf[i] = buf[i + 1] = '\0';
                 i++;
                 mode = 0;
             }
         } else {
             if(c == '*' && buf[i + 1] == '/') {
                 buf[i] = buf[i + 1] = '\0';
                 i++;
                 mode = 1;
             } else {
                 buf[i] = '\0';
             }
         }
         i++;
     }
     i = 0;
     while(i < len){
         c = buf[i];
         if(c == '\"'){
             buf[i++] = '\0';
             j = i;
             while(i < len){
                 if(buf[i] == '\"') {
                     break;
                 }
                 if(buf[i] == SUBJ_SYMBOL || buf[i] == LINK_SYMBOL) {
                     ErrH.Abort(fname,XERR_USER,-1,buf + i + 1);
                 }
                 i++;
             }
             if(i == len) {
                 ErrH.Abort(mss,XERR_USER,-1,"\" absent");
             } else {
                 buf[i] = '\0';
             }
         } else {
             if(c == SUBJ_SYMBOL) {
                 i++;
                 while(i < len) {
                     if(buf[i] == SUBJ_SYMBOL_RIGHT) break;
                     i++;
                 }
                 if(i == len) {
                     ErrH.Abort(mss,XERR_USER,-1,"RightSubjSymbol absent");
                 }
             } else {
                 if(c == LINK_SYMBOL) {
                     i++;
                     while(i < len) {
                         if(buf[i] == LINK_SYMBOL_RIGHT) break;
                         i++;
                         }
                     if(i == len) {
                         ErrH.Abort(mss,XERR_USER,-1,"RightLinkSymbol absent");
                     }
                 } else {
                     if(c == ' ' || c == '\t' || c == '\r' || c == '\n') {
                         buf[i] = '\0';
                     }
                 }
             }
         }
         i++;
     }
     index = 0;
 #ifdef DIAGEN_TEST
     if(external) return;
     char* b = new char[len];
     memset(b,0,len);
     int off = 0,l;
     char* p, *p2;
 #ifdef SAVE_SINGE_LANGUAGE
     int skip = !memcmp(fname + strlen(fname) - 3,"dil",3) || !memcmp(fname + strlen(fname) - 3,"lst",3);
 #endif
     while(1){
         p = getElement(DGF_NONE,1);
         if(!p) break;
 #ifdef SAVE_SINGE_LANGUAGE
         if(!skip){
             p2 = detect_text(p);
             if(!(*p2 == SUBJ_SYMBOL || *p2 == COMMAND_SYMBOL || *p2 == '<' || *p2 == '#')) {
                 if(!((lang() !== RUSSIAN && ISEALPHA(*p2)) || (lang() == RUSSIAN && !ISEALPHA(*p2)))) continue;
             }
         }
 #endif
         l = strlen(p);
         memcpy(b + off,p,l);
         off += l + 1;
         }
     FBox -> add(fname,b,off);
     delete b;
 #endif
     index = 0;
 }
References buf, XStream::close(), external, len, XStream::read(), XStream::size(), and XS_IN.
Referenced by dgFile(), and dgCell::read().
reset()
void dgFile::reset (void) inline
 { index = 0; }
References index.
Referenced by dgCell::isACCESS().
Member Data Documentation
buf
char* dgFile::buf
Referenced by dgFile(), free(), getElement(), load(), and ~dgFile().
external
int dgFile::external
Referenced by dgFile(), free(), load(), and ~dgFile().
index
int dgFile::index
Referenced by dgFile(), free(), getElement(), and reset().
len
int dgFile::len
Referenced by dgFile(), free(), getElement(), and load().
The documentation for this struct was generated from the following files:
src/uvs/diagen.h
src/uvs/diagen.cpp