Vangers: VangerFunctionType Struct Reference
VangerFunctionType Struct Reference
#include <mechos.h>
Public Member Functions
void Init (int _ID, Vector _vR, int _Time, int _External=0)
void Quant (void)
void SoundQuant (void)
Public Attributes
int ID
Vector vR
int Time
int LifeTime
VangerFunctionType * Next
VangerFunctionType * Prev
Detailed Description
Member Function Documentation
Init()
void VangerFunctionType::Init (int _ID, Vector _vR, int _Time, int _External = 0)
 {
     ID = _ID;
     vR = _vR;
     LifeTime = Time = _Time;
     Next = Prev =NULL;
     if(_External){
         switch(ID){
             case PROTRACTOR_SCALE_UP:
             case PROTRACTOR_SCALE_DOWN:
             case PROTRACTOR_BEEBOS_DANCE:
             case PROTRACTOR_MOLERIZATOR:
             case PROTRACTOR_PALLADIUM:
             case PROTRACTOR_JESTEROID:
                 Time = LifeTime - SIGNATOR_DELAY + 1;
                 break;
             case MECHANIC_BEEB_NATION:
             case MECHANIC_UNVISIBLE:
                 Time = LifeTime - SKY_QUAKE_DELAY + 1;
                 break;
         };
     }else{
         switch(ID){
             case PROTRACTOR_OPEN_SPODS:
                 ActD.SignEngine->set(vR,4);
                 SOUND_PROCTRACTOR_START()
                 break;
             case PROTRACTOR_SCALE_UP:
                 ActD.SignEngine->set(vR,6);
                 SOUND_PROCTRACTOR_START()
                 break;
             case PROTRACTOR_SCALE_DOWN:
                 ActD.SignEngine->set(vR,6);
                 SOUND_PROCTRACTOR_START()
                 break;
             case MECHANIC_BEEB_NATION:
                 if(ActD.mfActive == ActD.Active){
                     SkyQuake.set(ScreenCX,ScreenCY,200,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                     SkyQuakeEnable = 1;
                 };
                 SOUND_MESSIAH();
                 break;
             case MECHANIC_UNVISIBLE:
                 if(ActD.mfActive == ActD.Active){
                     SkyQuake.set(ScreenCX,ScreenCY,80,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                     SkyQuakeEnable = 1;
                 };
                 SOUND_MESSIAH();
                 break;
             case MECHANIC_FIRE_GARDEN:
                 if(ActD.mfActive == ActD.Active){
                     SkyQuake.set(ScreenCX,ScreenCY,50,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                     SkyQuakeEnable = 1;
                 };
                 SOUND_MESSIAH();
                 break;
             case MECHANIC_ITEM_FALL:
                 if(ActD.mfActive == ActD.Active){
                     SkyQuake.set(ScreenCX,ScreenCY,20,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                     SkyQuakeEnable = 1;
                 };
                 SOUND_MESSIAH();
                 break;
             case PROTRACTOR_BEEBOS_DANCE:
                 ActD.SignEngine->set(vR,7);
                 SOUND_PROCTRACTOR_START()
                 break;
             case PROTRACTOR_MOLERIZATOR:
                 ActD.SignEngine->set(vR,9);
                 SOUND_PROCTRACTOR_START()
                 break;
             case PROTRACTOR_PALLADIUM:
                 ActD.SignEngine->set(vR,3);
                 SOUND_PROCTRACTOR_START()
                 break;
             case PROTRACTOR_PREPASSAGE:
                 ActD.SignEngine->set(vR,5);
                 SOUND_PROCTRACTOR_START()
                 break;
             case PROTRACTOR_JESTEROID:
                 ActD.SignEngine->set(vR,8);
                 SOUND_PROCTRACTOR_START()
                 break;
         };
     };
 };
References ActD, ActionDispatcher::Active, ID, LifeTime, MECHANIC_BEEB_NATION, MECHANIC_FIRE_GARDEN, MECHANIC_ITEM_FALL, MECHANIC_UNVISIBLE, ActionDispatcher::mfActive, Next, NULL, Prev, PROTRACTOR_BEEBOS_DANCE, PROTRACTOR_JESTEROID, PROTRACTOR_MOLERIZATOR, PROTRACTOR_OPEN_SPODS, PROTRACTOR_PALLADIUM, PROTRACTOR_PREPASSAGE, PROTRACTOR_SCALE_DOWN, PROTRACTOR_SCALE_UP, ScreenCX, ScreenCY, LandQuake::set(), dastPoly3D::set(), SIGNATOR_DELAY, ActionDispatcher::SignEngine, SKY_QUAKE_DELAY, SKY_QUAKE_DELTA, SKY_QUAKE_RADIUS, SkyQuake, SkyQuakeEnable, SOUND_MESSIAH, SOUND_PROCTRACTOR_START, Time, and vR.
Referenced by ActionDispatcher::AddCoolFunction().
Quant()
void VangerFunctionType::Quant (void)
 {
 //  GeneralObject* p;
     BulletObject* n;
     int i,a;
     Vector vCheck,vTrack;
     VangerUnit* g;
     StuffObject* l;
     StuffObject* ll;
     Time--;
     SoundQuant();
     if(Time <= 0){
         switch(ID){
             case PROTRACTOR_PALLADIUM:
                 SOUND_PR_BARRIER();
                 SkyQuakeEnable3 = 0;
                 break;
             case PROTRACTOR_MOLERIZATOR:
                 if(ActD.pfActive){
                     ActD.pfActive->Molerizator = 0;
                     ActD.pfActive->LastMole = 256;
                 };
                 break;
             case PROTRACTOR_SCALE_DOWN:
             case PROTRACTOR_SCALE_UP:
                 if(ActD.pfActive)
                     ActD.pfActive->scale_size = ActD.pfActive->original_scale_size;
                 SOUND_PR_RESIZE();
                 break;
             case MECHANIC_UNVISIBLE:
                 if(ActD.mfActive)
                     ((VangerUnit*)(ActD.mfActive))->set_draw_mode(NORMAL_DRAW_MODE);
                 SOUND_MES_CLOAK();
                 break;
             case PROTRACTOR_PREPASSAGE:
                 SOUND_PR_FUNCTION_STOP();
                 if(ActD.pfActive){
                     ((VangerUnit*)(ActD.pfActive))->ExternalDraw = 1;
                     ActD.pfActive->switch_analysis(0);
                 };
                 break;
             case MECHANIC_BEEB_NATION:
                 if(ActD.mfActive){
                     ((VangerUnit*)(ActD.mfActive))->convert_to_beeb(NULL);
                     ActD.mfActive->BeebonationFlag = 0;
                 };
                 SOUND_MES_BEEBSOSPY();
                 break;
             case PROTRACTOR_BEEBOS_DANCE:
                 vInsectTarget = Vector(-1,-1,-1);
                 break;
             case PROTRACTOR_OPEN_SPODS:
                 if(!ActD.SpobsDestroy)
                     ActD.XploKeyEnable = 1;
                 break;
             case MECHANIC_ITEM_FALL:
                 if(ActD.mfActive){
                     if(NetworkON){
                         g = (VangerUnit*)(ActD.Tail);
                         while(g){
                             if(g->Visibility == VISIBLE && g->ID == ID_VANGER && g != ActD.mfActive && (g->Status & SOBJ_ACTIVE)){
                                 l = g->DeviceData;
                                 while(l){
                                     ll = (StuffObject*)(l->NextDeviceList);
                                     g->CheckOutDevice(l);
                                     ActD.CheckDevice(l);
                                     aciRemoveItem(&(l->ActIntBuffer));
                                     l->DeviceOut(g->R_curr + Vector(0,0,g->radius*4));
                                     l = ll;
                                 };
                             };
                             g = (VangerUnit*)(g->NextTypeList);
                         };
                     }else{
                         g = (VangerUnit*)(ActD.Tail);
                         while(g){
                             if(g->Visibility == VISIBLE && g->ID == ID_VANGER && g != ActD.mfActive){
                                 l = g->DeviceData;
                                 while(l){
                                     ll = (StuffObject*)(l->NextDeviceList);
                                     g->CheckOutDevice(l);
                                     if(g->Status & SOBJ_ACTIVE){
                                         ActD.CheckDevice(l);
                                         aciRemoveItem(&(l->ActIntBuffer));
                                     };
                                     l->DeviceOut(g->R_curr + Vector(0,0,g->radius*4));
                                     l = ll;
                                 };
                             };
                             g = (VangerUnit*)(g->NextTypeList);
                         };
                     };
                 };
                 break;
         };
         ID = FUNCTION_OFF;
     }else{
         switch(ID){
             case PROTRACTOR_JESTEROID:
                 if(ActD.pfActive && Time < LifeTime - SIGNATOR_DELAY){
                     if(ActD.pfActive->R_curr.z < 400) ActD.pfActive->impulse(Vector(0,0,64),RND(25),0);
                     else ActD.pfActive->impulse(Vector(0,0,0),1,RND(50));
                     SoundFlag |= SoundCopterig;
                 };
                 break;
             case PROTRACTOR_MOLERIZATOR:
                 if(ActD.pfActive){
                     if(Time < LifeTime - SIGNATOR_DELAY){
                         if(!(ActD.pfActive->mole_on)){
                             ActD.pfActive->Molerizator = 1;
                             if(Time < LifeTime - 2){
                                 ActD.pfActive->set_3D(SET_3D_DIRECT_PLACE,vR.x,vR.y,-32,0,-((VangerUnit*)(ActD.pfActive))->Angle,0);
                                 SoundFlag |= SoundCrotrig;
                             };
                         };
                     }else{
                         if(Time == LifeTime - SIGNATOR_DELAY){
                             ActD.pfActive->set_3D(SET_3D_DIRECT_PLACE,vR.x,vR.y,-32,0,-((VangerUnit*)(ActD.pfActive))->Angle,0);
                             for(i = 0;i < MOLERIZATOR_NUM;i++)
                                 MapD.CreateDust(Vector(XCYCL(vR.x + MOLERIZATOR_RADIUS - RND(2*MOLERIZATOR_RADIUS)),YCYCL(vR.y + MOLERIZATOR_RADIUS - RND(2*MOLERIZATOR_RADIUS)),0),MAP_DUST_PROCESS);
                             ActD.pfActive->StartMoleProcess();
                             ActD.pfActive->Molerizator = 1;
                         };
                     };
                 };
                 break;
             case PROTRACTOR_SCALE_UP:
                 if(ActD.pfActive && Time == LifeTime - SIGNATOR_DELAY){
                     ActD.pfActive->scale_size = ActD.pfActive->original_scale_size * 2;
                     SOUND_PR_RESIZE();
                 };
                 break;
             case PROTRACTOR_SCALE_DOWN:
                 if(ActD.pfActive && Time == LifeTime - SIGNATOR_DELAY){
                     ActD.pfActive->scale_size = ActD.pfActive->original_scale_size / 2;
                     SOUND_PR_RESIZE();
                 };
                 break;
             case PROTRACTOR_BEEBOS_DANCE:
                 if(ActD.pfActive && Time == LifeTime - SIGNATOR_DELAY)
                     vInsectTarget = vR;
                 break;
             case PROTRACTOR_PREPASSAGE:
                 if(ActD.pfActive && Time == LifeTime - SIGNATOR_DELAY){
                     SOUND_PR_FUNCTION_START();
                     ((VangerUnit*)(ActD.pfActive))->ExternalDraw = 0;
                     ActD.pfActive->switch_analysis(1);
                     ActD.pfActive->CreateParticleMechos(ActD.pfActive->R_curr,300,LifeTime - SIGNATOR_DELAY);
                 };
                 break;
             case MECHANIC_ITEM_FALL:
                 if(ActD.mfActive && Time == LifeTime - SKY_QUAKE_TIME){
                     if(ActD.mfActive == ActD.Active){
                         SkyQuake2.set(ScreenCX,ScreenCY,20,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                         SkyQuakeEnable2 = 1;
                     };
                 };
                 break;
             case MECHANIC_BEEB_NATION:
                 if(ActD.mfActive){
                     if(Time == LifeTime - SKY_QUAKE_TIME){
                         if(ActD.mfActive == ActD.Active){
                             SkyQuake2.set(ScreenCX,ScreenCY,20,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                             SkyQuakeEnable2 = 1;
                         };
                     }else{
                         if(Time == LifeTime - SKY_QUAKE_DELAY){
                             SOUND_MES_BEEBSOSPY();
                             ActD.mfActive->BeebonationFlag = 1;
                             ((VangerUnit*)(ActD.mfActive))->convert_to_beeb(&(ModelD.ActiveModel(ModelD.FindModel("Bug"))));
                             switch(((VangerUnit*)(ActD.mfActive))->uvsPoint->Pmechos->color){
                                 case 0:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::BODY_GREEN);
                                     break;
                                 case 1:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::BODY_RED);
                                     break;
                                 case 2:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::BODY_BLUE);
                                     break;
                                 case 3:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::BODY_YELLOW);
                                     break;
                                 case 4:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::BODY_CRIMSON);
                                     break;
                                 case 5:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::BODY_GRAY);
                                     break;
                                 case 6:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::ROTTEN_ITEM);
                                     break;
                                 case 7:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::MATERIAL_3);
                                     break;
                                 case 8:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::MATERIAL_1);
                                     break;
                                 case 9:
                                     ((VangerUnit*)(ActD.mfActive))->set_body_color(COLORS_IDS::MATERIAL_0);
                                     break;
                             };
                         };
                     };
                 };
                 break;
             case MECHANIC_UNVISIBLE:
                 if(ActD.mfActive){
                     if(Time == LifeTime - SKY_QUAKE_TIME){
                         if(ActD.mfActive == ActD.Active){
                             SkyQuake2.set(ScreenCX,ScreenCY,20,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                             SkyQuakeEnable2 = 1;
                         };
                     }else{
                         if(Time == LifeTime - SKY_QUAKE_DELAY){
                             SOUND_MES_CLOAK();
                             ((VangerUnit*)(ActD.mfActive))->set_draw_mode(TRANSPARENCY_DRAW_MODE);
                             ObjectDestroy(ActD.mfActive,0);
                         };
                     };
                 };
                 break;
             case MECHANIC_FIRE_GARDEN:
                 if(ActD.mfActive){
                     if(Time > LifeTime - SKY_QUAKE_DELAY){
                         if(Time == LifeTime - SKY_QUAKE_TIME){
                             if(ActD.mfActive == ActD.Active){
                                 SkyQuake2.set(ScreenCX,ScreenCY,20,SKY_QUAKE_RADIUS,SKY_QUAKE_DELTA);
                                 SkyQuakeEnable2 = 1;
                             };
                         };
                     }else{
                         SOUND_MES_FIRE();
                         a = 2*PI * Time / (LifeTime - SKY_QUAKE_DELAY);
                         n = BulletD.CreateBullet();
                         vCheck = Vector(ActD.mfActive->radius*4,0,0) * DBM(a,Z_AXIS);
                         vCheck += ActD.mfActive->R_curr;
                         cycleTor(vCheck.x,vCheck.y);
                         vTrack = Vector(ActD.mfActive->radius*3,0,0) * DBM(a,Z_AXIS);
                         vTrack += ActD.mfActive->R_curr;
                         cycleTor(vTrack.x,vTrack.y);
                         n->CreateBullet(vTrack,vCheck,NULL,&GameBulletData[WD_BULLET_FIRE_GARDEN],NULL);
                     };
                 };
                 break;
             case PROTRACTOR_PALLADIUM:
                 if(ActD.pfActive){
                     vR = ActD.pfActive->R_curr;
                     if(Time == LifeTime - SIGNATOR_DELAY){
                         SOUND_PR_BARRIER();
                         if(ActD.pfActive == ActD.Active){
 //                          SkyQuake3.set(ScreenCX,ScreenCY,PALLADIUM_RADIUS,PALLADIUM_RADIUS);
                             SkyQuakeEnable3 = 1;
                         };
                     };
                 };
                 break;
         };
     };
 };
References aciRemoveItem(), ActD, StuffObject::ActIntBuffer, ActionDispatcher::Active, ModelDispatcher::ActiveModel(), VangerUnit::BeebonationFlag, COLORS_IDS::BODY_BLUE, COLORS_IDS::BODY_CRIMSON, COLORS_IDS::BODY_GRAY, COLORS_IDS::BODY_GREEN, COLORS_IDS::BODY_RED, COLORS_IDS::BODY_YELLOW, BulletD, ActionDispatcher::CheckDevice(), BulletObject::CreateBullet(), BulletList::CreateBullet(), VangerUnit::CreateParticleMechos(), cycleTor(), StuffObject::DeviceOut(), ModelDispatcher::FindModel(), FUNCTION_OFF, g, GameBulletData, ID, ID_VANGER, Object::impulse(), VangerUnit::LastMole, LifeTime, MapD, COLORS_IDS::MATERIAL_0, COLORS_IDS::MATERIAL_1, COLORS_IDS::MATERIAL_3, MECHANIC_BEEB_NATION, MECHANIC_FIRE_GARDEN, MECHANIC_ITEM_FALL, MECHANIC_UNVISIBLE, ActionDispatcher::mfActive, ModelD, Object::mole_on, VangerUnit::Molerizator, MOLERIZATOR_NUM, MOLERIZATOR_RADIUS, NetworkON, StuffObject::NextDeviceList, NORMAL_DRAW_MODE, NULL, ObjectDestroy(), Object::original_scale_size, ActionDispatcher::pfActive, PI, PROTRACTOR_BEEBOS_DANCE, PROTRACTOR_JESTEROID, PROTRACTOR_MOLERIZATOR, PROTRACTOR_OPEN_SPODS, PROTRACTOR_PALLADIUM, PROTRACTOR_PREPASSAGE, PROTRACTOR_SCALE_DOWN, PROTRACTOR_SCALE_UP, Object::radius, RND(), COLORS_IDS::ROTTEN_ITEM, Object::scale_size, ScreenCX, ScreenCY, LandQuake::set(), Object::set_3D(), SET_3D_DIRECT_PLACE, SIGNATOR_DELAY, SKY_QUAKE_DELAY, SKY_QUAKE_DELTA, SKY_QUAKE_RADIUS, SKY_QUAKE_TIME, SkyQuake2, SkyQuakeEnable2, SkyQuakeEnable3, SOBJ_ACTIVE, SOUND_MES_BEEBSOSPY, SOUND_MES_CLOAK, SOUND_MES_FIRE, SOUND_PR_BARRIER, SOUND_PR_FUNCTION_START, SOUND_PR_FUNCTION_STOP, SOUND_PR_RESIZE, SoundCopterig, SoundCrotrig, SoundFlag, SoundQuant(), ActionDispatcher::SpobsDestroy, VangerUnit::StartMoleProcess(), Object::switch_analysis(), UnitList::Tail, Time, TRANSPARENCY_DRAW_MODE, vInsectTarget, VISIBLE, vR, WD_BULLET_FIRE_GARDEN, Vector::x, XCYCL, ActionDispatcher::XploKeyEnable, Vector::y, YCYCL, and Z_AXIS.
Referenced by ActionDispatcher::ClearMessiah(), ActionDispatcher::ClearProtractor(), and ActionDispatcher::FunctionQuant().
SoundQuant()
void VangerFunctionType::SoundQuant (void)
 {
     if(ID <= PROTRACTOR_PREPASSAGE) {
         if(Time <= LifeTime - SIGNATOR_DELAY) {
             SOUND_PROCTRACTOR_STOP();
         }
     };
 };
References ID, LifeTime, PROTRACTOR_PREPASSAGE, SIGNATOR_DELAY, SOUND_PROCTRACTOR_STOP, and Time.
Referenced by Quant().
Member Data Documentation
ID
int VangerFunctionType::ID
Referenced by ActionDispatcher::ClearMessiah(), ActionDispatcher::ClearProtractor(), ActionDispatcher::FunctionQuant(), Init(), ActionDispatcher::NewFunction(), Quant(), and SoundQuant().
LifeTime
int VangerFunctionType::LifeTime
Referenced by Init(), Quant(), and SoundQuant().
Next
VangerFunctionType* VangerFunctionType::Next
Referenced by ActionDispatcher::AddFunction(), ActionDispatcher::ClearMessiah(), ActionDispatcher::ClearProtractor(), ActionDispatcher::Close(), ActionDispatcher::DeleteFunction(), ActionDispatcher::FunctionQuant(), Init(), and ActionDispatcher::NewFunction().
Prev
VangerFunctionType* VangerFunctionType::Prev
Referenced by ActionDispatcher::AddFunction(), ActionDispatcher::DeleteFunction(), and Init().
Time
int VangerFunctionType::Time
Referenced by ActionDispatcher::ClearMessiah(), ActionDispatcher::ClearProtractor(), Init(), ActionDispatcher::NewFunction(), Quant(), and SoundQuant().
vR
Vector VangerFunctionType::vR
Referenced by Init(), and Quant().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp