Vangers: World Struct Reference
World Struct Reference
#include <server.h>
Public Member Functions
World (int ID, int V_SIZE)
~World ()
void attach_player (Player *player)
void detach_player (Player *player)
Object * search_object (int ID)
void add_object (Object *obj)
void move_object (Object *obj)
void delete_object (Object *obj)
int getDistY (int v0, int v1)
int check_visibility (Player *player, Object *object)
int check_visibility (Player *p1, Player *p2)
void process_create (Player *player, Object *obj)
void process_update (Player *player, Object *object)
void process_delete (Object *obj)
void process_set_position (Player *player)
void process_create_inventory (Player *player, Object *obj)
void process_update_inventory (Player *player, Object *obj)
Public Attributes
int ID
int V_SIZE
int number_of_objects
int number_of_y_lists
XTList< Object > * y_lists
XTListAlt< Object > objects
XTListAlt< Player > current_players
World * next
World * prev
XTList< World > * list
Detailed Description
Constructor & Destructor Documentation
World()
World::World (int ID, int V_SIZE)
{
     ID = id;
     number_of_objects = 0;
     y_lists = new XTList<Object>[number_of_y_lists = (V_SIZE = Vsize) >> Y_SHIFT];
     next = prev = 0;
     list = 0;
 }
References ID, list, next, number_of_objects, number_of_y_lists, prev, V_SIZE, y_lists, and Y_SHIFT.
~World()
World::~World ()
               {
     current_players.clear();
     Object *obj;
     while ((obj = objects.first()) != 0) {
         delete_object(obj);
         delete obj;
     }
     delete[] y_lists;
 }
References XTListAlt< Type >::clear(), current_players, delete_object(), XTListAlt< Type >::first(), objects, and y_lists.
Member Function Documentation
add_object()
void World::add_object (Object * obj)
{
     number_of_objects++;
     objects.append(obj);
     XTList<Object> *list = y_lists + ((obj->y >> Y_SHIFT) & (number_of_y_lists - 1));
     list->append(obj);
     obj->list = list;
 }
References XTList< Type >::append(), XTListAlt< Type >::append(), Object::list, list, number_of_objects, number_of_y_lists, objects, Object::y, y_lists, and Y_SHIFT.
Referenced by process_create().
attach_player()
void World::attach_player (Player * player)
{
     player->world = this;
     current_players.append(player);
     player->x = player->y = player->y_half_size_of_screen = 0;
     player->x_prev = player->y_prev = player->y_half_size_of_screen_prev = 0;
     if (!player->status) {
         player->status = GAMING_STATUS;
         player->code_queue.put(Event(PLAYERS_STATUS, player));
         player->game->put_event_for_all(PLAYERS_STATUS, player);
     }
     player->game->put_event_for_all(PLAYERS_WORLD, player);
 }
References XTListAlt< Type >::append(), Player::code_queue, current_players, Player::game, GAMING_STATUS, PLAYERS_STATUS, PLAYERS_WORLD, XQueue< Type >::put(), Game::put_event_for_all(), Player::status, Player::world, Player::x, Player::x_prev, Player::y, Player::y_half_size_of_screen, Player::y_half_size_of_screen_prev, and Player::y_prev.
Referenced by Player::receive().
check_visibility() [1/2]
int World::check_visibility (Player * p1, Player * p2)
{
     if (abs(getDistY(p1->y, p2->y)) <
         std::max(p1->y_half_size_of_screen, p2->y_half_size_of_screen) + PLAYERS_RADIUS)
         return 1;
     return 0;
 }
References getDistY(), max(), PLAYERS_RADIUS, Player::y, and Player::y_half_size_of_screen.
check_visibility() [2/2]
int World::check_visibility (Player * player, Object * object)
{
     if (abs(getDistY(object->y, player->y)) < player->y_half_size_of_screen + object->radius)
         return 1;
     return 0;
 }
References getDistY(), Object::radius, Object::y, Player::y, and Player::y_half_size_of_screen.
Referenced by process_create(), process_create_inventory(), process_set_position(), process_update(), and process_update_inventory().
delete_object()
void World::delete_object (Object * obj)
{
     number_of_objects--;
     objects.remove(obj);
     if (obj->list) {
         obj->list->remove(obj);
         obj->list = 0;
     }
 }
References Object::list, number_of_objects, objects, XTList< Type >::remove(), and XTListAlt< Type >::remove().
Referenced by Player::clear_object_queue(), Player::receive(), Player::send(), and ~World().
detach_player()
void World::detach_player (Player * player)
{
     player->clear_object_queue(1);
     // process_delete below won't place any objects to this player
     current_players.remove(player);
     player->world = 0;
     // Clear Inventory
     Object *obj = player->inventory.first();
     while (obj) {
         process_delete(obj);
         OUT_EVENTS_LOG1(AUTO_DELETE_INVENTORY, obj->ID);
         obj = obj->next;
     }
     // Clear Update Info and Private World's Objects
     int client_ID = player->ID;
     int inv_mask = ~player->client_mask;
     obj = objects.first();
     while (obj) {
         if (CLIENT_ID(obj->ID) == client_ID && PRIVATE_OBJECT(obj->ID)) {
             process_delete(obj);
             OUT_EVENTS_LOG1(AUTO_DELETE, obj->ID);
         } else {
             obj->visibility &= inv_mask;
             obj->last_update &= inv_mask;
             obj->in_queue &= inv_mask;
             obj->send_hide &= inv_mask;
             obj->send_delete &= inv_mask;
         }
         obj = obj->next_alt;
     }
     // Clear Update Info of Inventories
     Player *p = current_players.first();
     while (p) {
         obj = p->inventory.first();
         while (obj) {
             obj->visibility &= inv_mask;
             obj->last_update &= inv_mask;
             obj->in_queue &= inv_mask;
             obj->send_hide &= inv_mask;
             obj->send_delete &= inv_mask;
             obj = obj->next;
         }
         p = p->next_alt;
     }
     player->game->put_event_for_all(PLAYERS_WORLD, player);
 }
References Player::clear_object_queue(), CLIENT_ID, Player::client_mask, current_players, XTList< Type >::first(), XTListAlt< Type >::first(), Player::game, Object::ID, Player::ID, Object::in_queue, Player::inventory, Object::last_update, Object::next, Object::next_alt, Player::next_alt, objects, OUT_EVENTS_LOG1, PLAYERS_WORLD, PRIVATE_OBJECT, process_delete(), Game::put_event_for_all(), XTListAlt< Type >::remove(), Object::send_delete, Object::send_hide, Object::visibility, and Player::world.
Referenced by Game::detach_player(), and Player::receive().
getDistY()
int World::getDistY (int v0, int v1)
{
     int d = v0 - v1;
     int ad = abs(d);
     int dd = V_SIZE - ad;
     if (ad <= dd)
         return d;
     return d < 0 ? d + V_SIZE : d - V_SIZE;
 }
References V_SIZE.
Referenced by check_visibility(), and process_set_position().
move_object()
void World::move_object (Object * obj)
{
     XTList<Object> *new_list = y_lists + ((obj->y >> Y_SHIFT) & (number_of_y_lists - 1));
     if (new_list != obj->list) {
         obj->list->remove(obj);
         new_list->append(obj);
         obj->list = new_list;
     }
 }
References XTList< Type >::append(), Object::list, number_of_y_lists, XTList< Type >::remove(), Object::y, y_lists, and Y_SHIFT.
Referenced by process_update().
process_create()
void World::process_create (Player * player, Object * obj)
{
     add_object(obj);
     Player *p = current_players.first();
     while (p) {
         if (p != player) {
             if (check_visibility(p, obj)) {
                 p->put_object(obj);
                 obj->visibility |= p->client_mask;
                 obj->last_update |= p->client_mask;
             }
         } else {
             if (check_visibility(p, obj))
                 obj->visibility |= p->client_mask;
             obj->last_update |= p->client_mask;
         }
         p = p->next_alt;
     }
 }
References add_object(), check_visibility(), Player::client_mask, current_players, XTListAlt< Type >::first(), Object::last_update, Player::next_alt, Player::put_object(), and Object::visibility.
Referenced by Player::receive().
process_create_inventory()
void World::process_create_inventory (Player * player, Object * obj)
{
     number_of_objects++;
     objects.append(obj);
     player->inventory.append(obj);
     obj->list = &(player->inventory);
     Player *p = current_players.first();
     while (p) {
         if (p != player) {
             if (check_visibility(p, player)) {
                 p->put_object(obj);
                 obj->last_update |= p->client_mask;
             }
         } else
             obj->last_update |= p->client_mask;
         p = p->next_alt;
     }
 }
References XTList< Type >::append(), XTListAlt< Type >::append(), check_visibility(), Player::client_mask, current_players, XTListAlt< Type >::first(), Player::inventory, Object::last_update, Object::list, Player::next_alt, number_of_objects, objects, and Player::put_object().
Referenced by Player::receive().
process_delete()
void World::process_delete (Object * obj)
{
     Player *p = current_players.first();
     while (p) {
         obj->send_delete |= p->client_mask;
         p->put_object(obj);
         p = p->next_alt;
     }
 }
References Player::client_mask, current_players, XTListAlt< Type >::first(), Player::next_alt, Player::put_object(), and Object::send_delete.
Referenced by detach_player(), and Player::receive().
process_set_position()
void World::process_set_position (Player * player)
{
     Object *obj;
     unsigned int mask = player->client_mask;
     if (player->y_half_size_of_screen_prev) { // not a first set_position
         int update_y0, update_y1;
         int hide_y0, hide_y1;
         if (getDistY(player->y, player->y_prev) > 0) {
             update_y0 =
                 ((player->y_prev + player->y_half_size_of_screen_prev) & (V_SIZE - 1)) >> Y_SHIFT;
             update_y1 = ((player->y + player->y_half_size_of_screen) & (V_SIZE - 1)) >> Y_SHIFT;
             hide_y0 =
                 ((player->y_prev - player->y_half_size_of_screen_prev) & (V_SIZE - 1)) >> Y_SHIFT;
             hide_y1 = ((player->y - player->y_half_size_of_screen) & (V_SIZE - 1)) >> Y_SHIFT;
         } else {
             update_y1 =
                 ((player->y_prev - player->y_half_size_of_screen_prev) & (V_SIZE - 1)) >> Y_SHIFT;
             update_y0 = ((player->y - player->y_half_size_of_screen) & (V_SIZE - 1)) >> Y_SHIFT;
             hide_y1 =
                 ((player->y_prev + player->y_half_size_of_screen_prev) & (V_SIZE - 1)) >> Y_SHIFT;
             hide_y0 = ((player->y + player->y_half_size_of_screen) & (V_SIZE - 1)) >> Y_SHIFT;
         }
         update_y1 = (update_y1 + 1) & (number_of_y_lists - 1);
         hide_y1 = (hide_y1 + 1) & (number_of_y_lists - 1);
         // Check for update
         for (int y = update_y0; y != update_y1; y = (y + 1) & (number_of_y_lists - 1)) {
             obj = y_lists[y].first();
             while (obj) {
                 if (!(obj->visibility & mask) && check_visibility(player, obj)) {
                     obj->visibility |= mask;
                     if (!NON_STATIC(obj->ID)) {
                         if (!(obj->last_update & mask)) {
                             player->put_object(obj);
                             obj->last_update |= mask;
                         }
                     } else {
                         player->put_object(obj);
                         obj->send_hide &= ~mask;
                         obj->last_update |= mask;
                     }
                 }
                 obj = obj->next;
             }
         }
         // Check for hide
         for (int y = hide_y0; y != hide_y1; y = (y + 1) & (number_of_y_lists - 1)) {
             obj = y_lists[y].first();
             while (obj) {
                 if (obj->visibility & mask && !check_visibility(player, obj)) {
                     obj->visibility &= ~mask;
                     if (NON_STATIC(obj->ID)) {
                         player->put_object(obj);
                         obj->send_hide |= mask;
                     }
                 }
                 obj = obj->next;
             }
         }
     } else {
         // Check for update
         int update_y0 = ((player->y - player->y_half_size_of_screen) & (V_SIZE - 1)) >> Y_SHIFT;
         int update_y1 = ((player->y + player->y_half_size_of_screen) & (V_SIZE - 1)) >> Y_SHIFT;
         for (int y = update_y0; y != update_y1; y = (y + 1) & (number_of_y_lists - 1)) {
             obj = y_lists[y].first();
             while (obj) {
                 if (check_visibility(player, obj)) {
                     if (!NON_STATIC(obj->ID)) {
                         if (!(obj->last_update & mask)) {
                             player->put_object(obj);
                             obj->last_update |= mask;
                         }
                     } else {
                         if (!((obj->last_update | obj->visibility) & mask)) {
                             player->put_object(obj);
                             obj->send_hide &= ~mask;
                             obj->last_update |= mask;
                         }
                     }
                     obj->visibility |= mask;
                 } else
                     obj->visibility &= ~mask;
                 obj = obj->next;
             }
         }
     }
     player->x_prev = player->x;
     player->y_prev = player->y;
     player->y_half_size_of_screen_prev = player->y_half_size_of_screen;
     // Checking inventories
     int send_position = IS_PAST(player->last_sent_position + 5000) ? 1 : 0;
     Player *p = current_players.first();
     while (p) {
         if (p != player)
             if (check_visibility(p, player)) {
                 // All's inventories to Me
                 obj = p->inventory.first();
                 while (obj) {
                     if (!(obj->last_update & player->client_mask)) {
                         player->put_object(obj);
                         obj->last_update |= player->client_mask;
                     }
                     obj = obj->next;
                 }
                 // My inventory to All
                 obj = player->inventory.first();
                 while (obj) {
                     if (!(obj->last_update & p->client_mask)) {
                         p->put_object(obj);
                         obj->last_update |= p->client_mask;
                     }
                     obj = obj->next;
                 }
             } else if (send_position) {
                 p->code_queue.put(Event(PLAYERS_POSITION, player));
                 send_position = 2;
             }
         p = p->next_alt;
     }
     if (send_position == 2)
         player->last_sent_position = SDL_GetTicks();
 }
References check_visibility(), Player::client_mask, Player::code_queue, current_players, XTList< Type >::first(), XTListAlt< Type >::first(), getDistY(), Object::ID, Player::inventory, IS_PAST, Player::last_sent_position, Object::last_update, Object::next, Player::next_alt, NON_STATIC, number_of_y_lists, PLAYERS_POSITION, XQueue< Type >::put(), Player::put_object(), Object::send_hide, V_SIZE, Object::visibility, Player::x, Player::x_prev, Player::y, Player::y_half_size_of_screen, Player::y_half_size_of_screen_prev, y_lists, Player::y_prev, and Y_SHIFT.
Referenced by Player::receive().
process_update()
void World::process_update (Player * player, Object * object)
{
     obj->last_update = 0;
     Player *p = current_players.first();
     if (NON_STATIC(obj->ID)) {
         move_object(obj);
         while (p) {
             if (check_visibility(p, obj)) {
                 if (p != player)
                     p->put_object(obj);
                 obj->last_update |= p->client_mask;
                 obj->visibility |= p->client_mask;
                 obj->send_hide &= ~(p->client_mask);
             } else {
                 if (obj->visibility & p->client_mask) {
                     p->put_object(obj); // Hide
                     obj->send_hide |= p->client_mask;
                 }
                 obj->visibility &= ~(p->client_mask);
                 if (p == player)
                     obj->last_update |= p->client_mask;
             }
             p = p->next_alt;
         }
     } else {
         while (p) {
             if (check_visibility(p, obj)) {
                 if (p != player)
                     p->put_object(obj);
                 obj->last_update |= p->client_mask;
                 obj->visibility |= p->client_mask;
             } else {
                 obj->visibility &= ~(p->client_mask);
                 if (p == player)
                     obj->last_update |= p->client_mask;
             }
             p = p->next_alt;
         }
     }
 }
References check_visibility(), Player::client_mask, current_players, XTListAlt< Type >::first(), Object::ID, Object::last_update, move_object(), Player::next_alt, NON_STATIC, Player::put_object(), Object::send_hide, and Object::visibility.
Referenced by Player::receive().
process_update_inventory()
void World::process_update_inventory (Player * player, Object * obj)
{
     obj->last_update = 0;
     Player *p = current_players.first();
     while (p) {
         if (p != player) {
             if (check_visibility(p, player)) {
                 p->put_object(obj);
                 obj->last_update |= p->client_mask;
             }
         } else
             obj->last_update |= p->client_mask;
         p = p->next_alt;
     }
 }
References check_visibility(), Player::client_mask, current_players, XTListAlt< Type >::first(), Object::last_update, Player::next_alt, and Player::put_object().
Referenced by Player::receive().
search_object()
Object * World::search_object (int ID)
{
     return objects.search(ID);
 }
References ID, objects, and XTListAlt< Type >::search().
Referenced by Player::receive().
Member Data Documentation
current_players
XTListAlt<Player> World::current_players
Referenced by attach_player(), detach_player(), process_create(), process_create_inventory(), process_delete(), process_set_position(), process_update(), process_update_inventory(), and ~World().
ID
int World::ID
Referenced by Server::report(), search_object(), Player::send(), and World().
list
XTList<World>* World::list
Referenced by add_object(), and World().
next
World* World::next
Referenced by Game::get_object_ID_offsets(), Server::report(), and World().
number_of_objects
int World::number_of_objects
Referenced by add_object(), delete_object(), process_create_inventory(), Server::report(), and World().
number_of_y_lists
int World::number_of_y_lists
Referenced by add_object(), move_object(), process_set_position(), and World().
objects
XTListAlt<Object> World::objects
Referenced by add_object(), delete_object(), detach_player(), Game::get_object_ID_offsets(), process_create_inventory(), search_object(), and ~World().
prev
World* World::prev
Referenced by World().
V_SIZE
int World::V_SIZE
Referenced by getDistY(), process_set_position(), Player::receive(), and World().
y_lists
XTList<Object>* World::y_lists
Referenced by add_object(), move_object(), process_set_position(), World(), and ~World().
The documentation for this struct was generated from the following files:
server/server.h
server/server.cpp