Vangers: ClefList Struct Reference
ClefList Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void Free (void)
void FreeUnit (GeneralObject *p)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Quant (void)
virtual void NetEvent (int type, int id)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Public Attributes
ClefObject * Data
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
Free()
void ClefList::Free (void) virtual
Reimplemented from UnitListType.
 {
     UnitBaseListType::Free();
     if(Data) delete[] Data;
 };
References Data, and UnitListType::Free().
Referenced by GeneralSystemClose().
FreeUnit()
void ClefList::FreeUnit (GeneralObject * p) virtual
Reimplemented from UnitListType.
 {
     DisconnectTypeList(p);
 };
References UnitBaseListType::DisconnectTypeList().
Init()
void ClefList::Init (void) virtual
Reimplemented from UnitListType.
 {
     int i;
     if(CurrentWorld == WORLD_HMOK){
         Data = new ClefObject[MAX_CLEF_OBJECT];
         for(i = 0;i < MAX_CLEF_OBJECT;i++){
             Data[i].Init();
             Data[i].CreateClef();
             ConnectTypeList(&Data[i]);
         };
     }else Data = NULL;
 };
References UnitBaseListType::ConnectTypeList(), ClefObject::CreateClef(), CurrentWorld, Data, ClefObject::Init(), MAX_CLEF_OBJECT, NULL, and WORLD_HMOK.
Referenced by GeneralSystemOpen().
Member Data Documentation
Data
ClefObject* ClefList::Data
Referenced by Free(), and Init().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp