Vangers: EnterCenter Struct Reference
EnterCenter Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Close (void)
SensorDataType * GetCenter (void)
void PutCenter (EnterEngine *p)
SensorDataType * GetNearCenter (Vector &v)
EnterEngine * GetEnterCenter (Vector &v)
void LockedCenter (EnterEngine *p)
void ActiveCenter (void)
void Resort (void)
Public Attributes
int MaxEnter
int NumEnter
EnterEngine ** Data
int * Lock
uvsTarget * Owner
EnterEngine ** ListData
Detailed Description
Member Function Documentation
ActiveCenter()
void EnterCenter::ActiveCenter (void) inline
 { Data[NumEnter]->Active(); };
References EnterEngine::Active(), Data, and NumEnter.
Close()
void EnterCenter::Close (void)
 {
     if(MaxEnter){
         delete[] Data;
         delete[] ListData;
     };
 };
References Data, ListData, and MaxEnter.
GetCenter()
SensorDataType * EnterCenter::GetCenter (void)
 {
     if(NumEnter == 0)
         ErrH.Abort("Bad get Center");
     NumEnter--;
     if(NumEnter == 0) (*Lock) = 1;
 //  Data[NumEnter]->Active();
     return Data[NumEnter]->ActionLink;
 };
References XErrorHandler::Abort(), EnterEngine::ActionLink, Data, ErrH, and NumEnter.
GetEnterCenter()
EnterEngine * EnterCenter::GetEnterCenter (Vector & v)
 {
     Vector vCheck;
     int d,dm,i;
     EnterEngine* p;
     vCheck = Vector(getDistX(v.x,ListData[0]->ActionLink->R_curr.x),getDistY(v.y,ListData[0]->ActionLink->R_curr.y),0);
     dm = d = vCheck.x * vCheck.x + vCheck.y * vCheck.y;
     p = ListData[0];
     for(i = 1;i < MaxEnter;i++){
         vCheck = Vector(getDistX(v.x,ListData[i]->ActionLink->R_curr.x),getDistY(v.y,ListData[i]->ActionLink->R_curr.y),0);
         d = vCheck.x * vCheck.x + vCheck.y * vCheck.y;
         if(d < dm){
             dm = d;
             p = ListData[i];
         };
     };
     return p;
 };
References EnterEngine::ActionLink, getDistX(), getDistY(), ListData, MaxEnter, GeneralObject::R_curr, Vector::x, and Vector::y.
Referenced by GetNearCenter().
GetNearCenter()
SensorDataType * EnterCenter::GetNearCenter (Vector & v)
 {
     EnterEngine* p;
     p = NULL;
     if(NumEnter == 0) p =  Data[RND(NumEnter)];
     else  p = GetEnterCenter(v);
     return p->ActionLink;
 };
References EnterEngine::ActionLink, Data, GetEnterCenter(), NULL, NumEnter, and RND().
LockedCenter()
void EnterCenter::LockedCenter (EnterEngine * p)
 {
     int i;
     if(NumEnter == 0)
         ErrH.Abort("Bad Locked Num Enter");
     for(i = 0;i < NumEnter;i++)
         if(Data[i] == p) break;
     if(i == NumEnter)
         ErrH.Abort("Bad LockedCenter");
     NumEnter--;
     if(NumEnter == 0) (*Lock) = 1;
     else Data[i] = Data[NumEnter];
 };
References XErrorHandler::Abort(), Data, ErrH, and NumEnter.
Referenced by ElevatorEngine::Quant(), EscaveEngine::Quant(), ImpulseEscave::Quant(), and ImpulseSpot::Quant().
Open()
void EnterCenter::Open (Parser & in)
 {
     int i,j,t;
     char* n;
     uvsEscave* pe;
     uvsSpot* ps;
     in.search_name("MaxEnter");
     MaxEnter = in.get_int();
     NumEnter = 0;
     if(MaxEnter){
         Data = new EnterEngine*[MaxEnter];
         ListData = new EnterEngine*[MaxEnter];
         in.search_name("uvsObjectType");
         t = in.get_int();
         in.search_name("uvsObjectName");
         n = in.get_name();
         Lock = NULL;
         if(t == 0){
             pe = (uvsEscave*)EscaveTail;
             while(pe){
                 if(!strcmp(pe->name,n)){
                     Lock = &(pe->locked);
                     Owner = pe;
                     break;
                 };
                 pe = (uvsEscave*)(pe -> next);
             };
             if(!Lock)
                 ErrH.Abort("Bad Escave Center Name");
         }else{
             ps = (uvsSpot*)SpotTail;
             while(ps){
                 if(!strcmp(ps->name,n)){
                     Lock = &(ps->locked);
                     Owner = ps;
                     break;
                 };
                 ps = (uvsSpot*)(ps -> next);
             };
             if(!Lock)
                 ErrH.Abort("Bad Spot Center Name");
         };
         Owner->unitPtr.EnterT = this;
         for(i = 0;i < MaxEnter;i++){
             in.search_name("SensorName");
             n = in.get_name();
             for(j = 0;j < SnsTableSize;j++){
                 if(!strcmp(SensorObjectData[j]->Name,n)){
     //              if(SensorObjectData[j]->Owner->Type != EngineTypeList::ELEVATOR && SensorObjectData[j]->Owner->Type != EngineTypeList::ESCAVE)
     //                  ErrH.Abort("Bad Enter Sensor Name");
                     ListData[i] = (EnterEngine*)(SensorObjectData[j]->Owner);
                     PutCenter((EnterEngine*)(SensorObjectData[j]->Owner));
                     ((EnterEngine*)(SensorObjectData[j])->Owner)->Owner = this;
                     break;
                 };
             };
         };
     };
 };
References Data, EscaveTail, Parser::get_int(), Parser::get_name(), ListData, Lock, uvsEscave::locked, MaxEnter, uvsEscave::name, NULL, NumEnter, Owner, and Parser::search_name().
PutCenter()
void EnterCenter::PutCenter (EnterEngine * p)
 {
     if(NumEnter == 0) (*Lock) = 0;
     else if(NumEnter >= MaxEnter)
         ErrH.Abort("Bad put Center");
     Data[NumEnter] = p;
     NumEnter++;
 };
References XErrorHandler::Abort(), Data, ErrH, MaxEnter, and NumEnter.
Referenced by ElevatorEngine::Quant(), EscaveEngine::Quant(), ImpulseEscave::Quant(), and ImpulseSpot::Quant().
Resort()
void EnterCenter::Resort (void)
 {
     int i,t;
     EnterEngine* b[10];
     t = RND(NumEnter);
     for(i = 0;i < NumEnter;i++) b[i] = ListData[(t + i) % NumEnter];
     for(i = 0;i < NumEnter;i++) Data[i] = b[i];
 };
References Data, ListData, NumEnter, and RND().
Member Data Documentation
Data
EnterEngine** EnterCenter::Data
Referenced by ActiveCenter(), Close(), GetCenter(), GetNearCenter(), LockedCenter(), Open(), PutCenter(), and Resort().
ListData
EnterEngine** EnterCenter::ListData
Referenced by Close(), FindDoor(), GetEnterCenter(), Open(), and Resort().
Lock
int* EnterCenter::Lock
Referenced by Open().
MaxEnter
int EnterCenter::MaxEnter
Referenced by Close(), FindDoor(), GetEnterCenter(), Open(), and PutCenter().
NumEnter
int EnterCenter::NumEnter
Referenced by ActiveCenter(), GetCenter(), GetNearCenter(), LockedCenter(), Open(), PutCenter(), and Resort().
Owner
uvsTarget* EnterCenter::Owner
Referenced by Open().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp