Vangers: iAVIElement Struct Reference
iAVIElement Struct Reference
#include <iscreen.h>
Public Member Functions
void load (void)
void load_shape (void)
void free_shape (void)
void free (void)
void change_avi (char *fname)
void init_size (void)
int check_visible (void)
void init_name (char *p)
void add_name (const char *ptr)
void next_avi (void)
void prev_avi (void)
void free_mem (void)
iAVIElement (void)
Public Member Functions inherited from iScreenElement
void load_data (void)
void free_data (void)
void redraw (int x, int y, int sc, int sm, int hide_mode)
void scale_quant (void)
int check_xy (int x, int y)
void copy (iScreenElement *dest)
void init_align (void)
void change_terrainNum (int terr)
iScreenElement (void)
~iScreenElement (void)
Public Member Functions inherited from iListElement
void init_id (const char *p)
iListElement (void)
~iListElement (void)
Public Attributes
char * avi_name
void * data
iList * avi_ids
int border_type
int border_level
int border_null_level
int border_size
char * border_shape_file
char * border_shape
ibsObject * ibs
unsigned char * palBuf
short ShSizeX
short ShSizeY
Public Attributes inherited from iScreenElement
short ID
short type
short lX
short lY
short nlX
short nlY
short SizeX
short SizeY
int scale
int scale_delta
int terrainNum
int align_x
int align_y
int align_x_offs
int align_y_offs
int flags
int null_level
iListElement * owner
Public Attributes inherited from iListElement
std::string ID_ptr
int name_len
iListElement * prev
iListElement * next
Detailed Description
Constructor & Destructor Documentation
iAVIElement()
iAVIElement::iAVIElement (void)
 {
     border_type = AVI_FLAT_BORDER;
     border_size = AVI_DEF_BORDER_SIZE;
     border_level = 0;
     border_null_level = 0;
     avi_ids = new iList;
     avi_name = new char[256];
     memset(avi_name, 0, sizeof(char));
     border_shape_file = NULL;
     palBuf = NULL;
     ibs = NULL;
     type = I_AVI_ELEM;
 }
References AVI_DEF_BORDER_SIZE, AVI_FLAT_BORDER, avi_ids, avi_name, border_level, border_null_level, border_shape_file, border_size, border_type, I_AVI_ELEM, ibs, NULL, palBuf, and iScreenElement::type.
Member Function Documentation
add_name()
void iAVIElement::add_name (const char * ptr)
 {
     iListElement* p = new iListElement;
     p -> init_id(ptr);
     avi_ids -> connect(p);
     strcpy(avi_name,avi_ids->first->ID_ptr.c_str());
 }
References avi_ids, avi_name, iList::first, iListElement::ID_ptr, iListElement::iListElement(), and iListElement::init_id().
change_avi()
void iAVIElement::change_avi (char * fname)
 {
     free();
     if (avi_name!=fname) {
         strcpy(avi_name,fname);
     }
     load();
 }
References avi_name, free(), and load().
Referenced by next_avi(), and prev_avi().
check_visible()
int iAVIElement::check_visible (void)
 {
     iScreen* scr;
     iScreenObject* obj;
     obj = (iScreenObject*)owner;
     scr = (iScreen*)obj -> owner;
     if(iScreenOffs != scr -> ScreenOffs) return 0;
     return 1;
 }
References iScreenOffs, and iScreenElement::owner.
free()
void iAVIElement::free (void)
 {
     if(flags & EL_DATA_LOADED){
         AVIstop(data);
         AVIclose(data);
         //delete palBuf;
         palBuf = NULL;
         flags ^= EL_DATA_LOADED;
     }
 }
References AVIclose(), AVIstop(), data, EL_DATA_LOADED, iScreenElement::flags, NULL, and palBuf.
Referenced by change_avi(), free_mem(), and free_shape().
free_mem()
void iAVIElement::free_mem (void)
 {
     iListElement* p,*p1;
     p = avi_ids -> last;
     while(p){
         p1 = p -> prev;
         delete p;
         p = p1;
     }
     delete avi_ids;
     delete[] avi_name;
     if(ibs)
         delete ibs;
     free();
     if(border_shape_file)
         delete border_shape_file;
     //if(palBuf)
     //  delete palBuf;
     free_shape();
 }
References avi_ids, avi_name, border_shape_file, free(), free_shape(), ibs, and iListElement::prev.
free_shape()
void iAVIElement::free_shape (void)
 {
     if(flags & EL_BORDER_INIT){
         if(border_shape)
             delete border_shape;
         if(ibs)
             ibs -> free();
         flags ^= EL_BORDER_INIT;
     }
 }
References border_shape, EL_BORDER_INIT, iScreenElement::flags, free(), and ibs.
Referenced by free_mem().
init_name()
void iAVIElement::init_name (char * p)
 {
     strcpy(avi_name,ptr);
 }
References avi_name.
init_size()
void iAVIElement::init_size (void)
 {
     if(flags & EL_DATA_LOADED){
         SizeX = AVIwidth(data);
         SizeY = AVIheight(data);
     }
 }
References AVIheight(), AVIwidth(), data, EL_DATA_LOADED, iScreenElement::flags, iScreenElement::SizeX, and iScreenElement::SizeY.
load()
void iAVIElement::load (void)
 {
     if(!(flags & EL_DATA_LOADED)){
         flags &= ~AVI_STOPPED;
         //palBuf = new unsigned char[768];
         iResBuf -> init();
         *iResBuf < iVideoPathDefault < avi_name;
         if(!AVIopen(iResBuf -> address(),AVI_NOTIMER | AVI_NODRAW | AVI_LOOPING | AVI_NOPALETTE,0,&data)){
             iResBuf -> init();
             *iResBuf < iVideoPath < avi_name;
             if(!AVIopen(iResBuf -> address(),AVI_NOTIMER | AVI_NODRAW | AVI_LOOPING | AVI_NOPALETTE,0,&data)){
                 iResBuf -> init();
                 *iResBuf < iVideoPath < iEMPTY_AVI;
                 if(!AVIopen(iResBuf -> address(),AVI_NOTIMER | AVI_NODRAW | AVI_LOOPING | AVI_NOPALETTE,0,&data))
                     ErrH.Abort(AVInotFound);
             }
         }
         AVIplay(data,0,0);
         //pal_tmp = (char*)AVIGetPalette(data);
         palBuf=(unsigned char*)AVIGetPalette(data);
         //memcpy(palBuf,pal_tmp,768);
         //std::cout<<"iAVIElement::load"<<std::endl;
         flags |= EL_DATA_LOADED;
     }
 }
References XErrorHandler::Abort(), AVI_LOOPING, avi_name, AVI_NODRAW, AVI_NOPALETTE, AVI_NOTIMER, AVI_STOPPED, AVIGetPalette(), AVInotFound, AVIopen(), AVIplay(), data, EL_DATA_LOADED, ErrH, iScreenElement::flags, iEMPTY_AVI, iResBuf, iVideoPath, iVideoPathDefault, and palBuf.
Referenced by change_avi(), and load_shape().
load_shape()
void iAVIElement::load_shape (void)
 {
     XStream fh;
     if(!(flags & EL_BORDER_INIT)){
         if(border_shape_file){
             fh.open(border_shape_file);
             fh > ShSizeX > ShSizeY;
             if(ShSizeX != SizeX || ShSizeY != SizeY)
                 ErrH.Abort("Bad AVI border shape file...",XERR_USER,0,ID_ptr.c_str());
             border_shape = new char[ShSizeX * ShSizeY];
             fh.read(border_shape,ShSizeX * ShSizeY);
             fh.close();
             smooth_shape(ShSizeX,ShSizeY,(unsigned char*)border_shape);
         }
         else {
             ShSizeX = 0;
             ShSizeY = 0;
             border_shape = NULL;
             if(ibs){
                 ibs -> load();
             }
         }
         flags |= EL_BORDER_INIT;
     }
 }
References XErrorHandler::Abort(), border_shape, border_shape_file, XStream::close(), EL_BORDER_INIT, ErrH, iScreenElement::flags, ibs, iListElement::ID_ptr, load(), NULL, XStream::open(), XStream::read(), ShSizeX, ShSizeY, iScreenElement::SizeX, iScreenElement::SizeY, smooth_shape(), and XERR_USER.
next_avi()
void iAVIElement::next_avi (void)
 {
     int i;
     iListElement* p = avi_ids -> first;
     avi_ids -> index ++;
     if(avi_ids -> index >= avi_ids -> Size)
         avi_ids -> index = 0;
     for(i = 0; i < avi_ids -> index; i ++){
         p = p -> next;
     }
     change_avi((char *)p->ID_ptr.c_str());
 }
References avi_ids, change_avi(), iListElement::ID_ptr, and iListElement::next.
prev_avi()
void iAVIElement::prev_avi (void)
 {
     int i;
     iListElement* p = avi_ids -> first;
     avi_ids -> index --;
     if(avi_ids -> index < 0)
         avi_ids -> index = avi_ids -> Size - 1;
     for(i = 0; i < avi_ids -> index; i ++){
         p = p -> next;
     }
     change_avi((char *)p->ID_ptr.c_str());
 }
References avi_ids, change_avi(), iListElement::ID_ptr, and iListElement::next.
Member Data Documentation
avi_ids
iList* iAVIElement::avi_ids
Referenced by add_name(), free_mem(), iAVIElement(), next_avi(), and prev_avi().
avi_name
char* iAVIElement::avi_name
Referenced by add_name(), change_avi(), free_mem(), iAVIElement(), init_name(), and load().
border_level
int iAVIElement::border_level
Referenced by iAVIElement().
border_null_level
int iAVIElement::border_null_level
Referenced by iAVIElement().
border_shape
char* iAVIElement::border_shape
Referenced by free_shape(), and load_shape().
border_shape_file
char* iAVIElement::border_shape_file
Referenced by free_mem(), iAVIElement(), and load_shape().
border_size
int iAVIElement::border_size
Referenced by iAVIElement().
border_type
int iAVIElement::border_type
Referenced by iAVIElement().
data
void* iAVIElement::data
Referenced by free(), init_size(), and load().
ibs
ibsObject* iAVIElement::ibs
Referenced by free_mem(), free_shape(), iAVIElement(), and load_shape().
palBuf
unsigned char* iAVIElement::palBuf
Referenced by free(), iAVIElement(), and load().
ShSizeX
short iAVIElement::ShSizeX
Referenced by load_shape().
ShSizeY
short iAVIElement::ShSizeY
Referenced by load_shape().
The documentation for this struct was generated from the following files:
src/iscreen/iscreen.h
src/iscreen/iscreen.cpp