Vangers: PrmFile Struct Reference
PrmFile Struct Reference
#include <univang.h>
Public Member Functions
void init (const char *name)
char * getAtom (void)
void finit (void)
PrmFile (void)
void init (const char *name)
char * getAtom (void)
void finit (void)
Public Attributes
char * buf
int len
int index
Detailed Description
Constructor & Destructor Documentation
PrmFile()
PrmFile::PrmFile (void) inline
 { buf = NULL; len = index = 0;}
References buf, index, len, and NULL.
Member Function Documentation
finit() [1/2]
void PrmFile::finit (void) inline
                      {
         delete[] buf;
     }
References buf.
Referenced by GetKeepSpace(), and KeepCleanUp().
finit() [2/2]
void PrmFile::finit (void) inline
                      {
         delete[] buf;
     }
References buf.
getAtom() [1/2]
char * PrmFile::getAtom (void)
{
     char* p = buf + index;
     while(index < len && !(*p)) p++, index++;
     if(index == len) return NULL;
     char* ret = p;
     while(index < len && *p) p++, index++;
     return ret;
 }
References buf, index, len, and NULL.
Referenced by GetKeepSpace(), and KeepCleanUp().
getAtom() [2/2]
char* PrmFile::getAtom (void)
init() [1/2]
void PrmFile::init (const char * name)
{
     Parser* prs = new Parser(name); // TODO memory leak
     len = prs -> length();
     buf = prs -> address();
     int i = 0,mode = 1;
     char c;
     while(i < len){
         c = buf[i];
         if(c == '\"'){
             buf[i++] = '\0';
             while(i < len){
                 if(buf[i] == '\"') break;
                 i++;
                 }
             if(i == len) ErrH.Abort("Wrong PRM format, second <\"> is absent");
             else buf[i] = '\0';
             }
         else
             if(c == ' ' || c == '\t' || c == '\r' || c == ',' || c == '\n') buf[i] = '\0';
         i++;
         }
     i = 0;
     while(i < len){
         c = buf[i];
         if(mode){ if(c == '/' && buf[i + 1] == '*'){ buf[i] = '\0'; mode = 0; } }
         else {
             if(c == '*' && buf[i + 1] == '/'){ buf[i] = buf[i + 1] = '\0'; i++; mode = 1; }
             else if(c != '\n') buf[i] = '\0';
             }
         i++;
         }
     index = 0;
 }
References XErrorHandler::Abort(), buf, ErrH, index, and len.
Referenced by GetKeepSpace(), KeepCleanUp(), and ReadPriceList().
init() [2/2]
void PrmFile::init (const char * name)
Member Data Documentation
buf
char * PrmFile::buf
Referenced by finit(), getAtom(), init(), and PrmFile().
index
int PrmFile::index
Referenced by getAtom(), init(), and PrmFile().
len
int PrmFile::len
Referenced by getAtom(), init(), and PrmFile().
The documentation for this struct was generated from the following files:
src/terra/vmap.cpp
src/uvs/univang.h
src/uvs/univang.cpp