Vangers: DiagenDispatcher Struct Reference
DiagenDispatcher Struct Reference
#include <diagen.h>
Public Member Functions
DiagenDispatcher (void)
void init (void)
dgRoom * seekR (const char *_name, int onlyfirstchar=0)
void involveQ (dgAtom *atom)
void restHandle (dgMolecule *m)
char * getQprefix (void)
char * getQpostfix (void)
char * getQempty (void)
char * getQend (void)
char * getQblock (void)
char * getQout (void)
char * getQdead (void)
void startSession (const char *rname)
void endSession (void)
void checkSession (const char *rname)
char * getNextPhrase (void)
char * getAnswer (char *subject)
char * findQfirst (void)
char * findQnext (void)
int isEnd (void)
void save (XStream &ff)
void load (XStream &ff)
char * getWorldName (char *name)
char * getInvText (int type, int id, char *from=NULL, char *to=NULL)
Public Attributes
dgRoom * rtail
dgRoom * currentR
dgRoom * lastR
dgQuery * cqp
int cVind
int endSessionLog
int eStatus
int bStatus
int zStatus
int sStatus
dgAtom * varAtom
dgRoom * invR
char * CycleName [2][3][3]
char * SecretWname [2][DG_SECRETW_MAX]
Detailed Description
Constructor & Destructor Documentation
DiagenDispatcher()
DiagenDispatcher::DiagenDispatcher (void) inline
{
         rtail = NULL; currentR = NULL;
         varAtom = NULL;
         lastR = NULL;
         endSessionLog = 0;
         invR = NULL;
         eStatus = bStatus = zStatus = sStatus = 0;
     }
References bStatus, currentR, endSessionLog, eStatus, invR, lastR, NULL, rtail, sStatus, varAtom, and zStatus.
Member Function Documentation
checkSession()
void DiagenDispatcher::checkSession (const char * rname)
 {
     if(currentR) endSession();
     dgRoom* r = seekR(rname);
     checkStatus = 1;
     (currentR = r) -> startSession();
     while(!dgAbortStatus && !endSessionLog) getNextPhrase();
     endSession();
     checkStatus = 0;
 }
References currentR, endSession(), and seekR().
Referenced by startSession().
endSession()
void DiagenDispatcher::endSession (void)
 {
     if(currentR){
 #ifdef DIAGEN_TEST
         if(!checkStatus) std::cout << "\n" << strLine << " SESSION IN " << cp1251_to_utf8(currentR -> roomName) << " finished" << strLine << "\n\n";
 #endif
         currentR -> endSession();
         if(!checkStatus) lastR = currentR;
         currentR = NULL;
         }
 }
References currentR.
Referenced by checkSession(), and startSession().
findQfirst()
char * DiagenDispatcher::findQfirst (void)
 {
     if(varAtom)
         return Convert(varAtom -> variants[cVind = 0]);
     else {
         if(!currentR) return NULL;
         cqp = currentR -> qVtail;
         return cqp ? Convert(cqp -> subj) : NULL;
         }
 }
References Convert(), cqp, currentR, cVind, NULL, and varAtom.
findQnext()
char * DiagenDispatcher::findQnext (void)
 {
     if(varAtom){
         if(++cVind >= varAtom -> nvariant) return NULL;
         return Convert(varAtom -> variants[cVind]);
         }
     else {
         cqp = cqp -> next;
         return cqp ? Convert(cqp -> subj) : NULL;
         }
 }
References Convert(), cqp, cVind, NULL, and varAtom.
getAnswer()
char * DiagenDispatcher::getAnswer (char * subject)
 {
 #ifdef DIAGEN_TEST
     subj = strdup(subj);
 #endif
     char* subject = Convert(subj,1);
     if(varAtom){
         char* ret = NULL;
         Qcode = varAtom -> getVcode(subject,ret);
 //#ifndef DIAGEN_TEST
         dg_SendEvent(Qcode);
         dg_SendEvent(AML_CLEAR_QUESTION);
 //#endif
         varAtom = NULL;
         return Convert(ret);
         }
 //#ifndef DIAGEN_TEST
     if(aciEscaveEmpty || aciEscaveDead) return NULL;
 //#endif
     dgQuery* q = currentR -> seekQvisible(subject);
 #ifdef DIAGEN_TEST
     std::cout << "Subject: " << cp866_to_cp1251(cp1251_to_utf8(subj));
     free(subj);
 #endif
     if(q){
         dgMood = q -> mood;
         int n = q -> getIndex();
 #ifdef DIAGEN_TEST
         std::cout << " (" << n << ")\n";
 #endif
         char* str = q -> answers[n] -> data;
         involveQ(q -> answers[n]);
         str = Convert(str);
 #ifdef DIAGEN_TEST
         std::cout << str << "\n";
 #endif
         return str;
         }
 #ifdef DIAGEN_TEST
         std::cout << "\n" << (q ? "Not available...\n" : "Not found...\n");
 #endif
     return NULL;
 }
References Convert(), NULL, and varAtom.
getInvText()
char * DiagenDispatcher::getInvText (int type, int id, char * from = NULL, char * to = NULL)
 {
     static XBuffer buf(64);
     dgMolecule* m;
     buf.init();
     switch(type){
         case DG_POPONKA:
             buf < "Poponka " <= id;
             m = invR -> seekM(buf.GetBuf());
             return Convert(m -> tail -> data);
         case DG_TABUTASK:
             buf < "Tabutask " < *from <= id + 1;
             m = invR -> seekM(buf.GetBuf());
             return Convert(m -> tail -> data);
         case DG_PASSENGER:
             buf < "Passenger " < *from < "->" < *to < "";
             m = invR -> seekM(buf.GetBuf());
             return Convert(m -> tail -> data);
         case DG_FINAL:
             buf < "Final " <= id;
             m = invR -> seekM(buf.GetBuf());
             return Convert(m -> tail -> data);
         }
     return NULL;
 }
References Convert(), DG_FINAL, DG_PASSENGER, DG_POPONKA, DG_TABUTASK, XBuffer::GetBuf(), XBuffer::init(), invR, and NULL.
Referenced by aciSendEvent2itmdsp().
getNextPhrase()
char * DiagenDispatcher::getNextPhrase (void)
{
     if(!currentR) {
         return NULL;
     }
     dgMolecule* m = currentR->getCurrentMolecule();
     char* phr = NULL;
     if(eventOUT) {
         endSessionLog = 1;
         return NULL;
     }
     if(m) {
         dgMood = m->mood;
         involveQ(m->curA);
         phr = m -> getPhrase(currentR->bios == 4);
         varAtom = m -> getVariantsAtom();
 //#ifndef DIAGEN_TEST
         if(varAtom)
             dg_SendEvent(AML_GET_QUESTION);
 //#endif
         m->goNext();
     }
     if(!phr) {
         phr = getQend();
         endSessionLog = 1;
     } else {
         endSessionLog = 0;
     }
     phr = Convert(phr);
     dgLog(phr);
     return phr;
 }
References currentR, dgRoom::getCurrentMolecule(), and NULL.
getQblock()
char * DiagenDispatcher::getQblock (void)
{
     return currentR ? Convert(currentR -> seekM("Block Molecule") -> tail -> data) : NULL;
 }
References Convert(), currentR, and NULL.
getQdead()
char * DiagenDispatcher::getQdead (void)
 {
     if(!currentR) return NULL;
     if(*currentR -> roomName == 'P' && isSpummyDeath()) return Convert(currentR -> seekM("Last Letter") -> tail -> data);
     return Convert(currentR -> seekM("Dead Molecule") -> tail -> data);
 }
References Convert(), currentR, isSpummyDeath(), and NULL.
getQempty()
char * DiagenDispatcher::getQempty (void)
{
     return currentR ? Convert(currentR -> seekM("Empty Question") -> tail -> data) : NULL;
 }
References Convert(), currentR, and NULL.
getQend()
char * DiagenDispatcher::getQend (void)
{
     return currentR ? (!ClearStatus ? currentR -> seekM("Empty Molecule") -> tail -> data : (char *)"") : NULL;
 }
References currentR.
getQout()
char * DiagenDispatcher::getQout (void)
{
     dgMood = 3;
     return currentR ? Convert(currentR -> seekM("Out Molecule") -> tail -> data) : NULL;
 }
References Convert(), currentR, dgMood, and NULL.
getQpostfix()
char * DiagenDispatcher::getQpostfix (void)
{
     if(!currentR)
         return NULL;
     return varAtom ? NULL : Convert(currentR -> postfixQ);
 }
References Convert(), currentR, NULL, and varAtom.
getQprefix()
char * DiagenDispatcher::getQprefix (void)
{
     if(!currentR)
         return NULL;
     return varAtom ? NULL : Convert(currentR -> prefixQ);
 }
References Convert(), currentR, NULL, and varAtom.
getWorldName()
char * DiagenDispatcher::getWorldName (char * name)
 {
     if(name){
         dgRoom* r = rtail;
         while(r){
             if(!strcmp(name,r -> worldNames[0])) return r -> worldNames[lang() == RUSSIAN ? 1 : 0];
             r = r -> next;
             }
         for(int i = 0;i < DG_SECRETW_MAX;i++)
             if(!strcmp(name,SecretWname[0][i])) return SecretWname[lang() == RUSSIAN ? 1 : 0][i];
         }
     ErrH.Abort("dgWorldName not found");
     return NULL;
 }
References lang(), rtail, and RUSSIAN.
init()
void DiagenDispatcher::init (void)
 {
     std::cout<<"DiagenDispatcher::init "<<getDGname("room",".lst")<<std::endl;
     FBox = new FileBox;
 #ifndef DIAGEN_TEST
     FBox -> load();
 #endif
     dgFile* pf = new dgFile(getDGname("room",".lst"));
     char* p = NULL;
     dgRoom* pr;
     int i,j;
     int max  = oldVersion ? 8 : DG_ESCAVE_MAX;
     for (i = 0;i < max;i++) {
         (pr = new dgRoom(this)) -> link(rtail);
         pr -> read(pf);
     }
     if(!oldVersion) {
         for(j = 0;j < 3;j++){
             for(i = 0;i < 3;i++) CycleName[0][j][i] = getSubj(pf -> getElement(DGF_NONE));
 //#if defined(RUSSIAN_VERSION) || defined(DIAGEN_TEST)
             for(i = 0;i < 3;i++) CycleName[1][j][i] = pf -> getElement(DGF_NONE);
 //#endif
             }
         for(i = 0;i < DG_SECRETW_MAX;i++) SecretWname[0][i] = getSubj(pf -> getElement(DGF_NONE));
 //#if defined(RUSSIAN_VERSION) || defined(DIAGEN_TEST)
         for(i = 0;i < DG_SECRETW_MAX;i++) SecretWname[1][i] = pf -> getElement(DGF_NONE);
 //#endif
     }
     delete pf;
 //stalkerg    ,
 /*#ifdef DIAGEN_TEST
     pr = rtail;
     while(pr){
         pr -> test();
         pr = pr -> next;
         }
 #endif*/
     invR = new dgRoom(this);
     invR -> roomName = "Inventory";
     invR -> acceptTEXT();
 #ifdef DIAGEN_TEST
     FBox -> save();
 #endif
 }
References getDGname().
involveQ()
void DiagenDispatcher::involveQ (dgAtom * atom)
 {
     if(!atom) return;
     char* p = atom -> findQLfirst();
     dgQuery* q;
     dgRoom* r;
     while(p){
         r = rtail;
         while(r){
             if((q = r -> seekQall(p)) != NULL)
                 (q -> delink(r -> qAtail)) -> link(r -> qVtail);
             r = r -> next;
             }
         p = atom -> findQLnext();
         }
 }
References NULL, and rtail.
Referenced by restHandle().
isEnd()
int DiagenDispatcher::isEnd (void) inline
 { return endSessionLog; }
References endSessionLog.
load()
void DiagenDispatcher::load (XStream & ff)
 {
     std::cout<<"DiagenDispatcher::load"<<std::endl;
 /*#ifdef DIAGEN_TEST
     ff.open("test.sav",XS_IN);
 //  ff.seek(68734,XS_BEG);
 #endif*/
     isLoading = 1;
     ff > loadedVersion;
 //  if(loadedVersion < 0 || loadedVersion > saveVersion) ErrH.Abort("Intolerable dgVersion");
     if(!(loadedVersion == saveVersion || loadedVersion == saveVersion - 1)) ErrH.Abort("Intolerable dgVersion");
 /*  if(loadedVersion == 0){
         strcpy(DiagenTextName + strlen(DiagenTextName) - 4,"lst");
         oldVersion = 1;
         nDD = new DiagenDispatcher;
         nDD -> init();
         strcpy(DiagenTextName + strlen(DiagenTextName) - 3,"text");
         oldVersion = 0;
         }
 */
     ff > eStatus > bStatus > zStatus;
     if(loadedVersion >= 2) ff > sStatus;
     ff > singleRandAvailable > ClearStatus;
     if(loadedVersion >= 3) ff > wasRubeecated;
     int num;
     short len;
     char buf[256];
     dgRoom* r,*rr;
     ff > num;
     for(int i = 0;i < num;i++){
         ff > len;
         ff.read(buf,len + 1);
         r = seekR(buf);
         if(r) r -> load(ff);
         }
     dgQuery* q,*qq;
     r = rtail;
     while(r){
         q = r -> qVtail;
         while(q){
             rr = rtail;
             while(rr){
                 if((qq = rr -> seekQall(q -> subj)) != NULL)
                     (qq -> delink(rr -> qAtail)) -> link(rr -> qVtail);
                 rr = rr -> next;
                 }
             q = q -> next;
             }
         r = r -> next;
         }
 }
restHandle()
void DiagenDispatcher::restHandle (dgMolecule * m)
 {
     if(!m) return;
     while(m -> curA){
         involveQ(m -> curA);
         m -> goNext();
         }
 }
References involveQ().
save()
void DiagenDispatcher::save (XStream & ff)
 {
 /*#ifdef DIAGEN_TEST
     ff.open("test.sav",XS_OUT);
 #endif*/
     ff < saveVersion;
     ff < eStatus < bStatus < zStatus < sStatus;
     ff < singleRandAvailable < ClearStatus < wasRubeecated;
     dgRoom* r = rtail;
     int num = 0;
     while(r){
         num++;
         r = r -> next;
         }
     ff < num;
     r = rtail;
     while(r){
         ff < (short)strlen(r -> roomName);
         ff.write(r -> roomName,strlen(r -> roomName) + 1);
         r -> save(ff);
         r = r -> next;
         }
 }
References bStatus, eStatus, saveVersion, sStatus, and zStatus.
seekR()
dgRoom * DiagenDispatcher::seekR (const char * _name, int onlyfirstchar = 0)
 {
     if(!*_name) return NULL;
     dgRoom* r = rtail;
     if(!onlyfirstchar)
         while(r){
             if(!strcmp(r -> roomName,_name)) return r;
             r = r -> next;
             }
     else
         while(r){
             if(*r -> roomName == *_name) return r;
             r = r -> next;
             }
 //#ifndef DIAGEN_TEST
     ErrH.Abort("Room not found",XERR_USER,-1,_name);
 //#endif
     return NULL;
 }
References NULL, and rtail.
Referenced by checkSession(), and startSession().
startSession()
void DiagenDispatcher::startSession (const char * rname)
 {
     if(currentR) endSession();
     dgAbortStatus = 0;
     endSessionLog = 0;
     dgRoom* r = seekR(rname);
 #ifdef DIAGEN_TEST
     if(!r){
         std::cout << "\nError: room not found...\n\n";
         return;
         }
     std::cout << "\n" << strLine << " SESSION IN " << cp1251_to_utf8(r -> roomName) << " started" << strLine << "\n";
     checkSession(rname);
     if(dgAbortStatus) std::cout << "This session will be aborted!\n";
     std::cout << "\n";
 #endif
     (currentR = r) -> startSession();
     if(!isLoading){
         if(currentR != lastR) currentR -> visitCounter++;
         currentR -> comingCounter++;
         }
     isLoading = 0;
     enter_sStatus = sStatus;
 }
References checkSession(), cp1251_to_utf8(), currentR, dgAbortStatus, endSession(), endSessionLog, and seekR().
Member Data Documentation
bStatus
int DiagenDispatcher::bStatus
Referenced by DiagenDispatcher(), and save().
cqp
dgQuery* DiagenDispatcher::cqp
Referenced by findQfirst(), and findQnext().
currentR
dgRoom* DiagenDispatcher::currentR
Referenced by checkSession(), DiagenDispatcher(), endSession(), findQfirst(), getNextPhrase(), getQblock(), getQdead(), getQempty(), getQend(), getQout(), getQpostfix(), getQprefix(), and startSession().
cVind
int DiagenDispatcher::cVind
Referenced by findQfirst(), and findQnext().
CycleName
char* DiagenDispatcher::CycleName[2][3][3]
endSessionLog
int DiagenDispatcher::endSessionLog
Referenced by DiagenDispatcher(), isEnd(), and startSession().
eStatus
int DiagenDispatcher::eStatus
Referenced by DiagenDispatcher(), and save().
invR
dgRoom* DiagenDispatcher::invR
Referenced by DiagenDispatcher(), and getInvText().
lastR
dgRoom* DiagenDispatcher::lastR
Referenced by DiagenDispatcher().
rtail
dgRoom* DiagenDispatcher::rtail
Referenced by DiagenDispatcher(), getWorldName(), involveQ(), and seekR().
SecretWname
char* DiagenDispatcher::SecretWname[2][DG_SECRETW_MAX]
sStatus
int DiagenDispatcher::sStatus
Referenced by DiagenDispatcher(), and save().
varAtom
dgAtom* DiagenDispatcher::varAtom
Referenced by DiagenDispatcher(), findQfirst(), findQnext(), getAnswer(), getQpostfix(), and getQprefix().
zStatus
int DiagenDispatcher::zStatus
Referenced by DiagenDispatcher(), and save().
The documentation for this struct was generated from the following files:
src/uvs/diagen.h
src/uvs/diagen.cpp