Vangers: iBitmapElement Struct Reference
iBitmapElement Struct Reference
#include <iscreen.h>
Public Member Functions
void load_shape (void)
void free_shape (void)
void init_name (const char *ptr)
void init_palname (char *ptr)
void alloc_mem (void)
void free (void)
void load (void)
void set_pal (void)
void init_size (void)
void free_mem (void)
iBitmapElement (void)
Public Member Functions inherited from iScreenElement
void load_data (void)
void free_data (void)
void redraw (int x, int y, int sc, int sm, int hide_mode)
void scale_quant (void)
int check_xy (int x, int y)
void copy (iScreenElement *dest)
void init_align (void)
void change_terrainNum (int terr)
iScreenElement (void)
~iScreenElement (void)
Public Member Functions inherited from iListElement
void init_id (const char *p)
iListElement (void)
~iListElement (void)
Public Attributes
short bSizeX
short bSizeY
int bmp_null_level
iList * bmp_names
iList * pal_names
ibsObject * ibs
char * fname
char * palname
char * fdata
char * border_shape_file
char * border_shape
short ShSizeX
short ShSizeY
Public Attributes inherited from iScreenElement
short ID
short type
short lX
short lY
short nlX
short nlY
short SizeX
short SizeY
int scale
int scale_delta
int terrainNum
int align_x
int align_y
int align_x_offs
int align_y_offs
int flags
int null_level
iListElement * owner
Public Attributes inherited from iListElement
std::string ID_ptr
int name_len
iListElement * prev
iListElement * next
Detailed Description
Constructor & Destructor Documentation
iBitmapElement()
iBitmapElement::iBitmapElement (void)
 {
     bmp_null_level = HFONT_NULL_LEVEL;
     border_shape_file = NULL;
     fname = new char[256];
     palname = new char[256];
     memset(palname,0,256);
     bmp_names = new iList;
     pal_names = new iList;
     ibs = NULL;
     type = I_BITMAP_ELEM;
 }
References bmp_names, bmp_null_level, border_shape_file, fname, HFONT_NULL_LEVEL, I_BITMAP_ELEM, ibs, NULL, pal_names, palname, and iScreenElement::type.
Member Function Documentation
alloc_mem()
void iBitmapElement::alloc_mem (void)
 {
     int sz;
     if(!(flags & EL_DATA_LOADED)){
         sz = bSizeX * bSizeY;
         fdata = new char[sz];
     }
     flags |= EL_DATA_LOADED;
 }
References bSizeX, bSizeY, EL_DATA_LOADED, fdata, and iScreenElement::flags.
free()
void iBitmapElement::free (void)
 {
     if((flags & EL_DATA_LOADED)){
         flags ^= EL_DATA_LOADED;
         delete[] fdata;
     }
 }
References EL_DATA_LOADED, fdata, and iScreenElement::flags.
Referenced by free_mem(), and free_shape().
free_mem()
void iBitmapElement::free_mem (void)
 {
     iListElement* p,*p1;
     free();
     delete[] fname;
     delete[] palname;
     if(ibs)
         delete ibs;
     if(border_shape_file)
         delete border_shape_file;
     p = bmp_names -> last;
     while(p){
         p1 = p -> prev;
         delete p;
         p = p1;
     }
     delete bmp_names;
     p = pal_names -> last;
     while(p){
         p1 = p -> prev;
         delete p;
         p = p1;
     }
     delete pal_names;
 }
References bmp_names, border_shape_file, fname, free(), ibs, pal_names, palname, and iListElement::prev.
free_shape()
void iBitmapElement::free_shape (void)
 {
     if(flags & EL_BORDER_INIT){
         if(border_shape)
             delete border_shape;
         if(ibs)
             ibs -> free();
         flags ^= EL_BORDER_INIT;
     }
 }
References border_shape, EL_BORDER_INIT, iScreenElement::flags, free(), and ibs.
init_name()
void iBitmapElement::init_name (const char * ptr)
 {
     iListElement* p = new iListElement;
     if(!strcmp(ptr,"NONE")) flags |= EL_NONE_BMP;
     p -> init_id(ptr);
     bmp_names -> connect(p);
     strcpy(fname,bmp_names->first->ID_ptr.c_str());
 }
References bmp_names, EL_NONE_BMP, iList::first, iScreenElement::flags, fname, iListElement::ID_ptr, iListElement::iListElement(), and iListElement::init_id().
init_palname()
void iBitmapElement::init_palname (char * ptr)
 {
     iListElement* p = new iListElement;
     p -> init_id(ptr);
     pal_names -> connect(p);
     strcpy(palname,pal_names->first->ID_ptr.c_str());
 }
References iList::first, iListElement::ID_ptr, iListElement::iListElement(), iListElement::init_id(), pal_names, and palname.
init_size()
void iBitmapElement::init_size (void)
 {
     XStream fh;
     if(!(flags & EL_NONE_BMP)){
         fh.open(fname,XS_IN);
         fh > bSizeX > bSizeY;
         fh.close();
         SizeX = bSizeX;
         SizeY = bSizeY;
     }
     else {
         bSizeX = SizeX;
         bSizeY = SizeY;
     }
 }
References bSizeX, bSizeY, XStream::close(), EL_NONE_BMP, iScreenElement::flags, fname, XStream::open(), iScreenElement::SizeX, iScreenElement::SizeY, and XS_IN.
load()
void iBitmapElement::load (void)
 {
     int i,t,sz;
     XStream fh;
     if(!(flags & EL_DATA_LOADED)){
         if(flags & EL_NONE_BMP){
             sz = bSizeX * bSizeY;
             fdata = new char[sz];
             memset(fdata,0,sz);
         }
         else {
             fh.open(fname,XS_IN);
             fh > bSizeX > bSizeY;
             sz = bSizeX * bSizeY;
             fdata = new char[sz];
             fh.read(fdata,sz);
             fh.close();
             if(!(flags & EL_PICTURE)){
                 for(i = 0; i < sz; i ++){
                     t = ((unsigned char*)fdata)[i];
                     if(t)
                         t += bmp_null_level;
                     else
                         t = HFONT_NULL_LEVEL;
                     fdata[i] = t;
                 }
             }
             else {
                 if(flags & EL_HIDDEN_FON)
                     memset(fdata,0,sz);
             }
             set_pal();
         }
     }
     flags |= EL_DATA_LOADED;
 }
References bmp_null_level, bSizeX, bSizeY, XStream::close(), EL_DATA_LOADED, EL_HIDDEN_FON, EL_NONE_BMP, EL_PICTURE, fdata, iScreenElement::flags, fname, HFONT_NULL_LEVEL, XStream::open(), XStream::read(), set_pal(), and XS_IN.
Referenced by load_shape().
load_shape()
void iBitmapElement::load_shape (void)
 {
     XStream fh;
     if(!(flags & EL_BORDER_INIT)){
         if(border_shape_file){
             fh.open(border_shape_file);
             fh > ShSizeX > ShSizeY;
             if(ShSizeX != SizeX || ShSizeY != SizeY)
                 ErrH.Abort("Bad BMP border shape file...",XERR_USER,0,ID_ptr.c_str());
             border_shape = new char[ShSizeX * ShSizeY];
             fh.read(border_shape,ShSizeX * ShSizeY);
             fh.close();
             smooth_shape(ShSizeX,ShSizeY,(unsigned char*)border_shape);
         }
         else {
             border_shape = NULL;
             if(ibs){
                 ibs -> load();
             }
         }
         flags |= EL_BORDER_INIT;
     }
 }
References XErrorHandler::Abort(), border_shape, border_shape_file, XStream::close(), EL_BORDER_INIT, ErrH, iScreenElement::flags, ibs, iListElement::ID_ptr, load(), NULL, XStream::open(), XStream::read(), ShSizeX, ShSizeY, iScreenElement::SizeX, iScreenElement::SizeY, smooth_shape(), and XERR_USER.
set_pal()
void iBitmapElement::set_pal (void)
 {
     char* p;
     if(!(flags & EL_PICTURE) || !strlen(palname)) return;
     XStream fh(palname,XS_IN);
     _iALLOC_A_(char,p,768);
     fh.read(p,768);
     fh.close();
     XGR_SetPal(p + I_PAL_OFFS,I_PAL_START,I_PAL_SIZE);
     _iFREE_A_(char,p,768);
 }
References _iALLOC_A_, _iFREE_A_, XStream::close(), EL_PICTURE, iScreenElement::flags, I_PAL_OFFS, I_PAL_SIZE, I_PAL_START, palname, XStream::read(), XGR_SetPal, and XS_IN.
Referenced by load().
Member Data Documentation
bmp_names
iList* iBitmapElement::bmp_names
Referenced by free_mem(), iBitmapElement(), and init_name().
bmp_null_level
int iBitmapElement::bmp_null_level
Referenced by iBitmapElement(), iScrollerElement::iScrollerElement(), and load().
border_shape
char* iBitmapElement::border_shape
Referenced by free_shape(), and load_shape().
border_shape_file
char* iBitmapElement::border_shape_file
Referenced by free_mem(), iBitmapElement(), and load_shape().
bSizeX
short iBitmapElement::bSizeX
Referenced by alloc_mem(), iScrollerElement::change_val(), init_size(), and load().
bSizeY
short iBitmapElement::bSizeY
Referenced by alloc_mem(), iScrollerElement::change_val(), init_size(), and load().
fdata
char* iBitmapElement::fdata
Referenced by alloc_mem(), free(), and load().
fname
char* iBitmapElement::fname
Referenced by free_mem(), iBitmapElement(), init_name(), init_size(), and load().
ibs
ibsObject* iBitmapElement::ibs
Referenced by free_mem(), free_shape(), iBitmapElement(), and load_shape().
pal_names
iList* iBitmapElement::pal_names
Referenced by free_mem(), iBitmapElement(), and init_palname().
palname
char* iBitmapElement::palname
Referenced by free_mem(), iBitmapElement(), init_palname(), and set_pal().
ShSizeX
short iBitmapElement::ShSizeX
Referenced by load_shape().
ShSizeY
short iBitmapElement::ShSizeY
Referenced by load_shape().
The documentation for this struct was generated from the following files:
src/iscreen/iscreen.h
src/iscreen/iscreen.cpp