Vangers: BackgroundDispatcher Struct Reference
BackgroundDispatcher Struct Reference
#include <backg.h>
Public Member Functions
void init (int sz=100)
void free (void)
void close (void)
void put (BackgroundElement *p)
void restore (void)
Public Attributes
BackgroundElement ** BkData
int point
int size
Detailed Description
Member Function Documentation
close()
void BackgroundDispatcher::close (void)
 {
     point = 0;
 };
References point.
Referenced by GeneralSystemClose().
free()
void BackgroundDispatcher::free (void)
 {
     delete[] BkData;
 };
References BkData.
Referenced by GeneralSystemFree().
init()
void BackgroundDispatcher::init (int sz = 100)
 {
     size = sz;
     point = 0;
     BkData = new BackgroundElement*[size];
 };
References BkData, point, and size.
Referenced by GeneralSystemInit().
put()
void BackgroundDispatcher::put (BackgroundElement * p)
 {
     if(point < size){
         BkData[point] = p;
         point++;
     }else ErrH.Abort("Background stack overflow");
 };
References XErrorHandler::Abort(), BkData, ErrH, point, and size.
Referenced by DeformProcess::deform(), and LightPoint::quant().
restore()
void BackgroundDispatcher::restore (void)
 {
     while(point != 0){
         point--;
         BkData[point]->BackRestore();
     };
 };
References BackgroundElement::BackRestore(), BkData, and point.
Referenced by iGameMap::draw().
Member Data Documentation
BkData
BackgroundElement** BackgroundDispatcher::BkData
Referenced by free(), init(), put(), and restore().
point
int BackgroundDispatcher::point
Referenced by close(), init(), put(), and restore().
size
int BackgroundDispatcher::size
Referenced by init(), and put().
The documentation for this struct was generated from the following files:
src/backg.h
src/backg.cpp