Vangers: MainMenuRTO Struct Reference
MainMenuRTO Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
virtual void Finit (void)
MainMenuRTO (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Additional Inherited Members
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
MainMenuRTO()
MainMenuRTO::MainMenuRTO (void) inline
 { ID = RTO_MAIN_MENU_ID; Timer = RTO_ISCREEN_TIMER; }
References XRuntimeObject::ID, RTO_ISCREEN_TIMER, RTO_MAIN_MENU_ID, and XRuntimeObject::Timer.
Member Function Documentation
Finit()
void MainMenuRTO::Finit (void) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
     if(flags & RTO_FINIT_FLAG){
         //actintLowResFlag = !iGetOptionValue(iSCREEN_RESOLUTION);
         actintLowResFlag = 0;
         SoundVolumePanning = !iGetOptionValue(iPANNING_ON);
         aciGroundPressingEnabled = iGetOptionValue(iDESTR_MODE);
         EngineNoise = !iGetOptionValue(iMECH_SOUND);
         BackgroundSound = !iGetOptionValue(iBACK_SOUND);
         iFinitQuant();
         ClearFlag(RTO_ALL_FLAGS);
     }
     else
         SetFlag(RTO_FINIT_FLAG);
     XGR_MouseHide();
 #endif
 _MEM_STATISTIC_("AFTER MAIN MENU FINIT -> ");
 }
References _MEM_STATISTIC_, aciGroundPressingEnabled, actintLowResFlag, BackgroundSound, BaseRTO::ClearFlag(), EngineNoise, BaseRTO::flags, iBACK_SOUND, iDESTR_MODE, iFinitQuant(), iGetOptionValue(), iMECH_SOUND, iPANNING_ON, RTO_ALL_FLAGS, RTO_FINIT_FLAG, BaseRTO::SetFlag(), SoundVolumePanning, and XGR_MouseHide.
Init()
void MainMenuRTO::Init (int id) virtual
Reimplemented from XRuntimeObject.
 {
     Dead = 0;
 //  activeWTRACK = 0;
 _MEM_STATISTIC_("BEFORE MAIN MENU INIT -> ");
 #ifdef ISCREEN
     if(!(flags & RTO_INIT_FLAG)){
         LoadingMessage(1);
         iInit();
 _MEM_STATISTIC_("AFTER MAIN iINIT INIT -> ");
         palTr -> set(NULL,iscrPal,0,255,&Quit);
         palTr -> quant();
         iQuantFirst();
         iQuantPrepare();
 _MEM_STATISTIC_("AFTER IQUANTFIRST INIT -> ");
         //XGR_Flush(0,0,I_RES_X,I_RES_Y);
         SetFlag(RTO_INIT_FLAG);
         rtoSetNextID(RTO_PALETTE_TRANSFORM_ID,RTO_MAIN_MENU_ID);
 //        rtoSetNextID(RTO_ESCAVE_INGATE_ID,RTO_FIRST_ESCAVE_ID);
     }
     else {
         iKeyClear();
         XGR_MouseShow();
     }
 #else
     aLoadFonts32();
 #endif
     XGR_Obj.set_fullscreen(iGetOptionValue(iFULLSCREEN));
 _MEM_STATISTIC_("AFTER MAIN MENU INIT -> ");
 }
References _MEM_STATISTIC_, aLoadFonts32(), Dead, BaseRTO::flags, iFULLSCREEN, iGetOptionValue(), iInit(), iKeyClear(), iQuantFirst(), iQuantPrepare(), iscrPal, LoadingMessage(), NULL, palTr, Quit, RTO_INIT_FLAG, RTO_MAIN_MENU_ID, RTO_PALETTE_TRANSFORM_ID, rtoSetNextID(), set(), XGR_Screen::set_fullscreen(), BaseRTO::SetFlag(), XGR_MouseShow, and XGR_Obj.
Quant()
int MainMenuRTO::Quant (void) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
     int code;
     char* pal;
 //znfo next line was commented in zmod
 //  ShowImageRTO* p;
     MainMenuSoundQuant();
     if(flags & RTO_QUANT_FLAG){
         code = iQuantSecond();
         if(code){
             if(!iScrExitCode){
                 pal = new char[768];
                 i_slake_pal((unsigned char*)pal,32);
                 delete[] pal;
                 aciPrepareEndImage();
                 return RTO_SHOW_IMAGE_ID;
             }
             rtoSetNextID(RTO_LOADING1_ID,RTO_FIRST_ESCAVE_ID);
             return RTO_LOADING1_ID;
         }
         //XGR_Flip();
         return 0;
     }
     else {
         SetFlag(RTO_QUANT_FLAG);
         return RTO_PALETTE_TRANSFORM_ID;
     }
 #else
     return RTO_LOADING1_ID;
 #endif
 }
References aciPrepareEndImage(), BaseRTO::flags, i_slake_pal(), iQuantSecond(), iScrExitCode, MainMenuSoundQuant(), RTO_FIRST_ESCAVE_ID, RTO_LOADING1_ID, RTO_PALETTE_TRANSFORM_ID, RTO_QUANT_FLAG, RTO_SHOW_IMAGE_ID, rtoSetNextID(), and BaseRTO::SetFlag().
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp