Vangers: LightPoint Struct Reference
LightPoint Struct Reference
#include <light.h>
Public Member Functions
void load_color_line (void)
void restore_color_line (void)
void set_position (int _x, int _y, int _z)
int quant (void)
void BackRestore (void)
void FourLightLine (int, int, int)
void CreateLight (int _r, int _e, int _type)
void Quant (void)
void Free (void)
void Init (StorageType *s)
void MemInit (int R=64)
void Destroy (void)
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
int type
int x
int y
int xn
int yn
unsigned int x_size
unsigned int y_size
int c_time
int energy
int d_energy
int maxR
int last_z
uchar * buf
uchar * bool_buf
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
BackRestore()
void LightPoint::BackRestore (void) virtual
Reimplemented from BackgroundElement.
 {
     restore_color_line();
 };
References restore_color_line().
CreateLight()
void LightPoint::CreateLight (int _r, int _e, int _type)
 {
     Status = 0;
     //std::cout<<"LightPoint::CreateLight _r:"<<_r<<" _e:"<<_e<<" _t:"<<_t<<" light_table_pal:"<<(long long)light_table_pal<<std::endl;
     //Activate Function
     if ( _r > maxR ) _r = maxR;
     type = _t;
     x_size = _r<<1;
     y_size = _r<<1;
     if ( _e >= LIGHT_MAX_BRIGHTNESS )
         energy = (LIGHT_MAX_BRIGHTNESS-1)<<15;
     else
         energy = (_e)<<15;
     d_energy = energy/5;
     c_time  = 0;
 };
References c_time, d_energy, energy, LIGHT_MAX_BRIGHTNESS, maxR, GeneralObject::Status, type, x_size, and y_size.
Referenced by ActionDispatcher::Init().
Destroy()
void LightPoint::Destroy (void)
 {
 //  Status |= SOBJ_DISCONNECT;
     Status |= SOBJ_LINK;
 };
References SOBJ_LINK, and GeneralObject::Status.
Referenced by uvsDolly::ActiveQuant(), ActionDispatcher::Close(), GloryPlace::CloseWorld(), ItemsDispatcher::DeleteItem(), StuffObject::DeviceIn(), StuffObject::DeviceOut(), ActionDispatcher::FunctionQuant(), StuffObject::Quant(), BulletObject::Quant(), GloryPlace::Quant(), and BulletObject::TimeOutQuant().
FourLightLine()
void LightPoint::FourLightLine (int _dx, int _dy, int _E)
{
     uchar **ltc = vMap -> lineTcolor;
     uchar **lt = vMap -> lineT;
     unsigned int _z = (unsigned int)last_z;
     int dx, dy, de, ee, _e;
     int _x, _y;
     int n, color;
     int R = y_size>>1;
     if (_dx > _dy)
         n = _dx>>2;
     else
         n = _dy>>2;
     dx = -(_dx<<12)/n;
     dy = -(_dy<<12)/n;
     de = (_E<<15)/n;
     ee = 0 + (1<<14);
     _x = (_dx<<15) + (1<<14);
     _y = (_dy<<15) + (1<<14);
     for( int i = 0; i < 2*n; i++){
         int _x_ = _x >> 15;
         int _y_ = _y >> 15;
         _e = ee>>15;
         int mx = (x + _x_  + R)&clip_mask_x;
         int my = (y + _y_  + R)&clip_mask_y;
         if ( lt[my] ){
             if ( lt[my][ mx|1] <= _z){
                 color = buf[ (_y_ + R)*x_size +  _x_ + R];
                 ltc[ my ][ mx ] = light_table_pal[ ((_e) << 8) + color ];
             }
             mx = (x - _x_ + R)&clip_mask_x;
             if ( lt[my][mx|1] <= _z){
                 color = buf[ (_y_ + R)*x_size + R -  _x_];
                 ltc[ my ][ mx ] = light_table_pal[ ((_e) << 8) + color ];
             }
         }
         my = (y - _y_ + R)&clip_mask_y;
         mx = (x + _x_ + R)&clip_mask_x;
         if (lt[my] ){
             if ( lt[my][ mx|1] <= _z){
                 color = buf[ (R - _y_)*x_size +  _x_ + R];
                 ltc[ my ][ mx ] = light_table_pal[ ((_e) << 8) + color ];
             }
             mx = (x - _x_ + R)&clip_mask_x;
             if ( lt[my][mx|1] <= _z){
                 color = buf[ (R- _y_)*x_size + (R -  _x_)];
                 ltc[ my ][ mx ] = light_table_pal[ ((_e) << 8) + color ];
             }
         }
         _x += dx;
         _y += dy;
         if ( i < n)
             ee += de;
         else
             ee -= de;
     }
 }
References buf, clip_mask_x, clip_mask_y, last_z, light_table_pal, vMap, x, x_size, y, and y_size.
Referenced by quant().
Free()
void LightPoint::Free (void)
 {
     // Free memory
     delete[] buf;
     delete[] bool_buf;
 };
References bool_buf, and buf.
Init()
void LightPoint::Init (StorageType * s)
 {
 //  std::cout<<"LightPoint::Init"<<std::endl;
     GeneralObject::Init(s);
 };
Referenced by ActionDispatcher::Init().
load_color_line()
void LightPoint::load_color_line (void)
{
     unsigned int i;
     uchar **ltc = vMap -> lineTcolor;
     uchar **lt = vMap -> lineT;
     uchar *llt;
     uchar *llct;
     uchar *dbuf = buf;
     //int offset = LIGHT_MAX_RADIUSE<<1;
     int offset = x_size;
     memset( bool_buf, 0, y_size );
     for( i = 0; i < y_size; i++, dbuf += offset){
         llt = lt[(y + i) & clip_mask_y];
         llct = ltc[(y + i) & clip_mask_y];
         int _x = (x & clip_mask_x);
         if ( llt  ){
             if ( _x + x_size >=  map_size_x){
                 int d =  map_size_x - _x;
                 memcpy( dbuf, llct + _x, d);
                 memcpy( dbuf + d, llct,  x_size - d);
             } else {
                 memcpy( dbuf, llct + _x, x_size);
             }
             bool_buf[i] = 1;
         }//  end if
     }//  end for i
 }
References buf, and vMap.
Referenced by quant().
MemInit()
void LightPoint::MemInit (int R = 64)
 {
 // Allocate memory
     maxR = R;
     buf = new uchar[R*R*4];
     bool_buf = new uchar[R*2];
     memset(bool_buf, 0, R*2);
 };
References bool_buf, buf, and maxR.
Referenced by ActionDispatcher::Init().
quant()
int LightPoint::quant (void)
{
     int i, j;
     int R = y_size >> 1;
     uchar **ltc = vMap -> lineTcolor;
     uchar **lt = vMap -> lineT;
     uchar *llt;
     uchar *llct;
     uchar *llt1;
     uchar *llt2;
     uchar *llt3;
     uchar *llct1;
     int E = 32;
     int ee;
     int _R;
     unsigned int _z = (unsigned int)last_z;
     x = xn;
     y = yn;
     if (type & LIGHT_TYPE::STATIONARY) {
         if ( c_time < LIGHT_FIRST_TIME) {
             c_time++;
             E = ((c_time*energy)/LIGHT_FIRST_TIME)>>15;
         } else {
             E = (energy -= (3<<15))>>15;
             c_time += 3;
         }
         if( energy <= (5<<15) ) return 0;
     } else if (type & LIGHT_TYPE::DYNAMIC) {
         c_time++;
         if (c_time <= 5 ){
             energy -= d_energy;
         } else {
             if ( c_time == 10 ) c_time = 0;
             energy += d_energy;
         };
         E = energy>>15;
     } else if (type & LIGHT_TYPE::STATIC) {
         E = energy>>15;
     }
     //E=32;
     _R = E*(1<<16)/(R*R);
     //std::cout<<"LightPoint::quant type:"<<type<<" R:"<<R<<" _R:"<<_R<<" E:"<<E<<" energy:"<<energy<<std::endl;
     BackD.put(this);
     load_color_line();
     int rr;
     if (type & LIGHT_TYPE::TOR) {
         int dd, da, yy, xx, delta;
         R--;
         xx = 0;
         yy = R;
         dd = 2*( 1 - R);
         delta = 0;
         while( yy >= delta){
             FourLightLine( xx, yy, E);
             if (dd < 0){
                 da = 2*(dd + yy) - 1;
                 if (da <= 0){
                     xx++;
                     dd += 2*xx + 1;
                 } else if ( da > 0){
                     xx++;
                     yy--;
                     dd += 2*(xx - yy + 1);
                 }
             } else if (dd > 0){
                 da = 2*(dd + xx) - 1;
                 if (da <= 0){
                     xx++;
                     yy--;
                     dd += 2*(xx - yy + 1);
                 } else if ( da > 0){
                     yy--;
                     dd += 1 - 2*yy;
                 }
             } else {
                 xx++;
                 yy--;
                 dd += 2*(xx - yy + 1);
             }
         }//  while
         return 1;
     } else {
         int dimR[256];
         for(i = 0; i <= R+2; i++) {
             dimR[i]=(int)sqrt((double)R*R-i*i);
         }
         for(i = 1; i <= R; i++){//y_size
             if ( bool_buf[i]&& bool_buf[2*R-i] ) {
                 int _y = (y+i) & clip_mask_y;
                 int _y1 = (y+2*(R)-i-1) & clip_mask_y;//R-1
                 llct = ltc[ _y ];
                 llct1= ltc[ _y1 ];
     //          llct[x&clip_mask_x]=255;llct[(x+x_size-1)&clip_mask_x]=255;
     //          llct1[x&clip_mask_x]=255;llct1[(x+x_size-1)&clip_mask_x]=255;
                 j=0;
                 while(dimR[j]-(R-i) >0){
                     int _x = ((x+R+j) & clip_mask_x)|1;
                     int _x2 = ((x+R-j-2) & clip_mask_x)|1;
                     j += 2;
                     //Sectors light around point (light under pulse)
                     llt  =  lt[_y] + _x;
                     llt1 =  lt[_y1] + _x;
                     llt2 = lt[_y]+_x2;
                     llt3 = lt[_y1]+_x2;
                     int r4=(R*2-dimR[j]-dimR[R-i]);
                     int r, first_shift;
                     if ( (*llt) < _z ){
                         int _dz = _z - (*llt);
                         if  (_dz < 128) {
                             //r = (r<<8)/(_dz + 128 );
                             r = r4+(2*r4>>((_dz&0x60)>>5));
                         } else {
                             r = r4;
                         }
                         rr = (R-r);
                         if ( rr >= 0 ){
                             ee=rr*rr;
                             ee = (ee*_R)>>16;
                             first_shift = (ee << 8) + llct[_x];
                             if (light_table_pal_size <= first_shift || first_shift < 0) {
                                 std::cout<<"LightPoint::quant wrong light_table_pal position"<<std::endl;
                                 break;
                             }
                             //std::cout<<"rr*rr:"<<rr*rr<<"_R:"<<_R<<" ee:"<<ee<<"A:"<<(ee << 8) + llct[_x]<<" llct[_x]:"<<(long)llct[_x]<<" _x:"<<_x<<" pal:"<<&light_table_pal<<std::endl;
                             llct[_x] = light_table_pal[ first_shift ];
                             llct[_x-1] = light_table_pal[ (ee << 8) + llct[_x-1] ];
                         }
                     }
     //2tchk
                     if ( (*llt1) < _z ){
                         int _dz = _z - (*llt1);
                         if  (_dz < 128)
                             //r = (r<<8)/(_dz + 128 );
                             r = r4+(2*r4>>((_dz&0x60)>>5));
                         else r=r4;
                         rr = (R-r);
                         if ( rr >= 0 ){
                             ee=rr*rr;
                             ee = (ee*_R)>>16;
                             //std::cout<<"B:"<<(ee << 8) + llct[_x]<<" llct[_x]:"<<(long)llct[_x]<<" _x:"<<_x<<" pal:"<<&light_table_pal<<std::endl;
                             llct1[_x] = light_table_pal[ (ee << 8) + llct1[_x] ];
                             llct1[_x-1] = light_table_pal[ (ee << 8) + llct1[_x-1] ];
                         }
                     }
     //3
                     if ( (*llt2) < _z ){
                         int _dz = _z - (*llt2);
                         if  (_dz < 128)
                             //r = (r<<8)/(_dz + 128 );
                             r = r4+(2*r4>>((_dz&0x60)>>5));
                         else r=r4;
                         rr = (R-r);
                         if ( rr >= 0 ){
                             ee = rr*rr;
                             ee = (ee*_R)>>16;
                             llct[_x2] = light_table_pal[ (ee << 8) + llct[_x2] ]; //ERROR: #895
                             llct[_x2-1] = light_table_pal[ (ee << 8) + llct[_x2-1] ];
                         }
                     }
     //4
                     if ( (*llt3) < _z ){
                         int _dz = _z - (*llt3);
                         if  (_dz < 128)
                             //r = (r<<8)/(_dz + 128 );
                             r = r4+(2*r4>>((_dz&0x60)>>5));
                         else r=r4;
                         rr = (R-r);
                         if ( rr >= 0 ){
                             ee=rr*rr;
                             ee = (ee*_R)>>16;
                             llct1[_x2] = light_table_pal[ (ee << 8) + llct1[_x2] ];
                             llct1[_x2-1] = light_table_pal[ (ee << 8) + llct1[_x2-1] ];
                         }
                     }
                 }//  end for j
             }//  end if
         }
     //*/
     /*  for( i = 0; i < y_size; i++){
             if ( bool_buf[i] ) {
                 int _y = (y+i) & clip_mask_y;
                 llct = ltc[ _y ];
                 int yr = R - i;
                 yr = yr*yr;
                 for( j = 0; j < x_size; j++){
                     int _x = (x+j) & clip_mask_x;
                     llt =  lt[_y] + _x;
                     if(*(llt + H_SIZE) & DOUBLE_LEVEL)
                         if(!(_x & 1)) (++llt);
                     if ( (*llt) < _z ){
                         int _dz = _z - (*llt);
                         int xr = R - j;
                         xr = xr*xr;
                         int r = Sqrt( xr + yr );
                         if  (_dz < 127)
                             r = (r<<8)/(_dz + 128 );
                         uchar cl = llct[_x];
                         rr = (R-r);
                         if ( rr < 0 ) continue;
                         ee = _power_table[rr];
                         ee = (ee*_R)>>16;
                         llct[_x] =light_table_pal[ (ee << 8) + cl ];
                     }
                 }//  end for j
             }//  end if
         }//  end for i
     */
         //return c_time;
     }
     return 1;
 }
References BackD, bool_buf, c_time, clip_mask_x, clip_mask_y, d_energy, LIGHT_TYPE::DYNAMIC, energy, FourLightLine(), last_z, LIGHT_FIRST_TIME, light_table_pal, light_table_pal_size, load_color_line(), BackgroundDispatcher::put(), LIGHT_TYPE::STATIC, LIGHT_TYPE::STATIONARY, LIGHT_TYPE::TOR, type, vMap, x, xn, y, y_size, and yn.
Referenced by Quant().
Quant()
void LightPoint::Quant (void)
 {
     if(Status & SOBJ_LINK) Status = SOBJ_DISCONNECT;
     else{
         if(!quant()) Status = SOBJ_LINK;
     };
 };
References quant(), SOBJ_DISCONNECT, SOBJ_LINK, and GeneralObject::Status.
Referenced by ActionDispatcher::Quant().
restore_color_line()
void LightPoint::restore_color_line (void)
{
     unsigned int i;
     uchar **ltc = vMap -> lineTcolor;
     uchar **lt = vMap -> lineT;
     uchar *llt;
     uchar *llct;
     uchar *dbuf = buf;
     //int offset = LIGHT_MAX_RADIUSE<<1;
     int offset = x_size;
     for( i = 0; i < y_size; i++, dbuf += offset){
         llt = lt[(y + i) & clip_mask_y];
         llct = ltc[(y + i) & clip_mask_y];
         if ( llt && bool_buf[i] ){
             if ( (x & clip_mask_x) + x_size >=  map_size_x){
                 int d =  map_size_x - (x & clip_mask_x);
                 memcpy( llct + (x & clip_mask_x ), dbuf,  d);
                 memcpy( llct, dbuf + d,  x_size - d);
             } else
                 memcpy(  llct + (x & clip_mask_x ), dbuf, x_size);
         } else {
         }//  end if
     }//  end for i
 }
References buf, and vMap.
Referenced by BackRestore().
set_position()
void LightPoint::set_position (int _x, int _y, int _z)
{
     last_z = _z;
     xn = _x - (x_size>>1);
     yn = _y - (y_size>>1);
 }
References last_z, x_size, xn, y_size, and yn.
Referenced by BulletObject::DrawQuant(), ActionDispatcher::FunctionQuant(), StuffObject::Quant(), and ActionDispatcher::Quant().
Member Data Documentation
bool_buf
uchar* LightPoint::bool_buf
Referenced by Free(), MemInit(), and quant().
buf
uchar* LightPoint::buf
Referenced by FourLightLine(), Free(), load_color_line(), MemInit(), and restore_color_line().
c_time
int LightPoint::c_time
Referenced by CreateLight(), and quant().
d_energy
int LightPoint::d_energy
Referenced by CreateLight(), and quant().
energy
int LightPoint::energy
Referenced by CreateLight(), and quant().
last_z
int LightPoint::last_z
Referenced by FourLightLine(), quant(), and set_position().
maxR
int LightPoint::maxR
Referenced by CreateLight(), and MemInit().
type
int LightPoint::type
Referenced by CreateLight(), and quant().
x
int LightPoint::x
Referenced by FourLightLine(), and quant().
x_size
unsigned int LightPoint::x_size
Referenced by CreateLight(), FourLightLine(), and set_position().
xn
int LightPoint::xn
Referenced by quant(), and set_position().
y
int LightPoint::y
Referenced by FourLightLine(), and quant().
y_size
unsigned int LightPoint::y_size
Referenced by CreateLight(), FourLightLine(), quant(), and set_position().
yn
int LightPoint::yn
Referenced by quant(), and set_position().
The documentation for this struct was generated from the following files:
src/particle/light.h
src/particle/light.cpp