Vangers: ParticleObject Struct Reference
ParticleObject Struct Reference
#include <effect.h>
Public Member Functions
void InitParicle (int num)
void Init (StorageType *s)
void Free (void)
void Quant (void)
void DrawQuant (void)
void CreateParticle (int _LifeTime, int _Velocity, int _FirstRadius, int _EndRadius, int _FirstColor, int _EndColor, const Vector &v1, const Vector &v2)
void CreateParticle (int _LifeTime, int _Velocity, int _FirstRadius, int _EndRadius, int _FirstColor, int _EndColor, int _StepAlpha, const Vector &v1, const Vector &v2, const DBM &n)
void CreateParticle (ParticleInitDataType *n, const Vector &v1, const Vector &v2)
void CreateParticle (ParticleInitDataType *n, const Vector &v1, const Vector &v2, const DBM &m)
void CreateParticle (ParticleInitDataType *n, const Vector &v)
void CreateDirectParticle (ParticleInitDataType *n, const Vector &v)
void CreateRingOfLord (const Vector v1, int rad, int ltime, int fcol, int lcol, int vel)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
int NumParticle
int LifeTime
int Time
int Mode
int Phase
int dPhase
SimpleParticleType * Data
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CreateDirectParticle()
void ParticleObject::CreateDirectParticle (ParticleInitDataType * n, const Vector & v)
 {
     int i;
     int FirstColor,DeltaColor,Velocity;
     DBV vDelta;
     Vector vPos;
     SimpleParticleType* p;
     int Alpha,StepAlpha;
     Mode = 0;
     Time = 0;
     LifeTime = n->LifeTime;
     FirstColor = n->FirstColor << 8;
     DeltaColor = ((n->EndColor << 8) - FirstColor) / LifeTime;
     radius = n->FirstRadius;
     R_curr = v;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
     MapLevel = 1;
     Velocity = n->Velocity;
     vPos = Vector(v.x << 8,v.y << 8,v.z << 8);
     StepAlpha = rPI(2*PI / NumParticle);
     Alpha = RND(PI);
     double radius_inv = 1/(double)radius;
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         p->Color = FirstColor;
         p->dColor = DeltaColor;
         vDelta = DBV(radius*Cos(Alpha),radius*Sin(Alpha),0);
         p->vD = vDelta*(RND(Velocity)*radius_inv);
 //      p->vD = Vector(Velocity - RND(SignVelocity),Velocity - RND(SignVelocity),Velocity - RND(SignVelocity));
         p->vR = vPos + Vector(vDelta*256.);
         Alpha += StepAlpha;
     };
 };
References SimpleParticleType::Color, Cos(), cycleTor(), Data, SimpleParticleType::dColor, ParticleInitDataType::EndColor, ParticleInitDataType::FirstColor, ParticleInitDataType::FirstRadius, ParticleInitDataType::LifeTime, LifeTime, BaseObject::MapLevel, Mode, NumParticle, PI, GeneralObject::R_curr, BaseObject::radius, RND(), rPI, Sin(), GeneralObject::Status, Time, SimpleParticleType::vD, ParticleInitDataType::Velocity, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
Referenced by EffectDispatcher::CreateDirectParticle().
CreateParticle() [1/5]
void ParticleObject::CreateParticle (int _LifeTime, int _Velocity, int _FirstRadius, int _EndRadius, int _FirstColor, int _EndColor, const Vector & v1, const Vector & v2)
 {
     int i;
     int Radius,SignRadius,DeltaRadius,SignVelocity,FirstColor,DeltaColor;
     Vector vDelta,vPos;
     SimpleParticleType* p;
     Time = 0;
     Mode = 0;
     LifeTime = _LifeTime;
     FirstColor = _FirstColor << 8;
     DeltaColor = ((_EndColor << 8) - FirstColor) / LifeTime;
     Radius = _FirstRadius << 8;
     DeltaRadius = ((_EndRadius << 8) - Radius) / NumParticle;
     SignVelocity = _Velocity << 1;
     vDelta = Vector(getDistX(v2.x,v1.x),getDistY(v2.y,v1.y),(v2.z - v1.z));
     R_curr.x = vDelta.x >> 1;
     R_curr.y = vDelta.y >> 1;
     R_curr.z = vDelta.z >> 1;
     radius = (R_curr.x > R_curr.y) ? R_curr.x : R_curr.y;
 //  if(radius > 64) ErrH.Abort("Bad Particle Radius");
     R_curr += v1;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
 //  GetVisible();
     MapLevel = 1;
     vDelta <<= 8;
     vDelta /= NumParticle;
     vPos = Vector(v1.x << 8,v1.y << 8,v1.z << 8);
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         SignRadius = Radius << 1;
         p->Color = FirstColor;
         p->dColor = DeltaColor;
         p->vD = Vector(_Velocity - effectRND(SignVelocity),_Velocity - effectRND(SignVelocity),_Velocity - effectRND(SignVelocity));
         p->vR = vPos + Vector(Radius - effectRND(SignRadius),Radius - effectRND(SignRadius),Radius - effectRND(SignRadius));
         vPos += vDelta;
         Radius += DeltaRadius;
     };
 };
References SimpleParticleType::Color, cycleTor(), Data, SimpleParticleType::dColor, effectRND(), getDistX(), getDistY(), LifeTime, BaseObject::MapLevel, Mode, NumParticle, GeneralObject::R_curr, BaseObject::radius, GeneralObject::Status, Time, SimpleParticleType::vD, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
Referenced by EffectDispatcher::CreateParticle(), and EffectDispatcher::CreateParticleTime().
CreateParticle() [2/5]
void ParticleObject::CreateParticle (int _LifeTime, int _Velocity, int _FirstRadius, int _EndRadius, int _FirstColor, int _EndColor, int _StepAlpha, const Vector & v1, const Vector & v2, const DBM & n)
 {
     int i;
     int Radius,SignRadius,DeltaRadius,FirstColor,DeltaColor;
     Vector vDelta,vPos,vMax;
     SimpleParticleType* p;
     int Alpha = 0;
     Time = 0;
     Mode = 0;
     LifeTime = _LifeTime;
     FirstColor = _FirstColor << 8;
     DeltaColor = ((_EndColor << 8) - FirstColor) / LifeTime;
     Radius = _FirstRadius << 8;
     DeltaRadius = ((_EndRadius << 8) - Radius) / NumParticle;
     vDelta = Vector(getDistX(v2.x,v1.x),getDistY(v2.y,v1.y),(v2.z - v1.z));
     R_curr.x = vDelta.x >> 1;
     R_curr.y = vDelta.y >> 1;
     R_curr.z = vDelta.z >> 1;
     radius = (R_curr.x > R_curr.y) ? R_curr.x : R_curr.y;
 //  if(radius > 64) ErrH.Abort("Bad Particle Radius");
     R_curr += v1;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
 //  GetVisible();
     MapLevel = 1;
     vDelta <<= 8;
     vDelta /= NumParticle;
     vPos = Vector(v1.x << 8,v1.y << 8,v1.z << 8);
     vMax = Vector(_Velocity,0,0)*m;
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         SignRadius = Radius << 1;
         p->Color = FirstColor;
         p->dColor = DeltaColor;
         p->vD = vMax*fabs(Cos(Alpha));
         p->vR = vPos + Vector(Radius - effectRND(SignRadius),Radius - effectRND(SignRadius),Radius - effectRND(SignRadius));
         vPos += vDelta;
         Radius += DeltaRadius;
         Alpha += _StepAlpha;
     };
 };
References SimpleParticleType::Color, Cos(), cycleTor(), Data, SimpleParticleType::dColor, effectRND(), getDistX(), getDistY(), LifeTime, BaseObject::MapLevel, Mode, NumParticle, GeneralObject::R_curr, BaseObject::radius, GeneralObject::Status, Time, SimpleParticleType::vD, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
CreateParticle() [3/5]
void ParticleObject::CreateParticle (ParticleInitDataType * n, const Vector & v)
 {
     int i;
     int SignVelocity,FirstColor,DeltaColor,Velocity;
     Vector vDelta,vPos;
     SimpleParticleType* p;
     int Alpha,StepAlpha;
     Time = 0;
     LifeTime = n->LifeTime;
     Mode = 0;
     FirstColor = n->FirstColor << 8;
     DeltaColor = ((n->EndColor << 8) - FirstColor) / LifeTime;
     radius = n->FirstRadius;
     R_curr = v;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
     MapLevel = 1;
     Velocity = n->Velocity;
     SignVelocity = Velocity << 1;
     vPos = Vector(v.x << 8,v.y << 8,v.z << 8);
     StepAlpha = rPI(2*PI / NumParticle);
     Alpha = RND(PI);
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         p->Color = FirstColor;
         p->dColor = DeltaColor;
         p->vD = Vector(Velocity - RND(SignVelocity),Velocity - RND(SignVelocity),Velocity - RND(SignVelocity));
         p->vR = vPos + Vector(radius*COS(Alpha) >> 8,radius*SIN(Alpha) >> 8,0);
         Alpha += StepAlpha;
     };
 };
References SimpleParticleType::Color, COS(), cycleTor(), Data, SimpleParticleType::dColor, ParticleInitDataType::EndColor, ParticleInitDataType::FirstColor, ParticleInitDataType::FirstRadius, ParticleInitDataType::LifeTime, LifeTime, BaseObject::MapLevel, Mode, NumParticle, PI, GeneralObject::R_curr, BaseObject::radius, RND(), rPI, SIN(), GeneralObject::Status, Time, SimpleParticleType::vD, ParticleInitDataType::Velocity, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
CreateParticle() [4/5]
void ParticleObject::CreateParticle (ParticleInitDataType * n, const Vector & v1, const Vector & v2)
 {
     int i;
     int Radius,SignRadius,DeltaRadius,SignVelocity,FirstColor,DeltaColor,Velocity;
     Vector vDelta,vPos;
     SimpleParticleType* p;
     Mode = 0;
     Time = 0;
     LifeTime = n->LifeTime;
     FirstColor = n->FirstColor << 8;
     DeltaColor = ((n->EndColor << 8) - FirstColor) / LifeTime;
     Radius = n->FirstRadius << 8;
     DeltaRadius = ((n->EndRadius << 8) - Radius) / NumParticle;
     Velocity = n->Velocity;
     SignVelocity = Velocity << 1;
     vDelta = Vector(getDistX(v2.x,v1.x),getDistY(v2.y,v1.y),(v2.z - v1.z));
     R_curr.x = vDelta.x >> 1;
     R_curr.y = vDelta.y >> 1;
     R_curr.z = vDelta.z >> 1;
     radius = (R_curr.x > R_curr.y) ? R_curr.x : R_curr.y;
 //  if(radius > 64) ErrH.Abort("Bad Particle Radius");
     R_curr += v1;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
 //  GetVisible();
     MapLevel = 1;
     vDelta <<= 8;
     vDelta /= NumParticle;
     vPos = Vector(v1.x << 8,v1.y << 8,v1.z << 8);
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         SignRadius = Radius << 1;
         p->Color = FirstColor;
         p->dColor = DeltaColor;
         p->vD = Vector(Velocity - effectRND(SignVelocity),Velocity - effectRND(SignVelocity),Velocity - effectRND(SignVelocity));
         p->vR = vPos + Vector(Radius - effectRND(SignRadius),Radius - effectRND(SignRadius),Radius - effectRND(SignRadius));
         vPos += vDelta;
         Radius += DeltaRadius;
     };
 };
References SimpleParticleType::Color, cycleTor(), Data, SimpleParticleType::dColor, effectRND(), ParticleInitDataType::EndColor, ParticleInitDataType::EndRadius, ParticleInitDataType::FirstColor, ParticleInitDataType::FirstRadius, getDistX(), getDistY(), ParticleInitDataType::LifeTime, LifeTime, BaseObject::MapLevel, Mode, NumParticle, GeneralObject::R_curr, BaseObject::radius, GeneralObject::Status, Time, SimpleParticleType::vD, ParticleInitDataType::Velocity, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
CreateParticle() [5/5]
void ParticleObject::CreateParticle (ParticleInitDataType * n, const Vector & v1, const Vector & v2, const DBM & m)
 {
     int i;
     int Radius,SignRadius,DeltaRadius,FirstColor,DeltaColor;
     Vector vDelta,vPos,vMax;
     SimpleParticleType* p;
     int Alpha,StepAlpha;
     Time = 0;
     Mode = 0;
     LifeTime = n->LifeTime;
     FirstColor = n->FirstColor << 8;
     DeltaColor = ((n->EndColor << 8) - FirstColor) / LifeTime;
     Radius = n->FirstRadius << 8;
     DeltaRadius = ((n->EndRadius << 8) - Radius) / NumParticle;
     Alpha = n->FirstAlpha;
     StepAlpha = n->StepAlpha;
     vDelta = Vector(getDistX(v2.x,v1.x),getDistY(v2.y,v1.y),(v2.z - v1.z));
     R_curr.x = vDelta.x >> 1;
     R_curr.y = vDelta.y >> 1;
     R_curr.z = vDelta.z >> 1;
     radius = (R_curr.x > R_curr.y) ? R_curr.x : R_curr.y;
 //  if(radius > 64) ErrH.Abort("Bad Particle Radius");
     R_curr += v1;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
 //  GetVisible();
     MapLevel = 1;
     vDelta <<= 8;
     vDelta /= NumParticle;
     vPos = Vector(v1.x << 8,v1.y << 8,v1.z << 8);
     vMax = Vector(n->Velocity,0,0)*m;
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         SignRadius = Radius << 1;
         p->Color = FirstColor;
         p->dColor = DeltaColor;
         p->vD = vMax*abs(COS(Alpha)) >> 8;
         p->vR = vPos + Vector(Radius - effectRND(SignRadius),Radius - effectRND(SignRadius),Radius - effectRND(SignRadius));
         vPos += vDelta;
         Radius += DeltaRadius;
         Alpha += StepAlpha;
     };
 };
References SimpleParticleType::Color, COS(), cycleTor(), Data, SimpleParticleType::dColor, effectRND(), ParticleInitDataType::EndColor, ParticleInitDataType::EndRadius, ParticleInitDataType::FirstAlpha, ParticleInitDataType::FirstColor, ParticleInitDataType::FirstRadius, getDistX(), getDistY(), ParticleInitDataType::LifeTime, LifeTime, BaseObject::MapLevel, Mode, NumParticle, GeneralObject::R_curr, BaseObject::radius, GeneralObject::Status, ParticleInitDataType::StepAlpha, Time, SimpleParticleType::vD, ParticleInitDataType::Velocity, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
CreateRingOfLord()
void ParticleObject::CreateRingOfLord (const Vector v1, int rad, int ltime, int fcol, int lcol, int vel)
 {
     int i;
     int FirstColor,DeltaColor;
     Vector vDelta,vPos;
     SimpleParticleType* p;
     Mode = 1;
     Time = 0;
     LifeTime = ltime;
     FirstColor = fcol << 8;
     DeltaColor = ((lcol << 8) - FirstColor) / LifeTime;
     radius = rad;
     R_curr = v1;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
     MapLevel = 1;
     Phase = 0;
     dPhase = 2*PI / LifeTime;
     vPos.x = R_curr.x << 8;
     vPos.y = R_curr.y << 8;
     vPos.z = R_curr.z << 8;
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         p->Color = FirstColor;
         p->dColor = DeltaColor;
         p->vD = Vector(0,0,0);
         p->vR = vPos + Vector(vel,0,0);
     };
 };
References SimpleParticleType::Color, cycleTor(), Data, SimpleParticleType::dColor, dPhase, LifeTime, BaseObject::MapLevel, Mode, NumParticle, Phase, PI, GeneralObject::R_curr, BaseObject::radius, GeneralObject::Status, Time, SimpleParticleType::vD, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
Referenced by EffectDispatcher::CreateRingOfLord().
DrawQuant()
void ParticleObject::DrawQuant (void)
 {
     int i;
     SimpleParticleType* p;
     Vector vPos;
     int tx,ty;
     int phi,dphi;
     if(Mode){
         if(Time < LifeTime){
             dphi = (Time*PI << 8) / (2*NumParticle * LifeTime);
             phi = 0;
         }else{
             phi = PI / 2;
             dphi = 0;
         };
         if(AdvancedView){
             for(i = 0,p = Data;i < NumParticle;i++,p++){
                 p->QuantRingOfLord(Vector(R_curr.x << 8,R_curr.y << 8,R_curr.z << 8),abs(25 * SI[rPI(phi >> 8)] >> 8),32);
                 vPos = p->vR;
                 vPos >>= 8;
 //              if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
                     G2LQ(vPos.x,vPos.y,vPos.z,tx,ty);
     //              G2L(vPos.x,vPos.y,tx,ty);
                     if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
 //              };
                 phi += dphi;
             };
         }else{
             if(CurrentWorld < MAIN_WORLD_MAX - 1){
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->QuantRingOfLord(Vector(R_curr.x << 8,R_curr.y << 8,R_curr.z << 8),abs(25 * SI[rPI(phi >> 8)] >> 8),32);
                     vPos = p->vR;
                     vPos >>= 8;
     //              if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
         //              tx = round(SPGetDistX(p->vR.x,SPViewX)*ScaleMapInvFlt) + ScreenCX;
         //              ty = round((p->vR.y - SPViewY) * ScaleMapInvFlt) + ScreenCY;
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round((p->vR.y - SPViewY) * ScaleMapInvFlt) >> 8)+ ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
     //              };
                     phi +=dphi;
                 };
             }else{
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->QuantRingOfLord(Vector(R_curr.x << 8,R_curr.y << 8,R_curr.z << 8),abs(25 * SI[rPI(phi >> 8)] >> 8),32);
                     vPos = p->vR;
                     vPos >>= 8;
     //              if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
         //              tx = round(SPGetDistX(p->vR.x,SPViewX)*ScaleMapInvFlt) + ScreenCX;
         //              ty = round((p->vR.y - SPViewY) * ScaleMapInvFlt) + ScreenCY;
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round(SPGetDistY(p->vR.y,SPViewY) * ScaleMapInvFlt) >> 8) + ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
     //              };
                     phi +=dphi;
                 };
             };
         };
     }else{
         if(AdvancedView){
             for(i = 0,p = Data;i < NumParticle;i++,p++){
                 p->Quant();
                 vPos = p->vR;
                 vPos >>= 8;
                 if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
                     G2LQ(vPos.x,vPos.y,vPos.z,tx,ty);
     //              G2L(vPos.x,vPos.y,tx,ty);
                     if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                 };
             };
         }else{
             if(CurrentWorld < MAIN_WORLD_MAX - 1){
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->Quant();
                     vPos = p->vR;
                     vPos >>= 8;
                     if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
         //              tx = round(SPGetDistX(p->vR.x,SPViewX)*ScaleMapInvFlt) + ScreenCX;
         //              ty = round((p->vR.y - SPViewY) * ScaleMapInvFlt) + ScreenCY;
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round((p->vR.y - SPViewY) * ScaleMapInvFlt) >> 8)+ ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             }else{
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->Quant();
                     vPos = p->vR;
                     vPos >>= 8;
                     if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
         //              tx = round(SPGetDistX(p->vR.x,SPViewX)*ScaleMapInvFlt) + ScreenCX;
         //              ty = round((p->vR.y - SPViewY) * ScaleMapInvFlt) + ScreenCY;
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round(SPGetDistY(p->vR.y,SPViewY) * ScaleMapInvFlt) >> 8) + ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             };
         };
     };
 };
References AdvancedView, SimpleParticleType::Color, CurrentWorld, Data, G2LQ(), GetAltLevel(), LifeTime, MAIN_WORLD_MAX, Mode, NumParticle, PI, SimpleParticleType::Quant(), SimpleParticleType::QuantRingOfLord(), GeneralObject::R_curr, round(), rPI, ScaleMapInvFlt, ScreenCX, ScreenCY, SI, SPGetDistX(), SPGetDistY(), SPViewX, SPViewY, Time, UcutLeft, VcutDown, VcutUp, SimpleParticleType::vR, Vector::x, XGR_SetPixelFast(), Vector::y, and Vector::z.
Free()
void ParticleObject::Free (void)
 {
     delete[] Data;
 };
References Data.
Init()
void ParticleObject::Init (StorageType * s)
 {
     BaseObject::Init(s);
     ID = ID_EXPLOSION;
 };
References GeneralObject::ID, and ID_EXPLOSION.
InitParicle()
void ParticleObject::InitParicle (int num)
 {
     NumParticle = num;
     Data = new SimpleParticleType[NumParticle];
 };
References Data, and NumParticle.
Quant()
void ParticleObject::Quant (void)
 {
     if(DepthShow){
         int xt = getDistX(R_curr.x,ViewX);
         int yy = getDistY(R_curr.y,ViewY);
         int zz = round(A_g2s.a[6]*xt + A_g2s.a[7]*yy) - R_curr.z + ViewZ;
         int xx = round(A_g2s.a[0]*xt + A_g2s.a[1]*yy);
         yy = round(A_g2s.a[3]*xt + A_g2s.a[4]*yy);
         if(zz < -radius || abs(xx) > zz*TurnSideX/ViewZ + radius*2 ||  abs(yy) > zz*TurnSideY/ViewZ + radius*2)
             Visibility = UNVISIBLE;
         else
             Visibility = VISIBLE;
         }
     else{
         if(abs(getDistX(R_curr.x,ViewX)) - (radius << 1) < TurnSideX && abs(getDistY(R_curr.y,ViewY)) -  (radius << 1) < TurnSideY)
             Visibility = VISIBLE;
         else
             Visibility = UNVISIBLE;
         }
     if(Time++ >= LifeTime) Status |= SOBJ_DISCONNECT;
 };
References DBM::a, A_g2s, DepthShow, getDistX(), getDistY(), LifeTime, GeneralObject::R_curr, BaseObject::radius, round(), SOBJ_DISCONNECT, GeneralObject::Status, Time, TurnSideX, TurnSideY, UNVISIBLE, ViewX, ViewY, ViewZ, BaseObject::Visibility, VISIBLE, Vector::x, Vector::y, and Vector::z.
Member Data Documentation
Data
SimpleParticleType* ParticleObject::Data
Referenced by CreateDirectParticle(), CreateParticle(), CreateRingOfLord(), DrawQuant(), Free(), and InitParicle().
dPhase
int ParticleObject::dPhase
Referenced by CreateRingOfLord().
LifeTime
int ParticleObject::LifeTime
Referenced by CreateDirectParticle(), CreateParticle(), CreateRingOfLord(), DrawQuant(), and Quant().
Mode
int ParticleObject::Mode
Referenced by CreateDirectParticle(), CreateParticle(), CreateRingOfLord(), and DrawQuant().
NumParticle
int ParticleObject::NumParticle
Referenced by CreateDirectParticle(), CreateParticle(), CreateRingOfLord(), DrawQuant(), and InitParicle().
Phase
int ParticleObject::Phase
Referenced by CreateRingOfLord().
Time
int ParticleObject::Time
Referenced by CreateDirectParticle(), CreateParticle(), CreateRingOfLord(), DrawQuant(), and Quant().
The documentation for this struct was generated from the following files:
src/units/effect.h
src/units/effect.cpp