Vangers: dgRoom Struct Reference
dgRoom Struct Reference
#include <diagen.h>
Public Member Functions
dgCell * getGRID (int x, int y)
int getSTATUS (int x, int y)
void setGRID (int x, int y, dgCell *pc)
void setSTATUS (int x, int y, uchar val)
void nextState (int x, int y)
void explodeState (int x, int y)
void backup (void)
void restore (void)
dgRoom (DiagenDispatcher *_owner)
void link (dgRoom *&tail)
void read (dgFile *pf)
void locateActiveMolecule (void)
void acceptTEXT (void)
void acceptDIL (void)
void acceptQUERY (void)
void startSession (void)
void endSession (void)
dgMolecule * getCurrentMolecule (void)
int isEmptySession (void)
void setCell (char *name, int value)
void updateLevel (void)
dgQuery * seekQall (char *_subj)
dgQuery * seekQvisible (char *_subj)
dgMolecule * seekM (const char *_name)
void save (XStream &ff)
void load (XStream &ff)
Public Attributes
const char * roomName
const char * escaveNames [2]
char * counsillorNames [2]
char * worldNames [2]
int bios
int repeatable
dgCell ** grid
uchar * status
uchar * backup_status
int gridSX
int gridSY
int startX
int startY
int cIndex
dgMolecule * currentM
dgMolecule * mtail
dgQuery * qAtail
dgQuery * qVtail
DiagenDispatcher * owner
dgRoom * next
dgRoom * prev
char * prefixQ
char * postfixQ
int visitCounter
int comingCounter
Detailed Description
Constructor & Destructor Documentation
dgRoom()
dgRoom::dgRoom (DiagenDispatcher * _owner) inline
                                         { roomName = NULL;
                                         escaveNames[0] = escaveNames[1] = NULL;
                                         counsillorNames[0] = counsillorNames[1] = NULL;
                                         worldNames[0] = worldNames[1] = NULL;
                                         mtail = NULL; owner = _owner;
                                         grid = NULL; gridSX = gridSY = 0;
                                         startX = startY = 0;
                                         status = backup_status = NULL; cIndex = -1;
                                         currentM = NULL; visitCounter = comingCounter = 0;
                                         prefixQ = postfixQ = NULL;
                                         qAtail = qVtail = NULL;
                                         bios = 0; repeatable = 0;
                                         }
References backup_status, bios, cIndex, comingCounter, counsillorNames, currentM, escaveNames, grid, gridSX, gridSY, mtail, NULL, owner, postfixQ, prefixQ, qAtail, qVtail, repeatable, roomName, startX, startY, status, visitCounter, and worldNames.
Member Function Documentation
acceptDIL()
void dgRoom::acceptDIL (void)
 {
     //std::cout<<"dgRoom::acceptDIL "<<getDGname(roomName,".dil")<<std::endl;
     dgFile* dgf = new dgFile(getDGname(roomName,".dil"));
     gridSX = atoi(dgf -> getElement(DGF_NONE));
     gridSY = atoi(dgf -> getElement(DGF_NONE));
     memset(grid = new dgCell*[gridSX*gridSY],0,sizeof(dgCell*)*gridSX*gridSY);
     memset(status = new uchar[2*gridSX*gridSY],DG_CELLSTATUS::EMPTY,2*gridSX*gridSY);
     backup_status = status + gridSX*gridSY;
     int num = atoi(dgf -> getElement(DGF_NONE)),i;
     dgf -> getElement(DGF_NONE);
     dgCell* pc;
     for(i = 0;i < num;i++){
         (pc = new dgCell(this)) -> read(dgf);
         setGRID(pc -> x,pc -> y,pc);
         setSTATUS(pc -> x,pc -> y,DG_CELLSTATUS::DORMANT);
         }
     if(getSTATUS(startX,startY) != DG_CELLSTATUS::EMPTY){
         setSTATUS(startX,startY,DG_CELLSTATUS::WAITING);
         explodeState(startX,startY);
         }
 }
References backup_status, DGF_NONE, DG_CELLSTATUS::DORMANT, DG_CELLSTATUS::EMPTY, explodeState(), getDGname(), getSTATUS(), grid, gridSX, gridSY, read(), roomName, setGRID(), setSTATUS(), startX, startY, status, and DG_CELLSTATUS::WAITING.
acceptQUERY()
void dgRoom::acceptQUERY (void)
 {
     static dgAtom* adim[64];
     static int ldim[64];
     //std::cout<<"dgRoom::acceptQUERY "<<getDGname(roomName,".query")<<std::endl;
     dgFile* pf = new dgFile(getDGname(roomName,".query"));
     prefixQ = pf -> getElement(DGF_DUAL,1);
     postfixQ = pf -> getElement(DGF_DUAL,1);
     char* p = NULL;
     int m;
     dgQuery* pq;
     int i,j;
     while(1) {
         if(!p) {
             if(!(p = pf -> getElement(DGF_DUAL,1))) {
                 break;
             }
         }
         (pq = new dgQuery) -> link(qAtail);
         pq -> subj0 = getSubj(p,m);
         p = pf -> getElement(DGF_DUAL);
         pq -> subj1 = getSubj(p,m);//problem
         if (lang() == GERMAN) {
             pq -> subj = pq -> subj0;
         } else if (lang() == RUSSIAN) {
             pq -> subj = pq -> subj0;
         } else {
             pq -> subj = pq -> subj1;
         }
         pq -> mood = m;
         i = j = 0;
         p = pf -> getElement(DGF_DUAL);
         while(p) {
             if(*p == SUBJ_SYMBOL) {
                 break;
             }
             if(*p == COMMAND_SYMBOL) {
                 i = ldim[j] = atoi(p + 1);
                 p = pf -> getElement(DGF_DUAL);
             } else {
                 ldim[j] = i;
             }
             adim[j] = new dgAtom;
             p = adim[j++] -> read(pf,p);
             i++;
         }
         if(!j) {
             XBuffer m;
             m < "Empty query in " < roomName;
             ErrH.Abort(m.GetBuf(),XERR_USER,-1,pq -> subj);
         }
         pq -> nanswer = j;
         pq -> answers = new dgAtom*[2*j];
         pq -> levels = (int*)(pq -> answers + j);
         for(i = 0;i < j;i++) {
             pq -> answers[i] = adim[i];
             pq -> levels[i] = ldim[i];
         }
         if(!p) {
             break;
         }
     }
 }
References XErrorHandler::Abort(), COMMAND_SYMBOL, DGF_DUAL, ErrH, GERMAN, XBuffer::GetBuf(), getDGname(), getSubj(), lang(), link(), NULL, pf, postfixQ, prefixQ, qAtail, read(), roomName, RUSSIAN, SUBJ_SYMBOL, and XERR_USER.
acceptTEXT()
void dgRoom::acceptTEXT (void)
 {
     //std::cout<<"dgRoom::acceptTEXT "<<getDGname(roomName,".text")<<std::endl;
     dgFile* dgf = new dgFile(getDGname(roomName,".text"));
     char* p = NULL;
     int m;
     dgMolecule* pm;
     dgAtom* pa;
     while(1) {
         if(!p) {
             if(!(p = dgf -> getElement(DGF_DUAL,1)))
                 break;
         }
         (pm = new dgMolecule(getSubj(p,m))) -> link(mtail);
         pm -> mood = m;
         p = dgf -> getElement(DGF_DUAL);
         while(p){
             if(*p == SUBJ_SYMBOL) break;
             (pa = new dgAtom) -> link(pm -> tail);
             p = pa -> read(dgf,p);
         }
         if(!pm -> tail) {
             delete dgf;
             XBuffer m;
             m < "Empty molecule: " < pm -> name;
             ErrH.Abort(m.GetBuf(), XERR_USER, -1, roomName);
         }
         if(!p) break;
     }
     delete dgf;
 }
References XErrorHandler::Abort(), DGF_DUAL, ErrH, XBuffer::GetBuf(), getDGname(), getSubj(), link(), mtail, NULL, read(), roomName, SUBJ_SYMBOL, and XERR_USER.
backup()
void dgRoom::backup (void) inline
 { memcpy(backup_status,status,gridSX*gridSY); }
References backup_status, gridSX, gridSY, and status.
endSession()
void dgRoom::endSession (void)
 {
     if(checkStatus) restore();
     else
         if(!repeatable && !((aciEscaveEmpty || aciEscaveDead))){
             owner -> restHandle(currentM);
             for(cIndex = 0;cIndex < gridSX*gridSY;cIndex++)
                 switch(status[cIndex]){
                     case DG_CELLSTATUS::WAITING:
                         if(grid[cIndex] -> isACCESS()){
                             status[cIndex] = DG_CELLSTATUS::OPENED;
                             currentM = seekM(grid[cIndex] -> Name);
                             if(currentM) currentM -> reset();
                             owner -> restHandle(currentM);
                             grid[cIndex] -> doCMD(1);
                             grid[cIndex] -> doCMD(0);
                             }
                         break;
                     }
             }
     currentM = NULL;
     if(!checkStatus && !(aciEscaveEmpty || aciEscaveDead)){
         int i,j,ind = 0;
         for(j = 0;j < gridSY;j++)
             for(i = 0;i < gridSX;i++,ind++)
                 switch(getSTATUS(i,j)){
                     case DG_CELLSTATUS::EXPLODED:
                     case DG_CELLSTATUS::OPENED:
                         if(grid[ind] -> isLooping)
                             setSTATUS(i,j,DG_CELLSTATUS::WAITING);
                         else {
                             explodeState(i,j);
                             setSTATUS(i,j,DG_CELLSTATUS::USED);
                             }
                         break;
                     case DG_CELLSTATUS::HALFLIFE:
                         setSTATUS(i,j,DG_CELLSTATUS::WAITING);
                         break;
                     }
         }
 }
explodeState()
void dgRoom::explodeState (int x, int y)
 {
     nextState(x - 1,y);
     nextState(x + 1,y);
     nextState(x,y - 1);
     nextState(x,y + 1);
 }
References nextState().
Referenced by acceptDIL(), and nextState().
getCurrentMolecule()
dgMolecule * dgRoom::getCurrentMolecule (void)
 {
     if(currentM && !currentM -> curA && cIndex >= 0 && grid[cIndex]){
         if(repeatable && status[cIndex] == DG_CELLSTATUS::HALFLIFE) status[cIndex] = DG_CELLSTATUS::EXPLODED;
         grid[cIndex] -> doCMD(0);
         }
     if(!currentM || (currentM && !currentM -> curA)) locateActiveMolecule();
     return currentM;
 }
References cIndex, currentM, DG_CELLSTATUS::EXPLODED, grid, DG_CELLSTATUS::HALFLIFE, locateActiveMolecule(), repeatable, and status.
Referenced by DiagenDispatcher::getNextPhrase().
getGRID()
dgCell* dgRoom::getGRID (int x, int y) inline
 { if(x < 0 || x >= gridSX || y < 0 || y >= gridSY) return NULL; return *(grid + y*gridSX + x); }
References grid, gridSX, gridSY, and NULL.
Referenced by nextState().
getSTATUS()
int dgRoom::getSTATUS (int x, int y) inline
 { if(x < 0 || x >= gridSX || y < 0 || y >= gridSY) return DG_CELLSTATUS::EMPTY; return *(status + y*gridSX + x); }
References DG_CELLSTATUS::EMPTY, gridSX, gridSY, and status.
Referenced by acceptDIL(), and nextState().
isEmptySession()
int dgRoom::isEmptySession (void)
 {
     if(checkStatus) return 0;
     for(int i = 0;i < gridSX*gridSY;i++)
         switch(status[i]){
             case DG_CELLSTATUS::WAITING:
                 if(!grid[i] -> isACCESS()) continue;
             case DG_CELLSTATUS::OPENED:
                 if(!strcasecmp(grid[i] -> Name,"empty") || ClearStatus) continue;
                 return 0;
             }
     return 1;
 }
link()
void dgRoom::link (dgRoom *& tail)
 {
     if(!tail) tail = this;
     else {
         tail -> prev -> next = this;
         prev = tail -> prev;
         }
     next = NULL;
     tail -> prev = this;
 }
References next, NULL, and prev.
Referenced by acceptQUERY(), acceptTEXT(), and load().
load()
void dgRoom::load (XStream & ff)
 {
     currentM = NULL;
     ff > visitCounter > comingCounter;
     char buf[256];
     int n = gridSX*gridSY,i,ind;
     short cnt;
     uchar l;
 /*
     if(loadedVersion == 0){
         ff > cIndex;
         dgRoom* r = nDD -> seekR(roomName);
         ff.read(r -> status,gridSX*gridSY);
         for(ind = DG_CELLSTATUS::USED;ind <= DG_CELLSTATUS::EXPLODED;ind++){
             for(i = 0;i < n;i++)
                 if(r -> status[i] == ind && r -> grid[i])
                     setCell(r -> grid[i] -> Name,ind);
             }
         }
     else {
 */
         for(ind = DG_CELLSTATUS::USED;ind <= DG_CELLSTATUS::EXPLODED;ind++){
             ff > cnt;
             for(i = 0;i < cnt;i++){
                 ff > l;
                 ff.read(buf,l + 1);
                 setCell(buf,ind);
                 }
             }
 //      }
     dgQuery* q;
     int num;
     short len,li;
     ff > num;
     for(i = 0;i < num;i++){
         ff > len > li;
         ff.read(buf,len + 1);
         if((q = seekQall(buf)) != NULL){
             (q -> delink(qAtail)) -> link(qVtail);
             q -> lindex = li;
             }
         }
 }
References comingCounter, currentM, DG_CELLSTATUS::EXPLODED, gridSX, gridSY, link(), NULL, qAtail, qVtail, XStream::read(), seekQall(), setCell(), DG_CELLSTATUS::USED, and visitCounter.
locateActiveMolecule()
void dgRoom::locateActiveMolecule (void)
 {
     owner -> varAtom = NULL;
     currentM = NULL;
     for(cIndex = 0;cIndex < gridSX*gridSY;cIndex++)
         switch(status[cIndex]){
             case DG_CELLSTATUS::WAITING:
                 if(!grid[cIndex] -> isACCESS()) continue;
                 status[cIndex] = DG_CELLSTATUS::OPENED;
             case DG_CELLSTATUS::OPENED:
                 if(!strcasecmp(grid[cIndex] -> Name,"empty") || ClearStatus) continue;
                 currentM = seekM(grid[cIndex] -> Name);
                 currentM -> reset();
 #ifdef DIAGEN_TEST
                 if(!checkStatus) std::cout << "\n   Molecule [" << currentM -> name << "] involved (mood " << currentM -> mood << "):" << "\n";
 #endif
                 if(grid[cIndex] -> doCMD()) explodeState(cIndex%gridSX,cIndex/gridSX);
 #ifdef DIAGEN_TEST
                 if(!checkStatus) std::cout << "\n";
 #endif
                 status[cIndex] = repeatable ? DG_CELLSTATUS::HALFLIFE : DG_CELLSTATUS::EXPLODED;
                 return;
             }
     cIndex--;
 }
References cIndex, currentM, grid, gridSX, gridSY, NULL, DG_CELLSTATUS::OPENED, owner, status, and DG_CELLSTATUS::WAITING.
Referenced by getCurrentMolecule().
nextState()
void dgRoom::nextState (int x, int y)
 {
     if(x < 0 || x >= gridSX || y < 0 || y >= gridSY) return;
     if(getSTATUS(x,y) == DG_CELLSTATUS::DORMANT){
         setSTATUS(x,y,DG_CELLSTATUS::WAITING);
         if(!getGRID(x,y) -> isWaiting) explodeState(x,y);
         }
 }
References DG_CELLSTATUS::DORMANT, explodeState(), getGRID(), getSTATUS(), gridSX, gridSY, setSTATUS(), and DG_CELLSTATUS::WAITING.
Referenced by explodeState().
read()
void dgRoom::read (dgFile * pf)
 {
     roomName = getSubj(pf -> getElement(DGF_NONE));
     escaveNames[0] = roomName;
 //#if defined(RUSSIAN_VERSION) || defined(DIAGEN_TEST)
     escaveNames[1] = pf -> getElement(DGF_NONE);
 //#endif
     counsillorNames[0] = getSubj(pf -> getElement(DGF_NONE));
 //#if defined(RUSSIAN_VERSION) || defined(DIAGEN_TEST)
     counsillorNames[1] = pf -> getElement(DGF_NONE);
 //#endif
     if(!oldVersion) bios = atoi(pf -> getElement(DGF_NONE));
     worldNames[0] = getSubj(pf -> getElement(DGF_NONE));
 //#if defined(RUSSIAN_VERSION) || defined(DIAGEN_TEST)
     worldNames[1] = pf -> getElement(DGF_NONE);
 //#endif
     startX = atoi(pf -> getElement(DGF_NONE));
     startY = atoi(pf -> getElement(DGF_NONE));
     int MPstartX = atoi(pf -> getElement(DGF_NONE));
     int MPstartY = atoi(pf -> getElement(DGF_NONE));
     if(NetworkON){
         startX = MPstartX;
         startY = MPstartY;
         }
     if(!oldVersion) repeatable = atoi(pf -> getElement(DGF_NONE));
     acceptTEXT();
     acceptDIL();
     acceptQUERY();
 #ifdef DIAGEN_TEST
     dgMolecule* m = mtail;
     static XStream ff("Check.LOG",XS_OUT);
     ff < "***Escave: " < roomName < "\r\n";
     int i;
     while(m){
         for(i = 0;i < gridSX*gridSY;i++)
             if(grid[i] && !strcmp(m -> name,grid[i] -> Name)) break;
         if(i == gridSX*gridSY) ff < "Unattached molecule: " < m -> name < "\r\n";
         m = m -> next;
         }
     ff < "\r\n";
 #endif
 }
References counsillorNames, DGF_NONE, escaveNames, getSubj(), pf, and roomName.
Referenced by acceptDIL(), acceptQUERY(), and acceptTEXT().
restore()
void dgRoom::restore (void) inline
 { memcpy(status,backup_status,gridSX*gridSY); }
References backup_status, gridSX, gridSY, and status.
save()
void dgRoom::save (XStream & ff)
 {
     ff < visitCounter < comingCounter;
     int n = gridSX*gridSY;
     int cnt,i;
     char* name;
     for(int ind = DG_CELLSTATUS::USED;ind <= DG_CELLSTATUS::EXPLODED;ind++){
         for(cnt = 0,i = 0;i < n;i++) if(status[i] == ind) cnt++;
         ff < (short)cnt;
         for(i = 0;i < n;i++)
             if(status[i] == ind){
                 name = seekM(grid[i] -> Name) -> name;
                 ff < (uchar)strlen(name);
                 ff.write(name,strlen(name) + 1);
                 }
         }
     int num = 0;
     dgQuery* q = qVtail;
     while(q){
         num++;
         q = q -> next;
         }
     ff < num;
     q = qVtail;
     while(q){
         ff < (short)strlen(q -> subj) < (short)q -> lindex;
         ff.write(q -> subj,strlen(q -> subj) + 1);
         q = q -> next;
         }
 }
References comingCounter, DG_CELLSTATUS::EXPLODED, grid, gridSX, gridSY, next, qVtail, seekM(), status, DG_CELLSTATUS::USED, visitCounter, and XStream::write().
seekM()
dgMolecule * dgRoom::seekM (const char * _name)
 {
     dgMolecule* m = mtail;
     while(m){
         if(!strcmp(m -> name,_name)) return m;
         m = m -> next;
         }
 #ifdef DIAGEN_TEST
     XBuffer buf;
     buf < _name < "/" < roomName;
     ErrH.Abort("Molecule not found",XERR_USER,-1,buf.GetBuf());
 #else
 //  ErrH.Abort("Molecule not found",XERR_USER,-1,_name);
 #endif
     return NULL;
 }
References XErrorHandler::Abort(), ErrH, XBuffer::GetBuf(), mtail, next, NULL, roomName, and XERR_USER.
Referenced by save().
seekQall()
dgQuery * dgRoom::seekQall (char * _subj)
 {
     if(!_subj) return NULL;
     dgQuery* q = qAtail;
     while(q){
         if(!strcmp(q -> subj,_subj)) return q;
         q = q -> next;
         }
 //#ifndef DIAGEN_TEST
 //  ErrH.Abort("Query not found",XERR_USER,-1,_subj);
 //#endif
     return NULL;
 }
References next, NULL, and qAtail.
Referenced by load().
seekQvisible()
dgQuery * dgRoom::seekQvisible (char * _subj)
 {
     if(!_subj) return NULL;
     dgQuery* q = qVtail;
     while(q){
         if(!strcmp(q -> subj,_subj)) return q;
         q = q -> next;
         }
 //#ifndef DIAGEN_TEST
 //  ErrH.Abort("Query not found",XERR_USER,-1,_subj);
 //#endif
     return NULL;
 }
References next, NULL, and qVtail.
setCell()
void dgRoom::setCell (char * name, int value)
 {
     for(int i = 0;i < gridSX*gridSY;i++)
         if(grid[i] && !strcasecmp(name,grid[i] -> Name))
             status[i] = value;
 //  ErrH.Abort("Wrong setCell() working",XERR_USER,-1,name);
 }
References grid, gridSX, gridSY, and status.
Referenced by load().
setGRID()
void dgRoom::setGRID (int x, int y, dgCell * pc) inline
 { if(x < 0 || x >= gridSX || y < 0 || y >= gridSY) return; *(grid + y*gridSX + x) = pc; }
References grid, gridSX, and gridSY.
Referenced by acceptDIL().
setSTATUS()
void dgRoom::setSTATUS (int x, int y, uchar val) inline
 { if(x < 0 || x >= gridSX || y < 0 || y >= gridSY) return; *(status + y*gridSX + x) = val; }
References gridSX, gridSY, and status.
Referenced by acceptDIL(), and nextState().
startSession()
void dgRoom::startSession (void)
 {
     currentM = NULL;
     Qcode = eventOUT = 0;
     owner -> endSessionLog = isEmptySession();
     cIndex = -1;
     if(!isLoading){
         singleRandAvailable = 1;
         ClearStatus = 0;
         }
     updateLevel();
     solidQ = (bios == 1);
 //#ifndef DIAGEN_TEST
     aciEscaveDead = uvsCurrentWorldUnableBefore;
     aciEscaveEmpty = (*roomName == 'V' && !uvsgetDGdata(DG_EXTERNS::HERE_BOORAWCHICK));
 //#endif
     if(checkStatus) backup();
 }
References currentM, and NULL.
updateLevel()
void dgRoom::updateLevel (void)
 {
     switch(bios){
         case 0: dgLevel = &owner -> eStatus; break;
         case 1: dgLevel = &owner -> bStatus; break;
         case 2: dgLevel = &owner -> zStatus; break;
         case 3: dgLevel = &owner -> sStatus; break;
         }
 }
References bios.
Member Data Documentation
backup_status
uchar* dgRoom::backup_status
Referenced by acceptDIL(), backup(), dgRoom(), and restore().
bios
int dgRoom::bios
Referenced by dgRoom(), and updateLevel().
cIndex
int dgRoom::cIndex
Referenced by dgRoom(), getCurrentMolecule(), and locateActiveMolecule().
comingCounter
int dgRoom::comingCounter
Referenced by dgRoom(), load(), and save().
counsillorNames
char* dgRoom::counsillorNames[2]
Referenced by dgRoom(), and read().
currentM
dgMolecule* dgRoom::currentM
Referenced by dgRoom(), getCurrentMolecule(), load(), locateActiveMolecule(), and startSession().
escaveNames
const char* dgRoom::escaveNames[2]
Referenced by dgRoom(), and read().
grid
dgCell** dgRoom::grid
Referenced by acceptDIL(), dgRoom(), getCurrentMolecule(), getGRID(), locateActiveMolecule(), save(), setCell(), and setGRID().
gridSX
int dgRoom::gridSX
Referenced by acceptDIL(), backup(), dgRoom(), getGRID(), getSTATUS(), load(), locateActiveMolecule(), nextState(), restore(), save(), setCell(), setGRID(), and setSTATUS().
gridSY
int dgRoom::gridSY
Referenced by acceptDIL(), backup(), dgRoom(), getGRID(), getSTATUS(), load(), locateActiveMolecule(), nextState(), restore(), save(), setCell(), setGRID(), and setSTATUS().
mtail
dgMolecule* dgRoom::mtail
Referenced by acceptTEXT(), dgRoom(), and seekM().
next
dgRoom* dgRoom::next
Referenced by link(), save(), seekM(), seekQall(), and seekQvisible().
owner
DiagenDispatcher* dgRoom::owner
Referenced by dgRoom(), and locateActiveMolecule().
postfixQ
char * dgRoom::postfixQ
Referenced by acceptQUERY(), and dgRoom().
prefixQ
char* dgRoom::prefixQ
Referenced by acceptQUERY(), and dgRoom().
prev
dgRoom* dgRoom::prev
Referenced by link().
qAtail
dgQuery* dgRoom::qAtail
Referenced by acceptQUERY(), dgRoom(), load(), and seekQall().
qVtail
dgQuery* dgRoom::qVtail
Referenced by dgRoom(), load(), save(), and seekQvisible().
repeatable
int dgRoom::repeatable
Referenced by dgRoom(), and getCurrentMolecule().
roomName
const char* dgRoom::roomName
Referenced by acceptDIL(), acceptQUERY(), acceptTEXT(), dgRoom(), read(), and seekM().
startX
int dgRoom::startX
Referenced by acceptDIL(), and dgRoom().
startY
int dgRoom::startY
Referenced by acceptDIL(), and dgRoom().
status
uchar* dgRoom::status
Referenced by acceptDIL(), backup(), dgRoom(), getCurrentMolecule(), getSTATUS(), locateActiveMolecule(), restore(), save(), setCell(), and setSTATUS().
visitCounter
int dgRoom::visitCounter
Referenced by dgRoom(), load(), and save().
worldNames
char* dgRoom::worldNames[2]
Referenced by dgRoom().
The documentation for this struct was generated from the following files:
src/uvs/diagen.h
src/uvs/diagen.cpp