Vangers: uvsTabuTaskType Struct Reference
uvsTabuTaskType Struct Reference
#include <univang.h>
Public Member Functions
uvsTabuTaskType (PrmFile *pfile, char *atom)
~uvsTabuTaskType (void)
void activate (void)
void activateVANGER (void)
void activateDOLLY (void)
int is_able (void)
int checkCycleEvent (int, int &)
int Erase (int, int &)
Public Member Functions inherited from listElem
listElem (void)
void link (listElem *&tail)
listElem * seekName (const char *name)
virtual char * GetName (void)
Public Attributes
int status
int cash
int luck
int cycle
int target
int work_on_target
int item_number
int * item
int * item_count
int * real_count
int param
int priority
uvsTarget * Ptarget
uvsWorld * Pworld
Public Attributes inherited from listElem
listElem * next
listElem * prev
Detailed Description
Constructor & Destructor Documentation
uvsTabuTaskType()
uvsTabuTaskType::uvsTabuTaskType (PrmFile * pfile, char * atom)
{
     uvsEscave *pe = NULL;
     uvsSpot *ps = NULL;
     int i;
     pe = (uvsEscave*)EscaveTail -> seekName( atom );
     ps = (uvsSpot*)SpotTail -> seekName( atom );
     if (ps || pe){
         if (_pe_) _pe_ -> TabuTaskCount = MAX_TABUTASK - _pe_ -> TabuTaskID;
         if (_ps_) _ps_ -> TabuTaskCount = MAX_TABUTASK - _ps_ -> TabuTaskID;
         if (pe) {
             pe -> TabuTaskID = MAX_TABUTASK;
             _pe_ = pe;
             _ps_ = NULL;
         }
         if (ps) {
             ps -> TabuTaskID = MAX_TABUTASK;
             _ps_ = ps;
             _pe_ = NULL;
         }
         atom = pfile -> getAtom();
     }
     MAX_TABUTASK++;
     cash = atoi(atom);                  //  стоимость
     luck = atoi(pfile -> getAtom());            //  параметр удачи
     cycle  = atoi(pfile -> getAtom());      //  время в циклах
     target = uvsTagetID(pfile -> getAtom());    //  тип-обьект задания
     if (target == UVS_TARGET::ESCAVE || target == UVS_TARGET::SPOT){
         atom = pfile -> getAtom();
     }
     work_on_target = uvsTagetWorkID(pfile -> getAtom());    //  цель для обьукта
     item_number = atoi(pfile -> getAtom()); //  количество предметов
     item = new int[item_number];
     item_count = new int[item_number];
     real_count = new int[item_number];
     for( i = 0; i < item_number; i++){
         if ( target != UVS_TARGET::VANGERS )
             item[i] = GetItem_as_name(pfile -> getAtom());  //  предмет дя задания
         else
             item[i] = atoi(pfile -> getAtom());
         item_count[i] = atoi(pfile -> getAtom());           //  количество для задания
         real_count[i] = 0;
     }
     status = 0;
     if ( target != UVS_TARGET::RACE)
         *real_count  = 0;
     else {
         *real_count = atoi(pfile -> getAtom());
         param = GetMechos_as_name(pfile -> getAtom());
     }
     Ptarget = NULL;
     if ( target == UVS_TARGET::ESCAVE ){
         uvsEscave *pe = (uvsEscave*)EscaveTail -> seekName(atom);
         if (pe)
             Ptarget = (uvsTarget*)pe;
         else
             ErrH.Abort("uvsTabuTaskType :: Bad Escave Name");
     } else if ( target == UVS_TARGET::SPOT){
         uvsSpot *ps = (uvsSpot*)SpotTail -> seekName(atom);
         if (ps)
             Ptarget = (uvsTarget*)ps;
         else
             ErrH.Abort("uvsTabuTaskType :: Bad Spot Name");
     }
     Pworld = (uvsWorld*)WorldTail -> seekName(pfile -> getAtom());
     if (!Pworld)
         ErrH.Abort("uvsTabuTaskType :: Bad World Name");
     priority = atoi(pfile -> getAtom());
 }
References EscaveTail, NULL, listElem::seekName(), and SpotTail.
~uvsTabuTaskType()
uvsTabuTaskType::~uvsTabuTaskType (void)
{
     delete[] item;
     delete[] item_count;
     delete[] real_count;
 }
Member Function Documentation
activate()
void uvsTabuTaskType::activate (void)
{
     int i;
     if (status == UVS_TABUTASK_STATUS::ACTIVE) return;
     status = UVS_TABUTASK_STATUS::ACTIVE;
     switch( target ){
     case UVS_TARGET::RACE:
         break;
     case UVS_TARGET::DOLLY:
         *real_count = 0;
         activateDOLLY();
         break;
     case UVS_TARGET::VANGER:
         *real_count = 0;
         activateVANGER();
         break;
     case UVS_TARGET::VANGERS:
     case UVS_TARGET::ESCAVE:
     case UVS_TARGET::SPOT:
     case UVS_TARGET::PASSAGE:
     case UVS_TARGET::ITEM:
     case UVS_TARGET::FLY_FARMER:
     case UVS_TARGET::BEEB:
     case UVS_TARGET::GRIB:
     case UVS_TARGET::HIVE:
     case UVS_TARGET::CRYPT:
     case UVS_TARGET::WHIRLPOOL:
     case UVS_TARGET::SWAMP:
     case UVS_TARGET::SHEILD:
     case UVS_TARGET::RAFFA:
         for( i = 0; i < item_number; i++)
             real_count[i] = 0;
         break;
     case UVS_TARGET::NONE:
         break;
     };
 }
References activateDOLLY(), activateVANGER(), UVS_TABUTASK_STATUS::ACTIVE, UVS_TARGET::BEEB, UVS_TARGET::CRYPT, UVS_TARGET::DOLLY, UVS_TARGET::ESCAVE, UVS_TARGET::FLY_FARMER, UVS_TARGET::GRIB, UVS_TARGET::HIVE, UVS_TARGET::ITEM, item_number, UVS_TARGET::NONE, UVS_TARGET::PASSAGE, UVS_TARGET::RACE, UVS_TARGET::RAFFA, real_count, UVS_TARGET::SHEILD, UVS_TARGET::SPOT, status, UVS_TARGET::SWAMP, target, UVS_TARGET::VANGER, UVS_TARGET::VANGERS, and UVS_TARGET::WHIRLPOOL.
activateDOLLY()
void uvsTabuTaskType::activateDOLLY (void)
{
     switch(work_on_target){
     case UVS_TABUTASK_WORK::CHANGE_CYCLE:
         *real_count = Gamer -> Pworld -> escT[0] -> Pbunch -> nextCycle() + 1;
         break;
     };
 }
References UVS_TABUTASK_WORK::CHANGE_CYCLE, Gamer, Pworld, real_count, and work_on_target.
Referenced by activate().
activateVANGER()
void uvsTabuTaskType::activateVANGER (void)
{
     uvsVanger *pv = FindFreeVanger();
     switch(work_on_target){
     case UVS_TABUTASK_WORK::GO_OUT:
         pv -> goNewEscave();
         if (pv -> Pescave){
             pv -> pos_x = pv -> Pescave -> pos_x + 1024;
             pv -> pos_y = pv -> Pescave -> pos_y;
         }else{
             pv -> pos_x = pv -> Pspot -> pos_x + 1024;
             pv -> pos_y = pv -> Pspot -> pos_y;
         }
         pv -> status = UVS_VANGER_STATUS::FREE_MOVEMENT;
         Ptarget = (uvsTarget*)pv;
         break;
     case UVS_TABUTASK_WORK::KILL:
         if (pv -> Pescave){
             pv -> set_target(pv -> Pworld -> sptT[0], UVS_TARGET::SPOT);
             pv -> pos_x = pv -> Pescave -> pos_x + 1024;
             pv -> pos_y = pv -> Pescave -> pos_y;
         }else{
             pv -> set_target(pv -> Pworld -> escT[0], UVS_TARGET::ESCAVE);
             pv -> pos_x = pv -> Pspot -> pos_x + 1024;
             pv -> pos_y = pv -> Pspot -> pos_y;
         }
         pv -> addInventory();
         pv -> status = UVS_VANGER_STATUS::FREE_MOVEMENT;
         Ptarget = (uvsTarget*)pv;
         break;
     case UVS_TABUTASK_WORK::DEFENSE:
         if (pv -> Pescave)
             pv -> set_target(pv -> Pescave, UVS_TARGET::ESCAVE);
         else
             pv -> set_target(pv -> Pspot, UVS_TARGET::SPOT);
         pv -> pos_x = pv -> Pworld -> pssT[0] -> pos_x + 1024;
         pv -> pos_y = pv -> Pworld -> pssT[0] -> pos_y;
         pv -> addInventory();
         pv -> status = UVS_VANGER_STATUS::FREE_MOVEMENT;
         Ptarget = (uvsTarget*) pv;
         break;
     };
 }
References UVS_TABUTASK_WORK::DEFENSE, UVS_TARGET::ESCAVE, FindFreeVanger(), UVS_VANGER_STATUS::FREE_MOVEMENT, UVS_TABUTASK_WORK::GO_OUT, UVS_TABUTASK_WORK::KILL, Ptarget, Pworld, UVS_TARGET::SPOT, status, and work_on_target.
Referenced by activate().
checkCycleEvent()
int uvsTabuTaskType::checkCycleEvent (int param1, int & param2)
{
     if ((param1 > cycle) && (status == UVS_TABUTASK_STATUS::ACTIVE)){
         switch( target ){
         case UVS_TARGET::PASSAGE:
         case UVS_TARGET::SPOT:
         case UVS_TARGET::ESCAVE:
         case UVS_TARGET::RACE:
         case UVS_TARGET::VANGERS:
             param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
             ShowTaskMessage(-luck);
             GamerResult.luck -=  luck;
             if (GamerResult.luck < 0) GamerResult.luck = 0;
             status = UVS_TABUTASK_STATUS::SLEEP;
             break;
         case UVS_TARGET::DOLLY:
             if (work_on_target == UVS_TABUTASK_WORK::END_CYCLE_IN_WATER && FuckOFFinWater()){
                 param2 |= ((int)(UVS_TABUTASK_STATUS::GOOD)<<16);
                 uvsChangeTownTabuTask(param2 & 0x0000FFFF);
                 ShowTaskMessage(luck);
                 GamerResult.luck += luck;
                 if (GamerResult.luck > 100) GamerResult.luck = 100;
                 status = UVS_TABUTASK_STATUS::OK;
             } else {
                 param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
                 ShowTaskMessage(-luck);
                 GamerResult.luck -=  luck;
                 if (GamerResult.luck < 0) GamerResult.luck = 0;
                 status = UVS_TABUTASK_STATUS::SLEEP;
             }
             break;
         case UVS_TARGET::VANGER:
             switch(work_on_target){
             case UVS_TABUTASK_WORK::GO_OUT:
             case UVS_TABUTASK_WORK::DEFENSE:
                 param2 |= ((int)(UVS_TABUTASK_STATUS::GOOD)<<16);
                 uvsChangeTownTabuTask(param2 & 0x0000FFFF);
                 ShowTaskMessage(luck);
                 GamerResult.luck += luck;
                 if (GamerResult.luck > 100) GamerResult.luck = 100;
                 status = UVS_TABUTASK_STATUS::OK;
                 if (((uvsVanger*)Ptarget) -> shape == UVS_VANGER_SHAPE::TABUTASK)
                     ((uvsVanger*)Ptarget) -> shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
                 break;
             case UVS_TABUTASK_WORK::KILL:
                 param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
                 ShowTaskMessage(-luck);
                 GamerResult.luck -= luck;
                 if (GamerResult.luck < 0) GamerResult.luck = 0;
                 status = UVS_TABUTASK_STATUS::SLEEP;
                 if (((uvsVanger*)Ptarget) -> shape == UVS_VANGER_SHAPE::TABUTASK)
                     ((uvsVanger*)Ptarget) -> shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
                 break;
             };
             break;
         case UVS_TARGET::ITEM:
             switch(work_on_target){
             case UVS_TABUTASK_WORK::DELIVER:
             case UVS_TABUTASK_WORK::DELIVER_ONE:
             case UVS_TABUTASK_WORK::DELIVER_OR:
                 param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
                 ShowTaskMessage(-luck);
                 GamerResult.luck -= luck;
                 if (GamerResult.luck < 0) GamerResult.luck = 0;
                 status = UVS_TABUTASK_STATUS::SLEEP;
                 break;
             };//  end switch
             break;
         case UVS_TARGET::FLY_FARMER:
             break;
         case UVS_TARGET::BEEB:
         case UVS_TARGET::GRIB:
         case UVS_TARGET::HIVE:
         case UVS_TARGET::CRYPT:
         case UVS_TARGET::WHIRLPOOL:
         case UVS_TARGET::SWAMP:
         case UVS_TARGET::SHEILD:
         case UVS_TARGET::RAFFA:
             param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
             ShowTaskMessage(-luck);
             GamerResult.luck -= luck;
             if (GamerResult.luck < 0) GamerResult.luck = 0;
             status = UVS_TABUTASK_STATUS::SLEEP;
             break;
         case UVS_TARGET::NONE:
             break;
         };
 //      status = UVS_TABUTASK_STATUS::SLEEP;
         return 1;
     }//  end if
     return 0;
 }
References UVS_TABUTASK_STATUS::ACTIVE, UVS_TABUTASK_STATUS::BAD, UVS_TARGET::BEEB, UVS_VANGER_SHAPE::BUNCH_SLAVE, UVS_TARGET::CRYPT, cycle, UVS_TABUTASK_WORK::DEFENSE, UVS_TABUTASK_WORK::DELIVER, UVS_TABUTASK_WORK::DELIVER_ONE, UVS_TABUTASK_WORK::DELIVER_OR, UVS_TARGET::DOLLY, UVS_TABUTASK_WORK::END_CYCLE_IN_WATER, UVS_TARGET::ESCAVE, UVS_TARGET::FLY_FARMER, FuckOFFinWater(), GamerResult, UVS_TABUTASK_WORK::GO_OUT, UVS_TABUTASK_STATUS::GOOD, UVS_TARGET::GRIB, UVS_TARGET::HIVE, UVS_TARGET::ITEM, UVS_TABUTASK_WORK::KILL, luck, uvsGamerResult::luck, UVS_TARGET::NONE, UVS_TABUTASK_STATUS::OK, UVS_TARGET::PASSAGE, Ptarget, UVS_TARGET::RACE, UVS_TARGET::RAFFA, UVS_TARGET::SHEILD, ShowTaskMessage(), UVS_TABUTASK_STATUS::SLEEP, UVS_TARGET::SPOT, status, UVS_TARGET::SWAMP, UVS_VANGER_SHAPE::TABUTASK, target, uvsChangeTownTabuTask(), UVS_TARGET::VANGER, UVS_TARGET::VANGERS, UVS_TARGET::WHIRLPOOL, and work_on_target.
Erase()
int uvsTabuTaskType::Erase (int param1, int & param2)
{
     if (status == UVS_TABUTASK_STATUS::ACTIVE){
         switch( target ){
         case UVS_TARGET::PASSAGE:
         case UVS_TARGET::RACE:
         case UVS_TARGET::VANGERS:
         case UVS_TARGET::ESCAVE:
         case UVS_TARGET::SPOT:
         case UVS_TARGET::DOLLY:
             param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
             ShowTaskMessage(-luck);
             GamerResult.luck -=  luck;
             if (GamerResult.luck < 0) GamerResult.luck = 0;
             break;
         case UVS_TARGET::VANGER:
             switch(work_on_target){
             case UVS_TABUTASK_WORK::GO_OUT:
             case UVS_TABUTASK_WORK::KILL:
             case UVS_TABUTASK_WORK::DEFENSE:
                 param2 |= ((int)(UVS_TABUTASK_STATUS::GOOD)<<16);
                 ShowTaskMessage(-luck);
                 GamerResult.luck -=  luck;
                 if (GamerResult.luck < 0) GamerResult.luck = 0;
                 if (((uvsVanger*)Ptarget) -> shape == UVS_VANGER_SHAPE::TABUTASK)
                     ((uvsVanger*)Ptarget) -> shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
                 break;
             };
             break;
         case UVS_TARGET::ITEM:
             switch(work_on_target){
             case UVS_TABUTASK_WORK::DELIVER:
             case UVS_TABUTASK_WORK::DELIVER_ONE:
             case UVS_TABUTASK_WORK::DELIVER_OR:
                 param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
                 ShowTaskMessage(-luck);
                 GamerResult.luck -= luck;
                 if (GamerResult.luck < 0) GamerResult.luck = 0;
                 break;
             };//  end switch
             break;
         case UVS_TARGET::FLY_FARMER:
             break;
         case UVS_TARGET::SHEILD:
         case UVS_TARGET::SWAMP:
         case UVS_TARGET::WHIRLPOOL:
         case UVS_TARGET::BEEB:
         case UVS_TARGET::GRIB:
         case UVS_TARGET::HIVE:
         case UVS_TARGET::CRYPT:
         case UVS_TARGET::RAFFA:
             param2 |= ((int)(UVS_TABUTASK_STATUS::BAD)<<16);
             ShowTaskMessage(-luck);
             GamerResult.luck -= luck;
             if (GamerResult.luck < 0) GamerResult.luck = 0;
             break;
         case UVS_TARGET::NONE:
             break;
         };
         status = UVS_TABUTASK_STATUS::SLEEP;
         return 1;
     }//  end if
     return 0;
 }
References UVS_TABUTASK_STATUS::ACTIVE, UVS_TABUTASK_STATUS::BAD, UVS_TARGET::BEEB, UVS_VANGER_SHAPE::BUNCH_SLAVE, UVS_TARGET::CRYPT, UVS_TABUTASK_WORK::DEFENSE, UVS_TABUTASK_WORK::DELIVER, UVS_TABUTASK_WORK::DELIVER_ONE, UVS_TABUTASK_WORK::DELIVER_OR, UVS_TARGET::DOLLY, UVS_TARGET::ESCAVE, UVS_TARGET::FLY_FARMER, GamerResult, UVS_TABUTASK_WORK::GO_OUT, UVS_TABUTASK_STATUS::GOOD, UVS_TARGET::GRIB, UVS_TARGET::HIVE, UVS_TARGET::ITEM, UVS_TABUTASK_WORK::KILL, luck, uvsGamerResult::luck, UVS_TARGET::NONE, UVS_TARGET::PASSAGE, Ptarget, UVS_TARGET::RACE, UVS_TARGET::RAFFA, UVS_TARGET::SHEILD, ShowTaskMessage(), UVS_TABUTASK_STATUS::SLEEP, UVS_TARGET::SPOT, status, UVS_TARGET::SWAMP, UVS_VANGER_SHAPE::TABUTASK, target, UVS_TARGET::VANGER, UVS_TARGET::VANGERS, UVS_TARGET::WHIRLPOOL, and work_on_target.
is_able()
int uvsTabuTaskType::is_able (void)
{
     int i;
     int world = Gamer -> Pworld -> gIndex;
     if ((work_on_target == UVS_TABUTASK_WORK::DELIVER_OR) && (uvsMechosTable[20] -> constractor == 3) )
         return 0;
     if (target == UVS_TARGET::RACE) {
         for( i = 0; i < item_number; i++ )
             if (!uvsCheckItem(item[i]))
                 return 0;
     }
     if ((work_on_target == UVS_TABUTASK_WORK::DELIVER_OR ||
          work_on_target == UVS_TABUTASK_WORK::DELIVER_ONE ||
          work_on_target == UVS_TABUTASK_WORK::DELIVER) ){
         for( i = 0; i < item_number; i++ )
             if (!uvsCheckItem(item[i]))
                 return 0;
     }
     switch( priority ){
     case 1:
         break;
     case 2:
         if (world == 0 && aciWorldLinkExist(0,1,0) == 0) return 0;
         if (world == 1 && dgD -> bStatus < 1) return 0;
         if (world == 2 && GamerResult.game_zyk_result == 0) return 0;
         break;
     case 3:
         if (world == 0 && uvsSecretON() == 0) return 0;
         if (world == 1 && dgD -> bStatus < 2) return 0;
         if (world == 2 && (uvsSecretON() == 0 || GamerResult.game_zyk_result == 0)) return 0;
         break;
     case 4:
         if (world == 0) return 0;
         if (world == 1 && (dgD -> bStatus < 2 || uvsSecretON() == 0)) return 0;
         if (world == 2) return 0;
         break;
     }//  end switch
     if (Pworld)
         return Pworld -> GamerVisit;
     else
         return 1;
 }
References aciWorldLinkExist(), UVS_TABUTASK_WORK::DELIVER, UVS_TABUTASK_WORK::DELIVER_ONE, UVS_TABUTASK_WORK::DELIVER_OR, dgD, uvsGamerResult::game_zyk_result, Gamer, GamerResult, uvsEscave::GamerVisit, uvsEscave::Pworld, UVS_TARGET::RACE, uvsCheckItem(), uvsMechosTable, and uvsSecretON().
Member Data Documentation
cash
int uvsTabuTaskType::cash
Referenced by aciSendEvent2itmdsp().
cycle
int uvsTabuTaskType::cycle
Referenced by checkCycleEvent().
item
int* uvsTabuTaskType::item
item_count
int* uvsTabuTaskType::item_count
item_number
int uvsTabuTaskType::item_number
Referenced by activate().
luck
int uvsTabuTaskType::luck
Referenced by checkCycleEvent(), and Erase().
param
int uvsTabuTaskType::param
priority
int uvsTabuTaskType::priority
Ptarget
uvsTarget* uvsTabuTaskType::Ptarget
Referenced by activateVANGER(), checkCycleEvent(), CreateTabutaskTarget(), and Erase().
Pworld
uvsWorld* uvsTabuTaskType::Pworld
Referenced by activateDOLLY(), and activateVANGER().
real_count
int* uvsTabuTaskType::real_count
Referenced by activate(), and activateDOLLY().
status
int uvsTabuTaskType::status
Referenced by activate(), activateVANGER(), checkCycleEvent(), and Erase().
target
int uvsTabuTaskType::target
Referenced by activate(), checkCycleEvent(), and Erase().
work_on_target
int uvsTabuTaskType::work_on_target
Referenced by activateDOLLY(), activateVANGER(), checkCycleEvent(), and Erase().
The documentation for this struct was generated from the following files:
src/uvs/univang.h
src/uvs/univang.cpp