Vangers: InsectList Struct Reference
InsectList Struct Reference
#include <mechos.h>
Public Member Functions
void Init (void)
void FreeUnit (GeneralObject *p)
void Free (void)
void Quant (void)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void NetEvent (int type, int id)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Public Attributes
int NumInsect [MAX_INSECT_TYPE]
InsectUnit * Data
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
Free()
void InsectList::Free (void) virtual
Reimplemented from UnitListType.
 {
     UnitBaseListType::Free();
     if(Data) delete[] Data;
 };
References Data, and UnitListType::Free().
Referenced by GeneralSystemClose().
FreeUnit()
void InsectList::FreeUnit (GeneralObject * p) virtual
Reimplemented from UnitListType.
 {
     DisconnectTypeList(p);
 };
References UnitBaseListType::DisconnectTypeList().
Referenced by Quant().
Init()
void InsectList::Init (void) virtual
Reimplemented from UnitListType.
 {
     int i;
     for(i = 0;i < MAX_INSECT_TYPE;i++)
         NumInsect[i] = 0;
     if(CurrentWorld != WORLD_KHOX && CurrentWorld != WORLD_HMOK && CurrentWorld != WORLD_WEEXOW &&  !uvsCurrentWorldUnable){
         Data = new InsectUnit[MAX_INSECT_UNIT];
         for(i = 0;i < MAX_INSECT_UNIT;i++) {
             Data[i].Init();
             Data[i].CreateActionUnit(
                 ModelD.FindModel("Bug"),
                 SOBJ_AUTOMAT, Vector(RND(clip_mask_x), RND(clip_mask_y), -1),
                 0,
                 SET_3D_CHOOSE_LEVEL
             );
             Data[i].CreateInsect();
             ConnectTypeList(&Data[i]);
         }
     }else {
         Data = nullptr;
     }
 };
References clip_mask_x, clip_mask_y, UnitBaseListType::ConnectTypeList(), ActionUnit::CreateActionUnit(), InsectUnit::CreateInsect(), CurrentWorld, Data, ModelDispatcher::FindModel(), InsectUnit::Init(), MAX_INSECT_TYPE, MAX_INSECT_UNIT, ModelD, NumInsect, RND(), SET_3D_CHOOSE_LEVEL, SOBJ_AUTOMAT, uvsCurrentWorldUnable, WORLD_HMOK, WORLD_KHOX, and WORLD_WEEXOW.
Referenced by GeneralSystemOpen().
Quant()
void InsectList::Quant (void) virtual
Reimplemented from UnitListType.
 {
     GeneralObject* p;
     GeneralObject* pp;
     p = Tail;
     while(p){
         ((ActionUnit*)(p))->InitEnvironment();
         p = p->NextTypeList;
     };
     p = Tail;
     while(p){
         p->Quant();
         p = p->NextTypeList;
     };
     p = Tail;
     while(p){
         pp = p->NextTypeList;
         if(p->Status & SOBJ_DISCONNECT)
             FreeUnit(p);
         p = pp;
     };
 };
References FreeUnit(), GeneralObject::NextTypeList, SOBJ_DISCONNECT, GeneralObject::Status, and UnitListType::Tail.
Referenced by GameObjectDispatcher::Quant().
Member Data Documentation
Data
InsectUnit* InsectList::Data
Referenced by Free(), and Init().
NumInsect
int InsectList::NumInsect[MAX_INSECT_TYPE]
Referenced by InsectUnit::CreateInsect(), and Init().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp