Vangers: aiMessageType Struct Reference
aiMessageType Struct Reference
#include <hobj.h>
Public Member Functions
void Load (Parser &in)
void Send (int speed=0, int n=0xff, int sf=1)
int GetTime (int n=0xff)
Public Attributes
int LastFrame
int Num
int Type
char Data [AI_MESSAGE_MAX_STRING][AI_MESSAGE_LEN_STRING]
int Time [AI_MESSAGE_MAX_STRING]
int Color [AI_MESSAGE_MAX_STRING]
Detailed Description
Member Function Documentation
GetTime()
int aiMessageType::GetTime (int n = 0xff)
 {
     int c,i;
     c = 0;
     for(i = 0;i < Num;i++){
         if(ind & 1) c += strlen(Data[i]);
         ind >>= 1;
     };
     return c;
 };
References Data, and Num.
Referenced by aiMessageList::Quant().
Load()
void aiMessageType::Load (Parser & in)
 {
     int i;
     char* n;
     in.search_name("TypeString");
     Type = in.get_int();
     if(lang() == RUSSIAN) in.search_name("rNumString");
     else in.search_name("NumString");
     Num = in.get_int();
     if(Num >= AI_MESSAGE_MAX_STRING)
         ErrH.Abort("Bad aiMessage Num String");
     for(i = 0;i < Num;i++){
         in.search_name("Time:");
         Time[i] = in.get_int();
         in.search_name("Color:");
         Color[i] = in.get_int();
         if(lang() == RUSSIAN) in.search_name("rString:");
         else in.search_name("String:");
         n = in.get_name();
         if(strlen(n) >= (AI_MESSAGE_LEN_STRING - 1))
             ErrH.Abort("Bad aiMessage String");
         strcpy(Data[i],/*Convert(*/n/*)*/);
     };
 /*  for(i = 0;i < Num;i++){
         in.search_name("Time:");
         Time[i] = in.get_int();
         in.search_name("String:");
         n = in.get_name();
         Data[i] = new char[strlen(n) + 1];
         strcpy(Data[i],n);
     };*/
     LastFrame = 0;
 };
References XErrorHandler::Abort(), AI_MESSAGE_LEN_STRING, AI_MESSAGE_MAX_STRING, Color, Data, ErrH, Parser::get_int(), Parser::get_name(), lang(), LastFrame, Num, RUSSIAN, Parser::search_name(), Time, and Type.
Send()
void aiMessageType::Send (int speed = 0, int n = 0xff, int sf = 1)
 {
     int i,c;
 /*  static int PrevSpeed = 0;
     if(abs(speed) != 0) PrevSpeed = 10;
     else PrevSpeed--;
     if(sf && PrevSpeed > MAX_AI_MESSAGE_SPEED) return;
     if(abs(LastFrame - frame) > AI_MESSAGE_DELTA){*/
         aiMessageBuffer.align_type = Type;
         c = 0;
         for(i = 0;i < Num;i++){
             if(ind & 1){
                 aiMessageBuffer.add_str(c,(unsigned char*)(Data[i]));
                 aiMessageBuffer.TimeBuf[c] = Time[i];
                 aiMessageBuffer.ColBuf[c] = Color[i];
                 c++;
             };
             ind >>= 1;
         };
         aiMessageBuffer.NumStr = c;
         aciSendPrompt(&aiMessageBuffer);
 /*  };
     LastFrame = frame;*/
 };
References aciSendPrompt(), aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, aciPromptData::ColBuf, Color, Data, Num, aciPromptData::NumStr, Time, aciPromptData::TimeBuf, and Type.
Referenced by aiMessageList::Quant().
Member Data Documentation
Color
int aiMessageType::Color[AI_MESSAGE_MAX_STRING]
Referenced by Load(), and Send().
Data
char aiMessageType::Data[AI_MESSAGE_MAX_STRING][AI_MESSAGE_LEN_STRING]
Referenced by GetTime(), Load(), and Send().
LastFrame
int aiMessageType::LastFrame
Referenced by Load(), and aiMessageList::Send().
Num
int aiMessageType::Num
Referenced by GetTime(), Load(), and Send().
Time
int aiMessageType::Time[AI_MESSAGE_MAX_STRING]
Referenced by Load(), and Send().
Type
int aiMessageType::Type
Referenced by Load(), and Send().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp