Vangers: CompasObject Struct Reference
CompasObject Struct Reference
#include <mechos.h>
Public Member Functions
void Init (void)
void Open (void)
void Close (void)
void Free (void)
void Quant (void)
void AddTarget (int id, UnitOrderType d, char *n1, const char *n2)
void DeleteTarget (CompasTargetType *p)
Public Attributes
int x
int y
int FrameCount
Vector vMove
CompasTargetType * TargetData
CompasTargetType * CurrentTarget
Detailed Description
Member Function Documentation
AddTarget()
void CompasObject::AddTarget (int id, UnitOrderType d, char * n1, const char * n2)
 {
     CompasTargetType* p;
     p = TargetData;
     while(p){
         if(!strcmp(p->aciName,n2)) return;
         p = p->Next;
     };
     p = new CompasTargetType;
     if(!TargetData){
         p->Next = p->Prev = NULL;
         TargetData = p;
     }else{
         TargetData -> Prev = p;
         p -> Next = TargetData;
         p -> Prev = NULL;
         TargetData = p;
     };
     p->ID = id;
     if(n1){
         p->Name = new char[strlen(n1) + 1];
         strcpy(p->Name,n1);
     }else p->Name = NULL;
     if(n2){
         p->aciName = new char[strlen(n2) + 1];
         strcpy(p->aciName,n2);
         aciAdd2Targets(p->aciName);
     }else p->aciName = NULL;
     p->Data.ActionT = d.ActionT;
     p->dFlag = 0;
 };
References aciAdd2Targets(), CompasTargetType::aciName, UnitOrderType::ActionT, CompasTargetType::Data, CompasTargetType::dFlag, CompasTargetType::ID, CompasTargetType::Name, CompasTargetType::Next, NULL, CompasTargetType::Prev, and TargetData.
Referenced by AddPhantomTarget(), AddTarget2Compas(), CreateArtefactTarget(), CreatePhantomTarget(), and CreateTabutaskTarget().
Close()
void CompasObject::Close (void)
 {
     CurrentTarget = NULL;
     CompasTargetType* p;
     CompasTargetType* gp;
     p = TargetData;
     while(p){
         gp = p->Next;
         DeleteTarget(p);
         p = gp;
     };
 };
References CurrentTarget, DeleteTarget(), CompasTargetType::Next, NULL, and TargetData.
Referenced by GeneralSystemClose().
DeleteTarget()
void CompasObject::DeleteTarget (CompasTargetType * p)
 {
     if(p->Name) delete[] p->Name;
     if(p->aciName){
         aciDeleteFromTargets(p->aciName);
         delete[] p->aciName;
     };
     if((!p->Prev) && (!p->Next)) TargetData = NULL;
     else{
         if(p->Prev) p->Prev->Next = p->Next;
         else TargetData = p->Next;
         if(p->Next) p->Next->Prev = p->Prev;
     };
     delete p;
 };
References aciDeleteFromTargets(), CompasTargetType::aciName, CompasTargetType::Name, CompasTargetType::Next, NULL, CompasTargetType::Prev, and TargetData.
Referenced by ClearPhantomTarget(), ClearTabutaskTarget(), Close(), and DeleteArtefactTarget().
Free()
void CompasObject::Free (void)
 {
 };
Referenced by GeneralSystemFree().
Init()
void CompasObject::Init (void)
 {
     FrameCount = 0;
     vMove = Vector(0,0,0);
     CurrentTarget = NULL;
 };
References CurrentTarget, FrameCount, NULL, and vMove.
Referenced by GeneralSystemInit().
Open()
void CompasObject::Open (void)
 {
     CompasTargetType* p;
     uvsEscave* pe;
     uvsSpot* ps;
     uvsPassage* pp;
     p = TargetData;
     while(p){
         switch(p->ID){
             case CMP_TARGET_ESCAVE:
                 p->ID = CMP_OBJECT_ESCAVE;
                 pe = (uvsEscave*)EscaveTail;
                 while(pe){
                     if(!strcmp(pe->name,p->Name)){
                         p->Data.EnterT = pe->unitPtr.EnterT;
                         break;
                     };
                     pe = (uvsEscave*)(pe -> next);
                 };
                 if(pe == NULL) ErrH.Abort("Bad Compas Target Open");
 //              p->Data.EnterT = ((p->Data.TargetT)->unitPtr).EnterT;
                 break;
             case CMP_TARGET_SPOT:
                 p->ID = CMP_OBJECT_SPOT;
                 ps = (uvsSpot*)SpotTail;
                 while(ps){
                     if(!strcmp(ps->name,p->Name)){
                         p->Data.EnterT = ps->unitPtr.EnterT;
                         break;
                     };
                     ps = (uvsSpot*)(ps -> next);
                 };
                 if(ps == NULL) ErrH.Abort("Bad Compas Target Open");
 //              p->Data.EnterT = ((p->Data.TargetT)->unitPtr).EnterT;
                 break;
             case CMP_TARGET_PASSAGE:
                 p->ID = CMP_OBJECT_PASSAGE;
                 pp = (uvsPassage*)PassageTail;
                 while(pp){
                     if(!strcmp(pp->name,p->Name)){
                         p->Data.PassageT = pp->unitPtr.PassageT;
                         break;
                     };
                     pp = (uvsPassage*)(pp -> next);
                 };
                 if(pp == NULL) ErrH.Abort("Bad Compas Target Open");
 //              p->Data.PassageT = ((p->Data.TargetT)->unitPtr).PassageT;
                 break;
             case CMP_TARGET_SENSOR:
                 p->ID = CMP_OBJECT_SENSOR;
                 p->Data.SensorT = FindSensor(p->Name);
                 break;
         };
         if(!p->Data.SensorT)
             ErrH.Abort("Error in Compas Target Open");
         p = p->Next;
     };
 };
References CMP_OBJECT_ESCAVE, CMP_TARGET_ESCAVE, CompasTargetType::Data, UnitOrderType::EnterT, EscaveTail, CompasTargetType::ID, CompasTargetType::Name, uvsEscave::name, and TargetData.
Referenced by GeneralSystemOpen().
Quant()
void CompasObject::Quant (void)
 {
     int tx,ty;
     int d;
     Vector v;
     Vector R_curr;
     PlayerData* p;
     uvsVanger* tt;
     uvsPassage* pass;
     int dx,dy;
     if(!CurrentTarget || !ActD.Active || ActD.Active->ExternalMode != EXTERNAL_MODE_NORMAL || !(ActD.Active->ExternalDraw)) return;
     RaceTxtBuff.init();
     switch(CurrentTarget->ID){
         case CMP_OBJECT_ESCAVE:
         case CMP_OBJECT_SPOT:
             R_curr  = (((CurrentTarget->Data).EnterT)->GetEnterCenter(ActD.Active->R_curr)->ActionLink)->R_curr;
             break;
         case CMP_OBJECT_PASSAGE:
             R_curr = ((CurrentTarget->Data).PassageT)->ActionLink->R_curr;
             break;
         case CMP_OBJECT_SENSOR:
             R_curr = ((CurrentTarget->Data).SensorT)->R_curr;
             break;
         case CMP_OBJECT_PHANTOM:
             p = players_list.first();
             while(p){
                 if((CurrentTarget->Data).ID == p->client_ID){
                     R_curr.x = p->x;
                     R_curr.y = p->y;
                     R_curr.z = 0;
                     RaceTxtBuff < p->name < " : ";
                     break;
                 };
                 p = (PlayerData*)p -> next;
             };
             break;
         case CMP_OBJECT_ITEM:
             if(CurrentTarget->Data.StuffT->Owner){
                 R_curr.x = CurrentTarget->Data.StuffT->Owner->R_curr.x;
                 R_curr.y = CurrentTarget->Data.StuffT->Owner->R_curr.y;
             }else{
                 R_curr.x = CurrentTarget->Data.StuffT->R_curr.x;
                 R_curr.y = CurrentTarget->Data.StuffT->R_curr.y;
             };
             R_curr.z = 0;
             break;
         case CMP_OBJECT_VANGER:
             tt = (uvsVanger*)(CurrentTarget->Data.TargetT);
             if(tt ->Pworld->gIndex == CurrentWorld){
                 R_curr.x = tt->pos_x;
                 R_curr.y = tt->pos_y;
                 R_curr.z = 0;
             }else{
                 pass = GetPassage(CurrentWorld,tt ->Pworld->gIndex);
                 if(pass){
                     R_curr.x = pass->unitPtr.PassageT->ActionLink->R_curr.x;
                     R_curr.y = pass->unitPtr.PassageT->ActionLink->R_curr.y;
                     R_curr.z = pass->unitPtr.PassageT->ActionLink->R_curr.z;
                 };
             };
             break;
         case CMP_OBJECT_VECTOR:
             R_curr.x = (CurrentTarget->Data).vT.x;
             R_curr.y = (CurrentTarget->Data).vT.y;
             R_curr.z = (CurrentTarget->Data).vT.z;
             if(NetworkON && my_server_data.GameType == PASSEMBLOSS && UsedCheckNum < GloryPlaceNum){
                 if(GloryPlaceData[UsedCheckNum].World == CurrentWorld)
                     RaceTxtBuff < "C : ";
                 else
                     RaceTxtBuff < "P : ";
             };
             break;
         default: return;
     };
 //zmod 1.21
     if (CurrentWorld <= 2) {
         v = Vector(getDistX(R_curr.x,x),R_curr.y - y,0);
     } else {
         v = Vector(getDistX(R_curr.x,x),getDistY(R_curr.y,y),0);
     }
     d = v.vabs();
     if(d){
         vMove += v * MAX_COMPAS_DELTA / d;
         d = vMove.vabs();
         if(d) vMove = vMove * (MAX_COMPAS_SPEED * XTCORE_FRAME_NORMAL / d);
     };
     v = Vector(ActD.Active->Speed,0,0)*ActD.Active->RotMat;
     x = XCYCL(x + vMove.x + v.x);
     y = YCYCL(y + vMove.y + v.y);
     if(AdvancedView) G2LQ(x,y,0,tx,ty);
     else G2LS(x,y,0,tx,ty);
     if(tx < UcutLeft + COMPAS_LEFT){
         tx = UcutLeft + COMPAS_LEFT;
         vMove.x = 0;
     };
     if(tx > UcutRight - COMPAS_RIGHT){
         tx = UcutRight - COMPAS_RIGHT;
         vMove.x = 0;
     };
     if(ty < VcutUp + COMPAS_UP){
         ty = VcutUp + COMPAS_UP;
         vMove.y = 0;
     };
     if(ty > VcutDown - COMPAS_DOWN){
         ty = VcutDown - COMPAS_DOWN;
         vMove.y = 0;
     };
     EffD.FireBallData[2].Show2(tx,ty,FrameCount);
     EffD.FireBallData[2].CheckOut(FrameCount);
     S2G(tx,ty,x,y);
     int cclx,ccly,ccrx,ccry,ccm;
     ccm = XGR_Obj.ClipMode;
     XGR_SetClipMode(XGR_CLIP_ALL);
     cclx = XGR_Obj.clipLeft;
     ccly = XGR_Obj.clipTop;
     ccrx = XGR_Obj.clipRight;
     ccry = XGR_Obj.clipBottom;
     XGR_SetClip(UcutLeft,VcutUp,UcutRight,VcutDown);
     if(ActD.Active){
         dx = getDistX(R_curr.x,ActD.Active->R_curr.x);
         if(CurrentWorld < MAIN_WORLD_MAX - 1)
             dy = R_curr.y - ActD.Active->R_curr.y;
         else
             dy = getDistY(R_curr.y,ActD.Active->R_curr.y);
     }else{
         dx = 0;
         dy = 0;
     };
     RaceTxtBuff <= (int)(sqrt(dx*(double)dx + dy*(double)dy)) / 100;
     dx = ((ScreenCX - tx)*(int)(strlen(RaceTxtBuff.address()))*10 + 32) / (int)(curGMap -> xside);
     dy = ((ScreenCY - ty)*18 + 32) / (int)(curGMap -> yside);
     aOutText32clip(tx + dx,ty + dy,165 | (2 << 16),RaceTxtBuff.address(),0,0,0);
 /*  if(ty < ScreenCY){
         if(tx < ScreenCX)
             aOutText32clip(tx + 32,ty + 32,165 | (2 << 16),RaceTxtBuff.address(),0,0,0);
         else
               aOutText32clip(tx - strlen(RaceTxtBuff.address())*10,ty + 32,165 | (2 << 16),RaceTxtBuff.address(),0,0,0);
     }else{
         if(tx < ScreenCX)
             aOutText32clip(tx + 32,ty - 18,165 | (2 << 16),RaceTxtBuff.address(),0,0,0);
         else
             aOutText32clip(tx - strlen(RaceTxtBuff.address())*10,ty - 18,165 | (2 << 16),RaceTxtBuff.address(),0,0,0);
     };*/
     XGR_SetClip(cclx,ccly,ccrx,ccry);
     XGR_SetClipMode(ccm);
 };
References ActD, ActionDispatcher::Active, PlayerData::client_ID, CMP_OBJECT_ESCAVE, CMP_OBJECT_PASSAGE, CMP_OBJECT_PHANTOM, CMP_OBJECT_SENSOR, CMP_OBJECT_SPOT, CurrentTarget, CompasTargetType::Data, EXTERNAL_MODE_NORMAL, VangerUnit::ExternalDraw, VangerUnit::ExternalMode, XTList< Type >::first(), CompasTargetType::ID, XBuffer::init(), PlayerData::name, players_list, RaceTxtBuff, Vector::x, PlayerData::x, Vector::y, PlayerData::y, and Vector::z.
Referenced by GameObjectDispatcher::DrawQuant().
Member Data Documentation
CurrentTarget
CompasTargetType* CompasObject::CurrentTarget
Referenced by ClearPhantomTarget(), Close(), DeleteArtefactTarget(), VangerUnit::GamerOrderInit(), GetCompasTarget(), Init(), Quant(), and SelectCompasTarget().
FrameCount
int CompasObject::FrameCount
Referenced by Init().
TargetData
CompasTargetType* CompasObject::TargetData
Referenced by AddPhantomTarget(), AddTarget(), ClearPhantomTarget(), ClearTabutaskTarget(), Close(), CreateArtefactTarget(), CreatePhantomTarget(), CreateTabutaskTarget(), DeleteArtefactTarget(), DeleteTarget(), VangerUnit::GamerOrderInit(), Open(), and SelectCompasTarget().
vMove
Vector CompasObject::vMove
Referenced by Init().
x
int CompasObject::x
y
int CompasObject::y
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp