Vangers: aciScreenDispatcher Struct Reference
aciScreenDispatcher Struct Reference
#include <aci_scr.h>
Public Member Functions
void AddScreen (aciScreen *p)
void AddResource (aciScreenResource *p)
aciScreen * GetScreen (int id)
aciScreenObject * GetObject (int id)
aciScreenResource * GetResource (int id)
void KeyTrap (int code, SDL_Event *event)
void alloc_mem (void)
void free_mem (void)
int Quant (int flush_log=1)
void EventQuant (void)
int ObjectQuant (void)
void FlushEvents (void)
int redraw (void)
void flush (void)
void PrepareInput (int obj_id)
void InputQuant (SDL_Event *event)
void CancelInput (void)
void DoneInput (void)
void ChangeCoords (int dx, int dy)
void SetResource (int obj_id, int res_id, int fr)
void SetSequence (int obj_id, int seq_id)
void ChangeScroller (int obj_id, int x)
void SetScroller (int obj_id, int v, int max_v)
int GetObjectValue (int obj_id, int flag=0)
aciScreenDispatcher (void)
~aciScreenDispatcher (void)
Public Attributes
int flags
int QuantCode
XList * scrList
int curScrID
aciScreen * curScr
XList * resources
aciScreenInputField * activeInput
aciScreenEventLine * eventLine
aciScreenEventLine * flushLine
Detailed Description
Constructor & Destructor Documentation
aciScreenDispatcher()
aciScreenDispatcher::aciScreenDispatcher (void)
 {
     flags = 0;
     curScr = NULL;
     curScrID = 1;
     QuantCode = 0;
     activeInput = NULL;
     scrList = new XList;
     resources = new XList;
     eventLine = new aciScreenEventLine;
     flushLine = new aciScreenEventLine;
 }
References activeInput, curScr, curScrID, eventLine, flags, flushLine, NULL, QuantCode, resources, and scrList.
~aciScreenDispatcher()
aciScreenDispatcher::~aciScreenDispatcher (void)
 {
     //aciScreen *scr, *scr1;
     aciScreenResource *res, *res1;
     res = (aciScreenResource*)resources -> fPtr;
     while(res){
         res1 = (aciScreenResource*)res -> next;
         res -> free();
         acsFreeResource(res);
         res = res1;
     }
     delete resources;
     //aci_FREE_LIST(scrList,NULL,NULL,aciScreen);
     delete scrList;
     delete eventLine;
     delete flushLine;
 }
References resources.
Member Function Documentation
AddResource()
void aciScreenDispatcher::AddResource (aciScreenResource * p)
 {
     resources -> AddElement((XListElement*)p);
 }
References resources.
AddScreen()
void aciScreenDispatcher::AddScreen (aciScreen * p)
 {
     scrList -> AddElement((XListElement*)p);
 }
References scrList.
alloc_mem()
void aciScreenDispatcher::alloc_mem (void)
 {
     aciScreenResource* p = (aciScreenResource*)resources -> fPtr;
     while(p){
         p -> load();
         p = (aciScreenResource*)p -> next;
     }
     curScr = GetScreen(curScrID);
     curScr -> prepare();
     curScr -> alloc_mem();
     curScr -> init_objects();
     curScr -> backRes = GetResource(curScr -> backResID);
     flags &= ~ACS_NEED_EXIT;
     flags |= ACS_FORCED_REDRAW;
     flags |= ACS_FIRST_REDRAW;
     KeyTrap(ACS_STARTUP_KEY, nullptr);
     acsLoadFonts();
 }
References resources.
CancelInput()
void aciScreenDispatcher::CancelInput (void)
 {
     strcpy(activeInput -> string,acsBackupStr);
     activeInput -> flags |= ACS_REDRAW_OBJECT;
     activeInput -> flags &= ~ACS_ACTIVE_STRING;
     activeInput = NULL;
     delete acsBackupStr;
     acsBackupStr = NULL;
     SDL_StopTextInput();
 }
References ACS_ACTIVE_STRING, ACS_REDRAW_OBJECT, acsBackupStr, activeInput, flags, and NULL.
Referenced by free_mem(), InputQuant(), and PrepareInput().
ChangeCoords()
void aciScreenDispatcher::ChangeCoords (int dx, int dy)
 {
     aciScreenResource* p = (aciScreenResource*)resources -> fPtr;
     while(p){
         p -> change_coords(dx,dy);
         p = (aciScreenResource*)p -> next;
     }
     curScr -> ChangeCoords(dx,dy);
 }
References resources.
ChangeScroller()
void aciScreenDispatcher::ChangeScroller (int obj_id, int x)
 {
     aciScreenScroller* p = (aciScreenScroller*)GetObject(obj_id);
     p -> Change(x);
 }
References GetObject().
Referenced by FlushEvents().
DoneInput()
void aciScreenDispatcher::DoneInput (void)
 {
     int sz;
     sz = strlen(activeInput -> string);
     activeInput -> string[sz - 1] = 0;
     activeInput -> flags |= ACS_REDRAW_OBJECT;
     activeInput -> flags &= ~ACS_ACTIVE_STRING;
     activeInput = NULL;
     delete acsBackupStr;
     acsBackupStr = NULL;
     SDL_StopTextInput();
 }
References ACS_ACTIVE_STRING, ACS_REDRAW_OBJECT, acsBackupStr, activeInput, flags, and NULL.
Referenced by InputQuant().
EventQuant()
void aciScreenDispatcher::EventQuant (void)
 {
     curScr -> EventQuant();
 }
References curScr.
Referenced by Quant().
flush()
void aciScreenDispatcher::flush (void)
 {
     aciScreenEventCommand* ev;
     while(flushLine -> size){
         ev = flushLine -> get();
         XGR_Flush(ev -> data[0],ev -> data[1],ev -> data[2],ev -> data[3]);
     }
 }
References flushLine, and XGR_Flush.
Referenced by Quant().
FlushEvents()
void aciScreenDispatcher::FlushEvents (void)
 {
     aciScreenEventCommand* ev;
     while(eventLine -> size){
         ev = eventLine -> get();
         switch(ev -> code){
             case ACS_EXIT:
                 QuantCode = ev -> data[0]; // resume game pause
                 flags |= ACS_NEED_EXIT;
                 break;
             case ACS_SET_RESOURCE:
                 SetResource(ev -> data[0],ev -> data[1],ev -> data[2]);
                 break;
             case ACS_EXEC_SEQUENCE:
                 SetSequence(ev -> data[0],ev -> data[1]);
                 break;
             case ACS_CHANGE_SCROLLER:
                 ChangeScroller(ev -> data[0],XGR_MouseObj.PosX + XGR_MouseObj.SpotX);
                 break;
             case ACS_INPUT_STRING:
                 PrepareInput(ev -> data[0]);
                 break;
             case ACS_EXT_EVENT:
                 acsHandleExtEvent(ev -> data[0],ev -> data[1],ev -> data[2],ev -> data[3]);
                 break;
             case ACS_CHANGE_STR_STATE:
                 acsChangeStrState(ev -> data[0]);
                 break;
         }
         //std::cout<<"aciScreenDispatcher::FlushEvents "<<ev->code<<" QuantCode:"<<QuantCode<<std::endl;
     }
 }
References ACS_CHANGE_SCROLLER, ACS_CHANGE_STR_STATE, ACS_EXEC_SEQUENCE, ACS_EXIT, ACS_EXT_EVENT, ACS_INPUT_STRING, ACS_NEED_EXIT, ACS_SET_RESOURCE, acsChangeStrState(), acsHandleExtEvent(), ChangeScroller(), eventLine, flags, XGR_Mouse::PosX, PrepareInput(), QuantCode, SetResource(), SetSequence(), XGR_Mouse::SpotX, and XGR_MouseObj.
Referenced by Quant().
free_mem()
void aciScreenDispatcher::free_mem (void)
 {
     aciScreenResource* p = (aciScreenResource*)resources -> fPtr;
     if(activeInput) CancelInput();
     while(p){
         p -> free();
         p = (aciScreenResource*)p -> next;
     }
     acsFreeFonts();
 }
References activeInput, CancelInput(), and resources.
GetObject()
aciScreenObject * aciScreenDispatcher::GetObject (int id)
 {
     return curScr -> GetObject(id);
 }
References curScr.
Referenced by ChangeScroller(), GetObjectValue(), PrepareInput(), SetResource(), SetScroller(), and SetSequence().
GetObjectValue()
int aciScreenDispatcher::GetObjectValue (int obj_id, int flag = 0)
 {
     int ret = 0;
     aciScreenObject* p = GetObject(obj_id);
     if(p){
         switch(p -> type){
             case ACS_BASE_OBJ:
                 if(p -> curFrame) ret = 1;
                 break;
             case ACS_SCROLLER_OBJ:
                 if(!flag)
                     ret = ((aciScreenScroller*)p) -> CurValue;
                 else
                     ret = ((aciScreenScroller*)p) -> MaxValue;
                 break;
         }
     }
     return ret;
 }
References ACS_BASE_OBJ, ACS_SCROLLER_OBJ, and GetObject().
GetResource()
aciScreenResource * aciScreenDispatcher::GetResource (int id)
 {
     aciScreenResource* p = (aciScreenResource*)resources -> fPtr;
     while(p){
         if(p -> ID == id) return p;
         p = (aciScreenResource*)p -> next;
     }
     return curScr -> GetResource(id);
 }
References resources.
Referenced by ObjectQuant(), and SetResource().
GetScreen()
aciScreen * aciScreenDispatcher::GetScreen (int id)
 {
     aciScreen* p = (aciScreen*)scrList -> fPtr;
     while(p){
         if(p -> ID == id) return p;
         p = (aciScreen*)p -> next;
     }
     return NULL;
 }
References scrList.
InputQuant()
void aciScreenDispatcher::InputQuant (SDL_Event * event)
 {
     int sz;
     unsigned char* ptr = NULL;
     unsigned char chr;
     HFont* hfnt = NULL;
     if(!activeInput) {
         return;
     }
     if (!(event != nullptr && (event->type == SDL_KEYDOWN || event->type == SDL_TEXTINPUT)))
         return;
     ptr = (unsigned char*)activeInput -> string;
     if(activeInput -> flags & ACS_ISCREEN_FONT) {
         hfnt = acsFntTable[activeInput -> font];
     }
     if (event != nullptr && event->type == SDL_KEYDOWN) {
         if (event->key.keysym.sym > 0 && event->key.keysym.sym < 127) {
             chr = event->key.keysym.sym;
         } else {
             return;
         }
         switch(event->key.keysym.sym) {
             case SDLK_RETURN:
                 DoneInput();
                 break;
             case SDLK_ESCAPE:
                 CancelInput();
                 break;
             case SDLK_LEFT:
             case SDLK_BACKSPACE:
                 sz = strlen((char*)ptr);
                 if(sz > 1) {
                     ptr[sz - 1] = 0;
                     ptr[sz - 2] = '_';
                     activeInput->flags |= ACS_REDRAW_OBJECT;
                 }
                 break;
         }
     } else if (event != nullptr && event->type == SDL_TEXTINPUT) {
         if ((unsigned char)event->text.text[0] < 128) {
             chr = event->text.text[0];
         } else {
             unsigned short utf = ((unsigned short *)event->text.text)[0];
             utf = ntohs(utf);
             // All cyrilic chars should be coding in two octets. 8, 11 bit-index for 1,2 octets
             if ((utf & (1<<(7))) && !(utf & (1<<(10)))) {
                 chr = UTF8toCP866(utf);
             } else {
                 chr = ' ';
             }
         }
         if(hfnt && chr < (hfnt->StartChar-hfnt->EndChar+1) && (hfnt->data[chr]->Flags & NULL_HCHAR) && chr != ' ')
             return;
         sz = strlen((char*)ptr);
         if(sz <= activeInput->MaxStrLen) {
             ptr[sz - 1] = chr;
             ptr[sz] = '_';
             ptr[sz + 1] = 0;
             activeInput -> flags |= ACS_REDRAW_OBJECT;
         }
     }
 }
References ACS_ISCREEN_FONT, ACS_REDRAW_OBJECT, acsFntTable, activeInput, CancelInput(), HFont::data, DoneInput(), HFont::EndChar, aciScreenObject::flags, flags, HChar::Flags, NULL, NULL_HCHAR, HFont::StartChar, and UTF8toCP866().
Referenced by KeyTrap().
KeyTrap()
void aciScreenDispatcher::KeyTrap (int code, SDL_Event * event)
 {
     if(activeInput) {
         InputQuant(event);
     }
     if (event == nullptr || event->type != SDL_TEXTINPUT) {
         curScr->KeyTrap(code);
     }
 }
References activeInput, curScr, InputQuant(), and aciScreen::KeyTrap().
ObjectQuant()
int aciScreenDispatcher::ObjectQuant (void)
 {
     int ret = 0;
     aciScreenObject* p = (aciScreenObject*)curScr -> objList -> fPtr;
     while(p){
         if(p -> activeSeq){
             p -> ResID = p -> activeSeq -> ResourceID;
             p -> resPtr = GetResource(p -> ResID);
             p -> curFrame = p -> activeSeq -> CurFrame;
             if(p -> activeSeq -> CurFrame == p -> activeSeq -> EndFrame)
                 p -> activeSeq = NULL;
             else
                 p -> activeSeq -> CurFrame += p -> activeSeq -> FrameDelta;
             p -> flags |= ACS_REDRAW_OBJECT;
             ret = 1;
         }
         p -> Quant();
         p = (aciScreenObject*)p -> next;
     }
     return ret;
 }
References ACS_REDRAW_OBJECT, curScr, flags, GetResource(), NULL, and Quant().
Referenced by Quant().
PrepareInput()
void aciScreenDispatcher::PrepareInput (int obj_id)
 {
     int sz;
     aciScreenInputField* p = (aciScreenInputField*)GetObject(obj_id);
     if(p){
         if(activeInput){
             activeInput -> StopEvents();
             CancelInput();
         }
         sz = strlen(p -> string) + 1;
         if(!acsBackupStr){
             acsBackupStr = new char[sz];
             strcpy(acsBackupStr,p -> string);
         }
         p -> string[sz - 1] = '_';
         p -> string[sz] = 0;
         p -> flags |= ACS_ACTIVE_STRING;
         activeInput = p;
         SDL_StartTextInput();
     }
 }
References ACS_ACTIVE_STRING, acsBackupStr, activeInput, CancelInput(), flags, and GetObject().
Referenced by FlushEvents().
Quant()
int aciScreenDispatcher::Quant (int flush_log = 1)
 {
     int sz,obj_flag = 0;
     EventQuant();
     FlushEvents();
     ObjectQuant();
     if(activeInput){
         acsInputTimer ++;
         if(acsInputTimer >= ACS_INPUT_TIMER){
             acsInputTimer = 0;
             acsInputFlag = 1;
         }
         if(acsInputFlag){
             sz = strlen(activeInput -> string);
             if(activeInput -> string[sz - 1] == '_')
                 activeInput -> string[sz - 1] = ' ';
             else
                 activeInput -> string[sz - 1] = '_';
             activeInput -> flags |= ACS_REDRAW_OBJECT;
             acsInputFlag = 0;
         }
     }
     obj_flag = redraw();
     if(flush_log)
         flush();
     else
         flushLine -> clear();
     if(!obj_flag && !NetworkON){
         //KDWIN::Sleep(100);
     }
     return QuantCode;
 }
References ACS_INPUT_TIMER, ACS_REDRAW_OBJECT, acsInputFlag, acsInputTimer, activeInput, EventQuant(), flags, flush(), FlushEvents(), flushLine, NetworkON, ObjectQuant(), QuantCode, and redraw().
Referenced by ObjectQuant().
redraw()
int aciScreenDispatcher::redraw (void)
 {
     int force,ret = 0;
     if(flags & ACS_FORCED_REDRAW){
         force = 1;
         flags ^= ACS_FORCED_REDRAW;
     }
     else
         force = 0;
     if(flags & ACS_FIRST_REDRAW){
         flags ^= ACS_FIRST_REDRAW;
         acsFirstRedraw = 1;
     }
     else
         acsFirstRedraw = 0;
     ret = curScr -> redraw(force);
     return ret;
 }
References ACS_FIRST_REDRAW, ACS_FORCED_REDRAW, acsFirstRedraw, curScr, and flags.
Referenced by Quant().
SetResource()
void aciScreenDispatcher::SetResource (int obj_id, int res_id, int fr)
 {
     aciScreenResource* res = GetResource(res_id);
     aciScreenObject* obj = GetObject(obj_id);
     if(obj && res){
         obj -> ResID = res -> ID;
         obj -> resPtr = res;
         if(fr == ACS_MAX_FRAME)
             fr = acsGetMaxFrame(res_id);
         obj -> curFrame = fr;
         res -> flags |= ACS_NO_FLUSH;
         acsGetResourceSize(res,obj -> PosX,obj -> PosY,obj -> SizeX,obj -> SizeY);
     }
     else
         ErrH.Abort("SetResource() failed...");
 }
References XErrorHandler::Abort(), ACS_MAX_FRAME, ACS_NO_FLUSH, acsGetMaxFrame(), acsGetResourceSize(), ErrH, flags, GetObject(), and GetResource().
Referenced by FlushEvents().
SetScroller()
void aciScreenDispatcher::SetScroller (int obj_id, int v, int max_v)
 {
     aciScreenScroller* p = (aciScreenScroller*)GetObject(obj_id);
     if(!max_v) max_v = 1;
     p -> CurValue = (p -> MaxValue * v) / max_v;
     p -> flags |= ACS_REDRAW_OBJECT;
 }
References ACS_REDRAW_OBJECT, flags, and GetObject().
SetSequence()
void aciScreenDispatcher::SetSequence (int obj_id, int seq_id)
 {
     aciScreenFrameSequence* seq;
     aciScreenObject* obj = GetObject(obj_id);
     if(obj){
         seq = obj -> GetSequence(seq_id);
         obj -> activeSeq = seq;
         seq -> CurFrame = seq -> StartFrame;
     }
     else
         ErrH.Abort("SetSequence() failed...");
 }
References XErrorHandler::Abort(), ErrH, and GetObject().
Referenced by FlushEvents().
Member Data Documentation
activeInput
aciScreenInputField* aciScreenDispatcher::activeInput
Referenced by aciScreenDispatcher(), CancelInput(), DoneInput(), free_mem(), InputQuant(), KeyTrap(), PrepareInput(), and Quant().
curScr
aciScreen* aciScreenDispatcher::curScr
Referenced by aciScreenDispatcher(), EventQuant(), GetObject(), KeyTrap(), ObjectQuant(), and redraw().
curScrID
int aciScreenDispatcher::curScrID
Referenced by aciScreenDispatcher().
eventLine
aciScreenEventLine* aciScreenDispatcher::eventLine
Referenced by aciScreenDispatcher(), and FlushEvents().
flags
int aciScreenDispatcher::flags
Referenced by aciScreenDispatcher(), CancelInput(), DoneInput(), FlushEvents(), InputQuant(), ObjectQuant(), PrepareInput(), Quant(), redraw(), SetResource(), and SetScroller().
flushLine
aciScreenEventLine* aciScreenDispatcher::flushLine
Referenced by aciScreenDispatcher(), flush(), and Quant().
QuantCode
int aciScreenDispatcher::QuantCode
Referenced by aciScreenDispatcher(), FlushEvents(), and Quant().
resources
XList* aciScreenDispatcher::resources
Referenced by aciScreenDispatcher(), AddResource(), alloc_mem(), ChangeCoords(), free_mem(), GetResource(), and ~aciScreenDispatcher().
scrList
XList* aciScreenDispatcher::scrList
Referenced by aciScreenDispatcher(), AddScreen(), and GetScreen().
The documentation for this struct was generated from the following files:
src/actint/aci_scr.h
src/actint/aci_scr.cpp