Vangers: GameQuantRTO Struct Reference
GameQuantRTO Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
GameQuantRTO (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
virtual void Finit (void)
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Additional Inherited Members
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
GameQuantRTO()
GameQuantRTO::GameQuantRTO (void) inline
 { ID = RTO_GAME_QUANT_ID; Timer = RTO_GAME_QUANT_TIMER; }
References XRuntimeObject::ID, RTO_GAME_QUANT_ID, RTO_GAME_QUANT_TIMER, and XRuntimeObject::Timer.
Member Function Documentation
Init()
void GameQuantRTO::Init (int id) virtual
Reimplemented from XRuntimeObject.
 {
     vMap -> lockHeap();
 _MEM_STATISTIC_("AFTER GAME QUANT INIT -> ");
 }
References _MEM_STATISTIC_, and vMap.
Quant()
int GameQuantRTO::Quant (void) virtual
Reimplemented from XRuntimeObject.
 {
     int ret = 0;
     if(Pause <= 1 || NetworkON){
         if(Pause) Pause++;
         gameQuant();
 //      DBGCHECK
         frame++;
         if(++fps_frame == FPS_PERIOD) {
             sprintf(fps_string,"%.1f",(double)FPS_PERIOD/(SDL_GetTicks() - (int)fps_start)*1000);
 #ifdef _DEBUG
             network_analysis(network_analysis_buffer,0);
 #else
             if(curGMap -> prmFlag & PRM_FPS && NetworkON)
                 short_network_analysis(network_analysis_buffer);
 #endif
             fps_frame = 0;
             fps_start = SDL_GetTicks();
             }
         if(Redraw){
             XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
             Redraw = 0;
             frame = 0;
             _Timer_ = SDL_GetTicks();
             fps_start = SDL_GetTicks();
             }
 //      if(!PalIterLock && !palTr -> quant()) pal_iter();
         if(!PalIterLock) PalCD.Quant();
         if(vSoundOFF){ vSoundOFF = 0; EffectsOff(); }
         if(vSoundON){ vSoundON = 0; EffectsOn(); }
         }
     else {
         if(GameQuantReturnValue || acsQuant()){
             Pause = 0;
         }
     }
     ret = GameQuantReturnValue;
     GameQuantReturnValue = 0;
     //XGR_Flip();
     return ret;
 }
References _Timer_, acsQuant(), curGMap, EffectsOff(), EffectsOn(), fps_frame, FPS_PERIOD, fps_start, fps_string, frame, gameQuant(), GameQuantReturnValue, network_analysis(), network_analysis_buffer, NetworkON, PalCD, PalIterLock, Pause, PRM_FPS, PalConstructor::Quant(), Redraw, short_network_analysis(), vSoundOFF, vSoundON, XGR_Flush, XGR_MAXX, and XGR_MAXY.
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp