Vangers: ParticleGenerator Struct Reference
ParticleGenerator Struct Reference
#include <effect.h>
Public Member Functions
void Init (StorageType *s)
void Quant (void)
void DrawQuant (void)
void CreateGenerator (Vector vC, Vector vT, Vector vD, int mode=PG_STYLE_INCAR)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
Vector vTarget
Vector vDelta
int Speed
int Precision
int MoveMode
int TargetMode
int ParticleStorage
int ParticleType
int Time
int FlyRadius
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CreateGenerator()
void ParticleGenerator::CreateGenerator (Vector vC, Vector vT, Vector vD, int mode = PG_STYLE_INCAR)
 {
     switch(mode){
         case PG_STYLE_INCAR:
             R_curr = vC;
             cycleTor(R_curr.x,R_curr.y);
             ParticleStorage = EFF_PARTICLE07;
             ParticleType = 7;
             vTarget = vT;
             vDelta = vD;
             Speed = 15;
             MoveMode = PG_MODE_MOVE_TARGET;
             TargetMode = PG_RADIUS;
             Time = 300;
             FlyRadius = 100;
             radius = FlyRadius;
             Precision = 5;
             GetVisible();
             break;
         case PG_STYLE_ENTER:
             R_curr = vC;
             cycleTor(R_curr.x,R_curr.y);
             ParticleStorage = EFF_PARTICLE07;
             ParticleType = 8;
             vTarget = vT;
             vDelta = vD;
             Speed = 8;
             MoveMode = PG_MODE_TRUE_MASS;
             TargetMode = PG_RADIUS;
             Time = 40;
             FlyRadius = RND(50);
             radius = FlyRadius;
             Precision = 5;
             GetVisible();
             break;
         case PG_STYLE_REINCAR:
             R_curr = vC;
             cycleTor(R_curr.x,R_curr.y);
             ParticleStorage = EFF_PARTICLE07;
             ParticleType = 7;
             vTarget = vT;
             vDelta = vD;
             Speed = 5;
             MoveMode = PG_MODE_TRUE_MASS;
             TargetMode = PG_TARGET_RANDOM | PG_TARGET_RIGHT | PG_TARGET;
             Time = CHANGE_VANGER_TIME;
             FlyRadius = 100;
             radius = FlyRadius;
             Precision = 2;
             GetVisible();
             break;
     };
     R_prev = R_curr;
     Status = 0;
 };
References CHANGE_VANGER_TIME, cycleTor(), EFF_PARTICLE07, FlyRadius, MoveMode, ParticleStorage, ParticleType, PG_MODE_MOVE_TARGET, PG_MODE_TRUE_MASS, PG_RADIUS, PG_STYLE_ENTER, PG_STYLE_INCAR, PG_STYLE_REINCAR, PG_TARGET, PG_TARGET_RANDOM, PG_TARGET_RIGHT, Precision, GeneralObject::R_curr, BaseObject::R_prev, BaseObject::radius, RND(), Speed, GeneralObject::Status, TargetMode, Time, vDelta, vTarget, Vector::x, and Vector::y.
Referenced by EffectDispatcher::CreateParticleGenerator().
DrawQuant()
void ParticleGenerator::DrawQuant (void)
 {
     EffD.CreateParticle(ParticleType,R_prev,R_curr,ParticleStorage);
 };
References EffectDispatcher::CreateParticle(), EffD, ParticleStorage, ParticleType, GeneralObject::R_curr, and BaseObject::R_prev.
Init()
void ParticleGenerator::Init (StorageType * s)
 {
     BaseObject::Init(s);
     ID = ID_EXPLOSION;
 };
References GeneralObject::ID, and ID_EXPLOSION.
Quant()
void ParticleGenerator::Quant (void)
 {
     uchar alt;
     Vector vT;
     int d;
     vT = Vector(0,0,0);
     if(TargetMode & PG_RADIUS){
         vT = Vector(getDistX(vTarget.x,R_curr.x),getDistY(vTarget.y,R_curr.y),0);
         d =  vT.vabs();
         vT *= d - FlyRadius;
         vT /= d;
         d = vT.y;
         vT.y +=  vT.x;
         vT.x -= d;
     };
     if(TargetMode & PG_TARGET)
         vT += Vector(getDistX(vTarget.x,R_curr.x),getDistY(vTarget.y,R_curr.y),0);
     if((TargetMode & PG_TARGET_RANDOM) && RND(100) < 50)
         vT += Vector(BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2));
     if(TargetMode & PG_TARGET_RANDOM)
         vT += Vector(vDelta.y,-vDelta.x,0);
     if(TargetMode & PG_TARGET_RIGHT)
         vT += Vector(-vDelta.y,vDelta.x,0);
     if(TargetMode & PG_WALL){
         vT += Vector(getDistX(vTarget.x,R_curr.x),getDistY(vTarget.y,R_curr.y),vTarget.z - R_curr.z);
         if(vT.abs2() == radius*radius) Speed = 0;
     };
     d = vT.vabs();
     if(d){
         vDelta += vT * Precision / d;
         d = vDelta.vabs();
         if(!(MoveMode & PG_MODE_TRUE_MASS) || d > Speed) vDelta = vDelta * Speed / d;
     };
     R_prev = R_curr;
     R_curr += vDelta;
     cycleTor(R_curr.x,R_curr.y);
     Time--;
     GetAlt(R_curr.x,R_curr.y,R_curr.z,alt);
     R_curr.z = alt + radius;
     if(Time <= 0) Status |= SOBJ_DISCONNECT;
 };
References Vector::abs2(), BMAX_TARGET_VECTOR, BMAX_TARGET_VECTOR2, cycleTor(), FlyRadius, GetAlt(), getDistX(), getDistY(), MoveMode, PG_MODE_TRUE_MASS, PG_RADIUS, PG_TARGET, PG_TARGET_RANDOM, PG_TARGET_RIGHT, PG_WALL, Precision, GeneralObject::R_curr, BaseObject::R_prev, BaseObject::radius, RND(), SOBJ_DISCONNECT, Speed, GeneralObject::Status, TargetMode, Time, Vector::vabs(), vDelta, vTarget, Vector::x, Vector::y, and Vector::z.
Member Data Documentation
FlyRadius
int ParticleGenerator::FlyRadius
Referenced by CreateGenerator(), and Quant().
MoveMode
int ParticleGenerator::MoveMode
Referenced by CreateGenerator(), and Quant().
ParticleStorage
int ParticleGenerator::ParticleStorage
Referenced by CreateGenerator(), and DrawQuant().
ParticleType
int ParticleGenerator::ParticleType
Referenced by CreateGenerator(), and DrawQuant().
Precision
int ParticleGenerator::Precision
Referenced by CreateGenerator(), and Quant().
Speed
int ParticleGenerator::Speed
Referenced by CreateGenerator(), and Quant().
TargetMode
int ParticleGenerator::TargetMode
Referenced by CreateGenerator(), and Quant().
Time
int ParticleGenerator::Time
Referenced by CreateGenerator(), and Quant().
vDelta
Vector ParticleGenerator::vDelta
Referenced by CreateGenerator(), and Quant().
vTarget
Vector ParticleGenerator::vTarget
Referenced by CreateGenerator(), and Quant().
The documentation for this struct was generated from the following files:
src/units/effect.h
src/units/effect.cpp