Vangers: iChatInputField Struct Reference
iChatInputField Struct Reference
#include <i_chat.h>
Public Member Functions
virtual void redraw (void)
iChatInputField (void)
~iChatInputField (void)
Public Member Functions inherited from iChatScreenObject
virtual void flush (void)
int check_xy (int x, int y)
void init (int x, int y, int sx, int sy, int col1, int col2)
void set_font (int f)
iChatScreenObject (void)
~iChatScreenObject (void)
Public Member Functions inherited from XListElement
XListElement (void)
Public Attributes
int color
char * string
XBuffer * XConv
Public Attributes inherited from iChatScreenObject
int ID
int type
int flags
int PosX
int PosY
int SizeX
int SizeY
int font
int fonColor
int borderColor
Public Attributes inherited from XListElement
XListElement * next
XListElement * prev
Detailed Description
Constructor & Destructor Documentation
iChatInputField()
iChatInputField::iChatInputField (void)
 {
     string = new char[ISC_MAX_STRING_LEN];
     memset(string,0,ISC_MAX_STRING_LEN);
     XConv = new XBuffer(256);
     if(!iScreenChat)
         color = ICS_STRING_COL1;
     else
         color = ICS_iSTRING_COL1;
 }
References color, ICS_iSTRING_COL1, ICS_STRING_COL1, ISC_MAX_STRING_LEN, iScreenChat, and XConv.
~iChatInputField()
iChatInputField::~iChatInputField (void)
 {
     delete[] string;
 }
References string.
Member Function Documentation
redraw()
void iChatInputField::redraw (void) virtual
Reimplemented from iChatScreenObject.
 {
     int dy;
     iChatScreenObject::redraw();
     dy = (SizeY - aTextHeight32(string,font,0)) / 2;
     XConv -> init();
     *XConv < CurPlayerName < string;
     aOutText32(PosX,PosY,color,XConv -> address(),font,1,0);
 }
References aOutText32(), aTextHeight32(), color, CurPlayerName, iChatScreenObject::font, iChatScreenObject::init(), iChatScreenObject::PosX, iChatScreenObject::PosY, iChatScreenObject::redraw(), iChatScreenObject::SizeY, string, and XConv.
Member Data Documentation
color
int iChatInputField::color
Referenced by iChatInputField(), and redraw().
string
char* iChatInputField::string
Referenced by iChatInputChar(), redraw(), and ~iChatInputField().
XConv
XBuffer* iChatInputField::XConv
Referenced by iChatInputChar(), iChatInputField(), and redraw().
The documentation for this struct was generated from the following files:
src/iscreen/i_chat.h
src/iscreen/i_chat.cpp