Vangers: ItemsDispatcher Struct Reference
ItemsDispatcher Struct Reference
#include <items.h>
Public Member Functions
void Init (Parser &in)
void Free (void)
void Open (Parser &in)
void Close (void)
void Quant (void)
void DrawQuant (void)
void DeleteItem (StuffObject *p)
void NetEvent (int type, int id)
void NetDevice (int type, int id)
int CreateEnableCrypt (void)
void CryptQuant (void)
void LarvaHilator (void)
Public Member Functions inherited from UnitList
void Init (Parser &in)
void Open (Parser &in)
void ConnectTypeList (GeneralObject *p)
void DisconnectTypeList (GeneralObject *p)
void Quant (void)
void ConnectObject (BaseObject *p)
void Add2Next (GeneralObject *p, GeneralObject *t)
void Add2Prev (GeneralObject *p, GeneralObject *t)
GeneralObject * GetNetObject (int id)
GeneralObject * GetObject (int type)
void ClearNet (void)
Public Attributes
int NumDeviceType
StuffObject ** DeviceTypeData
StuffObject ** StuffItemLink
int NumVisibleItem
int UnitEnergy
int UnitArmor
int UnitDeltaEnergy
Public Attributes inherited from UnitList
int Total
int * MaxUnit
StorageType * UnitStorage
GeneralObject ** UnitData
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
Close()
void ItemsDispatcher::Close (void)
 {
     int i;
     StuffObject* p;
     StuffObject* pp;
     uvsItem* g;
     p = (StuffObject*)Tail;
     FreeList(WorldTable[GameD.cWorld]->Pitem);
     if(NetworkON){
         while(p){
             pp = (StuffObject*)(p->NextTypeList);
             DeleteItem(p);
             p = pp;
         };
     }else{
         for(i = 0;i < ProtoCryptTableSize[CurrentWorld];i++){
             if(ProtoCryptTable[CurrentWorld][i].SensorType == 3 || ProtoCryptTable[CurrentWorld][i].SensorType == 5 || (ProtoCryptTable[CurrentWorld][i].SensorType == 4 && ProtoCryptTable[CurrentWorld][i].z0 == UVS_ITEM_TYPE::SPUMMY)){
                 ProtoCryptTable[CurrentWorld][i].Enable = 0;
             };
         };
         while(p){
             pp = (StuffObject*)(p->NextTypeList);
             if(p->ActIntBuffer.type == ACI_CONLARVER){
                 uvsFreeDolly(p->R_curr.x,p->R_curr.y,p->ActIntBuffer.data0);
                 p->ActIntBuffer.data1 = p->ActIntBuffer.data0 = 0;
                 p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 g = new uvsItem(p->uvsDeviceType);
                 g->param1 = p->ActIntBuffer.data0;
                 g->param2 = p->ActIntBuffer.data1;
                 g->pos_x = p->R_curr.x;
                 g->pos_y = p->R_curr.y;
                 g->pos_z = ITEM_DEFAULT_Z;
                 g -> link(WorldTable[CurrentWorld]->Pitem);
 //              uvsKronDeleteItem(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
             }else{
                 if(p->CreateMode != STUFF_CREATE_RELAX){
                     if(((int)(RND(100)) < aiCutLuck || p->Hour == ConTimer.hour || p->ActIntBuffer.type == ACI_TABUTASK_SUCCESSFUL || p->ActIntBuffer.type == ACI_TABUTASK || CurrentWorld >= MAIN_WORLD_MAX) &&
                        (p->ActIntBuffer.type != ACI_ZEEX && p->ActIntBuffer.type != ACI_BEEBOORAT && p->ActIntBuffer.type != ACI_ELEEPOD && p->ActIntBuffer.type != ACI_TABUTASK_FAILED && p->ActIntBuffer.type != ACI_BOORAWCHIK)){
                         g = new uvsItem(p->uvsDeviceType);
                         g->param1 = p->ActIntBuffer.data0;
                         g->param2 = p->ActIntBuffer.data1;
                         g->pos_x = p->R_curr.x;
                         g->pos_y = p->R_curr.y;
                         g->pos_z = ITEM_DEFAULT_Z;
                         g -> link(WorldTable[CurrentWorld]->Pitem);
                     }else uvsKronDeleteItem(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 }else{
                     for(i = 0;i < ProtoCryptTableSize[CurrentWorld];i++){
                         if((ProtoCryptTable[CurrentWorld][i].SensorType == 3 || ProtoCryptTable[CurrentWorld][i].SensorType == 5 || (ProtoCryptTable[CurrentWorld][i].SensorType == 4 && ProtoCryptTable[CurrentWorld][i].z0 == UVS_ITEM_TYPE::SPUMMY)) && ProtoCryptTable[CurrentWorld][i].z0 == p->uvsDeviceType){
                             if(getDistY(ProtoCryptTable[CurrentWorld][i].R_curr.y,p->R_curr.y) < p->radius && getDistX(ProtoCryptTable[CurrentWorld][i].R_curr.x,p->R_curr.x) < p->radius)
                                 ProtoCryptTable[CurrentWorld][i].Enable = 1;
                         };
                     };
                 };
             };
             DeleteItem(p);
             p = pp;
         };
         if(ConTimer.day >= 16){
             if(!RND(3) && !aciWorldLinkExist(WORLD_FOSTRAL,WORLD_WEEXOW,0) && !aciWorldLinkExist(WORLD_GLORX,WORLD_KHOX,0)
                && !aciWorldLinkExist(WORLD_NECROSS,WORLD_BOOZEENA,0) && !aciWorldLinkExist(WORLD_NECROSS,WORLD_ARKONOY,0))
                 Item2ShopAction(5);
             if(!RND(3))
                 Item2ShopAction(3);
         };
     };
     for(i = 0;i < Total;i++) UnitData[i]->Close();
     for(i = 0;i < MAX_ITEMS_OBJECT;i++) UnitStorage[i].Check();
 };
References ACI_BEEBOORAT, ACI_BOORAWCHIK, ACI_CONLARVER, ACI_ELEEPOD, ACI_TABUTASK, ACI_TABUTASK_FAILED, ACI_TABUTASK_SUCCESSFUL, ACI_ZEEX, aciWorldLinkExist(), StuffObject::ActIntBuffer, aiCutLuck, ConTimer, StuffObject::CreateMode, CurrentWorld, GameObjectDispatcher::cWorld, actintItemData::data0, actintItemData::data1, uvsContimer::day, DeleteItem(), StaticObject::Enable, FreeList(), g, GameD, getDistX(), getDistY(), StuffObject::Hour, uvsContimer::hour, Item2ShopAction(), ITEM_DEFAULT_Z, MAIN_WORLD_MAX, MAX_ITEMS_OBJECT, NetworkON, uvsWorld::Pitem, ProtoCryptTable, ProtoCryptTableSize, Object::radius, RND(), UVS_ITEM_TYPE::SPUMMY, STUFF_CREATE_RELAX, UnitList::Tail, UnitList::Total, actintItemData::type, UnitList::UnitData, UnitList::UnitStorage, StuffObject::uvsDeviceType, uvsFreeDolly(), uvsKronDeleteItem(), uvsSetItemType(), WORLD_ARKONOY, WORLD_BOOZEENA, WORLD_FOSTRAL, WORLD_GLORX, WORLD_KHOX, WORLD_NECROSS, WORLD_WEEXOW, WorldTable, Object::x, and Object::y.
Referenced by GeneralSystemClose().
CreateEnableCrypt()
int ItemsDispatcher::CreateEnableCrypt (void)
 {
     int i,sz;
     sz = 0;
     int rx,ry;
     ry = TurnSideY - ActD.Active->radius - ActD.Active->Speed;
     rx = TurnSideX - ActD.Active->radius - ActD.Active->Speed;
     for(i = 0;i < ProtoCryptTableSize[CurrentWorld];i++){
         if((ProtoCryptTable[CurrentWorld][i].SensorType == 2 || ProtoCryptTable[CurrentWorld][i].SensorType == 6 ||  ProtoCryptTable[CurrentWorld][i].SensorType == 1 || ProtoCryptTable[CurrentWorld][i].SensorType == 7)
            && abs(getDistY(ProtoCryptTable[CurrentWorld][i].R_curr.y,ViewY)) < ry
            && abs(getDistX(ProtoCryptTable[CurrentWorld][i].R_curr.x,ViewX)) < rx){
             sz++;
             ProtoCryptTable[CurrentWorld][i].Enable = 1;
         }else
             ProtoCryptTable[CurrentWorld][i].Enable = 0;
     };
     return sz;
 };
References ActD, ActionDispatcher::Active, CurrentWorld, StaticObject::Enable, getDistX(), getDistY(), ProtoCryptTable, ProtoCryptTableSize, Object::radius, ActionUnit::Speed, TurnSideX, TurnSideY, ViewX, and ViewY.
Referenced by CryptQuant().
CryptQuant()
void ItemsDispatcher::CryptQuant (void)
 {
     int i,j;
     listElem* p;
     uvsItem* n;
     if(ActD.Active && Num < Total / 4 && !RND(200*ActD.NumVisibleVanger)){
         if(CreateEnableCrypt() > NumVisibleItem){
             for(i = 0;i < ProtoCryptTableSize[CurrentWorld];i++){
                 if(ProtoCryptTable[CurrentWorld][i].Enable){
                     if(ProtoCryptTable[CurrentWorld][i].SensorType == 2 || ProtoCryptTable[CurrentWorld][i].SensorType == 6){
                         for(j = 0;j < (int)(RND(ITEM_LUCK_MAX));j++){
                             if(!RND(10))
                                 uvsCreateNewItem(ProtoCryptTable[CurrentWorld][i].R_curr.x + (ITEM_LUCK_RADIUS*CO[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.y + (ITEM_LUCK_RADIUS*SI[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.z,uvsGenerateItemForCrypt(6),CurrentWorld);
                             else
                                 uvsCreateNewItem(ProtoCryptTable[CurrentWorld][i].R_curr.x + (ITEM_LUCK_RADIUS*CO[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.y + (ITEM_LUCK_RADIUS*SI[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.z,uvsGenerateItemForCrypt(2),CurrentWorld);
                         };
                     }else{
                         if(ProtoCryptTable[CurrentWorld][i].SensorType == 1 || ProtoCryptTable[CurrentWorld][i].SensorType == 7)
                             uvsCreateNewItem(ProtoCryptTable[CurrentWorld][i].R_curr.x,ProtoCryptTable[CurrentWorld][i].R_curr.y,ProtoCryptTable[CurrentWorld][i].R_curr.z,uvsGenerateItemForCrypt(ProtoCryptTable[CurrentWorld][i].SensorType),CurrentWorld);
                     };
                 };
             };
         };
         p = WorldTable[GameD.cWorld]->Pitem;
         while(p){
             n = (uvsItem*)(p);
             addDevice(n->pos_x,n->pos_y,n->pos_z,n->type,n->param1,n->param2,NULL);
             p = p->next;
         };
         FreeList(WorldTable[CurrentWorld]->Pitem);
     };
 };
References ActD, ActionDispatcher::Active, addDevice(), CO, CreateEnableCrypt(), CurrentWorld, GameObjectDispatcher::cWorld, FreeList(), GameD, ITEM_LUCK_MAX, ITEM_LUCK_RADIUS, listElem::next, NULL, UnitList::Num, NumVisibleItem, ActionDispatcher::NumVisibleVanger, uvsItem::param1, uvsItem::param2, PI, uvsWorld::Pitem, uvsTarget::pos_x, uvsTarget::pos_y, uvsItem::pos_z, ProtoCryptTable, ProtoCryptTableSize, GeneralObject::R_curr, RND(), SI, UnitList::Total, uvsItem::type, uvsCreateNewItem(), uvsGenerateItemForCrypt(), WorldTable, Vector::y, and Vector::z.
Referenced by Quant().
DeleteItem()
void ItemsDispatcher::DeleteItem (StuffObject * p)
 {
     if(p->LightData){
         p->LightData->Destroy();
         p->LightData = NULL;
     };
     GameD.DisconnectBaseList(p);
     DisconnectTypeList(p);
     if(p->Storage) p->Storage->Deactive(p);
 };
References StuffObject::Deactive(), LightPoint::Destroy(), GameObjectDispatcher::DisconnectBaseList(), UnitList::DisconnectTypeList(), GameD, StuffObject::LightData, and NULL.
Referenced by addDevice(), Close(), Quant(), and uvsapiDestroyItem().
DrawQuant()
void ItemsDispatcher::DrawQuant (void)
Free()
void ItemsDispatcher::Free (void)
 {
     int i;
     for(i = 0;i < NumDeviceType;i++)
         delete DeviceTypeData[i];
     delete[] DeviceTypeData;
     delete[] StuffItemLink;
     for(i = 0;i < Total;i++){
         UnitData[i]->Free();
         delete UnitData[i];
     };
     for(i = 0;i < MAX_ITEMS_OBJECT;i++) UnitStorage[i].Free();
     delete[] UnitData;
     delete[] MaxUnit;
     delete[] UnitStorage;
 };
References DeviceTypeData, MAX_ITEMS_OBJECT, UnitList::MaxUnit, NumDeviceType, StuffItemLink, UnitList::Total, UnitList::UnitData, and UnitList::UnitStorage.
Referenced by GeneralSystemFree().
Init()
void ItemsDispatcher::Init (Parser & in)
 {
     int i,j,k;
     char* name;
     Parser dp("device.lst");
     UnitList::Init(in);
     Total = 0;
     MaxUnit = new int[MAX_ITEMS_OBJECT];
     UnitStorage = new StorageType[MAX_ITEMS_OBJECT];
     in.search_name("NumItems");
     if(RAM16){
         for(i = 0;i < MAX_ITEMS_OBJECT;i++){
             MaxUnit[i] = in.get_int();
             MaxUnit[i] /= 2;
             if(MaxUnit[i] == 0) MaxUnit[i] = 1;
             Total += MaxUnit[i];
         };
     }else{
         for(i = 0;i < MAX_ITEMS_OBJECT;i++){
             MaxUnit[i] = in.get_int();
             Total += MaxUnit[i];
         };
     };
     in.search_name("UnitEnergy");
     UnitEnergy = in.get_int();
     in.search_name("UnitArmor");
     UnitArmor = in.get_int();
     in.search_name("UnitDeletaEnergy");
     UnitDeltaEnergy = in.get_int();
     UnitData = new GeneralObject*[Total];
     k = 0;
     for(i = 0;i < MAX_ITEMS_OBJECT;i++){
         UnitStorage[i].Init(MaxUnit[i]);
         for(j = 0;j < MaxUnit[i];j++){
             switch(i){
                 case ITEM_GUN_DEVICE:
                     UnitData[k] = new GunDevice;
                     break;
                 case ITEM_CHANGER:
                     UnitData[k] = new ChangerDevice;
                     break;
                 case ITEM_OTHER:
                     UnitData[k] = new StuffObject;
                     break;
             };
             UnitData[k]->Init(&UnitStorage[i]);
             UnitStorage[i].Deactive(UnitData[k]);
             k++;
         };
     };
     dp.search_name("NumDeviceType");
     NumDeviceType = dp.get_int();
     DeviceTypeData = new StuffObject*[NumDeviceType];
     StuffItemLink = new StuffObject*[MAX_ITEM_TYPE];
     for(j =0;j < MAX_ITEM_TYPE;j++) StuffItemLink[j] = (StuffObject*)0x83838383;
     for(i = 0;i < NumDeviceType;i++){
         dp.search_name("DeviceID");
         name = dp.get_name();
         if(!strcmp("Gun",name)){
             DeviceTypeData[i] = new GunDevice;
             DeviceTypeData[i]->StuffType = DEVICE_ID_GUN;
         }else{
             if(!strcmp("Changer",name)){
                 DeviceTypeData[i] = new ChangerDevice;
                 DeviceTypeData[i]->StuffType = DEVICE_ID_CHANGER;
             }else{
                 if(!strcmp("Other",name)){
                     DeviceTypeData[i] = new StuffObject;
                     DeviceTypeData[i]->StuffType = DEVICE_ID_OTHER;
                 };
             };
         };
         DeviceTypeData[i]->DataID = i;
         dp.search_name("UvsDeviceName");
         name = dp.get_name();
         for(j = 0;j < MAX_ITEM_TYPE;j++){
             if(!strcmp(uvsItemTable[j]->name,name)){
                 StuffItemLink[j] = DeviceTypeData[i];
                 DeviceTypeData[i]->uvsDeviceType = j;
                 DeviceTypeData[i]->ActIntBuffer.type = uvsItemTable[j]->SteelerTypeEmpty;
                 break;
             };
         };
         if(j == MAX_ITEM_TYPE){
             ErrH.Abort("Bad Item ID");
             StuffItemLink[0] = DeviceTypeData[i];
             DeviceTypeData[i]->uvsDeviceType = 0;
             DeviceTypeData[i]->ActIntBuffer.type = uvsItemTable[0]->SteelerTypeEmpty;
         };
         DeviceTypeData[i]->DeviceLoad(dp);
     };
 };
References XErrorHandler::Abort(), StuffObject::ActIntBuffer, StuffObject::DataID, StorageType::Deactive(), DEVICE_ID_CHANGER, DEVICE_ID_GUN, DEVICE_ID_OTHER, StuffObject::DeviceLoad(), DeviceTypeData, ErrH, Parser::get_int(), Parser::get_name(), StorageType::Init(), UnitList::Init(), ITEM_CHANGER, ITEM_GUN_DEVICE, ITEM_OTHER, MAX_ITEM_TYPE, MAX_ITEMS_OBJECT, UnitList::MaxUnit, NumDeviceType, RAM16, Parser::search_name(), uvsItemType::SteelerTypeEmpty, StuffItemLink, StuffObject::StuffType, UnitList::Total, actintItemData::type, UnitArmor, UnitList::UnitData, UnitDeltaEnergy, UnitEnergy, UnitList::UnitStorage, StuffObject::uvsDeviceType, and uvsItemTable.
Referenced by GeneralSystemInit().
LarvaHilator()
void ItemsDispatcher::LarvaHilator (void)
 {
     StuffObject* p;
     p = (StuffObject*)Tail;
     while(p){
         if(p->ActIntBuffer.type == ACI_CONLARVER){
             uvsFreeDolly(p->R_curr.x,p->R_curr.y,p->ActIntBuffer.data0);
             p->ActIntBuffer.data1 = p->ActIntBuffer.data0 = 0;
             p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
         };
         p = (StuffObject*)(p->NextTypeList);
     };
 };
References ACI_CONLARVER, StuffObject::ActIntBuffer, actintItemData::data0, actintItemData::data1, UnitList::Tail, actintItemData::type, StuffObject::uvsDeviceType, uvsFreeDolly(), uvsSetItemType(), Object::x, and Object::y.
Referenced by VangerUnit::Go2Universe().
NetDevice()
void ItemsDispatcher::NetDevice (int type, int id)
 {
     StuffObject* p;
     VangerUnit* v;
     uchar t;
     p = NULL;
     v = (VangerUnit*)(ActD.Tail);
     while(v){
         p = v->DeviceData;
         while(p){
             if(p->NetDeviceID == id) break;
             p = p->NextDeviceList;
         };
         if(p) break;
         v = (VangerUnit*)(v->NextTypeList);
     };
     if(p){
         if(p->Status & SOBJ_DISCONNECT) NETWORK_IN_STREAM.ignore_event();
         else p->NetEvent(type,id,NETWORK_IN_STREAM.current_creator(),NETWORK_IN_STREAM.current_x(),NETWORK_IN_STREAM.current_y());
     }else{
         p = (StuffObject*)(ItemD.Tail);
         while(p){
             if(p->NetDeviceID == id) break;
             p = (StuffObject*)(p->NextTypeList);
         };
         if(p){
             if(p->Status & SOBJ_DISCONNECT) NETWORK_IN_STREAM.ignore_event();
             else p->NetEvent(type,id,NETWORK_IN_STREAM.current_creator(),NETWORK_IN_STREAM.current_x(),NETWORK_IN_STREAM.current_y());
         }else{
             if(type == UPDATE_OBJECT){
                 NETWORK_IN_STREAM > t;
                 p = (StuffObject*)(ItemD.GetObject(DevicetStorageID[ItemD.DeviceTypeData[t]->StuffType]));
                 if(p){
                     p->DataID = t;
                     p->NetEvent(CREATE_OBJECT,id,NETWORK_IN_STREAM.current_creator(),NETWORK_IN_STREAM.current_x(),NETWORK_IN_STREAM.current_y());
                 }else NETWORK_IN_STREAM.ignore_event();
             }else NETWORK_IN_STREAM.ignore_event();
         };
     };
 };
References ActD, CREATE_OBJECT, StuffObject::DataID, uvsUnitType::DeviceData, DevicetStorageID, DeviceTypeData, UnitList::GetObject(), ItemD, StuffObject::NetDeviceID, StuffObject::NetEvent(), NETWORK_IN_STREAM, StuffObject::NextDeviceList, NULL, SOBJ_DISCONNECT, StuffObject::StuffType, UnitList::Tail, and UPDATE_OBJECT.
Referenced by GameObjectDispatcher::NetEvent().
NetEvent()
void ItemsDispatcher::NetEvent (int type, int id) virtual
Reimplemented from UnitList.
 {
     StuffObject* p;
     uchar t;
     VangerUnit* v;
     p = (StuffObject*)(GetNetObject(id));
     if(p){
         if(p->Status & SOBJ_DISCONNECT) NETWORK_IN_STREAM.ignore_event();
         else p->NetEvent(type,id,NETWORK_IN_STREAM.current_creator(),NETWORK_IN_STREAM.current_x(),NETWORK_IN_STREAM.current_y());
     }else{
         v = (VangerUnit*)(ActD.Tail);
         while(v){
             p = v->DeviceData;
             while(p){
                 if(p->NetID == id) break;
                 p = p->NextDeviceList;
             };
             if(p) break;
             v = (VangerUnit*)(v->NextTypeList);
         };
         if(p){
             if(p->Status & SOBJ_DISCONNECT) NETWORK_IN_STREAM.ignore_event();
             else p->NetEvent(type,id,NETWORK_IN_STREAM.current_creator(),NETWORK_IN_STREAM.current_x(),NETWORK_IN_STREAM.current_y());
         }else{
             if(type == UPDATE_OBJECT){
                 NETWORK_IN_STREAM > t;
                 p = (StuffObject*)(ItemD.GetObject(DevicetStorageID[ItemD.DeviceTypeData[t]->StuffType]));
                 if(p){
                     p->DataID = t;
                     p->NetEvent(CREATE_OBJECT,id,NETWORK_IN_STREAM.current_creator(),NETWORK_IN_STREAM.current_x(),NETWORK_IN_STREAM.current_y());
                 }else NETWORK_IN_STREAM.ignore_event();
             }else NETWORK_IN_STREAM.ignore_event();
         };
     };
 };
References ActD, CREATE_OBJECT, StuffObject::DataID, uvsUnitType::DeviceData, DevicetStorageID, DeviceTypeData, UnitList::GetNetObject(), UnitList::GetObject(), ItemD, StuffObject::NetEvent(), NETWORK_IN_STREAM, StuffObject::NextDeviceList, SOBJ_DISCONNECT, StuffObject::StuffType, UnitList::Tail, and UPDATE_OBJECT.
Referenced by GameObjectDispatcher::NetEvent().
Open()
void ItemsDispatcher::Open (Parser & in)
 {
     listElem* p;
     uvsItem* n;
     int i,j;
     UnitList::Open(in);
     for(i = 0;i < Total;i++) UnitData[i]->Open();
     GeneralMousePoint = Vector(83,0,0);
     NumVisibleItem = Total;
     if(!NetworkON){
         for(i = 0;i < ProtoCryptTableSize[CurrentWorld];i++){
             if(ProtoCryptTable[CurrentWorld][i].Enable){
                 if(ProtoCryptTable[CurrentWorld][i].SensorType == 2 || ProtoCryptTable[CurrentWorld][i].SensorType == 6){
                     for(j = 0;j < ITEM_LUCK_MAX;j++){
                         if((int)(RND(100)) <= aiCutLuck){
                             if(!RND(8))
                                 uvsCreateNewItem(ProtoCryptTable[CurrentWorld][i].R_curr.x + (ITEM_LUCK_RADIUS*CO[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.y + (ITEM_LUCK_RADIUS*SI[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.z,uvsGenerateItemForCrypt(6),CurrentWorld);
                             else
                                 uvsCreateNewItem(ProtoCryptTable[CurrentWorld][i].R_curr.x + (ITEM_LUCK_RADIUS*CO[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.y + (ITEM_LUCK_RADIUS*SI[RND(PI*2)] >> 16),ProtoCryptTable[CurrentWorld][i].R_curr.z,uvsGenerateItemForCrypt(2),CurrentWorld);
                         };
                     };
                 }else{
                     if(ProtoCryptTable[CurrentWorld][i].SensorType == 1 || ProtoCryptTable[CurrentWorld][i].SensorType == 7)
                         uvsCreateNewItem(ProtoCryptTable[CurrentWorld][i].R_curr.x,ProtoCryptTable[CurrentWorld][i].R_curr.y,ProtoCryptTable[CurrentWorld][i].R_curr.z,uvsGenerateItemForCrypt(ProtoCryptTable[CurrentWorld][i].SensorType),CurrentWorld);
                     else
                         uvsCreateNewItem(ProtoCryptTable[CurrentWorld][i].R_curr.x,ProtoCryptTable[CurrentWorld][i].R_curr.y,ProtoCryptTable[CurrentWorld][i].R_curr.z,ProtoCryptTable[CurrentWorld][i].z0,CurrentWorld);
                 };
             };
         };
         p = WorldTable[GameD.cWorld]->Pitem;
         while(p){
             n = (uvsItem*)(p);
             addDevice(n->pos_x,n->pos_y,n->pos_z,n->type,n->param1,n->param2,NULL);
             p = p->next;
         };
         FreeList(WorldTable[CurrentWorld]->Pitem);
     };
 };
References addDevice(), aiCutLuck, CO, CurrentWorld, GameObjectDispatcher::cWorld, FreeList(), GameD, GeneralMousePoint, ITEM_LUCK_MAX, ITEM_LUCK_RADIUS, NetworkON, listElem::next, NULL, NumVisibleItem, UnitList::Open(), uvsItem::param1, uvsItem::param2, PI, uvsWorld::Pitem, uvsTarget::pos_x, uvsTarget::pos_y, uvsItem::pos_z, ProtoCryptTable, ProtoCryptTableSize, GeneralObject::R_curr, RND(), SI, UnitList::Total, uvsItem::type, UnitList::UnitData, uvsCreateNewItem(), uvsGenerateItemForCrypt(), WorldTable, Vector::y, Vector::z, and SensorDataType::z0.
Referenced by GeneralSystemOpen().
Quant()
void ItemsDispatcher::Quant (void)
 {
     GeneralObject* n;
     StuffObject* p;
     StuffObject* np;
     StuffObject* pp;
     VangerUnit* v;
     if(NetworkON) CryptQuant();
     NumVisibleItem = 0;
     n = Tail;
     while(n){
         n->Quant();
         n = n->NextTypeList;
     };
     p = (StuffObject*)Tail;
     while(p){
         np = (StuffObject*)(p->NextTypeList);
         if(p->Status & SOBJ_DISCONNECT) DeleteItem(p);
         else{
             if(p->Status & SOBJ_LINK){
                 p->Status &= ~SOBJ_LINK;
                 if(p->Status & SOBJ_WAIT_CONFIRMATION)
                     p->Owner = NULL;
                 else{
                     v = (VangerUnit*)(p->Owner);
                     switch(v->CheckInDevice(p)){
                         case CHECK_DEVICE_IN:
                             p->DeviceIn();
                             PUT_GLOBAL_EVENT(AI_EVENT_CAPTURE,p->ID,p,v);
                             if(v->Status & SOBJ_ACTIVE){
                                 p->ActIntBuffer.slot = -1;
                                 aciSendEvent2actint(ACI_PUT_ITEM,&(p->ActIntBuffer));
                                 if(ActD.Active && v == ActD.Active)
                                     SOUND_TAKE_ITEM(getDistX(ActD.Active->R_curr.x,p->R_curr.x))
                             };
                             break;
                         case CHECK_DEVICE_ADD:
                             ObjectDestroy(p);
                             pp = v->DeviceData;
                             while(pp){
                                 if(pp->uvsDeviceType == p->uvsDeviceType){
                                     pp->ActIntBuffer.data1+= p->ActIntBuffer.data1;
                                     break;
                                 };
                                 pp = pp->NextDeviceList;
                             };
                             DeleteItem(p);
                             if(ActD.Active && v == ActD.Active)
                                 SOUND_TAKE_ITEM(getDistX(ActD.Active->R_curr.x,p->R_curr.x))
                             break;
                         case CHECK_DEVICE_OUT:
                             p->Owner = NULL;
                             break;
                     };
                 };
             };
         };
         p = np;
     };
 };
References ACI_PUT_ITEM, aciSendEvent2actint(), ActD, StuffObject::ActIntBuffer, ActionDispatcher::Active, AI_EVENT_CAPTURE, CHECK_DEVICE_ADD, CHECK_DEVICE_IN, CHECK_DEVICE_OUT, VangerUnit::CheckInDevice(), CryptQuant(), actintItemData::data1, DeleteItem(), uvsUnitType::DeviceData, StuffObject::DeviceIn(), getDistX(), Object::ID, NetworkON, StuffObject::NextDeviceList, GeneralObject::NextTypeList, NULL, NumVisibleItem, ObjectDestroy(), StuffObject::Owner, PUT_GLOBAL_EVENT, actintItemData::slot, SOBJ_ACTIVE, SOBJ_DISCONNECT, SOBJ_LINK, SOBJ_WAIT_CONFIRMATION, SOUND_TAKE_ITEM, UnitList::Tail, StuffObject::uvsDeviceType, and Object::x.
Referenced by GameObjectDispatcher::Quant().
Member Data Documentation
DeviceTypeData
StuffObject** ItemsDispatcher::DeviceTypeData
Referenced by Free(), Init(), NetDevice(), NetEvent(), and StuffObject::NetEvent().
NumDeviceType
int ItemsDispatcher::NumDeviceType
Referenced by Free(), and Init().
NumVisibleItem
int ItemsDispatcher::NumVisibleItem
Referenced by CryptQuant(), Open(), StuffObject::Quant(), and Quant().
StuffItemLink
StuffObject** ItemsDispatcher::StuffItemLink
Referenced by addDevice(), Free(), and Init().
UnitArmor
int ItemsDispatcher::UnitArmor
Referenced by Init().
UnitDeltaEnergy
int ItemsDispatcher::UnitDeltaEnergy
Referenced by Init().
UnitEnergy
int ItemsDispatcher::UnitEnergy
Referenced by Init().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp