Vangers: TntCreature Struct Reference
TntCreature Struct Reference
#include <sensor.h>
Public Member Functions
void Load (XStream &in)
void Save (XStream &in)
void DrawQuant (void)
void Quant (void)
void Touch (GeneralObject *p)
void Destroy (void)
void NetEvent (void)
void NetUpdate (void)
void ClearUpdate (void)
void NetQuant (void)
void NetDestroy (int fl=1)
void NetHideEvent (void)
void HideEvent (void)
Public Attributes
int HideFlag
int MaxHeight
int CurrentHeight
int StartHeight
int DelayHeight
int nSource
int DestroyProcess
int DestroyDelay
int Time
int TouchTime
MobileLocation * TntClone
int TntNumLink
int TntLinkDelay
TntCreature * TntLinkData [MAX_TNT_EXPLOSION]
unsigned int NetTime
Public Attributes inherited from StaticObject
int StaticType
int radius
char Enable
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
ClearUpdate()
void TntCreature::ClearUpdate (void)
Destroy()
void TntCreature::Destroy (void)
 {
     int i;
     Vector vCheck;
     Object* p;
     int d;
     BulletObject* g;
     if(TntClone->QuickCheck()){
         CurrentHeight = 0;
         TntClone->setPhase(CurrentHeight,1);
         MapD.CreateCrater(R_curr,MAP_POINT_CRATER06,radius + 10);
         EffD.CreateFireBall(R_curr + Vector(0,0,20),DT_FIRE_BALL04,NULL,1 << 8,0);
         TouchTime = 0;
         Time = DestroyDelay;
         if(ActD.Active)
             SOUND_BARREL_DESTROY(getDistX(ActD.Active->R_curr.x,R_curr.x));
 /*          CurrentHeight = 0;
             TntClone->setPhase(CurrentHeight,0);
             MapD.CreateCrater(R_curr,MAP_POINT_CRATER06,radius);
             EffD.CreateFireBall(R_curr + Vector(0,0,20),DT_FIRE_BALL04,NULL,1 << 8,0);
             TouchTime = 0;
             Time = DestroyDelay;*/
         switch(CurrentWorld){
             case WORLD_GLORX:
 /*              if(ActD.Active){
                     g = BulletD.CreateBullet();
                     vCheck = Vector(getDistX((ActD.Active)->R_curr.x,R_curr.x),getDistY((ActD.Active)->R_curr.y,R_curr.y),(ActD.Active)->R_curr.z - R_curr.z);
                     d = vCheck.vabs();
                     vCheck *= radius;
                     vCheck /= d;
                     g->CreateBullet(Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),
                         (ActD.Active)->R_curr,NULL,&GameBulletData[WD_BULLET_GSEED]);
                     g->Owner = NULL;
                 };*/
                 for(i = 0;i < PI*2;i+= PI / 8){
                     g = BulletD.CreateBullet();
                     vCheck = Vector(radius,0,0) * DBM(i,Z_AXIS);
                     g->CreateBullet(Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + radius),
                         Vector(XCYCL(vCheck.x*4 + R_curr.x),YCYCL(vCheck.y*4 + R_curr.y),R_curr.z),NULL,&GameBulletData[WD_BULLET_GSEED]);
                     g->Owner = NULL;
                 };
                 p = (Object*)(ActD.Tail);
                 while(p){
                     if(p->Visibility == VISIBLE){
                         vCheck = Vector(getDistX(p->R_curr.x,R_curr.x),getDistY(p->R_curr.y,R_curr.y),p->R_curr.z - R_curr.z);
                         d = vCheck.vabs();
                         if(d < TNT_POWER_RADIUS && d > 0){
                             p->impulse(vCheck,TNT_POWER_IMPULSE*(TNT_POWER_RADIUS - d) / d,0);
                             if(p->ID == ID_VANGER) ((VangerUnit*)(p))->BulletCollision(TNT_POWER_DAMAGE,NULL);
                         };
                     };
                     p = (Object*)(p->NextTypeList);
                 };
                 break;
             case WORLD_FOSTRAL:
                 for(i = 0;i < PI*2;i+= PI / 8){
                     g = BulletD.CreateBullet();
                     vCheck = Vector(radius,0,0) * DBM(i,Z_AXIS);
                     g->CreateBullet(Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + radius),
                         Vector(XCYCL(vCheck.x*4 + R_curr.x),YCYCL(vCheck.y*4 + R_curr.y),R_curr.z + radius*2),NULL,&GameBulletData[WD_BULLET_FSEED]);
                     g->Owner = NULL;
                 };
                 p = (Object*)(ActD.Tail);
                 while(p){
                     if(p->Visibility == VISIBLE){
                         vCheck = Vector(getDistX(p->R_curr.x,R_curr.x),getDistY(p->R_curr.y,R_curr.y),p->R_curr.z - R_curr.z);
                         d = vCheck.vabs();
                         if(d < TNT_POWER_RADIUS && d > 0){
                             p->impulse(vCheck,TNT_POWER_IMPULSE*(TNT_POWER_RADIUS - d) / d,0);
                             if(p->ID == ID_VANGER) ((VangerUnit*)(p))->BulletCollision(TNT_POWER_DAMAGE,NULL);
                         };
                     };
                     p = (Object*)(p->NextTypeList);
                 };
                 break;
             case WORLD_NECROSS:
                 for(i = 0;i < PI*2;i+= PI / 8){
                     g = BulletD.CreateBullet();
                     vCheck = Vector(radius,0,0) * DBM(i,Z_AXIS);
                     g->CreateBullet(Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + radius),
                         Vector(XCYCL(vCheck.x*4 + R_curr.x),YCYCL(vCheck.y*4 + R_curr.y),R_curr.z + radius*2),NULL,&GameBulletData[WD_BULLET_NSEED]);
                     g->Owner = NULL;
                 };
                 p = (Object*)(ActD.Tail);
                 while(p){
                     if(p->Visibility == VISIBLE){
                         vCheck = Vector(getDistX(p->R_curr.x,R_curr.x),getDistY(p->R_curr.y,R_curr.y),p->R_curr.z - R_curr.z);
                         d = vCheck.vabs();
                         if(d < TNT_POWER_RADIUS && d > 0){
                             p->impulse(vCheck,TNT_POWER_IMPULSE*(TNT_POWER_RADIUS - d) / d,0);
                             if(p->ID == ID_VANGER) ((VangerUnit*)(p))->BulletCollision(TNT_POWER_DAMAGE,NULL);
                         };
                     };
                     p = (Object*)(p->NextTypeList);
                 };
                 break;
         };
         for(i = 0;i < TntNumLink;i++){
             if(TntLinkData[i]->CurrentHeight > 0 && TouchTime == 0)
                 TntLinkData[i]->TouchTime = TntLinkDelay;
         };
     };
 };
References ActD, ActionDispatcher::Active, BulletD, BulletList::CreateBullet(), EffectDispatcher::CreateFireBall(), CurrentHeight, CurrentWorld, DestroyDelay, DT_FIRE_BALL04, EffD, g, GameBulletData, getDistX(), getDistY(), Object::ID, ID_VANGER, Object::impulse(), MapD, NULL, PI, GeneralObject::R_curr, StaticObject::radius, MobileLocation::setPhase(), SOUND_BARREL_DESTROY, UnitList::Tail, Time, TNT_POWER_DAMAGE, TNT_POWER_IMPULSE, TNT_POWER_RADIUS, TntClone, TntLinkData, TntLinkDelay, TntNumLink, TouchTime, Vector::vabs(), VISIBLE, WD_BULLET_FSEED, WD_BULLET_GSEED, WD_BULLET_NSEED, WORLD_FOSTRAL, WORLD_GLORX, WORLD_NECROSS, Object::x, Vector::x, XCYCL, Object::y, Vector::y, YCYCL, Vector::z, and Z_AXIS.
Referenced by Quant(), and Touch().
DrawQuant()
void TntCreature::DrawQuant (void)
 {
 /*  int aaa;
     if(TntClone->QuickCheck()){
         aaa = 0;
         if(HideFlag) HideFlag = 0;
         while(TntClone->cStage != CurrentHeight){
             TntClone->quant(1);
             if(aaa++ > 10) return;
         };
         if(RND(15000) < 5)
             TouchTime = TntLinkDelay;
     };*/
 };
HideEvent()
void TntCreature::HideEvent (void) inline
{
         if(HideFlag != 1){
             HideFlag = 1;
             TntClone->cStage = CurrentHeight = StartHeight;
             Time = 0;
             TouchTime = 0;
         };
     };
References MobileLocation::cStage, CurrentHeight, HideFlag, StartHeight, Time, TntClone, and TouchTime.
Referenced by StaticQuant().
Load()
void TntCreature::Load (XStream & in)
 {
     int i;
     int dx,dy;
     GeneralObject::Init();
     in > R_curr.x;
     in > R_curr.y;
     in > R_curr.z;
     in > nSource;
     in > radius;
     in > StartHeight;
     Status = 0;
     ID = ID_STATIC;
     StaticType = StaticObjectType::TNT;
     Enable = 1;
     CurrentHeight = 0;
     DestroyProcess = MAP_POINT_CRATER06;
 //  DestroyDelay = 5;
     if(NetworkON) DestroyDelay = 350;
     else DestroyDelay = 350 + RND(350);
 //  DestroyDelay = 10 + RND(20);
     if(NetworkON) DelayHeight = 1;
     else DelayHeight = 1 + RND(5);
     Time = 0;
     TouchTime = 0;
     TntLinkDelay = 5;
     TntNumLink = 0;
     TntClone = MLTnt[nSource]->cloning(getDistX(R_curr.x,MLTnt[nSource]->x0),getDistY(R_curr.y,MLTnt[nSource]->y0),"TntLocation");
     dx = abs(getDistX(TntClone->x0,TntClone->x1)) / 2;
     dy = abs(getDistY(TntClone->y0,TntClone->y1)) / 2;
     radius = (int)(sqrt(dx*(double)dx + dy*(double)dy));
     R_curr.x += dx;
     R_curr.y += dy;
     cycleTor(R_curr.x,R_curr.y);
     MaxHeight = TntClone->maxStage - 1;
 //  StartHeight = MaxHeight - 1;
     CurrentHeight = StartHeight = MaxHeight;
 //  TntClone->cStage = CurrentHeight = StartHeight;
     TntClone->setPhase(StartHeight,1);
     HideFlag = 1;
     for(i = 0;i < MAX_TNT_EXPLOSION;i++)
         TntLinkData[i] = NULL;
     NetTime = 0;
     if(NetworkON) NetID = CREATE_NET_ID(NID_TNT);
     else NetID = 0;
 };
References MobileLocation::cloning(), CREATE_NET_ID, CurrentHeight, cycleTor(), DelayHeight, DestroyDelay, DestroyProcess, StaticObject::Enable, getDistX(), getDistY(), HideFlag, GeneralObject::ID, ID_STATIC, MAX_TNT_EXPLOSION, MaxHeight, MLTnt, GeneralObject::NetID, NetTime, NetworkON, NID_TNT, nSource, NULL, GeneralObject::R_curr, StaticObject::radius, RND(), MobileLocation::setPhase(), StartHeight, StaticObject::StaticType, GeneralObject::Status, Time, StaticObjectType::TNT, TntClone, TntLinkData, TntLinkDelay, TntNumLink, TouchTime, Vector::x, MobileLocation::x0, MobileLocation::x1, Vector::y, MobileLocation::y0, MobileLocation::y1, and Vector::z.
Referenced by VLload().
NetDestroy()
void TntCreature::NetDestroy (int fl = 1)
 {
     int i;
     Vector vCheck;
     Object* p;
     int d;
     BulletObject* g;
     if(!HideFlag && CurrentHeight && TntClone->NetQuickCheck(R_curr.x,R_curr.y,radius)){
         CurrentHeight = 0;
         TntClone->setPhase(CurrentHeight,1);
         MapD.CreateCrater(R_curr,MAP_POINT_CRATER06,radius + 10);
         EffD.CreateFireBall(R_curr + Vector(0,0,20),DT_FIRE_BALL04,NULL,1 << 8,0);
         TouchTime = 0;
         Time = 0;
         NetTime = NetGlobalTime + (DestroyDelay*256 / 15);
         if(ActD.Active)
             SOUND_BARREL_DESTROY(getDistX(ActD.Active->R_curr.x,R_curr.x));
         if(fl){
             NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
             NETWORK_OUT_STREAM < NetTime;
             NETWORK_OUT_STREAM.end_body();
         };
         switch(CurrentWorld){ //znfo TNT power scheme
             case WORLD_GLORX:
                 for(i = 0;i < PI*2;i+= PI / 8){
                     g = BulletD.CreateBullet();
                     vCheck = Vector(radius,0,0) * DBM(i,Z_AXIS);
                     g->CreateBullet(Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + radius),
                         Vector(XCYCL(vCheck.x*4 + R_curr.x),YCYCL(vCheck.y*4 + R_curr.y),R_curr.z),NULL,&GameBulletData[WD_BULLET_GSEED]);
                     g->Owner = NULL;
                 };
                 p = (Object*)(ActD.Tail);
                 while(p){
                     if(p->Visibility == VISIBLE){
                         vCheck = Vector(getDistX(p->R_curr.x,R_curr.x),getDistY(p->R_curr.y,R_curr.y),p->R_curr.z - R_curr.z);
                         d = vCheck.vabs();
                         if(d < 2*TNT_POWER_RADIUS && d > 0){
                             p->impulse(vCheck,TNT_POWER_IMPULSE*(TNT_POWER_RADIUS*2 - d) / d,0);
                             if(p->ID == ID_VANGER) ((VangerUnit*)(p))->BulletCollision(TNT_POWER_DAMAGE,NULL);
                         };
                     };
                     p = (Object*)(p->NextTypeList);
                 };
                 break;
             case WORLD_FOSTRAL:
                 for(i = 0;i < PI*2;i+= PI / 8){
                     g = BulletD.CreateBullet();
                     vCheck = Vector(radius,0,0) * DBM(i,Z_AXIS);
                     g->CreateBullet(Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + radius),
                         Vector(XCYCL(vCheck.x*4 + R_curr.x),YCYCL(vCheck.y*4 + R_curr.y),R_curr.z + radius*2),NULL,&GameBulletData[WD_BULLET_FSEED]);
                     g->Owner = NULL;
                 };
                 p = (Object*)(ActD.Tail);
                 while(p){
                     if(p->Visibility == VISIBLE){
                         vCheck = Vector(getDistX(p->R_curr.x,R_curr.x),getDistY(p->R_curr.y,R_curr.y),p->R_curr.z - R_curr.z);
                         d = vCheck.vabs();
                         if(d < TNT_POWER_RADIUS && d > 0){
                             p->impulse(vCheck,TNT_POWER_IMPULSE*(TNT_POWER_RADIUS - d) / d,0);
                             if(p->ID == ID_VANGER) ((VangerUnit*)(p))->BulletCollision(TNT_POWER_DAMAGE,NULL);
                         };
                     };
                     p = (Object*)(p->NextTypeList);
                 };
                 break;
             case WORLD_NECROSS:
                 for(i = 0;i < PI*2;i+= PI / 8){
                     g = BulletD.CreateBullet();
                     vCheck = Vector(radius,0,0) * DBM(i,Z_AXIS);
                     g->CreateBullet(Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + radius),
                         Vector(XCYCL(vCheck.x*4 + R_curr.x),YCYCL(vCheck.y*4 + R_curr.y),R_curr.z + radius*2),NULL,&GameBulletData[WD_BULLET_NSEED]);
                     g->Owner = NULL;
                 };
                 p = (Object*)(ActD.Tail);
                 while(p){
                     if(p->Visibility == VISIBLE){
                         vCheck = Vector(getDistX(p->R_curr.x,R_curr.x),getDistY(p->R_curr.y,R_curr.y),p->R_curr.z - R_curr.z);
                         d = vCheck.vabs();
                         if(d < TNT_POWER_RADIUS && d > 0){
                             p->impulse(vCheck,TNT_POWER_IMPULSE*(TNT_POWER_RADIUS - d) / d,0);
                             if(p->ID == ID_VANGER) ((VangerUnit*)(p))->BulletCollision(TNT_POWER_DAMAGE,NULL);
                         };
                     };
                     p = (Object*)(p->NextTypeList);
                 };
                 break;
         };
         for(i = 0;i < TntNumLink;i++){
             if(TntLinkData[i]->CurrentHeight > 0 && TouchTime == 0)
                 TntLinkData[i]->TouchTime = TntLinkDelay;
         };
     };
 };
References ActD, ActionDispatcher::Active, BulletD, BulletList::CreateBullet(), EffectDispatcher::CreateFireBall(), CurrentHeight, CurrentWorld, DestroyDelay, DT_FIRE_BALL04, EffD, g, GameBulletData, getDistX(), getDistY(), HideFlag, Object::ID, ID_VANGER, Object::impulse(), MapD, NetGlobalTime, GeneralObject::NetID, NetTime, NETWORK_OUT_STREAM, NULL, PI, GeneralObject::R_curr, StaticObject::radius, MobileLocation::setPhase(), SOUND_BARREL_DESTROY, UnitList::Tail, Time, TNT_POWER_DAMAGE, TNT_POWER_IMPULSE, TNT_POWER_RADIUS, TntClone, TntLinkData, TntLinkDelay, TntNumLink, TouchTime, Vector::vabs(), VISIBLE, WD_BULLET_FSEED, WD_BULLET_GSEED, WD_BULLET_NSEED, WORLD_FOSTRAL, WORLD_GLORX, WORLD_NECROSS, Object::x, Vector::x, XCYCL, Object::y, Vector::y, YCYCL, Vector::z, and Z_AXIS.
Referenced by NetEvent(), NetQuant(), and Touch().
NetEvent()
void TntCreature::NetEvent (void)
 {
     NETWORK_IN_STREAM > NetTime;
     if(!HideFlag && NetTime > NetGlobalTime)
         NetDestroy(0);
 };
References HideFlag, NetDestroy(), NetGlobalTime, NetTime, and NETWORK_IN_STREAM.
NetHideEvent()
void TntCreature::NetHideEvent (void) inline
{
         if(HideFlag != 1)
             HideFlag = 1;
     };
References HideFlag.
Referenced by NetQuant(), and StaticQuant().
NetQuant()
void TntCreature::NetQuant (void)
 {
     BulletObject* p;
     Vector vCheck;
     if(TntClone->NetQuickCheck(R_curr.x,R_curr.y,radius)){
         if(HideFlag){
             if(NetTime > NetGlobalTime){
                 TntClone->setPhase(0,1);
                 if(CurrentWorld == WORLD_GLORX) ClearBarell(R_curr.x,R_curr.y,radius,83,R_curr.z);
                 else ClearBarell(R_curr.x,R_curr.y,radius,7,R_curr.z);
                 CurrentHeight = 0;
                 TouchTime = 0;
                 Time = 0;
             }else{
                 TntClone->cStage = CurrentHeight = StartHeight;
                 Time = 0;
                 TouchTime = 0;
                 TntClone->setPhase(0,1);
                 if(CurrentWorld == WORLD_GLORX) ClearBarell(R_curr.x,R_curr.y,radius,83,R_curr.z);
                 else ClearBarell(R_curr.x,R_curr.y,radius,7,R_curr.z);
                 TntClone->setPhase(CurrentHeight,0);
             };
             HideFlag = 0;
         };
         if(TouchTime > 0){
             TouchTime--;
             if(TouchTime <= 0) NetDestroy();
         }else{
             if(NetTime < NetGlobalTime){
                 if(CurrentHeight < MaxHeight){
                     if(Time <= 0){
                         Time =  DelayHeight;
                         CurrentHeight++;
                         TntClone->setPhase(CurrentHeight,0);
                     }else Time--;
                 }else{
                     switch(CurrentWorld){
                         case 0:
                             if(RND(300) < 5){
                                 p = BulletD.CreateBullet();
                                 vCheck = Vector(radius,0,0) * DBM((int)(RND(2*PI)),Z_AXIS);
                                 p->CreateBullet(R_curr,
                                     Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z),NULL,&GameBulletData[WD_BULLET_SPORE]);
                                 p->Owner = NULL;
                             };
                             break;
                         case 1:
                             if(RND(1000) < 5)
                                 TouchTime = TntLinkDelay;
                             break;
                     };
                 };
             };
         };
     }else NetHideEvent();
 };
References BulletD, ClearBarell(), BulletObject::CreateBullet(), BulletList::CreateBullet(), MobileLocation::cStage, CurrentHeight, CurrentWorld, DelayHeight, GameBulletData, HideFlag, MaxHeight, NetDestroy(), NetGlobalTime, NetHideEvent(), NetTime, NULL, BulletObject::Owner, PI, GeneralObject::R_curr, StaticObject::radius, RND(), MobileLocation::setPhase(), StartHeight, Time, TntClone, TntLinkDelay, TouchTime, WD_BULLET_SPORE, WORLD_GLORX, Vector::x, XCYCL, Vector::y, YCYCL, Vector::z, and Z_AXIS.
Referenced by StaticQuant().
NetUpdate()
void TntCreature::NetUpdate (void)
Quant()
void TntCreature::Quant (void)
 {
     BulletObject* p;
     Vector vCheck;
     if(TntClone->QuickCheck()){
         if(HideFlag)
             HideFlag = 0;
         if(TouchTime > 0){
             TouchTime--;
             if(TouchTime <= 0) Destroy();
         }else{
             if(CurrentHeight < MaxHeight){
                 if(Time <= 0){
                     Time =  DelayHeight;
                     CurrentHeight++;
                     TntClone->setPhase(CurrentHeight,0);
                     if(ActD.Active && abs(getDistY(R_curr.y,ViewY)) - (radius << 1) < TurnSideY && abs(getDistX(R_curr.x,ViewX)) - (radius << 1) < TurnSideX)
                         SOUND_GROW(getDistX(ActD.Active->R_curr.x,R_curr.x))
                 }else Time--;
             }else{
                 switch(CurrentWorld){
                     case 0:
                         if(RND(300) < 5){
                             p = BulletD.CreateBullet();
                             vCheck = Vector(radius,0,0) * DBM((int)(RND(2*PI)),Z_AXIS);
                             p->CreateBullet(R_curr,
                                 Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z),NULL,&GameBulletData[WD_BULLET_SPORE]);
                             p->Owner = NULL;
                         };
                         break;
                     case 1:
                         if(RND(1000) < 5 && abs(getDistY(R_curr.y,ViewY)) - (radius << 1) < TurnSideY && abs(getDistX(R_curr.x,ViewX)) - (radius << 1) < TurnSideX)
                             TouchTime = TntLinkDelay;
                         break;
                 };
             };
         };
     };
 };
References ActD, ActionDispatcher::Active, BulletD, BulletObject::CreateBullet(), BulletList::CreateBullet(), CurrentHeight, CurrentWorld, DelayHeight, Destroy(), GameBulletData, getDistX(), getDistY(), HideFlag, MaxHeight, NULL, BulletObject::Owner, PI, GeneralObject::R_curr, StaticObject::radius, RND(), MobileLocation::setPhase(), SOUND_GROW, Time, TntClone, TntLinkDelay, TouchTime, TurnSideX, TurnSideY, ViewX, ViewY, WD_BULLET_SPORE, Object::x, Vector::x, XCYCL, Vector::y, YCYCL, Vector::z, and Z_AXIS.
Referenced by StaticQuant().
Save()
void TntCreature::Save (XStream & in)
 {
     in < R_curr.x;
     in < R_curr.y;
     in < R_curr.z;
     in < nSource;
     in < radius;
     in < StartHeight;
 };
References nSource, GeneralObject::R_curr, StaticObject::radius, StartHeight, Vector::x, Vector::y, and Vector::z.
Touch()
void TntCreature::Touch (GeneralObject * p) virtual
Reimplemented from GeneralObject.
 {
     if(CurrentHeight){
         if(NetworkON) NetDestroy();
         else Destroy();
     };
 };
References CurrentHeight, Destroy(), NetDestroy(), and NetworkON.
Member Data Documentation
CurrentHeight
int TntCreature::CurrentHeight
Referenced by Destroy(), HideEvent(), Load(), NetDestroy(), NetQuant(), Quant(), StaticOpen(), and Touch().
DelayHeight
int TntCreature::DelayHeight
Referenced by Load(), NetQuant(), and Quant().
DestroyDelay
int TntCreature::DestroyDelay
Referenced by Destroy(), Load(), and NetDestroy().
DestroyProcess
int TntCreature::DestroyProcess
Referenced by Load().
HideFlag
int TntCreature::HideFlag
Referenced by HideEvent(), Load(), NetDestroy(), NetEvent(), NetHideEvent(), NetQuant(), and Quant().
MaxHeight
int TntCreature::MaxHeight
Referenced by Load(), NetQuant(), Quant(), and StaticOpen().
NetTime
unsigned int TntCreature::NetTime
Referenced by Load(), NetDestroy(), NetEvent(), and NetQuant().
nSource
int TntCreature::nSource
Referenced by Load(), Save(), and StaticOpen().
StartHeight
int TntCreature::StartHeight
Referenced by HideEvent(), Load(), NetQuant(), Save(), and StaticOpen().
Time
int TntCreature::Time
Referenced by Destroy(), HideEvent(), Load(), NetDestroy(), NetQuant(), and Quant().
TntClone
MobileLocation* TntCreature::TntClone
Referenced by Destroy(), HideEvent(), Load(), NetDestroy(), NetQuant(), and Quant().
TntLinkData
TntCreature* TntCreature::TntLinkData[MAX_TNT_EXPLOSION]
Referenced by Destroy(), Load(), NetDestroy(), StaticOpen(), and TestLink2Link().
TntLinkDelay
int TntCreature::TntLinkDelay
Referenced by Destroy(), Load(), NetDestroy(), NetQuant(), and Quant().
TntNumLink
int TntCreature::TntNumLink
Referenced by Destroy(), Load(), NetDestroy(), StaticOpen(), and TestLink2Link().
TouchTime
int TntCreature::TouchTime
Referenced by Destroy(), HideEvent(), Load(), NetDestroy(), NetQuant(), and Quant().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp