Vangers: EscaveEngine Struct Reference
EscaveEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Quant (void)
void Active (void)
Public Member Functions inherited from ElevatorEngine
void Close (void)
void Link (void)
void Touch (GeneralObject *obj, SensorDataType *p)
Public Member Functions inherited from LocationEngine
void NetEvent (void)
void SoundEvent (void)
Public Attributes
int LastOpen
int StartAngle
Public Attributes inherited from ElevatorEngine
DoorEngine * DoorLink
char * DoorName
int UseFlag
int ActionFlag
Public Attributes inherited from EnterEngine
SensorDataType * ActionLink
EnterCenter * Owner
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Active()
void EscaveEngine::Active (void) virtual
Reimplemented from ElevatorEngine.
Reimplemented in ImpulseSpot, and ImpulseEscave.
 {
     UseFlag = 1;
     ActionLink->Enable = 0;
     LastOpen = 1;
 };
References EnterEngine::ActionLink, StaticObject::Enable, LastOpen, and ElevatorEngine::UseFlag.
Open()
void EscaveEngine::Open (Parser & in) virtual
Reimplemented from ElevatorEngine.
Reimplemented in ImpulseSpot, and ImpulseEscave.
 {
     ElevatorEngine::Open(in);
     in.search_name("StartAngle");
     StartAngle = in.get_int();
     Type = EngineTypeList::ESCAVE;
     LastOpen = 0;
 };
References EngineTypeList::ESCAVE, Parser::get_int(), LastOpen, ElevatorEngine::Open(), Parser::search_name(), StartAngle, and LocationEngine::Type.
Quant()
void EscaveEngine::Quant (void) virtual
Reimplemented from ElevatorEngine.
Reimplemented in ImpulseSpot, and ImpulseEscave.
 {
     if(MLLink && !MLLink->frozen){
         if(UseFlag){
             if(DoorLink->Mode == EngineModeList::WAIT && !(DoorLink->ProcessFlag) && !LastOpen){
                 Owner->PutCenter(this);
                 UseFlag = 0;
                 ActionLink->Enable = 1;
             };
         }else{
             if(DoorLink->Mode != EngineModeList::WAIT){
                 Owner->LockedCenter(this);
                 UseFlag = 1;
                 ActionLink->Enable = 0;
              };
         };
     }else{
         if(UseFlag){
             Owner->PutCenter(this);
             UseFlag = 0;
             ActionLink->Enable = 1;
         };
     };
     LastOpen = 0;
 };
References EnterEngine::ActionLink, ElevatorEngine::DoorLink, StaticObject::Enable, MobileLocation::frozen, LastOpen, EnterCenter::LockedCenter(), LocationEngine::MLLink, LocationEngine::Mode, EnterEngine::Owner, DoorEngine::ProcessFlag, EnterCenter::PutCenter(), ElevatorEngine::UseFlag, and EngineModeList::WAIT.
Member Data Documentation
LastOpen
int EscaveEngine::LastOpen
Referenced by Active(), Open(), and Quant().
StartAngle
int EscaveEngine::StartAngle
Referenced by Open().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp