Vangers: ExplosionObject Struct Reference
ExplosionObject Struct Reference
#include <effect.h>
Public Member Functions
void InitProcess (char _type)
void Init (StorageType *s)
void Free (void)
void Quant (void)
void DrawQuant (void)
void CreateExplosion (const Vector &v, BaseObject *_owner, int _scale, int _dscale)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
int Scale
int dScale
int FirstRadius
BaseObject * Owner
ParticleMapProcess MainMapProcess
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CreateExplosion()
void ExplosionObject::CreateExplosion (const Vector & v, BaseObject * _owner, int _scale, int _dscale)
 {
     Owner = _owner;
     if(Owner) R_curr = Owner->R_curr;
     else R_curr = v;
     R_curr.z += EXPLOSION_OFFSET;
     Scale = _scale;
     dScale = _dscale;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
     GetVisible();
     MapLevel = 1;
     MainMapProcess.activate();
     radius = (FirstRadius * Scale) >> 15;
     MapD.CreateLight(R_curr.x,R_curr.y,R_curr.z,radius,32,LIGHT_TYPE::STATIONARY);
 };
References ParticleMapProcess::activate(), cycleTor(), dScale, EXPLOSION_OFFSET, FirstRadius, MainMapProcess, MapD, BaseObject::MapLevel, Owner, GeneralObject::R_curr, BaseObject::radius, Scale, LIGHT_TYPE::STATIONARY, GeneralObject::Status, Vector::x, Vector::y, and Vector::z.
Referenced by EffectDispatcher::CreateExplosion().
DrawQuant()
void ExplosionObject::DrawQuant (void)
 {
     int tx,ty,s;
     if(AdvancedView) s = G2LF(R_curr.x,R_curr.y,R_curr.z,tx,ty);
     else s = G2LS(R_curr.x,R_curr.y,R_curr.z,tx,ty);
     if(MainMapProcess.process((char*)XGR_GetVideoLine(0),tx,ty,Scale*s >> 8,0,0,R_curr.z,R_curr.x & clip_mask_x, R_curr.y & clip_mask_y)) Status |= SOBJ_DISCONNECT;
 //  if(MainMapProcess.process((char*)(VS(_video)->_video),tx,ty,Scale*curGMap -> xsize / TurnSecX,0,0)) Status |= SOBJ_DISCONNECT;
 };
References AdvancedView, clip_mask_x, clip_mask_y, G2LF(), G2LS(), MainMapProcess, ParticleMapProcess::process(), GeneralObject::R_curr, Scale, SOBJ_DISCONNECT, GeneralObject::Status, Vector::x, XGR_GetVideoLine(), Vector::y, and Vector::z.
Free()
void ExplosionObject::Free (void)
 {
     MainMapProcess.finit();
 };
References ParticleMapProcess::finit(), and MainMapProcess.
Init()
void ExplosionObject::Init (StorageType * s)
 {
     BaseObject::Init(s);
     ID = ID_EXPLOSION;
     Scale = 1 << 15;
     dScale = 0;
     Owner = NULL;
 };
References dScale, GeneralObject::ID, ID_EXPLOSION, NULL, Owner, and Scale.
InitProcess()
void ExplosionObject::InitProcess (char _type)
 {
     MainMapProcess.init(_type);
     FirstRadius = (MainMapProcess.Xmax > MainMapProcess.Ymax) ? MainMapProcess.Xmax : MainMapProcess.Ymax;
 };
References FirstRadius, ParticleMapProcess::init(), MainMapProcess, ParticleMapProcess::Xmax, and ParticleMapProcess::Ymax.
Quant()
void ExplosionObject::Quant (void)
 {
     GetVisible();
     Scale += dScale;
     if(Scale > dScale) radius = (FirstRadius * Scale) >> 15;
     if(Owner){
         if(Owner->Status & SOBJ_DISCONNECT) Owner = NULL;
         else{
             R_curr = Owner->R_curr;
             R_curr.z += EXPLOSION_OFFSET;
         };
     };
     if(Visibility != VISIBLE){
         if(MainMapProcess.process((char*)XGR_GetVideoLine(0),0,0,1,0,1, 255, 1, 1))  Status |= SOBJ_DISCONNECT;
     }else MapLevel = 1;
 };
References dScale, EXPLOSION_OFFSET, FirstRadius, MainMapProcess, BaseObject::MapLevel, NULL, Owner, ParticleMapProcess::process(), GeneralObject::R_curr, BaseObject::radius, Scale, SOBJ_DISCONNECT, GeneralObject::Status, BaseObject::Visibility, VISIBLE, XGR_GetVideoLine(), and Vector::z.
Member Data Documentation
dScale
int ExplosionObject::dScale
Referenced by CreateExplosion(), Init(), and Quant().
FirstRadius
int ExplosionObject::FirstRadius
Referenced by CreateExplosion(), InitProcess(), and Quant().
MainMapProcess
ParticleMapProcess ExplosionObject::MainMapProcess
Referenced by CreateExplosion(), DrawQuant(), Free(), InitProcess(), and Quant().
Owner
BaseObject* ExplosionObject::Owner
Referenced by CreateExplosion(), Init(), and Quant().
Scale
int ExplosionObject::Scale
Referenced by CreateExplosion(), DrawQuant(), Init(), and Quant().
The documentation for this struct was generated from the following files:
src/units/effect.h
src/units/effect.cpp