Vangers: HordeObject Struct Reference
HordeObject Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void Quant (void)
void DrawQuant (void)
void CreateHorde (Vector v, int r, int z, int cZ, VangerUnit *own=NULL)
void Touch (GeneralObject *p)
void Free (void)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Attributes
int Mode
int Speed
int Precision
VangerUnit * TargetObject
int NumParticle
SimpleParticleType * Data
int Power
Vector vDelta
int zAttackRadius
int AttackRadius
GeneralObject * Owner
int zCruiser
Vector vZone
int Time
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CreateHorde()
void HordeObject::CreateHorde (Vector v, int r, int z, int cZ, VangerUnit * own = NULL)
 {
     ID = ID_HORDE;
     Speed = 10;
     Precision = 7;
     Power = (50 << 16) / UnitGlobalTime;
     Mode = HORDE_RESTORE_MODE;
     NumParticle = HORDE_PARTICLE_NUM;
     vDelta = Vector(0,0,0);
     R_curr = v;
     cycleTor(R_curr.x,R_curr.y);
     GetVisible();
     Status = 0;
     TargetObject = NULL;
     radius =  r;
     AttackRadius = 200;
     zAttackRadius = z;
     Owner = own;
     zCruiser = cZ + radius;
     vZone = R_curr;
     Time = 150;
 };
References AttackRadius, cycleTor(), HORDE_PARTICLE_NUM, HORDE_RESTORE_MODE, GeneralObject::ID, ID_HORDE, Mode, NULL, NumParticle, Owner, Power, Precision, GeneralObject::R_curr, BaseObject::radius, Speed, GeneralObject::Status, TargetObject, Time, UnitGlobalTime, vDelta, vZone, Vector::x, Vector::y, zAttackRadius, and zCruiser.
DrawQuant()
void HordeObject::DrawQuant (void)
 {
     int i;
     SimpleParticleType* p;
     Vector vPos;
     int tx,ty;
     //std::cout<<"HordeObject::DrawQuant "<<ActD.Active<<std::endl;
     if(Status & SOBJ_DISCONNECT) return;
     if(ActD.Active)
         SOUND_HORDE(getDistX(ActD.Active->R_curr.x,R_curr.x));
     if(AdvancedView){
         for(i = 0,p = Data;i < NumParticle;i++,p++){
             p->QuantP(R_curr << 8, vDelta << 8,3 << 8,5);
             vPos = p->vR;
             vPos >>= 8;
             G2LQ(vPos.x,vPos.y,vPos.z,tx,ty);
             if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
         };
     }else{
         if(CurrentWorld < MAIN_WORLD_MAX - 1){
             for(i = 0,p = Data;i < NumParticle;i++,p++){
                 p->QuantP(R_curr << 8, vDelta << 8,3 << 8,5);
                 tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                 ty = ((int)round((p->vR.y - SPViewY) * ScaleMapInvFlt) >> 8)+ ScreenCY;
                 if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
             };
         }else{
             for(i = 0,p = Data;i < NumParticle;i++,p++){
                 p->QuantP(R_curr << 8, vDelta << 8,3 << 8,5);
                 tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                 ty = ((int)round(SPGetDistY(p->vR.y,SPViewY) * ScaleMapInvFlt) >> 8) + ScreenCY;
                 if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
             };
         };
     };
 };
References ActD, ActionDispatcher::Active, AdvancedView, SimpleParticleType::Color, CurrentWorld, Data, G2LQ(), getDistX(), MAIN_WORLD_MAX, NumParticle, SimpleParticleType::QuantP(), GeneralObject::R_curr, round(), ScaleMapInvFlt, ScreenCX, ScreenCY, SOBJ_DISCONNECT, SOUND_HORDE, SPGetDistX(), SPGetDistY(), SPViewX, SPViewY, GeneralObject::Status, UcutLeft, VcutDown, VcutUp, vDelta, SimpleParticleType::vR, Object::x, Vector::x, XGR_SetPixelFast(), Vector::y, and Vector::z.
Free()
void HordeObject::Free (void)
 {
     delete[] Data;
 };
References Data.
Init()
void HordeObject::Init (void)
 {
     BaseObject::Init();
     Data = new SimpleParticleType[HORDE_PARTICLE_NUM];
 };
References Data, and HORDE_PARTICLE_NUM.
Referenced by HordeList::CreateHorde().
Quant()
void HordeObject::Quant (void)
 {
     int lv;
     int i;
     int phi;
     int radius8,r;
     VangerUnit* n;
     SimpleParticleType* p;
     Vector vTarget;
     int d,md,l;
     int update_log = 0;
     VangerFunctionType* g;
     Vector v;
     if(Status & SOBJ_DISCONNECT) return;
     lv = Visibility;
     GetVisible();
     if(Visibility == VISIBLE){
         if(lv == UNVISIBLE && Mode == HORDE_ATTACK_MODE)
             Mode = HORDE_RESTORE_MODE;
         if(Owner){
             Time--;
             if(Time <= 0) Status |= SOBJ_DISCONNECT;
         };
         switch(Mode){
             case HORDE_RESTORE_MODE:
                 vDelta = Vector(0,0,0);
                 radius8 = radius << 8;
                 vTarget = R_curr << 8;
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     r = RND(radius8);
                     phi = rPI(RND(2*PI));
                     p->vR = vTarget + Vector(round(Cos(phi)*r),round(Sin(phi)*r),0);
                     p->vD = Vector(0,0,0);
                     p->Color = 1;
                 };
                 Mode = HORDE_ATTACK_MODE;
                 break;
             case HORDE_ATTACK_MODE:
                 if(TargetObject){
                     if(TargetObject->Status & SOBJ_DISCONNECT){
                         TargetObject = NULL;
                         update_log = 1;
                     }else{
                         g = ActD.fTail;
                         while(g){
                             if(g->ID == PROTRACTOR_PALLADIUM){
                                 v = Vector(getDistX(R_curr.x,g->vR.x),getDistY(R_curr.y,g->vR.y),R_curr.z - g->vR.z);
                                 d = v.vabs();
                                 if(d < PALLADIUM_RADIUS){
                                     vDelta = v * Speed;
                                     vDelta /= d;
                                 };
                                 break;
                             };
                             g = g->Next;
                         };
                         if(!g){
                             if(!(TargetObject->dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH | TOUCH_OF_WATER)) && TargetObject && TargetObject->ExternalDraw && TargetObject->draw_mode == NORMAL_DRAW_MODE && !(TargetObject->BeebonationFlag)){
                                 vTarget = Vector(getDistX(vZone.x,R_curr.x),getDistY(vZone.y,R_curr.y),vZone.z - R_curr.z);
                                 d = vTarget.vabs();
                                 if(d > AttackRadius){
                                     TargetObject = NULL;
                                     update_log = 1;
                                 }else
                                     vTarget = Vector(getDistX(TargetObject->R_curr.x,R_curr.x),getDistY(TargetObject->R_curr.y,R_curr.y),TargetObject->R_curr.z - R_curr.z);
                             }else{
                                 vTarget = Vector(getDistX(vZone.x,R_curr.x),getDistY(vZone.y,R_curr.y),vZone.z - R_curr.z);
                                 TargetObject = NULL;
                                 update_log = 1;
                             };
                             d = vTarget.vabs();
                             if(d){
                                 vDelta += vTarget*Precision / d;
                                 d = vDelta.vabs();
                                 if(d > Speed) vDelta = vDelta * Speed / d;
                             };
                         };
                         R_curr += vDelta;
                         cycleTor(R_curr.x,R_curr.y);
                     };
                 }else{
                     g = ActD.fTail;
                     while(g){
                         if(g->ID == PROTRACTOR_PALLADIUM){
                             v = Vector(getDistX(R_curr.x,g->vR.x),getDistY(R_curr.y,g->vR.y),R_curr.z - g->vR.z);
                             d = v.vabs();
                             if(d < PALLADIUM_RADIUS){
                                 vDelta = v * Speed;
                                 vDelta /= d;
                                 R_curr += vDelta;
                                 cycleTor(R_curr.x,R_curr.y);
                             };
                             break;
                         };
                         g = g->Next;
                     };
                     if(!g){
                         vTarget = Vector(getDistX(vZone.x,R_curr.x),getDistY(vZone.y,R_curr.y),vZone.z - R_curr.z);
                         d = vTarget.vabs();
                         if(d){
                             vDelta += vTarget*Precision / d;
                             d = vDelta.vabs();
                             if(d > Speed) vDelta = vDelta * Speed / d;
                         };
                         R_curr += vDelta;
                         cycleTor(R_curr.x,R_curr.y);
                         md = AttackRadius - radius;
                         n = (VangerUnit*)(ActD.Tail);
                         while(n){
                             if(((VangerUnit*)(n))->Visibility == VISIBLE){
                                 d = getDistY(R_curr.y,n->R_curr.y);
                                 if(d < AttackRadius){
                                     if(!(n->dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH | TOUCH_OF_WATER)) && n->ExternalDraw && n->draw_mode == NORMAL_DRAW_MODE && !(n->BeebonationFlag)){
                                         l  = getDistX(R_curr.x,n->R_curr.x);
                                         if(l < AttackRadius){
                                             l = round(sqrt(l*(double)l + d*(double)d));
                                             if(l < md){
                                                 md = l;
                                                 TargetObject = n;
                                                 update_log = 1;
                                             };
                                         };
                                     };
                                 };
                             };
                             n = (VangerUnit*)(n->NextTypeList);
                         };
                     };
                 };
                 break;
         };
     }else{
         if(Mode == HORDE_ATTACK_MODE){
             if(TargetObject){
                 if(TargetObject->Status & SOBJ_DISCONNECT){
                     TargetObject = NULL;
                     update_log = 1;
                 }else{
                     if(!(TargetObject->dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH | TOUCH_OF_WATER)) && TargetObject && TargetObject->ExternalDraw && TargetObject->draw_mode == NORMAL_DRAW_MODE && !(TargetObject->BeebonationFlag)){
                         vTarget = Vector(getDistX(vZone.x,R_curr.x),getDistY(vZone.y,R_curr.y),vZone.z - R_curr.z);
                         d = vTarget.vabs();
                         if(d > AttackRadius){
                             TargetObject = NULL;
                             update_log = 1;
                         }else
                             vTarget = Vector(getDistX(TargetObject->R_curr.x,R_curr.x),getDistY(TargetObject->R_curr.y,R_curr.y),TargetObject->R_curr.z - R_curr.z);
                     }else{
                         vTarget = Vector(getDistX(vZone.x,R_curr.x),getDistY(vZone.y,R_curr.y),vZone.z - R_curr.z);
                         TargetObject = NULL;
                         update_log = 1;
                     };
                     d = vTarget.vabs();
                     if(d){
                         vDelta += vTarget*Precision / d;
                         d = vDelta.vabs();
                         if(d > Speed) vDelta = vDelta * Speed / d;
                     }else vDelta = Vector(0,0,0);
                     R_curr += vDelta;
                     cycleTor(R_curr.x,R_curr.y);
                 };
             }else{
                 vTarget = Vector(getDistX(vZone.x,R_curr.x),getDistY(vZone.y,R_curr.y),vZone.z - R_curr.z);
                 d = vTarget.vabs();
                 if(d){
                     vDelta += vTarget*Precision / d;
                     d = vDelta.vabs();
                     if(d > Speed) vDelta = vDelta * Speed / d;
                 }else vDelta = Vector(0,0,0);
                 R_curr += vDelta;
                 cycleTor(R_curr.x,R_curr.y);
             };
         };
     };
 };
References ActD, AttackRadius, VangerUnit::BeebonationFlag, SimpleParticleType::Color, Cos(), cycleTor(), Data, Object::draw_mode, VangerUnit::ExternalDraw, ActionDispatcher::fTail, g, getDistX(), getDistY(), GROUND_COLLISION, HORDE_ATTACK_MODE, HORDE_RESTORE_MODE, Mode, NORMAL_DRAW_MODE, NULL, NumParticle, Owner, PALLADIUM_RADIUS, PI, Precision, PROTRACTOR_PALLADIUM, GeneralObject::R_curr, BaseObject::radius, RND(), round(), rPI, Sin(), SOBJ_DISCONNECT, Speed, GeneralObject::Status, UnitList::Tail, TargetObject, Time, TOUCH_OF_WATER, UNVISIBLE, Vector::vabs(), SimpleParticleType::vD, vDelta, BaseObject::Visibility, VISIBLE, SimpleParticleType::vR, vZone, WHEELS_TOUCH, Object::x, Vector::x, Object::y, Vector::y, and Vector::z.
Touch()
void HordeObject::Touch (GeneralObject * p) virtual
Reimplemented from GeneralObject.
 {
     if(p->ID == ID_VANGER){
         if(((VangerUnit*)(p))->BeebonationFlag) return;
         ((VangerUnit*)(p))->BulletCollision(Power,NULL);
     };
 };
References GeneralObject::ID, ID_VANGER, NULL, and Power.
Member Data Documentation
AttackRadius
int HordeObject::AttackRadius
Referenced by CreateHorde(), and Quant().
Data
SimpleParticleType* HordeObject::Data
Referenced by DrawQuant(), Free(), Init(), and Quant().
Mode
int HordeObject::Mode
Referenced by CreateHorde(), and Quant().
NumParticle
int HordeObject::NumParticle
Referenced by CreateHorde(), DrawQuant(), and Quant().
Owner
GeneralObject* HordeObject::Owner
Referenced by CreateHorde(), and Quant().
Power
int HordeObject::Power
Referenced by CreateHorde(), and Touch().
Precision
int HordeObject::Precision
Referenced by CreateHorde(), and Quant().
Speed
int HordeObject::Speed
Referenced by CreateHorde(), and Quant().
TargetObject
VangerUnit* HordeObject::TargetObject
Referenced by CreateHorde(), and Quant().
Time
int HordeObject::Time
Referenced by CreateHorde(), and Quant().
vDelta
Vector HordeObject::vDelta
Referenced by CreateHorde(), DrawQuant(), and Quant().
vZone
Vector HordeObject::vZone
Referenced by CreateHorde(), and Quant().
zAttackRadius
int HordeObject::zAttackRadius
Referenced by CreateHorde().
zCruiser
int HordeObject::zCruiser
Referenced by CreateHorde().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp