Vangers: XErrorHandler Struct Reference
XErrorHandler Struct Reference
#include <xerrhand.h>
Public Member Functions
XErrorHandler ()
~XErrorHandler ()
void SetPrefix (const char *s)
void SetPostfix (const char *s)
void Abort (const char *message, int code=XERR_USER, int val=-1, const char *subj=NULL)
void Log (const char *message)
void Exit (void)
void RTC (const char *file, unsigned int line, const char *expr)
Public Attributes
const char * prefix
const char * postfix
std::string log_name
std::fstream log_file
Detailed Description
Constructor & Destructor Documentation
XErrorHandler()
XErrorHandler::XErrorHandler (void)
 {
 #ifndef __HAIKU__
     log_name = "logfile.txt";
 #else
     log_name = SDL_GetPrefPath("KranX Productions", "Vangers");
     log_name += "/logfile.txt";
 #endif
     log_file.open(log_name.c_str(),std::ios::out|std::ios::trunc);
     log_file.close();
 }
References log_file, and log_name.
~XErrorHandler()
XErrorHandler::~XErrorHandler (void)
 {
     if(log_file.is_open())
         log_file.close();
 }
References log_file.
Member Function Documentation
Abort()
void XErrorHandler::Abort (const char * message, int code = XERR_USER, int val = -1, const char * subj = NULL)
 {
     log_file.open(log_name.c_str(),std::ios::out|std::ios::app);
     log_file<<"Abbort: "<<message<<" code:"<<code<<" val:"<<val
         <<std::endl<<"Subj:"<<subj<<std::endl;
     log_file.close();
     //MessageBox(NULL,outmsg,prefix,attr | MB_TOPMOST | MB_SYSTEMMODAL);
     exit(code);
 }
References log_file, and log_name.
Referenced by dgRoom::acceptQUERY(), dgRoom::acceptTEXT(), aciAddRubox(), aciExpropriation(), aciGetCurMatrixPrice(), aciGetRubox(), aciOpenWorldLink(), aciSell_Item(), aciSell_Matrix(), aciWorldLinkExist(), ParticleMapProcess::activate(), StorageType::Active(), iStack::add(), iScreen::add_object(), MemoryHeap::alloc(), dgCell::analyzeACCESS(), ivrtMap::analyzeINI(), aOutStr(), aOutText32(), aOutText32clip(), xtList< Type >::append(), XTList< Type >::append(), XTListAlt< Type >::append(), aPutChar(), aPutStr(), aPutStr32(), aTextHeight32(), aTextWidth32(), Particle::b_link(), MemoryHeap::back(), uvsVanger::break_harvest(), aciWorldMap::calc_shapes(), actIntDispatcher::change_ibs(), uvsBunch::Check(), ClearBarell(), ScriptFile::close_bscript(), Comparision(), KDWIN::create_server(), StorageType::Deactive(), Object::destroy_double_level(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroyBarellSpot(), DestroySmoothPut(), dgCell::doCMD(), Object::draw(), uvsVanger::emptyContainer(), uvsVanger::emuCheck(), uvsVanger::emuStep(), MemoryHeap::end_alloc(), OutputEventBuffer::end_body(), actIntDispatcher::EventQuant(), dgCell::expressACCESS(), ModelDispatcher::FindModel(), ParticleProcess::finit(), EscaveRTO::Finit(), actIntDispatcher::free_ibs(), GeneralSystemLoad(), FileBox::get(), MemoryHeap::get(), uvsWorld::get_anymal(), actIntDispatcher::get_locdata_id(), uvsVanger::get_shop(), EnterCenter::GetCenter(), TrackUnit::GetDirect(), dgFile::getElement(), dgMolecule::getHandledPhrase(), GetKeepSpace(), TrackUnit::GetNode(), StorageClusterType::GetPoint(), MemoryStorageType::GetPoint(), TrackType::GetPosition(), getRC(), getSubj(), dgMolecule::getVarPhrase(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), uvsVanger::go_from_escave(), uvsVanger::go_from_spot(), Object::ground_pressing(), uvsFlyFarmer::GrowCorn(), handle_error(), XBuffer::handleOutOfSize(), actIntDispatcher::i_init(), iCreateScreenElement(), iInitMultiGames(), PrmFile::init(), ParticleProcess::init(), XGR_Screen::init(), ParticleMapProcess::init(), ItemsDispatcher::Init(), ModelDispatcher::Init(), actIntDispatcher::init(), aciML_ItemData::init(), iScreenObject::init(), iScreen::init(), SkyFarmerList::Init(), iScreen::init_avi_border(), fncMenu::init_curItem(), iScreen::init_ids(), iScreenDispatcher::init_input_string(), actIntDispatcher::init_submenu(), InitProtoCrypt(), iScreenDispatcher::input_string_quant(), xtList< Type >::insert(), XTList< Type >::insert(), XTListAlt< Type >::insert(), iPreInitFirst(), iPutS_Str(), iQuantFirst(), ElevatorEngine::Link(), ItemGenerator::Link(), uvsEscave::link_good(), uvsSpot::link_good(), ibsObject::load(), Object::load(), ScriptFile::load(), ivrtMap::load(), vrtMap::load(), aiMessageType::Load(), iAVIElement::load(), MLFrame::load(), actIntDispatcher::load_data(), actIntDispatcher::load_ibs(), load_map_bmp(), iAVIElement::load_shape(), iBitmapElement::load_shape(), Model::loadC3D(), Model::loadC3Dvariable(), aciLocationShutterInfo::loadData(), LoadVPR(), EnterCenter::LockedCenter(), make_encode_data(), uvsVanger::makeJump(), uvsSpot::may_go_away(), Name2Int(), InputEventBuffer::next_event(), TrackType::Open(), XSocket::open(), XStream::open(), LocationEngine::Open(), CyclicEngine::Open(), DoorEngine::Open(), TiristorEngine::Open(), TrainEngine::Open(), SignPlayEngine::Open(), EnterEngine::Open(), PassageEngine::Open(), ImpulseEscave::Open(), CheckPointEngine::Open(), LandSlideEngine::Open(), ItemGenerator::Open(), NodeType::Open(), output_palette(), Parser::Parser(), ParticleMapProcess::PickUpMask(), Object::pixel_draw(), aciLocationInfo::prepare(), uvsShop::prepare_list_for_ActInt(), ScriptFile::prepare_pdata(), iScreenDispatcher::ProcessEvent(), aciML_EventSeqLine::put(), BackgroundDispatcher::put(), aciML_EventLine::put(), aciScreenEventLine::put(), actEventHeap::put(), aciML_FlushLine::put(), XMessageBuffer::put(), XQueue< Type >::put(), XIQueue< Type >::put(), actIntDispatcher::put_in_slot(), EnterCenter::PutCenter(), StorageClusterType::PutPoint(), VangerUnit::Quant(), uvsDolly::Quant(), dgAtom::read(), ScriptFile::read_src_line(), InputEventBuffer::receive(), InputEventBuffer::receive_waiting_for_event(), InfoPanel::redraw(), register_color(), RegisterIML(), vrtMap::reload(), xtList< Type >::remove(), XTList< Type >::remove(), XTListAlt< Type >::remove(), uvsWorld::remove_target(), restore_connection(), RTC(), FireBallProcess::Save(), Parser::search_name(), dgRoom::seekM(), OutputEventBuffer::send(), send_server_data(), OutputEventBuffer::send_simple_query(), Server::Server(), Object::set_body_color(), uvsVanger::set_target(), aciScreenDispatcher::SetResource(), aciScreenDispatcher::SetSequence(), SetupPath(), uvsVanger::shiftOrders(), StaticOpen(), iList::swap(), uvsVanger::thief_from_escave(), uvsVanger::thief_from_shop(), uvsVanger::thief_from_spot(), TrackUnit::TraceWay(), TrackUnit::TrackQuant(), actIntDispatcher::trade_items(), uvsVanger::UpdateAllTarget(), uvsBunch::uvsBunch(), uvsBunchCheck(), uvsCreateNetVanger(), uvsFreeDolly(), uvsMakeNewGamerInEscave(), uvsReturnWorldGamerVisit(), uvsSetItemType(), uvsVanger::uvsVanger(), uvsWorld::uvsWorld(), VLload(), XIQueue< Type >::XIQueue(), XQueue< Type >::XQueue(), xtGetRuntimeObject(), and xtInitApplication().
Exit()
void XErrorHandler::Exit (void)
 {
     exit(0);
 }
Referenced by KeyCenter().
Log()
void XErrorHandler::Log (const char * message)
 {
     log_file.open(log_name.c_str(),std::ios::out|std::ios::app);
     log_file<<message<<std::endl;
     log_file.close();
 }
References log_file, and log_name.
Referenced by SoundLoad().
RTC()
void XErrorHandler::RTC (const char * file, unsigned int line, const char * expr)
 {
     char msg[256], msg_tmp[10];
     strcpy(msg, file);
     strcat(msg,", LINE: ");
     strcat(msg, port_itoa(line,msg_tmp,10));
     strcat(msg,"\r\n");
     strcat(msg,expr);
     Abort("RTC",XERR_USER,-1,msg);
 }
References Abort(), port_itoa(), and XERR_USER.
SetPostfix()
void XErrorHandler::SetPostfix (const char * s)
 {
     postfix = s;
 }
References postfix.
SetPrefix()
void XErrorHandler::SetPrefix (const char * s)
 {
     prefix = s;
 }
References prefix.
Member Data Documentation
log_file
std::fstream XErrorHandler::log_file
Referenced by Abort(), Log(), XErrorHandler(), and ~XErrorHandler().
log_name
std::string XErrorHandler::log_name
Referenced by Abort(), Log(), and XErrorHandler().
postfix
const char* XErrorHandler::postfix
Referenced by SetPostfix().
prefix
const char* XErrorHandler::prefix
Referenced by SetPrefix().
The documentation for this struct was generated from the following files:
lib/xtool/xerrhand.h
lib/xtool/xerrhead.cpp