Vangers: FishWarrior Struct Reference
FishWarrior Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void CreateFish (Vector v, int _Speed, int Angle, int _Precision, int _Time, int _Mode, int _Model, VangerUnit *p, int Power)
void Quant (void)
void DrawQuant (void)
void Touch (GeneralObject *obj)
int test_objects_collision ()
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Attributes
int Mode
int Speed
int MaxSpeed
Vector vDelta
int Precision
int Power
int AttackTime
int Time
int zStatus
DBM RotMat
VangerUnit * TargetObject
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Detailed Description
Member Function Documentation
CreateFish()
void FishWarrior::CreateFish (Vector v, int _Speed, int Angle, int _Precision, int _Time, int _Mode, int _Model, VangerUnit * p, int Power)
 {
     MaxSpeed = Speed = _Speed;
     Precision = _Precision;
     Time = _Time;
     Mode = _Mode;
     vDelta = Vector(Speed,0,0)*DBM(Angle,Z_AXIS);
     Object::operator = (ModelD.ActiveModel(_Model));
     R_curr = v;
     cycleTor(R_curr.x,R_curr.y);
     GetVisible();
     set_active(0);
     switch_analysis(0);
     Status = 0;
     set_body_color(COLORS_IDS::BODY_RED);
     set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
     TargetObject = p;
     AttackTime = 0;
     Power = _Power;
 //  ActD.FishWarriorNum++;
 };
References ModelDispatcher::ActiveModel(), AttackTime, COLORS_IDS::BODY_RED, cycleTor(), MaxSpeed, Mode, ModelD, Object::operator=(), Power, Precision, Object::set_3D(), SET_3D_DIRECT_PLACE, Object::set_active(), Object::set_body_color(), Speed, Object::switch_analysis(), TargetObject, Time, vDelta, and Z_AXIS.
Referenced by FishWarriorList::Init().
DrawQuant()
void FishWarrior::DrawQuant (void)
 {
     draw();
 };
References Object::draw().
Init()
void FishWarrior::Init (void)
 {
     BaseObject::Init();
     ID = ID_FISH;
     zStatus = 0;
 };
References Object::ID, ID_FISH, and zStatus.
Referenced by FishWarriorList::Init().
Quant()
void FishWarrior::Quant (void)
 {
     Vector vTarget;
     int d,a,s,angle;
     VangerFunctionType* g;
     Vector v;
     GetVisible();
 //zmod 1.21
     if (NetworkON && zStatus==1)
         Visibility = UNVISIBLE;
     if(Visibility == VISIBLE){
         switch(Mode){
             case FISH_WARRIOR_PATROL:
                 if(TargetObject && TargetObject->ExternalDraw && TargetObject->draw_mode == NORMAL_DRAW_MODE && !(TargetObject->BeebonationFlag)){
                     if(AttackTime > 0){
                         vTarget = Vector(getDistX(TargetObject->R_curr.x,R_curr.x),getDistY(TargetObject->R_curr.y,R_curr.y),TargetObject->R_curr.z - R_curr.z);
                         AttackTime--;
                     }else{
                         if(!RND(15)){
                             if(!RND(4)){
                                 vTarget = Vector(BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2));
                                 Speed = RND(MaxSpeed >> 2);
                             };
                         }else{
                             AttackTime = FISH_WARRIOR_ATTACK_TIME;
                             Speed = MaxSpeed;
                         };
                     };
                 }else{
                     if(!RND(50)){
                         vTarget = Vector(BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2));
                         Speed = RND(MaxSpeed);
                     };
                     TargetObject = ActD.Active;
                 };
                 break;
             case FISH_WARRIOR_ATTACK:
                 if(TargetObject && TargetObject->ExternalDraw && TargetObject->draw_mode == NORMAL_DRAW_MODE && !(TargetObject->BeebonationFlag)) vTarget = Vector(getDistX(TargetObject->R_curr.x,R_curr.x),getDistY(TargetObject->R_curr.y,R_curr.y),TargetObject->R_curr.z - R_curr.z);
                 else{
                     TargetObject = ActD.Active;
                     if(!RND(50)){
                         vTarget = Vector(BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2));
                         Speed = RND(MaxSpeed);
                     };
                 };
                 break;
             case FISH_WARRIOR_NONE:
                 if(!RND(50)){
                     vTarget = Vector(BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2));
                     Speed = RND(MaxSpeed);
                 };
                 break;
         };
         d = vTarget.vabs();
         if(d){
             vDelta += vTarget * Precision / d;
             d = vDelta.vabs();
             if(d > Speed) vDelta = vDelta * Speed / d;
         };
         g = ActD.fTail;
         while(g){
             if(g->ID == PROTRACTOR_PALLADIUM){
                 v = Vector(getDistX(R_curr.x,g->vR.x),getDistY(R_curr.y,g->vR.y),R_curr.z - g->vR.z);
                 d = v.vabs();
                 if(d < PALLADIUM_RADIUS)
                     impulse(v,30 * (PALLADIUM_RADIUS - d) / PALLADIUM_RADIUS,0);
                 break;
             };
             g = g->Next;
         };
         analysis();
         RotMat = A_l2g*DBM(PI/2,Z_AXIS);
         angle = rPI((int)RTOG(atan2(RotMat.a[1],RotMat.a[0])));
         s = (int)V.y;
         if(Speed == s){
             if(Speed != MaxSpeed)
                 Speed = MaxSpeed;
         };
         a = rPI(vDelta.psi() - angle);
         if(a > PI) a -= 2*PI;
         d = Speed - s;
         if(a > 0){
             if(a > MECHOS_ROT_DELTA) a = MECHOS_ROT_DELTA;
         }else{
             if(a < -MECHOS_ROT_DELTA) a = -MECHOS_ROT_DELTA;
         };
         if(d > 0) controls(CONTROLS::TRACTION_INCREASE,83);
         else if(d < 0) controls(CONTROLS::TRACTION_DECREASE,83);
         controls(CONTROLS::STEER_BY_ANGLE,-a);
     };
 //zmod 1.21
     if (NetworkON) {
         if(Time-- <= 0) {
             switch (zStatus) {
                 case 0:
                     CreateDestroyEffect(R_curr,MAP_POINT_CRATER09,DT_DEFORM02,DEFORM_WATER_ONLY,EFF_EXPLOSION01,-1);
                     Time = 30;
                     zStatus = 1;
                     break;
                 case 1:
                     R_curr = Vector(RND(map_size_x),RND(map_size_y),10);
                     Time = 900 + RND(900);
                     zStatus = 0;
                     break;
                 }
         }
     }
 };
References DBM::a, Object::A_l2g, ActD, ActionDispatcher::Active, Object::analysis(), AttackTime, VangerUnit::BeebonationFlag, BMAX_TARGET_VECTOR, BMAX_TARGET_VECTOR2, Object::controls(), CreateDestroyEffect(), DEFORM_WATER_ONLY, Object::draw_mode, DT_DEFORM02, EFF_EXPLOSION01, VangerUnit::ExternalDraw, FISH_WARRIOR_ATTACK, FISH_WARRIOR_ATTACK_TIME, FISH_WARRIOR_NONE, FISH_WARRIOR_PATROL, ActionDispatcher::fTail, g, getDistX(), getDistY(), Object::impulse(), map_size_x, map_size_y, MaxSpeed, MECHOS_ROT_DELTA, Mode, NetworkON, NORMAL_DRAW_MODE, PALLADIUM_RADIUS, PI, Precision, PROTRACTOR_PALLADIUM, Vector::psi(), RND(), RotMat, rPI, RTOG, Speed, CONTROLS::STEER_BY_ANGLE, TargetObject, Time, CONTROLS::TRACTION_DECREASE, CONTROLS::TRACTION_INCREASE, UNVISIBLE, Object::V, Vector::vabs(), vDelta, VISIBLE, Object::x, Object::y, DBV::y, Z_AXIS, and zStatus.
test_objects_collision()
int FishWarrior::test_objects_collision () virtual
Reimplemented from Object.
 {
     return 0;
 };
Touch()
void FishWarrior::Touch (GeneralObject * obj)
 {
 /* //zmod. as it was
     if(p->ID == ID_VANGER) {
         if(((VangerUnit*)(p))->BeebonationFlag) return;
         ((VangerUnit*)(p))->BulletCollision(Power,NULL);
         CreateDestroyEffect(R_curr,MAP_POINT_CRATER09,DT_DEFORM02,DEFORM_WATER_ONLY,EFF_EXPLOSION01,-1);
         Status |= SOBJ_DISCONNECT;
     }
 */
     if(p->ID != ID_VANGER) return;
     if(((VangerUnit*)(p))->BeebonationFlag) return;
     ((VangerUnit*)(p))->BulletCollision(Power,NULL);
     CreateDestroyEffect(R_curr,MAP_POINT_CRATER09,DT_DEFORM02,DEFORM_WATER_ONLY,EFF_EXPLOSION01,-1);
     if (!NetworkON) {
         Status |= SOBJ_DISCONNECT;
     } else {
         Time = 30;
         zStatus = 1;
     }
 };
References CreateDestroyEffect(), DEFORM_WATER_ONLY, DT_DEFORM02, EFF_EXPLOSION01, GeneralObject::ID, ID_VANGER, NetworkON, NULL, Power, SOBJ_DISCONNECT, Time, and zStatus.
Member Data Documentation
AttackTime
int FishWarrior::AttackTime
Referenced by CreateFish(), and Quant().
MaxSpeed
int FishWarrior::MaxSpeed
Referenced by CreateFish(), and Quant().
Mode
int FishWarrior::Mode
Referenced by CreateFish(), and Quant().
Power
int FishWarrior::Power
Referenced by CreateFish(), and Touch().
Precision
int FishWarrior::Precision
Referenced by CreateFish(), and Quant().
RotMat
DBM FishWarrior::RotMat
Referenced by Quant().
Speed
int FishWarrior::Speed
Referenced by CreateFish(), and Quant().
TargetObject
VangerUnit* FishWarrior::TargetObject
Referenced by CreateFish(), and Quant().
Time
int FishWarrior::Time
Referenced by CreateFish(), Quant(), and Touch().
vDelta
Vector FishWarrior::vDelta
Referenced by CreateFish(), and Quant().
zStatus
int FishWarrior::zStatus
Referenced by Init(), Quant(), and Touch().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp