Vangers: GameObjectDispatcher Struct Reference
GameObjectDispatcher Struct Reference
#include <hobj.h>
Public Member Functions
void Init (void)
void Free (void)
void Open (void)
void Close (void)
void InitTime (void)
void ConnectBaseList (BaseObject *p)
void DisconnectBaseList (BaseObject *p)
void Quant (void)
void DrawQuant (void)
void Sort (void)
void ConnectViewList (BaseObject *p)
void ConnectNextView (BaseObject *p, BaseObject *link)
void ConnectPrevView (BaseObject *p, BaseObject *link)
void NetEvent (void)
Public Attributes
int Num
BaseObject * Tail
BaseObject * ViewTail
int GlobalTime
char FirstQuant
int cWorld
Detailed Description
Member Function Documentation
Close()
void GameObjectDispatcher::Close (void)
 {
 //  if(Num != 0  || Tail) ErrH.Abort("Bad Game Dispatcher Close");
 };
Referenced by GeneralSystemClose().
ConnectBaseList()
void GameObjectDispatcher::ConnectBaseList (BaseObject * p)
 {
     if (!Tail) {
         p->NextBaseList = p->PrevBaseList = NULL;
         Tail = p;
     } else {
         Tail -> PrevBaseList = p;
         p -> NextBaseList = Tail;
         p -> PrevBaseList = NULL;
         Tail = p;
     };
     Num++;
 };
References BaseObject::NextBaseList, NULL, Num, BaseObject::PrevBaseList, and Tail.
Referenced by UnitList::ConnectObject(), UnitBaseListType::ConnectTypeList(), EffectDispatcher::CreateDeform(), EffectDispatcher::CreateDirectParticle(), EffectDispatcher::CreateExplosion(), EffectDispatcher::CreateFireBall(), EffectDispatcher::CreateParticle(), EffectDispatcher::CreateParticleGenerator(), EffectDispatcher::CreateParticleTime(), EffectDispatcher::CreateRingOfLord(), StuffObject::CreateStuff(), StuffObject::DeviceOut(), and StuffObject::NetEvent().
ConnectNextView()
void GameObjectDispatcher::ConnectNextView (BaseObject * p, BaseObject * link)
 {
 //       if(!link) ErrH.Abort("AAAAAAA");
     p->NextViewList = link;
     p->PrevViewList = link->PrevViewList;
     if(link->PrevViewList) link->PrevViewList->NextViewList = p;
     else ViewTail = p;
     link->PrevViewList = p;
 };
References BaseObject::NextViewList, BaseObject::PrevViewList, and ViewTail.
Referenced by Sort().
ConnectPrevView()
void GameObjectDispatcher::ConnectPrevView (BaseObject * p, BaseObject * link)
 {
 //       if(!link) ErrH.Abort("AAAAAAA");
     p->PrevViewList = link;
     p->NextViewList = link->NextViewList;
     if(link->NextViewList) link->NextViewList->PrevViewList = p;
     link->NextViewList = p;
 };
References BaseObject::NextViewList, and BaseObject::PrevViewList.
Referenced by Sort().
ConnectViewList()
void GameObjectDispatcher::ConnectViewList (BaseObject * p)
 {
     if(!ViewTail){
         p->NextViewList = p->PrevViewList = NULL;
         ViewTail = p;
     }else{
         ViewTail -> PrevViewList = p;
         p -> NextViewList = ViewTail;
         p -> PrevViewList = NULL;
         ViewTail = p;
     };
 };
References BaseObject::NextViewList, NULL, BaseObject::PrevViewList, and ViewTail.
DisconnectBaseList()
void GameObjectDispatcher::DisconnectBaseList (BaseObject * p)
 {
     if ((!p->PrevBaseList) && (!p->NextBaseList)) {
         Tail = NULL;
     } else {
         if(p->PrevBaseList) {
             p->PrevBaseList->NextBaseList = p->NextBaseList;
         } else {
             Tail = p->NextBaseList;
         }
         if (p->NextBaseList) {
             p->NextBaseList->PrevBaseList = p->PrevBaseList;
         }
     };
     Num--;
 };
References BaseObject::NextBaseList, NULL, Num, BaseObject::PrevBaseList, and Tail.
Referenced by EffectDispatcher::DeleteEffect(), ItemsDispatcher::DeleteItem(), ActionDispatcher::DeleteUnit(), StuffObject::DeviceIn(), and UnitBaseListType::DisconnectTypeList().
DrawQuant()
void GameObjectDispatcher::DrawQuant (void)
{
 #ifdef _DEBUG
     if(!TotalDrawFlag) return;
 #endif
     BaseObject* p;
     p = ViewTail;
     while(p){
         p->DrawQuant();
         p = p->NextViewList;
     };
 //  ActD.CameraQuant();
     ActD.DrawResource();
     //znfo network
     if(NetworkON) {
         CreatePhantomTarget();
     }
     CreateTabutaskTarget();
     CompasObj.Quant();
 };
References ActD, CompasObj, CreatePhantomTarget(), CreateTabutaskTarget(), ActionDispatcher::DrawResource(), NetworkON, BaseObject::NextViewList, CompasObject::Quant(), TotalDrawFlag, and ViewTail.
Referenced by iGameMap::draw().
Free()
void GameObjectDispatcher::Free (void)
 {
 //  if(Num != 0 || Tail) ErrH.Abort("Bad Game Dispatcher Free");
 };
Referenced by GeneralSystemFree().
Init()
void GameObjectDispatcher::Init (void)
 {
     Num = 0;
     Tail = NULL;
     ViewTail = NULL;
 };
References NULL, Num, Tail, and ViewTail.
Referenced by GeneralSystemInit().
InitTime()
void GameObjectDispatcher::InitTime (void)
NetEvent()
void GameObjectDispatcher::NetEvent (void)
 {
     int id,type;
     //restore_connection();
     NETWORK_IN_STREAM.receive();
     while((type = NETWORK_IN_STREAM.current_event())){
         if(!(type & AUXILIARY_EVENT)){
             id = NETWORK_IN_STREAM.current_ID();
             switch(GET_NETWORK_ID(id)){
                 case NID_SHELL:
                     ActD.ShellNetEvent(type,id);
                     break;
                 case NID_GLOBAL:
                     sBunchReceive(id);
                     break;
                 case NID_VANGER:
                     ActD.NetEvent(type,id);
                     break;
                 case NID_SENSOR:
                     if(type == UPDATE_OBJECT) NetworkSetLocation(id);
                     break;
                 case NID_STUFF:
                     ItemD.NetEvent(type,id);
                     break;
                 case NID_DEVICE:
                     ItemD.NetDevice(type,id);
                     break;
                 case NID_TNT:
                     if(type == UPDATE_OBJECT) NetworkSetTnt(id);
                     break;
                 case NID_SLOT:
                     NetSlotEvent(type,id);
                     break;
                 default:
 #ifdef _DEBUG
                     fout.SetRadix(16);
                     fout < "Ignore:  Type:" <= type;
                     fout.SetRadix(10);
                     fout < "  EvID:" <= id < "  nID:" <= GET_NETWORK_ID(id) < "\n";
 #endif
                     NETWORK_IN_STREAM.ignore_event();
                     break;
             };
         };
         NETWORK_IN_STREAM.next_event();
     };
     NETWORK_OUT_STREAM.send();
 };
References ActD, AUXILIARY_EVENT, fout, GET_NETWORK_ID, ItemD, ItemsDispatcher::NetDevice(), ItemsDispatcher::NetEvent(), ActionDispatcher::NetEvent(), NetSlotEvent(), NETWORK_IN_STREAM, NETWORK_OUT_STREAM, NetworkSetLocation(), NetworkSetTnt(), NID_DEVICE, NID_GLOBAL, NID_SENSOR, NID_SHELL, NID_SLOT, NID_STUFF, NID_TNT, NID_VANGER, sBunchReceive(), XStream::SetRadix(), ActionDispatcher::ShellNetEvent(), and UPDATE_OBJECT.
Referenced by NetworkQuant().
Open()
void GameObjectDispatcher::Open (void)
 {
     ViewTail = NULL;
     Num = 0;
     Tail = NULL;
     FirstQuant = 1;
     cWorld = CurrentWorld;
 //  if(Num != 0  || Tail) ErrH.Abort("Bad Game Dispatcher Open");
 };
References CurrentWorld, cWorld, FirstQuant, NULL, Num, Tail, and ViewTail.
Referenced by GeneralSystemOpen().
Quant()
void GameObjectDispatcher::Quant (void)
 {
 //  ggg < "\nCurrentWorld\t" <= CurrentWorld;
     VangerUnit* p;
     int i;
     int time;
     if(TurnAngle == 0 && DepthShow == 0) AdvancedView = 0;
     else AdvancedView = 1;
 #ifdef _DEBUG
 //  DBGCHECK;
 #endif
     NetGlobalTime = GLOBAL_CLOCK();
     if(NetworkON)
         CheckPlayerList();
     if(FirstQuant){
         i = TELEPORT_ESCAVE_ID + 1;
         p = (VangerUnit*)(ActD.Tail);
         while(p){
             if(p->uvsPoint->shape == UVS_VANGER_SHAPE::GAMER_SLAVE){
                 aciAddTeleportMenuItem(uvsMechosType_to_AciInt(p->uvsPoint->Pmechos->type),i);
                 p->VangerCloneID = i;
                 i++;
             };
             p = (VangerUnit*)(p->NextTypeList);
         };
         if(CurrentWorld  < MAIN_WORLD_MAX - 1 && (i - TELEPORT_ESCAVE_ID - 1) <= 5) aciAddTeleportMenuItem(-1,TELEPORT_ESCAVE_ID);
         GlobalTime = GLOBAL_CLOCK();
         FirstQuant = 0;
         if(uvsKronActive){
             for(i = 0;i < MAX_ACTIVE_SLOT;i++)
                 if(ActD.Slot[i] && ActD.Slot[i]->StuffType == DEVICE_ID_GUN){
                     uvsCheckKronIventTabuTask(UVS_KRON_EVENT::WEAPON_ON,1);
                     break;
                 };
         };
     }else{
         time = GLOBAL_CLOCK();
     };
 #ifdef _DEBUG
 //  DBGCHECK;
 #endif
     if(ActD.Active)
         ActD.Active->NewKeyHandler();
     p = (VangerUnit*)(ActD.Tail);
     while(p){
         p->MapQuant();
         p = (VangerUnit*)(p->NextTypeList);
     };
     if(NetworkON && my_server_data.GameType == PASSEMBLOSS && UsedCheckNum < GloryPlaceNum)
         GloryPlaceData[UsedCheckNum].Quant();
     StaticQuant();
     MapD.Quant();
 #ifdef _DEBUG
 //  DBGCHECK;
 #endif
     ActD.Quant();
 #ifdef _DEBUG
 //  DBGCHECK;
 #endif
     ItemD.Quant();
 #ifdef _DEBUG
 //  DBGCHECK;
 #endif
     InsectD.Quant();
     FishD.Quant();
     HordeSourceD.Quant();
     HordeD.Quant();
     FarmerD.Quant();
     ClefD.Quant();
     BulletD.Quant();
     DebrisD.Quant();
     JumpD.Quant();
     EffD.Quant();
 //znfo ai quant
     aiMessageQueue.Quant();
 #ifdef _DEBUG
 //  DBGCHECK;
 #endif
     ViewTail = NULL;
     Sort();
 #ifdef _DEBUG
 //  DBGCHECK;
 #endif
 };
References aciAddTeleportMenuItem(), ActD, ActionDispatcher::Active, AdvancedView, aiMessageQueue, BulletD, CheckPlayerList(), ClefD, CurrentWorld, DebrisD, DepthShow, DEVICE_ID_GUN, EffD, FarmerD, FirstQuant, FishD, UVS_VANGER_SHAPE::GAMER_SLAVE, ServerData::GameType, GLOBAL_CLOCK, GlobalTime, GloryPlaceData, GloryPlaceNum, HordeD, HordeSourceD, InsectD, ItemD, JumpD, MAIN_WORLD_MAX, MapD, VangerUnit::MapQuant(), MAX_ACTIVE_SLOT, my_server_data, NetGlobalTime, NetworkON, VangerUnit::NewKeyHandler(), NULL, PASSEMBLOSS, uvsVanger::Pmechos, EffectDispatcher::Quant(), UnitListType::Quant(), aiMessageList::Quant(), GloryPlace::Quant(), ItemsDispatcher::Quant(), HordeSourceList::Quant(), ActionDispatcher::Quant(), InsectList::Quant(), uvsVanger::shape, ActionDispatcher::Slot, Sort(), StaticQuant(), StuffObject::StuffType, UnitList::Tail, TELEPORT_ESCAVE_ID, TurnAngle, uvsMechos::type, UsedCheckNum, uvsCheckKronIventTabuTask(), uvsKronActive, uvsMechosType_to_AciInt(), uvsKernel::uvsPoint, VangerUnit::VangerCloneID, ViewTail, and UVS_KRON_EVENT::WEAPON_ON.
Referenced by iGameMap::draw().
Sort()
void GameObjectDispatcher::Sort (void)
 {
     BaseObject* p;
     BaseObject* n;
     BaseObject* pp;
     int dx,dy,dz;
     int view_y,view_z;
     if(DepthShow){
         view_y = ViewY - round(Sin(SlopeAngle)*ViewZ);
         view_z = round(Cos(SlopeAngle)*ViewZ );
         }
     else{
         view_y = ViewY;
         view_z = ViewZ;
         }
     p = Tail;
     while(p){
         if(p->Visibility == VISIBLE){
             dx = getDistX(ViewX, p->R_curr.x);
             dy = getDistY(view_y,p->R_curr.y);
             dz = view_z - p->R_curr.z;
             p->ez = dx*dx + dy*dy + dz*abs(dz);
             if(!ViewTail){
                 p->NextViewList = p->PrevViewList = NULL;
                 ViewTail = p;
             }else{
                 pp = n = ViewTail;
                 while(n){
                     pp = n;
                     if(p->ez > n->ez) break;
 //                  if(compare(p,n)) break;
                     n = n->NextViewList;
                 };
                 if(n) ConnectNextView(p,pp);
                 else  ConnectPrevView(p,pp);
             };
         };
         p = p ->NextBaseList;
     };
 /*    int aaa = 0;
     int bbb = 0;
     p = Tail;
     while(p){
         if(p->Visibility == VISIBLE) bbb++;
         p = p->NextBaseList;
     };
     p = ViewTail;
     while(p){
         if(aaa > 1000) ErrH.Abort("Bad chain 1");
         if(p->PrevViewList && p->PrevViewList->NextViewList != p) ErrH.Abort("Bad chain 2");
         if(p->NextViewList){
             if(p->NextViewList->PrevViewList != p) ErrH.Abort("Bad chain 3");
             if(p->ez < p->NextViewList->ez) ErrH.Abort("Bad chain 4");
         };
         p = p->NextViewList;
         aaa++;
     };
     if(bbb != aaa) ErrH.Abort("Bad chain 5");*/
 };
References ConnectNextView(), ConnectPrevView(), Cos(), DepthShow, BaseObject::ez, getDistX(), getDistY(), BaseObject::NextBaseList, BaseObject::NextViewList, NULL, BaseObject::PrevViewList, GeneralObject::R_curr, round(), Sin(), SlopeAngle, Tail, ViewTail, ViewX, ViewY, ViewZ, BaseObject::Visibility, VISIBLE, Vector::x, Vector::y, and Vector::z.
Referenced by Quant().
Member Data Documentation
cWorld
int GameObjectDispatcher::cWorld
Referenced by ItemsDispatcher::Close(), ItemsDispatcher::CryptQuant(), SkyFarmerList::Init(), NetworkWorldOpen(), ItemsDispatcher::Open(), and Open().
FirstQuant
char GameObjectDispatcher::FirstQuant
Referenced by Open(), Quant(), and ActionDispatcher::SlotIn().
GlobalTime
int GameObjectDispatcher::GlobalTime
Referenced by Quant().
Num
int GameObjectDispatcher::Num
Referenced by ConnectBaseList(), DisconnectBaseList(), Init(), and Open().
Tail
BaseObject* GameObjectDispatcher::Tail
Referenced by ConnectBaseList(), DisconnectBaseList(), Init(), Open(), and Sort().
ViewTail
BaseObject* GameObjectDispatcher::ViewTail
Referenced by ConnectNextView(), ConnectViewList(), DrawQuant(), Init(), Open(), Quant(), and Sort().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp