Vangers: aiResolveList Struct Reference
aiResolveList Struct Reference
#include <mechos.h>
Public Member Functions
void ClearResolve (void)
void ClearResolve (int type, UnitOrderType obj)
void ClearResolveForce (UnitOrderType obj)
aiUnitResolve * FindResolve (int type, UnitOrderType obj)
aiUnitResolve * AddResolve (int type, UnitOrderType obj, int level=0, int status=AI_RESOLVE_STATUS_NONE)
aiUnitResolve * FastAddResolve (int type, UnitOrderType obj, int level=0, int status=AI_RESOLVE_STATUS_NONE)
Public Member Functions inherited from aiListType
void Init (void)
void Free (void)
void Connect (aiListElement *p)
void Disconnect (aiListElement *p)
Additional Inherited Members
Public Attributes inherited from aiListType
aiListElement * Tail
int Num
Detailed Description
Member Function Documentation
AddResolve()
aiUnitResolve * aiResolveList::AddResolve (int type, UnitOrderType obj, int level = 0, int status = AI_RESOLVE_STATUS_NONE)
 {
     aiUnitResolve* l;
     l = FindResolve(type,obj);
     if(l){
         l->Level += level;
         Disconnect(l);
         Connect(l);
         return l;
     };
     l = new aiUnitResolve;
     l->Type = type;
     l->Obj = obj;
     l->Time = 0;
     l->rStatus = status;
     l->Level = level;
     Connect(l);
     return l;
 };
References aiListType::Connect(), aiListType::Disconnect(), FindResolve(), level, aiUnitResolve::Level, aiUnitResolve::Obj, aiUnitResolve::rStatus, aiUnitResolve::Time, and aiUnitResolve::Type.
Referenced by VangerUnit::AddEvent(), VangerUnit::AddFindResolve(), VangerUnit::CalcAiFactor(), and VangerUnit::MainOrderInit().
ClearResolve() [1/2]
void aiResolveList::ClearResolve (int type, UnitOrderType obj)
 {
     aiUnitResolve* l;
     switch(type){
         case UNIT_ORDER_VANGER:
             l = (aiUnitResolve*)(Tail);
             while(l){
                 if(l->Obj.VangerT == obj.VangerT)
                     l->rStatus |= AI_RESOLVE_STATUS_DISCONNECT;
                 l = (aiUnitResolve*)(l->Next);
             };
             break;
         case UNIT_ORDER_STUFF:
             l = (aiUnitResolve*)(Tail);
             while(l){
                 if(l->Obj.StuffT == obj.StuffT)
                     l->rStatus |= AI_RESOLVE_STATUS_DISCONNECT;
                 l = (aiUnitResolve*)(l->Next);
             };
             break;
     };
 };
References AI_RESOLVE_STATUS_DISCONNECT, aiListElement::Next, aiUnitResolve::Obj, aiUnitResolve::rStatus, UnitOrderType::StuffT, aiListType::Tail, UNIT_ORDER_STUFF, UNIT_ORDER_VANGER, and UnitOrderType::VangerT.
ClearResolve() [2/2]
void aiResolveList::ClearResolve (void)
 {
     aiUnitResolve* l;
     l = (aiUnitResolve*)(Tail);
     while(l){
         l->rStatus |= AI_RESOLVE_STATUS_DISCONNECT;
         l = (aiUnitResolve*)(l->Next);
     };
 };
References AI_RESOLVE_STATUS_DISCONNECT, aiListElement::Next, aiUnitResolve::rStatus, and aiListType::Tail.
Referenced by VangerUnit::CalcAiFactor(), VangerUnit::ResolveGenerator(), SelectCompasTarget(), VangerUnit::StuffDestroyHandler(), and VangerUnit::VangerDestroyHandler().
ClearResolveForce()
void aiResolveList::ClearResolveForce (UnitOrderType obj)
 {
     aiUnitResolve* l;
     l = (aiUnitResolve*)(Tail);
     while(l){
         if(l->Obj.VangerT == obj.VangerT)
             l->rStatus |= AI_RESOLVE_STATUS_DISCONNECT;
         l = (aiUnitResolve*)(l->Next);
     };
 };
References AI_RESOLVE_STATUS_DISCONNECT, aiListElement::Next, aiUnitResolve::Obj, aiUnitResolve::rStatus, aiListType::Tail, and UnitOrderType::VangerT.
FastAddResolve()
aiUnitResolve * aiResolveList::FastAddResolve (int type, UnitOrderType obj, int level = 0, int status = AI_RESOLVE_STATUS_NONE)
 {
     aiUnitResolve* l;
     l = new aiUnitResolve;
     l->Type = type;
     l->Obj = obj;
     l->Time = 0;
     l->rStatus = status;
     l->Level = level;
     Connect(l);
     return l;
 };
References aiListType::Connect(), level, aiUnitResolve::Level, aiUnitResolve::Obj, aiUnitResolve::rStatus, aiUnitResolve::Time, and aiUnitResolve::Type.
FindResolve()
aiUnitResolve * aiResolveList::FindResolve (int type, UnitOrderType obj)
 {
     aiUnitResolve* l;
     l = NULL;
     switch(type){
         case UNIT_ORDER_VANGER:
             l = (aiUnitResolve*)(Tail);
             while(l){
                 if(l->Obj.VangerT == obj.VangerT)
                     break;
                 l = (aiUnitResolve*)(l->Next);
             };
             break;
         case UNIT_ORDER_STUFF:
             l = (aiUnitResolve*)(Tail);
             while(l){
                 if(l->Obj.StuffT == obj.StuffT)
                     break;
                 l = (aiUnitResolve*)(l->Next);
             };
             break;
         case UNIT_ORDER_SENSOR:
             l = (aiUnitResolve*)(Tail);
             while(l){
                 if(l->Obj.SensorT == obj.SensorT)
                     break;
                 l = (aiUnitResolve*)(l->Next);
             };
             break;
     };
     return l;
 };
References aiListElement::Next, NULL, aiUnitResolve::Obj, UnitOrderType::SensorT, UnitOrderType::StuffT, aiListType::Tail, UNIT_ORDER_SENSOR, UNIT_ORDER_STUFF, UNIT_ORDER_VANGER, and UnitOrderType::VangerT.
Referenced by AddResolve(), VangerUnit::CheckInDevice(), and VangerUnit::ResolveGenerator().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp