Vangers: ModelDispatcher Struct Reference
ModelDispatcher Struct Reference
#include <mechos.h>
Public Member Functions
void Init (Parser &in)
void Free (void)
Object & ActiveModel (char id)
int FindModel (const char *name)
Public Attributes
int MaxModel
Object * Data
char ** NameData
Detailed Description
Member Function Documentation
ActiveModel()
Object & ModelDispatcher::ActiveModel (char id)
 {
     return Data[id];
 };
References Data.
Referenced by VangerUnit::ChangeVangerProcess(), ActionUnit::CreateActionUnit(), JumpBallObject::CreateBullet(), ClefObject::CreateClef(), StuffObject::CreateDevice(), FishWarrior::CreateFish(), SkyFarmerObject::CreateSkyFarmer(), HordeSource::CreateSource(), StuffObject::CreateStuff(), VangerUnit::keyhandler(), StuffObject::NetEvent(), GunSlot::NetStuffQuant(), GunSlot::OpenGun(), VangerFunctionType::Quant(), and VangerUnit::SetMechos().
FindModel()
int ModelDispatcher::FindModel (const char * name)
 {
     int i;
     for(i = 0;i < MaxModel;i++)
         if(!strcmp(name,NameData[i]))
             return i;
     ErrH.Abort("Model Not Found",XERR_USER,0,name);
     return 0;
 };
References XErrorHandler::Abort(), ErrH, MaxModel, NameData, and XERR_USER.
Referenced by addVanger(), VangerUnit::ChangeVangerProcess(), ClefObject::CreateClef(), SkyFarmerObject::CreateSkyFarmer(), StuffObject::DeviceLoad(), HordeSourceList::Init(), FishWarriorList::Init(), InsectList::Init(), and VangerFunctionType::Quant().
Free()
void ModelDispatcher::Free (void)
 {
     int i;
     for(i = 0;i < MaxModel;i++){
         Data[i].free();
         delete[] NameData[i];
     };
     delete[] NameData;
     delete[] Data;
 };
References Data, Object::free(), MaxModel, and NameData.
Referenced by GeneralSystemFree().
Init()
void ModelDispatcher::Init (Parser & in)
 {
     int i;
     char* n;
     double max_size;
     int size;
     in.search_name("NumModel");
     MaxModel = in.get_int();
     in.search_name("MaxSize");
     max_size = in.get_double();
     Data = new Object[MaxModel];
     NameData = new char*[MaxModel];
     for(i = 0;i < MaxModel;i++){
         in.search_name("ModelNum");
         if(i != in.get_int())
             ErrH.Abort("Bad Model Num");
         in.search_name("Name");
         n = in.get_name();
         in.search_name("Size");
         size = (int)(in.get_double()*256./max_size);
         Data[i].ID = ID_VANGER;
         Data[i].load(n,size);
         in.search_name("NameID");
         n = in.get_name();
         NameData[i] = new char[strlen(n) + 1];
         strcpy(NameData[i],n);
     };
 /*
 //Test CRC
     extern double k_distance_to_force;
     if(test_block((unsigned char*)&k_distance_to_force,20))
         ErrH.Abort("test");
 */
 };
References XErrorHandler::Abort(), Data, ErrH, Parser::get_double(), Parser::get_int(), Parser::get_name(), Object::ID, ID_VANGER, Object::load(), MaxModel, NameData, and Parser::search_name().
Referenced by GeneralSystemInit().
Member Data Documentation
Data
Object* ModelDispatcher::Data
Referenced by ActiveModel(), Free(), and Init().
MaxModel
int ModelDispatcher::MaxModel
Referenced by FindModel(), Free(), Init(), and VangerUnit::keyhandler().
NameData
char** ModelDispatcher::NameData
Referenced by FindModel(), Free(), and Init().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp