Vangers: TiristorEngine Struct Reference
TiristorEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Close (void)
void Touch (GeneralObject *obj, SensorDataType *p)
void Quant (void)
void OpenDoor (void)
void CloseDoor (void)
Public Member Functions inherited from LocationEngine
virtual void Link (void)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
int NumSensor
SensorDataType ** SensorLink
int TouchFlag
int ProcessFlag
int LockFlag
int NumTouchObject
int Luck
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Close()
void TiristorEngine::Close (void) virtual
Reimplemented from LocationEngine.
 {
     delete[] SensorLink;
 };
References SensorLink.
CloseDoor()
void TiristorEngine::CloseDoor (void)
 {
     if(!Enable || !MLLink) return;
     Mode = EngineModeList::WAIT;
     ProcessFlag = 1;
     if(!MLLink->frozen){
         MLLink->goKeyPhase(DeactivePhase);
         SoundEvent();
     };
 };
References LocationEngine::DeactivePhase, LocationEngine::Enable, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, ProcessFlag, LocationEngine::SoundEvent(), and EngineModeList::WAIT.
Open()
void TiristorEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     char* n;
     int i;
     LocationEngine::Open(in);
     in.search_name("NumSensorLink");
     NumSensor = in.get_int();
     SensorLink = new SensorDataType*[NumSensor];
     for(i = 0;i < NumSensor;i++){
         in.search_name("SensorName");
         n = in.get_name();
         SensorLink[i] = NULL;
         SensorLink[i] = FindSensor(n);
         if(!SensorLink[i])
             ErrH.Abort("Bad Find Sensor");
         SensorLink[i]->Enable = 1;
         SensorLink[i]->Owner = this;
     };
     in.search_name("LockFlag");
     LockFlag = in.get_int();
     in.search_name("Luck");
     Luck = in.get_int();
     if(NetworkON) Luck = 0;
     TouchFlag = 0;
     Type = EngineTypeList::TIRISTOR;
     Mode = EngineModeList::WAIT;
     ProcessFlag = 0;
 //  MLLink->setStaticPhase(DeactivePhase);
     MLLink->goKeyPhase(DeactivePhase);
     NumTouchObject = 0;
     if(CurrentWorld == WORLD_FOSTRAL || CurrentWorld == WORLD_GLORX){
         for(i = 0;i < MAX_TIME_SECRET;i++){
             if(!strcmp(TimeSecretName[CurrentWorld][i],MLLink->name) && !TimeSecretEnable[CurrentWorld][i])
                 Enable = 0;
         };
     };
 };
References XErrorHandler::Abort(), CurrentWorld, LocationEngine::DeactivePhase, StaticObject::Enable, LocationEngine::Enable, ErrH, FindSensor(), Parser::get_int(), Parser::get_name(), MobileLocation::goKeyPhase(), LockFlag, Luck, MAX_TIME_SECRET, LocationEngine::MLLink, LocationEngine::Mode, MobileLocation::name, NetworkON, NULL, NumSensor, NumTouchObject, LocationEngine::Open(), SensorDataType::Owner, ProcessFlag, Parser::search_name(), SensorLink, TimeSecretEnable, TimeSecretName, EngineTypeList::TIRISTOR, TouchFlag, LocationEngine::Type, EngineModeList::WAIT, WORLD_FOSTRAL, and WORLD_GLORX.
OpenDoor()
void TiristorEngine::OpenDoor (void)
 {
     if(!Enable || !MLLink) return;
     Mode = EngineModeList::OPEN;
     ProcessFlag = 1;
     if(!MLLink->frozen){
         MLLink->goKeyPhase(ActivePhase);
         SoundEvent();
     };
 };
References LocationEngine::ActivePhase, LocationEngine::Enable, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, EngineModeList::OPEN, ProcessFlag, and LocationEngine::SoundEvent().
Referenced by Quant(), and VangerUnit::TouchSensor().
Quant()
void TiristorEngine::Quant (void) virtual
Reimplemented from LocationEngine.
 {
     if(!MLLink) return;
     if(!MLLink->frozen){
         NumTouchObject = TouchFlag;
         if(MLLink->isGoFinish()){
             if(NetworkON && Mode != NetMode){
                 if(UpdateFlag){
                     if(NetMode == EngineModeList::OPEN) OpenDoor();
                     UpdateFlag = 0;
                     return;
                 }else{
                     NetMode = Mode;
                     NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
                     NETWORK_OUT_STREAM < (char)(NetMode);
                     NETWORK_OUT_STREAM.end_body();
                 };
             };
             ProcessFlag = 0;
             if(TouchFlag){
                 if(Mode != EngineModeList::OPEN && !(LockFlag & DOOR_OPEN_LOCK)){
                     Mode = EngineModeList::OPEN;
                     MLLink->goKeyPhase(ActivePhase);
                     SoundEvent();
                     ProcessFlag = 1;
                 };
                 TouchFlag = 0;
             };
         };
     }else{
         if(Mode != EngineModeList::WAIT)
             MLLink->goKeyPhase(DeactivePhase);
         Mode = EngineModeList::WAIT;
         ProcessFlag = 0;
         NumTouchObject = 0;
     };
 };
References LocationEngine::ActivePhase, LocationEngine::DeactivePhase, DOOR_OPEN_LOCK, MobileLocation::frozen, MobileLocation::goKeyPhase(), MobileLocation::isGoFinish(), LockFlag, LocationEngine::MLLink, LocationEngine::Mode, LocationEngine::NetID, LocationEngine::NetMode, NETWORK_OUT_STREAM, NetworkON, NumTouchObject, EngineModeList::OPEN, OpenDoor(), ProcessFlag, LocationEngine::R_curr, LocationEngine::SoundEvent(), TouchFlag, LocationEngine::UpdateFlag, EngineModeList::WAIT, Vector::x, and Vector::y.
Touch()
void TiristorEngine::Touch (GeneralObject * obj, SensorDataType * p) virtual
Reimplemented from LocationEngine.
 {
     if(!Enable || !MLLink) return;
     if(!MLLink->frozen)
         TouchFlag++;
 };
References LocationEngine::Enable, MobileLocation::frozen, LocationEngine::MLLink, and TouchFlag.
Member Data Documentation
LockFlag
int TiristorEngine::LockFlag
Referenced by Open(), and Quant().
Luck
int TiristorEngine::Luck
Referenced by Open(), and VangerUnit::TouchSensor().
NumSensor
int TiristorEngine::NumSensor
Referenced by Open(), and VangerUnit::TouchSensor().
NumTouchObject
int TiristorEngine::NumTouchObject
Referenced by Open(), and Quant().
ProcessFlag
int TiristorEngine::ProcessFlag
Referenced by CloseDoor(), Open(), OpenDoor(), and Quant().
SensorLink
SensorDataType** TiristorEngine::SensorLink
Referenced by Close(), Open(), and VangerUnit::TouchSensor().
TouchFlag
int TiristorEngine::TouchFlag
Referenced by Open(), Quant(), and Touch().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp