Vangers: Parser Struct Reference
Parser Struct Reference
#include <parser.h>
Public Member Functions
Parser (const char *name, const char *del_chars=0)
void search_name (const char *name)
int is_next_name (const char *name)
int get_int ()
double get_double ()
double quick_get_double ()
char * get_name ()
char * get_string ()
Public Member Functions inherited from XBuffer
XBuffer (unsigned int sz=XB_DEFSIZE)
XBuffer (void *p, int sz)
~XBuffer (void)
void SetRadix (int r)
void SetDigits (int d)
void alloc (unsigned int sz)
void free (void)
void fill (char fc='\0')
void set (int off, int mode=XB_BEG)
void init (void)
int search (char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int search (const char *what, int mode=XB_FORWARD, int cs=XB_CASEON)
int end () const
unsigned int tell (void) const
unsigned int length (void) const
char * address ()
unsigned int read (void *s, unsigned int len)
unsigned int write (const void *s, unsigned int len, int bin_flag=1)
void handleOutOfSize ()
XBuffer & operator< (const char *v)
XBuffer & operator< (char v)
XBuffer & operator< (unsigned char v)
XBuffer & operator< (short v)
XBuffer & operator< (unsigned short v)
XBuffer & operator< (int v)
XBuffer & operator< (unsigned int v)
XBuffer & operator< (long v)
XBuffer & operator< (unsigned long v)
XBuffer & operator< (float v)
XBuffer & operator< (double v)
XBuffer & operator< (long double v)
XBuffer & operator> (char *v)
XBuffer & operator> (char &v)
XBuffer & operator> (unsigned char &v)
XBuffer & operator> (short &v)
XBuffer & operator> (unsigned short &v)
XBuffer & operator> (int &v)
XBuffer & operator> (unsigned int &v)
XBuffer & operator> (long &v)
XBuffer & operator> (unsigned long &v)
XBuffer & operator> (float &v)
XBuffer & operator> (double &v)
XBuffer & operator> (long double &v)
XBuffer & operator<= (char)
XBuffer & operator<= (unsigned char)
XBuffer & operator<= (short)
XBuffer & operator<= (unsigned short)
XBuffer & operator<= (int)
XBuffer & operator<= (unsigned int)
XBuffer & operator<= (long)
XBuffer & operator<= (unsigned long)
XBuffer & operator<= (long long int)
XBuffer & operator<= (float)
XBuffer & operator<= (double)
XBuffer & operator<= (long double)
XBuffer & operator>= (char &)
XBuffer & operator>= (unsigned char &)
XBuffer & operator>= (short &)
XBuffer & operator>= (unsigned short &)
XBuffer & operator>= (int &)
XBuffer & operator>= (unsigned int &)
XBuffer & operator>= (long &)
XBuffer & operator>= (unsigned long &)
XBuffer & operator>= (float &)
XBuffer & operator>= (double &)
XBuffer & operator>= (long double &)
char * GetBuf ()
char * operator() (int offs)
char * operator() (unsigned int offs)
XBuffer & operator++ ()
XBuffer & operator-- ()
XBuffer & operator+= (int v)
XBuffer & operator-= (int v)
XBuffer & operator+= (unsigned int v)
XBuffer & operator-= (unsigned int v)
char operator[] (int ind) const
char operator() () const
char & operator[] (int ind)
char & operator() ()
template<class T >
XBuffer & write (const T &v)
template<class T >
XBuffer & read (T &v)
Additional Inherited Members
Public Attributes inherited from XBuffer
char * buf
unsigned int size
unsigned int offset
int radix
int digits
int MakeFree
int automatic_realloc
Detailed Description
Constructor & Destructor Documentation
Parser()
Parser::Parser (const char * name, const char * del_chars = 0)
 : XBuffer(0,0)
 {
     int i;
     char c;
     unsigned _time_;
     XStream ff(name,XS_IN);
     long len = ff.size();
     ff > c;
     if(c) {
         ff.seek(0, XS_BEG);
         alloc(len + 1);
         ff.read(buf, len);
         buf[len] = 0;
         ff.close();
     } else {
 #ifdef _ROAD_
         ff > _time_;
         _time_ *= 6386891;
         _time_ |= 1;
         long compressed_size = len - 5;
         char* compressed_buff = new char[compressed_size];
         ff.read(compressed_buff,compressed_size);
         ff.close();
         for(i = 0;i < compressed_size;i++)
             compressed_buff[i] ^= crt(_time_);
         long decompressed_size =  *(unsigned int*)(compressed_buff + 2) + 12;//ZIP_GetExpandedSize(compressed_buff);
         alloc(decompressed_size + 1);
         //ZIP_expand(address(),decompressed_size,compressed_buff,compressed_size);
         /* ZLIB realisation (stalkerg)*/
         if(*(short*)(compressed_buff)) { //if label = 0 not compress
             //std::cout<<"Parser::Parser DeCompress "<<ff.file_name<<" file."<<std::endl;
             int stat = uncompress((Bytef*)address(),(uLongf*)&decompressed_size,(Bytef*)(compressed_buff+2+4),compressed_size-2-4);
             switch(stat){
                 //case Z_OK: std::cout<<"DeCompress ok."<<std::endl; break;
                 case Z_MEM_ERROR: std::cout<<"DeCompress not enough memory."<<std::endl; break;
                 case Z_BUF_ERROR: std::cout<<"DeCompress not enough room in the output buffer."<<std::endl; break;
                 case Z_DATA_ERROR: std::cout<<"DeCompress error data."<<std::endl; break;
             };
         } else {
             memcpy(address(),compressed_buff + 2 + 4,(unsigned)(compressed_size - 2 - 4));
         }
         delete[] compressed_buff;
         buf[decompressed_size] = 0;
 #else
         ErrH.Abort("Parser: unable to read coded file");
 #endif
     }
     if(del_chars)
         for(i = 0;i < (int)length();i++)
             if(strchr(del_chars,buf[i]))
                 buf[i] = ' ';
 }
References XErrorHandler::Abort(), XBuffer::address(), XBuffer::alloc(), XBuffer::buf, XStream::close(), crt(), ErrH, XBuffer::length(), XStream::read(), XStream::seek(), XStream::size(), XS_BEG, and XS_IN.
Member Function Documentation
get_double()
double Parser::get_double () inline
 { double t; *this >= t; return t; }
Referenced by aiFactorType::FactorLoad(), and ModelDispatcher::Init().
get_int()
int Parser::get_int () inline
 { int t; *this >= t; return t; }
Referenced by StuffObject::DeviceLoad(), GunDevice::DeviceLoad(), aiFactorType::FactorLoad(), GeneralSystemInit(), EffectDispatcher::Init(), ItemsDispatcher::Init(), ModelDispatcher::Init(), ActionDispatcher::Init(), WorldBulletTemplate::Init(), aiMessageType::Load(), UnitItemMatrix::Open(), LocationEngine::Open(), CyclicEngine::Open(), DoorEngine::Open(), TiristorEngine::Open(), TrainEngine::Open(), SignPlayEngine::Open(), EnterCenter::Open(), EscaveEngine::Open(), CheckPointEngine::Open(), LandSlideEngine::Open(), FireBallProcess::Save(), and StaticOpen().
get_name()
char * Parser::get_name ()
 {
     char c;
     unsigned int i,off;
     do{
         if(tell() >= length())
             return 0;
         *this > c;
         }while(iswspace(c));
     off = tell();
     if(c == '"')
         for(i = ++off;i < length();i++){
             if((c = buf[i]) == '"' || (iswspace(c) && c != ' ' && c != '\t')){
                 buf[i] = 0;
                 break;
                 }
             }
     else
         for(i = off;i < length();i++){
             if(iswspace(buf[i])){
                 buf[i] = 0;
                 break;
                 }
         }
     set(++i < length() ? i : length());
     return address() + off - 1;
 }
References XBuffer::address(), XBuffer::buf, XBuffer::length(), XBuffer::set(), and XBuffer::tell().
Referenced by StuffObject::DeviceLoad(), GeneralSystemInit(), GeneralSystemOpen(), EffectDispatcher::Init(), ItemsDispatcher::Init(), ModelDispatcher::Init(), WorldBulletTemplate::Init(), aiMessageType::Load(), LocationEngine::Open(), CyclicEngine::Open(), DoorEngine::Open(), TiristorEngine::Open(), TrainEngine::Open(), SignPlayEngine::Open(), EnterEngine::Open(), EnterCenter::Open(), PassageEngine::Open(), ElevatorEngine::Open(), ImpulseEscave::Open(), CheckPointEngine::Open(), LandSlideEngine::Open(), ItemGenerator::Open(), and FireBallProcess::Save().
get_string()
char * Parser::get_string ()
 {
     int i;
     char c;
     do{
         if(tell() >= length())
             return 0;
         *this > c;
         }while(iswspace(c));
     int off = tell();
     for(i = off;i < (int)length();i++){
         if(iswspace(buf[i]) && buf[i] != ' '){
             buf[i] = 0;
             break;
             }
         }
     if(++i < (int)length())
         set(i);
     return address() + off - 1;
 }
References XBuffer::address(), XBuffer::buf, XBuffer::length(), XBuffer::set(), and XBuffer::tell().
is_next_name()
int Parser::is_next_name (const char * name)
 {
     unsigned int off = tell();
     int log = 0;
     if(search(name)){
         unsigned int off1 = tell() - 1;
         for(unsigned int i = off;i < off1;i++)
             if(!iswspace(buf[i]))
                 goto ret;
         log = 1;
         }
 ret:
     set(off);
     return log;
 }
References XBuffer::buf, XBuffer::search(), XBuffer::set(), and XBuffer::tell().
quick_get_double()
double Parser::quick_get_double ()
 {
      char c,sign = 0;
      do
         *this > c;
         while(iswspace(c));
     if(c == '-'){
         sign = 1;
         *this > c;
         }
     double val = 0;
     while(iswdigit(c)){
         val  *= 10;
         val += (double)(c - '0');
         *this > c;
         }
     if(c == '.'){
         *this > c;
         double dig = 1;
         while(iswdigit(c)){
             dig  /= 10;
             val += ((double)(c - '0'))*dig;
             *this > c;
             }
         }
     return sign ? -val : val;
 }
search_name()
void Parser::search_name (const char * name)
 {
     if(!search(name))
         ErrH.Abort("Parser: Name not found", XERR_USER, 0, name);
     //(*this) + (int)(strlen(name));
     set(tell() + (int)(strlen(name)));
 }
References XErrorHandler::Abort(), ErrH, XBuffer::search(), XBuffer::set(), XBuffer::tell(), and XERR_USER.
Referenced by StuffObject::DeviceLoad(), GunDevice::DeviceLoad(), aiFactorType::FactorLoad(), GeneralSystemInit(), GeneralSystemOpen(), EffectDispatcher::Init(), ItemsDispatcher::Init(), ModelDispatcher::Init(), ActionDispatcher::Init(), WorldBulletTemplate::Init(), aiMessageType::Load(), UnitItemMatrix::Open(), LocationEngine::Open(), CyclicEngine::Open(), DoorEngine::Open(), TiristorEngine::Open(), TrainEngine::Open(), SignPlayEngine::Open(), EnterEngine::Open(), EnterCenter::Open(), PassageEngine::Open(), ElevatorEngine::Open(), EscaveEngine::Open(), ImpulseEscave::Open(), CheckPointEngine::Open(), LandSlideEngine::Open(), ItemGenerator::Open(), FireBallProcess::Save(), and StaticOpen().
The documentation for this struct was generated from the following files:
src/3d/parser.h
src/3d/3dgraph.cpp