Vangers: DangerDataType Struct Reference
DangerDataType Struct Reference
#include <sensor.h>
Public Member Functions
void CreateDanger (XStream &in)
void CreateDanger (Vector v, int r, int tp)
void Quant (void)
void FireWork (int rFactor, int Angle)
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
int Type
int Delay
int Time
int rActive
int dActive
int TabuUse
Public Attributes inherited from StaticObject
int StaticType
int radius
char Enable
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CreateDanger() [1/2]
void DangerDataType::CreateDanger (Vector v, int r, int tp)
 {
     R_curr = v;
     Type = tp;
     radius =  r;
     //zmod fixed
     //if(NetworkON) Enable = 0; //zmod 1.13
     //else Enable = 1;
     Enable = 1;
     StaticType = StaticObjectType::DANGER;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
     ID = ID_STATIC;
     switch(Type){
         case DangerTypeList::WHIRLPOOL:
         case DangerTypeList::TRAIN:
             Delay = 3;
             if(CurrentWorld == WORLD_GLORX){
                 if(!RND(1000)) Enable = 0;
             }else if(!RND(200)) Enable = 0;
             break;
         case DangerTypeList::FASTSAND:
         case DangerTypeList::SWAMP:
             dActive = 3;
             break;
     };
     Time = 0;
     rActive = radius / 2;
 };
References CurrentWorld, cycleTor(), dActive, StaticObjectType::DANGER, Delay, StaticObject::Enable, DangerTypeList::FASTSAND, GeneralObject::ID, ID_STATIC, GeneralObject::R_curr, rActive, StaticObject::radius, RND(), StaticObject::StaticType, GeneralObject::Status, DangerTypeList::SWAMP, Time, DangerTypeList::TRAIN, Type, DangerTypeList::WHIRLPOOL, WORLD_GLORX, Vector::x, and Vector::y.
CreateDanger() [2/2]
void DangerDataType::CreateDanger (XStream & in)
RND(4) means remove 1/4 in random
 {
     in > R_curr.x;
     in > R_curr.y;
     in > R_curr.z;
     in > Type;
     in > radius;
     in.seek(4*sizeof(int),XS_CUR);
     //zmod fixed
     //if(NetworkON) Enable = 1; //zmod danger
     //else Enable = 1;
     Enable = 1;
     StaticType = StaticObjectType::DANGER;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
     ID = ID_STATIC;
     switch(Type){
         case DangerTypeList::WHIRLPOOL:
         case DangerTypeList::TRAIN:
             Delay = 3;
             if(CurrentWorld == WORLD_GLORX){
                 if(!RND(1000)) Enable = 0;
             }else if(!RND(200)) Enable = 0;
             break;
         case DangerTypeList::FASTSAND:
         case DangerTypeList::SWAMP:
             dActive = 3;
             break;
 //zmod fixed 1.14
         case DangerTypeList::FIRE:
             if (NetworkON) {
 //zmod 1.21
                 if(CurrentWorld==WORLD_ARKONOY && !RND(2) && !RND(2)) Enable=0;
                 if(CurrentWorld==WORLD_THREALL && !RND(2)) Enable=0;
                 }
             break;
     };
     Time = 0;
     rActive = radius / 2;
 };
References CurrentWorld, cycleTor(), dActive, StaticObjectType::DANGER, Delay, StaticObject::Enable, DangerTypeList::FASTSAND, DangerTypeList::FIRE, GeneralObject::ID, ID_STATIC, NetworkON, GeneralObject::R_curr, rActive, StaticObject::radius, RND(), XStream::seek(), StaticObject::StaticType, GeneralObject::Status, DangerTypeList::SWAMP, Time, DangerTypeList::TRAIN, Type, DangerTypeList::WHIRLPOOL, WORLD_ARKONOY, WORLD_GLORX, WORLD_THREALL, Vector::x, XS_CUR, Vector::y, and Vector::z.
Referenced by TrainEngine::Link(), and VLload().
FireWork()
void DangerDataType::FireWork (int rFactor, int Angle)
 {
     BulletObject* p;
     Vector vCheck;
 //  FishWarrior* f;
     if(ActD.Active && RND(rFactor) < 5){
         switch(CurrentWorld){
             case WORLD_THREALL:
                 p = BulletD.CreateBullet();
                 vCheck = Vector(getDistX(ActD.Active->R_curr.x,R_curr.x),getDistY(ActD.Active->R_curr.y, R_curr.y),ActD.Active->R_curr.z - R_curr.z)*DBM((Angle >> 1) - (int)(RND(Angle)),Z_AXIS);
                 p->Owner = NULL;
 //zmod 1.21
                 if (!NetworkON) {
                     if(RND(100) < 50)
                         p->CreateBullet(Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                             Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),NULL,&GameBulletData[WD_BULLET_BIG_FIREBALL]);
                     else
                         p->CreateBullet(Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                             Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),NULL,&GameBulletData[WD_BULLET_SMALL_FIREBALL]);
                 } else {
                     if(RND(100) < 50)
                         p->CreateBullet(
                             Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                             Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),
                             NULL,
                             &GameBulletData[WD_BULLET_BIG_FIREBALL],
                             NULL,
                             -2); //decrease speed
                     else
                         p->CreateBullet(
                             Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                             Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),
                             NULL,
                             &GameBulletData[WD_BULLET_SMALL_FIREBALL],
                             NULL,
                             -2); //decrease speed
                 }
                 if(ActD.Active)
                     SOUND_THUNDER(getDistX(ActD.Active->R_curr.x,R_curr.x))
                 break;
             case WORLD_ARKONOY:
                 p = BulletD.CreateBullet();
                 vCheck = Vector(getDistX(ActD.Active->R_curr.x,R_curr.x),getDistY(ActD.Active->R_curr.y, R_curr.y),ActD.Active->R_curr.z - R_curr.z)*DBM((Angle >> 1) - (int)(RND(Angle)),Z_AXIS);
                 p->Owner = NULL;
 //zmod fixed 1.15
                 if (!NetworkON) {
                 p->CreateBullet(Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                     Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),ActD.Active,&GameBulletData[WD_BULLET_EYE_TERROR]);
                 } else {
                     p->CreateBullet(
                         Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                         Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),
                         ActD.Active,
                         &GameBulletData[WD_BULLET_EYE_TERROR],
                         NULL,
                         -3); //real speed=5 so 5-3=2
                 }
                 break;
             case WORLD_XPLO:
                 p = BulletD.CreateBullet();
                 vCheck = Vector(getDistX(ActD.Active->R_curr.x,R_curr.x),getDistY(ActD.Active->R_curr.y, R_curr.y),ActD.Active->R_curr.z - R_curr.z)*DBM((Angle >> 1) - (int)(RND(Angle)),Z_AXIS);
                 p->Owner = NULL;
                 p->CreateBullet(Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                     Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),ActD.Active,&GameBulletData[WD_BULLET_XPLORATOR]);
                 break;
             case WORLD_BOOZEENA:
                 p = BulletD.CreateBullet();
                 vCheck = Vector(getDistX(ActD.Active->R_curr.x,R_curr.x),getDistY(ActD.Active->R_curr.y, R_curr.y),ActD.Active->R_curr.z - R_curr.z)*DBM((Angle >> 1) - (int)(RND(Angle)),Z_AXIS);
                 p->Owner = NULL;
                 p->CreateBullet(Vector(R_curr.x,R_curr.y,radius + R_curr.z),
                     Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),NULL,&GameBulletData[WD_BULLET_OTHER]);
                 if(ActD.Active)
                     SOUND_THUNDER(getDistX(ActD.Active->R_curr.x,R_curr.x))
                 break;
         };
     };
 };
References ActD, ActionDispatcher::Active, BulletD, BulletObject::CreateBullet(), BulletList::CreateBullet(), CurrentWorld, GameBulletData, getDistX(), getDistY(), NetworkON, NULL, BulletObject::Owner, GeneralObject::R_curr, StaticObject::radius, RND(), SOUND_THUNDER, WD_BULLET_BIG_FIREBALL, WD_BULLET_EYE_TERROR, WD_BULLET_OTHER, WD_BULLET_SMALL_FIREBALL, WD_BULLET_XPLORATOR, WORLD_ARKONOY, WORLD_BOOZEENA, WORLD_THREALL, WORLD_XPLO, Object::x, Vector::x, XCYCL, Object::y, Vector::y, YCYCL, Vector::z, and Z_AXIS.
Referenced by Quant().
Quant()
void DangerDataType::Quant (void)
zmod
 {
     Vector vPos;
     int r,n,d1,d2,h;
     WaterParticleObject* w;
     int x,y,z,a;
     //if(NetworkON) return; //zmod fixed
     switch(Type){
         case DangerTypeList::FASTSAND:
 //#ifdef _DEBUG
 //          fDanger < "\nFastSand : " <= Enable < ";" <= R_curr.x < "," <= R_curr.y < "," <= R_curr.z;
 //#endif
             if(Enable){
                 if(rActive > radius - abs(dActive) || rActive <= abs(dActive)) dActive = -dActive;
                 rActive += dActive;
                 d1 = (radius + rActive) / (2*10);
                 d2 = (radius + rActive) / (2*2);
     //          for(i = 0;i < (int)RND(5);i++){
                     vPos = Vector(rActive - RND(2*rActive),rActive - RND(2*rActive),0);
                     vPos += R_curr;
                     vPos.x = XCYCL(vPos.x);
                     vPos.y = YCYCL(vPos.y);
                     r = d1 + RND(d1);
                     if(RND(100) < 50) h = -r;
                     else h = RND(d2) + r;
                     n = 3 + RND(3);
                     MapD.CreateLavaSpot(vPos,0,0,r,h,r,0,n,n*2,83,0,0,0,83);
     //          };
                 RadialRender(R_curr.x,R_curr.y,radius + d1 * 2);
                 if(!RND(100)) Enable = 0;
             }else{
                 if(!RND(100)) Enable = 1;
             };
             break;
         case DangerTypeList::WHIRLPOOL:
 //#ifdef _DEBUG
 //          fDanger < "\nWhirlpool : " <= Enable < ";" <= R_curr.x < "," <= R_curr.y < "," <= R_curr.z;
 //#endif
             if(Enable){
                 if(Time <= 0){
                     if(!RND(100)) Enable = 0;
                     else{
                         EffD.CreateDeform(R_curr,DEFORM_WATER_ONLY,0);
                         Time = EffD.DeformData[1].NumFrame - 1;
 //                      Time = 1 + RND(3);
                     };
                 }else{
                     Time--;
                     if(!(Time & 3)){
                         w = (WaterParticleObject*)(EffD.GetObject(EFF_PARTICLE03));
                         if(w){
                             w->CreateParticle(30,5,1 << 7,radius,10,31,5,R_curr,1);
                             EffD.ConnectObject(w);
                         };
                     };
                 };
             }else{
                 if(!RND(100)){
                     EffD.CreateDeform(R_curr,DEFORM_WATER_ONLY,0);
                     Time = EffD.DeformData[1].NumFrame - 1;
 //                  Time = 1 + RND(3);
                     Enable = 1;
                 };
             };
             break;
         case DangerTypeList::SWAMP:
 //#ifdef _DEBUG
 //          fDanger < "\nSwamp : " <= Enable < ";" <= R_curr.x < "," <= R_curr.y < "," <= R_curr.z;
 //#endif
             if(Enable){
                 if(rActive > radius - abs(dActive) || rActive <= abs(dActive)) dActive = -dActive;
                 rActive += dActive;
                 d1 = (radius + rActive) / (2*10);
                 d2 = (radius + rActive) / (2*2);
     //          for(i = 0;i < (int)RND(5);i++){
                     vPos = Vector(rActive - RND(2*rActive),rActive - RND(2*rActive),0);
                     vPos += R_curr;
                     vPos.x = XCYCL(vPos.x);
                     vPos.y = YCYCL(vPos.y);
                     r = d1 + RND(d1);
                     if(RND(100) < 50) h = -r;
                     else h = RND(d2) + r;
                     n = 3 + RND(3);
                     MapD.CreateLavaSpot(vPos,0,0,r,h,r,0,n,n*2,83,0,0,0,83);
     //          };
                 RadialRender(R_curr.x,R_curr.y,radius + d1 * 2);
                 if(!RND(100)) Enable = 0;
             }else{
                 if(!RND(100)) Enable = 1;
             };
             break;
         case DangerTypeList::FIRE:
             switch(CurrentWorld){
                 case WORLD_BOOZEENA:
                     FireWork(200,PI/4);
                     break;
                 case WORLD_THREALL:
                     if(!ActD.ThreallDestroy) FireWork(500,PI/8);
                     break;
                 case WORLD_ARKONOY:
                     FireWork(1000,PI/6);
                     break;
                 case WORLD_XPLO:
                     FireWork(800,PI / 6);
                     break;
             };
             break;
         case DangerTypeList::HOLE:
 //#ifdef _DEBUG
 //          fDanger < "\nHole : " <= Enable < ";" <= R_curr.x < "," <= R_curr.y < "," <= R_curr.z;
 //#endif
             if(Enable){
 //zmod fixed 1.15
                 if (!NetworkON) {
                 Delay = 70 + RND(30);
                 MapD.CreateMapHole(R_curr,radius,Delay,0,0);
                 } else {
                     vPos = Vector(realRND(30)-15,realRND(30)-15,0);
                     vPos += R_curr;
                     vPos.x = XCYCL(vPos.x);
                     vPos.y = YCYCL(vPos.y);
                     Delay = realRND(100);
                     MapD.CreateMapHole(vPos,(radius*0.8+realRND(radius*0.4)),Delay,0,0);
                 }
                 Enable = 0;
                 Time = 0;
                 Delay += radius*2;
             }else{
                 if(Time > Delay)
                     Enable = 1;
                 Time++;
             };
             break;
         case DangerTypeList::TRAIN:
             if(!RND(3)){
                 a = rPI(RND(PI*2));
                 r = RND(radius);
                 x = XCYCL(R_curr.x + (CO[a] * r >> 16));
                 y = YCYCL(R_curr.y + (SI[a] * r >> 16));
                 z = FloodLEVEL;
                 EffD.CreateParticleGenerator(Vector(x,y,z),Vector(R_curr.x,R_curr.y,z),Vector(5 - RND(10),5 - RND(10),0),PG_STYLE_ENTER);
             };
             break;
     };
 };
References ActD, CO, UnitList::ConnectObject(), EffectDispatcher::CreateDeform(), WaterParticleObject::CreateParticle(), EffectDispatcher::CreateParticleGenerator(), CurrentWorld, dActive, DEFORM_WATER_ONLY, EffectDispatcher::DeformData, Delay, EFF_PARTICLE03, EffD, StaticObject::Enable, DangerTypeList::FASTSAND, DangerTypeList::FIRE, FireWork(), FloodLEVEL, UnitList::GetObject(), DangerTypeList::HOLE, MapD, NetworkON, WaveProcess::NumFrame, PG_STYLE_ENTER, PI, GeneralObject::R_curr, rActive, RadialRender(), StaticObject::radius, realRND(), RND(), rPI, SI, DangerTypeList::SWAMP, ActionDispatcher::ThreallDestroy, Time, DangerTypeList::TRAIN, Type, DangerTypeList::WHIRLPOOL, WORLD_ARKONOY, WORLD_BOOZEENA, WORLD_THREALL, WORLD_XPLO, Vector::x, XCYCL, Vector::y, and YCYCL.
Member Data Documentation
dActive
int DangerDataType::dActive
Referenced by CreateDanger(), and Quant().
Delay
int DangerDataType::Delay
Referenced by CreateDanger(), and Quant().
rActive
int DangerDataType::rActive
Referenced by CreateDanger(), and Quant().
TabuUse
int DangerDataType::TabuUse
Referenced by VangerUnit::test_objects_collision().
Time
int DangerDataType::Time
Referenced by CreateDanger(), and Quant().
Type
int DangerDataType::Type
Referenced by CreateDanger(), Quant(), and VangerUnit::test_objects_collision().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp