Vangers: WaterParticleObject Struct Reference
WaterParticleObject Struct Reference
#include <effect.h>
Public Member Functions
void InitParicle (int num)
void Init (StorageType *s)
void Free (void)
void Quant (void)
void DrawQuant (void)
void CreateParticle (int _LifeTime, int _SetLifeTime, int _Velocity, int _Radius, int _FirstColor, int _SetColor, int _EndColor, const Vector &v1, int _TargetType=0)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
int NumParticle
int LifeTime
int SetLifeTime
int DeltaColor
int Time
int TargetType
Vector vCenter
int Velocity
SimpleParticleType * Data
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CreateParticle()
void WaterParticleObject::CreateParticle (int _LifeTime, int _SetLifeTime, int _Velocity, int _Radius, int _FirstColor, int _SetColor, int _EndColor, const Vector & v1, int _TargetType = 0)
 {
     int i;
     int Radius/*,SignRadius*/;
     int SignVelocity,FirstColor,DeltaColor1,SetColor;
     SimpleParticleType* p;
     Time = 0;
     LifeTime = _LifeTime;
     SetLifeTime = _SetLifeTime;
     FirstColor = _FirstColor << 8;
     SetColor = _SetColor << 8;
     DeltaColor1 = (SetColor  - FirstColor) / SetLifeTime ;
     DeltaColor = ((_EndColor << 8) - SetColor) / (LifeTime - SetLifeTime);
 //  Radius = _Radius << 8;
 //  SignRadius = Radius << 1;
     Velocity = _Velocity;
     TargetType = _TargetType;
     if(TargetType) _Velocity = 0;
     SignVelocity = _Velocity << 1;
     R_curr = v;
     radius = _Radius;
     cycleTor(R_curr.x,R_curr.y);
     Status = 0;
     MapLevel = 1;
     vCenter.x = R_curr.x << 8;
     vCenter.y = R_curr.y << 8;
     vCenter.z = R_curr.z << 8;
 /*  for(i = 0,p = Data;i < NumParticle;i++,p++){
         p->Color = FirstColor;
         p->dColor = DeltaColor1;
         p->vD = Vector(_Velocity - effectRND(SignVelocity),_Velocity - effectRND(SignVelocity),_Velocity - effectRND(SignVelocity));
         p->vR = vPos + Vector(Radius - effectRND(SignRadius),Radius - effectRND(SignRadius),Radius - effectRND(SignRadius));
     };*/
     int phi;
     int radius8 = radius << 8;
     for(i = 0,p = Data;i < NumParticle;i++,p++){
         p->Color = FirstColor;
         p->dColor = DeltaColor1;
         //phi = rPI((RND(16)*PI)>>3);
         phi = rPI(RND(2*PI));
         Radius = RND(radius8);
         //Radius = radius8 - RND(10);
         p->vR = vCenter + Vector(round(Cos(phi)*Radius),round(Sin(phi)*Radius),0);
         p->vD = Vector(_Velocity - effectRND(SignVelocity),_Velocity - effectRND(SignVelocity),_Velocity - effectRND(SignVelocity));
     };
 };
References SimpleParticleType::Color, Cos(), cycleTor(), Data, SimpleParticleType::dColor, DeltaColor, effectRND(), LifeTime, BaseObject::MapLevel, NumParticle, PI, GeneralObject::R_curr, BaseObject::radius, RND(), round(), rPI, SetLifeTime, Sin(), GeneralObject::Status, TargetType, Time, vCenter, SimpleParticleType::vD, Velocity, SimpleParticleType::vR, Vector::x, Vector::y, and Vector::z.
Referenced by VangerUnit::DrawQuant(), and DangerDataType::Quant().
DrawQuant()
void WaterParticleObject::DrawQuant (void)
 {
     int i;
     SimpleParticleType* p;
     Vector vPos;
     int tx,ty;
     if(TargetType){
         if(Time == SetLifeTime){
             if(TurnAngle){
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->QuantT(vCenter.x,vCenter.y,Velocity);
                     p->dColor = DeltaColor;
                     vPos = p->vR;
                     vPos >>= 8;
                     if(WaterAltLevel(vPos.x,vPos.y,vPos.z)){
                         G2L(vPos.x,vPos.y,tx,ty);
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             }else{
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->QuantT(vCenter.x,vCenter.y,Velocity);
                     p->dColor = DeltaColor;
                     vPos = p->vR;
                     vPos >>= 8;
                     if(WaterAltLevel(vPos.x,vPos.y,vPos.z)){
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round((p->vR.y - SPViewY) * ScaleMapInvFlt) >> 8)+ ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             };
         }else{
             if(TurnAngle){
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->QuantT(vCenter.x,vCenter.y,Velocity);
                     vPos = p->vR;
                     vPos >>= 8;
                     if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
                         G2L(vPos.x,vPos.y,tx,ty);
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             }else{
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->QuantT(vCenter.x,vCenter.y,Velocity);
                     vPos = p->vR;
                     vPos >>= 8;
                     if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round((p->vR.y - SPViewY) * ScaleMapInvFlt) >> 8)+ ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             };
         };
     }else{
         if(Time == SetLifeTime){
             if(TurnAngle){
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->Quant();
                     p->dColor = DeltaColor;
                     vPos = p->vR;
                     vPos >>= 8;
                     if(WaterAltLevel(vPos.x,vPos.y,vPos.z)){
                         G2L(vPos.x,vPos.y,tx,ty);
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             }else{
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->Quant();
                     p->dColor = DeltaColor;
                     vPos = p->vR;
                     vPos >>= 8;
                     if(WaterAltLevel(vPos.x,vPos.y,vPos.z)){
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round((p->vR.y - SPViewY) * ScaleMapInvFlt) >> 8)+ ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             };
         }else{
             if(TurnAngle){
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->Quant();
                     vPos = p->vR;
                     vPos >>= 8;
                     if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
                         G2L(vPos.x,vPos.y,tx,ty);
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             }else{
                 for(i = 0,p = Data;i < NumParticle;i++,p++){
                     p->Quant();
                     vPos = p->vR;
                     vPos >>= 8;
                     if(GetAltLevel(vPos.x,vPos.y,vPos.z)){
                         tx = ((int)round(SPGetDistX(p->vR.x,SPViewX) * ScaleMapInvFlt) >> 8) + ScreenCX;
                         ty = ((int)round((p->vR.y - SPViewY) * ScaleMapInvFlt) >> 8)+ ScreenCY;
                         if(tx > UcutLeft && tx < UcutRight && ty > VcutUp && ty < VcutDown) XGR_SetPixelFast(tx,ty,p->Color >> 8);
                     };
                 };
             };
         };
     };
 };
References SimpleParticleType::Color, Data, SimpleParticleType::dColor, DeltaColor, G2L(), GetAltLevel(), NumParticle, SimpleParticleType::Quant(), SimpleParticleType::QuantT(), round(), ScaleMapInvFlt, ScreenCX, ScreenCY, SetLifeTime, SPGetDistX(), SPViewX, SPViewY, TargetType, Time, TurnAngle, UcutLeft, vCenter, VcutDown, VcutUp, Velocity, SimpleParticleType::vR, WaterAltLevel(), Vector::x, XGR_SetPixelFast(), Vector::y, and Vector::z.
Free()
void WaterParticleObject::Free (void)
 {
     delete[] Data;
 };
References Data.
Init()
void WaterParticleObject::Init (StorageType * s)
 {
     BaseObject::Init(s);
     ID = ID_EXPLOSION;
 };
References GeneralObject::ID, and ID_EXPLOSION.
InitParicle()
void WaterParticleObject::InitParicle (int num)
 {
     NumParticle = num;
     Data = new SimpleParticleType[NumParticle];
 };
References Data, and NumParticle.
Quant()
void WaterParticleObject::Quant (void)
 {
     if(DepthShow){
         int xt = getDistX(R_curr.x,ViewX);
         int yy = getDistY(R_curr.y,ViewY);
         int zz = round(A_g2s.a[6]*xt + A_g2s.a[7]*yy) - R_curr.z + ViewZ;
         int xx = round(A_g2s.a[0]*xt + A_g2s.a[1]*yy);
         yy = round(A_g2s.a[3]*xt + A_g2s.a[4]*yy);
         if(zz < -radius || abs(xx) > zz*TurnSideX/ViewZ + radius*2 ||  abs(yy) > zz*TurnSideY/ViewZ + radius*2){
             Status |= SOBJ_DISCONNECT;
             Visibility = UNVISIBLE;
         }else Visibility = VISIBLE;
     }else{
         if(abs(getDistX(R_curr.x,ViewX)) - (radius << 1) < TurnSideX && abs(getDistY(R_curr.y,ViewY)) -  (radius << 1) < TurnSideY) Visibility = VISIBLE;
         else{
             Status |= SOBJ_DISCONNECT;
             Visibility = UNVISIBLE;
         };
     };
 //  if(z >= (1 << TOUCH_SHIFT)) VsFlag = oUNVISIBLE;
     if(Time > LifeTime) Status |= SOBJ_DISCONNECT;
     Time++;
 };
References DBM::a, A_g2s, DepthShow, getDistX(), getDistY(), LifeTime, GeneralObject::R_curr, BaseObject::radius, round(), SOBJ_DISCONNECT, GeneralObject::Status, Time, TurnSideX, TurnSideY, UNVISIBLE, ViewX, ViewY, ViewZ, BaseObject::Visibility, VISIBLE, Vector::x, Vector::y, and Vector::z.
Member Data Documentation
Data
SimpleParticleType* WaterParticleObject::Data
Referenced by CreateParticle(), DrawQuant(), Free(), and InitParicle().
DeltaColor
int WaterParticleObject::DeltaColor
Referenced by CreateParticle(), and DrawQuant().
LifeTime
int WaterParticleObject::LifeTime
Referenced by CreateParticle(), and Quant().
NumParticle
int WaterParticleObject::NumParticle
Referenced by CreateParticle(), DrawQuant(), and InitParicle().
SetLifeTime
int WaterParticleObject::SetLifeTime
Referenced by CreateParticle(), and DrawQuant().
TargetType
int WaterParticleObject::TargetType
Referenced by CreateParticle(), and DrawQuant().
Time
int WaterParticleObject::Time
Referenced by CreateParticle(), DrawQuant(), and Quant().
vCenter
Vector WaterParticleObject::vCenter
Referenced by CreateParticle(), and DrawQuant().
Velocity
int WaterParticleObject::Velocity
Referenced by CreateParticle(), and DrawQuant().
The documentation for this struct was generated from the following files:
src/units/effect.h
src/units/effect.cpp