Vangers: FireBallProcess Struct Reference
FireBallProcess Struct Reference
#include <df.h>
Public Member Functions
char CheckOut (int &f)
void Load (char *filename)
void Free (void)
void Activate (int &frame)
void Show (int x, int y, int z, int scale, int &frame)
void Show2 (int x, int y, int &frame)
void Save (char *filename)
void Convert (char *filename)
Public Attributes
int NumFrames
int x_size
int y_size
int FrameSize
int DataSize
uchar * Data
int cTable
Detailed Description
Member Function Documentation
Activate()
void FireBallProcess::Activate (int & frame) inline
 { frame = 0; };
References frame.
CheckOut()
char FireBallProcess::CheckOut (int & f)
 {
     f += FrameSize;
     if(f >= DataSize){
         f = 0;
         return 1;
     };
     return 0;
 };
References DataSize, and FrameSize.
Referenced by aWriteHelpString(), FireBallObject::DrawQuant(), BulletObject::DrawQuant(), and FireBallObject::Quant().
Convert()
void FireBallProcess::Convert (char * filename)
 {
     XStream in;
     in.open(filename,XS_OUT);
     in < NumFrames;
     in < (int)(0);
     in < x_size;
     in < y_size;
     in.write(Data,DataSize);
     in.close();
 };
References XStream::close(), Data, DataSize, NumFrames, XStream::open(), XStream::write(), x_size, XS_OUT, and y_size.
Free()
void FireBallProcess::Free (void) inline
                     {
         delete[] Data;
     };
References Data.
Load()
void FireBallProcess::Load (char * filename)
 {
 //  int i,sz,cmax;
 #ifdef FIRE_TEST
     int i,j;
     NumFrames = 256;
     cTable = 7;
     x_size = 32;
     y_size = 32;
     FrameSize = x_size * y_size;
     DataSize = NumFrames * FrameSize;
     Data = new uchar[DataSize];
     for(i = 0;i < NumFrames;i++)
         for(j = 0;j < FrameSize;j++) Data[i * FrameSize + j] = i;
 #else
     XStream in;
     in.open(filename,XS_IN);
     in > NumFrames;
     in > cTable;
     in > x_size;
     in > y_size;
     FrameSize = x_size * y_size;
     DataSize = NumFrames * FrameSize;
     Data = new uchar[DataSize];
     in.read(Data,DataSize);
     in.close();
 #endif
 /*  if(cTable){
         cmax = Data[0];
         for(i = 1;i < DataSize;i++)
             if(Data[i] > cmax) cmax = Data[i];
         for(i = 0;i < DataSize;i++)
             Data[i] = (uchar)((int)(Data[i])*255/cmax);
         sz = ENDCOLOR[cTable] - BEGCOLOR[cTable];
         for(i = 0;i < DataSize;i++)
             if(Data[i] > 0) Data[i] = (uchar)(BEGCOLOR[cTable] + (((int)(Data[i]) * sz) >> 8));
     };*/
 };
References XStream::close(), cTable, Data, DataSize, FrameSize, NumFrames, XStream::open(), XStream::read(), x_size, XS_IN, and y_size.
Referenced by EffectDispatcher::Init().
Save()
void FireBallProcess::Save (char * filename)
 {
     uchar c;
     int n;
     int i,j;
     short xs,ys;
     XStream in,out;
     Parser list(filename);
     list.search_name("BmlName");
     out.open(list.get_name(),XS_OUT);
     list.search_name("NumBmp");
     NumFrames = list.get_int();
     out < NumFrames;
     list.search_name("ColorSpace");
     n = list.get_int();
     out < (int)(n);
     for(i = 0;i < NumFrames;i++){
         list.search_name("NameBmp");
         in.open(list.get_name(),XS_IN);
         in > xs;
         in > ys;
         if(i == 0){
             x_size = xs;
             y_size = ys;
             out < x_size;
             out < y_size;
         };
         if(xs != x_size || ys != y_size) ErrH.Abort("Bad Bitmap Size");
         for(j = 0;j < x_size*y_size;j++){
             in > c;
 //          if(sz && c > 0) c = (uchar)(c1 + (((int)(c) * sz) >> 8));
 /*          if(c != 0){
                 c += 16;
                 if(c >= 255) c = 255;
             };*/
             out < c;
         };
         in.close();
     };
     out.close();
 };
References XErrorHandler::Abort(), XStream::close(), ErrH, Parser::get_int(), Parser::get_name(), NumFrames, XStream::open(), Parser::search_name(), x_size, XS_IN, XS_OUT, and y_size.
Show()
void FireBallProcess::Show (int x, int y, int z, int scale, int & frame)
 {
 /*  int dx,dy;
     int nx,ny;
     int nxs,nys;
     int i,j;
     int vadd,dadd;
     uchar* vbuf;
     uchar* dbuf;
     uchar c;
     if(y > VcutDown) return;
     if(x > UcutRight) return;
     dx = x + x_size;
     dy = y + y_size;
     nxs = x_size;
     nys = y_size;
     nx = x;
     ny = y;
     if(ny < VcutUp){
         if(dy <= VcutUp) return;
         else{
             ny = VcutUp;
             nys = dy - VcutUp;
         };
     };
     if(nx < UcutLeft){
         if(dx <= UcutLeft) return;
         else{
             nx = UcutLeft;
             nxs = dx - UcutLeft;
         };
     };
     if(dy >= VcutDown) nys = VcutDown - ny;
     if(dx >= UcutRight) nxs = UcutRight - nx;
     vadd = XGR_MAXX - nxs;
     dadd = x_size - nxs;
     vbuf = XGR_VIDEOBUF + ny * XGR_MAXX + nx;
     dbuf = Data + frame + (ny - y)*x_size + (nx - x);
     for(i = 0;i < nys;i++){
         for(j = 0;j < nxs;j++){
             c = (*dbuf);
                if(c) *vbuf =FireColorTable[(*vbuf) + (c << 8)];
             vbuf++;
             dbuf++;
         };
         vbuf += vadd;
         dbuf += dadd;
     };*/
     if(cTable)
         smart_putspr(Data + frame,x,y,x_size,y_size,x_size * scale >> 16,z,TerrainAlphaTable[cTable]);
     else
         smart_putspr(Data + frame,x,y,x_size,y_size,x_size * scale >> 16,z,FireColorTable);
 //  bitmap2screenFire((char*)(VS(_video)->_video),,x,y,x_size,y_size,x_size * scale >> 15);
 };
References cTable, Data, FireColorTable, frame, smart_putspr(), TerrainAlphaTable, x_size, and y_size.
Referenced by FireBallObject::DrawQuant(), and BulletObject::DrawQuant().
Show2()
void FireBallProcess::Show2 (int x, int y, int & frame)
 {
     int dx,dy;
     int nx,ny;
     int nxs,nys;
     int i,j;
     int vadd,dadd;
     uchar c;
     uchar* vbuf;
     uchar* dbuf;
     if(y > VcutDown) return;
     if(x > UcutRight) return;
     dx = x + x_size;
     dy = y + y_size;
     nxs = x_size;
     nys = y_size;
     nx = x;
     ny = y;
     if(ny < VcutUp){
         if(dy <= VcutUp) return;
         else{
             ny = VcutUp;
             nys = dy - VcutUp;
         };
     };
     if(nx < UcutLeft){
         if(dx <= UcutLeft) return;
         else{
             nx = UcutLeft;
             nxs = dx - UcutLeft;
         };
     };
     if(dy >= VcutDown) nys = VcutDown - ny;
     if(dx >= UcutRight) nxs = UcutRight - nx;
     vadd = XGR_MAXX - nxs;
     dadd = x_size - nxs;
     vbuf = XGR_VIDEOBUF + ny * XGR_MAXX + nx;
     dbuf = Data + frame + (ny - y)*x_size + (nx - x);
     for(i = 0;i < nys;i++){
         for(j = 0;j < nxs;j++){
                c = (*dbuf);
                if(c) *vbuf =FireColorTable[(*vbuf) + (c << 8)];
 //          if((*dbuf)) (*vbuf) = (*dbuf);
             vbuf++;
             dbuf++;
         };
         vbuf += vadd;
         dbuf += dadd;
     };
 };
References Data, FireColorTable, frame, UcutLeft, UcutRight, VcutDown, VcutUp, x_size, XGR_MAXX, XGR_VIDEOBUF, and y_size.
Referenced by aWriteHelpString().
Member Data Documentation
cTable
int FireBallProcess::cTable
Referenced by FireBallObject::CreateFireBall(), Load(), and Show().
Data
uchar* FireBallProcess::Data
Referenced by Convert(), Free(), Load(), Show(), and Show2().
DataSize
int FireBallProcess::DataSize
Referenced by CheckOut(), Convert(), and Load().
FrameSize
int FireBallProcess::FrameSize
Referenced by CheckOut(), and Load().
NumFrames
int FireBallProcess::NumFrames
Referenced by Convert(), Load(), and Save().
x_size
int FireBallProcess::x_size
Referenced by Convert(), FireBallObject::CreateFireBall(), Load(), Save(), Show(), and Show2().
y_size
int FireBallProcess::y_size
Referenced by Convert(), Load(), Save(), Show(), and Show2().
The documentation for this struct was generated from the following files:
src/particle/df.h
src/particle/df.cpp