Vangers: uvsShop Struct Reference
uvsShop Struct Reference
#include <univang.h>
Public Member Functions
uvsShop (void)
uvsShop (XStream &pfile)
~uvsShop (void)
void save (XStream &pfile)
void updateResource (void)
void updateList (listElem *)
void prepare_list_for_ActInt (uvsActInt *&Mechos, uvsActInt *&Item, int where)
void get_list_from_ActInt (uvsActInt *&Mechos, uvsActInt *&Item)
void addMechos (uvsMechos *am)
void sellMechos (uvsMechos *&am, int type=0)
int FindMechos (int)
void addItem (uvsItem *am)
void sellItem (uvsItem *&am, int &res)
Public Member Functions inherited from listElem
listElem (void)
void link (listElem *&tail)
listElem * seekName (const char *name)
virtual char * GetName (void)
Public Attributes
listElem * Pmechos
listElem * Pitem
int * Price
char * ItemHere
int locked
Public Attributes inherited from listElem
listElem * next
listElem * prev
Detailed Description
Constructor & Destructor Documentation
uvsShop() [1/2]
uvsShop::uvsShop (void) inline
 : listElem(){Pmechos = NULL; Pitem = NULL; locked  = 0; Price = NULL; ItemHere = NULL; };
References ItemHere, locked, NULL, Pitem, Pmechos, and Price.
uvsShop() [2/2]
uvsShop::uvsShop (XStream & pfile)
{
     int i;
     Pmechos = NULL;
     Pitem = NULL;
     int count = 0;
     locked = 0;
     pfile > count;
     uvsMechos *pm;
     for(i = 0; i < count; i++){
         (pm = new uvsMechos(pfile)) -> link(Pmechos);
     }
     pfile > count;
     uvsItem *pi;
     for( i = 0; i < count; i++){
         (pi = new uvsItem(pfile)) -> link(Pitem);
     }
     Price = new int[MAX_ITEM_TYPE*3];
     ItemHere = new char[MAX_ITEM_TYPE];
     memset( Price, 0, MAX_ITEM_TYPE*3*sizeof(int));
     if (uvsLoadVersion > 0){
         for( int i = 0; i < MAX_ITEM_TYPE; i++)
             pfile > Price[ MAX_ITEM_TYPE*2 + i];
     } else {
         int i;
         for( i = 0; i < MAX_ITEM_TYPE; i++)
             Price[ MAX_ITEM_TYPE*2 + i] = (RND(3) << 16) + RND(2);
         for( i = 0; i < 64; i++)
             pfile > Price[ MAX_ITEM_TYPE*2 + i];
     }
     if (uvsLoadVersion > 9){
         for( int i = 0; i < MAX_ITEM_TYPE; i++)
             pfile > ItemHere[i];
     } else {
         memset(ItemHere,(char)1, MAX_ITEM_TYPE);
     }
 }
References listElem::link(), uvsEscave::locked, MAX_ITEM_TYPE, NULL, uvsEscave::Pitem, RND(), and uvsLoadVersion.
~uvsShop()
uvsShop::~uvsShop (void)
                      {
     listElem* le;
     while( Pmechos){
         le = Pmechos;
         Pmechos = Pmechos -> next;
         delete ((uvsMechos*)le);
     }
     while( Pitem){
         le = Pitem;
         Pitem = Pitem -> next;
         delete ((uvsItem*)le);
     }
     delete[] Price;
     delete[] ItemHere;
 }
References listElem::next, and uvsEscave::Pitem.
Member Function Documentation
addItem()
void uvsShop::addItem (uvsItem * am)
{
     ((listElem*)Pi) -> link( Pitem );
 }
References listElem::link(), Pi, and Pitem.
Referenced by updateResource().
addMechos()
void uvsShop::addMechos (uvsMechos * am)
{
     ((listElem*)Pm) -> link( Pmechos );
 }
References listElem::link(), and Pmechos.
Referenced by sellMechos().
FindMechos()
int uvsShop::FindMechos (int Type)
{
     listElem *pm = Pmechos;
     while(pm){
         if (((uvsMechos*)pm) ->type == Type)
             return 1;
         pm = pm -> next;
     }
     return 0;
 }
References listElem::next, and Pmechos.
Referenced by uvsVanger::get_shop().
get_list_from_ActInt()
void uvsShop::get_list_from_ActInt (uvsActInt *& Mechos, uvsActInt *& Item)
{
     uvsActInt* pa;
     uvsItem* pl;
     int dead_world = (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE);
     //Pmechos = NULL;
     int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
     pa = Mechos;
     while(pa){
         if (Mechos -> type >= first_constr ){
             int _type = Mechos -> type - first_constr;
             Mechos -> type =  first_constr + (_type>>2);
             _type &= 3;
             uvsMechosTable[Mechos -> type] -> constractor = _type;
         }
         (new uvsMechos( Mechos -> type )) -> link( Pmechos );
         Mechos = (uvsActInt*)Mechos -> next;
         delete (uvsActInt*)pa;
         pa = Mechos;
     }
     Mechos = NULL;
     pa = Item;
     while(pa){
         int tmp_type = ActInt_to_Item( Item -> type);
         if ( uvsItemTable[ tmp_type ] -> type != UVS_ITEM_STATUS::GOODS){
             (pl = new uvsItem( tmp_type )) -> link( Pitem );
             if (pl -> type == UVS_ITEM_TYPE::CONLARVER || dead_world){
                 pl -> param1 = Item -> param1;
                 pl -> param2 = Item -> param2;
             }
         } else {
             if (tmp_type == UVS_ITEM_TYPE::ELEEPOD ||
                  tmp_type == UVS_ITEM_TYPE::BEEBOORAT ||
                  tmp_type == UVS_ITEM_TYPE::ZEEX){
                 if (Gamer -> Pescave )
                     Gamer -> Pescave -> PassagerWait = 0;
                 else
                     Gamer -> Pspot -> PassagerWait = 0;
             }//  end if
         }//  end if
         Item = (uvsActInt*)Item -> next;
         delete (uvsActInt*)pa;
         pa = Item;
     }
     Item = NULL;
     updateList(Pitem);
 }
References ActInt_to_Item(), UVS_ITEM_TYPE::BEEBOORAT, UVS_ITEM_TYPE::CONLARVER, UVS_ITEM_TYPE::ELEEPOD, Gamer, UVS_ITEM_STATUS::GOODS, listElem::link(), MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, listElem::next, NULL, Pitem, Pmechos, UVS_BUNCH_STATUS::UNABLE, updateList(), uvsItemTable, uvsMechosTable, and UVS_ITEM_TYPE::ZEEX.
prepare_list_for_ActInt()
void uvsShop::prepare_list_for_ActInt (uvsActInt *& Mechos, uvsActInt *& Item, int where)
{
     listElem* pe;
     listElem* pb;
     listElem* pn;
     listElem* pl;
     uvsActInt* pd = NULL;
     uvsBunch *pm;
     int cq, mq;
     int priceQ;
     int color = -1;
     int raffa_on = 0;
     int dead_world = (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE);
     int m_count = 0;
 #ifdef TOTAL_CASH
     aciUpdateCurCredits(799999);
 #endif
     char* lm = new char[MAX_MECHOS_TYPE];
     char* li = new char[MAX_ITEM_TYPE];
     memset( lm, 0, MAX_MECHOS_TYPE);
     memset( li, 0, MAX_ITEM_TYPE);
     pb = NULL;
     pe = Pmechos;
     if (WorldTable[ CurrentWorld ] -> escTmax){
         pm  = WorldTable[ CurrentWorld ] -> escT[0] -> Pbunch;
         color = CurrentWorld;
         cq = pm -> cycleTable[ pm -> currentStage ].cirtQ;
         mq = pm -> cycleTable[ pm -> currentStage ].cirtMAX;
         priceQ = pm -> cycleTable[ pm -> currentStage ].priceQ;
     } else {
         pm = NULL;
         cq = mq = 1;
         priceQ = 100;
     }
     while( pe ){
         m_count++;
         if ( uvsMechosTable[((uvsMechos*)pe) -> type] -> type == UVS_CAR_TYPE::RAFFA )
             raffa_on = 1;
 #ifdef _DEMO_
         if (CAR_DEMO[((uvsMechos*)pe) -> type])
 #endif
         if ( (!lm[((uvsMechos*)pe) -> type]) || dead_world){
              pn = new uvsActInt;
              int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
              if (( ((uvsMechos*)pe) -> type) >= first_constr){
                 int _type = ( ((uvsMechos*)pe) -> type) - first_constr;
                 ((uvsActInt*)pn) -> type =  first_constr + (_type<<2) + uvsMechosTable[( ((uvsMechos*)pe) -> type)] -> constractor;
                 if (uvsMechosTable[( ((uvsMechos*)pe) -> type)] -> constractor == 3)
                     ((uvsActInt*)pn) -> price = uvsMechosTable[( ((uvsMechos*)pe) -> type)] -> price;
                 else
                     ((uvsActInt*)pn) -> price = 1;
                  ((uvsActInt*)pn) -> sell_price = uvsMechosTable[( ((uvsMechos*)pe) -> type)] -> sell_price;
                  ((uvsActInt*)pn) -> param1 = color;
             } else {
                 ((uvsActInt*)pn) -> type = ( ((uvsMechos*)pe) -> type);
                  ((uvsActInt*)pn) -> price = uvsMechosTable[( ((uvsMechos*)pe) -> type)] -> price;
                  ((uvsActInt*)pn) -> sell_price = uvsMechosTable[( ((uvsMechos*)pe) -> type)] -> sell_price;
                  ((uvsActInt*)pn) -> param1 = color;
             }
             if (((uvsActInt*)pn) -> price != 1 && !NetworkON){
                  ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
                  ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
                 double t = ((double)(GamerResult.dominance+GamerResult.add_dominance))/100.0;
                 if ( t > 1.0 ) t = 1.0;
                 if ( t < -1.0 ) t = -1.0;
                  if ( t > 0.0 ){
                      double dt = ( ((uvsActInt*)pn) -> price - ((uvsActInt*)pn) -> sell_price)/2.0;
                     ((uvsActInt*)pn) -> price -= t*dt;
                     ((uvsActInt*)pn) -> sell_price +=  t*dt;
                  } else {
                      ((uvsActInt*)pn) -> price *= (1.0 - t);
                     ((uvsActInt*)pn) -> sell_price *= (1.0 + t);
                  }
                  if (((uvsActInt*)pn) -> sell_price > ((uvsActInt*)pn) -> price) ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price;
                  if (dead_world)
                      ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price = 0;
             }
 //           lm[((uvsMechos*)pe) -> type] = 1;
 #ifdef _DEMO_
              ((uvsActInt*)pn) -> param1 = CAR_COLOR[( ((uvsMechos*)pe) -> type)];
 #endif
 //          if (( ((uvsMechos*)pe) -> type) >= first_constr && dead_world){
 //              delete pn;
 //          } else
                 pn -> link(pb);
         }
          pl = pe;
          pe = pe -> next;
         if ( !lm[((uvsMechos*)pl) -> type]){
             lm[((uvsMechos*)pl) -> type] = 1;
             ((uvsMechos*)pl) -> delink(Pmechos);
             /*;if ( pl == Pmechos ) Pmechos = pe;
             if(pl -> prev -> next) pl -> prev -> next = pe;
             if(pe)
                 pe -> prev = pl -> prev;*/
             delete ((uvsMechos*)pl);
         }
     }
     if (!raffa_on && where ){
         pn = new uvsActInt;
         int _type_ = MAX_MECHOS_MAIN + RND(MAX_MECHOS_RAFFA);
         ((uvsActInt*)pn) -> type = _type_;
         ((uvsActInt*)pn) -> price = uvsMechosTable[_type_] -> price;
         ((uvsActInt*)pn) -> sell_price = uvsMechosTable[_type_] -> sell_price;
 #ifndef _DEMO_
         ((uvsActInt*)pn) -> param1 = color;
 #else
         ((uvsActInt*)pn) -> param1 = CAR_COLOR[((uvsActInt*)pn) -> type];
 #endif
         if (!NetworkON){
             ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
              ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
              double t = ((double)(GamerResult.dominance+GamerResult.add_dominance))/100.0;
              if ( t > 1.0 ) t = 1.0;
              if ( t < -1.0 ) t = -1.0;
              if ( t > 0.0){
                  double dt = (((uvsActInt*)pn) -> price - ((uvsActInt*)pn) ->sell_price)/2;
                 ((uvsActInt*)pn) -> price -= t*dt;
                 ((uvsActInt*)pn) -> sell_price +=  t*dt;
              } else {
                  ((uvsActInt*)pn) -> price *= (1.0 - t);
                 ((uvsActInt*)pn) -> sell_price *= (1.0 + t);
              }
         }//  end if
          if (((uvsActInt*)pn) -> sell_price > ((uvsActInt*)pn) -> price) ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price;
          if (dead_world)
                      ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price = 0;
         pn -> link(pb);
     }
     Mechos = (uvsActInt*)pb;
     pb = NULL;
     delete[] lm;
     pe = Pitem;
     uvsItem *ps;
     int _coef_ = RND(11);
     while( pe ){
         int item_on = 0;
 #ifndef ALL_ITEM_IN_SHOP
         if(!NetworkON && ((uvsItem*)pe)->type==UVS_ITEM_TYPE::CIRTAINER){
             item_on = 1;
             switch(Gamer -> Pworld -> gIndex){
             case 0:
                 //if (GamerResult.game_elr_result > 100)
                 if (WorldTable[0] -> escT[0] -> Pbunch -> cycleTable[1].Pgame -> all > 1)
                     item_on = 0;
                 break;
             case 1:
                 if ( GamerResult.game_ker_result >= 100)
                     item_on = 0;
                 if ( GamerResult.game_pip_result >= 100)
                     item_on = 0;
                 break;
             case 2:
                 if ( GamerResult.game_zyk_result >= 100)
                     item_on = 0;
                 break;
             };
         }
 #endif
 //      if( !( (!uvsItemTable[ ((uvsItem*)pe) -> type ] -> size && uvsItemTable[ ((uvsItem*)pe) -> type ] -> type == UVS_ITEM_STATUS::WEAPON && (((uvsItem*)pe) -> type*2 > ConTimer.hour) && (ConTimer.day == 1)) ||
 //          (uvsItemTable[ ((uvsItem*)pe) -> type ] -> type == UVS_ITEM_STATUS::DEVICE && (((uvsItem*)pe) -> type - UVS_ITEM_TYPE::COPTE_RIG + 1) > ConTimer.day) || item_on) ){
         if (!item_on){
             pn = new uvsActInt;
             ((uvsActInt*)pn) -> type = ( ((uvsItem*)pe) -> ActIntType());
             ((uvsActInt*)pn) -> price = Price[( ((uvsItem*)pe) -> type)];
             ((uvsActInt*)pn) -> param1 = ((uvsItem*)pe) -> param1;
             ((uvsActInt*)pn) -> param2 = ((uvsItem*)pe) -> param2;
             ((uvsActInt*)pn) -> sell_price = Price[( ((uvsItem*)pe) -> type) + MAX_ITEM_TYPE];
             switch( uvsItemTable[( ((uvsItem*)pe) -> type)] -> type){
             case UVS_ITEM_STATUS::DEVICE:
             case UVS_ITEM_STATUS::WEAPON:
                 if (!dead_world){
                     ((uvsActInt*)pn) -> param1 = uvsItemTable[ ((uvsItem*)pe) -> type] -> param1;
                     ((uvsActInt*)pn) -> param2 = uvsItemTable[ ((uvsItem*)pe) -> type] -> param2;
                 }
                 if ( ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::TERMINATOR || ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::TERMINATOR2){
                     ((uvsActInt*)pn) -> price *= ((uvsActInt*)pn) -> param2;
                     ((uvsActInt*)pn) -> sell_price *= ((uvsActInt*)pn) -> param2;
                 }
                 ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
                 ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
                 break;
             case UVS_ITEM_STATUS::AMMO:
                 ((uvsActInt*)pn) -> param1 = uvsItemTable[ ((uvsItem*)pe) -> type] -> param1;
                 ((uvsActInt*)pn) -> param2 = uvsItemTable[ ((uvsItem*)pe) -> type] -> param2;
                 ((uvsActInt*)pn) -> price *= ((uvsActInt*)pn) -> param2;
                 ((uvsActInt*)pn) -> sell_price *= ((uvsActInt*)pn) -> param2;
                 ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
                 ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
                 break;
             case UVS_ITEM_STATUS::ARTIFACT:
                 break;
             case UVS_ITEM_STATUS::GOODS:
                 ((uvsActInt*)pn) -> price = ((uvsActInt*)pn) -> price*( 100 + _coef_ - 5)/100;
                 ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> sell_price*( 100 + _coef_ - 5)/100;
                 break;
             case UVS_ITEM_STATUS::THING:
             case UVS_ITEM_STATUS::TREASURE:
             case UVS_ITEM_STATUS::MECHOS_PART:
                 break;
             };
             if (!NetworkON){
                 double t = ((double)(GamerResult.dominance+GamerResult.add_dominance))/100.0;
                 if ( t > 1.0 ) t = 1.0;
                 if ( t < -1.0 ) t = -1.0;
                  if ( t > 0.0){
                      double dt = (((uvsActInt*)pn) -> price - ((uvsActInt*)pn) ->sell_price)/2;
                     ((uvsActInt*)pn) -> price -= t*dt;
                     ((uvsActInt*)pn) -> sell_price +=  t*dt;
                  } else {
                      ((uvsActInt*)pn) -> price *= (1.0 - t);
                     ((uvsActInt*)pn) -> sell_price *= (1.0 + t);
                  }
                 if (((uvsActInt*)pn) -> sell_price == 0) ((uvsActInt*)pn) -> sell_price = 1;
                 if (((uvsActInt*)pn) -> price == 0) ((uvsActInt*)pn) -> price = 1;
                  if (((uvsActInt*)pn) -> sell_price > ((uvsActInt*)pn) -> price) ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price;
                  if (dead_world)
                          ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price = 0;
             }//  end if
              if ( uvsItemTable[(((uvsItem*)pe)->type)]->type != UVS_ITEM_STATUS::WEAPON || !li[((uvsItem*)pe) -> type] || dead_world ){
                  if (( ((uvsItem*)pe) -> type) != UVS_ITEM_TYPE::TERMINATOR2 && ( ((uvsItem*)pe) -> type) != UVS_ITEM_TYPE::TERMINATOR)
                     li[((uvsItem*)pe) -> type] = 1;
                 pn -> link(pb);
                 ps = (uvsItem*)pe;
                 pe = pe -> next;
                 ps -> delink(Pitem);
                 delete ps;
              } else {
                  pe = pe -> next;
                  delete pn;
              }
         }else {
             pe = pe -> next;
         }//  end if
     }//  end while
     if (pd) pd -> link(pb);
 /*  FreeList( Pitem );
     Pitem = NULL;*/
     Item = (uvsActInt*)pb;
     if (where){
         pe = Gamer -> Pescave -> Pitem;
     } else {
         pe = Gamer -> Pspot -> Pitem;
     }
     if (GTreasureItem) ErrH.Abort("uvsShop::prepare_list_for_ActInt - unresolved treasure");
     pb = NULL;
     if(pe && !((uvsItem*)pe) -> param1 && (GamerResult.luck + GamerResult.add_luck > RND(100)) ){
          pn = new uvsActInt;
          ((uvsActInt*)pn) -> type = ( ((uvsItem*)pe) -> ActIntType());
          ((uvsActInt*)pn) -> param1 = 0;
          ((uvsActInt*)pn) -> param2 = ( ((uvsItem*)pe) -> param2);
          ((uvsActInt*)pn) -> price = 1;
          ((uvsActInt*)pn) -> sell_price = 1;
          ((uvsItem*)pe) -> param1 = uvsTreasureInShop;
          pn -> link(pb);
     }
 //  if (GamerResult.rubbox_count < 2 && !where && (!strcmp(Gamer ->Pspot -> name, "Ogorod")) && (GamerResult.luck + GamerResult.add_luck > RND(30)) ){
     if ( ((GamerResult.rubbox_count < 1) || (GamerResult.rubbox_count < 2 && dgD -> bStatus >= 1)) && !where && (!strcmp(Gamer ->Pspot -> name, "Ogorod")) && (GamerResult.luck + GamerResult.add_luck > RND(30)) ){
          pn = new uvsActInt;
          ((uvsActInt*)pn) -> type = ACI_RUBOX;
          ((uvsActInt*)pn) -> param1 = uvsItemTable[UVS_ITEM_TYPE::RUBBOX] -> param1;
          ((uvsActInt*)pn) -> param2 = uvsItemTable[UVS_ITEM_TYPE::RUBBOX] -> param2;
          ((uvsActInt*)pn) -> price = 1;
          ((uvsActInt*)pn) -> sell_price = 1;
          GamerResult.rubbox_count++;
          pn -> link(pb);
     }
     GTreasureItem = (uvsActInt*)pb;
     delete[] li;
 }
References XErrorHandler::Abort(), ACI_RUBOX, aciUpdateCurCredits(), uvsGamerResult::add_dominance, uvsGamerResult::add_luck, UVS_ITEM_STATUS::AMMO, UVS_ITEM_STATUS::ARTIFACT, UVS_ITEM_TYPE::CIRTAINER, CurrentWorld, UVS_ITEM_STATUS::DEVICE, dgD, uvsGamerResult::dominance, ErrH, uvsGamerResult::game_ker_result, uvsGamerResult::game_pip_result, uvsGamerResult::game_zyk_result, Gamer, GamerResult, UVS_ITEM_STATUS::GOODS, GTreasureItem, listElem::link(), uvsGamerResult::luck, MAX_ITEM_TYPE, MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_MAIN, MAX_MECHOS_RAFFA, MAX_MECHOS_TYPE, UVS_ITEM_STATUS::MECHOS_PART, NetworkON, listElem::next, NULL, Pitem, Pmechos, Price, UVS_CAR_TYPE::RAFFA, RND(), UVS_ITEM_TYPE::RUBBOX, uvsGamerResult::rubbox_count, UVS_ITEM_TYPE::TERMINATOR, UVS_ITEM_TYPE::TERMINATOR2, UVS_ITEM_STATUS::THING, UVS_ITEM_STATUS::TREASURE, uvsItemType::type, UVS_BUNCH_STATUS::UNABLE, uvsItemTable, uvsMechosTable, uvsTreasureInShop, UVS_ITEM_STATUS::WEAPON, and WorldTable.
save()
void uvsShop::save (XStream & pfile)
{
     int i;
     int count = 0;
     listElem *pm = Pmechos;
     while(pm) {
         count++;
         pm = pm -> next;
     }
     pfile < count;
     pm = Pmechos;
     for(i = 0; i < count; i++){
         ((uvsMechos*)pm) -> save(pfile);
         pm = pm -> next;
     }
     count = 0;
     pm = Pitem;
     while(pm) {
         count++;
         pm = pm -> next;
     }
     pfile < count;
     pm = Pitem;
     for(  i = 0; i < count; i++){
         ((uvsItem*)pm) -> save(pfile);
         pm = pm -> next;
     }
     for( i = 0; i < MAX_ITEM_TYPE; i++)
         pfile < Price[ MAX_ITEM_TYPE*2 + i];
     for( i = 0; i < MAX_ITEM_TYPE; i++)
         pfile < ItemHere[i];
 }
References MAX_ITEM_TYPE, listElem::next, uvsEscave::Pitem, and uvsEscave::save().
sellItem()
void uvsShop::sellItem (uvsItem *& am, int & res)
sellMechos()
void uvsShop::sellMechos (uvsMechos *& am, int type = 0)
{
     int last_type = type;
     int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
     if ( !Pmechos ) return;
     if (!type) type = ~0;
     if (Pm) {
         addMechos(Pm);
     }
     if (last_type) {
         Pm = (uvsMechos*)Pmechos;
         while( Pm && ((Pm -> type >= first_constr) || ((Pm -> status & type) == 0))) {
             Pm = (uvsMechos*)Pm -> next;
         }
         uvsMechos*_pm_ = Pm;
         while( Pm ){
             if ((uvsMechosTable[Pm -> type]->price > uvsMechosTable[_pm_ -> type]->price) &&  (Pm -> type < first_constr))
                 _pm_ = Pm;
             Pm = (uvsMechos*)Pm -> next;
         }
         Pm = _pm_;
     } else {
         char *MechosHere = new char[first_constr];
         memset(MechosHere, 0, first_constr);
         uvsMechos*_pm_ = (uvsMechos*)Pmechos;
         while( _pm_ ){
             if (_pm_ -> type < first_constr)
                 MechosHere[_pm_ -> type] = 1;
             _pm_ = (uvsMechos*)_pm_ -> next;
         }//  end while
         int _i_ = RND(first_constr);
         while(!MechosHere[_i_])
             _i_ = RND(first_constr);
         _pm_ = (uvsMechos*)Pmechos;
         while( _pm_ ){
             if (_pm_ -> type == _i_) break;
             _pm_ = (uvsMechos*)_pm_ -> next;
         }//  end while
         delete[] MechosHere;
         Pm = _pm_;
     }
     if(Pm && (Pm -> type < first_constr)) {
         Pm -> delink(Pmechos);
         Pm -> sort();
 /*      if (((listElem*)Pm) == Pmechos ){
             Pmechos = Pmechos -> next;
             if (Pmechos)
                 Pmechos -> prev = Pm -> prev;
         } else {
             if (Pm -> next)
                 Pm -> next -> prev = Pm -> prev;
             else
                 Pmechos -> prev = Pm -> prev;
             Pm -> prev -> next = Pm -> next;
         }*/
     } else {
         Pm = (uvsMechos*)Pmechos;
         if (Pm -> type >= first_constr){
             Pm = new uvsMechos(0);
             Pm -> sort();
             return;
         } else {
             Pm -> delink(Pmechos);
             Pm -> sort();
             return;
         }
 /*      Pmechos = Pmechos -> next;
         if (Pmechos)
             Pmechos -> prev = Pm -> prev;*/
         return;
     }
 }
References addMechos(), MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, listElem::next, Pmechos, RND(), and uvsMechosTable.
updateList()
void uvsShop::updateList (listElem * pl)
{
     while(pl){
         ItemHere[((uvsItem*)pl)-> type] = 1;
         pl = pl -> next;
     }
 }
References ItemHere, and listElem::next.
Referenced by get_list_from_ActInt().
updateResource()
void uvsShop::updateResource (void)
{
     int i, j;
     uvsItem* pi;
     for( i = UVS_ITEM_TYPE::MACHOTINE_GUN_LIGHT; i <= UVS_ITEM_TYPE::CRUSTEST_CANNON; i++){
         if (  GetItem( Pitem, i, 0) == NULL  && !RND(3)  && ItemHere[i]) {
             addItem(pi = new uvsItem(i));
         }
     }
     for( i = UVS_ITEM_TYPE::TERMINATOR; i <= UVS_ITEM_TYPE::TERMINATOR2; i++){
         if (  GetItem( Pitem, i, 0) == NULL  && !RND(3) && ItemHere[i]) {
             addItem(pi = new uvsItem(i));
         }
     }
 /*  for( i = UVS_ITEM_TYPE::AMPUTATOR; i <= UVS_ITEM_TYPE::DEGRADATOR; i++){
         if (  GetItem( Pitem, i, 0) == NULL  && !RND(3) && ItemHere[i]) {
             addItem(pi = new uvsItem(i));
         }
     }*/
     for( i = UVS_ITEM_TYPE::SPEETLE_SYSTEM_AMMO0; i <= UVS_ITEM_TYPE::GLUEK; i++){
 #ifdef _DEMO_
         if (i != UVS_ITEM_TYPE::CRUSTEST_CANNON_AMMO)
 #endif
         if (  GetItem( Pitem, i, 0) == NULL )
             for( j = 0; j < 4 + RND(10); j++ ) {
                 addItem(pi = new uvsItem(i));
                 //pi -> param2 = uvsItemTable[pi -> type] -> count;
             }
     }
     if (  GetItem( Pitem, UVS_ITEM_TYPE::CIRTAINER, 0) == NULL ) addItem(new uvsItem(UVS_ITEM_TYPE::CIRTAINER));
 }
References addItem(), UVS_ITEM_TYPE::CIRTAINER, UVS_ITEM_TYPE::CRUSTEST_CANNON, UVS_ITEM_TYPE::CRUSTEST_CANNON_AMMO, GetItem(), UVS_ITEM_TYPE::GLUEK, ItemHere, UVS_ITEM_TYPE::MACHOTINE_GUN_LIGHT, NULL, Pitem, RND(), UVS_ITEM_TYPE::SPEETLE_SYSTEM_AMMO0, UVS_ITEM_TYPE::TERMINATOR, and UVS_ITEM_TYPE::TERMINATOR2.
Member Data Documentation
ItemHere
char* uvsShop::ItemHere
Referenced by updateList(), updateResource(), and uvsShop().
locked
int uvsShop::locked
Referenced by uvsShop().
Pitem
listElem* uvsShop::Pitem
Referenced by uvsEscave::add_goods_to_shop(), addItem(), get_list_from_ActInt(), prepare_list_for_ActInt(), updateResource(), and uvsShop().
Pmechos
listElem* uvsShop::Pmechos
Referenced by addMechos(), FindMechos(), get_list_from_ActInt(), prepare_list_for_ActInt(), sellMechos(), and uvsShop().
Price
int* uvsShop::Price
Referenced by prepare_list_for_ActInt(), and uvsShop().
The documentation for this struct was generated from the following files:
src/uvs/univang.h
src/uvs/univang.cpp