Vangers: uvsDolly Struct Reference
uvsDolly Struct Reference
#include <univang.h>
Public Member Functions
uvsDolly (void)
uvsDolly (uvsWorld *pw, int biosInd)
uvsDolly (XStream &)
void save (XStream &)
void setSpeed (void)
int getCirt (int x, int y)
virtual void Quant (void)
void ActiveQuant (void)
Public Member Functions inherited from uvsElement
uvsElement (void)
void elink (uvsElement *&tail)
void eunlink (uvsElement *&tail)
void delink (uvsElement *&tail)
virtual void emuQuant (void)
Public Member Functions inherited from uvsTarget
uvsTarget (void)
Public Member Functions inherited from listElem
listElem (void)
void link (listElem *&tail)
listElem * seekName (const char *name)
virtual char * GetName (void)
Public Attributes
uvsWorld * Pworld
int gIndex
int biosNindex
int x_speed
int y_speed
int status
int tail_x [DOLLY_TAIL_LEN]
int tail_y [DOLLY_TAIL_LEN]
int tail_cInd
int tail_counter
Public Attributes inherited from uvsElement
uvsElement * enext
uvsElement * eprev
UvsObjectType type
Public Attributes inherited from uvsTarget
int pos_x
int pos_y
Public Attributes inherited from listElem
listElem * next
listElem * prev
Detailed Description
Constructor & Destructor Documentation
uvsDolly() [1/3]
uvsDolly::uvsDolly (void) inline
                   : uvsElement(), uvsTarget(), listElem() {
         Pworld = NULL;
         gIndex = biosNindex = x_speed = y_speed = 0;
         status = 0;
         memset(tail_x, -1, sizeof(tail_x));
         memset(tail_y, -1, sizeof(tail_y));
     }
References biosNindex, gIndex, NULL, Pworld, status, tail_x, tail_y, x_speed, and y_speed.
uvsDolly() [2/3]
uvsDolly::uvsDolly (uvsWorld * pw, int biosInd)
{
     biosNindex = biosInd;
     gIndex = DollyIndex++;
     Pworld = pw;
     type = UVS_OBJECT::DOLLY;
     pos_x = RND(pw -> x_size);
     pos_y = RND(pw -> y_size);
     status = 0;
     setSpeed();
     tail_cInd = tail_counter = 0;
     memset(tail_x, -1, sizeof(tail_x));
     memset(tail_y, -1, sizeof(tail_y));
     elink(ETail);
 }
References biosNindex, and gIndex.
uvsDolly() [3/3]
uvsDolly::uvsDolly (XStream & pfile)
{
     int cw;
     pfile > biosNindex;
     pfile > gIndex;
     pfile > cw;
     Pworld = WorldTable[cw];
     type = UVS_OBJECT::DOLLY;
     pfile > pos_x;
     pfile > pos_y;
     pfile > status;
     setSpeed();
     tail_cInd = tail_counter = 0;
     memset(tail_x, -1, sizeof(tail_x));
     memset(tail_y, -1, sizeof(tail_y));
     elink(ETail);
 }
References biosNindex, UVS_OBJECT::DOLLY, uvsElement::elink(), ETail, gIndex, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, setSpeed(), status, tail_cInd, tail_counter, tail_x, tail_y, uvsElement::type, and WorldTable.
Member Function Documentation
ActiveQuant()
void uvsDolly::ActiveQuant (void)
 {
     BaseObject* p;
     StuffObject* n;
     int dm,d;
     Vector vCheck;
     pos_x = (pos_x + x_speed) & (Pworld -> x_size - 1);
     pos_y = (pos_y + y_speed) & (Pworld -> y_size - 1);
     dm = -1;
     n = NULL;
     p = (BaseObject*)(ItemD.Tail);
     while(p){
         if(p->ID == ID_STUFF && ((StuffObject*)(p))->ActIntBuffer.type == ACI_EMPTY_CONLARVER && ((StuffObject*)(p))->FindDolly){
             vCheck = Vector(getDistX(p->R_curr.x,pos_x),getDistY(p->R_curr.y,pos_y),0);
             d = vCheck.vabs();
             if(d < dm || dm == -1){
                 dm = d;
                 n = (StuffObject*)p;
             };
         };
         p = (BaseObject*)(p->NextTypeList);
     };
     if(n && dm < 80){
         vCheck = Vector(getDistX(n->R_curr.x,pos_x),getDistY(n->R_curr.y,pos_y),0);
         vCheck = 2*vCheck * V_SPEED_DOLLY / dm;
         if(dm < n->radius*2){
             n->ActIntBuffer.data0 = uvsCatchDolly(this);
             n->ActIntBuffer.type = ACI_CONLARVER;
             n->set_body_color(COLORS_IDS::YELLOW_CHARGED);
             if(n->LightData){
                 n->LightData->Destroy();
                 n->LightData = NULL;
             };
         };
         x_speed = vCheck.x;
         y_speed = vCheck.y;
 /*      p = (BaseObject*)(ActD.Tail);
         while(p){
             if(p->ID == ID_VANGER)
                 ((VangerUnit*)(p))->UpdateMainOrder = 1;
             p = (BaseObject*)(p->NextTypeList);
         };*/
     }else{
         if(!RND(128)) setSpeed();
     };
     if(!tail_counter){
         tail_x[tail_cInd] = pos_x;
         tail_y[tail_cInd] = pos_y;
         tail_cInd = (tail_cInd + 1)%DOLLY_TAIL_LEN;
         tail_counter++;
         }
     else if(++tail_counter == DOLLY_TAIL_PERIOD) tail_counter = 0;
 };
References ACI_CONLARVER, ACI_EMPTY_CONLARVER, StuffObject::ActIntBuffer, actintItemData::data0, LightPoint::Destroy(), DOLLY_TAIL_LEN, DOLLY_TAIL_PERIOD, getDistX(), getDistY(), GeneralObject::ID, ID_STUFF, ItemD, StuffObject::LightData, GeneralObject::NextTypeList, NULL, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, GeneralObject::R_curr, RND(), Object::set_body_color(), setSpeed(), UnitList::Tail, tail_cInd, tail_counter, tail_x, tail_y, actintItemData::type, uvsCatchDolly(), V_SPEED_DOLLY, Vector::vabs(), Object::x, Vector::x, x_speed, Object::y, Vector::y, y_speed, and COLORS_IDS::YELLOW_CHARGED.
Referenced by Quant().
getCirt()
int uvsDolly::getCirt (int x, int y)
{
     int i;
     int Range = 32000;
     int RangeL;
     int tmp;
     if (status) return 0;
 #ifdef STAND_REPORT
     stand < "dolly  index"<= gIndex  < "\n";
     stand < "dolly  bois"<= biosNindex  < "\n\n";
 #endif
     for( i = 0; i < DOLLY_TAIL_LEN; i++){
         RangeL = int(sqrt( double((tail_x[i] - x)*(tail_x[i] - x) + (tail_y[i] - y)*(tail_y[i] - y))));
         if ( RangeL < Range ) {
             Range = RangeL;
         }
     }
     if ( Range >= V_CIRT_R)     //  4096
         tmp = 0;
     else if ( Range >= V_CIRT_R/2)  // 2048
         tmp = 1;
     else if ( Range >= V_CIRT_R/4)  //  1024
         tmp = 2;
     else if ( Range >= V_CIRT_R/6)  // 700
         tmp = 3;
     else if ( Range >= V_CIRT_R/8) //  512
         tmp = 4;
     else if ( Range >= V_CIRT_R/16) // 256
         tmp = 5;
     else if ( Range >= V_CIRT_R/40) // 100
         tmp = 6;
     else
         tmp = 7;
     return (tmp << (gIndex*3));
 }
References DOLLY_TAIL_LEN, and V_CIRT_R.
Quant()
void uvsDolly::Quant (void) virtual
Reimplemented from uvsElement.
{
     if (status == UVS_DOLLY_STATUS::UNABLE || status == UVS_DOLLY_STATUS::CATCH) return;
     if (status) ErrH.Abort("uvsDolly::DAST IN MEMORY...");
     if ((Pworld->gIndex == CurrentWorld) && uvsKronActive) {
         ActiveQuant();
     } else {
         pos_x = (pos_x + x_speed) & (Pworld -> x_size - 1);
         pos_y = (pos_y + y_speed) & (Pworld -> y_size - 1);
         if(!tail_counter){
             tail_x[tail_cInd] = pos_x;
             tail_y[tail_cInd] = pos_y;
             tail_cInd = (tail_cInd + 1)%DOLLY_TAIL_LEN;
             tail_counter++;
             }
         else if(++tail_counter == DOLLY_TAIL_PERIOD) tail_counter = 0;
         if(!RND(128)) setSpeed();
     }
 }
References XErrorHandler::Abort(), ActiveQuant(), UVS_DOLLY_STATUS::CATCH, CurrentWorld, DOLLY_TAIL_LEN, DOLLY_TAIL_PERIOD, ErrH, uvsWorld::gIndex, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, RND(), setSpeed(), status, tail_cInd, tail_counter, tail_x, tail_y, UVS_DOLLY_STATUS::UNABLE, uvsKronActive, x_speed, and y_speed.
save()
void uvsDolly::save (XStream & pfile)
{
     pfile < biosNindex;
     pfile < gIndex;
     pfile < Pworld -> gIndex;
     pfile < pos_x;
     pfile < pos_y;
     pfile < status;
 }
References biosNindex, gIndex, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, and status.
setSpeed()
void uvsDolly::setSpeed (void)
{
     x_speed = y_speed = 0;
 //#ifdef ZMOD_BETA
 //  //znfo - dolly motion
 //  if (!NetworkON) {
 //      while(!x_speed && !y_speed){
 //          x_speed = V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1);
 //          y_speed = V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1);
 //      }
 //  } else {
 //      while(!x_speed && !y_speed){
 //          x_speed = V_SPEED_DOLLY - NetRnd.Get(V_SPEED_DOLLY*2+1);
 //          y_speed = V_SPEED_DOLLY - NetRnd.Get(V_SPEED_DOLLY*2+1);
 //      }
 //  }
 //#else
     while(!x_speed && !y_speed){
         x_speed = V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1);
         y_speed = V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1);
         }
 //#endif
 }
References RND(), V_SPEED_DOLLY, x_speed, and y_speed.
Referenced by ActiveQuant(), Quant(), and uvsDolly().
Member Data Documentation
biosNindex
int uvsDolly::biosNindex
Referenced by VangerUnit::CalcAiFactor(), getObjectPosition(), save(), and uvsDolly().
gIndex
int uvsDolly::gIndex
Referenced by VangerUnit::CalcAiFactor(), save(), and uvsDolly().
Pworld
uvsWorld* uvsDolly::Pworld
Referenced by ActiveQuant(), VangerUnit::CalcAiFactor(), getObjectPosition(), Quant(), save(), and uvsDolly().
status
int uvsDolly::status
Referenced by getObjectPosition(), Quant(), save(), and uvsDolly().
tail_cInd
int uvsDolly::tail_cInd
Referenced by ActiveQuant(), Quant(), and uvsDolly().
tail_counter
int uvsDolly::tail_counter
Referenced by ActiveQuant(), Quant(), and uvsDolly().
tail_x
int uvsDolly::tail_x[DOLLY_TAIL_LEN]
Referenced by ActiveQuant(), Quant(), and uvsDolly().
tail_y
int uvsDolly::tail_y[DOLLY_TAIL_LEN]
Referenced by ActiveQuant(), Quant(), and uvsDolly().
x_speed
int uvsDolly::x_speed
Referenced by ActiveQuant(), Quant(), setSpeed(), and uvsDolly().
y_speed
int uvsDolly::y_speed
Referenced by ActiveQuant(), Quant(), setSpeed(), and uvsDolly().
The documentation for this struct was generated from the following files:
src/uvs/univang.h
src/units/mechos.cpp
src/uvs/univang.cpp