Vangers: UnitListType Struct Reference
UnitListType Struct Reference
#include <hobj.h>
Public Member Functions
virtual void Init (void)
virtual void Free (void)
virtual void Quant (void)
virtual void NetEvent (int type, int id)
virtual void FreeUnit (GeneralObject *p)
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Public Attributes
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
ClearNet()
void UnitListType::ClearNet (void)
ConnectTypeList()
void UnitListType::ConnectTypeList (GeneralObject * p) virtual
Reimplemented in UnitBaseListType.
 {
     if(!Tail){
         p -> NextTypeList = p -> PrevTypeList = NULL;
         Tail = p;
     }else{
         Tail -> PrevTypeList = p;
         p -> NextTypeList = Tail;
         p -> PrevTypeList = NULL;
         Tail = p;
     };
     Num++;
 };
References NULL, Num, and Tail.
DisconnectTypeList()
void UnitListType::DisconnectTypeList (GeneralObject * p) virtual
Reimplemented in UnitBaseListType.
 {
     if((!p->PrevTypeList) && (!p->NextTypeList)) Tail = NULL;
     else{
         if(p->PrevTypeList) p->PrevTypeList->NextTypeList = p->NextTypeList;
         else Tail = p->NextTypeList;
         if(p->NextTypeList) p->NextTypeList->PrevTypeList = p->PrevTypeList;
     };
     Num--;
 };
References GeneralObject::NextTypeList, NULL, Num, GeneralObject::PrevTypeList, and Tail.
Referenced by FreeUnit().
Free()
void UnitListType::Free (void) virtual
Reimplemented in InsectList, FishWarriorList, SkyFarmerList, and ClefList.
 {
     GeneralObject* p;
     GeneralObject* pp;
     p = Tail;
     while(p){
         pp = p->NextTypeList;
         FreeUnit(p);
         p = pp;
     };
 };
References FreeUnit(), GeneralObject::NextTypeList, and Tail.
Referenced by ClefList::Free(), FishWarriorList::Free(), InsectList::Free(), and GeneralSystemClose().
FreeUnit()
void UnitListType::FreeUnit (GeneralObject * p) virtual
Reimplemented in InsectList, FishWarriorList, ClefList, and BulletList.
 {
     DisconnectTypeList(p);
     delete p;
 };
References DisconnectTypeList().
Referenced by Free(), SkyFarmerList::Free(), Quant(), and HordeSourceList::Quant().
GetNetObject()
GeneralObject * UnitListType::GetNetObject (int id)
 {
     GeneralObject* p;
     p = Tail;
     while(p){
         if(p->NetID == id)
             return p;
         p = p->NextTypeList;
     };
     return NULL;
 };
References GeneralObject::NetID, GeneralObject::NextTypeList, NULL, and Tail.
Init()
void UnitListType::Init (void) virtual
Reimplemented in InsectList, FishWarriorList, HordeSourceList, HordeList, SkyFarmerList, and ClefList.
 {
     Num = 0;
     Tail = NULL;
 };
References NULL, Num, and Tail.
Referenced by GeneralSystemOpen(), SkyFarmerList::Init(), and HordeSourceList::Init().
NetEvent()
void UnitListType::NetEvent (int type, int id) virtual
 {
 };
Quant()
void UnitListType::Quant (void) virtual
Reimplemented in InsectList, and HordeSourceList.
 {
     GeneralObject* p;
     GeneralObject* pp;
     p = Tail;
     while(p){
         p->Quant();
         p = p->NextTypeList;
     };
     p = Tail;
     while(p){
         pp = p->NextTypeList;
         if(p->Status & SOBJ_DISCONNECT)
             FreeUnit(p);
         p = pp;
     };
 };
References FreeUnit(), GeneralObject::NextTypeList, SOBJ_DISCONNECT, GeneralObject::Status, and Tail.
Referenced by GameObjectDispatcher::Quant().
Member Data Documentation
Num
int UnitListType::Num
Referenced by ConnectTypeList(), UnitBaseListType::ConnectTypeList(), DisconnectTypeList(), UnitBaseListType::DisconnectTypeList(), Init(), and VangerUnit::ResolveGenerator().
Tail
GeneralObject* UnitListType::Tail
Referenced by BunchEvent(), ConnectTypeList(), UnitBaseListType::ConnectTypeList(), DisconnectTypeList(), UnitBaseListType::DisconnectTypeList(), Free(), SkyFarmerList::Free(), GetNetObject(), Init(), InsectUnit::InitEnvironment(), Quant(), HordeSourceList::Quant(), InsectList::Quant(), HordeSource::test_objects_collision(), ClefObject::test_objects_collision(), and VangerUnit::test_objects_collision().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp