Vangers: StorageType Struct Reference
StorageType Struct Reference
#include <hobj.h>
Public Member Functions
void Init (int _max=100)
void Free (void)
GeneralObject * Active (void)
void Deactive (GeneralObject *p)
GeneralObject * GetAll (void)
void Check (void)
!!!!!!!!!!!
Public Attributes
int Max
int ObjectPointer
GeneralObject ** Data
Detailed Description
Member Function Documentation
Active()
GeneralObject * StorageType::Active (void)
 {
 /*  int i;
     for(i = 0;i < ObjectPointer - 1;i++)
         if(Data[i] == Data[ObjectPointer - 1])
             ErrH.Abort("Bad Object Storage");*/
     if(ObjectPointer > 0) return Data[--ObjectPointer];
     else
 #ifdef STACK_EMPTY_IGNORE
         return NULL;
 #else
         ErrH.Abort("Object stack empty");
 #endif
 };
References XErrorHandler::Abort(), Data, ErrH, NULL, and ObjectPointer.
Referenced by UnitList::GetObject().
Check()
void StorageType::Check (void)
!!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
 {
 //      StorageLog < "\nMax : " <= Max < "\nPoint : " <= ObjectPointer;
 //  if(ObjectPointer != Max)
 //      ErrH.Abort("Bad Storage Free");
 };
Deactive()
void StorageType::Deactive (GeneralObject * p)
 {
 /*  int i;
     for(i = 0;i < ObjectPointer;i++)
         if(Data[i] == p){
             ErrH.Abort("Bad Object Storage");
         };*/
     if(ObjectPointer < Max) Data[ObjectPointer++] = p;
     else ErrH.Abort("Object stack overflow");
 };
References XErrorHandler::Abort(), Data, ErrH, Max, and ObjectPointer.
Referenced by EffectDispatcher::DeleteEffect(), EffectDispatcher::Init(), ItemsDispatcher::Init(), and ActionDispatcher::Init().
Free()
void StorageType::Free (void)
 {
 //  Check();
     delete[] Data;
 };
References Data.
Referenced by ActionDispatcher::Free().
GetAll()
GeneralObject * StorageType::GetAll (void)
 {
     if(ObjectPointer > 0) return Data[--ObjectPointer];
     return NULL;
 };
References Data, NULL, and ObjectPointer.
Init()
void StorageType::Init (int _max = 100)
 {
     Data = new GeneralObject*[Max = _max];
     ObjectPointer = 0;
 };
References Data, Max, and ObjectPointer.
Referenced by EffectDispatcher::Init(), ItemsDispatcher::Init(), and ActionDispatcher::Init().
Member Data Documentation
Data
GeneralObject** StorageType::Data
Referenced by Active(), Deactive(), Free(), GetAll(), and Init().
Max
int StorageType::Max
Referenced by Deactive(), iGameMap::draw(), and Init().
ObjectPointer
int StorageType::ObjectPointer
Referenced by Active(), Deactive(), iGameMap::draw(), GetAll(), and Init().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp