Vangers: GloryPlace Struct Reference
GloryPlace Struct Reference
#include <items.h>
Public Member Functions
void Init (int ind)
void Quant (void)
void CloseWorld (void)
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
int World
int Enable
int Index
LightPoint * LightData
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CloseWorld()
void GloryPlace::CloseWorld (void)
 {
     if(LightData){
         LightData->Destroy();
         LightData = NULL;
     };
 };
References LightPoint::Destroy(), LightData, and NULL.
Init()
void GloryPlace::Init (int ind)
 {
     ID = ID_GLORY_PLACE;
     Enable = 1;
     R_curr.z = 255;
     Status = 0;
     LightData = NULL;
     Index = ind;
     //zMod fixed
     //zNfo - GloryPlace
     //Formula-V
     if (z_my_server_data.mod_id == Z_MODS_FORMULAV_ID) {
         World = WORLD_GLORX;
         switch (ind % 4) {
         case 0: R_curr.x = 1341;    R_curr.y = 5971;    break;
         case 1: R_curr.x =  486;    R_curr.y = 5648;    break;
         case 2: R_curr.x = 1607;    R_curr.y = 6315;    break;
         case 3: R_curr.x =   80;    R_curr.y = 7281;    break;
         }
         return;
     }
     //Trak-Trial
     if (z_my_server_data.mod_id == Z_MODS_TRAKTRIAL_ID) {
         World = WORLD_NECROSS;
         switch (ind % 2) {
         case 0: R_curr.x =  620;    R_curr.y = 14771;   break;
         case 1: R_curr.x = 1756;    R_curr.y = 2447;    break;
         }
         return;
     }
     //khoxrun
     if (z_my_server_data.mod_id == Z_MODS_KHOXRUN_ID) {
         World = WORLD_KHOX;
         switch (ind) {
         case  0:    R_curr.x = 1358;    R_curr.y = 7036;    World = WORLD_GLORX;    break; // НЕ МЕНЯТЬ !!! Связано с багом вылета клиента при смерти в пассе. если чек не на трех мирах.
         case  1:    R_curr.x =  390;    R_curr.y = 1266;    break;
         case  2:    R_curr.x = 1858;    R_curr.y = 1849;    break;
         case  3:    R_curr.x = 1869;    R_curr.y =  232;    break;
         case  4:    R_curr.x =  696;    R_curr.y =   86;    break;
         case  5:    R_curr.x = 1145;    R_curr.y = 1210;    break;
         case  6:    R_curr.x = 1987;    R_curr.y = 1043;    break;
         case  7:    R_curr.x = 2021;    R_curr.y =    8;    break;
         case  8:    R_curr.x =  150;    R_curr.y =  378;    break;
         case  9:    R_curr.x =  910;    R_curr.y = 2014;    break;
         case 10:    R_curr.x = 1232;    R_curr.y =  717;    break;
         case 11:    R_curr.x =  307;    R_curr.y =  385;    break;
         }
         return;
     }
     //classic
     if(ind == 0) {
         World = GloryRnd.aiRnd(3); // НЕ МЕНЯТЬ !!! Связано с багом вылета клиента при смерти в пассе. если чек не на трех мирах.
     } else {
         World = GloryRnd.aiRnd(WORLD_MAX);
         while (World == WORLD_HMOK)
             World = GloryRnd.aiRnd(WORLD_MAX);
         if(z_my_server_data.mod_id == Z_MODS_RAFARUN_ID ) //tarakan'i bega/ excludes hmok && threall
             while (World==WORLD_HMOK || World==WORLD_THREALL)
         World = GloryRnd.aiRnd(WORLD_MAX);
     };
     R_curr.x = GloryRnd.aiRnd(WorldTable[World]->x_size);
     if(World < MAIN_WORLD_MAX - 1)
         R_curr.y = 300 + GloryRnd.aiRnd(WorldTable[World]->y_size - 600);
     else
         R_curr.y = GloryRnd.aiRnd(WorldTable[World]->y_size);
 };
References aiRndType::aiRnd(), Enable, GloryRnd, GeneralObject::ID, ID_GLORY_PLACE, Index, LightData, MAIN_WORLD_MAX, zServerData::mod_id, NULL, GeneralObject::R_curr, GeneralObject::Status, WORLD_GLORX, WORLD_HMOK, WORLD_KHOX, WORLD_MAX, WORLD_NECROSS, WORLD_THREALL, WorldTable, Vector::x, Vector::y, Vector::z, Z_MODS_FORMULAV_ID, Z_MODS_KHOXRUN_ID, Z_MODS_RAFARUN_ID, Z_MODS_TRAKTRIAL_ID, and z_my_server_data.
Quant()
void GloryPlace::Quant (void)
 {
     int i;
     int dx,dy;
     uchar** lt;
     if(World == CurrentWorld && Enable){
         lt = vMap->lineT;
         for(i = -GLORY_PLACE_RADIUS;i < GLORY_PLACE_RADIUS;i++){
             if(!lt[YCYCL(R_curr.y + i)]){
                 if(LightData){
                     LightData->Destroy();
                     LightData = NULL;
                 };
                 return;
             };
         };
         if(ActD.Active){
             if(!LightData)
                 LightData = MapD.CreateLight(R_curr.x,R_curr.y,255,GLORY_PLACE_RADIUS,32,LIGHT_TYPE::DYNAMIC | LIGHT_TYPE::TOR);
             dx = getDistX(ActD.Active->R_curr.x,R_curr.x);
             dy = getDistY(ActD.Active->R_curr.y,R_curr.y);
             if((dx*dx + dy*dy) < GLORY_PLACE_RADIUS*GLORY_PLACE_RADIUS &&
                 ((ActD.Active->dynamic_state & GROUND_COLLISION) || (ActD.Active->dynamic_state & TRACTION_WHEEL_TOUCH) || (ActD.Active->dynamic_state & STEER_WHEEL_TOUCH))){
                     if(LightData){
                         LightData->Destroy();
                         LightData = NULL;
                     };
                     MapD.CreateLight(R_curr.x,R_curr.y,R_curr.z,GLORY_PLACE_RADIUS,32,LIGHT_TYPE::STATIONARY);
                     for(i = 0;i < 5;i++)
                         EffD.CreateDeform(Vector(XCYCL(R_curr.x + GLORY_PLACE_RADIUS - RND(2*GLORY_PLACE_RADIUS)),YCYCL(R_curr.y + GLORY_PLACE_RADIUS - RND(2*GLORY_PLACE_RADIUS)),255),DEFORM_ALL,PASSING_WAVE_PROCESS);
                     Enable = 0;
                     UsedCheckNum++;
                     NetStatisticUpdate(NET_STATISTICS_CHECKPOINT);
                     if(UsedCheckNum >= GloryPlaceNum)
                         NetStatisticUpdate(NET_STATISTICS_END_RACE);
                     send_player_body(my_player_body);
                     SOUND_SUCCESS();
             };
         };
     };
 };
References ActD, ActionDispatcher::Active, EffectDispatcher::CreateDeform(), CurrentWorld, DEFORM_ALL, LightPoint::Destroy(), LIGHT_TYPE::DYNAMIC, EffD, Enable, getDistX(), getDistY(), GLORY_PLACE_RADIUS, GloryPlaceNum, GROUND_COLLISION, LightData, vrtMap::lineT, MapD, my_player_body, NET_STATISTICS_CHECKPOINT, NET_STATISTICS_END_RACE, NetStatisticUpdate(), NULL, PASSING_WAVE_PROCESS, GeneralObject::R_curr, RND(), send_player_body(), SOUND_SUCCESS, LIGHT_TYPE::STATIONARY, STEER_WHEEL_TOUCH, LIGHT_TYPE::TOR, TRACTION_WHEEL_TOUCH, UsedCheckNum, vMap, Object::x, Vector::x, XCYCL, Object::y, Vector::y, YCYCL, and Vector::z.
Referenced by GameObjectDispatcher::Quant().
Member Data Documentation
Enable
int GloryPlace::Enable
Referenced by Init(), and Quant().
Index
int GloryPlace::Index
Referenced by Init().
LightData
LightPoint* GloryPlace::LightData
Referenced by CloseWorld(), Init(), and Quant().
World
int GloryPlace::World
Referenced by VangerUnit::Destroy().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp