Vangers: WorldScreen Struct Reference
WorldScreen Struct Reference
#include <screen.h>
Public Member Functions
WorldScreen (int _y, int _sy, uvsWorld *_Pworld)
int GetX (int xx)
int GetY (int yy)
void Quant (void)
void DollyQuant (uvsDolly *pd)
void VangerQuant (uvsVanger *pv)
Public Attributes
int x
int y
int sx
int sy
int fx
int fy
int x_size
int y_size
Place * placeTail
XBuffer info
uvsWorld * Pworld
Detailed Description
Constructor & Destructor Documentation
WorldScreen()
WorldScreen::WorldScreen (int _y, int _sy, uvsWorld * _Pworld)
 {
     Pworld = _Pworld;
 #ifdef TINY_MODE
     x = 100;
     sx = 320;
 #else
     x = 0;
     sx = XGR_MAXX;
 #endif
     y = _y; sy = _sy - (16 + 2);
     fx = 1; fy = y + sy + 2;
     x_size = Pworld -> x_size;
     y_size = Pworld -> y_size;
     placeTail = NULL;
 }
References fx, fy, NULL, placeTail, Pworld, sx, sy, x, x_size, XGR_MAXX, y, and y_size.
Member Function Documentation
DollyQuant()
void WorldScreen::DollyQuant (uvsDolly * pd)
 {
     int xx = x + GetX(pd -> pos_y);
     int yy = y + GetY(pd -> pos_x);
     XGR_LineTo(xx - 3,yy,7,2,63);
     XGR_LineTo(xx,yy - 3,7,3,63);
     XGR_SetPixel(xx - 1,yy - 1,63); XGR_SetPixel(xx - 1,yy + 1,63);
     XGR_SetPixel(xx + 1,yy - 1,63); XGR_SetPixel(xx + 1,yy + 1,63);
     int i,j = pd -> tail_cInd,c;
     j = (j - 1 < 0) ? DOLLY_TAIL_LEN - 1 : j - 1;
     for(i = 0;i < DOLLY_TAIL_LEN;i++)
         if(pd -> tail_x[j] != -1){
             xx = x + GetX(pd -> tail_y[j]);
             yy = y + GetY(pd -> tail_x[j]);
             c = 63 - (i + 1)*60/DOLLY_TAIL_LEN;
             XGR_LineTo(xx - 2,yy,5,2,c);
             XGR_LineTo(xx,yy - 2,5,3,c);
             j = (j - 1 < 0) ? DOLLY_TAIL_LEN - 1 : j - 1;
             }
 }
References DOLLY_TAIL_LEN, GetX(), GetY(), x, XGR_LineTo, XGR_SetPixel, and y.
GetX()
int WorldScreen::GetX (int xx) inline
 { return xx*sx/y_size; }
References sx, and y_size.
Referenced by DollyQuant(), Quant(), and VangerQuant().
GetY()
int WorldScreen::GetY (int yy) inline
 { return yy*sy/x_size; }
References sy, and x_size.
Referenced by DollyQuant(), Quant(), and VangerQuant().
Quant()
void WorldScreen::Quant (void)
 {
 std::cout<<"WorldScreen::Quant"<<std::endl;
 #ifdef TINY_MODE
     XGR_Rectangle(x,y,sx,sy,0,0,XGR_FILLED);
 #else
     XGR_Rectangle(x,y,sx,sy,0,SYSCOLOR,XGR_OUTLINED);
 #endif
     info.init();
     info < "                  " <  Pworld -> name;
     if (Pworld -> escTmax){
         info < " [Stage " <= Pworld -> escT[0] -> GetCurrentStage() < ": " < Pworld -> escT[0] -> GetCurrentStageName() < "]";
 #ifndef TINY_MODE
     info < " cirtQ: "<= Pworld -> escT[0] -> Pbunch -> GetCirtQ();
     info < " vRes: "<= Pworld -> escT[0] -> Pbunch -> vngResource;
 #endif
     }
     sysfont.draw(fx,fy,info.GetBuf());
     int i;
     int xx,yy,len;
     uvsEscave* pe;
     char* s;
     /*Place* p = placeTail;
     while(p){
         xx = x + GetX(p -> y);
         yy = y + GetY(p -> x);
         XGR_Rectangle(xx - 2,yy - 2,5,5,COL3,COL3,XGR_FILLED);
         p = (Place*)p -> next;
         }*/
     for(i = 0;i < Pworld -> escTmax;i++){
         pe = Pworld -> escT[i];
         xx = x + GetX(pe -> pos_y);
         yy = y + GetY(pe -> pos_x);
         XGR_Rectangle(xx - ESCAVE_SIDE,yy - ESCAVE_SIDE,ESCAVE_SIZE,ESCAVE_SIZE,COL1,COL1,XGR_FILLED);
         s = pe -> name;
         yy += ESCAVE_SIDE + 1;
         len = strlen(s)*8;
         xx -= len/2;
         if(xx < x + 2) xx = x + 2;
         else if(xx + len >= x + sx - 3) xx -= xx + len - (x + sx - 3);
 #ifndef TINY_MODE
         sysfont.draw(xx,yy,s,COL1,-1);
 #endif
         }
     uvsSpot* ps;
     for(i = 0;i < Pworld -> sptTmax;i++){
         ps = Pworld -> sptT[i];
         xx = x + GetX(ps -> pos_y);
         yy = y + GetY(ps -> pos_x);
         XGR_Rectangle(xx - SPOT_SIDE,yy - SPOT_SIDE,SPOT_SIZE,SPOT_SIZE,COL2,COL2,XGR_FILLED);
         s = ps -> name;
         yy += SPOT_SIDE + 1;
         len = strlen(s)*8;
         xx -= len/2;
         if(xx < x + 2) xx = x + 2;
         else if(xx + len >= x + sx - 3) xx -= xx + len - (x + sx - 3);
 #ifndef TINY_MODE
         sysfont.draw(xx,yy,s,COL2,-1);
 #endif
         }
     uvsPassage* pp;
     for(i = 0;i < Pworld -> pssTmax;i++){
         pp = Pworld -> pssT[i];
         xx = x + GetX(pp -> pos_y);
         yy = y + GetY(pp -> pos_x);
         XGR_Rectangle(xx - PASSAGE_SIDE,yy - PASSAGE_SIDE,PASSAGE_SIZE,PASSAGE_SIZE,COL1,COL1,XGR_OUTLINED);
         info.init();
         info <  (char)0x10 < pp -> Poutput -> name;
         s = info.GetBuf();
         yy += PASSAGE_SIDE + 1;
         len = strlen(s)*8;
         xx -= len/2;
         if(xx < x + 2) xx = x + 2;
         else if(xx + len >= x + sx - 3) xx -= xx + len - (x + sx - 3);
 #ifndef TINY_MODE
         sysfont.draw(xx,yy,s,COL1,-1);
 #endif
         }
     uvsElement* ppe = Pworld -> Panymal;
     while(ppe){
             int xx = x + GetX(((uvsFlyFarmer*)ppe) -> pos_y);
             int yy = y + GetY(((uvsFlyFarmer*)ppe) -> pos_x);
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_FLY_FARMER, XGR_HIDDEN_FON);
             ppe = ppe -> enext;
     }
 }
References COL1, COL2, ESCAVE_SIDE, ESCAVE_SIZE, fx, fy, XBuffer::GetBuf(), GetX(), GetY(), ICON_SX, ICON_SY, info, XBuffer::init(), PASSAGE_SIDE, PASSAGE_SIZE, Pworld, SPOT_SIDE, SPOT_SIZE, sx, sy, sysfont, x, XGR_FILLED, XGR_OUTLINED, XGR_PutSpr, XGR_Rectangle, and y.
VangerQuant()
void WorldScreen::VangerQuant (uvsVanger * pv)
 {
     int xx = x + GetX(pv -> pos_y);
     int yy = y + GetY(pv -> pos_x);
     switch(pv -> shape){
         case UVS_VANGER_SHAPE::TABUTASK:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_TABU, XGR_HIDDEN_FON);
             break;
         case UVS_VANGER_SHAPE::BUNCH_SLAVE:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_SLAVE, XGR_HIDDEN_FON);
             break;
         case UVS_VANGER_SHAPE::RANGER:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_RANGER,XGR_HIDDEN_FON);
             break;
         case UVS_VANGER_SHAPE::GAMER:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_GAMER, XGR_HIDDEN_FON);
             break;
         case UVS_VANGER_SHAPE::THIEF:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_THIEF, XGR_HIDDEN_FON);
             break;
         case UVS_VANGER_SHAPE::CARAVAN:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_CARAVAN, XGR_HIDDEN_FON);
             break;
         case UVS_VANGER_SHAPE::KILLER:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_KILLER, XGR_HIDDEN_FON);
             break;
         case UVS_VANGER_SHAPE::GAMER_SLAVE:
             XGR_PutSpr(xx - ICON_SX/2,yy - ICON_SY/2,ICON_SX,ICON_SY,ICON_GSLAVE, XGR_HIDDEN_FON);
             break;
         }
 }
References GetX(), GetY(), ICON_SX, ICON_SY, UVS_VANGER_SHAPE::TABUTASK, x, XGR_PutSpr, and y.
Member Data Documentation
fx
int WorldScreen::fx
Referenced by Quant(), and WorldScreen().
fy
int WorldScreen::fy
Referenced by Quant(), and WorldScreen().
info
XBuffer WorldScreen::info
Referenced by Quant().
placeTail
Place* WorldScreen::placeTail
Referenced by WorldScreen().
Pworld
uvsWorld* WorldScreen::Pworld
Referenced by Quant(), and WorldScreen().
sx
int WorldScreen::sx
Referenced by GetX(), Quant(), and WorldScreen().
sy
int WorldScreen::sy
Referenced by GetY(), Quant(), and WorldScreen().
x
int WorldScreen::x
Referenced by DollyQuant(), Quant(), VangerQuant(), and WorldScreen().
x_size
int WorldScreen::x_size
Referenced by GetY(), and WorldScreen().
y
int WorldScreen::y
Referenced by DollyQuant(), Quant(), VangerQuant(), and WorldScreen().
y_size
int WorldScreen::y_size
Referenced by GetX(), and WorldScreen().
The documentation for this struct was generated from the following files:
src/uvs/screen.h
src/uvs/screen.cpp