Vangers: BaseRTO Struct Reference
BaseRTO Struct Reference
#include <runtime.h>
Public Member Functions
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
virtual void Init (int pID)
virtual void Finit (void)
virtual int Quant (void)
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Public Attributes
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
BaseRTO()
BaseRTO::BaseRTO (void) inline
 { NextID = XT_TERMINATE_ID; flags = 0; }
References flags, NextID, and XT_TERMINATE_ID.
Member Function Documentation
ClearFlag()
void BaseRTO::ClearFlag (int fl) inline
 { flags &= ~fl; }
References flags.
Referenced by LoadingRTO1::Finit(), LoadingRTO2::Finit(), MainMenuRTO::Finit(), FirstEscaveRTO::Finit(), and EscaveRTO::Finit().
SetFlag()
void BaseRTO::SetFlag (int fl) inline
 { flags |= fl; }
References flags.
Referenced by MainMenuRTO::Finit(), FirstEscaveRTO::Finit(), EscaveRTO::Finit(), MainMenuRTO::Init(), LoadingRTO1::Quant(), LoadingRTO2::Quant(), and MainMenuRTO::Quant().
SetNext()
void BaseRTO::SetNext (int id) inline
 { NextID = id; }
References NextID.
Referenced by LoadingRTO3::Init().
Member Data Documentation
flags
int BaseRTO::flags
Referenced by BaseRTO(), ClearFlag(), MainMenuRTO::Finit(), FirstEscaveRTO::Finit(), EscaveRTO::Finit(), LoadingRTO1::Init(), MainMenuRTO::Init(), LoadingRTO1::Quant(), LoadingRTO2::Quant(), MainMenuRTO::Quant(), and SetFlag().
NextID
int BaseRTO::NextID
Referenced by BaseRTO(), LoadingRTO1::Quant(), LoadingRTO2::Quant(), LoadingRTO3::Quant(), EscaveOutRTO::Quant(), FirstEscaveOutRTO::Quant(), ShowImageRTO::Quant(), ShowAviRTO::Quant(), PaletteTransformRTO::Quant(), and SetNext().
The documentation for this struct was generated from the following file:
src/runtime.h