Vangers: ImpulseSpot Struct Reference
ImpulseSpot Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Quant (void)
void Active (void)
Public Member Functions inherited from ElevatorEngine
void Close (void)
void Link (void)
void Touch (GeneralObject *obj, SensorDataType *p)
Public Member Functions inherited from LocationEngine
void NetEvent (void)
void SoundEvent (void)
Additional Inherited Members
Public Attributes inherited from ImpulseEscave
SensorDataType * ImpulseLink
Public Attributes inherited from EscaveEngine
int LastOpen
int StartAngle
Public Attributes inherited from ElevatorEngine
DoorEngine * DoorLink
char * DoorName
int UseFlag
int ActionFlag
Public Attributes inherited from EnterEngine
SensorDataType * ActionLink
EnterCenter * Owner
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Active()
void ImpulseSpot::Active (void) virtual
Reimplemented from ImpulseEscave.
 {
     ImpulseLink->Enable = 1;
     UseFlag = 2;
     ActionLink->Enable = 0;
     DoorLink->OpenDoor(0);
 };
References EnterEngine::ActionLink, ElevatorEngine::DoorLink, StaticObject::Enable, ImpulseEscave::ImpulseLink, DoorEngine::OpenDoor(), and ElevatorEngine::UseFlag.
Open()
void ImpulseSpot::Open (Parser & in) virtual
Reimplemented from ImpulseEscave.
 {
     ImpulseEscave::Open(in);
     Type = EngineTypeList::IMPULSE_SPOT;
     ActionLink->Enable = 1;
 };
References EnterEngine::ActionLink, StaticObject::Enable, EngineTypeList::IMPULSE_SPOT, ImpulseEscave::Open(), and LocationEngine::Type.
Quant()
void ImpulseSpot::Quant (void) virtual
Reimplemented from ImpulseEscave.
 {
     if(MLLink && !MLLink->frozen){
         switch(UseFlag){
             case 0:
                 if(DoorLink->Mode != EngineModeList::WAIT){
                     Owner->LockedCenter(this);
                     UseFlag = 1;
                     ActionLink->Enable = 0;
                 };
                 break;
             case 1:
                 if(DoorLink->Mode == EngineModeList::WAIT && !(DoorLink->ProcessFlag)){
                     Owner->PutCenter(this);
                     UseFlag = 0;
                     ActionLink->Enable = 1;
                 };
                 break;
             case 2:
                 if(DoorLink->Mode == EngineModeList::WAIT && !(DoorLink->ProcessFlag)){
                     Owner->PutCenter(this);
                     UseFlag = 0;
                     ImpulseLink->Enable = 0;
                     ActionLink->Enable = 1;
                 };
                 break;
         };
     }else{
         if(UseFlag){
             Owner->PutCenter(this);
             UseFlag = 0;
             ImpulseLink->Enable = 0;
             ActionLink->Enable =1;
         };
     };
 };
References EnterEngine::ActionLink, ElevatorEngine::DoorLink, StaticObject::Enable, MobileLocation::frozen, ImpulseEscave::ImpulseLink, EnterCenter::LockedCenter(), LocationEngine::MLLink, LocationEngine::Mode, EnterEngine::Owner, DoorEngine::ProcessFlag, EnterCenter::PutCenter(), ElevatorEngine::UseFlag, and EngineModeList::WAIT.
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp