Vangers: HordeList Struct Reference
HordeList Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
HordeObject * CreateHorde (void)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Free (void)
virtual void Quant (void)
virtual void NetEvent (int type, int id)
virtual void FreeUnit (GeneralObject *p)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Additional Inherited Members
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
CreateHorde()
HordeObject * HordeList::CreateHorde (void)
 {
     HordeObject* p;
     p = new HordeObject;
     p->Init();
     ConnectTypeList(p);
     return p;
 };
References UnitBaseListType::ConnectTypeList(), and HordeObject::Init().
Referenced by Init(), HordeSourceList::Quant(), and GunSlot::Quant().
Init()
void HordeList::Init (void) virtual
Reimplemented from UnitListType.
 {
     int i,max;
 //zmod 1.21
     if(NetworkON){
         double kmax = (1.-zMod_flood_level_delta)/2;
         switch(CurrentWorld){
             case WORLD_FOSTRAL:
             case WORLD_GLORX:
             case WORLD_NECROSS:
                 max = MAX_HORDE_OBJECT;
                 break;
             default:
                 max = MAX_HORDE_SOURCE_OBJECT / 2;
         };
         max = (int)((double)max * kmax);
         for(i = 0;i < max;i++)
             (CreateHorde())->CreateHorde(Vector(NetRnd.Get(map_size_x),NetRnd.Get(map_size_y),270),20,240,400,NULL);
     }else{
         switch(CurrentWorld){
             case WORLD_WEEXOW:
             case WORLD_ARKONOY:
                 for(i = 0;i < MAX_HORDE_OBJECT;i++)
                     (CreateHorde())->CreateHorde(Vector(RND(map_size_x),RND(map_size_y),270),20,240,400,NULL);
                 break;
         };
     };
 };
References CreateHorde(), CurrentWorld, NetRndType::Get(), map_size_x, map_size_y, max(), MAX_HORDE_OBJECT, MAX_HORDE_SOURCE_OBJECT, NetRnd, NetworkON, NULL, RND(), WORLD_ARKONOY, WORLD_FOSTRAL, WORLD_GLORX, WORLD_NECROSS, WORLD_WEEXOW, and zMod_flood_level_delta.
Referenced by GeneralSystemOpen().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp