Vangers: LoadingRTO2 Struct Reference
LoadingRTO2 Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
virtual void Finit (void)
LoadingRTO2 (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Additional Inherited Members
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
LoadingRTO2()
LoadingRTO2::LoadingRTO2 (void) inline
 { ID = RTO_LOADING2_ID; Timer = 1; }
References XRuntimeObject::ID, RTO_LOADING2_ID, and XRuntimeObject::Timer.
Member Function Documentation
Finit()
void LoadingRTO2::Finit (void) virtual
Reimplemented from XRuntimeObject.
 {
     ClearFlag(RTO_ALL_FLAGS);
 _MEM_STATISTIC_("AFRET LOADING RTO2 FINIT -> ");
 }
References _MEM_STATISTIC_, BaseRTO::ClearFlag(), and RTO_ALL_FLAGS.
Init()
void LoadingRTO2::Init (int id) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
     FinishFirstShopPrepare(aciLoadLog);
     aciLoadLog = 0;
     i_change_res();
     LoadingMessage(1);
 #endif
 #ifdef _DEBUG
     StandScreenPrepare();
 #endif
 _MEM_STATISTIC_("\nBEFORE VMAP  -> ");
     vMapPrepare(mapFName,CurrentWorld);
     vMapInit();
 _MEM_STATISTIC_("AFTER VMAP  -> ");
     LoadResourceSOUND(GetTargetName("sound/"), 0);
 _MEM_STATISTIC_("AFTER SOUND  -> ");
 _MEM_STATISTIC_("AFTER LOAD PARAM  -> ");
     MLload();
 _MEM_STATISTIC_("AFTER ML LOAD  -> ");
     PrepareLight();
 _MEM_STATISTIC_("AFTER PREPARE LIGHT  -> ");
     EffD.CalcWave();
     dastCreateResource("resource/bml/mole.bml");
 _MEM_STATISTIC_("AFTER DAST  -> ");
 //  dastCreateResourceSign("resource\\bml\\sign.fnt");
     GeneralTableInit();
 _MEM_STATISTIC_("AFTER TABLE GENERAL  -> ");
     GeneralTableOpen();
 _MEM_STATISTIC_("AFTER TABLE OPEN  -> ");
 #ifdef ACTINT
     curGMap = new iGameMap(aScrDisp -> curIbs -> CenterX,aScrDisp -> curIbs -> CenterY,XSIDE,YSIDE);
 #else
     curGMap = new iGameMap(XGR_MAXX/2,XGR_MAXY/2,XSIDE,YSIDE);
 #endif
     Redraw = 1;
 _MEM_STATISTIC_("AFTER curGMap  -> ");
     loadingStatus = 0;
     vMap -> quant();
     uvsAddStationaryObjs();
     uvsRestoreVanger();
 #ifndef NEW_TNT
     RestoreBarell();
 #endif
     gameQuant(); gameQuant();
     StartMainQuantFlag = 1;
     gameQuant();
 #ifndef NEW_TNT
     RestoreFlagBarell();
 #endif
 #ifdef ISCREEN
     palTr -> set(NULL,palbufOrg,0,255);
 #else
     XGR_SetPal(palbufOrg,0,255);
 #endif
 #ifdef _ACI_SKIP_SHOP_
     XGR_SetPal(palbuf,0,255);
 #endif
     if(idOS == 1) vMap -> lockMem();
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 _MEM_STATISTIC_("AFTER LOADING RTO2 INIT -> ");
 }
References _MEM_STATISTIC_, aciLoadLog, aScrDisp, EffectDispatcher::CalcWave(), curGMap, CurrentWorld, dastCreateResource(), EffD, FinishFirstShopPrepare(), gameQuant(), GeneralTableInit(), GeneralTableOpen(), GetTargetName(), i_change_res(), idOS, LoadingMessage(), loadingStatus, LoadResourceSOUND(), mapFName, MLload(), NULL, palbuf, palbufOrg, palTr, PrepareLight(), Redraw, set(), StandScreenPrepare(), StartMainQuantFlag, uvsAddStationaryObjs(), uvsRestoreVanger(), vMap, vMapInit(), vMapPrepare(), XGR_Flush, XGR_MAXX, XGR_MAXY, XGR_SetPal, XSIDE, and YSIDE.
Quant()
int LoadingRTO2::Quant (void) virtual
Reimplemented from XRuntimeObject.
 {
     //XGR_Flip();
     if(!(flags & RTO_QUANT_FLAG)){
         SetFlag(RTO_QUANT_FLAG);
         return 0;
     }
 #ifdef ISCREEN
     return NextID;
 #else
     return RTO_GAME_QUANT_ID;
 #endif
 }
References BaseRTO::flags, BaseRTO::NextID, RTO_GAME_QUANT_ID, RTO_QUANT_FLAG, and BaseRTO::SetFlag().
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp