Vangers: dgMolecule Struct Reference
dgMolecule Struct Reference
#include <diagen.h>
Public Member Functions
dgMolecule (char *_name)
~dgMolecule (void)
void link (dgMolecule *&tail, int mode=0)
dgMolecule * delink (dgMolecule *&tail)
void accept (dgFile *_dgf)
void release (void)
char * getPhrase (int noHandle)
void goNext (void)
dgAtom * getVariantsAtom (void)
void reset (void)
int getHandledPhrase (char *s)
char * getVarPhrase (char *s)
Public Attributes
char * name
dgFile * dgf
int mood
dgAtom * tail
dgAtom * curA
dgMolecule * next
dgMolecule * prev
Detailed Description
Constructor & Destructor Documentation
dgMolecule()
dgMolecule::dgMolecule (char * _name) inline
                                { dgf = NULL; tail = curA = NULL;
                                 next = prev = NULL; name = strdup(_name);
                                 mood = 0; }
References curA, dgf, mood, name, next, NULL, prev, and tail.
~dgMolecule()
dgMolecule::~dgMolecule (void) inline
 { ::free(name); }
References name.
Member Function Documentation
accept()
void dgMolecule::accept (dgFile * _dgf)
 {
     dgf = _dgf;
     char* p = NULL;
     dgAtom* pa;
     while(1){
         if(!p) if(!(p = dgf -> getElement(DGF_DUAL,1))) break;
         (pa = new dgAtom) -> link(tail);
         if(!(p = pa -> read(dgf,p))) break;
         }
     curA = tail;
 }
References curA, dgf, DGF_DUAL, link(), NULL, and tail.
delink()
dgMolecule * dgMolecule::delink (dgMolecule *& tail)
 {
     if(tail != this){
         prev -> next = next;
         if(!next) tail -> prev = prev;
         }
     else {
         tail = next;
         }
     if(next) next -> prev = prev;
     return this;
 }
References next, prev, and tail.
getHandledPhrase()
int dgMolecule::getHandledPhrase (char * s)
 {
     static char mss[] = "Wrong VarPhrase format";
     char* var = strchr(s,'$');
     if(!var) return 0;
     char* p = var + 1;
     if(*p != '(') ErrH.Abort(mss);
     p++; while(*p != ')' && *p) p++;
     if(!*p) ErrH.Abort(mss);
     *p = '\0'; p++;
     char* pp = p + strlen(p) - 1;
     char* ns = getVarPhrase(var + 2);
     strcpy(var,ns);
     strcpy(var + strlen(ns),p);
     while(*pp) *pp-- = '\0';
     return 1;
 }
References XErrorHandler::Abort(), ErrH, and getVarPhrase().
Referenced by getPhrase().
getPhrase()
char * dgMolecule::getPhrase (int noHandle)
 {
     char* ret = curA ? curA -> data : NULL;
     if(!ret) {
         return NULL;
     }
     if(!noHandle) {
         static char* buf = new char[1311];
         int log = 1;
 //      if(strlen(ret) >= 310)
 //          ErrH.Abort("getPhrase() too long", XERR_USER,-1,name);
         strcpy(buf,ret);
         while(log) log = getHandledPhrase(buf);
         return buf;
     }
     return ret;
 }
References curA, getHandledPhrase(), and NULL.
getVariantsAtom()
dgAtom* dgMolecule::getVariantsAtom (void) inline
 { if(curA) return curA -> variants ? curA : NULL; return NULL; }
References curA, and NULL.
getVarPhrase()
char * dgMolecule::getVarPhrase (char * s)
 {
     static char nbuf[] = "\0\0\0\0\0\0\0\0\0\0";
     char* ret = NULL;
     if(!strcmp(s,"World of Larva0")) ret = dgD -> getWorldName(uvsGetLarvaWorld(0));
     else if(!strcmp(s,"World of Larva1")) ret = dgD -> getWorldName(uvsGetLarvaWorld(1));
     else if(!strcmp(s,"World of Larva2")) ret = dgD -> getWorldName(uvsGetLarvaWorld(2));
     else if(!strcmp(s,"Cirt Delivery")) ret = port_itoa(uvsgetDGdata(DG_EXTERNS::CIRT_DELIVERY),nbuf,10);
     else if(!strcmp(s,"Cycle Name of Locked Larva")) ret = dgD -> CycleName[lang() == RUSSIAN ? 1 : 0][dgD -> currentR -> bios][uvsgetDGdata(DG_EXTERNS::LARVA_CYCLE)];
     else if(!strcmp(s,"Boozeena Secret Code")) ret = StringOfBoozeeniada();
     if(!ret) return s;
 //      ErrH.Abort("Unknown VarPhrase",XERR_USER,-1,s);
     if(strlen(ret) >= strlen(s)) ErrH.Abort("Too long VarPhrase");
     return ret;
 }
References XErrorHandler::Abort(), DG_EXTERNS::CIRT_DELIVERY, dgD, ErrH, lang(), DG_EXTERNS::LARVA_CYCLE, NULL, port_itoa(), RUSSIAN, StringOfBoozeeniada(), uvsgetDGdata(), and uvsGetLarvaWorld().
Referenced by getHandledPhrase().
goNext()
void dgMolecule::goNext (void) inline
 { if(curA) curA = curA -> next; }
References curA, and next.
link()
void dgMolecule::link (dgMolecule *& tail, int mode = 0)
 {
     switch(mode){
         case 0:
             if(!tail) tail = this;
             else {
                 tail -> prev -> next = this;
                 prev = tail -> prev;
                 }
             next = NULL;
             tail -> prev = this;
             break;
         case 1:
             prev = tail -> prev;
             tail -> prev = this;
             next = tail;
             tail = this;
             break;
         case 2:
             next = tail -> next;
             prev = tail;
             if(!next) tail -> prev = this;
             else tail -> next -> prev = this;
             tail -> next = this;
             break;
         }
 }
References next, NULL, prev, and tail.
Referenced by accept().
release()
void dgMolecule::release (void) inline
 { tail = curA = NULL; }
References curA, NULL, and tail.
reset()
void dgMolecule::reset (void) inline
 { curA = tail; }
References curA, and tail.
Member Data Documentation
curA
dgAtom* dgMolecule::curA
Referenced by accept(), dgMolecule(), getPhrase(), getVariantsAtom(), goNext(), release(), and reset().
dgf
dgFile* dgMolecule::dgf
Referenced by accept(), and dgMolecule().
mood
int dgMolecule::mood
Referenced by dgMolecule().
name
char* dgMolecule::name
Referenced by dgMolecule(), and ~dgMolecule().
next
dgMolecule* dgMolecule::next
Referenced by delink(), dgMolecule(), goNext(), and link().
prev
dgMolecule* dgMolecule::prev
Referenced by delink(), dgMolecule(), and link().
tail
dgAtom* dgMolecule::tail
Referenced by accept(), delink(), dgMolecule(), link(), release(), and reset().
The documentation for this struct was generated from the following files:
src/uvs/diagen.h
src/uvs/diagen.cpp