Vangers: TrainEngine Struct Reference
TrainEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void CreateTrain (SensorDataType *p1, SensorDataType *p2, int time)
void Link (void)
Public Member Functions inherited from LocationEngine
virtual void Close (void)
virtual void Quant (void)
virtual void Touch (GeneralObject *obj, SensorDataType *p)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
int LockFlag
SensorDataType * TrainLink [2]
int EffectID
DangerDataType * DangerLink
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
CreateTrain()
void TrainEngine::CreateTrain (SensorDataType * p1, SensorDataType * p2, int time)
 {
     Type = EngineTypeList::TRAIN;
     MLLink = NULL;
     ActivePhase = 0;
     DeactivePhase = 0;
     Mode = EngineModeList::WAIT;
     Enable = 1;
     TrainLink[0] = p1;
     TrainLink[0]->Owner = this;
     TrainLink[0]->Enable = 1;
     TrainLink[0]->Index = 0;
     TrainLink[1] = p2;
     TrainLink[1]->Owner = this;
     TrainLink[1]->Enable = 1;
     TrainLink[1]->Index = 1;
     ActiveTime = time;
     DeactiveTime = 10;
     LockFlag = DOOR_CLOSE_LOCK;
 };
References LocationEngine::ActivePhase, LocationEngine::ActiveTime, LocationEngine::DeactivePhase, LocationEngine::DeactiveTime, DOOR_CLOSE_LOCK, StaticObject::Enable, LocationEngine::Enable, SensorDataType::Index, LockFlag, LocationEngine::MLLink, LocationEngine::Mode, NULL, SensorDataType::Owner, EngineTypeList::TRAIN, TrainLink, LocationEngine::Type, and EngineModeList::WAIT.
Link()
void TrainEngine::Link (void) virtual
Reimplemented from LocationEngine.
 {
     if(EffectID && NumAddDanger < DngTableSize){
         DangerLink = DangerObjectData[NumAddDanger];
         NumAddDanger++;
         DangerLink->CreateDanger(Vector(TrainLink[0]->R_curr.x,TrainLink[0]->R_curr.y,FloodLEVEL),TrainLink[0]->radius / 2,DangerTypeList::TRAIN);
     };
 };
References DangerDataType::CreateDanger(), DangerLink, DangerObjectData, DngTableSize, EffectID, FloodLEVEL, NumAddDanger, GeneralObject::R_curr, LocationEngine::R_curr, StaticObject::radius, DangerTypeList::TRAIN, TrainLink, Vector::x, and Vector::y.
Open()
void TrainEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     char* n;
     LocationEngine::Open(in);
     Type = EngineTypeList::TRAIN;
     in.search_name("FirstStationName");
     n = in.get_name();
     TrainLink[0] = FindSensor(n);
     if(!TrainLink[0])
         ErrH.Abort("Bad Find Sensor");
     TrainLink[0]->Owner = this;
     TrainLink[0]->Enable = 1;
     TrainLink[0]->Index = 0;
     in.search_name("SecondStationName");
     n = in.get_name();
     TrainLink[1] = FindSensor(n);
     if(!TrainLink[1])
         ErrH.Abort("Bad Find Sensor");
     TrainLink[1]->Owner = this;
     TrainLink[1]->Enable = 1;
     TrainLink[1]->Index = 1;
     LockFlag = DOOR_CLOSE_LOCK;
     in.search_name("EffectID");
     EffectID = in.get_int();
     DangerLink = NULL;
 };
References XErrorHandler::Abort(), DangerLink, DOOR_CLOSE_LOCK, EffectID, StaticObject::Enable, ErrH, FindSensor(), Parser::get_int(), Parser::get_name(), SensorDataType::Index, LockFlag, NULL, LocationEngine::Open(), SensorDataType::Owner, Parser::search_name(), EngineTypeList::TRAIN, TrainLink, and LocationEngine::Type.
Member Data Documentation
DangerLink
DangerDataType* TrainEngine::DangerLink
Referenced by Link(), and Open().
EffectID
int TrainEngine::EffectID
Referenced by Link(), and Open().
LockFlag
int TrainEngine::LockFlag
Referenced by CreateTrain(), and Open().
TrainLink
SensorDataType* TrainEngine::TrainLink[2]
Referenced by CreateTrain(), Link(), and Open().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp