Vangers: PlayersList Struct Reference
PlayersList Struct Reference
#include <network.h>
Public Member Functions
PlayersList ()
PlayerData * find (int client_id)
void single_parsing (int event_ID)
void reset_states ()
void delete_old_players ()
void parsing_names_query ()
void parsing_total_body_query ()
unsigned int get_team_mask (int color)
Public Member Functions inherited from XTList< PlayerData >
XTList ()
~XTList ()
int size ()
PlayerData * first ()
PlayerData * last ()
void clear ()
void delete_all ()
void insert (PlayerData *p)
void insert (PlayerData *pointer, PlayerData *p)
void append (PlayerData *p)
void append (PlayerData *pointer, PlayerData *p)
void remove (PlayerData *p)
PlayerData * search (int ID)
Public Attributes
int NumGamingPeople
Detailed Description
Constructor & Destructor Documentation
PlayersList()
PlayersList::PlayersList () inline
 { NumGamingPeople = 0; }
References NumGamingPeople.
Member Function Documentation
delete_old_players()
void PlayersList::delete_old_players ()
find()
PlayerData * PlayersList::find (int client_id)
 {
     PlayerData* p = first();
     while(p){
         if(p -> client_ID == client_id && p -> status != FINISHED_STATUS){
             return p;
             }
         p = p -> next;
         }
     p = new PlayerData(client_id);
     append(p);
     return p;
 }
References FINISHED_STATUS, and XTList< PlayerData >::first().
Referenced by iInitChatScreen(), MessageDispatcher::receive(), and single_parsing().
get_team_mask()
unsigned int PlayersList::get_team_mask (int color)
 {
     unsigned int mask = 0;
     PlayerData* p = first();
     while(p){
         if(p -> body.color == color && p -> status != FINISHED_STATUS)
             mask |= 1 << (p -> client_ID - 1);
         p = p -> next;
         }
     return mask;
 }
References FINISHED_STATUS, and XTList< PlayerData >::first().
Referenced by MessageDispatcher::send().
parsing_names_query()
void PlayersList::parsing_names_query ()
parsing_total_body_query()
void PlayersList::parsing_total_body_query ()
 {
     unsigned char client_ID,status,world;
     short x,y;
     char name[257];
     PlayerData* p;
     delete_all();
     my_player_data = 0;
     int num = events_in.get_byte();
     for(int i = 0;i < num;i++){
         events_in > client_ID > status > world > x > y > name;
         p = new PlayerData(client_ID);
         append(p);
         p -> status = status;
         p -> world = world;
         p -> x = x;
         p -> y = y;
         events_in.read(&p -> body,sizeof(PlayerBody));
         if(!p -> name){
             p -> name = new char[strlen(name) + 1];
             strcpy(p -> name, name);
             }
         else{
             if(strcmp(p -> name,name)){
                 delete p -> name;
                 p -> name = new char[strlen(name) + 1];
                 strcpy(p -> name, name);
                 }
             }
         if(p -> client_ID == GlobalStationID)
             my_player_data = p;
         }
 }
References XTList< PlayerData >::append(), XTList< PlayerData >::delete_all(), events_in, InputEventBuffer::get_byte(), GlobalStationID, my_player_data, and XBuffer::read().
Referenced by total_players_data_list_query().
reset_states()
void PlayersList::reset_states ()
single_parsing()
void PlayersList::single_parsing (int event_ID)
 {
     PlayerData* p = find(events_in.get_byte());
     switch(event_ID){
         case PLAYERS_NAME:{
             char name[257];
             events_in > name;
             if(!p -> name){
                 p -> name = new char[strlen(name) + 1];
                 strcpy(p -> name, name);
                 }
             else{
                 if(strcmp(p -> name,name)){
                     delete[] p -> name;
                     p -> name = new char[strlen(name) + 1];
                     strcpy(p -> name, name);
                     }
                 }
             }
             break;
         case PLAYERS_POSITION:
             p -> x = events_in.get_short();
             p -> y = events_in.get_short();
             break;
         case PLAYERS_WORLD:
             p -> world = events_in.get_byte();
             break;
         case PLAYERS_STATUS:
             p -> status = events_in.get_byte();
             if(p -> status == FINISHED_STATUS)
                 PLAYER_REMOVAL_EVENT(p);
             break;
         case PLAYERS_DATA:
             events_in.read(&(p -> body),sizeof(PlayerBody));
             break;
         case PLAYERS_RATING:
             p -> body.rating = (float)events_in.get_float();
             break;
         }
 }
References events_in, find(), FINISHED_STATUS, InputEventBuffer::get_byte(), InputEventBuffer::get_float(), InputEventBuffer::get_short(), PLAYER_REMOVAL_EVENT, PLAYERS_DATA, PLAYERS_NAME, PLAYERS_POSITION, PLAYERS_RATING, PLAYERS_STATUS, PLAYERS_WORLD, and XBuffer::read().
Member Data Documentation
NumGamingPeople
int PlayersList::NumGamingPeople
Referenced by PlayersList().
The documentation for this struct was generated from the following files:
src/network.h
src/network.cpp