Vangers: ItemGenerator Struct Reference
ItemGenerator Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Quant (void)
void Link (void)
void Close (void)
Public Member Functions inherited from LocationEngine
virtual void Touch (GeneralObject *obj, SensorDataType *p)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
int Time
char * DoorName
int DeviceType
int DeviceP1
int DeviceP2
LocationEngine * pLink
SensorDataType * SensorLink
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Close()
void ItemGenerator::Close (void) virtual
Reimplemented from LocationEngine.
 {
     if(DoorName) delete[] DoorName;
 };
References DoorName.
Link()
void ItemGenerator::Link (void) virtual
Reimplemented from LocationEngine.
 {
     pLink = FindSensor(DoorName)->Owner;
     if(!pLink) ErrH.Abort("Bad Door Object");
 };
References XErrorHandler::Abort(), DoorName, ErrH, FindSensor(), SensorDataType::Owner, and pLink.
Open()
void ItemGenerator::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     int i;
     char* n;
     LocationEngine::Open(in);
     in.search_name("SensorName");
     n = in.get_name();
     SensorLink = NULL;
     SensorLink = FindSensor(n);
     if(!SensorLink)
         ErrH.Abort("Bad Find Sensor");
     SensorLink->Enable = 1;
     SensorLink->Owner = this;
     in.search_name("DoorName");
     n = in.get_name();
     if(strcmp(n,"None")){
         DoorName = new char[strlen(n) + 1];
         strcpy(DoorName,n);
         pLink = NULL;
     }else DoorName = NULL;
     Enable = 1;
     Type = EngineTypeList::ITEM_GENERATOR;
     Mode = EngineModeList::WAIT;
     if(CurrentWorld == WORLD_FOSTRAL || CurrentWorld == WORLD_GLORX){
         for(i = 0;i < MAX_TIME_SECRET;i++){
             if(!strcmp(TimeSecretName[CurrentWorld][i],MLLink->name)){
                 DeviceType = TimeSecretType[CurrentWorld][i];
                 DeviceP1 = TimeSecretData0[CurrentWorld][i];
                 DeviceP2 = TimeSecretData1[CurrentWorld][i];
                 if(!TimeSecretEnable[CurrentWorld][i])
                     Enable = 0;
             };
         };
     };
     Time = 0;
 };
References XErrorHandler::Abort(), CurrentWorld, DeviceP1, DeviceP2, DeviceType, DoorName, StaticObject::Enable, LocationEngine::Enable, ErrH, FindSensor(), Parser::get_name(), EngineTypeList::ITEM_GENERATOR, MAX_TIME_SECRET, LocationEngine::MLLink, LocationEngine::Mode, MobileLocation::name, NULL, LocationEngine::Open(), SensorDataType::Owner, pLink, Parser::search_name(), SensorLink, Time, TimeSecretData0, TimeSecretData1, TimeSecretEnable, TimeSecretName, TimeSecretType, LocationEngine::Type, EngineModeList::WAIT, WORLD_FOSTRAL, and WORLD_GLORX.
Quant()
void ItemGenerator::Quant (void) virtual
Reimplemented from LocationEngine.
 {
     int i;
     if(Mode == EngineModeList::WAIT){
         if(pLink->Mode != EngineModeList::WAIT){
             Time = ActiveTime;
             Mode = EngineModeList::OPEN;
         };
     }else{
         Time--;
         if(Time == 0){
             addDevice(SensorLink->R_curr.x,SensorLink->R_curr.y,SensorLink->R_curr.z,DeviceType,DeviceP1,DeviceP2,NULL);
             if(CurrentWorld == WORLD_FOSTRAL || CurrentWorld == WORLD_GLORX){
                 for(i = 0;i < MAX_TIME_SECRET;i++){
                     if(!strcmp(TimeSecretName[CurrentWorld][i],MLLink->name) && TimeSecretEnable[CurrentWorld][i]){
                         TimeSecretEnable[CurrentWorld][i] = 0;
                         break;
                     };
                 };
             };
         };
     };
 };
References LocationEngine::ActiveTime, addDevice(), CurrentWorld, DeviceP1, DeviceP2, DeviceType, MAX_TIME_SECRET, LocationEngine::MLLink, LocationEngine::Mode, MobileLocation::name, NULL, EngineModeList::OPEN, pLink, GeneralObject::R_curr, SensorLink, Time, TimeSecretEnable, TimeSecretName, EngineModeList::WAIT, WORLD_FOSTRAL, WORLD_GLORX, Vector::x, Vector::y, and Vector::z.
Member Data Documentation
DeviceP1
int ItemGenerator::DeviceP1
Referenced by Open(), and Quant().
DeviceP2
int ItemGenerator::DeviceP2
Referenced by Open(), and Quant().
DeviceType
int ItemGenerator::DeviceType
Referenced by Open(), and Quant().
DoorName
char* ItemGenerator::DoorName
Referenced by Close(), Link(), and Open().
pLink
LocationEngine* ItemGenerator::pLink
Referenced by Link(), Open(), and Quant().
SensorLink
SensorDataType* ItemGenerator::SensorLink
Referenced by Open(), and Quant().
Time
int ItemGenerator::Time
Referenced by Open(), and Quant().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp