Vangers: DeformObject Struct Reference
DeformObject Struct Reference
#include <effect.h>
Public Member Functions
void Init (StorageType *s)
void Quant (void)
void DrawQuant (void)
void CreateDeform (const Vector &v, char _fl, WaveProcess *p)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Member Functions inherited from GeneralObject
virtual void Touch (GeneralObject *p)
Public Attributes
char FullFlag
int Offset
WaveProcess * wProcess
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Detailed Description
Member Function Documentation
CreateDeform()
void DeformObject::CreateDeform (const Vector & v, char _fl, WaveProcess * p)
 {
     R_curr = v;
 //  cycleTor(R_curr.x,R_curr.y);
     R_curr.x = XCYCL(R_curr.x);
     R_curr.y = YCYCL(R_curr.y);
     Status = 0;
     GetVisible();
     Offset = 0;
     wProcess = p;
     MapLevel = 1;
     FullFlag = _fl;
     radius = (wProcess->sx >  wProcess->sy) ? wProcess->sx : wProcess->sy;
     GetVisible();
 };
References FullFlag, BaseObject::MapLevel, Offset, GeneralObject::R_curr, BaseObject::radius, GeneralObject::Status, WaveProcess::sx, WaveProcess::sy, wProcess, Vector::x, XCYCL, Vector::y, and YCYCL.
Referenced by EffectDispatcher::CreateDeform().
DrawQuant()
void DeformObject::DrawQuant (void)
 {
     int tx,ty;
     G2L(R_curr.x,R_curr.y,tx,ty);
     wProcess->Deform(tx,ty,Offset,FullFlag);
 };
References WaveProcess::Deform(), FullFlag, G2L(), Offset, GeneralObject::R_curr, wProcess, Vector::x, and Vector::y.
Init()
void DeformObject::Init (StorageType * s)
 {
     BaseObject::Init(s);
     ID = ID_DEFORM;
 };
References GeneralObject::ID, and ID_DEFORM.
Quant()
void DeformObject::Quant (void)
 {
     GetVisible();
     if(wProcess->CheckOffset(Offset) || Visibility == UNVISIBLE) Status |= SOBJ_DISCONNECT;
 };
References WaveProcess::CheckOffset(), Offset, SOBJ_DISCONNECT, GeneralObject::Status, UNVISIBLE, BaseObject::Visibility, and wProcess.
Member Data Documentation
FullFlag
char DeformObject::FullFlag
Referenced by CreateDeform(), and DrawQuant().
Offset
int DeformObject::Offset
Referenced by CreateDeform(), DrawQuant(), and Quant().
wProcess
WaveProcess* DeformObject::wProcess
Referenced by CreateDeform(), DrawQuant(), and Quant().
The documentation for this struct was generated from the following files:
src/units/effect.h
src/units/effect.cpp