Vangers: JumpBallObject Struct Reference
JumpBallObject Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void Quant (void)
void DrawQuant (void)
void CreateBullet (GunSlot *p, WorldBulletTemplate *n)
void Touch (GeneralObject *p)
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
virtual int test_objects_collision ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Attributes
int DataID
int Mode
int Power
int DeltaPower
int CraterType
VangerUnit * Owner
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Detailed Description
Member Function Documentation
CreateBullet()
void JumpBallObject::CreateBullet (GunSlot * p, WorldBulletTemplate * n)
 {
     Vector vCheck;
     R_prev = R_curr = p->vFire;
     Status = 0;
     DataID = n->ID;
     Object::operator = (ModelD.ActiveModel(n->ShowType));
     cycleTor(R_curr.x,R_curr.y);
     set_active(0);
     set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
     GetVisible();
     Power = n->Power;
     DeltaPower = n->DeltaPower;
     Mode = n->TargetMode;
     CraterType = n->CraterType;
     Owner = p->Owner;
     archimedean = 0;
     if(Mode == BULLET_TARGET_MODE::CONTROL){
         vCheck = Vector(-(n->Speed),0,0)*DBM((int)(PI/4 - RND(PI/2)),Z_AXIS);
         vCheck *= p->mFire;
         vCheck *= n->LifeTime + Owner->Speed;
         vCheck /= n->Speed;
         precise_impulse(R_curr,XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y));
         set_body_color(COLORS_IDS::MATERIAL_5);
     }else{
         vCheck = Vector(n->Speed,0,0)*p->mFire;
         vCheck *= n->LifeTime + Owner->Speed;
         vCheck /= n->Speed;
         precise_impulse(R_curr,XCYCL(R_curr.x + vCheck.x),YCYCL(R_curr.y + vCheck.y));
     };
 };
References ModelDispatcher::ActiveModel(), Object::archimedean, BULLET_TARGET_MODE::CONTROL, BulletControlType::CraterType, CraterType, cycleTor(), DataID, BulletControlType::DeltaPower, DeltaPower, WorldBulletTemplate::ID, WorldBulletTemplate::LifeTime, COLORS_IDS::MATERIAL_5, GunSlot::mFire, Mode, ModelD, Object::operator=(), Owner, GunSlot::Owner, PI, BulletControlType::Power, Power, Object::precise_impulse(), RND(), Object::set_3D(), SET_3D_DIRECT_PLACE, Object::set_active(), Object::set_body_color(), BulletControlType::ShowType, BulletControlType::Speed, ActionUnit::Speed, BulletControlType::TargetMode, GunSlot::vFire, Vector::x, XCYCL, Vector::y, YCYCL, and Z_AXIS.
DrawQuant()
void JumpBallObject::DrawQuant (void)
 {
     draw();
 };
References Object::draw().
Init()
void JumpBallObject::Init (void)
 {
     BaseObject::Init();
     ID = ID_JUMPBALL;
     Status = SOBJ_DISCONNECT;
 };
References Object::ID, ID_JUMPBALL, and SOBJ_DISCONNECT.
Referenced by JumpBallList::CreateBall().
Quant()
void JumpBallObject::Quant (void)
 {
     char t;
     int y0,y1,i,l;
     Vector vCheck;
     StaticObject* st;
     VangerFunctionType* g;
     t = Visibility;
     GetVisible();
     if(Power > DeltaPower)
         Power -= DeltaPower;
     if(Visibility == VISIBLE){
         g = ActD.fTail;
         while(g){
             if(g->ID == PROTRACTOR_PALLADIUM){
                 vCheck = Vector(getDistX(R_curr.x,g->vR.x),getDistY(R_curr.y,g->vR.y),R_curr.z - g->vR.z);
                 l = vCheck.vabs();
                 if(l < PALLADIUM_RADIUS)
                     impulse(vCheck,30 * (PALLADIUM_RADIUS - l) / PALLADIUM_RADIUS,0);
                 break;
             };
             g = g->Next;
         };
         analysis();
         cycleTor(R_curr.x,R_curr.y);
         if(dynamic_state & GROUND_COLLISION){
             y0 = R_curr.y - EXPLOSION_BARELL_RADIUS;
             y1 = R_curr.y + EXPLOSION_BARELL_RADIUS;
             i = FindFirstStatic(y0,y1,(StaticObject**)TntSortedData,TntTableSize);
             if(i > -1){
                 do{
                     st = TntSortedData[i];
                     if(st->Enable){
                         vCheck.x = getDistX(st->R_curr.x,R_curr.x);
 //                      l = radius + st->radius;
                         l = radius + EXPLOSION_BARELL_RADIUS;
                         if(abs(vCheck.x) < l){
                             vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                             vCheck.z = st->R_curr.z - R_curr.z;
                             if(vCheck.abs2() < l*l){
                                 st->Touch(this);
                                 Touch(st);
                                 if(Owner && Owner == ActD.Active)
                                     uvsCheckKronIventTabuTask(UVS_KRON_EVENT::GRIB,1);
                             };
                         };
                     };
                     i++;
                 }while(i < TntTableSize && TntSortedData[i]->R_curr.y < y1);
             };
             Status |= SOBJ_DISCONNECT;
             if(Mode == BULLET_TARGET_MODE::CONTROL) CreateDestroyEffect(R_curr,MAP_POINT_CRATER03,DT_DEFORM02,DEFORM_WATER_ONLY,-1,DT_FIRE_BALL02);
             else CreateDestroyEffect(R_curr,MAP_POINT_CRATER10,DT_DEFORM02,DEFORM_WATER_ONLY,EFF_EXPLOSION03,-1);
             if(ActD.Active)
                 SOUND_EXPLOSION_CRUSTER(getDistX(ActD.Active->R_curr.x,R_curr.x));
         };
     }else Status |= SOBJ_DISCONNECT;
 };
References Vector::abs2(), ActD, ActionDispatcher::Active, Object::analysis(), BULLET_TARGET_MODE::CONTROL, CreateDestroyEffect(), cycleTor(), DEFORM_WATER_ONLY, DeltaPower, DT_DEFORM02, DT_FIRE_BALL02, EFF_EXPLOSION03, StaticObject::Enable, EXPLOSION_BARELL_RADIUS, FindFirstStatic(), ActionDispatcher::fTail, g, getDistX(), getDistY(), UVS_KRON_EVENT::GRIB, GROUND_COLLISION, Object::impulse(), Mode, Owner, PALLADIUM_RADIUS, Power, PROTRACTOR_PALLADIUM, GeneralObject::R_curr, Object::radius, SOBJ_DISCONNECT, SOUND_EXPLOSION_CRUSTER, TntSortedData, TntTableSize, GeneralObject::Touch(), Touch(), uvsCheckKronIventTabuTask(), Vector::vabs(), VISIBLE, Object::x, Vector::x, Vector::y, and Vector::z.
Touch()
void JumpBallObject::Touch (GeneralObject * p)
 {
     if(p->ID == ID_VANGER){
         if(((VangerUnit*)(p))->BeebonationFlag) return;
         ((VangerUnit*)(p))->BulletCollision(Power,Owner);
         Status |= SOBJ_DISCONNECT;
         if(ActD.Active)
             SOUND_BARREL_DESTROY(getDistX(ActD.Active->R_curr.x,R_curr.x))
         if(Mode == BULLET_TARGET_MODE::CONTROL){
             EffD.CreateExplosion(R_curr + Vector(0,0,20),EFF_EXPLOSION02);
             ((VangerUnit*)(p))->impulse(Vector(32 - RND(64),32 - RND(64),RND(64)),8 + RND(15),20);
             if(ActD.Active)
                 SOUND_BARREL_DESTROY(getDistX(ActD.Active->R_curr.x,R_curr.x))
         }else{
             EffD.CreateExplosion(R_curr + Vector(0,0,20),EFF_EXPLOSION03);
             if(ActD.Active)
                 SOUND_EXPLOSION_CRUSTER(getDistX(ActD.Active->R_curr.x,R_curr.x));
         };
     };
 };
References ActD, ActionDispatcher::Active, BULLET_TARGET_MODE::CONTROL, EffectDispatcher::CreateExplosion(), EFF_EXPLOSION02, EFF_EXPLOSION03, EffD, getDistX(), GeneralObject::ID, ID_VANGER, Object::impulse(), Mode, Owner, Power, RND(), SOBJ_DISCONNECT, SOUND_BARREL_DESTROY, SOUND_EXPLOSION_CRUSTER, and Object::x.
Referenced by Quant().
Member Data Documentation
CraterType
int JumpBallObject::CraterType
Referenced by CreateBullet().
DataID
int JumpBallObject::DataID
Referenced by CreateBullet().
DeltaPower
int JumpBallObject::DeltaPower
Referenced by CreateBullet(), and Quant().
Mode
int JumpBallObject::Mode
Referenced by CreateBullet(), Quant(), and Touch().
Owner
VangerUnit* JumpBallObject::Owner
Referenced by CreateBullet(), Quant(), and Touch().
Power
int JumpBallObject::Power
Referenced by CreateBullet(), Quant(), and Touch().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp