Vangers: LandSlideEngine Struct Reference
LandSlideEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Touch (GeneralObject *obj, SensorDataType *p)
Public Member Functions inherited from LocationEngine
virtual void Close (void)
virtual void Quant (void)
virtual void Link (void)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
int LifeTime
int cX [4]
int cY [4]
SensorDataType * SignalSensor
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Open()
void LandSlideEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     SensorDataType* p;
     char* n;
     int i;
     LocationEngine::Open(in);
     for(i = 0;i < 4;i++){
         in.search_name("BorderSensorName");
         n = in.get_name();
         p = NULL;
         p = FindSensor(n);
         if(!p)
             ErrH.Abort("Bad Find Sensor");
         p->Enable = 0;
         p->Owner = NULL;
         cX[i] = p->R_curr.x;
         cY[i] = p->R_curr.y;
     };
     in.search_name("SignalSensorName");
     n = in.get_name();
     SignalSensor = NULL;
     SignalSensor = FindSensor(n);
     if(!SignalSensor)
         ErrH.Abort("Bad Find Sensor");
     SignalSensor->Enable = 1;
     SignalSensor->Owner = this;
     in.search_name("LifeTime");
     LifeTime = in.get_int();
     Type = EngineTypeList::LAND_SLIDE;
     Mode = EngineModeList::WAIT;
 };
References XErrorHandler::Abort(), cX, cY, StaticObject::Enable, ErrH, FindSensor(), Parser::get_int(), Parser::get_name(), EngineTypeList::LAND_SLIDE, LifeTime, LocationEngine::Mode, NULL, LocationEngine::Open(), SensorDataType::Owner, GeneralObject::R_curr, Parser::search_name(), SignalSensor, LocationEngine::Type, EngineModeList::WAIT, Vector::x, and Vector::y.
Touch()
void LandSlideEngine::Touch (GeneralObject * obj, SensorDataType * p) virtual
Reimplemented from LocationEngine.
 {
     if(Mode == EngineModeList::WAIT){
         Mode = EngineModeList::OPEN;
         MapD.CreateLandSlide(cX,cY,LifeTime);
     };
 };
References cX, cY, LifeTime, MapD, LocationEngine::Mode, EngineModeList::OPEN, and EngineModeList::WAIT.
Member Data Documentation
cX
int LandSlideEngine::cX[4]
Referenced by Open(), and Touch().
cY
int LandSlideEngine::cY[4]
Referenced by Open(), and Touch().
LifeTime
int LandSlideEngine::LifeTime
Referenced by Open(), and Touch().
SignalSensor
SensorDataType* LandSlideEngine::SignalSensor
Referenced by Open().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp