Vangers: NetRndType Struct Reference
NetRndType Struct Reference
#include <network.h>
Public Member Functions
void Init (unsigned d)
NetRndType ()
unsigned Get (unsigned m)
Public Attributes
unsigned NetRndVal
Detailed Description
Constructor & Destructor Documentation
NetRndType()
NetRndType::NetRndType () inline
 { NetRndVal=0; }
References NetRndVal.
Member Function Documentation
Get()
unsigned NetRndType::Get (unsigned m) inline
{
         NetRndVal ^= NetRndVal >> 3;
         NetRndVal ^= NetRndVal << 28;
         NetRndVal &= 0x7FFFFFFF;
         if(!m) return 0;
         return NetRndVal%m;
     };
References NetRndVal.
Referenced by HordeList::Init(), HordeSourceList::Init(), and FishWarriorList::Init().
Init()
void NetRndType::Init (unsigned d) inline
 { NetRndVal=d; }
References NetRndVal.
Member Data Documentation
NetRndVal
unsigned NetRndType::NetRndVal
Referenced by Get(), Init(), and NetRndType().
The documentation for this struct was generated from the following file:
src/network.h