Vangers: MemoryStorageType Struct Reference
MemoryStorageType Struct Reference
#include <hobj.h>
Public Member Functions
void Init (int mElement, int eSize)
void Free (void)
GeneralObject * GetPoint (void)
void PutPoint (GeneralObject *p)
Public Attributes
int NumCluster
int ElementSize
int MaxElement
StorageClusterType * Tail
Detailed Description
Member Function Documentation
Free()
void MemoryStorageType::Free (void)
 {
     StorageClusterType* p;
     StorageClusterType* pn;
     p = Tail;
     while(p){
         pn = p->Next;
         p->Free();
         delete p;
         p = pn;
     };
 };
References StorageClusterType::Free(), StorageClusterType::Next, and Tail.
GetPoint()
GeneralObject * MemoryStorageType::GetPoint (void)
 {
     StorageClusterType* g;
     StorageClusterType* n;
     g = Tail;
     n = NULL;
     while(g){
         if(g->CheckSpace())
             return(g->GetPoint());
         n = g;
         g = g->Next;
     };
     if(n->Next != NULL)
         ErrH.Abort("Bad Units Heap");
     g = new StorageClusterType;
     g->Init(this);
     g->Next = NULL;
     if(n) n->Next = g;
     else ErrH.Abort("Bad Tail in Units Heap");
     return(g->GetPoint());
 };
References XErrorHandler::Abort(), ErrH, g, StorageClusterType::Next, NULL, and Tail.
Init()
void MemoryStorageType::Init (int mElement, int eSize)
 {
     StorageClusterType* p;
     NumCluster = 1;
     ElementSize = eSize;
     MaxElement = mElement;
     p = new StorageClusterType;
     p ->Init(this);
     Tail = p;
     p->Next = NULL;
 };
References ElementSize, StorageClusterType::Init(), MaxElement, StorageClusterType::Next, NULL, NumCluster, and Tail.
PutPoint()
void MemoryStorageType::PutPoint (GeneralObject * p)
 {
     p->Cluster->PutPoint(p);
     if(p->Cluster->CheckSpace() == 2 && p->Cluster != Tail){
         p->Cluster->Free();
         delete p->Cluster;
     };
 };
References StorageClusterType::CheckSpace(), GeneralObject::Cluster, StorageClusterType::Free(), StorageClusterType::PutPoint(), and Tail.
Member Data Documentation
ElementSize
int MemoryStorageType::ElementSize
Referenced by Init(), and StorageClusterType::Init().
MaxElement
int MemoryStorageType::MaxElement
Referenced by Init(), and StorageClusterType::Init().
NumCluster
int MemoryStorageType::NumCluster
Referenced by Init().
Tail
StorageClusterType* MemoryStorageType::Tail
Referenced by Free(), GetPoint(), Init(), and PutPoint().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp