Vangers: aciML_Dispatcher Struct Reference
aciML_Dispatcher Struct Reference
#include <mlstruct.h>
Public Member Functions
void add_data_set (aciML_DataSet *p)
void init_data_set (int id)
void event_quant (void)
void active_event_quant (void)
void rnd_event_quant (void)
void inc_events_timer (void)
int drop_channel_events (int channel, int pr)
int check_channel_events (int ch)
void clear_events (void)
void register_names (void)
void startup (void)
void shutdown (void)
void redraw_items (void)
void quant (void)
void key_trap (int key, int mode=-1)
int isEventActive (int key, int mode)
aciML_Event * getEvent (int key, int mode)
aciML_EventSeq * getEventSeq (int id)
void send_event (int cd, int d0=0, int d1=0)
void add_flush (int x, int y, int sx, int sy)
void flush (int mode=1)
void init (void)
void finit (void)
aciML_Dispatcher (void)
~aciML_Dispatcher (void)
Public Attributes
int flags
iList * ml_data
iList * ml_data_sets
aciML_DataSet * curDataSet
aciML_EventSeqLine ** SeqList
int timer
int startup_timer
int shutdown_timer
aciML_EventLine * event_line
aciML_FlushLine * flush_line
Detailed Description
Constructor & Destructor Documentation
aciML_Dispatcher()
aciML_Dispatcher::aciML_Dispatcher (void)
 {
     int i;
     flags = 0;
     ml_data_sets = new iList;
     SeqList = new aciML_EventSeqLine*[AML_MAX_SEQ_LINE_ID];
     for(i = 0; i < AML_MAX_SEQ_LINE_ID; i ++)
         SeqList[i] = new aciML_EventSeqLine;
     timer = 0;
     startup_timer = shutdown_timer = 0;
     event_line = new aciML_EventLine;
     flush_line = new aciML_FlushLine;
 }
References AML_MAX_SEQ_LINE_ID, event_line, flags, flush_line, ml_data_sets, SeqList, shutdown_timer, startup_timer, and timer.
~aciML_Dispatcher()
aciML_Dispatcher::~aciML_Dispatcher (void)
 {
     int i;
     aciML_DataSet* p,*p1;
     for(i = 0; i < AML_MAX_SEQ_LINE_ID; i ++)
         delete SeqList[i];
     delete[] SeqList;
     p = (aciML_DataSet*)ml_data_sets -> last;
     while(p){
         p1 = (aciML_DataSet*)p -> prev;
         delete p;
         p = p1;
     }
     delete ml_data_sets;
     delete event_line;
     delete flush_line;
 }
References AML_MAX_SEQ_LINE_ID, event_line, flush_line, ml_data_sets, prev, and SeqList.
Member Function Documentation
active_event_quant()
void aciML_Dispatcher::active_event_quant (void)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         p -> active_event_quant();
         p = (aciML_Data*)p -> prev;
     }
 }
References ml_data, and prev.
Referenced by quant().
add_data_set()
void aciML_Dispatcher::add_data_set (aciML_DataSet * p)
 {
     ml_data_sets -> connect((iListElement*)p);
 }
References ml_data_sets.
add_flush()
void aciML_Dispatcher::add_flush (int x, int y, int sx, int sy)
 {
     flush_line -> put(x,y,sx,sy);
 }
References flush_line.
check_channel_events()
int aciML_Dispatcher::check_channel_events (int ch)
 {
     int ret = 0;
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         ret = p -> check_channel_events(ch);
         if(ret) return ret;
         p = (aciML_Data*)p -> prev;
     }
     return 0;
 }
References ml_data, and prev.
clear_events()
void aciML_Dispatcher::clear_events (void)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         p -> flags &= ~AML_DISABLED_ML;
         p -> clear_events();
         p = (aciML_Data*)p -> prev;
     }
     event_line -> clear();
 }
References AML_DISABLED_ML, event_line, flags, ml_data, and prev.
Referenced by init(), and quant().
drop_channel_events()
int aciML_Dispatcher::drop_channel_events (int channel, int pr)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         if(!p -> drop_events(channel,pr)) return 0;
         p = (aciML_Data*)p -> prev;
     }
     return 1;
 }
References ml_data, and prev.
event_quant()
void aciML_Dispatcher::event_quant (void)
 {
     aciML_EventCommand* ev;
     while(event_line -> size){
         ev = event_line -> get();
 #ifdef AML_DEBUG
         logFile < "\r\n" <= XRec.frameCount < "\t" <= ev -> code < "\t" <= ev -> data0 < "\t" <= ev -> data1;
 #endif
 #ifndef _ACI_NO_SHOP_ANIMATION_
         switch(ev -> code){
             case AML_NEXT_PHRASE:
                 aciNextPhrase();
                 break;
             case AML_EXIT:
                 flags |= AML_PAUSE;
                 aciExitShop();
                 break;
             case AML_DISABLE_ML:
                 curDataSet -> disable_ml(ev -> data0);
                 break;
             case AML_ENABLE_ML:
                 curDataSet -> enable_ml(ev -> data0);
                 break;
             case AML_CLOSE_SPEECH:
                 aciEndSpeech = 1;
                 break;
             case AML_BREATH_ON:
                 aciBreathFlag = 1;
                 break;
             case AML_BREATH_OFF:
                 aciBreathFlag = 0;
                 break;
             case AML_LOCK:
                 LockIML(ev -> data0);
                 break;
             case AML_UNLOCK:
                 UnlockIML(ev -> data0);
                 break;
             case AML_CLOSE_ML:
                 aciML_Close(ev -> data0,ev -> data1);
                 break;
             case AML_INVERT_PHASE:
                 aciML_Invert(ev -> data0,ev -> data1);
                 break;
             case AML_SHUTDOWN_EV:
                 shutdown();
                 break;
             case AML_PAUSE_ALL:
                 PauseIMLall();
                 flags |= AML_PAUSE;
                 break;
             case AML_RESUME_ALL:
                 ResumeIMLall();
                 flags &= ~AML_PAUSE;
                 break;
             case AML_KEY_TRAP:
                 key_trap(ev -> data1,ev -> data0);
                 break;
             case AML_SEND2ACTINT:
                 aci_SendEvent(ev -> data0 + ACI_MAX_EVENT,ev -> data1);
                 break;
             case AML_CLEAR_QUEUE:
                 CleanQueueIML(ev -> data0);
                 break;
             case AML_ADD_IN_CH_QUEUE:
                 if(!isInQueueIML(ev -> data0,ev -> data1) && !isActiveIML(ev -> data1)){
                     HandlerIML(AML_PUT_IN_CH_QUEUE,ev -> data0,ev -> data1);
                 }
                 break;
             case AML_START_SOUND:
                 iSoundQuant(ev -> data0);
                 break;
             case AML_PUT_SEQUENCE:
                 SeqList[ev -> data0] -> putSeq(curDataSet -> getSeq(ev -> data1));
                 break;
             default:
                 HandlerIML(ev -> code,ev -> data0,ev -> data1);
                 break;
         }
 #endif
     }
 }
References ACI_MAX_EVENT, aci_SendEvent(), aciBreathFlag, aciEndSpeech, aciExitShop(), aciML_Close(), aciML_Invert(), aciNextPhrase(), AML_ADD_IN_CH_QUEUE, AML_BREATH_OFF, AML_BREATH_ON, AML_CLEAR_QUEUE, AML_CLOSE_ML, AML_CLOSE_SPEECH, AML_DISABLE_ML, AML_ENABLE_ML, AML_EXIT, AML_INVERT_PHASE, AML_KEY_TRAP, AML_LOCK, AML_NEXT_PHRASE, AML_PAUSE, AML_PAUSE_ALL, AML_PUT_IN_CH_QUEUE, AML_PUT_SEQUENCE, AML_RESUME_ALL, AML_SEND2ACTINT, AML_SHUTDOWN_EV, AML_START_SOUND, AML_UNLOCK, CleanQueueIML(), curDataSet, event_line, flags, XRecorder::frameCount, HandlerIML(), isActiveIML(), isInQueueIML(), iSoundQuant(), key_trap(), LockIML(), PauseIMLall(), ResumeIMLall(), SeqList, shutdown(), UnlockIML(), and XRec.
Referenced by quant().
finit()
void aciML_Dispatcher::finit (void)
 {
     ReleaseIML();
     curDataSet -> finit_items();
 }
References curDataSet, and ReleaseIML().
flush()
void aciML_Dispatcher::flush (int mode = 1)
 {
     aciML_FlushData* p;
     while(flush_line -> size){
         p = flush_line -> get();
         put_map(p -> PosX,p -> PosY,p -> SizeX,p -> SizeY);
 //        if(mode) XGR_Flush(p -> PosX,p -> PosY,p -> SizeX,p -> SizeY);
     }
     //if(mode)
     //  XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
 }
References flush_line, and put_map().
getEvent()
aciML_Event * aciML_Dispatcher::getEvent (int key, int mode)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     aciML_Event* ev;
     while(p){
         ev = (aciML_Event*)p -> event_list -> last;
         while(ev){
             if(mode == AML_STARTUP_MODE || mode == AML_SHUTDOWN_MODE){
                 if(key == ev -> data) return ev;
             }
             else {
                 if(ev -> check_key(key)) return ev;
             }
             ev = (aciML_Event*)ev -> prev;
         }
         p = (aciML_Data*)p -> prev;
     }
     return NULL;
 }
References AML_SHUTDOWN_MODE, AML_STARTUP_MODE, key(), ml_data, NULL, and prev.
getEventSeq()
aciML_EventSeq* aciML_Dispatcher::getEventSeq (int id) inline
 { return curDataSet -> getSeq(id); }
References curDataSet.
inc_events_timer()
void aciML_Dispatcher::inc_events_timer (void)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         p -> inc_events_timer();
         p = (aciML_Data*)p -> prev;
     }
 }
References ml_data, and prev.
Referenced by quant().
init()
void aciML_Dispatcher::init (void)
 {
     StartupIML();
     register_names();
     InitIML();
     clear_events();
     curDataSet -> init_items();
 }
References clear_events(), curDataSet, InitIML(), register_names(), and StartupIML().
init_data_set()
void aciML_Dispatcher::init_data_set (int id)
 {
     aciML_DataSet* p = (aciML_DataSet*)ml_data_sets -> last;
     while(p){
         if(p -> ID == id){
             ml_data = p -> ml_data;
             curDataSet = p;
             return;
         }
         p = (aciML_DataSet*)p -> prev;
     }
 }
References curDataSet, ml_data, ml_data_sets, and prev.
isEventActive()
int aciML_Dispatcher::isEventActive (int key, int mode)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         if(p -> isEventActive(key,mode)) return 1;
         p = (aciML_Data*)p -> prev;
     }
     return 0;
 }
References key(), ml_data, and prev.
key_trap()
void aciML_Dispatcher::key_trap (int key, int mode = -1)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     if(mode == -1){
         mode = AML_KEY;
         if(flags & AML_STARTUP_MODE){
             mode = AML_STARTUP;
         }
         else {
             if(flags & AML_SHUTDOWN_MODE)
                 mode = AML_SHUTDOWN;
         }
     }
     while(p){
         p -> key_trap(k,mode);
         p = (aciML_Data*)p -> prev;
     }
     if(!iScreenOffs && mode == AML_KEY && (k == iMOUSE_LEFT_PRESS_CODE || k == iMOUSE_RIGHT_PRESS_CODE)){
         curDataSet -> items_keytrap(iMouseX,iMouseY);
     }
 }
References AML_KEY, AML_SHUTDOWN, AML_SHUTDOWN_MODE, AML_STARTUP, AML_STARTUP_MODE, curDataSet, flags, iMOUSE_LEFT_PRESS_CODE, iMOUSE_RIGHT_PRESS_CODE, iMouseX, iMouseY, iScreenOffs, ml_data, and prev.
Referenced by event_quant(), and quant().
quant()
void aciML_Dispatcher::quant (void)
 {
     int i,log;
     if(flags & AML_PAUSE) return;
     if(flags & AML_STARTUP_MODE){
         key_trap(timer,AML_STARTUP);
     }
     else {
         if(flags & AML_SHUTDOWN_MODE){
             key_trap(timer,AML_SHUTDOWN);
         }
         else {
             if(!iScreenOffs && aciML_ToolzerON){
                 ToolzerQuant(iMouseX,iMouseY);
                 aScrDisp -> aml_check_redraw(iMouseX,iMouseY);
             }
         }
     }
     for(i = 0; i < AML_MAX_SEQ_LINE_ID; i ++)
         SeqList[i] -> firstQuant();
     rnd_event_quant();
     active_event_quant();
     event_quant();
     log = QuantIML();
     inc_events_timer();
     for(i = 0; i < AML_MAX_SEQ_LINE_ID; i ++)
         SeqList[i] -> secondQuant();
     timer ++;
     if(flags & AML_STARTUP_MODE){
         if(timer >= startup_timer){
             flags ^= AML_STARTUP_MODE;
             timer = 0;
         }
     }
     else {
         if(flags & AML_SHUTDOWN_MODE){
             if(timer >= shutdown_timer || (!log && timer >= AML_MIN_SHUTDOWN_TIMER)){
                 aciML_ShutdownCount ++;
             }
             if(aciML_ShutdownCount >= AML_SHUTDOWN_DELTA){
                 flags ^= AML_SHUTDOWN_MODE;
                 flags |= AML_END_SHUTDOWN | AML_PAUSE;
                 timer = 0;
                 clear_events();
 #ifdef AML_DEBUG
                 logFile.close();
 #endif
             }
         }
     }
 }
References aciML_ShutdownCount, aciML_ToolzerON, active_event_quant(), AML_END_SHUTDOWN, AML_MAX_SEQ_LINE_ID, AML_MIN_SHUTDOWN_TIMER, AML_PAUSE, AML_SHUTDOWN, AML_SHUTDOWN_DELTA, AML_SHUTDOWN_MODE, AML_STARTUP, AML_STARTUP_MODE, aScrDisp, clear_events(), event_quant(), flags, iMouseX, iMouseY, inc_events_timer(), iScreenOffs, key_trap(), QuantIML(), rnd_event_quant(), SeqList, shutdown_timer, startup_timer, timer, and ToolzerQuant().
redraw_items()
void aciML_Dispatcher::redraw_items (void)
 {
     curDataSet -> redraw_items();
 }
References curDataSet.
register_names()
void aciML_Dispatcher::register_names (void)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         RegisterIML(p -> name,p -> ID,p -> ChannelID);
         p = (aciML_Data*)p -> prev;
     }
 }
References ml_data, prev, and RegisterIML().
Referenced by init().
rnd_event_quant()
void aciML_Dispatcher::rnd_event_quant (void)
 {
     aciML_Data* p = (aciML_Data*)ml_data -> last;
     while(p){
         p -> rnd_event_quant();
         p = (aciML_Data*)p -> prev;
     }
 }
References ml_data, and prev.
Referenced by quant().
send_event()
void aciML_Dispatcher::send_event (int cd, int d0 = 0, int d1 = 0)
 {
     event_line -> put(cd,d0,d1);
 }
References event_line.
shutdown()
void aciML_Dispatcher::shutdown (void)
 {
     aciML_ShutdownCount = 0;
     flags |= AML_SHUTDOWN_MODE;
     flags &= ~AML_STARTUP_MODE;
     timer = 0;
 }
References aciML_ShutdownCount, AML_SHUTDOWN_MODE, AML_STARTUP_MODE, flags, and timer.
Referenced by event_quant().
startup()
void aciML_Dispatcher::startup (void)
 {
     int i;
     flags |= AML_STARTUP_MODE;
     aciML_ToolzerON = 0;
     timer = 0;
     if(!ml_data -> Size)
         aci_SendEvent(EV_NEXT_PHRASE);
     for(i = 0; i < AML_MAX_SEQ_LINE_ID; i ++)
         SeqList[i] -> clear();
     flags &= ~AML_PAUSE;
 #ifdef AML_DEBUG
     if(XRec.flags & XRC_PLAY_MODE)
         aciML_logFileName = aciML_logFileNameR;
     else
         aciML_logFileName = aciML_logFileNameW;
     if(aciML_logFile){
         logFile.open(aciML_logFileName,XS_OUT | XS_APPEND | XS_NOREPLACE);
     }
     else {
         logFile.open(aciML_logFileName,XS_OUT);
         aciML_logFile = 1;
     }
 #endif
 }
References aci_SendEvent(), aciML_ToolzerON, AML_MAX_SEQ_LINE_ID, AML_PAUSE, AML_STARTUP_MODE, EV_NEXT_PHRASE, XRecorder::flags, flags, ml_data, SeqList, timer, XRC_PLAY_MODE, XRec, XS_APPEND, XS_NOREPLACE, and XS_OUT.
Member Data Documentation
curDataSet
aciML_DataSet* aciML_Dispatcher::curDataSet
Referenced by event_quant(), finit(), getEventSeq(), init(), init_data_set(), key_trap(), and redraw_items().
event_line
aciML_EventLine* aciML_Dispatcher::event_line
Referenced by aciML_Dispatcher(), clear_events(), event_quant(), send_event(), and ~aciML_Dispatcher().
flags
int aciML_Dispatcher::flags
Referenced by aciML_Dispatcher(), clear_events(), event_quant(), key_trap(), quant(), shutdown(), and startup().
flush_line
aciML_FlushLine* aciML_Dispatcher::flush_line
Referenced by aciML_Dispatcher(), add_flush(), flush(), and ~aciML_Dispatcher().
ml_data
iList* aciML_Dispatcher::ml_data
Referenced by active_event_quant(), check_channel_events(), clear_events(), drop_channel_events(), getEvent(), inc_events_timer(), init_data_set(), isEventActive(), key_trap(), register_names(), rnd_event_quant(), and startup().
ml_data_sets
iList* aciML_Dispatcher::ml_data_sets
Referenced by aciML_Dispatcher(), add_data_set(), init_data_set(), and ~aciML_Dispatcher().
SeqList
aciML_EventSeqLine** aciML_Dispatcher::SeqList
Referenced by aciML_Dispatcher(), event_quant(), quant(), startup(), and ~aciML_Dispatcher().
shutdown_timer
int aciML_Dispatcher::shutdown_timer
Referenced by aciML_Dispatcher(), and quant().
startup_timer
int aciML_Dispatcher::startup_timer
Referenced by aciML_Dispatcher(), and quant().
timer
int aciML_Dispatcher::timer
Referenced by aciML_Dispatcher(), quant(), shutdown(), and startup().
The documentation for this struct was generated from the following files:
src/actint/mlstruct.h
src/actint/actintml.cpp