Vangers: aciML_EventSeqLine Struct Reference
aciML_EventSeqLine Struct Reference
#include <mlstruct.h>
Public Member Functions
void clear (void)
void put (aciML_Event *p)
void putSeq (aciML_EventSeq *p)
aciML_Event * get (void)
int dropEvents (int level, int channel)
void firstQuant (void)
void secondQuant (void)
aciML_EventSeqLine (void)
~aciML_EventSeqLine (void)
Public Attributes
int size
int first_index
int last_index
int flags
aciML_Event ** table
Detailed Description
Constructor & Destructor Documentation
aciML_EventSeqLine()
aciML_EventSeqLine::aciML_EventSeqLine (void)
 {
     int i;
     table = new aciML_Event*[AML_MAX_SEQ_EVENT];
     for(i = 0; i < AML_MAX_SEQ_EVENT; i ++){
         table[i] = NULL;
     }
     flags = 0;
     clear();
 }
References AML_MAX_SEQ_EVENT, clear(), flags, NULL, and table.
~aciML_EventSeqLine()
aciML_EventSeqLine::~aciML_EventSeqLine (void)
 {
     delete table;
 }
References table.
Member Function Documentation
clear()
void aciML_EventSeqLine::clear (void)
 {
     size = 0;
     first_index = 0;
     last_index = 0;
 }
References first_index, last_index, and size.
Referenced by aciML_EventSeqLine(), and dropEvents().
dropEvents()
int aciML_EventSeqLine::dropEvents (int level, int channel)
 {
     int i,index = 0,dropFlag = 0;
     index = last_index - 1;
     if(index < 0) index = AML_MAX_SEQ_EVENT - 1;
     for(i = 0; i < size; i ++){
         if(table[index] -> ChannelID == channel && table[index] -> priority == level){
             if(!(table[index] -> flags & AML_ACTIVE_EVENT)){
                 dropFlag = 1;
                 last_index = index;
                 table[index] -> stop();
                 size --;
             }
         }
         else {
             break;
         }
         index --;
         if(index < 0) index = AML_MAX_SEQ_EVENT - 1;
     }
     if(!size) clear();
     return dropFlag;
 }
References AML_ACTIVE_EVENT, AML_MAX_SEQ_EVENT, clear(), flags, last_index, level, size, and table.
Referenced by putSeq().
firstQuant()
void aciML_EventSeqLine::firstQuant (void)
 {
     int code;
     aciML_Event* ev;
     if(!size) return;
     ev = table[first_index];
     if(!(ev -> flags & AML_ACTIVE_EVENT)){
         if(ev -> startupType == AML_KEY){
             code = ((iScanCode*)ev -> keys -> codes -> last) -> code;
             aciML_KeyTrap(code,ev -> startupType);
         }
         else
             aciML_KeyTrap(ev -> data,ev -> startupType);
         if(!(ev -> flags & AML_ACTIVE_EVENT)) get();
     }
 }
References aciML_KeyTrap(), AML_ACTIVE_EVENT, AML_KEY, first_index, flags, get(), size, and table.
get()
aciML_Event * aciML_EventSeqLine::get (void)
 {
     aciML_Event* p;
     if(size){
         p = table[first_index];
         first_index ++;
         if(first_index >= AML_MAX_SEQ_EVENT)
             first_index = 0;
         size --;
         return p;
     }
     return NULL;
 }
References AML_MAX_SEQ_EVENT, first_index, NULL, size, and table.
Referenced by firstQuant(), and secondQuant().
put()
void aciML_EventSeqLine::put (aciML_Event * p)
 {
     if(size < AML_MAX_SEQ_EVENT){
         table[last_index] = p;
         p -> flags &= ~AML_FINISHED;
         last_index ++;
         if(last_index >= AML_MAX_SEQ_EVENT)
             last_index = 0;
         size ++;
     }
     else
         ErrH.Abort("iML Event buffer overflow...");
 }
References XErrorHandler::Abort(), AML_FINISHED, AML_MAX_SEQ_EVENT, ErrH, flags, last_index, size, and table.
Referenced by putSeq().
putSeq()
void aciML_EventSeqLine::putSeq (aciML_EventSeq * p)
 {
     int i,index = 0,dropFlag = 0,level;
     index = last_index - 1;
     if(index < 0) index = AML_MAX_SEQ_EVENT - 1;
     if(!p || p -> size >= AML_MAX_SEQ_EVENT - size) return;
     for(i = 0; i < AML_MAX_DROP_EVENT; i ++){
         if(dropEvents(p -> dropLevel[i],p -> ChannelID))
             dropFlag ++;
         else
             break;
     }
     for(i = 0; i < p -> size; i ++){
         p -> SeqEvents[i] = aciML_GetEvent(p -> SeqIDs[i],p -> SeqModes[i]);
     }
     for(level = 0; level < dropFlag; level ++){
         if(!p -> dropEvents(level)) break;
     }
     for(i = 0; i < p -> size; i ++){
         if(p -> SeqEvents[i])
             put(p -> SeqEvents[i]);
     }
 }
References aciML_GetEvent(), AML_MAX_DROP_EVENT, AML_MAX_SEQ_EVENT, dropEvents(), last_index, level, put(), and size.
secondQuant()
void aciML_EventSeqLine::secondQuant (void)
 {
     aciML_Event* ev;
     if(!size) return;
     ev = table[first_index];
     if(!(ev -> flags & AML_ACTIVE_EVENT) && ev -> flags & AML_FINISHED)
         get();
 }
References AML_ACTIVE_EVENT, AML_FINISHED, first_index, flags, get(), size, and table.
Member Data Documentation
first_index
int aciML_EventSeqLine::first_index
Referenced by clear(), firstQuant(), get(), and secondQuant().
flags
int aciML_EventSeqLine::flags
Referenced by aciML_EventSeqLine(), dropEvents(), firstQuant(), put(), and secondQuant().
last_index
int aciML_EventSeqLine::last_index
Referenced by clear(), dropEvents(), put(), and putSeq().
size
int aciML_EventSeqLine::size
Referenced by clear(), dropEvents(), firstQuant(), get(), put(), putSeq(), and secondQuant().
table
aciML_Event** aciML_EventSeqLine::table
Referenced by aciML_EventSeqLine(), dropEvents(), firstQuant(), get(), put(), secondQuant(), and ~aciML_EventSeqLine().
The documentation for this struct was generated from the following files:
src/actint/mlstruct.h
src/actint/actintml.cpp