Vangers: Game Struct Reference
Game Struct Reference
#include <server.h>
Public Member Functions
Game (int ID)
~Game ()
int attach_player (Player *player)
void detach_player (Player *player)
int quant ()
void get_object_ID_offsets (OutputEventBuffer &out_buffer, int client_ID)
void put_event_for_all (int code, Player *player=0)
void process_direct_sending (Object *obj, unsigned int mask)
void get_total_list_of_players_data (OutputEventBuffer &out_buffer)
void check_global_objects (Player *player)
void process_create_globals (Player *player, Object *obj)
void process_update_globals (Player *player, Object *obj)
void process_delete_globals (Object *obj)
void process_VAN_WAR_ratings ()
void process_MECHOSOMA_ratings ()
void process_PASSEMBLOSS_ratings ()
void save_result ()
void load_result (Server *server, char *name)
Public Attributes
int ID
int client_version
unsigned int used_players_IDs
XTList< Player > players
XTList< Player > removed_players
XTList< World > worlds
XTList< Object > global_objects
unsigned int birth_time
char name [128]
ServerData data
Game * next
Game * prev
XTList< Game > * list
Detailed Description
Constructor & Destructor Documentation
Game()
Game::Game (int ID)
                  {
     Game::ID = ID;
     name[0] = 0;
     client_version = 0;
     birth_time = SDL_GetTicks();
     next = prev = 0;
     list = 0;
     used_players_IDs = 0;
 }
References birth_time, client_version, ID, list, name, next, prev, and used_players_IDs.
~Game()
Game::~Game ()
             {
 #ifdef _DEBUG
     save_result();
 #endif
     if (players.size() || removed_players.size()) {
         switch (data.GameType) {
         case VAN_WAR:
             process_VAN_WAR_ratings();
             break;
         case MECHOSOMA:
             process_MECHOSOMA_ratings();
             break;
         case PASSEMBLOSS:
             process_PASSEMBLOSS_ratings();
             break;
         }
     }
     Player *p;
     while ((p = players.first()) != 0) {
         detach_player(p);
         delete p;
     }
     removed_players.delete_all();
     World *w;
     while ((w = worlds.first()) != 0) {
         worlds.remove(w);
         delete w;
     }
     DOUT1("Clear game", ID);
 }
References data, XTList< Type >::delete_all(), detach_player(), DOUT1, XTList< Type >::first(), ServerData::GameType, ID, MECHOSOMA, PASSEMBLOSS, players, process_MECHOSOMA_ratings(), process_PASSEMBLOSS_ratings(), process_VAN_WAR_ratings(), XTList< Type >::remove(), removed_players, save_result(), XTList< Type >::size(), VAN_WAR, and worlds.
Member Function Documentation
attach_player()
int Game::attach_player (Player * player)
{
     for (int i = 0; i < 31; i++)
         if (!(used_players_IDs & (1 << i))) {
             used_players_IDs |= 1 << i;
             player->server->clients.remove(player);
             players.append(player);
             player->client_mask = 1 << i;
             player->game = this;
             DOUT1("Player attached", i + 1);
             return player->ID = i + 1;
         }
     return 0;
 }
References XTList< Type >::append(), Player::client_mask, Server::clients, DOUT1, Player::game, Player::ID, players, XTList< Type >::remove(), Player::server, and used_players_IDs.
Referenced by Player::receive().
check_global_objects()
void Game::check_global_objects (Player * player)
{
     Object *obj = global_objects.first();
     unsigned int mask = player->client_mask;
     while (obj) {
         if (!(obj->last_update & mask)) {
             player->put_object(obj);
             obj->last_update |= mask;
         }
         obj = obj->next;
     }
 }
References Player::client_mask, XTList< Type >::first(), global_objects, Object::last_update, Object::next, and Player::put_object().
Referenced by Player::receive().
detach_player()
void Game::detach_player (Player * player)
{
     //  if(player -> name && player -> password && player -> status == GAMING_STATUS)
     //      player -> server -> add_rating_data(player -> name,player ->
     //password,data.GameType,player
     //-> rating);
     player->clear_object_queue(0);
     if (player->world)
         player->world->detach_player(player);
     players.remove(player);
     player->client_mask = 0;
     player->game = 0;
     DOUT1("Player detached", player->ID);
     //  player -> ID = 0;
 }
References Player::clear_object_queue(), Player::client_mask, World::detach_player(), DOUT1, Player::game, Player::ID, players, XTList< Type >::remove(), and Player::world.
Referenced by quant(), and ~Game().
get_object_ID_offsets()
void Game::get_object_ID_offsets (OutputEventBuffer & out_buffer, int client_ID)
{
     int offsets[16];
     memset(offsets, 0, 16 * sizeof(int));
     unsigned int inv_mask = ~client_ID;
     Object *obj;
     World *w = worlds.first();
     while (w) {
         obj = w->objects.first();
         while (obj) {
             if (CLIENT_ID(obj->ID) == client_ID &&
                 offsets[(obj->ID >> 16) & 63] < (obj->ID & 0xffff))
                 offsets[(obj->ID >> 16) & 63] = obj->ID & 0xffff;
             obj = obj->next_alt;
         }
         w = w->next;
     }
     Player *p = players.first();
     while (p) {
         obj = p->inventory.first();
         while (obj) {
             if (CLIENT_ID(obj->ID) == client_ID &&
                 offsets[(obj->ID >> 16) & 63] < (obj->ID & 0xffff))
                 offsets[(obj->ID >> 16) & 63] = obj->ID & 0xffff;
             obj = obj->next;
         }
         p = p->next;
     }
     obj = global_objects.first();
     while (obj) {
         if (CLIENT_ID(obj->ID) == client_ID && offsets[(obj->ID >> 16) & 63] < (obj->ID & 0xffff))
             offsets[(obj->ID >> 16) & 63] = obj->ID & 0xffff;
         obj->visibility &= inv_mask;
         obj->last_update &= inv_mask;
         obj->in_queue &= inv_mask;
         obj->send_hide &= inv_mask;
         obj->send_delete &= inv_mask;
         obj = obj->next;
     }
     for (int i = 0; i < 16; i++)
         out_buffer < (unsigned short)(offsets[i] ? offsets[i] + 1 : 0);
 }
References CLIENT_ID, XTList< Type >::first(), XTListAlt< Type >::first(), global_objects, Object::ID, Object::in_queue, Player::inventory, Object::last_update, Object::next, World::next, Player::next, Object::next_alt, World::objects, players, Object::send_delete, Object::send_hide, Object::visibility, and worlds.
Referenced by Player::receive().
get_total_list_of_players_data()
void Game::get_total_list_of_players_data (OutputEventBuffer & out_buffer)
{
     out_buffer.begin_event(TOTAL_LIST_OF_PLAYERS_DATA);
     out_buffer < (unsigned char)(players.size() + removed_players.size());
     Player *p = players.first();
     while (p) {
         out_buffer < (unsigned char)(p->ID) < (unsigned char)p->status <
             (unsigned char)(p->world ? p->world->ID : 0) < short(p->x) < short(p->y) < p->name <
             char(0);
         out_buffer.write((unsigned char *)&p->body, sizeof(PlayerBody));
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         out_buffer < (unsigned char)(p->ID) < (unsigned char)p->status <
             (unsigned char)(p->world ? p->world->ID : 0) < short(p->x) < short(p->y) < p->name <
             char(0);
         out_buffer.write((unsigned char *)&p->body, sizeof(PlayerBody));
         p = p->next;
     }
     out_buffer.end_event();
 }
References OutputEventBuffer::begin_event(), OutputEventBuffer::end_event(), XTList< Type >::first(), players, removed_players, XTList< Type >::size(), TOTAL_LIST_OF_PLAYERS_DATA, and XBuffer::write().
Referenced by Player::send().
load_result()
void Game::load_result (Server * server, char * name)
{
     players.delete_all();
     removed_players.delete_all();
     XStream in(name, XS_IN);
     in.read(&data, sizeof(ServerData));
     int counter;
     in > counter;
     XSocket sock;
     for (int i = 0; i < counter; i++) {
         Player *p = new Player(server, sock);
         removed_players.append(p);
         p->name = new char[256];
         in > p->name;
         in.read(&p->body, sizeof(PlayerBody));
     }
     switch (data.GameType) {
     case VAN_WAR:
         process_VAN_WAR_ratings();
         break;
     case MECHOSOMA:
         process_MECHOSOMA_ratings();
         break;
     case PASSEMBLOSS:
         process_PASSEMBLOSS_ratings();
         break;
     }
 }
References XTList< Type >::append(), Player::body, counter, data, XTList< Type >::delete_all(), ServerData::GameType, MECHOSOMA, Player::name, name, PASSEMBLOSS, players, process_MECHOSOMA_ratings(), process_PASSEMBLOSS_ratings(), process_VAN_WAR_ratings(), XStream::read(), removed_players, server, VAN_WAR, and XS_IN.
process_create_globals()
void Game::process_create_globals (Player * player, Object * obj)
{
     global_objects.append(obj);
     obj->list = &global_objects;
     Player *p = players.first();
     while (p) {
         if (p != player) {
             p->put_object(obj);
             obj->last_update |= p->client_mask;
         } else
             obj->last_update |= p->client_mask;
         p = p->next;
     }
 }
References XTList< Type >::append(), Player::client_mask, XTList< Type >::first(), global_objects, Object::last_update, Object::list, Player::next, players, and Player::put_object().
Referenced by Player::receive().
process_delete_globals()
void Game::process_delete_globals (Object * obj)
{
     Player *p = players.first();
     while (p) {
         obj->send_delete |= p->client_mask;
         p->put_object(obj);
         p = p->next;
     }
 }
References Player::client_mask, XTList< Type >::first(), Player::next, players, Player::put_object(), and Object::send_delete.
Referenced by Player::receive().
process_direct_sending()
void Game::process_direct_sending (Object * obj, unsigned int mask)
{
     Player *p = players.first();
     while (p) {
         if (mask & p->client_mask) {
             obj->send_delete |= p->client_mask;
             p->put_object(obj);
         }
         p = p->next;
     }
 }
References Player::client_mask, XTList< Type >::first(), Player::next, players, Player::put_object(), and Object::send_delete.
Referenced by Player::receive().
process_MECHOSOMA_ratings()
void Game::process_MECHOSOMA_ratings ()
{
     int counter = 0;
     double avr_rating = 0;
     Player *p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS) {
             p -> body.rating = (float)((p -> body.MechosomaStat.MaxTransitTime)*pow(1.1,p -> body.kills)*pow(0.9,p -> body.deaths));
             avr_rating += p->body.rating;
             counter++;
         }
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         p -> body.rating = (float)((p -> body.MechosomaStat.MaxTransitTime)*pow(1.1,p -> body.kills)*pow(0.9,p -> body.deaths));
         avr_rating += p->body.rating;
         counter++;
         p = p->next;
     }
     if (!counter)
         return;
     avr_rating /= (double)counter;
     double total_weight = 0;
     p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS)
             total_weight += fabs(p->body.rating - avr_rating);
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         total_weight += fabs(p->body.rating - avr_rating);
         p = p->next;
     }
     if (total_weight < 0.01)
         return;
     total_weight /= 2.;
     double total_account =
         2. * (double)(data.Mechosoma.ProductQuantity1 + data.Mechosoma.ProductQuantity2) * counter;
     //  if(data.Mechosoma.One_at_a_time)
     //      rating *= 2.;
     double factor = total_account / total_weight;
     p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS) {
             p->body.rating = (float)((p->body.rating - avr_rating) * factor);
             p->server->add_rating_data(p, MECHOSOMA);
         }
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         p->body.rating = (float)((p->body.rating - avr_rating) * factor);
         p->server->add_rating_data(p, MECHOSOMA);
         p = p->next;
     }
 }
References Server::add_rating_data(), Player::body, counter, data, XTList< Type >::first(), INITIAL_STATUS, MECHOSOMA, ServerData::Mechosoma, Player::next, players, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, PlayerBody::rating, removed_players, Player::server, and Player::status.
Referenced by load_result(), quant(), Player::receive(), and ~Game().
process_PASSEMBLOSS_ratings()
void Game::process_PASSEMBLOSS_ratings ()
{
     int counter = 0;
     double avr_rating = 0;
     Player *p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS) {
             p -> body.rating = (float)((p -> body.PassemblossStat.TotalTime)*pow(1.1,p -> body.kills)*pow(0.9,p -> body.deaths));
             avr_rating += p->body.rating;
             counter++;
         }
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         p->body.rating =
             (float)((p->body.PassemblossStat.TotalTime) * pow(1.1, p->body.kills) * pow(0.9, p->body.deaths));
         avr_rating += p->body.rating;
         counter++;
         p = p->next;
     }
     if (!counter)
         return;
     avr_rating /= (double)counter;
     double total_weight = 0;
     p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS)
             total_weight += fabs(p->body.rating - avr_rating);
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         total_weight += fabs(p->body.rating - avr_rating);
         p = p->next;
     }
     if (total_weight < 0.01)
         return;
     total_weight /= 2.;
     double total_account = 5. * (double)(data.Passembloss.CheckpointsNumber * counter);
     double factor = total_account / total_weight;
     p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS) {
             p->body.rating = (float)((p->body.rating - avr_rating) * factor);
             p->server->add_rating_data(p, PASSEMBLOSS);
         }
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         p->body.rating = (float)((p->body.rating - avr_rating) * factor);
         p->server->add_rating_data(p, PASSEMBLOSS);
         p = p->next;
     }
 }
References Server::add_rating_data(), Player::body, PASSEMBLOSS_PRM::CheckpointsNumber, counter, data, PlayerBody::deaths, XTList< Type >::first(), INITIAL_STATUS, PlayerBody::kills, Player::next, PASSEMBLOSS, ServerData::Passembloss, PlayerBody::PassemblossStat, players, PlayerBody::rating, removed_players, Player::server, Player::status, and PassemblossStatistic::TotalTime.
Referenced by load_result(), quant(), Player::receive(), and ~Game().
process_update_globals()
void Game::process_update_globals (Player * player, Object * obj)
{
     obj->last_update = 0;
     Player *p = players.first();
     while (p) {
         if (p != player) {
             p->put_object(obj);
             obj->last_update |= p->client_mask;
         } else
             obj->last_update |= p->client_mask;
         p = p->next;
     }
 }
References Player::client_mask, XTList< Type >::first(), Object::last_update, Player::next, players, and Player::put_object().
Referenced by Player::receive().
process_VAN_WAR_ratings()
void Game::process_VAN_WAR_ratings ()
{
     int total_account = 0;
     int counter = 0;
     double avr_rating = 0;
     Player *p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS) {
             p->body.rating = (float)((p->body.kills - p->body.deaths));
             total_account += p->body.kills;
             avr_rating += p->body.rating;
             counter++;
         }
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         p->body.rating = (float)((p->body.kills - p->body.deaths));
         total_account += p->body.kills;
         avr_rating += p->body.rating;
         counter++;
         p = p->next;
     }
     if (!counter)
         return;
     avr_rating /= (double)counter;
     double total_weight = 0;
     p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS)
             total_weight += fabs(p->body.rating - avr_rating);
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         total_weight += fabs(p->body.rating - avr_rating);
         p = p->next;
     }
     if (total_weight < 0.01)
         return;
     total_weight /= 2.;
     double factor = (double)total_account / (total_weight);
     p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS) {
             p->body.rating = (float)((p->body.rating - avr_rating) * factor);
             p->server->add_rating_data(p, VAN_WAR);
         }
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         p->body.rating = (float)((p->body.rating - avr_rating) * factor);
         p->server->add_rating_data(p, VAN_WAR);
         p = p->next;
     }
 }
References Server::add_rating_data(), Player::body, counter, PlayerBody::deaths, XTList< Type >::first(), INITIAL_STATUS, PlayerBody::kills, Player::next, players, PlayerBody::rating, removed_players, Player::server, Player::status, and VAN_WAR.
Referenced by load_result(), quant(), Player::receive(), and ~Game().
put_event_for_all()
void Game::put_event_for_all (int code, Player * player = 0)
{
     Player *p = players.first();
     while (p) {
         if (p != player)
             p->code_queue.put(Event(code, player));
         p = p->next;
     }
 }
References Player::code_queue, XTList< Type >::first(), Player::next, players, and XQueue< Type >::put().
Referenced by World::attach_player(), World::detach_player(), quant(), and Player::receive().
quant()
int Game::quant ()
                 {
     int work_log = 0;
     Player *p = players.first();
     while (p) {
         work_log += p->receive();
         if (!p->is_alive()) {
             Player *p_next = p->next;
             used_players_IDs &= ~(1 << p->ID - 1);
             detach_player(p);
             if (p->status == GAMING_STATUS) {
                 p->status = FINISHED_STATUS;
                 put_event_for_all(PLAYERS_STATUS, p);
                 removed_players.append(p);
                 switch (data.GameType) {
                 case VAN_WAR:
                     process_VAN_WAR_ratings();
                     break;
                 case MECHOSOMA:
                     process_MECHOSOMA_ratings();
                     break;
                 case PASSEMBLOSS:
                     process_PASSEMBLOSS_ratings();
                     break;
                 }
             } else
                 delete p;
             p = p_next;
             continue;
         }
         p = p->next;
     }
     p = players.first();
     while (p) {
         work_log += p->send();
         p = p->next;
     }
     return work_log;
 }
References XTList< Type >::append(), data, detach_player(), FINISHED_STATUS, XTList< Type >::first(), ServerData::GameType, GAMING_STATUS, Player::ID, Player::is_alive(), MECHOSOMA, Player::next, PASSEMBLOSS, players, PLAYERS_STATUS, process_MECHOSOMA_ratings(), process_PASSEMBLOSS_ratings(), process_VAN_WAR_ratings(), put_event_for_all(), Player::receive(), removed_players, Player::send(), Player::status, used_players_IDs, and VAN_WAR.
save_result()
void Game::save_result ()
{
     if (!players.size() && !removed_players.size())
         return;
     XBuffer name;
     name <= time(0) < ".rs" <= data.GameType;
     XStream out(name.GetBuf(), XS_OUT);
     out.write(&data, sizeof(ServerData));
     int counter = 0;
     int offset = out.tell();
     out < counter;
     Player *p = players.first();
     while (p) {
         if (p->status != INITIAL_STATUS) {
             out < p->name < char(0);
             out.write(&p->body, sizeof(PlayerBody));
             counter++;
         }
         p = p->next;
     }
     p = removed_players.first();
     while (p) {
         out < p->name < char(0);
         out.write(&p->body, sizeof(PlayerBody));
         counter++;
         p = p->next;
     }
     out.seek(offset, XS_BEG);
     out < counter;
 }
References counter, data, ServerData::GameType, name, players, removed_players, XTList< Type >::size(), XStream::write(), and XS_OUT.
Referenced by ~Game().
Member Data Documentation
birth_time
unsigned int Game::birth_time
Referenced by Game(), and Player::receive().
client_version
int Game::client_version
Referenced by Game(), and Player::receive().
data
ServerData Game::data
Referenced by load_result(), process_MECHOSOMA_ratings(), process_PASSEMBLOSS_ratings(), quant(), Player::receive(), save_result(), Player::send(), and ~Game().
global_objects
XTList<Object> Game::global_objects
Referenced by check_global_objects(), get_object_ID_offsets(), process_create_globals(), Player::receive(), and Server::report().
ID
int Game::ID
Referenced by Game(), Player::receive(), Server::report(), and ~Game().
list
XTList<Game>* Game::list
Referenced by Game().
name
char Game::name[128]
Referenced by Game(), load_result(), Player::receive(), save_result(), and Player::send().
next
Game* Game::next
Referenced by Game(), and Server::report().
players
XTList<Player> Game::players
Referenced by attach_player(), detach_player(), get_object_ID_offsets(), get_total_list_of_players_data(), load_result(), process_create_globals(), process_delete_globals(), process_direct_sending(), process_MECHOSOMA_ratings(), process_PASSEMBLOSS_ratings(), process_update_globals(), process_VAN_WAR_ratings(), put_event_for_all(), quant(), Player::receive(), Server::report(), save_result(), and ~Game().
prev
Game* Game::prev
Referenced by Game().
removed_players
XTList<Player> Game::removed_players
Referenced by get_total_list_of_players_data(), load_result(), process_MECHOSOMA_ratings(), process_PASSEMBLOSS_ratings(), process_VAN_WAR_ratings(), quant(), save_result(), and ~Game().
used_players_IDs
unsigned int Game::used_players_IDs
Referenced by attach_player(), Game(), quant(), and Player::receive().
worlds
XTList<World> Game::worlds
Referenced by get_object_ID_offsets(), Player::receive(), Server::report(), and ~Game().
The documentation for this struct was generated from the following files:
server/server.h
server/server.cpp