Vangers: InsectUnit Struct Reference
InsectUnit Struct Reference
#include <mechos.h>
Public Member Functions
void Init (void)
void CreateInsect (void)
void Quant (void)
void InitEnvironment (void)
void Touch (GeneralObject *p)
int test_objects_collision ()
void HideAction (void)
Public Member Functions inherited from ActionUnit
void Init (StorageType *s)
void Free (void)
void Open (void)
void Close (void)
void DrawQuant (void)
void CreateActionUnit (int nmodel, int _status, const Vector &_v, int _angle, int put_mode)
virtual void keyhandler (int key)
virtual void Hide2Show (void)
virtual void DeleteHandler (void)
void CalcTrackVector (Vector &v, int &len, int &angle1, int &angle2)
void Action (void)
void HideAction (void)
void MixVector (void)
void Touch (GeneralObject *obj)
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Attributes
Vector Target
int BeebType
Public Attributes inherited from ActionUnit
Vector vDirect
Vector vEnvir
int EnvirAngle
int EnvirLen
int NumCalcUnit
int NumViewUnit
int MaxVelocity
int ViewRadius
char SpeedDir
int MinSpeed
int MaxSpeed
int CurrSpeed
int MaxHideSpeed
int MoveAngle
int DeltaSpeed
int DeltaTraction
char OtherFlag
Vector vUp
Vector vDown
int Speed
int Angle
DBM RotMat
DBM MovMat
int PrevVisibility
int Count
int WavePhase
WaveProcess * wProcess
int nModel
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Detailed Description
Member Function Documentation
CreateInsect()
void InsectUnit::CreateInsect (void)
 {
     MaxSpeed = 5;
     MaxHideSpeed = 3;
     Target = R_curr + Vector(INSECT_RADIUS - RND(INSECT_RADIUS2),INSECT_RADIUS - RND(INSECT_RADIUS2),0);
     if(!RND(InsectD.NumInsect[2]*INSECT_PRICE_DATA[2])) BeebType = 2;
     else{
         if(!RND(InsectD.NumInsect[1]*INSECT_PRICE_DATA[1])) BeebType = 1;
         else BeebType = 0;
     };
     InsectD.NumInsect[BeebType]++;
     switch(BeebType){
         case 0:
             set_body_color(COLORS_IDS::MATERIAL_1);
             break;
         case 1:
             set_body_color(COLORS_IDS::MATERIAL_2);
             break;
         case 2:
             set_body_color(COLORS_IDS::MATERIAL_4);
             break;
     };
 };
References BeebType, INSECT_PRICE_DATA, INSECT_RADIUS, INSECT_RADIUS2, InsectD, COLORS_IDS::MATERIAL_1, COLORS_IDS::MATERIAL_2, COLORS_IDS::MATERIAL_4, ActionUnit::MaxHideSpeed, ActionUnit::MaxSpeed, InsectList::NumInsect, RND(), Object::set_body_color(), and Target.
Referenced by InsectList::Init().
HideAction()
void InsectUnit::HideAction (void)
 {
     dynamic_state = WHEELS_TOUCH;
     if(SpeedDir == 0) return;
     else{
         if(SpeedDir > 0){
             CurrSpeed = MaxHideSpeed;
             MoveAngle = rPI(MoveAngle - Angle);
         }else{
             MoveAngle = rPI(MoveAngle - Angle + PI);
             CurrSpeed = -MaxHideSpeed;
         };
     };
     if(MoveAngle > PI) MoveAngle -= 2*PI;
     if(MoveAngle > 0){
         if(MoveAngle > MECHOS_ROT_DELTA) MoveAngle = MECHOS_ROT_DELTA;
     }else{
         if(MoveAngle < -MECHOS_ROT_DELTA) MoveAngle = -MECHOS_ROT_DELTA;
     };
     Angle = rPI(Angle + MoveAngle);
     vDirect = Vector(CurrSpeed,0,0) * DBM(Angle,Z_AXIS);
     R_curr.x += vDirect.x;
     R_curr.y += vDirect.y;
     cycleTor(R_curr.x,R_curr.y);
 };
References ActionUnit::Angle, ActionUnit::CurrSpeed, cycleTor(), ActionUnit::MaxHideSpeed, MECHOS_ROT_DELTA, ActionUnit::MoveAngle, PI, rPI, ActionUnit::SpeedDir, ActionUnit::vDirect, WHEELS_TOUCH, Vector::x, Vector::y, and Z_AXIS.
Referenced by Quant().
Init()
void InsectUnit::Init (void)
 {
     ID = ID_INSECT;
     ActionUnit::Init(NULL);
 };
References Object::ID, ID_INSECT, ActionUnit::Init(), and NULL.
Referenced by InsectList::Init().
InitEnvironment()
void InsectUnit::InitEnvironment (void) virtual
Reimplemented from ActionUnit.
 {
     ActionUnit* p;
     int dx,dy;
     int d,r,f;
     ActionUnit::InitEnvironment();
     if(Visibility == UNVISIBLE) R_curr.z = 80;
     vDirect = Vector(0,0,0);
     NumCalcUnit = 0;
 //  if(Visibility != VISIBLE) return;
     if(vInsectTarget.y == -1){
         p = (ActionUnit*)(ActD.Tail);
         while(p){
             dy = getDistY(R_curr.y,p->R_curr.y);
             if(abs(dy) < ViewRadius){
                 dx = getDistX(R_curr.x,p->R_curr.x);
                 if(abs(dx) < ViewRadius){
                     d = (int)(sqrt(dx*(double)dx + dy*(double)dy));
                     if(d){
                         r = p->radius * 5;
                         if(d < r && r > 0){
                             f = MaxSpeed - MaxSpeed * d / r;
                             vDirect.x += dx * f / d;
                             vDirect.y += dy * f / d;
                             NumCalcUnit++;
                         };
                     };
                 };
             };
             p = (ActionUnit*)(p->NextTypeList);
         };
         p = (ActionUnit*)(InsectD.Tail);
         while(p){
             if(p != this/* && p->Visibility == VISIBLE*/){
                 dy = getDistY(R_curr.y,p->R_curr.y);
                 if(abs(dy) < ViewRadius){
                     dx = getDistX(R_curr.x,p->R_curr.x);
                     if(abs(dx) < ViewRadius){
                         d = (int)(sqrt(dx*(double)dx + dy*(double)dy));
                         if(d){
                             r = p->radius * 5;
                             if(d < r && r > 0){
                                 f = MaxSpeed - MaxSpeed * d / r;
                                 vDirect.x += dx * f / d;
                                 vDirect.y += dy * f / d;
                                 NumCalcUnit++;
                             };
                         };
                     };
                 };
             };
             p = (ActionUnit*)(p->NextTypeList);
         };
     };
 };
References ActD, getDistX(), getDistY(), ActionUnit::InitEnvironment(), InsectD, ActionUnit::MaxSpeed, ActionUnit::NumCalcUnit, Object::radius, UnitListType::Tail, UnitList::Tail, UNVISIBLE, ActionUnit::vDirect, ActionUnit::ViewRadius, vInsectTarget, Object::x, Vector::x, Object::y, and Vector::y.
Quant()
void InsectUnit::Quant (void) virtual
Reimplemented from ActionUnit.
 {
     ActionUnit::Quant();
     int dx,dy;
     int d;
     if(Status & SOBJ_AUTOMAT){
         vDirect.z = 0;
         if(vInsectTarget.y == -1){
             if(ActD.Active) Target = ActD.Active->R_curr;
             else Target = R_curr;
         }else Target = vInsectTarget;
         dx = getDistX(Target.x,R_curr.x);
         dy = getDistY(Target.y,R_curr.y);
 /*      if(dx == 0 && dy == 0){
             if(ActD.Active) Target = Vector(ActD.Active->R_curr.x + INSECT_RADIUS - RND(INSECT_RADIUS2),ActD.Active->R_curr.y + INSECT_RADIUS - RND(INSECT_RADIUS2),0);
             else  Target = R_curr + Vector(INSECT_RADIUS - RND(INSECT_RADIUS2),INSECT_RADIUS - RND(INSECT_RADIUS2),0);
             cycleTor(Target.x,Target.y);
         };*/
         d = (int)(sqrt(dx*(double)dx + dy*(double)dy));
         d <<= 2;
         if(d){
             vDirect.x += dx * MaxSpeed / d * XTCORE_FRAME_NORMAL;
             vDirect.y += dy * MaxSpeed / d * XTCORE_FRAME_NORMAL;
         };
         if(NumCalcUnit) vDirect /= NumCalcUnit;
         MoveAngle = vDirect.psi();
         DeltaSpeed = vDirect.vabs();
         if(Visibility == VISIBLE) Action();
         else HideAction();
     };
 };
References ActD, ActionUnit::Action(), ActionDispatcher::Active, ActionUnit::DeltaSpeed, getDistX(), getDistY(), HideAction(), ActionUnit::MaxSpeed, ActionUnit::MoveAngle, ActionUnit::NumCalcUnit, Vector::psi(), ActionUnit::Quant(), SOBJ_AUTOMAT, Target, Vector::vabs(), ActionUnit::vDirect, vInsectTarget, VISIBLE, Vector::x, XTCORE_FRAME_NORMAL, Vector::y, and Vector::z.
test_objects_collision()
int InsectUnit::test_objects_collision () virtual
Reimplemented from Object.
 {
     int log = 0;
     BaseObject* p;
     p = (BaseObject*)(ActD.Tail);
     while(p && p != this){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     return 0;
 };
References ActD, GeneralObject::NextTypeList, UnitList::Tail, Object::test_object_to_baseobject(), BaseObject::Visibility, and VISIBLE.
Touch()
void InsectUnit::Touch (GeneralObject * p)
 {
     switch(p->ID){
         case ID_VANGER:
             if(p->Status & SOBJ_ACTIVE){
                 SOUND_BEEB_DEATH(getDistX(ActD.Active->R_curr.x,R_curr.x));
 //              ActD.HotBug += INSECT_PRICE_DATA[BeebType];
                 aiPutHotBug(aiGetHotBug() + INSECT_PRICE_DATA[BeebType]);
                 if(BeebType == 2) uvsCheckKronIventTabuTask(UVS_KRON_EVENT::GOLD_BEEB,1);
                 else uvsCheckKronIventTabuTask(UVS_KRON_EVENT::BEEB,1);
                 if(NetworkON){
                     my_player_body.beebos = aiGetHotBug();
                     send_player_body(my_player_body);
                 };
             };
             MapD.CreateCrater(R_curr,MAP_POINT_CRATER03,Angle);
             R_curr.x = clip_mask_x/2 - RND(clip_mask_x);
             R_curr.y = clip_mask_y/2 - RND(clip_mask_y);
             cycleTor(R_curr.x,R_curr.y);
             set_3D(SET_3D_CHOOSE_LEVEL,R_curr.x,R_curr.y,R_curr.z,0,-Angle,0);
         case ID_BULLET:
         case ID_JUMPBALL:
             MapD.CreateCrater(R_curr,MAP_POINT_CRATER03,Angle);
             R_curr.x = clip_mask_x/2 - RND(clip_mask_x);
             R_curr.y = clip_mask_y/2 - RND(clip_mask_y);
             cycleTor(R_curr.x,R_curr.y);
             set_3D(SET_3D_CHOOSE_LEVEL,R_curr.x,R_curr.y,R_curr.z,0,-Angle,0);
             break;
     };
 };
References ActD, ActionDispatcher::Active, aiGetHotBug(), aiPutHotBug(), ActionUnit::Angle, UVS_KRON_EVENT::BEEB, PlayerBody::beebos, BeebType, clip_mask_x, clip_mask_y, cycleTor(), getDistX(), UVS_KRON_EVENT::GOLD_BEEB, GeneralObject::ID, ID_BULLET, ID_JUMPBALL, ID_VANGER, INSECT_PRICE_DATA, MapD, my_player_body, NetworkON, RND(), send_player_body(), Object::set_3D(), SET_3D_CHOOSE_LEVEL, SOBJ_ACTIVE, SOUND_BEEB_DEATH, GeneralObject::Status, uvsCheckKronIventTabuTask(), and Object::x.
Member Data Documentation
BeebType
int InsectUnit::BeebType
Referenced by CreateInsect(), and Touch().
Target
Vector InsectUnit::Target
Referenced by CreateInsect(), and Quant().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp