Vangers: uvsBunch Struct Reference
uvsBunch Struct Reference
#include <univang.h>
Public Member Functions
uvsBunch (void)
uvsBunch (PrmFile *pfile, char *atom)
uvsBunch (XStream &pfile, PrmFile *pf, char *atom)
~uvsBunch (void)
void save (XStream &)
void Quant (void)
void QuantCirt (int)
int nextCycle (void)
int game_soon (char *)
int game_now (char *, uvsCultGame *&)
void begin_game (void)
void begin_race (void)
void begin_harvest (void)
void end_game (void)
void end_race (void)
void end_harvest (void)
int real_hunter_now (uvsVanger *)
int game_exit (void)
int game_wait_end (void)
int addGOODS_any (uvsCultGame *)
int bring_game_GOODS (char *, listElem *&)
int bring_race_GOODS (char *, listElem *&)
int bring_harvest_GOODS (char *, listElem *&)
char * GetCurrentStageName (void)
int GetCirtQ (void)
int addCirt (uvsItem *)
void randVRes (void)
void Check (char *)
Public Member Functions inherited from listElem
listElem (void)
void link (listElem *&tail)
listElem * seekName (const char *name)
virtual char * GetName (void)
Public Attributes
uvsEscave * Pescave
int biosNindex
int cycleN
uvsCultStage * cycleTable
int currentStage
int vngResource
int status
int id
Public Attributes inherited from listElem
listElem * next
listElem * prev
Detailed Description
Constructor & Destructor Documentation
uvsBunch() [1/3]
uvsBunch::uvsBunch (void) inline
 : listElem() {Pescave = NULL; biosNindex = cycleN = currentStage = vngResource = 0; cycleTable = NULL; status = 0; id = 0;}
References biosNindex, currentStage, cycleN, cycleTable, NULL, Pescave, status, and vngResource.
uvsBunch() [2/3]
uvsBunch::uvsBunch (PrmFile * pfile, char * atom)
{
     status = 0;
     Pescave = (uvsEscave*)EscaveTail -> seekName(atom);
     Pescave -> Pbunch = this;
     char* s = pfile -> getAtom();
     int i;
     for(i = 0;i < BIOS_MAX;i++) if(!strcasecmp(s,BIOS_NAMES[i])) break;
     if(i == BIOS_MAX) ErrH.Abort(PrmWrongValue,XERR_USER,-1,"Bios Name");
     biosNindex = i;
     cycleN = atoi(pfile -> getAtom());
     if(cycleN <= 0) ErrH.Abort(PrmWrongValue,XERR_USER,-1,"cycleN");
     cycleTable = new uvsCultStage[cycleN];
     for(i = 0;i < cycleN;i++){
         s = pfile -> getAtom();
         cycleTable[i].name = new char[strlen(s)+1];
         strcpy(cycleTable[i].name, s);
         cycleTable[i].cirtMAX = atoi(pfile -> getAtom());
         cycleTable[i].time = atoi(pfile -> getAtom())*60;
         cycleTable[i].priceQ = atoi(pfile -> getAtom());
         cycleTable[i].GamerCirt = 0;
         if(cycleTable[i].cirtMAX <= 0) ErrH.Abort(PrmWrongValue,XERR_USER,-1,"cirtQ");
         cycleTable[i].cirtQ = 0;
         s = pfile -> getAtom();
         cycleTable[i].pal_name = new char[strlen(s)+1];
         strcpy(cycleTable[i].pal_name, s);
         s = pfile -> getAtom();
         if ( strcmp(s, PrmNoneGame) ){
             cycleTable[i].Pgame = new uvsCultGame(pfile, s);
             //ErrH.Abort(PrmWrongValue,XERR_USER,-1,"Game");
         } else
             cycleTable[i].Pgame = NULL;
     }
     currentStage = RND(cycleN);
     for(i = 0;i < cycleN;i++){
         int out  = 0;
         while( !out ){
             out = 1;
             cycleTable[i].Pdolly = WorldTable[getRW(Pescave -> Pworld -> gIndex)] -> generateDolly(biosNindex);
             if ( cycleTable[i].Pdolly == NULL  ) out = 0;
         }//  end while
     }//  end for i
     randVRes();
     if ( cycleTable[currentStage].Pgame ) begin_game();
 }
References XErrorHandler::Abort(), BIOS_MAX, BIOS_NAMES, ErrH, EscaveTail, Pescave, listElem::seekName(), and status.
uvsBunch() [3/3]
uvsBunch::uvsBunch (XStream & pfile, PrmFile * pf, char * atom)
{
     Pescave = (uvsEscave*)EscaveTail -> seekName(atom);
     Pescave -> Pbunch = this;
     char* s = pfile -> getAtom();
     int i, j;
     for(i = 0;i < BIOS_MAX;i++) if(!strcasecmp(s,BIOS_NAMES[i])) break;
     if(i == BIOS_MAX) ErrH.Abort(PrmWrongValue,XERR_USER,-1,"Bios Name");
     biosNindex = i;
     cycleN = atoi(pfile -> getAtom());
     if(cycleN <= 0) ErrH.Abort(PrmWrongValue,XERR_USER,-1,"cycleN");
     cycleTable = new uvsCultStage[cycleN];
     for(i = 0;i < cycleN;i++){
         s = pfile -> getAtom();
         cycleTable[i].name = new char[strlen(s)+1];
         strcpy(cycleTable[i].name, s);
         cycleTable[i].cirtMAX = atoi(pfile -> getAtom());
         cycleTable[i].time = atoi(pfile -> getAtom())*60;
         cycleTable[i].priceQ = atoi(pfile -> getAtom());
         if(cycleTable[i].cirtMAX <= 0) ErrH.Abort(PrmWrongValue,XERR_USER,-1,"cirtQ");
         //cycleTable[i].cirtQ = 0;
         s = pfile -> getAtom();
         cycleTable[i].pal_name = new char[strlen(s)+1];
         strcpy(cycleTable[i].pal_name, s);
         s = pfile -> getAtom();
         if ( strcmp(s, PrmNoneGame) ){
             cycleTable[i].Pgame = new uvsCultGame(pfile, s);
             //ErrH.Abort(PrmWrongValue,XERR_USER,-1,"Game");
         } else
             cycleTable[i].Pgame = NULL;
     }
     for(i = 0;i < cycleN;i++){
         pf > cycleTable[i].cirtQ;
         pf > cycleTable[i].GamerCirt;
         if (uvsLoadVersion < 5)
             cycleTable[i].GamerCirt = 4;
         if ( cycleTable[i].Pgame ){
             pf > cycleTable[i].Pgame -> GoodsBegCount;
             pf > cycleTable[i].Pgame -> GoodsEndCount;
             pf > cycleTable[i].Pgame -> result;
             pf > cycleTable[i].Pgame -> total;
             pf > cycleTable[i].Pgame -> flag;
             pf > cycleTable[i].Pgame -> first;
             pf > cycleTable[i].Pgame -> all;
             pf > cycleTable[i].Pgame -> sucks;
             pf > cycleTable[i].Pgame -> start;
             if ( cycleTable[i].Pgame -> GameType == UVS_GAME_TYPE::HARVEST ){
                 for(j = 0; j < cycleTable[i].Pgame -> total; j++)
                     pf > cycleTable[i].Pgame -> score[j];
             }
         }
         int cd;
         pf > cd;
 //      cd = biosNindex*3 + i + 1;
         uvsDolly* pd = (uvsDolly*)DollyTail;
         while(pd){
             if(pd -> gIndex == cd ) break;
             pd = (uvsDolly*)pd -> next;
             }
         if(!pd)
             ErrH.Abort(PrmWrongValue,XERR_USER,-1,"Dolly");
         cycleTable[i].Pdolly = pd;
     }
     pf > currentStage;
     pf > vngResource;
     pf > status;
     randVRes();
 }
References XErrorHandler::Abort(), BIOS_MAX, BIOS_NAMES, ErrH, EscaveTail, Pescave, and listElem::seekName().
~uvsBunch()
uvsBunch::~uvsBunch (void)
{
     int i;
     if ( cycleN ){
         for( i = 0; i < cycleN; i++){
             cycleTable[i].free();
         }
         delete[] cycleTable;
     }
 }
References cycleN, cycleTable, and uvsCultStage::free().
Member Function Documentation
addCirt()
int uvsBunch::addCirt (uvsItem * pi)
{
     int  i = 0;
     int tmp = 0;
     for ( i = 0; i < cycleN; i++){
         if( (1 << cycleTable[i].Pdolly -> gIndex) & pi -> param2) {
             tmp += ((pi -> param1 >> (cycleTable[i].Pdolly -> gIndex*3)) & 7);
             cycleTable[i].cirtQ += ((pi -> param1 >> (cycleTable[i].Pdolly -> gIndex*3)) & 7);
         }
     }//  end for j
     return tmp;
 }
addGOODS_any()
int uvsBunch::addGOODS_any (uvsCultGame * pg)
{
     uvsElement* e = ETail;
     while(e){
         if( ((uvsVanger*)e) -> type == UVS_OBJECT::VANGER && (((uvsVanger*)e) -> status == UVS_VANGER_STATUS::ESCAVE_WAITING ||
             ((uvsVanger*)e) -> status == UVS_VANGER_STATUS::SPOT_WAITING)) {
 #ifdef _ROAD_
             if ( ((uvsVanger*)e) -> shape != UVS_VANGER_SHAPE::GAMER ){
 #endif
             if ( ((uvsVanger*)e) -> addGOODS( pg ) ) return 1;
 #ifdef _ROAD_
         }
 #endif
         }//  end if
         e = e -> enext;
     }//  end while
     return 0;
 }
References UVS_VANGER_STATUS::ESCAVE_WAITING, ETail, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_STATUS::SPOT_WAITING, status, and UVS_OBJECT::VANGER.
Referenced by begin_race().
begin_game()
void uvsBunch::begin_game (void)
{
     uvsCultGame *pg = cycleTable[currentStage].Pgame;
     switch( pg -> GameType ){
     case UVS_GAME_TYPE::RACE:
         begin_race();
         break;
     case UVS_GAME_TYPE::HARVEST:
         begin_harvest();
         break;
     }
 }
References begin_harvest(), begin_race(), currentStage, cycleTable, UVS_GAME_TYPE::HARVEST, uvsCultStage::Pgame, and UVS_GAME_TYPE::RACE.
Referenced by Quant().
begin_harvest()
void uvsBunch::begin_harvest (void)
{
     int i;
     uvsCultGame *pg = cycleTable[currentStage].Pgame;
     uvsWorld* pw = Pescave -> Pworld;
 #ifdef STAND_REPORT
     stand < ConTimer.GetTime();
     stand < "\nHarvest begin on " < pw -> name < "\n\n";
 #endif
     if (uvsGamerWaitGame && !uvsEndHarvest) {
         uvsEndHarvest = 1;
     }
     pg -> GoodsBegCount = 0;        //      1
     pg -> GoodsEndCount = 0;        //      2
     pg -> result = 0;               //
     pg -> total = 0;                //
     if (!pg -> score ) pg -> score = new uchar[V_MAX_VANGER];
     pg -> score[pg -> total++] = 3 + RND(5);
     //if ( pw -> gIndex == CurrentWorld ) return;
     //   KRONa
     if (!NetworkON){ //znfo farmer adding
         for( i = 0; i < pg -> GoodsTypeBegCount/* + RND(3)*/; i++){
             if ( (pw -> gIndex == CurrentWorld) && uvsKronActive )
                 addFarmer(RND(pw->x_size), RND(pw->y_size), V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1),
                             V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1),pg -> GoodsTypeBeg,
                             FLY_FARMER_CORN, 0);
             else
                 ( new uvsFlyFarmer(pg -> GoodsTypeBeg, pw)) -> elink(pw -> Panymal);
         }//  end for i
     }//  end if
 }
References addFarmer(), ConTimer, currentStage, CurrentWorld, cycleTable, FLY_FARMER_CORN, uvsContimer::GetTime(), NetworkON, Pescave, uvsCultStage::Pgame, RND(), uvsEndHarvest, uvsGamerWaitGame, uvsKronActive, V_MAX_VANGER, V_SPEED_DOLLY, uvsWorld::x_size, and uvsWorld::y_size.
Referenced by begin_game().
begin_race()
void uvsBunch::begin_race (void)
{
     uvsCultGame *pg = cycleTable[currentStage].Pgame;
     char *name;
     if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE )
         name  = ((uvsEscave*)(pg -> townBeg)) -> name;
     else
         name = ((uvsSpot*)(pg -> townBeg)) -> name;
 #ifdef STAND_REPORT
     stand < ConTimer.GetTime();
     stand < "\nRace begin in " < name < "\n\n";
 #endif
     pg -> GoodsBegCount = pg -> GoodsTypeBegCount;
     pg -> GoodsEndCount = pg -> GoodsTypeEndCount;
     pg -> result = 0;
     pg -> start = 1;
     pg -> total = 0;
     pg -> flag = 0;
     if (!pg -> GoodsTypeBegCount)
         pg -> GoodsBegCount = V_RACE_VANGER;
      else
         pg -> GoodsBegCount = pg -> GoodsTypeBegCount;
     if ((!pg -> GoodsTypeBegCount) && (!strcmp( aci_curLocationName,  name) && Gamer -> status == UVS_VANGER_STATUS::IN_SHOP) ) {
         uvsEndHarvest = 1;
         if(GCharItem) delete GCharItem;
         if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE){
             GCharItem = new uvsActInt;
             GCharItem -> type = uvsSetItemType(pg -> GoodsTypeBeg, 0, 0);
             GCharItem -> param1 = Pescave -> Pworld -> gIndex<<16;
             GCharItem -> price = ((uvsEscave*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg];
             GCharItem -> sell_price = ((uvsEscave*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg + MAX_ITEM_TYPE];
 //          ((uvsEscave*)(pg -> townBeg)) -> Pshop -> addItem( new uvsItem(pg -> GoodsTypeBeg));
         } else {
             GCharItem = new uvsActInt;
             GCharItem -> type = uvsSetItemType(pg -> GoodsTypeBeg, 0, 0);
             GCharItem -> param1 = Pescave -> Pworld -> gIndex<<16;
             GCharItem -> price = ((uvsSpot*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg];
             GCharItem -> sell_price = ((uvsSpot*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg + MAX_ITEM_TYPE];
 //          ((uvsSpot*)(pg -> townBeg)) -> Pshop -> addItem( new uvsItem(pg -> GoodsTypeBeg));
         }
     }   else if ((!strcmp( aci_curLocationName,  name)) && Gamer -> status == UVS_VANGER_STATUS::IN_SHOP) {
         uvsEndHarvest = 1;
         if(GCharItem) delete GCharItem;
         GCharItem = NULL;
         GamerResult.get_weezyk = 1;
         pg -> flag = 1;
         if ( (GamerResult.luck + GamerResult.add_luck > RND(100)) && pg -> GoodsBegCount){
             pg -> GoodsBegCount--;
             GamerResult.get_weezyk = 2;
             pg -> flag = 2;
             pg -> start = 0;
             if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE){
                 GCharItem = new uvsActInt;
                 GCharItem -> type = uvsSetItemType(pg -> GoodsTypeBeg, 0, 0);
                 GCharItem -> param1 = Pescave -> Pworld -> gIndex<<16;
                 GCharItem -> price = ((uvsEscave*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg];
                 GCharItem -> sell_price = ((uvsEscave*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg + MAX_ITEM_TYPE];
     //          ((uvsEscave*)(pg -> townBeg)) -> Pshop -> addItem( new uvsItem(pg -> GoodsTypeBeg));
             } else {
                 GCharItem = new uvsActInt;
                 GCharItem -> type = uvsSetItemType(pg -> GoodsTypeBeg, 0, 0);
                 GCharItem -> param1 = Pescave -> Pworld -> gIndex<<16;
                 GCharItem -> price = ((uvsSpot*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg];
                 GCharItem -> sell_price = ((uvsSpot*)(pg -> townBeg)) -> Pshop -> Price[pg -> GoodsTypeBeg + MAX_ITEM_TYPE];
     //          ((uvsSpot*)(pg -> townBeg)) -> Pshop -> addItem( new uvsItem(pg -> GoodsTypeBeg));
             }
         } else
             addGOODS_any(pg);
     }
     uvsVanger* v = FindFreeVanger();
     if (v){
         v -> shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
         if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE ){
             v -> Pescave =  ((uvsEscave*)(pg -> townBeg));
             v -> Pspot = NULL;
             v -> Pworld = v -> Pescave -> Pworld;
             v -> status = UVS_VANGER_STATUS::ESCAVE_WAITING;
         }else{
             v -> Pescave = NULL;
             v -> Pspot =  ((uvsSpot*)(pg -> townBeg));
             v -> Pworld = v -> Pspot -> Pworld;
             v -> status = UVS_VANGER_STATUS::SPOT_WAITING;
         }
         v -> add_to_game(pg);
         v -> locTimer = RACE_WAIT + (RACE_WAIT*(GamerResult.dominance+GamerResult.add_dominance))/100;
     }
     uvsElement* e = ETail;
     while(e){
         if( ((uvsVanger*)e) -> type == UVS_OBJECT::VANGER && (((uvsVanger*)e) -> status == UVS_VANGER_STATUS::ESCAVE_WAITING ||
             ((uvsVanger*)e) -> status == UVS_VANGER_STATUS::SPOT_WAITING)) {
 #ifdef _ROAD_
             if ( ((uvsVanger*)e) -> shape != UVS_VANGER_SHAPE::GAMER ){
 #endif
             if (((uvsVanger*)e) -> add_to_game( pg ) )
                 ((uvsVanger*)e) -> locTimer = RACE_WAIT +  (RACE_WAIT*(GamerResult.dominance+GamerResult.add_dominance))/100;
             else if (((uvsVanger*)e) -> status == UVS_VANGER_STATUS::SPOT_WAITING)
                 ((uvsVanger*)e) -> status = UVS_VANGER_STATUS::SPOT_SLEEPING;
             else
                 ((uvsVanger*)e) -> status = UVS_VANGER_STATUS::ESCAVE_SLEEPING;
 #ifdef _ROAD_
         }
 #endif
         }
         e = e -> enext;
     }
 }
References aci_curLocationName, uvsGamerResult::add_dominance, uvsGamerResult::add_luck, addGOODS_any(), UVS_VANGER_SHAPE::BUNCH_SLAVE, ConTimer, currentStage, cycleTable, uvsGamerResult::dominance, UVS_TOWN::ESCAVE, UVS_VANGER_STATUS::ESCAVE_SLEEPING, UVS_VANGER_STATUS::ESCAVE_WAITING, ETail, FindFreeVanger(), Gamer, UVS_VANGER_SHAPE::GAMER, GamerResult, GCharItem, uvsGamerResult::get_weezyk, uvsContimer::GetTime(), UVS_VANGER_STATUS::IN_SHOP, uvsGamerResult::luck, MAX_ITEM_TYPE, NULL, Pescave, uvsCultStage::Pgame, RACE_WAIT, RND(), UVS_VANGER_STATUS::SPOT_SLEEPING, UVS_VANGER_STATUS::SPOT_WAITING, status, uvsEndHarvest, uvsSetItemType(), V_RACE_VANGER, and UVS_OBJECT::VANGER.
Referenced by begin_game().
bring_game_GOODS()
int uvsBunch::bring_game_GOODS (char * Pname, listElem *& pe)
{
     uvsCultGame* pg = cycleTable[currentStage].Pgame;
     if ( !pg ) return 0;
     switch(pg -> GameType){
     case UVS_GAME_TYPE::RACE:
         return bring_race_GOODS(Pname, pe);
         break;
     case UVS_GAME_TYPE::HARVEST:
         return bring_harvest_GOODS(Pname, pe);
         break;
     }
     return 0;
 }
References bring_harvest_GOODS(), bring_race_GOODS(), currentStage, cycleTable, UVS_GAME_TYPE::HARVEST, uvsCultStage::Pgame, and UVS_GAME_TYPE::RACE.
bring_harvest_GOODS()
int uvsBunch::bring_harvest_GOODS (char * Pname, listElem *& pe)
{
     char *nn;
     uvsCultGame* pg = cycleTable[currentStage].Pgame;
     uvsItem *pi = NULL;
     int GoodsType = -1, count;
     if ( (pg -> typeTownEnd == UVS_TOWN::ESCAVE && !strcmp( nn = ((uvsEscave*)(pg -> townEnd)) -> name, Pname))
         || ( pg -> typeTownEnd == UVS_TOWN::SPOT && !strcmp( nn = ((uvsSpot*)(pg -> townEnd)) -> name, Pname)) ) {
         GoodsType = pg -> GoodsTypeBeg;
     }
     if ( GoodsType != -1 ){
         pi = GetItem( pe, GoodsType, 0 );
         if (pi)
             count = ItemCount( pe, GoodsType );
         else
             count = 0;
         while( pi ){
             pi -> delink( pe );
             delete pi;
             pi = GetItem( pe, pg -> GoodsTypeEnd, 0 );
         }
         //
         if ( count ){
             pg -> score[pg -> total++] = count;
 #ifdef STAND_REPORT
             stand < ConTimer.GetTime();
             stand < "\t in " < nn < " finished with " <= count < " corns  <- any vanger \n";
 #endif
         return (V_RACE_SCORE*(count));
         }
     }
     return 0;
 }
References ConTimer, currentStage, cycleTable, UVS_TOWN::ESCAVE, GetItem(), uvsContimer::GetTime(), ItemCount(), NULL, uvsCultStage::Pgame, UVS_TOWN::SPOT, and V_RACE_SCORE.
Referenced by bring_game_GOODS().
bring_race_GOODS()
int uvsBunch::bring_race_GOODS (char * Pname, listElem *& pe)
{
     char *nn;
     uvsCultGame* pg = cycleTable[currentStage].Pgame;
     uvsItem* pi;
     if ( (pg -> typeTownEnd == UVS_TOWN::ESCAVE && !strcmp( nn = ((uvsEscave*)(pg -> townEnd)) -> name, Pname))
         || ( pg -> typeTownEnd == UVS_TOWN::SPOT && !strcmp( nn = ((uvsSpot*)(pg -> townEnd)) -> name, Pname)) ) {
         pi = GetItem( pe, pg -> GoodsTypeEnd, 0 );
         if ( pi ){
             pg -> result++;
 #ifdef STAND_REPORT
             stand < ConTimer.GetTime();
             stand < "\t in " < nn < " with result " <= pg -> result < "  <- ";
 #endif
         }
         while( pi ){
             pi -> delink( pe );
             delete pi;
             pi = GetItem( pe, pg -> GoodsTypeEnd, 0 );
         }
         if ( pg -> GoodsEndCount  && pi ){
             pg -> GoodsEndCount--;
             return (V_RACE_SCORE*(pg -> GoodsEndCount+1));
         }
 #ifdef STAND_REPORT
         else if ( pi )
             stand < " finished any\n";
 #endif
     }
     return 0;
 }
References ConTimer, currentStage, cycleTable, UVS_TOWN::ESCAVE, GetItem(), uvsContimer::GetTime(), uvsCultStage::Pgame, UVS_TOWN::SPOT, and V_RACE_SCORE.
Referenced by bring_game_GOODS().
Check()
void uvsBunch::Check (char * subj)
{
     int i;
     for(i = 0;i < cycleN;i++){
         if (cycleTable[i].Pdolly -> gIndex !=  (biosNindex*3 + i + 1))
             ErrH.Abort("Bunch Dolly incorrect", XERR_USER, -1, subj);
     }
 }
References XErrorHandler::Abort(), biosNindex, cycleN, cycleTable, ErrH, and XERR_USER.
end_game()
void uvsBunch::end_game (void)
{
     uvsCultGame *pg = cycleTable[currentStage].Pgame;
     switch( pg -> GameType ){
     case UVS_GAME_TYPE::RACE:
         end_race();
         break;
     case UVS_GAME_TYPE::HARVEST:
         end_harvest();
         break;
     }
 }
References currentStage, cycleTable, end_harvest(), end_race(), UVS_GAME_TYPE::HARVEST, uvsCultStage::Pgame, and UVS_GAME_TYPE::RACE.
Referenced by Quant().
end_harvest()
void uvsBunch::end_harvest (void)
{
     uvsCultGame *pg = cycleTable[currentStage].Pgame;
     uvsItem* pi;
     uvsElement*& Panymal = Pescave -> Pworld -> Panymal;
     uvsElement* pe;
     int i, count;
     if (pg -> result && GamerResult.game_result && (GamerResult.last_game_type == UVS_GAME_ID::PIPETKA || GamerResult.last_game_type == UVS_GAME_ID::KERNOBOO)){
         uvsEndHarvest = 1;
         count = 1;
         pg -> result--;
         for( i = 0; i < pg -> result; i++)
                 if ( pg -> score[i] >= GamerResult.game_result ) count++;
         for( i = pg -> result; i < pg -> total; i++)
                 if ( pg -> score[i] > GamerResult.game_result ) count++;
             pg -> result = count;
             count = GamerResult.game_result;
             GamerResult.game_result = pg -> result;
             uvsCheckKronIventTabuTask(UVS_KRON_EVENT::END_RACE, count, pg -> result, pg -> GoodsTypeBeg);
             if ( pg -> result == 1 ){
                 if ((pg -> total > 0) && (pg -> total - pg -> first > 0)){
                     GamerResult.luck += pg -> total - pg -> first;
                     ShowLuckMessage(pg -> total - pg -> first);
                     if (GamerResult.luck > 100) GamerResult.luck = 100;
                 }
                 pg -> first++;
             }
             if ( pg -> result <= V_RACE_VANGER ){
     #ifdef _ROAD_
                 //aciCurCredits += BONUS[pg -> result-1];
     #endif
                 GamerResult.game_total  =  ++pg -> total;
                 if (GamerResult.game_total > 1){
                     if ( !strcmp( ((uvsSpot*)(pg -> townEnd)) -> name , "Lampasso") )
                         GamerResult.last_game_type = UVS_GAME_ID::KERNOBOO;
                         //GamerResult.game_ker_result += GAME_RAITING[ pg -> result-1];
                     else if (!strcmp( ((uvsSpot*)(pg -> townEnd)) -> name , "Ogorod"))
                         GamerResult.last_game_type = UVS_GAME_ID::PIPETKA;
                         //GamerResult.game_pip_result += GAME_RAITING[ pg -> result-1];
                 }
             }
             if (pg -> total <= pg -> result && pg -> result > 1){
                 GamerResult.luck -= 5;
                 ShowLuckMessage(-5);
                 if (GamerResult.luck < 0) GamerResult.luck = 0;
             }
             pg -> all++;
     }
 #ifdef _ROAD_
     //if ( CurrentWorld != -1 ){
     if ( uvsKronActive ){
         if (uvsapiDestroyItem(  pg -> GoodsTypeBeg, pg -> GoodsTypeLast )){
 /*          GamerResult.luck -= 10;*/
             if (GamerResult.luck < 0) GamerResult.luck = 0;
         }
     } else {
         if (uvs_aciKillItem(uvsSetItemType(pg -> GoodsTypeBeg, 0, 1), uvsSetItemType(pg -> GoodsTypeLast, 0, 1))){
 /*          GamerResult.luck -= 10;*/
             if (GamerResult.luck < 0) GamerResult.luck = 0;
         }
     }
 #endif
     //     KRONa
     while(Panymal){
         pe = Panymal;
         Panymal = Panymal -> enext;
         if ( pe -> type == UVS_OBJECT::FLY_FARMER ){
             Pescave -> Pworld -> remove_target( (uvsTarget*)((uvsFlyFarmer*)pe), UVS_TARGET::FLY_FARMER);
 //          pe -> delink(Pescave -> Pworld -> Panymal);
             delete (uvsFlyFarmer*)pe;
         }
     }
     Panymal = NULL;
     for (i = 0; i < WORLD_MAX; i++ ){
         listElem*& Item = WorldTable[i] -> Pitem;
         pi = GetItem( Item, (pg -> GoodsTypeBeg), 0);
         while ( pi ){
             ((uvsItem*)pi) -> delink(Item);
             delete (uvsItem*)pi;
             pi = GetItem( Item, (pg -> GoodsTypeBeg), 0);
         }//  while
     }//  for i
     uvsElement* e = ETail;
     while(e){
         if( ((uvsVanger*)e) -> type == UVS_OBJECT::VANGER ){
             pi = GetItem( ((uvsVanger*)e) -> Pitem, pg -> GoodsTypeBeg, 0);
             while ( pi ){
                 ((uvsItem*)pi) -> delink( ((uvsVanger*)e) -> Pitem);
                 delete (uvsItem*)pi;
                 pi = GetItem( ((uvsVanger*)e) -> Pitem, pg -> GoodsTypeBeg, 0);
             }//  while
         }
         e = e -> enext;
     }//  while
 /*  uvsActInt* pr  = GItem;
     uvsActInt* pl;
     while(pr){
         if (pr -> type == uvsSetItemType(pg -> GoodsTypeBeg, 0, 0) ){
             pl = pr;
             pr = (uvsActInt*)pr -> next;
             pl -> delink(GItem);
             delete pl;
         } else
             pr = (uvsActInt*)pr -> next;
     }*/
 #ifdef STAND_REPORT
     stand < "\n" < ConTimer.GetTime();
     if (GamerResult.game_result)
         stand < "\t in " <= pg -> result < " position  <- GAMER FINISH  \n";
     stand < "\n" < "Harvest Finished " <= pg -> total < " vangers play this.\n\n\n";
 #endif
     /*delete (pg -> score);
     pg -> score = NULL;*/
     pg -> total = 0;
 }
References ConTimer, currentStage, cycleTable, UVS_KRON_EVENT::END_RACE, ETail, UVS_OBJECT::FLY_FARMER, UVS_TARGET::FLY_FARMER, uvsGamerResult::game_result, uvsGamerResult::game_total, GamerResult, GetItem(), uvsContimer::GetTime(), UVS_GAME_ID::KERNOBOO, uvsGamerResult::last_game_type, uvsGamerResult::luck, NULL, Pescave, uvsCultStage::Pgame, UVS_GAME_ID::PIPETKA, ShowLuckMessage(), uvs_aciKillItem(), uvsapiDestroyItem(), uvsCheckKronIventTabuTask(), uvsEndHarvest, uvsKronActive, uvsSetItemType(), V_RACE_VANGER, UVS_OBJECT::VANGER, WORLD_MAX, and WorldTable.
Referenced by end_game().
end_race()
void uvsBunch::end_race (void)
{
     uvsCultGame *pg = cycleTable[currentStage].Pgame;
     uvsItem* pi;
 #ifdef _ROAD_
     //if ( CurrentWorld != -1 ){
     if ( uvsKronActive ){
         if (uvsapiDestroyItem(  pg -> GoodsTypeBeg, pg -> GoodsTypeLast ) || (GamerResult.get_eleech && pg -> GoodsTypeBeg == UVS_ITEM_TYPE::ELEECH ) ){
             GamerResult.luck -= 10;
             ShowLuckMessage(-10);
             if (GamerResult.luck < 0) GamerResult.luck = 0;
             pg -> all++;
             pg -> sucks++;
             if (pg -> GoodsTypeBeg == UVS_ITEM_TYPE::ELEECH)
                 GamerResult.dead_eleech = 1;
             else
                 GamerResult.dead_weezyk = 1;
     #ifdef STAND_REPORT
             stand < "\n" < "GAMER NOT FINISHED\n";
     #endif
         }
     } else {
 #ifdef _ROAD_
         if (uvs_aciKillItem(uvsSetItemType(pg -> GoodsTypeBeg, 0, -1), uvsSetItemType(pg -> GoodsTypeLast, 0, -1)) ||
             (GamerResult.get_eleech && pg -> GoodsTypeBeg == UVS_ITEM_TYPE::ELEECH)){
             GamerResult.luck -= 10;
             ShowLuckMessage(-10);
             if (GamerResult.luck < 0) GamerResult.luck = 0;
             pg -> all++;
             pg -> sucks++;
             if (pg -> GoodsTypeBeg == UVS_ITEM_TYPE::ELEECH)
                 GamerResult.dead_eleech = 1;
             else
                 GamerResult.dead_weezyk = 1;
     #ifdef STAND_REPORT
             stand < "\n" < "GAMER NOT FINISHED\n";
     #endif
         }
 #endif
     }
 #endif
     if (GCharItem && GCharItem -> type == uvsSetItemType(pg -> GoodsTypeBeg, 0, 0) ){
         delete GCharItem;
         GCharItem = NULL;
     }
 /*
     if (!pg -> GoodsTypeBegCount) {
         if ( pg -> typeBeg ){
             pi = GetItem( ((uvsEscave*)(pg -> townBeg)) -> Pshop -> Pitem, (pg -> GoodsTypeBeg), 0);
             while ( pi )  {
                 ((uvsItem*)pi) -> delink(((uvsEscave*)(pg -> townBeg)) -> Pshop -> Pitem);
                 delete (uvsItem*)pi;
                 pi = GetItem( ((uvsEscave*)(pg -> townBeg)) -> Pshop -> Pitem, (pg -> GoodsTypeBeg), 0);
             }
         } else {
             pi = GetItem( ((uvsSpot*)(pg -> townBeg)) -> Pshop -> Pitem, (pg -> GoodsTypeBeg), 0);
             while ( pi ){
                 ((uvsItem*)pi) -> delink(((uvsSpot*)(pg -> townBeg)) -> Pshop -> Pitem);
                 delete (uvsItem*)pi;
                 pi = GetItem( ((uvsSpot*)(pg -> townBeg)) -> Pshop -> Pitem, (pg -> GoodsTypeBeg), 0);
             }
         }
     }*/
     for ( int i = 0; i < WORLD_MAX; i++ ){
         listElem*& Item = WorldTable[i] -> Pitem;
         pi = GetItem( Item, (pg -> GoodsTypeBeg), 0);
         while ( pi ){
             ((uvsItem*)pi) -> delink(Item);
             delete (uvsItem*)pi;
             pi = GetItem( Item, (pg -> GoodsTypeBeg), 0);
         }
     }
     uvsElement* e = ETail;
     while(e){
         if( ((uvsVanger*)e) -> type == UVS_OBJECT::VANGER ){
             pi = GetItem( ((uvsVanger*)e) -> Pitem, pg -> GoodsTypeBeg, 0);
             while ( pi ){
                 ((uvsItem*)pi) -> delink( ((uvsVanger*)e) -> Pitem);
                 delete (uvsItem*)pi;
                 pi = GetItem( ((uvsVanger*)e) -> Pitem, pg -> GoodsTypeBeg, 0);
             }//  end while
         }//  end while
         e = e -> enext;
     }
 #ifdef STAND_REPORT
     stand < "\n" < ConTimer.GetTime();
     stand < "\n" < "Race Finished " <= pg -> total < "\n\n\n";
 #endif
 }
References ConTimer, currentStage, cycleTable, uvsGamerResult::dead_eleech, uvsGamerResult::dead_weezyk, UVS_ITEM_TYPE::ELEECH, ETail, GamerResult, GCharItem, uvsGamerResult::get_eleech, GetItem(), uvsContimer::GetTime(), uvsGamerResult::luck, NULL, uvsCultStage::Pgame, ShowLuckMessage(), uvs_aciKillItem(), uvsapiDestroyItem(), uvsKronActive, uvsSetItemType(), UVS_OBJECT::VANGER, WORLD_MAX, and WorldTable.
Referenced by end_game().
game_exit()
int uvsBunch::game_exit (void)
{
     int i;
     if (cycleTable[currentStage].Pdolly -> status || cycleTable[currentStage].Pdolly -> Pworld -> gIndex > 3) return 0;
     for ( i = 1; i <= cycleN; i++){
         int stage = (i + currentStage)%cycleN;
         uvsCultGame *pg = cycleTable[stage].Pgame;
         if (cycleTable[stage].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE) continue;
         if ( pg ){
             char *name;
             switch(pg -> GameType){
             case UVS_GAME_TYPE::RACE:
                 if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE )
                     name  = ((uvsEscave*)(pg -> townBeg)) -> name;
                 else
                     name = ((uvsSpot*)(pg -> townBeg)) -> name;
 #ifdef _ROAD_
                 if ( !strcmp( aci_curLocationName,  name) ) return stage;
 #endif
                 break;
             case UVS_GAME_TYPE::HARVEST:
                 return stage;
                 break;
             }//  end switch
         }//  end if
     }//  end for
     return -1;
 }
References aci_curLocationName, currentStage, cycleN, cycleTable, UVS_TOWN::ESCAVE, UVS_GAME_TYPE::HARVEST, uvsCultStage::Pgame, UVS_GAME_TYPE::RACE, status, and UVS_DOLLY_STATUS::UNABLE.
game_now()
int uvsBunch::game_now (char * Pname, uvsCultGame *& Pg)
{
     uvsCultGame* pg = cycleTable[currentStage].Pgame;
     Pg = NULL;
     if ( !pg ) return 0;
     //if ( (!pg -> GoodsEndCount || (!pg -> GoodsBegCount) && pg -> total > 6 )) return 0;
     if ( (!pg -> GoodsEndCount) || (!pg -> GoodsBegCount) || (pg -> total > V_RACE_VANGER )) return 0;
     Pg = pg;
     switch (pg -> GameType ){
         case UVS_GAME_TYPE::RACE:
             if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE && !strcmp(((uvsEscave*)(pg -> townBeg) ) -> name, Pname) ) return 1;
             if ( pg -> typeTownBeg == UVS_TOWN::SPOT && !strcmp(((uvsSpot*)(pg -> townBeg) ) -> name, Pname) ) return 1;
         break;
     }
     return 0;
 }
References UVS_TOWN::ESCAVE, uvsEscave::name, NULL, UVS_GAME_TYPE::RACE, UVS_TOWN::SPOT, and V_RACE_VANGER.
game_soon()
int uvsBunch::game_soon (char * Pname)
{
     int i = 1;
     if (cycleTable[currentStage].Pdolly -> status || cycleTable[currentStage].Pdolly -> Pworld -> gIndex > 3) return 0;
     while(cycleTable[(currentStage+i)%cycleN].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE){
         i++;
         if ( i >= cycleN) return 0;
     }
     uvsCultGame* pg = cycleTable[(currentStage+i)%cycleN].Pgame;
     if ( !pg ) return 0;
     switch (pg -> GameType ){
         case UVS_GAME_TYPE::RACE:
             if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE && !strcmp(((uvsEscave*)(pg -> townBeg)) -> name, Pname)) return 1;
             if ( pg -> typeTownBeg == UVS_TOWN::SPOT && !strcmp(((uvsSpot*)(pg -> townBeg)) -> name, Pname)) return 1;
         break;
     }
     return 0;
 }
References currentStage, cycleN, cycleTable, UVS_TOWN::ESCAVE, UVS_GAME_TYPE::RACE, UVS_TOWN::SPOT, status, and UVS_DOLLY_STATUS::UNABLE.
game_wait_end()
int uvsBunch::game_wait_end (void)
{
     int i;
     uvsCultGame *pg = cycleTable[currentStage].Pgame;
     if ( pg  &&  pg -> GameType == UVS_GAME_TYPE::HARVEST && !cycleTable[currentStage].Pdolly -> status  && cycleTable[currentStage].Pdolly -> Pworld -> gIndex < 4){
         i = nextCycle();
         return i;
     }
     return -1;
 }
References currentStage, cycleTable, UVS_GAME_TYPE::HARVEST, nextCycle(), uvsCultStage::Pgame, and status.
GetCirtQ()
int uvsBunch::GetCirtQ (void) inline
 { return cycleTable[currentStage].cirtQ; }
References uvsCultStage::cirtQ, currentStage, and cycleTable.
GetCurrentStageName()
char* uvsBunch::GetCurrentStageName (void) inline
 { return cycleTable[currentStage].name; }
References currentStage, cycleTable, and uvsCultStage::name.
nextCycle()
int uvsBunch::nextCycle (void)
{
     int i = currentStage + 1;
     int _i = 0;
     if ( status == UVS_BUNCH_STATUS::UNABLE ) return -1;
     if( i == cycleN) i = 0;
     while( cycleTable[i].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE  ){
         if(++i == cycleN) i = 0;
         _i++;
         if (_i > cycleN) {
             status = UVS_BUNCH_STATUS::UNABLE;
             currentStage = 0;
             if( Pescave -> Pworld -> gIndex == Gamer -> Pworld -> gIndex ) {
                 uvsCurrentCycle = 0;
                 uvsCurrentWorldUnable = 1;
             }
             return -1;
         }
     }//  end while
     return i;
 }
References currentStage, cycleN, cycleTable, Gamer, Pescave, status, UVS_BUNCH_STATUS::UNABLE, UVS_DOLLY_STATUS::UNABLE, uvsCurrentCycle, and uvsCurrentWorldUnable.
Referenced by game_wait_end().
Quant()
void uvsBunch::Quant (void)
{
     if ( status == UVS_BUNCH_STATUS::UNABLE ) return;
     if(--vngResource < 0)  randVRes();;
     int& cv = cycleTable[currentStage].cirtQ;
     int mv = cycleTable[currentStage].cirtMAX;
     if (cycleTable[currentStage].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE )
         cv = mv +1;
     if(cv >= mv){
         int _i = 0;
         uvsWorld* pw = Pescave -> Pworld;
         pw -> updateResource();
         cv -= mv;
         if ( cycleTable[currentStage].Pgame && !NetworkON ) end_game();
         if(++currentStage == cycleN) currentStage = 0;
         while( cycleTable[currentStage].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE  ){
             if(++currentStage == cycleN) currentStage = 0;
             _i++;
             if (_i > cycleN) {
                 status = UVS_BUNCH_STATUS::UNABLE;
                 currentStage = 0;
                 //if( Pescave -> Pworld -> gIndex == CurrentWorld ) uvsCurrentCycle = 0;
                 if( Pescave -> Pworld -> gIndex == Gamer -> Pworld -> gIndex ) {
                     uvsCurrentCycle = 0;
                     uvsCurrentWorldUnable = 1;
                 }
 #ifdef STAND_REPORT
             stand < ConTimer.GetTime();
             stand < "  bunch  in " < Pescave -> name < " on stage " <= currentStage < " unable\n";
 #endif
                 return;
             }
         }
         uvsChangeGoodsInList( Pescave -> Pworld -> gIndex);
         if( Pescave -> Pworld -> gIndex == Gamer -> Pworld -> gIndex ) {
             uvsCurrentCycle = currentStage;
             SOUND_CYCLE();
         }
 #ifdef STAND_REPORT
         stand <  ConTimer.GetTime() < "\t changed cycle in "< Pescave -> Pworld -> name < " on :: "< cycleTable[currentStage].name < "\n\n";
 #endif
 #ifdef _ROAD_
         if(pw -> gIndex == CurrentWorld){
             BunchEvent( BUNCH_CHANGE_CYCLE );
         }
 #endif
         if ( cycleTable[currentStage].Pgame && !NetworkON) begin_game();
     }
 }
References begin_game(), BUNCH_CHANGE_CYCLE, BunchEvent(), uvsCultStage::cirtMAX, uvsCultStage::cirtQ, ConTimer, currentStage, CurrentWorld, cycleN, cycleTable, end_game(), Gamer, uvsContimer::GetTime(), uvsCultStage::name, NetworkON, Pescave, randVRes(), SOUND_CYCLE, status, UVS_BUNCH_STATUS::UNABLE, UVS_DOLLY_STATUS::UNABLE, uvsChangeGoodsInList(), uvsCurrentCycle, uvsCurrentWorldUnable, and vngResource.
QuantCirt()
void uvsBunch::QuantCirt (int counter)
{
     int i;
     for(i = 0; i < cycleN; i++){
         if( i != currentStage && (counter%cycleTable[i].time == 0)){
             cycleTable[i].cirtQ >>= 1;
         }
     }
 }
References uvsCultStage::cirtQ, counter, currentStage, cycleN, and cycleTable.
randVRes()
void uvsBunch::randVRes (void) inline
 { vngResource = RND(V_PRICE) + V_PRICE/2; }
References RND(), V_PRICE, and vngResource.
Referenced by Quant().
real_hunter_now()
int uvsBunch::real_hunter_now (uvsVanger * pv)
{
     uvsCultStage &pc = cycleTable[currentStage];
     uvsCultGame* pg = pc.Pgame;
     if (pc.Pdolly -> status == UVS_DOLLY_STATUS::UNABLE) return 0;
     if ( !pg ) return 0;
     if (pg -> GameType == UVS_GAME_TYPE::RACE){
         if (pg -> start){
             if (pg -> GoodsBegCount > 0){
                 pv -> addItem( new uvsItem(pg -> GoodsTypeBeg), 1);
                 pg -> GoodsBegCount--;
             }
             return 1;
         }//  end if pg -> start
         return 0;
     }//  end if pg -> GameType
     return 0;
 }
References currentStage, cycleTable, uvsCultStage::Pdolly, uvsCultStage::Pgame, UVS_GAME_TYPE::RACE, status, and UVS_DOLLY_STATUS::UNABLE.
save()
void uvsBunch::save (XStream & pfile)
{
     int i, j;
     for(i = 0;i < cycleN;i++){
         pfile < cycleTable[i].cirtQ;
         pfile < cycleTable[i].GamerCirt;
         if ( cycleTable[i].Pgame ){
              pfile < cycleTable[i].Pgame -> GoodsBegCount;
              pfile < cycleTable[i].Pgame -> GoodsEndCount;
              pfile < cycleTable[i].Pgame -> result;
              pfile < cycleTable[i].Pgame -> total;
              pfile < cycleTable[i].Pgame -> flag;
              pfile < cycleTable[i].Pgame -> first;
              pfile < cycleTable[i].Pgame -> all;
              pfile < cycleTable[i].Pgame -> sucks;
              pfile < cycleTable[i].Pgame -> start;
              if ( cycleTable[i].Pgame -> GameType == UVS_GAME_TYPE::HARVEST ){
                 for(j = 0; j < cycleTable[i].Pgame -> total; j++)
                     pfile < cycleTable[i].Pgame -> score[j];
             }
         }
         pfile < cycleTable[i].Pdolly -> gIndex;
     }
     pfile < currentStage;
     pfile <  vngResource;
     pfile <  status;
 }
References uvsCultStage::cirtQ, currentStage, cycleN, cycleTable, uvsCultStage::GamerCirt, UVS_GAME_TYPE::HARVEST, uvsCultStage::Pdolly, uvsCultStage::Pgame, status, and vngResource.
Member Data Documentation
biosNindex
int uvsBunch::biosNindex
Referenced by Check(), and uvsBunch().
currentStage
int uvsBunch::currentStage
Referenced by begin_game(), begin_harvest(), begin_race(), bring_game_GOODS(), bring_harvest_GOODS(), bring_race_GOODS(), end_game(), end_harvest(), end_race(), game_exit(), game_soon(), game_wait_end(), GetCirtQ(), GetCurrentStageName(), nextCycle(), OpenCyclicPal(), PalettePrepare(), Quant(), QuantCirt(), real_hunter_now(), save(), and uvsBunch().
cycleN
int uvsBunch::cycleN
Referenced by Check(), game_exit(), game_soon(), nextCycle(), OpenCyclicPal(), Quant(), QuantCirt(), save(), uvsBunch(), and ~uvsBunch().
cycleTable
uvsCultStage* uvsBunch::cycleTable
Referenced by begin_game(), begin_harvest(), begin_race(), bring_game_GOODS(), bring_harvest_GOODS(), bring_race_GOODS(), Check(), end_game(), end_harvest(), end_race(), game_exit(), game_soon(), game_wait_end(), GetCirtQ(), GetCurrentStageName(), nextCycle(), Quant(), QuantCirt(), real_hunter_now(), save(), uvsBunch(), and ~uvsBunch().
id
int uvsBunch::id
Pescave
uvsEscave* uvsBunch::Pescave
Referenced by begin_harvest(), begin_race(), end_harvest(), nextCycle(), Quant(), and uvsBunch().
status
int uvsBunch::status
Referenced by addGOODS_any(), begin_race(), game_exit(), game_soon(), game_wait_end(), nextCycle(), Quant(), real_hunter_now(), save(), and uvsBunch().
vngResource
int uvsBunch::vngResource
Referenced by Quant(), randVRes(), save(), and uvsBunch().
The documentation for this struct was generated from the following files:
src/uvs/univang.h
src/uvs/univang.cpp