Vangers: UnitBaseListType Struct Reference
UnitBaseListType Struct Reference
#include <hobj.h>
Public Member Functions
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Init (void)
virtual void Free (void)
virtual void Quant (void)
virtual void NetEvent (int type, int id)
virtual void FreeUnit (GeneralObject *p)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Additional Inherited Members
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
ConnectTypeList()
void UnitBaseListType::ConnectTypeList (GeneralObject * p) virtual
Reimplemented from UnitListType.
 {
     if(!Tail){
         p -> NextTypeList = p -> PrevTypeList = NULL;
         Tail = p;
     }else{
         Tail -> PrevTypeList = p;
         p -> NextTypeList = Tail;
         p -> PrevTypeList = NULL;
         Tail = p;
     };
     Num++;
     GameD.ConnectBaseList((BaseObject*)p);
 };
References GameObjectDispatcher::ConnectBaseList(), GameD, NULL, UnitListType::Num, and UnitListType::Tail.
Referenced by JumpBallList::CreateBall(), BulletList::CreateBullet(), DebrisList::CreateDebris(), HordeList::CreateHorde(), SkyFarmerList::CreateSkyFarmer(), HordeSourceList::CreateSource(), ClefList::Init(), FishWarriorList::Init(), and InsectList::Init().
DisconnectTypeList()
void UnitBaseListType::DisconnectTypeList (GeneralObject * p) virtual
Reimplemented from UnitListType.
 {
     GameD.DisconnectBaseList((BaseObject*)p);
     if((!p->PrevTypeList) && (!p->NextTypeList)) Tail = NULL;
     else{
         if(p->PrevTypeList) p->PrevTypeList->NextTypeList = p->NextTypeList;
         else Tail = p->NextTypeList;
         if(p->NextTypeList) p->NextTypeList->PrevTypeList = p->PrevTypeList;
     };
     Num--;
 };
References GameObjectDispatcher::DisconnectBaseList(), GameD, GeneralObject::NextTypeList, NULL, UnitListType::Num, GeneralObject::PrevTypeList, and UnitListType::Tail.
Referenced by BulletList::FreeUnit(), ClefList::FreeUnit(), FishWarriorList::FreeUnit(), and InsectList::FreeUnit().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp