Vangers: GunDevice Struct Reference
GunDevice Struct Reference
#include <items.h>
Public Member Functions
void CreateGun (void)
int CheckTarget (ActionUnit *p)
void DeviceLoad (Parser &in)
void GetDevice (StuffObject *p)
void DeviceIn (void)
void DeviceOut (Vector v1, int flag=1, Vector v2=Vector(-1,-1,-1))
void Quant (void)
void DeviceQuant (void)
Public Member Functions inherited from StuffObject
void Init (StorageType *s)
void Quant (void)
void DrawQuant (void)
void Touch (GeneralObject *p)
void CreateStuff (const Vector &_v, StuffObject *p, int cMode)
void CreateDevice (Vector v, VangerUnit *own, StuffObject *p)
virtual void Active (void)
virtual void Deactive (void)
void NetEvent (int type, int id, int creator, int x, int y)
void NetDeviceEvent (int type, int id, int creator, int x, int y)
void NetOwnerQuant (int impulse=0)
int GetTouchSensor (const char *name)
void ImpulseAction (Vector v1, int flag, Vector v2)
int CheckItemOver (void)
void SetStuffColor (void)
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
virtual int test_objects_collision ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Attributes
WorldBulletTemplate * pData
Public Attributes inherited from StuffObject
int StuffType
int ModelID
int uvsDeviceType
actintItemData ActIntBuffer
VangerUnit * Owner
int CreateMode
int DataID
int SizeID
StuffObject * NextDeviceList
StuffObject * PrevDeviceList
LightPoint * LightData
int CycleTime
VangerUnit * PrevOwner
int NetDeviceID
int xImpulse
int yImpulse
int OutFlag
int NetOwner
int Hour
int Minutes
int Time
int FindDolly
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Detailed Description
Member Function Documentation
CheckTarget()
int GunDevice::CheckTarget (ActionUnit * p)
CreateGun()
void GunDevice::CreateGun (void)
 {
     PrevOwner = NULL;
     if(uvsDeviceType == UVS_ITEM_TYPE::AMPUTATOR || uvsDeviceType == UVS_ITEM_TYPE::DEGRADATOR || uvsDeviceType == UVS_ITEM_TYPE::MECHOSCOPE)
         set_body_color(COLORS_IDS::BODY_GRAY);
 //  ActIntBuffer.data1 = 0;
 //  ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
 };
References UVS_ITEM_TYPE::AMPUTATOR, COLORS_IDS::BODY_GRAY, UVS_ITEM_TYPE::DEGRADATOR, UVS_ITEM_TYPE::MECHOSCOPE, NULL, StuffObject::PrevOwner, Object::set_body_color(), and StuffObject::uvsDeviceType.
DeviceIn()
void GunDevice::DeviceIn (void) virtual
Reimplemented from StuffObject.
 {
     StuffObject::DeviceIn();
     if(pData->BulletID == BULLET_TYPE_ID::HYPNOTISE){
         switch(ActIntBuffer.type){
             case ACI_AMPUTATOR:
                 EffD.CreateDeform(Owner->R_curr,DEFORM_ALL,PASSING_WAVE_PROCESS);
                 if(ActD.Active)
                     SOUND_AMPUTATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
             case ACI_DEGRADATOR:
                 EffD.CreateDeform(Owner->R_curr,DEFORM_ALL,PASSING_WAVE_PROCESS);
                 if(ActD.Active)
                     SOUND_DEGRADATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
             case ACI_MECHOSCOPE:
                 if(NetworkON){
                     if(PrevOwner && PrevOwner != Owner && (Owner->Status & SOBJ_ACTIVE) && PrevOwner->Visibility == VISIBLE && !(PrevOwner->Status & SOBJ_WAIT_CONFIRMATION)){
                         if(!(Owner->VangerChanger) && !(PrevOwner->VangerChanger)){
                             Owner->NetChanger = GET_STATION(PrevOwner->NetID);
                             Owner->ShellUpdateFlag = 1;
                             Owner->VangerChanger = PrevOwner;
                             Owner->MechosChangerType = PrevOwner->uvsPoint->Pmechos->type;
                             Owner->VangerChangerCount = 3;
                             Owner->vChangerPosition = PrevOwner->R_curr;
                             Owner->VangerChangerAngle = PrevOwner->Angle;
                             Owner->VangerChangerArmor = PrevOwner->Armor;
                             Owner->VangerChangerEnergy = PrevOwner->Energy;
                         };
                     };
                 }else{
                     if(PrevOwner && PrevOwner != Owner && PrevOwner->Visibility == VISIBLE && Owner->Visibility == VISIBLE && ((PrevOwner->Status & SOBJ_ACTIVE) || (Owner->Status & SOBJ_ACTIVE))){
                         if(ActD.Active)
                             SOUND_INCARNATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                         Owner->VangerChanger = PrevOwner;
                         Owner->MechosChangerType = PrevOwner->uvsPoint->Pmechos->type;
                         Owner->VangerChangerCount = 3;
                         Owner->vChangerPosition = PrevOwner->R_curr;
                         Owner->VangerChangerAngle = PrevOwner->Angle;
                         Owner->VangerChangerArmor = PrevOwner->Armor;
                         Owner->VangerChangerEnergy = PrevOwner->Energy;
                         Owner->VangerChangerColor = PrevOwner->uvsPoint->Pmechos->color;
                         PrevOwner->VangerChanger = Owner;
                         PrevOwner->MechosChangerType = Owner->uvsPoint->Pmechos->type;
                         PrevOwner->VangerChangerCount = 3;
                         PrevOwner->vChangerPosition = Owner->R_curr;
                         PrevOwner->VangerChangerAngle = Owner->Angle;
                         PrevOwner->VangerChangerArmor = Owner->Armor;
                         PrevOwner->VangerChangerEnergy = Owner->Energy;
                         PrevOwner->VangerChangerColor = Owner->uvsPoint->Pmechos->color;
                     };
                 };
                 ActIntBuffer.data1 = 0;
                 ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
                 set_body_color(COLORS_IDS::BODY_GRAY);
                 break;
         };
         PrevOwner = NULL;
     };
 };
References ACI_AMPUTATOR, ACI_DEGRADATOR, ACI_MECHOSCOPE, ActD, StuffObject::ActIntBuffer, ActionDispatcher::Active, ActionUnit::Angle, uvsUnitType::Armor, COLORS_IDS::BODY_GRAY, BulletControlType::BulletID, uvsMechos::color, EffectDispatcher::CreateDeform(), actintItemData::data0, actintItemData::data1, DEFORM_ALL, StuffObject::DeviceIn(), EffD, uvsUnitType::Energy, GET_STATION, getDistX(), BULLET_TYPE_ID::HYPNOTISE, VangerUnit::MechosChangerType, VangerUnit::NetChanger, NetworkON, NULL, StuffObject::Owner, PASSING_WAVE_PROCESS, pData, uvsVanger::Pmechos, StuffObject::PrevOwner, Object::set_body_color(), VangerUnit::ShellUpdateFlag, SOBJ_ACTIVE, SOBJ_WAIT_CONFIRMATION, SOUND_AMPUTATOR_SHOT, SOUND_DEGRADATOR_SHOT, SOUND_INCARNATOR_SHOT, actintItemData::type, uvsMechos::type, StuffObject::uvsDeviceType, uvsKernel::uvsPoint, uvsSetItemType(), VangerUnit::VangerChanger, VangerUnit::VangerChangerAngle, VangerUnit::VangerChangerArmor, VangerUnit::VangerChangerColor, VangerUnit::VangerChangerCount, VangerUnit::VangerChangerEnergy, VangerUnit::vChangerPosition, VISIBLE, and Object::x.
DeviceLoad()
void GunDevice::DeviceLoad (Parser & in) virtual
Reimplemented from StuffObject.
 {
 //  char* name;
     StuffObject::DeviceLoad(in);
     in.search_name("GunID");
     pData = &GameBulletData[in.get_int()];
 };
References StuffObject::DeviceLoad(), GameBulletData, Parser::get_int(), pData, and Parser::search_name().
DeviceOut()
void GunDevice::DeviceOut (Vector v1, int flag = 1, Vector v2 = Vector(-1,-1,-1)) virtual
Reimplemented from StuffObject.
 {
     if(Time){
         switch(ActIntBuffer.type){
             case ACI_AMPUTATOR:
 //              Owner->disable_control = 0;
                 EffD.CreateDeform(Owner->R_curr,DEFORM_ALL,PASSING_WAVE_PROCESS);
                 break;
             case ACI_DEGRADATOR:
                 Owner->scale_size = Owner->original_scale_size;
                 EffD.CreateDeform(Owner->R_curr,DEFORM_ALL,PASSING_WAVE_PROCESS);
                 break;
         };
     };
     PrevOwner = Owner;
     StuffObject::DeviceOut(v1,flag,v2);
 };
References ACI_AMPUTATOR, ACI_DEGRADATOR, StuffObject::ActIntBuffer, EffectDispatcher::CreateDeform(), DEFORM_ALL, StuffObject::DeviceOut(), EffD, Object::original_scale_size, StuffObject::Owner, PASSING_WAVE_PROCESS, StuffObject::PrevOwner, Object::scale_size, StuffObject::Time, and actintItemData::type.
Referenced by GunSlot::Quant().
DeviceQuant()
void GunDevice::DeviceQuant (void) virtual
Reimplemented from StuffObject.
 {
     if(pData->BulletID == BULLET_TYPE_ID::HYPNOTISE){
         switch(ActIntBuffer.type){
             case ACI_AMPUTATOR:
 //              Owner->disable_control = 1;
                 Owner->traction = 0;
                 Time--;
                 if(Time <= 0){
                     EffD.CreateDeform(Owner->R_curr,DEFORM_ALL,PASSING_WAVE_PROCESS);
                     Owner->disable_control = 0;
                     ActIntBuffer.data1 = 0;
                     ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
                     set_body_color(COLORS_IDS::BODY_GRAY);
                     if(Owner->Status & SOBJ_ACTIVE)
                         aciChangeItem(&ActIntBuffer);
                 };
                 break;
             case ACI_DEGRADATOR:
                 Owner->scale_size = Owner->original_scale_size / 2;
                 Time--;
                 if(Time <= 0){
                     EffD.CreateDeform(Owner->R_curr,DEFORM_ALL,PASSING_WAVE_PROCESS);
                     Owner->scale_size = Owner->original_scale_size;
                     ActIntBuffer.data1 = 0;
                     ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
                     set_body_color(COLORS_IDS::BODY_GRAY);
                     if(Owner->Status & SOBJ_ACTIVE)
                         aciChangeItem(&ActIntBuffer);
                 };
                 break;
         };
     };
 };
References ACI_AMPUTATOR, ACI_DEGRADATOR, aciChangeItem(), StuffObject::ActIntBuffer, COLORS_IDS::BODY_GRAY, BulletControlType::BulletID, EffectDispatcher::CreateDeform(), actintItemData::data0, actintItemData::data1, DEFORM_ALL, Object::disable_control, EffD, BULLET_TYPE_ID::HYPNOTISE, Object::original_scale_size, StuffObject::Owner, PASSING_WAVE_PROCESS, pData, Object::scale_size, Object::set_body_color(), SOBJ_ACTIVE, StuffObject::Time, Object::traction, actintItemData::type, StuffObject::uvsDeviceType, and uvsSetItemType().
GetDevice()
void GunDevice::GetDevice (StuffObject * p) virtual
Reimplemented from StuffObject.
 {
     GunDevice* n;
     n = (GunDevice*)p;
     StuffObject::GetDevice(p);
     pData = n->pData;
 };
References StuffObject::GetDevice(), and pData.
Quant()
void GunDevice::Quant (void)
 {
     if(Time > 0){
         Time--;
         if(Time == 0 && (ActIntBuffer.type == ACI_AMPUTATOR || ActIntBuffer.type == ACI_DEGRADATOR || ActIntBuffer.type == ACI_MECHOSCOPE)){
             ActIntBuffer.data1 = 0;
             ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
             set_body_color(COLORS_IDS::BODY_GRAY);
         }else{
             if(ActIntBuffer.type == ACI_EMPTY_AMPUTATOR || ActIntBuffer.type == ACI_EMPTY_DEGRADATOR || ActIntBuffer.type == ACI_EMPTY_MECHOSCOPE){
                 ActIntBuffer.data1 = 1;
                 ActIntBuffer.type = uvsSetItemType(uvsDeviceType,ActIntBuffer.data0,ActIntBuffer.data1);
                 set_body_color(COLORS_IDS::YELLOW_CHARGED);
             };
         };
     };
     StuffObject::Quant();
 };
References ACI_AMPUTATOR, ACI_DEGRADATOR, ACI_EMPTY_AMPUTATOR, ACI_EMPTY_DEGRADATOR, ACI_EMPTY_MECHOSCOPE, ACI_MECHOSCOPE, StuffObject::ActIntBuffer, COLORS_IDS::BODY_GRAY, actintItemData::data0, actintItemData::data1, StuffObject::Quant(), Object::set_body_color(), StuffObject::Time, actintItemData::type, StuffObject::uvsDeviceType, uvsSetItemType(), and COLORS_IDS::YELLOW_CHARGED.
Member Data Documentation
pData
WorldBulletTemplate* GunDevice::pData
Referenced by DeviceIn(), DeviceLoad(), DeviceQuant(), GetDevice(), GunSlot::NetStuffQuant(), GunSlot::OpenGun(), and VangerUnit::WeaponGenerator().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp