Vangers: actIntDispatcher Struct Reference
actIntDispatcher Struct Reference
#include <actint.h>
Public Member Functions
void add_matrix (invMatrix *m)
void add_imatrix (invMatrix *m)
void add_menu (fncMenu *p)
void add_imenu (fncMenu *p)
void add_item (invItem *p)
void add_iitem (invItem *p)
void add_ind (aIndData *p)
void add_locdata (aciLocationInfo *p)
void add_bmenu (aciBitmapMenu *p)
void send_event (int cd, int dt=0, actintItemData *p=NULL)
invMatrix * get_matrix (int tp)
invMatrix * get_imatrix (int tp)
invItem * get_item (int id)
invItem * get_iitem (int id)
fncMenu * get_menu (int mn)
fncMenu * get_imenu (int mn)
aciBitmapMenu * get_bmenu (int mn)
aButton * get_button (int id)
aIndData * get_ind (int id)
aciLocationInfo * get_locdata (int id)
int get_locdata_id (const char *name)
InfoPanel * get_info_panel (int id)
InfoPanel * get_aci_info_panel (int id)
CounterPanel * get_counter (int id)
CounterPanel * get_icounter (int id)
bmlObject * get_back_bml (int id)
ibsObject * get_ibs (int id)
void init (void)
void finit (void)
void init_prompt (void)
void i_init (void)
void i_finit (void)
void redraw (void)
void ind_redraw (void)
void flush (void)
void pal_flush ()
void i_redraw (void)
void i_flush (void)
void init_menus (void)
void init_inds (void)
void calc_load (void)
void init_submenu (fncMenu *m)
void change_ibs (int id)
void next_ibs (void)
void load_ibs (void)
void free_ibs (void)
void lock (void)
void unlock (void)
void KeyQuant (void)
void EventQuant (void)
void iKeyQuant (void)
void iKeyTrap (int cd)
invItem * get_item_ptr (int id)
invItem * get_item_ptr_xy (int id, int x, int y)
invItem * alloc_item (void)
fncMenuItem * alloc_menu_item (void)
invMatrix * alloc_matrix (int type, int imode=0)
void free_item (invItem *p)
void free_menu_item (fncMenuItem *p)
void clear_menu (fncMenu *p)
void free_matrix (invMatrix *p)
void change_mode (void)
void inv_mouse_move_quant (void)
void inv_mouse_imove_quant (void)
void inv_mouse_quant_l (void)
void inv_mouse_quant_r (void)
void aml_check_redraw (int x, int y)
int put_item (actintItemData *d)
void put_in_slot (actintItemData *d)
int put_item_xy (invItem *p, int x, int y, int sflag=0)
int put_item_auto (invItem *p)
void change_items (int x, int y, int sflag=0)
void remove_item (actintItemData *d)
void set_move_item (int index, int sflag=0)
void add_menu_item (fncMenu *p)
void remove_menu_item (fncMenu *p)
void prepare_menus (void)
void clean_menus (void)
void reinit_items (void)
void deactivate_items (void)
void trade_items (invMatrix *p, int imode=0)
void swap_matrices (void)
void cancel_matrix (void)
void save_data (XStream *fh)
void load_data (XStream *fh)
actIntDispatcher (void)
~actIntDispatcher (void)
Public Attributes
int flags
int curMode
int curScrMode
int prevScrMode
iList * menuList
iList * b_menuList
iList * itemList
iList * matrixList
aciPromptData * curPrompt
iList * locationList
aciLocationInfo * curLocData
iList * i_infoPanels
iList * infoPanels
iList * i_matrixList
iList * i_Counters
iList * i_itemList
iList * i_menuList
iList * intButtons
iList * invButtons
iList * infButtons
iList * intCounters
iList * invCounters
iList * infCounters
iList * indList
XGR_MousePromptScreen * invPrompt
XGR_MousePromptScreen * infPrompt
aKeyObj * ModeObj
aKeyObj * InvObj
aKeyObj * InfoObj
invMatrix * curMatrix
invMatrix * secondMatrix
invMatrix * i_curMatrix
invMatrix * a_curMatrix
invItem * curItem
InfoPanel * iP
InfoPanel * iscr_iP
InfoPanel * ascr_iP
aciWorldMap * wMap
bmlObject * mapObj
char ** map_names
fncMenuSet * qMenu
iList * ibsList
iList * backList
ibsObject * curIbs
int curIbsID
iList * freeItemList
iList * freeMatrixList
iList * freeMenuItemList
aciScreenText * ScrTextData
actEventHeap * events
Detailed Description
Constructor & Destructor Documentation
actIntDispatcher()
actIntDispatcher::actIntDispatcher (void)
 {
     int i;
     flags = 0;
     curIbsID = 0;
     iP = NULL;
     wMap = NULL;
     qMenu = NULL;
     curPrompt = new aciPromptData;
     ScrTextData = new aciScreenText;
     invPrompt = new XGR_MousePromptScreen;
     infPrompt = new XGR_MousePromptScreen;
     freeItemList = new iList;
     freeMatrixList = new iList;
     freeMenuItemList = new iList;
     b_menuList = new iList;
     map_names = new char*[MAX_NUM_MAP];
     for(i = 0; i < MAX_NUM_MAP; i ++)
         map_names[i] = NULL;
     i_infoPanels = new iList;
     infoPanels = new iList;
     curScrMode = prevScrMode = FULLSCR_MODE;
     ModeObj = new aKeyObj;
     InvObj = new aKeyObj;
     InvObj -> add_key(SDL_SCANCODE_RETURN);
     InfoObj = new aKeyObj;
     locationList = new iList;
     menuList = new iList;
     itemList = new iList;
     matrixList = new iList;
     i_matrixList = new iList;
     i_Counters = new iList;
     i_itemList = new iList;
     i_menuList = new iList;
     iscr_iP = NULL;
     ascr_iP = NULL;
     indList = new iList;
     intButtons = new iList;
     invButtons = new iList;
     infButtons = new iList;
     intCounters = new iList;
     invCounters = new iList;
     infCounters = new iList;
     curItem = NULL;
     events = new actEventHeap;
     curMode = AS_INFO_MODE;
     mapObj = new bmlObject;
     mapObj -> flags |= BMP_FLAG;
     ibsList = new iList;
     backList = new iList;
     curIbs = NULL;
     curMatrix = NULL;
 }
References AS_INFO_MODE, ascr_iP, b_menuList, backList, BMP_FLAG, curIbs, curIbsID, curItem, curMatrix, curMode, curPrompt, curScrMode, events, flags, freeItemList, freeMatrixList, freeMenuItemList, FULLSCR_MODE, i_Counters, i_infoPanels, i_itemList, i_matrixList, i_menuList, ibsList, indList, infButtons, infCounters, InfoObj, infoPanels, infPrompt, intButtons, intCounters, invButtons, invCounters, InvObj, invPrompt, iP, iscr_iP, itemList, locationList, map_names, mapObj, matrixList, MAX_NUM_MAP, menuList, ModeObj, NULL, prevScrMode, qMenu, ScrTextData, and wMap.
~actIntDispatcher()
actIntDispatcher::~actIntDispatcher (void)
 {
     int i;
     fncMenu* p,*p1;
     invMatrix* m,*m1;
     invItem* it,*it1;
     aButton* bt,*bt1;
     aIndData* ind,*ind1;
     CounterPanel* cp,*cp1;
     aciLocationInfo* lP,*lP1;
     InfoPanel* pl,*pl1;
     fncMenuItem* f,*f1;
     bmlObject* bml,*bml1;
     ibsObject* ibs,*ibs1;
     aciBitmapMenu* bm,*bm1;
     delete curPrompt;
     delete invPrompt;
     delete infPrompt;
     XGR_MouseSetPromptData(NULL);
     if(iP) delete iP;
     if(iscr_iP) delete iscr_iP;
     if(wMap) delete wMap;
     if(qMenu) delete qMenu;
     delete ScrTextData;
     if(aciColorSchemes){
         for(i = 0;  i < aciNumColSchemes; i ++)
             if(aciColorSchemes[i])
                 delete[] aciColorSchemes[i];
         delete[] aciColorSchemes;
         aciNumColSchemes = 0;
     }
     delete mapObj;
     for(i = 0; i < MAX_NUM_MAP; i ++)
         if(map_names[i]) delete[] map_names[i];
     delete[] map_names;
     m = (invMatrix*)freeMatrixList -> last;
     while(m){
         m1 = (invMatrix*)m -> prev;
         delete m;
         m = m1;
     }
     delete freeMatrixList;
     f = (fncMenuItem*)freeMenuItemList -> last;
     while(f){
         f1 = (fncMenuItem*)f -> prev;
         delete f;
         f = f1;
     }
     delete freeMenuItemList;
     it = (invItem*)freeItemList -> last;
     while(it){
         it1 = (invItem*)it -> prev;
         delete it;
         it = it1;
     }
     delete freeItemList;
     pl = (InfoPanel*)i_infoPanels -> last;
     while(pl){
         pl1 = (InfoPanel*)pl -> prev;
         delete pl;
         pl = pl1;
     }
     delete i_infoPanels;
     pl = (InfoPanel*)infoPanels -> last;
     while(pl){
         pl1 = (InfoPanel*)pl -> prev;
         delete pl;
         pl = pl1;
     }
     delete infoPanels;
     delete ModeObj;
     delete InvObj;
     delete InfoObj;
     lP = (aciLocationInfo*)locationList -> last;
     while(lP){
         lP1 = (aciLocationInfo*)lP -> prev;
         delete lP;
         lP = lP1;
     }
     delete locationList;
     it = (invItem*)itemList -> last;
     while(it){
         it1 = (invItem*)it -> prev;
         delete it;
         it = it1;
     }
     delete itemList;
     it = (invItem*)i_itemList -> last;
     while(it){
         it1 = (invItem*)it -> prev;
         delete it;
         it = it1;
     }
     delete i_itemList;
     p = (fncMenu*)menuList -> last;
     while(p){
         p1 = (fncMenu*)p -> prev;
         if(!(p -> flags & FM_ITEM_MENU))
             delete p;
         p = p1;
     }
     delete menuList;
     bm = (aciBitmapMenu*)b_menuList -> last;
     while(bm){
         bm1 = (aciBitmapMenu*)bm -> prev;
         delete bm;
         bm = bm1;
     }
     delete b_menuList;
     p = (fncMenu*)i_menuList -> last;
     while(p){
         p1 = (fncMenu*)p -> prev;
         if(!(p -> flags & FM_ITEM_MENU))
             delete p;
         p = p1;
     }
     delete i_menuList;
     m = (invMatrix*)matrixList -> last;
     while(m){
         m1 = (invMatrix*)m -> prev;
         delete m;
         m = m1;
     }
     delete matrixList;
     m = (invMatrix*)i_matrixList -> last;
     while(m){
         m1 = (invMatrix*)m -> prev;
         delete m;
         m = m1;
     }
     delete i_matrixList;
     bt = (aButton*)intButtons -> last;
     while(bt){
         bt1 = (aButton*)bt -> prev;
         delete bt;
         bt = bt1;
     }
     delete intButtons;
     bt = (aButton*)invButtons -> last;
     while(bt){
         bt1 = (aButton*)bt -> prev;
         delete bt;
         bt = bt1;
     }
     delete invButtons;
     bt = (aButton*)infButtons -> last;
     while(bt){
         bt1 = (aButton*)bt -> prev;
         delete bt;
         bt = bt1;
     }
     delete infButtons;
     ind = (aIndData*)indList -> last;
     while(ind){
         ind1 = (aIndData*)ind -> prev;
         delete ind;
         ind = ind1;
     }
     delete indList;
     cp = (CounterPanel*)intCounters -> last;
     while(cp){
         cp1 = (CounterPanel*)cp -> prev;
         delete cp;
         cp = cp1;
     }
     delete intCounters;
     cp = (CounterPanel*)infCounters -> last;
     while(cp){
         cp1 = (CounterPanel*)cp -> prev;
         delete cp;
         cp = cp1;
     }
     delete infCounters;
     cp = (CounterPanel*)invCounters -> last;
     while(cp){
         cp1 = (CounterPanel*)cp -> prev;
         delete cp;
         cp = cp1;
     }
     delete invCounters;
     cp = (CounterPanel*)i_Counters -> last;
     while(cp){
         cp1 = (CounterPanel*)cp -> prev;
         delete cp;
         cp = cp1;
     }
     delete i_Counters;
     bml = (bmlObject*)backList -> last;
     while(bml){
         bml1 = (bmlObject*)bml -> prev;
         delete bml;
         bml = bml1;
     }
     delete backList;
     ibs = (ibsObject*)ibsList -> last;
     while(ibs){
         ibs1 = (ibsObject*)ibs -> prev;
         delete ibs;
         ibs = ibs1;
     }
     delete ibsList;
     delete events;
     flags = 0;
 }
References aciColorSchemes, aciNumColSchemes, b_menuList, backList, curPrompt, events, flags, FM_ITEM_MENU, freeItemList, freeMatrixList, freeMenuItemList, i_Counters, i_infoPanels, i_itemList, i_matrixList, i_menuList, ibsList, indList, infButtons, infCounters, InfoObj, infoPanels, infPrompt, intButtons, intCounters, invButtons, invCounters, InvObj, invPrompt, iP, iscr_iP, itemList, locationList, map_names, mapObj, matrixList, MAX_NUM_MAP, menuList, ModeObj, NULL, prev, qMenu, ScrTextData, wMap, and XGR_MouseSetPromptData.
Member Function Documentation
add_bmenu()
void actIntDispatcher::add_bmenu (aciBitmapMenu * p)
 {
     b_menuList -> connect((iListElement*)p);
 }
References b_menuList.
add_iitem()
void actIntDispatcher::add_iitem (invItem * p)
 {
     i_itemList -> connect((iListElement*)p);
 }
References i_itemList.
add_imatrix()
void actIntDispatcher::add_imatrix (invMatrix * m)
 {
     i_matrixList -> connect((iListElement*)m);
 }
References i_matrixList.
add_imenu()
void actIntDispatcher::add_imenu (fncMenu * p)
 {
     i_menuList -> connect((iListElement*)p);
 }
References i_menuList.
add_ind()
void actIntDispatcher::add_ind (aIndData * p)
 {
     indList -> connect((iListElement*)p);
 }
References indList.
add_item()
void actIntDispatcher::add_item (invItem * p)
 {
     itemList -> connect((iListElement*)p);
 }
References itemList.
Referenced by change_items(), inv_mouse_imove_quant(), inv_mouse_move_quant(), put_in_slot(), and set_move_item().
add_locdata()
void actIntDispatcher::add_locdata (aciLocationInfo * p)
 {
     locationList -> connect(p);
 }
References locationList.
add_matrix()
void actIntDispatcher::add_matrix (invMatrix * m)
 {
     matrixList -> connect((iListElement*)m);
 }
References matrixList.
add_menu()
void actIntDispatcher::add_menu (fncMenu * p)
 {
     menuList -> connect((iListElement*)p);
 }
References menuList.
Referenced by add_menu_item().
add_menu_item()
void actIntDispatcher::add_menu_item (fncMenu * p)
 {
     fncMenu* m = (fncMenu*)menuList -> last;
     while(m){
         if(m -> flags & FM_MAIN_MENU){
             m -> add_menu(p);
             if(curMode == AS_INFO_MODE && m -> flags & FM_ACTIVE) m -> set_redraw();
         }
         m = (fncMenu*)m -> prev;
     }
 }
References add_menu(), AS_INFO_MODE, curMode, flags, FM_ACTIVE, FM_MAIN_MENU, menuList, and prev.
Referenced by change_items(), prepare_menus(), put_item(), put_item_auto(), and put_item_xy().
alloc_item()
invItem * actIntDispatcher::alloc_item (void)
 {
     invItem* p = new invItem;
 /*
     if(!freeItemList -> Size){
         p = new invItem;
     }
     else {
         p = (invItem*)freeItemList -> last;
         freeItemList -> dconnect((iListElement*)p);
     }
 */
     return p;
 }
Referenced by acsLoadData(), load_data(), and put_item().
alloc_matrix()
invMatrix * actIntDispatcher::alloc_matrix (int type, int imode = 0)
 {
     invMatrix* t,*p;
     t = (imode) ? get_imatrix(type) : get_matrix(type);
     if(!t) return NULL;
 /*
     p = (invMatrix*)freeMatrixList -> last;
     while(p){
         if(p -> SizeX == t -> SizeX && p -> SizeY == t -> SizeY){
             t -> clone(p);
             freeMatrixList -> dconnect(p);
             return p;
         }
         p = (invMatrix*)p -> prev;
     }
 */
     p = new invMatrix(t -> SizeX,t -> SizeY);
     t -> clone(p);
     return p;
 }
References get_imatrix(), get_matrix(), and NULL.
Referenced by cancel_matrix(), EventQuant(), i_finit(), i_init(), init(), and load_data().
alloc_menu_item()
fncMenuItem * actIntDispatcher::alloc_menu_item (void)
 {
     fncMenuItem* p = new fncMenuItem;
 /*
     if(!freeMenuItemList -> Size){
         p = new fncMenuItem;
     }
     else {
         p = (fncMenuItem*)freeMenuItemList -> last;
         freeMenuItemList -> dconnect((iListElement*)p);
     }
 */
     return p;
 }
aml_check_redraw()
void actIntDispatcher::aml_check_redraw (int x, int y)
 {
     int x1,y1,dx,dy;
     InfoPanel* pl;
     y += 16;
     pl = (InfoPanel*)i_infoPanels -> last;
     while(pl){
         if(pl -> iScreenOwner && pl -> iScreenOwner -> flags & EL_DATA_LOADED){
             x1 = pl -> PosX + pl -> SizeX/2;
             y1 = pl -> PosY + pl -> SizeY/2;
             dx = pl -> SizeX/2 + aciML_ToolzerRadius * 2;
             dy = pl -> SizeY/2 + aciML_ToolzerRadius * 2;
             if(abs(x - x1) <= dx && abs(y - y1) <= dy) pl -> set_redraw();
         }
         pl = (InfoPanel*)pl -> prev;
     }
     if(!(flags & AS_ISCREEN_INV_MODE) && qMenu && qMenu -> flags & FMC_DATA_INIT){
             x1 = qMenu -> ScreenX + qMenu -> ScreenSizeX/2;
             y1 = qMenu -> ScreenY + qMenu -> ScreenSizeY/2;
             dx = qMenu -> ScreenSizeX/2 + aciML_ToolzerRadius;
             dy = qMenu -> ScreenSizeY/2 + aciML_ToolzerRadius;
             if(abs(x - x1) <= dx && abs(y - y1) <= dy) qMenu -> set_redraw();
     }
 }
References aciML_ToolzerRadius, AS_ISCREEN_INV_MODE, EL_DATA_LOADED, flags, FMC_DATA_INIT, i_infoPanels, prev, and qMenu.
calc_load()
void actIntDispatcher::calc_load (void)
 {
     int i,sz;
     if(!curMatrix) return;
     sz = curMatrix -> SizeX * curMatrix -> SizeY;
     aciCurLoad = 0;
     for(i = 0; i < sz; i ++){
         if(curMatrix -> matrix[i] -> flags & AS_BUSY_CELL) aciCurLoad ++;
     }
     aciMaxLoad = curMatrix -> maxLoad;
 }
References aciCurLoad, aciMaxLoad, AS_BUSY_CELL, curMatrix, and flags.
Referenced by EventQuant().
cancel_matrix()
void actIntDispatcher::cancel_matrix (void)
 {
     invItem* p;
     uvsActInt* u;
     if(flags & AS_INV_MOVE_ITEM){
         flags ^= AS_INV_MOVE_ITEM;
         free_item(curItem);
         restore_mouse_cursor();
         curItem = NULL;
     }
     free_matrix(secondMatrix);
     if(curMatrix){
         backupMatrix -> ScreenX = curMatrix -> ScreenX;
         free_matrix(curMatrix);
         curMatrix = alloc_matrix(backupMatrix -> type,1);
         backupMatrix -> backup(curMatrix);
         p = (invItem*)curMatrix -> items -> last;
         while(p){
             if(p -> uvsDataPtr){
                 u = (uvsActInt*)p -> uvsDataPtr;
                 u -> pos_x = p -> MatrixX;
                 u -> pos_y = p -> MatrixY;
             }
             p = (invItem*)p -> prev;
         }
     }
     secondMatrix = NULL;
 }
References alloc_matrix(), AS_INV_MOVE_ITEM, backupMatrix, curItem, curMatrix, flags, free_item(), free_matrix(), NULL, prev, restore_mouse_cursor(), and secondMatrix.
change_ibs()
void actIntDispatcher::change_ibs (int id)
 {
     if(curIbs){
         curIbs -> free();
 //        if(curIbs -> back) curIbs -> back -> free();
     }
     curIbs = get_ibs(id);
     if(!curIbs) ErrH.Abort("IBS object not present",XERR_USER,id);
     load_ibs();
 }
References XErrorHandler::Abort(), curIbs, ErrH, get_ibs(), load_ibs(), and XERR_USER.
change_items()
void actIntDispatcher::change_items (int x, int y, int sflag = 0)
 {
     actintItemData* d;
     int id;
     invMatrix* m = (sflag) ? secondMatrix : curMatrix;
     invItem* p = m -> get_area_item(x,y,curItem);
     if(!p) return;
     m -> remove_item(p);
     if(!m -> check_fit(x,y,curItem)){
         m -> put_item(p -> MatrixX,p -> MatrixY,p);
         return;
     }
     if(flags & AS_ISCREEN && curItem -> flags & INV_ITEM_NO_PAY){
         if(!aciCheckItemCredits()){
             m -> put_item(p -> MatrixX,p -> MatrixY,p);
             return;
         }
         aciPay4Item(curItem);
     }
     m -> put_item(x,y,curItem);
     m -> set_redraw();
     if(!(flags & AS_ISCREEN)){
         if(p -> slotType != -1)
             aciSendEvent2itmdsp(ACI_DEACTIVATE_ITEM,p -> item_ptr);
     }
     if(curItem -> slotType != -1){
         if(!(flags & AS_ISCREEN)){
             id = m -> get_item_slot(curItem);
             d = curItem -> item_ptr;
             if(id != -1)
                 aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,d,id);
             else
                 aciSendEvent2itmdsp(ACI_DEACTIVATE_ITEM,d);
         }
     }
     m -> clear_shadow_cells();
     flags |= aMS_MOVED;
     if(!(flags & AS_ISCREEN)){
         if(p -> menu)
             remove_menu_item((fncMenu*)p -> menu);
         if(curItem -> menu)
             add_menu_item((fncMenu*)curItem -> menu);
     }
     else {
         if(curItem -> uvsDataPtr){
             ((uvsActInt*)curItem -> uvsDataPtr) -> pos_x = curItem -> MatrixX;
             ((uvsActInt*)curItem -> uvsDataPtr) -> pos_y = curItem -> MatrixY;
         }
         if(p -> uvsDataPtr){
             ((uvsActInt*)p -> uvsDataPtr) -> pos_x = -1;
             ((uvsActInt*)p -> uvsDataPtr) -> pos_y = -1;
             p -> MatrixX = p -> MatrixY = -1;
         }
     }
     curItem = p;
     if(iP){
         iP -> free_list();
         iP -> add_item(curItem->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
         if(!(flags & AS_ISCREEN)){
             iP -> add_items(curItem -> numComments,curItem -> comments);
             if(curItem -> pTemplate)
                 iP -> add_item(aciGetItemLoad(curItem,0));
         }
         else {
             iP -> add_items(curItem -> numComments,curItem -> comments);
             if(curItem -> pTemplate)
                 iP -> add_item(aciGetItemLoad(curItem,1));
             if(!uvsCurrentWorldUnable)
                 iP -> add_item(aciGetPrice((iListElement*)curItem,ITEMS_MODE,1));
         }
         iP -> set_redraw();
     }
     set_mouse_cursor(p -> frame,p -> ScreenSizeX,p -> ScreenSizeY);
 //    inv_mouse_move_quant();
 }
References ACI_ACTIVATE_ITEM, ACI_DEACTIVATE_ITEM, aciCheckItemCredits(), aciCurColorScheme, aciGetItemLoad(), aciGetPrice(), aciPay4Item(), aciSendEvent2itmdsp(), add_item(), add_menu_item(), aMS_MOVED, AS_ISCREEN, curItem, curMatrix, flags, FM_SELECT_COL, frame, iListElement::ID_ptr, INV_ITEM_NO_PAY, iP, ITEMS_MODE, put_item(), remove_item(), remove_menu_item(), secondMatrix, set_mouse_cursor(), and uvsCurrentWorldUnable.
Referenced by inv_mouse_quant_l().
change_mode()
void actIntDispatcher::change_mode (void)
 {
     //std::cout<<"actIntDispatcher::change_mode"<<std::endl;
     aButton* b;
     fncMenu* p;
     switch(curMode){
         case AS_INV_MODE:
             if(flags & AS_INV_MOVE_ITEM) break;
             curMode = AS_INFO_MODE;
             XGR_MouseSetPromptData(infPrompt);
             change_screen(prevScrMode);
             curScrMode = prevScrMode;
             p = (fncMenu*)menuList -> last;
             while(p){
                 p -> set_redraw();
                 p -> set_flush();
                 p = (fncMenu*)p -> prev;
             }
             b = (aButton*)infButtons -> last;
             while(b){
                 b -> set_redraw();
                 b -> set_flush();
                 b = (aButton*)b -> prev;
             }
             break;
         case AS_INFO_MODE:
             curMode = AS_INV_MODE;
             XGR_MouseSetPromptData(invPrompt);
             prevScrMode = curScrMode;
             curScrMode = INVSCR_MODE;
             change_screen(INVSCR_MODE);
             curMatrix -> set_redraw();
             curMatrix -> set_flush();
             b = (aButton*)invButtons -> last;
             while(b){
                 b -> set_redraw();
                 b -> set_flush();
                 b = (aButton*)b -> prev;
             }
             break;
     }
     flags &= ~AS_CHANGE_MODE;
 }
References AS_CHANGE_MODE, AS_INFO_MODE, AS_INV_MODE, AS_INV_MOVE_ITEM, change_screen(), curMatrix, curMode, curScrMode, flags, infButtons, infPrompt, invButtons, invPrompt, INVSCR_MODE, menuList, prev, prevScrMode, and XGR_MouseSetPromptData.
Referenced by EventQuant().
clean_menus()
void actIntDispatcher::clean_menus (void)
 {
     fncMenu* m = (fncMenu*)menuList -> last;
     while(m){
         if(m -> flags & FM_MAIN_MENU){
             m -> clean();
         }
         m = (fncMenu*)m -> prev;
     }
 }
References flags, FM_MAIN_MENU, menuList, and prev.
Referenced by i_finit().
clear_menu()
void actIntDispatcher::clear_menu (fncMenu * p)
 {
     fncMenuItem* p,*p1;
     p = (fncMenuItem*)mn -> items -> last;
     while(p){
         p1 = (fncMenuItem*)p -> prev;
         mn -> items -> dconnect((iListElement*)p);
         free_menu_item(p);
         p = p1;
     }
     p = (fncMenuItem*)mn -> inactive_items -> last;
     while(p){
         p1 = (fncMenuItem*)p -> prev;
         mn -> inactive_items -> dconnect((iListElement*)p);
         free_menu_item(p);
         p = p1;
     }
     mn -> prefix = NULL;
     mn -> postfix = NULL;
 }
References free_menu_item(), NULL, and prev.
deactivate_items()
void actIntDispatcher::deactivate_items (void)
 {
     int id;
     if(!curMatrix) return;
     invItem* p = (invItem*)curMatrix -> items -> last;
     actintItemData* d;
     while(p){
         if(p -> slotType != -1){
             id = curMatrix -> get_item_slot(p);
             d = p -> item_ptr;
             if(id != -1)
                 aciSendEvent2itmdsp(ACI_DEACTIVATE_ITEM,d,id);
         }
         p = (invItem*)p -> prev;
     }
 }
References ACI_DEACTIVATE_ITEM, aciSendEvent2itmdsp(), curMatrix, and prev.
EventQuant()
void actIntDispatcher::EventQuant (void)
 {
     actEvent* p;
     fncMenu* m;
     calc_load();
     aciSetTimePanel();
     aciCurFrame ++;
 //    aciUpdateCurCredits(aciCurCredits);
     if(aciItmTextQueueSize && !(flags & AS_TEXT_MODE)) aciReadItmText();
     if(iChatExit){
         iChatExit = 0;
         send_event(EV_LEAVE_CHAT);
     }
     aciTextColBright += aciTextColBrightDelta;
     if(aciTextColBright < 0){
         aciTextColBright = 0;
         aciTextColBrightDelta = 1;
     }
     if(aciTextColBright > 64){
         aciTextColBright = 64;
         aciTextColBrightDelta = -1;
     }
     if(wMap){
         wMap -> quant();
     }
     while(events -> size){
         p = events -> get();
         switch(p -> code){
             case EV_NEXT_PHRASE:
                 aciNextPhrase();
                 break;
             case EV_CHANGE_MODE:
                 change_mode();
                 break;
             case EV_SET_MODE:
                 if(p -> data != curMode)
                     change_mode();
                 break;
             case EV_ACTIVATE_MENU:
                 if(curMode == AS_INFO_MODE){
                     m = get_menu(p -> data);
                     if(!m)
                         ErrH.Abort("Bad event data...");
                     if(m -> trigger){
                         if(m -> trigger -> flags & B_PRESSED)
                             m -> flags &= ~FM_ACTIVE;
                         else
                             m -> flags |= FM_ACTIVE;
                     }
                     else
                         m -> flags ^= FM_ACTIVE;
                     m -> curItem = m -> get_fnc_item(m -> curFunction);
                     if(m -> VItems < m -> items -> Size)
                         m -> firstItem = m -> curItem;
                     else
                         m -> firstItem = (fncMenuItem*)m -> items -> first;
                     m -> set_redraw();
                 }
                 break;
             case ACI_PUT_ITEM:
                 put_item(p -> ptr);
                 break;
             case ACI_DROP_ITEM:
                 remove_item(p -> ptr);
                 break;
             case EV_CHANGE_SCREEN:
                 if(curScrMode != p -> data){
                     prevScrMode = curScrMode;
                     curScrMode = p -> data;
                     change_screen(p -> data);
                 }
                 break;
             case EV_FULLSCR_CHANGE:
                 flags ^= AS_FULLSCR;
                 if(flags & AS_FULLSCR){
                     set_screen(XGR_MAXX/2 - 0,XGR_MAXY/2 - 0,0,XGR_MAXX/2,XGR_MAXY/2);
                     XGR_MouseHide();
                     XGR_MouseSetPromptData(NULL);
                 }
                 else {
                     flags &= ~AS_FULL_REDRAW;
                     flags &= ~AS_TEXT_MODE;
                     set_screen(curIbs -> SideX,curIbs -> SideY,0,curIbs -> CenterX,curIbs -> CenterY);
                     XGR_MouseShow();
                     if(curMode == AS_INV_MODE){
                         XGR_MouseSetPromptData(invPrompt);
                     }
                     else {
                         if(curMode == AS_INFO_MODE){
                             XGR_MouseSetPromptData(infPrompt);
                         }
                     }
                 }
                 break;
             case EV_ACTIVATE_IINV:
                 flags |= AS_ISCREEN_INV_MODE;
                 break;
             case EV_DEACTIVATE_IINV:
                 flags &= ~AS_ISCREEN_INV_MODE;
                 break;
             case EV_ACTIVATE_MATRIX:
                 secondMatrix = alloc_matrix(aci_SecondMatrixID,1);
                 secondMatrix -> ScreenX += 400;
                 if(curMatrix){
                     backupMatrix = alloc_matrix(curMatrix -> type,1);
                     curMatrix -> backup(backupMatrix);
                 }
                 aciShowScMatrix();
                 break;
             case EV_DEACTIVATE_MATRIX:
                 aciBuyItem();
                 aciSwapMatrices();
                 aciInitShopAvi();
                 break;
             case EV_EVINCE_PALETTE:
                 flags |= AS_EVINCE_PALETTE;
                 break;
             case EV_INIT_MATRIX_OBJ:
                 aci_setMatrixBorder();
                 aci_setScMatrixBorder();
                 break;
             case EV_INIT_SC_MATRIX_OBJ:
                 aci_setScMatrixBorder();
                 break;
             case EV_REDRAW:
                 flags &= ~AS_FULL_REDRAW;
                 break;
             case EV_CANCEL_MATRIX:
                 aciCancelMatrix();
                 break;
             case EV_AUTO_MOVE_ITEMS:
                 aciAutoMoveItems();
                 break;
             case EV_SET_MECH_NAME:
                 aciSetMechName();
                 break;
             case EV_NEXT_SHOP_AVI:
                 aciNextShopItem();
                 aciInitShopAvi();
                 break;
             case EV_PREV_SHOP_AVI:
                 aciPrevShopItem();
                 aciInitShopAvi();
                 break;
             case EV_CHANGE_AVI_LIST:
                 aciChangeList();
                 aciInitShopAvi();
                 break;
             case EV_BUY_ITEM:
                 aciBuyItem();
                 aciInitShopAvi();
                 break;
             case EV_SET_ITM_PICKUP:
                 aciPickupItems ^= 1;
                 break;
             case EV_SET_WPN_PICKUP:
                 aciPickupDevices ^= 1;
                 break;
             case EV_ACTIVATE_SHOP_MENU:
                 aciInitShopList();
                 break;
             case EV_CHOOSE_SHOP_ITEM:
                 aciChooseShopItem();
                 break;
             case EV_SHOW_QUESTS:
                 aciBuildQuestList();
                 break;
             case EV_ASK_QUEST:
                 aciAskQuestion();
                 break;
             case EV_GET_BLOCK_PHRASE:
                 aciShowBlockPhrase();
                 break;
             case EV_TRY_2_ENTER:
                 aciActionEvent();
                 break;
             case EV_GET_CIRT:
                 aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,p -> ptr);
                 break;
             case ACI_PUT_IN_SLOT:
                 put_in_slot(p -> ptr);
                 break;
             case EV_GET_ELEECH:
                 aciGetEleech();
                 break;
             case EV_GET_RUBOX:
                 aciGetRubox();
                 break;
             case EV_LOCK_ISCREEN:
                 iScrDisp -> lock_events();
                 break;
             case EV_UNLOCK_ISCREEN:
                 iScrDisp -> unlock_events();
                 break;
             case EV_ISCR_KEYTRAP:
                 iScrDisp -> key_trap(p -> data);
                 break;
             case EV_SELL_MOVE_ITEM:
                 aciSellMoveItem();
                 break;
             case EV_CHANGE_AVI_INDEX:
                 aciChangeAviIndex();
                 aciInitShopAvi();
                 break;
             case EV_START_SPEECH:
 //                aciStartSpeech();
                 break;
             case EV_TELEPORT:
                 if(wMap){
                     aciWorldIndex = wMap -> world_ptr[p -> data] -> uvsID;
                     aciPrevJumpCount = -1;
                     if(!(flags & AS_FULLSCR)){
                         flags |= AS_FULLSCR;
                         flags &= ~AS_TEXT_MODE;
                         set_screen(XGR_MAXX/2 - 0,XGR_MAXY/2 - 0,0,XGR_MAXX/2,XGR_MAXY/2);
                         XGR_MouseSetPromptData(NULL);
                         XGR_MouseHide();
                     }
                     lock();
                 }
                 break;
             case EV_INIT_BUTTONS:
                 aciInitShopButtons();
                 break;
             case EV_ENTER_TEXT_MODE:
             case ACI_SHOW_TEXT:
                 if(!(flags & AS_FULLSCR)){
                     flags |= AS_FULLSCR;
                     XGR_MouseSetPromptData(NULL);
                     set_screen(XGR_MAXX/2 - 0,XGR_MAXY/2 - 0,0,XGR_MAXX/2,XGR_MAXY/2);
                     XGR_MouseHide();
                 }
                 ScrTextData -> color = aciTEXT_COLOR;
                 flags |= AS_TEXT_MODE;
                 break;
             case EV_LEAVE_TEXT_MODE:
             case ACI_HIDE_TEXT:
                 if(flags & AS_FULLSCR){
                     flags &= ~AS_FULL_REDRAW;
                     flags &= ~AS_FULLSCR;
                     set_screen(curIbs -> SideX,curIbs -> SideY,0,curIbs -> CenterX,curIbs -> CenterY);
                     XGR_MouseShow();
                     if(curMode == AS_INV_MODE)
                         XGR_MouseSetPromptData(invPrompt);
                     if(curMode == AS_INFO_MODE)
                         XGR_MouseSetPromptData(infPrompt);
                 }
                 ScrTextData -> clear();
                 flags &= ~AS_TEXT_MODE;
                 break;
             case ACI_LOCK_INTERFACE:
                 if(!(flags & AS_FULLSCR)){
                     flags |= AS_FULLSCR;
                     flags &= ~AS_TEXT_MODE;
                     set_screen(XGR_MAXX/2 - 0,XGR_MAXY/2 - 0,0,XGR_MAXX/2,XGR_MAXY/2);
                     XGR_MouseHide();
                     XGR_MouseSetPromptData(NULL);
                 }
                 lock();
                 break;
             case ACI_UNLOCK_INTERFACE:
                 if(flags & AS_FULLSCR){
                     flags &= ~AS_FULL_REDRAW;
                     flags &= ~AS_FULLSCR;
                     set_screen(curIbs -> SideX,curIbs -> SideY,0,curIbs -> CenterX,curIbs -> CenterY);
                     if(curMode == AS_INV_MODE)
                         XGR_MouseSetPromptData(invPrompt);
                     if(curMode == AS_INFO_MODE)
                         XGR_MouseSetPromptData(infPrompt);
                     XGR_MouseShow();
                 }
                 unlock();
                 break;
             case EV_PROTRACTOR_EVENT:
                 aciProtractorEvent = p -> data;
                 break;
             case EV_MECH_MESSIAH_EVENT:
                 aciMechMessiahEvent = p -> data;
                 break;
             case EV_PAUSE_AML:
                 aciML_Pause();
                 break;
             case EV_RESUME_AML:
                 aciML_Resume();
                 break;
             case EV_ENTER_CHAT:
                 if(!(flags & AS_FULLSCR)){
                     flags |= AS_FULLSCR;
                     flags &= ~AS_TEXT_MODE;
                     set_screen(XGR_MAXX/2 - 0,XGR_MAXY/2 - 0,0,XGR_MAXX/2,XGR_MAXY/2);
                     XGR_MouseSetPromptData(NULL);
                     XGR_MouseHide();
                 }
                 lock();
                 iChatInit();
                 flags |= AS_CHAT_MODE;
                 break;
             case EV_ITEM_TEXT:
                 aciSendEvent2itmdsp(ACI_SHOW_ITEM_TEXT,p -> ptr);
                 break;
             case EV_LEAVE_CHAT:
                 if(flags & AS_FULLSCR){
                     flags &= ~AS_FULL_REDRAW;
                     flags &= ~AS_FULLSCR;
                     set_screen(curIbs -> SideX,curIbs -> SideY,0,curIbs -> CenterX,curIbs -> CenterY);
                     XGR_MouseShow();
                     if(curMode == AS_INV_MODE)
                         XGR_MouseSetPromptData(invPrompt);
                     if(curMode == AS_INFO_MODE)
                         XGR_MouseSetPromptData(infPrompt);
                 }
                 unlock();
                 iChatFinit();
                 flags &= ~AS_CHAT_MODE;
                 break;
             case EV_INIT_AVI_OBJECT:
                 aciInitAviObject();
                 break;
         }
     }
 }
References XErrorHandler::Abort(), ACI_ACTIVATE_ITEM, ACI_DROP_ITEM, ACI_HIDE_TEXT, ACI_LOCK_INTERFACE, ACI_PUT_IN_SLOT, ACI_PUT_ITEM, aci_SecondMatrixID, aci_setMatrixBorder(), aci_setScMatrixBorder(), ACI_SHOW_ITEM_TEXT, ACI_SHOW_TEXT, ACI_UNLOCK_INTERFACE, aciActionEvent(), aciAskQuestion(), aciAutoMoveItems(), aciBuildQuestList(), aciBuyItem(), aciCancelMatrix(), aciChangeAviIndex(), aciChangeList(), aciChooseShopItem(), aciCurFrame, aciGetEleech(), aciGetRubox(), aciInitAviObject(), aciInitShopAvi(), aciInitShopButtons(), aciInitShopList(), aciItmTextQueueSize, aciMechMessiahEvent, aciML_Pause(), aciML_Resume(), aciNextPhrase(), aciNextShopItem(), aciPickupDevices, aciPickupItems, aciPrevJumpCount, aciPrevShopItem(), aciProtractorEvent, aciReadItmText(), aciSellMoveItem(), aciSendEvent2itmdsp(), aciSetMechName(), aciSetTimePanel(), aciShowBlockPhrase(), aciShowScMatrix(), aciSwapMatrices(), aciTEXT_COLOR, aciTextColBright, aciTextColBrightDelta, aciWorldIndex, alloc_matrix(), AS_CHAT_MODE, AS_EVINCE_PALETTE, AS_FULL_REDRAW, AS_FULLSCR, AS_INFO_MODE, AS_INV_MODE, AS_ISCREEN_INV_MODE, AS_TEXT_MODE, B_PRESSED, backupMatrix, calc_load(), change_mode(), change_screen(), curIbs, curItem, curMatrix, curMode, curScrMode, ErrH, EV_ACTIVATE_IINV, EV_ACTIVATE_MATRIX, EV_ACTIVATE_MENU, EV_ACTIVATE_SHOP_MENU, EV_ASK_QUEST, EV_AUTO_MOVE_ITEMS, EV_BUY_ITEM, EV_CANCEL_MATRIX, EV_CHANGE_AVI_INDEX, EV_CHANGE_AVI_LIST, EV_CHANGE_MODE, EV_CHANGE_SCREEN, EV_CHOOSE_SHOP_ITEM, EV_DEACTIVATE_IINV, EV_DEACTIVATE_MATRIX, EV_ENTER_CHAT, EV_ENTER_TEXT_MODE, EV_EVINCE_PALETTE, EV_FULLSCR_CHANGE, EV_GET_BLOCK_PHRASE, EV_GET_CIRT, EV_GET_ELEECH, EV_GET_RUBOX, EV_INIT_AVI_OBJECT, EV_INIT_BUTTONS, EV_INIT_MATRIX_OBJ, EV_INIT_SC_MATRIX_OBJ, EV_ISCR_KEYTRAP, EV_ITEM_TEXT, EV_LEAVE_CHAT, EV_LEAVE_TEXT_MODE, EV_LOCK_ISCREEN, EV_MECH_MESSIAH_EVENT, EV_NEXT_PHRASE, EV_NEXT_SHOP_AVI, EV_PAUSE_AML, EV_PREV_SHOP_AVI, EV_PROTRACTOR_EVENT, EV_REDRAW, EV_RESUME_AML, EV_SELL_MOVE_ITEM, EV_SET_ITM_PICKUP, EV_SET_MECH_NAME, EV_SET_MODE, EV_SET_WPN_PICKUP, EV_SHOW_QUESTS, EV_START_SPEECH, EV_TELEPORT, EV_TRY_2_ENTER, EV_UNLOCK_ISCREEN, events, flags, FM_ACTIVE, get_menu(), iChatExit, iChatFinit(), iChatInit(), infPrompt, invPrompt, iScrDisp, lock(), NULL, prevScrMode, put_in_slot(), put_item(), remove_item(), ScrTextData, secondMatrix, send_event(), set_screen(), unlock(), wMap, XGR_MAXX, XGR_MAXY, XGR_MouseHide, XGR_MouseSetPromptData, and XGR_MouseShow.
finit()
void actIntDispatcher::finit (void)
 {
     fncMenu* it;
     invItem* itm;
     aButton* b;
     aIndData* ind;
     CounterPanel* cp;
     InfoPanel* ip;
     aciBitmapMenu* bm;
     XGR_MouseSetPromptData(NULL);
     if(iP) iP -> finit();
     ip = (InfoPanel*)infoPanels -> last;
     while(ip){
         ip -> finit();
         ip = (InfoPanel*)ip -> prev;
     }
     bm = (aciBitmapMenu*)b_menuList -> last;
     while(bm){
         bm -> finit();
         bm = (aciBitmapMenu*)bm -> prev;
     }
     ind = (aIndData*)indList -> last;
     while(ind){
         ind -> finit();
         ind = (aIndData*)ind -> prev;
     }
     cp = (CounterPanel*)intCounters -> last;
     while(cp){
         cp -> finit();
         cp = (CounterPanel*)cp -> prev;
     }
     cp = (CounterPanel*)infCounters -> last;
     while(cp){
         cp -> finit();
         cp = (CounterPanel*)cp -> prev;
     }
     cp = (CounterPanel*)invCounters -> last;
     while(cp){
         cp -> finit();
         cp = (CounterPanel*)cp -> prev;
     }
     free_ibs();
     mapObj -> free();
     itm = (invItem*)itemList -> last;
     while(itm){
         itm -> finit();
         itm = (invItem*)itm -> prev;
     }
     it = (fncMenu*)menuList -> last;
     while(it){
         it -> finit();
         it = (fncMenu*)it -> prev;
     }
     b = (aButton*)intButtons -> last;
     while(b){
         b -> finit();
         b = (aButton*)b -> prev;
     }
     b = (aButton*)invButtons -> last;
     while(b){
         b -> finit();
         b = (aButton*)b -> prev;
     }
     b = (aButton*)infButtons -> last;
     while(b){
         b -> finit();
         b = (aButton*)b -> prev;
     }
     free_cell_frame();
 }
References b_menuList, free_cell_frame(), free_ibs(), indList, infButtons, infCounters, infoPanels, intButtons, intCounters, invButtons, invCounters, iP, itemList, mapObj, menuList, NULL, prev, and XGR_MouseSetPromptData.
Referenced by i_finit(), and i_init().
flush()
void actIntDispatcher::flush (void)
 {
     fncMenu* p;
     aButton* b;
     invMatrix* m;
     aIndData* ind;
     CounterPanel* cp;
     InfoPanel* iPl;
     int emode = ExclusiveLog ? XGR_EXCLUSIVE : 0;
     if(iKeyPressed(iKEY_EXIT)){
         i_slake_pal(actIntPal,32);
         acsHandleExtEvent(ACS_GLOBAL_EXIT);
         aciPrepareEndImage();
         GameQuantReturnValue = RTO_SHOW_IMAGE_ID;
         XGR_MouseHide();
         /*if(XGR_MAXX != 800){
             if(XGR_ReInit(800,600,emode)) ErrH.Abort("Error video initialization");
         }*/
         XGR_Flip();
         return;
     }
     if(flags & AS_FULLSCR){
         ind = (aIndData*)indList -> last;
         while(ind){
             ind -> redraw(IND_DATA_OFFS,IND_DATA_OFFS);
             ind -> flush(IND_DATA_OFFS,IND_DATA_OFFS);
             ind = (aIndData*)ind -> prev;
         }
         if(flags & AS_EVINCE_PALETTE){
             i_evince_pal(actIntPal,16);
             PalIterLock = 0;
             flags ^= AS_EVINCE_PALETTE;
         }
         if(flags & AS_TEXT_MODE){
             ScrTextData -> redraw();
             ScrTextData -> Quant();
         }
         if(curPrompt -> NumStr){
             curPrompt -> redraw(0,0,XGR_MAXX,XGR_MAXY);
             curPrompt -> quant();
         }
         if(flags & AS_CHAT_MODE){
             iChatQuant();
         }
         else {
             if(aciRacingFlag){
                 aciShowRacingPlace();
             }
         }
         if(Pause > 1 && NetworkON){
             if(GameQuantReturnValue || acsQuant()){
                 Pause = 0;
             }
         }
         return;
     }
     if(curPrompt -> NumStr){
         curPrompt -> redraw(curIbs -> PosX,curIbs -> PosY,curIbs -> SizeX,curIbs -> SizeY);
         curPrompt -> quant();
     }
     curIbs -> show();
     ind = (aIndData*)indList -> last;
     while(ind){
         ind -> redraw();
         if(!(flags & AS_FULL_FLUSH)) ind -> flush();
         ind = (aIndData*)ind -> prev;
     }
     if(aciRacingFlag){
         aciShowRacingPlace();
     }
     if(Pause > 1 && NetworkON){
         if(GameQuantReturnValue || acsQuant()){
             Pause = 0;
         }
         flags |= AS_FULL_FLUSH;
     }
     if(flags & AS_FULL_FLUSH){
         flags &= ~AS_FULL_FLUSH;
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     }
     cp = (CounterPanel*)intCounters -> last;
     while(cp){
         if(cp -> flags & CP_FLUSH){
             cp -> flush();
         }
         cp = (CounterPanel*)cp -> prev;
     }
     cp = (CounterPanel*)infCounters -> last;
     while(cp){
         if(cp -> flags & CP_FLUSH){
             cp -> flush();
         }
         cp = (CounterPanel*)cp -> prev;
     }
     cp = (CounterPanel*)invCounters -> last;
     while(cp){
         if(cp -> flags & CP_FLUSH){
             cp -> flush();
         }
         cp = (CounterPanel*)cp -> prev;
     }
     if(curMatrix){
         m = curMatrix;
         if(m -> flags & IM_FLUSH){
             m -> flush();
         }
         if(m -> flags & IM_REDRAW_SHADOW){
             m -> redraw_shadow_cells();
             m -> flags &= ~IM_REDRAW_SHADOW;
         }
     }
     p = (fncMenu*)menuList -> last;
     while(p){
         if(p -> flags & FM_FLUSH){
             p -> flush();
         }
         p = (fncMenu*)p -> prev;
     }
     b = (aButton*)intButtons -> last;
     while(b){
         if(b -> flags & B_FLUSH){
             b -> flush();
         }
         if(b -> flags & B_ACTIVE){
             b -> press();
         }
         if(b -> activeCount && b -> flags & B_PRESSED){
             if(b -> curCount >= b -> activeCount){
                 b -> press();
                 send_event(b -> eventCode,b -> eventData);
             }
             else
                 b -> curCount ++;
         }
         b = (aButton*)b -> prev;
     }
     b = (aButton*)invButtons -> last;
     while(b){
         if(b -> flags & B_FLUSH){
             b -> flush();
         }
         if(b -> flags & B_ACTIVE){
             b -> press();
         }
         if(curMode == AS_INV_MODE){
             if(b -> activeCount && b -> flags & B_PRESSED){
                 if(b -> curCount >= b -> activeCount){
                     b -> press();
                     send_event(b -> eventCode,b -> eventData);
                 }
                 else
                     b -> curCount ++;
             }
         }
         b = (aButton*)b -> prev;
     }
     b = (aButton*)infButtons -> last;
     while(b){
         if(b -> flags & B_FLUSH){
             b -> flush();
         }
         if(b -> flags & B_ACTIVE){
             b -> press();
         }
         if(curMode == AS_INFO_MODE){
             if(b -> activeCount && b -> flags & B_PRESSED){
                 if(b -> curCount >= b -> activeCount){
                     b -> press();
                     send_event(b -> eventCode,b -> eventData);
                 }
                 else
                     b -> curCount ++;
             }
         }
         b = (aButton*)b -> prev;
     }
     if(iP && iP -> flags & IP_FLUSH)
         iP -> flush();
     iPl = (InfoPanel*)infoPanels -> last;
     while(iPl){
         if(iPl -> flags & IP_FLUSH){
             iPl -> flush();
         }
         iPl = (InfoPanel*)iPl -> prev;
     }
     if(flags & AS_EVINCE_PALETTE){
         i_evince_pal(actIntPal,16);
         PalIterLock = 0;
         flags ^= AS_EVINCE_PALETTE;
     }
 }
References aciPrepareEndImage(), aciRacingFlag, aciShowRacingPlace(), ACS_GLOBAL_EXIT, acsHandleExtEvent(), acsQuant(), actIntPal, AS_CHAT_MODE, AS_EVINCE_PALETTE, AS_FULL_FLUSH, AS_FULLSCR, AS_INFO_MODE, AS_INV_MODE, AS_TEXT_MODE, B_ACTIVE, B_FLUSH, B_PRESSED, CP_FLUSH, curIbs, curMatrix, curMode, curPrompt, emode, ExclusiveLog, flags, FM_FLUSH, GameQuantReturnValue, i_evince_pal(), i_slake_pal(), iChatQuant(), iKEY_EXIT, iKeyPressed(), IM_FLUSH, IM_REDRAW_SHADOW, IND_DATA_OFFS, indList, infButtons, infCounters, infoPanels, intButtons, intCounters, invButtons, invCounters, iP, IP_FLUSH, iPl, menuList, NetworkON, PalIterLock, Pause, prev, redraw(), RTO_SHOW_IMAGE_ID, ScrTextData, send_event(), XGR_EXCLUSIVE, XGR_Flip, XGR_Flush, XGR_MAXX, XGR_MAXY, and XGR_MouseHide.
Referenced by i_flush().
free_ibs()
void actIntDispatcher::free_ibs (void)
 {
     if(!curIbs)
         ErrH.Abort("curIBS object not present");
     curIbs -> free();
 }
References XErrorHandler::Abort(), curIbs, and ErrH.
Referenced by finit().
free_item()
void actIntDispatcher::free_item (invItem * p)
 {
     delete p;
 //    freeItemList -> connect((iListElement*)p);
 }
Referenced by cancel_matrix(), free_matrix(), i_init(), inv_mouse_quant_l(), inv_mouse_quant_r(), put_item(), and remove_item().
free_matrix()
void actIntDispatcher::free_matrix (invMatrix * p)
 {
     invItem* itm,*itm1;
     itm = (invItem*)p -> items -> last;
     while(itm){
         itm1 = (invItem*)itm -> prev;
         p -> items -> dconnect((iListElement*)itm);
         free_item(itm);
         itm = itm1;
     }
     delete p;
 //    freeMatrixList -> connect((iListElement*)p);
 }
References free_item(), and prev.
Referenced by cancel_matrix(), i_finit(), i_init(), load_data(), and swap_matrices().
free_menu_item()
void actIntDispatcher::free_menu_item (fncMenuItem * p)
 {
     delete p;
 //    freeMenuItemList -> connect((iListElement*)p);
 }
Referenced by clear_menu().
get_aci_info_panel()
InfoPanel * actIntDispatcher::get_aci_info_panel (int id)
 {
     InfoPanel* p = (InfoPanel*)infoPanels -> last;
     while(p){
         if(p -> type == id)
             return p;
         p = (InfoPanel*)p -> prev;
     }
     return NULL;
 }
References infoPanels, NULL, and prev.
get_back_bml()
bmlObject * actIntDispatcher::get_back_bml (int id)
 {
     bmlObject* p = (bmlObject*)backList -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (bmlObject*)p -> prev;
     }
     return NULL;
 }
References backList, NULL, and prev.
Referenced by init().
get_bmenu()
aciBitmapMenu * actIntDispatcher::get_bmenu (int mn)
 {
     aciBitmapMenu* p = (aciBitmapMenu*)b_menuList -> last;
     while(p){
         if(p -> ID == mn) return p;
         p = (aciBitmapMenu*)p -> prev;
     }
     return NULL;
 }
References b_menuList, NULL, and prev.
Referenced by init_submenu(), and KeyQuant().
get_button()
aButton * actIntDispatcher::get_button (int id)
 {
     aButton* p;
     p = (aButton*)intButtons -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (aButton*)p -> prev;
     }
     p = (aButton*)invButtons -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (aButton*)p -> prev;
     }
     p = (aButton*)infButtons -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (aButton*)p -> prev;
     }
     return NULL;
 }
References infButtons, intButtons, invButtons, NULL, and prev.
Referenced by init_menus(), and inv_mouse_move_quant().
get_counter()
CounterPanel * actIntDispatcher::get_counter (int id)
 {
     CounterPanel* p;
     p = (CounterPanel*)intCounters -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (CounterPanel*)p -> prev;
     }
     p = (CounterPanel*)invCounters -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (CounterPanel*)p -> prev;
     }
     p = (CounterPanel*)infCounters -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (CounterPanel*)p -> prev;
     }
     return NULL;
 }
References infCounters, intCounters, invCounters, NULL, and prev.
get_ibs()
ibsObject * actIntDispatcher::get_ibs (int id)
 {
     ibsObject* p = (ibsObject*)ibsList -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (ibsObject*)p -> prev;
     }
     return NULL;
 }
References ibsList, NULL, and prev.
Referenced by change_ibs(), and init().
get_icounter()
CounterPanel * actIntDispatcher::get_icounter (int id)
 {
     CounterPanel* p;
     p = (CounterPanel*)i_Counters -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (CounterPanel*)p -> prev;
     }
     return NULL;
 }
References i_Counters, NULL, and prev.
get_iitem()
invItem * actIntDispatcher::get_iitem (int id)
 {
     invItem* p = (invItem*)i_itemList -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (invItem*)p -> prev;
     }
     return NULL;
 }
References i_itemList, NULL, and prev.
Referenced by acsLoadData(), inv_mouse_imove_quant(), load_data(), and trade_items().
get_imatrix()
invMatrix * actIntDispatcher::get_imatrix (int tp)
 {
     invMatrix* p = (invMatrix*)i_matrixList -> last;
     while(p){
         if(p -> type == tp)
             return p;
         p = (invMatrix*)p -> prev;
     }
     return NULL;
 }
References i_matrixList, NULL, and prev.
Referenced by alloc_matrix(), and load_data().
get_imenu()
fncMenu * actIntDispatcher::get_imenu (int mn)
 {
     fncMenu* m = (fncMenu*)i_menuList -> last;
     while(m){
         if(m -> type == mn)
             return m;
         m = (fncMenu*)m -> prev;
     }
     return NULL;
 }
References i_menuList, NULL, and prev.
get_ind()
aIndData * actIntDispatcher::get_ind (int id)
 {
     aIndData* p = (aIndData*)indList -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (aIndData*)p -> prev;
     }
     return NULL;
 }
References indList, NULL, and prev.
get_info_panel()
InfoPanel * actIntDispatcher::get_info_panel (int id)
 {
     InfoPanel* p = (InfoPanel*)i_infoPanels -> last;
     while(p){
         if(p -> type == id)
             return p;
         p = (InfoPanel*)p -> prev;
     }
     return NULL;
 }
References i_infoPanels, NULL, and prev.
get_item()
invItem * actIntDispatcher::get_item (int id)
 {
     invItem* p = (invItem*)itemList -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (invItem*)p -> prev;
     }
     return NULL;
 }
References itemList, NULL, and prev.
Referenced by acsLoadData(), inv_mouse_imove_quant(), inv_mouse_move_quant(), load_data(), put_item(), and trade_items().
get_item_ptr()
invItem * actIntDispatcher::get_item_ptr (int id)
 {
     if(!curMatrix) return NULL;
     invItem* p = (invItem*)curMatrix -> items -> last;
     while(p){
         if(p -> ID == id && !p -> item_ptr)
             return p;
         p = (invItem*)p -> prev;
     }
     return NULL;
 }
References curMatrix, NULL, and prev.
get_item_ptr_xy()
invItem * actIntDispatcher::get_item_ptr_xy (int id, int x, int y)
 {
     if(!curMatrix) return NULL;
     invItem* p = (invItem*)curMatrix -> items -> last;
     while(p){
         if(p -> ID == id && !p -> item_ptr && p -> MatrixX == x && p -> MatrixY == y)
             return p;
         p = (invItem*)p -> prev;
     }
     return NULL;
 }
References curMatrix, NULL, and prev.
Referenced by aciReInitItemXY().
get_locdata()
aciLocationInfo * actIntDispatcher::get_locdata (int id)
 {
     aciLocationInfo* p = (aciLocationInfo*)locationList -> last;
     while(p){
         if(p -> ID == id)
             return p;
         p = (aciLocationInfo*)p -> prev;
     }
     return NULL;
 }
References locationList, NULL, and prev.
Referenced by i_init().
get_locdata_id()
int actIntDispatcher::get_locdata_id (const char * name)
 {
     aciLocationInfo* p = (aciLocationInfo*)locationList -> last;
     while(p){
         if(!strcmp(p -> nameID,name))
             return p -> ID;
         p = (aciLocationInfo*)p -> prev;
     }
     ErrH.Abort("Bad Location name...");
     return -1;
 }
References XErrorHandler::Abort(), ErrH, locationList, and prev.
Referenced by i_init().
get_matrix()
invMatrix * actIntDispatcher::get_matrix (int tp)
 {
     invMatrix* p = (invMatrix*)matrixList -> last;
     while(p){
         if(p -> type == tp)
             return p;
         p = (invMatrix*)p -> prev;
     }
     return NULL;
 }
References matrixList, NULL, and prev.
Referenced by alloc_matrix(), i_init(), and load_data().
get_menu()
fncMenu * actIntDispatcher::get_menu (int mn)
 {
     fncMenu* m = (fncMenu*)menuList -> last;
     while(m){
         if(m -> type == mn)
             return m;
         m = (fncMenu*)m -> prev;
     }
     return NULL;
 }
References menuList, NULL, and prev.
Referenced by EventQuant(), and init_submenu().
i_finit()
void actIntDispatcher::i_finit (void)
 {
     CounterPanel* cp;
     invItem* itm;
     fncMenu* m;
     aciBufRedrawFlag = 0;
     aCellSize = aci_CellSize;
     CurrentWorld = prevWorld;
     aciChangeWorld(CurrentWorld);
     aciPrepareWorldsMenu();
     flags &= ~AS_ISCREEN;
     if(iscr_iP) iscr_iP -> finit();
     aciML_D -> finit();
     aciSet_aMouse();
     restore_mouse_cursor();
     if(!(flags & AS_FULLSCR))
         XGR_MouseShow();
     dgD -> endSession();
     SoundEscaveOff();
     delete qMenu;
     qMenu = NULL;
     if(flags & AS_INV_MOVE_ITEM){
         aciSell_Item(curItem);
         restore_mouse_cursor();
         curItem = NULL;
         flags ^= AS_INV_MOVE_ITEM;
     }
     m = (fncMenu*)i_menuList -> last;
     while(m){
         m -> finit();
         m = (fncMenu*)m -> prev;
     }
     cp = (CounterPanel*)i_Counters -> last;
     while(cp){
         cp -> finit();
         cp = (CounterPanel*)cp -> prev;
     }
     itm = (invItem*)i_itemList -> last;
     while(itm){
         itm -> finit();
         itm = (invItem*)itm -> prev;
     }
     free_cell_frame();
     iscr_iP = iP;
     iP = ascr_iP;
     init();
     aMS_init();
     if(curMatrix){
         a_curMatrix = alloc_matrix(curMatrix -> type);
         trade_items(a_curMatrix,0);
         free_matrix(curMatrix);
         curMatrix = a_curMatrix;
         clean_menus();
         prepare_menus();
         aciInitItmTextQueue();
     }
     aciPrevJumpCount = -1;
     iKeyClear();
 }
References a_curMatrix, aCellSize, aci_CellSize, aciBufRedrawFlag, aciChangeWorld(), aciInitItmTextQueue(), aciML_D, aciPrepareWorldsMenu(), aciPrevJumpCount, aciSell_Item(), aciSet_aMouse(), alloc_matrix(), aMS_init(), AS_FULLSCR, AS_INV_MOVE_ITEM, AS_ISCREEN, ascr_iP, clean_menus(), curItem, curMatrix, CurrentWorld, dgD, finit(), flags, free_cell_frame(), free_matrix(), i_Counters, i_itemList, i_menuList, iKeyClear(), init(), iP, iscr_iP, NULL, prepare_menus(), prev, prevWorld, qMenu, restore_mouse_cursor(), SoundEscaveOff(), trade_items(), and XGR_MouseShow.
i_flush()
void actIntDispatcher::i_flush (void)
 {
     invMatrix* m;
     CounterPanel* cp;
     if(!(flags & AS_ISCREEN_INV_MODE))
         return;
     if(flags & AS_FULL_FLUSH){
         flags &= ~AS_FULL_FLUSH;
         XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     }
     cp = (CounterPanel*)i_Counters -> last;
     while(cp){
         if(cp -> flags & CP_FLUSH){
             cp -> flush();
         }
         cp = (CounterPanel*)cp -> prev;
     }
     if(curMatrix){
         m = curMatrix;
         if(m -> flags & IM_FLUSH){
             m -> flush();
         }
         if(m -> flags & IM_REDRAW_SHADOW){
             m -> redraw_shadow_cells();
             m -> flush();
             m -> flags &= ~IM_REDRAW_SHADOW;
         }
     }
     if(secondMatrix){
         m = secondMatrix;
         if(m -> flags & IM_FLUSH){
             m -> flush();
         }
         if(m -> flags & IM_REDRAW_SHADOW){
             m -> redraw_shadow_cells();
             m -> flush();
             m -> flags &= ~IM_REDRAW_SHADOW;
         }
     }
 /*
     m = (invMatrix*)i_matrixList -> last;
     while(m){
         if(m -> flags & IM_FLUSH){
             m -> flush();
         }
         if(m -> flags & IM_REDRAW_SHADOW){
             m -> redraw_shadow_cells();
         }
         m = (invMatrix*)m -> prev;
     }
 */
     if(iP && iP -> flags & IP_FLUSH)
         iP -> flush();
 }
References AS_FULL_FLUSH, AS_ISCREEN_INV_MODE, CP_FLUSH, curMatrix, flags, flush(), i_Counters, IM_FLUSH, IM_REDRAW_SHADOW, iP, IP_FLUSH, prev, secondMatrix, XGR_Flush, XGR_MAXX, and XGR_MAXY.
i_init()
void actIntDispatcher::i_init (void)
 {
     int i;
     invMatrix* p;
     CounterPanel* cp;
     invItem* itm;
     aciLocationInfo* locData;
     fncMenu* m;
     XGR_GetPal(actIntPal);
     i_slake_pal(actIntPal,32);
     int emode = ExclusiveLog ? XGR_EXCLUSIVE : 0;
     /*if(XGR_MAXX != 800){
         if(XGR_ReInit(800,600,emode)) ErrH.Abort("Error video initialization");
     }*/
     XGR_Flip();
     LoadingMessage(1);
     aci_curLocationID = get_locdata_id(aci_curLocationName);
     locData = get_locdata(aci_curLocationID);
     if(!locData)
         ErrH.Abort("Location info not found...",XERR_USER,aci_curLocationID);
     aci_ivMapName = locData -> mapName;
     aci_iScreenID = locData -> screenID;
     curLocData = locData;
     locData -> prepare();
     memcpy(aci_iscrPal,iscrPal,768);
     XStream fh(locData -> palName,XS_IN);
     fh.read(iscrPal,768);
     fh.close();
     for(i = 0; i < 16; i ++){
         iscrPal[i * 3] = i * 4;
         iscrPal[i * 3 + 1] = i * 4;
         iscrPal[i * 3 + 2] = i * 4;
     }
     ipal_init(iscrPal);
     aciShowLocationPicture();
     finit();
     aciSet_iMouse();
     aci_CellSize = aCellSize;
     aCellSize = iCellSize;
     secondMatrix = NULL;
     flags &= ~AS_ISCREEN_INV_MODE;
     if(iscr_iP) iscr_iP -> init();
     m = (fncMenu*)i_menuList -> last;
     while(m){
         m -> init();
         m = (fncMenu*)m -> prev;
     }
     m = (fncMenu*)menuList -> last;
     while(m){
         if(m -> flags & FM_LOCATION_MENU)
             m -> flags &= ~FM_ACTIVE;
         m = (fncMenu*)m -> prev;
     }
     cp = (CounterPanel*)i_Counters -> last;
     while(cp){
         cp -> init();
         cp = (CounterPanel*)cp -> prev;
     }
     p = (invMatrix*)i_matrixList -> last;
     while(p){
         p -> init();
         p = (invMatrix*)p -> prev;
     }
     itm = (invItem*)i_itemList -> last;
     while(itm){
         itm -> init();
         itm = (invItem*)itm -> prev;
     }
     if(!curMatrix && GGamerMechos){
         p = get_matrix(GGamerMechos -> type);
         curMatrix = alloc_matrix(GGamerMechos -> type);
         p -> clone(curMatrix);
     }
     if(curMatrix){
         if(flags & AS_INV_MOVE_ITEM){
             flags ^= AS_INV_MOVE_ITEM;
             if(!curMatrix -> auto_put_item(curItem)){
                 aciSendEvent2itmdsp(ACI_DROP_ITEM,curItem -> item_ptr);
                 restore_mouse_cursor();
                 free_item(curItem);
             }
         }
         i_curMatrix = alloc_matrix(curMatrix -> type,1);
         trade_items(i_curMatrix,1);
         free_matrix(curMatrix);
         curMatrix = i_curMatrix;
     }
     else {
         a_curMatrix = NULL;
         i_curMatrix = NULL;
     }
     qMenu = new fncMenuSet;
     ascr_iP = iP;
     iP = iscr_iP;
     build_cell_frame();
     aciInitInfoPanels();
     aciInitEvLineID();
     aciInitShopItems();
     aciCurColorScheme = aciColorSchemes[SCH_ISCREEN];
     flags |= AS_ISCREEN;
     flags &= ~AS_FULL_REDRAW;
     prevWorld = CurrentWorld;
     CurrentWorld = -1;
     aciBufRedrawFlag = 1;
     PalIterLock = 1;
     dgD -> startSession(aci_curLocationName);
     LoadResourceSOUND(curLocData -> soundResPath,0);
     aciML_D -> init_data_set(aci_curLocationID);
     aciML_D -> init();
     aciPutTreasureItem();
     aciML_D -> startup();
 }
References a_curMatrix, XErrorHandler::Abort(), aCellSize, aci_CellSize, aci_curLocationID, aci_curLocationName, ACI_DROP_ITEM, aci_iScreenID, aci_iscrPal, aci_ivMapName, aciBufRedrawFlag, aciColorSchemes, aciCurColorScheme, aciInitEvLineID(), aciInitInfoPanels(), aciInitShopItems(), aciML_D, aciPutTreasureItem(), aciSendEvent2itmdsp(), aciSet_iMouse(), aciShowLocationPicture(), actIntPal, alloc_matrix(), AS_FULL_REDRAW, AS_INV_MOVE_ITEM, AS_ISCREEN, AS_ISCREEN_INV_MODE, ascr_iP, build_cell_frame(), XStream::close(), curItem, curLocData, curMatrix, CurrentWorld, dgD, emode, ErrH, ExclusiveLog, finit(), flags, FM_ACTIVE, FM_LOCATION_MENU, free_item(), free_matrix(), get_locdata(), get_locdata_id(), get_matrix(), GGamerMechos, i_Counters, i_curMatrix, i_itemList, i_matrixList, i_menuList, i_slake_pal(), iCellSize, init(), iP, ipal_init(), iscr_iP, iscrPal, LoadingMessage(), LoadResourceSOUND(), locData, menuList, NULL, PalIterLock, prev, prevWorld, qMenu, XStream::read(), restore_mouse_cursor(), SCH_ISCREEN, secondMatrix, trade_items(), XERR_USER, XGR_EXCLUSIVE, XGR_Flip, XGR_GetPal, and XS_IN.
Referenced by iPreInitFirst().
i_redraw()
void actIntDispatcher::i_redraw (void)
 {
     fncMenu* p;
     CounterPanel* cp;
     InfoPanel* ip;
     if(flags & AS_ISCREEN_INV_MODE){
         cp = (CounterPanel*)i_Counters -> last;
         while(cp){
             if(*cp -> value_ptr != cp -> last_value)
                 cp -> set_redraw();
             cp = (CounterPanel*)cp -> prev;
         }
     }
     if(!(flags & AS_FULL_REDRAW)){
         if(flags & AS_ISCREEN_INV_MODE){
             cp = (CounterPanel*)i_Counters -> last;
             while(cp){
                 cp -> redraw();
                 cp = (CounterPanel*)cp -> prev;
             }
             if(curMatrix){
                 curMatrix -> redraw();
             }
             if(secondMatrix){
                 secondMatrix -> redraw();
             }
             if(iP){
                 iP -> redraw();
             }
             p = (fncMenu*)i_menuList -> last;
             while(p){
                 if(!(p -> flags & FM_LOCATION_MENU) && p -> flags & FM_ACTIVE)
                     p -> redraw();
                 p = (fncMenu*)p -> prev;
             }
         }
         else {
             if(qMenu) qMenu -> redraw();
             p = (fncMenu*)i_menuList -> last;
             while(p){
                 if(p -> flags & FM_LOCATION_MENU && p -> flags & FM_ACTIVE)
                     p -> redraw();
                 p = (fncMenu*)p -> prev;
             }
         }
         ip = (InfoPanel*)i_infoPanels -> last;
         while(ip){
             ip -> redraw();
             ip = (InfoPanel*)ip -> prev;
         }
         flags |= AS_FULL_REDRAW;
         flags |= AS_FULL_FLUSH;
     }
     if(flags & AS_ISCREEN_INV_MODE){
         if(curMatrix && curMatrix -> flags & IM_REDRAW){
             curMatrix -> redraw();
             curMatrix -> set_flush();
         }
         if(secondMatrix && secondMatrix -> flags & IM_REDRAW){
             secondMatrix -> redraw();
             secondMatrix -> set_flush();
         }
         if(iP){
             if(iP -> flags & IP_REDRAW){
                 iP -> redraw();
                 iP -> set_flush();
             }
         }
         cp = (CounterPanel*)i_Counters -> last;
         while(cp){
             if(cp -> flags & CP_REDRAW){
                 cp -> redraw();
                 cp -> set_flush();
             }
             cp = (CounterPanel*)cp -> prev;
         }
         p = (fncMenu*)i_menuList -> last;
         while(p){
             if(!(p -> flags & FM_LOCATION_MENU) && p -> flags & FM_ACTIVE){
                 p -> redraw();
                 p -> set_flush();
             }
             p = (fncMenu*)p -> prev;
         }
     }
     else {
         if(qMenu && qMenu -> flags & FMC_REDRAW) qMenu -> redraw();
         p = (fncMenu*)i_menuList -> last;
         while(p){
             if(p -> flags & FM_LOCATION_MENU && p -> flags & FM_ACTIVE){
                 p -> redraw();
                 p -> set_flush();
             }
             p = (fncMenu*)p -> prev;
         }
     }
     ip = (InfoPanel*)i_infoPanels -> last;
     while(ip){
         if(ip -> flags & IP_REDRAW){
             ip -> redraw();
             ip -> set_flush();
         }
         ip = (InfoPanel*)ip -> prev;
     }
 }
References AS_FULL_FLUSH, AS_FULL_REDRAW, AS_ISCREEN_INV_MODE, CP_REDRAW, curMatrix, flags, FM_ACTIVE, FM_LOCATION_MENU, FMC_REDRAW, i_Counters, i_infoPanels, i_menuList, IM_REDRAW, iP, IP_REDRAW, prev, qMenu, redraw(), and secondMatrix.
iKeyQuant()
void actIntDispatcher::iKeyQuant (void)
 {
     fncMenu* m;
     if(flags & AS_ISCREEN_INV_MODE){
         inv_mouse_imove_quant();
         if(flags & aMS_MOVED){
             flags &= ~aMS_MOVED;
             m = (fncMenu*)i_menuList -> last;
             while(m){
                 if(!(m -> flags & FM_HIDDEN) && m -> check_xy(iMouseX,iMouseY)){
                     if(m -> flags & FM_ACTIVE){
                         m -> change(iMouseX,iMouseY,1);
                         if(m -> type == SHOP_ITEMS_MENU_ID)
                             aciSetShopItem(m -> curFunction);
                     }
                 }
                 m = (fncMenu*)m -> prev;
             }
         }
         if(flags & aMS_PRESS){
             if(flags & aMS_LEFT_PRESS){
                 flags &= ~aMS_LEFT_PRESS;
                 inv_mouse_quant_l();
             }
             if(flags & aMS_RIGHT_PRESS){
                 flags &= ~aMS_RIGHT_PRESS;
                 inv_mouse_quant_r();
             }
         }
     }
     else {
         if(flags & aMS_MOVED){
             flags &= ~aMS_MOVED;
             m = (fncMenu*)menuList -> last;
             while(m){
                 if(!(m -> flags & FM_HIDDEN) && m -> check_xy(iMouseX,iMouseY)){
                     if(m -> flags & FM_ACTIVE){
                         m -> change(iMouseX,iMouseY,1);
                     }
                 }
                 m = (fncMenu*)m -> prev;
             }
             if(iMouseLPressFlag){
                 if(qMenu && qMenu -> flags & FMC_DATA_INIT && qMenu -> check_xy(iMouseX,iMouseY) && qMenu -> check_xy(iMousePrevX,iMousePrevY)){
                     qMenu -> shift((iMouseX - iMousePrevX) * 4);
                 }
             }
         }
         if(flags & aMS_PRESS){
             if(flags & aMS_LEFT_PRESS){
                 if(qMenu && qMenu -> flags & FMC_DATA_INIT){
                     qMenu -> key_trap(iMouseX,iMouseY);
                 }
                 m = (fncMenu*)i_menuList -> last;
                 while(m){
                     if(m -> check_xy(iMouseX,iMouseY)){
                         if(m -> flags & FM_ACTIVE){
                             m -> change(iMouseX,iMouseY);
                             SOUND_SELECT();
                         }
                     }
                     m = (fncMenu*)m -> prev;
                 }
                 flags &= ~aMS_LEFT_PRESS;
             }
         }
     }
 }
References aciSetShopItem(), aMS_LEFT_PRESS, aMS_MOVED, aMS_PRESS, aMS_RIGHT_PRESS, AS_ISCREEN_INV_MODE, flags, FM_ACTIVE, FM_HIDDEN, FMC_DATA_INIT, i_menuList, iMouseLPressFlag, iMousePrevX, iMousePrevY, iMouseX, iMouseY, inv_mouse_imove_quant(), inv_mouse_quant_l(), inv_mouse_quant_r(), menuList, prev, qMenu, SHOP_ITEMS_MENU_ID, and SOUND_SELECT.
iKeyTrap()
void actIntDispatcher::iKeyTrap (int cd)
 {
     fncMenu* m;
     if(!NetworkON) aciCHandler(cd);
     if(!(flags & AS_ISCREEN_INV_MODE)){
         m = (fncMenu*)i_menuList -> last;
         while(m){
             if(m -> flags & FM_LOCATION_MENU && m -> flags & FM_ACTIVE && m -> up_key -> check(cd)){
                 m -> step_up();
                 m -> set_redraw();
                 SOUND_SELECT();
             }
             if(m -> flags & FM_ACTIVE && m -> down_key -> check(cd)){
                 m -> step_down();
                 m -> set_redraw();
                 SOUND_SELECT();
             }
             m = (fncMenu*)m -> prev;
         }
     }
 }
References aciCHandler(), AS_ISCREEN_INV_MODE, flags, FM_ACTIVE, FM_LOCATION_MENU, i_menuList, NetworkON, prev, and SOUND_SELECT.
ind_redraw()
void actIntDispatcher::ind_redraw (void)
 {
     aIndData* p;
     if(flags & AS_FULLSCR)
         return;
     p = (aIndData*)indList -> last;
     while(p){
         p -> redraw();
         p = (aIndData*)p -> prev;
     }
 }
References AS_FULLSCR, flags, indList, prev, and redraw().
init()
void actIntDispatcher::init (void)
 {
     fncMenu* it;
     invItem* itm;
     invMatrix* p;
     aButton* b;
     aIndData* ind;
     CounterPanel* cp;
     InfoPanel* ip;
     aciBitmapMenu* bm;
     ibsObject* ibs;
     bmlObject* bml;
     aciCurColorScheme = aciColorSchemes[SCH_DEFAULT];
     if(iP) iP -> init();
     ip = (InfoPanel*)infoPanels -> last;
     while(ip){
         ip -> init();
         ip = (InfoPanel*)ip -> prev;
     }
     bm = (aciBitmapMenu*)b_menuList -> last;
     while(bm){
         bm -> init();
         bm = (aciBitmapMenu*)bm -> prev;
     }
     if(wMap) wMap -> init();
     aciSet_aMouse();
     ind = (aIndData*)indList -> last;
     while(ind){
         ind -> init();
         ind = (aIndData*)ind -> prev;
     }
     cp = (CounterPanel*)intCounters -> last;
     while(cp){
         cp -> init();
         cp = (CounterPanel*)cp -> prev;
     }
     cp = (CounterPanel*)infCounters -> last;
     while(cp){
         cp -> init();
         cp = (CounterPanel*)cp -> prev;
     }
     cp = (CounterPanel*)invCounters -> last;
     while(cp){
         cp -> init();
         cp = (CounterPanel*)cp -> prev;
     }
     p = (invMatrix*)matrixList -> last;
     while(p){
         p -> init();
         p = (invMatrix*)p -> prev;
     }
 #ifdef _ACI_SKIP_SHOP_
     if(!curMatrix){
         curMatrix = alloc_matrix(curMatrixID);
     }
 #endif
     ibs = (ibsObject*)ibsList -> last;
     while(ibs){
         bml = get_back_bml(ibs -> backObjID);
         ibs -> back = bml;
         ibs = (ibsObject*)ibs -> prev;
     }
     curIbs = get_ibs(curIbsID);
     load_ibs();
     if(wMap -> world_ids[CurrentWorld] != -1 && map_names[wMap -> world_ids[CurrentWorld]]){
         mapObj -> free();
         mapObj -> load(map_names[wMap -> world_ids[CurrentWorld]],1);
     }
     else {
         ErrH.Abort("Map BMP not found...");
     }
     itm = (invItem*)itemList -> last;
     while(itm){
         itm -> init();
         itm = (invItem*)itm -> prev;
     }
     it = (fncMenu*)menuList -> last;
     while(it){
         it -> init();
         it = (fncMenu*)it -> prev;
     }
     b = (aButton*)intButtons -> last;
     while(b){
         b -> init();
         b = (aButton*)b -> prev;
     }
     b = (aButton*)invButtons -> last;
     while(b){
         b -> init();
         b = (aButton*)b -> prev;
     }
     b = (aButton*)infButtons -> last;
     while(b){
         b -> init();
         b = (aButton*)b -> prev;
     }
     init_menus();
     build_cell_frame();
     if(flags & AS_FULLSCR){
         XGR_MouseSetPromptData(NULL);
         XGR_MouseHide();
     }
     else {
         switch(curMode){
             case AS_INV_MODE:
                 XGR_MouseSetPromptData(invPrompt);
                 break;
             case AS_INFO_MODE:
                 XGR_MouseSetPromptData(infPrompt);
                 break;
         }
     }
     XGR_MouseObj.PromptColor = 160 | (1 << 16);
     aciPrevJumpCount = -1;
 }
References XErrorHandler::Abort(), aciColorSchemes, aciCurColorScheme, aciPrevJumpCount, aciSet_aMouse(), alloc_matrix(), AS_FULLSCR, AS_INFO_MODE, AS_INV_MODE, b_menuList, build_cell_frame(), curIbs, curIbsID, curMatrix, curMatrixID, curMode, CurrentWorld, ErrH, flags, get_back_bml(), get_ibs(), ibsList, indList, infButtons, infCounters, infoPanels, infPrompt, init_menus(), intButtons, intCounters, invButtons, invCounters, invPrompt, iP, itemList, load_ibs(), map_names, mapObj, matrixList, menuList, NULL, prev, XGR_Mouse::PromptColor, SCH_DEFAULT, wMap, XGR_MouseHide, XGR_MouseObj, and XGR_MouseSetPromptData.
Referenced by i_finit(), i_init(), and init_prompt().
init_inds()
void actIntDispatcher::init_inds (void)
 {
     int lx,ly,rx,ry,cx,cy;
     ibsObject* ibs = curIbs;
     XGR_MousePromptData* pr;
     lx = ibs -> PosX;
     ly = ibs -> PosY;
     rx = lx + ibs -> SizeX;
     ry = ly + ibs -> SizeY;
     aIndData* p = (aIndData*)indList -> last;
     while(p){
         switch(p -> CornerNum){
             case IND_UP_LEFT:
                 p -> PosX = lx + ibs -> indPosX[0];
                 p -> PosY = ly + ibs -> indPosY[0];
                 break;
             case IND_UP_RIGHT:
                 p -> PosX = rx - ibs -> indPosX[1] - p -> SizeX;
                 p -> PosY = ly + ibs -> indPosY[1];
                 break;
             case IND_DN_LEFT:
                 p -> PosX = lx + ibs -> indPosX[2];
                 p -> PosY = ry - ibs -> indPosY[2] - p -> SizeY;
                 break;
             case IND_DN_RIGHT:
                 p -> PosX = rx - ibs -> indPosX[3] - p -> SizeX;
                 p -> PosY = ry - ibs -> indPosY[3] - p -> SizeY;
                 break;
         }
         if(p -> bml){
             cx = p -> PosX + (p -> SizeX >> 1);
             cy = p -> PosY + (p -> SizeY >> 1);
             p -> bml -> OffsX = cx - (p -> bml -> SizeX >> 1);
             p -> bml -> OffsY = cy - (p -> bml -> SizeY >> 1);
         }
         if(p -> ID == IND_DVC){
             if(curMatrix && !curMatrix -> slot_exist(3)){
                 p -> flags |= IND_DISABLED;
             }
             else {
                 p -> flags &= ~IND_DISABLED;
             }
         }
         pr = invPrompt -> getData(p -> ID);
         if(pr){
             if(p -> flags & IND_DISABLED){
                 pr -> StartX = 0;
                 pr -> StartY = 0;
                 pr -> SizeX = 0;
                 pr -> SizeY = 0;
             }
             else {
                 pr -> StartX = p -> PosX;
                 pr -> StartY = p -> PosY;
                 pr -> SizeX = p -> SizeX;
                 pr -> SizeY = p -> SizeY;
             }
         }
         pr = infPrompt -> getData(p -> ID);
         if(pr){
             if(p -> flags & IND_DISABLED){
                 pr -> StartX = 0;
                 pr -> StartY = 0;
                 pr -> SizeX = 0;
                 pr -> SizeY = 0;
             }
             else {
                 pr -> StartX = p -> PosX;
                 pr -> StartY = p -> PosY;
                 pr -> SizeX = p -> SizeX;
                 pr -> SizeY = p -> SizeY;
             }
         }
         p = (aIndData*)p -> prev;
     }
 }
References curIbs, curMatrix, flags, IND_DISABLED, IND_DN_LEFT, IND_DN_RIGHT, IND_DVC, IND_UP_LEFT, IND_UP_RIGHT, indList, infPrompt, invPrompt, and prev.
Referenced by load_ibs().
init_menus()
void actIntDispatcher::init_menus (void)
 {
     fncMenu* m,*m1;
     fncMenuItem* p,*p1;
     m = (fncMenu*)menuList -> last;
     while(m){
         if(!(m -> flags & FM_SUBMENU)){
             p = (fncMenuItem*)m -> inactive_items -> last;
             while(p){
                 p1 = (fncMenuItem*)p -> prev;
                 m -> inactive_items -> dconnect((iListElement*)p);
                 m -> items -> connect((iListElement*)p);
                 p = p1;
             }
             m -> curItem = m -> get_fnc_item(m -> curFunction);
             if(m -> VItems < m -> items -> Size)
                 m -> firstItem = m -> curItem;
             else
                 m -> firstItem = (fncMenuItem*)m -> items -> first;
             m -> trigger = get_button(m -> trigger_code);
         }
         m = (fncMenu*)m -> prev;
     }
     m = (fncMenu*)menuList -> last;
     while(m){
         if(!(m -> flags & FM_SUBMENU)){
             p = (fncMenuItem*)m -> items -> last;
             while(p){
                 p1 = (fncMenuItem*)p -> prev;
                 m1 = (fncMenu*)menuList -> last;
                 while(m1){
                     if(!(m1 -> flags & FM_SUBMENU)){
                         if(m1 != m && m1 -> curFunction && m1 -> curFunction == p -> fnc_code){
                             if(m -> curItem == p){
                                 m -> curItem = (fncMenuItem*)p -> next;
                                 m -> curFunction = m -> curItem -> fnc_code;
                             }
                             m -> items -> dconnect((iListElement*)p);
                             m -> inactive_items -> connect((iListElement*)p);
                             m1 = NULL;
                         }
                         else
                             m1 = (fncMenu*)m1 -> prev;
                     }
                     else
                         m1 = (fncMenu*)m1 -> prev;
                 }
                 p = p1;
             }
             m -> sort();
             m -> curItem = m -> get_fnc_item(m -> curFunction);
             if(m -> VItems < m -> items -> Size)
                 m -> firstItem = m -> curItem;
             else
                 m -> firstItem = (fncMenuItem*)m -> items -> first;
             if(m -> flags & FM_ACTIVE) m -> set_redraw();
         }
         m = (fncMenu*)m -> prev;
     }
 }
References curItem, flags, FM_SUBMENU, get_button(), menuList, and prev.
Referenced by init(), KeyQuant(), and redraw().
init_prompt()
void actIntDispatcher::init_prompt (void)
 {
     aButton* b;
     aIndData* ind;
     XGR_MousePromptData* p;
     ind = (aIndData*)indList -> last;
     while(ind){
         if(ind -> promptData){
             p = new XGR_MousePromptData;
             p -> ID = ind -> ID;
             p -> set_text(ind -> promptData);
             invPrompt -> AddElement((XListElement*)p);
             p = new XGR_MousePromptData;
             p -> ID = ind -> ID;
             p -> set_text(ind -> promptData);
             infPrompt -> AddElement((XListElement*)p);
         }
         ind = (aIndData*)ind -> prev;
     }
     b = (aButton*)intButtons -> last;
     while(b){
         b -> init();
         if(b -> promptData){
             p = new XGR_MousePromptData(b -> PosX,b -> PosY,b -> SizeX,b -> SizeY,0);
             p -> set_text(b -> promptData);
             invPrompt -> AddElement((XListElement*)p);
             p = new XGR_MousePromptData(b -> PosX,b -> PosY,b -> SizeX,b -> SizeY,0);
             p -> set_text(b -> promptData);
             infPrompt -> AddElement((XListElement*)p);
         }
         b = (aButton*)b -> prev;
     }
     b = (aButton*)invButtons -> last;
     while(b){
         b -> init();
         if(b -> promptData){
             p = new XGR_MousePromptData(b -> PosX,b -> PosY,b -> SizeX,b -> SizeY,0);
             p -> set_text(b -> promptData);
             switch(b -> ID){
                 case ACI_WPN_PICKUP_BUTTON:
                     p -> ID = ACI_PICKUP_WPN_ON;
                     break;
                 case ACI_ITM_PICKUP_BUTTON:
                     p -> ID = ACI_PICKUP_ITM_ON;
                     break;
             }
             invPrompt -> AddElement((XListElement*)p);
         }
         b = (aButton*)b -> prev;
     }
     b = (aButton*)infButtons -> last;
     while(b){
         b -> init();
         if(b -> promptData){
             p = new XGR_MousePromptData(b -> PosX,b -> PosY,b -> SizeX,b -> SizeY,0);
             p -> set_text(b -> promptData);
             infPrompt -> AddElement((XListElement*)p);
         }
         b = (aButton*)b -> prev;
     }
 }
References ACI_ITM_PICKUP_BUTTON, ACI_PICKUP_ITM_ON, ACI_PICKUP_WPN_ON, ACI_WPN_PICKUP_BUTTON, indList, infButtons, infPrompt, init(), intButtons, invButtons, invPrompt, and prev.
init_submenu()
void actIntDispatcher::init_submenu (fncMenu * m)
 {
     char* ptr;
     fncMenu* p = NULL;
     aciBitmapMenu* bm = NULL;
     if(!m -> curItem) return;
     if(m -> curItem -> flags & FM_SUBMENU_ITEM){
         p = get_menu(m -> curItem -> submenuID);
         if(!p) ErrH.Abort("init_submenu() failed...");
         if(m -> curItem -> submenuID == FMENU_TELEPORT_MENU)
             p -> curFunction = FMENU_OFF;
         m -> init_submenu(p);
         p -> init_curItem();
         p -> curCount = p -> activeCount;
         p -> flags |= FM_LOCK;
         if(p -> VItems < p -> items -> Size)
             p -> firstItem = p -> curItem;
         else
             p -> firstItem = (fncMenuItem*)p -> items -> first;
     }
     else {
         if(m -> curItem -> flags & FM_BSUBMENU_ITEM){
             bm = get_bmenu(m -> curItem -> submenuID);
             bm -> upMenu = (iListElement*)m;
             if(bm -> activeCount)
                 bm -> curCount = bm -> activeCount;
         }
     }
     switch(m -> curFunction){
         case FMENU_TARGETS:
             if(!p) return;
             ptr = GetCompasTarget();
             if(!ptr)
                 p -> curItem = p -> get_obj(aciSTR_OFF);
             else
                 p -> curItem = p -> get_obj(ptr);
             if(p -> VItems < p -> items -> Size)
                 p -> firstItem = p -> curItem;
             else
                 p -> firstItem = (fncMenuItem*)p -> items -> first;
             break;
     }
 }
References XErrorHandler::Abort(), aciSTR_OFF, curItem, ErrH, flags, FM_BSUBMENU_ITEM, FM_LOCK, FM_SUBMENU_ITEM, FMENU_OFF, FMENU_TARGETS, FMENU_TELEPORT_MENU, get_bmenu(), get_menu(), GetCompasTarget(), and NULL.
Referenced by KeyQuant(), and redraw().
inv_mouse_imove_quant()
void actIntDispatcher::inv_mouse_imove_quant (void)
 {
     int mx,my,x,y;
     invItem* p = NULL;
     invItem* p1 = NULL;
     iScreenObject* obj;
     int cr = aciGetCurCredits();
     XGR_MousePromptData* pr = NULL,*pr0 = NULL,*pr1,*avi_pr1,*avi_pr2;
     if(XGR_MouseObj.promptData){
         pr = XGR_MouseObj.promptData -> getData(ACI_NO_CASH_PROMPT);
         pr0 = XGR_MouseObj.promptData -> getData(ACI_NO_CASH_PROMPT2);
         pr1 = XGR_MouseObj.promptData -> getData(ACI_BT15_PROMPT);
         avi_pr1 = XGR_MouseObj.promptData -> getData(ACI_AVI_PROMPT1);
         if(avi_pr1){
             avi_pr2 = XGR_MouseObj.promptData -> getData(ACI_AVI_PROMPT2);
             if(!avi_pr2){
                 avi_pr2 = new XGR_MousePromptData;
                 avi_pr2 -> ID = ACI_AVI_PROMPT2;
                 XGR_MouseObj.promptData -> AddElement((XListElement*)avi_pr2);
                 avi_pr2 -> set_text(aciSTR_PutThis);
             }
             obj = (iScreenObject*)curLocData -> objList[ACI_AVI_OBJ_ID];
             if(flags & AS_INV_MOVE_ITEM){
                 avi_pr2 -> StartX = obj -> PosX;
                 avi_pr2 -> StartY = obj -> PosY;
                 avi_pr2 -> SizeX = obj -> SizeX;
                 avi_pr2 -> SizeY = obj -> SizeY;
                 avi_pr1 -> StartX = avi_pr1 -> StartY = 0;
                 avi_pr1 -> SizeX = avi_pr1 -> SizeY = 0;
             }
             else {
                 avi_pr1 -> StartX = obj -> PosX;
                 avi_pr1 -> StartY = obj -> PosY;
                 avi_pr1 -> SizeX = obj -> SizeX;
                 avi_pr1 -> SizeY = obj -> SizeY;
                 avi_pr2 -> StartX = avi_pr2 -> StartY = 0;
                 avi_pr2 -> SizeX = avi_pr2 -> SizeY = 0;
             }
         }
     }
     if(pr) pr -> StartX = pr -> StartY = pr -> SizeX = pr -> SizeY = 0;
     if(!pr0){
         pr0 = new XGR_MousePromptData;
         pr0 -> ID = ACI_NO_CASH_PROMPT2;
         XGR_MouseObj.promptData -> AddElement((XListElement*)pr0);
         pr0 -> set_text(aciSTR_NO_CASH);
     }
     if(secondMatrix){
         obj = (iScreenObject*)iGetObject(iScrDisp->curScr->ID_ptr.c_str(),"Button15");
         if(((uvsActInt*)secondMatrix -> uvsDataPtr) -> price > cr + aciGetCurMatrixPrice()){
             if(pr0){
                 pr0 -> StartX = obj -> PosX;
                 pr0 -> StartY = obj -> PosY;
                 pr0 -> SizeX = obj -> SizeX;
                 pr0 -> SizeY = obj -> SizeY;
             }
             if(pr1){
                 pr1 -> StartX = 0;
                 pr1 -> StartY = 0;
                 pr1 -> SizeX = 0;
                 pr1 -> SizeY = 0;
             }
         }
         else {
             if(pr1){
                 pr1 -> StartX = obj -> PosX;
                 pr1 -> StartY = obj -> PosY;
                 pr1 -> SizeX = obj -> SizeX;
                 pr1 -> SizeY = obj -> SizeY;
             }
             if(pr0){
                 pr0 -> StartX = 0;
                 pr0 -> StartY = 0;
                 pr0 -> SizeX = 0;
                 pr0 -> SizeY = 0;
             }
         }
     }
     if(flags & aMS_MOVED){
         if(curMatrix) curMatrix -> clear_shadow_cells();
         if(secondMatrix) secondMatrix -> clear_shadow_cells();
     }
     mx = iMouseX;
     my = iMouseY;
     if(flags & AS_ISCREEN)
         mx += iScreenOffs - 800;
     if(flags & AS_INV_MOVE_ITEM){
         if(curItem -> flags & INV_ITEM_NO_PAY && ((uvsActInt*)curItem -> uvsDataPtr) -> price > cr){
             if(!pr){
                 pr = new XGR_MousePromptData;
                 pr -> ID = ACI_NO_CASH_PROMPT;
                 XGR_MouseObj.promptData -> AddElement((XListElement*)pr);
                 pr -> set_text(aciSTR_NO_CASH);
             }
             pr -> StartX = curMatrix -> ScreenX + iScreenOffs;
             pr -> StartY = curMatrix -> ScreenY;
             pr -> SizeX = curMatrix -> ScreenSizeX;
             pr -> SizeY = curMatrix -> ScreenSizeY;
         }
     }
     if(curMatrix && curMatrix -> check_xy(mx,my)){
         if(flags & AS_INV_MOVE_ITEM){
             x = iMouseX - curMatrix -> ScreenX - (curItem -> ShapeSizeX >> 1) + curItem -> ShapeCenterX;
             y = iMouseY - curMatrix -> ScreenY - (curItem -> ShapeSizeY >> 1) + curItem -> ShapeCenterY;
             x += iScreenOffs - 800;
             y /= aCellSize - (aCellSize >> 2);
             if(y & 0x01) x -= (aCellSize >> 1);
             x /= aCellSize;
         }
         else {
             x = iMouseX - curMatrix -> ScreenX;
             y = iMouseY - curMatrix -> ScreenY;
             x += iScreenOffs - 800;
             y /= aCellSize - (aCellSize >> 2);
             if(y & 0x01) x -= (aCellSize >> 1);
             x /= aCellSize;
         }
         if(x >= 0 && x < curMatrix -> SizeX && y >= 0 && y < curMatrix -> SizeY){
             if(flags & AS_INV_MOVE_ITEM){
                 if(curMatrix -> check_fit(x,y,curItem)){
                     curMatrix -> put_item_shadow(x,y,curItem);
                 }
                 else {
                     p = curMatrix -> get_area_item(x,y,curItem);
                     if(p){
                         curMatrix -> remove_item(p,1);
                         if(curMatrix -> check_fit(x,y,curItem))
                             curMatrix -> put_item_shadow(x,y,curItem);
                         curMatrix -> put_item(p -> MatrixX,p -> MatrixY,p,1);
                     }
                 }
             }
             else {
                 if(iP){
                     p = curMatrix -> get_item(x,y);
                     if(iP -> items -> Size){
                         iP -> free_list();
                         iP -> set_redraw();
                     }
                     if(p){
                         p1 = get_iitem(p -> ID);
                         iP -> add_item(p1->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
                         iP -> add_items(p1 -> numComments,p1 -> comments);
                         if(p1 -> pTemplate)
                             iP -> add_item(aciGetItemLoad(p,1));
                         if(!uvsCurrentWorldUnable)
                             iP -> add_item(aciGetPrice((iListElement*)p,ITEMS_MODE,1));
                     }
                 }
             }
         }
     }
     else {
         if(secondMatrix && secondMatrix -> check_xy(mx,my)){
             if(flags & AS_INV_MOVE_ITEM){
                 x = iMouseX - secondMatrix -> ScreenX - (curItem -> ShapeSizeX >> 1) + curItem -> ShapeCenterX;
                 y = iMouseY - secondMatrix -> ScreenY - (curItem -> ShapeSizeY >> 1) + curItem -> ShapeCenterY;
                 x += iScreenOffs - 800;
                 y /= aCellSize - (aCellSize >> 2);
                 if(y & 0x01) x -= (aCellSize >> 1);
                 x /= aCellSize;
             }
             else {
                 x = iMouseX - secondMatrix -> ScreenX;
                 y = iMouseY - secondMatrix -> ScreenY;
                 x += iScreenOffs - 800;
                 y /= aCellSize - (aCellSize >> 2);
                 if(y & 0x01) x -= (aCellSize >> 1);
                 x /= aCellSize;
             }
             if(x >= 0 && x < secondMatrix -> SizeX && y >= 0 && y < secondMatrix -> SizeY){
                 if(flags & AS_INV_MOVE_ITEM){
                     if(secondMatrix -> check_fit(x,y,curItem)){
                         secondMatrix -> put_item_shadow(x,y,curItem);
                     }
                     else {
                         p = secondMatrix -> get_area_item(x,y,curItem);
                         if(p){
                             secondMatrix -> remove_item(p,1);
                             if(secondMatrix -> check_fit(x,y,curItem))
                                 secondMatrix -> put_item_shadow(x,y,curItem);
                             secondMatrix -> put_item(p -> MatrixX,p -> MatrixY,p,1);
                         }
                     }
                 }
                 else {
                     if(iP){
                         p = secondMatrix -> get_item(x,y);
                         if(iP -> items -> Size){
                             iP -> free_list();
                             iP -> set_redraw();
                         }
                         if(p){
                             iP -> add_item(p->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
                             iP -> add_items(p -> numComments,p -> comments);
                             if(p -> pTemplate)
                                 iP -> add_item(aciGetItemLoad(p,1));
                             if(!uvsCurrentWorldUnable)
                                 iP -> add_item(aciGetPrice((iListElement*)p,ITEMS_MODE,1));
                         }
                     }
                 }
             }
         }
         else {
             if(!(flags & AS_INV_MOVE_ITEM)){
                 if(iP){
                     if(iP -> items -> Size){
                         iP -> free_list();
                         iP -> set_redraw();
                     }
                 }
             }
         }
     }
     if(flags & aMS_MOVED){
         if(curMatrix && curMatrix -> check_redraw()){
             curMatrix -> flags |= IM_REDRAW_SHADOW;
         }
         if(secondMatrix && secondMatrix -> check_redraw()){
             secondMatrix -> flags |= IM_REDRAW_SHADOW;
         }
     }
     if(iP){
         if(!iP -> items -> Size){
             aciInitMechosInfo(curMatrix,iP);
         }
     }
 }
References aCellSize, ACI_AVI_OBJ_ID, ACI_AVI_PROMPT1, ACI_AVI_PROMPT2, ACI_BT15_PROMPT, ACI_NO_CASH_PROMPT, ACI_NO_CASH_PROMPT2, aciCurColorScheme, aciGetCurCredits(), aciGetCurMatrixPrice(), aciGetItemLoad(), aciGetPrice(), aciInitMechosInfo(), aciSTR_NO_CASH, aciSTR_PutThis, add_item(), aMS_MOVED, AS_INV_MOVE_ITEM, AS_ISCREEN, curItem, curLocData, curMatrix, iScreenDispatcher::curScr, flags, FM_SELECT_COL, get_iitem(), get_item(), iListElement::ID_ptr, iGetObject(), IM_REDRAW_SHADOW, iMouseX, iMouseY, INV_ITEM_NO_PAY, iP, iScrDisp, iScreenOffs, ITEMS_MODE, NULL, XGR_Mouse::promptData, put_item(), remove_item(), secondMatrix, uvsCurrentWorldUnable, and XGR_MouseObj.
Referenced by iKeyQuant().
inv_mouse_move_quant()
void actIntDispatcher::inv_mouse_move_quant (void)
 {
     int x,y,ix,iy,isx,isy,id = -1;
     invItem* p = NULL;
     XBuffer* XBuf;
     char* ptr;
     aButton* bt;
     XGR_MousePromptData* pr = NULL,*bt_pr0,*bt_pr1;
     if(XGR_MouseObj.promptData){
         pr = XGR_MouseObj.promptData -> getData(ACI_ITEM_PROMPT);
     }
     if(pr) pr -> StartX = pr -> StartY = pr -> SizeX = pr -> SizeY = 0;
     if(curMode != AS_INV_MODE)
         return;
     bt = get_button(ACI_WPN_PICKUP_BUTTON);
     if(bt){
         if(XGR_MouseObj.promptData){
             bt_pr0 = XGR_MouseObj.promptData -> getData(ACI_PICKUP_WPN_ON);
             bt_pr1 = XGR_MouseObj.promptData -> getData(ACI_PICKUP_WPN_OFF);
             if(!bt_pr1){
                 bt_pr1 = new XGR_MousePromptData;
                 bt_pr1 -> set_text(aciSTR_PICKUP_WEAPONS_OFF);
                 bt_pr1 -> ID = ACI_PICKUP_WPN_OFF;
                 XGR_MouseObj.promptData -> AddElement((XListElement*)bt_pr1);
             }
             if(bt -> flags & B_PRESSED){
                 if(bt_pr0) bt_pr0 -> StartX = bt_pr0 -> StartY = bt_pr0 -> SizeX = bt_pr0 -> SizeY = 0;
                 bt_pr1 -> StartX = bt -> PosX;
                 bt_pr1 -> StartY = bt -> PosY;
                 bt_pr1 -> SizeX = bt -> SizeX;
                 bt_pr1 -> SizeY = bt -> SizeY;
             }
             else {
                 if(bt_pr1) bt_pr1 -> StartX = bt_pr1 -> StartY = bt_pr1 -> SizeX = bt_pr1 -> SizeY = 0;
                 if(bt_pr0){
                     bt_pr0 -> StartX = bt -> PosX;
                     bt_pr0 -> StartY = bt -> PosY;
                     bt_pr0 -> SizeX = bt -> SizeX;
                     bt_pr0 -> SizeY = bt -> SizeY;
                 }
             }
         }
     }
     bt = get_button(ACI_ITM_PICKUP_BUTTON);
     if(bt){
         if(XGR_MouseObj.promptData){
             bt_pr0 = XGR_MouseObj.promptData -> getData(ACI_PICKUP_ITM_ON);
             bt_pr1 = XGR_MouseObj.promptData -> getData(ACI_PICKUP_ITM_OFF);
             if(!bt_pr1){
                 bt_pr1 = new XGR_MousePromptData;
                 bt_pr1 -> set_text(aciSTR_PICKUP_ITEMS_OFF);
                 bt_pr1 -> ID = ACI_PICKUP_ITM_OFF;
                 XGR_MouseObj.promptData -> AddElement((XListElement*)bt_pr1);
             }
             if(bt -> flags & B_PRESSED){
                 if(bt_pr0) bt_pr0 -> StartX = bt_pr0 -> StartY = bt_pr0 -> SizeX = bt_pr0 -> SizeY = 0;
                 bt_pr1 -> StartX = bt -> PosX;
                 bt_pr1 -> StartY = bt -> PosY;
                 bt_pr1 -> SizeX = bt -> SizeX;
                 bt_pr1 -> SizeY = bt -> SizeY;
             }
             else {
                 if(bt_pr1) bt_pr1 -> StartX = bt_pr1 -> StartY = bt_pr1 -> SizeX = bt_pr1 -> SizeY = 0;
                 if(bt_pr0){
                     bt_pr0 -> StartX = bt -> PosX;
                     bt_pr0 -> StartY = bt -> PosY;
                     bt_pr0 -> SizeX = bt -> SizeX;
                     bt_pr0 -> SizeY = bt -> SizeY;
                 }
             }
         }
     }
     if(flags & aMS_MOVED)
         curMatrix -> clear_shadow_cells();
     x = iMouseX;
     y = iMouseY;
     ix = curIbs -> PosX;
     iy = curIbs -> PosY;
     isx = ix + curIbs -> SizeX;
     isy = iy + curIbs -> SizeY;
     if(x >= ix && x < isx && y >= iy && y < isy){
         id = aciGetScreenItem(x,y);
         if(id != -1){
             p = get_item(id);
             if(iP){
                 if(p){
                     iP -> free_list();
                     iP -> add_item(p->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
                     iP -> add_items(p -> numComments,p -> comments);
                     iP -> set_redraw();
                 }
                 else {
                     XBuf = new XBuffer;
                     *XBuf < "Undefined item, ID = " <= id;
                     ptr = XBuf -> address();
                     iP -> free_list();
                     iP -> add_item(ptr,-1,aciCurColorScheme[FM_SELECT_COL]);
                     iP -> set_redraw();
                     delete XBuf;
                 }
             }
         }
         if(id == -1){
             if(aciGetScreenMechos(x,y)){
                 if(iP -> items -> Size){
                     iP -> free_list();
                     iP -> set_redraw();
                 }
                 if(curMatrix && curMatrix -> mech_name)
                     iP -> add_item(curMatrix -> mech_name,-1,aciCurColorScheme[FM_SELECT_COL]);
             }
             else {
                 if(iP -> items -> Size){
                     iP -> free_list();
                     iP -> set_redraw();
                 }
             }
         }
     }
     else {
         if(curMatrix && curMatrix -> check_xy(iMouseX,iMouseY)){
             if(flags & AS_INV_MOVE_ITEM){
                 x = iMouseX - curMatrix -> ScreenX - (curItem -> ShapeSizeX >> 1) + curItem -> ShapeCenterX;
                 y = iMouseY - curMatrix -> ScreenY - (curItem -> ShapeSizeY >> 1) + curItem -> ShapeCenterY;
                 y /= aCellSize - (aCellSize >> 2);
                 if(y & 0x01) x -= (aCellSize >> 1);
                 x /= aCellSize;
             }
             else {
                 x = iMouseX - curMatrix -> ScreenX;
                 y = iMouseY - curMatrix -> ScreenY;
                 y /= aCellSize - (aCellSize >> 2);
                 if(y & 0x01) x -= (aCellSize >> 1);
                 x /= aCellSize;
             }
             if(x >= 0 && x < curMatrix -> SizeX && y >= 0 && y < curMatrix -> SizeY){
                 if(flags & AS_INV_MOVE_ITEM){
                     if(curMatrix -> check_fit(x,y,curItem)){
                         curMatrix -> put_item_shadow(x,y,curItem);
                     }
                     else {
                         p = curMatrix -> get_area_item(x,y,curItem);
                         if(p){
                             curMatrix -> remove_item(p,1);
                             if(curMatrix -> check_fit(x,y,curItem))
                                 curMatrix -> put_item_shadow(x,y,curItem);
                             curMatrix -> put_item(p -> MatrixX,p -> MatrixY,p,1);
                         }
                     }
                 }
                 else {
                     if(iP){
                         p = curMatrix -> get_item(x,y);
                         if(p){
                             if(iP -> items -> Size){
                                 iP -> free_list();
                                 iP -> set_redraw();
                             }
                             iP -> add_item(p->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
                             iP -> add_items(p -> numComments,p -> comments);
                             if(p -> pTemplate)
                                 iP -> add_item(aciGetItemLoad(p,0));
                             if(p -> promptData && XGR_MouseObj.promptData){
                                 if(!pr){
                                     pr = new XGR_MousePromptData;
                                     pr -> ID = ACI_ITEM_PROMPT;
                                     XGR_MouseObj.promptData -> AddElement((XListElement*)pr);
                                 }
                                 pr -> set_text(p -> promptData);
                                 curMatrix -> get_item_coords(p,pr -> StartX,pr -> StartY,pr -> SizeX,pr -> SizeY);
                             }
                         }
                         else {
                             if(!(flags & AS_INV_MOVE_ITEM)){
                                 if(iP -> items -> Size){
                                     iP -> free_list();
                                     iP -> set_redraw();
                                 }
                             }
                         }
                     }
                 }
             }
         }
         else {
             if(!(flags & AS_INV_MOVE_ITEM)){
                 if(iP){
                     if(iP -> items -> Size){
                         iP -> free_list();
                         iP -> set_redraw();
                     }
                 }
             }
         }
     }
     if(flags & aMS_MOVED){
         if(curMode == AS_INV_MODE && curMatrix && curMatrix -> check_redraw()){
             curMatrix -> flags |= IM_REDRAW_SHADOW;
         }
     }
 }
References aCellSize, ACI_ITEM_PROMPT, ACI_ITM_PICKUP_BUTTON, ACI_PICKUP_ITM_OFF, ACI_PICKUP_ITM_ON, ACI_PICKUP_WPN_OFF, ACI_PICKUP_WPN_ON, ACI_WPN_PICKUP_BUTTON, aciCurColorScheme, aciGetItemLoad(), aciGetScreenItem(), aciGetScreenMechos(), aciSTR_PICKUP_ITEMS_OFF, aciSTR_PICKUP_WEAPONS_OFF, add_item(), aMS_MOVED, AS_INV_MODE, AS_INV_MOVE_ITEM, B_PRESSED, curIbs, curItem, curMatrix, curMode, flags, FM_SELECT_COL, get_button(), get_item(), iListElement::ID_ptr, IM_REDRAW_SHADOW, iMouseX, iMouseY, iP, NULL, XGR_Mouse::promptData, put_item(), remove_item(), and XGR_MouseObj.
Referenced by KeyQuant().
inv_mouse_quant_l()
void actIntDispatcher::inv_mouse_quant_l (void)
 {
     int x,y,index;
     int mx = iMouseX;
     int my = iMouseY;
     if(flags & AS_ISCREEN) mx += iScreenOffs - 800;
     if(curMatrix && curMatrix -> check_xy(mx,my)){
         if(flags & AS_INV_MOVE_ITEM){
             x = iMouseX - curMatrix -> ScreenX - (curItem -> ShapeSizeX >> 1) + curItem -> ShapeCenterX;
             y = iMouseY - curMatrix -> ScreenY - (curItem -> ShapeSizeY >> 1) + curItem -> ShapeCenterY;
             if(flags & AS_ISCREEN)
                 x += iScreenOffs - 800;
             y /= aCellSize - (aCellSize >> 2);
             if(y & 0x01) x -= (aCellSize >> 1);
             x /= aCellSize;
         }
         else {
             x = iMouseX - curMatrix -> ScreenX;
             y = iMouseY - curMatrix -> ScreenY;
             if(flags & AS_ISCREEN)
                 x += iScreenOffs - 800;
             y /= aCellSize - (aCellSize >> 2);
             if(y & 0x01) x -= (aCellSize >> 1);
             x /= aCellSize;
         }
         index = x + y * curMatrix -> SizeX;
         if(x >= 0 && x < curMatrix -> SizeX && y >= 0 && y < curMatrix -> SizeY){
             if(flags & AS_INV_MOVE_ITEM){
                 if(curMatrix -> check_fit(x,y,curItem)){
                     if(flags & AS_ISCREEN && curItem -> flags & INV_ITEM_NO_PAY){
                         if(!aciCheckItemCredits()) return;
                         aciPay4Item(curItem);
                     }
                     put_item_xy(curItem,x,y);
                     SOUND_DROP();
                 }
                 else {
                     change_items(x,y);
                     SOUND_PICK();
                 }
             }
             else {
                 if(curMatrix -> matrix[index] -> flags & AS_BUSY_CELL){
                     set_move_item(index);
                     SOUND_PICK();
                 }
             }
         }
     }
     else {
         if(!(flags & AS_ISCREEN)){
             if(flags & AS_INV_MOVE_ITEM){
                 aciSendEvent2itmdsp(ACI_DROP_ITEM,curItem -> item_ptr);
                 restore_mouse_cursor();
                 if(curItem -> menu){
                     remove_menu_item((fncMenu*)curItem -> menu);
                 }
                 free_item(curItem);
                 flags &= ~AS_INV_MOVE_ITEM;
             }
         }
         else {
             if(secondMatrix && secondMatrix -> check_xy(mx,my)){
                 if(flags & AS_INV_MOVE_ITEM){
                     x = iMouseX - secondMatrix -> ScreenX - (curItem -> ShapeSizeX >> 1) + curItem -> ShapeCenterX;
                     y = iMouseY - secondMatrix -> ScreenY - (curItem -> ShapeSizeY >> 1) + curItem -> ShapeCenterY;
                     x += iScreenOffs - 800;
                     y /= aCellSize - (aCellSize >> 2);
                     if(y & 0x01) x -= (aCellSize >> 1);
                     x /= aCellSize;
                 }
                 else {
                     x = iMouseX - secondMatrix -> ScreenX;
                     y = iMouseY - secondMatrix -> ScreenY;
                     x += iScreenOffs - 800;
                     y /= aCellSize - (aCellSize >> 2);
                     if(y & 0x01) x -= (aCellSize >> 1);
                     x /= aCellSize;
                 }
                 index = x + y * secondMatrix -> SizeX;
                 if(x >= 0 && x < secondMatrix -> SizeX && y >= 0 && y < secondMatrix -> SizeY){
                     if(flags & AS_INV_MOVE_ITEM){
                         if(secondMatrix -> check_fit(x,y,curItem)){
                             put_item_xy(curItem,x,y,1);
                             SOUND_DROP();
                         }
                         else {
                             change_items(x,y,1);
                             SOUND_PICK();
                         }
                     }
                     else {
                         if(secondMatrix -> matrix[index] -> flags & AS_BUSY_CELL){
                             set_move_item(index,1);
                             SOUND_PICK();
                         }
                     }
                 }
             }
         }
     }
 }
References aCellSize, ACI_DROP_ITEM, aciCheckItemCredits(), aciPay4Item(), aciSendEvent2itmdsp(), AS_BUSY_CELL, AS_INV_MOVE_ITEM, AS_ISCREEN, change_items(), curItem, curMatrix, flags, free_item(), iMouseX, iMouseY, INV_ITEM_NO_PAY, iScreenOffs, put_item_xy(), remove_menu_item(), restore_mouse_cursor(), secondMatrix, set_move_item(), SOUND_DROP, and SOUND_PICK.
Referenced by iKeyQuant(), and KeyQuant().
inv_mouse_quant_r()
void actIntDispatcher::inv_mouse_quant_r (void)
 {
     int x,y,index;
     invItem* p = NULL;
     int mx = iMouseX;
     int my = iMouseY;
     if(flags & AS_ISCREEN) mx += iScreenOffs - 800;
     if(curMatrix && curMatrix -> check_xy(mx,my)){
         if(flags & AS_INV_MOVE_ITEM){
             x = iMouseX - curMatrix -> ScreenX - (curItem -> ShapeSizeX >> 1) + curItem -> ShapeCenterX;
             y = iMouseY - curMatrix -> ScreenY - (curItem -> ShapeSizeY >> 1) + curItem -> ShapeCenterY;
             if(flags & AS_ISCREEN)
                 x += iScreenOffs - 800;
             y /= aCellSize - (aCellSize >> 2);
             if(y & 0x01) x -= (aCellSize >> 1);
             x /= aCellSize;
         }
         else {
             x = iMouseX - curMatrix -> ScreenX;
             y = iMouseY - curMatrix -> ScreenY;
             if(flags & AS_ISCREEN)
                 x += iScreenOffs - 800;
             y /= aCellSize - (aCellSize >> 2);
             if(y & 0x01) x -= (aCellSize >> 1);
             x /= aCellSize;
         }
         index = x + y * curMatrix -> SizeX;
         if(x >= 0 && x < curMatrix -> SizeX && y >= 0 && y < curMatrix -> SizeY){
             if(flags & AS_INV_MOVE_ITEM){
                 if(curMatrix -> check_fit(x,y,curItem)){
                     if(flags & AS_ISCREEN && curItem -> flags & INV_ITEM_NO_PAY){
                         if(!aciCheckItemCredits()) return;
                         aciPay4Item(curItem);
                     }
                     put_item_xy(curItem,x,y);
                     SOUND_DROP();
                 }
             }
             else {
                 if(!(flags & AS_ISCREEN)){
                     if(curMatrix -> matrix[index] -> flags & AS_BUSY_CELL){
                         p = curMatrix -> matrix[index] -> item;
                         if(p -> EvCode){
                             send_event(p -> EvCode,0,p -> item_ptr);
                             SOUND_DROP();
                         }
                     }
                 }
             }
         }
     }
     else {
         if(!(flags & AS_ISCREEN)){
             if(flags & AS_INV_MOVE_ITEM){
                 aciSendEvent2itmdsp(ACI_DROP_ITEM,curItem -> item_ptr);
                 restore_mouse_cursor();
                 if(curItem -> menu){
                     remove_menu_item((fncMenu*)curItem -> menu);
                 }
                 free_item(curItem);
                 flags &= ~AS_INV_MOVE_ITEM;
             }
         }
         else {
             if(secondMatrix){
                 if(flags & AS_INV_MOVE_ITEM){
                     x = iMouseX - secondMatrix -> ScreenX - (curItem -> ShapeSizeX >> 1) + curItem -> ShapeCenterX;
                     y = iMouseY - secondMatrix -> ScreenY - (curItem -> ShapeSizeY >> 1) + curItem -> ShapeCenterY;
                     x += iScreenOffs - 800;
                     y /= aCellSize - (aCellSize >> 2);
                     if(y & 0x01) x -= (aCellSize >> 1);
                     x /= aCellSize;
                 }
                 else {
                     x = iMouseX - secondMatrix -> ScreenX;
                     y = iMouseY - secondMatrix -> ScreenY;
                     x += iScreenOffs - 800;
                     y /= aCellSize - (aCellSize >> 2);
                     if(y & 0x01) x -= (aCellSize >> 1);
                     x /= aCellSize;
                 }
                 index = x + y * secondMatrix -> SizeX;
                 if(x >= 0 && x < secondMatrix -> SizeX && y >= 0 && y < secondMatrix -> SizeY){
                     if(flags & AS_INV_MOVE_ITEM){
                         if(secondMatrix -> check_fit(x,y,curItem)){
                             put_item_xy(curItem,x,y,1);
                         }
                         SOUND_DROP();
                     }
                     else {
                         if(secondMatrix -> matrix[index] -> flags & AS_BUSY_CELL){
                             p = secondMatrix -> matrix[index] -> item;
                         }
                     }
                 }
             }
         }
     }
 }
References aCellSize, ACI_DROP_ITEM, aciCheckItemCredits(), aciPay4Item(), aciSendEvent2itmdsp(), AS_BUSY_CELL, AS_INV_MOVE_ITEM, AS_ISCREEN, curItem, curMatrix, flags, free_item(), iMouseX, iMouseY, INV_ITEM_NO_PAY, iScreenOffs, NULL, put_item_xy(), remove_menu_item(), restore_mouse_cursor(), secondMatrix, send_event(), and SOUND_DROP.
Referenced by iKeyQuant(), and KeyQuant().
KeyQuant()
void actIntDispatcher::KeyQuant (void)
 {
     int k;
     aButton* bt;
     fncMenu* m;
     aciBitmapMenu* bm;
 #ifdef _DEBUG
     int i;
     invMatrix* temp;
     invItem* temp_item;
     XBuffer* shotBufBMP;
     XBuffer* shotBufPAL;
 #endif
     if(aciKeyboardLocked && !(flags & AS_CHAT_MODE)) return;
     if(flags & AS_LOCKED){
         if(flags & AS_CHAT_MODE){
             while(KeyBuf -> size) iChatKeyQuant(KeyBuf -> get());
             if(flags & aMS_LEFT_PRESS || flags & aMS_RIGHT_PRESS){
                 iChatMouseQuant(XGR_MouseObj.PosX + XGR_MouseObj.SpotX,XGR_MouseObj.PosY + XGR_MouseObj.SpotY,1);
             }
         }
         flags &= ~aMS_PRESS;
         KeyBuf -> clear();
         return;
     }
     if(flags & AS_FULLSCR)
         flags &= ~aMS_PRESS;
     inv_mouse_move_quant();
     if(flags & aMS_MOVED){
         flags &= ~aMS_MOVED;
         if(curMode == AS_INFO_MODE){
             m = (fncMenu*)menuList -> last;
             while(m){
                 if(!(m -> flags & FM_HIDDEN) && m -> check_xy(iMouseX,iMouseY)){
                     if(m -> flags & FM_ACTIVE){
                         m -> change(iMouseX,iMouseY,1);
                     }
                 }
                 m = (fncMenu*)m -> prev;
             }
         }
     }
     if(flags & aMS_PRESS){
         if(flags & aMS_LEFT_PRESS){
             flags &= ~aMS_LEFT_PRESS;
             if(!(flags & AS_INV_MOVE_ITEM)){
                 bt = (aButton*)intButtons -> last;
                 while(bt){
                     if(!(bt -> flags & B_ACTIVE)){
                         if(bt -> check_xy(iMouseX,iMouseY)){
                             bt -> press();
                             SOUND_SELECT();
                             send_event(bt -> eventCode,bt -> eventData);
                         }
                     }
                     bt = (aButton*)bt -> prev;
                 }
             }
             switch(curMode){
                 case AS_INV_MODE:
                     if(!(flags & AS_INV_MOVE_ITEM)){
                         bt = (aButton*)invButtons -> last;
                         while(bt){
                             if(!(bt -> flags & B_ACTIVE)){
                                 if(bt -> check_xy(iMouseX,iMouseY)){
                                     bt -> press();
                                     SOUND_SELECT();
                                     send_event(bt -> eventCode,bt -> eventData);
                                 }
                             }
                             bt = (aButton*)bt -> prev;
                         }
                     }
                     inv_mouse_quant_l();
                     break;
                 case AS_INFO_MODE:
                     bt = (aButton*)infButtons -> last;
                     while(bt){
                         if(!(bt -> flags & B_ACTIVE)){
                             if(bt -> check_xy(iMouseX,iMouseY)){
                                 bt -> press();
                                 SOUND_SELECT();
                                 send_event(bt -> eventCode,bt -> eventData);
                             }
                         }
                         bt = (aButton*)bt -> prev;
                     }
                     m = (fncMenu*)menuList -> last;
                     while(m){
                         if(!(m -> flags & FM_HIDDEN) && !(m -> flags & FM_LOCK) && m -> check_xy(iMouseX,iMouseY)){
                             if(m -> flags & FM_ACTIVE){
                                 if(m -> change(iMouseX,iMouseY)){
                                     init_menus();
                                     if(!(m -> flags & FM_SUBMENU)){
                                         init_submenu(m);
                                         m -> curCount = m -> activeCount;
                                     }
                                     SOUND_SELECT();
                                 }
                             }
                             else {
                                 if(m -> curFunction == FMENU_CAMERAS){
                                     bm = get_bmenu(BMENU_CAMERAS_MENU);
                                     if(!bm) return;
                                     bm -> change(iMouseX - m -> PosX,iMouseY - m -> PosY);
                                 }
                                 else {
                                     if(!m -> trigger && !(m -> flags & FM_SUBMENU)){
                                         if(!(m -> flags & FM_LOCK)){
                                             m -> flags |= FM_ACTIVE;
                                             m -> curCount = m -> activeCount;
                                             m -> set_redraw();
                                             SOUND_SELECT();
                                         }
                                         else {
                                             m -> flags &= ~FM_LOCK;
                                         }
                                     }
                                 }
                             }
                         }
                         m = (fncMenu*)m -> prev;
                     }
                     break;
             }
         }
         if(flags & aMS_RIGHT_PRESS){
             flags &= ~aMS_RIGHT_PRESS;
             switch(curMode){
                 case AS_INV_MODE:
                     inv_mouse_quant_r();
                     break;
                 case AS_INFO_MODE:
                     break;
             }
         }
     }
     while(KeyBuf -> size){
         k = sdlEventToCode(KeyBuf->get());
         if(flags & AS_TEXT_MODE){
             if(iCheckKeyID(iKEY_SKIP_TEXT,k)){
                 if(!ScrTextData -> NextPage()){
                     aciTextEndFlag = 1;
                     send_event(EV_LEAVE_TEXT_MODE);
                 }
             }
         }
         if(iCheckKeyID(iKEY_FULLSCREEN,k)){
             send_event(EV_FULLSCR_CHANGE);
         }
         if(NetworkON){
             if(iCheckKeyID(iKEY_FRAG_INFO,k)){
                 aciShowFrags();
             }
             if(iCheckKeyID(iKEY_CHAT,k)){
                 send_event(EV_ENTER_CHAT);
             }
         }
         if(!(flags & AS_FULLSCR)){
             if(iCheckKeyID(iKEY_REDUCE_VIEW,k)){
                 if(curMode != AS_INV_MODE){
                     send_event(EV_CHANGE_SCREEN,1);
                 }
             }
             if(iCheckKeyID(iKEY_ENLARGE_VIEW,k)){
                 if(curMode != AS_INV_MODE){
                     send_event(EV_CHANGE_SCREEN,3);
                 }
             }
         }
         else {
             if(iCheckKeyID(iKEY_INVENTORY,k)){
                 if(curMode != AS_INV_MODE)
                     send_event(EV_SET_MODE,AS_INV_MODE);
                 send_event(EV_FULLSCR_CHANGE);
             }
         }
         if(!NetworkON)
             aciCHandler(k);
         if(!(flags & AS_FULLSCR)){
             bt = (aButton*)intButtons -> last;
             while(bt){
                 if(!(bt -> flags & B_ACTIVE)){
                     if(bt -> scankey -> check(k)){
                         bt -> press();
                         SOUND_SELECT();
                         send_event(bt -> eventCode,bt -> eventData);
                     }
                 }
                 bt = (aButton*)bt -> prev;
             }
             switch(curMode){
                 case AS_INV_MODE:
                     bt = (aButton*)invButtons -> last;
                     while(bt){
                         if(!(bt -> flags & B_ACTIVE)){
                             if(bt -> scankey -> check(k)){
                                 bt -> press();
                                 SOUND_SELECT();
                                 send_event(bt -> eventCode,bt -> eventData);
                             }
                         }
                         bt = (aButton*)bt -> prev;
                     }
                     break;
                 case AS_INFO_MODE:
                     bt = (aButton*)infButtons -> last;
                     while(bt){
                         if(!(bt -> flags & B_ACTIVE)){
                             if(bt -> scankey -> check(k)){
                                 bt -> press();
                                 SOUND_SELECT();
                                 send_event(bt -> eventCode,bt -> eventData);
                             }
                         }
                         bt = (aButton*)bt -> prev;
                     }
                     m = (fncMenu*)menuList -> last;
                     while(m){
                         if(m -> flags & FM_ACTIVE && m -> up_key -> check(k)){
                             m -> step_up();
                             m -> set_redraw();
                             SOUND_SELECT();
                         }
                         if(m -> flags & FM_ACTIVE && m -> down_key -> check(k)){
                             m -> step_down();
                             m -> set_redraw();
                             SOUND_SELECT();
                         }
                         m = (fncMenu*)m -> prev;
                     }
                     break;
             }
         }
     }
     m = (fncMenu*)menuList -> last;
     while(m){
         m -> flags &= ~FM_LOCK;
         m = (fncMenu*)m -> prev;
     }
 }
References aciCHandler(), aciKeyboardLocked, aciShowFrags(), aciTextEndFlag, aMS_LEFT_PRESS, aMS_MOVED, aMS_PRESS, aMS_RIGHT_PRESS, AS_CHAT_MODE, AS_FULLSCR, AS_INFO_MODE, AS_INV_MODE, AS_INV_MOVE_ITEM, AS_LOCKED, AS_TEXT_MODE, B_ACTIVE, BMENU_CAMERAS_MENU, curMode, EV_CHANGE_SCREEN, EV_ENTER_CHAT, EV_FULLSCR_CHANGE, EV_LEAVE_TEXT_MODE, EV_SET_MODE, flags, FM_ACTIVE, FM_HIDDEN, FM_LOCK, FM_SUBMENU, FMENU_CAMERAS, KeyBuffer::get(), get_bmenu(), iChatKeyQuant(), iChatMouseQuant(), iCheckKeyID(), iKEY_CHAT, iKEY_ENLARGE_VIEW, iKEY_FRAG_INFO, iKEY_FULLSCREEN, iKEY_INVENTORY, iKEY_REDUCE_VIEW, iKEY_SKIP_TEXT, iMouseX, iMouseY, infButtons, init_menus(), init_submenu(), intButtons, inv_mouse_move_quant(), inv_mouse_quant_l(), inv_mouse_quant_r(), invButtons, KeyBuf, menuList, NetworkON, XGR_Mouse::PosX, XGR_Mouse::PosY, prev, ScrTextData, sdlEventToCode(), send_event(), SOUND_SELECT, XGR_Mouse::SpotX, XGR_Mouse::SpotY, and XGR_MouseObj.
load_data()
void actIntDispatcher::load_data (XStream * fh)
 {
     int i,n,x,y,d,itm_size,ver,cr;
     *fh > ver;
     if(ver < 0 || ver > aciSaveVersion) ErrH.Abort("Bad save version...");
     aciWorldInfo* w;
     invItem* p,*p1;
     invMatrix* m;
     if(curMatrix)
         free_matrix(curMatrix);
     *fh > n > itm_size;
     if(n != -1){
         curMatrix = alloc_matrix(n);
         if(flags & AS_ISCREEN)
             m = get_imatrix(n);
         else
             m = get_matrix(n);
         m -> clone(curMatrix);
         for(i = 0; i < itm_size; i ++){
             *fh > n > x > y > d;
             if(flags & AS_ISCREEN)
                 p = get_iitem(n);
             else
                 p = get_item(n);
             p1 = alloc_item();
             p -> clone(p1);
             curMatrix -> put_item(x,y,p1,1);
             p1 -> dropCount = d;
         }
     }
     else {
         curMatrix = NULL;
     }
     *fh > cr;
     aciUpdateCurCredits(cr);
     if(wMap){
         w = (aciWorldInfo*)wMap -> world_list -> last;
         while(w){
             *fh > w -> flags;
             w = (aciWorldInfo*)w -> prev;
         }
         w = (aciWorldInfo*)wMap -> world_list -> last;
         while(w){
             fh -> read(w -> links,AS_MAX_WORLD);
             w = (aciWorldInfo*)w -> prev;
         }
     }
 }
References XErrorHandler::Abort(), aciSaveVersion, aciUpdateCurCredits(), alloc_item(), alloc_matrix(), AS_ISCREEN, AS_MAX_WORLD, curMatrix, ErrH, flags, free_matrix(), get_iitem(), get_imatrix(), get_item(), get_matrix(), NULL, prev, put_item(), and wMap.
Referenced by acsLoadData().
load_ibs()
void actIntDispatcher::load_ibs (void)
 {
     if(!curIbs)
         ErrH.Abort("curIBS object not present");
     curIbsID = curIbs -> ID;
     curIbs -> load();
     init_inds();
 }
References XErrorHandler::Abort(), curIbs, curIbsID, ErrH, and init_inds().
Referenced by change_ibs(), and init().
lock()
void actIntDispatcher::lock (void) inline
 { flags |= AS_LOCKED; }
References AS_LOCKED, and flags.
Referenced by EventQuant().
next_ibs()
void actIntDispatcher::next_ibs (void)
 {
     if(curIbs){
         curIbs -> free();
         if(curIbs -> back) curIbs -> back -> free();
     }
     curIbs = (ibsObject*)curIbs -> next;
     if(!curIbs) ErrH.Abort("IBS object not present");
     load_ibs();
 }
References curIbs.
pal_flush()
void actIntDispatcher::pal_flush ()
{
     if(flags & AS_EVINCE_PALETTE){
         i_evince_pal(actIntPal,16);
         PalIterLock = 0;
         flags ^= AS_EVINCE_PALETTE;
     }
 }
References actIntPal, AS_EVINCE_PALETTE, flags, i_evince_pal(), and PalIterLock.
prepare_menus()
void actIntDispatcher::prepare_menus (void)
 {
     invItem* p;
     if(!curMatrix) return;
     p = (invItem*)curMatrix -> items -> last;
     while(p){
         if(p -> menu)
             add_menu_item((fncMenu*)p -> menu);
         p = (invItem*)p -> prev;
     }
 }
References add_menu_item(), curMatrix, and prev.
Referenced by i_finit().
put_in_slot()
void actIntDispatcher::put_in_slot (actintItemData * d)
 {
     int x,y,index = 0,px,py,id;
     int ms_flag = 0;
     invItem* dvc;
     invItem* p = (invItem*)d -> actintOwner;
     //std::cout<<"actIntDispatcher::put_in_slot "<<p->fname<<std::endl;
     if(flags & AS_INV_MOVE_ITEM && curItem == p){
         ms_flag = 1;
     }
     else {
         id = curMatrix -> get_item_slot(p);
         if(id == AS_DEVICE_SLOT) return;
     }
     for(y = 0; y < curMatrix -> SizeY; y ++){
         for(x = 0; x < curMatrix -> SizeX; x ++){
             if(curMatrix -> matrix[index] -> slotType == AS_DEVICE_SLOT){
                 if(curMatrix -> check_fit(x,y,p)){
                     if(!ms_flag){
                         curMatrix -> remove_item(p);
                     }
                     else {
                         flags ^= AS_INV_MOVE_ITEM;
                         restore_mouse_cursor();
                         curMatrix -> clear_shadow_cells();
                         curItem = NULL;
                         if(iP){
                             iP -> free_list();
                             iP -> set_redraw();
                         }
                     }
                     curMatrix -> put_item(x,y,p);
                     SOUND_DROP();
                     id = curMatrix -> get_item_slot(p);
                     aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,d,id);
                     if(curMode == AS_INV_MODE)
                         curMatrix -> set_redraw();
                     return;
                 }
                 else {
                     dvc = curMatrix -> get_area_item(x,y,p);
                     if(dvc){
                         curMatrix -> remove_item(dvc);
                         if(!curMatrix -> check_fit(x,y,p)){
                             curMatrix -> put_item(dvc -> MatrixX,dvc -> MatrixY,dvc);
                             return;
                         }
                         if(!curMatrix -> check_fit(x,y,p)) ErrH.Abort("put_in_slot() failed...");
                         if(!ms_flag){
                             px = p -> MatrixX;
                             py = p -> MatrixY;
                             curMatrix -> remove_item(p);
                             curMatrix -> put_item(dvc -> MatrixX,dvc -> MatrixY,p);
                             curMatrix -> put_item(px,py,dvc);
                             SOUND_DROP();
                         }
                         else {
                             curMatrix -> put_item(dvc -> MatrixX,dvc -> MatrixY,p);
                             SOUND_DROP();
                             curItem = dvc;
                             if(iP){
                                 iP -> free_list();
                                 iP -> add_item(curItem->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
                                 iP -> add_items(curItem -> numComments,curItem -> comments);
                                 if(curItem -> pTemplate)
                                     iP -> add_item(aciGetItemLoad(curItem,0));
                                 iP -> set_redraw();
                             }
                             set_mouse_cursor(dvc -> frame,dvc -> ScreenSizeX,dvc -> ScreenSizeY);
                         }
                         aciSendEvent2itmdsp(ACI_DEACTIVATE_ITEM,dvc -> item_ptr);
                         id = curMatrix -> get_item_slot(p);
                         aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,d,id);
                         if(curMode == AS_INV_MODE)
                             curMatrix -> set_redraw();
                         return;
                     }
                 }
             }
             index ++;
         }
     }
 }
References XErrorHandler::Abort(), ACI_ACTIVATE_ITEM, ACI_DEACTIVATE_ITEM, aciCurColorScheme, aciGetItemLoad(), aciSendEvent2itmdsp(), add_item(), AS_DEVICE_SLOT, AS_INV_MODE, AS_INV_MOVE_ITEM, curItem, curMatrix, curMode, ErrH, flags, FM_SELECT_COL, frame, iListElement::ID_ptr, iP, NULL, put_item(), remove_item(), restore_mouse_cursor(), set_mouse_cursor(), and SOUND_DROP.
Referenced by EventQuant().
put_item()
int actIntDispatcher::put_item (actintItemData * d)
 {
     int id = d -> type;
     invItem* p = get_item(id),*p1;
     if(!p){
         std::cout<<"actIntDispatcher::put_item Item data not present... "<<XERR_USER<<" id:"<<id<<std::endl;
     }
     p1 = alloc_item();
     p -> clone(p1);
     if(!curMatrix -> auto_put_item(p1)){
         aciSendEvent2itmdsp(ACI_DROP_ITEM,d);
         free_item(p1);
         std::cout<<"actIntDispatcher::put_item !curMatrix -> auto_put_item(p1) id:"<<id<<std::endl;
         return 0;
     }
     p1 -> item_ptr = d;
     d -> actintOwner = p1;
     if(!(flags & AS_ISCREEN)){
         if(p1 -> slotType != -1){
             id = curMatrix -> get_item_slot(p1);
             if(id != -1)
                 aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,d,id);
             else
                 aciSendEvent2itmdsp(ACI_DEACTIVATE_ITEM,d);
         }
         if(p1 -> menu){
             add_menu_item((fncMenu*)p1 -> menu);
         }
     }
     if(curMode == AS_INV_MODE)
         curMatrix -> set_redraw();
     return 1;
 }
References ACI_ACTIVATE_ITEM, ACI_DEACTIVATE_ITEM, ACI_DROP_ITEM, aciSendEvent2itmdsp(), add_menu_item(), alloc_item(), AS_INV_MODE, AS_ISCREEN, curMatrix, curMode, flags, free_item(), get_item(), and XERR_USER.
Referenced by change_items(), EventQuant(), inv_mouse_imove_quant(), inv_mouse_move_quant(), load_data(), put_in_slot(), put_item_xy(), and trade_items().
put_item_auto()
int actIntDispatcher::put_item_auto (invItem * p)
 {
     if(!curMatrix -> auto_put_item(p1)){
         return 0;
     }
     p1 -> item_ptr = NULL;
     if(!(flags & AS_ISCREEN)){
         if(p1 -> menu){
             add_menu_item((fncMenu*)p1 -> menu);
         }
     }
     else {
         if(p1 -> uvsDataPtr){
             ((uvsActInt*)p1 -> uvsDataPtr) -> pos_x = p1 -> MatrixX;
             ((uvsActInt*)p1 -> uvsDataPtr) -> pos_y = p1 -> MatrixY;
         }
     }
     if(curMode == AS_INV_MODE)
         curMatrix -> set_redraw();
     return 1;
 }
References add_menu_item(), AS_INV_MODE, AS_ISCREEN, curMatrix, curMode, flags, and NULL.
put_item_xy()
int actIntDispatcher::put_item_xy (invItem * p, int x, int y, int sflag = 0)
 {
     int id = 0;
     actintItemData* d;
     invMatrix* m = (sflag) ? secondMatrix : curMatrix;
     if(m -> check_fit(x,y,p)){
         m -> put_item(x,y,p);
         m -> clear_shadow_cells();
         m -> set_redraw();
         if(flags & AS_INV_MOVE_ITEM)
             restore_mouse_cursor();
         flags &= ~AS_INV_MOVE_ITEM;
         if(p -> item_ptr && p -> slotType != -1){
             id = m -> get_item_slot(p);
             d = p -> item_ptr;
             if(!(flags & AS_ISCREEN)){
                 if(id != -1)
                     aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,d,id);
                 else
                     aciSendEvent2itmdsp(ACI_DEACTIVATE_ITEM,d);
             }
         }
         if(!(flags & AS_ISCREEN) && p -> menu){
             add_menu_item((fncMenu*)p -> menu);
         }
         if(flags & AS_ISCREEN){
             if(p -> uvsDataPtr){
                 ((uvsActInt*)p -> uvsDataPtr) -> pos_x = p -> MatrixX;
                 ((uvsActInt*)p -> uvsDataPtr) -> pos_y = p -> MatrixY;
             }
         }
         return 1;
     }
     return 0;
 }
References ACI_ACTIVATE_ITEM, ACI_DEACTIVATE_ITEM, aciSendEvent2itmdsp(), add_menu_item(), AS_INV_MOVE_ITEM, AS_ISCREEN, curMatrix, flags, put_item(), restore_mouse_cursor(), and secondMatrix.
Referenced by inv_mouse_quant_l(), and inv_mouse_quant_r().
redraw()
void actIntDispatcher::redraw (void)
 {
     fncMenu* p;
     aButton* b;
     invMatrix* m;
     CounterPanel* cp;
     InfoPanel* iPl;
     if(flags & AS_FULLSCR)
         return;
     aci_tmp ++;
     if(aci_tmp > 64) aci_tmp = 0;
     iPl = (InfoPanel*)infoPanels -> last;
     while(iPl){
         if(!(iPl -> flags & IP_NO_REDRAW)){
             if(iPl -> interf_type == INT_PANEL){
                 iPl -> set_redraw();
             }
             else {
                 switch(curMode){
                     case AS_INFO_MODE:
                         if(iPl -> interf_type == INF_PANEL){
                             iPl -> set_redraw();
                         }
                         break;
                     case AS_INV_MODE:
                         if(iPl -> interf_type == INV_PANEL){
                             iPl -> set_redraw();
                         }
                         break;
                 }
             }
         }
         iPl = (InfoPanel*)iPl -> prev;
     }
     if(curMode == AS_INFO_MODE){
         p = (fncMenu*)menuList -> last;
         while(p){
             if(!(p -> flags & FM_ACTIVE) && p -> curFunction && !(p -> flags & FM_SUBMENU) && !(p -> flags & FM_HIDDEN))
                 p -> set_redraw();
             if((p -> flags & FM_ACTIVE) && !p -> trigger){
                 p -> curCount --;
                 if(p -> curCount <= 0){
                     if(!(p -> flags & FM_SUBMENU)){
                         p -> flags &= ~FM_ACTIVE;
                         p -> set_redraw();
                         init_menus();
                         init_submenu(p);
                         p -> curCount = p -> activeCount;
                         SOUND_SELECT();
                     }
                     else {
                         if(p -> activeCount)
                             p -> go2upmenu();
                     }
                 }
             }
             p = (fncMenu*)p -> prev;
         }
     }
     cp = (CounterPanel*)intCounters -> last;
     while(cp){
         if(*cp -> value_ptr != cp -> last_value)
             cp -> set_redraw();
         cp = (CounterPanel*)cp -> prev;
     }
     switch(curMode){
         case AS_INFO_MODE:
             cp = (CounterPanel*)infCounters -> last;
             while(cp){
                 if(*cp -> value_ptr != cp -> last_value)
                     cp -> set_redraw();
                 cp = (CounterPanel*)cp -> prev;
             }
             break;
         case AS_INV_MODE:
             cp = (CounterPanel*)invCounters -> last;
             while(cp){
                 if(*cp -> value_ptr != cp -> last_value)
                     cp -> set_redraw();
                 cp = (CounterPanel*)cp -> prev;
             }
             break;
     }
     if(!(flags & AS_FULL_REDRAW)){
         XGR_MouseObj.flags &= ~XGM_PROMPT_ACTIVE;
         curIbs -> back -> load2mem(XGR_VIDEOBUF);
         if(curMode == AS_INV_MODE && curMatrix && curMatrix -> back){
             curMatrix -> back -> load();
             XGR_PutSpr(curMatrix -> back -> OffsX,curMatrix -> back -> OffsY,curMatrix -> back -> SizeX,curMatrix -> back -> SizeY,curMatrix -> back -> frames,XGR_BLACK_FON);
             curMatrix -> back -> free();
         }
         flags |= AS_FULL_FLUSH;
         cp = (CounterPanel*)intCounters -> last;
         while(cp){
             cp -> redraw();
             cp = (CounterPanel*)cp -> prev;
         }
         b = (aButton*)intButtons -> last;
         while(b){
             b -> redraw();
             b = (aButton*)b -> prev;
         }
         switch(curMode){
             case AS_INV_MODE:
                 b = (aButton*)invButtons -> last;
                 while(b){
                     b -> redraw();
                     b = (aButton*)b -> prev;
                 }
                 if(curMatrix){
                     curMatrix -> redraw();
                 }
                 if(iP){
                     iP -> redraw();
                 }
                 cp = (CounterPanel*)invCounters -> last;
                 while(cp){
                     cp -> redraw();
                     cp = (CounterPanel*)cp -> prev;
                 }
                 break;
             case AS_INFO_MODE:
                 b = (aButton*)infButtons -> last;
                 while(b){
                     b -> redraw();
                     b = (aButton*)b -> prev;
                 }
                 p = (fncMenu*)menuList -> last;
                 while(p){
                     if(!(p -> flags & FM_SUBMENU) || (p -> flags & FM_ACTIVE))
                         p -> redraw();
                     else
                         p -> flags &= ~FM_REDRAW;
                     p = (fncMenu*)p -> prev;
                 }
                 cp = (CounterPanel*)infCounters -> last;
                 while(cp){
                     cp -> redraw();
                     cp = (CounterPanel*)cp -> prev;
                 }
                 break;
         }
         flags |= AS_FULL_REDRAW;
     }
     b = (aButton*)intButtons -> last;
     while(b){
         if(b -> flags & B_REDRAW){
             b -> redraw();
             b -> set_flush();
         }
         b = (aButton*)b -> prev;
     }
     if(curMode == AS_INV_MODE){
         b = (aButton*)invButtons -> last;
         while(b){
             if(b -> flags & B_REDRAW){
                 b -> redraw();
                 b -> set_flush();
             }
             b = (aButton*)b -> prev;
         }
     }
     if(curMode == AS_INFO_MODE){
         b = (aButton*)infButtons -> last;
         while(b){
             if(b -> flags & B_REDRAW){
                 b -> redraw();
                 b -> set_flush();
             }
             b = (aButton*)b -> prev;
         }
     }
     if(curMode == AS_INV_MODE && curMatrix){
         m = curMatrix;
         if(m -> flags & IM_REDRAW){
             m -> redraw();
             m -> set_flush();
         }
     }
     if(curMode == AS_INFO_MODE){
         p = (fncMenu*)menuList -> last;
         while(p){
             if(p -> flags & FM_REDRAW){
                 p -> redraw();
                 p -> set_flush();
             }
             p = (fncMenu*)p -> prev;
         }
     }
     if(iP && curMode == AS_INV_MODE){
         if(iP -> flags & IP_REDRAW){
             iP -> redraw();
             iP -> set_flush();
         }
     }
     cp = (CounterPanel*)intCounters -> last;
     while(cp){
         if(cp -> flags & CP_REDRAW){
             cp -> redraw();
             cp -> set_flush();
         }
         cp = (CounterPanel*)cp -> prev;
     }
     if(curMode == AS_INFO_MODE){
         cp = (CounterPanel*)infCounters -> last;
         while(cp){
             if(cp -> flags & CP_REDRAW){
                 cp -> redraw();
                 cp -> set_flush();
             }
             cp = (CounterPanel*)cp -> prev;
         }
     }
     if(curMode == AS_INV_MODE){
         cp = (CounterPanel*)invCounters -> last;
         while(cp){
             if(cp -> flags & CP_REDRAW){
                 cp -> redraw();
                 cp -> set_flush();
             }
             cp = (CounterPanel*)cp -> prev;
         }
     }
     iPl = (InfoPanel*)infoPanels -> last;
     while(iPl){
         if(iPl -> flags & IP_REDRAW){
             iPl -> redraw();
             iPl -> set_flush();
         }
         iPl = (InfoPanel*)iPl -> prev;
     }
 }
References aci_tmp, AS_FULL_FLUSH, AS_FULL_REDRAW, AS_FULLSCR, AS_INFO_MODE, AS_INV_MODE, B_REDRAW, CP_REDRAW, curIbs, curMatrix, curMode, XGR_Mouse::flags, flags, FM_ACTIVE, FM_HIDDEN, FM_REDRAW, FM_SUBMENU, IM_REDRAW, INF_PANEL, infButtons, infCounters, infoPanels, init_menus(), init_submenu(), INT_PANEL, intButtons, intCounters, INV_PANEL, invButtons, invCounters, iP, IP_NO_REDRAW, IP_REDRAW, iPl, menuList, prev, SOUND_SELECT, XGM_PROMPT_ACTIVE, XGR_BLACK_FON, XGR_MouseObj, XGR_PutSpr, and XGR_VIDEOBUF.
Referenced by flush(), i_redraw(), and ind_redraw().
reinit_items()
void actIntDispatcher::reinit_items (void)
 {
     int id;
     invItem* p = (invItem*)curMatrix -> items -> last;
     actintItemData* d;
     while(p){
         if(p -> slotType != -1){
             id = curMatrix -> get_item_slot(p);
             d = p -> item_ptr;
             if(id != -1)
                 aciSendEvent2itmdsp(ACI_ACTIVATE_ITEM,d,id);
         }
         p = (invItem*)p -> prev;
     }
 }
References ACI_ACTIVATE_ITEM, aciSendEvent2itmdsp(), curMatrix, and prev.
remove_item()
void actIntDispatcher::remove_item (actintItemData * d)
 {
     invItem* p = (invItem*)d -> actintOwner;
     curMatrix -> remove_item(p);
     if(p -> menu){
         remove_menu_item((fncMenu*)p -> menu);
     }
     free_item(p);
     if(curMode == AS_INV_MODE)
         curMatrix -> set_redraw();
 }
References AS_INV_MODE, curMatrix, curMode, free_item(), and remove_menu_item().
Referenced by change_items(), EventQuant(), inv_mouse_imove_quant(), inv_mouse_move_quant(), put_in_slot(), set_move_item(), and trade_items().
remove_menu_item()
void actIntDispatcher::remove_menu_item (fncMenu * p)
 {
     int code = 0;
     fncMenu* m = (fncMenu*)menuList -> last;
     if(!p -> upMenuItem) return;
     code = p -> upMenuItem -> fnc_code;
     while(m){
         if(m -> flags & FM_MAIN_MENU){
             m -> remove_menu(code);
             if(curMode == AS_INFO_MODE && m -> flags & FM_ACTIVE) m -> set_redraw();
         }
         m = (fncMenu*)m -> prev;
     }
     if(p -> flags & FM_ACTIVE) p -> go2upmenu(curMode);
 }
References AS_INFO_MODE, curMode, flags, FM_ACTIVE, FM_MAIN_MENU, menuList, and prev.
Referenced by change_items(), inv_mouse_quant_l(), inv_mouse_quant_r(), and remove_item().
save_data()
void actIntDispatcher::save_data (XStream * fh)
 {
     invItem* p;
     aciWorldInfo* w;
     int cr = aciGetCurCredits();
     *fh < aciSaveVersion;
     if(curMatrix){
         *fh < curMatrix -> type < curMatrix -> items -> Size;
         p = (invItem*)curMatrix -> items -> last;
         while(p){
             *fh < p -> ID < p -> MatrixX < p -> MatrixY < p -> dropCount;
             p = (invItem*)p -> prev;
         }
     }
     else {
         *fh < (int)(-1);
     }
     *fh < cr;
     if(wMap){
         w = (aciWorldInfo*)wMap -> world_list -> last;
         while(w){
             *fh < w -> flags;
             w = (aciWorldInfo*)w -> prev;
         }
         w = (aciWorldInfo*)wMap -> world_list -> last;
         while(w){
             fh -> write(w -> links,AS_MAX_WORLD);
             w = (aciWorldInfo*)w -> prev;
         }
     }
 }
References aciGetCurCredits(), aciSaveVersion, AS_MAX_WORLD, curMatrix, flags, prev, and wMap.
send_event()
void actIntDispatcher::send_event (int cd, int dt = 0, actintItemData * p = NULL)
 {
     if(cd == EV_CHANGE_MODE || cd == EV_SET_MODE){
         if(!(flags & AS_CHANGE_MODE)){
             flags |= AS_CHANGE_MODE;
             events -> put(cd,dt,p);
         }
     }
     else
         events -> put(cd,dt,p);
 }
References AS_CHANGE_MODE, EV_CHANGE_MODE, EV_SET_MODE, events, and flags.
Referenced by EventQuant(), flush(), inv_mouse_quant_r(), and KeyQuant().
set_move_item()
void actIntDispatcher::set_move_item (int index, int sflag = 0)
 {
     invMatrix* m = (sflag) ? secondMatrix : curMatrix;
     invItem* p = m -> matrix[index] -> item;
     m -> remove_item(p);
     m -> put_item_shadow(p -> MatrixX,p -> MatrixY,p);
     m -> set_redraw();
     curItem = p;
     set_mouse_cursor(p -> frame,p -> ScreenSizeX,p -> ScreenSizeY);
     if(!(flags & AS_ISCREEN)){
         if(p -> slotType != -1)
             aciSendEvent2itmdsp(ACI_DEACTIVATE_ITEM,p -> item_ptr);
     }
     else {
         if(p -> uvsDataPtr){
             ((uvsActInt*)p -> uvsDataPtr) -> pos_x = -1;
             ((uvsActInt*)p -> uvsDataPtr) -> pos_y = -1;
             p -> MatrixX = p -> MatrixY = -1;
         }
     }
     if(iP){
         iP -> free_list();
         iP -> add_item(curItem->ID_ptr.c_str(),-1,aciCurColorScheme[FM_SELECT_COL]);
         if(!(flags & AS_ISCREEN)){
             iP -> add_items(curItem -> numComments,curItem -> comments);
             if(curItem -> pTemplate)
                 iP -> add_item(aciGetItemLoad(curItem,0));
         }
         else {
             iP -> add_items(curItem -> numComments,curItem -> comments);
             if(curItem -> pTemplate)
                 iP -> add_item(aciGetItemLoad(curItem,1));
             if(!uvsCurrentWorldUnable)
                 iP -> add_item(aciGetPrice((iListElement*)curItem,ITEMS_MODE,1));
         }
         iP -> set_redraw();
     }
     flags |= AS_INV_MOVE_ITEM;
 }
References ACI_DEACTIVATE_ITEM, aciCurColorScheme, aciGetItemLoad(), aciGetPrice(), aciSendEvent2itmdsp(), add_item(), AS_INV_MOVE_ITEM, AS_ISCREEN, curItem, curMatrix, flags, FM_SELECT_COL, frame, iListElement::ID_ptr, iP, ITEMS_MODE, remove_item(), secondMatrix, set_mouse_cursor(), and uvsCurrentWorldUnable.
Referenced by inv_mouse_quant_l().
swap_matrices()
void actIntDispatcher::swap_matrices (void)
 {
     int v;
     if(curMatrix){
         aciSell_Matrix(curMatrix);
         if(((uvsActInt*)secondMatrix -> uvsDataPtr) -> price <= 1){
             v = aciGetCurCredits();
             v -= ((uvsActInt*)curMatrix -> uvsDataPtr) -> sell_price;
             aciUpdateCurCredits(v);
         }
         secondMatrix -> ScreenX = curMatrix -> ScreenX;
         free_matrix(curMatrix);
         free_matrix(backupMatrix);
     }
     else {
         secondMatrix -> ScreenX -= 400;
     }
     curMatrix = secondMatrix;
     aciInitCurMatrixPtr();
     secondMatrix = NULL;
 }
References aciGetCurCredits(), aciInitCurMatrixPtr(), aciSell_Matrix(), aciUpdateCurCredits(), backupMatrix, curMatrix, free_matrix(), NULL, and secondMatrix.
trade_items()
void actIntDispatcher::trade_items (invMatrix * p, int imode = 0)
 {
     int cnt = 1,x,y,fl;
     invItem* it,*it1,*itm;
     it = (invItem*)curMatrix -> items -> last;
     while(it){
         it1 = (invItem*)it -> prev;
         cnt = it -> dropCount;
         x = it -> MatrixX;
         y = it -> MatrixY;
         fl = it -> flags;
         curMatrix -> remove_item(it,1);
         if(imode)
             itm = get_iitem(it -> ID);
         else
             itm = get_item(it -> ID);
         if(!itm)
             ErrH.Abort("Bad item ptr...");
         itm -> clone(it);
         if(!p -> put_item(x,y,it,1))
             ErrH.Abort("Bad trade item...");
         it -> dropCount = cnt;
         it -> flags = fl;
         it = it1;
     }
 }
References XErrorHandler::Abort(), curMatrix, ErrH, flags, get_iitem(), get_item(), prev, put_item(), and remove_item().
Referenced by i_finit(), and i_init().
unlock()
void actIntDispatcher::unlock (void) inline
 { flags &= ~AS_LOCKED; }
References AS_LOCKED, and flags.
Referenced by EventQuant().
Member Data Documentation
a_curMatrix
invMatrix* actIntDispatcher::a_curMatrix
Referenced by i_finit(), and i_init().
ascr_iP
InfoPanel* actIntDispatcher::ascr_iP
Referenced by actIntDispatcher(), i_finit(), and i_init().
b_menuList
iList* actIntDispatcher::b_menuList
Referenced by actIntDispatcher(), add_bmenu(), finit(), get_bmenu(), init(), and ~actIntDispatcher().
backList
iList* actIntDispatcher::backList
Referenced by actIntDispatcher(), get_back_bml(), and ~actIntDispatcher().
curIbs
ibsObject* actIntDispatcher::curIbs
Referenced by actIntDispatcher(), change_ibs(), EventQuant(), flush(), free_ibs(), init(), init_inds(), inv_mouse_move_quant(), load_ibs(), next_ibs(), and redraw().
curIbsID
int actIntDispatcher::curIbsID
Referenced by actIntDispatcher(), init(), and load_ibs().
curItem
invItem* actIntDispatcher::curItem
Referenced by actIntDispatcher(), cancel_matrix(), change_items(), EventQuant(), i_finit(), i_init(), init_menus(), init_submenu(), inv_mouse_imove_quant(), inv_mouse_move_quant(), inv_mouse_quant_l(), inv_mouse_quant_r(), put_in_slot(), and set_move_item().
curLocData
aciLocationInfo* actIntDispatcher::curLocData
Referenced by i_init(), and inv_mouse_imove_quant().
curMatrix
invMatrix* actIntDispatcher::curMatrix
Referenced by acsLoadData(), actIntDispatcher(), calc_load(), cancel_matrix(), change_items(), change_mode(), deactivate_items(), EventQuant(), flush(), get_item_ptr(), get_item_ptr_xy(), i_finit(), i_flush(), i_init(), i_redraw(), init(), init_inds(), inv_mouse_imove_quant(), inv_mouse_move_quant(), inv_mouse_quant_l(), inv_mouse_quant_r(), load_data(), prepare_menus(), put_in_slot(), put_item(), put_item_auto(), put_item_xy(), redraw(), reinit_items(), remove_item(), save_data(), set_move_item(), swap_matrices(), and trade_items().
curMode
int actIntDispatcher::curMode
Referenced by actIntDispatcher(), add_menu_item(), change_mode(), EventQuant(), flush(), init(), inv_mouse_move_quant(), KeyQuant(), put_in_slot(), put_item(), put_item_auto(), redraw(), remove_item(), and remove_menu_item().
curPrompt
aciPromptData* actIntDispatcher::curPrompt
Referenced by actIntDispatcher(), flush(), and ~actIntDispatcher().
curScrMode
int actIntDispatcher::curScrMode
Referenced by actIntDispatcher(), change_mode(), and EventQuant().
events
actEventHeap* actIntDispatcher::events
Referenced by actIntDispatcher(), EventQuant(), send_event(), and ~actIntDispatcher().
flags
int actIntDispatcher::flags
Referenced by acsLoadData(), actIntDispatcher(), add_menu_item(), aml_check_redraw(), calc_load(), cancel_matrix(), change_items(), change_mode(), clean_menus(), EventQuant(), flush(), i_finit(), i_flush(), i_init(), i_redraw(), iKeyQuant(), iKeyTrap(), ind_redraw(), init(), init_inds(), init_menus(), init_submenu(), inv_mouse_imove_quant(), inv_mouse_move_quant(), inv_mouse_quant_l(), inv_mouse_quant_r(), KeyQuant(), load_data(), lock(), pal_flush(), put_in_slot(), put_item(), put_item_auto(), put_item_xy(), redraw(), remove_menu_item(), save_data(), send_event(), set_move_item(), trade_items(), unlock(), and ~actIntDispatcher().
freeItemList
iList* actIntDispatcher::freeItemList
Referenced by actIntDispatcher(), and ~actIntDispatcher().
freeMatrixList
iList* actIntDispatcher::freeMatrixList
Referenced by actIntDispatcher(), and ~actIntDispatcher().
freeMenuItemList
iList* actIntDispatcher::freeMenuItemList
Referenced by actIntDispatcher(), and ~actIntDispatcher().
i_Counters
iList* actIntDispatcher::i_Counters
Referenced by actIntDispatcher(), get_icounter(), i_finit(), i_flush(), i_init(), i_redraw(), and ~actIntDispatcher().
i_curMatrix
invMatrix* actIntDispatcher::i_curMatrix
Referenced by i_init().
i_infoPanels
iList* actIntDispatcher::i_infoPanels
Referenced by actIntDispatcher(), aml_check_redraw(), get_info_panel(), i_redraw(), and ~actIntDispatcher().
i_itemList
iList* actIntDispatcher::i_itemList
Referenced by actIntDispatcher(), add_iitem(), get_iitem(), i_finit(), i_init(), and ~actIntDispatcher().
i_matrixList
iList* actIntDispatcher::i_matrixList
Referenced by actIntDispatcher(), add_imatrix(), get_imatrix(), i_init(), and ~actIntDispatcher().
i_menuList
iList* actIntDispatcher::i_menuList
Referenced by actIntDispatcher(), add_imenu(), get_imenu(), i_finit(), i_init(), i_redraw(), iKeyQuant(), iKeyTrap(), and ~actIntDispatcher().
ibsList
iList* actIntDispatcher::ibsList
Referenced by actIntDispatcher(), get_ibs(), init(), and ~actIntDispatcher().
indList
iList* actIntDispatcher::indList
Referenced by actIntDispatcher(), add_ind(), finit(), flush(), get_ind(), ind_redraw(), init(), init_inds(), init_prompt(), and ~actIntDispatcher().
infButtons
iList* actIntDispatcher::infButtons
Referenced by actIntDispatcher(), change_mode(), finit(), flush(), get_button(), init(), init_prompt(), KeyQuant(), redraw(), and ~actIntDispatcher().
infCounters
iList* actIntDispatcher::infCounters
Referenced by actIntDispatcher(), finit(), flush(), get_counter(), init(), redraw(), and ~actIntDispatcher().
InfoObj
aKeyObj* actIntDispatcher::InfoObj
Referenced by actIntDispatcher(), and ~actIntDispatcher().
infoPanels
iList* actIntDispatcher::infoPanels
Referenced by actIntDispatcher(), finit(), flush(), get_aci_info_panel(), init(), redraw(), and ~actIntDispatcher().
infPrompt
XGR_MousePromptScreen* actIntDispatcher::infPrompt
Referenced by actIntDispatcher(), change_mode(), EventQuant(), init(), init_inds(), init_prompt(), and ~actIntDispatcher().
intButtons
iList* actIntDispatcher::intButtons
Referenced by actIntDispatcher(), finit(), flush(), get_button(), init(), init_prompt(), KeyQuant(), redraw(), and ~actIntDispatcher().
intCounters
iList* actIntDispatcher::intCounters
Referenced by actIntDispatcher(), finit(), flush(), get_counter(), init(), redraw(), and ~actIntDispatcher().
invButtons
iList* actIntDispatcher::invButtons
Referenced by actIntDispatcher(), change_mode(), finit(), flush(), get_button(), init(), init_prompt(), KeyQuant(), redraw(), and ~actIntDispatcher().
invCounters
iList* actIntDispatcher::invCounters
Referenced by actIntDispatcher(), finit(), flush(), get_counter(), init(), redraw(), and ~actIntDispatcher().
InvObj
aKeyObj* actIntDispatcher::InvObj
Referenced by actIntDispatcher(), and ~actIntDispatcher().
invPrompt
XGR_MousePromptScreen* actIntDispatcher::invPrompt
Referenced by actIntDispatcher(), change_mode(), EventQuant(), init(), init_inds(), init_prompt(), and ~actIntDispatcher().
iP
InfoPanel* actIntDispatcher::iP
Referenced by actIntDispatcher(), change_items(), finit(), flush(), i_finit(), i_flush(), i_init(), i_redraw(), init(), inv_mouse_imove_quant(), inv_mouse_move_quant(), put_in_slot(), redraw(), set_move_item(), and ~actIntDispatcher().
iscr_iP
InfoPanel* actIntDispatcher::iscr_iP
Referenced by actIntDispatcher(), i_finit(), i_init(), and ~actIntDispatcher().
itemList
iList* actIntDispatcher::itemList
Referenced by actIntDispatcher(), add_item(), finit(), get_item(), init(), and ~actIntDispatcher().
locationList
iList* actIntDispatcher::locationList
Referenced by actIntDispatcher(), add_locdata(), get_locdata(), get_locdata_id(), and ~actIntDispatcher().
map_names
char** actIntDispatcher::map_names
Referenced by actIntDispatcher(), init(), and ~actIntDispatcher().
mapObj
bmlObject* actIntDispatcher::mapObj
Referenced by actIntDispatcher(), finit(), init(), and ~actIntDispatcher().
matrixList
iList* actIntDispatcher::matrixList
Referenced by actIntDispatcher(), add_matrix(), get_matrix(), init(), and ~actIntDispatcher().
menuList
iList* actIntDispatcher::menuList
Referenced by actIntDispatcher(), add_menu(), add_menu_item(), change_mode(), clean_menus(), finit(), flush(), get_menu(), i_init(), iKeyQuant(), init(), init_menus(), KeyQuant(), redraw(), remove_menu_item(), and ~actIntDispatcher().
ModeObj
aKeyObj* actIntDispatcher::ModeObj
Referenced by actIntDispatcher(), and ~actIntDispatcher().
prevScrMode
int actIntDispatcher::prevScrMode
Referenced by actIntDispatcher(), change_mode(), and EventQuant().
qMenu
fncMenuSet* actIntDispatcher::qMenu
Referenced by actIntDispatcher(), aml_check_redraw(), i_finit(), i_init(), i_redraw(), iKeyQuant(), and ~actIntDispatcher().
ScrTextData
aciScreenText* actIntDispatcher::ScrTextData
Referenced by actIntDispatcher(), EventQuant(), flush(), KeyQuant(), and ~actIntDispatcher().
secondMatrix
invMatrix* actIntDispatcher::secondMatrix
Referenced by cancel_matrix(), change_items(), EventQuant(), i_flush(), i_init(), i_redraw(), inv_mouse_imove_quant(), inv_mouse_quant_l(), inv_mouse_quant_r(), put_item_xy(), set_move_item(), and swap_matrices().
wMap
aciWorldMap* actIntDispatcher::wMap
Referenced by actIntDispatcher(), EventQuant(), init(), load_data(), save_data(), and ~actIntDispatcher().
The documentation for this struct was generated from the following files:
src/actint/actint.h
src/actint/actint.cpp