Vangers: UnitList Struct Reference
UnitList Struct Reference
#include <hobj.h>
Public Member Functions
void Init (Parser &in)
void Open (Parser &in)
void ConnectTypeList (GeneralObject *p)
void DisconnectTypeList (GeneralObject *p)
void Quant (void)
void ConnectObject (BaseObject *p)
void Add2Next (GeneralObject *p, GeneralObject *t)
void Add2Prev (GeneralObject *p, GeneralObject *t)
GeneralObject * GetNetObject (int id)
virtual void NetEvent (int type, int id)
GeneralObject * GetObject (int type)
void ClearNet (void)
Public Attributes
int Total
int * MaxUnit
StorageType * UnitStorage
GeneralObject ** UnitData
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
Add2Next()
void UnitList::Add2Next (GeneralObject * p, GeneralObject * t)
 {
     p->PrevTypeList = t;
     p->NextTypeList = t->NextTypeList;
     if(t->NextTypeList) t->NextTypeList->PrevTypeList = p;
     t->NextTypeList = p;
     Num++;
 };
References GeneralObject::NextTypeList, Num, and GeneralObject::PrevTypeList.
Add2Prev()
void UnitList::Add2Prev (GeneralObject * p, GeneralObject * t)
 {
     if(t == Tail) Tail = p;
     p->NextTypeList = t;
     p->PrevTypeList = t->PrevTypeList;
     if(t->PrevTypeList) t->PrevTypeList->NextTypeList = p;
     t->PrevTypeList = p;
     Num++;
 };
References GeneralObject::NextTypeList, Num, GeneralObject::PrevTypeList, and Tail.
ClearNet()
void UnitList::ClearNet (void)
ConnectObject()
void UnitList::ConnectObject (BaseObject * p)
 {
     ConnectTypeList(p);
     GameD.ConnectBaseList(p);
 };
References GameObjectDispatcher::ConnectBaseList(), ConnectTypeList(), and GameD.
Referenced by addVanger(), CreateDestroyEffect(), VangerUnit::CreateParticleMechos(), VangerUnit::CreateParticleRotor(), VangerUnit::Destroy(), VangerUnit::DrawQuant(), BulletObject::Event(), and DangerDataType::Quant().
ConnectTypeList()
void UnitList::ConnectTypeList (GeneralObject * p)
 {
 /*  GeneralObject* n;
     GeneralObject* np;
     int y;
     if(!Tail){
         p -> NextTypeList = p -> PrevTypeList = NULL;
         Tail = p;
     }else{
         y = p->R_curr.y;
         n = Tail;
         while(n){
             np = n;
             if(n->R_curr.z > y)
                 break;
             n = n->NextTypeList;
         };
         Add2Next(p,np);
     };*/
     if(!Tail){
         p -> NextTypeList = p -> PrevTypeList = NULL;
         Tail = p;
     }else{
         Tail -> PrevTypeList = p;
         p -> NextTypeList = Tail;
         p -> PrevTypeList = NULL;
         Tail = p;
     };
     Num++;
 };
References NULL, Num, and Tail.
Referenced by ConnectObject(), EffectDispatcher::CreateDeform(), EffectDispatcher::CreateDirectParticle(), EffectDispatcher::CreateExplosion(), EffectDispatcher::CreateFireBall(), EffectDispatcher::CreateParticle(), EffectDispatcher::CreateParticleGenerator(), EffectDispatcher::CreateParticleTime(), EffectDispatcher::CreateRingOfLord(), StuffObject::CreateStuff(), StuffObject::DeviceOut(), and StuffObject::NetEvent().
DisconnectTypeList()
void UnitList::DisconnectTypeList (GeneralObject * p)
 {
     if((!p->PrevTypeList) && (!p->NextTypeList)) Tail = NULL;
     else{
         if(p->PrevTypeList) p->PrevTypeList->NextTypeList = p->NextTypeList;
         else Tail = p->NextTypeList;
         if(p->NextTypeList) p->NextTypeList->PrevTypeList = p->PrevTypeList;
     };
     Num--;
 };
References GeneralObject::NextTypeList, NULL, Num, GeneralObject::PrevTypeList, and Tail.
Referenced by EffectDispatcher::DeleteEffect(), ItemsDispatcher::DeleteItem(), ActionDispatcher::DeleteUnit(), and StuffObject::DeviceIn().
GetNetObject()
GeneralObject * UnitList::GetNetObject (int id)
 {
     GeneralObject* p;
     p = Tail;
     while(p){
         if(p->NetID == id)
             return p;
         p = p->NextTypeList;
     };
     return NULL;
 };
References GeneralObject::NetID, GeneralObject::NextTypeList, NULL, and Tail.
Referenced by ItemsDispatcher::NetEvent(), ActionDispatcher::NetEvent(), StuffObject::NetEvent(), GunSlot::NetEvent(), StuffObject::NetOwnerQuant(), and NetSlotEvent().
GetObject()
GeneralObject* UnitList::GetObject (int type) inline
 { return UnitStorage[type].Active(); };
References StorageType::Active(), and UnitStorage.
Referenced by addDevice(), addVanger(), CreateDestroyEffect(), VangerUnit::CreateParticleMechos(), VangerUnit::CreateParticleRotor(), VangerUnit::Destroy(), VangerUnit::DrawQuant(), BulletObject::Event(), ItemsDispatcher::NetDevice(), ItemsDispatcher::NetEvent(), and DangerDataType::Quant().
Init()
void UnitList::Init (Parser & in)
 {
     Num = 0;
     Tail = NULL;
 };
References NULL, Num, and Tail.
Referenced by EffectDispatcher::Init(), ItemsDispatcher::Init(), and ActionDispatcher::Init().
NetEvent()
void UnitList::NetEvent (int type, int id) virtual
Reimplemented in ActionDispatcher, and ItemsDispatcher.
 {
 };
Open()
void UnitList::Open (Parser & in)
 {
     Num = 0;
     Tail = NULL;
 };
References NULL, Num, and Tail.
Referenced by EffectDispatcher::Open(), ItemsDispatcher::Open(), and ActionDispatcher::Open().
Quant()
void UnitList::Quant (void)
 { };
Member Data Documentation
MaxUnit
int* UnitList::MaxUnit
Referenced by EffectDispatcher::Free(), ItemsDispatcher::Free(), ActionDispatcher::Free(), EffectDispatcher::Init(), ItemsDispatcher::Init(), and ActionDispatcher::Init().
Num
int UnitList::Num
Referenced by Add2Next(), Add2Prev(), ConnectTypeList(), ItemsDispatcher::CryptQuant(), VangerUnit::DestroyItem(), DisconnectTypeList(), Init(), and Open().
Tail
GeneralObject* UnitList::Tail
Referenced by aciGetScreenItem(), uvsDolly::ActiveQuant(), Add2Prev(), addDevice(), ChangeItemData(), ChangeTabutaskItem(), EffectDispatcher::Close(), ItemsDispatcher::Close(), ActionDispatcher::Close(), ConnectTypeList(), TntCreature::Destroy(), VangerUnit::DestroyEnvironment(), DisconnectTypeList(), GunSlot::Fire(), GetNetObject(), ActionDispatcher::GetNextVanger(), getObjectPosition(), VangerUnit::Go2Universe(), Init(), InsectUnit::InitEnvironment(), ItemsDispatcher::LarvaHilator(), NetCheckRemovePlayer(), TntCreature::NetDestroy(), ItemsDispatcher::NetDevice(), ItemsDispatcher::NetEvent(), StuffObject::NetOwnerQuant(), ObjectDestroy(), Open(), EffectDispatcher::Quant(), GameObjectDispatcher::Quant(), HordeObject::Quant(), ItemsDispatcher::Quant(), VangerFunctionType::Quant(), ActionDispatcher::Quant(), VangerUnit::ResolveGenerator(), ActionDispatcher::ShellNetEvent(), VangerUnit::test_objects_collision(), InsectUnit::test_objects_collision(), and uvsapiDestroyItem().
Total
int UnitList::Total
Referenced by EffectDispatcher::Close(), ItemsDispatcher::Close(), ActionDispatcher::Close(), ItemsDispatcher::CryptQuant(), VangerUnit::DestroyItem(), EffectDispatcher::Free(), ItemsDispatcher::Free(), ActionDispatcher::Free(), EffectDispatcher::Init(), ItemsDispatcher::Init(), ActionDispatcher::Init(), EffectDispatcher::Open(), ItemsDispatcher::Open(), and ActionDispatcher::Open().
UnitData
GeneralObject** UnitList::UnitData
Referenced by EffectDispatcher::Close(), ItemsDispatcher::Close(), ActionDispatcher::Close(), EffectDispatcher::Free(), ItemsDispatcher::Free(), ActionDispatcher::Free(), EffectDispatcher::Init(), ItemsDispatcher::Init(), ActionDispatcher::Init(), EffectDispatcher::Open(), ItemsDispatcher::Open(), and ActionDispatcher::Open().
UnitStorage
StorageType* UnitList::UnitStorage
Referenced by EffectDispatcher::Close(), ItemsDispatcher::Close(), ActionDispatcher::Close(), EffectDispatcher::CreateDeform(), EffectDispatcher::CreateDirectParticle(), EffectDispatcher::CreateExplosion(), EffectDispatcher::CreateFireBall(), EffectDispatcher::CreateParticle(), EffectDispatcher::CreateParticleGenerator(), EffectDispatcher::CreateParticleTime(), EffectDispatcher::CreateRingOfLord(), iGameMap::draw(), EffectDispatcher::Free(), ItemsDispatcher::Free(), ActionDispatcher::Free(), GetObject(), EffectDispatcher::Init(), ItemsDispatcher::Init(), and ActionDispatcher::Init().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp