Vangers: dastPoly3D Struct Reference
dastPoly3D Struct Reference
#include <poly3d.h>
Public Member Functions
dastPoly3D (Vector lp, Vector rp, Vector dv)
dastPoly3D (Vector, int)
dastPoly3D (Vector, int, int)
~dastPoly3D (void)
void set (Vector lp, Vector rp, Vector dv)
void set (Vector, int)
void set (Vector _p, int _n, int _count)
void make_dast (void)
int quant_make_sign (void)
void make_mole (dastResourcePoly3D *res=dastResource)
int make_first_mole (dastResourcePoly3D *res=dastResource)
int make_last_mole (dastResourcePoly3D *res=dastResource)
int make_catch_dolly (dastResourcePoly3D *res=dastResource)
Public Attributes
Vector * p
Vector * p_array
int n
int count
Detailed Description
Constructor & Destructor Documentation
dastPoly3D() [1/3]
dastPoly3D::dastPoly3D (Vector lp, Vector rp, Vector dv)
{
     p = NULL;
     p_array = NULL;
     n = 4;
     count = 0;
     p_array = new Vector[4];
     p_array[0] = rp;
     p_array[1] = lp;
     p_array[2] = lp + dv;
     p_array[3] = rp + dv;
 }
References count, n, NULL, p, and p_array.
dastPoly3D() [2/3]
dastPoly3D::dastPoly3D (Vector _p, int _n)
{
     p = NULL;
     p_array = NULL;
     n = _n;
     count = dastResSign->poly[n];
     p = new Vector;
     *p = _p;
 /*   uchar *l1 = get_real_ground(0, p[0].x & clip_mask_x, p[0].y);
      uchar *l2 = get_real_ground(1, p[0].x & clip_mask_x, p[0].y);
     if ( abs( *l1 - p[0].z) < abs(*l2 - p[0].z)){
         pf = &get_up_ground;
     } else {
         pf = &get_down_ground;
     }*/
 }
References count, dastResSign, n, NULL, p, p_array, and dastResourceSign::poly.
dastPoly3D() [3/3]
dastPoly3D::dastPoly3D (Vector _p, int x, int y)
{
     p = NULL;
     p_array = NULL;
     n = x;
     count = y;
     p = new Vector;
     *p = _p;
 }
References count, n, NULL, p, and p_array.
~dastPoly3D()
dastPoly3D::~dastPoly3D (void)
{
     if (p) {
         delete p;
     }
     if (p_array) {
         delete[] p_array;
     }
 }
References p, and p_array.
Member Function Documentation
make_catch_dolly()
int dastPoly3D::make_catch_dolly (dastResourcePoly3D * res = dastResource)
{
     int dA = PIx2>>5;
     int A = 0;
     unsigned int scale;
     int dx, dy;
     if (count <= 0 ) return 0;
     if (!vMap -> lineT[p->y & clip_mask_y])
         return 0;
     int dz = *get_down_ground( (p->x) & clip_mask_x, p->y );
     if ( dz < 50 ) scale = 1 << 15;
     else if ( dz < 160 ) scale = 1 << 14;
     else if ( dz < 220 ) scale = 1 << 13;
     else return 0;
     for( int i = 1; i < 32; i++, A += dA)
         if ( !RND(16) ){
             dx = ((SI[A]*(n + RND(10)))>>16);
             dy = ((CO[A]*(n + RND(10)))>>16);
             dastPutSpriteOnMapAlt( p->x + dx, p->y + dy, res->data[RND(res->n)], res->x_size, res->y_size, scale);
             regRender( p->x + dx  - 8, p->y + dy - 8, p->x + dx + 8, p->y + dy + 8, 0);
         }
     //regRender( p->x - n - 18, p->y - n -18, p->x + n + 18, p->y + n + 18, 0);
     count--;
     return (count > 0);
 }
References clip_mask_x, clip_mask_y, CO, count, dastPutSpriteOnMapAlt(), dastResourcePoly3D::data, get_down_ground(), n, dastResourcePoly3D::n, p, PIx2, regRender(), RND(), SI, vMap, Vector::x, dastResourcePoly3D::x_size, Vector::y, and dastResourcePoly3D::y_size.
make_dast()
void dastPoly3D::make_dast (void)
make_first_mole()
int dastPoly3D::make_first_mole (dastResourcePoly3D * res = dastResource)
{
     int dA = PIx2>>5;
     int A = 0;
     unsigned int scale;
     if (count < 3 || n < 3) return 0;
     if (!vMap -> lineT[p->y & clip_mask_y])
         return 0;
     int dz = *get_down_ground( (p->x) & clip_mask_x, p->y );
     n -= 3;
     count -= 3;
     if ( dz < 50 ) scale = 1 << 15;
     else if ( dz < 160 ) scale = 1 << 14;
     else if ( dz < 220 ) scale = 1 << 13;
     else return 0;
     for( int i = 1; i < 32; i++, A += dA)
 //      if ( !RND(16 - (count/5)) ){
         if ( RND(count) && RND(3)){
             dastPutSpriteOnMapAlt( p->x + ((SI[A]*count)>>16), p->y + ((CO[A]*count)>>16), res->data[RND(res->n)], res->x_size, res->y_size, scale);
             //regRender( p->x - n - 8, p->y - count - 8, p->x + n + 8, p->y + count + 8, 0);
         }
     regRender( p->x - n - 8, p->y - count - 8, p->x + n + 8, p->y + count + 8, 0);
     return ((n > 0)&&(count > 0));
 }
References clip_mask_x, clip_mask_y, CO, count, dastPutSpriteOnMapAlt(), dastResourcePoly3D::data, get_down_ground(), n, dastResourcePoly3D::n, p, PIx2, regRender(), RND(), SI, vMap, Vector::x, dastResourcePoly3D::x_size, Vector::y, and dastResourcePoly3D::y_size.
Referenced by VangerUnit::MapQuant().
make_last_mole()
int dastPoly3D::make_last_mole (dastResourcePoly3D * res = dastResource)
{
     int dA = PIx2>>5;
     int A = 0;
     unsigned int scale;
     if (count >= n ) return 0;
     if (!vMap -> lineT[p->y & clip_mask_y])
         return 0;
     int dz = *get_down_ground( (p->x) & clip_mask_x, p->y );
     count += 3;
     if ( dz < 50 ) scale = 1 << 15;
     else if ( dz < 200 ) scale = 1 << 14;
     else scale = 1 << 13;
     for( int i = 1; i < 32; i++, A += dA)
         if ( RND(count) ){
 //      if ( !RND(16 - (count/5)) ){
             dastPutSpriteOnMapAlt( p->x + ((SI[A]*count)>>16), p->y + ((CO[A]*count)>>16), res->data[RND(res->n)], res->x_size, res->y_size, scale);
             //regRender( p->x - n - 8, p->y - count - 8, p->x + n + 8, p->y + count + 8, 0);
         }
     regRender( p->x - count - 8, p->y - count - 8, p->x + count + 8, p->y + count + 8, 0);
     return (count < n);
 }
References clip_mask_x, clip_mask_y, CO, count, dastPutSpriteOnMapAlt(), dastResourcePoly3D::data, get_down_ground(), n, dastResourcePoly3D::n, p, PIx2, regRender(), RND(), SI, vMap, Vector::x, dastResourcePoly3D::x_size, Vector::y, and dastResourcePoly3D::y_size.
make_mole()
void dastPoly3D::make_mole (dastResourcePoly3D * res = dastResource)
{
     int xl, xr, yl, yr;
 //--------------------------------------
     if (p_array[0].x < p_array[1].x ) {
         xl = p_array[0].x;
         xr = p_array[1].x;
     }else {
         xl = p_array[1].x;
         xr = p_array[0].x;
     }
     if (xl > p_array[2].x ) xl = p_array[2].x;
     if (xl > p_array[3].x ) xl = p_array[3].x;
     if (xr < p_array[2].x ) xr = p_array[2].x;
     if (xr < p_array[3].x ) xr = p_array[3].x;
     if (p_array[0].y < p_array[1].y ) {
         yl = p_array[0].y;
         yr = p_array[1].y;
     }else {
         yl = p_array[1].y;
         yr = p_array[0].y;
     }
     if (yl > p_array[2].y ) yl = p_array[2].y;
     if (yl > p_array[3].y ) yl = p_array[3].y;
     if (yr < p_array[2].y ) yr = p_array[2].y;
     if (yr < p_array[3].y ) yr = p_array[3].y;
 //--------------------------------------
     if (!vMap -> lineT[p_array[0].y & clip_mask_y])
         return;
     unsigned int scale;
     int dz = *get_down_ground( (p_array[0].x) & clip_mask_x, p_array[0].y );
     if ( dz < 50 ) scale = 1 << 15;
     else if ( dz < 120 ) scale = 1 << 14;
     else if ( dz < 200 ) scale = 1 << 13;
     else return ;
     for( int i = 1; i < 8; i++)
         if(!RND(5)) {
             dastPutSpriteOnMapAlt( (i*p_array[1].x + (8-i)*p_array[0].x)>>3, (i*p_array[1].y +  (8-i)*p_array[0].y)>>3, res->data[RND(res->n)], res->x_size, res->y_size, scale);
             ++i;
         }
     regRender(xl - (res->x_size>>1), yl - (res->y_size>>1), xr + (res->x_size>>1), yr + (res->y_size>>1), 0);
 }
References clip_mask_x, clip_mask_y, dastPutSpriteOnMapAlt(), dastResourcePoly3D::data, get_down_ground(), dastResourcePoly3D::n, p_array, regRender(), RND(), vMap, Vector::x, dastResourcePoly3D::x_size, Vector::y, and dastResourcePoly3D::y_size.
Referenced by VangerUnit::MoleProcessQuant().
quant_make_sign()
int dastPoly3D::quant_make_sign (void)
{
     Vector lp;
     int xl, xr, yl, yr;
     int dx, dy;
     int _z = p->z;
     for( int s = 0; s < dastResSign->once[n]; s++){
         if (count == dastResSign->poly[n]) return 0;
         lp.x = p->x + dastResSign -> x[n][count];
         lp.y = p->y + dastResSign -> y[n][count];
         if (p->x < lp.x ) {
             xl = p->x;
             xr = lp.x;
         }else {
             xl = lp.x;
             xr = p->x;
         }
         if (p->y < lp.y ) {
             yl = p->y;
             yr = lp.y;
         }else {
             yl = lp.y;
             yr = p->y;
         }
         switch (dastResSign -> type[n][count]){
         case DAST_SIGN_TYPE::UP:
         case DAST_SIGN_TYPE::DOWN:
         {
             dx = (lp.x-p->x);
             dy = (lp.y-p->y);
             int max;
             p->x <<= 16;
             p->x += 1<<15;
             p->y <<= 16;
             p->y += 1<<15;
             if ( abs(dx ) > abs(dy) ) max = abs(dx); else max = abs(dy);
             int tt = (1<<16)/max;
             dx *= tt;
             dy *= tt;
             for( int i = 0; i < max; i++){
                 int x = (p->x)>>16;
                 int y = (p->y)>>16;
                 //dastPutSandOnMapAlt( x ,y, uchar(p->z), uchar(5), dastResSign -> wide[n][count] );
                 dastPutSandOnMapAlt( x ,y, uchar(p->z), uchar(6), dastResSign -> wide[n][count] );
                 //regRender(x - 7, y - 7, x + 7, y + 7, 0);
                 p->x += dx;
                 p->y += dy;
             }
             break;
         }
         case DAST_SIGN_TYPE::MOVE:
             break;
         }
         *p = lp;
         p->z = _z;
         count++;
     }
     return (count != dastResSign->poly[n]);
 }
References count, dastPutSandOnMapAlt(), dastResSign, DAST_SIGN_TYPE::DOWN, max(), DAST_SIGN_TYPE::MOVE, n, dastResourceSign::once, p, dastResourceSign::poly, DAST_SIGN_TYPE::UP, Vector::x, Vector::y, and Vector::z.
set() [1/3]
void dastPoly3D::set (Vector _p, int _n, int _count)
{
     *p = _p;
     n = _n_;
     count = _count_;
 }
References count, n, and p.
set() [2/3]
void dastPoly3D::set (Vector lp, Vector rp, Vector dv)
{
     p_array[0] = rp;
     p_array[1] = lp;
     p_array[2] = lp + dv;
     p_array[3] = rp + dv;
 }
References p_array.
Referenced by StuffObject::DeviceOut(), StuffObject::ImpulseAction(), VangerFunctionType::Init(), VangerUnit::MapQuant(), VangerUnit::MoleProcessQuant(), StuffObject::Quant(), and VangerUnit::StartMoleProcess().
set() [3/3]
void dastPoly3D::set (Vector _p, int _n)
{
     *p = _p;
     n = _n;
     count = 0;
 }
References count, n, and p.
Member Data Documentation
count
int dastPoly3D::count
Referenced by dastPoly3D(), make_catch_dolly(), make_first_mole(), make_last_mole(), quant_make_sign(), and set().
n
int dastPoly3D::n
Referenced by dastPoly3D(), make_catch_dolly(), make_first_mole(), make_last_mole(), quant_make_sign(), and set().
p
Vector* dastPoly3D::p
Referenced by dastPoly3D(), make_catch_dolly(), make_first_mole(), make_last_mole(), quant_make_sign(), set(), and ~dastPoly3D().
p_array
Vector * dastPoly3D::p_array
Referenced by dastPoly3D(), make_mole(), set(), and ~dastPoly3D().
The documentation for this struct was generated from the following files:
src/dast/poly3d.h
src/dast/poly3d.cpp