Vangers: EnterEngine Struct Reference
EnterEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Close (void)
virtual void Active (void)
Public Member Functions inherited from LocationEngine
virtual void Quant (void)
virtual void Link (void)
virtual void Touch (GeneralObject *obj, SensorDataType *p)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
SensorDataType * ActionLink
EnterCenter * Owner
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Active()
void EnterEngine::Active (void) virtual
Reimplemented in ImpulseSpot, ImpulseEscave, EscaveEngine, and ElevatorEngine.
 {
 };
Referenced by EnterCenter::ActiveCenter().
Close()
void EnterEngine::Close (void) virtual
Reimplemented from LocationEngine.
Reimplemented in ElevatorEngine.
 {
 };
Open()
void EnterEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
Reimplemented in ImpulseSpot, ImpulseEscave, EscaveEngine, and ElevatorEngine.
 {
     char* n;
     LocationEngine::Open(in);
     in.search_name("ActionName");
     n = in.get_name();
     ActionLink = FindSensor(n);
     if(!ActionLink)
         ErrH.Abort("Bad Find Sensor");
     ActionLink->Owner = this;
     ActionLink->Enable = 1;
     ActionLink->Index = 0;
 };
References XErrorHandler::Abort(), ActionLink, StaticObject::Enable, ErrH, FindSensor(), Parser::get_name(), SensorDataType::Index, LocationEngine::Open(), SensorDataType::Owner, and Parser::search_name().
Referenced by ElevatorEngine::Open().
Member Data Documentation
ActionLink
SensorDataType* EnterEngine::ActionLink
Referenced by EscaveEngine::Active(), ImpulseSpot::Active(), EnterCenter::GetCenter(), EnterCenter::GetEnterCenter(), EnterCenter::GetNearCenter(), Open(), ImpulseSpot::Open(), EscaveEngine::Quant(), and ImpulseSpot::Quant().
Owner
EnterCenter* EnterEngine::Owner
Referenced by ElevatorEngine::Quant(), EscaveEngine::Quant(), ImpulseEscave::Quant(), and ImpulseSpot::Quant().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp