Vangers: TrackUnit Struct Reference
TrackUnit Struct Reference
#include <mechos.h>
Public Member Functions
void Init (StorageType *s)
void Free (void)
void Open (void)
void Close (void)
void Quant (void)
void CreateTrackUnit (void)
int TraceWay (void)
void WayInit (void)
void GetNode (TrackLinkType *tp, char &dir)
void GetInside (void)
char GetDirect (TrackLinkType *tp)
char Check2Position (int fx, int fy, int num)
char TestAnalysis (TrackLinkType &tp)
void GetBranch (void)
void HideGetBranch (void)
char ActiveGetBranch (void)
void MixVector (void)
void GetTrackVector (void)
void DirectQuant (void)
void TrackQuant (void)
void LastFire (void)
void DrawMechosParticle (int x, int y, int speed, int level, int n)
void Hide2Show (void)
void MakeTrackDist (void)
int GeneralRND (unsigned int m)
Public Member Functions inherited from ActionUnit
void Init (StorageType *s)
void Free (void)
void Open (void)
void Close (void)
void DrawQuant (void)
void CreateActionUnit (int nmodel, int _status, const Vector &_v, int _angle, int put_mode)
virtual void InitEnvironment (void)
virtual void keyhandler (int key)
virtual void DeleteHandler (void)
void CalcTrackVector (Vector &v, int &len, int &angle1, int &angle2)
void Action (void)
void HideAction (void)
void MixVector (void)
void Touch (GeneralObject *obj)
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
virtual int test_objects_collision ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Member Functions inherited from TrackLinkType
TrackLinkType (void)
void ChangeLink (void)
void HideChangeLink (char dir)
void AddLink (char s)
void DecLink (char s)
Public Attributes
int aiMoveMode
int aiMoveFunction
TrackLinkType TestPoint
TrackLinkType FrontPoint
int * WayDist
int * WayDistData
int * CalcWayDist
int * TrackDist
int NoWayDirect
TrackLinkType TargetPoint
Vector vTarget
int TargetAngle
int TargetLen
int EnvirReaction
int TargetReaction
int NullTime
char MoveDir
char FrontDir
BranchType * PrevBranch
int CheckPosition
int MaxCheckPosition
int CheckWayCount
int MaxWayCount
int DestroyPhase
int PrevWheelX [6]
int PrevWheelY [6]
int PrevWheelFlag [6]
int gRnd
Public Attributes inherited from ActionUnit
Vector vDirect
Vector vEnvir
int EnvirAngle
int EnvirLen
int NumCalcUnit
int NumViewUnit
int MaxVelocity
int ViewRadius
char SpeedDir
int MinSpeed
int MaxSpeed
int CurrSpeed
int MaxHideSpeed
int MoveAngle
int DeltaSpeed
int DeltaTraction
char OtherFlag
Vector vUp
Vector vDown
int Speed
int Angle
DBM RotMat
DBM MovMat
int PrevVisibility
int Count
int WavePhase
WaveProcess * wProcess
int nModel
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Public Attributes inherited from TrackLinkType
char PointStatus
Vector vPoint
LinkType * pNextLink
LinkType * pPrevLink
BranchType * pBranch
NodeType * pNode
Detailed Description
Member Function Documentation
ActiveGetBranch()
char TrackUnit::ActiveGetBranch (void)
 {
     char i;
     LinkType* lp;
     LinkType* ln;
     BranchType* b;
     ChangeLink();
     if(PointStatus == TRK_IN_BRANCH) return 0;
     if(pNode){
         if(PointStatus & TRK_NODE_MASK){
             if(CheckInNode(vPoint,pNode)){
                 PointStatus = TRK_IN_NODE;
                 OtherFlag |= MECHOS_RECALC_FRONT;
                 return 0;
             }else PointStatus = TRK_OUT_NODE;
         };
         for(i = 0;i < pNode->NumBranch;i++){
             b = pNode->pBranches[i];
             if(b != pBranch){
                 if(pNode->Status[i]){
                     lp = b->Link;
                     ln = lp + 1;
                 }else{
                     ln = b->Link + b->NumLink - 1;
                     lp = ln - 1;
                 };
                 if(CheckInBranch(vPoint,lp,ln,b)){
                     pBranch = b;
                     pPrevLink = lp;
                     pNextLink = ln;
                     PointStatus = TRK_IN_BRANCH;
                     OtherFlag |= MECHOS_RECALC_FRONT;
                     return 0;
                 };
             };
         };
     };
     return 1;
 /*  if(PointStatus & TRK_NODE_MASK){
         if(CheckInNode(vPoint,pNode)){
             PointStatus = TRK_IN_NODE;
             OtherFlag |= MECHOS_RECALC_FRONT;
             return;
         }else{
             for(i = 0;i < pNode->NumBranch;i++){
                 b = pNode->pBranches[i];
                 if(pNode->Status[i]){
                     lp = b->Link;
                     ln = lp + 1;
                 }else{
                     ln = b->Link + b->NumLink - 1;
                     lp = ln - 1;
                 };
                 if(CheckInBranch(vPoint,lp,ln,b)){
                     pBranch = b;
                     pPrevLink = lp;
                     pNextLink = ln;
                     PointStatus = TRK_IN_BRANCH;
                     OtherFlag |= MECHOS_RECALC_FRONT;
                     return;
                 };
             };
             PointStatus = TRK_OUT_NODE;
         };
     };*/
 };
References TrackLinkType::ChangeLink(), CheckInBranch(), CheckInNode(), BranchType::Link, MECHOS_RECALC_FRONT, NodeType::NumBranch, BranchType::NumLink, ActionUnit::OtherFlag, TrackLinkType::pBranch, NodeType::pBranches, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, NodeType::Status, TRK_IN_BRANCH, TRK_IN_NODE, TRK_NODE_MASK, TRK_OUT_NODE, and TrackLinkType::vPoint.
Referenced by GetBranch(), and VangerUnit::Quant().
Check2Position()
char TrackUnit::Check2Position (int fx, int fy, int num)
 {
     int dx,dy;
     int tx,ty;
     int i;
     tx = R_curr.x << 15;
     ty = R_curr.y << 15;
     dx = (getDistX(fx,R_curr.x) << 15) / num;
     dy = (getDistY(fy,R_curr.y) << 15) / num;
     TestPoint.PointStatus = TRK_IN_BRANCH;
     TestPoint.pNextLink = pNextLink;
     TestPoint.pPrevLink = pPrevLink;
     TestPoint.pBranch = pBranch;
     TestPoint.pNode = pNode;
     for(i = 0;i < num;i++){
         TestPoint.vPoint.x = tx >> 15;
         TestPoint.vPoint.y = ty >> 15;
         if(!TestAnalysis(TestPoint)) return 0;
         tx += dx;
         ty += dy;
     };
     return 1;
 };
References getDistX(), getDistY(), TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, TestAnalysis(), TestPoint, TRK_IN_BRANCH, TrackLinkType::vPoint, Vector::x, and Vector::y.
Close()
void TrackUnit::Close (void)
 {
     delete[] WayDistData;
     delete[] TrackDist;
 };
References TrackDist, and WayDistData.
CreateTrackUnit()
void TrackUnit::CreateTrackUnit (void)
 {
     int i;
 //  MobilityType = _type;
     WayDist = WayDistData;
     CalcWayDist = WayDistData + HideTrack.NumNode;
     memset(WayDistData,0,sizeof(int)*HideTrack.NumNode*2);
     TargetAngle = TargetLen = 0;
     EnvirReaction = 128;
     TargetReaction = TOTAL_REACTION - EnvirReaction;
     MoveDir = 1;
     PointStatus = TRK_IN_BRANCH;
     pNextLink = NULL;
     pBranch = NULL;
     HideTrack.GetFirstPosition(R_curr.x,R_curr.y,pNextLink,pBranch);
 //  if(pBranch == NULL || pNextLink == NULL)
 //      ErrH.Abort("Bad Track Position");
     if(pNextLink == pBranch->Link){
         pPrevLink = pNextLink;
         pNextLink++;
     }else pPrevLink = pNextLink - 1;
 //  WayData = ActD.WayMap[MobilityType];
 //  MobilityValue = ActD.MaxMobility[MobilityType];
 //  HideTrack.InitTrace(MaxNoise,0,WayData,0);
     if(pBranch->pBeg) pNode = pBranch->pBeg;
     else pNode = pBranch->pEnd;
     FrontDir = -1;
     FrontPoint.PointStatus = TRK_IN_BRANCH;
     FrontPoint.pNextLink = pNextLink;
     FrontPoint.pPrevLink = pPrevLink;
     FrontPoint.pBranch = pBranch;
     FrontPoint.pNode = pNode;
     PrevBranch = pBranch;
     OtherFlag = MECHOS_RECALC_FRONT | MECHOS_TARGET_MOVE;
     CheckWayCount = MaxWayCount = 50;
 #ifdef TEST_TRACK
     CheckPosition = MaxCheckPosition = 50;
 #else
     CheckPosition = MaxCheckPosition = 15;
 #endif
     DestroyPhase = 0;
     vTarget = Vector(0,0,0);
     for(i =0;i < n_wheels;i++){
         PrevWheelX[i] = 0;
         PrevWheelY[i] = 0;
         PrevWheelFlag[i] = 0;
     };
     NullTime = 0;
 /*  PrevWheelX[0] =  PrevWheelX[1] = 0;
     PrevWheelY[0] = PrevWheelY[1] = 0;
     PrevWheelFlag[0] = PrevWheelFlag[1] = 0;
     nLeftWheel = -1;
     nRightWheel = -1;
     for(i = 0;i < n_wheels;i++){
         if(!wheels[i].steer){
             if(nLeftWheel == -1) nLeftWheel = i;
             else if(nRightWheel == -1) nRightWheel = i;
                 else break;
         };
     };*/
     vEnvir = Vector(0,0,0);
     vDirect = Vector(0,0,0);
     aiMoveMode = AI_MOVE_TRACK;
     aiMoveFunction = AI_MOVE_FUNCTION_WHEEL;
     gRnd = 0xFFFFFFFF;
 };
References AI_MOVE_FUNCTION_WHEEL, AI_MOVE_TRACK, aiMoveFunction, aiMoveMode, CalcWayDist, CheckPosition, CheckWayCount, DestroyPhase, EnvirReaction, FrontDir, FrontPoint, TrackType::GetFirstPosition(), gRnd, HideTrack, BranchType::Link, MaxCheckPosition, MaxWayCount, MECHOS_RECALC_FRONT, MECHOS_TARGET_MOVE, MoveDir, Object::n_wheels, NULL, NullTime, TrackType::NumNode, ActionUnit::OtherFlag, BranchType::pBeg, TrackLinkType::pBranch, BranchType::pEnd, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, PrevBranch, PrevWheelFlag, PrevWheelX, PrevWheelY, TargetAngle, TargetLen, TargetReaction, TOTAL_REACTION, TRK_IN_BRANCH, ActionUnit::vDirect, ActionUnit::vEnvir, vTarget, WayDist, and WayDistData.
Referenced by addVanger().
DirectQuant()
void TrackUnit::DirectQuant (void)
 {
     int d;
     if(SpeedDir != 0){
 //      if(MoveDir == -1) ErrH.Abort("Bad Move Direction");
 //      if(pNode != pBranch->pBeg && pNode != pBranch->pEnd) ErrH.Abort("Bad Branch Link");
         switch(FrontPoint.PointStatus){
 //-----------------------------------------------------------------------------------------------
             case TRK_IN_BRANCH:
                 FrontPoint.pNextLink = pNextLink;
                 FrontPoint.pPrevLink = pPrevLink;
                 FrontPoint.pBranch = pBranch;
                 FrontPoint.pNode = pNode;
                 if(SpeedDir > 0){
                     if(MoveDir) FrontPoint.AddLink(radius / 12);
                     else FrontPoint.DecLink(radius / 12);
                 }else{
                     if(MoveDir) FrontPoint.DecLink(radius / 12);
                     else FrontPoint.AddLink(radius / 12);
                 };
                 if((TargetPoint.PointStatus & TRK_BRANCH_MASK) && pBranch == TargetPoint.pBranch){
                     if(TargetPoint.pNextLink <= FrontPoint.pNextLink){
                         if(TargetPoint.pNextLink >= pNextLink){
                             FrontPoint.pNextLink = TargetPoint.pNextLink;
                             FrontPoint.pPrevLink = TargetPoint.pPrevLink;
                             FrontPoint.PointStatus = TRK_TARGET_LINK;
                         }else{
                             MoveDir = 0;
                             FrontPoint.PointStatus = TRK_IN_BRANCH;
                         };
                     }else{
                         if(TargetPoint.pNextLink <= pNextLink){
                             FrontPoint.pNextLink = TargetPoint.pNextLink;
                             FrontPoint.pPrevLink = TargetPoint.pPrevLink;
                             FrontPoint.PointStatus = TRK_TARGET_LINK;
                         }else{
                             MoveDir = 1;
                             FrontPoint.PointStatus = TRK_IN_BRANCH;
                         };
                     };
                 }else{
                     if(FrontPoint.PointStatus == TRK_WAIT_NODE){
                         PrevBranch = pBranch;
                         GetNode(&FrontPoint,FrontDir);
                         NoWayDirect = -1;
                         if(SpeedDir == 0) FrontPoint.PointStatus = TRK_IN_BRANCH;
                         else{
                             if(FrontDir == -1) FrontPoint.PointStatus = TRK_TARGET_NODE;
                             else
                                 if(FrontPoint.pBranch == pBranch){
                                     MoveDir ^= 1;
                                     FrontPoint.PointStatus = TRK_IN_BRANCH;
                                 };
                         };
                     };
                 };
                 break;
             case TRK_WAIT_NODE:
                 if(PointStatus & TRK_NODE_MASK){
                     if(pNode == FrontPoint.pNode){
                         MoveDir = FrontDir;
                         pNextLink = FrontPoint.pNextLink;
                         pPrevLink = FrontPoint.pPrevLink;
                         pBranch = FrontPoint.pBranch;
                         if(SpeedDir > 0){
                             if(MoveDir) FrontPoint.AddLink(radius / 12);
                             else FrontPoint.DecLink(radius / 12);
                         }else{
                             if(MoveDir) FrontPoint.DecLink(radius / 12);
                             else FrontPoint.AddLink(radius / 12);
                         };
                         FrontPoint.PointStatus = TRK_WAIT_BRANCH;
                     }else FrontPoint.PointStatus = TRK_IN_NODE;
                 }else{
 //                  if(pBranch != PrevBranch)
 //                      ErrH.Abort("Bad Prev Branch");
                     if(SpeedDir > 0){
                         if(MoveDir){
                             if(CheckAddLink(pNextLink,pBranch,radius / 12)) FrontPoint.PointStatus = TRK_IN_BRANCH;
                         }else{
                             if(CheckDecLink(pPrevLink,pBranch,radius / 12)) FrontPoint.PointStatus = TRK_IN_BRANCH;
                         };
                     }else{
                         if(MoveDir){
                             if(CheckDecLink(pPrevLink,pBranch,radius / 12)) FrontPoint.PointStatus = TRK_IN_BRANCH;
                         }else{
                             if(CheckAddLink(pNextLink,pBranch,radius / 12)) FrontPoint.PointStatus = TRK_IN_BRANCH;
                         };
                     };
                 };
                 break;
             case TRK_WAIT_BRANCH:
                 if(PointStatus & TRK_BRANCH_MASK){
                     FrontPoint.PointStatus = TRK_IN_BRANCH;
 //                  if(pBranch != FrontPoint.pBranch) ErrH.Abort("Error in Wait Branch");
                 };
                 break;
 //-----------------------------------------------------------------------------------------------
             case TRK_IN_NODE:
                 FrontPoint.pNextLink = pNextLink;
                 FrontPoint.pPrevLink = pPrevLink;
                 FrontPoint.pBranch = pBranch;
                 FrontPoint.pNode = pNode;
                 GetNode(&FrontPoint,FrontDir);
                 NoWayDirect = -1;
                 if(SpeedDir == 0) FrontPoint.PointStatus = TRK_IN_NODE;
                 else{
                     if(FrontDir == -1) FrontPoint.PointStatus = TRK_TARGET_NODE;
                     else{
                         MoveDir = FrontDir;
                         pNextLink = FrontPoint.pNextLink;
                         pPrevLink = FrontPoint.pPrevLink;
                         pBranch = FrontPoint.pBranch;
                         if(SpeedDir > 0){
                             if(MoveDir) FrontPoint.AddLink(radius / 12);
                             else FrontPoint.DecLink(radius / 12);
                         }else{
                             if(MoveDir) FrontPoint.DecLink(radius / 12);
                             else FrontPoint.AddLink(radius / 12);
                         };
                         FrontPoint.PointStatus = TRK_WAIT_BRANCH;
                     };
                 };
                 break;
 //-----------------------------------------------------------------------------------------------
             case TRK_TARGET_LINK:
                 if(PointStatus & TRK_BRANCH_MASK){
                     if(pBranch == FrontPoint.pBranch){
                         d = (int)(pNextLink - FrontPoint.pNextLink);
                         if(abs(d) > radius / 15) FrontPoint.PointStatus = TRK_IN_BRANCH;
                     }else{
                         OtherFlag |= MECHOS_RECALC_FRONT;
                         FrontPoint.PointStatus = TRK_IN_BRANCH;
                     };
                 }else FrontPoint.PointStatus = TRK_IN_NODE;
                 break;
             case TRK_TARGET_NODE:
                 if(PointStatus & TRK_NODE_MASK){
                     if(FrontPoint.pNode != pNode) FrontPoint.PointStatus = TRK_IN_NODE;
                 }else FrontPoint.PointStatus = TRK_IN_BRANCH;
                 break;
 //-----------------------------------------------------------------------------------------------
             case TRK_END_BRANCH:
                 MoveDir ^= 1;
                 FrontPoint.PointStatus = TRK_IN_BRANCH;
                 break;
         };
         switch(FrontPoint.PointStatus){
             case TRK_WAIT_NODE:
             case TRK_END_BRANCH:
             case TRK_WAIT_BRANCH:
             case TRK_TARGET_LINK:
             case TRK_IN_BRANCH:
                 if(SpeedDir > 0){
                     if(MoveDir) vDirect = Vector(getDistX(FrontPoint.pNextLink->x,XCYCL(R_curr.x + vUp.x)),getDistY(FrontPoint.pNextLink->y,R_curr.y + vUp.y),0);
                     else vDirect = Vector(getDistX(FrontPoint.pPrevLink->x,XCYCL(R_curr.x + vUp.x)),getDistY(FrontPoint.pPrevLink->y,R_curr.y + vUp.y),0);
                 }else{
                     if(MoveDir) vDirect = Vector(getDistX(FrontPoint.pNextLink->x,XCYCL(R_curr.x + vDown.x)),getDistY(FrontPoint.pNextLink->y,R_curr.y + vDown.y),0);
                     else vDirect = Vector(getDistX(FrontPoint.pPrevLink->x,XCYCL(R_curr.x + vDown.x)),getDistY(FrontPoint.pPrevLink->y,R_curr.y + vDown.y),0);
                 };
                 break;
             case TRK_IN_NODE:
             case TRK_TARGET_NODE:
                 if(SpeedDir > 0) vDirect = Vector(getDistX(FrontPoint.pNode->x,XCYCL(R_curr.x + vUp.x)),getDistY(FrontPoint.pNode->y,R_curr.y + vUp.y),0);
                 else vDirect = Vector(getDistX(FrontPoint.pNode->x,XCYCL(R_curr.x + vDown.x)),getDistY(FrontPoint.pNode->y,R_curr.y + vDown.y),0);
                 break;
         };
     };
 };
References TrackLinkType::AddLink(), CheckAddLink(), CheckDecLink(), TrackLinkType::DecLink(), FrontDir, FrontPoint, getDistX(), getDistY(), GetNode(), MECHOS_RECALC_FRONT, MoveDir, NoWayDirect, ActionUnit::OtherFlag, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, PrevBranch, Object::radius, ActionUnit::SpeedDir, TargetPoint, TRK_BRANCH_MASK, TRK_END_BRANCH, TRK_IN_BRANCH, TRK_IN_NODE, TRK_NODE_MASK, TRK_TARGET_LINK, TRK_TARGET_NODE, TRK_WAIT_BRANCH, TRK_WAIT_NODE, ActionUnit::vDirect, ActionUnit::vDown, ActionUnit::vUp, Vector::x, LinkType::x, NodeType::x, XCYCL, Vector::y, LinkType::y, and NodeType::y.
Referenced by VangerUnit::TargetAnalysis().
DrawMechosParticle()
void TrackUnit::DrawMechosParticle (int x, int y, int speed, int level, int n)
 {
     uchar* TypeMap;
     int rLog = 1;
     uchar trn;
 //  int pf;
     double CosTetta = Cos(tetta)*(1 << FIXED_SHIFT)*8/3;
     int track_nx = -round(Cos(psi)*CosTetta);
     int track_ny = round(Sin(psi)*CosTetta);
     if(CurrentWorld == WORLD_KHOX) return;
     if(speed != 0){
 //      if(n == nLeftWheel) pf = 0;
 //      else if(n == nRightWheel) pf = 1;
 //          else return;
         //rLog = (256 - abs(speed)) >> 4;
         //if(rLog <= 2) rLog = 2;
         cycleTor(x,y);
         TypeMap = vMap->lineT[y];
         if(!TypeMap) return;
         TypeMap += H_SIZE + x;
         if((*TypeMap) & DOUBLE_LEVEL){
             if(level){
                 trn = GET_REAL_TERRAIN(TypeMap,x);
                 if(trn == 1){
                     if(PrevWheelY[n] != 0)
                         MapD.CreateTrace(x,y,PrevWheelX[n],PrevWheelY[n],track_nx,track_ny,1);
                     PrevWheelX[n] = x;
                     PrevWheelY[n] = y;
                     PrevWheelFlag[n] = 1;
                 };
             }else{
                 trn = GET_REAL_DOWNTERRAIN(TypeMap,x);
                 if(trn == 1){
                     if(PrevWheelY[n] != 0)
                         MapD.CreateTrace(x,y,PrevWheelX[n],PrevWheelY[n],track_nx,track_ny,0);
                     PrevWheelX[n] = x;
                     PrevWheelY[n] = y;
                     PrevWheelFlag[n] = 1;
                 };
             };
         }else{
             trn = GET_TERRAIN(*TypeMap);
             if(trn == 1){
                 if(PrevWheelY[n] != 0)
                     MapD.CreateTrace(x,y,PrevWheelX[n],PrevWheelY[n],track_nx,track_ny,1);
                 PrevWheelX[n] = x;
                 PrevWheelY[n] = y;
                 PrevWheelFlag[n] = 1;
             };
         };
         if((int)(RND(10)) > speed) return;
         if(trn == 1)
             MapD.CreateDust(Vector(x,y,level), MAP_DUST_PROCESS);
         if(Status & SOBJ_ACTIVE) NullTime = 0;
     }else{
         if(Status & SOBJ_ACTIVE){
             cycleTor(x,y);
             TypeMap = vMap->lineT[y];
             if(!TypeMap) return;
             TypeMap += H_SIZE + x;
             if(level && ((*TypeMap) & DOUBLE_LEVEL) && GET_REAL_TERRAIN(TypeMap,x) == 1) NullTime++;
             else NullTime = 0;
         };
     };
 };
References Cos(), CurrentWorld, cycleTor(), DOUBLE_LEVEL, FIXED_SHIFT, GET_REAL_DOWNTERRAIN(), GET_REAL_TERRAIN(), GET_TERRAIN, H_SIZE, level, vrtMap::lineT, MapD, NullTime, PrevWheelFlag, PrevWheelX, PrevWheelY, Object::psi, RND(), round(), Sin(), SOBJ_ACTIVE, Object::speed, Object::tetta, vMap, WORLD_KHOX, Object::x, and Object::y.
Referenced by VangerUnit::DrawMechosParticle().
Free()
void TrackUnit::Free (void)
 {
 };
GeneralRND()
int TrackUnit::GeneralRND (unsigned int m) inline
{
         gRnd ^= gRnd >> 3;
         gRnd ^= gRnd << 28;
         gRnd &= 0x7FFFFFFF;
         if(!m) return 0;
         return gRnd % m;
     };
References gRnd, and Object::m.
GetBranch()
void TrackUnit::GetBranch (void)
 {
     switch(PointStatus){
         case TRK_IN_BRANCH:
             CheckPosition = 0;
             ChangeLink();
             break;
         case TRK_IN_NODE:
             CheckPosition = 0;
             if(!CheckInNode(vPoint,pNode)){
                 if(CheckInBranch(vPoint,pPrevLink,pNextLink,pBranch)) PointStatus = TRK_IN_BRANCH;
                 else PointStatus = TRK_OUT_NODE;
             };
             break;
         case TRK_END_BRANCH:
         case TRK_OUT_NODE:
         case TRK_OUT_BRANCH:
             if(ActiveGetBranch()){
                 CheckPosition++;
                 if(CheckPosition > MaxCheckPosition){
                     CheckPosition = 0;
                     GetInside();
                 };
             };
             break;
     };
 };
References ActiveGetBranch(), TrackLinkType::ChangeLink(), CheckInBranch(), CheckInNode(), CheckPosition, GetInside(), MaxCheckPosition, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, TRK_END_BRANCH, TRK_IN_BRANCH, TRK_IN_NODE, TRK_OUT_BRANCH, TRK_OUT_NODE, and TrackLinkType::vPoint.
Referenced by VangerUnit::Quant().
GetDirect()
char TrackUnit::GetDirect (TrackLinkType * tp)
 {
     TrackLinkType t;
     char d;
     if(tp->PointStatus & TRK_BRANCH_MASK){
         if(NoWayDirect != -1) return NoWayDirect;
         if(MoveDir){
             if(tp->pBranch->pEnd){
                 t.pNode = tp->pBranch->pEnd;
                 GetNode(&t,d);
                 if(t.pBranch == tp->pBranch) return 0;
             }else{
                 if(tp->pBranch->pBeg){
                     t.pNode = tp->pBranch->pBeg;
                     GetNode(&t,d);
                     if(t.pBranch != tp->pBranch) return 0;
                 }else ErrH.Abort("Bad Node's Link to Branch");
             };
             return 1;
         }else{
             if(tp->pBranch->pBeg){
                 t.pNode = tp->pBranch->pBeg;
                 GetNode(&t,d);
                 if(t.pBranch == tp->pBranch) return 1;
             }else{
                 if(tp->pBranch->pEnd){
                     t.pNode = tp->pBranch->pEnd;
                     GetNode(&t,d);
                     if(t.pBranch != tp->pBranch) return 1;
                 }else ErrH.Abort("Bad Node's Link to Branch");
             };
             return 0;
         };
     };
     return -1;
 };
References XErrorHandler::Abort(), ErrH, GetNode(), MoveDir, NoWayDirect, BranchType::pBeg, TrackLinkType::pBranch, BranchType::pEnd, TrackLinkType::pNode, TrackLinkType::PointStatus, and TRK_BRANCH_MASK.
Referenced by TrackQuant().
GetInside()
void TrackUnit::GetInside (void)
 {
     int i,j;
     Vector vTrack;
     LinkType* ml;
     LinkType* pml;
     BranchType* mb;
     NodeType* nn;
     Vector vCheck = R_curr;
     mb = HideTrack.branch;
     for(i = 0;i < HideTrack.NumBranch;i++,mb++){
         if(R_curr.y > mb->Top && R_curr.y < mb->Bottom){
             pml = mb->Link;
             ml = pml + 1;
             for(j = 1;j < mb->NumLink;j++){
                 if(CheckInLink(vCheck,pml,ml) && ml->z < R_curr.z){
                     pBranch = mb;
                     pNextLink = ml;
                     pPrevLink = pml;
                     PointStatus = TRK_IN_BRANCH;
                     OtherFlag |= MECHOS_RECALC_FRONT;
                     return;
                 };
                 pml = ml;
                 ml++;
             };
         };
     };
     nn = HideTrack.node;
     for(i = 0;i < HideTrack.NumNode;i++,nn++){
         if(R_curr.y > nn->Top && R_curr.y < nn->Bottom){
             if(CheckInNode(vCheck,nn) && nn->z < R_curr.z){
                 pNode = nn;
                 PointStatus = TRK_IN_NODE;
                 OtherFlag |= MECHOS_RECALC_FRONT;
                 return;
             };
         };
     };
     PointStatus = TRK_OUT_BRANCH;
 };
References BranchType::Bottom, NodeType::Bottom, TrackType::branch, CheckInLink(), CheckInNode(), HideTrack, BranchType::Link, MECHOS_RECALC_FRONT, TrackType::node, TrackType::NumBranch, BranchType::NumLink, TrackType::NumNode, ActionUnit::OtherFlag, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, BranchType::Top, NodeType::Top, TRK_IN_BRANCH, TRK_IN_NODE, TRK_OUT_BRANCH, LinkType::z, and NodeType::z.
Referenced by GetBranch().
GetNode()
void TrackUnit::GetNode (TrackLinkType * tp, char & dir)
 {
     NodeType * n;
     BranchType* b;
     int cDist = 0,nn,td;
     int i;
     if(TargetPoint.PointStatus & TRK_BRANCH_MASK){
         if(tp->pNode == TargetPoint.pBranch->pBeg){
             tp->pBranch = TargetPoint.pBranch;
             tp->pPrevLink = TargetPoint.pBranch->Link;
             tp->pNextLink = tp->pPrevLink + 1;
             dir = 1;
             return;
         }else{
             if(tp->pNode == TargetPoint.pBranch->pEnd){
                 tp->pBranch = TargetPoint.pBranch;
                 tp->pNextLink = TargetPoint.pBranch->Link + TargetPoint.pBranch->NumLink - 1;
                 tp->pPrevLink = tp->pNextLink - 1;
                 dir = 0;
                 return;
             };
         };
     }else{
         n = tp->pNode;
         if(n == TargetPoint.pNode){
             dir = -1;
             return;
         };
         nn = -1;
         for(i = 0;i < n->NumBranch;i++){
             b = n->pBranches[i];
             if(n->Status[i]){
                 if(b->pEnd == TargetPoint.pNode){
                     nn = i;
                     break;
                 };
             }else{
                 if(b->pBeg == TargetPoint.pNode){
                     nn = i;
                     break;
                 };
             };
         };
         if(nn != -1){
             if(nn <= -1 || nn >= n->NumBranch) ErrH.Abort("Bad Short Way");
             tp->pBranch = n->pBranches[nn];
             if(n->Status[nn]){
                 tp->pPrevLink = tp->pBranch->Link;
                 tp->pNextLink = tp->pPrevLink + 1;
                 dir = 1;
             }else{
                 tp->pNextLink = tp->pBranch->Link + tp->pBranch->NumLink - 1;
                 tp->pPrevLink = tp->pNextLink - 1;
                 dir = 0;
             };
             return;
         };
     };
     n = tp->pNode;
     nn = -1;
     for(i = 0;i < n->NumWayNode;i++){
         td = WayDist[n->WayNodeIndex[i]] + TrackDist[n->WayBranchIndex[i]];
         if(td <= cDist || nn == -1){
             nn = i;
             cDist = td;
         };
     };
     tp->pBranch = &(HideTrack.branch[n->WayBranchIndex[nn]]);
     if(tp->pBranch->pBeg == n){
         tp->pPrevLink = tp->pBranch->Link;
         tp->pNextLink = tp->pPrevLink + 1;
         dir = 1;
     }else{
         if(tp->pBranch->pEnd == n){
             tp->pNextLink = tp->pBranch->Link + tp->pBranch->NumLink - 1;
             tp->pPrevLink = tp->pNextLink - 1;
             dir = 0;
         }else ErrH.Abort("Error make WayTable");
     };
 };
References XErrorHandler::Abort(), TrackType::branch, ErrH, HideTrack, BranchType::Link, NodeType::NumBranch, BranchType::NumLink, NodeType::NumWayNode, BranchType::pBeg, TrackLinkType::pBranch, NodeType::pBranches, BranchType::pEnd, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, NodeType::Status, TargetPoint, TrackDist, TRK_BRANCH_MASK, NodeType::WayBranchIndex, WayDist, and NodeType::WayNodeIndex.
Referenced by DirectQuant(), and GetDirect().
GetTrackVector()
void TrackUnit::GetTrackVector (void)
 {
     int tx,ty;
     Vector vCheck;
     vEnvir = vCheck = Vector(0,0,0);
     if(PointStatus & TRK_BRANCH_MASK){
         tx = (pPrevLink->x + pNextLink->x) >> 1;
         ty = (pPrevLink->y + pNextLink->y) >> 1;
         LinkDist(tx,ty,pPrevLink->xl,pPrevLink->yl,pNextLink->xl,pNextLink->yl,radius,vCheck);
         LinkDist(tx,ty,pNextLink->xr,pNextLink->yr,pPrevLink->xr,pPrevLink->yr,radius,vCheck);
         LinkDist(vPoint.x,vPoint.y,pPrevLink->xl,pPrevLink->yl,pNextLink->xl,pNextLink->yl,radius,vEnvir);
         LinkDist(vPoint.x,vPoint.y,pNextLink->xr,pNextLink->yr,pPrevLink->xr,pPrevLink->yr,radius,vEnvir);
         vEnvir -= vCheck;
 //      vEnvir /= 2;
     };
 };
References LinkDist(), TrackLinkType::pNextLink, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, Object::radius, TRK_BRANCH_MASK, ActionUnit::vEnvir, TrackLinkType::vPoint, Vector::x, LinkType::x, LinkType::xl, LinkType::xr, Vector::y, LinkType::y, LinkType::yl, and LinkType::yr.
Referenced by VangerUnit::Quant().
Hide2Show()
void TrackUnit::Hide2Show (void) virtual
Reimplemented from ActionUnit.
Reimplemented in VangerUnit.
 {
 /*  if(pBranch){
         if(pNextLink){
             if(pNextLink->Level == 1) set_3D(SET_3D_TO_THE_UPPER_LEVEL ,R_curr.x,R_curr.y,pNextLink->z,radius / 2,-Angle,Speed);
             else{
                 if(pNextLink->Level == 0) set_3D(SET_3D_TO_THE_LOWER_LEVEL,R_curr.x,R_curr.y,pNextLink->z,radius / 2,-Angle,Speed);
                 else ErrH.Abort("Bad Level");
             };
         }else ErrH.Abort("Bad Link in Hide2Show");
     }else{
         if(pNode){
             if(pNode->Level == 1) set_3D(SET_3D_TO_THE_UPPER_LEVEL ,R_curr.x,R_curr.y,pNode->z,radius / 2,-Angle,Speed);
             else{
                 if(pNode->Level == 0) set_3D(SET_3D_TO_THE_LOWER_LEVEL,R_curr.x,R_curr.y,pNode->z,radius / 2,-Angle,Speed);
                 else ErrH.Abort("Bad Level");
             };
         }else ErrH.Abort("Bad TrackInfo in Hide2Show");
     };*/
     if(pBranch){
         if(pNextLink) set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,pNextLink->z + zmax,0,-Angle,Speed);
 //      else ErrH.Abort("Bad Link in Hide2Show");
     }else{
         if(pNode) set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,pNode->z + zmax,0,-Angle,Speed);
 //      else ErrH.Abort("Bad TrackInfo in Hide2Show");
     };
 };
References ActionUnit::Angle, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, Object::set_3D(), SET_3D_DIRECT_PLACE, ActionUnit::Speed, LinkType::z, NodeType::z, and Object::zmax.
HideGetBranch()
void TrackUnit::HideGetBranch (void)
 {
     HideChangeLink(MoveDir);
 };
References TrackLinkType::HideChangeLink(), and MoveDir.
Init()
void TrackUnit::Init (StorageType * s)
 {
     ActionUnit::Init(s);
 };
References ActionUnit::Init().
Referenced by VangerUnit::Init().
LastFire()
void TrackUnit::LastFire (void)
MakeTrackDist()
void TrackUnit::MakeTrackDist (void)
 {
     int i;
     for(i = 0;i < HideTrack.NumBranch;i++)
         TrackDist[i] = HideTrack.branch[i].Len;
 };
References TrackType::branch, HideTrack, BranchType::Len, TrackType::NumBranch, and TrackDist.
Referenced by VangerUnit::InitAI().
MixVector()
void TrackUnit::MixVector (void)
 {
 //  vEnvir = vEnvir * EnvirReaction;
 //  vEnvir += vTarget * TargetReaction;
 //  vEnvir /= TOTAL_REACTION;
     if(NumCalcUnit) vEnvir += vTarget / NumCalcUnit;
     ActionUnit::MixVector();
 };
References ActionUnit::MixVector(), ActionUnit::NumCalcUnit, ActionUnit::vEnvir, and vTarget.
Referenced by VangerUnit::Action().
Open()
void TrackUnit::Open (void)
 {
     WayDistData = new int[HideTrack.NumNode * 2];
     TrackDist = new int[HideTrack.NumBranch];
 };
References HideTrack, TrackType::NumBranch, TrackType::NumNode, TrackDist, and WayDistData.
Quant()
void TrackUnit::Quant (void) virtual
Reimplemented from ActionUnit.
Reimplemented in VangerUnit.
 {
     int i;
     for(i = 0;i < n_wheels;i++) PrevWheelFlag[i] = 0;
     ActionUnit::Quant();
     vPoint = R_curr;
     cycleTor(vPoint.x,vPoint.y);
     for(i = 0;i < n_wheels;i++) if(!PrevWheelFlag[i]) PrevWheelY[i] = 0;
 //  if(!PrevWheelFlag[0]) PrevWheelY[0] = 0;
 //  if(!PrevWheelFlag[1]) PrevWheelY[1] = 0;
 };
References cycleTor(), Object::n_wheels, PrevWheelFlag, PrevWheelY, ActionUnit::Quant(), TrackLinkType::vPoint, Vector::x, and Vector::y.
Referenced by VangerUnit::Quant().
TestAnalysis()
char TrackUnit::TestAnalysis (TrackLinkType & tp)
 {
     char i;
     LinkType* lp;
     LinkType* ln;
     BranchType* b;
     tp.ChangeLink();
     switch(tp.PointStatus){
         case TRK_IN_NODE:
             if(CheckInNode(tp.vPoint,tp.pNode)) return 1;
             else{
                 for(i = 0;i < tp.pNode->NumBranch;i++){
                     b = tp.pNode->pBranches[i];
                     if(tp.pNode->Status[i]){
                         lp = b->Link;
                         ln = lp + 1;
                     }else{
                         ln = b->Link + b->NumLink - 1;
                         lp = ln - 1;
                     };
                     if(CheckInBranch(tp.vPoint,lp,ln,b)){
                         tp.pBranch = b;
                         tp.pPrevLink = lp;
                         tp.pNextLink = ln;
                         tp.PointStatus = TRK_IN_BRANCH;
                         return 1;
                     };
                 };
                 tp.PointStatus = TRK_OUT_NODE;
                 return 0;
             };
             break;
         case TRK_IN_BRANCH:
             return 1;
     };
     return 0;
 };
References TrackLinkType::ChangeLink(), CheckInBranch(), CheckInNode(), BranchType::Link, NodeType::NumBranch, BranchType::NumLink, TrackLinkType::pBranch, NodeType::pBranches, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, NodeType::Status, TRK_IN_BRANCH, TRK_IN_NODE, TRK_OUT_NODE, and TrackLinkType::vPoint.
Referenced by Check2Position().
TraceWay()
int TrackUnit::TraceWay (void)
 {
     NodeType* n;
     int* pdist;
     int td;
     int i,t;
     int j;
     int ff,fm;
     int nprocess;
     int* nInd;
     int* bInd;
     nprocess = 0;
     n = HideTrack.node;
     pdist = CalcWayDist;
     for(i = 0;i < HideTrack.NumNode;i++,n++,pdist++){
         if(n->NumBranch == 0) ErrH.Abort("Null Node");
         ff = 0;
         fm = 0xfffffff;
         nInd = n->WayNodeIndex;
         bInd = n->WayBranchIndex;
         for(j = 0;j < n->NumWayNode;j++,nInd++,bInd++){
             td = CalcWayDist[*nInd];
             if(td > 0){
                 ff++;
                 t = td + TrackDist[*bInd];
                 if(t < fm) fm = t;
             };
         };
         if(ff > 0 && (*pdist == 0 || *pdist > fm)){
             *pdist = fm;
             nprocess++;
         };
     };
     return nprocess;
 };
References XErrorHandler::Abort(), CalcWayDist, ErrH, HideTrack, TrackType::node, TrackType::NumNode, and TrackDist.
Referenced by VangerUnit::TargetAnalysis().
TrackQuant()
void TrackUnit::TrackQuant (void)
 {
     if((OtherFlag & MECHOS_RECALC_FRONT) && SpeedDir != 0){
         if(PointStatus & TRK_BRANCH_MASK){
             if(MoveDir){
                 if(pBranch->pBeg) pNode = pBranch->pBeg;
                 else{
                     if(pBranch->pEnd) pNode = pBranch->pEnd;
                     else ErrH.Abort("Bad Link to Node");
                 };
             }else{
                 if(pBranch->pEnd) pNode = pBranch->pEnd;
                 else{
                     if(pBranch->pBeg) pNode = pBranch->pBeg;
                     else ErrH.Abort("Bad Link to Node");
                 };
             };
             FrontPoint.PointStatus = TRK_IN_BRANCH;
             MoveDir = GetDirect(this);
         }else{
             pBranch = pNode->pBranches[0];
             if(pBranch->pBeg == pNode){
                 pPrevLink = pBranch->Link;
                 pNextLink = pPrevLink + 1;
                 MoveDir = 0;
             }else{
                 pNextLink = pBranch->Link + pBranch->NumLink - 1;
                 pPrevLink = pNextLink - 1;
                 MoveDir = 1;
             };
             FrontPoint.PointStatus = TRK_IN_NODE;
         };
         if(SpeedDir != 0) OtherFlag &= ~MECHOS_RECALC_FRONT;
     };
 };
References XErrorHandler::Abort(), ErrH, FrontPoint, GetDirect(), BranchType::Link, MECHOS_RECALC_FRONT, MoveDir, BranchType::NumLink, ActionUnit::OtherFlag, BranchType::pBeg, TrackLinkType::pBranch, NodeType::pBranches, BranchType::pEnd, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, ActionUnit::SpeedDir, TRK_BRANCH_MASK, TRK_IN_BRANCH, and TRK_IN_NODE.
Referenced by VangerUnit::TargetAnalysis().
WayInit()
void TrackUnit::WayInit (void)
 {
     int i;
     for(i = 0;i < HideTrack.NumNode;i++) CalcWayDist[i] = 0;
     if(OtherFlag & MECHOS_TARGET_MOVE){
         if(TargetPoint.PointStatus & TRK_BRANCH_MASK){
             if(TargetPoint.pBranch -> pBeg) CalcWayDist[TargetPoint.pBranch -> pBeg -> index] = 1;
             if(TargetPoint.pBranch -> pEnd) CalcWayDist[TargetPoint.pBranch -> pEnd -> index] = 1;
         }else CalcWayDist[TargetPoint.pNode -> index] = 1;
         OtherFlag |= MECHOS_CALC_WAY;
     };
 };
References CalcWayDist, HideTrack, MECHOS_CALC_WAY, MECHOS_TARGET_MOVE, TrackType::NumNode, ActionUnit::OtherFlag, TrackLinkType::pBranch, TrackLinkType::pNode, TrackLinkType::PointStatus, TargetPoint, and TRK_BRANCH_MASK.
Referenced by VangerUnit::NoWayHandler(), and VangerUnit::ResolveHandlerFind().
Member Data Documentation
aiMoveFunction
int TrackUnit::aiMoveFunction
Referenced by VangerUnit::Action(), VangerUnit::ChangeVangerProcess(), GunSlot::CheckTarget(), CreateTrackUnit(), and VangerUnit::UsingCopterig().
aiMoveMode
int TrackUnit::aiMoveMode
Referenced by VangerUnit::Action(), VangerUnit::CalcForce(), VangerUnit::CalcImpulse(), VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), VangerUnit::Hide2Show(), VangerUnit::NoWayHandler(), VangerUnit::Quant(), VangerUnit::ResolveFindDestroy(), VangerUnit::ResolveHandlerFind(), and VangerUnit::TargetAnalysis().
CalcWayDist
int* TrackUnit::CalcWayDist
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), VangerUnit::TargetAnalysis(), TraceWay(), and WayInit().
CheckPosition
int TrackUnit::CheckPosition
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), GetBranch(), and VangerUnit::Quant().
CheckWayCount
int TrackUnit::CheckWayCount
Referenced by VangerUnit::ChangeVangerProcess(), and CreateTrackUnit().
DestroyPhase
int TrackUnit::DestroyPhase
Referenced by CreateTrackUnit(), and VangerUnit::Destroy().
EnvirReaction
int TrackUnit::EnvirReaction
Referenced by VangerUnit::ChangeVangerProcess(), and CreateTrackUnit().
FrontDir
char TrackUnit::FrontDir
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), and DirectQuant().
FrontPoint
TrackLinkType TrackUnit::FrontPoint
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), DirectQuant(), VangerUnit::DrawQuant(), and TrackQuant().
gRnd
int TrackUnit::gRnd
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), and GeneralRND().
MaxCheckPosition
int TrackUnit::MaxCheckPosition
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), GetBranch(), and VangerUnit::Quant().
MaxWayCount
int TrackUnit::MaxWayCount
Referenced by VangerUnit::AddEvent(), VangerUnit::CalcAiFactor(), VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), VangerUnit::GamerOrderInit(), VangerUnit::MainOrderInit(), VangerUnit::ResolveGenerator(), and VangerUnit::ResolveHandlerFind().
MoveDir
char TrackUnit::MoveDir
Referenced by VangerUnit::CalcAiFactor(), VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), DirectQuant(), GetDirect(), VangerUnit::GetForceWay(), HideGetBranch(), VangerUnit::NoWayHandler(), VangerUnit::Quant(), and TrackQuant().
NoWayDirect
int TrackUnit::NoWayDirect
Referenced by VangerUnit::CalcAiFactor(), DirectQuant(), GetDirect(), VangerUnit::InitAI(), and VangerUnit::NoWayHandler().
NullTime
int TrackUnit::NullTime
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), DrawMechosParticle(), and VangerUnit::Quant().
PrevBranch
BranchType* TrackUnit::PrevBranch
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), and DirectQuant().
PrevWheelFlag
int TrackUnit::PrevWheelFlag[6]
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), DrawMechosParticle(), and Quant().
PrevWheelX
int TrackUnit::PrevWheelX[6]
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), and DrawMechosParticle().
PrevWheelY
int TrackUnit::PrevWheelY[6]
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), DrawMechosParticle(), and Quant().
TargetAngle
int TrackUnit::TargetAngle
Referenced by VangerUnit::ChangeVangerProcess(), and CreateTrackUnit().
TargetLen
int TrackUnit::TargetLen
Referenced by VangerUnit::ChangeVangerProcess(), and CreateTrackUnit().
TargetPoint
TrackLinkType TrackUnit::TargetPoint
Referenced by VangerUnit::Action(), VangerUnit::AddFindResolve(), VangerUnit::CalcForce(), VangerUnit::CalcImpulse(), VangerUnit::CheckReturn2Track(), DirectQuant(), GetNode(), VangerUnit::NoWayHandler(), VangerUnit::ResolveGenerator(), VangerUnit::ResolveHandlerFind(), VangerUnit::TargetAnalysis(), and WayInit().
TargetReaction
int TrackUnit::TargetReaction
Referenced by VangerUnit::ChangeVangerProcess(), and CreateTrackUnit().
TestPoint
TrackLinkType TrackUnit::TestPoint
Referenced by Check2Position().
TrackDist
int* TrackUnit::TrackDist
Referenced by Close(), GetNode(), MakeTrackDist(), VangerUnit::NoWayHandler(), Open(), and TraceWay().
vTarget
Vector TrackUnit::vTarget
Referenced by VangerUnit::ChangeVangerProcess(), CreateTrackUnit(), VangerUnit::DrawQuant(), VangerUnit::InitEnvironment(), and MixVector().
WayDist
int* TrackUnit::WayDist
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CheckNearTrack(), CreateTrackUnit(), GetNode(), and VangerUnit::TargetAnalysis().
WayDistData
int* TrackUnit::WayDistData
Referenced by VangerUnit::ChangeVangerProcess(), Close(), CreateTrackUnit(), and Open().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/hobj.cpp
src/units/mechos.cpp