Vangers: HordeSource Struct Reference
HordeSource Struct Reference
#include <items.h>
Public Member Functions
void Quant (void)
void DrawQuant (void)
void CreateSource (Vector v, int nModel, int r, int z)
void Touch (GeneralObject *p)
int test_objects_collision ()
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Attributes
int zHorde
int HordeRadius
int Time
int DataID
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Detailed Description
Member Function Documentation
CreateSource()
void HordeSource::CreateSource (Vector v, int nModel, int r, int z)
 {
     ID = ID_HORDE_SOURCE;
     Object::operator = (ModelD.ActiveModel(nModel));
     R_curr = v;
     cycleTor(R_curr.x,R_curr.y);
     GetVisible();
     set_active(0);
     switch_analysis(1);
     Status = 0;
     set_body_color(COLORS_IDS::BODY_RED);
     set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,0);
     HordeRadius =  r;
     zHorde = z;
     Time = 0;
     DataID = nModel;
 };
References ModelDispatcher::ActiveModel(), COLORS_IDS::BODY_RED, cycleTor(), DataID, HordeRadius, Object::ID, ID_HORDE_SOURCE, ModelD, Object::operator=(), Object::set_3D(), SET_3D_DIRECT_PLACE, Object::set_active(), Object::set_body_color(), Object::switch_analysis(), Time, and zHorde.
DrawQuant()
void HordeSource::DrawQuant (void)
 {
     if(Status & SOBJ_DISCONNECT) return;
 //  draw();
     scale_size = original_scale_size + original_scale_size*Sin(Time) / 8.;
     pixel_draw();
 };
References Object::original_scale_size, Object::pixel_draw(), Object::scale_size, Sin(), SOBJ_DISCONNECT, and Time.
Quant()
void HordeSource::Quant (void)
 {
     if(Status & SOBJ_DISCONNECT) return;
     GetVisible();
     if(Visibility == VISIBLE) analysis();
     Time = rPI(Time + PI / 8);
 };
References Object::analysis(), PI, rPI, SOBJ_DISCONNECT, Time, and VISIBLE.
test_objects_collision()
int HordeSource::test_objects_collision () virtual
Reimplemented from Object.
 {
     BaseObject* p;
     p = (BaseObject*)(BulletD.Tail);
     while(p){
 //      if(p->ID != ID_BULLET)
 //          ErrH.Abort("Bad Bullet List");
         if(p->Visibility == VISIBLE)
             test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)(JumpD.Tail);
     while(p){
 //      if(p->ID != ID_JUMPBALL)
 //          ErrH.Abort("Bad JumpBall List");
         if(p->Visibility == VISIBLE)
             test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     return 0;
 };
References BulletD, JumpD, GeneralObject::NextTypeList, UnitListType::Tail, Object::test_object_to_baseobject(), BaseObject::Visibility, and VISIBLE.
Touch()
void HordeSource::Touch (GeneralObject * p)
 {
     if(Status & SOBJ_DISCONNECT) return;
     switch(p->ID){
         case ID_VANGER:
         case ID_BULLET:
         case ID_JUMPBALL:
 //          EffD.CreateExplosion(R_curr + Vector(0,0,radius),EFF_EXPLOSION01,this,1 << 15,0);
             if(p->Status & SOBJ_ACTIVE)
                 uvsCheckKronIventTabuTask(UVS_KRON_EVENT::HIVE,1);
             Status |= SOBJ_DISCONNECT;
             break;
     };
 };
References UVS_KRON_EVENT::HIVE, GeneralObject::ID, ID_BULLET, ID_JUMPBALL, ID_VANGER, SOBJ_ACTIVE, SOBJ_DISCONNECT, GeneralObject::Status, and uvsCheckKronIventTabuTask().
Member Data Documentation
DataID
int HordeSource::DataID
Referenced by CreateSource().
HordeRadius
int HordeSource::HordeRadius
Referenced by CreateSource().
Time
int HordeSource::Time
Referenced by CreateSource(), DrawQuant(), and Quant().
zHorde
int HordeSource::zHorde
Referenced by CreateSource().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp