Vangers: aiMessageList Struct Reference
aiMessageList Struct Reference
#include <hobj.h>
Public Member Functions
void Open (void)
void Close (void)
void Send (int ind, int speed=0, int n=0xff, int sf=1)
void Quant (void)
void Connect (aiMessageListElem *p)
void Disconnect (aiMessageListElem *p)
void SendDominance (int dom)
void SendLuck (int luck)
void SendTabuTask (int luck)
Public Attributes
int Num
aiMessageListElem * Tail
aiMessageListElem * View
int Time
Detailed Description
Member Function Documentation
Close()
void aiMessageList::Close (void)
 {
     aiMessageListElem* p;
     aiMessageListElem* pp;
     p = Tail;
     while(p){
         pp = p->Next;
         Disconnect(p);
         delete p;
         p = pp;
     };
 };
References Disconnect(), aiMessageListElem::Next, and Tail.
Referenced by GeneralSystemFree().
Connect()
void aiMessageList::Connect (aiMessageListElem * p)
 {
     if(!Tail){
         p->Next = p->Prev = NULL;
         Tail = p;
     }else{
         Tail -> Prev = p;
         p -> Next = Tail;
         p -> Prev = NULL;
         Tail = p;
     };
     Num++;
 };
References aiMessageListElem::Next, NULL, Num, aiMessageListElem::Prev, and Tail.
Referenced by Send(), SendDominance(), SendLuck(), and SendTabuTask().
Disconnect()
void aiMessageList::Disconnect (aiMessageListElem * p)
 {
     if((!p->Prev) && (!p->Next)) Tail = NULL;
     else{
         if(p->Prev) p->Prev->Next = p->Next;
         else Tail = p->Next;
         if(p->Next) p->Next->Prev = p->Prev;
     };
     Num--;
 };
References aiMessageListElem::Next, NULL, Num, aiMessageListElem::Prev, and Tail.
Referenced by Close(), and Quant().
Open()
void aiMessageList::Open (void)
 {
     Time = Num = 0;
     View = Tail = NULL;
 };
References NULL, Num, Tail, Time, and View.
Referenced by GeneralSystemInit().
Quant()
void aiMessageList::Quant (void)
 {
     aiMessageListElem* p;
     if(View){
         if(Time > 0){
             Time--;
         }else{
             p = View->Prev;
             Disconnect(View);
             delete View;
             if(p){
                 switch(p->Index){
                     case AI_MESSAGE_INDEX_LUCK:
                         aiPromptLuckMessage(p->Luck);
                         Time = 70;
                         break;
                     case AI_MESSAGE_INDEX_DOMINANCE:
                         aiPromptDominanceMessage(p->Dominance);
                         Time = 50;
                         break;
                     case AI_MESSAGE_INDEX_TABUTASK:
                         aiPromptTaskMessage(p->TabuTask);
                         Time = 50;
                         break;
                     default:
                         aiMessageData[p->Index].Send(p->Speed,p->Mask,0);
                         Time = aiMessageData[p->Index].GetTime(p->Mask) / 2 + 10;
                         break;
                 };
             };
             View = p;
         };
     }else{
         if(Tail){
             View = Tail;
             switch(View->Index){
                 case AI_MESSAGE_INDEX_LUCK:
                     aiPromptLuckMessage(View->Luck);
                     Time = 70;
                     break;
                 case AI_MESSAGE_INDEX_DOMINANCE:
                     aiPromptDominanceMessage(View->Dominance);
                     Time = 50;
                     break;
                 case AI_MESSAGE_INDEX_TABUTASK:
                     aiPromptTaskMessage(View->TabuTask);
                     Time = 50;
                     break;
                 default:
                     aiMessageData[View->Index].Send(View->Speed,View->Mask,0);
                     Time = aiMessageData[View->Index].GetTime(View->Mask) / 2 + 10;
                     break;
             };
         };
     };
 };
References AI_MESSAGE_INDEX_DOMINANCE, AI_MESSAGE_INDEX_LUCK, AI_MESSAGE_INDEX_TABUTASK, aiMessageData, aiPromptDominanceMessage(), aiPromptLuckMessage(), aiPromptTaskMessage(), Disconnect(), aiMessageListElem::Dominance, aiMessageType::GetTime(), aiMessageListElem::Index, aiMessageListElem::Luck, aiMessageListElem::Mask, aiMessageListElem::Prev, aiMessageType::Send(), aiMessageListElem::Speed, aiMessageListElem::TabuTask, Tail, Time, and View.
Referenced by GameObjectDispatcher::Quant().
Send()
void aiMessageList::Send (int ind, int speed = 0, int n = 0xff, int sf = 1)
 {
     aiMessageListElem* p;
     static int PrevSpeed = 0;
     if(!ActD.Active || !(ActD.Active->ExternalDraw)) return;
     if(abs(speed) != 0) PrevSpeed = 10;
     else PrevSpeed--;
     if(sf && PrevSpeed > MAX_AI_MESSAGE_SPEED) return;
     if(abs(aiMessageData[ind].LastFrame - frame) > AI_MESSAGE_DELTA){
         p = Tail;
         while(p){
             if(p->Index == ind) return;
             p = p->Next;
         };
         p = new aiMessageListElem;
         p->Speed = speed;
         p->Mask = n;
         p->SpeedFlag = sf;
         p->Index = ind;
         p->Luck = 0;
         p->Dominance = 0;
         p->TabuTask = 0;
         Connect(p);
 /*      if(!View){
             View = p;
             aiMessageData[p->Index].Send(p->Speed,p->Mask,0);
             Time = aiMessageData[p->Index].GetTime(p->Mask) / 2 + 2;
         };*/
     };
     aiMessageData[ind].LastFrame = frame;
 };
References ActD, ActionDispatcher::Active, AI_MESSAGE_DELTA, aiMessageData, Connect(), aiMessageListElem::Dominance, VangerUnit::ExternalDraw, frame, aiMessageListElem::Index, aiMessageType::LastFrame, aiMessageListElem::Luck, aiMessageListElem::Mask, MAX_AI_MESSAGE_SPEED, aiMessageListElem::Next, aiMessageListElem::Speed, aiMessageListElem::SpeedFlag, aiMessageListElem::TabuTask, and Tail.
Referenced by aciSendEvent2itmdsp(), aiMessageTouch(), ChargeDevice(), ChargeWeapon(), VangerUnit::CheckOutDevice(), IncomingChatMessage(), VangerUnit::InitEnvironment(), VangerUnit::NewKeyHandler(), ActionDispatcher::PromptChangeCycle(), ActionDispatcher::PromptQuant(), VangerUnit::TouchSensor(), and uvsapiDestroyItem().
SendDominance()
void aiMessageList::SendDominance (int dom)
 {
     aiMessageListElem* p;
 //  if(!ActD.Active || !(ActD.Active->ExternalDraw)) return;
     p = Tail;
     while(p){
         if(p->Index == AI_MESSAGE_INDEX_DOMINANCE && p != View){
             p->Dominance += dom;
             return;
         };
         p = p->Next;
     };
     p = new aiMessageListElem;
     p->Speed = 0;
     p->Mask = 0;
     p->SpeedFlag = 0;
     p->Index = AI_MESSAGE_INDEX_DOMINANCE;
     p->Luck = 0;
     p->Dominance = dom;
     p->TabuTask = 0;
     Connect(p);
 /*  if(!View){
         View = p;
         aiPromptShowDominanceMessage(p->Dominance);
         Time = 100;
     };*/
 };
References AI_MESSAGE_INDEX_DOMINANCE, Connect(), aiMessageListElem::Dominance, aiMessageListElem::Index, aiMessageListElem::Luck, aiMessageListElem::Mask, aiMessageListElem::Next, aiMessageListElem::Speed, aiMessageListElem::SpeedFlag, aiMessageListElem::TabuTask, Tail, and View.
Referenced by ShowDominanceMessage().
SendLuck()
void aiMessageList::SendLuck (int luck)
 {
     aiMessageListElem* p;
 //  if(!ActD.Active || !(ActD.Active->ExternalDraw)) return;
     p = Tail;
     while(p){
         if(p->Index == AI_MESSAGE_INDEX_LUCK && p != View){
             p->Luck += luck;
             return;
         };
         p = p->Next;
     };
     p = new aiMessageListElem;
     p->Speed = 0;
     p->Mask = 0;
     p->SpeedFlag = 0;
     p->Index = AI_MESSAGE_INDEX_LUCK;
     p->Luck = luck;
     p->Dominance = 0;
     p->TabuTask = 0;
     Connect(p);
 /*  if(!View){
         View = p;
         aiPromptShowLuckMessage(p->Luck);
         Time = 100;
     };*/
 };
References AI_MESSAGE_INDEX_LUCK, Connect(), aiMessageListElem::Dominance, aiMessageListElem::Index, aiMessageListElem::Luck, aiMessageListElem::Mask, aiMessageListElem::Next, aiMessageListElem::Speed, aiMessageListElem::SpeedFlag, aiMessageListElem::TabuTask, Tail, and View.
Referenced by ShowLuckMessage().
SendTabuTask()
void aiMessageList::SendTabuTask (int luck)
 {
     aiMessageListElem* p;
     p = Tail;
     while(p){
         if(p->Index == AI_MESSAGE_INDEX_TABUTASK && p != View){
             p->TabuTask += luck;
             return;
         };
         p = p->Next;
     };
     p = new aiMessageListElem;
     p->Speed = 0;
     p->Mask = 0;
     p->SpeedFlag = 0;
     p->Index = AI_MESSAGE_INDEX_TABUTASK;
     p->Luck = 0;
     p->Dominance = 0;
     p->TabuTask = luck;
     Connect(p);
 /*  if(!View){
         View = p;
         aiPromptShowTaskMessage(p->TabuTask);
         Time = 100;
     };*/
 };
References AI_MESSAGE_INDEX_TABUTASK, Connect(), aiMessageListElem::Dominance, aiMessageListElem::Index, aiMessageListElem::Luck, aiMessageListElem::Mask, aiMessageListElem::Next, aiMessageListElem::Speed, aiMessageListElem::SpeedFlag, aiMessageListElem::TabuTask, Tail, and View.
Referenced by ShowTaskMessage().
Member Data Documentation
Num
int aiMessageList::Num
Referenced by Connect(), Disconnect(), and Open().
Tail
aiMessageListElem* aiMessageList::Tail
Referenced by Close(), Connect(), Disconnect(), Open(), Quant(), Send(), SendDominance(), SendLuck(), and SendTabuTask().
Time
int aiMessageList::Time
Referenced by Open(), and Quant().
View
aiMessageListElem* aiMessageList::View
Referenced by Open(), Quant(), SendDominance(), SendLuck(), and SendTabuTask().
The documentation for this struct was generated from the following files:
src/units/hobj.h
src/units/hobj.cpp