Vangers: ShowImageRTO Struct Reference
ShowImageRTO Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
virtual void Finit (void)
void SetNumFiles (int num)
void SetName (const char *p, int id=0)
void SetFlag (int id, int fl)
void DropFlag (int id, int fl)
ShowImageRTO (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Public Attributes
int count
int numFiles
int curFile
int * Flags
char ** fileNames
int imageSX
int imageSY
char * imageData
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
ShowImageRTO()
ShowImageRTO::ShowImageRTO (void)
 {
     int i;
     ID = RTO_SHOW_IMAGE_ID;
     Timer = RTO_IMAGE_TIMER;
     numFiles = 0;
     imageData = NULL;
     Flags = new int[RTO_SHOW_IMAGE_MAX];
     memset(Flags,0,sizeof(int) * RTO_SHOW_IMAGE_MAX);
     fileNames = new char*[RTO_SHOW_IMAGE_MAX];
     for(i = 0; i < RTO_SHOW_IMAGE_MAX; i ++)
         fileNames[i] = new char[256];
 }
References fileNames, Flags, XRuntimeObject::ID, imageData, NULL, numFiles, RTO_IMAGE_TIMER, RTO_SHOW_IMAGE_ID, RTO_SHOW_IMAGE_MAX, and XRuntimeObject::Timer.
Member Function Documentation
DropFlag()
void ShowImageRTO::DropFlag (int id, int fl) inline
 { Flags[id] &= ~fl; }
References Flags.
Finit()
void ShowImageRTO::Finit (void) virtual
Reimplemented from XRuntimeObject.
Reimplemented in ShowAviRTO.
 {
 #ifdef SHOW_IMAGES
     char* pal;
     pal = new char[768];
     i_slake_pal((unsigned char*)pal,32);
     delete[] pal;
     if(imageData) delete imageData;
 #endif
 _MEM_STATISTIC_("AFTER SHOW IMAGE RTO 4 FINIT -> ");
 }
References _MEM_STATISTIC_, i_slake_pal(), and imageData.
Init()
void ShowImageRTO::Init (int id) virtual
Reimplemented from XRuntimeObject.
Reimplemented in ShowAviRTO.
 {
 #ifdef SHOW_IMAGES
     int i;
     short sx,sy;
     XStream fh(0);
     XBuffer* XBuf = new XBuffer(1024);
     unsigned char* buf;
     char* pname;
     //NEED SEE
     set_key_nadlers(&ShowImageKeyPress, NULL);
     XGR_MouseSetPressHandler(XGM_LEFT_BUTTON, ShowImageMousePress);
     XGR_MouseSetPressHandler(XGM_RIGHT_BUTTON, ShowImageMousePress);
     XBuf -> init();
     if(!(Flags[curFile] & IMG_RTO_NO_IMAGE)){
         if(Flags[curFile] & IMG_RTO_CD_IMAGE){
             *XBuf < iVideoPathDefault < fileNames[curFile];
             if(!fh.open(XBuf -> address(),XS_IN)){
                 XBuf -> init();
                 *XBuf < iVideoPath < fileNames[curFile];
                 if(!fh.open(XBuf -> address(),XS_IN)){
                     Flags[curFile] |= IMG_RTO_NO_IMAGE;
                 }
                 else
                     fh.close();
             }
             else
                 fh.close();
         }
         else
             *XBuf < fileNames[curFile];
     }
     pname = strdup(XBuf -> address());
     memcpy(pname + strlen(pname) - 3,"pal",3);
     char* pal = new char[768];
     char* tpal = new char[768];
     memset(tpal,0,768);
     XStream ff(pname,XS_IN);
     ff.read(pal,768);
     ff.close();
     XGR_SetPal(tpal,0,255);
     if(!(Flags[curFile] & IMG_RTO_NO_IMAGE)){
         ff.open(XBuf -> address(),XS_IN);
         ff > sx > sy;
         if(!(Flags[curFile] & IMG_RTO_KEEP_IMAGE)){
             for(i = 0; i < sy; i ++){
                 buf = XGR_GetVideoLine(i);
                 ff.read(buf,sx);
             }
             imageData = NULL;
         }
         else {
             imageSX = sx;
             imageSY = sy;
             imageData = new char[sx * sy];
             ff.read(imageData,sx * sy);
             XGR_PutSpr(0,0,sx,sy,imageData,XGR_BLACK_FON);
         }
         ff.close();
     }
     else {
         XGR_Fill(0);
     }
     XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     PalEvidence(tpal,pal);
     count = CLOCK();
     delete[] pal;
     delete[] tpal;
     free(pname);
     delete XBuf;
     ShowImageMouseFlag = 0;
     ShowImageKeyFlag = 0;
     switch(GameOverTrigger){
         case GAME_OVER_EXPLOSION:
             LastStartWTRACK(ST_GAMEOVER);
             break;
         case GAME_OVER_INFERNAL_LOCKED:
             LastStartWTRACK(ST_THEEND);
             break;
         case GAME_OVER_SPOBS_LOCKED:
             LastStartWTRACK(ST_THEEND);
             break;
         case GAME_OVER_ALL_LOCKED:
             LastStartWTRACK(ST_THEEND_DOUBLE);
             break;
         case GAME_OVER_LUCKY:
             LastStartWTRACK(ST_INTRO);
             break;
         case GAME_OVER_LAMPASSO:
             LastStartWTRACK(ST_GAMEOVER);
             break;
         case GAME_OVER_ABORT:
             LastStartWTRACK(ST_INTRO);
             break;
         case GAME_OVER_NETWORK:
             break;
         }
     GameOverTrigger = -1;
 #endif
 _MEM_STATISTIC_("AFTER SHOW IMAGE RTO INIT -> ");
 }
References _MEM_STATISTIC_, CLOCK, XStream::close(), count, curFile, fileNames, Flags, GAME_OVER_ABORT, GAME_OVER_ALL_LOCKED, GAME_OVER_EXPLOSION, GAME_OVER_INFERNAL_LOCKED, GAME_OVER_LAMPASSO, GAME_OVER_LUCKY, GAME_OVER_NETWORK, GAME_OVER_SPOBS_LOCKED, GameOverTrigger, imageData, imageSX, imageSY, IMG_RTO_CD_IMAGE, IMG_RTO_KEEP_IMAGE, IMG_RTO_NO_IMAGE, iVideoPath, iVideoPathDefault, LastStartWTRACK(), NULL, XStream::open(), PalEvidence(), XStream::read(), set_key_nadlers(), ShowImageKeyFlag, ShowImageKeyPress(), ShowImageMouseFlag, ShowImageMousePress(), ST_GAMEOVER, ST_INTRO, ST_THEEND, ST_THEEND_DOUBLE, XGM_LEFT_BUTTON, XGM_RIGHT_BUTTON, XGR_BLACK_FON, XGR_Fill, XGR_Flush, XGR_GetVideoLine(), XGR_MAXX, XGR_MAXY, XGR_MouseSetPressHandler, XGR_PutSpr, XGR_SetPal, and XS_IN.
Quant()
int ShowImageRTO::Quant (void) virtual
Reimplemented from XRuntimeObject.
Reimplemented in ShowAviRTO.
 {
     int ret_flag = 1;
 #ifdef SHOW_IMAGES
     LastSoundQuant();
     if(Flags[curFile] & IMG_RTO_SHOW_TEXT){
         ret_flag = aciTextQuant();
     }
     else {
         if(!(Flags[curFile & IMG_RTO_CDTRACK_TIME])){
             if((count + 10000) > CLOCK()){
                 ret_flag = 0;
             }
         }
         else
             ret_flag = 0;
         if(ShowImageKeyFlag || ShowImageMouseFlag){
             ret_flag = 1;
         }
     }
 #endif
     if(ret_flag){
         curFile ++;
         if(curFile >= numFiles)
             return NextID;
     }
     else {
         return 0;
     }
     return ID;
 }
References aciTextQuant(), CLOCK, count, curFile, Flags, XRuntimeObject::ID, IMG_RTO_CDTRACK_TIME, IMG_RTO_SHOW_TEXT, LastSoundQuant(), BaseRTO::NextID, numFiles, ShowImageKeyFlag, and ShowImageMouseFlag.
SetFlag()
void ShowImageRTO::SetFlag (int id, int fl) inline
 { Flags[id] |= fl; }
References Flags.
SetName()
void ShowImageRTO::SetName (const char * p, int id = 0) inline
 { strcpy(fileNames[id],p); count = 0; Flags[id] = 0; }
References count, fileNames, and Flags.
Referenced by xtInitApplication().
SetNumFiles()
void ShowImageRTO::SetNumFiles (int num) inline
 { numFiles = num; curFile = 0; }
References curFile, and numFiles.
Referenced by xtInitApplication().
Member Data Documentation
count
int ShowImageRTO::count
Referenced by Init(), Quant(), and SetName().
curFile
int ShowImageRTO::curFile
Referenced by Init(), Quant(), ShowAviRTO::Quant(), and SetNumFiles().
fileNames
char** ShowImageRTO::fileNames
Referenced by Init(), SetName(), and ShowImageRTO().
Flags
int* ShowImageRTO::Flags
Referenced by DropFlag(), Init(), Quant(), SetFlag(), SetName(), and ShowImageRTO().
imageData
char* ShowImageRTO::imageData
Referenced by Finit(), Init(), and ShowImageRTO().
imageSX
int ShowImageRTO::imageSX
Referenced by Init().
imageSY
int ShowImageRTO::imageSY
Referenced by Init().
numFiles
int ShowImageRTO::numFiles
Referenced by Quant(), ShowAviRTO::Quant(), SetNumFiles(), and ShowImageRTO().
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp