Vangers: BulletObject Struct Reference
BulletObject Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void Quant (void)
void DrawQuant (void)
void Touch (GeneralObject *p)
void Event (int type)
void CreateBullet (GunSlot *p, WorldBulletTemplate *n)
void CreateBullet (Vector fv, Vector tv, GeneralObject *target, WorldBulletTemplate *p, GeneralObject *_Owner=NULL, int _speed=0)
void TimeOutQuant (void)
Public Member Functions inherited from BaseObject
BaseObject ()
Public Attributes
Vector vDelta
Vector vTarget
GeneralObject * TargetObject
int FrameCount
GeneralObject * Owner
Vector vTail
LightPoint * LightData
Vector vWallTarget
int DataID
Public Attributes inherited from BaseObject
Vector R_prev
int x_of_last_update
int y_of_last_update
int dynamic_state
int Visibility
int MapLevel
int ez
int radius
BaseObject * NextBaseList
BaseObject * PrevBaseList
BaseObject * NextViewList
BaseObject * PrevViewList
Public Attributes inherited from GeneralObject
int ID
int NetID
int Status
Vector R_curr
StorageType * Storage
StorageClusterType * Cluster
MemoryStorageType * ObjectHeap
GeneralObject * NextTypeList
GeneralObject * PrevTypeList
Public Attributes inherited from BulletControlType
int BulletID
int ShowID
int TargetMode
int BulletMode
int ShowType
int ExtShowType
int Power
int DeltaPower
int Speed
int Precision
int Time
int CraterType
int AltOffset
int BulletScale
Detailed Description
Member Function Documentation
CreateBullet() [1/2]
void BulletObject::CreateBullet (GunSlot * p, WorldBulletTemplate * n)
 {
     int d;
     R_prev = R_curr = p->vFire;
     Status = 0;
     GetVisible();
     Time = n->LifeTime;
     Power = n->Power;
     DeltaPower = n->DeltaPower;
     radius = n->BulletRadius;
     TargetObject = p->TargetObject;
     BulletID = n->BulletID;
     ShowID = n->ShowID;
     ShowType = n->ShowType;
     ExtShowType = n->ExtShowType;
     TargetMode = n->TargetMode;
     BulletMode = n->BulletMode;
     Precision = n->Precision;
     CraterType = n->CraterType;
     BulletScale = n->BulletScale;
     vTail = R_curr;
     vDelta = vTarget = Vector(0,0,0);
     FrameCount = 0;
 //  OwnerTouchFlag = BULLET_OWNER_TOUCH | BULLET_OWNER_CHECK;
     Speed = n->Speed;
     if(BulletMode & BULLET_CONTROL_MODE::SPEED) Speed += p->RealSpeed;
     if(BulletID == BULLET_TYPE_ID::LASER)
         vDelta = Vector(Speed,3 - RND(6),0)*p->mFire;
     else
         vDelta = Vector(Speed,0,0)*p->mFire;
     if(TargetObject && (BulletMode & BULLET_CONTROL_MODE::AIM)){
         vDelta = Vector(getDistX(TargetObject->R_curr.x,R_curr.x),getDistY(TargetObject->R_curr.y,R_curr.y),TargetObject->R_curr.z - R_curr.z);
         d = vDelta.vabs();
         vDelta = vDelta * Speed / vDelta.vabs();
     };
     if(CurrentWorld == WORLD_KHOX)
         BulletScale >>= 1;
     AltOffset = n->AltOffset;
     vWallTarget = R_curr;
     DataID = n->ID;
     LightData = NULL;
 };
References BULLET_CONTROL_MODE::AIM, BulletControlType::AltOffset, BulletControlType::BulletID, BulletControlType::BulletMode, WorldBulletTemplate::BulletRadius, BulletControlType::BulletScale, BulletControlType::CraterType, CurrentWorld, DataID, BulletControlType::DeltaPower, BulletControlType::ExtShowType, FrameCount, getDistX(), getDistY(), WorldBulletTemplate::ID, BULLET_TYPE_ID::LASER, WorldBulletTemplate::LifeTime, LightData, GunSlot::mFire, NULL, BulletControlType::Power, BulletControlType::Precision, GeneralObject::R_curr, BaseObject::R_prev, BaseObject::radius, GunSlot::RealSpeed, RND(), BulletControlType::ShowID, BulletControlType::ShowType, BULLET_CONTROL_MODE::SPEED, BulletControlType::Speed, GeneralObject::Status, BulletControlType::TargetMode, TargetObject, GunSlot::TargetObject, BulletControlType::Time, Vector::vabs(), vDelta, GunSlot::vFire, vTail, vTarget, vWallTarget, WORLD_KHOX, Vector::x, Vector::y, and Vector::z.
Referenced by DangerDataType::FireWork(), TntCreature::NetQuant(), GunSlot::Quant(), VangerFunctionType::Quant(), and TntCreature::Quant().
CreateBullet() [2/2]
void BulletObject::CreateBullet (Vector fv, Vector tv, GeneralObject * target, WorldBulletTemplate * p, GeneralObject * _Owner = NULL, int _speed = 0)
 {
     int d;
     R_prev = R_curr = fv;
     Status = 0;
     GetVisible();
     Owner = _Owner;
     R_curr.z += p->AltOffset;
     Time = p->LifeTime;
     Power = p->Power;
     DeltaPower = p->DeltaPower;
     radius = 1;
     TargetObject = target;
     BulletID = p->BulletID;
     ShowID = p->ShowID;
     ShowType = p->ShowType;
     ExtShowType = p->ExtShowType;
     TargetMode = p->TargetMode;
     BulletMode = p->BulletMode;
     Precision = p->Precision;
     CraterType = p->CraterType;
     vTail = R_curr;
     vDelta = vTarget = Vector(0,0,0);
     FrameCount = 0;
 //  OwnerTouchFlag = BULLET_OWNER_TOUCH | BULLET_OWNER_CHECK;
     Speed = p->Speed + _speed;
     BulletScale = p->BulletScale;
     AltOffset = p->AltOffset;
     vWallTarget = tv;
     LightData = NULL;
 //  if(BulletMode & BULLET_CONTROL_MODE::AIM){
         vDelta = Vector(getDistX(tv.x,R_curr.x),getDistY(tv.y,R_curr.y),tv.z - R_curr.z);
         d = vDelta.vabs();
         vDelta = vDelta * Speed / vDelta.vabs();
 //  };
     DataID = p->ID;
  };
References BulletControlType::AltOffset, BulletControlType::BulletID, BulletControlType::BulletMode, BulletControlType::BulletScale, BulletControlType::CraterType, DataID, BulletControlType::DeltaPower, BulletControlType::ExtShowType, FrameCount, getDistX(), getDistY(), WorldBulletTemplate::ID, WorldBulletTemplate::LifeTime, LightData, NULL, Owner, BulletControlType::Power, BulletControlType::Precision, GeneralObject::R_curr, BaseObject::R_prev, BaseObject::radius, BulletControlType::ShowID, BulletControlType::ShowType, BulletControlType::Speed, GeneralObject::Status, BulletControlType::TargetMode, TargetObject, BulletControlType::Time, Vector::vabs(), vDelta, vTail, vTarget, vWallTarget, Vector::x, Vector::y, and Vector::z.
DrawQuant()
void BulletObject::DrawQuant (void)
!!!!!!!!
 {
     int tx,ty,s;
     Vector vCheck;
     switch(ShowID){
         case BULLET_SHOW_TYPE_ID::PARTICLE:
             EffD.CreateParticle(ExtShowType,R_prev,R_curr,ShowType);
             if(BulletScale)
                 EffD.CreateParticle(ExtShowType,R_prev,R_curr,ShowType);
             break;
         case BULLET_SHOW_TYPE_ID::FIREBALL:
             if(AdvancedView) s = G2LF(R_curr.x,R_curr.y,R_curr.z,tx,ty);
             else s = G2LS(R_curr.x,R_curr.y,R_curr.z,tx,ty);
             s *= BulletScale;
             EffD.FireBallData[ShowType].Show(tx,ty,R_curr.z,s,FrameCount);
             EffD.FireBallData[ShowType].CheckOut(FrameCount);
             if(LightData)
                 LightData->set_position(XCYCL(R_curr.x + vDelta.x),YCYCL(R_curr.y + vDelta.y),R_curr.z);
             else
                 LightData = MapD.CreateLight(R_curr.x,R_curr.y,R_curr.z,40,32,LIGHT_TYPE::DYNAMIC);
             break;
         case BULLET_SHOW_TYPE_ID::DEFORM:
             if(AdvancedView) s = G2LF(R_curr.x,R_curr.y,R_curr.z,tx,ty);
             else s = G2LS(R_curr.x,R_curr.y,R_curr.z,tx,ty);
             if(EffD.DeformData[ShowType].CheckOffset(FrameCount)) FrameCount = 0;
             EffD.DeformData[ShowType].Deform(tx,ty,FrameCount,1);
             break;
         case BULLET_SHOW_TYPE_ID::DUST:
             MapD.CreateDust(Vector(R_curr.x,R_curr.y,MapLevel),ShowType);
             break;
         case BULLET_SHOW_TYPE_ID::CRATER:
             if(MapLevel && (vDelta.x != 0 || vDelta.y != 0 || vDelta.z != 0)){
                 if(ExtShowType){
                     if(BulletScale){
                         if(LightData)
                             LightData->set_position(R_prev.x,R_prev.y,R_prev.z + 63);
                         else
                             LightData = MapD.CreateLight(R_curr.x,R_curr.y,R_curr.z,20,32,LIGHT_TYPE::STATIC);
                         MapD.CreateLavaSpot(R_curr,5,5,20,10,0,0,1,8,83,0,4,1,ExtShowType);
                     }else MapD.CreateLavaSpot(R_curr,5,2,10,7,0,0,2,7,83,0,4,1,ExtShowType);
                 }else MapD.CreateLavaSpot(R_curr,5,2,10,7,0,0,2,7,83,0,4,1,83);
             };
             break;
         case BULLET_SHOW_TYPE_ID::LASER:
             vCheck = Vector(getDistX(R_prev.x,R_curr.x),getDistY(R_prev.y,R_curr.y),R_prev.z - R_curr.z);
             vCheck.x = 2*vCheck.x / 3;
             vCheck.y = 2*vCheck.y / 3;
             vCheck.z = 2*vCheck.z / 3;
             vCheck += R_curr;
             cycleTor(vCheck.x,vCheck.y);
             ScreenLineTrace(R_curr,vCheck,FireColorTable,0);
             break;
     };
     R_prev = vTail;
 };
References AdvancedView, BulletControlType::BulletScale, WaveProcess::CheckOffset(), FireBallProcess::CheckOut(), BULLET_SHOW_TYPE_ID::CRATER, EffectDispatcher::CreateParticle(), cycleTor(), WaveProcess::Deform(), BULLET_SHOW_TYPE_ID::DEFORM, EffectDispatcher::DeformData, BULLET_SHOW_TYPE_ID::DUST, LIGHT_TYPE::DYNAMIC, EffD, BulletControlType::ExtShowType, BULLET_SHOW_TYPE_ID::FIREBALL, EffectDispatcher::FireBallData, FireColorTable, FrameCount, G2LF(), G2LS(), getDistX(), getDistY(), BULLET_SHOW_TYPE_ID::LASER, LightData, MapD, BaseObject::MapLevel, BULLET_SHOW_TYPE_ID::PARTICLE, GeneralObject::R_curr, BaseObject::R_prev, ScreenLineTrace(), LightPoint::set_position(), FireBallProcess::Show(), BulletControlType::ShowID, BulletControlType::ShowType, LIGHT_TYPE::STATIC, vDelta, vTail, Vector::x, XCYCL, Vector::y, YCYCL, and Vector::z.
Event()
void BulletObject::Event (int type)
 {
     int i,y0,y1;
     Vector vCheck;
     StaticObject* st;
     int l;
     WaterParticleObject* wp;
     uchar* tp;
     int TntEnable;
     Status |= SOBJ_DISCONNECT;
     switch(type){
         case BULLET_EVENT_ID::MAP_DESTROY:
             TntEnable = 0;
             if(CurrentWorld != 1){
                 y0 = R_curr.y - EXPLOSION_BARELL_RADIUS;
                 y1 = R_curr.y + EXPLOSION_BARELL_RADIUS;
                 i = FindFirstStatic(y0,y1,(StaticObject**)TntSortedData,TntTableSize);
                 if(i > -1){
                     do{
                         st = TntSortedData[i];
                         if(st->Enable){
                             vCheck.x = getDistX(st->R_curr.x,R_curr.x);
     //                      l = radius + st->radius;
                             l = radius + EXPLOSION_BARELL_RADIUS;
                             if(abs(vCheck.x) < l){
                                 vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                 vCheck.z = st->R_curr.z - R_curr.z;
                                 if(vCheck.abs2() < l*l){
                                     st->Touch(this);
                                     TntEnable = 1;
                                     if(Owner && Owner == ActD.Active)
                                         uvsCheckKronIventTabuTask(UVS_KRON_EVENT::GRIB,1);
                                 };
                             };
                         };
                         i++;
                     }while(i < TntTableSize && TntSortedData[i]->R_curr.y < y1);
                 };
             };
             if(!TntEnable){
                 switch(ShowID){
                     case BULLET_SHOW_TYPE_ID::PARTICLE:
                         tp = vMap->lineT[R_curr.y];
                         if(tp){
                             tp += R_curr.x + H_SIZE;
                             if(GET_TERRAIN_TYPE(*tp) == WATER_TERRAIN && FloodLvl[R_curr.y >> WPART_POWER] >= R_curr.z){
                                 if(!RND(2) || CurrentWorld != WORLD_GLORX) EffD.CreateDeform(R_curr,DEFORM_WATER_ONLY,DT_DEFORM02);
                                 wp = (WaterParticleObject*)(EffD.GetObject(EFF_PARTICLE04));
                                 if(wp){
                                     wp->CreateParticle(30,5,1 << 8,5,5,28,5,R_curr);
                                     EffD.ConnectObject(wp);
                                 };
                             }else{
                                 for(i = 0;i < 6;i++){
                                     vCheck = Vector(20,0,30)*DBM((int)RND(PI*2),Z_AXIS);
                                     vCheck += R_curr;
                                     vCheck.x = XCYCL(vCheck.x);
                                     vCheck.y = YCYCL(vCheck.y);
                                     EffD.CreateParticle(ExtShowType,R_curr,vCheck,ShowType);
 //                                  EffD.CreateParticleTime(ExtShowType,R_curr,vCheck,ShowType,10);
                                 };
                             };
                             if(CraterType >= 0) MapD.CreateCrater(R_curr,CraterType);
                         };
                         break;
                     case BULLET_SHOW_TYPE_ID::FIREBALL:
                         CreateDestroyEffect(R_curr,CraterType,DT_DEFORM02,DEFORM_WATER_ONLY,-1,DT_FIRE_BALL02);
                         break;
                     case BULLET_SHOW_TYPE_ID::LASER:
                         if(CraterType >= 0) MapD.CreateCrater(R_curr,CraterType);
                         break;
                 };
             };
             break;
         case BULLET_EVENT_ID::LIFE_TIME_DESTROY:
             if(BulletMode & BULLET_CONTROL_MODE::MAP_DESTRUCTION){
                 if(ShowID == BULLET_SHOW_TYPE_ID::PARTICLE){
                     tp = vMap->lineT[R_curr.y];
                     if(tp){
                         tp += R_curr.x + H_SIZE;
                         if(GET_TERRAIN_TYPE(*tp) == WATER_TERRAIN && FloodLvl[R_curr.y >> WPART_POWER] >= R_curr.z){
                             if(!RND(2) || CurrentWorld != WORLD_GLORX) EffD.CreateDeform(R_curr,DEFORM_WATER_ONLY,DT_DEFORM02);
                             wp = (WaterParticleObject*)(EffD.GetObject(EFF_PARTICLE04));
                             if(wp){
                                 wp->CreateParticle(30,5,1 << 8,5,5,28,5,R_curr);
                                 EffD.ConnectObject(wp);
                             };
                         }else{
                             for(i = 0;i < 6;i++){
                                 vCheck = Vector(20,0,30)*DBM((int)RND(PI*2),Z_AXIS);
                                 vCheck += R_curr;
                                 vCheck.x = XCYCL(vCheck.x);
                                 vCheck.y = YCYCL(vCheck.y);
     //                          EffD.CreateParticle(ExtShowType,R_curr,vCheck,ShowType);
                                 EffD.CreateParticleTime(ExtShowType,R_curr,vCheck,ShowType,15);
                             };
                         };
                     };
                 };
                 if(CraterType >= 0) MapD.CreateCrater(R_curr,CraterType);
             }else{
                 if(ShowID == BULLET_SHOW_TYPE_ID::FIREBALL)
                     EffD.CreateFireBall(R_curr + Vector(0,0,20),DT_FIRE_BALL02,NULL,1 << 8,0);
             };
             break;
         case BULLET_EVENT_ID::TOUCH:
             switch(ShowID){
                 case BULLET_SHOW_TYPE_ID::PARTICLE:
                     R_prev = R_curr - vDelta;
                     R_prev.x = XCYCL(R_prev.x);
                     R_prev.y = YCYCL(R_prev.y);
                     for(i = 0;i < 6;i++){
                         vCheck = Vector(25 - RND(50),25 - RND(50),25 - RND(50));
                         vCheck += R_prev;
                         vCheck.x = XCYCL(vCheck.x);
                         vCheck.y = YCYCL(vCheck.y);
                         EffD.CreateParticle(ExtShowType,R_curr,vCheck,ShowType);
                     };
                     break;
                 case BULLET_SHOW_TYPE_ID::FIREBALL:
                     EffD.CreateFireBall(R_curr + Vector(0,0,20),DT_FIRE_BALL02);
                     break;
                 case BULLET_SHOW_TYPE_ID::LASER:
                     EffD.CreateExplosion(R_curr + Vector(0,0,20),EFF_EXPLOSION05);
                     break;
                 case BULLET_SHOW_TYPE_ID::CRATER:
 //                  EffD.CreateDeform(R_curr + Vector(16 - RND(32),16 - RND(32),0),DEFORM_ALL,PASSING_WAVE_PROCESS);
 //                  EffD.CreateDeform(R_curr + Vector(16 - RND(32),16 - RND(32),0),DEFORM_ALL,PASSING_WAVE_PROCESS);
 //                  EffD.CreateDeform(R_curr + Vector(16 - RND(32),16 - RND(32),0),DEFORM_ALL,PASSING_WAVE_PROCESS);
 //                  EffD.CreateDeform(R_curr + Vector(16 - RND(32),16 - RND(32),0),DEFORM_ALL,PASSING_WAVE_PROCESS);
                     if(CraterType >= 0) MapD.CreateCrater(R_curr,CraterType);
                     break;
             };
             break;
     };
 };
References Vector::abs2(), ActD, ActionDispatcher::Active, BulletControlType::BulletMode, UnitList::ConnectObject(), BULLET_SHOW_TYPE_ID::CRATER, BulletControlType::CraterType, EffectDispatcher::CreateDeform(), CreateDestroyEffect(), EffectDispatcher::CreateExplosion(), EffectDispatcher::CreateFireBall(), EffectDispatcher::CreateParticle(), EffectDispatcher::CreateParticleTime(), CurrentWorld, DEFORM_WATER_ONLY, DT_DEFORM02, DT_FIRE_BALL02, EFF_EXPLOSION05, EFF_PARTICLE04, EffD, StaticObject::Enable, EXPLOSION_BARELL_RADIUS, BulletControlType::ExtShowType, FindFirstStatic(), BULLET_SHOW_TYPE_ID::FIREBALL, FloodLvl, GET_TERRAIN_TYPE, getDistX(), getDistY(), UnitList::GetObject(), UVS_KRON_EVENT::GRIB, H_SIZE, BULLET_SHOW_TYPE_ID::LASER, BULLET_EVENT_ID::LIFE_TIME_DESTROY, vrtMap::lineT, BULLET_EVENT_ID::MAP_DESTROY, BULLET_CONTROL_MODE::MAP_DESTRUCTION, MapD, NULL, Owner, BULLET_SHOW_TYPE_ID::PARTICLE, PI, GeneralObject::R_curr, BaseObject::R_prev, BaseObject::radius, RND(), BulletControlType::ShowID, BulletControlType::ShowType, SOBJ_DISCONNECT, GeneralObject::Status, TntSortedData, TntTableSize, GeneralObject::Touch(), BULLET_EVENT_ID::TOUCH, uvsCheckKronIventTabuTask(), vDelta, vMap, WATER_TERRAIN, WORLD_GLORX, wp, WPART_POWER, Vector::x, XCYCL, Vector::y, YCYCL, Vector::z, and Z_AXIS.
Referenced by TimeOutQuant(), and Touch().
Init()
void BulletObject::Init (void)
 {
     BaseObject::Init();
     ID = ID_BULLET;
     Status = SOBJ_DISCONNECT;
     radius = 1;
 };
References GeneralObject::ID, ID_BULLET, BaseObject::radius, SOBJ_DISCONNECT, and GeneralObject::Status.
Referenced by BulletList::CreateBullet().
Quant()
void BulletObject::Quant (void)
 {
     if(Status & SOBJ_DISCONNECT) return;
     GetVisible();
     TimeOutQuant();
     if(Visibility == UNVISIBLE){
         if(LightData){
             LightData->Destroy();
             LightData = NULL;
         };
         R_prev = vTail;
     };
 };
References LightPoint::Destroy(), LightData, NULL, BaseObject::R_prev, SOBJ_DISCONNECT, GeneralObject::Status, TimeOutQuant(), UNVISIBLE, BaseObject::Visibility, and vTail.
TimeOutQuant()
void BulletObject::TimeOutQuant (void)
 {
     int d;
     uchar alt;
     Vector v;
     VangerFunctionType* g;
     if(TargetObject){
         v = Vector(getDistX(TargetObject->R_curr.x,R_curr.x),getDistY(TargetObject->R_curr.y,R_curr.y),TargetObject->R_curr.z - R_curr.z);
         if((TargetObject->Status & SOBJ_DISCONNECT) || (TargetObject->ID == ID_VANGER && (!((VangerUnit*)(TargetObject))->ExternalDraw || ((VangerUnit*)(TargetObject))->draw_mode != NORMAL_DRAW_MODE || ((VangerUnit*)(TargetObject))->BeebonationFlag)))
             TargetObject = NULL;
     };
     if(BulletMode & BULLET_CONTROL_MODE::TARGET){
         switch(TargetMode){
             case BULLET_TARGET_MODE::CONTROL:
                 if(TargetObject) vTarget = v;
                 else{
                     vTarget = Vector(0,0,0);
                     BulletMode &= ~BULLET_CONTROL_MODE::TARGET;
                 };
                 break;
             case BULLET_TARGET_MODE::LEFT_ROUND:
                 vTarget = Vector(vDelta.y,-vDelta.x,0);
                 break;
             case BULLET_TARGET_MODE::RIGHT_ROUND:
                 vTarget = Vector(-vDelta.y,vDelta.x,0);
                 break;
             case BULLET_TARGET_MODE::RANDOM:
                 if(RND(100) < 10) vTarget = Vector(BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2),BMAX_TARGET_VECTOR - RND(BMAX_TARGET_VECTOR2));
                 break;
             case BULLET_TARGET_MODE::WALL:
                 v.x = getDistX(R_curr.x,vWallTarget.x);
                 v.y = getDistY(R_curr.y,vWallTarget.y);
                 vTarget.x = v.x - v.y;
                 vTarget.y = v.y + v.x;
                 vTarget.z = 0;
                 break;
         };
         d = vTarget.vabs();
         if(d){
             vDelta += vTarget * Precision / d;
             d = vDelta.vabs();
             if(d > Speed) vDelta = vDelta * Speed / d;
         };
     };
     vTail = R_curr;
     R_curr += vDelta;
     cycleTor(R_curr.x,R_curr.y);
     Time--;
     Power -= DeltaPower;
     if(Visibility == VISIBLE){
         g = ActD.fTail;
         while(g){
             if(g->ID == PROTRACTOR_PALLADIUM){
                 v = Vector(getDistX(R_curr.x,g->vR.x),getDistY(R_curr.y,g->vR.y),0);
                 d = v.vabs();
                 if(d < PALLADIUM_RADIUS){
                     vDelta = Vector(Speed,0,0)*DBM(PI/2 + v.psi(),Z_AXIS);
                     R_curr = vTail;
                     R_curr += vDelta;
                     cycleTor(R_curr.x,R_curr.y);
                 };
                 break;
             };
             g = g->Next;
         };
         if(Time <= 0)
             Event(BULLET_EVENT_ID::LIFE_TIME_DESTROY);
         if(BulletMode & BULLET_CONTROL_MODE::FLY){
             v = vTail;
             if(MapLineTrace(v,R_curr)){
                 R_curr = v;
                 Event(BULLET_EVENT_ID::MAP_DESTROY);
             };
         }else{
             if(ShowID == BULLET_SHOW_TYPE_ID::CRATER && ExtShowType){
                 if(BigGetAlt(R_curr.x,R_curr.y,R_curr.z,alt,ExtShowType)) MapLevel = 1;
                 else{
                     MapLevel = 0;
                     alt = 0;
                     if(LightData){
                         LightData->Destroy();
                         LightData = NULL;
                     };
                 };
             }else MapLevel = GetAlt(R_curr.x,R_curr.y,R_curr.z,alt);
             R_curr.z = alt + AltOffset;
         };
     }else{
         if(Time <= 0)
             Event(BULLET_EVENT_ID::HIDE_LIFE_TIME_DESTROY);
     };
 //  if(ShowID == BULLET_SHOW_TYPE_ID::PARTICLE){
 //      EffD.CreateParticle(ExtShowType,vTail,R_curr,ShowType);
 //      if(BulletScale)
 //          EffD.CreateParticle(ExtShowType,vTail,R_curr,ShowType);
 //  };
 };
References ActD, BulletControlType::AltOffset, BigGetAlt(), BMAX_TARGET_VECTOR, BMAX_TARGET_VECTOR2, BulletControlType::BulletMode, BULLET_TARGET_MODE::CONTROL, BULLET_SHOW_TYPE_ID::CRATER, cycleTor(), BulletControlType::DeltaPower, LightPoint::Destroy(), Event(), BulletControlType::ExtShowType, BULLET_CONTROL_MODE::FLY, ActionDispatcher::fTail, g, GetAlt(), getDistX(), getDistY(), BULLET_EVENT_ID::HIDE_LIFE_TIME_DESTROY, GeneralObject::ID, ID_VANGER, BULLET_TARGET_MODE::LEFT_ROUND, BULLET_EVENT_ID::LIFE_TIME_DESTROY, LightData, BULLET_EVENT_ID::MAP_DESTROY, BaseObject::MapLevel, MapLineTrace(), NORMAL_DRAW_MODE, NULL, PALLADIUM_RADIUS, PI, BulletControlType::Power, BulletControlType::Precision, PROTRACTOR_PALLADIUM, Vector::psi(), GeneralObject::R_curr, BULLET_TARGET_MODE::RANDOM, BULLET_TARGET_MODE::RIGHT_ROUND, RND(), BulletControlType::ShowID, SOBJ_DISCONNECT, BulletControlType::Speed, GeneralObject::Status, BULLET_CONTROL_MODE::TARGET, BulletControlType::TargetMode, TargetObject, BulletControlType::Time, Vector::vabs(), vDelta, BaseObject::Visibility, VISIBLE, vTail, vTarget, vWallTarget, BULLET_TARGET_MODE::WALL, Vector::x, Vector::y, Vector::z, and Z_AXIS.
Referenced by Quant().
Touch()
void BulletObject::Touch (GeneralObject * p) virtual
Reimplemented from GeneralObject.
 {
     if(p == Owner) return;
     if(p->ID == ID_VANGER){
         if(((VangerUnit*)(p))->BeebonationFlag) return;
         if(Owner) PUT_GLOBAL_EVENT(AI_EVENT_COLLISION,ID_BULLET,Owner,(VangerUnit*)(p));
         if(BulletMode & BULLET_CONTROL_MODE::IMPULSE){
             if(/*(BulletMode & BULLET_CONTROL_MODE::FLY) && */(ShowID != BULLET_SHOW_TYPE_ID::CRATER))
                 ((VangerUnit*)(p))->impulse(vDelta,Power / BULLET_IMPULSE_POWER,Power / BULLET_IMPULSE_ARM);
             else{
                 ((VangerUnit*)(p))->impulse(Vector(0,0,64),4*Power / BULLET_IMPULSE_POWER,4*Power / BULLET_IMPULSE_ARM);
             };
         };
         if((ShowID == BULLET_SHOW_TYPE_ID::CRATER) && (p->Status & SOBJ_ACTIVE))
             camera_impulse(256);
         ((VangerUnit*)(p))->BulletCollision(Power,Owner);
         if(!(BulletMode & BULLET_CONTROL_MODE::UNTOUCH))
             Event(BULLET_EVENT_ID::TOUCH);
     };
     R_prev = vTail;
 };
References AI_EVENT_COLLISION, BULLET_IMPULSE_ARM, BULLET_IMPULSE_POWER, BulletControlType::BulletMode, camera_impulse(), BULLET_SHOW_TYPE_ID::CRATER, Event(), GeneralObject::ID, ID_BULLET, ID_VANGER, BULLET_CONTROL_MODE::IMPULSE, Owner, BulletControlType::Power, PUT_GLOBAL_EVENT, BaseObject::R_prev, BulletControlType::ShowID, SOBJ_ACTIVE, GeneralObject::Status, BULLET_EVENT_ID::TOUCH, BULLET_CONTROL_MODE::UNTOUCH, vDelta, and vTail.
Member Data Documentation
DataID
int BulletObject::DataID
Referenced by CreateBullet().
FrameCount
int BulletObject::FrameCount
Referenced by CreateBullet(), and DrawQuant().
LightData
LightPoint* BulletObject::LightData
Referenced by CreateBullet(), DrawQuant(), Quant(), and TimeOutQuant().
Owner
GeneralObject* BulletObject::Owner
Referenced by CreateBullet(), Event(), DangerDataType::FireWork(), TntCreature::NetQuant(), GunSlot::Quant(), TntCreature::Quant(), and Touch().
TargetObject
GeneralObject* BulletObject::TargetObject
Referenced by CreateBullet(), and TimeOutQuant().
vDelta
Vector BulletObject::vDelta
Referenced by CreateBullet(), DrawQuant(), Event(), TimeOutQuant(), and Touch().
vTail
Vector BulletObject::vTail
Referenced by CreateBullet(), DrawQuant(), Quant(), TimeOutQuant(), and Touch().
vTarget
Vector BulletObject::vTarget
Referenced by CreateBullet(), and TimeOutQuant().
vWallTarget
Vector BulletObject::vWallTarget
Referenced by CreateBullet(), and TimeOutQuant().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp