Vangers: iScreen Struct Reference
iScreen Struct Reference
#include <iscreen.h>
Public Member Functions
void CheckScanCode (int sc)
void HandleEvent (iScreenEvent *ev)
void redraw (int mode=0)
void prepare (void)
void init (void)
void init_prompt (void)
void init_ids (void)
void init_avi_border (void)
void load_palette (void)
void free_palette (void)
void show_avi (void)
void hide_avi (void)
void hide_avi_place (void)
void load_data (void)
void free_data (void)
void getfon (void)
void prepare_avi (void)
void close_avi (void)
void copy (iScreen *dest)
void add_object (iScreenObject *p)
void add_terr_object (iScreenObject *p)
void add_event (iListElement *p)
iListElement * get_object (const char *p)
int check_id (char *p)
iScreen (void)
~iScreen (void)
Public Member Functions inherited from iListElement
void init_id (const char *p)
iListElement (void)
~iListElement (void)
Public Attributes
short ID
iScreenObject * curObj
iScreenObject * dcurObj
char * t_objID
int flags
int ScreenOffs
iList * objList
iList * EventList
iList * TerrainList
iList * ObjIDs
char * pal_name
char * palette_buf
XGR_MousePromptScreen * promptData
Public Attributes inherited from iListElement
std::string ID_ptr
int name_len
iListElement * prev
iListElement * next
Detailed Description
Constructor & Destructor Documentation
iScreen()
iScreen::iScreen (void)
 {
     flags = 0;
     objList = new iList;
     EventList = new iList;
     TerrainList = new iList;
     ObjIDs = new iList;
     pal_name = NULL;
     palette_buf = NULL;
     ScreenOffs = 0;
     promptData = new XGR_MousePromptScreen;
 }
References EventList, flags, NULL, ObjIDs, objList, pal_name, palette_buf, promptData, ScreenOffs, and TerrainList.
~iScreen()
iScreen::~iScreen (void)
 {
     iObjID* id,*id1;
     iScreenObject* obj,*obj1;
     iScreenEvent* ev,*ev1;
     obj = (iScreenObject*)objList -> last;
     while(obj){
         obj1 = (iScreenObject*)obj -> prev;
         delete obj;
         obj = obj1;
     }
     obj = (iScreenObject*)TerrainList -> last;
     while(obj){
         obj1 = (iScreenObject*)obj -> prev;
         delete obj;
         obj = obj1;
     }
     ev = (iScreenEvent*)EventList -> last;
     while(ev){
         ev1 = (iScreenEvent*)ev -> prev;
         delete ev;
         ev = ev1;
     }
     id = (iObjID*)ObjIDs -> last;
     while(id){
         id1 = (iObjID*)id -> prev;
         delete id;
         id = id1;
     }
     delete objList;
     delete EventList;
     delete TerrainList;
     delete ObjIDs;
     delete promptData;
 }
References EventList, ObjIDs, objList, iListElement::prev, promptData, and TerrainList.
Member Function Documentation
add_event()
void iScreen::add_event (iListElement * p)
 {
     EventList -> connect(p);
 }
References EventList.
add_object()
void iScreen::add_object (iScreenObject * p)
 {
     iObjID* id;
     iListElement* obj;
     if(iScrDisp -> check_id((char*)p->ID_ptr.c_str()))
         ErrH.Abort("Duplicate object ID...",XERR_USER,0,p->ID_ptr.c_str());
     if(check_id((char*)p->ID_ptr.c_str())){
         obj = get_object(p->ID_ptr.c_str());
         if(obj != (iListElement*)p){
             ErrH.Abort("Duplicate object ID...",XERR_USER,0,p->ID_ptr.c_str());
             return;
         } else {
             id = new iObjID;
             id -> init(p->ID_ptr.c_str(), p->ID);
             id -> obj = (iListElement*)p;
         }
     } else {
         id = new iObjID;
         id -> init(p->ID_ptr.c_str(), p -> ID);
         id -> obj = (iListElement*)p;
     }
     p -> owner = (iListElement*)this;
     ObjIDs -> connect((iListElement*)id);
     objList -> connect((iListElement*)p);
 }
References XErrorHandler::Abort(), check_id(), ErrH, get_object(), ID, iListElement::ID_ptr, init(), iScrDisp, ObjIDs, objList, and XERR_USER.
Referenced by copy().
add_terr_object()
void iScreen::add_terr_object (iScreenObject * p)
 {
     p -> owner = (iListElement*)this;
     TerrainList -> connect((iListElement*)p);
 }
References TerrainList.
Referenced by copy().
check_id()
int iScreen::check_id (char * p)
 {
     iObjID* id = (iObjID*)ObjIDs -> last;
     while(id){
         if(id -> compare(p))
             return 1;
         id = (iObjID*)id -> prev;
     }
     return 0;
 }
References compare(), ObjIDs, and iListElement::prev.
Referenced by add_object().
CheckScanCode()
void iScreen::CheckScanCode (int sc)
 {
     int x = 0,y = 0,mouse_sc = 0;
     iScreenObject* obj;
     iListElement* cd;
     iScreenEvent* p;
     if(sc < 0){
         mouse_sc = 1;
         x = iMouseX + iScreenOffs;
         y = iMouseY;
     }
     obj = (iScreenObject*)objList -> last;
     while(obj){
         if(!iScrDisp -> ActiveEv){
             if(!mouse_sc || obj -> CheckXY(x,y)){
                 p = (iScreenEvent*)obj -> EventList -> last;
                 while(p){
                     if (bool(obj->flags & OBJ_LOCKED) == bool(p->flags & EV_IF_LOCKED)) {
                         cd = p -> codes -> last;
                         while(cd){
                             if(((iScanCode*)cd) -> code == sc && (!(p -> flags & EV_IF_SELECTED) || obj -> flags & OBJ_SELECTED))
                                 HandleEvent(p);
                             cd = cd -> prev;
                         }
                     }
                     p = (iScreenEvent*)p -> prev;
                 }
             }
         }
         obj = (iScreenObject*)obj -> prev;
     }
     if(!iScrDisp -> ActiveEv){
         p = (iScreenEvent*)EventList -> last;
         while(p){
             cd = p -> codes -> last;
             while(cd){
                 if(((iScanCode*)cd) -> code == sc)
                     HandleEvent(p);
                 cd = cd -> prev;
             }
             p = (iScreenEvent*)p -> prev;
         }
     }
 }
References EV_IF_LOCKED, EV_IF_SELECTED, EventList, iScreenEvent::flags, iScreenObject::flags, flags, HandleEvent(), iMouseX, iMouseY, iScrDisp, iScreenOffs, OBJ_LOCKED, OBJ_SELECTED, objList, and iListElement::prev.
close_avi()
void iScreen::close_avi (void)
 {
     iScreenElement* el;
     iScreenObject* p = (iScreenObject*)objList -> last;
     while(p){
         el = (iScreenElement*)p -> ElementList -> last;
         while(el){
             if(el -> type == I_AVI_ELEM)
                 ((iAVIElement*)el) -> free();
             el = (iScreenElement*)el -> prev;
         }
         p = (iScreenObject*)p -> prev;
     }
 }
References I_AVI_ELEM, objList, and iListElement::prev.
copy()
void iScreen::copy (iScreen * dest)
 {
     iScreenEvent* dest_ev,*ev;
     iTriggerObject* trg;
     iScreenObject* tmp,*p;
     p = (iScreenObject*)objList -> last;
     while(p){
         if(p -> flags & OBJ_TRIGGER){
             trg = new iTriggerObject;
             tmp = (iScreenObject*)trg;
         }
         else
             tmp = new iScreenObject;
         tmp -> init_id(p->ID_ptr.c_str());
         p -> copy(tmp);
         dest -> add_object(tmp);
         p = (iScreenObject*)p -> prev;
     }
     p = (iScreenObject*)TerrainList -> last;
     while(p){
         tmp = new iScreenObject;
         tmp -> init_id(p->ID_ptr.c_str());
         p -> copy(tmp);
         dest -> add_terr_object(tmp);
         p = (iScreenObject*)p -> prev;
     }
     ev = (iScreenEvent*)EventList -> last;
     while(ev){
         dest_ev = new iScreenEvent;
         ev -> copy(dest_ev);
         dest -> EventList -> connect((iListElement*)dest_ev);
         ev = (iScreenEvent*)ev -> prev;
     }
     dest -> ScreenOffs = ScreenOffs;
 }
References add_object(), add_terr_object(), EventList, flags, iListElement::ID_ptr, iListElement::init_id(), OBJ_TRIGGER, objList, iListElement::prev, ScreenOffs, and TerrainList.
free_data()
void iScreen::free_data (void)
 {
     iScreenObject* obj = (iScreenObject*)objList -> last;
     while(obj){
         obj -> free_data();
         obj = (iScreenObject*)obj -> prev;
     }
     obj = (iScreenObject*)TerrainList -> last;
     while(obj){
         obj -> free_data();
         obj = (iScreenObject*)obj -> prev;
     }
     if(pal_name) free_palette();
 }
References free_palette(), objList, pal_name, iListElement::prev, and TerrainList.
free_palette()
void iScreen::free_palette (void)
 {
     if(palette_buf){
         delete[] palette_buf;
         palette_buf = NULL;
     }
 }
References NULL, and palette_buf.
Referenced by free_data().
get_object()
iListElement * iScreen::get_object (const char * p)
 {
     iObjID* id = (iObjID*)ObjIDs -> last;
     while(id){
         if(id -> compare(p))
             return id -> obj;
         id = (iObjID*)id -> prev;
     }
     return NULL;
 }
References compare(), NULL, ObjIDs, and iListElement::prev.
Referenced by add_object(), init(), and init_ids().
getfon()
void iScreen::getfon (void)
 {
     iScreenObject* obj;
     obj = (iScreenObject*)objList -> last;
     while(obj){
         obj -> getfon();
         obj = (iScreenObject*)obj -> prev;
     }
 }
References objList, and iListElement::prev.
Referenced by load_data().
HandleEvent()
void iScreen::HandleEvent (iScreenEvent * ev)
 {
     iScreenEventCommand* p = (iScreenEventCommand*)ev -> CommSeq -> last;
     while(p){
         if(p -> EvType == EV_OBJECT_JUMP){
             if(p -> objID == curObj -> ID)
                 return;
         }
         p = (iScreenEventCommand*)p -> prev;
     }
     if(!(ev -> flags & EV_ACTIVE)){
         ev -> flags |= EV_ACTIVE;
         ev -> cur_time = 0;
         iScrDisp -> ActiveEv = ev;
         SOUND_SELECT();
     }
 }
References curObj, EV_ACTIVE, EV_OBJECT_JUMP, flags, ID, iScrDisp, iListElement::prev, and SOUND_SELECT.
Referenced by CheckScanCode().
hide_avi()
void iScreen::hide_avi (void)
 {
     iScreenObject* obj = (iScreenObject*)objList -> last;
     while(obj){
         if(obj -> flags & OBJ_AVI_PRESENT){
             obj -> curHeightScale = 0;
         }
         obj = (iScreenObject*)obj -> prev;
     }
 }
References flags, OBJ_AVI_PRESENT, objList, and iListElement::prev.
hide_avi_place()
void iScreen::hide_avi_place (void)
 {
     iScreenObject* obj = (iScreenObject*)objList -> last;
     while(obj){
         if(obj -> flags & OBJ_AVI_PRESENT){
             obj -> curHeightScale = 0;
             iregRender(obj -> PosX,obj -> PosY,obj -> PosX + obj -> SizeX,obj -> PosY + obj -> SizeY);
         }
         obj = (iScreenObject*)obj -> prev;
     }
 }
References flags, iregRender(), OBJ_AVI_PRESENT, objList, and iListElement::prev.
init()
void iScreen::init (void)
 {
     iScreenEvent* ev;
     iScreenObject* obj;
     iScreenEventCommand* ec;
     iListElement* p;
     init_ids();
     ev = (iScreenEvent*)EventList -> last;
     while(ev){
         ec = (iScreenEventCommand*)ev -> CommSeq -> last;
         while(ec){
             if(ec -> objType != I_ABSENT){
                 p = get_object(ec -> tmp_objID);
                 if(!p)
                     p = iScrDisp -> get_object(ec -> tmp_objID);
                 if(!p)
                     ErrH.Abort("Can't find object...",XERR_USER,0,ec -> tmp_objID);
                 ec -> obj = p;
             }
             ec = (iScreenEventCommand*)ec -> prev;
         }
         ev = (iScreenEvent*)ev -> prev;
     }
     obj = (iScreenObject*)objList -> last;
     while(obj){
         ev = (iScreenEvent*)obj -> EventList -> last;
         while(ev){
             ec = (iScreenEventCommand*)ev -> CommSeq -> last;
             while(ec){
                 if(ec -> objType != I_ABSENT){
                     p = get_object(ec -> tmp_objID);
                     if(!p)
                         p = iScrDisp -> get_object(ec -> tmp_objID);
                     if(!p)
                         ErrH.Abort("Can't find object...",XERR_USER,0,ec -> tmp_objID);
                     ec -> obj = p;
                 }
                 ec = (iScreenEventCommand*)ec -> prev;
             }
             ev = (iScreenEvent*)ev -> prev;
         }
         obj = (iScreenObject*)obj -> prev;
     }
 }
References XErrorHandler::Abort(), ErrH, EventList, get_object(), I_ABSENT, init_ids(), iScrDisp, objList, iListElement::prev, and XERR_USER.
Referenced by add_object(), init_avi_border(), and init_ids().
init_avi_border()
void iScreen::init_avi_border (void)
 {
     iScreenElement* el;
     iAVIBorderElement* bd;
     iAVIElement* avi;
     iScreenObject* obj,*b_obj;
     obj = (iScreenObject*)objList -> last;
     while(obj){
         obj -> init();
         if(obj -> flags & OBJ_AVI_PRESENT && !(obj -> flags & AVI_BORDER_INIT)){
             obj -> flags |= AVI_BORDER_INIT;
             el = (iScreenElement*)obj -> ElementList -> last;
             while(el && el -> type != I_AVI_ELEM)
                 el = (iScreenElement*)el -> prev;
             if(!el)
                 ErrH.Abort("Bad AVI object",XERR_USER,0,obj->ID_ptr.c_str());
             avi = (iAVIElement*)el;
                 b_obj = new iScreenObject;
                 b_obj -> ID = 0;
                 b_obj -> init_id("BORDER_OBJ");
                 bd = new iAVIBorderElement;
                 bd -> type = I_AVI_BORDER_ELEM;
                 bd -> border_type = avi -> border_type;
                 bd -> border_level = avi -> border_level;
                 bd -> border_null_level = avi -> border_null_level;
                 bd -> border_size = avi -> border_size;
                 bd -> SizeX = (bd -> border_size * 2) + avi -> SizeX;
                 bd -> SizeY = (bd -> border_size * 2) + avi -> SizeY;
                 b_obj -> add_element(bd);
                 b_obj -> PosX = obj -> PosX + avi -> lX - bd -> border_size - 1;
                 b_obj -> PosY = obj -> PosY + avi -> lY - bd -> border_size - 1;
                 b_obj -> flags |= OBJ_AVI_BORDER;
                 b_obj -> init();
                 objList -> connect((iListElement*)b_obj);
         }
         obj = (iScreenObject*)obj -> prev;
     }
 }
References XErrorHandler::Abort(), AVI_BORDER_INIT, ErrH, flags, I_AVI_BORDER_ELEM, I_AVI_ELEM, ID, iListElement::ID_ptr, init(), iListElement::init_id(), OBJ_AVI_BORDER, OBJ_AVI_PRESENT, objList, iListElement::prev, and XERR_USER.
init_ids()
void iScreen::init_ids (void)
 {
     iObjID* id;
     iListElement* p;
     iScreenElement* el;
     iScreenObject* obj;
     obj = (iScreenObject*)objList -> last;
     while(obj){
         p = get_object(obj->ID_ptr.c_str());
         if(!p){
             id = new iObjID;
             id -> init(obj->ID_ptr.c_str(), obj -> ID,obj);
             ObjIDs -> connect((iListElement*)id);
         }
         else {
             if(p != (iListElement*)obj)
                 ErrH.Abort("Duplicate object ID...",XERR_USER,0,obj->ID_ptr.c_str());
         }
         el = (iScreenElement*)obj -> ElementList -> last;
         while(el){
             if(el->ID_ptr.size()){
                 p = get_object(el->ID_ptr.c_str());
                 if(!p){
                     id = new iObjID;
                     id -> init(el->ID_ptr.c_str(),el -> ID,el);
                     ObjIDs -> connect((iListElement*)id);
                 }
                 else {
                     if(p != (iListElement*)el)
                         ErrH.Abort("Duplicate object ID...",XERR_USER,0,el->ID_ptr.c_str());
                 }
             }
             el = (iScreenElement*)el -> prev;
         }
         if(!obj -> owner) obj -> owner = (iListElement*)this;
         obj = (iScreenObject*)obj -> prev;
     }
 }
References XErrorHandler::Abort(), ErrH, get_object(), ID, iListElement::ID_ptr, init(), ObjIDs, objList, iListElement::prev, and XERR_USER.
Referenced by init().
init_prompt()
void iScreen::init_prompt (void)
 {
     iScreenObject* obj;
     XGR_MousePromptData* pr;
     obj = (iScreenObject*)objList -> last;
     while(obj){
         if(obj -> promptData){
             pr = new XGR_MousePromptData(obj -> PosX,obj -> PosY,obj -> SizeX,obj -> SizeY,0);
             pr -> set_text(obj -> promptData);
             if(obj -> promptID)
                 pr -> ID = obj -> promptID;
             promptData -> AddElement((XListElement*)pr);
         }
         obj = (iScreenObject*)obj -> prev;
     }
 }
References ID, objList, iListElement::prev, and promptData.
load_data()
void iScreen::load_data (void)
 {
     iScreenObject* obj = (iScreenObject*)TerrainList -> last;
     while(obj){
         obj -> load_data();
         obj -> getfon();
         obj -> redraw();
         obj = (iScreenObject*)obj -> prev;
     }
     obj = (iScreenObject*)objList -> last;
     while(obj){
         obj -> load_data();
         obj = (iScreenObject*)obj -> prev;
     }
     if(pal_name) load_palette();
 }
References getfon(), load_palette(), objList, pal_name, iListElement::prev, redraw(), and TerrainList.
load_palette()
void iScreen::load_palette (void)
 {
     XStream fh;
     if(!pal_name) return;
     if(!palette_buf) palette_buf = new char[768];
     fh.open(pal_name,XS_IN);
     fh.read(palette_buf,768);
     fh.close();
 }
References XStream::close(), XStream::open(), pal_name, palette_buf, XStream::read(), and XS_IN.
Referenced by load_data().
prepare()
void iScreen::prepare (void)
 {
     iScreenObject* p = (iScreenObject*)objList -> last;
     while(p){
         p -> flags &= ~OBJ_HIDE;
         if(!(p -> flags & OBJ_NOT_UNLOCK)) p -> flags &= ~OBJ_LOCKED;
         if(p -> flags & OBJ_SELECTABLE){
             if(p -> flags & OBJ_SELECTED)
                 p -> curHeightScale = 256;
             else
                 p -> curHeightScale = I_UNSELECT_SCALE;
         }
         else
             p -> curHeightScale = 256;
         p -> SmoothLevel = 0;
         p = (iScreenObject*)p -> prev;
     }
     p = (iScreenObject*)TerrainList -> last;
     while(p){
         p -> flags &= ~OBJ_HIDE;
         p -> curHeightScale = ((iTerrainElement*)p -> ElementList -> last) -> scale_strength;
         p -> SmoothLevel = 0;
         p = (iScreenObject*)p -> prev;
     }
     XGR_MouseSetPromptData(promptData);
     XGR_MouseObj.PromptDeltaX = ScreenOffs;
     if(actIntLog)
         XGR_MouseObj.PromptColor = aciCurColorScheme[FM_SELECT_START] | (aciCurColorScheme[FM_SELECT_SIZE] << 16);
 }
References aciCurColorScheme, actIntLog, flags, FM_SELECT_SIZE, FM_SELECT_START, I_UNSELECT_SCALE, OBJ_HIDE, OBJ_LOCKED, OBJ_NOT_UNLOCK, OBJ_SELECTABLE, OBJ_SELECTED, objList, iListElement::prev, XGR_Mouse::PromptColor, promptData, XGR_Mouse::PromptDeltaX, ScreenOffs, TerrainList, XGR_MouseObj, and XGR_MouseSetPromptData.
prepare_avi()
void iScreen::prepare_avi (void)
 {
     iScreenElement* el;
     iScreenObject* p = (iScreenObject*)objList -> last;
     while(p){
         el = (iScreenElement*)p -> ElementList -> last;
         while(el){
             if(el -> type == I_AVI_ELEM){
                 ((iAVIElement*)el) -> load();
                 ((iAVIElement*)el) -> init_size();
                 ((iAVIElement*)el) -> init_align();
             }
             el = (iScreenElement*)el -> prev;
         }
         p = (iScreenObject*)p -> prev;
     }
 }
References I_AVI_ELEM, objList, and iListElement::prev.
redraw()
void iScreen::redraw (int mode = 0)
 {
     iScreenObject* p;
     p = (iScreenObject*)objList -> last;
     while(p){
         p -> putfon();
         p = (iScreenObject*)p -> prev;
     }
     p = (iScreenObject*)TerrainList -> last;
     while(p){
         p -> putfon();
         p = (iScreenObject*)p -> prev;
     }
     p = (iScreenObject*)TerrainList -> last;
     while(p){
         p -> redraw(mode);
         p = (iScreenObject*)p -> prev;
     }
     p = (iScreenObject*)objList -> last;
     while(p){
         p -> redraw(mode);
         p = (iScreenObject*)p -> prev;
     }
 }
References objList, iListElement::prev, and TerrainList.
Referenced by load_data().
show_avi()
void iScreen::show_avi (void)
 {
     int sz;
     iAVIElement* avi;
     iScreenElement* el;
     iScreenObject* obj = (iScreenObject*)objList -> last;
     unsigned char* p;
     while(obj){
         if(obj -> flags & OBJ_AVI_PRESENT){
             el = (iScreenElement*)obj -> ElementList -> last;
             while(el){
                 if(el -> type == I_AVI_ELEM){
                     avi = (iAVIElement*)el;
                     sz = avi -> SizeX * avi -> SizeY;
                     _iALLOC_A_(unsigned char,p,sz);
                     memset(p,0,sz);
                     put_buf2col(obj -> PosX + avi -> lX,obj -> PosY + avi -> lY,avi -> SizeX,avi -> SizeY,p,iAVI_NULL_LEV,1);
                     _iFREE_A_(unsigned char,p,sz);
                 }
                 el = (iScreenElement*)el -> prev;
             }
         }
         obj = (iScreenObject*)obj -> prev;
     }
 }
References _iALLOC_A_, _iFREE_A_, flags, I_AVI_ELEM, iAVI_NULL_LEV, OBJ_AVI_PRESENT, objList, iListElement::prev, and put_buf2col().
Member Data Documentation
curObj
iScreenObject* iScreen::curObj
Referenced by HandleEvent().
dcurObj
iScreenObject* iScreen::dcurObj
EventList
iList* iScreen::EventList
Referenced by add_event(), CheckScanCode(), copy(), init(), iScreen(), and ~iScreen().
flags
int iScreen::flags
Referenced by CheckScanCode(), copy(), HandleEvent(), hide_avi(), hide_avi_place(), init_avi_border(), iScreen(), prepare(), and show_avi().
ID
short iScreen::ID
Referenced by add_object(), HandleEvent(), init_avi_border(), init_ids(), and init_prompt().
ObjIDs
iList* iScreen::ObjIDs
Referenced by add_object(), check_id(), get_object(), init_ids(), iScreen(), and ~iScreen().
objList
iList* iScreen::objList
Referenced by add_object(), CheckScanCode(), close_avi(), copy(), free_data(), getfon(), hide_avi(), hide_avi_place(), init(), init_avi_border(), init_ids(), init_prompt(), iScreen(), load_data(), prepare(), prepare_avi(), redraw(), show_avi(), and ~iScreen().
pal_name
char* iScreen::pal_name
Referenced by free_data(), iScreen(), load_data(), and load_palette().
palette_buf
char* iScreen::palette_buf
Referenced by free_palette(), iScreen(), and load_palette().
promptData
XGR_MousePromptScreen* iScreen::promptData
Referenced by init_prompt(), iScreen(), prepare(), and ~iScreen().
ScreenOffs
int iScreen::ScreenOffs
Referenced by copy(), iScreen(), and prepare().
t_objID
char* iScreen::t_objID
TerrainList
iList* iScreen::TerrainList
Referenced by add_terr_object(), copy(), free_data(), iScreen(), load_data(), prepare(), redraw(), and ~iScreen().
The documentation for this struct was generated from the following files:
src/iscreen/iscreen.h
src/iscreen/iscreen.cpp