Vangers: Server Struct Reference
Server Struct Reference
#include <server.h>
Public Member Functions
Server (int main_port, int broadcast_port, int time_to_live)
~Server ()
void clear ()
Game * create_game ()
int quant ()
int check_new_clients ()
int clients_quant ()
int games_quant ()
void get_games_list (OutputEventBuffer &out_buffer, int client_version)
void analyse_statistics (Game *g)
void report ()
void consoleReport (int players)
void load_rating_list (const char *name)
void save_rating_list (const char *name)
RatingData * search_rating_data (char *player_name, char *player_password, int MP_game)
void add_rating_data (Player *player, int MP_game)
void get_top_list (OutputEventBuffer &out_buffer, int MP_game)
Public Attributes
int games_IDs_counter
XTList< Game > games
XTList< Player > clients
float rating_threshoulds [NUMBER_MP_GAMES]
XTList< RatingData > rating_list
XSocket main_socket
int transferring
unsigned int time_to_live
unsigned int time_to_destroy
int next_broadcast
int n_games [NUMBER_MP_GAMES]
int n_players_max [NUMBER_MP_GAMES]
int n_players_sum [NUMBER_MP_GAMES]
int playing_time_max [NUMBER_MP_GAMES]
int playing_time_sum [NUMBER_MP_GAMES]
Detailed Description
Constructor & Destructor Documentation
Server()
Server::Server (int main_port, int broadcast_port, int time_to_live)
{
     if (!main_socket.listen(main_port)) {
         XBuffer err;
         err < "Vangers Server is already running or TCP/IP port " <= main_port <
             " is used by another application";
         ErrH.Abort(err.GetBuf());
         // SERVER_ERROR("Unable to create Server",main_port);
     }
     std::cout << "Main TCP/IP port: " << main_port << std::endl;
     load_rating_list("Rating.lst");
     transferring = 0;
     next_broadcast = 0;
     games_IDs_counter = 0;
     Server::time_to_live = time_to_live;
     time_to_destroy = 0;
     if (StatLogging)
         stat_log.open("VangersServer.log", XS_OUT);
     for (int i = 0; i < NUMBER_MP_GAMES; i++)
         n_games[i] = n_players_max[i] = n_players_sum[i] = playing_time_max[i] =
             playing_time_sum[i] = 0;
 }
References XErrorHandler::Abort(), ErrH, games_IDs_counter, XBuffer::GetBuf(), XSocket::listen(), load_rating_list(), main_socket, n_games, n_players_max, n_players_sum, next_broadcast, NUMBER_MP_GAMES, XStream::open(), playing_time_max, playing_time_sum, stat_log, StatLogging, time_to_destroy, time_to_live, transferring, and XS_OUT.
~Server()
Server::~Server ()
                 {
     save_rating_list("Rating.lst");
     RatingData *p;
     while ((p = rating_list.first()) != 0) {
         rating_list.remove(p);
         delete p;
     }
     clear();
 }
References clear(), XTList< Type >::first(), rating_list, XTList< Type >::remove(), and save_rating_list().
Member Function Documentation
add_rating_data()
void Server::add_rating_data (Player * player, int MP_game)
{
     RatingData *p = search_rating_data(player->name, player->password, MP_game);
     if (fabs(player->body.rating - player->prev_rating) < 0.01 &&
         (p || player->body.rating < rating_threshoulds[MP_game]))
         return;
     if (p)
         rating_list.remove(p);
     else
         p = new RatingData(player->name, player->password, MP_game, 0);
     p->rating += player->body.rating - player->prev_rating;
     float rating = p->rating;
     int counter = 0;
     RatingData *pp = rating_list.first();
     while (pp && (pp->MP_game < MP_game || pp->MP_game == MP_game && pp->rating > rating)) {
         if (pp->MP_game == MP_game)
             if (counter++ > 20) {
                 rating_threshoulds[MP_game] = pp->rating;
                 delete p;
                 return;
             }
         pp = pp->next;
     }
     rating_list.insert(pp, p);
     player->prev_rating = player->body.rating;
 }
References Player::body, counter, XTList< Type >::first(), XTList< Type >::insert(), RatingData::MP_game, Player::name, RatingData::next, Player::password, Player::prev_rating, PlayerBody::rating, RatingData::rating, rating_list, rating_threshoulds, XTList< Type >::remove(), and search_rating_data().
Referenced by Game::process_MECHOSOMA_ratings(), Game::process_PASSEMBLOSS_ratings(), and Game::process_VAN_WAR_ratings().
analyse_statistics()
void Server::analyse_statistics (Game * g)
{
     int playing_time = round(double(TIME_INTERVAL(g->birth_time)) / (60 * 1000));
     int n_players = g->removed_players.size();
     if (!n_players || playing_time < 5)
         return;
     int type = g->data.GameType;
     n_games[type]++;
     if (n_players_max[type] < n_players)
         n_players_max[type] = n_players;
     n_players_sum[type] += n_players;
     if (playing_time_max[type] < playing_time)
         playing_time_max[type] = playing_time;
     playing_time_sum[type] += playing_time;
     std::cout << "\nGames' Statistics (maximum/average):\n";
     for (int i = 0; i < NUMBER_MP_GAMES; i++) {
         if (!n_games[i])
             continue;
         std::cout << (char *)MP_GAMES_NAMES[i] << ": " << n_games[i]
                   << "; Players: " << n_players_max[i] << "/"
                   << round(double(n_players_sum[i]) / n_games[i])
                   << "; Time of game: " << playing_time_max[i] << "/"
                   << round(double(playing_time_sum[i]) / n_games[i]) << " min.\n";
     }
     std::cout << "Last game: ";
     time_t aclock;
     time(&aclock);
     struct tm *newtime = localtime(&aclock);
     char *strtime = asctime(newtime);
     strtime[strlen(strtime) - 1] = 0;
     std::cout << (char *)MP_GAMES_NAMES[type] << "; " << strtime << "; Players: " << n_players
               << "; Time of game: " << playing_time << " min.\n\n";
     if (StatLogging) {
         stat_log < strtime < "; " < (char *)MP_GAMES_NAMES[type] < "; Players: " <= n_players <
             "; Time of game: " <= playing_time < " min.\n";
         Player *p = g->removed_players.first();
         while (p) {
             int IP = p->socket.addr.host;
             if (IP)
                 stat_log < "IP: " <= (IP & 0xff) < "." <= ((IP >> 8) & 0xff) < "." <=
                     ((IP >> 16) & 0xff) < "." <= ((IP >> 24) & 0xff) < "; Time of Existence: " <=
                     round(double(TIME_INTERVAL(p->birth_time)) / (60 * 1000)) < " min.; Rating: " <=
                     round(p->body.rating) < "\n";
             p = p->next;
         }
         stat_log < "\n";
     }
 }
References g, MP_GAMES_NAMES, n_games, n_players_max, n_players_sum, NUMBER_MP_GAMES, playing_time_max, playing_time_sum, round(), stat_log, StatLogging, and TIME_INTERVAL.
Referenced by games_quant().
check_new_clients()
int Server::check_new_clients ()
{
     if (!main_socket)
         return 0;
     XSocket &&sock = main_socket.accept();
     if (!sock)
         return 0;
     Player *player = new Player(this, sock);
     clients.append(player);
     DOUT("Client attached");
     return 1;
 }
References XSocket::accept(), XTList< Type >::append(), clients, DOUT, and main_socket.
Referenced by quant().
clear()
void Server::clear (void)
                    {
     Game *g;
     while ((g = games.first()) != 0) {
         games.remove(g);
         delete g;
     }
     Player *p;
     while ((p = clients.first()) != 0) {
         clients.remove(p);
         delete p;
     }
     DOUT("Clear Server");
 }
References clients, DOUT, XTList< Type >::first(), g, games, and XTList< Type >::remove().
Referenced by ~Server().
clients_quant()
int Server::clients_quant ()
{
     int work_log = 0;
     Player *p = clients.first();
     while (p) {
         if (p->identificated) {
             work_log += p->receive();
             work_log += p->send();
         } else
             p->identification();
         if (!p->is_alive()) {
             Player *p_next = p->next;
             //          DOUT("Client removed");
             clients.remove(p);
             delete p;
             p = p_next;
         } else
             p = p->next;
     }
     return work_log;
 }
References clients, XTList< Type >::first(), Player::identificated, Player::identification(), Player::is_alive(), Player::next, Player::receive(), XTList< Type >::remove(), and Player::send().
Referenced by quant().
consoleReport()
void Server::consoleReport (int players)
{
     static int g = -1;
     static int p = -1;
     static int c = -1;
     if (g == games.size() && p == players && c == clients.size())
         return;
     g = games.size();
     p = players;
     c = clients.size();
     std::cout << "Games: " << games.size() << " "
               << "Players: " << players << " "
               << "Clients: " << clients.size() << " "
               << "\n";
 }
References clients, g, games, and XTList< Type >::size().
Referenced by quant().
create_game()
Game * Server::create_game ()
{
     Game *game = new Game(++games_IDs_counter);
     games.append(game);
     DOUT1("Game created", games_IDs_counter);
     return game;
 }
References XTList< Type >::append(), DOUT1, games, and games_IDs_counter.
Referenced by Player::receive(), and xtInitApplication().
games_quant()
int Server::games_quant ()
{
     int work_log = 0;
     Game *g = games.first();
     while (g) {
         work_log += g->quant();
         if (!g->players.size() && !leave_empty_games) {
             analyse_statistics(g);
             Game *g_next = g->next;
             games.remove(g);
             delete g;
             g = g_next;
             continue;
         }
         g = g->next;
     }
     return work_log;
 }
References analyse_statistics(), XTList< Type >::first(), g, games, leave_empty_games, and XTList< Type >::remove().
Referenced by quant().
get_games_list()
void Server::get_games_list (OutputEventBuffer & out_buffer, int client_version)
{
     int num = 0;
     Game *g = games.first();
     while (g) {
         if (g->data.GameType != UNCONFIGURED && g->used_players_IDs != 0x7fffffff &&
             g->client_version == client_version)
             num++;
         g = g->next;
     }
     out_buffer.begin_event(GAMES_LIST_RESPONSE);
     out_buffer < (unsigned char)num;
     g = games.first();
     while (g) {
         if (g->data.GameType != UNCONFIGURED && g->used_players_IDs != 0x7fffffff &&
             g->client_version == client_version) {
             out_buffer < g->ID < g->name < ": " <= g->players.size() < " " <
                 (g->data.GameType == VAN_WAR ? "V" : (g->data.GameType == MECHOSOMA ? "M" : "P"));
             int t = (SDL_GetTicks() - g->birth_time) / 1000;
             int ts = t % 60;
             t /= 60;
             int tm = t % 60;
             t /= 60;
             int th = t % 24;
             out_buffer < " " <= th < ":" <= tm < ":" <= ts < char(0);
         }
         g = g->next;
     }
     out_buffer.end_event();
 }
References OutputEventBuffer::begin_event(), OutputEventBuffer::end_event(), XTList< Type >::first(), g, games, GAMES_LIST_RESPONSE, MECHOSOMA, UNCONFIGURED, and VAN_WAR.
Referenced by Player::send().
get_top_list()
void Server::get_top_list (OutputEventBuffer & out_buffer, int MP_game)
{
     int num = 0;
     RatingData *p = rating_list.first();
     while (p) {
         if (p->MP_game == MP_game)
             num++;
         p = p->next;
     }
     if (num > 10)
         num = 10;
     out_buffer.begin_event(TOP_LIST_RESPONSE);
     out_buffer < (unsigned char)MP_game < (unsigned char)num;
     p = rating_list.first();
     while (p && num) {
         if (p->MP_game == MP_game) {
             out_buffer < p->name < char(0) < p->rating;
             num--;
         }
         p = p->next;
     }
     out_buffer.end_event();
 }
References OutputEventBuffer::begin_event(), OutputEventBuffer::end_event(), XTList< Type >::first(), RatingData::MP_game, RatingData::name, RatingData::next, RatingData::rating, rating_list, and TOP_LIST_RESPONSE.
Referenced by Player::receive().
load_rating_list()
void Server::load_rating_list (const char * name)
{
     XStream ff(0);
     if (!ff.open(fname, XS_IN))
         return;
     XBuffer buf(ff.size());
     ff.read(buf.address(), ff.size());
     char name[257];
     char password[257];
     int MP_game;
     float rating;
     RatingData *p;
     int num_data;
     buf > num_data;
     for (int i = 0; i < num_data; i++) {
         buf > name > password > MP_game > rating;
         p = new RatingData(name, password, MP_game, rating);
         rating_list.append(p);
     }
     for (int i = 0; i < NUMBER_MP_GAMES; i++)
         rating_threshoulds[i] = (float)-1e+10;
 }
References XBuffer::address(), XTList< Type >::append(), NUMBER_MP_GAMES, XStream::open(), rating_list, rating_threshoulds, XStream::read(), XStream::size(), and XS_IN.
Referenced by Server().
quant()
int Server::quant ()
                   {
     // fout < "Quant: " <= frame < "\t" <= SDL_GetTicks() < "\n";
     if (next_broadcast < SDL_GetTicks()) {
         next_broadcast = SDL_GetTicks() + 1000;
         int n_players = 0;
         Game *g = games.first();
         while (g) {
             n_players += g->players.size();
             g = g->next;
         }
         consoleReport(n_players);
         if (time_to_live && !(transferring | games.size() | n_players | clients.size())) {
             if (!time_to_destroy)
                 time_to_destroy = SDL_GetTicks() + time_to_live * 1000;
         } else
             time_to_destroy = 0;
         if (time_to_destroy && IS_PAST(time_to_destroy))
             GlobalExit = 1;
         transferring = 0;
         // report();
     }
     int transf = check_new_clients() + clients_quant() + games_quant();
     transferring += transf;
     return transf;
 }
References check_new_clients(), clients, clients_quant(), consoleReport(), XTList< Type >::first(), g, games, games_quant(), GlobalExit, IS_PAST, next_broadcast, XTList< Type >::size(), time_to_destroy, time_to_live, and transferring.
Referenced by KDsPlus::Quant().
report()
void Server::report ()
                     {
     std::cout << "\n\nReport's time: " << SECONDS() << "\n";
     Player *p;
     World *w;
     Game *s = games.first();
     while (s) {
         std::cout << "Game " << (unsigned char)(s->ID) << ": ";
         if (!(s->players.size() | s->worlds.size())) {
             std::cout << "Empty\n\n";
             s = s->next;
             continue;
         }
         std::cout << "\nPlayers: " << s->players.size() << "\tWorlds: " << s->worlds.size()
                   << "\tglobal objects: " << s->global_objects.size() << "\n";
         p = s->players.first();
         while (p) {
             std::cout << "Player: " << p->ID << "\tsocket: " << p->socket()
                       << "\tworld: " << (p->world ? p->world->ID : 0)
                       << "\tinventory: " << p->inventory.size() << "\t " << p->name << "\n";
             p = p->next;
         }
         w = s->worlds.first();
         while (w) {
             std::cout << "World: " << w->ID << "\ttotal objects: " << w->number_of_objects << "\n";
             w = w->next;
         }
         std::cout << "\n";
         s = s->next;
     }
 }
References XTList< Type >::first(), games, Game::global_objects, World::ID, Player::ID, Game::ID, Player::inventory, Player::name, World::next, Player::next, Game::next, World::number_of_objects, Game::players, SECONDS, XTList< Type >::size(), Player::socket, Player::world, and Game::worlds.
save_rating_list()
void Server::save_rating_list (const char * name)
{
     XStream ff(name, XS_OUT);
     ff < rating_list.size();
     RatingData *p = rating_list.first();
     //  fout < "\n\nRating:\n";
     while (p) {
         ff < p->name < char(0) < p->password < char(0) < p->MP_game < p->rating;
         //      fout < p -> name < "\t" < p -> password  < "\t" <= p -> MP_game < "\t" <= p ->
         //rating < "\n";
         p = p->next;
     }
     //  fout < "\n";
 }
References XTList< Type >::first(), RatingData::MP_game, RatingData::name, RatingData::next, RatingData::password, RatingData::rating, rating_list, XTList< Type >::size(), and XS_OUT.
Referenced by ~Server().
search_rating_data()
RatingData * Server::search_rating_data (char * player_name, char * player_password, int MP_game)
{
     RatingData *p = rating_list.first();
     while (p) {
         if (!strcmp(player_name, p->name) && !strcmp(player_password, p->password) &&
             MP_game == p->MP_game)
             return p;
         p = p->next;
     }
     return p;
 }
References XTList< Type >::first(), RatingData::MP_game, RatingData::name, RatingData::next, RatingData::password, and rating_list.
Referenced by add_rating_data().
Member Data Documentation
clients
XTList<Player> Server::clients
Referenced by Game::attach_player(), check_new_clients(), clear(), clients_quant(), consoleReport(), and quant().
games
XTList<Game> Server::games
Referenced by clear(), consoleReport(), create_game(), games_quant(), get_games_list(), quant(), Player::receive(), and report().
games_IDs_counter
int Server::games_IDs_counter
Referenced by create_game(), and Server().
main_socket
XSocket Server::main_socket
Referenced by check_new_clients(), and Server().
n_games
int Server::n_games[NUMBER_MP_GAMES]
Referenced by analyse_statistics(), and Server().
n_players_max
int Server::n_players_max[NUMBER_MP_GAMES]
Referenced by analyse_statistics(), and Server().
n_players_sum
int Server::n_players_sum[NUMBER_MP_GAMES]
Referenced by analyse_statistics(), and Server().
next_broadcast
int Server::next_broadcast
Referenced by quant(), and Server().
playing_time_max
int Server::playing_time_max[NUMBER_MP_GAMES]
Referenced by analyse_statistics(), and Server().
playing_time_sum
int Server::playing_time_sum[NUMBER_MP_GAMES]
Referenced by analyse_statistics(), and Server().
rating_list
XTList<RatingData> Server::rating_list
Referenced by add_rating_data(), get_top_list(), load_rating_list(), save_rating_list(), search_rating_data(), and ~Server().
rating_threshoulds
float Server::rating_threshoulds[NUMBER_MP_GAMES]
Referenced by add_rating_data(), and load_rating_list().
time_to_destroy
unsigned int Server::time_to_destroy
Referenced by quant(), and Server().
time_to_live
unsigned int Server::time_to_live
Referenced by quant(), and Server().
transferring
int Server::transferring
Referenced by quant(), and Server().
The documentation for this struct was generated from the following files:
server/server.h
server/server.cpp