Vangers: CyclicEngine Struct Reference
CyclicEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Quant (void)
Public Member Functions inherited from LocationEngine
virtual void Close (void)
virtual void Link (void)
virtual void Touch (GeneralObject *obj, SensorDataType *p)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
SensorDataType ** ActionLink
int Time
int ActionMode
int NumAction
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Open()
void CyclicEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     char* n;
     int i;
     LocationEngine::Open(in);
     in.search_name("ActionMode");
     ActionMode = in.get_int();
     if(ActionMode > -1){
         in.search_name("NumActionLink");
         NumAction = in.get_int();
         ActionLink = new SensorDataType*[NumAction];
         for(i = 0;i < NumAction;i++){
             in.search_name("ActionName");
             n = in.get_name();
             ActionLink[i] = FindSensor(n);
             if(!ActionLink[i])
                 ErrH.Abort("Bad Find Sensor");
             ActionLink[i]->Enable = 0;
             ActionLink[i]->Owner = this;
         };
     }else ActionLink = NULL;
     Type = EngineTypeList::CYCLIC;
     Time = 0;
     Mode = EngineModeList::SEND_PROCESS;
 //  MLLink->setStaticPhase(DeactivePhase);
     MLLink->goKeyPhase(DeactivePhase);
 };
References XErrorHandler::Abort(), ActionLink, ActionMode, EngineTypeList::CYCLIC, LocationEngine::DeactivePhase, StaticObject::Enable, ErrH, FindSensor(), Parser::get_int(), Parser::get_name(), MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, NULL, NumAction, LocationEngine::Open(), SensorDataType::Owner, Parser::search_name(), EngineModeList::SEND_PROCESS, Time, and LocationEngine::Type.
Quant()
void CyclicEngine::Quant (void) virtual
Reimplemented from LocationEngine.
 {
     int i;
     if(!MLLink) return;
     if(!MLLink->frozen){
         if(MLLink->isGoFinish()){
             if(abs(getDistY(YCYCL(MLLink->table[MLLink->cFrame].y0 - MLLink->table[MLLink->cFrame].sy / 2),ViewY)) > (TurnSideY + MLLink->table[MLLink->cFrame].sy) ||
                abs(getDistX(XCYCL(MLLink->table[MLLink->cFrame].x0 - MLLink->table[MLLink->cFrame].sx / 2),ViewX)) > (TurnSideX + MLLink->table[MLLink->cFrame].sx))
                 return;
             switch(Mode){
                 case EngineModeList::ACCEPT_PROCESS:
                     Time++;
                     if(Time > DeactiveTime){
                         MLLink->goKeyPhase(ActivePhase);
                         SoundEvent();
                         Time = 0;
                         Mode = EngineModeList::ACCEPT_DELAY;
                     };
                     break;
                 case EngineModeList::ACCEPT_DELAY:
                     Mode = EngineModeList::ACCEPT_PROCESS_END;
                     break;
                 case EngineModeList::ACCEPT_PROCESS_END:
                     Time++;
                     if(Time > ActiveTime){
                         MLLink->goKeyPhase(DeactivePhase);
                         SoundEvent();
                         Time = 0;
                         Mode = EngineModeList::SEND_PROCESS;
                     };
                     break;
                 case EngineModeList::SEND_PROCESS:
                     Mode = EngineModeList::ACCEPT_PROCESS;
                     break;
             };
         };
         if(ActionLink){
             if(Mode == ActionMode){
                 for(i = 0;i < NumAction;i++)
                     ActionLink[i]->Enable = 1;
             }else{
                 for(i = 0;i < NumAction;i++)
                     ActionLink[i]->Enable = 0;
             };
         };
     }else{
 //      MLLink->goKeyPhase(DeactivePhase);
         Mode = EngineModeList::SEND_PROCESS;
         Time = 0;
     };
 };
References EngineModeList::ACCEPT_DELAY, EngineModeList::ACCEPT_PROCESS, EngineModeList::ACCEPT_PROCESS_END, ActionLink, ActionMode, LocationEngine::ActivePhase, LocationEngine::ActiveTime, MobileLocation::cFrame, LocationEngine::DeactivePhase, LocationEngine::DeactiveTime, LocationEngine::Enable, MobileLocation::frozen, getDistX(), getDistY(), MobileLocation::goKeyPhase(), MobileLocation::isGoFinish(), LocationEngine::MLLink, LocationEngine::Mode, NumAction, EngineModeList::SEND_PROCESS, LocationEngine::SoundEvent(), MLFrame::sx, MLFrame::sy, MobileLocation::table, Time, TurnSideX, TurnSideY, ViewX, ViewY, MLFrame::x0, XCYCL, MLFrame::y0, and YCYCL.
Member Data Documentation
ActionLink
SensorDataType** CyclicEngine::ActionLink
Referenced by Open(), and Quant().
ActionMode
int CyclicEngine::ActionMode
Referenced by Open(), and Quant().
NumAction
int CyclicEngine::NumAction
Referenced by Open(), and Quant().
Time
int CyclicEngine::Time
Referenced by Open(), and Quant().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp