Vangers: SkyFarmerList Struct Reference
SkyFarmerList Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void Free (void)
SkyFarmerObject * CreateSkyFarmer (void)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Quant (void)
virtual void NetEvent (int type, int id)
virtual void FreeUnit (GeneralObject *p)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Additional Inherited Members
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
CreateSkyFarmer()
SkyFarmerObject * SkyFarmerList::CreateSkyFarmer (void)
 {
     SkyFarmerObject* p;
     p = new SkyFarmerObject;
     p->Init();
     ConnectTypeList(p);
     return p;
 };
References UnitBaseListType::ConnectTypeList(), and SkyFarmerObject::Init().
Referenced by addFarmer().
Free()
void SkyFarmerList::Free (void) virtual
Reimplemented from UnitListType.
 {
     int i;
     uvsFlyFarmer* l;
     GeneralObject* p;
     GeneralObject* pp;
 //  FreeFarmer(WorldTable[GameD.cWorld]->Panymal);
     p = Tail;
     while(p){
         pp = p->NextTypeList;
         l = new uvsFlyFarmer(((SkyFarmerObject*)(p))->CornType,WorldTable[CurrentWorld]);
 //      l->timer = ((SkyFarmerObject*)(p))->Timer;
         l->timer = 0;
 //      l->corn = ((SkyFarmerObject*)(p))->Corn;
         l->corn = 25;
         l->x_speed = ((SkyFarmerObject*)(p))->xSpeed;
         l->y_speed = ((SkyFarmerObject*)(p))->ySpeed;
         l->pos_x = ((SkyFarmerObject*)(p))->R_curr.x;
         l->pos_y = ((SkyFarmerObject*)(p))->R_curr.y;
         l -> elink(WorldTable[CurrentWorld]->Panymal);
         FreeUnit(p);
         p = pp;
     };
     for(i = 0;i < SkyFarmerWayTableSize;i++)
         SkyFarmerWayTable[i].Close();
     delete[] SkyFarmerWayTable;
 };
References uvsFlyFarmer::corn, CurrentWorld, UnitListType::FreeUnit(), GeneralObject::NextTypeList, uvsTarget::pos_x, uvsTarget::pos_y, SkyFarmerWayTable, SkyFarmerWayTableSize, UnitListType::Tail, uvsFlyFarmer::timer, WorldTable, uvsFlyFarmer::x_speed, and uvsFlyFarmer::y_speed.
Referenced by GeneralSystemClose().
Init()
void SkyFarmerList::Init (void) virtual
Reimplemented from UnitListType.
 {
     int i;
     uvsElement* l;
     char sign[8];
     int FlyCount,CheckFlyCount;
     XStream ff;
     ff.open("resource/crypts/skyfarmer.vlc",XS_IN);
     ff.read(sign,strlen("VLS1"));
     if(memcmp(sign,"VLS1",strlen("VLS1"))) ErrH.Abort("Bad SkyFarmer Way Point Format");
     ff > SkyFarmerWayTableSize;
     SkyFarmerWayTable = new SensorDataType[SkyFarmerWayTableSize];
     FlyCount = 0;
     CheckFlyCount = 0;
     for(i = 0;i < SkyFarmerWayTableSize;i++){
         SkyFarmerWayTable[i].CreateSensor(ff);
         if(SkyFarmerWayTable[i].SensorType < 0 && SkyFarmerWayTable[i].SensorType >= SkyFarmerWayTableSize)
             ErrH.Abort("Bad Sky Farmer Object");
         FlyCount += SkyFarmerWayTable[i].SensorType;
         CheckFlyCount += i;
 //      if(FlyCount != CheckFlyCount)
 //          ErrH.Abort("GASDHgJGDS");
     };
     UnitBaseListType::Init();
     l = WorldTable[GameD.cWorld]->Panymal;
     while(l){
         addFarmer(((uvsFlyFarmer*)(l))->pos_x,((uvsFlyFarmer*)(l))->pos_y,((uvsFlyFarmer*)(l))->x_speed,((uvsFlyFarmer*)(l))->y_speed,((uvsFlyFarmer*)(l))->corn_type,((uvsFlyFarmer*)(l))->corn,((uvsFlyFarmer*)(l))->timer);
         l = l->enext;
     };
     FreeFarmer(WorldTable[CurrentWorld]->Panymal);
 };
References XErrorHandler::Abort(), addFarmer(), SensorDataType::CreateSensor(), CurrentWorld, GameObjectDispatcher::cWorld, uvsElement::enext, ErrH, FreeFarmer(), GameD, UnitListType::Init(), XStream::open(), uvsWorld::Panymal, XStream::read(), SensorDataType::SensorType, SkyFarmerWayTable, SkyFarmerWayTableSize, WorldTable, and XS_IN.
Referenced by GeneralSystemOpen().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp