Vangers: iScreenDispatcher Struct Reference
iScreenDispatcher Struct Reference
#include <iscreen.h>
Public Member Functions
void init_texts (void)
void finit_texts (void)
void next_text (void)
void prev_text (void)
int copy_text_next (iScreen *p, int mode)
int copy_text_prev (iScreen *p, int mode)
iTextData * get_text (int id)
void key_trap (int sc)
void CheckScanCode (int sc)
void HandleEvent (iScreenEvent *ev)
void EventQuant (void)
void ProcessEvent (iScreenEvent *p)
void end_event (void)
void input_string_quant (void)
void init_input_string (iScreenElement *p)
void prepare (void)
void redraw (int mode=0)
void redraw_quant (void)
void flush_quant (void)
void set_scr_redraw (iScreen *p)
void set_obj_redraw (iScreenObject *p)
void hide_screen (iScreen *p)
void show_screen (iScreen *p)
void alloc_mem (void)
void free_mem (void)
int check_id (char *p)
iListElement * get_object (const char *p)
void move_screen (int val, int time)
void aci_move_screen (int val, int time)
void move2screen (iScreen *p, int time)
void lock_events (void)
void unlock_events (void)
void add_ext_screen (iScreen *p)
void remove_ext_screen (iScreen *p)
iScreen * get_ext_screen (const char *p)
void pal_quant (void)
void save_data (XStream *fh)
void load_data (XStream *fh)
iScreenDispatcher (void)
Public Member Functions inherited from iList
void connect (iListElement *p)
void dconnect (iListElement *p)
void init_list (void)
void swap (iListElement *p, iListElement *p1)
iList (void)
Public Attributes
int flags
iScreen * curScr
char * t_scrID
unsigned char * curPal
unsigned char * trgPal
int ret_val
int cur_max_input
iScreenEvent * ActiveEv
iScreenElement * ActiveEl
iList * ObjHeap
iList * drwObjHeap
iList * ScreenIDs
iList * ExtScreens
iTextData * curText
iList * texts
Public Attributes inherited from iList
int Size
int index
iListElement * first
iListElement * last
Detailed Description
Constructor & Destructor Documentation
iScreenDispatcher()
iScreenDispatcher::iScreenDispatcher (void)
 {
     init_list();
     drwObjHeap = new iList;
     ObjHeap = new iList;
     ScreenIDs = new iList;
     ExtScreens = new iList;
     texts = new iList;
     ActiveEv = NULL;
     flags = 0;
     BackupStr = new char[256];
     curPal = new unsigned char[768];
     trgPal = new unsigned char[768];
     memset(curPal,0,768);
     memset(trgPal,0,768);
 }
References ActiveEv, BackupStr, curPal, drwObjHeap, ExtScreens, flags, iList::iList(), iList::init_list(), NULL, ObjHeap, ScreenIDs, texts, and trgPal.
Member Function Documentation
aci_move_screen()
void iScreenDispatcher::aci_move_screen (int val, int time)
 {
     int i;
     iScreenOffsDelta = val / time;
     iScreenTargetOffs = iScreenOffs + val;
     XGR_MouseHide();
     if(actIntLog){
         aScrDisp -> flags &= ~AS_FULL_REDRAW;
         aScrDisp -> flags &= ~AS_FULL_FLUSH;
         aScrDisp -> i_redraw();
         redraw_quant();
         aScrDisp -> flags &= ~AS_FULL_REDRAW;
         aScrDisp -> flags &= ~AS_FULL_FLUSH;
         aScrDisp -> i_redraw();
         aScrDisp -> i_flush();
         curScr -> show_avi();
     }
     for(i = 0; i < time; i ++){
         iScreenOffs += iScreenOffsDelta;
         put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
         if(i == time - 1){
             iScreenOffs = iScreenTargetOffs;
             iScreenOffsDelta = 0;
         }
         XGR_Flush(0,0,I_RES_X,I_RES_Y);
     }
     XGR_MouseShow();
     XGR_MouseObj.PromptDeltaX = iScreenOffs;
 }
References actIntLog, AS_FULL_FLUSH, AS_FULL_REDRAW, aScrDisp, curScr, flags, I_RES_X, I_RES_Y, iScreenOffs, iScreenOffsDelta, iScreenTargetOffs, XGR_Mouse::PromptDeltaX, put_map(), redraw_quant(), XGR_Flush, XGR_MouseHide, XGR_MouseObj, and XGR_MouseShow.
Referenced by move2screen().
add_ext_screen()
void iScreenDispatcher::add_ext_screen (iScreen * p)
 {
     ExtScreens -> connect((iListElement*)p);
 }
References iList::connect(), and ExtScreens.
alloc_mem()
void iScreenDispatcher::alloc_mem (void)
 {
     iScreenObject* obj;
     _iALLOC_HEAP_(I_MEM_HEAP_SIZE,char);
     if(!actIntLog){
         obj = (iScreenObject*)ObjHeap -> last;
         while(obj){
             obj -> load_data();
             obj -> getfon();
             obj = (iScreenObject*)obj -> prev;
         }
     }
     curScr -> load_data();
     ret_val = 0;
 }
References _iALLOC_HEAP_, actIntLog, curScr, I_MEM_HEAP_SIZE, iList::last, load_data(), ObjHeap, prev, and ret_val.
check_id()
int iScreenDispatcher::check_id (char * p)
 {
     iObjID* id = (iObjID*)ScreenIDs -> last;
     while(id){
         if(id -> compare(p))
             return 1;
         id = (iObjID*)id -> prev;
     }
     return 0;
 }
References compare(), iList::last, prev, and ScreenIDs.
CheckScanCode()
void iScreenDispatcher::CheckScanCode (int sc)
 {
     int x = 0,y = 0,mouse_sc = 0;
     iScreenObject* obj;
     iListElement* cd;
     iScreenEvent* p;
     if(sc < 0){
         mouse_sc = 1;
         x = iMouseX + iScreenOffs;
         y = iMouseY;
     }
     if(!(curScr -> flags & iSCR_BLOCK_GLOBAL_OBJ)){
         obj = (iScreenObject*)ObjHeap -> last;
         while(obj){
             if(!ActiveEv){
                 if(!mouse_sc || obj -> CheckXY(x,y)){
                     p = (iScreenEvent*)obj -> EventList -> last;
                     while(p){
                         cd = p -> codes -> last;
                         while(cd){
                             if(((iScanCode*)cd) -> code == sc && (!(p -> flags & EV_IF_SELECTED) || obj -> flags & OBJ_SELECTED) && (!(p -> flags & EV_IF_NOT_SELECTED) || !(obj -> flags & OBJ_SELECTED)))
                                 HandleEvent(p);
                             cd = cd -> prev;
                         }
                         p = (iScreenEvent*)p -> prev;
                     }
                 }
             }
             obj = (iScreenObject*)obj -> prev;
         }
     }
 }
References ActiveEv, curScr, EV_IF_NOT_SELECTED, EV_IF_SELECTED, flags, HandleEvent(), iMouseX, iMouseY, iSCR_BLOCK_GLOBAL_OBJ, iScreenOffs, iList::last, OBJ_SELECTED, ObjHeap, and prev.
Referenced by key_trap().
copy_text_next()
int iScreenDispatcher::copy_text_next (iScreen * p, int mode)
 {
     int id,end_code,next_code;
     iScreenObject* obj = (iScreenObject*)scr -> get_object("Text00");
     iStringElement* title_obj = (iStringElement*)scr -> get_object("TextTitle00");
     if(obj){
         if(!curText){
             next_text();
         }
         else {
             if(curText -> eof()){
                 id = curText -> ID + 1;
                 ActiveEv -> flags &= ~EV_ACTIVE;
                 ActiveEv = NULL;
                 end_code = (mode) ? iTEXT_END_EVENT_CODE1 : iTEXT_END_EVENT_CODE0;
                 next_code = (mode) ? iTEXT_NEXT_EVENT_CODE1 : iTEXT_NEXT_EVENT_CODE0;
                 if(lang() != RUSSIAN){
                     if(id > iTEXT_ENG_MAX){
                         key_trap(end_code);
                     }
                     else {
                         next_text();
                         if(title_obj){
                             strcpy(title_obj -> string,curText -> objName);
                             title_obj -> init_size();
                             title_obj -> init_align();
                         }
                         key_trap(next_code);
                     }
                 }
                 else {
                     if(id > iTEXT_RUS_MAX){
                         key_trap(end_code);
                     }
                     else {
                         next_text();
                         if(title_obj){
                             strcpy(title_obj -> string,curText -> objName);
                             title_obj -> init_size();
                             title_obj -> init_align();
                         }
                         key_trap(next_code);
                     }
                 }
                 return 1;
             }
         }
         if(!curText) return 0;
         if(title_obj){
             strcpy(title_obj -> string,curText -> objName);
             title_obj -> init_size();
             title_obj -> init_align();
         }
         curText -> copy(obj);
     }
     return 0;
 }
References ActiveEv, curText, EV_ACTIVE, flags, get_object(), iTEXT_END_EVENT_CODE0, iTEXT_END_EVENT_CODE1, iTEXT_ENG_MAX, iTEXT_NEXT_EVENT_CODE0, iTEXT_NEXT_EVENT_CODE1, iTEXT_RUS_MAX, key_trap(), lang(), next_text(), NULL, and RUSSIAN.
Referenced by ProcessEvent().
copy_text_prev()
int iScreenDispatcher::copy_text_prev (iScreen * p, int mode)
 {
     int id,prev_code;
     iScreenObject* obj = (iScreenObject*)scr -> get_object("Text00");
     iStringElement* title_obj = (iStringElement*)scr -> get_object("TextTitle00");
     if(obj){
         if(!curText){
             next_text();
         }
         else {
             if(curText -> curLine <= obj -> ElementList -> Size){
                 id = curText -> ID - 1;
                 ActiveEv -> flags &= ~EV_ACTIVE;
                 ActiveEv = NULL;
                 prev_code = (mode) ? iTEXT_PREV_EVENT_CODE1 : iTEXT_PREV_EVENT_CODE0;
                 if((lang() != RUSSIAN && id > 0) || id > iTEXT_RUS1_ID - 1){
                     prev_text();
                     if(title_obj){
                         strcpy(title_obj -> string,curText -> objName);
                         title_obj -> init_size();
                         title_obj -> init_align();
                     }
                     curText -> curLine = curText -> numLines - (curText -> numLines % obj -> ElementList -> Size) + obj -> ElementList -> Size * 2;
                     key_trap(prev_code);
                 }
                 return 1;
             }
             else {
                 if(curText -> curLine >= obj -> ElementList -> Size * 2){
                     if(curText -> curLine != curText -> numLines)
                         curText -> curLine -= obj -> ElementList -> Size * 2;
                     else
                         curText -> curLine -= obj -> ElementList -> Size + (curText -> numLines % obj -> ElementList -> Size);
                 }
                 else {
                     ActiveEv -> flags &= ~EV_ACTIVE;
                     ActiveEv = NULL;
                     return 1;
                 }
             }
         }
         if(!curText) return 0;
         if(title_obj){
             strcpy(title_obj -> string,curText -> objName);
             title_obj -> init_size();
             title_obj -> init_align();
         }
         curText -> flags &= ~iTEXT_EOF;
         curText -> copy(obj);
     }
     return 0;
 }
References ActiveEv, curText, EV_ACTIVE, flags, get_object(), iTEXT_EOF, iTEXT_PREV_EVENT_CODE0, iTEXT_PREV_EVENT_CODE1, iTEXT_RUS1_ID, key_trap(), lang(), next_text(), NULL, prev_text(), RUSSIAN, and iList::Size.
Referenced by ProcessEvent().
end_event()
void iScreenDispatcher::end_event (void)
 {
     if(ActiveEv){
         ActiveEv -> flags &= ~EV_ACTIVE;
         ActiveEv = NULL;
     }
 }
References ActiveEv, EV_ACTIVE, flags, and NULL.
EventQuant()
void iScreenDispatcher::EventQuant (void)
 {
     int hp_offs = iHeapOffs;
     iListElementPtr* tmp;
     iScreenObject* obj;
     if(flags & SD_INPUT_STRING){
         input_string_quant();
     }
     else {
         if(ActiveEv){
             ProcessEvent(ActiveEv);
         }
     }
     obj = (iScreenObject*)curScr -> objList -> last;
     while(obj){
         if(obj -> flags & OBJ_AVI_PRESENT)
             set_obj_redraw(obj);
         if(obj -> flags & OBJ_MUST_REDRAW){
             obj -> flags ^= OBJ_MUST_REDRAW;
             set_obj_redraw(obj);
         }
         obj = (iScreenObject*)obj -> prev;
     }
     redraw_quant();
     tmp = (iListElementPtr*)drwObjHeap -> last;
     while(tmp){
         obj = (iScreenObject*)tmp -> ptr;
         obj -> flush();
         obj -> flags &= ~OBJ_REDRAW;
         tmp = (iListElementPtr*)tmp -> prev;
     }
     drwObjHeap -> init_list();
     iHeapOffs = hp_offs;
     if(flags & SD_PAL_CHANGE){
         pal_quant();
     }
 #ifdef SCREENSHOT
     shotMake(1);
 #endif
 }
References ActiveEv, curScr, drwObjHeap, flags, flush(), iHeapOffs, iList::init_list(), input_string_quant(), iList::last, OBJ_AVI_PRESENT, OBJ_MUST_REDRAW, OBJ_REDRAW, pal_quant(), prev, ProcessEvent(), redraw_quant(), SD_INPUT_STRING, SD_PAL_CHANGE, set_obj_redraw(), and shotMake().
finit_texts()
void iScreenDispatcher::finit_texts (void)
 {
     iTextData* p = (iTextData*)texts -> last;
     while(p){
         p -> free();
         p = (iTextData*)p -> prev;
     }
 }
References iList::last, prev, and texts.
flush_quant()
void iScreenDispatcher::flush_quant (void)
 {
     iListElementPtr* tmp;
     iScreenObject* obj;
     tmp = (iListElementPtr*)drwObjHeap -> last;
     while(tmp){
         obj = (iScreenObject*)tmp -> ptr;
         obj -> flush();
         obj -> flags &= ~OBJ_REDRAW;
         tmp = (iListElementPtr*)tmp -> prev;
     }
 }
References drwObjHeap, flags, flush(), iList::last, OBJ_REDRAW, and prev.
Referenced by move2screen().
free_mem()
void iScreenDispatcher::free_mem (void)
 {
     iScreenObject* obj;
     if(!actIntLog){
         obj = (iScreenObject*)ObjHeap -> last;
         while(obj){
             obj -> free_data();
             obj = (iScreenObject*)obj -> prev;
         }
     }
     curScr -> free_data();
     _iFREE_HEAP_(I_MEM_HEAP_SIZE,char);
 }
References _iFREE_HEAP_, actIntLog, curScr, free_data(), I_MEM_HEAP_SIZE, iList::last, ObjHeap, and prev.
get_ext_screen()
iScreen * iScreenDispatcher::get_ext_screen (const char * p)
 {
     iScreen* s = (iScreen*)ExtScreens -> last;
     while(s){
         if(s->ID_ptr!=p)
             return s;
         s = (iScreen*)s -> prev;
     }
     return NULL;
 }
References ExtScreens, iListElement::ID_ptr, iList::last, NULL, and prev.
Referenced by ProcessEvent().
get_object()
iListElement * iScreenDispatcher::get_object (const char * p)
 {
     iObjID* id = (iObjID*)ScreenIDs -> last;
     while(id){
         if(id -> compare(p))
             return id -> obj;
         id = (iObjID*)id -> prev;
     }
     return NULL;
 }
References compare(), iList::last, NULL, prev, and ScreenIDs.
Referenced by copy_text_next(), and copy_text_prev().
get_text()
iTextData * iScreenDispatcher::get_text (int id)
 {
     iTextData* p = (iTextData*)texts -> last;
     while(p){
         if(p -> ID == id) return p;
         p = (iTextData*)p -> prev;
     }
     return NULL;
 }
References iList::last, NULL, prev, and texts.
Referenced by next_text(), and prev_text().
HandleEvent()
void iScreenDispatcher::HandleEvent (iScreenEvent * ev)
 {
     iScreenEventCommand* p = (iScreenEventCommand*)ev -> CommSeq -> last;
     while(p){
         if(p -> EvType == EV_OBJECT_JUMP){
             if(p -> objID == curScr -> curObj -> ID)
                 return;
         }
         p = (iScreenEventCommand*)p -> prev;
     }
     if(!(ev -> flags & EV_ACTIVE)){
         ev -> flags |= EV_ACTIVE;
         ev -> cur_time = 0;
         ActiveEv = ev;
         SOUND_SELECT();
     }
 }
References ActiveEv, curScr, EV_ACTIVE, EV_OBJECT_JUMP, flags, iList::last, prev, and SOUND_SELECT.
Referenced by CheckScanCode().
hide_screen()
void iScreenDispatcher::hide_screen (iScreen * p)
 {
     iScreenObject* obj = (iScreenObject*)p -> objList -> last;
     while(obj){
         obj -> curHeightScale = 0;
         obj -> flags |= OBJ_HIDE;
         obj = (iScreenObject*)obj -> prev;
     }
     obj = (iScreenObject*)p -> TerrainList -> last;
     while(obj){
         ((iTerrainElement*)obj -> ElementList -> last) -> null_level = 0;
         obj -> curHeightScale = 0;
         obj -> flags |= OBJ_HIDE;
         obj = (iScreenObject*)obj -> prev;
     }
     set_scr_redraw(p);
 }
References flags, iList::last, OBJ_HIDE, prev, and set_scr_redraw().
Referenced by move2screen().
init_input_string()
void iScreenDispatcher::init_input_string (iScreenElement * p)
 {
     int sz;
     iListElementPtr* tmp;
     iScreenObject* obj;
     unsigned char* ptr = NULL;
     switch(p -> type){
         case I_STRING_ELEM:
             ptr = (unsigned char*)(((iStringElement*)p) -> string);
             break;
         case I_S_STRING_ELEM:
             ptr = (unsigned char*)(((iS_StringElement*)p) -> string);
             break;
         default:
             ErrH.Abort("Bad input string type...");
             break;
     }
     strcpy(BackupStr,(char*)ptr);
     sz = strlen((char*)ptr);
     if(p -> flags & EL_KEY_NAME){
         sz = 0;
     }
     ptr[sz] = '_';
     ptr[sz + 1] = 0;
     obj = (iScreenObject*)p -> owner;
     obj -> flags |= OBJ_REINIT;
     if(!(obj -> flags & OBJ_REDRAW)){
         obj -> flags |= OBJ_REDRAW;
         _iALLOC_(iListElementPtr,tmp);
         tmp -> ptr = (iListElement*)obj;
         drwObjHeap -> connect((iListElement*)tmp);
     }
     ActiveEl = p;
     flags |= SD_INPUT_STRING;
 }
References _iALLOC_, XErrorHandler::Abort(), ActiveEl, BackupStr, iList::connect(), drwObjHeap, EL_KEY_NAME, ErrH, flags, I_S_STRING_ELEM, I_STRING_ELEM, NULL, OBJ_REDRAW, OBJ_REINIT, and SD_INPUT_STRING.
init_texts()
void iScreenDispatcher::init_texts (void)
 {
     iTextData* p = (iTextData*)texts -> last;
     while(p){
         p -> load();
         p = (iTextData*)p -> prev;
     }
     curText = NULL;
 }
References curText, iList::last, NULL, prev, and texts.
input_string_quant()
void iScreenDispatcher::input_string_quant (void)
 {
     int k,sz,init_flag = 0,redraw_flag = 0,code,shift_flag = 0;
     iListElementPtr* tmp;
     iScreenObject* obj;
     unsigned char* ptr = NULL;
     HFont* hfnt = NULL;
     const char* key_name = NULL;
     switch(ActiveEl -> type){
         case I_STRING_ELEM:
             ptr = (unsigned char*)(((iStringElement*)ActiveEl) -> string);
             hfnt = HFntTable[(((iStringElement*)ActiveEl) -> font)];
             break;
         case I_S_STRING_ELEM:
             ptr = (unsigned char*)(((iS_StringElement*)ActiveEl) -> string);
             break;
         default:
             ErrH.Abort("Bad input string type...");
             break;
     }
     while(KeyBuf -> size) {
         SDL_Event *event = KeyBuf->get();
         //TODO: UTF8 fix
         if (event->type != SDL_KEYDOWN)
             continue;
         k = sdlEventToCode(event);
         if(!(k & 0x1000)) {
             if(!(ActiveEl -> flags & EL_KEY_NAME)){
                 switch(k){
                     case SDL_SCANCODE_RETURN:
                         sz = strlen((char*)ptr);
                         ptr[sz - 1] = 0;
                         flags ^= SD_INPUT_STRING;
                         flags |= SD_FINISH_INPUT;
                         init_flag = 1;
                         redraw_flag = 1;
                         break;
                     case SDL_SCANCODE_ESCAPE:
                         strcpy((char*)ptr,BackupStr);
                         flags ^= SD_INPUT_STRING;
                         flags |= SD_FINISH_INPUT;
                         init_flag = 1;
                         redraw_flag = 1;
                         break;
                     case SDL_SCANCODE_LEFT:
                     case SDL_SCANCODE_BACKSPACE:
                         sz = strlen((char*)ptr);
                         if(sz > 1){
                             ptr[sz - 1] = 0;
                             ptr[sz - 2] = '_';
                             init_flag = 1;
                             redraw_flag = 1;
                         }
                         break;
                     default:
                         if(!(ActiveEl -> flags & EL_NUMBER)){
                             if(KeyBuf -> flag & SHIFT_PRESSED) shift_flag = 1;
                             code = SDL_GetKeyFromScancode((SDL_Scancode)k);
                             if(code && hfnt && code < hfnt->NumChars){
                                 if((hfnt -> data[code] -> Flags & NULL_HCHAR) && code != ' ')
                                     break;
                                 sz = strlen((char*)ptr);
                                 if(sz < cur_max_input){
                                     ptr[sz - 1] = code;
                                     ptr[sz] = '_';
                                     ptr[sz + 1] = 0;
                                     init_flag = 1;
                                     redraw_flag = 1;
                                 }
                             }
                         }
                         else {
                             if(KeyBuf -> flag & SHIFT_PRESSED) shift_flag = 1;
                             code = SDL_GetKeyFromScancode((SDL_Scancode)k);
                             if(code && code >= '0' && code <= '9'){
                                 if(hfnt && (hfnt -> data[code] -> Flags & NULL_HCHAR) && code != ' ')
                                     break;
                                 sz = strlen((char*)ptr);
                                 if(sz < cur_max_input){
                                     ptr[sz - 1] = code;
                                     ptr[sz] = '_';
                                     ptr[sz + 1] = 0;
                                     init_flag = 1;
                                     redraw_flag = 1;
                                 }
                             }
                         }
                         break;
                 }
             }
             else {
                 switch(k){
                     case SDL_SCANCODE_ESCAPE:
                         strcpy((char*)ptr,BackupStr);
                         flags ^= SD_INPUT_STRING;
                         flags |= SD_FINISH_INPUT;
                         init_flag = 1;
                         redraw_flag = 1;
                         iScreenLastInput = k;
                         break;
                     default:
                         //NEED rewrite
                         /*if(!(k & iJOYSTICK_MASK))
                             key_name = iGetKeyNameText(k,lang());
                         else
                             key_name = iGetJoyBtnNameText(k,lang());
                         */
                         key_name = iGetKeyNameText(k,lang());
                         if(flags & SD_INPUT_STRING && key_name){
                             if(!(ActiveEl -> flags & EL_JOYSTICK_KEY) || (k & iJOYSTICK_MASK)){
                                 strcpy((char*)ptr,key_name);
                                 flags ^= SD_INPUT_STRING;
                                 flags |= SD_FINISH_INPUT;
                                 init_flag = 1;
                                 redraw_flag = 1;
                                 iScreenLastInput = k;
                             }
                         }
                         break;
                 }
             }
         }
     }
     if(init_flag){
         obj = (iScreenObject*)ActiveEl -> owner;
         obj -> flags |= OBJ_REINIT;
     }
     else {
         if(iFrameFlag){
             sz = strlen((char*)ptr);
             if(ptr[sz - 1] == ' ')
                 ptr[sz - 1] = '_';
             else
                 ptr[sz - 1] = ' ';
             ptr[sz] = 0;
             redraw_flag = 1;
         }
     }
     if(redraw_flag){
         obj = (iScreenObject*)ActiveEl -> owner;
         if(!(obj -> flags & OBJ_REDRAW)){
             obj -> flags |= OBJ_REDRAW;
             _iALLOC_(iListElementPtr,tmp);
             tmp -> ptr = (iListElement*)obj;
             drwObjHeap -> connect((iListElement*)tmp);
         }
     }
     iFrameFlag = 0;
 }
References _iALLOC_, XErrorHandler::Abort(), ActiveEl, BackupStr, iList::connect(), cur_max_input, drwObjHeap, EL_JOYSTICK_KEY, EL_KEY_NAME, EL_NUMBER, ErrH, flags, KeyBuffer::get(), HFntTable, I_S_STRING_ELEM, I_STRING_ELEM, iFrameFlag, iGetKeyNameText(), iJOYSTICK_MASK, iScreenLastInput, KeyBuf, lang(), NULL, NULL_HCHAR, OBJ_REDRAW, OBJ_REINIT, SD_FINISH_INPUT, SD_INPUT_STRING, sdlEventToCode(), and SHIFT_PRESSED.
Referenced by EventQuant().
key_trap()
void iScreenDispatcher::key_trap (int sc)
 {
     if(!actIntLog)
         CheckScanCode(sc);
     curScr -> CheckScanCode(sc);
 }
References actIntLog, CheckScanCode(), and curScr.
Referenced by copy_text_next(), and copy_text_prev().
load_data()
void iScreenDispatcher::load_data (XStream * fh)
 {
     int i,num_opt;
     *fh > num_opt;
     if(num_opt != iMAX_OPTION_ID) return;
     for(i = 0; i < iMAX_OPTION_ID; i ++){
         if(iScrOpt[i])
             iScrOpt[i] -> load(fh);
     }
 }
References iMAX_OPTION_ID, and iScrOpt.
Referenced by alloc_mem(), move2screen(), and ProcessEvent().
lock_events()
void iScreenDispatcher::lock_events (void)
 {
     if(ActiveEv) ActiveEv = NULL;
     flags |= SD_LOCK_EVENTS;
 }
References ActiveEv, flags, NULL, and SD_LOCK_EVENTS.
move2screen()
void iScreenDispatcher::move2screen (iScreen * p, int time)
 {
     iScreen* cp = curScr;
     int delta = p -> ScreenOffs - iScreenOffs;
     curScr = p;
     if(p != cp)
         p -> load_data();
     if(actIntLog){
         aci_setMatrixBorder();
         aci_setScMatrixBorder();
     }
     if(p -> pal_name)
         XGR_SetPal(p -> palette_buf,0,255);
     if(!delta){
         if(p != cp){
             hide_screen(cp);
             redraw_quant();
             flags |= (SD_GETFON | SD_END_GETFON);
             show_screen(p);
             redraw_quant();
             flush_quant();
         }
         else {
             show_screen(p);
             redraw_quant();
             flush_quant();
         }
     }
     else {
 //      if(p != cp)
 //          p -> load_data();
         show_screen(p);
         flags |= (SD_GETFON | SD_END_GETFON);
         redraw_quant();
         p -> show_avi();
         p -> hide_avi();
         if(actIntLog)
             aci_move_screen(delta,time);
         else
             move_screen(delta,time);
         drwObjHeap -> init_list();
         hide_screen(cp);
         redraw_quant();
         cp -> hide_avi_place();
     }
     drwObjHeap -> init_list();
     if(p != cp)
         cp -> free_data();
 }
References aci_move_screen(), aci_setMatrixBorder(), aci_setScMatrixBorder(), actIntLog, curScr, drwObjHeap, flags, flush_quant(), free_data(), hide_screen(), iList::init_list(), iScreenOffs, load_data(), move_screen(), redraw_quant(), SD_END_GETFON, SD_GETFON, show_screen(), and XGR_SetPal.
move_screen()
void iScreenDispatcher::move_screen (int val, int time)
 {
     int i;
     iScreenOffsDelta = val / time;
     iScreenTargetOffs = iScreenOffs + val;
     XGR_MouseHide();
     for(i = 0; i < time; i ++){
         iScreenOffs += iScreenOffsDelta;
         if(i == time - 1){
             iScreenOffs = iScreenTargetOffs;
             iScreenOffsDelta = 0;
         }
         put_map(iScreenOffs,0,I_RES_X,I_RES_Y);
         //XGR_Flush(0,0,I_RES_X,I_RES_Y);
         xtClearMessageQueue();
     }
     XGR_MouseShow();
     XGR_MouseObj.PromptDeltaX = iScreenOffs;
 }
References I_RES_X, I_RES_Y, iScreenOffs, iScreenOffsDelta, iScreenTargetOffs, XGR_Mouse::PromptDeltaX, put_map(), XGR_MouseHide, XGR_MouseObj, XGR_MouseShow, and xtClearMessageQueue().
Referenced by move2screen().
next_text()
void iScreenDispatcher::next_text (void)
 {
     int id = 0;
     if(curText) id = curText -> ID + 1;
     if(lang() != RUSSIAN){
         if(!id || id > iTEXT_ENG_MAX)
             id = iTEXT_ENG1_ID;
     }
     else {
         if(!id || id > iTEXT_RUS_MAX)
             id = iTEXT_RUS1_ID;
     }
     curText = get_text(id);
     if(!curText) return;
     curText -> reset();
 }
References curText, get_text(), iTEXT_ENG1_ID, iTEXT_ENG_MAX, iTEXT_RUS1_ID, iTEXT_RUS_MAX, lang(), and RUSSIAN.
Referenced by copy_text_next(), and copy_text_prev().
pal_quant()
void iScreenDispatcher::pal_quant (void)
 {
     int i,flag = 0;
     unsigned val,t_val;
     for(i = I_PAL_OFFS; i < 768; i ++){
         val = curPal[i];
         t_val = trgPal[i];
         if(val != t_val){
             flag = 1;
             val += SD_PAL_DELTA;
             if(val > t_val) val = t_val;
             curPal[i] = val;
         }
     }
     XGR_SetPal(curPal + I_PAL_OFFS,I_PAL_START,I_PAL_SIZE);
     if(!flag) flags &= ~SD_PAL_CHANGE;
 }
References curPal, flags, I_PAL_OFFS, I_PAL_SIZE, I_PAL_START, SD_PAL_CHANGE, SD_PAL_DELTA, trgPal, and XGR_SetPal.
Referenced by EventQuant().
prepare()
void iScreenDispatcher::prepare (void)
 {
     iScreen* scr;
     iScreenObject* p = (iScreenObject*)ObjHeap -> last;
     while(p){
         if(p -> flags & OBJ_SELECTABLE){
             if(p -> flags & OBJ_SELECTED)
                 p -> curHeightScale = 256;
             else
                 p -> curHeightScale = I_UNSELECT_SCALE;
         }
         else
             p -> curHeightScale = 256;
         p = (iScreenObject*)p -> prev;
     }
     scr = (iScreen*)last;
     while(scr){
         if(scr != curScr){
             iScreenObject* p = (iScreenObject*)scr -> objList -> last;
             while(p){
                 p -> curHeightScale = 0;
                 p = (iScreenObject*)p -> prev;
             }
         }
         scr = (iScreen*)scr -> prev;
     }
 }
References curScr, flags, I_UNSELECT_SCALE, iList::last, OBJ_SELECTABLE, OBJ_SELECTED, ObjHeap, and prev.
Referenced by ProcessEvent(), and show_screen().
prev_text()
void iScreenDispatcher::prev_text (void)
 {
     int id = 0;
     if(curText) id = curText -> ID - 1;
     if(lang() != RUSSIAN){
         if(id <= 0)
             return;
     }
     else {
         if(id <= iTEXT_RUS1_ID - 1)
             return;
     }
     curText = get_text(id);
     if(!curText) return;
     curText -> reset();
 }
References curText, get_text(), iTEXT_RUS1_ID, lang(), and RUSSIAN.
Referenced by copy_text_prev().
ProcessEvent()
void iScreenDispatcher::ProcessEvent (iScreenEvent * p)
 {
     int i,sc;
     iScreenObject* obj;
     iScrollerElement* scl;
     iTriggerObject* trg;
     iScreenEventCommand* cm;
     iScreenElement* el;
     iAVIElement* avi_el;
     iList* list;
     iListElement* list_el;
     cm = (iScreenEventCommand*)p -> CommSeq -> last;
     while(cm){
         if(!(p -> flags & EV_MULTI_LINE) || !cm -> LineID || cm -> LineID == iEvLineID){
             if(cm -> time + cm -> start_time == p -> cur_time + 1){
                 EventFlag = cm -> EvType;
                 CurEvComm = cm;
             }
             if(cm -> start_time == p -> cur_time){
                 EventFlag = cm -> EvType;
                 CurEvComm = cm;
                 i_preExtQuant();
                 EventFlag = 0;
             }
             if(cm -> start_time == p -> cur_time){
                 switch(cm -> EvType){
                     case EV_LOCK_OBJ:
                         obj = (iScreenObject*)cm -> obj;
                         obj -> flags |= OBJ_LOCKED;
                         break;
                     case EV_UNLOCK_OBJ:
                         obj = (iScreenObject*)cm -> obj;
                         obj -> flags &= ~OBJ_LOCKED;
                         break;
                     case EV_EXT_EVENT:
                         iHandleExtEvent(cm -> value,cm -> data0);
                         break;
                     case EV_RESET_TEXTS:
                         curText = NULL;
                         iEvLineID = iTEXT_NORMAL;
                         break;
                     case EV_NEXT_TEXT:
                         if(copy_text_next((iScreen*)cm -> obj,cm -> value)) return;
                         break;
                     case EV_PREV_TEXT:
                         if(copy_text_prev((iScreen*)cm -> obj,cm -> value)) return;
                         break;
                     case EV_STOP_AVI:
                         avi_el = (iAVIElement*)cm -> obj;
                         obj = (iScreenObject*)avi_el -> owner;
                         avi_el -> flags |= AVI_STOPPED;
                         obj -> flags |= OBJ_AVI_STOPPED;
                         break;
                     case EV_PLAY_AVI:
                         avi_el = (iAVIElement*)cm -> obj;
                         obj = (iScreenObject*)avi_el -> owner;
                         avi_el -> flags &= ~AVI_STOPPED;
                         obj -> flags &= ~OBJ_AVI_STOPPED;
                         break;
                     case EV_RISE_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         obj -> HeightScaleDelta = (256 - obj -> curHeightScale) / cm -> time;
                         break;
                     case EV_HIDE_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         obj -> HeightScaleDelta = -obj -> curHeightScale / cm -> time;
                         obj -> flags |= OBJ_HIDE;
                         break;
                     case EV_LOW_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         obj -> HeightScaleDelta = (I_UNSELECT_SCALE - obj -> curHeightScale) / cm -> time;
                         break;
                     case EV_START_DEMO:
 //                      startRecorder();
                         break;
                     case EV_SCALE_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         obj -> HeightScaleDelta = (cm -> value - obj -> curHeightScale) / cm -> time;
                         break;
                     case EV_SMOOTH_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         if(cm -> value == obj -> SmoothLevel){
                             obj -> SmoothTime = 0;
                             obj -> SmoothDelta = 0;
                         }
                         else {
                             obj -> SmoothTime = cm -> time / (cm -> value - obj -> SmoothLevel);
                             if(obj -> SmoothTime < 0){
                                 obj -> SmoothDelta = -1;
                                 obj -> SmoothTime = -obj -> SmoothTime;
                             }
                             else {
                                 obj -> SmoothDelta = 1;
                             }
                         }
                         obj -> SmoothCount = obj -> SmoothTime >> 1;
                         break;
                     case EV_OBJECT_JUMP:
                         curScr -> curObj -> flags ^= OBJ_SELECTED;
                         curScr -> curObj = (iScreenObject*)cm -> obj;
                         curScr -> curObj -> flags |= OBJ_SELECTED;
                         break;
                     case EV_SCREEN_JUMP:
                         curScr -> free_data();
                         curScr = (iScreen*)cm -> obj;
                         curScr -> prepare();
                         curScr -> load_data();
                         break;
                     case EV_EXT_SCREEN_JUMP:
                         curScr -> free_data();
                         curScr = iScrDisp -> get_ext_screen(cm -> pvalue);
                         if(!curScr)
                             ErrH.Abort("Can't find screen...",XERR_USER,0,cm -> pvalue);
                         curScr -> prepare();
                         curScr -> load_data();
                         obj = (iScreenObject*)curScr -> TerrainList -> last;
                         while(obj){
                             obj -> flags |= OBJ_HIDE;
                             obj -> curHeightScale = 0;
                             obj = (iScreenObject*)obj -> prev;
                         }
                         obj = (iScreenObject*)curScr -> objList -> last;
                         while(obj){
                             obj -> flags |= OBJ_HIDE;
                             obj -> curHeightScale = 0;
                             obj = (iScreenObject*)obj -> prev;
                         }
                         break;
                     case EV_RISE_SCREEN:
                         flags |= SD_GETFON;
                         obj = (iScreenObject*)curScr -> TerrainList -> last;
                         while(obj){
                             if(obj -> flags & OBJ_SELECTED || !(obj -> flags & OBJ_SELECTABLE))
                                 sc = ((iTerrainElement*)obj -> ElementList -> last) -> scale_strength;
                             else
                                 sc = I_UNSELECT_SCALE;
                             obj -> flags |= OBJ_HIDE;
                             obj -> curHeightScale = 0;
                             obj -> HeightScaleDelta = (sc - obj -> curHeightScale) / cm -> time;
                             sc = ((iTerrainElement*)obj -> ElementList -> last) -> def_null_level;
                             ((iTerrainElement*)obj -> ElementList -> last) -> level_delta = (sc - ((iTerrainElement*)obj -> ElementList -> last) -> null_level) / cm -> time;
                             obj = (iScreenObject*)obj -> prev;
                         }
                         obj = (iScreenObject*)curScr -> objList -> last;
                         while(obj){
                             if(obj -> flags & OBJ_SELECTED || !(obj -> flags & OBJ_SELECTABLE))
                                 sc = 256;
                             else
                                 sc = I_UNSELECT_SCALE;
                             obj -> flags |= OBJ_HIDE;
                             obj -> curHeightScale = 0;
                             obj -> HeightScaleDelta = (sc - obj -> curHeightScale) / cm -> time;
                             obj = (iScreenObject*)obj -> prev;
                         }
                         break;
                     case EV_HIDE_SCREEN:
                         flags |= SD_GETFON;
                         obj = (iScreenObject*)curScr -> objList -> last;
                         while(obj){
                             obj -> HeightScaleDelta = -obj -> curHeightScale / cm -> time;
                             obj -> flags |= OBJ_HIDE;
                             obj = (iScreenObject*)obj -> prev;
                         }
                         obj = (iScreenObject*)curScr -> TerrainList -> last;
                         while(obj){
                             obj -> HeightScaleDelta = -obj -> curHeightScale / cm -> time;
                             obj -> flags |= OBJ_HIDE;
                             ((iTerrainElement*)obj -> ElementList -> last) -> level_delta = -((iTerrainElement*)obj -> ElementList -> last) -> null_level / cm -> time;
                             obj = (iScreenObject*)obj -> prev;
                         }
                         break;
                     case EV_CHANGE_SCROLLER:
                         scl = (iScrollerElement*)cm -> obj;
                         if(scl -> check_xy(iMouseX + iScreenOffs,iMouseY)){
                             scl -> change_val(iMouseX + iScreenOffs,iMouseY);
                             scl -> scale_delta = (scl -> Value > scl -> prevValue) ? 512 / cm -> time : -512 / cm -> time;
                         }
                         else {
                             scl -> prevValue = scl -> Value;
                             scl -> scale_delta = 0;
                         }
                         break;
                     case EV_CHANGE_TRIGGER:
                         trg = (iTriggerObject*)cm -> obj;
                         trg -> change_state(cm -> time);
                         break;
                     case EV_PREV_TRIGGER:
                         trg = (iTriggerObject*)cm -> obj;
                         trg -> change_state(cm -> time,-2);
                         break;
                     case EV_SET_TRIGGER:
                         trg = (iTriggerObject*)cm -> obj;
                         if(trg -> state != cm -> value)
                             trg -> change_state(cm -> time,cm -> value);
                         else
                             trg -> prev_state = trg -> state;
                         break;
                     case EV_CHANGE_AVI:
                         avi_el = (iAVIElement*)cm -> obj;
                         avi_el -> change_avi(cm -> pvalue);
                         avi_el -> init_size();
                         avi_el -> init_align();
                         break;
                     case EV_NEXT_AVI:
                         avi_el = (iAVIElement*)cm -> obj;
                         avi_el -> next_avi();
                         avi_el -> init_size();
                         avi_el -> init_align();
                         break;
                     case EV_PREV_AVI:
                         avi_el = (iAVIElement*)cm -> obj;
                         avi_el -> prev_avi();
                         avi_el -> init_size();
                         avi_el -> init_align();
                         break;
                     case EV_LIST_CHANGE_AVI:
                         avi_el = (iAVIElement*)cm -> obj;
                         list = (iList*)cm -> pvalue;
                         list_el = list -> first;
                         list -> index ++;
                         if(list -> index >= list -> Size)
                             list -> index = 0;
                         for(i = 0; i < list -> index; i ++)
                             list_el = list_el -> next;
                         avi_el -> change_avi((char *)list_el->ID_ptr.c_str());
                         avi_el -> init_size();
                         avi_el -> init_align();
                         break;
                     case EV_INPUT_STRING:
                         if(!(flags & SD_INPUT_STRING) && !(flags & SD_FINISH_INPUT)){
                             el = (iScreenElement*)cm -> obj;
                             init_input_string(el);
                             cur_max_input = cm -> value;
                         }
                         break;
                     case EV_MOVE_SCREEN:
                         aci_move_screen(cm -> value,cm -> time);
                         p -> cur_time = cm -> time + cm -> start_time - 1;
                         break;
                     case EV_MOVE2SCREEN:
                         move2screen((iScreen*)cm -> obj,cm -> time);
                         p -> cur_time = cm -> time + cm -> start_time - 1;
                         break;
                     case EV_SEND2ACTINT:
                         aci_SendEvent(cm -> value + ACI_MAX_EVENT);
                         break;
                     case EV_SEND2ML_DISP:
                         aciML_SendEvent(cm -> value);
                         break;
                     case EV_ML_EVENT:
                         aciML_SendEvent(cm -> value,cm -> data0,cm -> data1);
                         break;
                     case EV_SEND_DATA2ACTINT:
                         aci_SendEvent((cm -> value & 0xFFFF) + ACI_MAX_EVENT,(cm -> value >> 16) & 0xFFFF);
                         break;
                     case EV_SET_LINE_ID:
                         iEvLineID = cm -> value;
                         break;
                     case EV_END_EVENT:
                         p -> cur_time = p -> time;
                         break;
                     case EV_EXIT_EVENT:
                         p -> cur_time = p -> time;
                         aciChangeLineID();
                         break;
                     case EV_CHECK_CREDITS:
                         if(!aciCheckCredits())
                             p -> cur_time = p -> time;
                         break;
                 }
             }
             if(cm -> start_time <= p -> cur_time && cm -> time + cm -> start_time > p -> cur_time){
                 switch(cm -> EvType){
                     case EV_RISE_OBJECT:
                     case EV_LOW_OBJECT:
                     case EV_SCALE_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         obj -> ScaleQuant();
                         if(cm -> time + cm -> start_time == p -> cur_time + 1)
                              obj -> flags &= ~OBJ_HIDE;
                         set_obj_redraw(obj);
                         break;
                     case EV_SMOOTH_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         obj -> SmoothQuant();
                         set_obj_redraw(obj);
                         break;
                     case EV_HIDE_OBJECT:
                         obj = (iScreenObject*)cm -> obj;
                         if(!obj) obj = curScr -> curObj;
                         if(cm -> time + cm -> start_time == p -> cur_time + 1)
                             obj -> curHeightScale = 0;
                         else
                             obj -> ScaleQuant();
                         set_obj_redraw(obj);
                         break;
                     case EV_HIDE_SCREEN:
                         if(cm -> time + cm -> start_time == p -> cur_time + 1)
                             flags |= SD_END_GETFON;
                         obj = (iScreenObject*)curScr -> objList -> last;
                         while(obj){
                             if(cm -> time + cm -> start_time == p -> cur_time + 1)
                                 obj -> curHeightScale = 0;
                             else
                                 obj -> ScaleQuant();
                             obj = (iScreenObject*)obj -> prev;
                         }
                         obj = (iScreenObject*)curScr -> TerrainList -> last;
                         while(obj){
                             if(cm -> time + cm -> start_time == p -> cur_time + 1){
                                 ((iTerrainElement*)obj -> ElementList -> last) -> null_level = 0;
                                 obj -> curHeightScale = 0;
                             }
                             else
                                 obj -> ScaleQuant();
                             obj = (iScreenObject*)obj -> prev;
                         }
                         set_scr_redraw(curScr);
                         break;
                     case EV_RISE_SCREEN:
                         if(cm -> time + cm -> start_time == p -> cur_time + 1)
                             flags |= SD_END_GETFON;
                         obj = (iScreenObject*)curScr -> objList -> last;
                         while(obj){
                             obj -> ScaleQuant();
                             if(cm -> time + cm -> start_time == p -> cur_time + 1){
                                 obj -> flags &= ~OBJ_HIDE;
                             }
                             obj = (iScreenObject*)obj -> prev;
                         }
                         obj = (iScreenObject*)curScr -> TerrainList -> last;
                         while(obj){
                             obj -> ScaleQuant();
                             if(cm -> time + cm -> start_time == p -> cur_time + 1){
                                 ((iTerrainElement*)obj -> ElementList -> last) -> null_level = ((iTerrainElement*)obj -> ElementList -> last) -> def_null_level;
                                 obj -> flags &= ~OBJ_HIDE;
                             }
                             obj = (iScreenObject*)obj -> prev;
                         }
                         set_scr_redraw(curScr);
                         break;
                     case EV_EXIT:
                         if(!actIntLog || (aScrDisp -> curMatrix || !cm -> value)){
                             iScrDisp -> flags |= SD_EXIT;
                             iScrDisp -> ret_val = cm -> value;
                         }
                         break;
                     case EV_CHANGE_SCROLLER:
                         scl = (iScrollerElement*)cm -> obj;
                         obj = (iScreenObject*)scl -> owner;
                         if(cm -> time + cm -> start_time == p -> cur_time + 1){
                             scl -> prevValue = scl -> Value;
                         }
                         else
                             scl -> change_quant();
                         set_obj_redraw(obj);
                         break;
                     case EV_CHANGE_TRIGGER:
                     case EV_SET_TRIGGER:
                     case EV_PREV_TRIGGER:
                         trg = (iTriggerObject*)cm -> obj;
                         if(trg -> state != trg -> prev_state){
                             if(cm -> time + cm -> start_time == p -> cur_time + 1){
                                 el = (iScreenElement*)trg -> StateElem[trg -> prev_state];
                                 el -> scale = 0;
                                 el -> flags |= EL_NO_REDRAW;
                                 if(el -> type == I_AVI_ELEM) trg -> flags |= OBJ_AVI_STOPPED;
                                 el = (iScreenElement*)trg -> StateElem[trg -> state];
                                 el -> scale = 256;
                                 el -> flags &= ~EL_HIDE;
                                 if(el -> type == I_AVI_ELEM) trg -> flags &= ~OBJ_AVI_STOPPED;
                             }
                             else {
                                 el = (iScreenElement*)trg -> StateElem[trg -> prev_state];
                                 el -> scale_quant();
                                 el = (iScreenElement*)trg -> StateElem[trg -> state];
                                 el -> scale_quant();
                                 if(el -> type == I_AVI_ELEM) trg -> flags &= ~OBJ_AVI_STOPPED;
                             }
                             set_obj_redraw((iScreenObject*)trg);
                         }
                         break;
                     case EV_INPUT_STRING:
                         if(cm -> time + cm -> start_time == p -> cur_time + 1)
                             flags &= ~(SD_INPUT_STRING | SD_FINISH_INPUT);
                         break;
                 }
             }
         }
         cm = (iScreenEventCommand*)cm -> prev;
     }
     p -> cur_time ++;
     if(p -> cur_time >= p -> time){
         p -> flags &= ~EV_ACTIVE;
         ActiveEv = NULL;
     }
 }
References XErrorHandler::Abort(), AVI_STOPPED, copy_text_next(), copy_text_prev(), CurEvComm, curScr, curText, ErrH, EV_CHANGE_AVI, EV_CHANGE_SCROLLER, EV_CHANGE_TRIGGER, EV_EXT_EVENT, EV_EXT_SCREEN_JUMP, EV_HIDE_OBJECT, EV_HIDE_SCREEN, EV_LIST_CHANGE_AVI, EV_LOCK_OBJ, EV_LOW_OBJECT, EV_MULTI_LINE, EV_NEXT_AVI, EV_NEXT_TEXT, EV_OBJECT_JUMP, EV_PLAY_AVI, EV_PREV_AVI, EV_PREV_TEXT, EV_PREV_TRIGGER, EV_RESET_TEXTS, EV_RISE_OBJECT, EV_RISE_SCREEN, EV_SCALE_OBJECT, EV_SCREEN_JUMP, EV_SET_TRIGGER, EV_SMOOTH_OBJECT, EV_START_DEMO, EV_STOP_AVI, EV_UNLOCK_OBJ, EventFlag, iList::first, flags, free_data(), get_ext_screen(), i_preExtQuant(), I_UNSELECT_SCALE, iEvLineID, iHandleExtEvent(), iMouseX, iMouseY, iList::index, iScrDisp, iScreenOffs, iTEXT_NORMAL, iList::last, load_data(), NULL, OBJ_AVI_STOPPED, OBJ_HIDE, OBJ_LOCKED, OBJ_SELECTABLE, OBJ_SELECTED, prepare(), prev, SD_GETFON, iList::Size, and XERR_USER.
Referenced by EventQuant().
redraw()
void iScreenDispatcher::redraw (int mode = 0)
 {
     iScreenObject* p;
     if(!actIntLog){
         p = (iScreenObject*)ObjHeap -> last;
         while(p){
             p -> redraw(mode);
             p = (iScreenObject*)p -> prev;
         }
     }
     curScr -> getfon();
     curScr -> redraw(mode);
 }
References actIntLog, curScr, iList::last, ObjHeap, and prev.
Referenced by redraw_quant().
redraw_quant()
void iScreenDispatcher::redraw_quant (void)
 {
     iListElementPtr* tmp;
     iScreenObject* obj;
     tmp = (iListElementPtr*)drwObjHeap -> last;
     while(tmp){
         obj = (iScreenObject*)tmp -> ptr;
         obj -> putfon();
         tmp = (iListElementPtr*)tmp -> prev;
     }
     tmp = (iListElementPtr*)drwObjHeap -> last;
     if(flags & SD_GETFON){
         while(tmp){
             obj = (iScreenObject*)tmp -> ptr;
             if(obj -> flags & OBJ_TERRAIN)
                 obj -> redraw();
             obj -> flags &= ~OBJ_REDRAW;
             tmp = (iListElementPtr*)tmp -> prev;
         }
         tmp = (iListElementPtr*)drwObjHeap -> last;
         while(tmp){
             obj = (iScreenObject*)tmp -> ptr;
             if(!(obj -> flags & OBJ_TERRAIN))
                 obj -> getfon();
             tmp = (iListElementPtr*)tmp -> prev;
         }
         tmp = (iListElementPtr*)drwObjHeap -> last;
         while(tmp){
             obj = (iScreenObject*)tmp -> ptr;
             if(!(obj -> flags & OBJ_TERRAIN))
                 obj -> redraw();
             obj -> flags &= ~OBJ_REDRAW;
             tmp = (iListElementPtr*)tmp -> prev;
         }
     }
     else {
         while(tmp){
             obj = (iScreenObject*)tmp -> ptr;
             obj -> redraw();
             obj -> flags &= ~OBJ_REDRAW;
             tmp = (iListElementPtr*)tmp -> prev;
         }
     }
     if(flags & SD_END_GETFON){
         flags &= ~(SD_GETFON | SD_END_GETFON);
     }
 }
References drwObjHeap, flags, iList::last, OBJ_REDRAW, OBJ_TERRAIN, prev, redraw(), SD_END_GETFON, and SD_GETFON.
Referenced by aci_move_screen(), EventQuant(), and move2screen().
remove_ext_screen()
void iScreenDispatcher::remove_ext_screen (iScreen * p)
 {
     ExtScreens -> dconnect((iListElement*)p);
 }
References iList::dconnect(), and ExtScreens.
save_data()
void iScreenDispatcher::save_data (XStream * fh)
 {
     std::cout<<"iScreenDispatcher::save_data"<<std::endl;
     int i,num_opt = iMAX_OPTION_ID;
     *fh < num_opt;
     for(i = 0; i < iMAX_OPTION_ID; i ++){
         if(iScrOpt[i])
             iScrOpt[i] -> save(fh);
     }
 }
References iMAX_OPTION_ID, and iScrOpt.
set_obj_redraw()
void iScreenDispatcher::set_obj_redraw (iScreenObject * p)
 {
     iListElementPtr* tmp;
     if(!(p -> flags & OBJ_REDRAW)){
         p -> flags |= OBJ_REDRAW;
         _iALLOC_(iListElementPtr,tmp);
         tmp -> ptr = (iListElement*)p;
         drwObjHeap -> connect((iListElement*)tmp);
     }
 }
References _iALLOC_, iList::connect(), drwObjHeap, flags, and OBJ_REDRAW.
Referenced by EventQuant(), and set_scr_redraw().
set_scr_redraw()
void iScreenDispatcher::set_scr_redraw (iScreen * p)
 {
     iScreenObject* obj;
     obj = (iScreenObject*)p -> objList -> last;
     while(obj){
         set_obj_redraw(obj);
         obj = (iScreenObject*)obj -> prev;
     }
     obj = (iScreenObject*)p -> TerrainList -> last;
     while(obj){
         set_obj_redraw(obj);
         obj = (iScreenObject*)obj -> prev;
     }
 }
References iList::last, prev, and set_obj_redraw().
Referenced by hide_screen(), and show_screen().
show_screen()
void iScreenDispatcher::show_screen (iScreen * p)
 {
     p -> prepare();
     set_scr_redraw(p);
 }
References prepare(), and set_scr_redraw().
Referenced by move2screen().
unlock_events()
void iScreenDispatcher::unlock_events (void)
 {
     flags &= ~SD_LOCK_EVENTS;
 }
References flags, and SD_LOCK_EVENTS.
Member Data Documentation
ActiveEl
iScreenElement* iScreenDispatcher::ActiveEl
Referenced by init_input_string(), and input_string_quant().
ActiveEv
iScreenEvent* iScreenDispatcher::ActiveEv
Referenced by CheckScanCode(), copy_text_next(), copy_text_prev(), end_event(), EventQuant(), HandleEvent(), iScreenDispatcher(), and lock_events().
cur_max_input
int iScreenDispatcher::cur_max_input
Referenced by input_string_quant().
curPal
unsigned char* iScreenDispatcher::curPal
Referenced by iScreenDispatcher(), and pal_quant().
curScr
iScreen* iScreenDispatcher::curScr
Referenced by aci_move_screen(), alloc_mem(), CheckScanCode(), EventQuant(), free_mem(), HandleEvent(), actIntDispatcher::inv_mouse_imove_quant(), key_trap(), move2screen(), prepare(), ProcessEvent(), and redraw().
curText
iTextData* iScreenDispatcher::curText
Referenced by copy_text_next(), copy_text_prev(), init_texts(), next_text(), prev_text(), and ProcessEvent().
drwObjHeap
iList* iScreenDispatcher::drwObjHeap
Referenced by EventQuant(), flush_quant(), init_input_string(), input_string_quant(), iScreenDispatcher(), move2screen(), redraw_quant(), and set_obj_redraw().
ExtScreens
iList* iScreenDispatcher::ExtScreens
Referenced by add_ext_screen(), get_ext_screen(), iScreenDispatcher(), and remove_ext_screen().
flags
int iScreenDispatcher::flags
Referenced by aci_move_screen(), CheckScanCode(), copy_text_next(), copy_text_prev(), end_event(), EventQuant(), flush_quant(), HandleEvent(), hide_screen(), init_input_string(), input_string_quant(), iScreenDispatcher(), lock_events(), move2screen(), pal_quant(), prepare(), ProcessEvent(), redraw_quant(), set_obj_redraw(), and unlock_events().
ObjHeap
iList* iScreenDispatcher::ObjHeap
Referenced by alloc_mem(), CheckScanCode(), free_mem(), iScreenDispatcher(), prepare(), and redraw().
ret_val
int iScreenDispatcher::ret_val
Referenced by alloc_mem().
ScreenIDs
iList* iScreenDispatcher::ScreenIDs
Referenced by check_id(), get_object(), and iScreenDispatcher().
t_scrID
char* iScreenDispatcher::t_scrID
texts
iList* iScreenDispatcher::texts
Referenced by finit_texts(), get_text(), init_texts(), and iScreenDispatcher().
trgPal
unsigned char* iScreenDispatcher::trgPal
Referenced by iScreenDispatcher(), and pal_quant().
The documentation for this struct was generated from the following files:
src/iscreen/iscreen.h
src/iscreen/iscreen.cpp