Vangers: ScriptFile Struct Reference
ScriptFile Struct Reference
#include <iscript.h>
Public Member Functions
int SeekPos (char *s)
int Seek (char *s)
int SeekCharPos (char s)
int SeekChar (char s)
int SeekComm (int mode)
int SeekCommPos (int mode)
int get_cur_str (void)
char * get_ptr (void)
char * get_conv_ptr (void)
void next_ptr (void)
void next_line (void)
void next_src_line (void)
void read_src_line (void)
void load (const char *fname)
void next (void)
void prepare (void)
void preprocess (void)
void strip_comments (void)
int check_math (void)
int parse_math (void)
void reset (void)
void set_bscript_name (char *fname)
void open_bscript (const char *fname)
void close_bscript (void)
void write_idata (int val)
void write_pdata (char *ptr)
void write_end (void)
int read_option (int mode=1)
int read_key (void)
int read_idata (void)
void read_pdata (char **ptr, int mode=0)
int get_idata (void)
void get_pdata (char **ptr, int mode=0)
char * get_pdata_ptr (void)
void prepare_pdata (void)
void prepare_idata (void)
void add_line (ScriptLine *p)
void remove_line (ScriptLine *p)
void add_def (ScriptLine *p)
void add_buf (ScriptFileBuffer *p)
void free_buffers (void)
int process_includes (void)
ScriptFile (void)
~ScriptFile (void)
Public Attributes
int Size
int EOF_Flag
int CurOffs
char * buffer
char * cur_ptr
char * prevStrBuf
int CompressLog
XStream * bin_fh
char * binConvBuf
int binConvBufSize
int binConvData
int NumStr
ScriptLine * firstLine
ScriptLine * lastLine
ScriptLine * curLine
int NumBufs
ScriptFileBuffer * fBuf
ScriptFileBuffer * lBuf
char * bScriptName
ScriptBlock * curBlock
int NumDef
ScriptDefine * fDef
ScriptDefine * lDef
Detailed Description
Constructor & Destructor Documentation
ScriptFile()
ScriptFile::ScriptFile (void)
 {
     firstLine = lastLine = NULL;
     curBlock = NULL;
     fDef = lDef = NULL;
     CompressLog = 0;
     NumBufs = 0;
     fBuf = lBuf = NULL;
     buffer = NULL;
     NumStr = NumDef = 0;
     EOF_Flag = 0;
 #ifdef _BINARY_SCRIPT_
     binConvPtr = NULL;
 #endif
     binConvBuf = new char[SCRIPT_CONV_BUF_SIZE];
     binConvBufSize = 0;
 #ifndef _BINARY_SCRIPT_
     prevStrBuf = new char[2048];
 #endif
 #ifdef _SAVE_BINARY_SCRIPT_
     bScriptName = NULL;
 #endif
 }
References binConvBuf, binConvBufSize, bScriptName, buffer, CompressLog, curBlock, EOF_Flag, fBuf, fDef, firstLine, lastLine, lBuf, lDef, NULL, NumBufs, NumDef, NumStr, prevStrBuf, and SCRIPT_CONV_BUF_SIZE.
~ScriptFile()
ScriptFile::~ScriptFile (void)
 {
     ScriptLine* l,*line = lastLine;
     ScriptDefine* d,*def = lDef;
 #ifndef _BINARY_SCRIPT_
     delete[] prevStrBuf;
 #endif
     while(def){
         d = def -> prev;
         delete def;
         def = d;
     }
     while(line){
         l = line -> prev;
         delete line;
         line = l;
     }
     delete[] binConvBuf;
 #ifdef _BINARY_SCRIPT_
     free_bscript();
 #endif
     if(buffer) {
         delete[] buffer;
     }
 }
References binConvBuf, buffer, lastLine, lDef, prev, and prevStrBuf.
Member Function Documentation
add_buf()
void ScriptFile::add_buf (ScriptFileBuffer * p)
 {
     if(lBuf){
         lBuf -> next = p;
         p -> prev = lBuf;
         p -> next = fBuf;
         lBuf  = p;
     }
     else{
         lBuf = p;
         fBuf = p;
         p -> next = p;
         p -> prev = 0;
     }
     NumBufs ++;
 }
References fBuf, lBuf, next(), NumBufs, and prev.
add_def()
void ScriptFile::add_def (ScriptLine * p)
 {
     ScriptDefine* d = new ScriptDefine;
     d -> add(p);
     d -> EndLine = NumStr;
     if(lDef){
         lDef -> next = d;
         d -> prev = lDef;
         d -> next = fDef;
         lDef  = d;
     }
     else{
         lDef = d;
         fDef = d;
         d -> next = d;
         d -> prev = NULL;
     }
     NumDef ++;
 }
References fDef, lDef, next(), NULL, NumDef, NumStr, and prev.
add_line()
void ScriptFile::add_line (ScriptLine * p)
 {
     if(lastLine){
         lastLine -> next = p;
         p -> prev = lastLine;
         p -> next = firstLine;
         lastLine  = p;
     }
     else{
         lastLine = p;
         firstLine = p;
         p -> next = p;
         p -> prev = 0;
     }
     NumStr ++;
 }
References firstLine, lastLine, next(), NumStr, and prev.
Referenced by preprocess().
check_math()
int ScriptFile::check_math (void)
 {
     if(EOF_Flag) return 0;
 #ifndef _BINARY_SCRIPT_
     int i;
     if(!curBlock || !curBlock -> data) return 0;
     for(i = 0; i < MT_MAX_CODE; i ++){
         if(*curBlock -> data == *scMathOpNames[i] && !strcmp(curBlock -> data,scMathOpNames[i])) return i + 1;
     }
 #endif
     return 0;
 }
References curBlock, EOF_Flag, and MT_MAX_CODE.
Referenced by parse_math().
close_bscript()
void ScriptFile::close_bscript (void)
 {
 #ifndef _BINARY_SCRIPT_
     write_end();
     bin_fh -> close();
 #ifdef _SAVE_PACKED_SCRIPT_
     int sz,out_sz;
     char* p,*p1;
     bin_fh -> open(bScriptName,XS_IN);
     sz = bin_fh -> size();
     p = new char[sz];
     p1 = new char[sz];
     bin_fh -> read(p,sz);
     bin_fh -> close();
     out_sz = ZIP_compress(p1,sz,p,sz);
     if(!out_sz) ErrH.Abort("Bad compressed script size...");
     CompressLog = 1;
     bin_fh -> open(bScriptName,XS_OUT);
     *bin_fh < BSCR_SIGN < '\0' < CompressLog;
     bin_fh -> write(p1,out_sz);
     bin_fh -> close();
     delete p;
     delete p1;
 #endif
     delete bin_fh;
 #endif
 }
References XErrorHandler::Abort(), bin_fh, bScriptName, CompressLog, ErrH, write_end(), XS_IN, XS_OUT, and ZIP_compress().
free_buffers()
void ScriptFile::free_buffers (void)
 {
     ScriptFileBuffer* p,*p1;
     p = lBuf;
     while(p){
         p1 = p -> prev;
         delete p;
         p = p1;
     }
     fBuf = lBuf = NULL;
     NumBufs = 0;
 }
References fBuf, lBuf, NULL, NumBufs, and prev.
get_conv_ptr()
char * ScriptFile::get_conv_ptr (void)
 {
     return binConvBuf;
 }
References binConvBuf.
get_cur_str()
int ScriptFile::get_cur_str (void)
 {
     return curLine -> ID;
 }
References curLine.
get_idata()
int ScriptFile::get_idata (void)
 {
     return binConvData;
 }
References binConvData.
get_pdata()
void ScriptFile::get_pdata (char ** ptr, int mode = 0)
 {
     int sz = binConvBufSize;
     if(mode)
         ptr[0] = new char[sz + 1];
     strcpy(ptr[0],binConvBuf);
 }
References binConvBuf, and binConvBufSize.
get_pdata_ptr()
char * ScriptFile::get_pdata_ptr (void)
 {
     return binConvBuf;
 }
References binConvBuf.
get_ptr()
char * ScriptFile::get_ptr (void)
 {
 #ifndef _BINARY_SCRIPT_
     if(curBlock){
         strcpy(prevStrBuf,curBlock -> data);
         return curBlock -> data;
     }
     return NULL;
 #else
     return binConvBuf;
 #endif
 }
References binConvBuf, curBlock, NULL, and prevStrBuf.
Referenced by prepare_pdata(), read_key(), read_option(), and read_pdata().
load()
void ScriptFile::load (const char * fname)
 {
     XStream fh;
 #ifdef _BINARY_SCRIPT_
     load_bscript(fname);
 #else
     int inc_count = 0;
     fh.open(fname,XS_IN);
     Size = fh.size();
     buffer = new char[Size];
     fh.read(buffer,Size);
     fh.close();
     while(process_includes()){
         inc_count ++;
         if(inc_count > iSCRIPT_INCLUDE_MAX) ErrH.Abort("process_includes() failed...");
     }
 #ifdef _SAVE_BINARY_SCRIPT_
     open_bscript(fname);
 #endif
 #endif
     cur_ptr = buffer;
     CurOffs = 0;
 }
References XErrorHandler::Abort(), buffer, XStream::close(), cur_ptr, CurOffs, ErrH, iSCRIPT_INCLUDE_MAX, XStream::open(), open_bscript(), process_includes(), XStream::read(), XStream::size(), Size, and XS_IN.
next()
void ScriptFile::next (void)
 {
     int sz;
     if((sz = strlen(cur_ptr)) != 0){
         cur_ptr += sz;
         CurOffs += sz;
     }
     while(!(*cur_ptr)){
         if(++CurOffs > Size - 1) return;
         cur_ptr++;
     }
 }
References cur_ptr, CurOffs, and Size.
Referenced by add_buf(), add_def(), add_line(), next_line(), next_ptr(), preprocess(), and remove_line().
next_line()
void ScriptFile::next_line (void)
 {
     if(curLine){
         curLine = curLine -> next;
         curBlock = curLine -> first;
         if(curLine == firstLine)
             EOF_Flag = 1;
     }
 }
References curBlock, curLine, EOF_Flag, firstLine, and next().
next_ptr()
void ScriptFile::next_ptr (void)
 {
     if(curBlock)
         curBlock = curBlock -> next;
     if(curBlock == curLine -> first){
         curLine = curLine -> next;
         curBlock = curLine -> first;
         if(curLine == firstLine)
             EOF_Flag = 1;
     }
 }
References curBlock, curLine, EOF_Flag, firstLine, and next().
Referenced by parse_math(), prepare_pdata(), read_key(), read_option(), and read_pdata().
next_src_line()
void ScriptFile::next_src_line (void)
 {
     while(*cur_ptr == '\n'){
         CurOffs ++;
         cur_ptr ++;
     }
     while(*cur_ptr != '\n'){
         if(++CurOffs > Size - 1) return;
         cur_ptr++;
     }
     if(*cur_ptr == '\n'){
         CurOffs ++;
         cur_ptr ++;
     }
 }
References cur_ptr, CurOffs, and Size.
open_bscript()
void ScriptFile::open_bscript (const char * fname)
 {
     if(!bScriptName){
         bScriptName = new char[256];
         strcpy(bScriptName,fname);
         memcpy(bScriptName + strlen(bScriptName) - 3,"scb",3);
     }
     bin_fh = new XStream;
     bin_fh -> open(bScriptName,XS_OUT);
 #ifndef _SAVE_PACKED_SCRIPT_
     *bin_fh < BSCR_SIGN < '\0' < CompressLog;
 #endif
 }
References bin_fh, bScriptName, and XS_OUT.
Referenced by load().
parse_math()
int ScriptFile::parse_math (void)
 {
 #ifndef _BINARY_SCRIPT_
     int val = 0,op_code = 0;
     scMathExpression* m;
     ScriptBlock* p = curBlock;
     val = check_math();
     next_ptr();
     op_code = check_math();
     if(val || op_code){
         m = new scMathExpression;
         m -> add2list(p);
     }
     else {
         return atoi(p -> data);
     }
     val = 1;
     while(val){
         m -> add2list(curBlock);
         next_ptr();
         if(*curBlock -> data == '}' ){
             next_ptr();
             val = 0;
         }
     }
     m -> prepare_list();
     val = m -> eval();
     delete m;
     return val;
 #else
     return 0;
 #endif
 }
References check_math(), curBlock, and next_ptr().
Referenced by prepare_idata(), and read_idata().
prepare()
void ScriptFile::prepare (void)
 {
 #ifndef _BINARY_SCRIPT_
     int i,j,offs,flag;
     ScriptDefine* def;
     ScriptBlock* p,*p1;
     ScriptLine* line,*l;
     strip_comments();
     for(i = 0; i < Size; i ++){
         if(*cur_ptr == '\"'){
             cur_ptr ++;
             i ++;
             if((offs = SeekCharPos('\"')) != -1){
                 cur_ptr += offs;
                 i += offs;
             }
             else
                 handle_error("Bad \"\" statement");
         }
         for(j = 0; j < MAX_STRIP_CHAR; j ++)
             if(*cur_ptr == StripChars[j]) *cur_ptr = 0;
         cur_ptr ++;
     }
     reset();
     preprocess();
     reset();
     while(!script -> EOF_Flag){
         if(curBlock && curBlock -> data && *curBlock -> data == '#' && !strcmp(curBlock -> data,"#define")){
             if(curLine -> Size < 2)
                 handle_error("Bad define statement");
             add_def(curLine);
             lDef -> StartLine = curLine -> ID;
             def = lDef -> prev;
             while(def){
                 if(!strcmp(def -> line -> first -> next -> data,lDef -> line -> first -> next -> data)){
                     def -> EndLine = lDef -> StartLine;
                     def = NULL;
                 }
                 else
                     def = def -> prev;
             }
             while(*lDef -> line -> last -> data == '\\'){
                 lDef -> line -> last -> clear();
                 if(!script -> EOF_Flag){
                     script -> next_line();
                     lDef -> add(curLine);
                 }
             }
         }
         script -> next_line();
     }
     reset();
     while(!script -> EOF_Flag){
         if(curBlock && curBlock -> data && *curBlock -> data == '$'){
             def = lDef;
             flag = 0;
             while(def){
                 if(curLine -> ID >= def -> StartLine && curLine -> ID < def -> EndLine && !strcmp(curBlock -> data + 1,def -> line -> first -> next -> data)){
                     flag = 1;
                     curBlock -> clear();
                     if(def -> line -> Size > 2)
                         curLine -> merge(curBlock,def -> line -> first -> next -> next,def -> line -> last);
                     def = NULL;
                 }
                 else
                     def = def -> prev;
             }
             if(!flag) handle_error("Bad define",curBlock -> data + 1);
         }
         next_ptr();
     }
     reset();
     for(i = 0; i < NumStr; i ++){
         p = curLine -> last;
         while(p){
             p1 = p -> prev;
             if(!(*p -> data)){
                 curLine -> dconnect(p);
             }
             p = p1;
         }
         curLine = curLine -> next;
     }
     reset();
     for(i = 0; i < NumStr; i ++){
         p = curLine -> last;
         while(p){
             p1 = p -> prev;
             if(*p -> data == '\"'){
                 *p -> data = 0;
                 p -> data ++;
                 if(*(p -> data + strlen(p -> data) - 1) == '\"')
                     *(p -> data + strlen(p -> data) - 1) = 0;
             }
             p = p1;
         }
         curLine = curLine -> next;
     }
     reset();
     for(i = 0; i < NumStr; i ++){
         p = curLine -> last;
         while(p){
             p1 = p -> prev;
             if(*p -> data == '\"'){
                 *p -> data = 0;
                 p -> data ++;
                 if(*(p -> data + strlen(p -> data) - 1) == '\"')
                     *(p -> data + strlen(p -> data) - 1) = 0;
             }
             p = p1;
         }
         curLine = curLine -> next;
     }
     reset();
     for(i = 0; i < Size; i ++){
         if(*cur_ptr == '\"')
             *cur_ptr = 0;
         cur_ptr ++;
     }
     reset();
     line = curLine;
     for(i = 0; i < NumStr; i ++){
         l = line -> next;
         if(!line -> Size){
             remove_line(line);
             delete line;
         }
         line = l;
     }
     reset();
 #ifdef _iSCRIPT_DEBUG_
     write_log();
 #endif
 #endif
 }
References cur_ptr, handle_error(), MAX_STRIP_CHAR, SeekCharPos(), Size, and strip_comments().
prepare_idata()
void ScriptFile::prepare_idata (void)
 {
 #ifdef _BINARY_SCRIPT_
     *binConv > binConvData;
     if(binConv -> end())
         EOF_Flag = 1;
 #else
     binConvData = parse_math();
 #ifdef _SAVE_BINARY_SCRIPT_
     write_idata(binConvData);
 #endif
 #endif
 }
References binConvData, EOF_Flag, parse_math(), and write_idata().
prepare_pdata()
void ScriptFile::prepare_pdata (void)
 {
 #ifdef _BINARY_SCRIPT_
     *binConv > binConvBufSize;
     *binConv > binConvBuf;
     if(binConv -> end())
         EOF_Flag = 1;
 #else
     binConvBufSize = strlen(get_ptr());
     if(binConvBufSize >= SCRIPT_CONV_BUF_SIZE)
         ErrH.Abort("Script buffer overflow...");
     strcpy(binConvBuf,get_ptr());
     next_ptr();
 #ifdef _SAVE_BINARY_SCRIPT_
     write_pdata(binConvBuf);
 #endif
 #endif
 }
References XErrorHandler::Abort(), binConvBuf, binConvBufSize, EOF_Flag, ErrH, get_ptr(), next_ptr(), SCRIPT_CONV_BUF_SIZE, and write_pdata().
preprocess()
void ScriptFile::preprocess (void)
 {
     int cur_line_id = 0;
     ScriptLine* line = NULL;
     ScriptBlock* p;
     if(!(*cur_ptr))
         next();
     line = new ScriptLine;
     line -> ID = cur_line_id;
     while(CurOffs < Size){
         if(*cur_ptr == '\n'){
             *cur_ptr = 0;
             cur_line_id ++;
             add_line(line);
             line = new ScriptLine;
             line -> ID = cur_line_id;
         }
         else {
             _sALLOC_(ScriptBlock,p);
             p -> data = cur_ptr;
             line -> connect(p);
         }
         next();
     }
 }
References _sALLOC_, add_line(), cur_ptr, CurOffs, next(), NULL, and Size.
process_includes()
int ScriptFile::process_includes (void)
 {
     int ret = 0;
     char* p,*p1,*p2;
     XStream fh;
     ScriptFileBuffer* b,*b1;
     int i,offs = 0,sz = strlen(INC_STR);
     reset();
     while(CurOffs < Size - 1){
         read_src_line();
         p = strchr(binConvBuf,'#');
         if(p){
             if(!strncmp(p,INC_STR,sz)){
                 p1 = strchr(p,'\"');
                 if(!p1) ErrH.Abort("Bad include line...");
                 p1 ++;
                 p2 = strchr(p1,'\"');
                 if(!p2) ErrH.Abort("Bad include line...");
                 *p2 = 0;
                 b = new ScriptFileBuffer;
                 fh.open(p1,XS_IN);
                 b -> load(&fh);
                 fh.close();
                 b -> offset = CurOffs;
                 next_src_line();
                 b -> offset_size = CurOffs - b -> offset;
                 add_buf(b);
                 ret = 1;
             }
             else
                 next_src_line();
         }
         else
             next_src_line();
     }
     reset();
     b = fBuf;
     if(!NumBufs) return 0;
     fh.open("iscreen/temp.scr",XS_OUT);
     for(i = 0; i < NumBufs; i ++){
         if(offs != b -> offset)
             fh.write(buffer + offs,b -> offset - offs);
         offs = b -> offset + b -> offset_size;
         b -> save(&fh);
         b = b -> next;
     }
     fh.write(buffer + offs,Size - offs);
     fh.close();
     delete[] buffer;
     b = lBuf;
     while(b){
         b1 = b -> prev;
         delete b;
         b = b1;
     }
     NumBufs = 0;
     fBuf = lBuf = NULL;
     fh.open("iscreen/temp.scr",XS_IN);
     Size = fh.size();
     buffer = new char[Size];
     fh.read(buffer,Size);
     fh.close();
     reset();
     return ret;
 }
Referenced by load().
read_idata()
int ScriptFile::read_idata (void)
 {
     int val;
 #ifdef _BINARY_SCRIPT_
     *binConv > val;
     if(binConv -> end())
         EOF_Flag = 1;
 #else
     val = parse_math();
 #ifdef _SAVE_BINARY_SCRIPT_
     write_idata(val);
 #endif
 #endif
     return val;
 }
References EOF_Flag, parse_math(), and write_idata().
Referenced by read_key(), and read_option().
read_key()
int ScriptFile::read_key (void)
 {
     int val = 0;
 #ifdef _BINARY_SCRIPT_
     val = read_idata();
 #else
     val = GetKeyCode(get_ptr());
     next_ptr();
 #ifdef _SAVE_BINARY_SCRIPT_
     write_idata(val);
 #endif
 #endif
     return val;
 }
References get_ptr(), GetKeyCode(), next_ptr(), read_idata(), and write_idata().
read_option()
int ScriptFile::read_option (int mode = 1)
 {
     int val = -1;
 #ifdef _BINARY_SCRIPT_
     val = read_idata();
 #else
     if(mode == 0)
         val = aGetOptionID(get_ptr());
     if(mode == 1)
         val = GetOptionID(get_ptr());
     if(mode == -1)
         val = acsGetOptionID(get_ptr());
     next_ptr();
 #ifdef _SAVE_BINARY_SCRIPT_
     write_idata(val);
 #endif
 #endif
     return val;
 }
References acsGetOptionID(), aGetOptionID(), get_ptr(), GetOptionID(), next_ptr(), read_idata(), and write_idata().
read_pdata()
void ScriptFile::read_pdata (char ** ptr, int mode = 0)
 {
     int sz;
 #ifdef _BINARY_SCRIPT_
     *binConv > sz;
     if(mode)
         ptr[0] = new char[sz + 1];
     *binConv > ptr[0];
     if(binConv -> end())
         EOF_Flag = 1;
 #else
     sz = strlen(get_ptr());
     if(mode)
         ptr[0] = new char[sz + 1];
     strcpy(ptr[0],get_ptr());
     next_ptr();
 #ifdef _SAVE_BINARY_SCRIPT_
     write_pdata(ptr[0]);
 #endif
 #endif
 }
References EOF_Flag, get_ptr(), next_ptr(), and write_pdata().
read_src_line()
void ScriptFile::read_src_line (void)
 {
     int i = 0;
     memset(binConvBuf,0,SCRIPT_CONV_BUF_SIZE);
     while(cur_ptr[i] != '\n'){
         if(i + CurOffs > Size - 1) return;
         if(i >= SCRIPT_CONV_BUF_SIZE)
             ErrH.Abort("Script buffer overflow...");
         binConvBuf[i] = cur_ptr[i];
         i++;
     }
 }
References XErrorHandler::Abort(), binConvBuf, cur_ptr, CurOffs, ErrH, SCRIPT_CONV_BUF_SIZE, and Size.
remove_line()
void ScriptFile::remove_line (ScriptLine * p)
 {
     if(p -> next -> prev)
         p -> next -> prev = p -> prev;
     else
         lastLine = p -> prev;
     if(p -> prev)
         p -> prev -> next = p -> next;
     else {
         firstLine = p -> next;
         lastLine-> next = p -> next;
     }
     NumStr --;
 }
References firstLine, lastLine, next(), NumStr, and prev.
reset()
void ScriptFile::reset (void)
 {
     CurOffs = 0;
     cur_ptr = buffer;
     EOF_Flag = 0;
     curLine = firstLine;
     if(curLine)
         curBlock = curLine -> first;
     else
         curBlock = NULL;
 }
References buffer, cur_ptr, curBlock, curLine, CurOffs, EOF_Flag, firstLine, and NULL.
Referenced by strip_comments().
Seek()
int ScriptFile::Seek (char * s)
 {
     int i,sz = strlen(s);
     for(i = CurOffs; i <= Size - sz; i ++){
         if(*cur_ptr == *s){
             if(!strncmp(cur_ptr,s,sz))
                 return 1;
         }
         cur_ptr ++;
         CurOffs ++;
     }
     return 0;
 }
References cur_ptr, CurOffs, and Size.
SeekChar()
int ScriptFile::SeekChar (char s)
 {
     int i;
     for(i = CurOffs; i <= Size - 1; i ++){
         if(*cur_ptr == s){
             return 1;
         }
         cur_ptr ++;
         CurOffs ++;
     }
     return 0;
 }
References cur_ptr, CurOffs, and Size.
SeekCharPos()
int ScriptFile::SeekCharPos (char s)
 {
     int i;
     for(i = 0; i <= Size - (1 + CurOffs); i ++){
         if(*(cur_ptr + i) == s){
             return i;
         }
     }
     return -1;
 }
References cur_ptr, CurOffs, and Size.
Referenced by prepare().
SeekComm()
int ScriptFile::SeekComm (int mode)
 {
     int i;
     char c1 = 0,c2 = 0;
     switch(mode){
         case C_COMMENT:
             c1 = '/';
             c2 = '*';
             break;
         case CPP_COMMENT:
             c1 = c2 = '/';
             break;
         case C_COMMENT_END:
             c1 = '*';
             c2 = '/';
             break;
         case CPP_COMMENT_END:
             c1 = '\r';
             c2 = '\n';
             break;
     }
     for(i = CurOffs; i <= Size - 2; i ++){
         if(*cur_ptr == c1){
             if(*(cur_ptr + 1) == c2)
                 return 1;
         }
         cur_ptr ++;
         CurOffs ++;
     }
     return 0;
 }
References C_COMMENT, C_COMMENT_END, CPP_COMMENT, CPP_COMMENT_END, cur_ptr, CurOffs, and Size.
Referenced by strip_comments().
SeekCommPos()
int ScriptFile::SeekCommPos (int mode)
 {
     int i;
     char c1 = 0,c2 = 0;
     switch(mode){
         case C_COMMENT:
             c1 = '/';
             c2 = '*';
             break;
         case CPP_COMMENT:
             c1 = c2 = '/';
             break;
         case C_COMMENT_END:
             c1 = '*';
             c2 = '/';
             break;
         case CPP_COMMENT_END:
             c1 = '\r';
             c2 = '\n';
             break;
     }
     for(i = 0; i <= Size - (2 + CurOffs); i ++){
         if(*(cur_ptr + i) == c1){
             if(*(cur_ptr + i + 1) == c2)
                 return i;
         }
     }
     return -1;
 }
References C_COMMENT, C_COMMENT_END, CPP_COMMENT, CPP_COMMENT_END, cur_ptr, CurOffs, and Size.
Referenced by strip_comments().
SeekPos()
int ScriptFile::SeekPos (char * s)
 {
     int i,sz = strlen(s);
     for(i = 0; i <= Size - (sz + CurOffs); i ++){
         if(*(cur_ptr + i) == *s){
             if(!strncmp(cur_ptr + i,s,sz))
                 return i;
         }
     }
     return -1;
 }
References cur_ptr, CurOffs, and Size.
set_bscript_name()
void ScriptFile::set_bscript_name (char * fname)
 {
     int sz = strlen(fname) + 1;
     bScriptName = new char[sz];
     strcpy(bScriptName,fname);
 }
References bScriptName.
strip_comments()
void ScriptFile::strip_comments (void)
 {
     int i,offs;
     while(SeekComm(CPP_COMMENT)){
         if((offs = SeekCommPos(CPP_COMMENT_END)) != -1){
             for(i = 0; i < offs + 2; i ++)
                 if(cur_ptr[i] != '\n')
                     cur_ptr[i] = 0;
             cur_ptr += offs + 2;
             CurOffs += offs + 2;
         }
         else
             handle_error("Bad script comment");
         if(CurOffs >= Size)
             break;
     }
     reset();
     while(SeekComm(C_COMMENT)){
         if((offs = SeekCommPos(C_COMMENT_END)) != -1){
             for(i = 0; i < offs + 2; i ++)
                 if(cur_ptr[i] != '\n')
                     cur_ptr[i] = 0;
             cur_ptr += offs + 2;
             CurOffs += offs + 2;
         }
         else
             handle_error("Bad script comment");
         if(CurOffs >= Size)
             break;
     }
     reset();
 }
References C_COMMENT, C_COMMENT_END, CPP_COMMENT, CPP_COMMENT_END, cur_ptr, CurOffs, handle_error(), reset(), SeekComm(), SeekCommPos(), and Size.
Referenced by prepare().
write_end()
void ScriptFile::write_end (void)
 {
     write_idata(iSCRIPT_EOF);
 }
References iSCRIPT_EOF, and write_idata().
Referenced by close_bscript().
write_idata()
void ScriptFile::write_idata (int val)
 {
     *bin_fh < val;
 }
References bin_fh.
Referenced by prepare_idata(), read_idata(), read_key(), read_option(), and write_end().
write_pdata()
void ScriptFile::write_pdata (char * ptr)
 {
     int sz = strlen(p);
     *bin_fh < sz < p < '\0';
 }
References bin_fh.
Referenced by prepare_pdata(), and read_pdata().
Member Data Documentation
bin_fh
XStream* ScriptFile::bin_fh
Referenced by close_bscript(), open_bscript(), write_idata(), and write_pdata().
binConvBuf
char* ScriptFile::binConvBuf
Referenced by get_conv_ptr(), get_pdata(), get_pdata_ptr(), get_ptr(), prepare_pdata(), read_src_line(), ScriptFile(), and ~ScriptFile().
binConvBufSize
int ScriptFile::binConvBufSize
Referenced by get_pdata(), prepare_pdata(), and ScriptFile().
binConvData
int ScriptFile::binConvData
Referenced by get_idata(), and prepare_idata().
bScriptName
char* ScriptFile::bScriptName
Referenced by close_bscript(), open_bscript(), ScriptFile(), and set_bscript_name().
buffer
char* ScriptFile::buffer
Referenced by load(), reset(), ScriptFile(), and ~ScriptFile().
CompressLog
int ScriptFile::CompressLog
Referenced by close_bscript(), and ScriptFile().
cur_ptr
char* ScriptFile::cur_ptr
Referenced by load(), next(), next_src_line(), prepare(), preprocess(), read_src_line(), reset(), Seek(), SeekChar(), SeekCharPos(), SeekComm(), SeekCommPos(), SeekPos(), and strip_comments().
curBlock
ScriptBlock* ScriptFile::curBlock
Referenced by check_math(), get_ptr(), next_line(), next_ptr(), parse_math(), reset(), and ScriptFile().
curLine
ScriptLine* ScriptFile::curLine
Referenced by get_cur_str(), next_line(), next_ptr(), and reset().
CurOffs
int ScriptFile::CurOffs
Referenced by load(), next(), next_src_line(), preprocess(), read_src_line(), reset(), Seek(), SeekChar(), SeekCharPos(), SeekComm(), SeekCommPos(), SeekPos(), and strip_comments().
EOF_Flag
int ScriptFile::EOF_Flag
Referenced by check_math(), next_line(), next_ptr(), prepare_idata(), prepare_pdata(), read_idata(), read_pdata(), reset(), and ScriptFile().
fBuf
ScriptFileBuffer* ScriptFile::fBuf
Referenced by add_buf(), free_buffers(), and ScriptFile().
fDef
ScriptDefine* ScriptFile::fDef
Referenced by add_def(), and ScriptFile().
firstLine
ScriptLine* ScriptFile::firstLine
Referenced by add_line(), next_line(), next_ptr(), remove_line(), reset(), and ScriptFile().
lastLine
ScriptLine* ScriptFile::lastLine
Referenced by add_line(), remove_line(), ScriptFile(), and ~ScriptFile().
lBuf
ScriptFileBuffer* ScriptFile::lBuf
Referenced by add_buf(), free_buffers(), and ScriptFile().
lDef
ScriptDefine* ScriptFile::lDef
Referenced by add_def(), ScriptFile(), and ~ScriptFile().
NumBufs
int ScriptFile::NumBufs
Referenced by add_buf(), free_buffers(), and ScriptFile().
NumDef
int ScriptFile::NumDef
Referenced by add_def(), and ScriptFile().
NumStr
int ScriptFile::NumStr
Referenced by add_def(), add_line(), remove_line(), and ScriptFile().
prevStrBuf
char* ScriptFile::prevStrBuf
Referenced by get_ptr(), ScriptFile(), and ~ScriptFile().
Size
int ScriptFile::Size
Referenced by load(), next(), next_src_line(), prepare(), preprocess(), read_src_line(), Seek(), SeekChar(), SeekCharPos(), SeekComm(), SeekCommPos(), SeekPos(), and strip_comments().
The documentation for this struct was generated from the following files:
src/iscreen/iscript.h
src/iscreen/script.cpp