Vangers: VangerUnit Struct Reference
VangerUnit Struct Reference
#include <mechos.h>
Public Member Functions
void TargetAnalysis (void)
void ResolveGenerator (void)
void NoWayHandler (void)
void ResolveHandler (aiUnitResolve *p)
int CheckReturn2Track (void)
void GetForceWay (int d2, Vector &v)
void WeaponGenerator (void)
int CheckNearTrack (void)
aiUnitEvent * AddEvent (int id, GeneralObject *obj, VangerUnit *subj)
void ClearSubjEvent (VangerUnit *subj)
void ClearObjEvent (GeneralObject *obj)
void ClearEvent (GeneralObject *obj)
void MainOrderInit (void)
int GetAllert (VangerUnit *p)
void StuffDestroyHandler (GeneralObject *p)
void VangerDestroyHandler (GeneralObject *p)
void InitAI (void)
void CheckFind (aiUnitResolve *p, Vector v)
void ResolveHandlerForce (aiUnitResolve *p)
void ResolveHandlerFind (aiUnitResolve *p)
void ResolveHandlerAttack (aiUnitResolve *p)
aiUnitResolve * AddFindResolve (int type, UnitOrderType obj, int level=0, int status=AI_RESOLVE_STATUS_NONE)
aiUnitEvent * FindEvent (VangerUnit *subj, GeneralObject *obj)
void NoWayInit (void)
void CalcImpulse (void)
void CalcForce (void)
void CalcWeaponDelta (void)
void AddEventTime (VangerUnit *p, int delta, int mode)
void ResolveFindDestroy (aiUnitResolve *p)
void GamerOrderInit (void)
void CalcAiFactor (VangerUnit *p, int ind)
void DestroyEnvironment (void)
void GetWeaponDelta (void)
void Init (StorageType *s)
void Free (void)
void TouchSensor (SensorDataType *p)
void AutomaticTouchSensor (SensorDataType *p)
void StopTouchSensor (SensorDataType *p)
void Touch (GeneralObject *p)
void SensorQuant (void)
void Action (void)
void HideAction (void)
void Quant (void)
void DrawQuant (void)
void Destroy (void)
void keyhandler (int key)
void NewKeyHandler (void)
void InitEnvironment (void)
void CreateVangerUnit (void)
void CreateParticleRotor (const Vector &v, int r)
void CreateParticleMechos (const Vector &v, int r, int type=0)
void AddFree (void)
void AddPassage (SensorDataType *p)
void AddEscave (SensorDataType *p)
void AddSpot (SensorDataType *p)
void ItemQuant (void)
void Go2World (void)
void Go2Universe (void)
char CheckInDevice (StuffObject *p)
void CheckOutDevice (StuffObject *p)
void Hide2Show (void)
void DeleteHandler (void)
void BulletCollision (int pow, GeneralObject *p)
void DestroyCollision (int l, Object *p)
int test_objects_collision ()
void LocalScan (void)
void SwitchTarget (void)
void TerrainQuant (void)
void MoleProcessQuant (void)
void SetMechos (int n)
int CheckStartJump (void)
void DrawMechosParticle (int x, int y, int speed, int level, int n)
void SendCameraData (void)
void ChangeVangerProcess (void)
void InCarNator (void)
void OutCarNator (void)
void StartMoleProcess (void)
void MapQuant (void)
void CheckAmmo (void)
int UsingCopterig (int decr_8)
int UsingCrotrig (int decr_8)
int UsingCutterig (int decr_8)
int CheckSpeetle (void)
void NetCreateVanger (uvsPassage *pp, uvsEscave *pe, uvsSpot *ps)
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius_)
void ShellNetEvent (int type, int id, int creator, int time, int x, int y, int radius_)
void NetCreateSlave (void)
void InitPlayerPoint (PlayerData *p)
int CheckInMatrix (int sz)
int CheckOutMatrix (int sz)
void ShellUpdate (void)
void DischargeItem (StuffObject *p)
void DestroyItem (StuffObject *p)
void ClearItemList (void)
Public Member Functions inherited from TrackUnit
void Init (StorageType *s)
void Free (void)
void Open (void)
void Close (void)
void CreateTrackUnit (void)
int TraceWay (void)
void WayInit (void)
void GetNode (TrackLinkType *tp, char &dir)
void GetInside (void)
char GetDirect (TrackLinkType *tp)
char Check2Position (int fx, int fy, int num)
char TestAnalysis (TrackLinkType &tp)
void GetBranch (void)
void HideGetBranch (void)
char ActiveGetBranch (void)
void MixVector (void)
void GetTrackVector (void)
void DirectQuant (void)
void TrackQuant (void)
void LastFire (void)
void DrawMechosParticle (int x, int y, int speed, int level, int n)
void MakeTrackDist (void)
int GeneralRND (unsigned int m)
Public Member Functions inherited from ActionUnit
void Init (StorageType *s)
void Free (void)
void Open (void)
void Close (void)
void DrawQuant (void)
void CreateActionUnit (int nmodel, int _status, const Vector &_v, int _angle, int put_mode)
void CalcTrackVector (Vector &v, int &len, int &angle1, int &angle2)
void Action (void)
void HideAction (void)
void MixVector (void)
void Touch (GeneralObject *obj)
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
Public Member Functions inherited from TrackLinkType
TrackLinkType (void)
void ChangeLink (void)
void HideChangeLink (char dir)
void AddLink (char s)
void DecLink (char s)
Public Member Functions inherited from uvsUnitType
void Init (void)
void Free (void)
void CreateUnitType (uvsVanger *p)
void AddDevice (StuffObject *p)
void DelDevice (StuffObject *p)
void AddOxigenResource (void)
void UseOxigenResource (void)
Public Member Functions inherited from aiFactorType
void FactorOpen (aiFactorType *in)
void FactorLoad (Parser &in)
Public Attributes
Vector vMove
int ShellNetID
int ShellUpdateFlag
int aiActionID
int aiStatus
aiResolveList aiResolveFind
aiResolveList aiResolveAttack
aiListType aiEvent
int NoWayEnable
Vector aiNearTrack
int aiResolveWayEnable
int aiModifier
aiUnitResolve * aiLocalTarget
int aiScanDist
int aiReactionTime
int aiReactionTimeMax
int aiVangerRadius
int aiFirstItem
int aiSecondItem
int aiItemRadius
int MixVectorEnable
BranchType * aiRunBranch
NodeType * aiRunNode
Vector vRunStartPosition
int RunStartDist
int RunTimeProcess
int aiMaxJumpRadius
int WeaponDelta
int SeedNum
int MaxSeed
int LowAmmo
int LowArmor
int ArmorAlarm
int aiAlarmTime
int aiDamage
int SpeedFactorTime
VangerUnit * aiDamageData
float aiResolveFactor [MAX_AI_FACTOR]
int aiRelaxTime
int aiRealxRadius
int aiRelaxTimeMax
Vector aiRelaxData
int WallCollisionTime
int DeltaTractionTime
int TractionValue
int TractionStat
StuffObject * CoptePoint
StuffObject * MolePoint
StuffObject * SwimPoint
int AttackRadius
int aiReactionCheckTime
int aiReactionMode
int aiReactionCheckTimeMax
int AddAttackTime
int BeebonationFlag
int SensorEnable
int UseDeviceMask
int VangerRaceStatus
int DoorFlag
int nDoorFlag
int NetCreateID
int NetExternalSensor
unsigned char NetDestroyID
int LastMole
dastPoly3D * MoleTool
dastPoly3D * MolePoint1
dastPoly3D * MolePoint2
int Molerizator
int VangerCloneID
VangerUnit * VangerChanger
int MechosChangerType
int VangerChangerCount
Vector vChangerPosition
int VangerChangerAngle
int VangerChangerArmor
int VangerChangerEnergy
int VangerChangerColor
unsigned char NetChanger
unsigned char NetFunction
unsigned int NetRuffaGunTime
unsigned int NetProtractorFunctionTime
unsigned int NetMessiahFunctionTime
unsigned int NetFunction83Time
unsigned int PrevNetFunction83Time
GunSlot GunSlotData [MAX_ACTIVE_SLOT]
int RuffaGunTime
SensorDataType * TouchKeyObject
int TouchKeyObjectFlag
int ExternalMode
int ExternalTime
int ExternalLock
int ExternalDraw
int ExternalAngle
int ExternalTime2
SensorDataType * ExternalObject
SensorDataType * ExternalLastSensor
SensorDataType * ExternalSensor
int RandomUpdate
PlayerData * pNetPlayer
int NetworkArmor
int NetworkEnergy
int TabuUse
int CheckPointCount
int MaxKhoxPoison
int KhoxPoison
int PlayerDestroyFlag
int PrevImpuseFrame
Public Attributes inherited from TrackUnit
int aiMoveMode
int aiMoveFunction
TrackLinkType TestPoint
TrackLinkType FrontPoint
int * WayDist
int * WayDistData
int * CalcWayDist
int * TrackDist
int NoWayDirect
TrackLinkType TargetPoint
Vector vTarget
int TargetAngle
int TargetLen
int EnvirReaction
int TargetReaction
int NullTime
char MoveDir
char FrontDir
BranchType * PrevBranch
int CheckPosition
int MaxCheckPosition
int CheckWayCount
int MaxWayCount
int DestroyPhase
int PrevWheelX [6]
int PrevWheelY [6]
int PrevWheelFlag [6]
int gRnd
Public Attributes inherited from ActionUnit
Vector vDirect
Vector vEnvir
int EnvirAngle
int EnvirLen
int NumCalcUnit
int NumViewUnit
int MaxVelocity
int ViewRadius
char SpeedDir
int MinSpeed
int MaxSpeed
int CurrSpeed
int MaxHideSpeed
int MoveAngle
int DeltaSpeed
int DeltaTraction
char OtherFlag
Vector vUp
Vector vDown
int Speed
int Angle
DBM RotMat
DBM MovMat
int PrevVisibility
int Count
int WavePhase
WaveProcess * wProcess
int nModel
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Public Attributes inherited from TrackLinkType
char PointStatus
Vector vPoint
LinkType * pNextLink
LinkType * pPrevLink
BranchType * pBranch
NodeType * pNode
Public Attributes inherited from uvsUnitType
int NumDevice
StuffObject * DeviceData
UnitItemMatrix * ItemMatrix
int * ItemMatrixData
int MaxVolume
int Volume
int MaxEnergy
int MaxArmor
int Armor
int Energy
int dEnergy
int DropEnergy
int DelayDrop
int DropTime
int uvsMaxSpeed
int MaxOxigenResource
int OxigenResource
int MaxPassageCount
int PassageCount
int DestroyClass
int PowerFlag
int aiPowerFlag
int ImpulsePower
Public Attributes inherited from uvsKernel
uvsVanger * uvsPoint
Public Attributes inherited from aiFactorType
int aiSection
int aiAttackUp
int aiAttackDown
int aiRunUp
int aiRunDown
int aiIgnoreUp
int aiIgnoreDown
int aiNoWayUp
int aiNoWayDown
float aiFactorAttack
float aiFactorRun
float aiFactorIgnore
float aiFactorNoWay
float aiRacerAttack
int aiMainLevel
int aiDeltaLevel
int aiFindLevel
int aiAddAttack
int aiMaxAttack
int aiAddView
int aiMaxView
int aiAddFrontCollision
int aiMaxFrontCollision
int aiAddBackCollision
int aiMaxBackCollision
int aiAddSideCollision
int aiMaxSideCollision
int aiAddAlarm
int aiMaxAlarm
float aiFuryLevel
float aiAlarmRun
float aiAlarmAttack
float aiAmmoRun
float aiAmmoAttack
float aiArmorRun
float aiArmorAttack
float aiMultyAttack
float aiTargetAttack
float aiTargetFind
float aiDollyAttack
float aiDollyRun
float aiDominanceAttack
float aiDominanceRun
float aiFrontOverAttack
float aiFrontOverRun
float aiFrontOverIgnore
float aiFrontOverNoWay
float aiBackOverAttack
float aiBackOverRun
float aiBackOverIgnore
float aiBackOverNoWay
float aiFrontUnderAttack
float aiFrontUnderRun
float aiFrontUnderIgnore
float aiFrontUnderNoWay
float aiBackUnderAttack
float aiBackUnderRun
float aiBackUnderIgnore
float aiBackUnderNoWay
float aiVisibleRun
float aiVisibleAttack
float aiInvisibleRun
float aiInvisibleAttack
float aiAttackTime
Detailed Description
Member Function Documentation
Action()
void VangerUnit::Action (void)
 {
     int a;
     int d;
     Vector vCheck;
     jump_power = 0;
     switch(aiMoveMode){
         case AI_MOVE_TRACK:
             if(MixVectorEnable){
                 MixVector();
                 MoveAngle = rPI(vDirect.psi() + MoveAngle);
             }else{
                 MoveAngle = vDirect.psi();
                 DeltaSpeed = MaxVelocity;
             };
             switch(aiMoveFunction){
                 case AI_MOVE_FUNCTION_WHEEL:
                     if(aiRelaxTime > aiRelaxTimeMax && !(aiStatus & AI_STATUS_TARGET)){
                         a = rPI(Angle - MoveAngle);
                         if(a > PI) a -= 2*PI;
                         if((dynamic_state & GROUND_COLLISION) && !(dynamic_state & TRACTION_WHEEL_TOUCH)){
                             if(a > 0) controls(CONTROLS::LEFT_SIDE_IMPULSE,20);
                             else controls(CONTROLS::RIGHT_SIDE_IMPULSE,20);
                         };
                         if(WallCollisionTime){
                             if(NoWayEnable == AI_NO_WAY_NONE){
                                 if(!RND(5)) CalcImpulse();
                                 else CalcForce();
                             };
                         }else{
                             if(DeltaTractionTime) MixVectorEnable = 0;
                             else MixVectorEnable = 1;
                             if(aiRelaxTime > 2*aiRelaxTimeMax && NoWayEnable == AI_NO_WAY_NONE){
                                 if(!RND(5)) CalcImpulse();
                                 else CalcForce();
                             };
                         };
                     }else MixVectorEnable = 1;
                     break;
                 case AI_MOVE_FUNCTION_IMPULSE:
                 case AI_MOVE_FUNCTION_FLY:
                     aiMoveFunction = AI_MOVE_FUNCTION_WHEEL;
                     break;
             };
             break;
         case AI_MOVE_POINT:
             MoveAngle = vDirect.psi();
             DeltaSpeed = MaxVelocity;
             switch(aiMoveFunction){
                 case AI_MOVE_FUNCTION_WHEEL:
                     if(aiStatus & AI_STATUS_WHEEL){
                         if(aiRelaxTime > aiRelaxTimeMax){
                             a = rPI(Angle - MoveAngle);
                             if(a > PI) a -= 2*PI;
                             if((dynamic_state & GROUND_COLLISION) && !(dynamic_state & TRACTION_WHEEL_TOUCH)){
                                 if(a > 0) controls(CONTROLS::LEFT_SIDE_IMPULSE,20);
                                 else controls(CONTROLS::RIGHT_SIDE_IMPULSE,20);
                             };
                         };
                         if(!(aiStatus & AI_STATUS_TARGET) || WallCollisionTime){
                             if(aiStatus & AI_STATUS_FLY) aiMoveFunction = AI_MOVE_FUNCTION_FLY;
                             else aiMoveFunction = AI_MOVE_FUNCTION_IMPULSE;
                         };
                     }else{
                         if(aiStatus & AI_STATUS_FLY) aiMoveFunction = AI_MOVE_FUNCTION_FLY;
                         else aiMoveFunction = AI_MOVE_FUNCTION_IMPULSE;
                     };
                     break;
                 case AI_MOVE_FUNCTION_FLY:
                     if((aiStatus & AI_STATUS_TARGET) || !(aiStatus & AI_STATUS_FLY)){
                         aiMoveFunction = AI_MOVE_FUNCTION_WHEEL;
                         controls(CONTROLS::HELICOPTER_DOWN,20);
                     }else{
                         if(R_curr.z < 350)
                             controls(CONTROLS::HELICOPTER_UP,20);
                         if(aiRelaxTime > aiRelaxTimeMax*5){
                             if(aiStatus & AI_MOVE_FUNCTION_IMPULSE) aiMoveFunction = AI_MOVE_FUNCTION_IMPULSE;
                             else  aiMoveFunction = AI_MOVE_FUNCTION_WHEEL;
                         }else{
                             if((dynamic_state & GROUND_COLLISION) && R_curr.z < 300){
                                 jump_power = aiRelaxTime * (max_jump_power - 1) / (aiRelaxTimeMax*5);
                                 controls(CONTROLS::JUMP_USING_ACCUMULATED_POWER,20);
                             };
                         };
                     };
                     break;
                 case AI_MOVE_FUNCTION_IMPULSE:
                     if(!(aiStatus & AI_STATUS_IMPULSE) || (aiStatus & AI_STATUS_TARGET)){
                         aiMoveFunction = AI_MOVE_FUNCTION_WHEEL;
                         aiReactionCheckTime = 0;
                         aiReactionMode = 0;
                         aiReactionTime = 0;
                     }else{
                         a = rPI(Angle - MoveAngle);
                         if(a > PI) a -= 2*PI;
                         switch(aiReactionMode){
                             case 0:
                                 if(dynamic_state & TOUCH_OF_GROUND){
                                     vCheck = Vector(getDistX(TargetPoint.vPoint.x,R_curr.x),getDistY(TargetPoint.vPoint.y,R_curr.y),0);
                                     d = vCheck.vabs();
                                     if(d < aiMaxJumpRadius) jump_power = d * (max_jump_power - 1) / aiMaxJumpRadius;
                                     else jump_power = max_jump_power - 1;
                                     controls(CONTROLS::JUMP_USING_ACCUMULATED_POWER,20);
                                     aiReactionMode = 1;
                                     aiRelaxTime = 0;
                                     aiReactionCheckTime = 0;
                                 };
                                 break;
                             case 1:
                                 if(aiRelaxTime > aiRelaxTimeMax || WallCollisionTime){
                                     aiReactionMode = 2;
                                     aiReactionCheckTime = 0;
                                 }else{
                                     if(aiReactionCheckTime > aiReactionCheckTimeMax){
                                         aiMoveFunction = AI_MOVE_FUNCTION_WHEEL;
                                         aiReactionMode = 1;
                                         aiRelaxTime = 0;
                                         aiReactionCheckTime = 0;
                                     }else{
                                         aiReactionCheckTime++;
                                         if((dynamic_state & GROUND_COLLISION) && !(dynamic_state & TRACTION_WHEEL_TOUCH)){
                                             if(a > 0) controls(CONTROLS::LEFT_SIDE_IMPULSE,20);
                                             else controls(CONTROLS::RIGHT_SIDE_IMPULSE,20);
                                         };
                                     };
                                 };
                                 break;
                             case 2:
                                 if((dynamic_state & GROUND_COLLISION) && !(dynamic_state & TRACTION_WHEEL_TOUCH)){
                                     if(a > 0) controls(CONTROLS::LEFT_SIDE_IMPULSE,20);
                                     else controls(CONTROLS::RIGHT_SIDE_IMPULSE,20);
                                 };
                                 if(abs(a) < PI / 8 || aiReactionCheckTime > 2*aiRelaxTimeMax) aiReactionMode = 0;
                                 else{
                                     aiReactionCheckTime++;
                                     if(aiReactionCheckTime < aiRelaxTimeMax)
                                         DeltaSpeed = -DeltaSpeed*4;
                                 };
                                 break;
                         };
                     };
                     break;
             };
             break;
     };
     TrackUnit::Action();
     if(!(frame % MAX_TRACTION_CHECK)){
         TractionValue = TractionStat / MAX_TRACTION_CHECK;
         TractionStat = 0;
     };
     TractionStat += CurrSpeed;
 };
References ActionUnit::Action(), AI_MOVE_FUNCTION_FLY, AI_MOVE_FUNCTION_IMPULSE, AI_MOVE_FUNCTION_WHEEL, AI_MOVE_POINT, AI_MOVE_TRACK, AI_NO_WAY_NONE, AI_STATUS_FLY, AI_STATUS_IMPULSE, AI_STATUS_TARGET, AI_STATUS_WHEEL, aiMaxJumpRadius, TrackUnit::aiMoveFunction, TrackUnit::aiMoveMode, aiReactionCheckTime, aiReactionCheckTimeMax, aiReactionMode, aiReactionTime, aiRelaxTime, aiRelaxTimeMax, aiStatus, ActionUnit::Angle, CalcForce(), CalcImpulse(), Object::controls(), ActionUnit::CurrSpeed, ActionUnit::DeltaSpeed, DeltaTractionTime, frame, getDistX(), getDistY(), GROUND_COLLISION, CONTROLS::HELICOPTER_DOWN, CONTROLS::HELICOPTER_UP, Object::jump_power, CONTROLS::JUMP_USING_ACCUMULATED_POWER, CONTROLS::LEFT_SIDE_IMPULSE, max_jump_power, MAX_TRACTION_CHECK, ActionUnit::MaxVelocity, TrackUnit::MixVector(), MixVectorEnable, ActionUnit::MoveAngle, NoWayEnable, PI, Vector::psi(), CONTROLS::RIGHT_SIDE_IMPULSE, RND(), rPI, TrackUnit::TargetPoint, TOUCH_OF_GROUND, TRACTION_WHEEL_TOUCH, TractionStat, TractionValue, Vector::vabs(), ActionUnit::vDirect, TrackLinkType::vPoint, WallCollisionTime, Vector::x, and Vector::y.
Referenced by Quant().
AddEscave()
void VangerUnit::AddEscave (SensorDataType * p)
 {
     ExternalMode = EXTERNAL_MODE_ESCAVE_OUT;
     ExternalObject = p;
     ExternalTime = p->Owner->ActiveTime;
     ExternalLock = 1;
     ExternalDraw = 1;
     switch_analysis(1);
     if(Status & SOBJ_ACTIVE){
         if(ChangeArmor != -1 && ChangeEnergy != -1){
             Energy = ChangeEnergy;
             Armor = ChangeArmor;
         };
     };
 //  if(Visibility == VISIBLE)
 //      SOUND_ENTRANCE();
 };
References LocationEngine::ActiveTime, uvsUnitType::Armor, ChangeArmor, ChangeEnergy, uvsUnitType::Energy, EXTERNAL_MODE_ESCAVE_OUT, ExternalDraw, ExternalLock, ExternalMode, ExternalObject, ExternalTime, SensorDataType::Owner, SOBJ_ACTIVE, and Object::switch_analysis().
Referenced by addVanger().
AddEvent()
aiUnitEvent * VangerUnit::AddEvent (int id, GeneralObject * obj, VangerUnit * subj)
 {
     aiUnitEvent* l;
     l = (aiUnitEvent*)(aiEvent.Tail);
     while(l){
         if(l->ID == id && l->Obj == obj && l->Subj == subj){
             l->Refresh = 1;
             return l;
         };
         l = (aiUnitEvent*)(l->Next);
     };
     l = new aiUnitEvent;
     l->ID = id;
     l->Obj = obj;
     l->Subj = subj;
     l->Refresh = 1;
     l->Time = 0;
     aiEvent.Connect(l);
     switch(id){
         case AI_EVENT_ITEM:
             aiResolveFind.AddResolve(UNIT_ORDER_STUFF,UnitOrderType((StuffObject*)(obj)))->Time = MaxWayCount;
             break;
     };
     return l;
 };
References aiResolveList::AddResolve(), AI_EVENT_ITEM, aiEvent, aiResolveFind, aiListType::Connect(), aiUnitEvent::ID, TrackUnit::MaxWayCount, aiListElement::Next, aiUnitEvent::Obj, aiUnitEvent::Refresh, aiUnitEvent::Subj, aiListType::Tail, aiUnitEvent::Time, and UNIT_ORDER_STUFF.
Referenced by ResolveGenerator().
AddEventTime()
void VangerUnit::AddEventTime (VangerUnit * p, int delta, int mode)
 {
     aiUnitEvent* l;
     l = (aiUnitEvent*)(aiEvent.Tail);
     while(l){
         if(l->Subj == p){
             switch(mode){
                 case AI_ADD_FRONT_COLLISION:
                     if(l->Time < aiMaxFrontCollision)
                         l->Time += delta;
                     break;
                 case AI_ADD_BACK_COLLISION:
                     if(l->Time < aiMaxBackCollision)
                         l->Time += delta;
                     break;
                 case AI_ADD_SIDE_COLLISION:
                     if(l->Time < aiMaxSideCollision)
                         l->Time += delta;
                     break;
                 case AI_ADD_ATTACK:
                     if(l->Time < aiMaxAttack)
                         l->Time += delta;
                     break;
             };
             return;
         };
         l = (aiUnitEvent*)(l->Next);
     };
 };
References AI_ADD_ATTACK, AI_ADD_BACK_COLLISION, AI_ADD_FRONT_COLLISION, AI_ADD_SIDE_COLLISION, aiEvent, aiFactorType::aiMaxAttack, aiFactorType::aiMaxBackCollision, aiFactorType::aiMaxFrontCollision, aiFactorType::aiMaxSideCollision, aiListElement::Next, aiUnitEvent::Subj, aiListType::Tail, and aiUnitEvent::Time.
Referenced by ResolveGenerator().
AddFindResolve()
aiUnitResolve * VangerUnit::AddFindResolve (int type, UnitOrderType obj, int level = 0, int status = AI_RESOLVE_STATUS_NONE)
 {
     aiUnitResolve* p;
     p = aiResolveFind.AddResolve(type,obj,level,status);
     switch(p->Type){
         case UNIT_ORDER_VANGER:
             TargetPoint.vPoint = (p->Obj.ActionT)->R_curr;
             break;
         case UNIT_ORDER_STUFF:
             if((p->Obj.StuffT)->Owner) TargetPoint.vPoint = ((p->Obj.StuffT)->Owner)->R_curr;
             else TargetPoint.vPoint = (p->Obj.StuffT)->R_curr;
             break;
         case UNIT_ORDER_SENSOR:
             TargetPoint.vPoint = (p->Obj.SensorT)->R_curr;
             break;
         case UNIT_ORDER_PASSAGE:
             TargetPoint.vPoint = (p->Obj.PassageT)->ActionLink->R_curr;
             aiLocalTarget = p;
             break;
         case UNIT_ORDER_ENTER:
             TargetPoint.vPoint = ((p->Obj.EnterT)->GetNearCenter(R_curr))->R_curr;
             aiLocalTarget = p;
             break;
         case UNIT_ORDER_DOLL:
             TargetPoint.vPoint = Vector((p->Obj.DollT)->pos_x,(p->Obj.DollT)->pos_y,0);
             break;
         case UNIT_ORDER_VECTOR:
             TargetPoint.vPoint.x = (p->Obj.vT).x;
             TargetPoint.vPoint.y = (p->Obj.vT).y;
             TargetPoint.vPoint.z = 0;
             break;
     };
     HideTrack.GetPosition(&TargetPoint);
     return p;
 };
References UnitOrderType::ActionT, aiResolveList::AddResolve(), aiLocalTarget, aiResolveFind, UnitOrderType::DollT, UnitOrderType::EnterT, TrackType::GetPosition(), HideTrack, level, aiUnitResolve::Obj, UnitOrderType::PassageT, UnitOrderType::SensorT, UnitOrderType::StuffT, TrackUnit::TargetPoint, aiUnitResolve::Type, UNIT_ORDER_DOLL, UNIT_ORDER_ENTER, UNIT_ORDER_PASSAGE, UNIT_ORDER_SENSOR, UNIT_ORDER_STUFF, UNIT_ORDER_VANGER, UNIT_ORDER_VECTOR, TrackLinkType::vPoint, UnitOrderType::vT, Object::x, Vector::x, Object::y, Vector::y, and Vector::z.
Referenced by CalcAiFactor(), GamerOrderInit(), MainOrderInit(), and ResolveGenerator().
AddFree()
void VangerUnit::AddFree (void)
 {
     int i;
     Vector vCheck;
     if(Status & SOBJ_ACTIVE){
         if(vSetVangerFlag != -1){
             ExternalMode = EXTERNAL_MODE_OUT_VANGER;
             ExternalObject = NULL;
             ExternalTime = CHANGE_VANGER_TIME;
             ExternalLock = 0;
             ExternalDraw = 1;
             switch_analysis(1);
             vSetVangerFlag = -1;
             PalCD.Set(CPAL_SHOW_PASSAGE,ExternalTime);
             for(i = 0;i < 5;i++){
                 vCheck = Vector(300,0,0)*DBM((int)(RND(PI*2)),Z_AXIS);
                 vCheck += R_curr;
                 cycleTor(vCheck.x,vCheck.y);
                 EffD.CreateParticleGenerator(vCheck,R_curr,Vector(5,0,0)*DBM((int)(RND(PI*2)),Z_AXIS),PG_STYLE_REINCAR);
             };
             set_3D(SET_3D_TO_THE_UPPER_LEVEL,R_curr.x,R_curr.y,R_curr.z,0,-Angle,0);
             SOUND_BOOT_START();
         }else{
             ExternalMode = EXTERNAL_MODE_PASS_OUT;
             ExternalObject = NULL;
             ExternalTime = ROTOR_PROCESS_LIFE_TIME;
             ExternalLock = 1;
             ExternalDraw = 0;
             switch_analysis(1);
             CreateParticleMechos(R_curr,500);
             if(!NetworkON || !PalIterLock) PalCD.Set(CPAL_SHOW_PASSAGE,ExternalTime);
             if(ChangeArmor != -1 && ChangeEnergy != -1){
                 Energy = ChangeEnergy;
                 Armor = ChangeArmor;
             };
             set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,255,0,-Angle,0);
         };
     }else{
         if(NetworkON && Visibility == VISIBLE && pNetPlayer && GetDistTime(NetGlobalTime,pNetPlayer->body.BirthTime) < 256*5 + 256*ROTOR_PROCESS_LIFE_TIME / 20){
             ExternalMode = EXTERNAL_MODE_PASS_OUT;
             ExternalObject = NULL;
             ExternalTime = ROTOR_PROCESS_LIFE_TIME;
             ExternalLock = 1;
             ExternalDraw = 0;
             switch_analysis(1);
             CreateParticleMechos(R_curr,500);
             set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,255,0,-Angle,0);
         }else{
             ExternalObject = NULL;
             ExternalMode = EXTERNAL_MODE_NORMAL;
             ExternalTime = 0;
             ExternalLock = 0;
             ExternalDraw = 1;
             switch_analysis(0);
         };
     };
 };
References ActionUnit::Angle, uvsUnitType::Armor, PlayerBody::BirthTime, PlayerData::body, CHANGE_VANGER_TIME, ChangeArmor, ChangeEnergy, CPAL_SHOW_PASSAGE, EffectDispatcher::CreateParticleGenerator(), CreateParticleMechos(), cycleTor(), EffD, uvsUnitType::Energy, EXTERNAL_MODE_NORMAL, EXTERNAL_MODE_OUT_VANGER, EXTERNAL_MODE_PASS_OUT, ExternalDraw, ExternalLock, ExternalMode, ExternalObject, ExternalTime, GetDistTime(), NetGlobalTime, NetworkON, NULL, PalCD, PalIterLock, PG_STYLE_REINCAR, PI, pNetPlayer, RND(), ROTOR_PROCESS_LIFE_TIME, PalConstructor::Set(), Object::set_3D(), SET_3D_DIRECT_PLACE, SET_3D_TO_THE_UPPER_LEVEL, SOBJ_ACTIVE, SOUND_BOOT_START, Object::switch_analysis(), VISIBLE, vSetVangerFlag, Vector::x, Vector::y, and Z_AXIS.
Referenced by addVanger(), and InitPlayerPoint().
AddPassage()
void VangerUnit::AddPassage (SensorDataType * p)
 {
     if(Status & SOBJ_ACTIVE){
         ExternalMode = EXTERNAL_MODE_PASS_OUT;
         ExternalObject = p;
         ExternalTime = p->Owner->ActiveTime;
         ExternalLock = 1;
         ExternalDraw = 0;
         switch_analysis(1);
         CreateParticleMechos(ExternalObject->R_curr,500);
         ActD.PassageTouchEnable = MAX_PASSAGE_DELAY;
         PalCD.Set(CPAL_SHOW_PASSAGE,ExternalTime);
         camera_direct(R_curr.x,R_curr.y,1 << 8,0,0,ExternalTime + 1);
         if(ChangeArmor != -1 && ChangeEnergy != -1){
             Energy = ChangeEnergy;
             Armor = ChangeArmor;
         };
     }else{
         if(NetworkON){
             if(Visibility == VISIBLE && pNetPlayer && GetDistTime(NetGlobalTime,pNetPlayer->body.BirthTime) < 256*5 + 256*ROTOR_PROCESS_LIFE_TIME/20){
                 ExternalMode = EXTERNAL_MODE_PASS_OUT;
                 ExternalObject = p;
                 ExternalTime = p->Owner->ActiveTime;
                 ExternalLock = 1;
                 ExternalDraw = 0;
                 switch_analysis(1);
                 CreateParticleMechos(ExternalObject->R_curr,500);
             }else{
                 ExternalObject = NULL;
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalTime = 0;
                 ExternalLock = 0;
                 ExternalDraw = 1;
                 switch_analysis(0);
             };
         }else{
             if(Visibility == VISIBLE){
                 ExternalMode = EXTERNAL_MODE_PASS_OUT;
                 ExternalObject = p;
                 ExternalTime = p->Owner->ActiveTime;
                 ExternalLock = 1;
                 ExternalDraw = 0;
                 switch_analysis(1);
                 CreateParticleMechos(ExternalObject->R_curr,500);
             }else{
                 ExternalObject = NULL;
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalTime = 0;
                 ExternalLock = 0;
                 ExternalDraw = 1;
                 switch_analysis(0);
             };
         };
     };
 /*  if(Visibility == VISIBLE || (Status & SOBJ_ACTIVE)){
 //      ExternalMode = EXTERNAL_MODE_PASS_IMPULSE;
         ExternalMode = EXTERNAL_MODE_PASS_OUT;
         ExternalObject = p;
 //      ExternalTime = p->Owner->ActiveTime + EXTERNAL_IMPULSE_TIME;
         ExternalTime = p->Owner->ActiveTime;
         ExternalLock = 1;
         ExternalDraw = 0;
 //      ExternalAngle = RND(2*PI);
         switch_analysis(1);
         CreateParticleMechos(ExternalObject->R_curr,500);
         if(Status & SOBJ_ACTIVE){
             ActD.PassageTouchEnable = MAX_PASSAGE_DELAY;
             PalCD.Set(CPAL_SHOW_PASSAGE,ExternalTime);
             camera_direct(R_curr.x,R_curr.y,1 << 8,0,0,ExternalTime);
             if(ChangeArmor != -1 && ChangeEnergy != -1){
                 Energy = ChangeEnergy;
                 Armor = ChangeArmor;
             };
         };
     }else{
         ExternalObject = NULL;
         ExternalMode = EXTERNAL_MODE_NORMAL;
         ExternalTime = 0;
         ExternalLock = 0;
         ExternalDraw = 1;
         switch_analysis(0);
     };*/
 };
References ActD, LocationEngine::ActiveTime, uvsUnitType::Armor, PlayerBody::BirthTime, PlayerData::body, camera_direct(), ChangeArmor, ChangeEnergy, CPAL_SHOW_PASSAGE, CreateParticleMechos(), uvsUnitType::Energy, EXTERNAL_MODE_NORMAL, EXTERNAL_MODE_PASS_OUT, ExternalDraw, ExternalLock, ExternalMode, ExternalObject, ExternalTime, GetDistTime(), MAX_PASSAGE_DELAY, NetGlobalTime, NetworkON, NULL, SensorDataType::Owner, PalCD, ActionDispatcher::PassageTouchEnable, pNetPlayer, GeneralObject::R_curr, ROTOR_PROCESS_LIFE_TIME, PalConstructor::Set(), SOBJ_ACTIVE, Object::switch_analysis(), and VISIBLE.
Referenced by addVanger().
AddSpot()
void VangerUnit::AddSpot (SensorDataType * p)
 {
     ExternalMode = EXTERNAL_MODE_SPOT_OUT;
     ExternalObject = p;
     ExternalTime = p->Owner->ActiveTime;
     ExternalLock = 1;
     ExternalDraw = 1;
     switch_analysis(1);
     if(Status & SOBJ_ACTIVE){
         if(ChangeArmor != -1 && ChangeEnergy != -1){
             Energy = ChangeEnergy;
             Armor = ChangeArmor;
         };
     };
 //  if(Visibility == VISIBLE)
 //      SOUND_ENTRANCE();
 };
References LocationEngine::ActiveTime, uvsUnitType::Armor, ChangeArmor, ChangeEnergy, uvsUnitType::Energy, EXTERNAL_MODE_SPOT_OUT, ExternalDraw, ExternalLock, ExternalMode, ExternalObject, ExternalTime, SensorDataType::Owner, SOBJ_ACTIVE, and Object::switch_analysis().
Referenced by addVanger().
AutomaticTouchSensor()
void VangerUnit::AutomaticTouchSensor (SensorDataType * p)
 {
     int etype;
     DoorEngine* d;
     if(p->Enable){
         p->Touch(this);
         switch(p->SensorType){
             case SensorTypeList::SPOT:
             case SensorTypeList::ESCAVE:
             case SensorTypeList::PASSAGE:
             case SensorTypeList::TRAIN:
             case SensorTypeList::TRAP:
                 if(!(Status & SOBJ_ACTIVE)){
                     if(ExternalSensor){
                         if(ExternalSensor == ExternalObject && ExternalObject != p) ExternalSensor = p;
                     }else ExternalSensor = p;
                 };
                 break;
             case SensorTypeList::IMPULSE:
                 impulse(p->vData,p->Power,0);
                 break;
             case SensorTypeList::SENSOR:
                 if(!(Status & SOBJ_ACTIVE)){
                     if(p->Owner){
                         if(p->Owner->Type == EngineTypeList::DOOR){
                             d = (DoorEngine*)(p->Owner);
                             if(d){
                                 if(aiLocalTarget && aiLocalTarget->Type == UNIT_ORDER_ENTER && FindDoor(d,etype) == (aiLocalTarget->Obj).EnterT){
                                     switch(etype){
                                         case EngineTypeList::IMPULSE_ESCAVE:
                                         case EngineTypeList::ELEVATOR:
                                             if(d->Mode == EngineModeList::WAIT && !d->ProcessFlag)
                                                 d->OpenDoor();
                                             break;
                                         case EngineTypeList::ESCAVE:
                                             if(TouchKeyObject && TouchKeyObject->SensorType == SensorTypeList::ESCAVE && d->Mode == EngineModeList::OPEN && !d->ProcessFlag)
                                                 d->CloseDoor();
                                             break;
                                     };
                                 };
                             };
                         };
                     };
                 };
                 break;
             case SensorTypeList::ARMOR_UPDATE:
                 Armor = MaxArmor;
                 LowArmor = 0;
                 break;
             case SensorTypeList::FIRE_UPDATE:
                 ChargeWeapon(this,ACI_GHORB_GEAR_LIGHT,1);
                 ChargeWeapon(this,ACI_GHORB_GEAR_HEAVY,1);
                 break;
         };
     }else{
         if(p->SensorType == SensorTypeList::SPOT || p->SensorType == SensorTypeList::ESCAVE || p->SensorType == SensorTypeList::PASSAGE){
             TouchKeyObject = p;
             TouchKeyObjectFlag = 0;
         };
     };
 };
References ACI_GHORB_GEAR_HEAVY, ACI_GHORB_GEAR_LIGHT, aiLocalTarget, uvsUnitType::Armor, SensorTypeList::ARMOR_UPDATE, ChargeWeapon(), DoorEngine::CloseDoor(), EngineTypeList::DOOR, EngineTypeList::ELEVATOR, StaticObject::Enable, SensorTypeList::ESCAVE, EngineTypeList::ESCAVE, ExternalObject, ExternalSensor, FindDoor(), SensorTypeList::FIRE_UPDATE, Object::impulse(), SensorTypeList::IMPULSE, EngineTypeList::IMPULSE_ESCAVE, LowArmor, uvsUnitType::MaxArmor, LocationEngine::Mode, aiUnitResolve::Obj, EngineModeList::OPEN, DoorEngine::OpenDoor(), SensorDataType::Owner, SensorTypeList::PASSAGE, SensorDataType::Power, DoorEngine::ProcessFlag, SensorTypeList::SENSOR, SensorDataType::SensorType, SOBJ_ACTIVE, SensorTypeList::SPOT, SensorDataType::Touch(), TouchKeyObject, TouchKeyObjectFlag, SensorTypeList::TRAIN, SensorTypeList::TRAP, aiUnitResolve::Type, LocationEngine::Type, UNIT_ORDER_ENTER, SensorDataType::vData, and EngineModeList::WAIT.
Referenced by InitEnvironment().
BulletCollision()
void VangerUnit::BulletCollision (int pow, GeneralObject * p)
 {
     if(ActD.Active && Visibility == VISIBLE){
         if(p)SOUND_HIT(getDistX(ActD.Active->R_curr.x,R_curr.x))
         else{
             if(Status & SOBJ_ACTIVE) SOUND_DAMAGE()
         };
     };
     if(NetworkON && !(Status & SOBJ_ACTIVE)) return;
     int pa = Armor;
     int s;
     if(original_scale_size - scale_size)
         pow = round((double)(pow) * 2. * original_scale_size / (original_scale_size - scale_size));
     Energy -= pow;
     if(Energy < 0){
         Armor += Energy;
         Energy = 0;
     };
     if(pa > 0 && Armor <= 0 && p && NetworkON && p->ID == ID_VANGER){
         switch(my_server_data.GameType){
             case VAN_WAR:
                 if(!(my_server_data.Van_War.TeamMode) || ((VangerUnit*)(p))->uvsPoint->Pmechos->color != uvsPoint->Pmechos->color)
                     NetDestroyID = GET_STATION(p->NetID);
                 break;
             case PASSEMBLOSS:
                 NetDestroyID = GET_STATION(p->NetID);
                 break;
             case MECHOSOMA:
                 if(!(my_server_data.Mechosoma.TeamMode) || ((VangerUnit*)(p))->uvsPoint->Pmechos->color != uvsPoint->Pmechos->color)
                     NetDestroyID = GET_STATION(p->NetID);
                 break;
         };
     };
     if(Status & SOBJ_ACTIVE){
         if(Armor < 0)
             Armor = 0;
     }else{
         if(p && p->ID == ID_VANGER && (p->Status & SOBJ_ACTIVE)){
             s = 0;
             if(!(TabuUse & TABUTASK_COUNT_OTHER)){
                 switch(VangerRaceStatus){
                     case VANGER_RACE_ELR:
                         s |= UVS_KRON_FLAG::ELEREC;
                         break;
                     case VANGER_RACE_PPS:
                         s |= UVS_KRON_FLAG::PIP;
                         break;
                     case VANGER_RACE_KRW:
                         s |= UVS_KRON_FLAG::KERN;
                         break;
                     case VANGER_RACE_ZLP:
                         s |= UVS_KRON_FLAG::ZEEXL;
                         break;
                 };
                 if(PowerFlag & VANGER_POWER_RUFFA_GUN)
                     s |= UVS_KRON_FLAG::RAFFA;
                 if(uvsPoint->Pmechos->color != uvsPoint->Pmechos->color)
                     s |= UVS_KRON_FLAG::ALIEN;
                 switch(uvsPoint->Pmechos->color){
                     case 0:
                         s |= UVS_KRON_FLAG::ELIPOD;
                         break;
                     case 1:
                         s |= UVS_KRON_FLAG::BEEBO;
                         break;
                     case 2:
                         s |= UVS_KRON_FLAG::ZEEX;
                         break;
                     default:
                         break;
                 };
                 TabuUse |= TABUTASK_COUNT_OTHER;
             };
             if((helicopter || R_curr.z > 300) && !(TabuUse & TABUTSAK_COUNT_FLY)){
                 s |= UVS_KRON_FLAG::FLY;
                 TabuUse |= TABUTSAK_COUNT_FLY;
             };
             if(VangerRaceStatus != VANGER_RACE_NONE && !(TabuUse & TABUTSAK_COUNT_RITUAL)){
                 s |= UVS_KRON_FLAG::RITUAL;
                 TabuUse |= TABUTSAK_COUNT_RITUAL;
             };
             if(CheckSpeetle() && !(TabuUse & TABUTASK_COUNT_SPEETLE)){
                 s |= UVS_KRON_FLAG::SPETLE;
                 TabuUse |= TABUTASK_COUNT_SPEETLE;
             };
             if(s) uvsCheckKronIventTabuTask(UVS_KRON_EVENT::SHOT,s);
             if(Armor <= 0 && pa > 0){
                 PlayerDestroyFlag = 1;
                 GamerResult.vanger_kill++;
                 uvsPoint->KillStatic();
             };
         };
     };
 };
References ActD, ActionDispatcher::Active, UVS_KRON_FLAG::ALIEN, uvsUnitType::Armor, UVS_KRON_FLAG::BEEBO, CheckSpeetle(), uvsMechos::color, UVS_KRON_FLAG::ELEREC, UVS_KRON_FLAG::ELIPOD, uvsUnitType::Energy, UVS_KRON_FLAG::FLY, GamerResult, ServerData::GameType, GET_STATION, getDistX(), Object::helicopter, Object::ID, GeneralObject::ID, ID_VANGER, UVS_KRON_FLAG::KERN, uvsVanger::KillStatic(), MECHOSOMA, ServerData::Mechosoma, my_server_data, NetDestroyID, GeneralObject::NetID, NetworkON, Object::original_scale_size, PASSEMBLOSS, UVS_KRON_FLAG::PIP, PlayerDestroyFlag, uvsVanger::Pmechos, uvsUnitType::PowerFlag, UVS_KRON_FLAG::RAFFA, UVS_KRON_FLAG::RITUAL, round(), Object::scale_size, UVS_KRON_EVENT::SHOT, SOBJ_ACTIVE, SOUND_DAMAGE, SOUND_HIT, UVS_KRON_FLAG::SPETLE, GeneralObject::Status, TABUTASK_COUNT_OTHER, TABUTASK_COUNT_SPEETLE, TABUTSAK_COUNT_FLY, TABUTSAK_COUNT_RITUAL, TabuUse, VAN_WAR_PRM::TeamMode, MECHOSOMA_PRM::TeamMode, uvsCheckKronIventTabuTask(), uvsKernel::uvsPoint, VAN_WAR, ServerData::Van_War, uvsGamerResult::vanger_kill, VANGER_POWER_RUFFA_GUN, VANGER_RACE_ELR, VANGER_RACE_KRW, VANGER_RACE_NONE, VANGER_RACE_PPS, VANGER_RACE_ZLP, VangerRaceStatus, VISIBLE, Object::x, UVS_KRON_FLAG::ZEEX, and UVS_KRON_FLAG::ZEEXL.
Referenced by DestroyEnvironment(), DrawQuant(), and ResolveHandlerAttack().
CalcAiFactor()
void VangerUnit::CalcAiFactor (VangerUnit * p, int ind)
 {
     int dx,dy,d1,d2;
     int i,d,a;
     float dd;
     uvsDolly* dl;
     if((time >= aiAttackDown  || aiAttackDown < 0) && (time <= aiAttackUp || aiAttackUp < 0))
         aiResolveFactor[AI_FACTOR_ATTACK] = aiFactorAttack;
     else
         aiResolveFactor[AI_FACTOR_ATTACK] = 0;
     if((time >= aiRunDown || aiRunDown < 0) && (time <= aiRunUp || aiRunUp < 0))
         aiResolveFactor[AI_FACTOR_RUN] = aiFactorRun;
     else
         aiResolveFactor[AI_FACTOR_RUN] = 0;
     if((time >= aiIgnoreDown || aiIgnoreDown < 0) && (time <= aiIgnoreUp || aiIgnoreUp < 0))
         aiResolveFactor[AI_FACTOR_IGNORE] = aiFactorIgnore;
     else
         aiResolveFactor[AI_FACTOR_IGNORE] = 0;
     if((time >= aiNoWayDown || aiNoWayDown < 0) && (time <= aiNoWayUp || aiNoWayUp < 0))
         aiResolveFactor[AI_FACTOR_NOWAY] = aiFactorNoWay;
     else
         aiResolveFactor[AI_FACTOR_NOWAY] = 0;
 #ifdef SAVE_AI_STATUS
     if(p->Status & SOBJ_ACTIVE) SaveAiStaus("InitFactor",this,time);
 #endif
     if(aiAlarmTime){
         aiResolveFactor[AI_FACTOR_RUN] += aiAlarmRun;
         aiResolveFactor[AI_FACTOR_ATTACK] += aiAlarmAttack;
     };
 #ifdef SAVE_AI_STATUS
     if(p->Status & SOBJ_ACTIVE) SaveAiStaus("AlarmFactor",this,time);
 #endif
     if((PointStatus & TRK_BRANCH_MASK) && (p->PointStatus & TRK_BRANCH_MASK) && pBranch == p->pBranch){
         if(MoveDir){
             if(pNextLink < p->pNextLink){
                 d1 = 1;
                 d2 = 0;
             }else{
                 d1 = 0;
                 d2 = 1;
             };
         }else{
             if(pNextLink > p->pNextLink){
                 d1 = 1;
                 d2 = 0;
             }else{
                 d1 = 0;
                 d2 = 1;
             };
         };
     }else{
         dx = getDistX(R_curr.x,vPoint.x);
         dy = getDistY(R_curr.y,vPoint.y);
         d1 = dx*dx + dy*dy;
         dx = getDistX(p->R_curr.x,vPoint.x);
         dy = getDistY(p->R_curr.y,vPoint.y);
         d2 = dx*dx + dy* dy;
     };
     a = rPI(Angle - p->Angle);
     if(a > PI) a -= 2*PI;
     if(d1 < d2){
         if(a > abs(PI / 2)){
             aiResolveFactor[AI_FACTOR_RUN] += aiFrontOverRun;
             aiResolveFactor[AI_FACTOR_ATTACK] += aiFrontOverAttack;
             aiResolveFactor[AI_FACTOR_IGNORE] += aiFrontOverIgnore;
             aiResolveFactor[AI_FACTOR_NOWAY] += aiFrontOverNoWay;
         }else{
             aiResolveFactor[AI_FACTOR_RUN] += aiFrontUnderRun;
             aiResolveFactor[AI_FACTOR_ATTACK] += aiFrontUnderAttack;
             aiResolveFactor[AI_FACTOR_IGNORE] += aiFrontUnderIgnore;
             aiResolveFactor[AI_FACTOR_NOWAY] += aiFrontUnderNoWay;
         };
     }else{
         if(a > abs(PI / 2)){
             aiResolveFactor[AI_FACTOR_RUN] += aiBackOverRun;
             aiResolveFactor[AI_FACTOR_ATTACK] += aiBackOverAttack;
             aiResolveFactor[AI_FACTOR_IGNORE] += aiBackOverIgnore;
             aiResolveFactor[AI_FACTOR_NOWAY] += aiBackOverNoWay;
         }else{
             aiResolveFactor[AI_FACTOR_RUN] += aiBackUnderRun;
             aiResolveFactor[AI_FACTOR_ATTACK] += aiBackUnderAttack;
             aiResolveFactor[AI_FACTOR_IGNORE] += aiBackUnderIgnore;
             aiResolveFactor[AI_FACTOR_NOWAY] += aiBackUnderNoWay;
         };
     };
     if(NoWayDirect != -1) aiResolveFactor[AI_FACTOR_NOWAY] = -100.0;
 #ifdef SAVE_AI_STATUS
     if(p->Status & SOBJ_ACTIVE) SaveAiStaus("NoWayFactor",this,time);
 #endif
     if(LowAmmo){
         aiResolveFactor[AI_FACTOR_RUN] += aiAmmoRun;
         aiResolveFactor[AI_FACTOR_ATTACK] += aiAmmoAttack;
     };
     if(LowArmor){
         aiResolveFactor[AI_FACTOR_RUN] += aiArmorRun;
         aiResolveFactor[AI_FACTOR_ATTACK] += aiArmorAttack;
     };
 #ifdef SAVE_AI_STATUS
     if(p->Status & SOBJ_ACTIVE) SaveAiStaus("LowFactor",this,time);
 #endif
     if(aiEvent.Num > 0) aiResolveFactor[AI_FACTOR_ATTACK] += aiMultyAttack*(aiEvent.Num - 1);
     if(aiResolveAttack.Num > 0) aiResolveFactor[AI_FACTOR_ATTACK] += aiTargetAttack*(aiResolveAttack.Num - 1);
     if(aiResolveFind.Num > 0) aiResolveFactor[AI_FACTOR_ATTACK] += aiTargetFind*(aiResolveFind.Num - 1);
 #ifdef SAVE_AI_STATUS
     if(p->Status & SOBJ_ACTIVE) SaveAiStaus("MultyFactor",this,time);
 #endif
     dl = (uvsDolly*)(DollyTail);
     while(dl){
         if(dl->biosNindex == aiModifier && dl->Pworld->gIndex == CurrentWorld){
             dx = getDistX(R_curr.x,dl->pos_x);
             dy = getDistY(R_curr.y,dl->pos_y);
             dd = (float)(dx*dx + dy*dy);
             if(dd < AI_MAX_DOLLY_FACTOR){
                 if(uvsPoint->CurrentDolly() == dl ->gIndex) aiResolveFactor[AI_FACTOR_RUN] += dd*aiDollyRun / AI_MAX_DOLLY_FACTOR;
                 else aiResolveFactor[AI_FACTOR_ATTACK] += dd*aiDollyAttack / AI_MAX_DOLLY_FACTOR;
             };
         };
         dl = (uvsDolly*)(dl->next);
     };
 //  if(aiActionID == AI_ACTION_FARMER && SeedNum >= MaxSeed)
 //      aiResolveFactor[AI_FACTOR_ATTACK] = -100;
     if(p->VangerRaceStatus != VANGER_RACE_NONE && (p->Status & SOBJ_ACTIVE)){
         aiResolveFactor[AI_FACTOR_ATTACK] += aiRacerAttack;
         if(CurrentWorld == WORLD_NECROSS && ActD.BigZek && p == ActD.BigZek->Owner)
             time = aiFindLevel;
     };
     if((p->Status & SOBJ_AUTOMAT)){
         if(RND(300) < 250){
             if(p->Visibility == VISIBLE){
                 if(aiResolveFactor[AI_FACTOR_ATTACK] > 0) aiResolveFactor[AI_FACTOR_ATTACK] *= .5;
             }else{
                 if(aiResolveFactor[AI_FACTOR_RUN] > 0) aiResolveFactor[AI_FACTOR_RUN] *= .5;
                 if(aiResolveFactor[AI_FACTOR_ATTACK] > 0) aiResolveFactor[AI_FACTOR_ATTACK] *= .25;
             };
             if(aiResolveFactor[AI_FACTOR_NOWAY] > 0) aiResolveFactor[AI_FACTOR_NOWAY] *= .5;
         };
     }else{
         aiResolveFactor[AI_FACTOR_ATTACK] += aiDominanceAttack*(float)(aiCutDominance) / (float)(100.0);
         aiResolveFactor[AI_FACTOR_RUN] += aiDominanceRun*(float)(aiCutDominance) / (float)(100.0);
     };
 #ifdef SAVE_AI_STATUS
     if(p->Status & SOBJ_ACTIVE) SaveAiStaus("DominanceFactor",this,time);
 #endif
     if(!(Status & SOBJ_ACTIVE) && (p->Status & SOBJ_ACTIVE))
         aiResolveFactor[AI_FACTOR_ATTACK] += aiFuryLevel*(float)(GlobalFuryLevel);
 #ifdef SAVE_AI_STATUS
     if(p->Status & SOBJ_ACTIVE) SaveAiStaus("FuryFactor",this,time);
 #endif
     dd = aiResolveFactor[0];
     d = 0;
     for(i = 1;i < MAX_AI_FACTOR;i++){
         if(aiResolveFactor[i] > dd){
             d = i;
             dd = aiResolveFactor[i];
         };
     };
     switch(d){
         case AI_FACTOR_ATTACK:
             if(!AddAttackTime){
                 if(time >= aiFindLevel)
                     AddFindResolve(UNIT_ORDER_VANGER,UnitOrderType(p),round((float)(time)*aiAttackTime) + 10,AI_RESOLVE_STATUS_VAR)->Time = MaxWayCount;
                 aiResolveAttack.AddResolve(UNIT_ORDER_VANGER,UnitOrderType(p),round((float)(time)*aiAttackTime) + 10,AI_RESOLVE_STATUS_VAR)->Time = MaxWayCount;
                 AddAttackTime = round((float)(time)*aiAttackTime);
             };
             break;
         case AI_FACTOR_RUN:
             if(NoWayEnable == AI_NO_WAY_NONE && !(OtherFlag & MECHOS_CALC_WAY)){
                 if(!LowArmor){
                     aiResolveFind.ClearResolve();
                     if(Status & SOBJ_ACTIVE) GamerOrderInit();
                     else MainOrderInit();
                 };
                 CalcImpulse();
             };
             break;
         case AI_FACTOR_NOWAY:
             if(!(OtherFlag & MECHOS_CALC_WAY))
                 NoWayInit();
             break;
     };
 };
References ActD, AddAttackTime, AddFindResolve(), aiResolveList::AddResolve(), AI_FACTOR_ATTACK, AI_FACTOR_IGNORE, AI_FACTOR_NOWAY, AI_FACTOR_RUN, AI_MAX_DOLLY_FACTOR, AI_NO_WAY_NONE, AI_RESOLVE_STATUS_VAR, aiFactorType::aiAlarmAttack, aiFactorType::aiAlarmRun, aiAlarmTime, aiFactorType::aiAmmoAttack, aiFactorType::aiAmmoRun, aiFactorType::aiArmorAttack, aiFactorType::aiArmorRun, aiFactorType::aiAttackDown, aiFactorType::aiAttackTime, aiFactorType::aiAttackUp, aiFactorType::aiBackOverAttack, aiFactorType::aiBackOverIgnore, aiFactorType::aiBackOverNoWay, aiFactorType::aiBackOverRun, aiFactorType::aiBackUnderAttack, aiFactorType::aiBackUnderIgnore, aiFactorType::aiBackUnderNoWay, aiFactorType::aiBackUnderRun, aiCutDominance, aiFactorType::aiDollyAttack, aiFactorType::aiDollyRun, aiFactorType::aiDominanceAttack, aiFactorType::aiDominanceRun, aiEvent, aiFactorType::aiFactorAttack, aiFactorType::aiFactorIgnore, aiFactorType::aiFactorNoWay, aiFactorType::aiFactorRun, aiFactorType::aiFindLevel, aiFactorType::aiFrontOverAttack, aiFactorType::aiFrontOverIgnore, aiFactorType::aiFrontOverNoWay, aiFactorType::aiFrontOverRun, aiFactorType::aiFrontUnderAttack, aiFactorType::aiFrontUnderIgnore, aiFactorType::aiFrontUnderNoWay, aiFactorType::aiFrontUnderRun, aiFactorType::aiFuryLevel, aiFactorType::aiIgnoreDown, aiFactorType::aiIgnoreUp, aiModifier, aiFactorType::aiMultyAttack, aiFactorType::aiNoWayDown, aiFactorType::aiNoWayUp, aiFactorType::aiRacerAttack, aiResolveAttack, aiResolveFactor, aiResolveFind, aiFactorType::aiRunDown, aiFactorType::aiRunUp, aiFactorType::aiTargetAttack, aiFactorType::aiTargetFind, ActionUnit::Angle, ActionDispatcher::BigZek, uvsDolly::biosNindex, CalcImpulse(), aiResolveList::ClearResolve(), uvsVanger::CurrentDolly(), CurrentWorld, DollyTail, GamerOrderInit(), getDistX(), getDistY(), uvsWorld::gIndex, uvsDolly::gIndex, GlobalFuryLevel, LowAmmo, LowArmor, MainOrderInit(), MAX_AI_FACTOR, TrackUnit::MaxWayCount, MECHOS_CALC_WAY, TrackUnit::MoveDir, listElem::next, TrackUnit::NoWayDirect, NoWayEnable, NoWayInit(), aiListType::Num, ActionUnit::OtherFlag, StuffObject::Owner, TrackLinkType::pBranch, PI, TrackLinkType::pNextLink, TrackLinkType::PointStatus, uvsTarget::pos_x, uvsTarget::pos_y, uvsDolly::Pworld, RND(), round(), rPI, SOBJ_ACTIVE, SOBJ_AUTOMAT, Object::time, aiUnitResolve::Time, TRK_BRANCH_MASK, UNIT_ORDER_VANGER, uvsKernel::uvsPoint, VANGER_RACE_NONE, VangerRaceStatus, VISIBLE, TrackLinkType::vPoint, WORLD_NECROSS, Object::x, Vector::x, Object::y, and Vector::y.
Referenced by ResolveGenerator().
CalcForce()
void VangerUnit::CalcForce (void)
 {
     Vector vCheck;
     int t;
     GetForceWay(aiMaxJumpRadius * aiMaxJumpRadius / 4,vCheck);
     if(vCheck.x != 0 || vCheck.y != 0){
         TargetPoint.vPoint = vCheck;
         HideTrack.GetPosition(&TargetPoint);
         aiMoveMode = AI_MOVE_POINT;
         aiResolveWayEnable = 2;
         NoWayEnable = AI_NO_WAY_PROCESS;
         aiRunBranch = pBranch;
         aiRunNode = pNode;
         vRunStartPosition = R_curr;
         t = getDistX(R_curr.x,TargetPoint.vPoint.x);
         RunStartDist = t*t;
         t = getDistY(R_curr.y,TargetPoint.vPoint.y);
         RunStartDist += t*t;
         RunTimeProcess = 4*aiRelaxTimeMax;
     }else{
         if(CheckNearTrack()){
             TargetPoint.vPoint = aiNearTrack;
             HideTrack.GetPosition(&TargetPoint);
             aiMoveMode = AI_MOVE_POINT;
             aiResolveWayEnable = 2;
             NoWayEnable = AI_NO_WAY_PROCESS;
             aiRunBranch = pBranch;
             aiRunNode = pNode;
             vRunStartPosition = R_curr;
             t = getDistX(R_curr.x,TargetPoint.vPoint.x);
             RunStartDist = t*t;
             t = getDistY(R_curr.y,TargetPoint.vPoint.y);
             RunStartDist += t*t;
             RunTimeProcess = 4*aiRelaxTimeMax;
         };
     };
 };
References AI_MOVE_POINT, AI_NO_WAY_PROCESS, aiMaxJumpRadius, TrackUnit::aiMoveMode, aiNearTrack, aiRelaxTimeMax, aiResolveWayEnable, aiRunBranch, aiRunNode, CheckNearTrack(), getDistX(), getDistY(), GetForceWay(), TrackType::GetPosition(), HideTrack, NoWayEnable, TrackLinkType::pBranch, TrackLinkType::pNode, RunStartDist, RunTimeProcess, TrackUnit::TargetPoint, TrackLinkType::vPoint, vRunStartPosition, Vector::x, and Vector::y.
Referenced by Action().
CalcImpulse()
void VangerUnit::CalcImpulse (void)
 {
     Vector vCheck;
     int t;
     SpeedFactorTime += 2;
     if(CheckNearTrack()){
         TargetPoint.vPoint = aiNearTrack;
         HideTrack.GetPosition(&TargetPoint);
         aiMoveMode = AI_MOVE_POINT;
         aiResolveWayEnable = 2;
         NoWayEnable = AI_NO_WAY_PROCESS;
         aiRunBranch = pBranch;
         aiRunNode = pNode;
         vRunStartPosition = R_curr;
         t = getDistX(R_curr.x,TargetPoint.vPoint.x);
         RunStartDist = t*t;
         t = getDistY(R_curr.y,TargetPoint.vPoint.y);
         RunStartDist += t*t;
         RunTimeProcess = 4*aiRelaxTimeMax;
     }else{
         GetForceWay(aiMaxJumpRadius * aiMaxJumpRadius / 4,vCheck);
         if(vCheck.x != 0 || vCheck.y != 0){
             TargetPoint.vPoint = vCheck;
             HideTrack.GetPosition(&TargetPoint);
             aiMoveMode = AI_MOVE_POINT;
             aiResolveWayEnable = 2;
             NoWayEnable = AI_NO_WAY_PROCESS;
             aiRunBranch = pBranch;
             aiRunNode = pNode;
             vRunStartPosition = R_curr;
             t = getDistX(R_curr.x,TargetPoint.vPoint.x);
             RunStartDist = t*t;
             t = getDistY(R_curr.y,TargetPoint.vPoint.y);
             RunStartDist += t*t;
             RunTimeProcess = 4*aiRelaxTimeMax;
         };
     };
 };
References AI_MOVE_POINT, AI_NO_WAY_PROCESS, aiMaxJumpRadius, TrackUnit::aiMoveMode, aiNearTrack, aiRelaxTimeMax, aiResolveWayEnable, aiRunBranch, aiRunNode, CheckNearTrack(), getDistX(), getDistY(), GetForceWay(), TrackType::GetPosition(), HideTrack, NoWayEnable, TrackLinkType::pBranch, TrackLinkType::pNode, RunStartDist, RunTimeProcess, SpeedFactorTime, TrackUnit::TargetPoint, TrackLinkType::vPoint, vRunStartPosition, Vector::x, and Vector::y.
Referenced by Action(), and CalcAiFactor().
CalcWeaponDelta()
void VangerUnit::CalcWeaponDelta (void)
ChangeVangerProcess()
void VangerUnit::ChangeVangerProcess (void)
!!!
!!!!!!!!
!!!!!!!
!!!!!!!!
 {
     uvsMechosType* sc;
     int i;
     StuffObject* p;
     StuffObject* pp;
     if(NetworkON && (Status & SOBJ_ACTIVE)){
         aciDropMoveItem();
         p = DeviceData;
         while(p){
             pp = p->NextDeviceList;
             if(p->ActIntBuffer.type == ACI_MECHOSCOPE)
                 p->ActIntBuffer.data1 = 0;
             ObjectDestroy(p);
             CheckOutDevice(p);
             if(Status & SOBJ_ACTIVE){
                 ActD.CheckDevice(p);
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             p->Storage->Deactive(p);
             DelDevice(p);
             p = pp;
         };
     };
     for(i = 0;i < ItemMatrix->NumSlot;i++)
         GunSlotData[ItemMatrix->nSlot[i]].CloseSlot();
     aiEvent.Free();
     aiResolveFind.Free();
     aiResolveAttack.Free();
     delete ItemMatrixData;
     if(!NetworkON){
         uvsPoint->Pmechos->type = MechosChangerType;
         uvsPoint->Pmechos->color = VangerChangerColor;
     }else{
         if(Status & SOBJ_ACTIVE){
             uvsPoint->Pmechos->type = MechosChangerType;
             uvsPoint->Pmechos->color = my_player_body.color;
         }else{
             uvsPoint->Pmechos->type = pNetPlayer->body.CarIndex;
             uvsPoint->Pmechos->color = pNetPlayer->body.color;
         };
     };
     sc = uvsMechosTable[uvsPoint->Pmechos->type];
     uvsMaxSpeed = sc->MaxSpeed;
     MaxArmor = sc->MaxArmor << 16;
     MaxEnergy = sc->MaxEnergy << 16;
     dEnergy = ((MaxEnergy / 10) * sc->DeltaEnergy) / (UnitGlobalTime * 100);
     DropEnergy = MaxEnergy * sc->DropEnergy / 100;
     DelayDrop = sc->DropTime;
     ImpulsePower = (MaxEnergy / 100) * sc->MaxFly;
     OxigenResource = MaxOxigenResource = sc->MaxOxigen;
     PowerFlag = sc->MaxFire;
     aiPowerFlag = VANGER_POWER_NONE;
     MaxPassageCount = sc->MaxTeleport;
     DestroyClass = sc->MaxDamage;
     PassageCount = 0;
     uvsPoint->Pmechos->teleport &= ~0xff;
     uvsPoint->Pmechos->teleport |= PassageCount;
     if(!NetworkON || (Status & SOBJ_ACTIVE)){
         Energy = VangerChangerEnergy;
         Armor = VangerChangerArmor;
     };
     switch(uvsPoint->Pmechos->type){
         case 0:
         case 1:
         case 2:
         case 3:
         case 4:
         case 5:
         case 6:
         case 7:
         case 8:
         case 9:
         case 10:
         case 11:
         case 12:
         case 13:
             ItemMatrix = &UnitMatrixData[UNIT_SUB_MATRIX_NUM + uvsPoint->Pmechos->type];
             break;
         case 14:
         case 15:
         case 16:
         case 17:
         case 18:
             ItemMatrix = &UnitMatrixData[23];
             break;
         case 19://Sandoll
             ItemMatrix = &UnitMatrixData[25];
             break;
         case 20://BTR
             ItemMatrix = &UnitMatrixData[26];
             break;
         case 21://Amphyb
             ItemMatrix = &UnitMatrixData[24];
             break;
         case 22://Helicopt
             ItemMatrix = &UnitMatrixData[27];
             break;
         case 23://Worm
             ItemMatrix = &UnitMatrixData[28];
             break;
     };
     if(Status & SOBJ_ACTIVE){
         aciNewMechos(uvsMechosType_to_AciInt(uvsPoint->Pmechos->type));
         aciSetRedraw();
     };
     if(!NetworkON || (Status & SOBJ_ACTIVE)){
         R_curr = vChangerPosition;
         Angle = VangerChangerAngle;
     };
     nModel = ModelD.FindModel(uvsMechosTable[uvsPoint->Pmechos->type]->name);
     Object::operator = (ModelD.ActiveModel(nModel));
     if(Status & SOBJ_ACTIVE) set_active(1);
     else set_active(0);
     cycleTor(R_curr.x,R_curr.y);
     set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,-Angle,0);
     ActionUnit::InitEnvironment();
     MovMat = RotMat = DBM(Angle,Z_AXIS);
     vUp = Vector(ymax_real,0,0)*MovMat;
     vDown = -vUp;
     vDirect =  Vector(0,0,0);
     WayDist = WayDistData;
     CalcWayDist = WayDistData + HideTrack.NumNode;
     memset(WayDistData,0,sizeof(int)*HideTrack.NumNode*2);
     TargetAngle = TargetLen = 0;
     EnvirReaction = 128;
     TargetReaction = TOTAL_REACTION - EnvirReaction;
     MoveDir = 1;
     PointStatus = TRK_IN_BRANCH;
     pNextLink = NULL;
     pBranch = NULL;
     HideTrack.GetFirstPosition(R_curr.x,R_curr.y,pNextLink,pBranch);
     if(pNextLink == pBranch->Link){
         pPrevLink = pNextLink;
         pNextLink++;
     }else pPrevLink = pNextLink - 1;
     if(pBranch->pBeg) pNode = pBranch->pBeg;
     else pNode = pBranch->pEnd;
     FrontDir = -1;
     FrontPoint.PointStatus = TRK_IN_BRANCH;
     FrontPoint.pNextLink = pNextLink;
     FrontPoint.pPrevLink = pPrevLink;
     FrontPoint.pBranch = pBranch;
     FrontPoint.pNode = pNode;
     PrevBranch = pBranch;
     OtherFlag = MECHOS_RECALC_FRONT | MECHOS_TARGET_MOVE;
     CheckWayCount = MaxWayCount = 50;
     CheckPosition = MaxCheckPosition = 15;
     vTarget = Vector(0,0,0);
     for(i =0;i < n_wheels;i++){
         PrevWheelX[i] = 0;
         PrevWheelY[i] = 0;
         PrevWheelFlag[i] = 0;
     };
     NullTime = 0;
     vEnvir = Vector(0,0,0);
     vDirect = Vector(0,0,0);
     aiMoveMode = AI_MOVE_TRACK;
     aiMoveFunction = AI_MOVE_FUNCTION_WHEEL;
     gRnd = 0xFFFFFFFF;
     ShellUpdateFlag = 1;
     switch(uvsPoint->Pmechos->color){
         case 0:
             set_body_color(COLORS_IDS::BODY_GREEN);
             aiModifier = AI_MODIFIER_ELEEPOD;
             break;
         case 1:
             set_body_color(COLORS_IDS::BODY_RED);
             aiModifier = AI_MODIFIER_BEEBOORAT;
             break;
         case 2:
             set_body_color(COLORS_IDS::BODY_BLUE);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 3:
             set_body_color(COLORS_IDS::BODY_YELLOW);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 4:
             set_body_color(COLORS_IDS::BODY_CRIMSON);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 5:
             set_body_color(COLORS_IDS::BODY_GRAY);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 6:
             set_body_color(COLORS_IDS::ROTTEN_ITEM);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 7:
             set_body_color(COLORS_IDS::MATERIAL_3);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 8:
             set_body_color(COLORS_IDS::MATERIAL_1);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 9:
             set_body_color(COLORS_IDS::MATERIAL_0);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
     };
     DoorFlag = 0;
     ExternalMode = EXTERNAL_MODE_NORMAL;
     ExternalTime = 0;
     ExternalLock = 0;
     ExternalDraw = 1;
     ExternalObject = ExternalLastSensor = ExternalSensor = NULL;
     ExternalTime2 = 0;
     ExternalAngle = 0;
     ItemMatrixData = new int[ItemMatrix->FullNum];
     for(i = 0;i < ItemMatrix->FullNum;i++) ItemMatrixData[i] = 0;
     for(i = 0;i < MAX_ACTIVE_SLOT;i++){
         GunSlotData[i].pData = NULL;
         GunSlotData[i].Owner = NULL;
     };
     for(i = 0;i < ItemMatrix->NumSlot;i++)
         GunSlotData[ItemMatrix->nSlot[i]].OpenSlot(ItemMatrix->nSlot[i],this,ItemMatrix->nSlot[i]);
     aiEvent.Init();
     aiResolveFind.Init();
     aiResolveAttack.Init();
     if(NetworkON){
         if(Status & SOBJ_ACTIVE){
             aciPrepareMenus();
             InCarNator();
             my_player_body.CarIndex = uvsPoint->Pmechos->type;
             send_player_body(my_player_body);
         };
     }else{
         if(Status & SOBJ_ACTIVE) aciPrepareMenus();
         InCarNator();
     };
     TouchKeyObject = NULL;
     TouchKeyObjectFlag = 1;
     CoptePoint = NULL;
     SwimPoint = NULL;
     MolePoint = NULL;
     if(Status & SOBJ_ACTIVE){
         aciUpdateCurCredits(aiGetHotBug());
 //      aciCurCredits = ActD.HotBug;
         aciMaxEnergy = (MaxEnergy >> 16) + 1;
         aciMaxArmor = (MaxArmor >> 16) + 1;
         aciCurEnergy = Energy >> 16;
         aciCurArmor = Armor >> 16;
         aciCurJumpCount = PassageCount;
         aciMaxJumpCount = MaxPassageCount + 1;
     };
     InitAI();
     RuffaGunTime = 0;
     SensorEnable = 0;
     VangerRaceStatus = VANGER_RACE_NONE;
     PlayerDestroyFlag = 0;
     NetworkArmor = Armor;
     NetworkEnergy = Energy;
     NetRuffaGunTime = 0;
     PrevImpuseFrame = 0;
 };
References ACI_MECHOSCOPE, aciCurArmor, aciCurEnergy, aciCurJumpCount, aciDropMoveItem(), aciMaxArmor, aciMaxEnergy, aciMaxJumpCount, aciNewMechos(), aciPrepareMenus(), aciRemoveItem(), aciSetRedraw(), aciUpdateCurCredits(), ActD, StuffObject::ActIntBuffer, ModelDispatcher::ActiveModel(), AI_MODIFIER_BEEBOORAT, AI_MODIFIER_ELEEPOD, AI_MODIFIER_ZEEX, AI_MOVE_FUNCTION_WHEEL, AI_MOVE_TRACK, aiEvent, aiGetHotBug(), aiModifier, TrackUnit::aiMoveFunction, TrackUnit::aiMoveMode, uvsUnitType::aiPowerFlag, aiResolveAttack, aiResolveFind, ActionUnit::Angle, uvsUnitType::Armor, PlayerData::body, COLORS_IDS::BODY_BLUE, COLORS_IDS::BODY_CRIMSON, COLORS_IDS::BODY_GRAY, COLORS_IDS::BODY_GREEN, COLORS_IDS::BODY_RED, COLORS_IDS::BODY_YELLOW, TrackUnit::CalcWayDist, PlayerBody::CarIndex, ActionDispatcher::CheckDevice(), CheckOutDevice(), TrackUnit::CheckPosition, TrackUnit::CheckWayCount, GunSlot::CloseSlot(), PlayerBody::color, uvsMechos::color, CoptePoint, cycleTor(), actintItemData::data1, StuffObject::Deactive(), uvsUnitType::DelayDrop, uvsUnitType::DelDevice(), uvsMechosType::DeltaEnergy, uvsUnitType::dEnergy, uvsUnitType::DestroyClass, uvsUnitType::DeviceData, DoorFlag, uvsUnitType::DropEnergy, uvsMechosType::DropEnergy, uvsMechosType::DropTime, uvsUnitType::Energy, TrackUnit::EnvirReaction, EXTERNAL_MODE_NORMAL, ExternalAngle, ExternalDraw, ExternalLastSensor, ExternalLock, ExternalMode, ExternalObject, ExternalSensor, ExternalTime, ExternalTime2, ModelDispatcher::FindModel(), aiListType::Free(), TrackUnit::FrontDir, TrackUnit::FrontPoint, UnitItemMatrix::FullNum, TrackType::GetFirstPosition(), TrackUnit::gRnd, GunSlotData, HideTrack, uvsUnitType::ImpulsePower, InCarNator(), aiListType::Init(), InitAI(), ActionUnit::InitEnvironment(), uvsUnitType::ItemMatrix, uvsUnitType::ItemMatrixData, BranchType::Link, COLORS_IDS::MATERIAL_0, COLORS_IDS::MATERIAL_1, COLORS_IDS::MATERIAL_3, MAX_ACTIVE_SLOT, uvsUnitType::MaxArmor, uvsMechosType::MaxArmor, TrackUnit::MaxCheckPosition, uvsMechosType::MaxDamage, uvsUnitType::MaxEnergy, uvsMechosType::MaxEnergy, uvsMechosType::MaxFire, uvsMechosType::MaxFly, uvsMechosType::MaxOxigen, uvsUnitType::MaxOxigenResource, uvsUnitType::MaxPassageCount, uvsMechosType::MaxSpeed, uvsMechosType::MaxTeleport, TrackUnit::MaxWayCount, MECHOS_RECALC_FRONT, MECHOS_TARGET_MOVE, MechosChangerType, ModelD, MolePoint, TrackUnit::MoveDir, ActionUnit::MovMat, my_player_body, Object::n_wheels, uvsMechosType::name, NetRuffaGunTime, NetworkArmor, NetworkEnergy, NetworkON, StuffObject::NextDeviceList, ActionUnit::nModel, UnitItemMatrix::nSlot, NULL, TrackUnit::NullTime, TrackType::NumNode, UnitItemMatrix::NumSlot, ObjectDestroy(), GunSlot::OpenSlot(), Object::operator=(), ActionUnit::OtherFlag, GunSlot::Owner, uvsUnitType::OxigenResource, uvsUnitType::PassageCount, BranchType::pBeg, TrackLinkType::pBranch, GunSlot::pData, BranchType::pEnd, PlayerDestroyFlag, uvsVanger::Pmechos, pNetPlayer, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, uvsUnitType::PowerFlag, TrackLinkType::pPrevLink, TrackUnit::PrevBranch, PrevImpuseFrame, TrackUnit::PrevWheelFlag, TrackUnit::PrevWheelX, TrackUnit::PrevWheelY, ActionUnit::RotMat, COLORS_IDS::ROTTEN_ITEM, RuffaGunTime, send_player_body(), SensorEnable, Object::set_3D(), SET_3D_DIRECT_PLACE, Object::set_active(), Object::set_body_color(), ShellUpdateFlag, SOBJ_ACTIVE, SwimPoint, TrackUnit::TargetAngle, TrackUnit::TargetLen, TrackUnit::TargetReaction, uvsMechos::teleport, TOTAL_REACTION, TouchKeyObject, TouchKeyObjectFlag, TRK_IN_BRANCH, actintItemData::type, uvsMechos::type, UNIT_SUB_MATRIX_NUM, UnitGlobalTime, UnitMatrixData, uvsUnitType::uvsMaxSpeed, uvsMechosTable, uvsMechosType_to_AciInt(), uvsKernel::uvsPoint, VANGER_POWER_NONE, VANGER_RACE_NONE, VangerChangerAngle, VangerChangerArmor, VangerChangerColor, VangerChangerEnergy, VangerRaceStatus, vChangerPosition, ActionUnit::vDirect, ActionUnit::vDown, ActionUnit::vEnvir, TrackUnit::vTarget, ActionUnit::vUp, TrackUnit::WayDist, TrackUnit::WayDistData, Object::ymax_real, and Z_AXIS.
Referenced by InitEnvironment().
CheckAmmo()
void VangerUnit::CheckAmmo (void)
 {
     int i;
     int s1,s2;
     s2 = s1 = 0;
     for(i = 0;i < ItemMatrix->NumSlot;i++){
         if(GunSlotData[ItemMatrix->nSlot[i]].pData){
             if(!GunSlotData[ItemMatrix->nSlot[i]].ItemData->ActIntBuffer.data1)
                 s1++;
             s2++;
         };
     };
     if(s1 == s2)
         LowAmmo = 1;
 };
References StuffObject::ActIntBuffer, actintItemData::data1, GunSlotData, GunSlot::ItemData, uvsUnitType::ItemMatrix, LowAmmo, UnitItemMatrix::nSlot, UnitItemMatrix::NumSlot, and GunSlot::pData.
Referenced by ResolveGenerator().
CheckFind()
void VangerUnit::CheckFind (aiUnitResolve * p, Vector v)
 {
     int dx,dy;
     if(p->rStatus & AI_RESOLVE_STATUS_TARGET){
         dy = abs(getDistY(v.y,R_curr.y));
         if(dy < radius * 4){
             dx = abs(getDistX(v.x,R_curr.x));
             if(dx < radius*4) ResolveFindDestroy(p);
         };
     }else{
         if(p->rStatus & AI_RESOLVE_STATUS_VIEW){
             dy = abs(getDistY(v.y,R_curr.y));
             if(dy < ViewRadius){
                 dx = abs(getDistX(v.x,R_curr.x));
                 if(dx < ViewRadius) ResolveFindDestroy(p);
             };
         };
     };
 };
References AI_RESOLVE_STATUS_TARGET, AI_RESOLVE_STATUS_VIEW, getDistX(), getDistY(), Object::radius, ResolveFindDestroy(), aiUnitResolve::rStatus, ActionUnit::ViewRadius, Vector::x, and Vector::y.
Referenced by ResolveHandlerFind().
CheckInDevice()
char VangerUnit::CheckInDevice (StuffObject * p) virtual
Reimplemented from uvsUnitType.
 {
     StuffObject* n;
     int id;
     aiUnitResolve* l;
     if(p->uvsDeviceType == UVS_ITEM_TYPE::PROTRACTOR && ActD.ThreallDestroy)
         return CHECK_DEVICE_OUT;
     if(p->uvsDeviceType == UVS_ITEM_TYPE::KERNOBOO || p->uvsDeviceType == UVS_ITEM_TYPE::PIPETKA){
         id = p->uvsDeviceType;
         n = DeviceData;
         while(n){
             if(n->uvsDeviceType == id && n->ActIntBuffer.data1 < MAX_SEED_QUANT){
 //              n->ActIntBuffer.data1++;
                 return CHECK_DEVICE_ADD;
             };
             n = n->NextDeviceList;
         };
     };
     if(Armor <= 0 || Energy <= DropEnergy) return CHECK_DEVICE_OUT;
     if(!(Status & SOBJ_ACTIVE)){
         l = aiResolveFind.FindResolve(UNIT_ORDER_STUFF,UnitOrderType(p));
         if(l){
             ResolveFindDestroy(l);
             return CHECK_DEVICE_IN;
         }else{
             if(p->ActIntBuffer.type == ACI_DEGRADATOR || p->ActIntBuffer.type == ACI_AMPUTATOR || p->ActIntBuffer.type == ACI_MECHOSCOPE) return CHECK_DEVICE_IN;
             return CHECK_DEVICE_OUT;
         };
     };
     if(aciCheckItemPickUp(&(p->ActIntBuffer))){
         uvsDomChangeFromItem(p->uvsDeviceType, 1, 1);
         return CHECK_DEVICE_IN;
     };
     return CHECK_DEVICE_OUT;
 };
References ACI_AMPUTATOR, ACI_DEGRADATOR, ACI_MECHOSCOPE, aciCheckItemPickUp(), ActD, StuffObject::ActIntBuffer, aiResolveFind, uvsUnitType::Armor, CHECK_DEVICE_ADD, CHECK_DEVICE_IN, CHECK_DEVICE_OUT, actintItemData::data1, uvsUnitType::DeviceData, uvsUnitType::DropEnergy, uvsUnitType::Energy, aiResolveList::FindResolve(), UVS_ITEM_TYPE::KERNOBOO, MAX_SEED_QUANT, StuffObject::NextDeviceList, UVS_ITEM_TYPE::PIPETKA, UVS_ITEM_TYPE::PROTRACTOR, ResolveFindDestroy(), SOBJ_ACTIVE, ActionDispatcher::ThreallDestroy, actintItemData::type, UNIT_ORDER_STUFF, StuffObject::uvsDeviceType, and uvsDomChangeFromItem().
Referenced by ItemsDispatcher::Quant().
CheckInMatrix()
int VangerUnit::CheckInMatrix (int sz)
 {
     int* p;
     p = ItemMatrixData;
     if(ItemMatrix->CheckSize(sz,p)){
         *p = sz + 1;
         return 1;
     };
     return 0;
 };
References UnitItemMatrix::CheckSize(), uvsUnitType::ItemMatrix, and uvsUnitType::ItemMatrixData.
CheckNearTrack()
int VangerUnit::CheckNearTrack (void)
 {
     int i,j;
     LinkType* ml;
     BranchType* mb;
     NodeType* nn;
     LinkType* cl;
     NodeType* cn;
     int cDist;
     int mDist,bDist,dx;
     aiNearTrack = Vector(0,0,0);
 //  if(!SpeedFactorTime)
 //      return 0;
     mb = HideTrack.branch;
     cDist = WayDist[pNode->index];
     bDist = 2*aiMaxJumpRadius;
     mDist = 0;
     cl = NULL;
     for(i = 0;i < HideTrack.NumBranch;i++,mb++){
         if((mb->pBeg && WayDist[mb->pBeg->index] < cDist) || (mb->pEnd && WayDist[mb->pEnd->index] < cDist)){
             ml = mb->Link;
             for(j = 0;j < mb->NumLink;j++){
                 dx = abs(getDistX(R_curr.x,ml->x)) + abs(R_curr.y - ml->y);
                 if(dx < bDist && dx > mDist){
                     mDist = dx;
                     cl = ml;
                 };
                 ml++;
             };
         };
     };
     nn = HideTrack.node;
     cn = NULL;
     for(i = 0;i < HideTrack.NumNode;i++,nn++){
         if(WayDist[nn->index] < cDist){
             dx = abs(getDistX(R_curr.x,nn->x)) + abs(R_curr.y - nn->y);
             if(dx < bDist && dx > mDist){
                 mDist = dx;
                 cn = nn;
             };
         };
     };
     if(cn){
         aiNearTrack = Vector(cn->x,cn->y,cn->z);
         return 1;
     }else{
         if(cl){
             aiNearTrack = Vector(cl->x,cl->y,cl->z);
             return 1;
         };
     };
     return 0;
 };
References aiMaxJumpRadius, aiNearTrack, TrackType::branch, getDistX(), HideTrack, NodeType::index, BranchType::Link, TrackType::node, NULL, TrackType::NumBranch, BranchType::NumLink, TrackType::NumNode, BranchType::pBeg, BranchType::pEnd, TrackLinkType::pNode, TrackUnit::WayDist, LinkType::x, NodeType::x, LinkType::y, NodeType::y, LinkType::z, and NodeType::z.
Referenced by CalcForce(), and CalcImpulse().
CheckOutDevice()
void VangerUnit::CheckOutDevice (StuffObject * p) virtual
Reimplemented from uvsUnitType.
 {
     int i;
     if(Status & SOBJ_ACTIVE)
         uvsDomChangeFromItem(p->uvsDeviceType, 0, 1);
     if(!(Status & SOBJ_ACTIVE)){
         for(i = 0;i < MAX_ACTIVE_SLOT;i++)
             if(GunSlotData[i].pData && GunSlotData[i].ItemData == p) GunSlotData[i].CloseGun();
     };
     StuffObject* n;
     switch(p->ActIntBuffer.type){
         case ACI_PHLEGMA:
             i = -1;
             n = DeviceData;
             while(n){
                 if(n->ActIntBuffer.type == ACI_PHLEGMA){
                     i++;
                     if(i == SAFE_STUFF_MAX) break;
                 };
                 n = n->NextDeviceList;
             };
             if(i < SAFE_STUFF_MAX){
                 n = DeviceData;
                 while(n){
                     if(n->ActIntBuffer.type == ACI_WEEZYK && !uvsCheckItemOnLive(UVS_ITEM_TYPE::WEEZYK)){
                         n->uvsDeviceType = UVS_ITEM_TYPE::DEAD_WEEZYK;
                         n->ActIntBuffer.type = uvsSetItemType(n->uvsDeviceType,n->ActIntBuffer.data0,n->ActIntBuffer.data1);
                         if(Status & SOBJ_ACTIVE){
                             aciChangeItem(&(n->ActIntBuffer));
                             uvsOnKillItem();
                         };
                     };
                     n = n->NextDeviceList;
                 };
             };
             break;
         case ACI_WEEZYK:
             if(!uvsCheckItemOnLive(UVS_ITEM_TYPE::WEEZYK)){
                 p->uvsDeviceType = UVS_ITEM_TYPE::DEAD_WEEZYK;
                 p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 if(Status & SOBJ_ACTIVE) uvsOnKillItem();
             };
             break;
         case ACI_TOXICK:
             i = -1;
             n = DeviceData;
             while(n){
                 if(n->ActIntBuffer.type == ACI_TOXICK){
                     i++;
                     if(i == SAFE_STUFF_MAX) break;
                 };
                 n = n->NextDeviceList;
             };
             if(i < SAFE_STUFF_MAX){
                 n = DeviceData;
                 while(n){
                     if(n->ActIntBuffer.type == ACI_ELEECH && !uvsCheckItemOnLive(UVS_ITEM_TYPE::ELEECH)){
                         n->uvsDeviceType = UVS_ITEM_TYPE::DEAD_ELEECH;
                         n->ActIntBuffer.type = uvsSetItemType(n->uvsDeviceType,n->ActIntBuffer.data0,n->ActIntBuffer.data1);
                         if(Status & SOBJ_ACTIVE){
                             aciChangeItem(&(n->ActIntBuffer));
                             uvsOnKillItem();
                         };
                     };
                     n = n->NextDeviceList;
                 };
             };
             break;
         case ACI_ELEECH:
             if(!uvsCheckItemOnLive(UVS_ITEM_TYPE::ELEECH)){
                 p->uvsDeviceType = UVS_ITEM_TYPE::DEAD_ELEECH;
                 p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 if(Status & SOBJ_ACTIVE) uvsOnKillItem();
             };
             break;
         case ACI_PROTRACTOR:
             ActD.ClearProtractor();
             break;
         case ACI_MECHANIC_MESSIAH:
             ActD.ClearMessiah();
             break;
         case ACI_PEELOT:
             if((Status & SOBJ_ACTIVE) && (Status & SOBJ_AUTOMAT)){
                 Status &=~SOBJ_AUTOMAT;
                 aiMessageQueue.Send(AI_MESSAGE_AUTOMATIC_OFF,0,0xff,0);
             };
             break;
     };
 };
References ACI_ELEECH, ACI_MECHANIC_MESSIAH, ACI_PEELOT, ACI_PHLEGMA, ACI_PROTRACTOR, ACI_TOXICK, ACI_WEEZYK, aciChangeItem(), ActD, StuffObject::ActIntBuffer, AI_MESSAGE_AUTOMATIC_OFF, aiMessageQueue, ActionDispatcher::ClearMessiah(), ActionDispatcher::ClearProtractor(), GunSlot::CloseGun(), actintItemData::data0, actintItemData::data1, UVS_ITEM_TYPE::DEAD_ELEECH, UVS_ITEM_TYPE::DEAD_WEEZYK, uvsUnitType::DeviceData, UVS_ITEM_TYPE::ELEECH, GunSlotData, MAX_ACTIVE_SLOT, StuffObject::NextDeviceList, SAFE_STUFF_MAX, aiMessageList::Send(), SOBJ_ACTIVE, SOBJ_AUTOMAT, actintItemData::type, uvsCheckItemOnLive(), StuffObject::uvsDeviceType, uvsDomChangeFromItem(), uvsOnKillItem(), uvsSetItemType(), and UVS_ITEM_TYPE::WEEZYK.
Referenced by ChangeVangerProcess(), DestroyItem(), DischargeItem(), Go2Universe(), Go2World(), ItemQuant(), StuffObject::NetEvent(), StuffObject::NetOwnerQuant(), NewKeyHandler(), OutCarNator(), GunSlot::Quant(), and uvsapiDestroyItem().
CheckOutMatrix()
int VangerUnit::CheckOutMatrix (int sz)
 {
     int* p;
     p = ItemMatrixData;
     if(ItemMatrix->GetSize(sz,p)){
         *p = 0;
         return 1;
     };
     return 0;
 };
References UnitItemMatrix::GetSize(), uvsUnitType::ItemMatrix, and uvsUnitType::ItemMatrixData.
CheckReturn2Track()
int VangerUnit::CheckReturn2Track (void)
 {
     int dx,dy;
     int d1,d2;
     dx = getDistX(R_curr.x,TargetPoint.vPoint.x);
     dy = getDistY(R_curr.y,TargetPoint.vPoint.y);
     d1 = round(sqrt(dx*(double)dx + dy*(double)dy));
     if(PointStatus & TRK_NODE_MASK){
         dx = getDistX(R_curr.x,pNode->x);
         dy = getDistY(R_curr.y,pNode->y);
         d2 = round(sqrt(dx*(double)dx + dy*(double)dy));
     }else{
         dx = getDistX(R_curr.x,pNextLink->x);
         dy = getDistY(R_curr.y,pPrevLink->y);
         d2 = round(sqrt(dx*(double)dx + dy*(double)dy));
     };
     if(TargetPoint.PointStatus & TRK_NODE_MASK){
         if(!TargetPoint.pNode) return 0;
         dx = getDistX(TargetPoint.vPoint.x,TargetPoint.pNode->x);
         dy = getDistY(TargetPoint.vPoint.y,TargetPoint.pNode->y);
         d2 += round(sqrt(dx*(double)dx + dy*(double)dy));
     }else{
         if(!TargetPoint.pNextLink) return 0;
         dx = getDistX(TargetPoint.vPoint.x,TargetPoint.pNextLink->x);
         dy = getDistY(TargetPoint.vPoint.y,TargetPoint.pNextLink->y);
         d2 += round(sqrt(dx*(double)dx + dy*(double)dy));
     };
     if(d1 > d2) return 0;
     return 1;
 };
References getDistX(), getDistY(), TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, round(), TrackUnit::TargetPoint, TRK_NODE_MASK, TrackLinkType::vPoint, Vector::x, LinkType::x, NodeType::x, Vector::y, LinkType::y, and NodeType::y.
Referenced by ResolveHandlerFind().
CheckSpeetle()
int VangerUnit::CheckSpeetle (void)
 {
     int i;
     for(i = 0;i < ItemMatrix->NumSlot;i++){
         if(GunSlotData[ItemMatrix->nSlot[i]].pData && (GunSlotData[ItemMatrix->nSlot[i]].ItemData->ActIntBuffer.type == ACI_SPEETLE_SYSTEM_LIGHT || GunSlotData[ItemMatrix->nSlot[i]].ItemData->ActIntBuffer.type == ACI_SPEETLE_SYSTEM_HEAVY))
             return 1;
     };
     return 0;
 };
References ACI_SPEETLE_SYSTEM_HEAVY, ACI_SPEETLE_SYSTEM_LIGHT, StuffObject::ActIntBuffer, GunSlotData, GunSlot::ItemData, uvsUnitType::ItemMatrix, UnitItemMatrix::nSlot, UnitItemMatrix::NumSlot, GunSlot::pData, and actintItemData::type.
Referenced by BulletCollision().
CheckStartJump()
int VangerUnit::CheckStartJump (void)
 {
     int st;
     st = (MaxEnergy - ImpulsePower) / max_jump_power;
     if(Energy >  ImpulsePower){
         Energy -= st;
         jump_power++;
         if(jump_power > max_jump_power)
             return 1;
         else
             return 0;
     };
     return 1;
 };
References uvsUnitType::Energy, uvsUnitType::ImpulsePower, Object::jump_power, max_jump_power, and uvsUnitType::MaxEnergy.
ClearEvent()
void VangerUnit::ClearEvent (GeneralObject * obj)
 {
     aiUnitEvent* l;
     l = (aiUnitEvent*)(aiEvent.Tail);
     if(obj->ID == ID_VANGER){
         while(l){
             if(l->Obj == obj || l->Subj == (VangerUnit*)(obj))
                 l->Refresh = 0;
             l = (aiUnitEvent*)(l->Next);
         };
     }else{
         while(l){
             if(l->Obj == obj)
                 l->Refresh = 0;
             l = (aiUnitEvent*)(l->Next);
         };
     };
 };
References aiEvent, GeneralObject::ID, ID_VANGER, aiListElement::Next, aiUnitEvent::Obj, aiUnitEvent::Refresh, aiUnitEvent::Subj, and aiListType::Tail.
Referenced by StuffDestroyHandler(), and VangerDestroyHandler().
ClearItemList()
void VangerUnit::ClearItemList (void)
 {
     StuffObject* p;
     StuffObject* pp;
     p = DeviceData;
     while(p){
         pp = p->NextDeviceList;
         p->Storage->Deactive(p);
         DelDevice(p);
         p = pp;
     };
 };
References StuffObject::Deactive(), uvsUnitType::DelDevice(), uvsUnitType::DeviceData, and StuffObject::NextDeviceList.
Referenced by ActionDispatcher::Close().
ClearObjEvent()
void VangerUnit::ClearObjEvent (GeneralObject * obj)
 {
     aiUnitEvent* l;
     l = (aiUnitEvent*)(aiEvent.Tail);
     while(l){
         if(l->Obj == obj)
             l->Refresh = 0;
         l = (aiUnitEvent*)(l->Next);
     };
 };
References aiEvent, aiListElement::Next, aiUnitEvent::Obj, aiUnitEvent::Refresh, and aiListType::Tail.
ClearSubjEvent()
void VangerUnit::ClearSubjEvent (VangerUnit * subj)
 {
     aiUnitEvent* l;
     l = (aiUnitEvent*)(aiEvent.Tail);
     while(l){
         if(l->Subj == subj)
             l->Refresh = 0;
         l = (aiUnitEvent*)(l->Next);
     };
 };
References aiEvent, aiListElement::Next, aiUnitEvent::Refresh, aiUnitEvent::Subj, and aiListType::Tail.
CreateParticleMechos()
void VangerUnit::CreateParticleMechos (const Vector & v, int r, int type = 0)
 {
     TargetParticleObject* p;
     Vector vPos;
     int i,a,da,dr;
     unsigned char color_offset,color_shift;
     if(Visibility == VISIBLE){
         COLORS_VALUE_TABLE[COLORS_IDS::BODY*2] = body_color_offset;
         COLORS_VALUE_TABLE[COLORS_IDS::BODY*2 + 1] = body_color_shift;
         p = (TargetParticleObject*)(EffD.GetObject(EFF_PARTICLE02));
         if(p){
             a = RND(PI*2);
             da = 8 * PI  / model->num_poly;
             if (_type)
                 p->CreateParticle(v,_type,0);
             else
                 p->CreateParticle(v,ROTOR_PROCESS_LIFE_TIME,0);
             dr = r / 8;
             DBM A = A_l2g*scale_real;
             for(i = 0;i < model->num_poly;i++){
                 vPos = Vector(dr + RND(r),0,0)*DBM(a,Z_AXIS);
                 vPos += v;
                 color_offset = COLORS_VALUE_TABLE[model->polygons[i].color_id*2];
                 color_shift = COLORS_VALUE_TABLE[model->polygons[i].color_id*2 + 1];
                 p->AddVertex2(vPos + Vector(RND(dr),RND(dr),0),
                         Vector(1 - RND(2),1- RND(2),0) + v + (A*Vector(model->polygons[i].middle_x,model->polygons[i].middle_y,model->polygons[i].middle_z)),
                         color_offset + (((1 << (7 - color_shift)) - 1) & ~1), _type);
                 p->AddVertex2(vPos + Vector(RND(dr),RND(dr),0),
                         Vector(1 - RND(2),1- RND(2),0) + v + (A*Vector(model->polygons[i].middle_x,model->polygons[i].middle_y,model->polygons[i].middle_z)),
                         color_offset + (((1 << (7 - color_shift)) - 1) & ~1), _type);
                 a = rPI(a + da);
             };
             EffD.ConnectObject(p);
         };
     };
 };
References Object::A_l2g, TargetParticleObject::AddVertex2(), COLORS_IDS::BODY, Object::body_color_offset, Object::body_color_shift, COLORS_VALUE_TABLE, UnitList::ConnectObject(), TargetParticleObject::CreateParticle(), EFF_PARTICLE02, EffD, UnitList::GetObject(), Object::model, Model::num_poly, PI, Model::polygons, RND(), ROTOR_PROCESS_LIFE_TIME, rPI, Object::scale_real, VISIBLE, and Z_AXIS.
Referenced by AddFree(), AddPassage(), and VangerFunctionType::Quant().
CreateParticleRotor()
void VangerUnit::CreateParticleRotor (const Vector & v, int r)
 {
     TargetParticleObject* p;
     int i;
     unsigned char color_offset,color_shift;
     if(Visibility == VISIBLE){
         COLORS_VALUE_TABLE[COLORS_IDS::BODY*2] = body_color_offset;
         COLORS_VALUE_TABLE[COLORS_IDS::BODY*2 + 1] = body_color_shift;
         p = (TargetParticleObject*)(EffD.GetObject(EFF_PARTICLE02));
         if(p){
             p->CreateParticle(v,ROTOR_PROCESS_LIFE_TIME,1);
             for(i = 0;i < model->num_poly;i++){
                 color_offset = COLORS_VALUE_TABLE[model->polygons[i].color_id*2];
                 color_shift = COLORS_VALUE_TABLE[model->polygons[i].color_id*2 + 1];
                 p->AddVertex(R_curr + (Vector(model->polygons[i].middle_x,model->polygons[i].middle_y,model->polygons[i].middle_z)*(A_scl)),
                         color_offset + (((1 << (7 - color_shift)) - 1) & ~1),
                         (2 << 8) + realRND(1 << 8),(3 << 7) + realRND(1 << 7));
                 p->AddVertex(R_curr + (Vector(model->polygons[i].middle_x,model->polygons[i].middle_y,model->polygons[i].middle_z)*(A_scl)),
                         color_offset + (((1 << (7 - color_shift)) - 1) & ~1),
                         (2 << 8) + realRND(1 << 8),(3 << 7) + realRND(1 << 7));
             };
             for(i = 0;i < (p->NumParticle - model->num_poly*2);i++)
                 p->AddVertex(v + Vector(r - realRND(r << 1),r - realRND(r << 1),r - realRND(r << 1)),
                         FIRE_COLOR_FIRST + realRND(FIRE_PROCESS_COLOR_MAX),
                         (15 << 8) + realRND(20 << 8),1 << 8);
             EffD.ConnectObject(p);
         };
     };
 };
References Object::A_scl, TargetParticleObject::AddVertex(), COLORS_IDS::BODY, Object::body_color_offset, Object::body_color_shift, COLORS_VALUE_TABLE, UnitList::ConnectObject(), TargetParticleObject::CreateParticle(), EFF_PARTICLE02, EffD, FIRE_COLOR_FIRST, FIRE_PROCESS_COLOR_MAX, UnitList::GetObject(), Object::model, Model::num_poly, TargetParticleObject::NumParticle, Model::polygons, realRND(), ROTOR_PROCESS_LIFE_TIME, and VISIBLE.
Referenced by Quant(), SensorQuant(), ShellNetEvent(), and XpeditionOFF().
CreateVangerUnit()
void VangerUnit::CreateVangerUnit (void)
 {
     if(NetworkON){
         if(Status & SOBJ_ACTIVE){
             NetID = CREATE_NET_ID(NID_VANGER);
             ShellNetID = (NetID & (~(63 << 16))) | NID_SHELL;
             uvsPoint->Pmechos->color = aciGetPlayerColor();
         }else{
             NetID = 0;
             ShellNetID = 0;
         };
     };
     ShellUpdateFlag = 0;
     switch(uvsPoint->Pmechos->color){
         case 0:
             set_body_color(COLORS_IDS::BODY_GREEN);
             aiModifier = AI_MODIFIER_ELEEPOD;
             break;
         case 1:
             set_body_color(COLORS_IDS::BODY_RED);
             aiModifier = AI_MODIFIER_BEEBOORAT;
             break;
         case 2:
             set_body_color(COLORS_IDS::BODY_BLUE);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 3:
             set_body_color(COLORS_IDS::BODY_YELLOW);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 4:
             set_body_color(COLORS_IDS::BODY_CRIMSON);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 5:
             set_body_color(COLORS_IDS::BODY_GRAY);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 6:
             set_body_color(COLORS_IDS::ROTTEN_ITEM);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 7:
             set_body_color(COLORS_IDS::MATERIAL_3);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 8:
             set_body_color(COLORS_IDS::MATERIAL_1);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
         case 9:
             set_body_color(COLORS_IDS::MATERIAL_0);
             aiModifier = AI_MODIFIER_ZEEX;
             break;
     };
 //  FeatureEnable = 0;
     DoorFlag = 0;
     ExternalMode = EXTERNAL_MODE_NORMAL;
     ExternalTime = 0;
     ExternalLock = 0;
     ExternalDraw = 1;
     ExternalObject = ExternalLastSensor = ExternalSensor = NULL;
     ExternalTime2 = 0;
     ExternalAngle = 0;
     Go2World();
     TouchKeyObject = NULL;
     TouchKeyObjectFlag = 1;
     dynamic_state = WHEELS_TOUCH;
     CheckPointCount = 0;
     MaxKhoxPoison = KhoxPoison = 300 << 8;
     VangerChanger = NULL;
     VangerChangerCount = 0;
     MechosChangerType = 0;
     vChangerPosition = Vector(0,0,0);
     VangerChangerAngle = 0;
     VangerChangerArmor = 0;
     VangerChangerEnergy = 0;
     VangerChangerColor = 0;
     RandomUpdate = -1;
     LastMole = 0;
     CoptePoint = NULL;
     SwimPoint = NULL;
     MolePoint = NULL;
 #ifdef AUTOMATIC_CHANGE_WORLD
         if(Status & SOBJ_ACTIVE){
             aciWorldIndex = AUTOMATIC_WORLD_INDEX;
             AUTOMATIC_WORLD_INDEX = -1;
         };
 #endif
     if(Status & SOBJ_ACTIVE){
         aciUpdateCurCredits(aiGetHotBug());
 //      aciCurCredits = ActD.HotBug;
         aciMaxEnergy = (MaxEnergy >> 16) + 1;
         aciMaxArmor = (MaxArmor >> 16) + 1;
         aciCurEnergy = Energy >> 16;
         aciCurArmor = Armor >> 16;
         aciCurJumpCount = PassageCount;
         aciMaxJumpCount = MaxPassageCount + 1;
     };
     InitAI();
     RuffaGunTime = 0;
     SensorEnable = 0;
     VangerRaceStatus = VANGER_RACE_NONE;
     NetDestroyID = 0xff;
     NetChanger = 0;
     NetFunction = 0;
     PlayerDestroyFlag = 0;
     TabuUse = 0;
     NetworkArmor = Armor;
     NetworkEnergy = Energy;
     NetRuffaGunTime = 0;
     PrevImpuseFrame = 0;
     PrevNetFunction83Time = NetFunction83Time = NetProtractorFunctionTime = NetMessiahFunctionTime = 0;
 };
References aciCurArmor, aciCurEnergy, aciCurJumpCount, aciGetPlayerColor(), aciMaxArmor, aciMaxEnergy, aciMaxJumpCount, aciUpdateCurCredits(), aciWorldIndex, AI_MODIFIER_BEEBOORAT, AI_MODIFIER_ELEEPOD, AI_MODIFIER_ZEEX, aiGetHotBug(), aiModifier, uvsUnitType::Armor, AUTOMATIC_WORLD_INDEX, COLORS_IDS::BODY_BLUE, COLORS_IDS::BODY_CRIMSON, COLORS_IDS::BODY_GRAY, COLORS_IDS::BODY_GREEN, COLORS_IDS::BODY_RED, COLORS_IDS::BODY_YELLOW, CheckPointCount, uvsMechos::color, CoptePoint, CREATE_NET_ID, DoorFlag, uvsUnitType::Energy, EXTERNAL_MODE_NORMAL, ExternalAngle, ExternalDraw, ExternalLastSensor, ExternalLock, ExternalMode, ExternalObject, ExternalSensor, ExternalTime, ExternalTime2, Go2World(), InitAI(), KhoxPoison, LastMole, COLORS_IDS::MATERIAL_0, COLORS_IDS::MATERIAL_1, COLORS_IDS::MATERIAL_3, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, MaxKhoxPoison, uvsUnitType::MaxPassageCount, MechosChangerType, MolePoint, NetChanger, NetDestroyID, NetFunction, NetFunction83Time, NetMessiahFunctionTime, NetProtractorFunctionTime, NetRuffaGunTime, NetworkArmor, NetworkEnergy, NetworkON, NID_SHELL, NID_VANGER, NULL, uvsUnitType::PassageCount, PlayerDestroyFlag, uvsVanger::Pmechos, PrevImpuseFrame, PrevNetFunction83Time, RandomUpdate, COLORS_IDS::ROTTEN_ITEM, RuffaGunTime, SensorEnable, Object::set_body_color(), ShellNetID, ShellUpdateFlag, SOBJ_ACTIVE, SwimPoint, TabuUse, TouchKeyObject, TouchKeyObjectFlag, uvsKernel::uvsPoint, VANGER_RACE_NONE, VangerChanger, VangerChangerAngle, VangerChangerArmor, VangerChangerColor, VangerChangerCount, VangerChangerEnergy, VangerRaceStatus, vChangerPosition, and WHEELS_TOUCH.
Referenced by addVanger().
DeleteHandler()
void VangerUnit::DeleteHandler (void) virtual
Reimplemented from ActionUnit.
 {
     Go2Universe();
 };
References Go2Universe().
Referenced by ActionDispatcher::Close().
Destroy()
void VangerUnit::Destroy (void)
 {
     WaterParticleObject* wp;
     int i;
     if(Visibility == VISIBLE){
         if(!BeebonationFlag){
             if(dynamic_state & TOUCH_OF_AIR){
                 switch(DestroyPhase){
                     case 0:
                         if(Status & SOBJ_ACTIVE)
                             camera_impulse(128);
                         EffD.CreateExplosion(R_curr + vUp,EFF_EXPLOSION01,this,1 << 15,0);
                         break;
                     case 3:
                         if(ActD.Active)
                             SOUND_EXPLOSION(getDistX(ActD.Active->R_curr.x,R_curr.x))
                         else
                             SOUND_EXPLOSION(0)
                         if(DestroyClass > 1)
                             EffD.CreateExplosion(R_curr + vDown,EFF_EXPLOSION01,this,1 << 15,0);
                         break;
                     case 4:
                         switch(DestroyClass){
                             case 0:
                                 EffD.CreateExplosion(R_curr,EFF_EXPLOSION03,this,1 << 15,0);
                                 break;
                             case 1:
                                 EffD.CreateExplosion(R_curr,EFF_EXPLOSION03,this,2 << 15,0);
                                 break;
                             case 2:
                                 EffD.CreateExplosion(R_curr,EFF_EXPLOSION03,this,2 << 15,1 << 10);
                                 break;
                             case 3:
                                 EffD.CreateExplosion(R_curr,EFF_EXPLOSION03,this,3 << 15,1 << 10);
                                 break;
                         };
                         break;
                     case 10:
                         EffD.CreateExplosion(R_curr + vDown,EFF_EXPLOSION01,this,1 << 14,0);
                         DestroyEnvironment();
                         break;
                     case 11:
                         if(DestroyClass > 1)
                             EffD.CreateExplosion(R_curr + vUp,EFF_EXPLOSION01,this,3 << 15,0);
                         Explosion(64,nModel);
                         break;
                     case 17:
                         if(DestroyClass > 0)
                             EffD.CreateExplosion(R_curr + vDown,EFF_EXPLOSION01,this,1 << 14,0);
                         break;
                     case 18:
                         if(DestroyClass > 2)
                             EffD.CreateExplosion(R_curr + vUp,EFF_EXPLOSION01,this,1 << 15,1 << 11);
                         break;
                     case 21:
                         if(DestroyClass > 1)
                             EffD.CreateExplosion(R_curr + vUp,EFF_EXPLOSION01,this,1 << 14,0);
                         break;
                     case 22:
                         if(DestroyClass > 0)
                             EffD.CreateExplosion(R_curr + vUp,EFF_EXPLOSION01,this,1 << 15,0);
                         break;
                     case 24:
                         if(DestroyClass > 2)
                             EffD.CreateExplosion(R_curr,EFF_EXPLOSION03,this,1 << 13,3 << 10);
                         break;
                     default:
                         if(dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH))
                             MapD.CreateCrater(R_curr,MAP_POINT_CRATER09);
                         break;
                 };
             }else{
                 if(DestroyPhase & 3){
                     wp = (WaterParticleObject*)(EffD.GetObject(EFF_PARTICLE04));
                     if(wp){
                         wp->CreateParticle(20,5,3 << 8,radius,5,28,5,Vector(R_curr.x + radius - RND(2*radius),R_curr.y + radius - RND(2*radius),R_curr.z));
                         EffD.ConnectObject(wp);
                     };
                     EffD.CreateDeform(R_curr + Vector(PASSING_WAVE_RADIUS - realRND(PASSING_WAVE_RADIUS2),PASSING_WAVE_RADIUS - realRND(PASSING_WAVE_RADIUS2),83),DEFORM_WATER_ONLY,PASSING_WAVE_PROCESS);
                     if(DestroyPhase == 11){
                         Explosion(64, nModel);
                         DestroyEnvironment();
                         if(ActD.Active)
                             SOUND_EXPLOSION(getDistX(ActD.Active->R_curr.x,R_curr.x))
                     };
                     if(RND(15) < 5 && (dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH)))
                         MapD.CreateCrater(R_curr,MAP_POINT_CRATER09);
                 };
             };
         };
     };
     if(DestroyPhase++ == 27){
         if(Status & SOBJ_ACTIVE){
             if(NetworkON){
                 NetStatisticUpdate(NET_STATISTICS_DEATH);
                 send_player_body(my_player_body);
                 ExternalMode = EXTERNAL_MODE_EARTH_PREPARE;
                 ExternalTime = 10;
                 PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
                 switch(my_server_data.GameType){
                     case MECHOSOMA:
                         ChangeWorldConstraction = CurrentWorld;
                         break;
                     case VAN_WAR:
                         if(my_server_data.Van_War.Nascency == -1) ChangeWorldConstraction = RND(3);
                         else ChangeWorldConstraction = my_server_data.Van_War.Nascency;
                         break;
                     case PASSEMBLOSS:
                         if(UsedCheckNum == 0) ChangeWorldConstraction = GloryPlaceData[0].World;
                         else{
                             for(i = UsedCheckNum - 1;i >= 0;i--){
                                 if(GloryPlaceData[i].World  < MAIN_WORLD_MAX - 1){
                                     ChangeWorldConstraction = GloryPlaceData[i].World;
                                     break;
                                 };
                             };
                         };
                         break;
                 };
                 ExternalLock = 1;
                 ExternalDraw = 1;
                 ExternalObject = NULL;
                 switch_analysis(0);
             }else{
                 if(GetStuffObject(this,ACI_SPUMMY)/* && CurrentWorld < MAIN_WORLD_MAX - 1*/){
                     ActD.SpummyRunner = 1;
                     GamerResult.earth_unable = 1;
 //                  if(CurrentWorld != WORLD_FOSTRAL)
                         ChangeWorldConstraction = WORLD_FOSTRAL;
                     ExternalMode = EXTERNAL_MODE_LIGHT;
                     ExternalTime = 3;
         //          StartHidePassage(ExternalTime);
                     PalCD.Set(CPAL_PASSAGE_TO,ExternalTime);
                     ExternalLock = 1;
                     ExternalDraw = 0;
                     ExternalObject = NULL;
                     switch_analysis(0);
                 }else{
                     Status |= SOBJ_DISCONNECT;
 //                  ObjectDestroy(this);
                     uvsPoint -> destroy(PlayerDestroyFlag);
                     GameOverID = GAME_OVER_EXPLOSION;
                     GameQuantReturnValue = RTO_LOADING3_ID;
                 };
             };
         }else{
             if(!NetworkON) uvsPoint -> destroy(PlayerDestroyFlag);
             Status |= SOBJ_DISCONNECT;
         };
     };
 };
References ACI_SPUMMY, ActD, ActionDispatcher::Active, BeebonationFlag, camera_impulse(), ChangeWorldConstraction, UnitList::ConnectObject(), CPAL_HIDE_PASSAGE, CPAL_PASSAGE_TO, EffectDispatcher::CreateDeform(), EffectDispatcher::CreateExplosion(), CurrentWorld, DEFORM_WATER_ONLY, uvsUnitType::DestroyClass, DestroyEnvironment(), TrackUnit::DestroyPhase, uvsGamerResult::earth_unable, EFF_EXPLOSION01, EFF_EXPLOSION03, EFF_PARTICLE04, EffD, Object::Explosion(), EXTERNAL_MODE_EARTH_PREPARE, EXTERNAL_MODE_LIGHT, ExternalDraw, ExternalLock, ExternalMode, ExternalObject, ExternalTime, GAME_OVER_EXPLOSION, GameOverID, GameQuantReturnValue, GamerResult, ServerData::GameType, getDistX(), UnitList::GetObject(), GetStuffObject(), GloryPlaceData, GROUND_COLLISION, MAIN_WORLD_MAX, MapD, MECHOSOMA, my_player_body, my_server_data, VAN_WAR_PRM::Nascency, NET_STATISTICS_DEATH, NetStatisticUpdate(), NetworkON, ActionUnit::nModel, NULL, PalCD, PASSEMBLOSS, PASSING_WAVE_PROCESS, PASSING_WAVE_RADIUS, PASSING_WAVE_RADIUS2, PlayerDestroyFlag, Object::radius, realRND(), RND(), RTO_LOADING3_ID, send_player_body(), PalConstructor::Set(), SOBJ_ACTIVE, SOBJ_DISCONNECT, SOUND_EXPLOSION, ActionDispatcher::SpummyRunner, Object::switch_analysis(), TOUCH_OF_AIR, UsedCheckNum, uvsKernel::uvsPoint, VAN_WAR, ServerData::Van_War, ActionUnit::vDown, VISIBLE, ActionUnit::vUp, WHEELS_TOUCH, GloryPlace::World, WORLD_FOSTRAL, wp, and Object::x.
Referenced by ItemQuant().
DestroyCollision()
void VangerUnit::DestroyCollision (int l, Object * p)
 {
     int pa;
     if(NetworkON && !(Status & SOBJ_ACTIVE)) return;
     if((Status & SOBJ_ACTIVE) && !(TabuUse & TABUTASK_COUNT_DAMAGE)){
         uvsCheckKronIventTabuTask(UVS_KRON_EVENT::DAMAGE,1);
         TabuUse |= TABUTASK_COUNT_DAMAGE;
     };
     pa = Armor;
     if((Armor -= l_16) < 0)
         Armor = 0;
     if(pa > 0 && Armor <= 0 && p){
         //NetDestroyID = GET_STATION(p->NetID);
         if(NetworkON && p->ID == ID_VANGER){
             switch(my_server_data.GameType){
                 case VAN_WAR:
                     if(!(my_server_data.Van_War.TeamMode) || ((VangerUnit*)(p))->uvsPoint->Pmechos->color != uvsPoint->Pmechos->color)
                         NetDestroyID = GET_STATION(p->NetID);
                     break;
                 case PASSEMBLOSS:
                     NetDestroyID = GET_STATION(p->NetID);
                     break;
                 case MECHOSOMA:
                     if(!(my_server_data.Mechosoma.TeamMode) || ((VangerUnit*)(p))->uvsPoint->Pmechos->color != uvsPoint->Pmechos->color)
                         NetDestroyID = GET_STATION(p->NetID);
                     break;
             };
         };
         if(p->Status & SOBJ_ACTIVE){
             PlayerDestroyFlag = 1;
             GamerResult.vanger_kill++;
             uvsPoint->KillStatic();
         };
     };
 };
References uvsUnitType::Armor, uvsMechos::color, UVS_KRON_EVENT::DAMAGE, GamerResult, ServerData::GameType, GET_STATION, Object::ID, ID_VANGER, uvsVanger::KillStatic(), MECHOSOMA, ServerData::Mechosoma, my_server_data, NetDestroyID, NetworkON, PASSEMBLOSS, PlayerDestroyFlag, uvsVanger::Pmechos, SOBJ_ACTIVE, TABUTASK_COUNT_DAMAGE, TabuUse, VAN_WAR_PRM::TeamMode, MECHOSOMA_PRM::TeamMode, uvsCheckKronIventTabuTask(), uvsKernel::uvsPoint, VAN_WAR, ServerData::Van_War, and uvsGamerResult::vanger_kill.
DestroyEnvironment()
void VangerUnit::DestroyEnvironment (void)
 {
     VangerUnit* p;
 /*  p = (VangerUnit*)(ActD.Tail);
     while(p){
         if(p->ID != ID_VANGER)
             ErrH.Abort("Bad List Mechos");
         p = (VangerUnit*)(p->NextTypeList);
     };*/
     Vector vCheck;
     int d;
     p = (VangerUnit*)(ActD.Tail);
     int ml;
     ml = 5 * radius;
     while(p){
 //      if(p->ID != ID_VANGER)
 //          ErrH.Abort("Bad Vanger List");
         if(p->Visibility == VISIBLE && p != this){
             vCheck = Vector(getDistX(p->R_curr.x,R_curr.x),getDistY(p->R_curr.y,R_curr.y),p->R_curr.z - R_curr.z);
             d = vCheck.vabs();
             if(d < ml){
                 p->impulse(vCheck,30*(ml - d) / ml,0);
                 p->BulletCollision((MaxEnergy / ml)*(ml - d),NULL);
             };
         };
         p = (VangerUnit*)(p->NextTypeList);
     };
 };
References ActD, BulletCollision(), getDistX(), getDistY(), Object::impulse(), uvsUnitType::MaxEnergy, NULL, Object::radius, UnitList::Tail, Vector::vabs(), VISIBLE, Object::x, and Object::y.
Referenced by Destroy().
DestroyItem()
void VangerUnit::DestroyItem (StuffObject * p)
 {
     switch(p->ActIntBuffer.type){
         case ACI_CIRTAINER:
         case ACI_EMPTY_CIRTAINER:
         case ACI_CONLARVER:
         case ACI_EMPTY_CONLARVER:
         case ACI_ELEECH:
         case ACI_KERNOBOO:
         case ACI_PIPETKA:
         case ACI_WEEZYK:
         case ACI_PROTRACTOR:
         case ACI_MECHANIC_MESSIAH:
         case ACI_FUNCTION83:
         case ACI_BOOT_SECTOR:
         case ACI_PEELOT:
         case ACI_LEEPURINGA:
         case ACI_SANDOLL_PART1:
         case ACI_SANDOLL_PART2:
         case ACI_LAST_MOGGY_PART1:
         case ACI_LAST_MOGGY_PART2:
         case ACI_QUEEN_FROG_PART1:
         case ACI_QUEEN_FROG_PART2:
         case ACI_LAWN_MOWER_PART1:
         case ACI_LAWN_MOWER_PART2:
         case ACI_WORMASTER_PART1:
         case ACI_WORMASTER_PART2:
         case ACI_TABUTASK:
         case ACI_ELEEPOD:
         case ACI_BEEBOORAT:
         case ACI_ZEEX:
         case ACI_PALOCHKA:
         case ACI_PIPKA:
         case ACI_NOBOOL:
         case ACI_BOORAWCHIK:
         case ACI_PEREPONKA:
         case ACI_ZEEFICK:
         case ACI_TABUTASK_FAILED:
         case ACI_TABUTASK_SUCCESSFUL:
             CheckOutDevice(p);
             if(Status & SOBJ_ACTIVE){
                 ActD.CheckDevice(p);
 //              aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             p->DeviceOut(R_curr + Vector(0,0,radius*4));
             break;
         case ACI_RUBOX:
             ObjectDestroy(p);
             CheckOutDevice(p);
             if(Status & SOBJ_ACTIVE){
                 ActD.CheckDevice(p);
 //              aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             p->Storage->Deactive(p);
             DelDevice(p);
             break;
         case ACI_SPUMMY:
             if(!(Status & SOBJ_ACTIVE)){
                 CheckOutDevice(p);
                 p->DeviceOut(R_curr + Vector(0,0,radius*4));
             };
             break;
         default:
             if(NetworkON){
                 if((int)(RND(ItemD.Total)) < ItemD.Num){
                     ObjectDestroy(p);
                     CheckOutDevice(p);
                     if(Status & SOBJ_ACTIVE){
                         ActD.CheckDevice(p);
     //                  aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                         aciRemoveItem(&(p->ActIntBuffer));
                     };
                     p->Storage->Deactive(p);
                     DelDevice(p);
                 }else DischargeItem(p);
             }else{
                 if(RND(aiCutLuck) < 30){
                     ObjectDestroy(p);
                     CheckOutDevice(p);
                     if(Status & SOBJ_ACTIVE){
                         ActD.CheckDevice(p);
     //                  aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                         aciRemoveItem(&(p->ActIntBuffer));
                     };
                     p->Storage->Deactive(p);
                     DelDevice(p);
                 }else DischargeItem(p);
             };
             break;
     };
 };
References ACI_BEEBOORAT, ACI_BOORAWCHIK, ACI_BOOT_SECTOR, ACI_CIRTAINER, ACI_CONLARVER, ACI_ELEECH, ACI_ELEEPOD, ACI_EMPTY_CIRTAINER, ACI_EMPTY_CONLARVER, ACI_FUNCTION83, ACI_KERNOBOO, ACI_LAST_MOGGY_PART1, ACI_LAST_MOGGY_PART2, ACI_LAWN_MOWER_PART1, ACI_LAWN_MOWER_PART2, ACI_LEEPURINGA, ACI_MECHANIC_MESSIAH, ACI_NOBOOL, ACI_PALOCHKA, ACI_PEELOT, ACI_PEREPONKA, ACI_PIPETKA, ACI_PIPKA, ACI_PROTRACTOR, ACI_QUEEN_FROG_PART1, ACI_QUEEN_FROG_PART2, ACI_RUBOX, ACI_SANDOLL_PART1, ACI_SANDOLL_PART2, ACI_SPUMMY, ACI_TABUTASK, ACI_TABUTASK_FAILED, ACI_TABUTASK_SUCCESSFUL, ACI_WEEZYK, ACI_WORMASTER_PART1, ACI_WORMASTER_PART2, ACI_ZEEFICK, ACI_ZEEX, aciRemoveItem(), ActD, StuffObject::ActIntBuffer, aiCutLuck, ActionDispatcher::CheckDevice(), CheckOutDevice(), StuffObject::Deactive(), uvsUnitType::DelDevice(), StuffObject::DeviceOut(), DischargeItem(), ItemD, NetworkON, UnitList::Num, ObjectDestroy(), Object::radius, RND(), SOBJ_ACTIVE, UnitList::Total, and actintItemData::type.
Referenced by ItemQuant().
DischargeItem()
void VangerUnit::DischargeItem (StuffObject * p)
 {
     switch(p->ActIntBuffer.type){
         case ACI_MACHOTINE_GUN_LIGHT:
         case ACI_MACHOTINE_GUN_HEAVY:
         case ACI_SPEETLE_SYSTEM_LIGHT:
         case ACI_SPEETLE_SYSTEM_HEAVY:
         case ACI_GHORB_GEAR_LIGHT:
         case ACI_GHORB_GEAR_HEAVY:
             if(NetworkON) p->ActIntBuffer.data1 = RND(p->ActIntBuffer.data1);
             else p->ActIntBuffer.data1 = RND(aiCutLuck) * p->ActIntBuffer.data1 / 100;
             CheckOutDevice(p);
             if(Status & SOBJ_ACTIVE){
                 ActD.CheckDevice(p);
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             p->DeviceOut(R_curr + Vector(0,0,radius*4));
             break;
         case ACI_COPTE_RIG:
         case ACI_CUTTE_RIG:
         case ACI_CROT_RIG:
             if(NetworkON) p->ActIntBuffer.data1 = RND(p->ActIntBuffer.data1);
             else p->ActIntBuffer.data1 = RND(aiCutLuck) * p->ActIntBuffer.data1 / 100;
             CheckOutDevice(p);
             if(Status & SOBJ_ACTIVE){
                 ActD.CheckDevice(p);
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
             p->DeviceOut(R_curr + Vector(0,0,radius*4));
             break;
         case ACI_TERMINATOR:
         case ACI_TERMINATOR2:
         case ACI_SPEETLE_SYSTEM_AMMO0:
         case ACI_SPEETLE_SYSTEM_AMMO1:
         case ACI_CRUSTEST_CANNON_AMMO:
             if(p->ActIntBuffer.data1 > 1){
                 if(NetworkON) p->ActIntBuffer.data1 = 1 + RND(p->ActIntBuffer.data1- 1);
                 else p->ActIntBuffer.data1 = 1 + RND(aiCutLuck) * (p->ActIntBuffer.data1 - 1) / 100;
                 CheckOutDevice(p);
                 if(Status & SOBJ_ACTIVE){
                     ActD.CheckDevice(p);
                     aciRemoveItem(&(p->ActIntBuffer));
                 };
                 p->DeviceOut(R_curr + Vector(0,0,radius*4));
             }else{
                 ObjectDestroy(p);
                 CheckOutDevice(p);
                 if(Status & SOBJ_ACTIVE){
                     ActD.CheckDevice(p);
                     aciRemoveItem(&(p->ActIntBuffer));
                 };
                 p->Storage->Deactive(p);
                 DelDevice(p);
             };
             break;
         case ACI_SPUMMY:
             if(!(Status & SOBJ_ACTIVE)){
                 CheckOutDevice(p);
                 p->DeviceOut(R_curr + Vector(0,0,radius*4));
             };
             break;
         case ACI_RUBOX:
             ObjectDestroy(p);
             CheckOutDevice(p);
             if(Status & SOBJ_ACTIVE){
                 ActD.CheckDevice(p);
 //              aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             p->Storage->Deactive(p);
             DelDevice(p);
             break;
         default:
             CheckOutDevice(p);
             if(Status & SOBJ_ACTIVE){
                 ActD.CheckDevice(p);
 //              aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             p->DeviceOut(R_curr + Vector(0,0,radius*4));
             break;
     };
 };
References ACI_COPTE_RIG, ACI_CROT_RIG, ACI_CRUSTEST_CANNON_AMMO, ACI_CUTTE_RIG, ACI_GHORB_GEAR_HEAVY, ACI_GHORB_GEAR_LIGHT, ACI_MACHOTINE_GUN_HEAVY, ACI_MACHOTINE_GUN_LIGHT, ACI_RUBOX, ACI_SPEETLE_SYSTEM_AMMO0, ACI_SPEETLE_SYSTEM_AMMO1, ACI_SPEETLE_SYSTEM_HEAVY, ACI_SPEETLE_SYSTEM_LIGHT, ACI_SPUMMY, ACI_TERMINATOR, ACI_TERMINATOR2, aciRemoveItem(), ActD, StuffObject::ActIntBuffer, aiCutLuck, ActionDispatcher::CheckDevice(), CheckOutDevice(), actintItemData::data0, actintItemData::data1, StuffObject::Deactive(), uvsUnitType::DelDevice(), StuffObject::DeviceOut(), NetworkON, ObjectDestroy(), Object::radius, RND(), SOBJ_ACTIVE, actintItemData::type, StuffObject::uvsDeviceType, and uvsSetItemType().
Referenced by DestroyItem(), and ItemQuant().
DrawMechosParticle()
void VangerUnit::DrawMechosParticle (int x, int y, int speed, int level, int n)
 {
     if(ExternalMode != EXTERNAL_MODE_NORMAL || !ExternalDraw)
         return;
     if(Armor < MaxArmor && (int)(RND(MaxArmor)) > Armor && (int)(RND(MaxArmor)) > Armor)
         MapD.CreateDust(Vector(x,y,level), (int)MAP_SMOKE_PROCESS);
     TrackUnit::DrawMechosParticle(x,y,speed,level,n);
 };
References uvsUnitType::Armor, TrackUnit::DrawMechosParticle(), EXTERNAL_MODE_NORMAL, ExternalDraw, ExternalMode, level, MapD, uvsUnitType::MaxArmor, RND(), Object::speed, Object::x, and Object::y.
DrawQuant()
void VangerUnit::DrawQuant (void)
 {
     WaterParticleObject* p;
     int i;
     if(!ExternalDraw || (Status & SOBJ_WAIT_CONFIRMATION)) return;
     TrackUnit::DrawQuant();
     Vector vCheck;
     if(ExternalMode == EXTERNAL_MODE_NORMAL){
         if(Status & SOBJ_ACTIVE){
             if(!mole_on){
                 if(dynamic_state & TOUCH_OF_AIR){
                     if(CurrentWorld != WORLD_KHOX) AddOxigenResource();
                 }else{
                     if(!(dynamic_state & TOUCH_OF_WATER))
                         UseOxigenResource();
                 };
             };
             if(dynamic_state & TOUCH_OF_WATER){
                 if(CurrentWorld == WORLD_THREALL){
                     if(NetworkON) BulletCollision((MaxEnergy + MaxArmor) / 150,NULL);
                     else BulletCollision((MaxEnergy + MaxArmor) / 20,NULL);
                 }else{
                     if(!(dynamic_state & TOUCH_OF_AIR)){
                         ChargeWeapon(this,ACI_MACHOTINE_GUN_LIGHT,1);
                         ChargeWeapon(this,ACI_MACHOTINE_GUN_HEAVY,1);
                         UseOxigenResource();
                         if(Speed){
                             p = (WaterParticleObject*)(EffD.GetObject(EFF_PARTICLE03));
                             if(p){
                                 p->CreateParticle(30,5,1 << 7,radius,5,28,5,R_curr);
                                 EffD.ConnectObject(p);
                             };
                         };
                     };
                 };
             };
         }else{
             if(dynamic_state & TOUCH_OF_WATER){
                 if(CurrentWorld == WORLD_THREALL)
                     BulletCollision(Energy / 20,NULL);
                 else{
                     if(Speed){
                         p = (WaterParticleObject*)(EffD.GetObject(EFF_PARTICLE03));
                         if(p){
                             p->CreateParticle(30,5,1 << 7,radius,5,28,5,R_curr);
                             EffD.ConnectObject(p);
                         };
                     };
                 };
             };
         };
     };
     PlayerData* pl;
     int cclx,ccly,ccrx,ccry,ccm;
     if(NetworkON && (Status & SOBJ_AUTOMAT)){
         pl = players_list.first();
         while(pl){
             if(uvsPoint == ((uvsVanger*)(pl->uvsPoint)) && pl->name){
                 ccm = XGR_Obj.ClipMode;
                 XGR_SetClipMode(XGR_CLIP_ALL);
                 cclx = XGR_Obj.clipLeft;
                 ccly = XGR_Obj.clipTop;
                 ccrx = XGR_Obj.clipRight;
                 ccry = XGR_Obj.clipBottom;
                 XGR_SetClip(UcutLeft,VcutUp,UcutRight,VcutDown);
                 aOutText32clip(R_scr.x,R_scr.y,165 | (2 << 16),pl->name,0,0,0);
                 XGR_SetClip(cclx,ccly,ccrx,ccry);
                 XGR_SetClipMode(ccm);
                 break;
             };
             pl = (PlayerData*)pl -> next;
         };
     };
 #ifdef UNIT_DEBUG_VIEW
 #ifdef TEST_TRACK
     if(Status & SOBJ_ACTIVE){
         int cc1,cc2;
         cc1 = 111;
         cc2 = 111;
         if(PointStatus & TRK_BRANCH_MASK){
             cc2 = 111;
             if(PointStatus & TRK_IN_MASK) cc1 = 175;
             else cc1 = 111;
         }else{
             cc1 = 111;
             if(PointStatus & TRK_IN_MASK) cc2 = 175;
             else cc2 = 111;
         };
         if(TestLevelFlag){
             if(pNode){
                 if(pNode->TrackCount){
                     /*line_trace(Vector(pNode->BorderX[0],pNode->BorderY[0],159),Vector(pNode->BorderX[pNode->NumBranch - 1],pNode->BorderY[pNode->NumBranch - 1],159));
                     for(i = 1;i < pNode->NumBranch;i++){
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],159),Vector(pNode->BorderX[i - 1],pNode->BorderY[i - 1],159));
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],159),Vector(pNode->x,pNode->y,159));
                     };*/
                 }else{
                     /*line_trace(Vector(pNode->BorderX[0],pNode->BorderY[0],cc2),Vector(pNode->BorderX[pNode->NumBranch - 1],pNode->BorderY[pNode->NumBranch - 1],cc2));
                     for(i = 1;i < pNode->NumBranch;i++){
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],cc2),Vector(pNode->BorderX[i - 1],pNode->BorderY[i - 1],cc2));
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],cc2),Vector(pNode->x,pNode->y,cc2));
                     };*/
                 };
             };
             for(i = 0;i < pBranch->NumLink;i++){
                 if(pBranch->Link[i].TrackCount){
                     putMapPixel(pBranch->Link[i].xr,pBranch->Link[i].yr,159);
                     putMapPixel(pBranch->Link[i].xl,pBranch->Link[i].yl,159);
                 }else{
                     putMapPixel(pBranch->Link[i].xr,pBranch->Link[i].yr,cc1);
                     putMapPixel(pBranch->Link[i].xl,pBranch->Link[i].yl,cc1);
                 };
             };
         }else{
             for(i = 0;i < pBranch->NumLink;i++){
                 if(pBranch->Link[i].Level){
                     putMapPixel(pBranch->Link[i].xr,pBranch->Link[i].yr,175);
                     putMapPixel(pBranch->Link[i].xl,pBranch->Link[i].yl,175);
                 }else{
                     putMapPixel(pBranch->Link[i].xr,pBranch->Link[i].yr,159);
                     putMapPixel(pBranch->Link[i].xl,pBranch->Link[i].yl,159);
                 };
         //      putMapPixel(pBranch->Link[i].x,pBranch->Link[i].y,175);
             };
             if(pNode){
                 if(pNode->Level){
                     /*line_trace(Vector(pNode->BorderX[0],pNode->BorderY[0],175),Vector(pNode->BorderX[pNode->NumBranch - 1],pNode->BorderY[pNode->NumBranch - 1],175));
                     for(i = 1;i < pNode->NumBranch;i++){
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],175),Vector(pNode->BorderX[i - 1],pNode->BorderY[i - 1],175));
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],175),Vector(pNode->x,pNode->y,175));
                     };*/
                 }else{
                     /*line_trace(Vector(pNode->BorderX[0],pNode->BorderY[0],159),Vector(pNode->BorderX[pNode->NumBranch - 1],pNode->BorderY[pNode->NumBranch - 1],159));
                     for(i = 1;i < pNode->NumBranch;i++){
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],159),Vector(pNode->BorderX[i - 1],pNode->BorderY[i - 1],159));
                         line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],159),Vector(pNode->x,pNode->y,159));
                     };*/
                 };
             };
         };
         //line_trace(Vector(pNextLink->xl,pNextLink->yl,195),Vector(pNextLink->xr,pNextLink->yr,210));
         //line_trace(Vector(pPrevLink->xl,pPrevLink->yl,195),Vector(pPrevLink->xr,pPrevLink->yr,210));
     };
 #else
 /*  VangerUnit* van;
     if(Status & SOBJ_ACTIVE){
         vCheck = Vector(300,0,0)*RotMat;
         vCheck += R_curr;
         cycleTor(vCheck.x,vCheck.y);
         line_trace(Vector(R_curr.x,R_curr.y,159),Vector(vCheck.x,vCheck.y,159));
         van = (VangerUnit*)(ActD.Tail);
         while(van){
             if(van->Visibility == VISIBLE && !(van->Status & SOBJ_ACTIVE)){
                 if(TouchSphere(R_curr,vCheck,van->R_curr,van->radius,i))
                     line_trace(Vector(XCYCL(van->R_curr.x - radius),van->R_curr.y,159),Vector(XCYCL(van->R_curr.x + radius),van->R_curr.y,175));
             };
             van = (VangerUnit*)(van->NextTypeList);
         };
     };*/
     for(i = 0;i < pBranch->NumLink;i++){
         if(pBranch->Link[i].Level){
             putMapPixel(pBranch->Link[i].xr,pBranch->Link[i].yr,175);
             putMapPixel(pBranch->Link[i].xl,pBranch->Link[i].yl,175);
         }else{
             putMapPixel(pBranch->Link[i].xr,pBranch->Link[i].yr,159);
             putMapPixel(pBranch->Link[i].xl,pBranch->Link[i].yl,159);
         };
 //      putMapPixel(pBranch->Link[i].x,pBranch->Link[i].y,175);
     };
     if(PointStatus == TRK_IN_NODE){
         if(pNode->Level){
             line_trace(Vector(pNode->BorderX[0],pNode->BorderY[0],175),Vector(pNode->BorderX[pNode->NumBranch - 1],pNode->BorderY[pNode->NumBranch - 1],175));
             for(i = 1;i < pNode->NumBranch;i++){
                 line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],175),Vector(pNode->BorderX[i - 1],pNode->BorderY[i - 1],175));
                 line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],175),Vector(pNode->x,pNode->y,175));
             };
         }else{
             line_trace(Vector(pNode->BorderX[0],pNode->BorderY[0],159),Vector(pNode->BorderX[pNode->NumBranch - 1],pNode->BorderY[pNode->NumBranch - 1],159));
             for(i = 1;i < pNode->NumBranch;i++){
                 line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],159),Vector(pNode->BorderX[i - 1],pNode->BorderY[i - 1],159));
                 line_trace(Vector(pNode->BorderX[i],pNode->BorderY[i],159),Vector(pNode->x,pNode->y,159));
             };
         };
     };
     line_trace(Vector(R_curr.x,R_curr.y,170),Vector(R_curr.x + vTarget.x / 2,R_curr.y + vTarget.y / 2,170));
     if(SpeedDir == 0 || (OtherFlag & MECHOS_CALC_WAY)){
         line_trace(Vector(FrontPoint.pNextLink->xl,FrontPoint.pNextLink->yl,183),Vector(FrontPoint.pNextLink->xr,FrontPoint.pNextLink->yr,159));
         line_trace(Vector(FrontPoint.pPrevLink->xl,FrontPoint.pPrevLink->yl,183),Vector(FrontPoint.pPrevLink->xr,FrontPoint.pPrevLink->yr,159));
     }else{
         line_trace(Vector(FrontPoint.pNextLink->xl,FrontPoint.pNextLink->yl,183),Vector(FrontPoint.pNextLink->xr,FrontPoint.pNextLink->yr,183));
         line_trace(Vector(FrontPoint.pPrevLink->xl,FrontPoint.pPrevLink->yl,183),Vector(FrontPoint.pPrevLink->xr,FrontPoint.pPrevLink->yr,183));
     };
     line_trace(Vector(pNextLink->xl,pNextLink->yl,195),Vector(pNextLink->xr,pNextLink->yr,210));
     line_trace(Vector(pPrevLink->xl,pPrevLink->yl,195),Vector(pPrevLink->xr,pPrevLink->yr,210));
 #endif
 #endif
 };
References ACI_MACHOTINE_GUN_HEAVY, ACI_MACHOTINE_GUN_LIGHT, uvsUnitType::AddOxigenResource(), aOutText32clip(), NodeType::BorderX, NodeType::BorderY, BulletCollision(), ChargeWeapon(), XGR_Screen::clipBottom, XGR_Screen::clipLeft, XGR_Screen::ClipMode, XGR_Screen::clipRight, XGR_Screen::clipTop, UnitList::ConnectObject(), WaterParticleObject::CreateParticle(), CurrentWorld, ActionUnit::DrawQuant(), EFF_PARTICLE03, EffD, uvsUnitType::Energy, EXTERNAL_MODE_NORMAL, ExternalDraw, ExternalMode, XTList< Type >::first(), TrackUnit::FrontPoint, UnitList::GetObject(), LinkType::Level, NodeType::Level, BranchType::Link, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, MECHOS_CALC_WAY, Object::mole_on, PlayerData::name, NetworkON, Object::next, NULL, NodeType::NumBranch, BranchType::NumLink, ActionUnit::OtherFlag, TrackLinkType::pBranch, players_list, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, putMapPixel(), Object::R_scr, Object::radius, SOBJ_ACTIVE, SOBJ_AUTOMAT, SOBJ_WAIT_CONFIRMATION, ActionUnit::Speed, ActionUnit::SpeedDir, TOUCH_OF_AIR, TOUCH_OF_WATER, LinkType::TrackCount, NodeType::TrackCount, TRK_BRANCH_MASK, TRK_IN_MASK, TRK_IN_NODE, UcutLeft, UcutRight, uvsUnitType::UseOxigenResource(), PlayerData::uvsPoint, uvsKernel::uvsPoint, VcutDown, VcutUp, TrackUnit::vTarget, WORLD_KHOX, WORLD_THREALL, Vector::x, NodeType::x, XGR_CLIP_ALL, XGR_Obj, XGR_SetClip, XGR_SetClipMode, LinkType::xl, LinkType::xr, Vector::y, NodeType::y, LinkType::yl, and LinkType::yr.
FindEvent()
aiUnitEvent * VangerUnit::FindEvent (VangerUnit * subj, GeneralObject * obj)
 {
     aiUnitEvent* l;
     l = (aiUnitEvent*)(aiEvent.Tail);
     while(l){
         if(l->Subj == subj && l->Obj == obj)
             return l;
         l = (aiUnitEvent*)(l->Next);
     };
     return NULL;
 };
References aiEvent, aiListElement::Next, NULL, aiUnitEvent::Obj, aiUnitEvent::Subj, and aiListType::Tail.
Free()
void VangerUnit::Free (void)
 {
     uvsUnitType::Free();
 };
References uvsUnitType::Free().
GamerOrderInit()
void VangerUnit::GamerOrderInit (void)
 {
     if(!CompasObj.CurrentTarget){
         CompasObj.CurrentTarget = CompasObj.TargetData;
         aciRefreshTargetsMenu();
     };
     //stalkerg
     if(!CompasObj.CurrentTarget){
         return;
     }
     //stalkerg
     switch(CompasObj.CurrentTarget->ID){
         case CMP_OBJECT_ESCAVE:
         case CMP_OBJECT_SPOT:
             AddFindResolve(UNIT_ORDER_ENTER,CompasObj.CurrentTarget->Data)->Time = MaxWayCount;
             break;
         case CMP_OBJECT_PASSAGE:
             AddFindResolve(UNIT_ORDER_PASSAGE,CompasObj.CurrentTarget->Data)->Time = MaxWayCount;
             break;
         case CMP_OBJECT_SENSOR:
             AddFindResolve(UNIT_ORDER_SENSOR,CompasObj.CurrentTarget->Data)->Time = MaxWayCount;
             break;
     };
 };
References aciRefreshTargetsMenu(), AddFindResolve(), CMP_OBJECT_ESCAVE, CMP_OBJECT_PASSAGE, CMP_OBJECT_SENSOR, CMP_OBJECT_SPOT, CompasObj, CompasObject::CurrentTarget, CompasTargetType::Data, CompasTargetType::ID, TrackUnit::MaxWayCount, CompasObject::TargetData, aiUnitResolve::Time, UNIT_ORDER_ENTER, UNIT_ORDER_PASSAGE, and UNIT_ORDER_SENSOR.
Referenced by CalcAiFactor(), and ResolveGenerator().
GetAllert()
int VangerUnit::GetAllert (VangerUnit * p)
 {
     int i,s;
     GunSlot* gs;
     s = 0;
     for(i = 0;i < p->ItemMatrix->NumSlot;i++){
         gs = &(p->GunSlotData[p->ItemMatrix->nSlot[i]]);
         if(gs->pData){
             if(gs->pData->WaitTime) s += gs->pData->Power / gs->pData->WaitTime;
             else s += gs->pData->Power;
         };
     };
     if(WeaponDelta){
         if(s == 0) s = 1;
         else s = ((Armor + Energy) / s) - ((p->Armor + p->Energy) / WeaponDelta);
     }else{
         if(s) s = -(Armor + Energy) / s;
         else s = Armor - p->Armor;
     };
     return s;
 };
References uvsUnitType::Armor, uvsUnitType::Energy, GunSlotData, uvsUnitType::ItemMatrix, UnitItemMatrix::nSlot, UnitItemMatrix::NumSlot, GunSlot::pData, BulletControlType::Power, WorldBulletTemplate::WaitTime, and WeaponDelta.
Referenced by ResolveGenerator().
GetForceWay()
void VangerUnit::GetForceWay (int d2, Vector & v)
 {
     LinkType* p;
     int d,md;
     int dx,dy;
     Vector vt;
     vt = Vector(0,0,0);
 //  if(!SpeedFactorTime){
 //      v = vt;
 //      return;
 //  };
     md = 0;
     if(MoveDir){
         p = pBranch->Link + pBranch->NumLink - 1;
         while(p != pNextLink && p != pBranch->Link){
             dy = R_curr.y - p->y;
             dx = getDistX(R_curr.x,p->x);
             d = dx*dx + dy*dy;
             if(d < d2 && d > md){
                 vt.x = p->x;
                 vt.y = p->y;
                 md = d;
             };
             p--;
         };
     }else{
         p = pBranch->Link;
         while(p != pNextLink && p != (pBranch->Link + pBranch->NumLink - 1)){
             dy = R_curr.y - p->y;
             dx = getDistX(R_curr.x,p->x);
             d = dx*dx + dy*dy;
             if(d < d2 && d > md){
                 vt.x = p->x;
                 vt.y = p->y;
                 md = d;
             };
             p++;
         };
     };
     v = vt;
 };
References getDistX(), BranchType::Link, TrackUnit::MoveDir, BranchType::NumLink, TrackLinkType::pBranch, TrackLinkType::pNextLink, Vector::x, LinkType::x, Vector::y, and LinkType::y.
Referenced by CalcForce(), and CalcImpulse().
GetWeaponDelta()
void VangerUnit::GetWeaponDelta (void)
 {
     int i,s;
     GunSlot* gs;
     s = 0;
     for(i = 0;i < ItemMatrix->NumSlot;i++){
         gs = &(GunSlotData[ItemMatrix->nSlot[i]]);
         if(gs->pData){
             if(gs->pData->WaitTime) s += gs->pData->Power / gs->pData->WaitTime;
             else s += gs->pData->Power;
         };
     };
     WeaponDelta = s;
 };
References GunSlotData, uvsUnitType::ItemMatrix, UnitItemMatrix::nSlot, UnitItemMatrix::NumSlot, GunSlot::pData, BulletControlType::Power, WorldBulletTemplate::WaitTime, and WeaponDelta.
Referenced by GunSlot::CloseGun(), InitAI(), and GunSlot::OpenGun().
Go2Universe()
void VangerUnit::Go2Universe (void) virtual
Reimplemented from uvsUnitType.
 {
     StuffObject* p;
     StuffObject* pp;
     uvsItem* g;
     uvsVanger* n;
     VangerUnit* l;
     int i;
 #ifdef ITEM_LOG
     if(Status & SOBJ_ACTIVE){
         xLog < "\n\n\n\nGo2Universe:";
         p = DeviceData;
         while(p){
             xLog < "\n\nuvsType " <= (int)(p->uvsDeviceType);
             xLog < "\nActIntType " <= (int)(p->ActIntBuffer.type);
             xLog < "\nActIntData0 " <= (int)(p->ActIntBuffer.data0);
             xLog < "\nActIntData1 " <= (int)(p->ActIntBuffer.data1);
             p = (StuffObject*)(p->NextDeviceList);
         };
     };
 #endif
 //  ObjectDestroy(this);
     FreeList(uvsPoint->Pitem);
     if(Status & SOBJ_ACTIVE){
         if(NetworkON)
             iChatFinit();
         ItemD.LarvaHilator();
         uvsPoint->Pmechos->teleport = PassageCount | (Armor & 0xffffff00);
         aciDropMoveItem();
         if(vSetVangerFlag != -1){
             if(DeviceData){
                 p = DeviceData;
                 while(p){
                     pp = p->NextDeviceList;
                     ObjectDestroy(p);
                     if(p->uvsDeviceType == UVS_ITEM_TYPE::SECTOR){
                         CheckOutDevice(p);
                         ActD.CheckDevice(p);
                         aciRemoveItem(&(p->ActIntBuffer));
                     }else{
                         g = new uvsItem(p->uvsDeviceType);
                         aciGetItemCoords(&(p->ActIntBuffer),g->pos_x,g->pos_y);
                         g->param1 = p->ActIntBuffer.data0;
                         g->param2 = p->ActIntBuffer.data1;
                         uvsPoint->addItem(g,1);
                     };
                     p->Storage->Deactive(p);
                     DelDevice(p);
                     p = pp;
                 };
 //              if(DeviceData != NULL)
 //                  ErrH.Abort("Bad Device List");
             };
             if(vSetVangerFlag == 0){
                 n = uvsMakeNewGamerInEscave(uvsPoint->Pworld->escT[0]);
                 aciNewMechos(uvsMechosType_to_AciInt(n->Pmechos->type));
                 if(!aciPutItem(ACI_BOOT_SECTOR))
                     ErrH.Abort("Water Closet Droped");
                 vSetVangerFlag = -1;
                 g = new uvsItem(UVS_ITEM_TYPE::SECTOR);
                 aciGetItemCoords(ACI_BOOT_SECTOR,g->pos_x,g->pos_y);
                 n->addItem(g,1);
             }else{
                 i = 1;
                 l = (VangerUnit*)(ActD.Tail);
                 while(l){
                     if(l->uvsPoint->shape == UVS_VANGER_SHAPE::GAMER_SLAVE){
                         if(i == vSetVangerFlag) break;
                         else i++;
                     };
                     l = (VangerUnit*)(l->NextTypeList);
                 };
                 uvsMakeGamerFromSlave(l->uvsPoint);
                 if(!l) ErrH.Abort("Gamer Slave Not Found");
                 aciNewMechos(uvsMechosType_to_AciInt(l->uvsPoint->Pmechos->type));
             };
         }else{
             if(ChangeWorldConstraction != -1){
                 if(ActD.SpummyRunner){
                     p = DeviceData;
                     while(p){
                         pp = p->NextDeviceList;
                         ObjectDestroy(p);
                         CheckOutDevice(p);
                         ActD.CheckDevice(p);
                         aciRemoveItem(&(p->ActIntBuffer));
                         p->Storage->Deactive(p);
                         DelDevice(p);
                         p = pp;
                     };
                 }else{
                     if(DeviceData){
                         p = DeviceData;
                         while(p){
                             pp = p->NextDeviceList;
                             ObjectDestroy(p);
                             g = new uvsItem(p->uvsDeviceType);
                             aciGetItemCoords(&(p->ActIntBuffer),g->pos_x,g->pos_y);
                             g->param1 = p->ActIntBuffer.data0;
                             g->param2 = p->ActIntBuffer.data1;
                             uvsPoint->addItem(g,1);
                             p->Storage->Deactive(p);
                             DelDevice(p);
                             p = pp;
                         };
                     };
                 };
                 n = uvsMakeNewGamerInEscave(uvsPoint->Pworld->escT[0],0);
                 aciNewMechos(uvsMechosType_to_AciInt(n->Pmechos->type));
 /*              if(ActD.SpummyRunner){
                     if(!aciPutItem(ACI_SPUMMY))
                         ErrH.Abort("SPummy Must Die");
                     g = new uvsItem(UVS_ITEM_TYPE::SPUMMY);
                     aciGetItemCoords(ACI_SPUMMY,g->pos_x,g->pos_y);
                     n->addItem(g,1);
                 };*/
             }else{
                 p = DeviceData;
                 while(p){
                     pp = p->NextDeviceList;
                     ObjectDestroy(p);
                     g = new uvsItem(p->uvsDeviceType);
                     aciGetItemCoords(&(p->ActIntBuffer),g->pos_x,g->pos_y);
                     g->param1 = p->ActIntBuffer.data0;
                     g->param2 = p->ActIntBuffer.data1;
                     uvsPoint->addItem(g,1);
                     p->Storage->Deactive(p);
                     DelDevice(p);
                     p = pp;
                 };
 //              if(DeviceData != NULL)
 //                  ErrH.Abort("Bad Device List");
                 aciKillLinks();
             };
         };
     }else uvsUnitType::Go2Universe();
 #ifdef ITEM_LOG
     if(Status & SOBJ_ACTIVE){
         g = (uvsItem*)(uvsPoint->Pitem);
         while(g){
             xLog < "\n\nuvsType " <= ((uvsItem*)(g))->type;
             xLog < "\nuvsParam1 " <= ((uvsItem*)(g))->param1;
             xLog < "\nuvsParam2 " <= ((uvsItem*)(g))->param2;
             g = (uvsItem*)(g->next);
         };
     };
 #endif
     for(i = 0;i < ItemMatrix->NumSlot;i++)
         GunSlotData[ItemMatrix->nSlot[i]].CloseSlot();
     aiEvent.Free();
     aiResolveFind.Free();
     aiResolveAttack.Free();
     delete[] ItemMatrixData;
     delete MoleTool;
     delete MolePoint1;
     delete MolePoint2;
 };
References XErrorHandler::Abort(), ACI_BOOT_SECTOR, aciDropMoveItem(), aciGetItemCoords(), aciKillLinks(), aciNewMechos(), aciPutItem(), aciRemoveItem(), ActD, StuffObject::ActIntBuffer, uvsVanger::addItem(), aiEvent, aiResolveAttack, aiResolveFind, uvsUnitType::Armor, ChangeWorldConstraction, ActionDispatcher::CheckDevice(), CheckOutDevice(), GunSlot::CloseSlot(), actintItemData::data0, actintItemData::data1, StuffObject::Deactive(), uvsUnitType::DelDevice(), uvsUnitType::DeviceData, ErrH, uvsWorld::escT, aiListType::Free(), FreeList(), g, UVS_VANGER_SHAPE::GAMER_SLAVE, uvsUnitType::Go2Universe(), GunSlotData, iChatFinit(), ItemD, uvsUnitType::ItemMatrix, uvsUnitType::ItemMatrixData, ItemsDispatcher::LarvaHilator(), MolePoint1, MolePoint2, MoleTool, NetworkON, StuffObject::NextDeviceList, UnitItemMatrix::nSlot, UnitItemMatrix::NumSlot, ObjectDestroy(), uvsUnitType::PassageCount, uvsVanger::Pitem, uvsVanger::Pmechos, uvsVanger::Pworld, UVS_ITEM_TYPE::SECTOR, uvsVanger::shape, SOBJ_ACTIVE, ActionDispatcher::SpummyRunner, UnitList::Tail, uvsMechos::teleport, actintItemData::type, uvsMechos::type, StuffObject::uvsDeviceType, uvsMakeGamerFromSlave(), uvsMakeNewGamerInEscave(), uvsMechosType_to_AciInt(), uvsKernel::uvsPoint, and vSetVangerFlag.
Referenced by DeleteHandler(), and SensorQuant().
Go2World()
void VangerUnit::Go2World (void) virtual
Reimplemented from uvsUnitType.
 {
     int i;
     StuffObject* p;
     listElem* n;
     uvsItem* g;
     MoleTool = new dastPoly3D(Vector(0,0,0),Vector(0,0,0),Vector(0,0,0));
     MolePoint1 = new dastPoly3D(Vector(0,0,0),0,0);
     MolePoint2 = new dastPoly3D(Vector(0,0,0),0,0);
     ItemMatrixData = new int[ItemMatrix->FullNum];
     for(i = 0;i < ItemMatrix->FullNum;i++) ItemMatrixData[i] = 0;
     for(i = 0;i < MAX_ACTIVE_SLOT;i++){
         GunSlotData[i].pData = NULL;
         GunSlotData[i].Owner = NULL;
     };
     for(i = 0;i < ItemMatrix->NumSlot;i++)
         GunSlotData[ItemMatrix->nSlot[i]].OpenSlot(ItemMatrix->nSlot[i],this,ItemMatrix->nSlot[i]);
     aiEvent.Init();
     aiResolveFind.Init();
     aiResolveAttack.Init();
 #ifdef ITEM_LOG
     if(Status & SOBJ_ACTIVE){
         xLog < "\n\n\nGo2World";
         g = (uvsItem*)(uvsPoint->Pitem);
         while(g){
             xLog < "\n\nuvsType " <= ((uvsItem*)(g))->type;
             xLog < "\nuvsParam1 " <= ((uvsItem*)(g))->param1;
             xLog < "\nuvsParam2 " <= ((uvsItem*)(g))->param2;
             g = (uvsItem*)(g->next);
         };
     };
 #endif
     uvsUnitType::Go2World();
     if(vSetVangerFlag > 0 && (Status & SOBJ_ACTIVE)){
         Armor = uvsPoint->Pmechos->teleport & 0xffffff00;
         n = uvsPoint->Pitem;
         while(n){
             p = addDevice(((uvsItem*)(n))->pos_x,((uvsItem*)(n))->pos_y,0,((uvsItem*)(n))->type,((uvsItem*)(n))->param1,((uvsItem*)(n))->param2,this);
             if(!p)
                 ErrH.Abort("Stuff Memory Overflow");
 //          if(p->ActIntBuffer.type == ACI_BOOT_SECTOR)
 //              ErrH.Abort("Boot Sectot Error");
             if(!aciPutItem(p->ActIntBuffer.type,((uvsItem*)(n))->pos_x,((uvsItem*)(n))->pos_y))
                 ErrH.Abort("Bad Put Item");
             n = n->next;
         };
         p = DeviceData;
         while(p){
             p->ActIntBuffer.slot = -1;
 //          aciReInitItem(&p->ActIntBuffer);
             aciReInitItemXY(&p->ActIntBuffer,p->R_curr.x,p->R_curr.y);
             p = p->NextDeviceList;
         };
         g = new uvsItem(UVS_ITEM_TYPE::SECTOR);
         uvsPoint->addItem(g,1);
         if(!aciPutItem(ACI_BOOT_SECTOR))
             ErrH.Abort("Water Closet Droped");
         p = addDevice(0,0,0,g->type,g->param1,g->param2,this);
         p->ActIntBuffer.slot = -1;
         aciReInitItem(&p->ActIntBuffer);
     }else{
         //stalkerg
         n = uvsPoint->Pitem;
         while(n){
             if(addDevice(((uvsItem*)(n))->pos_x,((uvsItem*)(n))->pos_y,0,((uvsItem*)(n))->type,((uvsItem*)(n))->param1,((uvsItem*)(n))->param2,this) == NULL)
                 ErrH.Abort("Stuff Memory Overflow");
             n = n->next;
         };
         //stalkerg   !
         if(Status & SOBJ_ACTIVE){
             p = DeviceData;
             while(p){
                 p->ActIntBuffer.slot = -1;
                 if(!aciReInitItemXY(&p->ActIntBuffer,p->R_curr.x,p->R_curr.y)){
                     if(!aciPutItem(p->ActIntBuffer.type)){
                         uvsKronDeleteItem(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                         ObjectDestroy(p);
                         CheckOutDevice(p);
                         ActD.CheckDevice(p);
                         p->Storage->Deactive(p);
                         DelDevice(p);
                     };
                 };
                 p = p->NextDeviceList;
             };
         };
     };
     FreeList(uvsPoint->Pitem);
 #ifdef ITEM_LOG
     if(Status & SOBJ_ACTIVE){
         p = DeviceData;
         while(p){
             xLog < "\n\nuvsType " <= (int)(p->uvsDeviceType);
             xLog < "\nActIntType " <= (int)(p->ActIntBuffer.type);
             xLog < "\nActIntData0 " <= (int)(p->ActIntBuffer.data0);
             xLog < "\nActIntData1 " <= (int)(p->ActIntBuffer.data1);
             p = (StuffObject*)(p->NextDeviceList);
         };
     };
 #endif
 };
References XErrorHandler::Abort(), ACI_BOOT_SECTOR, aciPutItem(), aciReInitItem(), aciReInitItemXY(), ActD, StuffObject::ActIntBuffer, addDevice(), uvsVanger::addItem(), aiEvent, aiResolveAttack, aiResolveFind, uvsUnitType::Armor, ActionDispatcher::CheckDevice(), CheckOutDevice(), actintItemData::data0, actintItemData::data1, StuffObject::Deactive(), uvsUnitType::DelDevice(), uvsUnitType::DeviceData, ErrH, FreeList(), UnitItemMatrix::FullNum, g, uvsUnitType::Go2World(), GunSlotData, aiListType::Init(), uvsUnitType::ItemMatrix, uvsUnitType::ItemMatrixData, MAX_ACTIVE_SLOT, MolePoint1, MolePoint2, MoleTool, listElem::next, StuffObject::NextDeviceList, UnitItemMatrix::nSlot, NULL, UnitItemMatrix::NumSlot, ObjectDestroy(), GunSlot::OpenSlot(), GunSlot::Owner, GunSlot::pData, uvsVanger::Pitem, uvsVanger::Pmechos, UVS_ITEM_TYPE::SECTOR, actintItemData::slot, SOBJ_ACTIVE, uvsMechos::teleport, actintItemData::type, StuffObject::uvsDeviceType, uvsKronDeleteItem(), uvsKernel::uvsPoint, vSetVangerFlag, Object::x, and Object::y.
Referenced by CreateVangerUnit().
Hide2Show()
void VangerUnit::Hide2Show (void) virtual
Reimplemented from TrackUnit.
 {
     if(aiMoveMode == AI_MOVE_TRACK){
         if(pBranch){
             if(pNextLink) set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,pNextLink->z + zmax,0,-Angle,Speed);
 //          else ErrH.Abort("Bad Link in Hide2Show");
         }else{
             if(pNode) set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,pNode->z + zmax,0,-Angle,Speed);
 //          else ErrH.Abort("Bad TrackInfo in Hide2Show");
         };
     }else set_3D(SET_3D_CHOOSE_LEVEL,R_curr.x,R_curr.y,R_curr.z + zmax,0,-Angle,Speed);
 };
References AI_MOVE_TRACK, TrackUnit::aiMoveMode, ActionUnit::Angle, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, Object::set_3D(), SET_3D_CHOOSE_LEVEL, SET_3D_DIRECT_PLACE, ActionUnit::Speed, LinkType::z, NodeType::z, and Object::zmax.
HideAction()
void VangerUnit::HideAction (void)
 {
     DeltaSpeed = MaxHideSpeed;
     if(RND(100) < 20) DeltaSpeed = 1 - RND(2);
     MoveAngle = vDirect.psi();
     TrackUnit::HideAction();
 };
References ActionUnit::DeltaSpeed, ActionUnit::HideAction(), ActionUnit::MaxHideSpeed, ActionUnit::MoveAngle, Vector::psi(), RND(), and ActionUnit::vDirect.
Referenced by Quant().
InCarNator()
void VangerUnit::InCarNator (void)
 {
     StuffObject* p;
     listElem* n;
     n = uvsPoint->Pitem;
     while(n){
         addDevice(((uvsItem*)(n))->pos_x,((uvsItem*)(n))->pos_y,0,((uvsItem*)(n))->type,((uvsItem*)(n))->param1,((uvsItem*)(n))->param2,this);
         n = n->next;
     };
     if(Status & SOBJ_ACTIVE){
         p = DeviceData;
         while(p){
             p->ActIntBuffer.slot = -1;
             aciSendEvent2actint(ACI_PUT_ITEM,&(p->ActIntBuffer));
             p = p->NextDeviceList;
         };
     };
     FreeList(uvsPoint->Pitem);
 };
References ACI_PUT_ITEM, aciSendEvent2actint(), StuffObject::ActIntBuffer, addDevice(), uvsUnitType::DeviceData, FreeList(), listElem::next, StuffObject::NextDeviceList, uvsVanger::Pitem, actintItemData::slot, SOBJ_ACTIVE, and uvsKernel::uvsPoint.
Referenced by ChangeVangerProcess().
Init()
void VangerUnit::Init (StorageType * s)
 {
     ID = ID_VANGER;
     uvsUnitType::Init();
     TrackUnit::Init(s);
 };
References Object::ID, ID_VANGER, TrackUnit::Init(), and uvsUnitType::Init().
InitAI()
void VangerUnit::InitAI (void)
 {
     aiActionID = AI_ACTION_AUTO;
     aiStatus = AI_STATUS_NONE;
     aiNearTrack = Vector(0,0,0);
     aiLocalTarget = NULL;
     aiResolveWayEnable = 0;
     NoWayDirect = -1;
     aiScanDist = radius*3;
     aiRunBranch = NULL;
     aiRunNode = NULL;
     vRunStartPosition = Vector(0,0,0);
     RunStartDist = 0;
     RunTimeProcess = 0;
     ViewRadius = 300;
     aiMaxJumpRadius = max_jump_distance;
     uvsMaxSpeed = round((double)(TotalVangerSpeed)*speed_factor);
     MaxHideSpeed = uvsMaxSpeed;
     MakeTrackDist();
     NoWayEnable = AI_NO_WAY_NONE;
     aiReactionCheckTime = 0;
     aiReactionMode = 0;
     aiReactionTime = 0;
     aiReactionCheckTime = 0;
     aiReactionTimeMax = 30;
     aiReactionCheckTimeMax = 50;
     AttackRadius = 300;
     MixVectorEnable = 1;
     SeedNum = 0;
     MaxSeed = 5 + RND(10);
     LowAmmo = 0;
     LowArmor = 0;
     WallCollisionTime = 0;
     DeltaTractionTime = 0;
     TractionValue = 0;
     TractionStat = 0;
     SpeedFactorTime = 0;
     aiAlarmTime = 0;
     aiDamage = 0;
     aiDamageData = NULL;
     BeebonationFlag = 0;
     ArmorAlarm = 2*MaxArmor / 3;
     if((Status & SOBJ_AUTOMAT) && !NetworkON)
         WeaponGenerator();
     else
         GetWeaponDelta();
     AddAttackTime = 0;
     aiRelaxTime = 0;
     aiRealxRadius = radius*4;
     aiRelaxTimeMax = 4 * aiRealxRadius / uvsMaxSpeed;
     aiRelaxData = R_curr;
     switch(uvsPoint->shape){
         case UVS_VANGER_SHAPE::GAMER_SLAVE:
             aiVangerRadius = 400;
             aiItemRadius = 400;
             aiFirstItem = -1;
             aiSecondItem = -1;
             aiActionID = AI_ACTION_BRAKE;
             FactorOpen(&aiFactorData[AI_FACTOR_TRANSPORT]);
             FactorOpen(&aiFactorData[AI_FACTOR_ALARM_NORMAL]);
             FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
             FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
             break;
         case UVS_VANGER_SHAPE::GAMER:
             aiVangerRadius = 400;
             aiItemRadius = 400;
             aiFirstItem = -1;
             aiSecondItem = -1;
             aiActionID = AI_ACTION_AUTO;
             FactorOpen(&aiFactorData[AI_FACTOR_KILLER]);
             FactorOpen(&aiFactorData[AI_FACTOR_ALARM_GAMER]);
             FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
             FactorOpen(&aiFactorData[AI_FACTOR_OTHER_GAMER]);
             break;
         case UVS_VANGER_SHAPE::KILLER:
             aiVangerRadius = 400;
             aiItemRadius = 400;
             aiFirstItem = -1;
             aiSecondItem = -1;
             aiActionID = AI_ACTION_RANGER;
             FactorOpen(&aiFactorData[AI_FACTOR_KILLER]);
             FactorOpen(&aiFactorData[AI_FACTOR_ALARM_FREEZER]);
             FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
             FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
             break;
         case UVS_VANGER_SHAPE::THIEF:
             aiVangerRadius = 400;
             aiItemRadius = 400;
             aiFirstItem = -1;
             aiSecondItem = -1;
             aiActionID = AI_ACTION_THIEF;
             FactorOpen(&aiFactorData[AI_FACTOR_THIEF]);
             FactorOpen(&aiFactorData[AI_FACTOR_ALARM_FUNK]);
             FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
             FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
             break;
         default:
             if(PowerFlag & VANGER_POWER_RUFFA_GUN){
                 aiVangerRadius = 400;
                 aiItemRadius = 400;
                 aiFirstItem = -1;
                 aiSecondItem = -1;
                 aiActionID = AI_ACTION_RACER;
                 FactorOpen(&aiFactorData[AI_FACTOR_TRANSPORT]);
                 FactorOpen(&aiFactorData[AI_FACTOR_ALARM_FUNK]);
                 FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
                 FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
             }else{
                 switch(uvsPoint->status){
                     case UVS_VANGER_STATUS::RACE:
                         aiVangerRadius = 400;
                         aiItemRadius = 400;
                         aiFirstItem = ACI_ELEECH;
                         aiSecondItem = -1;
                         aiActionID = AI_ACTION_RACER;
                         FactorOpen(&aiFactorData[AI_FACTOR_RACER]);
                         FactorOpen(&aiFactorData[AI_FACTOR_ALARM_NORMAL]);
                         FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
                         FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
                         break;
                     case UVS_VANGER_STATUS::RACE_HUNTER:
                         aiVangerRadius = 400;
                         aiItemRadius = 400;
                         aiFirstItem = ACI_WEEZYK;
                         aiSecondItem = -1;
                         aiActionID = AI_ACTION_RACER;
                         FactorOpen(&aiFactorData[AI_FACTOR_RACER]);
                         FactorOpen(&aiFactorData[AI_FACTOR_ALARM_NORMAL]);
                         FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
                         FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
                         break;
                     default:
                         if(CurrentWorld == WORLD_GLORX && (uvsCurrentCycle == 1 || uvsCurrentCycle == 2) && !RND(3)){
                             aiVangerRadius = 400;
                             aiItemRadius = 400;
                             if(uvsCurrentCycle == 1) aiFirstItem = ACI_PIPETKA;
                             else aiFirstItem = ACI_KERNOBOO;
                             aiSecondItem = -1;
                             aiActionID = AI_ACTION_FARMER;
                             FactorOpen(&aiFactorData[AI_FACTOR_RACER]);
                             FactorOpen(&aiFactorData[AI_FACTOR_ALARM_NORMAL]);
                             FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
                             FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
                         }else{
                             if(uvsPoint->shape ==  UVS_VANGER_SHAPE::RANGER){
                                 aiVangerRadius = 400;
                                 aiItemRadius = 400;
                                 aiFirstItem = -1;
                                 aiSecondItem = -1;
                                 aiActionID = AI_ACTION_RANGER;
                                 FactorOpen(&aiFactorData[AI_FACTOR_RANGER]);
                                 FactorOpen(&aiFactorData[AI_FACTOR_ALARM_FREEZER]);
                                 FactorOpen(&aiFactorData[AI_FACTOR_TARGET_FREEZER]);
                                 FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
                             }else{
                                 aiVangerRadius = 400;
                                 aiItemRadius = 400;
                                 aiFirstItem = -1;
                                 aiSecondItem = -1;
                                 aiActionID = AI_ACTION_SLAVE;
                                 FactorOpen(&aiFactorData[AI_FACTOR_TRANSPORT]);
                                 FactorOpen(&aiFactorData[AI_FACTOR_ALARM_NORMAL]);
                                 FactorOpen(&aiFactorData[AI_FACTOR_TARGET_MONO]);
                                 FactorOpen(&aiFactorData[AI_FACTOR_OTHER]);
                             };
                         };
                         break;
                 };
             };
             break;
     };
     Molerizator = 0;
     VangerCloneID = 0;
 };
References ACI_ELEECH, ACI_KERNOBOO, ACI_PIPETKA, ACI_WEEZYK, AddAttackTime, AI_ACTION_AUTO, AI_ACTION_BRAKE, AI_ACTION_FARMER, AI_ACTION_RACER, AI_ACTION_RANGER, AI_ACTION_SLAVE, AI_ACTION_THIEF, AI_FACTOR_ALARM_FREEZER, AI_FACTOR_ALARM_FUNK, AI_FACTOR_ALARM_GAMER, AI_FACTOR_ALARM_NORMAL, AI_FACTOR_KILLER, AI_FACTOR_OTHER, AI_FACTOR_OTHER_GAMER, AI_FACTOR_RACER, AI_FACTOR_RANGER, AI_FACTOR_TARGET_FREEZER, AI_FACTOR_TARGET_MONO, AI_FACTOR_THIEF, AI_FACTOR_TRANSPORT, AI_NO_WAY_NONE, AI_STATUS_NONE, aiActionID, aiAlarmTime, aiDamage, aiDamageData, aiFactorData, aiFirstItem, aiItemRadius, aiLocalTarget, aiMaxJumpRadius, aiNearTrack, aiReactionCheckTime, aiReactionCheckTimeMax, aiReactionMode, aiReactionTime, aiReactionTimeMax, aiRealxRadius, aiRelaxData, aiRelaxTime, aiRelaxTimeMax, aiResolveWayEnable, aiRunBranch, aiRunNode, aiScanDist, aiSecondItem, aiStatus, aiVangerRadius, ArmorAlarm, AttackRadius, BeebonationFlag, CurrentWorld, DeltaTractionTime, aiFactorType::FactorOpen(), UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, GetWeaponDelta(), UVS_VANGER_SHAPE::KILLER, LowAmmo, LowArmor, TrackUnit::MakeTrackDist(), Object::max_jump_distance, uvsUnitType::MaxArmor, ActionUnit::MaxHideSpeed, MaxSeed, MixVectorEnable, Molerizator, NetworkON, TrackUnit::NoWayDirect, NoWayEnable, NULL, uvsUnitType::PowerFlag, UVS_VANGER_STATUS::RACE, UVS_VANGER_STATUS::RACE_HUNTER, Object::radius, UVS_VANGER_SHAPE::RANGER, RND(), round(), RunStartDist, RunTimeProcess, SeedNum, uvsVanger::shape, SOBJ_AUTOMAT, Object::speed_factor, SpeedFactorTime, uvsVanger::status, UVS_VANGER_SHAPE::THIEF, TotalVangerSpeed, TractionStat, TractionValue, uvsCurrentCycle, uvsUnitType::uvsMaxSpeed, uvsKernel::uvsPoint, VANGER_POWER_RUFFA_GUN, VangerCloneID, ActionUnit::ViewRadius, vRunStartPosition, WallCollisionTime, WeaponGenerator(), and WORLD_GLORX.
Referenced by ChangeVangerProcess(), and CreateVangerUnit().
InitEnvironment()
void VangerUnit::InitEnvironment (void) virtual
Reimplemented from ActionUnit.
 {
     StaticObject* st;
     int y0,y1;
     int l,i;
     Vector vTrack;
     Vector vOffset;
     Vector vCheck;
     GunSlot* s;
     BulletObject* g;
     aiUnitResolve* p;
     aiUnitResolve* pp;
     if(Status & SOBJ_WAIT_CONFIRMATION) return;
     nDoorFlag = DoorFlag;
     ActionUnit::InitEnvironment();
     vTarget = Vector(0,0,0);
     NumCalcUnit = 0;
     if(NetworkON){
         if(VangerChanger){
             if(Status & SOBJ_ACTIVE){
                 switch(VangerChangerCount){
                     case 3:
                         OutCarNator();
                         VangerChangerCount = 2;
                         break;
                     case 1:
                         if(NetChanger == 0xff){
                             if(VangerChanger->NetChanger == 0xff){
                                 VangerChanger->VangerChanger = NULL;
                                 VangerChanger->VangerChangerCount = 0;
                                 VangerChanger = NULL;
                                 VangerChangerCount = 0;
                                 NetChanger = 0;
                                 ShellUpdateFlag = 1;
                             };
                         }else{
                             ChangeVangerProcess();
                             NetChanger = 0xff;
                             ShellUpdateFlag = 1;
                         };
                         break;
                 };
             };
         };
         if(pNetPlayer && pNetPlayer->body.CarIndex != uvsPoint->Pmechos->type && !(Status & SOBJ_ACTIVE))
             ChangeVangerProcess();
     }else{
         if(VangerChanger && VangerChangerCount > 0){
             VangerChangerCount--;
             switch(VangerChangerCount){
                 case 1:
                     OutCarNator();
                     break;
                 case 0:
                     ChangeVangerProcess();
                     VangerChanger = NULL;
                     break;
             };
         };
     };
     if(!NetworkON || (Status & SOBJ_ACTIVE)){
         ExternalLastSensor = ExternalSensor;
         ExternalSensor = NULL;
         if(Visibility == VISIBLE){
             if(Status & SOBJ_AUTOMAT){
                 if(aiActionID == AI_ACTION_BRAKE){
                     y0 = R_curr.y - radius - MAX_SENSOR_RADIUS;
                     y1 = R_curr.y + radius + MAX_SENSOR_RADIUS;
                     i = FindFirstStatic(y0,y1,(StaticObject**)SensorSortedData,SnsTableSize);
                     if(i > -1){
                         do{
                             st = SensorSortedData[i];
                             vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                             l = radius + st->radius;
                             if(abs(vCheck.x) < l){
                                 if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z < ((SensorDataType*)(st))->z1 + radius){
                                     vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                     if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l)
                                         StopTouchSensor((SensorDataType*)st);
                                 };
                             };
                             i++;
                         }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
                     };
                     if(TouchKeyObjectFlag)  TouchKeyObject = NULL;
                     else TouchKeyObjectFlag = 1;
                 }else{
                     ResolveGenerator();
                     NoWayHandler();
                     p = (aiUnitResolve*)(aiResolveFind.Tail);
                     while(p){
                         if(!(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT))
                             ResolveHandlerFind(p);
                         p = (aiUnitResolve*)(p->Next);
                     };
                     p = (aiUnitResolve*)(aiResolveAttack.Tail);
                     while(p){
                         if(!(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT))
                             ResolveHandlerAttack(p);
                         p = (aiUnitResolve*)(p->Next);
                     };
                     p = (aiUnitResolve*)(aiResolveFind.Tail);
                     while(p){
                         pp = (aiUnitResolve*)(p->Next);
                         if(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT){
                             if(p == aiLocalTarget) aiLocalTarget = NULL;
                             aiResolveFind.Disconnect(p);
                             delete p;
                         };
                         p = pp;
                     };
                     p = (aiUnitResolve*)(aiResolveAttack.Tail);
                     while(p){
                         pp = (aiUnitResolve*)(p->Next);
                         if(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT){
                             if(p == aiLocalTarget) aiLocalTarget = NULL;
                             aiResolveAttack.Disconnect(p);
                             delete p;
                         };
                         p = pp;
                     };
                     if(!mole_on && !SensorEnable){
                         y0 = R_curr.y - radius - MAX_SENSOR_RADIUS;
                         y1 = R_curr.y + radius + MAX_SENSOR_RADIUS;
                         i = FindFirstStatic(y0,y1,(StaticObject**)SensorSortedData,SnsTableSize);
                         if(i > -1){
                             do{
                                 st = SensorSortedData[i];
                                 vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                                 l = radius + st->radius;
                                 if(abs(vCheck.x) < l){
                                     if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z < ((SensorDataType*)(st))->z1 + radius){
                                         vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                         if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l)
                                             AutomaticTouchSensor((SensorDataType*)st);
                                     };
                                 };
                                 i++;
                             }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
                         };
                     };
                     if(TouchKeyObjectFlag)  TouchKeyObject = NULL;
                     else TouchKeyObjectFlag = 1;
                     if(aiStatus & AI_STATUS_TNT){
                         if(PowerFlag & VANGER_POWER_RUFFA_GUN){
                             if(RuffaGunTime > (RUFFA_GUN_WAIT * WeaponWaitTime >> 8)){
                                 RuffaGunTime = 0;
                                 g = BulletD.CreateBullet();
                                 vCheck = Vector(64,0,0)*RotMat;
                                 g->CreateBullet(Vector(R_curr.x,R_curr.y,R_curr.z),
                                     Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),NULL,&GameBulletData[WD_BULLET_RUFFA],this,Speed);
                                 if(ActD.Active)
                                     SOUND_RAFFA_SHOT(getDistX(ActD.Active->R_curr.x,R_curr.x));
                             };
                         }else{
                             s = NULL;
                             l = -1;
                             for(i = 0;i < ItemMatrix->NumSlot;i++){
                                 if(GunSlotData[ItemMatrix->nSlot[i]].pData && (GunSlotData[ItemMatrix->nSlot[i]].pData->BulletMode & BULLET_CONTROL_MODE::FLY) && (GunSlotData[ItemMatrix->nSlot[i]].pData->Power < l || l == -1)){
                                     s = &GunSlotData[ItemMatrix->nSlot[i]];
                                     l = GunSlotData[ItemMatrix->nSlot[i]].pData->Power;
                                 };
                             };
                             if(s) s->Fire();
                         };
                     };
                 };
             }else{
                 y0 = R_curr.y - radius - MAX_SENSOR_RADIUS;
                 y1 = R_curr.y + radius + MAX_SENSOR_RADIUS;
                 if(mole_on) i = -1;
                 else i = FindFirstStatic(y0,y1,(StaticObject**)SensorSortedData,SnsTableSize);
                 switch(CurrentWorld){
                     case WORLD_HMOK:
                         if(ActD.hMokKeyEnable && i > -1){
                             do{
                                 st = SensorSortedData[i];
                                 if(st->Enable){
                                     vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                                     l = radius + st->radius;
                                     if(abs(vCheck.x) < l){
                                         if(R_curr.z  > ((SensorDataType*)(st))->z0 - radius && R_curr.z < ((SensorDataType*)(st))->z1 + radius){
                                             vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                             if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                                 st->Touch(this);
                                                 TouchSensor((SensorDataType*)st);
                                             };
                                         };
                                     };
                                 };
                                 i++;
                             }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
                         };
                         break;
                     case WORLD_KHOX:
                         if(i > -1){
                             do{
                                 st = SensorSortedData[i];
                                 if(st->Enable){
                                     vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                                     l = radius + st->radius;
                                     if(abs(vCheck.x) < l){
                                         if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z  < ((SensorDataType*)(st))->z1 + radius){
                                             if(!strcmp(((SensorDataType*)(st))->Name,"UniDoor")){
                                                 if(CheckPointCount >= MAX_KHOX_CHECKPOINT){
                                                     vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                                     if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                                         st->Touch(this);
                                                         TouchSensor((SensorDataType*)st);
                                                     };
                                                 };
                                             }else{
                                                 vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                                 if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                                     st->Touch(this);
                                                     TouchSensor((SensorDataType*)st);
                                                 };
                                             };
                                         };
                                     };
                                 };
                                 i++;
                             }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
                         };
                         break;
                     case WORLD_XPLO:
                         ActD.SpobsEntrance = 0;
                         if(i > -1){
                             do{
                                 st = SensorSortedData[i];
                                 if(st->Enable){
                                     vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                                     l = radius + st->radius;
                                     if(abs(vCheck.x) < l){
                                         if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z < ((SensorDataType*)(st))->z1 + radius){
                                             if(!strcmp(((SensorDataType*)(st))->Name,"SpotDoor1") || !strcmp(((SensorDataType*)(st))->Name,"SpotDoor2")){
                                                 if(ActD.XploKeyEnable){
                                                     vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                                     if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                                         st->Touch(this);
                                                         TouchSensor((SensorDataType*)st);
                                                         ActD.SpobsEntrance = 1;
                                                     };
                                                 };
                                                 aiMessageQueue.Send(AI_MESSAGE_SPOBS,Speed);//aiMessageData[AI_MESSAGE_SPOBS].Send(Speed);
                                             }else{
                                                  if(strcmp(((SensorDataType*)(st))->Name,"Spot1") || (!(ActD.FunctionSpobsDestroyActive) && !(ActD.SpobsDestroy) && ActD.XploKeyEnable)){
                                                     vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                                     if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                                         if(((SensorDataType*)(st))->data6) aiMessageTouch(Speed,((SensorDataType*)(st))->data6 - 1);
                                                         st->Touch(this);
                                                         TouchSensor((SensorDataType*)st);
                                                     };
                                                 };
                                             };
                                         };
                                     };
                                 };
                                 i++;
                             }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
                         };
                         if(ActD.SpobsEntrance){
                             if(!ActD.CameraModifier){
                                 camera_direct(1650,820,1 << 8,0,0,20);
                                 ActD.CameraModifier = 20;
                             }else{
                                 if(ActD.CameraModifier == 1){
                                     camera_direct(1650,820,1 << 8,0,0,1);
                                 }else ActD.CameraModifier--;
                             };
                         }else{
                             if(ActD.CameraModifier){
                                 camera_direct(R_curr.x,R_curr.y,1 << 8,0,0,20);
                                 ActD.CameraModifier = 0;
                             };
                         };
                         break;
                     case WORLD_THREALL:
                         if(i > -1){
                             do{
                                 st = SensorSortedData[i];
                                 if(st->Enable){
                                     vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                                     l = radius + st->radius;
                                     if(abs(vCheck.x) < l){
                                         if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z < ((SensorDataType*)(st))->z1 + radius){
                                             if(!strcmp(((SensorDataType*)(st))->Name,"SIGN")){
                                                 if(!NetworkON && ActD.Active && ActD.Active->ExternalMode == EXTERNAL_MODE_NORMAL && ActD.Active->ExternalDraw && !ActD.ThreallDestroy){
                                                     vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                                     if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                                         st->Touch(this);
                                                         TouchSensor((SensorDataType*)st);
                                                     };
                                                 };
                                             }else{
                                                 vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                                 if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                                     if(((SensorDataType*)(st))->data6) aiMessageTouch(Speed,((SensorDataType*)(st))->data6 - 1);
                                                     st->Touch(this);
                                                     TouchSensor((SensorDataType*)st);
                                                 };
                                             };
                                         };
                                     };
                                 };
                                 i++;
                             }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
                         };
                         break;
                     default:
                         if(i > -1){
                             do{
                                 st = SensorSortedData[i];
                                 vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                                 l = radius + st->radius;
                                 if(abs(vCheck.x) < l){
                                     if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z < ((SensorDataType*)(st))->z1 + radius){
                                         vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                         if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                             if(((SensorDataType*)(st))->data6) aiMessageTouch(Speed,((SensorDataType*)(st))->data6 - 1);
                                             if(st->Enable){
                                                 st->Touch(this);
                                                 TouchSensor((SensorDataType*)st);
                                             };
                                         };
                                     };
                                 };
                                 i++;
                             }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
                         };
                         break;
                 };
             };
         }else{
             if(aiActionID != AI_ACTION_BRAKE){
                 ResolveGenerator();
                 NoWayHandler();
                 p = (aiUnitResolve*)(aiResolveFind.Tail);
                 while(p){
                     if(!(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT))
                         ResolveHandlerFind(p);
                     p = (aiUnitResolve*)(p->Next);
                 };
                 p = (aiUnitResolve*)(aiResolveAttack.Tail);
                 while(p){
                     if(!(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT))
                         ResolveHandlerAttack(p);
                     p = (aiUnitResolve*)(p->Next);
                 };
                 p = (aiUnitResolve*)(aiResolveFind.Tail);
                 while(p){
                     pp = (aiUnitResolve*)(p->Next);
                     if(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT){
                         if(p == aiLocalTarget) aiLocalTarget = NULL;
                         aiResolveFind.Disconnect(p);
                         delete p;
                     };
                     p = pp;
                 };
                 p = (aiUnitResolve*)(aiResolveAttack.Tail);
                 while(p){
                     pp = (aiUnitResolve*)(p->Next);
                     if(p->rStatus & AI_RESOLVE_STATUS_DISCONNECT){
                         if(p == aiLocalTarget) aiLocalTarget = NULL;
                         aiResolveAttack.Disconnect(p);
                         delete p;
                     };
                     p = pp;
                 };
             };
             y0 = R_curr.y - radius - MAX_SENSOR_RADIUS;
             y1 = R_curr.y + radius + MAX_SENSOR_RADIUS;
             i = FindFirstStatic(y0,y1,(StaticObject**)KeySensorSorted,NumKeySensor);
             if(i > -1){
                 do{
                     st = KeySensorSorted[i];
                     if(st->Enable){
                         vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                         l = radius + st->radius;
                         if(abs(vCheck.x) < l){
                             vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                             if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l){
                                 st->Touch(this);
                                 if(ExternalSensor){
                                     if(ExternalSensor == ExternalObject && ExternalObject != st) ExternalSensor = (SensorDataType*)(st);
                                 }else ExternalSensor = (SensorDataType*)(st);
                             };
                         };
                     };
                     i++;
                 }while(i < NumKeySensor && KeySensorSorted[i]->R_curr.y < y1);
             };
         };
     }else{
         if(Visibility == VISIBLE){
             ActD.NumVisibleVanger++;
             y0 = R_curr.y - radius - MAX_SENSOR_RADIUS;
             y1 = R_curr.y + radius + MAX_SENSOR_RADIUS;
             i = FindFirstStatic(y0,y1,(StaticObject**)SensorSortedData,SnsTableSize);
             if(i > -1){
                 do{
                     st = SensorSortedData[i];
                     if(st->Enable){
                         vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                         l = radius + st->radius;
                         if(abs(vCheck.x) < l){
                             if(R_curr.z > ((SensorDataType*)(st))->z0 - radius && R_curr.z < ((SensorDataType*)(st))->z1 + radius){
                                 vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                                 if((vCheck.x*vCheck.x + vCheck.y*vCheck.y) < l*l)
                                     st->Touch(this);
                             };
                         };
                     };
                     i++;
                 }while(i < SnsTableSize && SensorSortedData[i]->R_curr.y < y1);
             };
         };
     };
 /*  if(Visibility == VISIBLE){
         p = (ActionUnit*)(ActD.Tail);
         if(Status & SOBJ_AUTOMAT){
             while(p){
                 if(p != this && p->Visibility == VISIBLE){
                     dy = getDistY(p->R_curr.y,R_curr.y);
                     if(abs(dy) < ViewRadius){
                         dx = getDistX(p->R_curr.x,R_curr.x);
                         if(abs(dx) < ViewRadius){
                             switch(p->ID){
                                 case ID_VANGER:
                                     r = (int)(sqrt(dx*(double)dx + dy*(double)dy));
                                     if(r > 0){
                                         PointDist(-dx,-dy,R_curr.z - p->R_curr.z,r,2*radius + p->radius,1,vUp,vTarget);
                                         NumCalcUnit++;
                                     };
                                     break;
                             };
                         };
                     };
                 };
                 p = (ActionUnit*)(p->NextTypeList);
             };
         };
     };*/
 };
References ActD, ActionDispatcher::Active, AI_ACTION_BRAKE, AI_MESSAGE_SPOBS, AI_RESOLVE_STATUS_DISCONNECT, AI_STATUS_TNT, aiActionID, aiLocalTarget, aiMessageQueue, aiMessageTouch(), aiResolveAttack, aiResolveFind, aiStatus, AutomaticTouchSensor(), PlayerData::body, BulletD, BulletControlType::BulletMode, camera_direct(), ActionDispatcher::CameraModifier, PlayerBody::CarIndex, ChangeVangerProcess(), CheckPointCount, BulletList::CreateBullet(), CurrentWorld, aiListType::Disconnect(), DoorFlag, StaticObject::Enable, EXTERNAL_MODE_NORMAL, ExternalDraw, ExternalLastSensor, ExternalMode, ExternalObject, ExternalSensor, FindFirstStatic(), GunSlot::Fire(), BULLET_CONTROL_MODE::FLY, ActionDispatcher::FunctionSpobsDestroyActive, g, GameBulletData, getDistX(), getDistY(), GunSlotData, ActionDispatcher::hMokKeyEnable, ActionUnit::InitEnvironment(), uvsUnitType::ItemMatrix, KeySensorSorted, MAX_KHOX_CHECKPOINT, MAX_SENSOR_RADIUS, Object::mole_on, nDoorFlag, NetChanger, NetworkON, aiListElement::Next, NoWayHandler(), UnitItemMatrix::nSlot, NULL, ActionUnit::NumCalcUnit, NumKeySensor, UnitItemMatrix::NumSlot, ActionDispatcher::NumVisibleVanger, OutCarNator(), GunSlot::pData, uvsVanger::Pmechos, pNetPlayer, BulletControlType::Power, uvsUnitType::PowerFlag, GeneralObject::R_curr, Object::radius, StaticObject::radius, ResolveGenerator(), ResolveHandlerAttack(), ResolveHandlerFind(), ActionUnit::RotMat, aiUnitResolve::rStatus, RUFFA_GUN_WAIT, RuffaGunTime, aiMessageList::Send(), SensorEnable, SensorSortedData, ShellUpdateFlag, SnsTableSize, SOBJ_ACTIVE, SOBJ_AUTOMAT, SOBJ_WAIT_CONFIRMATION, SOUND_RAFFA_SHOT, ActionUnit::Speed, ActionDispatcher::SpobsDestroy, ActionDispatcher::SpobsEntrance, StopTouchSensor(), aiListType::Tail, ActionDispatcher::ThreallDestroy, GeneralObject::Touch(), TouchKeyObject, TouchKeyObjectFlag, TouchSensor(), uvsMechos::type, uvsKernel::uvsPoint, VANGER_POWER_RUFFA_GUN, VangerChanger, VangerChangerCount, VISIBLE, TrackUnit::vTarget, WD_BULLET_RUFFA, WeaponWaitTime, WORLD_HMOK, WORLD_KHOX, WORLD_THREALL, WORLD_XPLO, Object::x, Vector::x, XCYCL, ActionDispatcher::XploKeyEnable, Vector::y, YCYCL, and Vector::z.
InitPlayerPoint()
void VangerUnit::InitPlayerPoint (PlayerData * p)
 {
     int i;
     uvsPoint->status = UVS_VANGER_STATUS::MOVEMENT;
     NetID = p->body.NetID;
     ShellNetID = (NetID & (~(63 << 16))) | NID_SHELL;
     pNetPlayer = p;
     p->CreatePlayerFlag = 2;
     for(i = 0;i < MAX_ACTIVE_SLOT;i++){
         if(p->SlotNetID[i]){
             GunSlotData[i].NetID = p->SlotNetID[i];
             GunSlotData[i].StuffNetID = p->SlotStuffNetID[i];
             GunSlotData[i].NetFireCount = p->SlotFireCount[i];
             if(Visibility == UNVISIBLE) GunSlotData[i].FireCount = GunSlotData[i].NetFireCount;
         };
     };
     Status |= SOBJ_WAIT_CONFIRMATION;
     AddFree();
     AddPhantomTarget(p);
 };
References AddFree(), AddPhantomTarget(), PlayerData::body, PlayerData::CreatePlayerFlag, GunSlot::FireCount, GunSlotData, MAX_ACTIVE_SLOT, UVS_VANGER_STATUS::MOVEMENT, GunSlot::NetFireCount, PlayerBody::NetID, GunSlot::NetID, NID_SHELL, pNetPlayer, ShellNetID, PlayerData::SlotFireCount, PlayerData::SlotNetID, PlayerData::SlotStuffNetID, SOBJ_WAIT_CONFIRMATION, uvsVanger::status, GunSlot::StuffNetID, UNVISIBLE, and uvsKernel::uvsPoint.
Referenced by CheckPlayerList().
ItemQuant()
void VangerUnit::ItemQuant (void) virtual
Reimplemented from uvsUnitType.
 {
     StuffObject* p;
     StuffObject* pp;
     actintItemData* n;
     int i;
     if(!VangerChanger){
         if(NetworkON && !(Status & SOBJ_ACTIVE)){
             for(i = 0;i < ItemMatrix->NumSlot;i++){
                 GunSlotData[ItemMatrix->nSlot[i]].NetStuffQuant();
                 if(GunSlotData[ItemMatrix->nSlot[i]].pData)
                     GunSlotData[ItemMatrix->nSlot[i]].Quant();
             };
             if(Armor <= 0) Destroy();
         }else{
             if(Armor <= 0){
                 if(DeviceData){
                     p = DeviceData;
                     while(p){
                         pp = (StuffObject*)(p->NextDeviceList);
                         DestroyItem(p);
                         p = pp;
                     };
                 };
                 Destroy();
             }else{
                 if(Energy < MaxEnergy){
                     Energy += dEnergy;
                     if(Energy >= MaxEnergy) Energy = MaxEnergy;
                     else{
                         DropTime--;
                         if(Energy < DropEnergy){
                             if(DropTime <= 0){
                                 DropTime = DelayDrop;
                                 if(DeviceData){
                                     if(Status & SOBJ_ACTIVE){
                                         n = aciGetLast();
                                         if((StuffObject*)(n->stuffOwner)) DischargeItem((StuffObject*)(n->stuffOwner));
                                     }else DischargeItem(DeviceData);
                                 };
                             };
                         };
                     };
                 }else Energy = MaxEnergy;
                 for(i = 0;i < MAX_ACTIVE_SLOT;i++)
                     if(GunSlotData[i].pData)
                         GunSlotData[i].Quant();
             };
         };
         if(NetworkON){
             p = DeviceData;
             if(Status & SOBJ_ACTIVE){
                 while(p){
                     pp = p->NextDeviceList;
                     if(p->Status & SOBJ_WAIT_CONFIRMATION) p->NetOwnerQuant();
                     else{
                         switch(p->ActIntBuffer.type){
                             case ACI_GLUEK:
                                 if(Armor < MaxArmor / 2){
                                     Armor += 10 << 16;
                                     ObjectDestroy(p);
                                     if(Status & SOBJ_ACTIVE){
                                         aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                                         ActD.CheckDevice(p);
                                     };
                                     CheckOutDevice(p);
                                     p->Storage->Deactive(p);
                                     DelDevice(p);
                                 };
                                 break;
                             default:
                                 p->DeviceQuant();
                                 break;
                         };
                         p = pp;
                     };
                 };
             }else{
                 while(p){
                     pp = p->NextDeviceList;
                     if(p->Status & SOBJ_WAIT_CONFIRMATION)
                         p->NetOwnerQuant();
                     p->DeviceQuant();
                     p = pp;
                 };
             };
         }else{
             p = DeviceData;
             while(p){
                 pp = p->NextDeviceList;
                 switch(p->ActIntBuffer.type){
                     case ACI_GLUEK:
                         if(Armor < MaxArmor / 2){
                             Armor += 10 << 16;
                             ObjectDestroy(p);
                             if(Status & SOBJ_ACTIVE){
                                 aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                                 ActD.CheckDevice(p);
                             };
                             CheckOutDevice(p);
                             p->Storage->Deactive(p);
                             DelDevice(p);
                         };
                         break;
                     default:
                         p->DeviceQuant();
                         break;
                 };
                 p = pp;
             };
         };
     };
 };
References ACI_DROP_ITEM, ACI_GLUEK, aciGetLast(), aciSendEvent2actint(), ActD, StuffObject::ActIntBuffer, uvsUnitType::Armor, ActionDispatcher::CheckDevice(), CheckOutDevice(), StuffObject::Deactive(), uvsUnitType::DelayDrop, uvsUnitType::DelDevice(), uvsUnitType::dEnergy, Destroy(), DestroyItem(), uvsUnitType::DeviceData, StuffObject::DeviceQuant(), DischargeItem(), uvsUnitType::DropEnergy, uvsUnitType::DropTime, uvsUnitType::Energy, GunSlotData, uvsUnitType::ItemMatrix, MAX_ACTIVE_SLOT, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, StuffObject::NetOwnerQuant(), GunSlot::NetStuffQuant(), NetworkON, StuffObject::NextDeviceList, UnitItemMatrix::nSlot, UnitItemMatrix::NumSlot, ObjectDestroy(), GunSlot::pData, GunSlot::Quant(), SOBJ_ACTIVE, SOBJ_WAIT_CONFIRMATION, actintItemData::stuffOwner, actintItemData::type, and VangerChanger.
Referenced by Quant().
keyhandler()
void VangerUnit::keyhandler (int key) virtual
Reimplemented from ActionUnit.
 {
     Vector vCheck;
     BulletObject* g;
     SDL_Keymod mod;
     switch(key){
         case SDL_SCANCODE_1:
             DbgCheckEnable ^= 1;
             ActD.ActiveSlot(0);
             break;
         case SDL_SCANCODE_2:
             ActD.ActiveSlot(1);
             break;
         case SDL_SCANCODE_3:
             ActD.ActiveSlot(2);
             break;
         case SDL_SCANCODE_4:
             ActD.ActiveSlot(3);
             break;
         case SDL_SCANCODE_LCTRL:
         case SDL_SCANCODE_RCTRL:
             if(PowerFlag & VANGER_POWER_RUFFA_GUN){
                 if(RuffaGunTime > (RUFFA_GUN_WAIT * WeaponWaitTime >> 8)){
                     RuffaGunTime = 0;
                     g = BulletD.CreateBullet();
                     vCheck = Vector(64,0,0)*RotMat;
                     g->CreateBullet(Vector(R_curr.x,R_curr.y,R_curr.z),
                         Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),NULL,&GameBulletData[WD_BULLET_RUFFA],this,Speed);
                     if(ActD.Active)
                         SOUND_MACHOTINE_SHOT(getDistX(ActD.Active->R_curr.x,R_curr.x));
                 };
             }else ActD.ActiveAllSlots();
             break;
         case SDL_SCANCODE_TAB:
             ActD.ChangeLocator();
             break;
         case SDL_SCANCODE_SPACE:
             DoorFlag = 1;
             break;
         case SDL_SCANCODE_5:
             start_vibration();
             //Explosion(R_curr,64,nModel);
             camera_impulse(512);
             break;
         case SDL_SCANCODE_7: {
             static int i_model = 0;
             static int models[2] = {0,0};
             mod = SDL_GetModState();
             if(!(mod&KMOD_CTRL)){
                 if(!(mod&KMOD_SHIFT)){
                     if(++NumHumanModel >= ModelD.MaxModel)
                         NumHumanModel = 0;
                     }
                 else{
                     if(--NumHumanModel < 0)
                         NumHumanModel =  ModelD.MaxModel - 1;
                     }
                 models[i_model] = NumHumanModel;
                 }
             else
                 NumHumanModel = models[i_model = 1 - i_model];
             Object::operator = (ModelD.ActiveModel(NumHumanModel));
             cycleTor(R_curr.x,R_curr.y);
             set_active(1);
             set_3D(SET_3D_TO_THE_UPPER_LEVEL,R_curr.x,R_curr.y,R_curr.z,0,-Angle,Speed);
             }
             break;
     };
 };
References ActD, ActionDispatcher::Active, ActionDispatcher::ActiveAllSlots(), ModelDispatcher::ActiveModel(), ActionDispatcher::ActiveSlot(), ActionUnit::Angle, BulletD, camera_impulse(), ActionDispatcher::ChangeLocator(), BulletList::CreateBullet(), cycleTor(), DbgCheckEnable, DoorFlag, g, GameBulletData, getDistX(), Object::i_model, key(), ModelDispatcher::MaxModel, ModelD, Object::models, NULL, NumHumanModel, Object::operator=(), uvsUnitType::PowerFlag, ActionUnit::RotMat, RUFFA_GUN_WAIT, RuffaGunTime, Object::set_3D(), SET_3D_TO_THE_UPPER_LEVEL, Object::set_active(), SOUND_MACHOTINE_SHOT, ActionUnit::Speed, start_vibration(), VANGER_POWER_RUFFA_GUN, WD_BULLET_RUFFA, WeaponWaitTime, Object::x, Vector::x, XCYCL, Vector::y, YCYCL, and Vector::z.
Referenced by ActionDispatcher::keyhandler().
LocalScan()
void VangerUnit::LocalScan (void)
MainOrderInit()
void VangerUnit::MainOrderInit (void)
 {
     uvsTarget* g;
     aiUnitResolve* p;
     if(aiActionID == AI_ACTION_FARMER && SeedNum < MaxSeed){
         (p = AddFindResolve(UNIT_ORDER_VECTOR,UnitOrderType(RND(clip_mask_x),300 + RND(clip_mask_y - 600),0),0,AI_RESOLVE_STATUS_VIEW))->Time = MaxWayCount;
     }else{
         p = NULL;
         switch(uvsPoint->getOrder(g)){
             case UVS_TARGET::ESCAVE:
                 (p = AddFindResolve(UNIT_ORDER_ENTER,g->unitPtr))->Time = MaxWayCount;
                 break;
             case UVS_TARGET::SPOT:
                 (p = AddFindResolve(UNIT_ORDER_ENTER,g->unitPtr))->Time = MaxWayCount;
                 break;
             case UVS_TARGET::PASSAGE:
                 (p = AddFindResolve(UNIT_ORDER_PASSAGE,g->unitPtr))->Time = MaxWayCount;
                 break;
             case UVS_TARGET::DOLLY:
                 (p = AddFindResolve(UNIT_ORDER_DOLL,UnitOrderType((uvsDolly*)(g))))->Time = MaxWayCount;
                 break;
             case UVS_TARGET::VANGER:
                 if(ActD.Active){
                     (p = AddFindResolve(UNIT_ORDER_VANGER,ActD.Active))->Time = MaxWayCount;
                     aiResolveAttack.AddResolve(UNIT_ORDER_VANGER,ActD.Active);
                 }else
                     (p = AddFindResolve(UNIT_ORDER_VECTOR,UnitOrderType(RND(clip_mask_x),300 + RND(clip_mask_y - 600),0),0,AI_RESOLVE_STATUS_VIEW))->Time = MaxWayCount;
                 break;
             case UVS_TARGET::ITEM:
                 (p = AddFindResolve(UNIT_ORDER_PASSAGE,g->unitPtr))->Time = MaxWayCount;
                 break;
             default:
                 (p = AddFindResolve(UNIT_ORDER_VECTOR,UnitOrderType(RND(clip_mask_x),300 + RND(clip_mask_y - 600),0),0,AI_RESOLVE_STATUS_VIEW))->Time = MaxWayCount;
                 break;
         };
     };
 };
References ActD, ActionDispatcher::Active, AddFindResolve(), aiResolveList::AddResolve(), AI_ACTION_FARMER, AI_RESOLVE_STATUS_VIEW, aiActionID, aiResolveAttack, clip_mask_x, clip_mask_y, UVS_TARGET::DOLLY, UVS_TARGET::ESCAVE, g, UVS_TARGET::ITEM, MaxSeed, TrackUnit::MaxWayCount, NULL, UVS_TARGET::PASSAGE, RND(), SeedNum, UVS_TARGET::SPOT, UNIT_ORDER_DOLL, UNIT_ORDER_ENTER, UNIT_ORDER_PASSAGE, UNIT_ORDER_VANGER, UNIT_ORDER_VECTOR, uvsKernel::uvsPoint, and UVS_TARGET::VANGER.
Referenced by CalcAiFactor(), and ResolveGenerator().
MapQuant()
void VangerUnit::MapQuant (void)
 {
     if((mole_on == 256 && (dynamic_state & TOUCH_OF_AIR)) || Molerizator)
         MolePoint1->make_first_mole();
     if(MoleInProcess)
         MoleProcessQuant();
     if(LastMole == 256 && mole_on != 256){
         MolePoint2->set(R_curr,40,radius < 40 ? radius : 40);
         SensorEnable = 20;
     }else{
         if(SensorEnable > 0)
             SensorEnable--;
     };
     MolePoint2->make_first_mole();
     LastMole = mole_on;
 };
References LastMole, dastPoly3D::make_first_mole(), Object::mole_on, Object::MoleInProcess, MolePoint1, MolePoint2, MoleProcessQuant(), Molerizator, Object::radius, SensorEnable, dastPoly3D::set(), and TOUCH_OF_AIR.
Referenced by GameObjectDispatcher::Quant().
MoleProcessQuant()
void VangerUnit::MoleProcessQuant (void)
 {
     Vector left_border,right_border;
     double dx = xmax_real;
     Vector delta(round(A_l2g[0]*dx),round(A_l2g[1]*dx),round(A_l2g[2]*dx));
     if(sqrt((double)(sqr(R_curr.x - R_prev.x) + sqr(R_curr.y - R_prev.y))) > 2){
         MoleTool->set(R_curr - delta, R_curr + delta,Vector(0,0,0));
         MoleTool->make_mole();
         }
 };
References Object::A_l2g, dastPoly3D::make_mole(), MoleTool, round(), dastPoly3D::set(), sqr(), and Object::xmax_real.
Referenced by MapQuant().
NetCreateSlave()
void VangerUnit::NetCreateSlave (void)
 {
     DoorFlag = nDoorFlag = 0;
 //  Visibility = VISIBLE;
 };
References DoorFlag, and nDoorFlag.
Referenced by addVanger().
NetCreateVanger()
void VangerUnit::NetCreateVanger (uvsPassage * pp, uvsEscave * pe, uvsSpot * ps)
 {
     //zNfo NetCreateVanger
     //NETWORK_OUT_STREAM.set_position(ViewX,ViewY,round(2.*(fabs(curGMap -> xsize*sinTurnInvFlt) + fabs(curGMap -> ysize*cosTurnInvFlt))*0.5));
     NETWORK_OUT_STREAM.create_permanent_object(NetID,R_curr.x,R_curr.y,radius);
     int scr_size = round((fabs(curGMap -> xsize*sinTurnInvFlt) + fabs(curGMap -> ysize*cosTurnInvFlt))*.5);
     NETWORK_OUT_STREAM < (unsigned char)(scr_size < 255 ? scr_size : 255);
     Send();
     NETWORK_OUT_STREAM.end_body();
     NETWORK_OUT_STREAM.create_permanent_object(ShellNetID,0,0,0);
     ShellUpdate();
     NETWORK_OUT_STREAM.end_body();
     my_player_body.beebos = aiGetHotBug();
     my_player_body.world = CurrentWorld;
     my_player_body.NetID = NetID;
     my_player_body.BirthTime = GLOBAL_CLOCK();
     my_player_body.CarIndex = uvsPoint->Pmechos->type;
     my_player_body.color = uvsPoint->Pmechos->color;
     if(!pp && !pe && !ps){
         my_player_body.Data0 = R_curr.x;
         my_player_body.Data1 = R_curr.y;
     }else{
         if(pp) my_player_body.Data0 = pp->Poutput->gIndex;
         else my_player_body.Data0 = -1;
         if(pe) my_player_body.Data1 = pe->TabuTaskID;
         else{
             if(ps) my_player_body.Data1 = ps->TabuTaskID;
             else my_player_body.Data1 = -1;
         };
     };
     send_player_body(my_player_body);
 };
References aiGetHotBug(), PlayerBody::beebos, PlayerBody::BirthTime, PlayerBody::CarIndex, PlayerBody::color, uvsMechos::color, cosTurnInvFlt, curGMap, CurrentWorld, PlayerBody::Data0, PlayerBody::Data1, uvsWorld::gIndex, GLOBAL_CLOCK, my_player_body, PlayerBody::NetID, NETWORK_OUT_STREAM, uvsVanger::Pmechos, uvsPassage::Poutput, Object::radius, round(), Object::Send(), send_player_body(), ShellNetID, ShellUpdate(), sinTurnInvFlt, uvsEscave::TabuTaskID, uvsSpot::TabuTaskID, uvsMechos::type, uvsKernel::uvsPoint, and PlayerBody::world.
Referenced by addVanger().
NetEvent()
void VangerUnit::NetEvent (int type, int id, int creator, int time, int x, int y, int radius_)
 {
     switch(type){
         case UPDATE_OBJECT:
         case CREATE_OBJECT:
             Object::NetEvent(type,id,creator,time,x,y,radius_);
             Status &= ~SOBJ_WAIT_CONFIRMATION;
             break;
         case HIDE_OBJECT:
             Status |= SOBJ_WAIT_CONFIRMATION;
             break;
     };
 };
References CREATE_OBJECT, HIDE_OBJECT, Object::NetEvent(), SOBJ_WAIT_CONFIRMATION, Object::time, UPDATE_OBJECT, Object::x, and Object::y.
Referenced by ActionDispatcher::NetEvent().
NewKeyHandler()
void VangerUnit::NewKeyHandler (void)
 {
     Vector vCheck;
     BulletObject* g;
 //  VangerUnit* v;
     static int UseVectorFlag = 0;
     int i;
     StuffObject* p;
     StuffObject* n;
     if(iKeyPressed(iKEY_USE_GLUEK)){
         p = GetStuffObject(this,ACI_GLUEK);
         if(p){
             (ActD.Active)->Armor += 10 << 16;
             ObjectDestroy(p);
             (ActD.Active)->CheckOutDevice(p);
             ActD.CheckDevice(p);
             p->Storage->Deactive(p);
             (ActD.Active)->DelDevice(p);
             aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
         };
     };
     if(iKeyPressed(iKEY_USE_VECTOR)){
         if(!UseVectorFlag){
             UseVectorFlag++;
             p = NULL;
             for(i = 0;i < MAX_ACTIVE_SLOT;i++){
                 if(ActD.Slot[i]){
                     p = ActD.Slot[i];
                     aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                     if(p->ActIntBuffer.type != ACI_RADAR_DEVICE){
                         n = GetStuffObject(this,ACI_RADAR_DEVICE);
                         if(n)
                             aciSendEvent2actint(ACI_PUT_IN_SLOT,&(n->ActIntBuffer));
                     };
                     aciSendEvent2actint(ACI_PUT_ITEM,&(p->ActIntBuffer));
                     break;
                 };
             };
             if(!p){
                 n = GetStuffObject(this,ACI_RADAR_DEVICE);
                 if(n)
                     aciSendEvent2actint(ACI_PUT_IN_SLOT,&(n->ActIntBuffer));
             };
         };
     }else UseVectorFlag = 0;
     if(iKeyPressed(iKEY_OPEN)){
         if(!ThreallMessageProcess){
             if(ActD.DoorEnable){
                 DoorFlag = 1;
                 ActD.DoorEnable = 0;
             };
         };
     }else ActD.DoorEnable = 1;
     if(iKeyPressed(iKEY_FIRE_WEAPON4))
         ActD.ActiveAllTerminator();
     if(iKeyPressed(iKEY_FIRE_WEAPON1)){
         ActD.ActiveSlot(0);
 #ifdef UNIT_DEBUG_VIEW
 //      DBGCHECK;
 //      uvsChangeCycle();
 //      uvsapiDestroyItem(0,-1);
 //      v = (VangerUnit*)(ActD.Tail);
 //      while(v){
 //          if(v->Status & SOBJ_AUTOMAT) v->CalcImpulse();
 //          v = (VangerUnit*)(v->NextTypeList);
 //      };
 //      if(NumPromptTest >= aiNumMessage) NumPromptTest = 0;
 //      else NumPromptTest++;
 //      aiMessageData[NumPromptTest].Send();
 //      aciWorldIndex = WORLD_NECROSS;
 //      aiMessageQueue.Send(AI_MESSAGE_MACHOTINE,Speed,1,0);
 //      OpenCrypt(0,0);
 //      OpenCrypt(0,1);
 /*      int aaa[83],bbb[83];
         for(i = 0;i < 83;i++){
             aaa[i] = RND(9);
             bbb[i] = CheckInMatrix(aaa[i]);
         };
         for(i = 0;i < 83;i++){
             if(CheckOutMatrix(aaa[i]) != bbb[i])
                 ErrH.Abort("GHJHGH");
         };*/
 //      Armor = Energy = 0;
 //      aciWorldIndex = WORLD_THREALL;
 //      ShowDominanceMessage(+5);
 #endif
     };
     if(iKeyPressed(iKEY_FIRE_WEAPON2)){
         ActD.ActiveSlot(1);
 #ifdef UNIT_DEBUG_VIEW
 //      if(NumPromptTest <= 0) NumPromptTest = aiNumMessage - 1;
 //      else NumPromptTest--;
 //      aiMessageData[NumPromptTest].Send();
 //      aciWorldIndex = WORLD_GLORX;
 //      aiMessageQueue.Send(0,Speed,1,0);
 //      uvsChangeCycle();
 //      aciWorldIndex = WORLD_GLORX;
 /*      for(i = 0;i < SnsTableSize;i++){
             if(SensorObjectData[i]->SensorType == SensorTypeList::TRAIN){
                 if(!(SensorObjectData[i]->Owner))
                     t = 83;
                 else{
                     t = (int)(((TrainEngine*)(SensorObjectData[i]->Owner))->LockFlag);
                     if(((TrainEngine*)(SensorObjectData[i]->Owner))->TrainLink[0])
                         t = (int)(((TrainEngine*)(SensorObjectData[i]->Owner))->TrainLink[0]);
                     else
                         t = 83;
                     if(((TrainEngine*)(SensorObjectData[i]->Owner))->TrainLink[1])
                         t = (int)(((TrainEngine*)(SensorObjectData[i]->Owner))->TrainLink[1]);
                     else
                         t = 83;
                 };
             };
         };*/
 //      ShowLuckMessage(-5);
 //      Status ^= SOBJ_AUTOMAT;
 #endif
     };
     if(iKeyPressed(iKEY_FIRE_WEAPON3)){
         ActD.ActiveSlot(2);
 #ifdef UNIT_DEBUG_VIEW
 //      aciWorldIndex = WORLD_NECROSS;
 //      aiMessageQueue.Send(1,Speed,1,0);
 //      PalCD.Set(CPAL_THREALL_TO,50);
 //      ShowTaskMessage(10);
 //      Status ^= SOBJ_AUTOMAT;
 //      PalCD.Set(CPAL_SPOBS_TO,50);
 #endif
     };
     if(iKeyPressed(iKEY_FIRE_ALL_WEAPONS)){
         if(PowerFlag & VANGER_POWER_RUFFA_GUN){
             if(RuffaGunTime > (RUFFA_GUN_WAIT * WeaponWaitTime >> 8)){
                 RuffaGunTime = 0;
                 g = BulletD.CreateBullet();
                 vCheck = Vector(64,0,0)*RotMat;
                 g->CreateBullet(Vector(R_curr.x,R_curr.y,R_curr.z),
                     Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),NULL,&GameBulletData[WD_BULLET_RUFFA],this,Speed);
                 if(ActD.Active)
                     SOUND_RAFFA_SHOT(getDistX(ActD.Active->R_curr.x,R_curr.x));
                 if(NetworkON){
                     NetRuffaGunTime = GLOBAL_CLOCK();
                     ShellUpdateFlag = 1;
                 };
             };
         }else{
             ActD.ActiveAllSlots();
         };
     };
     if(iKeyPressed(iKEY_CHANGE_TARGET))
         ActD.ChangeLocator();
     if((Status & SOBJ_ACTIVE) && (Status & SOBJ_AUTOMAT) &&
        (iKeyPressed(iKEY_TURN_WHEELS_LEFT) || iKeyPressed(iKEY_TURN_WHEELS_RIGHT) || iKeyPressed(iKEY_MOVE_FORWARD) || iKeyPressed(iKEY_MOVE_BACKWARD) || iKeyPressed(iKEY_TURN_OVER_LEFT)
        || iKeyPressed(iKEY_TURN_OVER_RIGHT) || iKeyPressed(iKEY_DEVICE_ON) || iKeyPressed(iKEY_DEVICE_OFF) || iKeyPressed(iKEY_ACTIVATE_KID) || iKeyPressed(iKEY_ACCELERATION) || iKeyPressed(iKEY_OPEN))){
         Status &=~SOBJ_AUTOMAT;
         aiMessageQueue.Send(AI_MESSAGE_AUTOMATIC_OFF,0,0xff,0);
     };
 };
References ACI_DROP_ITEM, ACI_GLUEK, ACI_PUT_IN_SLOT, ACI_PUT_ITEM, ACI_RADAR_DEVICE, aciSendEvent2actint(), ActD, StuffObject::ActIntBuffer, ActionDispatcher::Active, ActionDispatcher::ActiveAllSlots(), ActionDispatcher::ActiveAllTerminator(), ActionDispatcher::ActiveSlot(), AI_MESSAGE_AUTOMATIC_OFF, aiMessageQueue, uvsUnitType::Armor, BulletD, ActionDispatcher::ChangeLocator(), ActionDispatcher::CheckDevice(), CheckOutDevice(), BulletList::CreateBullet(), StuffObject::Deactive(), uvsUnitType::DelDevice(), ActionDispatcher::DoorEnable, DoorFlag, g, GameBulletData, getDistX(), GetStuffObject(), GLOBAL_CLOCK, iKEY_ACCELERATION, iKEY_ACTIVATE_KID, iKEY_CHANGE_TARGET, iKEY_DEVICE_OFF, iKEY_DEVICE_ON, iKEY_FIRE_ALL_WEAPONS, iKEY_FIRE_WEAPON1, iKEY_FIRE_WEAPON2, iKEY_FIRE_WEAPON3, iKEY_FIRE_WEAPON4, iKEY_MOVE_BACKWARD, iKEY_MOVE_FORWARD, iKEY_OPEN, iKEY_TURN_OVER_LEFT, iKEY_TURN_OVER_RIGHT, iKEY_TURN_WHEELS_LEFT, iKEY_TURN_WHEELS_RIGHT, iKEY_USE_GLUEK, iKEY_USE_VECTOR, iKeyPressed(), MAX_ACTIVE_SLOT, NetRuffaGunTime, NetworkON, NULL, ObjectDestroy(), uvsUnitType::PowerFlag, ActionUnit::RotMat, RUFFA_GUN_WAIT, RuffaGunTime, aiMessageList::Send(), ShellUpdateFlag, ActionDispatcher::Slot, SOBJ_ACTIVE, SOBJ_AUTOMAT, SOUND_RAFFA_SHOT, ActionUnit::Speed, ThreallMessageProcess, actintItemData::type, VANGER_POWER_RUFFA_GUN, WD_BULLET_RUFFA, WeaponWaitTime, Object::x, Vector::x, XCYCL, Vector::y, YCYCL, and Vector::z.
Referenced by GameObjectDispatcher::Quant().
NoWayHandler()
void VangerUnit::NoWayHandler (void)
 {
     Vector vCheck;
     int dx,dy;
     switch(NoWayEnable){
         case AI_NO_WAY_CALC:
             if(!(OtherFlag & MECHOS_CALC_WAY)){
                 if(PointStatus & TRK_BRANCH_MASK){
                     if(pBranch->pEnd && pBranch->pBeg){
                         NoWayDirect = 1 - MoveDir;
                         TrackDist[pBranch->index] = 0xffff;
                         WayInit();
                     };
                 };
                 NoWayEnable = AI_NO_WAY_NONE;
 //              aiMoveMode = AI_MOVE_TRACK;
             };
             aiResolveWayEnable = 2;
             break;
         case AI_NO_WAY_PROCESS:
             if(Visibility == VISIBLE){
                 if(RunTimeProcess > 0){
                     RunTimeProcess--;
                     dx = getDistX(vRunStartPosition.x,R_curr.x);
                     dy = getDistY(vRunStartPosition.y,R_curr.y);
                     if((dx*dx + dy*dy) >= RunStartDist){
                         NoWayEnable = AI_NO_WAY_NONE;
                         aiMoveMode = AI_MOVE_TRACK;
                         OtherFlag |= MECHOS_RECALC_FRONT;
                     }else{
                         if(PointStatus & TRK_IN_MASK){
                             if(aiRunBranch != pBranch || aiRunNode != pNode){
                                 NoWayEnable = AI_NO_WAY_NONE;
                                 aiMoveMode = AI_MOVE_TRACK;
                                 OtherFlag |= MECHOS_RECALC_FRONT;
                             }else{
                                 if(TargetPoint.PointStatus & TRK_NODE_MASK){
                                     if(pNode == TargetPoint.pNode){
                                         NoWayEnable = AI_NO_WAY_NONE;
                                         aiMoveMode = AI_MOVE_TRACK;
                                         OtherFlag |= MECHOS_RECALC_FRONT;
                                     };
                                 }else{
                                     if(pBranch == TargetPoint.pBranch &&
                                        (pNextLink == TargetPoint.pPrevLink || pNextLink == TargetPoint.pNextLink ||
                                         pPrevLink == TargetPoint.pPrevLink || pPrevLink == TargetPoint.pNextLink)){
                                         NoWayEnable = AI_NO_WAY_NONE;
                                         aiMoveMode = AI_MOVE_TRACK;
                                         OtherFlag |= MECHOS_RECALC_FRONT;
                                     };
                                 };
                             };
                         };
                     };
                 }else{
                     NoWayEnable = AI_NO_WAY_NONE;
                     aiMoveMode = AI_MOVE_TRACK;
                     OtherFlag |= MECHOS_RECALC_FRONT;
                 };
             }else{
                 if(PointStatus & TRK_IN_MASK){
                     if(aiRunBranch != pBranch || aiRunNode != pNode){
                         NoWayEnable = AI_NO_WAY_NONE;
                         aiMoveMode = AI_MOVE_TRACK;
                         OtherFlag |= MECHOS_RECALC_FRONT;
                     }else{
                         if(TargetPoint.PointStatus & TRK_NODE_MASK){
                             if(pNode == TargetPoint.pNode){
                                 NoWayEnable = AI_NO_WAY_NONE;
                                 aiMoveMode = AI_MOVE_TRACK;
                                 OtherFlag |= MECHOS_RECALC_FRONT;
                             };
                         }else{
                             if(pBranch == TargetPoint.pBranch &&
                                (pNextLink == TargetPoint.pPrevLink || pNextLink == TargetPoint.pNextLink ||
                                 pPrevLink == TargetPoint.pPrevLink || pPrevLink == TargetPoint.pNextLink)){
                                 NoWayEnable = AI_NO_WAY_NONE;
                                 aiMoveMode = AI_MOVE_TRACK;
                                 OtherFlag |= MECHOS_RECALC_FRONT;
                             };
                         };
                     };
                 };
             };
             aiResolveWayEnable = 2;
             break;
     };
 };
References AI_MOVE_TRACK, AI_NO_WAY_CALC, AI_NO_WAY_NONE, AI_NO_WAY_PROCESS, TrackUnit::aiMoveMode, aiResolveWayEnable, aiRunBranch, aiRunNode, getDistX(), getDistY(), BranchType::index, MECHOS_CALC_WAY, MECHOS_RECALC_FRONT, TrackUnit::MoveDir, TrackUnit::NoWayDirect, NoWayEnable, ActionUnit::OtherFlag, BranchType::pBeg, TrackLinkType::pBranch, BranchType::pEnd, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, RunStartDist, RunTimeProcess, TrackUnit::TargetPoint, TrackUnit::TrackDist, TRK_BRANCH_MASK, TRK_IN_MASK, TRK_NODE_MASK, VISIBLE, vRunStartPosition, TrackUnit::WayInit(), Vector::x, and Vector::y.
Referenced by InitEnvironment().
NoWayInit()
void VangerUnit::NoWayInit (void) inline
 {if(NoWayEnable == AI_NO_WAY_NONE) NoWayEnable = AI_NO_WAY_CALC;};
References AI_NO_WAY_CALC, AI_NO_WAY_NONE, and NoWayEnable.
Referenced by CalcAiFactor().
OutCarNator()
void VangerUnit::OutCarNator (void)
 {
     StuffObject* p;
     StuffObject* pp;
     uvsItem* g;
     if(NetworkON){
         FreeList(uvsPoint->Pitem);
         p = VangerChanger->DeviceData;
         while(p){
             if(p->ActIntBuffer.type == ACI_MECHOSCOPE)
                 p->ActIntBuffer.data1 = 0;
             g = new uvsItem(p->uvsDeviceType);
             g->param1 = p->ActIntBuffer.data0;
             g->param2 = p->ActIntBuffer.data1;
             uvsPoint->addItem(g,1);
             p = p->NextDeviceList;
         };
     }else{
         FreeList(VangerChanger->uvsPoint->Pitem);
         if(Status & SOBJ_ACTIVE) aciDropMoveItem();
         p = DeviceData;
         while(p){
             pp = p->NextDeviceList;
             if(p->ActIntBuffer.type == ACI_MECHOSCOPE)
                 p->ActIntBuffer.data1 = 0;
             ObjectDestroy(p);
             CheckOutDevice(p);
             g = new uvsItem(p->uvsDeviceType);
             if(Status & SOBJ_ACTIVE){
                 aciGetItemCoords(&(p->ActIntBuffer),g->pos_x,g->pos_y);
                 ActD.CheckDevice(p);
                 aciRemoveItem(&(p->ActIntBuffer));
             };
             g->param1 = p->ActIntBuffer.data0;
             g->param2 = p->ActIntBuffer.data1;
             VangerChanger->uvsPoint->addItem(g,1);
             p->Storage->Deactive(p);
             DelDevice(p);
             p = pp;
         };
     };
 };
References ACI_MECHOSCOPE, aciDropMoveItem(), aciGetItemCoords(), aciRemoveItem(), ActD, StuffObject::ActIntBuffer, uvsVanger::addItem(), ActionDispatcher::CheckDevice(), CheckOutDevice(), actintItemData::data0, actintItemData::data1, StuffObject::Deactive(), uvsUnitType::DelDevice(), uvsUnitType::DeviceData, FreeList(), g, NetworkON, StuffObject::NextDeviceList, ObjectDestroy(), uvsVanger::Pitem, SOBJ_ACTIVE, actintItemData::type, StuffObject::uvsDeviceType, uvsKernel::uvsPoint, and VangerChanger.
Referenced by InitEnvironment().
Quant()
void VangerUnit::Quant (void) virtual
Reimplemented from TrackUnit.
 {
     int cX[4],cY[4];
     int cAlpha;
     Vector vCheck;
     int i;
     StuffObject* p;
     if(Status & SOBJ_WAIT_CONFIRMATION) return;
     RuffaGunTime++;
     SensorQuant();
     UseDeviceMask = 0;
     CoptePoint = NULL;
     SwimPoint = NULL;
     MolePoint = NULL;
     if(VangerRaceStatus != VANGER_RACE_ZLP) VangerRaceStatus = VANGER_RACE_NONE;
     p = DeviceData;
     while(p){
         switch(p->ActIntBuffer.type){
             case ACI_COPTE_RIG:
                 if(PowerFlag & VANGER_POWER_FLY && CurrentWorld != WORLD_KHOX){
                     UseDeviceMask |= DEVICE_MASK_COPTE;
                     CoptePoint = p;
                 };
                 break;
             case ACI_CUTTE_RIG:
                 if(PowerFlag & VANGER_POWER_FLY){
                     UseDeviceMask |= DEVICE_MASK_SWIM;
                     SwimPoint = p;
                 };
                 break;
             case ACI_CROT_RIG:
                 if(PowerFlag & VANGER_POWER_FLY){
                     UseDeviceMask |= DEVICE_MASK_MOLE;
                     MolePoint = p;
                 };
                 break;
             case ACI_ELEECH:
                 if(CurrentWorld == WORLD_FOSTRAL) VangerRaceStatus = VANGER_RACE_ELR;
                 break;
             case ACI_KERNOBOO:
                 if(CurrentWorld == WORLD_GLORX) VangerRaceStatus = VANGER_RACE_KRW;
                 break;
             case ACI_PIPETKA:
                 if(CurrentWorld == WORLD_GLORX)VangerRaceStatus = VANGER_RACE_PPS;
                 break;
             case ACI_WEEZYK:
                 if(CurrentWorld == WORLD_NECROSS) VangerRaceStatus = VANGER_RACE_ZLP;
                 break;
             case ACI_PROTRACTOR:
                 ActD.pfActive = this;
                 break;
             case ACI_MECHANIC_MESSIAH:
                 ActD.mfActive = this;
                 break;
         };
         p = p->NextDeviceList;
     };
     if((Status & SOBJ_ACTIVE) && CurrentWorld == WORLD_NECROSS && uvsCurrentCycle == 1 && uvsGamerWaitGame)
         VangerRaceStatus = VANGER_RACE_ZLP;
     if(uvsPoint->status == UVS_VANGER_STATUS::RACE_HUNTER)
         VangerRaceStatus = VANGER_RACE_ZLP;
     TrackUnit::Quant();
     if(Status & SOBJ_ACTIVE){
         switch(ActD.FlyTaskEnable){
             case 0:
                 if(ActD.FlyTaskDirect){
                     if(R_curr.y >= ActD.FlyTaskFirstY){
                         if(!(dynamic_state & TOUCH_OF_GROUND)) ActD.FlyTaskEnable = 1;
                         else ActD.FlyTaskEnable = 2;
                     };
                 }else{
                     if(R_curr.y <= ActD.FlyTaskFirstY){
                         if(!(dynamic_state & TOUCH_OF_GROUND)) ActD.FlyTaskEnable = 1;
                         else ActD.FlyTaskEnable = 2;
                     };
                 };
                 break;
             case 1:
                 if(dynamic_state & TOUCH_OF_GROUND)
                     ActD.FlyTaskEnable = 2;
                 else{
                     if(ActD.FlyTaskDirect){
                         if(R_curr.y > ActD.FlyTaskLastY){
                             uvsCheckKronIventTabuTask(UVS_KRON_EVENT::FLY_ONLINE,0);
                             ActD.FlyTaskEnable = 2;
                         };
                     }else{
                         if(R_curr.y < ActD.FlyTaskLastY){
                             uvsCheckKronIventTabuTask(UVS_KRON_EVENT::FLY_ONLINE,0);
                             ActD.FlyTaskEnable = 2;
                         };
                     };
                 };
                 break;
             case 2:
                 if(ActD.FlyTaskDirect){
                     if(R_curr.y <= ActD.FlyTaskFirstY)
                         ActD.FlyTaskEnable = 0;
                 }else{
                     if(R_curr.y >= ActD.FlyTaskFirstY)
                         ActD.FlyTaskEnable = 0;
                 };
                 break;
         };
     };
     if(NetworkON && !(Status & SOBJ_ACTIVE)){
 /*      if(aciWorldIndex != -1){
             uvsPoint -> Pworld = WorldTable[aciWorldIndex];
             aciWorldIndex = -1;
             EffD.CreateRingOfLord(EFF_PARTICLE06,R_curr + Vector(0,0,80),radius*2,200,111,111,radius << 7);
             ExternalLock = 1;
             ExternalObject = NULL;
             ExternalMode = EXTERNAL_MODE_FREE_IN;
             ExternalTime = ROTOR_PROCESS_LIFE_TIME;
             CreateParticleRotor(R_curr,83);
             ExternalDraw = 0;
             switch_analysis(1);
         };*/
         TerrainQuant();
         CheckPosition++;
         if(ActiveGetBranch()){
             if(CheckPosition > MaxCheckPosition){
                 CheckPosition = 0;
                 HideTrack.GetPosition(this);
             };
         };
         if(PointStatus & TRK_BRANCH_MASK){
             if(MoveDir){
                 if(pNode != pBranch->pBeg && pNode != pBranch->pEnd){
                     if(pBranch->pBeg) pNode = pBranch->pBeg;
                     else{
                         if(pBranch->pEnd) pNode = pBranch->pEnd;
                         else ErrH.Abort("Bad Link to Node");
                     };
                 };
             }else{
                 if(pNode != pBranch->pBeg && pNode != pBranch->pEnd){
                     if(pBranch->pEnd) pNode = pBranch->pEnd;
                     else{
                         if(pBranch->pBeg) pNode = pBranch->pBeg;
                         else ErrH.Abort("Bad Link to Node");
                     };
                 };
             };
         }else{
             if(pBranch->pBeg != pNode && pBranch->pEnd != pNode){
                 pBranch = pNode->pBranches[0];
                 if(pBranch->pBeg == pNode){
                     pPrevLink = pBranch->Link;
                     pNextLink = pPrevLink + 1;
                 }else{
                     pNextLink = pBranch->Link + pBranch->NumLink - 1;
                     pPrevLink = pNextLink - 1;
                 };
             };
         };
         GetTrackVector();
         if(CurrentWorld == WORLD_GLORX && !NetworkON){
             if(NullTime > 80){
                 cAlpha = RND(PI*2);
                 for(i = 0;i < 4;i++){
                     vCheck = Vector(radius*2,0,0)*DBM(cAlpha,Z_AXIS);
                     cX[i] = R_curr.x + vCheck.x;
                     cY[i] = R_curr.y + vCheck.y;
                     cAlpha -= PI/2 + PI/8 - RND(PI/6);
                 };
                 MapD.CreateLandSlide(cX,cY,50);
                 NullTime = -NullTime;
             };
         };
     }else{
         if(Status & SOBJ_AUTOMAT){
             if(Visibility == VISIBLE){
                 TerrainQuant();
                 if(aiMoveMode == AI_MOVE_POINT){
                     CheckPosition++;
                     if(ActiveGetBranch()){
                         if(CheckPosition > MaxCheckPosition){
                             CheckPosition = 0;
                             HideTrack.GetPosition(this);
                         };
                     };
                 }else GetBranch();
                 GetTrackVector();
                 if(aiActionID != AI_ACTION_BRAKE) TargetAnalysis();
                 else SpeedDir = 0;
                 Action();
             }else{
     //          HideGetBranch();
                 if(aiMoveMode == AI_MOVE_POINT){
                     CheckPosition++;
                     if(ActiveGetBranch()){
                         if(CheckPosition > MaxCheckPosition){
                             CheckPosition = 0;
                             HideTrack.GetPosition(this);
                         };
                     };
                 }else GetBranch();
                 if(aiActionID != AI_ACTION_BRAKE) TargetAnalysis();
                 else SpeedDir = 0;
                 HideAction();
             };
         }else{
             if(aciWorldIndex != -1){
                 if(!(Status & SOBJ_AUTOMAT)){
                     uvsPoint -> Pworld = WorldTable[aciWorldIndex];
                     EffD.CreateRingOfLord(EFF_PARTICLE06,R_curr + Vector(0,0,80),radius*2,200,111,111,radius << 7);
         //          ExternalMode = EXTERNAL_MODE_SIGN_IN;
         //          ExternalTime = 40;
                     ExternalLock = 1;
                     ExternalObject = NULL;
                     ExternalMode = EXTERNAL_MODE_FREE_IN;
                     ExternalTime = ROTOR_PROCESS_LIFE_TIME;
                     CreateParticleRotor(R_curr,83);
                     PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
                     ExternalDraw = 0;
                     switch_analysis(1);
                     StopCDTRACK();
                     NetFunction83Time = NetGlobalTime;
                     ShellUpdateFlag = 1;
                 };
                 aciWorldIndex = -1;
             };
             if(aciTeleportEvent != 0){
                 if(!(Status & SOBJ_AUTOMAT)){
                     ExternalTime = CHANGE_VANGER_TIME;
                     ExternalLock = 1;
                     ExternalObject = NULL;
                     ExternalMode = EXTERNAL_MODE_IN_VANGER;
                     vSetVangerFlag = aciTeleportEvent - TELEPORT_ESCAVE_ID;
         //          Go2Universe();
         //          Status |= SOBJ_DISCONNECT;
                     PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
                     switch_analysis(1);
                     for(i = 0;i < 5;i++)
                         EffD.CreateParticleGenerator(R_curr,R_curr,Vector(5,0,0)*DBM((int)(RND(PI*2)),Z_AXIS));
                     SOUND_BOOT_START();
                 };
                 aciTeleportEvent = 0;
             };
             if(ExternalMode == EXTERNAL_MODE_NORMAL && ActD.PassageTouchEnable > 0)
                 ActD.PassageTouchEnable--;
             TerrainQuant();
             CheckPosition++;
             if(ActiveGetBranch()){
                 if(CheckPosition > MaxCheckPosition){
                     CheckPosition = 0;
                     HideTrack.GetPosition(this);
                 };
             };
             if(PointStatus & TRK_BRANCH_MASK){
                 if(MoveDir){
                     if(pNode != pBranch->pBeg && pNode != pBranch->pEnd){
                         if(pBranch->pBeg) pNode = pBranch->pBeg;
                         else{
                             if(pBranch->pEnd) pNode = pBranch->pEnd;
                             else ErrH.Abort("Bad Link to Node");
                         };
                     };
                 }else{
                     if(pNode != pBranch->pBeg && pNode != pBranch->pEnd){
                         if(pBranch->pEnd) pNode = pBranch->pEnd;
                         else{
                             if(pBranch->pBeg) pNode = pBranch->pBeg;
                             else ErrH.Abort("Bad Link to Node");
                         };
                     };
                 };
             }else{
                 if(pBranch->pBeg != pNode && pBranch->pEnd != pNode){
                     pBranch = pNode->pBranches[0];
                     if(pBranch->pBeg == pNode){
                         pPrevLink = pBranch->Link;
                         pNextLink = pPrevLink + 1;
                     }else{
                         pNextLink = pBranch->Link + pBranch->NumLink - 1;
                         pPrevLink = pNextLink - 1;
                     };
                 };
             };
             GetTrackVector();
             if(CurrentWorld == WORLD_GLORX && !NetworkON){
                 if(NullTime > 80){
                     cAlpha = RND(PI*2);
                     for(i = 0;i < 4;i++){
                         vCheck = Vector(radius*2,0,0)*DBM(cAlpha,Z_AXIS);
                         cX[i] = R_curr.x + vCheck.x;
                         cY[i] = R_curr.y + vCheck.y;
                         //cycleTor(cX[i],cY[i]);
                         cAlpha -= PI/2 + PI/8 - RND(PI/6);
                     };
                     /*cX[2] = cX[1] + cX[3] - cX[0];
                     cY[2] = cY[1] + cY[3] - cY[0];*/
                     MapD.CreateLandSlide(cX,cY,50);
                     NullTime = -NullTime;
                 };
             };
         };
     };
     if(!NetworkON && CurrentWorld == WORLD_KHOX && ExternalMode == EXTERNAL_MODE_NORMAL && !PalIterLock && PalCD.PalEnable){
         if(KhoxPoison < 0){
             UseOxigenResource();
         }else{
             for(i = 0;i < 128*3;i++)
                 palbufOrg[i] = palbuf[i] = (uchar)(KhoxPoison*(int)(palbufSrc[i]) / MaxKhoxPoison);
              if(CheckPointCount < MAX_KHOX_CHECKPOINT) KhoxPoison -= 3 << 6;
         };
     };
     ItemQuant();
     if(uvsPoint) uvsPoint->update(R_curr.x,R_curr.y);
     if(NetworkON && (Status & SOBJ_ACTIVE)){
         if(my_server_data.GameType == PASSEMBLOSS && UsedCheckNum >= GloryPlaceNum && ExternalMode == EXTERNAL_MODE_NORMAL){
             ExternalLock = 1;
             ExternalObject = NULL;
             ExternalMode = EXTERNAL_MODE_FREE_IN;
             ExternalTime = ROTOR_PROCESS_LIFE_TIME;
             CreateParticleRotor(R_curr,83);
             PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
             ExternalDraw = 0;
             switch_analysis(1);
             StopCDTRACK();
             NetFunction83Time = NetGlobalTime;
             ShellUpdateFlag = 1;
         };
 //      static unsigned int last_send_set_position = 0;
 //      static prevViewY = 0;
 //      if(abs(getDistY(prevViewY,ViewY)) > 10 && IS_PAST(last_send_set_position + average_lag)){
 //          NETWORK_OUT_STREAM.set_position(ViewX,ViewY,round(2.*(fabs(curGMap -> xsize*sinTurnInvFlt) + fabs(curGMap -> ysize*cosTurnInvFlt))*0.5));
 //          prevViewY = ViewY;
 //          last_send_set_position = SDL_GetTicks();
 //          }
         static int need_to_send_vanger = 0;
         if(prev_controls != current_controls || dynamic_state & ITS_MOVING || IS_PAST(last_send_time + 2000))
             need_to_send_vanger = 1;
         if(need_to_send_vanger && IS_PAST(last_send_time + average_lag)){
             last_send_time = SDL_GetTicks();
             NETWORK_OUT_STREAM.update_object(NetID,R_curr.x,R_curr.y);
             int scr_size = round((fabs(curGMap -> xsize*sinTurnInvFlt) + fabs(curGMap -> ysize*cosTurnInvFlt))*.5);
             NETWORK_OUT_STREAM < (unsigned char)(scr_size < 255 ? scr_size : 255);
             Send();
             NETWORK_OUT_STREAM.end_body();
             need_to_send_vanger = 0;
             if(lag_averaging_t0.tell() < 20){
                 //zmod
                 z_time_init();
                 NETWORK_OUT_STREAM.begin_event(SERVER_TIME_QUERY);
                 NETWORK_OUT_STREAM.end_body();
                 lag_averaging_t0.put(SDL_GetTicks());
                 }
             }
         if(abs(Energy - NetworkEnergy) > (MaxEnergy >> 4)){
             NetworkEnergy = Energy;
             ShellUpdateFlag = 1;
         }else{
             if(Armor == 0 || abs(Armor - NetworkArmor) > (MaxArmor >> 4)){
                 NetworkArmor = Armor;
                 ShellUpdateFlag = 1;
             };
         };
         if(VangerChanger){
             if(VangerChanger->VangerChanger){
                 if(VangerChanger->VangerChanger != this){
                     VangerChanger = NULL;
                     VangerChangerCount = 0;
                     NetChanger = 0;
                     ShellUpdateFlag = 1;
                 }else{
                     if(NetChanger == GET_STATION(VangerChanger->NetID) && VangerChanger->NetChanger == GlobalStationID && VangerChangerCount == 2)
                         VangerChangerCount = 1;
                 };
             }else{
                 if(NetChanger == 0xff){
                     VangerChanger = NULL;
                     VangerChangerCount = 0;
                     NetChanger = 0;
                     ShellUpdateFlag = 1;
                 };
             };
         };
 /*      if(VangerChanger && VangerChanger->VangerChanger){
             if(VangerChanger->VangerChanger != this){
                 VangerChanger = NULL;
                 VangerChangerCount = 0;
                 NetChanger = 0;
                 ShellUpdateFlag = 1;
             }else{
                 if(VangerChangerCount == 2)
                     VangerChangerCount = 1;
             };
         };*/
         if(ShellUpdateFlag){
             ShellUpdateFlag = 0;
             NETWORK_OUT_STREAM.update_object(ShellNetID,0,0);
             ShellUpdate();
             NETWORK_OUT_STREAM.end_body();
         };
     };
 };
References XErrorHandler::Abort(), ACI_COPTE_RIG, ACI_CROT_RIG, ACI_CUTTE_RIG, ACI_ELEECH, ACI_KERNOBOO, ACI_MECHANIC_MESSIAH, ACI_PIPETKA, ACI_PROTRACTOR, ACI_WEEZYK, aciTeleportEvent, aciWorldIndex, ActD, StuffObject::ActIntBuffer, Action(), TrackUnit::ActiveGetBranch(), AI_ACTION_BRAKE, AI_MOVE_POINT, aiActionID, TrackUnit::aiMoveMode, uvsUnitType::Armor, average_lag, CHANGE_VANGER_TIME, CheckPointCount, TrackUnit::CheckPosition, CoptePoint, cosTurnInvFlt, CPAL_HIDE_PASSAGE, EffectDispatcher::CreateParticleGenerator(), CreateParticleRotor(), EffectDispatcher::CreateRingOfLord(), curGMap, Object::current_controls, CurrentWorld, DEVICE_MASK_COPTE, DEVICE_MASK_MOLE, DEVICE_MASK_SWIM, uvsUnitType::DeviceData, EFF_PARTICLE06, EffD, uvsUnitType::Energy, ErrH, EXTERNAL_MODE_FREE_IN, EXTERNAL_MODE_IN_VANGER, EXTERNAL_MODE_NORMAL, ExternalDraw, ExternalLock, ExternalMode, ExternalObject, ExternalTime, UVS_KRON_EVENT::FLY_ONLINE, ActionDispatcher::FlyTaskDirect, ActionDispatcher::FlyTaskEnable, ActionDispatcher::FlyTaskFirstY, ActionDispatcher::FlyTaskLastY, ServerData::GameType, GET_STATION, TrackUnit::GetBranch(), TrackType::GetPosition(), TrackUnit::GetTrackVector(), GlobalStationID, GloryPlaceNum, HideAction(), HideTrack, IS_PAST, ItemQuant(), ITS_MOVING, KhoxPoison, lag_averaging_t0, Object::last_send_time, BranchType::Link, MapD, MAX_KHOX_CHECKPOINT, uvsUnitType::MaxArmor, TrackUnit::MaxCheckPosition, uvsUnitType::MaxEnergy, MaxKhoxPoison, ActionDispatcher::mfActive, MolePoint, TrackUnit::MoveDir, my_server_data, NetChanger, NetFunction83Time, NetGlobalTime, NETWORK_OUT_STREAM, NetworkArmor, NetworkEnergy, NetworkON, StuffObject::NextDeviceList, NULL, TrackUnit::NullTime, BranchType::NumLink, palbuf, palbufOrg, palbufSrc, PalCD, PalConstructor::PalEnable, PalIterLock, ActionDispatcher::PassageTouchEnable, PASSEMBLOSS, BranchType::pBeg, TrackLinkType::pBranch, NodeType::pBranches, BranchType::pEnd, ActionDispatcher::pfActive, PI, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, uvsUnitType::PowerFlag, TrackLinkType::pPrevLink, Object::prev_controls, TrackUnit::Quant(), UVS_VANGER_STATUS::RACE_HUNTER, Object::radius, RND(), ROTOR_PROCESS_LIFE_TIME, round(), RuffaGunTime, Object::Send(), SensorQuant(), SERVER_TIME_QUERY, PalConstructor::Set(), ShellNetID, ShellUpdate(), ShellUpdateFlag, sinTurnInvFlt, SOBJ_ACTIVE, SOBJ_AUTOMAT, SOBJ_WAIT_CONFIRMATION, SOUND_BOOT_START, ActionUnit::SpeedDir, uvsVanger::status, StopCDTRACK(), SwimPoint, Object::switch_analysis(), TargetAnalysis(), TELEPORT_ESCAVE_ID, TerrainQuant(), TOUCH_OF_GROUND, TRK_BRANCH_MASK, actintItemData::type, uvsVanger::update(), UsedCheckNum, UseDeviceMask, uvsUnitType::UseOxigenResource(), uvsCheckKronIventTabuTask(), uvsCurrentCycle, uvsGamerWaitGame, uvsKernel::uvsPoint, VANGER_POWER_FLY, VANGER_RACE_ELR, VANGER_RACE_KRW, VANGER_RACE_NONE, VANGER_RACE_PPS, VANGER_RACE_ZLP, VangerChanger, VangerChangerCount, VangerRaceStatus, VISIBLE, vSetVangerFlag, WORLD_FOSTRAL, WORLD_GLORX, WORLD_KHOX, WORLD_NECROSS, WorldTable, Vector::x, Vector::y, Z_AXIS, and z_time_init().
ResolveFindDestroy()
void VangerUnit::ResolveFindDestroy (aiUnitResolve * p)
 {
     p->rStatus |= AI_RESOLVE_STATUS_DISCONNECT;
     if(aiMoveMode == AI_MOVE_POINT){
         aiMoveMode = AI_MOVE_TRACK;
         OtherFlag |= MECHOS_RECALC_FRONT;
     };
 };
References AI_MOVE_POINT, AI_MOVE_TRACK, AI_RESOLVE_STATUS_DISCONNECT, TrackUnit::aiMoveMode, MECHOS_RECALC_FRONT, ActionUnit::OtherFlag, and aiUnitResolve::rStatus.
Referenced by CheckFind(), CheckInDevice(), and ResolveHandlerFind().
ResolveGenerator()
void VangerUnit::ResolveGenerator (void)
 {
     int i;
     aiUnitEvent* n;
     aiUnitEvent* nn;
     int dx,dy;
     uchar* pa0;
     Vector vCheck,vTrack;
     VangerUnit* v;
     StuffObject* s;
     int q,a;
     SensorDataType* sns;
     aiStatus = AI_STATUS_NONE;
     aiStatus |= AI_STATUS_WHEEL | AI_STATUS_IMPULSE;
     if(dynamic_state & VERTICAL_WALL_COLLISION) WallCollisionTime = MAX_WALL_TIME;
     else if(WallCollisionTime > 0) WallCollisionTime--;
     if(abs(TractionValue) < MAX_TRACTION_CHECK_DELTA) DeltaTractionTime = MAX_TRACTION_CHECK_TIME;
     else if(DeltaTractionTime > 0) DeltaTractionTime--;
     if(aiAlarmTime > 0) aiAlarmTime--;
     if(SpeedFactorTime > 0) SpeedFactorTime--;
     if(AddAttackTime > 0) AddAttackTime = 0;
     if(aiDamage > 0){
         aiDamage -= (1 << 10);
         if(aiDamage < 0){
             aiDamage = 0;
             aiDamageData = NULL;
         };
     };
     if(!LowAmmo) CheckAmmo();
     if(!LowArmor && Armor < ArmorAlarm){
         sns = GetNearSensor(R_curr.y,SensorTypeList::ARMOR_UPDATE);
         if(sns && !aiResolveFind.FindResolve(UNIT_ORDER_SENSOR,UnitOrderType(sns))){
             AddFindResolve(UNIT_ORDER_SENSOR,UnitOrderType(sns),0,AI_RESOLVE_STATUS_TARGET)->Time = MaxWayCount;
             LowArmor = 1;
         };
     };
     if(aiActionID == AI_ACTION_FARMER){
         q = SeedNum;
         s = DeviceData;
         SeedNum = 0;
         if(uvsCurrentCycle == 1){
             while(s){
                 if(s->ActIntBuffer.type == ACI_PIPETKA)
                     SeedNum += s->ActIntBuffer.data1;
                 s = s->NextDeviceList;
             };
         }else{
             if(uvsCurrentCycle == 2){
                 while(s){
                     if(s->ActIntBuffer.type == ACI_KERNOBOO)
                         SeedNum += s->ActIntBuffer.data1;
                     s = s->NextDeviceList;
                 };
             };
         };
         if(FarmerD.Num == 0 && ActD.WorldSeedNum <= MaxSeed)
             SeedNum = MaxSeed;
         if(SeedNum >= MaxSeed && q < MaxSeed){
             aiResolveFind.ClearResolve();
             uvsPoint->break_harvest();
             MainOrderInit();
         };
     };
     if(Visibility == VISIBLE && CoptePoint && !aiAlarmTime) aiStatus |= AI_STATUS_FLY;
     if((Visibility == VISIBLE && !RND(MAX_CHECK_VISIBLE_FACTOR)) || (Visibility == UNVISIBLE && !RND(MAX_CHECK_UNVISIBLE_FACTOR))){
         n = (aiUnitEvent*)(aiEvent.Tail);
         while(n){
             if(n->Time < aiMaxView) n->Time += aiAddView;
             n->Refresh = 0;
             n = (aiUnitEvent*)(n->Next);
         };
         v = (VangerUnit*)(ActD.Tail);
         vCheck.z = 0;
         while(v){
             if(v != this && v->ExternalDraw && v->draw_mode == NORMAL_DRAW_MODE){
                 vCheck.x = abs(getDistX(v->R_curr.x,R_curr.x));
                 vCheck.y = abs(getDistY(v->R_curr.y,R_curr.y));
                 if(vCheck.y < aiVangerRadius && vCheck.x < aiVangerRadius)
                     AddEvent(AI_EVENT_VANGER,NULL,v);
             };
             v = (VangerUnit*)(v->NextTypeList);
         };
         s = (StuffObject*)(ItemD.Tail);
         while(s){
             if(s->ActIntBuffer.type == aiFirstItem || s->ActIntBuffer.type == aiSecondItem){
                 dy = getDistY(s->R_curr.y,R_curr.y);
                 if(abs(dy) < aiItemRadius){
                     dy= getDistX(s->R_curr.x,R_curr.x);
                     if(abs(dy) < aiItemRadius)
                         AddEvent(AI_EVENT_ITEM,s,NULL);
                 };
             };
             s = (StuffObject*)(s->NextTypeList);
         };
     }else{
         n = (aiUnitEvent*)(aiEvent.Tail);
         while(n){
             if(n->Time < aiMaxView) n->Time += aiAddView;
             n = (aiUnitEvent*)(n->Next);
         };
     };
     dx = getDistX(aiRelaxData.x,R_curr.x);
     dy = getDistY(aiRelaxData.y,R_curr.y);
     if(abs(dx) > aiRealxRadius || abs(dy) > aiRealxRadius){
         aiRelaxTime = 0;
         aiRelaxData = R_curr;
     }else aiRelaxTime++;
     dx = getDistX(TargetPoint.vPoint.x,R_curr.x);
     dy = getDistY(TargetPoint.vPoint.y,R_curr.y);
     if(abs(dy) < radius && abs(dx) < radius)
         aiStatus |= AI_STATUS_TARGET;
     i = 0;
     if(Visibility == VISIBLE){
         vCheck = R_curr;
         vTrack = R_curr + Vector(aiScanDist,0,0)*RotMat;
         if(MapLineTrace(vCheck,vTrack)){
             pa0 = vMap->lineT[vCheck.y];
             if(pa0 && GET_TERRAIN(*(pa0 + vCheck.x + H_SIZE)) == 7)
                 i++;
         };
         vCheck = R_curr;
         vTrack = R_curr + Vector(aiScanDist,radius,0)*RotMat;
         if(MapLineTrace(vCheck,vTrack)){
             pa0 = vMap->lineT[vCheck.y];
             if(pa0 && GET_TERRAIN(*(pa0 + vCheck.x + H_SIZE)) == 7)
                 i++;
         };
         vCheck = R_curr;
         vTrack = R_curr + Vector(aiScanDist,-radius,0)*RotMat;
         if(MapLineTrace(vCheck,vTrack)){
             pa0 = vMap->lineT[vCheck.y];
             if(pa0 && GET_TERRAIN(*(pa0 + vCheck.x + H_SIZE)) == 7)
                 i++;
         };
         if(i >= 2) aiStatus |= AI_STATUS_TNT;
     };
     n = (aiUnitEvent*)(aiEvent.Tail);
     if(Visibility == VISIBLE){
         while(n){
             nn = (aiUnitEvent*)(n->Next);
             if(!(n->Refresh)){
                 aiEvent.Disconnect(n);
                 delete n;
             }else{
                 if(n->ID == AI_EVENT_VANGER && !RND(MAX_CHECK_VISIBLE_FACTOR)){
                     if(n->Time > aiMainLevel)
                         n->Time += aiDeltaLevel;
                     if(!aiAlarmTime){
                         if(GetAllert(n->Subj) < 0)
                             aiAlarmTime = AI_MAX_ALARM_TIME;
                     }else{
                         if(n->Time < aiMaxAlarm)
                             n->Time += aiAddAlarm;
                     };
                     CalcAiFactor(n->Subj,n->Time);
                 };
             };
             n = nn;
         };
     }else{
         while(n){
             nn = (aiUnitEvent*)(n->Next);
             if(!(n->Refresh)){
                 aiEvent.Disconnect(n);
                 delete n;
             }else{
                 if(n->ID == AI_EVENT_VANGER && !RND(MAX_CHECK_UNVISIBLE_FACTOR)){
                     if(n->Time > aiMainLevel)
                         n->Time += aiDeltaLevel;
                     if(!aiAlarmTime){
                         if(GetAllert(n->Subj) < 0)
                             aiAlarmTime = AI_MAX_ALARM_TIME;
                     }else{
                         if(n->Time < aiMaxAlarm)
                             n->Time += aiAddAlarm;
                     };
                     CalcAiFactor(n->Subj,n->Time);
                 };
             };
             n = nn;
         };
     };
     n = aiGlobalEventData[aiReadEvent][AI_EVENT_DROP];
     for(i = 0;i < aiNumGlobalEvent[aiReadEvent][AI_EVENT_DROP];i++){
         if(n->Refresh){
         };
         n++;
     };
     n = aiGlobalEventData[aiReadEvent][AI_EVENT_CAPTURE];
     for(i = 0;i < aiNumGlobalEvent[aiReadEvent][AI_EVENT_CAPTURE];i++){
         if(n->Refresh){
             if(n->Subj == this){
                 if(aiResolveFind.FindResolve(UNIT_ORDER_STUFF,UnitOrderType((StuffObject*)(n->Obj))))
                     aiResolveFind.ClearResolve(UNIT_ORDER_STUFF,UnitOrderType((StuffObject*)(n->Obj)));
             };
         };
         n++;
     };
     n = aiGlobalEventData[aiReadEvent][AI_EVENT_COLLISION];
     for(i = 0;i < aiNumGlobalEvent[aiReadEvent][AI_EVENT_COLLISION];i++){
         if(n->Refresh){
             switch(n->ID){
                 case ID_VANGER:
                     if(n->Subj == this && aiRelaxTime > aiRelaxTimeMax){
                         vCheck = Vector(getDistX(n->Obj->R_curr.x,R_curr.x),getDistY(n->Obj->R_curr.y,R_curr.y),0);
                         a = rPI(vCheck.psi() - Angle);
                         if(a > PI) a -= PI*2;
                         if(abs(a) < PI / 4) AddEventTime((VangerUnit*)(n->Obj),aiAddFrontCollision,AI_ADD_FRONT_COLLISION);
                         else{
                             if(abs(a) > 3*PI / 4)
                                 AddEventTime((VangerUnit*)(n->Obj),aiAddBackCollision,AI_ADD_BACK_COLLISION);
                             else
                                 AddEventTime((VangerUnit*)(n->Obj),aiAddSideCollision,AI_ADD_SIDE_COLLISION);
                         };
                     };
                     break;
                 case ID_BULLET:
                     if(n->Subj == this)
                         AddEventTime((VangerUnit*)(n->Obj),aiAddAttack,AI_ADD_ATTACK);
                     break;
             };
         };
         n++;
     };
     aiResolveWayEnable = 0;
     aiLocalTarget = NULL;
     if(!aiResolveFind.Num){
         if(Status & SOBJ_ACTIVE) GamerOrderInit();
         else MainOrderInit();
     };
 };
References ACI_KERNOBOO, ACI_PIPETKA, ActD, StuffObject::ActIntBuffer, AddAttackTime, AddEvent(), AddEventTime(), AddFindResolve(), AI_ACTION_FARMER, AI_ADD_ATTACK, AI_ADD_BACK_COLLISION, AI_ADD_FRONT_COLLISION, AI_ADD_SIDE_COLLISION, AI_EVENT_CAPTURE, AI_EVENT_COLLISION, AI_EVENT_DROP, AI_EVENT_ITEM, AI_EVENT_VANGER, AI_MAX_ALARM_TIME, AI_RESOLVE_STATUS_TARGET, AI_STATUS_FLY, AI_STATUS_IMPULSE, AI_STATUS_NONE, AI_STATUS_TARGET, AI_STATUS_TNT, AI_STATUS_WHEEL, aiActionID, aiFactorType::aiAddAlarm, aiFactorType::aiAddAttack, aiFactorType::aiAddBackCollision, aiFactorType::aiAddFrontCollision, aiFactorType::aiAddSideCollision, aiFactorType::aiAddView, aiAlarmTime, aiDamage, aiDamageData, aiFactorType::aiDeltaLevel, aiEvent, aiFirstItem, aiGlobalEventData, aiItemRadius, aiLocalTarget, aiFactorType::aiMainLevel, aiFactorType::aiMaxAlarm, aiFactorType::aiMaxView, aiNumGlobalEvent, aiReadEvent, aiRealxRadius, aiRelaxData, aiRelaxTime, aiRelaxTimeMax, aiResolveFind, aiResolveWayEnable, aiScanDist, aiSecondItem, aiStatus, aiVangerRadius, ActionUnit::Angle, uvsUnitType::Armor, SensorTypeList::ARMOR_UPDATE, ArmorAlarm, uvsVanger::break_harvest(), CalcAiFactor(), CheckAmmo(), aiResolveList::ClearResolve(), CoptePoint, actintItemData::data1, DeltaTractionTime, uvsUnitType::DeviceData, aiListType::Disconnect(), Object::draw_mode, ExternalDraw, FarmerD, aiResolveList::FindResolve(), GamerOrderInit(), GET_TERRAIN, GetAllert(), getDistX(), getDistY(), GetNearSensor(), H_SIZE, aiUnitEvent::ID, ID_BULLET, ID_VANGER, ItemD, vrtMap::lineT, LowAmmo, LowArmor, MainOrderInit(), MapLineTrace(), MAX_CHECK_UNVISIBLE_FACTOR, MAX_CHECK_VISIBLE_FACTOR, MAX_TRACTION_CHECK_DELTA, MAX_TRACTION_CHECK_TIME, MAX_WALL_TIME, MaxSeed, TrackUnit::MaxWayCount, aiListElement::Next, StuffObject::NextDeviceList, NORMAL_DRAW_MODE, NULL, UnitListType::Num, aiListType::Num, aiUnitEvent::Obj, PI, Vector::psi(), GeneralObject::R_curr, Object::radius, aiUnitEvent::Refresh, RND(), ActionUnit::RotMat, rPI, SeedNum, SOBJ_ACTIVE, SpeedFactorTime, aiUnitEvent::Subj, UnitList::Tail, aiListType::Tail, TrackUnit::TargetPoint, aiUnitEvent::Time, aiUnitResolve::Time, TractionValue, actintItemData::type, UNIT_ORDER_SENSOR, UNIT_ORDER_STUFF, UNVISIBLE, uvsCurrentCycle, uvsKernel::uvsPoint, VERTICAL_WALL_COLLISION, VISIBLE, vMap, TrackLinkType::vPoint, WallCollisionTime, ActionDispatcher::WorldSeedNum, Object::x, Vector::x, Object::y, Vector::y, and Vector::z.
Referenced by InitEnvironment().
ResolveHandler()
void VangerUnit::ResolveHandler (aiUnitResolve * p)
ResolveHandlerAttack()
void VangerUnit::ResolveHandlerAttack (aiUnitResolve * p)
 {
     GunSlot* s;
     int dx,dy;
     int i;
     if(p->rStatus & AI_RESOLVE_STATUS_VAR){
         if(p->Level > 0) p->Level--;
         else p->rStatus |= AI_RESOLVE_STATUS_DISCONNECT;
     };
     dx = getDistX(((p->Obj).VangerT)->R_curr.x,R_curr.x);
     dy = getDistY(((p->Obj).VangerT)->R_curr.y,R_curr.y);
     if(dx < ViewRadius && dy < ViewRadius){
         s = NULL;
         if(Visibility == VISIBLE || (p->Obj.VangerT)->Visibility == VISIBLE){
             for(i = 0;i < ItemMatrix->NumSlot;i++){
                 s = &GunSlotData[ItemMatrix->nSlot[i]];
                 if(s->pData && s->GunStatus == GUN_READY && s->CheckTarget(p->Obj.VangerT))
                     s->Fire();
             };
         }else{
             for(i = 0;i < ItemMatrix->NumSlot;i++){
                 s = &GunSlotData[ItemMatrix->nSlot[i]];
                 if(s->pData)
                     p->Obj.VangerT->BulletCollision(s->pData->Power / s->pData->WaitTime,this);
             };
         };
     };
 };
References AI_RESOLVE_STATUS_DISCONNECT, AI_RESOLVE_STATUS_VAR, BulletCollision(), GunSlot::CheckTarget(), GunSlot::Fire(), getDistX(), getDistY(), GUN_READY, GunSlotData, GunSlot::GunStatus, uvsUnitType::ItemMatrix, aiUnitResolve::Level, UnitItemMatrix::nSlot, NULL, UnitItemMatrix::NumSlot, aiUnitResolve::Obj, GunSlot::pData, BulletControlType::Power, aiUnitResolve::rStatus, UnitOrderType::VangerT, ActionUnit::ViewRadius, VISIBLE, and WorldBulletTemplate::WaitTime.
Referenced by InitEnvironment().
ResolveHandlerFind()
void VangerUnit::ResolveHandlerFind (aiUnitResolve * p)
 {
     int dx,dy;
     StuffObject* c;
     Vector vCheck;
     if(aiResolveWayEnable == 0){
         if(p->rStatus & AI_RESOLVE_STATUS_VAR){
             if(p->Level > 0) p->Level--;
             else ResolveFindDestroy(p);
         };
         switch(p->Type){
             case UNIT_ORDER_VANGER:
                 TargetPoint.vPoint = (p->Obj.ActionT)->R_curr;
                 CheckFind(p,TargetPoint.vPoint);
                 break;
             case UNIT_ORDER_STUFF:
                 if((p->Obj.StuffT)->Owner) TargetPoint.vPoint = ((p->Obj.StuffT)->Owner)->R_curr;
                 else TargetPoint.vPoint = (p->Obj.StuffT)->R_curr;
                 if(p->rStatus & AI_RESOLVE_STATUS_VIEW){
                     dy = abs(getDistY(TargetPoint.vPoint.y,R_curr.y));
                     if(dy < ViewRadius){
                         dx = abs(getDistX(TargetPoint.vPoint.x,R_curr.x));
                         if(dx < ViewRadius) ResolveFindDestroy(p);
                     };
                 }else{
                     if(!(p->Obj.StuffT)->Owner && (p->Obj.StuffT)->Visibility == UNVISIBLE && Visibility == UNVISIBLE){
                         dx = abs(getDistX(((p->Obj).StuffT)->R_curr.x,R_curr.x));
                         dy = abs(getDistY(((p->Obj).StuffT)->R_curr.y,R_curr.y));
                         if(dx < radius*4 && dy < radius*4){
                             (p->Obj.StuffT)->Touch(this);
                             Touch(p->Obj.StuffT);
 //                          p->rStatus |= AI_RESOLVE_STATUS_DISCONNECT;
                         };
                     };
                 };
                 break;
             case UNIT_ORDER_SENSOR:
                 TargetPoint.vPoint = (p->Obj.SensorT)->R_curr;
                 CheckFind(p,TargetPoint.vPoint);
                 break;
             case UNIT_ORDER_PASSAGE:
                 TargetPoint.vPoint = (p->Obj.PassageT)->ActionLink->R_curr;
                 aiLocalTarget = p;
                 CheckFind(p,TargetPoint.vPoint);
                 break;
             case UNIT_ORDER_ENTER:
                 TargetPoint.vPoint = ((p->Obj.EnterT)->GetNearCenter(R_curr))->R_curr;
                 aiLocalTarget = p;
                 CheckFind(p,TargetPoint.vPoint);
                 break;
             case UNIT_ORDER_DOLL:
                 TargetPoint.vPoint = Vector((p->Obj.DollT)->pos_x,(p->Obj.DollT)->pos_y,0);
                 vCheck = Vector(getDistX((p->Obj.DollT)->pos_x,R_curr.x),getDistX((p->Obj.DollT)->pos_y,R_curr.y),0);
                 if(vCheck.vabs() < (int)(RND(radius*5))){
                     c = GetStuffObject(this,ACI_EMPTY_CIRTAINER);
                     if(c){
                         c->ActIntBuffer.data0 = p->Obj.DollT -> getCirt((p->Obj.DollT)->pos_x,(p->Obj.DollT)->pos_y);
                         c->ActIntBuffer.data1 = 1 << (p->Obj.DollT) -> gIndex;
                         c->ActIntBuffer.type = uvsSetItemType(c->uvsDeviceType,c->ActIntBuffer.data0,c->ActIntBuffer.data1);
                     };
                     uvsPoint->goHome();
                     ResolveFindDestroy(p);
                 };
                 break;
             case UNIT_ORDER_VECTOR:
                 TargetPoint.vPoint.x = (p->Obj.vT).x;
                 TargetPoint.vPoint.y = (p->Obj.vT).y;
                 TargetPoint.vPoint.z = 0;
                 CheckFind(p,TargetPoint.vPoint);
                 break;
         };
         if(!(OtherFlag & MECHOS_CALC_WAY)){
             p->Time++;
             if(p->Time > MaxWayCount){
                 HideTrack.GetPosition(&TargetPoint);
                 WayInit();
                 p->Time = 0;
             };
         };
         switch(aiMoveMode){
             case AI_MOVE_POINT:
                 if(!CheckReturn2Track()){
                     aiMoveMode = AI_MOVE_TRACK;
                     OtherFlag |= MECHOS_RECALC_FRONT;
                 };
                 break;
             case AI_MOVE_TRACK:
                 if(CheckReturn2Track()){
                     if(PointStatus & TRK_NODE_MASK){
                         if((TargetPoint.PointStatus & TRK_NODE_MASK) && pNode == TargetPoint.pNode)
                             aiMoveMode = AI_MOVE_POINT;
                     }else{
                         if((TargetPoint.PointStatus & TRK_BRANCH_MASK) && pBranch == TargetPoint.pBranch &&
                             (pNextLink == TargetPoint.pNextLink || pPrevLink == TargetPoint.pNextLink || pNextLink == TargetPoint.pPrevLink || pPrevLink == TargetPoint.pPrevLink))
                                 aiMoveMode = AI_MOVE_POINT;
                     };
                 };
                 break;
         };
         aiResolveWayEnable = 1;
     }else{
         switch(p->Type){
             case UNIT_ORDER_VANGER:
                 CheckFind(p,(p->Obj.ActionT)->R_curr);
                 break;
             case UNIT_ORDER_STUFF:
                 if(p->rStatus & AI_RESOLVE_STATUS_VIEW){
                     dy = abs(getDistY((p->Obj.StuffT)->R_curr.y,R_curr.y));
                     if(dy < ViewRadius){
                         dx = abs(getDistX((p->Obj.StuffT)->R_curr.x,R_curr.x));
                         if(dx < ViewRadius) ResolveFindDestroy(p);
                     };
                 }else{
                     if(!(p->Obj.StuffT)->Owner && (p->Obj.StuffT)->Visibility == UNVISIBLE && Visibility == UNVISIBLE){
                         dx = abs(getDistX(((p->Obj).StuffT)->R_curr.x,R_curr.x));
                         dy = abs(getDistY(((p->Obj).StuffT)->R_curr.y,R_curr.y));
                         if(dx < radius*4 && dy < radius*4){
                             (p->Obj.StuffT)->Touch(this);
                             Touch(p->Obj.StuffT);
                             ResolveFindDestroy(p);
                         };
                     };
                 };
                 break;
             case UNIT_ORDER_SENSOR:
                 CheckFind(p,(p->Obj.SensorT)->R_curr);
                 break;
             case UNIT_ORDER_PASSAGE:
                 CheckFind(p,(p->Obj.PassageT)->ActionLink->R_curr);
                 break;
             case UNIT_ORDER_ENTER:
                 CheckFind(p,((p->Obj.EnterT)->GetNearCenter(R_curr))->R_curr);
                 break;
             case UNIT_ORDER_DOLL:
                 TargetPoint.vPoint = Vector((p->Obj.DollT)->pos_x,(p->Obj.DollT)->pos_y,0);
                 vCheck = Vector(getDistX((p->Obj.DollT)->pos_x,R_curr.x),getDistX((p->Obj.DollT)->pos_y,R_curr.y),0);
                 if(vCheck.vabs() < (int)(RND(radius*5))){
                     c = GetStuffObject(this,ACI_EMPTY_CIRTAINER);
                     if(c){
                         c->ActIntBuffer.data0 = p->Obj.DollT -> getCirt((p->Obj.DollT)->pos_x,(p->Obj.DollT)->pos_y);
                         c->ActIntBuffer.data1 = 1 << (p->Obj.DollT) -> gIndex;
                         c->ActIntBuffer.type = uvsSetItemType(c->uvsDeviceType,c->ActIntBuffer.data0,c->ActIntBuffer.data1);
                     };
                     uvsPoint->goHome();
                     ResolveFindDestroy(p);
                 };
                 break;
             case UNIT_ORDER_VECTOR:
                 CheckFind(p,Vector(p->Obj.vT.x,p->Obj.vT.y,0));
                 break;
         };
     };
 };
References ACI_EMPTY_CIRTAINER, StuffObject::ActIntBuffer, UnitOrderType::ActionT, AI_MOVE_POINT, AI_MOVE_TRACK, AI_RESOLVE_STATUS_VAR, AI_RESOLVE_STATUS_VIEW, aiLocalTarget, TrackUnit::aiMoveMode, aiResolveWayEnable, CheckFind(), CheckReturn2Track(), actintItemData::data0, actintItemData::data1, UnitOrderType::DollT, UnitOrderType::EnterT, getDistX(), getDistY(), TrackType::GetPosition(), GetStuffObject(), uvsVanger::goHome(), HideTrack, aiUnitResolve::Level, TrackUnit::MaxWayCount, MECHOS_CALC_WAY, MECHOS_RECALC_FRONT, aiUnitResolve::Obj, ActionUnit::OtherFlag, UnitOrderType::PassageT, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, Object::radius, ResolveFindDestroy(), RND(), aiUnitResolve::rStatus, UnitOrderType::SensorT, UnitOrderType::StuffT, TrackUnit::TargetPoint, aiUnitResolve::Time, Touch(), TRK_BRANCH_MASK, TRK_NODE_MASK, actintItemData::type, aiUnitResolve::Type, UNIT_ORDER_DOLL, UNIT_ORDER_ENTER, UNIT_ORDER_PASSAGE, UNIT_ORDER_SENSOR, UNIT_ORDER_STUFF, UNIT_ORDER_VANGER, UNIT_ORDER_VECTOR, UNVISIBLE, StuffObject::uvsDeviceType, uvsKernel::uvsPoint, uvsSetItemType(), Vector::vabs(), ActionUnit::ViewRadius, TrackLinkType::vPoint, UnitOrderType::vT, TrackUnit::WayInit(), Object::x, Vector::x, UnitOrderType::x, Object::y, Vector::y, UnitOrderType::y, and Vector::z.
Referenced by InitEnvironment().
ResolveHandlerForce()
void VangerUnit::ResolveHandlerForce (aiUnitResolve * p)
SendCameraData()
void VangerUnit::SendCameraData (void)
 {
     events_out < (short int)ViewX;
     events_out < (short int)ViewY;
     events_out < (short int)ViewZ;
     events_out < (short int)TurnAngle;
     events_out < (short int)SlopeAngle;
     events_out < (short int)curGMap -> xside;
     events_out < (short int)curGMap -> yside;
 }
References curGMap, events_out, SlopeAngle, TurnAngle, ViewX, ViewY, and ViewZ.
SensorQuant()
void VangerUnit::SensorQuant (void)
 {
     Vector vCheck,vTrack;
     int d,a,l;
     int i;
 #ifdef TEST_TRACK
     double ddz,dda,ddb;
     DBV ddv;
 #endif
     uvsWorld* w1;
     uvsWorld* w2;
     if(!ExternalLock && ExternalLastSensor != ExternalSensor){
         if(ExternalSensor){
             switch(ExternalSensor->SensorType){
                 case SensorTypeList::SPOT:
                     if(Status & SOBJ_AUTOMAT){
                         if(aiLocalTarget && aiLocalTarget->Type == UNIT_ORDER_ENTER && (aiLocalTarget->Obj).EnterT == ((EnterEngine*)(ExternalSensor->Owner))->Owner){
                             ExternalMode = EXTERNAL_MODE_SPOT_IN;
                             ExternalLock = 1;
                             if(Visibility == VISIBLE){
                                 ExternalTime = ExternalSensor->Owner->DeactiveTime;
 //                              SOUND_ENTRANCE();
                             }else ExternalTime = 0;
                             ExternalObject = ExternalSensor;
                             switch_analysis(1);
                         };
                     }else{
                         ExternalMode = EXTERNAL_MODE_SPOT_IN;
                         ExternalLock = 1;
                         if(Visibility == VISIBLE){
 //                          SOUND_ENTRANCE();
                             ExternalTime = ExternalSensor->Owner->DeactiveTime;
                         }else ExternalTime = 0;
                         ExternalObject = ExternalSensor;
                         switch_analysis(1);
 //                      aciSendEvent2actint(ACI_LOCK_INTERFACE,NULL);
                     };
                     break;
                 case SensorTypeList::ESCAVE:
                     if(Status & SOBJ_AUTOMAT){
                         if(aiLocalTarget && aiLocalTarget->Type == UNIT_ORDER_ENTER && (aiLocalTarget->Obj).EnterT == ((EnterEngine*)(ExternalSensor->Owner))->Owner){
                             if(Visibility == VISIBLE){
                                 ExternalTime = ExternalSensor->Owner->DeactiveTime;
 //                              SOUND_ENTRANCE();
                             }else ExternalTime = 0;
                             ExternalMode = EXTERNAL_MODE_ESCAVE_IN;
                             ExternalLock = 1;
                             ExternalObject = ExternalSensor;
                             switch_analysis(1);
                         };
                     }else{
                         if(Visibility == VISIBLE){
                             ExternalTime = ExternalSensor->Owner->DeactiveTime;
 //                          SOUND_ENTRANCE();
                         }else ExternalTime = 0;
                         ExternalMode = EXTERNAL_MODE_ESCAVE_IN;
                         ExternalLock = 1;
                         ExternalObject = ExternalSensor;
                         switch_analysis(1);
 //                      aciSendEvent2actint(ACI_LOCK_INTERFACE,NULL);
                     };
                     break;
                 case SensorTypeList::PASSAGE:
                     if(Status & SOBJ_AUTOMAT){
                         if(aiLocalTarget && aiLocalTarget->Type == UNIT_ORDER_PASSAGE && ((aiLocalTarget->Obj).PassageT)->ActionLink == ExternalSensor){
 //                          if(MainOrderID != UVS_TARGET::PASSAGE)
 //                              ErrH.Abort("Bad Target Sesion");
 //                          SensorDebugFlag |= 4;
                             ExternalMode = EXTERNAL_MODE_PASS_IN;
                             if(Visibility == VISIBLE){
                                 ExternalTime = ExternalSensor->Owner->DeactiveTime;
                                 CreateParticleRotor(ExternalSensor->R_curr,ExternalSensor->radius);
                                 if(Status & SOBJ_ACTIVE){
                                     camera_direct(ExternalSensor->R_curr.x,ExternalSensor->R_curr.y,1 << 7,0,0,ExternalTime + 1);
 //                                  StartHidePassage(ExternalTime);
                                     PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
                                 };
                             }else ExternalTime = 0;
                             ExternalLock = 1;
                             ExternalDraw = 0;
                             ExternalObject = ExternalSensor;
                             switch_analysis(1);
                         };
                     }else{
                         if(aciWorldLinkExist(((PassageEngine*)(ExternalSensor->Owner))->uvsPort->Pworld->gIndex,((PassageEngine*)(ExternalSensor->Owner))->uvsPort->Poutput->gIndex)){
                             if(!ActD.PassageTouchEnable){
                                 PassageCount--;
                                 aciSendEvent2actint(ACI_LOCK_INTERFACE,NULL);
                                 ExternalMode = EXTERNAL_MODE_PASS_IN;
                                 if(Visibility == VISIBLE){
                                     ExternalTime = ExternalSensor->Owner->DeactiveTime;
                                     CreateParticleRotor(ExternalSensor->R_curr,ExternalSensor->radius);
                                     if(Status & SOBJ_ACTIVE){
                                         camera_direct(ExternalSensor->R_curr.x,ExternalSensor->R_curr.y,1 << 7,0,0,ExternalTime + 1);
                                         PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
                                     };
                                 }else ExternalTime = 0;
                                 ExternalLock = 1;
                                 ExternalDraw = 0;
                                 ExternalObject = ExternalSensor;
                                 switch_analysis(1);
                                 StopCDTRACK();
                                 NetFunction83Time = NetGlobalTime;
                                 ShellUpdateFlag = 1;
                                 if(CurrentWorld == WORLD_ARKONOY && (PowerFlag & VANGER_POWER_RUFFA_GUN))
                                     uvsCheckKronIventTabuTask(UVS_KRON_EVENT::ARK_NOY,0);
                             };
                         }else{
                             impulse(Vector(32 - RND(64),32 - RND(64),64),30,0);
                             SOUND_FAILEDPASS()
                         };
                     };
                     break;
                 case SensorTypeList::TRAIN:
                 case SensorTypeList::TRAP:
                     if(ExternalSensor->Index == 1){
                         if(((TrainEngine*)(ExternalSensor->Owner))->LockFlag & DOOR_CLOSE_LOCK) break;
                         ExternalObject = ((TrainEngine*)(ExternalSensor->Owner))->TrainLink[0];
                     }else{
                         if(((TrainEngine*)(ExternalSensor->Owner))->LockFlag & DOOR_OPEN_LOCK) break;
                         ExternalObject = ((TrainEngine*)(ExternalSensor->Owner))->TrainLink[1];
                     };
                     ExternalMode = EXTERNAL_MODE_MOVE;
                     ExternalLock = 1;
                     ExternalTime = ExternalSensor->Owner->ActiveTime;
                     ExternalTime2 = ExternalSensor->Owner->DeactiveTime;
                     ExternalDraw = 1;
                     switch_analysis(1);
                     break;
                 case SensorTypeList::EARTH_PASSAGE:
                     if(GamerResult.earth_unable && aciCurJumpCount > 0){
                         ExternalMode = EXTERNAL_MODE_EARTH_IN;
                         aciSendEvent2actint(ACI_LOCK_INTERFACE,NULL);
                         if(Visibility == VISIBLE){
                             ExternalTime = ROTOR_PROCESS_LIFE_TIME;
                             CreateParticleRotor(ExternalSensor->R_curr,ExternalSensor->radius);
                             if(Status & SOBJ_ACTIVE){
                                 camera_direct(ExternalSensor->R_curr.x,ExternalSensor->R_curr.y,1 << 7,0,0,ExternalTime + 1);
                                 PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
         //                      StartHidePassage(ExternalTime);
                             };
                         }else ExternalTime = 0;
                         ExternalLock = 1;
                         ExternalDraw = 0;
                         ExternalObject = ExternalSensor;
                         switch_analysis(1);
                         StopCDTRACK();
                     }else impulse(Vector(32 - RND(64),32 - RND(64),RND(64)),RND(30),RND(10));
                     break;
             };
         };
     };
     switch(ExternalMode){
 #ifdef TEST_TRACK
         case EXTERNAL_MODE_TEST:
             vCheck = Vector(getDistX(pNextLink->x,pPrevLink->x),pNextLink->y - pPrevLink->y,0);
             if(Speed < 0/* || (!(dynamic_state & TRACTION_WHEEL_TOUCH) && !(dynamic_state & STEER_WHEEL_TOUCH))*/)
                 break;
             if(PointStatus == TRK_IN_NODE){
                 pNode->TrackCount++;
                 pNode->Level = test_whether_there_is_not_something_above();
             }else{
                 if(PointStatus == TRK_IN_BRANCH){
                     if(pPrevLink != TestPrevLink){
                         TestLinkTime = 1;
                         TestPrevLink = pPrevLink;
                     }else TestLinkTime++;
                     pNextLink->TrackCount++;
                     pPrevLink->TrackCount++;
                     section_prepare(pPrevLink->xl,pPrevLink->yl,pNextLink->xl,pNextLink->yl,pNextLink->xr,pNextLink->yr,pPrevLink->xr,pPrevLink->yr,R_curr.z,
                     dda,ddb,ddz,ddv);
                     pNextLink->z += (int)(ddz);
                     pPrevLink->z += (int)(ddz);
                     pNextLink->Speed += Speed;
                     pPrevLink->Speed += Speed;
                     pNextLink->z >>= 1;
                     pPrevLink->z >>= 1;
                     pNextLink->Speed >>= 1;
                     pPrevLink->Speed >>= 1;
                     pNextLink->Level = test_whether_there_is_not_something_above();
                     pPrevLink->Level = pNextLink->Level;
                     pPrevLink->Time = TestLinkTime;
 //                  pPrevLink->Status = CurrentLinkStatus;
 //                  pNextLink->Status = CurrentLinkStatus;
                 };
             };
             break;
         case EXTERNAL_MODE_TEST_MOVE:
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_TEST;
                 switch_analysis(0);
                 ExternalLock = 0;
                 ExternalDraw = 1;
                 vCheck = Vector(getDistX(pNextLink->x,pPrevLink->x),pNextLink->y - pPrevLink->y,0);
                 set_3D(SET_3D_CHOOSE_LEVEL,vGoTest.x,vGoTest.y,vGoTest.z,radius / 2,-vCheck.psi(),0);
             }else{
                 vCheck = Vector(getDistX(vGoTest.x,R_curr.x),vGoTest.y - R_curr.y,vGoTest.z - R_curr.z);
                 d = vCheck.vabs();
                 l = d / ExternalTime;
                 vCheck *= l;
                 vCheck /= d;
                 R_curr += vCheck;
                 cycleTor(R_curr.x,R_curr.y);
                 set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,0,Speed);
                 ExternalTime--;
             };
             break;
 #endif
         case EXTERNAL_MODE_MOVE:
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 ExternalDraw = 1;
                 switch_analysis(0);
                 if(Status & SOBJ_ACTIVE && !(((TrainEngine*)(ExternalObject->Owner))->TabuUse)){
                     uvsCheckKronIventTabuTask(UVS_KRON_EVENT::CRYPT,1);
                     ((TrainEngine*)(ExternalObject->Owner))->TabuUse = 1;
                 };
                 ExternalSensor = ExternalObject;
             }else{
                 vCheck = Vector(getDistX(ExternalObject->R_curr.x,R_curr.x),ExternalObject->R_curr.y - R_curr.y,ExternalObject->R_curr.z - R_curr.z);
                 d = vCheck.vabs();
                 a = vCheck.psi();
                 l = d / ExternalTime;
                 if(Speed < 0) Speed = 0;
                 if(ExternalTime2 > 0){
                     Speed += (l - Speed) / ExternalTime2;
                     Angle = rPI(Angle + (a - Angle) / ExternalTime2);
                     ExternalTime2--;
                 }else{
                     Speed = l;
                     Angle = a;
                 };
                 vCheck *= Speed;
                 vCheck /= d;
                 R_curr += vCheck;
                 cycleTor(R_curr.x,R_curr.y);
                 if(Visibility == VISIBLE) set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,-Angle,Speed);
                 ExternalTime--;
             };
             break;
         case EXTERNAL_MODE_TRANSPORTER:
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 ExternalDraw = 1;
                 switch_analysis(0);
                 ExternalSensor = ExternalObject;
             }else{
                 vCheck = Vector(getDistX(ExternalObject->R_curr.x,R_curr.x),ExternalObject->R_curr.y - R_curr.y,ExternalObject->R_curr.z - R_curr.z);
                 d = vCheck.vabs();
                 a = vCheck.psi();
                 l = d / ExternalTime;
                 if(Speed < 0) Speed = 0;
                 if(ExternalTime2 > 0){
                     Speed += (l - Speed) / ExternalTime2;
                     Angle = rPI(Angle + (a - Angle) / ExternalTime2);
                     ExternalTime2--;
                 }else{
                     Speed = l;
                     Angle = a;
                 };
                 vCheck *= Speed;
                 vCheck /= d;
                 R_curr += vCheck;
                 cycleTor(R_curr.x,R_curr.y);
                 if(Visibility == VISIBLE) set_3D(SET_3D_DIRECT_PLACE,R_curr.x,R_curr.y,R_curr.z,0,-Angle,Speed);
                 ExternalTime--;
             };
             break;
         case EXTERNAL_MODE_PASS_OUT:
             ExternalTime--;
             if(Visibility == VISIBLE && ActD.Active) SOUND_PASSAGE(getDistX(ActD.Active->R_curr.x,R_curr.x));
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 ExternalDraw = 1;
                 switch_analysis(0);
                 ExternalSensor = ExternalObject;
                 if(Status & SOBJ_ACTIVE)
                     aciSendEvent2actint(ACI_UNLOCK_INTERFACE,NULL);
             };
             break;
         case EXTERNAL_MODE_PASS_IMPULSE:
             ExternalTime--;
             if(Visibility == VISIBLE && ActD.Active) SOUND_PASSAGE(getDistX(ActD.Active->R_curr.x,R_curr.x));
             if(ExternalTime == EXTERNAL_IMPULSE_TIME){
                 ExternalDraw = 1;
                 switch_analysis(0);
                 if(Status & SOBJ_ACTIVE)
                     aciSendEvent2actint(ACI_UNLOCK_INTERFACE,NULL);
             }else{
                 if(ExternalTime <= 0){
                     ExternalMode = EXTERNAL_MODE_NORMAL;
                     ExternalLock = 0;
                     ExternalSensor = ExternalObject;
                 }else{
                     if(ExternalTime < EXTERNAL_IMPULSE_TIME)
                         impulse(ExternalAngle,8 * ExternalTime / EXTERNAL_IMPULSE_TIME);
                 };
             };
             break;
         case EXTERNAL_MODE_ESCAVE_OUT:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 switch_analysis(0);
 //              set_3D(SET_3D_CHOOSE_LEVEL,R_curr.x,R_curr.y,R_curr.z,0,-Angle,0);
                 ExternalSensor = ExternalObject;
 //              if(Status & SOBJ_ACTIVE)
 //                  aciSendEvent2actint(ACI_UNLOCK_INTERFACE,NULL);
             };
             break;
         case EXTERNAL_MODE_SPOT_OUT:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 switch_analysis(0);
                 ExternalSensor = ExternalObject;
 //              if(Status & SOBJ_ACTIVE)
 //                  aciSendEvent2actint(ACI_UNLOCK_INTERFACE,NULL);
             };
             break;
         case EXTERNAL_MODE_SPOT_IN:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 uvsPoint -> Pspot = (uvsSpot*)(((EnterEngine*)(ExternalObject->Owner))->Owner->Owner);
                 uvsPoint -> Pescave = NULL;
                 Go2Universe();
                 uvsPoint -> Event(UVS_EVENT::SPOT_ARRIVAL);
                 Status |= SOBJ_DISCONNECT;
                 if(Status & SOBJ_ACTIVE){
                     ChangeArmor = Armor;
                     ChangeEnergy = Energy;
                 };
             };
             break;
         case EXTERNAL_MODE_ESCAVE_IN:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 uvsPoint -> Pescave = (uvsEscave*)(((EnterEngine*)(ExternalObject->Owner))->Owner->Owner);
                 uvsPoint -> Pspot = NULL;
                 Go2Universe();
                 uvsPoint -> Event(UVS_EVENT::ESCAVE_ARRIVAL);
                 Status |= SOBJ_DISCONNECT;
                 if(Status & SOBJ_ACTIVE){
                     ChangeArmor = Armor;
                     ChangeEnergy = Energy;
                 };
             };
             break;
         case EXTERNAL_MODE_DARK:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalTime = 10;
                 PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
                 ExternalMode = EXTERNAL_MODE_EARTH_PREPARE;
             };
             break;
         case EXTERNAL_MODE_LIGHT:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalTime = 5;
                 PalCD.Set(CPAL_PASSAGE_FROM,ExternalTime);
                 ExternalMode = EXTERNAL_MODE_DARK;
                 for(i = 0;i < 5;i++)
                     EffD.CreateParticleGenerator(R_curr,R_curr,Vector(5,0,0)*DBM((int)(RND(PI*2)),Z_AXIS));
             };
             break;
         case EXTERNAL_MODE_EARTH_PREPARE:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 if(ChangeWorldConstraction != -1 && ChangeWorldConstraction != CurrentWorld){
                     uvsPoint -> Pworld = WorldTable[ChangeWorldConstraction];
                     uvsPoint -> Pescave = uvsPoint->Pworld->escT[0];
                     uvsPoint -> Pspot = NULL;
                     uvsPoint -> Event(UVS_EVENT::GO_NEW_ESCAVE);
                 }else{
                      uvsPoint -> Pescave = uvsPoint->Pworld->escT[0];
                      if(uvsPoint -> Pescave){
                         uvsPoint -> Pspot = NULL;
                         uvsPoint -> Event(UVS_EVENT::ESCAVE_ARRIVAL);
                     }else{
                         uvsPoint -> Pescave = NULL;
                         uvsPoint -> Pspot = uvsPoint->Pworld->sptT[0];
                         uvsPoint -> Event(UVS_EVENT::SPOT_ARRIVAL);
                     };
                 };
                 Go2Universe();
                 ChangeWorldConstraction = -1;
                 Status |= SOBJ_DISCONNECT;
             };
             break;
         case EXTERNAL_MODE_PASS_IN:
             ExternalTime--;
             if(Visibility == VISIBLE && ActD.Active) {
                 SOUND_PASSAGE(getDistX(ActD.Active->R_curr.x,R_curr.x));
             }
             if(ExternalTime & 3) {
                 EffD.CreateDeform(
                     ExternalObject->R_curr + Vector(
                         PASSING_WAVE_RADIUS - realRND(PASSING_WAVE_RADIUS2),
                         PASSING_WAVE_RADIUS - realRND(PASSING_WAVE_RADIUS2),
                         83
                     ),
                     1,
                     PASSING_WAVE_PROCESS
                 );
             }
             if(!(Status & SOBJ_ACTIVE)){
                 if(ExternalTime <= 0){
                     ExternalMode = EXTERNAL_MODE_NORMAL;
                     ExternalLock = 0;
                     Go2Universe();
                     if(!NetworkON){
                         uvsPoint -> Ppassage = ((PassageEngine*)(ExternalObject->Owner))->uvsPort;
                         uvsPoint -> Event(UVS_EVENT::PASSAGE_ARRIVAL);
                     };
                     Status |= SOBJ_DISCONNECT;
                 };
             }else{
                 if(ExternalTime <= 0){
                     ExternalMode = EXTERNAL_MODE_NORMAL;
                     ExternalLock = 0;
                     uvsPoint -> Ppassage = ((PassageEngine*)(ExternalObject->Owner))->uvsPort;
                     w1 = ((PassageEngine*)(ExternalObject->Owner))->uvsPort->Poutput;
                     w2 = ((PassageEngine*)(ExternalObject->Owner))->uvsPort->Pworld;
                     for(i = 0;i < w1->pssTmax;i++){
                         if(w1->pssT[i]->Poutput == w2){
                             NewWorldX = w1->pssT[i]->pos_x;
                             NewWorldY = w1->pssT[i]->pos_y;
                         };
                     };
                     Go2Universe();
                     ChangeArmor = Armor;
                     ChangeEnergy = Energy;
                     uvsPoint -> Event(UVS_EVENT::PASSAGE_ARRIVAL);
                     Status |= SOBJ_DISCONNECT;
                 };
             };
             break;
         case EXTERNAL_MODE_SIGN_IN:
             ExternalTime--;
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_FREE_IN;
                 ExternalTime = ROTOR_PROCESS_LIFE_TIME;
                 CreateParticleRotor(R_curr,83);
 //              StartHidePassage(ExternalTime);
                 PalCD.Set(CPAL_HIDE_PASSAGE,ExternalTime);
 //              ExternalLock = 1;
                 ExternalDraw = 0;
 //              ExternalObject = NULL;
                 switch_analysis(1);
             };
             break;
         case EXTERNAL_MODE_FREE_IN:
             ExternalTime--;
             if(Visibility == VISIBLE && ActD.Active) SOUND_PASSAGE(getDistX(ActD.Active->R_curr.x,R_curr.x));
             if(ExternalTime <= 0){
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 Go2Universe();
                 if(NetworkON && my_server_data.GameType == PASSEMBLOSS && UsedCheckNum >= GloryPlaceNum){
                     GameOverID = GAME_OVER_NETWORK;
                     Status |= SOBJ_DISCONNECT;
                     GameQuantReturnValue = RTO_LOADING3_ID;
                 }else{
                     uvsPoint -> Event(UVS_EVENT::GO_NEW_WORLD);
                     NewWorldX = ViewX;
                     NewWorldY = ViewY;
                     Status |= SOBJ_DISCONNECT;
                     ChangeArmor = Armor;
                     ChangeEnergy = Energy;
                 };
             };
             break;
         case EXTERNAL_MODE_EARTH_IN:
             if(Visibility == VISIBLE && ActD.Active) SOUND_PASSAGE(getDistX(ActD.Active->R_curr.x,R_curr.x));
             if(ExternalTime & 3) EffD.CreateDeform(R_curr + Vector(PASSING_WAVE_RADIUS - realRND(PASSING_WAVE_RADIUS2),PASSING_WAVE_RADIUS - realRND(PASSING_WAVE_RADIUS2),83),1,PASSING_WAVE_PROCESS);
             ExternalTime--;
             if(ExternalTime <= 0){
 //              ExternalMode = EXTERNAL_MODE_NORMAL;
 //              ExternalLock = 0;
                 uvsPoint -> Pescave = NULL;
                 uvsPoint -> Pspot = NULL;
                 uvsPoint -> Ppassage = NULL;
                 Go2Universe();
                 if(ActD.LuckyFunction)
                     GameOverID = GAME_OVER_LUCKY;
                 else{
                     if(ActD.ThreallDestroy){
                         if(ActD.SpobsDestroy) GameOverID = GAME_OVER_ALL_LOCKED;
                         else GameOverID = GAME_OVER_INFERNAL_LOCKED;
                     }else{
                         if(ActD.SpobsDestroy) GameOverID = GAME_OVER_SPOBS_LOCKED;
                         else GameOverID = GAME_OVER_LUCKY;
                     };
                 };
 //              if(!NetworkON) uvsPoint -> destroy(PlayerDestroyFlag);
                 Status |= SOBJ_DISCONNECT;
                 GameQuantReturnValue = RTO_LOADING3_ID;
             };
             break;
         case EXTERNAL_MODE_IN_VANGER:
             ExternalTime--;
             if(ExternalTime <= 0){
                 SOUND_BOOT_STOP();
                 Go2Universe();
                 Status |= SOBJ_DISCONNECT;
             };
             break;
         case EXTERNAL_MODE_OUT_VANGER:
             ExternalTime--;
             if(ExternalTime <= 0){
                 SOUND_BOOT_STOP();
                 ExternalMode = EXTERNAL_MODE_NORMAL;
                 ExternalLock = 0;
                 ExternalDraw = 1;
                 switch_analysis(0);
                 ExternalSensor = ExternalObject;
             };
             break;
     };
     DoorFlag = 0;
 };
References ACI_LOCK_INTERFACE, ACI_UNLOCK_INTERFACE, aciCurJumpCount, aciSendEvent2actint(), aciWorldLinkExist(), ActD, ActionDispatcher::Active, LocationEngine::ActiveTime, aiLocalTarget, ActionUnit::Angle, UVS_KRON_EVENT::ARK_NOY, uvsUnitType::Armor, camera_direct(), ChangeArmor, ChangeEnergy, ChangeWorldConstraction, CPAL_HIDE_PASSAGE, CPAL_PASSAGE_FROM, EffectDispatcher::CreateDeform(), EffectDispatcher::CreateParticleGenerator(), CreateParticleRotor(), UVS_KRON_EVENT::CRYPT, CurrentWorld, cycleTor(), LocationEngine::DeactiveTime, DOOR_CLOSE_LOCK, DOOR_OPEN_LOCK, DoorFlag, SensorTypeList::EARTH_PASSAGE, uvsGamerResult::earth_unable, EffD, uvsUnitType::Energy, SensorTypeList::ESCAVE, UVS_EVENT::ESCAVE_ARRIVAL, uvsWorld::escT, EXTERNAL_IMPULSE_TIME, EXTERNAL_MODE_DARK, EXTERNAL_MODE_EARTH_IN, EXTERNAL_MODE_EARTH_PREPARE, EXTERNAL_MODE_ESCAVE_IN, EXTERNAL_MODE_ESCAVE_OUT, EXTERNAL_MODE_FREE_IN, EXTERNAL_MODE_IN_VANGER, EXTERNAL_MODE_LIGHT, EXTERNAL_MODE_MOVE, EXTERNAL_MODE_NORMAL, EXTERNAL_MODE_OUT_VANGER, EXTERNAL_MODE_PASS_IMPULSE, EXTERNAL_MODE_PASS_IN, EXTERNAL_MODE_PASS_OUT, EXTERNAL_MODE_SIGN_IN, EXTERNAL_MODE_SPOT_IN, EXTERNAL_MODE_SPOT_OUT, EXTERNAL_MODE_TRANSPORTER, ExternalAngle, ExternalDraw, ExternalLastSensor, ExternalLock, ExternalMode, ExternalObject, ExternalSensor, ExternalTime, ExternalTime2, GAME_OVER_ALL_LOCKED, GAME_OVER_INFERNAL_LOCKED, GAME_OVER_LUCKY, GAME_OVER_NETWORK, GAME_OVER_SPOBS_LOCKED, GameOverID, GameQuantReturnValue, GamerResult, ServerData::GameType, getDistX(), GloryPlaceNum, Go2Universe(), UVS_EVENT::GO_NEW_ESCAVE, UVS_EVENT::GO_NEW_WORLD, Object::impulse(), SensorDataType::Index, LinkType::Level, NodeType::Level, ActionDispatcher::LuckyFunction, my_server_data, NetFunction83Time, NetGlobalTime, NetworkON, NewWorldX, NewWorldY, NULL, aiUnitResolve::Obj, SensorDataType::Owner, PalCD, SensorTypeList::PASSAGE, UVS_EVENT::PASSAGE_ARRIVAL, uvsUnitType::PassageCount, ActionDispatcher::PassageTouchEnable, PASSEMBLOSS, PASSING_WAVE_PROCESS, PASSING_WAVE_RADIUS, PASSING_WAVE_RADIUS2, PI, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, uvsTarget::pos_x, uvsTarget::pos_y, uvsPassage::Poutput, uvsUnitType::PowerFlag, TrackLinkType::pPrevLink, Vector::psi(), uvsWorld::pssT, uvsWorld::pssTmax, uvsVanger::Pworld, GeneralObject::R_curr, Object::radius, StaticObject::radius, realRND(), RND(), ROTOR_PROCESS_LIFE_TIME, rPI, RTO_LOADING3_ID, section_prepare(), SensorDataType::SensorType, PalConstructor::Set(), Object::set_3D(), SET_3D_CHOOSE_LEVEL, SET_3D_DIRECT_PLACE, ShellUpdateFlag, SOBJ_ACTIVE, SOBJ_AUTOMAT, SOBJ_DISCONNECT, SOUND_BOOT_STOP, SOUND_FAILEDPASS, SOUND_PASSAGE, ActionUnit::Speed, LinkType::Speed, ActionDispatcher::SpobsDestroy, SensorTypeList::SPOT, UVS_EVENT::SPOT_ARRIVAL, uvsWorld::sptT, StopCDTRACK(), Object::switch_analysis(), TabuUse, Object::test_whether_there_is_not_something_above(), ActionDispatcher::ThreallDestroy, LinkType::Time, LinkType::TrackCount, NodeType::TrackCount, SensorTypeList::TRAIN, SensorTypeList::TRAP, TRK_IN_BRANCH, TRK_IN_NODE, aiUnitResolve::Type, UNIT_ORDER_ENTER, UNIT_ORDER_PASSAGE, UsedCheckNum, uvsCheckKronIventTabuTask(), uvsKernel::uvsPoint, Vector::vabs(), VANGER_POWER_RUFFA_GUN, ViewX, ViewY, VISIBLE, WORLD_ARKONOY, WorldTable, Object::x, Vector::x, LinkType::x, LinkType::xl, LinkType::xr, Vector::y, LinkType::y, LinkType::yl, LinkType::yr, Vector::z, LinkType::z, and Z_AXIS.
Referenced by Quant().
SetMechos()
void VangerUnit::SetMechos (int n)
 {
     Object::operator = (ModelD.ActiveModel(n));
     set_active(1);
     set_3D(SET_3D_CHOOSE_LEVEL,R_curr.x,R_curr.y,R_curr.z,0,-Angle,Speed);
 };
References ModelDispatcher::ActiveModel(), ActionUnit::Angle, ModelD, Object::operator=(), Object::set_3D(), SET_3D_CHOOSE_LEVEL, Object::set_active(), and ActionUnit::Speed.
ShellNetEvent()
void VangerUnit::ShellNetEvent (int type, int id, int creator, int time, int x, int y, int radius_)
 {
 //  int t;
     unsigned char ch;
     BulletObject* g;
     Vector vCheck;
     switch(type){
         case UPDATE_OBJECT:
         case CREATE_OBJECT:
             NETWORK_IN_STREAM > ch;
             NetFunction = ch;
             NETWORK_IN_STREAM > ch;
             Energy = ((MaxEnergy - 1) / 15) * (int)(ch & 0x0f);
             Armor = ((MaxArmor - 1) / 15) * (int)((ch  >> 4) & 0x0f);
             NETWORK_IN_STREAM > ch;
             if(ch != NetDestroyID && GlobalStationID == ch){
                 NetStatisticUpdate(NET_STATISTICS_KILL);
                 if(my_server_data.GameType == VAN_WAR){
                     aiPutHotBug(aiGetHotBug() + uvsMechosTable[uvsPoint->Pmechos->type]->price);
 //                  ActD.HotBug += uvsMechosTable[uvsPoint->Pmechos->type]->price;
                     my_player_body.beebos = aiGetHotBug();
                 };
                 send_player_body(my_player_body);
             };
             NetDestroyID = ch;
             NETWORK_IN_STREAM > ch;
             if(NetChanger != ch){
                 if(!ch){
                     VangerChanger = NULL;
                     VangerChangerCount = 0;
                 }else{
                     if(ActD.Active && GlobalStationID == ch){
                         VangerChanger = ActD.Active;
                         MechosChangerType = ActD.Active->uvsPoint->Pmechos->type;
                         VangerChangerCount = 3;
                         vChangerPosition = ActD.Active->R_curr;
                         VangerChangerAngle = ActD.Active->Angle;
                         VangerChangerArmor = ActD.Active->Armor;
                         VangerChangerEnergy = ActD.Active->Energy;
                         if(!(ActD.Active->VangerChanger)){
                             ActD.Active->ShellUpdateFlag = 1;
                             ActD.Active->NetChanger = GET_STATION(NetID);
                             ActD.Active->VangerChanger = this;
                             ActD.Active->MechosChangerType = uvsPoint->Pmechos->type;
                             ActD.Active->VangerChangerCount = 3;
                             ActD.Active->vChangerPosition = R_curr;
                             ActD.Active->VangerChangerAngle = Angle;
                             ActD.Active->VangerChangerArmor = Armor;
                             ActD.Active->VangerChangerEnergy = Energy;
                         };
                     };
                 };
             };
             NetChanger = ch;
             NETWORK_IN_STREAM > NetRuffaGunTime;
             if(!(Status & SOBJ_WAIT_CONFIRMATION) && Visibility == VISIBLE && GetDistTime(NetGlobalTime,NetRuffaGunTime) < 5*256 && RuffaGunTime > (RUFFA_GUN_WAIT * WeaponWaitTime >> 8)){
                 RuffaGunTime = 0;
                 g = BulletD.CreateBullet();
                 vCheck = Vector(64,0,0)*RotMat;
                 g->CreateBullet(Vector(R_curr.x,R_curr.y,R_curr.z),
                     Vector(XCYCL(vCheck.x + R_curr.x),YCYCL(vCheck.y + R_curr.y),R_curr.z + vCheck.z),NULL,&GameBulletData[WD_BULLET_RUFFA],this,Speed);
                 if(ActD.Active)
                     SOUND_MACHOTINE_SHOT(getDistX(ActD.Active->R_curr.x,R_curr.x));
             };
             NETWORK_IN_STREAM > NetProtractorFunctionTime;
             NETWORK_IN_STREAM > NetMessiahFunctionTime;
             NETWORK_IN_STREAM > NetFunction83Time;
             if(NetFunction83Time != PrevNetFunction83Time && GetDistTime(NetGlobalTime,NetFunction83Time) < 256*ROTOR_PROCESS_LIFE_TIME / 20){
                 CreateParticleRotor(R_curr,83);
                 ExternalDraw = 0;
                 switch_analysis(1);
             };
             PrevNetFunction83Time = NetFunction83Time;
             break;
         case DELETE_OBJECT:
             Status |= SOBJ_DISCONNECT;
             break;
     };
 };
References ActD, ActionDispatcher::Active, aiGetHotBug(), aiPutHotBug(), ActionUnit::Angle, uvsUnitType::Armor, PlayerBody::beebos, BulletD, CREATE_OBJECT, BulletList::CreateBullet(), CreateParticleRotor(), DELETE_OBJECT, uvsUnitType::Energy, ExternalDraw, g, GameBulletData, ServerData::GameType, GET_STATION, GetDistTime(), getDistX(), GlobalStationID, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, MechosChangerType, my_player_body, my_server_data, NET_STATISTICS_KILL, NetChanger, NetDestroyID, NetFunction, NetFunction83Time, NetGlobalTime, NetMessiahFunctionTime, NetProtractorFunctionTime, NetRuffaGunTime, NetStatisticUpdate(), NETWORK_IN_STREAM, NULL, uvsVanger::Pmechos, PrevNetFunction83Time, uvsMechosType::price, ActionUnit::RotMat, ROTOR_PROCESS_LIFE_TIME, RUFFA_GUN_WAIT, RuffaGunTime, send_player_body(), ShellUpdateFlag, SOBJ_DISCONNECT, SOBJ_WAIT_CONFIRMATION, SOUND_MACHOTINE_SHOT, ActionUnit::Speed, Object::switch_analysis(), uvsMechos::type, UPDATE_OBJECT, uvsMechosTable, uvsKernel::uvsPoint, VAN_WAR, VangerChanger, VangerChangerAngle, VangerChangerArmor, VangerChangerCount, VangerChangerEnergy, vChangerPosition, VISIBLE, WD_BULLET_RUFFA, WeaponWaitTime, Object::x, Vector::x, XCYCL, Vector::y, YCYCL, and Vector::z.
Referenced by ActionDispatcher::ShellNetEvent().
ShellUpdate()
void VangerUnit::ShellUpdate (void)
 {
     unsigned char t;
 /*  t = 0;
     if(ActD.NetActiveProtractor){
         t |= ((ActD.NetProtractor & 7) - 1) | 64;
         ActD.NetActiveProtractor = 0;
     };
     if(ActD.NetActiveMessiah){
         t |= (((ActD.NetMechMessiah & 7) - 1) << 3) | 128;
         ActD.NetActiveMessiah = 0;
     };
     NETWORK_OUT_STREAM < (unsigned char)(t);*/
     NetFunction = (ActD.NetFunctionProtractor | ActD.NetFunctionMessiah);
     NETWORK_OUT_STREAM < (unsigned char)(NetFunction);
     t = (unsigned char)((15 * Energy / MaxEnergy) | ((15 * Armor / MaxArmor) << 4));
     if(Armor > 0) t |= 16;
     NETWORK_OUT_STREAM < (unsigned char)(t);
     NETWORK_OUT_STREAM < (unsigned char)(NetDestroyID);
     NETWORK_OUT_STREAM < (unsigned char)(NetChanger);
     NETWORK_OUT_STREAM < (unsigned int)(NetRuffaGunTime);
     NETWORK_OUT_STREAM < (unsigned int)(NetProtractorFunctionTime);
     NETWORK_OUT_STREAM < (unsigned int)(NetMessiahFunctionTime);
     NETWORK_OUT_STREAM < (unsigned int)(NetFunction83Time);
 };
References ActD, uvsUnitType::Armor, uvsUnitType::Energy, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, NetChanger, NetDestroyID, NetFunction, NetFunction83Time, ActionDispatcher::NetFunctionMessiah, ActionDispatcher::NetFunctionProtractor, NetMessiahFunctionTime, NetProtractorFunctionTime, NetRuffaGunTime, and NETWORK_OUT_STREAM.
Referenced by NetCreateVanger(), and Quant().
StartMoleProcess()
void VangerUnit::StartMoleProcess (void) virtual
Reimplemented from Object.
 {
     MolePoint1->set(R_curr,40,radius < 40 ? radius : 40);
 };
References MolePoint1, Object::radius, and dastPoly3D::set().
Referenced by VangerFunctionType::Quant().
StopTouchSensor()
void VangerUnit::StopTouchSensor (SensorDataType * p)
 {
     if(p->Enable){
         p->Touch(this);
         switch(p->SensorType){
             case SensorTypeList::SPOT:
             case SensorTypeList::ESCAVE:
             case SensorTypeList::PASSAGE:
             case SensorTypeList::TRAIN:
             case SensorTypeList::TRAP:
                 if(ExternalSensor){
                     if(ExternalSensor == ExternalObject && ExternalObject != p) ExternalSensor = p;
                 }else ExternalSensor = p;
                 break;
             case SensorTypeList::IMPULSE:
                 impulse(p->vData,p->Power,0);
                 break;
         };
     }else{
         if(p->SensorType == SensorTypeList::SPOT || p->SensorType == SensorTypeList::ESCAVE || p->SensorType == SensorTypeList::PASSAGE){
             TouchKeyObject = p;
             TouchKeyObjectFlag = 0;
         };
     };
 };
References StaticObject::Enable, SensorTypeList::ESCAVE, ExternalObject, ExternalSensor, Object::impulse(), SensorTypeList::IMPULSE, SensorTypeList::PASSAGE, SensorDataType::Power, SensorDataType::SensorType, SensorTypeList::SPOT, SensorDataType::Touch(), TouchKeyObject, TouchKeyObjectFlag, SensorTypeList::TRAIN, SensorTypeList::TRAP, and SensorDataType::vData.
Referenced by InitEnvironment().
StuffDestroyHandler()
void VangerUnit::StuffDestroyHandler (GeneralObject * p)
 {
     aiResolveFind.ClearResolve(UNIT_ORDER_STUFF,UnitOrderType((StuffObject*)(p)));
     ClearEvent(p);
 };
References aiResolveFind, ClearEvent(), aiResolveList::ClearResolve(), and UNIT_ORDER_STUFF.
Referenced by ObjectDestroy().
SwitchTarget()
void VangerUnit::SwitchTarget (void)
TargetAnalysis()
void VangerUnit::TargetAnalysis (void)
 {
     Vector vCheck;
     int d;
     if(OtherFlag & MECHOS_CALC_WAY){
         if(!TraceWay()){
             OtherFlag &= ~MECHOS_CALC_WAY;
             OtherFlag |= MECHOS_RECALC_FRONT;
 //          SpeedDir = 1;
             memcpy(WayDist,CalcWayDist,sizeof(int)*HideTrack.NumNode);
         };
     };
     vCheck = Vector(getDistX(TargetPoint.vPoint.x,R_curr.x),getDistY(TargetPoint.vPoint.y,R_curr.y),0);
     d = vCheck.vabs();
     if(aiMoveMode == AI_MOVE_TRACK){
         TrackQuant();
         DirectQuant();
     }else{
         if(SpeedDir > 0) vDirect = Vector(getDistX(TargetPoint.vPoint.x,XCYCL(R_curr.x + vUp.x)),getDistY(TargetPoint.vPoint.y,R_curr.y + vUp.y),0);
         else vDirect = Vector(getDistX(TargetPoint.vPoint.x,XCYCL(R_curr.x + vDown.x)),getDistY(TargetPoint.vPoint.y,R_curr.y + vDown.y),0);
         TrackQuant();
     };
 };
References AI_MOVE_TRACK, TrackUnit::aiMoveMode, TrackUnit::CalcWayDist, TrackUnit::DirectQuant(), getDistX(), getDistY(), HideTrack, MECHOS_CALC_WAY, MECHOS_RECALC_FRONT, TrackType::NumNode, ActionUnit::OtherFlag, ActionUnit::SpeedDir, TrackUnit::TargetPoint, TrackUnit::TraceWay(), TrackUnit::TrackQuant(), Vector::vabs(), ActionUnit::vDirect, ActionUnit::vDown, TrackLinkType::vPoint, ActionUnit::vUp, TrackUnit::WayDist, Vector::x, XCYCL, and Vector::y.
Referenced by Quant().
TerrainQuant()
void VangerUnit::TerrainQuant (void)
 {
     int i,y0,y1;
     Vector vCheck;
     StaticObject* st;
     int l;
     if(CurrentWorld == 2){
         if(check_terrain_type(7)){
             y0 = R_curr.y - EXPLOSION_BARELL_RADIUS;
             y1 = R_curr.y + EXPLOSION_BARELL_RADIUS;
             i = FindFirstStatic(y0,y1,(StaticObject**)TntSortedData,TntTableSize);
             if(i > -1){
                 do{
                     st = TntSortedData[i];
                     if(st->Enable){
                         vCheck.x = getDistX(st->R_curr.x,R_curr.x);
 //                      l = radius + st->radius;
                         l = radius + st->radius;
                         if(abs(vCheck.x) < l){
                             vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                             vCheck.z = st->R_curr.z - R_curr.z;
                             if(vCheck.abs2() < l*l){
                                 st->Touch(this);
                                 Touch(st);
                             };
                         };
                     };
                     i++;
                 }while(i < TntTableSize && TntSortedData[i]->R_curr.y < y1);
             };
         };
     };
 };
References Vector::abs2(), Object::check_terrain_type(), CurrentWorld, StaticObject::Enable, EXPLOSION_BARELL_RADIUS, FindFirstStatic(), getDistX(), getDistY(), GeneralObject::R_curr, Object::radius, StaticObject::radius, TntSortedData, TntTableSize, GeneralObject::Touch(), Touch(), Vector::x, Vector::y, and Vector::z.
Referenced by Quant().
test_objects_collision()
int VangerUnit::test_objects_collision () virtual
Reimplemented from Object.
 {
     int log = 0;
     DangerDataType* st;
     int y0,y1;
     int d,l,i;
     Vector vCheck;
     BaseObject* p;
     if(ExternalMode != EXTERNAL_MODE_NORMAL || !ExternalDraw)
         return 0;
     p = (BaseObject*)(BulletD.Tail);
     while(p){
         if(p->Visibility == VISIBLE){
 //          if(p->ID != ID_BULLET)
 //              ErrH.Abort("Big BUG with memory");
             if(((BulletObject*)(p))->ShowID == BULLET_SHOW_TYPE_ID::CRATER){
                 i = radius + p->radius;
                 l = getDistY(p->R_curr.y,R_curr.y);
                 if(l < i){
                     d = getDistX(p->R_curr.x,R_curr.x);
                     if(d < i && R_curr.z <= p->R_curr.z + i && (d*d + l*l) < i*i){
                         Touch(p);
                         p->Touch(this);
                     };
                 };
             }else log += test_object_to_baseobject(p);
         };
         p = (BaseObject*)(p->NextTypeList);
     };
 //  if(mole_on || SensorEnable) return 0;
     if(!mole_on && !SensorEnable){
         p = (BaseObject*)(ActD.Tail);
         while(p && p != this){
             if(p->Visibility == VISIBLE)
                 log += test_object_to_baseobject(p);
             p = (BaseObject*)(p->NextTypeList);
         };
     };
     if(!NetworkON || (Status & SOBJ_ACTIVE)){
         p = (BaseObject*)(ItemD.Tail);
         while(p){
             if(p->Visibility == VISIBLE && (!mole_on || !(((Object*)(p))->analysis_off)))
                 log += test_object_to_baseobject(p);
             p = (BaseObject*)(p->NextTypeList);
         };
     };
     if(mole_on || SensorEnable) return 0;
     p = (BaseObject*)(JumpD.Tail);
     while(p){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)(FishD.Tail);
     while(p){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)(HordeSourceD.Tail);
     while(p){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)(HordeD.Tail);
     while(p){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)(ClefD.Tail);
     while(p){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)(DebrisD.Tail);
     while(p){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)(InsectD.Tail);
     while(p){
         if(p->Visibility == VISIBLE)
             log += test_object_to_baseobject(p);
         p = (BaseObject*)(p->NextTypeList);
     };
 /*  n = MapD.Tail;
     while(n){
         if(n->ID == ID_FIELD_SOURCE && ((BaseObject*)(n))->Visibility == VISIBLE)
             log += test_object_to_baseobject((BaseObject*)(n));
         n = n->NextTypeList;
     };*/
     closest_field_object = NULL;
     d = 0xfffffff;
     y0 = R_curr.y - radius - MAX_SENSOR_RADIUS;
     y1 = R_curr.y + radius + MAX_SENSOR_RADIUS;
     i = FindFirstStatic(y0,y1,(StaticObject**)DangerSortedData,DngTableSize);
     if(i > -1){
         do{
             st = DangerSortedData[i];
             if(st->Enable && R_curr.z < st->R_curr.z + radius){
                 vCheck.x = getDistX(st->R_curr.x,R_curr.x);
                 vCheck.y = getDistY(st->R_curr.y,R_curr.y);
                 vCheck.z = 0;
                 l = vCheck.vabs();
                 if(l < (st->radius + radius) && l < d){
                     d = l;
                     closest_field_object = st;
                 };
             };
             i++;
         }while(i < DngTableSize && DangerSortedData[i]->R_curr.y < y1);
     };
     if(Status & SOBJ_ACTIVE){
         if(closest_field_object){
             switch(closest_field_object->Type){
                 case DangerTypeList::FASTSAND:
                 case DangerTypeList::SWAMP:
                     if(ActD.Active)
                         SOUND_SWAMP(getDistX(ActD.Active->R_curr.x,R_curr.x))
                     if(!(closest_field_object->TabuUse)){
                         uvsCheckKronIventTabuTask(UVS_KRON_EVENT::SWAMP,1);
                         closest_field_object->TabuUse = 1;
                     };
                     break;
                 case DangerTypeList::WHIRLPOOL:
                     if(ActD.Active)
                         SOUND_SWAMP(getDistX(ActD.Active->R_curr.x,R_curr.x))
                     if(!(closest_field_object->TabuUse)){
                         uvsCheckKronIventTabuTask(UVS_KRON_EVENT::WHIRLPOOL,1);
                         closest_field_object->TabuUse = 1;
                     };
                     break;
                 case DangerTypeList::TRAIN:
                     break;
             };
         };
     };
     return 0;
 };
References ActD, ActionDispatcher::Active, BulletD, ClefD, Object::closest_field_object, BULLET_SHOW_TYPE_ID::CRATER, DangerSortedData, DebrisD, DngTableSize, StaticObject::Enable, EXTERNAL_MODE_NORMAL, ExternalDraw, ExternalMode, DangerTypeList::FASTSAND, FindFirstStatic(), FishD, getDistX(), getDistY(), HordeD, HordeSourceD, InsectD, ItemD, JumpD, MAX_SENSOR_RADIUS, Object::mole_on, NetworkON, GeneralObject::NextTypeList, NULL, GeneralObject::R_curr, Object::radius, BaseObject::radius, StaticObject::radius, SensorEnable, SOBJ_ACTIVE, SOUND_SWAMP, DangerTypeList::SWAMP, UVS_KRON_EVENT::SWAMP, DangerDataType::TabuUse, UnitListType::Tail, UnitList::Tail, Object::test_object_to_baseobject(), GeneralObject::Touch(), Touch(), DangerTypeList::TRAIN, DangerDataType::Type, uvsCheckKronIventTabuTask(), Vector::vabs(), BaseObject::Visibility, VISIBLE, DangerTypeList::WHIRLPOOL, UVS_KRON_EVENT::WHIRLPOOL, Object::x, Vector::x, Vector::y, and Vector::z.
Touch()
void VangerUnit::Touch (GeneralObject * p)
 {
     if(p->ID == ID_VANGER && (!NetworkON || (Status & SOBJ_ACTIVE))){
         PUT_GLOBAL_EVENT(AI_EVENT_COLLISION,ID_VANGER,p,this);
         if(BeebonationFlag){
             Energy = 0;
             Armor = 0;
             ExternalDraw = 0;
         };
     };
 };
References AI_EVENT_COLLISION, uvsUnitType::Armor, BeebonationFlag, uvsUnitType::Energy, ExternalDraw, GeneralObject::ID, ID_VANGER, NetworkON, PUT_GLOBAL_EVENT, and SOBJ_ACTIVE.
Referenced by ResolveHandlerFind(), TerrainQuant(), and test_objects_collision().
TouchSensor()
void VangerUnit::TouchSensor (SensorDataType * p)
 {
     DoorEngine* d;
     Vector vCheck;
     TiristorEngine* t;
     int i,s,r_log;
     switch(p->SensorType){
         case SensorTypeList::PASSAGE:
         case SensorTypeList::EARTH_PASSAGE:
         case SensorTypeList::ESCAVE:
         case SensorTypeList::SPOT:
         case SensorTypeList::TRAP:
         case SensorTypeList::TRAIN:
             if(ActD.PassageTouchEnable) ActD.PassageTouchEnable = MAX_PASSAGE_DELAY;
             if(!BeebonationFlag){
                 if(ExternalSensor){
                     if(ExternalSensor == ExternalObject && ExternalObject != p) ExternalSensor = p;
                 }else ExternalSensor = p;
             };
             break;
         case SensorTypeList::IMPULSE:
 //          impulse(Vector(32 - RND(64),32 - RND(64),RND(64)),20,0);
             impulse(p->vData,p->Power,0);
             if(abs(PrevImpuseFrame - frame) > 5){
                 SOUND_KIDPUSH();
                 PrevImpuseFrame = frame;
             };
             break;
         case SensorTypeList::ARMOR_UPDATE:
             if(Armor < MaxArmor){
                 Armor = MaxArmor;
                 aiMessageQueue.Send(AI_MESSAGE_ARMOR,Speed,2,0);//aiMessageData[AI_MESSAGE_ARMOR].Send(Speed,2,0);
                 SOUND_CHARGE_REPARE();
             };
             aiMessageQueue.Send(AI_MESSAGE_ARMOR,Speed,1);//aiMessageData[AI_MESSAGE_ARMOR].Send(Speed,1);
 //          if(Armor < (MaxArmor - MaxArmor / 32)){
 //              aiMessageData[AI_MESSAGE_ARMOR].Send(Speed,2,0);
 //              Armor += MaxArmor / 32;
 //              SOUND_CHARGE();
 //          };
 //          aiMessageData[AI_MESSAGE_ARMOR].Send(Speed,1);
             break;
         case SensorTypeList::RANDOMIZE_UPDATE:
             aiMessageQueue.Send(AI_MESSAGE_RANDOM_UPDATE,Speed,1);//aiMessageData[AI_MESSAGE_RANDOM_UPDATE].Send(Speed,1);
             if(RandomUpdate != frame - 1){
                 r_log = 0;
                 while(!r_log){
                     switch(RND(6)){
                         case 0:
                             s = ChargeWeapon(this,ACI_GHORB_GEAR_LIGHT,1);
                             s += ChargeWeapon(this,ACI_GHORB_GEAR_HEAVY,1);
                             if(s) r_log = 1;
                             break;
                         case 1:
                             s = ChargeWeapon(this,ACI_GHORB_GEAR_LIGHT,0);
                             s += ChargeWeapon(this,ACI_GHORB_GEAR_HEAVY,0);
                             if(s) r_log = 1;
                             break;
                         case 2:
                             if(Energy < MaxEnergy - 1){
                                 aiMessageQueue.Send(AI_MESSAGE_ENERGY,Speed,1,0);//aiMessageData[AI_MESSAGE_ENERGY].Send(Speed,1,0);
                                 Energy = MaxEnergy - 1;
                                 r_log = 1;
                                 uvsCheckKronIventTabuTask(UVS_KRON_EVENT::RECHARGE_SHEILD,1);
                                 SOUND_CHARGE_ENERGE();
                             };
                             break;
                         case 3:
                             if(Energy > 0){
                                 aiMessageQueue.Send(AI_MESSAGE_DENERGY,Speed,1,0);//aiMessageData[AI_MESSAGE_DENERGY].Send(Speed,1,0);
                                 Energy = 0;
                                 r_log = 1;
                                 SOUND_DISCHARGE();
                             };
                             break;
                         case 4:
                             s = ChargeDevice(this,ACI_EMPTY_COPTE_RIG,1);
                             s += ChargeDevice(this,ACI_EMPTY_CROT_RIG,1);
                             s += ChargeDevice(this,ACI_EMPTY_CUTTE_RIG,1);
                             s += ChargeDevice(this,ACI_COPTE_RIG,1);
                             s += ChargeDevice(this,ACI_CROT_RIG,1);
                             s += ChargeDevice(this,ACI_CUTTE_RIG,1);
                             if(s)  r_log = 1;
                             break;
                         case 5:
 //                          s = ChargeDevice(this,ACI_EMPTY_COPTE_RIG,0);
 //                          s += ChargeDevice(this,ACI_EMPTY_CROT_RIG,0);
 //                          s += ChargeDevice(this,ACI_EMPTY_CUTTE_RIG,0);
                             s = ChargeDevice(this,ACI_COPTE_RIG,0);
                             s += ChargeDevice(this,ACI_CROT_RIG,0);
                             s += ChargeDevice(this,ACI_CUTTE_RIG,0);
                             if(s) r_log = 1;
                             break;
                     };
                 };
             };
             RandomUpdate = frame;
             break;
         case SensorTypeList::OXIGEN_UPDATE:
             if(p->data5 == CheckPointCount){
                 KhoxPoison = MaxKhoxPoison;
                 p->Enable = 0;
                 MapD.CreateCrater(p->R_curr,MAP_POINT_CRATER12);
                 CheckPointCount++;
                 OxigenResource = MaxOxigenResource;
                 SOUND_CHECKPOINT()
             };
             break;
         case SensorTypeList::FLY_UPDATE:
             aiMessageQueue.Send(AI_MESSAGE_COPTER,Speed,1);//aiMessageData[AI_MESSAGE_COPTER].Send(Speed,1);
             if(RandomUpdate != frame - 1){
                 ChargeDevice(this,ACI_EMPTY_COPTE_RIG,1);
                 ChargeDevice(this,ACI_EMPTY_CROT_RIG,1);
                 ChargeDevice(this,ACI_EMPTY_CUTTE_RIG,1);
                 ChargeDevice(this,ACI_COPTE_RIG,1);
                 ChargeDevice(this,ACI_CROT_RIG,1);
                 ChargeDevice(this,ACI_CUTTE_RIG,1);
                 RandomUpdate = frame;
             };
             break;
         case SensorTypeList::FIRE_UPDATE:
             aiMessageQueue.Send(AI_MESSAGE_GHORB,Speed,1);//aiMessageData[AI_MESSAGE_GHORB].Send(Speed,1);
             ChargeWeapon(this,ACI_GHORB_GEAR_LIGHT,1);
             ChargeWeapon(this,ACI_GHORB_GEAR_HEAVY,1);
 //          ActD.AddFireResource();
             break;
         case SensorTypeList::KEY_UPDATE:
             aiMessageQueue.Send(AI_MESSAGE_SPIRAL,Speed,1);//aiMessageData[AI_MESSAGE_SPIRAL].Send(Speed,1);
             if(PassageCount < MaxPassageCount){
                 aiMessageQueue.Send(AI_MESSAGE_SPIRAL,Speed,2,0);//aiMessageData[AI_MESSAGE_SPIRAL].Send(Speed,2,0);
                 aciWorldLinksON();
                 PassageCount = MaxPassageCount;
                 SOUND_CHARGE_SPIRAL();
             };
             break;
         case SensorTypeList::SENSOR:
             if(DoorFlag){
                 if(p->Owner){
                     if(p->Owner->Type == EngineTypeList::DOOR){
                         d = (DoorEngine*)(p->Owner);
                         if(d->Luck > 0){
                             if((int)(RND(d->Luck)) <= aiCutLuck){
                                 DoorFlag = 0;
                                 if(d->Mode == EngineModeList::OPEN)
                                     d->CloseDoor();
                                 else
                                     d->OpenDoor();
                             }else{
                                 if(d->Luck > 0){
                                     for(i = 0;i < d->NumSensor;i++)
                                         d->SensorLink[i]->Enable = 0;
                                 };
                             };
                         }else{
                             if(d->Luck >= -aiCutLuck){
                                 DoorFlag = 0;
                                 if(d->Mode == EngineModeList::OPEN)
                                     d->CloseDoor();
                                 else
                                     d->OpenDoor();
                             };
                         };
                     }else{
                         if(p->Owner->Type == EngineTypeList::TIRISTOR){
                             DoorFlag = 0;
                             t = (TiristorEngine*)(p->Owner);
                             if(t->Luck > 0){
                                 if((int)(RND(t->Luck)) <= aiCutLuck){
                                     t->OpenDoor();
                                 }else{
                                     if(t->Luck > 0){
                                         for(i = 0;i < t->NumSensor;i++)
                                             t->SensorLink[i]->Enable = 0;
                                     };
                                 };
                             }else{
                                 if(t->Luck >= -aiCutLuck){
                                     if(t->Mode != EngineModeList::OPEN){
                                         t->OpenDoor();
                                     };
                                 };
                             };
                         };
                     };
                 };
             };
             break;
     };
 };
References ACI_COPTE_RIG, ACI_CROT_RIG, ACI_CUTTE_RIG, ACI_EMPTY_COPTE_RIG, ACI_EMPTY_CROT_RIG, ACI_EMPTY_CUTTE_RIG, ACI_GHORB_GEAR_HEAVY, ACI_GHORB_GEAR_LIGHT, aciWorldLinksON(), ActD, AI_MESSAGE_ARMOR, AI_MESSAGE_COPTER, AI_MESSAGE_DENERGY, AI_MESSAGE_ENERGY, AI_MESSAGE_GHORB, AI_MESSAGE_RANDOM_UPDATE, AI_MESSAGE_SPIRAL, aiCutLuck, aiMessageQueue, uvsUnitType::Armor, SensorTypeList::ARMOR_UPDATE, BeebonationFlag, ChargeDevice(), ChargeWeapon(), CheckPointCount, DoorEngine::CloseDoor(), SensorDataType::data5, EngineTypeList::DOOR, DoorFlag, SensorTypeList::EARTH_PASSAGE, StaticObject::Enable, uvsUnitType::Energy, SensorTypeList::ESCAVE, ExternalObject, ExternalSensor, SensorTypeList::FIRE_UPDATE, SensorTypeList::FLY_UPDATE, frame, Object::impulse(), SensorTypeList::IMPULSE, SensorTypeList::KEY_UPDATE, KhoxPoison, DoorEngine::Luck, TiristorEngine::Luck, MapD, MAX_PASSAGE_DELAY, uvsUnitType::MaxArmor, uvsUnitType::MaxEnergy, MaxKhoxPoison, uvsUnitType::MaxOxigenResource, uvsUnitType::MaxPassageCount, LocationEngine::Mode, DoorEngine::NumSensor, TiristorEngine::NumSensor, EngineModeList::OPEN, DoorEngine::OpenDoor(), TiristorEngine::OpenDoor(), SensorDataType::Owner, SensorTypeList::OXIGEN_UPDATE, uvsUnitType::OxigenResource, SensorTypeList::PASSAGE, uvsUnitType::PassageCount, ActionDispatcher::PassageTouchEnable, SensorDataType::Power, PrevImpuseFrame, GeneralObject::R_curr, SensorTypeList::RANDOMIZE_UPDATE, RandomUpdate, UVS_KRON_EVENT::RECHARGE_SHEILD, RND(), aiMessageList::Send(), SensorTypeList::SENSOR, DoorEngine::SensorLink, TiristorEngine::SensorLink, SensorDataType::SensorType, SOUND_CHARGE_ENERGE, SOUND_CHARGE_REPARE, SOUND_CHARGE_SPIRAL, SOUND_CHECKPOINT, SOUND_DISCHARGE, SOUND_KIDPUSH, ActionUnit::Speed, SensorTypeList::SPOT, EngineTypeList::TIRISTOR, SensorTypeList::TRAIN, SensorTypeList::TRAP, LocationEngine::Type, uvsCheckKronIventTabuTask(), and SensorDataType::vData.
Referenced by InitEnvironment().
UsingCopterig()
int VangerUnit::UsingCopterig (int decr_8) virtual
Reimplemented from Object.
 {
     StuffObject* p;
     int i;
     if(uvsPoint->Pmechos->type == FLY_DEVICE_DEFAULT) return 1;
     if(UseDeviceMask & DEVICE_MASK_COPTE){
         if(Status & SOBJ_ACTIVE){
             if(Status & SOBJ_AUTOMAT) return 0;
             for(i = 0;i < MAX_ACTIVE_SLOT;i++){
                 if(ActD.Slot[i] && ActD.Slot[i]->ActIntBuffer.type == ACI_COPTE_RIG){
                     if(!decr_8) return 1;
                     p = ActD.Slot[i];
                     if(p->ActIntBuffer.data1 <= 0){
                         p->ActIntBuffer.data1 = 0;
                         p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                         aciChangeItem(&(p->ActIntBuffer));
                         aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                         aciSendEvent2actint(ACI_PUT_ITEM,&(p->ActIntBuffer));
                     }else p->ActIntBuffer.data1--;
                     return 1;
                 };
             };
             p = GetStuffObject(this,ACI_COPTE_RIG);
             if(p){
                 aciSendEvent2actint(ACI_PUT_IN_SLOT,&(p->ActIntBuffer));
                 return 1;
             };
         }else{
             if(aiMoveFunction != AI_MOVE_FUNCTION_FLY) return 0;
             if(!decr_8) return 1;
             if(CoptePoint->ActIntBuffer.data1 <= 0){
                 CoptePoint->ActIntBuffer.data1 = 0;
                 CoptePoint->ActIntBuffer.type = uvsSetItemType(CoptePoint->uvsDeviceType,CoptePoint->ActIntBuffer.data0,CoptePoint->ActIntBuffer.data1);
             }else{
                 CoptePoint->ActIntBuffer.data1--;
                 return 1;
             };
         };
     };
     return 0;
 };
References ACI_COPTE_RIG, ACI_DROP_ITEM, ACI_PUT_IN_SLOT, ACI_PUT_ITEM, aciChangeItem(), aciSendEvent2actint(), ActD, StuffObject::ActIntBuffer, AI_MOVE_FUNCTION_FLY, TrackUnit::aiMoveFunction, CoptePoint, actintItemData::data0, actintItemData::data1, DEVICE_MASK_COPTE, FLY_DEVICE_DEFAULT, GetStuffObject(), MAX_ACTIVE_SLOT, uvsVanger::Pmechos, ActionDispatcher::Slot, SOBJ_ACTIVE, SOBJ_AUTOMAT, actintItemData::type, uvsMechos::type, UseDeviceMask, StuffObject::uvsDeviceType, uvsKernel::uvsPoint, and uvsSetItemType().
UsingCrotrig()
int VangerUnit::UsingCrotrig (int decr_8) virtual
Reimplemented from Object.
 {
     StuffObject* p;
     int i;
     if(CurrentWorld == WORLD_HMOK) return 0;
     if(uvsPoint->Pmechos->type == MOLE_DEVICE_DEFAULT) return 1;
     if(UseDeviceMask & DEVICE_MASK_MOLE){
         if(Status & SOBJ_ACTIVE){
             if(Status & SOBJ_AUTOMAT) return 0;
             for(i = 0;i < MAX_ACTIVE_SLOT;i++){
                 if(ActD.Slot[i] && ActD.Slot[i]->ActIntBuffer.type == ACI_CROT_RIG){
                     if(!decr_8) return 1;
                     p = ActD.Slot[i];
                     if(p->ActIntBuffer.data1 <= 0){
                         p->ActIntBuffer.data1 = 0;
                         p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                         aciChangeItem(&(p->ActIntBuffer));
                         aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                         aciSendEvent2actint(ACI_PUT_ITEM,&(p->ActIntBuffer));
                     }else p->ActIntBuffer.data1--;
                     return 1;
                 };
             };
             p = GetStuffObject(this,ACI_CROT_RIG);
             if(p){
                 aciSendEvent2actint(ACI_PUT_IN_SLOT,&(p->ActIntBuffer));
                 return 1;
             };
         }else{
             return 0;
 /*          if(!decr_8) return 1;
             if(MolePoint->ActIntBuffer.data1 <= 0){
                 MolePoint->ActIntBuffer.data1 = 0;
                 MolePoint->ActIntBuffer.type = uvsSetItemType(MolePoint->uvsDeviceType,MolePoint->ActIntBuffer.data0,MolePoint->ActIntBuffer.data1);
             }else MolePoint->ActIntBuffer.data1--;
             return 1;*/
         };
     };
     return 0;
 };
References ACI_CROT_RIG, ACI_DROP_ITEM, ACI_PUT_IN_SLOT, ACI_PUT_ITEM, aciChangeItem(), aciSendEvent2actint(), ActD, StuffObject::ActIntBuffer, CurrentWorld, actintItemData::data0, actintItemData::data1, DEVICE_MASK_MOLE, GetStuffObject(), MAX_ACTIVE_SLOT, MOLE_DEVICE_DEFAULT, uvsVanger::Pmechos, ActionDispatcher::Slot, SOBJ_ACTIVE, SOBJ_AUTOMAT, actintItemData::type, uvsMechos::type, UseDeviceMask, StuffObject::uvsDeviceType, uvsKernel::uvsPoint, uvsSetItemType(), and WORLD_HMOK.
UsingCutterig()
int VangerUnit::UsingCutterig (int decr_8) virtual
Reimplemented from Object.
 {
     StuffObject* p;
     int i;
     if(uvsPoint->Pmechos->type == SWIM_DEVICE_DEFAULT || PowerFlag & VANGER_POWER_SWIM_ALWAYS) return 1;
     if(UseDeviceMask & DEVICE_MASK_SWIM){
         if(Status & SOBJ_ACTIVE){
             if(Status & SOBJ_AUTOMAT) return 0;
             for(i = 0;i < MAX_ACTIVE_SLOT;i++){
                 if(ActD.Slot[i] && ActD.Slot[i]->ActIntBuffer.type == ACI_CUTTE_RIG){
                     if(!decr_8) return 1;
                     p = ActD.Slot[i];
                     if(p->ActIntBuffer.data1 <= 0){
                         p->ActIntBuffer.data1 = 0;
                         p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                         aciChangeItem(&(p->ActIntBuffer));
                         aciSendEvent2actint(ACI_DROP_ITEM,&(p->ActIntBuffer));
                         aciSendEvent2actint(ACI_PUT_ITEM,&(p->ActIntBuffer));
                     }else p->ActIntBuffer.data1--;
                     return 1;
                 };
             };
             p = GetStuffObject(this,ACI_CUTTE_RIG);
             if(p){
                 aciSendEvent2actint(ACI_PUT_IN_SLOT,&(p->ActIntBuffer));
                 return 1;
             };
         }else{
             return 0;
 /*          if(!decr_8) return 1;
             if(SwimPoint->ActIntBuffer.data1 <= 0){
                 SwimPoint->ActIntBuffer.data1 = 0;
                 SwimPoint->ActIntBuffer.type = uvsSetItemType(SwimPoint->uvsDeviceType,SwimPoint->ActIntBuffer.data0,SwimPoint->ActIntBuffer.data1);
             }else SwimPoint->ActIntBuffer.data1--;
             return 1;*/
         };
     };
     return 0;
 };
References ACI_CUTTE_RIG, ACI_DROP_ITEM, ACI_PUT_IN_SLOT, ACI_PUT_ITEM, aciChangeItem(), aciSendEvent2actint(), ActD, StuffObject::ActIntBuffer, actintItemData::data0, actintItemData::data1, DEVICE_MASK_SWIM, GetStuffObject(), MAX_ACTIVE_SLOT, uvsVanger::Pmechos, uvsUnitType::PowerFlag, ActionDispatcher::Slot, SOBJ_ACTIVE, SOBJ_AUTOMAT, SWIM_DEVICE_DEFAULT, actintItemData::type, uvsMechos::type, UseDeviceMask, StuffObject::uvsDeviceType, uvsKernel::uvsPoint, uvsSetItemType(), and VANGER_POWER_SWIM_ALWAYS.
VangerDestroyHandler()
void VangerUnit::VangerDestroyHandler (GeneralObject * p)
 {
     if(aiDamageData == p){
         aiDamage = 0;
         aiDamageData = NULL;
     };
     aiResolveFind.ClearResolve(UNIT_ORDER_VANGER,UnitOrderType((ActionUnit*)(p)));
     aiResolveAttack.ClearResolve(UNIT_ORDER_VANGER,UnitOrderType((ActionUnit*)(p)));
     ClearEvent(p);
 };
References aiDamage, aiDamageData, aiResolveAttack, aiResolveFind, ClearEvent(), aiResolveList::ClearResolve(), NULL, and UNIT_ORDER_VANGER.
Referenced by ObjectDestroy().
WeaponGenerator()
void VangerUnit::WeaponGenerator (void)
 {
     int i;
     StuffObject* p;
     GunDevice* pp;
     int ms,s,mp,d;
     GunSlot* gs;
     WeaponDelta = 0;
     AttackRadius = 300;
     for(i = 0;i < ItemMatrix->NumSlot;i++){
         gs = &(GunSlotData[ItemMatrix->nSlot[i]]);
         if(gs->pData)
             gs->CloseGun();
     };
     for(i = 0;i < ItemMatrix->NumSlot;i++){
         if(!GunSlotData[ItemMatrix->nSlot[i]].pData){
             s = ItemMatrix->SlotSize[i];
             ms = 0;
             mp = 0;
             pp = NULL;
             p = DeviceData;
             while(p){
                 if(p->StuffType == DEVICE_ID_GUN && p->ActIntBuffer.slot == -1 && p->ActIntBuffer.data1 > 0 &&
                    p->SizeID >= ms && ((GunDevice*)(p))->pData->Power >= mp){
                     if(p->SizeID > 0){
                         if(p->SizeID <= s){
                             ms = p->SizeID;
                             pp = (GunDevice*)(p);
                             mp = pp->pData->Power;
                         };
                     }else{
                         if(p->SizeID == 0 && s == 0){
                             ms = p->SizeID;
                             pp = (GunDevice*)(p);
                             mp = pp->pData->Power;
                         };
                     };
                 };
                 p = p->NextDeviceList;
             };
             if(pp){
                 GunSlotData[ItemMatrix->nSlot[i]].OpenGun(pp);
                 if(pp->pData->WaitTime) WeaponDelta += pp->pData->Power / pp->pData->WaitTime;
                 else WeaponDelta += pp->pData->Power;
                 d = pp->pData->LifeTime * pp->pData->Speed;
                 if(d < AttackRadius) AttackRadius = d;
             };
         };
     };
 };
References StuffObject::ActIntBuffer, AttackRadius, GunSlot::CloseGun(), actintItemData::data1, DEVICE_ID_GUN, uvsUnitType::DeviceData, GunSlotData, uvsUnitType::ItemMatrix, WorldBulletTemplate::LifeTime, StuffObject::NextDeviceList, UnitItemMatrix::nSlot, NULL, UnitItemMatrix::NumSlot, GunSlot::OpenGun(), GunDevice::pData, GunSlot::pData, BulletControlType::Power, StuffObject::SizeID, actintItemData::slot, UnitItemMatrix::SlotSize, BulletControlType::Speed, StuffObject::StuffType, WorldBulletTemplate::WaitTime, and WeaponDelta.
Referenced by InitAI().
Member Data Documentation
AddAttackTime
int VangerUnit::AddAttackTime
Referenced by CalcAiFactor(), InitAI(), and ResolveGenerator().
aiActionID
int VangerUnit::aiActionID
Referenced by InitAI(), InitEnvironment(), MainOrderInit(), Quant(), and ResolveGenerator().
aiAlarmTime
int VangerUnit::aiAlarmTime
Referenced by CalcAiFactor(), InitAI(), and ResolveGenerator().
aiDamage
int VangerUnit::aiDamage
Referenced by InitAI(), ResolveGenerator(), and VangerDestroyHandler().
aiDamageData
VangerUnit* VangerUnit::aiDamageData
Referenced by InitAI(), ResolveGenerator(), and VangerDestroyHandler().
aiEvent
aiListType VangerUnit::aiEvent
Referenced by AddEvent(), AddEventTime(), CalcAiFactor(), ChangeVangerProcess(), ClearEvent(), ClearObjEvent(), ClearSubjEvent(), FindEvent(), Go2Universe(), Go2World(), and ResolveGenerator().
aiFirstItem
int VangerUnit::aiFirstItem
Referenced by InitAI(), and ResolveGenerator().
aiItemRadius
int VangerUnit::aiItemRadius
Referenced by InitAI(), and ResolveGenerator().
aiLocalTarget
aiUnitResolve* VangerUnit::aiLocalTarget
Referenced by AddFindResolve(), AutomaticTouchSensor(), InitAI(), InitEnvironment(), ResolveGenerator(), ResolveHandlerFind(), and SensorQuant().
aiMaxJumpRadius
int VangerUnit::aiMaxJumpRadius
Referenced by Action(), CalcForce(), CalcImpulse(), CheckNearTrack(), and InitAI().
aiModifier
int VangerUnit::aiModifier
Referenced by CalcAiFactor(), ChangeVangerProcess(), and CreateVangerUnit().
aiNearTrack
Vector VangerUnit::aiNearTrack
Referenced by CalcForce(), CalcImpulse(), CheckNearTrack(), and InitAI().
aiReactionCheckTime
int VangerUnit::aiReactionCheckTime
Referenced by Action(), and InitAI().
aiReactionCheckTimeMax
int VangerUnit::aiReactionCheckTimeMax
Referenced by Action(), and InitAI().
aiReactionMode
int VangerUnit::aiReactionMode
Referenced by Action(), and InitAI().
aiReactionTime
int VangerUnit::aiReactionTime
Referenced by Action(), and InitAI().
aiReactionTimeMax
int VangerUnit::aiReactionTimeMax
Referenced by InitAI().
aiRealxRadius
int VangerUnit::aiRealxRadius
Referenced by InitAI(), and ResolveGenerator().
aiRelaxData
Vector VangerUnit::aiRelaxData
Referenced by InitAI(), and ResolveGenerator().
aiRelaxTime
int VangerUnit::aiRelaxTime
Referenced by Action(), InitAI(), and ResolveGenerator().
aiRelaxTimeMax
int VangerUnit::aiRelaxTimeMax
Referenced by Action(), CalcForce(), CalcImpulse(), InitAI(), and ResolveGenerator().
aiResolveAttack
aiResolveList VangerUnit::aiResolveAttack
Referenced by CalcAiFactor(), ChangeVangerProcess(), Go2Universe(), Go2World(), InitEnvironment(), MainOrderInit(), and VangerDestroyHandler().
aiResolveFactor
float VangerUnit::aiResolveFactor[MAX_AI_FACTOR]
Referenced by CalcAiFactor().
aiResolveFind
aiResolveList VangerUnit::aiResolveFind
Referenced by AddEvent(), AddFindResolve(), CalcAiFactor(), ChangeVangerProcess(), CheckInDevice(), Go2Universe(), Go2World(), InitEnvironment(), ResolveGenerator(), SelectCompasTarget(), StuffDestroyHandler(), and VangerDestroyHandler().
aiResolveWayEnable
int VangerUnit::aiResolveWayEnable
Referenced by CalcForce(), CalcImpulse(), InitAI(), NoWayHandler(), ResolveGenerator(), and ResolveHandlerFind().
aiRunBranch
BranchType* VangerUnit::aiRunBranch
Referenced by CalcForce(), CalcImpulse(), InitAI(), and NoWayHandler().
aiRunNode
NodeType* VangerUnit::aiRunNode
Referenced by CalcForce(), CalcImpulse(), InitAI(), and NoWayHandler().
aiScanDist
int VangerUnit::aiScanDist
Referenced by InitAI(), and ResolveGenerator().
aiSecondItem
int VangerUnit::aiSecondItem
Referenced by InitAI(), and ResolveGenerator().
aiStatus
int VangerUnit::aiStatus
Referenced by Action(), InitAI(), InitEnvironment(), and ResolveGenerator().
aiVangerRadius
int VangerUnit::aiVangerRadius
Referenced by InitAI(), and ResolveGenerator().
ArmorAlarm
int VangerUnit::ArmorAlarm
Referenced by InitAI(), and ResolveGenerator().
AttackRadius
int VangerUnit::AttackRadius
Referenced by InitAI(), and WeaponGenerator().
BeebonationFlag
int VangerUnit::BeebonationFlag
Referenced by Destroy(), GunSlot::Fire(), InitAI(), HordeObject::Quant(), FishWarrior::Quant(), VangerFunctionType::Quant(), GunSlot::RemoteFire(), Touch(), and TouchSensor().
CheckPointCount
int VangerUnit::CheckPointCount
Referenced by CreateVangerUnit(), InitEnvironment(), Quant(), CheckPointEngine::Touch(), and TouchSensor().
CoptePoint
StuffObject* VangerUnit::CoptePoint
Referenced by ChangeVangerProcess(), CreateVangerUnit(), Quant(), ResolveGenerator(), and UsingCopterig().
DeltaTractionTime
int VangerUnit::DeltaTractionTime
Referenced by Action(), InitAI(), and ResolveGenerator().
DoorFlag
int VangerUnit::DoorFlag
Referenced by aciActionEvent(), ChangeVangerProcess(), CreateVangerUnit(), InitEnvironment(), keyhandler(), NetCreateSlave(), NewKeyHandler(), SensorQuant(), and TouchSensor().
ExternalAngle
int VangerUnit::ExternalAngle
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and SensorQuant().
ExternalDraw
int VangerUnit::ExternalDraw
Referenced by AddEscave(), AddFree(), AddPassage(), AddSpot(), ChangeVangerProcess(), CreateVangerUnit(), Destroy(), DrawMechosParticle(), DrawQuant(), GunSlot::Fire(), InitEnvironment(), HordeObject::Quant(), FishWarrior::Quant(), Quant(), CompasObject::Quant(), ActionDispatcher::Quant(), GunSlot::RemoteFire(), ResolveGenerator(), aiMessageList::Send(), SensorQuant(), ShellNetEvent(), test_objects_collision(), Touch(), and XpeditionOFF().
ExternalLastSensor
SensorDataType* VangerUnit::ExternalLastSensor
Referenced by ChangeVangerProcess(), CreateVangerUnit(), InitEnvironment(), and SensorQuant().
ExternalLock
int VangerUnit::ExternalLock
Referenced by AddEscave(), AddFree(), AddPassage(), AddSpot(), ChangeVangerProcess(), CreateVangerUnit(), Destroy(), Quant(), SensorQuant(), and XpeditionOFF().
ExternalMode
int VangerUnit::ExternalMode
Referenced by AddEscave(), AddFree(), AddPassage(), AddSpot(), ChangeVangerProcess(), CreateVangerUnit(), Destroy(), DrawMechosParticle(), DrawQuant(), InitEnvironment(), Quant(), CompasObject::Quant(), ActionDispatcher::Quant(), SensorQuant(), test_objects_collision(), and XpeditionOFF().
ExternalObject
SensorDataType* VangerUnit::ExternalObject
Referenced by AddEscave(), AddFree(), AddPassage(), AddSpot(), AutomaticTouchSensor(), ChangeVangerProcess(), CreateVangerUnit(), Destroy(), InitEnvironment(), Quant(), SensorQuant(), StopTouchSensor(), TouchSensor(), and XpeditionOFF().
ExternalSensor
SensorDataType* VangerUnit::ExternalSensor
Referenced by AutomaticTouchSensor(), ChangeVangerProcess(), CreateVangerUnit(), InitEnvironment(), SensorQuant(), StopTouchSensor(), and TouchSensor().
ExternalTime
int VangerUnit::ExternalTime
Referenced by AddEscave(), AddFree(), AddPassage(), AddSpot(), ChangeVangerProcess(), CreateVangerUnit(), Destroy(), Quant(), SensorQuant(), and XpeditionOFF().
ExternalTime2
int VangerUnit::ExternalTime2
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and SensorQuant().
GunSlotData
GunSlot VangerUnit::GunSlotData[MAX_ACTIVE_SLOT]
Referenced by ActionDispatcher::ActiveSlot(), ActionDispatcher::ActiveTerminatorSlot(), ChangeVangerProcess(), CheckAmmo(), ActionDispatcher::CheckDevice(), CheckOutDevice(), CheckSpeetle(), GetAllert(), GetWeaponDelta(), Go2Universe(), Go2World(), InitEnvironment(), InitPlayerPoint(), ItemQuant(), NetSlotEvent(), ResolveHandlerAttack(), ActionDispatcher::SlotIn(), ActionDispatcher::SlotOut(), and WeaponGenerator().
KhoxPoison
int VangerUnit::KhoxPoison
Referenced by CreateVangerUnit(), Quant(), and TouchSensor().
LastMole
int VangerUnit::LastMole
Referenced by CreateVangerUnit(), MapQuant(), and VangerFunctionType::Quant().
LowAmmo
int VangerUnit::LowAmmo
Referenced by CalcAiFactor(), CheckAmmo(), InitAI(), and ResolveGenerator().
LowArmor
int VangerUnit::LowArmor
Referenced by AutomaticTouchSensor(), CalcAiFactor(), InitAI(), and ResolveGenerator().
MaxKhoxPoison
int VangerUnit::MaxKhoxPoison
Referenced by CreateVangerUnit(), Quant(), and TouchSensor().
MaxSeed
int VangerUnit::MaxSeed
Referenced by InitAI(), MainOrderInit(), and ResolveGenerator().
MechosChangerType
int VangerUnit::MechosChangerType
Referenced by ChangeVangerProcess(), CreateVangerUnit(), GunDevice::DeviceIn(), and ShellNetEvent().
MixVectorEnable
int VangerUnit::MixVectorEnable
Referenced by Action(), and InitAI().
MolePoint
StuffObject* VangerUnit::MolePoint
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and Quant().
MolePoint1
dastPoly3D* VangerUnit::MolePoint1
Referenced by Go2Universe(), Go2World(), MapQuant(), and StartMoleProcess().
MolePoint2
dastPoly3D* VangerUnit::MolePoint2
Referenced by Go2Universe(), Go2World(), and MapQuant().
Molerizator
int VangerUnit::Molerizator
Referenced by InitAI(), MapQuant(), and VangerFunctionType::Quant().
MoleTool
dastPoly3D* VangerUnit::MoleTool
Referenced by Go2Universe(), Go2World(), and MoleProcessQuant().
nDoorFlag
int VangerUnit::nDoorFlag
Referenced by InitEnvironment(), and NetCreateSlave().
NetChanger
unsigned char VangerUnit::NetChanger
Referenced by CreateVangerUnit(), GunDevice::DeviceIn(), InitEnvironment(), Quant(), ShellNetEvent(), and ShellUpdate().
NetCreateID
int VangerUnit::NetCreateID
NetDestroyID
unsigned char VangerUnit::NetDestroyID
Referenced by BulletCollision(), CreateVangerUnit(), DestroyCollision(), ShellNetEvent(), and ShellUpdate().
NetExternalSensor
int VangerUnit::NetExternalSensor
NetFunction
unsigned char VangerUnit::NetFunction
Referenced by CreateVangerUnit(), ActionDispatcher::FunctionQuant(), ShellNetEvent(), and ShellUpdate().
NetFunction83Time
unsigned int VangerUnit::NetFunction83Time
Referenced by CreateVangerUnit(), Quant(), SensorQuant(), ShellNetEvent(), and ShellUpdate().
NetMessiahFunctionTime
unsigned int VangerUnit::NetMessiahFunctionTime
Referenced by CreateVangerUnit(), ActionDispatcher::FunctionQuant(), ShellNetEvent(), and ShellUpdate().
NetProtractorFunctionTime
unsigned int VangerUnit::NetProtractorFunctionTime
Referenced by CreateVangerUnit(), ActionDispatcher::FunctionQuant(), ShellNetEvent(), and ShellUpdate().
NetRuffaGunTime
unsigned int VangerUnit::NetRuffaGunTime
Referenced by ChangeVangerProcess(), CreateVangerUnit(), NewKeyHandler(), ShellNetEvent(), and ShellUpdate().
NetworkArmor
int VangerUnit::NetworkArmor
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and Quant().
NetworkEnergy
int VangerUnit::NetworkEnergy
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and Quant().
NoWayEnable
int VangerUnit::NoWayEnable
Referenced by Action(), CalcAiFactor(), CalcForce(), CalcImpulse(), InitAI(), NoWayHandler(), and NoWayInit().
PlayerDestroyFlag
int VangerUnit::PlayerDestroyFlag
Referenced by BulletCollision(), ChangeVangerProcess(), CreateVangerUnit(), Destroy(), and DestroyCollision().
pNetPlayer
PlayerData* VangerUnit::pNetPlayer
Referenced by AddFree(), AddPassage(), ChangeVangerProcess(), CheckPlayerList(), ActionDispatcher::Close(), InitEnvironment(), InitPlayerPoint(), and NetCheckRemovePlayer().
PrevImpuseFrame
int VangerUnit::PrevImpuseFrame
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and TouchSensor().
PrevNetFunction83Time
unsigned int VangerUnit::PrevNetFunction83Time
Referenced by CreateVangerUnit(), and ShellNetEvent().
RandomUpdate
int VangerUnit::RandomUpdate
Referenced by CreateVangerUnit(), and TouchSensor().
RuffaGunTime
int VangerUnit::RuffaGunTime
Referenced by ChangeVangerProcess(), CreateVangerUnit(), InitEnvironment(), keyhandler(), NewKeyHandler(), Quant(), and ShellNetEvent().
RunStartDist
int VangerUnit::RunStartDist
Referenced by CalcForce(), CalcImpulse(), InitAI(), and NoWayHandler().
RunTimeProcess
int VangerUnit::RunTimeProcess
Referenced by CalcForce(), CalcImpulse(), InitAI(), and NoWayHandler().
SeedNum
int VangerUnit::SeedNum
Referenced by InitAI(), MainOrderInit(), and ResolveGenerator().
SensorEnable
int VangerUnit::SensorEnable
Referenced by ChangeVangerProcess(), CreateVangerUnit(), InitEnvironment(), MapQuant(), and test_objects_collision().
ShellNetID
int VangerUnit::ShellNetID
Referenced by ActionDispatcher::Close(), CreateVangerUnit(), InitPlayerPoint(), NetCreateVanger(), Quant(), and ActionDispatcher::ShellNetEvent().
ShellUpdateFlag
int VangerUnit::ShellUpdateFlag
Referenced by ChangeVangerProcess(), CreateVangerUnit(), GunDevice::DeviceIn(), ActionDispatcher::FunctionQuant(), InitEnvironment(), NewKeyHandler(), Quant(), SensorQuant(), and ShellNetEvent().
SpeedFactorTime
int VangerUnit::SpeedFactorTime
Referenced by CalcImpulse(), InitAI(), and ResolveGenerator().
SwimPoint
StuffObject* VangerUnit::SwimPoint
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and Quant().
TabuUse
int VangerUnit::TabuUse
Referenced by BulletCollision(), CreateVangerUnit(), DestroyCollision(), and SensorQuant().
TouchKeyObject
SensorDataType* VangerUnit::TouchKeyObject
Referenced by AutomaticTouchSensor(), ChangeVangerProcess(), CreateVangerUnit(), InitEnvironment(), and StopTouchSensor().
TouchKeyObjectFlag
int VangerUnit::TouchKeyObjectFlag
Referenced by AutomaticTouchSensor(), ChangeVangerProcess(), CreateVangerUnit(), InitEnvironment(), and StopTouchSensor().
TractionStat
int VangerUnit::TractionStat
Referenced by Action(), and InitAI().
TractionValue
int VangerUnit::TractionValue
Referenced by Action(), InitAI(), and ResolveGenerator().
UseDeviceMask
int VangerUnit::UseDeviceMask
Referenced by Quant(), UsingCopterig(), UsingCrotrig(), and UsingCutterig().
VangerChanger
VangerUnit* VangerUnit::VangerChanger
Referenced by CreateVangerUnit(), GunDevice::DeviceIn(), InitEnvironment(), ItemQuant(), OutCarNator(), Quant(), and ShellNetEvent().
VangerChangerAngle
int VangerUnit::VangerChangerAngle
Referenced by ChangeVangerProcess(), CreateVangerUnit(), GunDevice::DeviceIn(), and ShellNetEvent().
VangerChangerArmor
int VangerUnit::VangerChangerArmor
Referenced by ChangeVangerProcess(), CreateVangerUnit(), GunDevice::DeviceIn(), and ShellNetEvent().
VangerChangerColor
int VangerUnit::VangerChangerColor
Referenced by ChangeVangerProcess(), CreateVangerUnit(), and GunDevice::DeviceIn().
VangerChangerCount
int VangerUnit::VangerChangerCount
Referenced by CreateVangerUnit(), GunDevice::DeviceIn(), InitEnvironment(), Quant(), and ShellNetEvent().
VangerChangerEnergy
int VangerUnit::VangerChangerEnergy
Referenced by ChangeVangerProcess(), CreateVangerUnit(), GunDevice::DeviceIn(), and ShellNetEvent().
VangerCloneID
int VangerUnit::VangerCloneID
Referenced by InitAI(), ObjectDestroy(), and GameObjectDispatcher::Quant().
VangerRaceStatus
int VangerUnit::VangerRaceStatus
Referenced by BulletCollision(), CalcAiFactor(), ChangeVangerProcess(), CreateVangerUnit(), getObjectPosition(), ActionDispatcher::PromptQuant(), and Quant().
vChangerPosition
Vector VangerUnit::vChangerPosition
Referenced by ChangeVangerProcess(), CreateVangerUnit(), GunDevice::DeviceIn(), and ShellNetEvent().
vMove
Vector VangerUnit::vMove
vRunStartPosition
Vector VangerUnit::vRunStartPosition
Referenced by CalcForce(), CalcImpulse(), InitAI(), and NoWayHandler().
WallCollisionTime
int VangerUnit::WallCollisionTime
Referenced by Action(), InitAI(), and ResolveGenerator().
WeaponDelta
int VangerUnit::WeaponDelta
Referenced by GetAllert(), GetWeaponDelta(), and WeaponGenerator().
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/hobj.cpp
src/units/mechos.cpp