Vangers: DBM Struct Reference
DBM Struct Reference
#include <3d_math.h>
Public Member Functions
DBM ()
DBM (const DBM &m)
DBM (double a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8)
DBM (int angle, int axis)
DBM (double angle, int axis)
DBM (double psi, double tetta, double phi, int mode)
DBM (const DBV &v, double angle)
double operator[] (unsigned int i) const
double operator() (int i, int j) const
double & operator[] (unsigned int i)
double & operator() (int i, int j)
DBM & transpose ()
DBM & operator+= (const DBM &m)
DBM & operator-= (const DBM &m)
DBM & operator*= (const DBM &m)
DBM & operator*= (double w)
DBM & operator/= (double w)
DBM & operator+= (double w)
DBM & operator-= (double w)
DBM operator+ (const DBM &m) const
DBM operator- (const DBM &m) const
DBM operator* (const DBM &m) const
DBM operator* (double w) const
DBM operator/ (double w) const
DBM operator+ (double w) const
DBM operator- (double w) const
void print ()
DBV rotation_angles () const
double rotation_energy () const
double det () const
DBM inverse () const
Public Attributes
double a [9]
Friends
DBM transpose (const DBM &m)
XStream & operator<= (XStream &s, const DBM &v)
XStream & operator>= (XStream &s, DBM &v)
XStream & operator< (XStream &s, DBM &v)
XStream & operator> (XStream &s, DBM &v)
XBuffer & operator<= (XBuffer &b, const DBM &v)
XBuffer & operator>= (XBuffer &b, DBM &v)
XBuffer & operator< (XBuffer &b, const DBM &v)
XBuffer & operator> (XBuffer &b, DBM &v)
Detailed Description
Constructor & Destructor Documentation
DBM() [1/7]
DBM::DBM () inline
 {
     a[0] = 1; a[1] = 0; a[2] = 0;
     a[3] = 0; a[4] = 1; a[5] = 0;
     a[6] = 0; a[7] = 0; a[8] = 1;
 }
References a.
Referenced by DBM().
DBM() [2/7]
DBM::DBM (const DBM & m) inline
 {
     a[0] = m[0]; a[1] = m[1]; a[2] = m[2];
     a[3] = m[3]; a[4] = m[4]; a[5] = m[5];
     a[6] = m[6]; a[7] = m[7]; a[8] = m[8];
 }
References a.
DBM() [3/7]
DBM::DBM (double a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8) inline
 {
     a[0] = a0; a[1] = a1; a[2] = a2;
     a[3] = a3; a[4] = a4; a[5] = a5;
     a[6] = a6; a[7] = a7; a[8] = a8;
 }
References a.
DBM() [4/7]
DBM::DBM (int angle, int axis) inline
 {
 //  ------ Calculate Matrix for ROTATE point an angle ------
     double calpha = Cos(angle);
     double salpha = Sin(angle);
     switch(axis){
         case Z_AXIS:
             a[0]   =  calpha; a[1]   = -salpha; a[2]   = 0;
             a[3]   =  salpha; a[4]   = calpha;  a[5]   = 0;
             a[6]   = 0;   a[7]   = 0;       a[8]   = 1;
             break;
         case X_AXIS:
             a[0]   =  1;      a[1]   =  0;      a[2]   = 0;
             a[3]   =  0;      a[4]   =  calpha; a[5]   = -salpha;
             a[6]   =  0;      a[7]   =  salpha; a[8]   = calpha;
             break;
         case Y_AXIS:
             a[0]   = calpha;  a[1]   =  0;      a[2]   = salpha;
             a[3]   = 0;   a[4]   =  1;      a[5]   = 0;
             a[6]   = -salpha; a[7]   =  0;      a[8]   = calpha;
             break;
         }
 }
References a, Cos(), Sin(), X_AXIS, Y_AXIS, and Z_AXIS.
DBM() [5/7]
DBM::DBM (double angle, int axis) inline
 {
 //  ------ Calculate Matrix for ROTATE point an angle ------
     double calpha = cos(angle);
     double salpha = sin(angle);
     switch(axis){
         case Z_AXIS:
             a[0]   =  calpha; a[1]   = -salpha; a[2]   = 0;
             a[3]   =  salpha; a[4]   = calpha;  a[5]   = 0;
             a[6]   = 0;   a[7]   = 0;       a[8]   = 1;
             break;
         case X_AXIS:
             a[0]   =  1;      a[1]   =  0;      a[2]   = 0;
             a[3]   =  0;      a[4]   =  calpha; a[5]   = -salpha;
             a[6]   =  0;      a[7]   =  salpha; a[8]   = calpha;
             break;
         case Y_AXIS:
             a[0]   = calpha;  a[1]   =  0;      a[2]   = salpha;
             a[3]   = 0;   a[4]   =  1;      a[5]   = 0;
             a[6]   = -salpha; a[7]   =  0;      a[8]   = calpha;
             break;
         }
 }
References a, X_AXIS, Y_AXIS, and Z_AXIS.
DBM() [6/7]
DBM::DBM (double psi, double tetta, double phi, int mode)
 {
     switch(mode){
         case DIAGONAL:
             memset(a,0,sizeof(double)*9);
             a[0] = psi;
             a[4] = tetta;
             a[8] = phi;
             break;
         case EULER:
             if(fabs(phi) < DBL_EPS){
                 double t1 = cos(psi);
                 double t2 = cos(tetta);
                 double t4 = sin(psi);
                 double t5 = sin(tetta);
                 a[0] = t1*t2;  a[1] = -t4;  a[2] = t1*t5;
                 a[3] = t4*t2;  a[4] = t1;   a[5] = t4*t5;
                 a[6] = -t5;    a[7] = 0.0;  a[8] = t2;
                 }
             else{
                 double t1 = cos(psi);
                 double t2 = cos(tetta);
                 double t3 = t1*t2;
                 double t4 = cos(phi);
                 double t6 = sin(psi);
                 double t7 = sin(phi);
                 double t13 = sin(tetta);
                 double t15 = t6*t2;
                 a[0] = t3*t4-t6*t7;  a[1] = -t3*t7-t4*t6;  a[2] = t1*t13;
                 a[3] = t15*t4+t1*t7; a[4] = -t15*t7+t1*t4; a[5] = t6*t13;
                 a[6] = -t13*t4;      a[7] = t13*t7;    a[8] = t2;
                 }
             break;
         case EULER_INV:
             if(fabs(phi) < DBL_EPS){
                 double t1 = cos(psi);
                 double t2 = cos(tetta);
                 double t4 = sin(psi);
                 double t6 = sin(tetta);
                 a[0]   = t1*t2;   a[1]   =  t4*t2;  a[2]   = -t6;
                 a[3]   = -t4;     a[4]   =  t1;     a[5]   = 0;
                 a[6]   = t1*t6;   a[7]   =  t4*t6;  a[8]   = t2;
                 }
             else{
                 double t1 = cos(psi);
                 double t2 = cos(tetta);
                 double t3 = t1*t2;
                 double t4 = cos(phi);
                 double t6 = sin(psi);
                 double t7 = sin(phi);
                 double t10 = t6*t2;
                 double t14 = sin(tetta);
                 a[0] = t3*t4-t6*t7;  a[1] = t10*t4+t1*t7;  a[2] = -t14*t4;
                 a[3] = -t3*t7-t4*t6; a[4] = -t10*t7+t1*t4; a[5] = t14*t7;
                 a[6] = t1*t14;       a[7] = t6*t14;    a[8] = t2;
                 }
             break;
         case AROUND_EULER: {
             double t1 = cos(psi);
             double t2 = t1*t1;
             double t3 = cos(tetta);
             double t4 = t3*t3;
             double t6 = cos(phi);
             double t8 = sin(psi);
             double t9 = t8*t8;
             double t11 = sin(tetta);
             double t12 = t11*t11;
             double t17 = t8*t4*t1*t6;
             double t19 = sin(phi);
             double t20 = t9*t3*t19;
             double t22 = t2*t3*t19;
             double t24 = t1*t8*t6;
             double t26 = t1*t12*t8;
             double t28 = t11*t1;
             double t29 = t3*t6;
             double t30 = t28*t29;
             double t31 = t11*t8;
             double t32 = t31*t19;
             double t33 = t28*t3;
             double t41 = t31*t29;
             double t42 = t28*t19;
             double t43 = t31*t3;
             a[0] = t2*t4*t6+t9*t6+t2*t12;
             a[1] = t17-t20-t22-t24+t26;
             a[2] = -t30+t32+t33;
             a[3] = t17+t22+t20-t24+t26;
             a[4] = t9*t4*t6+t2*t6+t9*t12;
             a[5] = -t41-t42+t43;
             a[6] = -t30-t32+t33;
             a[7] = -t41+t42+t43;
             a[8] = t12*t6+t4;
             break;
             }
         case AROUND_VECTOR: {
             DBV v(psi,tetta,phi);
             (*this) = DBM(v.psi(),v.tetta(),v.vabs(),AROUND_EULER);
             break;
             }
         }
 }
References a, AROUND_EULER, AROUND_VECTOR, DBL_EPS, DBM(), DIAGONAL, EULER, EULER_INV, DBV::psi(), DBV::tetta(), and DBV::vabs().
DBM() [7/7]
DBM::DBM (const DBV & v, double angle)
 {
     (*this) = DBM(v.psi(),v.tetta(),angle,AROUND_EULER);
 }
References AROUND_EULER, DBM(), DBV::psi(), and DBV::tetta().
Member Function Documentation
det()
double DBM::det () const
 {
     return  a[0]*a[4]*a[8] + a[1]*a[6]*a[5] + a[3]*a[7]*a[2] - a[6]*a[4]*a[2] - a[3]*a[1]*a[8] - a[0]*a[5]*a[7];
 }
References a.
inverse()
DBM DBM::inverse () const
 {
       double t4 = a[0]*a[4];
       double t6 = a[0]*a[5];
       double t8 = a[1]*a[3];
       double t10 = a[2]*a[3];
       double t12 = a[1]*a[6];
       double t14 = a[2]*a[6];
       double t17 = 1/(t4*a[8]-t6*a[7]-t8*a[8]+t10*a[7]+t12*a[5]-t14*a[4]);
       DBM inv;
       inv.a[0] = (a[4]*a[8]-a[5]*a[7])*t17;
       inv.a[1] = -(a[1]*a[8]-a[2]*a[7])*t17;
       inv.a[2] = -(-a[1]*a[5]+a[2]*a[4])*t17;
       inv.a[3] = -(a[3]*a[8]-a[5]*a[6])*t17;
       inv.a[4] = (a[0]*a[8]-t14)*t17;
       inv.a[5] = -(t6-t10)*t17;
       inv.a[6] = (a[3]*a[7]-a[4]*a[6])*t17;
       inv.a[7] = -(a[0]*a[7]-t12)*t17;
       inv.a[8] = (t4-t8)*t17;
       return inv;
 }
References a.
Referenced by Object::basic_debris_analysis(), Object::basic_mechous_analysis(), Object::Explosion(), and Object::fish_analysis().
operator()() [1/2]
double& DBM::operator() (int i, int j) inline
 { i--; j--; return a[i + i + i + j]; }
References a.
operator()() [2/2]
double DBM::operator() (int i, int j) const inline
 { i--; j--; return a[i + i + i + j]; }
References a.
operator*() [1/2]
DBM DBM::operator* (const DBM & m) const inline
 {
     DBM m1;
     m1.a[0] = a[0]*m.a[0] + a[1]*m.a[3] + a[2]*m.a[6];
     m1.a[1] = a[0]*m.a[1] + a[1]*m.a[4] + a[2]*m.a[7];
     m1.a[2] = a[0]*m.a[2] + a[1]*m.a[5] + a[2]*m.a[8];
     m1.a[3] = a[3]*m.a[0] + a[4]*m.a[3] + a[5]*m.a[6];
     m1.a[4] = a[3]*m.a[1] + a[4]*m.a[4] + a[5]*m.a[7];
     m1.a[5] = a[3]*m.a[2] + a[4]*m.a[5] + a[5]*m.a[8];
     m1.a[6] = a[6]*m.a[0] + a[7]*m.a[3] + a[8]*m.a[6];
     m1.a[7] = a[6]*m.a[1] + a[7]*m.a[4] + a[8]*m.a[7];
     m1.a[8] = a[6]*m.a[2] + a[7]*m.a[5] + a[8]*m.a[8];
     return m1;
 }
References a.
operator*() [2/2]
DBM DBM::operator* (double w) const inline
 {
     DBM m;
     for(int i = 0;i < 9;i++)
         m.a[i] = a[i]*w;
     return m;
 }
References a.
operator*=() [1/2]
DBM & DBM::operator*= (const DBM & m) inline
 {
     double t[9];
     t[0] = a[0]*m.a[0] + a[1]*m.a[3] + a[2]*m.a[6];
     t[1] = a[0]*m.a[1] + a[1]*m.a[4] + a[2]*m.a[7];
     t[2] = a[0]*m.a[2] + a[1]*m.a[5] + a[2]*m.a[8];
     t[3] = a[3]*m.a[0] + a[4]*m.a[3] + a[5]*m.a[6];
     t[4] = a[3]*m.a[1] + a[4]*m.a[4] + a[5]*m.a[7];
     t[5] = a[3]*m.a[2] + a[4]*m.a[5] + a[5]*m.a[8];
     t[6] = a[6]*m.a[0] + a[7]*m.a[3] + a[8]*m.a[6];
     t[7] = a[6]*m.a[1] + a[7]*m.a[4] + a[8]*m.a[7];
     t[8] = a[6]*m.a[2] + a[7]*m.a[5] + a[8]*m.a[8];
     memcpy(a,t,sizeof(double)*9);
     return *this;
 }
References a.
operator*=() [2/2]
DBM & DBM::operator*= (double w) inline
 {
     for(int i = 0;i < 9;i++)
         a[i] *= w;
     return *this;
 }
References a.
operator+() [1/2]
DBM DBM::operator+ (const DBM & m) const inline
 {
     DBM m1;
     for(int i = 0;i < 9;i++)
         m1.a[i] = a[i] + m.a[i];
     return m1;
 }
References a.
operator+() [2/2]
DBM DBM::operator+ (double w) const inline
 {
     DBM m;
     for(int i = 0;i < 9;i++)
         m.a[i] = a[i] + w;
     return m;
 }
References a.
operator+=() [1/2]
DBM & DBM::operator+= (const DBM & m) inline
 {
     for(int i = 0;i < 9;i++)
         a[i] += m.a[i];
     return *this;
 }
References a.
operator+=() [2/2]
DBM & DBM::operator+= (double w) inline
 {
     for(int i = 0;i < 9;i++)
         a[i] += w;
     return *this;
 }
References a.
operator-() [1/2]
DBM DBM::operator- (const DBM & m) const inline
 {
     DBM m1;
     for(int i = 0;i < 9;i++)
         m1.a[i] = a[i] - m.a[i];
     return m1;
 }
References a.
operator-() [2/2]
DBM DBM::operator- (double w) const inline
 {
     DBM m;
     for(int i = 0;i < 9;i++)
         m.a[i] = a[i] - w;
     return m;
 }
References a.
operator-=() [1/2]
DBM & DBM::operator-= (const DBM & m) inline
 {
     for(int i = 0;i < 9;i++)
         a[i] -= m.a[i];
     return *this;
 }
References a.
operator-=() [2/2]
DBM & DBM::operator-= (double w) inline
 {
     for(int i = 0;i < 9;i++)
         a[i] -= w;
     return *this;
 }
References a.
operator/()
DBM DBM::operator/ (double w) const inline
 {
     DBM m;
     w = 1/w;
     for(int i = 0;i < 9;i++)
         m.a[i] = a[i]*w;
     return m;
 }
References a.
operator/=()
DBM & DBM::operator/= (double w) inline
 {
     w = 1/w;
     for(int i = 0;i < 9;i++)
         a[i] *= w;
     return *this;
 }
References a.
operator[]() [1/2]
double& DBM::operator[] (unsigned int i) inline
 { return a[i]; }
References a.
operator[]() [2/2]
double DBM::operator[] (unsigned int i) const inline
 { return a[i]; }
References a.
print()
void DBM::print ()
                 {
     std::cout<<a[0]<<" \t"<<a[1]<<" \t"<<a[2]<<"\n";
     std::cout<<a[3]<<" \t"<<a[4]<<" \t"<<a[5]<<"\n";
     std::cout<<a[6]<<" \t"<<a[7]<<" \t"<<a[8]<<"\n";
 }
References a.
rotation_angles()
DBV DBM::rotation_angles () const
 {
     return DBV(
         acos(a[0]/sqrt(sqr(a[0]) + sqr(a[3]) + sqr(a[6]) + DBL_EPS)),
         acos(a[4]/sqrt(sqr(a[1]) + sqr(a[4]) + sqr(a[7]) + DBL_EPS)),
         acos(a[8]/sqrt(sqr(a[2]) + sqr(a[5]) + sqr(a[8]) + DBL_EPS))
         );
 }
References a, DBL_EPS, and sqr().
Referenced by rotation_energy().
rotation_energy()
double DBM::rotation_energy () const
 {
     return rotation_angles().vabs();
 }
References rotation_angles(), and DBV::vabs().
transpose()
DBM & DBM::transpose () inline
 {
     double t;
     t = a[1]; a[1] = a[3]; a[3] = t;
     t = a[2]; a[2] = a[6]; a[6] = t;
     t = a[5]; a[5] = a[7]; a[7] = t;
     return *this;
 }
References a.
Friends And Related Function Documentation
operator< [1/2]
XBuffer& operator< (XBuffer & b, const DBM & v) friend
 {
     b < m.a[0] < m.a[1] < m.a[2];
     b < m.a[3] < m.a[4] < m.a[5];
     b < m.a[6] < m.a[7] < m.a[8];
     return b;
 }
operator< [2/2]
XStream& operator< (XStream & s, DBM & v) friend
 {
     s.write(&m,sizeof(DBM));
     return s;
 }
operator<= [1/2]
XBuffer& operator<= (XBuffer & b, const DBM & v) friend
 {
     b <= m.a[0] < " \t" <= m.a[1] < " \t" <= m.a[2] < "\n";
     b <= m.a[3] < " \t" <= m.a[4] < " \t" <= m.a[5] < "\n";
     b <= m.a[6] < " \t" <= m.a[7] < " \t" <= m.a[8] < "\n";
     return b;
 }
operator<= [2/2]
XStream& operator<= (XStream & s, const DBM & v) friend
 {
     s <= m.a[0] < " \t" <= m.a[1] < " \t" <= m.a[2] < "\n";
     s <= m.a[3] < " \t" <= m.a[4] < " \t" <= m.a[5] < "\n";
     s <= m.a[6] < " \t" <= m.a[7] < " \t" <= m.a[8] < "\n";
     return s;
 }
operator> [1/2]
XBuffer& operator> (XBuffer & b, DBM & v) friend
 {
     b > m.a[0] > m.a[1] > m.a[2];
     b > m.a[3] > m.a[4] > m.a[5];
     b > m.a[6] > m.a[7] > m.a[8];
     return b;
 }
operator> [2/2]
XStream& operator> (XStream & s, DBM & v) friend
 {
     s.read(&m,sizeof(DBM));
     return s;
 }
operator>= [1/2]
XBuffer& operator>= (XBuffer & b, DBM & v) friend
 {
     b >= m.a[0] >= m.a[1] >= m.a[2];
     b >= m.a[3] >= m.a[4] >= m.a[5];
     b >= m.a[6] >= m.a[7] >= m.a[8];
     return b;
 }
operator>= [2/2]
XStream& operator>= (XStream & s, DBM & v) friend
 {
     s >= m.a[0] >= m.a[1] >= m.a[2];
     s >= m.a[3] >= m.a[4] >= m.a[5];
     s >= m.a[6] >= m.a[7] >= m.a[8];
     return s;
 }
transpose
DBM transpose (const DBM & m) friend
 {
     return DBM(m[0],m[3],m[6],
                 m[1],m[4],m[7],
                 m[2],m[5],m[8]);
 }
Member Data Documentation
a
double DBM::a[9]
Referenced by Object::basic_mechous_analysis(), DBM(), det(), G2LF(), G2LQ(), ActionUnit::InitEnvironment(), inverse(), Matrix::Matrix(), obb_disjoint(), operator()(), Vector::operator*(), DBV::operator*(), operator*(), operator*(), Vector::operator*=(), DBV::operator*=(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator>(), operator>=(), operator[](), print(), ParticleObject::Quant(), WaterParticleObject::Quant(), TargetParticleObject::Quant(), FishWarrior::Quant(), ActionUnit::Quant(), rotation_angles(), and transpose().
The documentation for this struct was generated from the following files:
src/3d/3d_math.h
src/3d/3d_math.cpp