Vangers: EffectDispatcher Struct Reference
EffectDispatcher Struct Reference
#include <effect.h>
Public Member Functions
void Init (Parser &in)
void Free (void)
void Open (Parser &in)
void Close (void)
void Quant (void)
void CalcWave (void)
void CreateExplosion (const Vector &v, unsigned char _type, BaseObject *_owner=NULL, int _scale=1<< 15, int _dscale=0)
void CreateFireBall (const Vector &v, unsigned char _type, BaseObject *_owner=NULL, int _scale=1<< 8, int _dscale=0)
void CreateDeform (const Vector &v, char _fl, unsigned char _type)
void CreateParticle (char _init, const Vector &v1, const Vector &v2, unsigned char _type)
void CreateParticle (char _init, const Vector &v1, const Vector &v2, const DBM &m, unsigned char Type)
void CreateParticle (char _init, const Vector &v, unsigned char _type)
void CreateDirectParticle (char _init, const Vector &v, unsigned char _type)
void CreateRingOfLord (int type, const Vector v1, int rad, int ltime, int fcol, int lcol, int vel)
void DeleteEffect (BaseObject *p)
void CreateParticleTime (unsigned char _init, const Vector &v1, const Vector &v2, unsigned char _type, int LifeTime)
void CreateParticleGenerator (Vector vC, Vector vT, Vector vD, int mode=PG_STYLE_INCAR)
Public Member Functions inherited from UnitList
void Init (Parser &in)
void Open (Parser &in)
void ConnectTypeList (GeneralObject *p)
void DisconnectTypeList (GeneralObject *p)
void Quant (void)
void ConnectObject (BaseObject *p)
void Add2Next (GeneralObject *p, GeneralObject *t)
void Add2Prev (GeneralObject *p, GeneralObject *t)
GeneralObject * GetNetObject (int id)
virtual void NetEvent (int type, int id)
GeneralObject * GetObject (int type)
void ClearNet (void)
Public Attributes
int NumDeformProcessType
WaveProcess * DeformData
int NumFireBallProcessType
FireBallProcess * FireBallData
int NumParticleInitType
ParticleInitDataType * ParticleInitData
Public Attributes inherited from UnitList
int Total
int * MaxUnit
StorageType * UnitStorage
GeneralObject ** UnitData
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
CalcWave()
void EffectDispatcher::CalcWave (void)
 {
     int i;
     for(i = 0;i < NumDeformProcessType;i++) DeformData[i].Make();
 };
References DeformData, and NumDeformProcessType.
Referenced by LoadingRTO2::Init().
Close()
void EffectDispatcher::Close (void)
 {
     int i;
     BaseObject* p;
     p = (BaseObject*)Tail;
     while(p){
         DeleteEffect(p);
         p = (BaseObject*)(p->NextTypeList);
     };
     for(i = 0;i < MAX_EFFECT_TYPE;i++) UnitStorage[i].Check();
     for(i = 0;i < Total;i++) UnitData[i]->Close();
 };
References DeleteEffect(), MAX_EFFECT_TYPE, GeneralObject::NextTypeList, UnitList::Tail, UnitList::Total, UnitList::UnitData, and UnitList::UnitStorage.
Referenced by GeneralSystemClose().
CreateDeform()
void EffectDispatcher::CreateDeform (const Vector & v, char _fl, unsigned char _type)
 {
     DeformObject* p;
 //  if(_type < 0 || _type >=NumParticleInitType)
 //      ErrH.Abort("Error Number of  Deform System");
     p = (DeformObject*)(UnitStorage[EFF_DEFORM01].Active());
     if(p){
         p->CreateDeform(v,_fl,DeformData + _type);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), DeformObject::CreateDeform(), DeformData, EFF_DEFORM01, GameD, and UnitList::UnitStorage.
Referenced by CreateDestroyEffect(), VangerUnit::Destroy(), GunDevice::DeviceIn(), GunDevice::DeviceOut(), GunDevice::DeviceQuant(), BulletObject::Event(), StuffObject::Quant(), GloryPlace::Quant(), DangerDataType::Quant(), and VangerUnit::SensorQuant().
CreateDirectParticle()
void EffectDispatcher::CreateDirectParticle (char _init, const Vector & v, unsigned char _type)
 {
     ParticleObject* p;
 //  if(_init < 0 || _init >=NumParticleInitType) ErrH.Abort("Error Number of Particle System");
     p = (ParticleObject*)(UnitStorage[_type].Active());
     if(p){
         p->CreateDirectParticle(ParticleInitData + _init,v);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ParticleObject::CreateDirectParticle(), GameD, ParticleInitData, and UnitList::UnitStorage.
CreateExplosion()
void EffectDispatcher::CreateExplosion (const Vector & v, unsigned char _type, BaseObject * _owner = NULL, int _scale = 1 << 15, int _dscale = 0)
 {
     ExplosionObject* p;
     p = (ExplosionObject*)(UnitStorage[_type].Active());
     if(p){
         p->CreateExplosion(v,_owner,_scale,_dscale);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ExplosionObject::CreateExplosion(), GameD, and UnitList::UnitStorage.
Referenced by CreateDestroyEffect(), VangerUnit::Destroy(), BulletObject::Event(), ClefObject::Touch(), and JumpBallObject::Touch().
CreateFireBall()
void EffectDispatcher::CreateFireBall (const Vector & v, unsigned char _type, BaseObject * _owner = NULL, int _scale = 1 << 8, int _dscale = 0)
 {
     FireBallObject* p;
 //  if(_type < 0 || _type >=NumParticleInitType) ErrH.Abort("Error Number of  Deform System");
     p = (FireBallObject*)(UnitStorage[EFF_FIREBALL].Active());
     if(p){
         p->CreateFireBall(v,_owner,_scale,_dscale,_type);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), FireBallObject::CreateFireBall(), EFF_FIREBALL, GameD, and UnitList::UnitStorage.
Referenced by CreateDestroyEffect(), TntCreature::Destroy(), BulletObject::Event(), LandSlideLine(), and TntCreature::NetDestroy().
CreateParticle() [1/3]
void EffectDispatcher::CreateParticle (char _init, const Vector & v, unsigned char _type)
 {
     ParticleObject* p;
 //  if(_init < 0 || _init >=NumParticleInitType) ErrH.Abort("Error Number of Particle System");
     p = (ParticleObject*)(UnitStorage[_type].Active());
     if(p){
         p->CreateParticle(ParticleInitData + _init,v);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ParticleObject::CreateParticle(), GameD, ParticleInitData, and UnitList::UnitStorage.
CreateParticle() [2/3]
void EffectDispatcher::CreateParticle (char _init, const Vector & v1, const Vector & v2, const DBM & m, unsigned char Type)
 {
     ParticleObject* p;
 //  if(_init < 0 || _init >=NumParticleInitType) ErrH.Abort("Error Number of Particle System");
     p = (ParticleObject*)(UnitStorage[_type].Active());
     if(p){
         p->CreateParticle(ParticleInitData + _init,v1,v2,m);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ParticleObject::CreateParticle(), GameD, ParticleInitData, and UnitList::UnitStorage.
CreateParticle() [3/3]
void EffectDispatcher::CreateParticle (char _init, const Vector & v1, const Vector & v2, unsigned char _type)
 {
     ParticleObject* p;
 //  if(_init < 0 || _init >=NumParticleInitType) ErrH.Abort("Error Number of Particle System");
     p = (ParticleObject*)(UnitStorage[_type].Active());
     if(p){
 //      p->CreateParticle(ParticleInitData[_init].LifeTime,ParticleInitData[_init].Velocity,ParticleInitData[_init].FirstRadius,ParticleInitData[_init].EndRadius,ParticleInitData[_init].FirstColor,ParticleInitData[_init].EndColor,v1,v2);
         p->CreateParticle(ParticleInitData + _init,v1,v2);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ParticleObject::CreateParticle(), GameD, ParticleInitData, and UnitList::UnitStorage.
Referenced by ParticleGenerator::DrawQuant(), BulletObject::DrawQuant(), and BulletObject::Event().
CreateParticleGenerator()
void EffectDispatcher::CreateParticleGenerator (Vector vC, Vector vT, Vector vD, int mode = PG_STYLE_INCAR)
 {
     ParticleGenerator* pg;
     pg = (ParticleGenerator*)(UnitStorage[EFF_PARTICLE_GENERATOR].Active());
     if(pg){
         pg->CreateGenerator(vC,vT,vD,mode);
         ConnectTypeList(pg);
         GameD.ConnectBaseList(pg);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ParticleGenerator::CreateGenerator(), EFF_PARTICLE_GENERATOR, GameD, and UnitList::UnitStorage.
Referenced by VangerUnit::AddFree(), VangerUnit::Quant(), DangerDataType::Quant(), and VangerUnit::SensorQuant().
CreateParticleTime()
void EffectDispatcher::CreateParticleTime (unsigned char _init, const Vector & v1, const Vector & v2, unsigned char _type, int LifeTime)
 {
     ParticleObject* p;
 //  if(_init < 0 || _init >=NumParticleInitType) ErrH.Abort("Error Number of Particle System");
     p = (ParticleObject*)(UnitStorage[_type].Active());
     if(p){
         p->CreateParticle(_LifeTime,ParticleInitData[_init].Velocity,ParticleInitData[_init].FirstRadius,ParticleInitData[_init].EndRadius,ParticleInitData[_init].FirstColor,ParticleInitData[_init].EndColor,v1,v2);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ParticleObject::CreateParticle(), GameD, ParticleInitData, and UnitList::UnitStorage.
Referenced by BulletObject::Event().
CreateRingOfLord()
void EffectDispatcher::CreateRingOfLord (int type, const Vector v1, int rad, int ltime, int fcol, int lcol, int vel)
 {
     ParticleObject* p;
     p = (ParticleObject*)(UnitStorage[type].Active());
     if(p){
         p->CreateRingOfLord(v1,rad,ltime,fcol,lcol,vel);
         ConnectTypeList(p);
         GameD.ConnectBaseList(p);
     };
 };
References GameObjectDispatcher::ConnectBaseList(), UnitList::ConnectTypeList(), ParticleObject::CreateRingOfLord(), GameD, and UnitList::UnitStorage.
Referenced by VangerUnit::Quant().
DeleteEffect()
void EffectDispatcher::DeleteEffect (BaseObject * p)
 {
     GameD.DisconnectBaseList(p);
     DisconnectTypeList(p);
     p->Storage->Deactive(p);
 };
References StorageType::Deactive(), GameObjectDispatcher::DisconnectBaseList(), UnitList::DisconnectTypeList(), GameD, and GeneralObject::Storage.
Referenced by Close(), and Quant().
Free()
void EffectDispatcher::Free (void)
 {
     int i;
     delete[] ParticleInitData;
     for(i = 0;i < NumDeformProcessType;i++) DeformData[i].Free();
     delete[] DeformData;
     for(i = 0;i < NumFireBallProcessType;i++) FireBallData[i].Free();
     delete[] FireBallData;
     for(i = 0;i < Total;i++){
         UnitData[i]->Free();
         delete UnitData[i];
     };
     for(i = 0;i < MAX_EFFECT_TYPE;i++) UnitStorage[i].Free();
     delete[] UnitData;
     delete[] MaxUnit;
     delete[] UnitStorage;
 };
References DeformData, FireBallData, MAX_EFFECT_TYPE, UnitList::MaxUnit, NumDeformProcessType, NumFireBallProcessType, ParticleInitData, UnitList::Total, UnitList::UnitData, and UnitList::UnitStorage.
Referenced by GeneralSystemFree().
Init()
void EffectDispatcher::Init (Parser & in)
 {
     int i,j,k;
     UnitList::Init(in);
     Total = 0;
     MaxUnit = new int[MAX_EFFECT_TYPE];
     UnitStorage = new StorageType[MAX_EFFECT_TYPE];
     in.search_name("NumEffect");
     if(RAM16){
         for(i = 0;i < MAX_EFFECT_TYPE;i++){
             MaxUnit[i] = in.get_int();
             MaxUnit[i] /= 2;
             if(MaxUnit[i] == 0) MaxUnit[i] = 1;
             Total += MaxUnit[i];
         };
     }else{
         for(i = 0;i < MAX_EFFECT_TYPE;i++){
             MaxUnit[i] = in.get_int();
             Total += MaxUnit[i];
         };
     };
     UnitData = new GeneralObject*[Total];
     k = 0;
     for(i = 0;i < MAX_EFFECT_TYPE;i++){
         UnitStorage[i].Init(MaxUnit[i]);
         for(j = 0;j < MaxUnit[i];j++){
             switch(i){
                 case EFF_EXPLOSION01:
                 case EFF_EXPLOSION02:
                 case EFF_EXPLOSION03:
                 case EFF_EXPLOSION04:
                 case EFF_EXPLOSION05:
                     UnitData[k] = new ExplosionObject;
                     ((ExplosionObject*)(UnitData[k]))->InitProcess(i - EFF_EXPLOSION01);
                     break;
                 case EFF_DEFORM01:
                     UnitData[k] = new DeformObject;
                     break;
                 case EFF_PARTICLE01:
                     UnitData[k] = new ParticleObject;
                     ((ParticleObject*)(UnitData[k]))->InitParicle(PARTICLE_SIZE01);
                     break;
                 case EFF_PARTICLE02:
                     UnitData[k] = new TargetParticleObject;
                     ((TargetParticleObject*)(UnitData[k]))->InitParicle(PARTICLE_SIZE02);
                     break;
                 case EFF_PARTICLE03:
                     UnitData[k] = new WaterParticleObject;
                     ((WaterParticleObject*)(UnitData[k]))->InitParicle(PARTICLE_SIZE03);
                     break;
                 case EFF_FIREBALL:
                     UnitData[k] = new FireBallObject;
                     break;
                 case EFF_PARTICLE04:
                     UnitData[k] = new WaterParticleObject;
                     ((WaterParticleObject*)(UnitData[k]))->InitParicle(PARTICLE_SIZE04);
                     break;
                 case EFF_PARTICLE05:
                     UnitData[k] = new ParticleObject;
                     ((ParticleObject*)(UnitData[k]))->InitParicle(PARTICLE_SIZE05);
                     break;
                 case EFF_PARTICLE06:
                     UnitData[k] = new ParticleObject;
                     ((ParticleObject*)(UnitData[k]))->InitParicle(PARTICLE_SIZE06);
                     break;
                 case EFF_PARTICLE_GENERATOR:
                     UnitData[k] = new ParticleGenerator;
                     break;
                 case EFF_PARTICLE07:
                     UnitData[k] = new ParticleObject;
                     ((ParticleObject*)(UnitData[k]))->InitParicle(PARTICLE_SIZE07);
             };
             UnitData[k]->Init(&UnitStorage[i]);
             UnitStorage[i].Deactive(UnitData[k]);
             k++;
         };
     };
 /*  XStream fff;
     fff.open("pal.pal",XS_OUT);
     char dd;
     for(i = 0;i < 256;i++){
         dd = 63*i / 256;
         fff < dd < dd < dd;
     };
     fff.close();*/
 //  FireBallProcess aaa;
 //  aaa.Save("e:\\aaa\\aaa\\FireBall.lst");
 //  FireBallProcess bbb;
 //  bbb.Save("c:\\kron\\bml\\FireBall.lst");
     in.search_name("NumFireBallProcessType");
     NumFireBallProcessType = in.get_int();
     FireBallData = new FireBallProcess[NumFireBallProcessType];
 //  char* nnn;
     for(i = 0;i < NumFireBallProcessType;i++){
         in.search_name("NameFireBallProcess");
         FireBallData[i].Load(in.get_name());
 /*      nnn = in.get_name();
         FireBallData[i].Load(nnn);
         FireBallData[i].Convert(nnn);*/
     };
     in.search_name("NumDeformProcessType");
     NumDeformProcessType = in.get_int();
     DeformData = new WaveProcess[NumDeformProcessType];
     for(i = 0;i < NumDeformProcessType;i++){
         in.search_name("NameDeformProcess");
         DeformData[i].Init(in.get_name());
     };
     in.search_name("NumParticleProcessType");
     NumParticleInitType = in.get_int();
     ParticleInitData = new ParticleInitDataType[NumParticleInitType];
     for(i = 0;i < NumParticleInitType;i++){
         in.search_name("LifeTime");
         ParticleInitData[i].LifeTime = in.get_int();
         in.search_name("Velocity");
         ParticleInitData[i].Velocity = in.get_int() << in.get_int();
         in.search_name("FirstRadius");
         ParticleInitData[i].FirstRadius = in.get_int();
         in.search_name("EndRadius");
         ParticleInitData[i].EndRadius = in.get_int();
         in.search_name("FirstColor");
         ParticleInitData[i].FirstColor = in.get_int();
         in.search_name("EndColor");
         ParticleInitData[i].EndColor = in.get_int();
         in.search_name("FirstAlpha");
         ParticleInitData[i].FirstAlpha = in.get_int();
         in.search_name("StepAlpha");
         ParticleInitData[i].StepAlpha = in.get_int();
     };
 };
References StorageType::Deactive(), DeformData, EFF_DEFORM01, EFF_EXPLOSION01, EFF_EXPLOSION02, EFF_EXPLOSION03, EFF_EXPLOSION04, EFF_EXPLOSION05, EFF_FIREBALL, EFF_PARTICLE01, EFF_PARTICLE02, EFF_PARTICLE03, EFF_PARTICLE04, EFF_PARTICLE05, EFF_PARTICLE06, EFF_PARTICLE07, EFF_PARTICLE_GENERATOR, ParticleInitDataType::EndColor, ParticleInitDataType::EndRadius, FireBallData, ParticleInitDataType::FirstAlpha, ParticleInitDataType::FirstColor, ParticleInitDataType::FirstRadius, Parser::get_int(), Parser::get_name(), WaveProcess::Init(), StorageType::Init(), UnitList::Init(), ParticleInitDataType::LifeTime, FireBallProcess::Load(), MAX_EFFECT_TYPE, UnitList::MaxUnit, NumDeformProcessType, NumFireBallProcessType, NumParticleInitType, PARTICLE_SIZE01, PARTICLE_SIZE02, PARTICLE_SIZE03, PARTICLE_SIZE04, PARTICLE_SIZE05, PARTICLE_SIZE06, PARTICLE_SIZE07, ParticleInitData, RAM16, Parser::search_name(), ParticleInitDataType::StepAlpha, UnitList::Total, UnitList::UnitData, UnitList::UnitStorage, and ParticleInitDataType::Velocity.
Referenced by GeneralSystemInit().
Open()
void EffectDispatcher::Open (Parser & in)
 {
     int i;
     UnitList::Open(in);
     for(i = 0;i < Total;i++) UnitData[i]->Open();
 };
References UnitList::Open(), UnitList::Total, and UnitList::UnitData.
Referenced by GeneralSystemOpen().
Quant()
void EffectDispatcher::Quant (void)
 {
     BaseObject* p;
 /*  SPViewX = ViewX << 15;
     SPViewY = ViewY << 15;
     SPScaleMap = ScaleMap << 7;
     SPTorXSize = TOR_XSIZE << 15;*/
     SPViewX = ViewX << 8;
     SPViewY = ViewY << 8;
     SPScaleMap = ScaleMap;
     SPTorXSize = TOR_XSIZE << 8;
     SPTorYSize = TOR_YSIZE << 8;
     p = (BaseObject*)Tail;
     while(p){
         p->Quant();
         p = (BaseObject*)(p->NextTypeList);
     };
     p = (BaseObject*)Tail;
     while(p){
         if(p->Status & SOBJ_DISCONNECT) DeleteEffect(p);
         p = (BaseObject*)(p->NextTypeList);
     };
 };
References DeleteEffect(), GeneralObject::NextTypeList, ScaleMap, SOBJ_DISCONNECT, SPScaleMap, SPTorXSize, SPTorYSize, SPViewX, SPViewY, GeneralObject::Status, UnitList::Tail, TOR_XSIZE, TOR_YSIZE, ViewX, and ViewY.
Referenced by GameObjectDispatcher::Quant().
Member Data Documentation
DeformData
WaveProcess* EffectDispatcher::DeformData
Referenced by CalcWave(), ActionUnit::CreateActionUnit(), CreateDeform(), BulletObject::DrawQuant(), Free(), Init(), and DangerDataType::Quant().
FireBallData
FireBallProcess* EffectDispatcher::FireBallData
Referenced by aWriteHelpString(), FireBallObject::CreateFireBall(), BulletObject::DrawQuant(), Free(), and Init().
NumDeformProcessType
int EffectDispatcher::NumDeformProcessType
Referenced by CalcWave(), Free(), and Init().
NumFireBallProcessType
int EffectDispatcher::NumFireBallProcessType
Referenced by Free(), and Init().
NumParticleInitType
int EffectDispatcher::NumParticleInitType
Referenced by Init().
ParticleInitData
ParticleInitDataType* EffectDispatcher::ParticleInitData
Referenced by CreateDirectParticle(), CreateParticle(), CreateParticleTime(), Free(), and Init().
The documentation for this struct was generated from the following files:
src/units/effect.h
src/units/effect.cpp