Vangers: aciML_Event Struct Reference
aciML_Event Struct Reference
#include <mlstruct.h>
Public Member Functions
int check_key (int k)
int check_seq (void)
void start (void)
void stop (void)
void quant (void)
void inc_timer (void)
void add_key (int k)
void add_command (aciML_EventCommand *p)
aciML_Event (void)
~aciML_Event (void)
Public Member Functions inherited from iListElement
void init_id (const char *p)
iListElement (void)
~iListElement (void)
Public Attributes
int startupType
int data
int rndValue
int ChannelID
int priority
int cur_timer
int active_time
int flags
aKeyObj * keys
iList * commands
Public Attributes inherited from iListElement
std::string ID_ptr
int name_len
iListElement * prev
iListElement * next
Detailed Description
Constructor & Destructor Documentation
aciML_Event()
aciML_Event::aciML_Event (void)
 {
     startupType = AML_KEY;
     data = 0;
     rndValue = 0;
     cur_timer = 0;
     active_time = 1;
     flags = 0;
     ChannelID = 0;
     priority = 0;
     keys = new aKeyObj;
     commands = new iList;
 }
References active_time, AML_KEY, ChannelID, commands, cur_timer, data, flags, keys, priority, rndValue, and startupType.
~aciML_Event()
aciML_Event::~aciML_Event (void)
 {
     aciML_EventCommand* cm,*cm1;
     delete keys;
     cm = (aciML_EventCommand*)commands -> last;
     while(cm){
         cm1 = (aciML_EventCommand*)cm -> prev;
         delete cm;
         cm = cm1;
     }
     delete commands;
 }
References commands, keys, and iListElement::prev.
Member Function Documentation
add_command()
void aciML_Event::add_command (aciML_EventCommand * p)
 {
     commands -> connect((iListElement*)p);
     p -> owner = (iListElement*)this;
 }
References commands.
add_key()
void aciML_Event::add_key (int k) inline
 { keys -> add_key(k); }
References add_key(), and keys.
Referenced by add_key().
check_key()
int aciML_Event::check_key (int k)
 {
     return keys -> check(key);
 }
References key(), and keys.
check_seq()
int aciML_Event::check_seq (void)
 {
     aciML_EventCommand* cm = (aciML_EventCommand*)commands -> last;
     while(cm){
         if(cm -> start_timer == cur_timer){
             if(!(cm -> flags & AML_COMMAND_STARTED)) return 0;
             switch(cm -> code){
                 case AML_WAIT_CHANNEL:
                     if(isChannelActive(cm -> data0)) return 0;
                     break;
                 case AML_GO_INFINITE:
                     if(!isActiveIML(cm -> data0)) return 0;
                     break;
                 case AML_PUT_IN_QUEUE:
                     if(!isActiveIML(cm -> data1)) return 0;
                     break;
                 case AML_PUT_IN_CH_QUEUE:
                     if(!isLockedIML(cm -> data1) && (isInQueueIML(cm -> data0,cm -> data1))) return 0;
                     break;
                 case AML_ADD_IN_CH_QUEUE:
                     if(!isLockedIML(cm -> data1) && (isInQueueIML(cm -> data0,cm -> data1) || !isActiveIML(cm -> data1))) return 0;
                     break;
                 case AML_GO_PHASE:
                 case AML_CLOSE_ML:
                 case AML_INVERT_PHASE:
                     if(isActiveIML(cm -> data0)) return 0;
                     break;
             }
         }
         cm = (aciML_EventCommand*)cm -> prev;
     }
     return 1;
 }
References AML_ADD_IN_CH_QUEUE, AML_CLOSE_ML, AML_COMMAND_STARTED, AML_GO_INFINITE, AML_GO_PHASE, AML_INVERT_PHASE, AML_PUT_IN_CH_QUEUE, AML_PUT_IN_QUEUE, AML_WAIT_CHANNEL, commands, cur_timer, flags, isActiveIML(), isChannelActive(), isInQueueIML(), isLockedIML(), and iListElement::prev.
Referenced by inc_timer().
inc_timer()
void aciML_Event::inc_timer (void)
 {
     if(!(flags & AML_SEQUENCE_EVENT) || check_seq())
         cur_timer ++;
     if(cur_timer > active_time)
         stop();
 }
References active_time, AML_SEQUENCE_EVENT, check_seq(), cur_timer, flags, and stop().
quant()
void aciML_Event::quant (void)
 {
     aciML_EventCommand* cm = (aciML_EventCommand*)commands -> last;
     while(cm){
         if(cm -> start_timer == cur_timer && !(cm -> flags & AML_COMMAND_STARTED)){
             switch(cm -> code){
                 case AML_IS_LOCKED:
                     if(isLockedIML(cm -> data0)){
                         stop();
                         return;
                     }
                     break;
                 case AML_IS_NOT_LOCKED:
                     if(!isLockedIML(cm -> data0)){
                         stop();
                         return;
                     }
                     break;
                 case AML_EVENT_IS_ACTIVE:
                     if(isEventActive(cm -> data1,cm -> data0)){
                         stop();
                         return;
                     }
                     break;
                 case AML_IS_ACTIVE:
                     if(isActiveIML(cm -> data0)){
                         stop();
                         return;
                     }
                     break;
                 default:
                     aciML_SendEvent(cm -> code,cm -> data0,cm -> data1);
                     break;
             }
             cm -> flags |= AML_COMMAND_STARTED;
         }
         cm = (aciML_EventCommand*)cm -> prev;
     }
 }
References aciML_SendEvent(), AML_COMMAND_STARTED, AML_EVENT_IS_ACTIVE, AML_IS_ACTIVE, AML_IS_LOCKED, AML_IS_NOT_LOCKED, commands, cur_timer, flags, isActiveIML(), isEventActive(), isLockedIML(), iListElement::prev, and stop().
start()
void aciML_Event::start (void)
 {
     aciML_EventCommand* cm;
     if(flags & AML_ACTIVE_EVENT && flags & AML_NO_DEACTIVATE) return;
     cm = (aciML_EventCommand*)commands -> last;
     while(cm){
         cm -> flags &= ~AML_COMMAND_STARTED;
         cm = (aciML_EventCommand*)cm -> prev;
     }
     flags &= ~AML_FINISHED;
     flags |= AML_ACTIVE_EVENT;
     cur_timer = 0;
 }
References AML_ACTIVE_EVENT, AML_COMMAND_STARTED, AML_FINISHED, AML_NO_DEACTIVATE, commands, cur_timer, flags, and iListElement::prev.
stop()
void aciML_Event::stop (void) inline
 { flags &= ~AML_ACTIVE_EVENT; flags |= AML_FINISHED; }
References AML_ACTIVE_EVENT, AML_FINISHED, and flags.
Referenced by inc_timer(), and quant().
Member Data Documentation
active_time
int aciML_Event::active_time
Referenced by aciML_Event(), and inc_timer().
ChannelID
int aciML_Event::ChannelID
Referenced by aciML_Event().
commands
iList* aciML_Event::commands
Referenced by aciML_Event(), add_command(), check_seq(), quant(), start(), and ~aciML_Event().
cur_timer
int aciML_Event::cur_timer
Referenced by aciML_Event(), check_seq(), inc_timer(), quant(), and start().
data
int aciML_Event::data
Referenced by aciML_Event().
flags
int aciML_Event::flags
Referenced by aciML_Event(), check_seq(), inc_timer(), quant(), start(), and stop().
keys
aKeyObj* aciML_Event::keys
Referenced by aciML_Event(), add_key(), check_key(), and ~aciML_Event().
priority
int aciML_Event::priority
Referenced by aciML_Event().
rndValue
int aciML_Event::rndValue
Referenced by aciML_Event().
startupType
int aciML_Event::startupType
Referenced by aciML_Event().
The documentation for this struct was generated from the following files:
src/actint/mlstruct.h
src/actint/actintml.cpp