Vangers: TrackType Struct Reference
TrackType Struct Reference
#include <track.h>
Public Member Functions
void Open (char *filename)
void Save (char *filename)
void Close (void)
void GetPosition (int x, int y, LinkType *&ln, BranchType *&bn)
void GetPosition (int x, int y, LinkType *&ln, BranchType *&bn, NodeType *&n)
void GetPosition (TrackLinkType *p)
void GetFirstPosition (int x, int y, LinkType *&ln, BranchType *&bn)
void GetInsidePosition (TrackLinkType *p)
Public Attributes
int NumNode
int NumBranch
NodeType * node
BranchType * branch
Detailed Description
Member Function Documentation
Close()
void TrackType::Close (void)
 {
     int i;
     for(i = 0;i < NumBranch;i++) branch[i].Close();
     for(i = 0;i < NumNode;i++) node[i].Close();
     delete[] node;
     delete[] branch;
 };
References branch, node, NumBranch, and NumNode.
Referenced by GeneralSystemClose().
GetFirstPosition()
void TrackType::GetFirstPosition (int x, int y, LinkType *& ln, BranchType *& bn)
 {
     int i,j;
     int d1,d2,d3,md,d;
     LinkType* l;
     BranchType* b;
     LinkType* ml;
     BranchType* mb;
     md = 0xffffff;
     b = branch;
     ml = NULL;
     mb = NULL;
     for(i = 0;i < NumBranch;i++,b++){
         l = b->Link;
         for(j = 0;j < b->NumLink;j++,l++){
             d1 = abs(getDistX(l->x,x)) + abs(getDistY(l->y,y));
             d2 = abs(getDistX(l->xr,x)) + abs(getDistY(l->yr,y));
             d3 = abs(getDistX(l->xl,x)) + abs(getDistY(l->yl,y));
             d = MIN(MIN(d1,d2),d3);
             if(d < md){
                 md = d;
                 ml = l;
                 mb = b;
             };
         };
     };
     if(ml){
         ln = ml;
         bn = mb;
     };
 };
References branch, getDistX(), getDistY(), BranchType::Link, MIN, NULL, NumBranch, BranchType::NumLink, LinkType::x, LinkType::xl, LinkType::xr, LinkType::y, LinkType::yl, and LinkType::yr.
Referenced by VangerUnit::ChangeVangerProcess(), and TrackUnit::CreateTrackUnit().
GetInsidePosition()
void TrackType::GetInsidePosition (TrackLinkType * p)
 {
     int i,j;
     Vector vTrack;
     LinkType* ml;
     LinkType* pml;
     BranchType* mb;
     NodeType* nn;
 //  Vector vCheck = R_curr;
     Vector vCheck;
     vCheck = p->vPoint;
     mb = branch;
     for(i = 0;i < NumBranch;i++,mb++){
         if(vCheck.y > mb->Top && vCheck.y < mb->Bottom){
             pml = mb->Link;
             ml = pml + 1;
             for(j = 1;j < mb->NumLink;j++){
                 if(CheckInLink(vCheck,pml,ml)){
                     p->pBranch = mb;
                     p->pNextLink = ml;
                     p->pPrevLink = pml;
                     p->PointStatus = TRK_IN_BRANCH;
                     return;
                 };
                 pml = ml;
                 ml++;
             };
         };
     };
     nn = HideTrack.node;
     for(i = 0;i < HideTrack.NumNode;i++,nn++){
         if(vCheck.y > nn->Top && vCheck.y < nn->Bottom){
             if(CheckInNode(vCheck,nn) && nn->z < vCheck.z){
                 p->pNode = nn;
                 p->PointStatus = TRK_IN_NODE;
                 return;
             };
         };
     };
     p->PointStatus = TRK_OUT_BRANCH;
 };
References BranchType::Bottom, NodeType::Bottom, branch, CheckInLink(), CheckInNode(), HideTrack, BranchType::Link, node, NumBranch, BranchType::NumLink, NumNode, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, BranchType::Top, NodeType::Top, TRK_IN_BRANCH, TRK_IN_NODE, TRK_OUT_BRANCH, TrackLinkType::vPoint, Vector::y, Vector::z, and NodeType::z.
GetPosition() [1/3]
void TrackType::GetPosition (int x, int y, LinkType *& ln, BranchType *& bn)
 {
     int i,j;
     int d,md;
     LinkType* l;
     BranchType* b;
     LinkType* ml;
     BranchType* mb;
     md = 0xffffff;
     b = branch;
     ml = NULL;
     mb = NULL;
     for(i = 0;i < NumBranch;i++,b++){
         if(y > b->Top && y < b->Bottom){
             l = b->Link;
             for(j = 0;j < b->NumLink;j++,l++){
                 d = abs(getDistX(l->x,x)) + abs(getDistY(l->y,y));
                 if(d < md){
                     md = d;
                     ml = l;
                     mb = b;
                 };
             };
         };
     };
     if(ml){
         ln = ml;
         bn = mb;
     };
 };
References branch, getDistX(), getDistY(), BranchType::Link, NULL, NumBranch, BranchType::NumLink, BranchType::Top, LinkType::x, and LinkType::y.
Referenced by VangerUnit::AddFindResolve(), VangerUnit::CalcForce(), VangerUnit::CalcImpulse(), VangerUnit::Quant(), and VangerUnit::ResolveHandlerFind().
GetPosition() [2/3]
void TrackType::GetPosition (int x, int y, LinkType *& ln, BranchType *& bn, NodeType *& n)
 {
     int i,j;
     int d,md1,md2;
     LinkType* l;
     BranchType* b;
     NodeType* nn;
     LinkType* ml;
     BranchType* mb;
     NodeType* mn;
     md1 = 0xffffff;
     b = branch;
     ml = NULL;
     mb = NULL;
     for(i = 0;i < NumBranch;i++,b++){
         if(y > b->Top && y < b->Bottom){
             l = b->Link;
             for(j = 0;j < b->NumLink;j++,l++){
                 d = abs(getDistX(l->x,x)) + abs(getDistY(l->y,y));
                 if(d < md1){
                     md1 = d;
                     ml = l;
                     mb = b;
                 };
             };
         };
     };
     md2 = 0xffffff;
     nn = node;
     mn = NULL;
     for(i = 0;i < NumNode;i++,nn++){
         d = abs(getDistX(nn->x,x)) + abs(getDistY(nn->y,y));
         if(d < md2){
             mn = nn;
             md2 = d;
         };
     };
     if(!mn) ErrH.Abort("Bad find near node");
     if(ml){
         if(md1 < md2){
             n = NULL;
             ln = ml;
             bn = mb;
         }else{
             ln = NULL;
             bn = NULL;
             n = mn;
         };
     }else{
         ln = NULL;
         bn = NULL;
         n = mn;
     };
 };
References XErrorHandler::Abort(), branch, ErrH, getDistX(), getDistY(), BranchType::Link, node, NULL, NumBranch, BranchType::NumLink, NumNode, BranchType::Top, LinkType::x, NodeType::x, LinkType::y, and NodeType::y.
GetPosition() [3/3]
void TrackType::GetPosition (TrackLinkType * p)
 {
     int x,y;
     int i,j;
     int d,md1,md2;
     LinkType* l;
     LinkType* ml;
     BranchType* b;
     BranchType* mb;
     NodeType* nn;
     NodeType* mn;
     md1 = 0xffffff;
     b = branch;
     mb = NULL;
     x = p->vPoint.x;
     y = p->vPoint.y;
     for(i = 0;i < NumBranch;i++,b++){
         if(y > b->Top && y < b->Bottom){
             l = b->Link;
             for(j = 0;j < b->NumLink;j++,l++){
                 d = abs(getDistX(l->x,x)) + abs(getDistY(l->y,y));
                 if(d < md1){
                     md1 = d;
                     ml = l;
                     mb = b;
                 };
             };
         };
     };
     md2 = 0xffffff;
     nn = node;
     mn = NULL;
     for(i = 0;i < NumNode;i++,nn++){
         d = abs(getDistX(nn->x,x)) + abs(getDistY(nn->y,y));
         if(d < md2){
             mn = nn;
             md2 = d;
         };
     };
     if(!mn) ErrH.Abort("Bad find near node");
     if(mb && md1 < md2){
         p->pNextLink = ml;
         p->pBranch = mb;
         if(ml == mb->Link){
             p->pPrevLink = ml;
             p->pNextLink++;
         }else p->pPrevLink = p->pNextLink - 1;
         if(CheckInBranch(p->vPoint,p->pPrevLink,p->pNextLink,p->pBranch)) p->PointStatus = TRK_IN_BRANCH;
         else p->PointStatus = TRK_OUT_BRANCH;
     }else{
         p->pNode = mn;
         if(CheckInNode(p->vPoint,p->pNode)) p->PointStatus = TRK_IN_NODE;
         else p->PointStatus = TRK_OUT_NODE;
     };
 };
References XErrorHandler::Abort(), branch, CheckInBranch(), CheckInNode(), ErrH, getDistX(), getDistY(), BranchType::Link, node, NULL, NumBranch, BranchType::NumLink, NumNode, TrackLinkType::pBranch, TrackLinkType::pNextLink, TrackLinkType::pNode, TrackLinkType::PointStatus, TrackLinkType::pPrevLink, BranchType::Top, TRK_IN_BRANCH, TRK_IN_NODE, TRK_OUT_BRANCH, TRK_OUT_NODE, TrackLinkType::vPoint, Vector::x, LinkType::x, NodeType::x, Vector::y, LinkType::y, and NodeType::y.
Open()
void TrackType::Open (char * filename)
 {
     int i;
     XStream fin(GetTargetName(filename), XS_IN);
     fin > NumNode > NumBranch;
     node = new NodeType[NumNode];
     branch = new BranchType[NumBranch];
     for(i = 0;i < NumNode;i++ ) node[i].Open(fin,branch,i);
     for(i = 0;i < NumBranch;i++) branch[i].Open(fin,node,i);
     fin.close();
     for(i = 0;i < NumNode;i++){
         for(int j = 0;j < node[i].NumBranch;j++){
             if(node[i].Status[j] && node[i].pBranches[j]->pBeg != &node[i]) ErrH.Abort("Bad Status Node");
             if(!(node[i].Status[j]) && node[i].pBranches[j]->pEnd != &node[i]) ErrH.Abort("Bad Status Node");
         };
     };
 };
References XErrorHandler::Abort(), branch, XStream::close(), ErrH, GetTargetName(), node, NodeType::NumBranch, NumBranch, NumNode, and XS_IN.
Referenced by GeneralSystemOpen().
Save()
void TrackType::Save (char * filename)
 {
     int i;
     XStream flib(GetTargetName(filename), XS_OUT);
     flib < NumNode < NumBranch;
     for(i = 0;i < NumNode;i++ ) node[i].Save(flib);
     for(i = 0;i < NumBranch;i++) branch[i].Save(flib);
     flib.close();
 };
References branch, XStream::close(), GetTargetName(), node, NumBranch, NumNode, and XS_OUT.
Member Data Documentation
branch
BranchType* TrackType::branch
Referenced by VangerUnit::CheckNearTrack(), Close(), GetFirstPosition(), TrackUnit::GetInside(), GetInsidePosition(), TrackUnit::GetNode(), GetPosition(), TrackUnit::MakeTrackDist(), Open(), and Save().
node
NodeType* TrackType::node
Referenced by VangerUnit::CheckNearTrack(), Close(), TrackUnit::GetInside(), GetInsidePosition(), GetPosition(), Open(), Save(), and TrackUnit::TraceWay().
NumBranch
int TrackType::NumBranch
Referenced by VangerUnit::CheckNearTrack(), Close(), GetFirstPosition(), TrackUnit::GetInside(), GetInsidePosition(), GetPosition(), TrackUnit::MakeTrackDist(), Open(), TrackUnit::Open(), and Save().
NumNode
int TrackType::NumNode
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CheckNearTrack(), Close(), TrackUnit::CreateTrackUnit(), TrackUnit::GetInside(), GetInsidePosition(), GetPosition(), Open(), TrackUnit::Open(), Save(), VangerUnit::TargetAnalysis(), TrackUnit::TraceWay(), and TrackUnit::WayInit().
The documentation for this struct was generated from the following files:
src/units/track.h
src/units/track.cpp