Vangers: BulletList Struct Reference
BulletList Struct Reference
#include <items.h>
Public Member Functions
BulletObject * CreateBullet (void)
void FreeUnit (GeneralObject *p)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Init (void)
virtual void Free (void)
virtual void Quant (void)
virtual void NetEvent (int type, int id)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Additional Inherited Members
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
CreateBullet()
BulletObject * BulletList::CreateBullet (void)
 {
     BulletObject* p;
     p = new BulletObject;
     p->Init();
     ConnectTypeList(p);
     return p;
 };
References UnitBaseListType::ConnectTypeList(), and BulletObject::Init().
Referenced by TntCreature::Destroy(), DangerDataType::FireWork(), VangerUnit::InitEnvironment(), VangerUnit::keyhandler(), TntCreature::NetDestroy(), TntCreature::NetQuant(), VangerUnit::NewKeyHandler(), GunSlot::Quant(), VangerFunctionType::Quant(), TntCreature::Quant(), and VangerUnit::ShellNetEvent().
FreeUnit()
void BulletList::FreeUnit (GeneralObject * p) virtual
Reimplemented from UnitListType.
 {
     if(((BulletObject*)(p))->LightData){
         ((BulletObject*)(p))->LightData->Destroy();
         ((BulletObject*)(p))->LightData = NULL;
     };
     DisconnectTypeList(p);
     delete p;
 };
References UnitBaseListType::DisconnectTypeList(), and NULL.
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp