Vangers: uvsVanger Struct Reference
uvsVanger Struct Reference
#include <univang.h>
Public Member Functions
uvsVanger (void)
uvsVanger (uvsEscave *pe)
uvsVanger (XStream &)
~uvsVanger (void)
void save (XStream &)
virtual void Quant (void)
virtual void emuQuant (void)
void Event (UvsEventType ev)
int isBunchReady (void)
int emptyContainer (uvsEscave *)
void prepare_diagen_statistic (void)
void prepare_list_for_ActInt (uvsActInt *&, uvsActInt *&, uvsShop *, int where)
void get_list_from_ActInt (uvsActInt *&, uvsActInt *&)
void start_race (void)
void thief_from_escave (uvsEscave *)
void thief_from_spot (uvsSpot *)
void thief_from_shop (uvsShop *)
int prepare_killer (void)
void prepare_caravan (void)
void go_from_escave (void)
void go_from_spot (void)
void goCirt (void)
void goDolly (void)
void goHome (void)
void goNewEscave (void)
void go_to_GAMER (void)
void addInventory (void)
int addItem (uvsItem *pi, int w=0)
void sell_treasure_Item (uvsShop *)
void sell_move_Item (uvsShop *, int where)
int makeJump (void)
void aimHandle (void)
void homeArrival ()
void spotArrival ()
int add_to_game (uvsCultGame *)
int add_to_race (uvsCultGame *)
int addGOODS (uvsCultGame *)
int game_result (const char *)
int race_result (uvsCultGame *, const char *)
int harvest_result (uvsCultGame *, const char *)
void break_harvest (void)
void update (int x, int y)
void shiftOrders (void)
void gatherCirt (uvsDolly *dolly)
void gatherCirt (int x, int y, int &p1, int &p2)
int CurrentDolly (void)
int GoodTabuTask (void)
int newGoodTabuTask (void)
int GoodWorldTabuTask (void)
int CirtDelivery (void)
int sellCirt (void)
void _sellCirt_ (void)
void checkDolly (void)
void _checkDolly_ (void)
int checkCycle (int stage)
void set_target (uvsTarget *, int)
void UpdateAllTarget (void)
int buildWay (uvsWorld *fromW, uvsWorld *toW)
void changeRating (int val)
void KillStatic (void)
void destroy (int how=0)
void get_shop (int)
void prepare_shop (int)
void emuStep (void)
void emuCheck (void)
Public Member Functions inherited from uvsElement
uvsElement (void)
void elink (uvsElement *&tail)
void eunlink (uvsElement *&tail)
void delink (uvsElement *&tail)
Public Member Functions inherited from uvsTarget
uvsTarget (void)
Public Attributes
int gIndex
uvsMechos * Pmechos
listElem * Pitem
uvsWorld * Pworld
uvsEscave * Pescave
uvsSpot * Pspot
uvsPassage * Ppassage
UvsVangerShapeType shape
UvsVangerStatusType status
uvsBunch * owner
int biosNindex
uvsOrder * orderT
int locTimer
int rating
int speed
Public Attributes inherited from uvsElement
uvsElement * enext
uvsElement * eprev
UvsObjectType type
Public Attributes inherited from uvsTarget
int pos_x
int pos_y
Detailed Description
Constructor & Destructor Documentation
uvsVanger() [1/3]
uvsVanger::uvsVanger (void) inline
                     : uvsElement(), uvsTarget(){
         Pmechos = NULL;
         Pitem = NULL;
         Pworld = NULL;
         Pescave = NULL;
         Pspot = NULL;
         Ppassage = NULL;
         shape = status = biosNindex = locTimer = rating = speed = 0;
         owner = NULL;
         orderT = NULL;
     }
References biosNindex, locTimer, NULL, orderT, owner, Pescave, Pitem, Pmechos, Ppassage, Pspot, Pworld, rating, shape, speed, and status.
uvsVanger() [2/3]
uvsVanger::uvsVanger (uvsEscave * pe)
{
     type = UVS_OBJECT::VANGER;  // common uvsElement type
     gIndex = currentVanger++;
     rating = 1; // minimal
     status = UVS_VANGER_STATUS::ESCAVE_SLEEPING;        // состояние движения
     shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;          // принадлежность "души"
     owner = pe -> Pbunch;
     Pworld = pe -> Pworld;
     Pescave = owner -> Pescave;
     Pspot = NULL;
     Ppassage = NULL;
     Pmechos = NULL;             // указатель на мехос
     Pitem = NULL;                   // указатель на инвентори
     pos_x = pe -> pos_x;
     pos_y = pe -> pos_y;
     biosNindex = RND(BIOS_MAX);                 // bios случайный
     orderT = new uvsOrder[ORDER_V_MAX];
     speed = 10 + RND(V_SPEED_MAX);
     locTimer = 0;
 //  cirtStage = cirtQ = 0;
 }
References gIndex, uvsElement::type, and UVS_OBJECT::VANGER.
uvsVanger() [3/3]
uvsVanger::uvsVanger (XStream & pfile)
{
     type = UVS_OBJECT::VANGER;  // common uvsElement type
     int i;
     int count;
     char *s;
     char is;
     pfile > gIndex; // номер вангера
     pfile > rating; // minimal
     pfile > status;     // состояние движения
     pfile > shape;          // принадлежность "души"
     pfile > i;
     Pworld  = WorldTable[i];
     pfile > is;
     if(is) Pmechos = new uvsMechos(pfile); else Pmechos = NULL;
     pfile > count;
     uvsItem *pi;
     Pitem = NULL;
     for( i = 0; i < count; i++) {
         (pi = new uvsItem(pfile)) -> link(Pitem);
     }
     s = get_string(pfile);
     if ( s ) {
         Pescave = (uvsEscave*)EscaveTail -> seekName(s);
         owner = Pescave -> Pbunch;
         delete[] s;
     }else owner = NULL;
     s = get_string(pfile);
     if ( s ) {
         Pescave = (uvsEscave*)EscaveTail -> seekName(s);
         delete[] s;
     } else {
         Pescave = NULL;
     }
     s = get_string(pfile);
     if ( s ) {
         Pspot = (uvsSpot*)SpotTail -> seekName(s);
         delete[] s;
     }else Pspot = NULL;
     s = get_string(pfile);
     if ( s ) {
         Ppassage = (uvsPassage*)PassageTail -> seekName(s);
         delete[] s;
     }else Ppassage = NULL;
     pfile > pos_x;
     pfile > pos_y;
     pfile > biosNindex;                 // bios случайный
     orderT = new uvsOrder[ORDER_V_MAX];
     for ( i = 0; i < ORDER_V_MAX; i++){
         pfile > orderT[i].type;
         pfile > orderT[i].event;
         pfile > orderT[i].target;
         switch (orderT[i].target){
         case UVS_TARGET::FLY_FARMER:
             s = get_string(pfile);
             orderT[i].Ptarget = Pworld -> get_anymal( pos_x, pos_y, UVS_OBJECT::FLY_FARMER);
             if (!orderT[i].Ptarget) ErrH.Abort("uvsVanger::load - bad FlyFarmer");
             break;
         case UVS_TARGET::NONE:
             s = get_string(pfile);
             orderT[i].Ptarget = NULL;
             break;
         case UVS_TARGET::PASSAGE:
             s = get_string(pfile);
             orderT[i].Ptarget = (uvsTarget*)((uvsPassage*)PassageTail -> seekName(s));
             delete[] s;
             break;
         case UVS_TARGET::ESCAVE:
             s = get_string(pfile);
             orderT[i].Ptarget = (uvsTarget*)((uvsEscave*)EscaveTail -> seekName(s));
             delete[] s;
             break;
         case UVS_TARGET::SPOT:
             s = get_string(pfile);
             orderT[i].Ptarget = (uvsTarget*)((uvsSpot*)SpotTail -> seekName(s));
             delete[] s;
             break;
         case UVS_TARGET::DOLLY:  {
             int cd;
             s = get_string(pfile);
             pfile > cd;
             uvsDolly* pd = (uvsDolly*)DollyTail;
             while(pd){
                 if(pd -> gIndex == cd ) break;
                 pd = (uvsDolly*)pd -> next;
             }
             if(!pd) ErrH.Abort(PrmWrongValue,XERR_USER,-1,"Dolly");
             orderT[i].Ptarget = (uvsTarget*)pd;
         }
             break;
         case UVS_TARGET::VANGER:
             s = get_string(pfile);
 //          if (shape != UVS_VANGER_SHAPE::GAMER && shape != UVS_VANGER_SHAPE::KILLER)
 //              ErrH.Abort("uvsVanger :: load - target vanger not in Gamer");
             if (shape == UVS_VANGER_SHAPE::GAMER)
                 pfile > gIndex;
             break;
         case UVS_TARGET::ITEM:
             s = get_string(pfile);
             break;
         case UVS_TARGET::HIVE:
             orderT[i].target = UVS_TARGET::NONE;
             if (uvsLoadVersion < 1)
                 s = get_string(pfile);
             break;
         case UVS_TARGET::CRYPT:
             orderT[i].target = UVS_TARGET::NONE;
             if (uvsLoadVersion == 1)
                 s = get_string(pfile);
             break;
         case UVS_TARGET::WHIRLPOOL:
             orderT[i].target = UVS_TARGET::NONE;
             if (uvsLoadVersion < 4)
                 s = get_string(pfile);
             break;
         case UVS_TARGET::SWAMP:
             orderT[i].target = UVS_TARGET::NONE;
             if (uvsLoadVersion < 5)
                 s = get_string(pfile);
             break;
         case UVS_TARGET::SHEILD:
             orderT[i].target = UVS_TARGET::NONE;
             if (uvsLoadVersion < 5)
                 s = get_string(pfile);
             break;
         case UVS_TARGET::VANGERS:
             orderT[i].target = UVS_TARGET::NONE;
             if (uvsLoadVersion == 1)
                 s = get_string(pfile);
             break;
         default:
             orderT[i].target = UVS_TARGET::NONE;
             break;
         }
     }
     pfile > speed;
     locTimer = 1;
     if ( shape == UVS_VANGER_SHAPE::THIEF ){
         uvsItem *pi = GetItem_as_type( Pitem,  UVS_ITEM_STATUS::TREASURE);
         if ( !pi ) shape = UVS_VANGER_SHAPE::RANGER;
     };
 }
References XErrorHandler::Abort(), biosNindex, UVS_TARGET::DOLLY, DollyTail, ErrH, UVS_TARGET::ESCAVE, EscaveTail, uvsOrder::event, UVS_OBJECT::FLY_FARMER, UVS_TARGET::FLY_FARMER, get_string(), gIndex, UVS_TARGET::NONE, NULL, ORDER_V_MAX, orderT, owner, UVS_TARGET::PASSAGE, PassageTail, Pescave, Pitem, Pmechos, uvsTarget::pos_x, uvsTarget::pos_y, Ppassage, Pspot, uvsOrder::Ptarget, Pworld, rating, shape, UVS_TARGET::SPOT, SpotTail, status, uvsOrder::target, uvsOrder::type, uvsElement::type, UVS_OBJECT::VANGER, and WorldTable.
~uvsVanger()
uvsVanger::~uvsVanger (void)
{
     //if(orderT)delete orderT;
     //(Pmechos)delete (uvsMechos*)Pmechos;
     FreeList(Pitem);
 }
References FreeList(), and uvsEscave::Pitem.
Member Function Documentation
_checkDolly_()
void uvsVanger::_checkDolly_ (void)
{
     int i;
     uvsItem *pi;
     pi = GetItem(Pitem, UVS_ITEM_TYPE::CONLARVER, 0);
     GamerResult.dolly = 0;
     GamerResult.dolly_cycle = -1;
     if (!pi || !pi -> param1) return;
     GamerResult.dolly = UVS_DOLLY_TYPE::ALIEN;
     if (Pworld -> escTmax) {
         uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
         for( i = 0; i < pb -> cycleN; i++){
             if (pb -> cycleTable[i].Pdolly -> gIndex == pi -> param1){
                 GamerResult.dolly = UVS_DOLLY_TYPE::OWN;
                 GamerResult.dolly_cycle = i;
 #ifdef STAND_REPORT
                 stand < "dolly from cycle  "<= i  < "\n";
 #endif
                 break;
             }//  end if
         }//  end for
     }//  end if
 #ifdef STAND_REPORT
     stand < "dolly  "<= GamerResult.dolly  < "\n";
 #endif
 }
References UVS_DOLLY_TYPE::ALIEN, UVS_ITEM_TYPE::CONLARVER, uvsGamerResult::dolly, uvsGamerResult::dolly_cycle, GamerResult, GetItem(), UVS_DOLLY_TYPE::OWN, uvsEscave::Pbunch, uvsEscave::Pitem, and uvsEscave::Pworld.
_sellCirt_()
void uvsVanger::_sellCirt_ (void)
{
     int  i = 0;
     int have_full = 0;
     int tmp_good = 0;
     int tmp_bad = 0;
     int tmp_total_good = 0;
     int tmp_total_bad = 0;
     int last_param2;
     int cool_index = 0;
     uvsActInt* pa = GGamer;
     uvsItem *pi;
     if (!Pworld -> escTmax) return;
     uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
     pi = GetItem(Pitem, UVS_ITEM_TYPE::CIRTAINER, 0);
     GamerResult.cirt_bad = -1;
     GamerResult.cirt_good = -1;
     while( pi ){
         tmp_good = 0;
         tmp_bad = 0;
         last_param2  = pi -> param2;
         if (pi -> param2){
             have_full = 1;
             for ( i = 0; i < pb -> cycleN; i++){
                 //if( ((1 << (pb -> cycleTable[i].Pdolly -> gIndex)) & pi -> param2) && ((pi -> param1 >> (pb -> cycleTable[i].Pdolly -> gIndex*2)) & 3)) {
                 if( ((1 << (pb -> cycleTable[i].Pdolly -> gIndex)) & last_param2)) {
                     if (tmp_good < ((pi -> param1 >> (pb -> cycleTable[i].Pdolly -> gIndex*3)) & 7)){
                         tmp_good = ((pi -> param1 >> (pb -> cycleTable[i].Pdolly -> gIndex*3)) & 7);
                         cool_index = pb -> cycleTable[i].Pdolly -> gIndex;
                     }
                     last_param2 ^= (1 << (pb -> cycleTable[i].Pdolly -> gIndex));
                 }
             }//  end for j
             if (last_param2)
                 for ( i = 1; i < DollyIndex; i++){
                     if( (1 << i) & last_param2) {
                         if ( tmp_bad < ((pi -> param1 >> (i*3)) & 7)  )
                             tmp_bad =  ((pi -> param1 >> (i*3)) & 7);
                     }
                 }
             if (tmp_good >= tmp_bad && tmp_good > 0){
                 tmp_good = 0;
     //          if(cool_index == -1) ErrH.Abort("uvsVanger::sellCirt - good cirt not found but it have");
                 if ( cool_index == pb -> cycleTable[pb -> currentStage].Pdolly -> gIndex ){
                         tmp_good += 2*((pi -> param1 >> (cool_index*3)) & 7);
                 } else {
                         tmp_good += ((pi -> param1 >> (cool_index*3)) & 7);
                 }
                 tmp_total_good += tmp_good;
             } else {
                 tmp_total_bad += tmp_bad;
 //              if (tmp_bad > 0)
 //                  uvsCheckKronIventTabuTask(UVS_KRON_EVENT::BAD_CIRT, tmp_bad);
             }
         }
         pi = GetItem( pi -> next, UVS_ITEM_TYPE::CIRTAINER, 0 );
     }
 #ifdef _ROAD_
     if (have_full){
         GamerResult.cirt_good = tmp_total_good;
         GamerResult.cirt_bad = tmp_total_bad;
     }
 #ifdef STAND_REPORT
     stand < "cirt good "<= GamerResult.cirt_good < "  cirt bad " <= GamerResult.cirt_bad < "\n";
 #endif
 #endif
 }
References uvsGamerResult::cirt_bad, uvsGamerResult::cirt_good, UVS_ITEM_TYPE::CIRTAINER, GamerResult, GetItem(), GGamer, uvsEscave::Pbunch, uvsEscave::Pitem, and uvsEscave::Pworld.
add_to_game()
int uvsVanger::add_to_game (uvsCultGame * pg)
{
     if ( Pescave != (uvsEscave*)(pg -> townBeg) && Pspot != (uvsSpot*)(pg -> townBeg) ) return 0;
     switch( pg -> GameType ){
     case UVS_GAME_TYPE::RACE:
         return add_to_race( pg );
         break;
     }
     return 0;
 }
References add_to_race(), Pescave, Pspot, and UVS_GAME_TYPE::RACE.
add_to_race()
int uvsVanger::add_to_race (uvsCultGame * pg)
{
     if ( !(Pmechos -> status & UVS_MECHOS_USED::RACE) ) return 0;
     if (pg -> total >= V_RACE_VANGER )
         return 0;
     if ( pg -> GoodsBegCount > 0) {
          addItem( new uvsItem(pg -> GoodsTypeBeg), 1);
          pg -> GoodsBegCount--;
     }
     pg -> total++;
 #ifdef STAND_REPORT
     stand < ConTimer.GetTime();
     stand < "\t add to race -> Vanger::";
     switch (shape){
     case UVS_VANGER_SHAPE::BUNCH_SLAVE:
         stand < "slave\n";
         break;
     case UVS_VANGER_SHAPE::CARAVAN:
         stand < "caravan\n";
         break;
     case UVS_VANGER_SHAPE::RANGER:
         stand < "ranger\n";
         break;
     case UVS_VANGER_SHAPE::THIEF:
         stand < "thief\n";
         break;
     case UVS_VANGER_SHAPE::TABUTASK:
         stand < "tabutask\n";
         break;
     }
 #endif
     addInventory();
     if (pg -> GoodsTypeBegCount == 1){
         if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE )
             status = UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_ESCAVE;
         else
             status = UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_SPOT;
     } else {
         if ( pg -> typeTownBeg == UVS_TOWN::ESCAVE )
             status = UVS_VANGER_STATUS::GAME_BEGIN_ESCAVE;
         else
             status = UVS_VANGER_STATUS::GAME_BEGIN_SPOT;
     }
     if ( pg -> typeTownEnd == UVS_TOWN::ESCAVE){
         uvsEscave* pe = (uvsEscave*) (pg -> townEnd);
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_ESCAVE;
         ord -> target = UVS_TARGET::ESCAVE;
         ord -> Ptarget = (uvsTarget*)pe;
         //Pescave = pe;
     } else {
         uvsSpot* pe = (uvsSpot*) (pg -> townEnd);
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_SPOT;
         ord -> target = UVS_TARGET::SPOT;
         ord -> Ptarget = (uvsTarget*)pe;
         //Pspot = pe;
     }
     return 1;
 }
References addInventory(), addItem(), UVS_VANGER_SHAPE::BUNCH_SLAVE, UVS_VANGER_SHAPE::CARAVAN, ConTimer, UVS_TOWN::ESCAVE, UVS_TARGET::ESCAVE, UVS_VANGER_STATUS::GAME_BEGIN_ESCAVE, UVS_VANGER_STATUS::GAME_BEGIN_SPOT, UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_ESCAVE, UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_SPOT, uvsContimer::GetTime(), UVS_EVENT::GO_ESCAVE, UVS_EVENT::GO_SPOT, UVS_ORDER::MOVING, orderT, Pmechos, UVS_MECHOS_USED::RACE, UVS_VANGER_SHAPE::RANGER, shape, UVS_TARGET::SPOT, status, UVS_VANGER_SHAPE::TABUTASK, UVS_VANGER_SHAPE::THIEF, uvsElement::type, and V_RACE_VANGER.
Referenced by add_to_game().
addGOODS()
int uvsVanger::addGOODS (uvsCultGame * pg)
{
     uvsItem *pi;
     if (( pg -> typeTownBeg == UVS_TOWN::ESCAVE && ((uvsEscave*)(pg -> townBeg)) == Pescave ) ||
        ( pg -> typeTownBeg == UVS_TOWN::SPOT && ((uvsSpot*)(pg -> townBeg)) == Pspot )){
         if ( pg -> GoodsBegCount > 0) {
             pi = new uvsItem(pg -> GoodsTypeBeg);
             pi -> param1 = Pworld -> gIndex<<16;
              if (!addItem(pi)) {
                 delete pi;
                 return 0;
              }
              pg -> GoodsBegCount--;
              return 1;
         } else return 0;
     }
     return 0;
 }
References addItem(), UVS_TOWN::ESCAVE, gIndex, Pescave, Pspot, Pworld, and UVS_TOWN::SPOT.
addInventory()
void uvsVanger::addInventory (void)
{
 //  DBGCHECK;
     int i;
     uvsItem *pi;
     char* ItemHere;
     if (Pescave)
         ItemHere = Pescave -> Pshop -> ItemHere;
     else
         ItemHere = Pspot -> Pshop -> ItemHere;
     if ( uvsMechosTable[Pmechos -> type] -> type == ((int)UVS_CAR_TYPE::RAFFA) ) return;
     if (shape == UVS_VANGER_SHAPE::KILLER){
         pi = new uvsItem(UVS_ITEM_TYPE::SPEETLE_SYSTEM_HEAVY);
         if(!addItem(pi)) delete pi;
         pi = new uvsItem(UVS_ITEM_TYPE::SPEETLE_SYSTEM_LIGHT);
         if(!addItem(pi)) delete pi;
         pi = new uvsItem(UVS_ITEM_TYPE::SPEETLE_SYSTEM_LIGHT);
         if(!addItem(pi)) delete pi;
         for( int i = 0; i < 10; i++){
             pi = new uvsItem(UVS_ITEM_TYPE::SPEETLE_SYSTEM_AMMO1);
             addItem(pi, 1);
         }
     }
     i = RND(6);
     while(!ItemHere[i]){
         i = RND(6);
     }
     pi = new uvsItem(i);
     if(!addItem(pi)) {
          ((uvsItem*)pi) -> type = 0;
          if(!addItem(pi)) delete pi;
     }
     if ( !ItemHere[UVS_ITEM_TYPE::TERMINATOR] ){
         i = RND(6);
         while(!ItemHere[i]){
             i = RND(6);
         }
         pi = new uvsItem(i);
     } else {
         pi = new uvsItem(UVS_ITEM_TYPE::TERMINATOR);
     }
     if(!addItem(pi)) delete (uvsItem*)pi;
     if (!RND(3) && ItemHere[UVS_ITEM_TYPE::COPTE_RIG]){
         pi = new uvsItem(UVS_ITEM_TYPE::COPTE_RIG);
         if(!addItem(pi)) delete (uvsItem*)pi;
     }
     if ( (shape == UVS_VANGER_SHAPE::KILLER ||
          shape == UVS_VANGER_SHAPE::CARAVAN ||
          shape == UVS_VANGER_SHAPE::RANGER ||
          shape == UVS_VANGER_SHAPE::THIEF)
          && (ItemHere[UVS_ITEM_TYPE::RADAR_DEVICE])
          ){
         pi = new uvsItem(UVS_ITEM_TYPE::RADAR_DEVICE);
         if(!addItem(pi)) delete (uvsItem*)pi;
     }
 //  DBGCHECK;
 }
References addItem(), UVS_VANGER_SHAPE::CARAVAN, UVS_ITEM_TYPE::COPTE_RIG, UVS_VANGER_SHAPE::KILLER, Pescave, Pmechos, Pspot, UVS_ITEM_TYPE::RADAR_DEVICE, UVS_CAR_TYPE::RAFFA, UVS_VANGER_SHAPE::RANGER, RND(), shape, UVS_ITEM_TYPE::SPEETLE_SYSTEM_AMMO1, UVS_ITEM_TYPE::SPEETLE_SYSTEM_HEAVY, UVS_ITEM_TYPE::SPEETLE_SYSTEM_LIGHT, UVS_ITEM_TYPE::TERMINATOR, UVS_VANGER_SHAPE::THIEF, uvsElement::type, and uvsMechosTable.
Referenced by add_to_race().
addItem()
int uvsVanger::addItem (uvsItem * pi, int w = 0)
{
     int l_box[4];
     int k_box[4];
     int i;
     if ( !w ){
         memset(l_box, 0, sizeof(int)*4);
         listElem* pe = Pitem;
     //   проверка загруженности
         while(pe){
             l_box[uvsItemTable[((uvsItem*)pe) -> type] -> size]++;
             pe = pe -> next;
         }
         l_box[ uvsItemTable[((uvsItem*)pi) -> type ] -> size]++;
         memcpy(k_box, uvsMechosTable[Pmechos -> type] -> box, sizeof(int)*4 );
         for(i = 0; i < 4; i++){
             if( l_box[i] > k_box[i])
                 return 0;
             else if ( i != 3) k_box[i+1] += k_box[i] - l_box[i];
         }
     }
     pi -> link(Pitem);
     return 1;
 }
References Pitem, uvsElement::type, and uvsItemTable.
Referenced by add_to_race(), addGOODS(), addInventory(), uvsUnitType::Go2Universe(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), and VangerUnit::OutCarNator().
aimHandle()
void uvsVanger::aimHandle (void)
{
     uvsOrder* ord = orderT;
     switch(ord -> type){
         case UVS_ORDER::CIRT_GATHERING:
             gatherCirt((uvsDolly*)(ord -> Ptarget));
             shiftOrders();
             goHome();
             break;
         }
 }
References UVS_ORDER::CIRT_GATHERING.
break_harvest()
void uvsVanger::break_harvest (void)
{
     uvsCultGame* pg;
     pg = Pworld -> escT[0] -> Pbunch -> cycleTable[Pworld -> escT[0] -> Pbunch -> currentStage].Pgame;
     if (!pg) {
         ErrH.Abort("uvsVanger::break_harvest : don't now where go ");
         return;
     }
     if (pg -> typeTownEnd == UVS_TOWN::SPOT){
         if (Pspot && !strcmp(Pspot -> name, ((uvsSpot*)(pg -> townEnd)) -> name)) return;
         set_target((uvsTarget*)((uvsSpot*)pg -> townEnd), UVS_TARGET::SPOT);
     } else {
         if (Pescave && !strcmp(Pescave -> name, ((uvsEscave*)(pg -> townEnd)) -> name)) return;
         set_target( (uvsTarget*)((uvsEscave*)pg -> townEnd), UVS_TARGET::ESCAVE);
     }
 }
References XErrorHandler::Abort(), ErrH, UVS_TARGET::ESCAVE, Pescave, Pspot, Pworld, set_target(), UVS_TOWN::SPOT, and UVS_TARGET::SPOT.
Referenced by VangerUnit::ResolveGenerator().
buildWay()
int uvsVanger::buildWay (uvsWorld * fromW, uvsWorld * toW)
{
     uvsWorld* nextW,*tmpW = NULL;
     uvsWorld *lastfromW = NULL, *lasttoW = NULL;
     uvsOrder* ord;
     uvsPassage* pp;
     int i = 0;
     if (fromW -> gIndex >= MAIN_WORLD_MAX ) {
         lastfromW = fromW;
         fromW = fromW -> pssT[0] -> Poutput;
         ord = orderT;
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_PASSAGE;
         ord -> target = UVS_TARGET::PASSAGE;
         ord -> Ptarget = (uvsTarget*)lastfromW -> pssT[0];
         i = 1;
     }
     if (toW -> gIndex >= MAIN_WORLD_MAX ) {
         lasttoW = toW;
         toW = toW -> pssT[0] -> Poutput;
     }
     unsigned int linkage = ChainMap[toW -> gIndex + fromW -> gIndex*MAIN_WORLD_MAX],mI;
     if ( fromW == toW ) return 0;
     for(; i < 8; i++){
         mI = (linkage & (0x0000000F << 4*i)) >> 4*i;
         nextW = getWorld(mI);
         if(!nextW)  nextW = toW;
         pp = fromW -> getPassage(nextW);
         if ( !pp ) ErrH.Abort( "buildWay:: not passage");
         ord = orderT + i;
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_PASSAGE;
         ord -> target = UVS_TARGET::PASSAGE;
         ord -> Ptarget = (uvsTarget*)pp;
         fromW = nextW;
         if ( fromW == toW ) break;
     }
     i++;
     if ( lasttoW ){
         pp = fromW -> getPassage(lasttoW);
         ord = orderT + i;
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_PASSAGE;
         ord -> target = UVS_TARGET::PASSAGE;
         ord -> Ptarget = (uvsTarget*)pp;
         i++;
     }
     return (i);
 }
References UVS_EVENT::GO_PASSAGE, MAIN_WORLD_MAX, UVS_ORDER::MOVING, NULL, and UVS_TARGET::PASSAGE.
changeRating()
void uvsVanger::changeRating (int val)
{
     rating += val;
     if ( uvsMechosTable[Pmechos -> type] -> type == UVS_CAR_TYPE::RAFFA ) {
         rating = 0;
         shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
         return;
     }
     if ( shape == UVS_VANGER_SHAPE::THIEF || shape == UVS_VANGER_SHAPE::CARAVAN) return;
     if(rating >= V_RANGER_MAX){
         rating -= V_RANGER_MAX;
         shape = UVS_VANGER_SHAPE::RANGER;
 //      Pmechos -> color = 3;
     }
 }
References UVS_VANGER_SHAPE::BUNCH_SLAVE, UVS_VANGER_SHAPE::CARAVAN, UVS_CAR_TYPE::RAFFA, UVS_VANGER_SHAPE::RANGER, UVS_VANGER_SHAPE::THIEF, uvsMechosTable, and V_RANGER_MAX.
checkCycle()
int uvsVanger::checkCycle (int stage)
{
     if (!Pworld -> escTmax) return 0;
     uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
     if (pb -> cycleTable[stage].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE)
         return 0;
     else
         return 1;
 }
References uvsEscave::Pbunch, uvsEscave::Pworld, and UVS_DOLLY_STATUS::UNABLE.
checkDolly()
void uvsVanger::checkDolly (void)
{
     int i;
     uvsItem *pi;
     pi = GetItem(Pitem, UVS_ITEM_TYPE::CONLARVER, 0);
     GamerResult.dolly = 0;
     GamerResult.dolly_cycle = -1;
     if (!pi || !pi -> param1) return;
     GamerResult.dolly = UVS_DOLLY_TYPE::ALIEN;
     if (Pworld -> escTmax) {
         uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
         for( i = 0; i < pb -> cycleN; i++){
             if (pb -> cycleTable[i].Pdolly -> gIndex == pi -> param1){
                 GamerResult.dolly = UVS_DOLLY_TYPE::OWN;
                 GamerResult.dolly_cycle = i;
 #ifdef STAND_REPORT
                 stand < "dolly from cycle  "<= i  < "\n";
 #endif
                 if (Pescave){
                     aciUpdateCurCredits(aciGetCurCredits() + CASH_FOR_DOLLY);
                     pi -> param1 = 0;
                     pi -> param2 = 0;
                     GamerResult.luck += 10;
                     ShowLuckMessage(10);
                     if (GamerResult.luck > 100) GamerResult.luck = 100;
                     SOUND_END_LARVA()
 //                  uvs_aciChangeItem(uvsItemTable[UVS_ITEM_TYPE::CONLARVER] -> SteelerTypeFull, uvsItemTable[UVS_ITEM_TYPE::CONLARVER] -> SteelerTypeEmpty);
                     uvs_aciKillOneItem( uvsItemTable[UVS_ITEM_TYPE::CONLARVER] -> SteelerTypeFull, pi -> pos_x,  pi -> pos_y);
                     pb -> cycleTable[i].Pdolly -> status = UVS_DOLLY_STATUS::UNABLE;
                     pi -> delink(Pitem);
                     delete pi;
                     pb -> Quant();
                 }//  end if
                 break;
             }//  end if
         }//  end for
     }//  end if
 #ifdef STAND_REPORT
     stand < "dolly  "<= GamerResult.dolly  < "\n";
 #endif
 }
References aciGetCurCredits(), aciUpdateCurCredits(), UVS_DOLLY_TYPE::ALIEN, CASH_FOR_DOLLY, UVS_ITEM_TYPE::CONLARVER, uvsGamerResult::dolly, uvsGamerResult::dolly_cycle, GamerResult, GetItem(), uvsGamerResult::luck, UVS_DOLLY_TYPE::OWN, uvsEscave::Pbunch, uvsEscave::Pitem, uvsTarget::pos_x, uvsTarget::pos_y, uvsEscave::Pworld, ShowLuckMessage(), SOUND_END_LARVA, UVS_DOLLY_STATUS::UNABLE, uvs_aciKillOneItem(), and uvsItemTable.
CirtDelivery()
int uvsVanger::CirtDelivery (void)
{
     int Total = 0;
     uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
     for( int i = 0; i < pb -> cycleN; i++)
         Total += pb -> cycleTable[i].GamerCirt;
     return Total;
 }
References uvsEscave::Pbunch, and uvsEscave::Pworld.
CurrentDolly()
int uvsVanger::CurrentDolly (void)
{
     if (Pworld -> escTmax){
         uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
         return pb -> cycleTable[ pb -> currentStage ].Pdolly -> gIndex;
     } else
         return -1;
 }
References uvsEscave::Pbunch, and uvsEscave::Pworld.
Referenced by VangerUnit::CalcAiFactor().
destroy()
void uvsVanger::destroy (int how = 0)
{
     int i;
     if(shape == UVS_VANGER_SHAPE::GAMER){
 #ifdef _ROAD_
         GameQuantReturnValue = RTO_LOADING3_ID;
         Dead = 1;
         return;
 #endif
     }
     type = UVS_OBJECT::VANGER;  // common uvsElement type
     if (how)
         uvsCheckVangerTabuTask(this, uvsVANGER_KILLED);
     else
         uvsCheckVangerTabuTask(this, uvsVANGER_FAILED);
     rating = 1; // minimal
     status = UVS_VANGER_STATUS::ESCAVE_SLEEPING;        // состояние движения
     shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;          // принадлежность "души"
     Pworld = WorldTable[RND(3)];
     if (Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE ){
         for( i = 0; i < 3; i++){
             if (WorldTable[i] -> escT[0] -> Pbunch -> status != UVS_BUNCH_STATUS::UNABLE){
                 Pworld = WorldTable[i];
                 break;
             }//  end if
         }//  end for
     } //  end if
     Pescave = Pworld -> escT[0];
     Pmechos -> color = Pescave -> Pbunch -> biosNindex;
     Pescave -> Pshop -> addMechos(Pmechos);
     Pmechos = NULL;
     owner = Pescave -> Pbunch;
     Pspot = NULL;
     Ppassage = NULL;
     FreeList( Pitem );
     Pitem = NULL;
     pos_x =  Pescave -> pos_x;
     pos_y =  Pescave -> pos_y;
     biosNindex = RND(BIOS_MAX);                 // bios случайный
     //orderT = new uvsOrder[ORDER_V_MAX];
     for ( i = 0; i < ORDER_V_MAX; i++){
         orderT[i].type = UVS_ORDER::NONE;
         orderT[i].target = UVS_TARGET::NONE;
         orderT[i].Ptarget = NULL;
     }
     speed = 3 + RND(V_SPEED_MAX);
     locTimer = 0;
     //eunlink(ETail);
     //delink(deleteETail);
 }
References BIOS_MAX, UVS_VANGER_SHAPE::BUNCH_SLAVE, Dead, UVS_VANGER_STATUS::ESCAVE_SLEEPING, FreeList(), GameQuantReturnValue, UVS_VANGER_SHAPE::GAMER, UVS_TARGET::NONE, UVS_ORDER::NONE, NULL, ORDER_V_MAX, uvsEscave::Pbunch, uvsEscave::Pitem, uvsTarget::pos_x, uvsTarget::pos_y, uvsEscave::Pshop, uvsEscave::Pworld, RND(), RTO_LOADING3_ID, UVS_BUNCH_STATUS::UNABLE, uvsCheckVangerTabuTask(), uvsVANGER_FAILED, uvsVANGER_KILLED, V_SPEED_MAX, UVS_OBJECT::VANGER, and WorldTable.
Referenced by ActionDispatcher::Close().
emptyContainer()
int uvsVanger::emptyContainer (uvsEscave * pe)
{
     uvsItem *pi = (uvsItem*)Pitem;
     int tmp = 0;
     int tmp_p = 0;
     int out = 0;
     if (!pe) ErrH.Abort("uvsVanger:: empty container dont have Escave");
     while( !out ){
         out = 1;
         pi = GetItem(Pitem, UVS_ITEM_TYPE::CIRTAINER, 0);
         if( pi ){
             tmp += pe -> Pbunch -> addCirt(pi);
             ((uvsItem*)pi) -> delink(Pitem);
             delete (uvsItem*)pi;
             out = 0;
         }
     }
     return tmp;
 }
References XErrorHandler::Abort(), UVS_ITEM_TYPE::CIRTAINER, ErrH, GetItem(), uvsEscave::Pbunch, and uvsEscave::Pitem.
emuCheck()
void uvsVanger::emuCheck (void)
{
     uvsOrder* ord = orderT;
     if (shape  == UVS_VANGER_SHAPE::KILLER){
         go_to_GAMER();
     }
     if(abs(ord -> Ptarget -> pos_y - pos_y) <= V_SPEED_MAX){
         pos_y = ord -> Ptarget -> pos_y;
         if ( (ord -> event == UVS_EVENT::GO_CIRT) && (abs(ord -> Ptarget -> pos_x - pos_x) <= V_CIRT_R/2)){
             Event(UVS_EVENT::AIM_ARRIVAL);
         } else  if(abs(ord -> Ptarget -> pos_x - pos_x) <= V_SPEED_MAX ){
             pos_x = ord -> Ptarget -> pos_x;
             pos_y = ord -> Ptarget -> pos_y;
             switch(ord -> event){
                 case UVS_EVENT::GO_SPOT:
                     Pspot = (uvsSpot*)(orderT -> Ptarget);
                     Event(UVS_EVENT::SPOT_ARRIVAL);
                     break;
                 case UVS_EVENT::GO_ESCAVE:
                     Pescave = (uvsEscave*)(orderT -> Ptarget);
                     Event(UVS_EVENT::ESCAVE_ARRIVAL);
                     break;
                 case UVS_EVENT::GO_PASSAGE:
                     //Ppassage = (uvsPassage*)( orderT -> Ptarget);
                     Event(UVS_EVENT::PASSAGE_ARRIVAL);
                     break;
                 case UVS_EVENT::GO_CORN:
                     break;
                 case UVS_EVENT::GO_KILL:
                     break;
                 default:
                     ErrH.Abort("emuCheck arrival to never.");
                     break;
             }//  end switch
         }//  end if
     }//  end if
 }
References XErrorHandler::Abort(), UVS_EVENT::AIM_ARRIVAL, ErrH, UVS_EVENT::ESCAVE_ARRIVAL, UVS_EVENT::GO_CIRT, UVS_EVENT::GO_CORN, UVS_EVENT::GO_ESCAVE, UVS_EVENT::GO_KILL, UVS_EVENT::GO_PASSAGE, UVS_EVENT::GO_SPOT, UVS_VANGER_SHAPE::KILLER, UVS_EVENT::PASSAGE_ARRIVAL, uvsTarget::pos_x, uvsTarget::pos_y, UVS_EVENT::SPOT_ARRIVAL, V_CIRT_R, and V_SPEED_MAX.
emuQuant()
void uvsVanger::emuQuant (void) virtual
Reimplemented from uvsElement.
{
 #ifdef _ROAD_
     if((CurrentWorld == Pworld -> gIndex) && uvsKronActive) return;
 #endif
     switch(shape){
         case UVS_VANGER_SHAPE::TABUTASK:
         case UVS_VANGER_SHAPE::BUNCH_SLAVE:
         case UVS_VANGER_SHAPE::RANGER:
         case UVS_VANGER_SHAPE::THIEF:
         case UVS_VANGER_SHAPE::CARAVAN:
         case UVS_VANGER_SHAPE::KILLER:
             switch(status){
                 case UVS_VANGER_STATUS::ESCAVE_SLEEPING:
                     break;
                 case UVS_VANGER_STATUS::SPOT_SLEEPING:
                     break;
                 case UVS_VANGER_STATUS::MOVEMENT:
                 case UVS_VANGER_STATUS::FREE_MOVEMENT:
                 case UVS_VANGER_STATUS::RACE:
                 case UVS_VANGER_STATUS::RACE_HUNTER:
                 case UVS_VANGER_STATUS::GATHERING:
                 case UVS_VANGER_STATUS::WAIT_GAMER:
 //                  if (UVS_VANGER_STATUS::FREE_MOVEMENT == status ) break;
                     if (UVS_VANGER_STATUS::FREE_MOVEMENT == status && RND(3)) break;
                     emuStep();
                     emuCheck();
                     break;
                 }
             break;
         case UVS_VANGER_SHAPE::GAMER:
         case UVS_VANGER_SHAPE::GAMER_SLAVE:
             break;
         }
 }
References UVS_VANGER_SHAPE::BUNCH_SLAVE, UVS_VANGER_SHAPE::CARAVAN, CurrentWorld, UVS_VANGER_STATUS::ESCAVE_SLEEPING, UVS_VANGER_STATUS::FREE_MOVEMENT, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, UVS_VANGER_STATUS::GATHERING, UVS_VANGER_SHAPE::KILLER, UVS_VANGER_STATUS::MOVEMENT, uvsEscave::Pworld, UVS_VANGER_STATUS::RACE, UVS_VANGER_STATUS::RACE_HUNTER, UVS_VANGER_SHAPE::RANGER, RND(), UVS_VANGER_STATUS::SPOT_SLEEPING, UVS_VANGER_SHAPE::TABUTASK, UVS_VANGER_SHAPE::THIEF, uvsKronActive, and UVS_VANGER_STATUS::WAIT_GAMER.
emuStep()
void uvsVanger::emuStep (void)
{
     uvsOrder* ord = orderT;
     if( !speed ) ErrH.Abort("emuStep dont have speed");
     if(ord -> Ptarget -> pos_y > pos_y){ pos_y += speed + RND(2); pos_x += RND(5) - 2; }
     else if(ord -> Ptarget -> pos_y < pos_y){ pos_y -= speed + RND(2); pos_x += RND(5) - 2; }
     else
         if(ord -> Ptarget -> pos_x > pos_x) pos_x++;
         else if(ord -> Ptarget -> pos_x < pos_x) pos_x--;
 }
References XErrorHandler::Abort(), ErrH, uvsTarget::pos_x, uvsTarget::pos_y, and RND().
Event()
void uvsVanger::Event (UvsEventType ev)
{
     switch(ev){
         case UVS_EVENT::THIEF:
             thief_from_escave(Pescave);
             break;
         case UVS_EVENT::THIEF_FROM_SHOP:
             thief_from_shop(Pescave -> Pshop);
             break;
         case UVS_EVENT::GO_FROM_ESCAVE:
             go_from_escave();
             break;
         case UVS_EVENT::GO_FROM_SPOT:
             go_from_spot();
             break;
         case UVS_EVENT::GO_CIRT:
             goCirt();
             break;
         case UVS_EVENT::GO_NEW_ESCAVE:
             if (shape == UVS_VANGER_SHAPE::GAMER)
                 status = UVS_VANGER_STATUS::GO_NEW_ESCAVE;
             else
                 goNewEscave();
             break;
         case UVS_EVENT::SPOT_ARRIVAL:
             spotArrival();
             if ( shape != UVS_VANGER_SHAPE::GAMER ){
                 status = UVS_VANGER_STATUS::SPOT_SLEEPING;
             }else {
                 status = UVS_VANGER_STATUS::SHOPPING;
                 locTimer = LOC_TIME;
             }
             break;
         case UVS_EVENT::ESCAVE_ARRIVAL:
             homeArrival();
             if ( shape != UVS_VANGER_SHAPE::GAMER ){
                 status = UVS_VANGER_STATUS::ESCAVE_SLEEPING;
             } else {
                 status = UVS_VANGER_STATUS::SHOPPING;
                 locTimer = LOC_TIME;
             }
             break;
         case UVS_EVENT::PASSAGE_ARRIVAL:
             status = UVS_VANGER_STATUS::PASSAGE_GAP;
             if ( shape != UVS_VANGER_SHAPE::GAMER ){
                 shiftOrders();
             }
             locTimer = shape == UVS_VANGER_SHAPE::GAMER ? 1 : V_PGAP_TIME;
             break;
         case UVS_EVENT::AIM_ARRIVAL:
             aimHandle();
             break;
         case UVS_EVENT::FATALITY:
             destroy();
             break;
         case UVS_EVENT::GO_NEW_WORLD:
             status = UVS_VANGER_STATUS::GO_NEW_WORLD;
         break;
         };
 }
References UVS_EVENT::AIM_ARRIVAL, UVS_EVENT::ESCAVE_ARRIVAL, UVS_VANGER_STATUS::ESCAVE_SLEEPING, UVS_EVENT::FATALITY, UVS_VANGER_SHAPE::GAMER, UVS_EVENT::GO_CIRT, UVS_EVENT::GO_FROM_ESCAVE, UVS_EVENT::GO_FROM_SPOT, UVS_VANGER_STATUS::GO_NEW_ESCAVE, UVS_EVENT::GO_NEW_ESCAVE, UVS_VANGER_STATUS::GO_NEW_WORLD, UVS_EVENT::GO_NEW_WORLD, LOC_TIME, UVS_EVENT::PASSAGE_ARRIVAL, UVS_VANGER_STATUS::PASSAGE_GAP, uvsEscave::Pshop, UVS_VANGER_STATUS::SHOPPING, UVS_EVENT::SPOT_ARRIVAL, UVS_VANGER_STATUS::SPOT_SLEEPING, UVS_EVENT::THIEF, UVS_EVENT::THIEF_FROM_SHOP, and V_PGAP_TIME.
game_result()
int uvsVanger::game_result (const char * name)
{
     if (!Pworld -> escTmax) return 0;
     uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
     uvsCultGame* pg = pb -> cycleTable[pb -> currentStage].Pgame;
     if ( !pg ) return 0;
     switch( pg -> GameType ){
     case UVS_GAME_TYPE::RACE:
         return race_result(pg, name);
         break;
     case UVS_GAME_TYPE::HARVEST:
         return harvest_result(pg, name);
         break;
     }
     return 0;
 }
References UVS_GAME_TYPE::HARVEST, harvest_result(), Pworld, UVS_GAME_TYPE::RACE, and race_result().
gatherCirt() [1/2]
void uvsVanger::gatherCirt (int x, int y, int & p1, int & p2)
{
     listElem* pe = DollyTail;
 #ifdef STAND_REPORT
     stand < "Gamer gather \n";
 #endif
     p1 = p2 = 0;
     while( pe ){
         if ( (( uvsDolly*)pe) -> Pworld -> gIndex == CurrentWorld ){
             p1 |= (( uvsDolly*)pe) -> getCirt(x, y);
             p2 |= 1 << ((( uvsDolly*)pe) -> gIndex);
         }
         pe = pe -> next;
     }//  end while
     p1 |= 1<<31;
 #ifdef STAND_REPORT
     stand < "Gamer gather end\n";
 #endif
 }
References CurrentWorld, DollyTail, listElem::next, and uvsEscave::Pworld.
gatherCirt() [2/2]
void uvsVanger::gatherCirt (uvsDolly * dolly)
{
     uvsItem* pi = GetItem(Pitem, UVS_ITEM_TYPE::CIRTAINER, 1);
     if( !pi ) return;
     pi -> param1 = dolly -> getCirt(pos_x, pos_y) | (1<<31);
     pi -> param2 = 1 << (dolly -> gIndex);
 }
References UVS_ITEM_TYPE::CIRTAINER, GetItem(), uvsEscave::Pitem, uvsTarget::pos_x, and uvsTarget::pos_y.
Referenced by aciSendEvent2itmdsp().
get_list_from_ActInt()
void uvsVanger::get_list_from_ActInt (uvsActInt *& Item, uvsActInt *& Mechos)
{
     uvsActInt* pa;
     uvsItem* pi;
     int _tabu_taskID_;
     int _tabu_taskCOUNT_;
     if (Pescave){
         _tabu_taskID_ = Pescave -> TabuTaskID;
         _tabu_taskCOUNT_ = Pescave -> TabuTaskCount;
     } else {
         _tabu_taskID_ = Pspot -> TabuTaskID;
         _tabu_taskCOUNT_ = Pspot -> TabuTaskCount;
     }
     //Pitem = NULL;
     pa = Item;
     while(pa){
         Item = (uvsActInt*)Item -> next;
         (pi = new uvsItem(ActInt_to_Item(pa -> type))) -> link(Pitem);
         uvsDomChangeFromItem(pi -> type, 1, 0);
         pi -> param1 = pa -> param1;
         pi -> param2 = pa -> param2;
         pi -> pos_x = pa -> pos_x;
         pi -> pos_y = pa -> pos_y;
 //      if ( (pi -> type == UVS_ITEM_TYPE::TABUTASK) && ((pi -> param2 & 0xFFFF0000)  == 0)){
 //          TabuTable[pi -> param2 ] -> activate();
 //      }
         delete (uvsActInt*)pa;
         pa = Item;
     }
     Item = NULL;
     if ( Mechos ){
         int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
         if (Mechos -> type >= first_constr ){
             int _type = Mechos -> type - first_constr;
             Mechos -> type =  first_constr + (_type>>2);
             _type &= 3;
             Pmechos = new uvsMechos(Mechos -> type);
             uvsMechosTable[Mechos -> type] -> constractor = _type;
         } else {
             Pmechos = new uvsMechos(Mechos -> type);
         }
         if (strcmp(uvsMechosTable[Pmechos -> type] -> name, "LawnMower"))
             SetMotorFile(uvsMechosTable[Pmechos -> type] -> type);
         else
             SetMotorFile(6);
 #ifndef _DEMO_
         Pmechos -> color = Mechos -> param1;
 #else
         Pmechos -> color = CAR_COLOR[Mechos -> type];
 #endif
         Pmechos -> teleport = Mechos -> param2;
         delete Mechos;
     }
     Mechos = NULL;
 //  uvsCheckItemOnTabuTask(Pitem, _tabu_taskID_, _tabu_taskCOUNT_, 0);
     pi = (uvsItem*)Pitem;
     uvsTabuTaskFlag = 0;
     while(pi){
         if ( (pi -> type == UVS_ITEM_TYPE::TABUTASK) && ((pi -> param2 & 0xFFFF0000)  == 0)){
             if (!TabuTable[pi -> param2 ] -> status){
                 uvsTabuTaskX = pi -> pos_x;
                 uvsTabuTaskY = pi -> pos_y;
                 uvsTabuTaskFlag = 1;
             }
             TabuTable[pi -> param2 ] -> activate();
         }
         pi = (uvsItem*)pi -> next;
     }
     pa = GTreasureItem;
     while( pa ){
         uvsActInt* pl = pa;
         pa = (uvsActInt*)pa -> next;
         if (pl -> type == ACI_RUBOX){
             GamerResult.rubbox_count--;
             pl -> delink(GTreasureItem);
             delete pl;
         }
     }//  end while
     if(GTreasureItem){
         if (Pescave){
             ((uvsItem*)Pescave -> Pitem) -> param1 = 0;
         } else {
             ((uvsItem*)Pspot -> Pitem) -> param1 = 0;
         }
         delete (uvsActInt*)GTreasureItem;
         GTreasureItem = NULL;
     } else {
         if (Pescave){
             if ( ((uvsItem*)Pescave -> Pitem) && (((uvsItem*)Pescave -> Pitem) -> param1 == uvsTreasureInShop)){
                 Pworld -> escT[0] -> Pbunch -> status |= (int)UVS_BUNCH_STATUS::KILL_GAMER;
                 ShowDominanceMessage(-15);
                 GamerResult.dominance -= 15;
                 if (GamerResult.dominance < 0) GamerResult.dominance = 0;
                 ((uvsItem*)Pescave -> Pitem) -> param1 = uvsTreasureInGamer;
             }
         } else {
             if ( ((uvsItem*)Pspot -> Pitem) && (((uvsItem*)Pspot -> Pitem) -> param1 == uvsTreasureInShop)){
                 Pworld -> escT[0] -> Pbunch -> status |= (int)UVS_BUNCH_STATUS::KILL_GAMER;
                 ShowDominanceMessage(-15);
                 GamerResult.dominance -= 15;
                 if (GamerResult.dominance < 0) GamerResult.dominance = 0;
                 ((uvsItem*)Pspot -> Pitem) -> param1 = uvsTreasureInGamer;
             }
         }
     }
 }
References Pescave, and Pspot.
get_shop()
void uvsVanger::get_shop (int how)
{
     int count;
     int UnicumON = 0;
     listElem* pt;
     uvsItem *pi = NULL;
         if ( Pescave ){
             Pescave -> Pshop ->  get_list_from_ActInt( GMechos, GItem);
             Pescave -> Pshop -> locked = 0;
             pt = Pescave -> Pgood;
             Pescave ->  lastTabuTaskGood = Pescave -> TabuTaskGood;
             if (NetworkON && my_server_data.GameType == MUSTODONT){
                 UnicumON = Pescave -> Pshop ->FindMechos(uvsUnikumeMechos);
             }
             pi = GetItem(Pescave -> Pshop -> Pitem, ((uvsItem*)Pescave -> Pitem) -> type, 0 );
             if (pi){
                 pi -> delink(Pescave -> Pshop -> Pitem);
                 delete pi;
                 ((uvsItem*)Pescave -> Pitem) -> param1 = 0;
             }
             pi = GetItem(Pescave -> Pshop -> Pitem, UVS_ITEM_TYPE::BOORAWCHICK, 0 );
             if (pi){
                 pi -> delink(Pescave -> Pshop -> Pitem);
 #ifdef STAND_REPORT
 stand < ConTimer.GetTime() < "BOORAWCHICK go home\n";
 #endif
                 delete pi;
                 ((uvsItem*)WorldTable[1] -> escT[0] -> Pitem) ->param1 = uvsTreasureInWait;
             }
         } else if (Pspot -> Pshop){
             Pspot -> Pshop ->  get_list_from_ActInt( GMechos, GItem);
             Pspot -> Pshop -> locked = 0;
             pt = Pspot -> Pgood;
             Pspot ->  lastTabuTaskGood = Pspot -> TabuTaskGood;
             if (NetworkON && my_server_data.GameType == MUSTODONT){
                 UnicumON = Pspot -> Pshop ->FindMechos(uvsUnikumeMechos);
             }
             pi = GetItem(Pspot -> Pshop -> Pitem, ((uvsItem*)Pspot -> Pitem) -> type, 0 );
             if (pi){
                 pi -> delink(Pspot -> Pshop -> Pitem);
                 delete pi;
                 ((uvsItem*)Pspot -> Pitem) -> param1 = 0;
             }
             pi = GetItem(Pspot -> Pshop -> Pitem, UVS_ITEM_TYPE::BOORAWCHICK, 0 );
             if (pi){
                 pi -> delink(Pspot -> Pshop -> Pitem);
                 delete pi;
 #ifdef STAND_REPORT
 stand < ConTimer.GetTime() < "BOORAWCHICK go home\n";
 #endif
                 ((uvsItem*)WorldTable[1] -> escT[0] -> Pitem) ->param1 = uvsTreasureInWait;
             }
         }
          get_list_from_ActInt(GGamer, GGamerMechos);
         count = GamerResult.nymbos - ItemCount(Pitem,UVS_ITEM_TYPE::NYMBOS );
         GamerResult.nymbos = ItemCount(Pitem,UVS_ITEM_TYPE::NYMBOS );
         if (count > 0){
             uvsTradeItem* pl = (uvsTradeItem*)pt;
             while(pl){
                 if (pl -> type == UVS_ITEM_TYPE::NYMBOS){
                     GamerResult.nymbos_total += count;
                     if (GamerResult.nymbos_total >= GamerResult.nymbos_bonus*20) GamerResult.nymbos_bonus++;
                     break;
                 }
                 pl = (uvsTradeItem*)pl -> next;
             }//  end while
             if (NetworkON && my_server_data.GameType == MECHOSOMA){
                 my_player_body.MechosomaStat.ItemCount1 += count;
                 send_player_body(my_player_body);
             }
         }
         count = GamerResult.phlegma - ItemCount(Pitem, UVS_ITEM_TYPE::PHLEGMA);
         GamerResult.phlegma = ItemCount(Pitem, UVS_ITEM_TYPE::PHLEGMA);
         if (count > 0){
             uvsTradeItem* pl = (uvsTradeItem*)pt;
             while(pl){
                 if (pl -> type == UVS_ITEM_TYPE::PHLEGMA){
                     GamerResult.phlegma_total += count;
                     if (GamerResult.phlegma_total >= GamerResult.phlegma_bonus*20) GamerResult.phlegma_bonus++;
                     break;
                 }
                 pl = (uvsTradeItem*)pl -> next;
             }//  end while
             if (NetworkON && my_server_data.GameType == MECHOSOMA){
                 my_player_body.MechosomaStat.ItemCount2 += count;
                 send_player_body(my_player_body);
             }
         }
         //stalkerg Где то тут
         count = GamerResult.heroin - ItemCount(Pitem,UVS_ITEM_TYPE::HEROIN );
         GamerResult.heroin = ItemCount(Pitem,UVS_ITEM_TYPE::HEROIN );
         if (count > 0){
             uvsTradeItem* pl = (uvsTradeItem*)pt;
             while(pl){
                 if (pl -> type == UVS_ITEM_TYPE::HEROIN){
                     GamerResult.heroin_total += count;
                     if (GamerResult.heroin_total >= GamerResult.heroin_bonus*20) GamerResult.heroin_bonus++;
                     break;
                 }
                 pl = (uvsTradeItem*)pl -> next;
             }//  end while
             if (NetworkON && my_server_data.GameType == MECHOSOMA){
                 my_player_body.MechosomaStat.ItemCount1 += count;
                 send_player_body(my_player_body);
             }
         }
         count = GamerResult.shrub - ItemCount(Pitem,UVS_ITEM_TYPE::SHRUB );
         GamerResult.shrub = ItemCount(Pitem,UVS_ITEM_TYPE::SHRUB );
         if (count > 0){
             uvsTradeItem* pl = (uvsTradeItem*)pt;
             while(pl){
                 if (pl -> type == UVS_ITEM_TYPE::SHRUB){
                     GamerResult.shrub_total += count;
                     if (GamerResult.shrub_total >= GamerResult.shrub_bonus*20) GamerResult.shrub_bonus++;
                     break;
                 }
                 pl = (uvsTradeItem*)pl -> next;
             }//  end while
             if (NetworkON && my_server_data.GameType == MECHOSOMA){
                 my_player_body.MechosomaStat.ItemCount2 += count;
                 send_player_body(my_player_body);
             }
         }
         count = GamerResult.poponka - ItemCount(Pitem,UVS_ITEM_TYPE::POPONKA );
         GamerResult.poponka = ItemCount(Pitem,UVS_ITEM_TYPE::POPONKA );
         if (count > 0){
             uvsTradeItem* pl = (uvsTradeItem*)pt;
             while(pl){
                 if (pl -> type == UVS_ITEM_TYPE::POPONKA){
                     GamerResult.poponka_total += count;
                     if (GamerResult.poponka_total >= GamerResult.poponka_bonus*20) GamerResult.poponka_bonus++;
                     break;
                 }
                 pl = (uvsTradeItem*)pl -> next;
             }//  end while
             if (NetworkON && my_server_data.GameType == MECHOSOMA){
                 my_player_body.MechosomaStat.ItemCount1 += count;
                 send_player_body(my_player_body);
             }
         }
         count = GamerResult.toxick - ItemCount(Pitem,UVS_ITEM_TYPE::TOXICK );
         GamerResult.toxick = ItemCount(Pitem,UVS_ITEM_TYPE::TOXICK );
         if (count > 0){
             uvsTradeItem* pl = (uvsTradeItem*)pt;
             while(pl){
                 if (pl -> type == UVS_ITEM_TYPE::TOXICK){
                     GamerResult.toxick_total += count;
                     if (GamerResult.toxick_total >= GamerResult.toxick_bonus*20) GamerResult.toxick_bonus++;
                     break;
                 }
                 pl = (uvsTradeItem*)pl -> next;
             }//  end while
             if (NetworkON && my_server_data.GameType == MECHOSOMA){
                 my_player_body.MechosomaStat.ItemCount2 += count;
                 send_player_body(my_player_body);
             }
         }
         if (NetworkON && my_server_data.GameType == MECHOSOMA){
             if (my_player_body.MechosomaStat.ItemCount2 >= my_server_data.Mechosoma.ProductQuantity2
              && my_player_body.MechosomaStat.ItemCount1 >= my_server_data.Mechosoma.ProductQuantity1){
                 time_t _t_;
                 time(&_t_);
                 my_player_body.MechosomaStat.MaxTransitTime = _t_ - uvsFirstTime;
                 GameOverID = GAME_OVER_NETWORK;
                 GameQuantReturnValue = RTO_LOADING3_ID;
                 send_player_body(my_player_body);
             }
         }
         if (NetworkON && my_server_data.GameType == MUSTODONT){
             if (UnicumON && !my_player_body.MustodontStat.BodyTime){
                 time_t _t_;
                 time(&_t_);
                 my_player_body.MustodontStat.BodyTime = _t_ - uvsFirstTime;
             }
             if (uvsMechosTable[uvsUnikumeMechos] -> constractor && !my_player_body.MustodontStat.PartTime1){
                 time_t _t_;
                 time(&_t_);
                 my_player_body.MustodontStat.PartTime1 = _t_ - uvsFirstTime;
             }
             if ((uvsMechosTable[uvsUnikumeMechos] -> constractor == 3) && !my_player_body.MustodontStat.PartTime2){
                 time_t _t_;
                 time(&_t_);
                 my_player_body.MustodontStat.PartTime2 = _t_ - uvsFirstTime;
                 my_player_body.MustodontStat.MakeTime = _t_ - uvsFirstTime;
             }
         }
         if (!GamerResult.leepuringa) {
             GamerResult.leepuringa = ItemCount(Pitem, UVS_ITEM_TYPE::LEEPURINGA);
             if (GamerResult.leepuringa){
                 GamerResult.add_luck += 50;
                 ShowLuckMessage(50);
             }
         } else {
             GamerResult.leepuringa = ItemCount(Pitem, UVS_ITEM_TYPE::LEEPURINGA);
             if (!GamerResult.leepuringa){
                 GamerResult.add_luck -= 50;
                 ShowLuckMessage(-50);
             }
         }
         if (!GamerResult.mechanic_messiah) {
             GamerResult.mechanic_messiah = ItemCount(Pitem, UVS_ITEM_TYPE::MECHANIC_MESSIAH);
             if (GamerResult.mechanic_messiah){
                 GamerResult.add_dominance += 20;
                 ShowDominanceMessage(20);
             }
         } else {
             GamerResult.mechanic_messiah = ItemCount(Pitem, UVS_ITEM_TYPE::MECHANIC_MESSIAH);
             if (!GamerResult.mechanic_messiah){
                 GamerResult.add_dominance -= 20;
                 ShowDominanceMessage(-20);
             }
         }
         if (!GamerResult.protractor) {
             GamerResult.protractor = ItemCount(Pitem, UVS_ITEM_TYPE::PROTRACTOR);
             if (GamerResult.protractor){
                 GamerResult.add_luck += 20;
                 ShowLuckMessage(20);
             }
         } else {
             GamerResult.protractor = ItemCount(Pitem, UVS_ITEM_TYPE::PROTRACTOR);
             if (!GamerResult.protractor){
                 GamerResult.add_luck -= 20;
                 ShowLuckMessage(-20);
             }
         }
         if (!GamerResult.boorawchick) {
             GamerResult.boorawchick = ItemCount(Pitem, UVS_ITEM_TYPE::BOORAWCHICK);
             if (GamerResult.boorawchick){
                 GamerResult.add_dominance += 50;
                 ShowDominanceMessage(50);
             }
         } else {
             GamerResult.boorawchick = ItemCount(Pitem, UVS_ITEM_TYPE::BOORAWCHICK);
             if (!GamerResult.boorawchick){
                 GamerResult.add_dominance -= 50;
                 ShowDominanceMessage(-50);
             }
         }
 /*      if (GamerResult.luck > 100) GamerResult.luck = 100;
         if (GamerResult.luck < 0) GamerResult.luck = 0;
         if (GamerResult.dominance < -100) GamerResult.dominance = -100;
         if (GamerResult.dominance > 100) GamerResult.dominance = 100;
 */
         GamerResult.LocalInit();
         GamerResult.get_eleech = ItemCount(Pitem,UVS_ITEM_TYPE::ELEECH );
         GamerResult.get_weezyk = ItemCount(Pitem,UVS_ITEM_TYPE::WEEZYK );
         start_race();
         if (  lastMechos != Pmechos -> type ) {
             if (!uvsMechosTable[Pmechos -> type] -> gamer_use){
                 GamerResult.mechos_variant++;
                 if (uvsMechosTable[Pmechos -> type] -> constractor){
                     ShowDominanceMessage(9);
                     GamerResult.dominance += 9;
                 } else {
                     GamerResult.dominance += 5;
                     ShowDominanceMessage(5);
                 }
                 if (GamerResult.dominance > 100) GamerResult.dominance = 100;
             }
             ChangeArmor = -1;
 //          ChangeArmor = uvsMechosTable[Pmechos -> type] -> MaxArmor;
             uvsMechosTable[Pmechos -> type] -> gamer_use++;
 #ifndef _DEMO_
             Pmechos -> color = Pworld -> escT[0] -> Pbunch -> biosNindex;
 #else
             Pmechos -> color = CAR_COLOR[Pmechos -> type];
 #endif
         }
 #ifdef STAND_REPORT
         stand < ConTimer.GetTime() < " GAMER leave " < aci_curLocationName < "\n";
 #endif
         if (uvsTownName){
             status = UVS_VANGER_STATUS::SHOPPING;
             locTimer = 1;
             uvsEscave* pe = (uvsEscave*)EscaveTail -> seekName(uvsTownName);
             if ( !pe )  {
                 uvsSpot* ps = (uvsSpot*)SpotTail -> seekName(uvsTownName);
                 if ( !ps ) ErrH.Abort("uvsTownName wrong ",XERR_USER,-1,uvsTownName);
                 Pspot = ps;
                 Pescave = NULL;
             } else {
                 Pescave = pe;
                 Pspot = NULL;
             }
         } else
             status = UVS_VANGER_STATUS::MOVEMENT;
         if (WorldTable[CurrentWorld] -> escTmax)
             aci_curLocationName = WorldTable[CurrentWorld] -> escT[0] -> name;
         else
             aci_curLocationName = "";
 }
References XErrorHandler::Abort(), aci_curLocationName, uvsGamerResult::add_dominance, uvsGamerResult::add_luck, MustodontStatistic::BodyTime, UVS_ITEM_TYPE::BOORAWCHICK, uvsGamerResult::boorawchick, ChangeArmor, ConTimer, CurrentWorld, uvsGamerResult::dominance, UVS_ITEM_TYPE::ELEECH, ErrH, EscaveTail, uvsShop::FindMechos(), GAME_OVER_NETWORK, GameOverID, GameQuantReturnValue, GamerResult, ServerData::GameType, uvsGamerResult::get_eleech, uvsGamerResult::get_weezyk, GetItem(), uvsContimer::GetTime(), GGamer, GGamerMechos, GItem, GMechos, UVS_ITEM_TYPE::HEROIN, uvsGamerResult::heroin, uvsGamerResult::heroin_bonus, uvsGamerResult::heroin_total, ItemCount(), MechosomaStatistic::ItemCount1, MechosomaStatistic::ItemCount2, lastMechos, uvsEscave::lastTabuTaskGood, UVS_ITEM_TYPE::LEEPURINGA, uvsGamerResult::leepuringa, uvsGamerResult::LocalInit(), uvsEscave::locked, MustodontStatistic::MakeTime, MechosomaStatistic::MaxTransitTime, UVS_ITEM_TYPE::MECHANIC_MESSIAH, uvsGamerResult::mechanic_messiah, uvsGamerResult::mechos_variant, MECHOSOMA, ServerData::Mechosoma, PlayerBody::MechosomaStat, UVS_VANGER_STATUS::MOVEMENT, MUSTODONT, PlayerBody::MustodontStat, my_player_body, my_server_data, uvsEscave::name, NetworkON, listElem::next, NULL, UVS_ITEM_TYPE::NYMBOS, uvsGamerResult::nymbos, uvsGamerResult::nymbos_bonus, uvsGamerResult::nymbos_total, uvsItem::param1, MustodontStatistic::PartTime1, MustodontStatistic::PartTime2, uvsEscave::Pbunch, uvsEscave::Pgood, UVS_ITEM_TYPE::PHLEGMA, uvsGamerResult::phlegma, uvsGamerResult::phlegma_bonus, uvsGamerResult::phlegma_total, uvsEscave::Pitem, UVS_ITEM_TYPE::POPONKA, uvsGamerResult::poponka, uvsGamerResult::poponka_bonus, uvsGamerResult::poponka_total, MECHOSOMA_PRM::ProductQuantity1, MECHOSOMA_PRM::ProductQuantity2, UVS_ITEM_TYPE::PROTRACTOR, uvsGamerResult::protractor, uvsEscave::Pshop, uvsEscave::Pworld, RTO_LOADING3_ID, listElem::seekName(), send_player_body(), UVS_VANGER_STATUS::SHOPPING, ShowDominanceMessage(), ShowLuckMessage(), UVS_ITEM_TYPE::SHRUB, uvsGamerResult::shrub, uvsGamerResult::shrub_bonus, uvsGamerResult::shrub_total, SpotTail, uvsEscave::TabuTaskGood, UVS_ITEM_TYPE::TOXICK, uvsGamerResult::toxick, uvsGamerResult::toxick_bonus, uvsGamerResult::toxick_total, uvsFirstTime, uvsMechosTable, uvsTownName, uvsTreasureInWait, uvsUnikumeMechos, UVS_ITEM_TYPE::WEEZYK, WorldTable, and XERR_USER.
go_from_escave()
void uvsVanger::go_from_escave (void)
{
     uvsItem* pi;
     uvsSpot *ps = NULL;
     char *name = NULL;
     addInventory();
     int n = RND(Pescave -> TradeCount);
     if ( Pescave -> TradeCount > 0 ){
         listElem *pl = Pescave -> Ptrade;
         for( int i = 0; i < n; i++) pl = pl -> next;
         if ( shape != UVS_VANGER_SHAPE::THIEF ){
             pi = new uvsItem( ((uvsTradeItem*)pl) -> type );
             if (pi -> type == UVS_ITEM_TYPE::POPONKA){
                 pi -> param2 = RND(DG_POPONKA_MAX);
                 while(pi -> param2 == uvsPoponkaID)
                     pi -> param2 = RND(DG_POPONKA_MAX);
             }
             addItem( pi, 1 );
             pi -> param1 = Pworld -> gIndex<<16;
         }
         name = ((uvsTradeItem*)pl) -> town_name;
     }
     uvsEscave* pe;
     if ( name == NULL ){
         ps = Pworld -> getRandSpot();
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_SPOT;
         ord -> target = UVS_TARGET::SPOT;
         ord -> Ptarget = (uvsTarget*)ps;
         Pspot = ps;
     } else  if (( ps = (uvsSpot*)SpotTail -> seekName(name) )){
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_SPOT;
         ord -> target = UVS_TARGET::SPOT;
         ord -> Ptarget = (uvsTarget*)ps;
         Pspot = ps;
     } else if (( pe = (uvsEscave*)EscaveTail -> seekName(name) )){
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_ESCAVE;
         ord -> target = UVS_TARGET::ESCAVE;
         ord -> Ptarget = (uvsTarget*)pe;
     } else ErrH.Abort("uvsVanger::go_from_escave - go nothing");
     status = UVS_VANGER_STATUS::MOVEMENT;
 }
References XErrorHandler::Abort(), DG_POPONKA_MAX, ErrH, UVS_TARGET::ESCAVE, EscaveTail, UVS_EVENT::GO_ESCAVE, UVS_EVENT::GO_SPOT, UVS_VANGER_STATUS::MOVEMENT, UVS_ORDER::MOVING, uvsEscave::name, listElem::next, NULL, UVS_ITEM_TYPE::POPONKA, uvsEscave::Ptrade, uvsEscave::Pworld, RND(), listElem::seekName(), UVS_TARGET::SPOT, SpotTail, UVS_VANGER_SHAPE::THIEF, uvsEscave::TradeCount, and uvsPoponkaID.
go_from_spot()
void uvsVanger::go_from_spot (void)
{
     int i, n;
     uvsItem* pi;
     char* name = NULL;
     addInventory();
     n = RND(Pspot -> TradeCount);
     if ( Pspot -> TradeCount > 0 ){
         listElem *pl = Pspot -> Ptrade;
         for( i = 0; i < n; i++) pl = pl -> next;
         if ( shape != UVS_VANGER_SHAPE::THIEF ){
             pi = new uvsItem( ((uvsTradeItem*)pl) -> type );
             if (pi -> type == UVS_ITEM_TYPE::POPONKA){
                 pi -> param2 = RND(DG_POPONKA_MAX);
                 while(pi -> param2 == uvsPoponkaID)
                     pi -> param2 = RND(DG_POPONKA_MAX);
             }
             pi -> param1 = Pworld -> gIndex<<16;
             addItem( pi, 1 );
         }
         name = ((uvsTradeItem*)pl) -> town_name;
     }
     uvsSpot* ps;
     uvsEscave* pe;
     if ( name == NULL ){
         pe = Pworld -> escT[0];
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_ESCAVE;
         ord -> target = UVS_TARGET::ESCAVE;
         ord -> Ptarget = (uvsTarget*)pe;
         Pescave = pe;
     } else  if (( ps = (uvsSpot*)SpotTail -> seekName(name) )){
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_SPOT;
         ord -> target = UVS_TARGET::SPOT;
         ord -> Ptarget = (uvsTarget*)ps;
     } else if (( pe = (uvsEscave*)EscaveTail -> seekName(name) )){
         uvsOrder* ord = orderT;         // первый элемент
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_ESCAVE;
         ord -> target = UVS_TARGET::ESCAVE;
         ord -> Ptarget = (uvsTarget*)pe;
         Pescave = pe;
     } else ErrH.Abort("uvsVanger::go_from_spot - go nothing");
     status = UVS_VANGER_STATUS::MOVEMENT;
 }
References XErrorHandler::Abort(), DG_POPONKA_MAX, ErrH, UVS_TARGET::ESCAVE, EscaveTail, UVS_EVENT::GO_ESCAVE, UVS_EVENT::GO_SPOT, UVS_VANGER_STATUS::MOVEMENT, UVS_ORDER::MOVING, uvsEscave::name, listElem::next, NULL, UVS_ITEM_TYPE::POPONKA, uvsEscave::Ptrade, uvsEscave::Pworld, RND(), listElem::seekName(), UVS_TARGET::SPOT, SpotTail, UVS_VANGER_SHAPE::THIEF, uvsEscave::TradeCount, and uvsPoponkaID.
go_to_GAMER()
void uvsVanger::go_to_GAMER (void)
{
     shape = UVS_VANGER_SHAPE::KILLER;
     if ( Pworld == Gamer -> Pworld ){
         uvsOrder* ord;
         ord = orderT;
         ord -> type = UVS_ORDER::MOVING;
         ord -> event = UVS_EVENT::GO_KILL;
         ord -> target = UVS_TARGET::VANGER;
         ord -> Ptarget = (uvsTarget*)(Gamer);
         status = UVS_VANGER_STATUS::MOVEMENT;
     } else {
         uvsWorld* fromW = Pworld;
         uvsWorld* toW = Gamer -> Pworld;
         int offset;
         uvsOrder* ord;
         if ( toW -> gIndex < MAIN_WORLD_MAX ){
             offset = buildWay(fromW,toW);
             ord = orderT + offset;
             ord -> type = UVS_ORDER::MOVING;
             ord -> event = UVS_EVENT::GO_KILL;
             ord -> target = UVS_TARGET::VANGER;
             ord -> Ptarget = (uvsTarget*)(Gamer);
             status = UVS_VANGER_STATUS::MOVEMENT;
         } else {
             ord = orderT;
             ord -> type = UVS_ORDER::MOVING;
             ord -> event = UVS_EVENT::GO_KILL;
             ord -> target = UVS_TARGET::VANGER;
             ord -> Ptarget = (uvsTarget*)(Gamer);
             status = UVS_VANGER_STATUS::WAIT_GAMER;
         }
         //if ( !toW -> escT[0] )
         //  ErrH.Abort("");
     }
 }
References Gamer, UVS_EVENT::GO_KILL, UVS_VANGER_SHAPE::KILLER, UVS_VANGER_STATUS::MOVEMENT, UVS_ORDER::MOVING, uvsEscave::Pworld, and UVS_TARGET::VANGER.
goCirt()
void uvsVanger::goCirt (void)
{
     uvsItem* pi;
     uvsDolly* pdl = owner -> cycleTable[owner -> currentStage].Pdolly;
     if ( !(Pmechos -> status & UVS_MECHOS_USED::HARVEST) ) return;
     if ( pdl -> Pworld -> gIndex > 3 ) return;
     addInventory();
     if (pdl -> status == UVS_DOLLY_STATUS::CATCH){
         if (!RND(10) && uvsKillerNow() < 2)
             go_to_GAMER();
         else return;
     } else {
         pi = new uvsItem(UVS_ITEM_TYPE::CIRTAINER);
         if (!addItem(pi, 0)) {
             delete pi;
             return;
         }
         uvsWorld* fromW = Pworld;
         uvsWorld* toW = pdl -> Pworld;
         int offset;
         uvsOrder* ord;
         offset = buildWay(fromW,toW);
         ord = orderT + offset;
         ord -> type = UVS_ORDER::CIRT_GATHERING;
         ord -> event = UVS_EVENT::GO_CIRT;
         ord -> target = UVS_TARGET::DOLLY;
         ord -> Ptarget = (uvsTarget*)pdl;
         status = UVS_VANGER_STATUS::MOVEMENT;
     }
     //cirtStage = owner -> currentStage;
 }
References UVS_DOLLY_STATUS::CATCH, UVS_ITEM_TYPE::CIRTAINER, UVS_MECHOS_USED::HARVEST, uvsEscave::Pworld, RND(), and uvsKillerNow().
goDolly()
void uvsVanger::goDolly (void)
goHome()
void uvsVanger::goHome (void)
{
     uvsWorld* fromW = Pworld;
     uvsWorld* toW = owner -> Pescave -> Pworld;
     uvsOrder* ord;
     int offset;
     offset = buildWay(fromW, toW);
     ord = orderT + offset;
     ord -> type = UVS_ORDER::MOVING;
     ord -> event = UVS_EVENT::GO_ESCAVE;
     ord -> target = UVS_TARGET::ESCAVE;
     ord -> Ptarget = (uvsTarget*)(owner -> Pescave);
     if ( !owner -> Pescave )
         ErrH.Abort("Error");
     status = UVS_VANGER_STATUS::MOVEMENT;
 }
References uvsEscave::Pworld.
Referenced by VangerUnit::ResolveHandlerFind().
goNewEscave()
void uvsVanger::goNewEscave (void)
{
     if ( shape != UVS_VANGER_SHAPE::THIEF && shape != UVS_VANGER_SHAPE::TABUTASK){
         if (!prepare_killer() && !RND(10))
             prepare_caravan();
     } else {
         addInventory();
     }
     if ( shape == UVS_VANGER_SHAPE::KILLER ) return;
     uvsWorld* fromW = Pworld;
     uvsWorld* toW;
     do{
         toW= getWorld(getRW(fromW -> gIndex));
     }while(!toW -> escTmax);
     int offset;
     uvsOrder* ord;
     offset = buildWay(fromW,toW);
     ord = orderT + offset;
     ord -> type = UVS_ORDER::MOVING;
     ord -> event = UVS_EVENT::GO_ESCAVE;
     ord -> target = UVS_TARGET::ESCAVE;
     ord -> Ptarget = (uvsTarget*)(toW -> escT[0]);
     if ( !toW -> escT[0] )
         ErrH.Abort("Error");
     status = UVS_VANGER_STATUS::MOVEMENT;
 }
References getRW(), getWorld(), UVS_VANGER_SHAPE::KILLER, uvsEscave::Pworld, RND(), UVS_VANGER_SHAPE::TABUTASK, and UVS_VANGER_SHAPE::THIEF.
GoodTabuTask()
int uvsVanger::GoodTabuTask (void)
{
     if (Pescave)
         return Pescave -> TabuTaskGood;
     else
         return Pspot -> TabuTaskGood;
 }
References uvsEscave::TabuTaskGood.
GoodWorldTabuTask()
int uvsVanger::GoodWorldTabuTask (void)
{
     int good = 0;
     int i;
     for (i = 0; i < Pworld -> escTmax; i++){
         good += Pworld -> escT[i] -> TabuTaskGood;
     }
     for (i = 0; i < Pworld -> sptTmax; i++){
         good += Pworld -> sptT[i] -> TabuTaskGood;
     }
     return good;
 }
References uvsEscave::Pworld, and uvsEscave::TabuTaskGood.
harvest_result()
int uvsVanger::harvest_result (uvsCultGame * pg, const char * name)
{
     uvsItem* pi;
     char* nn;
     int count = 0, GoodsType = -1;
     if ( (pg -> typeTownEnd == UVS_TOWN::ESCAVE && !strcmp( nn = ((uvsEscave*)(pg -> townEnd)) -> name, name))
         || ( pg -> typeTownEnd == UVS_TOWN::SPOT && !strcmp( nn = ((uvsSpot*)(pg -> townEnd)) -> name, name)) ){
         GoodsType = pg -> GoodsTypeBeg;
     }
     if ( GoodsType !=-1 ){
         count = ItemCount( Pitem, GoodsType, 1 );
         if (GoodsType == UVS_ITEM_TYPE::PIPETKA){
             count += 5*ItemCount( Pitem, UVS_ITEM_TYPE::PIPKA );
             GamerResult.last_game_type = UVS_GAME_ID::PIPETKA;
         }else if (GoodsType == UVS_ITEM_TYPE::KERNOBOO){
             count += 5*ItemCount( Pitem, UVS_ITEM_TYPE::NOBOOL );
             GamerResult.last_game_type = UVS_GAME_ID::KERNOBOO;
         }
         if (count){
 #ifdef STAND_REPORT
             stand < ConTimer.GetTime();
             stand < "\t in " < nn < " with " <= count < " corn  <- GAMER FINISH  \n";
 #endif
             pg -> result = pg -> total + 1;
         }
         pi = GetItem( Pitem, GoodsType, 0 );
         if ( pi ){
             uvsActInt* pa = GGamer;
             uvsActInt* pp;
             while( pa ){
                 pp = (uvsActInt*)pa -> next;
                 if (uvsItemTable[ pi -> type ] -> SteelerTypeFull == pa -> type){
                     pa -> delink(GGamer);
                     delete pa;
                 }
                 pa = pp;
             }
 //          pi = GetItem( Pitem, GoodsType, 0 );
 //          if (!pi) ErrH.Abort("uvsVanger::harvest_result :: bad Pitem");
             uvs_aciKillItem(uvsItemTable[ pi -> type ] -> SteelerTypeFull);
             while(pi){
                 ((uvsItem*)pi) -> delink( Pitem );
                 delete pi;
                 pi = GetItem( Pitem, GoodsType, 0 );
             }
         }// if count
         return ( count );
     }//  if GoodsType != -1
     return 0;
 }
References ConTimer, UVS_TOWN::ESCAVE, GamerResult, GetItem(), uvsContimer::GetTime(), GGamer, ItemCount(), UVS_GAME_ID::KERNOBOO, UVS_ITEM_TYPE::KERNOBOO, uvsGamerResult::last_game_type, UVS_ITEM_TYPE::NOBOOL, UVS_GAME_ID::PIPETKA, UVS_ITEM_TYPE::PIPETKA, UVS_ITEM_TYPE::PIPKA, Pitem, and UVS_TOWN::SPOT.
Referenced by game_result().
homeArrival()
void uvsVanger::homeArrival ()
{
     int tmp;
     uvsCheckVangerTabuTask(this,uvsVANGER_ARRIVAL);
     Pspot = NULL;
     switch(shape){
         case UVS_VANGER_SHAPE::TABUTASK:
             tmp = Pescave -> bring_game_GOODS(Pitem);
 #ifdef STAND_REPORT
             if (tmp){
                 stand < " race finish tabutask\n";
             }
 #endif
             Pescave->Pshop->updateList(Pitem);
             FreeList(Pitem);
             break;
         case UVS_VANGER_SHAPE::BUNCH_SLAVE:
             tmp = Pescave -> bring_game_GOODS(Pitem);
 #ifdef STAND_REPORT
             if (tmp){
                 stand < " race finish slave\n";
             }
 #endif
             //changeRating( Pescave -> bring_GOODS(Pitem) );
             changeRating( tmp );
             if(!emptyContainer(Pescave)) changeRating(V_CIRTDELIVERY_SCORE);
             else changeRating(V_LOCTRIP_SCORE);
             if (RND(2))
                 Pescave->Pshop->updateList(Pitem);
             FreeList(Pitem);
             break;
         case UVS_VANGER_SHAPE::CARAVAN:
             tmp = Pescave -> bring_game_GOODS(Pitem);
 #ifdef STAND_REPORT
             if (tmp){
                 stand < " race finish caravan\n";
             }
 #endif
             //changeRating( Pescave -> bring_GOODS(Pitem) );
             changeRating( tmp );
             if(!emptyContainer(Pescave)) changeRating(V_LONGTRIP_SCORE);
             if ( !RND(3) ){
                     sell_move_Item( Pescave -> Pshop, 0);
                 }
             break;
         case UVS_VANGER_SHAPE::RANGER:
             tmp = Pescave -> bring_game_GOODS(Pitem);
 #ifdef STAND_REPORT
             if (tmp){
                 stand < " race finish ranger\n";
             }
 #endif
             //changeRating( Pescave -> bring_GOODS(Pitem) );
             changeRating( tmp );
             if(!emptyContainer(Pescave)) changeRating(V_LONGTRIP_SCORE);
             Pescave->Pshop->updateList(Pitem);
             FreeList(Pitem);
             if( !RND(2)){
                 // становиться рабом
                 shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
                 owner = Pworld -> escT[0] -> Pbunch;
                 if (Pmechos)
                     Pmechos -> color = Pworld -> escT[0] -> Pbunch -> biosNindex;
                 }
             else
                 if( !RND(2)) Event(UVS_EVENT::FATALITY);
             break;
         case UVS_VANGER_SHAPE::THIEF:
             if ( !Pescave -> arrest( this) ){
                 tmp = Pescave -> bring_game_GOODS(Pitem);
 #ifdef STAND_REPORT
                 if (tmp){
                     stand < " race finish thief\n";
                 }
 #endif
                 //changeRating( Pescave -> bring_GOODS(Pitem) );
                 changeRating( tmp );
                 if(!emptyContainer(Pescave)) changeRating(V_LONGTRIP_SCORE);
                 if ( !RND(3) ){
                     sell_treasure_Item( Pescave -> Pshop);
                 }
             }
             break;
         case UVS_VANGER_SHAPE::GAMER:
 #ifdef _ROAD_
             status = UVS_VANGER_STATUS::SHOPPING;
             locTimer = LOC_TIME;
             if ( !Pescave -> GamerVisit ){
                 GamerResult.dominance += 2;
                 ShowDominanceMessage(2);
                 if (GamerResult.dominance > 100) GamerResult.dominance = 100;
             }
             Pescave -> GamerVisit++;
 #endif
             break;
         }
 }
References uvsEscave::arrest(), uvsEscave::bring_game_GOODS(), UVS_VANGER_SHAPE::BUNCH_SLAVE, UVS_VANGER_SHAPE::CARAVAN, uvsGamerResult::dominance, UVS_EVENT::FATALITY, FreeList(), UVS_VANGER_SHAPE::GAMER, GamerResult, uvsEscave::GamerVisit, LOC_TIME, NULL, uvsEscave::Pbunch, uvsEscave::Pitem, uvsEscave::Pshop, uvsEscave::Pworld, UVS_VANGER_SHAPE::RANGER, RND(), UVS_VANGER_STATUS::SHOPPING, ShowDominanceMessage(), UVS_VANGER_SHAPE::TABUTASK, UVS_VANGER_SHAPE::THIEF, uvsCheckVangerTabuTask(), uvsVANGER_ARRIVAL, V_CIRTDELIVERY_SCORE, V_LOCTRIP_SCORE, and V_LONGTRIP_SCORE.
isBunchReady()
int uvsVanger::isBunchReady (void) inline
 { return !owner -> vngResource; }
References owner.
KillStatic()
void uvsVanger::KillStatic (void)
{
     if (shape == UVS_VANGER_SHAPE::GAMER_SLAVE) return ;
     if (uvsMechosTable[Pmechos -> type] -> gamer_kill < 5){
         GamerResult.dominance += 5 - uvsMechosTable[Pmechos -> type] -> gamer_kill;
         ShowDominanceMessage(5 - uvsMechosTable[Pmechos -> type] -> gamer_kill);
     } else {
         GamerResult.dominance++;
         ShowDominanceMessage(1);
     }
     if (GamerResult.dominance > 100) GamerResult.dominance = 100;
     uvsMechosTable[Pmechos -> type] -> gamer_kill++;
 }
References uvsGamerResult::dominance, UVS_VANGER_SHAPE::GAMER_SLAVE, GamerResult, ShowDominanceMessage(), and uvsMechosTable.
Referenced by VangerUnit::BulletCollision(), and VangerUnit::DestroyCollision().
makeJump()
int uvsVanger::makeJump (void)
{
     if(shape == UVS_VANGER_SHAPE::GAMER){
 #ifdef _ROAD_
         EffectsOff();
         uvsWorld* aim = Ppassage -> Poutput;
         //Quit = 0;
         //Dead = 0;
 //      ErrH.Abort("Limited version. Only one world available...");
         Ppassage = aim -> getPassage(Pworld);
         Pworld = aim;
         /*{
             Pworld -> getItemFromCrypt(UVS_CRYPT::DEVICE);
             Pworld -> getItemFromCrypt(UVS_CRYPT::AMMO);
             Pworld -> getItemFromCrypt(UVS_CRYPT::ARMO_LIGHT);
             Pworld -> getItemFromCrypt(UVS_CRYPT::ARMO_HEAVY);
         } else {
             Pworld -> updateCrypt();
         }*/
         Pworld -> GamerVisit++;
         if (WorldTable[aim -> gIndex]-> escTmax){
             uvsCurrentCycle = WorldTable[aim -> gIndex] -> escT[0] -> Pbunch -> currentStage;
             if (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE)
                 uvsCurrentWorldUnable = 1;
             else
                 uvsCurrentWorldUnable = 0;
         } else {
             uvsCurrentCycle = 0;
             uvsCurrentWorldUnable = 0;
         }
         if (WorldTable[aim -> gIndex] -> escTmax)
             aci_curLocationName = WorldTable[aim -> gIndex] -> escT[0] -> name;
         else
             aci_curLocationName = "";
         ChangeWorld(aim -> gIndex);              // смена мира
         addVanger(this,Ppassage,1);                 // человек
         uvsWorldReload(aim -> gIndex);
         if ( !Pworld -> GamerVisit ){
             ShowDominanceMessage(10);
             GamerResult.dominance += 10;
             if (GamerResult.dominance > 100) GamerResult.dominance = 100;
         }
 #ifdef STAND_REPORT
     stand < ConTimer.GetTime();
     stand < "\nTeleport on the World  " < Pworld -> name < "  visit " <= Pworld -> GamerVisit < "\n";
 #endif
 #endif
         }
     else {
         uvsOrder* ord = orderT;
         uvsWorld* aim = Ppassage -> Poutput;
         if ( aim -> gIndex >= MAIN_WORLD_MAX) ErrH.Abort("uvsVanger::makeJump - it not real world");
         uvsPassage* pp = aim -> getPassage(Pworld);
         if(pp -> locked || aim -> locked) return 0;
         uvsCheckVangerTabuTask(this,uvsVANGER_ARRIVAL);
         if ( Pmechos -> color < 3 &&
             WorldTable[Pmechos -> color] -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE &&
              shape != UVS_VANGER_SHAPE::GAMER_SLAVE){
                  Pmechos -> color = 3;
                 if( shape == UVS_VANGER_SHAPE::BUNCH_SLAVE)
                     shape = UVS_VANGER_SHAPE::RANGER;
         }
         Pworld = aim;
         Ppassage = pp;
         pos_x = pp -> pos_x;
         pos_y = pp -> pos_y;
         if ( shape == UVS_VANGER_SHAPE::KILLER )
             go_to_GAMER();
         switch(ord -> event){
             case UVS_EVENT::GO_ESCAVE:
                 status = UVS_VANGER_STATUS::MOVEMENT;
                 Pescave = (uvsEscave*)(ord -> Ptarget);
                 break;
             case UVS_EVENT::GO_SPOT:
                 status = UVS_VANGER_STATUS::MOVEMENT;
                 Pspot = (uvsSpot*)(ord -> Ptarget);
                 break;
             case UVS_EVENT::GO_PASSAGE:
                 status = UVS_VANGER_STATUS::MOVEMENT;
                 break;
             case UVS_EVENT::GO_CIRT:
                 status = UVS_VANGER_STATUS::MOVEMENT;
                 ord -> event = UVS_EVENT::GO_CIRT;
                 break;
                 }
         speed = 3;
         if ( shape !=  UVS_VANGER_SHAPE::THIEF)
             speed += RND(V_SPEED_MAX);
         }
     return 1;
 }
References XErrorHandler::Abort(), aci_curLocationName, addVanger(), UVS_VANGER_SHAPE::BUNCH_SLAVE, ChangeWorld(), ConTimer, uvsGamerResult::dominance, EffectsOff(), ErrH, Gamer, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, GamerResult, uvsEscave::GamerVisit, uvsContimer::GetTime(), UVS_EVENT::GO_CIRT, UVS_EVENT::GO_ESCAVE, UVS_EVENT::GO_PASSAGE, UVS_EVENT::GO_SPOT, UVS_VANGER_SHAPE::KILLER, uvsEscave::locked, MAIN_WORLD_MAX, UVS_VANGER_STATUS::MOVEMENT, uvsEscave::name, uvsEscave::Pbunch, uvsTarget::pos_x, uvsTarget::pos_y, uvsEscave::Pworld, UVS_VANGER_SHAPE::RANGER, RND(), ShowDominanceMessage(), UVS_VANGER_SHAPE::THIEF, UVS_BUNCH_STATUS::UNABLE, uvsCheckVangerTabuTask(), uvsCurrentCycle, uvsCurrentWorldUnable, uvsVANGER_ARRIVAL, uvsWorldReload(), V_SPEED_MAX, and WorldTable.
newGoodTabuTask()
int uvsVanger::newGoodTabuTask (void)
{
     if (Pescave)
         return (Pescave -> TabuTaskGood - Pescave -> lastTabuTaskGood);
     else
         return (Pspot -> TabuTaskGood - Pspot -> lastTabuTaskGood);
 }
References uvsEscave::lastTabuTaskGood, and uvsEscave::TabuTaskGood.
prepare_caravan()
void uvsVanger::prepare_caravan (void)
{
     uvsShop *ps;
     uvsItem *pi;
     if ( status == UVS_VANGER_STATUS::ESCAVE_SLEEPING ){
         ps = Pescave -> Pshop;
     } else {
         ps = Pspot -> Pshop;
     }
     if ((Pmechos -> status & UVS_MECHOS_USED::CARAVAN) && (Pworld -> escT[0] -> Pbunch -> status != UVS_BUNCH_STATUS::UNABLE)){
         if ((pi = GetItem_as_type( ps -> Pitem,  UVS_ITEM_STATUS::ARTIFACT)) != NULL ) {
             ((uvsItem*)pi) -> delink(  ps -> Pitem );
             addItem(pi, 1);
             shape = UVS_VANGER_SHAPE::CARAVAN;
         } else  if ((pi = GetItem_as_type( ps -> Pitem,  UVS_ITEM_STATUS::MECHOS_PART)) != NULL ) {
             ((uvsItem*)pi) -> delink(  ps -> Pitem );
             addItem(pi, 1);
             shape = UVS_VANGER_SHAPE::CARAVAN;
         }
     }
     addInventory();
 }
References UVS_ITEM_STATUS::ARTIFACT, UVS_MECHOS_USED::CARAVAN, UVS_VANGER_SHAPE::CARAVAN, UVS_VANGER_STATUS::ESCAVE_SLEEPING, GetItem_as_type(), UVS_ITEM_STATUS::MECHOS_PART, NULL, uvsEscave::Pbunch, uvsEscave::Pitem, uvsEscave::Pshop, uvsEscave::Pworld, and UVS_BUNCH_STATUS::UNABLE.
prepare_diagen_statistic()
void uvsVanger::prepare_diagen_statistic (void)
{
     int nymbos;
     int phlegma;
     int heroin;
     int shrub;
     int poponka;
     int toxick;
     uvsPassagerFromStatistic();
     //GamerResult.get_weezyk = 0;
     GamerResult.mechos_type = uvsMechosTable[Pmechos -> type] -> type;
     GamerResult.eleech = ItemCount(Pitem,UVS_ITEM_TYPE::ELEECH );
     nymbos = GamerResult.nymbos;
     phlegma = GamerResult.phlegma;
     heroin   = GamerResult.heroin;
     shrub = GamerResult.shrub;
     poponka = GamerResult.poponka;
     toxick = GamerResult.toxick;
     GamerResult.eleepod = ItemCount(Pitem,UVS_ITEM_TYPE::ELEEPOD );
     GamerResult.beeboorat = ItemCount(Pitem,UVS_ITEM_TYPE::BEEBOORAT );
     GamerResult.zeex = ItemCount(Pitem,UVS_ITEM_TYPE::ZEEX );
     GamerResult.nymbos = ItemCount(Pitem,UVS_ITEM_TYPE::NYMBOS );
     GamerResult.phlegma = ItemCount(Pitem, UVS_ITEM_TYPE::PHLEGMA);
     GamerResult.heroin = ItemCount(Pitem,UVS_ITEM_TYPE::HEROIN );
     GamerResult.shrub = ItemCount(Pitem, UVS_ITEM_TYPE::SHRUB);
     GamerResult.poponka = ItemCount(Pitem,UVS_ITEM_TYPE::POPONKA );
     GamerResult.toxick = ItemCount(Pitem, UVS_ITEM_TYPE::TOXICK);
     GamerResult.unik_poponka = uvsPoponkaIDON(Pitem);
     if (NetworkON && my_server_data.GameType == MECHOSOMA){
         if (GamerResult.nymbos > nymbos)
             my_player_body.MechosomaStat.SneakCount += GamerResult.nymbos - nymbos;
         else
             my_player_body.MechosomaStat.LostCount -= GamerResult.nymbos - nymbos;
         if (GamerResult.phlegma > phlegma)
             my_player_body.MechosomaStat.SneakCount += GamerResult.phlegma - phlegma;
         else
             my_player_body.MechosomaStat.LostCount -= GamerResult.phlegma - phlegma;
         if (GamerResult.heroin > heroin)
             my_player_body.MechosomaStat.SneakCount += GamerResult.heroin - heroin;
         else
             my_player_body.MechosomaStat.LostCount -= GamerResult.heroin - heroin;
         if (GamerResult.shrub > shrub)
             my_player_body.MechosomaStat.SneakCount += GamerResult.shrub - shrub;
         else
             my_player_body.MechosomaStat.LostCount -= GamerResult.shrub - shrub;
         if (GamerResult.poponka > poponka)
             my_player_body.MechosomaStat.SneakCount += GamerResult.poponka - poponka;
         else
             my_player_body.MechosomaStat.LostCount -= GamerResult.poponka - poponka;
         if (GamerResult.toxick > toxick)
             my_player_body.MechosomaStat.SneakCount += GamerResult.toxick - toxick;
         else
             my_player_body.MechosomaStat.LostCount -= GamerResult.toxick - toxick;
         NetStatisticUpdate(NET_STATISTICS_CHECKPOINT);
         send_player_body(my_player_body);
     }
     GamerResult.pipetka = ItemCount(Pitem, UVS_ITEM_TYPE::PIPETKA, 1);
     GamerResult.kernoboo = ItemCount(Pitem, UVS_ITEM_TYPE::KERNOBOO, 1);
     GamerResult.weezyk = ItemCount(Pitem, UVS_ITEM_TYPE::WEEZYK);
     GamerResult.rubbox = ItemCount(Pitem, UVS_ITEM_TYPE::RUBBOX);
     GamerResult.dead_eleech_now = ItemCount(Pitem, UVS_ITEM_TYPE::DEAD_ELEECH);
     GamerResult.boot_sector = ItemCount(Pitem, UVS_ITEM_TYPE::SECTOR);
     GamerResult.peelot = ItemCount(Pitem, UVS_ITEM_TYPE::PEELOT);
     GamerResult.spummy = ItemCount(Pitem, UVS_ITEM_TYPE::SPUMMY);
     GamerResult.fun83 = ItemCount(Pitem, UVS_ITEM_TYPE::FUNCTION83);
     GamerResult.mechanic_messiah = ItemCount(Pitem, UVS_ITEM_TYPE::MECHANIC_MESSIAH);
     GamerResult.protractor = ItemCount(Pitem, UVS_ITEM_TYPE::PROTRACTOR);
     GamerResult.leepuringa = ItemCount(Pitem, UVS_ITEM_TYPE::LEEPURINGA);
     GamerResult.palochka = ItemCount(Pitem, UVS_ITEM_TYPE::PALOCHKA);
     GamerResult.pipka = ItemCount(Pitem, UVS_ITEM_TYPE::PIPKA);
     GamerResult.nobool = ItemCount(Pitem, UVS_ITEM_TYPE::NOBOOL);
     GamerResult.boorawchick = ItemCount(Pitem, UVS_ITEM_TYPE::BOORAWCHICK);
     GamerResult.pereponka = ItemCount(Pitem, UVS_ITEM_TYPE::PEREPONKA);
     GamerResult.zeefick = ItemCount(Pitem, UVS_ITEM_TYPE::ZEEFICK);
     GamerResult.thief_leepuringa = uvsReturnTreasureStatus(UVS_ITEM_TYPE::LEEPURINGA);
     GamerResult.thief_palochka = uvsReturnTreasureStatus(UVS_ITEM_TYPE::PALOCHKA);
     GamerResult.thief_pipka = uvsReturnTreasureStatus(UVS_ITEM_TYPE::PIPKA);
     GamerResult.thief_nobool = uvsReturnTreasureStatus(UVS_ITEM_TYPE::NOBOOL);
     GamerResult.thief_boorawchick = uvsReturnTreasureStatus(UVS_ITEM_TYPE::BOORAWCHICK);
     GamerResult.thief_pereponka = uvsReturnTreasureStatus(UVS_ITEM_TYPE::PEREPONKA);
     GamerResult.thief_zeefick = uvsReturnTreasureStatus(UVS_ITEM_TYPE::ZEEFICK);
 #ifdef STAND_REPORT
     stand < "statistic:lucl " <= (GamerResult.luck + GamerResult.add_luck) < " dominionce "  <= (GamerResult.dominance+GamerResult.add_dominance) < "\n";
     stand < "statistic: nimbos " <= GamerResult.nymbos_total < " phlegma "  <= GamerResult.phlegma_total < "\n";
     stand < "statistic: heroin " <= GamerResult.heroin_total < " shrub "  <= GamerResult.shrub_total < "\n";
     stand < "statistic: poponka " <= GamerResult.poponka_total < " toxick "  <= GamerResult.toxick_total < " dead eleech " <= GamerResult.dead_eleech_now < " mechos " <= GamerResult.mechos_variant < "  \n";
 #endif
     _checkDolly_();
     _sellCirt_();
 }
References uvsGamerResult::add_dominance, uvsGamerResult::add_luck, UVS_ITEM_TYPE::BEEBOORAT, uvsGamerResult::beeboorat, UVS_ITEM_TYPE::BOORAWCHICK, uvsGamerResult::boorawchick, uvsGamerResult::boot_sector, UVS_ITEM_TYPE::DEAD_ELEECH, uvsGamerResult::dead_eleech_now, uvsGamerResult::dominance, UVS_ITEM_TYPE::ELEECH, uvsGamerResult::eleech, UVS_ITEM_TYPE::ELEEPOD, uvsGamerResult::eleepod, uvsGamerResult::fun83, UVS_ITEM_TYPE::FUNCTION83, GamerResult, ServerData::GameType, UVS_ITEM_TYPE::HEROIN, uvsGamerResult::heroin, uvsGamerResult::heroin_total, ItemCount(), UVS_ITEM_TYPE::KERNOBOO, uvsGamerResult::kernoboo, UVS_ITEM_TYPE::LEEPURINGA, uvsGamerResult::leepuringa, MechosomaStatistic::LostCount, uvsGamerResult::luck, UVS_ITEM_TYPE::MECHANIC_MESSIAH, uvsGamerResult::mechanic_messiah, uvsGamerResult::mechos_type, uvsGamerResult::mechos_variant, MECHOSOMA, PlayerBody::MechosomaStat, my_player_body, my_server_data, NET_STATISTICS_CHECKPOINT, NetStatisticUpdate(), NetworkON, UVS_ITEM_TYPE::NOBOOL, uvsGamerResult::nobool, UVS_ITEM_TYPE::NYMBOS, uvsGamerResult::nymbos, uvsGamerResult::nymbos_total, UVS_ITEM_TYPE::PALOCHKA, uvsGamerResult::palochka, UVS_ITEM_TYPE::PEELOT, uvsGamerResult::peelot, UVS_ITEM_TYPE::PEREPONKA, uvsGamerResult::pereponka, UVS_ITEM_TYPE::PHLEGMA, uvsGamerResult::phlegma, uvsGamerResult::phlegma_total, UVS_ITEM_TYPE::PIPETKA, uvsGamerResult::pipetka, UVS_ITEM_TYPE::PIPKA, uvsGamerResult::pipka, uvsEscave::Pitem, UVS_ITEM_TYPE::POPONKA, uvsGamerResult::poponka, uvsGamerResult::poponka_total, UVS_ITEM_TYPE::PROTRACTOR, uvsGamerResult::protractor, UVS_ITEM_TYPE::RUBBOX, uvsGamerResult::rubbox, UVS_ITEM_TYPE::SECTOR, send_player_body(), UVS_ITEM_TYPE::SHRUB, uvsGamerResult::shrub, uvsGamerResult::shrub_total, MechosomaStatistic::SneakCount, UVS_ITEM_TYPE::SPUMMY, uvsGamerResult::spummy, uvsGamerResult::thief_boorawchick, uvsGamerResult::thief_leepuringa, uvsGamerResult::thief_nobool, uvsGamerResult::thief_palochka, uvsGamerResult::thief_pereponka, uvsGamerResult::thief_pipka, uvsGamerResult::thief_zeefick, UVS_ITEM_TYPE::TOXICK, uvsGamerResult::toxick, uvsGamerResult::toxick_total, uvsGamerResult::unik_poponka, uvsMechosTable, uvsPassagerFromStatistic(), uvsPoponkaIDON(), uvsReturnTreasureStatus(), UVS_ITEM_TYPE::WEEZYK, uvsGamerResult::weezyk, UVS_ITEM_TYPE::ZEEFICK, uvsGamerResult::zeefick, UVS_ITEM_TYPE::ZEEX, and uvsGamerResult::zeex.
prepare_killer()
int uvsVanger::prepare_killer (void)
{
     if ( !(Pescave -> Pbunch -> status & ((int)(UVS_BUNCH_STATUS::KILL_GAMER))) ) return 0;
     if (uvsKillerNow() >= 2) return 0;
     if ( status == UVS_VANGER_STATUS::ESCAVE_SLEEPING ){
         Pescave -> Pshop -> sellMechos(Pmechos, (int)(UVS_MECHOS_USED::KILLER));
         Pmechos -> color = Pescave -> Pbunch -> biosNindex;
         if (Pmechos -> status & ((int)UVS_MECHOS_USED::KILLER)){
             shape = UVS_VANGER_SHAPE::KILLER;
             Pescave -> Pbunch -> status ^= (int)(UVS_BUNCH_STATUS::KILL_GAMER);
             addInventory();
             go_to_GAMER();
             return 1;
         }
     }
     return 0;
 }
References UVS_VANGER_STATUS::ESCAVE_SLEEPING, UVS_BUNCH_STATUS::KILL_GAMER, UVS_MECHOS_USED::KILLER, UVS_VANGER_SHAPE::KILLER, uvsEscave::Pbunch, uvsEscave::Pshop, and uvsKillerNow().
prepare_list_for_ActInt()
void uvsVanger::prepare_list_for_ActInt (uvsActInt *& Item, uvsActInt *& Mechos, uvsShop * ps, int where)
{
     listElem* pe;
     listElem* pb;
     listElem* pn;
     listElem *pg;
     uvsBunch *pm;
     int cq, mq;
     int priceQ;
     int _tabu_taskID_;
     int _tabu_taskCOUNT_;
     int dead_world;
     if (where){
         pg = Pescave -> Pgood;
         _tabu_taskID_ = Pescave -> TabuTaskID;
         _tabu_taskCOUNT_ = Pescave -> TabuTaskCount;
     } else {
         pg = Pspot -> Pgood;
         _tabu_taskID_ = Pspot -> TabuTaskID;
         _tabu_taskCOUNT_ = Pspot -> TabuTaskCount;
     }
     if (Pworld -> escTmax)
         dead_world = (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE);
     else {
         dead_world = 0;
         _tabu_taskID_ = -1;
         _tabu_taskCOUNT_ = 0;
     }
     if (Pworld -> escTmax){
         pm  = Pworld -> escT[0] -> Pbunch;
         cq = pm -> cycleTable[ pm -> currentStage ].cirtQ;
         mq = pm -> cycleTable[ pm -> currentStage ].cirtMAX;
         priceQ = pm -> cycleTable[ pm -> currentStage ].priceQ;
     } else {
         pm = NULL;
         cq = mq = 1;
         priceQ = 100;
     }
     pb = NULL;
     if ( Pmechos ){
         pn = new uvsActInt;
         int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
         if (Pmechos -> type >= first_constr){
             int _type = Pmechos -> type - first_constr;
             ((uvsActInt*)pn) -> type =  first_constr + (_type<<2) + uvsMechosTable[Pmechos -> type] -> constractor;
             if (uvsMechosTable[Pmechos -> type] -> constractor == 3)
                 ((uvsActInt*)pn) -> price = uvsMechosTable[Pmechos -> type] -> price;
             else
                 ((uvsActInt*)pn) -> price = 1;
             ((uvsActInt*)pn) -> sell_price = uvsMechosTable[Pmechos -> type] -> sell_price;
             ((uvsActInt*)pn) -> param1 = Pmechos -> color;
             ((uvsActInt*)pn) -> param2 = Pmechos -> teleport;
         } else {
             ((uvsActInt*)pn) -> type =  Pmechos -> type;
             ((uvsActInt*)pn) -> price = uvsMechosTable[Pmechos -> type] -> price;
             ((uvsActInt*)pn) -> sell_price = uvsMechosTable[Pmechos -> type] -> sell_price;
             ((uvsActInt*)pn) -> param1 = Pmechos -> color;
             ((uvsActInt*)pn) -> param2 = Pmechos -> teleport;
         }
         if (!NetworkON){
             if (WorldTable[ CurrentWorld ] -> escTmax){
                  ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
                  ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
             }
             double t = ((double)(GamerResult.dominance+GamerResult.add_dominance))/100.0;
             if ( t > 1.0 ) t = 1.0;
             if ( t < -1.0 ) t = -1.0;
              if ( t > 0.0){
                  double dt = (((uvsActInt*)pn) -> price - ((uvsActInt*)pn) ->sell_price)/2;
                 ((uvsActInt*)pn) -> price -= t*dt;
                 ((uvsActInt*)pn) -> sell_price +=  t*dt;
              } else {
                  ((uvsActInt*)pn) -> price *= (1.0 - t);
                 ((uvsActInt*)pn) -> sell_price *= (1.0 + t);
              }
         }//  end if
          if (ChangeArmor != -1){
              ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> sell_price*( 1.0 + (( (ChangeArmor>>16) - uvsMechosTable[Pmechos -> type] -> MaxArmor)/double(uvsMechosTable[Pmechos -> type] -> MaxArmor*2.0)));
          }
          if (((uvsActInt*)pn) -> sell_price > ((uvsActInt*)pn) -> price) ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price;
          if (dead_world)
             ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price = 0;
         pn -> link(pb);
     }
     Mechos = (uvsActInt*)pb;
     pb = NULL;
     pe = Pitem;
     while( pe ){
          pn = new uvsActInt;
          ((uvsActInt*)pn) -> type = ( ((uvsItem*)pe) -> ActIntType());
          ((uvsActInt*)pn) -> param1 = ( ((uvsItem*)pe) -> param1);
          ((uvsActInt*)pn) -> param2 = ( ((uvsItem*)pe) -> param2);
          ((uvsActInt*)pn) -> pos_x = ( ((uvsItem*)pe) -> pos_x);
          ((uvsActInt*)pn) -> pos_y = ( ((uvsItem*)pe) -> pos_y);
          if (WorldTable[ CurrentWorld ] -> escTmax){
              ((uvsActInt*)pn) -> price = ps -> Price[( ((uvsItem*)pe) -> type)];
              ((uvsActInt*)pn) -> sell_price = ps -> Price[( ((uvsItem*)pe) -> type) + MAX_ITEM_TYPE];
             switch( uvsItemTable[( ((uvsItem*)pe) -> type)] -> type){
             case UVS_ITEM_STATUS::DEVICE:
             case UVS_ITEM_STATUS::WEAPON:
                 if ( ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::TERMINATOR || ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::TERMINATOR2){
                     ((uvsActInt*)pn) -> price *= ((uvsActInt*)pn) -> param2;
                     ((uvsActInt*)pn) -> sell_price *= ((uvsActInt*)pn) -> param2;
                 } else {
                     if (uvsItemTable[( ((uvsItem*)pe) -> type)] -> param2 ){
                         ((uvsActInt*)pn) -> price -= (( uvsItemTable[((uvsItem*)pe) -> type] -> param2 - ((uvsActInt*)pn) -> param2)*(((uvsActInt*)pn) -> price))/(uvsItemTable[ ((uvsItem*)pe) -> type] -> param2*2);
                         ((uvsActInt*)pn) -> sell_price -= (( uvsItemTable[( ((uvsItem*)pe) -> type)] -> param2- ((uvsActInt*)pn) -> param2)*(((uvsActInt*)pn) -> sell_price))/(uvsItemTable[ ((uvsItem*)pe) -> type] -> param2*2);
                     }
                 }
                 if (!NetworkON){
                     ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
                     ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
                 }
                 break;
             case UVS_ITEM_STATUS::AMMO:
                 ((uvsActInt*)pn) -> price *= ((uvsActInt*)pn) -> param2;
                 ((uvsActInt*)pn) -> sell_price *= ((uvsActInt*)pn) -> param2;
                 if (!NetworkON){
                     ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
                     ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
                 }
                 break;
             case UVS_ITEM_STATUS::ARTIFACT:
                 break;
             case UVS_ITEM_STATUS::GOODS:
                 if ( ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::ELEECH || ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::WEEZYK){
                     int coef = (((uvsItem*)pe) -> param1 & 0x0000FFFF) + 1;
                     if (coef > 3) coef = 3;
                     ((uvsActInt*)pn) -> sell_price *= coef;
                 } else  if (((uvsItem*)pe) -> type == UVS_ITEM_TYPE::TABUTASK){
                     int _ID_ = ((uvsItem*)pe) -> param2 & 0x0000FFFF;
                     ((uvsActInt*)pn) -> sell_price = 0;
                     if ( (_ID_ >= _tabu_taskID_) && (_ID_ < _tabu_taskID_ + _tabu_taskCOUNT_) && ( ((uvsActInt*)pn) -> type ==TABUTASK_GOOD) ){
                         ((uvsActInt*)pn) -> sell_price = TabuTable[_ID_] -> cash;
                     }
                 } else if ( ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::ELEEPOD && !dgAbortStatus){
                     if (_tabu_taskID_ == (((uvsItem*)pe) -> param2>>16))  {
                         uvs_aciKillOneItem( ((uvsActInt*)pn) ->type, ((uvsActInt*)pn) -> pos_x, ((uvsActInt*)pn) -> pos_y);
                         aciUpdateCurCredits(aciGetCurCredits() + 6000);
                         delete (uvsActInt*)pn;
                         pn = NULL;
                     }
                     break;
                 } else if ( ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::BEEBOORAT && !dgAbortStatus){
                     if (_tabu_taskID_ == (((uvsItem*)pe) -> param2>>16)){
                         uvs_aciKillOneItem( ((uvsActInt*)pn) ->type, ((uvsActInt*)pn) -> pos_x, ((uvsActInt*)pn) -> pos_y);
                         aciUpdateCurCredits(aciGetCurCredits() + 2000);
                         delete (uvsActInt*)pn;
                         pn = NULL;
                     }
                     break;
                 } else if (((uvsItem*)pe) -> type == UVS_ITEM_TYPE::ZEEX && !dgAbortStatus){
                     if (_tabu_taskID_ == (((uvsItem*)pe) -> param2>>16)){
                         uvs_aciKillOneItem( ((uvsActInt*)pn) ->type, ((uvsActInt*)pn) -> pos_x, ((uvsActInt*)pn) -> pos_y);
                         aciUpdateCurCredits(aciGetCurCredits() + 5000);
                         delete (uvsActInt*)pn;
                         pn = NULL;
                     }
                     break;
                 } else {
                     uvsTradeItem* pl = (uvsTradeItem*)pg;
                     while(pl){
                         if (pl -> type == ((uvsItem*)pe) -> type){
                             int coef = (((uvsItem*)pe) -> param1 & 0x0000FFFF);
                             if (coef)
                                 ((uvsActInt*)pn) -> sell_price /= (1<<(coef-1));
                             else
                                 ((uvsActInt*)pn) -> sell_price *= 2;
                             break;
                         }//  end if
                         pl = (uvsTradeItem*)pl -> next;
                     }//  end while
                     if (!pl){
                         int coef = ((uvsItem*)pe) -> GetCoef();
                         if (coef < 0 ) ErrH.Abort("uvsItem :: dont have town");
                         ((uvsActInt*)pn) -> sell_price *= coef;
                         ((uvsActInt*)pn) -> sell_price /=2;
                     } //  end  if
                     if (((uvsItem*)pe) -> type == UVS_ITEM_TYPE::KERNOBOO || ((uvsItem*)pe) -> type == UVS_ITEM_TYPE::PIPETKA ){
                         ((uvsActInt*)pn) -> sell_price *= ((uvsItem*)pe) -> param2;
                         ((uvsActInt*)pn) -> price *= ((uvsItem*)pe) -> param2;
                     }
 //                  ((uvsActInt*)pn) -> price = ((uvsActInt*)pn) -> sell_price;
                 }//  end if
                 break;
             case UVS_ITEM_STATUS::THING:
             case UVS_ITEM_STATUS::TREASURE:
             case UVS_ITEM_STATUS::MECHOS_PART:
                 break;
             };
          } else {
              ((uvsActInt*)pn) -> price = 1;
              ((uvsActInt*)pn) -> sell_price = 1;
          }
          if (pn){
              if (((uvsItem*)pe) -> type != UVS_ITEM_TYPE::TABUTASK && !NetworkON){
                  double t = ((double)(GamerResult.dominance+GamerResult.add_dominance))/100.0;
                 if ( t > 1.0 ) t = 1.0;
                 if ( t < -1.0 ) t = -1.0;
                  if ( t > 0.0){
                      double dt = (((uvsActInt*)pn) -> price - ((uvsActInt*)pn) ->sell_price)/2;
                     ((uvsActInt*)pn) -> price -= t*dt;
                     ((uvsActInt*)pn) -> sell_price +=  t*dt;
                  } else {
                      ((uvsActInt*)pn) -> price *= (1.0 - t);
                     ((uvsActInt*)pn) -> sell_price *= (1.0 + t);
                  }
                 if (((uvsActInt*)pn) -> sell_price > ((uvsActInt*)pn) -> price) ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price;
              }
             if (((uvsActInt*)pn) -> sell_price == 0) ((uvsActInt*)pn) -> sell_price = 1;
             if (((uvsActInt*)pn) -> price == 0) ((uvsActInt*)pn) -> price = 1;
             if (((uvsActInt*)pn) -> type == ACI_DEAD_ELEECH ||
                 ((uvsActInt*)pn) -> type == ACI_ROTTEN_KERNOBOO ||
                 ((uvsActInt*)pn) -> type == ACI_ROTTEN_PIPETKA ||
                 ((uvsActInt*)pn) -> type == ACI_ROTTEN_WEEZYK ){
                 ((uvsActInt*)pn) -> sell_price = 0;
                 ((uvsActInt*)pn) -> price = 0;
             }
             if (dead_world)
                 ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price = 0;
              pn -> link(pb);
          }
         pe = pe -> next;
     }
     Item = (uvsActInt*)pb;
     if (Pworld -> escTmax){
         if (where)
             aciUpdateCurCredits(aciGetCurCredits() + sellCirt()*400);
         uvsCheckItemOnTabuTask(Pitem, _tabu_taskID_, _tabu_taskCOUNT_);
         if (!dgAbortStatus)
             GamerResult.game_result =  game_result( aci_curLocationName );
         else
             GamerResult.game_result = 0;
     }
     if (Pmechos){
         delete Pmechos;
         Pmechos = NULL;
     }
     FreeList(Pitem);
     Pitem = NULL;
 /*  if (where){
         pe = Pescave -> Pitem;
     } else {
         pe = Pspot -> Pitem;
     }
     if (GTreasureItem) ErrH.Abort("uvsVanger::prepare_list_for_ActInt - unresolved treasure");
     pb = NULL;
     if(pe && !((uvsItem*)pe) -> param1 && (GamerResult.luck + GamerResult.add_luck > RND(100)) ){
          pn = new uvsActInt;
          ((uvsActInt*)pn) -> type = ( ((uvsItem*)pe) -> ActIntType());
          ((uvsActInt*)pn) -> param1 = 0;
          ((uvsActInt*)pn) -> param2 = ( ((uvsItem*)pe) -> param2);
          ((uvsActInt*)pn) -> price = 1;
          ((uvsActInt*)pn) -> sell_price = 1;
          ((uvsItem*)pe) -> param1 = uvsTreasureInShop;
          pn -> link(pb);
     }
     if (!where && (!strcmp(Pspot -> name, "Ogorod")) && (GamerResult.luck + GamerResult.add_luck > RND(30)) ){
          pn = new uvsActInt;
          ((uvsActInt*)pn) -> type = ACI_RUBOX;
          ((uvsActInt*)pn) -> param1 = uvsItemTable[UVS_ITEM_TYPE::RUBBOX] -> param1;
          ((uvsActInt*)pn) -> param2 = uvsItemTable[UVS_ITEM_TYPE::RUBBOX] -> param2;
          ((uvsActInt*)pn) -> price = 1;
          ((uvsActInt*)pn) -> sell_price = 1;
          pn -> link(pb);
     }
     GTreasureItem = (uvsActInt*)pb;*/
 }
References aciGetCurCredits(), aciUpdateCurCredits(), uvsGamerResult::add_dominance, UVS_ITEM_STATUS::AMMO, UVS_ITEM_STATUS::ARTIFACT, UVS_ITEM_TYPE::BEEBOORAT, ChangeArmor, CurrentWorld, UVS_ITEM_STATUS::DEVICE, dgAbortStatus, uvsGamerResult::dominance, UVS_ITEM_TYPE::ELEECH, UVS_ITEM_TYPE::ELEEPOD, Gamer, GamerResult, UVS_ITEM_STATUS::GOODS, MAX_ITEM_TYPE, MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, NetworkON, NULL, Pescave, Pitem, Pmechos, uvsTarget::pos_x, uvsTarget::pos_y, Pspot, Pworld, status, TabuTable, UVS_ITEM_TYPE::TABUTASK, TABUTASK_GOOD, UVS_ITEM_TYPE::TERMINATOR, UVS_ITEM_TYPE::TERMINATOR2, uvsElement::type, UVS_BUNCH_STATUS::UNABLE, uvs_aciKillOneItem(), uvsItemTable, uvsMechosTable, UVS_ITEM_STATUS::WEAPON, UVS_ITEM_TYPE::WEEZYK, WorldTable, and UVS_ITEM_TYPE::ZEEX.
prepare_shop()
void uvsVanger::prepare_shop (int how)
{
         uvsGamerWaitGame = 0;
         uvsCurrentWorldUnableBefore = uvsCurrentWorldUnable;
         uvsTownName = NULL;
         EffectsOff();
         if ( Pescave ){
             aci_curLocationName = Pescave -> name;
             uvsBunchNumber = Pescave -> Pbunch -> biosNindex;
         } else
             aci_curLocationName = Pspot -> name;
         if (strcmp(uvsLastEscaveName, aci_curLocationName))
             uvsGoodsON = 1;
         else
             uvsGoodsON = 0;
         uvsLastEscaveName = aci_curLocationName;
         if (!how) return;
         GGamerMechos = GGamer = GMechos = GItem = NULL;
         lastMechos = Pmechos -> type;
         prepare_diagen_statistic();
         dgD -> checkSession(aci_curLocationName); // rname - имя эскейва
         if (!dgAbortStatus)
             checkDolly();
         if ( Pescave ){
 #ifdef _ROAD_
             Pescave -> Pshop -> locked = 1;
             Pescave -> add_goods_to_shop();
             Pescave -> Pshop ->  prepare_list_for_ActInt( GMechos, GItem, 1);
             uvsItem* pi = GetItem( Pitem, ((uvsItem*)Pescave -> Pitem) -> type, 0 );
             if (pi && (Pescave -> Pbunch -> status != UVS_BUNCH_STATUS::UNABLE) ){
                 if (((uvsItem*)Pescave -> Pitem) -> param1 != uvsTreasureInGamer){
                     aciUpdateCurCredits(aciGetCurCredits() + Pescave -> Pshop -> Price[((uvsItem*)Pescave -> Pitem) -> type + MAX_ITEM_TYPE]);
                     ShowDominanceMessage(5);
                     GamerResult.dominance += 5;
                     if (GamerResult.dominance >100) GamerResult.dominance = 100;
                 }
                 uvs_aciKillItem(uvsSetItemType(pi -> type, 0, -1));
                 pi -> delink(Pitem);
                 delete pi;
                 ((uvsItem*)Pescave -> Pitem) -> param1 = 0;
             }
 //          GamerResult.beeb = aciCurCredits;
 #endif
             prepare_list_for_ActInt(GGamer, GGamerMechos, Pescave -> Pshop, 1);
 #ifdef STAND_REPORT
         stand < ConTimer.GetTime() < " GAMER arrival to " < aci_curLocationName < " -> " <= Pescave -> GamerVisit < " \n";
 #endif
         } else {
 #ifdef _ROAD_
 //          GamerResult.beeb = aciCurCredits;
 #endif
             if (Pspot -> Pshop){
                 Pspot -> Pshop -> locked = 1;
                 Pspot -> add_goods_to_shop();
                 Pspot -> Pshop -> prepare_list_for_ActInt( GMechos, GItem, 0);
                 uvsItem* pi = GetItem( Pitem, ((uvsItem*)Pspot -> Pitem) -> type, 0 );
                 if ( (Pworld -> escT[0] -> Pbunch -> status != UVS_BUNCH_STATUS::UNABLE) &&pi && (pi -> type != UVS_ITEM_TYPE::NOBOOL) && (pi -> type != UVS_ITEM_TYPE::PIPKA) ){
                     if (((uvsItem*)Pspot -> Pitem) -> param1 != uvsTreasureInGamer){
                         aciUpdateCurCredits(aciGetCurCredits() + Pspot -> Pshop -> Price[((uvsItem*)Pspot -> Pitem) -> type + MAX_ITEM_TYPE]);
                         ShowDominanceMessage(5);
                         GamerResult.dominance += 5;
                         if (GamerResult.dominance >100) GamerResult.dominance = 100;
                     }
                     uvs_aciKillItem(uvsSetItemType(pi -> type, 0, -1));
                     pi -> delink(Pitem);
                     delete pi;
                     ((uvsItem*)Pspot -> Pitem) -> param1 = 0;
                 }
             }
             prepare_list_for_ActInt(GGamer, GGamerMechos, Pspot -> Pshop, 0);
 #ifdef STAND_REPORT
         stand < ConTimer.GetTime() < " GAMER arrival to " < aci_curLocationName < " -> " <= Pspot -> GamerVisit < " \n";
 #endif
         }
         if (thief_on_world()){
             if (GamerResult.theif_on_world)  GamerResult.theif = 0;
             else {
                 GamerResult.theif  = 1;
                 GamerResult.theif_on_world = 1;
             }
         } else {
             GamerResult.theif_on_world = 0;
         }
 #ifdef STAND_REPORT
         if (GamerResult.theif_on_world)
             stand < "thief on the world\n";
 #endif
 }
References aci_curLocationName, EffectsOff(), uvsEscave::name, NULL, uvsEscave::Pbunch, uvsBunchNumber, uvsCurrentWorldUnable, uvsCurrentWorldUnableBefore, uvsGamerWaitGame, and uvsTownName.
Quant()
void uvsVanger::Quant (void) virtual
Reimplemented from uvsElement.
{
     uvsCultGame* pg;
     c_All_Number++;
     switch(shape){
         case UVS_VANGER_SHAPE::BUNCH_SLAVE:
             c_S_Number++;
             switch(status){
                 case UVS_VANGER_STATUS::GAME_BEGIN_ESCAVE:
                     if ( Pescave -> locked || (--locTimer > 0)) break;
                     status = UVS_VANGER_STATUS::RACE;
 #ifdef _ROAD_
                     if(isActive()) addVanger(this,Pescave);
 #endif
                     break;
                 case UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_ESCAVE:
                     if ( !Pescave -> real_hunter_now(this) || (--locTimer > 0) ) break;
                     status = UVS_VANGER_STATUS::RACE_HUNTER;
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pescave);
 #endif
                     break;
                 case UVS_VANGER_STATUS::GAME_BEGIN_SPOT:
                     if ( Pspot -> locked || (--locTimer > 0)) break;
                     status = UVS_VANGER_STATUS::RACE;
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pspot);
 #endif
                     break;
                 case UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_SPOT:
                     if ( !Pspot -> real_hunter_now(this) || (--locTimer > 0)) break;
                     status = UVS_VANGER_STATUS::RACE_HUNTER;
         #ifdef _ROAD_
                     if(isActive()) addVanger(this,Pspot);
         #endif
                     break;
                 case UVS_VANGER_STATUS::ESCAVE_SLEEPING:
                     if(isBunchReady() && (Pescave -> may_go_away(Pmechos, shape))){
                         if (prepare_killer()){
                             go_to_GAMER();
                         } else if(Pescave -> game_soon() && RND(2)){
                             status = UVS_VANGER_STATUS::ESCAVE_WAITING;
                             break;
                         } else if (Pescave -> game_now(pg)){
                             add_to_game(pg);
                         } else if(!RND(2)) {
                             Event(UVS_EVENT::GO_FROM_ESCAVE);
                         } else {
                             Event(UVS_EVENT::GO_CIRT);
                         }
                         if (status != UVS_VANGER_STATUS::ESCAVE_SLEEPING)
                             owner -> randVRes();
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pescave);
 #endif
                     }
                     break;
                 case UVS_VANGER_STATUS::SPOT_SLEEPING:
                     if(isBunchReady() && (!Pspot -> locked)){
                         if(Pspot -> game_soon() && !RND(3)){
                             status = UVS_VANGER_STATUS::SPOT_WAITING;
                             break;
                         } else if (Pspot -> game_now(pg))
                             add_to_game(pg);
                         else
                             Event(UVS_EVENT::GO_FROM_SPOT);
                         if (status != UVS_VANGER_STATUS::SPOT_SLEEPING)
                             owner -> randVRes();
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pspot);
 #endif
                         }
                     break;
                 case UVS_VANGER_STATUS::MOVEMENT:
                 case UVS_VANGER_STATUS::FREE_MOVEMENT:
                 case UVS_VANGER_STATUS::RACE:
                 case UVS_VANGER_STATUS::RACE_HUNTER:
                 case UVS_VANGER_STATUS::GATHERING:
                 case UVS_VANGER_STATUS::WAIT_GAMER:
                     break;
                 case UVS_VANGER_STATUS::PASSAGE_GAP:
                     if(!--locTimer){
                         if(makeJump()){
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Ppassage);
 #endif
                         }else
                             locTimer = 1;
                     }
                     break;
                 case UVS_VANGER_STATUS::AIM_HANDLE:
                     if(!--locTimer) aimHandle();
                     break;
                 }
             break;
         case UVS_VANGER_SHAPE::CARAVAN:
         case UVS_VANGER_SHAPE::RANGER:
         case UVS_VANGER_SHAPE::THIEF:
             if ( shape == UVS_VANGER_SHAPE::THIEF)
                 c_A_Number++;
             else
                 c_R_Number++;
             switch(status){
                 case UVS_VANGER_STATUS::GAME_BEGIN_ESCAVE:
                     if ( Pescave -> locked || (--locTimer > 0)) break;
                     status = UVS_VANGER_STATUS::RACE;
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pescave);
 #endif
                     break;
                 case UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_ESCAVE:
                     if ( !Pescave -> real_hunter_now(this) || (--locTimer > 0)) break;
                     status = UVS_VANGER_STATUS::RACE_HUNTER;
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pescave);
 #endif
                     break;
                 case UVS_VANGER_STATUS::GAME_BEGIN_SPOT:
                     if ( Pspot -> locked || (--locTimer > 0)) break;
                     status = UVS_VANGER_STATUS::RACE;
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pspot);
 #endif
                     break;
                 case UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_SPOT:
                     if ( !Pspot -> real_hunter_now(this) || (--locTimer > 0)) break;
                     status = UVS_VANGER_STATUS::RACE_HUNTER;
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pspot);
 #endif
                     break;
                 case UVS_VANGER_STATUS::ESCAVE_SLEEPING:
                     if(isBunchReady() && (Pescave -> may_go_away(Pmechos, shape))){
 //                  if(Pescave -> may_go_away(Pmechos, shape)){
                         if(Pescave -> game_soon() ){
                             status = UVS_VANGER_STATUS::ESCAVE_WAITING;
                             break;
                         } else if (Pescave -> game_now(pg))
                             add_to_game(pg);
                         else if (shape !=  UVS_VANGER_SHAPE::THIEF && !RND(48)){
 //                      else if (shape !=  UVS_VANGER_SHAPE::THIEF && !RND(2)){
                             Event(UVS_EVENT::THIEF);
                         } else if(shape !=  UVS_VANGER_SHAPE::THIEF && !RND(5))
                             Event(UVS_EVENT::THIEF_FROM_SHOP);
                         else if(!RND(2))
                             Event(UVS_EVENT::GO_FROM_ESCAVE);
                         else
                             Event(UVS_EVENT::GO_NEW_ESCAVE);
                         if (status != UVS_VANGER_STATUS::ESCAVE_SLEEPING)
                             owner -> randVRes();
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pescave);
 #endif
                         }
                     break;
                 case UVS_VANGER_STATUS::SPOT_SLEEPING:
                     if(isBunchReady() && (!Pspot -> locked)){
 //                  if(!Pspot -> locked){
                         if(Pspot -> game_soon()){
                             status = UVS_VANGER_STATUS::SPOT_WAITING;
                             break;
                         } else if (Pspot -> game_now(pg))
                             add_to_game(pg);
                         else if (shape !=  UVS_VANGER_SHAPE::THIEF && !RND(48)){
 //                      else if (shape !=  UVS_VANGER_SHAPE::THIEF && !RND(2)){
                             thief_from_spot(Pspot);
                         } else
                             Event(UVS_EVENT::GO_FROM_SPOT);
                         if (status != UVS_VANGER_STATUS::SPOT_SLEEPING)
                             owner -> randVRes();
 #ifdef _ROAD_
                         if(isActive()) addVanger(this,Pspot);
 #endif
                         }
                     break;
                 case UVS_VANGER_STATUS::MOVEMENT:
                 case UVS_VANGER_STATUS::FREE_MOVEMENT:
                 case UVS_VANGER_STATUS::RACE:
                 case UVS_VANGER_STATUS::RACE_HUNTER:
                 case UVS_VANGER_STATUS::GATHERING:
                 case UVS_VANGER_STATUS::WAIT_GAMER:
                     break;
                 case UVS_VANGER_STATUS::PASSAGE_GAP:
                     if(!--locTimer){
                         if(makeJump()){
 #ifdef _ROAD_
                             if(isActive()) addVanger(this,Ppassage);
 #endif
                             }
                         else locTimer = 1;
                         }
                     break;
                 }
             break;
         case UVS_VANGER_SHAPE::TABUTASK:
             switch(status){
             case UVS_VANGER_STATUS::SPOT_SLEEPING:
                 Event(UVS_EVENT::GO_FROM_SPOT);
                 if (status != UVS_VANGER_STATUS::SPOT_SLEEPING)
                     owner -> randVRes();
 #ifdef _ROAD_
                 if(isActive()) addVanger(this,Pspot);
 #endif
                 break;
             case UVS_VANGER_STATUS::ESCAVE_SLEEPING:
                 if(!RND(2))
                     Event(UVS_EVENT::GO_FROM_ESCAVE);
                 else
                     Event(UVS_EVENT::GO_NEW_ESCAVE);
                 if (status != UVS_VANGER_STATUS::ESCAVE_SLEEPING)
                     owner -> randVRes();
 #ifdef _ROAD_
                 if(isActive()) addVanger(this,Pescave);
 #endif
                 break;
             case UVS_VANGER_STATUS::MOVEMENT:
             case UVS_VANGER_STATUS::FREE_MOVEMENT:
                 break;
             case UVS_VANGER_STATUS::PASSAGE_GAP:
                     if(!--locTimer){
                         if(makeJump()){
 #ifdef _ROAD_
                             if(isActive()) addVanger(this,Ppassage);
 #endif
                         } else locTimer = 1;
                     }
                     break;
             };//  end switch
             break;
         case UVS_VANGER_SHAPE::KILLER:
             switch(status){
             case UVS_VANGER_STATUS::MOVEMENT:
             case UVS_VANGER_STATUS::FREE_MOVEMENT:
             case UVS_VANGER_STATUS::WAIT_GAMER:
                 break;
             case UVS_VANGER_STATUS::PASSAGE_GAP:
                     if(!--locTimer){
                         if(makeJump()){
 #ifdef _ROAD_
                             if(isActive()) addVanger(this,Ppassage);
 #endif
                         } else locTimer = 1;
                     }
                     break;
             }//  end switch
             break;
         case UVS_VANGER_SHAPE::GAMER:
             switch(status){
 #ifdef _ROAD_
             case UVS_VANGER_STATUS::GO_NEW_WORLD:
                 /*{
                     Pworld -> getItemFromCrypt(UVS_CRYPT::DEVICE);
                     Pworld -> getItemFromCrypt(UVS_CRYPT::AMMO);
                     Pworld -> getItemFromCrypt(UVS_CRYPT::ARMO_LIGHT);
                     Pworld -> getItemFromCrypt(UVS_CRYPT::ARMO_HEAVY);
                 } else {
                     Pworld -> updateCrypt();
                 }*/
                 EffectsOff();
                 Pworld -> GamerVisit++;
                 if (WorldTable[Pworld -> gIndex]-> escTmax){
                     uvsCurrentCycle = WorldTable[Pworld -> gIndex] -> escT[0] -> Pbunch -> currentStage;
                      if (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE)
                         uvsCurrentWorldUnable = 1;
                     else
                         uvsCurrentWorldUnable = 0;
                 } else {
                     uvsCurrentCycle = 0;
                     uvsCurrentWorldUnable = 0;
                 }
                 if (WorldTable[Pworld -> gIndex] -> escTmax)
                     aci_curLocationName = WorldTable[Pworld -> gIndex] -> escT[0] -> name;
                 else
                     aci_curLocationName = "";
                 ChangeWorld(Pworld -> gIndex);              // смена мира
                 addVanger(this,pos_x, pos_y,1); // человек
                 uvsWorldReload(Pworld -> gIndex);
                 if ( !Pworld -> GamerVisit ){
                     ShowDominanceMessage(10);
                     GamerResult.dominance += 10;
                     if (GamerResult.dominance > 100) GamerResult.dominance = 100;
                 }
 #ifdef STAND_REPORT
                 stand < ConTimer.GetTime();
                 stand < "\nTeleport on the World  " < Pworld -> name < "  visit " <= Pworld -> GamerVisit < "\n";
 #endif
                 status = UVS_VANGER_STATUS::MOVEMENT;
                 break;
 #endif
             case UVS_VANGER_STATUS::GO_NEW_ESCAVE:
                 Pworld -> GamerVisit++;
                 if (WorldTable[Pworld -> gIndex]-> escTmax){
                     uvsCurrentCycle = WorldTable[Pworld -> gIndex] -> escT[0] -> Pbunch -> currentStage;
                     if (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE)
                         uvsCurrentWorldUnable = 1;
                     else
                         uvsCurrentWorldUnable = 0;
                 } else {
                     uvsCurrentCycle = 0;
                     uvsCurrentWorldUnable = 0;
                 }
                 ChangeWorld(Pworld -> gIndex, 0);               // смена мира
                 if ( !Pworld -> GamerVisit ){
                     ShowDominanceMessage(10);
                     GamerResult.dominance += 10;
                     if (GamerResult.dominance > 100) GamerResult.dominance = 100;
                 }
 #ifdef STAND_REPORT
                 stand < ConTimer.GetTime();
                 stand < "\nTeleport on the World  " < Pworld -> name < "  visit " <= Pworld -> GamerVisit < "\n";
 #endif
                 status = UVS_VANGER_STATUS::SHOPPING;
                 locTimer = 1;
                 break;
             case UVS_VANGER_STATUS::MOVE_TO_MECHOS:
                     ChangeVanger();
                     addVanger(this,pos_x, pos_y,1); // человек
                     uvsWorldReload(Pworld -> gIndex);
                     status = UVS_VANGER_STATUS::MOVEMENT;
                     break;
                 case UVS_VANGER_STATUS::PASSAGE_GAP:
                     if(!--locTimer) makeJump();
                     break;
                 case UVS_VANGER_STATUS::SHOPPING:
 #ifdef _ROAD_
                     if(--locTimer) break;
                     status = UVS_VANGER_STATUS::IN_SHOP;
                     GameQuantReturnValue = RTO_ESCAVE_ID;
 #endif
                     break;
                 }
             break;
         case UVS_VANGER_SHAPE::GAMER_SLAVE:
             break;
         }
 }
References aci_curLocationName, addVanger(), UVS_VANGER_STATUS::AIM_HANDLE, UVS_VANGER_SHAPE::BUNCH_SLAVE, c_A_Number, c_All_Number, c_R_Number, c_S_Number, UVS_VANGER_SHAPE::CARAVAN, ChangeVanger(), ChangeWorld(), ConTimer, uvsGamerResult::dominance, EffectsOff(), UVS_VANGER_STATUS::ESCAVE_SLEEPING, UVS_VANGER_STATUS::ESCAVE_WAITING, UVS_VANGER_STATUS::FREE_MOVEMENT, UVS_VANGER_STATUS::GAME_BEGIN_ESCAVE, UVS_VANGER_STATUS::GAME_BEGIN_SPOT, UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_ESCAVE, UVS_VANGER_STATUS::GAME_HUNTER_BEGIN_SPOT, uvsEscave::game_now(), uvsEscave::game_soon(), GameQuantReturnValue, Gamer, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, GamerResult, uvsEscave::GamerVisit, UVS_VANGER_STATUS::GATHERING, uvsContimer::GetTime(), UVS_EVENT::GO_CIRT, UVS_EVENT::GO_FROM_ESCAVE, UVS_EVENT::GO_FROM_SPOT, UVS_VANGER_STATUS::GO_NEW_ESCAVE, UVS_EVENT::GO_NEW_ESCAVE, UVS_VANGER_STATUS::GO_NEW_WORLD, UVS_VANGER_STATUS::IN_SHOP, UVS_VANGER_SHAPE::KILLER, uvsEscave::locked, uvsEscave::may_go_away(), UVS_VANGER_STATUS::MOVE_TO_MECHOS, UVS_VANGER_STATUS::MOVEMENT, uvsEscave::name, UVS_VANGER_STATUS::PASSAGE_GAP, uvsEscave::Pbunch, uvsTarget::pos_x, uvsTarget::pos_y, uvsEscave::Pworld, UVS_VANGER_STATUS::RACE, UVS_VANGER_STATUS::RACE_HUNTER, UVS_VANGER_SHAPE::RANGER, uvsEscave::real_hunter_now(), RND(), RTO_ESCAVE_ID, UVS_VANGER_STATUS::SHOPPING, ShowDominanceMessage(), UVS_VANGER_STATUS::SPOT_SLEEPING, UVS_VANGER_STATUS::SPOT_WAITING, UVS_VANGER_SHAPE::TABUTASK, UVS_VANGER_SHAPE::THIEF, UVS_EVENT::THIEF, UVS_EVENT::THIEF_FROM_SHOP, UVS_BUNCH_STATUS::UNABLE, uvsCurrentCycle, uvsCurrentWorldUnable, uvsWorldReload(), UVS_VANGER_STATUS::WAIT_GAMER, and WorldTable.
race_result()
int uvsVanger::race_result (uvsCultGame * pg, const char * name)
{
     uvsItem* pi;
     char* nn;
     if ( (pg -> typeTownEnd == UVS_TOWN::ESCAVE && !strcmp( nn = ((uvsEscave*)(pg -> townEnd)) -> name, name))
         || ( pg -> typeTownEnd == UVS_TOWN::SPOT && !strcmp( nn = ((uvsSpot*)(pg -> townEnd)) -> name, name)) ) {
         pi = GetItem( Pitem, pg -> GoodsTypeEnd, 0 );
         int count = ItemCount( Pitem, pg -> GoodsTypeEnd);
         if ( pi ){
 #ifdef _ROAD_
             uvs_aciKillItem(uvsItemTable[ pi -> type ] -> SteelerTypeFull);
             if (pg -> typeTownEnd == UVS_TOWN::ESCAVE)
                 aciUpdateCurCredits(aciGetCurCredits() + (count-1)*((uvsEscave*)(pg -> townEnd)) -> Pshop -> Price[pg -> GoodsTypeEnd  + MAX_ITEM_TYPE]);
             else
                 aciUpdateCurCredits(aciGetCurCredits() + (count-1)*((uvsSpot*)(pg -> townEnd)) -> Pshop -> Price[pg -> GoodsTypeEnd + MAX_ITEM_TYPE]);
             uvsActInt* pa = GGamer;
             uvsActInt* pp;
             while( pa ){
                 pp = (uvsActInt*)pa -> next;
                 if (uvsItemTable[ pi -> type ] -> SteelerTypeFull == pa -> type){
                     pa -> delink(GGamer);
                     delete pa;
                 }
                 pa = pp;
             }
             while( pi ){
                 ((uvsItem*)pi) -> delink( Pitem );
                 delete pi;
                 pi = GetItem( Pitem, pg -> GoodsTypeEnd, 0 );
             }//  end while
             /*if (pg -> typeEnd)
                 aciCurCredits += (uvsItemTable[pg -> GoodsTypeEnd] -> sell_price*((uvsEscave*)(pg -> townEnd)) -> Pshop -> Price[pg -> GoodsTypeEnd])/100;
             else
                 aciCurCredits += (uvsItemTable[pg -> GoodsTypeEnd] -> sell_price*((uvsSpot*)(pg -> townEnd)) -> Pshop -> Price[pg -> GoodsTypeEnd])/100;*/
 #endif
             pg -> result++;
 #ifdef STAND_REPORT
             stand < ConTimer.GetTime();
             stand < "\t in " < nn < " with result " <= pg -> result < " <- GAMER FINISH   from " <= (pg -> total+1) < "\t" <= count < "\n";
 #endif
             uvsCheckKronIventTabuTask(UVS_KRON_EVENT::END_RACE, count, pg -> result, pg -> GoodsTypeEnd);
             if ( pg -> result == 1 ){
                 if ((pg -> total > 0) && (pg -> total - pg -> first > 0)){
                     GamerResult.luck += pg -> total - pg -> first;
                     ShowLuckMessage( pg -> total - pg -> first);
                     if (GamerResult.luck > 100) GamerResult.luck = 100;
                 }
                 pg -> first++;
             }
             if ( pg -> result <= V_RACE_VANGER ){
 #ifdef _ROAD_
                 //aciCurCredits += BONUS[pg -> result-1];
 #endif
                 if ( !strcmp( nn , "Podish") && GamerResult.get_eleech ){
                     GamerResult.last_game_type = UVS_GAME_ID::ELEECH;
                     //GamerResult.game_elr_result += GAME_RAITING[ pg -> result-1];
                     GamerResult.get_eleech = 0;
                 }else if ( !strcmp( nn , "B-Zone") )
                     GamerResult.last_game_type = UVS_GAME_ID::WEEZYK;
                     //GamerResult.game_zyk_result += GAME_RAITING[ pg -> result-1];
                 GamerResult.game_total  =  ++pg -> total;
             }//  end if
             pg -> all++;
             if (pg -> total <= pg -> result && pg -> result > 1){
                 GamerResult.luck -= 5;
                 ShowLuckMessage(-5);
                 if (GamerResult.luck < 0) GamerResult.luck = 0;
             }
             return ( pg -> result );
         } else if ( !strcmp( nn , "B-Zone") && pg -> flag){
                 GamerResult.last_game_type = UVS_GAME_ID::WEEZYK;
                 GamerResult.game_total  =  ++pg -> total;
                 return ( pg -> result );
         }//  end if (pi)
     }//  end if (pi)
     return 0;
 }
References aciGetCurCredits(), aciUpdateCurCredits(), UVS_TOWN::ESCAVE, GetItem(), GGamer, ItemCount(), MAX_ITEM_TYPE, Pitem, UVS_TOWN::SPOT, uvsElement::type, uvs_aciKillItem(), and uvsItemTable.
Referenced by game_result().
save()
void uvsVanger::save (XStream & pfile)
{
     int i, count = 0;
     pfile < gIndex;
     pfile < rating; // minimal
     pfile < status;     // состояние движения
     pfile < shape;          // принадлежность "души"
     pfile < Pworld -> gIndex;
     if(Pmechos) {
         pfile < char(1);
         Pmechos -> save(pfile);
     } else
         pfile < char(0);
     listElem *pi = Pitem;
     count = 0;
     while( pi ){
         count++;
         pi = pi -> next;
     }
     pfile < count;
     pi = Pitem;
     for( i = 0; i < count; i++){
         ((uvsItem*)pi) -> save(pfile);
         pi = pi -> next;
     }
     if(owner) put_string(pfile,  owner -> Pescave -> name); else pfile < ((char)0);
     if(Pescave) put_string(pfile,  Pescave -> name); else pfile < ((char)0);
     if(Pspot) put_string(pfile,  Pspot -> name);  else pfile < ((char)0);
     if(Ppassage) put_string(pfile,  Ppassage -> name);  else pfile < ((char)0);
     pfile < pos_x;
     pfile < pos_y;
     pfile < biosNindex;                 // bios случайный
     for ( i = 0; i < ORDER_V_MAX; i++){
         pfile < orderT[i].type;
         pfile < orderT[i].event;
         pfile < orderT[i].target;
         switch(orderT[i].target) {
         case UVS_TARGET::NONE:
             pfile < ((char)0);
             break;
         case UVS_TARGET::PASSAGE:
             put_string(pfile,  ((uvsPassage*)(orderT[i].Ptarget)) -> name );
             break;
         case UVS_TARGET::ESCAVE:
             put_string(pfile,  ((uvsEscave*)(orderT[i].Ptarget)) -> name);
             break;
         case UVS_TARGET::SPOT:
             put_string(pfile,  ((uvsSpot*)(orderT[i].Ptarget)) -> name);
             break;
         case UVS_TARGET::DOLLY:
             pfile < ((char)0);
             pfile < (((uvsDolly*)(orderT[i].Ptarget)) -> gIndex);
             break;
         case UVS_TARGET::VANGER:
             pfile < ((char)0);
             if (shape == UVS_VANGER_SHAPE::GAMER)
                 pfile < (((uvsVanger*)(orderT[i].Ptarget)) -> gIndex);
             break;
         case UVS_TARGET::ITEM:
             pfile < ((char)0);
             break;
         case UVS_TARGET::FLY_FARMER:
             pfile < ((char)0);
             break;
         }//  end switch
     }//  end for i
     pfile < speed;
 //  pfile < cirtStage < cirtQ;
 }
References gIndex, Pitem, Pmechos, Pworld, rating, shape, and status.
sell_move_Item()
void uvsVanger::sell_move_Item (uvsShop * ps, int where)
{
     uvsItem* pi = NULL;
     if ( ps -> locked ) return;
     if (where)
         pi = GetItem_as_type( Pitem,  UVS_ITEM_STATUS::MECHOS_PART);
     if ( !pi ) pi = GetItem_as_type( Pitem,  UVS_ITEM_STATUS::ARTIFACT);
     if ( !pi ){
         pi = GetItem_as_type( Pitem,  UVS_ITEM_STATUS::MECHOS_PART);
         if (!pi)
             shape = UVS_VANGER_SHAPE::RANGER;
         return;
     }
     ((uvsItem*)pi) -> delink(  Pitem );
     ps -> addItem(pi);
     pi = GetItem_as_type( Pitem,  UVS_ITEM_STATUS::MECHOS_PART);
     if ( !pi ) pi = GetItem_as_type( Pitem,  UVS_ITEM_STATUS::ARTIFACT);
     if ( !pi )  shape = UVS_VANGER_SHAPE::RANGER;
 }
References UVS_ITEM_STATUS::ARTIFACT, GetItem_as_type(), uvsEscave::locked, UVS_ITEM_STATUS::MECHOS_PART, NULL, uvsEscave::Pitem, and UVS_VANGER_SHAPE::RANGER.
sell_treasure_Item()
void uvsVanger::sell_treasure_Item (uvsShop * ps)
{
     if ( ps -> locked ) return;
     uvsItem* pi = GetItem_as_type( Pitem,  UVS_ITEM_STATUS::TREASURE);
     if ( !pi )  {
         shape = UVS_VANGER_SHAPE::RANGER;
         return;
     }
     ((uvsItem*)pi) -> delink(  Pitem );
     ps -> addItem(pi);
     if ( !GetItem_as_type( Pitem,  UVS_ITEM_STATUS::TREASURE) ) shape = UVS_VANGER_SHAPE::RANGER;
 }
References GetItem_as_type(), uvsEscave::locked, uvsEscave::Pitem, UVS_VANGER_SHAPE::RANGER, and UVS_ITEM_STATUS::TREASURE.
sellCirt()
int uvsVanger::sellCirt (void)
{
     int  i = 0;
     int have_full = 0;
     int tmp_good = 0;
     int tmp_bad = 0;
     int tmp_total_good = 0;
     int tmp_total_bad = 0;
     int last_param2;
     int cool_index = 0;
     uvsActInt* pa = GGamer;
     uvsItem *pi;
     uvsBunch *pb = Pescave -> Pbunch;
     pi = GetItem(Pitem, UVS_ITEM_TYPE::CIRTAINER, 0);
     GamerResult.cirt_bad = -1;
     GamerResult.cirt_good = -1;
     while( pi ){
         tmp_good = 0;
         tmp_bad = 0;
         last_param2  = pi -> param2;
         if (pi -> param2){
             have_full = 1;
             for ( i = 0; i < pb -> cycleN; i++){
                 //if( ((1 << (pb -> cycleTable[i].Pdolly -> gIndex)) & pi -> param2) && ((pi -> param1 >> (pb -> cycleTable[i].Pdolly -> gIndex*2)) & 3)) {
                 if( ((1 << (pb -> cycleTable[i].Pdolly -> gIndex)) & last_param2)) {
                     if (tmp_good < ((pi -> param1 >> (pb -> cycleTable[i].Pdolly -> gIndex*3)) & 7)){
                         tmp_good = ((pi -> param1 >> (pb -> cycleTable[i].Pdolly -> gIndex*3)) & 7);
                         cool_index = pb -> cycleTable[i].Pdolly -> gIndex;
                     }
                     last_param2 ^= (1 << (pb -> cycleTable[i].Pdolly -> gIndex));
                 }
             }//  end for j
             if (last_param2)
                 for ( i = 1; i < DollyIndex; i++){
                     if( (1 << i) & last_param2) {
                         if ( tmp_bad < ((pi -> param1 >> (i*3)) & 7)  )
                             tmp_bad =  ((pi -> param1 >> (i*3)) & 7);
                     }
                 }
             if (tmp_good >= tmp_bad && tmp_good > 0 && !dgAbortStatus ){
                 tmp_good = 0;
     //          if(cool_index == -1) ErrH.Abort("uvsVanger::sellCirt - good cirt not found but it have");
                 if ( cool_index == pb -> cycleTable[pb -> currentStage].Pdolly -> gIndex ){
                         tmp_good += 2*((pi -> param1 >> (cool_index*3)) & 7);
                 } else {
                         tmp_good += ((pi -> param1 >> (cool_index*3)) & 7);
                 }
                 for ( i = 0; i < pb -> cycleN; i++)
                     if ( cool_index == pb -> cycleTable[i].Pdolly -> gIndex ) break;
                 pb -> cycleTable[i].cirtQ += (((pi -> param1 >> (cool_index*3)) & 7));
                 if (pb -> cycleTable[i].cirtQ >= pb -> cycleTable[i].cirtMAX){
                     uvsCheckKronIventTabuTask(UVS_KRON_EVENT::END_CYCLE, i+1);
                 }
                 pb -> cycleTable[i].GamerCirt += (((pi -> param1 >> (cool_index*3)) & 7));
                 tmp_total_good += tmp_good;
                 uvs_aciChangeOneItem(uvsItemTable[UVS_ITEM_TYPE::CIRTAINER] -> SteelerTypeFull, uvsItemTable[UVS_ITEM_TYPE::CIRTAINER] -> SteelerTypeEmpty, pi -> pos_x, pi -> pos_y);
                 pa = GGamer;
                 while( pa && ((pi -> pos_x != pa -> pos_x) || (pi -> pos_y != pa -> pos_y))){
                     pa = (uvsActInt*)pa -> next;
                 }
                 if (pa){
                     pa -> type = ACI_EMPTY_CIRTAINER;
                     pa -> param1 = 0;
                     pa -> param2 = 0;
                 }
                 pi -> param1 = 0;
                 pi -> param2 = 0;
             } else {
                 tmp_total_bad += tmp_bad;
                 if (tmp_bad > 0)
                     uvsCheckKronIventTabuTask(UVS_KRON_EVENT::BAD_CIRT, tmp_bad);
             }
         }
         pi = GetItem(pi->next, UVS_ITEM_TYPE::CIRTAINER, 0 );
     }
 #ifdef _ROAD_
     if (have_full){
         GamerResult.cirt_good = tmp_total_good;
         GamerResult.cirt_bad = tmp_total_bad;
     }
 #ifdef STAND_REPORT
     stand < "cirt good "<= GamerResult.cirt_good < "  cirt bad " <= GamerResult.cirt_bad < "\n";
 #endif
 #endif
     if (GamerResult.cirt_good > 0)
         return GamerResult.cirt_good;
     else
         return 0;
 }
References uvsGamerResult::cirt_bad, uvsGamerResult::cirt_good, UVS_ITEM_TYPE::CIRTAINER, GamerResult, GetItem(), GGamer, uvsEscave::Pbunch, and uvsEscave::Pitem.
set_target()
void uvsVanger::set_target (uvsTarget * pt, int _type)
{
     uvsOrder* ord = orderT;         // первый элемент
     switch(_type){
         case UVS_TARGET::ESCAVE:
             ord -> type = UVS_ORDER::MOVING;
             ord -> event = UVS_EVENT::GO_ESCAVE;
             ord -> target = _type;
             ord -> Ptarget = pt;
             status = UVS_VANGER_STATUS::MOVEMENT;
             break;
         case UVS_TARGET::SPOT:
             ord -> type = UVS_ORDER::MOVING;
             ord -> event = UVS_EVENT::GO_SPOT;
             ord -> target = _type;
             ord -> Ptarget = pt;
             status = UVS_VANGER_STATUS::MOVEMENT;
             break;
         case UVS_TARGET::VANGER:
             ord -> type = UVS_ORDER::MOVING;
             ord -> event = UVS_EVENT::GO_KILL;
             ord -> target = _type;
             ord -> Ptarget = pt;
             status = UVS_VANGER_STATUS::MOVEMENT;
             break;
         case UVS_TARGET::VANGERS:
         case UVS_TARGET::PASSAGE:
         case UVS_TARGET::DOLLY:
         case UVS_TARGET::ITEM:
         case UVS_TARGET::BEEB:
         case UVS_TARGET::GRIB:
         case UVS_TARGET::HIVE:
         case UVS_TARGET::CRYPT:
         case UVS_TARGET::WHIRLPOOL:
         case UVS_TARGET::SWAMP:
         case UVS_TARGET::SHEILD:
         case UVS_TARGET::NONE:
             ErrH.Abort("uvsVanger::set_target : go nothing");
             break;
         case UVS_TARGET::FLY_FARMER:
             ord -> type = UVS_ORDER::MOVING;
             ord -> event = UVS_EVENT::GO_CORN;
             ord -> target = _type;
             ord -> Ptarget = pt;
             status = UVS_VANGER_STATUS::GATHERING;
             break;
     }
 }
References XErrorHandler::Abort(), UVS_TARGET::BEEB, UVS_TARGET::CRYPT, UVS_TARGET::DOLLY, ErrH, UVS_TARGET::ESCAVE, UVS_TARGET::FLY_FARMER, UVS_VANGER_STATUS::GATHERING, UVS_EVENT::GO_CORN, UVS_EVENT::GO_ESCAVE, UVS_EVENT::GO_KILL, UVS_EVENT::GO_SPOT, UVS_TARGET::GRIB, UVS_TARGET::HIVE, UVS_TARGET::ITEM, UVS_VANGER_STATUS::MOVEMENT, UVS_ORDER::MOVING, UVS_TARGET::NONE, orderT, UVS_TARGET::PASSAGE, UVS_TARGET::SHEILD, UVS_TARGET::SPOT, status, UVS_TARGET::SWAMP, uvsElement::type, UVS_TARGET::VANGER, UVS_TARGET::VANGERS, and UVS_TARGET::WHIRLPOOL.
Referenced by break_harvest().
shiftOrders()
void uvsVanger::shiftOrders (void)
{
     if(shape == UVS_VANGER_SHAPE::GAMER || NetworkON) return;
     uvsOrder* ord = orderT;
     switch ( orderT -> target ){
     case UVS_TARGET::NONE:
         ErrH.Abort("uvsVanger::shift order none");
         break;
     case UVS_TARGET::ESCAVE:
         Pescave = (uvsEscave*)(orderT -> Ptarget);
         break;
     case UVS_TARGET::SPOT:
         Pspot = (uvsSpot*)(orderT -> Ptarget);
         break;
     case UVS_TARGET::PASSAGE:
         Ppassage = (uvsPassage*)(orderT -> Ptarget);
         break;
     case UVS_TARGET::VANGER:
         break;
     case UVS_TARGET::ITEM:
         break;
     }//  end swith
     for(int i = 1;i < ORDER_V_MAX; i++){;
         orderT[i - 1].type = orderT[i].type;
         orderT[i - 1].event = orderT[i].event;
         orderT[i - 1].target = orderT[i].target;
         orderT[i - 1].Ptarget = orderT[i].Ptarget;
     }
     ord = orderT + ORDER_V_MAX - 1;
     ord -> type = UVS_ORDER::NONE;
     ord -> target = UVS_TARGET::NONE;
     ord -> Ptarget = NULL;
 }
References XErrorHandler::Abort(), ErrH, UVS_TARGET::ESCAVE, UVS_VANGER_SHAPE::GAMER, UVS_TARGET::ITEM, NetworkON, UVS_TARGET::NONE, UVS_ORDER::NONE, NULL, ORDER_V_MAX, UVS_TARGET::PASSAGE, UVS_TARGET::SPOT, and UVS_TARGET::VANGER.
spotArrival()
void uvsVanger::spotArrival ()
{
     uvsCheckVangerTabuTask(this,uvsVANGER_ARRIVAL);
     Pescave =  NULL;
     switch(shape){
         case UVS_VANGER_SHAPE::TABUTASK:
             FreeList(Pitem);
             break;
         case UVS_VANGER_SHAPE::BUNCH_SLAVE:
             changeRating( Pspot -> bring_game_GOODS(Pitem) );
             if (RND(2))
                 Pspot->Pshop->updateList(Pitem);
             FreeList(Pitem);
             break;
         case UVS_VANGER_SHAPE::CARAVAN:
             changeRating( Pspot -> bring_game_GOODS(Pitem) );
             if ( !RND(10) ){
                 sell_move_Item( Pspot -> Pshop, 1);
             }
             break;
         case UVS_VANGER_SHAPE::RANGER:
             changeRating( Pspot -> bring_game_GOODS(Pitem) );
             Pspot->Pshop->updateList(Pitem);
             FreeList(Pitem);
             break;
         case UVS_VANGER_SHAPE::THIEF:
             changeRating( Pspot -> bring_game_GOODS(Pitem) );
             if ( !RND(10) ){
                 sell_treasure_Item( Pspot -> Pshop);
             }
             break;
         case UVS_VANGER_SHAPE::GAMER:
 #ifdef _ROAD_
             status = UVS_VANGER_STATUS::SHOPPING;
             locTimer = LOC_TIME;
             if ( !Pspot -> GamerVisit ){
                 GamerResult.dominance += 2;
                 ShowDominanceMessage(2);
                 if (GamerResult.dominance > 100) GamerResult.dominance = 100;
             }
             Pspot -> GamerVisit++;
 #endif
             break;
         }
 }
References uvsEscave::bring_game_GOODS(), UVS_VANGER_SHAPE::BUNCH_SLAVE, UVS_VANGER_SHAPE::CARAVAN, uvsGamerResult::dominance, FreeList(), UVS_VANGER_SHAPE::GAMER, GamerResult, uvsEscave::GamerVisit, LOC_TIME, NULL, uvsEscave::Pitem, uvsEscave::Pshop, UVS_VANGER_SHAPE::RANGER, RND(), UVS_VANGER_STATUS::SHOPPING, ShowDominanceMessage(), UVS_VANGER_SHAPE::TABUTASK, UVS_VANGER_SHAPE::THIEF, uvsCheckVangerTabuTask(), and uvsVANGER_ARRIVAL.
start_race()
void uvsVanger::start_race (void)
{
     if (Pworld -> escTmax){
         uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
         uvsCultGame* pg = pb -> cycleTable[pb -> currentStage].Pgame;
         if (pg){
             if(pg -> GameType == UVS_GAME_TYPE::RACE && !pg -> start){
                 if (!GamerResult.get_weezyk && pg -> GoodsTypeBeg == UVS_ITEM_TYPE::WEEZYK)
                     pg -> GoodsBegCount = 1;
                 pg -> start = 1;
             }
         }//  end if pg
     }//  end if Pworld
 }
References GamerResult, uvsGamerResult::get_weezyk, uvsEscave::Pbunch, uvsEscave::Pworld, UVS_GAME_TYPE::RACE, and UVS_ITEM_TYPE::WEEZYK.
thief_from_escave()
void uvsVanger::thief_from_escave (uvsEscave * pe)
{
     uvsItem* pi;
     if (!strcmp(pe -> Pworld -> name, "Glorx")) return;
     if ( !(Pmechos -> status & UVS_MECHOS_USED::CARAVAN) ) return;
     pi = (uvsItem*)(pe -> Pitem);
     if ( !pi || pi -> param1) return;
     pi -> param1 = uvsTreasureThief;
     pi = new uvsItem( ((uvsItem*)pi) -> type);
     pi -> param2 = Pworld -> gIndex;
     if ( !addItem( pi, 1 ) ) ErrH.Abort("uvsVanger::thief_from_escave");
 #ifdef STAND_REPORT
     stand < "thief from " < pe -> name < "\n";
 #endif
     shape = UVS_VANGER_SHAPE::THIEF;
     //go_from_escave();
     goNewEscave();
     //Event(UVS_EVENT::GO_NEW_ESCAVE);
 }
References XErrorHandler::Abort(), UVS_MECHOS_USED::CARAVAN, ErrH, uvsEscave::name, uvsEscave::Pitem, uvsEscave::Pworld, UVS_VANGER_SHAPE::THIEF, and uvsTreasureThief.
thief_from_shop()
void uvsVanger::thief_from_shop (uvsShop * ps)
{
     uvsItem* pi;
     if ( ps -> locked ) return;
     if ( !(Pmechos -> status & UVS_MECHOS_USED::CARAVAN) ) return;
     pi = GetItem_as_type( ps -> Pitem,  UVS_ITEM_STATUS::TREASURE);
     if ( !pi ) return;
     listElem* tmp = (listElem*)ps -> Pitem;
     //((uvsItem*)pi) -> delink( tmp );
     pi->delink( tmp );
     if ( !addItem( pi, 1 ) ) ErrH.Abort("uvsVanger::thief_from_shop");
     shape = UVS_VANGER_SHAPE::THIEF;
     goNewEscave();
     //Event(UVS_EVENT::GO_NEW_ESCAVE);
 }
References XErrorHandler::Abort(), UVS_MECHOS_USED::CARAVAN, uvsItem::delink(), ErrH, GetItem_as_type(), uvsEscave::locked, uvsEscave::Pitem, UVS_VANGER_SHAPE::THIEF, and UVS_ITEM_STATUS::TREASURE.
thief_from_spot()
void uvsVanger::thief_from_spot (uvsSpot * ps)
{
     uvsItem* pi;
     if ( !(Pmechos -> status & UVS_MECHOS_USED::CARAVAN) ) return;
     pi = (uvsItem*)(ps -> Pitem);
     if ( !pi || pi -> param1 ) return;
     pi -> param1 = uvsTreasureThief;
     pi = new uvsItem( ((uvsItem*)pi) -> type);
     pi -> param2 = Pworld -> gIndex;
     if ( !addItem( pi, 1 ) ) ErrH.Abort("uvsVanger::thief_from_escave");
 #ifdef STAND_REPORT
     stand < "thief from " < ps -> name < "\n";
 #endif
     shape = UVS_VANGER_SHAPE::THIEF;
     //go_from_escave();
     goNewEscave();
     //Event(UVS_EVENT::GO_NEW_ESCAVE);
 }
References XErrorHandler::Abort(), UVS_MECHOS_USED::CARAVAN, ErrH, uvsEscave::name, uvsEscave::Pitem, uvsEscave::Pworld, UVS_VANGER_SHAPE::THIEF, and uvsTreasureThief.
update()
void uvsVanger::update (int x, int y)
{
     pos_x = x;
     pos_y = y;
 }
References uvsTarget::pos_x, and uvsTarget::pos_y.
Referenced by VangerUnit::Quant().
UpdateAllTarget()
void uvsVanger::UpdateAllTarget (void)
{
     for ( int i = 0; i < ORDER_V_MAX; i++){
         switch (orderT[i].target){
         case UVS_TARGET::FLY_FARMER:
             break;
         case UVS_TARGET::NONE:
             break;
         case UVS_TARGET::PASSAGE:
             break;
         case UVS_TARGET::ESCAVE:
             break;
         case UVS_TARGET::SPOT:
             break;
         case UVS_TARGET::DOLLY:
             break;
         case UVS_TARGET::VANGER:{
             if (shape != UVS_VANGER_SHAPE::GAMER) ErrH.Abort("uvsVanger :: load - target vanger not in Gamer");
             uvsElement* p = ETail;
             uvsVanger* v;
             while(p){
                 if(p -> type == UVS_OBJECT::VANGER){
                     v = (uvsVanger*)p;
                     if(v -> gIndex == gIndex ) {
                         orderT[i].Ptarget = (uvsTarget*)v;
                         break;
                     }//  end if
                 }//  end if
                 p = p -> enext;
             }//  end while
             if (!p) ErrH.Abort("UpDateAllTarger - dont find target");
             gIndex = 0;
         }
             break;
         case UVS_TARGET::ITEM:
             break;
         }//  end switch
     }//  end for
 }
References XErrorHandler::Abort(), UVS_TARGET::DOLLY, uvsElement::enext, ErrH, UVS_TARGET::ESCAVE, ETail, UVS_TARGET::FLY_FARMER, UVS_VANGER_SHAPE::GAMER, gIndex, UVS_TARGET::ITEM, UVS_TARGET::NONE, ORDER_V_MAX, orderT, UVS_TARGET::PASSAGE, uvsOrder::Ptarget, shape, UVS_TARGET::SPOT, uvsElement::type, UVS_OBJECT::VANGER, and UVS_TARGET::VANGER.
Member Data Documentation
biosNindex
int uvsVanger::biosNindex
Referenced by uvsVanger().
gIndex
int uvsVanger::gIndex
Referenced by addGOODS(), save(), UpdateAllTarget(), and uvsVanger().
locTimer
int uvsVanger::locTimer
Referenced by uvsVanger().
orderT
uvsOrder* uvsVanger::orderT
Referenced by add_to_race(), set_target(), UpdateAllTarget(), and uvsVanger().
owner
uvsBunch* uvsVanger::owner
Referenced by isBunchReady(), and uvsVanger().
Pescave
uvsEscave* uvsVanger::Pescave
Referenced by add_to_game(), addGOODS(), addInventory(), break_harvest(), get_list_from_ActInt(), prepare_list_for_ActInt(), uvsRestoreVanger(), and uvsVanger().
Pitem
listElem* uvsVanger::Pitem
Referenced by addItem(), uvsEscave::arrest(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), harvest_result(), VangerUnit::InCarNator(), VangerUnit::OutCarNator(), prepare_list_for_ActInt(), race_result(), save(), and uvsVanger().
Pmechos
uvsMechos* uvsVanger::Pmechos
Referenced by add_to_race(), addInventory(), addVanger(), VangerUnit::BulletCollision(), VangerUnit::ChangeVangerProcess(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), VangerUnit::DestroyCollision(), GunDevice::DeviceIn(), getObjectPosition(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), VangerUnit::InitEnvironment(), VangerUnit::NetCreateVanger(), ObjectDestroy(), prepare_list_for_ActInt(), GameObjectDispatcher::Quant(), save(), VangerUnit::ShellNetEvent(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), and uvsVanger().
Ppassage
uvsPassage* uvsVanger::Ppassage
Referenced by uvsUnitType::CreateUnitType(), and uvsVanger().
Pspot
uvsSpot* uvsVanger::Pspot
Referenced by add_to_game(), addGOODS(), addInventory(), break_harvest(), get_list_from_ActInt(), prepare_list_for_ActInt(), uvsRestoreVanger(), and uvsVanger().
Pworld
uvsWorld* uvsVanger::Pworld
Referenced by addGOODS(), break_harvest(), game_result(), VangerUnit::Go2Universe(), prepare_list_for_ActInt(), ActionDispatcher::Quant(), save(), VangerUnit::SensorQuant(), uvsGetLarvaWorld(), and uvsVanger().
rating
int uvsVanger::rating
Referenced by save(), and uvsVanger().
shape
UvsVangerShapeType uvsVanger::shape
Referenced by add_to_race(), addInventory(), VangerUnit::Go2Universe(), VangerUnit::InitAI(), ObjectDestroy(), GameObjectDispatcher::Quant(), save(), UpdateAllTarget(), and uvsVanger().
speed
int uvsVanger::speed
Referenced by uvsVanger().
status
UvsVangerStatusType uvsVanger::status
Referenced by add_to_race(), VangerUnit::InitAI(), VangerUnit::InitPlayerPoint(), prepare_list_for_ActInt(), VangerUnit::Quant(), save(), set_target(), and uvsVanger().
The documentation for this struct was generated from the following files:
src/uvs/univang.h
src/uvs/univang.cpp