Vangers: SignPlayEngine Struct Reference
SignPlayEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Quant (void)
void Touch (GeneralObject *obj, SensorDataType *p)
void Close (void)
Public Member Functions inherited from LocationEngine
virtual void Link (void)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
int NumSensor
SensorDataType ** SensorLink
int Time
int LockFlag
int ReplayCount
int NumReplay
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Close()
void SignPlayEngine::Close (void) virtual
Reimplemented from LocationEngine.
 {
     delete SensorLink;
 };
References SensorLink.
Open()
void SignPlayEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     char* n;
     int i;
     LocationEngine::Open(in);
     in.search_name("NumSensorLink");
     NumSensor = in.get_int();
     SensorLink = new SensorDataType*[NumSensor];
     for(i = 0;i < NumSensor;i++){
         in.search_name("SensorName");
         n = in.get_name();
         SensorLink[i] = NULL;
         SensorLink[i] = FindSensor(n);
         if(!SensorLink[i])
             ErrH.Abort("Bad Find Sensor");
         SensorLink[i]->Enable = 1;
         SensorLink[i]->Owner = this;
     };
     in.search_name("NumReplay");
     NumReplay = in.get_int();
     ReplayCount = 0;
     Type = EngineTypeList::SIGN_PLAY;
     Mode = EngineModeList::WAIT;
     Time = 0;
     MLLink->goKeyPhase(DeactivePhase);
 };
References XErrorHandler::Abort(), LocationEngine::DeactivePhase, StaticObject::Enable, ErrH, FindSensor(), Parser::get_int(), Parser::get_name(), MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, NULL, NumReplay, NumSensor, LocationEngine::Open(), SensorDataType::Owner, ReplayCount, Parser::search_name(), SensorLink, EngineTypeList::SIGN_PLAY, Time, LocationEngine::Type, and EngineModeList::WAIT.
Quant()
void SignPlayEngine::Quant (void) virtual
Reimplemented from LocationEngine.
 {
     if(!MLLink) return;
     if(!MLLink->frozen){
         if(Mode == EngineModeList::OPEN && MLLink->isGoFinish()){
             if(ReplayCount >= NumReplay)
                 Mode = EngineModeList::WAIT;
             else{
                 if(Time > 0) Time--;
                 else{
                     if(ReplayCount & 1){
                         MLLink->goKeyPhase(ActivePhase);
                         Time = ActiveTime;
                         SoundEvent();
                     }else{
                         MLLink->goKeyPhase(DeactivePhase);
                         Time = DeactiveTime;
                         SoundEvent();
                     };
                     ReplayCount++;
                 };
             };
         };
     }else{
         if(Mode != EngineModeList::WAIT)
             MLLink->goKeyPhase(DeactivePhase);
         Mode = EngineModeList::WAIT;
         Time = 0;
     };
 };
References LocationEngine::ActivePhase, LocationEngine::ActiveTime, LocationEngine::DeactivePhase, LocationEngine::DeactiveTime, MobileLocation::frozen, MobileLocation::goKeyPhase(), MobileLocation::isGoFinish(), LocationEngine::MLLink, LocationEngine::Mode, NumReplay, EngineModeList::OPEN, ReplayCount, LocationEngine::SoundEvent(), Time, and EngineModeList::WAIT.
Touch()
void SignPlayEngine::Touch (GeneralObject * obj, SensorDataType * p) virtual
Reimplemented from LocationEngine.
 {
     if(!Enable || !MLLink) return;
     if(!MLLink->frozen && Mode != EngineModeList::OPEN){
         Mode = EngineModeList::OPEN;
         MLLink->goKeyPhase(ActivePhase);
         ReplayCount = 0;
         Time = ActivePhase;
     };
 };
References LocationEngine::ActivePhase, LocationEngine::Enable, MobileLocation::frozen, MobileLocation::goKeyPhase(), LocationEngine::MLLink, LocationEngine::Mode, EngineModeList::OPEN, ReplayCount, and Time.
Member Data Documentation
LockFlag
int SignPlayEngine::LockFlag
NumReplay
int SignPlayEngine::NumReplay
Referenced by Open(), and Quant().
NumSensor
int SignPlayEngine::NumSensor
Referenced by Open().
ReplayCount
int SignPlayEngine::ReplayCount
Referenced by Open(), Quant(), and Touch().
SensorLink
SensorDataType** SignPlayEngine::SensorLink
Referenced by Close(), and Open().
Time
int SignPlayEngine::Time
Referenced by Open(), Quant(), and Touch().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp