Vangers: LoadingRTO1 Struct Reference
LoadingRTO1 Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
virtual void Finit (void)
LoadingRTO1 (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Additional Inherited Members
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
LoadingRTO1()
LoadingRTO1::LoadingRTO1 (void) inline
 { ID = RTO_LOADING1_ID; Timer = 1; }
References XRuntimeObject::ID, RTO_LOADING1_ID, and XRuntimeObject::Timer.
Member Function Documentation
Finit()
void LoadingRTO1::Finit (void) virtual
Reimplemented from XRuntimeObject.
 {
     ClearFlag(RTO_ALL_FLAGS);
 _MEM_STATISTIC_("AFTER LOADING RTO1 FINIT -> ");
 }
References _MEM_STATISTIC_, BaseRTO::ClearFlag(), and RTO_ALL_FLAGS.
Init()
void LoadingRTO1::Init (int id) virtual
Reimplemented from XRuntimeObject.
 {
     RAM16 = 0;//iGetOptionValue(iDETAIL_SETTING);
     if(!MuteLog && EffectInUsePriory){
         if(!iGetOptionValue(iSOUND_ON)){
             SetSoundVolume(iGetOptionValue(iSOUND_VOLUME_CUR)*256/iGetOptionValue(iSOUND_VOLUME_MAX));
         } else {
             MuteLog = 1; EffectInUsePriory = EffectInUse = 0;
         }
     }
     if(!(flags & RTO_INIT_FLAG)){
         uniVangPrepare();
         uvsCreateItem_in_Crypt();
     }
 #ifdef ACTINT
 #ifndef ISCREEN
     aKeyInit();
 #endif
     aInit();
 #endif
 #ifdef ACTINT
     XSIDE = aScrDisp -> curIbs -> SideX;
     YSIDE = aScrDisp -> curIbs -> SideY;
     XSIZE = 2*XSIDE;
     YSIZE = 2*YSIDE;
 #else
     XSIDE = (XGR_MAXX)/2 - 4;
     YSIDE = (XGR_MAXY)/2 - 4;
     XSIZE = 2*XSIDE;
     YSIZE = 2*YSIDE;
 #endif
     set_key_nadlers(&KeyCenter, NULL);
     graph3d_init();
     GeneralSystemInit();
 //  palTr -> set(iscrPal,palbufInt,0,255,&Quit);
     palTr -> set(iscrPal,NULL,0,255,&Quit);
     Quit = 1;
     while(Quit){
         palTr -> quant();
         SDL_Delay(10);
     }
     LoadingMessage(1);
     diagenPrepare();
 _MEM_STATISTIC_("AFTER LOADING RTO1 INIT -> ");
 }
References _MEM_STATISTIC_, aInit(), aKeyInit(), aScrDisp, diagenPrepare(), EffectInUse, EffectInUsePriory, BaseRTO::flags, GeneralSystemInit(), graph3d_init(), iGetOptionValue(), iscrPal, iSOUND_ON, iSOUND_VOLUME_CUR, iSOUND_VOLUME_MAX, KeyCenter(), LoadingMessage(), MuteLog, NULL, palTr, Quit, RAM16, RTO_INIT_FLAG, set(), set_key_nadlers(), SetSoundVolume(), uniVangPrepare(), uvsCreateItem_in_Crypt(), XGR_MAXX, XGR_MAXY, XSIDE, XSIZE, YSIDE, and YSIZE.
Quant()
int LoadingRTO1::Quant (void) virtual
Reimplemented from XRuntimeObject.
 {
     //XGR_Flip();
     if(!(flags & RTO_QUANT_FLAG)){
         SetFlag(RTO_QUANT_FLAG);
         return 0;
     }
 #ifdef ISCREEN
     return NextID;
 #else
     return RTO_LOADING2_ID;
 #endif
 }
References BaseRTO::flags, BaseRTO::NextID, RTO_LOADING2_ID, RTO_QUANT_FLAG, and BaseRTO::SetFlag().
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp