Vangers: XStream Struct Reference
XStream Struct Reference
#include <xstream.h>
Public Types
typedef std::fstream * XSHANDLE
Public Member Functions
XStream (int err=1)
XStream (const char *name, unsigned flags, int err=1)
~XStream ()
int open (const char *name, unsigned f=XS_IN)
int open (XStream *owner, long start, long ext_sz=-1)
void close ()
unsigned long read (void *buf, unsigned long len)
unsigned long write (const void *buf, unsigned long len)
long seek (long offset, int dir)
long tell () const
char * getline (char *buf, unsigned len)
int eof ()
long size ()
XSHANDLE gethandler ()
void flush ()
const char * GetFileName () const
void SetRadix (int r)
void SetDigits (int d)
XStream & operator< (const char *)
XStream & operator< (char)
XStream & operator< (unsigned char)
XStream & operator< (short)
XStream & operator< (unsigned short)
XStream & operator< (int)
XStream & operator< (unsigned int)
XStream & operator< (long)
XStream & operator< (unsigned long)
XStream & operator< (float)
XStream & operator< (double)
XStream & operator< (long double)
XStream & operator> (char *)
XStream & operator> (char &)
XStream & operator> (unsigned char &)
XStream & operator> (short &)
XStream & operator> (unsigned short &)
XStream & operator> (int &)
XStream & operator> (unsigned int &)
XStream & operator> (long &)
XStream & operator> (unsigned long &)
XStream & operator> (float &)
XStream & operator> (double &)
XStream & operator> (long double &)
XStream & operator<= (char)
XStream & operator<= (unsigned char)
XStream & operator<= (short)
XStream & operator<= (unsigned short)
XStream & operator<= (int)
XStream & operator<= (unsigned int)
XStream & operator<= (long)
XStream & operator<= (unsigned long)
XStream & operator<= (float)
XStream & operator<= (double)
XStream & operator<= (long double)
XStream & operator>= (char &)
XStream & operator>= (unsigned char &)
XStream & operator>= (short &)
XStream & operator>= (unsigned short &)
XStream & operator>= (int &)
XStream & operator>= (unsigned int &)
XStream & operator>= (long &)
XStream & operator>= (unsigned long &)
XStream & operator>= (float &)
XStream & operator>= (double &)
XStream & operator>= (long double &)
int operator! ()
operator void * ()
template<class T >
XStream & write (const T &v)
template<class T >
XStream & read (T &v)
Public Attributes
XSHANDLE handler
long pos
int eofFlag
int ErrHUsed
std::string fname
int radix
int digits
long extSize
long extPos
std::string file_name
char _ConvertBuffer [_CONV_BUFFER_LEN+1]
Detailed Description
Member Typedef Documentation
XSHANDLE
typedef std::fstream* XStream::XSHANDLE
Constructor & Destructor Documentation
XStream() [1/2]
XStream::XStream (int err = 1)
 {
     ErrHUsed = err;
     handler  = NULL;
     eofFlag  = 1;
     radix    = XS_DEFRADIX;
     digits   = XS_DEFDIGITS;
     extSize  = -1;
     extPos   = 0;
 }
References digits, eofFlag, ErrHUsed, extPos, extSize, handler, NULL, radix, XS_DEFDIGITS, and XS_DEFRADIX.
XStream() [2/2]
XStream::XStream (const char * name, unsigned flags, int err = 1) inline
{
         ErrHUsed = err;
         handler  = NULL;//(XSHANDLE)-1;
         eofFlag  = 1;
         radix    = XS_DEFRADIX;
         digits   = XS_DEFDIGITS;
         extSize  = -1;
         extPos   = 0;
         open(name,flags);
     }
~XStream()
XStream::~XStream ()
 {
     close();
 }
References close().
Member Function Documentation
close()
void XStream::close (void)
 {
     if(handler == NULL)
         return;
     //std::cout<<"XStream::close: "<<fname<<std::endl;
     /* Full stream debug
     std::fstream debug("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open()&&fname!=NULL)
         debug<<"CLOSE "<<fname<<std::endl;
     debug.close();
     */
     //if(extSize == -1 && !CloseHandle(handler) && ErrHUsed)
     //  ErrH.Abort(closeMSG,XERR_USER,GetLastError(),fname);
     handler->close();
     delete handler;
     handler = NULL;
     //fname = "";
     pos = 0L;
     eofFlag = 1;
     extSize = -1;
     extPos = 0;
 }
References eofFlag, extPos, extSize, handler, NULL, and pos.
Referenced by aci_setMatrixBorder(), aci_setScMatrixBorder(), aciPackFile(), aciUnPackFile(), acsPrepareSlotName(), acsSaveData(), aLoadFonts(), ivrtMap::analyzeINI(), aciWorldMap::calc_shapes(), XGR_Screen::capture_screen(), XRecorder::Close(), CompressMap(), FireBallProcess::Convert(), dastResourcePoly3D::dastResourcePoly3D(), dastResourceSign::dastResourceSign(), Object::dynamics_init(), GeneralSystemFree(), GetKeepSpace(), actIntDispatcher::i_init(), iLoadControls(), iLoadData(), WaveProcess::Init(), ShowImageRTO::Init(), aciML_ItemData::init(), aciLocationInfo::init_map_data(), aciLocationShutterInfo::init_size(), iBitmapElement::init_size(), InitProtoCrypt(), InitScreenFonts(), iSaveControls(), iSaveData(), KeepCleanUp(), FireBallProcess::Load(), aciFont::load(), iMobileLocation::load(), dgFile::load(), ibsObject::load(), Object::load(), aciCHTree::load(), ScriptFile::load(), bmlObject::load(), vrtMap::load(), aciScreenResourceBMP::load(), aciScreenResourceBML::load(), aciScreenResourceBMO::load(), aciScreenResourceXBM::load(), aciBitmapMenuItem::load(), iBitmapElement::load(), iTextData::load(), bmlObject::load2mem(), aButton::load_frames(), iScreen::load_palette(), load_s_text(), iAVIElement::load_shape(), iBitmapElement::load_shape(), load_text(), Object::loadA3D(), aciLocationShutterInfo::loadData(), XZIP_Resource::LoadIndex(), Object::loadM3D(), loadMouseFrames(), LoadVPR(), main(), TrackType::Open(), PassageImageType::Open(), OpenCyclicPal(), PalettePrepare(), Parser::Parser(), vrtMap::reload(), FireBallProcess::Save(), TrackType::Save(), aciCHTree::save(), iBitmapElement::set_pal(), PassageImageType::Show(), StaticClose(), StaticOpen(), VLload(), xtInitApplication(), and ~XStream().
eof()
int XStream::eof () inline
 { return eofFlag || pos >= size(); }
References eofFlag, pos, and size().
Referenced by getline(), and open().
flush()
void XStream::flush ()
 {
     /* Full stream debug
     std::fstream debug("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open())
         debug<<"FLUSH "<<fname<<std::endl;
     debug.close();
     */
     //if (!FlushFileBuffers(handler) && ErrHUsed)
     //  ErrH.Abort(flushMSG,XERR_USER,GetLastError(),fname);
     ((std::fstream *)handler)->flush();
 }
References handler.
GetFileName()
const char* XStream::GetFileName () const inline
 { return fname.c_str(); }
References fname.
gethandler()
XSHANDLE XStream::gethandler () inline
 { return handler; }
References handler.
Referenced by vrtMap::reload().
getline()
char * XStream::getline (char * buf, unsigned len)
 {
     int i = -1;
     do {
         i++;
         read(&buf[i],1);
        } while(buf[i] != '\n' && i < (int)len && !eof());
     if(eof())
         buf[i] = '\0';
     else
         buf[i - 1] = '\0';
     return buf;
 }
References eof(), and read().
open() [1/2]
int XStream::open (const char * name, unsigned f = XS_IN)
 {
     std::string smode;
     smode+="File name:";
     smode+=name;
     file_name = name;
 #ifdef XSTREAM_DEBUG
     std::cerr << "DBG: XStream::open(\"" << name << "\", 0x" << std::hex << f << ")" << std::endl;
 #endif
     std::fstream *file = open_file(name, f);
     handler = file;
     if (file->is_open()) {
         fname = name;
         pos = file->tellg();
         eofFlag = 0;
     } else {
         #ifdef XSTREAM_DEBUG
             std::cerr << "ERR: XStream::open(\"" << name << "\", 0x" << std::hex << f << ")" << std::endl;
         #endif
         if(ErrHUsed)
             ErrH.Abort(openMSG,XERR_USER,0,smode.c_str());
         else
             return 0;
     }
     return 1;
 }
References XErrorHandler::Abort(), eofFlag, ErrH, ErrHUsed, file_name, fname, handler, open_file(), and pos.
Referenced by aciPackFile(), aciUnPackFile(), acsLoadData(), acsPrepareSlotName(), acsSaveData(), aLoadFonts(), aciWorldMap::calc_shapes(), XGR_Screen::capture_screen(), CompressMap(), FireBallProcess::Convert(), Object::dynamics_init(), GeneralSystemInit(), GetKeepSpace(), iLoadControls(), iLoadData(), ShowImageRTO::Init(), aciML_ItemData::init(), SkyFarmerList::Init(), aciLocationInfo::init_map_data(), iBitmapElement::init_size(), InitProtoCrypt(), InitScreenFonts(), iPrepareSaveNames(), KeepCleanUp(), FireBallProcess::Load(), MobileLocation::load(), ibsObject::load(), ScriptFile::load(), ivrtMap::load(), vrtMap::load(), aciScreenResourceBMP::load(), aciScreenResourceBML::load(), aciScreenResourceBMO::load(), aciScreenResourceXBM::load(), aciBitmapMenuItem::load(), iBitmapElement::load(), iTextData::load(), invItem::load_frame(), aButton::load_frames(), iScreen::load_palette(), Server::load_rating_list(), load_s_text(), iAVIElement::load_shape(), iBitmapElement::load_shape(), load_text(), loadMouseFrames(), main(), XRecorder::Open(), XZIP_Resource::open(), PassageImageType::Open(), OpenCyclicPal(), vrtMap::reload(), FireBallProcess::Save(), aciCHTree::save(), Server::Server(), PassageImageType::Show(), StaticOpen(), VLload(), and XZIP_Resource::XZIP_Resource().
open() [2/2]
int XStream::open (XStream * owner, long start, long ext_sz = -1)
 {
     /* Full stream debug
     std::fstream debug("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open())
         debug<<"OPEN_XSTREAM "<<owner -> fname<<std::endl;
     debug.close();
     */
     fname = owner -> fname;
     handler = owner -> handler;
     pos = 0;
     owner -> seek(s,XS_BEG);
     eofFlag = owner -> eof();
     extSize = ext_sz;
     extPos = s;
     return 1;
 }
References eof(), eofFlag, extPos, extSize, fname, handler, pos, seek(), and XS_BEG.
operator void *()
XStream::operator void * () inline
 { if(handler != XSHANDLE(-1)) return 0; else return this; }
References handler.
operator!()
int XStream::operator! () inline
 { if(handler != XSHANDLE(-1)) return 1; else return 0; }
References handler.
operator<() [1/12]
XStream & XStream::operator< (char v)
 {
     write(&v,(unsigned)sizeof(char));
     return *this;
 }
References write().
operator<() [2/12]
XStream & XStream::operator< (const char * v)
 {
     write(v,(unsigned)strlen(v));
     return *this;
 }
References write().
operator<() [3/12]
XStream & XStream::operator< (double v)
 {
     write(&v,(unsigned)sizeof(double));
     return *this;
 }
References write().
operator<() [4/12]
XStream & XStream::operator< (float v)
 {
     write(&v,(unsigned)sizeof(float));
     return *this;
 }
References write().
operator<() [5/12]
XStream & XStream::operator< (int v)
 {
     write(&v,(unsigned)sizeof(int));
     return *this;
 }
References write().
operator<() [6/12]
XStream & XStream::operator< (long double v)
 {
     write(&v,(unsigned)sizeof(long double));
     return *this;
 }
References write().
operator<() [7/12]
XStream & XStream::operator< (long v)
 {
     write(&v,(unsigned)sizeof(long));
     return *this;
 }
References write().
operator<() [8/12]
XStream & XStream::operator< (short v)
 {
     write(&v,(unsigned)sizeof(short));
     return *this;
 }
References write().
operator<() [9/12]
XStream & XStream::operator< (unsigned char v)
 {
     write(&v,(unsigned)sizeof(char));
     return *this;
 }
References write().
operator<() [10/12]
XStream& XStream::operator< (unsigned int)
operator<() [11/12]
XStream & XStream::operator< (unsigned long v)
 {
     write(&v,(unsigned)sizeof(unsigned long));
     return *this;
 }
References write().
operator<() [12/12]
XStream & XStream::operator< (unsigned short v)
 {
     write(&v,(unsigned)sizeof(unsigned short));
     return *this;
 }
References write().
operator<=() [1/11]
XStream & XStream::operator<= (char var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s));
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [2/11]
XStream & XStream::operator<= (double var)
 {
     int len = snprintf(_ConvertBuffer, _CONV_BUFFER_LEN, "%.*g", digits, var);
     write(_ConvertBuffer,len);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, digits, and write().
operator<=() [3/11]
XStream & XStream::operator<= (float var)
 {
     int len = snprintf(_ConvertBuffer, _CONV_BUFFER_LEN, "%.*g", digits, var);
     write(_ConvertBuffer,len);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, digits, and write().
operator<=() [4/11]
XStream & XStream::operator<= (int var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s));
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [5/11]
XStream & XStream::operator<= (long double var)
 {
     int len = snprintf(_ConvertBuffer, _CONV_BUFFER_LEN, "%.*Lg", digits, var);
     write(_ConvertBuffer,len);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, digits, and write().
operator<=() [6/11]
XStream & XStream::operator<= (long var)
 {
     char* s = port_ltoa(var,_ConvertBuffer,radix);
     write(s,strlen(s));
     return *this;
 }
References _ConvertBuffer, port_ltoa(), radix, and write().
operator<=() [7/11]
XStream & XStream::operator<= (short var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s));
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [8/11]
XStream & XStream::operator<= (unsigned char var)
 {
     char* s = port_itoa(var,_ConvertBuffer,radix);
     write(s,strlen(s));
     return *this;
 }
References _ConvertBuffer, port_itoa(), radix, and write().
operator<=() [9/11]
XStream& XStream::operator<= (unsigned int)
operator<=() [10/11]
XStream & XStream::operator<= (unsigned long var)
 {
     char* s = port_ultoa(var,_ConvertBuffer,radix);
     write(s,strlen(s));
     return *this;
 }
References _ConvertBuffer, port_ultoa(), radix, and write().
operator<=() [11/11]
XStream & XStream::operator<= (unsigned short var)
 {
     char* s = port_ltoa(var,_ConvertBuffer,radix);
     write(s,strlen(s));
     return *this;
 }
References _ConvertBuffer, port_ltoa(), radix, and write().
operator>() [1/12]
XStream & XStream::operator> (char & v)
 {
     read(&v,(unsigned)sizeof(char));
     return *this;
 }
References read().
operator>() [2/12]
XStream & XStream::operator> (char * v)
 {
     read(v,(unsigned)strlen(v));
     return *this;
 }
References read().
operator>() [3/12]
XStream & XStream::operator> (double & v)
 {
     read(&v,(unsigned)sizeof(double));
     return *this;
 }
References read().
operator>() [4/12]
XStream & XStream::operator> (float & v)
 {
     read(&v,(unsigned)sizeof(float));
     return *this;
 }
References read().
operator>() [5/12]
XStream & XStream::operator> (int & v)
 {
     read(&v,(unsigned)sizeof(int));
     return *this;
 }
References read().
operator>() [6/12]
XStream & XStream::operator> (long & v)
 {
     read(&v,(unsigned)sizeof(long));
     return *this;
 }
References read().
operator>() [7/12]
XStream & XStream::operator> (long double & v)
 {
     read(&v,(unsigned)sizeof(long double));
     return *this;
 }
References read().
operator>() [8/12]
XStream & XStream::operator> (short & v)
 {
     read(&v,(unsigned)sizeof(short));
     return *this;
 }
References read().
operator>() [9/12]
XStream & XStream::operator> (unsigned char & v)
 {
     read(&v,(unsigned)sizeof(char));
     return *this;
 }
References read().
operator>() [10/12]
XStream& XStream::operator> (unsigned int &)
operator>() [11/12]
XStream & XStream::operator> (unsigned long & v)
 {
     read(&v,(unsigned)sizeof(unsigned long));
     return *this;
 }
References read().
operator>() [12/12]
XStream & XStream::operator> (unsigned short & v)
 {
     read(&v,(unsigned)sizeof(unsigned short));
     return *this;
 }
References read().
operator>=() [1/11]
XStream & XStream::operator>= (char & var)
 {
     int ret = read(_ConvertBuffer,4);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = (char)strtol(p,&p,0);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [2/11]
XStream & XStream::operator>= (double & var)
 {
     int ret = read(_ConvertBuffer,_CONV_BUFFER_LEN);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = strtod(p,&p);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [3/11]
XStream & XStream::operator>= (float & var)
 {
     int ret = read(_ConvertBuffer,_CONV_BUFFER_LEN);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = (float)strtod(p,&p);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [4/11]
XStream & XStream::operator>= (int & var)
 {
     int ret = read(_ConvertBuffer,16);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = strtol(p,&p,0);
     //std::cout<<"seek - p:"<<(long long)p<<" _ConvertBuffer:"<<(long)_ConvertBuffer<<" ret:"<<var<<" result:"<<p - _ConvertBuffer + 1 - ret<<std::endl;
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     //std::cout<<"Pos:"<<ppos<<std::endl;
     return *this;
 }
References _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [5/11]
XStream & XStream::operator>= (long & var)
 {
     int ret = read(_ConvertBuffer,16);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = strtol(p,&p,0);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [6/11]
XStream & XStream::operator>= (long double & var)
 {
     int ret = read(_ConvertBuffer,_CONV_BUFFER_LEN);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = strtod(p,&p);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _CONV_BUFFER_LEN, _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [7/11]
XStream & XStream::operator>= (short & var)
 {
     int ret = read(_ConvertBuffer,6);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = (short)strtol(p,&p,0);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [8/11]
XStream & XStream::operator>= (unsigned char & var)
 {
     int ret = read(_ConvertBuffer,4);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = (unsigned char)strtoul(p,&p,0);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [9/11]
XStream& XStream::operator>= (unsigned int &)
operator>=() [10/11]
XStream & XStream::operator>= (unsigned long & var)
 {
     int ret = read(_ConvertBuffer,16);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = strtoul(p,&p,0);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _ConvertBuffer, read(), seek(), and XS_CUR.
operator>=() [11/11]
XStream & XStream::operator>= (unsigned short & var)
 {
     int ret = read(_ConvertBuffer,6);
     if(!ret) return *this;
     char* p = _ConvertBuffer;
     p[ret] = ' ';
     var = (unsigned short)strtoul(p,&p,0);
     seek(p - _ConvertBuffer + 1 - ret,XS_CUR);
     return *this;
 }
References _ConvertBuffer, read(), seek(), and XS_CUR.
read() [1/2]
template<class T > XStream& XStream::read (T & v) inline
 { read(&v, sizeof(T)); return *this; }
References read().
Referenced by read().
read() [2/2]
unsigned long XStream::read (void * buf, unsigned long len)
 {
     unsigned long ret;
     /*if(!ReadFile(handler,buf,len,&ret,0))
         if(ErrHUsed) ErrH.Abort(readMSG,XERR_USER,GetLastError(),fname);
         else return 0U;
     if(ret < len) eofFlag = 1;*/
     ((std::fstream *)handler)->read((char *)buf, len);
     len = ((std::fstream *)handler)->gcount();
     ret = len;
     pos += ret;
     if(extSize != -1 && pos >= extSize) eofFlag = 1;
     if(xsReadHandler){
         xsReadBytesDelta += ret;
         if(xsReadBytesDelta >= xsRdWrResolution){
             xsReadBytes += xsReadBytesDelta;
             xsReadBytesDelta = 0;
             (*xsReadHandler)(xsReadBytes);
         }
     }
     // Full stream debug
     /*std::fstream debug("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open())
         debug<<"READ "<<fname<<" len:"<<len<<std::endl;
         //debug<<"READ "<<fname<<" len:"<<len<<" buf:"<<(char *)buf<<std::endl;
     debug.close();*/
     return ret;
 }
References eofFlag, extSize, handler, pos, xsRdWrResolution, xsReadBytes, xsReadBytesDelta, and xsReadHandler.
Referenced by ivrtMap::accept(), vrtMap::accept(), aci_setMatrixBorder(), aci_setScMatrixBorder(), aciLoadPackedFile(), aciPackFile(), aciUnPackFile(), acsPrepareSlotName(), aLoadFonts(), aciWorldMap::calc_shapes(), CompressMap(), SensorDataType::CreateSensor(), dastResourcePoly3D::dastResourcePoly3D(), vrtMap::dump_terrain(), get_string(), getline(), actIntDispatcher::i_init(), iLoadControls(), WaveProcess::Init(), ShowImageRTO::Init(), aciML_ItemData::init(), SkyFarmerList::Init(), aciLocationInfo::init_map_data(), InitProtoCrypt(), InitScreenFonts(), iPrepareSaveNames(), vrtMap::link(), vrtMap::linkC(), FireBallProcess::Load(), aciFont::load(), iMobileLocation::load(), dgFile::load(), MobileLocation::load(), ibsObject::load(), Object::load(), Mask::load(), aciCHTree::load(), ScriptFile::load(), bmlObject::load(), vrtMap::load(), aciScreenResourceBMP::load(), aciScreenResourceBML::load(), aciScreenResourceBMO::load(), aciScreenResourceXBM::load(), aciBitmapMenuItem::load(), iBitmapElement::load(), FileBox::load(), dgRoom::load(), bmlObject::load2mem(), invItem::load_frame(), aButton::load_frames(), iScreen::load_palette(), Server::load_rating_list(), Game::load_result(), iAVIElement::load_shape(), iBitmapElement::load_shape(), Mask::load_to_flame(), Object::loadA3D(), aciLocationShutterInfo::loadData(), XZIP_Resource::LoadHeaders(), Object::loadM3D(), loadMouseFrames(), LoadVPR(), main(), MLverify(), PassageImageType::Open(), OpenCyclicPal(), operator>(), operator>(), operator>=(), PalettePrepare(), Parser::Parser(), vrtMap::reload(), iBitmapElement::set_pal(), PassageImageType::Show(), VLload(), xtInitApplication(), and XZIP_FileHeader::XZIP_FileHeader().
seek()
long XStream::seek (long offset, int dir)
 {
     /* Full stream debug*/
     /*std::fstream debug("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open())
         debug<<"SEEK START "<<fname<<" tellg:"<<((std::fstream *)handler)->tellg()
         <<" addr:"<<handler<<" curo:"<<offset<<std::endl;
     debug.close();*/
     long ret=0;
     if(extSize != -1){
         switch(dir){
             case XS_BEG:
                 //ret = SetFilePointer(handler,extPos + offset,0,dir) - extPos;
                 if (((std::fstream *)handler)->flags() & std::ios::out) {
                     ret = ((std::fstream *)handler)->tellp() - (std::streamoff)extPos;
                     ((std::fstream *)handler)->seekp(extPos + offset, std::ios_base::beg);
                 }
                 else {
                     ret = ((std::fstream *)handler)->tellg() - (std::streamoff)extPos;
                     ((std::fstream *)handler)->seekg(extPos + offset, std::ios_base::beg);
                 }
                 break;
             case XS_END:
                 //ret = SetFilePointer(handler,extPos + extSize - offset - 1,0,XS_BEG) - extPos;
                 if (((std::fstream *)handler)->flags() & std::ios::out) {
                     ret = ((std::fstream *)handler)->tellp() - (std::streamoff)extPos;
                     ((std::fstream *)handler)->seekp(extPos + extSize - offset - 1, std::ios_base::beg);
                 } else {
                     ret = ((std::fstream *)handler)->tellg() - (std::streamoff)extPos;
                     ((std::fstream *)handler)->seekg(extPos + extSize - offset - 1, std::ios_base::beg);
                 }
                 break;
             case XS_CUR:
                 //ret = SetFilePointer(handler,extPos + pos + offset,0,XS_BEG) - extPos;
                 //((std::fstream *)handler)->clear();
                 if (((std::fstream *)handler)->flags() & std::ios::out) {
                     ret = ((std::fstream *)handler)->tellp() - (std::streamoff)extPos;
                     ((std::fstream *)handler)->seekp(extPos + pos + offset, std::ios_base::beg);
                 } else {
                     ret = ((std::fstream *)handler)->tellg() - (std::streamoff)extPos;
                     ((std::fstream *)handler)->seekg(extPos + pos + offset, std::ios_base::beg);
                 }
                 break;
         }
     }
     else
     {
         //ret = SetFilePointer(handler,offset,0,dir);
         //std::cout<<"SEEK:"<<fname<<std::endl;
         switch(dir){
             case XS_BEG:
                 if (((std::fstream *)handler)->flags() & std::ios::out)
                     ((std::fstream *)handler)->seekp(offset, std::ios_base::beg);
                 else
                     ((std::fstream *)handler)->seekg(offset, std::ios_base::beg);
                 break;
             case XS_END:
                 if (((std::fstream *)handler)->flags() & std::ios::out)
                     ((std::fstream *)handler)->seekp(offset, std::ios_base::end);
                 else
                     ((std::fstream *)handler)->seekg(offset, std::ios_base::end);
                 break;
             case XS_CUR:
                 if (((std::fstream *)handler)->flags() & std::ios::out)
                     ((std::fstream *)handler)->seekp(offset, std::ios_base::cur);
                 else
                     ((std::fstream *)handler)->seekg(offset, std::ios_base::cur);
                 break;
         }
         if (((std::fstream *)handler)->flags() & std::ios::out)
             ret = ((std::fstream *)handler)->tellp();
         else
             ret = ((std::fstream *)handler)->tellg();
     }
     /* Full stream debug*/
     /*debug.open("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open())
         debug<<"SEEK "<<fname<<" offset:"<<offset<<" dir:"<<dir
         <<" extSize:"<<extSize<<" pos:"<<pos<<" extPos:"<<extPos
         <<" ret:"<<ret<<std::endl;
     debug.close();*/
     if (((std::fstream *)handler)->fail()) {
         std::cout<<"Warning: Bad seek in file."<<std::endl;
         }
     if (ret == -1L)
         {
         std::cout<<"Warning: XStream::seek applies when the end of the file reached. "<<fname<<std::endl;
         return -1L;
         }
     if (ret >= size() - 1) eofFlag = 1;  else eofFlag = 0;
     return pos = ret;
 }
Referenced by ivrtMap::accept(), vrtMap::accept(), acsLoadData(), CompressMap(), DangerDataType::CreateDanger(), vrtMap::delink(), vrtMap::dump_terrain(), ivrtMap::finit(), vrtMap::link(), vrtMap::linkC(), iMobileLocation::load(), MobileLocation::load(), vrtMap::load(), FileBox::load(), iMLFrame::load(), MLFrame::load(), XZIP_Resource::LoadHeaders(), LoadVPR(), main(), open(), operator>=(), PalettePrepare(), Parser::Parser(), and vrtMap::reload().
SetDigits()
void XStream::SetDigits (int d) inline
 { digits=d; }
References digits.
SetRadix()
void XStream::SetRadix (int r) inline
 { radix=r; }
References radix.
Referenced by GameObjectDispatcher::NetEvent().
size()
long XStream::size ()
 {
 //std::cout<<"XStream::size()"<<std::endl;
     long tmp = extSize;
     long int tmp2;
     if(tmp == -1){
         //tmp=GetFileSize(handler,0);
         if (((std::fstream *)handler)->flags() & std::ios::in) {
             tmp2 = ((std::fstream *)handler)->tellg();
             ((std::fstream *)handler)->seekp(0, std::ios_base::end);
             tmp = ((std::fstream *)handler)->tellg();
             ((std::fstream *)handler)->seekp(tmp2);
         } else {
             tmp2 = ((std::fstream *)handler)->tellp();
             ((std::fstream *)handler)->seekg(0, std::ios_base::end);
             tmp = ((std::fstream *)handler)->tellp();
             ((std::fstream *)handler)->seekg(tmp2);
         }
         if (tmp == -1L) {
             if (ErrHUsed)
                 ErrH.Abort(sizeMSG,XERR_USER,0,fname.c_str());
             else
                 return -1;
         }
     }
     /* Full stream debug
     std::fstream debug("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open())
         debug<<"SIZE "<<fname<<" size:"<<tmp<<std::endl;
     debug.close();
     */
     return tmp;
 }
References extSize, and handler.
Referenced by aciLoadPackedFile(), aciPackFile(), aciUnPackFile(), aLoadFonts(), eof(), GetKeepSpace(), InitScreenFonts(), dgFile::load(), Object::load(), aciCHTree::load(), ScriptFile::load(), vrtMap::load(), Server::load_rating_list(), Object::loadA3D(), Object::loadM3D(), LoadVPR(), main(), Parser::Parser(), vrtMap::reload(), and xtInitApplication().
tell()
long XStream::tell (void) const inline
 { return pos; }
References pos.
Referenced by CompressMap(), vrtMap::load(), XZIP_Resource::LoadHeaders(), and vrtMap::reload().
write() [1/2]
template<class T > XStream& XStream::write (const T & v) inline
 { write(&v, sizeof(T)); return *this; }
References write().
Referenced by write().
write() [2/2]
unsigned long XStream::write (const void * buf, unsigned long len)
 {
     /* Full stream debug
     std::fstream debug("openfile.txt", std::ios::out|std::ios::app);
     if (debug.is_open())
         debug<<"WRITE "<<fname<<" len:"<<len<<" buf:"<<(char*)buf<<std::endl;
     debug.close();
     */
     unsigned long ret;
     /*std::cout<<"Start write to:"<<fname
             <<" len:"<<len
             <<" "<<((std::fstream *)handler)->fail()
             <<" "<<((std::fstream *)handler)->good()
             <<" "<<((std::fstream *)handler)->eof()
             <<" "<<((std::fstream *)handler)->bad()
             <<" open:"<<((std::fstream *)handler)->is_open()
             <<" tellp:"<<((std::fstream *)handler)->tellp()<<std::endl;*/
     ((std::fstream *)handler)->write((char *)buf, len);
     /*
         std::cout<<"END write to:"<<fname
             <<" len:"<<len
             <<" "<<((std::fstream *)handler)->fail()
             <<" "<<((std::fstream *)handler)->good()
             <<" "<<((std::fstream *)handler)->eof()
             <<" "<<((std::fstream *)handler)->bad()
             <<" tellp:"<<((std::fstream *)handler)->tellp()<<std::endl;
         std::cout<<(char *)buf<<std::endl;*/
     ret = len;
     pos += ret;
     if(xsWriteHandler){
         xsWriteBytesDelta += ret;
         if(xsWriteBytesDelta >= xsRdWrResolution){
             xsWriteBytes += xsWriteBytesDelta;
             xsWriteBytesDelta = 0;
             (*xsWriteHandler)(xsWriteBytes);
         }
     }
     return ret;
 }
References handler, pos, xsRdWrResolution, xsWriteBytes, xsWriteBytesDelta, and xsWriteHandler.
Referenced by aciPackFile(), aciUnPackFile(), XGR_Screen::capture_screen(), CompressMap(), FireBallProcess::Convert(), vrtMap::delink(), ivrtMap::finit(), iSaveControls(), vrtMap::load(), operator<(), operator<(), operator<=(), output_palette(), put_string(), vrtMap::reload(), aciCHTree::save(), dgRoom::save(), XZIP_FileHeader::save(), Game::save_result(), SensorDataType::SaveSensor(), and StaticOpen().
Member Data Documentation
_ConvertBuffer
char XStream::_ConvertBuffer[_CONV_BUFFER_LEN+1]
Referenced by operator<=(), and operator>=().
digits
int XStream::digits
Referenced by operator<=(), SetDigits(), and XStream().
eofFlag
int XStream::eofFlag
Referenced by close(), eof(), open(), read(), and XStream().
ErrHUsed
int XStream::ErrHUsed
Referenced by open(), and XStream().
extPos
long XStream::extPos
Referenced by close(), open(), and XStream().
extSize
long XStream::extSize
Referenced by close(), open(), read(), size(), and XStream().
file_name
std::string XStream::file_name
Referenced by open().
fname
std::string XStream::fname
Referenced by GetFileName(), and open().
handler
XSHANDLE XStream::handler
Referenced by close(), flush(), gethandler(), open(), operator void *(), operator!(), read(), size(), write(), and XStream().
pos
long XStream::pos
Referenced by close(), eof(), open(), read(), tell(), and write().
radix
int XStream::radix
Referenced by operator<=(), SetRadix(), and XStream().
The documentation for this struct was generated from the following files:
lib/xtool/xstream.h
lib/xtool/xstream/xscnvin.cpp
lib/xtool/xstream/xscnvout.cpp
lib/xtool/xstream/xscore.cpp
lib/xtool/xstream/xsenlv.cpp
lib/xtool/xstream/xsgetlin.cpp
lib/xtool/xstream/xsinput.cpp
lib/xtool/xstream/xsoutput.cpp
lib/xtool/xstream/xsrdwr.cpp
lib/xtool/xstream/xsserv.cpp