Vangers: DebrisObject Struct Reference
DebrisObject Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void Quant (void)
void DrawQuant (void)
void CreateDebris (int id, int ind)
void vExplosion (Object *parent, int debris_index)
Public Member Functions inherited from Object
Object ()
~Object ()
Object ()
Object & operator= (Object &obj)
virtual ~Object ()
void free ()
void load (char *name, int scale=256)
void save (char *name)
void loadLST (char *name_lst, char *name_asc=0)
void loadM3D (char *name)
void saveM3D (char *name)
void loadLSA (char *name)
void loadA3D (char *name)
void saveA3D (char *name)
void draw ()
void pixel_draw ()
void non_sorted_draw ()
void set_body_color (unsigned int color_id)
void lay_to_slot (int slot, Object *weapon)
void dynamics_init (char *prm_name)
void calc_springs (int NumParts, int Threshold)
void calc_bound ()
void load_parameters (const char *name)
void save_parameters (char *name)
void global_save_parameter (int i_entry)
void entries_control ()
void set_active (int on)
void controls (int mode, int param=0)
void set_3D (int mode, int x, int y, int z, int dz, int angle, int speed)
void impulse (int angle, int distance, int slope=Pi/4, int lever_arm=0)
void impulse (const DBV &direct, int distance, int lever_arm=0)
void jump ()
void direct_keyboard_control ()
void direct_joystick_control ()
void import_controls ()
void analysis ()
void switch_analysis (int off)
void mechous_analysis (double dt)
void basic_mechous_analysis (double dt, int last)
void debris_analysis (double dt)
void basic_debris_analysis (double dt)
void insect_analysis ()
void skyfarmer_analysis (double dt)
void fish_analysis (double dt)
void update_coord (int camera_correction=0)
void convert_to_beeb (Object *beeb=0)
void set_draw_mode (int mode)
void set_ground_elastic (double k)
void steer (int dir)
void motor_control (int dir)
void impulse (int side)
void brake_on ()
virtual int test_objects_collision ()
int test_object_to_object (Object *obj)
int test_object_to_baseobject (BaseObject *obj)
int test_box_to_box (Object *obj)
int test_wheels_to_sphere (Object *sphere)
void DrawQuant ()
void Explosion (int m_TNT, int m_id)
void destroy_double_level ()
void ground_pressing ()
int test_whether_there_is_not_something_above ()
int check_terrain_type (int terrain_type)
int check_mole_submerging ()
int get_max_jump_distance ()
void NetEvent (int type, int id, int creator, int time, int x, int y, int radius)
void Send (void)
void skyfarmer_start (int x, int y, int angle=0)
void skyfarmer_set_direction (const DBV &direction)
void skyfarmer_end ()
void precise_impulse (Vector source_point, int x_dest, int y_dest)
virtual void StartMoleProcess (void)
virtual int UsingCopterig (int decr_8)
virtual int UsingCrotrig (int decr_8)
virtual int UsingCutterig (int decr_8)
Public Attributes
int ModelID
int ModelIndex
int Time
Public Attributes inherited from Object
int ID
int client_ID
unsigned int visibility
unsigned int last_update
unsigned int in_queue
unsigned int send_hide
unsigned int send_delete
int time
int x
int y
int radius
int body_size
int death_body_size
unsigned char * body
Object * next
Object * prev
XTList< Object > * list
Object * next_alt
Object * prev_alt
XTListAlt< Object > * list_alt
int n_models
Model * models
unsigned int i_model
Model * model
Model * bound
int xmax
int ymax
int zmax
int zmin
int rmax
double scale_size
double original_scale_size
int body_color_offset
int body_color_shift
int n_wheels
Wheel * wheels
int n_debris
Model * debris
Model * bound_debris
int slots_existence
Object * data_in_slots [MAX_SLOTS]
Vector R_slots [MAX_SLOTS]
int location_angle_of_slots [MAX_SLOTS]
char prm_name [128]
Object * old_appearance_storage
Vector R_scr
DBM A_scl
int psi
int tetta
double scale
double scale_max
double scale_real
int xmax_real
int ymax_real
int zmax_real
int rmax_screen
int z_below
int speed
int in_water
double device_modulation
double terrain_immersion
double water_immersion
DBV R
DBV V
DBV W
DBM A_l2g
DBM A_g2l
Quaternion Q_l2g
double V_drag
double W_drag
Object * collision_object
int after_db_coll
int interpolation_on
DBV dR_corr
Quaternion dQ_corr
int analysis_off
int disable_control
int active
int rudder
int traction
int wheel_analyze
int brake
int hand_brake
int nitro
int turbo
int archimedean
int jump_power
int stuff_phase
int side_impulse_enable
int mole_on
int k_track
int draw_mode
unsigned int device_switch_latency
int prev_controls
int current_controls
unsigned int last_send_time
int helicopter
int helicopter_time
int helicopter_strife
int helicopter_thrust_phase
int helicopter_circle_phase
int skyfarmer_fly_direction
DBV skyfarmer_direction
double k_elastic_modulation
DangerDataType * closest_field_object
double m
DBM J_inv
double scale_bound
double scale_box
int z_offset_of_mass_center
double speed_factor
double mobility_factor
double water_speed_factor
double air_speed_factor
double underground_speed_factor
double k_archimedean
double k_water_traction
double k_water_rudder
double TerraMoverSx
double TerraMoverSy
double TerraMoverSz
int FrontDefense
int BackDefense
int SideDefense
int UpperDefense
int LowerDefense
int FrontRamPower
int BackRamPower
int SideRamPower
int UpperRamPower
int LowerRamPower
int max_jump_distance
int end_of_object_data
int MoleInProcess
Detailed Description
Member Function Documentation
CreateDebris()
void DebrisObject::CreateDebris (int id, int ind)
 {
     Status = 0;
     cycleTor(R_curr.x,R_curr.y);
     GetVisible();
     Time = 0;
     set_active(0);
     ModelID = id;
     ModelIndex = ind;
 };
References cycleTor(), ModelID, ModelIndex, Object::set_active(), and Time.
DrawQuant()
void DebrisObject::DrawQuant (void)
 {
     draw();
 };
References Object::draw().
Init()
void DebrisObject::Init (void)
 {
     BaseObject::Init();
     ID = ID_DEBRIS;
     Status = SOBJ_DISCONNECT;
 };
References Object::ID, ID_DEBRIS, and SOBJ_DISCONNECT.
Referenced by DebrisList::CreateDebris().
Quant()
void DebrisObject::Quant (void)
 {
     int t;
     t = Visibility;
     GetVisible();
     Time++;
     if(Visibility == VISIBLE){
         R_prev = R_curr;
         analysis();
         cycleTor(R_curr.x,R_curr.y);
     }else{
         if(Time > DEBRIS_LIFE_TIME)
             Status |= SOBJ_DISCONNECT;
     };
 };
References Object::analysis(), cycleTor(), DEBRIS_LIFE_TIME, SOBJ_DISCONNECT, Time, and VISIBLE.
vExplosion()
void DebrisObject::vExplosion (Object * parent, int debris_index)
 {
     Object::operator = (*parent);
     n_models = 1;
     models = model = &(parent -> debris[debris_index]);
     m = density*model -> volume*pow(scale_size,3);
     J_inv = (model -> J*(pow(scale_size,2)/model -> volume)).inverse();
     body_color_shift++;
     k_archimedean = 0;
     xmax = model -> xmax;
     ymax = model -> ymax;
     zmax = model -> zmax;
     radius = rmax = model -> rmax;
 };
References Object::debris, density, Object::m, Object::model, Object::models, Object::n_models, and Object::operator=().
Member Data Documentation
ModelID
int DebrisObject::ModelID
Referenced by CreateDebris().
ModelIndex
int DebrisObject::ModelIndex
Referenced by CreateDebris().
Time
int DebrisObject::Time
Referenced by CreateDebris(), and Quant().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp