Vangers: FirstEscaveOutRTO Struct Reference
FirstEscaveOutRTO Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
virtual void Finit (void)
FirstEscaveOutRTO (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Additional Inherited Members
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
FirstEscaveOutRTO()
FirstEscaveOutRTO::FirstEscaveOutRTO (void) inline
 { ID = RTO_FIRST_ESCAVE_OUT_ID; Timer = RTO_ISCREEN_TIMER; }
References XRuntimeObject::ID, RTO_FIRST_ESCAVE_OUT_ID, RTO_ISCREEN_TIMER, and XRuntimeObject::Timer.
Member Function Documentation
Finit()
void FirstEscaveOutRTO::Finit (void) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
 #ifndef _ACI_SKIP_SHOP_
     iOutEscaveFinit();
     aci_LocationQuantFinit();
 #endif
 #endif
 _MEM_STATISTIC_("AFTER FIRST ESCAVE FINIT -> ");
 }
References _MEM_STATISTIC_, aci_LocationQuantFinit(), and iOutEscaveFinit().
Init()
void FirstEscaveOutRTO::Init (int id) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
 #ifndef _ACI_SKIP_SHOP_
     iOutEscaveInit();
 #endif
 #endif
 _MEM_STATISTIC_("AFTER FIRST ESCZVE INIT -> ");
 }
References _MEM_STATISTIC_, and iOutEscaveInit().
Quant()
int FirstEscaveOutRTO::Quant (void) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
     int val;
 #ifndef _ACI_SKIP_SHOP_
     val = iOutEscaveQuant();
 #else
     val = 1;
 #endif
     if(val){
         if(iAbortGameFlag){
             iAbortGameMode = 0;
             return RTO_LOADING3_ID;
         }
         else
             return NextID;
     }
     //XGR_Flip();
     return 0;
 #else
     return NextID;
 #endif
 }
References iAbortGameFlag, iAbortGameMode, iOutEscaveQuant(), BaseRTO::NextID, and RTO_LOADING3_ID.
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp