Vangers: uvsFlyFarmer Struct Reference
uvsFlyFarmer Struct Reference
#include <univang.h>
Public Member Functions
uvsFlyFarmer (int _t, uvsWorld *pw)
uvsFlyFarmer (XStream &)
virtual void Quant (void)
virtual void emuQuant (void)
void setSpeed (void)
void GrowCorn (void)
void save (XStream &)
Public Member Functions inherited from uvsTarget
uvsTarget (void)
Public Member Functions inherited from uvsElement
uvsElement (void)
void elink (uvsElement *&tail)
void eunlink (uvsElement *&tail)
void delink (uvsElement *&tail)
Public Attributes
uvsWorld * Pworld
int corn_type
int timer
int corn
int x_speed
int y_speed
Public Attributes inherited from uvsTarget
int pos_x
int pos_y
Public Attributes inherited from uvsElement
uvsElement * enext
uvsElement * eprev
UvsObjectType type
Detailed Description
Constructor & Destructor Documentation
uvsFlyFarmer() [1/2]
uvsFlyFarmer::uvsFlyFarmer (int _t, uvsWorld * pw) inline
                                       : uvsTarget(), uvsElement(){
                 timer = 0; corn = FLY_FARMER_CORN;
                 corn_type = _t; type = UVS_OBJECT::FLY_FARMER;
                 Pworld = pw;   pos_x = RND( pw -> x_size );
                 pos_y = RND( pw -> y_size );  setSpeed();
     };
References corn, corn_type, UVS_OBJECT::FLY_FARMER, FLY_FARMER_CORN, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, RND(), setSpeed(), timer, and uvsElement::type.
uvsFlyFarmer() [2/2]
uvsFlyFarmer::uvsFlyFarmer (XStream & fin)
{
     int cw;
     fin > pos_x;
     fin > pos_y;
     fin > timer;
     fin > corn ;
     fin > corn_type;
     fin > cw;
     type = UVS_OBJECT::FLY_FARMER;
     Pworld = WorldTable[cw];
     setSpeed();
 }
References corn, corn_type, UVS_OBJECT::FLY_FARMER, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, setSpeed(), timer, uvsElement::type, and WorldTable.
Member Function Documentation
emuQuant()
virtual void uvsFlyFarmer::emuQuant (void) inline virtual
Reimplemented from uvsElement.
 {};
GrowCorn()
void uvsFlyFarmer::GrowCorn (void)
{
     uvsItem* pi;
     uvsItem* _pi;
     uvsElement* pv = ETail;
     pi = new uvsItem(corn_type);
     pi -> param2 = RND(5)+1;
     pi -> pos_x = pos_x;
     pi -> pos_y = pos_y;
     corn--;
     while( pv ){
         if ( pv -> type == UVS_OBJECT::VANGER &&
             ((uvsVanger*)pv) -> Pworld == Pworld &&
             UVS_VANGER_SHAPE::GAMER !=  ((uvsVanger*)pv) -> shape &&
             UVS_VANGER_SHAPE::GAMER_SLAVE !=  ((uvsVanger*)pv) -> shape &&
             ((uvsVanger*)pv) -> status == UVS_VANGER_STATUS::MOVEMENT &&
             (UVS_VANGER_SHAPE::BUNCH_SLAVE !=  ((uvsVanger*)pv) -> shape || ((uvsVanger*)pv) -> Pmechos -> color == 1))
         {
             if ( abs(((uvsVanger*)pv) -> pos_y - pos_y) < FLY_CORN_DELTA && abs(((uvsVanger*)pv) -> pos_x - pos_x) < FLY_CORN_DELTA){
                 _pi = GetItem( ((uvsVanger*)pv) -> Pitem, corn_type, 0);
                 if (_pi){
                     _pi -> param2 += RND(5) + 1;
                     if (_pi -> param2 > 10 ) _pi -> param2 = 10;
                     delete pi;
                 } else
                     if(!((uvsVanger*)pv) -> addItem(pi, 1)) ErrH.Abort("uvsFlyFarmer::GrowCorn : don't add CORN");
                 ((uvsVanger*)pv) -> set_target((uvsTarget*)this, UVS_TARGET::FLY_FARMER);
                 return;
             }
         }
         pv = pv -> enext;
     }
     pi -> param2 = 1;
     pi -> link( Pworld -> Pitem);
 }
References XErrorHandler::Abort(), UVS_VANGER_SHAPE::BUNCH_SLAVE, corn, corn_type, uvsElement::enext, ErrH, ETail, FLY_CORN_DELTA, UVS_TARGET::FLY_FARMER, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, GetItem(), UVS_VANGER_STATUS::MOVEMENT, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, RND(), uvsElement::type, and UVS_OBJECT::VANGER.
Referenced by Quant().
Quant()
void uvsFlyFarmer::Quant (void) virtual
Reimplemented from uvsElement.
{
     if ((Pworld -> gIndex == CurrentWorld) && uvsKronActive ) return;
     pos_x = (pos_x + x_speed) & (Pworld -> x_size - 1);
     pos_y = (pos_y + y_speed) & (Pworld -> y_size - 1);
     if(++timer > FLY_FARMER_FIRST_TIME){
         if ( corn && !RND(144)){
             GrowCorn();
         }
     }
     if( timer > FLY_FARMER_LIVE || !RND(10)){
         Pworld -> remove_target( (uvsTarget*)this, UVS_TARGET::FLY_FARMER);
     }
     if(!RND(256)) setSpeed();
 }
References corn, CurrentWorld, UVS_TARGET::FLY_FARMER, FLY_FARMER_FIRST_TIME, FLY_FARMER_LIVE, GrowCorn(), uvsTarget::pos_x, uvsTarget::pos_y, Pworld, RND(), setSpeed(), timer, uvsKronActive, x_speed, and y_speed.
save()
void uvsFlyFarmer::save (XStream & fout)
{
     fout < type;
     fout < pos_x;
     fout < pos_y;
     fout < timer;
     fout < corn ;
     fout < corn_type;
     fout < Pworld -> gIndex;
 }
References corn, corn_type, fout, uvsTarget::pos_x, uvsTarget::pos_y, Pworld, timer, and uvsElement::type.
setSpeed()
void uvsFlyFarmer::setSpeed (void)
{
     x_speed = y_speed = 0;
     while(!x_speed && !y_speed){
         x_speed = V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1);
         y_speed = V_SPEED_DOLLY - RND(V_SPEED_DOLLY*2+1);
     }
 }
References RND(), V_SPEED_DOLLY, x_speed, and y_speed.
Referenced by Quant(), and uvsFlyFarmer().
Member Data Documentation
corn
int uvsFlyFarmer::corn
Referenced by SkyFarmerList::Free(), GrowCorn(), Quant(), save(), and uvsFlyFarmer().
corn_type
int uvsFlyFarmer::corn_type
Referenced by GrowCorn(), save(), and uvsFlyFarmer().
Pworld
uvsWorld* uvsFlyFarmer::Pworld
Referenced by GrowCorn(), Quant(), save(), and uvsFlyFarmer().
timer
int uvsFlyFarmer::timer
Referenced by SkyFarmerList::Free(), Quant(), save(), and uvsFlyFarmer().
x_speed
int uvsFlyFarmer::x_speed
Referenced by SkyFarmerList::Free(), Quant(), and setSpeed().
y_speed
int uvsFlyFarmer::y_speed
Referenced by SkyFarmerList::Free(), Quant(), and setSpeed().
The documentation for this struct was generated from the following files:
src/uvs/univang.h
src/uvs/univang.cpp