Vangers: GunSlot Struct Reference
GunSlot Struct Reference
#include <mechos.h>
Public Member Functions
void OpenSlot (int slot, VangerUnit *own, int ind)
void CloseSlot (void)
void OpenGun (GunDevice *p)
void CloseGun (void)
void Fire (void)
void Quant (void)
int CheckTarget (ActionUnit *p)
void RemoteFire (void)
void NetEvent (unsigned int time)
void NetStuffQuant (void)
void NetUpdate (void)
Public Attributes
int NetID
int StuffNetID
int nSlot
GunDevice * ItemData
WorldBulletTemplate * pData
int RealSpeed
int Time
int GunStatus
Vector vPlace
Vector vFire
DBM mPlace
DBM mFire
VangerUnit * Owner
int ControlFlag
GeneralObject * TargetObject
GeneralObject * aiTargetObject
int FireCount
int NetFireCount
int TableIndex
Detailed Description
Member Function Documentation
CheckTarget()
int GunSlot::CheckTarget (ActionUnit * p)
 {
     int d,v,a,l;
     Vector vCheck,vStart,vEnd,vTan;
     if(pData->BulletMode & BULLET_CONTROL_MODE::SPEED) v = pData->Speed + Owner->Speed;
     else v = pData->Speed;
     d = v * pData->LifeTime;
     vStart = Owner->R_curr;
     aiTargetObject = NULL;
     if(Owner->aiMoveFunction == AI_MOVE_FUNCTION_WHEEL && (Owner->PowerFlag & VANGER_POWER_FLY) && GetStuffObject(Owner,ACI_RADAR_DEVICE)){
         if(pData->BulletMode & BULLET_CONTROL_MODE::AIM){
             vEnd = p->R_curr;
             vCheck = Vector(getDistX(vEnd.x,vStart.x),getDistY(vEnd.y,vStart.y),vEnd.z - vStart.z);
             if(vCheck.abs2() > d*d) return 0;
             if(!(pData->BulletMode & BULLET_CONTROL_MODE::FLY) && MapLineTrace(vStart,vEnd)) return 0;
             aiTargetObject = p;
         }else{
             if(pData->BulletMode & BULLET_CONTROL_MODE::TARGET){
                 vEnd = p->R_curr;
                 vCheck = Vector(getDistX(vEnd.x,vStart.x),getDistY(vEnd.y,vStart.y),vEnd.z - vStart.z);
                 if(vCheck.abs2() > d*d) return 0;
                 vTan = Vector(vCheck.x,vCheck.y,0);
                 a = rPI(Owner->Angle - vTan.psi());
                 if(a > PI) a -= 2*PI;
                 if(abs(a) > PI/4) return 0;
                 if(!(pData->BulletMode & BULLET_CONTROL_MODE::FLY) && MapLineTrace(vStart,vEnd)) return 0;
                 aiTargetObject = p;
             }else{
                 vEnd = Vector(d,0,0)*Owner->RotMat;
                 vEnd += Owner->R_curr;
                 cycleTor(vEnd.x,vEnd.y);
                 if(!TouchSphere(vStart,vEnd,p->R_curr,p->radius,l)) return 0;
                 vTan = p->R_curr;
                 if(!(pData->BulletMode & BULLET_CONTROL_MODE::FLY) && MapLineTrace(vStart,vTan)) return 0;
             };
         };
     }else{
         vEnd = Vector(d,0,0)*Owner->RotMat;
         vEnd += Owner->R_curr;
         cycleTor(vEnd.x,vEnd.y);
         if(!TouchSphere(vStart,vEnd,p->R_curr,p->radius,l)) return 0;
         vTan = p->R_curr;
         if(!(pData->BulletMode & BULLET_CONTROL_MODE::FLY) && MapLineTrace(vStart,vTan)) return 0;
     };
     return 1;
 };
References Vector::abs2(), ACI_RADAR_DEVICE, AI_MOVE_FUNCTION_WHEEL, BULLET_CONTROL_MODE::AIM, TrackUnit::aiMoveFunction, aiTargetObject, ActionUnit::Angle, BulletControlType::BulletMode, cycleTor(), BULLET_CONTROL_MODE::FLY, getDistX(), getDistY(), GetStuffObject(), WorldBulletTemplate::LifeTime, MapLineTrace(), NULL, Owner, pData, PI, uvsUnitType::PowerFlag, Vector::psi(), Object::radius, ActionUnit::RotMat, rPI, BULLET_CONTROL_MODE::SPEED, BulletControlType::Speed, ActionUnit::Speed, BULLET_CONTROL_MODE::TARGET, TouchSphere(), VANGER_POWER_FLY, Vector::x, Vector::y, and Vector::z.
Referenced by VangerUnit::ResolveHandlerAttack().
CloseGun()
void GunSlot::CloseGun (void)
 {
     ItemData->ActIntBuffer.slot = -1;
     pData = NULL;
     Owner->lay_to_slot(nSlot,NULL);
     StuffNetID = 0;
     FireCount = 0;
     NetFireCount = 0;
     if(Owner->Status & SOBJ_ACTIVE){
         Owner->GetWeaponDelta();
         if(NetworkON && (Owner->Status & SOBJ_ACTIVE)){
             NETWORK_OUT_STREAM.update_object(NetID,0,0);
             NETWORK_OUT_STREAM < (int)(Owner->NetID);
             NETWORK_OUT_STREAM < (uchar)(TableIndex);
             NETWORK_OUT_STREAM < (int)(StuffNetID);
             NETWORK_OUT_STREAM < (int)(FireCount);
             NETWORK_OUT_STREAM < (int)(0);
             NETWORK_OUT_STREAM.end_body();
         };
     };
 };
References StuffObject::ActIntBuffer, FireCount, VangerUnit::GetWeaponDelta(), ItemData, Object::lay_to_slot(), NetFireCount, NetID, NETWORK_OUT_STREAM, NetworkON, nSlot, NULL, Owner, pData, actintItemData::slot, SOBJ_ACTIVE, StuffNetID, and TableIndex.
Referenced by ActionDispatcher::CheckDevice(), VangerUnit::CheckOutDevice(), Fire(), Quant(), ActionDispatcher::SlotOut(), and VangerUnit::WeaponGenerator().
CloseSlot()
void GunSlot::CloseSlot (void)
 {
     Owner->lay_to_slot(nSlot,NULL);
 //  pData = NULL;
     if(NetworkON && (Owner->Status & SOBJ_ACTIVE)){
         NETWORK_OUT_STREAM.delete_object(NetID);
         NETWORK_OUT_STREAM.end_body();
     };
 };
References Object::lay_to_slot(), NetID, NETWORK_OUT_STREAM, NetworkON, nSlot, NULL, Owner, and SOBJ_ACTIVE.
Referenced by VangerUnit::ChangeVangerProcess(), and VangerUnit::Go2Universe().
Fire()
void GunSlot::Fire (void)
 {
     GeneralObject* p;
     int mlen,len;
     int dx,dy;
     int rx,ry;
     StuffObject* l;
     if(GunStatus != GUN_READY || Owner->BeebonationFlag || !(Owner->ExternalDraw)) return;
     TargetObject = NULL;
     switch(ItemData->ActIntBuffer.type){
         case ACI_MACHOTINE_GUN_HEAVY:
         case ACI_MACHOTINE_GUN_LIGHT:
             if(ItemData->ActIntBuffer.data1 > 0){
                 GunStatus = GUN_FIRE;
                 ItemData->ActIntBuffer.data1--;
                 if(NetworkON) NetUpdate();
                 if(ActD.Active)
                     SOUND_MACHOTINE_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             };
             break;
         case ACI_GHORB_GEAR_LIGHT:
             if(ItemData->ActIntBuffer.data1 > 0){
                 GunStatus = GUN_FIRE;
                 ItemData->ActIntBuffer.data1--;
                 if(NetworkON) NetUpdate();
                 if(ActD.Active)
                     SOUND_GHORB_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             };
             break;
         case ACI_GHORB_GEAR_HEAVY:
             if(ItemData->ActIntBuffer.data1 > 0){
                 GunStatus = GUN_FIRE;
                 ItemData->ActIntBuffer.data1--;
                 if(NetworkON) NetUpdate();
                 if(ActD.Active)
                     SOUND_GHORB_BIG_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             };
             break;
         case ACI_SPEETLE_SYSTEM_LIGHT:
         case ACI_SPEETLE_SYSTEM_HEAVY:
             if(ItemData->ActIntBuffer.data1 > 0){
                 if(ControlFlag){
                     p = ActD.Tail;
                     mlen = -1;
                     rx = Owner->R_curr.x;
                     ry = Owner->R_curr.y;
                     while(p){
                         if(((BaseObject*)(p)) -> Visibility == VISIBLE && p != Owner){
                             dx = getDistX(p->R_curr.x,rx);
                             dy = getDistY(p->R_curr.y,ry);
                             len = dx*dx + dy*dy;
                             if(len < mlen || mlen == -1){
                                 TargetObject = p;
                                 mlen = len;
                             };
                         };
                         p = (Object*)(p->NextTypeList);
                     };
                 };
                 GunStatus = GUN_FIRE;
                 ItemData->ActIntBuffer.data1--;
                 if(NetworkON) NetUpdate();
                 if(ActD.Active)
                     SOUND_SPEETLE_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             }else{
                 l = GetStuffObject(Owner,ACI_SPEETLE_SYSTEM_AMMO1);
                 if(!l){
                     ControlFlag = 0;
                     l = GetStuffObject(Owner,ACI_SPEETLE_SYSTEM_AMMO0);
                 }else ControlFlag = 1;
                 if(l){
                     ObjectDestroy(l);
                     ItemData->ActIntBuffer.data1 = l->ActIntBuffer.data1;
                     if(Owner->ID == ID_VANGER && (Owner->Status & SOBJ_ACTIVE)) aciSendEvent2actint(ACI_DROP_ITEM,&(l->ActIntBuffer));
                     l->Storage->Deactive(l);
                     Owner->DelDevice(l);
                 };
             };
             break;
         case ACI_BEEBBANOZA_BLOCKADE:
             if(Owner->ID == ID_VANGER && (Owner->Status & SOBJ_ACTIVE)){
                 if(aiGetHotBug() > 5){
                     aiPutHotBug(aiGetHotBug() - 5);
                     GunStatus = GUN_FIRE;
                     if(NetworkON){
                         NetUpdate();
                         my_player_body.beebos = aiGetHotBug();
                         send_player_body(my_player_body);
                     };
                     if(ActD.Active)
                         SOUND_BEEBBANOZA_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 };
             }else{
                 GunStatus = GUN_FIRE;
                 if(ActD.Active)
                     SOUND_BEEBBANOZA_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             };
             break;
         case ACI_CRUSTEST_CANNON:
             if(ItemData->ActIntBuffer.data1 > 0){
                 GunStatus = GUN_FIRE;
                 ItemData->ActIntBuffer.data1--;
                 if(NetworkON) NetUpdate();
                 if(ActD.Active)
                     SOUND_CRUSTEST_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             }else{
                 l = GetStuffObject(Owner,ACI_CRUSTEST_CANNON_AMMO);
                 if(l){
                     ObjectDestroy(l);
                     ItemData->ActIntBuffer.data1 = l->ActIntBuffer.data1;
                     if(Owner->ID == ID_VANGER && (Owner->Status & SOBJ_ACTIVE)) aciSendEvent2actint(ACI_DROP_ITEM,&(l->ActIntBuffer));
                     l->Storage->Deactive(l);
                     Owner->DelDevice(l);
                 };
             };
             break;
         case ACI_TERMINATOR:
             if(Owner->dynamic_state & (GROUND_COLLISION | WHEELS_TOUCH)){
                 p = ActD.Tail;
                 mlen = -1;
                 rx = Owner->R_curr.x;
                 ry = Owner->R_curr.y;
                 while(p){
                     if(((BaseObject*)(p)) -> Visibility == VISIBLE && p != Owner){
                         dx = getDistX(p->R_curr.x,rx);
                         dy = getDistY(p->R_curr.y,ry);
                         len = dx*dx + dy*dy;
                         if(len < mlen || mlen == -1){
                             TargetObject = p;
                             mlen = len;
                         };
                     };
                     p = (Object*)(p->NextTypeList);
                 };
                 GunStatus = GUN_FIRE;
                 ItemData->ActIntBuffer.data1--;
                 if(NetworkON) NetUpdate();
                 if(ActD.Active)
                     SOUND_TERMINATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 if(ItemData->ActIntBuffer.data1 <= 0){
                     l = Owner->DeviceData;
                     while(l){
                         if(l->ActIntBuffer.type == ACI_TERMINATOR && l != ItemData)
                             break;
                         l = l->NextDeviceList;
                     };
                     if(l){
                         ObjectDestroy(l);
                         ItemData->ActIntBuffer.data0 = l->ActIntBuffer.data0;
                         ItemData->ActIntBuffer.data1 = l->ActIntBuffer.data1;
                         if(Owner->ID == ID_VANGER && (Owner->Status & SOBJ_ACTIVE)) aciSendEvent2actint(ACI_DROP_ITEM,&(l->ActIntBuffer));
                         l->Storage->Deactive(l);
                         Owner->DelDevice(l);
                     }else{
                         ObjectDestroy(ItemData);
                         if(Owner->ID == ID_VANGER && (Owner->Status & SOBJ_ACTIVE)) aciSendEvent2actint(ACI_DROP_ITEM,&(ItemData->ActIntBuffer));
                         ItemData->Storage->Deactive(ItemData);
                         Owner->DelDevice(ItemData);
                         CloseGun();
                     };
                 };
             };
             break;
         case ACI_TERMINATOR2:
             p = ActD.Tail;
             mlen = -1;
             rx = Owner->R_curr.x;
             ry = Owner->R_curr.y;
             while(p){
                 if(((BaseObject*)(p)) -> Visibility == VISIBLE && p != Owner){
                     dx = getDistX(p->R_curr.x,rx);
                     dy = getDistY(p->R_curr.y,ry);
                     len = dx*dx + dy*dy;
                     if(len < mlen || mlen == -1){
                         TargetObject = p;
                         mlen = len;
                     };
                 };
                 p = (Object*)(p->NextTypeList);
             };
             GunStatus = GUN_FIRE;
             ItemData->ActIntBuffer.data1--;
             if(NetworkON) NetUpdate();
             if(ActD.Active)
                 SOUND_TERMINATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             if(ItemData->ActIntBuffer.data1 <= 0){
                 l = Owner->DeviceData;
                 while(l){
                     if(l->ActIntBuffer.type == ACI_TERMINATOR2 && l != ItemData)
                         break;
                     l = l->NextDeviceList;
                 };
                 if(l){
                     ObjectDestroy(l);
                     ItemData->ActIntBuffer.data0 = l->ActIntBuffer.data0;
                     ItemData->ActIntBuffer.data1 = l->ActIntBuffer.data1;
                     if(Owner->ID == ID_VANGER && (Owner->Status & SOBJ_ACTIVE)) aciSendEvent2actint(ACI_DROP_ITEM,&(l->ActIntBuffer));
                     l->Storage->Deactive(l);
                     Owner->DelDevice(l);
                 }else{
                     ObjectDestroy(ItemData);
                     if(Owner->ID == ID_VANGER && (Owner->Status & SOBJ_ACTIVE)) aciSendEvent2actint(ACI_DROP_ITEM,&(ItemData->ActIntBuffer));
                     ItemData->Storage->Deactive(ItemData);
                     Owner->DelDevice(ItemData);
                     CloseGun();
                 };
             };
             break;
         case ACI_EMPTY_AMPUTATOR:
             if(ActD.Active)
                 SOUND_TERMINATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             GunStatus = GUN_FIRE;
             if(NetworkON) NetUpdate();
             break;
         case ACI_EMPTY_DEGRADATOR:
             if(ActD.Active)
                 SOUND_TERMINATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             GunStatus = GUN_FIRE;
             if(NetworkON) NetUpdate();
             break;
         case ACI_EMPTY_MECHOSCOPE:
             if(ActD.Active)
                 SOUND_TERMINATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
             GunStatus = GUN_FIRE;
             if(NetworkON) NetUpdate();
             break;
     };
 };
References ACI_BEEBBANOZA_BLOCKADE, ACI_CRUSTEST_CANNON, ACI_CRUSTEST_CANNON_AMMO, ACI_DROP_ITEM, ACI_EMPTY_AMPUTATOR, ACI_EMPTY_DEGRADATOR, ACI_EMPTY_MECHOSCOPE, ACI_GHORB_GEAR_HEAVY, ACI_GHORB_GEAR_LIGHT, ACI_MACHOTINE_GUN_HEAVY, ACI_MACHOTINE_GUN_LIGHT, ACI_SPEETLE_SYSTEM_AMMO0, ACI_SPEETLE_SYSTEM_AMMO1, ACI_SPEETLE_SYSTEM_HEAVY, ACI_SPEETLE_SYSTEM_LIGHT, ACI_TERMINATOR, ACI_TERMINATOR2, aciSendEvent2actint(), ActD, StuffObject::ActIntBuffer, ActionDispatcher::Active, aiGetHotBug(), aiPutHotBug(), VangerUnit::BeebonationFlag, PlayerBody::beebos, CloseGun(), ControlFlag, actintItemData::data0, actintItemData::data1, StuffObject::Deactive(), uvsUnitType::DelDevice(), uvsUnitType::DeviceData, VangerUnit::ExternalDraw, getDistX(), getDistY(), GetStuffObject(), GROUND_COLLISION, GUN_FIRE, GUN_READY, GunStatus, Object::ID, ID_VANGER, ItemData, my_player_body, NetUpdate(), NetworkON, StuffObject::NextDeviceList, GeneralObject::NextTypeList, NULL, ObjectDestroy(), Owner, GeneralObject::R_curr, send_player_body(), SOBJ_ACTIVE, SOUND_BEEBBANOZA_SHOT, SOUND_CRUSTEST_SHOT, SOUND_GHORB_BIG_SHOT, SOUND_GHORB_SHOT, SOUND_MACHOTINE_SHOT, SOUND_SPEETLE_SHOT, SOUND_TERMINATOR_SHOT, UnitList::Tail, TargetObject, actintItemData::type, VISIBLE, WHEELS_TOUCH, Object::x, Vector::x, Object::y, and Vector::y.
Referenced by ActionDispatcher::ActiveSlot(), ActionDispatcher::ActiveTerminatorSlot(), VangerUnit::InitEnvironment(), and VangerUnit::ResolveHandlerAttack().
NetEvent()
void GunSlot::NetEvent (unsigned int time)
 {
     int t;
     TargetObject = NULL;
     NETWORK_IN_STREAM > StuffNetID;
     NETWORK_IN_STREAM > NetFireCount;
     NETWORK_IN_STREAM > t;
     if(Owner && Owner->Visibility == VISIBLE && !(Owner->Status & SOBJ_WAIT_CONFIRMATION) && GetDistTime(NetGlobalTime,time) < 5*256){
         if(t) aiTargetObject = ActD.GetNetObject(t);
         else aiTargetObject = NULL;
     }else{
         FireCount = NetFireCount;
         aiTargetObject = NULL;
     };
 };
References ActD, aiTargetObject, FireCount, GetDistTime(), UnitList::GetNetObject(), NetFireCount, NetGlobalTime, NETWORK_IN_STREAM, NULL, Owner, SOBJ_WAIT_CONFIRMATION, StuffNetID, TargetObject, and VISIBLE.
Referenced by NetSlotEvent().
NetStuffQuant()
void GunSlot::NetStuffQuant (void)
 {
     StuffObject* p;
     if(StuffNetID){
         if(!pData){
             ItemData = NULL;
             p = Owner->DeviceData;
             while(p){
                 if(p->NetDeviceID == StuffNetID){
                     ItemData = (GunDevice*)(p);
                     break;
                 };
                 p = p->NextDeviceList;
             };
             if(ItemData){
                 pData = ItemData->pData;
                 RealSpeed = 0;
                 Time = 0;
                 GunStatus = GUN_READY;
                 ControlFlag = 0;
                 TargetObject = NULL;
                 aiTargetObject = NULL;
                 Owner->lay_to_slot(nSlot,&ModelD.ActiveModel(p->ModelID));
                 ItemData->ActIntBuffer.slot = nSlot;
                 FireCount = NetFireCount;
             };
         }else{
             if(ItemData->NetDeviceID != StuffNetID){
                 ItemData->ActIntBuffer.slot = -1;
                 pData = NULL;
                 Owner->lay_to_slot(nSlot,NULL);
             }else{
                 if(FireCount < NetFireCount)
                     RemoteFire();
             };
         };
     }else{
         if(pData){
             ItemData->ActIntBuffer.slot = -1;
             pData = NULL;
             Owner->lay_to_slot(nSlot,NULL);
             FireCount = NetFireCount;
         };
     };
 };
References StuffObject::ActIntBuffer, ModelDispatcher::ActiveModel(), aiTargetObject, ControlFlag, uvsUnitType::DeviceData, FireCount, GUN_READY, GunStatus, ItemData, Object::lay_to_slot(), ModelD, StuffObject::ModelID, StuffObject::NetDeviceID, NetFireCount, StuffObject::NextDeviceList, nSlot, NULL, Owner, GunDevice::pData, pData, RealSpeed, RemoteFire(), actintItemData::slot, StuffNetID, TargetObject, and Time.
Referenced by VangerUnit::ItemQuant().
NetUpdate()
void GunSlot::NetUpdate (void)
 {
     FireCount++;
     NETWORK_OUT_STREAM.update_object(NetID,0,0);
     NETWORK_OUT_STREAM < (int)(Owner->NetID);
     NETWORK_OUT_STREAM < (uchar)(TableIndex);
     NETWORK_OUT_STREAM < (int)(StuffNetID);
     NETWORK_OUT_STREAM < (int)(FireCount);
     if(ActD.LocatorPoint) NETWORK_OUT_STREAM < (int)(ActD.LocatorPoint->NetID);
     else{
         if(TargetObject) NETWORK_OUT_STREAM < (int)(TargetObject->NetID);
         else NETWORK_OUT_STREAM < (int)(0);
     };
     NETWORK_OUT_STREAM.end_body();
 };
References ActD, FireCount, ActionDispatcher::LocatorPoint, GeneralObject::NetID, NetID, NETWORK_OUT_STREAM, Owner, StuffNetID, TableIndex, and TargetObject.
Referenced by Fire().
OpenGun()
void GunSlot::OpenGun (GunDevice * p)
 {
     ItemData = p;
     pData = ItemData->pData;
     RealSpeed = 0;
     Time = 0;
     GunStatus = GUN_READY;
     ControlFlag = 0;
     TargetObject = NULL;
     aiTargetObject = NULL;
     Owner->lay_to_slot(nSlot,&ModelD.ActiveModel(p->ModelID));
     ItemData->ActIntBuffer.slot = nSlot;
     StuffNetID = ItemData->NetDeviceID;
     FireCount = 0;
     NetFireCount = 0;
     if(NetworkON && (Owner->Status & SOBJ_ACTIVE)){
         NETWORK_OUT_STREAM.update_object(NetID,0,0);
         NETWORK_OUT_STREAM < (int)(Owner->NetID);
         NETWORK_OUT_STREAM < (uchar)(TableIndex);
         NETWORK_OUT_STREAM < (int)(StuffNetID);
         NETWORK_OUT_STREAM < (int)(FireCount);
         NETWORK_OUT_STREAM < (int)(0);
         NETWORK_OUT_STREAM.end_body();
     };
     if(Owner->Status & SOBJ_ACTIVE)
         Owner->GetWeaponDelta();
 };
References StuffObject::ActIntBuffer, ModelDispatcher::ActiveModel(), aiTargetObject, ControlFlag, FireCount, VangerUnit::GetWeaponDelta(), GUN_READY, GunStatus, ItemData, Object::lay_to_slot(), ModelD, StuffObject::ModelID, StuffObject::NetDeviceID, NetFireCount, NetID, NETWORK_OUT_STREAM, NetworkON, nSlot, NULL, Owner, GunDevice::pData, pData, RealSpeed, actintItemData::slot, SOBJ_ACTIVE, StuffNetID, TableIndex, TargetObject, and Time.
Referenced by ActionDispatcher::SlotIn(), and VangerUnit::WeaponGenerator().
OpenSlot()
void GunSlot::OpenSlot (int slot, VangerUnit * own, int ind)
 {
     ItemData = NULL;
     pData = NULL;
     Owner = own;
     nSlot = slot;
     Owner->lay_to_slot(nSlot,NULL);
     StuffNetID = 0;
     FireCount = 0;
     NetFireCount = 0;
     TableIndex = ind;
     if(NetworkON){
         if(Owner->Status & SOBJ_ACTIVE){
             NetID = CREATE_NET_ID(NID_SLOT);
             NETWORK_OUT_STREAM.create_permanent_object(NetID,0,0,0);
             NETWORK_OUT_STREAM < (int)(Owner->NetID);
             NETWORK_OUT_STREAM < (uchar)(TableIndex);
             NETWORK_OUT_STREAM < (int)(StuffNetID);
             NETWORK_OUT_STREAM < (int)(FireCount);
             NETWORK_OUT_STREAM < (int)(0);
             NETWORK_OUT_STREAM.end_body();
         }else NetID = 0;
     };
 };
References CREATE_NET_ID, FireCount, ItemData, Object::lay_to_slot(), NetFireCount, NetID, NETWORK_OUT_STREAM, NetworkON, NID_SLOT, nSlot, NULL, Owner, pData, SOBJ_ACTIVE, StuffNetID, and TableIndex.
Referenced by VangerUnit::ChangeVangerProcess(), and VangerUnit::Go2World().
Quant()
void GunSlot::Quant (void)
 {
     BulletObject* b;
     JumpBallObject* g;
     int i;
     Vector vCheck;
     switch(pData->BulletID){
         case BULLET_TYPE_ID::HYPNOTISE:
             if(GunStatus == GUN_FIRE){
                 ItemData->Time = pData->LifeTime;
                 if(Owner->Status & SOBJ_ACTIVE){
                     ActD.CheckDevice(ItemData);
                     Owner->CheckOutDevice(ItemData);
                     aciRemoveItem(&(ItemData->ActIntBuffer));
 //                  aciSendEvent2actint(ACI_DROP_ITEM,&(ItemData->ActIntBuffer));
                 }else
                     Owner->CheckOutDevice(ItemData);
                 vCheck = Vector(HYPNOTISE_WEAPON_RADIUS,0,0)*Owner->MovMat;
                 vCheck += Owner->R_curr;
                 cycleTor(vCheck.x,vCheck.y);
                 ItemData->DeviceOut(Owner->R_curr + Vector(0,0,Owner->radius*4),1,vCheck);
                 CloseGun();
                 GunStatus = GUN_READY;
             };
             break;
         case BULLET_TYPE_ID::ROCKET:
         case BULLET_TYPE_ID::FIREBALL:
         case BULLET_TYPE_ID::TERMINATOR:
             switch(GunStatus){
                 case GUN_FIRE:
                     if(Owner->Status & SOBJ_ACTIVE){
                         if(ActD.LocatorPoint)
                             TargetObject = ActD.LocatorPoint;
                     }else{
                         if(aiTargetObject)
                             TargetObject = aiTargetObject;
                         else
                             TargetObject = NULL;
                     };
                     b = BulletD.CreateBullet();
                     Time = 0;
                     if(Owner->Speed > 0) RealSpeed = Owner->Speed;
                     else RealSpeed = 0;
                     mFire = Owner->RotMat;
                     vFire = Owner->R_curr;
                     if((1 << ItemData->ActIntBuffer.slot) & Owner->slots_existence) vFire += Owner->A_l2g*(Owner->R_slots[ItemData->ActIntBuffer.slot]*Owner->scale_real);
                     cycleTor(vFire.x,vFire.y);
                     b->Owner = Owner;
                     b->CreateBullet(this,pData);
                     GunStatus = GUN_WAIT;
                     break;
                 case GUN_WAIT:
                     Time++;
                     if(Time > pData->WaitTime) GunStatus = GUN_READY;
                     break;
             };
             break;
         case BULLET_TYPE_ID::LASER:
             switch(GunStatus){
                 case GUN_FIRE:
                     Time = 0;
                     if(Owner->Speed > 0) RealSpeed = Owner->Speed;
                     else RealSpeed = 0;
                     mFire = Owner->RotMat;
                     vFire = Owner->R_curr;
                     if((1 << ItemData->ActIntBuffer.slot) & Owner->slots_existence) vFire += Owner->A_l2g*(Owner->R_slots[ItemData->ActIntBuffer.slot]*Owner->scale_real);
                     cycleTor(vFire.x,vFire.y);
                     GunStatus = GUN_WAIT;
                     for(i = 0;i < pData->TapeSize;i++){
                         b = BulletD.CreateBullet();
                         b->Owner = Owner;
                         b->CreateBullet(this,pData);
                     };
                     break;
                 case GUN_WAIT:
                     Time++;
                     if(Time > pData->WaitTime) GunStatus = GUN_READY;
                     break;
             };
             break;
         case BULLET_TYPE_ID::HORDE:
             switch(GunStatus){
                 case GUN_FIRE:
                     Time = 0;
                     mFire = Owner->RotMat;
                     vFire = Owner->R_curr + Vector(0,0,Owner->radius*2);
                     cycleTor(vFire.x,vFire.y);
                     GunStatus = GUN_WAIT;
                     (HordeD.CreateHorde())->CreateHorde(vFire,20,240,400,Owner);
                     break;
                 case GUN_WAIT:
                     Time++;
                     if(Time > pData->WaitTime) GunStatus = GUN_READY;
                     break;
             };
             break;
         case BULLET_TYPE_ID::JUMPBALL:
             switch(GunStatus){
                 case GUN_FIRE:
                     Time = 0;
                     mFire = Owner->RotMat;
                     vFire = Owner->R_curr + Vector(0,0,Owner->radius*2);
                     cycleTor(vFire.x,vFire.y);
                     GunStatus = GUN_WAIT;
                     if(pData->TargetMode == BULLET_TARGET_MODE::CONTROL){
                         for(i = 0;i < pData->TapeSize;i++){
                             g = JumpD.CreateBall();
                             g->CreateBullet(this,pData);
                         };
                     }else{
                         g = JumpD.CreateBall();
                         g->CreateBullet(this,pData);
                     };
                     break;
                 case GUN_WAIT:
                     Time++;
                     if(Time > pData->WaitTime) GunStatus = GUN_READY;
                     break;
             };
             break;
     };
 };
References Object::A_l2g, aciRemoveItem(), ActD, StuffObject::ActIntBuffer, aiTargetObject, BulletD, BulletControlType::BulletID, ActionDispatcher::CheckDevice(), VangerUnit::CheckOutDevice(), CloseGun(), BULLET_TARGET_MODE::CONTROL, JumpBallList::CreateBall(), BulletObject::CreateBullet(), BulletList::CreateBullet(), HordeList::CreateHorde(), cycleTor(), GunDevice::DeviceOut(), BULLET_TYPE_ID::FIREBALL, g, GUN_FIRE, GUN_READY, GUN_WAIT, GunStatus, BULLET_TYPE_ID::HORDE, HordeD, BULLET_TYPE_ID::HYPNOTISE, HYPNOTISE_WEAPON_RADIUS, ItemData, BULLET_TYPE_ID::JUMPBALL, JumpD, BULLET_TYPE_ID::LASER, WorldBulletTemplate::LifeTime, ActionDispatcher::LocatorPoint, mFire, ActionUnit::MovMat, NULL, BulletObject::Owner, Owner, pData, Object::R_slots, Object::radius, RealSpeed, BULLET_TYPE_ID::ROCKET, ActionUnit::RotMat, Object::scale_real, actintItemData::slot, Object::slots_existence, SOBJ_ACTIVE, ActionUnit::Speed, WorldBulletTemplate::TapeSize, BulletControlType::TargetMode, TargetObject, BULLET_TYPE_ID::TERMINATOR, StuffObject::Time, Time, vFire, WorldBulletTemplate::WaitTime, Vector::x, and Vector::y.
Referenced by VangerUnit::ItemQuant().
RemoteFire()
void GunSlot::RemoteFire (void)
 {
     if(GunStatus != GUN_READY || Owner->BeebonationFlag || !(Owner->ExternalDraw)) return;
     FireCount++;
     TargetObject = NULL;
     GunStatus = GUN_FIRE;
     if(ActD.Active){
         switch(ItemData->ActIntBuffer.type){
             case ACI_MACHOTINE_GUN_HEAVY:
             case ACI_MACHOTINE_GUN_LIGHT:
                 SOUND_MACHOTINE_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
             case ACI_GHORB_GEAR_LIGHT:
             case ACI_GHORB_GEAR_HEAVY:
                 SOUND_GHORB_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
             case ACI_SPEETLE_SYSTEM_LIGHT:
             case ACI_SPEETLE_SYSTEM_HEAVY:
                 SOUND_SPEETLE_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
             case ACI_BEEBBANOZA_BLOCKADE:
                 SOUND_BEEBBANOZA_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
             case ACI_CRUSTEST_CANNON:
                 SOUND_CRUSTEST_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
             case ACI_TERMINATOR2:
             case ACI_TERMINATOR:
                 SOUND_TERMINATOR_SHOT(getDistX(ActD.Active->R_curr.x,Owner->R_curr.x));
                 break;
         };
     };
 };
References ACI_BEEBBANOZA_BLOCKADE, ACI_CRUSTEST_CANNON, ACI_GHORB_GEAR_HEAVY, ACI_GHORB_GEAR_LIGHT, ACI_MACHOTINE_GUN_HEAVY, ACI_MACHOTINE_GUN_LIGHT, ACI_SPEETLE_SYSTEM_HEAVY, ACI_SPEETLE_SYSTEM_LIGHT, ACI_TERMINATOR, ACI_TERMINATOR2, ActD, StuffObject::ActIntBuffer, ActionDispatcher::Active, VangerUnit::BeebonationFlag, VangerUnit::ExternalDraw, FireCount, getDistX(), GUN_FIRE, GUN_READY, GunStatus, ItemData, NULL, Owner, SOUND_BEEBBANOZA_SHOT, SOUND_CRUSTEST_SHOT, SOUND_GHORB_SHOT, SOUND_MACHOTINE_SHOT, SOUND_SPEETLE_SHOT, SOUND_TERMINATOR_SHOT, TargetObject, actintItemData::type, and Object::x.
Referenced by NetStuffQuant().
Member Data Documentation
aiTargetObject
GeneralObject* GunSlot::aiTargetObject
Referenced by CheckTarget(), NetEvent(), NetStuffQuant(), OpenGun(), and Quant().
ControlFlag
int GunSlot::ControlFlag
Referenced by Fire(), NetStuffQuant(), and OpenGun().
FireCount
int GunSlot::FireCount
Referenced by CloseGun(), VangerUnit::InitPlayerPoint(), NetEvent(), NetStuffQuant(), NetUpdate(), OpenGun(), OpenSlot(), and RemoteFire().
GunStatus
int GunSlot::GunStatus
Referenced by Fire(), NetStuffQuant(), OpenGun(), Quant(), RemoteFire(), and VangerUnit::ResolveHandlerAttack().
ItemData
GunDevice* GunSlot::ItemData
Referenced by VangerUnit::CheckAmmo(), VangerUnit::CheckSpeetle(), CloseGun(), Fire(), NetStuffQuant(), OpenGun(), OpenSlot(), Quant(), and RemoteFire().
mFire
DBM GunSlot::mFire
Referenced by BulletObject::CreateBullet(), JumpBallObject::CreateBullet(), and Quant().
mPlace
DBM GunSlot::mPlace
NetFireCount
int GunSlot::NetFireCount
Referenced by CloseGun(), VangerUnit::InitPlayerPoint(), NetEvent(), NetStuffQuant(), OpenGun(), and OpenSlot().
NetID
int GunSlot::NetID
Referenced by CloseGun(), CloseSlot(), VangerUnit::InitPlayerPoint(), NetSlotEvent(), NetUpdate(), OpenGun(), and OpenSlot().
nSlot
int GunSlot::nSlot
Referenced by CloseGun(), CloseSlot(), NetStuffQuant(), OpenGun(), and OpenSlot().
Owner
VangerUnit* GunSlot::Owner
Referenced by VangerUnit::ChangeVangerProcess(), CheckTarget(), CloseGun(), CloseSlot(), JumpBallObject::CreateBullet(), Fire(), VangerUnit::Go2World(), NetEvent(), NetStuffQuant(), NetUpdate(), OpenGun(), OpenSlot(), Quant(), and RemoteFire().
pData
WorldBulletTemplate* GunSlot::pData
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::CheckAmmo(), VangerUnit::CheckSpeetle(), CheckTarget(), CloseGun(), VangerUnit::GetAllert(), VangerUnit::GetWeaponDelta(), VangerUnit::Go2World(), VangerUnit::InitEnvironment(), VangerUnit::ItemQuant(), NetStuffQuant(), OpenGun(), OpenSlot(), Quant(), VangerUnit::ResolveHandlerAttack(), and VangerUnit::WeaponGenerator().
RealSpeed
int GunSlot::RealSpeed
Referenced by BulletObject::CreateBullet(), NetStuffQuant(), OpenGun(), and Quant().
StuffNetID
int GunSlot::StuffNetID
Referenced by CloseGun(), VangerUnit::InitPlayerPoint(), NetEvent(), NetStuffQuant(), NetUpdate(), OpenGun(), and OpenSlot().
TableIndex
int GunSlot::TableIndex
Referenced by CloseGun(), NetUpdate(), OpenGun(), and OpenSlot().
TargetObject
GeneralObject* GunSlot::TargetObject
Referenced by BulletObject::CreateBullet(), Fire(), NetEvent(), NetStuffQuant(), NetUpdate(), OpenGun(), Quant(), and RemoteFire().
Time
int GunSlot::Time
Referenced by NetStuffQuant(), OpenGun(), and Quant().
vFire
Vector GunSlot::vFire
Referenced by BulletObject::CreateBullet(), JumpBallObject::CreateBullet(), and Quant().
vPlace
Vector GunSlot::vPlace
The documentation for this struct was generated from the following files:
src/units/mechos.h
src/units/mechos.cpp