Vangers: PassageEngine Struct Reference
PassageEngine Struct Reference
#include <sensor.h>
Public Member Functions
void Open (Parser &in)
void Close (void)
void Quant (void)
void Link (void)
Public Member Functions inherited from LocationEngine
virtual void Touch (GeneralObject *obj, SensorDataType *p)
void NetEvent (void)
void SoundEvent (void)
Public Attributes
uvsPassage * uvsPort
SensorDataType * ActionLink
char * PassageName
Public Attributes inherited from LocationEngine
int NetID
int Type
int Mode
int NetMode
MobileLocation * MLLink
int ActivePhase
int DeactivePhase
int Enable
int ActiveTime
int DeactiveTime
int * CheckIndex
int SoundID
int HideFlag
int UpdateFlag
Vector R_curr
int radius
int TabuUse
Detailed Description
Member Function Documentation
Close()
void PassageEngine::Close (void) virtual
Reimplemented from LocationEngine.
 {
     delete[] PassageName;
 };
References PassageName.
Link()
void PassageEngine::Link (void) virtual
Reimplemented from LocationEngine.
 {
     uvsPassage* pe;
     uvsPort = NULL;
     pe = (uvsPassage*)PassageTail;
     while(pe){
         if(!strcmp(pe->name,PassageName)){
             uvsPort = pe;
             break;
         };
         pe = (uvsPassage*)(pe -> next);
     };
     if(!uvsPort)
         ErrH.Abort("Bad uvsPort");
     uvsPort->unitPtr.PassageT = this;
     uvsPort->locked = 0;
 };
References uvsPassage::name, NULL, PassageName, PassageTail, and uvsPort.
Open()
void PassageEngine::Open (Parser & in) virtual
Reimplemented from LocationEngine.
 {
     char* n;
     LocationEngine::Open(in);
     Type = EngineTypeList::PASSAGE;
     in.search_name("ActionName");
     n = in.get_name();
     ActionLink = FindSensor(n);
     if(!ActionLink)
         ErrH.Abort("Bad Find Sensor");
     ActionLink->Owner = this;
     ActionLink->Enable = 1;
     in.search_name("PassageName");
     n = in.get_name();
     PassageName = new char[strlen(n) + 1];
     strcpy(PassageName,n);
 };
References XErrorHandler::Abort(), ActionLink, StaticObject::Enable, ErrH, FindSensor(), Parser::get_name(), LocationEngine::Open(), SensorDataType::Owner, EngineTypeList::PASSAGE, PassageName, Parser::search_name(), and LocationEngine::Type.
Quant()
void PassageEngine::Quant (void) virtual
Reimplemented from LocationEngine.
 {
 };
Member Data Documentation
ActionLink
SensorDataType* PassageEngine::ActionLink
Referenced by Open().
PassageName
char* PassageEngine::PassageName
Referenced by Close(), Link(), and Open().
uvsPort
uvsPassage* PassageEngine::uvsPort
Referenced by Link().
The documentation for this struct was generated from the following files:
src/units/sensor.h
src/units/sensor.cpp