Vangers: EscaveOutRTO Struct Reference
EscaveOutRTO Struct Reference
#include <runtime.h>
Public Member Functions
virtual void Init (int id)
virtual int Quant (void)
virtual void Finit (void)
EscaveOutRTO (void)
Public Member Functions inherited from BaseRTO
void SetNext (int id)
void SetFlag (int fl)
void ClearFlag (int fl)
BaseRTO (void)
Public Member Functions inherited from XRuntimeObject
void SetTimer (int t)
XRuntimeObject (void)
XRuntimeObject (int id)
XRuntimeObject (int id, int tm)
~XRuntimeObject (void)
Additional Inherited Members
Public Attributes inherited from BaseRTO
int flags
int NextID
Public Attributes inherited from XRuntimeObject
int ID
int Timer
XRuntimeObject * next
Detailed Description
Constructor & Destructor Documentation
EscaveOutRTO()
EscaveOutRTO::EscaveOutRTO (void) inline
 { ID = RTO_ESCAVE_OUT_ID; Timer = RTO_ISCREEN_TIMER; }
References XRuntimeObject::ID, RTO_ESCAVE_OUT_ID, RTO_ISCREEN_TIMER, and XRuntimeObject::Timer.
Member Function Documentation
Finit()
void EscaveOutRTO::Finit (void) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
     iOutEscaveFinit();
     aci_LocationQuantFinit();
     if(!iAbortGameFlag)
         uvsCloseQuant();
 #endif
 _MEM_STATISTIC_("AFTER ESCAVE FINIT -> ");
 }
References _MEM_STATISTIC_, aci_LocationQuantFinit(), iAbortGameFlag, iOutEscaveFinit(), and uvsCloseQuant().
Init()
void EscaveOutRTO::Init (int id) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
     iOutEscaveInit();
 #endif
 _MEM_STATISTIC_("AFTER ESCAVE INIT -> ");
 }
References _MEM_STATISTIC_, and iOutEscaveInit().
Quant()
int EscaveOutRTO::Quant (void) virtual
Reimplemented from XRuntimeObject.
 {
 #ifdef ISCREEN
     int val = iOutEscaveQuant();
     if(val){
         if(iAbortGameFlag){
             iAbortGameMode = 2;
             return RTO_LOADING3_ID;
         }
         else
             return NextID;
     }
     //XGR_Flip();
     return 0;
 #else
     return NextID;
 #endif
 }
References iAbortGameFlag, iAbortGameMode, iOutEscaveQuant(), BaseRTO::NextID, and RTO_LOADING3_ID.
The documentation for this struct was generated from the following files:
src/runtime.h
src/road.cpp