Vangers: FishWarriorList Struct Reference
FishWarriorList Struct Reference
#include <items.h>
Public Member Functions
void Init (void)
void FreeUnit (GeneralObject *p)
void Free (void)
Public Member Functions inherited from UnitBaseListType
virtual void ConnectTypeList (GeneralObject *p)
virtual void DisconnectTypeList (GeneralObject *p)
Public Member Functions inherited from UnitListType
virtual void Quant (void)
virtual void NetEvent (int type, int id)
GeneralObject * GetNetObject (int id)
void ClearNet (void)
Public Attributes
FishWarrior * Data
Public Attributes inherited from UnitListType
int Num
GeneralObject * Tail
Detailed Description
Member Function Documentation
Free()
void FishWarriorList::Free (void) virtual
Reimplemented from UnitListType.
 {
     UnitBaseListType::Free();
     if(Data) delete[] Data;
 };
References Data, and UnitListType::Free().
Referenced by GeneralSystemClose().
FreeUnit()
void FishWarriorList::FreeUnit (GeneralObject * p) virtual
Reimplemented from UnitListType.
 {
     DisconnectTypeList(p);
 };
References UnitBaseListType::DisconnectTypeList().
Init()
void FishWarriorList::Init (void) virtual
Reimplemented from UnitListType.
 {
 /*
 //zmod 1.17 as it was before
     int i;
     if(CurrentWorld == WORLD_WEEXOW && !NetworkON){
         Data = new FishWarrior[MAX_FISH_WARRIOR];
         for(i = 0;i < MAX_FISH_WARRIOR;i++){
             Data[i].Init();
             Data[i].CreateFish(Vector(RND(map_size_x),RND(map_size_y),10),20,RND(2*PI),5,2000,FISH_WARRIOR_PATROL,ModelD.FindModel("FishWarrior"),NULL,100 << 16);
             ConnectTypeList(&Data[i]);
         };
     }else Data = NULL;
 */
     int i;
     if(!NetworkON){
         if(CurrentWorld == WORLD_WEEXOW){
             Data = new FishWarrior[MAX_FISH_WARRIOR];
             for(i = 0;i < MAX_FISH_WARRIOR;i++){
                 Data[i].Init();
                 Data[i].CreateFish(Vector(RND(map_size_x),RND(map_size_y),10),20,RND(2*PI),5,2000,FISH_WARRIOR_PATROL,ModelD.FindModel("FishWarrior"),NULL,100 << 16);
                 ConnectTypeList(&Data[i]);
             };
         } else Data = NULL;
     } else {
         int max = MAX_FISH_WARRIOR;
 //zmod 1.21
         max /= 2;
         switch(CurrentWorld){
             case WORLD_GLORX:
                 if (z_my_server_data.mod_id == Z_MODS_FORMULAV_ID)
                     max = 512;
             case WORLD_WEEXOW:
                 if (z_my_server_data.mod_id == Z_MODS_NEPTUN_ID) //zmod 1.20 neptun fix
                     max = 2;
                 Data = new FishWarrior[max];
                 for(i = 0;i < max;i++){
                     Data[i].Init();
                     Data[i].CreateFish(
                         Vector(NetRnd.Get(map_size_x),NetRnd.Get(map_size_y),10),
                         20,
                         NetRnd.Get(2*PI),
                         5,
                         1200 + RND(1200),
                         FISH_WARRIOR_PATROL,
                         ModelD.FindModel("FishWarrior"),
                         NULL,
                         100 << 16
                     ); //create fish
                     ConnectTypeList(&Data[i]);
                 }; //for
                 break;
             default:
                 Data = NULL;
                 break;
         };//switch
     };//networkon
 };
References UnitBaseListType::ConnectTypeList(), FishWarrior::CreateFish(), CurrentWorld, Data, ModelDispatcher::FindModel(), FISH_WARRIOR_PATROL, NetRndType::Get(), FishWarrior::Init(), map_size_x, map_size_y, max(), MAX_FISH_WARRIOR, zServerData::mod_id, ModelD, NetRnd, NetworkON, NULL, PI, RND(), WORLD_GLORX, WORLD_WEEXOW, Z_MODS_FORMULAV_ID, Z_MODS_NEPTUN_ID, and z_my_server_data.
Referenced by GeneralSystemOpen().
Member Data Documentation
Data
FishWarrior* FishWarriorList::Data
Referenced by Free(), and Init().
The documentation for this struct was generated from the following files:
src/units/items.h
src/units/items.cpp