Vangers: TopList Struct Reference
TopList Struct Reference
#include <network.h>
Public Member Functions
TopList (int MP_game)
~TopList ()
Public Member Functions inherited from XTList< RatingData >
XTList ()
~XTList ()
int size ()
RatingData * first ()
RatingData * last ()
void clear ()
void delete_all ()
void insert (RatingData *p)
void insert (RatingData *pointer, RatingData *p)
void append (RatingData *p)
void append (RatingData *pointer, RatingData *p)
void remove (RatingData *p)
RatingData * search (int ID)
Detailed Description
Constructor & Destructor Documentation
TopList()
TopList::TopList (int MP_game)
 {
     events_out.send_simple_query(TOP_LIST_QUERY,MP_game);
     events_in.receive_waiting_for_event(TOP_LIST_RESPONSE);
     char name[257];
     float rating;
     RatingData* p;
     events_in.get_byte();
     int num = events_in.get_byte();
     while(num--){
         events_in > name > rating;
         p = new RatingData(name,rating);
         append(p);
         }
     events_in.ignore_event();
 }
References XTList< RatingData >::append(), events_in, events_out, InputEventBuffer::get_byte(), InputEventBuffer::ignore_event(), InputEventBuffer::receive_waiting_for_event(), OutputEventBuffer::send_simple_query(), TOP_LIST_QUERY, and TOP_LIST_RESPONSE.
~TopList()
TopList::~TopList ()
 {
     delete_all();
 }
References XTList< RatingData >::delete_all().
The documentation for this struct was generated from the following files:
src/network.h
src/network.cpp