Vangers: LandQuake Struct Reference
LandQuake Struct Reference
#include <light.h>
Public Member Functions
LandQuake (void)
~LandQuake (void)
void set (int _x, int _y, int _Rmin, int _Rmax, int _dx=0)
int quant (int)
Public Attributes
int x
int y
int Rmin
int Rmax
int Rcur
int dx
Detailed Description
Constructor & Destructor Documentation
LandQuake()
LandQuake::LandQuake (void) inline
 {Rmax = 0; Rcur = 1;};
References Rcur, and Rmax.
~LandQuake()
LandQuake::~LandQuake (void) inline
 {};
Member Function Documentation
quant()
int LandQuake::quant (int shiftparam)
{
     int dd, da, yy, xx, delta;
     xx = 0;
     yy = Rcur;
     dd = 2*( 1 - Rcur);
     delta = 0;
     if (Rcur > Rmax) return 0;
     while( yy > delta){
         LineQuake( x + xx, yy + y, x, y, dx, shiftparam );
         LineQuake( x - xx, yy + y, x, y, dx, shiftparam );
         LineQuake( x + xx, y - yy , x, y, dx, shiftparam );
         LineQuake( x - xx, y - yy , x, y, dx, shiftparam );
         if (dd < 0){
             da = 2*(dd + yy) - 1;
             if (da <= 0){
                 xx++;
                 dd += 2*xx + 1;
             } else if ( da > 0){
                 xx++;
                 yy--;
                 dd += 2*(xx - yy + 1);
             }
         } else if (dd > 0){
             da = 2*(dd + xx) - 1;
             if (da <= 0){
                 xx++;
                 yy--;
                 dd += 2*(xx - yy + 1);
             } else if ( da > 0){
                 yy--;
                 dd += 1 - 2*yy;
             }
         } else {
             xx++;
             yy--;
             dd += 2*(xx - yy + 1);
         }
     }//  while
     Rcur += dx;
     return 1;
 }
References dx, LineQuake(), Rcur, Rmax, x, and y.
Referenced by ActionDispatcher::DrawResource().
set()
void LandQuake::set (int _x, int _y, int _Rmin, int _Rmax, int _dx = 0)
{
     x = _x;
     y = _y;
     Rcur = Rmin = _Rmin;
     Rmax = _Rmax;
     dx = _dx;
 };
References dx, Rcur, Rmax, Rmin, x, and y.
Referenced by ActionDispatcher::DrawResource(), ActionDispatcher::FunctionQuant(), VangerFunctionType::Init(), ActionDispatcher::NewFunction(), and VangerFunctionType::Quant().
Member Data Documentation
dx
int LandQuake::dx
Referenced by quant(), and set().
Rcur
int LandQuake::Rcur
Referenced by LandQuake(), quant(), and set().
Rmax
int LandQuake::Rmax
Referenced by LandQuake(), quant(), and set().
Rmin
int LandQuake::Rmin
Referenced by set().
x
int LandQuake::x
Referenced by quant(), and set().
y
int LandQuake::y
Referenced by quant(), and set().
The documentation for this struct was generated from the following files:
src/particle/light.h
src/particle/light.cpp