Vangers: src/uvs/univang.cpp File Reference
univang.cpp File Reference
#include "../global.h"
#include "../common.h"
#include "../network.h"
#include "../actint/item_api.h"
#include "../actint/credits.h"
#include "../units/uvsapi.h"
#include "../units/compas.h"
#include "../runtime.h"
#include "../3d/3d_math.h"
#include "../3d/parser.h"
#include "../terra/vmap.h"
#include "../sound/hsound.h"
#include "diagen.h"
#include "univang.h"
Macros
#define CIRT_FOR_CONLARVER 16
#define CASH_FOR_DOLLY 20000
#define MAX_TABUTASK_RESERVED 100
Functions
void LoadingMessage (int flush=0)
void ChangeVanger (void)
int uvsSecretON (void)
void uvs_aciChangeOneItem (int, int, int, int)
int uvs_aciKillOneItem (int id, int x, int y)
void uvs_aciChangeOneItem (int id_from, int id_to, uvsActInt *ptr)
void uvsDeleteItem (listElem *&pe, int type, int count)
void uvsCheckAllItem (void)
char * get_string (XStream &pfile)
void put_string (XStream &, char *)
void ReadPriceList (void)
void aciSaveData (void)
int thief_on_world (void)
void uvsSetTownName (char *)
void uvsChangeGoodsInList (int world)
int uvsReturnTreasureStatus (int Type, int TreasureStatus=uvsTreasureInGamer)
int GetItem_as_name (char *)
int GetMechos_as_name (char *)
int ItemCount (listElem *Pitem, int ItemType, int what=0)
uvsItem * GetItem (listElem *, int, int)
uvsItem * GetItem_as_type (listElem *pe, int status, int work=0, int index=0)
uvsVanger * FindFreeVanger (void)
uvsEscave * uvsGetEscaveByID (int type)
uvsSpot * uvsGetSpotByID (int type)
int uvsCheckItem (int type)
void uvsCheckVangerTabuTask (uvsVanger *, int)
void uvsCheckItemOnTabuTask (listElem *&, int ID, int IDCount, int what=1)
void uvsChangeTabuTask (int, int)
void uvsRestoreTabuTask (void)
void uvsPassagerFromStatistic (void)
int uvsPoponkaIDON (listElem *Pitem)
int uvsKillerNow (void)
int get_power (int)
int ActInt_to_Item (int)
int uvsMechosType_to_AciInt (int)
void uvsRestoreVanger (void)
void FirstShopPrepare (int how)
void uvsMechosSave (XStream &)
void uvsMechosLoad (XStream &)
void MLReset (void)
int getRW (int n)
void uniVangPrepare (void)
void GeneralSystemInit (void)
void GeneralSystemFree (void)
void GeneralSystemClose (void)
void GeneralSystemOpen (void)
void uvsAddStationaryObjs (void)
void uvsWorldReload (int newW)
uvsWorld * getWorld (int n)
void uvsBunchCheck (char *subj)
int isCycleExist (int cycle, char ew)
int getPreviousCycle (int cycle)
void FreeList (listElem *&pe)
void FreeFarmer (uvsElement *&pe)
void uvsChangeCycle (void)
void uvsQuant (void)
void uniVangSave (XStream &pfile)
void CloseCyclicPal (void)
void OpenCyclicPal (void)
void GeneralTableOpen (void)
void uniVangLoad (XStream &pfile)
void uniVangDelete (void)
int ActInt_param2 (int InType)
int uvsChangeGoodsParam (int type, int &param1, int &param2, int world)
int uvsChangeTabuTask (int &param1, int &param2, int type, int status)
void WaitGameInTown (int cWorld)
void WaitEndGameInTown (int cWorld)
void _FirstShopPrepare (void)
void FinishFirstShopPrepare (int how)
int uvsSetItemType (int type, int param1, int param2)
void uvsPrepareQuant (void)
void uvsCloseQuant (void)
void uvsCreateNewCrypt (int x, int y, int z, int type, int iWorld)
void uvsCreateNewItem (int x, int y, int z, int type, int iWorld)
void uvsCreateItem_in_Crypt (void)
int uvsCatchDolly (uvsDolly *pd)
int uvsFreeDolly (int _x, int _y, int _index_)
int uvsgetDGdata (int code)
void uvsMakeGamerFromSlave (uvsVanger *pv)
uvsVanger * uvsMakeNewGamerInEscave (uvsEscave *pe, int what)
void uvsChangeRaiting (void)
void uvsSetTownName (const char *_name_)
int uvsGenerateItemForCrypt (int type)
void uvsDomChangeFromItem (int type, int what, int where)
int uvsTagetID (char *s)
int uvsTagetWorkID (char *s)
char * uvsGetLarvaWorld (int n)
uvsPassage * GetPassage (int fromWID, int toWID)
void uvsCheckKronIventTabuTask (int KronType, int KronCount, int MYresult, int MYitem)
char * uvsGetNameByID (int type, int &ID)
void uvsActIntSell (uvsActInt *pa)
void uvsActIntSellMechos (uvsActInt *pn)
void uvsKronDeleteItem (int type, int param1, int param2)
int uvsGameRaceNumber (void)
int uvsGameRaceFinish (void)
void uvsChangeTownTabuTask (int type)
int uvsPrepareItemToDiagen (int type, int param1, int param2, int &what, int &ID, char *&NameFrom, char *&NameTo)
void uvsChangeLuck (void)
void uvsChangeDominance (void)
uvsVanger * uvsCreateNetVanger (int CarType, int Color, int PassageIndex, int TownTabutaskID)
int uvsReturnWorldGamerVisit (int where)
int getWorldVisitStats (char wc)
int getPassangerStats (char efrom, char wto)
int getPassangerFrom (char efrom)
void uvsTabuComplete (int i)
void uvsTabuCreate (uvsActInt *pa, int num)
void uvsBoorawchickZero (void)
int uvsCheckItemOnLive (int type)
void uvsOnKillItem (void)
void uvsLuckChange (int delta)
int uvsWorldToCross (int fromWID, int toWID)
Variables
const int TABUTASK_BAD = ACI_TABUTASK_FAILED
const int TABUTASK_GOOD = ACI_TABUTASK_SUCCESSFUL
int RACE_WAIT = 300
int uvsKronActive = 0
int uvsVersion = 14
int uvsLoadVersion = 0
int uvsCurrentWorldUnable = 0
int uvsCurrentWorldUnableBefore = 0
int uvsEndHarvest = 0
int uvsQuantFlag = 0
int uvsTabuTaskX = 0
int uvsTabuTaskY = 0
int uvsTabuTaskFlag = 0
int Dead
int Quit
int GameQuantReturnValue
int NetworkON
NetRndType NetRnd
int ChangeArmor
int dgAbortStatus
uchar * actIntPal
int GeneralMapReload = 0
uchar ** WorldPalData
const int uvsVANGER_ARRIVAL = 0
const int uvsVANGER_FAILED = 1
const int uvsVANGER_KILLED = 2
const char * BIOS_NAMES [BIOS_MAX]
listElem * EscaveTail = NULL
listElem * SpotTail = NULL
listElem * PassageTail = NULL
uvsTabuTaskType ** TabuTable
listElem * DollyTail = NULL
uvsMechosType ** uvsMechosTable
uvsItemType ** uvsItemTable
const char * uvsTownName = NULL
uvsActInt * GMechos
uvsActInt * GGamerMechos
uvsActInt * GItem
uvsActInt * GGamer = NULL
uvsActInt * GCharItem = NULL
uvsActInt * GTreasureItem = NULL
uvsGamerResult GamerResult
uvsWorld * WorldTable [WORLD_MAX]
int uvsCurrentCycle = 0
int CurrentWorld
int uvsRandomWorld = 0
int uvsUnikumeMechos = 1
int uvsQuantity = 0
int uvsGamerWaitGame = 0
time_t uvsFirstTime = 0
int uvsNetworkChangeWorld = 0
uvsContimer ConTimer
int cVngNumber
int c_All_Number
int c_S_Number
int c_R_Number
int c_A_Number
int MAX_TABUTASK = 0
int MAX_ITEM_TYPE = 0
int MAX_MECHOS_TYPE = 0
int MAX_MECHOS_MAIN = 0
int MAX_MECHOS_RAFFA = 0
int MAX_MECHOS_CONSTRACTOR = 0
int MAX_PART_MACHOS = 2
int GamePoint
int uvsBunchNumber = 0
int uvsPoponkaID = 0
uvsElement * ETail = NULL
uvsElement * deleteETail = NULL
uvsVanger * Gamer
uchar * palbufOrg
uchar * palbufSrc
uchar * palbuf
int WorldPalCurrent
int light_modulation
int WorldLightParam [WORLD_MAX][3]
int lastMechos
int ChangeWorldSkipQuant
int GeneralSystemSkip
const int ELEECH [5] = { 2000, 1000, 300, 100, 50}
const int PIPETKA [3] = { 1500, 1000, 500 }
const int KERNOBOO [3] = { 3000, 1000, 300}
const int WEEZYK [1] = { 5000}
Macro Definition Documentation
CASH_FOR_DOLLY
#define CASH_FOR_DOLLY 20000
CIRT_FOR_CONLARVER
#define CIRT_FOR_CONLARVER 16
MAX_TABUTASK_RESERVED
#define MAX_TABUTASK_RESERVED 100
Function Documentation
_FirstShopPrepare()
void _FirstShopPrepare (void)
{
         Gamer -> Pescave -> Pshop -> sellMechos(Gamer -> Pmechos);
 }
References Gamer, and uvsEscave::Pshop.
aciSaveData()
void aciSaveData (void)
 {
     acsSaveData();
 }
References acsSaveData().
ActInt_param2()
int ActInt_param2 (int InType)
{
     return uvsItemTable[ActInt_to_Item(InType)] -> param2;
 }
References ActInt_to_Item(), and uvsItemTable.
ActInt_to_Item()
int ActInt_to_Item (int InType)
{
     int i;
     if (InType == TABUTASK_GOOD)
         return UVS_ITEM_TYPE::TABUTASK;
     if (InType == TABUTASK_BAD)
         return UVS_ITEM_TYPE::TABUTASK;
     for( i = 0; i < MAX_ITEM_TYPE; i++)
         if( uvsItemTable[i] -> SteelerTypeFull == InType ) return i;
     for( i = 0; i < MAX_ITEM_TYPE; i++)
         if( (uvsItemTable[i] -> SteelerTypeEmpty) == InType ) return i;
     return -1;
 }
References MAX_ITEM_TYPE, UVS_ITEM_TYPE::TABUTASK, TABUTASK_BAD, TABUTASK_GOOD, and uvsItemTable.
Referenced by ActInt_param2(), uvsShop::get_list_from_ActInt(), uvsActInt::load(), uvsChangeGoodsInList(), and uvsChangeTabuTask().
ChangeVanger()
void ChangeVanger (void)
 {
     GeneralSystemClose();
     MLReset();
     vMap->release();
     GeneralMapReload = 1;
     GeneralSystemOpen();
     if(WorldTable[CurrentWorld] -> escTmax){
         WorldPalCurrent = uvsCurrentCycle;
         light_modulation  = WorldLightParam[CurrentWorld][WorldPalCurrent];
     };
 };
References CurrentWorld, GeneralMapReload, GeneralSystemClose(), GeneralSystemOpen(), light_modulation, MLReset(), vrtMap::release(), uvsCurrentCycle, vMap, WorldLightParam, WorldPalCurrent, and WorldTable.
Referenced by uvsVanger::Quant().
CloseCyclicPal()
void CloseCyclicPal (void)
 {
     int i;
     if(CurrentWorld < MAIN_WORLD_MAX - 1){
         for(i = 0;i < WorldPalNum;i++) {
             delete[] WorldPalData[i];
         }
         delete[] WorldPalData;
     };
     WorldPalData = NULL;
 };
References CurrentWorld, MAIN_WORLD_MAX, NULL, WorldPalData, and WorldPalNum.
Referenced by ChangeWorld(), and GeneralSystemFree().
FindFreeVanger()
uvsVanger * FindFreeVanger (void)
{
     uvsElement* p = ETail;
     uvsVanger* v;
     while(p){
         if(p -> type == UVS_OBJECT::VANGER && ((uvsVanger*)p) -> shape != UVS_VANGER_SHAPE::GAMER){
             v = (uvsVanger*)p;
             if( v -> status == UVS_VANGER_STATUS::SPOT_SLEEPING || v -> status == UVS_VANGER_STATUS::ESCAVE_SLEEPING){
                 if (Gamer -> Pworld -> escTmax)
                     v -> Pworld = Gamer -> Pworld;
                 else
                     v -> Pworld = WorldTable[RND(3)];
                 v -> Pescave = Gamer -> Pescave;
                 v -> Pspot = Gamer -> Pspot;
                 v -> shape = UVS_VANGER_SHAPE::TABUTASK;
                 if (v -> Pescave ){
                     v -> pos_x = v -> Pescave -> pos_x + 1024;
                     v -> pos_y = v -> Pescave -> pos_y + (1-RND(2))*1000;
                 } else {
                     v -> pos_x = v -> Pspot -> pos_x + 1024;
                     v -> pos_y = v -> Pspot -> pos_y + (1-RND(2))*1000;
                 }
                 v -> Pworld -> escT[0] -> Pshop -> sellMechos(v -> Pmechos);
                 if (!v -> Pmechos)
                     return NULL;
                 return v;
             }
         }
         p = p -> enext;
     }
     return NULL;
 }
References UVS_VANGER_STATUS::ESCAVE_SLEEPING, ETail, Gamer, UVS_VANGER_SHAPE::GAMER, NULL, uvsTarget::pos_x, uvsTarget::pos_y, uvsEscave::Pshop, uvsEscave::Pworld, RND(), UVS_VANGER_STATUS::SPOT_SLEEPING, UVS_VANGER_SHAPE::TABUTASK, UVS_OBJECT::VANGER, and WorldTable.
Referenced by uvsTabuTaskType::activateVANGER(), uvsBunch::begin_race(), and uvsCreateNetVanger().
FinishFirstShopPrepare()
void FinishFirstShopPrepare (int how)
                                     { //znfo
     if( !how){
         lastMechos = -1;
         Gamer -> get_shop(1);
 /*      uvsEscave* Pescave = Gamer -> Pescave;
         Pescave -> Pshop ->  get_list_from_ActInt( GMechos, GItem);
         Pescave -> Pshop -> locked = 0;
         Pescave -> GamerVisit++;
         lastMechos = -1;
         Gamer -> get_list_from_ActInt(GGamer, GGamerMechos);
         GamerResult.leepuringa = ItemCount(Gamer -> Pitem, UVS_ITEM_TYPE::LEEPURINGA);
         GamerResult.nymbos = ItemCount(Gamer -> Pitem,UVS_ITEM_TYPE::NYMBOS );
         GamerResult.phlegma = ItemCount(Gamer -> Pitem, UVS_ITEM_TYPE::PHLEGMA);
         GamerResult.heroin = ItemCount(Gamer -> Pitem,UVS_ITEM_TYPE::HEROIN );
         GamerResult.shrub = ItemCount(Gamer -> Pitem, UVS_ITEM_TYPE::SHRUB);
         GamerResult.poponka = ItemCount(Gamer -> Pitem,UVS_ITEM_TYPE::POPONKA );
         GamerResult.toxick = ItemCount(Gamer -> Pitem, UVS_ITEM_TYPE::TOXICK);
         if (GamerResult.leepuringa){
             GamerResult.add_luck += 50;
             ShowLuckMessage(50);
         }
         if (  lastMechos != Gamer -> Pmechos -> type ) {
             if (uvsMechosTable[Gamer -> Pmechos -> type] -> constractor){
                 GamerResult.dominance += 9;
                 ShowDominanceMessage(9);
             } else {
                 GamerResult.dominance += 5;
                 ShowDominanceMessage(5);
             }
             uvsMechosTable[Gamer -> Pmechos -> type] -> gamer_use++;
 #ifndef _DEMO_
             Gamer -> Pmechos -> color = Gamer -> Pworld -> escT[0] -> Pbunch -> biosNindex;
 #else
             Gamer -> Pmechos -> color = CAR_COLOR[Gamer -> Pmechos -> type];
 #endif
         }
         if (Gamer -> Pworld -> escTmax)
             aci_curLocationName = Gamer -> Pescave -> name;
         else
             aci_curLocationName = "";
 */
     } else {
         Gamer -> get_shop(0);
     }
 //  uvsRestoreVanger();
 }
References Gamer, and lastMechos.
Referenced by LoadingRTO2::Init().
FirstShopPrepare()
void FirstShopPrepare (int how)
                               { //znfo
     time(&uvsFirstTime);
     if( !how ){
         uvsEscave* Pescave = Gamer -> Pescave;
         uvsBunchNumber = Pescave -> Pbunch -> biosNindex;
         GGamerMechos = GGamer = GMechos = GItem = NULL;
         uvsLastEscaveName = aci_curLocationName = Pescave -> name;
         uvsGoodsON = 1;
         Pescave -> Pshop -> locked = 1;
         Pescave -> add_goods_to_shop();
         CurrentWorld = Gamer -> Pworld -> gIndex;
         Gamer -> prepare_list_for_ActInt( GGamer, GGamerMechos, Pescave -> Pshop, 1);
         Pescave -> Pshop ->  prepare_list_for_ActInt( GMechos, GItem, 1);
         //CurrentWorld = 0;
     } else{
         Gamer -> prepare_shop(0);
     }
 }
References Gamer, GGamer, GGamerMechos, GItem, GMechos, NULL, uvsEscave::Pbunch, uvsBunchNumber, and uvsFirstTime.
Referenced by FirstEscaveRTO::Init().
FreeFarmer()
void FreeFarmer (uvsElement *& pe)
{
     uvsFlyFarmer* pi = (uvsFlyFarmer*)pe;
     if (CurrentWorld != 1 ) return;
     while(pe){
         pi = (uvsFlyFarmer*)pe;
         pe = pe -> enext;
         if ( pi -> type == UVS_OBJECT::FLY_FARMER ){
             WorldTable[CurrentWorld] -> remove_target( (uvsTarget*)((uvsFlyFarmer*)pi), UVS_TARGET::FLY_FARMER);
 //          pi -> delink(pe);
             delete (uvsFlyFarmer*)pi;
         }//  end if
     }// end while
     pe = NULL;
 }
References CurrentWorld, UVS_OBJECT::FLY_FARMER, UVS_TARGET::FLY_FARMER, NULL, and WorldTable.
Referenced by SkyFarmerList::Init().
FreeList()
void FreeList (listElem *& pe)
{
     uvsItem* pi = (uvsItem*)pe;
     while(pe){
         pe = pe -> next;
         delete (uvsItem*)pi;
         pi = (uvsItem*)pe;
     }
     pe = NULL;
 }
References listElem::next, and NULL.
Referenced by uvsEscave::arrest(), ItemsDispatcher::Close(), ItemsDispatcher::CryptQuant(), uvsVanger::destroy(), VangerUnit::Go2Universe(), VangerUnit::Go2World(), uvsVanger::homeArrival(), VangerUnit::InCarNator(), NetworkWorldOpen(), ItemsDispatcher::Open(), VangerUnit::OutCarNator(), uvsVanger::spotArrival(), uvsVanger::~uvsVanger(), and uvsWorld::~uvsWorld().
GeneralSystemClose()
void GeneralSystemClose (void)
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
!!!!!!!!!!
 {
     int i;
     if(GeneralSystemSkip){
         aciClearTeleportMenu();
         uvsKronActive = 0;
         if(NetworkON && my_server_data.GameType == PASSEMBLOSS){
             for(i = 0;i < GloryPlaceNum;i++)
                 GloryPlaceData[i].CloseWorld();
         };
 //      StorageLog < "\nStartClose";
         CompasObj.Close();
 //      StorageLog < "\nActiveClose";
         ActD.Close();
 //      StorageLog < "\nEffectClose";
         EffD.Close();
 //      StorageLog < "\nItemClose";
         ItemD.Close();
 //      StorageLog < "\nOtherListClose";
         InsectD.Free();
         FishD.Free();
         HordeSourceD.Free();
         HordeD.Free();
         FarmerD.Free();
         ClefD.Free();
         BulletD.Free();
         DebrisD.Free();
         JumpD.Free();
 //      StorageLog < "\nMapClose";
         MapD.Close();
 //      StorageLog < "\nGameClose";
         GameD.Close();
 //      StorageLog < "\nTrackClose";
         HideTrack.Close();
         BackD.close();
 //      StorageLog < "\nStaticClose";
         StaticClose();
         PalCD.Free();
 //      StorageLog < "\nNetworkClose";
         if(NetworkON) NetworkWorldClose();
 //      StorageLog < "\nEndClose";
     };
 };
References aciClearTeleportMenu(), ActD, BackD, BulletD, ClefD, BackgroundDispatcher::close(), EffectDispatcher::Close(), GameObjectDispatcher::Close(), ItemsDispatcher::Close(), CompasObject::Close(), ActionDispatcher::Close(), TrackType::Close(), CompasObj, DebrisD, EffD, FarmerD, FishD, UnitListType::Free(), PalConstructor::Free(), ClefList::Free(), SkyFarmerList::Free(), FishWarriorList::Free(), InsectList::Free(), GameD, ServerData::GameType, GeneralSystemSkip, GloryPlaceData, GloryPlaceNum, HideTrack, HordeD, HordeSourceD, InsectD, ItemD, JumpD, MapD, my_server_data, NetworkON, NetworkWorldClose(), PalCD, PASSEMBLOSS, StaticClose(), and uvsKronActive.
Referenced by ChangeVanger(), ChangeWorld(), FreeAll(), and uvsPrepareQuant().
GeneralSystemFree()
void GeneralSystemFree (void)
 {
     int i,j;
     if(GeneralSystemSkip){
         if(CurrentWorld == WORLD_KHOX)
             scale_general *= 2.;
         CompasObj.Free();
         CloseCyclicPal();
         ActD.Free();
         EffD.Free();
         ItemD.Free();
         MapD.Free();
         GameD.Free();
         ModelD.Free();
         BackD.free();
         delete[] GameBulletData;
         aiMessageQueue.Close();
         delete[] aiMessageData;
         aiMessageBuffer.free_mem();
         for(i = 0;i < NumUnitMatrix;i++)
             UnitMatrixData[i].Close();
         delete[] UnitMatrixData;
         FreeProtoCrypt();
         for(i = 0;i < WORLD_MAX;i++){
             if(NumSkipLocation[i]){
                 for(j =0;j < NumSkipLocation[i];j++)
                     delete[] SkipLocationName[i][j];
                 delete[] SkipLocationName[i];
                 delete[] NumLocationData[i];
                 delete[] NumLocationID[i];
             };
         };
         delete[] CHECK_BSIGN_DATA;
     };
     for(i = 0;i < PassageBmpNum;i++)
         PassageImageData[i].Close();
     delete[] PassageImageData;
     if(NetworkON){
         if(my_server_data.GameType == PASSEMBLOSS){
             if(GloryPlaceData){
                 delete GloryPlaceData;
                 GloryPlaceData = NULL;
             };
         };
         total_players_data_list_query();
         disconnect_from_server();
         NetworkON = 0;
     };
 //  for(i = 0;i < WORLD_MAX;i++)
 //      delete SKIP_LOCATION_NAME[i];
 #ifdef ITEM_LOG
     xLog.close();
 #endif
 //  DBGCHECK;
 };
References ActD, aiMessageBuffer, aiMessageData, aiMessageQueue, BackD, CHECK_BSIGN_DATA, XStream::close(), aiMessageList::Close(), CloseCyclicPal(), CompasObj, CurrentWorld, disconnect_from_server(), EffD, BackgroundDispatcher::free(), EffectDispatcher::Free(), GameObjectDispatcher::Free(), ItemsDispatcher::Free(), ModelDispatcher::Free(), CompasObject::Free(), ActionDispatcher::Free(), aciPromptData::free_mem(), FreeProtoCrypt(), GameBulletData, GameD, ServerData::GameType, GeneralSystemSkip, GloryPlaceData, ItemD, MapD, ModelD, my_server_data, NetworkON, NULL, NumLocationData, NumLocationID, NumSkipLocation, NumUnitMatrix, PassageBmpNum, PassageImageData, PASSEMBLOSS, scale_general, SkipLocationName, total_players_data_list_query(), UnitMatrixData, WORLD_KHOX, and WORLD_MAX.
Referenced by FreeAll().
GeneralSystemInit()
void GeneralSystemInit (void)
 {
     int i,j;
     char*n;
 #ifdef ITEM_LOG
     xLog.open("item.log",XS_OUT);
 #endif
     GeneralMapReload = 1;
     GeneralLoadReleaseFlag = 1;
     ChangeArmor = -1;
     ChangeEnergy = -1;
     if(GeneralSystemSkip){
         InitProtoCrypt();
         CreateBoozeeniadaString();
         Parser aiData("jungle.lst");
         for(i = 0;i < AI_FACTOR_NUM;i++)
             aiFactorData[i].FactorLoad(aiData);
         for(i = 0;i < MAX_TIME_SECRET;i++){
             TimeSecretEnable[WORLD_FOSTRAL][i] = 0;
             TimeSecretEnable[WORLD_GLORX][i] = 0;
         };
         BackD.init(200);
     #ifdef GLOBAL_TIMER
         Parser in("tgame.lst");
     #else
         Parser in("game.lst");
     #endif
         in.search_name("NumImage");
         PassageBmpNum = in.get_int();
         PassageImageData = new PassageImageType[PassageBmpNum];
         for(i = 0;i < PassageBmpNum;i++){
             in.search_name("NameImage");
             PassageImageData[i].Open(in.get_name());
         };
         PassageBmpPrev = -1;
         for(i = 0;i < WORLD_MAX;i++){
             in.search_name("NumSkipML");
             NumSkipLocation[i] = in.get_int();
             in.search_name("RealNumLocation");
             RealNumLocation[i] = in.get_int();
             if(NetworkON) RealNumLocation[i] = 0;
             if(NumSkipLocation[i] > 0){
                 SkipLocationName[i] = new char*[NumSkipLocation[i]];
                 NumLocationData[i] = new int[NumSkipLocation[i]];
                 NumLocationID[i] = new int[NumSkipLocation[i]];
                 for(j =0;j < NumSkipLocation[i];j++){
                     in.search_name("SkipLocationID");
                     NumLocationID[i][j] = in.get_int();
                     in.search_name("SkipLocationName");
                     n = in.get_name();
                     SkipLocationName[i][j] = new char[strlen(n) + 1];
                     strcpy(SkipLocationName[i][j],n);
                 };
             };
         };
         aiMessageBuffer.alloc_mem(AI_MESSAGE_MAX_STRING);
         in.search_name("NumMessage");
         aiNumMessage = in.get_int();
         aiMessageData = new aiMessageType[aiNumMessage];
         for(i = 0;i < aiNumMessage;i++)
             aiMessageData[i].Load(in);
         aiMessageQueue.Open();
         in.search_name("NumUnitMatrix");
         NumUnitMatrix = in.get_int();
         UnitMatrixData = new UnitItemMatrix[NumUnitMatrix];
         for(i = 0;i < NumUnitMatrix;i++)
             UnitMatrixData[i].Open(in);
         for(i = 0;i < NumUnitMatrix;i++)
             UnitMatrixData[i].FullNum = UnitMatrixData[i].GetFullNum();
         in.search_name("UnitTimeConst");
         UnitGlobalTime = in.get_int();
         in.search_name("WeaponWaitTime");
         WeaponWaitTime = in.get_int();
         in.search_name("MaxOxigenBar");
         MaxOxigenBar = in.get_int();
         in.search_name("TotalVangerSpeed");
         TotalVangerSpeed = in.get_int();
         in.search_name("GameBulletNumType");
         GameBulletNum = in.get_int();
         GameBulletData = new WorldBulletTemplate[GameBulletNum];
         for(i = 0;i < GameBulletNum;i++){
             GameBulletData[i].ID = i;
             GameBulletData[i].Init(in);
         };
         ModelD.Init(in);
         GameD.Init();
         MapD.Init(in);
         EffD.Init(in);
         ItemD.Init(in);
         ActD.Init(in);
     //  MechosLst.open("report.lst",XS_OUT);
         OpenCyclicPal();
         CompasObj.Init();
         if(NetworkON){
             LocalNetEnvironment  =  LocalStationID | (CurrentWorld << 22);
         };
     };
 };
References ActD, AI_FACTOR_NUM, AI_MESSAGE_MAX_STRING, aiFactorData, aiMessageBuffer, aiMessageData, aiMessageQueue, aiNumMessage, aciPromptData::alloc_mem(), BackD, ChangeArmor, ChangeEnergy, CompasObj, CreateBoozeeniadaString(), CurrentWorld, EffD, GameBulletData, GameBulletNum, GameD, GeneralLoadReleaseFlag, GeneralMapReload, GeneralSystemSkip, Parser::get_int(), Parser::get_name(), WorldBulletTemplate::ID, BackgroundDispatcher::init(), EffectDispatcher::Init(), ItemsDispatcher::Init(), ModelDispatcher::Init(), ActionDispatcher::Init(), WorldBulletTemplate::Init(), GameObjectDispatcher::Init(), CompasObject::Init(), InitProtoCrypt(), ItemD, LocalNetEnvironment, LocalStationID, MapD, MAX_TIME_SECRET, MaxOxigenBar, ModelD, NetworkON, NumLocationData, NumLocationID, NumSkipLocation, NumUnitMatrix, PassageImageType::Open(), XStream::open(), aiMessageList::Open(), OpenCyclicPal(), PassageBmpNum, PassageBmpPrev, PassageImageData, RealNumLocation, Parser::search_name(), SkipLocationName, TimeSecretEnable, TotalVangerSpeed, UnitGlobalTime, UnitMatrixData, WeaponWaitTime, WORLD_FOSTRAL, WORLD_GLORX, WORLD_MAX, and XS_OUT.
Referenced by LoadingRTO1::Init().
GeneralSystemOpen()
void GeneralSystemOpen (void)
 {
 //  DBGCHECK;
     aiCutLuck = GamerResult.luck + GamerResult.add_luck;
     aiCutDominance = GamerResult.dominance + GamerResult.add_dominance;
     if(aiCutLuck > 100) aiCutLuck = 100;
     else if(aiCutLuck < 0) aiCutLuck = 0;
     if(aiCutDominance > 100) aiCutDominance = 100;
     else if(aiCutDominance < -100) aiCutDominance = -100;
     if(GeneralSystemSkip){
         ChangeWorldConstraction = -1;
         ChangeWorldSkipQuant = 0;
         aciPrepareMenus();
         PalCD.Init();
         if(CurrentWorld < MAIN_WORLD_MAX - 1) WorldBorderEnable = 1;
         else WorldBorderEnable = 0;
         PTrack_mask_y = (map_size_y << 8) - 1;
     #ifdef GLOBAL_TIMER
         Parser in(GetTargetName("tlevel.lst"));
     #else
         Parser in(GetTargetName("level.lst"));
     #endif
         StaticOpen();
 //zNfo many game inits
         in.search_name("TrackName");
         HideTrack.Open(in.get_name());
         GameD.Open();
         MapD.Open(in);
         ItemD.Open(in);
         FishD.Init();           //zNfo
         HordeSourceD.Init();    //zNfo
         HordeD.Init();          //zNfo
         FarmerD.Init();
         ClefD.Init();
         BulletD.Init();
         DebrisD.Init();
         JumpD.Init();
         InsectD.Init();
         EffD.Open(in);
         ActD.Open(in);
         ResortEnter();
         if(lang() == RUSSIAN){
             switch(CurrentWorld){
                 case WORLD_FOSTRAL:
 //zNfo - add target 2 compass
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Incubator"),rCmpIncubator);
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("Podish"),rCmpPodish);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate1"),rCmpRepair1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate2"),rCmpRepair2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate1"),rCmpRigs);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FireUpdate1"),rCmpGhOrb);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate1"),rCmpBroken1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate2"),rCmpBroken2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate1"),rCmpSpiral);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("F2G"),rCmpPassGlorx);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("F2W"),rCmpPassWeexow);
                     if(GamerResult.earth_unable)
                         AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("PASS83"),rCmpPassEarth);
                     break;
                 case WORLD_GLORX:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Ogorod"),rCmpOgorod);
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Lampasso"),rCmpLampasso);
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("VigBoo"),rCmpVigBoo);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2F"),rCmpPassFostral);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2N"),rCmpPassNecross);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2X"),rCmpPassXplo);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2K"),rCmpPassKhox);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate01"),rCmpRigs1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate02"),rCmpRigs2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate01"),rCmpRepair1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate02"),rCmpRepair2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FireUpdate01"),rCmpGhOrb);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate01"),rCmpSpiral);
                     break;
                 case WORLD_NECROSS:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("B-Zone"),rCmpBZone);
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("ZeePa"),rCmpZeePa);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2G"),rCmpPassGlorx);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2B"),rCmpPassBoozeena);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2A"),rCmpPassArk);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate01"),rCmpRigs);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate01"),rCmpRepair);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate01"),rCmpSpiral);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate01"),rCmpBroken);
                     break;
                 case WORLD_XPLO:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Spobs"),rCmpSpobs);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("X2G"),rCmpPassGlorx);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("X2T"),rCmpPassThreall);
                     break;
                 case WORLD_KHOX:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("K2G"),rCmpPassGlorx);
                     break;
                 case WORLD_BOOZEENA:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("B2N"),rCmpPassNecross);
                     break;
                 case WORLD_WEEXOW:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("W2F"),rCmpPassFostral);
                     break;
                 case WORLD_THREALL:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("T2X"),rCmpPassXplo);
                     break;
                 case WORLD_ARKONOY:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("A2N"),rCmpPassNecross);
                     break;
             };
         }else{
             switch(CurrentWorld){
                 case WORLD_FOSTRAL:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Incubator"),eCmpIncubator);
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("Podish"),eCmpPodish);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate1"),eCmpRepair1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate2"),eCmpRepair2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate1"),eCmpRigs);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FireUpdate1"),eCmpGhOrb);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate1"),eCmpBroken1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate2"),eCmpBroken2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate1"),eCmpSpiral);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("F2G"),eCmpPassGlorx);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("F2W"),eCmpPassWeexow);
                     if(GamerResult.earth_unable)
                         AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("PASS83"),eCmpPassEarth);
                     break;
                 case WORLD_GLORX:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Ogorod"),eCmpOgorod);
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Lampasso"),eCmpLampasso);
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("VigBoo"),eCmpVigBoo);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2F"),eCmpPassFostral);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2N"),eCmpPassNecross);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2X"),eCmpPassXplo);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2K"),eCmpPassKhox);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate01"),eCmpRigs1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate02"),eCmpRigs2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate01"),eCmpRepair1);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate02"),eCmpRepair2);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FireUpdate01"),eCmpGhOrb);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate01"),eCmpSpiral);
                     break;
                 case WORLD_NECROSS:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("B-Zone"),eCmpBZone);
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("ZeePa"),eCmpZeePa);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2G"),eCmpPassGlorx);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2B"),eCmpPassBoozeena);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2A"),eCmpPassArk);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate01"),eCmpRigs);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate01"),eCmpRepair);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate01"),eCmpSpiral);
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate01"),eCmpBroken);
                     break;
                 case WORLD_XPLO:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Spobs"),eCmpSpobs);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("X2G"),eCmpPassGlorx);
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("X2T"),eCmpPassThreall);
                     break;
                 case WORLD_KHOX:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("K2G"),eCmpPassGlorx);
                     break;
                 case WORLD_BOOZEENA:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("B2N"),eCmpPassNecross);
                     break;
                 case WORLD_WEEXOW:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("W2F"),eCmpPassFostral);
                     break;
                 case WORLD_THREALL:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("T2X"),eCmpPassXplo);
                     break;
                 case WORLD_ARKONOY:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("A2N"),eCmpPassNecross  );
                     break;
             };
 /*          switch(CurrentWorld){
                 case WORLD_FOSTRAL:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Incubator"),"Incubator");
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("Podish"),"Podish");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate1"),"Repair Station I");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate2"),"Repair Station II");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate1"),"Rigs Station");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FireUpdate1"),"ghOrb Station");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate1"),"Broken Station I");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate2"),"Broken Station II");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate1"),"Spiral Station");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("F2G"),"Passage to Glorx");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("F2W"),"Passage to  Weexow");
                     break;
                 case WORLD_GLORX:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Ogorod"),"Ogorod");
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Lampasso"),"Lampasso");
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("VigBoo"),"VigBoo");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2F"),"Passage to  Fostral");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2N"),"Passage to  Necross");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2X"),"Passage to  Xplo");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("G2K"),"Passage to  Khox");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate01"),"Rigs Station I");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate02"),"Rigs Station II");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate01"),"Repair Station I");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate02"),"Repair Station II");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FireUpdate01"),"ghOrb Station");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate01"),"Spiral Station");
                     break;
                 case WORLD_NECROSS:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("B-Zone"),"B-Zone");
                     AddTarget2Compas(CMP_TARGET_ESCAVE,(void*)("ZeePa"),"ZeePa");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2G"),"Passage to  Glorx");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2B"),"Passage to  Boozeena");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("N2A"),"Passage to  Ark'a'Znoy");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("FlyUpdate01"),"Rigs Station");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("ArmorUpdate01"),"Repair Station");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("KeyUpdate01"),"Spiral Station");
                     AddTarget2Compas(CMP_TARGET_SENSOR,(void*)("RandomUpdate01"),"Broken Station");
                     break;
                 case WORLD_XPLO:
                     AddTarget2Compas(CMP_TARGET_SPOT,(void*)("Spobs"),"Spobs");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("X2G"),"Passage to Glorx");
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("X2T"),"Passage to Threall");
                     break;
                 case WORLD_KHOX:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("K2G"),"Passage to Glorx");
                     break;
                 case WORLD_BOOZEENA:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("B2N"),"Passage to Necross");
                     break;
                 case WORLD_WEEXOW:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("W2F"),"Passage to Fostral");
                     break;
                 case WORLD_THREALL:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("T2X"),"Passage to  Xplo");
                     break;
                 case WORLD_ARKONOY:
                     AddTarget2Compas(CMP_TARGET_PASSAGE,(void*)("A2N"),"Passage to  Necross");
                     break;
             };*/
         };
         SelectCompasTarget(NULL);
         CompasObj.Open();
         uvsKronActive = 1;
         actCurrentViewObject = NULL;
         actCurrentViewDolly = NULL;
         actCurrentViewStuff = NULL;
         if(NetworkON) NetworkWorldOpen();
     }
 };
References aciPrepareMenus(), actCurrentViewDolly, actCurrentViewObject, actCurrentViewStuff, ActD, uvsGamerResult::add_dominance, uvsGamerResult::add_luck, AddTarget2Compas(), aiCutDominance, aiCutLuck, BulletD, ChangeWorldConstraction, ChangeWorldSkipQuant, ClefD, CMP_TARGET_ESCAVE, CMP_TARGET_PASSAGE, CMP_TARGET_SENSOR, CMP_TARGET_SPOT, CompasObj, CurrentWorld, DebrisD, uvsGamerResult::dominance, uvsGamerResult::earth_unable, eCmpBroken, eCmpBroken1, eCmpBroken2, eCmpBZone, eCmpGhOrb, eCmpIncubator, eCmpLampasso, eCmpOgorod, eCmpPassArk, eCmpPassBoozeena, eCmpPassEarth, eCmpPassFostral, eCmpPassGlorx, eCmpPassKhox, eCmpPassNecross, eCmpPassThreall, eCmpPassWeexow, eCmpPassXplo, eCmpPodish, eCmpRepair, eCmpRepair1, eCmpRepair2, eCmpRigs, eCmpRigs1, eCmpRigs2, eCmpSpiral, eCmpSpobs, eCmpVigBoo, eCmpZeePa, EffD, FarmerD, FishD, GameD, GamerResult, GeneralSystemSkip, Parser::get_name(), GetTargetName(), HideTrack, HordeD, HordeSourceD, UnitListType::Init(), PalConstructor::Init(), ClefList::Init(), SkyFarmerList::Init(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), InsectList::Init(), InsectD, ItemD, JumpD, lang(), uvsGamerResult::luck, MAIN_WORLD_MAX, map_size_y, MapD, NetworkON, NetworkWorldOpen(), NULL, TrackType::Open(), EffectDispatcher::Open(), ItemsDispatcher::Open(), ActionDispatcher::Open(), GameObjectDispatcher::Open(), CompasObject::Open(), PalCD, PTrack_mask_y, rCmpBroken, rCmpBroken1, rCmpBroken2, rCmpBZone, rCmpGhOrb, rCmpIncubator, rCmpLampasso, rCmpOgorod, rCmpPassArk, rCmpPassBoozeena, rCmpPassEarth, rCmpPassFostral, rCmpPassGlorx, rCmpPassKhox, rCmpPassNecross, rCmpPassThreall, rCmpPassWeexow, rCmpPassXplo, rCmpPodish, rCmpRepair, rCmpRepair1, rCmpRepair2, rCmpRigs, rCmpRigs1, rCmpRigs2, rCmpSpiral, rCmpSpobs, rCmpVigBoo, rCmpZeePa, ResortEnter(), RUSSIAN, Parser::search_name(), SelectCompasTarget(), StaticOpen(), uvsKronActive, WORLD_ARKONOY, WORLD_BOOZEENA, WORLD_FOSTRAL, WORLD_GLORX, WORLD_KHOX, WORLD_NECROSS, WORLD_THREALL, WORLD_WEEXOW, WORLD_XPLO, and WorldBorderEnable.
Referenced by ChangeVanger(), ChangeWorld(), uvsAddStationaryObjs(), and uvsCloseQuant().
GeneralTableOpen()
void GeneralTableOpen (void)
 {
     Vector vColor,vCheck;
     int i,j,k;
     int d1,d2,dc;
     int nmin,cmin;
     int ti,dec;
     int n;
     int MaxVector;
     int cmax,cval,cdelta,lmin;
     if(GeneralSystemSkip){
         for(i = 0;i < TERRAIN_MAX;i++){
             LastColorPlace[CurrentWorld][i] = ENDCOLOR[i];
             FirstColorPlace[CurrentWorld][i] = BEGCOLOR[i];
         };
         if(uvsCurrentWorldUnable && CurrentWorld < MAIN_WORLD_MAX - 1){
             vColor = Vector(63,63,63);
             MaxVector = vColor.vabs();
             for(k = 0;k < WorldPalNum;k++){
                 for(i = 0;i < NUM_COLOR_PLACE;i++){
                     for(j = FirstColorPlace[CurrentWorld][i];j <= LastColorPlace[CurrentWorld][i];j++){
                         vCheck = Vector(WorldPalData[k][j*3],WorldPalData[k][j*3 + 1],WorldPalData[k][j*3 + 2]);
                         dc = 63 * vCheck.vabs() / MaxVector;
                         WorldPalData[k][j*3] = WorldPalData[k][j*3] + GrayColorCycle[CurrentWorld][i]*(dc - WorldPalData[k][j*3]) / 63;
                         WorldPalData[k][j*3 + 1] = WorldPalData[k][j*3 + 1] + GrayColorCycle[CurrentWorld][i]*(dc - WorldPalData[k][j*3 + 1]) / 63;
                         WorldPalData[k][j*3 + 2] = WorldPalData[k][j*3 + 2] + GrayColorCycle[CurrentWorld][i]*(dc - WorldPalData[k][j*3 + 2]) / 63;
                     };
                 };
             };
         };
         PalettePrepare();
         for(i = 0;i < 256;i++){
             if(i > ENDCOLOR[0]){
                 vColor = Vector(palbufOrg[i * 3],palbufOrg[i * 3 + 1],palbufOrg[i * 3 + 2]);
                 WaterColorTable[i] = vColor.vabs() >> 3;
             }else WaterColorTable[i] = i;
         };
         if(CurrentWorld < MAIN_WORLD_MAX - 1) {
             for(k = 0;k < WorldPalNum;k++) FirePaletteInit(WorldPalData[k]);
         };
         FirePaletteInit(palbufOrg);
         FirePaletteInit(palbuf);
         ParticlePaletteTableInit(palbufOrg);
         FirePaletteTableInit(palbufOrg);
         vColor = Vector(63,63,63);
         MaxVector = vColor.vabs();
         for(k = 0;k < 256;k++){
             for(i = 0;i < 256;i++){
                 vColor = Vector(palbuf[i*3],palbuf[i*3 + 1],palbuf[i*3 + 2]);
                 d1 = vColor.vabs() + (MaxVector - vColor.vabs()) * k / 256;
                 ti = FIRE_COLOR_FIRST;
                 vColor = Vector(palbuf[FIRE_COLOR_FIRST*3],palbuf[FIRE_COLOR_FIRST*3 + 1],palbuf[FIRE_COLOR_FIRST*3 + 2]);
                 dec = abs(vColor.vabs() - d1);
                 for(j = FIRE_COLOR_FIRST + 1;j < FIRE_COLOR_FIRST + FIRE_PROCESS_COLOR_MAX;j++){
                     vColor = Vector(palbuf[j*3],palbuf[j*3 + 1],palbuf[j*3 + 2]);
                     d2 = vColor.vabs();
                     dc = abs(d2 - d1);
                     if(dc < dec){
                         dec = dc;
                         ti = j;
                     };
                 };
                 FireColorTable[i + (k << 8)] = ti;
             };
         };
         for(i  = 0;i < 256;i++)
             ShadowColorTable[i] = 0;
         for(k = 0;k < NUM_COLOR_PLACE;k++){
             dec = DecColorPlace[CurrentWorld][k];
             for(i = FirstColorPlace[CurrentWorld][k];i <= LastColorPlace[CurrentWorld][k];i++){
                 vColor = Vector(palbufOrg[i * 3],palbufOrg[i * 3 + 1],palbufOrg[i * 3 + 2]);
                 dc = vColor.vabs();
                 d1 = dc - dec;
                 if(d1 < 1) d1 = 1;
                 if(dc < 1) dc = 1;
                 vColor = vColor * d1 / dc;
                 vCheck = Vector(palbufOrg[FirstColorPlace[CurrentWorld][k]],palbufOrg[FirstColorPlace[CurrentWorld][k] + 1],palbufOrg[FirstColorPlace[CurrentWorld][k] + 2]) - vColor;
                 nmin = FirstColorPlace[CurrentWorld][k];
                 cmin = vCheck.vabs();
                 for(j = FirstColorPlace[CurrentWorld][k] + 1;j <= LastColorPlace[CurrentWorld][k];j++){
                     vCheck = Vector(palbufOrg[j * 3],palbufOrg[j * 3 + 1],palbufOrg[j * 3 + 2]) - vColor;
                     d2 = vCheck.vabs();
                     if(d2 <= cmin){
                         nmin = j;
                         cmin = d2;
                     };
                 };
                 if(nmin > i) ShadowColorTable[i] = i;
                 else ShadowColorTable[i] = nmin;
             };
         };
         for(n = 0;n < TERRAIN_MAX;n++){
             if(n == 1 || n == 7){
                 cmax = 0;
                 lmin = 255;
                 for(i = BEGCOLOR[n];i < ENDCOLOR[n];i++){
                     vColor = Vector(palbufOrg[i*3],palbufOrg[i*3 + 1],palbufOrg[i*3 + 2]);
                     cval = vColor.vabs();
                     if(cval > cmax) cmax = cval;
                     if(cval < lmin) lmin = cval;
                 };
                 vColor = Vector(63,63,63);
                 MaxVector = vColor.vabs();
                 cdelta = cmax - lmin;
                 for(k = 0;k < 256;k++){
                     for(i = 0;i < 256;i++){
                         vColor = Vector(palbufOrg[i*3],palbufOrg[i*3 + 1],palbufOrg[i*3 + 2]);
                         d1 = vColor.vabs() + (MaxVector - vColor.vabs()) * k / 256;
                         d1 = lmin + d1 * cdelta / MaxVector;
                         ti = BEGCOLOR[n];
                         vColor = Vector(palbufOrg[BEGCOLOR[n]*3],palbufOrg[BEGCOLOR[n]*3 + 1],palbufOrg[BEGCOLOR[n]*3 + 2]);
                         dec = abs(vColor.vabs() - d1);
                         for(j = BEGCOLOR[n] + 1;j < ENDCOLOR[n];j++){
                             vColor = Vector(palbufOrg[j*3],palbufOrg[j*3 + 1],palbufOrg[j*3 + 2]);
                             d2 = vColor.vabs();
                             dc = abs(d2 - d1);
                             if(dc < dec){
                                 dec = dc;
                                 ti = j;
                             };
                         };
                         TerrainAlphaTable[n][i + (k << 8)] = ti;
                     };
                 };
             };
         };
         for(i = 0;i < 768;i++)
             palbufSrc[i] = palbufOrg[i];
         for(i = 0;i < 8;i++)
             register_color(COLORS_IDS::MATERIAL_0 + i,FirstColorPlace[CurrentWorld][i],LastColorPlace[CurrentWorld][i]);
     };
 };
References BEGCOLOR, CurrentWorld, DecColorPlace, ENDCOLOR, FIRE_COLOR_FIRST, FIRE_PROCESS_COLOR_MAX, FireColorTable, FirePaletteInit(), FirePaletteTableInit(), FirstColorPlace, GeneralSystemSkip, GrayColorCycle, LastColorPlace, MAIN_WORLD_MAX, COLORS_IDS::MATERIAL_0, NUM_COLOR_PLACE, palbuf, palbufOrg, palbufSrc, PalettePrepare(), ParticlePaletteTableInit(), register_color(), ShadowColorTable, TERRAIN_MAX, TerrainAlphaTable, uvsCurrentWorldUnable, Vector::vabs(), WaterColorTable, WorldPalData, and WorldPalNum.
Referenced by ChangeWorld(), and LoadingRTO2::Init().
get_power()
int get_power (int t)
                     {
     int i, n;
     i = 0;
     n = 1;
     while( t != n ){
         i++;
         n <<= 1;
     }
     return i;
 }
Referenced by uvsWorld::save().
get_string()
char * get_string (XStream & pfile)
{
     char n;
     char *s;
     pfile > n;
     if ( n == 0 ) return NULL;
     s = new char[n+1];
     pfile.read(s, n);
     s[n] = 0;
     return s;
 }
References NULL, and XStream::read().
Referenced by uvsEscave::uvsEscave(), uvsPassage::uvsPassage(), uvsSpot::uvsSpot(), uvsVanger::uvsVanger(), and uvsWorld::uvsWorld().
GetItem()
uvsItem * GetItem (listElem * pe, int inType, int work)
{
     if ( !pe ) return NULL;
     while(1){
             while( ((uvsItem*)pe) -> type != inType && pe -> next ){
                 pe = pe -> next;
             }
             if(((uvsItem*)pe) -> type == inType){
                 if( !work ) return (uvsItem*)pe;
                 else if ( !(((uvsItem*)pe) -> param1) ) return (uvsItem*)pe;
             }
             if( !(pe -> next) ) return NULL;
             pe  = pe -> next;
     }
 }
References listElem::next, and NULL.
Referenced by uvsVanger::_checkDolly_(), uvsVanger::_sellCirt_(), uvsEscave::add_goods_to_shop(), uvsEscave::arrest(), uvsBunch::bring_harvest_GOODS(), uvsBunch::bring_race_GOODS(), uvsVanger::checkDolly(), uvsVanger::emptyContainer(), uvsBunch::end_harvest(), uvsBunch::end_race(), uvsVanger::gatherCirt(), uvsVanger::get_shop(), uvsFlyFarmer::GrowCorn(), uvsVanger::harvest_result(), ItemCount(), uvsVanger::race_result(), uvsVanger::sellCirt(), uvsShop::updateResource(), uvsPassagerFromStatistic(), and uvsPoponkaIDON().
GetItem_as_name()
int GetItem_as_name (char * s)
{
     int i;
     for(i = 0; i < MAX_ITEM_TYPE; i++) if (!strcmp(s, uvsItemTable[i] -> name)) return i;
     return -1;
 }
References MAX_ITEM_TYPE, uvsEscave::name, and uvsItemTable.
GetItem_as_type()
uvsItem * GetItem_as_type (listElem * pe, int status, int work = 0, int index = 0)
{
     if ( !pe ) return NULL;
     while(1){
             while( uvsItemTable[((uvsItem*)pe)  -> type] -> type != status && pe -> next ){
                 pe = pe -> next;
             }
             if(uvsItemTable[((uvsItem*)pe) -> type] -> type == status){
                 if( !work ) return (uvsItem*)pe;
                 else if ( ((uvsItem*)pe) -> param2 == index ) return (uvsItem*)pe;
             }
             if( !(pe -> next) ) return NULL;
             pe  = pe -> next;
     }
 }
References listElem::next, NULL, and uvsItemTable.
Referenced by uvsEscave::arrest(), uvsVanger::prepare_caravan(), uvsVanger::sell_move_Item(), uvsVanger::sell_treasure_Item(), uvsVanger::thief_from_shop(), and thief_on_world().
GetMechos_as_name()
int GetMechos_as_name (char * s)
{
     int i;
     for(i = 0; i < MAX_MECHOS_TYPE; i++)
         if (!strcmp(s, uvsMechosTable[i] -> name)) return i;
     return -1;
 }
References MAX_MECHOS_TYPE, uvsEscave::name, and uvsMechosTable.
GetPassage()
uvsPassage* GetPassage (int fromWID, int toWID)
{
     uvsWorld *nextW;
     uvsWorld *fromW;
     if ( fromWID == toWID ) return NULL;
     if ( fromWID >= MAIN_WORLD_MAX ) {
         return WorldTable[fromWID] -> pssT[0];
     }
     if (toWID >= MAIN_WORLD_MAX ) {
         int lastID = toWID;
         toWID = WorldTable[toWID] -> pssT[0] -> Poutput -> gIndex;
         if (fromWID == toWID) return WorldTable[fromWID] -> getPassage( getWorld(lastID) );;
     }
     unsigned int linkage = ChainMap[toWID + fromWID*MAIN_WORLD_MAX],mI;
     mI = linkage & (0x0000000F);
     nextW = getWorld(mI);
     if(!nextW) nextW = getWorld(toWID);
     fromW = getWorld(fromWID);
     return  fromW -> getPassage(nextW);
 }
References getWorld(), MAIN_WORLD_MAX, NULL, and WorldTable.
Referenced by CreatePhantomTarget().
getPassangerFrom()
int getPassangerFrom (char efrom)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     while(pe){
         if ( pe -> name[0] == efrom)
             return pe -> PassagerFrom;
         pe = (uvsEscave*)pe -> next;
     }
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(ps){
         if ( ps -> name[0] == efrom)
             return ps -> PassagerFrom;
         ps = (uvsSpot*)ps -> next;
     }
     return 0;
 }
References EscaveTail, uvsEscave::name, listElem::next, uvsEscave::PassagerFrom, and SpotTail.
getPassangerStats()
int getPassangerStats (char efrom, char wto)
{
     uvsWorld *pw = (uvsWorld*)WorldTail;
     while(pw && pw -> name[0] != wto ){
         pw = (uvsWorld*)pw -> next;
     }
     if (!pw) ErrH.Abort("getPassangerStats :: Incorrect world name");
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     while(pe){
         if ( pe -> name[0] == efrom)
             return pe -> PassagerStatistic[pw -> gIndex];
         pe = (uvsEscave*)pe -> next;
     }
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(ps){
         if ( ps -> name[0] == efrom)
             return ps -> PassagerStatistic[pw -> gIndex];
         ps = (uvsSpot*)ps -> next;
     }
     return 0;
 }
Referenced by getSpectorsTaskStatus().
getPreviousCycle()
int getPreviousCycle (int cycle)
{
     uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
     int i = cycle - 1;
     int _i = 0;
     if( i < 0 ) i = pb -> cycleN - 1;
     while( pb -> cycleTable[i].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE  ){
         if( --i < 0 ) i = pb -> cycleN - 1;
         _i++;
         if (_i > pb -> cycleN) {
             return -1;
         }
     }//  end while
     return i;
 }
References Gamer, uvsEscave::Pbunch, uvsEscave::Pworld, and UVS_DOLLY_STATUS::UNABLE.
Referenced by dgCell::analyzeACCESS().
getRW()
int getRW (int n)
                 {
     int r = n;
     while( r == n )
         r = RND(MAIN_WORLD_MAX);
     return r;
 }
References MAIN_WORLD_MAX, and RND().
Referenced by uvsVanger::goNewEscave().
getWorld()
uvsWorld* getWorld (int n)
{
     //if ( n >= 0 ) return WorldTable[n]; else return NULL;
     int i = 0;
     listElem* p = WorldTail;
     while(i != n && p) i++, p = p -> next;
     return (uvsWorld*)p;
 }
Referenced by GetPassage(), uvsVanger::goNewEscave(), and StandScreenPrepare().
getWorldVisitStats()
int getWorldVisitStats (char wc)
{
     uvsWorld *pw = (uvsWorld*)WorldTail;
     while(pw && pw -> name[0] != wc ){
         pw = (uvsWorld*)pw -> next;
     }
     if (!pw) ErrH.Abort("getWorldVisitStats :: Incorrect world name");
     return pw -> GamerVisit;
 }
Referenced by dgCell::analyzeACCESS().
isCycleExist()
int isCycleExist (int cycle, char ew)
{
     if(!ew)
         return Gamer -> checkCycle(cycle);
     else {
         uvsWorld *pw = (uvsWorld*)WorldTail;
         while(pw && pw -> name[0] != ew ){
             pw = (uvsWorld*)pw -> next;
         }
         if (!pw) ErrH.Abort("isCycleExist :: Incorrect world name");
         if (!pw -> escTmax) return 0;
         uvsBunch *pb = pw -> escT[0] -> Pbunch;
         if (pb -> cycleTable[cycle].Pdolly -> status == UVS_DOLLY_STATUS::UNABLE)
             return 0;
         else
             return 1;
     }
 }
References Gamer.
Referenced by getInfernalsTaskStatus().
ItemCount()
int ItemCount (listElem * Pitem, int ItemType, int what = 0)
{
     int tmp = 0;
     uvsItem *pi;
     if (  UVS_ITEM_TYPE::PIPETKA == ItemType || ItemType == UVS_ITEM_TYPE::KERNOBOO)
         what = 1;
     pi = GetItem(Pitem, ItemType, 0);
     while( pi ){
         if (what)
             tmp += pi -> param2;
         else
             tmp++;
         pi = GetItem( pi -> next, ItemType, 0 );
     }
     return tmp;
 }
References GetItem(), UVS_ITEM_TYPE::KERNOBOO, listElem::next, UVS_ITEM_TYPE::PIPETKA, and uvsEscave::Pitem.
Referenced by uvsBunch::bring_harvest_GOODS(), uvsVanger::get_shop(), uvsVanger::harvest_result(), uvsVanger::prepare_diagen_statistic(), uvsVanger::race_result(), and uvsCheckItemOnTabuTask().
LoadingMessage()
void LoadingMessage (int flush = 0)
 {
     if(flush){
         char col255[3] = { 60,40,0 }; XGR_SetPal(col255,255,1);
         char col0[3] = { 0,0,0 }; XGR_SetPal(col0,0,1);
         XGR_Fill(0);
     }
     char* str = getRC();
     sysfont.draw(8,XGR_MAXY - 35,(unsigned char*)str,255,-1);
     XBuffer buf;
     if (lang() == RUSSIAN) {
         buf < Convert(zSTR_LOADING_800_RU);
     } else if (lang() == GERMAN) {
         if(XGR_MAXX == 800)
             buf < "(C)1997-2014. Alle Rechte vorbehalten. Release Version 1.3. Gleich geht's weiter...";
         else
             buf < "Spiel wird geladen. Gleich geht's weiter...";
     } else {
         buf < "(C)1997-2014 All Rights Reserved. Release Version 1.3 Loading. Please wait...";
     }
     int len = MAX(strlen(str),strlen(buf.GetBuf()));
     sysfont.draw(8,XGR_MAXY - 20,(unsigned char*)(buf.GetBuf()),255,-1);
     XGR_LineTo(8,XGR_MAXY - 45,len*8 + 5 + 16,2,255);
     XGR_LineTo(8 + len*8 + 11,XGR_MAXY - 45 - 7,2*7,3,255);
     //if(flush){
     //  XGR_Flush(0,0,XGR_MAXX,XGR_MAXY);
     //}
 }
References Convert(), flush(), GERMAN, XBuffer::GetBuf(), getRC(), lang(), MAX, RUSSIAN, sysfont, XGR_Fill, XGR_LineTo, XGR_MAXX, XGR_MAXY, XGR_SetPal, and zSTR_LOADING_800_RU.
Referenced by gameQuant(), LoadingRTO1::Init(), LoadingRTO2::Init(), MainMenuRTO::Init(), uvsCloseQuant(), and xtInitApplication().
MLReset()
void MLReset (void)
 {
     for(int i = 0;i < MLTableSize;i++) MLTable[i]->reset();
 };
References MLTable, and MLTableSize.
Referenced by ChangeVanger(), and uvsPrepareQuant().
OpenCyclicPal()
void OpenCyclicPal (void)
 {
     int i;
     XStream fin;
     if(CurrentWorld < MAIN_WORLD_MAX - 1){
         WorldPalNum = WorldTable[CurrentWorld]->escT[0]->Pbunch->cycleN;
         WorldPalData = new uchar*[WorldPalNum];
         WorldPalCurrent = WorldTable[CurrentWorld]->escT[0]->Pbunch->currentStage;
         for(i = 0;i < WorldPalNum;i++){
             WorldPalData[i] = new uchar[768];
             fin.open(WorldTable[CurrentWorld]->escT[0]->Pbunch->cycleTable[i].pal_name,XS_IN);
             fin.read(WorldPalData[i],768);
             fin.close();
         };
     };
 };
References XStream::close(), uvsBunch::currentStage, CurrentWorld, uvsBunch::cycleN, uvsWorld::escT, MAIN_WORLD_MAX, XStream::open(), uvsEscave::Pbunch, XStream::read(), WorldPalCurrent, WorldPalData, WorldPalNum, WorldTable, and XS_IN.
Referenced by ChangeWorld(), and GeneralSystemInit().
put_string()
void put_string (XStream & pfile, char * s)
{
     char n = strlen(s);
     pfile < n;
     pfile.write(s, n);
 }
References XStream::write().
Referenced by uvsWorld::save(), uvsEscave::save(), uvsSpot::save(), and uvsPassage::save().
ReadPriceList()
void ReadPriceList (void)
{
     char *atom;
     int i;
     uvsEscave* pe;
     uvsSpot* ps;
     PrmFile pfile;
     pfile.init(PrmFileName[8]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[8]);
     while( 1 ){
         if((atom = pfile.getAtom()) == NULL) break;
         for( i = 0; i < MAX_ITEM_TYPE; i++)
             if ( !strcmp( atom, uvsItemTable[i] -> name) ) break;
         if ( i == MAX_ITEM_TYPE ) {
             pe = (uvsEscave*)EscaveTail -> seekName( atom );
             ps = (uvsSpot*)SpotTail -> seekName( atom );
             if ( !ps && !pe ) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,"Bad ITEM or Town NAME");
         } else {
             if ( pe ){
                 pe -> Pshop -> Price[i] = atoi(pfile.getAtom());
                 pe -> Pshop -> Price[i + MAX_ITEM_TYPE] = atoi(pfile.getAtom());
             } else if ( ps ){
                 ps -> Pshop -> Price[i] = atoi(pfile.getAtom());
                 ps -> Pshop -> Price[i + MAX_ITEM_TYPE] = atoi(pfile.getAtom());
             } else ErrH.Abort(PrmWrongMsg,XERR_USER,-1,"None Town Name");
         }
     }  //  end while
     pfile.finit();
 }
References PrmFile::init().
thief_on_world()
int thief_on_world (void)
{
     uvsElement* p = ETail;
     uvsVanger* v;
     uvsItem *pi;
     while(p){
         if(p -> type == UVS_OBJECT::VANGER ){
             v = (uvsVanger*)p;
             if ( v -> shape == UVS_VANGER_SHAPE::THIEF && v -> Pworld -> gIndex == CurrentWorld){
                 if ((pi = GetItem_as_type( v -> Pitem,  UVS_ITEM_STATUS::TREASURE, 1, CurrentWorld)) != NULL ) {
 //                  AddTarget2Compas(CMP_TARGET_ITEM,(void*)(pi) ,"Leepuringa");
                     return 1;
                 }
             }
         }
         p = p -> enext;
     }
     return 0;
 }
References CurrentWorld, ETail, GetItem_as_type(), NULL, uvsEscave::Pitem, uvsEscave::Pworld, UVS_VANGER_SHAPE::THIEF, UVS_ITEM_STATUS::TREASURE, and UVS_OBJECT::VANGER.
uniVangDelete()
void uniVangDelete (void)
{
     int i;
     uvsElement* ET;
     listElem *le;
     while (ETail){
         ET = ETail;
         ETail = ETail -> enext;
         if ( ET -> type == UVS_OBJECT::VANGER)
             delete ((uvsVanger*)ET);
         else
             delete ((uvsDolly*)ET);
     }
     ETail = NULL;
     if ( MAX_ITEM_TYPE ){
         for( i = 0; i < MAX_ITEM_TYPE; i++)
             delete uvsItemTable[i];
         delete[] uvsItemTable;
     }
     if ( MAX_MECHOS_TYPE ){
         for( i = 0; i < MAX_MECHOS_TYPE; i++)
             delete uvsMechosTable[i];
         delete[] uvsMechosTable;
     }
     while (WorldTail){
         le = WorldTail;
         WorldTail = WorldTail -> next;
         delete ((uvsWorld*)le);
     }
     WorldTail = NULL;
     DollyTail = NULL;
     while (EscaveTail){
         le = EscaveTail;
         EscaveTail = EscaveTail -> next;
         delete ((uvsEscave*)le);
     }
     EscaveTail = NULL;
     while (SpotTail){
         le = SpotTail;
         SpotTail = SpotTail -> next;
         delete (uvsSpot*)le;
     }
     SpotTail = NULL;
     while (PassageTail){
         le = PassageTail;
         PassageTail = PassageTail -> next;
         delete (uvsPassage*)le;
     }
     PassageTail = NULL;
     while (BunchTail){
         le = BunchTail;
         BunchTail = BunchTail -> next;
         delete ((uvsBunch*)le);
     }
     BunchTail = NULL;
     while (TabuTaskTypeTail){
         le = TabuTaskTypeTail;
         TabuTaskTypeTail = TabuTaskTypeTail -> next;
         delete ((uvsTabuTaskType*)le);
     }
     TabuTaskTypeTail = NULL;
     delete[] TabuTable;
 //  CloseCyclicPal();
 };
References ETail, MAX_ITEM_TYPE, MAX_MECHOS_TYPE, NULL, uvsItemTable, uvsMechosTable, and UVS_OBJECT::VANGER.
Referenced by uniVangLoad().
uniVangLoad()
void uniVangLoad (XStream & pfile)
{
 //  XStream pfile;
     PrmFile pf;
     int count, i;
     uniVangDelete();
     uvsTownName = NULL;
     uvsQuantFlag = 0;
     ETail = NULL;
     pfile > uvsLoadVersion;
     if (uvsLoadVersion > 12)
         pfile > uvsGamerWaitGame;
     else
         uvsGamerWaitGame = 0;
     // item initing
     pf.init(PrmFileName[6]);
     if(strcmp(PrmSignature,pf.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[6]);
     MAX_ITEM_TYPE = atoi(pf.getAtom());
     uvsItemTable = new uvsItemType*[MAX_ITEM_TYPE];
     for( i = 0; i < MAX_ITEM_TYPE; i++)
         uvsItemTable[i] = new uvsItemType(&pf);
     pf.finit();
     // mechos initing
     pf.init(PrmFileName[7]);
     if(strcmp(PrmSignature,pf.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[7]);
     MAX_MECHOS_MAIN = atoi(pf.getAtom());
     MAX_MECHOS_RAFFA = atoi(pf.getAtom());
     MAX_MECHOS_CONSTRACTOR = atoi(pf.getAtom());
     MAX_MECHOS_TYPE = MAX_MECHOS_MAIN + MAX_MECHOS_RAFFA + MAX_MECHOS_CONSTRACTOR;
     uvsMechosTable = new uvsMechosType*[MAX_MECHOS_TYPE];
     for( i = 0; i < MAX_MECHOS_TYPE; i++){
         uvsMechosTable[i] = new uvsMechosType(&pf);
     }//  end for i
     pf.finit();
 // worlds initing
 //  pfile.open("save", XS_IN);
     pfile > count;
     WorldTail = NULL;
     uvsWorld* pw;
     for( i = 0; i < count; i++ ) (pw = new uvsWorld(pfile)) -> link(WorldTail);
     DollyTail = NULL;
     // dolly initing
     pfile > count;
     uvsDolly* pd;
     for( i = 0; i < count; i++)  (pd = new uvsDolly(pfile)) -> link(DollyTail);
     // escaves initing
     pfile > count;
     uvsEscave* pe;
     for( i = 0; i < count; i++)  (pe = new uvsEscave(pfile)) -> link(EscaveTail);
     // spots initing
     pfile > count;
     uvsSpot* ps;
     for( i =0; i < count; i++) (ps = new uvsSpot(pfile)) -> link(SpotTail);
     // passages initing
     pfile > count;
     uvsPassage* pp;
     for(i = 0; i < count; i++) (pp = new uvsPassage(pfile)) -> link(PassageTail);
     // bunches initing
     pfile > count;
     uvsBunch* pb;
     pf.init(PrmFileName[4]);
     if(strcmp(PrmSignature,pf.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[4]);
     for(i = 0; i < count; i++) (pb = new uvsBunch(pfile, &pf, pf.getAtom())) -> link(BunchTail);
     pf.finit();
     // TabuTask Initing
     MAX_TABUTASK = 0;
     char* atom;
     pf.init(PrmFileName[10]);
     if(strcmp(PrmSignature,pf.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[10]);
     uvsTabuTaskType* pt;
     while((atom = pf.getAtom()) != NULL) (pt = new uvsTabuTaskType(&pf,atom)) -> link(TabuTaskTypeTail);
     pf.finit();
     if (_pe_) _pe_ -> TabuTaskCount = MAX_TABUTASK - _pe_ -> TabuTaskID;
     if (_ps_) _ps_ -> TabuTaskCount = MAX_TABUTASK - _ps_ -> TabuTaskID;
     _ps_ = NULL;
     _pe_ = NULL;
     TabuTable = new uvsTabuTaskType*[MAX_TABUTASK];
     pt = (uvsTabuTaskType*)TabuTaskTypeTail;
     for( i = 0; i < MAX_TABUTASK; i++){
         TabuTable[i] = pt;
         pt = (uvsTabuTaskType*)pt -> next;
     }
     // stationary objects linking
     pw = (uvsWorld*)WorldTail;
     while(pw){
         i = 0;
         if (pw -> escTmax){
             pw -> escT = new uvsEscave*[pw -> escTmax];
             pe = (uvsEscave*)EscaveTail;
             while(pe){
                 if(pe -> Pworld == pw) pw -> escT[i++] = pe;
                 pe = (uvsEscave*)pe -> next;
                 }
         }
         i = 0;
         if (pw -> sptTmax){
             pw -> sptT = new uvsSpot*[pw -> sptTmax];
             ps = (uvsSpot*)SpotTail;
             while(ps){
                 if(ps -> Pworld == pw) pw -> sptT[i++] = ps;
                 ps = (uvsSpot*)ps -> next;
                 }
         }
         i = 0;
         pw -> pssT = new uvsPassage*[pw -> pssTmax];
         pp = (uvsPassage*)PassageTail;
         while(pp){
             if(pp -> Pworld == pw) pw -> pssT[i++] = pp;
             pp = (uvsPassage*)pp -> next;
             }
         pw = (uvsWorld*)pw -> next;
         }
     // vangers initing
     pfile > cVngNumber;
     pe = (uvsEscave*)EscaveTail;
     uvsVanger* v;
     int j = 0;
     Gamer = NULL;
     for(i = 0;i < cVngNumber;i++){
         (v = new uvsVanger(pfile));
         if( v -> shape == UVS_VANGER_SHAPE::GAMER  ){
             Gamer = v;
             v -> shape = UVS_VANGER_SHAPE::GAMER;
         }
         v -> elink(ETail);
     }
     if (!Gamer) ErrH.Abort("uniVangLoad : Gamer not FOUND");
     uvsElement* e = ETail;
     while(e){
         if ( e -> type == UVS_OBJECT::VANGER){
             v = (uvsVanger*)e;
             if (v -> shape == UVS_VANGER_SHAPE::KILLER )
                 v -> go_to_GAMER();
         }
         e = e -> enext;
     }
     Gamer -> UpdateAllTarget();
     pt = (uvsTabuTaskType*)TabuTaskTypeTail;
     for(i = 0; i < MAX_TABUTASK; i++){
         int _i_;
         pfile > pt -> status;
         for(j = 0; j < pt -> item_number; j++)
             pt -> real_count[j] = 0;
         if (uvsLoadVersion < 3 || (i >= WorldTable[2] -> escT[0] -> TabuTaskID && uvsLoadVersion < 6) )
 //      if (uvsLoadVersion < 3 )
             pfile > *pt -> real_count;
         else {
             for(j = 0; j < pt -> item_number; j++)
                 pfile > pt -> real_count[j];
         }
         if (pt -> target == UVS_TARGET::VANGER && pt -> status){
             pfile > _i_;
             uvsElement* p = ETail;
             uvsVanger* v;
             while(p){
                 if(p -> type == UVS_OBJECT::VANGER){
                     v = (uvsVanger*)p;
                     if(v -> gIndex == _i_ ) {
                         pt -> Ptarget = (uvsTarget*)v;
                         break;
                     }//  end if
                 }//  end if
                 p = p -> enext;
             }//  end while
         }//  end if
         pt = (uvsTabuTaskType*)pt -> next;
     }
     int local;
     for(i = MAX_TABUTASK; i < MAX_TABUTASK_RESERVED; i++){
         pfile > local;
         pfile > local;
     }
 #ifdef _ROAD_
     pfile > CurrentWorld;
     pfile > lastMechos;
     //Gamer = v;
     int ObjNum = 0;
     pp = (uvsPassage*)PassageTail;
     while(pp){
         ObjNum++;
         pp = (uvsPassage*)pp -> next;
         }
     pe = (uvsEscave*)EscaveTail;
     while(pe){
         ObjNum++;
         pe -> link_good();
         pe = (uvsEscave*)pe -> next;
         }
     ps = (uvsSpot*)SpotTail;
     while(ps){
         ObjNum++;
         ps -> link_good();
         ps = (uvsSpot*)ps -> next;
         }
     //AllocateGamePort(ObjNum);
 #else
     CurrentWorld = -1;
 #endif
 #ifdef _ROAD_
     if (Gamer -> Pworld -> escTmax){
         uvsCurrentCycle = Gamer -> Pworld -> escT[0] -> Pbunch -> currentStage;
         if (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE){
             uvsCurrentWorldUnable = 1;
             uvsCurrentWorldUnableBefore = 1;
         } else {
             uvsCurrentWorldUnable = 0;
             uvsCurrentWorldUnableBefore = 0;
         }
     } else {
         uvsCurrentCycle = 0;
         uvsCurrentWorldUnable = 0;
         uvsCurrentWorldUnableBefore = 0;
     }
 #endif
     ConTimer.load(pfile);
     GamerResult.Load(pfile);
     uvsMechosLoad(pfile);
     /*for( i = 0; i < MAX_ITEM_TYPE; i++) {
         if (uvsItemTable[i] -> gamer_use) {
             std::cout<<"gamer use item:"<<uvsItemTable[i]->type<<std::endl;
         }
     }*/
     if (uvsLoadVersion > 10)
         pfile > uvsPoponkaID;
     if (uvsPoponkaID >= DG_POPONKA_MAX || uvsPoponkaID < 0)
         uvsPoponkaID = RND(DG_POPONKA_MAX);
     //pfile.close();
 #ifdef STAND_REPORT
     stand < ConTimer.GetTime() < "  LOAD STAND\n";
 #endif
     ReadPriceList();
     //XCon < "Worlds Loaded...\n\n";
     CloseCyclicPal();
     OpenCyclicPal();
 };
References ETail, NULL, pf, uniVangDelete(), uvsGamerWaitGame, uvsLoadVersion, uvsQuantFlag, and uvsTownName.
Referenced by acsLoadData().
uniVangPrepare()
void uniVangPrepare (void)
{
     std::cout<<"uniVangPrepare"<<std::endl;
     uvsEscave* pe;
     PrmFile pfile;
     char* atom;
     int i;
     aci_curLocationName = "";
     uvsLastEscaveName = "";
     DollyIndex = 1;
     uvsQuantFlag = 0;
     uvsPoponkaID = RND(DG_POPONKA_MAX);
     uniVangDelete();
     CurrentWorld = 0;
     if (NetworkON){
         NetStatisticInit();
         NetStatisticGameStart();
         RNDVAL = my_server_data.InitialRND|1;
         switch (my_server_data.GameType){
         case VAN_WAR:
             break;
         case MECHOSOMA:
             break;
         case PASSEMBLOSS:
             break;
         case HUNTAGE:
             break;
         case MUSTODONT:
             uvsUnikumeMechos = 0;
             break;
         };
     }
     uvsTownName = NULL;
     // item initing
     pfile.init(PrmFileName[6]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[6]);
     MAX_ITEM_TYPE = atoi(pfile.getAtom());
     uvsItemTable = new uvsItemType*[MAX_ITEM_TYPE];
     for( i = 0; i < MAX_ITEM_TYPE; i++){
         uvsItemTable[i] = new uvsItemType(&pfile);
     }//  end for i
     pfile.finit();
     // worlds initing
     pfile.init(PrmFileName[0]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[0]);
     uvsWorld* pw;
     while((atom = pfile.getAtom()) != NULL) (pw = new uvsWorld(&pfile,atom)) -> link(WorldTail);
     pfile.finit();
     // escaves initing
     pfile.init(PrmFileName[1]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[1]);
     while((atom = pfile.getAtom()) != NULL) (pe = new uvsEscave(&pfile,atom)) -> link(EscaveTail);
     pfile.finit();
     // spots initing
     pfile.init(PrmFileName[2]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[2]);
     uvsSpot* ps;
     while((atom = pfile.getAtom()) != NULL) (ps = new uvsSpot(&pfile,atom)) -> link(SpotTail);
     pfile.finit();
     // passages initing
     pfile.init(PrmFileName[3]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[3]);
     uvsPassage* pp;
     while((atom = pfile.getAtom()) != NULL) (pp = new uvsPassage(&pfile,atom)) -> link(PassageTail);
     pfile.finit();
 // mechos initing
     pfile.init(PrmFileName[7]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[7]);
     MAX_MECHOS_MAIN = atoi(pfile.getAtom());
     MAX_MECHOS_RAFFA = atoi(pfile.getAtom());
     MAX_MECHOS_CONSTRACTOR = atoi(pfile.getAtom());
     MAX_MECHOS_TYPE = MAX_MECHOS_MAIN + MAX_MECHOS_RAFFA + MAX_MECHOS_CONSTRACTOR;
     uvsMechosTable = new uvsMechosType*[MAX_MECHOS_TYPE];
     for( i = 0; i < MAX_MECHOS_TYPE; i++){
         uvsMechosTable[i] = new uvsMechosType(&pfile);
     }//  end for i
     pfile.finit();
     // TabuTask Initing
     MAX_TABUTASK = 0;
     pfile.init(PrmFileName[10]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[10]);
     uvsTabuTaskType* pt;
     while((atom = pfile.getAtom()) != NULL) (pt = new uvsTabuTaskType(&pfile,atom)) -> link(TabuTaskTypeTail);
     pfile.finit();
     if (_pe_) _pe_ -> TabuTaskCount = MAX_TABUTASK - _pe_ -> TabuTaskID;
     if (_ps_) _ps_ -> TabuTaskCount = MAX_TABUTASK - _ps_ -> TabuTaskID;
     _ps_ = NULL;
     _pe_ = NULL;
     TabuTable = new uvsTabuTaskType*[MAX_TABUTASK];
     pt = (uvsTabuTaskType*)TabuTaskTypeTail;
     for( i = 0; i < MAX_TABUTASK; i++){
         TabuTable[i] = pt;
         pt = (uvsTabuTaskType*)pt -> next;
     }
     // stationary objects linking
     pw = (uvsWorld*)WorldTail;
     int __t = 1;
     int _t = 1;
     while(pw) {
         i = 0;
         if (pw->escTmax) {
             if (pw->escT != NULL) {
                 delete[] pw->escT;
             }
             pw->escT = new uvsEscave*[pw->escTmax];
             pe = (uvsEscave*)EscaveTail;
             while(pe){
                 if (__t)
                     pe -> link_good();
                 if(pe -> Pworld == pw){
                     if ( i == pw -> escTmax ) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,"escave graiter when MAX");
                     pw -> escT[i++] = pe;
                 }
                 pe = (uvsEscave*)pe -> next;
             }
             __t = 0;
         }
         i = 0;
         if (pw -> sptTmax){
             pw -> sptT = new uvsSpot*[pw -> sptTmax];
             ps = (uvsSpot*)SpotTail;
             while(ps){
                 if (_t)
                     ps -> link_good();
                 if(ps -> Pworld == pw) {
                     if ( i == pw -> sptTmax ) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,"spot graiter when MAX");
                     pw -> sptT[i++] = ps;
                 }
                 ps = (uvsSpot*)ps -> next;
                 }
             _t = 0;
         }
         i = 0;
         pw -> pssT = new uvsPassage*[pw -> pssTmax];
         pp = (uvsPassage*)PassageTail;
         while(pp){
             if(pp -> Pworld == pw) {
                 if ( i == pw -> pssTmax ) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,"passage graiter when MAX");
                 pw -> pssT[i++] = pp;
             }
             pp = (uvsPassage*)pp -> next;
             }
         pw = (uvsWorld*)pw -> next;
         }
     //znfo
     for( i = 0; i < MAX_ITEM_TYPE; i++){
         if ( uvsItemTable[i] -> type == UVS_ITEM_STATUS::WEAPON) {
 #ifdef ALL_ITEM_IN_SHOP
             if(1)
 #else
             if (i == UVS_ITEM_TYPE::MACHOTINE_GUN_LIGHT ||
                 i == UVS_ITEM_TYPE::SPEETLE_SYSTEM_LIGHT ||
                 i == UVS_ITEM_TYPE::GHORB_GEAR_LIGHT )
 #endif
                 for( int j = 0; j < MAIN_WORLD_MAX; j++) WorldTable[j] -> generate_item( i );
             else
                 WorldTable[RND(3)] -> generate_item( i );
         } else if (uvsItemTable[i] -> type == UVS_ITEM_STATUS::DEVICE){
 #ifdef ALL_ITEM_IN_SHOP
             for( int j = 0; j < MAIN_WORLD_MAX; j++) WorldTable[j] -> generate_item( i );
 #else
             switch(i){
             case UVS_ITEM_TYPE::COPTE_RIG:
                 WorldTable[2] -> generate_item( i );
                 break;
             case UVS_ITEM_TYPE::CROT_RIG:
                 WorldTable[0] -> generate_item( i );
                 break;
             case UVS_ITEM_TYPE::CUTTE_RIG:
                 WorldTable[1] -> generate_item( i );
                 break;
             case UVS_ITEM_TYPE::RADAR_DEVICE:
                 WorldTable[RND(3)] -> generate_item( i );
                 break;
             }//  end switch
 #endif
         } else
             for( int j = 0; j < MAIN_WORLD_MAX; j++) WorldTable[j] -> generate_item( i );
     }//  end for i
     // bunches initing
     pfile.init(PrmFileName[4]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[4]);
     uvsBunch* pb;
     while((atom = pfile.getAtom()) != NULL) (pb = new uvsBunch(&pfile,atom)) -> link(BunchTail);
     pfile.finit();
     currentVanger = 1;
     // vangers initing
     pfile.init(PrmFileName[5]);
     if(strcmp(PrmSignature,pfile.getAtom())) ErrH.Abort(PrmWrongMsg,XERR_USER,-1,PrmFileName[5]);
     pe = (uvsEscave*) EscaveTail;
     cVngNumber = atoi(pfile.getAtom());
     int meanN = cVngNumber/(MAIN_WORLD_MAX-1);  //   -   ()
     int j = 0;
     uvsVanger* v;
     uvsMechos* pm;
     meanN = 0;
     //zNfo
     for( int k = 0; k < MAX_MECHOS_MAIN + MAX_MECHOS_RAFFA; k++){
         pe = WorldTable[RND(3)] -> escT[0];
 #ifdef ALL_ITEM_IN_SHOP
         if (1){
 #else
         if (
             (uvsMechosTable[k] -> type == UVS_CAR_TYPE::RAFFA) ||
             (!strcmp(uvsMechosTable[k] -> name, "OxidizeMonk")) ||
             (!strcmp(uvsMechosTable[k] -> name, "Piercator") ) ||
             NetworkON
         ){
 #endif
             pe = (uvsEscave*) EscaveTail;
             while(pe){
                 for( i = 0; i < 4; i++){
                     if (meanN++ < cVngNumber)
                         (v = new uvsVanger(pe)) -> elink(ETail);
                     (pm = new uvsMechos(k)) -> link(pe -> Pshop -> Pmechos);
                     pm -> sort();
                     if ( (MAX_MECHOS_MAIN)/2 >= pm -> type || pm -> type >= MAX_MECHOS_MAIN) pm -> status |= UVS_MECHOS_USED::USES;
 //                  if (NetworkON)
                         pm -> status |= UVS_MECHOS_USED::USES;
                 }//  end for i
                 pe = (uvsEscave*)pe -> next;
             }//  end while
         } else {
             for( i = 0; i < 4; i++){
                 if (meanN++ < cVngNumber)
                     (v = new uvsVanger(pe)) -> elink(ETail);
                 (pm = new uvsMechos(k)) -> link(pe -> Pshop -> Pmechos);
                 pm -> sort();
                 if ( (MAX_MECHOS_MAIN)/2 >= pm -> type || pm -> type >= MAX_MECHOS_MAIN) pm -> status |= UVS_MECHOS_USED::USES;
 //              if (NetworkON)
                     pm -> status |= UVS_MECHOS_USED::USES;
             }//  end for i
         }
     }//  end for k
 /*  pe = (uvsEscave*) EscaveTail;
     for( i = 0; i < cVngNumber; i++){
         (v = new uvsVanger(pe)) -> elink(ETail);
 //      (pm = new uvsMechos(RND(MAX_MECHOS_MAIN + MAX_MECHOS_RAFFA))) -> link(pe -> Pshop -> Pmechos);
 //      if ( (MAX_MECHOS_MAIN)/2 >= pm -> type  ||  pm -> type >= MAX_MECHOS_MAIN) pm -> status |= UVS_MECHOS_USED::USES;
         if (NetworkON)
             pm -> status |= UVS_MECHOS_USED::USES;
         if(++j == meanN){
             j = 0;
             if(pe -> next){
                 pe = (uvsEscave*)pe -> next;
             }//  end if
         }//  end if
     }//  end for i*/
     pe = (uvsEscave*) EscaveTail;
     j = RND(MAX_MECHOS_CONSTRACTOR);
     for( i = 0; i < MAX_MECHOS_CONSTRACTOR; i++,j++){
         if ( j == MAX_MECHOS_CONSTRACTOR ) j = 0;
         (pm = new uvsMechos(MAX_MECHOS_MAIN + MAX_MECHOS_RAFFA + j)) -> link(pe -> Pshop -> Pmechos);
         pm -> status |= UVS_MECHOS_USED::USES;
         if (NetworkON && uvsUnikumeMechos)
             uvsMechosTable[pm -> type] -> constractor = 3;
         if(pe -> next){
             pe = (uvsEscave*)pe -> next;
         }else {
             pe = (uvsEscave*) EscaveTail;
         }//  end if
     }//  end for i
     pfile.finit();
     ReadPriceList();
 #ifdef _ROAD_
     if (NetworkON){
 //zNfo
         RNDVAL *= SDL_GetTicks();
         RNDVAL |= 1;
         uvsRandomWorld = 0;
         uvsQuantity = 0;
         CurrentWorld = 0;
         GamerResult.luck = 100;
         uvsNetworkChangeWorld = 0;
         switch (my_server_data.GameType){
         case VAN_WAR:
             aciUpdateCurCredits(my_server_data.Van_War.InitialCash);
             if (my_server_data.Van_War.Nascency == 255 || my_server_data.Van_War.Nascency == -1)
                 uvsRandomWorld = my_server_data.Van_War.Nascency;
             else
                 CurrentWorld = my_server_data.Van_War.Nascency;
             if (my_server_data.Van_War.WorldAccess)
                 uvsNetworkChangeWorld = 1;
             break;
         case MECHOSOMA:
             aciUpdateCurCredits(my_server_data.Mechosoma.InitialCash);
             CurrentWorld = my_server_data.Mechosoma.World;
             uvsQuantity = my_server_data.Mechosoma.One_at_a_time;
             uvsNetworkChangeWorld = 1;
             break;
         case PASSEMBLOSS:
             aciUpdateCurCredits(my_server_data.Passembloss.InitialCash);
 //          CurrentWorld = my_server_data.Passembloss.RandomEscave;
             if (my_server_data.Passembloss.RandomEscave == 255 || my_server_data.Passembloss.RandomEscave == -1)
                 uvsRandomWorld = my_server_data.Passembloss.RandomEscave;
             else
                 CurrentWorld = my_server_data.Passembloss.RandomEscave;
             break;
         case HUNTAGE:
             aciUpdateCurCredits(my_server_data.Huntage.InitialCash);
             break;
         case MUSTODONT:
             aciUpdateCurCredits(my_server_data.Mustodont.InitialCash);
             uvsUnikumeMechos = my_server_data.Mustodont.UniqueMechosName + MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
             break;
         };
         if (uvsRandomWorld)
             CurrentWorld = RND(3);
     } else
         CurrentWorld = 0;
     WorldTable[ CurrentWorld ] -> GamerVisit++;
     Gamer = v;
     v -> gIndex = 0;
     v -> shape = UVS_VANGER_SHAPE::GAMER;
     Gamer -> status = UVS_VANGER_STATUS::IN_SHOP; // znfo -
     v -> Pworld = WorldTable[ CurrentWorld ];
     v -> Pescave = v -> Pworld -> escT[0];
 #ifdef _DEMO_
     v -> Pescave -> Pbunch -> currentStage = 0;
 #endif
     //zNfo  DEFAULT MECHOS
     // 16 =
     int MechosID = 0;
     if (NetworkON) switch (z_my_server_data.mod_id) {
         case Z_MODS_RAFARUN_ID:     { MechosID = 16; break; } //
         case Z_MODS_TRAKTRIAL_ID:   { MechosID =  7; break; } //
         case Z_MODS_NEPTUN_ID:      { MechosID = 21; break; } //
         case Z_MODS_TEST_ID:        { MechosID =  5; break; } //
         default: MechosID = 5; //
     }
     v -> Pescave -> Pshop -> sellMechos(v -> Pmechos, MechosID);
     v -> Pmechos -> type = MechosID;
     //zNfo  /DEFAULT MECHOS
     v -> Pmechos -> sort();
     uvsCurrentCycle = v -> Pworld -> escT[0] -> Pbunch -> currentStage;
     int ObjNum = 0;
     pp = (uvsPassage*)PassageTail;
     while(pp){
         ObjNum++;
         pp = (uvsPassage*)pp -> next;
         }
     pe = (uvsEscave*)EscaveTail;
     while(pe){
         ObjNum++;
         pe = (uvsEscave*)pe -> next;
         }
     ps = (uvsSpot*)SpotTail;
     while(ps){
         ObjNum++;
         ps = (uvsSpot*)ps -> next;
         }
 #else
     CurrentWorld = -1;
 #endif
     ConTimer.Start();
     GamerResult.Init();
 }
References aci_curLocationName.
Referenced by LoadingRTO1::Init().
uniVangSave()
void uniVangSave (XStream & pfile)
{
     int count, i;
 // worlds initing
 //  pfile.open("save", XS_OUT);
     pfile < uvsVersion;
     pfile < uvsGamerWaitGame;
     count = 0;
     listElem*p = WorldTail;
     while( p ){
         count++;
         p = p -> next;
     }
     pfile < count;
     p = WorldTail;
     for( i = 0; i < count; i++ ){
         ((uvsWorld*)p) -> save(pfile);
         p = p -> next;
     }
 // dolly initing
     count = 0;
     p = DollyTail;
     while( p ){
         count++;
         p = p -> next;
     }
     pfile < count;
     p = DollyTail;
     for( i = 0; i < count; i++){
         ((uvsDolly*)p) -> save(pfile);
         p = p -> next;
     }
     // escaves initing
     count = 0;
     p = EscaveTail;
     while( p ){
         count++;
         p = p -> next;
     }
     pfile < count;
     p = EscaveTail;
     for( i = 0; i < count; i++){
         ((uvsEscave*)p) -> save(pfile);
         p = p -> next;
     }
     // spots initing
     count = 0;
     p = SpotTail;
     while( p ){
         count++;
         p = p -> next;
     }
     pfile < count;
     p = SpotTail;
     for( i =0; i < count; i++){
         ((uvsSpot*)p) -> save(pfile);
         p = p -> next;
     }
     // passages initing
     count = 0;
     p = PassageTail;
     while( p ){
         count++;
         p = p -> next;
     }
     pfile < count;
     p = PassageTail;
     for(i = 0; i < count; i++){
         ((uvsPassage*)p)-> save(pfile);
         p = p -> next;
     }
     // bunches initing
     count = 0;
     p = BunchTail;
     while( p ){
         count++;
         p = p -> next;
     }
     pfile < count;
     p = BunchTail;
     for(i = 0; i < count; i++){
         ((uvsBunch*)p) -> save(pfile);
         p = p -> next;
     }
 // vangers initing
     pfile < cVngNumber;
     uvsElement* e = ETail;
     while(e){
         if( e -> type == UVS_OBJECT::VANGER) ((uvsVanger*)e) -> save(pfile);
         e = e -> enext;
     }
     uvsTabuTaskType *pt = (uvsTabuTaskType*)TabuTaskTypeTail;
     int j;
     for(i = 0; i < MAX_TABUTASK; i++){
         pfile < pt -> status;
         for(j = 0; j < pt -> item_number; j++)
             pfile < pt -> real_count[j];
         if (pt -> target == UVS_TARGET::VANGER && pt -> status)
             pfile < ((uvsVanger*)pt -> Ptarget)-> gIndex;
         pt = (uvsTabuTaskType*)pt -> next;
     }
     for(i = MAX_TABUTASK; i < MAX_TABUTASK_RESERVED; i++){
         pfile < int(0);
         pfile < int(0);
     }
     pfile < CurrentWorld;
     pfile < lastMechos;
     ConTimer.save(pfile);
     GamerResult.Save(pfile);
     uvsMechosSave(pfile);
     pfile < uvsPoponkaID;
 //  pfile.close();
 }
References uvsGamerWaitGame, and uvsVersion.
uvs_aciChangeOneItem() [1/2]
void uvs_aciChangeOneItem (int id_from, int id_to, uvsActInt * ptr)
 {
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     it = aScrDisp -> get_iitem(id_to);
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id_from && p -> uvsDataPtr == ptr){
             it -> clone(p);
             return;
         }
         p = p1;
     }
     aScrDisp -> curMatrix -> set_redraw();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id_from && aScrDisp -> curItem -> uvsDataPtr == ptr){
                 it -> clone(aScrDisp -> curItem);
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
                 return;
         }
     }
     if(aScrDisp -> flags & AS_ISCREEN){
         if(!aScrDisp -> secondMatrix) return;
         p = (invItem*)aScrDisp -> secondMatrix -> items -> last;
         while(p){
             p1 = (invItem*)p -> prev;
             if(p -> ID == id_from && p -> uvsDataPtr == ptr){
                 it -> clone(p);
             }
             p = p1;
         }
         aScrDisp -> secondMatrix -> set_redraw();
     }
 }
References aScrDisp, curMatrix, and prev.
uvs_aciChangeOneItem() [2/2]
void uvs_aciChangeOneItem (int , int , int , int)
 {
     invItem* p,*p1,*it;
     if(!aScrDisp -> curMatrix) return;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     if(!(aScrDisp -> flags & AS_ISCREEN))
         it = aScrDisp -> get_item(id_to);
     else
         it = aScrDisp -> get_iitem(id_to);
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id_from && p -> MatrixX == x && p -> MatrixY == y){
             it -> clone(p);
 //            if(p -> uvsDataPtr) ((uvsActInt*)p -> uvsDataPtr) -> type = id_to;
             return;
         }
         p = p1;
     }
     aScrDisp -> curMatrix -> set_redraw();
     if(aScrDisp -> flags & AS_INV_MOVE_ITEM){
         if(aScrDisp -> curItem -> ID == id_from && aScrDisp -> curItem -> MatrixX == x && aScrDisp -> curItem -> MatrixY == y){
                 it -> clone(aScrDisp -> curItem);
                 set_mouse_cursor(aScrDisp -> curItem -> frame,aScrDisp -> curItem -> ScreenSizeX,aScrDisp -> curItem -> ScreenSizeY);
                 return;
         }
     }
     if(aScrDisp -> flags & AS_ISCREEN){
         if(!aScrDisp -> secondMatrix) return;
         p = (invItem*)aScrDisp -> secondMatrix -> items -> last;
         while(p){
             p1 = (invItem*)p -> prev;
             if(p -> ID == id_from && p -> MatrixX == x && p -> MatrixY == y){
                 it -> clone(p);
             }
             p = p1;
         }
         aScrDisp -> secondMatrix -> set_redraw();
     }
 }
References aScrDisp, and curMatrix.
Referenced by uvsChangeGoodsInList(), and uvsChangeTabuTask().
uvs_aciKillOneItem()
int uvs_aciKillOneItem (int id, int x, int y)
 {
     int ret = 0;
     invItem* p,*p1;
     if(!aScrDisp -> curMatrix) return ret;
     p = (invItem*)aScrDisp -> curMatrix -> items -> last;
     while(p){
         p1 = (invItem*)p -> prev;
         if(p -> ID == id && p -> MatrixX == x && p -> MatrixY == y){
             aScrDisp -> curMatrix -> remove_item(p);
             aScrDisp -> free_item(p);
             return 1;
         }
         p = p1;
     }
     return 0;
 }
References aScrDisp, curMatrix, and prev.
Referenced by uvsVanger::checkDolly(), uvsVanger::prepare_list_for_ActInt(), and uvsDeleteItem().
uvsActIntSell()
void uvsActIntSell (uvsActInt * pa)
{
     uvsEscave *pe;
     uvsSpot *ps;
     char* NameTo;
     char *NameFrom;
     int ID;
     switch(pa -> type){
     case ACI_TABUTASK:
 //  case TABUTASK_BAD:
 //      GamerResult.luck -= TabuTable[pa -> param2 & 0x0000FFFF] -> luck;
         TabuTable[pa -> param2 & 0x0000FFFF] -> Erase(pa -> param1, pa -> param2);
         if (GamerResult.luck < 0) GamerResult.luck = 0;
         break;
     case TABUTASK_GOOD:
 //      GamerResult.luck += TabuTable[pa -> param2 & 0x0000FFFF] -> luck;
 //      if (GamerResult.luck > 100) GamerResult.luck = 100;
         break;
     case ACI_ELEEPOD:
     case ACI_BEEBOORAT:
     case ACI_ZEEX:
         pe = uvsGetEscaveByID(pa -> param2 & 0x0000FFFF);
         ps = uvsGetSpotByID(pa -> param2 & 0x0000FFFF);
         NameFrom = uvsGetNameByID(pa -> param2 & 0x0000FFFF, ID);
         NameTo = uvsGetNameByID(pa -> param2 >>16, ID);
         if (strcmp(NameTo, aci_curLocationName) && !RND(2) && strcmp(NameFrom, aci_curLocationName)){
             if (ps){
                 ps -> Pworld -> escT[0] -> Pbunch -> status |= (int)UVS_BUNCH_STATUS::KILL_GAMER;
             }else if (pe){
                 pe -> Pbunch -> status |= (int)UVS_BUNCH_STATUS::KILL_GAMER;
             }
         }//  end if
         break;
     }
 }
References ACI_BEEBOORAT, aci_curLocationName, ACI_ELEEPOD, ACI_TABUTASK, ACI_ZEEX, GamerResult, UVS_BUNCH_STATUS::KILL_GAMER, uvsGamerResult::luck, uvsEscave::Pbunch, uvsEscave::Pworld, RND(), TabuTable, TABUTASK_GOOD, uvsGetEscaveByID(), uvsGetNameByID(), and uvsGetSpotByID().
uvsActIntSellMechos()
void uvsActIntSellMechos (uvsActInt * pn)
{
      int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
      uvsBunch* pm  = Gamer -> Pworld -> escT[0] -> Pbunch;
     int cq = pm -> cycleTable[ pm -> currentStage ].cirtQ;
     int mq = pm -> cycleTable[ pm -> currentStage ].cirtMAX;
     if ( ((uvsActInt*)pn) -> type >= first_constr && ((uvsActInt*)pn) -> price == 1){
          ((uvsActInt*)pn) -> price = uvsMechosTable[( ((uvsActInt*)pn) -> type)] -> price;
          ((uvsActInt*)pn) -> price = (((uvsActInt*)pn) -> price*1.5*cq + ((uvsActInt*)pn) -> price*(mq-cq))/mq;
          ((uvsActInt*)pn) -> sell_price = (((uvsActInt*)pn) -> sell_price*cq + ((uvsActInt*)pn) -> sell_price*0.5*(mq-cq))/mq;
          double t = ((double)(GamerResult.dominance+GamerResult.add_dominance))/100.0;
          if ( t > 1.0 ) t = 1.0;
          if ( t < -1.0 ) t = -1.0;
          if ( t > 0.0 ){
             double dt = ( ((uvsActInt*)pn) -> price - ((uvsActInt*)pn) -> sell_price)/2.0;
             ((uvsActInt*)pn) -> price -= t*dt;
             ((uvsActInt*)pn) -> sell_price +=  t*dt;
          } else {
             ((uvsActInt*)pn) -> price *= (1.0 - t);
             ((uvsActInt*)pn) -> sell_price *= (1.0 + t);
          }
          if (((uvsActInt*)pn) -> sell_price > ((uvsActInt*)pn) -> price) ((uvsActInt*)pn) -> sell_price = ((uvsActInt*)pn) -> price;
     }
 }
References uvsGamerResult::add_dominance, uvsGamerResult::dominance, Gamer, GamerResult, MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, uvsEscave::Pbunch, uvsEscave::Pworld, and uvsMechosTable.
uvsAddStationaryObjs()
void uvsAddStationaryObjs (void)
{
 #ifdef _ROAD_
     GeneralSystemOpen();
 #endif
 }
References GeneralSystemOpen().
Referenced by LoadingRTO2::Init().
uvsBoorawchickZero()
void uvsBoorawchickZero (void)
{
     GamerResult.BoorawchickGoHimself = 0;
 }
References uvsGamerResult::BoorawchickGoHimself, and GamerResult.
uvsBunchCheck()
void uvsBunchCheck (char * subj)
{
 /*  listElem* l = BunchTail;
     while(l){
         ((uvsBunch*)l) -> Check(subj);
         l = l -> next;
     }*/
     if (Gamer -> shape != UVS_VANGER_SHAPE::GAMER)
         ErrH.Abort("Bad GAMER", XERR_USER, -1, subj);
 }
References XErrorHandler::Abort(), ErrH, Gamer, UVS_VANGER_SHAPE::GAMER, and XERR_USER.
uvsCatchDolly()
int uvsCatchDolly (uvsDolly * pd)
{
     uvsElement* p = ETail;
     uvsVanger* v;
     uvsOrder* ord;
     while(p){
         if(p -> type == UVS_OBJECT::VANGER ){
             v = (uvsVanger*)p;
             if ( v -> shape != UVS_VANGER_SHAPE::GAMER ){
                 ord = v -> orderT;
                 while(ord -> target == UVS_TARGET::PASSAGE) ord++;
                 if (ord -> Ptarget == ((uvsTarget*)(pd)) )
                     v -> go_to_GAMER();
             }//  end if
         }//  end if
         p = p -> enext;
     }//  end while
     pd -> status = UVS_DOLLY_STATUS::CATCH;
     SOUND_LARVA()
     WorldTable[pd -> biosNindex] -> escT[0] -> Pbunch -> status |= (int)UVS_BUNCH_STATUS::KILL_GAMER;
 #ifdef STAND_REPORT
     stand < ConTimer.GetTime();
     stand < "  Catch Dolly " <= pd -> gIndex < " from world " < pd -> Pworld -> name < "\n";
 #endif
     return pd -> gIndex;
 }
References UVS_DOLLY_STATUS::CATCH, ConTimer, ETail, UVS_VANGER_SHAPE::GAMER, uvsContimer::GetTime(), UVS_BUNCH_STATUS::KILL_GAMER, uvsEscave::name, UVS_TARGET::PASSAGE, uvsEscave::Pbunch, uvsEscave::Pworld, SOUND_LARVA, UVS_OBJECT::VANGER, and WorldTable.
Referenced by uvsDolly::ActiveQuant().
uvsChangeCycle()
void uvsChangeCycle (void)
{
     uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
     int i = pb -> currentStage;
     pb -> cycleTable[i].cirtQ += pb -> cycleTable[i].cirtMAX;
 }
References Gamer, uvsEscave::Pbunch, and uvsEscave::Pworld.
uvsChangeDominance()
void uvsChangeDominance (void)
{
     GamerResult.dominance += 20;
     ShowDominanceMessage(20);
     if (GamerResult.dominance > 100) GamerResult.dominance = 100;
 }
References uvsGamerResult::dominance, GamerResult, and ShowDominanceMessage().
uvsChangeGoodsInList()
void uvsChangeGoodsInList (int world)
{
     uvsActInt *pa = GGamer;
     if (GGamer){
         while( pa ){
             int type = ActInt_to_Item( pa -> type);
             if (uvsChangeGoodsParam(type, pa -> param1, pa -> param2, world)){
 //              uvs_aciChangeOneItem(pa -> type, uvsSetItemType(type, pa -> param1, pa -> param2), pa);
                 uvs_aciChangeOneItem(pa -> type, uvsSetItemType(type, pa -> param1, pa -> param2), pa -> pos_x, pa -> pos_y);
                 if (uvsSetItemType(type, pa -> param1, pa -> param2) == TABUTASK_GOOD){
                     int param2 = (pa -> param2 & 0x0000FFFF);
                     SOUND_SUCCESS();
                     pa -> type = TABUTASK_GOOD;
                     if (Gamer -> Pescave){
                         if ( (Gamer -> Pescave -> TabuTaskID <= param2) && (Gamer -> Pescave -> TabuTaskCount +Gamer -> Pescave -> TabuTaskID > param2))
                             pa -> sell_price = TabuTable[param2] -> cash;
                     } else {
                         if ( (Gamer -> Pspot -> TabuTaskID <= param2) && (Gamer -> Pspot -> TabuTaskCount +Gamer -> Pspot -> TabuTaskID > param2))
                             pa -> sell_price = TabuTable[param2] -> cash;
                     }
                 } else {
                     SOUND_FAILED();
                     pa -> type = TABUTASK_BAD;
                 }
             }
             pa = (uvsActInt*)(pa -> next);
         }//  end while
     }//  end if
     if (uvsKronActive)
         ChangeItemData(world);
     uvsWorld *pw = (uvsWorld*)WorldTail;
     while( pw ){
         pw -> ChangeGoodsInList(world);
         pw = (uvsWorld*)pw -> next;
     }
 }
References ActInt_to_Item(), ChangeItemData(), Gamer, GGamer, listElem::next, uvsTarget::pos_x, uvsTarget::pos_y, SOUND_FAILED, SOUND_SUCCESS, TabuTable, TABUTASK_BAD, TABUTASK_GOOD, uvsEscave::TabuTaskCount, uvsEscave::TabuTaskID, uvs_aciChangeOneItem(), uvsChangeGoodsParam(), uvsKronActive, and uvsSetItemType().
Referenced by uvsBunch::Quant().
uvsChangeGoodsParam()
int uvsChangeGoodsParam (int type, int & param1, int & param2, int world)
{
     if( uvsItemTable[type] -> type == UVS_ITEM_STATUS::GOODS ) {
         if ((param1>>16) == world) {
             param1++;
             if (type == UVS_ITEM_TYPE::TABUTASK && ((param2 & 0xFFFF0000) == 0) )
                 return TabuTable[param2] -> checkCycleEvent(param1 & 0x0000FFFF, param2);
         }// end if
     }//  end if
     return 0;
 }
References UVS_ITEM_STATUS::GOODS, TabuTable, UVS_ITEM_TYPE::TABUTASK, and uvsItemTable.
Referenced by uvsWorld::ChangeGoodsInList(), ChangeItemData(), and uvsChangeGoodsInList().
uvsChangeLuck()
void uvsChangeLuck (void)
{
     GamerResult.luck += 20;
     ShowLuckMessage(20);
     if (GamerResult.luck > 100) GamerResult.luck = 100;
 }
References GamerResult, uvsGamerResult::luck, and ShowLuckMessage().
uvsChangeRaiting()
void uvsChangeRaiting (void)
{
     if (GamerResult.game_result < 1 )
         return;
     switch (GamerResult.last_game_type){
     case UVS_GAME_ID::ELEECH:
         if (V_RACE_VANGER >= GamerResult.game_result)
             GamerResult.game_elr_result += GAME_RAITING[ GamerResult.game_result-1];
         if ((GamerResult.game_result-1) < 5)
             aciUpdateCurCredits(aciGetCurCredits() + ELEECH[GamerResult.game_result-1]);
         break;
     case UVS_GAME_ID::PIPETKA:
         if (V_RACE_VANGER >= GamerResult.game_result)
             GamerResult.game_pip_result += GAME_RAITING[ GamerResult.game_result-1];
         if ((GamerResult.game_result-1) < 3)
             aciUpdateCurCredits(aciGetCurCredits() + PIPETKA[GamerResult.game_result-1]);
         break;
     case UVS_GAME_ID::KERNOBOO:
         if (V_RACE_VANGER >= GamerResult.game_result)
             GamerResult.game_ker_result += GAME_RAITING[ GamerResult.game_result-1];
         if ((GamerResult.game_result-1) < 3)
             aciUpdateCurCredits(aciGetCurCredits() + KERNOBOO[GamerResult.game_result-1]);
         break;
     case UVS_GAME_ID::WEEZYK:
         if (V_RACE_VANGER >= GamerResult.game_result)
             GamerResult.game_zyk_result += GAME_RAITING[ GamerResult.game_result-1];
         if ((GamerResult.game_result-1) < 1)
             aciUpdateCurCredits(aciGetCurCredits() + WEEZYK[GamerResult.game_result-1]);
         break;
     }//  end switch
 }
References UVS_GAME_ID::ELEECH, uvsGamerResult::game_elr_result, uvsGamerResult::game_result, GamerResult, uvsGamerResult::last_game_type, and V_RACE_VANGER.
Referenced by uvsPrepareQuant().
uvsChangeTabuTask() [1/2]
int uvsChangeTabuTask (int & param1, int & param2, int type, int status)
{
     if ( param2 == type){
         if (status == UVS_TABUTASK_STATUS::BAD){
 //          ShowTaskMessage(-TabuTable[ param2 & 0x0000FFFF] -> luck);
             GamerResult.luck -= TabuTable[ param2 & 0x0000FFFF] -> luck;
             if (GamerResult.luck < 0) GamerResult.luck = 0;
         } else {
 //          ShowTaskMessage(TabuTable[ param2 & 0x0000FFFF] -> luck);
             GamerResult.luck += TabuTable[ param2 & 0x0000FFFF] -> luck;
             if (GamerResult.luck > 100) GamerResult.luck = 100;
         }
         param2 |= (status <<16);
         return param2;
     }
     return 0;
 }
References UVS_TABUTASK_STATUS::BAD, GamerResult, uvsGamerResult::luck, and TabuTable.
uvsChangeTabuTask() [2/2]
void uvsChangeTabuTask (int type, int status)
{
     uvsActInt *pa = GGamer;
     if (status == UVS_TABUTASK_STATUS::BAD){
         ShowTaskMessage(-TabuTable[ type ] -> luck);
     } else {
         ShowTaskMessage(TabuTable[ type] -> luck);
     }
     if (GGamer){
         while( pa ){
             int _type_ = ActInt_to_Item( pa -> type);
             if (_type_ == UVS_ITEM_TYPE::TABUTASK && (pa -> param2 == type)){
                 pa -> param2 |= (status <<16);
                 if (status == UVS_TABUTASK_STATUS::BAD){
                     GamerResult.luck -= TabuTable[ pa -> param2 & 0x0000FFFF] -> luck;
                     if (GamerResult.luck < 0) GamerResult.luck = 0;
                 } else {
                     GamerResult.luck += TabuTable[ pa -> param2 & 0x0000FFFF] -> luck;
                     if (GamerResult.luck > 100) GamerResult.luck = 100;
                 }
                 if (status == UVS_TABUTASK_STATUS::GOOD){
                     SOUND_SUCCESS();
 //                  uvs_aciChangeOneItem(pa -> type, TABUTASK_GOOD, pa );
                     uvs_aciChangeOneItem(pa -> type, TABUTASK_GOOD, pa -> pos_x, pa -> pos_y);
                     pa -> type = TABUTASK_GOOD;
                     int param2 = pa -> param2 & 0x0000FFFF;
                     if (Gamer -> Pescave){
                         if ( (Gamer -> Pescave -> TabuTaskID <= param2) && (Gamer -> Pescave -> TabuTaskCount +Gamer -> Pescave -> TabuTaskID > param2))
                             pa -> sell_price = TabuTable[param2] -> cash;
                     } else {
                         if ( (Gamer -> Pspot -> TabuTaskID <= param2) && (Gamer -> Pspot -> TabuTaskCount +Gamer -> Pspot -> TabuTaskID > param2))
                             pa -> sell_price = TabuTable[param2] -> cash;
                     }
                 } else {
                     SOUND_FAILED()
                     uvs_aciChangeOneItem(pa -> type, TABUTASK_BAD, pa -> pos_x, pa -> pos_y);
 //                  uvs_aciChangeOneItem(pa -> type, TABUTASK_BAD, pa);
                     pa -> type = TABUTASK_BAD;
                 }
             }
             pa = (uvsActInt*)(pa -> next);
         }//  end while
     }//  end if
     if (uvsKronActive)
         ChangeTabutaskItem(type, status);
     uvsWorld *pw = (uvsWorld*)WorldTail;
     while( pw ){
         pw -> ChangeTabuTaskInList(type, status);
         pw = (uvsWorld*)pw -> next;
     }
 }
References ActInt_to_Item(), UVS_TABUTASK_STATUS::BAD, ChangeTabutaskItem(), Gamer, GamerResult, GGamer, UVS_TABUTASK_STATUS::GOOD, uvsGamerResult::luck, listElem::next, uvsTarget::pos_x, uvsTarget::pos_y, ShowTaskMessage(), SOUND_FAILED, SOUND_SUCCESS, TabuTable, UVS_ITEM_TYPE::TABUTASK, TABUTASK_BAD, TABUTASK_GOOD, uvsEscave::TabuTaskCount, uvsEscave::TabuTaskID, uvs_aciChangeOneItem(), and uvsKronActive.
Referenced by ChangeTabutaskItem(), uvsCheckItemOnTabuTask(), uvsCheckKronIventTabuTask(), uvsCheckVangerTabuTask(), and uvsTabuComplete().
uvsChangeTownTabuTask()
void uvsChangeTownTabuTask (int type)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     uvsSpot *ps = (uvsSpot*)SpotTail;
     int ID;
     while(pe){
         ID = pe -> SeekID( type );
         if (ID != -1){
             pe -> TabuTaskGood++;
             return;
         }
         pe = (uvsEscave*)pe -> next;
     }
     while(ps){
         ID = ps -> SeekID( type );
         if (ID != -1){
             ps -> TabuTaskGood++;
             return;
         }
         ps = (uvsSpot*)ps -> next;
     }
 }
References EscaveTail, listElem::next, uvsEscave::SeekID(), SpotTail, and uvsEscave::TabuTaskGood.
Referenced by uvsTabuTaskType::checkCycleEvent(), uvsCheckItemOnTabuTask(), uvsCheckKronIventTabuTask(), uvsCheckVangerTabuTask(), and uvsTabuComplete().
uvsCheckAllItem()
void uvsCheckAllItem (void)
uvsCheckItem()
int uvsCheckItem (int type)
{
     int i;
     uvsBunch* pb = (uvsBunch*)BunchTail;
     uvsCultGame* pg;
     while(pb){
         for( i = 0; i < pb -> cycleN; i++){
             pg = pb -> cycleTable[i].Pgame;
             if (pg){
                 if (pg -> GoodsTypeBeg == type && pb -> cycleTable[i].Pdolly -> status) return 0;
             }
         }//  end for
         pb = (uvsBunch*)pb -> next;
     }//  end while
     return 1;
 }
Referenced by uvsTabuTaskType::is_able().
uvsCheckItemOnLive()
int uvsCheckItemOnLive (int type)
{
     uvsBunch* pb = (uvsBunch*)BunchTail;
     uvsCultGame* pg;
     while(pb){
         pg = pb -> cycleTable[ pb -> currentStage ].Pgame;
         if (pg){
             if (pg -> GoodsTypeBeg == type) return 1;
         }
         pb = (uvsBunch*)pb -> next;
     }//  end while
     return 0;
 }
Referenced by VangerUnit::CheckOutDevice().
uvsCheckItemOnTabuTask()
void uvsCheckItemOnTabuTask (listElem *& pe, int ID, int IDCount, int what = 1)
{
     int i, j, komplit;
     for( i = 0; i < MAX_TABUTASK; i++){
         if ( TabuTable[i] -> status == UVS_TABUTASK_STATUS::ACTIVE){
             if ((TabuTable[i] -> target == UVS_TARGET::ITEM) && ( i >= ID ) && ( i < ID + IDcount)){
                 switch(TabuTable[i] -> work_on_target){
                 case UVS_TABUTASK_WORK::DELIVER:
                 case UVS_TABUTASK_WORK::DELIVER_ONE:
                 case UVS_TABUTASK_WORK::DELIVER_OR:
                     if (what){
                         for( j = 0; j < TabuTable[i]  -> item_number; j++){
                             int l_count = TabuTable[i] -> item_count[j] - TabuTable[i]  -> real_count[j];
                             TabuTable[i]  -> real_count[j] += ItemCount(pe, TabuTable[i] -> item[j]);
                             uvsDeleteItem(pe, TabuTable[i] -> item[j], l_count);
 //                          uvs_aciKillItem(uvsItemTable[  TabuTable[i] -> item[j] ] -> SteelerTypeFull);
                         }
                     } else {
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             TabuTable[i]  -> real_count[j] -= ItemCount(pe, TabuTable[i] -> item[j]);
                     }
                     if (!what) break;
                     if (TabuTable[i] -> work_on_target != UVS_TABUTASK_WORK::DELIVER_OR){
                         komplit = 1;
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             if (TabuTable[i]  -> real_count[j] < TabuTable[i] -> item_count[j])
                                 komplit = 0;
                     } else {
                         komplit = 0;
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             if (TabuTable[i]  -> real_count[j] >= TabuTable[i] -> item_count[j])
                                 komplit = 1;
                     }
                     if (komplit){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                     if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::DELIVER_ONE)
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             TabuTable[i]  -> real_count[j] = 0;
                     break;
                 }//  end switch
             } else if ( (TabuTable[i] -> target == UVS_TARGET::ESCAVE) || (TabuTable[i] -> target == UVS_TARGET::SPOT) ){
                 int _ID_;
                 if (TabuTable[i] -> target == UVS_TARGET::ESCAVE)
                     _ID_ = ((uvsEscave*)TabuTable[i] -> Ptarget) -> TabuTaskID;
                 else
                     _ID_ = ((uvsSpot*)TabuTable[i] -> Ptarget) -> TabuTaskID;
                 if (_ID_ == ID){
                     switch(TabuTable[i] -> work_on_target){
                     case UVS_TABUTASK_WORK::GO_WITHOUT_DAMAGE:
                     case UVS_TABUTASK_WORK::GO_WITHOUT_GRIB:
 //                  case UVS_TABUTASK_WORK::GO_FLY:
                         if (!what) break;
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                         break;
                     case UVS_TABUTASK_WORK::DELIVER:
                     case UVS_TABUTASK_WORK::DELIVER_ONE:
                     case UVS_TABUTASK_WORK::DELIVER_OR:
                     if (what){
                         for( j = 0; j < TabuTable[i]  -> item_number; j++){
                             int l_count = TabuTable[i] -> item_count[j] - TabuTable[i]  -> real_count[j];
                             TabuTable[i]  -> real_count[j] += ItemCount(pe, TabuTable[i] -> item[j]);
                             uvsDeleteItem(pe, TabuTable[i] -> item[j], l_count);
 //                          uvs_aciKillItem(uvsItemTable[  TabuTable[i] -> item[j] ] -> SteelerTypeFull);
                         }
                     } else {
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             TabuTable[i]  -> real_count[j] -= ItemCount(pe, TabuTable[i] -> item[j]);
                     }
                     if (!what) break;
                     if (TabuTable[i] -> work_on_target != UVS_TABUTASK_WORK::DELIVER_OR){
                         komplit = 1;
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             if (TabuTable[i]  -> real_count[j] < TabuTable[i] -> item_count[j])
                                 komplit = 0;
                     } else {
                         komplit = 0;
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             if (TabuTable[i]  -> real_count[j] >= TabuTable[i] -> item_count[j])
                                 komplit = 1;
                     }
                     if (komplit){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                     if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::DELIVER_ONE)
                         for( j = 0; j < TabuTable[i]  -> item_number; j++)
                             TabuTable[i]  -> real_count[j] = 0;
                     break;
                     }//  end switch
                 }// end if _ID_
             }//  end if taget
         }//  end if status
     }//  end for i
 }
References UVS_TABUTASK_STATUS::ACTIVE, UVS_TABUTASK_WORK::DELIVER, UVS_TABUTASK_WORK::DELIVER_ONE, UVS_TABUTASK_WORK::DELIVER_OR, UVS_TARGET::ESCAVE, UVS_TABUTASK_WORK::GO_WITHOUT_DAMAGE, UVS_TABUTASK_WORK::GO_WITHOUT_GRIB, UVS_TABUTASK_STATUS::GOOD, UVS_TARGET::ITEM, ItemCount(), MAX_TABUTASK, UVS_TABUTASK_STATUS::OK, UVS_TARGET::SPOT, TabuTable, uvsEscave::TabuTaskID, uvsChangeTabuTask(), uvsChangeTownTabuTask(), and uvsDeleteItem().
uvsCheckKronIventTabuTask()
void uvsCheckKronIventTabuTask (int KronType, int KronCount, int MYresult, int MYitem)
{
     int i;
 #ifdef TABU_REPORT
     tabu < ConTimer.GetTime();
     tabu < " Kron Type " <= KronType < "KronCount " <= KronCount < "MYresult " <= MYresult < "MYitem " <= MYitem < "\n";
 #endif
     for( i = 0; i < MAX_TABUTASK; i++){
         if ( TabuTable[i] -> status == UVS_TABUTASK_STATUS::ACTIVE){
             switch(TabuTable[i] -> target){
             case UVS_TARGET::DOLLY:
                 if (KronType == UVS_KRON_EVENT::END_CYCLE){
                     if((TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::CHANGE_CYCLE)
                     &&( i >= Gamer -> Pescave -> TabuTaskID && i < Gamer -> Pescave -> TabuTaskCount + Gamer -> Pescave -> TabuTaskID)){
 //                      if ((*TabuTable[i] -> real_count) == KronCount){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                             uvsChangeTownTabuTask(i);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                             *TabuTable[i]  -> real_count = 0;
 //                      }
                     }//  end if
                 } else if (KronType == UVS_KRON_EVENT::KILL_DOLLY){
                     if(TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::KILL){
                         if ((*TabuTable[i] -> item_count) == KronCount){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                             uvsChangeTownTabuTask(i);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                             *TabuTable[i]  -> real_count = 0;
                         }//  if
                     }
                 }//  end fi
                 break;
             case UVS_TARGET::BEEB:
                 switch(KronType){
                     case UVS_KRON_EVENT::BEEB:
                         if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::KILL_BEEB){
                             (*TabuTable[i] -> real_count) += KronCount;
                             if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                                 uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                                 uvsChangeTownTabuTask(i);
                                 TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                                 *TabuTable[i]  -> real_count = 0;
                             }
                         }
                         break;
                     case UVS_KRON_EVENT::GOLD_BEEB:
                         if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::KILL_BEEB ||
                             TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::KILL_GOLD_BEEB){
                             (*TabuTable[i] -> real_count) += KronCount;
                             if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                                 uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                                 uvsChangeTownTabuTask(i);
                                 TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                                 *TabuTable[i]  -> real_count = 0;
                             }
                         }
                         break;
                 }//  end switch
                 break;
             case UVS_TARGET::GRIB:
                 if (KronType == UVS_KRON_EVENT::GRIB){
                     (*TabuTable[i] -> real_count) += KronCount;
                     if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                 }//  end if
                 break;
             case UVS_TARGET::HIVE:
                 if (KronType == UVS_KRON_EVENT::HIVE){
                     (*TabuTable[i] -> real_count) += KronCount;
                     if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                 }//  end if
                 break;
             case UVS_TARGET::CRYPT:
                 if (KronType == UVS_KRON_EVENT::CRYPT){
                     (*TabuTable[i] -> real_count) += KronCount;
                     if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                 }//  end if
                 break;
             case UVS_TARGET::WHIRLPOOL:
                 if (KronType == UVS_KRON_EVENT::WHIRLPOOL){
                     (*TabuTable[i] -> real_count) += KronCount;
                     if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                 }//  end if
                 break;
             case UVS_TARGET::SWAMP:
                 if (KronType == UVS_KRON_EVENT::SWAMP){
                     (*TabuTable[i] -> real_count) += KronCount;
                     if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                 }//  end if
                 break;
             case UVS_TARGET::SHEILD:
                 if (KronType == UVS_KRON_EVENT::RECHARGE_SHEILD){
                     (*TabuTable[i] -> real_count) += KronCount;
                     if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i]  -> real_count = 0;
                     }
                 }//  end if
                 break;
             case UVS_TARGET::PASSAGE:
                 if (KronType == UVS_KRON_EVENT::ARK_NOY){
                     uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                     uvsChangeTownTabuTask(i);
                     TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                     *TabuTable[i]  -> real_count = 0;
                 }//  end if
                 break;
             case UVS_TARGET::ESCAVE:
             case UVS_TARGET::SPOT:
                 switch(KronType){
                     case UVS_KRON_EVENT::DAMAGE:
                         if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::GO_WITHOUT_DAMAGE){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::BAD);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::SLEEP;
                             *TabuTable[i]  -> real_count = 0;
                         }
                         break;
                     case UVS_KRON_EVENT::FLY_ONLINE:
                         if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::GO_FLY){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                             uvsChangeTownTabuTask(i);
                             *TabuTable[i]  -> real_count = 0;
                         }
                         break;
                     case UVS_KRON_EVENT::GRIB:
                         if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::GO_WITHOUT_GRIB){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::BAD);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::SLEEP;
                             *TabuTable[i]  -> real_count = 0;
                         }
                         break;
                     case UVS_KRON_EVENT::BAD_CIRT:
                         if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::DELIVER_BAD_CIRT){
                             uvsTarget* pt;
                             if (Gamer -> Pescave)
                                 pt = (uvsTarget*)Gamer -> Pescave;
                             else
                                 pt = (uvsTarget*)Gamer -> Pspot;
                             if (pt == TabuTable[i]  -> Ptarget){
                                 uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                                 uvsChangeTownTabuTask(i);
                                 TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                                 *TabuTable[i]  -> real_count = 0;
                             }//  end if
                         }//  end if
                         break;
                 }//  end switch
                 break;
             case UVS_TARGET::VANGERS:
                 if (KronType == UVS_KRON_EVENT::SHOT){
                     if (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::SHOT_ANY){
                         int NEEDFlag = *TabuTable[i] -> item;
                         int KronFlag = KronCount & NEEDFlag;
                         if ( ((KronFlag & 0x0000000F) == (NEEDFlag & 0x0000000F)) && ( (NEEDFlag & 0x000000F0) == 0 || (KronFlag & 0x000000F0)) && ( (NEEDFlag & 0x00000F00) == 0 || (KronFlag & 0x00000F00)) ){
                             (*TabuTable[i] -> real_count)++;
 #ifdef TABU_REPORT
     tabu < " count " <= (*TabuTable[i] -> real_count) < " need " <= (*TabuTable[i] -> item_count)< "\n ";
 #endif
                             if ((*TabuTable[i] -> real_count) >= (*TabuTable[i] -> item_count)){
                                 uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                                 uvsChangeTownTabuTask(i);
                                 TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                                 *TabuTable[i]  -> real_count = 0;
                             }//  end if
                         }//  end if
                     }//end if
                 }//  end if
                 break;
             case UVS_TARGET::RACE:
                 if ( (KronType == UVS_KRON_EVENT::END_RACE) && (KronCount >= *TabuTable[i] -> item_count)
                      && ((MYresult == (*TabuTable[i] -> real_count)) || ((*TabuTable[i] -> real_count) == -1)) && (MYitem == *TabuTable[i] -> item)) {
                     if (TabuTable[i] -> work_on_target != UVS_TABUTASK_WORK::END_RACE_RAFFA){
                         if ((TabuTable[i] -> param == -1) || (Gamer -> Pmechos -> type == TabuTable[i] -> param)){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                             uvsChangeTownTabuTask(i);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         }
                     } else if (uvsMechosTable[Gamer -> Pmechos -> type] -> type == UVS_CAR_TYPE::RAFFA){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                     }
                 } else if (KronType == UVS_KRON_EVENT::WEAPON_ON && (TabuTable[i] -> work_on_target == UVS_TABUTASK_WORK::END_RACE_WEAPON)){
                     if (Gamer -> Pworld -> gIndex < 3){
                         uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
                         if (pb -> cycleTable[ pb -> currentStage ].Pgame && pb -> cycleTable[ pb -> currentStage ].Pgame -> GoodsTypeEnd == (*TabuTable[i] -> item)){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::BAD);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::SLEEP;
                         }//  end if
                     }//  end if
                 }//  end if
             }//  end if
         }//  end if status
     }//  end for i
 }
References UVS_TABUTASK_STATUS::ACTIVE, UVS_KRON_EVENT::ARK_NOY, UVS_TABUTASK_STATUS::BAD, UVS_KRON_EVENT::BAD_CIRT, UVS_KRON_EVENT::BEEB, UVS_TARGET::BEEB, UVS_TABUTASK_WORK::CHANGE_CYCLE, ConTimer, UVS_KRON_EVENT::CRYPT, UVS_TARGET::CRYPT, UVS_KRON_EVENT::DAMAGE, UVS_TABUTASK_WORK::DELIVER_BAD_CIRT, UVS_TARGET::DOLLY, UVS_KRON_EVENT::END_CYCLE, UVS_KRON_EVENT::END_RACE, UVS_TABUTASK_WORK::END_RACE_RAFFA, UVS_TABUTASK_WORK::END_RACE_WEAPON, UVS_TARGET::ESCAVE, UVS_KRON_EVENT::FLY_ONLINE, Gamer, uvsContimer::GetTime(), UVS_TABUTASK_WORK::GO_FLY, UVS_TABUTASK_WORK::GO_WITHOUT_DAMAGE, UVS_TABUTASK_WORK::GO_WITHOUT_GRIB, UVS_KRON_EVENT::GOLD_BEEB, UVS_TABUTASK_STATUS::GOOD, UVS_KRON_EVENT::GRIB, UVS_TARGET::GRIB, UVS_KRON_EVENT::HIVE, UVS_TARGET::HIVE, UVS_TABUTASK_WORK::KILL, UVS_TABUTASK_WORK::KILL_BEEB, UVS_KRON_EVENT::KILL_DOLLY, UVS_TABUTASK_WORK::KILL_GOLD_BEEB, MAX_TABUTASK, UVS_TABUTASK_STATUS::OK, UVS_TARGET::PASSAGE, uvsEscave::Pbunch, uvsEscave::Pworld, UVS_TARGET::RACE, UVS_CAR_TYPE::RAFFA, UVS_KRON_EVENT::RECHARGE_SHEILD, UVS_TARGET::SHEILD, UVS_KRON_EVENT::SHOT, UVS_TABUTASK_WORK::SHOT_ANY, UVS_TABUTASK_STATUS::SLEEP, UVS_TARGET::SPOT, UVS_KRON_EVENT::SWAMP, UVS_TARGET::SWAMP, TabuTable, uvsEscave::TabuTaskCount, uvsEscave::TabuTaskID, uvsChangeTabuTask(), uvsChangeTownTabuTask(), uvsMechosTable, UVS_TARGET::VANGERS, UVS_KRON_EVENT::WEAPON_ON, UVS_KRON_EVENT::WHIRLPOOL, and UVS_TARGET::WHIRLPOOL.
Referenced by VangerUnit::BulletCollision(), VangerUnit::DestroyCollision(), uvsBunch::end_harvest(), BulletObject::Event(), GameObjectDispatcher::Quant(), JumpBallObject::Quant(), VangerUnit::Quant(), VangerUnit::SensorQuant(), ActionDispatcher::SlotIn(), VangerUnit::test_objects_collision(), HordeSource::Touch(), InsectUnit::Touch(), VangerUnit::TouchSensor(), and uvsFreeDolly().
uvsCheckVangerTabuTask()
void uvsCheckVangerTabuTask (uvsVanger * pv, int how)
{
     int i;
     for( i = 0; i < MAX_TABUTASK; i++){
         if (TabuTable[i] -> status == UVS_TABUTASK_STATUS::ACTIVE){
             switch(TabuTable[i] -> target){
             case UVS_TARGET::VANGER:
                 if ( TabuTable[i] -> Ptarget == ((uvsTarget*)pv) ){
                     switch(TabuTable[i] -> work_on_target){
                     case UVS_TABUTASK_WORK::GO_OUT:
                         if ( how == uvsVANGER_ARRIVAL ){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::BAD);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::SLEEP;
                         } else {
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                             uvsChangeTownTabuTask(i);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         }
                         pv -> shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
 //                      TabuTable[i]  -> status = UVS_TABUTASK_STATUS::SLEEP;
                         break;
                     case UVS_TABUTASK_WORK::KILL:
                         if ( how == uvsVANGER_FAILED || how == uvsVANGER_KILLED) {
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                             uvsChangeTownTabuTask(i);
                             pv -> shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                         }
                         break;
                     case UVS_TABUTASK_WORK::DEFENSE:
                         if ( how == uvsVANGER_ARRIVAL ){
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::BAD);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::SLEEP;
                         } else {
                             uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                             TabuTable[i]  -> status = UVS_TABUTASK_STATUS::OK;
                             uvsChangeTownTabuTask(i);
                         }
                         pv -> shape = UVS_VANGER_SHAPE::BUNCH_SLAVE;
 //                      TabuTable[i]  -> status = UVS_TABUTASK_STATUS::SLEEP;
                         break;
                     }//  end switch
                 }//  end if
                 break;
             case UVS_TARGET::VANGERS:
                 if ( how == uvsVANGER_KILLED){
                     switch(TabuTable[i] -> work_on_target){
                     case UVS_TABUTASK_WORK::KILL:
                         int NEEDFlag = *TabuTable[i] -> item;
                         int Mask = 0;
                         if (pv -> status == UVS_VANGER_STATUS::RACE)
                             Mask |= UVS_KRON_FLAG::ELEREC;
                         else if (pv -> status == UVS_VANGER_STATUS::RACE_HUNTER)
                             Mask |= UVS_KRON_FLAG::ZEEXL;
                         else if (CurrentWorld == 1 && uvsCurrentCycle == 1)
                             Mask |= UVS_KRON_FLAG::PIP;
                         else if (CurrentWorld == 1 && uvsCurrentCycle == 2)
                             Mask |= UVS_KRON_FLAG::KERN;
                         switch(pv -> Pmechos -> color){
                         case 0: Mask |= UVS_KRON_FLAG::ELIPOD;
                             break;
                         case 1: Mask |= UVS_KRON_FLAG::BEEBO;
                             break;
                         case 2: Mask |= UVS_KRON_FLAG::ZEEX;
                             break;
                         }//  end switch
                         int KronFlag = Mask & NEEDFlag;
                         if ( ( (NEEDFlag & 0x000000F0) == 0 || (KronFlag & 0x000000F0)) && ( (NEEDFlag & 0x00000F00) == 0 || (KronFlag & 0x00000F00)) ){
                             (*TabuTable[i]  -> real_count)++;
                             if ((*TabuTable[i]  -> real_count) >= (*TabuTable[i]  -> item_count)){
                                 uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                                 uvsChangeTownTabuTask(i);
                                 TabuTable[i] -> status = UVS_TABUTASK_STATUS::OK;
                                 *TabuTable[i] -> real_count = 0;
                             }//  end if
                         }
 ;
                         break;
                     }//  ens switch
                 }//  end if
                 break;
             case UVS_TARGET::RAFFA:
                 if ( uvsMechosTable[ pv -> Pmechos -> type ] -> type == UVS_CAR_TYPE::RAFFA && how == uvsVANGER_KILLED ){
                     (*TabuTable[i]  -> real_count)++;
                     if ((*TabuTable[i]  -> real_count) >= (*TabuTable[i]  -> item_count)){
                         uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
                         uvsChangeTownTabuTask(i);
                         TabuTable[i] -> status = UVS_TABUTASK_STATUS::OK;
                         *TabuTable[i] -> real_count = 0;
                     }//  end if
                 }//  end if
                 break;
             }//  end switch
         }//  end if
     }//  end for i
 }
References UVS_TABUTASK_STATUS::ACTIVE, UVS_TABUTASK_STATUS::BAD, UVS_KRON_FLAG::BEEBO, UVS_VANGER_SHAPE::BUNCH_SLAVE, CurrentWorld, UVS_TABUTASK_WORK::DEFENSE, UVS_KRON_FLAG::ELEREC, UVS_KRON_FLAG::ELIPOD, UVS_TABUTASK_WORK::GO_OUT, UVS_TABUTASK_STATUS::GOOD, UVS_KRON_FLAG::KERN, UVS_TABUTASK_WORK::KILL, MAX_TABUTASK, UVS_TABUTASK_STATUS::OK, UVS_KRON_FLAG::PIP, UVS_VANGER_STATUS::RACE, UVS_VANGER_STATUS::RACE_HUNTER, UVS_CAR_TYPE::RAFFA, UVS_TARGET::RAFFA, UVS_TABUTASK_STATUS::SLEEP, TabuTable, uvsChangeTabuTask(), uvsChangeTownTabuTask(), uvsCurrentCycle, uvsMechosTable, uvsVANGER_ARRIVAL, uvsVANGER_FAILED, uvsVANGER_KILLED, UVS_TARGET::VANGER, UVS_TARGET::VANGERS, UVS_KRON_FLAG::ZEEX, and UVS_KRON_FLAG::ZEEXL.
Referenced by uvsVanger::destroy(), uvsVanger::homeArrival(), uvsVanger::makeJump(), and uvsVanger::spotArrival().
uvsCloseQuant()
void uvsCloseQuant (void)
{
     //if (!uvsTownName){
         LoadingMessage(1);
 //      WorldTable[CurrentWorld] -> updateCrypt();
         GeneralSystemSkip = 1;
     //} else {
     //  GeneralSystemSkip = 0;
     //}
     GeneralMapReload = 1;
     GeneralSystemOpen();
     if (WorldTable[CurrentWorld]-> escTmax){
         uvsCurrentCycle = WorldTable[CurrentWorld] -> escT[0] -> Pbunch -> currentStage;
         if (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE)
             uvsCurrentWorldUnable = 1;
         else
             uvsCurrentWorldUnable = 0;
     } else {
         uvsCurrentCycle = 0;
         uvsCurrentWorldUnable = 0;
     }
     if (WorldTable[CurrentWorld] -> escTmax){
         WorldPalCurrent = uvsCurrentCycle;
         CloseBunchPal();
         memcpy(actIntPal,WorldPalData[WorldPalCurrent],768);
         memcpy(palbuf,actIntPal,768);
         memcpy(palbufOrg,actIntPal,768);
         memcpy(palbufSrc,actIntPal,768);
         light_modulation  = WorldLightParam[CurrentWorld][WorldPalCurrent];
     }
     Gamer -> get_shop(1);
     if (WorldTable[CurrentWorld] -> escTmax)
         aci_curLocationName = WorldTable[CurrentWorld] -> escT[0] -> name;
     else
         aci_curLocationName = "";
     if (!uvsTownName) {
         uvsRestoreVanger();
     } else {
         uvsTownName = NULL;
     }
 }
References aci_curLocationName, actIntPal, CloseBunchPal(), CurrentWorld, Gamer, GeneralMapReload, GeneralSystemOpen(), GeneralSystemSkip, light_modulation, LoadingMessage(), uvsEscave::name, NULL, palbuf, palbufOrg, palbufSrc, uvsEscave::Pbunch, uvsEscave::Pworld, UVS_BUNCH_STATUS::UNABLE, uvsCurrentCycle, uvsCurrentWorldUnable, uvsRestoreVanger(), uvsTownName, WorldLightParam, WorldPalCurrent, WorldPalData, and WorldTable.
Referenced by EscaveOutRTO::Finit().
uvsCreateItem_in_Crypt()
void uvsCreateItem_in_Crypt (void)
{
 /*      WorldTable[CurrentWorld] -> getItemFromCrypt(UVS_CRYPT::DEVICE);
         WorldTable[CurrentWorld] -> getItemFromCrypt(UVS_CRYPT::AMMO);
         WorldTable[CurrentWorld] -> getItemFromCrypt(UVS_CRYPT::ARMO_LIGHT);
         WorldTable[CurrentWorld] -> getItemFromCrypt(UVS_CRYPT::ARMO_HEAVY);*/
 }
Referenced by LoadingRTO1::Init().
uvsCreateNetVanger()
uvsVanger* uvsCreateNetVanger (int CarType, int Color, int PassageIndex, int TownTabutaskID)
{
     uvsVanger *pv = FindFreeVanger();
     pv -> shape = UVS_VANGER_SHAPE::NETWORK;
     pv -> status = UVS_VANGER_STATUS::MOVEMENT;
     pv -> Pmechos -> type = CarType;
     pv -> Pmechos -> color = Color;
     pv -> Pworld = WorldTable[ CurrentWorld ];
     pv -> owner = NULL;
     if (pv -> Pitem) ErrH.Abort("uvsCreateNetVanger : Pitem not NULL");
     pv -> Pitem = NULL;
     if (PassageIndex != -1 && TownTabutaskID == -1){
         pv -> Pescave = NULL;
         pv -> Pspot = NULL;
         pv -> Ppassage = WorldTable[ CurrentWorld ] -> getPassage(WorldTable[PassageIndex]);
 //      addVanger(pv, pv -> Ppassage);
     } else if (PassageIndex == -1 && TownTabutaskID != -1){
         pv -> Pescave =  uvsGetEscaveByID(TownTabutaskID);
         pv -> Pspot =  uvsGetSpotByID(TownTabutaskID);
 //      if (pv -> Pescave)
 //          addVanger(pv, pv -> Pescave);
 //      else
 //          addVanger(pv, pv -> Pspot);
     } else {
         pv -> Pescave =  NULL;
         pv -> Pspot =  NULL;
         pv -> Ppassage = NULL;
 //      addVanger(pv, PassageIndex, TownTabutaskID);
     }
     return pv;
 }
References XErrorHandler::Abort(), CurrentWorld, ErrH, FindFreeVanger(), UVS_VANGER_STATUS::MOVEMENT, UVS_VANGER_SHAPE::NETWORK, NULL, uvsEscave::Pitem, uvsEscave::Pworld, uvsGetEscaveByID(), uvsGetSpotByID(), and WorldTable.
Referenced by NetEvent4Uvs().
uvsCreateNewCrypt()
void uvsCreateNewCrypt (int x, int y, int z, int type, int iWorld)
{
 //  (new uvsCrypt(x, y, z, type)) -> link(WorldTable[iWorld] -> Pcrypt);
 }
uvsCreateNewItem()
void uvsCreateNewItem (int x, int y, int z, int type, int iWorld)
{
     (new uvsItem(x, y, z, type)) -> link(WorldTable[iWorld] -> Pitem);
 }
References listElem::link(), uvsEscave::Pitem, and WorldTable.
Referenced by ItemsDispatcher::CryptQuant(), NetworkWorldOpen(), and ItemsDispatcher::Open().
uvsDeleteItem()
void uvsDeleteItem (listElem *& pe, int type, int count)
{
     uvsItem* pi = (uvsItem*)pe;
     uvsItem*pl;
     int i = 0;
     while(pi){
         if (pi -> type == type && i < count){
             pl = pi;
             pi = (uvsItem*)pi -> next;
             pl -> delink(pe);
             delete pl;
             i++;
         } else
             pi = (uvsItem*)pi -> next;
     }//  end while
     i = 0;
     uvsActInt* pa = GGamer;
     uvsActInt* pp;
     while( pa ){
         pp = (uvsActInt*)pa -> next;
         if (uvsItemTable[ type ] -> SteelerTypeFull == pa -> type && i < count){
             uvs_aciKillOneItem( pa ->type, pa -> pos_x, pa -> pos_y);
             pa -> delink(GGamer);
             delete pa;
             i++;
         }
         pa = pp;
     }//  end while
 }//
References GGamer, listElem::next, uvsTarget::pos_x, uvsTarget::pos_y, uvs_aciKillOneItem(), and uvsItemTable.
Referenced by uvsCheckItemOnTabuTask().
uvsDomChangeFromItem()
void uvsDomChangeFromItem (int type, int what, int where)
{
     if ( where){
         if (what){
             if (type == UVS_ITEM_TYPE::LEEPURINGA){
                 GamerResult.add_luck += 50;
                 ShowLuckMessage(50);
             }
             if (type == UVS_ITEM_TYPE::BOORAWCHICK){
                 GamerResult.add_dominance += 50;
                 ShowDominanceMessage(50);
             }
             if (type == UVS_ITEM_TYPE::PROTRACTOR){
                 GamerResult.add_luck += 20;
                 ShowLuckMessage(20);
             }
             if (type == UVS_ITEM_TYPE::MECHANIC_MESSIAH){
                 GamerResult.add_dominance += 20;
                 ShowDominanceMessage(20);
             }
         } else {
             if (type == UVS_ITEM_TYPE::LEEPURINGA){
                 GamerResult.add_luck -= 50;
                 ShowLuckMessage(-50);
             }
             if (type == UVS_ITEM_TYPE::BOORAWCHICK){
                 GamerResult.add_dominance -= 50;
                 ShowDominanceMessage(-50);
             }
             if (type == UVS_ITEM_TYPE::PROTRACTOR){
                 GamerResult.add_luck -= 20;
                 ShowLuckMessage(-20);
             }
             if (type == UVS_ITEM_TYPE::MECHANIC_MESSIAH){
                 GamerResult.add_dominance -= 20;
                 ShowDominanceMessage(-20);
             }
         }
 /*      if (GamerResult.dominance > 100) GamerResult.dominance = 100;
         if (GamerResult.luck > 100) GamerResult.luck = 100;
         if (GamerResult.dominance < -100) GamerResult.dominance = -100;
         if (GamerResult.luck < 0 ) GamerResult.luck = 0;*/
     }
     if (what){
         if ( !uvsItemTable[type] -> gamer_use ){
             uvsItemTable[type] -> gamer_use = 1;
             switch( uvsItemTable[type] -> type ){
             case UVS_ITEM_STATUS::ARTIFACT:
                 GamerResult.dominance += 15;
                 ShowDominanceMessage(15);
                 if (GamerResult.dominance > 100) GamerResult.dominance = 100;
                 break;
             case UVS_ITEM_STATUS::WEAPON:
                 GamerResult.dominance += 3;
                 ShowDominanceMessage(3);
                 if (GamerResult.dominance > 100) GamerResult.dominance = 100;
                 break;
             case UVS_ITEM_STATUS::DEVICE:
                 GamerResult.dominance += 3;
                 ShowDominanceMessage(3);
                 if (GamerResult.dominance > 100) GamerResult.dominance = 100;
                 break;
             case UVS_ITEM_STATUS::MECHOS_PART:
                 GamerResult.dominance += 5;
                 ShowDominanceMessage(5);
                 if (GamerResult.dominance > 100) GamerResult.dominance = 100;
                 break;
             }//  end switch
         }//  end if
     }
 }
References uvsGamerResult::add_dominance, uvsGamerResult::add_luck, UVS_ITEM_STATUS::ARTIFACT, UVS_ITEM_TYPE::BOORAWCHICK, UVS_ITEM_STATUS::DEVICE, uvsGamerResult::dominance, GamerResult, UVS_ITEM_TYPE::LEEPURINGA, UVS_ITEM_TYPE::MECHANIC_MESSIAH, UVS_ITEM_STATUS::MECHOS_PART, UVS_ITEM_TYPE::PROTRACTOR, ShowDominanceMessage(), ShowLuckMessage(), uvsItemTable, and UVS_ITEM_STATUS::WEAPON.
Referenced by VangerUnit::CheckInDevice(), and VangerUnit::CheckOutDevice().
uvsFreeDolly()
int uvsFreeDolly (int _x, int _y, int _index_)
{
     listElem* pd = DollyTail;
     while(pd){
         if (((uvsDolly*)pd) -> gIndex == _index_){
             if (CurrentWorld > 3){
 //              ((uvsDolly*)pd) -> status = UVS_DOLLY_STATUS::UNABLE;
                 ((uvsDolly*)pd) -> status = 0;
                 uvsCheckKronIventTabuTask(UVS_KRON_EVENT::KILL_DOLLY, ((uvsDolly*)pd) -> biosNindex);
             } else
                 ((uvsDolly*)pd) -> status = 0;
             ((uvsDolly*)pd) -> Pworld = WorldTable[CurrentWorld];
             ((uvsDolly*)pd) -> pos_x = _x;
             ((uvsDolly*)pd) -> pos_y = _y;
             ((uvsDolly*)pd) -> setSpeed();
 #ifdef STAND_REPORT
         stand < ConTimer.GetTime();
         stand < "  Free Dolly " <= ((uvsDolly*)pd)  -> gIndex < " in world " < WorldTable[CurrentWorld] -> name < "\n";
 #endif
             GamerResult.luck -= 10;
             ShowLuckMessage(-10);
             if (GamerResult.luck < 0) GamerResult.luck = 0;
             return 0;
         }
         pd = pd -> next;
     }
     ErrH.Abort("uvsFreeDolly : dont find dolly");
     return 0;
 }
References XErrorHandler::Abort(), ConTimer, CurrentWorld, DollyTail, ErrH, GamerResult, uvsContimer::GetTime(), UVS_KRON_EVENT::KILL_DOLLY, uvsGamerResult::luck, uvsEscave::name, listElem::next, uvsTarget::pos_x, uvsTarget::pos_y, uvsEscave::Pworld, ShowLuckMessage(), uvsCheckKronIventTabuTask(), and WorldTable.
Referenced by ItemsDispatcher::Close(), ItemsDispatcher::LarvaHilator(), and StuffObject::Quant().
uvsGameRaceFinish()
int uvsGameRaceFinish (void)
{
     uvsWorld* pw = Gamer -> Pworld;
     if (pw -> escTmax){
         uvsBunch *pb = pw -> escT[0] -> Pbunch;
         uvsCultGame *pg = pb -> cycleTable[pb -> currentStage].Pgame;
         if (pg && pg -> GameType ==  UVS_GAME_TYPE::RACE){
             return pg -> result;
         } else
             return 0;
     }else return 0;
 }
References Gamer, uvsEscave::Pbunch, uvsEscave::Pworld, and UVS_GAME_TYPE::RACE.
uvsGameRaceNumber()
int uvsGameRaceNumber (void)
{
     uvsWorld* pw = Gamer -> Pworld;
     if (pw -> escTmax){
         uvsBunch *pb = pw -> escT[0] -> Pbunch;
         uvsCultGame *pg = pb -> cycleTable[pb -> currentStage].Pgame;
         if (pg && pg -> GameType ==  UVS_GAME_TYPE::RACE){
             return (pg -> total + 1);
         } else
             return 0;
     }else return 0;
 }
References Gamer, uvsEscave::Pbunch, uvsEscave::Pworld, and UVS_GAME_TYPE::RACE.
uvsGenerateItemForCrypt()
int uvsGenerateItemForCrypt (int type)
{
     int itype, icount, _type_;
     switch (type){
     case UVS_CRYPT::DEVICE:
         itype = UVS_ITEM_TYPE::AMPUTATOR;
         icount = UVS_ITEM_TYPE::MECHOSCOPE + 1 - itype;
 //      icount = 0;
         return (itype  + RND(icount));
         break;
     case UVS_CRYPT::ARMO_LIGHT:
         itype = UVS_ITEM_TYPE::MACHOTINE_GUN_LIGHT;
         icount = UVS_ITEM_TYPE::TERMINATOR2 + 1 - itype;
         _type_ = RND(icount);
         while( !uvsItemTable[itype + _type_]->size
 #ifdef _DEMO_
             || !uvsItemTable[itype + _type_]->count
 #endif
             )
             _type_ = RND(icount);
         return(itype  + _type_);
         break;
     case UVS_CRYPT::ARMO_HEAVY:
         itype = UVS_ITEM_TYPE::MACHOTINE_GUN_LIGHT;
         icount = UVS_ITEM_TYPE::TERMINATOR2 +1 - itype;
         _type_ = RND(icount);
         while( uvsItemTable[itype + _type_]->size
 #ifdef _DEMO_
             || !uvsItemTable[itype + _type_]->count
 #endif
             )
             _type_ = RND(icount);
         return(itype  + _type_);
         //pi -> param2 = 8;
         break;
     case UVS_CRYPT::AMMO:
         itype = UVS_ITEM_TYPE::SPEETLE_SYSTEM_AMMO0;
         icount = UVS_ITEM_TYPE::GLUEK +1 - UVS_ITEM_TYPE::SPEETLE_SYSTEM_AMMO0;
         _type_ = RND(icount);
 #ifdef _DEMO_
         if ( type + _type_ == UVS_ITEM_TYPE::CRUSTEST_CANNON_AMMO)
             _type_++;
 #endif
         return(itype  + _type_);
         break;
     }
     return -1;
 }
References UVS_CRYPT::AMMO, UVS_ITEM_TYPE::AMPUTATOR, UVS_CRYPT::ARMO_HEAVY, UVS_CRYPT::ARMO_LIGHT, UVS_ITEM_TYPE::CRUSTEST_CANNON_AMMO, UVS_CRYPT::DEVICE, UVS_ITEM_TYPE::GLUEK, UVS_ITEM_TYPE::MACHOTINE_GUN_LIGHT, UVS_ITEM_TYPE::MECHOSCOPE, RND(), UVS_ITEM_TYPE::SPEETLE_SYSTEM_AMMO0, UVS_ITEM_TYPE::TERMINATOR2, and uvsItemTable.
Referenced by ItemsDispatcher::CryptQuant(), InitProtoCrypt(), and ItemsDispatcher::Open().
uvsgetDGdata()
int uvsgetDGdata (int code)
{
     switch( code ){
     case DG_EXTERNS::INV_UNIQUE_POPONKA:
             return GamerResult.unik_poponka;
             break;
         case DG_EXTERNS::ELR_RESULT:
 //          if (GamerResult.get_eleech)
                 return GamerResult.game_result;
 //          else
 //              return 0;
             break;
         case DG_EXTERNS::ELR_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::ELR_RATING:
             return (GamerResult.game_elr_result);
             break;
         case DG_EXTERNS::KER_RESULT:
             return GamerResult.game_result;
             break;
         case DG_EXTERNS::KER_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::KER_RATING:
             return (GamerResult.game_ker_result);
             break;
         case DG_EXTERNS::PIP_RESULT:
             return GamerResult.game_result;
             break;
         case DG_EXTERNS::PIP_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::PIP_RATING:
             return (GamerResult.game_pip_result);
             break;
         case DG_EXTERNS::ZYK_RESULT:
             return GamerResult.game_result;
             break;
         case DG_EXTERNS::ZYK_TOTAL:
             return (GamerResult.game_total);
             break;
         case DG_EXTERNS::ZYK_RATING:
             return (GamerResult.game_zyk_result);
             break;
         case DG_EXTERNS::INV_BAD_CIRT:
             return (GamerResult.cirt_bad);
             break;
         case DG_EXTERNS::INV_GOOD_CIRT:
             return (GamerResult.cirt_good);
             break;
         case DG_EXTERNS::INV_NYMBOS:
             return (GamerResult.nymbos);
             break;
         case DG_EXTERNS::INV_PHLEGMA:
             return (GamerResult.phlegma);
             break;
         case DG_EXTERNS::INV_HEROIN:
             return (GamerResult.heroin);
             break;
         case DG_EXTERNS::INV_SHRUB:
             return (GamerResult.shrub);
             break;
         case DG_EXTERNS::INV_POPONKA:
             return (GamerResult.poponka);
             break;
         case DG_EXTERNS::INV_TOXICK:
             return (GamerResult.toxick);
             break;
         case DG_EXTERNS::INV_PIPETKA:
             return (GamerResult.pipetka);
             break;
         case DG_EXTERNS::INV_KERNOBOO:
             return (GamerResult.kernoboo);
             break;
         case DG_EXTERNS::INV_WEEZYK:
             return (GamerResult.weezyk);
             break;
         case DG_EXTERNS::INV_ELEECH:
             return (GamerResult.eleech);
             break;
         case DG_EXTERNS::INV_DEAD_ELEECH:
             return (GamerResult.dead_eleech_now);
             break;
         case DG_EXTERNS::INV_RUBBOX:
             return (GamerResult.rubbox);
             break;
         case DG_EXTERNS::KILLED_VANGERS:
             return (GamerResult.vanger_kill);
             break;
         case DG_EXTERNS::MECHOS_CHANGED:
             return (GamerResult.mechos_variant);
             break;
         case DG_EXTERNS::MECHOS_TYPE:
             return (GamerResult.mechos_type);
             break;
         case DG_EXTERNS::NYMBOS_DELIVERY:
             return (GamerResult.nymbos_total);
             break;
         case DG_EXTERNS::PHLEGMA_DELIVERY:
             return (GamerResult.phlegma_total);
             break;
         case DG_EXTERNS::HEROIN_DELIVERY:
             return (GamerResult.heroin_total);
             break;
         case DG_EXTERNS::SHRUB_DELIVERY:
             return (GamerResult.shrub_total);
             break;
         case DG_EXTERNS::POPONKA_DELIVERY:
             return (GamerResult.poponka_total);
             break;
         case DG_EXTERNS::TOXICK_DELIVERY:
             return (GamerResult.toxick_total);
             break;
         case DG_EXTERNS::NYMBOS_BONUS:
             return (GamerResult.nymbos_total >= GamerResult.nymbos_bonus*20);
             break;
         case DG_EXTERNS::PHLEGMA_BONUS:
             return (GamerResult.phlegma_total  >= GamerResult.phlegma_bonus*20);
             break;
         case DG_EXTERNS::HEROIN_BONUS:
             return (GamerResult.heroin_total  >= GamerResult.heroin_bonus*20);
             break;
         case DG_EXTERNS::SHRUB_BONUS:
             return (GamerResult.shrub_total >=  GamerResult.shrub_bonus*20);
             break;
         case DG_EXTERNS::POPONKA_BONUS:
             return (GamerResult.poponka_total >= GamerResult.poponka_bonus*20);
             break;
         case DG_EXTERNS::TOXICK_BONUS:
             return (GamerResult.toxick_total  >= GamerResult.toxick_bonus*20);
             break;
         case DG_EXTERNS::CYCLE:
             return (uvsCurrentCycle);
             break;
         case DG_EXTERNS::BEEBS:
             return (aciGetCurCredits());
             break;
         case DG_EXTERNS::WEEZYK_ASSIGNMENT:
             return (GamerResult.get_weezyk);
             break;
         case DG_EXTERNS::INV_BAD_LARVA:
             return (GamerResult.dolly == UVS_DOLLY_TYPE::ALIEN);
             break;
         case DG_EXTERNS::LARVA_CYCLE:
             return (GamerResult.dolly_cycle);
             break;
         case DG_EXTERNS::INV_GOOD_LARVA:
             return (GamerResult.dolly == UVS_DOLLY_TYPE::OWN);
             break;
         case DG_EXTERNS::LUCK:
             if (GamerResult.luck + GamerResult.add_luck > 100)
                 return 100;
             if (GamerResult.luck + GamerResult.add_luck < 0)
                 return 0;
             return (GamerResult.luck + GamerResult.add_luck);
             break;
         case DG_EXTERNS::INV_MESSIAH:
             if (uvsKronActive)
                 return CheckThreallMessiah();
             else
                 return (GamerResult.mechanic_messiah);
             break;
         case DG_EXTERNS::INV_ELEEPOD:
             return (GamerResult.eleepod);
             break;
         case DG_EXTERNS::INV_BEEBOORAT:
             return (GamerResult.beeboorat);
             break;
         case DG_EXTERNS::INV_ZEEX:
             return (GamerResult.zeex);
             break;
         case DG_EXTERNS::INV_LEEPURINGA:
             return (GamerResult.leepuringa);
             break;
         case DG_EXTERNS::INV_PALOCHKA:
             return (GamerResult.palochka);
             break;
         case DG_EXTERNS::INV_BOORAWCHICK:
             return (GamerResult.boorawchick);
             break;
         case DG_EXTERNS::INV_NOBOOL:
             return (GamerResult.nobool);
             break;
         case DG_EXTERNS::INV_PIPKA:
             return (GamerResult.pipka);
             break;
         case DG_EXTERNS::INV_PEREPONKA:
             return (GamerResult.pereponka);
             break;
         case DG_EXTERNS::INV_ZEEFICK:
             return (GamerResult.zeefick);
             break;
         case DG_EXTERNS::INV_PROTRACTOR:
             return (GamerResult.protractor);
             break;
         case DG_EXTERNS::INV_FUNCTION83:
             return (GamerResult.fun83);
             break;
         case DG_EXTERNS::INV_BOOTSECTOR:
             return (GamerResult.boot_sector);
             break;
         case DG_EXTERNS:: INV_PEELOT:
             return (GamerResult.peelot);
             break;
         case DG_EXTERNS::INV_SPUMMY:
             return (GamerResult.spummy);
             break;
         case DG_EXTERNS::DOMINANCE:
             if (GamerResult.dominance+GamerResult.add_dominance > 100 )
                 return 100;
             if (GamerResult.dominance+GamerResult.add_dominance < -100)
                 return -100;
             return (GamerResult.dominance+GamerResult.add_dominance);
             break;
         case DG_EXTERNS::TABUTASKS:
             return (Gamer -> GoodTabuTask());
             break;
         case DG_EXTERNS::FRESH_TABUTASKS:
             return (Gamer -> newGoodTabuTask());
             break;
         case DG_EXTERNS::WTABUTASKS:
             return (Gamer -> GoodWorldTabuTask());
             break;
         case DG_EXTERNS::CIRT_DELIVERY:
             return (Gamer -> CirtDelivery());
             break;
         case DG_EXTERNS::THIEF_LEEPURINGA:
             return (GamerResult.thief_leepuringa);
             break;
         case DG_EXTERNS::THIEF_PALOCHKA:
             return (GamerResult.thief_palochka);
             break;
         case DG_EXTERNS::THIEF_BOORAWCHICK:
             return (GamerResult.thief_boorawchick);
             break;
         case DG_EXTERNS::THIEF_NOBOOL:
             return (GamerResult.thief_nobool);
             break;
         case DG_EXTERNS::THIEF_PIPKA:
             return (GamerResult.thief_pipka);
             break;
         case DG_EXTERNS::THIEF_PEREPONKA:
             return (GamerResult.thief_pereponka);
             break;
         case DG_EXTERNS::THIEF_ZEEFICK:
             return (GamerResult.thief_zeefick);
             break;
         case DG_EXTERNS::TRUE_PASSENGER:
             return GamerResult.passagerOk;
             break;
         case DG_EXTERNS::HERE_LEEPURINGA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::LEEPURINGA, uvsTreasureInShop) ||
                     uvsReturnTreasureStatus(UVS_ITEM_TYPE::LEEPURINGA, 0));
             break;
         case DG_EXTERNS::HERE_PALOCHKA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::PALOCHKA, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::PALOCHKA, 0));
             break;
         case DG_EXTERNS::HERE_BOORAWCHICK:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::BOORAWCHICK, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::BOORAWCHICK, 0));
             break;
         case DG_EXTERNS::HERE_NOBOOL:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::NOBOOL, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::NOBOOL, 0));
             break;
         case DG_EXTERNS::HERE_PIPKA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::PIPKA, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::PIPKA, 0));
             break;
         case DG_EXTERNS::HERE_PEREPONKA:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::PEREPONKA, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::PEREPONKA, 0));
             break;
         case DG_EXTERNS::HERE_ZEEFICK:
             return (uvsReturnTreasureStatus(UVS_ITEM_TYPE::ZEEFICK, uvsTreasureInShop) ||
                 uvsReturnTreasureStatus(UVS_ITEM_TYPE::ZEEFICK, 0));
             break;
         case DG_EXTERNS::BOORAWCHICK_RETURN:
             return GamerResult.BoorawchickGoHimself;
             break;
         case DG_EXTERNS::ZIGGER_ZAGGER:
             return (uvsMechosTable[19] -> constractor == 1 || uvsMechosTable[19] -> constractor == 3);
             break;
         case DG_EXTERNS::CART:
             return (uvsMechosTable[19] -> constractor == 2 || uvsMechosTable[19] -> constractor == 3);
             break;
         case DG_EXTERNS::PUT_PUT:
             return (uvsMechosTable[20] -> constractor == 1 || uvsMechosTable[20] -> constractor == 3);
             break;
         case DG_EXTERNS::BOX:
             return (uvsMechosTable[20] -> constractor == 2 || uvsMechosTable[20] -> constractor == 3);
             break;
         case DG_EXTERNS::RATTLE:
             return (uvsMechosTable[21] -> constractor == 1 || uvsMechosTable[21] -> constractor == 3);
             break;
         case DG_EXTERNS::HEAVY_IRON:
             return (uvsMechosTable[21] -> constractor == 2 || uvsMechosTable[21] -> constractor == 3);
             break;
         case DG_EXTERNS::STAR:
             return (uvsMechosTable[22] -> constractor == 1 || uvsMechosTable[22] -> constractor == 3);
             break;
         case DG_EXTERNS::WHIZZER:
             return (uvsMechosTable[22] -> constractor == 2 || uvsMechosTable[22] -> constractor == 3);
             break;
         case DG_EXTERNS::HUSKER:
             return (uvsMechosTable[23] -> constractor == 1 || uvsMechosTable[23] -> constractor == 3);
             break;
         case DG_EXTERNS::COGGED_WIDGET:
             return (uvsMechosTable[23] -> constractor == 2 || uvsMechosTable[23] -> constractor == 3);
             break;
         }// end switrh
     return 0;
 }
References aciGetCurCredits(), uvsGamerResult::add_dominance, uvsGamerResult::add_luck, UVS_DOLLY_TYPE::ALIEN, uvsGamerResult::beeboorat, DG_EXTERNS::BEEBS, UVS_ITEM_TYPE::BOORAWCHICK, uvsGamerResult::boorawchick, DG_EXTERNS::BOORAWCHICK_RETURN, uvsGamerResult::BoorawchickGoHimself, uvsGamerResult::boot_sector, DG_EXTERNS::BOX, DG_EXTERNS::CART, CheckThreallMessiah(), uvsGamerResult::cirt_bad, DG_EXTERNS::CIRT_DELIVERY, uvsGamerResult::cirt_good, DG_EXTERNS::COGGED_WIDGET, DG_EXTERNS::CYCLE, uvsGamerResult::dead_eleech_now, uvsGamerResult::dolly, uvsGamerResult::dolly_cycle, DG_EXTERNS::DOMINANCE, uvsGamerResult::dominance, uvsGamerResult::eleech, uvsGamerResult::eleepod, DG_EXTERNS::ELR_RATING, DG_EXTERNS::ELR_RESULT, DG_EXTERNS::ELR_TOTAL, DG_EXTERNS::FRESH_TABUTASKS, uvsGamerResult::fun83, uvsGamerResult::game_elr_result, uvsGamerResult::game_ker_result, uvsGamerResult::game_pip_result, uvsGamerResult::game_result, uvsGamerResult::game_total, uvsGamerResult::game_zyk_result, Gamer, GamerResult, uvsGamerResult::get_weezyk, DG_EXTERNS::HEAVY_IRON, DG_EXTERNS::HERE_BOORAWCHICK, DG_EXTERNS::HERE_LEEPURINGA, DG_EXTERNS::HERE_NOBOOL, DG_EXTERNS::HERE_PALOCHKA, DG_EXTERNS::HERE_PEREPONKA, DG_EXTERNS::HERE_PIPKA, DG_EXTERNS::HERE_ZEEFICK, uvsGamerResult::heroin, DG_EXTERNS::HEROIN_BONUS, uvsGamerResult::heroin_bonus, DG_EXTERNS::HEROIN_DELIVERY, uvsGamerResult::heroin_total, DG_EXTERNS::HUSKER, DG_EXTERNS::INV_BAD_CIRT, DG_EXTERNS::INV_BAD_LARVA, DG_EXTERNS::INV_BEEBOORAT, DG_EXTERNS::INV_BOORAWCHICK, DG_EXTERNS::INV_BOOTSECTOR, DG_EXTERNS::INV_DEAD_ELEECH, DG_EXTERNS::INV_ELEECH, DG_EXTERNS::INV_ELEEPOD, DG_EXTERNS::INV_FUNCTION83, DG_EXTERNS::INV_GOOD_CIRT, DG_EXTERNS::INV_GOOD_LARVA, DG_EXTERNS::INV_HEROIN, DG_EXTERNS::INV_KERNOBOO, DG_EXTERNS::INV_LEEPURINGA, DG_EXTERNS::INV_MESSIAH, DG_EXTERNS::INV_NOBOOL, DG_EXTERNS::INV_NYMBOS, DG_EXTERNS::INV_PALOCHKA, DG_EXTERNS::INV_PEELOT, DG_EXTERNS::INV_PEREPONKA, DG_EXTERNS::INV_PHLEGMA, DG_EXTERNS::INV_PIPETKA, DG_EXTERNS::INV_PIPKA, DG_EXTERNS::INV_POPONKA, DG_EXTERNS::INV_PROTRACTOR, DG_EXTERNS::INV_RUBBOX, DG_EXTERNS::INV_SHRUB, DG_EXTERNS::INV_SPUMMY, DG_EXTERNS::INV_TOXICK, DG_EXTERNS::INV_UNIQUE_POPONKA, DG_EXTERNS::INV_WEEZYK, DG_EXTERNS::INV_ZEEFICK, DG_EXTERNS::INV_ZEEX, DG_EXTERNS::KER_RATING, DG_EXTERNS::KER_RESULT, DG_EXTERNS::KER_TOTAL, uvsGamerResult::kernoboo, DG_EXTERNS::KILLED_VANGERS, DG_EXTERNS::LARVA_CYCLE, UVS_ITEM_TYPE::LEEPURINGA, uvsGamerResult::leepuringa, DG_EXTERNS::LUCK, uvsGamerResult::luck, uvsGamerResult::mechanic_messiah, DG_EXTERNS::MECHOS_CHANGED, DG_EXTERNS::MECHOS_TYPE, uvsGamerResult::mechos_type, uvsGamerResult::mechos_variant, UVS_ITEM_TYPE::NOBOOL, uvsGamerResult::nobool, uvsGamerResult::nymbos, DG_EXTERNS::NYMBOS_BONUS, uvsGamerResult::nymbos_bonus, DG_EXTERNS::NYMBOS_DELIVERY, uvsGamerResult::nymbos_total, UVS_DOLLY_TYPE::OWN, UVS_ITEM_TYPE::PALOCHKA, uvsGamerResult::palochka, uvsGamerResult::passagerOk, uvsGamerResult::peelot, UVS_ITEM_TYPE::PEREPONKA, uvsGamerResult::pereponka, uvsGamerResult::phlegma, DG_EXTERNS::PHLEGMA_BONUS, uvsGamerResult::phlegma_bonus, DG_EXTERNS::PHLEGMA_DELIVERY, uvsGamerResult::phlegma_total, DG_EXTERNS::PIP_RATING, DG_EXTERNS::PIP_RESULT, DG_EXTERNS::PIP_TOTAL, uvsGamerResult::pipetka, UVS_ITEM_TYPE::PIPKA, uvsGamerResult::pipka, uvsGamerResult::poponka, DG_EXTERNS::POPONKA_BONUS, uvsGamerResult::poponka_bonus, DG_EXTERNS::POPONKA_DELIVERY, uvsGamerResult::poponka_total, uvsGamerResult::protractor, DG_EXTERNS::PUT_PUT, DG_EXTERNS::RATTLE, uvsGamerResult::rubbox, uvsGamerResult::shrub, DG_EXTERNS::SHRUB_BONUS, uvsGamerResult::shrub_bonus, DG_EXTERNS::SHRUB_DELIVERY, uvsGamerResult::shrub_total, uvsGamerResult::spummy, DG_EXTERNS::STAR, DG_EXTERNS::TABUTASKS, DG_EXTERNS::THIEF_BOORAWCHICK, uvsGamerResult::thief_boorawchick, DG_EXTERNS::THIEF_LEEPURINGA, uvsGamerResult::thief_leepuringa, DG_EXTERNS::THIEF_NOBOOL, uvsGamerResult::thief_nobool, DG_EXTERNS::THIEF_PALOCHKA, uvsGamerResult::thief_palochka, DG_EXTERNS::THIEF_PEREPONKA, uvsGamerResult::thief_pereponka, DG_EXTERNS::THIEF_PIPKA, uvsGamerResult::thief_pipka, DG_EXTERNS::THIEF_ZEEFICK, uvsGamerResult::thief_zeefick, uvsGamerResult::toxick, DG_EXTERNS::TOXICK_BONUS, uvsGamerResult::toxick_bonus, DG_EXTERNS::TOXICK_DELIVERY, uvsGamerResult::toxick_total, DG_EXTERNS::TRUE_PASSENGER, uvsGamerResult::unik_poponka, uvsCurrentCycle, uvsKronActive, uvsMechosTable, uvsReturnTreasureStatus(), uvsTreasureInShop, uvsGamerResult::vanger_kill, uvsGamerResult::weezyk, DG_EXTERNS::WEEZYK_ASSIGNMENT, DG_EXTERNS::WHIZZER, DG_EXTERNS::WTABUTASKS, UVS_ITEM_TYPE::ZEEFICK, uvsGamerResult::zeefick, uvsGamerResult::zeex, DG_EXTERNS::ZIGGER_ZAGGER, DG_EXTERNS::ZYK_RATING, DG_EXTERNS::ZYK_RESULT, and DG_EXTERNS::ZYK_TOTAL.
Referenced by dgCell::analyzeACCESS(), and dgMolecule::getVarPhrase().
uvsGetEscaveByID()
uvsEscave * uvsGetEscaveByID (int type)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     int ID;
     while(pe){
         ID = pe -> SeekID( type );
         if (ID != -1)
             return pe;
         pe = (uvsEscave*)pe -> next;
     }
     return NULL;
 }
References EscaveTail, listElem::next, NULL, and uvsEscave::SeekID().
Referenced by uvsActIntSell(), uvsCreateNetVanger(), uvsKronDeleteItem(), and uvsPassagerFromStatistic().
uvsGetLarvaWorld()
char* uvsGetLarvaWorld (int n)
{
     uvsWorld *Pworld = Gamer->Pworld;
     if (Pworld -> escTmax){
         uvsBunch *pb = Pworld -> escT[0] -> Pbunch;
         return pb -> cycleTable[n].Pdolly -> Pworld -> name;
     } else
         return NULL;
 }
References Gamer, uvsEscave::name, NULL, uvsEscave::Pbunch, uvsEscave::Pworld, and uvsVanger::Pworld.
Referenced by dgMolecule::getVarPhrase().
uvsGetNameByID()
char* uvsGetNameByID (int type, int & ID)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(pe){
         ID = pe -> SeekID( type );
         if (ID != -1)
             return pe -> name;
         pe = (uvsEscave*)pe -> next;
     }
     while(ps){
         ID = ps -> SeekID( type );
         if (ID != -1)
             return ps -> name;
         ps = (uvsSpot*)ps -> next;
     }
     return NULL;
 }
References EscaveTail, uvsEscave::name, listElem::next, NULL, uvsEscave::SeekID(), and SpotTail.
Referenced by aciGetItemEscave(), aciSendEvent2itmdsp(), uvsActIntSell(), uvsPassagerFromStatistic(), and uvsPrepareItemToDiagen().
uvsGetSpotByID()
uvsSpot * uvsGetSpotByID (int type)
{
     uvsSpot *ps = (uvsSpot*)SpotTail;
     int ID;
     while(ps){
         ID = ps -> SeekID( type );
         if (ID != -1)
             return ps;
         ps = (uvsSpot*)ps -> next;
     }
     return NULL;
 }
References listElem::next, NULL, uvsEscave::SeekID(), and SpotTail.
Referenced by uvsActIntSell(), uvsCreateNetVanger(), uvsKronDeleteItem(), and uvsPassagerFromStatistic().
uvsKillerNow()
int uvsKillerNow (void)
                       {
     uvsElement* p = ETail;
     int count  = 0;
     while(p){
         if(p -> type == UVS_OBJECT::VANGER && ((uvsVanger*)p) -> shape == UVS_VANGER_SHAPE::KILLER){
             count++;
         }
         p = p -> enext;
     }//  end while
     return count;
 }
References ETail, UVS_VANGER_SHAPE::KILLER, and UVS_OBJECT::VANGER.
Referenced by uvsVanger::goCirt(), and uvsVanger::prepare_killer().
uvsKronDeleteItem()
void uvsKronDeleteItem (int type, int param1, int param2)
{
     uvsWorld *pw = Gamer -> Pworld;
     uvsItem* pi;
     if (type == UVS_ITEM_TYPE::BOORAWCHICK){
         ((uvsItem*)WorldTable[1] -> escT[0] -> Pitem) ->param1 = uvsTreasureInWait;
     } else {
         switch(uvsItemTable[type] -> type){
         case UVS_ITEM_STATUS::MECHOS_PART:
 //          if (ConTimer.day < 10)
 //              ErrH.Abort("Its not MY");
             while ( pw == Gamer -> Pworld )
                 pw = WorldTable[RND(3)];
             pi = new uvsItem(type);
             pi -> param1 = param1;
             pi -> param2 = param2;
             pi -> link(pw -> sptT[RND(pw -> sptTmax)] -> Pshop -> Pitem);
             break;
         case UVS_ITEM_STATUS::ARTIFACT:
 //          if (ConTimer.day < 10)
 //              ErrH.Abort("Its not MY");
         case UVS_ITEM_STATUS::TREASURE:
             while ( pw == Gamer -> Pworld )
                 pw = WorldTable[RND(3)];
             if (((uvsItem*)pw -> escT[0] -> Pitem) -> type != type){
                 pi = new uvsItem(type);
                 pi -> param1 = param1;
                 pi -> param2 = param2;
                 pi -> link(pw -> escT[0] -> Pshop -> Pitem);
             } else {
                 pi = new uvsItem(type);
                 pi -> param1 = param1;
                 pi -> param2 = param2;
                 pi -> link(pw -> sptT[RND(pw -> sptTmax)] -> Pshop -> Pitem);
             }
             break;
         case UVS_ITEM_STATUS::GOODS:
             if ((type == UVS_ITEM_TYPE::TABUTASK) && ((param2 & 0xFFFF0000) == 0)){
                 TabuTable[param2 & 0x0000FFFF] -> Erase( param1,  param2);
             } else if (type == UVS_ITEM_TYPE::ELEEPOD || type == UVS_ITEM_TYPE::BEEBOORAT || type == UVS_ITEM_TYPE::ZEEX ){
                 uvsEscave *pe =  uvsGetEscaveByID(param2 & 0x0000FFFF);
                 uvsSpot *ps =  uvsGetSpotByID(param2 & 0x0000FFFF);
                 if (pe ){
                     pe -> PassagerStatistic[CurrentWorld] += 1;
                 }
                 if (ps){
                     ps -> PassagerStatistic[CurrentWorld] += 1;
                 }
             }
             break;
         }//  end switch
     }//  end if
 }
References UVS_ITEM_STATUS::ARTIFACT, UVS_ITEM_TYPE::BEEBOORAT, UVS_ITEM_TYPE::BOORAWCHICK, CurrentWorld, UVS_ITEM_TYPE::ELEEPOD, Gamer, UVS_ITEM_STATUS::GOODS, listElem::link(), UVS_ITEM_STATUS::MECHOS_PART, uvsItem::param1, uvsEscave::PassagerStatistic, uvsEscave::Pitem, uvsEscave::Pshop, uvsEscave::Pworld, RND(), TabuTable, UVS_ITEM_TYPE::TABUTASK, UVS_ITEM_STATUS::TREASURE, uvsGetEscaveByID(), uvsGetSpotByID(), uvsItemTable, uvsTreasureInWait, WorldTable, and UVS_ITEM_TYPE::ZEEX.
Referenced by ItemsDispatcher::Close(), VangerUnit::Go2World(), Item2ShopAction(), and StuffObject::Quant().
uvsLuckChange()
void uvsLuckChange (int delta)
{
     GamerResult.luck += delta;
     ShowLuckMessage(delta);
     if (GamerResult.luck < 0) GamerResult.luck = 0;
     if (GamerResult.luck > 100) GamerResult.luck = 100;
 }
References GamerResult, uvsGamerResult::luck, and ShowLuckMessage().
uvsMakeGamerFromSlave()
void uvsMakeGamerFromSlave (uvsVanger * pv)
{
     pv -> shape = UVS_VANGER_SHAPE::GAMER;
     pv -> status = UVS_VANGER_STATUS::MOVE_TO_MECHOS;
     pv -> Pworld = Gamer -> Pworld;
     Gamer -> shape = UVS_VANGER_SHAPE::GAMER_SLAVE;
     Gamer -> status = UVS_VANGER_STATUS::MOVEMENT;
     Gamer -> gIndex = pv -> gIndex;
     pv -> gIndex = 0;
     Gamer = pv;
 }
References Gamer, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, UVS_VANGER_STATUS::MOVE_TO_MECHOS, UVS_VANGER_STATUS::MOVEMENT, and uvsEscave::Pworld.
Referenced by VangerUnit::Go2Universe().
uvsMakeNewGamerInEscave()
uvsVanger* uvsMakeNewGamerInEscave (uvsEscave * pe, int what)
{
     uvsElement* p = ETail;
     uvsVanger* v;
     uvsMechos* pm;
     listElem* pl;
 //  FreeMechosList(GGamerList);
     while(p){
         if(p -> type == UVS_OBJECT::VANGER ){
             v = (uvsVanger*)p;
             if ( v -> status == UVS_VANGER_STATUS::ESCAVE_SLEEPING || v -> status == UVS_VANGER_STATUS::SPOT_SLEEPING){
                 if (what){
                     v -> locTimer = 1;
                     v -> shape = UVS_VANGER_SHAPE::GAMER;
                     v -> status = UVS_VANGER_STATUS::SHOPPING;
                     v -> Pescave = pe;
                     v -> Pspot = NULL;
                     v -> Pworld = pe -> Pworld;
                     Gamer -> shape = UVS_VANGER_SHAPE::GAMER_SLAVE;
                     Gamer -> gIndex = v -> gIndex;
                     v -> gIndex = 0;
                     Gamer = v;
                 } else
                     pe -> Pshop -> sellMechos(Gamer -> Pmechos);
                 pm = (uvsMechos*)pe -> Pshop -> Pmechos;
                 pl = pe -> Pshop -> Pmechos -> next;
                 while(pl){
                     if (uvsMechosTable[pm -> type] -> price > uvsMechosTable[((uvsMechos*)pl) -> type] -> price)
                         pm =(uvsMechos*)pl;
                     pl = pl -> next;
                 }
                 if (((listElem*)pm) == pe -> Pshop -> Pmechos ){
                     pe -> Pshop -> Pmechos = pe -> Pshop -> Pmechos -> next;
                     if (pe -> Pshop -> Pmechos)
                         pe -> Pshop -> Pmechos -> prev = pm -> prev;
                 } else {
                     if (pm -> next)
                         pm -> next -> prev = pm -> prev;
                     else
                         pe -> Pshop -> Pmechos -> prev = pm -> prev;
                     pm -> prev -> next = pm -> next;
                 }
                 pm -> type = RND(MAX_MECHOS_RAFFA) + MAX_MECHOS_MAIN;
                 Gamer -> Pmechos = pm;
                 if (!Gamer -> Pmechos)
                     ErrH.Abort("uvsMakeNewGamer :: dont have any mechos in shop");
 //              aciCurCredits -= uvsMechosTable[pm -> type] -> price;
 //              if (aciCurCredits < 0)
 //                  aciCurCredits = 0;
                 if (what){
 //                  aciCurCredits -= uvsMechosTable[pm -> type] -> price;
 /*                  if (!Gamer -> addItem(new uvsItem(UVS_ITEM_TYPE::SECTOR)))
                         ErrH.Abort("uvsMakeNewGamerInEscave : dont add artifact");*/
                 }
                 if (aciGetCurCredits() < 0)
                     aciUpdateCurCredits(0);
                 return Gamer;
             }//  if status
         }//  end if vanger
         p = p -> enext;
     }//  end while
     ErrH.Abort("uvsMakeNewGamer :: dont find free vanger");
     return NULL;
 }
References XErrorHandler::Abort(), aciGetCurCredits(), aciUpdateCurCredits(), ErrH, UVS_VANGER_STATUS::ESCAVE_SLEEPING, ETail, Gamer, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, MAX_MECHOS_MAIN, MAX_MECHOS_RAFFA, listElem::next, NULL, listElem::prev, uvsEscave::Pshop, uvsEscave::Pworld, RND(), UVS_VANGER_STATUS::SHOPPING, UVS_VANGER_STATUS::SPOT_SLEEPING, uvsMechosTable, and UVS_OBJECT::VANGER.
Referenced by VangerUnit::Go2Universe().
uvsMechosLoad()
void uvsMechosLoad (XStream & fout)
{
     int i;
     for( i = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR; i < MAX_MECHOS_TYPE; i++)
         fout > uvsMechosTable[i] -> constractor;
     for( i = 0; i < MAX_MECHOS_TYPE; i++){
         fout > uvsMechosTable[i] -> gamer_use;
         fout > uvsMechosTable[i] -> gamer_kill;
     }
     if (uvsLoadVersion > 0){
         for( i = 0; i < MAX_ITEM_TYPE; i++)
             fout > uvsItemTable[i] -> gamer_use;
     } else {
         for( i = 0; i < 64; i++)
             fout > uvsItemTable[i] -> gamer_use;
     }
 }
References fout, MAX_ITEM_TYPE, MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, uvsItemTable, uvsLoadVersion, and uvsMechosTable.
uvsMechosSave()
void uvsMechosSave (XStream & fin)
{
     int i;
     for( i = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR; i < MAX_MECHOS_TYPE; i++)
         fin < uvsMechosTable[i] -> constractor;
     for( i = 0; i < MAX_MECHOS_TYPE; i++){
         fin < uvsMechosTable[i] -> gamer_use;
         fin < uvsMechosTable[i] -> gamer_kill;
     }
     for( i = 0; i < MAX_ITEM_TYPE; i++)
         fin < uvsItemTable[i] -> gamer_use;
 }
References MAX_ITEM_TYPE, MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, uvsItemTable, and uvsMechosTable.
uvsMechosType_to_AciInt()
int uvsMechosType_to_AciInt (int type)
{
     int first_constr = MAX_MECHOS_TYPE - MAX_MECHOS_CONSTRACTOR;
     int _type;
     int _type_;
     if ( type >= first_constr){
          _type = type - first_constr;
          _type_ =  first_constr + (_type<<2) + uvsMechosTable[type] -> constractor;
     } else
         _type_ = type;
     return _type_;
 }
References MAX_MECHOS_CONSTRACTOR, MAX_MECHOS_TYPE, and uvsMechosTable.
Referenced by VangerUnit::ChangeVangerProcess(), VangerUnit::Go2Universe(), ObjectDestroy(), and GameObjectDispatcher::Quant().
uvsOnKillItem()
void uvsOnKillItem (void)
{
     GamerResult.luck -= 10;
     ShowLuckMessage(-10);
     if (GamerResult.luck < 0) GamerResult.luck = 0;
 }
References GamerResult, uvsGamerResult::luck, and ShowLuckMessage().
Referenced by VangerUnit::CheckOutDevice().
uvsPassagerFromStatistic()
void uvsPassagerFromStatistic (void)
{
     GamerResult.passagerOk = 0;
     char *NameTo;
     int ID;
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     while(pe){
         pe -> PassagerFrom = 0;
         pe = (uvsEscave*)pe -> next;
     }
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(ps){
         ps -> PassagerFrom = 0;
         ps = (uvsSpot*)ps -> next;
     }
     uvsItem *pi = GetItem(Gamer -> Pitem, UVS_ITEM_TYPE::ELEEPOD, 0);
     while( pi ){
         pe = uvsGetEscaveByID(pi -> param2 & 0x0000FFFF);
         ps = uvsGetSpotByID(pi -> param2 & 0x0000FFFF);
         if (ps)
             ps -> PassagerFrom++;
         else
             pe -> PassagerFrom++;
         NameTo = uvsGetNameByID(pi -> param2 >> 16, ID);
         if (!strcmp(aci_curLocationName, NameTo))
             GamerResult.passagerOk++;
         pi = GetItem( pi -> next, UVS_ITEM_TYPE::ELEEPOD, 0 );
     }
     pi = GetItem(Gamer -> Pitem, UVS_ITEM_TYPE::BEEBOORAT, 0);
     while( pi ){
         pe = uvsGetEscaveByID(pi -> param2 & 0x0000FFFF);
         ps = uvsGetSpotByID(pi -> param2 & 0x0000FFFF);
         if (ps)
             ps -> PassagerFrom++;
         else
             pe -> PassagerFrom++;
         NameTo = uvsGetNameByID(pi -> param2 >> 16, ID);
         if (!strcmp(aci_curLocationName, NameTo))
             GamerResult.passagerOk++;
         pi = GetItem( pi -> next, UVS_ITEM_TYPE::BEEBOORAT, 0 );
     }
     pi = GetItem(Gamer -> Pitem, UVS_ITEM_TYPE::ZEEX, 0);
     while( pi ){
         pe = uvsGetEscaveByID(pi -> param2 & 0x0000FFFF);
         ps = uvsGetSpotByID(pi -> param2 & 0x0000FFFF);
         if (ps)
             ps -> PassagerFrom++;
         else
             pe -> PassagerFrom++;
         NameTo = uvsGetNameByID(pi -> param2 >> 16, ID);
         if (!strcmp(aci_curLocationName, NameTo))
             GamerResult.passagerOk++;
         pi = GetItem( pi -> next, UVS_ITEM_TYPE::ZEEX, 0 );
     }
 #ifdef STAND_REPORT
     stand < "\nGood Passage " <= GamerResult.passagerOk < "\n";
 #endif
 }
References aci_curLocationName, UVS_ITEM_TYPE::BEEBOORAT, UVS_ITEM_TYPE::ELEEPOD, EscaveTail, Gamer, GamerResult, GetItem(), listElem::next, uvsEscave::PassagerFrom, uvsGamerResult::passagerOk, uvsEscave::Pitem, SpotTail, uvsGetEscaveByID(), uvsGetNameByID(), uvsGetSpotByID(), and UVS_ITEM_TYPE::ZEEX.
Referenced by uvsVanger::prepare_diagen_statistic().
uvsPoponkaIDON()
int uvsPoponkaIDON (listElem * Pitem)
{
     uvsItem *pi;
     pi = GetItem(Pitem, UVS_ITEM_TYPE::POPONKA, 0);
     while( pi ){
         if (pi ->param2 == uvsPoponkaID)
             return 1;
         pi = GetItem( pi -> next, UVS_ITEM_TYPE::POPONKA, 0 );
     }
     return 0;
 }
References GetItem(), listElem::next, uvsEscave::Pitem, UVS_ITEM_TYPE::POPONKA, and uvsPoponkaID.
Referenced by uvsVanger::prepare_diagen_statistic().
uvsPrepareItemToDiagen()
int uvsPrepareItemToDiagen (int type, int param1, int param2, int & what, int & ID, char *& NameFrom, char *& NameTo)
{
     switch(type){
     case UVS_ITEM_TYPE::POPONKA:
         what = DG_POPONKA;
         ID = param2;
         if (ID >= DG_POPONKA_MAX || ID < 0)
             ID = 0;
         NameFrom = NULL;
         NameTo = NULL;
         return 1;
         break;
     case UVS_ITEM_TYPE::TABUTASK:
         what = DG_TABUTASK;
 #ifdef _IN_FILE_
         ff <= (param2 & 0x0000FFFF) < "\n";
 #endif
         NameFrom = uvsGetNameByID(param2 & 0x0000FFFF, ID);
 #ifdef _IN_FILE_
         ff < NameFrom < "\n";
 #endif
         NameTo = NULL;
         ID = (param2 & 0x0000FFFF) - ID;
 #ifdef _IN_FILE_
         ff <= ID < "\n";
 #endif
         return 1;
         break;
     case UVS_ITEM_TYPE::ELEEPOD:
     case UVS_ITEM_TYPE::BEEBOORAT:
     case UVS_ITEM_TYPE::ZEEX:
         what = DG_PASSENGER;
         NameFrom = uvsGetNameByID(param2 & 0x0000FFFF, ID);
         NameTo = uvsGetNameByID(param2 >>16, ID);
         ID = 0;
         return 1;
         break;
     }//  end switch
     return 0;
 }
References UVS_ITEM_TYPE::BEEBOORAT, DG_PASSENGER, DG_POPONKA, DG_POPONKA_MAX, DG_TABUTASK, UVS_ITEM_TYPE::ELEEPOD, NULL, UVS_ITEM_TYPE::POPONKA, UVS_ITEM_TYPE::TABUTASK, uvsGetNameByID(), and UVS_ITEM_TYPE::ZEEX.
Referenced by aciSendEvent2itmdsp().
uvsPrepareQuant()
void uvsPrepareQuant (void)
{
     if (!ChangeWorldSkipQuant)
         GeneralSystemClose();
         Gamer -> prepare_shop(1);
         MLReset();
         vMap->release();
         //status = UVS_VANGER_STATUS::IN_SHOP;
         int lastWorld = CurrentWorld;
         CurrentWorld = -1;
         if ( GamerResult.game_result ){
             WaitEndGameInTown(lastWorld);
         }
         uvsChangeRaiting();
         CurrentWorld = lastWorld;
         if ( Gamer -> Pworld -> escTmax){
             uvsCurrentCycle = Gamer -> Pworld -> escT[0] -> Pbunch -> currentStage;
             if (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE)
                 uvsCurrentWorldUnable = 1;
             else
                 uvsCurrentWorldUnable = 0;
         } else {
             uvsCurrentCycle = 0;
             uvsCurrentWorldUnable = 0;
         }
 }
References ChangeWorldSkipQuant, CurrentWorld, uvsGamerResult::game_result, Gamer, GamerResult, GeneralSystemClose(), MLReset(), uvsEscave::Pbunch, uvsEscave::Pworld, vrtMap::release(), UVS_BUNCH_STATUS::UNABLE, uvsChangeRaiting(), uvsCurrentCycle, uvsCurrentWorldUnable, vMap, and WaitEndGameInTown().
Referenced by EscaveRTO::Init().
uvsQuant()
void uvsQuant (void)
                    {
 //  DBGCHECK;
 //_MEM_STATISTIC_("BEFOR uvsQuant -> ");
 //  uvsBunchCheck("Before Quant");
 //  uvsCheckAllItem();
     NetworkQuant();
     if (NetworkON && ConTimer.day == 1 && ConTimer.hour == 0 && ConTimer.min == 0 && ConTimer.sec == 0){
         uvsBunch* pb = (uvsBunch*)BunchTail;
         while(pb){
             sBunchCreate(pb -> id, pb -> Pescave -> Pworld -> gIndex,0,pb -> currentStage);
             pb = (uvsBunch*)pb -> next;
         }
 //      sBunchCreate(int& id,int world,int data);
         ConTimer.sec = 1;
     }
     if (!RND(1024) && NetworkON && uvsNetworkChangeWorld){
         if (Gamer -> Pworld -> gIndex < 3){
             uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
             pb -> cycleTable[pb -> currentStage].cirtQ++;
             sBunchSend(pb -> id, pb -> cycleTable[pb -> currentStage].cirtQ, pb -> currentStage);
         }//  end fi
     }//  end if
     if (!RND(1024) && !NetworkON && (Gamer -> status == UVS_VANGER_STATUS::IN_SHOP)){
         if (Gamer -> Pworld -> gIndex < 3){
             uvsBunch *pb = Gamer -> Pworld -> escT[0] -> Pbunch;
             pb -> cycleTable[pb -> currentStage].cirtQ++;
         }//  end fi
     }//  end if
     uvsQuantFlag ^= 1;
     if (uvsQuantFlag &&  Gamer -> status == UVS_VANGER_STATUS::IN_SHOP) return;
     ConTimer.Quant();
     uvsElement* p;
     if(NetworkON) {
         Gamer -> Quant();
         listElem* l = BunchTail;
         while(l){
             ((uvsBunch*)l) -> Quant();
             l = l -> next;
         }
         //znfo HERE CALLED DOLLY QUANT in network game
         p = ETail;
         while(p){
             switch (p->type) {
             case UVS_OBJECT::DOLLY:
             //case UVS_OBJECT::VANGER:
             //case UVS_OBJECT::FLY_FARMER:
                 p->Quant();
             }
             p = p->enext;
         }
         return;
     }
     c_All_Number = c_S_Number = c_R_Number = c_A_Number = 0;
     for(int i = 0;i < EMU_MAX;i++){
         p = ETail;
         while(p){
             p -> emuQuant();
             p = p -> enext;
             }
         }
     p = ETail;
     while(p){
         p -> Quant();
         p = p -> enext;
         }
     listElem* l = BunchTail;
     while(l){
         ((uvsBunch*)l) -> Quant();
         l = l -> next;
         }
     l = WorldTail;
     while(l){
         ((uvsWorld*)l) -> Quant();
         l = l -> next;
         }
     uvsElement*& ip = deleteETail;
     while(ip){
         p = ip;
         ip = ip -> eprev;
         delete ((uvsVanger*)p);
         }
 //  uvsBunchCheck("After Quant");
 //  DBGCHECK;
 //_MEM_STATISTIC_("AFTER uvsQuant -> ");
 }
References ConTimer, uvsContimer::day, uvsContimer::hour, uvsContimer::min, NetworkON, NetworkQuant(), and uvsContimer::sec.
Referenced by iGameMap::draw(), WaitEndGameInTown(), and WaitGameInTown().
uvsRestoreTabuTask()
void uvsRestoreTabuTask (void)
{
     int i;
     for( i = 0; i < MAX_TABUTASK; i++){
         if ( TabuTable[i] -> status == UVS_TABUTASK_STATUS::SLEEP)
             TabuTable[i] -> status = 0;
     }//  end for
 }
References MAX_TABUTASK, UVS_TABUTASK_STATUS::SLEEP, and TabuTable.
uvsRestoreVanger()
void uvsRestoreVanger (void)
{
 #ifdef _ROAD_
     uvsElement* p = ETail;
     uvsVanger* v;
     v = Gamer;
     if (!NetworkON) {
         if( v -> Pescave) {
             addVanger(v,v->Pescave, 1);
         } else {
             addVanger(v,v->Pspot, 1);
         }
     } else {
         if( v -> Pescave ){
             int x, y;
             NetworkGetStart(v -> Pescave -> name, x, y);
             addVanger(v,x,y, 1);
         }else{
             int x, y;
             NetworkGetStart(v -> Pspot -> name, x, y);
             addVanger(v,x, y, 1);
         }
     }
     while(p){
         if(p -> type == UVS_OBJECT::VANGER ){
             v = (uvsVanger*)p;
             if ( v -> shape != UVS_VANGER_SHAPE::GAMER ){
                 if(v -> Pworld -> gIndex == CurrentWorld && (v -> status == UVS_VANGER_STATUS::MOVEMENT
                         || v -> status == UVS_VANGER_STATUS::FREE_MOVEMENT
                         || v -> status == UVS_VANGER_STATUS::AIM_HANDLE
                         || v -> status == UVS_VANGER_STATUS::RACE_HUNTER
                         || v -> status == UVS_VANGER_STATUS::GATHERING
                         || v -> status == UVS_VANGER_STATUS::WAIT_GAMER
                         || v -> status == UVS_VANGER_STATUS::RACE)){
                     if ( v -> Pmechos -> color < 3 &&
                         WorldTable[v -> Pmechos -> color] -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE &&
                         v -> shape != UVS_VANGER_SHAPE::GAMER_SLAVE){
                             v -> Pmechos -> color = 3;
                             if(v -> shape == UVS_VANGER_SHAPE::BUNCH_SLAVE)
                                 v -> shape = UVS_VANGER_SHAPE::RANGER;
                     }
                     addVanger(v,v -> pos_x,v -> pos_y);
                 }
             }
         }
         p = p -> enext;
     }
     StartWTRACK();
 #endif
 }
References addVanger(), UVS_VANGER_STATUS::AIM_HANDLE, UVS_VANGER_SHAPE::BUNCH_SLAVE, CurrentWorld, ETail, UVS_VANGER_STATUS::FREE_MOVEMENT, Gamer, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, UVS_VANGER_STATUS::GATHERING, UVS_VANGER_STATUS::MOVEMENT, NetworkGetStart(), NetworkON, uvsVanger::Pescave, uvsVanger::Pspot, UVS_VANGER_STATUS::RACE, UVS_VANGER_STATUS::RACE_HUNTER, UVS_VANGER_SHAPE::RANGER, StartWTRACK(), UVS_BUNCH_STATUS::UNABLE, UVS_OBJECT::VANGER, UVS_VANGER_STATUS::WAIT_GAMER, and WorldTable.
Referenced by LoadingRTO2::Init(), and uvsCloseQuant().
uvsReturnTreasureStatus()
int uvsReturnTreasureStatus (int Type, int TreasureStatus = uvsTreasureInGamer)
{
     uvsEscave *pe = (uvsEscave*)EscaveTail;
     while(pe){
         if ( ((uvsItem*)pe -> Pitem) -> type == Type && ((uvsItem*)pe -> Pitem) -> param1 == TreasureStatus)
             return 1;
         pe = (uvsEscave*)pe -> next;
     }
     uvsSpot *ps = (uvsSpot*)SpotTail;
     while(ps){
         if ( ps -> Pitem && ((uvsItem*)ps -> Pitem) -> type == Type && ((uvsItem*)ps -> Pitem) -> param1 == TreasureStatus)
             return 1;
         ps = (uvsSpot*)ps -> next;
     }
     return 0;
 }
References EscaveTail, listElem::next, uvsEscave::Pitem, and SpotTail.
Referenced by uvsVanger::prepare_diagen_statistic(), and uvsgetDGdata().
uvsReturnWorldGamerVisit()
int uvsReturnWorldGamerVisit (int where)
{
     if(where < 0 || where > 9) ErrH.Abort("uvsReturnWorldGamerVisit : Bad world");
     return WorldTable[where] -> GamerVisit;
 }
References XErrorHandler::Abort(), ErrH, uvsEscave::GamerVisit, and WorldTable.
Referenced by aciWorldExploredInfo().
uvsSecretON()
int uvsSecretON (void)
                      {
     int i, j;
     for(i = 0; i < 3; i++)
         for(j = 3; j < 10; j++)
             if (aciWorldLinkExist(i,j,0)) return 1;
     return 0;
 }
References aciWorldLinkExist().
Referenced by uvsTabuTaskType::is_able().
uvsSetItemType()
int uvsSetItemType (int type, int param1, int param2)
{
     if ( type == -1 ) return -1;
     if (type >= MAX_ITEM_TYPE)
         ErrH.Abort("uvsSetItemType :: type >= MAX_ITEM_TYPE");
     int i = uvsItemTable[type] -> SteelerTypeEmpty;
     if (type  == UVS_ITEM_TYPE::TABUTASK){
         if (param2 & ((int)(UVS_TABUTASK_STATUS::GOOD)<<16))
             return TABUTASK_GOOD;
         if (param2 & ((int)(UVS_TABUTASK_STATUS::BAD)<<16))
             return TABUTASK_BAD;
     }
     if( (param1 || param2) && (uvsItemTable[type] -> type != UVS_ITEM_STATUS::GOODS))
         i = uvsItemTable[type] -> SteelerTypeFull;
     return i;
 }
References XErrorHandler::Abort(), UVS_TABUTASK_STATUS::BAD, ErrH, UVS_TABUTASK_STATUS::GOOD, UVS_ITEM_STATUS::GOODS, MAX_ITEM_TYPE, UVS_ITEM_TYPE::TABUTASK, TABUTASK_BAD, TABUTASK_GOOD, and uvsItemTable.
Referenced by aciSendEvent2itmdsp(), uvsBunch::begin_race(), ChangeItemData(), ChangeTabutaskItem(), ChargeDevice(), VangerUnit::CheckOutDevice(), ItemsDispatcher::Close(), StuffObject::CreateDevice(), StuffObject::CreateStuff(), GunDevice::DeviceIn(), GunDevice::DeviceQuant(), VangerUnit::DischargeItem(), uvsBunch::end_harvest(), uvsBunch::end_race(), ItemsDispatcher::LarvaHilator(), StuffObject::Quant(), GunDevice::Quant(), VangerUnit::ResolveHandlerFind(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), uvsapiDestroyItem(), and uvsChangeGoodsInList().
uvsSetTownName() [1/2]
void uvsSetTownName (char *)
uvsSetTownName() [2/2]
void uvsSetTownName (const char * _name_)
{
     uvsTownName = _name_;
 }
References uvsTownName.
uvsTabuComplete()
void uvsTabuComplete (int i)
{
     uvsChangeTabuTask(i, UVS_TABUTASK_STATUS::GOOD);
     uvsChangeTownTabuTask(i);
 }
References UVS_TABUTASK_STATUS::GOOD, uvsChangeTabuTask(), and uvsChangeTownTabuTask().
uvsTabuCreate()
void uvsTabuCreate (uvsActInt * pa, int num)
{
     int TabuTaskID;
     if (Gamer -> Pescave)
         TabuTaskID = Gamer -> Pescave -> TabuTaskID + num - 1;
     else
         TabuTaskID = Gamer -> Pspot -> TabuTaskID + num -1;
     pa -> param1 = Gamer -> Pworld -> gIndex<<16;
     pa -> param2 = TabuTaskID;
     pa -> price = 1;
     pa -> sell_price = 1;
 }
References Gamer, uvsEscave::Pworld, and uvsEscave::TabuTaskID.
uvsTagetID()
int uvsTagetID (char * s)
{
     int i;
     for(i = 0; i < UVS_TARGET::NONE; i++) if (!strcmp(s, PrmTargetName[i])) return i;
     ErrH.Abort("uvsTabuTask:: Bad Target");
     return -1;
 }
References UVS_TARGET::NONE.
uvsTagetWorkID()
int uvsTagetWorkID (char * s)
{
     int i;
     for(i = 0; i <= UVS_TABUTASK_WORK::NONE; i++) if (!strcmp(s, PrmTargetWorkName[i])) return i;
     ErrH.Abort("uvsTabuTask:: Bad Work");
     return -1;
 }
References UVS_TABUTASK_WORK::NONE.
uvsWorldReload()
void uvsWorldReload (int newW)
{
 #ifdef _ROAD_
     uvsElement* p = ETail;
     uvsVanger* v;
     while(p){
         if(p -> type == UVS_OBJECT::VANGER && ((uvsVanger*)p) -> shape != UVS_VANGER_SHAPE::GAMER){
             v = (uvsVanger*)p;
             if(v -> Pworld -> gIndex == newW && (v -> status == UVS_VANGER_STATUS::MOVEMENT
                 || v -> status == UVS_VANGER_STATUS::FREE_MOVEMENT
                 || v -> status == UVS_VANGER_STATUS::AIM_HANDLE
                 || v -> status == UVS_VANGER_STATUS::RACE_HUNTER
                 || v -> status == UVS_VANGER_STATUS::GATHERING
                 || v -> status == UVS_VANGER_STATUS::WAIT_GAMER
                 || v -> status == UVS_VANGER_STATUS::RACE)){
                 if ( v -> Pmechos -> color < 3 &&
                     WorldTable[v -> Pmechos -> color] -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE &&
                     v -> shape != UVS_VANGER_SHAPE::GAMER_SLAVE){
                         v -> Pmechos -> color = 3;
                         if(v -> shape == UVS_VANGER_SHAPE::BUNCH_SLAVE)
                             v -> shape = UVS_VANGER_SHAPE::RANGER;
                 }
                 addVanger(v,v -> pos_x,v -> pos_y);
             }
         }
         p = p -> enext;
     }
     CurrentWorld = newW;
     if (WorldTable[CurrentWorld]-> escTmax){
         uvsCurrentCycle = WorldTable[CurrentWorld] -> escT[0] -> Pbunch -> currentStage;
          if (Gamer -> Pworld -> escT[0] -> Pbunch -> status == UVS_BUNCH_STATUS::UNABLE)
             uvsCurrentWorldUnable = 1;
         else
             uvsCurrentWorldUnable = 0;
     } else {
         uvsCurrentCycle = 0;
         uvsCurrentWorldUnable = 0;
     }
     if (NetworkON && WorldTable[CurrentWorld]-> escTmax){
         uvsBunch* pb = WorldTable[CurrentWorld]-> escT[0] -> Pbunch;
         pb -> cycleTable[pb -> currentStage].cirtQ = pb -> cycleTable[pb -> currentStage].cirtMAX;
         sBunchSend(pb -> id, pb -> cycleTable[pb -> currentStage].cirtQ, pb -> currentStage);
     }
     StartWTRACK();
 #endif
 }
References addVanger(), UVS_VANGER_STATUS::AIM_HANDLE, UVS_VANGER_SHAPE::BUNCH_SLAVE, CurrentWorld, ETail, UVS_VANGER_STATUS::FREE_MOVEMENT, Gamer, UVS_VANGER_SHAPE::GAMER, UVS_VANGER_SHAPE::GAMER_SLAVE, UVS_VANGER_STATUS::GATHERING, UVS_VANGER_STATUS::MOVEMENT, NetworkON, UVS_VANGER_STATUS::RACE, UVS_VANGER_STATUS::RACE_HUNTER, UVS_VANGER_SHAPE::RANGER, sBunchSend(), StartWTRACK(), UVS_BUNCH_STATUS::UNABLE, uvsCurrentCycle, uvsCurrentWorldUnable, UVS_OBJECT::VANGER, UVS_VANGER_STATUS::WAIT_GAMER, and WorldTable.
Referenced by uvsVanger::makeJump(), and uvsVanger::Quant().
uvsWorldToCross()
int uvsWorldToCross (int fromWID, int toWID)
{
     uvsWorld* fromW = WorldTable[fromWID];
     uvsWorld* toW = WorldTable[toWID];
     uvsWorld* nextW,*tmpW = NULL;
     uvsWorld *lastfromW = NULL, *lasttoW = NULL;
     uvsPassage* pp;
     int i = 0;
     int _i_ = 0;
     if ( fromWID == 7 || toWID == 7)
         return -1;
     if (fromW -> gIndex >= MAIN_WORLD_MAX ) {
         lastfromW = fromW;
         fromW = fromW -> pssT[0] -> Poutput;
         _i_ += 1;
     }
     if (toW -> gIndex >= MAIN_WORLD_MAX ) {
         lasttoW = toW;
         toW = toW -> pssT[0] -> Poutput;
         _i_ += 1;
     }
     unsigned int linkage = ChainMap[toW -> gIndex + fromW -> gIndex*MAIN_WORLD_MAX],mI;
     if ( fromW == toW ) return _i_;
     for(i = 0; i < 8; i++, _i_++){
         mI = (linkage & (0x0000000F << 4*i)) >> 4*i;
         nextW = getWorld(mI);
         if(!nextW)  nextW = toW;
         pp = fromW -> getPassage(nextW);
         if ( !pp ) ErrH.Abort( "buildWay:: not passage");
         fromW = nextW;
         if ( fromW == toW ) break;
     }
     _i_++;
     return (_i_);
 }
References MAIN_WORLD_MAX, NULL, and WorldTable.
WaitEndGameInTown()
void WaitEndGameInTown (int cWorld)
{
     int ww;
     if ( (ww = WorldTable[cWorld] -> escT[0] -> Pbunch -> game_wait_end()) != -1 ){
         if (ww != WorldTable[ cWorld ] -> escT[0] -> Pbunch -> currentStage){
             while( WorldTable[ cWorld ] -> escT[0] -> Pbunch -> currentStage != ww )
                 uvsQuant();
         } else {
             uvsEndHarvest = 0;
             while( !uvsEndHarvest )
                 uvsQuant();
         }
     }
 }
References uvsEscave::Pbunch, uvsEndHarvest, uvsQuant(), and WorldTable.
Referenced by uvsPrepareQuant().
WaitGameInTown()
void WaitGameInTown (int cWorld)
{
     int ww;
     if ( (ww = WorldTable[cWorld] -> escT[0] -> Pbunch -> game_exit()) != -1 ){
         uvsGamerWaitGame = 1;
         if (ww != WorldTable[ cWorld ] -> escT[0] -> Pbunch -> currentStage){
             while( WorldTable[ cWorld ] -> escT[0] -> Pbunch -> currentStage != ww )
                 uvsQuant();
         } else {
             uvsEndHarvest = 0;
             while( !uvsEndHarvest )
                 uvsQuant();
         }
     }
 }
References uvsEscave::Pbunch, uvsEndHarvest, uvsGamerWaitGame, uvsQuant(), and WorldTable.
Referenced by aciOfferEleech(), and aciWaitNextPeriod().
Variable Documentation
actIntPal
uchar* actIntPal extern
Referenced by actIntDispatcher::flush(), actIntDispatcher::i_init(), actIntDispatcher::pal_flush(), and uvsCloseQuant().
BIOS_NAMES
const char* BIOS_NAMES[BIOS_MAX]
Initial value:
= {
    "Eleepods", "Beeboorats", "Zeexes"
    }
Referenced by uvsBunch::uvsBunch().
c_A_Number
int c_A_Number
Referenced by uvsVanger::Quant(), and ScreenQuant().
c_All_Number
int c_All_Number
Referenced by uvsVanger::Quant(), and ScreenQuant().
c_R_Number
int c_R_Number
Referenced by uvsVanger::Quant(), and ScreenQuant().
c_S_Number
int c_S_Number
Referenced by uvsVanger::Quant(), and ScreenQuant().
ChangeArmor
int ChangeArmor extern
Referenced by VangerUnit::AddEscave(), VangerUnit::AddFree(), VangerUnit::AddPassage(), VangerUnit::AddSpot(), GeneralSystemInit(), GeneralSystemLoad(), GeneralSystemSave(), uvsVanger::get_shop(), uvsVanger::prepare_list_for_ActInt(), and VangerUnit::SensorQuant().
ChangeWorldSkipQuant
int ChangeWorldSkipQuant extern
Referenced by ChangeWorld(), iGameMap::draw(), GeneralSystemOpen(), and uvsPrepareQuant().
ConTimer
uvsContimer ConTimer
Referenced by uvsVanger::add_to_race(), uvsBunch::begin_harvest(), uvsBunch::begin_race(), uvsBunch::bring_harvest_GOODS(), uvsBunch::bring_race_GOODS(), ItemsDispatcher::Close(), StuffObject::CreateStuff(), StuffObject::DeviceOut(), iGameMap::draw(), uvsBunch::end_harvest(), uvsBunch::end_race(), uvsVanger::get_shop(), uvsVanger::harvest_result(), StuffObject::ImpulseAction(), uvsVanger::makeJump(), ActionDispatcher::PromptQuant(), StuffObject::Quant(), uvsBunch::Quant(), uvsVanger::Quant(), ScreenQuant(), uvsCatchDolly(), uvsCheckKronIventTabuTask(), uvsFreeDolly(), and uvsQuant().
CurrentWorld
int CurrentWorld extern
Referenced by uvsBunch::begin_harvest(), uvsVanger::emuQuant(), FreeFarmer(), uvsVanger::gatherCirt(), uvsVanger::get_shop(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsBunch::Quant(), uvsWorld::Quant(), uvsFlyFarmer::Quant(), uvsDolly::Quant(), thief_on_world(), uvsCheckVangerTabuTask(), uvsCloseQuant(), uvsCreateNetVanger(), uvsFreeDolly(), uvsKronDeleteItem(), uvsPrepareQuant(), uvsRestoreVanger(), uvsWorld::uvsWorld(), and uvsWorldReload().
cVngNumber
int cVngNumber
Dead
int Dead extern
Referenced by uvsVanger::destroy(), and MainMenuRTO::Init().
deleteETail
uvsElement* deleteETail = NULL
dgAbortStatus
int dgAbortStatus extern
Referenced by uvsVanger::prepare_list_for_ActInt(), and DiagenDispatcher::startSession().
DollyTail
listElem* DollyTail = NULL
Referenced by VangerUnit::CalcAiFactor(), uvsVanger::gatherCirt(), uvsWorld::generateDolly(), getObjectPosition(), uvsFreeDolly(), and uvsVanger::uvsVanger().
ELEECH
const int ELEECH[5] = { 2000, 1000, 300, 100, 50}
EscaveTail
listElem* EscaveTail = NULL
Referenced by uvsVanger::get_shop(), uvsItem::GetCoef(), GetEscaveDist(), getPassangerFrom(), uvsVanger::go_from_escave(), uvsVanger::go_from_spot(), uvsEscave::link_good(), uvsSpot::link_good(), EnterCenter::Open(), CompasObject::Open(), uvsBunch::uvsBunch(), uvsChangeTownTabuTask(), uvsGetEscaveByID(), uvsGetNameByID(), uvsPassagerFromStatistic(), uvsReturnTreasureStatus(), uvsTabuTaskType::uvsTabuTaskType(), and uvsVanger::uvsVanger().
ETail
uvsElement* ETail = NULL
Referenced by uvsBunch::addGOODS_any(), uvsBunch::begin_race(), uvsBunch::end_harvest(), uvsBunch::end_race(), FindFreeVanger(), uvsFlyFarmer::GrowCorn(), uvsWorld::remove_target(), ScreenQuant(), thief_on_world(), uniVangDelete(), uniVangLoad(), uvsVanger::UpdateAllTarget(), uvsCatchDolly(), uvsDolly::uvsDolly(), uvsKillerNow(), uvsMakeNewGamerInEscave(), uvsRestoreVanger(), and uvsWorldReload().
GamePoint
int GamePoint
GameQuantReturnValue
int GameQuantReturnValue extern
Referenced by uvsVanger::destroy(), uvsVanger::get_shop(), GameQuantRTO::Quant(), and uvsVanger::Quant().
Gamer
uvsVanger* Gamer
Referenced by _FirstShopPrepare(), uvsTabuTaskType::activateDOLLY(), uvsBunch::begin_race(), FindFreeVanger(), FinishFirstShopPrepare(), FirstShopPrepare(), uvsShop::get_list_from_ActInt(), GetEscaveDist(), getPreviousCycle(), uvsVanger::go_to_GAMER(), uvsTabuTaskType::is_able(), isCycleExist(), uvsVanger::makeJump(), uvsBunch::nextCycle(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsBunch::Quant(), uvsVanger::Quant(), uvsActIntSellMechos(), uvsBunchCheck(), uvsChangeCycle(), uvsChangeGoodsInList(), uvsChangeTabuTask(), uvsCheckKronIventTabuTask(), uvsCloseQuant(), uvsGameRaceFinish(), uvsGameRaceNumber(), uvsgetDGdata(), uvsGetLarvaWorld(), uvsKronDeleteItem(), uvsMakeGamerFromSlave(), uvsMakeNewGamerInEscave(), uvsPassagerFromStatistic(), uvsPrepareQuant(), uvsRestoreVanger(), uvsTabuCreate(), and uvsWorldReload().
GamerResult
uvsGamerResult GamerResult
Referenced by uvsVanger::_checkDolly_(), uvsVanger::_sellCirt_(), uvsBunch::begin_race(), VangerUnit::BulletCollision(), uvsWorld::ChangeTabuTaskInList(), uvsTabuTaskType::checkCycleEvent(), uvsVanger::checkDolly(), ActionDispatcher::CreateActive(), VangerUnit::Destroy(), VangerUnit::DestroyCollision(), uvsBunch::end_harvest(), uvsBunch::end_race(), uvsTabuTaskType::Erase(), GeneralSystemOpen(), uvsVanger::get_shop(), uvsVanger::harvest_result(), uvsVanger::homeArrival(), uvsTabuTaskType::is_able(), uvsVanger::KillStatic(), uvsVanger::makeJump(), uvsVanger::prepare_diagen_statistic(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), ActionDispatcher::PromptQuant(), uvsVanger::Quant(), uvsVanger::sellCirt(), VangerUnit::SensorQuant(), uvsVanger::spotArrival(), uvsVanger::start_race(), uvsWorld::updateResource(), uvsActIntSell(), uvsActIntSellMechos(), uvsBoorawchickZero(), uvsChangeDominance(), uvsChangeLuck(), uvsChangeRaiting(), uvsChangeTabuTask(), uvsDomChangeFromItem(), uvsFreeDolly(), uvsgetDGdata(), uvsLuckChange(), uvsOnKillItem(), uvsPassagerFromStatistic(), and uvsPrepareQuant().
GCharItem
uvsActInt* GCharItem = NULL
Referenced by aciFreeUVS(), aciGetEleech(), acsLoadData(), uvsBunch::begin_race(), and uvsBunch::end_race().
GeneralMapReload
int GeneralMapReload = 0
Referenced by addVanger(), ChangeVanger(), GeneralSystemInit(), GeneralSystemLoad(), and uvsCloseQuant().
GeneralSystemSkip
int GeneralSystemSkip extern
Referenced by iGameMap::draw(), FreeAll(), GeneralSystemClose(), GeneralSystemFree(), GeneralSystemInit(), GeneralSystemOpen(), GeneralTableFree(), GeneralTableInit(), GeneralTableOpen(), and uvsCloseQuant().
GGamer
uvsActInt* GGamer = NULL
Referenced by uvsVanger::_sellCirt_(), aciAddRubox(), aciFreeUVS(), aciGetGamerItem(), aciGetRubox(), aciSell_Item(), acsLoadData(), FirstShopPrepare(), uvsVanger::get_shop(), uvsVanger::harvest_result(), uvsVanger::race_result(), uvsVanger::sellCirt(), uvsChangeGoodsInList(), uvsChangeTabuTask(), and uvsDeleteItem().
GGamerMechos
uvsActInt* GGamerMechos
Referenced by aciChange2Raffa(), aciFreeUVS(), aciInitCurMatrixPtr(), acsLoadData(), FirstShopPrepare(), uvsVanger::get_shop(), and actIntDispatcher::i_init().
GItem
uvsActInt* GItem
Referenced by aciAddTabutask(), aciFreeUVS(), aciGetShopItem(), aciRemoveUvsItem(), aciSell_Item(), acsLoadData(), FirstShopPrepare(), and uvsVanger::get_shop().
GMechos
uvsActInt* GMechos
Referenced by aciChange2Raffa(), aciFreeUVS(), aciGetMechos(), aciInitEvLineID(), aciInitMechosInfo(), aciInitShopItems(), acsLoadData(), FirstShopPrepare(), and uvsVanger::get_shop().
GTreasureItem
uvsActInt* GTreasureItem = NULL
Referenced by aciFreeUVS(), aciPutTreasureItem(), aciStealItem(), acsLoadData(), and uvsShop::prepare_list_for_ActInt().
KERNOBOO
const int KERNOBOO[3] = { 3000, 1000, 300}
lastMechos
int lastMechos
Referenced by FinishFirstShopPrepare(), and uvsVanger::get_shop().
light_modulation
int light_modulation extern
Referenced by uvsCloseQuant().
MAX_ITEM_TYPE
int MAX_ITEM_TYPE = 0
Referenced by ActInt_to_Item(), uvsBunch::begin_race(), GetItem_as_name(), ItemsDispatcher::Init(), uvsEscave::ItemCoef(), uvsSpot::ItemCoef(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsVanger::race_result(), uvsShop::save(), uniVangDelete(), uvsMechosLoad(), uvsMechosSave(), uvsSetItemType(), and uvsShop::uvsShop().
MAX_MECHOS_CONSTRACTOR
int MAX_MECHOS_CONSTRACTOR = 0
Referenced by uvsShop::get_list_from_ActInt(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsShop::sellMechos(), uvsActIntSellMechos(), uvsMechosLoad(), uvsMechosSave(), and uvsMechosType_to_AciInt().
MAX_MECHOS_MAIN
int MAX_MECHOS_MAIN = 0
Referenced by uvsShop::prepare_list_for_ActInt(), uvsEscave::QuantChange(), uvsMechos::sort(), and uvsMakeNewGamerInEscave().
MAX_MECHOS_RAFFA
int MAX_MECHOS_RAFFA = 0
Referenced by uvsShop::prepare_list_for_ActInt(), and uvsMakeNewGamerInEscave().
MAX_MECHOS_TYPE
int MAX_MECHOS_TYPE = 0
Referenced by uvsShop::get_list_from_ActInt(), GetMechos_as_name(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsShop::sellMechos(), uniVangDelete(), uvsActIntSellMechos(), uvsMechosLoad(), uvsMechosSave(), and uvsMechosType_to_AciInt().
MAX_PART_MACHOS
int MAX_PART_MACHOS = 2
MAX_TABUTASK
int MAX_TABUTASK = 0
Referenced by CreateTabutaskTarget(), uvsCheckItemOnTabuTask(), uvsCheckKronIventTabuTask(), uvsCheckVangerTabuTask(), and uvsRestoreTabuTask().
NetRnd
NetRndType NetRnd extern
Referenced by HordeList::Init(), HordeSourceList::Init(), and FishWarriorList::Init().
NetworkON
int NetworkON extern
Referenced by uvsEscave::add_goods_to_shop(), uvsSpot::add_goods_to_shop(), uvsBunch::begin_harvest(), connect_to_server(), uvsVanger::get_shop(), uvsVanger::prepare_diagen_statistic(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsBunch::Quant(), uvsVanger::shiftOrders(), uvsQuant(), uvsRestoreVanger(), and uvsWorldReload().
palbuf
uchar* palbuf extern
Referenced by LoadingRTO2::Init(), LoadingRTO3::Init(), PalettePrepare(), and uvsCloseQuant().
palbufOrg
uchar* palbufOrg extern
Referenced by LoadingRTO2::Init(), pal_iter0(), pal_iter1(), PalettePrepare(), and uvsCloseQuant().
palbufSrc
uchar* palbufSrc extern
Referenced by GeneralTableFree(), GeneralTableInit(), GeneralTableOpen(), PalettePrepare(), VangerUnit::Quant(), PalPoint::Set(), and uvsCloseQuant().
PassageTail
listElem* PassageTail = NULL
Referenced by PassageEngine::Link(), and uvsVanger::uvsVanger().
PIPETKA
const int PIPETKA[3] = { 1500, 1000, 500 }
Quit
int Quit
RACE_WAIT
int RACE_WAIT = 300
Referenced by uvsBunch::begin_race().
SpotTail
listElem* SpotTail = NULL
Referenced by uvsVanger::get_shop(), uvsItem::GetCoef(), getPassangerFrom(), uvsVanger::go_from_escave(), uvsVanger::go_from_spot(), uvsEscave::link_good(), uvsSpot::link_good(), uvsChangeTownTabuTask(), uvsGetNameByID(), uvsGetSpotByID(), uvsPassagerFromStatistic(), uvsReturnTreasureStatus(), uvsTabuTaskType::uvsTabuTaskType(), and uvsVanger::uvsVanger().
TabuTable
uvsTabuTaskType** TabuTable
Referenced by aciSendEvent2itmdsp(), uvsWorld::ChangeTabuTaskInList(), CreateTabutaskTarget(), uvsVanger::prepare_list_for_ActInt(), uvsActIntSell(), uvsChangeGoodsInList(), uvsChangeGoodsParam(), uvsChangeTabuTask(), uvsCheckItemOnTabuTask(), uvsCheckKronIventTabuTask(), uvsCheckVangerTabuTask(), uvsKronDeleteItem(), and uvsRestoreTabuTask().
TABUTASK_BAD
const int TABUTASK_BAD = ACI_TABUTASK_FAILED
Referenced by ActInt_to_Item(), uvsItem::ActIntType(), uvsChangeGoodsInList(), uvsChangeTabuTask(), and uvsSetItemType().
TABUTASK_GOOD
const int TABUTASK_GOOD = ACI_TABUTASK_SUCCESSFUL
Referenced by ActInt_to_Item(), uvsItem::ActIntType(), uvsVanger::prepare_list_for_ActInt(), uvsActIntSell(), uvsChangeGoodsInList(), uvsChangeTabuTask(), and uvsSetItemType().
uvsBunchNumber
int uvsBunchNumber = 0
Referenced by FirstShopPrepare(), and uvsVanger::prepare_shop().
uvsCurrentCycle
int uvsCurrentCycle = 0
Referenced by aciGetCurCycle(), BunchEvent(), ChangeVanger(), VangerUnit::InitAI(), uvsVanger::makeJump(), uvsBunch::nextCycle(), ActionDispatcher::PromptChangeCycle(), ActionDispatcher::PromptQuant(), VangerUnit::Quant(), uvsBunch::Quant(), uvsVanger::Quant(), VangerUnit::ResolveGenerator(), uvsCheckVangerTabuTask(), uvsCloseQuant(), uvsgetDGdata(), uvsPrepareQuant(), and uvsWorldReload().
uvsCurrentWorldUnable
int uvsCurrentWorldUnable = 0
Referenced by aciInitMechosInfo(), actIntDispatcher::change_items(), CloseBunchPal(), GeneralTableOpen(), InsectList::Init(), actIntDispatcher::inv_mouse_imove_quant(), uvsVanger::makeJump(), uvsBunch::nextCycle(), uvsVanger::prepare_shop(), uvsBunch::Quant(), uvsVanger::Quant(), actIntDispatcher::set_move_item(), ToolzerQuant(), uvsCloseQuant(), uvsPrepareQuant(), and uvsWorldReload().
uvsCurrentWorldUnableBefore
int uvsCurrentWorldUnableBefore = 0
Referenced by uvsVanger::prepare_shop().
uvsEndHarvest
int uvsEndHarvest = 0
Referenced by uvsBunch::begin_harvest(), uvsBunch::begin_race(), uvsBunch::end_harvest(), WaitEndGameInTown(), and WaitGameInTown().
uvsFirstTime
time_t uvsFirstTime = 0
Referenced by FirstShopPrepare(), and uvsVanger::get_shop().
uvsGamerWaitGame
int uvsGamerWaitGame = 0
Referenced by uvsBunch::begin_harvest(), uvsVanger::prepare_shop(), VangerUnit::Quant(), uniVangLoad(), uniVangSave(), and WaitGameInTown().
uvsItemTable
uvsItemType** uvsItemTable
Referenced by ActInt_param2(), ActInt_to_Item(), uvsItem::ActIntType(), uvsVanger::addItem(), ChargeDevice(), ChargeWeapon(), uvsVanger::checkDolly(), ActionDispatcher::DrawResource(), uvsWorld::generate_item(), uvsShop::get_list_from_ActInt(), GetItem_as_name(), GetItem_as_type(), ItemsDispatcher::Init(), uvsActInt::load(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsVanger::race_result(), uniVangDelete(), uvsChangeGoodsParam(), uvsDeleteItem(), uvsDomChangeFromItem(), uvsGenerateItemForCrypt(), uvsItem::uvsItem(), uvsKronDeleteItem(), uvsMechosLoad(), uvsMechosSave(), and uvsSetItemType().
uvsKronActive
int uvsKronActive = 0
Referenced by uvsBunch::begin_harvest(), uvsVanger::emuQuant(), uvsBunch::end_harvest(), uvsBunch::end_race(), FakeOfMight(), GeneralSystemClose(), GeneralSystemOpen(), NetCheckRemovePlayer(), GameObjectDispatcher::Quant(), PalConstructor::Quant(), uvsFlyFarmer::Quant(), uvsDolly::Quant(), ActionDispatcher::SlotIn(), uvsChangeGoodsInList(), uvsChangeTabuTask(), uvsgetDGdata(), and XpeditionOFF().
uvsLoadVersion
int uvsLoadVersion = 0
Referenced by uvsActInt::load(), uniVangLoad(), uvsItem::uvsItem(), uvsMechosLoad(), and uvsShop::uvsShop().
uvsMechosTable
uvsMechosType** uvsMechosTable
Referenced by uvsVanger::addInventory(), addVanger(), uvsVanger::changeRating(), VangerUnit::ChangeVangerProcess(), uvsUnitType::CreateUnitType(), uvsShop::get_list_from_ActInt(), uvsVanger::get_shop(), GetMechos_as_name(), uvsTabuTaskType::is_able(), uvsVanger::KillStatic(), uvsVanger::prepare_diagen_statistic(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), uvsShop::sellMechos(), VangerUnit::ShellNetEvent(), uvsMechos::sort(), uniVangDelete(), uvsActIntSellMechos(), uvsCheckKronIventTabuTask(), uvsCheckVangerTabuTask(), uvsgetDGdata(), uvsMakeNewGamerInEscave(), uvsMechosLoad(), uvsMechosSave(), and uvsMechosType_to_AciInt().
uvsNetworkChangeWorld
int uvsNetworkChangeWorld = 0
uvsPoponkaID
int uvsPoponkaID = 0
Referenced by CreateBoozeeniadaString(), uvsVanger::go_from_escave(), uvsVanger::go_from_spot(), and uvsPoponkaIDON().
uvsQuantFlag
int uvsQuantFlag = 0
Referenced by uniVangLoad().
uvsQuantity
int uvsQuantity = 0
Referenced by uvsEscave::add_goods_to_shop(), and uvsSpot::add_goods_to_shop().
uvsRandomWorld
int uvsRandomWorld = 0
uvsTabuTaskFlag
int uvsTabuTaskFlag = 0
uvsTabuTaskX
int uvsTabuTaskX = 0
uvsTabuTaskY
int uvsTabuTaskY = 0
uvsTownName
const char* uvsTownName = NULL
Referenced by uvsVanger::get_shop(), uvsVanger::prepare_shop(), uniVangLoad(), uvsCloseQuant(), and uvsSetTownName().
uvsUnikumeMechos
int uvsUnikumeMechos = 1
Referenced by uvsVanger::get_shop().
uvsVANGER_ARRIVAL
const int uvsVANGER_ARRIVAL = 0
Referenced by uvsVanger::homeArrival(), uvsVanger::makeJump(), uvsVanger::spotArrival(), and uvsCheckVangerTabuTask().
uvsVANGER_FAILED
const int uvsVANGER_FAILED = 1
Referenced by uvsVanger::destroy(), and uvsCheckVangerTabuTask().
uvsVANGER_KILLED
const int uvsVANGER_KILLED = 2
Referenced by uvsVanger::destroy(), and uvsCheckVangerTabuTask().
uvsVersion
int uvsVersion = 14
Referenced by uniVangSave().
WEEZYK
const int WEEZYK[1] = { 5000}
WorldLightParam
int WorldLightParam[WORLD_MAX][3] extern
Referenced by ChangeVanger(), PalPoint::Set(), and uvsCloseQuant().
WorldPalCurrent
int WorldPalCurrent extern
Referenced by BunchEvent(), ChangeVanger(), OpenCyclicPal(), PalettePrepare(), PalPoint::Set(), and uvsCloseQuant().
WorldPalData
uchar** WorldPalData extern
Referenced by BunchEvent(), CloseBunchPal(), CloseCyclicPal(), GeneralTableOpen(), OpenCyclicPal(), PalettePrepare(), and uvsCloseQuant().
WorldTable
uvsWorld* WorldTable[WORLD_MAX]
Referenced by aciInitWorldIDs(), ChangeVanger(), ItemsDispatcher::Close(), ItemsDispatcher::CryptQuant(), uvsVanger::destroy(), uvsBunch::end_harvest(), uvsBunch::end_race(), FindFreeVanger(), SkyFarmerList::Free(), FreeFarmer(), uvsVanger::get_shop(), GetPassage(), GloryPlace::Init(), SkyFarmerList::Init(), uvsVanger::makeJump(), NetworkWorldOpen(), ItemsDispatcher::Open(), OpenCyclicPal(), PalettePrepare(), uvsVanger::prepare_list_for_ActInt(), uvsShop::prepare_list_for_ActInt(), ActionDispatcher::PromptChangeCycle(), ActionDispatcher::PromptQuant(), VangerUnit::Quant(), uvsVanger::Quant(), sBunchReceive(), VangerUnit::SensorQuant(), uvsCatchDolly(), uvsCloseQuant(), uvsCreateNetVanger(), uvsCreateNewItem(), uvsDolly::uvsDolly(), uvsFlyFarmer::uvsFlyFarmer(), uvsFreeDolly(), uvsKronDeleteItem(), uvsRestoreVanger(), uvsReturnWorldGamerVisit(), uvsVanger::uvsVanger(), uvsWorld::uvsWorld(), uvsWorldReload(), uvsWorldToCross(), WaitEndGameInTown(), and WaitGameInTown().