Vangers: src/units/uvsapi.h File Reference
uvsapi.h File Reference
Classes
struct uvsKernel
union UnitOrderType
Functions
VangerUnit * addVanger (uvsVanger *p, int x, int y, int Human=0)
VangerUnit * addVanger (uvsVanger *p, uvsPassage *origin, int Human=0)
VangerUnit * addVanger (uvsVanger *p, uvsEscave *origin, int Human=0)
VangerUnit * addVanger (uvsVanger *p, uvsSpot *origin, int Human=0)
void BunchEvent (int type)
void ChangeWorld (int world, int flag=1)
int uvsapiDestroyItem (int ind, int ind2)
int uvsSetItemType (int type, int param1, int param2)
void addFarmer (int x_pos, int y_pos, int x_speed, int y_speed, int corn_type, int corn, int time)
void ChangeItemData (int d)
void ChangeTabutaskItem (int type, int status)
void NetStatisticInit (void)
void NetStatisticUpdate (int id)
void NetStatisticGameStart (void)
void CreateBoozeeniadaString (void)
int FuckOFFinWater (void)
char * StringOfBoozeeniada (void)
void addInfernalsKill2Protractor (void)
void addSpectorsKill2Messiah (void)
int getSpobsState (void)
int getThreallState (void)
int isSpummyDeath (void)
void sBunchCreate (int &id, int world, int data, int cycle)
void sBunchSend (int id, int data, int cycle)
void sBunchReceive (int id)
void OpenCrypt (int world, int id)
void NetworkQuant (void)
void CloseBunchPal (void)
int CheckThreallMessiah (void)
void ShowDominanceMessage (int d)
void ShowLuckMessage (int d)
void ShowTaskMessage (int l)
void aiPromptDominanceMessage (int d)
void aiPromptLuckMessage (int d)
void aiPromptTaskMessage (int l)
void NetworkGetStart (char *name, int &x, int &y)
Variables
const int BUNCH_CHANGE_CYCLE = 1
const int UVS_DEVICE_POWER = 1000
const int UVS_AMMO_POWER = 30
const int UVS_TERMINATOR_POWER = 8
const int UNIT_ORDER_NONE = 0
const int UNIT_ORDER_ACTION = 1
const int UNIT_ORDER_STUFF = 2
const int UNIT_ORDER_SENSOR = 3
const int UNIT_ORDER_ENTER = 4
const int UNIT_ORDER_PASSAGE = 5
const int UNIT_ORDER_DOLL = 6
const int UNIT_ORDER_FARMER = 7
const int UNIT_ORDER_VECTOR = 8
const int UNIT_ORDER_VANGER = 9
int GeneralSystemSkip
const int NET_STATISTICS_KILL = 0
const int NET_STATISTICS_DEATH = 1
const int NET_STATISTICS_CHECKPOINT = 2
const int NET_STATISTICS_END_RACE = 3
Function Documentation
addFarmer()
void addFarmer (int x_pos, int y_pos, int x_speed, int y_speed, int corn_type, int corn, int time)
 {
     (FarmerD.CreateSkyFarmer())->CreateSkyFarmer(x_pos,y_pos,x_speed,y_speed,corn_type,corn,time);
 };
References SkyFarmerList::CreateSkyFarmer(), and FarmerD.
Referenced by uvsBunch::begin_harvest(), and SkyFarmerList::Init().
addInfernalsKill2Protractor()
void addInfernalsKill2Protractor (void)
 {
     ActD.ThreallDestroyActive = 1;
     aciActivateItemFunction(ACI_PROTRACTOR,ACI_PROTRACTOR_EVENT8);
 };
addSpectorsKill2Messiah()
void addSpectorsKill2Messiah (void)
 {
     ActD.SpobsDestroyActive = 1;
     aciActivateItemFunction(ACI_MECHANIC_MESSIAH,ACI_MECH_MESSIAH_EVENT6);
 };
addVanger() [1/4]
VangerUnit* addVanger (uvsVanger * p, int x, int y, int Human = 0)
 {
     VangerUnit* n;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         n->CreateUnitType(p);
         if(Human){
             if(GeneralMapReload){
                 if(GeneralLoadReleaseFlag) vMap->release();
                 ViewX = x;
                 preViewY = ViewY = y;
                 vMap->reload(CurrentWorld);
                 GeneralMapReload = 0;
 #ifndef NEW_TNT
                 RestoreFlagBarell();
                 RestoreBarell();
 #endif
             };
             MLCheckQuant();
             ActD.CreateActive(n);
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,Vector(x,y,128),0,SET_3D_DIRECT_PLACE);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,Vector(x,y,128),0,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
         if(NetworkON){
             if(Human){
                 n->NetCreateVanger(NULL,NULL,NULL);
                 n->AddFree();
             }else n->NetCreateSlave();
         }else n->AddFree();
         ActD.ConnectObject(n);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddFree(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), CurrentWorld, ModelDispatcher::FindModel(), GeneralLoadReleaseFlag, GeneralMapReload, UnitList::GetObject(), MLCheckQuant(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, uvsVanger::Pmechos, preViewY, vrtMap::release(), vrtMap::reload(), SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, uvsMechos::type, uvsMechosTable, ViewX, ViewY, and vMap.
Referenced by CheckPlayerList(), uvsVanger::makeJump(), uvsVanger::Quant(), uvsRestoreVanger(), and uvsWorldReload().
addVanger() [2/4]
VangerUnit* addVanger (uvsVanger * p, uvsEscave * origin, int Human = 0)
 {
     int ang;
     VangerUnit* n;
     SensorDataType* s;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(origin->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddInEscave");
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(origin->locked)
 //      ErrH.Abort("Bad Locked Escave");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         s = origin->unitPtr.EnterT->GetCenter();
         if(Human){
             if(GeneralMapReload){
                 if(GeneralLoadReleaseFlag) vMap->release();
                 ViewX = s->R_curr.x;
                 preViewY = ViewY = s->R_curr.y;
                 vMap->reload(CurrentWorld);
                 GeneralMapReload = 0;
 #ifndef NEW_TNT
                 RestoreFlagBarell();
                 RestoreBarell();
 #endif
             };
             MLCheckQuant();
         };
         ((origin->unitPtr).EnterT)->ActiveCenter();
         n->CreateUnitType(p);
         if(s->Owner->Type == EngineTypeList::ESCAVE) ang = ((EscaveEngine*)(s->Owner))->StartAngle;
         else ang = RND(PI*2);
         if(Human){
             ActD.CreateActive(n);
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,s->R_curr,ang,SET_3D_DIRECT_PLACE);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,s->R_curr,ang,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
         n->AddEscave(s);
         ActD.ConnectObject(n);
         if(NetworkON){
             if(Human) n->NetCreateVanger(NULL,origin,NULL);
             else n->NetCreateSlave();
         };
         if(Human)
             ActD.PromptInit(1);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddEscave(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), CurrentWorld, EngineTypeList::ESCAVE, ModelDispatcher::FindModel(), GeneralLoadReleaseFlag, GeneralMapReload, UnitList::GetObject(), MLCheckQuant(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, SensorDataType::Owner, PI, uvsVanger::Pmechos, preViewY, ActionDispatcher::PromptInit(), GeneralObject::R_curr, vrtMap::release(), vrtMap::reload(), RND(), SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, LocationEngine::Type, uvsMechos::type, uvsMechosTable, ViewX, ViewY, vMap, Vector::x, and Vector::y.
addVanger() [3/4]
VangerUnit* addVanger (uvsVanger * p, uvsPassage * origin, int Human = 0)
 {
     VangerUnit* n;
     SensorDataType* s;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(origin->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddInPassage");
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(origin->locked)
 //      ErrH.Abort("Bad locked Passage");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         n->CreateUnitType(p);
         s = ((origin->unitPtr).PassageT)->ActionLink;
         if(Human){
             ActD.CreateActive(n);
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,s->R_curr,0,SET_3D_DIRECT_PLACE);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,s->R_curr,0,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
 //      n->AddPassage(s);
         if(NetworkON){
             if(Human){
                 n->NetCreateVanger(origin,NULL,NULL);
                 n->AddPassage(s);
             }else n->NetCreateSlave();
         }else n->AddPassage(s);
 //      if(NetworkON){
 //          if(Human) n->NetCreateVanger(origin,NULL,NULL);
 //          else n->NetCreateSlave();
 //      };
         ActD.ConnectObject(n);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddPassage(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), ModelDispatcher::FindModel(), UnitList::GetObject(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, uvsVanger::Pmechos, GeneralObject::R_curr, SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, uvsMechos::type, and uvsMechosTable.
addVanger() [4/4]
VangerUnit* addVanger (uvsVanger * p, uvsSpot * origin, int Human = 0)
 {
     VangerUnit* n;
     SensorDataType* s;
 #ifdef TEST_TRACK
     if(!Human) return NULL;
 #endif
 //  if(origin->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddInSpot");
 //  if(origin->locked)
 //      ErrH.Abort("Bad locked Spot");
 //  if(p->Pworld->gIndex != CurrentWorld)
 //      ErrH.Abort("Bad AddFree");
 //  if(!(p->Pmechos))
 //      ErrH.Abort("Add pMechos Error");
     n = (VangerUnit*)(ActD.GetObject(ACTION_VANGER));
     if(n){
         s = ((origin->unitPtr).EnterT)->GetCenter();
         if(Human){
             if(GeneralMapReload){
                 if(GeneralLoadReleaseFlag) vMap->release();
                 ViewX = s->R_curr.x;
                 preViewY = ViewY = s->R_curr.y;
                 vMap->reload(CurrentWorld);
                 GeneralMapReload = 0;
 #ifndef NEW_TNT
                 RestoreFlagBarell();
                 RestoreBarell();
 #endif
             };
             MLCheckQuant();
         };
         ((origin->unitPtr).EnterT)->ActiveCenter();
         n->CreateUnitType(p);
         if(Human){
             NumHumanModel = ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name);
             n->CreateActionUnit(NumHumanModel,SOBJ_ACTIVE,s->R_curr,0,SET_3D_DIRECT_PLACE);
             ActD.CreateActive(n);
         }else n->CreateActionUnit(ModelD.FindModel(uvsMechosTable[p->Pmechos->type]->name),SOBJ_AUTOMAT,s->R_curr,0,SET_3D_DIRECT_PLACE);
         n->CreateTrackUnit();
         n->CreateVangerUnit();
         n->AddSpot(s);
         ActD.ConnectObject(n);
         if(NetworkON){
             if(Human) n->NetCreateVanger(NULL,NULL,origin);
             else n->NetCreateSlave();
         };
         if(Human)
             ActD.PromptInit(0);
     };
     return n;
 };
References ActD, ACTION_VANGER, VangerUnit::AddSpot(), UnitList::ConnectObject(), ActionUnit::CreateActionUnit(), ActionDispatcher::CreateActive(), TrackUnit::CreateTrackUnit(), uvsUnitType::CreateUnitType(), VangerUnit::CreateVangerUnit(), CurrentWorld, ModelDispatcher::FindModel(), GeneralLoadReleaseFlag, GeneralMapReload, UnitList::GetObject(), MLCheckQuant(), ModelD, uvsMechosType::name, VangerUnit::NetCreateSlave(), VangerUnit::NetCreateVanger(), NetworkON, NULL, NumHumanModel, uvsVanger::Pmechos, preViewY, ActionDispatcher::PromptInit(), GeneralObject::R_curr, vrtMap::release(), vrtMap::reload(), SET_3D_DIRECT_PLACE, SOBJ_ACTIVE, SOBJ_AUTOMAT, uvsMechos::type, uvsMechosTable, ViewX, ViewY, vMap, Vector::x, and Vector::y.
aiPromptDominanceMessage()
void aiPromptDominanceMessage (int d)
 {
 //  if(!uvsKronActive) return;
     RaceTxtBuff.init();
     if(lang() == RUSSIAN) RaceTxtBuff < rDominanceMessageData;
     else RaceTxtBuff < DominanceMessageData;
     if(d > 0) RaceTxtBuff < " +";
     else RaceTxtBuff < " -";
     RaceTxtBuff <= abs(d);
     aiMessageBuffer.align_type = 0;
     aiMessageBuffer.TimeBuf[0] = 200;
     aiMessageBuffer.ColBuf[0] = 143;
     aiMessageBuffer.NumStr = 1;
     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
     aciSendPrompt(&aiMessageBuffer);
 };
References aciSendPrompt(), aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, aciPromptData::ColBuf, DominanceMessageData, XBuffer::GetBuf(), XBuffer::init(), lang(), aciPromptData::NumStr, RaceTxtBuff, rDominanceMessageData, RUSSIAN, and aciPromptData::TimeBuf.
Referenced by aiMessageList::Quant().
aiPromptLuckMessage()
void aiPromptLuckMessage (int d)
 {
 //  if(!uvsKronActive) return;
     RaceTxtBuff.init();
     if(lang() == RUSSIAN) RaceTxtBuff < rTaskMessageLuck;
     else RaceTxtBuff < TaskMessageLuck;
     if(d > 0) RaceTxtBuff < " +";
     else RaceTxtBuff < " -";
     RaceTxtBuff <= abs(d);
     aiMessageBuffer.align_type = 0;
     aiMessageBuffer.TimeBuf[0] = 200;
     aiMessageBuffer.ColBuf[0] = 143;
     aiMessageBuffer.NumStr = 1;
     aiMessageBuffer.add_str(0,(uchar*)(RaceTxtBuff.GetBuf()));
     aciSendPrompt(&aiMessageBuffer);
 };
References aciSendPrompt(), aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, aciPromptData::ColBuf, XBuffer::GetBuf(), XBuffer::init(), lang(), aciPromptData::NumStr, RaceTxtBuff, rTaskMessageLuck, RUSSIAN, TaskMessageLuck, and aciPromptData::TimeBuf.
Referenced by aiMessageList::Quant().
aiPromptTaskMessage()
void aiPromptTaskMessage (int l)
 {
 //  if(!uvsKronActive) return;
     aiMessageBuffer.align_type = 0;
     if(l >= 0){
         if(lang() == RUSSIAN) aiMessageBuffer.add_str(0,(unsigned char*)rSuccessTaskMessageData);
         else aiMessageBuffer.add_str(0,(unsigned char*)SuccessTaskMessageData);
     }else{
         if(lang() == RUSSIAN) aiMessageBuffer.add_str(0,(unsigned char*)rFailedTaskMessageData);
         else aiMessageBuffer.add_str(0,(unsigned char*)FailedTaskMessageData);
     };
 //  aiMessageBuffer.add_str(0,(uchar*)(s));
     aiMessageBuffer.TimeBuf[0] = 200;
     aiMessageBuffer.ColBuf[0] = 143;
     RaceTxtBuff.init();
     if(lang() == RUSSIAN) RaceTxtBuff < rTaskMessageLuck;
     else RaceTxtBuff < TaskMessageLuck;
     if(l > 0) RaceTxtBuff < " +";
     else RaceTxtBuff < " -";
     RaceTxtBuff <= abs(l);
     aiMessageBuffer.add_str(1,(uchar*)(RaceTxtBuff.GetBuf()));
     aiMessageBuffer.TimeBuf[1] = 200;
     aiMessageBuffer.ColBuf[1] = 143;
     aiMessageBuffer.NumStr = 2;
     aciSendPrompt(&aiMessageBuffer);
     ClearTabutaskTarget();
 };
References aciSendPrompt(), aciPromptData::add_str(), aiMessageBuffer, aciPromptData::align_type, ClearTabutaskTarget(), aciPromptData::ColBuf, FailedTaskMessageData, XBuffer::GetBuf(), XBuffer::init(), lang(), aciPromptData::NumStr, RaceTxtBuff, rFailedTaskMessageData, rSuccessTaskMessageData, rTaskMessageLuck, RUSSIAN, SuccessTaskMessageData, TaskMessageLuck, and aciPromptData::TimeBuf.
Referenced by aiMessageList::Quant().
BunchEvent()
void BunchEvent (int type)
 {
     GeneralObject* p;
     switch(type){
         case BUNCH_CHANGE_CYCLE:
             if(CurrentWorld >= MAIN_WORLD_MAX - 1) return;
             WorldPalCurrent = uvsCurrentCycle;
             if(WorldPalCurrent >= WorldPalNum) WorldPalCurrent = 0;
 //          StartSetColor(100,WorldPalData[WorldPalCurrent]);
             PalCD.Set(CPAL_CHANGE_CYCLE,100,WorldPalData[WorldPalCurrent]);
             p = FarmerD.Tail;
             while(p){
 //              if(p->ID != ID_SKYFARMER)
 //                  ErrH.Abort("Bad SkyFarmer List");
                 ((SkyFarmerObject*)(p))->skyfarmer_end();
                 p = p->NextTypeList;
             };
             ActD.PromptChangeCycle();
             break;
     };
 };
References ActD, BUNCH_CHANGE_CYCLE, CPAL_CHANGE_CYCLE, CurrentWorld, FarmerD, MAIN_WORLD_MAX, GeneralObject::NextTypeList, PalCD, ActionDispatcher::PromptChangeCycle(), PalConstructor::Set(), UnitListType::Tail, uvsCurrentCycle, WorldPalCurrent, WorldPalData, and WorldPalNum.
Referenced by uvsBunch::Quant().
ChangeItemData()
void ChangeItemData (int d)
 {
     StuffObject* p;
     VangerUnit* n;
     p = (StuffObject*)(ItemD.Tail);
     while(p){
 //      uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d);
         if(uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d)){
             p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
             switch(p->ActIntBuffer.type){
                 case ACI_TABUTASK_FAILED:
                     SOUND_FAILED();
 //                  ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
                 case ACI_TABUTASK_SUCCESSFUL:
                     SOUND_SUCCESS();
 //                  ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
             };
         };
         p = (StuffObject*)(p->NextTypeList);
     };
     n = (VangerUnit*)(ActD.Tail);
     while(n){
         p = n->DeviceData;
         while(p){
 //          uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d);
             if(uvsChangeGoodsParam(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1,d)){
                 p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 if(p->Owner->Status & SOBJ_ACTIVE) aciChangeItem(&(p->ActIntBuffer));
                 switch(p->ActIntBuffer.type){
                     case ACI_TABUTASK_FAILED:
                         SOUND_FAILED();
 //                      ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         break;
                     case ACI_TABUTASK_SUCCESSFUL:
                         SOUND_SUCCESS();
 //                      ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         break;
                 };
             };
             p = p->NextDeviceList;
         };
         n = (VangerUnit*)(n->NextTypeList);
     };
 };
References ACI_TABUTASK_FAILED, ACI_TABUTASK_SUCCESSFUL, aciChangeItem(), ActD, StuffObject::ActIntBuffer, actintItemData::data0, actintItemData::data1, uvsUnitType::DeviceData, ItemD, StuffObject::NextDeviceList, StuffObject::Owner, StuffObject::SetStuffColor(), SOBJ_ACTIVE, SOUND_FAILED, SOUND_SUCCESS, UnitList::Tail, actintItemData::type, uvsChangeGoodsParam(), StuffObject::uvsDeviceType, and uvsSetItemType().
Referenced by uvsChangeGoodsInList().
ChangeTabutaskItem()
void ChangeTabutaskItem (int type, int status)
 {
     StuffObject* p;
     VangerUnit* n;
     p = (StuffObject*)(ItemD.Tail);
     while(p){
         if(p->uvsDeviceType == UVS_ITEM_TYPE::TABUTASK && uvsChangeTabuTask(p->ActIntBuffer.data0,p->ActIntBuffer.data1,type,status)){
             p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
             switch(p->ActIntBuffer.type){
                 case ACI_TABUTASK_FAILED:
                     SOUND_FAILED();
 //                  ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
                 case ACI_TABUTASK_SUCCESSFUL:
                     SOUND_SUCCESS();
 //                  ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                     p->SetStuffColor();
                     break;
             };
         };
         p = (StuffObject*)(p->NextTypeList);
     };
     n = (VangerUnit*)(ActD.Tail);
     while(n){
         p = n->DeviceData;
         while(p){
             if(p->uvsDeviceType == UVS_ITEM_TYPE::TABUTASK && uvsChangeTabuTask(p->ActIntBuffer.data0,p->ActIntBuffer.data1,type,status)){
                 p->ActIntBuffer.type = uvsSetItemType(p->uvsDeviceType,p->ActIntBuffer.data0,p->ActIntBuffer.data1);
                 switch(p->ActIntBuffer.type){
                     case ACI_TABUTASK_FAILED:
                         SOUND_FAILED();
 //                      ShowTaskMessage(-TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         if(p->Owner->Status & SOBJ_ACTIVE) aciChangeItem(&(p->ActIntBuffer));
                         break;
                     case ACI_TABUTASK_SUCCESSFUL:
                         SOUND_SUCCESS();
 //                      ShowTaskMessage(TabuTable[p->ActIntBuffer.data1 & 0xffff]->luck);
                         if(p->Owner->Status & SOBJ_ACTIVE) aciChangeItem(&(p->ActIntBuffer));
                         break;
                 };
             };
             p = p->NextDeviceList;
         };
         n = (VangerUnit*)(n->NextTypeList);
     };
 };
References ACI_TABUTASK_FAILED, ACI_TABUTASK_SUCCESSFUL, aciChangeItem(), ActD, StuffObject::ActIntBuffer, actintItemData::data0, actintItemData::data1, uvsUnitType::DeviceData, ItemD, StuffObject::NextDeviceList, StuffObject::Owner, StuffObject::SetStuffColor(), SOBJ_ACTIVE, SOUND_FAILED, SOUND_SUCCESS, UVS_ITEM_TYPE::TABUTASK, UnitList::Tail, actintItemData::type, uvsChangeTabuTask(), StuffObject::uvsDeviceType, and uvsSetItemType().
Referenced by uvsChangeTabuTask().
ChangeWorld()
void ChangeWorld (int world, int flag = 1)
 {
     int t,i;
     if(CurrentWorld == WORLD_KHOX)
         scale_general *= 2.;
     GeneralSystemClose();
     CloseCyclicPal();
     PassageBmpPrev = -1;
     t = RND(PassageBmpNum);
     if(PassageImageData[t].xSize != XGR_MAXX){
         for(i = t;i < PassageBmpNum;i++){
             if(PassageImageData[i].xSize == XGR_MAXX){
                 PassageBmpPrev = i;
                 break;
             };
         };
         if(PassageBmpPrev == -1){
             for(i = 0;i < PassageBmpNum;i++){
                 if(PassageImageData[i].xSize == XGR_MAXX){
                     PassageBmpPrev = i;
                     break;
                 };
             };
         };
     }else PassageBmpPrev = t;
     XGR_MouseHide();
     if(PassageBmpPrev >= 0) PassageImageData[PassageBmpPrev].Show();
     CurrentWorld = world;
     camera_X_prev = ViewX = NewWorldX;
     camera_Y_prev = preViewY = ViewY = NewWorldY;
 //  for(i = 0;i < MAX_NID_OBJECT;i++) LocalStationCounter[i] = 0;
     LocalStationCounter[GET_COUNTER_INDEX(NID_TNT)] = 0;
     LocalStationCounter[GET_COUNTER_INDEX(NID_SENSOR)] = 0;
     LocalNetEnvironment  =  LocalStationID | (CurrentWorld << 22);
     vMap->release();
     vMap -> reload(CurrentWorld);
     LoadResourceSOUND(GetTargetName("sound"));
     MLreload();
     Redraw = 1;
     OpenCyclicPal();
     GeneralTableOpen();
 //  OpenCyclicPal();
     if(flag)
         GeneralSystemOpen();
     else
         ChangeWorldSkipQuant = 1;
     if(world == WORLD_KHOX) //znfo - items sizing
         scale_general /= 2.;
     if(PassageBmpPrev >= 0) PassageImageData[PassageBmpPrev].Hide();
     XGR_MouseShow();
     memset(palbuf,0,768);
 //  XGR_SetPal(palbufOrg,0,255);
 #ifdef ACTINT
     void load_map_bmp(int n);
     load_map_bmp(CurrentWorld);
 #endif
 };
References camera_X_prev, camera_Y_prev, ChangeWorldSkipQuant, CloseCyclicPal(), CurrentWorld, GeneralSystemClose(), GeneralSystemOpen(), GeneralTableOpen(), GET_COUNTER_INDEX, GetTargetName(), PassageImageType::Hide(), load_map_bmp(), LoadResourceSOUND(), LocalNetEnvironment, LocalStationCounter, LocalStationID, MLreload(), NewWorldX, NewWorldY, NID_SENSOR, NID_TNT, OpenCyclicPal(), palbuf, PassageBmpNum, PassageBmpPrev, PassageImageData, preViewY, Redraw, vrtMap::release(), RND(), scale_general, PassageImageType::Show(), ViewX, ViewY, vMap, WORLD_KHOX, XGR_MAXX, XGR_MouseHide, and XGR_MouseShow.
Referenced by uvsVanger::makeJump(), and uvsVanger::Quant().
CheckThreallMessiah()
int CheckThreallMessiah (void)
 {
     if(ActD.Active && GetStuffObject(ActD.Active,ACI_MECHANIC_MESSIAH)) return 1;
     return 0;
 };
References ACI_MECHANIC_MESSIAH, ActD, ActionDispatcher::Active, and GetStuffObject().
Referenced by uvsgetDGdata().
CloseBunchPal()
void CloseBunchPal (void)
 {
     int k,j,i;
     Vector vColor,vCheck;
     int MaxVector,dc;
     if(uvsCurrentWorldUnable && CurrentWorld < MAIN_WORLD_MAX - 1){
         vColor = Vector(63,63,63);
         MaxVector = vColor.vabs();
         for(k = 0;k < WorldPalNum;k++){
             for(i = 0;i < NUM_COLOR_PLACE;i++){
                 for(j = FirstColorPlace[CurrentWorld][i];j <= LastColorPlace[CurrentWorld][i];j++){
                     vCheck = Vector(WorldPalData[k][j*3],WorldPalData[k][j*3 + 1],WorldPalData[k][j*3 + 2]);
                     dc = 63 * vCheck.vabs() / MaxVector;
                     WorldPalData[k][j*3] = WorldPalData[k][j*3] + GrayColorCycle[CurrentWorld][i]*(dc - WorldPalData[k][j*3]) / 63;
                     WorldPalData[k][j*3 + 1] = WorldPalData[k][j*3 + 1] + GrayColorCycle[CurrentWorld][i]*(dc - WorldPalData[k][j*3 + 1]) / 63;
                     WorldPalData[k][j*3 + 2] = WorldPalData[k][j*3 + 2] + GrayColorCycle[CurrentWorld][i]*(dc - WorldPalData[k][j*3 + 2]) / 63;
                 };
             };
         };
     };
 };
References CurrentWorld, FirstColorPlace, GrayColorCycle, LastColorPlace, MAIN_WORLD_MAX, NUM_COLOR_PLACE, uvsCurrentWorldUnable, Vector::vabs(), WorldPalData, and WorldPalNum.
Referenced by uvsCloseQuant().
CreateBoozeeniadaString()
void CreateBoozeeniadaString (void)
 {
     int i,t,i1,i2,s1,s2;
     char ch;
     CHECK_BSIGN_DATA = new char[NUM_CHECK_BSIGN + 1]; memset(CHECK_BSIGN_DATA, '\0', NUM_CHECK_BSIGN + 1);
     strcpy(CHECK_BSIGN_DATA, "ABCDEFKLMNOPR");
     for(i = 0;i < NUM_CHECK_BSIGN;i++)
         CHECK_BSIGN_INDEX[i] = i;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         i1 = RND(NUM_CHECK_BSIGN);
         i2 = RND(NUM_CHECK_BSIGN);
         if(i1 != i2){
             t = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = CHECK_BSIGN_INDEX[i2];
             CHECK_BSIGN_INDEX[i2] = t;
             ch = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = CHECK_BSIGN_DATA[i2];
             CHECK_BSIGN_DATA[i2] = ch;
         };
     };
     i1 = 1;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         if(CHECK_BSIGN_DATA[i] == 'A'){
             t = CHECK_BSIGN_INDEX[i];
             CHECK_BSIGN_INDEX[i] = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = t;
             ch = CHECK_BSIGN_DATA[i];
             CHECK_BSIGN_DATA[i] = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = ch;
             break;
         };
     };
     i1 = 3;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         if(CHECK_BSIGN_DATA[i] == 'E'){
             t = CHECK_BSIGN_INDEX[i];
             CHECK_BSIGN_INDEX[i] = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = t;
             ch = CHECK_BSIGN_DATA[i];
             CHECK_BSIGN_DATA[i] = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = ch;
             break;
         };
     };
     i1 = 5;
     for(i = 0;i < NUM_CHECK_BSIGN;i++){
         if(CHECK_BSIGN_DATA[i] == 'O'){
             t = CHECK_BSIGN_INDEX[i];
             CHECK_BSIGN_INDEX[i] = CHECK_BSIGN_INDEX[i1];
             CHECK_BSIGN_INDEX[i1] = t;
             ch = CHECK_BSIGN_DATA[i];
             CHECK_BSIGN_DATA[i] = CHECK_BSIGN_DATA[i1];
             CHECK_BSIGN_DATA[i1] = ch;
             break;
         };
     };
     CHECK_BSIGN_DATA[NUM_CONTROL_BSIGN] = '\0';
     for(i = 0;i < 8;i++){
         i1 = RND(2);
         i2 = RND(MAX_TIME_SECRET);
         s1 = RND(2);
         s2 = RND(MAX_TIME_SECRET);
         t = TimeSecretType[i1][i2];
         TimeSecretType[i1][i2] = TimeSecretType[s1][s2];
         TimeSecretType[s1][s2] = t;
     };
     for(i = 0;i < MAX_TIME_SECRET;i++){
         TimeSecretData0[0][i] = 0;
         if(UVS_ITEM_TYPE::POPONKA)
             TimeSecretData1[0][i] = uvsPoponkaID;
         else
             TimeSecretData1[0][i] = 0;
         TimeSecretData0[1][i] = 0;
         if(UVS_ITEM_TYPE::POPONKA)
             TimeSecretData1[1][i] = uvsPoponkaID;
         else
             TimeSecretData1[1][i] = 0;
     };
 };
References CHECK_BSIGN_DATA, CHECK_BSIGN_INDEX, MAX_TIME_SECRET, NUM_CHECK_BSIGN, NUM_CONTROL_BSIGN, UVS_ITEM_TYPE::POPONKA, RND(), TimeSecretData0, TimeSecretData1, TimeSecretType, and uvsPoponkaID.
Referenced by GeneralSystemInit().
FuckOFFinWater()
int FuckOFFinWater (void)
 {
     if(ActD.Active && (ActD.Active->dynamic_state & TOUCH_OF_WATER)) return 1;
     return 0;
 };
References ActD, ActionDispatcher::Active, and TOUCH_OF_WATER.
Referenced by uvsTabuTaskType::checkCycleEvent().
getSpobsState()
int getSpobsState (void)
 {
     if(ActD.SpobsDestroy == 0) return 1;
     return 0;
 };
getThreallState()
int getThreallState (void)
 {
      if(ActD.ThreallDestroy == 0) return 1;
      return 0;
 };
isSpummyDeath()
int isSpummyDeath (void)
 {
     return ActD.SpummyRunner;
 };
NetStatisticGameStart()
void NetStatisticGameStart (void)
 {
     time(&StartGameTime);
     PrevKillTime = PrevLifeTime = StartGameTime;
 };
References PrevKillTime, PrevLifeTime, and StartGameTime.
NetStatisticInit()
void NetStatisticInit (void)
 {
     my_player_body.kills = 0;
     my_player_body.deaths = 0;
     switch(my_server_data.GameType){
         case VAN_WAR:
             my_player_body.VanVarStat.MaxLiveTime = 0;
             my_player_body.VanVarStat.MinLiveTime = 0;
             my_player_body.VanVarStat.KillFreq = 0;
             my_player_body.VanVarStat.DeathFreq = 0;
             MinLifeTime = 0;
             MaxLifeTime = 0;
             MinKillTime = 0;
             MaxKillTime = 0;
             break;
         case PASSEMBLOSS:
             my_player_body.PassemblossStat.TotalTime = 0;
             my_player_body.PassemblossStat.MinTime = 0;
             my_player_body.PassemblossStat.MaxTime = 0;
             my_player_body.PassemblossStat.CheckpointLighting = 0;
             break;
         case MECHOSOMA:
             my_player_body.MechosomaStat.ItemCount1 = 0;
             my_player_body.MechosomaStat.ItemCount2 = 0;
             my_player_body.MechosomaStat.MaxTransitTime = 0;
             my_player_body.MechosomaStat.MinTransitTime = 0;
             my_player_body.MechosomaStat.SneakCount = 0;
             my_player_body.MechosomaStat.LostCount = 0;
             break;
     };
 };
References PassemblossStatistic::CheckpointLighting, VanVarStatistic::DeathFreq, PlayerBody::deaths, ServerData::GameType, MechosomaStatistic::ItemCount1, MechosomaStatistic::ItemCount2, VanVarStatistic::KillFreq, PlayerBody::kills, MechosomaStatistic::LostCount, MaxKillTime, MaxLifeTime, VanVarStatistic::MaxLiveTime, PassemblossStatistic::MaxTime, MechosomaStatistic::MaxTransitTime, MECHOSOMA, PlayerBody::MechosomaStat, MinKillTime, MinLifeTime, VanVarStatistic::MinLiveTime, PassemblossStatistic::MinTime, MechosomaStatistic::MinTransitTime, my_player_body, my_server_data, PASSEMBLOSS, PlayerBody::PassemblossStat, MechosomaStatistic::SneakCount, PassemblossStatistic::TotalTime, VAN_WAR, and PlayerBody::VanVarStat.
NetStatisticUpdate()
void NetStatisticUpdate (int id)
 {
     time_t t,d;
     time(&t);
     switch(my_server_data.GameType){
         case VAN_WAR:
             switch(id){
                 case NET_STATISTICS_KILL:
                     my_player_body.kills++;
                     d = labs((long)(t - PrevKillTime));
                     if(MinKillTime == 0 || MinKillTime > d) MinKillTime = d;
                     if(MaxKillTime == 0 || MaxKillTime < d) MaxKillTime = d;
                     PrevKillTime = t;
                     if(MinKillTime == MaxKillTime)my_player_body.VanVarStat.KillFreq = MaxKillTime;
                     else my_player_body.VanVarStat.KillFreq = (MaxKillTime - MinKillTime) / 2;
                     break;
                 case NET_STATISTICS_DEATH:
                     my_player_body.deaths++;
                     d = labs((long)(t - PrevLifeTime));
                     if(MinLifeTime == 0 || MinLifeTime > d) MinLifeTime = d;
                     if(MaxLifeTime == 0 || MaxLifeTime < d) MaxLifeTime = d;
                     PrevLifeTime = t;
                     if(MinLifeTime == MaxLifeTime) my_player_body.VanVarStat.DeathFreq = MaxLifeTime;
                     else my_player_body.VanVarStat.DeathFreq = (MaxLifeTime - MinLifeTime) / 2;
                     break;
             };
             break;
         case PASSEMBLOSS:
             switch(id){
                 case NET_STATISTICS_KILL:
                     my_player_body.kills++;
                     break;
                 case NET_STATISTICS_DEATH:
                     my_player_body.deaths++;
                     break;
                 case NET_STATISTICS_CHECKPOINT:
                     my_player_body.PassemblossStat.CheckpointLighting = UsedCheckNum;
                     my_player_body.PassemblossStat.MaxTime = labs((long)(t - StartGameTime));
                     break;
                 case NET_STATISTICS_END_RACE:
                     my_player_body.PassemblossStat.CheckpointLighting = UsedCheckNum;
                     my_player_body.PassemblossStat.TotalTime =
                         my_player_body.PassemblossStat.MaxTime = labs((long)(t - StartGameTime));
                     break;
             };
             break;
         case MECHOSOMA:
             switch(id){
                 case NET_STATISTICS_KILL:
                     my_player_body.kills++;
                     break;
                 case NET_STATISTICS_DEATH:
                     my_player_body.deaths++;
                     break;
                 case NET_STATISTICS_CHECKPOINT:
                 case NET_STATISTICS_END_RACE:
                     my_player_body.MechosomaStat.MinTransitTime = labs((long)(t - StartGameTime));
                     break;
             };
             break;
     };
 };
References PassemblossStatistic::CheckpointLighting, VanVarStatistic::DeathFreq, PlayerBody::deaths, ServerData::GameType, VanVarStatistic::KillFreq, PlayerBody::kills, MaxKillTime, MaxLifeTime, PassemblossStatistic::MaxTime, MECHOSOMA, PlayerBody::MechosomaStat, MinKillTime, MinLifeTime, MechosomaStatistic::MinTransitTime, my_player_body, my_server_data, NET_STATISTICS_CHECKPOINT, NET_STATISTICS_DEATH, NET_STATISTICS_END_RACE, NET_STATISTICS_KILL, PASSEMBLOSS, PlayerBody::PassemblossStat, PrevKillTime, PrevLifeTime, StartGameTime, PassemblossStatistic::TotalTime, UsedCheckNum, VAN_WAR, and PlayerBody::VanVarStat.
Referenced by VangerUnit::Destroy(), uvsVanger::prepare_diagen_statistic(), GloryPlace::Quant(), and VangerUnit::ShellNetEvent().
NetworkGetStart()
void NetworkGetStart (char * name, int & x, int & y)
 {
     int i,j,t;
     SensorSortedData = new SensorDataType*[SnsTableSize];
     StaticSort(SnsTableSize,(StaticObject**)SensorObjectData,(StaticObject**)SensorSortedData);
     for(i = 0;i < NETWORK_NUM_ESCAVE;i++){
         if(!strcmp(name,NetworkEscaveName[i])){
             t = -1;
             for(j = ActD.NetEnterOffset + 1;j < SnsTableSize;j++){
                 if(SensorObjectData[j]->SensorType == SensorTypeList::PLAYER_BIRTH && SensorObjectData[j]->data5 == i){
                     t = j;
                     break;
                 };
             };
             if(t == -1){
                 for(j =0;j < SnsTableSize;j++){
                     if(SensorObjectData[j]->SensorType == SensorTypeList::PLAYER_BIRTH && SensorObjectData[j]->data5 == i){
                         ActD.NetEnterOffset = j;
                         x = SensorObjectData[j]->R_curr.x;
                         y = SensorObjectData[j]->R_curr.y;
                         return;
                     };
                 };
             }else{
                 ActD.NetEnterOffset = t;
                 x = SensorObjectData[t]->R_curr.x;
                 y = SensorObjectData[t]->R_curr.y;
                 return;
             };
         };
     };
 //  ErrH.Abort("Escave Name Not FOUND!");
 };
References ActD, ActionDispatcher::NetEnterOffset, NETWORK_NUM_ESCAVE, NetworkEscaveName, SensorTypeList::PLAYER_BIRTH, GeneralObject::R_curr, SensorObjectData, SensorSortedData, SnsTableSize, StaticSort(), Vector::x, and Vector::y.
Referenced by uvsRestoreVanger().
NetworkQuant()
void NetworkQuant (void)
 {
     if(NetworkON)
         GameD.NetEvent();
 };
References GameD, GameObjectDispatcher::NetEvent(), and NetworkON.
Referenced by uvsQuant().
OpenCrypt()
void OpenCrypt (int world, int id)
 {
     TimeSecretEnable[world][id] = 1;
 };
sBunchCreate()
void sBunchCreate (int & id, int world, int data, int cycle)
 {
     id = NET_SBUNCH_COUNTER | (world << 22);
     NETWORK_OUT_STREAM.create_permanent_object(id,0,0,0);
     NETWORK_OUT_STREAM < (int)(cycle);
     NETWORK_OUT_STREAM < (int)(data);
     NETWORK_OUT_STREAM.end_body();
 };
References NET_SBUNCH_COUNTER, and NETWORK_OUT_STREAM.
sBunchReceive()
void sBunchReceive (int id)
 {
     int t;
     uvsBunch *pb = WorldTable[id >> 22]->escT[0]->Pbunch;
     NETWORK_IN_STREAM > t;
      pb -> currentStage = t;
     NETWORK_IN_STREAM > t;
     pb -> cycleTable[pb -> currentStage].cirtQ = t;
 };
References uvsWorld::escT, NETWORK_IN_STREAM, uvsEscave::Pbunch, and WorldTable.
Referenced by GameObjectDispatcher::NetEvent().
sBunchSend()
void sBunchSend (int id, int data, int cycle)
 {
     NETWORK_OUT_STREAM.update_object(id,0,0);
     NETWORK_OUT_STREAM < (int)(cycle);
     NETWORK_OUT_STREAM < (int)(data);
     NETWORK_OUT_STREAM.end_body();
 };
References NETWORK_OUT_STREAM.
Referenced by uvsWorldReload().
ShowDominanceMessage()
void ShowDominanceMessage (int d)
 {
 //#ifndef ZMOD_BETA
     if(NetworkON) return;
 //#endif
     aiMessageQueue.SendDominance(d);
 };
References aiMessageQueue, NetworkON, and aiMessageList::SendDominance().
Referenced by uvsVanger::get_shop(), uvsVanger::homeArrival(), uvsVanger::KillStatic(), uvsVanger::makeJump(), uvsVanger::Quant(), uvsVanger::spotArrival(), uvsChangeDominance(), and uvsDomChangeFromItem().
ShowLuckMessage()
void ShowLuckMessage (int d)
 {
 //#ifndef ZMOD_BETA
     if(NetworkON) return;
 //#endif
     aiMessageQueue.SendLuck(l);
 };
References aiMessageQueue, NetworkON, and aiMessageList::SendLuck().
Referenced by uvsVanger::checkDolly(), uvsBunch::end_harvest(), uvsBunch::end_race(), uvsVanger::get_shop(), uvsChangeLuck(), uvsDomChangeFromItem(), uvsFreeDolly(), uvsLuckChange(), and uvsOnKillItem().
ShowTaskMessage()
void ShowTaskMessage (int l)
 {
     if(NetworkON) return;
     aiMessageQueue.SendTabuTask(l);
 };
References aiMessageQueue, NetworkON, and aiMessageList::SendTabuTask().
Referenced by uvsTabuTaskType::checkCycleEvent(), uvsTabuTaskType::Erase(), and uvsChangeTabuTask().
StringOfBoozeeniada()
char* StringOfBoozeeniada (void)
 {
     return CHECK_BSIGN_DATA;
 };
uvsapiDestroyItem()
int uvsapiDestroyItem (int ind, int ind2)
 {
     VangerUnit* n;
     GeneralObject* p;
     StuffObject* g;
     int GamerOwnerLog,keep_log;
     GeneralObject* tp;
     StuffObject* tg;
     GamerOwnerLog = 0;
     p = ItemD.Tail;
     while(p){
 //      if(p->ID != ID_STUFF)
 //          ErrH.Abort("Bad Stuff List");
         tp = p->NextTypeList;
         if(((StuffObject*)(p))->uvsDeviceType == ind)
             ItemD.DeleteItem((StuffObject*)(p));
         p = tp;
     };
     n = (VangerUnit*)(ActD.Tail);
     if(ind2 == -1){
         while(n){
 //          if(n->ID != ID_VANGER)
 //              ErrH.Abort("Bad Vanger List");
             g = n->DeviceData;
             if(n->Status & SOBJ_ACTIVE){
                 while(g){
                     tg = g->NextDeviceList;
                     if(g->uvsDeviceType == ind){
                         n->CheckOutDevice(g);
                         ActD.CheckDevice(g);
                         aciRemoveItem(&(g->ActIntBuffer));
                         GamerOwnerLog = 1;
                         n->DelDevice(g);
                         g->Storage->Deactive(g);
                     };
                     g = tg;
                 };
             }else{
                 while(g){
                     tg = g->NextDeviceList;
                     if(g->uvsDeviceType == ind){
                         n->CheckOutDevice(g);
                         n->DelDevice(g);
                         g->Storage->Deactive(g);
                     };
                     g = tg;
                 };
             };
             n = (VangerUnit*)(n->NextTypeList);
         };
     }else{
         while(n){
             keep_log = 0;
             if(ind == UVS_ITEM_TYPE::ELEECH){
                 g = n->DeviceData;
                 while(g){
                     if(g->ActIntBuffer.type == ACI_TOXICK){
                         keep_log++;
                         if(keep_log == SAFE_STUFF_MAX)
                             break;
                     };
                     g = g->NextDeviceList;
                 };
 //              if(GetStuffObject(n,ACI_TOXICK)) keep_log = 1;
             }else{
                 if(ind == UVS_ITEM_TYPE::WEEZYK){
 //                  if(GetStuffObject(n,ACI_PHLEGMA)) keep_log = 1;
                     g = n->DeviceData;
                     while(g){
                         if(g->ActIntBuffer.type == ACI_PHLEGMA){
                             keep_log++;
                             if(keep_log == SAFE_STUFF_MAX)
                                 break;
                         };
                         g = g->NextDeviceList;
                     };
                 };
             };
             if(keep_log < SAFE_STUFF_MAX){
                 g = n->DeviceData;
                 while(g){
                     tg = g->NextDeviceList;
                     if(g->uvsDeviceType == ind){
                         g->uvsDeviceType = ind2;
                         g->ActIntBuffer.type = uvsSetItemType(g->uvsDeviceType,g->ActIntBuffer.data0,g->ActIntBuffer.data1);
                         if(n->Status & SOBJ_ACTIVE){
                             switch(ind){
                                 case UVS_ITEM_TYPE::ELEECH:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_ELLECH,0,0xff,0);
                                     break;
                                 case UVS_ITEM_TYPE::WEEZYK:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_WEEZYK,0,0xff,0);
                                     break;
                                 case UVS_ITEM_TYPE::KERNOBOO:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_KERN,0,0xff,0);
                                     break;
                                 case UVS_ITEM_TYPE::PIPETKA:
                                     aiMessageQueue.Send(AI_MESSAGE_DOWN_PIP,0,0xff,0);
                                     break;
                             };
                             aciChangeItem(&(g->ActIntBuffer));
                             GamerOwnerLog = 1;
                         };
                     };
                     g = tg;
                 };
             };
             n = (VangerUnit*)(n->NextTypeList);
         };
     };
     return GamerOwnerLog;
 };
References ACI_PHLEGMA, ACI_TOXICK, aciChangeItem(), aciRemoveItem(), ActD, AI_MESSAGE_DOWN_ELLECH, AI_MESSAGE_DOWN_KERN, AI_MESSAGE_DOWN_PIP, AI_MESSAGE_DOWN_WEEZYK, aiMessageQueue, ActionDispatcher::CheckDevice(), VangerUnit::CheckOutDevice(), uvsUnitType::DelDevice(), ItemsDispatcher::DeleteItem(), uvsUnitType::DeviceData, UVS_ITEM_TYPE::ELEECH, g, ItemD, UVS_ITEM_TYPE::KERNOBOO, GeneralObject::NextTypeList, UVS_ITEM_TYPE::PIPETKA, SAFE_STUFF_MAX, aiMessageList::Send(), SOBJ_ACTIVE, UnitList::Tail, uvsSetItemType(), and UVS_ITEM_TYPE::WEEZYK.
Referenced by uvsBunch::end_harvest(), and uvsBunch::end_race().
uvsSetItemType()
int uvsSetItemType (int type, int param1, int param2)
{
     if ( type == -1 ) return -1;
     if (type >= MAX_ITEM_TYPE)
         ErrH.Abort("uvsSetItemType :: type >= MAX_ITEM_TYPE");
     int i = uvsItemTable[type] -> SteelerTypeEmpty;
     if (type  == UVS_ITEM_TYPE::TABUTASK){
         if (param2 & ((int)(UVS_TABUTASK_STATUS::GOOD)<<16))
             return TABUTASK_GOOD;
         if (param2 & ((int)(UVS_TABUTASK_STATUS::BAD)<<16))
             return TABUTASK_BAD;
     }
     if( (param1 || param2) && (uvsItemTable[type] -> type != UVS_ITEM_STATUS::GOODS))
         i = uvsItemTable[type] -> SteelerTypeFull;
     return i;
 }
Referenced by aciSendEvent2itmdsp(), ChangeItemData(), ChangeTabutaskItem(), ChargeDevice(), VangerUnit::CheckOutDevice(), ItemsDispatcher::Close(), StuffObject::CreateDevice(), StuffObject::CreateStuff(), GunDevice::DeviceIn(), GunDevice::DeviceQuant(), VangerUnit::DischargeItem(), ItemsDispatcher::LarvaHilator(), StuffObject::Quant(), GunDevice::Quant(), VangerUnit::ResolveHandlerFind(), VangerUnit::UsingCopterig(), VangerUnit::UsingCrotrig(), VangerUnit::UsingCutterig(), and uvsapiDestroyItem().
Variable Documentation
BUNCH_CHANGE_CYCLE
const int BUNCH_CHANGE_CYCLE = 1
Referenced by BunchEvent(), and uvsBunch::Quant().
GeneralSystemSkip
int GeneralSystemSkip extern
NET_STATISTICS_CHECKPOINT
const int NET_STATISTICS_CHECKPOINT = 2
Referenced by NetStatisticUpdate(), uvsVanger::prepare_diagen_statistic(), and GloryPlace::Quant().
NET_STATISTICS_DEATH
const int NET_STATISTICS_DEATH = 1
Referenced by VangerUnit::Destroy(), and NetStatisticUpdate().
NET_STATISTICS_END_RACE
const int NET_STATISTICS_END_RACE = 3
Referenced by NetStatisticUpdate(), and GloryPlace::Quant().
NET_STATISTICS_KILL
const int NET_STATISTICS_KILL = 0
Referenced by NetStatisticUpdate(), and VangerUnit::ShellNetEvent().
UNIT_ORDER_ACTION
const int UNIT_ORDER_ACTION = 1
UNIT_ORDER_DOLL
const int UNIT_ORDER_DOLL = 6
Referenced by VangerUnit::AddFindResolve(), VangerUnit::MainOrderInit(), and VangerUnit::ResolveHandlerFind().
UNIT_ORDER_ENTER
const int UNIT_ORDER_ENTER = 4
Referenced by VangerUnit::AddFindResolve(), VangerUnit::AutomaticTouchSensor(), VangerUnit::GamerOrderInit(), VangerUnit::MainOrderInit(), VangerUnit::ResolveHandlerFind(), and VangerUnit::SensorQuant().
UNIT_ORDER_FARMER
const int UNIT_ORDER_FARMER = 7
UNIT_ORDER_NONE
const int UNIT_ORDER_NONE = 0
UNIT_ORDER_PASSAGE
const int UNIT_ORDER_PASSAGE = 5
Referenced by VangerUnit::AddFindResolve(), VangerUnit::GamerOrderInit(), VangerUnit::MainOrderInit(), VangerUnit::ResolveHandlerFind(), and VangerUnit::SensorQuant().
UNIT_ORDER_SENSOR
const int UNIT_ORDER_SENSOR = 3
Referenced by VangerUnit::AddFindResolve(), aiResolveList::FindResolve(), VangerUnit::GamerOrderInit(), VangerUnit::ResolveGenerator(), and VangerUnit::ResolveHandlerFind().
UNIT_ORDER_STUFF
const int UNIT_ORDER_STUFF = 2
Referenced by VangerUnit::AddEvent(), VangerUnit::AddFindResolve(), VangerUnit::CheckInDevice(), aiResolveList::ClearResolve(), aiResolveList::FindResolve(), VangerUnit::ResolveGenerator(), VangerUnit::ResolveHandlerFind(), and VangerUnit::StuffDestroyHandler().
UNIT_ORDER_VANGER
const int UNIT_ORDER_VANGER = 9
Referenced by VangerUnit::AddFindResolve(), VangerUnit::CalcAiFactor(), aiResolveList::ClearResolve(), aiResolveList::FindResolve(), VangerUnit::MainOrderInit(), VangerUnit::ResolveHandlerFind(), and VangerUnit::VangerDestroyHandler().
UNIT_ORDER_VECTOR
const int UNIT_ORDER_VECTOR = 8
Referenced by VangerUnit::AddFindResolve(), VangerUnit::MainOrderInit(), and VangerUnit::ResolveHandlerFind().
UVS_AMMO_POWER
const int UVS_AMMO_POWER = 30
UVS_DEVICE_POWER
const int UVS_DEVICE_POWER = 1000
UVS_TERMINATOR_POWER
const int UVS_TERMINATOR_POWER = 8