Vangers: src/terra/vmap.h File Reference
vmap.h File Reference
Classes
struct vrtWorld
struct vrtNode
struct vrtMap
Functions
void vMapPrepare (const char *name, int nWorld=0)
int getDistX (int v0, int v1)
int getDistY (int v0, int v1)
int getDelta (int v0, int v1)
int getDeltaX (int v0, int v1)
double getDistX (double v0, double v1)
double getDistY (double v0, double v1)
Variables
const uint H_POWER = MAP_POWER_X
const uint H_SIZE = 1 << H_POWER
const uint H2_SIZE = 2*H_SIZE
uint V_POWER
uint V_SIZE
int * FloodLvl
uchar FloodLEVEL
double zMod_cycle
double zMod_flood_level_delta
vrtMap * vMap
const int MLNAMELEN = 15
Function Documentation
getDelta()
int getDelta (int v0, int v1) inline
 {
     return YCYCL(v0 - v1 + V_SIZE);
 }
References V_SIZE, and YCYCL.
Referenced by vrtMap::quant().
getDeltaX()
int getDeltaX (int v0, int v1) inline
 {
     return XCYCL(v0 - v1 + H_SIZE);
 }
References H_SIZE, and XCYCL.
Referenced by regSet().
getDistX() [1/2]
double getDistX (double v0, double v1) inline
 {
     double d = v0 - v1;
     double ad = fabs(d);
     double dd = H_SIZE - ad;
     if(ad <= dd) return d;
     return d < 0 ? d + H_SIZE : d - H_SIZE;
 }
References H_SIZE.
getDistX() [2/2]
int getDistX (int v0, int v1) inline
 {
     int d = v0 - v1;
     int ad = abs(d);
     int dd = H_SIZE - ad;
     if(ad <= dd) return d;
     return d < 0 ? d + H_SIZE : d - H_SIZE;
 }
References H_SIZE.
Referenced by aciGetScreenItem(), aciGetScreenMechos(), VangerUnit::Action(), uvsDolly::ActiveQuant(), TargetParticleObject::AddVertex(), TargetParticleObject::AddVertex2(), AxisLen(), Object::basic_debris_analysis(), Object::basic_mechous_analysis(), VangerUnit::BulletCollision(), VangerUnit::CalcAiFactor(), MobileLocation::calcBounds(), VangerUnit::CalcForce(), VangerUnit::CalcImpulse(), camera_direct(), camera_quant(), TrackUnit::Check2Position(), VangerUnit::CheckFind(), VangerUnit::CheckNearTrack(), VangerUnit::CheckReturn2Track(), GunSlot::CheckTarget(), ItemsDispatcher::Close(), BulletObject::CreateBullet(), ItemsDispatcher::CreateEnableCrypt(), ParticleObject::CreateParticle(), VangerUnit::Destroy(), TntCreature::Destroy(), VangerUnit::DestroyEnvironment(), GunDevice::DeviceIn(), TrackUnit::DirectQuant(), DrawMechosWheelDown(), DrawMechosWheelUp(), BulletObject::DrawQuant(), HordeObject::DrawQuant(), BulletObject::Event(), GunSlot::Fire(), DangerDataType::FireWork(), G2L(), G2LF(), G2LP(), G2LQ(), G2LS(), GetAngle(), EnterCenter::GetEnterCenter(), GetEscaveDist(), TrackType::GetFirstPosition(), VangerUnit::GetForceWay(), TrackType::GetPosition(), StuffObject::GetTouchSensor(), ActionUnit::InitEnvironment(), VangerUnit::InitEnvironment(), InsectUnit::InitEnvironment(), VangerUnit::keyhandler(), LenDist(), LinkDist(), TntCreature::Load(), MapLineTrace(), TntCreature::NetDestroy(), Object::NetEvent(), VangerUnit::NewKeyHandler(), VangerUnit::NoWayHandler(), LocationEngine::Open(), Object::precise_impulse(), MobileLocation::quant(), ParticleObject::Quant(), WaterParticleObject::Quant(), TargetParticleObject::Quant(), ParticleGenerator::Quant(), HordeObject::Quant(), JumpBallObject::Quant(), SkyFarmerObject::Quant(), FishWarrior::Quant(), GloryPlace::Quant(), ItemsDispatcher::Quant(), InsectUnit::Quant(), CyclicEngine::Quant(), TntCreature::Quant(), GunSlot::RemoteFire(), VangerUnit::ResolveGenerator(), VangerUnit::ResolveHandlerAttack(), VangerUnit::ResolveHandlerFind(), ScreenLineTrace(), VangerUnit::SensorQuant(), VangerUnit::ShellNetEvent(), GameObjectDispatcher::Sort(), LocationEngine::SoundEvent(), StaticOpen(), StaticQuant(), VangerUnit::TargetAnalysis(), VangerUnit::TerrainQuant(), Object::test_object_to_baseobject(), VangerUnit::test_objects_collision(), BulletObject::TimeOutQuant(), ClefObject::Touch(), JumpBallObject::Touch(), InsectUnit::Touch(), TouchSphere(), TouchSphereZ(), and Object::update_coord().
getDistY() [1/2]
double getDistY (double v0, double v1) inline
 {
     double d = v0 - v1;
     double ad = fabs(d);
     double dd = V_SIZE - ad;
     if(ad <= dd) return d;
     return d < 0 ? d + V_SIZE : d - V_SIZE;
 }
References V_SIZE.
getDistY() [2/2]
int getDistY (int v0, int v1) inline
 {
     int d = v0 - v1;
     int ad = abs(d);
     int dd = V_SIZE - ad;
     if(ad <= dd) return d;
     return d < 0 ? d + V_SIZE : d - V_SIZE;
 }
References V_SIZE.
Referenced by aciGetScreenItem(), aciGetScreenMechos(), VangerUnit::Action(), uvsDolly::ActiveQuant(), TargetParticleObject::AddVertex(), TargetParticleObject::AddVertex2(), AxisLen(), Object::basic_debris_analysis(), Object::basic_mechous_analysis(), VangerUnit::CalcAiFactor(), MobileLocation::calcBounds(), VangerUnit::CalcForce(), VangerUnit::CalcImpulse(), camera_direct(), camera_quant(), vrtMap::change(), TrackUnit::Check2Position(), VangerUnit::CheckFind(), VangerUnit::CheckReturn2Track(), GunSlot::CheckTarget(), ItemsDispatcher::Close(), BulletObject::CreateBullet(), ItemsDispatcher::CreateEnableCrypt(), ParticleObject::CreateParticle(), TntCreature::Destroy(), VangerUnit::DestroyEnvironment(), TrackUnit::DirectQuant(), DrawMechosWheelDown(), DrawMechosWheelUp(), BulletObject::DrawQuant(), BulletObject::Event(), GunSlot::Fire(), DangerDataType::FireWork(), G2L(), G2LF(), G2LP(), G2LQ(), G2LS(), GetAngle(), EnterCenter::GetEnterCenter(), GetEscaveDist(), TrackType::GetFirstPosition(), GetNearSensor(), TrackType::GetPosition(), StuffObject::GetTouchSensor(), vrtMap::increase(), ActionUnit::InitEnvironment(), VangerUnit::InitEnvironment(), InsectUnit::InitEnvironment(), LenDist(), LinkDist(), TntCreature::Load(), MapLineTrace(), TntCreature::NetDestroy(), Object::NetEvent(), VangerUnit::NoWayHandler(), LocationEngine::Open(), Object::precise_impulse(), ActionDispatcher::PromptQuant(), MobileLocation::quant(), vrtMap::quant(), ParticleObject::Quant(), WaterParticleObject::Quant(), TargetParticleObject::Quant(), ParticleGenerator::Quant(), HordeObject::Quant(), JumpBallObject::Quant(), SkyFarmerObject::Quant(), FishWarrior::Quant(), GloryPlace::Quant(), InsectUnit::Quant(), CyclicEngine::Quant(), TntCreature::Quant(), VangerUnit::ResolveGenerator(), VangerUnit::ResolveHandlerAttack(), VangerUnit::ResolveHandlerFind(), ScreenLineTrace(), GameObjectDispatcher::Sort(), LocationEngine::SoundEvent(), StaticOpen(), VangerUnit::TargetAnalysis(), VangerUnit::TerrainQuant(), Object::test_object_to_baseobject(), VangerUnit::test_objects_collision(), BulletObject::TimeOutQuant(), TouchSphere(), TouchSphereZ(), and Object::update_coord().
vMapPrepare()
void vMapPrepare (const char * name, int nWorld = 0)
 {
 #ifdef _ROAD_
     if(NetworkON)
 #endif
         KeepON = 0;
     vMap = new vrtMap;
     vMap -> load(name,nWorld);
 #ifdef _SURMAP_
     vMapInit();
 #endif
 }
References KeepON, NetworkON, vMap, and vMapInit().
Referenced by LoadingRTO2::Init().
Variable Documentation
FloodLEVEL
uchar FloodLEVEL extern
Referenced by Object::basic_debris_analysis(), Object::basic_mechous_analysis(), Object::destroy_double_level(), Object::draw(), Object::fish_analysis(), Object::insect_analysis(), TrainEngine::Link(), vrtMap::linkC(), Object::pixel_draw(), and DangerDataType::Quant().
FloodLvl
int* FloodLvl extern
Referenced by CreateDestroyEffect(), BulletObject::Event(), LoadVPR(), pixDownSet(), pixSet(), pixSetR(), vrtMap::reload(), YSetup(), and vrtMap::~vrtMap().
H2_SIZE
const uint H2_SIZE = 2*H_SIZE
H_POWER
const uint H_POWER = MAP_POWER_X
H_SIZE
const uint H_SIZE = 1 << H_POWER
Referenced by getDeltaX(), and getDistX().
MLNAMELEN
const int MLNAMELEN = 15
V_POWER
uint V_POWER extern
Referenced by YSetup().
V_SIZE
uint V_SIZE extern
Referenced by vrtMap::delink(), vrtMap::dump_terrain(), vrtMap::finit(), getDelta(), getDistY(), vrtMap::init(), vrtMap::load(), regRender(), regRender2(), vrtMap::reload(), SetSkipLineTable(), and YSetup().
vMap
vrtMap* vMap extern
Referenced by addVanger(), Mask::BackRestore(), Particle::BackRestore(), Object::basic_debris_analysis(), Object::basic_mechous_analysis(), BigGetAlt(), CastArbitraryShadow(), CastShadow(), ChangeVanger(), ChangeWorld(), MLFrame::check(), check_double_level(), VariablePolygon::check_mole_submerging(), VariablePolygon::check_terrain_type(), ClearBarell(), creat_poster(), CreateDestroyEffect(), dastPutSandOnMapAlt(), dastPutSpriteOnMapAlt(), Mask::deformBuff(), Object::destroy_double_level(), DestroyBarellSmooth(), DestroyBarellSmoothWithCheck(), DestroyBarellSpot(), MLFrame::DestroyQuant(), DestroySmooth(), DestroySmoothCheck(), DestroySmoothPut(), DestroySpot(), iGameMap::draw(), Draw3DPlane(), DrawLinear(), TrackUnit::DrawMechosParticle(), BulletObject::Event(), Particle::express(), LightPoint::FourLightLine(), FreeAll(), get_down_ground(), get_height(), get_real_ground(), get_three_heights(), get_up_ground(), get_upper_height(), GetAlt(), GetAltLevel(), Particle::GetBackGround(), GetCollisionMap(), GetGlobalAlt(), GetLandAlt(), GetMapLevel(), GetMapLevelType(), Object::ground_pressing(), height_analysis_fish(), LoadingRTO2::Init(), GameQuantRTO::Init(), Object::insect_analysis(), LandSlideLine(), LINE_render(), LightPoint::load_color_line(), LoadVPR(), VariablePolygon::lower_average(), VariablePolygon::lower_average_z(), dastPoly3D::make_catch_dolly(), dastPoly3D::make_first_mole(), dastPoly3D::make_last_mole(), dastPoly3D::make_mole(), MakeSecondLevel(), MapCircleProcess(), PalettePrepare(), PerpSlopTurn(), pixDownSet(), pixSet(), pixSetR(), Object::precise_impulse(), ParticleMapProcess::process(), Particle::purge(), MLFrame::quant(), LightPoint::quant(), GloryPlace::Quant(), MLFrame::quantAbs(), RadialRender(), regRender(), regRender2(), regSet(), iGameMap::reset(), VangerUnit::ResolveGenerator(), LightPoint::restore_color_line(), section_prepare(), set_3D_adjust(), setMapPixel(), SlopTurnSkip(), smart_putspr(), smart_putspr_f(), square_analysis(), MLFrame::start(), StaticQuant(), Object::test_whether_there_is_not_something_above(), vrtMap::turning(), VariablePolygon::upper_average(), uvsPrepareQuant(), vMapInit(), vMapPrepare(), WaterAltLevel(), xDestroySpot(), and xRestoreDestroySpot().
zMod_cycle
double zMod_cycle extern
zMod_flood_level_delta
double zMod_flood_level_delta extern