Vangers: lib/xtool/xutil/xclock.cpp File Reference
xclock.cpp File Reference
#include "xglobal.h"
Functions
long long getRDTSC ()
void initclock ()
double clockf ()
int clocki ()
Variables
long long tick_per_sec =1000
long long beg_tick =0
const unsigned int MS_PER_PERIOD =1
Function Documentation
clockf()
double clockf (void)
 {
 //std::cout<<"clockf() "<<(double)(getRDTSC()-beg_tick)/(double)tick_per_sec<<std::endl;
 //  return (double)(getRDTSC()-beg_tick)/(double)tick_per_sec;
     return (double)SDL_GetTicks()*MS_PER_PERIOD;
 }
References MS_PER_PERIOD.
clocki()
int clocki (void)
 {
 //std::cout<<"clocki() "<<(int)((getRDTSC()-beg_tick)/tick_per_sec)<<std::endl;
 //  return (int)((getRDTSC()-beg_tick)/tick_per_sec);
 //  return (int)((getRDTSC()-beg_tick)*1000);
     return (SDL_GetTicks()*MS_PER_PERIOD);
 }
References MS_PER_PERIOD.
Referenced by main().
getRDTSC()
long long getRDTSC ()
 {
     return SDL_GetTicks(); //stalkerg: winnt function for get tick milliseconds.
 }
Referenced by initclock().
initclock()
void initclock (void)
 {
     if(tick_per_sec!=0)
         return;
 /*  clock_t t1,t2;
     __int64 tickb,ticke;
     t1=t2=clock();
     while(t1==t2){
         t2=clock();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+1000 > t2){
         t2=clock();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/1000;
     beg_tick=getRDTSC();
 */
 //  timeBeginPeriod(1);
 /*  unsigned int t1,t2;
     __int64 tickb,ticke;
     t1=t2=timeGetTime();
     while(t1==t2){
         t2=timeGetTime();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+MS_PER_PERIOD > t2){
         t2=timeGetTime();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/MS_PER_PERIOD;
     beg_tick=getRDTSC();
     */
     /*WORKunsigned int t1,t2;
     long long tickb,ticke;
     t1=t2=getRDTSC();
     while(t1==t2){
         t2=getRDTSC();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+MS_PER_PERIOD > t2){
         t2=getRDTSC();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/MS_PER_PERIOD;*/
     beg_tick=getRDTSC();
 std::cout<<"initclock() "<<tick_per_sec<<" b:"<<beg_tick<<std::endl;
 //  timeEndPeriod(1);
 /*  LARGE_INTEGER TK_PER_SEC;
     QueryPerformanceFrequency(&TK_PER_SEC);
     __int64 t1,t2;
     __int64 tickb,ticke;
     t1=t2=getQPC();
     while(t1==t2){
         t2=getQPC();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+TK_PER_SEC.QuadPart > t2){
         t2=getQPC();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/1000;//MS_PER_SEC;
     beg_tick=getRDTSC();*/
 }
References beg_tick, getRDTSC(), and tick_per_sec.
Referenced by main().
Variable Documentation
beg_tick
long long beg_tick =0
Referenced by initclock().
MS_PER_PERIOD
const unsigned int MS_PER_PERIOD =1
Referenced by clockf(), and clocki().
tick_per_sec
long long tick_per_sec =1000
Referenced by initclock().