Vangers: lib/xgraph/xfont.cpp File Reference
xfont.cpp File Reference
#include "xgraph.h"
Macros
#define XFNT_TAB_SIZE 8
Functions
void XFNT_Prepare (void)
void XGR_OutString (int x, int y, int col, void *str, int font, int space, int pr_flag)
void XGR_OutText (int x, int y, int col, void *text, int font, int hspace, int vspace, int pr_flag)
int XGR_StrLen (void *str, int font, int space)
int XGR_TextWidth (void *text, int font, int hspace)
int XGR_TextHeight (void *text, int font, int vspace)
Variables
XGR_Font ** XGR_FontTable = NULL
Macro Definition Documentation
XFNT_TAB_SIZE
#define XFNT_TAB_SIZE 8
Function Documentation
XFNT_Prepare()
void XFNT_Prepare (void)
 {
     if(XGR_FontTable) return;
     XGR_FontTable = new XGR_Font*[XGR_NUM_FONTS];
     XGR_FontTable[XGR_FONT0_8x16] = new XGR_Font;
     XGR_FontTable[XGR_FONT0_8x16] -> init(4096,XSysFontData0);
     XGR_FontTable[XGR_FONT0_8x8] = new XGR_Font;
     XGR_FontTable[XGR_FONT0_8x8] -> init(2048,XSysFontData1);
 }
References XGR_FONT0_8x16, XGR_FontTable, and XGR_NUM_FONTS.
Referenced by XGR_Screen::init().
XGR_OutString()
void XGR_OutString (int x, int y, int col, void * str, int font, int space, int pr_flag)
 {
     int sx,sy,hcol_flag = 0;
     int i,j,s,ch,n,count,offs = 0,sz = strlen((char*)str),X = 0;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     char* p = (char*)XGR_FontTable[font] -> data;
     unsigned char* buf = (unsigned char*)str;
     sx = XGR_FontTable[font] -> SizeX;
     sy = XGR_FontTable[font] -> SizeY;
     if(XGR_Obj.flags & XGR_HICOLOR) hcol_flag = 1;
     for(s = 0; s < sz; s ++){
         if(buf[s] == '\t'){
             ch = ' ';
             count = XFNT_TAB_SIZE;
         }
         else {
             ch = buf[s];
             count = 1;
         }
         for(n = 0; n < count; n ++){
             if(pr_flag)
                 X -= lOffs[ch];
             offs = sy * ch;
             for(i = 0; i < sy; i ++){
                 for(j = 0; j < sx; j ++){
                     if(p[offs] & (1 << (7 - j))){
                         if(hcol_flag)
                             XGR_SetPixel16Fast(x + X + j,y + i,col);
                         else
                             XGR_SetPixelFast(x + X + j,y + i,col);
                     }
                 }
                 offs ++;
             }
             X += sx + space;
             if(pr_flag)
                 X -= rOffs[ch];
         }
     }
 }
References XGR_Screen::flags, XFNT_TAB_SIZE, XGR_FontTable, XGR_HICOLOR, XGR_Obj, XGR_SetPixel16Fast(), and XGR_SetPixelFast().
XGR_OutText()
void XGR_OutText (int x, int y, int col, void * text, int font, int hspace, int vspace, int pr_flag)
 {
     int sx,sy,hcol_flag = 0;
     int i,j,s,ch,n,count,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     char* p = (char*)XGR_FontTable[font] -> data;
     unsigned char* buf = (unsigned char*)text;
     sx = XGR_FontTable[font] -> SizeX;
     sy = XGR_FontTable[font] -> SizeY;
     if(XGR_Obj.flags & XGR_HICOLOR){
         hcol_flag = 1;
     }
     for(s = 0; s < sz; s ++){
         if(buf[s] != '\r'){
             if(buf[s] == '\n'){
                 X = 0;
                 Y += sy + vspace;
             }
             else {
                 if(buf[s] == '\t'){
                     ch = ' ';
                     count = XFNT_TAB_SIZE;
                 }
                 else {
                     ch = buf[s];
                     count = 1;
                 }
                 for(n = 0; n < count; n ++){
                     if(pr_flag)
                         X -= lOffs[ch];
                     offs = sy * ch;
                     for(i = 0; i < sy; i ++){
                         for(j = 0; j < sx; j ++){
                             if(p[offs] & (1 << (7 - j))){
                                 if(hcol_flag)
                                     XGR_SetPixel16Fast(x + X + j,y + Y + i,col);
                                 else
                                     XGR_SetPixelFast(x + X + j,y + Y + i,col);
                             }
                         }
                         offs ++;
                     }
                     X += sx + hspace;
                     if(pr_flag)
                         X -= rOffs[ch];
                 }
             }
         }
     }
 }
References XGR_Screen::flags, XFNT_TAB_SIZE, XGR_FontTable, XGR_HICOLOR, XGR_Obj, XGR_SetPixel16Fast(), and XGR_SetPixelFast().
Referenced by XGR_Mouse::PutPrompt().
XGR_StrLen()
int XGR_StrLen (void * str, int font, int space)
 {
     unsigned char* p = (unsigned char*)str;
     int i,s,sx,sz = strlen((char*)str),len = 0,ch = 0,count;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     sx = XGR_FontTable[font] -> SizeX;
     if(!sz) return 0;
     for(s = 0; s < sz; s ++){
         if(p[s] == '\t'){
             ch = ' ';
             count = XFNT_TAB_SIZE;
         }
         else {
             ch = p[s];
             count = 1;
         }
         for(i = 0; i < count; i ++)
             len += sx - (lOffs[ch] + rOffs[ch]) + space;
     }
     return len;
 }
References XFNT_TAB_SIZE, and XGR_FontTable.
XGR_TextHeight()
int XGR_TextHeight (void * text, int font, int vspace)
 {
     unsigned char* p = (unsigned char*)text;
     int s,sy,sz = strlen((char*)text),len = 0;
     if(!sz) return 0;
     sy = XGR_FontTable[font] -> SizeY;
     len =sy;
     for(s = 0; s < sz; s ++){
         if(p[s] == '\n')
             len += sy + vspace;
     }
     return len;
 }
References XGR_FontTable.
Referenced by XGR_MousePromptData::init().
XGR_TextWidth()
int XGR_TextWidth (void * text, int font, int hspace)
 {
     unsigned char* p = (unsigned char*)text;
     int i,sx,s,sz = strlen((char*)text),len = 0,max_len = 0,ch = 0,count;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     sx = XGR_FontTable[font] -> SizeX;
     if(!sz) return 0;
     for(s = 0; s < sz; s ++){
         if(p[s] == '\n'){
             if(len > max_len) max_len = len;
             len = 0;
         }
         else {
             if(p[s] != '\r'){
                 if(p[s] == '\t'){
                     ch = ' ';
                     count = XFNT_TAB_SIZE;
                 }
                 else {
                     ch = p[s];
                     count = 1;
                 }
                 for(i = 0; i < count; i ++)
                     len += sx - (lOffs[ch] + rOffs[ch]) + hspace;
             }
         }
     }
     if(len > max_len) max_len = len;
     return max_len;
 }
References XFNT_TAB_SIZE, and XGR_FontTable.
Referenced by XGR_MousePromptData::init().
Variable Documentation
XGR_FontTable
XGR_Font** XGR_FontTable = NULL
Referenced by XFNT_Prepare(), XGR_OutString(), XGR_OutText(), XGR_StrLen(), XGR_TextHeight(), and XGR_TextWidth().