Vangers: lib/xgraph/xgraph.h File Reference
xgraph.h File Reference
#include "xglobal.h"
Classes
struct XGR_Font
struct XGR_Pal64K
struct XGR_Screen
struct XGR_MousePromptData
struct XGR_MousePromptScreen
struct XGR_MouseButton
struct XGR_Mouse
Macros
#define XGR_RGB64K(r, g, b) (((r) << XGR_SHIFT_R) + ((g) << XGR_SHIFT_G) + ((b) << XGR_SHIFT_B))
#define XGR_64KR(c) (((c) >> XGR_SHIFT_R) & XGR_COLOR_MASK_R)
#define XGR_64KG(c) (((c) >> XGR_SHIFT_G) & XGR_COLOR_MASK_G)
#define XGR_64KB(c) (((c) >> XGR_SHIFT_B) & XGR_COLOR_MASK_B)
#define XGR_HIDDEN_FON 0x01
#define XGR_BLACK_FON 0x02
#define XGR_CLIPPED 0x04
#define XGR_NOCLIP 0x08
#define XGR_BOTTOM_UP 0x10
#define XGR_FILLED 0x00
#define XGR_OUTLINED 0x01
#define XGR_NUM_FONTS 0x02
#define XGR_FONT0_8x16 0
#define XGR_FONT0_8x8 1
#define XGR_EXCLUSIVE 0x01
#define XGR_REINIT 0x02
#define XGR_PALETTE 0x04
#define XGR_INIT 0x08
#define XGR_HICOLOR 0x10
#define XGR_CLIP_PUTSPR 0x00
#define XGR_CLIP_ALL 0x01
#define XGR_PROMPT_ACTIVE 0x01
#define XGR_PROMPT_MEM_ALLOC 0x02
#define XGM_LEFT_BUTTON 0x01
#define XGM_RIGHT_BUTTON 0x02
#define XGM_MIDDLE_BUTTON 0x03
#define XGM_INIT 0x01
#define XGM_VISIBLE 0x02
#define XGM_AUTOCLIP 0x04
#define XGM_PROMPT_ACTIVE 0x08
#define XGM_HICOLOR 0x10
#define XGM_DISABLE_PROMPT 0x20
#define XGM_NONE 0
#define XGM_PLAY_ONCE 1
#define XGM_PLAY_INFINITE 2
#define XGM_CURSOR_TIMER 1333
#define XGR_Init(x, y, fl) XGR_Obj.init(x,y,fl)
#define XGR_ReInit(x, y, fl) XGR_Obj.init(x,y,fl | XGR_REINIT)
#define XGR_Finit() XGR_Obj.finit()
#define XGR_SetClip(left, top, right, bottom) XGR_Obj.set_clip(left,top,right,bottom)
#define XGR_GetClip(left, top, right, bottom) XGR_Obj.get_clip(left,top,right,bottom)
#define XGR_SetClipMode(mode) XGR_Obj.set_clip_mode(mode)
#define XGR_Flush(x, y, sx, sy) XGR_Obj.flush(x,y,sx,sy)
#define XGR_Flip() XGR_Obj.flip()
#define XGR_Fill(col) XGR_Obj.fill(col)
#define XGR_Erase(x, y, sx, sy, col) XGR_Obj.erase(x,y,sx,sy,col)
#define XGR_Rectangle(x, y, sx, sy, outcol, incol, mode) XGR_Obj.rectangle(x,y,sx,sy,outcol,incol,mode)
#define XGR_SetPixel(x, y, col) XGR_Obj.setpixel(x,y,col)
#define XGR_GetPixel(x, y) XGR_Obj.getpixel(x,y)
#define XGR_Line(x1, y1, x2, y2, col) XGR_Obj.line(x1,y1,x2,y2,col)
#define XGR_LineTo(x, y, len, dir, col) XGR_Obj.lineto(x,y,len,dir,col)
#define XGR_SetPal(ptr, st, cnt) XGR_Obj.setpal(ptr,st,cnt)
#define XGR_GetPal(ptr) XGR_Obj.getpal(ptr)
#define XGR_PutSpr(x, y, sx, sy, p, mode) XGR_Obj.putspr(x,y,sx,sy,p,mode)
#define XGR_GetSpr(x, y, sx, sy, p) XGR_Obj.getspr(x,y,sx,sy,p)
#define XGR_WriteScreen(bmp_name, pal_name) XGR_Obj.capture_screen(bmp_name,pal_name)
#define XGR_PutSpr16(x, y, sx, sy, p, mode) XGR_Obj.putspr16(x,y,sx,sy,p,mode)
#define XGR_GetSpr16(x, y, sx, sy, p) XGR_Obj.getspr16(x,y,sx,sy,p)
#define XGR_PutSpr16a(x, y, sx, sy, p, mode, alpha) XGR_Obj.putspr16a(x,y,sx,sy,p,mode,alpha)
#define XGR_PutSpr16ap(x, y, sx, sy, p, mode, alpha) XGR_Obj.putspr16ap(x,y,sx,sy,p,mode,alpha)
#define XGR_Erase16(x, y, sx, sy, col) XGR_Obj.erase16(x,y,sx,sy,col)
#define XGR_Fill16(col) XGR_Obj.fill16(col)
#define XGR_SetPixel16(x, y, col) XGR_Obj.setpixel16(x,y,col)
#define XGR_Line16(x1, y1, x2, y2, col) XGR_Obj.line16(x1,y1,x2,y2,col)
#define XGR_LineTo16(x, y, len, dir, col) XGR_Obj.lineto16(x,y,len,dir,col)
#define XGR_Rectangle16(x, y, sx, sy, outcol, incol, mode) XGR_Obj.rectangle16(x,y,sx,sy,outcol,incol,mode)
#define XGR_MouseInit(x, y, sx, sy, num, p) XGR_MouseObj.Init(x,y,sx,sy,num,p)
#define XGR_MouseSetCursor(sx, sy, num, p) XGR_MouseObj.SetCursor(sx,sy,num,p)
#define XGR_MouseSetSpot(x, y) XGR_MouseObj.SetSpot(x,y)
#define XGR_MouseInitPos(x, y) XGR_MouseObj.InitPos(x,y)
#define XGR_MouseVisible() XGR_MouseObj.Visible()
#define XGR_MouseCheckRedraw(x, y, sx, sy) XGR_MouseObj.CheckRedraw(x,y,sx,sy)
#define XGR_MouseNextFrame() XGR_MouseObj.NextFrame()
#define XGR_MouseSetSeq(beg, end, mode, delta) XGR_MouseObj.SetSeq(beg,end,mode,delta)
#define XGR_MouseSetAlphaSeq(beg, end, mode, delta) XGR_MouseObj.SetAlphaSeq(beg,end,mode,delta)
#define XGR_MouseRedraw() XGR_MouseObj.Redraw()
#define XGR_MousePutFrame() XGR_MouseObj.PutFrame()
#define XGR_MousePutFon() XGR_MouseObj.PutFon()
#define XGR_MouseGetFon() XGR_MouseObj.GetFon()
#define XGR_MouseSetPressHandler(bt, p) XGR_MouseObj.SetPressHandler(bt,p)
#define XGR_MouseSetUnPressHandler(bt, p) XGR_MouseObj.SetUnPressHandler(bt,p)
#define XGR_MouseSetDblHandler(bt, p) XGR_MouseObj.SetDblHandler(bt,p)
#define XGR_MouseSetMoveHandler(p) XGR_MouseObj.SetMoveHandler(p)
#define XGR_MousePress(bt, fl, x, y) XGR_MouseObj.Press(bt,fl,x,y)
#define XGR_MouseUnPress(bt, fl, x, y) XGR_MouseObj.UnPress(bt,fl,x,y)
#define XGR_MouseDblClick(bt, fl, x, y) XGR_MouseObj.DblClick(bt,fl,x,y)
#define XGR_MouseMove(fl, x, y) XGR_MouseObj.Move(fl,x,y)
#define XGR_MouseHide() XGR_MouseObj.Hide()
#define XGR_MouseShow() XGR_MouseObj.Show()
#define XGR_MouseSetPos(x, y) XGR_MouseObj.SetPos(x,y)
#define XGR_MouseSetPromptData(p) XGR_MouseObj.SetPromptData(p)
#define XGR_MouseCurFrame XGR_MouseObj.CurFrame
#define XGR_MouseNumFrames XGR_MouseObj.NumFrames
#define XGR_MAXX xgrScreenSizeX
#define XGR_MAXY xgrScreenSizeY
#define XGR_VIDEOBUF XGR_Obj.ScreenBuf
Typedefs
typedef void(* XGR_OutTextHandler) (int x, int y, int col, void *text, int font, int hspace, int vspace)
typedef int(* XGR_TextWidthHandler) (void *text, int font, int hspace)
typedef int(* XGR_TextHeightHandler) (void *text, int font, int vspace)
typedef void(* XGR_MOUSE_HANDLER) (int, int, int)
Enumerations
enum XGR_LINEDIR { XGR_LEFT, XGR_TOP, XGR_RIGHT, XGR_BOTTOM }
Functions
void XGR_OutString (int x, int y, int col, void *str, int font=0, int space=1, int pr_flag=1)
int XGR_StrLen (void *str, int font=0, int space=1)
void XGR_OutText (int x, int y, int col, void *text, int font=0, int hspace=1, int vspace=1, int pr_flag=1)
int XGR_TextHeight (void *text, int font=0, int hspace=1)
int XGR_TextWidth (void *text, int font=0, int vspace=1)
unsigned char * XGR_GetVideoLine (int y)
void XGR_SetPixelFast (int x, int y, int col)
void XGR_SetPixel16Fast (int x, int y, int col)
void XGR_PrepareSprite (int sx, int sy, void *dst_buf, void *src_buf, XGR_Pal64K *pal)
void XGR_SetTextOutFnc (XGR_OutTextHandler p)
void XGR_SetTextXFnc (XGR_TextWidthHandler p)
void XGR_SetTextYFnc (XGR_TextHeightHandler p)
Variables
int xgrScreenSizeX
int xgrScreenSizeY
XGR_Screen XGR_Obj
XGR_Mouse XGR_MouseObj
int XGR_MASK_R
int XGR_MASK_G
int XGR_MASK_B
int XGR_SHIFT_R
int XGR_SHIFT_G
int XGR_SHIFT_B
int XGR_COLOR_MASK_R
int XGR_COLOR_MASK_G
int XGR_COLOR_MASK_B
const char * XGraphWndID
int XGR_HighColorMode
int UI_OR_GAME
Macro Definition Documentation
XGM_AUTOCLIP
#define XGM_AUTOCLIP 0x04
XGM_CURSOR_TIMER
#define XGM_CURSOR_TIMER 1333
XGM_DISABLE_PROMPT
#define XGM_DISABLE_PROMPT 0x20
XGM_HICOLOR
#define XGM_HICOLOR 0x10
XGM_INIT
#define XGM_INIT 0x01
XGM_LEFT_BUTTON
#define XGM_LEFT_BUTTON 0x01
XGM_MIDDLE_BUTTON
#define XGM_MIDDLE_BUTTON 0x03
XGM_NONE
#define XGM_NONE 0
XGM_PLAY_INFINITE
#define XGM_PLAY_INFINITE 2
XGM_PLAY_ONCE
#define XGM_PLAY_ONCE 1
XGM_PROMPT_ACTIVE
#define XGM_PROMPT_ACTIVE 0x08
XGM_RIGHT_BUTTON
#define XGM_RIGHT_BUTTON 0x02
XGM_VISIBLE
#define XGM_VISIBLE 0x02
XGR_64KB
#define XGR_64KB (c) (((c) >> XGR_SHIFT_B) & XGR_COLOR_MASK_B)
XGR_64KG
#define XGR_64KG (c) (((c) >> XGR_SHIFT_G) & XGR_COLOR_MASK_G)
XGR_64KR
#define XGR_64KR (c) (((c) >> XGR_SHIFT_R) & XGR_COLOR_MASK_R)
XGR_BLACK_FON
#define XGR_BLACK_FON 0x02
XGR_BOTTOM_UP
#define XGR_BOTTOM_UP 0x10
XGR_CLIP_ALL
#define XGR_CLIP_ALL 0x01
XGR_CLIP_PUTSPR
#define XGR_CLIP_PUTSPR 0x00
XGR_CLIPPED
#define XGR_CLIPPED 0x04
XGR_Erase
#define XGR_Erase (x, y, sx, sy, col) XGR_Obj.erase(x,y,sx,sy,col)
XGR_Erase16
#define XGR_Erase16 (x, y, sx, sy, col) XGR_Obj.erase16(x,y,sx,sy,col)
XGR_EXCLUSIVE
#define XGR_EXCLUSIVE 0x01
XGR_Fill
#define XGR_Fill (col) XGR_Obj.fill(col)
XGR_Fill16
#define XGR_Fill16 (col) XGR_Obj.fill16(col)
XGR_FILLED
#define XGR_FILLED 0x00
XGR_Finit
#define XGR_Finit () XGR_Obj.finit()
XGR_Flip
#define XGR_Flip () XGR_Obj.flip()
XGR_Flush
#define XGR_Flush (x, y, sx, sy) XGR_Obj.flush(x,y,sx,sy)
XGR_FONT0_8x16
#define XGR_FONT0_8x16 0
XGR_FONT0_8x8
#define XGR_FONT0_8x8 1
XGR_GetClip
#define XGR_GetClip (left, top, right, bottom) XGR_Obj.get_clip(left,top,right,bottom)
XGR_GetPal
#define XGR_GetPal (ptr) XGR_Obj.getpal(ptr)
XGR_GetPixel
#define XGR_GetPixel (x, y) XGR_Obj.getpixel(x,y)
XGR_GetSpr
#define XGR_GetSpr (x, y, sx, sy, p) XGR_Obj.getspr(x,y,sx,sy,p)
XGR_GetSpr16
#define XGR_GetSpr16 (x, y, sx, sy, p) XGR_Obj.getspr16(x,y,sx,sy,p)
XGR_HICOLOR
#define XGR_HICOLOR 0x10
XGR_HIDDEN_FON
#define XGR_HIDDEN_FON 0x01
XGR_INIT
#define XGR_INIT 0x08
XGR_Init
#define XGR_Init (x, y, fl) XGR_Obj.init(x,y,fl)
XGR_Line
#define XGR_Line (x1, y1, x2, y2, col) XGR_Obj.line(x1,y1,x2,y2,col)
XGR_Line16
#define XGR_Line16 (x1, y1, x2, y2, col) XGR_Obj.line16(x1,y1,x2,y2,col)
XGR_LineTo
#define XGR_LineTo (x, y, len, dir, col) XGR_Obj.lineto(x,y,len,dir,col)
XGR_LineTo16
#define XGR_LineTo16 (x, y, len, dir, col) XGR_Obj.lineto16(x,y,len,dir,col)
XGR_MAXX
#define XGR_MAXX xgrScreenSizeX
XGR_MAXY
#define XGR_MAXY xgrScreenSizeY
XGR_MouseCheckRedraw
#define XGR_MouseCheckRedraw (x, y, sx, sy) XGR_MouseObj.CheckRedraw(x,y,sx,sy)
XGR_MouseCurFrame
#define XGR_MouseCurFrame XGR_MouseObj.CurFrame
XGR_MouseDblClick
#define XGR_MouseDblClick (bt, fl, x, y) XGR_MouseObj.DblClick(bt,fl,x,y)
XGR_MouseGetFon
#define XGR_MouseGetFon () XGR_MouseObj.GetFon()
XGR_MouseHide
#define XGR_MouseHide () XGR_MouseObj.Hide()
XGR_MouseInit
#define XGR_MouseInit (x, y, sx, sy, num, p) XGR_MouseObj.Init(x,y,sx,sy,num,p)
XGR_MouseInitPos
#define XGR_MouseInitPos (x, y) XGR_MouseObj.InitPos(x,y)
XGR_MouseMove
#define XGR_MouseMove (fl, x, y) XGR_MouseObj.Move(fl,x,y)
XGR_MouseNextFrame
#define XGR_MouseNextFrame () XGR_MouseObj.NextFrame()
XGR_MouseNumFrames
#define XGR_MouseNumFrames XGR_MouseObj.NumFrames
XGR_MousePress
#define XGR_MousePress (bt, fl, x, y) XGR_MouseObj.Press(bt,fl,x,y)
XGR_MousePutFon
#define XGR_MousePutFon () XGR_MouseObj.PutFon()
XGR_MousePutFrame
#define XGR_MousePutFrame () XGR_MouseObj.PutFrame()
XGR_MouseRedraw
#define XGR_MouseRedraw () XGR_MouseObj.Redraw()
XGR_MouseSetAlphaSeq
#define XGR_MouseSetAlphaSeq (beg, end, mode, delta) XGR_MouseObj.SetAlphaSeq(beg,end,mode,delta)
XGR_MouseSetCursor
#define XGR_MouseSetCursor (sx, sy, num, p) XGR_MouseObj.SetCursor(sx,sy,num,p)
XGR_MouseSetDblHandler
#define XGR_MouseSetDblHandler (bt, p) XGR_MouseObj.SetDblHandler(bt,p)
XGR_MouseSetMoveHandler
#define XGR_MouseSetMoveHandler (p) XGR_MouseObj.SetMoveHandler(p)
XGR_MouseSetPos
#define XGR_MouseSetPos (x, y) XGR_MouseObj.SetPos(x,y)
XGR_MouseSetPressHandler
#define XGR_MouseSetPressHandler (bt, p) XGR_MouseObj.SetPressHandler(bt,p)
XGR_MouseSetPromptData
#define XGR_MouseSetPromptData (p) XGR_MouseObj.SetPromptData(p)
XGR_MouseSetSeq
#define XGR_MouseSetSeq (beg, end, mode, delta) XGR_MouseObj.SetSeq(beg,end,mode,delta)
XGR_MouseSetSpot
#define XGR_MouseSetSpot (x, y) XGR_MouseObj.SetSpot(x,y)
XGR_MouseSetUnPressHandler
#define XGR_MouseSetUnPressHandler (bt, p) XGR_MouseObj.SetUnPressHandler(bt,p)
XGR_MouseShow
#define XGR_MouseShow () XGR_MouseObj.Show()
XGR_MouseUnPress
#define XGR_MouseUnPress (bt, fl, x, y) XGR_MouseObj.UnPress(bt,fl,x,y)
XGR_MouseVisible
#define XGR_MouseVisible () XGR_MouseObj.Visible()
XGR_NOCLIP
#define XGR_NOCLIP 0x08
XGR_NUM_FONTS
#define XGR_NUM_FONTS 0x02
XGR_OUTLINED
#define XGR_OUTLINED 0x01
XGR_PALETTE
#define XGR_PALETTE 0x04
XGR_PROMPT_ACTIVE
#define XGR_PROMPT_ACTIVE 0x01
XGR_PROMPT_MEM_ALLOC
#define XGR_PROMPT_MEM_ALLOC 0x02
XGR_PutSpr
#define XGR_PutSpr (x, y, sx, sy, p, mode) XGR_Obj.putspr(x,y,sx,sy,p,mode)
XGR_PutSpr16
#define XGR_PutSpr16 (x, y, sx, sy, p, mode) XGR_Obj.putspr16(x,y,sx,sy,p,mode)
XGR_PutSpr16a
#define XGR_PutSpr16a (x, y, sx, sy, p, mode, alpha) XGR_Obj.putspr16a(x,y,sx,sy,p,mode,alpha)
XGR_PutSpr16ap
#define XGR_PutSpr16ap (x, y, sx, sy, p, mode, alpha) XGR_Obj.putspr16ap(x,y,sx,sy,p,mode,alpha)
XGR_Rectangle
#define XGR_Rectangle (x, y, sx, sy, outcol, incol, mode) XGR_Obj.rectangle(x,y,sx,sy,outcol,incol,mode)
XGR_Rectangle16
#define XGR_Rectangle16 (x, y, sx, sy, outcol, incol, mode) XGR_Obj.rectangle16(x,y,sx,sy,outcol,incol,mode)
XGR_REINIT
#define XGR_REINIT 0x02
XGR_ReInit
#define XGR_ReInit (x, y, fl) XGR_Obj.init(x,y,fl | XGR_REINIT)
XGR_RGB64K
#define XGR_RGB64K (r, g, b) (((r) << XGR_SHIFT_R) + ((g) << XGR_SHIFT_G) + ((b) << XGR_SHIFT_B))
XGR_SetClip
#define XGR_SetClip (left, top, right, bottom) XGR_Obj.set_clip(left,top,right,bottom)
XGR_SetClipMode
#define XGR_SetClipMode (mode) XGR_Obj.set_clip_mode(mode)
XGR_SetPal
#define XGR_SetPal (ptr, st, cnt) XGR_Obj.setpal(ptr,st,cnt)
XGR_SetPixel
#define XGR_SetPixel (x, y, col) XGR_Obj.setpixel(x,y,col)
XGR_SetPixel16
#define XGR_SetPixel16 (x, y, col) XGR_Obj.setpixel16(x,y,col)
XGR_VIDEOBUF
#define XGR_VIDEOBUF XGR_Obj.ScreenBuf
XGR_WriteScreen
#define XGR_WriteScreen (bmp_name, pal_name) XGR_Obj.capture_screen(bmp_name,pal_name)
Typedef Documentation
XGR_MOUSE_HANDLER
typedef void(* XGR_MOUSE_HANDLER) (int, int, int)
XGR_OutTextHandler
typedef void(* XGR_OutTextHandler) (int x, int y, int col, void *text, int font, int hspace, int vspace)
XGR_TextHeightHandler
typedef int(* XGR_TextHeightHandler) (void *text, int font, int vspace)
XGR_TextWidthHandler
typedef int(* XGR_TextWidthHandler) (void *text, int font, int hspace)
Enumeration Type Documentation
XGR_LINEDIR
enum XGR_LINEDIR
Enumerator
XGR_LEFT
XGR_TOP
XGR_RIGHT
XGR_BOTTOM
 {
     XGR_LEFT,
     XGR_TOP,
     XGR_RIGHT,
     XGR_BOTTOM
 };
Function Documentation
XGR_GetVideoLine()
unsigned char* XGR_GetVideoLine (int y) inline
 { return (XGR_Obj.ScreenBuf + XGR_Obj.yOffsTable[y]); }
References XGR_Screen::ScreenBuf, XGR_Obj, and XGR_Screen::yOffsTable.
Referenced by arbitrary_shadowing_line(), ExplosionObject::DrawQuant(), ShowImageRTO::Init(), putMapPixel(), ExplosionObject::Quant(), and setMapPixel().
XGR_OutString()
void XGR_OutString (int x, int y, int col, void * str, int font = 0, int space = 1, int pr_flag = 1)
 {
     int sx,sy,hcol_flag = 0;
     int i,j,s,ch,n,count,offs = 0,sz = strlen((char*)str),X = 0;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     char* p = (char*)XGR_FontTable[font] -> data;
     unsigned char* buf = (unsigned char*)str;
     sx = XGR_FontTable[font] -> SizeX;
     sy = XGR_FontTable[font] -> SizeY;
     if(XGR_Obj.flags & XGR_HICOLOR) hcol_flag = 1;
     for(s = 0; s < sz; s ++){
         if(buf[s] == '\t'){
             ch = ' ';
             count = XFNT_TAB_SIZE;
         }
         else {
             ch = buf[s];
             count = 1;
         }
         for(n = 0; n < count; n ++){
             if(pr_flag)
                 X -= lOffs[ch];
             offs = sy * ch;
             for(i = 0; i < sy; i ++){
                 for(j = 0; j < sx; j ++){
                     if(p[offs] & (1 << (7 - j))){
                         if(hcol_flag)
                             XGR_SetPixel16Fast(x + X + j,y + i,col);
                         else
                             XGR_SetPixelFast(x + X + j,y + i,col);
                     }
                 }
                 offs ++;
             }
             X += sx + space;
             if(pr_flag)
                 X -= rOffs[ch];
         }
     }
 }
References XGR_Screen::flags, XFNT_TAB_SIZE, XGR_FontTable, XGR_HICOLOR, XGR_Obj, XGR_SetPixel16Fast(), and XGR_SetPixelFast().
XGR_OutText()
void XGR_OutText (int x, int y, int col, void * text, int font = 0, int hspace = 1, int vspace = 1, int pr_flag = 1)
 {
     int sx,sy,hcol_flag = 0;
     int i,j,s,ch,n,count,offs = 0,sz = strlen((char*)text),X = 0,Y = 0;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     char* p = (char*)XGR_FontTable[font] -> data;
     unsigned char* buf = (unsigned char*)text;
     sx = XGR_FontTable[font] -> SizeX;
     sy = XGR_FontTable[font] -> SizeY;
     if(XGR_Obj.flags & XGR_HICOLOR){
         hcol_flag = 1;
     }
     for(s = 0; s < sz; s ++){
         if(buf[s] != '\r'){
             if(buf[s] == '\n'){
                 X = 0;
                 Y += sy + vspace;
             }
             else {
                 if(buf[s] == '\t'){
                     ch = ' ';
                     count = XFNT_TAB_SIZE;
                 }
                 else {
                     ch = buf[s];
                     count = 1;
                 }
                 for(n = 0; n < count; n ++){
                     if(pr_flag)
                         X -= lOffs[ch];
                     offs = sy * ch;
                     for(i = 0; i < sy; i ++){
                         for(j = 0; j < sx; j ++){
                             if(p[offs] & (1 << (7 - j))){
                                 if(hcol_flag)
                                     XGR_SetPixel16Fast(x + X + j,y + Y + i,col);
                                 else
                                     XGR_SetPixelFast(x + X + j,y + Y + i,col);
                             }
                         }
                         offs ++;
                     }
                     X += sx + hspace;
                     if(pr_flag)
                         X -= rOffs[ch];
                 }
             }
         }
     }
 }
References XGR_Screen::flags, XFNT_TAB_SIZE, XGR_FontTable, XGR_HICOLOR, XGR_Obj, XGR_SetPixel16Fast(), and XGR_SetPixelFast().
Referenced by XGR_Mouse::PutPrompt().
XGR_PrepareSprite()
void XGR_PrepareSprite (int sx, int sy, void * dst_buf, void * src_buf, XGR_Pal64K * pal)
 {
     int i,j,index = 0;
     unsigned char* src = (unsigned char*)src_buf;
     unsigned short* dst = (unsigned short*)dst_buf;
     for(i = 0; i < sy; i ++){
         for(j = 0; j < sx; j ++){
             dst[index] = pal -> data[src[index]];
             index ++;
         }
     }
 }
XGR_SetPixel16Fast()
void XGR_SetPixel16Fast (int x, int y, int col) inline
{
     unsigned short* p = (unsigned short*)(XGR_Obj.ScreenBuf + XGR_Obj.yOffsTable[y]);
     p[x] = col;
 }
References XGR_Screen::ScreenBuf, XGR_Obj, and XGR_Screen::yOffsTable.
Referenced by XGR_OutString(), and XGR_OutText().
XGR_SetPixelFast()
void XGR_SetPixelFast (int x, int y, int col) inline
 { XGR_Obj.ScreenBuf[XGR_Obj.yOffsTable[y] + x] = col; }
References XGR_Screen::ScreenBuf, XGR_Obj, and XGR_Screen::yOffsTable.
Referenced by aciPutSpr32(), TargetParticleType::aQuant(), TargetParticleType::aQuant2(), ParticleObject::DrawQuant(), WaterParticleObject::DrawQuant(), HordeObject::DrawQuant(), TargetParticleType::sQuant(), TargetParticleType::sQuant2(), XGR_OutString(), and XGR_OutText().
XGR_SetTextOutFnc()
void XGR_SetTextOutFnc (XGR_OutTextHandler p)
 {
     XGR_TextOutFnc = p;
 }
References XGR_TextOutFnc.
XGR_SetTextXFnc()
void XGR_SetTextXFnc (XGR_TextWidthHandler p)
 {
     XGR_TextXFnc = p;
 }
References XGR_TextXFnc.
XGR_SetTextYFnc()
void XGR_SetTextYFnc (XGR_TextHeightHandler p)
 {
     XGR_TextYFnc = p;
 }
References XGR_TextYFnc.
XGR_StrLen()
int XGR_StrLen (void * str, int font = 0, int space = 1)
 {
     unsigned char* p = (unsigned char*)str;
     int i,s,sx,sz = strlen((char*)str),len = 0,ch = 0,count;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     sx = XGR_FontTable[font] -> SizeX;
     if(!sz) return 0;
     for(s = 0; s < sz; s ++){
         if(p[s] == '\t'){
             ch = ' ';
             count = XFNT_TAB_SIZE;
         }
         else {
             ch = p[s];
             count = 1;
         }
         for(i = 0; i < count; i ++)
             len += sx - (lOffs[ch] + rOffs[ch]) + space;
     }
     return len;
 }
References XFNT_TAB_SIZE, and XGR_FontTable.
XGR_TextHeight()
int XGR_TextHeight (void * text, int font = 0, int hspace = 1)
 {
     unsigned char* p = (unsigned char*)text;
     int s,sy,sz = strlen((char*)text),len = 0;
     if(!sz) return 0;
     sy = XGR_FontTable[font] -> SizeY;
     len =sy;
     for(s = 0; s < sz; s ++){
         if(p[s] == '\n')
             len += sy + vspace;
     }
     return len;
 }
References XGR_FontTable.
Referenced by XGR_MousePromptData::init().
XGR_TextWidth()
int XGR_TextWidth (void * text, int font = 0, int vspace = 1)
 {
     unsigned char* p = (unsigned char*)text;
     int i,sx,s,sz = strlen((char*)text),len = 0,max_len = 0,ch = 0,count;
     unsigned char* lOffs = XGR_FontTable[font] -> LeftOffs;
     unsigned char* rOffs = XGR_FontTable[font] -> RightOffs;
     sx = XGR_FontTable[font] -> SizeX;
     if(!sz) return 0;
     for(s = 0; s < sz; s ++){
         if(p[s] == '\n'){
             if(len > max_len) max_len = len;
             len = 0;
         }
         else {
             if(p[s] != '\r'){
                 if(p[s] == '\t'){
                     ch = ' ';
                     count = XFNT_TAB_SIZE;
                 }
                 else {
                     ch = p[s];
                     count = 1;
                 }
                 for(i = 0; i < count; i ++)
                     len += sx - (lOffs[ch] + rOffs[ch]) + hspace;
             }
         }
     }
     if(len > max_len) max_len = len;
     return max_len;
 }
References XFNT_TAB_SIZE, and XGR_FontTable.
Referenced by XGR_MousePromptData::init().
Variable Documentation
UI_OR_GAME
int UI_OR_GAME extern
Referenced by vrtMap::init().
XGR_COLOR_MASK_B
int XGR_COLOR_MASK_B extern
XGR_COLOR_MASK_G
int XGR_COLOR_MASK_G extern
XGR_COLOR_MASK_R
int XGR_COLOR_MASK_R extern
XGR_HighColorMode
int XGR_HighColorMode extern
XGR_MASK_B
int XGR_MASK_B extern
Referenced by XGR_Screen::putspr16a(), and XGR_Screen::putspr16ap().
XGR_MASK_G
int XGR_MASK_G extern
Referenced by XGR_Screen::putspr16a(), and XGR_Screen::putspr16ap().
XGR_MASK_R
int XGR_MASK_R extern
Referenced by XGR_Screen::putspr16a(), and XGR_Screen::putspr16ap().
XGR_MouseObj
XGR_Mouse XGR_MouseObj extern
Referenced by iScreenDispatcher::aci_move_screen(), acsQuant(), CursorAnim(), XGR_Screen::flip(), aciScreenDispatcher::FlushEvents(), iFinitQuant(), iHandleExtEvent(), XGR_Screen::init(), actIntDispatcher::init(), actIntDispatcher::inv_mouse_imove_quant(), actIntDispatcher::inv_mouse_move_quant(), actIntDispatcher::KeyQuant(), iScreenDispatcher::move_screen(), iScreen::prepare(), aciScreenInputField::Quant(), actIntDispatcher::redraw(), and XGR_MouseFnc().
XGR_Obj
XGR_Screen XGR_Obj extern
Referenced by creat_poster(), WaveProcess::Deform(), VangerUnit::DrawQuant(), ActionDispatcher::DrawResource(), ibsout(), MainMenuRTO::Init(), XGR_Mouse::Init(), iSetFullscreen(), shotFlush(), PassageImageType::Show(), XGR_GetVideoLine(), XGR_OutString(), XGR_OutText(), XGR_SetPixel16Fast(), and XGR_SetPixelFast().
XGR_SHIFT_B
int XGR_SHIFT_B extern
XGR_SHIFT_G
int XGR_SHIFT_G extern
XGR_SHIFT_R
int XGR_SHIFT_R extern
XGraphWndID
const char* XGraphWndID extern
Referenced by xtInitApplication().
xgrScreenSizeX
int xgrScreenSizeX extern
Referenced by XGR_Screen::init().
xgrScreenSizeY
int xgrScreenSizeY extern
Referenced by XGR_Screen::init().