Vangers: lib/xtool/xmath/xmath.h File Reference
xmath.h File Reference
#include <math.h>
#include <iostream>
#include <cmath>
Classes
class RandomGenerator
class Vect2f
class Vect2i
class Vect2s
class Mat2f
class MatX2f
class Vect3f
class Vect3d
class Mat3f
class Mat3d
class MatXf
class MatXd
class QuatF
class QuatD
class Se3f
class Se3d
class Vect4f
class Mat4f
Macros
#define M_PI 3.14159265358979323846f
#define xm_inline inline
#define __ROUND__
#define NOMINMAX
#define G2R(x) ((x)*M_PI/180.f)
#define R2G(x) ((x)*180.f/M_PI)
#define __swap__(x, y) { float t = y; y = x; x = t; }
Enumerations
enum eAxis { X_AXIS, Y_AXIS, Z_AXIS, W_AXIS }
Functions
xm_inline int round (double x)
xm_inline int round (float x)
template<class T >
xm_inline T sqr (const T &x)
template<class T >
xm_inline int SIGN (const T &x)
xm_inline double SIGN (double a, double b)
xm_inline float SIGN (float a, float b)
xm_inline unsigned random (unsigned m)
xm_inline float frnd (float x)
xm_inline float fabsRnd (float x)
xm_inline int min (int x, int y)
xm_inline float min (float x, float y)
xm_inline double min (double x, double y)
xm_inline int max (int x, int y)
xm_inline float max (float x, float y)
xm_inline double max (double x, double y)
template<class T >
xm_inline T min (const T &a, const T &b, const T &c)
template<class T >
xm_inline T max (const T &a, const T &b, const T &c)
xm_inline int mina (int x, int y)
xm_inline int mina (int x, int y, int z)
xm_inline int maxa (int x, int y)
xm_inline int maxa (int x, int y, int z)
xm_inline double mina (double x, double y)
xm_inline double mina (double x, double y, double z)
xm_inline double maxa (double x, double y)
xm_inline double maxa (double x, double y, double z)
xm_inline int minAbs (int x, int y)
xm_inline int minAbs (int x, int y, int z)
xm_inline int maxAbs (int x, int y)
xm_inline int maxAbs (int x, int y, int z)
xm_inline double minAbs (double x, double y)
xm_inline double minAbs (double x, double y, double z)
xm_inline double maxAbs (double x, double y)
xm_inline double maxAbs (double x, double y, double z)
xm_inline void average (double &x_avr, double x, double tau)
xm_inline void average (double &x_avr, double x, double tau, double factor)
xm_inline void average (float &x_avr, float x, float tau)
xm_inline void average (float &x_avr, float x, float tau, float factor)
xm_inline float Acos (float x)
xm_inline double Acos (double x)
template<class T , class T1 , class T2 >
xm_inline T clamp (const T &x, const T1 &xmin, const T2 &xmax)
xm_inline const Vect2f operator* (const Mat2f &m, const Vect2f &v)
xm_inline const Vect2f operator* (const MatX2f &m, const Vect2f &v)
xm_inline void decomposition (const Vect3f &axis, const Vect3f &v, Vect3f &v_normal, Vect3f &v_tangent)
xm_inline void decomposition (const Vect3d &axis, const Vect3d &v, Vect3d &v_normal, Vect3d &v_tangent)
xm_inline double dot (const Vect3d &u, const Vect3f &v)
xm_inline float dot (const Vect3f &u, const Vect3d &v)
QuatF normalize (const QuatF &q)
QuatF operator* (float w, const QuatF &q)
QuatD normalize (const QuatD &q)
QuatD operator* (double w, const QuatD &q)
ostream & operator<< (ostream &os, const Vect2i &v)
istream & operator>> (istream &is, Vect2i &v)
ostream & operator<< (ostream &os, const Vect2f &v)
istream & operator>> (istream &is, Vect2f &v)
ostream & operator<< (ostream &os, const Vect2s &v)
istream & operator>> (istream &is, Vect2s &v)
ostream & operator<< (ostream &os, const Vect3d &v)
istream & operator>> (istream &is, Vect3d &v)
ostream & operator<< (ostream &os, const Vect3f &v)
istream & operator>> (istream &is, Vect3f &v)
ostream & operator<< (ostream &os, const Vect4f &v)
istream & operator>> (istream &is, Vect4f &v)
ostream & operator<< (ostream &os, const Mat3d &m)
istream & operator>> (istream &is, Mat3d &m)
ostream & operator<< (ostream &os, const Mat3f &m)
istream & operator>> (istream &is, Mat3f &m)
ostream & operator<< (ostream &os, const MatXd &m)
istream & operator>> (istream &is, MatXd &m)
ostream & operator<< (ostream &os, const MatXf &m)
istream & operator>> (istream &is, MatXf &m)
istream & operator>> (istream &is, QuatD &q)
ostream & operator<< (ostream &os, const QuatD &q)
istream & operator>> (istream &is, QuatF &q)
ostream & operator<< (ostream &os, const QuatF &q)
ostream & operator<< (ostream &os, const Se3d &se3)
istream & operator>> (istream &is, Se3d &se3)
ostream & operator<< (ostream &os, const Se3f &se3)
istream & operator>> (istream &is, Se3f &se3)
Variables
const double DBL_EPS = 1.e-15
const double DBL_INF = 1.e+100
const double DBL_COMPARE_TOLERANCE = 1.e-10
const float FLT_EPS = 1.e-7f
const float FLT_INF = 1.e+30f
const float FLT_COMPARE_TOLERANCE = 1.e-5f
const int INT_INF = 0x7fffffff
RandomGenerator xm_random_generator
Macro Definition Documentation
__ROUND__
#define __ROUND__
__swap__
#define __swap__ (x, y) { float t = y; y = x; x = t; }
G2R
#define G2R (x) ((x)*M_PI/180.f)
M_PI
#define M_PI 3.14159265358979323846f
NOMINMAX
#define NOMINMAX
R2G
#define R2G (x) ((x)*180.f/M_PI)
xm_inline
#define xm_inline inline
Enumeration Type Documentation
eAxis
enum eAxis
Enumerator
X_AXIS
Y_AXIS
Z_AXIS
W_AXIS
 { X_AXIS, Y_AXIS, Z_AXIS, W_AXIS };
Function Documentation
Acos() [1/2]
xm_inline double Acos (double x)
 { return x > 1. ? 0 : (x < -1. ? M_PI : acos(x)); }
References M_PI.
Acos() [2/2]
xm_inline float Acos (float x)
 { return x > 1.f ? 0 : (x < -1.f ? M_PI : acosf(x)); }
References M_PI.
average() [1/4]
xm_inline void average (double & x_avr, double x, double tau)
 { x_avr = x_avr*(1. - tau) + tau*x; }
average() [2/4]
xm_inline void average (double & x_avr, double x, double tau, double factor)
 { tau = pow(tau, factor); x_avr = x_avr*(1. - tau) + tau*x; }
average() [3/4]
xm_inline void average (float & x_avr, float x, float tau)
 { x_avr = x_avr*(1.f - tau) + tau*x; }
average() [4/4]
xm_inline void average (float & x_avr, float x, float tau, float factor)
 { tau = (float)pow(tau, factor); x_avr = x_avr*(1.f - tau) + tau*x; }
clamp()
template<class T , class T1 , class T2 > xm_inline T clamp (const T & x, const T1 & xmin, const T2 & xmax)
 { if(x < xmin) return xmin; if(x > xmax) return xmax; return x; }
decomposition() [1/2]
xm_inline void decomposition (const Vect3d & axis, const Vect3d & v, Vect3d & v_normal, Vect3d & v_tangent)
 {
     // axis - axis of decomposition, v_normal - collinear to axis, v_tangent - perpendicular to axis
     v_normal.scale(axis, dot(axis, v)/((axis).norm2()));
     v_tangent.sub(v,v_normal);
 }
References dot(), Vect3d::scale(), and Vect3d::sub().
decomposition() [2/2]
xm_inline void decomposition (const Vect3f & axis, const Vect3f & v, Vect3f & v_normal, Vect3f & v_tangent)
 {
     // axis - axis of decomposition, v_normal - collinear to axis, v_tangent - perpendicular to axis
     v_normal.scale(axis, dot(axis, v)/((axis).norm2()));
     v_tangent.sub(v,v_normal);
 }
References dot(), Vect3f::scale(), and Vect3f::sub().
dot() [1/2]
xm_inline double dot (const Vect3d & u, const Vect3f & v)
 { return u.dot(v); }
References Vect3d::dot().
Referenced by decomposition(), Mat3d::set(), Mat3f::set(), and Slerp().
dot() [2/2]
xm_inline float dot (const Vect3f & u, const Vect3d & v)
 { return u.dot(v); }
References Vect3f::dot().
fabsRnd()
xm_inline float fabsRnd (float x)
 { return xm_random_generator.fabsRnd(x); }
References RandomGenerator::fabsRnd(), and xm_random_generator.
frnd()
xm_inline float frnd (float x)
 { return xm_random_generator.frnd(x); }
References RandomGenerator::frnd(), and xm_random_generator.
max() [1/4]
template<class T > xm_inline T max (const T & a, const T & b, const T & c)
 { return max(max(a, b), c); }
References max().
max() [2/4]
xm_inline double max (double x, double y)
 { return x > y ? x : y; }
max() [3/4]
xm_inline float max (float x, float y)
 { return x > y ? x : y; }
max() [4/4]
xm_inline int max (int x, int y)
 { return x > y ? x : y; }
Referenced by ivrtMap::accept(), vrtMap::accept(), World::check_visibility(), vrtMap::delink(), ivrtMap::finit(), ilandPrepare(), HordeList::Init(), HordeSourceList::Init(), FishWarriorList::Init(), vrtMap::link(), vrtMap::linkC(), max(), Name2Int(), pack(), pack_short(), PaletteTransform::quant(), dastPoly3D::quant_make_sign(), unpack(), unpack_short(), and win32_getMemStat().
maxa() [1/4]
xm_inline double maxa (double x, double y)
 { return fabs(x) > fabs(y) ? x : y; }
maxa() [2/4]
xm_inline double maxa (double x, double y, double z)
 { return maxa(maxa(x,y),z); }
References maxa().
maxa() [3/4]
xm_inline int maxa (int x, int y)
 { return abs(x) > abs(y) ? x : y; }
Referenced by maxa().
maxa() [4/4]
xm_inline int maxa (int x, int y, int z)
 { return maxa(maxa(x,y),z); }
References maxa().
maxAbs() [1/4]
xm_inline double maxAbs (double x, double y)
 { return fabs(x) > fabs(y) ? fabs(x) : fabs(y); }
maxAbs() [2/4]
xm_inline double maxAbs (double x, double y, double z)
 { return maxAbs(maxAbs(x,y),z); }
References maxAbs().
maxAbs() [3/4]
xm_inline int maxAbs (int x, int y)
 { return abs(x) > abs(y) ? abs(x) : abs(y); }
Referenced by maxAbs().
maxAbs() [4/4]
xm_inline int maxAbs (int x, int y, int z)
 { return maxAbs(maxAbs(x,y),z); }
References maxAbs().
min() [1/4]
template<class T > xm_inline T min (const T & a, const T & b, const T & c)
 { return min(min(a, b), c); }
References min().
min() [2/4]
xm_inline double min (double x, double y)
 { return x < y ? x : y; }
min() [3/4]
xm_inline float min (float x, float y)
 { return x < y ? x : y; }
min() [4/4]
xm_inline int min (int x, int y)
 { return x < y ? x : y; }
Referenced by GetNetworkGameTime(), min(), pack(), pack_short(), StaticSort(), unpack(), and unpack_short().
mina() [1/4]
xm_inline double mina (double x, double y)
 { return fabs(x) < fabs(y) ? x : y; }
mina() [2/4]
xm_inline double mina (double x, double y, double z)
 { return mina(mina(x,y),z); }
References mina().
mina() [3/4]
xm_inline int mina (int x, int y)
 { return abs(x) < abs(y) ? x : y; }
Referenced by mina().
mina() [4/4]
xm_inline int mina (int x, int y, int z)
 { return mina(mina(x,y),z); }
References mina().
minAbs() [1/4]
xm_inline double minAbs (double x, double y)
 { return fabs(x) < fabs(y) ? fabs(x) : fabs(y); }
minAbs() [2/4]
xm_inline double minAbs (double x, double y, double z)
 { return minAbs(minAbs(x,y),z); }
References minAbs().
minAbs() [3/4]
xm_inline int minAbs (int x, int y)
 { return abs(x) < abs(y) ? abs(x) : abs(y); }
Referenced by minAbs().
minAbs() [4/4]
xm_inline int minAbs (int x, int y, int z)
 { return minAbs(minAbs(x,y),z); }
References minAbs().
normalize() [1/2]
QuatD normalize (const QuatD & q)
 {
   double scale;
   scale = 1.0 / sqrt(q.s_*q.s_ + q.x_*q.x_ + q.y_*q.y_ + q.z_*q.z_);
   return QuatD(scale * q.s_, scale * q.x_, scale * q.y_, scale * q.z_);
 }
normalize() [2/2]
QuatF normalize (const QuatF & q)
 {
   float scale;
   scale = 1.f / sqrtf(q.s_*q.s_ + q.x_*q.x_ + q.y_*q.y_ + q.z_*q.z_);
   return QuatF(scale * q.s_, scale * q.x_, scale * q.y_, scale * q.z_);
 }
operator*() [1/4]
xm_inline const Vect2f operator* (const Mat2f & m, const Vect2f & v)
 { Vect2f vv(v); return vv *= m; }
operator*() [2/4]
xm_inline const Vect2f operator* (const MatX2f & m, const Vect2f & v)
 { Vect2f vv(v); return vv *= m; }
operator*() [3/4]
QuatD operator* (double w, const QuatD & q)
 {
     return QuatD(q.s_*w,q.x_*w,q.y_*w,q.z_*w);
 }
operator*() [4/4]
QuatF operator* (float w, const QuatF & q)
 {
     return QuatF(q.s_*w,q.x_*w,q.y_*w,q.z_*w);
 }
operator<<() [1/14]
ostream& operator<< (ostream & os, const Mat3d & m) inline
 {
   os << m.xx << " \t" << m.xy << " \t" << m.xz << endl;
   os << m.yx << " \t" << m.yy << " \t" << m.yz << endl;
   os << m.zx << " \t" << m.zy << " \t" << m.zz;
   return os;
 }
operator<<() [2/14]
ostream& operator<< (ostream & os, const Mat3f & m) inline
 {
   os << m.xx << " \t" << m.xy << " \t" << m.xz << endl;
   os << m.yx << " \t" << m.yy << " \t" << m.yz << endl;
   os << m.zx << " \t" << m.zy << " \t" << m.zz;
   return os;
 }
operator<<() [3/14]
ostream& operator<< (ostream & os, const MatXd & m) inline
 {
   return os << m.R << m.d;
 }
operator<<() [4/14]
ostream& operator<< (ostream & os, const MatXf & m) inline
 {
   return os << m.R << m.d;
 }
operator<<() [5/14]
ostream& operator<< (ostream & os, const QuatD & q) inline
 {
   os << q.s_ << " \t" << q.x_ << " \t" << q.y_ << " \t" << q.z_;
   return os;
 }
operator<<() [6/14]
ostream& operator<< (ostream & os, const QuatF & q) inline
 {
   os << q.s_ << " \t" << q.x_ << " \t" << q.y_ << " \t" << q.z_;
   return os;
 }
operator<<() [7/14]
ostream& operator<< (ostream & os, const Se3d & se3) inline
 {
   return os << se3.q << se3.d;
 }
operator<<() [8/14]
ostream& operator<< (ostream & os, const Se3f & se3) inline
 {
   return os << se3.q << se3.d;
 }
operator<<() [9/14]
ostream& operator<< (ostream & os, const Vect2f & v) inline
 {
     os << v.x << " \t" << v.y;
     return os;
 }
References Vect2f::x, and Vect2f::y.
operator<<() [10/14]
ostream& operator<< (ostream & os, const Vect2i & v) inline
 {
     os << v.x << " \t" << v.y;
     return os;
 }
References Vect2i::x, and Vect2i::y.
operator<<() [11/14]
ostream& operator<< (ostream & os, const Vect2s & v) inline
 {
     os << v.x << " \t" << v.y;
     return os;
 }
References Vect2s::x, and Vect2s::y.
operator<<() [12/14]
ostream& operator<< (ostream & os, const Vect3d & v) inline
 {
     os << v.x << " \t" << v.y << " \t" << v.z;
     return os;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator<<() [13/14]
ostream& operator<< (ostream & os, const Vect3f & v) inline
 {
     os << v.x << " \t" << v.y << " \t" << v.z;
     return os;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
operator<<() [14/14]
ostream& operator<< (ostream & os, const Vect4f & v) inline
 {
     os << v.x << " \t" << v.y << " \t" << v.z << " \t" << v.w;
     return os;
 }
References Vect4f::w, Vect4f::x, Vect4f::y, and Vect4f::z.
operator>>() [1/14]
istream& operator>> (istream & is, Mat3d & m) inline
 {
   is >> m.xx >> m.xy >> m.xz;
   is >> m.yx >> m.yy >> m.yz;
   is >> m.zx >> m.zy >> m.zz;
   return is;
 }
operator>>() [2/14]
istream& operator>> (istream & is, Mat3f & m) inline
 {
   is >> m.xx >> m.xy >> m.xz;
   is >> m.yx >> m.yy >> m.yz;
   is >> m.zx >> m.zy >> m.zz;
   return is;
 }
operator>>() [3/14]
istream& operator>> (istream & is, MatXd & m) inline
 {
   Se3d T;
   is >> T;
   m.set(T);
   return is;
 }
References MatXd::set().
operator>>() [4/14]
istream& operator>> (istream & is, MatXf & m) inline
 {
   Se3d T;
   is >> T;
   m.set(T);
   return is;
 }
References MatXf::set().
operator>>() [5/14]
istream& operator>> (istream & is, QuatD & q) inline
 {
   is >> q.s_ >> q.x_ >> q.y_ >> q.z_;
   return is;
 }
operator>>() [6/14]
istream& operator>> (istream & is, QuatF & q) inline
 {
   is >> q.s_ >> q.x_ >> q.y_ >> q.z_;
   return is;
 }
operator>>() [7/14]
istream& operator>> (istream & is, Se3d & se3) inline
 {
     return is >> se3.q >> se3.d;
 }
operator>>() [8/14]
istream& operator>> (istream & is, Se3f & se3) inline
 {
     return is >> se3.q >> se3.d;
 }
operator>>() [9/14]
istream& operator>> (istream & is, Vect2f & v) inline
 {
     is >> v.x >> v.y;
     return is;
 }
References Vect2f::x, and Vect2f::y.
operator>>() [10/14]
istream& operator>> (istream & is, Vect2i & v) inline
 {
     is >> v.x >> v.y;
     return is;
 }
References Vect2i::x, and Vect2i::y.
operator>>() [11/14]
istream& operator>> (istream & is, Vect2s & v) inline
 {
     is >> v.x >> v.y;
     return is;
 }
References Vect2s::x, and Vect2s::y.
operator>>() [12/14]
istream& operator>> (istream & is, Vect3d & v) inline
 {
     is >> v.x >> v.y >> v.z;
     return is;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator>>() [13/14]
istream& operator>> (istream & is, Vect3f & v) inline
 {
     is >> v.x >> v.y >> v.z;
     return is;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
operator>>() [14/14]
istream& operator>> (istream & is, Vect4f & v) inline
 {
     is >> v.x >> v.y >> v.z >> v.w;
     return is;
 }
References Vect4f::w, Vect4f::x, Vect4f::y, and Vect4f::z.
random()
xm_inline unsigned random (unsigned m)
 { return xm_random_generator(m); }
References xm_random_generator.
Referenced by SkyFarmerObject::CreateSkyFarmer().
round() [1/2]
xm_inline int round (double x)
 {
     int a;
     _asm {
         fld x
         fistp dword ptr a
     }
     return a;
 }
Referenced by Server::analyse_statistics(), Object::basic_debris_analysis(), Object::basic_mechous_analysis(), VangerUnit::BulletCollision(), calc_view_factors(), VangerUnit::CalcAiFactor(), camera_quant(), CastArbitraryShadow(), CastShadow(), Object::check_mole_submerging(), Object::check_terrain_type(), VangerUnit::CheckReturn2Track(), Object::controls(), costab(), WaterParticleObject::CreateParticle(), Object::debris_analysis(), Vector::descart(), Object::direct_joystick_control(), Vect2s::distance(), Object::draw(), Draw3DPlane(), TrackUnit::DrawMechosParticle(), ParticleObject::DrawQuant(), WaterParticleObject::DrawQuant(), HordeObject::DrawQuant(), Object::dynamics_init(), Object::fish_analysis(), G2L(), G2LF(), G2LQ(), G2LS(), get_height(), Object::get_max_jump_distance(), CharacterDataType::GetInternalStuffOrder(), CharacterDataType::GetStuffOrder(), CharacterDataType::GetVangerOrder(), height_analysis_fish(), VangerUnit::InitAI(), ActionUnit::InitEnvironment(), Object::insect_analysis(), iPrepareHallOfFame(), iPrepareResults(), LinkDist(), LoadVPR(), Matrix::Matrix(), Object::mechous_analysis(), VangerUnit::MoleProcessQuant(), VangerUnit::NetCreateVanger(), Object::NetEvent(), Vect2i::norm(), Vect2s::norm(), Vect2s::normalize(), Vector::operator*(), operator*(), Vect2s::operator*(), Vector::operator*=(), Vect2i::operator*=(), Vect2s::operator*=(), Vect2s::operator/(), Vector::operator/(), Vect2s::operator/=(), Vector::operator/=(), Vertex::operator=(), Vector::operator=(), pack(), pack_short(), Object::pixel_draw(), PointDist(), PrepareLight(), ParticleObject::Quant(), WaterParticleObject::Quant(), TargetParticleObject::Quant(), HordeObject::Quant(), VangerUnit::Quant(), Player::receive(), S2G(), vrtMap::scaling_3D(), Object::Send(), Vect2i::set(), Object::set_3D(), set_time_by_server(), short_network_analysis(), Object::skyfarmer_analysis(), smart_putspr(), smart_putspr_f(), GameObjectDispatcher::Sort(), Vector::spherical(), Vector::spherical2descart(), TargetParticleType::sQuant(), TargetParticleType::sQuant2(), square_analysis(), Object::test_object_to_baseobject(), Object::test_wheels_to_sphere(), Vect2i::Vect2i(), Vect2s::Vect2s(), Vector::Vector(), Vertex::Vertex(), Vect4f::wi(), Vect2f::xi(), Vect3f::xi(), Vect3d::xi(), Vect4f::xi(), Vect2f::yi(), Vect3f::yi(), Vect3d::yi(), Vect4f::yi(), Vect3f::zi(), Vect3d::zi(), and Vect4f::zi().
round() [2/2]
xm_inline int round (float x)
 {
     int a;
     _asm {
         fld x
         fistp dword ptr a
     }
     return a;
 }
SIGN() [1/3]
template<class T > xm_inline int SIGN (const T & x)
 { return x ? (x > 0 ? 1 : -1 ) : 0; }
SIGN() [2/3]
xm_inline double SIGN (double a, double b)
 { return b >= 0.0 ? fabs(a) : -fabs(a); }
SIGN() [3/3]
xm_inline float SIGN (float a, float b)
 { return b >= 0.0f ? fabsf(a) : -fabsf(a); }
sqr()
template<class T > xm_inline T sqr (const T & x)
 { return x*x; }
Referenced by Object::basic_debris_analysis(), Object::basic_mechous_analysis(), Object::direct_joystick_control(), Quaternion::Euler(), Object::impulse(), Object::insect_analysis(), Object::mechous_analysis(), VangerUnit::MoleProcessQuant(), Object::NetEvent(), Quaternion::rotation(), DBM::rotation_angles(), set_time_by_server(), and Object::test_object_to_baseobject().
Variable Documentation
DBL_COMPARE_TOLERANCE
const double DBL_COMPARE_TOLERANCE = 1.e-10
Referenced by QuatD::operator!=(), Vect3d::operator!=(), QuatD::operator==(), and Vect3d::operator==().
DBL_EPS
const double DBL_EPS = 1.e-15
Referenced by Object::basic_debris_analysis(), Object::basic_mechous_analysis(), DBM::DBM(), Draw3DPlane(), Quaternion::Euler(), get_height(), interpolation(), interpolation_factors(), VariablePolygon::lower_average_z(), Vect3d::Normalize(), DBM::rotation_angles(), section_prepare(), QuatD::set(), Slerp(), smart_putspr(), smart_putspr_f(), square_analysis(), and Vect3d::theta().
DBL_INF
const double DBL_INF = 1.e+100
FLT_COMPARE_TOLERANCE
const float FLT_COMPARE_TOLERANCE = 1.e-5f
Referenced by QuatF::operator!=(), Vect3f::operator!=(), Vect4f::operator!=(), QuatF::operator==(), Vect3f::operator==(), and Vect4f::operator==().
FLT_EPS
const float FLT_EPS = 1.e-7f
Referenced by Vect3f::Normalize(), QuatF::set(), and Vect3f::theta().
FLT_INF
const float FLT_INF = 1.e+30f
INT_INF
const int INT_INF = 0x7fffffff
Referenced by CastArbitraryShadow(), and graph3d_init().
xm_random_generator
RandomGenerator xm_random_generator extern
Referenced by fabsRnd(), frnd(), and random().