Vangers: lib/xtool/xmath/xmath.cpp File Reference
xmath.cpp File Reference
#include "xglobal.h"
#include "xmath.h"
Macros
#define STR_LENGTH 1000
Functions
XStream & operator<= (XStream &s, const Vect2i &v)
XStream & operator>= (XStream &s, Vect2i &v)
XStream & operator< (XStream &s, const Vect2i &v)
XStream & operator> (XStream &s, Vect2i &v)
XBuffer & operator<= (XBuffer &b, const Vect2i &v)
XBuffer & operator>= (XBuffer &b, Vect2i &v)
XBuffer & operator< (XBuffer &b, const Vect2i &v)
XBuffer & operator> (XBuffer &b, Vect2i &v)
XStream & operator<= (XStream &s, const Vect2f &v)
XStream & operator>= (XStream &s, Vect2f &v)
XStream & operator< (XStream &s, const Vect2f &v)
XStream & operator> (XStream &s, Vect2f &v)
XBuffer & operator<= (XBuffer &b, const Vect2f &v)
XBuffer & operator>= (XBuffer &b, Vect2f &v)
XBuffer & operator< (XBuffer &b, const Vect2f &v)
XBuffer & operator> (XBuffer &b, Vect2f &v)
XStream & operator<= (XStream &s, const Vect2s &v)
XStream & operator>= (XStream &s, Vect2s &v)
XStream & operator< (XStream &s, const Vect2s &v)
XStream & operator> (XStream &s, Vect2s &v)
XBuffer & operator<= (XBuffer &b, const Vect2s &v)
XBuffer & operator>= (XBuffer &b, Vect2s &v)
XBuffer & operator< (XBuffer &b, const Vect2s &v)
XBuffer & operator> (XBuffer &b, Vect2s &v)
XStream & operator<= (XStream &s, const Vect3d &v)
XStream & operator>= (XStream &s, Vect3d &v)
XStream & operator< (XStream &s, const Vect3d &v)
XStream & operator> (XStream &s, Vect3d &v)
XBuffer & operator<= (XBuffer &b, const Vect3d &v)
XBuffer & operator>= (XBuffer &b, Vect3d &v)
XBuffer & operator< (XBuffer &b, const Vect3d &v)
XBuffer & operator> (XBuffer &b, Vect3d &v)
XStream & operator<= (XStream &s, const Vect3f &v)
XStream & operator>= (XStream &s, Vect3f &v)
XStream & operator< (XStream &s, const Vect3f &v)
XStream & operator> (XStream &s, Vect3f &v)
XBuffer & operator<= (XBuffer &b, const Vect3f &v)
XBuffer & operator>= (XBuffer &b, Vect3f &v)
XBuffer & operator< (XBuffer &b, const Vect3f &v)
XBuffer & operator> (XBuffer &b, Vect3f &v)
XStream & operator<= (XStream &s, const Mat3d &m)
XStream & operator>= (XStream &s, Mat3d &m)
XStream & operator< (XStream &s, const Mat3d &m)
XStream & operator> (XStream &s, Mat3d &m)
XBuffer & operator<= (XBuffer &b, const Mat3d &m)
XBuffer & operator>= (XBuffer &b, Mat3d &m)
XBuffer & operator< (XBuffer &b, const Mat3d &m)
XBuffer & operator> (XBuffer &b, Mat3d &m)
XStream & operator<= (XStream &s, const Mat3f &m)
XStream & operator>= (XStream &s, Mat3f &m)
XStream & operator< (XStream &s, const Mat3f &m)
XStream & operator> (XStream &s, Mat3f &m)
XBuffer & operator<= (XBuffer &b, const Mat3f &m)
XBuffer & operator>= (XBuffer &b, Mat3f &m)
XBuffer & operator< (XBuffer &b, const Mat3f &m)
XBuffer & operator> (XBuffer &b, Mat3f &m)
XStream & operator<= (XStream &s, const QuatD &q)
XStream & operator>= (XStream &s, QuatD &q)
XStream & operator< (XStream &s, const QuatD &q)
XStream & operator> (XStream &s, QuatD &q)
XBuffer & operator<= (XBuffer &b, const QuatD &q)
XBuffer & operator>= (XBuffer &b, QuatD &q)
XBuffer & operator< (XBuffer &b, const QuatD &q)
XBuffer & operator> (XBuffer &b, QuatD &q)
XStream & operator<= (XStream &s, const QuatF &q)
XStream & operator>= (XStream &s, QuatF &q)
XStream & operator< (XStream &s, const QuatF &q)
XStream & operator> (XStream &s, QuatF &q)
XBuffer & operator<= (XBuffer &b, const QuatF &q)
XBuffer & operator>= (XBuffer &b, QuatF &q)
XBuffer & operator< (XBuffer &b, const QuatF &q)
XBuffer & operator> (XBuffer &b, QuatF &q)
QuatD Slerp (const QuatD &A, const QuatD &B, double t)
Variables
RandomGenerator xm_random_generator
Macro Definition Documentation
STR_LENGTH
#define STR_LENGTH 1000
Function Documentation
operator<() [1/18]
XBuffer& operator< (XBuffer & b, const Mat3d & m)
 {
     b < m.xx < m.xy < m.xz;
     b < m.yx < m.yy < m.yz;
     b < m.zx < m.zy < m.zz;
     return b;
 }
operator<() [2/18]
XBuffer& operator< (XBuffer & b, const Mat3f & m)
 {
     b < m.xx < m.xy < m.xz;
     b < m.yx < m.yy < m.yz;
     b < m.zx < m.zy < m.zz;
     return b;
 }
operator<() [3/18]
XBuffer& operator< (XBuffer & b, const QuatD & q)
 {
     b < q.s_ < q.x_ < q.y_ < q.z_;
     return b;
 }
operator<() [4/18]
XBuffer& operator< (XBuffer & b, const QuatF & q)
 {
     b < q.s_ < q.x_ < q.y_ < q.z_;
     return b;
 }
operator<() [5/18]
XBuffer& operator< (XBuffer & b, const Vect2f & v)
 {
     b < v.x < v.y;
     return b;
 }
References Vect2f::x, and Vect2f::y.
operator<() [6/18]
XBuffer& operator< (XBuffer & b, const Vect2i & v)
 {
     b < v.x < v.y;
     return b;
 }
References Vect2i::x, and Vect2i::y.
operator<() [7/18]
XBuffer& operator< (XBuffer & b, const Vect2s & v)
 {
     b < v.x < v.y;
     return b;
 }
References Vect2s::x, and Vect2s::y.
operator<() [8/18]
XBuffer& operator< (XBuffer & b, const Vect3d & v)
 {
     b < v.x < v.y < v.z;
     return b;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator<() [9/18]
XBuffer& operator< (XBuffer & b, const Vect3f & v)
 {
     b < v.x < v.y < v.z;
     return b;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
operator<() [10/18]
XStream& operator< (XStream & s, const Mat3d & m)
 {
     s.write(&m,sizeof(Mat3d));
     return s;
 }
References XStream::write().
operator<() [11/18]
XStream& operator< (XStream & s, const Mat3f & m)
 {
     s.write(&m,sizeof(Mat3f));
     return s;
 }
References XStream::write().
operator<() [12/18]
XStream& operator< (XStream & s, const QuatD & q)
 {
     s.write(&q,sizeof(QuatD));
     return s;
 }
References XStream::write().
operator<() [13/18]
XStream& operator< (XStream & s, const QuatF & q)
 {
     s.write(&q,sizeof(QuatF));
     return s;
 }
References XStream::write().
operator<() [14/18]
XStream& operator< (XStream & s, const Vect2f & v)
 {
     s.write(&v,sizeof(Vect2f));
     return s;
 }
References XStream::write().
operator<() [15/18]
XStream& operator< (XStream & s, const Vect2i & v)
 {
     s.write(&v,sizeof(Vect2i));
     return s;
 }
References XStream::write().
operator<() [16/18]
XStream& operator< (XStream & s, const Vect2s & v)
 {
     s.write(&v,sizeof(Vect2s));
     return s;
 }
References XStream::write().
operator<() [17/18]
XStream& operator< (XStream & s, const Vect3d & v)
 {
     s.write(&v,sizeof(Vect3d));
     return s;
 }
References XStream::write().
operator<() [18/18]
XStream& operator< (XStream & s, const Vect3f & v)
 {
     s.write(&v,sizeof(Vect3f));
     return s;
 }
References XStream::write().
operator<=() [1/18]
XBuffer& operator<= (XBuffer & b, const Mat3d & m)
 {
     b <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     b <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     b <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return b;
 }
operator<=() [2/18]
XBuffer& operator<= (XBuffer & b, const Mat3f & m)
 {
     b <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     b <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     b <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return b;
 }
operator<=() [3/18]
XBuffer& operator<= (XBuffer & b, const QuatD & q)
 {
     b <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return b;
 }
operator<=() [4/18]
XBuffer& operator<= (XBuffer & b, const QuatF & q)
 {
     b <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return b;
 }
operator<=() [5/18]
XBuffer& operator<= (XBuffer & b, const Vect2f & v)
 {
     b <= v.x < " \t" <= v.y < "\n";
     return b;
 }
References Vect2f::x, and Vect2f::y.
operator<=() [6/18]
XBuffer& operator<= (XBuffer & b, const Vect2i & v)
 {
     b <= v.x < " \t" <= v.y < "\n";
     return b;
 }
References Vect2i::x, and Vect2i::y.
operator<=() [7/18]
XBuffer& operator<= (XBuffer & b, const Vect2s & v)
 {
     b <= v.x < " \t" <= v.y < "\n";
     return b;
 }
References Vect2s::x, and Vect2s::y.
operator<=() [8/18]
XBuffer& operator<= (XBuffer & b, const Vect3d & v)
 {
     b <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return b;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator<=() [9/18]
XBuffer& operator<= (XBuffer & b, const Vect3f & v)
 {
     b <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return b;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
operator<=() [10/18]
XStream& operator<= (XStream & s, const Mat3d & m)
 {
     s <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     s <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     s <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return s;
 }
operator<=() [11/18]
XStream& operator<= (XStream & s, const Mat3f & m)
 {
     s <= m.xx < " \t" <= m.xy < " \t" <= m.xz < "\n";
     s <= m.yx < " \t" <= m.yy < " \t" <= m.yz < "\n";
     s <= m.zx < " \t" <= m.zy < " \t" <= m.zz < "\n";
     return s;
 }
operator<=() [12/18]
XStream& operator<= (XStream & s, const QuatD & q)
 {
     s <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return s;
 }
operator<=() [13/18]
XStream& operator<= (XStream & s, const QuatF & q)
 {
     s <= q.s_ < " \t\t"  <= q.x_ < " \t" <= q.y_ < " \t" <= q.z_ < "\n";
     return s;
 }
operator<=() [14/18]
XStream& operator<= (XStream & s, const Vect2f & v)
 {
     s <= v.x < " \t" <= v.y < "\n";
     return s;
 }
References Vect2f::x, and Vect2f::y.
operator<=() [15/18]
XStream& operator<= (XStream & s, const Vect2i & v)
 {
     s <= v.x < " \t" <= v.y < "\n";
     return s;
 }
References Vect2i::x, and Vect2i::y.
operator<=() [16/18]
XStream& operator<= (XStream & s, const Vect2s & v)
 {
     s <= v.x < " \t" <= v.y < "\n";
     return s;
 }
References Vect2s::x, and Vect2s::y.
operator<=() [17/18]
XStream& operator<= (XStream & s, const Vect3d & v)
 {
     s <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return s;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator<=() [18/18]
XStream& operator<= (XStream & s, const Vect3f & v)
 {
     s <= v.x < " \t" <= v.y < " \t" <= v.z < "\n";
     return s;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
operator>() [1/18]
XBuffer& operator> (XBuffer & b, Mat3d & m)
 {
     b > m.xx > m.xy > m.xz;
     b > m.yx > m.yy > m.yz;
     b > m.zx > m.zy > m.zz;
     return b;
 }
operator>() [2/18]
XBuffer& operator> (XBuffer & b, Mat3f & m)
 {
     b > m.xx > m.xy > m.xz;
     b > m.yx > m.yy > m.yz;
     b > m.zx > m.zy > m.zz;
     return b;
 }
operator>() [3/18]
XBuffer& operator> (XBuffer & b, QuatD & q)
 {
     b > q.s_ > q.x_ > q.y_ > q.z_;
     return b;
 }
operator>() [4/18]
XBuffer& operator> (XBuffer & b, QuatF & q)
 {
     b > q.s_ > q.x_ > q.y_ > q.z_;
     return b;
 }
operator>() [5/18]
XBuffer& operator> (XBuffer & b, Vect2f & v)
 {
     b > v.x > v.y;
     return b;
 }
References Vect2f::x, and Vect2f::y.
operator>() [6/18]
XBuffer& operator> (XBuffer & b, Vect2i & v)
 {
     b > v.x > v.y;
     return b;
 }
References Vect2i::x, and Vect2i::y.
operator>() [7/18]
XBuffer& operator> (XBuffer & b, Vect2s & v)
 {
     b > v.x > v.y;
     return b;
 }
References Vect2s::x, and Vect2s::y.
operator>() [8/18]
XBuffer& operator> (XBuffer & b, Vect3d & v)
 {
     b > v.x > v.y > v.z;
     return b;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator>() [9/18]
XBuffer& operator> (XBuffer & b, Vect3f & v)
 {
     b > v.x > v.y > v.z;
     return b;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
operator>() [10/18]
XStream& operator> (XStream & s, Mat3d & m)
 {
     s.read(&m,sizeof(Mat3d));
     return s;
 }
References XStream::read().
operator>() [11/18]
XStream& operator> (XStream & s, Mat3f & m)
 {
     s.read(&m,sizeof(Mat3f));
     return s;
 }
References XStream::read().
operator>() [12/18]
XStream& operator> (XStream & s, QuatD & q)
 {
     s.read(&q,sizeof(QuatD));
     return s;
 }
References XStream::read().
operator>() [13/18]
XStream& operator> (XStream & s, QuatF & q)
 {
     s.read(&q,sizeof(QuatF));
     return s;
 }
References XStream::read().
operator>() [14/18]
XStream& operator> (XStream & s, Vect2f & v)
 {
     s.read(&v,sizeof(Vect2f));
     return s;
 }
References XStream::read().
operator>() [15/18]
XStream& operator> (XStream & s, Vect2i & v)
 {
     s.read(&v,sizeof(Vect2i));
     return s;
 }
References XStream::read().
operator>() [16/18]
XStream& operator> (XStream & s, Vect2s & v)
 {
     s.read(&v,sizeof(Vect2s));
     return s;
 }
References XStream::read().
operator>() [17/18]
XStream& operator> (XStream & s, Vect3d & v)
 {
     s.read(&v,sizeof(Vect3d));
     return s;
 }
References XStream::read().
operator>() [18/18]
XStream& operator> (XStream & s, Vect3f & v)
 {
     s.read(&v,sizeof(Vect3f));
     return s;
 }
References XStream::read().
operator>=() [1/18]
XBuffer& operator>= (XBuffer & b, Mat3d & m)
 {
     b >= m.xx >= m.xy >= m.xz;
     b >= m.yx >= m.yy >= m.yz;
     b >= m.zx >= m.zy >= m.zz;
     return b;
 }
operator>=() [2/18]
XBuffer& operator>= (XBuffer & b, Mat3f & m)
 {
     b >= m.xx >= m.xy >= m.xz;
     b >= m.yx >= m.yy >= m.yz;
     b >= m.zx >= m.zy >= m.zz;
     return b;
 }
operator>=() [3/18]
XBuffer& operator>= (XBuffer & b, QuatD & q)
 {
     b >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return b;
 }
operator>=() [4/18]
XBuffer& operator>= (XBuffer & b, QuatF & q)
 {
     b >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return b;
 }
operator>=() [5/18]
XBuffer& operator>= (XBuffer & b, Vect2f & v)
 {
     b >= v.x >= v.y;
     return b;
 }
References Vect2f::x, and Vect2f::y.
operator>=() [6/18]
XBuffer& operator>= (XBuffer & b, Vect2i & v)
 {
     b >= v.x >= v.y;
     return b;
 }
References Vect2i::x, and Vect2i::y.
operator>=() [7/18]
XBuffer& operator>= (XBuffer & b, Vect2s & v)
 {
     b >= v.x >= v.y;
     return b;
 }
References Vect2s::x, and Vect2s::y.
operator>=() [8/18]
XBuffer& operator>= (XBuffer & b, Vect3d & v)
 {
     b >= v.x >= v.y >= v.z;
     return b;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator>=() [9/18]
XBuffer& operator>= (XBuffer & b, Vect3f & v)
 {
     b >= v.x >= v.y >= v.z;
     return b;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
operator>=() [10/18]
XStream& operator>= (XStream & s, Mat3d & m)
 {
     s >= m.xx >= m.xy >= m.xz;
     s >= m.yx >= m.yy >= m.yz;
     s >= m.zx >= m.zy >= m.zz;
     return s;
 }
operator>=() [11/18]
XStream& operator>= (XStream & s, Mat3f & m)
 {
     s >= m.xx >= m.xy >= m.xz;
     s >= m.yx >= m.yy >= m.yz;
     s >= m.zx >= m.zy >= m.zz;
     return s;
 }
operator>=() [12/18]
XStream& operator>= (XStream & s, QuatD & q)
 {
     s >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return s;
 }
operator>=() [13/18]
XStream& operator>= (XStream & s, QuatF & q)
 {
     s >= q.s_ >= q.x_ >= q.y_ >= q.z_;
     return s;
 }
operator>=() [14/18]
XStream& operator>= (XStream & s, Vect2f & v)
 {
     s >= v.x >= v.y;
     return s;
 }
References Vect2f::x, and Vect2f::y.
operator>=() [15/18]
XStream& operator>= (XStream & s, Vect2i & v)
 {
     s >= v.x >= v.y;
     return s;
 }
References Vect2i::x, and Vect2i::y.
operator>=() [16/18]
XStream& operator>= (XStream & s, Vect2s & v)
 {
     s >= v.x >= v.y;
     return s;
 }
References Vect2s::x, and Vect2s::y.
operator>=() [17/18]
XStream& operator>= (XStream & s, Vect3d & v)
 {
     s >= v.x >= v.y >= v.z;
     return s;
 }
References Vect3d::x, Vect3d::y, and Vect3d::z.
operator>=() [18/18]
XStream& operator>= (XStream & s, Vect3f & v)
 {
     s >= v.x >= v.y >= v.z;
     return s;
 }
References Vect3f::x, Vect3f::y, and Vect3f::z.
Slerp()
QuatD Slerp (const QuatD & A, const QuatD & B, double t)
 {
     double theta = acos(dot(A,B));
     double sin_theta = sin(theta);
     if(fabs(sin_theta) < DBL_EPS)
         return A;
     sin_theta = 1/sin_theta;
     return A*(sin(theta*(1 - t))*sin_theta) + B*(sin(theta* t)*sin_theta);
 }
References DBL_EPS, and dot().
Referenced by Object::update_coord().
Variable Documentation
xm_random_generator
RandomGenerator xm_random_generator
Referenced by fabsRnd(), frnd(), and random().