Vangers: lib/xtool/xrecorder/xrec.cpp File Reference
xrec.cpp File Reference
#include "xglobal.h"
Macros
#define XREC_MAX_CMESSAGE 3
#define XREC_MAX_IMESSAGE 3
Functions
int xtDispatchMessage (SDL_Event *msg)
void xtProcessMessageBuffer (void)
void xtSysQuant (void)
Variables
XRecorder XRec
Macro Definition Documentation
XREC_MAX_CMESSAGE
#define XREC_MAX_CMESSAGE 3
XREC_MAX_IMESSAGE
#define XREC_MAX_IMESSAGE 3
Function Documentation
xtDispatchMessage()
int xtDispatchMessage (SDL_Event * msg)
 {
     int ret = 0;
     xtMsgHandlerObject* p = XSysHandlerLst.first();
     while(p){
         (*p -> Handler)(msg);
         p = p -> next;
     }
     ret += xtCallXKey(msg);
     switch(msg -> type){
         case SDL_QUIT:
             xtSetExit();
             break;
         case SDL_WINDOWEVENT:
             switch (msg->window.event) {
                 case SDL_WINDOWEVENT_SHOWN:
                     //Pause = 0;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 0);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window show"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_HIDDEN:
                     //Pause = 1;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 1);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window hidden"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_RESTORED:
                     //Pause = 0;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 0);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window restored"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_FOCUS_LOST:
                     //Pause = 1;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 1);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window focus lost"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_FOCUS_GAINED:
                     //Pause = 0;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 0);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window focus gained"<<std::endl;
                     break;
             }
             break;
     }
     return ret;
 }
References XSysHandlerLst.
Referenced by XRecorder::DispatchMessage(), xtClearMessageQueue(), and xtProcessMessageBuffer().
xtProcessMessageBuffer()
void xtProcessMessageBuffer (void)
 {
     SDL_Event event;
     while(XMsgBuf -> get(&event)) {
         if(!(XRec.flags & XRC_PLAY_MODE) || XRec.CheckMessage(event.type)){
             xtDispatchMessage(&event);
 //          if(!xtDispatchMessage(&event))
 //              DispatchMessage(&event);
         }
     }
 }
References XRecorder::CheckMessage(), XRecorder::flags, XMsgBuf, XRC_PLAY_MODE, XRec, and xtDispatchMessage().
Referenced by XRecorder::Quant().
xtSysQuant()
void xtSysQuant (void)
 {
     XSysObject* p = (XSysObject*)XSysQuantLst.fPtr;
     while(p){
         (*(XFNC)(p -> QuantPtr))();
         p = (XSysObject*)p -> next;
     }
 }
Referenced by XRecorder::Quant().
Variable Documentation
XRec
XRecorder XRec
Referenced by aciML_Dispatcher::event_quant(), main(), aciML_Dispatcher::startup(), XGR_MouseFnc(), xtClearMessageQueue(), xtInitApplication(), and xtProcessMessageBuffer().