Vangers: lib/xtool/xtcore.cpp File Reference
xtcore.cpp File Reference
#include "../../src/lang.h"
#include "xglobal.h"
#include "xt_list.h"
#include "../xgraph/xgraph.h"
Classes
struct xtMsgHandlerObject
Macros
#define XT_DEFAULT_TABLE_SIZE 32
Typedefs
typedef void(* XFNC) ()
Functions
void xtSetExit (void)
int xtCallXKey (SDL_Event *m)
void xtSysQuant (void)
void xtAddSysObj (XList *lstPtr, void(*fPtr)(void), int id)
void xtDeleteSysObj (XList *lstPtr, int id)
void xtDeactivateSysObj (XList *lstPtr, int id)
void xtReadConsoleInput (void)
void xtRegisterSysMsgFnc (void(*fPtr)(SDL_Event *), int id)
void xtRegisterSysFinitFnc (void(*fPtr)(void), int id)
void xtUnRegisterSysFinitFnc (int id)
void xtDeactivateSysFinitFnc (int id)
void xtSysFinit (void)
int xtDispatchMessage (SDL_Event *msg)
void xtProcessMessageBuffer (void)
int main (int argc, char *argv[])
void xtCreateRuntimeObjectTable (int len)
XRuntimeObject * xtGetRuntimeObject (unsigned int id)
void xtRegisterRuntimeObject (XRuntimeObject *p)
void xtRegisterSysQuant (void(*qPtr)(void), int id)
void xtUnRegisterSysQuant (int id)
void xtClearMessageQueue (void)
void win32_break (char *error, char *msg)
void * xtGet_hInstance (void)
void * xtGet_hWnd (void)
void xtSet_hWnd (void *hWnd)
void xtSysQuantDisable (int v)
void set_key_nadlers (void(*pH)(SDL_Event *), void(*upH)(SDL_Event *))
Variables
int __internal_argc
char ** __internal_argv
XRuntimeObject ** XRObjTable = NULL
unsigned int XRObjTableSize = 0
XRuntimeObject * XRObjFirst = NULL
XRuntimeObject * XRObjLast = NULL
const char * XToolClassName = "XToolClass"
const char * XToolWndName = "XToolWindow"
void * XAppHinst = NULL
void * XGR_hWnd = NULL
void * hXConOutput = NULL
void * hXConInput = NULL
int XAppMode = 0
void(* press_handler)(SDL_Event *m)
void(* unpress_handler)(SDL_Event *m)
XList XSysQuantLst
XList XSysFinitLst
xtList< xtMsgHandlerObject > XSysHandlerLst
double XTCORE_FRAME_DELTA = 0
double XTCORE_FRAME_NORMAL = 0
int xtSysQuantDisabled = 0
bool XGR_FULL_SCREEN
int Pause
Macro Definition Documentation
XT_DEFAULT_TABLE_SIZE
#define XT_DEFAULT_TABLE_SIZE 32
Typedef Documentation
XFNC
typedef void(* XFNC) ()
Function Documentation
main()
int main (int argc, char * argv[])
 {
 #ifdef __HAIKU__
     const char *data_dir = getenv("VANGERS_DATA");
     if(data_dir != NULL){
         chdir(data_dir);
     }
 #endif
     int id, prevID, clockDelta, clockCnt, clockNow, clockCntGlobal, clockNowGlobal;
     XRuntimeObject* XObj;
     __internal_argc = argc;
     __internal_argv = argv;
     #ifdef _WIN32
         std::cout<<"Load backtrace"<<std::endl;
         LoadLibraryA("backtrace.dll");
         std::cout<<"Set priority class"<<std::endl;
         SetPriorityClass(GetCurrentProcess(), HIGH_PRIORITY_CLASS);
         putenv("SDL_AUDIODRIVER=DirectSound");
     #endif
     for (int i = 1; i < argc; i++) {
         std::string cmd_key = argv[i];
         if (cmd_key == "-fullscreen")
             XGR_FULL_SCREEN = true;
         else if (cmd_key == "-russian")
             setLang(RUSSIAN);
     }
 #if defined(__unix__) || defined(__linux__) || defined(__APPLE__)
     std::cout<<"Set locale. ";
     char* res = setlocale(LC_NUMERIC, "POSIX");
     std::cout<<"Result:"<<res<<std::endl;
 #endif
     //Set handlers to null
     press_handler = NULL;
     unpress_handler = NULL;
     XMsgBuf = new XMessageBuffer;
     initclock();
     prevID = 0;
     id = xtInitApplication();
     XObj = xtGetRuntimeObject(id);
 #ifdef _RTO_LOG_
     if(XRec.flags & XRC_PLAY_MODE)
         xtRTO_Log.open("xt_rto_p.log",XS_OUT);
     else
         xtRTO_Log.open("xt_rto_w.log",XS_OUT);
 #endif
     while(XObj){
         XObj -> Init(prevID);
         prevID = id;
         id = 0;
         clockCnt = clocki();
         clockCntGlobal = clockCnt;
         while(!id) {
             if(XObj->Timer) {
                 id = XObj -> Quant();
                 clockNow = clockNowGlobal = clocki();
                 clockDelta = clockNow - clockCnt;
                 XTCORE_FRAME_DELTA = (clockNowGlobal - clockCntGlobal) / 1000.0;
                 XTCORE_FRAME_NORMAL = XTCORE_FRAME_DELTA / 0.050; //20FPS
                 clockCntGlobal = clockNowGlobal;
 //              std::cout<<"XTCORE_FRAME_DELTA:"<<XTCORE_FRAME_DELTA
 //                       <<" XTCORE_FRAME_NORMAL:"<<XTCORE_FRAME_NORMAL
 //                       <<" clockDelta:"<<clockDelta<<std::endl;
                 if (clockDelta < XObj->Timer) {
                     SDL_Delay(XObj->Timer - clockDelta);
                 } else {
                     std::cout<<"Strange deltas clockDelta:"<<clockDelta<<" Timer:"<<XObj->Timer<<std::endl;
                     if (clockDelta > 300) {
                         // something wrong and for preventing abnormal physics set something neutral
                         XTCORE_FRAME_NORMAL = 1.0;
                     }
                 }
                 clockCnt = clocki();
             } else {
                 id = XObj -> Quant();
             }
             if(!xtSysQuantDisabled)
                 XRec.Quant(); // впускает внешние события, записывает их или воспроизводит
             XGR_Flip();
         }
         XObj -> Finit();
 #ifdef _RTO_LOG_
         xtRTO_Log < "\r\nChange RTO: " <= XObj -> ID < " -> " <= id < " frame -> " <= XRec.frameCount;
 #endif
         XObj = xtGetRuntimeObject(id);
     }
     xtDoneApplication();
     xtSysFinit();
 #ifdef _RTO_LOG_
     xtRTO_Log.close();
 #endif
     return 0;
 }
References __internal_argc, __internal_argv, clocki(), XStream::close(), XRecorder::flags, XRecorder::frameCount, initclock(), NULL, XStream::open(), press_handler, XRecorder::Quant(), RUSSIAN, setLang(), XRuntimeObject::Timer, unpress_handler, XGR_Flip, XGR_FULL_SCREEN, XMsgBuf, XRC_PLAY_MODE, XRec, XS_OUT, XTCORE_FRAME_DELTA, XTCORE_FRAME_NORMAL, xtDoneApplication(), xtGetRuntimeObject(), xtInitApplication(), xtSysFinit(), and xtSysQuantDisabled.
set_key_nadlers()
void set_key_nadlers (void(*)(SDL_Event *) pH, void(*)(SDL_Event *) upH)
{
     press_handler = pH;
     unpress_handler = upH;
 }
References press_handler, and unpress_handler.
Referenced by LoadingRTO1::Init(), ShowImageRTO::Init(), iScrQuantFinit(), and KBD_init().
win32_break()
void win32_break (char * error, char * msg)
 {
     std::cout<<"--------------------------------\n";
     std::cout<<error<<"\n";
     std::cout<<msg<<"\n";
     std::cout<<"--------------------------------\n";
 }
xtAddSysObj()
void xtAddSysObj (XList * lstPtr, void(*)(void) fPtr, int id)
 {
     XSysObject* p = (XSysObject*)lstPtr -> fPtr;
     while(p){
         if(p -> ID == id) return;
         p = (XSysObject*)p -> next;
     }
     p = new XSysObject;
     p -> ID = id;
     p -> QuantPtr = (void*)fPtr;
     lstPtr -> AddElement((XListElement*)p);
 }
Referenced by xtRegisterSysFinitFnc(), and xtRegisterSysQuant().
xtCallXKey()
int xtCallXKey (SDL_Event * m)
{
     switch(m->type) {
         case SDL_KEYDOWN:
             if (press_handler) {
                 (*press_handler)(m);
             }
             break;
         case SDL_KEYUP:
             if (unpress_handler) {
                 (*unpress_handler)(m);
             }
             break;
         case SDL_TEXTINPUT:
             if (press_handler) {
                 (*press_handler)(m);
             }
             break;
         case SDL_JOYBUTTONDOWN:
             //std::cout<<"jevent down button:"<<(int)m->jbutton.button<<std::endl;
             if (press_handler) {
                 (*press_handler)(m);
             }
             break;
         case SDL_JOYBUTTONUP:
             //std::cout<<"jevent up"<<std::endl;
             if (unpress_handler) {
                 (*unpress_handler)(m);
             }
             break;
         case SDL_CONTROLLERBUTTONDOWN:
             //std::cout<<"CONTROLLERBUTTONDOWN"<<std::endl;
             if (press_handler) {
                 (*press_handler)(m);
             }
             break;
         case SDL_CONTROLLERBUTTONUP:
             //std::cout<<"CONTROLLERBUTTONUP"<<std::endl;
             if (unpress_handler) {
                 (*unpress_handler)(m);
             }
             break;
         case SDL_JOYHATMOTION:
             //std::cout<<"SDL_JOYHATMOTION:"<<(int)m->jhat.hat<<" value"<<(int)m->jhat.value<<" k:"<<std::endl;
             if (press_handler) {
                 (*press_handler)(m);
             }
             break;
         case SDL_JOYBALLMOTION:
             //std::cout<<"SDL_JOYBALLMOTION:"<<(int)m->jball.ball<<" xrel:"<<m->jball.xrel<<" yrel:"<<m->jball.yrel<<std::endl;
             break;
         case SDL_JOYAXISMOTION:
             //std::cout<<"SDL_JOYAXISMOTION:"<<(int)m->jaxis.axis<<" value"<<m->jaxis.value<<std::endl;
             break;
     }
     return 1;
 }
References press_handler, and unpress_handler.
xtClearMessageQueue()
void xtClearMessageQueue (void)
 {
     SDL_Event event;
     while(SDL_PollEvent(&event)) {
         //std::cout<<"event "<<event.type<<std::endl;
         if(XRec.CheckMessage(event.type)) {
             xtDispatchMessage(&event);
 //          if(!xtDispatchMessage(&event))
 //              DispatchMessage(&event);
         } else {
             XMsgBuf -> put(&event);
         }
     }
 }
References XRecorder::CheckMessage(), XMsgBuf, XRec, and xtDispatchMessage().
Referenced by aciCancelMatrix(), aciCloseGate(), aciHideLocation(), aciOpenGate(), aciShowLocation(), aciShowScMatrix(), aciSwapMatrices(), LoadingRTO3::Init(), XGR_Screen::init(), iScreenDispatcher::move_screen(), PalEvidence(), PalSlake(), and XRecorder::Quant().
xtCreateRuntimeObjectTable()
void xtCreateRuntimeObjectTable (int len)
 {
     int i;
     if(!len) len = XT_DEFAULT_TABLE_SIZE;
     XRObjTableSize = len;
     XRObjTable = new XRuntimeObject*[len];
     for(i = 0; i < len; i ++){
         XRObjTable[i] = NULL;
     }
 }
References NULL, XRObjTable, XRObjTableSize, and XT_DEFAULT_TABLE_SIZE.
Referenced by xtInitApplication().
xtDeactivateSysFinitFnc()
void xtDeactivateSysFinitFnc (int id)
 {
     xtDeactivateSysObj(&XSysFinitLst,id);
 }
References XSysFinitLst, and xtDeactivateSysObj().
Referenced by XGR_Screen::close(), and XGR_Screen::finit().
xtDeactivateSysObj()
void xtDeactivateSysObj (XList * lstPtr, int id)
 {
     XSysObject* p = (XSysObject*)lstPtr -> fPtr;
     while(p){
         if(p -> ID == id)
             p -> flags |= XSYS_OBJ_INACTIVE;
         p = (XSysObject*)p -> next;
     }
 }
Referenced by xtDeactivateSysFinitFnc().
xtDeleteSysObj()
void xtDeleteSysObj (XList * lstPtr, int id)
 {
     XSysObject* p = (XSysObject*)lstPtr -> fPtr;
     while(p){
         if(p -> ID == id){
             lstPtr -> RemoveElement((XListElement*)p);
             delete p;
             return;
         }
         p = (XSysObject*)p -> next;
     }
 }
Referenced by xtUnRegisterSysFinitFnc(), and xtUnRegisterSysQuant().
xtDispatchMessage()
int xtDispatchMessage (SDL_Event * msg)
 {
     int ret = 0;
     xtMsgHandlerObject* p = XSysHandlerLst.first();
     while(p){
         (*p -> Handler)(msg);
         p = p -> next;
     }
     ret += xtCallXKey(msg);
     switch(msg -> type){
         case SDL_QUIT:
             xtSetExit();
             break;
         case SDL_WINDOWEVENT:
             switch (msg->window.event) {
                 case SDL_WINDOWEVENT_SHOWN:
                     //Pause = 0;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 0);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window show"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_HIDDEN:
                     //Pause = 1;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 1);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window hidden"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_RESTORED:
                     //Pause = 0;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 0);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window restored"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_FOCUS_LOST:
                     //Pause = 1;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 1);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window focus lost"<<std::endl;
                     break;
                 case SDL_WINDOWEVENT_FOCUS_GAINED:
                     //Pause = 0;
                     SDL_LockAudioDevice(1);
                     SDL_PauseAudioDevice(1, 0);
                     SDL_UnlockAudioDevice(1);
                     std::cout<<"window focus gained"<<std::endl;
                     break;
             }
             break;
     }
     return ret;
 }
References XSysHandlerLst.
Referenced by XRecorder::DispatchMessage(), xtClearMessageQueue(), and xtProcessMessageBuffer().
xtGet_hInstance()
void* xtGet_hInstance (void)
 {
     return XAppHinst;
 }
References XAppHinst.
xtGet_hWnd()
void* xtGet_hWnd (void)
 {
     return XGR_hWnd;
 }
References XGR_hWnd.
xtGetRuntimeObject()
XRuntimeObject* xtGetRuntimeObject (unsigned int id)
 {
     if(id == XT_TERMINATE_ID)
         return NULL;
     if(!XRObjTable || !XRObjTableSize || id < 1 || id > XRObjTableSize)
         ErrH.Abort("XTool system error...");
     return XRObjTable[id - 1];
 }
References XErrorHandler::Abort(), ErrH, NULL, XRObjTable, XRObjTableSize, and XT_TERMINATE_ID.
Referenced by aciInitEndGame(), aciPrepareEndImage(), aciTextQuant(), GameTimerON_OFF(), LoadingRTO3::Init(), main(), rtoClearFlag(), rtoSetFlag(), and xtInitApplication().
xtProcessMessageBuffer()
void xtProcessMessageBuffer (void)
 {
     SDL_Event event;
     while(XMsgBuf -> get(&event)) {
         if(!(XRec.flags & XRC_PLAY_MODE) || XRec.CheckMessage(event.type)){
             xtDispatchMessage(&event);
 //          if(!xtDispatchMessage(&event))
 //              DispatchMessage(&event);
         }
     }
 }
References XRecorder::CheckMessage(), XRecorder::flags, XMsgBuf, XRC_PLAY_MODE, XRec, and xtDispatchMessage().
Referenced by XRecorder::Quant().
xtReadConsoleInput()
void xtReadConsoleInput (void)
xtRegisterRuntimeObject()
void xtRegisterRuntimeObject (XRuntimeObject * p)
 {
     if(!XRObjFirst){
         XRObjFirst = XRObjLast = p;
     }
     else {
         XRObjLast -> next = p;
         XRObjLast = p;
     }
     XRObjTable[p -> ID - 1] = p;
 }
References XRObjFirst, and XRObjLast.
Referenced by xtInitApplication().
xtRegisterSysFinitFnc()
void xtRegisterSysFinitFnc (void(*)(void) fPtr, int id)
 {
     xtAddSysObj(&XSysFinitLst,fPtr,id);
 }
References XSysFinitLst, and xtAddSysObj().
xtRegisterSysMsgFnc()
void xtRegisterSysMsgFnc (void(*)(SDL_Event *) fPtr, int id)
 {
     xtMsgHandlerObject* p = new xtMsgHandlerObject(fPtr,id);
     XSysHandlerLst.append(p);
 }
References XSysHandlerLst.
xtRegisterSysQuant()
void xtRegisterSysQuant (void(*)(void) qPtr, int id)
 {
     xtAddSysObj(&XSysQuantLst,qPtr,id);
 }
References XSysQuantLst, and xtAddSysObj().
xtSet_hWnd()
void xtSet_hWnd (void * hWnd)
 {
     XGR_hWnd = hWnd;
 }
References XGR_hWnd.
xtSetExit()
void xtSetExit (void)
 {
     std::cout<<"Exit!"<<std::endl;
     SDL_Quit();
     exit(0);
 //  ResetEvent(hXActiveWndEvent);
 //  SetEvent(hXNeedExitEvent);
 };
xtSysFinit()
void xtSysFinit (void)
 {
     int i,sz = XSysFinitLst.ListSize;
     XSysObject* p = (XSysObject*)XSysFinitLst.lPtr;
     for(i = 0; i < sz; i ++){
         if(!(p -> flags & XSYS_OBJ_INACTIVE))
             (*(XFNC)(p -> QuantPtr))();
         p = (XSysObject*)p -> prev;
     }
     XRec.Close();
 }
References XList::ListSize, XList::lPtr, and XSysFinitLst.
Referenced by main().
xtSysQuant()
void xtSysQuant (void)
 {
     XSysObject* p = (XSysObject*)XSysQuantLst.fPtr;
     while(p){
         (*(XFNC)(p -> QuantPtr))();
         p = (XSysObject*)p -> next;
     }
 }
References XList::fPtr, and XSysQuantLst.
Referenced by XRecorder::Quant().
xtSysQuantDisable()
void xtSysQuantDisable (int v)
 {
     xtSysQuantDisabled = v;
 }
References xtSysQuantDisabled.
xtUnRegisterSysFinitFnc()
void xtUnRegisterSysFinitFnc (int id)
 {
     xtDeleteSysObj(&XSysFinitLst,id);
 }
References XSysFinitLst, and xtDeleteSysObj().
xtUnRegisterSysQuant()
void xtUnRegisterSysQuant (int id)
 {
     xtDeleteSysObj(&XSysQuantLst,id);
 }
References XSysQuantLst, and xtDeleteSysObj().
Variable Documentation
__internal_argc
int __internal_argc
Referenced by main(), and xtInitApplication().
__internal_argv
char** __internal_argv
Referenced by main(), and xtInitApplication().
hXConInput
void* hXConInput = NULL
hXConOutput
void* hXConOutput = NULL
Pause
int Pause extern
press_handler
void(* press_handler) (SDL_Event *m)
Referenced by main(), set_key_nadlers(), and xtCallXKey().
unpress_handler
void(* unpress_handler) (SDL_Event *m)
Referenced by main(), set_key_nadlers(), and xtCallXKey().
XAppHinst
void* XAppHinst = NULL
Referenced by xtGet_hInstance().
XAppMode
int XAppMode = 0
XGR_FULL_SCREEN
bool XGR_FULL_SCREEN extern
Referenced by main().
XGR_hWnd
void* XGR_hWnd = NULL
Referenced by XGR_Screen::finit(), xtGet_hWnd(), and xtSet_hWnd().
XRObjFirst
XRuntimeObject* XRObjFirst = NULL
Referenced by xtRegisterRuntimeObject().
XRObjLast
XRuntimeObject* XRObjLast = NULL
Referenced by xtRegisterRuntimeObject().
XRObjTable
XRuntimeObject** XRObjTable = NULL
Referenced by xtCreateRuntimeObjectTable(), and xtGetRuntimeObject().
XRObjTableSize
unsigned int XRObjTableSize = 0
Referenced by xtCreateRuntimeObjectTable(), and xtGetRuntimeObject().
XSysFinitLst
XList XSysFinitLst
Referenced by xtDeactivateSysFinitFnc(), xtRegisterSysFinitFnc(), xtSysFinit(), and xtUnRegisterSysFinitFnc().
XSysHandlerLst
xtList<xtMsgHandlerObject> XSysHandlerLst
Referenced by xtDispatchMessage(), and xtRegisterSysMsgFnc().
XSysQuantLst
XList XSysQuantLst
Referenced by xtRegisterSysQuant(), xtSysQuant(), and xtUnRegisterSysQuant().
XTCORE_FRAME_DELTA
double XTCORE_FRAME_DELTA = 0
Referenced by main().
XTCORE_FRAME_NORMAL
double XTCORE_FRAME_NORMAL = 0
Referenced by camera_direct(), camera_quant(), main(), and InsectUnit::Quant().
XToolClassName
const char* XToolClassName = "XToolClass"
XToolWndName
const char* XToolWndName = "XToolWindow"
xtSysQuantDisabled
int xtSysQuantDisabled = 0
Referenced by main(), and xtSysQuantDisable().