Vangers: lib/xtool/xtcore.h File Reference
xtcore.h File Reference
#include <iostream>
#include <SDL.h>
Classes
struct XListElement
struct XList
struct XRuntimeObject
struct XSysObject
Macros
#define NULL 0L
#define XGRAPH_SYSOBJ_ID 0x01
#define XSOUND_SYSOBJ_ID 0x02
#define XAVI_SYSOBJ_ID 0x03
#define XD3D_SYSOBJ_ID 0x04
#define XT_TERMINATE_ID 0xFFFFFFFF
#define XSYS_OBJ_INACTIVE 0x01
#define SDLK_JOYSTICK_BUTTON_MASK (1<<28)
#define SDLK_GAMECONTROLLER_BUTTON_MASK (1<<27)
#define SDLK_JOYSTICK_HAT_MASK (1<<26)
Functions
void xtCreateRuntimeObjectTable (int len=0)
void xtRegisterRuntimeObject (XRuntimeObject *p)
XRuntimeObject * xtGetRuntimeObject (unsigned int id)
void xtRegisterSysQuant (void(*qPtr)(void), int id)
void xtUnRegisterSysQuant (int id)
void xtClearMessageQueue (void)
int xtInitApplication (void)
void xtDoneApplication (void)
void * xtGet_hInstance (void)
void * xtGet_hWnd (void)
void xtSet_hWnd (void *hWnd)
void xtSysQuantDisable (int v=1)
void xtSysQuant (void)
void xtCreateDummyWindow (int x=0, int y=0, int sx=100, int sy=100)
void xtCloseDummyWindow (void)
void set_key_nadlers (void(*pH)(SDL_Event *), void(*upH)(SDL_Event *))
Variables
void * XGR_hWnd
double XTCORE_FRAME_DELTA
double XTCORE_FRAME_NORMAL
Macro Definition Documentation
NULL
#define NULL 0L
SDLK_GAMECONTROLLER_BUTTON_MASK
#define SDLK_GAMECONTROLLER_BUTTON_MASK (1<<27)
SDLK_JOYSTICK_BUTTON_MASK
#define SDLK_JOYSTICK_BUTTON_MASK (1<<28)
SDLK_JOYSTICK_HAT_MASK
#define SDLK_JOYSTICK_HAT_MASK (1<<26)
XAVI_SYSOBJ_ID
#define XAVI_SYSOBJ_ID 0x03
XD3D_SYSOBJ_ID
#define XD3D_SYSOBJ_ID 0x04
XGRAPH_SYSOBJ_ID
#define XGRAPH_SYSOBJ_ID 0x01
XSOUND_SYSOBJ_ID
#define XSOUND_SYSOBJ_ID 0x02
XSYS_OBJ_INACTIVE
#define XSYS_OBJ_INACTIVE 0x01
XT_TERMINATE_ID
#define XT_TERMINATE_ID 0xFFFFFFFF
Function Documentation
set_key_nadlers()
void set_key_nadlers (void(*)(SDL_Event *) pH, void(*)(SDL_Event *) upH)
{
     press_handler = pH;
     unpress_handler = upH;
 }
References press_handler, and unpress_handler.
Referenced by LoadingRTO1::Init(), ShowImageRTO::Init(), iScrQuantFinit(), and KBD_init().
xtClearMessageQueue()
void xtClearMessageQueue (void)
 {
     SDL_Event event;
     while(SDL_PollEvent(&event)) {
         //std::cout<<"event "<<event.type<<std::endl;
         if(XRec.CheckMessage(event.type)) {
             xtDispatchMessage(&event);
 //          if(!xtDispatchMessage(&event))
 //              DispatchMessage(&event);
         } else {
             XMsgBuf -> put(&event);
         }
     }
 }
References XRecorder::CheckMessage(), XMsgBuf, XRec, and xtDispatchMessage().
Referenced by aciCancelMatrix(), aciCloseGate(), aciHideLocation(), aciOpenGate(), aciShowLocation(), aciShowScMatrix(), aciSwapMatrices(), LoadingRTO3::Init(), XGR_Screen::init(), iScreenDispatcher::move_screen(), PalEvidence(), PalSlake(), and XRecorder::Quant().
xtCloseDummyWindow()
void xtCloseDummyWindow (void)
xtCreateDummyWindow()
void xtCreateDummyWindow (int x = 0, int y = 0, int sx = 100, int sy = 100)
xtCreateRuntimeObjectTable()
void xtCreateRuntimeObjectTable (int len = 0)
 {
     int i;
     if(!len) len = XT_DEFAULT_TABLE_SIZE;
     XRObjTableSize = len;
     XRObjTable = new XRuntimeObject*[len];
     for(i = 0; i < len; i ++){
         XRObjTable[i] = NULL;
     }
 }
References NULL, XRObjTable, XRObjTableSize, and XT_DEFAULT_TABLE_SIZE.
Referenced by xtInitApplication().
xtDoneApplication()
void xtDoneApplication (void)
{
 }
References restore(), and server.
Referenced by main().
xtGet_hInstance()
void* xtGet_hInstance (void)
 {
     return XAppHinst;
 }
References XAppHinst.
xtGet_hWnd()
void* xtGet_hWnd (void)
 {
     return XGR_hWnd;
 }
References XGR_hWnd.
xtGetRuntimeObject()
XRuntimeObject* xtGetRuntimeObject (unsigned int id)
 {
     if(id == XT_TERMINATE_ID)
         return NULL;
     if(!XRObjTable || !XRObjTableSize || id < 1 || id > XRObjTableSize)
         ErrH.Abort("XTool system error...");
     return XRObjTable[id - 1];
 }
References XErrorHandler::Abort(), ErrH, NULL, XRObjTable, XRObjTableSize, and XT_TERMINATE_ID.
Referenced by aciInitEndGame(), aciPrepareEndImage(), aciTextQuant(), GameTimerON_OFF(), LoadingRTO3::Init(), main(), rtoClearFlag(), rtoSetFlag(), and xtInitApplication().
xtInitApplication()
int xtInitApplication (void)
{
     return 1;
 }
References __internal_argc, __internal_argv, _MEM_STATISTIC_, XErrorHandler::Abort(), actintLowResFlag, avaible_servers, AVInotFoundMSS, broadcast_port, XStream::close(), ComlineAnalyze(), costab(), Server::create_game(), default_server_port, emode, ErrH, ErrorVideoMss, ExclusiveLog, XTList< Type >::first(), GERMAN, host_name, host_port, ilandPrepare(), InstallSOUND(), JOYSTICK_Joystick, JoystickMode, lang(), LoadingMessage(), LoadResourceSOUND(), NetInit(), nVER, XRecorder::Open(), palTr, preCALC(), XStream::read(), realRNDVAL, RecorderMode, RecorderName, result_name, RNDVAL, roadFNTname, RTO_GAME_QUANT_ID, RTO_MAIN_MENU_ID, RTO_MAX_ID, RUSSIAN, server, ShowImageRTO::SetName(), ShowImageRTO::SetNumFiles(), SetSoundVolume(), setTimerLog, SetupPath(), XStream::size(), SkipIntro, speed_correction_enabled, sysfont, ServersList::talk_to_server(), time_to_live, VERSION, videoMode, XGR_EXCLUSIVE, XGR_Fill, XGR_Init, XGraphWndID, XJoystickInit(), XRec, XS_IN, XSocketInit(), xtCreateRuntimeObjectTable(), xtGetRuntimeObject(), xtRegisterRuntimeObject(), zchatFNTname, and zchatfont.
Referenced by main().
xtRegisterRuntimeObject()
void xtRegisterRuntimeObject (XRuntimeObject * p)
 {
     if(!XRObjFirst){
         XRObjFirst = XRObjLast = p;
     }
     else {
         XRObjLast -> next = p;
         XRObjLast = p;
     }
     XRObjTable[p -> ID - 1] = p;
 }
References XRObjFirst, and XRObjLast.
Referenced by xtInitApplication().
xtRegisterSysQuant()
void xtRegisterSysQuant (void(*)(void) qPtr, int id)
 {
     xtAddSysObj(&XSysQuantLst,qPtr,id);
 }
References XSysQuantLst, and xtAddSysObj().
xtSet_hWnd()
void xtSet_hWnd (void * hWnd)
 {
     XGR_hWnd = hWnd;
 }
References XGR_hWnd.
xtSysQuant()
void xtSysQuant (void)
 {
     XSysObject* p = (XSysObject*)XSysQuantLst.fPtr;
     while(p){
         (*(XFNC)(p -> QuantPtr))();
         p = (XSysObject*)p -> next;
     }
 }
References XList::fPtr, and XSysQuantLst.
xtSysQuantDisable()
void xtSysQuantDisable (int v = 1)
 {
     xtSysQuantDisabled = v;
 }
References xtSysQuantDisabled.
xtUnRegisterSysQuant()
void xtUnRegisterSysQuant (int id)
 {
     xtDeleteSysObj(&XSysQuantLst,id);
 }
References XSysQuantLst, and xtDeleteSysObj().
Variable Documentation
XGR_hWnd
void* XGR_hWnd extern
XTCORE_FRAME_DELTA
double XTCORE_FRAME_DELTA extern
Referenced by main().
XTCORE_FRAME_NORMAL
double XTCORE_FRAME_NORMAL extern
Referenced by camera_direct(), camera_quant(), main(), and InsectUnit::Quant().