Vangers: lib/xtool/xzip.h File Reference
xzip.h File Reference
Functions
unsigned int ZIP_compress (char *trg, unsigned int trgsize, char *src, unsigned int srcsize)
unsigned int ZIP_GetExpandedSize (char *p)
void ZIP_expand (char *trg, unsigned int trgsize, char *src, unsigned int srcsize)
Function Documentation
ZIP_compress()
unsigned int ZIP_compress (char * trg, unsigned int trgsize, char * src, unsigned int srcsize)
 {
     ushort att = (ushort)UNKNOWN;
     ushort flags = 0;
     int method = DEFLATE;
     read_buf = mem_read;
     in_buf = src;
     in_size = (unsigned)srcsize;
     in_offset = 0;
     out_buf = trg;
     out_size = (unsigned)trgsize;
     out_offset = 2 + 4;
     window_size = 0L;
     if(out_size <= 6) return 0;
     bi_init();
     ct_init(&att,&method);
     lm_init((level != 0 ? level : 1),&flags);
     deflate();
     free_data();
     window_size = 0L;
     trg[0] = (char)(method & 0xFF);
     trg[1] = (char)((method >> 8) & 0xFF);
     *(unsigned int*)(trg + 2) = (unsigned int)srcsize;
     return (unsigned int)out_offset;
 }
References UNKNOWN.
Referenced by ScriptFile::close_bscript().
ZIP_expand()
void ZIP_expand (char * trg, unsigned int trgsize, char * src, unsigned int srcsize)
 {
     unsigned short method;
     outbuf = new uchar[OUTBUFSIZ + 1];
     slide = new uchar[WSIZE];
     method = *(short*)(src);
     mem_i_buffer = (uchar*)src + 2 + 4;
     mem_i_size   = srcsize - 2 - 4;
     mem_i_offset = 0;
     mem_o_buffer = (uchar*)trg;
     mem_o_size   = trgsize;
     mem_o_offset = 0;
     bits_left = 0;
     bitbuf = 0L;
     outpos = 0L;
     outcnt = 0;
     outptr = outbuf;
     zipeof = 0;
     memset(outbuf,0xAA,OUTBUFSIZ);
     switch (method) {
         case STORE:
             memcpy(trg,src + 2 + 4,(unsigned)(srcsize - 2 - 4));
         break;
         case DEFLATE:
             inflate();
             FlushOutput();
             break;
         default:
             break;
     }
     delete outbuf;
     delete slide;
 }
References outbuf, OUTBUFSIZ, slide, and WSIZE.
Referenced by main().
ZIP_GetExpandedSize()
unsigned int ZIP_GetExpandedSize (char * p)
 {
     return *(unsigned int*)(p + 2);
 }
Referenced by main().