Vangers: lib/xtool/xutl.h File Reference
xutl.h File Reference
Macros
#define XALLOC(a) xalloc(a)
#define XREALLOC(a, b) xrealloc(a,b)
#define XFREE(a) xfree(a)
#define M_PI 3.14159265358979323846
#define __ROUND__
Functions
void * xalloc (unsigned sz)
void * xrealloc (void *p, unsigned sz)
void xfree (void *p)
void XRndSet (unsigned int m)
unsigned int XRndGet ()
char * XFindNext (void)
char * XFindFirst (char *mask)
template<class T >
T sqr (const T &x)
template<class T >
int SIGN (const T &x)
bool IsPowerOf2 (int x)
int BitSR (int x)
void initclock (void)
int clocki (void)
double clockf (void)
void xtDeleteFile (char *fname)
Macro Definition Documentation
__ROUND__
#define __ROUND__
M_PI
#define M_PI 3.14159265358979323846
XALLOC
#define XALLOC (a) xalloc(a)
XFREE
#define XFREE (a) xfree(a)
XREALLOC
#define XREALLOC (a, b) xrealloc(a,b)
Function Documentation
BitSR()
int BitSR (int x) inline
{
     unsigned int a = abs(x);
     for (int i = 31; i > 0; i--)
         if (a & (1 << i))
             return i;
     return 0;
 }
Referenced by Object::destroy_double_level(), Object::draw(), Object::ground_pressing(), Object::pixel_draw(), register_color(), Sqrt(), and XIQueue< Type >::XIQueue().
clockf()
double clockf (void)
 {
 //std::cout<<"clockf() "<<(double)(getRDTSC()-beg_tick)/(double)tick_per_sec<<std::endl;
 //  return (double)(getRDTSC()-beg_tick)/(double)tick_per_sec;
     return (double)SDL_GetTicks()*MS_PER_PERIOD;
 }
References MS_PER_PERIOD.
clocki()
int clocki (void)
 {
 //std::cout<<"clocki() "<<(int)((getRDTSC()-beg_tick)/tick_per_sec)<<std::endl;
 //  return (int)((getRDTSC()-beg_tick)/tick_per_sec);
 //  return (int)((getRDTSC()-beg_tick)*1000);
     return (SDL_GetTicks()*MS_PER_PERIOD);
 }
References MS_PER_PERIOD.
Referenced by main().
initclock()
void initclock (void)
 {
     if(tick_per_sec!=0)
         return;
 /*  clock_t t1,t2;
     __int64 tickb,ticke;
     t1=t2=clock();
     while(t1==t2){
         t2=clock();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+1000 > t2){
         t2=clock();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/1000;
     beg_tick=getRDTSC();
 */
 //  timeBeginPeriod(1);
 /*  unsigned int t1,t2;
     __int64 tickb,ticke;
     t1=t2=timeGetTime();
     while(t1==t2){
         t2=timeGetTime();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+MS_PER_PERIOD > t2){
         t2=timeGetTime();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/MS_PER_PERIOD;
     beg_tick=getRDTSC();
     */
     /*WORKunsigned int t1,t2;
     long long tickb,ticke;
     t1=t2=getRDTSC();
     while(t1==t2){
         t2=getRDTSC();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+MS_PER_PERIOD > t2){
         t2=getRDTSC();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/MS_PER_PERIOD;*/
     beg_tick=getRDTSC();
 std::cout<<"initclock() "<<tick_per_sec<<" b:"<<beg_tick<<std::endl;
 //  timeEndPeriod(1);
 /*  LARGE_INTEGER TK_PER_SEC;
     QueryPerformanceFrequency(&TK_PER_SEC);
     __int64 t1,t2;
     __int64 tickb,ticke;
     t1=t2=getQPC();
     while(t1==t2){
         t2=getQPC();
     };
     tickb=getRDTSC();
     t1=t2;
     while(t1+TK_PER_SEC.QuadPart > t2){
         t2=getQPC();
     }
     ticke=getRDTSC();
     tick_per_sec = (ticke-tickb)/1000;//MS_PER_SEC;
     beg_tick=getRDTSC();*/
 }
References beg_tick, getRDTSC(), and tick_per_sec.
Referenced by main().
IsPowerOf2()
bool IsPowerOf2 (int x) inline
 {
     return (x) && !(x & (x - 1));
 }
Referenced by XQueue< Type >::XQueue().
SIGN()
template<class T > int SIGN (const T & x) inline
 { return x ? (x > 0 ? 1 : -1 ) : 0; }
sqr()
template<class T > T sqr (const T & x) inline
 { return x*x; }
xalloc()
void* xalloc (unsigned sz)
XFindFirst()
char* XFindFirst (char * mask)
XFindNext()
char* XFindNext (void)
xfree()
void xfree (void * p)
xrealloc()
void* xrealloc (void * p, unsigned sz)
XRndGet()
unsigned int XRndGet ()
XRndSet()
void XRndSet (unsigned int m)
xtDeleteFile()
void xtDeleteFile (char * fname)